### ISSUE TITLE
Functional tests failing on the CI

### ISSUE THREAD

**Issue by jbagga** [dotnet/efcore#7982] opened 2017-03-24 18:19 UTC
The following tests are failing on the CI

- SqliteScaffoldingModelFactoryTest.It_loads_default_values
[Details](http://aspnetci/project.html?projectId=XPlat&testNameId=-7020909974607453548&tab=testDetails)

- SqliteScaffoldingModelFactoryTest.It_assigns_uniqueness_to_composite_foreign
[Details](http://aspnetci/project.html?projectId=XPlat&testNameId=4003493612089367827&tab=testDetails)

- SqliteScaffoldingModelFactoryTest.It_assigns_uniqueness_to_pk_foreign_key
[Details](http://aspnetci/project.html?projectId=XPlat&testNameId=1138814809839697204&tab=testDetails)

- SqliteConnectionTest.EnableExtensions_works
[Details](http://aspnetci/project.html?projectId=XPlat&testNameId=-1721692031195498021&tab=testDetails)

- SqliteAllFluentApiE2ETest.Missing_primary_key
[Details](http://aspnetci/project.html?projectId=XPlat&testNameId=-5253440610789403477&tab=testDetails)

@bricelam

**Comment by bricelam** [comment] 2017-03-24 19:07
Possibly due to undisposed command objects in our testing infrastructure

**Comment by bricelam** [comment] 2017-03-24 19:08
`SqliteConnectionTest.EnableExtensions_works` has been flaky on AppVeyor too. Can probably just remove the test or add some retries.

**Comment by bricelam** [comment] 2017-03-24 19:10
> due to undisposed command objects

This isn't supposed to matter if the connection gets disposed, but there might be a bug...

**Comment by bricelam** [comment] 2017-03-24 19:13
@smitpatel feel free to revert https://github.com/aspnet/Microsoft.Data.Sqlite/commit/351d65fd1648b9482cb67c6a9fd14f5f427cb1e3 & https://github.com/aspnet/Microsoft.Data.Sqlite/commit/e39711b155cd501bfe10458d773469c4a6799e20. I can dig more into the failures when I get back on Wednesday.

**Comment by ajcvickers** [comment] 2017-03-24 19:55
@bricelam We have been investigating this morning. Smit confirmed that it is the SQLite change causing the issue. We tried to go back to an older build, but it wasn't in the feed, so Smit is reverting.

**Comment by smitpatel** [comment] 2017-03-24 20:21
Reverted the offending commit in SQLite repo and created issue to investigate it further.
This should fix the CI builds.
@jbagga - Close this issue if CI passes after SQLite changes are in.

**Comment by ajcvickers** [comment] 2017-03-27 18:10
Issue being tracked at root cause on SQLite repro.

**Closed** 2022-10-16 10:58 UTC
Labels: closed-external
