### ISSUE TITLE
InMemory context is empty in TestServer after upgrade to EF Core 2

### ISSUE THREAD

**Issue by sm-g** [dotnet/efcore#9594] opened 2017-08-26 14:47 UTC
I'm writing my [integration tests](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing) in such way:

```cs
[Test]
public async Task Test() {
var options = new DbContextOptionsBuilder()
            .UseInMemoryDatabase(nameof(MyContext))
            .Options;
using (var db = new MyContext(options))
{
   db.SeedSingleUserLogin();
   db.SaveChanges();
}

var response = await _client.GetAsync("/api/xxx", );

// assert
}
```

Base class for tests contains:

```cs
var builder = new WebHostBuilder()
            .UseContentRoot(contentRoot)
            .ConfigureServices(OverrideServices)
            .UseEnvironment("Development")
            .UseStartup(typeof(WebApp.Tests.Startup))
            ;

        _server = new TestServer(builder);

        _client = _server.CreateClient();
```

WebApp.Tests.Startup:
```cs
services.AddDbContext<MyContext>(x => x.UseInMemoryDatabase(nameof(MyContext))
                .ConfigureWarnings(z => z.Ignore(InMemoryEventId.TransactionIgnoredWarning))
                .EnableSensitiveDataLogging());
```

In controller there should be same DbContext because I use same string (`nameof(MyContext)`), but all its DbSets are empty.

EF Core 2.0.0 / VS 15.3.0

**Comment by ajcvickers** [comment] 2017-08-28 23:12
@sm-g A few questions to help us understand what might be going on:
* Are you creating instances of MyContext with `new` in all places that it is use? 
* Do you call UseInternalServiceProvider anywhere?
* Do you have the same configuration for your context options in some places? For example, it looks like you are configuring warnings and using sensitive data logging in one place, but not the other. Do things start to work if you make sure the ConfigureWarnings and EnableSensitiveDataLogging are called consistently in both places?

**Comment by sm-g** [comment] 2017-08-29 10:07
> Are you creating instances of MyContext with new in all places that it is use?
only to seed initial state at beginning of test, other code receive it via DI

> Do you call UseInternalServiceProvider anywhere?
no

> Do things start to work if you make sure the ConfigureWarnings and EnableSensitiveDataLogging are called consistently in both places?
I set same options, but nothing changed.

**Comment by ajcvickers** [comment] 2017-08-29 16:56
@sm-g I thought it might be #9613, but given it still happens when both contexts have the same options it can't be that. I have been unable to reproduce this so far. Would it be possible to put together a full code listing or project that reproduces what you are seeing?

**Comment by sm-g** [comment] 2017-08-30 07:02
@ajcvickers https://github.com/sm-g/EFCoreInMemorySample

**Comment by msmolka** [comment] 2017-08-30 08:30
@ajcvickers Hello
I'm experiencing the same issue with my scenario after upgrade only to .NET Core 2
Here is my project:
[https://github.com/msmolka/ZNetCS.AspNetCore.Logging.EntityFrameworkCore](https://github.com/msmolka/ZNetCS.AspNetCore.Logging.EntityFrameworkCore)

**Comment by ajcvickers** [comment] 2017-08-31 01:03
Looks like this is the same underlying cause as #9613. In this case, it is AddDbContext  that sets an option (ApplicationServiceProvider) that later causes two service providers to be created.

Closing as a duplicate of #9613, since that details the root cause. I will look into workarounds/options for fixing this tomorrow.

**Comment by ajcvickers** [comment] 2017-09-12 18:53
Hi @sm-g, @msmolka. We are gathering information on the use of EF Core pre-release builds. You reported this issue shortly after the release of 2.0.0 RTM. It would be really helpful if you could let us know:

- Did you consider testing your code against the pre-release builds?
- Was there anything blocking you from using pre-release builds?
- What do you think could make it easier for you to use pre-release builds in the future?

Thanks in advance for any feedback. Hopefully this will help us to increase the value of pre-release builds going forward.

**Comment by msmolka** [comment] 2017-09-12 18:57
@ajcvickers l'm currently AFK. So will test after available again in 2 weeks

**Comment by msmolka** [comment] 2017-12-21 10:29
@ajcvickers I finally made some tests, with latest provider and memory root. And it looks working

**Closed** 2022-10-16 11:18 UTC
