### ISSUE TITLE
Improve reverse engineering extensibility

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#12050] opened 2018-05-17 16:23 UTC
We have an ongoing discussion on how to best address the needs of customers using reverse engineering. 

Part of the plan is to make sure third parties that enable additional customization of the outcome (e.g. EF Core PowerTools)  can do so relying on public extensibility (rather than public/internal) surface.

**Comment by ajcvickers** [comment] 2018-06-13 00:10
Consider file names when working on this--see #12319

**Comment by bricelam** [comment] 2018-06-13 15:57
@ajcvickers Did you mean #4038?

**Comment by ajcvickers** [comment] 2018-12-03 20:48
@divega @bricelam Should this be closes as a duplicate of #4038

**Comment by bricelam** [comment] 2018-12-03 23:16
I say yes, but I think @divega had a narrower scope in mind when he created this--to make sure the existing third-party projects have the public API they need today.

**Comment by ajcvickers** [comment] 2022-10-26 11:33
Extensibility is this area is working well; we don't plan to do anything else.

**Closed by ajcvickers** 2022-10-26 11:33 UTC
Labels: type-enhancement, propose-close, area-scaffolding
