### ISSUE TITLE
Composite Indexes automatically create index tables for standalone entity indexes

### ISSUE THREAD

**Issue by kimimaru4000** [dotnet/efcore#23550] opened 2020-12-01 22:58 UTC
## File a bug
If you specify composite indexes, EF Core will automatically create more indexes that **were not specified** while creating the model. This issue has been causing me many pains, and I'll summarize how it affects me by including my code and relevant images.

My DbSets:
```
public DbSet<Settings> SettingCollection { get; set; } = null;
public DbSet<GameLog> GameLogs { get; set; } = null; 
public DbSet<CommandData> Commands { get; set; } = null;
public DbSet<Meme> Memes { get; set; } = null;
public DbSet<InputMacro> Macros { get; set; } = null;
public DbSet<InputSynonym> InputSynonyms { get; set; } = null;
public DbSet<GameConsole> Consoles { get; set; } = null;
public DbSet<User> Users { get; set; } = null;
public DbSet<PermissionAbility> PermAbilities { get; set; } = null;
```

Here is my full `OnModelCreating`:
```
modelBuilder.Entity<Settings>().ToTable("Settings", "settings");
modelBuilder.Entity<Settings>(entity =>
{
    entity.HasKey(e => e.ID);
    entity.Property(e => e.Key).HasDefaultValue(string.Empty);
    entity.Property(e => e.ValueStr).HasDefaultValue(string.Empty);
    entity.Property(e => e.ValueInt).HasDefaultValue(0L);
    entity.HasIndex(e => e.Key).IsUnique();
});

modelBuilder.Entity<GameLog>().ToTable("GameLogs", "gamelogs");
modelBuilder.Entity<GameLog>(entity => 
{
    entity.HasKey(e => e.ID);
});

modelBuilder.Entity<CommandData>().ToTable("CommandData", "commanddata");
modelBuilder.Entity<CommandData>(entity =>
{
    entity.HasKey(e => e.ID);
    entity.Property(e => e.Level).HasDefaultValue(0);
    entity.Property(e => e.Enabled);
    entity.Property(e => e.DisplayInList);
    entity.HasIndex(e => e.Name).IsUnique();
});

modelBuilder.Entity<Meme>().ToTable("Memes", "memes");
modelBuilder.Entity<Meme>(entity =>
{
    entity.HasKey(e => e.ID);
    entity.HasIndex(e => e.MemeName).IsUnique();
});

modelBuilder.Entity<InputMacro>().ToTable("Macros", "macros");
modelBuilder.Entity<InputMacro>(entity =>
{
    entity.HasKey(e => e.ID);
    entity.Property(e => e.MacroName).HasDefaultValue(string.Empty);
    entity.Property(e => e.MacroValue).HasDefaultValue(string.Empty);
    entity.HasIndex(e => e.MacroName).IsUnique();
});

modelBuilder.Entity<InputSynonym>().ToTable("InputSynonyms", "inputsynonyms");
modelBuilder.Entity<InputSynonym>(entity =>
{
    entity.HasKey(e => e.ID);
    entity.Property(e => e.SynonymName).HasDefaultValue(string.Empty);
    entity.Property(e => e.SynonymValue).HasDefaultValue(string.Empty);
    entity.Property(e => e.ConsoleID).HasDefaultValue(1);
    entity.HasIndex(e => new { e.SynonymName, e.ConsoleID });
});

modelBuilder.Entity<GameConsole>().ToTable("Consoles", "consoles");
modelBuilder.Entity<GameConsole>(entity =>
{
    entity.HasKey(e => e.ID);
    entity.Property(e => e.Name).HasDefaultValue("GameConsole");
    entity.Ignore(e => e.InputRegex);
    entity.Ignore(e => e.ConsoleInputs);
    entity.HasMany(e => e.InputList).WithOne(c => c.Console).HasForeignKey(c => c.ConsoleID).IsRequired().OnDelete(DeleteBehavior.Cascade);
    entity.HasMany(e => e.InvalidCombos).WithOne().OnDelete(DeleteBehavior.Cascade);
    entity.HasIndex(e => e.Name);
});

modelBuilder.Entity<InputData>().ToTable("Inputs", "inputs");
modelBuilder.Entity<InputData>(entity =>
{
    entity.HasKey(e => e.ID);
    entity.Property(e => e.Name).HasDefaultValue(string.Empty);
    entity.Property(e => e.ButtonValue).HasDefaultValue(0);
    entity.Property(e => e.AxisValue).HasDefaultValue(0);
    entity.Property(e => e.InputType).HasDefaultValue(InputTypes.Blank).HasConversion(new EnumToNumberConverter<InputTypes, int>());
    entity.Property(e => e.MinAxisVal).HasDefaultValue(0);
    entity.Property(e => e.MaxAxisVal).HasDefaultValue(1);
    entity.Property(e => e.MaxAxisPercent).HasDefaultValue(100);
    entity.Property(e => e.Enabled).HasDefaultValue(1);
    entity.HasIndex(e => new { e.Name, e.ConsoleID });
});

modelBuilder.Entity<InvalidCombo>().ToTable("InvalidInputCombos", "invalidinputcombos");
modelBuilder.Entity<InvalidCombo>(entity =>
{
    entity.HasKey(e => e.ID);
    entity.HasOne(e => e.Input).WithOne().HasForeignKey<InvalidCombo>(c => c.InputID).IsRequired().OnDelete(DeleteBehavior.Cascade);
    entity.HasIndex(e => e.InputID);
});

modelBuilder.Entity<User>().ToTable("Users", "users");
modelBuilder.Entity<User>(entity =>
{
    entity.HasKey(e => e.ID);
    entity.Property(e => e.Name).HasDefaultValue(string.Empty);
    entity.HasOne(e => e.Stats).WithOne(u => u.user).HasForeignKey<UserStats>(u => u.UserID).IsRequired().OnDelete(DeleteBehavior.Cascade);
    entity.HasMany(e => e.UserAbilities).WithOne(c => c.user).HasForeignKey(u => u.UserID).IsRequired().OnDelete(DeleteBehavior.Cascade);
    entity.HasMany(e => e.RestrictedInputs).WithOne(e => e.user).HasForeignKey(e => e.UserID).IsRequired().OnDelete(DeleteBehavior.Cascade);
    entity.HasIndex(e => e.Name);
});

modelBuilder.Entity<UserStats>().ToTable("UserStats", "userstats");
modelBuilder.Entity<UserStats>(entity =>
{
    entity.HasKey(e => e.ID);
});

modelBuilder.Entity<PermissionAbility>().ToTable("PermissionAbilities", "permissionabilities");
modelBuilder.Entity<PermissionAbility>(entity =>
{
    entity.HasKey(e => e.ID);
    entity.Property(e => e.AutoGrantOnLevel).HasConversion(new EnumToNumberConverter<PermissionLevels, int>());
    entity.HasIndex(e => e.Name);
});

modelBuilder.Entity<UserAbility>().ToTable("UserAbilities", "userabilities");
modelBuilder.Entity<UserAbility>(entity =>
{
    entity.HasKey(e => e.ID);
    entity.HasOne(e => e.PermAbility).WithOne().HasForeignKey<UserAbility>(u => u.PermabilityID).IsRequired();
    entity.HasIndex(e => new { e.UserID, e.PermabilityID });
});

modelBuilder.Entity<RestrictedInput>().ToTable("RestrictedInputs", "restrictedinputs");
modelBuilder.Entity<RestrictedInput>(entity =>
{
    entity.HasKey(e => e.ID);
    entity.HasOne(e => e.inputData).WithOne().HasForeignKey<RestrictedInput>(e => e.InputID).IsRequired().OnDelete(DeleteBehavior.Cascade);
    entity.HasIndex(e => new { e.UserID, e.InputID });
});
```

After this, I would expect the models with **only** composite indexes to create **only** those composite indexes. That's not the case:

![EFCoreIndexes](https://user-images.githubusercontent.com/1388037/100805671-fe03de00-3426-11eb-9335-36a48bf48e37.png)

In particular, EF Core added the following indexes, which again, **I did not tell it to create**:
- IX_Inputs_ConsoleID
- IX_InvalidInputCombos_GameConsoleID
- IX_RestrictedInputs_InputID
- IX_UserAbilities_PermabilityID

Not only that, but they're all unique indexes. This creates huge issues that I've been fighting with for months now. My `User` object has this navigation property:

`public virtual List<UserAbility> UserAbilities { get; set; }`

From the above models, we saw that `UserAbility` has a `PermissionAbility` navigation property called "PermAbility" and a foreign key for it called "PermabilityID". Basically, thanks to these auto-generated indexes, no two users can have a `UserAbility` referencing the same `PermissionAbility`. Attempting to do so crashes the application and was absolutely not my intent when I created the model. **I wanted each `UserAbility` to be linked to each `User` AND each `PermissionAbility`, not only the latter**.

I consider this a bug because I would like **only the index tables I specified to be created**, nothing else. I don't want to keep wrestling with manually modifying the migrations to drop these tables, and I don't expect other developers on my application to do so either.

### Specs

EF Core version: 5.0.0
Database provider: System.Data.SQLite
Target framework: .NET 5.0
Operating system: Linux Mint 20 Ulyana
IDE: dotnet cli

**Comment by smitpatel** [comment] 2020-12-01 23:02
Note for triage: These are just indexes created for FKs.

**Comment by tdeeb** [comment] 2020-12-01 23:09
Also, I found out this is not completely unique to composite indexes. Removing indexes entirely still creates them, which simply sounds wrong. The developer should be the only one to determine whether they want an index in their database or not.

**Comment by ajcvickers** [comment] 2020-12-04 17:46
Duplicate of #13793

**Closed** 2022-10-16 19:13 UTC
Labels: customer-reported
