### ISSUE TITLE
Unable to cast object of type 'System.Decimal' to type 'System.Int32'

### ISSUE THREAD

**Issue by wjvii** [dotnet/efcore#19943] opened 2020-02-15 21:58 UTC
I have a table that I am inserting into from EF Core 3.1.1 and somehow the insert trigger on that table is causing this error but I don't understand why because in looking at it, nothing in the stored procedure has anything to do with decimal values. I am fairly certain it is the trigger at this point because if I disable it then the insert works fine. That said, if I execute a SQL insert query with the same parameter values that the EF Core logging indicates are being passed in SQL insert statement runs as expected with no error and the row is inserted.

I didn't write the stored procedure and I am definitely not a T-SQL guru so hoping someone can point me in the right direction on what to look at since I don't understand how it can have an issue with a System.Decimal when there isn't a decimal involved in the table fields or the entities properties.

Thank you in advance.

Got Exceptions? Include both the message and the stack trace

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> System.InvalidCastException: Unable to cast object of type 'System.Decimal' to type 'System.Int32'.
   at Microsoft.Data.SqlClient.SqlBuffer.get_Int32() in E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlBuffer.cs:line 330
   at Microsoft.Data.SqlClient.SqlDataReader.GetInt32(Int32 i) in E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlDataReader.cs:line 2312
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagation(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Microsoft.EntityFrameworkCore.Update: Error: An exception occurred in the database while saving changes for context type 'DbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
```

### Further technical details

EF Core version: 3,1,1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.4.5)

**Comment by ajcvickers** [comment] 2020-02-19 17:44
@wjvii Please attach a small, runnable project or post a complete code listing that reproduces the error you are seeing so that we can investigate.

**Comment by wjvii** [comment] 2020-02-21 01:15
@ajcvickers Thank you again for the response.

I finally tracked it down. The tables insert trigger is calling a stored procedure and this stored procedure returned the SCOPE IDENTITY. This seems to interfere with the EF so I modified the stored procedure to not return a value and that seems to have resolved the issue.

Should that cause an issue with EF on an insert? If it doesn't sound like it then I am happy to provide some examples from the SP that caused the issue if this explanation is not enough.

**Comment by ajcvickers** [comment] 2020-02-21 22:06
@wjvii Can you post the trigger and stored procedures here?

**Comment by ajcvickers** [comment] 2020-02-28 17:03
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:11 UTC
Labels: closed-no-further-action, customer-reported
