### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by deokershesh** [dotnet/efcore#20790] opened 2020-04-30 11:57 UTC
I am using EFCore source  code from https://github.com/dotnet/efcore, while doing build (using "build" command), I get following errors! What am I missing?

D:\shesh\EntityFrameworkCore\efcore-master>dotnet --version
5.0.100-preview.2.20176.6

Visual Studio 2019 Professional Edition

C:\Users\sheshnarayan.a\.nuget\packages\microsoft.build.tasks.git\1.1.0-beta-20206-02\build\Microsoft.Build.Tasks.Git.targets(47,5): error : Unable to locate repository with working directory that contains directory 'D:\shesh\EntityFrameworkCore\efcore-master\test\EFCore.SqlServer.Tests'. [D:\shesh\EntityFrameworkCore\efcore-master\test\EFCore.SqlServer.Tests\EFCore.SqlServer.Tests.csproj]
C:\Users\sheshnarayan.a\.nuget\packages\microsoft.sourcelink.common\1.1.0-beta-20206-02\build\Microsoft.SourceLink.Common.targets(52,5): error : Source control information is not available - the generated source link is empty. [D:\shesh\EntityFrameworkCore\efcore-master\test\EFCore.SqlServer.Tests\EFCore.SqlServer.Tests.csproj]
    0 Warning(s)
    194 Error(s)

**Comment by ajcvickers** [comment] 2020-04-30 15:47
@deokershesh I haven't seen this before. Did you follow the instructions here: https://github.com/dotnet/efcore/blob/master/docs/getting-and-building-the-code.md

**Comment by ajcvickers** [comment] 2020-05-08 15:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:22 UTC
Labels: closed-could-not-reproduce, customer-reported
