### ISSUE TITLE
Serialization settings with Cosmos Db Provider

### ISSUE THREAD

**Issue by vafzamora** [dotnet/efcore#30300] opened 2023-02-16 22:04 UTC
I have a customer who uses this code snippet to change default null value handling behavior for JSON serialization when using the CosmosDb client: 

```C#
       var cosmosJsonOptions = new JsonSerializerSettings
        {
            NullValueHandling = NullValueHandling.Ignore
        };
        Configure(builder);         
        JsonConvert.DefaultSettings = () =>
        {
            return cosmosJsonOptions;
        };
```
He asked me on how to do the same for EF Core using CosmosDb provider. 
I didn't find a way to set serialization options when configuring the DbContext with UseCosmos, only a subset of CosmosDb options is available. 
Reading the source code I could see that the serializer instance used internally is created with ```JsonSerializer.Create()``` which,  according to Newtonsoft documentation, won't use ```JsonConvert.DefaultSettings```. 

Is this by design? Is there any way to change serialization settings for CosmosDb provider? 

EF Core version: 6+
Database provider: (e.g. Microsoft.EntityFrameworkCore.Cosmos)

Thanks in advance,

**Comment by ajcvickers** [comment] 2023-02-17 11:15
Duplicate of #17306. Please vote (👍) for that issue.

**Comment by roji** [comment] 2023-02-18 09:19
Duplicate of #17306

**Closed** 2023-02-22 15:15 UTC
Labels: customer-reported
