### ISSUE TITLE
SQLite Migrations: Cycle-breaking AddForeignKey not lifted to CreateTable

### ISSUE THREAD

**Issue by dmarlow** [dotnet/efcore#17477] opened 2019-08-28 17:56 UTC
Since I'm using SQLite, AddForeignKey and DropForeignKey aren't supported. Is it possible to define things such that `migrationBuilder.AddForeignKey` isn't used, but rather, it's defined in the `CreateTable` call as `table.ForeignKey` instead? This would get rid of the two calls that aren't supported. Is the only way to do it to manually alter the generated migration? I'd like to avoid that as that causes a lot of churn.

### Steps to reproduce
```c#
public class EFCoreDemoContext : DbContext
{
    public DbSet<Site> Sites { get; set; }
    public DbSet<Scan> Scans { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Data Source=test.db");
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Site>()
            .HasMany(x => x.Scans)
            .WithOne(x => x.Site)
            .HasForeignKey(x => x.SiteId);

        modelBuilder.Entity<Scan>()
            .HasOne(x => x.Site)
            .WithMany(x => x.Scans)
            .HasForeignKey(x => x.SiteId);

        base.OnModelCreating(modelBuilder);
    }
}

public class Site
{
    public int SiteId { get; set; }

    public int LatestScanId { get; set; }
    [ForeignKey("LatestScanId")]
    public Scan LatestScan { get; set; }

    public ICollection<Scan> Scans { get; set; } = new List<Scan>();
}

public class Scan
{
    public int ScanId { get; set; }
    public int SiteId { get; set; }
    public Site Site { get; set; }
}
```

The following migration is generated:
```c#
public partial class Test : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Sites",
            columns: table => new
            {
                SiteId = table.Column<int>(nullable: false)
                    .Annotation("Sqlite:Autoincrement", true),
                LatestScanId = table.Column<int>(nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Sites", x => x.SiteId);
            });

        migrationBuilder.CreateTable(
            name: "Scans",
            columns: table => new
            {
                ScanId = table.Column<int>(nullable: false)
                    .Annotation("Sqlite:Autoincrement", true),
                SiteId = table.Column<int>(nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Scans", x => x.ScanId);
                table.ForeignKey(
                    name: "FK_Scans_Sites_SiteId",
                    column: x => x.SiteId,
                    principalTable: "Sites",
                    principalColumn: "SiteId",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "IX_Scans_SiteId",
            table: "Scans",
            column: "SiteId");

        migrationBuilder.CreateIndex(
            name: "IX_Sites_LatestScanId",
            table: "Sites",
            column: "LatestScanId");

        migrationBuilder.AddForeignKey(
            name: "FK_Sites_Scans_LatestScanId",
            table: "Sites",
            column: "LatestScanId",
            principalTable: "Scans",
            principalColumn: "ScanId",
            onDelete: ReferentialAction.Cascade);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "FK_Scans_Sites_SiteId",
            table: "Scans");

        migrationBuilder.DropTable(
            name: "Sites");

        migrationBuilder.DropTable(
            name: "Scans");
    }
}
```

### Further technical details
EF Core version: 2.2.6
Database Provider: SQLite
Operating system: Win 10
IDE: Visual Studio 2019 16.2

**Comment by ajcvickers** [comment] 2019-08-30 17:34
Duplicate of #329

**Comment by bricelam** [comment] 2019-09-03 17:27
@dmarlow Are you sure it doesn't work? It's supposed to lift it back into the CREATE TABLE statement when it generates the SQL (see #2590)

**Comment by dmarlow** [comment] 2019-09-04 16:39
@bricelam I'm positive. The code and output are above. Maybe the lift requires things to be done in a certain way?

**Comment by bricelam** [comment] 2020-06-23 20:33
I found the code that does this:

https://github.com/dotnet/efcore/blob/e4884bbaf11c3b75fe4021c49ac1da5dfa0f293a/src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs#L72-L81

Note well, this happens at SQL generation time. So even tough the operations are separate in the Migration class, they are collapsed before being sent to the database.

**Closed** 2022-10-16 14:38 UTC
Labels: closed-could-not-reproduce, customer-reported, punted-for-3.1, punted-for-5.0
