### ISSUE TITLE
Can execute ThenByDescending on owned type?

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22732] opened 2020-09-24 22:52 UTC
Moved from discussions.

### Question

From @aodpi

I have a use case where I call `OrderByDescending` on a query then make a call to `ThenByDescending` but the body of that method is actually an owned type that has a property called `CreateDate`. I want to order by create date that is located in an owned type basically. While testing this use case using an In-Memory database with EF Core version 3.1.8 I get an error:

```
 Message: 
    System.ArgumentException : Expression of type 'System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Storage.ValueBuffer]' cannot be used for parameter of type 'System.Linq.IOrderedEnumerable`1[Microsoft.EntityFrameworkCore.Storage.ValueBuffer]' of method 'System.Linq.IOrderedEnumerable`1[Microsoft.EntityFrameworkCore.Storage.ValueBuffer] ThenByDescending[ValueBuffer,Nullable`1](System.Linq.IOrderedEnumerable`1[Microsoft.EntityFrameworkCore.Storage.ValueBuffer], System.Func`2[Microsoft.EntityFrameworkCore.Storage.ValueBuffer,System.Nullable`1[System.DateTimeOffset]])' (Parameter 'arg0')
  Stack Trace: 
    ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
    Expression.Call(MethodInfo method, Expression arg0, Expression arg1)
    InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateThenBy(ShapedQueryExpression source, LambdaExpression keySelector, Boolean ascending)
    QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    MethodCallExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    MethodCallExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
    Database.CompileQuery[TResult](Expression query, Boolean async)
    QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
    <>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
    CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
    CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
    QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
    EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
    EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
    ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
    EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
    MessageService.GetMessagesAsync(ITagQuery tagFilter, String searchText, Nullable`1 pageNumber, Nullable`1 pageSize, String orderBy, IEnumerable`1 tagOrder, Boolean filterOnDate, CancellationToken cancellationToken) line 218
    MessageServiceTests.CanSortOnTags() line 64
    GenericAdapter`1.GetResult()
    AsyncToSyncAdapter.Await(Func`1 invoke)
    TestMethodCommand.RunTestMethod(TestExecutionContext context)
    TestMethodCommand.Execute(TestExecutionContext context)
    <>c__DisplayClass1_0.<Execute>b__0()
    BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

I'm wondering, am I doing something wrong or this is not possible for the moment. I wasn't able to find some documentation regarding ordering on owned types. Thanks in advance

### Replies

From @smitpatel

Tracked as issue by #18912

**Comment by smitpatel** [comment] 2020-09-25 03:46
Duplicate of #18912

**Closed** 2022-10-16 18:43 UTC
Labels: closed-duplicate, customer-reported
