### ISSUE TITLE
UWP SQLite Database with absolute path leads to very bad performance

### ISSUE THREAD

**Issue by ftiefenbach** [dotnet/efcore#5981] opened 2016-07-05 12:36 UTC
### Steps to reproduce

Create a SQLite Database with some Data. Mine has only one table containing four columns. I created the database with EF Core RC2 SQLiteProvider and the ConnectionString "Filename=MasterData.db". I filled this database with 40 Entries. Nothing very special. Take the filled Database and move it in an UWP project (I use a folder Data in the project) and set the BuildAction to 'Content' and 'Copy always'. Use

```
var appInstalledFolder = Windows.ApplicationModel.Package.Current.InstalledLocation;
var documentsRoot = await appInstalledFolder.GetFolderAsync("Data");
var masterDataFile = await documentsRoot.GetFileAsync("MasterData.db");
var connectionstring = $"Filename={masterDataFile.Path}"
```

as connection string for the SQLite Provider.
### The issue

If I use the Database within the default localState (Filename=MasterData.db) a simple select query takes about 15ms. But if I deploy the same database as  an application content and I connect by an absolute path to it, the same query takes 1700ms. I wouldn't expect any difference.
### Further technical details

EF Core version: 1.0.0-rc2-final
Operating system: Windows 10 (UWP)
Visual Studio version: VS 2015 Update 3

**Comment by rowanmiller** [comment] 2016-07-15 17:21
Our guess here is that you are incurring some extra UWP sand box checks because a Data folder in the install directory is not optimized for writing data to. Is there a reason you want to put data there rather than the default location for data files? Also, do you see the same slowdown if you just use SQLite directly (i.e. are you sure this is an Entity Framework issue)?

**Comment by rowanmiller** [comment] 2016-07-20 17:52
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 09:49 UTC
