### ISSUE TITLE
GroupBy could not be translated and will be evaluated locally

### ISSUE THREAD

**Issue by paulovila** [dotnet/efcore#14700] opened 2019-02-14 12:27 UTC
The groupBy is calculated locally instead of SQL Server

### Steps to reproduce

```c#
_context.Positions
.Where(w => 
    w.Performance.ClientId == 150
    && w.EffectiveDate >= new DateTime(2018, 12, 1)
    && w.EffectiveDate <= new DateTime(2018, 12, 31))
.Select(p => new
{
    AssetId = p.AssetId,
    Asset = p.Asset,
    DailyTotal = _context.Positions
        .Where(w => w.Performance.ClientId == 150
                      && w.EffectiveDate == p.EffectiveDate)
		.Sum(x => x.AssetBase),
    ALoss = p.ALoss,
    ActiveLoss = p.ActiveLoss
})
.GroupBy(w => w.Asset)
.Select(g => new Summary
{
    AssetId = g.Key.Id,
    Asset = g.Key,
    AssetReturn = g.Sum(x => x.ALoss / x.DailyTotal) * 100,
})
```

Returns
```
Microsoft.EntityFrameworkCore.Query: Warning: The LINQ expression 'GroupBy([a.Asset], new Summary() {AssetId = ...... w in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1 ...Position]) join Performance w.Performance in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1 ... A..............' could not be translated and will be evaluated locally.
Microsoft.EntityFrameworkCore.Query: Warning: The LINQ expression 'Sum()' could not be translated and will be evaluated locally.

```

### Further technical details
EF Core version: (2.2)
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE:  Visual Studio 2017 15.9.6

**Comment by smitpatel** [comment] 2019-02-14 18:20
Duplicate of #11976

**Closed** 2022-10-16 13:52 UTC
Labels: closed-duplicate, customer-reported
