### ISSUE TITLE
Where condition on an include appears not to work

### ISSUE THREAD

**Issue by johnkwaters** [dotnet/efcore#8069] opened 2017-04-04 17:20 UTC
Is it supported?

I have an entity Product, which has a collection of ProductListItems. ProductListItem is a join table from Product to ListItem. ListItem has in turn a List (that it belongs to). So one List has many list items.

I want to select all products, and include each products list items

var qry = ctxt.Set<Product>.AsNoTracking().AsQueryable();

qry Include( p => p.ListItems)

but only for those list items whose list belongs to a certain tenant. I tried

qry.Include(p => p.ListItems.Where(li => li.ListItem.List.TenantId == 7).Select( pli => pli));

And 

qry.Include(p => p.ListItems.Where(li => li.ListItem.List.TenantId == 7));

Both give this error:

System.InvalidOperationException: 'The property expression 'p => {from ProductListItem li in [<generated>_6].ListItems where ([li].ListItem.List.TenantId == __FilterByTenantId_0) select [li]}' is not valid. The expression should represent a property access: 't => t.MyProperty'. For more information on including related data, see http://go.microsoft.com/fwlink/?LinkID=746393.'

Is there a way to filter the included collection?

**Comment by ajcvickers** [comment] 2017-04-04 17:34
Duplicate of #1833

**Closed** 2022-10-16 10:59 UTC
Labels: closed-duplicate
