### ISSUE TITLE
[Sqlite in memory] ToList() throws exception

### ISSUE THREAD

**Issue by RaguMP** [dotnet/efcore#19398] opened 2019-12-24 11:32 UTC
I am using Sqlite in memory database for my integration test project where I have some linq select query which contains list of data throws exception whereas those query works fine when using MS SQL database.

**Sample Query:**

 ```C#
var result = (from user in context.Users.Where(i => i.IsActive && i.UserId == 1)
                       select new
                       {
                           RoleIdList = context.UserRoleMapper
                                               .Where(j => j.IsActive && j.UserId==user.UserId)
                                               .Select(j=> k.RoleId).ToList()
                       }).FirstOrDefault();
```

I am expecting a result of single item contain list of role Ids mapped with the user but getting the following exceptions.

```
**Exception Details:**

**Inner Exception Message:** SQLite Error 1: 'near "(": syntax error'.

**Inner Exception StackTrace :**    
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.<PrepareAndEnumerateStatements>d__64.MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.<GetStatements>d__54.MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)  
```

**Note:**
If I use "FirstOrDefault()" in the above query I can able to get the result but in my case I need to fetch all roles mapped. I know I can able to get using join query and then do "groupby" but in my application need to map some other tables too. So I preferred to get in a single item.

**Modified Query:**

 ```C#
var result = (from user in context.Users.Where(i => i.IsActive && i.UserId == 1)
                       select new
                       {
                           RoleIdList = context.UserRoleMapper
                                               .Where(j => j.IsActive && j.UserId==user.UserId)
                                               .Select(j=> k.RoleId).FirstOrDefault()
                       }).FirstOrDefault();
```

### Further technical details

EF Core version: 3.1.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.InMemory, Microsoft.EntityFrameworkCore.Sqlite)
Target framework: (e.g. .NET Core 3.1)
Operating system:
IDE: (e.g. Visual Studio 2019 16.4.2)

**Comment by ajcvickers** [comment] 2020-01-03 18:31
@smitpatel to find dupe.

**Comment by smitpatel** [comment] 2020-01-03 19:42
Duplicate of #19178 
But in this case, it should convert it to left join.

**Comment by smitpatel** [comment] 2020-02-08 01:15
I could not reproduce it on 3.1
```C#
using System;
using System.ComponentModel.DataAnnotations;
using System.Data.Common;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static async Task Main(string[] args)
        {
            var dbConnection = new SqliteConnection("filename=:memory:");
            dbConnection.Open();

            using (var db = new MyContext(dbConnection))
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database


                db.SaveChanges();
            }

            using (var context = new MyContext(dbConnection))
            {
                // Run queries
                var result = (from user in context.Users.Where(i => i.IsActive && i.UserId == 1)
                              select new
                              {
                                  RoleIdList = context.UserRoleMapper
                                                      .Where(j => j.IsActive && j.UserId == user.UserId)
                                                      .Select(j => j.RoleId).ToList()
                              }).FirstOrDefault();
            }
            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        private readonly DbConnection _dbConnection;

        private static ILoggerFactory ContextLoggerFactory
            => LoggerFactory.Create(b =>
            {
                b
                .AddConsole()
                .AddFilter("", LogLevel.Debug);
            });

        public MyContext(DbConnection dbConnection)
        {
            this._dbConnection = dbConnection;
        }

        // Declare DBSets
        public DbSet<User> Users { get; set; }
        public DbSet<UserRoleMaper> UserRoleMapper { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                //.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                //.UseSqlite("filename=_modelApp.db")
                .UseSqlite(_dbConnection)
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                //.UseCosmos("https://localhost:8081", @"C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==", "_ModelApp")
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(ContextLoggerFactory);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
        }
    }

    public class User
    {
        public int UserId { get; set; }
        public bool IsActive { get; set; }
    }

    public class UserRoleMaper
    {
        [Key]
        public int RoleId { get; set; }
        public int UserId { get; set; }
        public bool IsActive { get; set; }
    }
}
```

@RaguMP - Please modify above repro code to demonstrate issue you are seeing.

**Comment by ajcvickers** [comment] 2020-02-21 17:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:02 UTC
Labels: closed-could-not-reproduce, customer-reported
