### ISSUE TITLE
SqlServerModelBuilderExtensions not working

### ISSUE THREAD

**Issue by redowl5** [dotnet/efcore#28448] opened 2022-07-14 10:03 UTC
Hi, 

The SqlServerModelBuilderExtensions of HasServiceTier, HasDatabaseMaxSize or HasPerformanceLevel do not work when deploying to Azure (UK South).  The database created is Gen5 - General Purpose (GP_Gen5_2)

```C#

Program.cs

context.Database.EnsureDeleted();
context.Database.EnsureCreated();

DataContext.cs

protected override void OnModelCreating(ModelBuilder modelBuilder)
 {
            base.OnModelCreating(modelBuilder);

            modelBuilder.HasDatabaseMaxSize("100 MB");
            modelBuilder.HasServiceTier("Basic");
            modelBuilder.HasPerformanceLevel("Basic");
}
```
EF Core version:  6.0.5
Microsoft.EntityFrameworkCore.SqlServer version:  6.0.5
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Azure
IDE:  Visual Studio 2022 17.3

![image](https://user-images.githubusercontent.com/78690088/178957244-44935548-f292-4fca-8a28-5e3802e7503e.png)

**Comment by roji** [comment] 2022-07-14 10:18
@redowl5 can you please post the migration SQL that's getting generated? You can obtain that with `dotnet ef migrations sql ...`.

**Comment by ajcvickers** [comment] 2022-07-27 19:29
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-07-27 19:29 UTC
Labels: customer-reported
