### ISSUE TITLE
EntityFrameworkCore 6.0.24 and 7.0.13 fails Scaffolding for data objects that have two primary keys as the Primary Clustered Key

### ISSUE THREAD

**Issue by mckelvj** [dotnet/efcore#32271] opened 2023-11-09 18:52 UTC
I am experiencing an issue where it is not reverse engineering two many-to-many tables. It is defining the one entity the DbContext on one table, but not the other and the Class for the entity is not created and the "public virtual DbSet class {get; set;}" statement is not defined. No errors are identified in the response to the "dotnet ef dbcontext scaffold" command. Everything else in the database is scaffold correctly.

There are two tables in the database that are not scaffolded. They are both many-to-many. Everything else is correctly scaffold. I tried this using Microsoft.EntityFrameworkCore and MicrosoftEntityFrameworkCore.Tools in both version 6.0.24 and 7.0.13.

A scripted table definition of one table is a shown below:

```TSQL for table example that does not scaffold
USE [databasename]
GO

/****** Object:  Table [dbo].[ClusteredKeyTable]    Script Date: 11/8/2023 1:42:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ClusteredKeyTable](
	[TableOneId] [nvarchar](128) NOT NULL,
	[TableTwoId] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_dbo.ClusteredKeyTable] PRIMARY KEY CLUSTERED 
(
	[TableOneId] ASC,
	[TableTwoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ClusteredKeyTable]  WITH CHECK ADD  CONSTRAINT [FK_dbo.ClusteredKeyTable_dbo.TableTwo_TableTwoId] FOREIGN KEY([TableTwoId])
REFERENCES [dbo].[TableTwo] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ClusteredKeyTable] CHECK CONSTRAINT [FK_dbo.ClusteredKeyTable_dbo.TableTwo_TableTwoId]
GO

ALTER TABLE [dbo].[ClusteredKeyTable]  WITH CHECK ADD  CONSTRAINT [FK_dbo.ClusteredKeyTable_dbo.TableOne_TableOneId] FOREIGN KEY([TableOneId])
REFERENCES [dbo].[TableOne] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ClusteredKeyTable] CHECK CONSTRAINT [FK_dbo.ClusteredKeyTable_dbo.TableOne_TableOneId]
GO
```

```CLI used for scaffolding 
dotnet ef dbcontext scaffold "connectionstring" Microsoft.EntityFrameworkCore.SqlServer -c "dbo" --no-pluralize -p "C:\Users\UserName\source\repos\TestScaffolding\TestScaffolding" --schema "dbo"  -o "C:\Users\UserName\source\repos\TestScaffolding\TestScaffolding\models\dbo"  --force
```

EF Core version: 7.0.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NETCore 6.0
Operating system: 
IDE: Visual Studio 2022 17.1.1

**Comment by ajcvickers** [comment] 2023-11-15 15:11
@mckelvj Can you also post the schema for TableOne and TableTwo?

**Comment by ajcvickers** [comment] 2023-11-29 17:22
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-11-29 17:22 UTC
Labels: customer-reported
