### ISSUE TITLE
EF Core   ExecuteUpdateAsync   Can receive   Expression<Func<T, T>> UpdateColumsExpression ?

### ISSUE THREAD

**Issue by ZetRe** [dotnet/efcore#33256] opened 2024-03-06 07:29 UTC
How to implement the following example?  
I don't want to accept the parameter of Expression<Func<SetPropertyCalls<TSource>, SetPropertyCalls<TSource>>> .
I need to receive the parameter is Expression<Func<TSource, TSource>>

 _dbContext.Set<T>()
                .Where(UpdateWhereExpression)
                                    .ExecuteUpdateAsync(a=>new T(){ Code="1234",Name="test"});

**Comment by roji** [comment] 2024-03-06 10:34
Duplicate of #32018

**Comment by roji** [comment] 2024-03-06 10:34
See specifically https://github.com/dotnet/efcore/issues/32018#issuecomment-1826879920. We're definitely considering making this easier, but for now you'll have to create the full expression tree yourself (i.e. `Expression<Func<SetPropertyCalls, SetPropertyCalls>>`); this is absolutely doable, but a bit more complex than it should be.

**Closed** 2024-03-06 19:58 UTC
Labels: customer-reported

**Comment by ZetRe** [comment] 2024-03-13 03:30
I finally implemented the way by dynamically building the expression tree

```
public static class UpdateExtensions
{
    public static Task<int> ExecuteUpdateAsync<TSource>(this IQueryable<TSource> source, Expression<Func<TSource, TSource>> updateExpresionss, CancellationToken cancellationToken = default)
    {
        if (updateExpresionss == null)
        {
            throw new ArgumentNullException(nameof(updateExpresionss));
        }
        var SetPropertyCallsExpressions = updateExpresionss.ConvertUpdateExpression();

        return source.ExecuteUpdateAsync(SetPropertyCallsExpressions, cancellationToken);
    }


    public static int ExecuteUpdate<TSource>(this IQueryable<TSource> source, Expression<Func<TSource, TSource>> updateExpresionss)
    {
        if (updateExpresionss == null)
        {
            throw new ArgumentNullException(nameof(updateExpresionss));
        }
        var SetPropertyCallsExpressions = updateExpresionss.ConvertUpdateExpression();

        return source.ExecuteUpdate(SetPropertyCallsExpressions);
    }

    public static Expression<Func<SetPropertyCalls<TSource>, SetPropertyCalls<TSource>>> ConvertUpdateExpression<TSource>(this Expression<Func<TSource, TSource>> expression)
    {
        var parameterName = "a";
        ParameterExpression param = Expression.Parameter(typeof(SetPropertyCalls<TSource>), parameterName);
        Expression constructorExpressions = null;
        if (expression.Body is MemberInitExpression memberInitExpression)
        {
            foreach (var item in memberInitExpression.Bindings)
            {
                if (item is MemberAssignment assignment)
                {
                    PropertyInfo propertyInfo = (PropertyInfo)assignment.Member;

                    string propertyName = assignment.Member.Name;

                    var properrtyType = propertyInfo.PropertyType;

                    var parameter = Expression.Parameter(typeof(TSource), parameterName);
                    var propertyAccess = Expression.Property(parameter, propertyName);
                    var propertyExpression = Expression.Lambda(propertyAccess, parameter);



                    var valueExpression = assignment.Expression;

                    var valueParameter = Expression.Parameter(typeof(TSource), parameterName);
                    var valueExpressionFunc = Expression.Lambda(valueExpression, valueParameter);


                    var setPropertyMethod = typeof(SetPropertyCalls<>)
                            .MakeGenericType(typeof(TSource))
                            .GetMethods()
                            .Where(m => m.Name == "SetProperty"
                            && m.GetParameters()
                                .Where(p =>
                                p.ParameterType.IsGenericType &&
                                p.ParameterType.GetGenericTypeDefinition() == typeof(Func<,>)).Count() == 2)
                             .FirstOrDefault();

                    setPropertyMethod = setPropertyMethod.MakeGenericMethod(properrtyType);

                    var setPropertyCall = Expression.Call(
                        constructorExpressions ?? param,
                        setPropertyMethod,
                        propertyExpression,
                        valueExpressionFunc
                    );
                    constructorExpressions = setPropertyCall;
                }
            }
        }

        return Expression.Lambda<Func<SetPropertyCalls<TSource>, SetPropertyCalls<TSource>>>(constructorExpressions ?? param, param);

    }

}
```

**Comment by AlphaYu** [comment] 2025-02-21 16:19
@ZetRe  
wonderful,tks

**Comment by roji** [comment] 2025-02-23 20:49
Note that #32018 has been implemented for EF 10, so dynamically specifying setters to ExecuteUpdate will become much easier.
