### ISSUE TITLE
To change the IDENTITY property of a column, the column needs to be dropped and recreated

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#20549] opened 2020-04-06 16:04 UTC
I'm still experimenting with code-first database migrations and data annotations. I was using `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]` for my primary key and then decided I didn't need it. So I removed it.

Then when I attempt to `update-database`, I get an exception.

```
Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.2 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (17ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (17ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (22ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '20200406153833_AttributeTweaks'.
Applying migration '20200406153833_AttributeTweaks'.
System.InvalidOperationException: To change the IDENTITY property of a column, the column needs to be dropped and recreated.
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(AlterColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__71_4(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass15_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
To change the IDENTITY property of a column, the column needs to be dropped and recreated.
```

I saw some similar issues but one was closed, and the other seemed specific to SQLite.

I am much more comfortable working with SQL Server Management Studio. And it's very unsettling when everything is automatic like this but then it doesn't work. It's difficult to know what the fix is.

Here's my migration file:

    public partial class AnnotationTweaks : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Areas",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int")
                .Annotation("SqlServer:Identity", "1, 1");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Areas",
                type: "int",
                nullable: false,
                oldClrType: typeof(int))
                .OldAnnotation("SqlServer:Identity", "1, 1");
        }
    }

### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.5.1

**Comment by bricelam** [comment] 2020-04-07 16:28
Duplicate of #2100

**Comment by SoftCircuits** [comment] 2020-04-07 16:53
@bricelam Is there a workaround?

**Comment by bricelam** [comment] 2020-04-07 20:19
Rebuild the table:

1. Add a new table with IDENTITY on the column
2. Copy data from the old table to the new table (with IDENTITY_INSERT ON)
3. Drop referencing constraints and indexes
4. Drop the old table
5. Rename the new table back to its original name
6. Re-create referencing constraints and indexes

The easiest way might be to just generate a script using SSMS and paste it into your migration:

```cs
// UNDONE: Not supported by SQL Server
//migrationBuilder.AlterColumn<int>(
//    name: "Id",
//    table: "Areas",
//    nullable: false,
//    oldClrType: typeof(int),
//    oldType: "int")
//    .Annotation("SqlServer:Identity", "1, 1");
migrationBuilder.Sql(@"
    CREATE TABLE [dbo].[tmp_ms_xx_...
    SET IDENTITY_INSERT [dbo].[tmp_ms_xx_...
    INSERT INTO [dbo].[tmp_ms_xx_...
    SET IDENTITY_INSERT [dbo].[tmp_ms_xx_...
    DROP TABLE [dbo].[...
    EXECUTE sp_rename N'[dbo].[tmp_ms_xx_...
    ALTER TABLE [dbo].[...
        ADD FOREIGN KEY ([...
");
```

**Closed** 2022-10-16 18:19 UTC
Labels: closed-duplicate, customer-reported
