### ISSUE TITLE
Cannot use SQL Server with Identity

### ISSUE THREAD

**Issue by shammelburg** [dotnet/efcore#9669] opened 2017-09-01 06:55 UTC
We can not create the Identity tables on our SQL Server, however, using localdb works fine.

We are using the Package Manager Console to migrate and update.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Failed executing DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DROP INDEX [UserNameIndex] ON [AspNetUsers];

Stack trace:
fail: Microsoft.EntityFrameworkCore.Database.Command[200102]
      Failed executing DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      DROP INDEX [UserNameIndex] ON [AspNetUsers];
System.Data.SqlClient.SqlException (0x80131904): Cannot drop the index 'AspNetUsers.UserNameIndex', because it does not exist or you do not have permission.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:3ec80fda-53a6-4c66-bdf4-c50e1c67e3dc
Error Number:3701,State:6,Class:11
System.Data.SqlClient.SqlException (0x80131904): Cannot drop the index 'AspNetUsers.UserNameIndex', because it does not exist or you do not have permission.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:3ec80fda-53a6-4c66-bdf4-c50e1c67e3dc
Error Number:3701,State:6,Class:11
Cannot drop the index 'AspNetUsers.UserNameIndex', because it does not exist or you do not have permission.
```

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio Enterprise 2017

**Comment by ajcvickers** [comment] 2017-09-11 17:13
@shammelburg Is the schema on your localdb instance different to the one on your other SQL Server instance? Has the SQL Server schema been modified by other Migrations or manual changes since it was created?

**Comment by shammelburg** [comment] 2017-09-18 06:59
@ajcvickers The schema is the same. Nothing has been modified.

**Comment by ajcvickers** [comment] 2017-09-18 16:31
@shammelburg That's very surprising. I was expecting that the schema would be different and the main thrust of the investigation here would be figuring how they got to be different and what to do about it. How did you determine the schema was the same in both cases? Do they both contain the UserNameIndex or both not contain the UserNameIndex?

**Comment by ajcvickers** [comment] 2017-09-27 17:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:20 UTC
Labels: closed-could-not-reproduce
