### ISSUE TITLE
Setting lazy property to null doesn't persist change to database if the property has not been loaded yet

### ISSUE THREAD

**Issue by jasonhill** [dotnet/efcore#23248] opened 2020-11-10 03:11 UTC
We are using lazy loading with EF core and are finding that setting a lazy loaded property to null when it hasn't already been loaded does not actually nullify the value in the database.

For example, let's say we have Article and Author entities in the database. We have an Article in the database that is linked to an Author of "John Doe".

If we retrieve that Article from the database and then set the Author to null, this change is not persisted to the database.

If we retrieve that Article from the database and navigate the Author property first before setting it to null, then the change is persisted to the database.

Is this expected behaviour? We are using v5.0.0-rc2.20475.6.

**Comment by ajcvickers** [comment] 2020-11-10 16:43
Duplicate of #14086

**Closed** 2022-10-16 19:08 UTC
Labels: closed-duplicate, customer-reported
