### ISSUE TITLE
No database provider has been configured

### ISSUE THREAD

**Issue by ondrejtomcik** [dotnet/efcore#20168] opened 2020-03-04 07:20 UTC
Greetings,
I am now facing the same issue as was already mentioned here https://github.com/dotnet/efcore/issues/4825. When creating an initial migration, following error is returned.
```
...
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Release'.
System.NullReferenceException: Object reference not set to an instance of an object.
An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: Object reference not set to an instance of an object.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'ConfigDbContext'.
Found DbContext 'IdentitiesDbContext'.
Found DbContext 'OAuthDbContext'.
Found DbContext 'PersistedGrantDbContext'.
Using context 'IdentitiesDbContext'.
System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, IDbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
```
Setup:
- `Microsoft.EntityFrameworkCore.*` `3.1.2`
- up to date `dotnet ef migrations tool`

`IdentitiesDbContext.cs`
```
public class IdentitiesDbContext : IdentityDbContext<TenantUser, Role, string, IdentityUserClaim<string>, UserRole, IdentityUserLogin<string>, IdentityRoleClaim<string>, IdentityUserToken<string>>
{        
        public IdentitiesDbContext(DbContextOptions<IdentitiesDbContext> options) : base(options) { }
        public IdentitiesDbContext() { }
}
```
`Startup.cs`
```
        private readonly IConfiguration _configuration;

        public Startup(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public void ConfigureServices(IServiceCollection services)
        {
            var connectionString = _configuration.GetConnectionString("DefaultConnection");
            var assemblyName = typeof(DbInitializer).GetTypeInfo().Assembly.GetName().Name;
            services.AddDbContext<IdentitiesDbContext>(b => b.UseLazyLoadingProxies().UseSqlite(connectionString, o => o.MigrationsAssembly(assemblyName)));
        }
```

When starting an application, constructor `IdentitiesDbContext(DbContextOptions<IdentitiesDbContext> options)` is called. When calling `dotnet ef migrations add -c IdentitiesDbContext -s src/Project/Project.csproj -p src/Project.Db/Project.Db.csproj
 -o Data/Migrations/IdentitiesDb -v Initial`,
`DbContextOptions` are not configured. (verified in `OnConfiguring(DbContextOptionsBuilder options)`) and parameter less constructor is called.

**Comment by kamekaioken** [comment] 2020-03-04 09:44
Can you try removing the parameter less constructor of `IdentitiesDbContext ` and just leave one constructor?
I think DI container cannot resolve an instance when multiple constructors are provided.

**Comment by kamekaioken** [comment] 2020-03-04 09:45
Can you try removing the parameter less constructor of `IdentitiesDbContext ` and just leave the constructor with the options parameter?

**Comment by kamekaioken** [comment] 2020-03-04 09:55
Can you try calling the base constructor in the parameter less constructor?
`public IdentitiesDbContext() : base() { }`

**Comment by ondrejtomcik** [comment] 2020-03-04 10:04
I tried already. No difference.

**Comment by kamekaioken** [comment] 2020-03-04 10:05
What about removing the parameter less constructor completely?
Sorry for suggesting trial and error advices, but I don't have any suitable environment to test it by myself right now.

**Comment by ondrejtomcik** [comment] 2020-03-04 10:46
This is no more possible in the `3.1.2`. See error below:
```
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'IdentitiesDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
 ---> System.MissingMethodException: No parameterless constructor defined for type 'Kistler.KiConnect.IdentityDatabase.Data.IdentitiesDbContext'.
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_3.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to create an object of type 'IdentitiesDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

**Comment by ajcvickers** [comment] 2020-03-04 16:33
@ondrejtomcik Does your code match the patterns shown in the [link from the exception](https://go.microsoft.com/fwlink/?linkid=851728)?  In particular, do you have a `CreateHostBuilder` as shown?

**Comment by ondrejtomcik** [comment] 2020-03-04 21:38
Yes, I do.
```
public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration(configuration => {
                    configuration.SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                        .AddJsonFile("appsettings.json", false, true)
                        .AddOsIndependentEnvironmentVariables();
                })
                .UseWindowsService()
                .ConfigureWebHostDefaults(webBuilder => {
                    webBuilder
                        .UseKestrel()
                        .ConfigureLogging((hostingContext, loggingBuilder) => loggingBuilder.ClearProviders())
                        .UseContentRoot(AppDomain.CurrentDomain.BaseDirectory)
                        .ConfigureKestrel(options =>
                        {
                            options.ListenAnyIP(3001, o =>
                            {
                                o.Protocols = HttpProtocols.Http1AndHttp2;
                            });
                        })
                .UseStartup<Startup>();
            })
            .ConfigureLogging((hostingContext, logging) => {
                logging.ClearProviders();
                if (WindowsServiceHelpers.IsWindowsService())
                    logging.AddEventLog(hostingContext.Configuration.GetSection("Logging:EventLog").Get<EventLogSettings>());
                logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Debug);
            })
            .UseNLog();
```

**Comment by ajcvickers** [comment] 2020-03-06 17:15
@ondrejtomcik Please attach a small, runnable project that reproduces the behavior you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-03-13 16:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by angyisz** [comment] 2021-01-28 09:21
@ajcvickers @ondrejtomcik I had the same problem (No parameterless constructor defined...) but every code were perfect. The root cause was that my DesignTimeDbContextFactory was in a core project named: EF
I recreated the project in other name and it works. I think this class name conflicted: https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.ef?view=efcore-5.0

**Closed** 2022-10-16 18:14 UTC
Labels: closed-could-not-reproduce, customer-reported
