### ISSUE TITLE
Incorrect SQL generation: Navis not translated after the query is pushed down to subquery

### ISSUE THREAD

**Issue by PawelGerr** [dotnet/efcore#27419] opened 2022-02-09 22:35 UTC
The SQL statement is missing `JOINs` when projecting a navi after the query is pushed down into subquery.

## Repro

In the repro I'm using the method `Distinct()` to trigger `PushdownIntoSubquery()`, but the issue should be reproducible with other operations (that lead to `PushdownIntoSubquery()`) as well.

**csproj file**
```XML
<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <OutputType>Exe</OutputType>
      <TargetFramework>net6.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
   </PropertyGroup>

   <ItemGroup>
     <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.2" />
     <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
   </ItemGroup>

</Project>
```

**DbContext and Entity**
```C#
using Microsoft.EntityFrameworkCore;

namespace EfCoreSubQueryIssue;

public class DemoDbContext : DbContext
{
   public DbSet<DemoEntity> DemoEntities { get; set; }

   public DemoDbContext(DbContextOptions<DemoDbContext> options)
      : base(options)
   {
   }
}

public class DemoEntity
{
   public Guid Id { get; set; }

   public Guid? ParentId { get; set; }
   public DemoEntity? Parent { get; set; }
}
```

**Program.cs**

```C#
using EfCoreSubQueryIssue;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

var loggerFactory = LoggerFactory.Create(builder => builder
                                                    .SetMinimumLevel(LogLevel.Trace)
                                                    .AddConsole());

var options = new DbContextOptionsBuilder<DemoDbContext>()
              .UseSqlite("DataSource=:memory:")
              .UseLoggerFactory(loggerFactory)
              .Options;

using var dbContext = new DemoDbContext(options);
dbContext.Database.OpenConnection();
dbContext.Database.EnsureCreated();
```

No issue when having the combination ` .Select(e => e)` + `.Distinct()` before ` .Select(e => new { e.Id, ParentId = e.Parent.Id })`

```C#
// produces correct SQL:
//
// SELECT "t"."Id", "d0"."Id" AS "ParentId"
// FROM
// (
//    SELECT DISTINCT "d"."Id", "d"."ParentId"
//    FROM "DemoEntities" AS "d"
//  ) AS "t"
// LEFT JOIN "DemoEntities" AS "d0" ON "t"."ParentId" = "d0"."Id"
dbContext.DemoEntities
         .Select(e => e)
         .Distinct()
         .Select(e => new { e.Id, ParentId = e.Parent!.Id })
         .ToList();
```

When changing the 1st select to ` .Select(e => new { e })` then the subquery seam to break the internal mapping , so the expression `e.Parent` cannot be bound anymore. The `LEFT JOIN` is gone.
There are no warnings nor errors.

```C#
// LEFT JOIN is missing
//
// SELECT "t"."Id", "t"."ParentId"
// FROM
// (
//    SELECT DISTINCT "d"."Id", "d"."ParentId"
//    FROM "DemoEntities" AS "d"
//  ) AS "t"
dbContext.DemoEntities
         .Select(e => new { e })
         .Distinct()
         .Select(e => new { e.e.Id, ParentId = e.e.Parent!.Id })
         .ToList();
```

The issue is more obvious with `e.Parent.Parent.Id` instead of `e.Parent.Id` because now there should be 2 `JOINs` but we have none.

```C#
// 2 LEFT JOINs are missing
//
// SELECT "t"."Id", "t"."ParentId"
// FROM
// (
//    SELECT DISTINCT "d"."Id", "d"."ParentId"
//    FROM "DemoEntities" AS "d"
// ) AS "t"
dbContext.DemoEntities
         .Select(e => new { e })
         .Distinct()
         .Select(e => new { e.e.Id, ParentId = e.e.Parent.Parent!.Id })
         .ToList();

```

## provider and version information

EF Core version: 6.0.2
Database provider: Microsoft.EntityFrameworkCore.Sqlite and Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0)
Operating system: Win10 x66
IDE: Jetbrains Rider 2021.3.3

**Comment by maumar** [comment] 2022-02-17 01:39
duplicate of #24263

**Closed** 2022-10-16 20:25 UTC
Labels: closed-duplicate, customer-reported
