### ISSUE TITLE
Migrations: Order columns of abstract base class properties last in CreateTable

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/efcore#11314] opened 2018-03-17 18:01 UTC
Before the release of **Entity Framework Core 2.1**, Entity Framework Core team announced that,

>  Column ordering in migrations: Based on customer feedback, we have updated migrations to initially generate columns for tables in the same order as properties are declared in classes.

but unfortunately, it is not working as expected in case of the following scenarios:

```
public abstract class AuditModel
{
    public int? CreatedBy { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public int? ModifiedBy { get; set; }
    public DateTime? ModifiedAt { get; set; }
    public bool IsActive { get; set; } = true;
}

public class Employee : AuditModel
{
   [Key]
   [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
   public long EmployeeId { get; set; }

   public string EmployeeNo { get; set; }

   [ForeignKey("Company")]
   public long CompanyId { get; set; }

   [ForeignKey("CompanyOffice")]
   public long OfficeId { get; set; }

   [ForeignKey("Section")]
   public long SectionId { get; set; }
    ..........................
}
```

Entity Framework Core Migration is generating the Employee Table columns as the following order:

      [CreatedBy] <-----
      ,[CreatedAt] <-----
      ,[ModifiedBy] <-----
      ,[ModifiedAt] <-----
      ,[IsActive] <-----
      ,[EmployeeId]
      ,[EmployeeNo]
      ,[CompanyId]
      ,[OfficeId]
      ,[SectionId]
      ............

Actually It should have been:

      ,[EmployeeId]
      ,[EmployeeNo]
      ,[CompanyId]
      ,[OfficeId]
      ,[SectionId]
       ............
      ,[CreatedBy] <-----
      ,[CreatedAt] <-----
      ,[ModifiedBy] <-----
      ,[ModifiedAt] <-----
      ,[IsActive] <-----

Note that, **Entity Framework 6.x** Migration generates the columns as expected order even in case of inheritance.

**Comment by ajcvickers** [comment] 2018-03-19 19:34
@TanvirArjel Can you be more specific about what is "wrong" with the order generated? For example, is it just that the primary key is not the first column? Or is it also that the unmapped base type should go at the end? If the latter, then what is the logic that determines this and would that also be true if it was a mapped base type?

**Comment by TanvirArjel** [comment] 2018-03-19 21:54
@ajcvickers  Yes! Primary key should be the first column and the unmapped based type columns should go at the end..

**Comment by ajcvickers** [comment] 2018-03-19 21:58
@TanvirArjel Can you provide an explanation as to why the unmapped base type should go at the end and whether or not this should also be the case for a  mapped base type? (I'm not saying you're wrong, I'm just trying to understand what the reasoning is behind this ordering.)

**Comment by TanvirArjel** [comment] 2018-03-20 08:36
Dear @ajcvickers , Thanks for your persistent reply.

Does it make sense that the primary key of the table at column no. 5 or so other than the first column of the table? Look at the two orders of the columns in the question. Which makes sense? Which is more meaningful? Obviously not the first order..Hope,you will also be agree with me.

In case of unmapped based type, yes! it also be more readable and rational that unmapped based type columns should go at the end of the table because normally in the common unmapped base type we put the columns which are common to the every table like CreatorName, CreationTime, ModifierName, ModificationTime etc. These columns at the beginning of the table does not make sense.

Point to be noted that, In Entity Framework 6.2.0, Primary key of the table is always the first column and both unmapped  and mapped based type goes at the end. This really makes sense!

I know Entity Framework Core is a breaking change from Entity Framework but what's wrong to bring these already accustomed,well tested and more sensible behaviors from Entity Framework to Entity Framework Core?

**Comment by ajcvickers** [comment] 2018-03-20 16:13
@TanvirArjel Thanks for the additional information. It will help us decide our course of action here.

**Comment by ajcvickers** [comment] 2018-03-22 02:33
Triage decisions:
* Primary keys first
* Un-mapped base classes at end

**Comment by TanvirArjel** [comment] 2018-03-22 04:53
Dear @ajcvickers,  Thanks a lot! for taking speedy action..That's why we love and rely on Microsoft  :)

**Comment by JairoMarques** [comment] 2018-06-29 15:05
I think this is also related to this question:

```c#
public override void Configure(EntityTypeBuilder<User> builder)
{
	base.Configure(builder);
	builder.ToTable("Users");
	builder
		.Property(x => x.Id)
		.HasColumnName("UserId");
	builder
		.Property(x => x.Active)
		.IsRequired()
		.HasColumnName("Active");
	builder
		.Property(x => x.UserCode)
		.HasMaxLength(255)
		.IsRequired()
		.HasColumnName("UserCode");
	builder
		.Property(x => x.Nome)
		.HasMaxLength(255)
		.IsRequired()
		.HasColumnName("Name");
	builder
		.Property(x => x.ResellerId)
		.HasColumnName("ResellerId");
	builder
		.HasOne(x => x.Reseller)
		.WithMany()
		.HasForeignKey(x => x.ResellerId);
	builder
		.Property(x => x.Password)
		.HasMaxLength(96)
		.IsFixedLength(true)
		.IsUnicode(false)
		.IsRequired()
		.HasColumnName("Password");
}
```
		
I'm waiting for this column order:

UserId
Active
UserCode
Name
**ResellerId
Password**

Instead I'm getting this column order:

UserId
Active
UserCode
Name
**Password
ResellerId**

**Comment by JairoMarques** [comment] 2018-06-29 16:06
Sorry, my bad. The columns order is related to properties in my class not the order in the Configure method.

**Comment by shargon** [comment] 2018-08-11 07:53
Any update about this?

**Comment by ajcvickers** [comment] 2018-08-13 16:03
@TanvirArjel This issue is in the 3.0 milestone. This means it is currently planned to be fixed for the 3.0 release.

**Comment by nunorelvao** [comment] 2018-09-17 13:49
I also would love to have the possibility to work with order annotations eg:

`public class BaseModel
    {
        [Key, Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Column(Order = 100, TypeName = "datetime")]
        public DateTime Base_Addeddate { get; set; }

        [Column(Order = 101, TypeName = "datetime")]
        public DateTime Base_Modifieddate { get; set; }

        [Column(Order = 102, TypeName = "nvarchar(50)")]
        public string Base_Username { get; set; }

        [Column(Order = 103)]
        [MaxLength(255)]
        public string Base_Ipaddress { get; set; }

        [Column(Order = 104)]
        public bool? Base_Enabled { get; set; }
    }

public class Language : BaseModel
    {
        [Column(Order = 2)]
        public string Code { get; set; }

        [Column(Order = 3)]
        public string Name { get; set; }

        [InverseProperty("Language")]
        public virtual IList<Country> Countries { get; set; }
    }
`

Will this be possible? AS currently the order is created is by Name!  and ignores totally this Annotation!

So the idea is to have the order as described even by inherited classes!

**Comment by TanvirArjel** [comment] 2018-09-18 03:54
@nunorelvao  Think! you have hundred of model classes with lots of columns. Then imagine how many times you have to write `order` annotations.

**Comment by smitpatel** [comment] 2018-10-19 19:08
Primary Keys first fixed in #13678

**Comment by TrevorFradsham** [comment] 2019-01-24 13:24
Is there any further work being doing to allow the order of the fields to be set? I have an SoftDeleted class with fields to handle logical deletion and it is inherited by any any class that would like this feature. The problem: the fields from the inherited class are always shown immediately after the primary key field. I understand that I can control the order of the fields within a class, but I cannot across an inherited class.

```
    public class SoftDeleted : ISoftDeleted
    {
        public DateTime? DeletedOn { get; set; }
        public String DeletedBy { get; set; }
    }
```

Just a thought:  is it possible to have an annotation [PriorityOrder(n)] so you can control the order of the column generation? ex: to 

```
     [PriorityOrder(300)]
    public class SoftDeleted : ISoftDeleted
    {
        public DateTime? DeletedOn { get; set; }
        public String DeletedBy { get; set; }
    }
    [PriorityOrder(100)]
    public class MyClass: SoftDeleted
    {
        [Key]
        public int Id { get; set; }
        public String Comment{ get; set; }
    }
```


so the migration output would look like
 
```
       protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "MyClass",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Comment= table.Column<string>(nullable: true),
                    DeletedOn = table.Column<DateTime>(nullable: true),
                    DeletedBy = table.Column<string>(nullable: true),
                    
```

instead of: 

```
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "MyClass",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    DeletedOn = table.Column<DateTime>(nullable: true),
                    DeletedBy = table.Column<string>(nullable: true),
                    Comment= table.Column<string>(nullable: true),
```

**Comment by TrevorFradsham** [comment] 2019-01-24 19:23
thanks for the link. I am not seeing that there is any progress for Column order for EF Core. Will keep monitoring though.

**Comment by biliktamas79** [comment] 2019-02-15 13:53
+1 for the explicit orderable properties/columns.

**Comment by Olbrasoft** [comment] 2019-02-27 12:32
+1 for the explicit orderable properties/columns.

**Comment by bricelam** [comment] 2019-02-27 23:00
You're doing it wrong. We only count 👍 reactions on #10059. (joking, but true)

**Comment by TanvirArjel** [comment] 2019-04-23 17:25
@ajcvickers as you said:

> Triage decisions:
> 
> Primary keys first
> Un-mapped base classes at end

`Primary keys first` has been fixed! What about the `Un-mapped base classes at end`? Any update please?

**Comment by ajcvickers** [comment] 2019-04-24 15:06
@TanvirArjel The issue is currently in the 3.0 milestone, but 3.0 is still overbooked with work, so unfortunately this issue may have to be pushed back to a later release.

**Comment by ekuryla** [comment] 2019-08-07 17:21
This problem is creating messy code. What is the status of this issue (putting unmapped base classes at the end of a table)? In 3.0 Preview 4, I'm seeing naming convention changes- but nothing about the unmapped classes issue, which to me is more significant. No one in their right mind wants to see auditable table properties at the beginning of the table -- totally against industry standard. Does anyone have a workaround for this?

**Comment by ekuryla** [comment] 2019-08-07 17:27
Not using EF Core Migrations as the workaround is the wrong answer...lol

**Comment by ekuryla** [comment] 2019-08-07 17:47
Found this as workaround - https://stackoverflow.com/questions/55757687/order-columns-in-migrations-ef-core. This works...but not perfect. Alot of decoration...

**Comment by smitpatel** [comment] 2019-09-24 16:10
There are 81 more years to go before century ends. 😮

**Comment by bricelam** [comment] 2019-09-24 21:17
There were some improvements to this area in 3.0.0.

With our limited team of five engineers, we strive really hard to [prioritize our work appropriately](https://docs.microsoft.com/en-us/ef/core/what-is-new/#release-planning-process).

Just for perspective, this issue: ![image](https://user-images.githubusercontent.com/1226749/65550611-ce794d80-ded4-11e9-9d96-34f22c8d78c1.png); many-to-many: ![image](https://user-images.githubusercontent.com/1226749/65550670-f5378400-ded4-11e9-84f0-b8b392a2a4fa.png)

**Comment by jdanl89** [comment] 2019-09-26 21:11
The easiest work around is to do a migration without extending the base class. Then add the extension, and do another migration. It's not a good solution.
My first thought was that you should be able to do [Column(Order = -1)]... but this doesn't solve the issue of multiple levels of inheritance.

Really, there should be a class-level attribute for specifying whether the base class's properties come before or after those of the class in question... then you would add that attribute at each level of inheritance.

**Comment by administersoftware** [comment] 2019-10-04 12:30
Just tried this on one of my entities, I set the first property an annotation of [Column(Order = 0)], and then in the abstract class I set the only property an annotation of [Column(Order = 1000)] and generated my database. Sadly the column ordering was ignored and the property in the abstract class was generated as the 2nd property rather than the last :(

Now that NetCore3 is out I would think a lot more Dev's are going to run into this, I'm already thinking of taking the pain of removing my abstract classes to get the entity layout I require - and only because I'm fussy ;) But hopeful for a fix...

**Comment by bricelam** [comment] 2019-10-04 16:47
@administersoftware You're aware you can just reorder the columns in the generated migration, right? No need to refactor your entire model...

**Comment by administersoftware** [comment] 2019-10-04 17:52
No I did not. I will begin googlebinging, but if there is anything you can point me in the direction of I would be most grateful indeed.

Thank you.

**Comment by bricelam** [comment] 2019-10-04 18:00
``` csharp
migrationBuilder.CreateTable(
    name: "Posts",
    columns: table => new
    {
        // NB: You can reorder columns here
        PostId = table.Column<int>(nullable: false),
        Title = table.Column<string>(nullable: true),
        Content = table.Column<string>(nullable: true),
        BlogId = table.Column<int>(nullable: false)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Posts", x => x.PostId);
    });
``

**Comment by administersoftware** [comment] 2019-10-04 18:29
Thanks, I don't do migrations yet, I only build the database as application is still in development, so dropping and rebuilding locally is fine, schema changes are then done to online database used by devs, but will look into this right now.

**Comment by PatrickOliveros** [comment] 2019-10-08 14:48
> ```cs
> migrationBuilder.CreateTable(
>     name: "Posts",
>     columns: table => new
>     {
>         // TODO: Reorder columns here
>         PostId = table.Column<int>(nullable: false),
>         Title = table.Column<string>(nullable: true),
>         Content = table.Column<string>(nullable: true),
>         BlogId = table.Column<int>(nullable: false)
>     },
>     constraints: table =>
>     {
>         table.PrimaryKey("PK_Posts", x => x.PostId);
>     });
> ```

I am quite aware of this workaround although it defeats the purpose of doing migrations as there's another step that has to be done to get the order correctly. I thought the release of .NET Core 3.0 would have this one fixed and is it safe to assume that this won't even be available by .NET 5 release?

**Comment by administersoftware** [comment] 2019-10-08 16:29
> 
> 
> ```cs
> migrationBuilder.CreateTable(
>     name: "Posts",
>     columns: table => new
>     {
>         // TODO: Reorder columns here
>         PostId = table.Column<int>(nullable: false),
>         Title = table.Column<string>(nullable: true),
>         Content = table.Column<string>(nullable: true),
>         BlogId = table.Column<int>(nullable: false)
>     },
>     constraints: table =>
>     {
>         table.PrimaryKey("PK_Posts", x => x.PostId);
>     });
> ```

Thanks for this, a workaround it is, but a lot of pain :( Hopefully a better automated resolution will be available in due course.

**Comment by BernardBoakye** [comment] 2019-11-06 23:25
> ```cs
> migrationBuilder.CreateTable(
>     name: "Posts",
>     columns: table => new
>     {
>         // TODO: Reorder columns here
>         PostId = table.Column<int>(nullable: false),
>         Title = table.Column<string>(nullable: true),
>         Content = table.Column<string>(nullable: true),
>         BlogId = table.Column<int>(nullable: false)
>     },
>     constraints: table =>
>     {
>         table.PrimaryKey("PK_Posts", x => x.PostId);
>     });
> ```

Imagine you are working on large data entities with a lot of base entities. That will be really tedious.

**Comment by administersoftware** [comment] 2019-11-07 08:34
It sure was for me, took a couple of hours to do and check, sure hope it gets fixed soon.

**Comment by fradsham** [comment] 2019-11-08 23:57
I have been following this thread for a while. I was hoping that it would have been addressed with net core 3. I have a project with 57 objects and some are inherited, so reordering the builder files is not feasible. I have tested different approaches. For example to handle logical deletion as opposed to physical deletion of records, I have a root class that all are inherited from (code below). The DeletedBy field should appear as the second last field given its high column number (600) but it does not. It is always the third field any any generated migration files. The columns in the child class all have lower numbers.
```
public class SoftDeleted : ISoftDeleted
{
    [Column(Order = 601)]
    public DateTime? DeletedOn { get; set; }
    [Column(Order = 600)]
    public String DeletedBy { get; set; }
}
```

**Comment by no3Ldev** [comment] 2019-11-12 12:59
Also having the same problem that I have been troubleshooting for a while now. DataAnnotation "Column -> Order" does not work. Regardless whether you place column order annotation on the base class (higher index), or on the inheriting class (starting from 0), order still follows its own style - primary key first then the columns from the base class, then the remaining columns from the inheriting class.

[NewClass : BaseClass]
> pk_column
> column2
> column3

[BaseClass]
> base_userid
> base_timestamp

[DB Result]
> pk_column
> base_userid
> base_timestamp
> column2
> column3

Should have removed it from the DataAnnotation Column parameter option if they have no plan on fully supporting it :) Peace. Still looking for workarounds, anyone?

**Comment by no3Ldev** [comment] 2019-11-12 13:18
Also having the same problem that I have been working on for a while now. DataAnnotation "Column -> Order" parameter does not work. Regardless whether you place column order annotation on the base class with higher index, or on the inheriting class starting from 0, order still follows its own style - primary key first followed by the columns from the base class, then the remaining columns from the inheriting class.

```
[NewClass : BaseClass]
- pk_column
- column2
- column3

[BaseClass]
- base_userid
- base_timestamp

[DB Result]
- pk_column
- base_userid
- base_timestamp
- column2
- column3
```

Still looking for workarounds, anyone?

**Comment by Luis-Palacios** [comment] 2019-11-12 20:25
@no3Ldev sadly the only workarounds at the time are not using inheritance or sorting manually the CreateTable methods generated on the migrations  😢

**Comment by no3Ldev** [comment] 2019-11-14 14:05
well that's what i thought. this concern has been quite around for some time already. thank you

**Comment by TanvirArjel** [comment] 2019-11-17 16:32
This is a very weird bug which should been fixed in version 1.1. But it seems it would not be fixed even in .NET 8.0 in 2023. Frustrated! very frustrated.

**Comment by pklejnowski** [comment] 2019-12-28 16:05
Is there any workaround for this?

**Comment by tehZeno** [comment] 2019-12-28 16:40
> Is there any workaround for this?

I manually edited the files and changed the order; but it's a royal pain in the behind. 
Don't think there is a real workable workaround yet.

**Comment by administersoftware** [comment] 2019-12-29 11:04
> 
> 
> Is there any workaround for this?

I'm still manually edit the file, and as @tehZeno says, it's a royal pain in the behind :(

**Comment by drewpayment** [comment] 2019-12-30 03:33
> Is there any workaround for this?

This is wild. There are a multitude of issues that have been opened over the course of the last five years, closed for various reasons and ultimately hundreds, or possibly thousands, of hours wasted because no one has just fixed this issue. 

I was thinking about adopting .NET Core, but I mean......... this is painful after the last 30 minutes of reading through these issues.

**Comment by administersoftware** [comment] 2019-12-30 10:44
> 
> 
> > Is there any workaround for this?
> 
> This is wild. There are a multitude of issues that have been opened over the course of the last five years, closed for various reasons and ultimately hundreds, or possibly thousands, of hours wasted because no one has just fixed this issue.
> 
> I was thinking about using EF Core, but I mean......... this is painful after the last 30 minutes of reading through these issues.

@drewpayment I definitely agree to the number of hours wasted on this one issue, but I also understand that there are more important issues for the team to be focussed on, what we need is more people to upvote the priority of this issue. Atleast the issue remains open :)

**Comment by TanvirArjel** [comment] 2019-12-30 14:56
> @drewpayment I definitely agree to the number of hours wasted on this one issue, but I also understand that there are more important issues for the team to be focussed on, what we need is more people to upvote the priority of this issue. Atleast the issue remains open :)

Frankly speaking, **I am Microsoft fan** but I am obliged to say that may be Microsoft is now open source on paper but still they give damn to the open source community. It's very rare that they are taking any suggestion from the community. They always persists on their own thought irrespective whether it is right or wrong and it also does not matter what outsiders think.

You are talking about upvote. It has no impact on the Microsoft choice of priority. There lots of issues with hundreds of upvote and still not fixed just because of Microsoft thinking no need to fix those :'(

It they think yes it's time to fix these then they will fix these even no one upvote :'(

**Comment by Luis-Palacios** [comment] 2019-12-30 16:30
In any case for those of you that like me are manually ordering the migrations, have you found a way to order columns when adding a new column to an existing table?

**Comment by TanvirArjel** [comment] 2019-12-30 17:31
@Luis-Palacios No way! You have to do it manually.

**Comment by premchandrasingh** [comment] 2020-02-14 12:19
I managed ordering by customizing `SqlServerMigrationsAnnotationProvider` and `SqlServerMigrationsSqlGenerator`. Even though it says internal API, I think it is much cleaner until available out of the box. Here is git repo [https://github.com/premchandrasingh/EFCoreColumnOrder](https://github.com/premchandrasingh/EFCoreColumnOrder)

**Comment by DesarrolloNedugaTech** [comment] 2020-02-16 03:53
I tried it and it works, thanks and regards.

**Comment by Seabizkit** [comment] 2020-02-26 10:06
can this be fixed already we are on version 3.1 of ef core already. I would also like to see the "index" attribute back. like ef 6 had. I  wouldn't think it would be that hard to implement order by on attributes for migrations.

**Comment by bricelam** [comment] 2020-02-26 19:05
Yes, the plan is to fix this in the next version of EF Core. Here is the issue for an index attribute: #4050. I'm not sure what you mean by *order by on attributes for migrations*, but please always feel free to submit a PR; we're eager to help users fix their biggest pet peeves or implement small enhancements.

**Comment by zgonzales** [comment] 2020-05-12 22:11
Please fix this soon

**Comment by Seabizkit** [comment] 2020-05-13 20:07
@bricelam FYI just in case it wasn't clear

There are two attributes....
 
- "[Index(name), order, IsUnique = true)]" 
- "[Column(Order = 601)]"

What we are wanting is the order they are specified in the model.
when there is an abstract class inherited then they must be appended to the end except for the table key.

We also want to be able to specify preference.... so giving a lower Order will make it appear closer to the start. Basically what EF6 is doing with the added ability to specify higher or lower index on abstract classes.

This issue is more about the ordering than the Index, just sharing as you gave a link to the missing Index one, but the "bigger" issue is the order.

Index can be specified using fluent notation.
 
```
class entity
{
    Id 
    [Column(Order = 2)]
    DateCreated

    DateModfied
}

class persion : entity
{
     Name
     Email
}
```

the order
```
Id
DateCreated
Name
Email
DateModfied
```

**Comment by bricelam** [comment] 2020-08-10 21:38
Nobody here has any expectations about unmapped types in the middle of a hierarchy, right? This is just about the case identified in the issue description?

**Comment by bricelam** [comment] 2020-08-10 21:41
Also, if an owned type has an unmapped base type, it's properties should go next to the other owned type's properties, right?

**Closed** 2020-08-11 01:14 UTC
Labels: area-migrations, closed-fixed, poachable, punted-for-2.1, punted-for-3.0, type-enhancement

**Comment by TanvirArjel** [comment] 2020-08-11 01:18
>Nobody here has any expectations about unmapped types in the middle of a hierarchy, right?

Yes! but if anybody wants this then he/should be able to use `ColumnOrderAttribute` to specify the custom position,

**Comment by linkinpark2014** [comment] 2020-09-30 18:45
> 
> 
> I managed ordering by customizing `SqlServerMigrationsAnnotationProvider` and `SqlServerMigrationsSqlGenerator`. Even though it says internal API, I think it is much cleaner until available out of the box. Here is git repo https://github.com/premchandrasingh/EFCoreColumnOrder

This doesn't work with MySQL. Any thoughts?
here's the error I'm getting:

```
System.InvalidOperationException: The current migration SQL generator 'CustomSqlServerMigrationsSqlGenerator' is unable to generate SQL for operations
of type 'Microsoft.EntityFrameworkCore.Migrations.Operations.MySqlCreateDatabaseOperation'.
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder
builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.CreateCreateOperations()
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The current migration SQL generator 'CustomSqlServerMigrationsSqlGenerator' is unable to generate SQL for operations of type 'Microsoft.EntityFrameworkCore.Migrations.Operations.MySqlCreateDatabaseOperation'.
```

**Comment by pgiacomo69** [comment] 2020-10-16 20:32
Today, with Net 5.0 RC2 and Pomelo.EntityFrameworkCore.MySql:

 public partial class BaseEntity 
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("ID", Order = 0)]
        public long Id { get; set; }
        [Column("CREATED_AT", Order = 995)]
        [IgnoreDataMember]
        [JsonIgnore]
        public DateTime? CreatedAt { get; set; }
        [Column("CREATED_BY_SESSION_ID", Order = 996)]
        [IgnoreDataMember]
        [JsonIgnore]
        public long CreatedBySessionId { get; set; }
        [Column("UPDATED_AT", Order = 997)]
        [IgnoreDataMember]
        [JsonIgnore]
        public DateTime? UpdatedAt { get; set; }
        [Column("UPDATED_BY_SESSION_ID", Order = 998)]
        [IgnoreDataMember]
        [JsonIgnore]
        public long UpdatedBySessionId { get; set; }
        [Column("VERSION_ID", Order = 999)]
        public long? VersionId { get; set; }
    }

  [Table("Tb_Geo_Zone")]
    public class GeoZona :BaseEntity
    {
        [Required]
        [Column("codice", Order = 1)]
        [StringLength(10)]
        public string codice { get; set; }

        [Column("nome", Order = 2)]
        [StringLength(10)]
        public string Nome { get; set; }
    }

Sql autogenerated from Migration:

CREATE TABLE `Tb_Geo_Zone` (
    `ID` bigint NOT NULL AUTO_INCREMENT,
    `codice` varchar(10) CHARACTER SET utf8mb4 NOT NULL,
    `nome` varchar(10) CHARACTER SET utf8mb4 NULL,
    `CREATED_AT` datetime(6) NULL,
    `CREATED_BY_SESSION_ID` bigint NOT NULL,
    `UPDATED_AT` datetime(6) NULL,
    `UPDATED_BY_SESSION_ID` bigint NOT NULL,
    `VERSION_ID` bigint NULL,
    CONSTRAINT `PK_Tb_Geo_Zone` PRIMARY KEY (`ID`),
    CONSTRAINT `AK_Tb_Geo_Zone_codice` UNIQUE (`codice`)
);

At least it works!!!!

**Comment by skini82** [comment] 2022-03-10 09:37
I'm having the same issue in EF Core 6.0.3 on VS2022 with SQLServer DB
