### ISSUE TITLE
Query Filter does not work for owned types

### ISSUE THREAD

**Issue by BickelLukas** [dotnet/efcore#18534] opened 2019-10-23 11:01 UTC
When setting a query filter on an owned type it is ingored when loading the entity.

We are using EFCore owned types to represent aggregates in our domain model.

We are using soft deletion and have a query filter on all Entities that filter the Deleted from the result. But when loading an aggregate, the child collection contains all entries, even deleted ones.

### Steps to reproduce

Entities:
``` C#
interface IEntity {
    bool IsDeleted { get; }
}

class Parent : IEntity {
    public List<Child> Children { get; }
    public bool IsDeleted { get; }
}

class Child : IEntity {
    public bool IsDeleted { get; }
}
```
Configuration
``` C#
builder.Entity<Parent>().OwnsMany(x => x.Children);
```

Query Filter 
```C#
foreach (var entityType in builder.Model.GetEntityTypes().ToList())
{
    if (typeof(IEntity).IsAssignableFrom(entityType.ClrType))
    {
        var b = ((EntityType)entityType).Builder;

        Expression<Func<IEntity, bool>> ex = (e) => !e.IsDeleted;
        var param = Expression.Parameter(entityType);
        var body = new ParameterSubstitutionVisitor(param).Visit(ex.Body);
        builder.HasQueryFilter(Expression.Lambda(body, param), ConfigurationSource.Explicit);
    }
}
```

The query filter works for all entities. Only the owned collections ignore it completely.

### Further technical details

EF Core version: 3.1.0-preview1.19506.2
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET Core 3.0
Operating system: Windows/docker
IDE: Visual Studio 2019 16.3

**Comment by AndriySvyryd** [comment] 2019-10-23 16:30
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/14113

**Comment by BickelLukas** [comment] 2019-10-24 06:16
@AndriySvyryd This is not a duplicate but rather a regression, since this used to work in 2.2.6

Back then I could add the following line:
``` c#
builder.Entity<Child>().HasQueryFilter(x => !x.IsDeleted);
```

This is no longer allowed because I cannot configure a owned type as an entity type. Thats why I'm using the internal API in the example above. 

If this is not a supported scenario then at least an exception should be thrown when configuring a QueryFilter for an owned type. Right now it lets me configure the query filter without warnings but then silently ignores it.

**Comment by AndriySvyryd** [comment] 2019-10-24 06:50
@BickelLukas If you have to use internal API then it's not a supported scenario.

**Closed** 2022-10-16 14:51 UTC
Labels: closed-duplicate, customer-reported
