### ISSUE TITLE
Issue with dynamic 'OrderBy' and AutoMapper inherited types

### ISSUE THREAD

**Issue by onionhammer** [dotnet/efcore#18584] opened 2019-10-24 20:21 UTC
Similar description to #11453, but with EF Core 3.1 preview;

If I generate an 'OrderBy' using a dynamic expression, I receive an 'InvalidOperationException', 
"...could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either "

If I use the equivalent non-generated code, the query executes fine.

![image](https://user-images.githubusercontent.com/969938/67508583-e91b1f80-f656-11e9-84d6-4a3a1f88fa69.png)
![image](https://user-images.githubusercontent.com/969938/67508588-ed473d00-f656-11e9-8c74-df54a91b69cb.png)

`OrderByExpression()` is defined [here](https://gist.github.com/onionhammer/5137cefeface774af96af905a76593b6), and works for simple cases, but when combined with 

### Steps to reproduce
1. Ensure docker is installed
2. Run the following
```
git clone https://github.com/onionhammer/ReproduceEFCoreIssue.git
cd ReproduceEFCoreIssue
dotnet test
```

>  Error Message:
   System.InvalidOperationException : The LINQ expression 'OrderByDescending<Classroom, int>(
    source: DbSet<Classroom>,
    keySelector: (c) => new ClassroomViewModel{
        Classroom = c.Name,
        NumStudents = Count<Student>(Where<Student>(
            source: DbSet<Student>,
            predicate: (s) => Property<Nullable<Guid>>(c, "Id") != null && Property<Nullable<Guid>>(c, "Id") == Property<Nullable<Guid>>(s, "ClassroomId"))),
        TeacherNames = Select<Teacher, string>(
            source: Where<Teacher>(
                source: DbSet<Teacher>,
                predicate: (t) => Property<Nullable<Guid>>(c, "Id") != null && Property<Nullable<Guid>>(c, "Id") == Property<Nullable<Guid>>(t, "ClassroomId")),
            selector: (t) => t.Name)
    }
    .NumStudents)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
  Stack Trace:

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment] 2019-10-24 20:34
`NumStudents` likely you have wrong PropertyInfo in your member expression. See #18386

**Comment by onionhammer** [comment] 2019-10-24 20:37
@smitpatel Both expressions are the same, I verified the expression tree

**Comment by smitpatel** [comment] 2019-10-24 21:04
In the memberExpression `p => p.DateAdded`, the memberInfo.ReflectedType is different than what compiler generates. So manually generated expression tree is somewhat incorrect that compiler generated. Hence it does not work. Exact duplicate of #18386

**Comment by onionhammer** [comment] 2019-10-24 21:15
@smitpatel So since this code worked flawlessly for years in EntityFramework, what is it, in practical terms, about EF Core that doesnt like this code

**Comment by smitpatel** [comment] 2019-10-24 21:20
```C#
// Form1
new ClassroomViewModel {
    Classroom = c.Name,
    NumStudents = s.Students.Count()
}.NumStudents

// Form2
s.Students.Count()
```

In order for us to convert Form1 to form2, the MemberInfo inside ClassroomViewModel  NumStudents must match MemberInfo used in MemberExpression. In your dynamically generated case they are different so we cannot simplify it. So you get error. Given compiler does not generate that kind of expression tree, it is low priority for us to try to support such scenarios.

**Comment by onionhammer** [comment] 2019-10-24 21:29
So in other words, it's an open bug, not a closed bug? but you're saying you wont fix it?

These expressions look identical to me, left hand side is defined statically, the right hand side is dynamically constructed

![image](https://user-images.githubusercontent.com/969938/67526925-635d9b00-f67b-11e9-97f0-acc1d959523c.png)

**Comment by smitpatel** [comment] 2019-10-24 21:32
`ReflectedType` is different in both sides.
It's closed bug because right now we don't think we will ever get time to fix it.

**Comment by onionhammer** [comment] 2019-10-25 13:40
@smitpatel thanks, I must be blind :)

If anyone is interested, I've updated the GIST with the working 'ObjectQueryExtensions.cs'

**Comment by liuliang-wt** [comment] 2019-11-21 12:00
I also run into this trouble , constructing a dynamic expression is critical to our product. For example, we let user only write basic select query, and we add orderby expression dynamically when he click a list title. If you are not going to fix this, please at least tell me a walk around.

**Comment by liuliang-wt** [comment] 2019-11-21 14:22
@onionhammer  hi, have you solved this problem?

**Comment by smitpatel** [comment] 2019-11-21 16:32
@liuliang-wt - See https://github.com/aspnet/EntityFrameworkCore/issues/18386#issuecomment-546109304

**Comment by onionhammer** [comment] 2019-11-21 21:39
@liuliang-wt Take a look at this:

https://gist.github.com/onionhammer/5137cefeface774af96af905a76593b6

**Comment by smitpatel** [comment] 2019-12-05 18:55
We are enabling support for this scenario in #19182

**Closed** 2022-10-16 14:52 UTC
Labels: customer-reported
