### ISSUE TITLE
Reconsider UseSqlServer SqlConnectionStringBuilder overloads

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#15664] opened 2019-05-08 21:13 UTC
These were added for #1238, but after playing with the implementation, @divega didn't find them as useful as he initially thought they would be since SqlConnectionStringBuilder isn't very fluent.

We should either consider alternative designs or just remove them before the final 3.0.0 release.

**Comment by divega** [comment] 2019-05-08 21:16
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/15642? :smile:

**Closed** 2022-10-16 14:20 UTC
