### ISSUE TITLE
TPH Where Filter ignores derived classes

### ISSUE THREAD

**Issue by wdnijdam** [dotnet/efcore#4071] opened 2015-12-14 15:49 UTC
7.0.0-rc1-final
When using a class hierarchy and TPH mapping:

```
Item (abstract base)
     Base2Item (discriminator '2')
          ItemA (discriminator 'A'
          ItemB (discriminator 'B')
     ItemC (discriminator 'C')
```

And executing `var aItems = db.Items.OfType<Base2Item>().ToList();`

The created SQL code is:

```
SELECT [i].[ItemId], [i].[ItemType], [i].[PropA], [i].[PropB], [i].[PropC]
FROM [Item] AS [i]
WHERE [i].[ItemType] = '2'
```

The result set is wrong. It should contain ItemA and ItemB types from the table.
I would expect `WHERE [i].[ItemType] in ('2' , 'A', 'B')`

**Comment by rowanmiller** [comment] 2015-12-22 23:10
I am not able to reproduce this issue. On both RC1 and the latest nightly build I see the correct query generated:

```sql
SELECT [i].[ItemId], [i].[Name], [i].[discriminator], [i].[PropA], [i].[PropB], [i].[PropC]
FROM [Item] AS [i]
WHERE [i].[discriminator] IN ('B', 'A', '2')
```

Here is the code I used to test:

```c#
using Microsoft.Data.Entity;
using System.Linq;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new SampleContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                var aItems = db.Items.OfType<Base2Item>().ToList();
            }
        }
    }

    public class SampleContext : DbContext
    {
        public DbSet<Item> Items { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Item>()
                .HasDiscriminator<string>("discriminator")
                .HasValue<Base2Item>("2")
                .HasValue<ItemA>("A")
                .HasValue<ItemB>("B")
                .HasValue<ItemC>("C");
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Sample;Trusted_Connection=True;");
        }
    }

    public abstract class Item
    {
        public int ItemId { get; set; }
        public string Name { get; set; }
    }

    public class Base2Item : Item
    {
    }

    public class ItemA : Base2Item
    {
        public string PropA { get; set; }
    }

    public class ItemB : Base2Item
    {
        public string PropB { get; set; }
    }

    public class ItemC : Item
    {
        public string PropC { get; set; }
    }
}
```

Can you share a complete code listing that demonstrates the issue you are seeing?

**Comment by wdnijdam** [comment] 2015-12-23 15:59
Rowan,

I can confirm your code operates correctly.

But if you add the Discriminator value for item (HasValue<Item>("I")) the code returns the wrong result.

modelBuilder.Entity<Item>()
                .HasDiscriminator<string>("ItemType")
                .HasValue<Item>("I")
                .HasValue<ItemA>("A")
                .HasValue<ItemB>("B")
                .HasValue<ItemC>("C")
                .HasValue<Base2Item>("2");

**Comment by wdnijdam** [comment] 2015-12-23 16:48
It also allows me to map the same value twice. I would expect an error in that case.

**Comment by rowanmiller** [comment] 2015-12-23 21:26
Confirmed that this is fixed on our latest code base (tested against 7.0.0-rc2-16619). We produce `WHERE [i].[discriminator] IN ('B', 'A', '2')` for all the code snippets you provided. 

Opened https://github.com/aspnet/EntityFramework/issues/4170 for the duplicate discriminator values issue (agreed that is a bug).

**Closed** 2022-10-16 09:20 UTC
