### ISSUE TITLE
EF Core 7 In-Memory database provider throws while evaluating value conversions.

### ISSUE THREAD

**Issue by fiseni** [dotnet/efcore#30121] opened 2023-01-23 17:45 UTC
The behavior is observed in `EF Core 7` and affects only the in-memory database provider. It worked correctly in `EF Core 6.0.13`.

**Scenario:**
- An entity `X` contains a property `Y` of arbitrary type.
- The property is defined as nullable, and the corresponding DB column is created as nullable.
- The property is configured using a value converter.
- If we query the entity for records with `null` value for property `Y`, then:
	- For `SqlServer` provider, the expression is translated correctly and we get filtered data.
	- For `In-Memory` provider, it throws an exception.

**Sample App:**

If we run the following sample, it will throw an exception. If we switch the provider then correct behavior is observed.
Also, if we switch to version `6.0.13`, the in-memory provider works correctly too.

```c#
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="7.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.2" />
  </ItemGroup>

</Project>

```

```c#
using Microsoft.EntityFrameworkCore;

var connectionString = "Server=(localdb)\\mssqllocaldb;Database=EF7InMemoryDbIssue;Trusted_Connection=True;";
var dbContextOptionsSqlServer = new DbContextOptionsBuilder<AppDbContext>().UseSqlServer(connectionString).Options;
var dbContextOptionsInMemory = new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;

// If we change to dbContextOptionsSqlServer everything works correctly!
var dbContextOptions = dbContextOptionsInMemory;

using (var dbContext = new AppDbContext(dbContextOptions))
{
    await dbContext.Database.EnsureDeletedAsync();
    await dbContext.Database.EnsureCreatedAsync();

    var customers = new List<Customer>
    {
        new Customer {Type = new CustomerType(1)},
        new Customer {Type = null},
        new Customer {Type = new CustomerType(3)}
    };

    dbContext.Customers.AddRange(customers);
    await dbContext.SaveChangesAsync();
}

using (var dbContext = new AppDbContext(dbContextOptions))
{
    var result = await dbContext.Customers
        .Where(x => x.Type == null)
        .ToListAsync();

    Console.WriteLine($"Found {result.Count} records!");
}

class CustomerType
{
    public int Value { get; }

    public CustomerType(int value)
    {
        Value = value;
    }
}

class Customer
{
    public int Id { get; set; }
    public CustomerType? Type { get; set; }
}

class AppDbContext : DbContext
{
    public DbSet<Customer> Customers => Set<Customer>();

    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options) { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>().Property(x => x.Type).HasConversion(x => x!.Value, x => new CustomerType(x)); 
    }
}
```

**Comment by ajcvickers** [comment] 2023-01-24 18:50
@fiseni Please post the exception message and stack trace.

**Comment by fiseni** [comment] 2023-01-24 19:24
Oh sorry, here it is. Btw, the above code is the full app, so you can run it directly.

```
System.ArgumentException
  HResult=0x80070057
  Message=Expression of type 'System.Object' cannot be used for constructor parameter of type 'System.Int32' (Parameter 'arguments[0]')
  Source=System.Linq.Expressions
  StackTrace:
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Dynamic.Utils.ExpressionUtils.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments, String methodParamName)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at System.Linq.Expressions.NewExpression.Update(IEnumerable`1 arguments)
   at Microsoft.EntityFrameworkCore.Query.ReplacingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ReplacingExpressionVisitor.Replace(Expression original, Expression replacement, Expression tree)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryExpressionTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryExpressionTranslatingExpressionVisitor.TranslateInternal(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryExpressionTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateExpression(Expression expression, Boolean preserveType)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateLambdaExpression(ShapedQueryExpression shapedQueryExpression, LambdaExpression lambdaExpression, Boolean preserveType)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in D:\Projects\NET\Temp\EF7InMemoryDbIssue\EF7InMemoryDbIssue\Program.cs:line 30

```

**Comment by ajcvickers** [comment] 2023-01-24 19:28
Duplicate of #29603

**Closed by ajcvickers** 2023-01-24 19:28 UTC
Labels: customer-reported
