### ISSUE TITLE
SQLite: Make AUTOINCREMENT more first-class

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#10597] opened 2017-12-20 20:01 UTC
Right now, `AUTOINCREMENT` is more  or less an implementation detail of SQLite Migrations. We should make it more first-class like `IDENTITY` on SQL Server. This would include a convention, `ModelBuilder` API, validation, etc. for it.

**Comment by smitpatel** [comment] 2017-12-20 20:05
Duplicate of #10228

**Comment by bricelam** [comment] 2017-12-20 20:14
Thanks, I saw it but didn't read it since the title looked unrelated. I'll update its title.

**Closed** 2022-10-16 12:03 UTC
Labels: closed-duplicate
