### ISSUE TITLE
Scaffold-Dbcontext not working in .Net Core 1.1 project after updating VS 2017 to 15.1.1/.Net Core 2.0 installed

### ISSUE THREAD

**Issue by gopinathbecse** [dotnet/efcore#10583] opened 2017-12-18 10:20 UTC
My App has data layer project in .Net Core 1.1. When trying to reverse engineer my DB classes, the command `Scaffold-DbContext "Server=SQL2014;Database=MyAppDB;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -force` in PMC thows an exception.

The command was worked until I update VS 2017 to 15.5.1 which installed .Net Core 2.0. I am not in the position to migrate the solution to .Net Core 2.0 as everyone in my team may need an upgrade.

**Exception message:** 
Exception calling "AddFromFile" with "1" argument(s): "'basePath' cannot be an empty string ("") or start 
with the null character.
Parameter name: basePath"

**Stack trace:**
```
Using project 'MyProject.DAL'.
Using startup project 'MyProject.DAL'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile "E:\MyProject\DAL\bin\Debug\netcoreapp1.1\MyProject.DAL.deps.json" --additionalprobingpath C:\Users\User\.nuget\packages --fx-version 1.1.2 C:\Users\User\.nuget\packages\microsoft.entityframeworkcore.tools\1.1.1\tools\netcoreapp1.0\ef.dll dbcontext scaffold Server=SYSTEM1\SQL2014;Database=MyAppDB;Trusted_Connection=True; Microsoft.EntityFrameworkCore.SqlServer --json --output-dir "E:\MyProject\DAL\Models" --force --verbose --no-color --prefix-output --assembly "E:\MyProject\DAL\bin\Debug\netcoreapp1.1\MyProject.DAL.dll" --startup-assembly "E:\MyProject\DAL\bin\Debug\netcoreapp1.1\MyProject.DAL.dll" --project-dir "E:\MyProject\DAL\\" --content-root "E:\MyProject\DAL\\" --data-dir "E:\MyProject\DAL\bin\Debug\netcoreapp1.1\\" --root-namespace MyProject.DAL
```

### Further technical details
**.Net Core Version:**
```
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
```
**EF Core version:** 
```
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="1.1.2" />
    <PackageReference Include="NuGet.CommandLine" Version="4.1.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="1.4.0" />
    <PackageReference Include="Serilog.Sinks.Literate" Version="2.1.0" />
  </ItemGroup>
```
Database Provider: `Microsoft.EntityFrameworkCore.SqlServer`
Operating system: Win 7
IDE: **Visual Studio 2017 15.5.1**
`dotnet --version` returns 2.1.2

**Comment by gopinathbecse** [comment] 2017-12-18 10:31
Hello @bricelam. I need your help on this. I already tried most of the solutions in your git but nothing works. What should I need to do with EF Core to make it work again?

**Comment by bricelam** [comment] 2017-12-18 18:33
Hmm... What version of the PMC tools are loaded? (run `Get-Module`)

**Comment by bricelam** [comment] 2017-12-18 18:36
Also, does adding `-Verbose` give any additional information?

**Comment by bricelam** [comment] 2017-12-18 18:39
If you run this command directly, does it tell you more? ()

    dotnet exec --depsfile "E:\MyProject\DAL\bin\Debug\netcoreapp1.1\MyProject.DAL.deps.json" --additionalprobingpath C:\Users\User\.nuget\packages --fx-version 1.1.2 C:\Users\User\.nuget\packages\microsoft.entityframeworkcore.tools\1.1.1\tools\netcoreapp1.0\ef.dll dbcontext scaffold Server=SYSTEM1\SQL2014;Database=MyAppDB;Trusted_Connection=True; Microsoft.EntityFrameworkCore.SqlServer --json --output-dir "E:\MyProject\DAL\Models" --force --verbose --no-color --prefix-output --assembly "E:\MyProject\DAL\bin\Debug\netcoreapp1.1\MyProject.DAL.dll" --startup-assembly "E:\MyProject\DAL\bin\Debug\netcoreapp1.1\MyProject.DAL.dll" --project-dir "E:\MyProject\DAL\\" --content-root "E:\MyProject\DAL\\" --data-dir "E:\MyProject\DAL\bin\Debug\netcoreapp1.1\\" --root-namespace MyProject.DAL

**Comment by gopinathbecse** [comment] 2017-12-19 07:27
`Get-Module` gives,

```
ModuleType Name                                ExportedCommands                                                                                                                                                                                 
---------- ----                                ----------------                                                                                                                                                                                 
Script     EntityFrameworkCore                 {Add-Migration, Drop-Database, Enable-Migrations, Remove-Migration...}                                                                                                                           
Script     NuGet                               {Add-BindingRedirect, Find-Package, Get-Package, Get-Project...}                                                                                                                                 
Script     profile        
```

**Comment by gopinathbecse** [comment] 2017-12-19 07:36
@bricelam 
I am getting the below error by executing the command.

```
PM> dotnet exec --depsfile "D:\EFMigrationTest\ClassLibrary1\ClassLibrary1\bin\Debug\netcoreapp1.1\ClassLibrary1.deps.json" --additionalprobingpath C:\Users\User\.nuget\packages --fx-version 1.1.2 C:\Users\User\.nuget\packages\microsoft.entityframeworkcore.tools\1.1.1\tools\netcoreapp1.0\ef.dll dbcontext scaffold Server=SYSTEM1\SQL2014;Database=MyAppDB;Trusted_Connection=True; Microsoft.EntityFrameworkCore.SqlServer --json --output-dir "D:\EFMigrationTest\ClassLibrary1\ClassLibrary1\Models" --force --verbose --no-color --prefix-output --assembly "D:\EFMigrationTest\ClassLibrary1\ClassLibrary1\bin\Debug\netcoreapp1.1\ClassLibrary1.dll" --startup-assembly "D:\EFMigrationTest\ClassLibrary1\ClassLibrary1\bin\Debug\netcoreapp1.1\ClassLibrary1.dll" --project-dir "D:\EFMigrationTest\ClassLibrary1\ClassLibrary1\\" --content-root "D:\EFMigrationTest\ClassLibrary1\ClassLibrary1\\" --data-dir "D:\EFMigrationTest\ClassLibrary1\ClassLibrary1\bin\Debug\netcoreapp1.1\\" --root-namespace ClassLibrary1
dotnet : It was not possible to find any compatible framework version
At line:1 char:1
+ dotnet exec --depsfile "D:\EFMigrationTest\ClassLibrary1\ClassLibrary1\bin\Debug ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (It was not poss...amework version:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 

The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '1.1.2'.

Database=MyAppDB : The term 'Database=MyAppDB' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:335
+ ... YSTEM1\SQL2014;Database=MyAppDB;Trusted_Connection=True; Microsoft.EntityFramewo ...
+                    ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Database=MyAppDB:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Trusted_Connection=True : The term 'Trusted_Connection=True' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
At line:1 char:352
+ ... tabase=MyAppDB;Trusted_Connection=True; Microsoft.EntityFrameworkCore.SqlServer  ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Trusted_Connection=True:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Microsoft.EntityFrameworkCore.SqlServer : The term 'Microsoft.EntityFrameworkCore.SqlServer' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At line:1 char:377
+ ... nnection=True; Microsoft.EntityFrameworkCore.SqlServer --json --output-dir "D:\E ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.EntityFrameworkCore.SqlServer:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by gopinathbecse** [comment] 2017-12-19 07:39
My `.csproj` file

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.1" />
  </ItemGroup>

</Project>
```

**Comment by gopinathbecse** [comment] 2017-12-19 07:59
Downloaded and installed `.NET Core 1.1.2` from [here](https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.2-download.md) and now the command `Scaffold-DbContext "Server=SQL2014;Database=MyAppDB;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -force` working fine.

Only errors from command `dotnet exec --depsfile..` still exists.

It seems updating VS 2017 for .Net Core 2.0 deleted .Net Core 1.0 and caused the issue.

**Comment by bricelam** [comment] 2017-12-19 16:58
Glad it's working now! From an EF Core perspective, I think we can consider this issue a duplicate of  #10338. Please use the **Send Feedback** menu in VS to report that .NET Core 1.x was uninstalled.

![image](https://user-images.githubusercontent.com/1226749/34168942-ae0c8eb2-e49a-11e7-9820-39989d0274ad.png)

**Closed** 2022-10-16 12:03 UTC
Labels: closed-duplicate
