### ISSUE TITLE
the function of Self join / Self referencing urgently needs to be easy to use in 8.0.

### ISSUE THREAD

**Issue by yajiegithub** [dotnet/efcore#31645] opened 2023-09-06 05:24 UTC
```
public class User
{

 public string ID {get;set;}

public string Name {get;set}

   [InverseProperty("SentUser")]
   public List<Invitation>? Invitations { get; set; }

   [InverseProperty("ReceUser")]
   public List<Invitation>? Invitationed { get; set; }
}
```

```

public class Invitation
{
    public string SentID { get; set; }
    
public string ReceID { get; set; }

    public DateTime InvitTime{ get; set; }

  [ForeignKey(nameof(SentID))]
  [InverseProperty("Invitations")]
  public User SentUser { get; set; }

  [ForeignKey(nameof(ReceID))]
  [InverseProperty("Invitationed")]
  public User ReceUser { get; set; }

```

It is too difficult to use EFcore to solve this problem, and the function of Self join / Self referencing urgently needs to be easy to use in 8.0.

Thank you, development team. Thank you for your hard work

**Comment by ajcvickers** [comment] 2023-09-06 10:59
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-09-20 19:29
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-09-20 19:29 UTC
Labels: type-enhancement, customer-reported
