### ISSUE TITLE
Unable to move from build 16018 to 16105 on aspnetcidev

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#3553] opened 2015-10-25 08:11 UTC
**Failed to add reference to 'System.Collections.Concurrent'. Please make sure that it is in the Global Assembly Cache.**

With the SQL CE provider project: .NET 4.5.1 Class Library in VS 2015 with NuGet extension version: 3.2.60914, I get the error, when only updating Microsoft.Extensions.Logging from aspnetcidev, blocking me from moving to the latest RC1 bits. Also installing from a "empty" project with no NuGet dependencies causes the same error. 

PM> Install-Package Microsoft.Extensions.Logging -Pre
Attempting to gather dependencies information for package 'Microsoft.Extensions.Logging.1.0.0-rc1-15741' with respect to project 'EntityFramework.SqlServerCompact35', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for package 'Microsoft.Extensions.Logging.1.0.0-rc1-15741' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Microsoft.Extensions.Logging.1.0.0-rc1-15741'
Resolved actions to install package 'Microsoft.Extensions.Logging.1.0.0-rc1-15741'
Removed package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-15705' from 'packages.config'
Successfully uninstalled 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-15705' from EntityFramework.SqlServerCompact35
Removed package 'Microsoft.Extensions.Logging.1.0.0-rc1-15704' from 'packages.config'
Successfully uninstalled 'Microsoft.Extensions.Logging.1.0.0-rc1-15704' from EntityFramework.SqlServerCompact35
Removed package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-15704' from 'packages.config'
Successfully uninstalled 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-15704' from EntityFramework.SqlServerCompact35
Adding package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-15736' to folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Added package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-15736' to folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Added package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-15736' to 'packages.config'
Successfully installed 'Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0-rc1-15736' to EntityFramework.SqlServerCompact35
Adding package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-15741' to folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Added package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-15741' to folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Added package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-15741' to 'packages.config'
Successfully installed 'Microsoft.Extensions.Logging.Abstractions 1.0.0-rc1-15741' to EntityFramework.SqlServerCompact35
Adding package 'Microsoft.Extensions.Logging.1.0.0-rc1-15741' to folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Added package 'Microsoft.Extensions.Logging.1.0.0-rc1-15741' to folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Install failed. Rolling back...
Package 'Microsoft.Extensions.Logging 1.0.0-rc1-15741' does not exist in project 'EntityFramework.SqlServerCompact35'
Removed package 'Microsoft.Extensions.Logging.Abstractions 1.0.0-rc1-15741' from 'packages.config'
Removed package 'Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0-rc1-15736' from 'packages.config'
Package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-15704' already exists in folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Added package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-15704' to 'packages.config'
Package 'Microsoft.Extensions.Logging.1.0.0-rc1-15704' already exists in folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Added package 'Microsoft.Extensions.Logging.1.0.0-rc1-15704' to 'packages.config'
Package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-15705' already exists in folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Added package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-15705' to 'packages.config'
Removing package 'Microsoft.Extensions.Logging 1.0.0-rc1-15741' from folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Removed package 'Microsoft.Extensions.Logging 1.0.0-rc1-15741' from folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Removing package 'Microsoft.Extensions.Logging.Abstractions 1.0.0-rc1-15741' from folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Removed package 'Microsoft.Extensions.Logging.Abstractions 1.0.0-rc1-15741' from folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Removing package 'Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0-rc1-15736' from folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Removed package 'Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0-rc1-15736' from folder 'C:\Code\EntityFramework7.SqlServerCompact\packages'
Install-Package : **Failed to add reference to 'System.Collections.Concurrent'. Please make sure that it is in the Global Assembly Cache.**
At line:1 char:1
- Install-Package Microsoft.Extensions.Logging -Pre
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by tstar** [comment] 2015-10-26 11:56
Update first dnx to latest unstable:
set DNX_UNSTABLE_FEED=https://www.myget.org/F/aspnetcidev
dnvm upgrade -u
Then you can use the latest versions like 16105.

**Comment by natemcmaster** [comment] 2015-10-26 16:44
@ErikEJ this is an issue with logging. (See https://github.com/aspnet/Logging/issues/270). We closed the issue because we couldn't reproduce on other machines. Is this error consistent across machines for you?

**Comment by ErikEJ** [comment] 2015-10-26 17:39
@natemcmaster Thanks, will test with a vanilla Azure VM and let you know

**Comment by ErikEJ** [comment] 2015-10-26 18:24
The issue could be related to https://github.com/aspnet/Logging/commit/cceb0dcc43e572ebcd3650b7628e052e22308b85 I guess. @bricelam ??

**Comment by bricelam** [comment] 2015-10-26 19:04
Yeah, probably the same as [this discussion](https://github.com/aspnet/EntityFramework/pull/3504#discussion_r43027248) /cc @pranavkm

**Comment by rowanmiller** [comment] 2015-10-27 18:20
Being tracked by https://github.com/aspnet/EntityFramework/pull/3504#discussion_r43027248

**Comment by ErikEJ** [comment] 2015-10-27 18:38
@rowanmiller But #3504 is closed ?!

**Comment by rowanmiller** [comment] 2015-10-27 19:23
@ErikEJ sorry about that... it spun off into https://github.com/aspnet/EntityFramework/pull/3571 which is still open and should resolve the issue (there have been a whole bunch of changes and discussion around this)

**Comment by ErikEJ** [comment] 2015-10-27 20:25
@rowanmiller  But does that fix the issue with Logging?

**Comment by ErikEJ** [comment] 2015-10-29 13:49
@rowanmiller @natemcmaster Ping !?

**Comment by natemcmaster** [comment] 2015-10-29 16:01
Should have been fixed with https://github.com/aspnet/EntityFramework/pull/3571#issuecomment-152225588 (build ≥ 16151). @EricEJ Are you still experiencing issues?

**Comment by ErikEJ** [comment] 2015-10-29 16:15
@natemcmaster Thanks - will give it a try - but how does that fix the issue for Logging?

**Comment by ErikEJ** [comment] 2015-10-29 17:22
@natemcmaster Thanks for your support - YES, after removing all previous package references, I can now move forward! But how about rc1 vs rc2?

**Comment by ErikEJ** [comment] 2015-10-29 17:57
Maybe I should use the aspnetcirelease feed for rc1?

**Comment by pranavkm** [comment] 2015-10-29 17:59
That sounds right.

**Comment by ErikEJ** [comment] 2015-10-29 18:02
Thanks, will do :smile:

**Closed** 2022-10-16 09:13 UTC
