### ISSUE TITLE
Update is including ignore column in update script.

### ISSUE THREAD

**Issue by AndreBarnard** [dotnet/efcore#18980] opened 2019-11-19 08:35 UTC
I have a UserId column on my table that is not a primary key and is setup in Modelbuilder to ValueGeneratedOnAdd(). When I update that data the UserId is part of my update script when I run SQL profiler and I get an exception: "Cannot update identity column 'UserId'."

### Steps to reproduce

Create a Model with property, not the primary key.
```C#
public int UserId { get; private set; }
```
OnModelCreating: Add 
```C#
Property(p => p.UserId)
        .ValueGeneratedOnAdd();
```
and
```C#
 (p => p.UserId)
        .Metadata.BeforeSaveBehavior = PropertySaveBehavior.Ignore;
```
See on model creating code below:
```C#
  protected override void OnModelCreating(ModelBuilder builder)
    {
      base.OnModelCreating(builder);

      builder.Entity<ApplicationUser>(b =>
      {
        b.Property(p => p.UserId)
        .ValueGeneratedOnAdd();

        b.Property(p => p.UserId)
        .Metadata.BeforeSaveBehavior = PropertySaveBehavior.Ignore;
      });
    }
```
### Further technical details

EF Core version: 2.2.6-servicing-10079
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 2.2
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.5

**Comment by AndreBarnard** [comment] 2019-11-19 08:36
See script generated: @p18 should not be in script

exec sp_executesql N'SET NOCOUNT ON;
UPDATE [AspNetUsers] SET [AccessFailedCount] = @p0, [ConcurrencyStamp] = @p1, [Email] = @p2, [EmailConfirmed] = @p3, [FirstName] = @p4, [IsActive] = @p5, [LastName] = @p6, [LockoutEnabled] = @p7, [LockoutEnd] = @p8, [NormalizedEmail] = @p9, [NormalizedUserName] = @p10, [PasswordHash] = @p11, [PhoneNumber] = @p12, [PhoneNumberConfirmed] = @p13, [SDWPassword] = @p14, [SDWSalt] = @p15, [SecurityStamp] = @p16, [TwoFactorEnabled] = @p17, [UserId] = @p18, [UserName] = @p19
WHERE [Id] = @p20 AND [ConcurrencyStamp] = @p21;
SELECT @@ROWCOUNT;

',N'@p20 nvarchar(450),@p0 int,@p1 nvarchar(4000),@p21 nvarchar(4000),@p2 nvarchar(256),@p3 bit,@p4 nvarchar(150),@p5 bit,@p6 nvarchar(150),@p7 bit,@p8 datetimeoffset(7),@p9 nvarchar(256),@p10 nvarchar(256),@p11 nvarchar(4000),@p12 nvarchar(4000),@p13 bit,@p14 nvarchar(4000),@p15 nvarchar(4000),@p16 nvarchar(4000),@p17 bit,@p18 int,@p19 nvarchar(256)',@p20=N'477c7081-6c16-4853-a78a-5015c371046a',@p0=1,@p1=N'2497b6cf-f3c5-4f0b-840b-d6e3dad05283',@p21=N'db258de8-6b70-4924-b903-23fba479ad01',@p2=N'jspringer@singular.co.za',@p3=1,@p4=N'Julian',@p5=1,@p6=N'Springer',@p7=1,@p8=NULL,@p9=N'JSPRINGER@SINGULAR.CO.ZA',@p10=N'JSPRINGER@SINGULAR.CO.ZA',@p11=N'AQAAAAEAACcQAAAAEJ298fiBBXoEcuY+waWKhKSP5eHediUYzRhV+SDpfhHa3VaPsOb6vRxJc0nHqgieyA==',@p12=NULL,@p13=0,@p14=NULL,@p15=NULL,@p16=N'ICH5TZU2NGECK7FL5NFVAQ7N5LQVF6KK',@p17=0,@p18=1,@p19=N'jspringer@singular.co.za'

**Comment by ajcvickers** [comment] 2019-11-21 17:00
@AndreBarnard Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2019-12-02 16:55
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:57 UTC
Labels: closed-could-not-reproduce, customer-reported
