### ISSUE TITLE
Cannot run add-migration when using custom middleware

### ISSUE THREAD

**Issue by Ruhrpottpatriot** [dotnet/efcore#10544] opened 2017-12-12 19:36 UTC
In my project I have a piece of custom middlware to listen for WebSocket requests, which look and is registered like this:
```
public class WebsocketMiddleware
{
        public WebsocketMiddleware(RequestDelegate next, WebSocketHandler socketHandler, ILogger<WebsocketMiddleware> logger)
        {
            this.Next = next;
            this.SocketHandler = socketHandler;
            this.Logger = logger;
        }
    // Remainder removed for brevity
}

public static IApplicationBuilder MapWebSocketManager(this IApplicationBuilder app, PathString path, WebSocketHandler handler)
{
    return app.Map(path, builder => builder.UseMiddleware<WebsocketMiddleware>(handler));
}
```

If I run the code everything compiles and runs fine without errors. However, when I want to add migrations to the project I get the following error and stack trace:

> Unable to create an object of type 'CharactersDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<CharactersDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.

> PM> add-migration Characters-v2 -Context CharactersDbContext -v
> More than one startup project found.
> Using project 'src\Api'.
> Using startup project 'src\Api'.
> Build started...
> Build succeeded.
> C:\Program Files\dotnet\dotnet.exe exec --depsfile "E:\Users\Robert\Documents\Visual Studio 2017\Projects\FantasyPage2.0\src\Api\bin\Debug\netcoreapp2.0\Api.deps.json" --additionalprobingpath C:\Users\Robert\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig "E:\Users\Robert\Documents\Visual Studio 2017\Projects\FantasyPage2.0\src\Api\bin\Debug\netcoreapp2.0\Api.runtimeconfig.json" C:\Users\Robert\.nuget\packages\microsoft.entityframeworkcore.tools\2.0.1\tools\netcoreapp2.0\ef.dll migrations add Characters-v2 --json --context CharactersDbContext --verbose --no-color --prefix-output --assembly "E:\Users\Robert\Documents\Visual Studio 2017\Projects\FantasyPage2.0\src\Api\bin\Debug\netcoreapp2.0\Api.dll" --startup-assembly "E:\Users\Robert\Documents\Visual Studio 2017\Projects\FantasyPage2.0\src\Api\bin\Debug\netcoreapp2.0\Api.dll" --project-dir "E:\Users\Robert\Documents\Visual Studio 2017\Projects\FantasyPage2.0\src\Api" --root-namespace Api
> Using assembly 'Api'.
> Using startup assembly 'Api'.
> Using application base 'E:\Users\Robert\Documents\Visual Studio 2017\Projects\FantasyPage2.0\src\Api\bin\Debug\netcoreapp2.0'.
> Using working directory 'E:\Users\Robert\Documents\Visual Studio 2017\Projects\FantasyPage2.0\src\Api'.
> Using root namespace 'Api'.
> Using project directory 'E:\Users\Robert\Documents\Visual Studio 2017\Projects\FantasyPage2.0\src\Api'.
> Finding DbContext classes...
> Finding IDesignTimeDbContextFactory implementations...
> Finding application service provider...
> Finding BuildWebHost method...
> Using environment 'Development'.
> Using application service provider from BuildWebHost method on 'Program'.
> Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
>       User profile is available. Using 'C:\Users\Robert\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
> Application startup exception: System.InvalidOperationException: A suitable constructor for type 'Api.Websockets.WebsocketMiddleware' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
>    at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
>    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
>    at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
>    at Microsoft.AspNetCore.Builder.MapExtensions.Map(IApplicationBuilder app, PathString pathMatch, Action`1 configuration)
>    at Api.Websockets.WebSocketExtensions.MapWebSocketManager(IApplicationBuilder app, PathString path, WebSocketHandler handler) in E:\Users\Robert\Documents\Visual Studio 2017\Projects\FantasyPage2.0\src\Api\Websockets\WebSocketExtensions.cs:line 16
>    at Api.Startup.Configure(IApplicationBuilder app, IServiceProvider serviceProvider) in E:\Users\Robert\Documents\Visual Studio 2017\Projects\FantasyPage2.0\src\Api\Startup.cs:line 145
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
> crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
>       Application startup exception
> System.InvalidOperationException: A suitable constructor for type 'Api.Websockets.WebsocketMiddleware' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
>    at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
>    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
>    at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
>    at Microsoft.AspNetCore.Builder.MapExtensions.Map(IApplicationBuilder app, PathString pathMatch, Action`1 configuration)
>    at Api.Websockets.WebSocketExtensions.MapWebSocketManager(IApplicationBuilder app, PathString path, WebSocketHandler handler) in E:\Users\Robert\Documents\Visual Studio 2017\Projects\FantasyPage2.0\src\Api\Websockets\WebSocketExtensions.cs:line 16
>    at Api.Startup.Configure(IApplicationBuilder app, IServiceProvider serviceProvider) in E:\Users\Robert\Documents\Visual Studio 2017\Projects\FantasyPage2.0\src\Api\Startup.cs:line 145
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
> System.InvalidOperationException: A suitable constructor for type 'Api.Websockets.WebsocketMiddleware' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
>    at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
>    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
>    at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
>    at Microsoft.AspNetCore.Builder.MapExtensions.Map(IApplicationBuilder app, PathString pathMatch, Action`1 configuration)
>    at Api.Websockets.WebSocketExtensions.MapWebSocketManager(IApplicationBuilder app, PathString path, WebSocketHandler handler) in E:\Users\Robert\Documents\Visual Studio 2017\Projects\FantasyPage2.0\src\Api\Websockets\WebSocketExtensions.cs:line 16
>    at Api.Startup.Configure(IApplicationBuilder app, IServiceProvider serviceProvider) in E:\Users\Robert\Documents\Visual Studio 2017\Projects\FantasyPage2.0\src\Api\Startup.cs:line 145
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at Api.Program.BuildWebHost(String[] args) in E:\Users\Robert\Documents\Visual Studio 2017\Projects\FantasyPage2.0\src\Api\Program.cs:line 20
> An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider. Error: A suitable constructor for type 'Api.Websockets.WebsocketMiddleware' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
> No application service provider was found.
> Finding DbContext classes in the project...
> Found DbContext 'CharactersDbContext'.
> Found DbContext 'GameObjectsDbContext'.
> Found DbContext 'ServersDbContext'.
> Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'CharactersDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<CharactersDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time. ---> System.MissingMethodException: No parameterless constructor defined for this object.
>    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
>    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
>    at System.Activator.CreateInstance(Type type)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
>    --- End of inner exception stack trace ---
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
>    at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
> Unable to create an object of type 'CharactersDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<CharactersDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.

I heard this might have something to do with my Program and Startup class, but this is a fresh netcore 2.0 project, so those classes look like they should:

```
public static void Main(string[] args)
        {
            Console.Title = "Fantasy - API";
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();

public void ConfigureServices(IServiceCollection services)
{
    services.AddDbContext<CharactersDbContext>(options =>
    {
        var connection = this.Configuration.GetConnectionString("CharactersDb");
        if (this.Environment.IsDevelopment())
        {
            options.UseSqlite(connection);
        }
        else
        {
            options.UseSqlServer(connection);
        }
    });
    // Remainder removed for brevity
}
public void Configure(IApplicationBuilder app, IServiceProvider serviceProvider)
{
    app.UseAuthentication();

    app.UseWebSockets(new WebSocketOptions
    {
        KeepAliveInterval = TimeSpan.FromSeconds(120),
    ReceiveBufferSize = 4 * 1024,
    });

    app.MapWebSocketManager("/api/worlds", serviceProvider.GetService<WorldServerMessageHandler>());
    app.MapWebSocketManager("/api/game", serviceProvider.GetService<GameMessageHandler>());

    app.UseMvc();
}
```

If I comment out the `MapWebSocketManager` calls the command runs fine and at first I thought it might have to do something, how I map the WebSocketManager, but when debugging everything is normal.

### Further technical details
EF Core version: 2.0.0
Database Provider: SQLite
Operating system: Win10 x64
IDE: Visual Studio 2017 15.4.2

**Comment by bricelam** [comment] 2017-12-13 17:35
Duplicate of #10502

**Closed** 2022-10-16 12:02 UTC
