### ISSUE TITLE
EF Core materializes projection property as object with default values instead of null

### ISSUE THREAD

**Issue by Alexander-Leontiev** [dotnet/efcore#26551] opened 2021-11-05 09:58 UTC
I have a LINQ expression like the following:

```C#
from u in Context.Users.Where(u => u.Id == 123).Select(UserDto.Map)
join l in Context.Locations.Select(LocationDto.Map) on u.LocationId equals l.Id into locations
from l in locations.DefaultIfEmpty()
join a in Context.Agencies.Select(AgencyDto.Map) on l.CompanyId equals a.Id into agencies
from a in agencies.DefaultIfEmpty()
join m in Context.Markets.Select(MarketDto.Map) on l.CompanyId equals m.Id into markets
from m in markets.DefaultIfEmpty()
select new UserEntityData {
   User = u,
   Location = l,
   Agency = a,
   Market = m
}
```

User via Location can be connected to Agency or Market, not both.
EF translates it correctly into SQL query with left joins. Query returns correct data with Agency or Market columns all NULL.
However when query data is materialized I get UserEntityData objects with both Agency and Market properties not null. UserEntityData property for missing DB record is initialized with object with default values. I expect property to be null.

UPD: if I read full entities for agency\market (not projected DTOs) all works fine.

EF Core version: 3.1.15
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .Net Framework 4.8

**Comment by ajcvickers** [comment] 2021-11-10 10:36
@Alexander-Leontiev Can you please try with EF Core 6.0 and if you are still seeing an issue then attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2021-11-18 12:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by Alexander-Leontiev** [comment] 2021-11-25 12:32
@ajcvickers sorry for so long answer.
I tried EF Core 5\6 and got another error 'Nullable object must have a value' during materialization. Looks like EF tries to put NULLs from DB response into not-nullable properties of my DTOs.

**Closed** 2022-10-16 20:12 UTC
Labels: closed-could-not-reproduce, customer-reported
