### ISSUE TITLE
HasDefaultValueSql() does not work when relationship is configured

### ISSUE THREAD

**Issue by yorickdewid** [dotnet/efcore#14751] opened 2019-02-20 14:22 UTC
When a default value is configured for a column and the same column is used in an relationship, then the default value is never used. In this specific case resulting in a not-null constraint violation, but other columns are just set to 'null' instead of using the default. Tested with both `HasDefaultValueSql()` and `HasDefaultValue()`. The problem could be specific to the Npgsql database provider. If the relationship is removed, the default is used as supposed to.

```
Microsoft.EntityFrameworkCore.Database.Command:Error: Failed executing DbCommand (29ms) [Parameters=[@p0='?' (Size = 64), @p1='?' (DbType = Boolean), @p2='?' (DbType = Int32), @p3='?' (DbType = Int32), @p4='?' (DbType = DateTimeOffset), @p5='?' (DbType = Date), @p6='?' (Size = 128), @p7='?' (DbType = Boolean), @p8='?' (DbType = Boolean), @p9='?' (DbType = Boolean), @p10='?', @p11='?' (DbType = Int32), @p12='?' (DbType = Int32), @p13='?' (DbType = Int32), @p14='?' (Size = 32), @p15='?' (Size = 32), @p16='?' (DbType = DateTimeOffset)], CommandType='Text', CommandTimeout='30']
INSERT INTO report.report (document_id, conform_f3o, contractor, creator, delete_date, document_date, document_name, floor_measurement, inspection, joint_measurement, note, owner, project, reviewer, status, type, update_date)
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16)
RETURNING id, create_date;

Npgsql.PostgresException (0x80004005): 23502: null value in column "type" violates not-null constraint
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 467
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1217
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Update:Error: An exception occurred in the database while saving changes for context type 'FunderMaps.Data.FisDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Npgsql.PostgresException: 23502: null value in column "type" violates not-null constraint
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 467
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1217
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken) in C:\projects\EFCore.PG\src\EFCore.PG\Storage\Internal\NpgsqlExecutionStrategy.cs:line 72
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

### Steps to reproduce
```c#
public class Report
{
    public int Id { get; set; }
    public string Status { get; set; }
    public string Type { get; set; }

    public ReportStatus StatusNavigation { get; set; }
    public ReportType TypeNavigation { get; set; }
}

modelBuilder.Entity<Report>(entity =>
{
    entity.HasKey(e => e.Id);

    entity.ToTable("report", "report");

    entity.Property(e => e.Id).HasColumnName("id").HasDefaultValueSql("nextval('report.report_id_seq'::regclass)");
    entity.Property(e => e.Status).HasColumnName("status").HasMaxLength(32).HasDefaultValueSql("'todo'::character varying");
    entity.Property(e => e.Type).IsRequired().HasColumnName("type").HasMaxLength(32).HasDefaultValueSql("'unknown'::character varying");

    entity.HasOne(d => d.StatusNavigation)
        .WithMany(p => p.Report)
        .HasForeignKey(d => d.Status)
        .HasConstraintName("report_status_fkey");

    entity.HasOne(d => d.TypeNavigation)
        .WithMany(p => p.Report)
        .HasForeignKey(d => d.Type)
        .OnDelete(DeleteBehavior.ClientSetNull)
        .HasConstraintName("report_type_fkey");
});
```

Install nuget packages:

* Npgsql.EntityFrameworkCore.PostgreSQL (version 2.1.1.1)

The preceding code will use the default for 'Id' but not for 'status' or 'type'. If the relationship for 'status' or 'type' is removed, the default is used.

### Further technical details
EF Core version: 2.1.1
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL (2.1.1.1)
Operating system: Windows x64
IDE: Visual Studio 2017 15.9.7

**Comment by ajcvickers** [comment] 2019-02-25 20:15
@yorickdewid There isn't enough information here for us to effectively investigate the issue. Could you posts a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by yorickdewid** [comment] 2019-02-26 09:56
I'll do so. I found an additional problem with the `HasDefaultValue()`. Once the default is configured EF Core will never look if the value was null or set. It looks like an issue with the Npgsql provider, although I have not verified that,

**Comment by ajcvickers** [comment] 2019-03-04 17:33
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ashiahakim** [comment] 2019-03-29 06:25
> When a default value is configured for a column and the same column is used in an relationship, then the default value is never used. In this specific case resulting in a not-null constraint violation, but other columns are just set to 'null' instead of using the default. Tested with both `HasDefaultValueSql()` and `HasDefaultValue()`. The problem could be specific to the Npgsql database provider. If the relationship is removed, the default is used as supposed to.
> 
> ```
> Microsoft.EntityFrameworkCore.Database.Command:Error: Failed executing DbCommand (29ms) [Parameters=[@p0='?' (Size = 64), @p1='?' (DbType = Boolean), @p2='?' (DbType = Int32), @p3='?' (DbType = Int32), @p4='?' (DbType = DateTimeOffset), @p5='?' (DbType = Date), @p6='?' (Size = 128), @p7='?' (DbType = Boolean), @p8='?' (DbType = Boolean), @p9='?' (DbType = Boolean), @p10='?', @p11='?' (DbType = Int32), @p12='?' (DbType = Int32), @p13='?' (DbType = Int32), @p14='?' (Size = 32), @p15='?' (Size = 32), @p16='?' (DbType = DateTimeOffset)], CommandType='Text', CommandTimeout='30']
> INSERT INTO report.report (document_id, conform_f3o, contractor, creator, delete_date, document_date, document_name, floor_measurement, inspection, joint_measurement, note, owner, project, reviewer, status, type, update_date)
> VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16)
> RETURNING id, create_date;
> 
> Npgsql.PostgresException (0x80004005): 23502: null value in column "type" violates not-null constraint
>    at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
> --- End of stack trace from previous location where exception was thrown ---
>    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 467
>    at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1217
>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
> Microsoft.EntityFrameworkCore.Update:Error: An exception occurred in the database while saving changes for context type 'FunderMaps.Data.FisDbContext'.
> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Npgsql.PostgresException: 23502: null value in column "type" violates not-null constraint
>    at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
> --- End of stack trace from previous location where exception was thrown ---
>    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 467
>    at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1217
>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
>    at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken) in C:\projects\EFCore.PG\src\EFCore.PG\Storage\Internal\NpgsqlExecutionStrategy.cs:line 72
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
> ```
> ### Steps to reproduce
> ```cs
> public class Report
> {
>     public int Id { get; set; }
>     public string Status { get; set; }
>     public string Type { get; set; }
> 
>     public ReportStatus StatusNavigation { get; set; }
>     public ReportType TypeNavigation { get; set; }
> }
> 
> modelBuilder.Entity<Report>(entity =>
> {
>     entity.HasKey(e => e.Id);
> 
>     entity.ToTable("report", "report");
> 
>     entity.Property(e => e.Id).HasColumnName("id").HasDefaultValueSql("nextval('report.report_id_seq'::regclass)");
>     entity.Property(e => e.Status).HasColumnName("status").HasMaxLength(32).HasDefaultValueSql("'todo'::character varying");
>     entity.Property(e => e.Type).IsRequired().HasColumnName("type").HasMaxLength(32).HasDefaultValueSql("'unknown'::character varying");
> 
>     entity.HasOne(d => d.StatusNavigation)
>         .WithMany(p => p.Report)
>         .HasForeignKey(d => d.Status)
>         .HasConstraintName("report_status_fkey");
> 
>     entity.HasOne(d => d.TypeNavigation)
>         .WithMany(p => p.Report)
>         .HasForeignKey(d => d.Type)
>         .OnDelete(DeleteBehavior.ClientSetNull)
>         .HasConstraintName("report_type_fkey");
> });
> ```
> 
> Install nuget packages:
> 
> * Npgsql.EntityFrameworkCore.PostgreSQL (version 2.1.1.1)
> 
> The preceding code will use the default for 'Id' but not for 'status' or 'type'. If the relationship for 'status' or 'type' is removed, the default is used.
> 
> ### Further technical details
> EF Core version: 2.1.1
> Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL (2.1.1.1)
> Operating system: Windows x64
> IDE: Visual Studio 2017 15.9.7

How you have solved this issue?

**Closed** 2022-10-16 13:52 UTC
Labels: closed-could-not-reproduce, customer-reported
