### ISSUE TITLE
Entity Framework Core with Azure Table Storage

### ISSUE THREAD

**Issue by leroylll** [dotnet/efcore#18737] opened 2019-11-04 04:08 UTC
Any plans to have Entity Framework Core work with Azure Table Storage?

**Comment by ajcvickers** [comment] 2019-11-04 17:53
@leroylll We currently have no plans. Duplicate of #18514

**Comment by brandonh-msft** [comment] 2022-08-10 16:18
@ajcvickers it's not clear to me how this ask is a dupe of 18514 - is that the right source item?

**Comment by ajcvickers** [comment] 2022-08-10 16:24
@brandonh-msft Thanks, wrong issue. Should be #1142.

**Closed** 2022-10-16 14:54 UTC
Labels: customer-reported
