### ISSUE TITLE
Core 3.1, Ef 2.2.6, Microsoft Sql Server, Insert or Update scenario

### ISSUE THREAD

**Issue by yahorsi** [dotnet/efcore#19620] opened 2020-01-17 13:03 UTC
The task:
Imagine you are using EF to implement the service that needs to Insert new record or Update if a record with the key already exists for some table that has FK & some child tables. I didn't find a nice way to implement it, both good from the code perspective options cause exceptions. 

Please NOTE, we do not call SaveChanges after Remove call, that made on purpose. Please consider 2 reasons:
1. Imagine you are implementing Upsert (or Merge) method in the repository pattern, so, you simply can't call SaveChanges, it is not your responsibility and it's just wrong place to call it
2. Batching scenario, imagine the case when you're updating a batch of records and to avoid perf issues you do not want to call SaveChanges after updating a single entity.

So, let have some tables with some relation between them
```SQL
USE [master]
GO

DROP DATABASE IF EXISTS Ef31SqlServerQueryLogicAndOrderBug
GO

CREATE DATABASE Ef31SqlServerQueryLogicAndOrderBug
GO 

USE Ef31SqlServerQueryLogicAndOrderBug
GO

CREATE TABLE Keyboard
(
    [Id] INT NOT NULL,
    [Value] NVARCHAR(MAX),
    CONSTRAINT [PK_Keyboard] PRIMARY KEY CLUSTERED ([Id] ASC)

)
GO

CREATE TABLE Button
(
    [Id] INT NOT NULL PRIMARY KEY,
    [KeyboardId] INT NOT NULL,
    [Value] NVARCHAR(MAX),
    CONSTRAINT [FK_Keyboard_Id] FOREIGN KEY ([KeyboardId]) REFERENCES [Keyboard]([Id]) ON DELETE CASCADE
)
GO
```

Very simple master->child relation.
Here is the database context.
```C#
    [Table("Keyboard")]
    public class Keyboard
    {
        public Keyboard()
        {
            Buttons = new HashSet<Button>();
        }

        [Key]
        public int Id { get; set; }

        public string Value { get; set; }

        [InverseProperty("Keyboard")]
        public ICollection<Button> Buttons { get; set; }
    }

    [Table("Button")]
    public class Button
    {
        [Key]
        public int Id { get; set; }

        public int KeyboardId { get; set; }

        public string Value { get; set; }

        [ForeignKey("KeyboardId")]
        [InverseProperty("Buttons")]
        public Keyboard Keyboard { get; set; }
    }

    public class DatabaseContext : DbContext
    {
        public DbSet<Keyboard> Keyboards { get; set; }
        public DbSet<Button> Buttons { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var connectionString = "Server=.;Database=Ef31SqlServerQueryLogicAndOrderBug;Trusted_Connection=True;";
            var connection = new SqlConnection(connectionString);
            optionsBuilder.UseSqlServer(connection);
            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Keyboard>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();
            });
            modelBuilder.Entity<Button>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();
                entity.HasOne(d => d.Keyboard)
                    .WithMany(p => p.Buttons)
                    .HasForeignKey(d => d.KeyboardId)
                    .HasConstraintName("[FK_Keyboard_Id]");
            });
        }
    }
```

### Steps to reproduce
Having code above in mind let us implement update or insert the simplest (intuitive) possible way
```C#
        private static void UpdateUsingSimpleRemoveAndAdd(int id)
        {
            var context = new DatabaseContext();
            var keyboard = BuildKeyboard();
            context.Keyboards.Remove(keyboard);
            context.Keyboards.Add(keyboard);
            context.SaveChanges();
        }
```

The code above works just fine when there is no existing record in the database but fails when there is already record in the database with:
```
"Violation of PRIMARY KEY constraint 'PK_Keyboard'".
```

Sooo, maybe we're doing it wrong, let's try another way:
```C#
        private static void UpdateUsingSimpleRemoveAndAdd2(int id)
        {
            var context = new DatabaseContext();
            context.Keyboards.Remove(BuildKeyboard());
            context.Keyboards.Add(BuildKeyboard());
            context.SaveChanges();
        }
```

This way it fails as well but now with another exception:
```
The instance of entity type 'Button' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked.
```

Sooo, let's try another one way:
```C#
        private static void UpdateUsingExistenceCheck(int id)
        {
            var context = new DatabaseContext();

            var existingKeyboard = context.Keyboards.Find(id);

            if (existingKeyboard != null)
            {
                context.Keyboards.Remove(existingKeyboard);
            }

            context.Keyboards.Add(BuildKeyboard());
            context.SaveChanges();
        }
```

And again fails when there is the record in the database with:
```
Violation of PRIMARY KEY constraint 'PK__Button__3214EC076F7532C1'. Cannot insert duplicate key in object 'dbo.Button'. The duplicate key value is (1).
The statement has been terminated.
```

Maybe try to just update a record without calling Remove?:
```C#
        private static void UpdateUsingSimpleRemoveAndAdd3(int id)
        {
            var context = new DatabaseContext();
            context.Keyboards.Update(BuildKeyboard());
            context.SaveChanges();
        }
```

Fails with:
```
Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
```

Let's have the last attempt (call SaveChanges after calling Delete)
```C#
        private static void UpdateUsingExistenceCheck2(int id)
        {
            var context = new DatabaseContext();

            var existingKeyboard = context.Keyboards.Find(id);

            if (existingKeyboard != null)
            {
                context.Keyboards.Remove(existingKeyboard);
                context.SaveChanges();
            }

            context.Keyboards.Add(BuildKeyboard());
            context.SaveChanges();
        }
```

Finally, it worked but that brakes batching scenario, where you want to update not just single record but many using single SQL statement/roundtrip.

### Full C# and SQL code for that article is available here https://github.com/yahorsi/Ef31SqlServerQueryLogicAndOrderBug

I'm not putting full source here just to not overload the issue with too much text.
Please let me know if it was a bad idea so I'll put a full sample code here.

### Conclusion0
It is hard to tell me where the bug is. This article is made as a result of 2 days' work of failed attempt to implement insert or update using EF, using nice, simple and **efficient** code. 

### Conclusion1
So, the conclusion is simple. **It is now impossible to efficiently implement update or insert scenario in the EF 2.2 and upper.** In order to make it work you have to run SELECT to test if record exists and then run DELETE manually or by calling SaveChnages that is bad choice because breaks batching scenario and make's it hard to tell where SaveChanges should be called. Even without adding UpdateOrDelete it could have been implemented using single DELETE statement and single INSERT but it is not and seems not possible ((

It is sad there is no Merge or Upsert support built into the EF. having in mind that could be done really efficiently using e.g. single Merge statement for Microsoft Sql Server.

### Conclusion2
Most likely I understand why it works like this - you simply have an entity and status flag and so Add overrides Remove. If so, in order to make insert or update scenario work EF needs to support Merge or Upsert operation on the DbSet out of the box, otherwise, the only way to do it efficiently is manual that is again not as simple when your app has already got a dependency on EF.

### Further technical details

EF Core version: 2.2.6 and above
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.2

**Comment by ajcvickers** [comment] 2020-01-17 16:52
@yahorsi See https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities for different ways to do this. Closing this issue as duplicate of #4526

**Comment by yahorsi** [comment] 2020-01-17 17:28
> @yahorsi See https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities for different ways to do this. Closing this issue as duplicate of #4526

Disconnected entities is not the way to solve the problem.
It is might be not clear from my explanation, so, I'll try to explain again.
Imagine the cause when you receive thousands of messages from the Azure Service Bus or Event Hubs.
Messages contain some "entities" that you need to update or insert, based on NOT the entity Id but the fact is are there already records in the database with given key or not. And because of the volume, you want to do this efficiently, without querying if every entity exists. Ideally what you want is to bulk upload all entities and then run MERGE statement that will insert records for the keys that are not in the database yet or UPDATE for the keys that are already in the database.

The issue you pointed is created in 2016 and there is still no info on whether this is going to be implemented or not. So, it would be really cool if you could provide your plans on this front.

Thank you

**Comment by ajcvickers** [comment] 2020-01-17 20:01
Re-opening to discuss with team.

**Comment by ajcvickers** [comment] 2020-01-21 23:45
Went over this again. Possibly better covered by #795.

With regard to plans, both these issues are in the Backlog milestone. This means that it is not planned for the next release (EF Core 5.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Closed** 2022-10-16 18:06 UTC
Labels: customer-reported
