### ISSUE TITLE
Bi-Temporal Table Support

### ISSUE THREAD

**Issue by at0dd** [dotnet/efcore#29577] opened 2022-11-16 03:58 UTC
## Ask a question
Is there any planned support for bi-temporal tables, or suggested ways to implement?

Along with the "period start" and "period end" columns, bi-temporal  adds "system start" and "system end" to tell when the data was valid in the system.
A good example: [Cloudera Bi-Temporal Data Modeling](https://blog.cloudera.com/bi-temporal-data-modeling-with-envelope/)

### Include provider and version information

EF Core version: 7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Mac OS 12.16.1
IDE: Visual Studio for Mac 2022 17.5 Preview

**Comment by roji** [comment] 2022-11-16 07:05
@at0dd EF's support of temporal table supports SQL Server's native [Temporal table](https://learn.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-ver16) feature; are you aware of similar **native** support for the bi-temporal concept?

Otherwise, if bi-temporal is just about modeling your data in a certain way (e.g. adding system start/end columns), there's probably nothing in particular that EF needs to support here, i.e. you can simply add those columns yourself and use them (query filters can make sure queries always filter by them, etc.).

**Comment by ajcvickers** [comment] 2022-11-23 13:11
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-11-23 13:11 UTC
Labels: customer-reported
