### ISSUE TITLE
Perf: provide a way to batch the generated commands for a complex query

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#10465] opened 2017-12-01 21:01 UTC
Some queries (e.g. [ones with multiple collection includes)](https://github.com/AndriySvyryd/UnicornHack/blob/2dd021c0b85d1bb3ebf34c7707cdac57d877350f/src/UnicornHack.Web/Data/GameDbContext.cs#L496) can result in multiple database commands being executed. If the expected results are relatively small data sets the queries could be combined in a single command and the data buffered.

**Comment by ajcvickers** [comment] 2018-02-08 01:43
Closing this as a virtual duplicate of #10878.

**Closed** 2022-10-16 12:01 UTC
Labels: closed-duplicate
