### ISSUE TITLE
Support of unique Index with Owned types properties

### ISSUE THREAD

**Issue by thiagomajesk** [dotnet/efcore#12637] opened 2018-07-11 23:25 UTC
Hi, I wonder if this is supported...

I have an owned type already configured and I wish to add a unique constraint that includes one of the owned type properties to prevent the user to insert two entities with "same" info. 

For clarification:

```c#
class MyType
{
    private string description;
    public string Description => description;
}
```
```c#
class Bar
{
    public virtual ICollection<Foo> Foos { get; set; }
}
```

```c#
class Foo
{
    public virtual Bar Bar { get; set; }
    public MyType Buzz { get; set; }
}
```

```c#
 modelBuilder.Entity<Foo>(x =>
{
    x.OwnsOne(z => z.Buzz)
     .Property(z => z.Description).HasColumnName("Buzz")
     .UsePropertyAccessMode(PropertyAccessMode.FieldDuringConstruction)
     .IsRequired();

      // Only want to allow one pair of BarId + Buzz to exist in the db
      x.HasIndex("BarId", "Buzz").IsUnique(); // does not work
});
```

The error I'm getting is...

> The property or navigation 'Buzz' cannot be added to the entity type 'Foo' because a property or navigation with the same name already exists on entity type 'Foo'.

Is there any currently supported way to get this working?

**Comment by divega** [comment] 2018-07-16 18:47
@AndriySvyryd, thoughts?

**Comment by AndriySvyryd** [comment] 2018-07-16 19:01
@thiagomajesk You can just create the index on the owned type:
```C#
modelBuilder.Entity<Foo>(x =>
{
    x.OwnsOne(z => z.Buzz, zb =>
    {    
         zb.Property(z => z.Description).HasColumnName("Buzz")
           .UsePropertyAccessMode(PropertyAccessMode.FieldDuringConstruction)
           .IsRequired();
         
         zb.HasIndex(z => z.Description).IsUnique();
    });
});
```

**Comment by AndriySvyryd** [comment] 2018-07-16 20:41
Then this is a duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/11336, see the comments there for a workaround.

**Comment by thiagomajesk** [comment] 2018-07-16 20:42
@AndriySvyryd Ok, thanks!

**Closed** 2022-10-16 13:18 UTC
Labels: closed-duplicate, customer-reported
