### ISSUE TITLE
Can't use Microsoft.EntityFrameworkCore.Sqlite

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#10325] opened 2017-11-16 21:50 UTC
VS Feedback:

In VS15.5 Preview, I created a Xamarin.Forms projects with .NET Standard code sharing strategy.
Add Microsoft.EntityFrameworkCore.Sqlite, Android Project can't run, if I run the android project, program will crash and vs will stop.

**Comment by ajcvickers** [comment] 2017-11-17 21:05
Assigning to @divega along with other Android investigations. Feel free to de-dupe as needed.

**Comment by topfunet** [comment] 2017-11-18 17:18
any news?

**Comment by bricelam** [comment] 2017-11-22 18:46
Duplicate of  #8922?

**Comment by divega** [comment] 2018-02-05 21:54
If this is not a duplicate of #8922 then it is no repro. Closing.

**Closed** 2022-10-16 11:59 UTC
Labels: closed-duplicate, area-external, area-xamarin
