### ISSUE TITLE
Including Display Property when Key is Empty Guid returns null

### ISSUE THREAD

**Issue by selected-pixel-jameson** [dotnet/efcore#11908] opened 2018-05-04 14:17 UTC
When I attempt to Include a display property from a model which has a field that is an Empty.Guid the query returns null.

For example:

```
[Key]
public Guid Id {get; set;}
public String name { get; set;}
public String otherProperty {get; set;}

public Guid BillingContactId {get; set;}
public Contact BillingContact {get; set;}  
```
And then within a repository for that model.
```
return await _entities
                .Include(c => c.BillingContact)
                .AsNoTracking()
                .ToListAsync();
```

The value in the database for BillingContactId would be an Empty.Guid. The repository query will return null instead of the entity with a null value for the BillingContact display property.

I can't really figure out a way of making this include conditional without first loading the entity without the include and then reloading it again with the include. Ideally it would just return that display property as null and not return null all together. 

### Further technical details
EF Core version: 2.0.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Visual Studio 2017 15.4

**Comment by ajcvickers** [comment] 2018-05-04 16:32
@selected-pixel-jameson Does the database contain a row in the principal table with a primary key value of Guid.Empty?

**Comment by selected-pixel-jameson** [comment] 2018-05-04 17:13
@ajcvickers The parent entity has a populated Guid value. The BillingContactId field in the table has a value of Guid.Empty.

**Comment by ajcvickers** [comment] 2018-05-04 21:56
@selected-pixel-jameson I'm really struggling to understand what you are trying to do. Can you post a runnable project/solution or code listing that demonstrates the behavior you are seeing?

**Comment by selected-pixel-jameson** [comment] 2018-05-07 12:54
When you try to query for an entity and include a property that has a reference to a foreign key which is Guid.Empty it causes the query to return null. It seems like it should still return the entity and instead just set the foreign key property to null or empty.

**Comment by ajcvickers** [comment] 2018-05-07 16:58
@selected-pixel-jameson Code would really help--it's not ambiguous. Some of the problems I'm having with the question:
* If an FK value is Guid.Empty, then it means there must be a corresponding PK value of Guid.Empty, otherwise the FK constraint is violated.
* Assuming that there is no database constraint such that the violation is not detected by the database, then when querying for the dependent directly I would expect it to come back with a Guid.Empty FK value and a navigation property set to null.
* On the other hand, if I query for all the principals, then the results will depend on whether or not the FK is nullable, which in turn depends on whether the relationship is required or optional.
  * For a required relationship, the FK says that every dependent must have a principal with a corresponding PK. If this is not the case, then the FK in the EF model is being violated and it may mean that EF does not return some data since it will never look for any entity that doesn't have a matching PK.
  * For an optional relationship, the FK says that every dependent must have a principal with a corresponding PK _or the FK must be null_. If this is not the case, which is true even if Guid.Empty is used, then the FK in the model is still being violated. However, EF may still return the child in this case because allowing nulls means that there may be children that don't have a PK matching the FK (when it is null) and hence EF must look for all dependents which may then bring back the violating entity anyway.

**Comment by ajcvickers** [comment] 2018-05-14 18:04
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:23 UTC
Labels: closed-could-not-reproduce
