### ISSUE TITLE
Owned type with seperate table in EF Core 5 preview 8 now needs a Include for owned type

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#22444] opened 2020-09-08 14:18 UTC
I just updated my code to EF Core 5 preview 8 and I found that I have to have an `Include` to load the owned type in a separate table. That is a change from previous, i.e.

1. EF Core 5 preview 7 and before 
   - I would load the main entity and the owned type in a separate table was loaded automatically
2. EF Core 5 preview 8 
   - I load the main entity that has an owned type in a separate table I get a `InvalidOperationException` with the message `Sequence contains no elements`
   - If I add an`Include` for the owned type it works.

Is this a change in how Owned Types work or is it a bug?

### Steps to reproduce

``` C#
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using TestSupport.EfHelpers;
using Xunit.Extensions.AssertExtensions;

namespace EfCore5Preview8OwnedTypeSeperateTable
{
    class Program
    {
        static void Main(string[] args)
        {
            TestCreateUserWithAddressReadBackOk();
            Console.WriteLine("It worked");
        }

        [Owned]
        public class Address
        {
            public string NumberAndStreet { get; set; }
            public string City { get; set; }
            public string ZipPostCode { get; set; }
            [Required]
            [MaxLength(2)]
            public string CountryCodeIso2 { get; set; }
        }

        public class User
        {
            public int UserId { get; set; }

            public string Name { get; set; }

            public Address HomeAddress { get; set; }
        }


        public class SplitOwnDbContext : DbContext
        {
            public SplitOwnDbContext(DbContextOptions<SplitOwnDbContext> options)
                : base(options) { }

            public DbSet<User> Users { get; set; }

            protected override void OnModelCreating
                (ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<User>().OwnsOne(e => e.HomeAddress)
                    .ToTable("Addresses");
            }
        }

        public static void TestCreateUserWithAddressReadBackOk()
        {
            //SETUP
            var options = SqliteInMemory.CreateOptions<SplitOwnDbContext>();
            using (var context = new SplitOwnDbContext(options))
            {
                context.Database.EnsureCreated();

                var entity = new User()
                {
                    Name = "Unit Test",
                    HomeAddress = new Address
                    {
                        NumberAndStreet = "1, my street",
                        City = "My city",
                        ZipPostCode = "W1A 1AA",
                        CountryCodeIso2 = "UK"
                    }
                };
                context.Add(entity);
                context.SaveChanges();
            }
            using (var context = new SplitOwnDbContext(options))
            {
                //ATTEMPT
                var user = context.Users.FirstOrDefault(); //THIS THROWS AN EXCEPTION

                //VERIFY
                user?.HomeAddress.ShouldNotBeNull();
            }
        }
    }
}
```

csprog file
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EfCore.TestSupport" Version="3.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.0-preview.8.20407.4" />
  </ItemGroup>

</Project>
```

Exception is
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains no elements
  Source=System.Linq
  StackTrace:
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.GetPropertyExpressionsFromJoinedTable(IEntityType entityType, ITableBase table, TableExpressionBase tableExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.TryExpand(Expression source, MemberIdentity member)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.Expand(SelectExpression selectExpression, Expression lambdaBody)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.ExpandWeakEntities(SelectExpression selectExpression, Expression lambdaBody)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at EfCore5Preview8OwnedTypeSeperateTable.Program.TestCreateUserWithAddressReadBackOk() in C:\Users\JonPSmith\source\repos\EfCore5Preview8OwnedTypeSeperateTable\Program.cs:line 79
   at EfCore5Preview8OwnedTypeSeperateTable.Program.Main(String[] args) in C:\Users\JonPSmith\source\repos\EfCore5Preview8OwnedTypeSeperateTable\Program.cs:line 14
```

### Further technical details

EF Core version: 5.0.0-preview.8.20407.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.Sqlite and SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system: Windows
IDE: Visual Studio 2019 16.7

**Comment by smitpatel** [comment] 2020-09-08 15:04
Duplicate of https://github.com/dotnet/efcore/issues/22340

**Closed** 2022-10-16 18:39 UTC
Labels: closed-duplicate, customer-reported
