### ISSUE TITLE
MSBuild-ify tools

### ISSUE THREAD

**Issue by muratg** [dotnet/efcore#6494] opened 2016-09-08 16:44 UTC
### Microsoft.EntityFrameworkCore.Tools
- Expect to run independently, via the CLI
- Expect to run via MSBuild
- Runtime dependencies/Load Context thingy
- Project namespace (in MSBuild)
- OutputType
- TargetPath
### TODO
- Fork tools repos to `rel/1.0.0-preview3` branches for "October" release. Dev branches will continue to be used for 1.1 release.
- Use desktop msbuild to start our work until the new msbuild is ready for   consumption
### Notes
- [This](https://github.com/aspnet/Coherence-Signed/issues/375) tracks the work across the tools repos.
- [This](https://github.com/aspnet/specs/blob/master/notes/Tools.md) is the previous discussion on the topic.

**Comment by bricelam** [comment] 2016-09-16 02:43
Clearing the milestone since it sounds like the plans for the October release have changed.

**Comment by bricelam** [comment] 2016-10-17 21:34
Closing as a dupe of #6139 (cross-repo issue updated)

**Closed** 2022-10-16 09:56 UTC
Labels: blocked
