### ISSUE TITLE
IsRequired() is ignored for owned types

### ISSUE THREAD

**Issue by mhDuke** [dotnet/efcore#18373] opened 2019-10-15 04:50 UTC
After configuring owned type with `IsRequired()` as shown below, generated migration code ignores it, and sets `nullable` to true.

```
builder.OwnsOne<GeoLocation>(e => e.GeoLocation, a =>
            {
                a.Property(e => e.Latitude)
                .HasColumnName(nameof(GeoLocation.Latitude))
                .HasColumnType("decimal(8,6)")
                .HasDefaultValue(-99)
                .IsRequired();

                a.Property(e => e.Longitude)
                .HasColumnName(nameof(GeoLocation.Longitude))
                .HasColumnType("decimal(9,6)")
                .HasDefaultValue(-999)
                .IsRequired();
            });
```
```
migrationBuilder.CreateTable(
                name: "Sites",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(maxLength: 50, nullable: false),
                    Latitude = table.Column<decimal>(type: "decimal(8,6)", nullable: true, defaultValue: -99m),
                    Longitude = table.Column<decimal>(type: "decimal(9,6)", nullable: true, defaultValue: -999m),
                    CityId = table.Column<int>(nullable: false)
                },
                constraints:
```
### Further technical details

EF Core version: 3
Database provider: Microsoft.EntityFrameworkCore.SqlServer version 3
Target framework: EF Core project: netstandard2.1. Startup project(includes EntityFrameworkCore.Design): .NET Core 3.0
IDE: Visual Studio 2019 16.3.4

**Comment by AndriySvyryd** [comment] 2019-10-15 06:26
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/16943

**Closed** 2022-10-16 14:49 UTC
Labels: customer-reported
