### ISSUE TITLE
DateTime.AddHours(Double) having its parameter casted to int in SQL query

### ISSUE THREAD

**Issue by mateusrodrigues** [dotnet/efcore#20550] opened 2020-04-06 17:47 UTC
I've noticed that `DateTime.AddHours(Double)`, when translated to SQL, seems to be casting the `double `value to an `int`, such that `1.5` becomes `1`, `0.5` becomes `0`, and so on.

### Steps to reproduce

In my query, I have the following WHERE clauses:

```
...
.Where(t => t.RouteId == routeId)
.Where(t => t.Departure.AddHours(purchaseWindow) > localTime)
...
```

When translated, this is the WHERE clause for the resulting SQL query:

```
...
WHERE ([t].[RouteId] = @__routeId_0) AND (DATEADD(hour, CAST(@__purchaseWindow_1 AS int), [t].[Departure]) > @__localTime_2)
...
``` 

`purchaseWindow` is of type `double`, `localTime` and `t.Departure` are `DateTime`.

Is the integer casting an expected behavior?

### Further technical details

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 Pro x64 Version 1909
IDE: Visual Studio 2019 16.5.2

**Comment by ajcvickers** [comment] 2020-04-06 22:32
Duplicate of #11794

**Closed** 2022-10-16 18:19 UTC
Labels: customer-reported
