### ISSUE TITLE
UserManager.CheckPasswordAsync ==> DbUpdateConcurrencyException

### ISSUE THREAD

**Issue by toddtsic** [dotnet/efcore#2408] opened 2015-06-18 13:36 UTC
SaveChangesAsync that follows UserManager.CheckPasswordAsync fails with DbUpdateConcurrencyException.  Same SaveChangesAsync without preceeding UserManager.CheckPasswordAsync succeeds.

Failing Example (test password followed by table update that involves user being tested):

```
bool bCorrectPassword = await UserManager.CheckPasswordAsync(user, model.New_Player_Detail.TSIC_Password);
if (bCorrectPassword)
{
    Family_Members record = new Family_Members()
    {
        Family_UserId = model.Family_Details.Family_UserId,
        Family_Member_UserId = user.Id,
        modified = DateTime.Now,
        lebUserID = model.Family_Details.Family_UserId
    };

    db.Family_Members.Add(record);
    await db.SaveChangesAsync();
    return RedirectToAction("EditFamilyAccount", new { StatusMessage = String.Format("Player: {0} has been added to your family account.", model.New_Player_Detail.TSIC_Username) });
}
```

Successful Example:

```
//bool bCorrectPassword = await UserManager.CheckPasswordAsync(user, //model.New_Player_Detail.TSIC_Password);
//if (bCorrectPassword)
//{
    Family_Members record = new Family_Members()
    {
        Family_UserId = model.Family_Details.Family_UserId,
        Family_Member_UserId = user.Id,
        modified = DateTime.Now,
        lebUserID = model.Family_Details.Family_UserId
    };

    db.Family_Members.Add(record);
    await db.SaveChangesAsync();
    return RedirectToAction("EditFamilyAccount", new { StatusMessage = String.Format("Player: {0} has been added to your family account.", model.New_Player_Detail.TSIC_Username) });
//}
```

Failure is at dbSaveChangesAsync:
A database operation failed while processing the request. DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded.

Running sql trace across that step shows:

```
UPDATE [AspNetUsers] 
SET [AccessFailedCount] = @p0, [ConcurrencyStamp] = @p1, [Email] = @p3, [EmailConfirmed] = @p4, [FirstName] = @p5, [LastName] = @p7, [LockoutEnabled] = @p8, [LockoutEnd] = @p9, [LockoutEndDateUtc] = @p10, [NormalizedEmail] = @p11, [NormalizedUserName] = @p12, [PasswordHash] = @p13, [PhoneNumber] = @p14, [PhoneNumberConfirmed] = @p15, [SecurityStamp] = @p16, [TwoFactorEnabled] = @p17, [UserName] = @p18, [cellphone] = @p19, [cellphoneProvider] = @p20, [city] = @p21, [country] = @p22, [dob] = @p23, [fax] = @p24, [gender] = @p25, [imageFile] = @p26, [imageFileMimeType] = @p27, [phone] = @p28, [postalCode] = @p29, [state] = @p30, [streetAddress] = @p31, [workphone] = @p32
WHERE [ConcurrencyStamp] = @p2 AND [Id] = @p6;
SELECT @@ROWCOUNT;
```

This same query run in sql management studio SUCCEEDS (even when run while the debugger is on the line "db.SaveChangesAsync".  (If you don't run the command in sql management studio but step the debugger, the above DbUpdateConcurrencyException occurs.

**Comment by toddtsic** [comment] 2015-06-19 17:39
I just tried a different approach to validating the password and it works (code below).  The VerifyHashedPassword is returning PasswordVerificationResult.SuccessRehashNeeded.  Can I ignore, or should I deal with that?

Code showing replacement of UserManager.CheckPasswordAsync with PasswordHasher.VerifyHashedPassword:

    Family_Members record = new Family_Members()
    {
        Family_UserId = model.Family_Details.Family_UserId,
        Family_Member_UserId = thisUserId,
        modified = DateTime.Now,
        lebUserID = model.Family_Details.Family_UserId
    };

    PasswordHasher<ApplicationUser> pHasher = new PasswordHasher<ApplicationUser>();
    PasswordVerificationResult pvResult = pHasher.VerifyHashedPassword(user, user.PasswordHash, model.New_Player_Detail.TSIC_Password);

    switch (pvResult)
    {
        case PasswordVerificationResult.Success:
            db.Family_Members.Add(record);
            await db.SaveChangesAsync();
            return RedirectToAction("EditFamilyAccount", new { StatusMessage = String.Format("Player: {0} has been added to your family account.", model.New_Player_Detail.TSIC_Username) });
        case PasswordVerificationResult.SuccessRehashNeeded:
            db.Family_Members.Add(record);
            await db.SaveChangesAsync();
            return RedirectToAction("EditFamilyAccount", new { StatusMessage = String.Format("Player: {0} has been added to your family account.", model.New_Player_Detail.TSIC_Username) });
        case PasswordVerificationResult.Failed:
            return RedirectToAction("EditFamilyAccount", new { StatusMessage = "Credentials for new player were not valid." });
    }

**Comment by rowanmiller** [comment] 2015-06-30 18:51
Duplicate of https://github.com/aspnet/Identity/issues/498 and https://github.com/aspnet/Mvc/issues/2713

**Comment by conterio** [comment] 2016-05-27 07:00
i'm getting the same error when i call await _context.SaveChangesAsync();


```
if (ModelState.IsValid)  {
                try
                {
                   var` result = _context.Update(applicationUser);
                    await _context.SaveChangesAsync();

                    var result = _context.Update(applicationUser);
                    await _context.SaveChangesAsync();
                }

```

This is scaffolded code generated on the edit view from the default applicationuser.  Im not sure whats going on.

**Comment by smitpatel** [comment] 2016-05-28 05:42
@conterio - Can you file a separate issue? The exception may be the same but the cause could be totally different. While filing new issue, please provide more information about your model classes for us to repro the issue.

**Closed** 2022-10-16 08:59 UTC
