### ISSUE TITLE
InMemory: after adding LoggerFactory to dbContext,  dbContext can't access data (all returned tables are empty).

### ISSUE THREAD

**Issue by rpokrovskij** [dotnet/efcore#10420] opened 2017-11-28 22:38 UTC
1. create dbcontext over inMemory data provider
2. add some data using first instance of dbContext
3. check that data exists with second instance of dbContext (yes it is exist)
4. create third instance of dbContext (but this time add LoggerFactory for custom logging)
4b. try to return data from third dbContext - data source is empty

expected behaviour - data added on step 2 should be there (as it was on step 3). but it is absent. it seems like adding LoggerFactory brokes service cache of your internal service locators.

if you will add the data (in this third dbContext) you will see that custom logging works. but again this data will be not accessed through forth dbContext

if this is not an error it is a clear abstraction leak. 

please, do it simple - make a logging first of all injected through dbContext constructor, after this you can invest your time to other fancy methods "compatable with ASP". now you do not have basics.  

Code important for understanding:

```
        public static DbContextOptions Build(string connectionString, Action<string> verbose = null)
        {
            var optionsBuilder = new DbContextOptionsBuilder<MyDbContext>();
            optionsBuilder.UseInMemoryDatabase(connectionString);
            if (verbose != null)
            {
                var loggerFactory = new LoggerFactory(new[] { new MyLoggerProvider(verbose) });
                optionsBuilder.UseLoggerFactory(loggerFactory);
            }
            return optionsBuilder.Options;
        }

        internal static void InMemoryTest()
        {
            var connectionString = Guid.NewGuid().ToString();
            using (var dbContext = new MyDbContext(MyDbContext.Build(connectionString)))
            {
                var parentRecord1 = new ParentRecord()
                {
                    FieldA = "1_A",
                    FieldB1 = "1_B",
                    FieldB2 = "1_C",
                    FieldCA = "1_1",
                    FieldCB1 = "1_2",
                    FieldCB2 = "1_3"
                };

                var parentRecord2 = new ParentRecord()
                {
                    FieldA = "2_A",
                    FieldB1 = "2_B",
                    FieldB2 = "2_C",
                    FieldCA = "2_1",
                    FieldCB1 = "2_2",
                    FieldCB2 = "2_3"
                };

                dbContext.ParentRecords.Add(parentRecord1);
                dbContext.ParentRecords.Add(parentRecord2);
                dbContext.SaveChanges();
            }

            int id = 0;
            // ACT1: works well
            using (var dbContext = new MyDbContext(MyDbContext.Build(connectionString, null)))
            {
                var parentRecords = dbContext.ParentRecords
                   .Include(e => e.ParentRecordHierarchyRecordMap)
                   .ThenInclude(e => e.HierarchyRecord).ToList();
                var parentRecord = parentRecords.First(e => e.FieldA == "1_A");
                id = parentRecord.ParentRecordId;
            }

            // ACT2: the same + verbose ruins test !
            // throws ': 'Sequence contains no matching element' means can't access data
            var messages = new List<string>();
            Action<string> VERBOSE = (text) => {
                messages.Add(text);
                Console.WriteLine(text);
                Console.WriteLine();
            };
            using (var dbContext = new MyDbContext(MyDbContext.Build(connectionString, VERBOSE)))
            {
                var parentRecords = dbContext.ParentRecords
                   .Include(e => e.ParentRecordHierarchyRecordMap)
                   .ThenInclude(e => e.HierarchyRecord).ToList();
                var parentRecord = parentRecords.First(e => e.FieldA == "1_A");
                id = parentRecord.ParentRecordId;
            }
        }

```

Whole project: [ConsoleApp1.zip](https://github.com/aspnet/EntityFrameworkCore/files/1511861/ConsoleApp1.zip)

### Further technical details
EF Core version: 2.0.1
Database Provider: InMemory
Operating system: Windows 10
IDE:  Visual Studio 2017 5.0.5

**Comment by ajcvickers** [comment] 2017-11-28 23:34
Duplicate of #9613

**Comment by rpokrovskij** [comment] 2017-11-29 07:50
So this means "it is normal since  abstraction leaks are normal with EF core /ORM and ASP tubes".
They can explain this way any design fail.

**Closed** 2022-10-16 12:01 UTC
