### ISSUE TITLE
Message 'The given key 'PlatformTarget' was not present in the dictionary.' when running 'dotnet ef'

### ISSUE THREAD

**Issue by MarcelVersteeg** [dotnet/efcore#34579] opened 2024-08-30 15:24 UTC
I have two projects in a solution (will be more) that together will create an ASP.NET Core application. One of these projects is the application (will create the executable) and one of these projects is a library, that contains `DbContext` classes.

When I run any `dotnet ef <command>`, I get the message `The target "GetEFProjectMetadata" does not exist in the project`. I have looked in a lot of places and tried a lot of things, but I cannot get around this message.

The structure of my solution is as follows:
```
|- Application
|   \- Application.csproj
|- Library
|   \- Library.csproj
|- Solution.sln
|- Directory.Build.props
|- Directory.Build.targets
|- Directory.Packages.props
\- NuGet.config
```

### Application.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFrameworks>$(NetTargetFramework)</TargetFrameworks>
        <RootNamespace>Application</RootNamespace>
        <PublishAot>False</PublishAot>
        <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)Library/Library.csproj" />
    </ItemGroup>

</Project>
```

### Library.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFrameworks>$(NetTargetFramework)</TargetFrameworks>
        <RootNamespace>Library</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
```

### Directory.Build.props
```
<?xml version="1.0" encoding="utf-8"?>
<Project>
    <PropertyGroup>
        <!-- Build output location -->
        <MSBuildProjectExtensionsPath>$(MSBuildThisFileDirectory)_bin/_extensions/$(MSBuildProjectName)</MSBuildProjectExtensionsPath>
        <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)_bin/_intermediate/$(Configuration)/$(TargetFramework)/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
        <IntermediateOutputPath>$(BaseIntermediateOutputPath)</IntermediateOutputPath>
        <OutputPath>$(MSBuildThisFileDirectory)_bin/$(Configuration)/$(TargetFramework)/</OutputPath>
        <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>

        <!-- Selection of target frameworks -->
        <NetTargetFramework>net8.0</NetTargetFramework>

        <!-- The configurations to build -->
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>

        <!-- Package references -->
        <ManagePackageVersionsCentrally>True</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>True</CentralPackageTransitivePinningEnabled>
        <CentralPackageVersionOverrideEnabled>False</CentralPackageVersionOverrideEnabled>

        <!-- Code generation -->
        <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
        <IncludePackageReferencesDuringMarkupCompilation>False</IncludePackageReferencesDuringMarkupCompilation>
        <ImplicitUsings>disable</ImplicitUsings>
        <InvariantGlobalization>false</InvariantGlobalization>
        <AddRazorSupportForMvc>True</AddRazorSupportForMvc>

        <!-- Warnings and errors -->
        <WarningLevel>4</WarningLevel>
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>

        <!-- Binary generation -->
        <FileAlignment>512</FileAlignment>
        <AutoGenerateBindingRedirects>True</AutoGenerateBindingRedirects>
        <ErrorReport>prompt</ErrorReport>
        <Prefer32Bit>False</Prefer32Bit>

        <!-- Assembly signing -->
        <SignAssembly>False</SignAssembly>

        <!-- Code analysis -->
        <EnableNETAnalyzers>True</EnableNETAnalyzers>
        <AnalysisLevel>latest-all</AnalysisLevel>
        <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
        <_SkipUpgradeNetAnalyzersNuGetWarning>True</_SkipUpgradeNetAnalyzersNuGetWarning>
        <IsAotCompatible>True</IsAotCompatible>
    </PropertyGroup>

    <!-- The general build configuration properties -->
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        <DebugSymbols>True</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>False</Optimize>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
        <DebugType>pdbonly</DebugType>
        <Optimize>True</Optimize>
        <DefineConstants></DefineConstants>
    </PropertyGroup>

    <!-- Add packages used by all projects -->
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
    </ItemGroup>
</Project>
```

### Directory.Build.targets
```
<?xml version="1.0" encoding="utf-8"?>
<Project>
    <Target Name="GetEFProjectMetadata">
        <PropertyGroup>
            <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)_bin/_projectmetadata/$(MSBuildProjectName)/_intermediate/</BaseIntermediateOutputPath>
            <IntermediateOutputPath>$(BaseIntermediateOutputPath)</IntermediateOutputPath>
            <OutputPath>$(MSBuildThisFileDirectory)_bin/_projectmetadata/$(MSBuildProjectName)/</OutputPath>
        </PropertyGroup>
    </Target>
</Project>
```

### Directory.Packages.props
```
<?xml version="1.0" encoding="utf-8"?>
<Project>
    <ItemGroup>
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8" />
        <PackageVersion Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.4" />
    </ItemGroup>
</Project>
```

### Execution
Now, I run the command `dotnet ef dbcontext list --project "Library\Library.csproj" --startup-project "Application\Application.csproj" --configuration Debug --msbuildprojectextensionspath "_bin\_projectmetadata\Library\_intermediate" --verbose` and the output is as follows:
```
Using project 'Library\Library.csproj'.
Using startup project 'Application\Application.csproj'.
Writing '_bin\_projectmetadata\Library\_intermediate\Library.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=E:\Temp\tmpbuooiu.tmp /verbosity:quiet /nologo Library\Library.csproj
System.Collections.Generic.KeyNotFoundException: The given key 'PlatformTarget' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.EntityFrameworkCore.Tools.Project.FromFile(String file, String buildExtensionsDir, String framework, String configuration, String runtime)
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute(String[] _)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
The given key 'PlatformTarget' was not present in the dictionary.
```

### Include provider and version information

EF Core version: 8.0.8
Database provider: Pomelo.EntityFrameworkCore.MySql, version 8.0.2
Target framework: .NET 8.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.11.2
dotnet-ef tool: version 8.0.8

Is there something I am doing wrong?

**Comment by cincuranet** [comment] 2024-09-02 08:15
Dupe of #23853.

**Closed** 2024-09-02 08:15 UTC
Labels: customer-reported
