### ISSUE TITLE
Too many columns selected for collection subquery

### ISSUE THREAD

**Issue by InspiringCode** [dotnet/efcore#34851] opened 2024-10-08 11:34 UTC
Wenn doing a collection subquery, several ID columns of the related entities are also selected instead of only the used ones.

For example:
```csharp
var query = db
    .Users
    .Select(x => new
    {
        Id = x.Id,
        DefaultLanguageCode = x.DefaultLanguageCode,
        Permissions = x.AssignedPermissions.Select(x => x.BusinessKey).ToArray(),
    });
```
Generates:
```sql
SELECT [u].[Id], [u].[DefaultLanguageCode], [t].[BusinessKey], [t].[UserId], [t].[PermissionId], [t].[Id]
FROM [adm].[User] AS [u]
LEFT JOIN (
    SELECT [p].[BusinessKey], [u0].[UserId], [u0].[PermissionId], [p].[Id]
    FROM [adm].[UserPermission] AS [u0]
    INNER JOIN [adm].[Permission] AS [p] ON [u0].[PermissionId] = [p].[Id]
) AS [t] ON [u].[Id] = [t].[UserId]
ORDER BY [u].[Id], [t].[UserId], [t].[PermissionId]
```

But I would expect it to generate:

```sql
SELECT [u].[Id], [u].[DefaultLanguageCode], [t].[BusinessKey]
FROM [adm].[User] AS [u]
LEFT JOIN (
    SELECT [p].[BusinessKey]
    FROM [adm].[UserPermission] AS [u0]
    INNER JOIN [adm].[Permission] AS [p] ON [u0].[PermissionId] = [p].[Id]
) AS [t] ON [u].[Id] = [t].[UserId]
ORDER BY [u].[Id]
```

Which could be further simplified to (but this might maybe perform worse, I didn't test):

```sql 
SELECT [u].[Id], [u].[DefaultLanguageCode], [p].[BusinessKey]
FROM [adm].[User] AS [u]
LEFT JOIN[adm].[UserPermission] AS [u0] ON [u0].[UserId] = [u].Id
LEFT JOIN [adm].[Permission] AS [p] ON [u0].[PermissionId] = [p].[Id]
ORDER BY [u].[Id]
```

**Comment by roji** [comment] 2024-10-08 13:23
I agree that we're projecting unneeded columns here, and this is indeed a result of the collection projection.

@maumar does this sound familiar to you (any other issue tracking this)?

**Comment by maumar** [comment] 2024-11-01 05:53
These extra column projections are used as identifiers, so we know how to bucket the results. Related issue: https://github.com/dotnet/efcore/issues/32329

**Comment by roji** [comment] 2024-11-05 00:10
Makes sense - closing as duplicate.

**Comment by roji** [comment] 2024-11-05 00:10
Duplicate of #32329

**Closed by roji** 2024-11-05 00:10 UTC
Labels: type-enhancement, area-perf, customer-reported, area-query, consider-for-next-release
