### ISSUE TITLE
Why automatic fix-up is a terrible feature and needs to go

### ISSUE THREAD

**Issue by fschlaef** [dotnet/efcore#18838] opened 2019-11-11 14:31 UTC
In the [EF Core documentation](https://docs.microsoft.com/en-us/ef/core/querying/related-data), there is a paragraph that reads as follows :

> Entity Framework Core will automatically fix-up navigation properties to any other entities that were previously loaded into the context instance. So even if you don't explicitly include the data for a navigation property, the property may still be populated if some or all of the related entities were previously loaded.

This is a **terrible feature**. Let's say you have `Invoices` with a foreign key to `Customer`, and those invoices have `InvoiceLine`s attached to them.

If you do stuff like

```csharp
 context.Customer
	.Select(c => new Customer()
	{
		Invoice = c.Invoice  // I don't want invoice lines, only invoices
	})
``` 

EF will load **all** the `InvoiceLine` created during the context instance, even though you never wanted them. `.Include()` does the same thing. Imagine that with 100k entities, or even more.

EF is basically loading unwanted data, by default, totally transparently, with **absolutely no way** of turning it off anywhere. 

In another issue about this (#11564), @ajcvickers  said

> This is the same behavior that every version of EF from the first release in 2008 until now has had. There is nothing different here in the behavior of EF Core.

Sorry but this is **not** a valid argument. This is still a bad design.

I understand that deactivating this would be a major breaking change, but please at least allow us to configure the behavior, even globally (I don't need per-query rules, something like `DbContext.AutomaticFixUp = false` would be perfect.

### Steps to reproduce

https://github.com/fschlaef/AutomaticFixUpIsBad (also includes sh** workaround which is just re-instanciating the context, something you cannot do in real applications)

Built on 3.1.0-preview3 with latest runtime.

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1.0-preview3
Operating system: Window 10 x64
IDE: Visual Studio 2019 16.4

**Comment by ajcvickers** [comment] 2019-11-11 17:37
@fschlaef I ran you code and I didn't see any extra data being loaded from the database. Can you point to where this is happening?

**Comment by fschlaef** [comment] 2019-11-11 18:15
@ajcvickers This is not about what's being loaded from database or not, this is about network load, reliability, and trust.

When I call my API, and I make a SELECT call asking for field A, B and C, I don't want EF to add field E and F just because I happen to create some previously.

Also, something that is not featured in my repro (but I will happily build one for that) is the possibility to create infinite loop in objects, something that becomes a major problem when you try to serialize them to JSON. With Newtonsoft, the band-aid has been `ReferenceLoopHandling.Ignore` for years, but Json.NET doesn't support that (yet ?) which adds another issue.

Again, I see the interest in having this feature, but the fact that it's the default, works invisibly and cannot be configured or disabled makes it inherently problematic.

**Comment by ajcvickers** [comment] 2019-11-11 19:08
@fschlaef The assertion that extra data is being loaded is something that I wanted to look into. Given that that is not happening, I'm closing this as a duplicate of #11564 where this has been discussed extensively.

**Closed** 2022-10-16 14:55 UTC
Labels: customer-reported
