### ISSUE TITLE
It is not possible to select data in the database migration.

### ISSUE THREAD

**Issue by mytrash** [dotnet/efcore#8367] opened 2017-05-03 06:54 UTC
I am changing database tables from this scenario:
**users**
  id
  name
  address_street
  address_post

into this one:
**users**
  id
  name

**addresses**
  id
  user_id
  street
  post

It is not possible to select data from table **users.address_street**, **users.address_post**  and copy it into the **addresses.street**, **addresses.post** columns.

It is not possible to access dbcontext in the database migration and do something like this:
```C#
List<User> users = dbcontext.Users.ToList();
foreach (var user in users)
{
    Address address = new Address();
    address.User = user;
    address.Street = user.AddressStreet;
    address.Post = user.AddressPost;
    dbcontext.Addresses.Add(address);
}
context.SaveChanges();
```

**Comment by danielrjames** [comment] 2017-05-04 08:59
Have you tried the following?

1. Create your address class and properties. Add a new migration and update db.
2. Run the code you have listed.
3. Remove the properties from your user class (table). Add a new migration for this and update db (this should remove the user.address_street and user.address_post columns and data from the db.

**Comment by mytrash** [comment] 2017-05-04 11:03
Yes. The following steps work.

* But if you do bigger changes in your application, it is hard to manage the application life cycle, automate the update process etc. 
* If you work on the application in small team it is not easy to maintain these steps.
* It would be nice to do this in one step - in one migration or maybe multiple migrations without need to run the application between two independent migrations (or maybe there could be more migrations between our first migration that creates new table and the second one that removes two old columns).

**Comment by danielrjames** [comment] 2017-05-04 17:37
I understand your concerns, but you cannot migrate already deleted data from the User table.

You have to migrate first and then delete the address data from the User table.

**Comment by ajcvickers** [comment] 2017-05-06 01:59
@mytrash The prototyping work done recently on seeding (see #629) would cover some cases of this--if the data you are attempting to migrate is seed data. Beyond that, we have a work item for "data motion" during migrations which covers the more general case: #5642. Closing this as a dupe of those two issues.

For now, moving data around while migrating is best done by adding custom SQL to your migrations.

**Comment by tinchou** [comment] 2017-05-07 19:28
You probably want to write a `SELECT INTO` custom SQL statement. Migrations don't currently support moving data across tables, and it's not planned either.

**Closed** 2022-10-16 11:03 UTC
