### ISSUE TITLE
Count of products inside async method does not work

### ISSUE THREAD

**Issue by gancarzradoslaw** [dotnet/efcore#7284] opened 2016-12-20 20:06 UTC
I have upgraded project to EF 1.1. Before all was working good. 

Code:

        public override async Task<List<CategoryWithCountProducts>> ExecuteAsync()
        {
            var val = from c in DbContext.Categories
                      where c.IsVisible
                      orderby c.SequenceNumber
                      select new CategoryWithCountProducts()
                      {
                          Id = c.Id,
                          CategoryParentId = c.Parent.Id,
                          CountOfProducts = c.Products.Count(x => x.MainCategoryId == _mainCategoryId
                                                                  && x.IsActive
                                                                  && !x.IsBlocked
                                                                  && x.IsVerified),
                          Name = c.Name,
                          EncodedName = c.EncodedName
                      };

            return await val.ToListAsync();
        }

When I am not using ToListAsync all is OK:

        public override async Task<List<CategoryWithCountProducts>> ExecuteAsync()
        {
            var val = from c in DbContext.Categories
                      where c.IsVisible
                      orderby c.SequenceNumber
                      select new CategoryWithCountProducts()
                      {
                          Id = c.Id,
                          CategoryParentId = c.Parent.Id,
                          CountOfProducts = c.Products.Count(x => x.MainCategoryId == _mainCategoryId
                                                                  && x.IsActive
                                                                  && !x.IsBlocked
                                                                  && x.IsVerified),
                          Name = c.Name,
                          EncodedName = c.EncodedName
                      };

            return val.ToList();
        }

When I have removed CountOfProducts it was ok.

Exception message:
ArgumentException: Incorrect number of arguments supplied for call to method 'System.Threading.Tasks.Task`1[System.Int32] GetResult[Int32](System.Collections.Generic.IAsyncEnumerable`1[Microsoft.EntityFrameworkCore.Storage.ValueBuffer], System.Threading.CancellationToken)'
Parameter name: method

EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: (e.g. Visual Studio 2015)

**Comment by maumar** [comment] 2017-01-04 18:47
duplicate of https://github.com/aspnet/EntityFramework/issues/6534

**Closed** 2022-10-16 10:47 UTC
Labels: closed-duplicate
