### ISSUE TITLE
EF 6 .0   GroupBy  select Top N    Query  Count()  Throw Exception  

### ISSUE THREAD

**Issue by ByZhouhang** [dotnet/efcore#28353] opened 2022-07-01 01:55 UTC
### Include your code

I see in the documentation that ef6.0 support for GroupBy queries
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#improved-groupby-support

I have a paginated list (grouped to take the first N items), and when I try query.Count(), it throws an exception and does not query the database
```C#
var query= context.People
    .Include(e => e.Shoes)
    .GroupBy(e => e.Id)
    .Select(g => { PeopleId=g.key,   Count=g.Shoes.Count(),Top2List=   g.Shoes.take(2)});


var count=query.Count()  //Throw  exception  Nullable object must have a value.
var list =query.ToList()  // can be queried
var list2=query.Skip(0).Take(10).ToList() // can be queried
```

**Comment by smitpatel** [comment] 2022-07-01 05:15
Duplicate of #27796

**Closed** 2022-07-05 16:13 UTC
Labels: customer-reported
