### ISSUE TITLE
Entities derived from unmapped base class

### ISSUE THREAD

**Issue by nvmkpk** [dotnet/efcore#15843] opened 2019-05-29 15:32 UTC
Why can't I map entities derived from an unmapped base class? My context was working fine in version 2.1.4. I am unable to upgrade to 3.0 preview 5. without altering my context or entity classes.

**Comment by sdanyliv** [comment] 2019-05-30 18:06
This one? https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#totable-on-a-derived-type-throws-an-exception

**Comment by nvmkpk** [comment] 2019-05-30 20:44
> Currently it isn't valid to map a derived type to a different table.
As I understand this, it is about mapping base class and derived class to different tables. That is not what I am refering to. All my entity classes have a common base class that contains all common properties.

**Comment by AndriySvyryd** [comment] 2019-05-30 22:04
@nvmkpk Are you sure that the base is not mapped? Call `modelBuilder.Ignore<BaseType>()` to be sure.

If so please provide a small repro project that shows the issue.

**Comment by nvmkpk** [comment] 2019-05-31 16:12
I am sure base type is not mapped but I do not call Ignore on it. I will try that and update here.

**Comment by ajcvickers** [comment] 2019-06-10 16:41
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:22 UTC
Labels: closed-could-not-reproduce, customer-reported
