### ISSUE TITLE
Foreign key will be set to null when entity will be detached (but not the related object itself)

### ISSUE THREAD

**Issue by ManuelHaas** [dotnet/efcore#20000] opened 2020-02-20 11:44 UTC
When detaching an entity which has a Parent relation set, the ParentId property will be set to null but the Parent Relation stays intact. Don't know if it is because of the hierachical model.

### Steps to reproduce

``` C#
public class Question
{
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[MaxLength(450)]
	public string QuestionId { get; set; }

	/// <summary>
	/// Used to support Super-Sub-Question relationship
	/// </summary>
	public string ParentId { get; set; }
	public virtual Question Parent { get; set; }

	public virtual List<Question> Children { get; set; }
}

// entities must be tracked to that Children-relation will be set, but afterwards tracking can be removed.
var questions = await (from q in db.Questions.Include(c => c.Children)
					   select q).ToListAsync();

Console.WriteLine($"Before detach ParentId null count: {questions.Count(p => p.ParentId == null)}");
Console.WriteLine($"Before detach Parent null count: {questions.Count(p => p.Parent == null)}");

foreach (var question in questions)
{
	db.Entry(question).State = EntityState.Detached;
}

Console.WriteLine($"After detach ParentId null count: {questions.Count(p => p.ParentId == null)}");
Console.WriteLine($"After detach Parent null count: {questions.Count(p => p.Parent == null)}");
```

```
Output:
Before detach ParentId null count: 1
Before detach Parent null count: 1
After detach ParentId null count: 20
After detach Parent null count: 1
```

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: (Visual Studio 2019 16.4.4)

**Comment by ajcvickers** [comment] 2020-02-21 21:11
Duplicate of #19203 which is fixed for the 3.1.3 patch release, tentatively scheduled for March.

**Closed** 2022-10-16 18:12 UTC
Labels: customer-reported
