### ISSUE TITLE
Can not update identity column

### ISSUE THREAD

**Issue by thiagomoises** [dotnet/efcore#14024] opened 2018-11-27 20:08 UTC
I'm using Fluent API to map the database and an identity property.
Here is the code snippet of the map:
`
builder.Property (x => x.SeqChv)
   .HasColumnName ("seq_chv")
   .UseSqlServerIdentityColumn ()
   .ValueGeneratedOnAdd ();
`
But when using `_context.SaveChangesAsync ();` the following error is returned:

> System.Data.SqlClient.SqlException (0x80131904): Can not update identity column 'seq_chv'.
Can not update identity column 'seq_chv'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at 

EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Visual Studio 2017 15.9.2

**Comment by ajcvickers** [comment] 2018-11-28 17:38
@thiagomoises There isn't enough information here for us to be able to see what is going on. Can you post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by divega** [comment] 2018-12-07 19:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 13:41 UTC
Labels: closed-could-not-reproduce, customer-reported
