### ISSUE TITLE
Add: EF.StringConvert or allow to translate ToString

### ISSUE THREAD

**Issue by groege** [dotnet/efcore#18329] opened 2019-10-11 06:32 UTC
Lets say we have an entity with a column of type "Guid", now the user can filter for that column and obviously you don't want to type in the whole guid...
So I'd like to do those:
x => x.Guid.ToString().Contains("filter") (or EF.ConvertString(x.Guid).Contains("filter"))
x => x.Guid.ToString().StartsWith("filter")

etc. ==> the interesting thing is, that if i say expression.Complie() while using "ToString" it will say in the debugger "{Method = <Internal Error evaluation expression>}"

Also in the meantime can anyone help me to do MigrationBuilder.HasDbFunction for "CAST" on npgsql? Is there a way to add generic db functios like: 
static T Convert<T>(value);

where something like this happens
Convert<string>(value) ==> CAST(value as Text)
or 
Convert<DateTime>(value) => CAST(value as DATE)

maybe there is a way to get all the database type mappings and iterate them to register each possible type?

Thank you in advance

**Comment by groege** [comment] 2019-10-11 09:56
Postgres

**Comment by groege** [comment] 2019-10-11 10:12
@smitpatel Postgres:
```
System.InvalidOperationException: 'The LINQ expression 'Where<TransportOrderView>(
    source: FromSqlOnQueryable<TransportOrderView>(
        source: DbSet<TransportOrderView>, 
        sql: "SELECT * FROM (SELECT DISTINCT ON (o."Guid")  o."Guid" as "Guid", CASE WHEN n."Guid" IS NULL THEN o."StatusCreationDate" ELSE n."StatusCreationDate" END as "StatusCreationDate"FROM "TransportOrder" AS o LEFT JOIN(SELECT DISTINCT ON(n."TransportOrderGuid") * FROM "TransportDeliveryNote" n ORDER BY n."TransportOrderGuid", n."StatusCreationDate" DESC) AS n ON o."Guid" = n."TransportOrderGuid" ORDER BY o."Guid", o."StatusCreationDate" DESC, o."Pk" DESC) AS "TransportOrders" ORDER BY "TransportOrders"."StatusCreationDate" ", 
        parameters: (Unhandled parameter: __p_0)), 
    predicate: (t) => t.Guid.ToString().Contains(
        value: "13f", 
        comparisonType: InvariantCultureIgnoreCase))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'

```

**Comment by groege** [comment] 2019-10-11 10:29
Found a solution EF.Functions.ILike(x.ToString(), $"{strValue}%")
Would be nice to use functions like string.startswith,.. for this as well

**Comment by smitpatel** [comment] 2019-10-11 14:50
@groege - Which version of EF Core? Further, are you using passing `InvariantCultureIgnoreCase` in your Contains method call or no? This should likely be working.

**Comment by ajcvickers** [comment] 2019-10-18 16:06
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:49 UTC
Labels: closed-could-not-reproduce, customer-reported
