### ISSUE TITLE
dynamic query filter expression in include

### ISSUE THREAD

**Issue by cyptus** [dotnet/efcore#13647] opened 2018-10-16 19:02 UTC
i am creating a query filter to an entity which calls a func to be able to modify the variables within the expression on runtime:

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<GroupItem>().HasQueryFilter(x => GenerateMyFilter()(x));
}

protected Func<GroupItem, bool> GenerateMyFilter()
{
    return x => x.Priority >= Program.MinPriority;
}
```

this is working fine (also with changes to Program.MinPriority) while calling
```c#
dbContext.GroupItems.ToList()
```

but fails for including the data with:
```c#
dbContext.Groups.Include(x => x.Items).ToList()
```

ef core throws an NullReferenceException on this call:

```c#
Exception message:
Stack trace:
   at lambda_method(Closure , AnonymousObject )
   at System.Linq.Lookup`2.CreateForJoin(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.JoinIterator[TOuter,TInner,TKey,TResult](IEnumerable`1 outer, IEnumerable`1 inner, Func`2 outerKeySelector, Func`2 innerKeySelector, Func`3 resultSelector, IEqualityComparer`1 comparer)+MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollection[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relatedEntitiesFactory, Func`3 joinPredicate)
   at lambda_method(Closure , QueryContext , Group , Object[] )
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._Include[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Action`3 fixup)
   at lambda_method(Closure , Group )
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFCoreTest.Program.PrintGroups[TDbContext]()
```

### Steps to reproduce
sample console application to reproduce:
https://gist.github.com/cyptus/f9ac8bb74b2a7d98d148326502600d40

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Visual Studio 2017 15.8.6

**Comment by maumar** [comment] 2018-10-16 22:55
related/dupe of https://github.com/aspnet/EntityFrameworkCore/issues/11567

**Comment by cyptus** [comment] 2018-10-17 07:11
I see i can work around this by using instance level fields at the db context and a expression which uses these fields. EF core will notice changes to this field within the compiled query.
This functionality however seems very limited. As soon as i start using an array as field and query this array within the expression for example with Any(...) EF core starts throwing this exception again.

Is there any way to do some complexe queries on complexe types within these expressions used by the query filter in an include?

You changed prio and size of releated issue #10736 often, is this feature / bugfix considerd for any near release?

**Comment by smitpatel** [comment] 2018-10-17 19:42
@cyptus - What is the expected SQL for Any case according to you?

**Closed** 2022-10-16 13:35 UTC
Labels: closed-duplicate, customer-reported
