### ISSUE TITLE
Problem EF Core 1(RC2) - Command Where()

### ISSUE THREAD

**Issue by ralmsdeveloper** [dotnet/efcore#5235] opened 2016-04-30 23:47 UTC
## Hello friends,

I have a very strange case, if I make an appointment without declaring a variable EF Core 1 RC2, returns me all record of my table, but when I declare the variable he obeys the command!

Example

 var Database = new JamsoftBanco.JamsoftBancoContext(); 
  var c01 = Database.Cargos.Where(p=>p.codcargo<int.Parse(id)).Take(1).OrderByDescending(r=>r.codcargo).ToListAsync();
## Produces the following command

**SELECT [p].[codcargo], [p].[nomecargo]
FROM [Cargos] AS [p]**

---

 var _Codigo = int.Parse(id);
 var c02 = Database.Cargos.Where(p=>p.codcargo<_Codigo).Take(1).OrderByDescending(r=>r.codcargo).ToListAsync();
## Produces the following command

**exec sp_executesql N'SELECT [t].[codcargo], [t].[nomecargo]
FROM (
    SELECT TOP(@__p_1) [p0].[codcargo], [p0].[nomecargo]
    FROM [Cargos] AS [p0]
    WHERE [p0].[codcargo] < @___Codigo_0
) AS [t]
ORDER BY [t].[codcargo] DESC',N'@__p_1 int,@___Codigo_0 int',@__p_1=1,@___Codigo_0=2008**

Note that the only difference is the variable *\* "_Codigo "*\*  that is value without this within the lambda expression Where () command

Kind of weird not ?!

**Comment by rowanmiller** [comment] 2016-05-04 18:04
@ralmsdeveloper can you share your model. The Where clause in both queries is different, so it's probably more to do with the properties you are accessing rather than the fact you are using a variable. It looks like the `.Where(p=>p.codcargor.codcargo)` is getting evaluated in-memory, but without knowing what that property is it's hard to comment on why.

**Comment by ralmsdeveloper** [comment] 2016-05-06 01:15
The where clause is the same the only difference is that in a get the value of a variable and not another.

Follow my Model as requested.


    public class Cargos
    {
       [Key]
       [Display(Name="codcargo")]
       public int codcargo { get; set; } 
       
       [Display(Name="nomecargo")]
       [StringLength(50)]
       [Column(TypeName="varchar(50)")]
       public string nomecargo { get; set; }

   }

**Comment by smitpatel** [comment] 2016-05-06 16:41
dupe of #4826 which is fixed by #5251 recently.

**Closed** 2022-10-16 09:38 UTC
