### ISSUE TITLE
Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite ERROR: System.ArgumentException: shell is empty but holes are not

### ISSUE THREAD

**Issue by aramosvizcarra** [dotnet/efcore#34981] opened 2024-10-25 11:54 UTC
Hi there,
 
I'm migrating an application from .Net Framework 4.8 /  EF 6 to dotnet core 8 / EF Core 8 with spatial types so I started using NTS 
with the following packages 

```XML
    <PackageReference Include="NetTopologySuite" Version="2.5.0" />
    <PackageReference Include="NetTopologySuite.IO.SqlServerBytes" Version="2.1.0" />
   <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
   <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="8.0.10" />
```

I have several geometries that fail while loading and I can't understand why,
Here is one POLIGON that always fails 
 POLYGON ((175.6335 -40.973277777778, 176.216861111111 -40.898277777778, 177.709472222222 -40.712666666667, -179.733083333333 -38.44825, 178.291333333333 -38.369333333333, 177.556333333333 -38.4085, 176.571027777778 -39.049916666667, 175.6335 -40.973277777778))

The exception is the following:

 An exception occurred while iterating over the results of a query for context type 
      System.ArgumentException: shell is empty but holes are not
         at NetTopologySuite.Geometries.Polygon..ctor(LinearRing shell, LinearRing[] holes, GeometryFactory factory)
         at NetTopologySuite.Geometries.GeometryFactory.CreatePolygon(LinearRing shell, LinearRing[] holes)
         at NetTopologySuite.IO.SqlServerBytesReader.ToGeometry(Geography geography)
         at NetTopologySuite.IO.SqlServerBytesReader.Read(Stream stream)
         at NetTopologySuite.IO.SqlServerBytesReader.Read(Byte[] source)
         at lambda_method83(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()

We tried several modifications to the geometry but it still fails with the same error, so I would like some advice on this error. I'm pretty new to geometries so I can't really identify anything that could be wrong with those values.

**Comment by maumar** [comment] 2024-10-25 23:47
I can't reproduce this. I tried the following code and it works fine:

```cs
    internal class Program
    {
        static async Task Main(string[] args)
        {
            using var ctx = new MyContext();
            await ctx.Database.EnsureDeletedAsync();
            await ctx.Database.EnsureCreatedAsync();

            ctx.Database.ExecuteSqlInterpolated($$"""
INSERT INTO Entities (Id, Poly)
VALUES (
1, 
'POLYGON ((175.6335 -40.973277777778, 176.216861111111 -40.898277777778, 177.709472222222 -40.712666666667, -179.733083333333 -38.44825, 178.291333333333 -38.369333333333, 177.556333333333 -38.4085, 176.571027777778 -39.049916666667, 175.6335 -40.973277777778))')
""");

            var query = await ctx.Entities.Select(x => x).ToListAsync();
        }
    }

    public class MyEntity
    {
        public int Id { get; set; }
        public Polygon Poly { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<MyEntity> Entities { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MyEntity>(b =>
            {
                b.Property(x => x.Id).ValueGeneratedNever();
                b.Property(x => x.Poly).HasColumnType("geometry");
            });
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                    .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=NTSRepro;Trusted_Connection=True;MultipleActiveResultSets=true", x=> x.UseNetTopologySuite())
                    .LogTo(Console.WriteLine, LogLevel.Information)
                    .EnableSensitiveDataLogging();
        }
    }

```

**Comment by maumar** [comment] 2024-10-25 23:52
@aramosvizcarra please modify the code above in such a way that it reproduces the problem. 
On general note, EF just passes the spatial values from database to NTS objects and back, so this issue is likely external to EF. 
As such, we are not experts on how things work under the covers and why NTS ctor doesn't accept a particular shape. I think you are much better of asking about details on the NTS repo.

**Comment by aramosvizcarra** [comment] 2024-10-29 10:34
I think the whole binary will be more helpful. I did notice that just the coordinates doesn't create the same binary. I will update once I get a chance.

**Comment by roji** [comment] 2024-11-12 20:47
Closing as no repro has been provided.

@aramosvizcarra as @maumar wrote, what we need here is a code sample that shows the problem - a binary would not help us understand what it is that you're doing, or reproduce the error in order to fix it. If you're still running into the issue, please make the effort to provide a minimal, runnable code sample similar to what @maumar posted above (or tweak that sample).

**Closed by roji** 2024-11-12 20:47 UTC
Labels: customer-reported
