### ISSUE TITLE
Memory increase when creating so many Sqlite databases

### ISSUE THREAD

**Issue by dzwlxfiber01** [dotnet/efcore#29596] opened 2022-11-17 09:24 UTC
I developed a web API, which exposed three actions:
      Init
      Process  
      Exit
In each action, a scoped dbcontext will be created.

The APP will create separate Sqlite database for each client. And each client will only do one-time request for those three actions.
So many Sqlite database will be generated when receiving massive client requests. 
The problem is that we see the occupied memory for this APP will continuously increase. Is it caused by creating so many Sqlite databases?

EF Core version: 6.0.11
Database provider: (e.g. Microsoft.EntityFrameworkCore.Sqlite)
Target framework: (e.g. .NET 6.0)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by ajcvickers** [comment] 2022-11-17 10:34
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-11-28 13:21
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-11-28 13:21 UTC
Labels: customer-reported
