### ISSUE TITLE
uint not working with oid Postgres Entity Framework 2.1.1

### ISSUE THREAD

**Issue by nishantkagrawal** [dotnet/efcore#12546] opened 2018-07-04 05:08 UTC
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: An exception occurred while reading a database value for property 'XXX.Order'. The expected type was 'System.UInt32' but the actual value was of type 'System.UInt32'.
Stack trace: at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
```

### Steps to reproduce
I have a Model where one of the field is UInt32, the respective field in PostGres is oid.

It was working before upgrade to Entity Framework 2.1.1 in 2.0.1.

```c#
        [Column("order")]
        public uint Order { get; set; }
```

### Further technical details
EF Core version: 2.1.1
Database: PostgreSQL 9.5.10
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: 
IDE: Visual Studio 2017 15.7.4

**Comment by roji** [comment] 2018-07-04 05:41
You're not supposed to get an exception on this, but there was indeed a behavior change. The type `oid` is an internal PostgreSQL type and isn't really meant to be used in user tables. As such it is no longer mapped by default to. NET `uint`.

You can still explicitly map to `oid` by specifying the column type with the fluent API (`.HasColumnType()`) or the corresponding attribute.

Otherwise, unless I'm mistaken the new 2.1 value conversion system should store `uint` in a database `bigint` column.

But will check...

**Comment by roji** [comment] 2018-07-04 05:57
@nishantkagrawal, I couldn't reproduce the issue, see my code below which successfully maps a CLR `uint` property to a PostgreSQL `bigint` column, as expected (via value converters).

Regardless, even if there's an issue here, it's entirely Npgsql-related so please move this issue to http://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/.

Working code:

```c#
class Program
{
    static void Main(string[] args)
    {
        using (var ctx = new BlogContext())
        {
            ctx.Database.EnsureDeleted();
            ctx.Database.EnsureCreated();

            ctx.Blogs.Add(new Blog { Name = "foo", Uint = 8 });
            ctx.SaveChanges();

            var bb = ctx.Blogs.Single(b => b.Uint > 3);
            Console.WriteLine(bb.Uint);
        }
    }
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
    public uint Uint { get; set; }
}

public class BlogContext : DbContext
{
    public const string ConnectionString = "Host=localhost;Database=test;Username=npgsql_tests;Password=npgsql_tests";

    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder builder)
    {
        builder.UseNpgsql(ConnectionString);
    }
}
```

**Comment by ajcvickers** [comment] 2018-07-05 17:23
@roji I wonder if this issue happens when the column already exists in the database as an `oid` and then 2.1 is used which expects the column to be a `uint`?

**Comment by ajcvickers** [comment] 2018-07-05 17:23
Closing as a PostgreSQL provider issue, as stated above by @roji

**Closed** 2022-10-16 13:17 UTC
Labels: closed-external, customer-reported
