### ISSUE TITLE
In Memory Testing EFCore not working after upgrade to .NET Core 2

### ISSUE THREAD

**Issue by radenkozec** [dotnet/efcore#9759] opened 2017-09-11 09:56 UTC
I have a code like this for integration testing:
```
 _server = new TestServer(new WebHostBuilder().UseStartup<TestStartup>());
            _client = _server.CreateClient();
```
and TestStartup:
```
public class TestStartup : Startup
    {
        public TestStartup(IConfiguration env) : base(env)
        {
        }

        public override void SetUpDataBase(IServiceCollection services)
        {
           services
                .AddEntityFrameworkInMemoryDatabase()
                .AddDbContext<ApplicationDbContext>(options => options.UseInMemoryDatabase("SomeDatabaseName"));
        }
    }
```

When I read same database in integration test:
```
   var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
            optionsBuilder.UseInMemoryDatabase("SomeDatabaseName");
            using (var context = new ApplicationDbContext(optionsBuilder.Options))
            {
}
```
I see that this InMemoryInstance of Database is not shared between TestServer and my integration test even I specify same database name.

In previous version .NET Core 1.1 I did not have to specify database name and everything worked correctly.

**Comment by ajcvickers** [comment] 2017-09-11 16:46
Duplicate of #9613

**Comment by radenkozec** [comment] 2017-09-12 09:36
@ajcvickers Issue you referenced is probably my case but I don't know how to solve it.
In TestServer Host I am using IServiceCollection services from TestStartup class defined above but in constructor of test class I cannot access the same serviceProvider:
```
	public PaymentControllerTests()
        {
            _server = new TestServer(new WebHostBuilder().UseStartup<TestStartup>());
            _client = _server.CreateClient();
        }
```
Also I have tried to inject IServiceProvider in constructor of PaymentControllerTests Test Class. It does not work.
Not sure how to resolve same instance of ApplicationContext in Integration Tests and in TestServer Host.
In previous version .NET Core 1.1. this worked without any issues.

**Closed** 2022-10-16 11:48 UTC
