### ISSUE TITLE
Strong typing names in data annotations during reverse engineering where possible

### ISSUE THREAD

**Issue by piskov** [dotnet/efcore#32126] opened 2023-10-22 20:14 UTC
With data annotations you get db-first code like this:
```
[Index("Id")]
[PrimaryKey("Id")]
public class Post
{
    public int Id { get; set; }

    [ForeignKey("BlogKey")]
    public Blog Blog { get; init; }
}
```

It would be much more error-prone to use “strongly typed” `nameof` version when possible during reverse engineering:
- `PrimaryKey(nameof(First), nameof(Second)]`.
- string interpolation for foreign keys `[ForeignKey($"{nameof(First)}, {nameof(Second)}")]`.

This is especially useful if user would like to rename the property after scaffolding:
```
class Item
{
    [Column("ActualNameInDb")]
    public string Property {get; set;}
}
```
 Also one could easily see “usages” of the property when it’s referenced not via a magic string but a `nameof`.

**Comment by ajcvickers** [comment] 2023-10-23 13:16
Duplicate of #11744. See also https://github.com/dotnet/efcore/pull/26622.

**Comment by piskov** [comment] 2023-10-23 13:58
@ajcvickers oh, that’s rather unfortunate considering:

1. `[InverseProperty]` is only needed when there is more than one relationship between the same types (which is far more rare).

2. If you use pluralizing like with EF power tools, you would never end with `ICollection<Item> Item { get; set; }` — `Items` will be used as a name instead and there will be no clash to begin with.

So it seems far more useful `nameof` was sacrificed for rather rare case (unless there’re others not mentioned in the referenced issue) and I would rather fix those manually if they would ever arise (not that they will seem to appear with pluralizing or not including the inverse attribute if there’s just a single relationship between the entities).

Maybe it is something that can be used at least as an option during scaffolding. Or even maybe implemented manually in T4? In our codebase we do replace all those magic strings manually to `nameof`.

cc: @ErikEJ

**Comment by ajcvickers** [comment] 2023-10-25 18:28
@piskov The general case is very difficult to solve--we would end up re-implementing significant parts of the compiler. If you're okay with limitations, then the T4 templates are where to do this.

**Closed by ajcvickers** 2023-10-25 18:28 UTC
Labels: customer-reported
