### ISSUE TITLE
Attempt to execute supposedly unreachable code.

### ISSUE THREAD

**Issue by matthewDDennis** [dotnet/efcore#2707] opened 2015-07-24 19:00 UTC
Using Beta6 from the ASPNETBETA6 myget feed:
# Error

> An unhandled exception occurred while processing the request.
> InvalidOperationException: Code supposed to be unreachable
> System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
# Console Dump

```
[14:37:29 INF] from Article a in {from Article a in {value(Microsoft.Data.Entity.Query.EntityQueryable`1[CodeProject.Modules.Articles.EF.Article]) => AnnotateQuery(QueryAnnotation(AsNoTracking(value(Microsoft.Data.Entity.Query.EntityQueryable`1[CodeProject.Modules.Articles.EF.Article])))) => AnnotateQuery(QueryAnnotation(FromSql(value(Microsoft.Data.Entity.Query.EntityQueryable`1[CodeProject.Modules.Articles.EF.Article]), "Select Distinct a.* From Article as a Where a.PublishingStatusID = 2 and a.ArticleTypeId in (1, 3, 6, 8)", [])))} orderby [a].Updated desc 
select [a] => Skip(0) => Take(25)} select new <>f__AnonymousType2`16(Id = [a].Id, ArticleTypeId = [a].ArticleTypeId, Posted = [a].Posted, Updated = [a].Updated, Title = [a].Title, Authors = [a].Authors, Description = [a].Description, SubsectionId = [a].SubsectionId, TagIds = [a].TagIds, LicenseId = [a].LicenseId, SourceUrl = [a].SourceUrl, BaseName = [a].BaseName, Slug = [a].Slug, PageViews = [a].PageViews, DownloadCount = [a].DownloadCount, Thumbnail = [a].Thumbnail)

[14:37:29 INF] from Article a in {from Article a in value(Microsoft.Data.Entity.Query.EntityQueryable`1[CodeProject.Modules.Articles.EF.Article]) orderby [a].Updated desc select [a] => Skip(0) => Take(25)} select new <>f__AnonymousType2`16(Id = [a].Id, ArticleTypeId = [a].ArticleTypeId, Posted = [a].Posted, Updated = [a].Updated, Title = [a].Title, Authors = [a].Authors, Description = [a].Description, SubsectionId = [a].SubsectionId, TagIds = [a].TagIds, LicenseId = [a].Licen
seId, SourceUrl = [a].SourceUrl, BaseName = [a].BaseName, Slug = [a].Slug, PageViews = [a].PageViews, DownloadCount = [a].DownloadCount, Thumbnail = [a].Thumbnail)

[14:37:33 ERR] An unhandled exception has occurred while executing the request
System.InvalidOperationException: Code supposed to be unreachable
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteNewExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGener
ator)
   at System.Linq.Expressions.Expression`1.Compile()
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.RelationalDatabase.CompileAsyncQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Data.Entity.Query.CompiledQueryCache.CompileQuery(IDatabase database, MethodInfo compileMethodInfo, Type
 resultItemType, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.CompiledQueryCache.<>c__8`1.<ExecuteAsync>b__8_0(Expression q, IDatabase ds)
   at Microsoft.Data.Entity.Query.CompiledQueryCache.GetOrAdd(Expression query, QueryContext queryContext, IDatabase dat
abase, Boolean isAsync, Func`3 compiler)
   at Microsoft.Data.Entity.Query.CompiledQueryCache.ExecuteAsync[TResult](Expression query, IDatabase database, QueryCo
ntext queryContext)
   at Microsoft.Data.Entity.Query.EntityQueryProvider.ExecuteAsync[TResult](Expression expression)
   at Microsoft.Data.Entity.Query.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()

   at System.Linq.AsyncEnumerable.Aggregate[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Fu
nc`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.Aggregate[TSource,TAccumulate](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 acc
umulator, CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.ToList[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.Data.Entity.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationTok
en cancellationToken)
   at CodeProject.Modules.Articles.EF.ArticleQuery.<GetArticleSummariesPageFromDatabase>d__17.MoveNext() in D:\Dev\CodeP
roject3\CodeProject\src\Modules\Articles\CodeProject.Modules.Articles.EF\ArticleQuery.cs:line 184
```

**Comment by rowanmiller** [comment] 2015-08-04 16:45
Dupe of #325 - the query is accessing a navigation property (`...Authors = [a].Authors...`)

**Closed** 2022-10-16 09:03 UTC
