### ISSUE TITLE
EF Core 5 Scaffolding many to many issue

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#23050] opened 2020-10-19 19:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1222241/ef-core-5-scaffolding-many-to-many-issue.html)._

---
[severity:It bothers me. A fix would be nice]
Hi,
I recently installed and used EF Core 5 (SQLServer + Tools + Design RC2.20475.6) and I tried to use scaffolding on my database.
It appears that a Many to Many joint is missing.
The table has only 2 Ids columns, which are linked to 2 FKs, and... No the result is :
Tables : Enseigne (PK : Id) and Site (PK : Id)

modelBuilder.Entity<EnseignesSite>(entity =>
            {
                entity. HasKey(e => new { e.IdSite, e.IdEnseigne });

entity. HasOne(d => d.IdEnseigneNavigation)
                    . WithMany(p => p.EnseignesSite)
                    . HasForeignKey(d => d.IdEnseigne)
                    . OnDelete(DeleteBehavior.ClientSetNull)
                    . HasConstraintName("FK_EnseignesSite_Enseigne");

entity. HasOne(d => d.IdSiteNavigation)
                    . WithMany(p => p.EnseignesSite)
                    . HasForeignKey(d => d.IdSite)
                    . OnDelete(DeleteBehavior.ClientSetNull)
                    . HasConstraintName("FK_EnseignesSite_Site");
            });

Is it a known limitation ?

Thank you !
Erwan

---
#### Feedback Bot on 10/15/2020, 06:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2020-10-19 19:04
Duplicate of #22475

**Closed** 2022-10-16 19:05 UTC
Labels: customer-reported
