### ISSUE TITLE
Navigation properties of navigation properties of views don't want to include.

### ISSUE THREAD

**Issue by zn** [dotnet/efcore#25054] opened 2021-06-08 10:13 UTC
## Models
```C#
public class UploadFile
{
    public int Id { get; set; }
    public string OriginalFileName { get; set; }
    public string OriginalFilePath { get; set; }
    public string OriginalWebpFilePath { get; set; }
    public bool IsPublished { get; set; }

    public IList<CroppedUploadFile> CroppedFiles { get; set; }
}

public class CroppedUploadFile
{
    public int Id { get; set; }
    public string FilePath { get; set; }
    public string WebpFilePath { get; set; }
    
    public int UploadFileId { get; set; }
    public UploadFile UploadFile { get; set; }
}
```
The view (SQL):
```SQL
CREATE OR REPLACE VIEW ready_business.cards_and_lots_catalog AS
    rb.id,
    rb.title,
    uf.id AS picture_id
FROM ready_business.ready_business rb
    LEFT JOIN ready_business.ready_business_pictures rbp ON rbp.ready_business_id = rb.id and rbp.order = 0
    LEFT JOIN files.upload_files uf ON uf.id = rbp.picture_file_id and uf.is_published
```
Model for view:
```C#
public class ReadyBusinessCatalogView
{
    [Column("id")]
    public int Id { get; set; }

    [Column("title")]
    public string Title { get; set; }

    [Column("picture_id")]
    public int? PictureId { get; set; }

    public UploadFile Picture { get; set; }
}
```
### ER-diagram
Don't mind Lots and LotsPictures (that's why I need a view)
![er-diagram](https://user-images.githubusercontent.com/39989294/121165754-2a2a6c80-c859-11eb-919c-f4b7f8239a07.png)

## Question
I have a couple of tables and a view. There is a foreign key property in the view - **PictureId**. I want the Picture to be included with the data of the view. It's ok, I just do `.Include(x=>x.Picture)` and do some magic in DbContext configuration. Here is the code:
 
```C#
// AppDbContext.cs
protected override void OnModelCreating(ModelBuilder builder)
{
    builder.Entity<ReadyBusinessCatalogView>(entity =>
    {
        entity.HasNoKey();
        entity.ToView("cards_and_lots_catalog", "ready_business");
        entity.HasOne(x => x.Picture);
    });
}
```

```C#
// querying data
var dataWithPictures = context.ReadyBusinessCatalogView.Include(x => x.Picture).ToList();
```

At this point everything is alright. But. As you can notice, my **UploadFile** model has a relationship with the **CroppedFiles** table and I want them (cropped files) also to be included.

To do this, I put `.ThenInclude(x=>x.CroppedFiles)`:

```C#
// querying data
var notAllData= context.ReadyBusinessCatalogView
                              .Include(x => x.Picture)
                              .ThenInclude(x=>x.CroppedFiles)
                              .ToList();
```

The problem is that after adding `.ThenInclude()` context returns not all data. I don't know why some records missed.
Could you please help me with this? Maybe I need to configure something else or it is a bug?

### System information

EF Core version: 3.1.1
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: 3.1.402
Operating system: Windows 10
IDE: JetBrains Rider

**Comment by AndriySvyryd** [comment] 2021-06-12 01:02
This is not quite enough for us to repro the issue as we also need some records in the database. Please create a small project that illustrates the problem.

**Comment by AndriySvyryd** [comment] 2021-06-18 18:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:36 UTC
Labels: closed-could-not-reproduce, customer-reported
