### ISSUE TITLE
Error in SequentialGuidGenerator

### ISSUE THREAD

**Issue by peroyhav** [dotnet/efcore#20527] opened 2020-04-04 10:02 UTC
The SequentialGuidGenerator states it generates a new Guid in the same way as SQL server's NEWSEQUENTIALID(), however, since a new GUID is generated upon every insert, this does not generate the GUIDS in the same maner.

### Steps to reproduce

Insert multiple entities and compare the GUIDs of the newly created entities, they do not only differ in an incremental manner.

### Further technical details

The SequentialGuidValueGenerator should according to the documentation produce GUIDs in somewhat the same manner as the SQL server equivalent

To produce an example for testing on SQL server:

In order to correct, the bytes of the initially generated GUID should be stored in a field and used instead of generating a new Guid each time, in addition, if the GUID's shall be similar to a sequential GUID, the correct bytes should be updated, in the same manner as for SQL server.

e.g.
```sql
DECLARE @tbl TABLE(ID UNIQUEIDENTIFIER UNIQUE DEFAULT(NEWSEQUENTIALID()))

INSERT INTO @tbl VALUES(DEFAULT),(DEFAULT),(DEFAULT),(DEFAULT)
...
INSERT INTO @tbl VALUES(DEFAULT),(DEFAULT),(DEFAULT),(DEFAULT)

SELECT * FROM @tbl
```

**Comment by ajcvickers** [comment] 2020-04-06 15:05
@peroyhav Thanks for reporting this and for sending the PR. It looks like one of the same issues discussed on #11391 

@roji Can you look at this issue together with #11391 and the PR #20528 and determine if we need to do anything else as well?

**Comment by peroyhav** [comment] 2020-04-06 17:14
@ajcvickers I cant see the resemblance with SQL server and IIS Express here, the error in #11391 is an error when using EF core in IIS Express, while the error I reported, and proposed a solution for through PR #20528 is an issue with the way Sequential GUIDs were generated.

**Comment by ajcvickers** [comment] 2020-04-06 17:29
@peroyhav Linked the wrong issue. 🤦‍♂ Should be #19124.

**Comment by peroyhav** [comment] 2020-04-06 17:46
@ajcvickers Ok, thanks, It looks like this will solve parts of the issue. I'm not sure what clock value is used to seed SQL server, so I've used DateTime.UtcNow, the incremental part is therefore somewhat different from that of SQL server, In adition SQL server seems to have a constant node-id per server instance, and counts , the version I implemented, will have different node-id per instance. to ensure the same behavior, the count values should probably be static across instances, this would then require higher care to ensure thread safety. If I'm to do more work on this; are there any standards that should be taken into consideration simultaneously?

**Comment by peroyhav** [comment] 2020-04-06 18:03
This Issue looks a lot like #19124 I see that I have omitted Value in the class name when searching for Github issues, so it didn't pop up when I searched.

**Comment by roji** [comment] 2020-04-13 13:06
Duplicate of #19124

**Comment by roji** [comment] 2020-04-13 13:06
See valuable conversation and analysis in #20528 (thanks for doing that @peroyhav).

**Closed** 2022-10-16 18:19 UTC
Labels: customer-reported
