### ISSUE TITLE
error migration

### ISSUE THREAD

**Issue by killerangels** [dotnet/efcore#18107] opened 2019-09-27 19:46 UTC
### Steps to reproduce

error happing when I will deploy

### Further technical details
![erro do kct](https://user-images.githubusercontent.com/17747049/65797618-10f59100-e146-11e9-8985-f423f36cdf59.png)

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment] 2019-09-27 20:30
Duplicate of #17737

@killerangels - Can you share your project so we can reproduce the problem?

**Comment by killerangels** [comment] 2019-09-28 16:30
dotnet tool install -g dotnet-ef

**Comment by killerangels** [comment] 2019-09-28 16:30
Solved

**Closed** 2022-10-16 14:45 UTC
Labels: closed-duplicate, customer-reported
