### ISSUE TITLE
Include details in Exception for "LINQ Expression could not be translated" errors.

### ISSUE THREAD

**Issue by IronSean** [dotnet/efcore#21753] opened 2020-07-23 13:53 UTC
EF Framework used to provide specific errors if an expression could not be translated. I you tried to do `DateTime.Now - entity.Time > myTimespan` it would give you an errors like "TimeSpan can not be translated using Linq-to-SQL"

EFCore seems to just give a generic "The LINQ Expression could not be translated" error, but no additional guidance on which part of the expression is causing the problem. This causes unnecessary confusion when trying to determine which part of a LINQ expression is causing the problem, and I could see it being unnecessarily difficult for a newer user without a deep understanding of what Linq-to-SQL does and does not support.

Perhaps an inner exception could be passed through on `InnerException` or a better explanation message should be surfaced another way to describe the exact statements that are unable to be translated.

**Comment by ajcvickers** [comment] 2020-07-23 22:06
Duplicate of #20344. EF Core 5.0 already throws better messages for common cases where a query cannot be translated, and we are open to adding more.

**Comment by smitpatel** [comment] 2020-07-23 22:27
Filed #21762 for some cases. Which covers basic case mentioned above about DateTime - TimeSpan translation.

**Closed** 2022-10-16 18:34 UTC
Labels: customer-reported
