### ISSUE TITLE
Microsoft.EntityFrameworkCore.Design Stopped to work

### ISSUE THREAD

**Issue by jeferrodrigu-saino** [dotnet/efcore#6507] opened 2016-09-10 01:22 UTC
I having the next exception when im runing "dotnet ef" in the comand line, this is really unexpected. I did a full clean of the nuget cache, resintalling .net core, last thing that i didnt try is re-formatting the laptop. So, next is the error details.

I have no idea what i did wrong, but i will help to found the error in the bug, if exist.

The exeption:

Exception message:
System.IO.FileLoadException was unhandled
Message: An unhandled exception of type 'System.IO.FileLoadException' occurred in Unknown Module.
Additional information: No se puede cargar el archivo o ensamblado 'Microsoft.Extensions.Logging.Abstractions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ni una de sus dependencias. La definición del manifiesto del ensamblado no coincide con la referencia al ensamblado. (Excepción de HRESULT: 0x80131040)

EF Core version: "Microsoft.EntityFrameworkCore": "1.0.0"
Operating system: Win10 x 64
Visual Studio version: VS 2015

**Comment by divega** [comment] 2016-09-10 01:47
@ingdotrodriguezbarrios are you mixing RTM packages form NuGet with pre-release packages from the nightly feeds? That error occurred while trying to load a pre-release 1.1 version of a logging package.

**Comment by ingdotrodriguezbarrios** [comment] 2016-09-10 02:03
Im not loading 1.1, this is my project.json
[project.json.zip](https://github.com/aspnet/EntityFramework/files/465175/project.json.zip)

**Comment by smitpatel** [comment] 2016-09-13 21:23
I tried reproducing this but I got no error.
Steps followed:
1. Run `dotnet new` on command line to start a new project.
2. Copy `project.json` file from above attachment to the newly create project (replacing the default `project.json`)
3. Run `dotnet restore`
4. Run `dotnet ef`

You `project.json` looks correct. Try restoring packages again.
You can also follow above steps and see if it works to figure out if something is wrong with your project or nuget config/cache.

**Comment by smitpatel** [comment] 2016-09-21 00:30
Closing as unable to reproduce.

**Closed by smitpatel** 2016-09-21 00:30 UTC
Labels: closed-could-not-reproduce
