### ISSUE TITLE
Need EF core to support many-to-many relationship directly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#21977] opened 2020-08-06 18:59 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/485228/need-ef-core-to-support-many-to-many-relationship.html)._

---
<p>In EF6, we could use many to many directly like</p><pre> modelBuilder.Entity&lt;Student&gt;() 
         .HasMany&lt;Course&gt;(s =&gt; s.Courses)                
        .WithMany(c =&gt; c.Students) </pre><p>When it comes to EF core, we have to represent a many-to-many relationship by including an entity class for the join table and mapping two separate one-to-many relationships</p><pre class="">class MyContext : DbContext
{
    public DbSet&lt;Post&gt; Posts { get; set; }
    public DbSet&lt;Tag&gt; Tags { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity&lt;PostTag&gt;()
            .HasKey(t =&gt; new { t.PostId, t.TagId });

        modelBuilder.Entity&lt;PostTag&gt;()
            .HasOne(pt =&gt; pt.Post)
            .WithMany(p =&gt; p.PostTags)
            .HasForeignKey(pt =&gt; pt.PostId);

        modelBuilder.Entity&lt;PostTag&gt;()
            .HasOne(pt =&gt; pt.Tag)
            .WithMany(t =&gt; t.PostTags)
            .HasForeignKey(pt =&gt; pt.TagId);
    }
}

public class Post
{
    public int PostId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }

    public List&lt;PostTag&gt; PostTags { get; set; }
}

public class Tag
{
    public string TagId { get; set; }

    public List&lt;PostTag&gt; PostTags { get; set; }
}

public class PostTag
{
    public int PostId { get; set; }
    public Post Post { get; set; }

    public string TagId { get; set; }
    public Tag Tag { get; set; }
}
<br></pre><p>From <a href="https://github.com/aspnet/EntityFrameworkCore/issues/1368">github </a>discussion, it seems that the problem still exists nowadays.</p>

---
#### Jane Wu [MSFT] on 3/12/2019, 01:32 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
#### Christian Graus on 9/23/2019, 05:45 PM: 

<p>That this was still being talked about in March and is not here in August is literally INSANE.   Code first **** at the best of times, but that I need to create an entity, which then sits on my chain of logic, for a joining table, in 2019, is ridiculous</p>

**Comment by ajcvickers** [comment] 2020-08-07 18:38
Duplicate of #10508. See #1368.

**Closed** 2022-10-16 18:36 UTC
Labels: closed-duplicate, customer-reported
