### ISSUE TITLE
An exception is thrown when adding an entity to the context with a SqlHeirarchyId property

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/efcore#14182] opened 2018-12-16 14:10 UTC
I would like to be able to set a value for a SqlHeirarchyId and have it saved in the database.  Instead, an exception is thrown by System.Core.

To reproduce:

Model:

```
public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }
    public SqlHierarchyId? NodeId{get;set;}
}
```

Code to reproduce:

```
var newBlog = new Blog { Url = "http://blogs.msdn.com/adonet" };
newBlog.NodeId = SqlHierarchyId.GetRoot();
db.Blogs.Add(newBlog); //Exception thrown here.
```
>Exception thrown: 'System.ArgumentException' in System.Core.dll
An unhandled exception of type 'System.ArgumentException' occurred in System.Core.dll
Argument must be boolean

### Further technical details
EF Core version: 2.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10
IDE: Visual Studio 2017 15.9)

**Comment by gregoryagu** [comment] 2018-12-16 14:13
If the SqlHierarchyId is removed from the Model, then no error is thrown.

**Comment by sergkr** [comment] 2019-08-07 12:53
Running into the same issue here with `Microsoft.EntityFrameworkCore` v2.2.6 and `Microsoft.SqlServer.Types` v14.0.1016.290, except the workaround with setting `CurrentValues` did not work. I also noticed this issue only occurs if the `SqlHierarchyId` is declared as nullable in the model.

**Comment by ajcvickers** [comment] 2020-03-27 21:30
Closing as duplicate of #365; see discussion there.

**Closed** 2022-10-16 13:44 UTC
Labels: closed-duplicate, customer-reported, punted-for-3.0
