### ISSUE TITLE
not clear error message reading sqlite db with an incorrect model

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/efcore#4548] opened 2016-02-12 19:50 UTC
I'm creating the model for an existing sqlite database I have to handle with ef 7: I added as properties some not nullable integers that are mapped to sqlite columns that I discovered later contains null values.
While fetching rows where are present null values, the error is a generic NullReferenceException without any indication of the reason of the error or the name of the column.
I mapped in an incorrect way, I know, but the error was so generic that required time to understand the nature of the error.

**Comment by rowanmiller** [comment] 2016-02-12 20:00
Duplicate of https://github.com/aspnet/EntityFramework/issues/4289

**Closed** 2022-10-16 09:29 UTC
