### ISSUE TITLE
Extremely slow build for asp.net core 3.1 apps

### ISSUE THREAD

**Issue by rezathecoder** [dotnet/efcore#23435] opened 2020-11-22 10:07 UTC
I’m using visual studio community 2019 for developing asp.net core applications but i experience extremely slow builds that is really preventing me from doing my work. So here is the situation:

I was using version 16.7.7 of visual studio 2019 on windows 10 20H2 update and when i started build process it took about 10 MINUTES each time. So i updated to version 16.8.2 and things got worse.

Now it takes more than 30 MINUTES to build my project. During build VBCSCompiler process uses 100% of CPU power and more than 6GB of RAM and i’m unable to use my computer in the mean time. I run on SSD so it’s not a problem related to slow disk.

I use asp.net core 3.1.9 mvc and i’m working on a medium sized project with about 800 CS files and 400 razor views and a few .resx files.

The build configuration is set on Any CPU and there is no difference between debug and release modes.

### Important Note:
When i make a change in views (.cshtml files) the build time is about 30 SECONDS which is normal and acceptable but if i change in CS files even only one line of code in a single file i have to wait 30 MINUTES to see the result.
I don’t think it’s related but i use Git for source control and NPM for managing client side libraries.

Please help me with this problem. Thanks!

**Comment by roji** [comment] 2020-11-23 09:56
> Then i found that every migration has a .Designer.cs file which is about 2.5MB in size so over 250MB of csharp files in Migrations folder!

@rezathecoder 2.5MB per migration is indeed problematic - may I ask what you're doing to reach these sizes? Are you by any chance seeding large data via migrations (#21065)?

**Comment by rezathecoder** [comment] 2020-11-23 12:40
> 
> 
> > Then i found that every migration has a .Designer.cs file which is about 2.5MB in size so over 250MB of csharp files in Migrations folder!
> 
> @rezathecoder 2.5MB per migration is indeed problematic - may I ask what you're doing to reach these sizes? Are you by any chance seeding large data via migrations (#21065)?

Yes i am seeding my database but it's not binary data like the issue you mentioned and it's not very large.
I think the code related to seeding process should only exist in the first migration but why it is repeated in every single migration that i created after seeding?

**Comment by rezathecoder** [comment] 2020-11-23 12:46
> 
> 
> @rezathecoder can you try out [this recommendation](https://github.com/dotnet/efcore/issues/23426#issuecomment-731710962)

Answering to the question asked in the comment you mentioned: Yes i this slowness existed before in version 16.8 and 16.7 and earlier.
And about using daily build of dotnet SDK can you give me a reference to how to do it? I'm using asp.net core 3.1

**Comment by rezathecoder** [comment] 2020-11-23 17:45
@mkArtakMSFT  @roji @ajcvickers 
As i mentioned before i think new migration .Designer.cs files should not contain the code for seeded data in previous migrations but i think there is a temporary solution and i wanted to know expert's opinion on that to see if there is any downside that i'm missing.

If we set the `Build Action` for old migrations that are already applied to the database to `None` they will be excluded from compilation process (and we get fast compilation) and it seem to generate correct SQL queries.
For example if we have 10 migrations and number 8 is the last applied migration on database, we could set `Build Action` for migrations number 1 to 7 to `None` and set the rest to `C# Compiler` then we can execute following command and get the correct script:
`Script-Migration -From 8 -Context ApplicationContext`

I also notice if i do this my `[ProjectName].dll` file size is 10 times smaller than before and i think compiled migration files has nothing to do with application functionality.

**Comment by roji** [comment] 2020-11-24 06:23
>  As i mentioned before i think new migration .Designer.cs files should not contain the code for seeded data in previous migrations but i think there is a temporary solution and i wanted to know expert's opinion on that to see if there is any downside that i'm missing.

@rezathecoder the Designer file for each migration needs to contain this information in order for EF to function correctly. If you exclude old migration files from compilation, that obviously speeds up your compilation; however, you will no longer be able to apply those old migrations (e.g. when creating a new database), or generate migration SQL scripts. In the general case, users do need to have old migrations compiled into their projects, even if in your specific case compiling only the latest one may work.

The first thing to understand from your side, is what your model contains that makes each Designer file 2.5MB big; if this is seeded data (regardless of whether it's binary or not), this is discouraged as I wrote above (and as we [mention in our docs](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding#limitations-of-model-seed-data)). If seeding data what's  causing your Designer files to be 2.5MB big, consider switching to [custom initialization logic](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding#custom-initialization-logic) instead.

Finally, we are indeed currently investigating some reports that Visual Studio 16.8 has worsened the build times around migrations. One issue has already been located and [fixed in VS 16.8.2](https://github.com/dotnet/efcore/issues/23291#issuecomment-728862715), and I'm looking into another one which may explain the difference you're seeing between 16.7.x and 16.8.2. However, even your starting situation with VS 16.7.x, where your build takes 10 minutes, is abnormal, and is probably the result of big seeded data as I wrote above.

**Comment by rezathecoder** [comment] 2020-11-24 18:33
@roji Thanks for your response. Yes the big size of migration files is related to seeding data and i will try to switch to custom initialization logic. I guess for now we could apply that temporary solution and exclude old migrations and if we needed to create new database just set the build action to `C# Compiler` again.
Thanks for your effort for making efcore better i'm waiting to hear good news from the team.

**Comment by rezathecoder** [comment] 2020-11-26 11:35
@roji  So i tried to switch to custom initialization logic but i think it's not suitable for me because i have a lot of base information that i need to seed into my database (about 10,000 records) that are rarely changed. According to code example in docs i need to check if the record exists or not then try to insert it and it can't be done for large data. I think efcore needs a new way to handle data seeding. I will post some ideas on that area in a new issue soon.

**Comment by ErikEJ** [comment] 2020-11-26 15:49
@rezathecoder Where in the docs - you should be able to use MERGE with SQL Server.

**Comment by ajcvickers** [comment] 2020-12-04 17:27
@roji How about this one?

**Comment by roji** [comment] 2020-12-05 15:04
@rezathecoder coming back to this, just to make sure - your original post above mentions a build time regression from 10 minutes to 30 when upgrading from VS 16.7.x to 16.8.2. Can you please confirm this (https://github.com/dotnet/efcore/issues/23435#issuecomment-732140341 may suggest otherwise), and specifically that you're still experiencing a *regression* in 16.8.2 (as opposed to 16.8.0 or 16.8.1)?

If so, can you please put together some sort of repro that we can investigate?

**Comment by rezathecoder** [comment] 2020-12-12 16:06
> 
> 
> @rezathecoder Where in the docs - you should be able to use MERGE with SQL Server.

@ErikEJ Can you please give me more info about this MERGE operation ?

**Comment by rezathecoder** [comment] 2020-12-12 16:08
> 
> 
> @rezathecoder coming back to this, just to make sure - your original post above mentions a build time regression from 10 minutes to 30 when upgrading from VS 16.7.x to 16.8.2. Can you please confirm this ([#23435 (comment)](https://github.com/dotnet/efcore/issues/23435#issuecomment-732140341) may suggest otherwise), and specifically that you're still experiencing a _regression_ in 16.8.2 (as opposed to 16.8.0 or 16.8.1)?
> 
> If so, can you please put together some sort of repro that we can investigate?

@roji Yes the slowness existed before 16.8.2 but it got worse in 16.8.2.
I temporarily solved my problem by excluding old migrations from build process

**Comment by ErikEJ** [comment] 2020-12-12 16:14
sure: https://docs.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql?view=sql-server-ver15

**Comment by roji** [comment] 2020-12-12 16:50
@rezathecoder what you describe doesn't correspond to anything I'm aware of at the moment... Having 250MB of source files in your migrations directory (because of seeding) is indeed going to cause significant build slowness - but there isn't supposed to be a regression.

In order for me to investigate, can you please put together a repro project?

**Comment by rezathecoder** [comment] 2020-12-13 20:37
@roji Sorry i can't upload my project files. But if you say there should not be a regression, maybe the slowness i experienced after updating is because i probably added new migrations and it made build process longer because as i was investigating the problem by adding migrations one by one, i discovered that build time is growing exponentially. So by adding just one or two migrations i colud get 3 times slower build.

**Comment by roji** [comment] 2020-12-13 22:37
If that's true, that also definitely sounds like something that should be investigated - build times shouldn't get exponentially slower as migrations are added. If you'd like to pursue this further, you can also share a project privately (e.g. by sharing a private github repo with me, or otherwise sending me a download link to the email listed on my github profile).

**Comment by ajcvickers** [comment] 2021-01-08 15:07
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by WinInsider** [comment] 2021-02-03 21:46
one additional avenue to try out for those of use still experiencing slow build on 16.8 is to disable VS Extensions, ones that depend on Roslyn compiler, such as "Microsoft Code Analysis 2019" or "Visual Studio IntelliCode"
 
![image](https://user-images.githubusercontent.com/15760785/106813375-e6bbb980-663e-11eb-8be3-48141dfa3a23.png)

**Comment by roji** [comment] 2021-11-03 14:19
@geomorillo we aren't aware of any issue in EF Core. If you think there is one, can you please submit a code sample which shows this?

**Closed** 2022-10-16 19:11 UTC
Labels: closed-could-not-reproduce, customer-reported
