### ISSUE TITLE
Revert Migration doesn't work

### ISSUE THREAD

**Issue by JNickVA1** [dotnet/efcore#17511] opened 2018-11-18 09:54 UTC
I have followed the instructions above for rolling back a migration but it doesn't work. I have the 4 migration that have been applied to the database:
20181116220831_AgencyIdentity (migration class name AgencyIdentity)
20181117120739_AgencyTypeManagement (migration class name AgencyTypeManagement)
20181117174417_AgencyClientManagement (migration class name AgencyClientManagement)
20181117212205_AgencyCloudAzure (migration class name AgencyCloudAzure)

According to the instructions, I should simply enter the command:
Update-Database 20181117174417_AgencyClientManagement (which is the last good migration)
This results in the error: More than one DbContext was found. Specify which one to use. Use the '-Context' parameter for PowerShell commands and the '--context' parameter for dotnet commands. So, I added the context name as in:
Update-Database 20181117174417_AgencyClientManagement -Context:AgencyClientContext
This results in the info: No migrations were applied. The database is already up to date.

So, how exactly am I supposed to revert the database to a state consistent with a prior migration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/#revert-a-migration)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment] 2019-08-29 22:29
@JNickVA1 Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-09-06 16:31
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:38 UTC
Labels: closed-could-not-reproduce
