### ISSUE TITLE
Migration generator missing the namespace System.Collections.Generic in MySQL for ef core

### ISSUE THREAD

**Issue by yukozh** [dotnet/efcore#6367] opened 2016-08-19 10:32 UTC
Hi, I'm the author of  [Pomelo.EntityFrameworkCore.MySql](https://github.com/pomelofoundation/pomelo.entityframeworkcore.mysql). Since we have supported json db type, we have an issue in json type migrations.

If we add or remove a [`JsonObject<T>`](https://github.com/PomeloFoundation/Pomelo.Data.MySql/blob/master/src/Pomelo.Data.MySql/Json/JsonObject%601.cs) field which T is a generic collection, the generated migrations C# code missing the namespace `System.Collections.Generic`.(Both `20160819XXX_xxxxx.cs` and `XXXModelSnapshot.cs`)

The following code is the result of migration generator generated.

``` c#
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MyCatSample;

namespace MyCatSample.Migrations
{
    [DbContext(typeof(SampleContext))]
    partial class SampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "1.0.0-rtm-21431");

            modelBuilder.Entity("MyCatSample.Blog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<JsonObject<List<string>>>("Tags"); // Missing namespace System.Collections.Generic

                    b.Property<DateTime>("Time");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });
        }
    }
}

```

How should I fix the migration c# code generator to add the namespace in?

@rowanmiller @natemcmaster

**Comment by bricelam** [comment] 2016-08-19 15:52
Dupe of #5912

**Comment by divega** [comment] 2016-08-19 18:44
Closing as duplicate.

**Closed** 2022-10-16 09:55 UTC
Labels: closed-duplicate
