### ISSUE TITLE
Is it possible to configure EF Core to delete principal when dependent entity is deleted in one-to-one relationship?

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#14765] opened 2019-02-21 10:43 UTC
The problem I have is that DB's entities hierarchy is inverse to the logical one.

I have `User` and `Organization` aggregates each containing `Address` as a value object.
If I used separate tables for each type of addresses: `UserAddress`, `OrganizationAddress` - owned types feature would be a perfect fit.
However, I want to store all addresses in a single table. It means other entities must reference their address by `id` effectively making it a principal entity. But when I change address of user or organization the old address will be orphaned, if not explicitly deleted.

Is there any way to automate this behaviour?

**Comment by ajcvickers** [comment] 2019-02-22 20:36
@voroninp I recently answered a very similar question in #14658, so closing this as a duplicate of that.

**Comment by bert2** [comment] 2019-02-23 10:10
The problem seems similar to #14658, but actually isn't.

@voroninp, I think you can use entity inheritance to map your different types of addresses to the same table, because EFCore implements [table per hierarchy](https://www.learnentityframeworkcore.com/inheritance/table-per-hierarchy).

Your model would look something like this:

```c#
class User {
    [InverseProperty(nameof(UserAddress.User))]
    UserAddress Address { get; set; }
}
class Organizaion {
    [InverseProperty(nameof(OrgAddress.Organization))]
    OrgAddress Address { get; set; }
}
abstract class Address {
    string AddressType { get; set; }
    string Street { get; set; }
}
class UserAddress : Address {
    int UserId { get; set; }
    User User { get; set; ]
}
class OrgAddress : Address {
    int OrganizationId { get; set; }
    Organization Organization { get; set; ]
}
```

And inside the context you can define how EFCore should remember the different address types:

```
protected override void OnModelCreating(ModelBuilder modelBuilder) => modelBuilder
    .Entity<Address>(x => x
        .HasDiscriminator<string>("AddressType")
        .HasValue<UserAddress>("User")
        .HasValue<OrgAddress>("Org"));
```

EFCore will then map both address types to a single table with the additional columns `AddressType`, `UserId` (nullable), and `OrganizationId` (nullable). Depending on the type either the one or the other will be used as the FK to the principal entity.

Defining the discriminator column as done above is optional though. EFCore can it on its own as well.

**Closed** 2022-10-16 13:53 UTC
Labels: closed-duplicate, customer-reported
