### ISSUE TITLE
Exception using 'ThenBy' in EF Core 2.0.0-preview2-final

### ISSUE THREAD

**Issue by andreluizsecco** [dotnet/efcore#9136] opened 2017-07-10 20:47 UTC
I have a problem with this query.

```c#
var task = db.TaskRequests.OrderBy(x => x.Priority).ThenBy(x => x.RequestDate)
			.Where(x => x.IdTaskStatus == 1 || x.IdTaskStatus == 4)
			.Include(p => p.Task).Include(p => p.Attachments)
			.FirstOrDefault();
```
				
When I use the "ThenBy" statement, throws the exception:

```
"Unable to cast object of type 'System.Linq.Expressions.PropertyExpression' to type 'Microsoft.EntityFrameworkCore.Query.Expressions.Internal.NullConditionalExpression'."
```

When I delete "ThenBy", it works fine!

What's the problem?

### Further technical details
EF Core version: 2.0.0-preview2-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by smitpatel** [comment] 2017-07-10 20:53
dupe of #8369

**Comment by andreluizsecco** [comment] 2017-07-11 11:02
Using an indicated temporary workaround (Adding ToList()), it worked fine.

```c#
var task = db.TaskRequests.Where(x => x.IdTaskStatus == 1 || x.IdTaskStatus == 4)
                        .OrderBy(x => x.Priority)
			.Include(p => p.Task).Include(p => p.Attachments).ToList()
                        .OrderBy(x => x.RequestDate)
			.FirstOrDefault();
```

**Closed** 2022-10-16 11:11 UTC
Labels: closed-duplicate
