### ISSUE TITLE
Generated EF Core migrations should also compile warning-free when part of an assembly having an XML Documentation file

### ISSUE THREAD

**Issue by berendengelbrecht** [dotnet/efcore#26549] opened 2021-11-05 09:53 UTC
If I add a migration to my EF Core project, it always adds some "Missing XML comment for publicly visible type or member" warnings. To reproduce, check `XML documentation file` in the Build properties of the project containing migrations.

To resolve the issue, add this before each generated `partial class`, in both generated files for each migration and in `ContextModelSnapshot.cs`:
``` csharp
#pragma warning disable CS1591
```
And this after the same class:
``` csharp
#pragma warning restore CS1591
```

**Comment by ajcvickers** [comment] 2021-11-05 10:05
Duplicate of #10695

**Closed** 2022-10-16 20:12 UTC
Labels: closed-duplicate, customer-reported
