### ISSUE TITLE
Adding method that returns a Func to Entity Framework model causes exception "InvalidOperationException: The entity type '<>c' requires a primary key to be defined."   

### ISSUE THREAD

**Issue by mperdeck** [dotnet/efcore#18755] opened 2019-11-05 07:02 UTC
I have a class that I am using successfully as an Entity Framework model. I use .Net Core 2. It has the primary key explicitly defined:
   
```
public partial class SsoProfile
{
	[Key]
	public int Id { get; set; }

	.... more properties
}
```

I added this method to this class:

```
public Func<SsoProfile, IComparable> DefaultSortOrderSelector()
{
    return (SsoProfile x) => x.Id;
}
```

Now whenever I access the SsoProfile table via the SsoProfile class, I get the exception:

> InvalidOperationException: The entity type '<>c' requires a primary key to be defined.

Same happens when I add this method:

```
public Func<int, IComparable> DefaultSortOrderSelector()
{
    return (int x) => x;
}
```

But when I add this method, there is no exception:

```
public int DefaultSortOrderSelector()
{
    return Id;
}
```

How can I add a method to an Entity Framework model class that returns a Func?

**Comment by AndriySvyryd** [comment] 2019-11-05 21:12
@mperdeck Can you show how `DefaultSortOrderSelector` is used, where the exception is thrown from and the full stack trace?

**Comment by ajcvickers** [comment] 2019-11-15 17:33
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:54 UTC
Labels: closed-could-not-reproduce, customer-reported
