### ISSUE TITLE
add Migration creates silly migrations

### ISSUE THREAD

**Issue by glatzert** [dotnet/efcore#10334] opened 2017-11-17 15:08 UTC
dotnet ef migrations add "NewMigration" created very silly migrations:

Assume the following class being changed as follows:

```
public class MyEntity1_before {
  public int SomeId {get;set;}
}

public class MyEntity1_after {
  public int SomeId {get;set;}
  public int SomeOtherId {get;set;}
}
```

This Change to the Entity class resultet in a Migration, that
 1. Renamed SomeId to SomeOtherId (the original Name was "DisplayNameId" and "DisplayNameIdPlural")
 2. Created a new Column SomeId.

That's odd, but we ignored it, since it was easy enough to repair by Hand.

Today I something else happened upon adding a new DbSet to the Context.
More or less all tables were renamed to another table and adjusted, so the Schemas would match the original table.

Assume E3 beeing the new Entity, E1 and E1 beeing existing entities - the migration built something like:
 - Rename E2s to E3s
 - remove Surplus columns, add missing ones
 - rename columns with matching types to match names from E3.

 - Rename E1s to E2s
 - repeat the column nonsense

 - Create new E1-Table

I checked the Database, which Looks good - also the changes to the model-snapshot are only what I expected it to be.

### Further technical details
EF Core version: 2.0.1
Entity Framework Core .NET Command Line Tools
2.0.1-rtm-125
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: WIN10-x64
IDE: VS 2015.4.4

**Comment by ajcvickers** [comment] 2017-11-17 21:59
@glatzert We are not able to repro this with just the info posted. Can you please post a full code listing or project that reproduces the issue you are seeing?

**Comment by glatzert** [comment] 2017-11-17 22:10
I can share the project with you on Monday, so you can just add the migration and probably see the problem.

I will also provide the DbContext, ModelSnapshots and resulting Migration.

Am 17.11.2017 10:59 nachm. schrieb Arthur Vickers <notifications@github.com>:

@glatzert<https://github.com/glatzert> We are not able to repro this with just the info posted. Can you please post a full code listing or project that reproduces the issue you are seeing?

**Comment by glatzert** [comment] 2017-11-20 08:30
[MigrationIssue.zip](https://github.com/aspnet/EntityFrameworkCore/files/1486918/MigrationIssue.zip)

This is the DataAccess, Migration and Model Project of my Solution - I added the Migrations Project before adding the new Migration and after adding it. You'll see, that the last Migration is really huge (and somewhat crazy) compared to the changes in the ModelSnapshot.

**Comment by glatzert** [comment] 2017-11-22 10:21
I created the needed migration manually to move on.
Today I needed to remove an entity from the database, with interesting results as well:

It removed this:
```
modelBuilder.Entity("ZDV.JGUDirectory.Model.Entities.Public.IncludedGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RoleId");
                    b.Property<int?>("RoleSortKey");
                    b.Property<int>("StructuralUnitId");
                    b.Property<int>("TargetStructuralUnitId");
                    b.HasKey("Id");
                    b.HasIndex("RoleId");
                    b.HasIndex("TargetStructuralUnitId");
                    b.HasIndex("StructuralUnitId", "RoleId", "TargetStructuralUnitId")
                        .IsUnique();

                    b.ToTable("IncludedGroups","Pub");
                });
```
and all related parts from the ModelSnapshot, resulting in a migration which drops a lot of unrelated columns and foreign keys, just to recreate them.

**Comment by gcali** [comment] 2017-12-01 10:12
Today I found the same issue; I added a new DbSet and, instead of simply creating a new table, it started renaming tables and dropping/creating columns in other tables. While the result is coherent with the expected model, it leads to data loss.

Unfortunately I cannot share the code of this project; but I can say that I noticed that the issue might be linked to complex types. The migration has this strange behaviour when the new entity owns a complex type: if instead of using it I simply include its properties in the main object, the migration is successful.

I will try and reproduce the issue in a personal project in the next days.

**Comment by smitpatel** [comment] 2017-12-21 20:43
First part of this is duplicate of #9873 - Adding a property in owned type renames existing property instead of adding the new one.
Second part is duplicate of #10099 - Adding a new entity with similar complex type renames tables instead of creating new one.

**Closed** 2022-10-16 11:59 UTC
Labels: closed-duplicate
