### ISSUE TITLE
Foreign key nvarchar(450) is generated as nvarchar(max) in down script

### ISSUE THREAD

**Issue by joakimriedel** [dotnet/efcore#11116] opened 2018-03-01 14:44 UTC
A string foreign key which was previously nvarchar(450) will be generated as nvarchar(max) in down script.

### Steps to reproduce
Let's assume you have the following foreign key in some entity:

```c#
        public ApplicationUser AuthoredByUser { get; set; }
        public string AuthoredByUserId { get; set; }
```

When you script the *Up* migration for this entity, it will generate a column with the following definition:

```sql
CREATE TABLE [Posts] (
    [...]
    [AuthoredByUserId] nvarchar(450) NULL,
    [...]
);
```

Now remove this key from the entity, and generate a new migration. The *Up* migration will successfully drop the column. However, the *Down* migration will try to re-add the column as

```sql
ALTER TABLE [Posts] ADD [ApprovedByUserId] nvarchar(max) NULL;
```

This will also have the effect that the next SQL statement will fail on creating an index for a nvarchar(max) column.

```sql
CREATE INDEX [IX_Posts_ApprovedByUserId] ON [Posts] ([ApprovedByUserId]);

System.Data.SqlClient.SqlException (0x80131904): Column 'ApprovedByUserId' in table 'Posts' is of a type that is invalid for use as a key column in an index.
```

### Further technical details
EF Core version: 2.0.5
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.5.7

**Comment by bricelam** [comment] 2018-03-02 23:14
Similar to #10186

**Comment by bricelam** [comment] 2018-04-05 16:59
Duplicate of #10186

**Comment by bricelam** [comment] 2018-04-05 18:02
Never mind; not a dupe.

**Comment by jcemoller** [comment] 2018-04-06 17:58
@bricelam Installed 2.0.2-rtm-10011 and retried scripting the down migration. Still get nvarchar(max) as datatype.

**Comment by bricelam** [comment] 2018-04-06 20:00
You may need to regenerate the last two migrations. The Down is based on the model stored in the previous migration

**Comment by bricelam** [comment] 2018-04-06 20:01
The easiest fix is just to manually update the Down to be correct. The bug shouldn't happen again in future migrations

**Closed** 2022-10-16 12:11 UTC
