### ISSUE TITLE
How does efcore implement full join

### ISSUE THREAD

**Issue by luo007** [dotnet/efcore#29511] opened 2022-11-09 02:19 UTC

**Comment by roji** [comment] 2022-11-09 06:31
@luo007 your question is lacking information - what exact LINQ query are you looking at? Reading the [Loading related data](https://learn.microsoft.com/en-us/ef/core/querying/related-data/) topic is probably a good way to understand how EF deals with and join. And in any case, the simplest way to know how EF does something is to write a query and look at the resulting SQL (with ToQueryString or by turning on logging).

**Comment by ajcvickers** [comment] 2022-11-16 19:59
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-11-16 19:59 UTC
Labels: customer-reported
