### ISSUE TITLE
Wrong conversion of List of Enum with explicit conversion

### ISSUE THREAD

**Issue by hassanrazakhalid** [dotnet/efcore#32447] opened 2023-11-29 10:21 UTC
I am using postgres npgsql and migrated to net8 stable version and when i ran command from cli to generate migration, i see that List<ColumnType> is converted to interger[] in database, although i explicitly mentioned to convert it to List<string>. In EFCore7 it works as expected, it creates a postgres type "text[]". 
After running migration after migration to net8. The below piece of code is not expected.

```
 migrationBuilder.AlterColumn<int[]>(
                name: "ColumnTypes",
                table: "ReportTemplateMappings",
                type: "integer[]",
                nullable: false,
                oldClrType: typeof(List<string>),
                oldType: "text[]");
```

I'm also sharing following code snippet to show i am applying conversion to List<ColumnType>

```C#
[JsonConverter(typeof(JsonStringEnumConverter))]
 public enum ColumnType
{
    Formula,
    Display,
    Filter
}

public sealed class ReportTemplateMapping {

      public string Id { get; init; }
      public List<ColumnType> ColumnTypes { get; init; } = new ();
}

public sealed class ReportTemplateMapConfiguration: IEntityTypeConfiguration<ReportTemplateMapping>
{
    public void Configure(EntityTypeBuilder<ReportTemplateMapping> builder)
    {
        builder.HasKey(x => x.Id);
        builder.Property(x => x.ColumnTypes)
            .HasConversion<List<string>>();
    }
}

```

### Include provider and version information

EF Core version:
Database provider: Npgsql 8.0
Target framework: .NET 8.0
Operating system:
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
IDE: Rider

**Comment by hassanrazakhalid** [comment] 2023-11-29 12:40
Yes it does work. May i ask what is the reason behind of changing the old behavior. Also can you please point me to docs where this change in documented, so i can see if there any other breaking change that i need to be aware of.

Thank you.

**Comment by roji** [comment] 2023-11-29 12:55
This is related to the work done on primitive collections in EF 8.0; I indeed still need to investigate whether the breaking change really is necessary - and it not, possibly patch the provider to make the old style work as well. If not, I'll add a breaking change note.

But in any case, the new way using PrimitiveCollection() is the better/more standard way to model going forward, so I'd recommend keeping that. I'll go ahead and close this issue as a duplicate of https://github.com/npgsql/efcore.pg/issues/2982, and keep the latter to track investigating further.

**Closed by roji** 2023-11-29 12:55 UTC
Labels: customer-reported
