### ISSUE TITLE
Tracking issues after upgrading from aspnet core 2.2 to 3.0

### ISSUE THREAD

**Issue by steinbachio** [dotnet/efcore#18235] opened 2019-10-05 08:06 UTC
After upgrading to 3.0 (following the [guideline](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)) the edit action of at least one controller is not working. I am getting 

> InvalidOperationException: The instance of entity type 'ApplicationUser' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked.

This error is gone when i am downgrading to aspnet core 2.2 again.

### Steps to reproduce
ChangesController.cs // Edit Action 
```C#
[HttpPost]
[ValidateAntiForgeryToken]
[Authorize(Roles = Constants.ChangeAdministratorsRole + ", " + Constants.ChangeWritersRole)]
public async Task<IActionResult> Edit([Bind("ID,Title,ClerkID,ResponsibleID,Type,isActive,Description,CustomerID,Services,Devices,VirtualMachines,Racks,Files,ExistingFiles")] EditViewModel viewModel)
{
    // commented to ensure that it is not related to exception
    //_logger.LogInformation($"User with ID '{ _userManager.GetUserId(User) }' is trying to update Change { viewModel.ID }.");

    if (ModelState.IsValid)
    {
        try
        {
            Change oldChange = _context.Change.AsNoTracking()
                .Include(c => c.Clerk)
                .Include(c => c.Responsible)
                .Include(c => c.AddedBy)
                .Include(c => c.UpdatedBy)
                .Where(cng => cng.ID == viewModel.ID).First();
                    
            int oldversion = _context.ChangeVersion.Where(cv => cv.Change.ID == oldChange.ID).Count() + 1;
            _context.Add(new ChangeVersion(oldChange, oldversion)); // <-- Exception thrown here when adding to context, not when constructing ChangeVersion.
            await _context.SaveChangesAsync();
            
            // more code here but not related  to exception (commented out)
        }
        catch (DbUpdateConcurrencyException)
        {
            if (!ChangeExists(viewModel.ID))
            {
                return NotFound();
            }
            else
            {
                throw;
            }
        }
        return RedirectToAction(nameof(Index));
    }
    _logger.LogInformation($"User with ID '{ _userManager.GetUserId(User) }' did not succeed updating Change { viewModel.ID }.");

    return View(viewModel);
}
```
Change.cs
```C#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace supii.Common.Models
{
    public class Change
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public ApplicationUser Clerk { get; set; }
        public ApplicationUser Responsible { get; set; }
        public ChangeType Type { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy hh:mm:ss}")]
        public DateTime Start { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy hh:mm:ss}")]
        public DateTime End { get; set; }
        public bool isActive { get; set; }
        public string Description { get; set; }
        public Customer Customer { get; set; }
        public int CustomerID { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy hh:mm:ss}")]
        public DateTime AddedAt { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy hh:mm:ss}")]
        public DateTime UpdatedAt { get; set; }
        public ApplicationUser AddedBy { get; set; }
        public ApplicationUser UpdatedBy { get; set; }
        public virtual List<Service> Services { get; set; } = new List<Service>();
        public virtual List<Device> Devices { get; set; } = new List<Device>();
        public virtual List<VirtualMachine> VirtualMachines { get; set; } = new List<VirtualMachine>();
        public virtual List<Rack> Racks { get; set; } = new List<Rack>();
        public virtual List<ChangeVersion> Versions { get; set; } = new List<ChangeVersion>();
        public virtual List<File> Files { get; set; } = new List<File>();
    }
    public enum ChangeType
    {
        Change = 1,
        Incident = 2,
        Problem = 3,
        Task = 4
    }
}
```
ChangeVersion.cs
```C#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace supii.Common.Models
{
    public class ChangeVersion
    {
        public ChangeVersion()
        {

        }
        public ChangeVersion(Change change, int version)
        {
            Change = change;
            Title = change.Title;
            Clerk = change.Clerk;
            Type = change.Type;
            Responsible = change.Responsible;
            Start = change.Start;
            End = change.End;
            isActive = change.isActive;
            Description = change.Description;
            Customer = change.Customer;
            CustomerID = change.CustomerID;
            AddedAt = change.AddedAt;
            UpdatedAt = change.UpdatedAt;
            AddedBy = change.AddedBy;
            UpdatedBy = change.UpdatedBy;
            Version = version;
            Files = change.Files;
            Services = change.Services;
            VirtualMachines = change.VirtualMachines;
            Devices = change.Devices;
            Racks = change.Racks;
        }
        public Change Change { get; set; }
        public int Version { get; set; }
        public int ID { get; set; }
        public string Title { get; set; }
        public ApplicationUser Clerk { get; set; }
        public ChangeType Type { get; set; }
        public ApplicationUser Responsible { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy hh:mm:ss}")]
        public DateTime Start { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy hh:mm:ss}")]
        public DateTime End { get; set; }
        public bool isActive { get; set; }
        public string Description { get; set; }
        public Customer Customer { get; set; }
        public int CustomerID { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy hh:mm:ss}")]
        public DateTime AddedAt { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy hh:mm:ss}")]
        public DateTime UpdatedAt { get; set; }
        public ApplicationUser AddedBy { get; set; }
        public ApplicationUser UpdatedBy { get; set; }
        public virtual List<Service> Services { get; set; }
        public virtual List<Device> Devices { get; set; }
        public virtual List<VirtualMachine> VirtualMachines { get; set; }
        public virtual List<Rack> Racks { get; set; }
        public virtual List<File> Files { get; set; }
        public virtual List<ChangeVersion> Versions { get; set; }
    }
}
```
### Exception

> An unhandled exception occurred while processing the request.
> InvalidOperationException: The instance of entity type 'ApplicationUser' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
> Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap<TKey>.ThrowIdentityConflict(InternalEntityEntry entry)

> InvalidOperationException: The instance of entity type 'ApplicationUser' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

> Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap<TKey>.ThrowIdentityConflict(InternalEntityEntry entry)
> Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap<TKey>.Add(TKey key, InternalEntityEntry entry, bool updateDuplicate)
> Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap<TKey>.Add(TKey key, InternalEntityEntry entry)
> Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap<TKey>.Add(InternalEntityEntry entry)
> Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
> Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, bool acceptChanges, bool modifyProperties)
> Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, bool acceptChanges, bool modifyProperties, Nullable<EntityState> forceStateWhenUnknownKey)
> Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode<ValueTuple<EntityState, EntityState, bool>> node)
> Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph<TState>(EntityEntryGraphNode<TState> node, Func<EntityEntryGraphNode<TState>, bool> handleNode)
> Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph<TState>(EntityEntryGraphNode<TState> node, Func<EntityEntryGraphNode<TState>, bool> handleNode)
> Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph<TState>(EntityEntryGraphNode<TState> node, Func<EntityEntryGraphNode<TState>, bool> handleNode)
> Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, bool forceStateWhenUnknownKey)
> Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
> Microsoft.EntityFrameworkCore.DbContext.SetEntityState<TEntity>(TEntity entity, EntityState entityState)
> Microsoft.EntityFrameworkCore.DbContext.Add<TEntity>(TEntity entity)
> supii.Controllers.ChangesController.Edit(EditViewModel viewModel) in ChangesController.cs
> +
>                     _context.Add(new ChangeVersion(oldChange, oldversion));
> Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
> System.Threading.Tasks.ValueTask<TResult>.get_Result()
> System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
> Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
> Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
> Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
> Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
> Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
> Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
> Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
> Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
> Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
> Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
> Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
> Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows Server 2019
IDE: Visual Studio 2019 16.3.2

**Comment by ajcvickers** [comment] 2019-10-10 18:05
@smitpatel I think the issue here is that the no-tracking query now doesn't do identity resolution, which means this:
```C#
 Change oldChange = _context.Change.AsNoTracking()
                .Include(c => c.Clerk)
                .Include(c => c.Responsible)
                .Include(c => c.AddedBy)
                .Include(c => c.UpdatedBy)
                .Where(cng => cng.ID == viewModel.ID).First();
```
brings in multiple different `ApplicationUser` instances for the same ID.

We should discuss what pattern can be used instead.

**Comment by ajcvickers** [comment] 2019-10-11 22:54
@steinbachio After further discussion I have been attempting to reproduce exactly what you are seeing so as to investigate ways forward and have been unable to do so. Could you please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by mscrivo** [comment] 2019-10-14 02:32
I hit this error after upgrading to EF Core 3 as well.  Here's the scenario that causes it for us:

```C#
public class A
    {
        public long ID { get; set; }

        [InverseProperty("A")]
        public ICollection<B> CollectionOfB { get; set; }
    }

    public class B
    {
        public long ID { get; set; }

        [ForeignKey("ID")]
        [InverseProperty("CollectionOfB")]
        public A CompanyAccount { get; set; }

        [InverseProperty("CompanyAccountSync")]
        public ICollection<C> CollectionOfC { get; set; }

        [InverseProperty("CompanyAccountSync")]
        public ICollection<D> CollectionOfD { get; set; }
    }

    public class C
    {
        [ForeignKey("ID")]
        [InverseProperty("CollectionOfC")]
        public B B { get; set; }

        [ForeignKey("ID")]
        [InverseProperty("CollectionOfC")]
        public CommonType CommonType { get; set; }
    }

    public class D
    {
        [ForeignKey("ID")]
        [InverseProperty("CollectionOfD")]
        public B B { get; set; }

        [ForeignKey("ID")]
        [InverseProperty("CollectionOfD")]
        public CommonType CommonType { get; set; }
    }
        
    public class CommonType
    {
        public long ID { get; set; }

        [InverseProperty("CommonType")]
        public ICollection<C> CollectionOfC { get; set; }

        [InverseProperty("CommonType")]
        public ICollection<D> CollectionOfD { get; set; }
    }

    public async Task SomeMethod(CancellationToken cancellationToken)
    {
        var context = new DbContext(new DbContextOptions<DbContext>());

        context.A
            .Include(x => x.CollectionOfB)
                .ThenInclude(b => b.CollectionOfC)
                .ThenInclude(c => c.CommonType)
            .Include(x => x.CollectionOfB)
                .ThenInclude(b => b.CollectionOfD)
                .ThenInclude(c => c.CommonType);

        // change some property on A
        
        await context.SaveChangesAsync(cancellationToken);
    }
```

It's a contrived example, with a lot of stuff cut out and with the Type names what they are, but I stripped that out from our actual code that worked in 2.2 but fails with the below exception in 3.0.  Hopefully it'll help you track it down. With the above setup, it seems that because CommonType is included in both sub collections, and points to the the exact same ComonType in both, it can't figure out how to update it.

I can work around for now by setting the collections to null before saving, but it's not ideal because I have to track down every possible place this particular method of loading the entities is used in a save operation.

The exception when saving is:

```
System.InvalidOperationException: The instance of entity type 'CommonType' cannot be tracked because another instance with the same key value for {'ID'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
```

**Comment by ajcvickers** [comment] 2019-10-14 22:12
@mscrivo To me, this doesn't look like the same root cause. I tried to reproduce, but there is too much missing code, such as the configuration of the model. Please open a new issue and post a small, runnable project/solution or _complete_ code listing that demonstrates the exception you are seeing.

**Comment by mscrivo** [comment] 2019-10-15 13:32
@ajcvickers fair enough ... after some reflection, I feel like this is an issue with our code anyway, and EF Core 3 is just being more strict about it. I just wanted to add our experience to the pile just in case it helped.

**Comment by ajcvickers** [comment] 2019-10-18 16:00
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:47 UTC
Labels: closed-could-not-reproduce, customer-reported
