### ISSUE TITLE
ef-core tool 7.0.0-preview.2.22153.1 command 'dbcontext optimize' creates product version '7.0.0-preview.1.22076.6' annotation

### ISSUE THREAD

**Issue by schuettecarsten** [dotnet/efcore#27682] opened 2022-03-21 20:01 UTC
I use `dotnet tool run dotnet-ef -- dbcontext optimize` to precompile my model. That worked fine until preview.1, but after updating to preview.2.22153.1, the command to update the model still creates a product version annotation with value `7.0.0-preview.1.22076.6`. This causes lots of errors like this:

```
The model supplied in the context options was created with EF Core version '7.0.0-preview.1.22076.6', but the context is from version '7.0.0-preview.2.22153.1'. Update the externally built model.
```

From DbContextModelBuilder.cs:
```
AddAnnotation("ProductVersion", "7.0.0-preview.1.22076.6");
```

`dotnet tool list` output:
```
D:\Projekte\Source\CloudManagementTool\CloudManagementTool.DataAccess>dotnet tool list
Paket-ID       Version                      Befehle        Manifest
---------------------------------------------------------------------------------------------------------------------------------
dotnet-ef      7.0.0-preview.2.22153.1      dotnet-ef      D:\Projekte\Source\.config\dotnet-tools.json
```

I can update the model as often as I want, it does not create the expected version annotation. Deleting and restoring all local NuGet caches did not help. 

### Include provider and version information

EF Core version: 7.0.0-preview.2.22153.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0-preview.2
Operating system: Windows 11
IDE: Visual Studio 2022 Version 17.1.1

**Comment by AraHaan** [comment] 2022-03-22 04:38
Does using the ``dotnet-7`` feed version help?

**Comment by ajcvickers** [comment] 2022-03-31 18:53
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:29 UTC
Labels: closed-could-not-reproduce, customer-reported
