### ISSUE TITLE
Derived, owned type usage issue when configured as owned by another type

### ISSUE THREAD

**Issue by jonathansapp** [dotnet/efcore#19474] opened 2020-01-03 21:42 UTC
An exception is thrown when attaching an instance of an derived owned type to an entity when another property or entity has been configured with a reference to the same type.

### Steps to reproduce

```C#
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using Xunit;

namespace OwnedTypesTestProject
{
    public class OwnedTypesTests
    {

        [Fact]
        public void TestThatAnnualLeaveCanBeAnAValue()
        {
            // Arrange
            using var context = new TestContext(CreateOptions(nameof(TestThatAnnualLeaveCanBeAnAValue)));
            context.TestEntities.Add(new TestEntity { AnnualLeave = new A(4) });
            context.SaveChanges();

            var entity = context.TestEntities.Single();
            entity.AnnualLeave = new A(4);

            // Act
            context.SaveChanges(); // Succeeds
        }

        [Fact]
        public void TestThatAnnualLeaveCanBeAnBValue()
        {
            // Arrange
            using var context = new TestContext(CreateOptions(nameof(TestThatAnnualLeaveCanBeAnBValue)));
            context.TestEntities.Add(new TestEntity { AnnualLeave = new A(4) });
            context.SaveChanges();

            var entity = context.TestEntities.Single();
            entity.AnnualLeave = new B(4); // Note: not an 'A' type

            // Act
            context.SaveChanges(); // Fails
        }

        private DbContextOptions<TestContext> CreateOptions(string databaseName)
        {
            var optionsBuilder = new DbContextOptionsBuilder<TestContext>()
                .UseInMemoryDatabase(databaseName);

            return optionsBuilder.Options;
        }
    }

    public class TestContext : DbContext
    {
        public TestContext(DbContextOptions<TestContext> options) : base(options) { }

        public DbSet<TestEntity> TestEntities { get; set; }

        public DbSet<TestEntity2> TestEntities2 { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<TestEntity>(o => o.OwnsOne(a => a.AnnualLeave));
            modelBuilder.Entity<TestEntity2>(o => o.OwnsOne(a => a.BonusLeave));
        }
    }

    public class TestEntity
    {
        public int Id { get; private set; }

        public A AnnualLeave { get; set; }

        public TestEntity2 TestEntity2 { get; set; }
    }

    public class TestEntity2
    {
        public int Id { get; private set; }

        public B BonusLeave { get; set; }
    }

    // Owned type A
    public class A
    {
        public A(int value) => Value = value;

        public int Value { get; private set; }
    }

    // Owned type B
    public class B : A
    {
        public B(int value) : base(value)
        {
            if (value <= 0) throw new InvalidOperationException();
        }
    }
}

```

### Result

TestThatAnnualLeaveCanBeAnBValue fails with `System.InvalidOperationException : The instance of entity type 'B' cannot be tracked as the entity type 'A' because they are not in the same hierarchy.`

```C#
Result StackTrace:	
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateEntry(Object entity, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.NavigationReferenceChanged(InternalEntityEntry entry, INavigation navigation, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.NavigationReferenceChanged(InternalEntityEntry entry, INavigation navigation, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigation navigation)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.LocalDetectChanges(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges()
   at Microsoft.EntityFrameworkCore.DbContext.TryDetectChanges()
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at OwnedTypesTestProject.OwnedTypesTests.TestThatAnnualLeaveCanBeAnBValue()
```

Both tests succeed if `B` is never referenced as an owned type. For instance, making the following change to `TestEntity2`:

```C#
    public class TestEntity2
    {
        public int Id { get; private set; }

        public A BonusLeave { get; set; }
    }
```
will cause both tests to succeed. 

In `StateManager.GetOrCreateEntry(object entity, IEntityType entityType)`, the call to `entityType.IsAssignableFrom(runtimeEntityType)` fails (`runtimeEntityType.BaseType` is null, causing the call to `IsAssignableFrom` to fail).

This issue began when we upgraded from EF Core 2.1 to 3.1.

### Further technical details

EF Core version: 3.1.0
Database provider: Microsoft.EntityFrameworkCore.InMemory (also happens with SqlServer)
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.4.0)

**Comment by ajcvickers** [comment] 2020-01-06 21:59
Duplicate of #9630

**Closed** 2022-10-16 18:04 UTC
Labels: closed-duplicate, customer-reported
