### ISSUE TITLE
Recursive Hierarchy in self referenced table - ef core 5

### ISSUE THREAD

**Issue by tnlthanzeel** [dotnet/efcore#25649] opened 2021-08-22 04:23 UTC
Hi all,

i have a problem querying data using ef core 5.

i have a stackoverflow question posted for this [here]( https://stackoverflow.com/questions/68873946/ef-core-self-joined-icollection-query) . but seems like they didnt understand my question

following are my table structures

```C#
public class SoqHeading 
{
        public int Id { get; set; }
        
        public string ItemNo { get; set; } 
        public string Heading { get; set; }
        
        public SoqRevision SoqRevision_NP { get; set; }

        public ICollection<SoqItem> Items { get; set; }

        public int? ParentSoqHeadingId { get; set; }
        public SoqHeading Parent_NP { get; set; }

        public ICollection<SoqHeading> Children_NP { get; set; }
}

public class SoqItem 
{
    public int Id { get; set; }
    public SoqPreliminaryOrContract_enum PreliminaryOrContract { get; set; }
    
     
    public int SoqHeadingId { get; set; }
    
    public SoqHeading SoqHeading_NP { get; set; }
}
```

the problem is i need to query from the root node till i get to the end of the children node from the SoqHeading table including the Items. But when i do the following query 

```C#
   var entity = _context.SoqHeadings
                .Include(i=>i.Items)
                .Include(e => e.Children_NP)
                .Where(e => e.Level == SoqLevels_enum.L1 && e.SoqRevisionId == 4)
                .ToList();
```

i get the nodes only for the first children. the rest of the nested children are empty as follows

the root node is the SoqHeading, which has an collection of SoqHeeadings as children and a collection of Items for each SoqHeading which can be zero or many.
```
[
  {
    "Level": 1,
    "ItemNo": "C",
    "Items": [
      {
        "ItemNo": "c-1",
        "Qty": 77.00,
        "Rate": 0.00,
        "Amount": 0.00,
        "SoqHeadingId": 20,
      },
      {
        "ItemNo": "c-2",
        "Qty": 99.00,
        "Rate": 0.00,
        "Amount": 0.00,
        "SoqHeadingId": 20,
      }
    ],
    "Children_NP": [
      {
        "ItemNo": "C.1",
        "Items": null,
        "ParentSoqHeadingId": 20,
        "Children_NP": [],
        "Id": 24,
      },
      {
        "Level": 2,
        "ItemNo": "C.2",
        "Items": null,
        "Children_NP": [],
        "Id": 29,
      }
    ],
    "Id": 20,
  }
]
```
i need a query that will return all the nested children of the parent node for all levels as below

```
[
  {
    "Level": 1,
    "ItemNo": "C",
    "Items": [
      {
        "ItemNo": "c-1",
        "Qty": 77.00,
        "Rate": 0.00,
        "Amount": 0.00,
        "Id": 7,
      },
      {
        "ItemNo": "c-2",
        "Qty": 99.00,
        "Rate": 0.00,
        "Amount": 0.00,
        "Id": 8,
      }
    ],
    "Children_NP": [
      {
        "ItemNo": "C.1",
        "Items": [],
        "Children_NP": [
          {
            "ItemNo": "C.1.1",
            "Items": [
              {
                "ItemNo": "c.1.1-1",
                "Qty": 565.00,
                "Rate": 0.00,
                "Amount": 0.00,
                "Id": 3,
              },
              {
                "ItemNo": "c.1.1-2",
                "Qty": 687.00,
                "Rate": 0.00,
                "Amount": 0.00,
                "Id": 4,
              }
            ],
            "Children_NP": [],
            "Id": 25
          },
          {
            "ItemNo": "C.1.2",
            "Items": [
              {
                "ItemNo": "c.1.2-1",
                "Qty": 77.00,
                "Rate": 0.00,
                "Amount": 0.00,
                "Id": 5,
              },
            ],
            "Children_NP": [],
            "Id": 31,
          }
        ],
        "Id": 24,
      },
      {
        "ItemNo": "C.2",
        "Items": [],
        "Children_NP": [],
        "Id": 29,
      }
    ],
    "Id": 20
  }
]
```
my database table (the top table is the SoqHeading and the bottom table is the SoqItem)

![image](https://user-images.githubusercontent.com/18216790/130342553-7d0430f6-b6f2-4200-87e8-431c79a2fc9e.png)

please help us with this

**Comment by ajcvickers** [comment] 2021-08-24 11:18
Duplicate of #14144

**Closed** 2022-10-16 19:43 UTC
Labels: closed-duplicate, customer-reported
