### ISSUE TITLE
Cannot delete the db file after calling DbContext.Database methods - EF Core 7.0.11

### ISSUE THREAD

**Issue by we3py** [dotnet/efcore#32882] opened 2024-01-22 15:47 UTC
The issue occurred after updating EF Core from 5.0.13 to 7.0.11.

After calling the CanConnect() and GetPendingMigrations() methods, the database file is "locked" and I cannot delete it (an IOException is thrown).

Calling the GC.Collect() and GC.WaitForPendingFinalizers() methods before deleting the file solves the problem, but this workaround is not perfect.

I tried closing the connection or getting rid of the context, but without success.

I found some posts on the Internet that the problem may be caused by sqlite and multi-threading causing the file to be locked by come process.

### Code
```
private bool CanConnectToDb(DbContext context)
{
  return context.Database.CanConnect();
}
```

```
private Task<bool> IsDatabaseMigrationOcured(DbContext context)
{
  var migrations = context.Database.GetPendingMigrations();
  if(!migrations.Any())
  {
      return Task.FromResult(true);
  }

  return Task.FromResult(false);
}
```
After calling either of these two methods, attempting to delete the database throws an IOException.
```
private void DeleteDb()
{
   fileSystem.DeleteFile(databasePath);
}
```

Some of those methods are of type Task, so maybe this is the problem.

**Comment by ajcvickers** [comment] 2024-01-22 15:52
Duplicate of https://github.com/dotnet/efcore/issues/26580

**Closed** 2024-01-25 18:05 UTC
Labels: customer-reported
