### ISSUE TITLE
Overriding MigrationBuilder CreateTable function

### ISSUE THREAD

**Issue by vasicvuk** [dotnet/efcore#23525] opened 2020-11-30 11:37 UTC
## Ask a question

Hi everyone i want to be able to set prefix or custom schema to Entity Framework in runtime. I managed to do everything except the part of migrations. Regarding schema I managed to do that but I want to have ability to automatically override name argument in **CreateTable** function for example if Prefix is provided for tables.

I see that **MigrationBuilder** methods are overridable but how can I set custom MigrationBuilder to be used ?

**Comment by roji** [comment] 2020-11-30 12:59
@vasicvuk the way to do this isn't to change MigrationBuilder, but rather to configure the table names in your model. For example, you can do something like the following:

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    foreach (var entityType in modelBuilder.Model.GetEntityTypes())
    {
        entityType.SetTableName("Prefix_" + entityType.GetTableName());
    }
}
```

**Comment by vasicvuk** [comment] 2020-11-30 13:02
Hi @roji,

I already have done this. But I want also to have ability to prefix table names when generating and executing migrations which I don't get by setting table name this way. I want to escape manually changing all migrations and do that on one place. For example overrding CreateTable like this:

```csharp
    public override CreateTableBuilder<TColumns> CreateTable<TColumns>(string name, Func<ColumnsBuilder, TColumns> columns, string schema = null, Action<CreateTableBuilder<TColumns>> constraints = null, string comment = null)
        {
            name = Prefix + "_" + name;
            return base.CreateTable(name, columns, schema, constraints, comment);
        }
```

**Comment by roji** [comment] 2020-11-30 16:41
Any reason you want to prefix when generating and executing migrations, as opposed to when setting up your model in OnModelCreating as I wrote above? Does the latter not meet your needs in some way?

**Comment by ajcvickers** [comment] 2020-12-07 16:31
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by vasicvuk** [comment] 2020-12-07 16:48
@roji I don't understand what model builder has to do with CS migrations. When migrations are executed it uses the table name from migration not from model builder. I am changing prefix in runtime so i don't wont to have different CreateTable with fixed string as name for each of possible prefixes

**Comment by roji** [comment] 2020-12-07 18:33
@vasicvuk migrations are generated by EF Core by comparing your model to a snapshot of model as it was in the past; any changes that are detected are generated as the Up method in your migration. The model is the authoritative, single source of truth, which contains all table and column names, while migrations are generated from that. This is why any change in table naming must be done in the model, as opposed to in the migrations themselves.

To drive the point home, table names are important in EF Core outside of migrations; for example, when executing a query, the model is consulted in order to find out what the table name is for an entity type, and to integrate that in the SQL. If you change table names in migrations only, your model will be out of sync with actual tables in the database, and your queries will fail.

Hope that clears things up - just think of the model as your source of truth.

**Comment by vasicvuk** [comment] 2020-12-07 18:41
@roji The thing is that i use CS migrations not SQL to initiate database structure that is why i need to add prefix to migrations also. As I said for model I already did this, but as I am using Containerized application that is taking care of own database I need to change also migrations in runtime (prefix the tables, change schema). In general i never have SQL files I am executing the migrations files directly with Database.Migrate()

**Comment by roji** [comment] 2020-12-07 18:44
@vasicvuk it doesn't matter if you use SQL files or Database.Migrate() - both these techniques apply the same migrations as defined in your migration's Up method. I also don't think containerization should play a role here - what exactly is the issue with defining your table names in your model?

**Comment by vasicvuk** [comment] 2020-12-07 18:49
Okey back to my question in Up method i have CreateTable function calling table "Reports" in model i prefixed the tables as you suggested but still CreateTable creates "Reports" table and not "prefix_Reports".

For containerization i have environment variables Database_Prefix, Database_Schema since this is variable and I have 20 of microservices i dont want to change hunders of up method prefixing all CreateTable functions with table name.

**Closed** 2022-10-16 19:12 UTC
Labels: closed-no-further-action, customer-reported
