### ISSUE TITLE
Artifacts of deleted columns remain after update from database

### ISSUE THREAD

**Issue by AbbottF** [dotnet/efcore#2051] opened 2015-04-22 19:43 UTC
A simple Linq to Sql query fails complaining about 6 Invalid Column names.

I had done an update from database.

The names are not in the DB table or in the context. They are from an old version of the table in a different DB that the project had previously referenced.

= I dropped and then re-added all the tables and can't find any references to the 6 fields in the context files. 
- I also deleted all the bins and objs before the build.
- I even dropped the emx and added a newly named emx.
  The issue did not go away.

I had to create a brand new EF context in a separate project and then use that in the original project before everything work,

If this can't be repaired quickly, it would be good to have an entry in the Wiki that describes where the artifacts exist and how to remove them.

Thanks
Abbott
.

**Comment by rowanmiller** [comment] 2015-05-15 22:43
__EF Team Triage:__ This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving. Following are a few questions to help us understand this bug report, for future issues please try to include this info in the initial report._


Could you share step by step instructions to reproduce the issue. Including scripts to create database schema etc.

**Comment by rowanmiller** [comment] 2015-05-15 22:43
Because this issue relates to EF6 I'm closing it out here because EF6 is maintained on CodePlex http://entityframework.codeplex.com/. Please open a new issue there with the requested details.

**Closed** 2022-10-16 08:55 UTC
