### ISSUE TITLE
GroupBy couldn't be translated and will be evaluated locally

### ISSUE THREAD

**Issue by MNie** [dotnet/efcore#14384] opened 2019-01-11 10:27 UTC
I have a query with two where's, count and groupby. I enable warnings as an errors so right now I get an error (below) that says that `GroupBy` is evaluated locally. I try to remove where clauses and count but the error still occurs. There is some option to run it not locally or it is a bug in EFCore? Property on which I grouped is defined as an integer.

```
Exception message:
Stack trace:

System.InvalidOperationException: Error generated for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'GroupBy(Convert([x.SomeElem]?.Id, Int32), [x])' could not be translated and will be evaluated locally.'. This exception can be suppressed or logged by passing event ID 'RelationalEventId.QueryClientEvaluationWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
  at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, TParam arg, Exception exception)
  at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.QueryClientEvaluationWarning(IDiagnosticsLogger`1 diagnostics, QueryModel queryModel, Object queryModelElement)
  at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
  at Remotion.Linq.Clauses.ResultOperatorBase.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
  at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
  at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
  at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
  at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
  at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.LiftSubQuery(IQuerySource querySource, SubQueryExpression subQueryExpression)
  at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.CompileMainFromClauseExpression(MainFromClause mainFromClause, QueryModel queryModel)
  at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
  at Remotion.Linq.Clauses.MainFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
  at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
  at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
  at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
  at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
  at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
  at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
  at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
  at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
  at Spotio.SearchDB.Context.Repository.SpotioSearchDBRepository.GetPerformanceConversionN(String companyId, Int32[] userIds, Int32[] territoryIds, Boolean territoryFilter, Int32 currentUserId, Nullable`1 startDate, Nullable`1 endDate) in D:\git\Spotio2\backend-dotnet\Spotio.Search.DB.Context\Repository\SpotioSearchDBRepository.cs:line 1251
```

### Steps to reproduce
```csharp
var result = await _dbContext
                .SomeA.AsNoTracking()
                .Where(somePredicateFunction)
                .Where(x => x.SomeElem != null 
                   && x.Id1 == id1 
                   && startDate <= x.CreatedAt 
                   && endDate >= x.CreatedAt 
                   && x.Type == Type.Create 
                   && (!userIds.Any() || userIds.Contains(x.OwnerId))
            )
            .GroupBy(o => o.SomeElem.Id )
            .Select(x => new { Key = x.Key, Count = x.Count() })
            .ToDictionaryAsync( k => k.Key, v => v.Count);
```

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 PRO
IDE: JetBrains Rider 2018.3

**Comment by smitpatel** [comment] 2019-01-11 20:00
Duplicate of #12089

**Closed** 2022-10-16 13:47 UTC
Labels: closed-duplicate, customer-reported
