### ISSUE TITLE
Relational: 2nd Level Caching using a cache server like Redis

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/efcore#6041] opened 2016-07-11 15:26 UTC
Availability of 2nd level caching in a cache server such as Redis can be a really nice feature with EF. 
Availability of Cache invalidation strategies within the framework will help more.

Thanks

**Comment by gdoron** [comment] 2016-07-12 23:25
I'll be very happy to get rid of my code I copy - paste from project to project and use a built in tool.

**Comment by rowanmiller** [comment] 2016-07-18 23:01
Duplicate of https://github.com/aspnet/EntityFramework/issues/5858

**Closed** 2022-10-16 09:50 UTC
