### ISSUE TITLE
CREATE FILE encountered operating system error 5(Access is denied)

### ISSUE THREAD

**Issue by ArchwayEon** [dotnet/efcore#11329] opened 2018-03-19 18:45 UTC
During update-database in the Package Manager Console, the creation of the mdf file is failing because the path string does not include a slash. See the included image. Instead of writing the mdf file to C:\Users\Parkers\Lab10Db.mdf it tries to write to C:\Users\ParkersLab10Db.mdf

### Steps to reproduce
I'm an instructor and I have my students create a database using the code first approach. It does not happen for all students and it happens after they issue the update-database command. I was not able to isolate the conditions for the selected few.

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.4

![error](https://user-images.githubusercontent.com/37549850/37615406-a0f36f72-2b83-11e8-9812-ecdd7025683e.jpg)

**Comment by pmiddleton** [comment] 2018-03-19 21:42
I have run into this issue myself.  There is a bug in the localdb version of Sql Server 2017 in which it fails to put the final slash between the file path and database name.

You can read more here - https://dba.stackexchange.com/questions/191393/localdb-v14-creates-wrong-path-for-mdf-files

Can you have the students with the issue manually create the database?

**Comment by ArchwayEon** [comment] 2018-03-19 21:54
Thanks for the stack exchange.

The workaround I use for those students is to manually add AttachDbFilename=<path> into the connection string.

**Comment by pmiddleton** [comment] 2018-03-19 21:54
That works too :)

**Comment by ajcvickers** [comment] 2018-03-22 02:40
Duplicate of https://github.com/aspnet/EntityFramework6/issues/384

**Comment by damsalem** [comment] 2018-12-21 19:55
I was following this guide exactly https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/creating-an-entity-framework-data-model-for-an-asp-net-mvc-application and it said to use: `<add name="SchoolContext" connectionString="Data Source=(LocalDb)\MSSQLLocalDB;Initial Catalog=ContosoUniversity1;Integrated Security=SSPI;" providerName="System.Data.SqlClient"/>`

I used `AttachDbFileName=` in this way: `<add name="SchoolContext" connectionString="Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\TheTechAcademy1.mdf;Initial Catalog=TheTechAcademy1;Integrated Security=SSPI;" providerName="System.Data.SqlClient"/>`

That solved the problem for me.

**Comment by yoadwo** [comment] 2019-05-11 15:44
> I was following this guide exactly https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/creating-an-entity-framework-data-model-for-an-asp-net-mvc-application
> 
> It said to use: `<add name="SchoolContext" connectionString="Data Source=(LocalDb)\MSSQLLocalDB;Initial Catalog=ContosoUniversity1;Integrated Security=SSPI;" providerName="System.Data.SqlClient"/>`
> 
> Following the comments here, I used `AttachDbFileName=` in this way: `<add name="SchoolContext" connectionString="Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\TheTechAcademy1.mdf;Initial Catalog=TheTechAcademy1;Integrated Security=SSPI;" providerName="System.Data.SqlClient"/>`
> 
> That solved the problem for me.
> 
> My reference for this structure was this article: https://docs.microsoft.com/en-us/previous-versions/aspnet/jj653752(v=vs.110)#localdb-connection-string-example

hey. actually, i had the same problem, with a "reversed" solution. following [this tutorial by okta](https://developer.okta.com/blog/2018/09/07/build-simple-crud-with-aspnet-webapi-vue) i had encountered migration problems. except, their tutorials connection string was this:

      `connectionString="Data Source=(LocalDb)\MSSQLLocalDB;Initial Catalog=WeightTracker;Integrated Security=SSPI;AttachDBFilename=|DataDirectory|\WeightTracker.mdf"`

it is only when I **removed** the `AttachDBFileName` attribute, was when I got rid of of the said OS error 5. I wish I had an explanation for it, but at least it's working. may it help more ppl :)

**Closed** 2022-10-16 12:14 UTC
Labels: closed-duplicate
