### ISSUE TITLE
Nested select can't use IEqualityComparer

### ISSUE THREAD

**Issue by grosch** [dotnet/efcore#18608] opened 2019-10-26 17:58 UTC
Trying to implement an IEqualityComparer<T> on a nested select throws an exception.  The nested select it return TONS of duplicate rows, and so there has to be some way to get just distinct values there.

The error points me to the client vs server evaluation page, but that's not providing me any information on how I'd actually solve this common issue.

### Steps to reproduce

``` C#
from foo in ...
join bar in ...
select new DTO {
    EntitlementNames = (from b in _context.BadgeReaderData.AsNoTracking()
                        join m in _context.BadgeReaderMapping on b.ReaderId equals m.BadgeReaderId
                        join e in _context.BadgeReaderEntitlement on b.EntitlementId equals e.Id
                        where b.LabSpaceId == s.Id && e.Exclude == false
                        orderby m.BadgeName, e.Name
                        select new ApmEntitlementDto {
                            BadgeReaderName = m.BadgeName,
                            EntitlementName = e.Name,
                            EntitlementId = e.Id
                        }).Distinct(new ApmEntitlementEqualityComparer()),
```

Here's the comparer:

``` C#
internal class ApmEntitlementEqualityComparer : IEqualityComparer<ApmEntitlementDto>
{
    public bool Equals([AllowNull] ApmEntitlementDto x, [AllowNull] ApmEntitlementDto y)
    {
        if (x == null && y == null)
            return true;
        else if (x == null || y == null)
            return false;
        else
            return x.EntitlementId == y.EntitlementId;
    }

    public int GetHashCode([DisallowNull] ApmEntitlementDto obj)
    {
        return obj.EntitlementId.GetHashCode();
    }
}
```

### Exception

> InvalidOperationException: Processing of the LINQ expression 'Distinct<ApmEntitlementDto>(
source: Select<<>f__AnonymousType27<<>f__AnonymousType26<BadgeReaderData, BadgeReaderMapping>, BadgeReaderEntitlement>, ApmEntitlementDto>(
source: ThenBy<<>f__AnonymousType27<<>f__AnonymousType26<BadgeReaderData, BadgeReaderMapping>, BadgeReaderEntitlement>, string>(
source: OrderBy<<>f__AnonymousType27<<>f__AnonymousType26<BadgeReaderData, BadgeReaderMapping>, BadgeReaderEntitlement>, string>(
source: Where<<>f__AnonymousType27<<>f__AnonymousType26<BadgeReaderData, BadgeReaderMapping>, BadgeReaderEntitlement>>(
source: Join<<>f__AnonymousType26<BadgeReaderData, BadgeReaderMapping>, BadgeReaderEntitlement, int, <>f__AnonymousType27<<>f__AnonymousType26<BadgeReaderData, BadgeReaderMapping>, BadgeReaderEntitlement>>(
outer: Join<BadgeReaderData, BadgeReaderMapping, int, <>f__AnonymousType26<BadgeReaderData, BadgeReaderMapping>>(
outer: DbSet<BadgeReaderData>,
inner: DbSet<BadgeReaderMapping>,
outerKeySelector: (b) => b.ReaderId,
innerKeySelector: (m) => m.BadgeReaderId,
resultSelector: (b, m) => new {
b = b,
m = m
}),
inner: DbSet<BadgeReaderEntitlement>,
outerKeySelector: (<>h__TransparentIdentifier0) => <>h__TransparentIdentifier0.b.EntitlementId,
innerKeySelector: (e) => e.Id,
resultSelector: (<>h__TransparentIdentifier0, e) => new {
<>h__TransparentIdentifier0 = <>h__TransparentIdentifier0,
e = e
}),
predicate: (<>h__TransparentIdentifier1) => <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.b.LabSpaceId == NavigationTreeExpression
Value: EntityReferenceLabSpace
Expression: (Unhandled parameter: ti4).Outer.Outer.Outer.Outer.Outer.Outer.Outer.Id && <>h__TransparentIdentifier1.e.Exclude == False),
keySelector: (<>h__TransparentIdentifier1) => <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.m.BadgeName),
keySelector: (<>h__TransparentIdentifier1) => <>h__TransparentIdentifier1.e.Name),
selector: (<>h__TransparentIdentifier1) => new ApmEntitlementDto{
BadgeReaderName = <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.m.BadgeName,
EntitlementName = <>h__TransparentIdentifier1.e.Name,
EntitlementId = <>h__TransparentIdentifier1.e.Id
}
),
comparer: new ApmEntitlementEqualityComparer())' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)

### Further technical details

EF Core version: 3.1.0-preview1.19506.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.6

**Comment by grosch** [comment] 2019-10-28 21:46
@ajcvickers That makes sense.  Can you point at any specific solutions though so that I'm not pulling down thousands of duplicate rows?

**Comment by ajcvickers** [comment] 2019-10-28 22:08
@grosch I don't know of any way to implement a custom distinct operation in SQL. Is there some specific SQL that you are expecting to be generated?

**Comment by grosch** [comment] 2019-10-29 15:23
I just want DISTINCT in there.  So instead of generating this:

``` SQL
SELECT m.BadgeName BadgeReaderName, e.Name, EntitlementName, e.Id EntitlementId
FROM BadgeReaderData b
JOIN BadgeReaderMapping on b.ReaderId = m.BadgeReaderId
JOIN BadgeReaderEntitlement on b.EntitlementId = e.Id
WHERE b.labSpaceId = s.Id AND e.Exclude = 0
ORDER BY m.BadgeName, e.Name
```

I want you to generate this:

``` SQL
SELECT DISTINCT m.BadgeName BadgeReaderName, e.Name, EntitlementName, e.Id EntitlementId
FROM BadgeReaderData b
JOIN BadgeReaderMapping on b.ReaderId = m.BadgeReaderId
JOIN BadgeReaderEntitlement on b.EntitlementId = e.Id
WHERE b.labSpaceId = s.Id AND e.Exclude = 0
ORDER BY m.BadgeName, e.Name
```

**Comment by ajcvickers** [comment] 2019-10-29 17:47
@grosch What do you get if you use, `.Distinct()` in your query instead of `.Distinct(new ApmEntitlementEqualityComparer())`?

**Comment by grosch** [comment] 2019-10-29 19:56
There's no error then of course, but I have hundreds of duplicated entries in my output.

**Comment by ajcvickers** [comment] 2019-10-29 21:19
@grosch What SQL is generated?

**Comment by grosch** [comment] 2019-10-30 23:08
Sorry I'm struggling to figure out exactly how to enable this logging in EF Core 3.

**Comment by grosch** [comment] 2019-10-30 23:24
@ajcvickers Finally figured out how to do logging now :)

This is what I'm seeing for that part of the query.

This one is first:

```sql
    LEFT JOIN Projection Mapping:
    (
        SELECT DISTINCT b0.BadgeName, b1.Name, b1.id, b.AccessDt, b.EntitlementId, b.ReaderId, b.Lab_Space_Id, b0.BadgeReaderID, b0.LabSpaceID
        FROM Badge_Reader_Data AS b
        INNER JOIN Badge_Reader_Mapping AS b0 ON b.ReaderId == b0.BadgeReaderID
        INNER JOIN Badge_Reader_Entitlement AS b1 ON b.EntitlementId == b1.id
        WHERE b1.Exclude == CAST(0 AS bit)
    ) AS t0 ON l.id == t0.Lab_Space_Id
```

and this one shows afterwards.

``` sql
LEFT JOIN (
    SELECT DISTINCT [b0].[BadgeName], [b1].[Name], [b1].[id], [b].[AccessDt], [b].[EntitlementId], [b].[ReaderId], [b].[Lab_Space_Id], [b0].[BadgeReaderID], [b0].[LabSpaceID]
    FROM [Badge_Reader_Data] AS [b]
    INNER JOIN [Badge_Reader_Mapping] AS [b0] ON [b].[ReaderId] = [b0].[BadgeReaderID]
    INNER JOIN [Badge_Reader_Entitlement] AS [b1] ON [b].[EntitlementId] = [b1].[id]
    WHERE [b1].[Exclude] = CAST(0 AS BIT)
) AS [t0] ON [l].[id] = [t0].[Lab_Space_Id]
```

So, while the individual subquery seems to be including the distinct, it appears that being wrapped in a `LEFT JOIN` might be what's adding the duplicates?

**Comment by grosch** [comment] 2019-10-30 23:57
@ajcvickers OK, this helps identify the problem.  I greatly simplified the query trying to track down why there's extra data.  I now have this code

``` csharp
var query = from s in _context.LabSpace
            where s.Id == 1036558
            select new LabDto {
                EntitlementNames = (from b in _context.BadgeReaderData.AsNoTracking()
                                    join m in _context.BadgeReaderMapping on b.ReaderId equals m.BadgeReaderId
                                    join e in _context.BadgeReaderEntitlement on b.EntitlementId equals e.Id
                                    where b.LabSpaceId == s.Id && e.Exclude == false
                                    orderby m.BadgeName, e.Name
                                    select new ApmEntitlementDto {
                                        BadgeReaderName = m.BadgeName,
                                        EntitlementName = e.Name,
                                        EntitlementId = e.Id
                                    }).Distinct()
            };
```

And the logged query is like so:

``` sql
SELECT [l].[id], [t].[BadgeName], [t].[Name], [t].[id], [t].[AccessDt], [t].[EntitlementId], [t].[ReaderId], [t].[Lab_Space_Id], [t].[BadgeReaderID], [t].[LabSpaceID]
FROM [Lab_Space] AS [l]
LEFT JOIN (
    SELECT DISTINCT [b0].[BadgeName], [b1].[Name], [b1].[id], [b].[AccessDt], [b].[EntitlementId], [b].[ReaderId], [b].[Lab_Space_Id], [b0].[BadgeReaderID], [b0].[LabSpaceID]
    FROM [Badge_Reader_Data] AS [b]
    INNER JOIN [Badge_Reader_Mapping] AS [b0] ON [b].[ReaderId] = [b0].[BadgeReaderID]
    INNER JOIN [Badge_Reader_Entitlement] AS [b1] ON [b].[EntitlementId] = [b1].[id]
    WHERE [b1].[Exclude] = CAST(0 AS bit)
) AS [t] ON [l].[id] = [t].[Lab_Space_Id]
WHERE [l].[id] = 1036558
ORDER BY [l].[id], [t].[AccessDt], [t].[EntitlementId], [t].[ReaderId], [t].[Lab_Space_Id], [t].[BadgeReaderID], [t].[LabSpaceID], [t].[id]
```

You can see in the built SQL, it's asking for the `AccessDt` column, for example.  That is a column on the `Badge_Reader_Data` table, but I do *not* ask for that anywhere in my query.  As soon as you throw in the `AccessDt` column I suddenly gets tons of "duplicate" rows because all the rest of the data is the same, but there are hundreds of different access dates for the three columns I asked for.

Why are columns that exist on the table, but which I didn't ask to be involved in the query, getting put into the generated SQL?

**Comment by smitpatel** [comment] 2019-10-31 00:03
Related #15873
I believe this query cannot be translated to server. There is no correlation to figure out the collection grouping. I am not sure why it translated to incorrect result in first place. (I was expecting invalid SQL)

**Comment by grosch** [comment] 2019-10-31 00:17
@ajcvickers Looking at the `Badge_Reader_Data` table I see that the primary key is made up of 4 columns:  `AccessDt`, `EntitlementId`, `ReaderId`, `Lab_Space_Id`.  So that at least explains why you're throwing those columns in there.  I'll need to work with the DBA to see if I can get that changed.

**Comment by ajcvickers** [comment] 2019-11-01 18:54
Re-opening to discuss in triage.

**Comment by ajcvickers** [comment] 2019-11-08 18:06
@smitpatel to investigate.

**Comment by smitpatel** [comment] 2019-11-12 18:48
We project out PK properties so that we can identify when inner record changes. It is required to form groups on client side since nested select is projecting a collection. The only thing here would be to block translation of collection.Distinct() when inner does not project out correlation columns.

**Comment by smitpatel** [comment] 2019-11-12 18:50
This should be closed as by design since this query cannot be translated to server.

**Closed** 2022-10-16 14:52 UTC
Labels: closed-by-design, customer-reported
