### ISSUE TITLE
Regression in 5.0.8 for Microsoft.EntityFrameworkCore.Design and Microsoft.EntityFrameworkCore.Tools

### ISSUE THREAD

**Issue by msawczyn** [dotnet/efcore#25267] opened 2021-07-15 11:24 UTC
The issue described in https://github.com/dotnet/efcore/issues/16216 is present in v5.0.8. 

The workaround Bryce confirmed in that ticket is correct, and I had it working in 5.0.7 by editing PackageReference entries for `Microsoft.EntityFrameworkCore.Design` and `Microsoft.EntityFrameworkCore.Tools` in the project file. But the update to 5.0.8 restored  the problem and it had to be manually corrected again.

The TLDR recap:

```
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```
and
```
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```
should instead be
```
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.8" />
```
and
```
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.8" />
```

Thanks, team, for all your hard work.

**Comment by ErikEJ** [comment] 2021-07-15 11:35
@msawczyn that is actually by design!

**Comment by msawczyn** [comment] 2021-07-15 11:37
Aarg! Who would have thunk it? Thanks.

**Comment by ajcvickers** [comment] 2021-07-15 15:26
Duplicate of #11506

**Closed** 2022-10-16 19:39 UTC
Labels: customer-reported
