### ISSUE TITLE
InvalidOperationException when inserting array of data into database table

### ISSUE THREAD

**Issue by Jakemangan** [dotnet/efcore#13714] opened 2018-10-22 13:07 UTC
I have an `Instruction` class which contains a list of `Borrower` objects. I am trying to pass through an array of `Borrower` objects through a JSON string which can then be added into my database. However when I try and pass the JSON through this exception is raised. 

The above below is produced when I attempt to insert an array of data into an SQL server using Entity Framework.

Below is the JSON array that I am attempting to insert into the database, the array contains two elements and I believe the error is being caused by entity framework inserting the two array elements into the database with the same ID. If I remove one element from the array then the data is inserted as normal. The fact that a single element is inserted correctly also suggests that the problem is not with the data currently held inside the database.

```
Exception message: System.InvalidOperationException: 'The instance of entity type 'Borrower' cannot be tracked because another instance with the key value '{BorrowerId: -2147482647}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.'
Stack trace: https://gist.github.com/Jakemangan/e1c03d4ca2501141e72f81689cedc6eb


```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

JSON input: 

```json
{
  "instructionType": 2,
  "applicationId": 1,
  "dateLogged": "2018-10-17T09:22:00.421",
  "additionalInformation": {
    "furtherComments": "string"
  },
  "borrowerBank": null,
  "broker": {
    "address": {
      "houseNum": "string",
      "houseName": "string",
      "streetName": "string",
      "locality": "string",
      "town": "string",
      "county": "string",
      "postcode": "ne11en"
    },
    "companyName": "string",
    "brokerReference": "string",
    "email": "string@string.com"
  },
  "property": {
    "referenceNumber": "10000004",
    "caseOwner": "stg",
    "amountBorrowed": 10,
    "security": {
      "houseNum": "string",
      "houseName": "string",
      "streetName": "string",
      "locality": "string",
      "town": "string",
      "county": "string",
      "postcode": "ne11en"
    },
    "correspondence": {
      "houseNum": "string",
      "houseName": "string",
      "streetName": "string",
      "locality": "string",
      "town": "string",
      "county": "string",
      "postcode": "ne11en"
    },
    "occupier": [
      {
        "title": 1,
        "firstName": "string",
        "lastName": "string",
        "dob": "2018-10-17T09:22:00.422",
        "relationship": "string"
      }
    ],
    "tenure": 1,
    "jurisdiction": 1,
    "funder": 1
  },
  "solicitor": {
    "companyName": "string",
    "solicitorReference": "string",
    "address": {
      "houseNum": "string",
      "houseName": "string",
      "streetName": "string",
      "locality": "string",
      "town": "string",
      "county": "string",
      "postcode": "ne11en"
    }
  },
  "borrower": [
    {
      "address": {
        "houseNum": "string",
        "houseName": "string",
        "streetName": "string",
        "locality": "string",
        "town": "string",
        "county": "string",
        "postcode": "NE11NE"
      },
      "title": 1,
      "firstName": "string",
      "lastName": "string",
      "dob": "2018-10-17T09:22:00.422",
      "homeNumber": "01212122222",
      "workNumber": "01212122222",
      "mobileNumber": "01212122222",
      "email": "borrower@borrower.com"
    },
	{
      "address": {
        "houseNum": "string",
        "houseName": "string",
        "streetName": "string",
        "locality": "string",
        "town": "string",
        "county": "string",
        "postcode": "NE11NE"
      },
      "title": 1,
      "firstName": "string",
      "lastName": "string",
      "dob": "2018-10-17T09:22:00.422",
      "homeNumber": "01212122222",
      "workNumber": "01212122222",
      "mobileNumber": "01212122222",
      "email": "borrower@borrower.com"
    }
  ],
  "currentLender": [
    {
      "name": "string",
      "currentLenderAccountNumber": "01234567",
      "estimatedAmount": 10000,
      "deedsLocation": "UNKNOWN"
    }
  ]
}
```

The methods being called in this situation are relatively simple and therefore should not be the source of the error, but I have included them below for clarity.

Send Instruction
```C#
    [HttpPost]
            public IActionResult SendInstruction([FromBody]SolicitorInstruction si)
            {
    			//Validate
    			ValidationController controller = new ValidationController();
    	        bool instructionIsValid = controller.ValidateInstruction(si);
    
    	        if (instructionIsValid)
    	        {
    		        _instructionRepo.CreateInstruction(si);
    		        Console.WriteLine("\nInstruction successfully inserted into database records.\n");
    				return Ok("Successfully added instruction into database.");
    			}
    
    			Console.WriteLine("\nInvalid Data: Insert into database records aborted.\n");
    	        return BadRequest(controller.ErrorMessages);
            }
```
Create Instruction
```C#
    public void CreateInstruction(SolicitorInstruction instruction)
    	    {
    			_context.SolicitorInstructions.Add(instruction);
    		    _context.SaveChanges();
    	    }
```
DbContext - Used to create the EF model.
```C#
    public class SolicitorContext : DbContext
    	{
    
    		public DbSet<AdditionalInformation> AdditionalInformations { get; set; }
    		public DbSet<Address> Addresses { get; set; }
    		public DbSet<Borrower> Borrowers { get; set; }
    		public DbSet<BorrowerBank> BorrowerBanks { get; set; }
    		public DbSet<Broker> Brokers { get; set; }
    		public DbSet<CurrentLender> CurrentLender { get; set; }
    		public DbSet<Occupier> Occupiers { get; set; }
    		public DbSet<Property> Properties { get; set; }
    		public DbSet<Solicitor> Solicitors { get; set; }
    		public DbSet<SolicitorInstruction> SolicitorInstructions { get; set; }
    
    		public SolicitorContext(DbContextOptions<SolicitorContext> options)
    			: base(options)
    		{
    
    		}
```
Instruction table

```C#
public class SolicitorInstruction
	{
		[Key]
		public int SolicitorInstructionId { get; set; }
		public InstructionTypes InstructionType { get; set; }
		public int ApplicationId { get; set; }
		public DateTime DateLogged { get; set; }
		[ForeignKey("AdditionalInformationId")]
		public AdditionalInformation AdditionalInformation { get; set; }
		[ForeignKey("BorrowerBankId")]
		public BorrowerBank BorrowerBank { get; set; }
		[ForeignKey("BrokerId")]
		public Broker Broker { get; set; }
		[ForeignKey("PropertyId")]
		public Property Property { get; set; }
		[ForeignKey("SolicitorId")]
		public Solicitor Solicitor { get; set; }
		[ForeignKey("BorrowerId")]
		public List<Borrower> Borrower { get; set; }
		[ForeignKey("CurrentLenderId")]
		public List<CurrentLender> CurrentLender { get; set; }
	}
```

Borrower table
```C#
    [Table("Borrower")]
        public partial class Borrower
    	{
    		[Key]
    		public int BorrowerId { get; set; }
    		[ForeignKey("AddressId")]
    		public Address Address { get; set; }
    		//public bool BorrowerAddressIsCorrespondenceAddress { get; set; }
    		public Honorifics Title { get; set; }
    		[StringLength(32)]
    		public string FirstName { get; set; }
    		[StringLength(32)]
    		public string LastName { get; set; }
    		public DateTime Dob { get; set; }
    		[StringLength(32)]
    		public string HomeNumber { get; set; }
    		[StringLength(32)]
    		public string WorkNumber { get; set; }
    		[StringLength(32)]
    		public string MobileNumber { get; set; }
    		[StringLength(64)]
    		public string Email { get; set; }
    	}
```
### Further technical details
EF Core version:  2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 2.1.4
Operating system: Win 10
IDE: Visual Studio 2017 15.8.6

**Comment by ajcvickers** [comment] 2018-10-22 22:44
@Jakemangan There is nothing here that looks obviously wrong, and the exception in that form is not something that rings any bells. I have been unable to reproduce what you are seeing. Can you post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by ajcvickers** [comment] 2018-10-29 17:46
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:36 UTC
Labels: closed-could-not-reproduce, customer-reported
