### ISSUE TITLE
Customize column selection in relations in query builder

### ISSUE THREAD

**Issue by rezathecoder** [dotnet/efcore#21251] opened 2020-06-13 11:44 UTC
Hi everyone.
The feature that i'm looking for is a feature that probably all of efcore users will need and its very common and well implemented in most ORMs.
We need to filter and customize the columns of the relation we are including.
the only solution available for this is to write nested Linq expressions but it gets so complicated that most of the time we choose to include all the columns which is not performant.
Another issue here is that when using nested expression we have to mention all the columns from the main entity to be included in the result.

suppose we have the ApplicationUser as below:

```c#
public class ApplicationUser {
    public int Id {get; set;}
    public string FirstName {get; set;}
    public string LastName {get; set;}
    public string Username {get; set; }
    public int AddressId {get; set;}
    public Address Address {get; set;}
...
}
```

and we have Address class like this:

```c#
public class Address {
    public int Id {get; set;}
    public string City {get; set;}
    public string Avenue {get; set;}
    public string ZipCode {get; set;}
   ...
}
```

if i only need the city in some cases i have to do this:

```c#
await _context.Users.Select(u => new ApplicationUser {
    FirstName = u.FirstName,
    LastName = u.LastName ,
    Username = u.Username,
    AddressId = u.AddressId,
    Address = _context.Addresses.Where(a => a.Id == u.AddressId).Select(a => new Address {City = a.City}).FirstOrDefault()
}).ToListAsync();
```

this is a really simple example. what if the ApplicationUser had 50 fields ? what if instead of Address we have another relation that has another 50 fields and we only need 2 of them ?

Well you might say using an anonymous type is the solution but most of the times we need the strongly typed object to work with. (Probably send it to a razor view)

My suggestion is that add another overload for Include() and ThenInclude() methods to accept a list of desired columns. This can be done in a couple of ways. for example accepting an array of strings as the name of the fields to be selected. (We will use nameof() operator to avoid typos and ...)

If you look at the queries generated by efcore in your log, you will notice that even if you select entire entity, the select statement will generate list of all fields to be selected from database. Here we can apply the filtering and instead of generating the full list of columns, only generate the list of desired columns.

example:

```c#
await _context.Users.Include(u => u.Address, new string[] { nameof(Address.City) }).ToListAsync();
```
as you can see this much more simpler and cleaner and you'll get the performance you are looking for.

This technique could also be implemented for the main entity. That way we dont need to pass lamda expression to Select() method to filter the columns.

**Comment by AndriySvyryd** [comment] 2020-06-13 15:43
Duplicate of https://github.com/dotnet/efcore/issues/1387

**Closed** 2022-10-16 18:29 UTC
Labels: closed-duplicate, customer-reported
