### ISSUE TITLE
How to Increase the Size of VARCHAR results of OPENJSON in EF Core 8 Contains Query

### ISSUE THREAD

**Issue by sirhcybe** [dotnet/efcore#32913] opened 2024-01-24 21:07 UTC
I just updated to EF Core 8 and this query is not working:
```
//types contains a list of strings formatted like "<type>-<subtype>"
public async Task<IEnumerable<MyObject>> GetMyObjects(IEnumerable<string> types)
{
    using var _context = _contextFactory.CreateDbContext();
    return await _context.MyObject
        .Where(types.Contains((x.Type + "-" + x.SubType)))
        .ToListAsync();
}
```
This is getting translated into a query like this:

```
SELECT [p].[Id], [p].[Name], [p].[Type], [p].[SubType]
FROM [Hpms].[MyObject] AS [p]
WHERE [p].[Type] + '-' + COALESCE([p].[SubType], '') IN (
    SELECT [s].[value]
    FROM OPENJSON('["Long Type and Long Type and Long Type-SubType1","Long Type and Long Type and Long Type-SubType2","Long Type and Long Type and Long Type-SubType3","Long Type and Long Type and Long Type-SubType4","Long Type and Long Type and Long Type-Traffic","Type2"]') WITH ([value] varchar(30) '$') AS [s]
)
```
The problem with this is that my "Long Type and Long Type and Long Type-SubType1" type strings are more than 30 characters and are getting truncated and my query isn't returning the correct results. How do I increase the length of the varchar(30) typing?

EF Core version: 8.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
IDE: Visual Studio 2022 17.8.5

**Comment by roji** [comment] 2024-01-24 21:47
Duplicate of #32735

**Closed** 2024-01-25 18:07 UTC
Labels: customer-reported
