### ISSUE TITLE
Support For Ef Core 6 Free Text

### ISSUE THREAD

**Issue by akdemirsafak** [dotnet/efcore#31530] opened 2023-08-22 09:13 UTC
## How to I can use FreeText? 

I'm using Entity Framework 6 Code First SqlServer Database and wanna use FreeText but doesn't working.  Need apply some configs ?

`_dbContext.Products.Where(x=>EF.Functions.FreeText(x.Name,request.SearchText).ToList(); ` **-> Doesnt working.**
`_dbContext.Products.Where(x=>x.Name.Contains(request.SearchText).ToList(); ` **->Working.**

Entity :
![entity](https://github.com/dotnet/efcore/assets/58888062/500c896c-ba2f-4cce-b4db-7a62aa0a4b22)

DbContext :

![newDbContext](https://github.com/dotnet/efcore/assets/58888062/4af2349d-a16e-471c-8e83-a573fa22531f)

Repository :
![Repository](https://github.com/dotnet/efcore/assets/58888062/3f1935aa-f025-41ea-ac0b-8b207743b1cb)

Error :

![Ekran görüntüsü 2023-08-22 133845](https://github.com/dotnet/efcore/assets/58888062/65699400-42dc-453f-bcca-f9fe9d469ba4)

**Comment by ajcvickers** [comment] 2023-08-22 09:53
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by akdemirsafak** [comment] 2023-08-22 10:24
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

I added extra information, maybe better now.

**Comment by roji** [comment] 2023-08-23 14:37
@akdemirsafak the above doesn't contain the actual exception and stack trace you're getting from EF (a screenshot showing an HTTP 500 error isn't enough).

**Comment by bricelam** [comment] 2023-08-28 21:36
See [SQL Server Full-Text Search and EF Core](https://www.bricelam.net/2020/08/08/mssql-freetext-and-efcore.html) for the basics.

**Comment by ajcvickers** [comment] 2023-09-06 18:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-09-06 18:51 UTC
Labels: customer-reported
