### ISSUE TITLE
Database hits when caching

### ISSUE THREAD

**Issue by ebudimlic** [dotnet/efcore#9890] opened 2017-09-23 20:56 UTC
While running the same query in a loop, within the same database context, I get cached values from the first instance of query materialization which is as expected.  However, I was running an Sql Profiler at the same time and observed that the query is actually executed every time against the sql server database. These database hits are needless excess as I proved to myself by updating affected row from outside the db context and verifying that cached data did not change.
I believe that you could save countless hits to the database for all EF users by not hitting the database after the data is cached.

### Steps to reproduce
1) Open Sql Server Management Studio (SSMS)
2) Open "Create database script.sql" part and execute it in SSMS
3) Click on Tools-->Sql Profiler, connect to 'localhost' db server and Run the trace
4) Run the program attached to this ticket (ExcessDbHits)
5) Stop the Sql Profiler and examine its trace to confirm that database query was executed 5 times even though EF returns a cached value.

[ExcessDbHits.zip](https://github.com/aspnet/EntityFrameworkCore/files/1326853/ExcessDbHits.zip)

### Further technical details
EF Core version: <package id="EntityFramework" version="6.1.3" targetFramework="net461" />
Sql Server: 2012
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by divega** [comment] 2017-09-23 23:14
This seems to be a duplicate of #1948.

**Comment by divega** [comment] 2017-09-23 23:23
@ebudimlic also, BTW, I think one possible reason we don't get this request more often is because we already have the `Find` which you can use as a replacement for simple queries for a single entity by key, and which already looks first in the cache.

**Comment by ajcvickers** [comment] 2017-09-25 19:49
Duplicate of #1948

**Closed** 2022-10-16 11:51 UTC
Labels: closed-duplicate
