### ISSUE TITLE
Filtering (Where/First) on an enum property with a ValueConversion does not work (2.1-preview1)

### ISSUE THREAD

**Issue by GWigWam** [dotnet/efcore#11211] opened 2018-03-09 13:29 UTC
I have an enum property defined on an entity which uses a custom value conversion (`.HasConversion`) to be mapped to a string (`nvarchar(20)`) column in MSSQL. When I use this property in a `.Where` or `.First` linq query an exception is thrown: `Conversion failed when converting the nvarchar value 'Value2' to data type int.`

##### Type definition
```c#
//Very basic type definition
public class Entity {
    public Guid Id { get; set; }
    public MyEnum EnumCol { get; set; }
}
public enum MyEnum {
    Value1, Value2
}
```

##### In DbContext class
```c#
public DbSet<Entity> Entities { get; set; }

// Configuring the conversion
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);

    modelBuilder.Entity<Entity>()
        .Property(e => e.EnumCol)
        .HasColumnType("nvarchar(20)")
        .HasConversion(
            convertToStoreExpression: e => e.ToString(),
            convertFromStoreExpression: s => (MyEnum)Enum.Parse(typeof(MyEnum), s));
}
```

##### In `void Main()`
This query causes the exception:
`myContext.Entities.Where(e => e.EnumCol == MyEnum.Value2).ToArray();`

It is converted to the following SQL, it seems the conversion is ignored and the default enum handling is used, the `WHERE` is based on an `int` but should be a `string`:

```SQL
SELECT [e].[Id], [e].[EnumCol]
FROM [Entities] AS [e]
WHERE [e].[EnumCol] = 1
```

Full exception:
```
System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting the nvarchar value 'Value2' to data type int.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Read()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at TestEFCore_2._1_ValueConversions.Program.Main(String[] args) in C:\DotNet\WSB_Git\Misc\TestEFCore_2.1_ValueConversions\TestEFCore_2.1_ValueConversions\Program.cs:line 24
ClientConnectionId:2b5b4781-e93d-4a73-b44d-56651bc482bb
Error Number:245,State:1,Class:16
```

When I get the entities without using `.Where` (e.g. `myContext.Entities.Take(1).ToArray()`) everything works as expected.

The [docs.microsoft](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions#limitations) entry does not mention filtering like this as a limitation so I assume this should be possible?

### Further technical details
EF Core version: `2.1.0-preview1-final`
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 x64
IDE: Visual Studio 2017 15.5

**Comment by smitpatel** [comment] 2018-03-09 15:57
Duplicate of #11127

**Closed** 2022-10-16 12:13 UTC
Labels: closed-duplicate
