### ISSUE TITLE
.NET Native: LINQ query of nullable Enum type throws ArgumentException

### ISSUE THREAD

**Issue by Jobria** [dotnet/efcore#6537] opened 2016-09-15 10:13 UTC
### Steps to reproduce
1. Create an UWP project.
2. Create Entity like the following.

> ```
> public enum PostType { New, Reply };
> 
> public class Blog
> {
>     public Guid? ID { get; set; }
> 
>     public string Url { get; set; }
> 
>     public string Name { get; set; }
> 
>     public List<Post> Posts { get; set; }
> }
> 
> public class Post
> {
>     public Guid? ID { get; set; }
> 
>     public string Title { get; set; }
> 
>     public string Content { get; set; }
> 
>     public PostType? Type { get; set; }
> 
>     public Guid? BlogID { get; set; }
> 
>     public Blog Blog { get; set; }
> }
> ```
> 1. Create DBContext  as following
>    public class BloggingContext : DbContext
>    {
>        public DbSet<Blog> Blogs { get; set; }
>        public DbSet<Post> Posts { get; set; }
>    
>    ```
>    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
>    {
>        optionsBuilder.UseSqlite("Filename=./blog.db");
>    }
>    ```
>    
>    }
1. Create Migration as following

> [DbContext(typeof(BloggingContext))]
>     [Migration("1.0.0")]
>     public class Migration100 : Migration
>     {
>         protected override void Up(MigrationBuilder migrationBuilder)
>         {
>             migrationBuilder.CreateTable("Blogs",
>             table => new
>             {
>                 ID = table.Column<Guid>(nullable: false),
>                 Url = table.Column<string>(nullable: true),
>                 Name = table.Column<string>(nullable: true),
>             },
>             constraints: table => table.PrimaryKey("PK_Blog", x => x.ID));
> 
> ```
>         migrationBuilder.CreateTable("Posts",
>         table => new
>         {
>             ID = table.Column<Guid>(nullable: false),
>             Title = table.Column<string>(nullable: true),
>             Content = table.Column<string>(nullable: true),
>             Type = table.Column<int>(nullable: true),
>             BlogID = table.Column<Guid>(nullable: true),
>         },
>         constraints:
>         table =>
>         {
>             table.PrimaryKey("PK_Post", x => x.ID);
>             table.ForeignKey("FK_Post_BlogID", x => x.BlogID, "Blogs", "ID");
>         });
>     }
> 
>     protected override void Down(MigrationBuilder migrationBuilder)
>     {
>         migrationBuilder.DropTable("Posts");
>         migrationBuilder.DropTable("Blogs");
>     }
> }
> ```
1. Edit the MainPage XAML as following

> ```
> <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
>     <StackPanel>
>         <TextBox Name="NewBlogUrl"></TextBox>
>         <Button Name="AddButton">Add</Button>
>         <ListView Name="Blogs">
>             <ListView.ItemTemplate>
>                 <DataTemplate>
>                     <TextBlock Text="{Binding Url}" />
>                 </DataTemplate>
>             </ListView.ItemTemplate>
>         </ListView>
>     </StackPanel>
> </Grid>
> ```

6.Edit the MainPage code in constructor as following

> public MainPage()
>         {
>             this.InitializeComponent();
> 
> ```
>         this.Loaded += (sender, args) =>
>         {
>             using (var db = new BloggingContext())
>             {
>                 var data = (from blog in db.Blogs
>                             join post in db.Posts on blog.ID equals post.BlogID
>                             where post.Type == PostType.New
>                             select blog).ToArray();
> 
>                 Blogs.ItemsSource = data;
>             }
>         };
> 
>         this.AddButton.Click += (sender, args) =>
>         {
>             using (var db = new BloggingContext())
>             {
>                 var blog = new Blog { ID = Guid.NewGuid(), Url = NewBlogUrl.Text, Posts = new List<Post>() };
>                 blog.Posts.Add(new Post() { ID = Guid.NewGuid(), Type = PostType.New, BlogID = blog.ID });
>                 blog.Posts.Add(new Post() { ID = Guid.NewGuid(), Type = PostType.Reply, BlogID = blog.ID });
> 
>                 db.Blogs.Add(blog);
> 
>                 foreach (var post in blog.Posts)
>                 {
>                     db.Posts.Add(post);
>                 }
> 
>                 db.SaveChanges();
> 
>                 Blogs.ItemsSource = db.Blogs.ToList();
>             }
> 
>             this.NewBlogUrl.Text = string.Empty;
>         };
>     }
> ```
### The issue

after added few records and then restart the app in release mode, the linq query for the data with the criteria of Nullable PostType. However, it works as Debug mode. If I change the PostType as non-nullable type, it works both debug and release mode. I have no idea what I did wrong.

If you are seeing an exception, include the full exceptions details (message and stack trace).
Since it only trigger on release mode, I can only get the exception from output windows like the following.

Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
Exception thrown: 'System.ArgumentException' in Microsoft.EntityFrameworkCore.dll
Unhandled exception at 0x06F57D38 (Windows.UI.Xaml.dll) in App9.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x0DE13ED0, 0x00000002).

```
Exception message:
Stack trace:
```
### Further technical details

EF Core version: 1.0.1
Operating system: Win10 Pro 14393
Visual Studio version: (e.g. VS 2013 or n/a) VS 2005 Enterpise

Other details about my project setup:
  "dependencies": {
    "Microsoft.Data.SQLite": "1.0.0",
    "Microsoft.EntityFrameworkCore": "1.0.1",
    "Microsoft.EntityFrameworkCore.Relational": "1.0.1",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.1",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
    "System.ComponentModel.Annotations": "4.1.0",
    "System.IO.FileSystem.Primitives": "4.0.1",
    "System.Threading.Overlapped": "4.0.1"

**Comment by MattWhilden** [comment] 2016-10-18 03:36
Hmm. Sorry to hear it's giving you trouble. We've had a number of issues with the .NET Native optimizer not correctly handling cases with Nullable<T>. One way to see if that's the issue is to enable .NET Native in the DEBUG configuration and see if the issue reproduces. This mode skips almost all of the optimizer so is pretty good for helping us know where issues lie.

- Switch to DEBUG
- Enable .NET Native (Project Properties > BUILD > Enable .NET Native)
- Rerun your scenario... does it repro?

I have some other tools/tricks but this is a good first triage.

**Comment by AndriySvyryd** [comment] 2017-08-15 19:47
Verified that this is fixed in the prerelease builds of EF 2.0.1 and UWP 6.0.0

**Closed** 2022-10-16 09:57 UTC
Labels: closed-external, area-external
