### ISSUE TITLE
Should we deprecate the InMemory provider?

### ISSUE THREAD

**Issue by KennethHoff** [dotnet/efcore#31335] opened 2023-07-22 18:19 UTC
The InMemory provider has exceedingly few good use-cases, but causes a lot of noise on GitHub. New features rarely get added to it, and it's not recommended for testing (which is the main reason it's currently being used I'm imagining) because it's not actually representative to the production environment.

Deprecate the InMemory provider. Recommend using e.g. SQLite as an equivalent playground-provider.

**Comment by roji** [comment] 2023-07-22 20:08
Duplicate of #18457

**Comment by roji** [comment] 2023-07-22 20:12
While the team generally agrees with your point of view, we raised this in #18457 and there seem to be too many users who depend on it for their testing. It's true that for a restricted set of query types (no transactions, no SQL, no need for case-insensitive behavior...) in-memory can work, even though I agree that it creates more potential for trouble than it's worth.

We've put warnings and explain the problems in our docs, but at this point I don't think there's anything more we can do. On the positive side, we also generally invest very little time in the in-memory provider, so at least it doesn't come at the expense of other more important work.

> Recommend using e.g. SQLite as an equivalent playground-provider.

I wouldn't really recommend this for some of the same reason in-memory is problematic: it doesn't match the query behavior of your real database (even though it's closer than in-memory). Either test against your production database type or use a mockable repository pattern for true unit testing.

**Comment by KennethHoff** [comment] 2023-07-22 20:30
What I meant by "playground-provider" was for those making one-off projects for testing out EF syntax or whatever, not integration testing for their actual production software.

I can understand the confusion however.

**Comment by KennethHoff** [comment] 2023-07-22 20:30
What I meant by "playground-provider" was for those making one-off projects for testing out EF syntax or whatever, not integration testing for their actual production software.

I can understand the confusion however.

**Closed** 2023-07-26 19:51 UTC
Labels: closed-duplicate, customer-reported
