### ISSUE TITLE
2.2 Preview 3 Filter Dates - Null Reference Exception

### ISSUE THREAD

**Issue by aherrick** [dotnet/efcore#13688] opened 2018-10-19 15:06 UTC
In 2.2 Preview 2 I could filter dates similar to the following:

```
       var data = from vb in qry
                   where !vb.Purged 
                   &&
                    (
                        (!vb.Blown && vb.LastSeen > DateTime.UtcNow.AddDays(-6) ||
                            (vb.Blown && vb.ModifiedOn > DateTime.UtcNow.AddDays(-1))
                    ))

                   select vb;
```

In 2.2 Preview 3 I get an exception:

```
NullReferenceException: Object reference not set to an instance of an object.
Microsoft.EntityFrameworkCore.SqlServer.Query.ExpressionTranslators.Internal.SqlServerCurveMemberTranslator.Translate(MemberExpression memberExpression)
```

Is there a different way to filter dates?

**Comment by ajcvickers** [comment] 2018-10-22 16:54
@bricelam This looks similar to the last one. Full repro and stack trace:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.SqlServer.Query.ExpressionTranslators.Internal.SqlServerCurveMemberTranslator.Translate(MemberExpression memberExpression)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.RelationalCompositeMemberTranslator.Translate(MemberExpression memberExpression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.ProcessComparisonExpression(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.ExpressionVisitors.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression expression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.ExpressionVisitors.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression expression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.ExpressionVisitors.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression expression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.ExpressionVisitors.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.Main() in C:\Stuff\TwoTwoPreview\TwoTwoPreview\Program.cs:line 60
Press any key to continue . . .
```

```C#
public class Blog
{
    public int Id { get; set; }
    public bool Purged { get; set; }
    public bool Blown { get; set; }
    public DateTime LastSeen { get; set; }
    public DateTime ModifiedOn { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0",
                b => b.UseNetTopologySuite());

    public DbSet<Blog> Blogs { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog { Purged = false, Blown = false, LastSeen = DateTime.UtcNow, ModifiedOn = DateTime.UtcNow });
            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var data = from vb in context.Blogs
                where !vb.Purged
                      &&
                      (
                          (!vb.Blown && vb.LastSeen > DateTime.UtcNow.AddDays(-6) ||
                           (vb.Blown && vb.ModifiedOn > DateTime.UtcNow.AddDays(-1))
                          ))

                select vb;

            var results = data.ToList();
        }
    }
}
```

**Comment by bricelam** [comment] 2018-10-24 17:36
Dupe of #13686. Fixed in [the nightly builds](https://dotnet.myget.org/gallery/dotnet-core).

**Comment by aherrick** [comment] 2018-10-26 12:52
Is there any kind of work around to this minus going to the nightly builds? My app is killed without filtering dates.

Thanks!

**Comment by bricelam** [comment] 2018-10-26 17:06
Disable spatial (don't call `UseNetTopologySuite()`).

Keep in mind that the 2.2 nightly builds are closer to RTM quality than the Preview 3 release. The only changes going in are to stabilize for the final 2.2 release.

**Comment by aherrick** [comment] 2018-10-26 19:08
What does not calling UseNetTopologySuite do? I thought that was required for any kind of Spatial interaction? I've reverted back to Preview 2 for the time being. Thank you!

**Comment by bricelam** [comment] 2018-10-26 19:30
Exactly; the workaround is to not enable spatial support for queries that use `DateTime.UtcNow`.

**Closed** 2022-10-16 13:36 UTC
Labels: closed-duplicate, customer-reported
