### ISSUE TITLE
Global OwnedType Configuration

### ISSUE THREAD

**Issue by alienwareone** [dotnet/efcore#22191] opened 2020-08-24 11:46 UTC
I have multiple Entites which Own the same Type with the same Configurations.

e.g.
```
class Message
{
    string Text;
}
class Category
{
    Message Hint;
}
class Product
{
    Message Hint;
}
```

I tried to configure the Message type but this gives me the following error:
```
// InvalidOperationException: The entity type 'Message' cannot be added to the model because a weak entity type with the same name already exists.
public class MessageConfiguration : IEntityTypeConfiguration<Message>
{
    public void Configure(EntityTypeBuilder<Message> builder)
    {
        builder.Property(x => x.Heading).HasMaxLength(100);
    }
}
```

**Comment by ajcvickers** [comment] 2020-08-24 15:52
Duplicate of #6787

**Closed** 2022-10-16 18:37 UTC
Labels: customer-reported
