### ISSUE TITLE
System.InvalidCastException DBSet<T>.Add()

### ISSUE THREAD

**Issue by mkgn** [dotnet/efcore#10375] opened 2017-11-22 12:39 UTC
I am using EF Core 2.0 with ASP.Net Core 2.0 and SQL Server.

I get System.InvalidCastException when trying to call the generic method Context.Set<T> method. I have detailed out all information in below link.

[StackOVerflow Question](https://stackoverflow.com/questions/47368802/system-invalidcastexception-when-adding-an-entity-dbsett-add)

Since I couldn't get any information, i thought to write here as well. I appreciate any information.
```

**Comment by ajcvickers** [comment] 2017-11-22 17:05
@mkgn Can you post a complete code listing or VS project/solution that reproduces what you are seeing?

**Comment by ajcvickers** [comment] 2017-11-29 19:36
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:00 UTC
Labels: closed-could-not-reproduce
