### ISSUE TITLE
Lazy and Eager loading mismatched

### ISSUE THREAD

**Issue by yguang004** [dotnet/efcore#13983] opened 2018-11-20 04:22 UTC
While I have two web project share the same appdbcontext and service.
In the service I have this line of code to retrieve the information,
```
PublicAppUserProfile user = appDbCtx.PublicAppUserProfile
                                        .Where(o => o.Id == id && o.IsDeleted == false).SingleOrDefault();
            
```
How ever for one project, it only retrieve the information from the PublicAppUserProfile only.
For another project, it will retrieve all related tables, (with foreign keys) and the records in related table has been filter by IsDeleted, which only retrieve me the records that IsDeleted == false.
both sql executed are same.
both injection in the startup are the same:
```
services.AddDbContext<AppDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("AppDatabase"),
                                        sqlServerOptions => sqlServerOptions.EnableRetryOnFailure()));
```

And I never set the UseLazyLoaderProxies.
Anyone know what happened here?

**Comment by ajcvickers** [comment] 2018-11-20 19:08
@yguang004 There is not enough information here for us to be able to effectively and efficiently reproduce the issue you are seeing. Can you please post a runnable project/solution or complete code listing that demonstrates what you are seeing.

**Comment by ajcvickers** [comment] 2018-11-28 17:13
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:40 UTC
Labels: closed-could-not-reproduce, customer-reported
