### ISSUE TITLE
Not getting scaffolding work in a non local DB

### ISSUE THREAD

**Issue by cesarromero** [dotnet/efcore#7563] opened 2017-02-07 06:15 UTC
Hi
I not sure if is something to be with the non local DB the only thing created is the dbcontext and a bunch of commented error for every table I have in my DB

```
// Unable to generate entity type for table 'dbo.__MigrationHistory'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Almacenes'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Area_Almacen'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Areas'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Articulos_Auditoria'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Articulos_Cocidas'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Articulos_Compras'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Articulos_Cortes'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Articulos_Empresa'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Articulos_Facturas'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Articulos_Remisiones'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Articulos_Solicitudes'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Articulos_Traslados'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.AspNetRoles'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.AspNetUserClaims'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.AspNetUserLogins'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.AspNetUserRoles'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.AspNetUsers'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Auditorias'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Autorizaciones'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Cancelaciones'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Categorias'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.CategoriasCaja'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Clientes'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Cocidas'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.CodigosCaja'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Compras'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Comprobantes'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Conceptos_Contables'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.ConfiguracionGlobal'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Correcciones'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Cortes'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.CortesDeCaja'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Creditos'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Departamentos'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Detalles_Depositos'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Devoluciones'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Divisas'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Empleado_Contratos'. Please see the warning messages.
        // Unable to generate entity type for table 'dbo.Empleado_Faltas'. Please see the warning messages. //... and so on
```
At the end Any of my tables are scaffolded and the only warning I get is the normal 

`#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.`

I Excecuted the verbose mode and I get no clue for me

```
Using project 'MaISYS_Entity_API'.
Using startup project 'MaISYS_Entity_API'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile "C:\users\cesar\documents\visual studio 2017\Projects\MaISYS_Entity_API\MaISYS_Entity_API\bin\Debug\netcoreapp1.1\MaISYS_Entity_API.deps.json" --additionalprobingpath C:\Users\Cesar\.nuget\packages --runtimeconfig "C:\users\cesar\documents\visual studio 2017\Projects\MaISYS_Entity_API\MaISYS_Entity_API\bin\Debug\netcoreapp1.1\MaISYS_Entity_API.runtimeconfig.json" C:\Users\Cesar\.nuget\packages\microsoft.entityframeworkcore.tools\1.1.0-msbuild3-final\tools\netcoreapp1.0\ef.dll dbcontext scaffold "Server=BDD-SERVER\SQLSERVER;Database=Rosenda;User Id=developer;Password=*****" Microsoft.EntityFrameworkCore.SqlServer --json --output-dir Models --force --verbose --no-color --prefix-output --assembly "C:\users\cesar\documents\visual studio 2017\Projects\MaISYS_Entity_API\MaISYS_Entity_API\bin\Debug\netcoreapp1.1\MaISYS_Entity_API.dll" --startup-assembly "C:\users\cesar\documents\visual studio 2017\Projects\MaISYS_Entity_API\MaISYS_Entity_API\bin\Debug\netcoreapp1.1\MaISYS_Entity_API.dll" --project-dir "c:\users\cesar\documents\visual studio 2017\Projects\MaISYS_Entity_API\MaISYS_Entity_API" --content-root "c:\users\cesar\documents\visual studio 2017\Projects\MaISYS_Entity_API\MaISYS_Entity_API" --data-dir "C:\users\cesar\documents\visual studio 2017\Projects\MaISYS_Entity_API\MaISYS_Entity_API\bin\Debug\netcoreapp1.1\\" --root-namespace MaISYS_Entity_API
Using assembly 'MaISYS_Entity_API'.
Using startup assembly 'MaISYS_Entity_API'.
Using application base 'C:\users\cesar\documents\visual studio 2017\Projects\MaISYS_Entity_API\MaISYS_Entity_API\bin\Debug\netcoreapp1.1'.
Using content root 'c:\users\cesar\documents\visual studio 2017\Projects\MaISYS_Entity_API\MaISYS_Entity_API'.
Using root namespace 'MaISYS_Entity_API'.
Using project directory 'c:\users\cesar\documents\visual studio 2017\Projects\MaISYS_Entity_API\MaISYS_Entity_API'.
Using data directory 'C:\users\cesar\documents\visual studio 2017\Projects\MaISYS_Entity_API\MaISYS_Entity_API\bin\Debug\netcoreapp1.1\'.
```

I have no more information than that, you can tell me a way to get more information and I I'll post it

### Further technical details
EF Core version: EF 1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Hyper-V Windows 10
IDE: Visual Studio 2017
SQL Server 2016 Express mounted on Hyper-V machine with Windows Server 2016 Standar Core

**Comment by rowanmiller** [comment] 2017-02-13 18:54
I'm not able to reproduce this issue, I can successfully reverse engineer from a SQL 2016 database.

Could you share the schema creation script for the database you are reverse engineering from.

**Comment by rowanmiller** [comment] 2017-02-22 19:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 10:52 UTC
Labels: closed-could-not-reproduce
