### ISSUE TITLE
Guidance: System.InvalidCastException when mapping smallint to a boolean variable in valuedatabuffer.

### ISSUE THREAD

**Issue by PrashanthIBM** [dotnet/efcore#4371] opened 2016-01-22 07:33 UTC
Hi @rowanmiller , @divega , @maumar ,

We are trying to support Any() linq operator and getting System.InvalidCastException .
Issue recreatable with rc1 code.

The database does not support BIT Or BOOLEAN data type. 

Seems like a genuine and priority issue since it does not allow type casting of smallint to a boolean variable.
All servers which do not support boolean or bit data type  will face this problem.

Application code : 

```
    db.Customers.Any();
```

Actual Query generated in EF7 SQLSERVER : 

```
    SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [Customers] AS [c])
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END"
```

If the query is changed to something like this where the type casting is changed to SMALLINT in place of BIT, InvalidCastException is thrown.

```
 " SELECT CASE  WHEN EXISTS (  SELECT 1  FROM [Customers] AS [c])  THEN CAST(1 AS SMALLINT) ELSE CAST(0 AS SMALLINT) END "  
```

Stack trace : 

```
StackTrace = "   at Microsoft.Data.Entity.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers) in C:\\Users\\praskarn\\Desktop\\EF7\\EntityFramework-7.0.0-rc1\\src\\EntityFramework.Relational\\Query\\QueryMethodProvider.cs:line 64\r\n   at lambda_met...


Call stack : 

>   EntityFramework.Core.dll!Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery.AnonymousMethod__1(Microsoft.Data.Entity.Query.QueryContext qc) Line 164   C#
    EntityFramework.Core.dll!Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute<bool>(System.Linq.Expressions.Expression query) Line 78 C#
    EntityFramework.Core.dll!Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute<bool>(System.Linq.Expressions.Expression expression) Line 37  C#
    [External Code] 
    test_mssql.exe!test_mssql.Program.Main(string[] args) Line 25   C#
    [External Code] 
```

Simple ways to recreate :

1) 
App code : 
    db.Customer.Any();
During runtime,  
Put a breakpoint at https://github.com/aspnet/EntityFramework/blob/7.0.0-rc1/src/EntityFramework.Relational/Storage/Internal/RelationalCommand.cs and copy the failing sql in 
commandText in the below constructor and continue execution, the issue should be re-creatable.

```
    public RelationalCommand(
        [NotNull] ISensitiveDataLogger logger,
        [NotNull] DiagnosticSource diagnosticSource,
        [NotNull] string commandText,
        [NotNull] IReadOnlyList<IRelationalParameter> parameters)
    {
        Check.NotNull(logger, nameof(logger));
        Check.NotNull(diagnosticSource, nameof(diagnosticSource));
        Check.NotNull(commandText, nameof(commandText));
        Check.NotNull(parameters, nameof(parameters));

        Logger = logger;
        DiagnosticSource = diagnosticSource;
        CommandText = commandText;
        Parameters = parameters;
    }           
```

2) Try to create a linq query which returns 1 or 0 as smallint at the query level and where in EFrelational it is expecting a boolean in valuedatabuffer.

Thanks ,
Prashanth.

**Comment by PrashanthIBM** [comment] 2016-01-27 08:54
Hi ,

Can someone help me out with this issue ?

Thanks and Regards,
Prashanth.

**Comment by PrashanthIBM** [comment] 2016-01-27 12:25
After some more debugging, found that ExistsExpression type is cast to bool,
https://github.com/aspnet/EntityFramework/blob/7.0.0-rc1/src/EntityFramework.Relational/Query/Expressions/ExistsExpression.cs

public override Type Type => typeof(bool);

        protected override Expression Accept([NotNull] ExpressionVisitor visitor)
        {
            Check.NotNull(visitor, nameof(visitor));

            var specificVisitor = visitor as ISqlExpressionVisitor;

            return specificVisitor != null
                ? specificVisitor.VisitExists(this)
                : base.Accept(visitor);
        }

**Comment by rowanmiller** [comment] 2016-02-02 19:14
@anpete can comment on this one

**Comment by PrashanthIBM** [comment] 2016-02-10 10:29
Hi @anpete ,

Any updates on this issue ?
If you check this file : 
https://github.com/aspnet/EntityFramework/blob/7.0.0-rc1/src/EntityFramework.Relational/Query/Expressions/ExistsExpression.cs

The type is cast to bool 
public override Type Type => typeof(bool); .

If its changed to 
public override Type Type => typeof(**object**); similar to this file :
https://github.com/aspnet/EntityFramework/blob/7.0.0-rc1/src/EntityFramework.Relational/Query/Expressions/TableExpressionBase.cs
public override Type Type => typeof(object); 

Do you foresee any issues if the type is cast to object instead of bool ?

Thanks and Regards,
Prashanth.

**Comment by anpete** [comment] 2016-05-09 21:05
@PrashanthIBM Can you try the fix outline in: https://github.com/aspnet/EntityFramework/issues/5250

**Comment by rowanmiller** [comment] 2016-05-31 19:16
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Comment by clockwiseq** [comment] 2019-05-01 13:49
This is still very much an issue and can we please reopen this or something?  Returning a bit or int from SQL should properly map to a bool.

**Comment by clockwiseq** [comment] 2019-05-01 14:02
> This is still very much an issue and can we please reopen this or something? Returning a bit or int from SQL should properly map to a bool.

The only workaround I have found to work is to CAST the column to a BIT.

**Comment by ajcvickers** [comment] 2019-05-01 15:13
@clockwiseq This is an issue with the IBM provider. You should follow up with them.

**Closed** 2022-10-16 09:26 UTC
