### ISSUE TITLE
Generated SQL add extra precision to decimal constant without precision

### ISSUE THREAD

**Issue by cyuz** [dotnet/efcore#30545] opened 2023-03-22 01:49 UTC
1. I need load a value (decimal(4, 0)) and add constant(e.g. 1M)  from db.
2. Do some operation with the value.
3. Then write back to another column(decimal 4,0))

But the value generated at step 1, will be decimal(5,1).
So I must truncate before write back.

### Code

`var val = dbContext.TableA.Select(m =>m.SrcColumn + 1M).FirstOrDefault();`

### Generated SQL
```
SELECT TOP(1) [A].[SrcColumn] + 1.0
FROM [TableA] AS [A]
```

### Current WorkAround
declare a variable
```
decimal addedValue = 1M;
var val = dbContext.TableA.Select(m =>m.SrcColumn + addedValue ).FirstOrDefault();
```

### Include provider and version information
EF Core version:5.0.17
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system:VS 2019 16.11.25
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by ajcvickers** [comment] 2023-03-22 09:55
EF Core 5.0 is [out-of-support](https://learn.microsoft.com/en-us/ef/core/what-is-new/). Please update to EF Core 7.0 and try again.

**Comment by ajcvickers** [comment] 2023-04-05 17:18
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-04-05 17:18 UTC
Labels: customer-reported
