### ISSUE TITLE
CS8103: Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.

### ISSUE THREAD

**Issue by princegearydymosco** [dotnet/efcore#35270] opened 2024-12-04 17:04 UTC
I'm encountering an issue when attempting to run Update-Database on my .NET 6 project. This problem arose after I successfully created two new tables via migration, but the issue persists even with the most recent table I have tried to create. I used a workaround previously, where I divided the table creation into multiple migration files, allowing me to create two additional tables. However, even when trying to create a simple table with just an Id column (the most recent one), I am consistently getting the following error:

CS8103: Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.

Environment:
- .NET Version: .NET 6
- IDE: Visual Studio Community Edition 2022
- SDK Version: 9.0.101

**Comment by ajcvickers** [comment] 2024-12-04 17:09
Likely duplicate of #32261. @princegearydymosco Do you have a large amount of data in calls to `HasData`?

**Comment by princegearydymosco** [comment] 2024-12-05 16:27
> Likely duplicate of [#32261](https://github.com/dotnet/efcore/issues/32261). [@princegearydymosco](https://github.com/princegearydymosco) Do you have a large amount of data in calls to `HasData`?

I followed your advice and removed the HasData configuration, @ajcvickers . After doing this, the migration builds and Update-Database works as expected. However, I’m still unable to create new tables through the Add-Migration script, even though the HasData configuration has been removed from the current snapshot.

**Comment by AndriySvyryd** [comment] 2024-12-10 00:41
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.

Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2024-12-17 23:03 UTC
Labels: closed-could-not-reproduce, customer-reported
