### ISSUE TITLE
I modified the property value, but the modification state has not changed and the value has not changed

### ISSUE THREAD

**Issue by 775253959** [dotnet/efcore#24754] opened 2021-04-25 03:58 UTC
## File a bug

Remember:

* Please check that the [documentation](https://docs.microsoft.com/ef/) does not explain the behavior you are seeing.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your bug has not already been filed.

### Include your code

```c#
using (DMPDbContext context = new DMPDbContext())
{
    foreach (var deleteSpecimen in deleteSpecimens)
    {
        var existSpecimen = context.SpecimenInfos.FirstOrDefault(d => d.Id == deleteSpecimen.Id);
        if (existSpecimen != null)
        {
            existSpecimen.IsDeleted = true;
            existSpecimen.ModifyTime = DateTime.Now;
            existSpecimen.ModifierId = UserInfoRepository.LoginUser?.Id;
            var isfalse = context.Entry(existSpecimen).Property("IsDeleted").IsModified;//It was supposed to beTure, but now it's False
            var isfalse1= context.Entry(existSpecimen).Property("IsDeleted").CurrentValue; //It was supposed to beTure, but now it's False
        }
    }
    var count = context.SaveChanges();//The count is 0
    return true;
}
```

### Include stack traces

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.Sqlite)
Target framework: (e.g. .NET 3.1.7)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment] 2021-04-26 16:01
I am not able to reproduce this with the code snippet posted above. Please attach a small, _runnable_ project or post a small, _runnable_ code listing that reproduces what you are seeing so that we can investigate.

**Comment by 775253959** [comment] 2021-04-27 02:11
![image](https://user-images.githubusercontent.com/24452103/116174298-b74db200-a740-11eb-9ff6-888ffbcae0b2.png)
My computer has an encryption system and the code can't be sent out, but this picture is the key code and the result output

**Comment by roji** [comment] 2021-04-27 06:05
@775253959 see below for a code sample that's very similar to what you wrote above, and which behaves differently; something is missing from your code sample.

As @ajcvickers wrote above, we need a small, **runnable** project or code sample, and not code snippets. We don't need your full application code, but you'll need to work on a minimal unrelated project which reproduces the issue. In our experience, while working on that unrelated project, many users come across an issue in their code which explains the problematic behavior.

<details>
<summary>Attempted repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var blog = ctx.Blogs.Single();

blog.IsDeleted = true;
Console.WriteLine($"Deleted?: {blog.IsDeleted}");
Console.WriteLine($"IsDeleted CurrentValue: {ctx.Entry(blog).Property("IsDeleted").CurrentValue}");
Console.WriteLine($"IsDeleted IsModified: {ctx.Entry(blog).Property("IsDeleted").IsModified}");
Console.WriteLine("---------");
ctx.Entry(blog).Property("IsDeleted").CurrentValue = true;
Console.WriteLine($"Deleted?: {blog.IsDeleted}");
Console.WriteLine($"IsDeleted CurrentValue: {ctx.Entry(blog).Property("IsDeleted").CurrentValue}");
Console.WriteLine($"IsDeleted IsModified: {ctx.Entry(blog).Property("IsDeleted").IsModified}");

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
        => modelBuilder.Entity<Blog>().HasData(new Blog { Id = 1, Name = "foo", IsDeleted = false });
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
    public bool IsDeleted { get; set; }
}
```

Running the above results in the following, which seems correct:

```
Deleted?: True
IsDeleted CurrentValue: True
IsDeleted IsModified: True
---------
Deleted?: True
IsDeleted CurrentValue: True
IsDeleted IsModified: True
```

</details>

**Comment by ajcvickers** [comment] 2021-05-07 16:32
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:32 UTC
Labels: closed-could-not-reproduce, customer-reported
