### ISSUE TITLE
Need EF core supports using the same value converter to all properties

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#21976] opened 2020-08-06 19:00 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/537949/need-ef-core-supports-using-the-same-value-convert.html)._

---
<p>I'm using Entity Framework in ASP.Net Core 2.2 MVC.  I would like make ALL strings coming <strong>from</strong> the database to uppercase. I don't want to store them as uppercase, I just want them to be uppercase when I retrieve them.</p><p>Preferably, I'd like it to be just <strong>1 place</strong> in my code as opposed to writing a bunch of &quot;getters&quot; on model properties.</p><p>However, it seems that EF core does not support it yet:</p>0
<p>&quot;<a href="https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions">There is currently no way to specify in one place that every property of a given type must use the same value converter. This feature will be considered for a future release.</a>&quot; - Microsoft, Entity framework core docs.</p><p></p><p></p>

---
#### Jane Wu [MSFT] on 4/18/2019, 00:12 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by ajcvickers** [comment] 2020-08-07 18:36
Duplicate of #10784

**Closed** 2022-10-16 18:35 UTC
Labels: closed-duplicate, customer-reported
