### ISSUE TITLE
Simple LINQ stopped to work after upgrade to 5.0.1

### ISSUE THREAD

**Issue by maxima120** [dotnet/efcore#23667] opened 2020-12-12 15:05 UTC
## File a bug

What worked in 5.0

```
var events = dbContext.Events.Where(i => i.Date == date).ToArray();
```

In 5.0.1 this returns 0.

It works however if I rewrite it like this:

```
var events = dbContext.Events.ToList().Where(i => i.Date == date).ToArray();
```

so, materialised Linq works but SQLite Linq doesnt.

### Include your code

the column defined as
```SQL
create table events
(
	id integer primary key autoincrement,
	date date not null,
```

the EF OnModelCreating:

```C#
                entity.Property(e => e.Date)
                    .IsRequired()
                    .HasColumnType("date")
                    .HasColumnName("date");
```

the entity property:

```C#
public DateTime Date { get; set; }
```

### Include version information

Microsoft.Data.Sqlite version: 5.0.1
Target framework:  5.0.1
Operating system: Win 10

**Comment by roji** [comment] 2020-12-12 17:57
I'm not able to reproduce the issue - please see the code sample below. Can you please submit a full, runnable code sample (similar to the below) which demonstrates the problem?

<details>
<summary>Attempted repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var date = new DateTime(2020, 1, 1);
var events = ctx.Events.Where(i => i.Date == date).ToArray();
Console.WriteLine($"Count: {events.Length}");

public class BlogContext : DbContext
{
    public DbSet<Event> Events { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlite("Filename=/tmp/test.sqlite")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Event>().HasData(new Event { Id = 1, Date = new DateTime(2020, 1, 1) });
    }
}

public class Event
{
    public int Id { get; set; }
    public DateTime Date { get; set; }
}
```

</details>

**Comment by ajcvickers** [comment] 2021-01-04 16:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:15 UTC
Labels: closed-could-not-reproduce, customer-reported
