### ISSUE TITLE
Aggregate functions behave weirdly if result equals to default value in EF Core 3.0.1

### ISSUE THREAD

**Issue by imb590** [dotnet/efcore#19103] opened 2019-11-28 11:19 UTC
If the result of an aggregate function such as `Max`, `Min`, `Average` is equal to the default value of the resulting type, EF Core seems to treat the value as null. For example, the following program prints "null":

``` C#
using System.Linq;
using Microsoft.EntityFrameworkCore;

class Program
{
    static void Main(string[] args)
    {
        using (var db = new Context())
        {
            db.Database.EnsureDeleted();
            db.Database.EnsureCreated();

            db.Add(new Entity { Data = 0 });
            db.SaveChanges();

            var result = db.Entities.Max(e => (int?)e.Data);
            System.Console.WriteLine(result?.ToString() ?? "null");
        }
    }
}

public class Context : DbContext
{
    public DbSet<Entity> Entities { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlite("filename=test.db");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
    }
}

public class Entity
{
    public int Id { get; set; }
    public int Data { get; set; }
}
```

Without cast to `int?` it throws an exception as if database is empty:
```
System.InvalidOperationException: 'Sequence contains no elements.'
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Max[TSource,TResult](IQueryable`1 source, Expression`1 selector)
   at Program.Main(String[] args)
```

**Comment by smitpatel** [comment] 2019-11-30 11:19
Duplicate of #18955

**Closed** 2022-10-16 14:58 UTC
Labels: customer-reported
