### ISSUE TITLE
Throws System.InvalidOperationException where Any is used with FromSqlRaw

### ISSUE THREAD

**Issue by fscavo** [dotnet/efcore#27546] opened 2022-03-02 14:10 UTC
System.InvalidOperationException: The query contains usage of 'Any' or 'AnyAsync' operation after 'FromSqlRaw' or 'FromSqlInterpolated' me ││ thod. Using this raw SQL query more than once isn't currently supported. Replace the use of 'Any' or 'AnyAsync' with 'Count' or 'CountAsync'

**Comment by ErikEJ** [comment] 2022-03-02 14:14
Please share some code.

**Comment by fscavo** [comment] 2022-03-02 14:17
This code used to work fine with EF core 5
```csharp
var mappings = dbContext.Set<IdMappingDbEntity>().FromSqlRaw(query).AsNoTracking();
var result = mappings.Any() ? .....
```

**Comment by ajcvickers** [comment] 2022-03-02 14:31
Duplicate of #26167

**Closed** 2022-10-16 20:27 UTC
Labels: customer-reported
