### ISSUE TITLE
Linq to Entity is 3x slower than Linq to SQL

### ISSUE THREAD

**Issue by tomasr78** [dotnet/efcore#20071] opened 2020-02-26 10:25 UTC
I am trying to execute the `Linq to Entity` query on `EF Core 3.1.1` and it is `3X slower` than executing the same query on Linqpad using `Linq to SQL` provider.  

```
      var startDateTime = new DateTime(2020, 01, 01, 0, 0, 0);
      var endDateTime = new DateTime(2020, 02, 26, 0, 0, 0);

        var logs = _db.Logs
                    .Where(w => w.UserId == 10 && w.DateStamp >= startDateTime && w.DateStamp <= endDateTime)
                    .GroupBy(g => new
                    {
                        g.DateStamp.Date,
                        g.Result
                    }).Select(s => new
                    {
                        s.Key.Date,
                        s.Key.Result,
                        Conversions = s.Count(),
                        Cost = s.Sum(sum => sum.ConversionCost)
                    }).ToList();
```

I have checked the SQL which both providers generate and I would say Linq to Entity do better job writing queries.

**Linq to Entity, 6 seconds**

```
    -- Region Parameters
    -- @__startDateTime_0='2020-01-01T00:00:00', @__endDateTime_1='2020-02-26T00:00:00'
    -- EndRegion
    SELECT CONVERT(date, [l].[DateStamp]) AS [Date], [l].[Result], COUNT(*) AS [Conversions], SUM([l].[ConversionCost]) AS [Cost]
    FROM [Log] AS [l]
    WHERE (([l].[UserId] = 10) AND ([l].[DateStamp] >= @__startDateTime_0)) AND ([l].[DateStamp] <= @__endDateTime_1)
    GROUP BY CONVERT(date, [l].[DateStamp]), [l].[Result]
```

**Linq To SQL, 2 seconds**

```
    -- Region Parameters
    DECLARE @p0 Int = 10
    DECLARE @p1 DateTime = '2020-01-01 00:00:00.000'
    DECLARE @p2 DateTime = '2020-02-26 00:00:00.000'
    -- EndRegion
    SELECT COUNT(*) AS [Conversions], SUM([t1].[ConversionCost]) AS [Cost], [t1].[value] AS [Date], [t1].[Result]
    FROM (
        SELECT CONVERT(DATE, [t0].[DateStamp]) AS [value], [t0].[Result], [t0].[UserId], [t0].[DateStamp], [t0].[ConversionCost]
        FROM [Log] AS [t0]
        ) AS [t1]
    WHERE ([t1].[UserId] = @p0) AND ([t1].[DateStamp] >= @p1) AND ([t1].[DateStamp] <= @p2)
    GROUP BY [t1].[value], [t1].[Result]
```

**My pure SQL, 2 seconds**

```
    SELECT
    CONVERT(DATE, log.DateStamp),
    log.Result,
    Count(*),
    Sum(log.ConversionCost)
    FROM
    log
    Where UserId= 10 AND  DateStamp >= '2020-01-01' AND DateStamp <= '2020-02-26'
    GROUP BY
    log.Result,
    CONVERT(DATE, log.DateStamp)
```

So as you may find `Pure SQL` and `Linq to Entity` are very similar `SQLs` and `Linq to SQL` produce a little bit different version of SQL. Unfortunately, Linq to Entity query execution takes about 3 times slower than the other two.

My EF Core connection string

`    data source=xxx.xxx.xxx.xxx;initial catalog=x-test;user id=x-v2;password=x72-;connection timeout=600`

I have tried to execute SQL using Database.ExecuteSqlInterpolated and it gave perfect performance similar to Linq to SQL, but why Linq to Entity so slow?

### Further technical details

EF Core version: 3.1.1 and 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system:
Windows, LinqPad and Rider, this does not matter from which IDE I run queries performance the same.

**Comment by tomasr78** [comment] 2020-02-26 11:59
Am update, if I remove filtering by Date (w.DateStamp >= startDateTime && w.DateStamp <= endDateTime) from Linq the speed of Linq to Entity becomes the same as Linq to SQL. Why filtering by date causes speed degradation in Linq to Entity but not in SQL to Linq?

**Comment by ajcvickers** [comment] 2020-02-28 22:22
@tomasr78 What does the database schema for the table being mapped to look like? (We're wondering if the `DateStamp` column is `datetime` or `datetime2` or something else. However it would be good to see the complete schema for the table in case there is something else there.)

**Comment by ajcvickers** [comment] 2020-03-06 17:25
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:13 UTC
Labels: closed-could-not-reproduce, customer-reported
