### ISSUE TITLE
Cannot translate simple GroupBy on DateTime

### ISSUE THREAD

**Issue by fschlaef** [dotnet/efcore#19371] opened 2019-12-20 08:40 UTC
I have a query like this :

```csharp
_context.Client
    .Select(c => new
    {
        MonthYear = c.CreatedDate.Year.ToString() + "-" + c.CreatedDate.Month.ToString()
    })
    .ToList();
```

It gets correctly translated to SQL as this :

```sql
SELECT (CONVERT(VARCHAR(11), DATEPART(year, [c].[createdDate])) + N'-') + CONVERT(VARCHAR(11), DATEPART(month, [c].[createdDate])) AS [MonthYear]
FROM [Client] AS [c]
```

So far so good. Now, I want to `GROUP BY` on the same field. In SQL, I can simply copy paste the `SELECT` expression and it works fine :

```sql
SELECT (CONVERT(VARCHAR(11), DATEPART(year, [c].[createdDate])) + N'-') + CONVERT(VARCHAR(11), DATEPART(month, [c].[createdDate])) AS [MonthYear]
FROM [Client] AS [c]
GROUP BY (CONVERT(VARCHAR(11), DATEPART(year, [c].[createdDate])) + N'-') + CONVERT(VARCHAR(11), DATEPART(month, [c].[createdDate]))
```

But I have no way to write this with an EF Core query.

This throws an `System.InvalidOperationException: 'Client side GroupBy is not supported.'` :

```csharp
_context.Client
    .Select(c => new
    {
        MonthYear = c.CreatedDate.Year.ToString() + "-" + c.CreatedDate.Month.ToString()
    })
    .GroupBy(c => c.MonthYear)
    .ToList();
```

 So does this :

```csharp
_context.Client
    .Select(c => new
    {
        c.CreatedDate.Month,
        c.CreatedDate.Year
    })
    .GroupBy(c => new { c.Year, c.Month })
    .ToList();
```

I also tried looking in `EF.Functions` but it seems the SQL `YEAR()` and `MONTH()` have not been implemented, and neither is `DATEPART()`.

How can I translate this to EF ?

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: W10 x64
IDE: Visual Studio 2019 16.5P1

**Comment by smitpatel** [comment] 2019-12-20 21:10
Duplicate of #17068

**Closed** 2022-10-16 18:02 UTC
Labels: customer-reported
