### ISSUE TITLE
Include Query Filters into Compiled Query Cache

### ISSUE THREAD

**Issue by razims** [dotnet/efcore#11540] opened 2018-04-04 09:20 UTC
I am moving an application framework based on EF on EF Core. I find the query filters as nice feature for multi-tenant applications. Unfortunately they are not considered in compiled query cache. 

### Steps to reproduce
I have two parameters on my entities:
1. DeletedOn -> DateTime - on some objects.
1. Language -> String - on some objects (en-US, de-DE etc.).
2. TenantId -> Guid - all objects.

There is a `IDateTimeProvider` (faciliates testing) which is injected into EntityTypeConfiguration and mimics DateTime.UtcNow. Then the expression tree is built depending on entity interface and set as query filter
```c#
var finalExpression = Expression.Lambda(body, parameter);
builder.HasQueryFilter(finalExpression);
```

Since the lambda expression is cached and not considering query filters in cache key, my tests are failing at this point (using moq):

```c#
repo.Count().Should().Be(1);

var entity = repo.First(); // there is only one entity
datetImeProvider.SetupGet(x=>x.UtcNow).Returns(DateTime.UtcNow);
repo.Delete(entity); // sets DeletedOn internally

datetImeProvider.SetupGet(x=>x.UtcNow).Returns(DateTime.UtcNow.AddDays(-1)); // rewind time
repo.Count().Should().Be(0);

datetImeProvider.SetupGet(x=>x.UtcNow).Returns(DateTime.UtcNow); // set it back
repo.Count().Should().Be(1); // fails, returns 0
```

The same story is with my `ILanguageProvider`.

I added a custom `FakeMemoryCache` implementing `IMemoryCache` which does **NO** caching and all tests passed.

```c#
optionsBuilder.UseMemoryCache(new FakeMemoryCache());
```

### Suggestion
Use query filters as a part of `CompiledQueryCacheKey` struct. I see no sense of not considering them as a part of a query. Otherwise i have to use them internally in my repo by chaining Where(x=>x...) and they will be cached then. 

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Win 10 64x
IDE: JetBrains Rider 2018.1

**Comment by smitpatel** [comment] 2018-04-04 14:41
@razims - QueryFilters are not part of `CompiledQueryCacheKey` because that would be redundant. QueryFilters are stored on `IModel` and cannot change unless model changes. And `IModel` is part of cache key.

Apart from that, please share a runnable code which can be used to see the failures you are seeing.

**Comment by razims** [comment] 2018-04-04 17:45
@smitpatel - i created a test project you can find it under [efcoretest](https://github.com/razims/efcoretest)

Please look into tests project, i have commented the steps.

**Comment by smitpatel** [comment] 2018-04-05 00:07
The issue is how the test & filter both are setup.
Especially this line https://github.com/razims/efcoretest/blob/9e06a759361ab7995f8b87880eb8da3d8cda9c47/EfCoreTest.Data/Mapping/BaseEntityTypeConfiguration.cs#L25

You are encapsulating IDateTimeProvider in a constant expression inside your query filter. At that point onwards it loses connection with DbContext. So even if you change your mock to return different DateTime, the filter will not get updated. Hence if you force recompilation, the filter will be evaluated again and will re-compute value of the constant.
Further, even without constructing the ExpressionTree manually, you are not passing your DbContext, instead you are passing a property inside of it. If you use that in ExpressionTree (regardless of manual or compiler generated), we cannot know that the `IDateTimeProvider` you are using in your ET will take same value as the one of `DbContext` hence the values are not updated.

Please have a look at https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Specification.Tests/TestModels/QueryFilterFuncletizationContext.cs
Which defines a large variety of patterns of defining query filter and mentions what will be parametrized and what will be inlined.

**Comment by razims** [comment] 2018-04-05 14:11
@smitpatel thanks for your reply. I understand that DbContext loses connection with the provider, it is an expected behavior. 

What i actually want to understand  is why not include the filter into actual compiled query.

### Example
Assume i have a query filter defined, `IDataTimeProvider` passed to DbContext etc.:
```C#
builder.HasQueryFilter(x=>x.DeletedOn > dateTimeProvider.UtcNow || x.DeletedOn == null);
```
Then if i call:
```C#
Table.AsNoTracking().Count();
```

Should be considered as:
```C#
Table.AsNoTracking()
    .Where(x=>x.DeletedOn > dateTimeProvider.Object.UtcNow || x.DeletedOn == null)
    .Count();
```

**Comment by smitpatel** [comment] 2018-04-05 16:13
> What i actually want to understand is why not include the filter into actual compiled query.

Filters are included into compiled query. They are just not part of cache key explicitly since they are transitively take part in it through model.

```
//When you define filter like this
builder.HasQueryFilter(x=>x.DeletedOn > dateTimeProvider.UtcNow || x.DeletedOn == null);
// Then
Table.AsNoTracking().Count();
// Cannot be converted to
Table.AsNoTracking()
    .Where(x=>x.DeletedOn > dateTimeProvider.Object.UtcNow || x.DeletedOn == null)
    .Count();
```
Notice you changed from `dateTimeProvider.UtcNow` to `dateTimeProvider.Object.UtcNow`. That is incorrect and we cannot possibly mutate the expression tree in meaningfull way for all the cases.
Further, even if you remove copy over the filter as is, then Expression Tree becomes invalid because the value of `dateTimeProvider` is not in current scope. It will take value from the scope of closure when it was defined. Essentially filter will use stale values as you are seeing. Hence we do some pre-processing to allow updating values which goes into filter.

```C#
//For a filter like this
builder.HasQueryFilter(b => b.DeletedOn > context.dateTime);
// At the time of query compilation, it will first processed to find out where the value comes from current context instance and it will be changed.
// So after pre-processing step filter becomes this
var @param1 = context.dateTime;
filter = b => b.DeletedOn > @param1;
// For query like below
Table.AsNoTracking().Count();
//We convert it to following after pre-processing step
var @param1 = currentContext.dateTime; // we compute this value before running the query using current context instance
Table.AsNoTracking()
    .Where(b => b.DeletedOn > @param1)
    .Count()
// Above gets stored into compiled query
```
So whenever you run the same linq query again, we recompute the parameter values from current context and run the query with new parameters rather than recompiling it again.

There are multiple reason for this design,
- Since same filter Expression will compute same parametrized filter, we don't need to recompile query. Query Compilation is really costly step. By doing above, we avoid doing recompilation to provide better perf and avoid polluting query cache.
- The terms in filter which are not context bound gets inlined because there is no reliable way to update them. Further their values will be same as when you initialized your model. In your case your expression tree gets new value on recompilation (perhaps due to Mock), but in general it would have the same values as model building time and will evaluate to same thing over and over again. Hence we just inline them.

We have https://github.com/aspnet/EntityFrameworkCore/issues/11040 tracking adding an overload of `HasQueryFilter` which takes context in lambda expression as to tell EF about the terms which will take value from query running instance. That would make it easy for people to use context based variables in defining filter.

**Closed** 2022-10-16 12:17 UTC
Labels: closed-no-further-action
