### ISSUE TITLE
New EF7 Optimization of Insert query fails on tables with Triggers

### ISSUE THREAD

**Issue by CorsairRO** [dotnet/efcore#28897] opened 2022-08-26 12:19 UTC
## Ask a question

Hello @roji 

Thank you very much for your enormous amount of work done to improve perf every day...

However can i please make a suggestion if it is possible,
regarding your last optimization of Inserts that removes the need for temporary table there ( shown in .NET standup )

If i have 500+ objects in my DB and ALL of them uses triggers, and they are splitted in 20+ contexts.
Why should i have to go to EACH context/model builder and add .HasTrigger() ???

Please make it a GENERIC option in the DB Context, like .UseSqlServer, .UseLogging and so on ...

Moving from EF6 to EF7 will take me 2 days otherwise

PS: Triggers are REALLY needed in real life applications ( more that an app that shows blogs and posts ). Like to cascade calcuations of on stock quantities as a basic example where the quantity can be changed from multiple places and DB can handle that nicely instead of programmer have to remember to do so.
Not to mention AUDIT logging of all changes and so on ...

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ErikEJ** [comment] 2022-08-26 12:22
@CorsairRO EF Core 7 scaffolding add triggers for you (maybe need daily build)

**Comment by roji** [comment] 2022-08-26 12:24
Duplicate of #27531

**Comment by roji** [comment] 2022-08-26 12:25
We ended up deciding not to include such functionality inside EF Core, but you can easily do it yourself! Follow the instructions in https://github.com/dotnet/EntityFramework.Docs/issues/3883#issuecomment-1220969823 (which we'll be adding to the docs), this will basically configure a "blank" trigger to each table.

**Comment by ErikEJ** [comment] 2022-08-26 12:27
@roji Did you not add it to reverse engineering?

**Comment by roji** [comment] 2022-08-26 13:55
I did, but there's no indication above that @CorsairRO is using scaffolding... And BTW, scaffolding does scaffold the per-table trigger.

**Closed** 2022-08-31 18:59 UTC
Labels: customer-reported
