### ISSUE TITLE
Unexpected behavior using Table Splitting

### ISSUE THREAD

**Issue by draudrau** [dotnet/efcore#19779] opened 2020-02-03 12:44 UTC
Hi all,

I am using table splitting to model composition association between two entities.
You can look at the project in attachment.

First I create the parent entity (Blog) without explicitely defining the child entity (Author).
Then I try to get the Blog entity with loading the child (Author). I am expecting the Author entity is loading (with all its properties to null). 
But I get an exception. Author is null.
I think it's not relevant. Table splitting is appropriate to model composition association between two entities. In a composition, the Blog entity can't exist without the Author entity.
When I get the Blog entity with the Author entity, the Author should never be null.

[TableSplittingIssue.zip](https://github.com/dotnet/efcore/files/4147905/TableSplittingIssue.zip)

### Further technical details
EF Core version: 3.1.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SQLite)
Target framework: (e.g. .NET Core 3.1.1)
Operating system: Windows 10 Pro 1909
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment] 2020-02-03 21:30
Duplicate of #12100. 

@draudrau Not a great workaround, I know, but if one or more properties on the child are required, then you should get the behavior you want.

**Comment by draudrau** [comment] 2020-02-04 13:59
Thanks for the workaround, I am doing like that for now.
It's just a bit frustrating when I dont need required property.

Good job, EF Core is a great ORM, very pleasant to use.

**Closed** 2022-10-16 18:08 UTC
Labels: closed-duplicate, customer-reported
