### ISSUE TITLE
Some DateTime values are not diffed correctly in seed data

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#13208] opened 2018-09-04 16:16 UTC
Moved from https://github.com/aspnet/EntityFrameworkCore/issues/13172#issuecomment-418177283 posted by @fpanaccia

Hi, i just found that with DateTime.MaxValue it has the same behaviour than the one with byte[], i have this seed

```C#
            modelBuilder.Entity<Entities.Tasks>().HasData(new Entities.Tasks()
            {
                Id = Guid.Parse("50475284-2956-4F4B-9C51-B6D87C112D32"),
                Status = DTO.Enum.TasksStatus.Waiting,
                CreationDate = DateTime.MinValue,
                StartDate = DateTime.MinValue.Date.AddDays(1).AddHours(8).AddMinutes(30),
                LastRunning = DateTime.MinValue,
                EndDate = DateTime.MaxValue,
                Period = TimeSpan.FromHours(24),
                Json = JsonConvert.SerializeObject(string.Empty)
            });
```

And then, when we create a migration without any change in the context, we get this

```C#
    public partial class InitialCreate3 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                schema: "payment",
                table: "tasks",
                keyColumn: "id",
                keyValue: new Guid("50475284-2956-4f4b-9c51-b6d87c112d32"),
                column: "end_date",
                value: new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified));
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                schema: "payment",
                table: "tasks",
                keyColumn: "id",
                keyValue: new Guid("50475284-2956-4f4b-9c51-b6d87c112d32"),
                column: "end_date",
                value: new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified));
        }
    }
```
BUT it does not behave like this, if you use DateTime.MinValue.

EF Core version: 2.1.1
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL (2.1.1.1)
Operating system: Win 10 Pro 1803
IDE: Visual Studio 2017 15.8.2

**Comment by ajcvickers** [comment] 2018-09-05 18:46
@AndriySvyryd to find the dupe.

**Comment by AndriySvyryd** [comment] 2018-09-05 20:00
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/12346

**Closed** 2022-10-16 13:29 UTC
Labels: closed-duplicate, customer-reported
