### ISSUE TITLE
[Feature Request] InternalDbSet.CreateEntityQueryable()

### ISSUE THREAD

**Issue by joe88ds** [dotnet/efcore#22876] opened 2020-10-03 02:10 UTC
https://github.com/dotnet/efcore/blob/3011c69f126dd60ecb340ca4d15650f8a96aa9c8/src/EFCore/Internal/InternalDbSet.cs#L141

Currently:
`private EntityQueryable<TEntity> CreateEntityQueryable()
            => new EntityQueryable<TEntity>(_context.GetDependencies().QueryProvider, EntityType);`

Would like to see this changed so a custom IAsyncQueryProvider has a chance to create the EntityQueryable:
`private EntityQueryable<TEntity> CreateEntityQueryable()
            => _context.GetDependencies().QueryProvider.CreateQuery(EntityType);`

The EntityQueryProvider would also need to support this.

**Comment by smitpatel** [comment] 2020-10-03 04:43
IQueryProvider.CreateQuery does not take IEntityType argument.
EntityQueryable is internal API which can break between releases.

Can you describe what are you trying to achieve?

**Comment by joe88ds** [comment] 2020-10-03 14:54
Yes, I am overriding the IAsyncQueryProvider.Execute*() methods in order to post-process the results. I achieve this by reading from the expression tree to get my custom EntityQueryable. Through my own extension methods that take a IQueryable<T>, I then am able to add "observer-like" actions to my custom EntityQueryable. I then wrap my own iterator around the results from IAsyncQueryProvider.Execute*() methods, which will then process the entity before it is returned to the caller.

Example code:

IAsyncQueryProvider
_public override IAsyncEnumerable<TResult> ExecuteAsync<TResult>(Expression expression)
{
  // Read's the expression tree to find the custom EntityQueryable
  var Q = GetQueryObject(expression);
  // Execute the expression
  var R = base.ExecuteAsync<TResult>(expression);
  // If Q is valid then use Q.AsyncDo to process each item (passing each item to the observers)
  return (Q == null) ? R : R.Do(Q.AsyncDo);
}_

IQueryable<T> extensions:
_public static IQueryable<T> WithStore<T>(this IQueryable<T> Query, Action<T> Pred)
{
  // Get the custom provider
  var P = Query.Provider as DbQueryProvider;
  // Get the custom EntityQueryable
  var Q = P.GetQueryObject(Query.Expression) ?? (Query as IDbEntityQueryable);
  // Add Pred as a observer
  Q.AddObserver(Pred);
   // Return the original query
  return Query;
}_

As it goes though, the InternalDbSet uses EntityQueryable and I would think it more proper to use the injected IAsyncQueryProvider instead (with or without my request). Since CollectionEntry.Load*(), or any other method that depends on the IQueryable<T> returned from DbSet, it should return the proper EntityQueryable, which I believe must be provided through the IAsyncQueryProvider interface.

**Comment by smitpatel** [comment] 2020-10-03 18:07
@joe88ds - Above code snipper does not compile. EF Core does not have types `DbQueryProvider` or `IDbEntityQueryable`.
Regardless, if you are using your own IAsyncQueryProvider then you need to register it in DI by replacing the default one. Then it will be used. The implementation of CreateEntityQueryable above wouldn't matter.

**Comment by joe88ds** [comment] 2020-10-03 19:06
My first post was describing the issue more clearly. The InternalDbSet doesn't use the injected IAsyncQueryProvider to return a EntityQueryable object, as I pointed out in the first post. Instead, I'm asking to add this feature to the code, so the injected IAsyncQueryProvider will have a chance to create that EntityQueryable object, and not hard-coded inside the InternalDbSet.

**Comment by smitpatel** [comment] 2020-10-03 19:58
`CreateEntityQueryable` in `InternalDbSet` is taking IAsyncQueryProvider from DI. See `_context.GetDependencies().QueryProvider`. Make sure you have properly registered your custom query provider in services.
Nothing is hard-coded except for the part that it will return `EntityQueryable<T>`. Are you trying to replace query provider or queryable?

**Comment by joe88ds** [comment] 2020-10-03 20:23
I'm trying to get my custom EntityQueryable to be used by the InternalDbSet, and this would only be possible if it asked my custom IAsyncQueryProvider to create the object. Here, from my first post I wrote out a quick example of what this should look like:
```
private EntityQueryable<TEntity> CreateEntityQueryable() => 
  _context.GetDependencies().QueryProvider.CreateQuery(EntityType);
```
That would be the first modification. The second modification would be to add the *new method* inside the IAsyncQueryProvider interface so it would be possible to do it this way.

**Comment by smitpatel** [comment] 2020-10-03 23:28
Given EF Core's `EntityQueryable<T>` calls to `IAsyncQueryProvider` for execute method, why do _really_ need to replace `EntityQueryable<T>`? Otherwise, if you want to replace `EntityQueryable<T>` in DbSet then you need to write a custom implementation of `DbSet<T>` rather than using `InternalDbSet<T>`.

On the other hand, if you want to pass something which works when invoking Execute then it should be part of Execute method if returning non-enumerable result or GetEnumerator method if returning enumerable result. I suggest you look up how async queries pass cancellation token to executing query in various scenarios. Notice there is no "WithCancellationToken" queryable operator.

**Comment by joe88ds** [comment] 2020-10-04 01:06
I thank you for your time, I really don't see how it is a good practice to hard-code dependencies when you should be using the injected providers to get the dependency. If doing it this way, when allowing us to replace the `IAsyncQueryProvider` with a custom one, and then giving us the ability to override `CreateQuery()`, and yet not using it for cases that need a `IQueryable<T>`, is acceptable within the group here, then so be it. I see a benefit in using DI when possible, and in this case, it is 100% possible. I understand this is internal services, and is not really used for public consumption. Again, why would this not be used?
```
private EntityQueryable<TEntity> CreateEntityQueryable() => 
  _context.GetDependencies().QueryProvider.CreateQuery<TEntity>();
```

and why is this more favorable?
```
private EntityQueryable<TEntity> CreateEntityQueryable() => 
  new EntityQueryable<TEntity>(_context.GetDependencies().QueryProvider, EntityType);
```

**Comment by smitpatel** [comment] 2020-10-04 15:47
It is not used because it is wrong design. Any operator (or method call) working on Queryable is supposed to create a different expression tree and put it inside the Queryable. They do not change the Queryable in any way. Anything custom which needs to go in during execution phase should be passed only when calling Execute method. We are just following the core design of Queryable/QueryProvider here. If it is being blocker for a wrong design then it is expected.

We will discuss in team meeting if we want to make `EntityQueryable<T>` public so that someone can depend on it. Otherwise trying to change `EntityQueryable<T>` in EF Core can have drastic consequences in terms of query translation.

**Comment by joe88ds** [comment] 2020-10-04 17:26
So we shouldn't use `EntityQueryable<T>` to carry state through-out the query building process? I think I have a valid design in order to support this. The caller gets a injected `IRepository<T>`, and asks for a `IQueryable<T>`. The `IRepository<T>`, before returning a `IQueryable<T>`, adds observers to the `Queryable`, as partially shown in my second post. The caller then builds the query, and then executes the query to get the results. Before the results get to the caller, the observers are able to process each entity. I have no interest in parsing a expression tree, I just want to be able to carry state with the query, without affecting the expression tree in any way. This would be bad design?

**Comment by smitpatel** [comment] 2020-10-04 20:09
Enumerable is deferred-execution iterators. When you apply `Where` to enumerable, it does not apply the predicate and filter it right away. It will wait till you actually enumerate the iterator to apply predicate. Taking it 1 more step further,
Queryable is also deferred-fully iterator. When you apply `Where` to a queryable, it does not store predicate as a state, rather it forms an expression tree and integrate it so no matter what operators you apply in what order, there is no chained execution. The query provider can execute the expression tree in whatever way. (In case of any ORM like EF Core, changing operations which gives same result, moving around operators etc is common for queryables).

Queryables are not **required** to have any states other than expression tree. They are just wrapper over the expression tree for composability. Since Queryables also implement IEnumerable, EF Core stores Query provider inside to enumerate. Again if there is another way to enumerate the expression without going to query provider then this state is not needed.

So anything beyond above, if you want to store a state in Queryable you can and that is personal preference. EF Core follows simplest and most suitable implementation of IQueryable for its queries. For anything complex you need to bring your own so you need to modify DbSet implementation to return you Queryable rather than using EntityQueryable, (Changing above method wouldn't help)

**Comment by joe88ds** [comment] 2020-10-05 00:47
I tried to get as much relevant code as possible for you. All this does is add "observable" behavior to the queryables returned from the repository.

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Microsoft.Extensions.DependencyInjection;

namespace GitHub.EFCore.ObservableQueryable
{
	public static class CustomQueryableExtensions
	{
		public static IQueryable<T> WithObserver<T>(this IQueryable<T> Query, Action<T> Observer)
		{
			var Queryable = (Query.Provider as CustomQueryProvider)?.GetQueryObject(Query.Expression) ?? (Query as ICustomEntityQueryable);
			Queryable?.AddObserver(Observer);
			return Query;
		}
	}

	public interface ICustomEntityQueryable
	{
		void AddObserver<T>(Action<T> Observer);
		void ObserveItem<T>(T Entity);
		IEnumerable<T> Process<T>(IEnumerable<T> Entities);
		T Process<T>(T Entity);
	}
	public class CustomEntityQueryable<TResult> : EntityQueryable<TResult>, ICustomEntityQueryable
	{
		public List<Action<TResult>> Observers => (_Observers ?? (_Observers = new List<Action<TResult>>()));
		private List<Action<TResult>> _Observers;

		public CustomEntityQueryable(IAsyncQueryProvider provider) : base(provider)
		{
		}
		public CustomEntityQueryable(IAsyncQueryProvider provider, Expression expression) : base(provider, expression)
		{
		}

		public void AddObserver<T>(Action<T> Observer)
		{
			Observers.Add((Action<TResult>)(object)Observer);
		}

		public void ObserveItem<T>(T Entity)
		{
			foreach (var Item in Observers)
			{
				Item((TResult)(object)Entity);
			}
		}
		public IEnumerable<T> Process<T>(IEnumerable<T> Entities)
		{
			foreach (var Entity in Entities)
			{
				ObserveItem(Entity);
				yield return Entity;
			}
		}
		public T Process<T>(T Entity)
		{
			if (typeof(T).IsClass && typeof(TResult).IsInstanceOfType(Entity))
			{
				ObserveItem(Entity);
			}
			return Entity;
		}
	}

	public class CustomQueryProvider : EntityQueryProvider
	{
		public CustomQueryProvider(IQueryCompiler queryCompiler) : base(queryCompiler)
		{
		}

		public ICustomEntityQueryable GetQueryObject(Expression expression)
		{
			// There are two possibilities:
			//	1. expression is a queryable with no other methods added to it (should be a ConstantExpression)
			//	2. expression is a queryable with a chain of methods (e.g. Where()) and we must iterate this chain until we reach a ConstantExpression
			//
			ConstantExpression Query = null;
			if (expression is MethodCallExpression MethodCall)
			{
				FindQueryObject(MethodCall, ref Query);
			}
			else
			{
				Query = expression as ConstantExpression;
			}
			return (Query?.Value as ICustomEntityQueryable);
		}
		private void FindQueryObject(MethodCallExpression methodCall, ref ConstantExpression query)
		{
			if (!(methodCall.Arguments[0] is MethodCallExpression))
			{
				query = methodCall.Arguments[0] as ConstantExpression;
				return;
			}

			// Iterate the chain of method calls, expecting Arguments[0] to be either another MethodCallExpression or a ConstantExpression
			var Scope = methodCall.Arguments[0] as MethodCallExpression;
			while (Scope != null)
			{
				if (Scope.Arguments[0] is MethodCallExpression NextScope)
				{
					Scope = NextScope;
				}
				else
				{
					query = Scope.Arguments[0] as ConstantExpression;
					return;
				}
			}
		}

		public override TResult Execute<TResult>(Expression expression)
		{
			var Query = GetQueryObject(expression);
			var Result = base.Execute<TResult>(expression);
			return (Query == null) ? Result : Query.Process((dynamic)Result);
		}
		public override IAsyncEnumerable<TResult> ExecuteAsync<TResult>(Expression expression)
		{
			var Query = GetQueryObject(expression);
			var Iterator = base.ExecuteAsync<TResult>(expression);
			return (Query == null) ? Iterator : Iterator.Do(Query.ObserveItem);
		}
	}

	public class CustomEntity
	{
		public int Id;
	}
	public class CustomDbContext : DbContext
	{
		public CustomDbContext(DbContextOptions<CustomDbContext> options) : base(options)
		{
		}
	}

	public interface ICustomRepository<TEntity>
	{
		IQueryable<TEntity> Queryable { get; }
	}
	public class CustomRepository<TEntity, TContext> : ICustomRepository<TEntity>
		where TEntity : class
		where TContext : DbContext
	{
		public IQueryable<TEntity> Queryable => EntitySet;

		private readonly DbSet<TEntity> EntitySet;
		private readonly TContext DbContext;

		public CustomRepository(TContext dbContext)
		{
			DbContext = dbContext;
			EntitySet = DbContext.Set<TEntity>();
			//
			// Not possible, because InternalDbSet uses EntityQueryable<T> and not my CustomEntityQueryable
			//EntitySet.WithObserver(CustomObserver);
			//
			InitializeEntityQueryable();
		}

		private IAsyncQueryProvider GetQueryProvider => DbContext.GetDependencies().QueryProvider;
		private void InitializeEntityQueryable()
		{
			var EntityQueryable = EntitySet.GetType().GetField("_entityQueryable", BindingFlags.NonPublic | BindingFlags.Instance);
			//
			// Ask the QueryProvider for the EntityQueryable<T>
			// var Queryable = DbContext.GetDependencies().QueryProvider.CreateQuery<TEntity>();
			//
			var Queryable = new CustomEntityQueryable<TEntity>(GetQueryProvider).WithObserver(CustomObserver);
			//
			// Need a way to use InternalDbSet.EntityQueryable as transient (e.g. create a new queryable on every use)
			//
			// The reason why I care about this below is because I want my queryable to be used when CollectionEntry.Load*() or 
			// ReferenceEntry.Load*() is called, or whatever code that may use the DbSet as a queryable
			//	- There would be no problem if this was created through the QueryProvider in the first place
			//
			EntityQueryable.SetValue(EntitySet, Queryable);
		}

		private void CustomObserver(TEntity Entity)
		{
			//
			// Process Entity...
			//
			// If Entity has features... do stuff...
			//
		}
	}

	public class Startup
	{
		public void SetupCustomServices(IServiceCollection services)
		{
			services.AddDbContext<CustomDbContext>(options =>
			{
				options.ReplaceService<IAsyncQueryProvider, CustomQueryProvider>();
				// Need to setup the SQL connection string
				options.UseSqlServer("");
			});
			services.AddScoped<ICustomRepository<CustomEntity>, CustomRepository<CustomEntity, CustomDbContext>>();
		}
	}
	public class ExecuteCallerCode
	{
		// DI injected
		public ExecuteCallerCode(ICustomRepository<CustomEntity> repository)
		{
			// Before this returns, the observer set up in CustomRepository.InitializeEntityQueryable() would have processed these entities
			repository.Queryable.ToList();
		}
	}
}

```

**Comment by smitpatel** [comment] 2020-10-05 21:32
We cannot change the method to use CreateQuery. CreateQuery returns `IQueryable<T>` where as DbSet is special queryable that it requires async enumerable also. That means that the Queryable represented by DbSet must be `EntityQueryable<T>` to enumerate it async without going through bunch of casting over interface. Using CreateQuery will change the return type to IQueryable<T> which will be in a way perf regression.

**Closed** 2022-10-16 19:03 UTC
Labels: closed-no-further-action, customer-reported
