### ISSUE TITLE
Change query filter on execute

### ISSUE THREAD

**Issue by ErliSoares** [dotnet/efcore#10645] opened 2018-01-04 20:45 UTC
In the database the type is a string, but in the code I put it to be bool, making the following configuration:

Simplified configuration:
```CSHARP
public class ContaConfiguration : IEntityTypeConfiguration<Conta>
{
    public void Configure(EntityTypeBuilder<Conta> builder)
    {
        builder.HasKey(c => new { c.Codigo });
        builder.Property("DbImprimir");
    }
}
```

Simplified entity:
```CSHARP
[System.ComponentModel.DataAnnotations.Schema.Table("conta")]
public partial class Conta
{
    [System.ComponentModel.DataAnnotations.Key()]
    [System.ComponentModel.DataAnnotations.Schema.Column("Codigo")]
    public int Codigo { get; set; }

    [System.ComponentModel.DataAnnotations.Schema.NotMapped]
    public bool? Imprimir { get; set; }

    [System.ComponentModel.DataAnnotations.Schema.Column("Imprimir")]
    private string DbImprimir { get => Imprimir.IsTrue() ? "Sim" : "Não"; set => Imprimir = value?.TryCast<string>() == "Sim"; }
}
```

When I put the filter below does not work, because the 'Imprimir' property is not mapped, does it have any before executing the query change the property to 'DbImprimir' in Query Linq?
```CSHARP
using (var db = new DbContext())
{
    var test = db.Conta.Where(equipeQ => equipeQ.Imprimir == true).FirstOrDefault();
}
```

**Comment by ErliSoares** [comment] 2018-01-04 21:00
Change the expression, I think it is possible with:
```CSHARP
public class MemberExpressionModifier : ExpressionVisitor
{
    protected override Expression VisitMember(MemberExpression node)
    {
        return Modify(node);
    }
    public MemberExpression Modify(MemberExpression expression)
    {
        ...
    }
}
```

**Comment by ralmsdeveloper** [comment] 2018-01-04 21:09
@ErliSoares 

I believe, that you are wanting this:
https://docs.microsoft.com/en-us/ef/core/modeling/backing-field

**Comment by ErliSoares** [comment] 2018-01-04 21:41
thanks @ralmsdeveloper, but not work.

Entity property:

```CSHARP
        string _imprimir;
        public bool? Imprimir
        {
            get
            {
                if (string.IsNullOrEmpty(_imprimir))
                {
                    return null;
                }
                return _imprimir == "Sim";
            }
            set
            {
                _imprimir = Imprimir.IsTrue() ? "Sim" : "Não";
            }
        }
```

Configuration:
```CSHARP
public class ContaConfiguration : IEntityTypeConfiguration<Conta>
{
    public void Configure(EntityTypeBuilder<Conta> builder)
    {
        builder.HasKey(c => new { c.Codigo });
        builder.Property("Imprimir").HasField("_imprimir").UsePropertyAccessMode(PropertyAccessMode.Field);
    }
}
```

The following error occurs:
> The specified field '_imprimir' of type 'string' cannot be used for the property 'Conta.Imprimir' of type 'Nullable<bool>'. Only backing fields of types that are assignable from the property type can be used.

Then I'll try: "Fields without property"

**Comment by ralmsdeveloper** [comment] 2018-01-04 23:18
@ErliSoares,

I do not think it's anything fancy, but it solves your problem!
```csharp
public class ContaConfiguration : IEntityTypeConfiguration<Conta>
{
    public void Configure(EntityTypeBuilder<Conta> builder)
    {
        builder
            .ToTable("conta")
            .HasKey(c => new { c.Codigo });

        builder
            .Ignore(p => p.Imprimir)
            .Property(p => p.DbImprimir)
            .HasColumnName("Imprimir");
    }
}
```

```csharp
public partial class Conta
{
    [System.ComponentModel.DataAnnotations.Key()]
    public int Codigo { get; set; }

    public bool Imprimir
    {
        get => _imprimir.Equals("Sim", StringComparison.OrdinalIgnoreCase);
        set
        {
            _imprimir = value ? "Sim" : "Não";
            Imprimir = value;
        }
    }

    private string _imprimir;
    public string DbImprimir
    {
        get=> _imprimir;
        set=> _imprimir = value;
    }
}
```

**Comment by ErliSoares** [comment] 2018-01-05 00:00
I think it will be the same alternative, if they were not to change the library I would try to change the query expression using QueryCompiler, but I am afraid to hide this possibility in future versions.

```CSHARP
public class CustomQueryCompiler : Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler
{
    public CustomQueryCompiler(IQueryContextFactory queryContextFactory, ICompiledQueryCache compiledQueryCache, ICompiledQueryCacheKeyGenerator compiledQueryCacheKeyGenerator, IDatabase database, IDiagnosticsLogger<DbLoggerCategory.Query> logger, INodeTypeProviderFactory nodeTypeProviderFactory, ICurrentDbContext currentContext, IEvaluatableExpressionFilter evaluatableExpressionFilter) : base(queryContextFactory, compiledQueryCache, compiledQueryCacheKeyGenerator, database, logger, nodeTypeProviderFactory, currentContext, evaluatableExpressionFilter)
    {

    }
    public override TResult Execute<TResult>(Expression query)
    {
        query = ChageProperties(query);
        return base.Execute<TResult>(query);
    }

}
```

Change service
```CSHARP
new DbContextOptionsBuilder().ReplaceService<IQueryCompiler, CustomQueryCompiler>()
```

If you have any more ideas, you had to be able to use it along with OData, that way that posted resolves, but when using with the OData querys in service will not work.

**Comment by ralmsdeveloper** [comment] 2018-01-05 00:08
Did the part I put above help with your initial question?

I suggest that when you open the problem, tell the environment that you are trying to run the tests.
**Example:**
### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ErliSoares** [comment] 2018-01-05 22:54
It did not help much, he had made that attempt, but it could not be that way with other tools and maintenance terms as well.

I wanted the database to be a data type and the other type code was another type, defining the conversion between the types in the source code, but from what I'm seeing it will not be possible. 
Leave a few more days to see if any more suggestions appear.

Thanks for the help and suggestion to put more details @ralmsdeveloper.

### My technical details
Microsoft.EntityFrameworkCore _2.0.1_
MySqlConnector _0.32.0_
Pomelo.EntityFrameworkCore.MySql  _2.0.1_
.NET Standart  _2.0_

**Comment by ajcvickers** [comment] 2018-01-09 16:37
@ErliSoares When 2.1 is released this will be possible using value conversions--that is, it will be possible to configure the bool property in the model to be converted to and from a string in the database. It should then be possible to use it in the query filter directly.

In 2.0, I don't think that there is a way to do this because the query filter needs the actual mapped property, which has to be a string if it will be stored to the database as a string.

Closing as duplicate of #242

**Closed** 2022-10-16 12:04 UTC
Labels: closed-duplicate
