### ISSUE TITLE
Invalid SQL (multi-part binding issue) when querying a parent table with a two branch three level relationship pattern

### ISSUE THREAD

**Issue by brianro** [dotnet/efcore#3429] opened 2015-10-14 20:37 UTC
EF 7 beta 7 is corrupting the SQL for this specific condition:

Relationships
A -> B -> C,
A -> D <- E

One A record has one B and one D record. B record has one C record. E record has one D record. Records are all required. E -> D is an inverse reference.

NOTE: E.dId is nullable  - I think this plays a part in the issue - just not sure exactly how / why. For this subset, it is definitely populated.

This statement also doesn't work unless I wrap the statement
from e in E where ids.Contains(E.dId.Value)   <-- Does not work - query missing parts
from e in E where ids.Contains(E.dId ?? 0)   <-- Works

Relationships are FK integer id's.

Query pattern
Db.A
.Include(a => a.B)
.Include(a => a.B.C)
.Include(a => a.D)
.Include(a => a.D.E)
.Select( a => new A
{
   Id = a.Id,
   Name = a.Name,
   B = new B
   {
      Id = a.B.Id,
      Name = a.B.Name,
      C = new C
      {
          Id = a.B.C.Id,
          Name = a.B.C.Name
      }
    },
   D = new D
   {
      Id = a.D.Id,
      Name = a.D.Name,
      E = new E
      {
          Id = a.D.E.Id,
          Name = a.D.E.Name
      }
    }
  }
).ToList();

If I remove either of the second level elements e.g. C or E, the query works just fine. The moment I include all tables, the query has multi-part identifier that cannot be bound.

Please don't hesitate to email me for more info.
brianro@hotmail.com

Thanks,
B.

**Comment by rowanmiller** [comment] 2015-10-16 22:15
@brianro There isn't enough info in this issue for us to work out what is happening. Can you share a complete code listing that we can use to reproduce and debug the issue? Include the entity classes, context, and application code. It would also be great if you could include the generated SQL and the full exception details (message and stack trace).

**Comment by brianro** [comment] 2015-10-17 14:06
Rowan - I appreciate your time on this - I know you guys are busy and this is probably an edge case (from an inverted data relationship design)

I will try and mock up a project with the same behavior for you. I don't mind sending you the original code, but I have to go back a couple of versions (I since iterated away the issue using an alternative structure). If I fail with the mock-up, I will try pull out the version with issues.

**Comment by rowanmiller** [comment] 2015-10-19 16:13
@brianro sounds good

**Comment by rowanmiller** [comment] 2015-10-27 16:39
Closing this out as we have not heard back with details to reproduce. Feel free to re-open or open a new issue if you have a chance to put it together.

**Comment by brianro** [comment] 2015-10-29 22:44
Rowan – please find the demo file attached. One test case will create and populate the DB. You will see that any test using the relationship ab fails.

**Comment by smitpatel** [comment] 2015-10-29 23:51
from the exception message and query written above, `.Include(a => a.B.C)` is used in the query which is not supported at present.

**Comment by maumar** [comment] 2015-10-30 05:24
@brianro if the code snippet is not too big you can paste it here

**Comment by maumar** [comment] 2015-10-30 05:27
@brianro otherwise feel free to send the sample to me. My address is [my-githib-account-name]At micr0$oft D0t coooom. Please let me know when you get the address so I can delete this message

**Comment by maumar** [comment] 2015-10-30 05:29
@brianro recently I made some fixes in this area, so its possible that this issue (or parts of it) is already fixed. If you have access to the recent nightly you can verify, otherwise I will do it upon receiving the repro code

**Comment by brianro** [comment] 2015-10-30 11:50
@maumar - E-mail sent. Thanks for all your help. I hope there is something there and I didn't just mess up. I appreciate your time. I understand how busy you guys are.

**Comment by maumar** [comment] 2015-11-02 23:20
@brianro this seems to be fixed in the latest bits, most likely fixed by 41ad57ad2f3755c5e35b51d939fab52b489ce738 or c2b01796fbea1aba41c2f7e46f4a55b8b0a44550.

However your tests uncovered a different bug (https://github.com/aspnet/EntityFramework/issues/3633) that has been introduced after beta 8 was released.

**Comment by maumar** [comment] 2015-11-02 23:23
@brianro  with regards to your comment in the test code:

```
            entityA
                .HasOne(p => p.D)
                .WithOne(p => p.A)
                .ForeignKey<A>(p => p.DId); // Why doesn't this work same as "with many"?
```

for one-to-one mapping we use the generic method to determine which side of the relationship is principal and which one is dependent (i.e. which table the foreign key should be located in). In case of one-to-many this is not needed because the many side is always dependent, so the FK will always be there implicitly.

**Comment by brianro** [comment] 2015-11-03 21:01
Regarding the comment - I gave you a poor explanation:
For indicating which "non-shadow" property stores the FK_Id, why does the intellisense / compiler not infer the type of the FK object, same as when we use a WithMany?

 entityA
                .HasOne(p => p.D)
                .WithOne(p => p.A)
                .ForeignKey<A>(p => p.DId); // Why can't the type "A" be inferred same as WithMany?

**Comment by maumar** [comment] 2015-11-04 04:08
Problem with that approach is that it forces a fixed order of declaring navigations (e.g Principal always first, dependent second). This leads to problems for some models. E.g this would work:

customer.HasOne(c=>c.Detail).WithOne().ForeignKey(d=>d.CustomerId)

But if the navigation was from detail to customer, but FK was on detaiil still, we hit a problem

customer.HasOne(/*no nav prop on customer*/).WithOne(/*so this can't be inferred*/)

We tried API where we declare both ends at once, to avoid this but we didn't like it (don't remember what the problem with that one was) so we ended up with what we have now

**Comment by maumar** [comment] 2015-11-04 04:15
With 1-many this is not an issue because FK is always on the dependent, so both cases for one sided navigation work:

Customer.HasMany(c=>c.Orders). WithOne().ForeignKey(/*we know it should be on order*/)

and

Order.HasOne(o=>o.Customer).WithMany().ForeignKey(/*again, we know fk is on order*/)

**Comment by brianro** [comment] 2015-11-04 15:01
So your point is that for one-to-one bi-directional relationships, both entities can be considered the principal entity so:

1.       You can declare the dependency in the principal entity OR

2.       You can declare bi-directional dependencies

 

You guys are WAY more skilled than I am at this, but I am not really sure why these cases would be supported. Feels to me like both would be a bad practice.

 

As always appreciate your time and expertise in this discussion.

 

B.

**Comment by maumar** [comment] 2015-11-05 06:14
Bi-directional relationships (ones that have navigations on both entities pointing to each other) are fine, problem is for uni-directional navigations, like with the example above (detail has navigation to customer but customer doesn't have navigation to detail)

Wrt the second point, we support some scenarios that are not best practices, because some customers are working with existing databases and/or poco objects that they can't control/modify and need the flexibility in order to use EF at all. E.g. we support string keys even though its very often a better idea to use a surrogate int key, but databases use names, emails, credit card numbers etc as their keys sometimes and people are stuck with it.

**Comment by brianro** [comment] 2015-11-05 13:05
Thanks Maurycy,

 

This has been a great educational experience. I definitely learned a lot and appreciate you answering my questions and resolving my issue.

 

B.

**Closed** 2022-10-16 09:12 UTC
