### ISSUE TITLE
Must I use nullable property to determine whether the type is null when left join a IQueryable<anonymous>(sub query, gourp by)?

### ISSUE THREAD

**Issue by ly4236** [dotnet/efcore#28273] opened 2022-06-20 09:18 UTC
updating: yes.
this code will throw "Nullable object must have a value".
```c#
var subQuery= db.A
    .Select(x => new
    {
        x.Id,
        x.BId,
        x.Count
    });
var query = from b in db.B
                from a in subQuery.Where(a => a.BId == b.Id).DefaultIfEmpty()
                select new
                {
                    Id = b.Id,
                    Count = a == null ? 0 : a.Count,
                };
var list = query.ToList();
```
this code can work
```c#
// query
var subQuery= db.A
    .Select(x => new
    {
        x.Id,
        Bid = (Guid?)x.BId,
        x.Count
    });
var query = from b in db.B
                from a in subQuery.Where(a => a.BId == b.Id).DefaultIfEmpty()
                select new
                {
                    Id = b.Id,
                    Count= !a.Bid.HasValue ? 0 : a.Count,
                };
var list = query.ToList();
```

**Comment by ajcvickers** [comment] 2022-06-21 17:06
@smitpatel to look for dupe.

**Comment by smitpatel** [comment] 2022-06-21 17:17
Duplicate of #22517

**Closed by smitpatel** 2022-06-21 17:17 UTC
Labels: closed-duplicate, customer-reported
