### ISSUE TITLE
Data Annotation for [NotMapped] ReadOnly Property

### ISSUE THREAD

**Issue by chris-oswald** [dotnet/efcore#4687] opened 2016-03-02 22:07 UTC
I get a weird nondescript error when I create a read-only property on my model using the Data Annotation syntax.

If I use the fluent syntax to set the property to ignore it works fine.  So it seems to be isolated to the data annotation and the good news is I have a work around.

**Read-Only Property Example**
[NotMapped]
        public DateTimeOffset EstimatedArrivalTime
        {
            get
            {
                return EstimatedDepartureTime.Add(EstimatedTravelTime);
            }
        }

**First Few Lines of StackTrace**
ArgumentNullException: Value cannot be null.
 Parameter name: navigation
Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
Microsoft.Data.Entity.Metadata.Conventions.Internal.ConventionDispatcher.OnNavigationAdded(InternalRelationshipBuilder relationshipBuilder, Navigation navigation)

**Comment by smitpatel** [comment] 2016-03-02 22:15
Possible dupe of #3805
Which version of EF are you using?

**Comment by chris-oswald** [comment] 2016-03-02 22:21
I'm using 7.0.0-rc1-final.  I apologize for the double post.  It does seem to be the same issue I'm seeing.  I looks like you've closed it out on rc2.

**Closed** 2022-10-16 09:31 UTC
