### ISSUE TITLE
Query: error when creating QueryExecutor in async for queries with FirstOrDefault<object> projecting anonymous type when

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#15865] opened 2019-05-30 21:00 UTC
query:

```cs
ctx.Gears.Where(g => g.Rank.HasFlag(MilitaryRank.Corporal))
                    .Select(
                        b => new
                        {
                            hasFlagTrue = b.Rank.HasFlag(MilitaryRank.Corporal),
                            hasFlagFalse = b.Rank.HasFlag(MilitaryRank.Sergeant)
                        })

and then apply FirstOrDefault, where TSource is object
```

can be reproduced by:
Select_enum_has_flag
FirstOrDefault_with_manually_created_groupjoin_is_translated_to_sql
Optional_Navigation_Null_Coalesce_To_Clr_Type

Exception:

```
Expression of type 'System.Threading.Tasks.Task`1[<>f__AnonymousType125`2[System.Boolean,System.Boolean]]' cannot be used for return type 'System.Threading.Tasks.Task`1[System.Object]'

     at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
     at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
     at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
     at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
  D:\git\EntityFrameworkCore\src\EFCore\Query\Pipeline\QueryCompilationContext2.cs(68,0): at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryCompilationContext2.CreateQueryExecutor[TResult](Expression query)
  D:\git\EntityFrameworkCore\src\EFCore\Storage\Database.cs(97,0): at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery2[TResult](Expression query, Boolean async)
  D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(118,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
  D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(151,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
  D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs(84,0): at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
  D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs(59,0): at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
  D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(147,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
  D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\EntityQueryProvider.cs(99,0): at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
  D:\git\EntityFrameworkCore\src\EFCore\EntityFrameworkQueryableExtensions.cs(3099,0): at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
  D:\git\EntityFrameworkCore\src\EFCore\EntityFrameworkQueryableExtensions.cs(3124,0): at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
  D:\git\EntityFrameworkCore\src\EFCore\EntityFrameworkQueryableExtensions.cs(300,0): at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
  D:\git\EntityFrameworkCore\test\EFCore.Specification.Tests\TestUtilities\QueryAsserter.cs(1112,0): at Microsoft.EntityFrameworkCore.TestUtilities.QueryAsserter`1.AssertFirst[TItem1](Func`2 actualQuery, Func`2 expectedQuery, Action`2 asserter, Int32 entryCount, Boolean isAsync)
  D:\git\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\Query\GearsOfWarQuerySqlServerTest.cs(878,0): at Microsoft.EntityFrameworkCore.Query.GearsOfWarQuerySqlServerTest.Select_enum_has_flag(Boolean isAsync)
```

**Comment by smitpatel** [comment] 2019-05-31 18:11
Duplicate of #15535

**Closed** 2022-10-16 14:23 UTC
