### ISSUE TITLE
Generated SQL queries have more than 10 levels of nestings using CASE and violate "SQL Server allows for only 10 levels of nesting in CASE expressions."

### ISSUE THREAD

**Issue by henrikdahl8240** [dotnet/efcore#20134] opened 2020-03-03 08:29 UTC
At https://docs.microsoft.com/en-us/sql/t-sql/language-elements/case-transact-sql?view=sql-server-ver15 it reads: "SQL Server allows for only 10 levels of nesting in CASE expressions.".

SQL Server Profiler shows this expression has been sent by Entity Framework Core 3.1.2:
(beginning of SQL expression)
```sql
exec sp_executesql N'SELECT [l].[ID], [l].[Description], [l].[Discriminator], [l].[DisplayPriority], [l].[Name], [l].[Version], [l].[FolderParentID], [l].[ShopConsortiumID], [t].[ID], [t].[Description], [t].[Discriminator], [t].[DisplayPriority], [t].[Name], [t].[Version], [t].[FolderParentID], [t0].[c], [t0].[ID], [t0].[Version], [t0].[DisplayPriority], [t0].[Name], [t0].[Description], [t0].[IsChecked], [t0].[c0], [t0].[Discriminator], [t0].[FolderID], [t0].[ShopConsortiumID], [t0].[Organization_Number], [t0].[Preferred_For_SupplierRecord], [t0].[Target_ShopID], [t0].[Target_ShopConsortiumID], [t0].[Target_ShopConsortium_SupplierBikeCollectionID], [t0].[Target_Shop_SupplierBikeCollectionID], [t0].[Target_FranchiseProductID], [t0].[Target_FranchiseProductCustomerID], [t0].[Target_FranchiseProductCustomer_SupplierBikeCollectionID], [t0].[Target_FranchiseProductDistributorID], [t0].[Target_FranchiseProductDistributor_SupplierBikeCollectionID], [t0].[Target_FranchiseProduct_SupplierBikeCollectionID], [t0].[c1]
FROM [C].[ShopConsortium_SupplierDataProviderFolders] AS [l]
LEFT JOIN (
    SELECT [l0].[ID], [l0].[Description], [l0].[Discriminator], [l0].[DisplayPriority], [l0].[Name], [l0].[Version], [l0].[FolderParentID]
    FROM [C].[ShopConsortium_SupplierDataProviderFolders] AS [l0]
    WHERE [l0].[Discriminator] = CAST(1 AS tinyint)
) AS [t] ON [l].[ID] = [t].[FolderParentID]
LEFT JOIN (
    SELECT CASE
        WHEN [l1].[Discriminator] = CAST(10 AS tinyint) THEN N''BikeShop.OpenServices.DomainModel.ShopConsortium_SupplierDataProvider__Local__Shop_SupplierBikeCollection''
        ELSE CASE
            WHEN [l1].[Discriminator] = CAST(9 AS tinyint) THEN N''BikeShop.OpenServices.DomainModel.ShopConsortium_SupplierDataProvider__Local__Shop''
            ELSE CASE
                WHEN [l1].[Discriminator] = CAST(8 AS tinyint) THEN N''BikeShop.OpenServices.DomainModel.ShopConsortium_SupplierDataProvider__Local__ShopConsortium_SupplierBikeCollection''
                ELSE CASE
                    WHEN [l1].[Discriminator] = CAST(7 AS tinyint) THEN N''BikeShop.OpenServices.DomainModel.ShopConsortium_SupplierDataProvider__Local__ShopConsortium''
                    ELSE CASE
                        WHEN [l1].[Discriminator] = CAST(6 AS tinyint) THEN N''BikeShop.OpenServices.DomainModel.ShopConsortium_SupplierDataProvider__Local__FranchiseProductCustomer_SupplierBikeCollection''
                        ELSE CASE
                            WHEN [l1].[Discriminator] = CAST(5 AS tinyint) THEN N''BikeShop.OpenServices.DomainModel.ShopConsortium_SupplierDataProvider__Local__FranchiseProductCustomer''
                            ELSE CASE
                                WHEN [l1].[Discriminator] = CAST(4 AS tinyint) THEN N''BikeShop.OpenServices.DomainModel.ShopConsortium_SupplierDataProvider__Local__FranchiseProductDistributor_SupplierBikeCollection''
                                ELSE CASE
                                    WHEN [l1].[Discriminator] = CAST(3 AS tinyint) THEN N''BikeShop.OpenServices.DomainModel.ShopConsortium_SupplierDataProvider__Local__FranchiseProductDistributor''
                                    ELSE CASE
                                        WHEN [l1].[Discriminator] = CAST(2 AS tinyint) THEN N''BikeShop.OpenServices.DomainModel.ShopConsortium_SupplierDataProvider__Local__FranchiseProduct_SupplierBikeCollection''
                                        ELSE CASE
                                            WHEN [l1].[Discriminator] = CAST(1 AS tinyint) THEN N''BikeShop.OpenServices.DomainModel.ShopConsortium_SupplierDataProvider__Local__FranchiseProduct''
                                            ELSE CASE
                                                WHEN CAST(0 AS bit) = CAST(1 AS bit) THEN N''BikeShop.OpenServices.DomainModel.ShopConsortium_SupplierDataProvider__Local''
                                                ELSE CASE
                                                    WHEN [l1].[Discriminator] = CAST(0 AS tinyint) THEN N''BikeShop.OpenServices.DomainModel.ShopConsortium_SupplierDataProvider_Target''
                                                    ELSE N''BikeShop.OpenServices.DomainModel.ShopConsortium_SupplierDataProvider''
                                                END
                                            END
                                        END
                                    END
                                END
                            END
                        END
                    END
                END
            END
        END
    END AS [c], [l1].[ID], [l1].[Version], [l1].[DisplayPriority], [l1].[Name], [l1].[Description], [l1].[IsChecked], CASE
        WHEN [l1].[Discriminator] = CAST(0 AS tinyint) THEN N''Organization_Number''
        ELSE NULL
    END AS [c0], [l1].[Discriminator], [l1].[FolderID], [l1].[ShopConsortiumID], [l1].[Organization_Number], [l1].[Preferred_For_SupplierRecord], [l1].[Target_ShopID], [l1].[Target_ShopConsortiumID], [l1].[Target_ShopConsortium_SupplierBikeCollectionID], [l1].[Target_Shop_SupplierBikeCollectionID], [l1].[Target_FranchiseProductID], [l1].[Target_FranchiseProductCustomerID], [l1].[Target_FranchiseProductCustomer_SupplierBikeCollectionID], [l1].[Target_FranchiseProductDistributorID], [l1].[Target_FranchiseProductDistributor_SupplierBikeCollectionID], [l1].[Target_FranchiseProduct_SupplierBikeCollectionID], CASE
        WHEN CAST(0 AS bit) = CAST(1 AS bit) THEN N''Preferred_For_SupplierRecord''
        ELSE NULL
    END AS [c1]
    FROM [C].[ShopConsortium_SupplierDataProviders] AS [l1]
    WHERE [l1].[Discriminator] IN (CAST(0 AS tinyint), CAST(9 AS tinyint), CAST(7 AS tinyint), CAST(8 AS tinyint), CAST(10 AS tinyint), CAST(1 AS tinyint), CAST(5 AS tinyint), CAST(6 AS tinyint), CAST(3 AS tinyint), CAST(4 AS tinyint), CAST(2 AS tinyint))
) AS [t0] ON [l].[ID] = [t0].[FolderID]
WHERE [l].[Discriminator] IN (CAST(1 AS tinyint), CAST(0 AS tinyint)) AND ([l].[ID] = @__id_0)
ORDER BY [l].[ID], [t].[ID], [t0].[ID]',N'@__id_0 uniqueidentifier',@__id_0='5E9CE128-6788-4FD1-5CCC-08D7BCE56D56'
```
(end of SQL expression)

The generated SQL has more than 10 levels of nested CASE statements so I get this exception:
(beginning of exception)
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Case-udtryk må kun indlejres til niveau 10.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.AspNet.OData.EnableQueryAttribute.SingleOrDefault(IQueryable queryable, IWebApiActionDescriptor actionDescriptor)
   at Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func`2 modelFunction, IWebApiRequestMessage request, Func`2 createQueryOptionFunction)
   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func`2 modelFunction, Func`2 createQueryOptionFunction, Action`1 createResponseAction, Action`3 createErrorAction)
   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext)
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.
<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.
    <InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.
        <InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
(end of exception)
```
If I just remove the nesting in the CASE expression, i.e. I remove "ELSE CASE" and the corresponding "END", it works fine using SQL Server Management Studio.

It could seem like the programmer thought, that there may be only one WHEN per CASE. It is not the case, there may be multiple WHENs.

Therefore my question is: May you stop this nesting and just generate a list of WHENs, so the generated SQL CASE expressions may become valid in this regard and the SQL Statement may execute without problems?

### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET Core 3.1)
Operating system: Windows 10.
IDE: Visual Studio 2019 16.4.5

**Comment by maumar** [comment] 2020-03-03 21:25
possible dupe of #12729

@henrikdahl8240 can you provide us with a linq query that you were using? Want to make sure that this scenario is also covered by the CASE statement improvements we recently added.

**Comment by henrikdahl8240** [comment] 2020-03-03 21:37
May I send it to your e-mail address and not disclose the details publicly?

**Comment by henrikdahl8240** [comment] 2020-03-03 21:38
One more question: Do you offer a nightly build or something like that, which I can try with .NET 3.1, because then I can just try it of course?

**Comment by henrikdahl8240** [comment] 2020-03-03 22:12
I have tweaked the names a bit, so I do not disclose anything.

It is a query for OData 7.3.0 and it goes like this:
`http://localhost/BikeShop.Services/odata-internal/SupplierFolders(5e9ce128-6788-4fd1-5ccc-08d7bce56d56)?$expand=FolderChildren($select=ID,Version,Priority,Name,Description),Contents($select=ID,Version,Priority,Name,Description,IsChecked,BikeShop.OpenServices.DomainModel.Supplier_Target/GlobalID,BikeShop.OpenServices.DomainModel.Supplier__Local/Preferred_PropertyUri_For_MetaData)`

It is the type casts at the end of the expression, which causes the problem.

So, do you think, that it is already fixed? Will it be in 3.1.3, which I guess it will be named? When can we expect 3.1.3, more or less?

**Comment by maumar** [comment] 2020-03-04 01:25
@henrikdahl8240 sure, my email is my github name at microsoft dot com. wrt nightly builds here is the info:
https://github.com/dotnet/aspnetcore/blob/master/docs/DailyBuilds.md.

The fix has not been ported to 3.1.3 so currently its scheduled to be shipped in 5.0 around September. We will take a second look at the issue to see if it meets the bar for patch, since now we have a legitimate customer scenario that hits it.

**Comment by henrikdahl8240** [comment] 2020-03-09 07:40
Perhaps you may reproduce the situation yourself using the solution I mailed you on March 6. 2020 13:46?

The mail details the few steps you should go through.

**Comment by ajcvickers** [comment] 2020-03-15 19:52
Confirmed duplicate of #12729 which we are considering for a patch on 3.1.

**Closed** 2022-10-16 18:14 UTC
Labels: customer-reported
