### ISSUE TITLE
nested Include not working

### ISSUE THREAD

**Issue by mikebridge** [dotnet/efcore#8570] opened 2017-05-23 23:08 UTC
I don't seem to be able to `Include` a secondary object, even with extra Includes:

```c#
    var schools = ctx.Program
                .Include(x => x.School)
                .ThenInclude(x => x.Country)
                .Select(x => x.School)                
                .Include(x => x.Country)
                .ToList();
```

I'm finding that school.Country is not populated in the result.  Am I making an obvious error here?

This is with EF Core 1.1.2 on Windows, using Sql Server 1.1.2

**Comment by maumar** [comment] 2017-05-23 23:17
dupe of #6451, which is fixed in 2.0-preview1

As a workaround, you can try:

```cs
    var schools = ctx.Program
                .Include(x => x.School)
                .ThenInclude(x => x.Country)
                .ToList();
                .Select(x => x.School)                
                .ToList();
```

**Closed** 2022-10-16 11:06 UTC
