### ISSUE TITLE
[3.0] Nullable owned type - exception on update

### ISSUE THREAD

**Issue by sygnowskip** [dotnet/efcore#19044] opened 2019-11-23 18:59 UTC
Hi guys,
there is an issue with nullable owned types in EF Core 3.0. When I'm trying to update value of owned type that have been set to NULL, I'm receiving exception: 
```
System.InvalidOperationException
  HResult=0x80131509
  Message=The entity of type 'Address' is sharing the table 'Candidate' with entities of type 'Candidate', but there is no entity of this type with the same key value that has been marked as 'Added'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.Validate(Dictionary`2 sharedTablesCommandsMap)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.CreateModificationCommands(IList`1 entries, IUpdateAdapter updateAdapter, Func`1 generateParameterName)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.<BatchCommands>d__11.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at EF_Core_OwnedType_Issue.Program.NotWorkingUpdateOnNullOwnedType(DbContextOptions`1 builderOptions) in D:\Projects\EF_Core_OwnedType_Issue\EF_Core_OwnedType_Issue\Program.cs:line 52
   at EF_Core_OwnedType_Issue.Program.Main(String[] args) in D:\Projects\EF_Core_OwnedType_Issue\EF_Core_OwnedType_Issue\Program.cs:line 23

```

Class definition / mapping:
```
public class Candidate
{
    public long Id { get; set; }
    public string FirstName { get; set; }
    public Address Address { get; set; }
}

public class Address
{
    public string Street { get; set; }
    public string PostalCode { get; set; }
}

public class CandidateConfig : IEntityTypeConfiguration<Candidate>
{
    public void Configure(EntityTypeBuilder<Candidate> builder)
    {
        builder.ToTable(nameof(Candidate));

        builder.HasKey(c => c.Id);
        builder.Property(c => c.Id).UseIdentityColumn();

        builder.Property(c => c.FirstName);

        builder.OwnsOne(c => c.Address,
        navigationBuilder =>
        {
            navigationBuilder.Property(e => e.Street).HasColumnName(nameof(Address.Street));
            navigationBuilder.Property(e => e.PostalCode).HasColumnName(nameof(Address.PostalCode));
        });
    }
}
```

Execution code (updating an entity, that was previously saved with a null value in owned type):
```
long? candidateId = null;
using (var dbContext = new CandidateDbContext(builderOptions))
{
    var candidate = new Candidate()
    {
        FirstName = "FirstName"
    };

    dbContext.Add(candidate);
    dbContext.SaveChanges();
    candidateId = candidate.Id;
}

using (var dbContext = new CandidateDbContext(builderOptions))
{
    var candidate = dbContext.Candidates.SingleOrDefault(c => c.Id == candidateId);

    if (candidate != null)
    {
        candidate.Address = new Address()
        {
            Street = "Street2",
            PostalCode = "Postal2"
        };
        dbContext.SaveChanges();
    }
}
```

Here is example console application with this issue:
https://github.com/sygnowskip/EF_Core_OwnedType_Issue

How to solve this issue? 😃 

### Further technical details

EF Core version: 3.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by sygnowskip** [comment] 2019-11-25 08:18
Use cases for _OwnsOne_:
* NULL, SaveChanges(), { Value }, SaveChanges() -> Exception

> The entity of type 'Address' is sharing the table 'Candidate' with entities of type 'Candidate', but there is no entity of this type with the same key value that has been marked as 'Added'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values.

* { Value }, SaveChanges(), { Value }, SaveChanges() -> OK
* { Value }, SaveChanges(), NULL, SaveChanges() -> Exception

>  The entity of type 'Address' is sharing the table 'Candidate' with entities of type 'Candidate', but there is no entity of this type with the same key value that has been marked as 'Deleted'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values.

**Comment by ajcvickers** [comment] 2019-11-25 20:01
Duplicate of #17422

**Comment by sygnowskip** [comment] 2019-11-25 20:28
Workaround described here: https://github.com/aspnet/EntityFrameworkCore/issues/17422#issuecomment-558325838 😃

**Closed** 2022-10-16 14:58 UTC
Labels: closed-duplicate, customer-reported
