### ISSUE TITLE
Problem with optional foreign keys

### ISSUE THREAD

**Issue by MethodSistemas** [dotnet/efcore#30184] opened 2023-01-31 17:45 UTC
### Ask a question
We're having a problem with optional foreign keys, that behavior started when the project was migrated from EFCore 5 to EFCore 7.
We're using the same configurations, but all the tables with optional foreign keys throw this exception.

_"The foreign key column '[KeyId]' has 'integer' values which cannot be compared to the 'integer' values of the associated principal key column '[KeyId]'. To use 'SaveChanges` or 'SaveChangesAsync', foreign key column types must be comparable with principal key column types."_

### Include your code

In the class, the optional foreign key has beem declared like this:
```
    public class Empresa
    { 
        public int EmpresaId { get; set; }
        public int GrupoEconomicoId { get; set; }
        public int? ContabilistaId { get; set; }
        public Contabilista? Contabilista { get; set; }
}
```
In the class referenced by the foreign key:
```
public class Contabilista : GrupoEconomicoEntity, IContabilista
    {
        public int GrupoEconomicoId { get; set; }
        public int ContabilistaId { get; set; }
        public ICollection<Empresa> Empresas { get; private set; } = new HashSet<Empresa>();
}
```

In the Configuration of the principal class we have that:
```
public class EmpresaConfiguration : IEntityTypeConfiguration<Empresa>
    {
        public void Configure(EntityTypeBuilder<Empresa> builder)
        {
            builder.ToTable("Empresa");

            builder.HasKey(e => new { e.GrupoEconomicoId, e.EmpresaId });

            builder.HasOne(e => e.GrupoEconomico).WithMany(e => e.Empresas).HasForeignKey(e => e.GrupoEconomicoId);

            builder.HasOne(e => e.Contabilista).WithMany(e => e.Empresas).HasForeignKey(e => new { e.GrupoEconomicoId, e.ContabilistaId });

            builder.Property(e => e.EmpresaId).ValueGeneratedOnAdd();

            builder.Property(e => e.ContabilistaId).IsNullable();
     }
}
```
Configuration to the referenced table:
```
public class ContabilistaConfiguration : IEntityTypeConfiguration<Contabilista>
    {
        public void Configure(EntityTypeBuilder<Contabilista> builder)
        {
            builder.ToTable("Contabilista");

            builder.HasKey(e => new { e.GrupoEconomicoId, e.ContabilistaId });
    }
}
```

### Include stack traces

The stack trace generated:

```An error occurred while migrating or initializing the database.
System.InvalidOperationException: The foreign key column 'ContabilistaId' has 'integer' values which cannot be compared to the 'integer' values of the associated principal key column 'ContabilistaId'. To use 'SaveChanges` or 'SaveChangesAsync', foreign key column types must be comparable with principal key column types.
   at Microsoft.EntityFrameworkCore.Update.Internal.CompositeRowForeignKeyValueFactory..ctor(IForeignKeyConstraint foreignKey, IValueConverterSelector valueConverterSelector)
   at Microsoft.EntityFrameworkCore.Update.Internal.RowForeignKeyValueFactoryFactory.Create(IForeignKeyConstraint foreignKey)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKeyConstraint.<>c.<GetRowForeignKeyValueFactory>b__28_0(ForeignKeyConstraint constraint)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKeyConstraint.GetRowForeignKeyValueFactory()
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.AddForeignKeyEdges(Multigraph`2 commandGraph)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.TopologicalSort(IEnumerable`1 commands)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.BatchCommands(IList`1 entries, IUpdateAdapter updateAdapter)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__107_0(DbContext _, ValueTuple`2 t)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Simge.Data.DatabaseInitializer.InicializarEmpresas() in C:\Users\NoteDev-001\Documents\GitHub\SGM\backend\src\Simge.Data\DatabaseInitializer.cs:line 194
   at Simge.Data.DatabaseInitializer.Initialize(MethodDbContext context, IQueryUtilities queryUtilities) in C:\Users\NoteDev-001\Documents\GitHub\SGM\backend\src\Simge.Data\DatabaseInitializer.cs:line 42
   at Program.<Main>$(String[] args) in C:\Users\NoteDev-001\Documents\GitHub\SGM\backend\src\AspNet70\Program.cs:line 259
```

### Include provider and version information

EF Core version: 7.0.2
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 7.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.4.4

**Comment by MethodSistemas** [comment] 2023-02-01 12:27
### UPDATE
Our method (isNullable) conflicts with configuration:

`
        public static PropertyBuilder<int?> IsNullable(this PropertyBuilder<int?> builder)
        {
            return builder.HasConversion(v => v == 0 ? null : v, v => v ?? 0).IsRequired(false);
        }
`
Removing the method from the property it's works.

`
//error
builder.Property(e => e.ContabilistaId).IsNullable();

//works
builder.Property(e => e.ContabilistaId);
`

**Comment by ajcvickers** [comment] 2023-02-01 20:56
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-02-15 12:19
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-02-15 12:19 UTC
Labels: customer-reported
