### ISSUE TITLE
Critical issue using EF Core on UWP (unable to open database file)

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#6130] opened 2016-07-21 19:58 UTC
**Steps to reproduce**

Follow this simple [tutorial](https://docs.efproject.net/en/latest/platforms/uwp/getting-started.html).

**The issue**

Start the app either in Debug or Release.

An exception occurs with db.Database.Migrate();.

_Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll. Additional information: SQLite Error 14: 'unable to open database file'._

This is the very first step, Migrate() method should create the database if there is not any yet (it also fails with db.Database.EnsureCreated()).

**Further technical details**

EF Core Tools version: 1.0.0-preview2-final

EF Core Sqlite version: 1.0.0

UniversalWindowsPlatform version: 5.2.2

Operating system: Windows 10 (UWP)

Visual Studio version: VS 2015 Update 3

**Comment by natemcmaster** [comment] 2016-07-21 21:36
@bbougot can you zip up and share a project that reproduces the issue?

**Comment by bbougot** [comment] 2016-07-21 22:09
[WindowsApp1.zip](https://github.com/aspnet/EntityFramework/files/377081/WindowsApp1.zip)

Simply tick every thing in Exception Window and launch in Release using .NET Native Toolchain.

**Comment by natemcmaster** [comment] 2016-07-21 22:46
I believe this is a duplicate of https://github.com/aspnet/EntityFramework/issues/5386#issuecomment-220089390. @bbougot although the exception is thrown, it doesn't actually represent a bug as EF Core handles this and continues execution normally.

**Comment by bbougot** [comment] 2016-07-22 06:45
Yes this is exactly the same issue. Although it does not crash the app, it's a weird issue, which leads to a misinterpretation (the database is created anyway).

**Comment by natemcmaster** [comment] 2016-07-22 15:27
Closing as a duplicate of #5386

**Closed** 2022-10-16 09:51 UTC
Labels: closed-duplicate
