### ISSUE TITLE
Issue with EFScaffoldModelStage and entity named Module

### ISSUE THREAD

**Issue by rzurlo** [dotnet/efcore#35304] opened 2024-12-10 10:57 UTC
Hi,

When I set EFScaffoldModelStage to publish or build for compiling/optimizing the context model, I encounter the following error related to an entity named Module:

.\Easyone.Plm.Data\obj\Release\net9.0\ModuleEntityType.g.cs(29,24): error CS0104: 'Module' è un riferimento ambiguo tra 'Easyone.Plm.Data.Models.Module' e 'System.Reflection.Module'

If I set EFScaffoldModelStage to none, the error disappears.

Could you help me resolve this issue?

Thanks

EF Core version: (9.0)
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (NET 9.0)
Operating system: Windows 11
IDE: (e.g. Visual Studio 2022 17.12.3)

**Comment by ajcvickers** [comment] 2024-12-11 11:41
Duplicate of #27203

**Comment by AndriySvyryd** [comment] 2024-12-11 23:03
The workaround is described in https://github.com/dotnet/efcore/issues/25523#issuecomment-902836615

**Closed by AndriySvyryd** 2024-12-11 23:03 UTC
Labels: customer-reported
