### ISSUE TITLE
EF 7 and SQLite - compiler error CS1061

### ISSUE THREAD

**Issue by mguinness** [dotnet/efcore#3779] opened 2015-11-18 00:28 UTC
I'm getting the following compiler error with EntityFramework.SQLite.Design dependency:

```
DNX,Version=v4.5.1 error CS1061: 'EntityFrameworkServicesBuilder' does not contain a definition for 'AddSqlite' and no extension method 'AddSqlite' accepting a first argument of type 'EntityFrameworkServicesBuilder' could be found.
```

I previously raised the issue over in SO and was asked to post the issue in GH with a repro:

http://stackoverflow.com/questions/33750255/asp-net-5-ef-7-and-sqlite-compiler-error-cs1061

[WebApplication3.docx (rename to zip)](https://github.com/aspnet/EntityFramework/files/37353/WebApplication3.docx)

**Comment by natemcmaster** [comment] 2015-11-18 16:50
There is a bug in DNX with case-sensitive package names. If you replace ` "EntityFramework.SQLite"` with `"EntityFramework.Sqlite"`, does this fix the issue?

**Comment by natemcmaster** [comment] 2015-11-18 17:05
Possible duplicate of https://github.com/dotnet/cli/issues/236

**Comment by mguinness** [comment] 2015-11-18 18:35
@natemcmaster - yes that worked, thanks!

**Closed** 2022-10-16 09:16 UTC
