### ISSUE TITLE
Tracking API issue: modified collection contains already detached elements

### ISSUE THREAD

**Issue by rpokrovskij** [dotnet/efcore#7253] opened 2016-12-15 13:53 UTC
0. Get record `parentRecord`. with relation  ParentRecordHierarchyRecordMap

```
var parentRecord = dbContext.ParentRecords
                    .Include(e=>e.ParentRecordHierarchyRecordMap)
                    .ThenInclude(e=>e.HierarchyRecord).First(e => e.FieldA == "1_A");

```
1. Detach some relation entities

```
var only2 = parentRecord.ParentRecordHierarchyRecordMap.Take(2).ToList();
                var count2 = only2.Count(); // 2
                foreach (var map in only2)
                {
                    dbContext.Entry(map).State = EntityState.Detached;
                }
```

2. Load collection using tracking API.

```
EntityEntry<ParentRecord> entry = dbContext.Entry(parentRecord);
var col = entry.Collection(e => e.ParentRecordHierarchyRecordMap);
col.Load();

```

3. Modify collection through:

```
var oldRelations = parentRecord.ParentRecordHierarchyRecordMap;
                var tmp = new List<ParentRecordHierarchyRecord>();
                foreach (var e1 in oldRelations)
                    if (!only2.Any(e2 => e1.HierarchyRecordId == e2.HierarchyRecordId))
                        tmp.Add(e1);
                foreach (var e in tmp)
                    oldRelations.Remove(e);
```

4. dbContext.SaveChanges();
5. get parentRecord (using the same dbContext) including ParentRecordHierarchyRecordMap
6. get parentRecord.ParentRecordHierarchyRecordMap count

dbContext.SaveChanges();

```
                var parentRecord2 = dbContext.ParentRecords
                    .Include(e => e.ParentRecordHierarchyRecordMap)
                    .ThenInclude(e => e.HierarchyRecord).First(e => e.FieldA == "1_A");

                var count3 = parentRecord2.ParentRecordHierarchyRecordMap.Count();

                if (count3 != 2)
                    throw new ApplicationException("Tracking error");
```

**Expected result:** the state that is in DB (2 records, all other were deleted)

**Actual result:** records are doubled. e.g. if you have 2 records in db, count will be equal 4 (and collection will include those 2 records twice)

Here it is a code: 

[EfCoreTest.zip](https://github.com/aspnet/EntityFramework/files/654795/EfCoreTest.zip)
 
To start: modify connection string in app.config. sql server required. test app will create a database if it is not exists, and reset data each restart.

**Comment by ajcvickers** [comment] 2016-12-20 00:05
@rpokrovskij As far as I can tell everything is working as designed. I suspect there are some expectations that don't align, so I'll try walking through the code describing what happens.

```C#
var parentRecord = dbContext.ParentRecords
    .Include(e=>e.ParentRecordHierarchyRecordMap)
    .ThenInclude(e=>e.HierarchyRecord).First(e => e.FieldA == "1_A");
```
At this point parentRecord.ParentRecordHierarchyRecordMap contains all five related entities.

```C#
var count1 = parentRecord.ParentRecordHierarchyRecordMap.Count(); // 5
var only2 = parentRecord.ParentRecordHierarchyRecordMap.Take(2);
var count2 = only2.Count(); // 2
foreach (var map in only2)
{
    dbContext.Entry(map).State = EntityState.Detached;
}
```
This code marks two of the entities as detached. Note that they are still in the collection--detaching entities does not sever relationships between entities since that causes issues for common scenarios where detaching is used. So now the collection contains three tracked entities and two that are detached and are therefore being ignored by the context.

```C#
EntityEntry<ParentRecord> entry = dbContext.Entry(parentRecord);
var col = entry.Collection(e => e.ParentRecordHierarchyRecordMap);
col.Load();
```
This does nothing because the collection is already marked as loaded. If the intention is to reload related entities, then set IsLoaded to false before calling Load.

```C#
var oldRelations = parentRecord.ParentRecordHierarchyRecordMap;
```

oldRelations is now a reference to the navigation collection, currently holding the three tracked and two untracked entities.

```C#
var tmp = new List<ParentRecordHierarchyRecord>();
foreach (var e1 in oldRelations)
    if (!only2.Any(e2 => e1.HierarchyRecordId == e2.HierarchyRecordId))
        tmp.Add(e1);
```
At this point, tmp contains the three entities that are still being tracked.

```C#
foreach (var e in tmp)
    oldRelations.Remove(e);
```
The three tracked entities are removed from the collection. When SaveChanges is called this will result in the entities being marked for deletion and removed from the database.

```C#
foreach (var e1 in only2)
    if (!oldRelations.Any(e2 => e1.HierarchyRecordId == e2.HierarchyRecordId))
        oldRelations.Add(e1);
```
only2 is re-evaluated over the collection navigation property, which is now also referenced by oldRelations. If either of the two entities returned are not in oldRelations, then there are added to oldRelations. However, both entities must be in oldRelations because only2 is getting its entities from oldRelations. So this code ultimately does nothing.

```C#
dbContext.SaveChanges();
```
The three tracked entities that were removed from the collection are now deleted in the database.

```C#
var parentRecord2 = dbContext.ParentRecords
    .Include(e => e.ParentRecordHierarchyRecordMap)
    .ThenInclude(e => e.HierarchyRecord).First(e => e.FieldA == "1_A");
```
parentRecord2 is now the same object as parentRecord because it is being tracked and the context is doing identity resolution on the query. ParentRecordHierarchyRecordMap therefore still contains the two untracked entities that were detached at the beginning. It also contains copies of these entities because they still exist in the database and hence new instances are created--identity resolution does not happen here because the original two entities are not being tracked and so are ignored.

```C#
var count3 = parentRecord2.ParentRecordHierarchyRecordMap.Count();

if (count3 != 2)
    throw new ApplicationException("Tracking error");
```
Count is four because the collection contains the two untracked entities and the two tracked entities.

Hopefully this helps explains what is going on.

**Comment by rpokrovskij** [comment] 2016-12-20 09:48
> parentRecord2 is now the same object as parentRecord because it is being tracked and the context is doing identity resolution on the query

It is the same object, but that doesn't mean that tracker just search it in cache and return it. What I see EF goes to db for a data:

```
var parentRecord2 = dbContext.ParentRecords
    .Include(e => e.ParentRecordHierarchyRecordMap)
    .ThenInclude(e => e.HierarchyRecord).First(e => e.FieldA == "1_A");
```

EF Core executes:

```

SELECT TOP(1) [e].[ParentRecordId], [e].[FieldA], [e].[FieldB1], [e].[FieldB2], [e].[FieldCA], [e].[FieldCB1], [e].[FieldCB2], [e].[FieldNotNull]
FROM [tst].[ParentRecords] AS [e]
WHERE [e].[FieldA] = N'1_A'
ORDER BY [e].[ParentRecordId] ; 

SELECT [p].[ParentRecordId], [p].[HierarchyRecordId], [h].[HierarchyRecordId], [h].[HierarchyRecordTitle], [h].[ParentHierarchyRecordId]
FROM [tst].[ParentRecordHierarchyRecordMap] AS [p]
INNER JOIN (
    SELECT DISTINCT TOP(1) [e].[ParentRecordId]
    FROM [tst].[ParentRecords] AS [e]
    WHERE [e].[FieldA] = N'1_A'
    ORDER BY [e].[ParentRecordId]
) AS [e0] ON [p].[ParentRecordId] = [e0].[ParentRecordId]
INNER JOIN [tst].[HierarchyRecords] AS [h] ON [p].[HierarchyRecordId] = [h].[HierarchyRecordId]
ORDER BY [e0].[ParentRecordId]
```

So why after that ParentRecordHierarchyRecordMap collection can't be filtered out (remove detached entities, replace with just selected from db)?

Actually I agree with you that applications of "detach" could require exactly the behavior we have - detached should stay in collections. But together I expect that it should continue only till the db operations that request "the last state" of object from db. 

I will test it with EF6 when  I will have a time.

**Comment by rpokrovskij** [comment] 2016-12-20 12:08
As a workaround, method RemoveFromCollections() can be provided:

```
                var only2 = parentRecord.ParentRecordHierarchyRecordMap.Take(2).ToList();
                foreach (var map in only2)
                {
                    dbContext.Entry(map).State = EntityState.Detached;
                    // instead of this (it works)
                    // parentRecord.ParentRecordHierarchyRecordMap.Remove(map);
                    // the more abstract method can be provided
                   dbContext.Entry(map).RemoveFromCollections();
                }
```

**Comment by rpokrovskij** [comment] 2016-12-20 15:00
Know what?
EF6 contains 2 elements. Doesn't contains detached.

Test app:

P.S. I can't understand how quick MS Core and MS EF Core teams are in closing errors...  

[Vse.Ef6Test.zip](https://github.com/aspnet/EntityFramework/files/664003/Vse.Ef6Test.zip)

**Comment by ajcvickers** [comment] 2016-12-20 17:42
@rpokrovskij EF6 shreds relationships between objects when they are detached. It is intentional that EF Core does not do this. EF Core is not intended to be backward compatible with EF6; it is a new code base with new behaviors. What is that you are trying to achieve by detaching the entities?

With regard to the query, all queries on a DbSet are store queries and retrieve data from the database. However, if an entity with the identity in the data returned is already tracked, then the returned data is discarded and the tracked entity is used instead. No attempt it made to update the entity with data from the store. This is true in both EF Core and EF6. This is why parentRecord2 is the same object as parentRecord.

**Comment by rpokrovskij** [comment] 2016-12-20 18:29
@ajcvickers  OK.  Then you  can just confirm incompatibility issue and promise to add it to incompatibility  list.  EF Core still tracks those incompatibilities as I know. 

Where detach can be used: in every place where you want to serilaize entities in the middle of some process (and eliminate circular references before serializtio: after detach become possible to set a null to navigation properties you do no need). There are other methods to solve it, I know.

**Comment by ajcvickers** [comment] 2016-12-20 18:33
@rpokrovskij I will leave it up to @rowanmiller if/how to document this.

**Comment by divega** [comment] 2016-12-28 02:39
@rpokrovskij just to add to what @ajcvickers already explained:

Setting the `State` property of an entry is an area in which the behavior of EF Core is intentionally different form EF6: 

- In EF6 it was a high priority goal to have the outcome of any public change tracking API be a context and a graph in a consistent state. This was done often at the cost of adding side effects, e.g. detaching an entity (through either the `Detach()` API or setting the state, which were exactly equivalent) all relationships would be severed. Side affects made it difficult or even impossible to write logic that required multiple steps to achieve an outcome. 

- In EF Core we have made an intentional design choice to make setting the `State` property a low-level API that provides you with orthogonal control and no side effects. This enables writing logic that manipulates state that isn't order dependent and requires multiple steps, but it also means that when you write this kind of logic you need to be mindful of leaving the graph and the context in a consistent state.

I will also leave it to @rowanmiller to decide how this difference should be reflected in our documentation.

> Where detach can be used: in every place where you want to serilaize entities in the middle of some process (and eliminate circular references before serializtion: after detach, it is become possible to set a null to navigation properties you don't need). There are other methods to solve it, I know (cloning).

`Detach()` (or setting `State` to `Detached`) in EF6 doesn't make it **possible** to null a navigation property. It **forces all navigation properties to be null**. Perhaps what you have in mind is the idea of producing a graph that is not controlled by a `DbContext` anymore, sort of detaching the whole graph, rather than individual entities?

> P.S. I can't understand why MS Core and MS EF Core teams are so quick in closing issues... I have never felt this with other projects (e.g. NLOG). @ajcvickers may be you can explain what exactly means "closed" status for this issue?

On the EF team we use this issue tracker as the main means to track pending work: any pending work should be represented by an issue and any issue should represent pending work. We tend to close an issue as soon as we arrive to the conclusion that we won't act upon it at any time in the future. E.g. in the case of this issue it is in area that we have discussed before and we have a very firm consensus that we landed on the design we wanted. 

There is of course space to have general discussions (that is what the Discussions milestone is for) that could lead to design changes, especially if we get a lot of feedback on an area, but in general we will tend to close the issue when it is considered by design because we believe that leads to more realistic expectations on what will happen.

**Comment by rpokrovskij** [comment] 2016-12-28 09:25
@divega wrote:

> but it also means that when you write this kind of logic you need to be mindful of leaving the graph and the context in a consistent state.

There "_leaving graph.. in consistent state_" I understand straightforward: means remove detached from navigation properties by yourself; but what could mean "_leaving ... **context** in consistent state_" ? Can you or @rowanmiller  explain it? What we should care after detach ?

**Closed** 2022-10-16 10:46 UTC
Labels: closed-by-design
