### ISSUE TITLE
How to live with query filters added to root elements of inheritance hierarchy only?

### ISSUE THREAD

**Issue by folbo** [dotnet/efcore#33474] opened 2024-04-04 10:52 UTC
I have a multitenant application where every persisted entity must be protected by `TenantId` filter. To accomplish the requirement I created a QueryFilter on each entity in OnModelCreating using some reflection:
```
var entities = modelBuilder.Model
    .GetEntityTypes()
    .Where(x => typeof(BaseEntity).IsAssignableFrom(x.ClrType))
    .Select(entityType => entityType.ClrType);

foreach (var type in entities)
{
    modelBuilder.Entity(type).HasQueryFilter(/* */)
}
```

Note that `BaseEntity` is a base class for all EF entities.

All was fine until I introduced some inherited entities. The relationship looks like this:

```
                           Person
                             /\  
                              | inherits
Company   ----------->    Employee
            has many

```

Got error because query filters can't be applied to a whole inheritance hierarchy:
> System.InvalidOperationException: The filter expression 'entity => {redacted}' cannot be specified for entity type 'Employee'. A filter may only be applied to the root entity type 'Person'.

Okay, let's workaround the problem, right?
```
var entities = modelBuilder.Model
    .GetEntityTypes()
    .Where(x => x.ClrType.BaseType == typeof(BaseEntity))
    .Select(entityType => entityType.ClrType);

foreach (var type in entities)
{
    modelBuilder.Entity(type).HasQueryFilter(/* */)
}
```

Now `entities` contains only _direct_ descendants of `BaseEntity`, so it would be `Company` and `Person` (employee inherits from Person so it won't be included anymore).

Okay, error is gone now, but I get a warning:
> Entity 'Company' has a global query filter defined and is the required end of a relationship with the entity 'Employee'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.

Turns out that entites with query filters that are also required ends of relationships produce warnings if the other end of relationship doesn't have the same query filter.

How can I get rid of the warning if I can't specify a query filter on `Employee` entity (because it is inherited from `Person`)? How can I make sure that my queries for Employees have the TenantId filter applied correctly? Making the relationship optional will remove the warning but will filters be working correctly?

### Include provider and version information

EF Core version: 6.0.26
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Microsoft Windows 10
IDE: Visual Studio 2022 17.7.6

**Comment by stevendarby** [comment] 2024-04-04 11:06
I _think_ you are describing this issue, which was fixed in EF 7.0: https://github.com/dotnet/efcore/issues/26216

**Comment by folbo** [comment] 2024-04-04 11:10
Sounds about right. After reading the issue you linked I assume that this warning is safe to ignore/suppress in this case?

**Comment by stevendarby** [comment] 2024-04-04 11:36
First and foremost I would recommend upgrading to EF 8.0 :)

Otherwise, you can supress the warnings, but I decided not to do this while waiting for the fix as I didn't want to miss any other, genuine filter issues that might have cropped up.

**Comment by SamMonoRT** [comment] 2024-04-04 15:18
Closing issue.

**Closed by SamMonoRT** 2024-04-04 15:18 UTC
Labels: closed-no-further-action, customer-reported

**Comment by roji** [comment] 2024-04-04 15:28
Duplicate of #26216
