### ISSUE TITLE
Include() after Entry(...).State = EntityState.Detached no longer works

### ISSUE THREAD

**Issue by maurei** [dotnet/efcore#18621] opened 2019-10-28 19:01 UTC
Loading a relationship using `Include( .. )` after having performed a `Entry(e).State = EntityState.Detached` no longer works if the targeted relationship has a nullable foreign key.

Small example:
```c#
// TodoItem.cs
public class TodoItem
{
    public int Id { get; set; }
    public Person Assignee { get; set; }
    public int? AssigneeId { get; set; }
}
// Person.cs
public class Person
{
   public int Id { get; set; }
}


// Program.cs
var todo = new TodoItem { Assignee = new Person() };
db.Add(todo);
db.SaveChanges();
db.Entry(todo.Assignee).State = EntityState.Detached;

var reloadedTodo = db.TodoItems.Where(e => e.Id == todo.Id).Include(e => e.Assignee).FirstOrDefault();

result = reloadedTodo.Assignee != null; // is false but should be true
```

The queries are performed by EF core as expected as can be seen from the logs, but the result is not reflected on the navigation property. This seems to be a regression, it worked in v2.1.

I also noticed that setting the entity state to `EntityState.Detached` in the example above now also nulls the navigation property and the foreign key (if present and if not nullable). I don't think this is desirable? Adjusting the entity state should only flag the targeted entity for the change tracker, not update it properties? This might be related to the cause of the problem.

### Steps to reproduce
[I made a reproduction repository](https://github.com/maurei/efcore3-bug).

There's two projects: `before-v3` which demonstrates the involved code in a .net core 2.1 project and where it works fine, and `v3` which has the  same code running in .net core 3 in which it fails

[These](https://github.com/maurei/efcore3-bug/blob/af548fde9cb4d1eae1f73562c9324e81c22d5911/before/Program.cs#L39) and [these](https://github.com/maurei/efcore3-bug/blob/master/after/Program.cs#L39) booleans should all be true, but in the case of nullable reference in v3

### Further technical details
EF Core version: 3.0
Database provider: InMemory, SqlServer
Target framework: 3.0
Operating system: OSX 
IDE: (e.g. Visual Studio for Mac 8.3.4

**Comment by ajcvickers** [comment] 2019-10-28 19:53
Duplicate of #17784. Verified fixed in the current daily builds.

**Comment by maurei** [comment] 2019-10-28 20:54
That issue does not mention anything about the behaviour of `Include( .. )` after detaching entities. I can imagine the issues are related, but is this really the same issue? My guesd would be that EF doing join queries but this not being reflected in the nav props to me would seem to be independent of the changed (but reverted) behaviour of clearing nav props upon a change in `EntityState`? 

 (I haven't checked if inclusion works as expected in the latest daily build)

**Comment by ajcvickers** [comment] 2019-10-28 22:07
@maurei I ran your code against the latest [daily build](https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md) of 3.1 and it works as expected. I believe the issue I linked fixed it by not nulling navigations/FKs. If this isn't the case, then please update your repro code to make it fail with the current 3.1 bits and we will investigate further.

**Comment by maurei** [comment] 2019-10-29 08:29
Confirmed that it it works as expected with  `3.1.0-preview2.19525.5`. Thanks.

**Closed** 2022-10-16 14:52 UTC
Labels: customer-reported
