### ISSUE TITLE
 Please provide an extension method for EF and Linq2DB to have clear join tables such as Inner Join, Left Join, and Right Join.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#32994] opened 2024-02-02 17:21 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/-Please-provide-an-extension-method-for-/10387766)._

---
Please provide an extension method for EF and Linq2DB to have clear join tables such as Inner Join, Left Join, and Right Join. (Please provide EF's extension method to connect tables as clearly as Inner Join, Left Join, and Right Join as Linq2DB.) Like this, (similar to this effect), https://freesql.net/guide/select-multi-table.html, like from c in db.xxxx d from d in db.xxxx2 on c.id equal equals d.id into tmp1,This writing method is not good. (This is not a good way of writing.) )

---
#### Feedback Bot on 6/9/2023, 02:07 AM: 

(private comment, text removed)

**Comment by roji** [comment] 2024-02-02 17:26
Duplicate of #12793

**Closed** 2024-02-08 08:36 UTC
Labels: customer-reported
