### ISSUE TITLE
Mismatch in Count and ToListAsync Results When Using Global Query Filters on Joined Entities

### ISSUE THREAD

**Issue by ArthurMtd** [dotnet/efcore#34810] opened 2024-10-02 08:40 UTC
There is a mismatch between `CountAsync()` and `ToListAsync()` results when using global query filters with joined entities. Below is a minimal reproducible example:

```csharp
// Global query filter applied to Entity2
modelBuilder.Entity<Entity2>()
    .HasQueryFilter(e => !e.IsDeleted);

// Query involving Entity1 and a related Entity2
var query = myContext.Entity1
    .Include(e => e.Entity2)
    .AsQueryable();

var count = await query.CountAsync();
var data = await query.ToListAsync();
```

**Expected Behavior**:  
The `count` value should match the number of records returned by `ToListAsync()`, considering the global query filter applied to `Entity2`.

**Actual Behavior**:  
- `ToListAsync()` correctly excludes records where `Entity2.IsDeleted == true` based on the global query filter.
- However, `CountAsync()` does not account for the global query filter on `Entity2`, resulting in a mismatch between the count and the number of records returned by `ToListAsync()`.

### Include stack traces

No exceptions encountered, just mismatched results.

### Include provider and version information

- **EF Core version**: .NET 8
- **Database provider**: PostgreSQL
- **Target framework**: .NET 8
- **Operating system**: Windows 11
- **IDE**: Visual Studio 2022

---

**Comment by maumar** [comment] 2024-10-02 19:15
this is a known (unintuitive) behavior. It's currently by design, but we have an issue on backlog to address this (https://github.com/dotnet/efcore/issues/29645), as many people are hitting it. 

More info: https://learn.microsoft.com/en-us/ef/core/querying/filters#accessing-entity-with-query-filter-using-required-navigation

dupe of https://github.com/dotnet/efcore/issues/19649

**Closed by maumar** 2024-10-02 19:15 UTC
Labels: customer-reported
