### ISSUE TITLE
Filter records by collection of parameter sets

### ISSUE THREAD

**Issue by hubert-wojtowicz** [dotnet/efcore#20641] opened 2020-04-15 12:29 UTC
I am looking for solution described in more detail here [here](https://stackoverflow.com/questions/61226542/how-to-write-linq-query-retrieving-records-having-parameters-out-of-defined-coll).

What I want to acheive is to generate query like:
```
SELECT *
FROM Entity
WHERE ( SomeId_1 = SomeId AND DateAt_1 = DateAt)
    OR..
    OR (SomeId_N = SomeId AND DateAt_N = DateAt)
```
using LINQ extension methods over `IQuerable<Entity>` interface, for `Entity` having collumns (among others) `SomeId`, `DateAt`.

Lets assume I have:
```
class SomeIdAtPair
{
   public int SomeId { get;set; }
   public DateTime DateAt { get;set; }
}
```
and collection of parameters:
```
var pairs = new List<SomeIdAtPair>
{
    new SomeIdAtPair { ... },
    ...
};
```

Is it possible or will it be possible in **EF Core 3.1+**?

**Comment by smitpatel** [comment] 2020-04-15 12:51
Duplicate of #19070

**Closed** 2022-10-16 18:20 UTC
Labels: closed-duplicate, customer-reported
