### ISSUE TITLE
Scaffolding using "Name" connectionString throws ArgumentNullException (Parameter 'connectionString')

### ISSUE THREAD

**Issue by glacasa** [dotnet/efcore#17827] opened 2019-09-13 08:42 UTC
I scaffold my entities with EF Core 2.2 using the followinf command line : 

`dotnet ef dbcontext scaffold "Name=Default" Microsoft.EntityFrameworkCore.SqlServer`

After updating to EF Core 3.0 preview 9, I now have an exception : 

System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContextGenerator.GenerateClass(IModel model, String contextName, String connectionString, Bo
olean useDataAnnotations, Boolean suppressConnectionStringWarning)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContextGenerator.WriteCode(IModel model, String namespace, String contextName, String connec
tionString, Boolean useDataAnnotations, Boolean suppressConnectionStringWarning)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databas
eOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String out
putContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabas
eNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbC
ontextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean us
eDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Value cannot be null. (Parameter 'connectionString')

### Steps to reproduce

I started an empty aspnet core 3 project, with a default connection string

```XML
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.0.0-preview9.19423.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="3.0.0-preview9.19423.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.0-preview9.19423.6">
      <PrivateAssets>all</PrivateAssets>
      <!-- Remove IncludeAssets to allow compiling against the assembly -->
      <!--<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0-preview9.19423.6" />
  </ItemGroup>

</Project>
```

```json
{
  "ConnectionStrings": {
    "Default": "Data Source=.\\SQLEXPRESS;Initial Catalog=AppDatabase;Integrated Security=True"
  }
}
```

The database is empty.

When I run the command using the named connection string, I have an exception. 

`dotnet ef dbcontext scaffold "Name=Default" Microsoft.EntityFrameworkCore.SqlServer`

If I use the actual connection string, the entities are created

`dotnet ef dbcontext scaffold "Data Source=.\SQLEXPRESS;Initial Catalog=AppDatabase;Integrated Security=True" Microsoft.EntityFrameworkCore.SqlServer`

### Further technical details

EF Core version: 3.0.0-preview9.19423.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: N/A

**Comment by smitpatel** [comment] 2019-09-13 16:21
Duplicate of #17375

**Closed** 2022-10-16 14:42 UTC
Labels: closed-duplicate, customer-reported
