### ISSUE TITLE
EF Scaffold - Strange handling of boolean fields

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#23917] opened 2021-01-18 23:45 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/EF-Scaffold---Strange-handling-of-boolea/1024595)._

---
Steps to reproduce:
Use scaffold command to generate entities.

Scaffold-DbContext "Host=localhost; Port=5432;Database=testdb; Username=postgres; Password=password" Npgsql.EntityFrameworkCore.PostgreSQL -DataAnnotations -OutputDir Models

Expected behavior:
non nullable boolean fields should not be nullable in generated models.

Actual behavior:
some nullable boolean fields are nullable in generated models.

Additional information about the project being scaffolded, such as:
Target framework(s):
.Net Core 3.1

The (PostgreSQL) database has the columns:

"printing_enabled" bool NOT NULL DEFAULT true,
"export_data" bool NOT NULL DEFAULT false

The generated model fields are:

[Required]
[Column("printing_enabled")]
public bool? PrintingEnabled { get; set; }

[Column("export_data")]
public bool ExportData { get; set; }

I'm not sure why both are not marked as Required and why PrintingEnabled is set as nullable?

Link to db script and sample project: https://1drv.ms/u/s!AgH_tMBurHdqii95fqUolVckFnaQ?e=CO7FZi

---
#### Feedback Bot on 5/10/2020, 08:36 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/10/2020, 11:24 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Deep Choudhery [MSFT] on 5/18/2020, 06:10 PM: 

<p>Looking into it. Will reach back soon.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2021-01-19 18:07
Duplicate of #13613.

**Closed** 2022-10-16 19:19 UTC
Labels: customer-reported
