### ISSUE TITLE
Entity framework update 3.1.0 breaknig change

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#21266] opened 2020-06-15 15:14 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1076747/entity-framework-update-310-breaknig-change.html)._

---
The following code works in versions < 3.1.0 of entity framework core but throws a null reference on all versions >= 3.1.0

 queueItems = Entities.HA_AMISYS_CLAIMS_PREPS
                               .Join(Entities.QUEUES, x => x.HA_AMISYS_CLAIMS_PREP_GEN_ID, y => y.RECORD_ID, (Data, Queue) => new { Queue = Queue, Data = (BaseQueueItem)Data })
                               .Where(x => x.Queue.RULEProperty.RULE_ID == rule.RULE_ID && x.Queue.QUEUE_STATUS_ID == QueueStatusNew.QUEUE_STATUS_ID).Skip(0).Take(MAX_RECORDS).ToList();

 I have tried removing Skip or Take and it will not work, however if I remove both it will work but I am unable to limit my records server side.

I get the following error with no inner exception "System.ArgumentNullException: 'Value cannot be null. "

---
#### Brian Riggan on 6/12/2020, 09:12 AM: 

<p>For reference HA_AMISYS_CLAIMS_PREPS inherits from BaseQueueItem. MAX_RECORDS is a constant of 500.</p>

#### Visual Studio Feedback System on 6/15/2020, 00:23 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Brian Riggan solved on 6/15/2020, 06:40 AM, 0 votes: 

<p>Rewriting the query like the following resolves the issue. I am not sure why.</p><p>   queueItems = Entities.QUEUES.Where(x =&gt; x.RULE_ID == rule.RULE_ID && x.QUEUE_STATUS_ID == QueueStatusNew.QUEUE_STATUS_ID).Take(MAX_RECORDS)<br>                                                .Join(Entities.HA_AMISYS_CLAIMS_PREPS, x =&gt; x.RECORD_ID, y =&gt; y.HA_AMISYS_CLAIMS_PREP_GEN_ID, (Queue, Data) =&gt; new { Queue = Queue, Data = (BaseQueueItem)Data }).ToList();      </p>

**Comment by ajcvickers** [comment] 2020-06-15 15:16
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by smitpatel** [comment] 2020-06-15 23:18
> Data = (BaseQueueItem)Data

Causes client evaluation which is possibly throwing at later stage in binding of Skip/Take.

**Comment by ajcvickers** [comment] 2020-06-22 16:12
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:29 UTC
Labels: closed-could-not-reproduce, customer-reported
