### ISSUE TITLE
Distributed Cache as EF Core DbContext Cache

### ISSUE THREAD

**Issue by RebelionTheGrey** [dotnet/efcore#21007] opened 2020-05-21 17:37 UTC
Hello.

I realize my own microservice-based project where I need to use shared tables between different services.
So, of course, I want to use the cache mechanism realized in EF Core now. But, the current EF Core caching mechanism does not allow to use distributed cache (like Redis, for example). And there is no cache synchronization mechanism between different processes in EF Core right now. 
So, will EF Core has a distributed cache mechanism in the future or I should realize my own distributed cache proxy for `IMemoryCache`? The current problem is connected with `CacheEntry` implementations for `ICacheEntry` - there are no default  public realizations of `ICacheEntry` and no public extension methods for realized `ICacheEntry` interface object generation.
Could anyone explain to me the reason for local cache usage implementation and no distributed cache implementation?

Thank you.

**Comment by roji** [comment] 2020-05-21 19:14
> So, of course, I want to use the cache mechanism realized in EF Core now.

Can you explain which exact caching mechanism you're referring to? It seems like you're asking for a "second-level cache" (#5858) but I'm not sure.

**Comment by RebelionTheGrey** [comment] 2020-05-21 20:43
Roij, I'm talking about this one: `public virtual DbContextOptionsBuilder UseMemoryCache([CanBeNullAttribute] IMemoryCache memoryCache);` in `DbContextOptionsBuilder` for method `AddDbContext`

**Comment by smitpatel** [comment] 2020-05-21 21:09
> EF Core has a distributed cache mechanism in the future or I should realize my own distributed cache proxy for IMemoryCache? 

EF Core does not have distributed caching mechanism. It uses `IMemoryCache` registered in service provider for all it's services. Using your own distributed cache proxy for `IMemoryCache` would be right way to go.

**Comment by roji** [comment] 2020-05-21 22:15
As @smitpatel wrote, EF Core uses IMemoryCache internally (e.g. caching SQL of LINQ queries) - this isn't a mechanism for caching results coming from the database.

**Comment by roji** [comment] 2020-05-21 22:15
Duplicate of #5858

**Comment by RebelionTheGrey** [comment] 2020-05-21 22:20
So, where can I read about internal `IMemoryCache` usage? I want to understand what EF Core memory cache is using for? I always thought that memory cache in EF Core uses for result caching.

**Comment by roji** [comment] 2020-05-21 22:25
In general, you shouldn't be too concerned about EF Core's IMemoryCache usage - that is mostly an internal implementation details. Specifically, when you run a LINQ query, EF Core has to "compile" that query from a LINQ expression tree into a SQL command (as well as a compiled shaper to materialize entities out of that command). Since compilation can be quite heavy, caching is employed to make sure that repeated queries bypass it.

**Comment by RebelionTheGrey** [comment] 2020-05-21 22:26
Ah,  I understood, thank you!!

**Closed** 2022-10-16 18:26 UTC
Labels: customer-reported
