### ISSUE TITLE
EFCore 3.0 Preview7 .ThenInclude doesn't resolve on first child of collection

### ISSUE THREAD

**Issue by T3chArmy** [dotnet/efcore#16732] opened 2019-07-24 22:12 UTC
When querying a database table with child relationships, that also has relationships to another table, the first child doesn't resolve their relationships when there are multiple child entries

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore.Views_MessageBoard_ViewThread.ExecuteAsync() in [Redacted]\Intranet\Views\MessageBoard\ViewT
hread.cshtml:line 26
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage pa
ge, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page,
ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContex
t viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionCont
ext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary
tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(Acti
onContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext conte
xt)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultF
ilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task l
astTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExec
utedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter
,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilter
s()
--- End of stack trace from previous location where exception was thrown ---
```

### Steps to reproduce

```c#
public class MessageBoardReply
    {
        [Key]
        public int Id { get; set; }
        public int MessageBoardThreadId { get; set; }
        [ForeignKey("MessageBoardThreadId")]
        public MessageBoardThread MessageBoardThread { get; set; }
        public DateTime Posted { get; set; }
        public string PostedByGuid { get; set; }
        public Employee PostedBy { get; set; }
        public DateTime Edited { get; set; }
        public string EditedByGuid { get; set; }
        public Employee EditedBy { get; set; }
        [Required]
        public string Body { get; set; }
    }
    public class MessageBoardThread
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        public IEnumerable<MessageBoardReply> Replies { get; set; }
        public int OriginalPostId { get; set; }
        public MessageBoardReply OriginalPost { get; set; }
        public int LastReplyId { get; set; }
        public MessageBoardReply LastReply { get; set; }
    }
    public class MessageBoardController : Controller
    {
        public async Task<IActionResult> ViewThread(int id)
        {
            MessageBoardThread thread = await dbContext.MessageBoardThreads
            .Include(t => t.Replies)
                .ThenInclude(r => r.PostedBy)
            .Include(t => t.Replies)
                .ThenInclude(r => r.EditedBy)
            .SingleAsync(t => t.Id == id);

            return View(thread);
        }
    }
```

Line 26 of the view is::
```html
<span class="font-weight-bold">@reply.PostedBy.Name</span><br />
```

Every child of MessageBoardThread.Replies will resolve PostedBy except for element 0/first child of the query when there are multiple MessageBoardReply entries. However, when there is only a single MessageBoardReply in the Replies collection it will resolve the PostedBy value fine.

### Further technical details
EF Core version: 3.0.0-preview7.19362
Database Provider: Microsoft.EntityFrameworkCore.SQLite
Operating system: Windows 10 1903
IDE: (e.g. Visual Studio 2017 15.4) Visual Studio 2019 16.3 Preview 1.0

**Comment by T3charmy** [comment] 2019-07-25 03:06
Just an update as I was looking into why I hadn't run into this previously as I have other similar queries in my code...

if I add `.AsNoTracking()`, the issue goes away.

I added a debugger to figure out why this is happening and this is what happens, nothing in my code modifies the value, so I can only assume this is a bug somewhere in EFCore?

```
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'MainDbContext' started tracking 'MessageBoardReply' entity with key '{Id: 5}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'MainDbContext' started tracking 'Employee' entity with key '{Id: 11}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'MainDbContext' started tracking 'MessageBoardReply' entity with key '{Id: 6}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: The 'MessageBoardReply' entity with key '{Id: 5}' tracked by 'MainDbContext' changed from 'Unchanged' to 'Modified'.
Microsoft.EntityFrameworkCore.Update: Debug: 'MessageBoardReply' entity with key '{Id: 5}' changed to 'Deleted' state due to severed required relationship to parent 'Employee' entity.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: The 'MessageBoardReply' entity with key '{Id: 5}' tracked by 'MainDbContext' changed from 'Modified' to 'Deleted'.
```

**Comment by T3charmy** [comment] 2019-07-25 03:23
Another update:

If I remove `.AsNoTracking()`, and I have a thread with 2 Replies, each having different PostedBy Employee, both replies get linked with their relationship correctly.

If I add a third reply by one of the 2 prior Employees then this is when it breaks. but again it only breaks the prior use of that employee, if I add a 4th reply by the same employee, the third and fourth reply will resolve, however that first initial reply by that user breaks.

If my description of my findings is unclear let me know, and I will try and explain better.

**Comment by ajcvickers** [comment] 2019-07-25 18:22
@T3charmy I attempted to reproduce this, but there is too much missing information. Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by T3charmy** [comment] 2019-07-25 19:44
I am time restricted at the moment, I can try and write an example this weekend.

**Comment by ajcvickers** [comment] 2019-08-02 15:03
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:32 UTC
Labels: closed-could-not-reproduce, customer-reported
