### ISSUE TITLE
Query: Translate GetValueOrDefault over DateTime

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#19266] opened 2019-12-10 22:14 UTC
This require knowledge from TypeMapping what kind of constant literal of DateTime we can generate on server side.

**Comment by roji** [comment] 2023-12-04 07:34
Closing in favor of #22243, which shows a workaround.

**Comment by roji** [comment] 2023-12-04 07:34
Duplicate of #22243

**Closed** 2023-12-04 07:34 UTC
