### ISSUE TITLE
Linq unable to translate if building expression tree with Expression.MemberInit and OrderBy

### ISSUE THREAD

**Issue by wolfywoof** [dotnet/efcore#19802] opened 2020-02-05 06:28 UTC
I use some methods that dynamically generate a lambda expression that I can use in a Select statement or a where statement.

One such method builds an expression similar to:
``` C#
myQuery.Select(myEntity => new EntityDto
{
  PropertyOne = myEntity.ColumnOne,
  PropertyTwo = myEntity.ColumnTwo
});
```
If I use my method to build a select statement and then call a ToList() on the query, it works just fine.
If I use my method to build a select statement and then call an OrderBy before calling a ToList, it is unable to translate the query.

I compared the lambda expression from doing this manually (typing everything out) and using the method to generate it and it is exactly the same.

I can just manually type it out, but it would be nice to know why its not working or if I am doing something wrong.  I made my lambda expression to project into a new class as simple as possible, but it still throws an error if I do an OrderBy after a select.

### Steps to reproduce

``` C#
// Represents an input parameter such as the "input" in "input => input.Property"
var xParameter = Expression.Parameter(typeof(MyEntityClass), "entity");

// Represents declaring a class such as "new MyDto"
var xNew = Expression.New(typeof(MyDto));

// Represents bindings for initialization such as "PropertyOne = 1", will be empty for this test
var bindings = new List<MemberAssignment>();

// Represents instantiating new class, so "new Dto { }
var xInit = Expression.MemberInit(xNew, bindings);

// Generates full lambda expression function "entity => new MyDto { }"
var lambda = Expression.Lambda<Func<MyEntityClass, MyDto>>(xInit, xParameter);

// Use an EF Core 3.1 Context
var myQuery = myContext.MyEntityClass
  // Use lambda to do select
  .Select(lambda);

// This works
var workingResult = myQuery.ToList();

// This fails
var failingResult = myQuery.OrderBy(dto => dto.Id).ToList();

```

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.5

**Comment by smitpatel** [comment] 2020-02-05 16:57
Post a runnable repro code. A slight error in construction of expression can generate very different expression tree which may not be easily visible to eyes.

**Comment by wolfywoof** [comment] 2020-02-05 20:42
I'll try to get something up later tonight. Thanks!

**Comment by ajcvickers** [comment] 2020-02-14 17:26
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:09 UTC
Labels: closed-could-not-reproduce, customer-reported
