### ISSUE TITLE
Full-text search for a word with a prefix/suffix (Prefix/Suffix Term)

### ISSUE THREAD

**Issue by nirav5884** [dotnet/efcore#19734] opened 2020-01-29 04:35 UTC
Is it possible to implement prefix/suffix search in EFCore full text same like below SQL query?
`SELECT Id, Name, Description FROM dbo.Products WHERE CONTAINS (Description, '"*auto*"' )`
The above query returns me all products whose description contains `automatic`, `automobile`, `transmission auto`, `CVT auto transmission`.
But when I apply the same to EF core, it only returns the products whose description contains exact word `auto`, it omits all prefix and suffix characters/words.
```
var searchText = "auto";
searchText = $"\"*{searchText}*\"";
var result1 = _context.Products.Where(f => EF.Functions.FreeText(f.Description, searchText));
var result2 = _context.Products.Where(f => EF.Functions.Contains(f.Description, searchText));
```

**Comment by nirav5884** [comment] 2020-01-31 04:04
Duplicate of #19757

**Comment by ajcvickers** [comment] 2020-01-31 20:17
@nirav5884 Have you tried `searchText = $"*{searchText}*";`

**Comment by nirav5884** [comment] 2020-02-01 05:44
> @nirav5884 Have you tried this?
> 
> ```cs
> searchText = $"*{searchText}*";
> ```

Yes, tried it but no success. 
The EF parameter should be converted to `'"*search text*"'`
Whereas when we pass from c#, it omits the double quote.

**Comment by ajcvickers** [comment] 2020-02-03 20:15
Note for team: SQL generation looks like what is being asked for. Wasn't able to test functionality yet since I only have LocalDb on this machine.

Generated sql for `$"\"*{searchText}*\""`:
```sql
dbug: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[@__searchText_1='"*auto*"' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SELECT [p].[Id], [p].[Description], [p].[Name]
      FROM [Products] AS [p]
      WHERE FREETEXT([p].[Description], @__searchText_1)
```
```sql
dbug: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[@__searchText_1='"*auto*"' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SELECT [p].[Id], [p].[Description], [p].[Name]
      FROM [Products] AS [p]
      WHERE CONTAINS([p].[Description], @__searchText_1)
```

**Comment by ajcvickers** [comment] 2020-02-08 00:09
@nirav5884 Please attach a small, runnable project that reproduces the behavior you are seeing.

**Comment by ajcvickers** [comment] 2020-02-14 17:18
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:08 UTC
Labels: closed-could-not-reproduce, customer-reported
