### ISSUE TITLE
LazyLoadingProxies not loading related entities if the property has a default value

### ISSUE THREAD

**Issue by daniel3303** [dotnet/efcore#22754] opened 2020-09-25 11:57 UTC
## File a bug
When using lazy loading proxies and entities with default values for some relation the lazy loading proxies fail to load the related entities. This happens for EF Core 5.0.0-rc.1.20451.13 but works propertly on EF Core 3.1.x.

### Include your code

This example works both on EF Core 3.1.x and EF Core 5.0.0-rc1
``` C#
public class A  {
        public int Id { get; set; }
        public virtual B Relation { get; set; }
}

public class B  {
        public int Id { get; set; }
}


public IActionResult Test() {
     /* load instance of A from the DbContext with the relation previously set ... */
     Console.WriteLine(a.B.Id); // output: 1
     return Ok();
}

```

This example works only on EF Core 3.1.x

``` C#
public class A  {
        public int Id { get; set; }
        public virtual B Relation { get; set; } = new B();
}

public class B  {
        public int Id { get; set; }
}


public IActionResult Test() {
     /* load instance of A from the DbContext with the relation previously set ... */
     Console.WriteLine(a.B.Id); // output: 1 for EF Core 3.1.x - output: 0 for EF Core 5.0.0-rc1
     return Ok();
}
```

### Include provider and version information

EF Core version: 5.0.0-rc.1.20451.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: macOS Catalina and Windows 10 (happens in both)
IDE: Visual Studio 2019 16.7 and Rider 2020.01 (tested in both)

**Comment by ajcvickers** [comment] 2020-09-28 21:11
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/2693

**Closed** 2022-10-16 19:00 UTC
Labels: customer-reported
