### ISSUE TITLE
Query: OrderBy with subquery evaluates on client

### ISSUE THREAD

**Issue by Tasteful** [dotnet/efcore#10181] opened 2017-10-29 22:30 UTC
When using adding an `.OrderBy` with a subquery the client evaluation warning is thrown. If turning of the client evaluation the query is executed without any sort order.
```
System.InvalidOperationException: Warning as error exception for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning': The LINQ expression 'orderby {from MyTable2 x in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[MemoryUsage.MyTable2]) where ([x].Id == [item].Id) select [x].Name} asc' could not be translated and will be evaluated locally. To suppress this Exception use the DbContextOptionsBuilder.ConfigureWarnings API. ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, TParam arg, Exception exception) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Diagnostics\EventDefinition`.cs:line 71
   at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.QueryClientEvaluationWarning(IDiagnosticsLogger`1 diagnostics, QueryModel queryModel, Object queryModelElement) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore.Relational\Internal\RelationalLoggerExtensions.cs:line 995
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitOrderByClause(OrderByClause orderByClause, QueryModel queryModel, Int32 index) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore.Relational\Query\RelationalQueryModelVisitor.cs:line 1037
   at Remotion.Linq.Clauses.OrderByClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\EntityQueryModelVisitor.cs:line 699
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore.Relational\Query\RelationalQueryModelVisitor.cs:line 268
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\EntityQueryModelVisitor.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 166
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0() in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 103
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 69
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MemoryUsage.Program.Execute() in C:\Git\bugs\MemoryUsage\Program.cs:line 57
   at MemoryUsage.Program.Main(String[] args) in C:\Git\bugs\MemoryUsage\Program.cs:line 21
```

### Steps to reproduce
Project for replication https://github.com/Tasteful/bugs/tree/sortby-expression

### Further technical details
EF Core version: 2.0.1-rtm-207 (also tested with version 1.1.2 and 2.0.0 with the same result)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 (15.4.1)

**Comment by smitpatel** [comment] 2017-10-29 23:49
possibly Duplicate of #7776

**Comment by ajcvickers** [comment] 2017-10-30 19:48
@Tasteful Just to clarify, are you saying that EF reports a client-eval warning for this query, and if this warning is ignored, then the order-by does indeed happen on the client? In other words, the issue is that this is client-evaluated, not that there is some issue with the warning/errors? Assuming that's the case, @maumar will investigate if this is a dupe of #7776.

**Comment by Tasteful** [comment] 2017-10-30 20:27
@ajcvickers  I forgot to have an seed to add some default data so I never got the 1+N selects that I expected. Now when I have the seed that is adding some default data and ignoring the  `options.ConfigureWarnings(w => w.Ignore(RelationalEventId.QueryClientEvaluationWarning))` I got this exception instead. This exception is thrown before the N-selects is starting, SQL Profiler reporting only 1 select executed.
```
System.ArgumentException: At least one object must implement IComparable.
   at System.Collections.Comparer.Compare(Object a, Object b)
   at System.Linq.EnumerableSorter`2.CompareAnyKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.CompareKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__3.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext() in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\Internal\LinqOperatorProvider.cs:line 173
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext() in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\Internal\LinqOperatorProvider.cs:line 137
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MemoryUsage.Program.Execute() in C:\Git\bugs\MemoryUsage\Program.cs:line 67
   at MemoryUsage.Program.Main(String[] args) in C:\Git\bugs\MemoryUsage\Program.cs:line 21
```

So issue is that the subquery can't be used in orderby expression.

**Comment by Tasteful** [comment] 2017-10-30 20:34
Changed 
```
var items = dbContext.MyTable1
                        .OrderBy(item => dbContext.MyTable2.Where(x => x.Id == item.Id).Select(x => x.Name))
                        .ToList();
```
to 
```
var items = dbContext.MyTable1
                        .OrderBy(item => dbContext.MyTable2.Where(x => x.Id == item.Id).Select(x => x.Name).FirstOrDefault())
                        .ToList();
```
with the last `.FirstOrDefault()` and that seems to make the query to work.

**Comment by smitpatel** [comment] 2017-10-30 20:36
That exception is in Linq. Basically trying to sort on something which does not implement IComparable is invalid. e.g. You cannot sort by array.

**Comment by Tasteful** [comment] 2017-10-30 20:58
I updated the example code in the linked repository.

```
var items = dbContext.MyTable1
    .OrderBy(item => dbContext.MyTable2.Where(x => x.Id == item.Id).Select(x => x.Name).FirstOrDefault())
    .ToList();
```
is resulting in correct sql
```
SELECT [item].[Id], [item].[Name]
FROM [MyTable1] AS [item]
ORDER BY (
    SELECT TOP(1) [x].[Name]
    FROM [MyTable2] AS [x]
    WHERE [x].[Id] = [item].[Id]
)
```

If instead using an expression to order the query with
```
Func<MyTable1, object> orderExpression =
    item => dbContext.MyTable2.Where(x => x.Id == item.Id).Select(x => x.Name).FirstOrDefault();

var items = dbContext.MyTable1
    .OrderBy(orderExpression)
    .ToList();
```
is generating the following sql
```
SELECT [m].[Id], [m].[Name]
FROM [MyTable1] AS [m]
go
exec sp_executesql N'SELECT TOP(1) [x].[Name]
FROM [MyTable2] AS [x]
WHERE [x].[Id] = @__item_Id_0',N'@__item_Id_0 int',@__item_Id_0=1
go
exec sp_executesql N'SELECT TOP(1) [x].[Name]
FROM [MyTable2] AS [x]
WHERE [x].[Id] = @__item_Id_0',N'@__item_Id_0 int',@__item_Id_0=2
go
exec sp_executesql N'SELECT TOP(1) [x].[Name]
FROM [MyTable2] AS [x]
WHERE [x].[Id] = @__item_Id_0',N'@__item_Id_0 int',@__item_Id_0=3
go
exec sp_executesql N'SELECT TOP(1) [x].[Name]
FROM [MyTable2] AS [x]
WHERE [x].[Id] = @__item_Id_0',N'@__item_Id_0 int',@__item_Id_0=4
go
exec sp_executesql N'SELECT TOP(1) [x].[Name]
FROM [MyTable2] AS [x]
WHERE [x].[Id] = @__item_Id_0',N'@__item_Id_0 int',@__item_Id_0=5
go
```
even when using 
`options.ConfigureWarnings(w => w.Throw(RelationalEventId.QueryClientEvaluationWarning))`

**Comment by Tasteful** [comment] 2017-10-30 21:09
@smitpatel you are so correct about that, when updated to an expression that was working :)

I will close this issue for the moment and reopen/create a new one when I have found the exact steps that I have in my work application if you not have any good guess about the error that I got there and trying to reproduce in the sample app. Real exception message 
```
Message: System.InvalidOperationException : Warning as error exception for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning': The LINQ expression 'join AnonymousObject _x in {from BaseProductEntity x in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[AppData.BaseProductEntity]) orderby {from FieldDataEntity x in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[AppData.BaseProductEntity+FieldDataEntity]) where ((([x].OwnerId == [x].SystemId) AndAlso ([x].Id == __f_Id_0)) AndAlso (([x].Culture == "*") OrElse ([x].Culture == __culture_Name_1))) orderby [x].Index asc select [x].TextValue => FirstOrDefault()} desc, EF.Property(?[x]?, "SystemId") asc select new AnonymousObject(new [] {Convert(EF.Property(?[x]?, "SystemId")), Convert({from FieldDataEntity x in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[AppData.BaseProductEntity+FieldDataEntity]) where ((([x].OwnerId == [x].SystemId) AndAlso ([x].Id == __f_Id_0)) AndAlso (([x].Culture == "*") OrElse ([x].Culture == __culture_Name_1))) orderby [x].Index asc select [x].TextValue => FirstOrDefault()})}) => Skip(__p_2)} on Property([x.FieldDatas], "OwnerId") equals Convert([_x].GetValue(0))' could not be translated and will be evaluated locally. To suppress this Exception use the DbContextOptionsBuilder.ConfigureWarnings API. ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
```

**Comment by smitpatel** [comment] 2017-10-30 21:11
@Tasteful - With above query, just throw in Include with `FieldDatas` and see if you see the same exception.

**Comment by Tasteful** [comment] 2017-10-30 21:21
@smitpatel I have `.Include(x => x.FieldDatas)` already in the expression. The complete query is built with a lot of expressions that is combined. The code is working with version `EF Core 1.1.2` but after upgrade to `EF Core 2.0.0` I have this issue left. 

I will try to break apart my code and see if I can find the root cause.

**Comment by Tasteful** [comment] 2017-10-31 07:51
Identified the root cause, see #10192

**Comment by zhousht** [comment] 2019-02-15 06:33
I got the same error with this linq,
            var posts = (from c in _context.Posts
                        select new PostsViewModel
                        {
                            Id = c.Id,
                            Title = c.Title,
                            Slug = Common.ToUrlSlug(c.Title)
                        }).AsNoTracking().OrderByDescending(x => x.ModifyTime);

I corrected with this,
            var posts = (from c in _context.Posts
                         .OrderByDescending(x => x.ModifyTime)
                         select new PostsViewModel
                        {
                            Id = c.Id,
                            Title = c.Title,
                            Slug = Common.ToUrlSlug(c.Title)
                        }).AsNoTracking();

How come the compiler didn't caught the error? It could be a compiler bug.

**Closed** 2022-10-16 11:56 UTC
Labels: closed-no-further-action
