### ISSUE TITLE
System.InvalidOperationException: Sequence contains no elements when using .Max() or .MaxAsync()

### ISSUE THREAD

**Issue by neyromant** [dotnet/efcore#10766] opened 2018-01-25 10:33 UTC
I get a strange exception when using the method .Max() or .MaxAsync() if there are no records in the specified table.

```
Exception message:
System.InvalidOperationException: Sequence contains no elements.
Stack trace:
at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.<GetResult>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()
```

### Steps to reproduce
I wrote a query
```c#
var dateTimeMs = await _db.Orders
                .AsNoTracking()
                .Where(r => r.DepartmentId == departmentId)
                .Select(r => r.OperationDate)
                .MaxAsync();
```

It was translated to 
```
Microsoft.EntityFrameworkCore.Database.Command:Debug: Executing DbCommand [Parameters=[@__departmentId_0='?' (Size = 6)], CommandType='Text', CommandTimeout='300']
SELECT MAX("r"."OperationDate")
FROM "public"."Orders" AS "r"
WHERE "r"."DepartmentId" = @__departmentId_0
```

If there are no records in the specified table, I get an exception. 
Although, when I used version 1.1 of EFCore, I got zero

### Further technical details
EF Core version: Microsoft.EntityFrameworkCore 2.0.1
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL 2.0.1
Operating system: CentOs 7.4, Windows 10 
IDE: Visual Studio 2017 15.4

**Comment by ajcvickers** [comment] 2018-01-26 21:57
@neyromant This is a duplicate of #10086, and is by-design. Can you let us know what you expect the return value to be and why?

**Comment by neyromant** [comment] 2018-01-27 06:30
I expect zero, because I choose from the integer column. I'm very surprised, because this worked in ef 1.1.
In any case, thanks!

**Comment by neyromant** [comment] 2018-01-27 06:38
I honestly do not understand why it throws an exception, and does not return nullable.

**Comment by smitpatel** [comment] 2018-01-28 00:16
The behavior EF Core represent is of `Enumerable.Max` and not of SQL. If you are calling max on non-nullable type empty sequence then it throws exception. It would return null of Max is called on a sequence of nullable type.

**Closed** 2022-10-16 12:06 UTC
Labels: closed-duplicate
