### ISSUE TITLE
Filtering data by related entity field

### ISSUE THREAD

**Issue by 007exs** [dotnet/efcore#2030] opened 2015-04-18 10:26 UTC
I try to filter data by related entity field and get the following exception "Sequence contains more than one element". It's on EntityFramework.Core (7.0.0-beta5-12928).

Steps to reproduce in the dev branch:
- Add the following test:
  
  <pre><code> 
  public class IncludeSqlServerTest : IncludeTestBase<NorthwindQuerySqlServerFixture>
  ...
      [Fact]
      public virtual void Where_by_related_entity()
      {
          using (var context = CreateContext())
          {
              var orderDetails
                  = context.Set&#60;Order&#62;()
                      .Include(od => od.Customer)
                      .Where(od => od.Customer.ContactTitle == "Owner")
                      .ToList();
  
              Assert.True(orderDetails.Count > 0);
          }
      }
  </code></pre>

Actual result:

<pre><code> 
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.EntityFramework.Core (7.0.0-beta5-12928).<>c__DisplayClass58_0`1.<BindMemberExpression>b__0(IEnumerable`1 ps, IQuerySource qs) in 
D:\EntityFramework-dev\EntityFramework-dev\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 945
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpressionCore[TResult](MemberExpression memberExpression, IQuerySource 
querySource, Func`3 memberBinder) in D:\EntityFramework-dev\EntityFramework-dev\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 967
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, IQuerySource 
querySource, Func`3 memberBinder) in D:\EntityFramework-dev\EntityFramework-dev\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 942
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, Func`3 memberBinder) in 
D:\EntityFramework-dev\EntityFramework-dev\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 931
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.RequiresMaterializationExpressionTreeVisitor.VisitMemberExpression(MemberExpression 
memberExpression) in D:\EntityFramework-dev\EntityFramework-dev\src\EntityFramework.Core\Query\ExpressionTreeVisitors
\RequiresMaterializationExpressionTreeVisitor.cs:line 46
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression) in D:\EntityFramework-
dev\EntityFramework-dev\src\EntityFramework.Core\Query\ExpressionTreeVisitors\ExpressionTreeVisitorBase.cs:line 13
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitBinaryExpression(BinaryExpression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression) in D:\EntityFramework-
dev\EntityFramework-dev\src\EntityFramework.Core\Query\ExpressionTreeVisitors\ExpressionTreeVisitorBase.cs:line 13
   at Remotion.Linq.Clauses.WhereClause.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel) in D:\EntityFramework-dev\EntityFramework-dev\src
\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 416
   at Microsoft.Data.Entity.Relational.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel) in D:\EntityFramework-dev
\EntityFramework-dev\src\EntityFramework.Relational\Query\RelationalQueryModelVisitor.cs:line 86
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel) in D:\EntityFramework-dev
\EntityFramework-dev\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 94
   at Microsoft.Data.Entity.Relational.RelationalDataStore.CompileQuery[TResult](QueryModel queryModel) in D:\EntityFramework-dev\EntityFramework-
dev\src\EntityFramework.Relational\RelationalDataStore.cs:line 91

Compiling query model: 'from Order od in {value(Microsoft.Data.Entity.Query.EntityQueryable`1
[Microsoft.Data.Entity.FunctionalTests.TestModels.Northwind.Order]) => AnnotateQuery(Include([od].Customer))} where ([od].Customer.ContactTitle == "Owner") select [od]' 

Optimized query model: 'from Order od in value(Microsoft.Data.Entity.Query.EntityQueryable`1
[Microsoft.Data.Entity.FunctionalTests.TestModels.Northwind.Order]) where ([od].Customer.ContactTitle == "Owner") select [od]'
</code></pre>

Ticket #1460 states that this issue was fixed, but it looks like it was not.
Could you please take a look?

**Comment by htuomola** [comment] 2015-05-12 13:20
I also just got the same error, on build 7.0.0-beta5-13026. Actually my query is more complex, with  nested includes, but stack trace seems similar.

```
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<>c__DisplayClass63_0`1.<BindMemberExpression>b__0(IEnumerable`1 ps, IQuerySource qs)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpressionCore[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpression(MemberExpression memberExpression, Action`2 memberBinder)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.RequiresMaterializationExpressionTreeVisitor.VisitMemberExpression(MemberExpression memberExpression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitBinaryExpression(BinaryExpression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression)
   at Remotion.Linq.Clauses.WhereClause.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ProjectionExpressionTreeVisitor.VisitSubQueryExpression(SubQueryExpression subQueryExpression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.DefaultQueryExpressionTreeVisitor.VisitMemberExpression(MemberExpression memberExpression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.DefaultQueryExpressionTreeVisitor.VisitMemberExpression(MemberExpression memberExpression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.DefaultQueryExpressionTreeVisitor.VisitMemberExpression(MemberExpression memberExpression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.DefaultQueryExpressionTreeVisitor.VisitMemberExpression(MemberExpression memberExpression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](T expression, String methodName)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.<>c__DisplayClass6`1.<VisitAndConvert>b__5(T expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollection`1 list, Func`2 visitMethod)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](ReadOnlyCollection`1 expressions, String callerName)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.DefaultQueryExpressionTreeVisitor.VisitMethodCallExpression(MethodCallExpression methodCallExpression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberAssignment(MemberAssignment memberAssigment)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberBinding(MemberBinding memberBinding)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollection`1 list, Func`2 visitMethod)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberBindingList(ReadOnlyCollection`1 expressions)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberInitExpression(MemberInitExpression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ProjectionExpressionTreeVisitor.VisitSubQueryExpression(SubQueryExpression subQueryExpression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberAssignment(MemberAssignment memberAssigment)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberBinding(MemberBinding memberBinding)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollection`1 list, Func`2 visitMethod)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberBindingList(ReadOnlyCollection`1 expressions)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberInitExpression(MemberInitExpression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.InMemory.InMemoryDataStore.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Data.Entity.Query.CompiledQueryCache.CompileQuery(IDataStore dataStore, MethodInfo compileMethodInfo, Type resultItemType, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.CompiledQueryCache.<>c__4`1.<Execute>b__4_0(Expression q, IDataStore ds)
   at Microsoft.Data.Entity.Query.CompiledQueryCache.<>c__DisplayClass7_0.<GetOrAdd>b__0(ICacheSetContext c)
   at Microsoft.Framework.Caching.Memory.CacheExtensions.<>c__DisplayClass7_0`1.<Set>b__0(ICacheSetContext context)
   at Microsoft.Framework.Caching.Memory.MemoryCache.Set(String key, IEntryLink link, Object state, Func`2 create)
   at Microsoft.Framework.Caching.Memory.CacheExtensions.Set(IMemoryCache cache, String key, Object state, Func`2 create)
   at Microsoft.Framework.Caching.Memory.CacheExtensions.Set[T](IMemoryCache cache, String key, Object state, Func`2 create)
   at Microsoft.Framework.Caching.Memory.CacheExtensions.GetOrSet[T](IMemoryCache cache, String key, Object state, Func`2 create)
   at Microsoft.Data.Entity.Query.CompiledQueryCache.GetOrAdd(Expression query, QueryContext queryContext, IDataStore dataStore, Boolean isAsync, Func`3 compiler)
   at Microsoft.Data.Entity.Query.CompiledQueryCache.Execute[TResult](Expression query, IDataStore dataStore, QueryContext queryContext)
   at Microsoft.Data.Entity.Query.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at BusinessLogic.DashboardLogic.GetAllApps() in c:\Workspaces\VSO_discointernal\ITDC\main\source\ITDevCenter\BusinessLogic\DashboardLogic.cs:line 38
   at BusinessLogic.Tests.DashboardLogicTests.GetAllApps_Multiple_Success() in c:\Workspaces\VSO_discointernal\ITDC\main\source\ITDevCenter\BusinessLogic.Tests\DashboardLogicTests.cs:line 117
```

**Comment by anpete** [comment] 2015-05-12 21:36
Dupe of #1543

**Closed** 2022-10-16 08:54 UTC
