### ISSUE TITLE
Computed columns shouldn't require a column in the schema

### ISSUE THREAD

**Issue by rschiefer** [dotnet/efcore#18429] opened 2019-10-17 17:43 UTC
**PROBLEM**:  Currently, computed columns don't work if they aren't defined in the table schema.  Raw SQL doesn't require a column for the computed result.  So we have to artificially change our database schema for EF Core to handle a computed column correctly.

**PROPOSED SOLUTION**:  Support computed columns without a real column on the table.

**Comment by ajcvickers** [comment] 2019-10-18 20:30
@rschiefer It's not 100% clear to me what you mean by "computed columns" here. Could you explain in more detail, preferably showing what you are currently doing in code?

Related: #10768

**Comment by rschiefer** [comment] 2019-10-19 13:17
In my particular use case I'm calculating distance for addresses in the database based on a passed in location. Here is a PR for another repo which is a good example.

https://github.com/scottschluer/geolocation/commit/a3dc84d8636c533b7ab9eaf2c7db0b28ddaa9178

**Comment by ajcvickers** [comment] 2019-10-21 18:51
@rschiefer Can you post an example of a table and the SQL that you would like to run against that table?

**Comment by ajcvickers** [comment] 2019-10-28 16:32
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by rschiefer** [comment] 2019-10-28 16:46
A simplified example of the table would be:

TestCases Table:
x | y |
------
1 | 1 |
1 | 2 |
2 | 1 |
2 | 2 |

SQL: 
SELECT x, y, x * y as [product]
FROM TestCases

SQL Results:

x | y | product |
------
1 | 1 | 1 |
1 | 2 | 2 |
2 | 1 | 2 |
2 | 2 | 4 |

**Comment by rschiefer** [comment] 2019-10-28 17:06
Correct.  The problem is EF won't (at least not that I can figure out) return the calculated result unless you define the column as part of your entity which then requires you to set some default value that is a magic value for null (I'm currently using -1).  

I want: 

- Calculation performed in SQL
- Result returned by EF
- No table schema column on entity table for result column

**Comment by smitpatel** [comment] 2019-10-28 18:40
LINQ: `context.TestCases.Select(t => new { t.x, t.y, product = t.x * t.y });`

**Comment by rschiefer** [comment] 2019-10-28 20:05
I would prefer to bring back my entity class and specify how I want the "calculated" property set:

context.TestCases.Select(t => new TestCase { t.x, t.y, product = t.x * t.y });

**Closed** 2022-10-16 14:50 UTC
Labels: closed-could-not-reproduce, customer-reported
