### ISSUE TITLE
Command Interception

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/efcore#7371] opened 2017-01-06 19:18 UTC
When can we expect the simple command interception to be implemented in EF Core. In its absence, are there any work around of implementation of IsDeleted type of feature in EFCore?

**Comment by divega** [comment] 2017-01-14 00:09
@satyajit-behera we haven't decided if we want to have command interception that looks like the one we did in EF6 but here are a few related things:

- Issue #626 covers all lifecycle hooks which could include some means for command or query interception
- We have been thinking a lot about the concept of filtering applied to a model and `DbContext`, which should make it easier to implement soft-deletes than interception. We are using #7413 to track that. 
- Although it requires using and replacing some of our internal service types, there is already a way to achieve command interception. @ajcvickers could you please point to the test that does this?

**Comment by divega** [comment] 2017-01-14 00:09
Closing as a duplicate of #636 and #7413.

**Comment by satyajit-behera** [comment] 2017-01-14 11:54
@divega Thanks.
@ajcvickers Please let me know how I can achieve this using a different mechanism. Thanks.

**Comment by ajcvickers** [comment] 2017-01-17 18:22
@divega Not sure what you are referring to; I haven't done this in EF Core. I think @anpete might have done something at one point. @satyajit-behera If I was going to start somewhere, I would probably investigate replacing SqlServerConnection, or whatever the RelationalConnection class is for the provider you are targeting.

**Comment by divega** [comment] 2017-01-17 21:32
@ajcvickers ok, I guess I had it mixed up in my notes. @anpete do you know of a test that does service replacement to achieve something similar to command interception? I had this in my notes from triage but it might have been a misunderstanding.

**Comment by anpete** [comment] 2017-01-17 21:38
@divega https://github.com/aspnet/EntityFramework/blob/1145ef9b3dd46a07a84cb04b11141ecc8bfc62d2/test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/BadDataSqliteTest.cs

**Closed** 2022-10-16 10:49 UTC
Labels: closed-duplicate
