### ISSUE TITLE
Migrations, `migrationBuilder.AddColumn` wrong expression generated for model property of type enum

### ISSUE THREAD

**Issue by ahmad-moussawi** [dotnet/efcore#4233] opened 2016-01-06 12:21 UTC
My model is as the following

```
class Transaction {
 public int id {get; set;}
 public Status Status{get;set;}
}

public enum Status {
 None = 0,
 Pending = 1,
 Done = 2
}
```

It will generate the following in the migration file

> **Note:** Off course since it's an AddColumn operation, so this is not the first migration

```
migrationBuilder.AddColumn<int>(
    name: "Status",
    table: "Transaction",
    nullable: false,
    defaultValue: Status.0);
```

Note the `Status.0` instead of `0`

**Comment by smitpatel** [comment] 2016-01-06 15:08
dupe of #4061

**Closed** 2022-10-16 09:23 UTC
