### ISSUE TITLE
Conversion of int[] array with array.Contains(int value) causes Exception|Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '$'. 

### ISSUE THREAD

**Issue by RM-Coyote** [dotnet/efcore#31371] opened 2023-07-28 08:02 UTC
Looks like the way it's generating the sql for a Linq statement when using a int [] Contains(value) has changed. See data from MS SQL profiler below.

Apologies if I'm missing info as first time I've reported an issue!!!
### Include your code

Works with hard coded values rather aOutletIds.Contains(j.JnldOutlet) and works in LinqPad

```C#
                qry =
                (from j in db.Jnldtbls
                 join p in db.Prodtbls on j.JnldProduct equals p.ProdNumber
                 //                              Double?                 string                        Double                  string
                 join c in db.Codetbls on new { x1 = p.ProdCommodity, x2 = "COMMODITY" } equals new { x1 = (Double?)c.CodeKeyNum, x2 = c.CodeKeyType } into t
                 from rt in t.DefaultIfEmpty()
                 where (p.ProdDepartment == 37 && j.JnldStatus == 1 && j.JnldType == "SALE"
                     && ((p.ProdCommodity == 4301) || (p.ProdCommodity == 4001) || (p.ProdCommodity == 4101) || (p.ProdCommodity == 4201) || (p.ProdCommodity == 4302) ||
                         (p.ProdCommodity == 4999) || (p.ProdCommodity == 4401))
                     && p.ProdNumber != 19978
                     && aOutletIds.Contains(j.JnldOutlet)
                     //&& ((j.JnldOutlet == 804) || (j.JnldOutlet == 805) || (j.JnldOutlet == 812) ||
                     //    (j.JnldOutlet == 818) || (j.JnldOutlet == 857) || (j.JnldOutlet == 819))
                     && j.JnldHhmmss >= startTime && j.JnldHhmmss <= endTime && j.JnldYyyymmdd == aYYYYMMDD)
                 orderby j.JnldOutlet, j.JnldProduct, j.JnldYyyymmdd, j.JnldHhmmss
                 select new FuelSalesData()
                 {
                     Yyyymmdd = j.JnldYyyymmdd,
                     Hhmmss = j.JnldHhmmss,
                     Outlet = j.JnldOutlet,
                     Product = Convert.ToInt32(j.JnldProduct.GetValueOrDefault()),
                     Qty = j.JnldQty.GetValueOrDefault(),
                     Amt = (j.JnldAmt.GetValueOrDefault() + j.JnldDiscAmt.GetValueOrDefault()),
                     Cost = j.JnldCost.GetValueOrDefault()
                 }).ToList();
```

### Include stack traces

full exception message from log is.

```
2023-07-28 17:15:10.8167|ERROR|OwnPrice_SalesVolume_FileCreator.MainWindow|Unhandled Exception|Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '$'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OwnPrice_SalesVolume_FileCreator.BackGrdWorker.GetData(Int32 aYYYYMMDD, Int32 aLastRunHour, Int32[] aOutletIds) in E:\DevGitHub\KalibrateUtils\OwnPrice_SalesVolume_FileCreator\OwnPrice_SalesVolume_FileCreator\BackGrdWorker.cs:line 135
   at OwnPrice_SalesVolume_FileCreator.BackGrdWorker.DoWork() in E:\DevGitHub\KalibrateUtils\OwnPrice_SalesVolume_FileCreator\OwnPrice_SalesVolume_FileCreator\BackGrdWorker.cs:line 102
   at OwnPrice_SalesVolume_FileCreator.BackGrdWorker.TestDoWork() in E:\DevGitHub\KalibrateUtils\OwnPrice_SalesVolume_FileCreator\OwnPrice_SalesVolume_FileCreator\BackGrdWorker.cs:line 58
   at OwnPrice_SalesVolume_FileCreator.MainWindow.btnTest_Click(Object sender, RoutedEventArgs e) in E:\DevGitHub\KalibrateUtils\OwnPrice_SalesVolume_FileCreator\OwnPrice_SalesVolume_FileCreator\MainWindow.xaml.cs:line 109
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at OwnPrice_SalesVolume_FileCreator.App.Main()
ClientConnectionId:203435fd-9144-42d8-a303-7f8eb71b628a
Error Number:102,State:1,Class:15
```

Copy of the text data from MS SQL Profiler:

```
For Microsoft.EntityFrameworkCore.SqlServer 8.0.0-preview.6.23329.4:

exec sp_executesql N'SELECT [j].[JNLD_YYYYMMDD] AS [Yyyymmdd], [j].[JNLD_HHMMSS] AS [Hhmmss], [j].[JNLD_OUTLET] AS [Outlet], CONVERT(int, COALESCE([j].[JNLD_PRODUCT], 0.0E0)) AS [Product], 
COALESCE([j].[JNLD_QTY], 0.0E0) AS [Qty], COALESCE([j].[JNLD_AMT], 0.0E0) + COALESCE([j].[JNLD_DISC_AMT], 0.0E0) AS [Amt], COALESCE([j].[JNLD_COST], 0.0E0) AS [Cost]
FROM [JNLDTBL] AS [j]
INNER JOIN [PRODTBL] AS [p] ON [j].[JNLD_PRODUCT] = [p].[PROD_NUMBER]
LEFT JOIN [CODETBL] AS [c] ON [p].[PROD_COMMODITY] = [c].[CODE_KEY_NUM] AND ''COMMODITY'' = [c].[CODE_KEY_TYPE]
WHERE [p].[PROD_DEPARTMENT] = 37.0E0 AND [j].[JNLD_STATUS] = CAST(1 AS smallint) AND [j].[JNLD_TYPE] = ''SALE'' 
  AND [p].[PROD_COMMODITY] IN (4301.0E0, 4001.0E0, 4101.0E0, 4201.0E0, 4302.0E0, 4999.0E0, 4401.0E0) AND [p].[PROD_NUMBER] <> 19978.0E0 
  **AND [j].[JNLD_OUTLET] IN (
    SELECT [a].[value]
    FROM OPENJSON(@__aOutletIds_0) WITH ([value] int ''$'') AS [a]
)** AND [j].[JNLD_HHMMSS] >= @__startTime_1 AND [j].[JNLD_HHMMSS] <= @__endTime_2 AND [j].[JNLD_YYYYMMDD] = @__aYYYYMMDD_3
ORDER BY [j].[JNLD_OUTLET], [j].[JNLD_PRODUCT], [j].[JNLD_YYYYMMDD], [j].[JNLD_HHMMSS]',N'@__aOutletIds_0 nvarchar(4000),@__startTime_1 int,@__endTime_2 int,@__aYYYYMMDD_3 int',@__aOutletIds_0=N'[804,805,812,818,857,819]',@__startTime_1=120000,@__endTime_2=125959,@__aYYYYMMDD_3=20230621


For Microsoft.EntityFrameworkCore.SqlServer 7.0.9:

exec sp_executesql N'SELECT [j].[JNLD_YYYYMMDD] AS [Yyyymmdd], [j].[JNLD_HHMMSS] AS [Hhmmss], [j].[JNLD_OUTLET] AS [Outlet], CONVERT(int, COALESCE([j].[JNLD_PRODUCT], 0.0E0)) AS [Product], 
COALESCE([j].[JNLD_QTY], 0.0E0) AS [Qty], COALESCE([j].[JNLD_AMT], 0.0E0) + COALESCE([j].[JNLD_DISC_AMT], 0.0E0) AS [Amt], COALESCE([j].[JNLD_COST], 0.0E0) AS [Cost]
FROM [JNLDTBL] AS [j]
INNER JOIN [PRODTBL] AS [p] ON [j].[JNLD_PRODUCT] = [p].[PROD_NUMBER]
LEFT JOIN [CODETBL] AS [c] ON [p].[PROD_COMMODITY] = [c].[CODE_KEY_NUM] AND ''COMMODITY'' = [c].[CODE_KEY_TYPE]
WHERE [p].[PROD_DEPARTMENT] = 37.0E0 AND [j].[JNLD_STATUS] = CAST(1 AS smallint) AND [j].[JNLD_TYPE] = ''SALE'' 
  AND [p].[PROD_COMMODITY] IN (4301.0E0, 4001.0E0, 4101.0E0, 4201.0E0, 4302.0E0, 4999.0E0, 4401.0E0) AND [p].[PROD_NUMBER] <> 19978.0E0 
  **AND [j].[JNLD_OUTLET] IN (804, 805, 812, 818, 857, 819)** 
  AND [j].[JNLD_HHMMSS] >= @__startTime_1 AND [j].[JNLD_HHMMSS] <= @__endTime_2 AND [j].[JNLD_YYYYMMDD] = @__aYYYYMMDD_3
ORDER BY [j].[JNLD_OUTLET], [j].[JNLD_PRODUCT], [j].[JNLD_YYYYMMDD], [j].[JNLD_HHMMSS]',N'@__startTime_1 int,@__endTime_2 int,@__aYYYYMMDD_3 int',@__startTime_1=120000,@__endTime_2=125959,@__aYYYYMMDD_3=20230621
```

### Include provider and version information

EF Core version: 8.0.0-preview.6.23329.4 (Works in 7.0.9)
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (NET 6.0)
Operating system: Windows 11 Version 22H2 OS Build 25300.1000
IDE: (Visual Studio 2022 17.6.5)

**Comment by ErikEJ** [comment] 2023-07-28 08:20
Duplicate of #31323 - also see: https://github.com/dotnet/efcore/issues/31362#issuecomment-1652920760

**Comment by roji** [comment] 2023-07-29 08:12
Duplicate of #31323

**Comment by roji** [comment] 2023-07-29 08:13
Note that we have https://github.com/dotnet/EntityFramework.Docs/pull/4428 which adds a breaking change note with all the relevant information - hopefully that will help people avoid this (and if not, at least we can point directly to it).

**Closed** 2023-07-29 08:13 UTC
Labels: customer-reported
