### ISSUE TITLE
 SqlMethods.Like equivalent in EF7

### ISSUE THREAD

**Issue by bearyung** [dotnet/efcore#3325] opened 2015-10-05 16:56 UTC
In EF6, we can perform a SQL LIKE enquiry by writing 

``` c#
SqlMethods.Like(dbProductMaster.ProductName.ToLower(), "%" + searchProductName.ToLower() + "%"))
```

and it will translate to 

``` sql
SELECT * FROM ProductMaster WHERE ProductName LIKE '%xxx%'; 
```

What should I do to perform the same query under EF7?

**Comment by natemcmaster** [comment] 2015-10-05 17:05
In EF7 we translate ".Contains" to "LIKE".

```c#
context.Products.Where(p => p.ProductName.Contains("xxx"))
```

**Comment by roji** [comment] 2015-10-05 17:28
See #2850 for related discussion

**Comment by bearyung** [comment] 2015-10-05 17:32
@natemcmaster Got it, thanks!

@roji so the issue of "Contains provides only a subset of what can be done with SQL LIKE (consider 'a%b%c')" still exist in EF7 beta6? Is there any workaround for that?

**Comment by divega** [comment] 2015-10-05 17:38
Since we don't have something like `EF.Functions.Like()` the best workaround is bootstrap the query with the `FromSql()` method, e.g. something like this:

``` C#
var newMatches = context.Products
    .FromSql("SELECT * FROM Products WHERE Name LIKE @pattern", pattern)
    .Where(p => !p.Discontinued)
    .Select(p => new {p.Id, p.Name});
```

**Comment by bearyung** [comment] 2015-10-05 17:45
@divega Extacly what I need, thanks.

**Comment by rowanmiller** [comment] 2015-10-05 18:07
Closing as dupe of https://github.com/aspnet/EntityFramework/issues/2850

**Comment by dmitry-pavlov** [comment] 2017-09-29 14:25
`EF.Functions.Like()` is here in EF Core 2.0 by the way

**Closed** 2022-10-16 09:11 UTC
