### ISSUE TITLE
Bug in Union, Concat, etc... in EF core

### ISSUE THREAD

**Issue by vlapenkov** [dotnet/efcore#14149] opened 2018-12-12 07:05 UTC
I have two sequences (products) to be united in SQL and then filter by this criteria. In EF6 all worked fine on SQL server
`public IEnumerable<Producer> GetProducersByWheelTypeInSeasonStockItemsForPartnerId(ProductType producttype, WheelType wheelType,string  partnerId)
       {
           var rests = _dbContext.Set<SeasonStockItem>().Select(p => p.ProductId).
               Union(
               _dbContext.Set<SeasonStockItemOfPartner>().Where(p => p.PartnerId == partnerId).Select(p => p.ProductId));

           var query = _dbContext.Set<Product>()
                   .Where(p => rests.Contains(p.ProductId) && p.ProductType == producttype &&
                           p.Producer.Active && p.WheelType == wheelType)
                   .Include(p => p.Producer)
                   .Select(p => p.Producer)
                   .Distinct()
                   .OrderBy(p => p.Name);

           return query.ToArray();        

       }`
But i encountered a bug that this code in EF Core performs thouthands cycles.
I found issue on October 2016. https://github.com/aspnet/EntityFrameworkCore/issues/6812. Since then problem is not resolved. 
Please tell if you are going to bug fix and when.

**Comment by smitpatel** [comment] 2018-12-12 16:24
Duplicate of #6812

**Closed** 2022-10-16 13:43 UTC
Labels: customer-reported
