### ISSUE TITLE
This overload is currently not supported.

### ISSUE THREAD

**Issue by SteffenMangold** [dotnet/efcore#14242] opened 2018-12-23 14:54 UTC
I try to create an extension expression that has no impact on the generated SQL result.
I only want to react in my custom `QueryCompiler` method `public override TResult Execute<TResult>(Expression query)`.

But compiling the query failed. How do I "register" my extension or how to tell to ignore it at the compilation or do I have to rewrite the query befor compilation and remove my custom part?

```
Exception message:
Could not parse expression 'value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Model.AzureSQL.Core.Entities.Inverter]).*****.Where(d => (d.ID == __expectedResult_ID_0)).Cacheable(00:00:05)': This overload of the method 'EntityFrameworkQueryableExtensions.Cacheable' is currently not supported.
```

### Steps to reproduce
I created a custom Expression close to the `AsNotTracking` expression.

```c#
 public class CacheableExpressionNode : ResultOperatorExpressionNodeBase
 { 
 [...]

public class CacheableResultOperator : SequenceTypePreservingResultOperatorBase, IQueryAnnotation
 { 
 [...]

public static class EntityFrameworkQueryableExtensions
    {
        internal static readonly MethodInfo CacheablehMethodInfo
            = typeof(EntityFrameworkQueryableExtensions)
                .GetTypeInfo().GetDeclaredMethod(nameof(Cacheable));

        public static IQueryable<T> Cacheable<T>(this IQueryable<T> source, [NotParameterized] TimeSpan timeToLive)
        {
            Check.NotNull(source, nameof(source));
            Check.NotNull(timeToLive, nameof(timeToLive));

            return
                source.Provider is EntityQueryProvider
                    ? source.Provider.CreateQuery<T>(
                        Expression.Call(
                            instance: null,
                            method: CacheablehMethodInfo.MakeGenericMethod(typeof(T)),
                            arg0: source.Expression,
                            arg1: Expression.Constant(timeToLive)))
                    : source;
        }
    }
```

### Further technical details
Further technical details
EF Core version: 2.2.0
Database Provider: any

**Comment by SteffenMangold** [comment] 2018-12-23 14:56
#14230

**Comment by SteffenMangold** [comment] 2018-12-23 14:57
#14230

**Comment by smitpatel** [comment] 2018-12-23 19:44
If you decide to add custom node in expression tree which you want to be available at compile time then
- Add custom method with ResultOperator like above.
- Add your custom method in the list here https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs so that Relinq can parse it and add it to QueryModel
- Override ResultOperatorHandler if you want to handle it as result operator. If not, then override some other part which would strip off the result operator (like how AsTracking/AsNoTracking) is deal with.

**Comment by SteffenMangold** [comment] 2018-12-23 21:12
@smitpatel thanks!
By "add" you mean override and `ReplaceService` on `DbContextOptionsBuilder`?

**Comment by smitpatel** [comment] 2018-12-23 22:08
Override the service and add additional line like this
https://github.com/aspnet/EntityFrameworkCore/blob/359424adda850025d55e912684df4fa065e23948/src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs#L40-L41

**Comment by SteffenMangold** [comment] 2018-12-23 22:10
Just finished it before a few seconds! It works fantastic now. Thank you very much for your help so long.

**Comment by SteffenMangold** [comment] 2018-12-24 02:06
I also made a Git project out if it. If someone wants to see complete source. [EntityFrameworkCore.Cacheable](https://github.com/SteffenMangold/EntityFrameworkCore.Cacheable)

**Comment by ErikEJ** [comment] 2018-12-24 09:55
Duplication of effort? https://github.com/VahidN/EFSecondLevelCache.Core/

**Comment by SteffenMangold** [comment] 2018-12-24 10:03
> Duplication of effort? https://github.com/VahidN/EFSecondLevelCache.Core/

No. Same usage but way faster and based on more EF Core like implementation.
EFSecondLevelCache.Core uses a `ToSql` implementation to identify queries, that is extremely slow if you hit the cache on a heavy workload. I do not use a reflective monster to identify the query, I intercept the query compiler.

**Comment by ErikEJ** [comment] 2018-12-24 10:19
Good work, Steffen!

**Comment by SteffenMangold** [comment] 2018-12-24 10:43
> Good work, Steffen!

I had to work a little bit more on it to close all TODOs, but after I would love to see it under https://docs.microsoft.com/de-de/ef/core/extensions/
I think it can be really helpful for other developers.

**Comment by ErikEJ** [comment] 2018-12-24 12:35
I plan to update the extension list soon!

**Comment by sdanyliv** [comment] 2018-12-24 18:12
@SteffenMangold, just checked your implementation. It is small but possible chance to hit wrong cache item. Maybe it is better to make key as an object which contain whole expression tree and parameters with cutom equality members. I assume that this can be paranoid check, but who knows ;)

**Comment by SteffenMangold** [comment] 2018-12-24 19:58
@sdanyliv I think the possibility is as high as that MSSQL server is selecting a false query plan. They also using 64bit Hash values. Also if it really happens, I think the result type would not match and throw an exception. But you are right there is indeed a really tiny chance. I'm not sure if it needs to be handled.

**Comment by SteffenMangold** [comment] 2018-12-25 13:47
@smitpatel you mean by replacing the `ExtractParameters` part with a custom visitor that also returns if Cacheable expression is part of the query and cutting it out if so?
Is there a possibility of preventing that a query can contain two calls of my expression? I mean at design time and avoiding throwing an exception at run time.

**Comment by SteffenMangold** [comment] 2018-12-26 21:04
Thank you! Removing query part works perfect.

So for future versions, would it be better to inherit from `MethodCallExpressionNodeBase` or even just build an [extension method like this one](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/EFSecondLevelCache.Core/EFCachedQueryExtensions.cs)? If I understand you correctly there will be no more `ResultOperatorExpressionNodeBase` on next major release.

**Comment by smitpatel** [comment] 2018-12-26 21:15
Just build extension methods on Queryable. And they will be in expression tree as MethodCallExpression. At that point they are same as having `Queryable.Where`, so there shouldn't be any need to inherit from anything (unless I am misunderstanding something).

**Comment by SteffenMangold** [comment] 2018-12-26 21:20
Perfect! Thanks for all you help, it was perfect for a deeper understanding.

**Comment by smitpatel** [comment] 2018-12-28 00:34
This weird code takes care of that. Currently EF Core's query compiler has unwritten contract that result type is always going to IEnumerable so in front end we have such code to call first to get TResult rather than IEnumerable. (Don't worry, we are changing it in 3.0)
https://github.com/aspnet/EntityFrameworkCore/blob/ec3f6f714de2206e0900ea8b482a174a64910f1f/src/EFCore/Query/Internal/QueryCompiler.cs#L118-L163

**Comment by SteffenMangold** [comment] 2018-12-28 00:57
But I call `CompileQueryCore` method that already is calling this `ComipleQueryCore` method.

https://github.com/aspnet/EntityFrameworkCore/blob/ec3f6f714de2206e0900ea8b482a174a64910f1f/src/EFCore/Query/Internal/QueryCompiler.cs#L109-L115

Should it not be executed after that and the result should be the "after-db-call" Enumerable?

**Comment by SteffenMangold** [comment] 2018-12-28 01:20
@smitpatel what every I do (even with crazy reflection code) I can't get the result out of `EnumeratorExceptionInterceptor[MyTyp]`. This underlying type makes it impossible. :(

**Comment by smitpatel** [comment] 2018-12-28 06:50
https://github.com/SteffenMangold/EntityFrameworkCore.Cacheable/blob/b726648b72fbd33e0685fe9f9c1922832c92ff54/EntityFrameworkCore.Cacheable/CustomQueryCompiler.cs#L91
That lines looks spooky. You should not be calling `CreateCompiledQuery` method. If is method which works with `EF.CompileQuery` and not for normal query compilation phase. The correct method to use is `CompileQueryCore` directly. (Notice the difference in Extract parameter args)
I think that would fix the issue of query not being executed. Let me know if you still face any issue.

**Comment by SteffenMangold** [comment] 2018-12-28 10:00
@smitpatel I did not use this method because it is in private. I Just copied it, but it produces the same "before DB" result.

**Comment by SteffenMangold** [comment] 2018-12-28 11:40
OK I think I found the reason...

https://github.com/aspnet/EntityFrameworkCore/blob/ec3f6f714de2206e0900ea8b482a174a64910f1f/src/EFCore/Query/Internal/QueryCompiler.cs#L30

This part is not supposed to return the actual result. It returns an `ExceptionInterceptor ` that is calling the DB only if you call `.ToList(...` for example on the underlying enumerator.

So I think I was right with workaround this to get the actual result.
For notice: for single result queries it work because of a `.First(...` call already happens.

https://github.com/aspnet/EntityFrameworkCore/blob/ec3f6f714de2206e0900ea8b482a174a64910f1f/src/EFCore/Query/Internal/QueryCompiler.cs#L140

**Comment by SteffenMangold** [comment] 2018-12-28 12:38
So I ended up with this solution, which works find for now.

https://github.com/SteffenMangold/EntityFrameworkCore.Cacheable/blob/a80e58d0a151c6b508661f3c4cbf3cd7e6d2b6ea/EntityFrameworkCore.Cacheable/CustomQueryCompiler.cs#L164-L185

**Comment by smitpatel** [comment] 2018-12-28 20:45
@SteffenMangold - I think I understood now what is happening. The issue is EF Core returns result type or IEnumerable. The result type would always execute query and gives back the single result. (the First call) but the `IEnumerable` will execute query only when it is enumerated. In other word, in order to store results of `IEnumerable` in cache, you would actually need to enumerate it. So calling ToList method on it would be one way to do it.

**Closed** 2022-10-16 13:45 UTC
Labels: closed-no-further-action, customer-reported
