### ISSUE TITLE
Microsoft.EntityFrameworkCore.Sqlite 6.0.4

### ISSUE THREAD

**Issue by X-7r3em** [dotnet/efcore#27855] opened 2022-04-21 15:02 UTC
Hello guys. I have a pretty simple bug.

I am using Microsoft.EntityFrameworkCore.Sqlite 6.0.4 in my tests dll. On my windows pc, it runs perfectly.

When I push it trough the CI/CD process to create an image on mcr.microsoft.com/dotnet/aspnet:6.0.4-bullseye-slim-amd64, the container will start, however, when I do a database query, it will throw the exception:
"Could not load file or assembly 'Microsoft.Data.SqlClient, Version=2.0.20168.4, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5'. The system cannot find the file specified."

It seems to be colliding with Microsoft.EntityFrameworkCore.SqlServer 5.0.15 to 6.0.4 -> tested on all of them with the proper matching versions.

Right now, the debian container works, I have commented out the Microsoft.EntityFrameworkCore.Sqlite dependency in the test.csproj and it works. If I active it/uncomment it, it will throw the above mentioned exception.

Microsoft.EntityFrameworkCore.Sqlite: 5.0.15-6.04
Target framework: NET5.0, NET6.0
Operating system: debian

**Comment by roji** [comment] 2022-04-21 16:26
@X-7r3em there's not much we can do without a runnable code sample - it's not possible to investigate the above without that. Also, since things seem to run well locally but fail in CI/CD, I'd recommend giving another close look at exactly what it is you're sending to CI/CD - you may be sending the wrong version in some way (in general there's no reason for something to work locally and not in CI/CD).

**Comment by X-7r3em** [comment] 2022-05-01 08:08
Yeah, no worries. I am 100 percent sure it is not in the CI/CD, as the way I fixed the issue was to change the csproj file, containing the dependency, to stop referencing it when in release configuration. I simply have not had the time to post it, as it is in a company repository.

I will have to create a new project and post it here. The difference I see on my local and dev environment is that on local I am on a windows machine and we start it in debug config. On the dev, we are on linux-64 and release. It a really really nasty bug.

**Comment by AndriySvyryd** [comment] 2022-05-10 16:26
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it. Once we receive a repro project we'll reopen the issue.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:32 UTC
Labels: closed-could-not-reproduce, customer-reported, area-adonet-sqlite
