### ISSUE TITLE
EF Core Add-Migration not detecting DbContext for multilevel hierarchy class inheritance

### ISSUE THREAD

**Issue by Smartware** [dotnet/efcore#8787] opened 2017-06-08 20:27 UTC
Declared an AppDbContext class inheriting from DbContext  as below in a seperate project

```c#
namespace Smarware.Lib
{
    public partial class AppDbContext : DbContext
    {
    }
}

```
The I've a separate project referencing the Smartware.Lib project to inherit AppContext

```c#
namespace WebApp
{
    public class MyMainDbContext: AppDbContext
    {
    }
}
```
When I run EF Add-migration command 

```
No DbContext was found in assembly 'WebApp'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.
```
But when I try to  Inherit directly from DbContext it works fine, like this
namespace WebApp
{
    public class MyMainDbContext: DbContext
    {
    }
}

Which won't work in my case.

This was very possible with EF 6

### Further technical details
EF Core 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows
IDE: Visual Studio 2017

**Comment by smitpatel** [comment] 2017-06-09 00:49
How are you registering your context in service provider?

**Comment by ajcvickers** [comment] 2017-06-16 18:18
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:07 UTC
Labels: closed-could-not-reproduce
