### ISSUE TITLE
ServiceProviderCache throws ExecutionEngineException

### ISSUE THREAD

**Issue by pfaustinopt** [dotnet/efcore#15887] opened 2019-05-31 20:19 UTC
I don't know how to reproduce this error, but sometimes I get an exception with the following stack trace (I think it happens when the IIS is recycled, e.g. changing the web.config):

```
[[PrestubMethodFrame] (Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache..ctor)] Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache..ctor()
--
Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache..cctor()+1f
[[GCFrame]]
[[HelperMethodFrame]]
Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.get_Instance()+f
Microsoft.EntityFrameworkCore.DbContext..ctor(Microsoft.EntityFrameworkCore.DbContextOptions)+5a
MedicineOneServices.Data.Context.BaseDbContext`1[[System.__Canon, mscorlib]]..ctor(Microsoft.EntityFrameworkCore.DbContextOptions`1)+31
MedicineOneServices.Data.Context.Agenda.AgendaContext..ctor(Microsoft.EntityFrameworkCore.DbContextOptions`1)+30
MedicineOneServices.Data.Infrastructure.DatabaseFactory..ctor()+82
DynamicClass.lambda_method(System.Runtime.CompilerServices.Closure, System.Object[])+2a
Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()+d5
Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(Autofac.IComponentContext, System.Collections.Generic.IEnumerable`1)+f6
Autofac.Core.Resolving.InstanceLookup.Activate(System.Collections.Generic.IEnumerable`1, System.Object ByRef)+68
Autofac.Core.Resolving.InstanceLookup+<>c__DisplayClass6_0.b__0()+12
Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(System.Guid, System.Func`1)+cf
Autofac.Core.Resolving.InstanceLookup.Execute()+92
Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(Autofac.Core.ISharingLifetimeScope, Autofac.Core.IComponentRegistration, System.Collections.Generic.IEnumerable`1)+b0
Autofac.Core.Resolving.InstanceLookup.ResolveComponent(Autofac.Core.IComponentRegistration, System.Collections.Generic.IEnumerable`1)+19
Autofac.Core.Activators.Reflection.AutowiringParameter+<>c__DisplayClass0_0.b__0()+1a
Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()+5f
Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(Autofac.IComponentContext, System.Collections.Generic.IEnumerable`1)+f6
Autofac.Core.Resolving.InstanceLookup.Activate(System.Collections.Generic.IEnumerable`1, System.Object ByRef)+68
Autofac.Core.Resolving.InstanceLookup.Execute()+a6
Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(Autofac.Core.ISharingLifetimeScope, Autofac.Core.IComponentRegistration, System.Collections.Generic.IEnumerable`1)+b0
Autofac.Core.Resolving.InstanceLookup.ResolveComponent(Autofac.Core.IComponentRegistration, System.Collections.Generic.IEnumerable`1)+19
Autofac.Core.Activators.Reflection.AutowiringParameter+<>c__DisplayClass0_0.b__0()+1a
Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()+5f
Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(Autofac.IComponentContext, System.Collections.Generic.IEnumerable`1)+f6
Autofac.Core.Resolving.InstanceLookup.Activate(System.Collections.Generic.IEnumerable`1, System.Object ByRef)+68
Autofac.Core.Resolving.InstanceLookup.Execute()+a6
Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(Autofac.Core.ISharingLifetimeScope, Autofac.Core.IComponentRegistration, System.Collections.Generic.IEnumerable`1)+b0
Autofac.Core.Resolving.ResolveOperation.Execute(Autofac.Core.IComponentRegistration, System.Collections.Generic.IEnumerable`1)+2d
Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(Autofac.Core.IComponentRegistration, System.Collections.Generic.IEnumerable`1)+75
Autofac.ResolutionExtensions.TryResolveService(Autofac.IComponentContext, Autofac.Core.Service, System.Collections.Generic.IEnumerable`1, System.Object ByRef)+4b
Autofac.Core.Activators.Reflection.AutowiringPropertyInjector.InjectProperties(Autofac.IComponentContext, System.Object, Autofac.Core.IPropertySelector, System.Collections.Generic.IEnumerable`1)+2dd
Autofac.ResolutionExtensions.InjectProperties[[System.__Canon, mscorlib]](Autofac.IComponentContext, System.__Canon)+2f
CommonLibrary.WebServiceIoC`1[[System.__Canon, mscorlib]]..ctor()+153
AgendaLibrary.AgendaBService..ctor()+50
[[GCFrame]]
[[DebuggerU2MCatchHandlerFrame]]
[[GCFrame]]
[[HelperMethodFrame_2OBJ] (System.RuntimeTypeHandle.CreateInstance)] System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, BooleanByRef, System.RuntimeMethodHandleInternalByRef, BooleanByRef)
mscorlib_ni!System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)+78
mscorlib_ni!System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)+e9
mscorlib_ni!System.Activator.CreateInstance(System.Type, Boolean)+54
mscorlib_ni!System.Activator.CreateInstance(System.Type)+c
System.Web.Services.Protocols.ServerProtocol.CreateServerInstance()+18
System.Web.Services.Protocols.SoapServerProtocol.CreateServerInstance()+f
System.Web.Services.Protocols.WebServiceHandler.Invoke()+33
System.Web.Services.Protocols.WebServiceHandler.CoreProcessRequest()+28e
System.Web.Services.Protocols.SyncSessionlessHandler.ProcessRequest(System.Web.HttpContext)+84
System.Web.Script.Services.ScriptHandlerFactory+HandlerWrapper.ProcessRequest(System.Web.HttpContext)+c
System.Web.HttpApplication+CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()+32e
System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep)+85
System.Web.HttpApplication.ExecuteStep(IExecutionStep, Boolean ByRef)+4a
System.Web.HttpApplication+PipelineStepManager.ResumeSteps(System.Exception)+5c3
System.Web.HttpApplication.BeginProcessRequestNotification(System.Web.HttpContext, System.AsyncCallback)+65
System.Web.HttpRuntime.ProcessRequestNotificationPrivate(System.Web.Hosting.IIS7WorkerRequest, System.Web.HttpContext)+1ba
System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr, IntPtr, IntPtr, Int32)+3a9
[[InlinedCallFrame]]
System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr, IntPtr, IntPtr, Int32)+20
DomainNeutralILStubClass.IL_STUB_PInvoke(IntPtr, System.Web.RequestNotificationStatus ByRef)+60
[[InlinedCallFrame]]
System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr, IntPtr, IntPtr, Int32)+4f1
[[InlinedCallFrame]]
System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr, IntPtr, IntPtr, Int32)+20
[[ContextTransitionFrame]]
```

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: OS Microsoft Windows 10 Enterprise 10.0.17134 N/A Build 17134
IDE: Visual Studio 2019 16.1.1

**Comment by ajcvickers** [comment] 2019-06-03 21:47
@pfaustinopt This looks like a possible duplicate of https://github.com/dotnet/coreclr/issues/22137

If not, you may want to follow up with on the CoreCLR GitHub repo since this kind of exception is very unlikely to be caused by something EF is doing as opposed to a bug in the CLR.

**Comment by pfaustinopt** [comment] 2019-06-03 21:51
You're correct, the call stack is identical in both issues. 

Thanks for your time.

**Closed** 2022-10-16 14:23 UTC
Labels: closed-external, customer-reported
