### ISSUE TITLE
SplitToTable with IsTemporal

### ISSUE THREAD

**Issue by esben2000** [dotnet/efcore#30366] opened 2023-02-28 15:00 UTC
### I have tried using the below code. However, it seem like the History table will be the same for all tables and the migration gives an error: "Object reference not set to an instance of an object."

Code
```C#
    modelBuilder.Entity<Customer>(entityBuilder =>
        {
            entityBuilder
                .ToTable("Customers", b => b.IsTemporal())
                .SplitToTable(
                    "PhoneNumbers",
                    tableBuilder =>
                    {
                        tableBuilder.Property(customer => customer.Id).HasColumnName("CustomerId");
                        tableBuilder.Property(customer => customer.PhoneNumber);
                    })
                .SplitToTable(
                    "Addresses",
                    tableBuilder =>
                    {
                        tableBuilder.Property(customer => customer.Id).HasColumnName("CustomerId");
                        tableBuilder.Property(customer => customer.Street);
                        tableBuilder.Property(customer => customer.City);
                        tableBuilder.Property(customer => customer.PostCode);
                        tableBuilder.Property(customer => customer.Country);
                    });
        });

```

This code will create the following migration (notice the TemporalHistoryTableName is CustomersHistory for all three tables):

```C#
    migrationBuilder.CreateTable(
        name: "Customers",
        columns: table => new
        {
            Id = table.Column<int>(type: "int", nullable: false)
                .Annotation("SqlServer:Identity", "1, 1")
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CustomersHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart"),
            Name = table.Column<string>(type: "nvarchar(max)", nullable: true)
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CustomersHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart"),
            PeriodEnd = table.Column<DateTime>(type: "datetime2", nullable: false)
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CustomersHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart"),
            PeriodStart = table.Column<DateTime>(type: "datetime2", nullable: false)
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CustomersHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart")
        },
        constraints: table =>
        {
            table.PrimaryKey("PK_Customers", x => x.Id);
        })
        .Annotation("SqlServer:IsTemporal", true)
        .Annotation("SqlServer:TemporalHistoryTableName", "CustomersHistory")
        .Annotation("SqlServer:TemporalHistoryTableSchema", null)
        .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
        .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");

    migrationBuilder.CreateTable(
        name: "Addresses",
        columns: table => new
        {
            CustomerId = table.Column<int>(type: "int", nullable: false)
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CustomersHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", null)
                .Annotation("SqlServer:TemporalPeriodStartColumnName", null),
            Street = table.Column<string>(type: "nvarchar(max)", nullable: true)
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CustomersHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", null)
                .Annotation("SqlServer:TemporalPeriodStartColumnName", null),
            City = table.Column<string>(type: "nvarchar(max)", nullable: true)
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CustomersHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", null)
                .Annotation("SqlServer:TemporalPeriodStartColumnName", null),
            PostCode = table.Column<string>(type: "nvarchar(max)", nullable: true)
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CustomersHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", null)
                .Annotation("SqlServer:TemporalPeriodStartColumnName", null),
            Country = table.Column<string>(type: "nvarchar(max)", nullable: true)
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CustomersHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", null)
                .Annotation("SqlServer:TemporalPeriodStartColumnName", null)
        },
        constraints: table =>
        {
            table.PrimaryKey("PK_Addresses", x => x.CustomerId);
            table.ForeignKey(
                name: "FK_Addresses_Customers_CustomerId",
                column: x => x.CustomerId,
                principalTable: "Customers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        })
        .Annotation("SqlServer:IsTemporal", true)
        .Annotation("SqlServer:TemporalHistoryTableName", "CustomersHistory")
        .Annotation("SqlServer:TemporalHistoryTableSchema", null)
        .Annotation("SqlServer:TemporalPeriodEndColumnName", null)
        .Annotation("SqlServer:TemporalPeriodStartColumnName", null);

    migrationBuilder.CreateTable(
        name: "PhoneNumbers",
        columns: table => new
        {
            CustomerId = table.Column<int>(type: "int", nullable: false)
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CustomersHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", null)
                .Annotation("SqlServer:TemporalPeriodStartColumnName", null),
            PhoneNumber = table.Column<string>(type: "nvarchar(max)", nullable: true)
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CustomersHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", null)
                .Annotation("SqlServer:TemporalPeriodStartColumnName", null)
        },
        constraints: table =>
        {
            table.PrimaryKey("PK_PhoneNumbers", x => x.CustomerId);
            table.ForeignKey(
                name: "FK_PhoneNumbers_Customers_CustomerId",
                column: x => x.CustomerId,
                principalTable: "Customers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        })
        .Annotation("SqlServer:IsTemporal", true)
        .Annotation("SqlServer:TemporalHistoryTableName", "CustomersHistory")
        .Annotation("SqlServer:TemporalHistoryTableSchema", null)
        .Annotation("SqlServer:TemporalPeriodEndColumnName", null)
        .Annotation("SqlServer:TemporalPeriodStartColumnName", null);
```

When I run the migration using 'Update-Database' I get the error "Object reference not set to an instance of an object."

EF Core version: EF 7.0.2
Target framework: .NET 7
Visual Studio 2022 17.4

**Comment by ajcvickers** [comment] 2023-02-28 17:18
Duplicate of #26457. Please vote (👍) for that issue.

**Closed** 2023-03-01 20:21 UTC
Labels: customer-reported
