### ISSUE TITLE
EF Core2: Unable to determine the relationship represented by navigation property...

### ISSUE THREAD

**Issue by wdfpk001** [dotnet/efcore#10484] opened 2017-12-05 13:36 UTC
Hi,

With EF Core 1.1 below code worked fine, but **after upgrading to EF Core 2.0 it's breaking**. Please help. Error message:

> System.InvalidOperationException: 'Unable to determine the relationship represented by navigation property 'Language.UserR' of type 'User'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.'

```C#
  [Table("User")]
     public class User : IDbEntity
     {
       // ...
       private Language language;
 private System.Nullable<Guid> languageID;  
        //...
       
        /// <summary>
        /// 
        /// </summary>
        [ForeignKey("LanguageID")]
        public Language Language
        {
            get
            {
                return this.language;
            }
            set
            {
                this.language = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Nullable<Guid> LanguageID
        {
            get
            {
                return this.languageID;
            }
            set
            {
                this.languageID = value;
            }
        }   
              
      //  ...
    }
```

   ```C#
 [Table("Language")]
    public sealed class Language : IDbEntity
    {
        //...
        private User userR;
        private Guid userIDR;
       //...

       
        /// <summary>
        /// 
        /// </summary>
        [ForeignKey("UserIDR")]
        public User UserR
        {
            get
            {
                return this.userR;
            }
            set
            {
                this.userR = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public Guid UserIDR
        {
            get
            {
                return this.userIDR;
            }
            set
            {
                this.userIDR = value;
            }
        }
 //...     
    }
```

In OnModelCreating:

```C#
modelBuilder.Entity<Language>().HasOne(l => l.UserR).WithOne(u => u.Language).HasForeignKey<User>(u => u.LanguageID);
```

That's working fine with EF Core 1.1.. I've tired the following, didn't help:

- Placing ForeignKey attributes on FKs instead of Navigation properties. 
- Adding additional fluent code: `modelBuilder.Entity<User>().HasOne(u => u.Language).WithOne(l => l.UserR).HasForeignKey<Language>(l => l.UserIDR);`

The only thing that helped is deleting the 'Language' navigation property from User class. But I don't want to do that.

Thanks!

Peter

**Comment by ajcvickers** [comment] 2017-12-05 16:46
@wdfpk001 I took the code above and made minimal changes to make it run, but was not able to reproduce what you are seeing. Can you look at my attempt below and see what might need to change so that it reproduces the error you are seeing?

```C#
[Table("User")]
public class User
{
    private Language language;
    private System.Nullable<Guid> languageID;

    public Guid Id { get; set; }

    [ForeignKey("LanguageID")]
    public Language Language
    {
        get { return this.language; }
        set { this.language = value; }
    }

    public System.Nullable<Guid> LanguageID
    {
        get { return this.languageID; }
        set { this.languageID = value; }
    }
}

[Table("Language")]
public sealed class Language
{
    private User userR;
    private Guid userIDR;

    public Guid Id { get; set; }

    [ForeignKey("UserIDR")]
    public User UserR
    {
        get { return this.userR; }
        set { this.userR = value; }
    }

    public Guid UserIDR
    {
        get { return this.userIDR; }
        set { this.userIDR = value; }
    }
}

public class TestDbContext : DbContext
{
    public DbSet<Language> Languages { get; set; }
    public DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Language>().HasOne(l => l.UserR).WithOne(u => u.Language).HasForeignKey<User>(u => u.LanguageID);
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(
            @"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
}

public class Program
{
    public static void Main()
    {
        using (var context = new TestDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }
    }
}

```

**Comment by smitpatel** [comment] 2017-12-05 20:17
I would like to point out that `ForeignKeyAttribute` is used incorrectly. Having foreign key annotation on both sides of relationship pointing to different properties is incorrect.

**Comment by ajcvickers** [comment] 2017-12-05 20:37
Good catch @smitpatel.

**Comment by ajcvickers** [comment] 2017-12-06 20:40
@wdfpk001 Even with one or more FK attributes removed, this still does not repro for us,  so can you look at my attempt above and see what might need to change so that it reproduces the error you are seeing?

**Comment by wdfpk001** [comment] 2017-12-08 14:49
Thanks for the replies @ajcvickers and @smitpatel !

@ajcvickers : Saw no major difference in your code.. so I dig elsewhere.. and it appears that the problem was with another context.

I have two db contexts: one which is populated dynamically by entity types found at runtime, and another with only two tehnical entities. With the first I had this manual 'HasOne' 'WithOne' relation mapping for resolving circular navigational referencies. For the second I had no manual relation mapping.

With EF Core 1.1 this worked fine.

With EF Core 2.0 I had to add the manual relation mapping (OnModelCreating) to the second context as well. Now it works fine..

**Comment by ajcvickers** [comment] 2017-12-11 20:54
@wdfpk001 I still have not been able to reproduce what you are seeing, but since you have something that is working for you I am closing this for now.

**Closed** 2022-10-16 12:02 UTC
Labels: closed-could-not-reproduce
