### ISSUE TITLE
Customizable scaffolding

### ISSUE THREAD

**Issue by 188867052** [dotnet/efcore#20593] opened 2020-04-10 10:26 UTC
Customizable scaffolding, we know that the code is now generated according to the database configuration
1. Sometimes we don't want the database to have a FK, but I want to have navigation properties
2. Tables are not in single database
3. Some tables do not want to generate code
...

**Comment by ajcvickers** [comment] 2020-04-13 16:50
Duplicate of #4038

**Closed** 2022-10-16 18:20 UTC
Labels: closed-duplicate, customer-reported
