### ISSUE TITLE
.Net Core 2.1 EntityFramework Error - Casting User Defined Types and at runtime getting Type dbo.Flag is not a defined system type.

### ISSUE THREAD

**Issue by rajeevanvgh** [dotnet/efcore#16160] opened 2019-06-19 14:33 UTC
While trying to upgrade a .net core 2.0 Web API project to 2.1, I am getting an Exception "Type Flag is not a defined system type."
There are two columns in db, Primary and Deleted which are of **User Defined Type**  _Flag_ which we are facing problem.
Please find the details:

The following query throws exception at runtime.

```C#
var query = await (from pl in _azureContext.Product.AsNoTracking()
                             where pl.Primary ==1 &&  pl.Deleted=0
                             select new Product()
                             {
                                 ProductId = pl.ProductId,
                                 ProductName = pl.ProductName
                             }).OrderBy(P => s.ProductName).ToListAsync<Product>();
```
The query generated internally as follows.
```sql
SELECT  [pl].[ProductId] , [pl].[ProductName]
      FROM [Products] AS [ps]
      WHERE ([pl].[Primary] = **CAST(1 AS Flag))** AND ([pl].[Deleted] = **CAST(0 AS Flag)**)
      ORDER BY [ProductName]
```

The Issue in EF Core 2.1 is that the SQL generated applies CAST operator on a User Defined Type and when it executes in SQL Server CAST operator does not work with User Defined Type. But In EF Core 2.0 CAST operator is not applied for  User Defined Type.

![EFCore2 1_Casting_UserDefinedType_Issue](https://user-images.githubusercontent.com/25582813/59774559-4714b080-92cd-11e9-9df3-5626763d5fa2.jpg)

### Further technical details
EF Core version: 2.1.11
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.9.3)

**Comment by ajcvickers** [comment] 2019-06-19 14:46
Duplicate of #12633

**Closed** 2022-10-16 14:26 UTC
Labels: customer-reported
