### ISSUE TITLE
dotnet ef migrations commands not working in Linux

### ISSUE THREAD

**Issue by jarz** [dotnet/efcore#19605] opened 2020-01-15 22:01 UTC
When attempting to run `dotnet ef migration script` in an Azure DevOps pipeline Ubuntu agent _or_ a WSL Ubuntu 18.04 install, I receive the following error:

```
2020-01-15T21:02:00.0699927Z ========================== Starting Command Output ===========================
2020-01-15T21:02:00.0751142Z [command]/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/home/vsts/work/_temp/c30bfb4a-96db-4699-863f-79f8ad3a127a.ps1'
2020-01-15T21:02:02.2223109Z /home/vsts/work/1/s/Data/Data.Migrations/Data.Migrations.csproj : error MSB4057: The target "GetEFProjectMetadata" does not exist in the project.
2020-01-15T21:02:02.2818943Z Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
2020-01-15T21:02:02.3705468Z ##[error]PowerShell exited with code '1'.
2020-01-15T21:02:02.3727641Z ##[section]Finishing: Create SQL migration script (PowerShell)
```

My migrations are in a separate csproj, which is probably the root ~of all evil~ cause.

### Steps to reproduce

_Short on time today, can work on code sample later..._

1. Create new .net core project.
    - Separate csproj's for the DbContext, Migrations, and console app.
1. Add a migration.
1. Run `dotnet build`, etc. in Windows
1. Run `dotnet ef migration script`
    - SQL script is generated
1. Run `dotnet clean`
1. Open WSL or clone in Linux.
1. Run `dotnet build`, etc. in Linux.
1. Run `dotnet ef migration script`
    - MSB4057 error for GetEFProjectMetadata

My command looks similar to this:
```
dotnet ef migrations script --idempotent `
    --startup-project Api\Api.csproj `
    --project Data\Data.Migrations\Data.Migrations.csproj `
    --output migrations.sql
```

Specifying `--msbuildprojectextensionspath Data\Data.Migrations\obj\` doesn't resolve the error.

### Further technical details

EF Core version: 2.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: ASP.NET Core 2.1
Operating system: Ubuntu 18.04
IDE: N/A

**Comment by jarz** [comment] 2020-01-15 22:02
I'm assuming there's some relationship to #10216.

**Comment by ajcvickers** [comment] 2020-01-16 21:07
@bricelam Thoughts on this?

**Comment by bricelam** [comment] 2020-01-17 23:37
Can you share a repro? It's hard to say what's going wrong without debugging into it.

P.S. Using PowerShell Core on Linux threw us through a bit of a loop when we first looked at this. 😆

**Comment by jarz** [comment] 2020-01-24 01:27
Here's a repro: https://github.com/jarz/Repro19605

```
tim@tim-xps13:/mnt/c/Users/tim/source/repos/Repro19605$ dotnet ef migrations script --idempotent --startup-project Repro19605\\Repro19605.API.csproj --project Repro19605.Database.Migrations\\Repro19605.Database.Migrations.csproj --output migrations.sql
/mnt/c/Users/tim/source/repos/Repro19605/Repro19605.Database.Migrations/Repro19605.Database.Migrations.csproj : error MSB4057: The target "GetEFProjectMetadata" does not exist in the project.
Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
```

**Comment by bricelam** [comment] 2020-01-25 00:12
I'm not able to repro this. Does `--verbose` give any additional information?

**Comment by pbarczyn** [comment] 2020-01-28 10:40
I had the same issue. The solution that works for our team was changing "\" to "/" in paths.

**Comment by bricelam** [comment] 2020-01-28 19:53
That was my initial thought too, but using `\` totally worked for me in PowerShell on Ubuntu. 😎

**Comment by ajcvickers** [comment] 2020-01-31 16:41
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by sajibcefalo** [comment] 2020-11-16 04:31
> I had the same issue. The solution that works for our team was changing "\" to "/" in paths.

It also worked for me

**Comment by qhero** [comment] 2022-02-23 10:02
This might be obvious for some people but replacing "\" by "/" on MacOS did the trick too.
Thanks

**Closed** 2022-10-16 18:06 UTC
Labels: closed-could-not-reproduce, customer-reported
