### ISSUE TITLE
Shadow property with custom conversion type is not translated to sql.

### ISSUE THREAD

**Issue by rkdrnfds** [dotnet/efcore#11379] opened 2018-03-22 02:22 UTC
```
dbContext.Posts.Where(e => EF.Property<BlogId>(e, "BlogId") == blogId).ToList();
```
and 
```
dbContext.Entry(blog).Collection(e => e.Posts).Load();
```
generates warning 

```
Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'where (Property([e], "BlogId") == __blogId_0)' could not be translated and will be evaluated locally.
```

Post.BlogId Property Is a shadow foreign key to Blog Entity, and also has custom value conversion of EF Core 2.1 
```
dbContext.Entity<Post>()
.Property<BlogId>("BlogId")
.HasConversion(blogIdToGuidConverter)
```

with primitive type like int, sql translation works well with shadow type.

Environments:
 ```
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0-preview1-final" />
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.1.0-preview1" />
```

**Comment by smitpatel** [comment] 2018-03-22 19:24
Duplicate of #10434 

The error here is when we visit the Constant the type is not primitive type which TypeMapper understands. SqlTranslator does not utilize inference so we fail to translate the Constant to server and falls into client eval. If we passed in constant as is (that's what Constant expression translate too) then in this case, it could possible generate SQL literal using the type mapping with converter from left side of equality.

**Closed** 2022-10-16 12:15 UTC
