### ISSUE TITLE
SQL Server Graph support

### ISSUE THREAD

**Issue by wstaelens** [dotnet/efcore#30180] opened 2023-01-31 09:48 UTC
SQL Server (express) has Graph capabilities, but there is almost nothing provided to work with it.

Working with Graph capabilities in SQL Server (express). (maybe link to [dotnetrdf](https://dotnetrdf.org/) project?)

ultimate goal:
Easily create graphs with EF (who knows an rdf triplestore? 😃 )
https://codingsight.com/how-to-make-use-of-sql-server-graph-database-features/
https://learn.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-sample?view=sql-server-ver15

**Comment by ajcvickers** [comment] 2023-01-31 10:25
Duplicate of #8527. Please vote for that issue.

**Comment by roji** [comment] 2023-01-31 10:43
Duplicate of #8527

**Closed** 2023-02-01 20:20 UTC
Labels: closed-duplicate, customer-reported
