### ISSUE TITLE
Include and ThenInclude not working after select

### ISSUE THREAD

**Issue by AniMeIIIkA** [dotnet/efcore#13207] opened 2018-09-04 12:49 UTC
Microsoft.AspNetCore.All - 2.1.3
``` C#
 var userCourses = await ctx.UserCourses
        .Include(x => x.User)
            .ThenInclude(x => x.UserCompanies)
                .ThenInclude(x => x.Company)
                    .ThenInclude(x => x.Licenses)
                        .ThenInclude(x => x.CompanyCourseLicenses)
        .Select(x => new
        {
            x.Course.Title,
            x.User
        })
        .ToListAsync();
```
All User navigation property ICollection is null
If i remove select, then userCourse have User with all ICollection's

**Comment by smitpatel** [comment] 2018-09-05 20:40
Duplicate of #12737

**Closed** 2022-10-16 13:29 UTC
Labels: closed-duplicate, customer-reported
