### ISSUE TITLE
EntityFrameworkCore 5.05 ExecuteSqlRaw fail multiple updates

### ISSUE THREAD

**Issue by frablaser** [dotnet/efcore#25336] opened 2021-07-26 12:51 UTC
## File a bug

I try to Execute a stored procedure from , if I execute it directly from SSMS, it works as expected, but if I use it from ExecuteSqlRaw or ExecuteSqlRawAsync, it fails as soon as it hits the first SELECT COUNT(), no error, but the second UPDATE never run.

### Include your code

The SP:
```
     ALTER PROCEDURE [fact].[SetJobDoneByProcess]
          @JobId int
         ,@JobProcId int
         ,@JobUserId smallint
         ,@Done bit
            
     AS
     BEGIN
        
         DECLARE @procCnt int = 0 
                ,@procCntDone int = 0
                ,@CompletedDtTm datetime = NULL;
        
         --Update this process status
         IF @Done = 1
         BEGIN
             SET @CompletedDtTm = GETDATE();
         END
        
         UPDATE fact.Jobs_Processes
         SET CompletedDtTm = @CompletedDtTm, JobUserId = @JobUserId
         WHERE JobProcId = @JobProcId
        
         -- Compare job processes finished
         SET @CompletedDtTm = NULL;
         SET @procCnt = (SELECT COUNT(JobProcId) FROM fact.Jobs_Processes WHERE JobId = @JobId)
         SET @procCntDone = (SELECT COUNT(JobProcId) FROM fact.Jobs_Processes WHERE JobId = @JobId AND NOT CompletedDtTm IS NULL)
        
         -- Update job
         IF @procCnt = @procCntDone
         BEGIN
             SET @CompletedDtTm = GETDATE();
             UPDATE fact.Jobs
             SET CompletedDtTm = @CompletedDtTm
             WHERE JobId = @JobId
         END
         ELSE
         BEGIN
             UPDATE fact.Jobs
             SET StartedDtTm = GETDATE()
             WHERE JobId = @JobId
             AND StartedDtTm IS NULL
         END
        
     END
```

```C#

```
       var parameters = new[]
         {
            new SqlParameter("@JobId", SqlDbType.Int)
             {
               Direction = ParameterDirection.Input,
               Value = JobProcId
             },
            new SqlParameter("@JobProcId", SqlDbType.Int)
             {
               Direction = ParameterDirection.Input,
               Value = JobProcId
             },
            new SqlParameter("@JobUserId", SqlDbType.SmallInt)
             {
               Direction = ParameterDirection.Input,
               Value = UserId
             },
            new SqlParameter("@Done", SqlDbType.Bit)
             {
               Direction = ParameterDirection.Input,
               Value = Done
             },
         };
            
         ctx.Database.ExecuteSqlRaw("exec fact.SetJobDoneByProcess @JobId, @JobProcId, @JobUserId, @Done", parameters:parameters);

```
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

NO EXCEPTION...

### Include verbose output

Please include `--verbose` output when filing bugs about the `dotnet ef` or Package Manager Console tools.

Use triple-tick fences for tool output. For example:

```
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'SawpProdData'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'SAWPContext'.
SawpProdData.Models.SAWPContext

...
```

### Include provider and version information

EF Core version: 5.0.5
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 5.0
Operating system: Win10
IDE:  Visual Studio 2019 16.10.3

**Comment by AndriySvyryd** [comment] 2021-07-27 21:59
@frablaser Could you simplify the sproc or provide the schema for all the referenced objects?

**Comment by frablaser** [comment] 2021-07-27 22:30
Hi Sir, 
It is what I did... I replaced the two SELECT COUNT() by constants and it do not works from EF Core, but still works from SSMS...

After, I moved the second UPDATE outside de IF clause, and after, it worked...

Then, conclusion, it bump into the IF clause... Why? It's magic!

**Comment by ErikEJ** [comment] 2021-07-28 06:59
Please provide a complete, simplified repro stored procedure.

**Comment by frablaser** [comment] 2021-07-28 14:21
Is that as simple as you want ErikEJ?
```

CREATE PROCEDURE EFFails
	@IdCol int
AS
BEGIN
	
	DECLARE @cnt1 int = 5,
		    @cnt2 int = 5;

	IF @cnt1 = @cnt2
	BEGIN
		UPDATE dbo.MyTable
		SET MyDtTm = GETDATE()
		WHERE IdCol = @IdCol
	END
	ELSE
	BEGIN 
		UPDATE dbo.MyTable
		SET MyDtTm = NULL
		WHERE IdCol = @IdCol
	END

END
GO

```

**Comment by ErikEJ** [comment] 2021-07-28 14:24
Almost, please include the CREATE TABLE script for do.mytable

**Comment by frablaser** [comment] 2021-07-28 14:51
Code for create Table
```

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MyTable](
	[IdCol] [int] IDENTITY(1,1) NOT NULL,
	[MyDtTm] [datetime] NULL,
 CONSTRAINT [PK_MyTable] PRIMARY KEY CLUSTERED 
(
	[IdCol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

```

Code to insert a couple of lines:
```

SET IDENTITY_INSERT [dbo].[MyTable] ON 
GO
INSERT [dbo].[MyTable] ([IdCol], [MyDtTm]) VALUES (1, NULL)
GO
INSERT [dbo].[MyTable] ([IdCol], [MyDtTm]) VALUES (2, CAST(N'2021-01-01T00:00:00.000' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[MyTable] OFF
GO
```

**Comment by frablaser** [comment] 2021-07-28 14:54
C# code :

            var parameters = new[]
            {
               new SqlParameter("@IDCol", SqlDbType.Int)
                {
                  Direction = ParameterDirection.Input,
                  Value = 1
                }
            };
            
            context.Database.ExecuteSqlRaw("exec dbo.MyTable @IdCol", parameters:parameters);

**Comment by roji** [comment] 2021-07-29 16:07
@frablaser I took your code above and made it into a minimal console program, and I can see the stored procedure being invoked successfully - the EFFail stored procedure indeed updates the row with the provided ID to have the current timestamp. Can you please compare this code with your own and try to submit a similar sample which shows the error occurring?

<details>
<summary>Attempted repro</summary>

```c#
await using var ctx = new SomeContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

await ctx.Database.ExecuteSqlRawAsync(@"
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
CREATE TABLE [dbo].[MyTable](
	[IdCol] [int] IDENTITY(1,1) NOT NULL,
	[MyDtTm] [datetime] NULL,
 CONSTRAINT [PK_MyTable] PRIMARY KEY CLUSTERED
(
	[IdCol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

SET IDENTITY_INSERT [dbo].[MyTable] ON;
INSERT [dbo].[MyTable] ([IdCol], [MyDtTm]) VALUES (1, NULL);
INSERT [dbo].[MyTable] ([IdCol], [MyDtTm]) VALUES (2, CAST(N'2021-01-01T00:00:00.000' AS DateTime));
SET IDENTITY_INSERT [dbo].[MyTable] OFF;");

await ctx.Database.ExecuteSqlRawAsync(@"
CREATE PROCEDURE EFFails
	@IdCol int
AS
BEGIN

	DECLARE @cnt1 int = 5,
		    @cnt2 int = 5;

	IF @cnt1 = @cnt2
	BEGIN
		UPDATE dbo.MyTable
		SET MyDtTm = GETDATE()
		WHERE IdCol = @IdCol
	END
	ELSE
	BEGIN
		UPDATE dbo.MyTable
		SET MyDtTm = NULL
		WHERE IdCol = @IdCol
	END
END");

await ctx.Database.ExecuteSqlRawAsync(
    "exec EFFails @IdCol",
    new SqlParameter("@IdCol", SqlDbType.Int) { Direction = ParameterDirection.Input, Value = 1 });

public class SomeContext : DbContext
{
    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);
}
```

</details>

**Comment by frablaser** [comment] 2021-07-30 13:30
Hi roji,

I tested my example (I did not tested it, all my fault, I did a minding shortcut), it works (for me too) as you told me.  It is a little bit more complex as I expected.

Then, I need to figure out where it bumping into. I will need to do a better test set who more reflect my reality. And I will come back with a better example with tables with relations.  

To do that, I need more time. I'll come back ASAP.

Best regards.

**Comment by ajcvickers** [comment] 2021-08-12 16:36
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by frablaser** [comment] 2021-08-31 19:45
I found where it bumping into...

I set all my Parameters to null by default in my SQL Stored Procedures, and since I did that, everything works like a charm... 

Regards.

**Closed** 2022-10-16 19:41 UTC
Labels: closed-could-not-reproduce, customer-reported
