### ISSUE TITLE
cannot add migration in a uwp app

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/efcore#5300] opened 2016-05-09 12:25 UTC
I'm trying to add a ef 7 db context in a uwp app, following the tutorial in the docs site, but when I try to create the migration I have the error message "Object reference not set to an instance of an object."

Am I missing somthing?

**Comment by rowanmiller** [comment] 2016-05-09 18:51
@lucamorelli are you using RC1 packages from NuGet.org?

**Comment by lucamorelli** [comment] 2016-05-09 18:52
yes

**Comment by rowanmiller** [comment] 2016-05-17 17:18
Could you retry with the [RC2 release](https://blogs.msdn.microsoft.com/dotnet/2016/05/16/announcing-entity-framework-core-rc2/)

**Comment by rowanmiller** [comment] 2016-05-23 21:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 09:39 UTC
