### ISSUE TITLE
Migrations with dotnet tools

### ISSUE THREAD

**Issue by christiannagel** [dotnet/efcore#4309] opened 2016-01-14 15:42 UTC
How will the migrations command look like with the CLI / dotnet tools - without the commands section in project.json?

**Comment by rowanmiller** [comment] 2016-01-14 19:38
We are still working that out :smile:. It will look very similar to what we have now, but `dnx ef` will be replaced by something `dotnet ...`. @bricelam is just starting on the implementation now.

**Comment by bricelam** [comment] 2016-01-14 19:54
It will be mostly the same. Instead of *dnx*, you'll type *dotnet*. To align with the NuGet commands better, we'll probably bring back `--startupProject`. Your `project.json` will need to contain the following.
```json
{
  "tools": {
    "dotnet-ef": "7.0.0-*"
  }
}
```

**Comment by bricelam** [comment] 2016-01-14 19:59
Work is being tracked by #3925

**Comment by christiannagel** [comment] 2016-01-14 20:01
That's great, so it will be dotnet ef migrations.... This way I don't need to change too much in my book. Also, thanks for the tracking link :+1:

**Comment by rowanmiller** [comment] 2016-01-14 20:23
Closing this out now, but feel free to post additional questions (we still follow comments even after the issue is closed :smile:)

**Comment by julielerman** [comment] 2016-01-31 20:07
If using David Fowler's NDC sample https://github.com/davidfowl/dotnetcli-aspnetcore as my starting point, after adding EFCore & EFCore.commands to project.json (restore worked), I am trying to get dotnet ef into the tools section but it's not recognized yet. Is that correct ...not implemented yet or am I doing something wrong (again)? Thanks.

**Comment by ErikEJ** [comment] 2016-01-31 20:37
Not yet...

**Comment by rowanmiller** [comment] 2016-02-01 17:37
@julielerman still very much a work in progress, nothing working end-to-end yet

**Comment by julielerman** [comment] 2016-02-01 17:50
understood! :) I don't envy you guys right now.

**Comment by christiannagel** [comment] 2016-02-21 08:39
I tried adding this to project.json:
```
"tools": {
  "dotnet-ef": "1.0.0-*"
}
```
Running *dotnet ef* results in this error:
Failed to initialize CoreCLR, HRESULT: 0x80004005
Am I doing something wrong?

Using CLI tools version 1.0.0-beta-001492, OS Platform Windows 10.0.10586

**Closed** 2022-10-16 09:25 UTC
