### ISSUE TITLE
How to cascade update?

### ISSUE THREAD

**Issue by SirwanAfifi** [dotnet/efcore#15280] opened 2019-04-08 14:47 UTC
How can we specify `on update cascade`? Let's say I have these models:

```csharp
public class Region
{
    public virtual int RegionID { get; set; }
    public virtual string RegionName { get; set; }
}

public class Field
{
    public virtual int FieldID { get; set; }
    [ForeignKey("FieldRegionID")]
    public virtual Region FieldRegion { get; set; }
    public int FieldRegionID { get; set; }
}
```

For some reason my users should be able to update RegionID (PK), this might not be a good idea but as I mentioned this is part of requirement:

```csharp
public DbSet<Region> Regions { get; set; }
public DbSet<Field> Fields { get; set; }

protected override void OnModelCreating(ModelBuilder builder)
{
    base.OnModelCreating(builder);

    builder.Entity<Region>()
        .HasKey(c => c.RegionID);
    builder.Entity<Region>()
        .Property(c => c.RegionID)
        .ValueGeneratedNever();
}
```

It seems that `on delete cascade` is the default behaviour, now my question is that how can I add `on update cascade` to the mix? I couldn't find something on the docs, any idea?

What I basically want is having this structure:

```sql
CREATE TABLE Regions (
                      RegionID INT NOT NULL,
                      PRIMARY KEY (RegionID),
                      RegionName nvarchar(50)
);

CREATE TABLE Fields (
                     FieldID INT,
                     FieldRegionID INT,
                     INDEX Region_Index (FieldRegionID),
                     FOREIGN KEY (FieldRegionID)
                       REFERENCES Regions(RegionID)
                       ON DELETE CASCADE
                       ON UPDATE CASCADE
);
```

### Further technical details
EF Core version: **2.2.0**
Database Provider: **MySql.Data.EntityFrameworkCore**
Operating system: **macOS**
IDE: **Rider**

**Comment by ajcvickers** [comment] 2019-04-08 15:58
Duplicate of #10551

**Comment by NetTecture** [comment] 2019-04-09 17:44
I do not think you will EVER find an ORM that so blatantly violates the requirement that primary keys are non changing, PERIOD.You are aware that Ef can not do the update because every update is a separate SQL statement, and there is no (!) valid way to do that in SQL outside of usingSQL Server cascading change operations, which EF explicitly does not use?

**Comment by SirwanAfifi** [comment] 2019-04-09 17:56
@ajcvickers, Thanks. Appreciate it. Why not adding this as part of fluent API just like OnDelete? Based on the answers in the link you provided I have to add _cascade update_ in Migration file which is not a good idea, what if I have to remove the migration files? So, in this case, I must go to the migration files and manually edit the file. By the way, the other issue is that EF doesn't allow updating PK, it throws an exception, I had to use RAW SQL using _FromSQL_ method.

**Comment by ajcvickers** [comment] 2019-04-09 18:47
@SirwanAfifi I'm not sure 100% what you are asking, but this is not just about allowing it to be specified in the database, but also about then also making EF Core work in a way that keeps things consistent.

**Closed** 2022-10-16 14:17 UTC
Labels: closed-duplicate, customer-reported
