### ISSUE TITLE
[UWP] [SQLite] Data Annotation [Key] not working

### ISSUE THREAD

**Issue by predalpha** [dotnet/efcore#7194] opened 2016-12-06 22:26 UTC
### Steps to reproduce
Hello, 

i dont understand what am i doing wrong cause it seemed to work previously.
The data annotation [Key] doesnt seem to be recognize to perform a **Add-Migration** command.

Im following the Microsoft beginner's tutorial there : https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started

But i dont create Post class, only the Blog one.

Working ->
`public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
    }
`
Not Working ->
`public class Blog
    {
        [Key]
        public int BlogZz { get; set; }
        public string Url { get; set; }
    }
` 
### The issue
System.InvalidOperationException: The entity type 'Blog' requires a primary key to be defined.
   … Microsoft.EntityFrameworkCore.Internal.ModelValidator.ShowError(String message)
   … Microsoft.EntityFrameworkCore.Internal.ModelValidator.EnsureNonNullPrimaryKeys(IModel model)
   … Microsoft.EntityFrameworkCore.Internal.ModelValidator.Validate(IModel model)
   … Microsoft.EntityFrameworkCore.Internal.RelationalModelValidator.Validate(IModel model)
   … Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   … Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass14_0.<GetModel>b__0(Object k)
   … System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   … Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   … Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   … Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   … Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   … Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_6(IServiceProvider p)
   … Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactoryService(FactoryService factoryService, ServiceProvider provider)
   … Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   … Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   … Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   … Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   … Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   … Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   … Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.<>c__DisplayClass6_0.<ConfigureContextServices>b__9(IServiceProvider _)
   … Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactoryService(FactoryService factoryService, ServiceProvider provider)
   … Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   … Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   … Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   … Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   … Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   … Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   … Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   … Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   … Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   … Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   … Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   … Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   … Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   … Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   … Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   … Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The entity type 'Blog' requires a primary key to be defined.
### Further technical details

{
  "dependencies": {
    "Microsoft.EntityFrameworkCore.Sqlite": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}

**Comment by predalpha** [comment] 2016-12-06 22:35
Well if this can help, ive switched to Microsoft.EntityFrameworkCore.Tools Preview3, then reupdate to Preview4 and it works ..., lost my afternoon for that and dont know why since ive reinstalled Visual Studio and clean all.

**Comment by rowanmiller** [comment] 2016-12-06 22:45
Probably a duplicate of https://github.com/aspnet/EntityFramework/issues/5945, which was fixed in the latest set of releases

**Comment by predalpha** [comment] 2016-12-07 00:15
Thank you for your fast answer even if #5945 doesn't help me to understand why downgrading and upgrading the tools fixed it.

For informations, ive tried a new clear UWP project and still have the issue. Must do the downgrade and upgrade tools for the migration to perform.

Do you know why ?

**Comment by predalpha** [comment] 2016-12-07 10:39
Well after restarting Visual Studio, this doesnt work. I clear nuget cache... but no success.
Need a solution

**Comment by bricelam** [comment] 2016-12-07 16:51
[This workaround](https://github.com/aspnet/EntityFramework/issues/7045#issuecomment-265010057) should work. Dupe of #7045 (a regression of #5945 in 1.1.0-preview4-final)

**Comment by predalpha** [comment] 2016-12-08 23:36
Thank you bricelam, finally i downgrade with tools preview_3 and add Microsoft.EntityFrameworkCore.Design. This works now.

**Closed** 2022-10-16 10:45 UTC
