### ISSUE TITLE
Is it possible to evaluate in server if a the property of a row starts with any item of a list of strings?

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#28292] opened 2022-06-22 10:05 UTC
### Include provider and version information

EF Core version: 6.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlIte
Target framework: NET 6.0
Operating system: Windows 11 21H2
IDE: (e.g. Visual Studio 2022 17.2.3)

I have a list of strings and I would like to get all the entities which one property starts with any of the items of the list.

I am trying this query:

```C#
List<string> miLstStrings;   // it is populated with some strings.

List<Data> miLstResultDb = await miDbContext.Data
    .Where(x => miLstStrings.Any(y => x.StringProperty.Contains(y)))
    .ToListAsync()
    .ConfigureAwait(false);
```

But I get an exception that tells that the query can't be translated to be evaluated in the server. I have to evaluate it in the client using for example, AsAsyncEnumerable.

But I would like to know if it is some way with Entity core to evalute the query in the server.

Thanks.

**Comment by ajcvickers** [comment] 2022-06-29 08:38
Duplicate of #19070.

**Closed** 2022-06-29 08:38 UTC
Labels: customer-reported
