### ISSUE TITLE
InMemory: When adding subquery projection, take into account client projection

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#17620] opened 2019-09-04 20:56 UTC
See https://github.com/aspnet/EntityFrameworkCore/issues/16963#issuecomment-528037843

**Comment by zlepper** [comment] 2020-01-23 11:47
So how exactly are we supposed to work around this? Using an anonymous object doesn't work either, and we can't create tuples in expressions?

We are just now attempting to update to dotnet 3 (from 2.2), and we have a bunch of failing tests because of this..

**Comment by tomasbruckner** [comment] 2020-02-20 09:46
any update on this?

**Comment by brenwebber** [comment] 2020-03-09 18:33
I'm getting this exact error, but in different a different, quite specific, situation.

Scenario: Fetching a Parent-ChildCollection and projecting to new Parent-ChildAggregate with a nested Parent.OwnedEntityProperty.

Json representation of source Parent entity structure:
`
{
  "Config": {
    "SubConfig": {
    }
  }
 "Child": []
}
`

Whenever I try aggregate the child list AND retrieve the nested value object, I get the `Unable to cast object of type 'System.Linq.Expressions.NewExpression' to type 'System.Linq.Expressions.MethodCallExpression'` error.

I created a simple console app and proved that this is the only scenario it happens in.

- No child aggregate, just nested config -> passes
- Just child aggregate, no config -> passes
- Child Aggregate, with non-nested config -> passes
- Child list, with nested config -> passes
- Child aggregate, with nested config -> FAILS

In my real project the last scenario succeeds against SQL Server, I have not tried this sample against SQL.

[EFCoreTests.zip](https://github.com/dotnet/efcore/files/4308336/EFCoreTests.zip)

**Comment by PoyaManouchehri** [comment] 2020-03-27 00:23
Really keen to hear if there is an ETA for this. It's a blocker for our migration to 3.1 at this point.

**Comment by jgbpercy** [comment] 2020-07-21 10:41
For anyone coming across this because they're trying to use a `.Count` alongside a parameterized constructor (like my issue https://github.com/dotnet/efcore/issues/21001 ), we've worked around this by wrapping the `Count` in a `Convert.ToInt32` call. This fixes the tests that use the InMemory provider. In terms of the SQL generated for the SQL Server provider, this adds a `CONVERT`. Someone who is more of an expert on SQL perf can correct me if I'm wrong, but I don't think that should adversely affect performance, and for us it's superior to dropping to parameterless ctors.

@PoyaManouchehri don't know if this helps you?

**Comment by kvv842** [comment] 2020-08-03 13:29
I have this exception used Select and Count.
```
var test = await db.Users.Select(u => new
                {
                    u.Id,
                    Acts = u.Activities.Select(a => new { a.Id }),
                    ActsCount = u.Activities.Count(),
                }).ToListAsync();
```

**Comment by PoyaManouchehri** [comment] 2020-08-04 04:26
@jgbpercy I can confirm that our original issue (exception when using `.Any()` in a subquery) is fixed in EF Core InMemory 3.1.6.

**Comment by Noppey** [comment] 2020-08-17 12:20
.Any() is still a problem for me in EF Core InMemory 3.1.7. When I replace .any() with .Count() > 0 my tests pass.

**Comment by tomasbruckner** [comment] 2020-09-24 15:42
This still fails in 3.1.8 in InMemoryDatabase but works fine in SQL Server/PostgreSQL.

Exception
```
Unable to cast object of type 'System.Linq.Expressions.NewExpression' to type 'System.Linq.Expressions.MethodCallExpression'.
```
code 
```c#
public static IQueryable<ContainerDto> ToDtoList(this IQueryable<Container> data)
{
    return data.Select(AsDto);
}

public static readonly Expression<Func<Container, ContainerDto>> AsDto =
  item => new ContainerDto
{
    Text = item.Text,
    Cars = item.Cars
        .AsQueryable()
        .Select(AsCarDto)
        .FirstOrDefault(),
};

public static readonly Expression<Func<Car, CarDto>> AsCarDto =
  item => new CarDto
  {
      Name = item.Name,
  };
```

**Comment by ryannasr** [comment] 2020-10-11 00:30
> This still fails in 3.1.8 in InMemoryDatabase but works fine in SQL Server/PostgreSQL.
> 
> Exception
> 
> ```
> Unable to cast object of type 'System.Linq.Expressions.NewExpression' to type 'System.Linq.Expressions.MethodCallExpression'.
> ```
> 
> code
> 
> ```cs
> public static IQueryable<ContainerDto> ToDtoList(this IQueryable<Container> data)
> {
>     return data.Select(AsDto);
> }
> 
> public static readonly Expression<Func<Container, ContainerDto>> AsDto =
>   item => new ContainerDto
> {
>     Text = item.Text,
>     Cars = item.Cars
>         .AsQueryable()
>         .Select(AsCarDto)
>         .FirstOrDefault(),
> };
> 
> public static readonly Expression<Func<Car, CarDto>> AsCarDto =
>   item => new CarDto
>   {
>       Name = item.Name,
>   };
> ```

I am having the same problem. Works in SQL Server but not InMemoryDatabase. Is there a known workaround?

Thanks!

**Closed** 2021-05-05 17:14 UTC
Labels: area-in-memory, area-query, closed-fixed, punted-for-3.1, type-bug
