### ISSUE TITLE
Bug when generating SQL

### ISSUE THREAD

**Issue by joshmouch** [dotnet/efcore#7307] opened 2016-12-23 18:31 UTC
I have an Expression tree that is generating incorrect SQL.

First, here is an example that works correctly.  The following expression tree:
````
{e => (((((e.RecommendationId == 20c1330e-8467-472f-b9d2-2f212394f508) Or (e.RecommendationId == 3e155765-e0de-43ba-be60-602f06a8c09a)) Or (e.RecommendationId == 6abda0ce-0721-4dba-b826-0be331e4adfa)) Or (e.RecommendationId == ba0d5d50-4063-4b95-84d1-f9b53f12a0a8)) Or (e.RecommendationId == f14bace9-6732-403b-9a56-694efe64bf6d))}
````

Correctly generates the following SQL:
````

SELECT {removed}
FROM {removed} AS [e]
WHERE ((((CASE
    WHEN [e].[RecommendationID] = '20c1330e-8467-472f-b9d2-2f212394f508'
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END | CASE
    WHEN [e].[RecommendationID] = '3e155765-e0de-43ba-be60-602f06a8c09a'
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END) | CASE
    WHEN [e].[RecommendationID] = '6abda0ce-0721-4dba-b826-0be331e4adfa'
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END) | CASE
    WHEN [e].[RecommendationID] = 'ba0d5d50-4063-4b95-84d1-f9b53f12a0a8'
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END) | CASE
    WHEN [e].[RecommendationID] = 'f14bace9-6732-403b-9a56-694efe64bf6d'
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END) = 1

````

Please note the "=1" at the end of the SQL query.

Now if I simply add to the original expression tree so that it looks like this:

````
{e => ((((((e.RecommendationId == 20c1330e-8467-472f-b9d2-2f212394f508) Or (e.RecommendationId == 3e155765-e0de-43ba-be60-602f06a8c09a)) Or (e.RecommendationId == 6abda0ce-0721-4dba-b826-0be331e4adfa)) Or (e.RecommendationId == ba0d5d50-4063-4b95-84d1-f9b53f12a0a8)) Or (e.RecommendationId == f14bace9-6732-403b-9a56-694efe64bf6d)) AndAlso Invoke(e => ((e.ClientId == value(Epreop.Data.Repository+<>c__DisplayClass2422_0).clientId) AndAlso (e.DeleteFlag == False)), e))}
````

Then the "=1" gets removed from the generated SQL, and a SQL error occurs.  The new generated SQL is:

````
SELECT {removed}
FROM {removed} AS [e]
WHERE ((((CASE
    WHEN [e].[RecommendationID] = '20c1330e-8467-472f-b9d2-2f212394f508'
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END | CASE
    WHEN [e].[RecommendationID] = '3e155765-e0de-43ba-be60-602f06a8c09a'
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END) | CASE
    WHEN [e].[RecommendationID] = '6abda0ce-0721-4dba-b826-0be331e4adfa'
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END) | CASE
    WHEN [e].[RecommendationID] = 'ba0d5d50-4063-4b95-84d1-f9b53f12a0a8'
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END) | CASE
    WHEN [e].[RecommendationID] = 'f14bace9-6732-403b-9a56-694efe64bf6d'
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END) AND (([e].[ClientID] = @__clientId_0) AND ([e].[DeleteFlag] = 0))
````

Again, note that the "=1" was removed, resulting in invalid SQL.

**Comment by divega** [comment] 2017-01-06 20:09
@joshmouch could you try using `OrElse` instead of `Or`? 

@smitpatel looks like this is a bug regardless of whether this works with `OrElse`, but we can discuss the priority if it does.

**Comment by joshmouch** [comment] 2017-01-06 20:20
@divega I'm not sure I'd know how to easily do that.  I'm using a simple LinqKit method to add to the Expression.

**Comment by smitpatel** [comment] 2017-01-20 00:09
possible dupe of #7271

**Comment by smitpatel** [comment] 2017-01-24 22:36
duplicate of #7271 
PR #7331 resolves this too.

**Closed** 2022-10-16 10:47 UTC
Labels: closed-duplicate
