### ISSUE TITLE
Database migration not applied

### ISSUE THREAD

**Issue by jaysee260** [dotnet/efcore#22622] opened 2020-09-19 21:59 UTC
I started with [this issue](https://github.com/dotnet/efcore/issues/22619), which was resolved by targeting the latest daily build.

However, now when I run `dotnet ef database update`, the operation appears to succeed, but I don't see the tables in my database. It says "the database is already up to date" and so it concludes that there are "no migrations to apply".

Here's the output:
```
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 5.0.0-rc.2.20469.1 initialized 'LibraryContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: SensitiveDataLoggingEnabled 
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (15ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE c.relname='__EFMigrationsHistory');
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE c.relname='__EFMigrationsHistory');
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "MigrationId", "ProductVersion"
      FROM "__EFMigrationsHistory"
      ORDER BY "MigrationId";
info: Microsoft.EntityFrameworkCore.Migrations[20405]
      No migrations were applied. The database is already up to date.
No migrations were applied. The database is already up to date.
Done.
```

Moreover, when I query the `__EFMigrationsHistory` table directly from Postgres, it comes back with `0 rows`.
![image](https://user-images.githubusercontent.com/33580723/93689950-6d616700-faa1-11ea-939a-b43448d99089.png)

I found [this issue](https://github.com/dotnet/efcore/issues/22306) which seemed to address a similar problem, but it was closed since it couldn't be reproduced.

### Further technical details

EF Core version:
Entity Framework Core .NET Command-line Tools
5.0.0-rc.1.20451.13
```
<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.0-rc.2.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0-rc.2.*" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.0-rc1"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0-rc.1.20451.14"/>
  </ItemGroup>
```
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL - 5.0.0-rc1
Target framework: .NET Core 3.1
Operating system: Windows 10 - Version 2004, OS Build 19041.450
IDE: Visual Studio Code 1.48.2

**Comment by ajcvickers** [comment] 2020-09-21 17:54
@roji to follow up.

**Comment by roji** [comment] 2020-09-22 22:11
@programmer1718 we've frequently seen this kind of thing when a model exists, but no initial migration for it is created. Every time the model changed - including the first time when it's first created - you need to run `dotnet ef migrations add` to scaffold the right migration. After doing that, doing `dotnet ef database update` will apply that migration - see the [migration docs](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli) for more info.

If you're sure you have a migration, can you please post step-by-step instructions on how to reproduce the issue, including your actual model, your migration creation, etc.?

**Comment by programmer1718** [comment] 2020-09-23 20:19
@roji yes, I'll take some time later today to provide the requested information.

**Comment by ajcvickers** [comment] 2020-10-05 18:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:41 UTC
Labels: closed-could-not-reproduce, customer-reported
