### ISSUE TITLE
EF generates two nonsensical JOINs when mapping a HasOne().WithOne() relationship with table splitting

### ISSUE THREAD

**Issue by InspiringCode** [dotnet/efcore#25231] opened 2021-07-09 19:24 UTC
Given a very simple model with a one-to-one relationship using table splitting:
```
public class Employee {
    public Guid Id { get; set; } = Guid.NewGuid();

    public string Name { get; set; }

    public EmployeeData Data { get; set; }
}

public class EmployeeData {
    public string Address { get; set; }
}
```
With the mapping
```
b.Entity<Employee>(e => {
    e.ToTable("Employee");
    e.HasOne(x => x.Data).WithOne().HasForeignKey<EmployeeData>("Id");
});

b.Entity<EmployeeData>(e => {
    e.ToTable("Employee");
    e.HasKey("Id");
    e.Property<Guid>("Id");
});
```

When simply querying for all Employees:
```
db.Set<Employee>().Include(x => x.Data).ToArray()
```

Then the query should have no JOINs since all data is in the Employee table, but the actual query has TWO JOINs!
```
SELECT [e].[Id], [e].[Name], [t].[Id], [t].[Address]
FROM [Employee] AS [e]
LEFT JOIN (
    SELECT [e0].[Id], [e0].[Address]
    FROM [Employee] AS [e0]
    INNER JOIN [Employee] AS [e1] ON [e0].[Id] = [e1].[Id]
) AS [t] ON [e].[Id] = [t].[Id]
```

Even when I directly query for `EmployeeData` with `db.Set<EmployeeData>().ToArray()`, a strange INNER JOIN is generated:
```
SELECT [e].[Id], [e].[Address]
FROM [Employee] AS [e]
INNER JOIN [Employee] AS [e0] ON [e].[Id] = [e0].[Id]
```

This seems like a bug to me, or am I using Entity Framework Core in a very wrong way here? Is there any way I can change my mapping so that the queries make more sense?

I am using Entity Framework Core 5.0.7.

**Comment by InspiringCode** [comment] 2021-07-09 20:45
When I change the mapping to
```
b.Entity<Employee>(e => {
    e.ToTable("Employee");
    e.HasOne(x => x.Data).WithMany().HasForeignKey(x => x.Id);
});
```
Then the query is generated with one JOIN less, but I cannot insert any data anymore, because EF Core doesn't recognize the table splitting anymore and does two INSERTs into [Employee] which obviously fails with a NULL constraint or UNIQUE constraint violation.

**Comment by smitpatel** [comment] 2021-07-09 23:40
Duplicate of #18869

**Comment by smitpatel** [comment] 2021-07-09 23:47
The join is logical and required in certain cases, the duplicate issue tracks removing the join specifically but preserving it's effects on the result.

In table splitting scenario, every row must represent the main entity type which is being mapped to that table (this entity type could be a derived type using TPT also). Any entity which is using the same table must have a one-to-one relationship with this main entity type. If the main entity type doesn't exist for any reason, then the join makes sure that it filters such row out.

e.g. If table is using TPH for Person/Employee hierarchy and Employee has EmployeeData which is sharing table then any query on EmployeeData must also add join & apply filter on discriminator for the main entity. Without it, the EmployeeData will either have null results from the rows of Person if it is not Employee or incorrect results/errors if the same columns are being used by a different type. We can eliminate the join since they are in same table but we need to preserve filter (aka conditions for existence of principal entity when table sharing)

**Comment by InspiringCode** [comment] 2021-07-10 14:25
Thank you very much for your thorough answer. I tried to think about all the possible cases and came to the following conclusion:

1. If we query `Set<Employee>().Include(x => x.Data)` we should in theory never need neither of the two joins because when dematerializing the results on the client we know whether the concrete type has a EmployeeData property or not.

2. If we query `Set<EmployeeData>`, I could think of only two cases where a join would be needed:
	1. Person is mapped as TPH AND only a subtype (Employee) defines the one-to-one relationship to EmployeeData.
    2. In a TPT scenario we should not need any JOIN UNLESS the one-to-one relation is only defined on SOME subtypes, but is sharing the table with the base type (which seems like a quite esoteric scenario to me).
	
Could you please confirm if my understanding is correct or correct me if not?

**Closed** 2022-10-16 19:39 UTC
Labels: closed-duplicate, customer-reported
