### ISSUE TITLE
Counting over group join returns wrong result

### ISSUE THREAD

**Issue by jtheisen** [dotnet/efcore#7971] opened 2017-03-23 20:56 UTC
A query of the form

```c#
            var result = (
                from f in db.Foos
                join b in db.Bars on f.FooId equals b.FooId into bars
                select new { Name = f.FooId, Count = bars.Count() }
                ).Take(15).ToArray();
```

returns the wrong result.

#### Model

```c#
    public class MyFooEntity
    {
        [Key]
        public Guid FooId { get; set; }
    }

    public class MyBarEntity
    {
        [Key]
        public Guid BarId { get; set; }

        public Guid FooId { get; set; }

        public MyFooEntity Foo { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<MyFooEntity> Foos { get; set; }
        public DbSet<MyBarEntity> Bars { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=.\\;Database=mycdb;Integrated Security=SSPI;");
        }
    }
```

#### Test

```c#
        static void Main(string[] args)
        {
            var db = new MyContext();

            if (db.Foos.Count() == 0)
            {
                for (int i = 0; i < 20; ++i)
                {
                    var foo = new MyFooEntity() { FooId = Guid.NewGuid() };

                    db.Foos.Add(foo);

                    for (int j = 0; j < 20; ++j)
                    {
                        var bar = new MyBarEntity() { BarId = Guid.NewGuid(), FooId = foo.FooId };

                        db.Bars.Add(bar);
                    }
                }

                db.SaveChanges();
            }

            var result = (
                from f in db.Foos
                join b in db.Bars on f.FooId equals b.FooId into bars
                select new { Name = f.FooId, Count = bars.Count() }
                ).Take(15).ToArray();

            var text = JsonConvert.SerializeObject(result, Formatting.Indented);

            Debug.WriteLine(text);

            Debug.WriteLine("done.");
        }
```

#### Output

```
[
  {
    "Name": "f73a9dce-afeb-4269-9f65-0fe3258f9190",
    "Count": 15
  }
]
```

Expected are 15 objects with a count of 20 each, not one with a count of 15.

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Visual Studio 2017

**Comment by pmiddleton** [comment] 2017-03-23 22:55
This has already been fixed in dev, I believe by #7823.  

In 1.1.1 the Take call is being translated into a top statement in the sql which is limiting the number of results.  That is why you are only seeing 1 result with a 15 count.  In dev branch the count it is being applied clientside. 

In dev this will currently not produce an optimal query since group by is not yet supported, but it does produce the expected result.

**Comment by maumar** [comment] 2017-03-23 23:01
Yup, this is a dupe of https://github.com/aspnet/EntityFramework/issues/7497, closing

**Comment by jtheisen** [comment] 2017-03-24 09:44
I'm glad to hear it!

**Closed** 2022-10-16 10:58 UTC
