### ISSUE TITLE
Bad AddRange performance

### ISSUE THREAD

**Issue by jessetabak** [dotnet/efcore#12162] opened 2018-05-29 19:19 UTC
I'm inserting a few million entities (in batches of +/- 100.000) and while I expect it to take a while it really is too slow. I profiled the operation and there seems to be one method call that causes 99% of the delay. It's the Add(object, object) method in the ClrICollectionAccessor class. Internally it does a Contains() on a List which obviously will get slow with lots of records. The SaveChanges() method has exactly the same issue. I included the profile report from resharper:

AddRange():
![image](https://user-images.githubusercontent.com/5311393/40678271-60fa1be8-6380-11e8-91fa-35acc1326e18.png)

SaveChanges():
![image](https://user-images.githubusercontent.com/5311393/40678354-ad94d31c-6380-11e8-8783-8b00bbf90233.png)

Entities:
```c#
public partial class Machine
{
    public Machine()
    {
        Segment = new HashSet<Segment>();
    }

    public long ID { get; set; }    
    public string Name { get; set; }            
    public ICollection<Segment> Segment { get; set; }
}


public partial class Segment
{
    public Segment()
    {        
        Event = new HashSet<Event>();        
    }

    public long ID { get; set; }
    public long? MachineID { get; set; }
    public long Number { get; set; }
    public string Serial { get; set; }

    public Machine Machine { get; set; }
    
    public ICollection<Event> Event { get; set; }    
}


public partial class Event
{
    public long ID { get; set; }
    public long Timestamp { get; set; }
    public string Message { get; set; }
    public long SegmentID { get; set; }

    public Segment Segment { get; set; }
}
```

Entity tree creation:
```c#
var events = new List<Event>();

var machine = new Machine
{    
    Name = "Machine01"
};

var segment = new Segment
{
    Number = 1,
    Serial = "xxx",
    Machine = machine
};

// +/- 100.000 iterations
foreach (var logEntry in logEntries)
{
    var @event = new Event
    {
        Message = logEntry.FullMessage,
        Timestamp = logEntry.DateTimeStamp
        Segment = segment        
    };
                            
    events.Add(@event);
}

DbContext.ChangeTracker.AutoDetectChangesEnabled = false;
DbContext.ChangeTracker.LazyLoadingEnabled = false;
DbContext.Event.AddRange(events);
DbContext.SaveChanges();
```

### Further technical details
EF Core version: 2.1.0-preview2-final
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio 2017 15.6.6

**Comment by anpete** [comment] 2018-05-29 19:40
@jessetabak This is due to the navigation fix-up occurring in the state manager. A couple of things to improve this:

1) Use different collection types for collection navigations. I.e. You can use HashSet<T> so that Contains is faster.
2) Remove the navigations if possible so fix-up doesn't even need to take place.

Related to #10632

**Comment by jessetabak** [comment] 2018-05-29 23:05
@anpete 
Thanks for the quick answer.
I think I see now what went wrong here, while the collections in my entities are by default initialized with a hashset, I use Automapper to map from my domain models which use List for all the collections.

I'll try to update my mapping logic so I don't end up with Lists in my entities anymore.

**Comment by ajcvickers** [comment] 2018-06-01 21:52
Closing this as a double-dupe of #10632 (Allow fixup to be disabled) and #9422 (Perf for change tracking)

**Closed** 2022-10-16 12:27 UTC
Labels: closed-duplicate, customer-reported
