### ISSUE TITLE
Query: constant values sometimes get incorrectly parameterized which may lead to issue when the parameter value doesn't match the expected type mapping

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#20078] opened 2020-02-26 21:32 UTC
Found as part of investigation of https://github.com/dotnet/efcore/issues/19128

query:

```cs
context.Set<Gear>()
    .OrderBy(g => g.Nickname)
    .Take(1)
    .Select(g => g.Rank & MilitaryRank.Private))
```

generates the following sql:

```sql
SELECT TOP(@__p_0) [g].[Rank] & @__p_0
FROM [Gears] AS [g]
WHERE [g].[Discriminator] IN (N'Gear', N'Officer')
ORDER BY [g].[Nickname]
```

This happens because we always parameterize arguments to a Skip/Take (value: 1, typed as int).
When processing a projection, we encounter constant enum MilitaryRank.Private, with underlying type also being 1 typed as int. This leads us to substitute the constant with the same parameter.

However the issue is that the expected type mapping for that parameter in the projection is MilitaryRank, not enum. We should not be reusing parameters this way, especially when their type mappings don't match

**Comment by maumar** [comment] 2020-02-26 21:34
Workaround is to parameterize the constant, like so:

```
var prm = MilitaryRank.Private;

context.Set<Gear>()
    .OrderBy(g => g.Nickname)
    .Take(1)
    .Select(g => g.Rank & prm))
```

This will create two separate parameters, both with correct type mappings.

**Comment by smitpatel** [comment] 2020-03-05 23:18
Duplicate of #19503

**Closed** 2022-10-16 18:13 UTC
Labels: closed-duplicate
