### ISSUE TITLE
FromSql composability fails when the initial SELECT is followed by a non platform line ending

### ISSUE THREAD

**Issue by angelyordanov** [dotnet/efcore#15682] opened 2019-05-10 14:58 UTC
A query composed of a `FromSql` call coupled with some linq (e.g. Where filtering) will be evaluated locally if the sql in question starts with a "SELECT\n" on windows or "SELECT\r\n" on macos.

The following console application exhibits the problem.

To make things more obvious EFCore is setup to throw on QueryClientEvaluationWarning.

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.DependencyInjection;
using System.Linq;

namespace FromSqlSample
{
    class Program
    {
        static void Main(string[] args)
        {
            var services = new ServiceCollection();
            services.AddEntityFrameworkSqlServer()
                .AddDbContext<MyDbContext>(optionsBuilder =>
                    optionsBuilder
                        .UseSqlServer($"Server=localhost,1433;User Id=<user>;Password=<pass>;Initial Catalog=<db>")
                        .ConfigureWarnings(warnings =>
                            warnings.Throw(RelationalEventId.QueryClientEvaluationWarning)));

            var serviceProvider = services.BuildServiceProvider();

            var dbContext = serviceProvider.GetService<MyDbContext>();

            // fails on macos
            var res1 = dbContext.Query<UserQuery>()
                .FromSql("SELECT\r\nEmail FROM Users")
                .Where(u => u.Email == "test@gmail.com")
                .ToList();

            // fails on windows
            var res2 = dbContext.Query<UserQuery>()
                .FromSql("SELECT\nEmail FROM Users")
                .Where(u => u.Email == "test@gmail.com")
                .ToList();
        }
    }

    class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions<MyDbContext> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Query<UserQuery>();
        }
    }

    class UserQuery
    {
        public string Email { get; set; }
    }
}
```

The only requirements are a call to
```
dotnet add package Microsoft.EntityFrameworkCore.SqlServer --version 2.2.4
```

And setting a correct connection string to a DB with the following table.
```sql
CREATE TABLE [dbo].[Users] (
    [Email] NVARCHAR (50) NOT NULL
)
```

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: win, macos

**Comment by ajcvickers** [comment] 2019-05-10 15:14
Duplicate of #14489

**Closed** 2022-10-16 14:20 UTC
Labels: customer-reported
