### ISSUE TITLE
EF Core loading related entites

### ISSUE THREAD

**Issue by MateiNenciu** [dotnet/efcore#10018] opened 2017-10-09 08:29 UTC
I am developing an ASP.NET Core API and in some cases I'm loading data with EF Core. I have the following scenario with 3 related entities:

  Employee (E) -> EmployeeStates (ES) -> JobTitles (JT)

  One E can have one or many ES and only ONE current ES. Each ES is related to only one employee.
One ES can have only one JT and there are many ES that have the same JT.

The entities are defined below:
```c#
public partial class Employees
{
  public Employee()
  {
    EmployeeStates = new HashSet<EmployeeStates>();
    .......
  }

  public int IdEmployee { get; set; }
  public ICollection<EmployeeStates> EmployeeStates { get; set; } // (all ES)
  public EmployeeStates IdCurrentEmployeeStateNavigation { get; set; }  // current ES
  ..........
}

public partial class EmployeeStates
{
   public EmployeeStates()
   {
      Employees = new HashSet<Employees>();
      ........
   }

   public int IdEmployeeState { get; set; }
   public int IdEmployee { get; set; }
   public Employees IdEmployeeNavigation { get; set; }
   public ICollection<Employees> Employees { get; set; }
   public JobTitles IdJobTitleNavigation { get; set; }
   ...........
}
public partial class JobTitles
{
   public JobTitles()
   {
      EmployeeStates = new HashSet<EmployeeStates>();
      .........
   }
  
   public int IdJobTitle { get; set; }
   public ICollection<EmployeeStates> EmployeeStates { get; set; }
   .............
}

//In my Context.cs

modelBuilder.Entity<Employees>(entity =>
{
   entity.HasKey(e => e.IdEmployee);
   entity.Property(e => e.IdEmployee).HasColumnName("idEmployee");
   entity.Property(e => e.IdCurrentEmployeeState).HasColumnName("idCurrentEmployeeState");
   
   entity.HasOne(d => d.IdCurrentEmployeeStateNavigation)
            .WithMany(p => p.Employees)
            .HasForeignKey(d => d.IdCurrentEmployeeState)
            .HasConstraintName("FK_Employees_EmployeeStates");
    ............
}

modelBuilder.Entity<EmployeeStates>(entity =>
{
   entity.HasKey(e => e.IdEmployeeState);
   entity.Property(e => e.IdEmployeeState).HasColumnName("idEmployeeState");
   entity.Property(e => e.IdEmployee).HasColumnName("idEmployee");
   entity.Property(e => e.IdJobTitle).HasColumnName("idJobTitle");

   entity.HasOne(d => d.IdEmployeeNavigation)
            .WithMany(p => p.EmployeeStates)
            .HasForeignKey(d => d.IdEmployee)
            .HasConstraintName("FK_EmployeeStates_Employees");
   entity.HasOne(d => d.IdJobTitleNavigation)
             .WithMany(p => p.EmployeeStates)
             .HasForeignKey(d => d.IdJobTitle)
             .HasConstraintName("FK_EmployeeStates_JobTitles");
   ...............
}

modelBuilder.Entity<JobTitles>(entity =>
{
   entity.HasKey(e => e.IdJobTitle);
   entity.Property(e => e.IdJobTitle).HasColumnName("idJobTitle");
}
}

```

  The problem appears when I'm trying to load data for 20 employees it make a huge JSON with data ( 1 million + rows). 
  What happens? I'm trying to explain with the following JSON : https://jsonblob.com/969ad8b8-acc3-11e7-894a-21128ef3c0de ( I used this website to be more readable).  This JSON was generated by the following code:
```c#
   var emps = this.Context.Employees
                .Include(e => e.IdCurrentEmployeeStateNavigation)
                    .ThenInclude(es => es.IdJobTitleNavigation);
                    
```
  As you can see in the JSON the first Employee have the employeeStates array completed ( but I only included e.IdCurrentEmployeeStateNavigation). In this case ok the current ES is basically an EmployeeState but I did not specifically requested for it, only for the CurrentESNavigation. 
  The problem is getting even worse with the second employee: as you can see in the idCurrentEmployeeStateNavigation entity there is idJobTitleNavigation. If you expand this navigation you can find an array named employeeStates which contains the ES of the first Employee. This is wrong! Why is EF completing that array anyway? I didn't included that with .Include<>.
  Adding a third employee and his JobTitleNavigation will have the array ES completed with the Employee1 + Employee2 data. An so on for 20 employees generates over 1 million rows...

Am I doing something wrong? Those entites and their relationships were generated from the DB with EF core command. Adding support for Lazy Loading in EF will solve my problem? Why EF Core doesn't complete only the entities I included, where I requested them?

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 latest version
IDE: Visual Studio 2017 Update 3

**Comment by ajcvickers** [comment] 2017-10-09 16:25
@MateiNenciu As far as I can tell from the code and the description above, EF is only loading the entities requested. However, when there are relationships between entities, EF automatically fixes up those relationships when loading, including any back references or collections. In other words, it's not "loading" more than requested, it's just putting what is loaded into a fully connected consistent graph of objects.

What you are likely then seeing is issues with json serialization of graphs of objects. See this section in the docs for more info: https://docs.microsoft.com/en-us/ef/core/querying/related-data#related-data-and-serialization

**Comment by MateiNenciu** [comment] 2017-10-09 16:44
Yes I thought the same thing but in my controller, before I return values to be serialized I have something like var values = _repo.GetValues(...);. If I debug this the results view of my values variable already contains this bad organized graph so I don't think is about serialization. I will provide later,  as I get home, more details and a picture to see exactly what I'm talking about. My GetValues method is IQuerable

**Comment by MateiNenciu** [comment] 2017-10-10 07:14
Ok according to this link : https://stackoverflow.com/questions/39024354/asp-net-core-api-only-returning-first-result-of-list/39024972 a user named jeremy.bass sugested using .AsNoTracking() for solving a problem related to mine. 
I did as him and it helped me with the self referencing some of the entities (I got from 1 million rows to 20k). I noticed that it solved the problem with level 1 self refencing entities. But it didn't solve the problem with the example that I provided in the JSON above (IdJobTitleNavigation still brings me n EmployeeStates, it's ES and all of the above employees ES's).

**Comment by ajcvickers** [comment] 2017-10-10 16:36
@MateiNenciu Using AsNoTracking, you will get fixup for just the relationships you Include, but it will still fix up both sides of the relationship.

At this point it looks like everything EF is doing is by design. For us to investigate further could you put together a simple repro project, or post full code of a console app here, so we can look very specifically at what is happening in your particular case?

**Comment by MateiNenciu** [comment] 2017-10-10 16:39
Yes I will try to recreate the issue tomorrow with another project.

**Comment by ajcvickers** [comment] 2017-10-18 18:04
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:53 UTC
Labels: closed-could-not-reproduce
