### ISSUE TITLE
ExecuteUpdate throws InvalidOperationException when update owned entity and others properties together

### ISSUE THREAD

**Issue by raphaelm22** [dotnet/efcore#31342] opened 2023-07-24 20:07 UTC
## Ask a question

When ExecuteUpdate is called to update some ownedEntity and other property together, the InvalidOperationException is throwed.
I wish update the whole entity, including ownedEntities, in the same update statement.

```C#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

ctx.Entities
    .ExecuteUpdate(updates => updates
        .SetProperty(e => e.Name, "name updated")
        .SetProperty(e => e.Owned.Value, "owned value updated")
    );

class BlogContext : DbContext
{
    public DbSet<Blog> Entities { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User ID=sa; Password=myPwd;Connect Timeout=15;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
    public BlogDetails Owned { get; set; }
}

[Owned]
public class BlogDetails
{
    public string Value { get; set; }
}
```

### Include stack traces

Exception
```
The LINQ expression 'DbSet<Blog>()
    .Where(b => b.Id > 0)
    .Select(b => IncludeExpression(
        EntityExpression:
        b, 
        NavigationExpression:
        EF.Property<BlogDetails>(b, "Owned"), Owned)
    )
    .ExecuteUpdate(updates => updates.SetProperty<string>(
        propertyExpression: e => e.Name, 
        valueExpression: "name updated").SetProperty<string>(
        propertyExpression: e => e.Owned.Value, 
        valueExpression: "owned value updated"))' could not be translated. Additional information: Multiple 'SetProperty' invocations refer to properties on different entity types ('BlogDetails' and 'Blog'). A single 'ExecuteUpdate' call can only update the properties of a single entity type. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

Stack trace
```
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteUpdate[TSource](IQueryable`1 source, Expression`1 setPropertyCalls)
   at Program.<<Main>$>d__0.MoveNext() in C:\repo\poc\execute-update-owned\execute-update-owned\Program.cs:line 8
   at Program.<<Main>$>d__0.MoveNext() in C:\repo\poc\execute-update-owned\execute-update-owned\Program.cs:line 8
```

### Include provider and version information

EF Core version: 7.0.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 7.0
Operating system: Windows 11
IDE:  Visual Studio 2022 17.7

**Comment by roji** [comment] 2023-07-24 21:35
Duplicate of #28627

**Comment by roji** [comment] 2023-07-24 21:36
See [this section in the docs](https://learn.microsoft.com/en-us/ef/core/saving/execute-insert-update-delete#navigations-and-related-entities) for how to work around this.

**Closed** 2023-07-26 19:22 UTC
Labels: closed-duplicate, customer-reported
