### ISSUE TITLE
Scaffold Not Building Entities With Correct Capitalization

### ISSUE THREAD

**Issue by coleblarson** [dotnet/efcore#28729] opened 2022-08-15 17:35 UTC
EF Core version: 7.0.0-preview.7.22376.2
Database provider: Sql
Target framework: (e.g. .NET 5.0) 6.0
Operating system: Win 10
IDE: Visual Studio Preview 2022

Scaffold DB context as of preview 6 is no longer replicating capitalization from DB names correctly.   For Example a Database named BBSData scaffolds a context: BbsdataContext and a Column named DNSReason becomes Dnsreason.

**Comment by ajcvickers** [comment] 2022-08-16 09:35
@coleblarson Can you post the full command line call you are using and the `--verbose` output from the tool?

**Comment by ajcvickers** [comment] 2022-08-24 10:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-08-24 10:01 UTC
Labels: customer-reported
