### ISSUE TITLE
Database Creation Parameters

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/efcore#16941] opened 2019-08-04 12:45 UTC
Is there a way to control database creation parameters with EFCore?

For my app, I'd like the database to be created on a specific path of the server and I'd also like certain settings (such as AutoClose) enabled by default.

**Comment by ajcvickers** [comment] 2019-08-05 14:46
Duplicate of #6577

**Closed** 2022-10-16 14:33 UTC
Labels: closed-duplicate, customer-reported
