### ISSUE TITLE
Missing using directive when scaffolding entities from database tables with --context-dir and -o arguments

### ISSUE THREAD

**Issue by dsthode** [dotnet/efcore#17881] opened 2019-09-17 11:15 UTC
I'm generating the entities for my project scaffolding the tables from my database.

If I run the `dotnet-ef` command with the argument `--context-dir`, the generated DbContext file lacks the using directive to the namespace of the generated entities.

For example, running the following command in my project directory (say `c:\projects\dataaccess`)

`dotnet-ef dbcontext scaffold "server=...;database=...;user=...;password=..." microsoft.entityframeworkcore.sqlserver -c EntityMapping -d --use-database-names -o Entities --context-dir .`

The generated entities are in `c:\projects\dataaccess\Entities`, each in the namespace `dataaccess.Entities`, and the DbContext file is generated in `c:\projects\dataaccess\EntityMapping.cs` and lacks the following `using` directive to compile without errors:
```cs
using dataaccess.Entities;
```

**Comment by bricelam** [comment] 2019-09-17 16:52
Duplicate of #17839

**Closed** 2022-10-16 14:42 UTC
Labels: closed-duplicate, customer-reported
