### ISSUE TITLE
Could not load assembly 'TestProj5'. Ensure it is referenced by the startup project 'TestProj5'.

### ISSUE THREAD

**Issue by tpspencer** [dotnet/efcore#6452] opened 2016-09-01 23:35 UTC
Trying to get EFC for SQLite working.
I got it working on one test project, then tried to reproduce it in 3 additional new test projects and am getting this error.

My db context is in the Model's folder in the same namespace as the project.

I am following the example in docs website.
https://docs.efproject.net/en/latest/platforms/uwp/getting-started.html

![efc1](https://cloud.githubusercontent.com/assets/15737661/18187858/d0c56d22-7072-11e6-9473-99f6300e2e69.PNG)
![efc2](https://cloud.githubusercontent.com/assets/15737661/18187859/d0c5bfa2-7072-11e6-9e91-5004a52a77fb.PNG)
![efc3](https://cloud.githubusercontent.com/assets/15737661/18187857/d0c4e0aa-7072-11e6-9daf-efc0160d3366.PNG)
![efc4](https://cloud.githubusercontent.com/assets/15737661/18187856/d0c4a9b4-7072-11e6-9387-9b83f11efe39.PNG)

**Comment by tpspencer** [comment] 2016-09-06 04:26
Any thoughts on this issue?  It would be nice to start working with efc now with my Template10 projects.

**Comment by bricelam** [comment] 2016-09-06 15:54
`x64` was not supported by the Preview 2 tooling. Select x86 as the solution platform before running tools.

![image](https://cloud.githubusercontent.com/assets/1226749/18280811/50b01fa6-740f-11e6-80d8-579eee539af5.png)

This issue should be resolved by our new tooling architecture. (See issue #5334)

**Comment by divega** [comment] 2016-09-07 18:16
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Comment by tpspencer** [comment] 2016-09-07 21:12
>>Select x86 as the solution platform before running tools

Thank you that worked.

**Comment by plipowczan** [comment] 2020-05-26 13:08
In my case I had to remove:
```  
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
   <PlatformTarget>x86</PlatformTarget>
</PropertyGroup>
```
from my csproj project file.

**Comment by JoinDevv** [comment] 2020-12-20 19:31
> In my case I had to remove:
> 
> ```
> <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
>    <PlatformTarget>x86</PlatformTarget>
> </PropertyGroup>
> ```
> 
> from my csproj project file.

thx this works for me

**Closed** 2022-10-16 09:56 UTC
Labels: closed-no-further-action, customer-reported
