### ISSUE TITLE
Nesting HasQueryFilter On Navigation Properties

### ISSUE THREAD

**Issue by zamzowd** [dotnet/efcore#15227] opened 2019-04-01 21:13 UTC
I'm trying to use HasQueryFilter in a multi-tenancy scenario, with multiple tables limited by the tenancy.

This is a feature request for HasQueryFilter to apply when the navigation property is used in another HasQueryFilter.

### Desired Setup
```c#
private string _tenantId;

protected override void OnModelCreating(ModelBuilder builder)
{
  var accountBuilder = builder.Entity<Account>();
  // Base rule to see if the Account is on the desired tenant.
  accountBuilder.HasQueryFilter(x => x.TenantId == _tenantId);

  var orderBuilder = builder.Entity<Order>();
  orderBuilder.HasOne(x => x.Account)
    .WithMany(x => x.Orders)
    .HasForeignKey(x => x.AccountId);
  // Passes if the related Account is not null,
  // i.e. the related Account is on the desired tenant.
  orderBuilder.HasQueryFilter(x => x.Account != null);

  var orderLineBuilder = builder.Entity<OrderLine>();
  orderLineBuilder.HasOne(x => x.Order)
    .WithMany(x => x.OrderLines)
    .HasForeignKey(x => x.OrderId);
  // Passes if the related Order is not null,
  // i.e. the related Order passes,
  // i.e. the related Order's related Account is on the desired tenant.
  orderLineBuilder.HasQueryFilter(x => x.Order != null);

  // Many-to-many between Locations and Accounts
  var locationAccountBuilder = builder.Entity<LocationAccount>();
  locationAccountBuilder.HasOne(x => x.Location)
    .WithMany(x => x.LocationAccounts)
    .HasForeignKey(x => x.LocationId);
  locationAccountBuilder.HasOne(x => x.Account)
    .WithMany(x => x.LocationAccounts)
    .HasForeignKey(x => x.AccountId);
  // Passes if any Accounts pass, i.e. any Accounts are on the desired tenant.
  locationAccountBuilder.HasQueryFilter(x => x.Accounts.Any());

  var locationBuilder = builder.Entity<Location>();
  // Passes if any LocationAccounts pass,
  // i.e. if any LocationAccounts have any Accounts that pass,
  // i.e. if any many-to-many related Accounts are on the desired tenant.
  locationBuilder.HasQueryFilter(x => x.LocationAccounts.Any());
}
```

### Current Behavior
The `HasQueryFilter` expressions defined on navigation parameters used in `HasQueryFilter` do not get applied.

### Desired Behavior
The `HasQueryFilter` expressions apply to navigation properties used inside of `HasQueryFilter` expressions.  That way a "base rule" or rules can be set up once that other related tables depend on, rather than redefined on each `HasQueryFilter`.

**Comment by smitpatel** [comment] 2019-04-01 21:15
Duplicate of #13361

**Closed** 2022-10-16 13:58 UTC
Labels: customer-reported
