### ISSUE TITLE
After using OwnsMany, the generated sql is automatically brought with order by id

### ISSUE THREAD

**Issue by xiedeyou** [dotnet/efcore#18088] opened 2019-09-27 07:38 UTC
After using OwnsMany, the generated sql is automatically brought with order by id.
But in some cases I don't want to sort by id. When I customize the sort, I will generate two sort fields, which greatly affects performance.
[EfCore.Demo.zip](https://github.com/aspnet/EntityFrameworkCore/files/3661504/EfCore.Demo.zip)

### Steps to reproduce

``` C#
 public class DemoDbContext : DbContext
    {
        public DemoDbContext(DbContextOptions options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Weibo>(builder => {
                builder.ToTable("weibos");
                builder.HasKey(s => s.Id);
                builder.Property(s => s.Title).HasMaxLength(200);

                builder.OwnsMany(s => s.Labels, a =>
                {
                    a.ToTable("WeiboLabels");
                    a.HasForeignKey("WeiboId");
                    a.HasKey("WeiboId", nameof(Label.LabelId), nameof(Label.LabelType));
                });
            });
        }
    }

public class Weibo
    {
        public int Id { get; set; }

        public string Title { get; private set; }

        public virtual List<Label> Labels { get;  set; }
    }

    public class Label
    {
        public int LabelId { get; set; }

        public int LabelType { get; set; }
    }
```
When I execute any linq
``` C#
context.Set<Weibo>().FirstOrDefault();
```
Log input.
```
 Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (37ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `w`.`Id`, `w`.`Title`
      FROM `weibos` AS `w`
      ORDER BY `w`.`Id`
      LIMIT 1
```

When I execute any linq
``` C#
context.Set<Weibo>().FirstOrDefault();
```
Log input.
```
 Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `s`.`Id`, `s`.`Title`
      FROM `weibos` AS `s`
      ORDER BY `s`.`Title`, `s`.`Id`
      LIMIT 1
```

EF Core version: 2.2
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework:.Net Core 2.2
Operating system: win 10
IDE: Visual Studio 2019 16.2.1

**Comment by smitpatel** [comment] 2019-09-27 21:14
Duplicate of #17525 

EF Core needs ordering for collection include so it adds it. In your case, since you have owned collection navigation it will be eager loaded automatically.

**Closed** 2022-10-16 14:45 UTC
Labels: closed-no-further-action, customer-reported
