### ISSUE TITLE
Invalid sql generated for foreignkey reference

### ISSUE THREAD

**Issue by cuiliang** [dotnet/efcore#1632] opened 2015-02-16 15:18 UTC
Version:7.0.0-beta4-12265

when
first:`k ef migration add intital`, 
then:`k ef migration apply`

error info:
`System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ')'.`

The sql after 'REFERENCES' is invalid.

``` sql
CREATE TABLE [AspNetRoleClaims] (
    [ClaimType] nvarchar(max),
    [ClaimValue] nvarchar(max),
    [Id] int NOT NULL IDENTITY,
    [RoleId] bigint NOT NULL,
    CONSTRAINT [PK_AspNetRoleClaims] PRIMARY KEY NONCLUSTERED ([Id]),
    CONSTRAINT [FK_AspNetRoleClaims_AspNetRoles_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [Id].[AspNetRoles] ()
```

**Comment by bricelam** [comment] 2015-02-24 19:28
This is a dupe of #1612

**Closed** 2022-10-16 08:51 UTC
Labels: type-bug
