### ISSUE TITLE
TPH Inheritance with shared backing columns call all converters of all derived types

### ISSUE THREAD

**Issue by Dunge** [dotnet/efcore#17135] opened 2019-08-13 20:43 UTC
My issue is extremely similar to #14590.

I have a TPH hierarchy using a discriminator to determine the proper derived type to instantiate. Some of these types map the same database column on different properties on the derived types.

Strangely I don't have the issue reported in #14590 (maybe something changed between 2.2.1 and 2.2.6?). For me, once the entity is instantiated, the proper conversion is always executed in the end result.

The problem is, for every entities that get loaded, every single converters defined on the same column get executed. This is problematic obviously for performance reason, but also if the converter throw an exception.

Example (re-using an nvarchar column called "CustomData"):

    modelBuilder.Entity<Container>(entity =>
    {
        entity.ToTable("Container");
        entity.HasKey(e => e.Id);
        entity.HasDiscriminator<ContainerType>("Type")
                .HasValue<Derived1>(ContainerType.Derived1)
                .HasValue<Derived2>(ContainerType.Derived2)
                .HasValue<Derived3>(ContainerType.Derived3);
    }

    modelBuilder.Entity<Derived1>(entity =>
    {
        entity.HasBaseType<Container>();
        entity.Property(e => e.Options).HasColumnName("CustomData")
            .HasConversion(e => JsonConvert.SerializeObject(e), e => JsonConvert.DeserializeObject<RouteOptions>(e));
    }

    modelBuilder.Entity<Derived2>(entity =>
    {
        entity.HasBaseType<Container>();
        entity.Property(e => e.Accessories).HasColumnName("CustomData")
            .HasConversion(e => e.ToString("D"), e =>(AccessoriesBitfield)Enum.Parse(typeof(AccessoriesBitfield), e));
    }

    modelBuilder.Entity<Derived3>(entity =>
    {
        entity.HasBaseType<Container>();
        entity.Property(e => e.SpecialName).HasColumnName("CustomData");
    }

In this example:
Derived1 property Option is a class that get serialized in json (I know this is bad design in relational database, but that's how it is saved from a legacy system).

Derived2 property Accessories is an enum that have its numeric value converted as a string (again strange I know).

Derived3 property SpecialName is directly a string.

Now I load an entity this way:

    using (var context = new MyDataContext())
    {
        return context.Containers.FirstOrDefault(t => t.Id == id);
    }

If I pass and ID where the data in the database have the type for Derived1 and a json string in the CustomData column, it will throw an exception in the converter of Derived2 because of Enum.Parse.

If I pass and ID where the data in the database have the type for Derived2 and a numeric value in the CustomData column, it will throw an exception in the converter of Derived1 because of JsonConvert.DeserializeObject.

Now let's try to work around this:
If I change the converter of Derived2 to add some validation (which is hard because I can't use TryParse which require an "out" which is not supported in expression trees, so I used regex instead):

    entity.Property(e => e.Accessories).HasColumnName("CustomData")
        .HasConversion(e => e.ToString("D"), e => (string.IsNullOrEmpty(e) || !Regex.IsMatch(e, @"^\d+$")) ? AccessoriesBitfield.All : (AccessoriesBitfield)Enum.Parse(typeof(AccessoriesBitfield), e));

With this change, loading the entity of type Derived1 works great. The regex prevent Enum.Parse from throwing, and when the entity is instantiated it correctly used the Json deserializer to fill the Options property.

Now of course, loading the entity of type Derived2 still throw in the Json deserializer, so I could add additional validation to check the value is a valid json string before trying to deserialize it. But my point is, I shouldn't have to do that right? Why does the converter of the other derived type get called at all? I would have expected the converter to be executed only after it have determined the correct derived type to instantiate and only call the converter on the proper derived type, not to go through all of them.

Additional note: The other issue seems to mention a lot changed related to the "new query pipeline materializer" in EFCore 3.0. Maybe this issue is already gone and fixed. Unfortunately, my solution target the .NET Framework 4.7 so I won't be able to upgrade. Those kind of big changes will never be backported to EFCore 2 right?

### Further technical details
EF Core version: 2.2.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 2.2.6
Operating system: Windows 10 1809
IDE: Visual Studio 2017 15.9.14

**Comment by smitpatel** [comment] 2019-08-13 22:40
It is already fixed in latest preview of EF Core 3.0. Given the nature of the issue and root cause behind it, it cannot be backported to 2.2 (since it is huge breaking change).

**Comment by Dunge** [comment] 2019-08-13 22:53
Thanks, that's good to know.

Knowing this, would you say adding validation rules in the converters an acceptable workaround or would you say it's just searching for trouble because this root cause behind the issue could lead to just more problems?

It would be a possibility to execute a maintenance script on every databases to split the exisitng values into separate columns, but it would break compatibility for other softwares.

**Comment by ajcvickers** [comment] 2019-08-14 19:55
Same root cause as #14590--closing as duplicate.

@Dunge I think for 2.2 the only thing you can do is write the value converters to be resilient to being called even when they should not be.

**Closed** 2022-10-16 14:35 UTC
Labels: closed-duplicate, customer-reported
