### ISSUE TITLE
EF Core 7 - Skip & Take with 0s translate to "WHERE 0 = 1"

### ISSUE THREAD

**Issue by pzaj2** [dotnet/efcore#30041] opened 2023-01-12 11:52 UTC
As described in the title, if a query contains both `Take(0)` and `Skip(0)` the query will still be executed but these will translate to `[Where...] 0 = 1` and in some scenarios lead to a complete rewrite of the query where all `Where` expressions are omitted.

This is confusing and hides the logical bug in the code. I believe that a better-suited behaviour would be to throw an exception or log a warning - this way it'd be easily identifiable.

**Comment by roji** [comment] 2023-01-12 12:18
@pzaj2 there are some cases where the user may pass a variable to Skip or Take, and that value might legitimately contain 0 (coming from some external calculation). EF's results here are correct - return zero rows for Take(0) - and throwing on this would needlessly force users to specifically check before executing the query.

In addition, you can do Take(0) in regular LINQ to Objects, and that works. EF aligns to general LINQ behavior, so throwing would be problematic.

Finally, #29954 tracks optimizing cases like this and not actually contacting the database.

**Comment by pzaj2** [comment] 2023-01-16 12:57
@roji I can see your point. I still think that:
- the translation of Take(0) to WHERE 0 = 1 is very confusing and you can't use query/command logs alone to identify the problem
- logging a warning would be a non-breaking, non-invasive mechanism to allow identifying such cases; alternatively, translating it to a more literal representation (`LIMIT 0` in the case of MySQL and equivalents for other storage engines)

Logging a warning would also complement the optimizations related to ignoring such queries.

To recap:
- throwing an exception would be both invasive and breaking (and inconsistent with LINQ to Objects)
- literally translating such conditions would be backwards compatible but with potential optimizations that'd eliminate querying the database, it's a futile effort
- logging a warning would be backwards compatible and non-invasive and help identify such cases (especially when they're a result of some 3rd party components misconfiguration, etc.)

I'd therefore propose that a warning is logged when a query that must return no results is made (or when optimized - is attempted) against a database.

**Comment by roji** [comment] 2023-01-16 13:12
@pzaj2 can you please submit a minimal, runnable code sample showing where the rewriting to `WHERE 0=1` is occuring? This doesn't happen for a simple query with `Take(0).Skip(0)`.

**Comment by ajcvickers** [comment] 2023-01-24 17:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-01-24 17:30 UTC
Labels: customer-reported
