### ISSUE TITLE
AsSplitQuery undermines OrderBy clause of an Include with a ThenInclude

### ISSUE THREAD

**Issue by pjaffe** [dotnet/efcore#25233] opened 2021-07-09 21:58 UTC
An `.OrderBy(...)` clause in a filtered `.Include(...)` does not take effect as expected.  I empirically isolated it to the combination of *both* a `.ThenInclude(...)` *and* the `.AsSplitQuery()` directive.  If I eliminate one or the other of those, the `.OrderBy(...)` starts working as expected.

I would assume both should interplay nicely based on [Filtered Includes](https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include) being documented as supporting OrderBy clauses, and the noted limitations didn't seem to indicate any incompatibilities with the use of [Split Queries](https://docs.microsoft.com/en-us/ef/core/querying/single-split-queries).

Here is my code block:
```C#
await _dbOps.Db.CustomLists
  .Include(x => x.Items.OrderBy(y => y.DisplaySequence).ThenBy(y => y.Name))
  .ThenInclude(x => x.Restrictions)
  // BUG: The combo of the ThenInclude above + the SplitQuery below undermines the sorting of the Items collection
  // Note that a Take and/or Where would still work fine with the AsSplitQuery in place.
  // Commenting out the AsSplitQuery() causes the OrderBy to take effect as expected
  .AsSplitQuery()
  .ToListAsync()
```
I'm hopeful this is enough to reproduce the problem in whatever test harnesses are in the EF Core project. But if capturing verbose logging from my running system would help, I could grab that.

Again, in brief, the `.OrderBy(...)` clauses above take effect if I either:
- comment out the `.AsSplitQuery()`
- or comment out the ` .ThenInclude(...)`

But I would expect the full clause above to work as written.  This seems to be specific to OrderBy, since a Take or Where is applied as expected in all situations.

EF Core version: 5.0.7
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: (e.g. .NET 5.0)
Operating system: running in a mcr.microsoft.com/dotnet/sdk:5.0.103-focal docker container
IDE: VS Code 1.58.0 using Remote Containers

**Comment by AndriySvyryd** [comment] 2021-07-12 20:05
We are unable to repro this with our models. Please share a small self-contained project that illustrated the issue.

**Comment by pjaffe** [comment] 2021-07-12 20:44
Ugh... I'll see if our team has some time to isolate this in the coming days, but it is probably a low priority for us since we got the expected behavior by disabling `AsSplitQuery()` with minimal performance risk, due to the data set size for that query.

**Comment by ajcvickers** [comment] 2021-07-20 14:40
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:39 UTC
Labels: closed-could-not-reproduce, customer-reported
