### ISSUE TITLE
Creating indexes using data annotation

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/efcore#11634] opened 2018-04-11 17:42 UTC
Now we are to create indexes using Fluent API. Can I know when shall we be able to create indexes in Entity Framework Core using data annotation like Entity Framework 6.2.0?

Thanks

**Comment by smitpatel** [comment] 2018-04-11 17:44
Duplicate of #4050

**Closed** 2022-10-16 12:18 UTC
