### ISSUE TITLE
Package manager prompt hangs

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#10699] opened 2018-01-12 21:00 UTC
Moved from https://github.com/aspnet/EntityFramework6/issues/434 since this is an EF Core scenario.

From VS Feedback:

Package manager prompt is not restored after sucessfully completing add-migration or update-database operation.

PM> update-database
infoinfo:
Applying migration '20171216085326_IssueEditedBy'.
Done.

Closing the Package Manager Console does not help as it is greyed out on the View -> Other Windows list.

Have to restart Visual Studio to get the functionality back.

After running add-migration the prompt does not return.
This is because an instance of the dotnet process is still running.
Killing this process using Task Manager completes the action in Visual Studio and the prompt is restored and I can continue to work without restarting Visual Studio.
The dotnet process is also left running after update-database from the VS package manager console.

I am using MariaDb and the Pomelo.EntityFrameworkCore.MySql NuGet package in a EF Core / AspNet Core 2 solution.

**Comment by ajcvickers** [comment] 2018-01-12 21:03
[IssueTracker.zip](https://github.com/aspnet/EntityFrameworkCore/files/1627475/IssueTracker.zip)

**Comment by bricelam** [comment] 2018-01-26 20:37
I'm not able to repro this with the solution provided. After updating the solution to compile (it was missing some internal NuGet pacakges), the `Add-Migration` and `Update-Database` commands work and PMC is functional.

**Comment by TomCJones** [comment] 2018-04-09 22:36
i have this - perhaps i ran debug on the app before add-migration and then add-migration hung

**Comment by bricelam** [comment] 2018-04-10 01:14
This may be a duplicate of #11066

**Comment by Abenezer** [comment] 2018-10-29 02:29
Same here, i had worked perfectly, but suddenly it started to hang after add-migration. (is there a released update that may start this bug) .. as mentioned when i stop dotnethost.exe i get PMC back

**Comment by Abenezer** [comment] 2018-10-29 22:02
i got the cause .. in my case it's in the startup.cs. 
 ` services.AddSingleton(RabbitHutch.CreateBus(Configuration["MQ:Dev"]));`
(its EasynetMQ service) i still don't get it why this cause dotnethost.exe to keep running after add-migration or update-database. anyways i have to comment this line before a run add-migration

**Comment by Looooooka** [comment] 2019-03-21 11:35
Still exists in 2.2.
Clearly there should be at least some option to detect migrations so we can "skip" code that appears to hang the application shutdown.
In my case there's also no error...the net core instance just stays alive until I kill it.
then immediately 
{
  "migrationFile": "*****\\Migrations\\20190321113059_InitialCreate.cs",
  "metadataFile": "*****\\Migrations\\20190321113059_InitialCreate.Designer.cs",
  "snapshotFile": "*****\\Migrations\\DataContextModelSnapshot.cs"
}
is printed out. 
So that instance is clearly "alive" as if it was booted for normal continuous work

**Comment by Skybladev2** [comment] 2020-11-07 22:57
Same problem still persists. Reproduced with Package Manager Console  or `dotnet ef migrations`.
Any command, say, `Script-Migration`, never ends.
There is a `dotnet.exe` process which, when killed. releases Package Manager Console or .NET CLI with an error message `The pipeline has been stopped`.

**Comment by rogerfar** [comment] 2022-01-17 14:38
It looks like there is something going on with this too:
```
            services.AddHangfire(hangfire => hangfire.UseMemoryStorage());

            services.AddHangfireServer(options =>
            {
                options.WorkerCount = 5;
            });
```
When this is added to `ConfigureServices` PMC will hang.

**Closed** 2022-10-16 12:05 UTC
Labels: closed-could-not-reproduce
