### ISSUE TITLE
Implementing IDataErrorInfo break the database creation

### ISSUE THREAD

**Issue by eiadxp** [dotnet/efcore#13148] opened 2018-08-28 23:12 UTC
When I try to implement IDataErrorInfo interface in my base entity the ORM fail to create the database due to reflection TargetParameterCountException
--

```
Exception message:"Parameter count mismatch." 
Stack trace:
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)\r\n   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)\r\n   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.GetData(Boolean providerValues)\r\n   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateData(IModel model)\r\n   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)\r\n   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)\r\n   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)\r\n   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)\r\n   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()\r\n   at System.Lazy`1.CreateValue()\r\n   at System.Lazy`1.LazyInitValue()\r\n   at System.Lazy`1.get_Value()\r\n   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)\r\n   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()\r\n   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()\r\n   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)\r\n   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()\r\n   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()\r\n   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()\r\n   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()\r\n   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)\r\n   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)\r\n   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator()\r\n   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureDeleted()\r\n   at CM.DataContext.GetLogin(String userName, String password)\r\n   at CM.Contexts.Users.GetLogin(String userName, String password)\r\n   at CM.Contexts.Users.<>c__DisplayClass3_0.<GetLoginAsync>b__0()\r\n   at System.Threading.Tasks.Task`1.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()
```

### Steps to reproduce
1. Create a.NET Standard project and add Microsoft.EntityFrameworkCore.SqlServer package.
2. Create a base entity class that implement IDataErrorInfo interface.
3. Create entity using your base entity.
4. Create your DbContext and expose your main entity in it (Not the base entity).
5. Create another project to consume your library and you will get the exception.

```c#
    public class BaseEntity : INotifyPropertyChanged, IDataErrorInfo
    {
        #region IDataErrorInfo
        [NotMapped] string IDataErrorInfo.this[string propertyName] => "";
        [NotMapped] string IDataErrorInfo.Error => "";
        #endregion

        #region INotifyPropertyChanged
        event PropertyChangedEventHandler PropertyChanged;
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged
        {
            add => PropertyChanged += value;
            remove => PropertyChanged -= value;
        }

        protected virtual bool Set<TValue>(ref TValue oldValue, TValue newValue,
            string relatedProperty = null, [CallerMemberName]string propertyName = null)
        {
            if (Equals(oldValue, newValue)) return false;
            oldValue = newValue;
            NotifyPropertyChanged(propertyName);
            if (!string.IsNullOrWhiteSpace(relatedProperty)) NotifyPropertyChanged(relatedProperty);
            return true;
        }
        protected virtual bool Set<TValue>(ref TValue oldValue, TValue newValue,
            IEnumerable<string> relatedProperties, [CallerMemberName]string propertyName = null)
        {
            if (Equals(oldValue, newValue)) return false;
            oldValue = newValue;
            NotifyPropertyChanged(propertyName);
            foreach (var item in relatedProperties)
                if (!string.IsNullOrWhiteSpace(item)) NotifyPropertyChanged(item);
            return true;
        }

        protected virtual void NotifyPropertyChanged(string propertyName) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        #endregion
    }
    public class User : BaseEntity
    {
        Guid _Id = Guid.NewGuid();
        [Key]
        public Guid ID { get => _Id; set => Set(ref _Id, value); }

        string _Name;
        [StringLength(250, MinimumLength = 3), Required(AllowEmptyStrings = false)]
        public string Name { get => _Name; set => Set(ref _Name, value); }

        string _Password;
        [StringLength(250, MinimumLength = 3), Required(AllowEmptyStrings = false)]
        public string Password { get => _Password; set => Set(ref _Password, value); }

        string _DisplayName;
        [StringLength(250, MinimumLength = 3), Required(AllowEmptyStrings = false)]
        public string DisplayName { get => _DisplayName; set => Set(ref _DisplayName, value); }

        bool _IsEnabled = true;
        public bool IsEnabled { get => _IsEnabled; set => Set(ref _IsEnabled, value); }
    }
    class DataContext : DbContext
    {
        #region Configures
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=CM;Trusted_Connection=True;");
            //base.OnConfiguring(optionsBuilder);
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var users = modelBuilder.Entity<User>();
            users.HasData(new User() { Name = "admin", Password = "1234", DisplayName = "Administrator", IsEnabled = true });
            users.HasIndex(u => u.Name).IsUnique();
            users.HasIndex(u => u.DisplayName).IsUnique();
            base.OnModelCreating(modelBuilder);
        }
        #endregion
        #region Tables
        public DbSet<User> Users { get; set; }
        #endregion

        #region Static Methods
        public static User GetLogin(string userName, string password)
        {
            using (var cxt = new DataContext())
            {
                cxt.Database.EnsureDeleted();
                cxt.Database.EnsureCreated();
                LoginUser = cxt.Users.AsNoTracking().FirstOrDefault(u => u.IsEnabled && 
                                                                         u.Name == userName && 
                                                                         u.Password == password);
            }
            return LoginUser;
        }
        #endregion
    }

```

### Further technical details
EF Core version: Microsoft.EntityFrameworkCore (2.1.2)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.1

**Comment by ajcvickers** [comment] 2018-08-29 22:53
Duplicate of #12605

**Closed** 2022-10-16 13:28 UTC
Labels: closed-duplicate
