### ISSUE TITLE
IsRequired on owned entity properties not working.

### ISSUE THREAD

**Issue by honey-hoper** [dotnet/efcore#21662] opened 2020-07-17 06:50 UTC
I have an Entity which is complex type. It has a model as property which I configured to be an owned entity. But when I configure owned entity property to be not null, it is not working. It always stays `nullable: true` in migrations.

Here's a snippet of configuration
`builder.OwnsOne(e => e.IdProof, nb =>
 {
     nb.Property(it => it.Type)
            .IsRequired()
            .HasMaxLength(Constants.shortLength);
 }`

and corresponding migration snippet

`migrationBuilder.AddColumn<string>(
    name: "IdProof_Type",
    table: "Player",
    maxLength: 255,
    nullable: true);`

### Steps to reproduce

1. Create an entity and add another POCO object as a Property
2. Configure that property as OwnsOne as shown above and in navigationBuilder lambda configure child properties as IsRequired.
3. Create migrations

### Further technical details

EF Core version: 3.1
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.5.4

**Comment by ajcvickers** [comment] 2020-07-17 16:21
Duplicate of #12100

**Closed** 2022-10-16 18:33 UTC
Labels: closed-duplicate, customer-reported
