### ISSUE TITLE
Left Join Bug ?

### ISSUE THREAD

**Issue by Eneuman** [dotnet/efcore#3991] opened 2015-12-06 14:55 UTC
Hi!

Running the following code will generate a SQL with an INNER JOIN between A and Group, resulting in no A records being returned (if A has no group).

```
public class Group
{
   public int Id { get; set; }
   public List<A> A { get; set; }
 }

 public class A
{
   public int Id { get; set; }
   public string Name { get; set; }
   public int? GroupId { get; set; }
   public Group Group { get; set; }
}

 var items = _dbContext.A.Where(t => t.Name == 'Test').AsQueryable();

var query = items.Select(i => new Models.MyModel
{
  Id = i.Id,
  Name = i.Name,
  Groupname = i.Group != null ? i.Group.Name : string.Empty
});

 var result = query.ToList();
```

Is this by design or a bug?

**Comment by Eneuman** [comment] 2015-12-06 15:40
Using from and DefaultIfEmpty() still produces a INNER JOIN

**Comment by maumar** [comment] 2015-12-06 18:47
Duplicate of https://github.com/aspnet/EntityFramework/issues/3186

**Closed** 2022-10-16 09:19 UTC
