### ISSUE TITLE
SQLite Bool_not_equal_nullable_int_HasValue fails after merge from release/6.0

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#27162] opened 2022-01-11 13:02 UTC
Test expects 12 tracked entities, but gets 18 on SQLite. SQL Server results in the expected 12.

**Comment by roji** [comment] 2022-01-11 19:03
This was fixed in 6.0 via #26652 ("big hammer" patch), but has not yet been fixed in main in the proper way (without adding lots of parentheses everywhere): #26767 tracks that. @ajcvickers I see you've already skipped this test, so I'll just fix #26767 soon.

**Comment by roji** [comment] 2022-01-11 19:03
Duplicate of #26767

**Closed** 2022-10-16 20:21 UTC
Labels: closed-duplicate
