### ISSUE TITLE
HasDefaultValueSql("getdate()") does not work with DateTime as explained in the documentation

### ISSUE THREAD

**Issue by harissecic** [dotnet/efcore#13808] opened 2018-10-30 14:58 UTC
Does not work as expected. If the DateTime is used inside Model/Entity it will default to default(DateTime) and SQL one will be ignored which makes this useless when using DateTime.

Example here: https://docs.microsoft.com/en-us/ef/core/modeling/relational/default-values

**Comment by ajcvickers** [comment] 2018-10-30 16:32
@harissecic Works for me--see code below. Can you post a runnable project/solution or a code listing like that below that demonstrates the behavior you are seeing?

```C#
public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    public DbSet<Blog> Blogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>()
            .Property(b => b.Created)
            .HasDefaultValueSql("getdate()");
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }
    public DateTime Created { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog());

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            Console.WriteLine(context.Blogs.Single().Created);
        }
    }
}
```
Output:
```
10/30/2018 9:29:59 AM
Press any key to continue . . .
```

**Comment by harissecic** [comment] 2018-11-01 09:12
@ajcvickers I use same logic, have some models which dates are set to getdate() for sql but end result is default DateTime from C# ("0001-01-01 00:00:00.0000000"). So there is no code that I can post which is related to this. I also dropped the database and removed migrations manually generated again these this and these migration do contain getdate() I've also checked that but any time I run API which has .Migrate() or run Update-Database manualy it uses this default date from C#.

**Comment by smitpatel** [comment] 2018-11-01 16:45
Probably, if you are adding a column of `DateTime` in existing table using Alter Column, you need to provide a default value for existing columns. That is where we may be using `default(T)`.

**Comment by harissecic** [comment] 2018-11-02 07:34
> @harissecic Can you provide some more details on what you mean by, " any time I run API which has .Migrate() or run Update-Database manually it uses this default date from C#?" In what way does it use the default date?

I guessed this by having ("0001-01-01 00:00:00.0000000") as a value in database for these fields. As far as I know this is default value for DateTime in C#.



> Probably, if you are adding a column of `DateTime` in existing table using Alter Column, you need to provide a default value for existing columns. That is where we may be using `default(T)`.

Not the case. Date columns were new. Migrations added for them. After all this I removed migrations and the database manually, so I deleted files and dropped the database and generated new ones then let the migrations create the database and fill it. Don't see this having anything to do with existing columns (no columns were DateTime type before this addition).

On the other hand I do have the Auditable abstract class which is extended by most of the entities in code and this class contains dates. Don't see this as potential problem as the migrations generate good code as far as I can see. But anyway thanks for your help I'll try to investigate what causes this and post reply back.

**Comment by ajcvickers** [comment] 2018-11-12 17:22
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:38 UTC
Labels: closed-could-not-reproduce, customer-reported
