### ISSUE TITLE
Invalid sql with aliased ternary clause

### ISSUE THREAD

**Issue by KallDrexx** [dotnet/efcore#13869] opened 2018-11-02 21:41 UTC
When a ternary operation is used with an aliased field, EF Core is generating invalid sql

### Steps to reproduce
Add the following table

```sql
create table SomeData (
    Id int not null identity primary key,
    UserId int not null,
    DateOfService datetime2 not null,
    BalanceDue money
)
```

Now have EF core scaffold a db context for you, then set your main method to be:

```C#
        static void Main(string[] args)
        {
            var results = new testContext().SomeData
                .Where(x => x.UserId == 5)
                .Select(x => new
                {
                    x.UserId,
                    Age = EF.Functions.DateDiffDay(x.DateOfService, DateTime.UtcNow),
                    x.BalanceDue
                })
                .GroupBy(x => x.UserId)
                .Select(x => new
                {
                    UserId = x.Key,
                    Current = x.Sum(y => y.Age <= 30 ? y.BalanceDue : 0),
                    PrevMonth = x.Sum(y => y.Age > 30 && y.Age <= 60 ? y.BalanceDue : 0)
                })
                .ToArray();
        }
```

This triggers the following exception:

```
System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Incorrect syntax near the keyword 'AS'.
  Source=.Net SqlClient Data Provider
```

EF profiler shows the following sql

```sql
SELECT [x].[UserId], SUM(CASE
    WHEN DATEDIFF(DAY, [x].[DateOfService], GETUTCDATE()) AS [Age] <= 30
    THEN [x].[BalanceDue] ELSE 0.0
END) AS [Current], SUM(CASE
    WHEN (DATEDIFF(DAY, [x].[DateOfService], GETUTCDATE()) AS [Age] > 30) AND (DATEDIFF(DAY, [x].[DateOfService], GETUTCDATE()) AS [Age] <= 60)
    THEN [x].[BalanceDue] ELSE 0.0
END) AS [PrevMonth]
FROM [SomeData] AS [x]
WHERE [x].[UserId] = 5
GROUP BY [x].[UserId]
```

This is bad sql as the `AS [Age]` is invalid in it's current placement.

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.7

**Comment by ajcvickers** [comment] 2018-11-05 19:19
@smitpatel to find duplicate.

**Comment by smitpatel** [comment] 2018-11-05 20:14
Duplicate of #12826

**Closed** 2022-10-16 13:38 UTC
Labels: customer-reported
