### ISSUE TITLE
MySQL EnityFramework Errors in MAUI

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#30189] opened 2023-02-01 10:21 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MySQL-EnityFramework-Errors-in-MAUI/10259732)._

---
[severity:I'm unable to use this version]
I'm trying to add EnityFramework for MySQL into a new simple MAUI project. Tried several times using MySQL page's (below) options. All failed.

1. Started New MAUI Blazor project - which compiled fine by itself
2. Did 2 MySQL steps to add EnityFramework - per their site/page https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core-scaffold-example.html#connector-net-entityframework-core-scaffold-packagemgr
(a) tried diff "Install-Package MySql.EntityFrameworkCore -Version" 's "- xxxxxx" since connector not specifed in .net MAUI
(b) added "Microsoft.EntityFrameworkCore.Tools"
3. Before doing anything else just wanted to see if it would Build - fails each time with following Errors:
(a) Severity	Code	Description	Project	File	Line	Suppression State
Error	APPX1101	Payload contains two or more files with the same destination path 'TestMySQLEnityFramework.deps.json'. Source files: 
D:\Dev\Blazor\Dev\TestMySQLEnityFramework\TestMySQLEnityFramework\obj\Debug\net6.0-windows10.0.19041.0\win10-x64\TestMySQLEnityFramework.deps.json
D:\Dev\Blazor\Dev\TestMySQLEnityFramework\TestMySQLEnityFramework\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\TestMySQLEnityFramework.deps.json	TestMySQLEnityFramework	C:\Users\SnowEagle\.nuget\packages\microsoft.windowsappsdk\1.1.3\buildTransitive\Microsoft.Build.Msix.Packaging.targets	1479	
(b) Severity	Code	Description	Project	File	Line	Suppression State
Error	APPX0002	Task 'WinAppSdkRemovePayloadDuplicates' failed. Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
	TestMySQLEnityFramework	C:\Users\SnowEagle\.nuget\packages\microsoft.windowsappsdk\1.1.3\buildTransitive\Microsoft.Build.Msix.Packaging.targets	1479	
4. Searched the Web & found no Real Answers

Please help resolve or give a reasonable workaround, ASAP. 

Thanks,
Tom

---
#### Feedback Bot on 1/24/2023, 07:37 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2023-02-01 20:22
Please try with the [Pomelo MySQL provider](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql). If this still doesn't work, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-02-15 12:19
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-02-15 12:19 UTC
