### ISSUE TITLE
Add new migration fails but update-database works

### ISSUE THREAD

**Issue by KangJiYoung** [dotnet/efcore#7184] opened 2016-12-05 08:21 UTC
### Steps to reproduce
I upgraded a project from .NET Core and EF Core 1.0 to 1.1

### The issue
When I run add-migration it gives me this error:

> `System.InvalidOperationException: The current CSharpHelper cannot scaffold literals of type 'System.Collections.Immutable.ImmutableSortedDictionary`2[System.Reflection.PropertyInfo,System.Type]'. Configure your services to use one that can. 
>    at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpHelper.UnknownLiteral(Object value)
>     at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateAnnotation(IAnnotation annotation, IndentedStringBuilder stringBuilder) 
>     at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityTypeAnnotations(IEntityType entityType, IndentedStringBuilder stringBuilder) 
>     at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityType(String builderName, IEntityType entityType, IndentedStringBuilder stringBuilder) 
>     at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityTypes(String builderName, IReadOnlyList`1 entityTypes, IndentedStringBuilder stringBuilder) 
>     at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.Generate(String builderName, IModel model, IndentedStringBuilder stringBuilder) 
>     at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMetadata(String migrationNamespace, Type contextType, String migrationName, String migrationId, IModel targetModel) 
>     at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace)
>     at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType) 
>     at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.Execute(CommonOptions commonOptions, String name, String outputDir, String context, String environment, Action`1 reporter) 
>    at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.<>c__DisplayClass0_0.<Configure>b__0()
>     at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
>     at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
>  The current CSharpHelper cannot scaffold literals of type 'System.Collections.Immutable.ImmutableSortedDictionary`2[System.Reflection.PropertyInfo,System.Type]'. Configure your services to use one that can. `

### Further technical details

EF Core version: 1.1
Operating system: Windows 10 x64
Visual Studio version: 2015

**Comment by smitpatel** [comment] 2016-12-05 19:33
dupe of #6520 
You need to align tooling and runtime packages versions. Preview2 tooling does not work with 1.1 runtime.

**Comment by KangJiYoung** [comment] 2016-12-05 20:41
I have tried to use Preview 4 and it gives me another error:
`dotnet ef unrecognised command` - something like this

**Comment by smitpatel** [comment] 2016-12-05 21:00
Are you using full .net (like net451) or .net core?

**Comment by KangJiYoung** [comment] 2016-12-05 21:02
Tried both with net451 and net452

**Comment by smitpatel** [comment] 2016-12-05 21:45
Then you are hitting issue #7071 
You can use `1.0.0-preview3-final` version of `EF.Tools.Dotnet` package and it will work correctly.

**Comment by KangJiYoung** [comment] 2016-12-07 10:37
Ok so I tried what you suggested and now I get this error:
`Cannot execute this command because the version of Microsoft.EntityFrameworkCore.Design installed is not compatible with this tool.`

**Comment by bricelam** [comment] 2016-12-07 16:48
Could you share your `packages.config`/`project.json` file?

**Comment by KangJiYoung** [comment] 2016-12-08 08:35
Sure, I have 2 projects, one is Data where I keep Migrations/Entities/DbContext and one is Web where I create a migration/update etc.
Data project.json:
```
{
  "version": "1.0.0-*",

  "buildOptions": {
    "embed": {
      "include": [ "StoredProcedures/*.sql", "CacheSeed/*.sql" ]
    }
  },

  "dependencies": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview3-final",
    "BadgeMedia.Common": "1.0.0-*",
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0"
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final"
  },

  "frameworks": {
    "net452": {
    }
  }
}
```
Web project.json
```
{
  "userSecretsId": "aspnet-BadgeMedia.Web-4563fa87-9309-43e5-b353-2f7b7b397cc9",
  "version": "1.3.0",
  "dependencies": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Data": "1.0.0-*",
    "Microsoft.AspNet.Identity.Core": "2.2.1",
    "EvoHtmlToPdf_Azure_Client": "6.16.0",
    "EvoHtmlToPdf_x64": "6.16.0",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
    "PaulMiami.AspNetCore.Mvc.Recaptcha": "1.1.1",
    "Serilog.Sinks.RollingFile": "3.2.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "System.Interactive.Async": "3.1.1",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Mvc.Core": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.Session": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.Extensions.Caching.SqlServer": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Serilog.Extensions.Logging": "1.3.1",
    "Serilog.Sinks.MSSqlServer": "4.2.0",
    "AutoMapper": "5.2.0",
    "EO.Pdf": "16.2.72",
    "EO.WebBrowser": "16.2.72",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview3-final"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    },
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final"
  },

  "frameworks": {
    "net452": {
      "frameworkAssemblies": {
        "System.Drawing": "4.0.0.0"
      }
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "copyToOutput": [ "appsettings.json", "evointernal.dat" ]
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "npm install", "grunt prod" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

**Comment by bricelam** [comment] 2016-12-08 16:27
Try installing version 1.1.0 of Microsoft.EntityFrameworkCore.Design.

**Closed** 2022-10-16 10:45 UTC
Labels: closed-no-further-action
