### ISSUE TITLE
[question]performance improve

### ISSUE THREAD

**Issue by ZhiqiangTao** [dotnet/efcore#14438] opened 2019-01-16 05:53 UTC
why does the series of EF  not implement or integrate [https://entityframework-extensions.net/](url) by default, it seems more perfomance! .........

**Comment by smitpatel** [comment] 2019-01-16 07:51
Duplicate of #795

**Comment by ajcvickers** [comment] 2019-01-17 18:13
@ZhiqiangTao Functionality existing in third-party libraries is something we encourage. It helps build a better ecosystem overall. That being said, we also consider well-written, robust PRs to add functionality to EF Core.

**Closed** 2022-10-16 13:47 UTC
Labels: closed-no-further-action, customer-reported
