### ISSUE TITLE
Can't zip database file in 6.0.0+ update as connection logic is being held after query completed

### ISSUE THREAD

**Issue by SaviorXTanren** [dotnet/efcore#27797] opened 2022-04-10 22:15 UTC
## Bug information

Since the 6.0.0 update for Microsoft.Data.Sqlite, attempting to zip the contents of a sqlite database after doing any form of connection activity to it throws a System.IO.IOException when attempting to access that file. Of note, attempting to copy the file doesn't have this issue, only when zipping it. This worked previously on version 5.0.15 without issue.

## Code

See attached ZIP for full sample with sample sqlite database:

[Program.zip](https://github.com/dotnet/efcore/files/8460027/Program.zip)

```
using Microsoft.Data.Sqlite;
using System.IO.Compression;

Console.WriteLine("Opening database and running select query");

try
{
    using (SqliteConnection connection = new SqliteConnection("Data Source=" + "test.sqlite3"))
    {
        await connection.OpenAsync();
        using (SqliteCommand command = new SqliteCommand("SELECT * FROM Test", connection))
        {
            using (SqliteDataReader reader = command.ExecuteReader())
            {
                while (reader.Read())
                {
                    try
                    {
                        Console.WriteLine("--- Row ---");

                        for (int i = 0; i < reader.FieldCount; i++)
                        {
                            Console.WriteLine($"{reader.GetName(i)} - {reader.GetValue(i)}");
                        }
                    }
                    catch (Exception ex) { Console.WriteLine(ex.ToString()); }
                }
            }
        }
    }
}
catch (Exception ex)
{
    Console.WriteLine(ex.ToString());
}

Console.WriteLine("Attempting to copy database file");

try
{
    if (File.Exists("copy-test.sqlite3"))
    {
        File.Delete("copy-test.sqlite3");
    }

    File.Copy("test.sqlite3", "copy-test.sqlite3", overwrite: true);

    Console.WriteLine("Copy Complete");
}
catch (Exception ex)
{
    Console.WriteLine(ex.ToString());
}

Console.WriteLine("Attempting to zip database file");

try
{
    if (File.Exists("test.zip"))
    {
        File.Delete("test.zip");
    }

    using (ZipArchive zipFile = ZipFile.Open("test.zip", ZipArchiveMode.Create))
    {
        zipFile.CreateEntryFromFile("test.sqlite3", Path.GetFileName("test.sqlite3"));
    }

    Console.WriteLine("Zip complete");
}
catch (Exception ex)
{
    Console.WriteLine(ex.ToString());
}
```

## Stack trace

```
System.IO.IOException: The process cannot access the file 'C:\Users\savio\source\repos\ConsoleApp3\ConsoleApp3\bin\Debug\net6.0\test.sqlite3' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.Compression.ZipFileExtensions.DoCreateEntryFromFile(ZipArchive destination, String sourceFileName, String entryName, Nullable`1 compressionLevel)
   at System.IO.Compression.ZipFileExtensions.CreateEntryFromFile(ZipArchive destination, String sourceFileName, String entryName)
   at Program.<Main>$(String[] args) in C:\Users\savio\source\repos\ConsoleApp3\ConsoleApp3\Program.cs:line 68
```

## Version information

Microsoft.Data.Sqlite version: 6.0.3
Target framework: .NET 6.0
Operating system: Windows 10

**Comment by roji** [comment] 2022-04-11 11:20
Duplicate of #26580

**Comment by roji** [comment] 2022-04-11 11:20
This is by design, [see breaking change note for 6.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes#connection-pool).

The SQLite provider now pools connections, improving connection speed significantly but keeping connections open. You can disable pooling by adding `Pooling=false` to the connection string or calling `SqliteConnection.ClearAllPools()` at the point where you want them to be closed.

**Closed** 2022-10-16 20:31 UTC
Labels: closed-duplicate, customer-reported
