### ISSUE TITLE
DbContext Models are not cached throughout xUnit test run

### ISSUE THREAD

**Issue by gojanpaolo** [dotnet/efcore#11333] opened 2018-03-20 00:10 UTC
See https://github.com/aspnet/EntityFrameworkCore/issues/1906#issuecomment-374352462

Here are the test results that I got.
![image](https://user-images.githubusercontent.com/16026608/37628678-7271d7b8-2ba8-11e8-9efd-72f283443a87.png)

The `CacheTestClassXXX` classes use a simplified version of the work around described in https://github.com/aspnet/EntityFrameworkCore/issues/1906#issuecomment-374320307.

Notice that only `CacheTestClass1` had the overhead of `DbContext` model creation.
But the `TestClassXXX` classes all had the overhead.

### Steps to reproduce
1. Create Class Library (.NET Framework 4.6.1) project.
2. Add Dependencies (Nuget)... see below for list of dependencies
3. Paste code below..
```C#
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using System;
using Xunit;

public abstract class TestBase : IDisposable
{
    private readonly SqliteConnection _connection;
    protected readonly DbContextOptions<DbContext> _options;
    public TestBase()
    {
        _connection = new SqliteConnection("DataSource=:memory:");
        _connection.Open();
        _options = new DbContextOptionsBuilder<DbContext>()
            .UseSqlite(_connection)
            .Options;
        using (var context = new DbContext(_options))
        {
            context.Database.EnsureCreated();
        }
    }
    public void Dispose()
    {
        _connection.Close();
    }

    [Fact]
    public void DummyTestMethod() { }
}

public class TestClass1 : TestBase { }

public class TestClass2 : TestBase { }

public class TestClass3 : TestBase { }

[Collection(nameof(DbContextCache))]
public class CacheTestClass1 : TestBase { }

[Collection(nameof(DbContextCache))]
public class CacheTestClass2 : TestBase { }

[Collection(nameof(DbContextCache))]
public class CacheTestClass3 : TestBase { }

[CollectionDefinition(nameof(DbContextCache))]
public class DbContextCache : ICollectionFixture<object> { }
```

### Dependencies 
microsoft.entityframeworkcore.sqlite v2.0.2
xunit v2.3.1
xunit.runner.visualstuio v2.3.1

### Further technical details
.NET Framework 4.6.1
VS 2017 15.6.1
Windows 7

cc: @ajcvickers

**Comment by ajcvickers** [comment] 2018-03-22 02:43
@gojanpaolo I was able to reproduce this. The issue is that xunit (or the runner) is creating a new app domain for each test collection. This can be good for isolation, but does defeat EF caching. I believe that there are options to turn of this behavior in xunit, so that might be cleaner than what you have above. Also, when running on .NET Core there are no app domains, so xunit will never have this behavior there. (Unless they simulate it with multiple processes or something like that.) Closing as there is no EF actionable issue here.

**Comment by smitpatel** [comment] 2018-03-22 03:07
For more info on how to configure xunit not to use appdomains
https://xunit.github.io/docs/configuring-with-json

**Comment by gojanpaolo** [comment] 2018-03-22 13:32
@ajcvickers I see. Thank you for taking the time to look into this. :)
@smitpatel Awesome! Thanks for the link.

**Closed** 2022-10-16 12:14 UTC
Labels: closed-external
