### ISSUE TITLE
Add CancellationToken to IQueryable.AsAsyncEnumerable

### ISSUE THREAD

**Issue by rick-de-water** [dotnet/efcore#18818] opened 2019-11-08 21:19 UTC
Lets make a simple repository style wrapper around a database context!
```C#
public IEnumerable<Job> GetByPipeline(int pipelineId)
{
    return context.Jobs.Where(job => job.Pipeline.Id == pipelineId);
}
```

Easy! Now lets make it async!
```C#
public IAsyncEnumerable<Job> GetByPipeline(int pipelineId)
{
    return context.Jobs.Where(job => job.Pipeline.Id == pipelineId).AsAsyncEnumerable();
}
```
It worked! Now lets add a `CancellationToken`!
```C#
public IAsyncEnumerable<Job> GetByPipeline(int pipelineId, CancellationToken cancellationToken)
{
    return context.Jobs.Where(job => job.Pipeline.Id == pipelineId).AsAsyncEnumerable(cancellationToken);
}
```
> error CS1501: No overload for method 'AsAsyncEnumerable' takes 1 arguments

Uh oh! Maybe we can use `WithCancellation`?
```C#
public IAsyncEnumerable<Job> GetByPipeline(int pipelineId, CancellationToken cancellationToken)
{
    return context.Jobs.Where(job => job.Pipeline.Id == pipelineId).AsAsyncEnumerable().WithCancellation(cancellationToken);
}
```

> error CS0029: Cannot implicitly convert type 'System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable<Astra.Domain.Entities.Job>' to 'System.Collections.Generic.IAsyncEnumerable<Astra.Domain.Entities.Job>'

`WithCancellation` does not return an `IAsyncEnumerable`!
Ok... I guess we can loop over it ourselves in an async function?
```C#
public async IAsyncEnumerable<Job> GetByPipeline(int pipelineId, CancellationToken cancellationToken)
{
    await foreach(var job in context.Jobs.Where(job => job.Pipeline.Id == pipelineId)
        .AsAsyncEnumerable()
        .WithCancellation(cancellationToken))
    {
        yield return job;
    }
}
```

It compiles, but since this library function now has await in it, we should probably `ConfigureAwait` as well.
```C#
public async IAsyncEnumerable<Job> GetByPipeline(int pipelineId, CancellationToken cancellationToken)
{
    await foreach(var job in context.Jobs.Where(job => job.Pipeline.Id == pipelineId)
        .AsAsyncEnumerable()
        .WithCancellation(cancellationToken)
        .ConfigureAwait(false))
    {
        yield return job;
    }
}
```

Pfew I think we're done........wait. A new warning?

> warning CS8425: Async-iterator 'JobRepository.GetByPipeline(int, CancellationToken)' has one or more parameters of type 'CancellationToken' but none of them is decorated with the 'EnumeratorCancellation' attribute, so the cancellation token parameter from the generated 'IAsyncEnumerable<>.GetAsyncEnumerator' will be unconsumed

`EnumeratorCancellationAttribute` to the rescue!

```C#
public async IAsyncEnumerable<Job> GetByPipeline(int pipelineId, [EnumeratorCancellation] CancellationToken cancellationToken)
{
	await foreach(var job in context.Jobs.Where(job => job.Pipeline.Id == pipelineId)
		.AsAsyncEnumerable()
		.WithCancellation(cancellationToken)
		.ConfigureAwait(false))
	{
		yield return job;
	}
}
```
Isn't she beautiful?

...
...
...

Please add a `CancellationToken` parameter to `AsAsyncEnumerable`. Thanks.

**Comment by smitpatel** [comment] 2019-11-08 21:25
The pain you went through, exactly same I went through while trying to add CancellationToken to the method. You can also remove EF from picture. If you are using any method which returns IAsyncEnumerable<T>, you cannot pass cancellationToken unless you go through above exercise. It's beautiful but the beauty is created by BCL (especially result type of WithCancellation() being different. ) I would suggest filing issue with them if you want to suggest any changes.
Since all the methods returning IAsyncEnumerable (EF or without EF) hits the same fate, this is how we suggest to use the API.
```C#
await foreach (var element in GetByPipeline(pipelineId).WithCancellation(cancellationToken))
{
///
}
```

**Comment by rick-de-water** [comment] 2019-11-08 21:42
> The pain you went through, exactly same I went through while trying to add CancellationToken to the method. 

It gives me comfort knowing I'm not alone.

> created by BCL

I remember reading somewhere that `ConfiguredCancelableAsyncEnumerable` not implementing `IAsyncEnumerable` was a design decision. And since pretty much every other async `IQueryable` methods support `CancellationToken`, I figured I would have more luck here with a small change. It only needs to be done once, so the higher up the chain the better. But I'll definitely consider also posting an issue on the corefx repository.

**Comment by smitpatel** [comment] 2019-11-08 22:17
> pretty much every other async IQueryable methods support CancellationToken

Is there a method we have which returns IAsyncEnumerable & also support cancellationToken? EF Core provides async methods mainly for single result (where enumerable is not returned) or methods which enumerates and populate collection objects. They all take cancellationToken since they enumerate asynchronously inside the body to generate the result (rather than streaming).

**Comment by ajcvickers** [comment] 2019-11-11 20:22
Closing as `by-design` since, as @smitpatel says, this is how cancellation support was designed for the async enumerable language feature. If there is something simple we could do in EF to make the experience easier, then we would consider doing that. As it stands, we are limited by the language feature.

**Closed** 2022-10-16 14:55 UTC
Labels: closed-external, customer-reported
