### ISSUE TITLE
Setting entity state cause it to be added to a tracked collection

### ISSUE THREAD

**Issue by zehavibarak** [dotnet/efcore#22385] opened 2020-09-03 08:35 UTC
### Steps to reproduce

``` C#
class A {
  public int Id {get; set;}
  public IList<B> Bs {get; set;}
}
class B {
  public int Id {get; set;}
}

class MyContext : DbContext {
   public DbSet<A> As {get; set;}
   public DbSet<B> Bs {get; set;}
}
using(var store = new MyContext()) {
   store.Add(new A {
      Bs = new {new B {} }
   });
   store.SaveChanges();
   var a = store.As.Include(a=> a.Bs).First();
   var b = a.Bs.First();
   a.Bs.Remove(b);
   Console.Write(a.Bs.Count()); // zero
   store.Entry(b).State = EntityState.Deleted; // <- adds `b` to `a` Bs collection
   Console.Write(a.Bs.Count()); // should have been zero
}
```

**Comment by ajcvickers** [comment] 2020-09-08 22:37
@zehavibarak I am not able to reproduce this in EF Core 3.1.8 or the latest daily build of EF Core 5.0. What version of EF Core are you using?

My repro code:

```C#
public class SomeDbContext : DbContext
{
    private static readonly ILoggerFactory
        Logger = LoggerFactory.Create(x => x.AddConsole());//.SetMinimumLevel(LogLevel.Debug));
    
    public DbSet<A> As { get; set; }
    public DbSet<B> Bs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .EnableSensitiveDataLogging()
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=TestX;ConnectRetryCount=0");
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }

        using(var store = new SomeDbContext())
        {
            store.Add(new A
            {
                Bs = new List<B> {new B()}
            });
                
            store.SaveChanges();
                
            var a = store.As.Include(a=> a.Bs).First();
            var b = a.Bs.First();
            a.Bs.Remove(b);
            
            Console.Write(a.Bs.Count()); // zero
            
            store.Entry(b).State = EntityState.Deleted; // <- adds `b` to `a` Bs collection
            
            Console.Write(a.Bs.Count()); // should have been zero
        }
    }
}

public class A
{
    public int Id { get; set; }
    public IList<B> Bs { get; set; }
}

public class B
{
    public int Id { get; set; }
}
```

**Comment by zehavibarak** [comment] 2020-09-09 05:01
Dropped a line in the repro: in the code, the B obj should be Detached, then Deleted.

```c#
                var a = store.As.Include(a => a.Bs).First();
                var b = a.Bs.First();
                a.Bs.Remove(b);
                store.Entry(b).State = EntityState.Detached; // <- here

                Console.WriteLine($"1st: {a.Bs.Count()}"); // zero

                store.Remove(b); // <- adds `b` to `a` Bs collection

                Console.WriteLine($"2nd: {a.Bs.Count()}"); // should have been zero
```
While this may not seems to be real code, it demonstrates how Unattached entity is being added t collection, when set as Deleted.

**Comment by ajcvickers** [comment] 2020-09-09 18:10
@zehavibarak This is expected because calling Remove on the context re-attaches the entity and fixes up its relationships before marking it as Deleted. Why are you detaching the entity and then re-attaching it again?

**Comment by zehavibarak** [comment] 2020-09-09 19:53
The scenario we have is of two different instances of the same model and model id that are being compared. The manipulation of one of them - influence the other. What we wish to accomplish is applying changes that were made between the two instances to the database. So we delete a record - only to find it is being added back, making our instance muted from original.

**Comment by zehavibarak** [comment] 2020-09-09 20:06
Again, we take an instance of a model that was were deserialized and never retrieved from EF and compare it with a second instance that too was not retrieved, manipulate them to force EF to apply changes between the two to backing tables.

**Comment by ajcvickers** [comment] 2020-09-11 19:58
What specifically do you mean by, " So we delete a record - only to find it is being added back?" By "delete" do you mean mark as deleted in the context, or do you mean remove from some collection of related entities?

**Comment by zehavibarak** [comment] 2020-09-13 12:02
We set the entity state to Deleted, which causes it to be added back to collection, as the original code demonstrates. It shouldn't, since code may relay on the record not being there prior to SaveChanges(),.

**Comment by ajcvickers** [comment] 2020-09-14 18:25
@zehavibarak Deleted entities are not removed from associated collections until SaveChanges is called which is when the entity is actually deleted, as opposed to being marked to be deleted. You can explicitly remove the entity from the related collection _while the entity is being tracked_ and EF Core won't add it back. However, if the EF is detached, then that information is lost and when the entity is tracked again.

**Comment by zehavibarak** [comment] 2020-09-14 18:35
Would marking in Unchanged, then removing it from collection and marking it Deleted will prevent it from being added to collection?

**Comment by zehavibarak** [comment] 2020-09-14 19:13
Setting the entity state to Unchanged and then marking it Deleted doesn't work either.

**Comment by ajcvickers** [comment] 2020-09-17 19:49
@zehavibarak Here's a runnable example using Unchanged entitites:

```C#
public class SomeDbContext : DbContext
{
    private static readonly ILoggerFactory
        Logger = LoggerFactory.Create(x => x.AddConsole());//.SetMinimumLevel(LogLevel.Debug));

    public DbSet<A> As { get; set; }
    public DbSet<B> Bs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .EnableSensitiveDataLogging()
            .UseSqlServer(Your.SqlServerConnectionString);
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new A
            {
                Bs = new List<B> {new B()}
            });

            context.SaveChanges();
        }

        using(var context = new SomeDbContext())
        {
            var a = context.As.Include(a=> a.Bs).First();
            var b = a.Bs.First();

            Console.WriteLine($"a is {context.Entry(a).State}"); // Unchanged
            Console.WriteLine($"b is {context.Entry(b).State}"); // Unchanged
            Console.WriteLine($"a.Bs.Count is {a.Bs.Count}"); // 1

            a.Bs.Remove(b);

            Console.WriteLine($"a is {context.Entry(a).State}"); // Unchanged
            Console.WriteLine($"b is {context.Entry(b).State}"); // Modified
            Console.WriteLine($"a.Bs.Count is {a.Bs.Count}"); // 0

            context.Entry(b).State = EntityState.Deleted;

            Console.WriteLine($"a is {context.Entry(a).State}"); // Unchanged
            Console.WriteLine($"b is {context.Entry(b).State}"); // Deleted
            Console.WriteLine($"a.Bs.Count is {a.Bs.Count}"); // 0

            context.SaveChanges();

            Console.WriteLine($"a is {context.Entry(a).State}"); // Unchanged
            Console.WriteLine($"b is {context.Entry(b).State}"); // Detached
            Console.WriteLine($"a.Bs.Count is {a.Bs.Count}"); // 0
        }
    }
}

public class A
{
    public int Id { get; set; }
    public IList<B> Bs { get; set; }
}

public class B
{
    public int Id { get; set; }
}
```

**Closed** 2022-10-16 18:39 UTC
Labels: closed-no-further-action, customer-reported
