### ISSUE TITLE
Multiple includes results in empty reference

### ISSUE THREAD

**Issue by neridonk** [dotnet/efcore#10725] opened 2018-01-19 07:52 UTC
Multiple includes  results in empty reference.

### Steps to reproduce

```
 employee
       .Include(o => o.Details).ThenInclude(o => o.IdCard);
        .Include(o => o.Mails).ThenInclude(o => o.Names).ThenInclude(o => o.Language)
        .Include(o => o.Details).ThenInclude(o => o.Title).ThenInclude(o => o.Language)
        .Include(o => o.Details).ThenInclude(o => o.PhoneNumbers).ThenInclude(o => o.Names).ThenInclude(o => o.Language)
        .Include(o => o.Details).ThenInclude(o => o.Elements).ThenInclude(o => o.Element).ThenInclude(o => o.Names).ThenInclude(o => o.Language);
```

in the end employee has 0 reference in details.

A workaround was to split  the include:

```
var emp =  employee
       .Include(o => o.Details).ThenInclude(o => o.IdCard);

 return emp 
        .Include(o => o.Mails).ThenInclude(o => o.Names).ThenInclude(o => o.Language)
        .Include(o => o.Details).ThenInclude(o => o.Title).ThenInclude(o => o.Language)
        .Include(o => o.Details).ThenInclude(o => o.PhoneNumbers).ThenInclude(o => o.Names).ThenInclude(o => o.Language)
        .Include(o => o.Details).ThenInclude(o => o.Elements).ThenInclude(o => o.Element).ThenInclude(o => o.Names).ThenInclude(o => o.Language);
```

### Further technical details
EF Core version: (found in project.csproj or packages.config) : 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: win 10
IDE: Visual Studio 2017 15.4

**Comment by maumar** [comment] 2018-01-19 21:12
@neridonk can you provide full listing of your entities and contents of OnModelCreating method on your DbContext? We need to know how the relationships are defined in order to properly reproduce the issue.

**Comment by ajcvickers** [comment] 2018-02-07 21:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:06 UTC
Labels: closed-could-not-reproduce
