### ISSUE TITLE
Updating the nullable navigation property of a One-To-One relationship throws a DbUpdateConcurrencyException 

### ISSUE THREAD

**Issue by NexganGH** [dotnet/efcore#25042] opened 2021-06-06 16:54 UTC
### Include your code
```C#
public class UserChannel
{
    [Key]
    public ulong Id { get; set; }
    
    public WaitingRoom? WaitingRoom { get; set; }
}

public class WaitingRoom
{
    [Key, ForeignKey(nameof(LinkedChannel))]
    public ulong LinkedChannelId { get; set; }
    public UserChannel LinkedChannel { get; set; }

    public ulong VoiceChannelId { get; set; }
}

// This is where the exception is thrown upon saving. model is a valid UserChannel model.
// The exception is thrown only if WaitingRoom is set in the UserChannel.
using (var scope = factory.CreateScope())
{
    var ctx = scope.ServiceProvider.GetRequiredService<TempChannelContext>();

    ctx.UserChannels.Update(model);

    ctx.SaveChanges();
}
```

The exception is not being thrown if I update the context as follows:
```C#
var m = ctx.UserChannels.Find(model.Id);
m.WaitingRoom = model.WaitingRoom;
ctx.SaveChanges();
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagation(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__104_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at EmpyManager.Bot.Modules.TemporaryChannels.Services.TempChannelRepository.UpdateUserChannel(SocketUserChannel channel) in C:\Users\Torto\source\repos\EmpyManager\Bot\Modules\TemporaryChannels\EmpyManager.Bot.Modules.TemporaryChannels\Services\TempChannelRepository.cs:line 468
   at EmpyManager.Bot.Modules.TemporaryChannels.Services.ChannelService.UpdateChannel(SocketUserChannel uc) in C:\Users\Torto\source\repos\EmpyManager\Bot\Modules\TemporaryChannels\EmpyManager.Bot.Modules.TemporaryChannels\Services\ChannelService.cs:line 59
   at EmpyManager.Bot.Modules.TemporaryChannels.Services.ChannelService.EditActionsAsync(ISocketUserChannel ch, Func`2 func) in C:\Users\Torto\source\repos\EmpyManager\Bot\Modules\TemporaryChannels\EmpyManager.Bot.Modules.TemporaryChannels\Services\ChannelService.cs:line 57
   at EmpyManager.Bot.Modules.TemporaryChannels.TempChannelModule.PerformQuickCommandAsync(SocketMessageComponent interaction, String subAction, ISocketUserChannel userChannel) in C:\Users\Torto\source\repos\EmpyManager\Bot\Modules\TemporaryChannels\EmpyManager.Bot.Modules.TemporaryChannels\TempChannelModule.Interactions.cs:line 147
   at EmpyManager.Bot.Modules.TemporaryChannels.TempChannelModule.ButtonPressedAsync(SocketMessageComponent interaction) in C:\Users\Torto\source\repos\EmpyManager\Bot\Modules\TemporaryChannels\EmpyManager.Bot.Modules.TemporaryChannels\TempChannelModule.Interactions.cs:line 32
   at EmpyManager.Bot.Modules.GuildEventExtensions.InvokeAsync[T](GuildEvent`1 eventHandler, T arg) in C:\Users\Torto\source\repos\EmpyManager\Bot\Modules\EmpyManager.Bot.Modules\GuildEvents.cs:line 126
```

### Include verbose output

Please include `--verbose` output when filing bugs about the `dotnet ef` or Package Manager Console tools.

Use triple-tick fences for tool output. For example:

```
dotnet exec --depsfile C:\Users\Torto\source\repos\EmpyManager\EmpyManager.DAL\bin\Debug\net5.0\EmpyManager.DAL.deps.json --additionalprobingpath C:\Users\Torto\.nuget\packages --runtimeconfig C:\Users\Torto\source\repos\EmpyManager\EmpyManager.DAL\bin\Debug\net5.0\EmpyManager.DAL.runtimeconfig.json C:\Users\Torto\.dotnet\tools\.store\dotnet-ef\5.0.6\dotnet-ef\5.0.6\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll dbcontext list --assembly C:\Users\Torto\source\repos\EmpyManager\EmpyManager.DAL\bin\Debug\net5.0\EmpyManager.DAL.dll --startup-assembly C:\Users\Torto\source\repos\EmpyManager\EmpyManager.DAL\bin\Debug\net5.0\EmpyManager.DAL.dll --project-dir C:\Users\Torto\source\repos\EmpyManager\EmpyManager.DAL\ --language C# --working-dir C:\Users\Torto\source\repos\EmpyManager\EmpyManager.DAL --verbose --root-namespace EmpyManager.DAL
Using assembly 'EmpyManager.DAL'.
Using startup assembly 'EmpyManager.DAL'.
Using application base 'C:\Users\Torto\source\repos\EmpyManager\EmpyManager.DAL\bin\Debug\net5.0'.
Using working directory 'C:\Users\Torto\source\repos\EmpyManager\EmpyManager.DAL'.
Using root namespace 'EmpyManager.DAL'.
Using project directory 'C:\Users\Torto\source\repos\EmpyManager\EmpyManager.DAL\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'EmpyManager.DAL'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'TempChannelContext'.
```

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5-6
Operating system: Windows 10
IDE: 16.10.0 Preview 4.0

**Comment by ajcvickers** [comment] 2021-06-08 18:59
@NexganGH There isn't enough code here for us to be able to reproduce this. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate. Also, what version of EF Core are you using?

**Comment by AndriySvyryd** [comment] 2021-06-15 17:23
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:36 UTC
Labels: closed-could-not-reproduce, customer-reported
