### ISSUE TITLE
Concurrency Exception when saving changes in Insert operation in a table with INSTEAD OF INSERT Trigger

### ISSUE THREAD

**Issue by Jokencio** [dotnet/efcore#16067] opened 2019-06-13 12:42 UTC
I do an insert operation in a table with autonumeric primary key

![codigoSaveChanges](https://user-images.githubusercontent.com/46807208/59432496-bda24180-8de7-11e9-92f6-509f8314c0e3.PNG)
 
![tabla](https://user-images.githubusercontent.com/46807208/59432611-0823be00-8de8-11e9-86e5-d8ff5e0db949.PNG)

this table has an INSTEAD OF INSERT Trigger where I Insert elements in the same table.

It shows a concurrency exception at the time of saving changes

![excepcion](https://user-images.githubusercontent.com/46807208/59432710-45884b80-8de8-11e9-82dd-6d023dcab039.PNG)

![StackTrace](https://user-images.githubusercontent.com/46807208/59432723-4a4cff80-8de8-11e9-860b-1bdfc0fcbc1c.PNG)

I need that trigger, it's not possible for me to get rid of it. I don't know what's the best way to handle this and to force the adding of data.

Thanks in advance.

**Comment by ajcvickers** [comment] 2019-06-13 14:21
Duplicate of #12064

**Closed** 2022-10-16 14:25 UTC
Labels: customer-reported
