### ISSUE TITLE
Question: entities relationships between 2 assemblies (libraries)

### ISSUE THREAD

**Issue by prodenx** [dotnet/efcore#16163] opened 2019-06-19 15:27 UTC
Hi,

I have 2 libraries. Each library has own Entities, Migrations and Db Context. Both of them working with one DB. For example:

**Assembly 1**

        [Table["Foos"]]
        public class Foo
        {
                public int Id { get; set; }

                //columns
        } 

**Assembly 2**

        [Table["Bars"]]
        public class Bar
        {
                //columns
        }

Each assmbly has migration creating tables included into db contexts (personal for each assembly).
I want to add navigation property `ICollection<Bar> Bars` to Foo for **Assembly 2**. For that I referenced **Assembly 1** in **Assembly 2**, created inherited class `BFoo` with mentioned navigation property. Also I created foreign key `int FooId` on Bar:

**Assembly 2**

        public class BFoo: Foo
        {
                [ForeignKey("FooId")]
                public ICollection<Bar> Bars { get; set; }
        }

        [Table["Bars"]]
        public class Bar
        {
                public int FooId { get; set; }
                //columns
        }

Next, I included `DbSet<BFoo>` into `BarDbContext` and marked that `set` as `Ignored` to skip **Foos** table creation in migration of **Assembly 2**, becuase it will be created by migration from **Assembly 1**. When I create new migration on **Assembly 2** I do not get relationship between **Foos** and **Bars** created. Methods `Up()` and `Down()` are empty. Also I tryed other way with `modelBuilder`. I created navigation property `public Foo Foo { get; set; }` on `Bar`, removed `ForeignKey` attribute on BFoo.

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Ignore<BFoo>();

            modelBuilder.Entity<BFoo>().HasMany<Bar>(i => i.Bars)
                .WithOne(i => i.Foo);
        }

It helps, but **Foos** table created anyway (should not, becuase it is ignored)

Could someone help to reach my goal? Extending **Assembly1** entites with navigations properties in **Assembly2**.

PS: I use Asp Net Boileplate framework. I created 2 modules with own domain layers and db contexts.

**Comment by smitpatel** [comment] 2019-06-19 15:54
Duplicate of #2725

Current model building and migration are always in sync. So if you mark EntityType as ignored then it won't be in the model and migrations both. If you don't mark it as ignored (to get FK constraint) then it will be in migration as table too. #2725 will allow you to include entity in the model to create the constraints but exclude creating table from migration.

**Closed** 2022-10-16 14:26 UTC
Labels: closed-duplicate, customer-reported
