### ISSUE TITLE
Sqlite: ValueConverters are not taken into account with DateTime.Now

### ISSUE THREAD

**Issue by kunom** [dotnet/efcore#16639] opened 2019-07-17 14:47 UTC
The following setup (minimized):

```C#
    public class Record
    {
        public int Id { get; set; }
        public DateTime Dt { get; set; } = DateTime.Now;
        public DateTime Dt2 { get; set; } = DateTime.Now;
        public DateTime Dt3 { get; set; } = DateTime.Now;
    }

    public class TestDbContext : DbContext
    {
        public DbSet<Record> Records { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Record>().Property(e => e.Dt2).HasConversion(new DateToStringConverter()); // custom implementaiton that produces YYYY-MM-DD
            modelBuilder.Entity<Record>().Property(e => e.Dt3).HasConversion(new DateTimeToTicksConverter());
        }
    }
```

Filtering by a specific timestamp produces good queries and good log warnings if value converters are used:
```C#
                var somewhen = DateTime.Now.AddHours(-1);
                db.Records.Where(r => r.Dt < somewhen).ToList();
                db.Records.Where(r => r.Dt2 < somewhen).ToList();
                db.Records.Where(r => r.Dt3 < somewhen).ToList();
```
```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[@__somewhen_0='?'], CommandType='Text', CommandTimeout='30']
      SELECT "r"."Id", "r"."Dt", "r"."Dt2", "r"."Dt3", "r"."Dto"
      FROM "Records" AS "r"
      WHERE "r"."Dt" < @__somewhen_0
warn: Microsoft.EntityFrameworkCore.Query[20503]
      A SQL parameter or literal was generated for the type 'DateTime' using the ValueConverter 'DateToStringConverter'. Review the generated SQL for correctness and consider evaluating the target expression in-memory instead.
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[@__somewhen_0='?' (Size = 10)], CommandType='Text', CommandTimeout='30']
      SELECT "r"."Id", "r"."Dt", "r"."Dt2", "r"."Dt3", "r"."Dto"
      FROM "Records" AS "r"
      WHERE "r"."Dt2" < @__somewhen_0
warn: Microsoft.EntityFrameworkCore.Query[20503]
      A SQL parameter or literal was generated for the type 'DateTime' using the ValueConverter 'DateTimeToTicksConverter'. Review the generated SQL for correctness and consider evaluating the target expression in-memory instead.
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[@__somewhen_0='?'], CommandType='Text', CommandTimeout='30']
      SELECT "r"."Id", "r"."Dt", "r"."Dt2", "r"."Dt3", "r"."Dto"
      FROM "Records" AS "r"
      WHERE "r"."Dt3" < @__somewhen_0
```

But when using `DateTime.Now' as argument, the queries degenerate:
* `strftime` magic even if value converters are used
* no log warnings when value converters are used

```C#
                db.Records.Where(r => r.Dt < DateTime.Now).ToList();
                db.Records.Where(r => r.Dt2 < DateTime.Now).ToList();
                db.Records.Where(r => r.Dt3 < DateTime.Now).ToList();
```
```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "r"."Id", "r"."Dt", "r"."Dt2", "r"."Dt3", "r"."Dto"
      FROM "Records" AS "r"
      WHERE "r"."Dt" < rtrim(rtrim(strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime'), '0'), '.')
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "r"."Id", "r"."Dt", "r"."Dt2", "r"."Dt3", "r"."Dto"
      FROM "Records" AS "r"
      WHERE "r"."Dt2" < rtrim(rtrim(strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime'), '0'), '.')
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "r"."Id", "r"."Dt", "r"."Dt2", "r"."Dt3", "r"."Dto"
      FROM "Records" AS "r"
      WHERE "r"."Dt3" < rtrim(rtrim(strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime'), '0'), '.')      
```

### Further technical details
EF Core version: 2.2.6

**Comment by ajcvickers** [comment] 2019-07-17 15:13
Duplicate of #10434

**Closed** 2022-10-16 14:31 UTC
Labels: customer-reported
