### ISSUE TITLE
value cannot be null afer upgrade from 2.1.4 to 2.2

### ISSUE THREAD

**Issue by guiohm** [dotnet/efcore#14613] opened 2019-02-05 10:50 UTC
After upgrading from 2.1.4 to 2.2. I have multiple issues. One of them is:
Scenario:
A bunch of entities are loaded / modified, some created and whensaving I got now:
```
 "InnerException": {
      "Type": "System.ArgumentNullException",
      "Message": "Value cannot be null. Parameter name: key",
      "Source": "mscorlib",
      "ParamName": "key"
    }
```

I have no property "key" in my model. The model and code is now quite complex, (it's a production app) and I can't even figure out what I can do to debug this. Any idea?

As a side note, I have other errors appearing here and there about navigation objects not loaded anymore even though I do call `include(x => x.Relation)`. I'll probabley create another issue about that.
And also other errors where I have no log other that one line appearing a few hundred times at once in VisualStudio Debug Output:
 `System.Exception occured in App.exe`

Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Windows 10 / Server 2012 R2

**Comment by ajcvickers** [comment] 2019-02-05 17:01
@guiohm Looks like you could be hitting #14226. However, it is hard to be sure without a complete stack trace and/or code to reproduce what you are seeing.

**Comment by ajcvickers** [comment] 2019-02-15 17:41
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:50 UTC
Labels: closed-could-not-reproduce, customer-reported
