### ISSUE TITLE
Inline tsql function in where clause

### ISSUE THREAD

**Issue by vlapenkov** [dotnet/efcore#16599] opened 2019-07-15 06:05 UTC
Can i use somehow tsql inline function in where clause?  Like `dbContext.Foos.where(p=>myPedicateFunc(paramA))`
I need some tricks in this function

**Comment by smitpatel** [comment] 2019-07-15 14:56
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by bricelam** [comment] 2019-07-16 22:16
See [Database scalar function mapping](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0#database-scalar-function-mapping)

**Comment by ajcvickers** [comment] 2019-07-22 19:05
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:30 UTC
Labels: closed-could-not-reproduce, customer-reported
