### ISSUE TITLE
I cannot access to a SQLite database created with system.Data.SQLite with password

### ISSUE THREAD

**Issue by DevReportOne** [dotnet/efcore#25019] opened 2021-06-02 09:12 UTC
I cannot access to a SQLite database created with system.Data.SQLite with password.

Not working small project with the error using Microsoft.EntityFrameworkCore.Sqlite 5.0.6 Package:

[DBRead_MSSQLite.zip](https://github.com/dotnet/efcore/files/6583137/DBRead_MSSQLite.zip)

ERROR: 
```
Microsoft.Data.Sqlite.SqliteException
  HResult=0x80004005
  Message=SQLite Error 26: 'file is not a database'.
  Source=Microsoft.Data.Sqlite
  Arborescence des appels de procédure :
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.<PrepareAndEnumerateStatements>d__64.MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.<GetStatements>d__54.MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at DBRead_MSSQLite.Program.Main(String[] args) in C:\Sources\AnnexePink\trunk\MS\DBRead_MSSQLite\Program.cs:line 44
```

Connection code using system.Data.SQLite 1.0.112.0 for database creation:

```C#

           var sb = new SQLiteConnectionStringBuilder()
            {
                DataSource = "MySqliteDB.db"
            };

            var connexion = new SQLiteConnection(sb.ConnectionString);
            connexion.Open();

            // Sanitize the user input using the quote() function
            var quoteCommand = connexion.CreateCommand();
            quoteCommand.CommandText = "SELECT quote($value)";
            quoteCommand.Parameters.AddWithValue("$value", @"MyDBPassword");
            var quotedPassword = (string)quoteCommand.ExecuteScalar();

            // PRAGMA statements can't be paramaterized. We're forced to concatenate the
            // escaped user input
            var keyCommand = connexion.CreateCommand();
            keyCommand.Parameters.Clear();
            keyCommand.CommandText =
                $@"
                    PRAGMA key = {quotedPassword}
                ";
            keyCommand.ExecuteScalar();
            //On gere les foreign keys 
            keyCommand.Parameters.Clear();
            keyCommand.CommandText =
                $@"
                    PRAGMA foreign_keys=ON;
                ";
            keyCommand.ExecuteScalar();
```

**Comment by AndriySvyryd** [comment] 2021-06-04 17:14
cc: @bricelam

**Comment by bricelam** [comment] 2021-06-04 19:57
Duplicate of https://github.com/dotnet/efcore/issues/23999#issuecomment-770029224

**Closed** 2022-10-16 19:36 UTC
Labels: closed-duplicate, customer-reported, area-adonet-sqlite
