### ISSUE TITLE
Support for ValueGeneration OnUpdate

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#12611] opened 2018-07-09 20:40 UTC
```C#
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var blog = new Blog { Value = "A" };
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database
                var entry = db.Add(blog);
                Console.WriteLine(entry.CurrentValues["Discriminator"]);

                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                blog.Value = "B";
                var entry = db.Update(blog);
                Console.WriteLine(entry.CurrentValues["Discriminator"]);
                db.SaveChanges();
            }

            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        private static ILoggerFactory LoggerFactory => new LoggerFactory().AddConsole(LogLevel.Trace);

        // Declare DBSets
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<SpecialBlog> SpecialBlogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                //.UseSqlite("filename=_modelApp.db")
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(LoggerFactory);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
        }
    }

    public class Blog
    {
        public int Id { get; set; }
        public string Value { get; set; }
    }

    public class SpecialBlog : Blog
    {
    }
}
```
The "Discriminator" property on entity entry is set to correct value when doing `Add` but when doing `Update` the value is null. For relational it works since update does not change values in database due to partial update. Though the value is required for CosmosDb provider since there are not partial updates.

**Comment by divega** [comment] 2018-07-11 19:48
This seems important for Cosmos DB, stored procedures and general client generated values for update could potentially could help with optimistic "offline lock".

**Comment by divega** [comment] 2018-07-11 19:49
For the time being we have a workaround this for Cosmos DB.

**Comment by AndriySvyryd** [comment] 2018-12-07 23:45
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/6999

**Closed** 2022-10-21 10:32 UTC
Labels: closed-duplicate
