### ISSUE TITLE
JSON (or XML) Columns

### ISSUE THREAD

**Issue by TehWardy** [dotnet/efcore#19049] opened 2019-11-25 09:52 UTC
Before I begin ...
  I realise having thought about this at length that this may be an XY problem ...
      https://en.wikipedia.org/wiki/XY_problem
... so if the underlying problem can be solved of "querying dynamic child data on an entity" in EF without this mechanism i'm open to alternative approaches.

I'm hoping to make JSON / XML columns work with OData.
Is there any way this can be made possible (either by myself or by you guys).

I realise that this is a pretty complex edge case for you guys and there's a ton of core functionality that will ultimately come before this in your own backlog but if the response to this is "you can download the source and implement your solution to this <here: some ref in the framework code>" then so be it, i'm happy to have a crack at it and then submit my findings as a pull request as need be.

My scenario is essentially as listed here ... 
   https://github.com/OData/WebApi/issues/1966

From what I can tell the only other ticket i've seen like this is this one ...
   https://github.com/aspnet/EntityFrameworkCore/issues/6284

My situation in a nutshell is something like this ...

I have a core set of Entity types that need the ability to define complex "child data items" that will depend on the items usage and that usage on the client will understand how to build the correct query on the data.

The idea is that our system provides a platform for other companies to build their own business processes and the net result is that they often need fields that don't exist in a type safe fashion that they can apply business rules to.

If i can make the data queryable i'm absolutely certain I have the business logic requirements solved for the layer on top of the context.

Example of my goals ....

```
public class GenericEntity
{
    [Key]
     public Guid Id { get; set; }  // required primary key

     public string Name { get; set; }  // friend ident for the instance

     public string Type { get; set; }  // defined by the caller to determine the use case

     // unknown (by back end) structured data consumed by front end process
     public dynamic Data { get; set; } 
}
```

Ideally i need to be able to build linq queries form OData on the property "Data" in the above type like ...

`~/GenericEntity?$filter=Data/SomeProp eq someval`

EF is responsible for building the SQL query on the expression tree provided by the OData framework so I figure this is the place to solve the issue.

**Comment by smitpatel** [comment] 2019-11-25 21:37
Duplicate of #4021

Currently in EF Core, you can map any object to json column in database by providing your custom value converter. But as you suspect, then you would be losing functionality to query properly. If you look at the #4021 then it also details an UDF in order to query using JSON path.

#4021 works in the direction of making it easier to deal with by providing first class support from EF Core. That is what work is being tracked on EF Core side.

Now, what kind of query ODATA will generate and EF Core supporting it a different issue. We plan to support normal user scenarios and probably some basic patterns in ODATA but ODATA may also need to react to create proper expression tree for translation in EF Core.

**Closed** 2022-10-16 14:58 UTC
Labels: customer-reported
