### ISSUE TITLE
could not be translated and will be evaluated locally.

### ISSUE THREAD

**Issue by parxal** [dotnet/efcore#12230] opened 2018-06-04 17:18 UTC
Sql Where is not being generate when using properties of my base class.
The follow example is a basic version of the problem. 

```
Exception message:
Stack trace:
Microsoft.EntityFrameworkCore.Query:Warning: The LINQ expression 'where (new PackageViewModel() {CreatedByUserName = [p.CreatedBy].UserName, Id = [p].Id}.CreatedByUserName == "Ivan")' could not be translated and will be evaluated locally.
```

```c#
public class BaseViewModel
{
   public String CreatedByUserName { get; set; }
}

public class PackageViewModel : BaseViewModel
{
   public Guid Id { get; set; }
}

public class myTest
{
        public void Test()
        {
           var query = _dbContext.Set<Package>().Select(p => new PackageViewModel()
            {
                CreatedByUserName = p.CreatedBy.UserName,
                Id = p.Id
            });

            var param = Expression.Parameter(typeof(PackageViewModel), "p");
            var exp = Expression.Lambda<Func<PackageViewModel, bool>>(
                Expression.Equal(
                    Expression.Property(param, "CreatedByUserName"),
                    Expression.Constant("Ivan", typeof(String))
                ), param
            );

            var result = query.Where(exp).ToList();
       }
}

```

If i try with: 
var param = Expression.Parameter(typeof(BaseViewModel), "p"); 
It works, but then it doens't work with other properties like "Id", because they doesn't exist in the base class.

The problem is that in my final version I have some dynamic “where’s” over properties that are in my main class and others that are in my base class which will result in something like this : ( p => p.Id==”…” && p.CreatedByUserName==”…”)

Questions: 
Is this a bug? 
Why properties that are on my base class only evaluate locally? 
Is there a workaround?
Is the solution to copy all properties from my base class to all my main classes? 

### Further technical details
EF Core version: 2.0.3
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL 2.0.1
Operating system: 
IDE: Visual Studio 2017 15.7.2

**Comment by bricelam** [comment] 2018-06-04 17:36
Duplicate of #10807? Does it work in version 2.1.0?

**Comment by parxal** [comment] 2018-06-05 11:06
@bricelam not working on 2.1.0, probably different problem

**Comment by maumar** [comment] 2018-06-05 23:41
When the parameter is typed as a base (`Expression.Parameter(typeof(BaseViewModel), "p")`) relinq is smart enough to optimize the query into the following form:

```cs
from Package p in DbSet<Package>
where [p].CreatedBy.UserName == "Ivan"
select new PackageViewModel{ 
    CreatedByUserName = [p].CreatedBy.UserName, 
    Id = [p].Id 
}
```

which then EF can translate fully to the server. However when the parameter is typed as `PackageViewModel`, relinq gives us the following query model:

```cs
from Package p in DbSet<Package>
where new PackageViewModel{ 
    CreatedByUserName = [p].CreatedBy.UserName, 
    Id = [p].Id 
}
.CreatedByUserName == "Ivan"
select new PackageViewModel{ 
    CreatedByUserName = [p].CreatedBy.UserName, 
    Id = [p].Id 
}
```

which is the reason for client eval in where (we can't translate construction of dto in a predicate).

Additionally, if your dynamic predicate uses property that is defined on the derived type directly, then it translates nicely also.

```cs
                var param = Expression.Parameter(typeof(PackageViewModel), "p");

                var exp = Expression.Lambda<Func<PackageViewModel, bool>>(
                    Expression.Equal(
                        Expression.Property(param, "Id"),
                        Expression.Constant(Guid.NewGuid(), typeof(Guid))
                    ), param
                );
```

produces:

```
from Package p in DbSet<Package>
where [p].Id == 6db575e4-c366-4177-88f8-a8afd1d341c4
select new PackageViewModel{ 
    CreatedByUserName = [p].CreatedBy.UserName, 
    Id = [p].Id 
}
```

**Comment by maumar** [comment] 2018-06-05 23:53
Filed https://www.re-motion.org/jira/browse/RMLNQ-121 to track this.

**Comment by MichaelKetting** [comment] 2018-06-20 12:14
@parxal I've explained the details in https://www.re-motion.org/jira/browse/RMLNQ-121 but the TL:DR answer to solve your problem right now is the following:

You need to use the type where the property was originally declared, just like the C# compiler does it, e.g. "BaseViewModel" for "CreatedByUserName"

**Comment by earllocker** [comment] 2019-03-26 21:21
@parxal Did you ever get this resolved with your particular situation - where you are attempting to dynamically build a where statement that includes properties from BOTH your base class and your derived class? I know there's a workaround when accessing one of the other, but I don't see a workaround when including both.

**Comment by progmars** [comment] 2019-08-07 09:18
I have a very similar issue caused by generic method as an expression source and then trying to apply it on a projected (Select()) queryable:



```

public interface ISomeable
{
    string Some { get; set; }
}

public static Expression<Func<T, bool>> GetCriteria<T>() where T : class, ISomeable
{  return e => (e.Some == "Hello"); }

...


Expression<Func<MySimpleEntity, bool>> someCriteria = e => (e.Some == "Hello");
Expression<Func<MySimpleEntity, bool>> someCriteria2 = GetCriteria<MySimpleEntity>();

var query = db.Entities
       .Select(s => new MySimpleEntity { Id = s.Id, Some = s.Some });
// if this Select is removed and MySimpleEntity in both expressions replaced with MyFullEntity, 
// the issue disappears

// this succeeds
// var filteredQueryResults = query.Where(someCriteria).ToList();

// this fails: why is it evaluated locally and not in SQL? <-------------------------------
var filteredQueryResults = filteredQueryResults = query.Where(someCriteria2).ToList();
// someCriteria2 is set to the same e => (e.Some == "Hello");
// debugger shows that both someCriteria and someCriteria2 are essentially the same,
// however, Linq somehow knows about generic roots of someCriteria2 and treats it differently

/*
 * 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: 
 * The LINQ expression 'where (new MySimpleEntity() {Id = [s].Id, Some = [s].Some}.Some == "Hello")' 
 * could not be translated and will be evaluated locally.'. 
 */
```

Here's my Gist of a minimal application:

https://gist.github.com/progmars/eeec32a533dbd2e1f85e551db1bc53f8

Is there any workaround (casting, traversing the expression to replace types etc. etc.) to make it work for `someCriteria2`?

**Comment by progmars** [comment] 2019-08-07 11:34
Found a somewhat dirty solution in some other issue:
https://github.com/aspnet/EntityFrameworkCore/issues/14118#issuecomment-519057279

**Closed** 2022-10-16 12:28 UTC
Labels: closed-external, customer-reported
