### ISSUE TITLE
InvalidOperationException: The instance of entity type 'Entity1' cannot be tracked because another instance of this type with the same key is already being tracked.

### ISSUE THREAD

**Issue by dpjain** [dotnet/efcore#6485] opened 2016-09-07 15:40 UTC
```
  [HttpPost]
        public IActionResult Action1(Entity1 entity1)
        {
            Entity1 objEntity1 = _context.Entity1.AsNoTracking().Single(s => s.Id == entity1.Id);
            if (ModelState.IsValid)
            {
               entity1.Property1 = objEntity1.Property1;
                _context.Update(entity1);
                _context.SaveChanges();
             }
return View();
        }
```
### The issue

Got the following issue while updating the context for Entity1. (It was working properly with asp.net core RC1, but failed for .net core 1.0.)

InvalidOperationException: The instance of entity type 'BookingVenueSite' cannot be tracked because another instance of this type with the same key is already being tracked. When adding new entities, for most key types a unique temporary key value will be created if no key is set (i.e. if the key property is assigned the default value for its type). If you are explicitly setting key values for new entities, ensure they do not collide with existing entities or temporary values generated for other new entities. When attaching existing entities, ensure that only one entity instance with a given key value is attached to the context.
### Further technical details

EF Core version: EntityFrameworkCore
Visual Studio version: VS 2015

**Comment by divega** [comment] 2016-09-07 19:03
@dpjain Is the controller action being executed by MVC directly or is it invoked from a different action? Is the `DbContext` scoped to the request? The exception is certainly unexpected if the `DbContext` is clean (i.e. does not contain any other entity instances) by the time you call `Update()`.

**Comment by dpjain** [comment] 2016-09-08 07:33
@divega : Yes the controller action being executed by MVC directly

**Comment by ajcvickers** [comment] 2016-09-08 18:54
@dpjain This exception is usually an indication that the same context instance is being re-used for multiple units of work. This is generally not a good idea and we would usually recommend a single context instance per unit of work.

It seems you are also making things more difficult by using no tracking queries and then attempting to attach the entities to the context. Consider re-writing the method to something like this:
```C#
var objEntity1 = _context.Entity1.Single(s => s.Id == entity1.Id);
if (ModelState.IsValid)
{
    entity1.Property1 = objEntity1.Property1;
    _context.SaveChanges();
}
return View();
```
This has several advantages over the code as it was before:
* It is usually faster to do a tracking query rather than a no-tracking query and an Attach/Update call
* EF will detect if Property1 has really changed and will only send an update if it is different from the value queried from the database.
* EF will not attempt to update any other properties since they have not changed.
* If multiple parts of the same unit of work need to get the same entity from the database, then identity resolution in the context will ensure that the same instance is used in all places.

The last point may be why you are getting the exception. If multiple methods in the same unit of work are requesting the entity with the same ID, and they all attempt to attach it to the context, then only the first will succeed.

**Comment by dpjain** [comment] 2016-09-09 13:52
@ajcvickers : I have tried using the below code
var objEntity1 = _context.Entity1.Single(s => s.Id == entity1.Id);
if (ModelState.IsValid)
{
    entity1.Property1 = objEntity1.Property1;
    _context.SaveChanges();
}
return View();
but still I am getting the same issue.

**Comment by ajcvickers** [comment] 2016-09-09 17:41
@dpjain Please post the stack trace.

**Comment by dpjain** [comment] 2016-09-13 08:54
InvalidOperationException: The instance of entity type 'BookingVenueSite' cannot be tracked because another instance of this type with the same key is already being tracked. When adding new entities, for most key types a unique temporary key value will be created if no key is set (i.e. if the key property is assigned the default value for its type). If you are explicitly setting key values for new entities, ensure they do not collide with existing entities or temporary values generated for other new entities. When attaching existing entities, ensure that only one entity instance with a given key value is attached to the context.
Add
Add
StartTracking
SetEntityState
SetEntityState
PaintAction
TraverseGraph
TraverseGraph
TraverseGraph
AttachGraph
SetEntityState
SetEntityState
Update
MoveNext
Throw
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
ValidateEnd
GetResult
MoveNext
Throw
MoveNext
Throw
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
ValidateEnd
GetResult
MoveNext
Throw
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
ValidateEnd
GetResult
MoveNext
Throw
MoveNext
Throw
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
ValidateEnd
GetResult
MoveNext
Throw
MoveNext
Throw
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
ValidateEnd
GetResult
MoveNext
Throw
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
ValidateEnd
GetResult
MoveNext
Throw
MoveNext
Throw
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
ValidateEnd
GetResult
MoveNext

Show raw exception details
System.InvalidOperationException: The instance of entity type 'BookingVenueSite' cannot be tracked because another instance of this type with the same key is already being tracked. When adding new entities, for most key types a unique temporary key value will be created if no key is set (i.e. if the key property is assigned the default value for its type). If you are explicitly setting key values for new entities, ensure they do not collide with existing entities or temporary values generated for other new entities. When attaching existing entities, ensure that only one entity instance with a given key value is attached to the context.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Update[TEntity](TEntity entity)
   at SnPBokking.Controllers.BookingsController.<SiteEdit>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()

**Comment by ajcvickers** [comment] 2016-09-13 16:00
@dpjain This stack trace shows a call to Update inside BookingsController. The code I posted does not have any call to Update. Can you show the stack trace you get when running the code I posted? Or, if the exception is coming from somewhere else, can you then show the code that is causing the exception?

**Comment by ajcvickers** [comment] 2016-09-20 23:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Comment by iberodev** [comment] 2016-10-27 00:26
I have had a similar error. View this ticket where there is a link to a sample project all ready to reproduce the issue.
https://github.com/aspnet/EntityFramework/issues/6873

**Comment by meteor-learning** [comment] 2017-05-12 04:23
The link @iberodev provided is a huge help.  I was missing a hasIndex in my model builder, so when I was creating new many to many items, Entity Framework kept getting temporary duplicate keys.  By adding the hasIndex in my model builder, like so:

`				modelBuilder.Entity<KhanAcademyAssignmentStudent>()
		            .HasIndex(x => new {x.StudentId, x.KhanAcademyAssignmentId}).IsUnique(true);`

Everything works and Entity Framework can add many to many entries with on problem.  Thank you!

**Closed** 2022-10-16 09:56 UTC
Labels: closed-could-not-reproduce
