### ISSUE TITLE
ORDER BY Clause contains AS 

### ISSUE THREAD

**Issue by omr-htp** [dotnet/efcore#13114] opened 2018-08-24 20:49 UTC
Hello,

i have an enum "MyStatusEnum" with type of byte

and i'm using this class 
```c#
    public class myFilter1
    {
        public byte Id { get; set; }

        public string Name { get; set; }

        public int Count { get; set; }
    }
```
to store the results of this query 
```c#
var res = _context.Set<MyModel>()
.GroupBy(x => x.Status)
.Select(g => new myFilter1
    {
    Id = (byte)g.Key,
    Name = System.Enum.GetName(typeof(MyStatusEnum), g.Key),
    Count = g.Count()
    })
.OrderBy(s => s.Id)
.ToList();
```
the produced sql statement is 
```SQL
SELECT [x].[Status] AS [Id], [x].[Status] AS [Key], COUNT(*) AS [Count]
FROM [dbo].[MyModel] AS [x]
WHERE ([x].[IsDeleted] = 0)
GROUP BY [x].[Status]
ORDER BY [x].[Status] AS [Id]
````
Note "AS" in order by ...

the second big problem appears when i change the type of id property from byte to int without changing conversion "(byte)g.Key"

the sql statement become

```SQL
SELECT CAST([x].[Status] AS [Key] AS int) AS [Id], [x].[Status] AS [Key], COUNT(*) AS [Count]
FROM [dbo].[MyModel] AS [x]
WHERE ([x].[IsDeleted] = 0)
GROUP BY [x].[Status]
ORDER BY [x].[Status] AS [Key]
```
Note "CAST as key before  as int"

i'm using latest sdk v2.1.401 with Microsoft.AspNetCore.App v2.1.3
Thanks.

**Comment by smitpatel** [comment] 2018-08-27 20:51
Duplicate of #12826

**Closed** 2022-10-16 13:27 UTC
Labels: customer-reported
