### ISSUE TITLE
Feature: Supported keyed registrations in AddDbContext for Cosmos

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/efcore#34522] opened 2024-08-24 00:28 UTC
When my application starts up, I'd like to have it ensure that the target Cosmos database and the containers specified in the DbContext are created via `myContext.Database.EnsureCreatedAsync()`. Unfortunately, it has come to my attention today that while Cosmos DB supports managed identities via Entra for data-related operations, it [does _not_ allow non-data operations](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-forbidden#non-data-operations-are-not-allowed) (like the one I'm trying) with managed identities.

This introduces a problem - I need the DbContext registered so the container schema is known so `EnsureCreatedAsync` actually does something, but I also want to use the managed identity to perform data-related operations. 

So this means I need to register the `AddDbContext` twice - one with the managed identity and one with the primary key in the connection string, which seems absurd. Unfortunately, there's no support for keyed registrations for identical DbContexts, so I've had to resort to using a third-party library (Scrutor) to accomplish the same.

This is a feature request form for the EF Core SDK itself and not Cosmos, so while the need for this could be obviated by Cosmos allowing any operation to be done by a managed identity that it allows with a connection string (especially when that principal is assigned the [special built-in roles](https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#built-in-role-definitions)) 'm requesting that the `AddDbContext` method be updated to support keyed service that lets me register the same `DbContext` with different authentication approaches for different use cases. 

Thank you for the consideration!

**Comment by roji** [comment] 2024-08-24 06:35
Duplicate of #32272

**Comment by roji** [comment] 2024-08-24 06:40
Registering contexts as keyed DI services is tracked by #32272.

Just a thought on your specific scenario... Assuming the EnsureCreatedAsync needs to happen in only one place in your application, I wouldn't necessarily want the non-managed-identity context registered in DI... In other words, I'd consider only registering your regular DbContext - the one with managed identity, that presumably is used everywhere for regular data operations - and handling the creation in a special way, without a registered DI service for that context.

**Closed by roji** 2024-08-24 06:40 UTC
Labels: customer-reported
