### ISSUE TITLE
MapToStoredProcedures support

### ISSUE THREAD

**Issue by abadakhshan** [dotnet/efcore#20768] opened 2020-04-28 08:10 UTC
Is there any plan to support MapToStoredProcedures like [EF 6](https://www.entityframeworktutorial.net/entityframework6/code-first-insert-update-delete-stored-procedure-mapping.aspx)?

**Comment by ajcvickers** [comment] 2020-05-01 16:23
Duplicate of #245

**Closed** 2022-10-16 18:22 UTC
Labels: closed-duplicate, customer-reported
