### ISSUE TITLE
Remove a entity by Primary Keys

### ISSUE THREAD

**Issue by mojtabakaviani** [dotnet/efcore#10893] opened 2018-02-06 20:23 UTC
When need remove a entity from database first we must find it later remove it. why can not remove a entity when have primary keys and required for entities. please add remove overloading that can remove a entity by primary keys.

**Comment by ajcvickers** [comment] 2018-02-06 20:44
Duplicate of #795

**Comment by mojtabakaviani** [comment] 2018-02-06 22:31
Duplicate means many developers need it.

**Comment by Davilink** [comment] 2018-05-24 02:44
Technically you can just create and empty entity with the primary key field setted, attach it to the context and finally removing it.

```
var entity = new Entity
{
  Id = "my-id"
};
context.MyDbSet.Attach(entity);

context.MyDbSet.Remove(entity);
context.SaveChanges();
```

**Closed** 2022-10-16 12:08 UTC
Labels: closed-duplicate
