### ISSUE TITLE
Subquery is not translated

### ISSUE THREAD

**Issue by fschick** [dotnet/efcore#27082] opened 2021-12-31 08:50 UTC
## Subquery is not translated
When explicit subquery should be used, it's translated to wrong MIN aggregate

The following query:
```csharp
Expression<Func<Order, bool>> someFilterFromOutside = x => x.Number != "A1";

var orders = await dbContext
    .Set<Order>()
    .Where(someFilterFromOutside)
    .GroupBy(x => new { x.CustomerId, x.Number })
    .Select(x => new
    {
        x.Key.CustomerId,
        // ==> SUBQUERY VIA 'dbContext'
        CustomerMinHourlyRate = dbContext.Set<Order>().Where(n => n.CustomerId == x.Key.CustomerId).Min(h => h.HourlyRate),
        HourlyRate = x.Min(f => f.HourlyRate),
        Count = x.Count()
    })
    .ToListAsync();
```
Is translated to:
```sql
SELECT "o"."CustomerId",
	MIN("o"."HourlyRate") AS "CustomerMinHourlyRate", -- <== THIS IS WRONG
	COUNT(*) AS "Count"
FROM "Order" AS "o"
WHERE ("o"."Number" <> 'A1') OR "o"."Number" IS NULL
GROUP BY "o"."CustomerId",
	"o"."Number"
```
The generated `MIN` selects the minimum of filtered and fully grouped (`CustomerId` and `Number`) orders instead of (sub) querying `Order`filtered by `CustomerId` only.

See [WhenSubSelectIsUsed_MinHourlyRatePerCustomerIsSelectedProperly](https://github.com/fschick/EF.GeneratedSelectBug/blob/260a8a0c31bdd265343d72a587eef346b6649077/EF.GeneratedSelectBug.Tests/SqlTranslationTests.cs#L61) to reproduce

### Code to reproduce
```bash
git clone https://github.com/fschick/EF.GeneratedSelectBug.git
cd EF.GeneratedSelectBug
dotnet test
```
### Provider and version information
EF Core version: 6.0.1
Database provider: at least Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6.0
Operating system: All
IDE: All

**Comment by smitpatel** [comment] 2022-01-05 05:53
Duplicate of #27102 

Generated SQL after fix
```SQL
SELECT [o].[CustomerId], (
    SELECT MIN([o0].[HourlyRate])
    FROM [Order] AS [o0]
    WHERE [o0].[CustomerId] = [o].[CustomerId]) AS [CustomerMinHourlyRate], MIN([o].[HourlyRate]) AS [HourlyRate], COUNT(*) AS [Count]
FROM [Order] AS [o]
WHERE ([o].[Number] <> N'A1') OR [o].[Number] IS NULL
GROUP BY [o].[CustomerId], [o].[Number]
```

**Comment by smitpatel** [comment] 2022-01-05 05:53
Added test in #27109

**Closed** 2022-10-16 20:20 UTC
Labels: closed-duplicate, customer-reported
