### ISSUE TITLE
Scaffolding generates wrong namespace

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#12176] opened 2018-05-30 23:14 UTC
Looks like [same issue reported here](https://github.com/aspnet/EntityFrameworkCore/issues/9787).

Expected:
namespace NPBOverrides.RiskDB.Model

Actual:
namespace NPBOverrides.RiskDB_Model

**Comment by smitpatel** [comment] 2018-05-30 23:15
What is the command being run?

**Comment by sam-wheat** [comment] 2018-05-30 23:18
C:\Git\NPBOverrides\NPBOverrides>dotnet ef dbcontext scaffold -o ..\NPBOverrides
.RiskDB.Model "server=zzz" Microsoft.EntityFrameworkCore.SqlServer

Versions:
2.0.3
and also
2.1

**Comment by smitpatel** [comment] 2018-05-30 23:38
https://github.com/aspnet/EntityFrameworkCore/issues/9787 is fixed in 2.1 release. Are you sure you are using 2.1 version of EF Core? It should not have above issue.

The command you shared is scaffolding model outside of current project directory (notice `../` at the start). We cannot compute correct namespace in such case (see #9723). We would be using default namespace in that case.

I am unable to reproduce this issue in 2.1 packages using the details you shared.

**Comment by sam-wheat** [comment] 2018-05-30 23:54
My error sorry.  I upgraded EntityFrameworkCore packages to 2.1.0 however this did not upgrade package Microsoft.EntityFrameworkCore.Tools.DotNet so above comments are actually related to 2.0.3 only.

After upgrading to 2.1.0-preview1-final I get this:

Expected:
namespace NPBOverrides.RiskDB.Model

Actual:
namespace NPBOverrides

Same command being run as previous.

  <Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <OutputType>Exe</OutputType>
      <TargetFramework>netcoreapp2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Inflector.NetStandard" Version="1.2.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0" />
    </ItemGroup>

    <ItemGroup>
      <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.1.0-preview1-final" />
    </ItemGroup>
  </Project>

**Comment by smitpatel** [comment] 2018-05-30 23:55
`Microsoft.EntityFrameworkCore.Tools.DotNet` is part of dotnet SDK now. You should remove reference to it from your csproj and install 2.1 .NET Core SDK to get dotnet ef commands.

**Comment by smitpatel** [comment] 2018-05-30 23:55
Duplicate of #9723

**Comment by smitpatel** [comment] 2018-05-30 23:56
Marking as duplicate since in 2.1 version, we would be using default namespace if the output dir is outside of current project dir.

**Closed** 2022-10-16 12:27 UTC
Labels: customer-reported
