### ISSUE TITLE
"The specified deps.json ... does not exist" Error on Visual Studio 2019 Migration

### ISSUE THREAD

**Issue by corix010** [dotnet/efcore#17575] opened 2019-07-17 19:24 UTC
I am having issue with Add-Migration InitialCreate command in Package Manager Console. I'm getting the error "The specified deps.json [C:\App Dev Sample\DotNet\Sample5\SampleCoreMVC\SampleCoreMVC.deps.json] does not exist". The solution builds successfully.

The project is a ASP.NET Core 2.1 Web Application (MVC) using Visual Studio Professional 2019 Version 16.1.6 on Windows 10 machine.

I tried creating identical project using Visual Studio Professional 2017 on the same machine and I was able run migration commands with no error.

UPDATE:
I cloned the project to another machine with single but just a bit older installation of Visual Studio (VS Professional 2019 16.0.4) and the migration commands runs without error. So it's either the new version 16.1.6 or installing VS 2019 alongside 2017 which is causing the error?

**Comment by ajcvickers** [comment] 2019-09-07 19:56
@corix010 Can you post the `.csproj` file?

**Comment by corix010** [comment] 2019-09-09 14:16
@ajcvickers I did several sample projects. All gave the same error. The following is from one of them:
https://github.com/corix010/CoreMVCBlogger/blob/master/Blogger/Blogger.csproj

**Comment by smitpatel** [comment] 2019-09-09 17:29
@corix010 - That is class library. `OutputType` is not set to Exe.

**Comment by bricelam** [comment] 2019-09-18 22:34
Duplicate of #16386

**Closed** 2022-10-16 14:39 UTC
Labels: customer-reported
