### ISSUE TITLE
Performance issue while querying for a high page number.

### ISSUE THREAD

**Issue by akshay-zz** [dotnet/efcore#30861] opened 2023-05-09 19:11 UTC
## Problem
If we try to fetch records using pagination. There's a huge difference in execution time as the offset grows through the Linq method syntax. I'm working with Postgres. The page number will never reach this in practical life but even though I found the ef core behavior a little weird.

```
Directly querying against the database
Page = 1, PageSize = 100, time -  ~0.3 sec 
Page = 185300, PageSize = 100, time -  ~5 sec 

By ef core(Linq query syntax)
Page = 1, PageSize = 100, time -  ~1 sec 
Page = 185300, PageSize = 100, time -  ~180 sec

By ef core(Raw SQL query)
Page = 1, PageSize = 100, time -  ~1 sec 
Page = 185300, PageSize = 100, time -  ~5sec
```
Also, I saw that as we increase the page number. Ef core was taking respectively more time to fetch the data in compare to the raw SQL query

```C#
IQueryable<T> source
var items = await source
    .Skip((pageNumber - 1) * pageSize)
    .Take(pageSize).ToListAsync(cancellationToken);
```

The query that is getting generated by ef core is very simple and similar to the below query.
```
SELECT column1, column2
FROM 
my_table AS f 
WHERE f.status = 'active'::status 
ORDER BY column1, column2 DESC 
LIMIT @__p_1 OFFSET @__p_0
```

### Include provider and version information

EF Core version: 6.0.14
Database provider: (Npgsql.EntityFrameworkCore.PostgreSQL)
Target framework: (.NET 6.0)
Operating system: Win 11
IDE: (Visual Studio 2022 17.4.4)

**Comment by ajcvickers** [comment] 2023-05-10 08:32
@akshay-zz Consider using [keyset pagination](https://learn.microsoft.com/en-us/ef/core/querying/pagination#keyset-pagination).

**Comment by ajcvickers** [comment] 2023-05-10 08:42
@akshay-zz Can you post the SQL being used for the direct query and raw SQL cases?

**Comment by akshay-zz** [comment] 2023-05-10 08:45
I have mentioned in the issue itself. Both places used the same raw sql query. Also this the same query that is getting generated by ef core while querying with Linq method syntax

**Comment by AndriySvyryd** [comment] 2023-05-10 20:13
cc @roji

**Comment by roji** [comment] 2023-05-11 09:48
@akshay-zz to be sure I understand, are you saying that the same raw SQL runs slowly when executed by EF, but is fast when executed directly without EF? That would definitely odd - we're going to need to see a minimal, runnable repro.

**Comment by akshay-zz** [comment] 2023-05-11 09:54
Yes @roji , Even if I use `ef.SqlQuery("...")`. It works fine. Only switching to the **Linq method syntax** was facing this issue. Which I feel is quite odd. I will try to create a minimal repo. It will take some time for me to do so. Allow me few days.

**Comment by roji** [comment] 2023-05-11 09:58
No problem @akshay-zz. I highly suspect there's some small difference between the EF-generated SQL and the other SQL, otherwise this would be very strange.

**Comment by akshay-zz** [comment] 2023-05-14 11:05
Hi, here is a very small repo. Here the query is not taking much time. But we can see the difference in the query execution time.

Database running on [docker](https://hub.docker.com/_/postgres)
Repo: https://github.com/akshay-zz/EfCorePerformance

Sql query
```
 SELECT p."Id", p."Address", p."Age", p."Name"
      FROM "Person" AS p
      LIMIT pageSize OFFSET pageNumber
```
On executing the same raw SQL a few times from PG ADMIN
Raw Query(page no 1 & page size 100)
```
00:00:00.70, 00:00:00.81, 00:00:00.98, 00:00:00.115, 00:00:00.103, 00:00:00.63, 00:00:00.101
```

Raw Query(page no 185181 & page size 100)
```
00:00:00.105, 00:00:00.151, 00:00:00.109, 00:00:00.70, 00:00:00.72, 00:00:00.77
```
Following are the result from ef core log i .e ` Executed DbCommand (xx ms) [Parameters=[], CommandType='Text', CommandTimeout='30']`

Ef core func(page no 1 && page size 100)
```
2ms, 4ms, 3ms,4ms, 6ms, 4ms
```

Ef core func(page no 185181 && pageSize 100)
```
2892ms, 2642ms, 1544ms, 3239ms, 2621ms, 2697ms
```
Ef core raw query(page no 1 && page size 100)
```
2ms, 2ms, 2ms, 2ms, 2ms, 2ms
```

Ef core raw query(page no 185181 && pageSize 100)
```
31ms, 48ms, 52ms, 29ms, 27ms, 30ms
```

Here also we can easily see there's a huge difference in Linq method syntax and in executing the same query as raw SQL.

**Comment by roji** [comment] 2023-05-16 09:50
As expected, the SQL between the LINQ and SQL versions is different. When using LINQ, the SQL is:

```sql
SELECT p."Id", p."Address", p."Age", p."Name"
FROM "Person" AS p
LIMIT $1 OFFSET $2
```

While the SQL query interpolates the constants directly into the SQL:

```sql
SELECT p."Id", p."Address", p."Age", p."Name"
FROM "Person" AS p
LIMIT 10 OFFSET 20
```

I can indeed see a considerable difference in running time between the two (0.55s for the constant version, 2.3s for the parameterized) - so this is a duplicate of #28632 (it's good to get a minimal repro for PostgreSQL as well - thanks for that. Interestingly, the plan for the two queries is exactly the same:

```
Limit  (cost=3661.85..3663.83 rows=100 width=47)
  ->  Seq Scan on "Person" p  (cost=0.00..365891.44 rows=18503244 width=47)
```

Note that embedding constants in the SQL also has a performance disadvantage, in that you have constantly changing SQLs; this defeats the prepared statement mechanism implemented inside Npgsql, causing eviction of other SQLs and slowing your application down.

I'm going to go ahead and close this as a duplicate of #28632, but will also follow up with the PostgreSQL people to understand the performance gap.

**Comment by roji** [comment] 2023-05-16 09:50
Duplicate of #28632

**Closed by roji** 2023-05-16 09:50 UTC
Labels: closed-duplicate, customer-reported

**Comment by roji** [comment] 2023-05-16 09:51
One last note: regardless of the performance gap above, using LIMIT/OFFSET for pagination of a large dataset is generally a bad idea - even with the more efficient constant version, performance degrades as you page. Consider using keyset pagination instead - [see these docs](https://learn.microsoft.com/en-us/ef/core/querying/pagination).
