### ISSUE TITLE
Performance issue while executing multiple contexts using Task Parallel 

### ISSUE THREAD

**Issue by vmohan074** [dotnet/efcore#23924] opened 2021-01-20 10:18 UTC
I create multiple instances of DBContext in the Context Factory.cs and create context inside Task parallel. The use case is to update10 million records(1 Parent with 4 child tables), so we split the records as 10k and send it to EF core. In order to increase the performance of update, we are using Task parallel and creating multiple instances of DBContexts. But the performance numbers are not what we expect, is there any other way to improve the performance.

**Context Factory.cs:**

```C#
public DbContext CreateDbContext()
        {
            var builder = new DbContextOptionsBuilder<PCDCDbContext>();
            builder.UseSqlServer(connectionString,
                providerOptions => {
                    providerOptions.EnableRetryOnFailure(3, new TimeSpan(0, 0, 1), null);
                    providerOptions.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery);
                });
            return new PCDCDbContext(builder.Options);
        }
```
**Program.cs**

```C#
Task t = Task.Run(() =>
                    {
                        using (var context = contextFactory.CreateDbContext())
                        {
                                context.ChangeTracker.AutoDetectChangesEnabled = false;
                                context.UpdateRange(item);
                                context.ChangeTracker.DetectChanges();
                                context.SaveChanges();
                           
                        }
                    });
                    tskContext.Add(t);
                }
                Task.WaitAll(tskContext.ToArray());
```

**Comment by anranruye** [comment] 2021-01-20 10:34
don't do this with DbContext SaveChanges. Ef is not designed to perform bulk operations. 
Use raw Sql command instead.

**Comment by vmohan074** [comment] 2021-01-20 11:39
> don't do this with DbContext SaveChanges. Ef is not designed to perform bulk operations.
> Use raw Sql command instead.

I do understand, but EF core was helpful in creating DB models and we started that way. It will be great if we can get the some descent performance numbers for the insert using EF Core.

**Comment by ajcvickers** [comment] 2021-01-20 16:49
@vmohan074 Are you doing updates or inserts or both? With 10 million records, this is going to be somewhat slow, depending on your hardware. #795 will help for updates like this.

**Comment by ajcvickers** [comment] 2021-01-29 17:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:19 UTC
Labels: closed-no-further-action, customer-reported
