### ISSUE TITLE
QueryFilter Expression.Invoke() should be evaluated on client prior to SQL translation

### ISSUE THREAD

**Issue by krispenner** [dotnet/efcore#18613] opened 2019-10-28 04:42 UTC
I have an `Expression.Invoke()` call in my `QueryFilter` which was properly invoked in EF Core 2.1 prior to the SQL translation and the output result of the expression invocation was included correctly in the generated SQL query as a SQL parameter.

As of EF Core 3.0, this no longer works. I get an error:
`InvalidOperationException: No coercion operator is defined between types 'ApplicationDbContext' and 'System.String'.`

I would assume this has to do with [Client vs. Server Evaluation](https://docs.microsoft.com/en-us/ef/core/querying/client-eval) changes in EF Core 3.0.

However, as this can be and needs to be invoked prior to going to the database, I would expect this to still work. Maybe this isn't a bug and there is just a new way to perform this, but I can't find anything help relating to this scenario in EF Core 3.0.

### Steps to reproduce
```cs
// add tenant query filter

// eg. User e
var entityParameter = Expression.Parameter(typeof(TEntity), "e");

// eg. "TenantId"
var propertyNameConstant = Expression.Constant(propertyName, typeof(string));

// EF.Property<string>(e, "TenantId")
var efPropertyMethod = typeof(EF).GetMethod(nameof(EF.Property), BindingFlags.Public | BindingFlags.Static).MakeGenericMethod(modelState.TenantKeyType);  // eg. EF.Property<string>
var efPropertyMethodCall = Expression.Call(efPropertyMethod, entityParameter, propertyNameConstant);

//==============================
// This is no longer evaluated on the client prior to query translation, it was in EF 2.1.
// InvalidOperationException: No coercion operator is defined between types 'MultiTenancyServer.Samples.AspNetIdentityAndEFCore.Data.ApplicationDbContext' and 'System.String'.
// 'tenancyContext' exists on the DbContext 'ApplicationDbContext' as per https://github.com/aspnet/EntityFrameworkCore/issues/18417
//==============================
// (() => tenancyContext.Tenant.Id)()
var invokeTenantId = Expression.Invoke(tenantId);

// (string)(() => tenancyContext.Tenant.Id)()
var typedTenantId = Expression.Convert(invokeTenantId, modelState.TenantKeyType);

// EF.Property(e, "TenantId") == (string)(() => tenancyContext.Tenant.Id)()
var expression = Expression.Equal(efPropertyMethodCall, typedTenantId);

var lambda = Expression.Lambda(expression, entityParameter);
builder.HasQueryFilter(lambda);
```

Full code library working with EF Core 2.1
https://github.com/MultiTenancyServer/MultiTenancyServer.EntityFrameworkCore/blob/master/src/EFCore/Extensions/TenancyEFExtensions.cs

### Further technical details
EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.4

**Comment by ajcvickers** [comment] 2019-10-28 23:41
Duplicate of #18510

**Closed** 2022-10-16 14:52 UTC
Labels: customer-reported
