### ISSUE TITLE
MigrationBuilder.Sql ignores suppressTransaction value

### ISSUE THREAD

**Issue by jorgeyanesdiez** [dotnet/efcore#4633] opened 2016-02-24 09:59 UTC
### Functional impact

It is not possible to execute EF7 migrations that run SQL statements that are not supported inside a transaction because the parameter to suppress the transaction seems to be ignored.
### Minimal repro steps

1) Create a project that supports EF migrations (default web template, for example) and configure the database connection. In my case I'm using SQL Server 2012 Standard.
2) Add a new migration `(dnx ef migrations add Problem)`
3) Replace the contents of the method

```
protected override void Up(MigrationBuilder migrationBuilder)
```

with

```
migrationBuilder.Sql("CREATE FULLTEXT CATALOG [FT_MyCatalog]", suppressTransaction: true);
```

Note that `suppressTransaction` is `true`

4) Run the migration `dnx ef database update`
5) An error is shown

```
System.Data.SqlClient.SqlException (0x80131904): CREATE FULLTEXT CATALOG statement cannot be used inside a user transaction.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.<>c.<ExecuteNonQuery>b__13_0(DbCommand cmd, IRelationalConnection con)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.Execute[T](IRelationalConnection connection, Func`3 action, String executeMethod, Boolean openConnection, Boolean closeConnection)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, Boolean manageConnection)
   at Microsoft.Data.Entity.Storage.RelationalCommandExtensions.ExecuteNonQuery(IEnumerable`1 commands, IRelationalConnection connection)
   at Microsoft.Data.Entity.Migrations.Internal.Migrator.Execute(IEnumerable`1 relationalCommands)
   at Microsoft.Data.Entity.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.Data.Entity.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
ClientConnectionId:7d941487-ebdc-40fe-a748-1dba27a51898
Error Number:574,State:0,Class:16
CREATE FULLTEXT CATALOG statement cannot be used inside a user transaction.
```
### Expected result

The migration should have been executed.
### Actual result

The migration fails.
### Further technical details

See: https://github.com/aspnet/EntityFramework/blob/2bc7eaa29cc57f7d550ab4eeba24b07c940595a2/src/Microsoft.EntityFrameworkCore.Relational/Migrations/MigrationBuilder.cs#L600
around line 600. It seems that nothing is done with the `suppressTransaction` parameter.

**Comment by rowanmiller** [comment] 2016-02-24 17:59
Probably a dupe of https://github.com/aspnet/EntityFramework/issues/2558

**Comment by jorgeyanesdiez** [comment] 2016-03-21 08:28
Yes, it's a dupe. Sorry but I couldn't find it earlier.

**Closed** 2022-10-16 09:30 UTC
