### ISSUE TITLE
Entity equality causes translation failure inside projection

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#21157] opened 2020-06-06 09:13 UTC
The following fails:

```c#
_ = await context.Blogs
    .Select(b => new
    {
        Foo = b.BlogDetails == null ? null : new
        {
            b.BlogDetails.Id
        }
    })
    .Where(x => x.Foo != null)
    .ToListAsync();
```

The expression tree after preprocessing:

```
[Microsoft.EntityFrameworkCore.Query.QueryRootExpression]
    .LeftJoin([Microsoft.EntityFrameworkCore.Query.QueryRootExpression], b => Property(b, "BlogDetailsId"), b0 => Property(b0, "Id"), (o, i) => new TransparentIdentifier`2(Outer = o, Inner = i))
    .Where(b => (IIF((b.Inner == null), null, new <>f__AnonymousType1`1(Id = b.Inner.Id)) != null))
    .Select(b => new <>f__AnonymousType0`1(Foo = IIF((b.Inner == null), null, new <>f__AnonymousType1`1(Id = b.Inner.Id))))
```

The `b.Inner == null` causes translation failure.

Originally flagged by @mdmoura in #21148

**Comment by smitpatel** [comment] 2020-06-06 19:08
Duplicate of #17020 

Wrong title.

**Comment by smitpatel** [comment] 2020-06-06 19:09
Comparing `IIF((b.Inner == null), null, new <>f__AnonymousType1`1(Id = b.Inner.Id))` to null fails in translation.

**Closed** 2022-10-16 18:28 UTC
Labels: customer-reported
