### ISSUE TITLE
Error when updating the entity with primary key default value (zero).

### ISSUE THREAD

**Issue by ethembynkr** [dotnet/efcore#23737] opened 2020-12-19 15:04 UTC
I get error when updating the entity with primary key 0(zero). How can I fix it?

```
public class User
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { get; set; }
        public LocalizedEntity NationalityName { get; set; }
    }
[Owned]
public class LocalizedEntity
    {
        public string Primary { get; set; }
        public string Secondary { get; set; }
    }
````
Error:

`InvalidOperationException: The value of 'User.NationalityName#LocalizedEntity.UserId' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.`

EF Core version: 5.0.0

**Comment by smitpatel** [comment] 2020-12-21 22:21
Duplicate of #23730

**Closed** 2022-10-16 19:16 UTC
Labels: customer-reported
