### ISSUE TITLE
SQL clauses on the resulting object of a subquery joined into a table are evaluated on the client.

### ISSUE THREAD

**Issue by JabX** [dotnet/efcore#12652] opened 2018-07-12 20:13 UTC
Hello,

I am not sure if the title is very clear but I have an issue with SQL translation : every clause that apply on a object that has been created in a sub select query in a join operation in evaluated on the client

I have a complete self-contained example that shows the problem below:
```cs
using System;
using System.Linq;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace EFIssues
{
    class ItemA
    {
        public int Id { get; set; }
        public string Test { get; set; }
    }

    class ItemB
    {
        public int Id { get; set; }
        public int ItemAId { get; set; }
    }

    class DtoB
    {
        public int Id { get; set; }
        public int ItemAId { get; set; }
    }

    class TestContext : DbContext
    {
        public TestContext(DbContextOptions<TestContext> options)
            : base(options)
        {
        }

        public DbSet<ItemA> ItemA { get; set; }
        public DbSet<ItemB> ItemB { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var connection = new SqliteConnection("DataSource=:memory:");
            connection.Open();

            var context = new ServiceCollection()
                .AddDbContext<TestContext>(options => options.UseSqlite(connection))
                .AddLogging(o => o.AddConsole())
                .BuildServiceProvider()
                .GetRequiredService<TestContext>();

            context.Database.EnsureCreated();

            var query = (
                from a in context.ItemA
                join b in
                    from b in context.ItemB
                    select new DtoB
                    {
                        Id = b.Id,
                        ItemAId = b.ItemAId
                    }
                    on a.Id equals b.ItemAId
                orderby b.Id // Client eval
                select new
                {
                    b.Id,
                    a.Test
                }).ToList();

            Console.ReadKey();
        }
    }
}
```
The client eval also happens with a WHERE clause.

This is a major issue for me because I have about 40 queries where I need to repeat the same join sequence over and over to get the same data that will be used as filter criteria. The obvious solution for me was to create a DTO that contains all the criteria and a subquery that gets all of it with the joins and all, and then replace the join sequences in the queries by a single join to that subquery. Also, this subquery will definitely evolve in the future, and I'd be very happy to update it once instead of 40 times.

### Further technical details
EF Core version: 2.1.1
Database Provider: example with SQLite 2.1.1, using Npgsql.EFCore 2.1.1 in the real world

**Comment by divega** [comment] 2018-07-16 19:55
*EF Test:* This is a duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/8107, but we can provide workaround. For example, we believe if you use an anonymous type instead of a DTO, it would translate to the server.

**Comment by JabX** [comment] 2018-07-16 22:59
Hello,

Thank you for taking the time to answer, but this is a bit different from the issue you linked because the scenarios you're describing there are actually supported, the problem specifically arises when a join or multiple from queries are involved.

Using an anonymous type instead yields the same client-side evaluation and isn't a good workaround anyway, since the initial objective was to move the subquery into its own method, and you can't return an anonymous type from a method.

**Comment by maumar** [comment] 2018-08-28 23:38
Translation for this case is indeed blocked even when anonymous type is used in the middle of the query, due to https://github.com/aspnet/EntityFrameworkCore/issues/8094. The workaround currently is to only use anonymous type when you are not binding to it afterwards (i.e. in final projection). 

If the entire query gets translated, we won't pull any additional data from db so perf impact should be small. E.g.

```cs
var query = from a in ctx.ItemA
			join b in ctx.ItemB on a.Id equals b.ItemAId
			orderby b.Id
			select new
			{
			    b.Id,
			    a.Test
			};
```

produces:

```sql
SELECT [b].[Id], [a].[Test]
FROM [ItemA] AS [a]
INNER JOIN [ItemB] AS [b] ON [a].[Id] = [b].[ItemAId]
ORDER BY [b].[Id], 
```

**Closed** 2022-10-16 13:19 UTC
Labels: customer-reported
