### ISSUE TITLE
How to specify SQL server index column order?

### ISSUE THREAD

**Issue by sandersaares** [dotnet/efcore#15156] opened 2019-03-26 09:40 UTC
I am defining indexes to be applied in migrations with SQL server but I do not see any API to specify the column sort order. Is this feature missing or just not documented? If so, please add either the feature and/or [documentation](https://docs.microsoft.com/en-us/ef/core/modeling/indexes).

**Comment by ajcvickers** [comment] 2019-03-26 16:54
Duplicate of #4150

**Closed** 2022-10-16 13:57 UTC
Labels: closed-duplicate, customer-reported
