### ISSUE TITLE
Sql server Sequence with entity framework core is not working

### ISSUE THREAD

**Issue by SrinivasSrinivas** [dotnet/efcore#8745] opened 2017-06-06 09:36 UTC
Hi,

Sql server Sequence with entity framework core is not working.

The below is my code in model creating.
``` c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{           
	modelBuilder.Entity<ManifestModel>().ToTable("Manifest").HasKey("ManifestId");
	modelBuilder.HasSequence("Manifest_Seq", "cargo");
	modelBuilder.Entity<ManifestModel>().Property("ManifestId").HasDefaultValueSql("next value for cargo.Manifest_Seq"); // first approach

	modelBuilder.Entity<ManifestModel>().Property("ManifestId").ForSqlServerHasDefaultValueSql("next value for cargo.Manifest_Seq"); // second approach
}
```
The below is where I am adding the new "ManifestModel" object.
``` c#
ManifestModel entity = new ManifestModel();
this.DbContext.Set<ManifestModel>().Add(entity);
```
But here the primary key column "ManifestId" is not being incremented according to the sequence.

### Further technical details
EF Core version: Microsoft.EntityFrameworkCore - 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer - 1.1.2
Operating system: windows 7
IDE: Visual Studio 2017

**Comment by divega** [comment] 2017-06-06 14:16
@SrinivasSrinivas the value from the sequence won't be applied until the entity is saved to the database.

**Comment by SrinivasSrinivas** [comment] 2017-06-07 06:19
Hi,

I am calling the SaveChanges() also, but it is giving exception as the primary key value is not incremented and the default value of integer i.e. 0 is being inserted.

Thanks.

**Comment by ajcvickers** [comment] 2017-06-09 18:30
@SrinivasSrinivas Can you post a full code listing or project that reproduces the behavior you are seeing?

**Comment by ajcvickers** [comment] 2017-06-16 18:14
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:07 UTC
