### ISSUE TITLE
DbContext with compiled model freezes on initialization on Android

### ISSUE THREAD

**Issue by pekspro** [dotnet/efcore#32346] opened 2023-11-18 19:14 UTC
## File a bug

A DbContext that uses a compiled model will freeze on initialization on Android. I guess this for introduced for the fix of https://github.com/dotnet/efcore/issues/31751. It works fine on Windows.

### Include your code

Full sample project: https://github.com/pekspro/MauiIssues/tree/EfCore_32346_ContextFreezesOnAndroid

I have this super simple DbContext with a compiled model in an MAUI application;

```C#
public sealed class GeneralDatabaseContext : DbContext
{
    public string FileName;

    public GeneralDatabaseContext()
    {
        FileName = "?";
    }

    public GeneralDatabaseContext(string basePath)
    {
        FileName = Path.Combine(basePath, "generaldb.sqlite");
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // Command to update compiled model:
        // dotnet ef dbcontext optimize --context GeneralDatabaseContext --output-dir GeneralDatabase\CompiledModel --namespace MauiIssues.GeneralDatabase.CompiledModel

        optionsBuilder
            .UseModel(GeneralDatabaseContextModel.Instance)
            .UseSqlite($"Data Source={FileName};");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {        
    }

    public DbSet<Blog> Blog { get; set; } = null!;
}

public sealed class Blog
{
    public int BlogId { get; set; }
}
```

When I run this code it will freeze on `EnsureDeleted`.

```C#
var context = new GeneralDatabaseContext(cachePath);
context.Database.EnsureDeleted();
context.Database.EnsureCreated();
```

### Reason

The code freeze in the compile model code at `thread.Join();` below:

```C#
static GeneralDatabaseContextModel()
{
    var model = new GeneralDatabaseContextModel();

    if (_useOldBehavior31751)
    {
        model.Initialize();
    }
    else
    {
        var thread = new System.Threading.Thread(RunInitialization, 10 * 1024 * 1024);
        thread.Start();
        thread.Join();

        void RunInitialization()
        {
            model.Initialize();
        }
    }

    model.Customize();
    _instance = model;
}
```

### Workaround

Run this code before any DbContext is created, like in MauiProgram.cs:

```C#
System.AppContext.SetSwitch("Microsoft.EntityFrameworkCore.Issue31751", true);
```

### Include provider and version information

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 8
Operating system: Android

**Comment by AndriySvyryd** [comment] 2024-08-17 00:46
This is a duplicate of https://github.com/dotnet/efcore/issues/31370
Once that is fixed we'll remove the thread manipulation code.

**Closed by AndriySvyryd** 2024-08-17 00:46 UTC
Labels: type-bug, customer-reported, area-aot, resourcing-discussion
