### ISSUE TITLE
EFCORE 7 not supported in Azure Function V4 .net6 isolated? 

### ISSUE THREAD

**Issue by MacMcDell** [dotnet/efcore#30897] opened 2023-05-15 16:23 UTC
## File a bug
I cannot seem to create migrations following the 

### Include your code
Using VS2022 I create a brand new .net 6 isolated function project. 
### Add the following references to efCore
```
 <Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.10.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.5" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
```
###  create dbcontext file
```C# 
using Microsoft.EntityFrameworkCore;

namespace EfCore7Test
{
    public class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions<MyDbContext> options) : base(options)
        { }
        public DbSet<Animal> Animals {get;set;}
    }
}
```

### update program.cs (tried both settings.. neither work) 
```C#
using EfCore7Test;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureServices(DoServiceConfiguration)
    .Build();

void DoServiceConfiguration(IServiceCollection services)
{
    var sp = services.BuildServiceProvider();
    var config = sp.GetService<IConfiguration>();
    
    services.AddDbContext<MyDbContext>(options =>
    SqlServerDbContextOptionsExtensions.UseSqlServer(options,config.GetConnectionString("default"))
   // options.UseSqlServer(config.GetConnectionString("default"))
    );
}

host.Run();
```

### Add connection string to appsettings.local 

```Json 
{
  "IsEncrypted": false,
  "ConnectionStrings": {
    "default": "aConnectionToSqlServer"
  },
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"
    }
}
```

### Try to add initial migration

PS C:\Projects\EfCore7Test\EfCore7Test> dotnet ef migrations add initial
Build started...
Build succeeded.
Unable to create an object of type 'MyDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

I have reviewed the link multiple times.. what am I missing here? Would really appreciate direction to a working Azure Function V4 .net6 isolated (long term support) sample. Super frustrating. 

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
PS C:\Projects\EfCore7Test\EfCore7Test> dotnet ef migrations add initial
Build started...
Build succeeded.
Unable to create an object of type 'MyDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

```

### Include provider and version information

EF Core version:
 dotnet ef --version
Entity Framework Core .NET Command-line Tools
7.0.5
Database provider: 
 Microsoft.EntityFrameworkCore.SqlServer
Target framework:
.Net 6
Operating system:
Visual Studio 2022 17.5.5
Azure Function 
V4 Isolated

**Comment by MacMcDell** [comment] 2023-05-15 18:55
I was finally able to create a migrations file by adding a parameterless ctor on MyDbContext AND overriding OnConfiguring, however the database refuses to update saying no connection string... and naturally this horrendousness won't even run any longer as it has no idea what to do anymore.    Is the issue got to do with it being isolated? This just seems so hokey.  The error says no db, but I can confirm in my function, I am able to inject and get a result from the db. If I leave the configuration like above and run the app, I get data, but I cannot update db and I cannot create/apply migrations 
```

       public class MyDbContext : DbContext //this code is terrible... 
    {
        private readonly IConfiguration _config;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseSqlServer(_config.GetConnectionString("default"));
        }

        public MyDbContext()
        {
        }
      
        public MyDbContext(IConfiguration config)
        {
            _config = config;
        }

        public MyDbContext(DbContextOptions<MyDbContext> options) : base(options)
        { }
        public DbSet<Animal> Animals {get;set;}


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Animal>().ToTable("Animal");
        }
    }

```


### I keep getting this error: 
```
"C:\Program Files\dotnet\dotnet.exe" ef database update --project EfCore7Test\EfCore7Test.csproj --startup-project EfCore7Test\EfCore7Test.csproj --context EfCore7Test.MyDbContext --configuration Debug 20230515180959_Initial
Build started...
Build succeeded.
System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, DbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
Process terminated with exit code 1
```



The function however does/is connecting to the docker sql server and is returning data, so when the app runs it is  getting the right connection string etc ... 

#### Function1.cs
```
    private MyDbContext _context; 

        public Function1(ILoggerFactory loggerFactory, MyDbContext context)
        {
            _context = context;
            _logger = loggerFactory.CreateLogger<Function1>();
        }

        [Function("Function1")]
        public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequestData req)
        {

            var x =  _context.Animals.Where(x => x.Id == 1).ToList();
...
```

overriding onconfiguring at the context seems to remove all the appeal of doing DI... 
            

Attaching a zip of the project as I have no idea how to work around this... 
[EfCore7Test_zip.zip](https://github.com/dotnet/efcore/files/11481032/EfCore7Test_zip.zip)

**Comment by MacMcDell** [comment] 2023-05-15 20:43
Continuing to absolutely murder the code... I was eventually able to achieve both migrations and database update AND actually run the code.  Following this guys same ramble https://github.com/dotnet/efcore/issues/25036 I can see he was having exact same issues.. code runs but no migrations or updates. Adding a new class that invokes the IDesignTimeDvContextFactory<T>  makes it work: 

```C#
public class MyDbContextFactory : IDesignTimeDbContextFactory<MyDbContext>
{
    public MyDbContext CreateDbContext(string[] args)
    {
        IConfigurationRoot configuration = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("local.settings.json", optional:true)
            .AddJsonFile("settings.json",optional:true)
            .Build();
    
        var connectionString = configuration.GetConnectionString("default");
    
        var optionsBuilder = new DbContextOptionsBuilder<MyDbContext>();
        optionsBuilder.UseSqlServer(connectionString);
    
        return new MyDbContext(optionsBuilder.Options);
    }
}
```

After this I was able to run migrations locally. I am cringing to wire this to CI.

**Comment by ajcvickers** [comment] 2023-05-16 10:47
@davidfowl Any idea why this isn't working with your host running magic?

**Comment by ajcvickers** [comment] 2023-06-14 19:11
Ping @davidfowl

**Comment by davidfowl** [comment] 2023-06-14 20:08
```C#
void DoServiceConfiguration(IServiceCollection services)
{
    var sp = services.BuildServiceProvider();
    var config = sp.GetService<IConfiguration>();
    
    services.AddDbContext<MyDbContext>(options =>
    SqlServerDbContextOptionsExtensions.UseSqlServer(options,config.GetConnectionString("default"))
   // options.UseSqlServer(config.GetConnectionString("default"))
    );
}
```
This looks suspect, @MacMcDell is this the logic in your application?

**Comment by MacMcDell** [comment] 2023-06-15 13:30
I am doing as such... 
```
     void DoConfiguration(IServiceCollection services)
         {
             var sp = services.BuildServiceProvider();
             var config = sp.GetService<IConfiguration>();
          
            services.AddDbContext<MyDbContext>(options =>
            {
                options.UseSqlServer(config.GetConnectionString("default"));
                options.EnableSensitiveDataLogging(true);
            });
           }
```

**Comment by ajcvickers** [comment] 2023-07-07 16:40
> The app crashes attempting to map columns with the .ToJson() extension.

Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-08-02 19:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-08-02 19:10 UTC
Labels: customer-reported
