### ISSUE TITLE
ChangeTracker: How to get original owned entity when modifying a principals owned property?

### ISSUE THREAD

**Issue by davidroth** [dotnet/efcore#21972] opened 2020-08-07 14:06 UTC
When implementing auditing in ef, its currently not possible to get the original value of a modified owned entity.

### Steps to reproduce

Example model:

```csharp
public class Order
{
     public int Id { get; set; }
     public Money Total { get; set; }
}

[Owned]
public class Money
{
    public decimal Value { get; set; }
    public string Currency { get; set; }
}

```

Example code:
```csharp

// Bootstrap an order with an initial value of 3 for the total:
using (var context = new SampleContext())
{
    var oder = new Order();
    order.Total = new Money() { Value = 3, Currency =  "USD" };
    context.SaveChanges();
}

// Lets load the order and modify its total owned property:
using (var context = new SampleContext())
{
   var order = context.Orders.First();
   order.Total = new Money() { Value =  5, Currency =  "USD" };

   // ChangeTracker.Entries only contains the new Money with value "5"
   // Unfortunately, the old Money instance with value "3" is not reachable in change tracker
   // Search for money in navigations does not work as only the new money with value "5" is available:      
   var navigation = context.ChangeTracker.Entry(order).Navigations.First();
   var currentMoney = navigation.CurrentValue;
   var previousMoney = navigation.OriginalValue; // <----- This property does not exist         
   context.SaveChanges();
}
```

### Expected:

`NavigationEntry` currently only provides a `CurrentValue` property. If it would provide a `OriginalValue` property containing the previous Money with value "5", we could properly audit this change.

### Further technical details

EF Core version: 3.1

**Comment by AndriySvyryd** [comment] 2020-08-07 15:52
Duplicate of https://github.com/dotnet/efcore/issues/10013

**Closed** 2022-10-16 18:35 UTC
Labels: customer-reported
