### ISSUE TITLE
EF.Functions IN?

### ISSUE THREAD

**Issue by JDMilne** [dotnet/efcore#19580] opened 2020-01-13 18:23 UTC
I love to see a EF.Functions.In function to assist in creating dynamic Linq queries.

Usage:

long[] statuses = { 2, 6, 7 };  (support for IEnumerable would be better than arrays).
var list = context.Orders.Where(o => EF.Functions.In(o.StatusID, statuses)

Currently we have to use a switch statement with statuses.Length as the switch expression and cases with an increasing number of 'ORs'  (e.g.  (o => o.StatusId == statuses[0] || o.StatusId == statuses[1] || .... ).

Using statuses.Contains(o.StatusId) is not an option as it requires the result to be evaluated locally.

**Comment by ErikEJ** [comment] 2020-01-13 18:48
Have a look at this: https://github.com/divega/ContainsOptimization/tree/master/ContainsOptimization

**Comment by ErikEJ** [comment] 2020-01-13 18:54
More context here: https://github.com/dotnet/efcore/issues/13617#issuecomment-447515393

**Comment by ajcvickers** [comment] 2020-01-17 19:33
@JDMilne `statuses.Contains(o.StatusId)` should not be evaluated locally. Please attach a small, runnable project or post a complete code listing that reproduces this.

**Comment by ajcvickers** [comment] 2020-01-24 17:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:05 UTC
Labels: closed-could-not-reproduce, customer-reported
