### ISSUE TITLE
Could I ReplaceService for create base Conventions

### ISSUE THREAD

**Issue by borissizov** [dotnet/efcore#28463] opened 2022-07-16 12:14 UTC
Hi! I want to make base Conventions for by context, like a `IModelCustomizer`:

```C#
services.AddDbContext<TDbContext>(options =>
{
    options.ReplaceService<IModelCustomizer, EntitiesCustomizer>()
	    .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking)
	    .UseNpgsql(connectionString);
});
```

Usage:
internal class `EntitiesCustomizer : RelationalModelCustomizer`

Could you help me, and discuss how can I do the same thing for ef 6, `ConfigureConventions(ModelConfigurationBuilder configurationBuilder)` method?

**Comment by ajcvickers** [comment] 2022-07-23 09:18
@borissizov Can you explain a bit more what the replaced conventions would do here and how they would be used in your application or library?

**Comment by ajcvickers** [comment] 2022-08-08 15:33
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-08-08 15:33 UTC
Labels: customer-reported
