### ISSUE TITLE
dotnet-ef computes incorrect assembly filename for standalone apps

### ISSUE THREAD

**Issue by mgpnd** [dotnet/efcore#5961] opened 2016-07-03 09:35 UTC
### Steps to reproduce

Create two projects: first with POCO models (Personal.Common), second with context (Personal.Database)

The example repository: https://github.com/mgpnd/dotnetexpample
### The issue

Command `dotnet ef migrations add Initial -v` running from src/Personal.Database gives the next output:

> Using target project 'Personal.Database'.
> Using startup project 'Personal.Database'.
> Using framework 'netcoreapp1.0'.
> Using configuration 'Debug'.
> Running /usr/local/share/dotnet/dotnet build /Users/username/code/dotnetexample/src/Personal.Database/project.json --configuration Debug --framework netcoreapp1.0
> Process ID: 1861
> Project Personal.Common (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
> Project Personal.Database (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
> Setting the data directory to '/Users/username/code/dotnetexample/src/Personal.Database/bin/Debug/netcoreapp1.0/osx.10.11-x64/'.
> Invoking dependency command 'Microsoft.EntityFrameworkCore.Design' in project 'Personal.Database'
> Running /usr/local/share/dotnet/dotnet exec --runtimeconfig /Users/username/code/dotnetexample/src/Personal.Database/bin/Debug/netcoreapp1.0/osx.10.11-x64/Personal.Database.runtimeconfig.json --depsfile /Users/username/code/dotnetexample/src/Personal.Database/bin/Debug/netcoreapp1.0/osx.10.11-x64/Personal.Database.deps.json --additionalprobingpath /Users/username/.nuget/packages /Users/username/.nuget/packages/Microsoft.EntityFrameworkCore.Design/1.0.0-preview2-final/lib/netcoreapp1.0/Microsoft.EntityFrameworkCore.Design.dll --assembly /Users/username/code/dotnetexample/src/Personal.Database/bin/Debug/netcoreapp1.0/osx.10.11-x64/Personal.Database --startup-assembly /Users/username/code/dotnetexample/src/Personal.Database/bin/Debug/netcoreapp1.0/osx.10.11-x64/Personal.Database.dll --dispatcher-version 1.0.0-preview2-21431 --data-dir /Users/username/code/dotnetexample/src/Personal.Database/bin/Debug/netcoreapp1.0/osx.10.11-x64/ --project-dir /Users/username/code/dotnetexample/src/Personal.Database --content-root-path /Users/username/code/dotnetexample/src/Personal.Database --root-namespace Personal.Database --verbose migrations add Initial
> Process ID: 1862
> System.IO.FileNotFoundException: Could not load file or assembly 'Personal, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
> File name: 'Personal, Culture=neutral, PublicKeyToken=null'
>    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
>    at Microsoft.EntityFrameworkCore.Design.Internal.OperationExecutor..ctor(CommonOptions options, String environment)
>    at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.Execute(CommonOptions commonOptions, String name, String outputDir, String context, String environment, Action`1 reporter)
>    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
>    at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
> **Could not load file or assembly 'Personal, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.**

Running `/usr/local/share/dotnet/dotnet exec` manually with changed `--attribute` value to `/Users/username/code/dotnetexample/src/Personal.Database/bin/Debug/netcoreapp1.0/osx.10.11-x64/Personal.Database.dll` works fine.
### Further technical details

EF Core version: 1.0.0
Operating system: OS X El Captain 10.11.15

Other details about my project setup:
`dotnet --info` output:

> .NET Command Line Tools (1.0.0-preview2-003121)
> 
> Product Information:
>  Version:            1.0.0-preview2-003121
>  Commit SHA-1 hash:  1e9d529bc5
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.11
>  OS Platform: Darwin
>  RID:         osx.10.11-x64

**Comment by natemcmaster** [comment] 2016-07-05 20:09
The issue is in this section of code: https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Tools/DispatchCommand.cs#L187-L192. In standalone .NET Core projects on x-plat, the APIs from Microsoft.DotNet.ProjectModel give us the filepath for the corehost bootstrapper, not the dynamic lib.

@mgpnd it looks like you want a "portable" instead, but your project.json is missing `"type": "platform"`
```json
"dependencies": {
   "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
   }
}
```

See [Application Types](https://docs.microsoft.com/en-us/dotnet/articles/core/app-types) for more info.

**Comment by mgpnd** [comment] 2016-07-05 20:38
Thank you @natemcmaster 
With `"type": "platform"` it works fine.

**Comment by natemcmaster** [comment] 2016-07-27 16:00
This isn't going to be relevant in the next release. Closing as we will be using a different set of APIs altogether to find compiled output filenames. This work is tracked in https://github.com/aspnet/EntityFramework/issues/6139

**Closed by natemcmaster** 2016-07-27 16:00 UTC
Labels: closed-out-of-scope
