### ISSUE TITLE
Using Query<> and FromSql does not map columns by name

### ISSUE THREAD

**Issue by THammond9** [dotnet/efcore#13489] opened 2018-10-03 15:36 UTC
I am using `this.TenantContext.Query<EnrollmentGetChoicesForSurveyField>().FromSql("EnrollmentGetChoicesForSurveyField {0}", myVar.Value)` to run a stored procedure.
The `EnrollmentGetChoicesForSurveyField` class looks like:

    public class EnrollmentGetChoicesForSurveyField
    {
        public string Label { get; set; }
        public string Value { get; set; }
        public string Key { get; set; }
    }
    
The class is added to the context like:

    public virtual DbQuery<EnrollmentGetChoicesForSurveyField> EnrollmentGetChoicesForSurveyField { get; set; }
    
There is nothing in the `OnModelCreating` method for this class.

In the visual studio debugger I see that the resulting values are mapped like `Value = "UNK", Key = "Unknown", Label = "0"`
but when I run the query the results are like:

    Label		Value	Key
    Unknown		UNK	0

When I changed the order of the results in the stored procedure the values assigned to the properties are changed. I would have expected that the values are assigned by name, but it does not appear that that is the case. Can I get some confirmation on whether this is the desired behavior, how mapping by name can be achieved, or if it cannot, how mapping is determined?

### Further technical details
EF Core version: 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.6

**Comment by THammond9** [comment] 2018-10-05 13:56
I see that this is marked as a bug with a milestone that seems not soon, so I was wondering if there was a work around for this issue? I thought that position of the returned columns in the stored procedure might matter but when I changed the order the values were still mapped incorrectly. How should I arrange things so that the values end up in the correct properties?

**Comment by ajcvickers** [comment] 2018-10-05 15:28
@THammond9 Based on your description above we were working on the assumption that it was using the order, which would be a bug, although since this code has been the same since 1.0 or 1.1, it would be a bug that has likely been around a long time. However, based on your follow up comment this no longer seems to be the case.  Can you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can fully reproduce and investigate.

**Comment by THammond9** [comment] 2018-10-05 19:18
@ErikEJ All of the columns are already aliased. I did try changing the names so that Key & Value were not used in case they were treated special.

@ajcvickers After more investigation, I have found that there is an order being followed. It is: `Key, Value, Label` but I am confused as to how that order is being determined. It is not alphabetical and reordering the class' properties does not affect the order either.

**Comment by THammond9** [comment] 2018-10-05 20:06
Continuing the investigation into this problem:
I think the order is determined by the column creation order in the tables that are being queried. I reproduced this issue with a basic query selecting just a few columns. It just so happened that the columns I chose were listed in the order that they were created in for the table. When I moved the columns around in the select statement, the data ended up in the wrong properties. I also checked the table where I originally had this issue and the columns are listed in `Key, Value, Label` just like the only order that worked. I will try to get something that you can use to test this issue but I think all that needs to be done to repro this issue is create a table with columns A,B,C,D, Id and then create a sproc that is something like `SELECT A, B, C FROM SomeTable WHERE Id = @SomeId` check the values returned, and then change the sproc to `SELECT B, C, A FROM SomeTable WHERE Id =  @SomeId` and see that the value are not matched by name. You should use the same value types for these columns when testing or an `InvalidOperationException` will be thrown (since it could be trying to match an int with a string when things are reordered.)

**Comment by ajcvickers** [comment] 2018-10-08 18:02
For triage: here's my code:
```C#
public class BackingTable
{
    public int Id { get; set; }
    public int One { get; set; }
    public int Two { get; set; }
}

public class ProcType
{
    public int One { get; set; }
    public int Two { get; set; }
}

public class BloggingContext : DbContext
{
    private static readonly LoggerFactory Logger
        = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    public IQueryable<ProcType> GetStatisticCalls(short companyId, DateTime start, DateTime end)
    {
        return Set<ProcType>().FromSql("exec dbo.SomeProc");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BackingTable>();
        modelBuilder.Query<ProcType>();
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var connection = context.Database.GetDbConnection();
            var command = connection.CreateCommand();
            command.CommandText = @"
CREATE PROCEDURE SomeProc
AS
SELECT One as Two, Two as One
FROM BackingTable";

            connection.Open();
            command.ExecuteNonQuery();
            connection.Close();

            context.Add(new BackingTable()
            {
                One = 1,
                Two = 2
            });

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var results = context.Query<ProcType>().FromSql("exec dbo.SomeProc").Single();

            Console.WriteLine($"One: {results.One}");
            Console.WriteLine($"Two: {results.Two}");
        }
    }
}
```
Output:
```
One: 2
Two: 1
```
Logs:
```
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      (QueryContext queryContext) => IEnumerable<ProcType> _InterceptExceptions(
          source: IEnumerable<ProcType> _ToSequence(() => ProcType Single(IEnumerable<ProcType> _ShapedQuery(
                      queryContext: queryContext,
                      shaperCommandContext: SelectExpression:
                          exec dbo.SomeProc
                          ,
                      shaper: UnbufferedEntityShaper<ProcType>))),
          contextType: BloggingContext,
          logger: DiagnosticsLogger<Query>,
          queryContext: queryContext)

dbug: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      exec dbo.SomeProc
```

**Comment by divega** [comment] 2019-03-20 21:30
Revert https://github.com/aspnet/EntityFramework.Docs/commit/e15fc182a057e0aa56d504ba9003b97704c89b77 when fix this.

**Comment by divega** [comment] 2019-03-20 23:18
I was looking at something similar so I tried the repro in the previous comment. I may be missing something simple, but I couldn't observe the behavior described by @THammond9. 

If I swap the columns and the aliases on purpose (as the stored procedure in this repro does) then yes, I see that the values are swapped, but if I just change the order of the columns in the projection in the stored procedure, I still always get the columns in the right order. 

@THammond9 any chance that you can produce a self-contained repro of what you are seeing?

**Comment by ajcvickers** [comment] 2019-03-29 15:32
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by richardbartley** [comment] 2020-02-06 09:09
I can confirm this behavior exists with EFCore 2.2.6

I had 2 columns VehicleOptionId and PaintOptionId with the values being swapped into the Dto.  It was working, but then we added this PaintOptionId column to the entity and stored procedure and then the unexpected behavior started.

My workaround was to explicitly specify Column annotation attributes on the Dto class being used.

e.g.
```
var result = _dbContext.Query<VehicleOptionPublicationDto>()
                .FromSql(DbHelper.GenerateCommandText("usp_GetVehOptions", parameters), parameters)
                .AsNoTracking();
```

Worked only when I added attributes as follows

```
[Column("VehicleOptionId")]
public int VehicleOptionId { get; set; }

[Column("PaintOptionId")]
public int PaintOptionId { get; set; }
```

Originally this class also had a base class with some of the properties on it.  Whether that was a factor here I do not know.  As this was being used for some SqlBulkCopy later the base class was removed.

**Comment by ajcvickers** [comment] 2020-02-10 16:38
@richardbartley EF Core 2.2 is now [out-of-support](https://docs.microsoft.com/en-us/ef/core/what-is-new/). Please file a new issue and include a small, runnable project or complete code listing that reproduces the behavior so we can investigate.

**Closed** 2022-10-16 13:33 UTC
Labels: closed-could-not-reproduce, customer-reported
