### ISSUE TITLE
when the column is DateTimeKind type, the written value and the read value are inconsistent

### ISSUE THREAD

**Issue by Varorbc** [dotnet/efcore#22290] opened 2020-08-28 08:11 UTC
![image](https://user-images.githubusercontent.com/5714438/91536971-2243b080-e948-11ea-8649-be14bfd4d80a.png)

### Steps to reproduce

```csharp

using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var testDbContext = new TestDbContext();
            var test = testDbContext.Test
                                    .Add(new Test
                                    {
                                        Id = Guid.NewGuid(),
                                        CreateTime = DateTime.Now
                                    })
                                    .Entity;

            Console.WriteLine(test.CreateTime.Kind);

            testDbContext.SaveChanges();

            Console.WriteLine(test.CreateTime.Kind);

            var test2 = testDbContext.Test.FirstOrDefault(a => a.Id == test.Id);

            Console.WriteLine(test2.CreateTime.Kind);

            testDbContext = new TestDbContext();
            var test3 = testDbContext.Test.FirstOrDefault(a => a.Id == test.Id);

            Console.WriteLine(test3.CreateTime.Kind);

            Console.ReadLine();
        }
    }

    public class TestDbContext : DbContext
    {
        public virtual DbSet<Test> Test { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            options.UseSqlServer("data source=.;initial catalog=Test;user id=sa;password=test;MultipleActiveResultSets=True;");
        }
    }

    public class Test
    {
        [Key]
        public Guid Id { get; set; }

        public DateTime CreateTime { get; set; }
    }
}


```

### Further technical details

EF Core version:5.0.0-preview.8.20407.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: win 10
IDE: Visual Studio 2019 16.7.2

**Comment by ajcvickers** [comment] 2020-08-28 20:44
Duplicate of #4711

**Closed** 2022-10-16 18:38 UTC
Labels: closed-duplicate, customer-reported
