### ISSUE TITLE
Temporal tables query throws an Exception when using fromsql<T> 

### ISSUE THREAD

**Issue by jvelezc** [dotnet/efcore#11042] opened 2018-02-22 23:40 UTC
The issue only occurs with temporal tables are defined. The column in question is defined:
	[SysStartDate] [datetime2](7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEndDate] [datetime2](7) GENERATED ALWAYS AS ROW END NOT NULL,

```
     protected IQueryable<T> QueryOutputTable<T>(DbContext context) where T : class
        {
            var queryString = SqlQueryBuilder.SelectFromOutputTable(this);
            var connection = context.Database.GetDbConnection();
            var queryWorksWithDapper = connection.Query<T>(queryString).AsQueryable();

            var queryDoesntWorkWithEF = context.Set<T>().FromSql<T>(SqlQueryBuilder.SelectFromOutputTable(this)).ToList();
// BREAKS!
          
            return queryWorksWithDapper;
        }
 
```

The issue also surface with other folks and they did what I called hacks to make it work. 
https://stackoverflow.com/questions/40742142/entity-framework-not-working-with-temporal-table 

Here the exception:
e = {System.InvalidOperationException: The required column 'SysEndDate' was not present in the results of a 'FromSql' operation.
   at Microsoft.EntityFrameworkCore.Query.Sql.Internal.FromSqlNonComposedQuerySqlGenerator.CreateValueBufferFactory(IRelationalValu...
StackTrace = "   at Microsoft.EntityFrameworkCore.Query.Sql.Internal.FromSqlNonComposedQuerySqlGenerator.CreateValueBufferFactory(IRelationalValueBufferFactoryFactory relationalValueBufferFactoryFactory, DbDataReader dataReader)\r\n   at Microsoft.EntityFrameworkCore.Qu...

**Comment by ajcvickers** [comment] 2018-02-28 21:04
@jvelezc We looked at this and discussed it, but it's not clear exactly what is going on. Can you please post a runnable project/solution that reproduces the issue?

**Comment by ajcvickers** [comment] 2018-03-07 19:18
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:10 UTC
Labels: closed-could-not-reproduce
