### ISSUE TITLE
DBQuery<> for 3.1.1

### ISSUE THREAD

**Issue by askeet** [dotnet/efcore#19614] opened 2020-01-16 20:56 UTC
I've  migrated project with custom DBQuery Views from EF Core 2.6 to 3.1   
The query with a child property  returns just one record when it generated the correct Raw SQL  query with more than one record 
 
```
            var test = (
                from v1 in _context.View1
                where v1.Deleted == false
                select new View1Object()
                {
                    ID = v1.ID,
                    Title = v1.Title ,
                    Items= _context.View2
                        .Where(v2 => v2.ID == v1.ID)
                        .Select(v1 =>
                            new View2Object()
                            {
                                FieldID = v2.FieldId,
                                FieldName = v2.FieldName
                            }).ToList()
                }).ToList();
```

### Steps to reproduce

Changed properties 
`DBQuery<>` to `DBSet<>  `
and in the OnModelCreatingPartial 
from 
`modelBuilder.Query<T>().ToView("name","schema")`
 to
`modelBuilder.Entity<T>().HasNoKey().ToView("name","schema")  `

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  4.7.2
Operating system: Windows 10  
IDE:  Visual Studio 2019 16.3

**Comment by ajcvickers** [comment] 2020-01-17 17:46
@askeet Please attach a small, runnable project or post a complete code listing that reproduces this behavior so that we can investigate.

**Comment by ajcvickers** [comment] 2020-01-24 17:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:06 UTC
Labels: closed-could-not-reproduce, customer-reported
