### ISSUE TITLE
How do I make a many-to-many relation with no backwards navigation property?

### ISSUE THREAD

**Issue by midgleyc** [dotnet/efcore#25139] opened 2021-06-23 13:36 UTC
How do I make a many-to-many skip navigation relation with no backwards navigation property? My use case is that I have "user accounts" and "permissions", and a user can have many permissions, and similarly a permission can belong to many users, but the request "give all users with permission X" isn't useful inside the context of the application, so I don't want a navigation property for it.

If this was one-to-many, I could write:
```
public class PermissionConfig : IEntityTypeConfiguration<Permission>
{
    builder
        .HasOne(x => x.UserAccount)
        .WithMany()
}
```

but the `WithMany` after a `HasMany` relationship has only required parameters.

The [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.collectionnavigationbuilder-2.withmany?view=efcore-5.0) says:

> If no property is specified, the relationship will be configured without a navigation property on the other end of the relationship.

How do I do this? `WithMany()` doesn't compile. Passing null as a string gives 
>Value cannot be null. (Parameter 'inverseName')

and as an Expression 
> Object reference not set to an instance of an object.

`WithMany(x => null)` gives
> The expression 'x => null' is not a valid member access expression. The expression should represent a simple property or field access: 't => t.MyProperty'. (Parameter 'memberAccessExpression')

Are the docs right that I can do this? If so, how?

### Include provider and version information

EF Core version: 5.0.6
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 5.0
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by AndriySvyryd** [comment] 2021-06-25 19:54
Duplicate of https://github.com/dotnet/efcore/issues/3864

**Closed** 2022-10-16 19:37 UTC
Labels: customer-reported
