### ISSUE TITLE
Redundant left joins when using Include with type check

### ISSUE THREAD

**Issue by onliner10** [dotnet/efcore#24321] opened 2021-03-04 21:14 UTC
Having the entities defined as below (with lazy loading proxies enabled):
```csharp
public class A
{
    public Guid Id { get; set; }

    public virtual ICollection<C> Cs { get; set; }
}

public class B : A
{
}

public class C
{
    public Guid Id { get; set; }

    public Guid AId { get; set; }
}
```
When issuing a query
```csharp
Bs.Include(x => x.Cs)
    .Select(x => new {
       Type = (x is A) ? "A" : (x is B) ? "B" : "Other"
    })
```
Ef core 5.03 generates following SQL:
```sql
SELECT [a].[Id], [a].[Discriminator], [c].[Id], [c].[AId], [c0].[Id], [c0].[AId]
FROM [As] AS [a]
LEFT JOIN [C] AS [c] ON [a].[Id] = [c].[AId]
LEFT JOIN [C] AS [c0] ON [a].[Id] = [c0].[AId]
WHERE [a].[Discriminator] = N'B'
ORDER BY [a].[Id], [c].[Id], [c0].[Id]
GO
```

It seems to generate a left join  for each type which is type checked. Am I missing someting, or is it a bug?

This is pretty annoying, since those type checks are generated by OData in our case, so we cannot really adjust the queries :(

### Include provider and version information
EF Core version: 5.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: JetBrains Rider

**Comment by AndriySvyryd** [comment] 2021-03-05 18:15
@smitpatel to dedupe

**Comment by smitpatel** [comment] 2021-03-05 18:41
Duplicate of #24196

**Closed** 2022-10-16 19:26 UTC
Labels: customer-reported
