### ISSUE TITLE
Reopen: EF Core 5 AsSplitQuery() can not work with OData WebApi

### ISSUE THREAD

**Issue by anranruye** [dotnet/efcore#25882] opened 2021-09-06 05:55 UTC
See #23752. 

#21234 is marked as fixed.

However, we still can not use AsSplitQuery() with OData WebApi.

**Comment by stevendarby** [comment] 2021-09-06 06:55
That issue is marked as fixed in 6.0

**Comment by ajcvickers** [comment] 2021-09-06 06:56
@anranruye If this isn't working with 6.0-preview7, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by anranruye** [comment] 2021-09-06 08:54
@ajcvickers #23752 has 6.0-preview5 milestone. I can say this is not working with 6.0.0-preview5. And ef core 6.0-preview7 requires the latest net6 preview runtime. I need to update my sdk first before the test.

Should this work with 6.0-preview5? Or I have to update to 6.0-preview7?

**Comment by ajcvickers** [comment] 2021-09-06 09:05
@anranruye Theoretically it should work with preview 5. But if it doesn't, then the next step would always be to see if works on the current bits, and the closest release on NuGet to that is preview 7. If it doesn't work on preview 7, then we will investigate.

**Comment by anranruye** [comment] 2021-09-06 10:21
now this works after update to preview 7.

**Comment by roji** [comment] 2021-09-06 11:15
Duplicate of #21234

**Closed** 2022-10-16 19:45 UTC
Labels: customer-reported
