### ISSUE TITLE
Scaffold-DbContext with UseDatabaseNames options not working correctly

### ISSUE THREAD

**Issue by geetmenon** [dotnet/efcore#25503] opened 2021-08-12 19:55 UTC
I have a table whose name ends with the word Data (for e.g. EmployeeData). 
Scaffold-DbContext  -UseDatabaseNames results in Entity name EmployeeDatum which is incorrect. It should have retained the original table name (i.e. EmployeeData) for the Entity.

**Comment by ErikEJ** [comment] 2021-08-13 05:43
Are you using NoPluralize ??

**Comment by geetmenon** [comment] 2021-08-13 17:51
No, I am not using NoPluralize. But the result is the same for this Entity whether or not I use NoPlualize. It results in EmployeeDatum.

**Comment by ajcvickers** [comment] 2021-08-17 12:32
@geetmenon I am not able to reproduce this. Can you post the SQL of the table(s) you are attempting to scaffold?

My table:

```sql
CREATE TABLE [dbo].[EmployeeData](
	[Id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_EmployeeData] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
```

Command:

```
Scaffold-DbContext 'Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow' Microsoft.EntityFrameworkCore.SqlServer -UseDatabaseNames -NoPluralize
```

Scaffolded code:

```C#
namespace MyNamespace
{
    public partial class EmployeeData
    {
        public int Id { get; set; }
    }
}

namespace MyNamespace
{
    public partial class AllTogetherNowContext : DbContext
    {
        public AllTogetherNowContext()
        {
        }

        public AllTogetherNowContext(DbContextOptions<AllTogetherNowContext> options)
            : base(options)
        {
        }

        public virtual DbSet<EmployeeData> EmployeeData { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=(LocalDb)\\MSSQLLocalDB;Database=AllTogetherNow", x => x.UseNetTopologySuite());
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
```

**Comment by ajcvickers** [comment] 2021-08-24 07:48
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by geetmenon** [comment] 2021-08-24 18:32
Steps to recreate

1)  Create a new database named TestDB
2) Add the following table
CREATE TABLE [dbo].[EmployeeData](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EIN] nvarchar(20) NOT NULL,
	[Name] nvarchar(50) NOT NULL
 CONSTRAINT [PK_EmployeeData] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

3) Create a new .Net 5 class library named EntityFrameworkScaffold using VS2019. Add packages Microsoft.EntityFrameworkCore.SqlServer (5.0.9) and Microsoft.EntityFrameworkCore.Tools (5.0.9). Create a project subfolder named Model.

4) Go to Package Manager Console and run the following command:
Scaffold-DbContext -Connection "Server=cxcmv1\sql2012express; Database=TestDB; Trusted_Connection=True; MultipleActiveResultSets=true;" -Provider Microsoft.EntityFrameworkCore.SqlServer -OutputDir .\Model -Namespace MyComp.Data.Model -ContextDir. -Context CXCDbContext -ContextNamespace MyComp.Data -StartupProject MyComp.Data -UseDatabaseNames

A model named EmployeeDatum is created instead of model named EmployeeData.

**Comment by ajcvickers** [comment] 2021-08-24 18:37
@geetmenon You need to use `NoPluralize`. Otherwise this is by-design. Above you said, " But the result is the same for this Entity whether or not I use NoPlualize. It results in EmployeeDatum." So this is only a bug if you have a repro where this is happening when NoPluralize is used.

**Comment by geetmenon** [comment] 2021-08-24 18:53
Sorry I was very busy with my work. I have now updated the ticket with the
information you have requested to reproduce the issue. Please re-open this
ticket and follow-up on this.

Please let me know if you need any additional information.

Thanks
Geetha..

**Comment by ajcvickers** [comment] 2021-08-25 07:34
@geetmenon This is your step 4:

> Go to Package Manager Console and run the following command:
> Scaffold-DbContext -Connection "Server=.\sql2012express; Database=TestDB; Trusted_Connection=True; MultipleActiveResultSets=true;" -Provider Microsoft.EntityFrameworkCore.SqlServer -OutputDir .\Model -Namespace EntityFrameworkScaffold.Model -ContextDir. -Context MyDbContext -ContextNamespace EntityFrameworkScaffold -StartupProject EntityFrameworkScaffold -UseDatabaseNames

You are not passing -NoPluralize. You need to include -NoPluralize here to achieve the behavior that you want.

**Comment by geetmenon** [comment] 2021-09-16 07:10
1) Sorry I am not able to replicate the issue with NoPluralize now. My co-worker and me had run into the issue with NoPluralize. But neither of us are able to replicate this issue now. Not sure if it is because we have updated VS 2019 to a newer version. Following the behavior we see now:
 
 If tablename is singular (for e.g. User), then with NoPluralize flag:   no change(i.e. results in singular for both EntitySet name as well as Model name)
 If tablename is singular (for e.g. User), then w/o NoPluralize flag:   EntitySet name = plural of tablename= Users, and  Model name=tablename 	(i.e it changes the EntitySet name)
 
 If tablename is plural  (for e.g. EmployeeData), then with NoPluralize flag:  no change(i.e. results in plural for both EntitySet name as well as Model name)
 If tablename is plural  (for e.g. EmployeeData), then w/o NoPluralize flag:   EntitySet name =  tablename, and Model Name = singular of tablename= EmployeeDatum  	 (i.e it changes the Model name)						

 
 2) However with NoPluralize flag, we notice that the collection property within the Model gets changed to singular. For e.g. in User Model class;
 		 public virtual ICollection<UserRole> UserRole { get; set; }
 
	This I feel is a bug. It should be plural regardless of whether we use NoPluralize flag or not:
		public virtual ICollection<UserRole> UserRoles { get; set; }
 
	Let me know if I should open a separate ticket for this
 
 
 3) In EF 6, if I have a User table, a Role table and UserRole table (user can have many roles), when I had generated models from edmx (i.e. using Database first approach), I had ended up with 
	a) User Model with a collection of Roles, i.e.  public virtual ICollection<Role> Roles { get; set; }
	b) Role Model with a collection of User, i.e.	public virtual ICollection<User> Users { get; set; }
	
	However in EF Core using Scaffold-DbContext with NoPluralize flag, I end up with 
	a) User Model with a collection of Roles, i.e.  public virtual ICollection<UserRole> UserRole { get; set; }
	b) Role Model with a collection of User, i.e.	public virtual ICollection<UserRole> UserRole { get; set; }
	c) UserRole Model with a navigation property to User and another one to Role, i.e.	 public virtual Role Role { get; set; } and public virtual User User { get; set; }
	
	What is/are the parameter(s) I need to pass in Scaffold-DbContext in EF Core to get the same results as what I had got with EF 6?

**Closed** 2022-10-16 19:42 UTC
Labels: closed-could-not-reproduce, customer-reported
