### ISSUE TITLE
OwnsMany with inheritance/discriminator

### ISSUE THREAD

**Issue by UKDeveloper99** [dotnet/efcore#16194] opened 2019-06-21 15:05 UTC
I'm trying to set up an owned collection of base/child types. I feel like I'm missing something to get this working properly. I've had a look at discriminators but it doesn't seem that discriminators are exposed on ```CollectionOwnershipBuilder```. I think this behavior is handled and setup behind the scenes but I can't figure out how to get it working. Currently when I query for the aggregate object the owned collection just contains base types and from what I can infer from the inheritance docs is that all derived types need to be formally declared to the dbcontext. Either with a DbSet<T> or through the ModelBuilder for the base type.

Of course we're working with Owned types here, I can't find a way for the OwnedCollection to become aware of the derived types. I can get the relationship working for one derived type if I specify OwnsMany with the derived type in the ownedTypeName parameter. I tried adding multiple OwnsMany calls for each derived type with the same navigation property but the raises an exception. Specified cast is not valid.

```
{System.InvalidCastException: Specified cast is not valid.
  at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrPropertyGetter`2[TEntity,TValue].GetClrValue (System.Object instance) [0x00000] in <adf771f92e754fe1bb85c5850cd0c16b>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.ReadPropertyValue (Microsoft.EntityFrameworkCore.Metadata.IPropertyBase propertyBase) [0x00011] in <adf771f92e754fe1bb85c5850cd0c16b>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.get_Item (Microsoft.EntityFrameworkCore.Metadata.IPropertyBase propertyBase) [0x00010] in <adf771f92e754fe1bb85c5850cd0c16b>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.SetForeignKeyProperties (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry dependentEntry, Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry principalEntry, Microsoft.EntityFrameworkCore.Metadata.IForeignKey foreignKey, System.Boolean setModified) [0x00031] in <adf771f92e754fe1bb85c5850cd0c16b>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.FixupToDependent (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry principalEntry, Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry dependentEntry, Microsoft.EntityFrameworkCore.Metadata.IForeignKey foreignKey, System.Boolean setModified) [0x00000] in <adf771f92e754fe1bb85c5850cd0c16b>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.DelayedFixup (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry, Microsoft.EntityFrameworkCore.Metadata.INavigation navigation, Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry referencedEntry) [0x00047] in <adf771f92e754fe1bb85c5850cd0c16b>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry, System.Collections.Generic.ISet`1[T] handledForeignKeys, System.Boolean fromQuery) [0x00414] in <adf771f92e754fe1bb85c5850cd0c16b>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.StateChanged (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry, Microsoft.EntityFrameworkCore.EntityState oldState, System.Boolean fromQuery) [0x00017] in <adf771f92e754fe1bb85c5850cd0c16b>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.StateChanged (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry, Microsoft.EntityFrameworkCore.EntityState oldState, System.Boolean fromQuery) [0x00014] in <adf771f92e754fe1bb85c5850cd0c16b>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.FireStateChanged (Microsoft.EntityFrameworkCore.EntityState oldState) [0x0000b] in <adf771f92e754fe1bb85c5850cd0c16b>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState (Microsoft.EntityFrameworkCore.EntityState oldState, Microsoft.EntityFrameworkCore.EntityState newState, System.Boolean acceptChanges) [0x0023c] in <adf771f92e754fe1bb85c5850cd0c16b>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState (Microsoft.EntityFrameworkCore.EntityState entityState, System.Boolean acceptChanges, System.Nullable`1[T] forceStateWhenUnknownKey) [0x00034] in <adf771f92e754fe1bb85c5850cd0c16b>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction (Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntryGraphNode node, System.Boolean force) [0x0003f] in <adf771f92e754fe1bb85c5850cd0c16b>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState] (Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntryGraphNode node, TState state, System.Func`3[T1,T2,TResult] handleNode) [0x00000] in <adf771f92e754fe1bb85c5850cd0c16b>:0 
…
```

### Steps to reproduce

```c#
public class TrailWaypoint
{
    public int Id { get; set; }
    public string Title { get; set; }
    public double Latitude { get; set; }
    public double Longitude { get; set; }

    private readonly List<TrailStep> _trailSteps = new List<TrailStep>();
    public IReadOnlyCollection<TrailStep> TrailSteps => _trailSteps;

    public void AddTrailStep(TrailStep trailStep)
    {
        if (trailStep == null)
            throw new ArgumentException("No trail step was provided");

        _trailSteps.Add(trailStep);
    }
}

public class BaseTrailStep
{
    public enum TrailStepType
    {
        ImageText
    }

    public int Id { get; set; }
    public int TrailWaypointId { get; set; }
    public TrailStepType StepType { get; set; }
}

public class TrailStepImageText : BaseTrailStep
{
    public string Text { get; set; }
    public string ImageUrl { get; set; }
}

public class TrailStepQuestionBoxes : BaseTrailStep
{
    public string Question { get; set; }
    public string Option1 { get; set; }
    public string Option2 { get; set; }
    public string Option3 { get; set; }
    public string Option4 { get; set; }
}

public class TrailWayPointTypeConfiguration : IEntityTypeConfiguration<TrailWaypoint>
{
    public void Configure(EntityTypeBuilder<TrailWaypoint> builder)
    {
        builder
            .OwnsMany(typeof(TrailStepImageText), "TrailSteps", s =>
            {
                s.ToTable("TrailStepImageText");
                s.HasForeignKey("TrailWaypointId");
                s.Property<int>("Id");
                s.HasKey("TrailWaypointId", "Id");
                s.Property("StepType").HasConversion<string>();
            }).UsePropertyAccessMode(PropertyAccessMode.Field)
            .OwnsMany(typeof(TrailStepQuestionBoxes), "TrailSteps", s =>
            {
                s.ToTable(nameof(TrailStepQuestionBoxes));
                s.HasForeignKey("TrailWaypointId");
                s.Property<int>("Id");
                s.HasKey("TrailWaypointId", "Id");
                s.Property("StepType").HasConversion<string>();
            }).UsePropertyAccessMode(PropertyAccessMode.Field);
            
        var navigation = builder.Metadata.FindNavigation(nameof(TrailWaypoint.TrailSteps));
        navigation.SetPropertyAccessMode(PropertyAccessMode.Field);
    }
}
```

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: MacOS Mojave
Built for: Xamarin.Android
IDE: Visual Studio for Mac

**Comment by ajcvickers** [comment] 2019-06-24 17:42
@AndriySvyryd to respond.

**Comment by UKDeveloper99** [comment] 2019-06-28 15:22
@AndriySvyryd Had a chance to look at this yet? It's affecting a project I'm working on that's due for delivery soon. Thanks in advance.

**Comment by AndriySvyryd** [comment] 2019-06-28 19:38
@UKDeveloper99 This is not supported yet. An owned type cannot have any base or derived types mapped to the same navigation.

**Comment by UKDeveloper99** [comment] 2019-06-28 19:41
@AndriySvyryd ahh okay. Should I just use HasMany for now then?

**Comment by AndriySvyryd** [comment] 2019-06-28 19:41
@UKDeveloper99 Yes

Dupe of https://github.com/aspnet/EntityFrameworkCore/issues/9630

**Closed** 2022-10-16 14:26 UTC
Labels: closed-duplicate
