### ISSUE TITLE
Using multiple includes within a transaction leads to an error

### ISSUE THREAD

**Issue by PawelGerr** [dotnet/efcore#5852] opened 2016-06-24 06:41 UTC
### Steps to reproduce

Github: https://github.com/PawelGerr/EntityFrameworkCoreIssues 
Project: `MultipleIncludes`
### The issue

EF Core raises an error when using a query having 2 includes within a transaction.

Queries

```
var product = ctx.Products
    .Include(p => p.Category)
    .Include(p => p.Suppliers)
    .FirstOrDefault();

ctx.Categories.ToList(); // raises an error in Sqlite
ctx.SaveChanges();
tx.Commit(); // raises an error in MS SQL Server
```
#### Sqlite

```
System.InvalidOperationException: The transaction object is not associated with the connection object.
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MultipleIncludes.TestCase.ExecuteHavingTwoIncludes(DatabaseContext ctx) in C:\Sources\PG\EntityFrameworkCoreIssues\MultipleIncludes\TestCase.cs:line 95
   at MultipleIncludes.TestCase.ExecuteQueryWithinTransaction(Action`1 query) in C:\Sources\PG\EntityFrameworkCoreIssues\MultipleIncludes\TestCase.cs:line 57
```
#### MS SQL Server

```
System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
   at System.Data.SqlClient.SqlTransaction.ZombieCheck()
   at System.Data.SqlClient.SqlTransaction.Commit()
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Commit()
   at MultipleIncludes.TestCase.ExecuteQueryWithinTransaction(Action`1 query) in C:\Sources\PG\EntityFrameworkCoreIssues\MultipleIncludes\TestCase.cs:line 60
```
### Further technical details

EF Core version: 1.0.0-preview1-002702
Operating system: Win10-x64
Visual Studio version: VS 2015

project.json

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
    "Serilog.Extensions.Logging": "1.0.0-rc2-10110",
    "Serilog.Sinks.Literate": "2.0.0-rc-25",
    "SQLite": "3.12.2"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "portable-net45",
      "dependencies": {
        "Microsoft.EntityFrameworkCore.Tools": {
          "type": "build",
          "version": "1.0.0-preview1-final"
        },
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0-rc2-3002702"
        }
      }
    }
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [ "portable-net45" ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true
  }
}
```

**Comment by rowanmiller** [comment] 2016-06-24 18:41
@smitpatel is this something we fixed post-rc2?

**Comment by smitpatel** [comment] 2016-06-24 18:59
dupe of #5628 
Fixed in RTM release.

**Closed** 2022-10-16 09:46 UTC
