### ISSUE TITLE
CLI doesn't execute migrations when the migration folder isn't in the default place

### ISSUE THREAD

**Issue by christopherspence** [dotnet/efcore#13222] opened 2018-09-05 19:47 UTC
My coworker and I found an interesting bug in the Entity Framework CLI. If you have your migrations in a non-standard folder, and you try to update the database, it doesn't run through the migrations.

What doesn't work:

```
$ dotnet ef migrations add "Initial" --context MyProject.Data.MyDbContext -o Data\Migrations
Done. To undo this action, use 'ef migrations remove'
$ dotnet ef database update
No migrations were applied. The database is already up to date
$ 
```
However, it does work in the VS 2017 Package Manager

```
PM> Add-Migration "Initial" -o Data/Migrations
To undo this action, use Remove-Migration.
PM> Update-Database
Applying migration '20180905193318_Initial'.
Done.
```

Thanks in advance

### Further technical details
.NET Core version: 2.1.302
EF Core version: 2.1.1
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 
IDE: Visual Studio 2017 15.7.5

**Comment by ajcvickers** [comment] 2018-09-07 19:17
@christopherspence I was not able to reproduce this behavior--it may be due to something about the project/solution structure. Can you post a project/solution that reproduces what you are seeing?

```
C:\Stuff\TwoOneCore\TwoOneCore>dotnet ef migrations add "Initial" --context BloggingContext -o Data\Migrations
Done. To undo this action, use 'ef migrations remove'

C:\Stuff\TwoOneCore\TwoOneCore>dotnet ef database update
Applying migration '20180907191457_Initial'.
Done.

C:\Stuff\TwoOneCore\TwoOneCore>
```

**Comment by ajcvickers** [comment] 2018-09-17 16:45
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:29 UTC
Labels: closed-could-not-reproduce, customer-reported
