### ISSUE TITLE
Bool property with default true value, will always be saved as true

### ISSUE THREAD

**Issue by Trungkho** [dotnet/efcore#6627] opened 2016-09-28 03:17 UTC
### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.
In entity:
**public bool Active { get; set; }**

In configuration:
**modelBuilder.Entity<T>().Property(e => e.Active).HasDefaultValue(true);**
### The issue
1. I implemented a class (SeedSystemData)
2. Register it in ConfigureServices (asp.net core)
   **services.AddTransient<SeedSystemData>();**
3. Inject it in Configure method

> public void Configure(IApplicationBuilder app,
>             IHostingEnvironment env,
>             ILoggerFactory loggerFactory,
>             SeedSystemData seeder,
1. Call **seeder.EnsureSeedData().Wait();**
2. Add a new entity to DbContext with Active = false
3. await _context.SaveChangesAsync();

Result: the entity is still saved with Active = true.
### Further technical details

EF Core version: 1.0.1
Operating system: Windows 10
Visual Studio version: VS 2015, latest update

Other details about my project setup:

**Comment by ajcvickers** [comment] 2016-09-28 16:04
Dupe of #6054.

**Closed** 2022-10-16 09:59 UTC
Labels: closed-duplicate
