### ISSUE TITLE
DeleteBehaviour not set as specified

### ISSUE THREAD

**Issue by EliasDerHai** [dotnet/efcore#18064] opened 2019-09-26 12:35 UTC
### Steps to reproduce
Set OnDeleteBehaviour of my Table like this:

````
            modelBuilder.Entity<VisuPageLayerEntity>()
                        .HasMany(x => x.ControlInstances)
                        .WithOne(x => x.PageLayer)
                        .HasForeignKey(x => x.PageLayerUuid)
                        .OnDelete(DeleteBehavior.Cascade);
````

### The issue
DeleteBehaviour is set to Restrict (it does work for most other tables though)

Migration Script:
````            
migrationBuilder.CreateTable(
                name: "VisuControlInstance",
                columns: table => new
                {
                    Uuid = table.Column<Guid>(maxLength: 40, nullable: false),
                    ControlTypeUuid = table.Column<Guid>(nullable: false),
                    Order = table.Column<int>(nullable: false),
                    PageGroupUuid = table.Column<Guid>(nullable: true),
                    PageLayerUuid = table.Column<Guid>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_VisuControlInstance", x => x.Uuid);
                    table.ForeignKey(
                        name: "FK_VisuControlInstance_VisuControlType_ControlTypeUuid",
                        column: x => x.ControlTypeUuid,
                        principalTable: "VisuControlType",
                        principalColumn: "Uuid",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_VisuControlInstance_VisuPageGroup_PageGroupUuid",
                        column: x => x.PageGroupUuid,
                        principalTable: "VisuPageGroup",
                        principalColumn: "Uuid",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_VisuControlInstance_VisuPageLayer_PageLayerUuid",
                        column: x => x.PageLayerUuid,
                        principalTable: "VisuPageLayer",
                        principalColumn: "Uuid",
                        onDelete: ReferentialAction.Restrict);
                });
````

![pomelo](https://user-images.githubusercontent.com/19493409/65687613-f0f09f80-e069-11e9-9329-8507e6a2be7f.PNG)

### Further technical details
MySQL version: 8.0.13
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.20
Microsoft.AspNetCore.App version: 2.2.0

**Comment by bricelam** [comment] 2019-09-27 21:59
@EliasDerHai Are you sure nothing else in your code is changing the OnDelete behavior? Can you reproduce the issue in a new project? It may be an issue in [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql)

**Comment by ajcvickers** [comment] 2019-10-07 15:52
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:45 UTC
Labels: closed-could-not-reproduce, customer-reported
