### ISSUE TITLE
InMemory database throwing ArgumentException when using value-converted property in a query

### ISSUE THREAD

**Issue by haacked** [dotnet/efcore#30026] opened 2023-01-11 00:46 UTC
I'm attempting to upgrade from EF Core 6.0 to EF Core 7.0.2 and it breaks queries against the `InMemory` database where I query on a value converted property. This used to work. I tried to fix it by setting a `ValueComparer<T>` but that doesn't seem to fix it.

Here's a sample console app that recreates the issue.

```csharp
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

var dbContextOptions = new DbContextOptionsBuilder<MyContext>()
    .UseInMemoryDatabase("MyBugRepro")
    .ConfigureWarnings(b => b.Ignore(InMemoryEventId.TransactionIgnoredWarning))
    .Options;

await using var db = new MyContext(dbContextOptions);
db.MyEntities.Add(new MyEntity { ApiToken = SecretString.Create("secret-token")});
db.MyEntities.Add(new MyEntity { ApiToken = null });
await db.SaveChangesAsync();

// This next call throws an exception. It used to work in EF Core 6.0.
var results = await db.MyEntities.Where(e => e.ApiToken != null).ToListAsync();

Console.WriteLine(results.Count);

public class MyContext : DbContext
{
    public MyContext(DbContextOptions<MyContext> options) : base(options)
    {
    }

    public DbSet<MyEntity> MyEntities { get; set; } = null!;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var secretStringValueConverter = new SecretStringValueConverter();
        var secretStringValueComparer = new ValueComparer<SecretString>(
            (l, r) => (l == null && r == null) || (l != null && l.Equals(r)),
            v => v.GetHashCode());
        modelBuilder.SetValueConversionOnPropertiesOfType<SecretString>(
            secretStringValueConverter,
            secretStringValueComparer);
    }

    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        // This tells EF that all properties of type SecretString should be converted to a string and not
        // treated like a navigation property. We can't specify the SecureStringValueConverter here because
        // EF does not use DI to create instances of the converters and this method doesn't allow us to
        // pass in a converter.
        configurationBuilder.Properties<SecretString>().HaveConversion<string>();
    }
}

public class MyEntity
{
    public int Id { get; set; }

    public SecretString? ApiToken { get; init; }
}

public class SecretString : IEquatable<SecretString>
{
    public string ProtectedValue { get; }

    public SecretString(string dbValue)
    {
        ProtectedValue = dbValue;
    }

    public string Reveal()
    {
        return ProtectedValue[7..].Reverse() + "";
    }

    public static SecretString Create(string clearTextValue)
    {
        // Don't worry, the actual code does something more secure than this. This is just for demo purposes.
        return new SecretString("prefix:" + clearTextValue.Reverse());
    }

    public bool Equals(SecretString? other) => other is not null && string.Equals(ProtectedValue, other.ProtectedValue, StringComparison.Ordinal);
    public override bool Equals(object? obj) => obj is SecretString other && Equals(other);
    public override int GetHashCode() => ProtectedValue?.GetHashCode(StringComparison.Ordinal) ?? 0;
}

public class SecretStringValueConverter : ValueConverter<SecretString, string>
{
    public SecretStringValueConverter()
        : base(
            secret => secret.ProtectedValue,
            storedValue => new SecretString(storedValue))
    {
    }
}

public static class ModelBuilderExtensions
{
    public static void SetValueConversionOnPropertiesOfType<TClrType>(
        this ModelBuilder builder,
        ValueConverter valueConverter,
        ValueComparer valueComparer)
    {
        foreach (var entityType in builder.Model.GetEntityTypes())
        {
            foreach (var property in entityType.GetProperties())
            {
                if (property.ClrType == typeof(TClrType))
                {
                    property.SetValueConverter(valueConverter);
                    property.SetValueComparer(valueComparer);
                }
            }
        }
    }
}
```

And here's the full exception message:

```
Unhandled exception. System.ArgumentException: Expression of type 'System.Object' cannot be used for constructor parameter of type 'System.String' (Parameter 'arguments[0]')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Dynamic.Utils.ExpressionUtils.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments, String methodParamName)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at System.Linq.Expressions.NewExpression.Update(IEnumerable`1 arguments)
   at Microsoft.EntityFrameworkCore.Query.ReplacingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ReplacingExpressionVisitor.Replace(Expression original, Expression replacement, Expression tree)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryExpressionTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryExpressionTranslatingExpressionVisitor.TranslateInternal(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryExpressionTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateExpression(Expression expression, Boolean preserveType)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateLambdaExpression(ShapedQueryExpression shapedQueryExpression, LambdaExpression lambdaExpression, Boolean preserveType)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in /Users/haacked/dev/exp/EfBugRepro/Program.cs:line 16
   at Program.<Main>$(String[] args) in /Users/haacked/dev/exp/EfBugRepro/Program.cs:line 17
   at Program.<Main>(String[] args)
```

### Include provider and version information

EF Core version: 7.0.2
Database provider: (e.g. Microsoft.EntityFrameworkCore.InMemory)
Target framework: (e.g. .NET 7.0): .NET 7.0
Operating system: Apple M1 Max Ventura 13.1

**Comment by ajcvickers** [comment] 2023-01-12 21:18
Duplicate of #29603. Verified fixed in daily build.

**Closed** 2023-01-18 20:19 UTC
Labels: closed-duplicate, customer-reported
