### ISSUE TITLE
Invalid host name isn't returning any error number for SqlException for .net core 2 in Linux

### ISSUE THREAD

**Issue by jaydeept** [dotnet/efcore#10160] opened 2017-10-25 20:05 UTC
I am having a negative integration test case in .net core 2 based project where I am providing invalid host name to connect to SQL server database. I am expecting that the error number should be returned as 53 for that (I am having some logic around error number). While executing test case in Windows, it's throwing proper error code i.e. 53 but in Linux it's not throwing any error number though returning SqlException.

The error I am receiving in Windows is:

> A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found

In Linux:

> A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.AggregateException: One or more errors occurred.

Any help will be appreciated.

P.S. I tried to search error number [here](https://technet.microsoft.com/en-us/library/cc645612(v=sql.105).aspx) but didn't get any help.

**Comment by smitpatel** [comment] 2017-10-25 20:21
Duplicate of # https://github.com/dotnet/corefx/issues/12472

**Closed** 2022-10-16 11:55 UTC
Labels: closed-external
