### ISSUE TITLE
EF Core 2.1.2 and .net core 2.0 - Linq2Entities causes 'must be reducible node' error

### ISSUE THREAD

**Issue by normantimorehl** [dotnet/efcore#12721] opened 2018-07-19 11:56 UTC
Dear EF Core team,

I encountered the error above in the title. I already asked the same question in stackoverflow, so please don't be angry with me, if I link the question here:
https://stackoverflow.com/questions/51379659/ef-core-2-1-2-and-net-core-2-0-linq2entities-causes-must-be-reducible-node

>> Describe what is not working as expected.

I upgraded EF Core 1.x to 2.1.2 and the same query (which worked in 1.x) does not work anymore.

>> If you are seeing an exception, include the full exceptions details (message and stack trace).

```
_Exception message:_ 'must be reducible node' error
_Stack trace:_ at System.Linq.Expressions.Expression.ReduceAndCheck() at System.Linq.Expressions.Expression.ReduceExtensions() at System.Linq.Expressions.Compiler.StackSpiller.RewriteExtensionExpression(Expression expr, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberExpression(Expression expr, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberExpression(Expression expr, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression) at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions) at System.Linq.Expressions.Compiler.StackSpiller.RewriteNewExpression(Expression expr, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression) at System.Linq.Expressions.Compiler.StackSpiller.RewriteBinaryExpression(Expression expr, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression1 lambda)
     at System.Linq.Expressions.Expression1.Accept(StackSpiller spiller) at System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr) at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression) at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions) at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression) at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions) at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression) at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions) at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack) at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression1 lambda)
     at System.Linq.Expressions.Expression1.Accept(StackSpiller spiller) at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda) at System.Linq.Expressions.Expression1.Compile(Boolean preferInterpretation)
     at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
     at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger1 logger, Type contextType) at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_01.<Execute>b__0()
     at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func1 compiler) at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) at Remotion.Linq.QueryableBase`1.System.Collections.IEnumerable.GetEnumerator() at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType) at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType) at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer) at My.api.MyController.MyServiceMethod(Guid projectId, DateTime fromDate, DateTime toDate) in C:\Sources[...]MyController.cs:line 347
```

### Steps to reproduce
>> Include a complete code listing (or project/solution) that we can run to reproduce the issue.

I'm sorry, but in my case the company does not allow to include the exact source code. But I can give you following information:

>> Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
    // this query works...
var projectEfforts = from projectEntry in _context.ProjectTrackingEntry
                     where projectEntry.ProjectId == projectId
                     group projectEntry by new { projectEntry.Day.Year, projectEntry.Day.Month } into g
                     select new
                     {
                         PeDate = new DateTime(g.Key.Year, g.Key.Month, 1),
                         Month = g.Key,
                         MonthlyWorkingHours = g.Sum(x => x.WorkingHours)
                     };

// and here the query is executed with a valid result
string jsonprojectEfforts = Newtonsoft.Json.JsonConvert.SerializeObject(projectEfforts);

// following Linq will produce an error
var effHours = from projectEffort in projectEfforts
               where (projectEffort.PeDate < fromDate)
               select projectEffort.MonthlyWorkingHours;

// work with the result above will cause the 'must be reducible node' error
string jsoneffHours = Newtonsoft.Json.JsonConvert.SerializeObject(effHours);
```

For better understanding here is the result of the first Linq operation (in JSON):
`[{"PeDate":"2017-01-01T00:00:00","Month":{"Year":2017,"Month":1},"MonthlyWorkingHours":128.00} ,{"PeDate":"2018-01-01T00:00:00","Month":{"Year":2018,"Month":1},"MonthlyWorkingHours":40.00} ,{"PeDate":"2017-02-01T00:00:00","Month":{"Year":2017,"Month":2},"MonthlyWorkingHours":80.00} ,{"PeDate":"2017-03-01T00:00:00","Month":{"Year":2017,"Month":3},"MonthlyWorkingHours":88.00} ,{"PeDate":"2018-03-01T00:00:00","Month":{"Year":2018,"Month":3},"MonthlyWorkingHours":64.00} ,{"PeDate":"2017-04-01T00:00:00","Month":{"Year":2017,"Month":4},"MonthlyWorkingHours":104.00} ,{"PeDate":"2018-04-01T00:00:00","Month":{"Year":2018,"Month":4},"MonthlyWorkingHours":76.00} ,{"PeDate":"2017-05-01T00:00:00","Month":{"Year":2017,"Month":5},"MonthlyWorkingHours":16.00} ,{"PeDate":"2018-05-01T00:00:00","Month":{"Year":2018,"Month":5},"MonthlyWorkingHours":24.00} ,{"PeDate":"2017-06-01T00:00:00","Month":{"Year":2017,"Month":6},"MonthlyWorkingHours":60.00} ,{"PeDate":"2018-06-01T00:00:00","Month":{"Year":2018,"Month":6},"MonthlyWorkingHours":24.00} ,{"PeDate":"2017-07-01T00:00:00","Month":{"Year":2017,"Month":7},"MonthlyWorkingHours":48.00} ,{"PeDate":"2018-07-01T00:00:00","Month":{"Year":2018,"Month":7},"MonthlyWorkingHours":80.00} ,{"PeDate":"2017-08-01T00:00:00","Month":{"Year":2017,"Month":8},"MonthlyWorkingHours":104.00} ,{"PeDate":"2017-09-01T00:00:00","Month":{"Year":2017,"Month":9},"MonthlyWorkingHours":48.00} ,{"PeDate":"2017-10-01T00:00:00","Month":{"Year":2017,"Month":10},"MonthlyWorkingHours":72.00} ,{"PeDate":"2017-12-01T00:00:00","Month":{"Year":2017,"Month":12},"MonthlyWorkingHours":213.75}]`

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows Server 2012 R2
IDE: Visual Studio 2017 15.7.5

Please let me know, if more infomration is needed.

Thanks a lot,
Timo

**Comment by ShiftySituation** [comment] 2018-07-30 16:21
I'm having the same issue.  It is Sum that is causing the issue.  My query isn't much different than the example.

**Comment by normantimorehl** [comment] 2018-08-10 05:33
@ajcvickers As I mentioned before: I am not allowed to post our source code in public. But I have the GO to post the dependent table and model code:

```
CREATE TABLE [dbo].[ProjectTrackingEntry](
	[TimeTrackingId] [uniqueidentifier] NOT NULL,
	[Day] [date] NOT NULL,
	[ProjectId] [uniqueidentifier] NOT NULL,
	[Description] [nvarchar](256) NULL,
	[IsHomeOffice] [bit] NOT NULL,
	[WorkingHours] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_ProjectTrackingEntry] PRIMARY KEY CLUSTERED 
(
	[TimeTrackingId] ASC,
	[Day] ASC,
	[ProjectId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
```
there are 3 additionally FK check constraints, but these are not necessary to produce the error.

And here is the relevant model code:
```
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace eneromIT.Webportal.Models
{
    public class ProjectTrackingEntry
    {
        [Required]
        public Guid TimeTrackingId { get; set; }
        [JsonIgnore]
        public TimeTracking TimeTracking { get; set; }

        [Column(TypeName = "date"), Required]
        public DateTime Day { get; set; }

        [JsonIgnore]
        public TimeTrackingEntry TimeTrackingEntry { get; set; }

        [Required]
        public Guid ProjectId { get; set; }
        [JsonIgnore]
        public Project Project { get; set; }

        public decimal? WorkingHours { get; set; }

        [MaxLength(256)]
        public string Description { get; set; }

        public bool IsHomeOffice { get; set; } = false;
    }
}
```

With the information in my first post you should be able to reproduce the error (I assume).

Kind regards
Timo

**Comment by maumar** [comment] 2018-08-10 22:03
possibly related to https://github.com/aspnet/EntityFrameworkCore/issues/12799

**Comment by smitpatel** [comment] 2019-12-07 00:33
Above query has `new DateTime` in projection after `GroupBy` operator which is client projection. Where predicate after client projection does not translate to server starting 3.0 so above query is not supported.
See issue #15283 about adding a functionality similar to `new DateTime` on server side. Once that is implemented and used in above query, we believe it would be translated correctly.

Closing as by design.

**Closed** 2022-10-16 13:20 UTC
Labels: closed-by-design, customer-reported, area-query
