### ISSUE TITLE
Duplication in results for a self-referencing object

### ISSUE THREAD

**Issue by hapartnerships** [dotnet/efcore#23102] opened 2020-10-26 22:04 UTC
I have an object which is self referencing:

```
    public class ProjectPlanItem
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public Guid Reference { get; set; } = Guid.NewGuid();
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime BaselineStartDate { get; set; }
        public DateTime BaselineEndDate { get; set; }
        public int Duration { get; set; }
        public string DurationUnit { get; set; }
        public int Progress { get; set; }
        public string Predecessor { get; set; }
        public bool IsSubItem { get; set; }
        public virtual ICollection<ProjectPlanItem> ProjectPlanSubItems { get; set; } = new  List<ProjectPlanItem>();
    }
```
This object gets loaded into a collection on a parent object:

```
    public class ProjectPlan
    {
        [Key]
        public int ID { get; set; }
        public Guid Reference { get; set; } = Guid.NewGuid();
        public string Name { get; set; }
        public string Version { get; set; }
        public DateTime VersionDate { get; set; }
        public ProjectPlanStatus Status { get; set; }
        public string WorkWeek { get; set; }
        public ICollection<ProjectPlanItem> ProjectPlanItems { get; set; } = new List<ProjectPlanItem>();
        public ICollection<ProjectPlanEventMarker> ProjectPlanEvents { get; set; } = new List<ProjectPlanEventMarker>();
        public ICollection<ProjectPlanResource> ProjectPlanResources { get; set; } = new List<ProjectPlanResource>();
        public ICollection<ProjectPlanHoliday> ProjectPlanHolidays { get; set; } = new List<ProjectPlanHoliday>();
    }
```

the DbContext is very simple just containing:

```
        public DbSet<ProjectPlan> ProjectPlans { get; set; }
        public DbSet<ProjectPlanItem> ProjectPlanItems { get; set; }
        public DbSet<ProjectPlanEventMarker> ProjectPlanEventMarkers { get; set; }
        public DbSet<ProjectPlanHoliday> ProjectPlanHolidays { get; set; }
        public DbSet<ProjectPlanResource> ProjectPlanResources { get; set; }
```
Using efcore update-database the database is created appropriately with FKs created in the correct places for the 1-many relaitonships.

I have amended slightly the Controller, created routinely using add > controller > API Controller with actions using Entity Framework selecting the ProjectPlan type and DbContext, for eager loading as follows:

```
 public async Task<ActionResult<ProjectPlan>> GetProjectPlan(int id)
        {
            var projectPlan = await _context.ProjectPlans
                .Where(p=> p.ID==id)
                .Include(p => p.ProjectPlanEvents)
                .Include(p => p.ProjectPlanHolidays)
                .Include(p => p.ProjectPlanResources)
                .Include(p => p.ProjectPlanItems)
                .ThenInclude(pi => pi.ProjectPlanSubItems)
                .FirstOrDefaultAsync();

            if (projectPlan == null)
            {
                return NotFound();
            }

            return projectPlan;
        }
```

The resulting output of GET: api/ProjectPlans/{id} duplicates the nested ProjectPlanItems on the root as per the below:

- Group 1
    - Group 1 Item 1
    - Group 1 Item 2
- Group 1 Item 1
- Group 1 Item 2
- Group 2
    - Group 2 Item 1
    - Group 2 Item 2
- Group 2 Item 1
- Group 2 Item 2

Rather then the expected:

- Group 1
    - Group 1 Item 1
    - Group 1 Item 2
- Group 2
    - Group 2 Item 1
    - Group 2 Item 2

**Comment by ajcvickers** [comment] 2020-10-29 17:57
@hapartnerships I have not been able to reproduce this--see my code below. Please attach a small, runnable project or post a small, runnable code listing, like below, that reproduces what you are seeing so that we can investigate.

```C#
public class ProjectPlanItem
{
    [Key]
    public int Id { get; set; }
    public string Name { get; set; }
    public Guid Reference { get; set; } = Guid.NewGuid();
    public DateTime StartDate { get; set; }
    public DateTime EndDate { get; set; }
    public DateTime BaselineStartDate { get; set; }
    public DateTime BaselineEndDate { get; set; }
    public int Duration { get; set; }
    public string DurationUnit { get; set; }
    public int Progress { get; set; }
    public string Predecessor { get; set; }
    public bool IsSubItem { get; set; }
    public virtual ICollection<ProjectPlanItem> ProjectPlanSubItems { get; set; } = new  List<ProjectPlanItem>();
}

public class ProjectPlan
{
    [Key]
    public int ID { get; set; }
    public Guid Reference { get; set; } = Guid.NewGuid();
    public string Name { get; set; }
    public string Version { get; set; }
    public DateTime VersionDate { get; set; }
    // public ProjectPlanStatus Status { get; set; }
    public string WorkWeek { get; set; }
    public ICollection<ProjectPlanItem> ProjectPlanItems { get; set; } = new List<ProjectPlanItem>();
    // public ICollection<ProjectPlanEventMarker> ProjectPlanEvents { get; set; } = new List<ProjectPlanEventMarker>();
    // public ICollection<ProjectPlanResource> ProjectPlanResources { get; set; } = new List<ProjectPlanResource>();
    // public ICollection<ProjectPlanHoliday> ProjectPlanHolidays { get; set; } = new List<ProjectPlanHoliday>();
}

public class Program
{
    public static void Main()
    {
        using (var context = new BlogContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new ProjectPlan
            {
                ProjectPlanItems = new List<ProjectPlanItem>
                {
                    new ProjectPlanItem
                    {
                        ProjectPlanSubItems = new List<ProjectPlanItem>
                        {
                            new ProjectPlanItem(),
                            new ProjectPlanItem(),
                        }
                    },
                    new ProjectPlanItem()
                    {
                        ProjectPlanSubItems = new List<ProjectPlanItem>
                        {
                            new ProjectPlanItem(),
                            new ProjectPlanItem(),
                        }
                    }
                }
            });

            context.SaveChanges();
        }

        using (var context = new BlogContext())
        {
            var id = 1;
            var projectPlan = context.ProjectPlans
                .Where(p => p.ID == id)
                // .Include(p => p.ProjectPlanEvents)
                // .Include(p => p.ProjectPlanHolidays)
                // .Include(p => p.ProjectPlanResources)
                .Include(p => p.ProjectPlanItems)
                .ThenInclude(pi => pi.ProjectPlanSubItems)
                .FirstOrDefault();

            Console.WriteLine($"ProjectPlan {projectPlan.ID}");
            foreach (var planItem in projectPlan.ProjectPlanItems)
            {
                Console.WriteLine($"  ProjectPlanItem {planItem.Id }");
                foreach (var subItem in planItem.ProjectPlanSubItems)
                {
                    Console.WriteLine($"    ProjectPlanSubItem {subItem.Id }");
                }
            }
        }
    }
}

public class BlogContext : DbContext
{
    public DbSet<ProjectPlan> ProjectPlans { get; set; }
    public DbSet<ProjectPlanItem> ProjectPlanItems { get; set; }
    // public DbSet<ProjectPlanEventMarker> ProjectPlanEventMarkers { get; set; }
    // public DbSet<ProjectPlanHoliday> ProjectPlanHolidays { get; set; }
    // public DbSet<ProjectPlanResource> ProjectPlanResources { get; set; }

    private static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().SetMinimumLevel(LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);
}
```

Output:
```
ProjectPlan 1
  ProjectPlanItem 1
    ProjectPlanSubItem 3
    ProjectPlanSubItem 4
  ProjectPlanItem 2
    ProjectPlanSubItem 5
    ProjectPlanSubItem 6
```

**Comment by ajcvickers** [comment] 2020-11-09 15:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:06 UTC
Labels: closed-could-not-reproduce, customer-reported
