### ISSUE TITLE
Error - Cannot resolve the collation conflict between "Latin1_General_CI_AI" and "Latin1_General_CS_AS" in the equal to operation.

### ISSUE THREAD

**Issue by gabrieldss** [dotnet/efcore#27601] opened 2022-03-09 12:59 UTC
I am doing a insert operation and shows this error:
![image](https://user-images.githubusercontent.com/33532210/157300400-7e07f29b-b89d-4906-9442-ed08abe119ba.png)

The insert does a inner join with my table when there are many inserts to optimize i believe, but my database is configured right with CS_AS an my project too.
![image](https://user-images.githubusercontent.com/33532210/157301308-abb88f78-e4f9-49e6-8aca-69107c2d0626.png)

My configuration:
![image](https://user-images.githubusercontent.com/33532210/157301585-5515f451-b30d-4057-a6f8-bbeee89e40a7.png)

My query with error:
[sql_select_collate.txt](https://github.com/dotnet/ef6/files/8208722/sql_select_collate.txt)

When i used this old configuration haven't error:
![image](https://user-images.githubusercontent.com/33532210/157302014-844727d8-ee73-4db9-ad3e-e32d24a12627.png)

I did the update for this version and show the error too:
![image](https://user-images.githubusercontent.com/33532210/157302427-3322c64c-4440-4899-8cbf-7996dd340b1b.png)

I used the declaration different, equals this example and show the error too:
![image](https://user-images.githubusercontent.com/33532210/157302561-1c6588d0-95e7-4bc2-a4fc-cd1812f85109.png)

I believe be a bug in this version...

Exception message:
Cannot resolve the collation conflict between "Latin1_General_CI_AI" and "Latin1_General_CS_AS" in the equal to operation.

### Steps to reproduce
Doing a insertion with a list with three or more elements...
![image](https://user-images.githubusercontent.com/33532210/157303504-14978a05-33a4-4908-9e3d-198a9b8d54dc.png)

### Further technical details
EF version: i send a image with this configurations
Database Provider: Microsoft SQL Server Management Studio 18 / "Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.2" / SQL Server 2019.
Operating system:  Windows 10.
IDE: 
![image](https://user-images.githubusercontent.com/33532210/157303914-7b43f8ed-c84c-46fd-9b3b-f7d1db82b497.png)

**Comment by roji** [comment] 2022-03-09 14:01
This error generally occurs when you try to compare two columns which have incompatible collations; review which different collations you're using in the database, and where you're comparing columns with different collations.

If you need further assistance, please create a minimal, runnable code sample, which reproduces the error without any extra code; the above fragments are not enough to know exactly what you're doing.

**Comment by ajcvickers** [comment] 2022-03-22 13:34
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:28 UTC
Labels: closed-could-not-reproduce, customer-reported
