### ISSUE TITLE
Migration is not  being applied to db

### ISSUE THREAD

**Issue by dvdobrovolskiy** [dotnet/efcore#7456] opened 2017-01-23 19:42 UTC
Project has  single migration - Initial.  Applied to db and single record in  __EFMigrationsHistory.

Next I add new migration and try to apply it to db.  update-database say done but I have exception like
```html
<span>SqlException: Invalid object name &#x27;Files&#x27;.</span>
h2>Applying existing migrations for ApplicationDbContext may resolve this issue</h2>
            <p>There are migrations for ApplicationDbContext that have not been applied to the database</p>
            <ul>
                    <li>20170122215933_files</li>
            </ul>
```
and no record added to __EFMigrationsHistory.

also then I try remove-migration I got message that migration Initial is applied to db and cannot be undone (then is should be second migration named "file")

In package management console it looks like  this
PM> add-migration  file
To undo this action, use Remove-Migration.
PM> update-database
Done.
PM> remove-migration
The migration '20170122010641_Initial' has already been applied to the database. Unapply it and try again. If the migration has been applied to other databases, consider reverting its changes using a new migration.

**Update** dotnet ef database  update  from console did apply migration

**Comment by bricelam** [comment] 2017-01-23 22:16
What version of the `Microsoft.EntityFrameworkCore.Tools` package were you using? What is the output of the command with `-Verbose`?

**Comment by rowanmiller** [comment] 2017-01-31 19:16
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by dvdobrovolskiy** [comment] 2017-01-31 19:35
1.1.0-preview4-final

PM> add-migration comm2 -Verbose
Build started...
Build succeeded.
Setting app base path c:\Users\dima\Source\Repos\CET\src\CET\bin\Debug\netcoreapp1.0
Finding DbContext classes...
Using context 'ApplicationDbContext'.
Writing migration to 'c:\Users\dima\Source\Repos\CET\src\CET\Migrations\20170131193152_comm2.cs'.
Writing model snapshot to 'c:\Users\dima\Source\Repos\CET\src\CET\Migrations\ApplicationDbContextModelSnapshot.cs'.
To undo this action, use Remove-Migration.

PM> update-database -Verbose
Build started...
Build succeeded.
Setting app base path c:\Users\dima\Source\Repos\CET\src\CET\bin\Debug\netcoreapp1.0
Finding DbContext classes...
Using context 'ApplicationDbContext'.
Done.
Build started...
Build succeeded.
Setting app base path c:\Users\dima\Source\Repos\CET\src\CET\bin\Debug\netcoreapp1.0
Finding DbContext classes...
Using context 'ApplicationDbContext'.
Done.

and nothing happened.  Just added new field to one of classes
Was
`    public class StudyHistory
    {
        public int Id { get; set; }

        public Person Student { get; set; }

        public Person Teacher { get; set; }

        public Level Level { get; set; }

        public Term Term { get; set; }
    }`
become
`    public class StudyHistory
    {
        public int Id { get; set; }

        public Person Student { get; set; }

        public Person Teacher { get; set; }

        public Level Level { get; set; }

        public Term Term { get; set; }

        public string Comment { get; set; }
    }`

add-migration create empty migration. 
ef dotnet migrations add
creates normal migration with new field
 protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Comment",
                table: "StudyHistories",
                nullable: true);
        }

**Comment by divega** [comment] 2017-01-31 19:40
@dvdobrovolskiy as your intention to reopen the issue to consider the additional information?

**Comment by dvdobrovolskiy** [comment] 2017-01-31 19:49
It is an issue for me.

**Comment by rowanmiller** [comment] 2017-02-01 19:39
@dvdobrovolskiy can you provide the project so that we can debug the issue?

**Comment by dvdobrovolskiy** [comment] 2017-02-02 11:49
Sure

https://1drv.ms/u/s!AvdtTGXIWO4bicV9o8lUgutbBX57aw

just added new field to StudyHistory and 
PM> add-migration comment2
gives me empty migration

dotnet ef migrations add comment3
from cmd executed straight after generates normal migration with new field

**Comment by bricelam** [comment] 2017-03-31 16:19
After upgrading your project to the RTM version of the tooling, I'm unable to reproduce this issue.

**Closed** 2022-10-16 10:50 UTC
Labels: closed-could-not-reproduce
