### ISSUE TITLE
Dynamic Where expression after projection causes translation failure when referencing a property of the DTO's base type

### ISSUE THREAD

**Issue by csboling** [dotnet/efcore#12481] opened 2018-06-27 17:19 UTC
### Steps to reproduce
[Here](https://github.com/csboling/ef-core-dynamic-where-issue) is a repo with a reproduction and a demonstration of some similar usages where translation succeeds.

A query with a Where clause after projection, such as
``` C#
class SimpleDto
{
    public int Pk { get; set; }
}

dbContext.Set<Book>()
    .Select(book => new SimpleDto { Pk = book.Id })
    .Where(x => x.Pk == 1)
    .ToList();
```
correctly translates to SQL. This also works if the body of the Where clause is an expression built at runtime:
``` C#
var parameter = Expression.Parameter(typeof(SimpleDto), "x");
var propertyExpression = Expression.Property(parameter, "Pk");
var constant = Expression.Constant(1);
var body = Expression.Equal(propertyExpression, constant);
var lambda = Expression.Lambda<Func<SimpleDto, bool>>(body, parameter);

dbContext.Set<Book>()
    .Select(book => new SimpleDto { Pk = book.Id })
    .Where(lambda)
    .ToList();
```

as long as the `Pk` property is actually defined on the `SimpleDto` projection target class. However, if the destination DTO derives the `Pk` property from a base class:
``` C#
class BaseDto
{
    public int Pk { get; set; }
}

class DerivedDto : BaseDto
{
}

var parameter = Expression.Parameter(typeof(DerivedDto), "x");
var propertyExpression = Expression.Property(parameter, "Pk");
var constant = Expression.Constant(1);
var body = Expression.Equal(propertyExpression, constant);
var lambda = Expression.Lambda<Func<DerivedDto, bool>>(body, parameter);

dbContext.Set<Book>()
    .Select(book => new DerivedDto { Pk = book.Id })
    .Where(lambda)
    .ToList();
```
then translation will fail when using a dynamic expression, but not for a compile-time expression.
```
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'where (new DerivedDto() {Pk = [derived].Id}.Pk == 1)' could not be translated and will be evaluated locally.
```

### Further technical details
EF Core version: 2.1.1. I couldn't get the MyGet nightly package to install.
Database Provider: Microsoft.EntityFrameworkCore.Sqlite 2.1.1 in the linked example. Originally discovered while using [Pomelo.EntityFrameworkCore.MySql](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) 2.1.0-rc1.
Operating system: Windows 10.0.16299
IDE: .NET Core SDK 2.1.300-preview2-008533

**Comment by ajcvickers** [comment] 2018-06-28 16:44
@csboling The difference is that the PropertyInfo generated by the compiler has a [ReflectedType](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.reflectedtype?view=netframework-4.7.1) indicating it was obtained from `BaseDto`. To get the same in the manually built expression tree you need to explicitly get the PropertyInfo instead of just passing the string name:

```C#
var propertyExpression = Expression.Property(parameter, typeof(BaseDto).GetProperty("Pk"));
```

**Comment by smitpatel** [comment] 2018-06-28 17:00
Duplicate of #12230

**Comment by csboling** [comment] 2018-06-28 17:29
Excellent, I figured I had to be missing something simple, but the expressions appearing to be the same got me thinking it was translation related. Thanks!

**Comment by csboling** [comment] 2018-07-06 22:33
I played with this some more and looked at the [upstream re-linq issue](https://www.re-motion.org/jira/browse/RMLNQ-121) and I don't think the `Expression.Property(ParameterExpression, PropertyInfo)` overload is right. The problem is that the `ParameterExpression` needs to be constructed with the declaring type of the member you are accessing, i.e. the `DeclaringType` of the `PropertyInfo`. So
```
var propertyInfo = typeof(T).GetProperty("Pk");
var parameter = Expression.Parameter(propertyInfo.DeclaringType);
var propertyExpression = Expression.Property(parameter, "Pk");
```
will translate fine. However, `Expression.Property(parameter, propertyInfo)` still fails to translate when the `parameter` was built this way. I have updated the repo to show this case of translation failure.

**Comment by progmars** [comment] 2019-08-07 09:15
I have a very similar issue caused by generic method as an expression source and then trying to apply it on a projected (Select()) queryable:



```

public interface ISomeable
{
    string Some { get; set; }
}

public static Expression<Func<T, bool>> GetCriteria<T>() where T : class, ISomeable
{  return e => (e.Some == "Hello"); }

...


Expression<Func<MySimpleEntity, bool>> someCriteria = e => (e.Some == "Hello");
Expression<Func<MySimpleEntity, bool>> someCriteria2 = GetCriteria<MySimpleEntity>();

var query = db.Entities
       .Select(s => new MySimpleEntity { Id = s.Id, Some = s.Some });
// if this Select is removed and MySimpleEntity in both expressions replaced with MyFullEntity, 
// the issue disappears

// this succeeds
// var filteredQueryResults = query.Where(someCriteria).ToList();

// this fails: why is it evaluated locally and not in SQL? <-------------------------------
var filteredQueryResults = filteredQueryResults = query.Where(someCriteria2).ToList();
// someCriteria2 is set to the same e => (e.Some == "Hello");
// debugger shows that both someCriteria and someCriteria2 are essentially the same,
// however, Linq somehow knows about generic roots of someCriteria2 and treats it differently

/*
 * 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: 
 * The LINQ expression 'where (new MySimpleEntity() {Id = [s].Id, Some = [s].Some}.Some == "Hello")' 
 * could not be translated and will be evaluated locally.'. 
 */
```

Here's my Gist of a minimal application:

https://gist.github.com/progmars/eeec32a533dbd2e1f85e551db1bc53f8

Is there any workaround (casting, traversing the expression to replace types etc. etc.) to make it work for `someCriteria2`?

**Comment by progmars** [comment] 2019-08-07 11:34
Found a somewhat dirty solution in some other issue:
https://github.com/aspnet/EntityFrameworkCore/issues/14118#issuecomment-519057279

**Closed** 2022-10-16 13:16 UTC
Labels: closed-duplicate, customer-reported
