### ISSUE TITLE
Sometimes SelectExpressions are pushed down unnecessarily

### ISSUE THREAD

**Issue by tuespetre** [dotnet/efcore#7766] opened 2017-03-02 16:26 UTC
There are many cases where, for one reason or another, `LiftSubQuery` will push a `SelectExpression` down into a subquery even though it is not required.

Some examples:

- It's being pushed down in the `MainFromClause` even though there are no `JoinClause`s, `GroupJoinClause`s, or `AdditionalFromClause`s
- It's being pushed down in a `JoinClause`, a `GroupJoinClause`, or an `AdditionalFromClause` even though the query will not be able to be flattened

**Comment by tuespetre** [comment] 2017-03-11 20:23
This was largely resolved by #7843 and will be handled when #7831 is addressed (the third point about inheriting from SubQueryFromClauseFlattenrr, to be specific) 

cc @smitpatel

**Comment by divega** [comment] 2017-05-08 22:10
@maumar @smitpatel @anpete should this issue be marked as closed-fixed as per the comment above? Or is it a duplicate?

**Comment by smitpatel** [comment] 2017-05-08 22:17
dupe of #8094

**Closed** 2022-10-16 10:55 UTC
Labels: type-bug, closed-duplicate
