### ISSUE TITLE
Use value object with multiple property as primary key

### ISSUE THREAD

**Issue by hadijahangiri** [dotnet/efcore#25329] opened 2021-07-25 10:45 UTC
```C#
 public class CustomerId : ValueObject<CustomerId>
    {
        public string Code { get; private set; }
        public int Number { get; private set; }
        public CustomerId(string code, int number)
        {
            this.Code = code;
            this.Number = number;
        }
    } 
     public class Customer : Entity<CustomerId>
    {
        private readonly List<Address> _addresses;
        private readonly List<PhoneNumber> _phoneNumbers;
        public FullName FullName { get; private set; }
        public NationalId NationalId { get; private set; }
        public IReadOnlyCollection<Address> Addresses => _addresses.AsReadOnly();
        public IReadOnlyCollection<PhoneNumber> PhoneNumbers => _phoneNumbers.AsReadOnly();

        public Customer(): base(null){}
        public Customer(CustomerId id, FullName fullName, NationalId nationalId, List<Address> addresses  , List<PhoneNumber> phoneNumbers)
            : base(id)
        {
            this.FullName = fullName;
            this.NationalId = nationalId;
            if(addresses == null)
                addresses = new List<Address>();
            _addresses = addresses;
            if (phoneNumbers == null)
                phoneNumbers = new List<PhoneNumber>();
            _phoneNumbers = phoneNumbers;
        }

        public void AddAddress(Address address)
        {
            _addresses.Add(address);
        }

        public void AddPhoneNumber(PhoneNumber phoneNumber)
        {
            _phoneNumbers.Add(phoneNumber);
        }
    }
```

I wabt use customerId as a primary key

**Comment by bricelam** [comment] 2021-07-27 16:55
Related to #4835

**Comment by AndriySvyryd** [comment] 2021-07-27 21:51
Duplicate of https://github.com/dotnet/efcore/issues/13947

**Closed** 2022-10-16 19:40 UTC
Labels: closed-duplicate, customer-reported
