### ISSUE TITLE
Wrong column names prohibits sharing EF classes with dapper

### ISSUE THREAD

**Issue by ststeiger** [dotnet/efcore#11070] opened 2018-02-27 11:52 UTC
Even when i use  `--use-database-names` EF scaffold renames the database columns. 
e.g. parent_id becomes ParentId
Obviously, this is only for tables, but there is no equivalent for columns.
This prohibits sharing of EF classes with dapper (and I don't want to write a mapping for every class). 
More importantly, if I create different classes, I have to create different views and display templates for the "same" thing - which is bad.

Via google I found somewhere 
`-e |--entityConventionName Configure the convention name of entity class. `
and
`-f |–-fieldConventionName Configure the convention name of field of entity class. `
e.g. `–-fieldConventionName SnakeCase`
but that only yields `Unrecognized option '–-fieldConventionName'`. 

Also, I cannot specify the namespace - must rename it with sed. 

And two question: 
1) If I write my own scaffolder, does the primary key need to be called id, and if yes, is upper camel case compulsory/mandatory ? 
2) Will EF explode (at startup or at EnsureDbCreated, or at a query/join)  if I map a class without primary key ? - Never mind, answer to this question is  a resounding yes.

**Comment by smitpatel** [comment] 2018-02-28 08:31
Duplicate of #9820
We fixed in 2.1.0-preview1. The column names should retain there names too.

**Closed** 2022-10-16 12:11 UTC
Labels: closed-duplicate
