### ISSUE TITLE
Entity query fails suddenly with Index was outside the bounds of the array - RowNumberPagingExpressionVisitor in the stack trace

### ISSUE THREAD

**Issue by john-luke-laue** [dotnet/efcore#13176] opened 2018-08-31 16:11 UTC
I have a complex entity query that has been working for the past couple of weeks. Suddenly, the query starts failing.

We did recently upgrade our SQL Server from 2005 to 2016, but that was many weeks back, and the query has worked fine since the upgrade until now.

**Important Note:** An IIS reset made the issue go away.

I noticed in the stack trace that there is a call to _RowNumberPagingExpressionVisitor_.

I also noticed that we are still using the _UseRowNumberForPaging_ option for our DbContext. Maybe that is somehow related to the issue?

```
Exception message: 
An exception occurred in the database while iterating the results of a query for context type 'MyProject.Data.MyContext'. 
System.IndexOutOfRangeException: Index was outside the bounds of the array.

Stack trace:
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred in the database while iterating the results of a query for context type 'MyProject.Data.MyContext'.
      System.IndexOutOfRangeException: Index was outside the bounds of the array.
at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Expressions.SelectExpression.VisitChildren(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.Expressions.SelectExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Sql.Internal.SqlServerQuerySqlGenerator.RowNumberPagingExpressionVisitor.VisitSelectExpression(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Sql.Internal.SqlServerQuerySqlGenerator.RowNumberPagingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Sql.Internal.SqlServerQuerySqlGenerator..ctor(QuerySqlGeneratorDependencies dependencies, SelectExpression selectExpression, Boolean rowNumberPagingEnabled)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Sql.Internal.SqlServerQuerySqlGeneratorFactory.CreateDefault(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.Expressions.SelectExpression.CreateDefaultQuerySqlGenerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.GetRelationalCommand(IReadOnlyDictionary`2 parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

### Code to reproduce

```c#
    var companyTypes = _context.CompanyTypes.FromCacheMyApp().ToDictionary(k => k.Id);

    IQueryable<Companies> query = _context.Companies;

    var states = _context.StateRegions.FromCacheMyApp().ToList();
    var countries = _context.CountryCodes.FromCacheMyApp().ToList();

    var s = "test";
    Expression<Func<Companies, bool>> condition = x => x.Code.Contains(s)
         || x.Name.Contains(s) 
         || x.Places.Any(p => p.City == s);

    var matchingStateIds = states.Where(x => x.Name.Contains(s)).Select(x => x.Id).ToList();
    var matchingCountryIds = countries.Where(x => x.Name.Contains(s)).Select(x => x.Id).ToList();

    if (matchingStateIds.Any())
    {
        foreach (int matchingStateId in matchingStateIds)
        {
            condition = condition.Or(x => x.StateRegionId == matchingStateId);
        }
    }

    if (matchingCountryIds.Any())
    {
        foreach (int matchingCountryId in matchingCountryIds)
        {
            condition = condition.Or(x => x.CountryId == matchingCountryId);
        }
    }

    query = query.Where(condition);
    query = query.Skip(0).Take(30);

    var results = query
        .ToList() //ToList is called Select for a reason...
        .Select(x => new CompanyDto
        {
            Id = x.Id,
            Code = x.Code,
            CompanyType = x.CompanyTypeId.HasValue ? companyTypes[u.CompanyTypeId.Value].Code : "",
            //.....other stuff to select
        });

    var totalCount = query.Count();
```

I don't this it is relevant to the error, but if it helps, this is how we build our OR expression:
```c#
    internal class SubstExpressionVisitor : System.Linq.Expressions.ExpressionVisitor
    {
        public Dictionary<Expression, Expression> subst = new Dictionary<Expression, Expression>();

        protected override Expression VisitParameter(ParameterExpression node)
        {
            Expression newValue;
            if (subst.TryGetValue(node, out newValue))
            {
                return newValue;
            }
            return node;
        }
    }

    public static class PredicateBuilder
    {
        public static Expression<Func<T, bool>> Or<T>(this Expression<Func<T, bool>> a, Expression<Func<T, bool>> b)
        {

            ParameterExpression p = a.Parameters[0];

            SubstExpressionVisitor visitor = new SubstExpressionVisitor();
            visitor.subst[b.Parameters[0]] = p;

            Expression body = Expression.OrElse(a.Body, visitor.Visit(b.Body));
            return Expression.Lambda<Func<T, bool>>(body, p);
        }
    }
```

### Further technical details
EF Core version: 2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows Server 2008 R2

**Comment by ajcvickers** [comment] 2018-08-31 19:43
@john-luke-laue Unfortunately, there are two many unknowns in the snippets above for us to be able to effectively reproduce the issue you are seeing. Can you post a runnable project/solution or complete code listing that demonstrates the issue?

**Comment by ajcvickers** [comment] 2018-09-07 15:50
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2018-11-14 23:03
@john-luke-laue If you are still using RowNumberForPaging, could you please comment on issue #13959 and let us know why?

**Comment by john-luke-laue** [comment] 2018-11-14 23:56
@ajcvickers We finally upgrade our database from SQL Server 2005 to SQL Server 2016 which allowed us to remove `RowNumberForPaging`. It has been a little over a month since updating, and I have not gotten this error. 

So, I guess there is no reason for me to comment on the issue you linked to.

**Comment by ajcvickers** [comment] 2018-11-14 23:57
@john-luke-laue Thanks for the info. Much appreciated.

**Closed** 2022-10-16 13:28 UTC
Labels: closed-could-not-reproduce, customer-reported
