### ISSUE TITLE
Value conversion on view only works in memory/locally

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#24727] opened 2021-04-22 13:14 UTC
## File a bug

I have a view mapped to an entity containing a property using a value conversion from int (database) to bool (entity). The value conversion works when checking the `IsEligibleToVote` property on an entity object pulled back from the view but not when querying the view (using LINQ `Where` method).

When querying the view, the SQL that runs has `where age = 1` instead of `where age >= 18`.

Is this set up incorrectly or possibly not supported?

### Include your code

```C#
// view mapping
modelBuilder
    .Entity<MyEntity>(a =>
    {
        a.HasNoKey();
        a.ToView("MyTable");
        a.Property(p => p.IsEligibleToVote).HasColumName("age").HasConversion(
            a => Convert.ToInt32(v),
            a => Convert.ToBoolean(v >= 18)
        );
});

// query
var myEntities = context.MyEntities.Where(m => m.IsEligibleToVote).ToList();
```

### Include provider and version information

EF Core version: 5.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: macOS 11
IDE: Visual Studio for Mac 8.10 Preview 2

**Comment by roji** [comment] 2021-04-22 15:04
Probably a dup of #20721 - that issue explicitly discussed member translation rather than an operator, but the principle is the same.

**Comment by smitpatel** [comment] 2021-04-22 15:07
Duplicate of #24625 
Query doesn't look into value converter expressions
Value converter is not round-trip-able.

**Comment by mrlife** [comment] 2021-04-22 15:10
@smitpatel I see, so it's not convertible back to boolean in this case. Can we change this to a feature request?

**Comment by smitpatel** [comment] 2021-04-22 15:14
This particular value converter is just bad.
Suppose you read a value from database from "age" column which has value of 25. The converter will convert it to true on client side. Then if you save it back to database it will get converted to 1 in database so next time when you read from database it will be read as false on client side. This is all without making any changes to data.

**Comment by mrlife** [comment] 2021-04-22 15:15
Yes, I agree.

**Closed** 2022-10-16 19:32 UTC
Labels: closed-no-further-action, customer-reported
