### ISSUE TITLE
Unexpected behaviour in where clause

### ISSUE THREAD

**Issue by gighen76** [dotnet/efcore#13588] opened 2018-10-11 07:22 UTC
Just to exclude misunterstanding in my previous issue I'd try to describe my problem in another way.
I've following code:

```c#
var orderRows = context.OrderRows.Where(or => or.DeliveryDate != null).ToList();
if (orderRows.Any()) 
{
    var maxDeliveryDate = orderRows.Max(or => or.DeliveryDate.Value); 
}
```

In some situations I've following exception:
**InvalidOperationException:  Nullable object must have a value.**
caused by orderRows with DeliveryDate = null in or.DeliveryDate.Value .
But how can I have orderRows with null values when I requested those with "not null" values in previous where clause?

If this behaviour is correct how do have I interpret conditions in where clause? some times works and some times not?

I'm not interested in stale rows on dbcontext, I'm only interested in behaviour of where clause.

Steps to reproduce this problem are described in this issue 
https://github.com/aspnet/EntityFrameworkCore/issues/13570

**Comment by ajcvickers** [comment] 2018-10-11 16:09
Duplicate of #13570

**Closed** 2022-10-16 13:34 UTC
Labels: closed-duplicate, customer-reported
