### ISSUE TITLE
Efcore 7 max pool size was reached

### ISSUE THREAD

**Issue by granit1986** [dotnet/efcore#31118] opened 2023-06-22 04:53 UTC
We have MidLoad service on .NET Framework 4.8 and EntityFramework Core 3.1.32.
We use default Max Pool parameter in connection string for connect to MS SQL Server and all works fine.

But, when we try to upgrade the service to net 7 and efcore 7, after 2 hours of work, errors of exhaustion of the database connection pool begin to appear. We tried to make Max Pool = 500 and then the service worked for about 10 hours and errors appeared again. At the same time, SQL Server shows no more than 200 connections to the database at the peak. And at the current time everything works stably at Max Pool 100.

In the current version, we use our IdbContextFactory inside ActivatorUtilities.CreateInstance as well. In the new version, the standard IDbContextFactory

**Comment by roji** [comment] 2023-06-22 08:33
@granit1986 you're going to have to post a minimal code sample - it's not possible to help you given the short description above. It sounds like a connection leak is happening somewhere, but it's impossible to know for sure without some code.

**Comment by ajcvickers** [comment] 2023-07-12 18:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-07-12 18:44 UTC
Labels: customer-reported
