### ISSUE TITLE
Package Remotion.Linq 2.0.2 is not compatible with netcoreapp1.0

### ISSUE THREAD

**Issue by agileorange** [dotnet/efcore#5673] opened 2016-06-07 09:22 UTC
http://stackoverflow.com/questions/37645066/package-remotion-linq-2-0-2-is-not-compatible-with-netcoreapp1-0

Windows 10

If I create a .NET Core Console App in VS2015, making no changes it builds and runs as expected.

When I add Entity Framework RC2 by adding a dependency in project.json

{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    },
    "Microsoft.EntityFrameworkCore": "1.0.0-rc2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dnxcore50" ]
    }
  }
}
then restoring packages gives the following errors:

Package Ix-Async 1.2.5 is not compatible with netcoreapp1.0

Package Remotion.Linq 2.0.2 is not compatible with netcoreapp1.0
This is expected as a work around is required as per the article here: https://docs.efproject.net/en/latest/miscellaneous/rc1-rc2-upgrade.html#using-imports-in-project-json

Where it describes adding a portable profile as an import:

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dnxcore50", "portable-net45+win8" ]
    }
  }
This resolves the issue with the Ix-Async but does not fix the issue with Remotion.Linq i.e. I am still seeing this error.

Package Remotion.Linq 2.0.2 is not compatible with netcoreapp1.0
I tried everything I can think of (different profiles, different project types, clearing caches) and even uninstalled, reinstalled everything several times. Short of re-building my PC I've run of ideas...

**Comment by natemcmaster** [comment] 2016-06-07 19:18
This is a documentation bug (cc @rowanmiller). The portable imports should be "portable-**net451**+win8".

**Comment by natemcmaster** [comment] 2016-06-07 22:59
I've update the docs. Closing as a duplicate of #5176 and https://github.com/aspnet/EntityFramework.Docs/issues/183

**Closed** 2022-10-16 09:44 UTC
