### ISSUE TITLE
[GB18030]With a name using GB18030 encoded, create .NET Core-1.x project, Add Migration will meet an error: Unrecognized escape sequence.

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#11123] opened 2018-03-01 23:58 UTC
REPRO MACHINE: WNVM30593

REPRO ACCOUNT: redmond\fwtlaba
REPRO Configuration: Win10 x64 CHS +  Dev15 (Release channel : pre-release-build) VSE CHS (Web  workload, ASP.NET Core 1.0-1.1 dev tools checked)

INSTALL STEPS
1. Clean machine: Win10 x64 CHS OS
2.Install Dev15.5RTW VSE
 from: \\cpvsbuild\drops\VS\d15rel\products\27128.00\channels\internal\Release\bootstrappers\fixed
3. Select Web workload

REPRO STEPS

1. New project  >C# >Web> ASP.NET Core App > ASP.NET Core 1.1 - .NET Core >Web

App(MVC) with IndAuth >Name this peoject "①Ⅻㄨㄩ 啊阿鼾齄丂丄狚狛狜狝﨨﨩ˊˋ˙– ⿻〇㐀㐁䶴䶵" > OK.

2. In Solution Explorer, right click the Models folder > Add > Class. Name the class Movie and add the following properties

 public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set;}
        public decimal Price { get; set; }
    }

3.Right-click the Controllers folder > Add > Controller

  In the Add Scaffold dialog, tap MVC Controller with views, using Entity Framework > Add

4.Complete the Add Controller dialog

    Model class: Movie(MvcMovie.Models - your namespace)
    Data context class: ApplicationDbContext
   Views: Keep the default of each option checked
   Controller name: Keep the default MoviesController

 Tap Add

5.Verify Output window - Code Generation Log pane shows that scaffolding completed successfully, and the MoviesController and cshtml files under

Views\Movies got added in Solution Explorer

6. Open Package Manager Console (PMC) , type "Add-Migration AddMovies"

Meet an error: Unrecognized escape sequence.

**Comment by bricelam** [comment] 2018-03-02 17:44
Possible duplicate of #10532. Could consider porting to 1.1.x

**Comment by ajcvickers** [comment] 2018-03-02 20:58
This does not meet the bar for patching, so closing.

**Closed** 2022-10-16 12:11 UTC
Labels: closed-out-of-scope
