### ISSUE TITLE
CosmosDB - Entity Framework Core - Contains could not be translated

### ISSUE THREAD

**Issue by patrickdgt** [dotnet/efcore#18673] opened 2019-10-31 09:44 UTC
I try to manipulate a CosmosDB (SQL) using entity framework core 3.0. Everything works fine except when I try to use Contains

For example:

var query = _context.Challenges.Where(c => c.Name.Contains( "string"));

EF is supposed to translate it to the following SQL (that works perfectly on the CosmosDB – Query Explorer)

SELECT * FROM c WHERE CONTAINS(c.Name, "string")

But I receive the following error message:

The LINQ expression 'Where<Challenge>(\n    source: DbSet<Challenge>, \n    predicate: (c) => c.Name.Contains(\"string\"))' could not be translated. 
Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). 
See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

Of course, I don’t want to code it like the following, that will execute the entire contains on the client, just to make a simple LIKE…

List<Challenge> entities = _context.Challenges.AsEnumerable().Where(c => c.Name.Contains( "string")).ToList();

Any idea of to evaluate the "contains" on the server side ?

Note: I try the exact same code using UseSqlServer rather than UseCosmos (and by adding the needed [Key] annotation and creating a SQL server) and it works like a charm.... So I think it's a definitively a CosmosDB vs EF issue.

EF Core version: 
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: NET Core 3.0.0
Operating system: OS X Windows 10 (try both) 
IDE: Last stable version on both OSX and Windows 10

Thanks in advance for your help.

**Comment by smitpatel** [comment] 2019-10-31 12:32
Duplicate of #16143

**Comment by ajcvickers** [comment] 2019-11-01 17:31
Note from triage: do the 3.1 relational fix for Cosmos.

**Comment by krw1010** [comment] 2020-01-10 20:39
Any further info on this?   I'm encountering the same error in .NET Core 3.1.   @ajcvickers What is the relational fix you mentioned?

var user = Context.Users.Where(x => x.email.Contains("string"));

System.InvalidOperationException
  HResult=0x80131509
  Message=The LINQ expression 'DbSet<ApplicationUser>
    .Where(a => a.Email.Contains(__search_0))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
  Source=Microsoft.EntityFrameworkCore

**Comment by xtellurian** [comment] 2020-01-21 04:30
I'm also seeing this error in 3.1

**Comment by nickwilsonr** [comment] 2020-01-21 17:46
Still an issue in 3.1.1.. It looks like the solution has been [merged ](https://github.com/svengeance/EntityFrameworkCore/commit/d34b02c1066234b3adf4810ab02ce18d1dcc5f9a) though, so when can we expect it to be released?

**Comment by ajcvickers** [comment] 2020-01-22 21:54
@AndriySvyryd @smitpatel Difference between #16143 and this issue?

**Comment by AndriySvyryd** [comment] 2020-01-22 21:58
This is a subset.
Fixed in https://github.com/dotnet/efcore/commit/83dccdc2e5cc5d20ba4bb07a07a2883790f60292

**Closed by AndriySvyryd** 2020-01-22 21:58 UTC
Labels: area-query, customer-reported, type-bug
