### ISSUE TITLE
Query: optimize nested CASE blocks

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#18774] opened 2019-11-06 00:16 UTC
Some nested CASE blocks, e.g.:

```sql
CASE 
    WHEN (condition1)
    THEN 
    CASE
        WHEN (condition2)
        THEN result1
        ELSE result2 
    END
    ELSE result2
END
```

can be optimized to:

```sql
CASE
    WHEN condition1 AND condition2
    THEN result1
    ELSE result2
END
```

In practice we get those kinds of chained CASE blocks in the following scenarios:

```cs
context.Set<Product>().OrderBy(p => p.UnitsInStock > 10 ? p.ProductID > 40 : p.ProductID <= 40)
```

**Comment by smitpatel** [comment] 2019-11-12 19:30
Duplicate of #2881

**Comment by maumar** [comment] 2019-11-13 22:07
this is somewhat different scenario, where nested block happens in the THEN part, not the ELSE part

**Comment by ranma42** [comment] 2024-07-06 08:26
There are 3 ways in which `CASE` statements could be nested, each with a slightly different optimization:

### ELSE
```sql
CASE 
    WHEN t1 THEN r1
    ELSE CASE
        WHEN t2 THEN r2
        ELSE r3
    END
END
```
is already being optimized into 
```sql
CASE 
    WHEN t1 THEN r1
    WHEN t2 THEN r2
    ELSE r3
END
```
The optimization could be extended to also allow flattening of `ELSE CASE`s with the same operand as the outer `CASE` (as long as side-effects are not possible/considered).

### THEN
```sql
CASE 
    WHEN t1 THEN CASE
        WHEN t2 THEN r1
        ELSE r2
    END
    ELSE r2
END
```
can be simplified to
```sql
CASE 
    WHEN t1 AND t2 THEN r1
    ELSE r2
END
```
(the main target of this issue). This requires matching `r2` results and can only be applied (in a trivial way) to the last clause.

### CASE
```sql
CASE 
    WHEN CASE
        WHEN t1 THEN TRUE -- b1
        ELSE FALSE -- b2
    END THEN r1
    ELSE r2
END
```
can be simplified to
```sql
CASE 
    WHEN t1 THEN r1
    ELSE r2
END
```
This also works when `b2` is `NULL`; it can easily be extended to also work when `b1` is `NULL` or `FALSE` and `b2` is TRUE by negating `t1` in the result.

**Closed** 2024-07-12 19:43 UTC
Labels: type-enhancement, area-query
