### ISSUE TITLE
Add-Migration is not useful

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#30089] opened 2023-01-18 11:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-Migration-is-not-useful/10239048)._

---
[severity:It's more difficult to complete my work]
Add-Migration throws an error of Build Failed while dotnet-ef advises that a library is missing (Microsoft.EntityFrameworkCore.Design).

Why can't Add-Migration be improved, or added as a Visual Studio tool?

---
#### Feedback Bot on 12/27/2022, 02:27 AM: 

(private comment, text removed)
#### Peng Ge [MSFT] on 12/27/2022, 11:32 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2023-01-18 11:43
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-01-27 13:12
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-01-27 13:12 UTC
Labels: customer-reported
