### ISSUE TITLE
optionsBuilder.UseSqlServer AttachDBFilename |DataDirectory| fail

### ISSUE THREAD

**Issue by FlippieCoetser** [dotnet/efcore#18067] opened 2019-09-26 14:15 UTC
When passing a connection string, **with** ```|DataDirectory|``` as part of the ```AttachDBFilename``` field, to the ```optionsBuilder.UserSQL()``` an error is thrown: **Invalid value for key 'attachdbfilename'**

When passing a connection string, with the data folder path (**without** ```|DataDirectory|```)  as part of the ```AttachDBFilename``` field, to the ```optionsBuilder.UserSqlServer()``` no error is thrown.

To reproduce the error use ```EF Core Migrations``` and type ```update-database``` in Package Manager Console in Visual Studio 2019

**Comment by ErikEJ** [comment] 2019-09-26 18:10
This is a .NET Core SqlClient issue, not an EF Core issue

**Comment by smitpatel** [comment] 2019-09-26 18:34
Duplicate of dotnet/SqlClient#16

**Closed** 2022-10-16 14:45 UTC
Labels: closed-external, customer-reported
