### ISSUE TITLE
Updating Navigation Properties Clears IsModified Flag On Other Fields

### ISSUE THREAD

**Issue by andrejohansson** [dotnet/efcore#18273] opened 2019-10-08 07:56 UTC
I am using EF Core 3 with Lazy Loading Proxies and I think I've found a situation where IsModified is not working correctly.

I was trying to use the audit feature of EFPlus (https://entityframework-plus.net/audit) and noticed that some properties I changed was not being audited. 

### Steps to reproduce

```csharp

// _db.Entry(myAttachedEntity).Property(x => x.StringProperty).IsModified = false here
myAttachedEntity.StringProperty = "newvalue";
// _db.Entry(myAttachedEntity).Property(x => x.StringProperty).IsModified = true here

// Touching a navigation property on the same entity seems to reset IsModified for the stringproperty
myAttachedEntity.SomeNavProperty = new or same value;

// _db.Entry(myAttachedEntity).Property(x => x.StringProperty).IsModified = false  here
// !!! This is wrong...stringproperty is still changed

```

Since the audit framework looks to the IsModified property I never got any entries for StringProperty. The weird thing is that the changed values were still persisted to the database correctly. So it feels like either the Proxy object or the original object gets their IsModified value out of sync.

Simply changing the order of operation fixes the property for me:

```csharp

myAttachedEntity.SomeNavProperty = new value;

// _db.Entry(myAttachedEntity).Property(x => x.StringProperty).IsModified = false here
myAttachedEntity.StringProperty = "newvalue";
// _db.Entry(myAttachedEntity).Property(x => x.StringProperty).IsModified = true here

```

### Further technical details

EF Core version: 3.0.0 
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: JetBrains Rider

**Comment by ajcvickers** [comment] 2019-10-09 20:17
@andrejohansson Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-10-18 16:00
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:48 UTC
Labels: closed-could-not-reproduce, customer-reported
