### ISSUE TITLE
EF 3 - Migration Error

### ISSUE THREAD

**Issue by rodrigodevelms** [dotnet/efcore#15147] opened 2019-03-25 04:32 UTC
Hello.
I am developing in linux, using .net core 3, and am having the following error when I do dotnet ef migrations add NewMigration:
`Unable to create an object of type 'OAuthContext'. For the different patterns supported at design time,`

My context:

```
using Microsoft.EntityFrameworkCore;
using OAuth.Domain.Entity;

namespace OAuth.Infra.Context
{
    public class OAuthContext : DbContext
    {
        public DbSet<User> Users { get; set; }

        public OAuthContext(DbContextOptions<OAuthContext> options) : base(options)
        {
        }
    }
}
```

My Startup class

```
public class Startup
    {
        public IConfiguration Configuration { get; set; }

        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddDbContext<OAuthContext>(options => options.UseNpgsql(Configuration
                .GetConnectionString("postgreSQL")));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting(routes =>
            {
                routes.MapGet("/", async context => { await context.Response.WriteAsync("Hello World!"); });
            });
        }
    }

```
My Entity

```
namespace OAuth.Domain.Entity
{
    public class User
    {
        public long Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool Active { get; set; }
        public long CompanyId { get; set; }
        public long EmployeeId { get; set; }
    }
}
```

**Comment by ajcvickers** [comment] 2019-03-25 16:51
@rodrigodevelms Can you post your `.csproj` file so that we can see exactly which versions of packages are being used.

**Comment by ajcvickers** [comment] 2019-04-01 16:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:57 UTC
Labels: closed-could-not-reproduce, customer-reported
