### ISSUE TITLE
Use of List of Ints in query forces the use Client Evaluation

### ISSUE THREAD

**Issue by mdmoura** [dotnet/efcore#20443] opened 2020-03-27 22:08 UTC
I need to use a list of Ints in a query but I am getting the error:

    The linq expression ... could not be translated. 
    Either rewrite the query in a form that can be translated, or switch to client evaluation 

I have the following entities:

    public class User {
       public Int32 Id { get; set; }
       public virtual Collection<UserSkill> UserSkills { get; set; }
    }

    public class UserSkill {
       public Int32 UserId { get; set; }
       public Int32 SkillId { get; set; }
       public virtual User User { get; set; }
       public virtual Skill Skill { get; set; }
    }

Given a list of SkillsIds I need to get the Users that have all these SkillsIds in their UserSkills.

        var skillsIds = new List<Int32> { 1, 2 }; 

        var users = await context.Users
            .Where(x => skillsIds.All(y => x.UserSkills.Any(z => y == z.SkillId)))
            .ToListAsync();

And I get the following error:

```
Exception has occurred: CLR/System.InvalidOperationException
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll: 'The LINQ expression 'DbSet<User>
    .Where(u => __skillsIds_0
        .All(y => DbSet<UserSkill>
            .Where(u0 => EF.Property<Nullable<int>>(u, "Id") != null && EF.Property<Nullable<int>>(u, "Id") == EF.Property<Nullable<int>>(u0, "UserId"))
            .Any(u0 => y == u0.SkillId)))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__64`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Data.Tests.<TestShouldPassAsync>d__1.MoveNext()
``` 

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system: Mac OS X 10.15
IDE: Visual Studio Code 1.43.2

**Dotnet Info Output**
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.200/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.200 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by smitpatel** [comment] 2020-03-27 22:49
Duplicate of #19070

**Comment by mdmoura** [comment] 2020-03-27 22:58
@smitpatel I have read the other issue. It seems is in backlog and with no further work.

Is there a workaround for this problem? This is a very common scenario and I am moving a large project to Asp.Net Core with a lot of this type of queries.

Thank you

**Comment by smitpatel** [comment] 2020-03-27 23:06
You can expand list yourself into and/or. If the size of list is not known then you may need to drop down to dynamically create the expression tree.
In your case, since there is double nesting of Any/All, even though it is translated it will generate a lot of subqueries. You may want to rewrite query differently for performance reasons.

**Closed** 2022-10-16 18:18 UTC
Labels: customer-reported
