### ISSUE TITLE
Migration with HasData - JIT Compiler encountered an internal limitation

### ISSUE THREAD

**Issue by mdmoura** [dotnet/efcore#14050] opened 2018-11-30 12:03 UTC
I am creating a Migration using "dotnet ef migrations add InitialCommit".

The migration includes seeding 280 objects in one of the entities using HasData.

I am able to seed 1 and 20 objects but I get an exception when seeding 280 objects.

### Exception

```
Exception message: JIT Compiler encountered an internal limitation.
Stack trace:
System.InvalidProgramException: JIT Compiler encountered an internal limitation.
   at Proj.Configurations.CompositionConfiguration.Configure(EntityTypeBuilder`1 builder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration[TEntity](IEntityTypeConfiguration`1 configuration)
   at Proj.Context.<>c.<OnModelCreating>b__209_0(ModelBuilder x) in Proj/Context.cs:line 80
   at Proj.Context.OnModelCreating(ModelBuilder builder) in Proj/Context.cs:line 72
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
JIT Compiler encountered an internal limitation.
```

### Steps to reproduce

The entity Composition is as follows:

```
  public class Composition {

    public Int32 ProfuctId { get; set; }
    public Decimal? P01 { get; set; }
    public Decimal P02 { get; set; }
    public Decimal? P03 { get; set; }
    public Decimal P04 { get; set; } 
    public Decimal? P05 { get; set; }    
    public Decimal? P06 { get; set; }
    public Decimal? P07 { get; set; }
    public Decimal? P08 { get; set; }
    public Decimal? P09 { get; set; }
    public Decimal? P10 { get; set; }
    public Decimal? P11 { get; set; }
    public Decimal? P12 { get; set; }
    public Decimal? P13 { get; set; }
    public Decimal? P14 { get; set; }
    public Decimal P15 { get; set; }
    public Decimal? P16 { get; set; }
    public Decimal? P17 { get; set; }
    public Decimal? P18 { get; set; }
    public Decimal? P19 { get; set; }
    public Decimal? P20 { get; set; }
    public Decimal P21 { get; set; }
    public Decimal? P22 { get; set; }
    public Decimal? P23 { get; set; }    
    public Decimal? P24 { get; set; }    
    public Decimal? P25 { get; set; }      
    public Decimal? P26 { get; set; }    
    public Decimal? P27 { get; set; }
    public Decimal? P28 { get; set; }
    public Decimal? P29 { get; set; }
    public Decimal? P30 { get; set; }
    public Decimal? P31 { get; set; }
    public Decimal? P32 { get; set; }    

    public virtual Product { get; set; }

  }
```

And this is the Composition configuration:

        builder.ToTable("Compositions");

        builder.HasKey(y => y.ProductId);

        builder.Property(x => x.P01).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P02).IsRequired(true).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P03).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P04).IsRequired(true).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P05).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));        
        builder.Property(x => x.P06).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P07).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P08).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P09).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P10).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P11).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P12).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P13).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P14).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P15).IsRequired(true).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P16).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P17).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P18).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P19).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P20).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P21).IsRequired(true).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P22).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P23).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P24).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));      
        builder.Property(x => x.P25).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P26).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P27).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P28).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P29).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P30).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P31).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
        builder.Property(x => x.P32).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));        	      

        builder.HasOne(y => y.Product).WithOne(y => y.Composition).HasForeignKey<Composition>(y => y.ProductId).IsRequired(true).OnDelete(DeleteBehavior.Cascade);

        builder.HasData(
          new { 
            ProductId = 1,
            P01 = (Decimal?) 110.0, 
            P02 = (Decimal) 60030.0, 
            P03 = (Decimal?) 0.0, 
            P04 = (Decimal) 336.0, 
            P05 = (Decimal?) 10600.0, 
            P06 = (Decimal?) 0.0, 
            P07 = (Decimal?) 0.633, 
            P08 = (Decimal?) 8.27, 
            P09 = (Decimal?) 184.0, 
            P10 = (Decimal?) 106.0, 
            P11 = (Decimal?) 2.075, 
            P12 = (Decimal?) 424.0, 
            P13 = (Decimal?) 542.0, 
            P14 = (Decimal?) 1112.0, 
            P15 = (Decimal) 23520.0, 
            P16 = (Decimal?) 0.226, 
            P17 = (Decimal?) 331.0, 
            P18 = (Decimal?) 16.0, 
            P19 = (Decimal?) 6900.0, 
            P20 = (Decimal?) 0.853, 
            P21 = (Decimal) 1260.0, 
            P22 = (Decimal?) 0.633, 
            P23 = (Decimal?) 0.0, 
            P24 = (Decimal?) 0.003, 
            P25 = (Decimal?) 0.0, 
            P26 = (Decimal?) 0.357, 
            P27 = (Decimal?) 1.5, 
            P28 = (Decimal?) 0.0, 
            P29 = (Decimal?) 0.39, 
            P30 = (Decimal?) 0.005, 
            P31 = (Decimal?) 11950.0, 
            P32 = (Decimal?) 3.37 
        });

In the code example I just posted HasData is seeding only one Composition ...
In reality I am seeding 280 compositions and I also tested seeding only 20 ...

### Further technical details

```
EF Core version: 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: macOS Mojave
IDE: Visual Studio Code 1.29.1
NET Core SDK: 2.1.403
```

**Comment by benaadams** [comment] 2018-11-30 12:19
Guessing it would be the high number of variables coupled with the branches https://github.com/dotnet/coreclr/issues/12480#issuecomment-320018827 would probably need to be split into multiple method invocations?

**Comment by mdmoura** [comment] 2018-11-30 12:35
> (...) would probably need to be split into multiple method invocations?

What do you mean?

**Comment by benaadams** [comment] 2018-11-30 12:55
Would need to be done in batches
```csharp
void ConfigureStep1(EntityTypeBuilder<T> builder)
{
    builder.Property(x => x.P01).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
    // ...
    builder.Property(x => x.P30).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
}

void ConfigureStep2(EntityTypeBuilder<T> builder)
{
    builder.Property(x => x.P31).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
    // ...
    builder.Property(x => x.P60).IsRequired(false).HasColumnType(Sql.Decimal(8, 2));
}

// etc
```
So that any one method doesn't end up tracking too many locals when compiling to asm. Not sure if this is generated code, if so the generator would need to split across multiple methods. It can still call them though same initial method e.g.
```csharp
void Configure(EntityTypeBuilder<T> builder)
{
    builder.ToTable("Compositions");

    builder.HasKey(y => y.ProductId);

    ConfigureStep1(builder);
    ConfigureStep2(builder);
    ConfigureStep3(builder);
    // etc
}
```

**Comment by mdmoura** [comment] 2018-11-30 13:10
> Not sure if this is generated code (...)

It is not generated code ... 

But it is akward that such splitting is necessary to make this work ...

I mean, this is just an entity with 32 properties ... It is not that much.

And if I need to add no 280 objects but 2000? I suppose more splitting?

Even 2000 is not that much for database seeding.

**Comment by benaadams** [comment] 2018-11-30 13:35
I'd suggest opening a new issue on coreclr https://github.com/dotnet/coreclr/issues as its a Jit issue rather then EFCore issue

**Comment by ajcvickers** [comment] 2018-12-03 21:00
@mdmoura I haven't been able to reproduce this. Would it be possible for you to post a runnable project/solution or complete code listing that demonstrates the error?

**Comment by mdmoura** [comment] 2018-12-03 21:19
@ajcvickers I created a repository with it: https://github.com/mdmoura/JITCompilerEFCore

You just need to run the command:

dotnet ef migrations add InitialCommit

With that command, and with the code as it is, you will get the error:

JIT Compiler encountered an internal limitation.

Note: I am inserting 262 records to get the error ... But you can get the error with much less.

If you comment all lines, in HasData, leaving only one then the command dotnet ef migrations add InitialCommit will create the migration without any error ...

Any idea what might be wrong?

**Comment by ajcvickers** [comment] 2018-12-07 21:54
@divega Doesn't repro for me on Windows; let's try with the Mac.

**Comment by mdmoura** [comment] 2018-12-07 23:03
@ajcvickers I know the error occurs in Asp.Net Core 2.1 and I think in Asp.net Core 2.2. Not in Asp.Net Core 3.0 which release is still far away.

This means a some DataSeed scenarios will be impossible using EF Core and HasData since even the Migrations CS files will have that code.

**Comment by mdmoura** [comment] 2018-12-08 02:02
@ajcvickers I also reported this issue on coreclr as suggested by @benaadams and they were able to replicate the error: 

https://github.com/dotnet/coreclr/issues/21303#issuecomment-444605252

**Comment by divega** [comment] 2018-12-08 18:40
Thanks @mdmoura for the update.

@ajcvickers from reading the thread in the CoreCLR issue, it seems that there is a know fix and we should ask if it can be included in a patch. Can you do that?

**Comment by ajcvickers** [comment] 2018-12-08 22:17
@divega Yep, I was thinking the same thing.

**Comment by ajcvickers** [comment] 2018-12-11 00:08
@mdmoura Thanks for reporting this to coreclr--I was only trying to get a repro to hand off anyway. :-)

Closing this issue as external because https://github.com/dotnet/coreclr/issues/21303 is tracking the root cause and we are following up there.

**Closed** 2022-10-16 13:42 UTC
Labels: closed-external, customer-reported
