### ISSUE TITLE
Inclued doesn't work after GroupBy

### ISSUE THREAD

**Issue by jarzimichal** [dotnet/efcore#6226] opened 2016-08-02 07:21 UTC
Hi,

I'm trying to use Includes on GroupedBy query but getting {"Unable to cast object of type 'Remotion.Linq.Clauses.Expressions.SubQueryExpression' to type 'System.Linq.Expressions.MemberExpression'."} error.

This query was working fine on EF6

var ctx = new MyDataContext(); 
var result = ctx.SomeTable
                .Where(t => t.IsWhateverTrue)
                .GroupBy(t => t.MyGroupingKey)
                .Select(gt => 
                    gt.OrderByDescending(d => d.SomeProperty)
                        .FirstOrDefault(ah => ah.SomeAnotherFilter))
                .Include(ah => ah.IncludedTable) // THIS INCLUDE DOESN"T WORK
                .ToList(); // Execute query here

**Comment by maumar** [comment] 2016-08-02 18:13
@jarzimichal could you provide the actual query and EF model you are using (classes and DbContext listing). This makes it easier for us to reproduce as we don't have to reverse engineer the repro project. Also, as a workaround you can try to place include first, like so:

```
ctx.SomeTable.Include(t => t.SomeOtherTable).Where(...).GroupBy(...) 
```

**Comment by divega** [comment] 2016-08-08 18:14
@maumar we think this may be a dupe of another bug that talked about `Include()` after group by. Can you check?

**Comment by divega** [comment] 2016-08-10 18:26
@maumar any update?

**Comment by maumar** [comment] 2016-08-12 18:10
I couldn't find anything exactly like it. However there is a bug talking about issues with include not being right after DbSet - https://github.com/aspnet/EntityFramework/issues/3829 Is that what you were thinking about perhaps? It's not the same, but somewhat similar

**Comment by divega** [comment] 2016-08-15 06:37
Closing as duplicate of #3418.

**Closed** 2022-10-16 09:53 UTC
Labels: closed-duplicate
