### ISSUE TITLE
Migration issue with .MaxLength()

### ISSUE THREAD

**Issue by NoralK** [dotnet/efcore#2691] opened 2015-07-23 02:18 UTC
I have a basic Model called Person here is the class and the class for DbContext.

```
    public class Person
    {
        public int Person_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
    }

    public class PersonDBContext : DbContext
    {

        public DbSet<Person> Person { get; set; }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<Person>(b =>
            {
                b.Key(e => e.Person_ID);
                b.Property(e => e.Person_ID).ForSqlServer().UseIdentity();
            });

            builder.Entity<Person>()
                .Property(b => b.First_Name)
                .MaxLength(30)
                .Required();
        }

        protected override void OnConfiguring(EntityOptionsBuilder optionsBuilder)
        {
            string connString = @"Server=(localdb)\mssqllocaldb;Database=aspnet5-BaseMVC-9adc29c4-988e-411c-96d3-15ad2e5a39e7;Trusted_Connection=True;MultipleActiveResultSets=true;";
            optionsBuilder.UseSqlServer(connString);
        }
    }
```

When I perform the initial Migration the database schema that gets created in the newly created database is this:

```
CREATE TABLE [dbo].[Person] (
    [Person_ID]  INT            IDENTITY (1, 1) NOT NULL,
    [First_Name] NVARCHAR (MAX) NOT NULL,
    [Last_Name]  NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED ([Person_ID] ASC)
);
```

I believe this is incorrect, I expect [First_Name] should be NVARCHAR(30) not NVARCHAR(MAX).

**Comment by bricelam** [comment] 2015-07-23 16:36
Dupe of #882. Fixed in Beta 6.

**Closed** 2022-10-16 09:03 UTC
