### ISSUE TITLE
How to get SqlExpression/SelectExpression from IQueryable

### ISSUE THREAD

**Issue by yangzhongke** [dotnet/efcore#18334] opened 2019-10-11 11:44 UTC
I am going to get the SQL related to IQueryable in EF Core 3.0
I have got the code by RosiOli
https://gist.github.com/rionmonster/2c59f449e67edf8cd6164e9fe66c545a

But RosiOli's code uses hack code and need to execute the IQueryable.

I have tried the following code:
```
var books = ctx.Books.Where(b => b.Id > 1).Select(b=>b);
IQuerySqlGeneratorFactory factory = ctx.GetService<IQuerySqlGeneratorFactory>();
DatabaseDependencies dbDependencies = ctx.GetService<DatabaseDependencies>();
QueryCompilationContext queryComiplationCtx = dbDependencies.QueryCompilationContextFactory.Create(false);

QuerySqlGenerator sqlGenerator = factory.Create();
ISqlExpressionFactory sf = ctx.GetService<ISqlExpressionFactory>();

//some code can convert books(IQueryable) to SelectExpression

var command = sqlGenerator.GetCommand(sqe);//sqe is SelectExpression
var sql = command.CommandText;
Console.WriteLine(sql);
```

I am only a step away from success, that is 'How to convert books(IQueryable) to SelectExpression'.

Regards

**Comment by smitpatel** [comment] 2019-10-11 14:55
Duplicate of #17791

**Comment by smitpatel** [comment] 2019-10-11 14:57
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/6482#issuecomment-537740772

**Closed** 2022-10-16 14:49 UTC
Labels: customer-reported
