### ISSUE TITLE
Two references to the same owned type throws an invalidoperation exception when saving

### ISSUE THREAD

**Issue by sjkaspar** [dotnet/efcore#28485] opened 2022-07-20 12:41 UTC
[EF_Core_Issue.zip](https://github.com/dotnet/efcore/files/9149807/EF_Core_Issue.zip)
This solution contains a test project that demonstrates the issue.

Important to run: 
* you need to provide a connectionstring in the "MyContext.cs" class.
* you need to run the database update command.

What is going wrong: 
When using the same owned type more than once inside a single class EF Core uses the reference to this type instead of the value for setting the foreign key to its owner.
This results in rather unexpected behavior given we are using owned types as value types.

EF Core version: 6.0.7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 11 Pro
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment] 2022-07-23 09:34
Duplicate of #12345

**Closed by ajcvickers** 2022-07-23 09:34 UTC
Labels: customer-reported
