### ISSUE TITLE
.Contains method generate different commands if it take its value from variable or directly

### ISSUE THREAD

**Issue by mo-ah-dawood** [dotnet/efcore#27700] opened 2022-03-25 07:25 UTC
I have a million row in my table
when i search in this table by name i use contains method which take its value from variable but the generated command has  execution time bigger than the one generated if i pass value directly

> if i use variable (3,779ms)
```c#
 var value = "test";
            var list1 = source
               .Where(w => w.Name.Contains(value))
               .Take(10)
               .Select((x) => new
               {
                   x.Id
               }).ToList();
```  
- the generated command is 
- @__p_1='10'
- @__value_0='test'
``` sql
      SELECT TOP(@__p_1) [c].[Id]
      FROM [Categories] AS [c]
      WHERE ([c].[Deleted] IS NULL) AND ((@__value_0 LIKE N'') OR (CHARINDEX(@__value_0, [c].[Name]) > 0))
```

> if i  pass value directly (1,080ms)
```c#
             var list2 = source
                .Where(w => w.Name.Contains("test"))
                .Take(10)
                .Select((x) => new
                {
                    x.Id
                }).ToList();
```  
- the generated command is 
- @__p_0='10'
``` sql
      SELECT TOP(@__p_0) [c].[Id]
      FROM [Categories] AS [c]
      WHERE ([c].[Deleted] IS NULL) AND ([c].[Name] LIKE N'%test%')
```

EF 6

**Comment by roji** [comment] 2022-03-26 08:25
EF Core sometimes generates different SQL for parameter and literal/constant cases. In the specific example above, we can use LIKE with a literal because we can detect and escape wildcards (%, _) when compiling the query. The same currently isn't possible to do efficiently when the pattern is a parameter; client-side parameter transformation would allow using LIKE for this case above - I think #11881 covers that (@smitpatel do you remember if we have a better issue tracking that?).

Although we've seen cases where LIKE is significantly faster than CHARINDEX (#7429), this case is surprising because this is Contains rather than StartsWith, and presumably searching in the middle of the string (as above) cannot use an index in any case. So I'm not sure why LIKE would perform so much better than CHARINDEX - I can at least repro this and try to understand a bit better.

**Comment by ErikEJ** [comment] 2022-03-26 10:03
I think a full repro with Deleted column and index definitions is needed.

**Comment by ajcvickers** [comment] 2022-04-05 15:32
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:29 UTC
Labels: closed-by-design, customer-reported

**Comment by mo-ah-dawood** [comment] 2022-10-29 18:20
Here is my model 

```c#

public class Category : ISoftDeleted
{
    public int Id { get; set; }

    public string? Name { get; set; }
    
    public DateTime? Deleted { get; set; }
}
```

IsDeleted has query filter so that you can see in the generated column
```c#
// where T is ISoftDeleted
builder.Entity<T>().HasQueryFilter(p => p.Deleted == null);
```

**Comment by roji** [comment] 2022-10-30 18:54
@mo-ah-dawood the code sample you've provided doesn't make any use of Contains. Please open a new issue with a full, runnable code sample and a description of the exact problem you're running into.
