### ISSUE TITLE
Wrong migration when foreign key property belong to base class

### ISSUE THREAD

**Issue by myshon** [dotnet/efcore#9902] opened 2017-09-26 12:27 UTC
I have following classes (important notice `Parent` inherits `ParentBase`)

```C#
public class ParentBase
{
    public Guid ChildId { get; private set; }

    public ParentBase(Guid childId)
    {
        ChildId = childId;
    }
}

public class Parent : ParentBase
{
    public Guid Id { get; private set; }
    
    public string Code { get; private set; }

    public Parent(Guid id, string code, Guid childId) 
		: base(childId)
    {
        Id = id;
        Code = code;
    }
}

public class Child
{
    public Guid Id { get; private set; }

    public Child(Guid id)
    {
        Id = id;
    }
}
```
and following mapping configuration 
```C#
modelBuilder.Entity<Parent>(b =>
{
    b.HasKey(e => e.Id);
    b.HasOne<Child>().WithMany().HasForeignKey(x => x.ChildId).IsRequired();
});
```
When I add migration then it generates: 

## Actual result
```C#
migrationBuilder.CreateTable(
    name: "Parent",
    schema: "Test",
    columns: table => new
    {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        ChildId = table.Column<Guid>(type: "uuid", nullable: false),
        ChildId1 = table.Column<Guid>(type: "uuid", nullable: true),
        Code = table.Column<string>(type: "text", nullable: true)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Parent", x => x.Id);
        table.ForeignKey(
            name: "FK_Parent_Child_ChildId",
            column: x => x.ChildId,
            principalSchema: "Test",
            principalTable: "Child",
            principalColumn: "Id",
            onDelete: ReferentialAction.Cascade);
        table.ForeignKey(
            name: "FK_Parent_Child_ChildId1",
            column: x => x.ChildId1,
            principalSchema: "Test",
            principalTable: "Child",
            principalColumn: "Id",
            onDelete: ReferentialAction.Restrict);
    });
```

As you see, there is additional nullable column  `ChildId1` which is wrong. When I remove `ParentBase` and move properties `ChildId` to `Parent` class then it generates correct migration as excepted result. 

## Expected result
```C#
migrationBuilder.CreateTable(
    name: "Parent",
    schema: "Test",
    columns: table => new
    {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        ChildId = table.Column<Guid>(type: "uuid", nullable: false),
        Code = table.Column<string>(type: "text", nullable: true)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Parent", x => x.Id);
        table.ForeignKey(
            name: "FK_Parent_Child_ChildId",
            column: x => x.ChildId,
            principalSchema: "Test",
            principalTable: "Child",
            principalColumn: "Id",
            onDelete: ReferentialAction.Cascade);
    });
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Npgsql.EntityFrameworkCore.PostgresSQL 2.0.0
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment] 2017-09-26 16:56
@myshon I was able to reproduce this and it looks like it's a side-effect of #9705. Workarounds are to either give `ChildId` a public setter or explicitly map it before configuring the relationship:
```C#
modelBuilder.Entity<Parent>(b =>
{
    b.HasKey(e => e.Id);
    b.Property(e => e.ChildId);
    b.HasOne<Child>().WithMany().HasForeignKey(x => x.ChildId).IsRequired();
});
```

**Comment by myshon** [comment] 2017-09-26 20:20
@ajcvickers I would like keep DDD approach so public setter doesn't sound good, but explicit configuration is fine. Thanks!

**Comment by ajcvickers** [comment] 2018-04-08 18:07
Same root cause as #9705, and fixed by the fix for that issue which already went into preview2. Closing as duplicate.

**Closed** 2022-10-16 11:51 UTC
Labels: type-bug, closed-duplicate
