### ISSUE TITLE
Multi Include() query causing output that generates every possible combination of a record.

### ISSUE THREAD

**Issue by UncountedBrute2** [dotnet/efcore#19790] opened 2020-02-04 11:04 UTC
Entity framework core as of version 3 causes included tables to generate every combinations of related records.
As an example, in the system that was identified, from one expected result from around 12 joined tables, 51000 rows were returned before selecting the first record. This causes SQL timeout exceptions due to the overhead of producing all the combinations.
I have reproduced the issue into a generic version, please accept that the design of this example would not be used in production but allows you to replicate the issue.

This is a performance regression from ef core 2.2 which runs seperate queries on each table and then joins it on the server to the object in question.

```
public class User
    {
        public long RowId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public List<Job> Jobs { get; set; }
        public List<Clothing> ClothingItems { get; set; }

        public static List<User> TestUsers()
        {
            return new List<User>()
            {
                new User()
                {
                    FirstName = "John",
                    MiddleName = "Michael",
                    LastName = "Smith",
                    EmailAddress = "jsmith@test.com",
                    Jobs = new List<Job>()
                    {
                        new Job()
                        {
                            Title = "Something",
                            Department = "Important",
                            Division = "ICT",
                            StartDate = DateTime.Now,
                            EndDate = DateTime.Now
                        },
                        new Job()
                        {
                            Title = "Something Else",
                            Department = "That is Important",
                            Division = "HR",
                            StartDate = DateTime.Now,
                            EndDate = DateTime.Now
                        }
                    },
                    ClothingItems = new List<Clothing>()
                    {
                        new Clothing()
                        {
                            Make = "Something",
                            Model = "Expensive"
                        },
                        new Clothing()
                        {
                            Make = "Something",
                            Model = "Cheap"
                        }
                    }
                }
            };
        }
    }
```

```
public class Job
    {
        public long RowId { get; set; }
        public string Title { get; set; }
        public string Department { get; set; }
        public string Division { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public long UserRowId { get; set; }
        public User User { get; set; }
    }
```

```
public class Clothing
    {
        public long RowId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public long UserRowId { get; set; }
        public User User { get; set; }
    }
```

```
public class TestDbContext : DbContext
    {
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Clothing> ClothingItems { get; set; }
        public static readonly ILoggerFactory MyLoggerFactory = LoggerFactory.Create(builder => { builder.AddConsole(); });
        protected override void OnConfiguring(DbContextOptionsBuilder options) => options.UseLoggerFactory(MyLoggerFactory).UseSqlite("Data Source=sqlitedemo.db");
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<User>(entity =>
            {
                entity.HasKey(e => e.RowId);
                entity.ToTable("users");
                entity.Property(e => e.RowId).HasColumnName("row_id").IsRequired().ValueGeneratedOnAdd();
                entity.Property(e => e.FirstName).HasColumnName("first_name").HasColumnType("VARCHAR(100)");
                entity.Property(e => e.MiddleName).HasColumnName("middle_name").HasColumnType("VARCHAR(100)");
                entity.Property(e => e.LastName).HasColumnName("last_name").HasColumnType("VARCHAR(100)");
                entity.Property(e => e.EmailAddress).HasColumnName("email_address").HasColumnType("varchar(200)");
            });

            modelBuilder.Entity<Job>(entity =>
            {
                entity.HasKey(e => e.RowId);
                entity.ToTable("jobs");
                entity.Property(e => e.RowId).HasColumnName("row_id").IsRequired().ValueGeneratedOnAdd();
                entity.Property(e => e.Title).HasColumnName("title").HasColumnType("VARCHAR(100)");
                entity.Property(e => e.Department).HasColumnName("department").HasColumnType("VARCHAR(100)");
                entity.Property(e => e.Division).HasColumnName("division").HasColumnType("VARCHAR(100)");
                entity.Property(e => e.StartDate).HasColumnName("start_date").HasColumnType("DATETIME");
                entity.Property(e => e.EndDate).HasColumnName("end_date").HasColumnType("DATETIME");
                entity.Property(e => e.UserRowId).HasColumnName("user_row_id").HasColumnType("BIGINT");
                entity.HasOne(e => e.User).WithMany(e => e.Jobs).HasForeignKey(e => e.UserRowId);
            });

            modelBuilder.Entity<Clothing>(entity =>
            {
                entity.HasKey(e => e.RowId);
                entity.ToTable("clothing");
                entity.Property(e => e.RowId).HasColumnName("row_id").IsRequired().ValueGeneratedOnAdd();
                entity.Property(e => e.Make).HasColumnName("make").HasColumnType("VARCHAR(100)");
                entity.Property(e => e.Model).HasColumnName("model").HasColumnType("VARCHAR(100)");
                entity.Property(e => e.UserRowId).HasColumnName("user_row_id").HasColumnType("VARCHAR(100)");
                entity.HasOne(e => e.User).WithMany(e => e.ClothingItems).HasForeignKey(e => e.UserRowId);
            });
        }
    }
```

Running the following sql call will output the sql to the console:
```
using (TestDbContext testDbContext = new TestDbContext())
            {
                var result = testDbContext.Users
                    .Include(c => c.Jobs)
                    .Include(c => c.ClothingItems)
                    .AsNoTracking().Where(e => e.FirstName == "John");
            }
```

This will output the following:
```
 SELECT "u"."row_id", "u"."email_address", "u"."first_name", "u"."last_name", "u"."middle_name", "j"."row_id", "j"."department", "j"."division", "j"."end_date", "j"."start_date", "j"."title", "j"."user_row_id", "c"."row_id", "c"."make", "c"."model", "c"."user_row_id"
      FROM "users" AS "u"
      LEFT JOIN "jobs" AS "j" ON "u"."row_id" = "j"."user_row_id"
      LEFT JOIN "clothing" AS "c" ON "u"."row_id" = "c"."user_row_id"
      ORDER BY "u"."row_id", "j"."row_id", "c"."row_id"
```
![image](https://user-images.githubusercontent.com/47774993/73739396-0d9a9380-473e-11ea-94bf-c0143f722e4f.png)

**Comment by ajcvickers** [comment] 2020-02-04 17:07
Duplicate of #18022

**Closed** 2022-10-16 18:09 UTC
Labels: customer-reported
