### ISSUE TITLE
EnsureCreated when multiple DbContext in one database

### ISSUE THREAD

**Issue by rodchenkov** [dotnet/efcore#8320] opened 2017-04-28 10:55 UTC
Hi All

I have integration test project and I need to create test database based on 3 DbContexts.

My code:
`
identityDbContext.Database.EnsureCreated();
configurationDbContext.Database.EnsureCreated();
persistedGrantDbContext.Database.EnsureCreated();
`

As a result only tables for first DbContext (identityDbContext) created.

Can you please provide solution on how to solve this?

**Comment by ajcvickers** [comment] 2017-04-28 14:56
Dupe of #2874 (See comments at the end for what to do instead.)

**Closed** 2022-10-16 11:03 UTC
