### ISSUE TITLE
Can't build sources

### ISSUE THREAD

**Issue by gitsparty** [dotnet/efcore#8031] opened 2017-03-30 07:48 UTC
build initialize doesn't work as 

### Steps to reproduce
RUN "build initialize". it will fail as I don't have access to nuget store msblox.pkgs.visualstudio.com. Is this expected?

Retrying 'FindPackagesByIdAsync' for source 'https://msblox.pkgs.visualstudio.com/DefaultCollection/_packaging/de9af483-3d68-4e7c-88a3-a79624abdade/nuget/v3/flat2/internal.aspnetcore.buildtools.tasks/index.json'.
  Response status code does not indicate success: 401 (Unauthorized).
  Retrying 'FindPackagesByIdAsync' for source 'https://msblox.pkgs.visualstudio.com/DefaultCollection/_packaging/de9af483-3d68-4e7c-88a3-a79624abdade/nuget/v3/flat2/nugetpackageverifier/index.json'.
  Response status code does not indicate success: 401 (Unauthorized).
  Retrying 'FindPackagesByIdAsync' for source 'https://msblox.pkgs.visualstudio.com/DefaultCollection/_packaging/de9af483-3d68-4e7c-88a3-a79624abdade/nuget/v3/flat2/internal.aspnetcore.buildtools.tasks/index.json'.
  Response status code does not indicate success: 401 (Unauthorized).
  Retrying 'FindPackagesByIdAsync' for source 'https://msblox.pkgs.visualstudio.com/DefaultCollection/_packaging/de9af483-3d68-4e7c-88a3-a79624abdade/nuget/v3/flat2/nugetpackageverifier/index.json'.
  Response status code does not indicate success: 401 (Unauthorized).

### Further technical details
EF Core version: N/A
Database Provider: N/A
Operating system: Windows 10
IDE: N/A

**Comment by ajcvickers** [comment] 2017-03-31 23:14
@gitsparty What branch are you trying to build? Also, "initialize" is no longer supported by build since we moved from project.json to msbuild. Do you also see these errors when just doing a straightforward "build"?

**Comment by ajcvickers** [comment] 2017-04-05 18:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by nagytech** [comment] 2017-07-06 11:38
@ajcvickers If the [Getting and Building the Code](https://github.com/aspnet/EntityFramework/wiki/Getting-and-Building-the-Code) instructions are no longer relevant, do you think they can be updated?

**Comment by ajcvickers** [comment] 2017-07-06 15:34
@nagytech Updated. @bricelam Can you scan over my updates and add anything I missed/got wrong?

**Comment by bricelam** [comment] 2017-07-06 16:17
LGTM

**Comment by smitpatel** [comment] 2017-07-06 16:19
I edited a couple of things. 😃

**Comment by smitpatel** [comment] 2017-07-06 17:39
@divega

**Comment by nagytech** [comment] 2017-07-07 04:44
@ajcvickers thanks, I'll try it this evening.

**Closed** 2022-10-16 10:59 UTC
Labels: closed-could-not-reproduce
