### ISSUE TITLE
JSON materialization code is not resilient to empty string

### ISSUE THREAD

**Issue by ascott18** [dotnet/efcore#33074] opened 2024-02-12 18:10 UTC
## File a bug

When a JSON column is added by migration to an existing table, the default value of the column is `""`, i.e. empty string. The JSON deserialization code cannot handle this and enters an infinite loop. This affects columns that store an array, but potentially other types as well.

Related: #32194 

### Include your code

```C#
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

Context.conn.Open();
var context = new Context();
context.Database.EnsureCreated();
context.Foos.Add(new () { Integers = [] });
context.SaveChanges();

// Simulate "Integers" being added later via migration where it receives a defaultValue of "".
context.ChangeTracker.Clear();
context.Database.ExecuteSqlRaw("UPDATE Foos SET Integers = ''");

// ERROR HERE: This code never completes. Process stuck at 10% CPU usages on 16 core CPU (somewhere between 1-2 core maxed out):
var result = context.Foos.Single();

class Context : DbContext 
{
	public static SqliteConnection conn = new("Data Source=:memory:");

	public DbSet<Foo> Foos { get; set; }
	
	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		optionsBuilder.UseSqlite(conn);
	}
}

class Foo 
{
	public int Id { get; set; }

	public int[] Integers { get; set; }
}

```

### Include stack traces

No stack trace - code enters an infinite loop. It never returns nor throws.

### Include verbose output

No output - code enters an infinite loop. It never returns nor throws.

### Include provider and version information

EF Core version: 8.0.1
Database provider: both SQL Server and SQLite 
Target framework: Net 8
Operating system: Win 10
IDE: VS Code

**Comment by maumar** [comment] 2024-02-12 18:56
duplicate of https://github.com/dotnet/efcore/issues/32896 (which has been fixed in 8.0.3 patch)

**Closed** 2024-02-12 19:37 UTC
Labels: closed-duplicate, customer-reported
