### ISSUE TITLE
Error with Primitive Collection and Outer/Cross Apply it

### ISSUE THREAD

**Issue by SpaceOgre** [dotnet/efcore#32477] opened 2023-12-01 12:33 UTC
We have started using Primitive Collections now and want to create the following SQL in LINQ:

```sql
SELECT sri.Id, STRING_AGG(s.Name, ', ') WITHIN GROUP (ORDER BY sri.Id) AS Skolor
FROM StudentReportImports sri
OUTER APPLY OPENJSON(sri.Schools) WITH ([value] nvarchar(10) '$') AS js
INNER JOIN Schools s ON s.SchoolCode = js.value
GROUP BY sri.Id
```

This is only a small part of the LINQ that we build, we are going to join it based on the selected Id.

I have tried lots of ways to try and solve this, usually I get an error of this typ:
```
System.InvalidOperationException: The LINQ expression 'EF.Property<List<string>>(StructuralTypeShaperExpression: 
    GR.Elevinformation.Library.DataAccess.Models.Elinfil
    ValueBufferExpression: 
        ProjectionBindingExpression: EmptyProjectionMember
    IsNullable: False
, "Schools")' could not be translated
```

### Include your code

```csharp
public class StudentReportImports
{
    public Guid Id { get; set; }
    public List<string> Schools { get; set; }
}

public class School
{
    public Guid Id { get; set; }
    public string Code { get; set; }
    public string Name { get; set; }
}
```

I would like to write it something like this (this is not with the group by and string join because it gives the error anyway)
```csharp
from sri in _dbContext.StudentReportImports
from schoolCode in sri.Schools //this seems to be the problem
join school in _dbContext.Schools
on schoolCode equals school.Code into schoolGroup
from school in schoolGroup.DefaultIfEmpty()
select school
```

This is working but I don't like that i have to include the `.First()` and it seems to verbose with the extra join on _dbContext.StudentReportImports
```csharp
from sri in _dbContext.StudentReportImports
//There is more stuff here
from namnSkolor in _dbContext.StudentReportImports
    .Where(x => x.Id == sri.Id)
    .Select(ef =>
        ef.Schools
            .Join(_dbContext.Schools, code=> code, s => s.Code, (_, school) => new { ef.Id, school.Name })
            .Join(_dbContext.StudentReportImports, steg2 => steg2.Id, ef => ef.Id, (steg1, ef) => new { ef.Id, steg1.Name })
            .GroupBy(y => y.Id)
            .Select(y => string.Join(";", y.Select(x => x.Name).OrderBy(x => x)))
            .First()
    ).DefaultIfEmpty()
```

Like above I would like to be able to write it more like this:
```csharp
from sri in _dbContext.StudentReportImports
//There is more stuff here
from namnSkolor in sri.Schools //Not working
        .Join(_dbContext.Schools, code=> code, s => s.Code, (_, school) => new { ef.Id, school.Name })
        .Join(_dbContext.StudentReportImports, steg2 => steg2.Id, ef => ef.Id, (steg1, ef) => new { ef.Id, steg1.Name })
        .GroupBy(y => y.Id)
        .Select(y => string.Join(";", y.Select(x => x.Name).OrderBy(x => x)))
        .DefaultIfEmpty()
```

### Include stack traces

```
System.InvalidOperationException: The LINQ expression 'EF.Property<List<string>>(StructuralTypeShaperExpression: 
    GR.Elevinformation.Library.DataAccess.Models.Elinfil
    ValueBufferExpression: 
        ProjectionBindingExpression: EmptyProjectionMember
    IsNullable: False
, "Schools")' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelectMany(ShapedQueryExpression source, LambdaExpression collectionSelector, LambdaExpression resultSelector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

### Include provider and version information

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.8

**Comment by SpaceOgre** [comment] 2023-12-01 12:41
It also seems like `SelectMany` does not work with Primitive Collections, it gives the same error.

**Comment by SpaceOgre** [comment] 2023-12-06 20:09
Could it be connected to #32505? Or even the same issue?

**Comment by roji** [comment] 2024-01-05 06:43
> It also seems like SelectMany does not work with Primitive Collections, it gives the same error.

I'd need to see some code to be sure, but that sounds like #32505. This has already been fixed for 9.0, so you can give the [daily builds](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md) a try to confirm whether that's working. We aren't patching 8.0 with a fix for this yet, but if there's enough user feedback we may consider doing that.

**Comment by roji** [comment] 2024-01-05 06:52
Duplicate of #32505

**Comment by roji** [comment] 2024-01-05 06:56
Yes, doing `from ... from ...` generates a SelectMany under the hood, and there was a bug with SelectMany directly over primitive collections (that's #32505). This has already been fixed in main; I've verified and your query:

```c#
from sri in _dbContext.StudentReportImports
from schoolCode in sri.Schools //this seems to be the problem
join school in _dbContext.Schools
on schoolCode equals school.Code into schoolGroup
from school in schoolGroup.DefaultIfEmpty()
select school
```

Translates in the latest bits, producing the following SQL:

```sql
SELECT [s1].[Id], [s1].[Code]
FROM [StudentReportImports] AS [s]
CROSS APPLY OPENJSON([s].[Schools]) WITH ([value] nvarchar(max) '$') AS [s0]
LEFT JOIN [Schools] AS [s1] ON [s0].[value] = [s1].[Code]
```

Please upvote #32505 - if enough users consider this blocking we may consider patching it for 8.0. In the meantime, once the 9.0 previews start coming out, you can use those (previews are considered very stable), or continue using your workaround with First (or just with SQL).

**Closed** 2024-01-05 09:33 UTC
Labels: customer-reported
