### ISSUE TITLE
UNABLE TO LOAD VIEWS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#16282] opened 2019-06-25 23:43 UTC
Use migrations to create the database for SoftSpot300Context
In Visual Studio, use the Package Manager Console to scaffold a new migration and apply it to the database:

```
PM> Add-Migration [migration name] 
PM> Update-Database
```
Alternatively, you can scaffold a new migration and apply it from a command prompt at your project directory:
```
> dotnet ef migrations add [migration name] 
> dotnet ef database update
```

Thats the error i get have a clue am build a database and when i click on these 2 tabs to see my Views, i get the error above ,ive tried to do what has been said above, if anyone has detailed instructions or a solution id be vert greatful.

Thanks in advance

Darren

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/589700/unable-to-load-views.html
VSTS ticketId: 902491_
_These are the original issue comments:_

Visual Studio Feedback System on 5/30/2019, 08:35 PM (25 days ago): <p"We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p"

_These are the original issue solutions:_
(no solutions)

**Comment by ajcvickers** [comment] 2019-06-26 17:35
Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-07-05 15:59
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:27 UTC
Labels: closed-could-not-reproduce, customer-reported
