### ISSUE TITLE
Migrations: Ability to list applied and unapplied migrations

### ISSUE THREAD

**Issue by dneimke** [dotnet/efcore#6007] opened 2016-07-07 00:23 UTC
We can use the following command to list all Migrations in a project:

`dotnet ef migrations list`

I would like to see flags added that allow a user to view applied and unapplied Migrations.   For example:

```
** Lists applied migrations only **
dotnet ef migrations list -a

** Lists unapplied migrations only **
dotnet ef migrations list -u
```

**Comment by gdoron** [comment] 2016-07-07 00:39
Also would be nice if database update will show the migrations that were applied.

**Comment by lnaie** [comment] 2016-07-07 08:36
And the ability to output the --json to a file

**Comment by bricelam** [comment] 2016-10-06 20:49
Closing as a dupe of #577

**Closed** 2022-10-16 09:49 UTC
