### ISSUE TITLE
Add-Migration generated code is not correct for HasConversions() of enums

### ISSUE THREAD

**Issue by vflame** [dotnet/efcore#11845] opened 2018-04-28 05:12 UTC
When adding a ValueConverter for an enum to an entity property, the subequent scaffolding code generated when using ```add-migration``` keeps trying to alter the column to ```nullable: false```, even when the existing column is already ```nullable: false```. It appears that this behavior is specific to enum conversions and occurs when using ```EnumToStringConverter<T>()``` and when manually writing the lambdas for ```HasConversion()```.

To reproduce:

1) Create a dbcontext in a .Net Core 2.1 project with a database provider/dependency installed from nuget and configured in Startup.cs

```c#
  services.AddDbContext<ApplicationDbContext>(options => options.UseSqlite("Data Source=temp.db"));
```

2) Within DbContext.cs, create a property with two types that require conversion, one of which is an enum:

```c#
  public class Product
    {
        public int Id { get; private set; }
        public Types MyEnum { get; set; }

        public Uri MyUri
        {
            get;
            set;
        }

    }

    public enum Types
    {
        One,
        Two,
        Three
    }
```
3) Configure the entity in DbContext.cs:

```c#
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<Product>().Property(p => p.MyEnum).HasConversion(new EnumToStringConverter<Types>());

            builder.Entity<Product>().Property(p => p.MyUri).HasConversion(
                v => v.ToString(),
                v => new Uri(v));
        }
```

4) Run consecutive migrations without changing entity configurations:

```
add-migration AddValueConverters
```
Yields:
```c#
public partial class ValueConvertersAdded : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "MyEnum",
                table: "Products",
                nullable: false,
                oldClrType: typeof(int));

            migrationBuilder.AddColumn<string>(
                name: "MyUri",
                table: "Products",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "MyUri",
                table: "Products");

            migrationBuilder.AlterColumn<int>(
                name: "MyEnum",
                table: "Products",
                nullable: false,
                oldClrType: typeof(string));
        }
    }
```

```
add-migration ThisMigrationShouldBeEmpty
```
Yields:

```c#
public partial class ThisMigrationShouldBeEmpty : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            
            migrationBuilder.AlterColumn<string>(
                name: "MyEnum",
                table: "Products",
                nullable: false,
                oldClrType: typeof(string),
                oldNullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "MyEnum",
                table: "Products",
                nullable: true,
                oldClrType: typeof(string));
        }
    }
```

The expected result of the second migration is:

```c#
public partial class ThisMigrationShouldBeEmpty : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
```

[EFCoreValueConverterTest.zip](https://github.com/aspnet/EntityFrameworkCore/files/1957297/EFCoreValueConverterTest.zip)

EF Core version: 2.1.preview final
Database Provider: tested with Sqlite/NPGSql
Operating system: Win10
IDE: Visual Studio 2017 15.7

**Comment by smitpatel** [comment] 2018-04-30 18:56
Duplicate of #11343

**Closed** 2022-10-16 12:22 UTC
