### ISSUE TITLE
need method: public DbSet Set(Type entityType) in DbContext.cs for Migrating from .net4.5

### ISSUE THREAD

**Issue by yangke2911** [dotnet/efcore#18635] opened 2019-10-29 11:58 UTC
DbSet Set(Type entityType) Sync/Migrating coding from .net 4.5 issue

need method: public DbSet Set(Type entityType) in EntityFrameworkCore/DbContext.cs for Migrating from .net 4.5 to aspnetcore

**Comment by ajcvickers** [comment] 2019-10-29 16:28
Duplicate of #2586 and #747.

**Comment by yangke2911** [comment] 2019-10-30 02:29
basically below solution works fine for me so far. thanks! Hope whole solution all works  #fine.
-----------------------------------------------------------------------------------
MeikelLP commented on Feb 6, 2018
Here is my code (works at least for me).

        [HttpPost]
        public async Task<IActionResult> List(string entityType)
        {
            var type = typeof(ApplicationUser).Assembly.GetType(entityType);
            if (type == null) return NotFound("Unkown entity");
            var dbSetMethodInfo = typeof(DbContext).GetMethod("Set");
            var dbSet = dbSetMethodInfo.MakeGenericMethod(type).Invoke(_db, null);

            var toListMethodInfo = typeof(EntityFrameworkQueryableExtensions).GetMethod("ToListAsync").MakeGenericMethod(type);
            var toListMethod = (dynamic)toListMethodInfo.Invoke(dbSet, new []{dbSet, default(CancellationToken)});
            var results = await toListMethod;

            return Json(results);
        }

**Closed** 2022-10-16 14:52 UTC
Labels: customer-reported
