### ISSUE TITLE
An invalid index is being created

### ISSUE THREAD

**Issue by NikVladi** [dotnet/efcore#34358] opened 2024-08-05 01:12 UTC
Microsoft.EntityFrameworkCore 8.0.7.
Npgsql.EntityFrameworkCore.PostgreSQL 8.0.4.

I have two models. 

using Microsoft.EntityFrameworkCore;

Country:
public class Country 
{
    public int Id { get; set; }
    public string Name { get; set; }    
}

Region:
public class Region
{  
    public int Id { get; set; }
    public string Name { get; set; }
    public Country Country { get; set; }  
}

The issue:
//Correctly. An index is created by Name and CountryId as expected
 [Index("Name", "CountryId", IsUnique = true)]
public class Region
...

//Incorrectly. An index is created by Name and Id as unexpected
 [Index(nameof(Name), nameof(Country.Id), IsUnique = true)]
public class Region
...

**Comment by roji** [comment] 2024-08-05 08:37
> //Incorrectly. An index is created by Name and Id as unexpected
> [Index(nameof(Name), nameof(Country.Id), IsUnique = true)]

What's unexpected about this? In C#, `nameof(Country.Id)` returns "Id" - this has nothing to do with EF Core.

Note also that databases do not support creating an index over multiple tables, as you seem to be trying to do here.

**Comment by ajcvickers** [comment] 2024-08-12 10:34
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-08-12 10:34 UTC
Labels: customer-reported
