### ISSUE TITLE
Migrations: Unexpected rename tables

### ISSUE THREAD

**Issue by FinkoAI** [dotnet/efcore#12813] opened 2018-07-26 15:41 UTC
We have merged two branches with a lot of changes (including TPH for one type).

Basically we had one class Vehicle, but we have changed it to base class BaseVehicle and added another one overload.

```
modelBuilder.Entity<Vehicle>();
modelBuilder.Entity<Trailer>();
            
modelBuilder.Entity<BaseVehicle>()
    .HasDiscriminator(x => x.Discriminator)  
    .HasValue<Vehicle>(nameof(Vehicle))
    .HasValue<Trailer>(nameof(Trailer));
```

We also had another one TPH for Events with several overloads (were not changed in the branch).

```
modelBuilder.Entity<TripEvent>();
modelBuilder.Entity<SessionEvent>();

modelBuilder
    .Entity<Event>()
    .HasDiscriminator(x => x.Discriminator)
     .HasValue<TripEvent>(nameof(TripEvent))
     .HasValue<SessionEvent>(nameof(SessionEvent));
```

We have tried to generate migration, and got the following (besides other changes).

```
migrationBuilder.RenameTable(
    name: "Vehicles",
    newName: "Events");

migrationBuilder.RenameTable(
    name: "Events",
    newName: "BaseVehicles");
```

But we expected, that it would rename Vehicles table to BaseVehicles directly.

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.4

**Comment by bricelam** [comment] 2018-07-27 17:17
This may be fixed in 2.1--there were a lot of improvements in this area.

**Comment by ajcvickers** [comment] 2018-07-30 22:50
@FinkoAI Can you test with 2.1 and let us know if this is fixed there? If not, can you post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by ajcvickers** [comment] 2018-08-06 18:07
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:21 UTC
Labels: closed-could-not-reproduce, customer-reported
