### ISSUE TITLE
Run Custom Sql in EF Core

### ISSUE THREAD

**Issue by shawn-show** [dotnet/efcore#19534] opened 2020-01-09 08:13 UTC
If I want to execute raw sql like
```sql
declare @adCode nvarchar(50)='SCHAEFFLER\xiaoxio';
with a as (
    select o.Code, sum(omi.Amount * MI.Price) TotalPrice
    from OrderMeasureInstrument OMI
             left join [Order] O on OMI.OrderFK = O.Id
             left join [User] U on O.UserFK = U.Id
             left join MeasureInstrument MI on OMI.InstrumentFK = MI.Id
    where u.ADCode = @adCode
      and o.State = 1
    group by O.Code),
     b as (select o.Code, sum(OMA.Amount * MA.Price) TotalPrice
           from OrderMeasureAccessory OMA
                    left join [Order] O on OMA.OrderFK = O.Id
                    left join [User] U on O.UserFK = U.Id
                    left join MeasureAccessory MA on OMA.AccessoryFK = MA.Id
           where u.ADCode = @adCode
             and o.State = 1
           group by O.Code)
select a.Code, a.TotalPrice + b.TotalPrice TotalPrice
from a
         left join b on a.Code = b.Code
```
The fields in sql doesnt exist in any table of the database,how can I do it,

I'd like ef core can do that:
 HashTable table = _context.Database.RawSql("")

**Comment by ajcvickers** [comment] 2020-01-10 18:18
@shawn-show Can you provide some more details as to what exactly you are trying to do. Do you have entity types defined? What does, "sql doesnt exist in any table" mean?

**Comment by ajcvickers** [comment] 2020-01-17 17:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:04 UTC
Labels: closed-could-not-reproduce, customer-reported
