### ISSUE TITLE
Can async methods not throw, if IQueryable is made from IEnumerable?

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22726] opened 2020-09-24 22:36 UTC
Moved from discussions.

### Question

From @voroninp

I have a function `func` with signature  `Func<IQueryable<T>, Task<T>>`.

When in unit tests I call `await func(items.AsEnumerable())` I get exception that IQueryable has unsupported provider. 

`FirstOrDefaultAsync`, `ToListAsyn`, etc - all such methods throw exception.  

Can EF just fallback to wrapping regular method (`FirstOrDefault`, `ToList`) with a task instead of throwing?

### Replies

From @smitpatel 

Just refer to discussion on #9179

**Comment by smitpatel** [comment] 2020-09-25 03:45
Duplicate of #9179

**Closed** 2022-10-16 18:43 UTC
Labels: closed-duplicate, customer-reported
