### ISSUE TITLE
Update-Database always takes Production configuration

### ISSUE THREAD

**Issue by foconnor-DS** [dotnet/efcore#19210] opened 2019-12-06 17:19 UTC
I'm not sure if this is an EF Core bug, or a ASPNETCore bug, or a new "NetCore" bug. 

Here's what happens:

I have a .Net Core 3.1 Generic Host (Project Sdk="Microsoft.NET.Sdk.Worker"). I use the provided CreateDefaultBuilder. As you know, it handles the Config, along with Environment specific configuration ( like we expect from CreateDefaultWebBuilder).

I wire up the DbContext in a relatively standard way:
```C#
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((hostContext, services) =>
                {                    
                    services.AddDbContext<AppNameDBContext>
                            (
                                options => options.UseLazyLoadingProxies()
                                .UseSqlServer(hostContext.Configuration.GetConnectionString("DefaultConnection"),
                                sqlServerOptionsAction: sqlOptions => {
                                    sqlOptions.MigrationsAssembly("AppName.Data");
                                    sqlOptions.EnableRetryOnFailure(
                                        maxRetryCount: 5,
                                        maxRetryDelay: TimeSpan.FromSeconds(5),
                                        errorNumbersToAdd: null);
                                 })
                            );
```

When I run my app, it uses the appropriate environment specified by the new environmental variable prefix DOTNET_ (DOTNET_ENVIRONMENT).

However, when I run UPDATE-DATABASE from within Visual Studio Package Manager, it always uses the Production config.

If I run a command prompt, 
`dotnet ef database update`
it will properly obeys the DOTNET_ENVIRONMENT variable specified in the current shell.

I can't seem to get the package manager Update-Database to obey environmental configs. 

I know I can write my own DesignTimeFactory for the DBContext, and reinvent the wheel, but I'd rather not. This works correctly in ASPNETCORE architecture (UPDATE-DATABASE would honor the project settings Environment Variable on the Debug tab of the project properties) and I hope we can find a way for it to work in NETCORE architecture.

Thanks.

**Comment by ajcvickers** [comment] 2019-12-06 17:53
@foconnor-DS How are you setting the environment variable in the Package Manager Console?

**Comment by foconnor-DS** [comment] 2019-12-06 18:59
I don't set it in the Package Manager Console. In the past, it seems to have always used my startup project settings. In which case it would pull the Environmental variable from the Debug tab on the project properties.

**Comment by ajcvickers** [comment] 2019-12-07 00:47
@foconnor-DS Are you using `launchSettings.json`? (See #8695)

**Comment by foconnor-DS** [comment] 2019-12-13 17:39
@ajcvickers  sorry for the delay. Big deployment week. Yes, the launchsettings.json is configured ( not by me, VS2019 handles it automagically)

`
{
  "profiles": {
    "PersonicomNextGen.RenderBot": {
      "commandName": "Project",
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Development"
      }
    }
  }
}
`
Package Manager Console EF tooling was definitely not honoring that.

When I get some time I'l double check from a clean project/dev VM to make sure it isn't some oddball configuration issues.

**Comment by ajcvickers** [comment] 2019-12-13 17:47
Duplicate of #8695

**Closed** 2022-10-16 17:59 UTC
Labels: customer-reported
