### ISSUE TITLE
One to many plus One to One with same entity

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#29183] opened 2022-09-22 22:07 UTC
I'm having trouble working out if EF Core can do what I want. Basically I have defined a simple model, and queries seem to work, but when I try to insert the complete object graph in a single SaveChanges() call it fails. I can get the insert to work if I save changes first then update the nav property for the additional relationship, then save again.. but I can't do it all in one go.. let me explain..

I have two entities and rather than just a `one to many relationship` between them as is often the case, I have:

An `Office` can have many `Person`s, `Person`s must have an office (one to many)
An `Office` can also have one of those `Person`s be the important Office Person. (one to one)

I'm using different noun's here, but the basic need for this type of model arose because, where there are several million offices, ,and offices have several hundred people, being able to mark one of those people as the "special office person" - means either having a flag at the person level (and means removing the flag and setting it on another person each time the special person changes) or involves storing the id of the special person on the office record itself as a nullable FK relationship - which is the route I chose to go - because that should also make it easier to query - i.e join from office to the special people directly on Office.PersonId rather than joining to all people at the office (based on Person.OfficeId) then filtering for the one person that is marked as special (e.g so these are performance concerns)

Here is my fluent config for `Office`:

```csharp
 builder.HasMany(d => d.Persons) // office has persons (one to many)
              .WithOne(s => s.Office) 
              .HasForeignKey(a => a.OfficeId); 

            builder.HasOne(d => d.Person) // the one person that is special for this office.
              .WithOne() // must avoid using nav property in more than one relationship else ef throws.
              .HasForeignKey<Office>(a => a.PersonId);

```

```
public class Office
{
    public virtual int Id { get; set; }
    public virtual HashSet<Person> Persons { get; set; } = new HashSet<Person>();
    public Person? Person { get; set; }
    public int? PersonId { get; set; }    
}

public class Person
{
    public virtual int Id { get; set; }
    public int OfficeId { get; set; }
    public virtual Office Office { get; set; }
}

```

So the problem I have is that when I attempt to create  a new Office, new Person, and add that Person to the Office.Persons, as well as set that person as the Office.Person, then call SaveChanges() I get this:

```
System.InvalidOperationException : Unable to save changes because a circular dependency was detected in the data to be saved: 'Office { 'Id': -2147482647 } [Added] <-
Persons { 'OfficeId': -2147482647 } Person { 'Id': -2147482647 } [Added] <-
Person { 'PersonId': -2147482647 } Office { 'Id': -2147482647 } [Added]'.

  Stack Trace: 
Multigraph`2.ThrowCycle(List`1 cycle, Func`2 formatCycle, Func`2 formatException)
Multigraph`2.BatchingTopologicalSort(Func`4 tryBreakEdge, Func`2 formatCycle)
CommandBatchPreparer.TopologicalSort(IEnumerable`1 commands)
CommandBatchPreparer.BatchCommands(IList`1 entries, IUpdateAdapter updateAdapter)+MoveNext()
BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
RelationalDatabase.SaveChanges(IList`1 entries)
StateManager.SaveChanges(IList`1 entriesToSave)
StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
<>c.<SaveChanges>b__104_0(DbContext _, ValueTuple`2 t)
<>c__DisplayClass31_0`2.<Execute>b__0(DbContext context, TState state)
ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
BaseMultitenantDbContext`3.SaveChanges(Boolean acceptAllChangesOnSuccess) line 52
DbContext.SaveChanges()
```

I get the same error even if I remove the navigation property "Office" from the "Person" class. (keeping the relationships configured exactly the same just without the explicit navigation property).

I can work around this problem like so:

1. Create the office, and the person, and add the Person to Office.Persons but don't set Office.Person. Call SaveChanges() - this inserts the office and the person, but Office.PersonId remains null. Then set Office.Person and call SaveChanges() again. This time it works.

So there is a need for me to call SaveChanges twice. I'm trying to insert a large amount of Offices here, so after the initial SaveChanges I basically have to loop back through all the data to set this nav property then call SaveChanges again - its not ideal.

Is there a better way?

**Comment by ajcvickers** [comment] 2022-09-26 16:58
Duplicate of #1699

**Closed** 2022-09-30 11:31 UTC
Labels: closed-duplicate, customer-reported
