### ISSUE TITLE
Temp id is not replaced with permanent value after SaveChanges

### ISSUE THREAD

**Issue by blkcelebration** [dotnet/efcore#34309] opened 2024-07-29 11:35 UTC
Hi, 
I use EF CORE 8 , 
and I have an entity which has a PK ("Id") and a foreign key ("ParentId") within the same entity.
The primary key column Id is store-generated by the database.

```C#
class MyEntity
{

public int Id;
public int? ParentId;

MyEntity Parent;
ICollection<MyEntity> Children;

}

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<MyEntity>(entity =>
    {
        entity.HasKey(x => x.Id).ValueGeneratedOnAdd();
        entity.HasOne(x=> x.Parent)
            .WithMany(x=> x.Children)
            .HasForeignKey(x=> x.ParentId)
    });  
}
```

Since I have thousands of entities, I'm not calling SaveChanges() after each AddEntity and so, EF is using a temporary id to connect the entities, that should be replaced later on.

To achieve this I have to link the entity like this:

```C#
_context.MyEntity.Add(entity);
int tempId = _context.Entry(entity).Property(x=>x.Id).CurrentValue;
entity.ParentId = tempId; // set the FK in the same record
```

I pass the tempId parameter above to the FK field "ParentId" and after SaveChanges() it is successfully replaced with the permanent id in the added entity records.

But when the parent and child entities are same (parent of entity A is the same entity A) this doesn’t work, and the temporary id value (negative number) is persisted to the database (!).

Why doesn't it work and how can I fix it?

And also, is there an way to retrieve the temporary key without having to be coupled to the EF context ?  

i.e. accessing the myEntity.Id property rather than …Entry..Property().CurrentValue ?

### Include provider and version information

EF Core version: 8.0.7
Database provider:  Microsoft.EntityFrameworkCore.SqlServer)
Target framework: net 8.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.10

**Comment by ajcvickers** [comment] 2024-08-12 10:32
@blkcelebration The ID in the FK is updated not because it is temporary (as far as EF is concerned, it isn't because you set it) but because the PK is temporary, and when the PK gets a real value it is propagated to all associated FKs.

Can you explain why you need to do this manually, rather than letting EF do the temp value propagation to FKs automatically?

**Comment by ajcvickers** [comment] 2024-08-26 11:27
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-08-26 11:27 UTC
Labels: customer-reported, area-change-tracking
