### ISSUE TITLE
Cosmos: Fluent mapping of class PK using .ToJsonProperty("id") throw alternate key property 'id' is null exception

### ISSUE THREAD

**Issue by MedAnd** [dotnet/efcore#20654] opened 2020-04-16 02:52 UTC
Mapping a class property and primary key called "Id" of type string, to the internal CosmosDB "id" field and using the following fluent mapping:

![image](https://user-images.githubusercontent.com/13365135/79408516-e1717d80-7fde-11ea-846b-533ca81bcfc8.png)

throws an alternate key property 'id' is null exception.

_Unable to track an entity of type 'DeviceVerificationResponse' because alternate key property 'id' is null. If the alternate key is not used in a relationship, then consider using a unique index instead. Unique indexes may contain nulls, while alternate keys must not._

### Steps to reproduce

1. Create a fluent mapping as per above where DeviceVerificationResponse class has a string property called Id (primary key).
2. Calling AddAsync, Update etc via the DbContext throws the alternate key property 'id' is null exception

### Further technical details

EF Core version: Microsoft.EntityFrameworkCore 3.1.3
Database provider: Microsoft.EntityFrameworkCore.Cosmos 3.1.3
Target framework: netcoreapp3.1
Operating system: Visual Studio 2019 16.5.4

cc @AndriySvyryd @smitpatel

**Comment by AndriySvyryd** [comment] 2020-04-16 03:49
Duplicate of https://github.com/dotnet/efcore/issues/18428 and https://github.com/dotnet/efcore/issues/17751.

As a workaround rename the property to "id" and don't configure the partition key.

**Comment by MedAnd** [comment] 2020-04-16 03:56
@AndriySvyryd - just to clarify.... so the only workaround is to change the model (class property) to lowercase id and not configure a partition key? 

Does this mean the collection will not be partitioned or it will use the default /__partitionKey? Will this value be blank etc?

**Comment by AndriySvyryd** [comment] 2020-04-16 04:01
@MedAnd Yes, `__partitionKey` with [PartitionKey.None](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.partitionkey.none?view=azure-dotnet) will be used if you don't configure a partition key.

**Comment by MedAnd** [comment] 2020-04-16 04:51
@AndriySvyryd - for performance reasons we would need to partition the collections. Also another challenge with above workaround is that every model / class would need to have it's PK property renamed to lowercase id, which as you can imagine will pollute the domain.

So I guess in summary, we would like to use EF Core with CosmosDB however we want to:

1. map the model's PK property to "id" in CosmosDB (so as to avoid duplicate data)
2. partition collections
3. use migrations, at least InitialCreate (at a minimum create / delete collections & possibly life-cycle Stored Procedures, User Defined Functions, Triggers etc)

Could you clarify when / if above is on the EF Core road-map as these issues are major blockers?

Thank you!

**Comment by smitpatel** [comment] 2020-04-16 04:58
using id as partition key is worst for performance compared to no partition key.

**Comment by MedAnd** [comment] 2020-04-16 05:03
@smitpatel - roger 🙂 above is from a PoC... what I'm trying to asses is if EF Core and CosmosDB provider are ready for production use; we would like to use in a multi-tenant, Azure Functions e-commerce microservice.

PS. Happy to jump on a call if you need more context or detail?

**Comment by AndriySvyryd** [comment] 2020-04-16 05:10
> 1. map the model's PK property to "id" in CosmosDB (so as to avoid duplicate data)

EF also adds the discriminator to the `id` value to allow different entity types to be mapped to the same container, so it's best not to handle it explicitly.

>  2. partition collections

You can configure a partition key that's not the `id`

> 3. use migrations, at least InitialCreate (at a minimum create / delete collections & possibly life-cycle Stored Procedures, User Defined Functions, Triggers etc)

See https://github.com/dotnet/efcore/issues/11099

**Comment by MedAnd** [comment] 2020-04-16 05:43
@AndriySvyryd @smitpatel - the below mapping works however at the cost of having two fields "Id" and  "id" in the collection, with exactly the same value & hence this issue & my tweets 🙂

Still not clear if this is a limitation of EF Core / CosmosDB provider and if this is on your road-map? 
Moreover will #17751 resolve this issue, once implemented will we be able to map PK and for that matter composite PKs to the "id" field?

![image](https://user-images.githubusercontent.com/13365135/79418444-feff1100-7ff7-11ea-9f6e-e238ab50b697.png)

**Comment by AndriySvyryd** [comment] 2020-04-16 17:57
> Moreover will #17751 resolve this issue, once implemented will we be able to map PK

Yes

> and for that matter composite PKs to the "id" field?

You'd need something like https://github.com/dotnet/efcore/issues/13947 to define a conversion to parse out the `id` value to several properties.

**Closed** 2022-10-16 18:21 UTC
Labels: closed-duplicate, customer-reported
