### ISSUE TITLE
Scaffolding Changes Type Casing (e.g. ID -> Id)

### ISSUE THREAD

**Issue by rasikaw-is** [dotnet/efcore#6033] opened 2016-07-09 00:24 UTC
Hi everyone,

This is a possible bug report only, not 100% certain if it is. What is the best place to post discussion / question type posts on EF Core; is it here?

We were using ASP.NET Core RC1 with EF Core and are now migrating to the RTM release. When scaffolding using:

Scaffold-DbContext "server=(local);database=mydb;trusted_connection=true;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models

The generated code has for example 'SomeFieldId' rather than 'SomeFieldID', which is how to appears in the database. This issue was not there with the 'dnx ef dbcontext scaffold' command in RC1, which generated field names exactly as they appeared in the database. So not sure why it is happening in RTM with both 'Scaffold-DbContext' and 'dotnet ef dbcontext scaffold'. So the issue is that scaffolding generates code with incorrect casing, which does not work with the existing code (based on previously RC1 scaffolded EF code).

Tech Info:

"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0"
Windows 10 Pro
Visual Studio 2015 Update 3 and NET Core 1.0 for Visual Studio - DotNetCore.1.0.0-VS2015Tools.Preview2.

**Comment by lajones** [comment] 2016-07-11 16:21
Closing as dupe of #5947.

**Closed** 2022-10-16 09:50 UTC
Labels: closed-duplicate
