### ISSUE TITLE
BoolToStringConverter: inconsistent translation for where clause

### ISSUE THREAD

**Issue by ifgitman** [dotnet/efcore#18403] opened 2019-10-16 17:31 UTC
I am getting different SQL translations when using a bool field with BoolToStringConverter for Where expression:

When I write:
``` C#
var prueba = 
    await _ctx.Usuarios
        .Where(u => u.Habilitado == false)
        .ToListAsync();
```

I get this SQL:
``` C#
SELECT `u`.`id`, `u`.`habilitado`
FROM `usuarios` AS `u`
WHERE `u`.`habilitado` = 'N'
```

When I write:
``` C#
var prueba = 
    await _ctx.Usuarios
        .Where(u => !u.Habilitado)
        .ToListAsync();
```

I get:

``` C#
SELECT `u`.`orden`, `u`.`habilitado`
FROM `usuarios` AS `u`
WHERE NOT (`u`.`habilitado`)
```

### Further technical details

EF Core version: 3.0.0
Database provider: Pomelo.EntityFrameworkCore.MySql 3.0.0-rc1.final
Target framework: .NET Core 3.0
Operating system: Win 10 x64
IDE: Visual Studio 2019 16.3.3

**Comment by ajcvickers** [comment] 2019-10-18 17:51
@smitpatel to find duplicate.

**Comment by ajcvickers** [comment] 2019-10-18 17:53
Duplicate of #18147

**Closed** 2022-10-16 14:50 UTC
Labels: customer-reported
