### ISSUE TITLE
SqlQuery<TClass>(Type elementType, string sql, params object[] parameters) not supported in Ef core

### ISSUE THREAD

**Issue by vlapenkov** [dotnet/efcore#14063] opened 2018-12-03 14:53 UTC
I' m moving one large project from MVC5 to EF core.  
SqlQuery<SomeModel> **was extremely** useful in EF6 as i called stored procedured and didn't need store SomeModel as Entity in DbContext.
I'm trying to bypass it. 
If i use suggested way: public DbQuery<SomeModel> SomeModels { get; set; } it makes me store SomeModel in DAL assembly. It's very inconvenient as this model is  depending on  some services living in Services assembly.  So i have cross-reference between assemblies.

Please suggest anything

**Comment by Vasimovic** [comment] 2018-12-03 16:38
We face the same issue, many large projects using EF6 SqlQuery, having SqlQuery in EF Core would be great and solve a lot of issues for us.

**Comment by ajcvickers** [comment] 2018-12-03 18:38
Duplicate of #10753

**Comment by Vasimovic** [comment] 2018-12-05 19:14
@ajcvickers I think what some of us are looking for is an equivalent to the SqlQuery<T> that we had in EF 6; 

#10753 does not solve the issues because of DbQuery complaining that Query types cannot have keys. While all my complex read-only view models are annotated with the [Key] attribute, removing them would not be trivial and practical because sometimes the models are used by DbSet and sometimes by DbQuery

#1862 is closed but does not actually solve the issue (Raw store access APIs: Support for ad hoc mapping of arbitrary types)

I am hoping an equivalent functionality (SqlQuery<T>) is brought back, or, allow the [Key] attributes to exist in a model for Query types.

**Comment by ajcvickers** [comment] 2018-12-12 21:49
Added a note to #10753 to consider the case of multiple mappings for the same CLR type.

**Closed** 2022-10-16 13:42 UTC
Labels: closed-duplicate, customer-reported
