### ISSUE TITLE
Undoing migration results in exception

### ISSUE THREAD

**Issue by taori** [dotnet/efcore#18129] opened 2019-09-29 14:08 UTC
![grafik](https://user-images.githubusercontent.com/5545184/65833697-3532a880-e2d3-11e9-8882-ea01fd3a3f16.png)

### Steps to reproduce
See screenshot

### Further technical details

EF Core version:
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (.NET Core 3.0)
Operating system:
IDE: (Visual Studio 2019 16.3.1)
executed from console

**Comment by smitpatel** [comment] 2019-09-29 16:23
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by taori** [comment] 2019-09-29 18:05
ok. I'll try

**Comment by bricelam** [comment] 2019-10-02 18:22
Possible duplicate of #18178

**Comment by ajcvickers** [comment] 2019-10-06 20:02
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:46 UTC
Labels: customer-reported
