### ISSUE TITLE
EF Core returns NULL for an object with NULL scalar properties but with NOT NULL complex types properties

### ISSUE THREAD

**Issue by alvorteg** [dotnet/efcore#24399] opened 2021-03-15 10:35 UTC
### Steps to reproduce

If you have these classes:
```
public class Class1 {

public string Identifier{ get; set; }
public Class2 Child { get; set; }

}

public class Class2 {
public string Name { get; set; }
public Class3 Surnames { get; set; }
}

public class Class3 {

public string Surname1 { get; set; }
public string Surname2 {get; set; }
}
```
Modeled with EF Core as follows:

```
  modelBuilder.Entity<Class1>().HasKey(t => t.Identifier);
  modelBuilder.Entity<Class1>().OwnsOne(_ => _.Child).Property(_ => _.Name).IsRequired(false);
  modelBuilder.Entity<Class1>().OwnsOne(_ => _.Child).OwnsOne(_ => _.Surnames);

```
Now you insert an object with these values:
```
{
    "Class1": {
        "Identifier": "TESTID",
        "Child": {
            "Name": null,
            "Surnames": {
                "Surname1": "SUR1",
                "Surname2": "SUR2"
            }
        }
    }
}
```

### Actual behaviour

When getting object via DbContext, you receive this object:

```
{
    "Class1": {
        "Identifier": "TESTID",
        "Child": null
    }
}
```
### Expected behaviour

```
{
    "Class1": {
        "Identifier": "TESTID",
        "Child": {
            "Name": null,
            "Surnames": {
                "Surname1": "SUR1",
                "Surname2": "SUR2"
            }
        }
    }
}
```

### Include provider and version information

EF Core version: 5.0.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.0

**Comment by smitpatel** [comment] 2021-03-15 16:18
Duplicate of #23564

**Closed** 2022-10-16 19:27 UTC
Labels: closed-duplicate, customer-reported
