### ISSUE TITLE
Including sequentially two derived properties causes error "Unable to cast object of type X to type Y"

### ISSUE THREAD

**Issue by alexandis** [dotnet/efcore#21309] opened 2020-06-17 12:40 UTC
I have two entities that differ with HasDiscriminator only:

           public class ModuleType : GeneralEntity
            {
                public ModuleType() {}
            }

            public class Owner : GeneralEntity
            {
                public Owner() {}
            }

            builder.Entity<Owner>(b =>
            {
                b.HasDiscriminator(x => x.Field).HasValue<Owner>(FieldTypes.Owner);
            });

            builder.Entity<ModuleType>(b =>
            {
                b.HasDiscriminator(x => x.Field).HasValue<ModuleType>(FieldTypes.Module);
            });

When I use the following query

`DbSet.Include(m => m.ModuleType).Include(m => m.Owner)`

it fails:

> Unable to cast object of type 'XXX.ModuleType' to type 'XXX.Owner'.
> System.InvalidCastException: Unable to cast object of type 'XXX.ModuleType' to type 'XXX.Owner'

The generated SQL query itself is correct.

**Comment by ajcvickers** [comment] 2020-06-17 15:33
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-06-29 14:56
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:29 UTC
Labels: closed-could-not-reproduce, customer-reported
