### ISSUE TITLE
Refer to Enable Detailed Errors in Exception Messages

### ISSUE THREAD

**Issue by markolbert** [dotnet/efcore#33222] opened 2024-03-02 18:59 UTC
A small change in the content of at least some exception messages would make life much easier for developers not super familiar with EF Core: suggest enabling detailed errors.

That's already done in some/many cases. But in the case of at least one error (described below), it's not.

The specific exception I ran into is something along the lines of "data is null". It popped up because a string field was specified in the schema as being required but was erroneously assigned the value null.

Unfortunately, the exception only manifested itself when I tried to do an Include() from one table to another (the field causing the problem was the target of the relationship I was including). 

Worse yet, testing the Include() on the DbContext used to load the erroneous null values worked (i.e., I was able to retrieve the related entity). It was only when I created a different DbContext, on the same SQL Server database, that the Include() failed. Needless to say, that's a hair-puller :).

**Comment by ajcvickers** [comment] 2024-03-03 11:29
Duplicate of #30397

**Closed** 2024-03-06 19:55 UTC
Labels: customer-reported
