### ISSUE TITLE
Behaviour of bool fields with HasDefaultValue option

### ISSUE THREAD

**Issue by crabulik** [dotnet/efcore#6054] opened 2016-07-12 15:11 UTC
Hi. I need to clear such situation.
I have an entity Product with bool field:

`public bool IsActive{ get; set; }`

For that field I made such definition in my DbCOntext:

`protected override void OnModelCreating(ModelBuilder modelBuilder)
 {
            modelBuilder.Entity<Product>()
                .Property(b => b.IsActive)
                .HasDefaultValue(true);
 }`

So, if I insert the Product with "IsActive=false", the record wor this Product in DB will contain "IsActive=true".

Is it correct EF behaviour? 

Because in documentation it says:

> The default value of a column is the value that will be inserted if a new row is inserted but no value is specified for the column.

Because I think that "IsActive=false" is a specified value.

**Comment by divega** [comment] 2016-11-23 02:48
Reopening to consider adding a model validation that errors or warns when this scenario is hit.

**Comment by divega** [comment] 2016-11-23 23:16
There seems to be more useful information and discussion now in #7089 so closing this issue as a dupe of that one.

**Comment by Linnod** [comment] 2019-04-05 15:50
Hello!

This problem is still actual. If there's code like `builder.Property(x => x.IsActive).HasColumnName("IsActive").HasDefaultValue(true);` in entity's configuration and IsActive value equals TRUE, EF does not generate insert for this column.

Thank you!

**Comment by m4ss1m0g** [comment] 2020-01-02 15:41
I found a solution from [stackoverflow post](https://stackoverflow.com/questions/38570246/how-to-set-another-value-on-a-boolean-with-defaut-value-with-entity-framework-co) for **REQUIRED** boolean field and default value

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
        modelBuilder.Entity<MyEntity>()
             .Property(p => p.MyRequiredBooleanField)
             .ValueGeneratedNever()
             .HasDefaultValue(false);
}
```

Ref

**Closed** 2022-10-16 09:50 UTC
Labels: closed-duplicate
