### ISSUE TITLE
Support for Cosmos Db Hierarchical Partition Keys

### ISSUE THREAD

**Issue by ericpaulblankenburg** [dotnet/efcore#31403] opened 2023-08-02 19:03 UTC
Cosmos Db hierarchical partition keys have been released. This feature is absolutely critical for a project I am starting. But I haven't heard any mention of whether or not Entity Framework Core 8 will support it. Is support coming?

**Comment by ajcvickers** [comment] 2023-08-02 19:25
Duplicate of #28186

**Closed** 2023-08-02 19:25 UTC
Labels: closed-duplicate, customer-reported
