### ISSUE TITLE
BeginExecuteReader requires an open and available Connection. The connection's current state is open.

### ISSUE THREAD

**Issue by JeanCollas** [dotnet/efcore#12447] opened 2018-06-21 19:58 UTC
How is this possible?

```
BeginExecuteReader requires an open and available Connection. The connection's current state is open.
----------------
at System.Data.SqlClient.SqlCommand.<>c.b__122_0(Task`1 result)
at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.FastQueryAsyncEnumerable`1.FastQueryAsyncEnumerator.MoveNext(CancellationToken cancellationToken)
at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
```

The caller is 
```
await (from t in DbContext.PlaceAttributes where t.PlaceId == placeId select t).AsNoTracking().ToListAsync();
```

**Comment by JeanCollas** [comment] 2018-06-22 12:09
Unfortunately the project is probably too complex to share, and the issue does not happen every times, it is random, only a few % of request have this issue.

**Comment by ajcvickers** [comment] 2018-06-22 16:41
@JeanCollas I have seen this before when multiple threads are using the same DbContext/DbConnection instance concurrently. Both DbContext and DbConnection and other related classes are not thread safe.

**Comment by ralmsdeveloper** [comment] 2018-06-22 18:07
@ajcvickers
I do not know if it is useful for you, but I had something identical and solved only with **MultipleActiveResultSets =True** in my connection string

**Comment by JeanCollas** [comment] 2018-06-22 20:31
Thanks, the DbContext is created in the same thread of the execution (it is something like `using(new DbContext(dbOptions) `). 
However I will check if the concerned connection have the MultipleResultSets activated. :)

**Comment by ajcvickers** [comment] 2018-06-25 17:59
@ralmsdeveloper @JeanCollas Setting MultipleActiveResultSets should not resolve this intentionally. It's likely that it is masking a bug in your app code.

**Comment by ajcvickers** [comment] 2018-06-29 18:00
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by TPIvan** [comment] 2022-09-30 10:41
I had the same issue and it was caused by using 
`public async void OnGet()`
instead of 
`public async Task OnGet()`

**Closed** 2022-10-16 13:15 UTC
Labels: closed-could-not-reproduce, customer-reported

**Comment by alex-belikov** [comment] 2023-11-20 13:28
I had this issue and I was able to figure it out for my case. It was not related to Entity Framework for me. Here's my code with an issue:
`    protected SqlConnection Conn()
    {
        if (_conn != null) return _conn;

        lock (_lockObject)
        {
            if (_conn != null) return _conn;

            SqlMapper.AddTypeMap(typeof(DateTime), DbType.DateTime2);
            _conn = new SqlConnection(_connectionString);
            _conn.Open();
            return _conn;
        }
    }`

It might be called by multiple concurrent threads. While first thread was trying to .Open() the connection, the _conn field was already not null. So other threads were using this connection at a time when it was not yet fully opened.

As a solution, I started setting a reference into _conn field when connection is opened, like this:
`    protected SqlConnection Conn()
    {
        if (_conn != null) return _conn;

        lock (_lockObject)
        {
            if (_conn != null) return _conn;

            SqlMapper.AddTypeMap(typeof(DateTime), DbType.DateTime2);
            var conn = new SqlConnection(_connectionString);
            conn.Open();
            return _conn = conn;
        }
    }`
Hope it helps.

**Comment by csstreiser** [comment] 2024-10-16 15:17
> I had the same issue and it was caused by using `public async void OnGet()` instead of `public async Task OnGet()`

Bless you! this solved my problem
