### ISSUE TITLE
Add-Migration hangs after build succeeds in VS 2019 and VS 2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#29083] opened 2022-09-14 07:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-Migration-hangs-after-build-succeeds/10138668)._

---
[severity:Other]
After creating a new ASP.NET Core Blazor Server project and added a db context.  I added several code first model files and the db sets to the db context.  In the package manager console, I ran Add-Migration.  

The results were build started... build succeeded.  Then nothing else.  It just hangs, no errors, nothing.  I waited an hour and still nothing.  I attempted this in VS 2019 and VS 2022 17.3.3

---
#### Sam Boustani on 9/3/2022, 07:32 PM: 

(private comment, text removed)
#### Feedback Bot on 9/5/2022, 02:52 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2022-09-14 07:39
Can you post your csproj file?

**Comment by qsdfplkj** [comment] 2022-09-16 13:53
If you run it from the command line `dotnet ef..`  maybe it will show you what's wrong.
I had a similar thing...  it's has something to do with security options for me adding Encrypt=False; to the connection string helped me working around this...

**Comment by ajcvickers** [comment] 2022-09-21 18:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-09-21 18:42 UTC
