### ISSUE TITLE
AddMigration doesn't create all indexes when using different filters or names

### ISSUE THREAD

**Issue by cornem** [dotnet/efcore#18159] opened 2019-10-01 07:43 UTC
When you define multiple indexes for an entity over the same columns but with a different filter expression and/or name, EF will only create a migration statement for the last one.

### Steps to reproduce
Create a project with this model:

``` C#
public class State
{
    public Guid Id { get; set; }

    public DateTime LastModified { get; set; } = DateTime.UtcNow;

    public int? CustomerId { get; set; }

    public int? ItemId { get; set; }

    public int? ItemGroupId { get; set; }

    [Required, StringLength(450)]
    public string RemoteId { get; set; }
}

public class StateDbContext : DbContext
{
    public DbSet<State> State { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<State>(s =>
        {
            s.HasIndex("RemoteId")
                .HasFilter("CustomerId IS NOT NULL")
                .HasName("IX_State_RemoteId_CustomerId")
                .IsUnique();

            s.HasIndex("RemoteId")
                .HasFilter("ItemId IS NOT NULL")
                .HasName("IX_State_RemoteId_ItemId")
                .IsUnique();

            s.HasIndex("RemoteId")
                .HasFilter("ItemGroupId IS NOT NULL")
                .HasName("IX_State_RemoteId_ItemGroupId")
                .IsUnique();
        });
    }
}
```

- Notice that even though the index uses the same property `RemoteId`, the name and filter for each index is different (I can create such indexes on SQL server with T-SQL)
- Add a migration: `dotnet ef migrations add CreateInitialSchema`
- Notice that the generated migration only contains the index `IX_State_RemoteId_ItemGroupId`.

### Further technical details

EF Core version: both 2.* and 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: netcoreapp2.2 / netcoreapp3.0
Operating system: Windows 10
IDE: N/A

**Comment by bricelam** [comment] 2019-10-02 18:33
This is a limitation in our Fluent API. `s.HasIndex("RemoteId")` will get or add the single index covering that property. Subsequent calls to HasFilter and HasName are overriding the configuration for that index.

@AndriySvyryd Can you work around this by dropping down to Metadata? Do we have an issue on our backlog about addressing indexes by name in the fluent API?

**Comment by AndriySvyryd** [comment] 2019-10-02 18:37
There is no way of doing this in Metadata.
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/4150

**Comment by bricelam** [comment] 2019-10-02 18:57
Note, you can manually add the indexes by adding calls to `migrationBuilder.CreateIndex()` inside a migration.

**Closed** 2022-10-16 14:46 UTC
Labels: customer-reported
