### ISSUE TITLE
InMemory PrimaryKeyGeneration creating duplicates for different contexts with the same databaseName and databaseRoot

### ISSUE THREAD

**Issue by foz1284** [dotnet/efcore#15086] opened 2019-03-20 11:32 UTC
I have described the issue initially here:
https://github.com/aspnet/EntityFramework.Docs/issues/1374

When adding a second entity from the inherited class when a first entity was created in the base class gives the following error since the ID of the entity being added is being set to 1 which already exists:

```
Exception message:
System.InvalidOperationException: 'The instance of entity type 'OperationsSchedule' cannot be tracked because another instance with the same key value for {'OperationsScheduleID'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.'
Stack trace:
```

### Steps to reproduce

https://github.com/foz1284/EntityFrameworkInMemoryInheritanceTest

### Further technical details
EF Core version: 2.2.3
Database Provider: InMemory
Operating system: Windows10
IDE: Visual Studio 2017 15.9.7

**Comment by ajcvickers** [comment] 2019-03-25 21:28
@foz1284 The issue with duplicate IDs is a duplicate of #14646 which is fixed for 3.0. However, I doubt that this will work even with that fix because the two contexts are using different models. (It's possibly it could work if the inherited context creates the in-memory database and the base context just uses it, but it still wouldn't be recommended.)

Leaving open to discuss with the team if this is something it makes sense to support.

**Comment by foz1284** [comment] 2019-03-25 21:52
Hi Arthur, thanks for the reply, sorry I didn't spot the duplicate, 

I had a feeling this may have been fixed as I built from source on Saturday to try and reproduce and possibly fix but the test worked successfully(It wasn't working on the nuget beta), I hadn't done enough testing to comment back on here, sorry this is my first time attempting to contribute to a high profile project in any way!

Would you be able to explain why this may not be recommended? Inheriting the context allows me to have a core database and be flexible where my customers that have specific extensions?

This is also working for me with SQL Server.

Thanks

**Comment by ajcvickers** [comment] 2019-03-25 22:13
@foz1284 Because the shape of the in-memory database is copied from the model and is implemented in terms of the model. For example, accessing a property is done through the index of that property in the EF model. For this to work with multiple models in a realizable way would require that the the in-memory database have an extra layer which abstracts the EF model from some less tightly coupled lower layer.

Have you considered using SQLite? It supports an in-memory mode that is closer to a real relational database.

**Comment by foz1284** [comment] 2019-03-25 22:27
Thanks for the explanation, 

I'd seen the SQLite in memory mode but not spent any time evaluating as in memory was working fine for me before I refactored for inheritance last week, I will look into this option.

**Comment by ajcvickers** [comment] 2019-03-29 18:51
We discussed this in triage and decided that this would be a major change for the in-memory provider and compared to other things we could do does not provide enough value. SQLite (or another database with in-memory support) is the way to go here.

**Closed** 2022-10-16 13:56 UTC
Labels: closed-out-of-scope, customer-reported
