### ISSUE TITLE
The instance of entity type "Rmt" cannot be tracked because another instance with the same key value for {Id} is already being tracked. When attaching existing entities,  ensure that only one entity instance with a given key value is attached. Consider using DbContextOptionsBuilder.EnableSensitiveDataLogging; to see the conflicting key values.

### ISSUE THREAD

**Issue by richof** [dotnet/efcore#13459] opened 2018-10-01 20:35 UTC
I have 3 process inside a method,  first two of them call create methpod from repository, the trhid and fourth ones update the entities that has been recently created in db.

 ```
BeginTransaction();
                var exc = _mtmService.Remove();
               Commit(); //create
 BeginTransaction();
                var poc = _mtmService.Import();
               Commit();//create
BeginTransaction();
                var pocDel = _mtmService.HanddleAndUpdate(); // this method  update some properties from each entity inside a foreach and call Update Method wich turns entity into EntityState.Modified state.
               Commit();//update heres the problem
```

______________________________________________________

Commit just call dbContext.SaveChanges() method

```
The instance of entity type "Rmt" cannot be tracked because another instance with the same key value for {e87fbc31-06c9-4c29-af17-d91413f59fdb} is already being tracked. When attaching existing entities, 
ensure that only one entity instance with a given key value is attached. Consider using "DbContextOptionsBuilder.EnableSensitiveDataLogging" to see the conflicting key values.

```
 "Microsoft.EntityFrameworkCore" Version="2.1.3" 
Thanks in advance

**Comment by ajcvickers** [comment] 2018-10-08 17:39
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:33 UTC
Labels: closed-could-not-reproduce, customer-reported
