### ISSUE TITLE
Trying to drop the 'Discriminator' column even if it doesn't exist when migration

### ISSUE THREAD

**Issue by kion-admin** [dotnet/efcore#20410] opened 2020-03-25 18:19 UTC
Hello,

I will try to explain problem.

When i run add-migration its add migration file and snapshot file after i run add-migration again then  intead of create empty migration file its add some codes like below

```C#
protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Discriminator",
                schema: "usertask",
                table: "UserTasks");

            migrationBuilder.DropColumn(
                name: "Discriminator",
                schema: "usertask",
                table: "UserTaskHistory");
        }
```

When i research first migration file and snapshot file, i see migration file correct but snapshot file have that  `b.HasDiscriminator();` with releated entity

My entities and config like below. Important `=> builder.HasBaseType((Type)null);`

```C#
modelBuilder.Entity<UserTaskHistory>(builder =>
            {
            builder.HasBaseType((Type)null);
            builder.Ignore("Id");
            builder.HasKey(p => p.LogId);
            builder.Property("Id").HasColumnName("EntityId");
            });

    public class UserTaskHistory : UserTask, IHistoryTable
    {
        public Guid LogId { get; set; }
        public string EntityState { get; set; }
        public DateTime EntityOperationDate { get; set; }
    }

public class UserTask : FullAuditedAggregateRoot<Guid>, IMayHaveTenant, IHaveHistoryTable<UserTaskHistory>
    {
        public int? TenantId { get; set; }

        public long UserId { get; protected set; }
        public User User { get; protected set; }

        public string Title { get; protected set; }

        public virtual string Description { get; protected set; }

        public DateTime? ReminderDate { get; protected set; }
}
```

**Comment by ajcvickers** [comment] 2020-03-26 16:29
@kion-admin In this code:

```C#
builder.Ignore("Id");
builder.Property("Id").HasColumnName("EntityId");
```

Trying to both ignore and map the same property seems wrong. What is your intention here?

**Comment by kion-admin** [comment] 2020-03-26 23:09
Thanks for answer.

UserTaskHistory > UserTask > FullAuditedAggregateRoot(abstract class and have Id property)

Why i ignore Id and after replace it, because Id property coming from UserTask(PK) class
But i dont want it to make PK in my UserTaskHistory class. Because of that first i ignored it after added again and its worked with new columnname.

Everythink work nice just i have problem about migrations, with this way i simulating System-Versioned Temporal Table with override savechanges method in dbcontext class

**Comment by kion-admin** [comment] 2020-03-26 23:17
@ajcvickers 

i updated like below but still same problem

            var keys = builder.Metadata.GetKeys().ToList();
            foreach (var key in keys)
            {
                builder.Metadata.RemoveKey(key);
            }
            builder.Property("Id").HasColumnName("EntityId");
            builder.HasKey(p => p.LogId);

**Comment by ajcvickers** [comment] 2020-04-01 14:53
@kion-admin I have not been able to reproduce this, but that’s probably because I don’t have the exact shape of the model. Please attach a small, runnable project or post a small, runnable cost listing that reproduces the behavior you are seeing so that we can investigate.

Also, new configuration on the model builder overrides any existing configuration. It’s very unusual to have to manually manipulate FKs like this.

**Comment by kion-admin** [comment] 2020-04-01 18:47
Hello

I prepared a sample, just write add-migration twice

[efcoretest.zip](https://github.com/dotnet/efcore/files/4417042/efcoretest.zip)

**Comment by ErroneousFatality** [comment] 2020-04-28 03:27
I've run into the same issue. I'll try to simplify and explain my model.

I have two cases of inheritance which rely one on another.

```
abstract PaymentDetails (bunch of strings)
   -> StandardPaymentDetails (adds Id key property)
   -> CustomPaymentDetails (adds no additional properties to base class)
```

```
abstract PaymentOrder (has a PaymentDetails property)
   -> StandardPaymentOrder (has a StandardPaymentDetailsId foreign key property)
   -> CustomPaymentOrder (adds no additional properties to base class)
```

I want to have a table for `StandardPaymentDetails`, because each row of data will be very reusable by many `StandardPaymentOrder` rows.
I don't want a table for `CustomPaymentDetails`, since each row will belong exactly to one row of `CustomPaymentOrder`.
So I made it so that the table `CustomPaymentOrder` stores the data of `CustomPaymentDetails` in itself.

Here's the simplified DbContext implementation:
```
class Context : DbContext
{
    public DbSet<StandardPaymentDetails> StandardPaymentDetails { get; set; }

    public DbSet<PaymentOrder> PaymentOrders { get; set; }
    public DbSet<StandardPaymentOrder> StandardPaymentOrders { get; set; }
    public DbSet<CustomPaymentOrder> CustomPaymentOrders { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Ignore<PaymentDetails>();
        modelBuilder.Entity<StandardPaymentDetails>(
            (EntityTypeBuilder<StandardPaymentDetails> builder) =>
            {
                builder.HasMany(e => e.StandardPaymentOrders)
                    .WithOne((StandardPaymentOrder standardPaymentOrder) => (StandardPaymentDetails)standardPaymentOrder.PaymentDetails)
                    .HasForeignKey((StandardPaymentOrder standardPaymentOrder) => standardPaymentOrder.StandardPaymentDetailsId)
                    .IsRequired()
                    .OnDelete(DeleteBehavior.Restrict);
            }
        );

        modelBuilder.Entity<PaymentOrder>(
            (EntityTypeBuilder<PaymentOrder> builder) =>
            {
                builder.HasDiscriminator<PaymentOrderType>(_paymentOrder => _paymentOrder.Type)
                    .HasValue<StandardPaymentOrder>(PaymentOrderType.Standard)
                    .HasValue<CustomPaymentOrder>(PaymentOrderType.Custom);
            }
        );
        modelBuilder.Entity<StandardPaymentOrder>(
            (EntityTypeBuilder<StandardPaymentOrder> builder) =>
            {
                builder.HasOne<StandardPaymentDetails>(e => (StandardPaymentDetails)e.PaymentDetails)
                    .WithMany((StandardPaymentDetails standardPaymentDetails) => standardPaymentDetails.StandardPaymentOrders)
                    .HasForeignKey(e => e.StandardPaymentDetailsId)
                    .IsRequired()
                    .OnDelete(DeleteBehavior.Restrict);
            }
        );
        modelBuilder.Entity<CustomPaymentOrder>(
            (EntityTypeBuilder<CustomPaymentOrder> builder) =>
            {
                builder.OwnsOne<CustomPaymentDetails>(
                    e => (CustomPaymentDetails)e.PaymentDetails, 
                    (OwnedNavigationBuilder<CustomPaymentOrder, CustomPaymentDetails> buildAction) => 
                    {
                        buildAction.ToTable($"{nameof(PaymentOrder)}s");
                    }
                );
            }
        );
    }
}
```

The initial migration is generated perfectly.

There are two tables: 

`StandardPaymentDetails`, containing all properties from the `PaymentDetails` abstract class, and one additional property for its key value.

`PaymentOrders`, containing all the properties of the `PaymentOrder` abstract class, a Discriminator field, and all the nullable properties from both `StandardPaymentOrder` and `CustomPaymentOrder`, including the properties for `CustomPaymentDetails` which belong to the `CustomPaymentOrder`.

But, every migration after the initial, regardless if it has anything to do with these classes or not, always adds the following code in the `Up` method:
```
migrationBuilder.DropColumn(
    name: "Discriminator",
    table: "StandardPaymentDetails");
```

**Comment by edlut** [comment] 2020-06-05 19:39
Has anyone found a solution for this problem? I have got the same problem

**Comment by sNakiex** [comment] 2020-06-09 13:23
I have the same problem. 

Seems to happen when you are extending models, a fix for this issue is much appreciated.

**Comment by AndriySvyryd** [comment] 2020-07-23 01:33
I am not able to repro this.

@kion-admin @ErroneousFatality @edlut @sNakiex Can you still repro this using a [daily build](https://github.com/dotnet/aspnetcore/blob/master/docs/DailyBuilds.md)?
If so please post a small compilable project and I'll reopen the issue

**Closed by AndriySvyryd** 2020-07-23 01:33 UTC
Labels: area-model-building, customer-reported, poachable, type-bug

**Comment by agrothe** [comment] 2021-01-28 15:22
For anyone getting here via google:

I had this issue (.net core 3.1.5) where an Entity "Application" was being included from a shared library. I needed to modify it and created a new OpApplication entity. 

Adding this line created the issue of always getting the Drop Column Discriminator:

` builder.Ignore<Application>();`

Adding this fixes it.

```
builder.Entity<OpApplication>(entity => {
    entity.HasDiscriminator(x => x.Id);
});
```
