### ISSUE TITLE
Support map property to view and ignore it on table

### ISSUE THREAD

**Issue by CoreDX9** [dotnet/efcore#34147] opened 2024-07-03 06:55 UTC
I have a computed property using other table as data source, so I can't use computed column. Now I use view to compute value, but I can't ignore property mapping from table. So I map the property to computed column using dummy value generation sql now. Can EF Core support to configure table and view separately like below.

``` csharp
entityBuilder
    .ToTable(
        tableName,
        tableBuilder =>
            tableBuilder
                .Property(propertyName)
                .IsReadOnlyAndComputedOnDatabase()
                .IgnoreMappingToColumn()
     )
    .ToView(
        viewName,
        viewBuilder =>
            viewBuilder
                .Property(propertyName)
                .SomeConfigure()
    );
```

**Comment by AndriySvyryd** [comment] 2024-07-03 23:35
This is essentially a duplicate of https://github.com/dotnet/efcore/issues/14121

For now, the closest would be to configure it with:

```C#
var property = entityBuilder.Property(propertyName).Metadata;
property.SetBeforeSaveBehavior(PropertySaveBehavior.Ignore)
property.SetAfterSaveBehavior(PropertySaveBehavior.Ignore)
```

**Closed by AndriySvyryd** 2024-07-03 23:35 UTC
Labels: type-enhancement, customer-reported
