### ISSUE TITLE
IncludeFilter

### ISSUE THREAD

**Issue by amrrizk95** [dotnet/efcore#24729] opened 2021-04-22 16:22 UTC
i want to add function for filter included data

**Comment by roji** [comment] 2021-04-22 20:57
@amrrizk95 you're going to have to provider more information for us to understand exactly what you want to do. If you're looking for the filtered includes feature, the documentation can be found [here](https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include).

**Comment by ajcvickers** [comment] 2021-04-29 15:00
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:32 UTC
Labels: closed-no-further-action, customer-reported
