### ISSUE TITLE
GroupBy-Aggregate should use grouping key as identifier column

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#22892] opened 2020-10-05 20:05 UTC
Repro here https://github.com/dotnet/efcore/issues/22805#issuecomment-702893774

Each row in groupby-aggregate can uniquely identify using grouping key.

**Comment by AndriySvyryd** [comment] 2020-10-09 17:36
@maumar Dedupe if necessary.

**Comment by maumar** [comment] 2021-05-05 20:20
dupe of #22049

**Closed** 2022-10-16 19:03 UTC
Labels: area-query
