### ISSUE TITLE
Query: Can you scaffold directly against Sql Db Project

### ISSUE THREAD

**Issue by rposener** [dotnet/efcore#10837] opened 2018-01-31 17:07 UTC
We have a large database project that we use to manage the SQL Database.  Currently we have to do a deploy with special options like make sure it removes all extra tables, etc. before we can scaffold.  Could a scaffold process not be created to scaffold directly from the dacpac project instead of having to jump through the hoops of deploying to SQL then scaffolding back to our C# project?

**Comment by ErikEJ** [comment] 2018-01-31 20:01
Yes, potentially you could implement you own IDatabaseModelFactory and use DacFX to generate it. 

https://the.agilesql.club/Blogs/Ed-Elliott/DacFx-Create-tSQLt-Tests-From-A-Dacpac

https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs

Would make a nice addition to "EF Core Power Tools"! (of course also a lib/command line tool)

**Comment by bricelam** [comment] 2018-02-01 00:04
Duplicate of #4321

**Comment by bricelam** [comment] 2018-02-01 00:10
@ErikEJ is correct.

The end-to-end experience could look something like this:
```
dotnet install package EFCore.SqlServer.Dacpac
dotnet ef dbcontext scaffold ..\TheDatabase\bin\Debug\TheDatabase.dacpac EFCore.SqlServer.Dacpac
```

**Comment by bricelam** [comment] 2018-02-01 00:14
Where EFCore.SqlServer.Dacpac would basically use all the services directly from Microsoft.EntityFrameworkCore.SqlServer but replace the `IDatabaseModelFactory`.

**Comment by ErikEJ** [comment] 2018-02-01 10:01
Currently Windows only, though

**Comment by ErikEJ** [comment] 2018-02-05 15:56
@rposener This feature is now available in the latest daily build of "EF Core Power Tools" https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools

**Comment by ErikEJ** [comment] 2018-03-09 18:27
Is this syntax also possible with PMC, and if yes, what does it look like:

    dotnet ef dbcontext scaffold ..\TheDatabase\bin\Debug\TheDatabase.dacpac EFCore.SqlServer.Dacpac

**Comment by bricelam** [comment] 2018-03-09 18:53
Should just be...
``` ps1
Scaffold-DbContext ..\TheDatabase\bin\Debug\TheDatabase.dacpac EFCore.SqlServer.Dacpac
```

**Comment by bricelam** [comment] 2018-03-09 18:54
The relative path is weird though. It's probably relative to the target project, not the current directory.

**Comment by ErikEJ** [comment] 2018-03-09 19:37
I Will document a full path!

**Comment by bricelam** [comment] 2018-03-09 20:11
It's a similar issue to #10036, but probably requires a different solution since yours is inside a `connectionString`.

**Closed** 2022-10-16 12:07 UTC
Labels: closed-duplicate
