### ISSUE TITLE
Why does EF Core try to create objects that are not present in the class? REOPEN

### ISSUE THREAD

**Issue by carumsoft** [dotnet/efcore#32101] opened 2023-10-19 21:49 UTC
I would like to reopen the issue https://github.com/dotnet/efcore/issues/30636.

I've prepared a project with the problem. 
[ConsoleApp4.zip](https://github.com/dotnet/efcore/files/13048028/ConsoleApp4.zip)

My classes:
```C#
public abstract class UserBase : Entity
{
    public string Name { get; set; }
}

public class UserA : UserBase
{
    public UserSymbol UserSymbol { get; set; }
}

public class UserB : UserBase
{

}

public record UserSymbol
    {
        public string Text { get; init; }
        public UserSymbol(string text)
        {
            if (text is null)
            {
                throw new ArgumentNullException(nameof(text));
            }

            Text = text;
        }
    }
```

My data in sqlLite database:
id | Name | Discriminator | UserSymbol_Text
1 | user b | UserB | null

Execution:
```C#
var list = ERPContext.UserBases.ToList();
```

THE PROBLEM:
![obraz](https://user-images.githubusercontent.com/103263820/230134684-8cb9d828-ec2b-4d0f-a54f-a079b53f5d14.png)

Why EF is creating UserSymbol object for UserB object? There is no UserSymbol in UserB  class.

**Comment by ajcvickers** [comment] 2023-10-23 15:03
Duplicate of #31353

**Closed** 2023-10-25 18:22 UTC
Labels: closed-duplicate, customer-reported
