### ISSUE TITLE
value of fileParts[0] not present in the SQL query

### ISSUE THREAD

**Issue by Ronan-Farrell** [dotnet/efcore#11679] opened 2018-04-15 10:54 UTC
The following two bits of code in this screenshot:

![image](https://user-images.githubusercontent.com/13832903/38777623-24a8723e-40a3-11e8-868a-c23b3b8af0b5.png)

With fileParts[0], the query executed against the database does not include docNo in the where clause and instead returns ALL records matching on Rev and then does the check for DocNo in code.

vs. 

the 2nd which works as I expected.

Is there a reason why the value of fileParts[0] can't be included in the database query?

**Comment by Ronan-Farrell** [comment] 2018-04-15 12:55
fyi, behind the Get is:
![image](https://user-images.githubusercontent.com/13832903/38778600-fcf80c34-40b3-11e8-86cc-cce32d5f1ee3.png)

**Comment by smitpatel** [comment] 2018-04-15 15:04
Duplicate of #6859

Fixed in EF Core 2.1.0-preview1

**Comment by Ronan-Farrell** [comment] 2018-04-15 15:15
Thanks @smitpatel will test.

**Closed** 2022-10-16 12:18 UTC
Labels: closed-duplicate
