### ISSUE TITLE
query hangs in presence of ICollection<ownedEntity>

### ISSUE THREAD

**Issue by pas059** [dotnet/efcore#20972] opened 2020-05-15 18:48 UTC
Hello,

I'm try to modify an Entity class by replacing several OwnsOne() usages by one OwnsMany. This seems to work now and i can create a database like this. The code used to do this is like to the one below:

```C#
public partial class Test
{
    //......
    public virtual ICollection<SpecialParam> SpecialParams { get; protected set; }
    //......
}

public partial class SpecialParam
{
    //......
    public ICollection<RealData4> Parameters { get; set; }
    //......
}

public partial class RealData4
{
    //......
    [Required]
    public int Id { get; set; }
    //......
}

public partial class MyDbContext : DbContext
{
    //......
    public virtual Microsoft.EntityFrameworkCore.DbSet<Test> Tests { get; set; }
    //......

    protected override void OnModelCreating( ModelBuilder modelBuilder )
    {
        //......
        modelBuilder.Entity<SpecialParam>()
                        .OwnsMany<RealData4>( stp => stp.Parameters,
                                              r4 =>
                                              {
                                                    r4.WithOwner().HasForeignKey( "SpecialParamId" );
                                                    r4.Property( "Id" );
                                                    r4.HasKey( "Id" );
                                               }
                                            );
        //......
    }
}

```

Now my problem is to load a previously saved entity. To do this i do:

```C#
public partial class MyDbContext : DbContext
{
    public virtual Test GetTestFrom( int testId )
	{
        //......
        Test theTest = Tests//  some .Include()
                            .Include( test => test.SpecialParams )
                                //.ThenInclude( p => p.Parameters )     //  this change nothing
                            //  some .Include()
                        .Single<Test>( test => test.TestId == testId );
        return theTest;
        //......
    }
}
```

Unfortunately the execution hangs, never return, no exception. When trying to load a Test which has no 'SpecialParams' this works without problem.
Someone can help on this kind of query?

Regards
Pascal

### Further technical details

EF Core version: 3.1.3
Database provider:Sqlite
Target framework: .NET 4.7.2
Operating system: W10pro
IDE:  Visual Studio 2019CE 16.5.4

**Comment by pas059** [comment] 2020-05-18 16:07
Hi,

Apparently i found the origin of this issue. In fact the Collection of Owned entities was not the problem.
I think that my problem was a consequence of the change in the queries between EFc226 and EFc313. I will trying to explain.

In the Query listed above, there was one Include that created the problem:

```

public partial class MyDbContext : DbContext
{

    public virtual Microsoft.EntityFrameworkCore.DbSet<DocRecord> DocRecords { get; set; }
    public virtual Microsoft.EntityFrameworkCore.DbSet<DocData> DocDatas { get; set; }


    public virtual Test GetTestFrom( int testId )
	{
        //......
        Test theTest = Tests//  some .Include()
                            .Include( test => test.DocRecord.DocDataSet )    //  the Include that creates the problem
                            //  some .Include()
                            .Include( test => test.SpecialParams )
                            //  some .Include()
                        .Single<Test>( test => test.TestId == testId );
        return theTest;
        //......
    }
}

public partial class Test
{
    //...
          public virtual DocRecord DocRecord { get; set; }

    //...
}

public partial class DocRecord
{
    //...
    public virtual ICollection<DocData> DocDataSet { get; protected set; }
    //...
}
```

'test.DocRecord.DocDataSet ' is nothing so complex but this can implies to load a large amount of data (M bytes). If i had already noticed that the some queries give an exception telling that t'he LINQ query can not be translated blablabla...', this time the program just hung without an exception being thrown.
So my solution is to simply remove this Include, and after the query being returned, do a second for just the  DocRecord.DocDataSet.

Any comment or suggestion is of course appreciated.
Regards

**Comment by ajcvickers** [comment] 2020-05-18 16:23
@pas059 You could be hitting this: #18022 . If not, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by pas059** [comment] 2020-05-18 18:48
Hi Arthur,
thanks for this interesting link. It's similar problem except that in my case:

- the app hangs
- the number of Include (14 in the my real query) is not the problem (i tried to remove some of them) but this the one indicated which creates the problem; this one also implies much more amount of data than all the others.

My workaround is the following:
```
public partial class MyDbContext : DbContext
{

    public virtual Microsoft.EntityFrameworkCore.DbSet<DocRecord> DocRecords { get; set; }
    public virtual Microsoft.EntityFrameworkCore.DbSet<DocData> DocDatas { get; set; }


    public virtual Test GetTestFrom( int testId )
	{
        //......
        Test theTest = Tests//  some .Include()
                            //.Include( test => test.DocRecord.DocDataSet ) //  this causes the App to hang when test.SpecialParams exist
                            //  some .Include()
                            .Include( test => test.SpecialParams )
                            //  some .Include()
                        .Single<Test>( test => test.TestId == testId );
        LoadDocDataOf( theTest.DocRecord );
        return theTest;
        //......
    }

    private void LoadDocDataOf( DocRecord docRecord )
    {
        var ddsq = DocRecords.Include( dr => dr.DocDataSet )
                            .Where( dr => dr.DocRecordId == docRecord.DocRecordId )
                            .Select( dr => dr.DocDataSet )
                            .First();
        foreach ( DocData dd in ddsq )
        {
            docRecord.DocDataSet.Add( dd );
        }
    }

}

```
Anyway, perhaps it's better to split the query in 2 parts, as this is the second which implies the greatest amount of data (??).

PS: it will not possible for me to make a small, runnable code listing
Best regards

**Comment by ajcvickers** [comment] 2020-05-18 18:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:25 UTC
Labels: closed-could-not-reproduce, customer-reported
