### ISSUE TITLE
How to get dbset dynamically

### ISSUE THREAD

**Issue by hanfeige** [dotnet/efcore#20988] opened 2020-05-19 00:05 UTC
What should I do to get the object type of dbset dynamically? Because my entity type is generated dynamically at runtime and added to the context through modulebuilder, but I can't get dbset and use it now. I hope there is a similar way to dbcontext. Set (type type) to get Dbset

**Comment by smitpatel** [comment] 2020-05-19 00:16
How do you plan to use the non generic DbSet?

**Comment by hanfeige** [comment] 2020-05-19 00:56
> How do you plan to use the non generic DbSet?

First I extended an EfCore auto-migration method that will help me migrate the database automatically and I will call it when the program starts, as shown below
`            KingsDbContext dbContext = new KingsDbContext(new DbContextOptions<KingsDbContext>());
            dbContext.AutoMigratorDatabase();`

31/5000 
Some entity types are dynamically generated through roslyn and added to the database entity
![image](https://user-images.githubusercontent.com/17940219/82272682-e050b900-99ad-11ea-8b6b-14057036e980.png)

Now I want to by DbSet. Get (string) or DbSet. Get Get DbSet (Type), and use the dynamic query technology to perform data CRUD operations, such as: use the Microsoft. EntityFrameworkCore. DynamicLinq
`            var query = context.Set(myType)
                .Where("Orders.Count >= @0", 5)
                .OrderBy("Orders.Count")
                .ToList();`

**Comment by smitpatel** [comment] 2020-05-19 02:00
If you are going to generate the query dynamically then you can just create the DbSet dynamically in expression trees too.

**Comment by hanfeige** [comment] 2020-05-19 02:05
> If you are going to generate the query dynamically then you can just create the DbSet dynamically in expression trees too.

How do I dynamically generate a DbSet and use it in the EfCore context?

**Comment by ajcvickers** [comment] 2020-05-22 20:47
@hanfeige The main problem with this is that LINQ is inherently based on generic types. This means if you end up with a fully dynamic, not-generic `IQueryable` there isn't much you can do with it, without using lots of nasty reflection. Do you have a plan for how you would deal with this?

**Comment by ajcvickers** [comment] 2020-06-01 16:41
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:25 UTC
Labels: closed-no-further-action, customer-reported
