### ISSUE TITLE
Sub-library table

### ISSUE THREAD

**Issue by zhanghaiboshiwo** [dotnet/efcore#21600] opened 2020-07-13 03:30 UTC
Can EFCore realize the query of sub-library and table

**Comment by roji** [comment] 2020-07-13 13:23
@zhanghaiboshiwo you're going to have to provide more details - it's hard to understand what exactly you're asking. A minimal code sample could help as well.

**Comment by ajcvickers** [comment] 2020-07-20 15:35
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:33 UTC
Labels: closed-could-not-reproduce, customer-reported
