### ISSUE TITLE
N+1 on subqueries that use `.Take()` and/or `.Skip()` 

### ISSUE THREAD

**Issue by jeradrose** [dotnet/efcore#15587] opened 2019-05-02 21:49 UTC
### Summary
If you have a 1:N subquery that involves `.Take()` or `.Skip()`, it causes an N+1.

### Steps to repro
This can be done on any query starting with a table, and doing a subquery on a related 1:N table. 

Take this sample query:

```c#
var test = MyDbContext
    .Users
    .Where(u => u.Id == 1 || u.Id == 2)
    .Select(u => new {
        AddressIds = u.Addresses
            .Take(3)
            .Select(a => a.Id)
            .ToList()
    })
    .ToList();
```

And this generates three queries -- 1 for the list of `Users.Id`, and N (= 2) for each list of `Addresses.Id`:

```
SELECT [u].[Id]
FROM [Users] AS [u]
WHERE [u].[Id] IN (1, 2)

exec sp_executesql N'
SELECT TOP(3) [a].[Id]
FROM [Addresses] AS [a]
WHERE @_outer_Id = [a].[UserId]',N'@_outer_Id int',@_outer_Id=1

exec sp_executesql N'
SELECT TOP(3) [a].[Id]
FROM [Addresses] AS [a]
WHERE @_outer_Id = [a].[UserId]',N'@_outer_Id int',@_outer_Id=2
```

With EF6 (which we have migrated from a while back), this definitely was not causing N+1s. In fact, I believe (without the `.ToList()` to force materialization) this would generate a single query with EF6.

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 x64
IDE: Visual Studio 2017 15.9.11

**Comment by smitpatel** [comment] 2019-05-02 22:26
Duplicate of #11340

**Closed** 2022-10-16 14:20 UTC
Labels: closed-duplicate, customer-reported
