### ISSUE TITLE
Join statement generates invalid sql

### ISSUE THREAD

**Issue by zeeshanzahoor** [dotnet/efcore#14247] opened 2018-12-26 06:55 UTC
The generated SQL is not valid when I try to join two entities having custom projection. I am using SQL server provider.

### Sample Codes
```c#
 // ServiceDefinition and ServiceInternalMap are entities with custom TableName attributes.
    var query = context.ServiceDefinition.Select(m => new ServiceDefinition()
    {
        Id = m.Id,
        LogicalName = m.LogicalName
    })
    .Join(context.ServiceInternalMap.Select(c => new ServiceInternalMap()
    {
        Id = c.Id,
        ServiceDefinitionId = c.ServiceDefinitionId
    }),
    m => m.Id,
    c => c.ServiceDefinitionId,
    (m, c) => new { m, c });

    var result = query.ToList();
```
The sql query generated from the above code is following. The mistake is in  [t].[SERVICE_DEFINITION_ID]. The properties of entities have custom Column attribute.

```SQL
SELECT [t].[ID], [t].[ServiceDefinitionId], [t].[SERVICE_DEFINITION_ID], [m].[ID] AS [Id0], [m].[LOGICAL_NAME] AS [LogicalName]
FROM [dbo].[SERVICE_DEFINITION] AS [m]
INNER JOIN (
    SELECT [c].[ID], [c].[SERVICE_DEFINITION_ID] AS [ServiceDefinitionId]
    FROM [dbo].[SERVICE_INTERNAL_MAP] AS [c]
) AS [t] ON [m].[ID] = [t].[SERVICE_DEFINITION_ID]
```

### Exception Details

```
Exception message: 

Invalid column name 'SERVICE_DEFINITION_ID'.
Invalid column name 'SERVICE_DEFINITION_ID'.

Stack trace:    
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFTestTransaction.Program.Main(String[] args)
```

**Comment by maumar** [comment] 2018-12-26 08:19
I was able to reproduce this on current bits. Full repro:

```cs
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();
            }

            using (var ctx = new MyContext())
            {
                var query = ctx.ServiceDefinitions.Select(m => new ServiceDefinition()
                {
                    Id = m.Id,
                    LogicalName = m.LogicalName
                })
                .Join(ctx.ServiceInternalMaps.Select(c => new ServiceInternalMap()
                {
                    Id = c.Id,
                    ServiceDefinitionId = c.ServiceDefinitionId
                }),
                m => m.Id,
                c => c.ServiceDefinitionId,
                (m, c) => new { m, c });

                var result = query.ToList();


                Console.WriteLine(result);
            }
        }
    }

    public class ServiceDefinition
    {
        public int Id { get; set; }
        public string LogicalName { get; set; }
    }

    public class ServiceInternalMap
    {
        public int Id { get; set; }

        [Column(name: "SERVICE_DEFINITION_ID")]
        public int ServiceDefinitionId { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<ServiceDefinition> ServiceDefinitions { get; set; }
        public DbSet<ServiceInternalMap> ServiceInternalMaps { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=Repro14247;Trusted_Connection=True;MultipleActiveResultSets=true;");
        }
    }
```

**Comment by maumar** [comment] 2018-12-26 08:19
@zeeshanzahoor workaround is to use anonymous projection instead of DTO, like so:

```
                var query = ctx.ServiceDefinitions.Select(m => new //ServiceDefinition()
                {
                    Id = m.Id,
                    LogicalName = m.LogicalName
                })
                .Join(ctx.ServiceInternalMaps.Select(c => new //ServiceInternalMap()
                {
                    Id = c.Id,
                    ServiceDefinitionId = c.ServiceDefinitionId
                }),
                m => m.Id,
                c => c.ServiceDefinitionId,
                (m, c) => new { m, c });
```

**Comment by zeeshanzahoor** [comment] 2018-12-26 08:43
> @zeeshanzahoor workaround is to use anonymous projection instead of DTO, like so:
> 
> ```cs
>                 var query = ctx.ServiceDefinitions.Select(m => new
>                 {
>                     Id = m.Id,
>                     LogicalName = m.LogicalName
>                 })
>                 .Join(ctx.ServiceInternalMaps.Select(c => new 
>                 {
>                     Id = c.Id,
>                     ServiceDefinitionId = c.ServiceDefinitionId
>                 }),
>                 m => m.Id,
>                 c => c.ServiceDefinitionId,
>                 (m, c) => new { m, c });
> ```

Thank you for your support and workaround. Actually I want to include or exclude columns from the result set (dynamically) without changing the type of the result. The sample code was provided just to address the issue.

**Comment by smitpatel** [comment] 2018-12-26 19:57
Duplicate of #8094

**Closed** 2022-10-16 13:45 UTC
Labels: closed-duplicate, customer-reported
