### ISSUE TITLE
Argument types do not match on query with projection

### ISSUE THREAD

**Issue by mdmoura** [dotnet/efcore#5578] opened 2016-05-30 15:39 UTC
I have the following entities in Entity Framework Core RC2:

```
public class Job {
  public Int32 Id { get; set; }
  public Int32? DegreeLevelId { get; set; }
  public Int32 PositionId { get; set; }   
  public virtual DegreeLevel DegreeLevel { get; set; }
  public virtual Position Position { get; set; }
}

public class DegreeLevel {
  public Int32 Id { get; set; }
  public String Name { get; set; }
}

public class Position {
  public Int32 Id { get; set; }
  public String Name { get; set; }
}
```

And the following Models:

```
public class JobModel {
    public Int32 Id { get; set; }
    public DegreeLevelModel DegreeLevel { get; set; }
    public PositionModel Position { get; set; }
}

public class DegreeLevelModel {
  public Int32 Id { get; set; }
  public String Name { get; set; }
}

public class PositionModel {
  public Int32 Id { get; set; }
  public String Name { get; set; }
}
```

And the following query with projection:

```
      var result = await context.Jobs.Select(x =>
        new JobModel {
          Id = x.Id,
          DegreeLevel = new DegreeLevelModel {
            Id = x.DegreeLevel.Id,
            Name = x.DegreeLevel.Name
          },
          Position = new PositionModel {
            Id = x.Position.Id,
            Name = x.Position.Name
          }
        }).ToListAsync();
```

When I run it I get the error "Argument types do not match".

I was able to isolate the problem and it seems is because I have:

```
public Int32? DegreeLevelId { get; set; }
```

The FK as optional since DegreeLevel is option in Job entity. I suppose this is a normal configuration.

Any idea how to solve this?

**Comment by smitpatel** [comment] 2016-05-30 16:09
Duplicate of #5522 which faces the same issue as this due to optional navigation. That issue have all information why this is happening and work-around for it.

**Comment by mdmoura** [comment] 2016-05-31 17:04
@smitpatel Thank you. Do you want me to close this or let it open until it #5522 is resolved?

**Closed** 2022-10-16 09:43 UTC
