### ISSUE TITLE
Is using options injected by ConfigurationBuilder possible while migrating with EFCore tools?

### ISSUE THREAD

**Issue by Saegusae** [dotnet/efcore#27265] opened 2022-01-24 13:48 UTC
Hello,

I have a project deployed to AWS with Terraform that generates RDS credentials on deployment and saves them on AWS SystemsManager ParameterStore. For my startup script I have the settings mapped to options objects like this:

```C#
if (!builder.Environment.IsDevelopment())
  builder.Configuration
    .AddSystemsManager($"/{organizationName}/{applicationName}/{environmentName}", new AWSOptions
    {
      Region = RegionEndpoint.GetBySystemName(region)
    });

builder.Services.Configure<DatabaseOptions>(builder.Configuration.GetSection(DatabaseOptions.Section));
```

And then I create my DbContext for default and local environments like this:

```C#
if (!builder.Environment.IsDevelopment())
    builder.Services.AddDbContext<DataContext>();
else
    builder.Services.AddDbContext<DataContext, TestContext>();
```

The test context inherits from `DataContext` and overrides the configure method to use a local SQLite file, the actual context uses the PostgreSQL driver. Using these with EF Core tools I can generate migrations for other environments just fine like this:

```powershell
dotnet ef migrations add InitialCreate --project API 
    --context DataContext --output-dir Migrations/Staging -- --environment staging
```

But when I try to apply these migrations using

```powershell
dotnet ef database update/drop
```

commands, the configuration options won't get loaded into the objects like it does on runtime using AWS ConfigurationBuilder extensions. So the DatabaseOptions object will have every value null for staging/production environments if ran on local machine which throws this error:

```
Failed creating connection: Couldn't set port (Parameter 'port')' on server 'Failed creating connection: Couldn't set port (Parameter 'port')'?
```

Is there any way to get around this with efcore tools without looking up the parameters terraform generated and pulling them down to hardcode in the appsettings files?

### Version Info

EF Core version: 6.0.1
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 6.0.2
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Jetbrains Rider

**Comment by Saegusae** [comment] 2022-01-27 11:10
Quick Update: Had to write an `IDesignTimeDbContextFactory` implementation. It looks awful, have to parse some custom cli options but it works flawlessly atm. This also let me get rid of the TestContext that inherited from DataContext. I'll leave the question open if anyone wants to comment on how they solved a similar issue.

**Comment by ajcvickers** [comment] 2022-01-27 13:04
@Saegusae We have been having difficulty understanding what the specific problem is here. is it that you can't stop `builder.Services.Configure<DatabaseOptions>(builder.Configuration.GetSection(DatabaseOptions.Section));` from running in your test environment? Or that without it running, some options that you need are not available? And how does this relate to EF Core configuration? (I don't know anything about "Terraform", including what it does or how it's related to EF Core usage.)

**Comment by ajcvickers** [comment] 2022-01-27 13:51
@Saegusae It seems to me that this is a Terraform issue (or, at most, a .NET config/options issue) rather than an EF issue. What am I missing here?

**Comment by Saegusae** [comment] 2022-01-27 14:06
It was a fundamental practice issue on my part not at all with terraform. But it is related to efcore tools. Since it does not produce an IConfiguration service for dependency injection into the derived DbContext, the connection string was not getting generated. It was easily solved using the Design Time Factory method.

**Comment by Saegusae** [comment] 2022-01-27 17:13
Entity Framework Core tools for .Net Core CLI, [here](https://github.com/dotnet/efcore/tree/main/src/dotnet-ef) in the repo. I mentioned this the sentence before but maybe I missed a point?

**Comment by ajcvickers** [comment] 2022-01-27 17:19
@bricelam Do you understand what is being said here?

**Comment by Saegusae** [comment] 2022-01-28 10:23
Ehm, I'll try to explain better. We're using EntityFramework as the ORM solution for our ASP.NET Core 6 application. Dev, Staging and Prod environments have different databases so we need different connectionStrings for the context.

In the startup `Program.cs` we build the app configuration and inject the section called "Database" into an IOptions object as written [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-6.0). This configuration object contains Host, Port, User, Pass, DatabaseName of the remote connection and we build the connectionString out of these variables. AWS Sdk has a [configuration provider](https://github.com/aws/aws-dotnet-extensions-configuration) to be able to inject these options from AWS SystemsManager ParameterStore instead of the appSettings.{environment}.json file

But when using the context with `dotnet ef` commands instead of running the application. This part is completely skipped. The Host, Port, User, Pass, DbName variables in the generated DatabaseOptions object are null by default for other environments than Development. Means we could not do migrations on our remote databases using `dotnet ef database update` with this pattern.

**Comment by ajcvickers** [comment] 2022-02-02 11:24
> But when using the context with dotnet ef commands instead of running the application. This part is completely skipped. 

This is the bit I don't understand. I don't believe anything is skipped by EF Core. On the other hand, if the AWS configuration provider is not available to supply these options, and the application has not provided any alternate mechanism to supply these things, then there is nothing EF can do about that. What is it that makes you think EF is skipping something here?

**Comment by ajcvickers** [comment] 2022-02-14 19:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:23 UTC
Labels: closed-no-further-action, customer-reported
