### ISSUE TITLE
Distinct done on too much columns for subqueries

### ISSUE THREAD

**Issue by jonathanantoine** [dotnet/efcore#19826] opened 2020-02-07 09:22 UTC
The SQL produced by this query does not include the distinct for the sublist query : 

```  C#
var ddd = await DbContext.ADbSet
    .Select(item =>
        new AModel
        {
            Id = item.Id,
            Name = item.Name,
            Type = item.Type,
            sublist = item.SubObject
                .Select(s => s.RelatedObject.Name).OrderBy(a => a).Distinct().Select(t => t).ToList()
        })
    .ToListAsync();

```
Expected :
```SQL
SELECT "t"."Id", "t"."Name", "t"."Type", "t0"."Name", "t0"."Id", "t0"."Id0"
FROM (
    SELECT "d"."Id", "d"."Name", "d"."Type"
    FROM "ADbSets" AS "d"
    ORDER BY (SELECT 1)
    LIMIT @__p_1 OFFSET @__p_0
) AS "t"
LEFT JOIN (
    SELECT DISTINCT "d1"."Name", "d1"."ADbSetItemId"
    FROM "SubObjects" AS "d0"
    INNER JOIN "RelatedObjects" AS "d1" ON "d0"."RelatedObjectId" = "d1"."Id"
) AS "t0" ON "t"."Id" = "t0"."ADbSetItemId"
ORDER BY "t"."Id", "t0"."Id", "t0"."Id0"

```

Produced :
```SQL
SELECT "t"."Id", "t"."Name", "t"."Type", "t0"."Name", "t0"."Id", "t0"."Id0"
FROM (
    SELECT "d"."Id", "d"."Name", "d"."Type"
    FROM "ADbSets" AS "d"
    ORDER BY (SELECT 1)
    LIMIT @__p_1 OFFSET @__p_0
) AS "t"
LEFT JOIN (
    SELECT DISTINCT "d1"."Name", "d0"."Id", "d1"."Id" AS "Id0", "d0"."ADbSetItemId"
    FROM "SubObjects" AS "d0"
    INNER JOIN "RelatedObjects" AS "d1" ON "d0"."RelatedObjectId" = "d1"."Id"
) AS "t0" ON "t"."Id" = "t0"."ADbSetItemId"
ORDER BY "t"."Id", "t0"."Id", "t0"."Id0"

```

### Further technical details

EF Core version: 3.1.1
Database provider: Sqlite
Target framework:  NET Core 3.1
Operating system:
IDE: not related

**Comment by smitpatel** [comment] 2020-02-07 11:17
Provide a runnable repro project. Your LINQ query does not generated the SQL you posted.

**Comment by ajcvickers** [comment] 2020-02-14 17:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by jonathanantoine** [comment] 2020-04-14 13:29
Sorry @ajcvickers , I forgot to add a repro for this bug. Here it is : [NoDistinctInSubqueries.zip](https://github.com/dotnet/efcore/files/4475499/NoDistinctInSubqueries.zip)


I used the [classic "get started" models](https://docs.microsoft.com/en-us/ef/core/get-started/?tabs=netcore-cli) and the code to test the bad behavior is :
```csharp
using (var db = new BloggingContext())
{
    db.Database.EnsureCreated();
    // Create
    db.Add(new Blog {Url = "http://blogs.msdn.com/adonet"});
    db.SaveChanges();
    // Read
    var blog = db.Blogs
        .OrderBy(b => b.BlogId)
        .First();
    var randomTitle = Guid.NewGuid().ToString("N");
    for (int i = 0; i < 5; i++)
    {
        db.Add(new Post
        {
            Blog = blog,
            Title = randomTitle
        });
        db.SaveChanges();
    }
    var distinctedQuery = db.Blogs
        .OrderBy(b => b.BlogId)
        .Select(b => new
        {
            PostTitles = b.Posts
                .Select(s => s.Title)
                .OrderBy(a => a)
                .Distinct().ToList()
        })
        .First();
    Console.WriteLine("Expected PostTitles count to be 1 and found " + distinctedQuery.PostTitles.Count);
}
```

Which returns :

> Expected PostTitles count to be 1 and found 5

**Comment by smitpatel** [comment] 2020-04-14 14:36
Duplicate of #15873

**Comment by jonathanantoine** [comment] 2020-04-14 15:38
Can you provide a description of the other but @smitpatel ? I can't be sure it's a duplicate.

**Comment by smitpatel** [comment] 2020-04-14 15:51
You cannot do `Distinct` over collection in projection if you are not projecting out key columns. There is no way for us to know how to create individual `PostTitles` groups.

**Comment by kjeske** [comment] 2020-07-28 22:52
If that's not possible, shouldn't it throw a not-supported-exception? I think it's misleading when you explicitly select a column, make a distinct instruction, but behind the scenes a primary key is added to the projection and you get unexpected results.

**Comment by smitpatel** [comment] 2020-07-28 23:14
@kjeske - #15873 is tracking of throwing a better exception message rather than unexpected results.

**Closed** 2022-10-16 18:09 UTC
Labels: customer-reported
