### ISSUE TITLE
Support for combining TPH and TPT inheritance strategies

### ISSUE THREAD

**Issue by petarpetrovt** [dotnet/efcore#31184] opened 2023-07-04 17:26 UTC
As of my understanding, the current version of Entity Framework Core (EF Core) does not provide direct support for combining Table Per Hierarchy (TPH) and Table Per Type (TPT) inheritance strategies. TPH maps all derived types to a single table, while TPT maps each derived type to its own table. Combining these strategies simultaneously could be beneficial in certain scenarios where a hybrid approach is required. This could potentially involve extending the existing mapping annotations or providing a new mechanism for defining custom inheritance mappings.

Example:
```csharp
public class ObjectEntity
{
    public int Id { get; set; }

    public int Type { get; set; }

    public ObjectEntity(int type)
    {
        Type = type;
    }
}

public class CustomObjectWithTable : ObjectEntity
{
    public CustomObjectWithTable() : base(type: 1) { }

    public int? Test { get; set; }
}

public class CustomObjectWithoutTable : ObjectEntity
{
    public CustomObjectWithoutTable(): base(type: 2) { }
}

builder.Entity<ObjectEntity>(e =>
{
    e.ToTable("Objects", "dbo");
    e.Property(x => x.Id).HasColumnType("int").HasColumnName("Id").UseIdentityColumn();
    e.Property(x => x.Type).HasColumnType("int").HasColumnName("Type").IsRequired(true);
    e.HasDiscriminator(x => x.Type);
    e.HasKey(x => x.Id);
});

builder.Entity<CustomObjectWithTable>(e =>
{
    e.ToTable("CustomObjects", "dbo");
    e.Property(x => x.Test).HasColumnType("int").HasColumnName("Test").IsRequired(false);
    e.HasDiscriminator(x => x.Type).HasValue(1);
    e.HasBaseType<ObjectEntity>();
});

builder.Entity<CustomObjectWithoutTable>(e =>
{
    e.HasDiscriminator(x => x.Type).HasValue(2);
    e.HasBaseType<ObjectEntity>();
});
```

**Comment by roji** [comment] 2023-07-04 19:56
Duplicate of #27707

**Closed** 2023-07-07 16:57 UTC
Labels: customer-reported
