### ISSUE TITLE
InMemory database - Views

### ISSUE THREAD

**Issue by redowl3** [dotnet/efcore#19252] opened 2019-12-09 14:24 UTC
We're trying to use an inmemory db for our integration tests and the db we are modelling our inmemory versions uses a number of Views.  How do we create a View in OnModelCreating?

Thanks,

**Comment by redowl3** [comment] 2019-12-09 14:34
I've tried adding the view using a SQL script when seeding the in-memory db but get this error

"System.InvalidOperationException: 'Relational-specific methods can only be used when the context is using a relational database provider.'"

**Comment by ajcvickers** [comment] 2019-12-09 17:20
Duplicate of https://github.com/aspnet/EntityFramework.Docs/issues/1850

**Closed** 2022-10-16 18:00 UTC
Labels: customer-reported
