### ISSUE TITLE
Must be reducible node thrown when projecting sub collection to a get only list.

### ISSUE THREAD

**Issue by devl-up** [dotnet/efcore#27506] opened 2022-02-25 08:50 UTC
When I try projection my entity to a DTO which contains a get only list, i get a `System.ArgumentException: must be reducible node` exception.

The query in question:
```C#
public Task<RoomDto?> GetRoom(Guid id)
{
	return Rooms
		.Include(room => room.Tiles)
		.Where(room => room.Id == id)
		.Select(room => new RoomDto
		{
			Id = room.Id.ToString(),
			Name = room.Name.Value,
			Width = room.Size.Width,
			Height = room.Size.Height,
			Tiles =
			{
				room.Tiles.Select(tile => new TileDto
				{
					Id = tile.Id.ToString(),
					X = tile.Position.X,
					Y = tile.Position.Y,
					Type = tile.Type.ToString()
				})
			}
		})
		.FirstOrDefaultAsync();
}
```

The DTO is generated by grpc, but the property is as follows:

```C#
 /// <summary>Field number for the "tiles" field.</summary>
    public const int TilesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Application.TileDto> _repeated_tiles_codec
        = pb::FieldCodec.ForMessage(42, global::Application.TileDto.Parser);
    private readonly pbc::RepeatedField<global::Application.TileDto> tiles_ = new pbc::RepeatedField<global::Application.TileDto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Application.TileDto> Tiles {
      get { return tiles_; }
    }
```

The problem is not present anymore when I remove the projection of the "Tiles", so the following code is the problem in the query

```C#
Tiles =
{
        room.Tiles.Select(tile => new TileDto
        {
	        Id = tile.Id.ToString(),
	        X = tile.Position.X,
	        Y = tile.Position.Y,
	        Type = tile.Type.ToString()
        })
}
```
This is the stacktrace:
```
System.ArgumentException: must be reducible node
         at System.Linq.Expressions.Expression.VisitChildren(ExpressionVisitor visitor)
         at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
         at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
         at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
         at Microsoft.EntityFrameworkCore.Query.Internal.SelectExpressionPruningExpressionVisitor.Visit(Expression expression)
         at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
         at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
         at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
         at Microsoft.EntityFrameworkCore.Query.Internal.SelectExpressionPruningExpressionVisitor.Visit(Expression expression)
         at Microsoft.EntityFrameworkCore.Query.Internal.SelectExpressionPruningExpressionVisitor.Visit(Expression expression)
         at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
         at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
         at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
         at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
         at Infrastructure.EntityFramework.Queries.EfRoomQueries.GetRoom(Guid id) in C:\Users\E626738\Projects\ware-to\backend\src\Infrastructure\EntityFramework\Queries\EfRoomQueries.cs:line 47
         at Application.Rooms.Queries.GetRoomHandler.Handle(GetRoomRequest query) in C:\Users\E626738\Projects\ware-to\backend\src\Application\Rooms\Queries\GetRoomHandler.cs:line 16
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 invokerTask, GrpcActivatorHandle`1 serviceHandle)
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 invokerTask, GrpcActivatorHandle`1 serviceHandle)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)

```

EF Core version: 6.0.3
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Rider 2021.3.3

**Comment by maumar** [comment] 2022-03-01 06:55
we don't recognize/translate collection initializer pattern

**Comment by BusschaertTanguy** [comment] 2022-03-01 10:25
> we don't recognize/translate collection initializer pattern

@maumar and no plans on supporting it ?

**Comment by ajcvickers** [comment] 2022-03-11 21:26
@roji To look for dupe.

**Comment by ajcvickers** [comment] 2022-03-14 11:15
@BusschaertTanguy We may support this in the future, but it isn't a high priority.

**Comment by roji** [comment] 2022-03-14 11:19
Duplicate of #16867

**Closed** 2022-10-16 20:27 UTC
Labels: customer-reported
