### ISSUE TITLE
ExecuteUpdate does not work with owned Entities

### ISSUE THREAD

**Issue by Ta1sty** [dotnet/efcore#30176] opened 2023-01-30 18:50 UTC
Hello, 

after upgrading our Repositiory to .Net7 I encountered a bug with the Own-Components in our Context Model. We previously had our own implementation of ExecuteUpdate prior to .net7. Now with the new release we switched to the official version provided by microsoft.
Once exchanged, all entities that had an owned component no longer functioned with this method. It wasn't even requried to update a value inside the own-component, any update would be enough to throw an Exception:

```
System.InvalidOperationException: The LINQ expression 'DbSet<Entity>()
    .Select(e => IncludeExpression(
        EntityExpression:
        e, 
        NavigationExpression:
        EF.Property<Owned>(e, "Data"), Data)
    )
    .ExecuteUpdate(x => x.SetProperty<DateTime>(
        propertyExpression: e => e.Modified, 
        valueExpression: DateTime.UtcNow))' could not be translated. Additional information: The following lambda argument to 'SetProperty' does not represent a valid property to be set: 'e => e.Modified'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteUpdateAsync[TSource](IQueryable`1 source, Expression`1 setPropertyCalls, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in F:\GIS\server\STP.GIS.Portal.SnapshotTerminator\Program.cs:line 21
```

The Code to produce this error is shown below. (The Query crashes during translation, therefore it is not required to set up an sql server)

```C#
// Using EntityFramework Core 7.0.2, EntityFrameworkCore.SqlServer 7.0.2
var connectionStr = "Server=tcp:this.domain.doesnt.exist,1433;Initial Catalog=db;User ID=sa;Password=123;";
var collection = new ServiceCollection();
collection.AddDbContextPool<TestContext>(options =>
{
    options.UseSqlServer(connectionStr, _ => { })
        .EnableSensitiveDataLogging();
    {
        var loggerFactory = new LoggerFactory(new[]
        {
            new DebugLoggerProvider()
        });
        options.UseLoggerFactory(loggerFactory);
    }
});
var services = collection.BuildServiceProvider();
var scope = services.CreateScope();
var context = scope.ServiceProvider.GetRequiredService<TestContext>();

// The Test
context.Test.ExecuteUpdateAsync(x => x.SetProperty(e => e.Modified, DateTime.UtcNow));

// The Context
public class TestContext  : DbContext{
    public TestContext(DbContextOptions<TestContext> options) : base(options)
    {
    }
    public class Entity
    {
        public Guid Id { get; set; }
        public DateTime Modified { get; set; }
        public Owned Data { get; set; }
    }

    public class Owned
    {
        public string Name { get; set; }
        public int Value { get; set; }
    }
    public DbSet<Entity> Test { get; set; }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<Entity>(entity =>
        {
            entity.HasKey(x => x.Id);
            entity.OwnsOne(x => x.Data);
        });
    }
}

```

For the Update statement: context.Test.ExecuteUpdateAsync(x => x.SetProperty(e => e.Modified, DateTime.UtcNow));
it is not required to access any of the own-component's propertys nor to update them in any way.

The exception is caused by the translation of the query, more precicely in:
RelationalQueryableMethodTranslatingExpressionVisitor.IsValidPropertyAccess

There the property is checked: expression is MemberExpression { Expression: EntityShaperExpression ese }
Which is not the case, the actual EntityShaperExpression is 1 more steps down the line. 
Here we have the following values:
- For the Input Expression expression: [Microsoft.EntityFrameworkCore.Query.IncludeExpression].Modified
- For the InnerExpresion of the Input; [Microsoft.EntityFrameworkCore.Query.IncludeExpression]
- For the EntityExpression of the Include: [Microsoft.EntityFrameworkCore.Query.RelationalEntityShaperExpression]

```
// expression is MemberExpression : true
// expression as MemberExpression mem
// mem is EntityShaperExpression : false
// mem is IncudeExpression: true
// mem as IncludeExpression incl
// incl.EntityExpression is EntityShaperExpression = true
if (expression is MemberExpression { Expression: EntityShaperExpression ese })
{
  entityShaperExpression = ese;
  return true;
}
```
While this is still a completly valid access of a property the method does not check recursivly throgh an IncludeExpression.

Now my question is, is there a reason why this isn't allowd, is this a bug and how can I fix this issue? Is there a way to ignore the inclusion of OwnedEntities? Such that the query-compiler does not produce an IncludeExpression?

I.M.O. this sould be working with OwnedEntities, firstly updating the Owner but also updating values in the owned entity.

### Include provider and version information

EF Core version: 7.0.2
Database provider: SQL-Server 7.0.2
Target framework: .NET 7.0
Operating system: Windows 11 x64
IDE: JetBrains Rider

**Comment by ajcvickers** [comment] 2023-01-30 19:10
Duplicate of #28727.

**Closed** 2023-02-01 20:18 UTC
Labels: customer-reported
