### ISSUE TITLE
.net core wep api sending mail

### ISSUE THREAD

**Issue by TimucinAkdeniz** [dotnet/efcore#23763] opened 2020-12-24 13:41 UTC
Hi everyone,

I have a major problem.

"System.Exception: Failure sending mail.
GSSAPI operation failed with error - An invalid name was supplied (Name is empty)."

please help me.

Thanks

**Comment by ajcvickers** [comment] 2021-01-01 17:52
@TimucinAkdeniz It's not clear how this is related to EF Core. Can you provide more details?

**Comment by ajcvickers** [comment] 2021-01-08 15:11
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:16 UTC
Labels: closed-no-further-action, customer-reported
