### ISSUE TITLE
[Sqlite in memory] LastOrDefaultAsync() returns null, but ToListAsync().LastOrDefault() returns an object with the same predicate

### ISSUE THREAD

**Issue by ChrisSwinchatt** [dotnet/efcore#19352] opened 2019-12-18 14:20 UTC
When using EF Core 2.2 with a Sqlite in memory DB (`Microsoft.EntityFrameworkCore.Sqlite`, `DataSource=:memory:`), executing a LastOrDefaultAsync on a DB table returns null, but executing LastOrDefault on the results of ToListAsync - with the same predicate - returns an entity.

The InMemory provider (`Microsoft.EntityFrameworkCore.InMemory`) and the Npgsql provider do not have this behaviour.

### Steps to reproduce

The following Gist contains code which demonstrates the problem:
https://gist.github.com/ChrisSwinchatt/381c500aa822a0857766a86da0978d49

### Further technical details

EF Core version: 2.2.6
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (Asp) .Net Core 2.2
Operating system: Linux Mint 19.2 (Ubuntu 18.04)
IDE: JetBrains Rider 2019.3

**Comment by ajcvickers** [comment] 2019-12-18 21:34
@ChrisSwinchatt Can you try using EF Core 3.1?

**Comment by ajcvickers** [comment] 2020-01-02 17:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:02 UTC
Labels: closed-could-not-reproduce, customer-reported
