### ISSUE TITLE
Query: EF Core 3.1.1 Join to Table-Valued Function fails when leveraging `.Cast<T>` to a base entity

### ISSUE THREAD

**Issue by shuhkla** [dotnet/efcore#20046] opened 2020-02-24 17:54 UTC
We have a method that performs a LINQ join from a base entity to a table valued function that worked correctly in EF Core 2.2. It is no longer working in 3.1 with the following exception being thrown: `System.ArgumentNullException: 'Value cannot be null. (Parameter 'key')'`

We had QueryClientEvaluationWarning throw as an error prior to the upgrade, so I believe we can rule out this possibility.

### Steps to reproduce

Model:

``` C#
public class BaseEntity {
  public Guid Id {get; set;}
}

public class NotificationTemplateAttachment: BaseEntity
{
}

public class TvfGetAuditColumns
{
        public Guid OriginalId { get; set; }
        public string CreatedBy { get; set; }
        public DateTimeOffset CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTimeOffset? ModifiedOn { get; set; }
}

```

With the mapping:
``` C#
            builder.Query<TvfGetAuditColumns>(); // Table valued function
            builder.Entity<NotificationTemplateAttachment>().ToTable("NotificationTemplateAttachment").HasKey(x => x.Id);

```

And the method that performs LINQ join:
``` C#
private IList<EntityWithAuditHistoryQuery> GetEntityWithAuditHistoryQuery(IQueryable<T> query) where T: BaseEntity
{
           var auditHistoryDatabaseFunctionQuery =
                DbContext.TvfGetAuditColumns.FromSqlInterpolated($"SELECT OriginalId, CreatedBy, CreatedOn, ModifiedBy, ModifiedOn FROM LPS.TvfGetAuditColumns('{typeof(T).Name}')");

            var entityQuery = query.Cast<BaseEntity>();

            var joinQuery
                from baseEntityQuery in entityQuery
                join auditHistoryQuery in auditHistoryDatabaseFunctionQuery on baseEntityQuery.Id equals auditHistoryQuery.OriginalId
           select new EntityWithAuditHistoryQuery
                {
                    EntityQuery = baseEntityQuery,
                    AuditHistoryQuery = auditHistoryQuery
                };

            return joinQuery.ToList();
}
```

Exception:
```
System.ArgumentNullException: 'Value cannot be null. (Parameter 'key')'
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.GetMappedProjection(ProjectionMember projectionMember)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__64`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LPS.Repositories.EfRepository`2.<ListWithAuditHistoryByCriteria>d__17.MoveNext() in
```

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system:
Windows 10 (Reproducible in MacOS as well)

**Comment by ajcvickers** [comment] 2020-02-28 22:14
@smitpatel Which was the issue that you thought this might be a duplicate of? (I tried to repro, but there is a lot of missing information.)

**Comment by smitpatel** [comment] 2020-03-10 01:05
The issue is already fixed in nightly builds. Removing redundant cast to Base Type is a work-around.

**Closed** 2020-03-10 06:49 UTC
Labels: area-query, closed-fixed, type-bug
