### ISSUE TITLE
DbContext calls degrade over time

### ISSUE THREAD

**Issue by bigswede74** [dotnet/efcore#14581] opened 2019-02-01 18:53 UTC
I have noticed all of our DbContext calls getting longer and longer in duration over time. Just after a few hours I can see the calls increasing in execution time. I began replacing all the LINQ queries with direct calls to StoredProcedures still using the DbContext to execute the StoredProcedures but still the call duration degrades over time. It is not any specific query but all DbContext calls.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
I do see the below warnings in the Entity logs, we are using a custom Column type
Warning:
No type was specified for the decimal column 'MyColumn' on entity type 'MyType'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values using 'ForHasColumnType()'.

Exception message:

Stack trace:
```

### Steps to reproduce
We are using a factory to build our DbContext that is then wrapped in a using statement so it is disposed properly.

```c#
    public interface IMyContextFactory
    {
        MyContext GetMyContext();
    }

    public class MyContextFactory : IMyContextFactory
    {
        public MyContext GetMyContext()
        {
            var contextOptions = new DbContextOptionsBuilder<MyContext>()
                .UseSqlServer(MyDatabaseConnectionString)
                .Options;

            return new MyContext(contextOptions);
        }
    }
        //  sample call to query data
        public List<MyObj> GetObjs()
        {
            using (var context = _myContextFactory.GetMyContext())
            {
               //  stored procedure call
                return context.SelectMyObjs();
            }
        }

    //  stored procedure extension method
        public static List<MyObj> SelectObjs(this MyContext context)
        {
            var objs = new List<Obj>();

            using (var reader = context.ExecuteStoredProcedure_Reader())
            {
                if (!reader.Read())
                {
                    return null;
                }

                while (reader.Read())
                {
                    objs.Add(reader.GetObj());
                }
            }

            return objs;
        }

     //  extension methods to execute the query
        public static DbDataReader ExecuteStoredProcedure_Reader(this MyContext context, List<SqlParameter> parameters,
            int commandTimeout = 0,
            IDbContextTransaction transaction = null,
            [CallerMemberName] string storedProcedureName = null)
        {
            storedProcedureName.ThrowIfNull(nameof(storedProcedureName));

            using (var command = context.Database.GetDbConnection().CreateCommand())
            {
                if (commandTimeout > 0)
                {
                    command.CommandTimeout = commandTimeout;
                }

                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = $"[{context.SchemaName()}].[{storedProcedureName}]";
                command.Transaction = transaction?.GetDbTransaction();

                if (parameters != null)
                {
                    command.Parameters.AddRange(parameters.ToArray());
                }
                context.Database.OpenConnection();

                return command.ExecuteReader();
            }
        }

        public static DbDataReader ExecuteStoredProcedure_Reader(this MyContext context,
            int commandTimeout = 0,
            IDbContextTransaction transaction = null,
            [CallerMemberName] string storedProcedureName = null)
        {
            storedProcedureName.ThrowIfNull(nameof(storedProcedureName));
            return context.ExecuteStoredProcedure_Reader(null, commandTimeout, transaction, storedProcedureName);
        }

```

### Further technical details
EF Core version: 2.1.4, TargetFramework - net471
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows Server 2016 with SQL Server 2016
IDE: Visual Studio 2017 15.9.6

**Comment by ajcvickers** [comment] 2019-02-01 19:01
@bigswede74 The code above doesn't actually make use of the DbContext except as a means of creating a `SqlConnection` object. What do you see if you create the connection manually and remove DbContext entirely from the code path?

**Comment by bigswede74** [comment] 2019-02-01 19:07
@ajcvickers The issue happens without StoredProcedure calls as well with direct LINQ calls against the DbContext. I have been replacing the calls with StoredProcedures to see if this fixes the issue but so far with no luck. It does slow the process down somewhat.

**Comment by bigswede74** [comment] 2019-02-01 19:12
@ajcvickers Could the custom column type warnings be causing any issue?

**Comment by ajcvickers** [comment] 2019-02-01 19:13
@bigswede74 Understood. But can you change your code to something like this:
```C#
public class MyContextFactory : IMyContextFactory
{
    public DbConnection GetMyContext()
    {
        return new SqlConnection(MyDatabaseConnectionString);
    }
}
```
with appropriate changes to the other methods and test to see if you see the same results?

**Comment by ajcvickers** [comment] 2019-02-01 19:13
@bigswede74 It's unlikely it has anything to do with those warnings.

**Comment by bigswede74** [comment] 2019-02-04 20:43
@ajcvickers I will setup this test to see if we are not cleaning up our db connections properly.

**Comment by ajcvickers** [comment] 2019-02-11 17:41
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by bigswede74** [comment] 2019-02-11 18:22
@ajcvickers We have determined that our EF logger configuration was causing a new logger to be added every time the context was created. I will open a different issue to figure out how to best configure EntityFrameworkCore logging with Serilog in a windows service.

**Closed** 2022-10-16 13:50 UTC
Labels: closed-could-not-reproduce, customer-reported
