### ISSUE TITLE
Stored Proc and navigational properties

### ISSUE THREAD

**Issue by mgolois** [dotnet/efcore#6179] opened 2016-07-27 14:20 UTC
Hello,

I'm using EF Core 1.0 and would like my navigational properties to be set if they exist in the context. 
Here is a simplify version of what I'm currently doing, which is not working correctly. What am I missing? 

```
public class Student
{
    public int Id { get; set; }
    public int MentorStudentId { get; set; }
    public string StudentName  { get; set; }
    public Student Mentor { get; set; }
    public List<Student> Mentees { get; set; }
}

 modelBuilder.Entity<Student>(entity =>
 {
    entity.HasKey(e => e.Id);
    entity.HasOne(d => d.Mentor).WithMany(p => p.Mentees).HasForeignKey(d => d.MentorStudentId);
});

public IQueryable<Student> GetStudentsByCourse(int courseId)
{
    return Set<Student>()
            .FromSql("EXEC [dbo].[GetStudentsByCourse] {0}", courseId)
            .AsNoTracking();
}

stored proc result:
Id      MentorStudentId     StudentName
1       3                  "AKJJHSHJSHD"
3       5                  "QQQQQSDSDD"
5       7                  "CCDSDDEEEEE"
7       9                  "WWWWWEFEFEF"
```

**Comment by rowanmiller** [comment] 2016-07-29 23:30
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

**Comment by divega** [comment] 2016-08-08 18:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 09:52 UTC
