### ISSUE TITLE
ToUpperInvariant() is not understand by the LINQ Interpreter

### ISSUE THREAD

**Issue by MikeKenyon** [dotnet/efcore#21758] opened 2020-07-23 17:46 UTC
Code verification systems will note that a comparison of strings in a culture-dependent fashion leads to a potential source of problems in your code.  This will flag a code-analysis warning if you either compare without culture.  This includes the only understood way of handling this ... `ToUpper()`.  

Therefore to have valid EF Core code, you need to have code that generates code analysis warnings.  

The reasonable solution is to also handle the `ToUpperInvariant()` method which is what is' actually doing under the hood if I understand correctly.

### Steps to reproduce

Consider this code.

``` C#
var q = (from item in _context.Table
              where item.Email.ToUpperInvariant() == passedInValue.Email.ToUpperInvariant()
              select item).FirstOrDefault();
```

This fails at runtime because `ToUpperInvariant()` is not handled by the processor, but `ToUpper()` is.  

### Further technical details

EF Core version: 3.1.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1.4
Operating system: Linux
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment] 2020-07-23 22:23
@MikeKenyon There are several things going on here.

> Therefore to have valid EF Core code, you need to have code that generates code analysis warnings.

In essence, this is an issue with the code analyzer. Since these expression trees are not compiled and executed the warnings are bogus here.

Looking at it from a different angle, when translating `ToUpper()` to the database, the semantics on the database may not match the semantics you would get in C#, even taking locale differences into account. This is by-design because we're attempting to create the most useful translation that can be performed efficiently.

We have discussed doing the same for `ToUpperInvariant`, but this method imply's stronger semantics than `ToUpper` such that there is more likely to be an expectation that the semantics will be preserved on the database.

All this is why we have implemented support for [database collations](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#database-collations) in EF Core 5.0. If you need to be sure what translation you are getting then we recommend being explicit about the collation at the database level. 

Related: #18995

**Comment by Saibamen** [comment] 2020-07-24 08:08
Related https://github.com/dotnet/efcore/issues/1222?

**Comment by ajcvickers** [comment] 2020-07-24 19:02
We discussed as a team and agreed that this is still the approach we want to take. Closing as duplicate of #18995 for the reasons discussed in #1222

**Closed** 2022-10-16 18:34 UTC
Labels: customer-reported
