### ISSUE TITLE
Recursive Common Table Expression like in SQL

### ISSUE THREAD

**Issue by vukasinpetrovic** [dotnet/efcore#24177] opened 2021-02-17 21:11 UTC
I was searching for a recursive SQL CTE (Common table expression) in EF Linq for couple of days, but I couldn't find it. My current implementation, and only options for now, is custom SQL that is executed on dbContext via .FromSqlRaw(mySqlStringWithCte). Is there any way to do it via Linq syntax in order to avoid plain SQL or stored procedure (whole project is in Linq)? 

My purpose for recursive SQL CTE is to do search of hierarchically structured data in table (id-parentId).

EF Core version: 3.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: 3.1
Operating system: Windows 10 & OSX
IDE: Visual studio 2019 & IntelliJ Rider

**Comment by roji** [comment] 2021-02-17 21:15
Duplicate of #2865

**Comment by roji** [comment] 2021-02-17 21:15
EF doesn't currently support translating to CTEs, for now you indeed have to use raw SQL for these.

**Comment by vukasinpetrovic** [comment] 2021-02-17 21:32
@roji Thank you for quick response. Do you plan to implement that feature soon?

**Comment by roji** [comment] 2021-02-18 06:55
@vukasinpetrovic CTEs definitely aren't in the plan for EF Core 6.0. We've generally seen little interest from users in this over the years - #2865 has been open since 2015 and has only 5 votes on it, while other issues have hundreds of votes.

**Comment by vukasinpetrovic** [comment] 2021-02-18 07:01
@roji Is there a better approach to hierarchical search than cte, considering performance? I could create recursive query calls with linq, but I think cte is faster.

**Comment by ilmax** [comment] 2021-02-18 07:08
@vukasinpetrovic HierarchyId may be an option if you're on Sql server and EF core [supports it](https://docs.microsoft.com/en-us/ef/core/extensions/#entityframeworkcoresqlserverhierarchyid)

**Comment by vukasinpetrovic** [comment] 2021-02-19 14:22
> @vukasinpetrovic HierarchyId may be an option if you're on Sql server and EF core [supports it](https://docs.microsoft.com/en-us/ef/core/extensions/#entityframeworkcoresqlserverhierarchyid)

I'm looking into HierarchyId this morning. It looks nice, but I'm not sure if MySQL supports it. I cannot find it in MySQL.

**Comment by roji** [comment] 2021-02-19 16:22
@vukasinpetrovic HierarchyId is a SQL Server feature. You'll have to check if there's something similar in MySQL (PG has something called ltree).

**Comment by vukasinpetrovic** [comment] 2021-02-19 16:40
Thank you guys for quick responses. I'll close this issue for now.

**Closed** 2022-10-16 19:24 UTC
Labels: customer-reported
