### ISSUE TITLE
Aggregate of count on a nested table (one to many relationship) throws an exception 

### ISSUE THREAD

**Issue by gustavnavar** [dotnet/efcore#34020] opened 2024-06-18 13:07 UTC
I want to calculate aggregates of count of rows on a nested table (one to many relationship). 

The code that throws this exception is any of the following Linq statements:
```c#
var sum = _context.Orders.Sum(r => r.OrderDetails.Count);
var avg = _context.Orders.Average(r => r.OrderDetails.Count);
var max = _context.Orders.Max(r => r.OrderDetails.Count);
var min = _context.Orders.Min(r => r.OrderDetails.Count);
``` 

EF creates SQL queries for each statement that MS SQL Server can not execute and returns an exception:
```sql
SELECT COALESCE(SUM((
﻿          SELECT COUNT(*)
﻿          FROM [Order Details] AS [o0]
﻿          WHERE [o].[OrderID] = [o0].[OrderID])), 0)
﻿      FROM [Orders] AS [o]

SELECT AVG(CAST((
﻿          SELECT COUNT(*)
﻿          FROM [Order Details] AS [o0]
﻿          WHERE [o].[OrderID] = [o0].[OrderID]) AS float))
﻿      FROM [Orders] AS [o]

SELECT MAX((
﻿          SELECT COUNT(*)
﻿          FROM [Order Details] AS [o0]
﻿          WHERE [o].[OrderID] = [o0].[OrderID]))
﻿      FROM [Orders] AS [o]

SELECT MIN((
﻿          SELECT COUNT(*)
﻿          FROM [Order Details] AS [o0]
﻿          WHERE [o].[OrderID] = [o0].[OrderID]))
﻿      FROM [Orders] AS [o]
```

The exception returned is:
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot perform an aggregate function on an expression containing an aggregate or a subquery.
``` 

I was expecting that SQL queries created by EF would be as:
```sql
SELECT SUM(d.totalColumn) FROM (SELECT (SELECT COUNT(*) FROM [Order Details] AS od WHERE o.orderid = od.orderid) FROM orders AS o) AS d(totalColumn)

SELECT AVG(CAST(d.totalColumn AS FLOAT)) FROM (SELECT (SELECT COUNT(*) FROM [Order Details] AS od WHERE o.orderid = od.orderid) FROM orders AS o) AS d(totalColumn)

SELECT MAX(d.totalColumn) FROM (SELECT (SELECT COUNT(*) FROM [Order Details] AS od WHERE o.orderid = od.orderid) FROM orders AS o) AS d(totalColumn)

SELECT MIN(d.totalColumn) FROM (SELECT (SELECT COUNT(*) FROM [Order Details] AS od WHERE o.orderid = od.orderid) FROM orders AS o) AS d(totalColumn)
```

These SQL queries are executed by MS SQL server with no issues.

I'm using the Northwind sample database for testing of this issue with the following model:
```c#
public partial class Order
{
    [Key]
    public int OrderID { get; set; }
    public string CustomerID { get; set; }
    public int? EmployeeID { get; set; }
    public DateTime? OrderDate { get; set; }
    public DateTime? RequiredDate { get; set; }
    public DateTime? ShippedDate { get; set; }
    public int? ShipVia { get; set; }
    public decimal? Freight { get; set; }
    public string ShipName { get; set; }
    public string ShipAddress { get; set; }
    public string ShipCity { get; set; }
    public string ShipRegion { get; set; }
    public string ShipPostalCode { get; set; }
    public string ShipCountry { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; }

    public Order()
    {
        this.OrderDetails = new HashSet<OrderDetail>();
    }
}

[Table("Order Details")]
public partial class OrderDetail
{
    public int OrderID { get; set; }
    public int ProductID { get; set; }
    public decimal UnitPrice { get; set; }
    public short Quantity { get; set; }
    public float Discount { get; set; }

    public OrderDetail()
    { }
}
```

Sample code: 
[AggregatesOfCountDemo.zip](https://github.com/user-attachments/files/15887028/AggregatesOfCountDemo.zip)

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer 8.0.6
Target framework: .NET 8.0
Operating system: Windows Pro 11
IDE: Visual Studio 2022 17.10.2

**Comment by roji** [comment] 2024-06-19 14:18
Makes sense. Note that the problem with the query currently being generated is on SQL Server only, i.e. other databases should work just fine; otherwise the two query forms seem pretty much equivalent.

Putting on the backlog.

**Comment by roji** [comment] 2024-07-20 13:55
Duplicate of https://github.com/dotnet/efcore/issues/34256

**Comment by roji** [comment] 2024-07-20 13:55
Am going to use https://github.com/dotnet/efcore/issues/34256 to track working around the SQL Server limitation in EF.

**Closed by roji** 2024-07-20 13:55 UTC
Labels: type-bug, customer-reported, area-sqlserver
