### ISSUE TITLE
Please add Visual Tooling for database first scenarios in Visual Studio

### ISSUE THREAD

**Issue by pishah** [dotnet/efcore#8799] opened 2017-06-09 13:36 UTC
The visual tooling and templates seem to be missing for Core projects. And the online tools that show up do not seem to work with Visual Studio 2017. The learning material is also very sparse when it comes to using Entity Framework with Core projects. I am not an expert, just learning. I would be nice if this learning experience could be made better. Thank you

**Comment by ErikEJ** [comment] 2017-06-11 12:37
I have free Visual Tooling that works with VS 2017 - https://twitter.com/ErikEJ/status/834452863380250624

**Comment by divega** [comment] 2017-06-11 13:47
@incendy thanks for the feedback. Could you please detail what specific tasks you found hard to perform without the help of UI in Visual Studio? E.g.:

- getting started using EF Core in an application, 
- creating an EF Core model based on an existing database, 
- updating the model based on changes on the database, 
- creating entity classes and adding them to the model, 
- configuring the mapping of entity classes and their properties,
- creating migrations, 
- applying migrations, 
- other migrations commands,
- deploying applications to a server and provisioning the database
- merging migrations from separate developers in a team environment, 
- editing and selecting or finding connection strings, 
- finding appropriate online documentation for each task
- others

Also did you find the topics at https://docs.microsoft.com/ef/core/ lacking? In what way? Anything particularly useful that was missing?

**Comment by incendy** [comment] 2017-06-11 17:43
I imagine after some time I would get used to it. But I am struggling with everything about the process thus far. Just finding out where to start was difficult due to a lack of relevant learning material or instructions when it comes to Database First design. I am still pretty lost.

In the past, I would open up Visual Studio, choose Add ADO.net Entity Model and was ready to go within 30 seconds. With Core, I am going on 80 hours now and still do not have data working in my project.  Which means I cannot really answer any of the questions passed your first 5. I guess all those years of being spoiled with Templates kept me from having to learn enough for this new CLI Studio of our future.

**Comment by ErikEJ** [comment] 2017-06-11 17:46
Did you try my GUI tool, should be up and running in  29 seconds 😄 ?

**Comment by incendy** [comment] 2017-06-11 18:47
I just did Erik and you are right. 29 second easy! You are a genius. One question though, if I need to update the model, is it best to Delete the current model and regenerate or can I just run it over the top?

**Comment by ErikEJ** [comment] 2017-06-11 19:19
Delete current - notice that the generated classes are partial

**Comment by incendy** [comment] 2017-06-11 19:21
That works for me. Thank you again

**Comment by ajcvickers** [comment] 2017-06-12 19:23
Based on the discussion, it looks like this is a duplicate of #5837. If there is some other visual functionality you are looking for (see list from @divega above), then please open an issue with details of what you would like to see.

**Closed** 2022-10-16 11:07 UTC
