### ISSUE TITLE
AsNoTracking after projection causes no translation for skip order where

### ISSUE THREAD

**Issue by msmolka** [dotnet/efcore#14477] opened 2019-01-21 09:57 UTC
When I will add AsNoTracking after projection, this won't be translated to sql
### Steps to reproduce

```c#
var query = context.Logs.Select(l => new LogDisplay {
  Id = I.Id,
  Message = l.Message
})
.AsNoTracking();
```
`LogDisplay` is model not assigned to context. just projection model.
then make 
```c#
var result = await query.Take(10).ToListAsync();
```
Take is not translated to SQL query and all records from db are collected. and then it is translated locally.

### Further technical details
EF Core version: 2.20
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.9.5)

**Comment by ajcvickers** [comment] 2019-01-23 01:36
@msmolka I have not been able to reproduce what you are seeing--my full test code is below. Can you post a small, runnable, project/solution or code listing (like below) that reproduces what you are seeing?

```C#
public class Log
{
    public int Id { get; set; }
    public string Message { get; set; }
}

public class LogDisplay
{
    public int Id { get; set; }
    public string Message { get; set; }
}

public class BloggingContext : DbContext
{
    private static readonly LoggerFactory Logger
        = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseLoggerFactory(Logger)
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    public DbSet<Log> Logs { get; set; }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var query = context.Logs.Select(l => new LogDisplay
                {
                    Id = l.Id,
                    Message = l.Message
                })
                .AsNoTracking();

            var result = await query.Take(10).ToListAsync();
        }
    }
}
```
Log:
```
warn: Microsoft.EntityFrameworkCore.Query[10102]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      Query: '(from Log l in DbSet<Log> select new LogDisplay{ {
          Id = [l].Id, ,
          Message = [l].Message ...' uses a row limiting operation (Skip/Take) without OrderBy which may lead to unpredictable results.
dbug: Microsoft.EntityFrameworkCore.Query[10104]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      Optimized query model:
      '(from Log l in DbSet<Log>
      select new LogDisplay{
          Id = [l].Id,
          Message = [l].Message
      }
      ).Take(__p_0)'
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      (QueryContext queryContext) => IAsyncEnumerable<LogDisplay> _InterceptExceptions(
      |__ source: IAsyncEnumerable<LogDisplay> _ShapedQuery(
      |   |__ queryContext: queryContext,
      |   |__ shaperCommandContext: SelectExpression:
      |   |       SELECT TOP(@__p_0) [l].[Id], [l].[Message]
      |   |       FROM [Logs] AS [l],
      |   |__ shaper: (QueryContext queryContext | ValueBuffer l) => new LogDisplay{
      |           Id = int TryReadValue(l, 0, Log.Id),
      |           Message = string TryReadValue(l, 1, Log.Message)
      |       }
      |__ ),
      |__ contextType: BloggingContext,
      |__ logger: DiagnosticsLogger<Query>,
      |__ queryContext: Unhandled parameter: queryContext)
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (78ms) [Parameters=[@__p_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
      SELECT TOP(@__p_0) [l].[Id], [l].[Message]
      FROM [Logs] AS [l]
```

**Comment by msmolka** [comment] 2019-01-23 11:18
Hello @ajcvickers 
I've spent some time to evaluate this issue. It is more complex. It is related not to `AsNoTrafic` itself but interface and dynamic linq expressions:

I've finally made code for you EFCore 2.2.0:

```c#
using System;

namespace ConsoleAppAsNoTracking
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Reflection;
    using System.Threading.Tasks;

    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.Logging;
    using Microsoft.Extensions.Logging.Console;

    public class Log
    {
        public int Id { get; set; }
        public bool Deleted { get; set; }
        public virtual LogEx LogEx { get; set; }
        public virtual Log2 Log2 { get; set; }
    }

    public class LogEx
    {
        public int Id { get; set; }
        public int LogId { get; set; }
        public virtual Log Log { get; set; }
        public string Message { get; set; }
    }

    public class Log2
    {
        public int Id { get; set; }
        public int LogId { get; set; }
        public virtual Log Log { get; set; }
        public string Message { get; set; }
    }

    public class LogDisplay : ILogDisplay
    {
        public int Id { get; set; }
        public string MessageEx { get; set; }
        public string Message2 { get; set; }
    }

    public interface ILogDisplay
    {
        int Id { get; set; }
        string MessageEx { get; set; }

    }

    public class BloggingContext : DbContext
    {
        private static readonly LoggerFactory Logger
            = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseLoggerFactory(Logger)
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
        }

       
        public DbSet<Log> Logs { get; set; }

        public DbSet<LogEx> LogEx { get; set; }

        public DbSet<Log2> Logs2 { get; set; }
    }

    public static class Extensions
    {
        public static IQueryable<T> OrderBy<T>(this IQueryable<T> source, string ordering)
        {
            var type = typeof(T);
            var property = type.GetProperty(ordering);
            var parameter = Expression.Parameter(type, "p");
            var propertyAccess = Expression.MakeMemberAccess(parameter, property);
            var orderByExp = Expression.Lambda(propertyAccess, parameter);
            MethodCallExpression resultExp = Expression.Call(typeof(Queryable), "OrderBy", new Type[] { type, property.PropertyType }, source.Expression, Expression.Quote(orderByExp));
            return source.Provider.CreateQuery<T>(resultExp);
        }
    }

    public class Program
    {
        public static async Task Main()
        {
            using (var context = new BloggingContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                // correct 1
                var result1 = await GetInterface(context).Skip(10).Take(10).ToListAsync();

                // correct 2
                var result4 = await GetQueryable(context).OrderBy("MessageEx").Skip(10).Take(10).ToListAsync();

                // incorrect
                var result2 = await GetInterface(context).OrderBy("MessageEx").Skip(10).Take(10).ToListAsync();

                // incorrect 2
                var result3 = await GetInterfaceAsNoTracking(context).OrderBy("MessageEx").Skip(10).Take(10).ToListAsync();
                
            }
        }

        private static IQueryable<LogDisplay> GetQueryable(BloggingContext context)
        {
            var query = context.Logs
                .Where(l => !l.Deleted)
                .Select(l => new LogDisplay
                {
                    Id = l.Id,
                    MessageEx = l.LogEx.Message,
                    Message2 = l.Log2.Message
                });

            return query;
        }

        private static IQueryable<ILogDisplay> GetInterfaceAsNoTracking(BloggingContext context) => GetQueryable(context).AsNoTracking();

        private static IQueryable<ILogDisplay> GetInterface(BloggingContext context) => GetQueryable(context);

        
    }
}

```

**Comment by ajcvickers** [comment] 2019-01-25 19:32
@smitpatel to find the dupe.

**Comment by smitpatel** [comment] 2019-01-26 01:31
Duplicate of #14118

**Closed** 2022-10-16 13:48 UTC
Labels: closed-duplicate, customer-reported
