### ISSUE TITLE
SqlLite.FunctionalTests sometimes fail on Ubuntu

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/efcore#8642] opened 2017-05-30 21:50 UTC
The SqlLite.FunctionalTests sometimes fail with:
```
The active test run was aborted. Reason: 
null
```
Obviously that's not a great error message. There is a bug for it https://github.com/Microsoft/vstest/issues/527

Here:
http://aspnetci/viewLog.html?buildId=226869&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR&tab=buildLog#_focus=47267
and
http://aspnetci/viewLog.html?buildId=228289&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR&tab=buildLog#_focus=47170
are two examples of the tests failing

**Comment by smitpatel** [comment] 2017-05-30 21:52
Can you get this file for us?
`Results File: /datadrive/33bdfc1cae7b2a38/.r/EntityFramework/test/EFCore.Sqlite.FunctionalTests/TestResults/_aspnetci-a-111_2017-05-30_21:11:22.trx`

**Comment by BrennanConroy** [comment] 2017-05-30 21:54
I'll try

**Comment by BrennanConroy** [comment] 2017-05-30 22:04
We'll have to wait for it to fail again to get the file

**Comment by smitpatel** [comment] 2017-06-13 23:24
I have seen this error happening on travis once or twice. I tried to reproduce this locally.
I have been running SQLite.FunctionalTests in a loop on my Ubuntu VM for last 5h. I am still not getting error locally.

There is nothing we can do if we cannot get the error locally or sufficient log data from remote machine.
Clearing milestone for re-triage, this may be flaky but unless the test running framework gives us some information, there is nothing actionable.

**Comment by BrennanConroy** [comment] 2017-06-13 23:26
Try running it on one of our machines that it fails on. It happens very frequently.
________________________________

**Comment by smitpatel** [comment] 2017-06-13 23:47
@ryanbrandenburg

**Comment by ajcvickers** [comment] 2017-06-16 19:46
@Eilon We discussed this in triage this morning. @smitpatel has tried running many (30+) times on on one of our machines that it fails on, but it never fails for him. Right now we are completely out of ideas on how to proceed further with this. Any suggestions?

**Comment by Eilon** [comment] 2017-06-18 03:55
Where do we think this issue exists? Is it in the test runner, or is it related to databases?

**Comment by smitpatel** [comment] 2017-06-18 14:18
We are uncertain about the cause of error but the error message is something which is due to test runner, first we have to unwrap test runner to see if there is more info available. But we don't know how.

**Comment by Eilon** [comment] 2017-06-20 17:10
Do we know who can help? This is an area where I have almost zero familiarity unfortunately.

**Comment by smitpatel** [comment] 2017-06-20 17:16
AFAIK, no one in EF team has any insights.

**Comment by Eilon** [comment] 2017-06-21 02:31
Can we try to add more diagnostic info around where this error occurs so that if it happens again we have a better chance of figuring it out?

**Comment by ajcvickers** [comment] 2017-06-21 20:13
Discussed again in triage and decided that we need to get more info from the test runner. Commented on https://github.com/Microsoft/vstest/issues/527 asking for more info. Marking as blocked for now until we get some info from the vstest team.

**Comment by ajcvickers** [comment] 2017-06-26 17:51
Self-assigning and will discuss with @Eilon

**Comment by smitpatel** [comment] 2017-06-26 17:53
I ran build.sh in loop over the Ubuntu agent where this was failing in CI. I still did not hit the error.

**Comment by BrennanConroy** [comment] 2017-06-26 17:56
I can hit this on a personal VM by running just the Sqlite tests over and over. `dotnet test --no-build` on the Sqlite.FunctionalTests folder, build.sh takes far too long.

**Comment by smitpatel** [comment] 2017-06-26 17:57
I ran on my VM over 500 times still did not hit it. It seems less like code issue and more like machine config issue.

**Comment by smitpatel** [comment] 2017-06-26 18:31
@BrennanConroy - Since you are able to get the repro, please get the log files like mentioned here https://github.com/Microsoft/vstest/issues/627#issuecomment-310286859

And provide them to vstest team for further investigation.

**Comment by ryanbrandenburg** [comment] 2017-07-20 17:28
This fails the Ubuntu-Universe build more often than it passes. Can we prioritize it?

**Comment by ajcvickers** [comment] 2017-07-20 17:31
@BrennanConroy Any update?

**Comment by bricelam** [comment] 2017-07-20 19:17
Did any of my fixes in `dev` help?

**Comment by smitpatel** [comment] 2017-07-20 19:30
@bricelam - If it is still failing then perhaps no

**Comment by bricelam** [comment] 2017-07-20 19:55
Confirmed: Didn't help.

**Comment by ajcvickers** [comment] 2017-07-21 23:08
@BrennanConroy I was just chatting with @smitpatel about this. It seems that right now you are the only person able to reproduce this issue outside of Travis. Can you please provide the requested information above to the vstest team so that we can get some traction to try to move this forward? /cc @Eilon

**Comment by BrennanConroy** [comment] 2017-07-27 16:16
I tried disabling parallel tests for Sqlite.FunctionalTests and haven't seen the issue repro. We could do this as a workaround.

I've tried what the vstest team suggested and it provided no useful information.

**Comment by Eilon** [comment] 2017-08-06 00:39
@BrennanConroy - there's likely a real bug here, so having a workaround is nice, but not enough. Is it possible to somehow snapshot the VM so that the VSTest team can repro it more easily and debug? Maybe some other crazy idea??

**Comment by BrennanConroy** [comment] 2017-08-08 19:32
I disabled `String_ends_with_not_equals_nullable_column` and `String_ends_with_equals_nullable_column`  tests and haven't hit the test issue yet. Will keep running to make sure. I also have some hard to read logs from when it failed if anyone wants to take a look.

**Comment by smitpatel** [comment] 2017-08-08 20:12
Share the logs.

**Comment by Eilon** [comment] 2017-08-08 22:42
@BrennanConroy - can we share those with the VSTest folks?

**Closed** 2022-10-16 11:06 UTC
Labels: blocked, closed-could-not-reproduce, punted-for-2.0
