### ISSUE TITLE
Provide API for returning Func<TEntity, bool> predicated based on keys

### ISSUE THREAD

**Issue by Liero** [dotnet/efcore#27623] opened 2022-03-11 11:51 UTC
## Problems I'm trying to solve

In short I want to do this:

    object[] keys = ....;
    dbContext.Set<TEntity>().Local.Find(keys)
    //or
    dbContext.ChangeTracker.Entries<TEntity>().Find(keys);

or

    bool EqualsByPK(TEntity entity1,  TEntity entity2);

or

resolve duplicates as described in the [change-tracking/identity-resolution docs](https://docs.microsoft.com/en-us/ef/core/change-tracking/identity-resolution#resolve-duplicates).

 In other words, find out, whether entity with specified key is already tracked:

       context.ChangeTracker.TrackGraph(entity, node =>
            {
                var entityType = node.Entry.Metadata;                
                                
                //documented way is not generic because of hard code Id property
                //var keyValue = node.Entry.Property("Id").CurrentValue; //hard coded ID
                //var existingEntity = node.Entry.Context.ChangeTracker.Entries()
                //    .FirstOrDefault(
                //        e => Equals(e.Metadata, entityType)
                //             && Equals(e.Property("Id").CurrentValue, keyValue)); //hard coded ID
                
                object[] keyValues = entityType.GetKeyValues(node.Entry.Entity); //new api
                //object[] keyValues = entityType.GetKeys()
                //    .FirstOrDefault(key => key.IsPrimaryKey())?.Properties
                //    .Select(property => node.Entry.CurrentValues[property])
                //    .ToArray();
                  

                var predicate = entityType.CreatePrimaryKeyPredicate(keyValues); //new API
                    .dbContext.ChangeTracker.Entries().Where(e => Equals(e.Metadata, entityType))
                    .FirstOrDefault(e => predicate(e.Entity));

                var existingEntity = dbContext.ChangeTracker.Entries().FirstOrDefault(predicate);
                    
                if (existingEntity == null)
                {
                    Console.WriteLine($"Tracking {entityType.DisplayName()} entity with key value {keyValue}");

                    node.Entry.State = EntityState.Modified;
                }
                else
                {
                    Console.WriteLine($"Discarding duplicate {entityType.DisplayName()} entity with key value {keyValue}");
                }
            });

Proposed solution:

 new APIs:
 
 1. `object[] GetKeyValues(this IEntityType entityType, object Entity);`
 2. `Func<bool, object>(this IEntityType entityType, entityType.CreatePrimaryKeyPredicate(keyValues))`
 
    object[] keyValues = entityType.GetKeyValues(node.Entry.Entity);
                //object[] keyValues = entityType.GetKeys()
                //    .FirstOrDefault(key => key.IsPrimaryKey())?.Properties
                //    .Select(property => node.Entry.CurrentValues[property])
                //    .ToArray();
                var predicate = entityType.CreatePrimaryKeyPredicate(keyValues);
                dbContext.ChangeTracker.Entries().Where(e => Equals(e.Metadata, entityType))
                    .FirstOrDefault(predicate);

**Comment by ajcvickers** [comment] 2022-03-11 11:53
Duplicate of #7391.

**Closed** 2022-10-16 20:28 UTC
Labels: customer-reported
