### ISSUE TITLE
How can you use character set support when creating a database

### ISSUE THREAD

**Issue by honorduan** [dotnet/efcore#15360] opened 2019-04-15 08:41 UTC
When I use the mysql Database database.ensurecreated () interface, you specify the character set that creates the Database.

**Comment by ajcvickers** [comment] 2019-04-15 19:36
Closing as a duplicate of #6577. You might also want to consider following up with the MySQL provider authors as to whether there is a provider-specific way to do this.

**Closed** 2022-10-16 14:17 UTC
Labels: closed-duplicate, customer-reported
