### ISSUE TITLE
AsSplitQuery : Remove LEFT JOIN in child query when split the query and join self

### ISSUE THREAD

**Issue by universorum** [dotnet/efcore#31700] opened 2023-09-12 11:44 UTC
When we split the query they include self
```
context.Users.Include(x => x.CreateBy)
        .Include(x => x.Orders)
        .Include(x => x.Scores)
        .AsNoTracking()
        .AsSplitQuery()
        .ToList();
```

It will join self in all generated query
```
SELECT "u"."Id", "u"."CreateById", "u0"."Id", "u0"."CreateById"
FROM "Users" AS "u"
         LEFT JOIN "Users" AS "u0" ON "u"."CreateById" = "u0"."Id"
ORDER BY "u"."Id", "u0"."Id";
```
```
SELECT "o"."Id", "o"."BuyerId", "o"."Value", "u"."Id", "u0"."Id"
FROM "Users" AS "u"
         LEFT JOIN "Users" AS "u0" ON "u"."CreateById" = "u0"."Id"
         INNER JOIN "Orders" AS "o" ON "u"."Id" = "o"."BuyerId"
ORDER BY "u"."Id", "u0"."Id";
```
```
SELECT "s"."Id", "s"."StudentId", "s"."Value", "u"."Id", "u0"."Id"
FROM "Users" AS "u"
         LEFT JOIN "Users" AS "u0" ON "u"."CreateById" = "u0"."Id"
         INNER JOIN "Score" AS "s" ON "u"."Id" = "s"."StudentId"
ORDER BY "u"."Id", "u0"."Id";
```

Look like it only use for sorting.
But why we need order it in all query? 
Is it possible to remove that?
I think a query like this would work well:

```
SELECT "o"."Id", "o"."BuyerId", "o"."Value", "u"."Id"
FROM "Users" AS "u"
         INNER JOIN "Orders" AS "o" ON "u"."Id" = "o"."BuyerId"
ORDER BY "u"."Id";
```
```
SELECT "s"."Id", "s"."StudentId", "s"."Value", "u"."Id"
FROM "Users" AS "u"
         INNER JOIN "Score" AS "s" ON "u"."Id" = "s"."StudentId"
ORDER BY "u"."Id";
```
Repo

```
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;


using (var context = new MyContext())
{
    if (context.Database.EnsureCreated())
    {
        var user = new User();
        context.Users.Add(user);
        context.Users.Add(new User { CreateBy = user });
        context.SaveChanges();
    }
}


using (var context = new MyContext())
{
    var result = context.Users.Include(x => x.CreateBy)
        .Include(x => x.Orders)
        .Include(x => x.Scores)
        .AsNoTracking()
        .AsSplitQuery()
        .ToList();
}

public class MyContext : DbContext
{
    public DbSet<User>  Users  { get; set; }
    public DbSet<Order> Orders { get; set; }
    public DbSet<Score> Score  { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) =>
        optionsBuilder.UseSqlite("Data Source=application.db;").LogTo(Console.WriteLine, LogLevel.Information);
}

public class User
{
    public int  Id         { get; set; }
    public int? CreateById { get; set; }

    public virtual User?               CreateBy { get; set; }
    public virtual ICollection<User>?  Created  { get; set; }
    public virtual ICollection<Order>? Orders   { get; set; }
    public virtual ICollection<Score>? Scores   { get; set; }
}

public class Order
{
    public int Id      { get; set; }
    public int BuyerId { get; set; }
    public int Value   { get; set; }

    public virtual required User Buyer { get; set; }
}

public class Score
{
    public int Id        { get; set; }
    public int StudentId { get; set; }
    public int Value     { get; set; }

    public virtual required User Student { get; set; }
}
```

Microsoft.EntityFrameworkCore 7.0.10
Microsoft.EntityFrameworkCore.Sqlite 7.0.10

Possibly related: #29182

**Comment by ajcvickers** [comment] 2023-09-25 16:59
> Look like it only use for sorting. But why we need order it in all query?

Sorting is needed so that EF Core can correctly fixup the related entities after they have been returned.

**Comment by ajcvickers** [comment] 2023-09-25 17:00
See also #29171.

**Comment by stevendarby** [comment] 2023-09-25 17:41
> > Look like it only use for sorting. But why we need order it in all query?
> 
> 
> 
> Sorting is needed so that EF Core can correctly fixup the related entities after they have been returned.

Not for reference navigations. I believe this is a duplicate of https://github.com/dotnet/efcore/issues/29182. Please upvote if you agree @universorum

**Closed** 2023-10-04 06:30 UTC
Labels: customer-reported

**Comment by roji** [comment] 2023-10-04 06:32
Duplicate of #29182

**Comment by stevendarby** [comment] 2023-11-03 22:03
Sorry to be a pain @universorum, and possibly a bit cheeky of me, but I meant if you could up-vote the other open issue rather than my comment, as this would slightly increase its chances of it getting fixed. (I've identified 3 other duplicates, it's a shame they can't be converted to up-votes!)
