### ISSUE TITLE
Scaffold - DbContext rename entity class name and field names

### ISSUE THREAD

**Issue by JuanIrigoyen** [dotnet/efcore#5953] opened 2016-07-01 23:31 UTC
In the previous version when you run the Scaffold - DbContext command this generated the names of tables and fields as they exist in SQL Server, for example if the table is called 'Customer_type' the entity class is called 'Customer_type' but in the last version Scaffold - DbContext renames the table from 'Customer_type' to 'CustomerType' , the same behavior also applies to the fields, there is a way around this behavior and that the names of entities and fields are as before, the same as the names of the database.

**Comment by natemcmaster** [comment] 2016-07-01 23:57
Duplicate of #5947 and https://github.com/aspnet/EntityFramework/issues/3987

**Closed** 2022-10-16 09:48 UTC
