### ISSUE TITLE
HasQueryFilter not working

### ISSUE THREAD

**Issue by obarlik** [dotnet/efcore#16461] opened 2019-07-05 10:43 UTC
Hello,

I'm having trouble with EntityTypeBuilder<>.HasQueryFilter() method.

In my case I tried to implement "soft deletion". 
For example I've a User entity class with an "int GarbageId" property for deleted records.
When this value is 0, the record becomes an available record.

So, I've set a QueryFilter as described, by overriding OnModelCreating as described.

``` csharp
modelBuilder.Entity<User>().HasQueryFilter(u => u.GarbageId == 0);`
```

I expect this setting would be effective on all queries on selected DBSet.
Including anything that access "DbSet<User> Users" of dbcontext.

But this seems to have no effect on DB select query. 
Therefore the records with "GarbageId" value other than 0 are selected.

Am I doing something wrong?
If not, can you send me a working simple project source code?

> EF Core version: 3.0.0-preview6.19304.10
> Database Provider: Microsoft.EntityFrameworkCore.SqlServer
> Operating system: Windows 10
> IDE: Visual Studio 2019 16.2.0 Preview 3.0

**Comment by ajcvickers** [comment] 2019-07-05 15:28
First, many thanks for trying preview 6. We really appreciate people trying the previews and filing issues on what they find.

If you haven't seen it already, there is some good information in the [preview announcement post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/) about the changes that are happening to LINQ queries for EF Core 3.0. Preview 6 is the first release containing these changes, which means we are both expecting things to be broken, but at the same time very grateful for everyone who tries the release and generated feedback.

Closing as a duplicate of #15264

**Comment by filipbekic01** [comment] 2019-08-14 13:30
Not fixed in preview7?

**Closed** 2022-10-16 14:29 UTC
Labels: customer-reported
