### ISSUE TITLE
Configure OwnedType via convention

### ISSUE THREAD

**Issue by glatzert** [dotnet/efcore#30251] opened 2023-02-10 14:04 UTC
I'm trying to configure an owned type from a third-party assembly, as owned type by convention.

Esentially I want to archieve the following:
```
configurationBuilder.Properties<L10nString>()
            .AreOwned(x => x.ToJson())
```

But I cannot figure out how to get there via `IConventions` or `ModelConfigurationBuilder`.
Via ModelBuilder I'd do something like that:
```
foreach(var entityType in modelBuilder.Model.GetEntityTypes())
        {
            foreach(var property in entityType.ClrType.GetProperties())
            {
                if (property.PropertyType != typeof(L10nString))
                    continue;

                modelBuilder.Entity(entityType.ClrType)
                    .OwnsOne(typeof(L10nString), property.Name,
                        ownedType => ownedType.ToJson());
            }
        }
```

But that would probably have side effects?

**Comment by ajcvickers** [comment] 2023-02-16 18:45
Duplicate of #6787. Make vote (👍) for that issue.

**Closed by ajcvickers** 2023-02-16 18:45 UTC
Labels: customer-reported
