### ISSUE TITLE
Cosmos: allow to specify a custom Json serializer and serialization options

### ISSUE THREAD

**Issue by alexeymarkov** [dotnet/efcore#19905] opened 2020-02-13 12:46 UTC
I am trying to make EF Core Cosmos provider working with camel case json but I could not find a way how to do it.
I could probably resolve SingletonCosmosClientWrapper, call Client property and assign SerializerOptions but this would not give me a possibility to provide a custom Json serializer if I want.
And I do not want to bind each property of each my entity with JsonProperty attribute or to call ToJsonProperty for all of them.

Somewhere in UseCosmos.

**Comment by AndriySvyryd** [comment] 2020-02-13 19:02
Duplicate of https://github.com/dotnet/efcore/issues/17306

**Closed** 2022-10-16 18:10 UTC
Labels: customer-reported
