### ISSUE TITLE
Ask for the "PrivacyInfo.xcprivacy" required by Apple

### ISSUE THREAD

**Issue by baihao** [dotnet/efcore#34029] opened 2024-06-19 08:11 UTC
Ask for the `PrivacyInfo.xcprivacy` manifest as required by Apple, please refer to the Apple's document https://developer.apple.com/documentation/bundleresources/privacy_manifest_files for the detailed information, thanks.

A `PrivacyInfo.xcprivacy` for macOS just like the page mentioned: https://devblogs.microsoft.com/dotnet/apple-privacy-manifest-support/

**Comment by SamMonoRT** [comment] 2024-07-09 13:31
@baihao - If I read the documentation correctly, the privacy manifest file makes assertions/assumptions for the actual app in question. Technically the onus is on the app developer to take that into account. Having the EF repo/libraries provide that option isn't right imo. Also, I don't think we call into any Apple APIs via this repo. 

What was the reasoning/thinking behind opening the issue on the EF repo?

**Comment by ajcvickers** [comment] 2024-08-12 08:33
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-08-12 08:33 UTC
Labels: type-enhancement, customer-reported, waiting-for-response
