### ISSUE TITLE
composite keys support the use of data annotation configure

### ISSUE THREAD

**Issue by Varorbc** [dotnet/efcore#25007] opened 2021-06-01 07:58 UTC
composite keys support the use of data annotation configure, just like [EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/data-annotations#composite-keys)

**Comment by roji** [comment] 2021-06-01 09:13
Duplicate of #11003

**Closed** 2022-10-16 19:36 UTC
Labels: customer-reported
