### ISSUE TITLE
Use getter to get count of collection without write in Select()

### ISSUE THREAD

**Issue by universorum** [dotnet/efcore#32224] opened 2023-11-03 09:17 UTC
For 1-N relationships, we can get count of child by this
```
Order.Select(x => new { x.Id, x.Items.Count });

SELECT "o"."Id", (
    SELECT COUNT(*)
    FROM "Item" AS "i"
    WHERE "o"."Id" = "i"."OrderEntityId") AS "Count"
FROM "Orders" AS "o"
```

But it can't work
```
Order.Select(x => new { x.Id, x.Count });

SELECT "o"."Id"
FROM "Orders" AS "o"
```

```
class Order
{
    public int Id { get; set; }
    public int Count => Items.Count;
    public ICollection<Item> Items { get; }
}
```

My use case:
```
public abstract class Order
{
    public int Id { get; set; }
    public abstract int Count { get; }
}

public class Item
{
    public int Id { get; set; }
}

public class OrderEntity : Order
{ 
    public int Count => Items.Count;
    public ICollection<Item> Items { get; set; } = new List<Item>(0);
}

public abstract class OrderNotManageByDatabase : Order { /* some code */ }

public interface IOrderContext
{
    IQueryable<Order> Orders { get; }
}

public class Context : DbContext , IOrderContext
{
    public DbSet<OrderEntity> Orders { get; set; } = null!;
    IQueryable<Order> IOrderContext.Orders => Orders;
}

public static Extensions
{
    /* other some code to allow EF defined method like ToListAsync() work on List<T>... */
}
```

```
Builder.Services.AddScoped(typeof(IOrderContext), typeof(ApplicationDbContext));
Builder.Services.AddScoped(typeof(IOrderContext), typeof(OtherOrderProvider));
```
```
var context = GetContext(providerId);
_ = context.Where(x => true).ToListAsync();
```

Maybe we can have something like this?
```
b.Property(e => e.Count).HasComputedColumn(e => e.Items.Count);

public class OrderEntity : Order
{ 
    public int Count { get; }
    public ICollection<Item> Items { get; set; } = new List<Item>(0);
}
```

**Comment by roji** [comment] 2023-11-03 12:58
> public int Count => Items.Count;

You can't call an arbitrary .NET property inside your EF query, since EF has no way of knowing what the code in that property does (i.e. that the property is implemented as `Items.Count`).

**Comment by roji** [comment] 2023-11-03 12:58
Duplicate of #10768

**Closed** 2023-11-08 18:41 UTC
Labels: closed-duplicate, customer-reported
