### ISSUE TITLE
Incorrect type of MinValue and MaxValue in DatabaseSequence class

### ISSUE THREAD

**Issue by pfdsilva** [dotnet/efcore#22926] opened 2020-10-08 12:11 UTC
If a sequence is defined as a decimal in the database, then the max value of the sequence can be of 38 precision.

But the MinValue and MaxValue property's in DatabaseColumn class in the Microsoft.EntityFrameworkCore.Scaffolding.Metadata namespace are defined as long which can hold a max value of 9223372036854775807 and min value of -9223372036854775808.

There seems to be a mismatch between the max/min value that EFCORE can actually support and what the database actually allows.

https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Scaffolding/Metadata/DatabaseSequence.cs

EF Core version:
Microsoft.EntityFrameworkCore.Relational 
EFCORE 5.0 RC1

**Comment by ErikEJ** [comment] 2020-10-08 14:09
Duplicate of #18314

**Comment by pfdsilva** [comment] 2020-10-10 17:40
Why was this closed?

**Comment by ErikEJ** [comment] 2020-10-10 17:55
There is no good way to represent decimal(38,0) in .NET, so the implemented fix is to max out at long.MaxValue / long.MinValue

**Closed** 2022-10-16 19:04 UTC
Labels: closed-duplicate, customer-reported
