### ISSUE TITLE
EF migration failing

### ISSUE THREAD

**Issue by pgmolloy** [dotnet/efcore#9904] opened 2017-09-26 20:02 UTC

**Comment by pgmolloy** [comment] 2017-09-26 20:02
This is happening just using the tutorial I am unable to use EF migrations for 2.0 projects right now. Here's what I receive using the tutorial. My files are same as tutorial. Take a look at the second line being generated "rosoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]", where is this coming from.
PM> Update-Database -context 'BloggingContext'
rosoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
Update-Database : Exception calling "Substring" with "1" argument(s): "StartIndex cannot be less than zero.
Parameter name: startIndex"
At line:1 char:1
Update-Database -context 'BloggingContext'
  + CategoryInfo          : NotSpecified: (:) [Update-Database], MethodInvocationException
  + FullyQualifiedErrorId : ArgumentOutOfRangeException,Update-Database

**Comment by ajcvickers** [comment] 2017-09-27 18:53
@pgmolloy Can you post a link to the specific tutorial that you are following?

**Comment by ajcvickers** [comment] 2017-10-04 18:36
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by oneandy** [comment] 2018-02-23 07:11
Somewhere in our code, there is a Console output, with ":" in the string.  
This is the broken code

```c#
    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            Console.WriteLine(":"); //This is the end of the world.

            optionsBuilder.UseSqlServer(@"Server=;Database=EFGetStarted.ConsoleApp.NewDb;Trusted_Connection=True;");
        }
    }
```

**Comment by ajcvickers** [comment] 2018-02-23 16:26
@oneandy If you are reporting a bug, can you please open a new issue with a full description of the behavior and a runnable project/solution that demonstrates the issue.

**Comment by bricelam** [comment] 2018-03-01 23:56
@oneandy That was issue #8163

**Closed** 2022-10-16 11:51 UTC
Labels: closed-could-not-reproduce
