### ISSUE TITLE
EFCore 9 preview 7 - 'Specify caching for sequences' support has been removed

### ISSUE THREAD

**Issue by shvmgpt116** [dotnet/efcore#34551] opened 2024-08-28 09:03 UTC
## Ask a question
It seems [Specify caching for sequences ](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-9.0/whatsnew#specify-caching-for-sequences)support has been removed from Scaffolding and Migrations both in EFCore 9 preview 7.
`SequenceOperation `and `DatabaseSequence `classes don't have any properties to support sequence cache info.
Please can someone let me know why the support was removed in preview 7.

### Include provider and version information

EF Core version: EFCore 9 preview 7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows
IDE: Visual Studio 2022 17.4

**Comment by shvmgpt116** [comment] 2024-08-28 09:05
@ajcvickers 
@roji

**Comment by ajcvickers** [comment] 2024-08-28 09:57
@shvmgpt116 We were unable to agree on a final shape for the API surface.

**Comment by shvmgpt116** [comment] 2024-08-28 10:03
@ajcvickers Thanks for the quick response.
Are there any future plans to bring the support back? If yes, in which version of efcore.

**Comment by ajcvickers** [comment] 2024-08-28 10:10
I'll bring it up with the team.

**Comment by roji** [comment] 2024-08-28 23:13
Duplicate of #11261

**Closed** 2024-09-04 19:14 UTC
Labels: customer-reported
