### ISSUE TITLE
Behavior of multiple "Merge Using" statements in a single command

### ISSUE THREAD

**Issue by mrhartvig** [dotnet/efcore#34610] opened 2024-09-04 10:07 UTC
We have a workload (~60pods) that takes a message from Kafka, does some transformations and inserts multiple rows (normally below 100 rows) into a database. We are observing that sometimes our insert statements takes seconds to complete which we are trying to investigate. 

Our configuration is as follows:

1 Unique index (CompanyId (Guid), + 8 other columns) 
7 Non-unique indexes (at most 3 columns)
1 clustered (CompanyId (Guid), Id (bigint))

Our kafka partion key is the CompanyId, ie. no two pods works on the same CompanyId at the same time. 

Looking at the query store of the database, it's reported that 100% of the cost is spent at "Clustered Index Merge"
Looking at our temeletry we have observed that sometimes the SQL generated by Ef to insert the rows is divided into multiple Merge/insert commands.

A example, we have 103 rows we want to insert. Our configuration for MaxBatchSize is set to 100. We are seeing that it's divided into two roundtrips to the SQL which we expect.
The first roundtrip is splitted into 3 Merge statements, one with 4 rows, one with 2 and the last with 94 rows. The first roundtrip executes in 1,47 seconds.

```sql
SET IMPLICIT_TRANSACTIONS OFF;
SET NOCOUNT ON;
MERGE [BookingRowWithMetadata] USING (
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, 0),
--- 2 lines omitted  
(@p57, @p58, @p59, @p60, @p61, @p62, @p63, @p64, @p65, @p66, @p67, @p68, @p69, @p70, @p71, @p72, @p73, @p74, @p75, 3)) AS i ([CompanyId], [AccountingGroupId], [AdjustedPeriodEnd], [AdjustedPeriodStart], [BookkeepingId], [CreatedAt], [DispositionDate], [EmployeeId], [JsonBlob], [PayoutDate], [PensionId], [RunId], [SalaryPeriodCode], [SalaryPeriodEnd], [SalaryPeriodStart], [Type], [TypeIdentifier], [Unit], [Value], _Position) ON 1=0
WHEN NOT MATCHED THEN
INSERT ([CompanyId], [AccountingGroupId], [AdjustedPeriodEnd], [AdjustedPeriodStart], [BookkeepingId], [CreatedAt], [DispositionDate], [EmployeeId], [JsonBlob], [PayoutDate], [PensionId], [RunId], [SalaryPeriodCode], [SalaryPeriodEnd], [SalaryPeriodStart], [Type], [TypeIdentifier], [Unit], [Value])
VALUES (i.[CompanyId], i.[AccountingGroupId], i.[AdjustedPeriodEnd], i.[AdjustedPeriodStart], i.[BookkeepingId], i.[CreatedAt], i.[DispositionDate], i.[EmployeeId], i.[JsonBlob], i.[PayoutDate], i.[PensionId], i.[RunId], i.[SalaryPeriodCode], i.[SalaryPeriodEnd], i.[SalaryPeriodStart], i.[Type], i.[TypeIdentifier], i.[Unit], i.[Value])
OUTPUT INSERTED.[Id], i._Position;
MERGE [BookingRowWithMetadata] USING (
VALUES (@p76, @p77, @p78, @p79, @p80, @p81, @p82, @p83, @p84, @p85, @p86, @p87, @p88, @p89, @p90, @p91, @p92, @p93, 0),
(@p94, @p95, @p96, @p97, @p98, @p99, @p100, @p101, @p102, @p103, @p104, @p105, @p106, @p107, @p108, @p109, @p110, @p111, 1)) AS i ([CompanyId], [AccountingGroupId], [AdjustedPeriodEnd], [AdjustedPeriodStart], [BookkeepingId], [CreatedAt], [DispositionDate], [EmployeeId], [JsonBlob], [PayoutDate], [PensionId], [RunId], [SalaryPeriodCode], [SalaryPeriodEnd], [SalaryPeriodStart], [Type], [TypeIdentifier], [Value], _Position) ON 1=0
WHEN NOT MATCHED THEN
INSERT ([CompanyId], [AccountingGroupId], [AdjustedPeriodEnd], [AdjustedPeriodStart], [BookkeepingId], [CreatedAt], [DispositionDate], [EmployeeId], [JsonBlob], [PayoutDate], [PensionId], [RunId], [SalaryPeriodCode], [SalaryPeriodEnd], [SalaryPeriodStart], [Type], [TypeIdentifier], [Value])
VALUES (i.[CompanyId], i.[AccountingGroupId], i.[AdjustedPeriodEnd], i.[AdjustedPeriodStart], i.[BookkeepingId], i.[CreatedAt], i.[DispositionDate], i.[EmployeeId], i.[JsonBlob], i.[PayoutDate], i.[PensionId], i.[RunId], i.[SalaryPeriodCode], i.[SalaryPeriodEnd], i.[SalaryPeriodStart], i.[Type], i.[TypeIdentifier], i.[Value])
OUTPUT INSERTED.[Id], INSERTED.[Unit], i._Position;
MERGE [BookingRowWithMetadata] USING (
VALUES (@p112, @p113, @p114, @p115, @p116, @p117, @p118, @p119, @p120, @p121, @p122, @p123, @p124, @p125, @p126, @p127, @p128, @p129, @p130, 0),
--- 92 lines omitted 
(@p1879, @p1880, @p1881, @p1882, @p1883, @p1884, @p1885, @p1886, @p1887, @p1888, @p1889, @p1890, @p1891, @p1892, @p1893, @p1894, @p1895, @p1896, @p1897, 93)) AS i ([CompanyId], [AccountingGroupId], [AdjustedPeriodEnd], [AdjustedPeriodStart], [BookkeepingId], [CreatedAt], [DispositionDate], [EmployeeId], [JsonBlob], [PayoutDate], [PensionId], [RunId], [SalaryPeriodCode], [SalaryPeriodEnd], [SalaryPeriodStart], [Type], [TypeIdentifier], [Unit], [Value], _Position) ON 1=0
WHEN NOT MATCHED THEN
INSERT ([CompanyId], [AccountingGroupId], [AdjustedPeriodEnd], [AdjustedPeriodStart], [BookkeepingId], [CreatedAt], [DispositionDate], [EmployeeId], [JsonBlob], [PayoutDate], [PensionId], [RunId], [SalaryPeriodCode], [SalaryPeriodEnd], [SalaryPeriodStart], [Type], [TypeIdentifier], [Unit], [Value])
VALUES (i.[CompanyId], i.[AccountingGroupId], i.[AdjustedPeriodEnd], i.[AdjustedPeriodStart], i.[BookkeepingId], i.[CreatedAt], i.[DispositionDate], i.[EmployeeId], i.[JsonBlob], i.[PayoutDate], i.[PensionId], i.[RunId], i.[SalaryPeriodCode], i.[SalaryPeriodEnd], i.[SalaryPeriodStart], i.[Type], i.[TypeIdentifier], i.[Unit], i.[Value])
OUTPUT INSERTED.[Id], i._Position;
```

The second roundtrip is done in a single Merge statement with 3 rows and completes in 3,26 ms.

Looking at the "Id" column we observe that in our example we have 48 rows without gaps and the rest has gaps in between them.

### Questions

1. Would we benefit from using Hilo with a sequence that matches our batchsize/estimated number of rows?
2. Does the pods trip over each other when multiple are doing a "Clustered Index Merge" at the same time?
3. Is there any negative impact of having multiple merge statements in the same command?

### Include provider and version information

EF Core version: 8.0.6
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 8.0)
SQL managed instance,  Business Critical Premium-series 32vcores

**Comment by roji** [comment] 2024-09-04 13:08
In general, when there's a performance issue such as the above, I'd recommend concentrating on the SQL Server side - understand how the statements are being executed (plans etc.), seeing the timing in the log of SQL Server itself (to make sure the statements themselves are actually slow, and not some sort of network thing), etc. Otherwise, the 3 questions/suggestions are a sort of "shooting in the dark" - with luck, you may be able to stumble upon something that helps, but it's better to get to the bottom of the issue if at all possible.

As always, the best way forward is to try to reproduce your problem with a minimal repro. If this really is a concurrency-related problem, that becomes a bit more difficult, but it should still be possible to have multiple threads performing your workload in a loop and causing this to repro.

> Would we benefit from using Hilo with a sequence that matches our batchsize/estimated number of rows?

I'm not sure I see why - HiLo would simply remove the need for the MERGE statements to return the generated IDs (`OUTPUT INSERTED.[Id]`), though I'm noting that you also have `OUTPUT INSERTED.[Unit]`, so the OUTPUT clause wouldn't get eliminated anyway. But you can always try.

> Does the pods trip over each other when multiple are doing a "Clustered Index Merge" at the same time?

I wouldn't assume so - databases are engineered to work well with concurrency, and unless there's some special locking/configuration going on, concurrent inserts (including via MERGE) shouldn't interfere or block one another. Have you verified that the perf issue never occurs without concurrency?

> Is there any negative impact of having multiple merge statements in the same command?

Not as far as I know, that would be very surprising.

**Comment by mrhartvig** [comment] 2024-09-04 13:36
Thanks for the answer @roji.

I didn't even see the `OUTPUT INSERTED.[Unit]` which is a bit of a surprise as it's not something that's generated on the server side and is set by the client.  Will try to dig into that to see if there is any differences between the data inserted in the three statements. The code used to insert the rows is simply 
```c#
await _context.Entity.AddRangeAsync(chunk, cancellationToken);
await _context.SaveChangesAsync()
```
So that it generates different insert statements is out of our control (from my point of view).


We are, as you say, fumbling in the dark a bit with this issue. Will try to see if it's something that we can reproduce with a sample program and see if I can verify the logs. The sql server is hosted in azure so I'm not familiar with the options we have to look at the logs.

**Comment by roji** [comment] 2024-09-04 13:44
> I didn't even see the OUTPUT INSERTED.[Unit] which is a bit of a surprise as it's not something that's generated on the server side but is set by the client.

That's something that EF does based on how you configure the entity in the model - EF thinks that this column is database-generated (for whatever reason) and there needs to be fetched back. I can't really say why without seeing the model, but it should be easy to find out.

> The sql server is hosted in azure so I'm not familiar with the options we have to look at the logs.

Yeah, I'd definitely recommend investing some time in this, and general SQL Server techniques for analyzing/profiling slow queries/statements.

I'm going to go ahead and close this issue for now since right now there's nothing actionable on the EF side, but definitely feel free to keep posting back here once you find more (a closed issue doesn't mean we can't continue the conversation). And if we find something that needs to be improved/fixed on the EF side, I can always reopen. Good luck!

**Closed by roji** 2024-09-04 13:44 UTC
Labels: customer-reported, area-save-changes
