### ISSUE TITLE
Get a string from an array on automapper mapping fails

### ISSUE THREAD

**Issue by Tbd19** [dotnet/efcore#12471] opened 2018-06-26 11:06 UTC
I have the following configuration on the Automapper 7 and EFCore 2.0.3

```C#
CreateMap<A, B>()
.ForMember(dest => dest.Property, opt => opt.MapFrom(src => src.Array.FirstOrDefault(a => a.BooleanValue).Property))
```

I have updated to EFCore 2.1.1 and I get the error
System.InvalidOperationException: Nullable object must have a value.

I have asked the same question to AutoMapper and they said that it is a EF issue
https://github.com/AutoMapper/AutoMapper/issues/2699

```
Here is the StackTrace
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at lambda_method(Closure , TransparentIdentifier`2 )
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.AsyncEnumerable.AsyncEnumerableAdapter`1.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
```

**Comment by ajcvickers** [comment] 2018-06-26 16:33
@Tbd19 I have not been able to reproduce this. Can you please post a complete project/solution or code listing that demonstrates the behavior you are seeing?

**Comment by ajcvickers** [comment] 2018-07-05 18:45
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by maganuk** [comment] 2018-07-19 08:52
@ajcvickers I'm having a similar issue. Below is the code which is failing:

    class Program
    {
        static void Main(string[] args)
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<Vehicle, VehicleDTO>()
                    .ForMember(d => d.Target, opt => opt.MapFrom(c => c.CarCollections.Where(x => x.CarType == CarType.VAN).FirstOrDefault()));
                cfg.CreateMap<CarCollection, CarCollectionDTO>();
                cfg.CreateMap<Car, CarDTO>();
                cfg.CreateMissingTypeMaps = false;
            });
            Mapper.AssertConfigurationIsValid();
            Mapper.Configuration.CompileMappings();
            var optionsBuilder = new DbContextOptionsBuilder<TestContext>();
            optionsBuilder.UseSqlServer("Server=(LocalDb)\\MSSQLLocalDB;Database=TestingCore;Trusted_Connection=true;MultipleActiveResultSets=true");
            var dbContext = new TestContext(optionsBuilder.Options);
            dbContext.Database.EnsureDeleted();
            dbContext.Database.EnsureCreated();
            dbContext.Vehicles.Add(new Vehicle { CarCollections = new List<CarCollection> { new CarCollection { Car= new Car() { Title = "test" }, CarType = CarType.VAN } } });
            dbContext.SaveChanges();
            var result = dbContext.Vehicles.Where(x => x.ID == 1).ProjectTo<VehicleDTO>().ToList();
        }
    }

    public class TestContext : DbContext
    {
        public TestContext(DbContextOptions<TestContext> options) : base(options)
        {
        }

        public DbSet<Vehicle> Vehicles { get; set; }
    }

    public enum CarType
    {
        VAN
    }

    public class Car
    {
        public int ID { get; set; }
        public string Title { get; set; }
    }

    public class CarCollection
    {
        public int ID { get; set; }
        public Car Car { get; set; }
        public CarType CarType { get; set; }
    }

    public class Vehicle
    {
        public int ID { get; set; }
        public virtual ICollection<CarCollection> CarCollections { get; set; }
    }

    public class VehicleDTO
    {
        public int ID { get; set; }
        public CarCollectionDTO Target { get; set; }
    }

    public class CarDTO
    {
        public string Title { get; set; }
    }

    public class CarCollectionDTO
    {
        public CarDTO Car { get; set; }
    }

**Closed** 2022-10-16 13:15 UTC
Labels: closed-could-not-reproduce, customer-reported
