### ISSUE TITLE
Entity mapping from mutilple query

### ISSUE THREAD

**Issue by jasonliaocn** [dotnet/efcore#20701] opened 2020-04-21 03:12 UTC
in my project I have one entity mapping to mutilple query from sql like:

`public DBSet<Report1> Report1{ get; set; }`
`public DBSet<Report2> Report2{ get; set; }`
`public DBSet<Report3> Report3{ get; set; }`
`public DBSet<Table1> Table1{ get; set; }`
`public DBQuery<MyReport> MyReport{ get; set; }`

`public async Task<MyReport> GetMyReport1(){`
     `string mysql = "select R1 as A, R2 as B, R3 as C from table Report1 join Table1";`
     `return await Context.MyReport.FromSqlRaw(mysql).FirstOrDefaultAsync();`
}

`public async Task<MyReport> GetMyReport2(){`
    `string mysql = "select  R4 as A, R5 as B,R6 as C from table Report2 join Table1";`
    `return await Context.MyReport.FromSqlRaw(mysql).FirstOrDefaultAsync();`
}

`public async Task<MyReport> GetMyReport3(){`
    `string mysql = "select R7 as A, R8 as B, R9 as C from table Report3 join Table1";`
    `return await Context.MyReport.FromSqlRaw(mysql).FirstOrDefaultAsync();`
`}`

above three Report tables have different column names and struct

Currently I use the solution from [EF Core 3 DbQuery equivalent functionality](https://stackoverflow.com/questions/59427708/ef-core-3-dbquery-equivalent-functionality/59428468#59428468)

Expect to keep the object like DBQuery or some replacement in EFCore 3.1 or higher versions

**Comment by ajcvickers** [comment] 2020-04-21 14:18
Duplicate of #18719

**Closed** 2022-10-16 18:21 UTC
Labels: customer-reported
