### ISSUE TITLE
Option to avoid attempting to insert duplicate rows

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#14464] opened 2019-01-19 01:21 UTC
We talked recently about having an alternative to detect when an insert operation would insert duplicate data (e.g. violate a unique constrain) without relying on an exception. 

I ran today into this pattern that works with SQL Server, and seems relatively clean:

``` SQL
INSERT INTO Users (UserName, Email)
SELECT @UserName, @Email
EXCEPT 
SELECT UserName, Email
FROM Users
WHERE Email = @Email
```
This will insert 0 rows if there is a conflict in the @Email (that is supposed to be Unique). The idea is to check for rows affected to detect that the INSERT didn't happen, at which point EF Core can handle the case as appropriate (e.g. throw a provider-agnostic exception). 

Not sure how this performs or how provider agnostic it can be. This is obviously for a single INSERT, but perhaps there is a similar pattern that would work with batching.

**Comment by HailOdin** [comment] 2019-02-23 17:08
there's also something like UPSERT https://github.com/artiomchi/FlexLabs.Upsert

**Comment by roji** [comment] 2022-10-19 07:02
The precise issue covering this is "add or ignore" (#16949), which is indeed closely related to upsert. Am closing this issue as a duplicate of that and will add the above notes there.

**Comment by roji** [comment] 2022-10-19 07:02
Duplicate of #16949

**Closed by roji** 2022-10-19 07:02 UTC
Labels: type-enhancement, area-save-changes
