### ISSUE TITLE
ExecuteInsert (bulk insert)

### ISSUE THREAD

**Issue by IndigoHealth** [dotnet/efcore#29994] opened 2023-01-06 00:34 UTC
EF 7 gave us [`ExecuteUpdate` and `ExecuteDelete` (Bulk updates)](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#executeupdate-and-executedelete-bulk-updates). Is there a way to leverage any of this to do a bulk insert? Are there plans for an `ExecuteInsert` method?

**Comment by roji** [comment] 2023-01-06 01:06
Duplicate of #27333

**Comment by roji** [comment] 2023-01-06 01:07
See also #29897

**Closed** 2023-01-06 10:51 UTC
Labels: customer-reported
