### ISSUE TITLE
Cosmos.Sql -- Logging category name Microsoft.EntityFrameworkCore.Database.Command

### ISSUE THREAD

**Issue by espray** [dotnet/efcore#13471] opened 2018-10-02 19:47 UTC
`Version="2.2.0-preview3-35373"` logging category `Microsoft.EntityFrameworkCore.Database.Command` with `LogLevel.Information` is not outputting any information. As a comparison `Microsoft.EntityFrameworkCore.SqlServer` with the same category/loglevel will output the sql statements.

**Comment by ajcvickers** [comment] 2018-10-03 23:40
@espray The Cosmos provider should be logging queries to that category, but it's possible that there is a bug. Can you post a runnable project/solution or complete code listing that demonstrates what you are seeing?

**Comment by ajcvickers** [comment] 2018-10-10 17:58
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by julielerman** [comment] 2019-01-23 19:12
I'm having the same problem. I can get changetracker and other logs but not SQL. I starting with v2.2.1 but am now using latest (3.0.0-preview.18572.1).
In VS Code on MacOs.

Queries and SaveChanges are not returning any SQL. 

Here's my default logger:

```
private ILoggerFactory GetLoggerFactory()
{
  IServiceCollection serviceCollection = new ServiceCollection();
  serviceCollection.AddLogging(builder =>
         builder.AddConsole()
                .AddFilter("DbLoggerCategory.Database.Command.Name", 
                           LogLevel.Information)); 
  return serviceCollection.BuildServiceProvider()
          .GetService<ILoggerFactory>();
}
```

I've tried Debug and Trace. I've changed filter to "". There I can see loads of change tracker logs including starting save changes and when the change tracker sets just inserted data state to Unchanged.

Here for example is the output with filter="" and Level = Debug.  I've called EnsureCreated, inserted data and done a query. That last "2" in my log is a console.writeline to show the number of results from a query.

```
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.0.0-preview.18572.1 initialized 'ExpanseContext' using provider 'Microsoft.EntityFrameworkCore.Cosmos' with options: ServiceEndPoint=https://lermandatapoints.documents.azure.com/ Database=ExpanseCosmosDemo SensitiveDataLoggingEnabled
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.0.0-preview.18572.1 initialized 'ExpanseContext' using provider 'Microsoft.EntityFrameworkCore.Cosmos' with options: ServiceEndPoint=https://lermandatapoints.documents.azure.com/ Database=ExpanseCosmosDemo SensitiveDataLoggingEnabled
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.0.0-preview.18572.1 initialized 'ExpanseContext' using provider 'Microsoft.EntityFrameworkCore.Cosmos' with options: ServiceEndPoint=https://lermandatapoints.documents.azure.com/ Database=ExpanseCosmosDemo SensitiveDataLoggingEnabled
2
```

As you may guess by now, I've been trying everything I could think of before raising this.

**Comment by espray** [comment] 2019-01-23 20:14
@julielerman I dont remember getting the SQL statement to output either.
`Microsoft.EntityFrameworkCore.SqlServer` and `Cosmos.Sql` the log output is inconsistent, category and level, between the drivers. Frustrating.

To be honest I am not sure I would recommend using the EFCore Cosmos driver. EF is relational data opinionated, and that can cause problems in a NoSql db.

**Comment by julielerman** [comment] 2019-01-23 20:18
Remember that the driver is a preview . Also I just discovered that unfiltered Debug logs is outputting SQL. So it's there and even tagged with the database.command category. 

```
dbug: Microsoft.EntityFrameworkCore.Database.Command[30000]
      Executing Sql Query [Parameters=[]]
      SELECT c
      FROM root c
      WHERE (c["Discriminator"] = "Consortium")
```
So there's just some tweaking to do. The driver is really just inserting and reading data. And doing things like adding discriminators etc. t's still up to you (user) to determine the model, how to spread across containers, etc etc. EF Core will just use some simple defaults.

**Comment by julielerman** [comment] 2019-01-25 19:40
Dear provider, it's not you it''s me... again. I can't believe I didn't notice that I was passing the DbLogger category in as a string and not just using it to return the name of the event class:
.AddFilter("DbLoggerCategory.Database.Command.Name", 
                           LogLevel.Information)); 

should have been

.AddFilter(DbLoggerCategory.Database.Command.Name, 
                           LogLevel.Information)); 

All working now.

**Closed** 2022-10-16 13:33 UTC
Labels: closed-could-not-reproduce, customer-reported
