### ISSUE TITLE
Error when running dotnet ef migrations add

### ISSUE THREAD

**Issue by phenning** [dotnet/efcore#4871] opened 2016-03-21 18:13 UTC
Assembly Load failure when running ef migrations add:

C:\dd\samples\mynewindauth\src\mynewindauth>dotnet ef migrations add 00000000000000_CreateIdentitySchema -c ApplicationDbContext
System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located 
C:\dd\samples\mynewindauth\src\mynewindauth>dotnet ef migrations add 00000000000000_CreateIdentitySchema -c ApplicationDbContext
System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Add(IConfigurationProvider provider)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder configurationBuilder, String path, Boolean optional)
   at mynewindauth.Startup..ctor(IHostingEnvironment env, IApplicationEnvironment appEnv) in C:\dd\samples\mynewindauth\src\mynewindauth\Startup.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.StartupInvoker.Invoke(Type type, String[] methodNames, IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.StartupInvoker.ConfigureServices()
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations..ctor(ILoggerProvider loggerProvider, Assembly assembly, Assembly startupAssembly, String environment, String startupProjectDir)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations..ctor(AssemblyLoader assemblyLoader, ILoggerProvider loggerProvider, Assembly assembly, Assembly startupAssembly, String environment, String projectDir, String startupProjectDir, String rootNamespace)
   at Microsoft.EntityFrameworkCore.Commands.OperationExecutor.<>c__DisplayClass3_0.<.ctor>b__4()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Commands.OperationExecutor.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Commands.MigrationsAddCommand.Execute(String name, String outputDir, String context, String startupProject, String environment, Action`1 reporter)
   at Microsoft.EntityFrameworkCore.Commands.MigrationsAddCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Commands.Program.Main(String[] args)
Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Add(IConfigurationProvider provider)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder configurationBuilder, String path, Boolean optional)
   at mynewindauth.Startup..ctor(IHostingEnvironment env, IApplicationEnvironment appEnv) in C:\dd\samples\mynewindauth\src\mynewindauth\Startup.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.StartupInvoker.Invoke(Type type, String[] methodNames, IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.StartupInvoker.ConfigureServices()
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations..ctor(ILoggerProvider loggerProvider, Assembly assembly, Assembly startupAssembly, String environment, String startupProjectDir)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations..ctor(AssemblyLoader assemblyLoader, ILoggerProvider loggerProvider, Assembly assembly, Assembly startupAssembly, String environment, String projectDir, String startupProjectDir, String rootNamespace)
   at Microsoft.EntityFrameworkCore.Commands.OperationExecutor.<>c__DisplayClass3_0.<.ctor>b__4()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Commands.OperationExecutor.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Commands.MigrationsAddCommand.Execute(String name, String outputDir, String context, String startupProject, String environment, Action`1 reporter)
   at Microsoft.EntityFrameworkCore.Commands.MigrationsAddCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Commands.Program.Main(String[] args)
Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I noticed that when dot net restore is performed on the project that the ef tool installs 7.0.1 of newtonsoft.json, while 8.0.3 is also restored by the project. If I manually remove the 7.0.1 package from the .nuget/packages folder, I'm able to successfully run the migration

Restoring Tool 'dotnet-ef' for 'C:\dd\samples\mynewindauth\src\mynewindauth\obj\ca70d0c2-19e3-41b5-aaf9-2de18d516d17\bin\project.json' in 'C:\dd\samples\mynewindauth\src\mynewindauth\obj\ca70d0c2-19e3-41b5-aaf9-2de18d516d17\bin'
log  : Restoring packages for C:\dd\samples\mynewindauth\src\mynewindauth\obj\ca70d0c2-19e3-41b5-aaf9-2de18d516d17\bin\project.json...
info :   GET https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.dynamic.runtime/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.runtime.loader/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.csharp/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.xml.xdocument/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.reflection.metadata/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/nuget.packaging/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json 73ms
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.extensions.filesystemglobbing/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.io.filesystem/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.linq/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.runtime/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.reflection/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/7.0.1/newtonsoft.json.7.0.1.nupkg
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.extensions.platformabstractions/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/7.0.1/newtonsoft.json.7.0.1.nupkg 306ms
log  : Installing Newtonsoft.Json 7.0.1.

**Comment by bricelam** [comment] 2016-03-22 15:58
Dupe of #4862

**Closed** 2022-10-16 09:34 UTC
