### ISSUE TITLE
Cannot create a DbSet for 'MostExpensiveProduct' because this type is not included in the model for the context.

### ISSUE THREAD

**Issue by yukozh** [dotnet/efcore#31424] opened 2023-08-08 05:31 UTC
Hi team,

I'm from Pomelo.EFCore.MySql and working on upgrade it from 7.0 to 8.0-preview.6

![image](https://github.com/dotnet/efcore/assets/2216750/085a5c2b-83cf-4c3f-8f06-0aec8cdc6d23)

I got lots of same error as below:

```
System.InvalidOperationException : Cannot create a DbSet for 'MostExpensiveProduct' because this type is not included in the model for the context.
```
Is there any breaking changes between 7.0 & 8.0? Any suggestions to fix this problem?

BR,
Yuko

**Comment by ajcvickers** [comment] 2023-09-05 15:02
@yukozh Sorry for the slow response. There is nothing obvious here. We need to be able to reproduce what you are seeing to investigate more.

/cc @lauxjpn

**Comment by ajcvickers** [comment] 2023-10-01 11:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-10-01 11:10 UTC
Labels: customer-reported

**Comment by lauxjpn** [comment] 2023-10-01 23:25
I believe this error was related to the following line missing from the fixture:

https://github.com/lauxjpn/Pomelo.EntityFrameworkCore.MySql/blob/95229150cc17cd2bad8d1854a4523be38fecabee/test/EFCore.MySql.FunctionalTests/Query/NorthwindQueryMySqlFixture.cs#L16

```csharp
namespace Pomelo.EntityFrameworkCore.MySql.FunctionalTests.Query
{
    public class NorthwindQueryMySqlFixture<TModelCustomizer> : NorthwindQueryRelationalFixture<TModelCustomizer>
        where TModelCustomizer : IModelCustomizer, new()
    {
        protected override ITestStoreFactory TestStoreFactory => MySqlNorthwindTestStoreFactory.Instance;
        protected override Type ContextType => typeof(NorthwindMySqlContext); // <--

        protected override bool ShouldLogCategory(string logCategory)
```
