### ISSUE TITLE
InMemory provider does not throw exception when trying to update or delete with an invalid primary key

### ISSUE THREAD

**Issue by hameedfs** [dotnet/efcore#4515] opened 2016-02-08 10:52 UTC
InMemory provider does not throw exception when trying to update or delete with an invalid primary key. Attached is the test code that compares the behavior of Sqlite and InMemory providers when trying to update or delete with an invalid primary key.

[InvalidIdTests.zip](https://github.com/aspnet/EntityFramework/files/121444/InvalidIdTests.zip)

**Comment by rowanmiller** [comment] 2016-02-12 18:13
Duplicate of https://github.com/aspnet/EntityFramework/issues/3953

**Closed** 2022-10-16 09:28 UTC
