### ISSUE TITLE
Behaviour of bool fields with HasDefaultValue(true) option

### ISSUE THREAD

**Issue by Linnod** [dotnet/efcore#15323] opened 2019-04-11 08:10 UTC
Hello!

I have an entity `ClassDef `with `public bool IsActive { get; set; }` property. I want this property to be true by default, so I have configuration like `builder.Property(x => x.IsActive).HasColumnName("IsActive").HasDefaultValue(true);`.

When **IsActive** equals **FALSE**, EF **does not** generate insert for this column (like in this issue - https://github.com/aspnet/EntityFrameworkCore/issues/6054). So database value is always TRUE.

Note, that this is correct only for this config `builder.Property(x => x.IsActive).HasColumnName("IsActive").HasDefaultValue(true);`. If HasDefaultValue(**false**), everything works fine.

Thank you!

**Comment by roji** [comment] 2019-04-11 12:28
The workaround mentioned in #6054 (and #7089) is still the valid way to deal with this - make your boolean property nullable. #15182 will improve this by allowing you to specify a nullable backing field instead.

Note that EF Core emits a warning for non-boolean store-generated properties which explains this (#7163). #15070 also contains some more information on alternatives recently considered by the team.

**Comment by roji** [comment] 2019-04-11 12:28
Duplicate of #7089

**Closed** 2022-10-16 14:17 UTC
Labels: customer-reported
