### ISSUE TITLE
Seeding problem, there was no value provided for the required property 

### ISSUE THREAD

**Issue by geedsen** [dotnet/efcore#12883] opened 2018-08-03 09:51 UTC
First I had this:

           modelBuilder.Entity<EFInstallPackage>().HasData(
                new EFInstallPackage()
                {
                    Guid = Guid.Parse("821f881e-56d3-4b55-afcb-26496c0768db"),
                    Type = 2,
                    Version = 0,
                    ZippedAppPackageUrl = "Scripts.zip",
                    LogOnAsEncryptedPassword = "",
                    LogOnAsUser = "",
                    LogOnAsLocalSystem = true,
                    ProgramExeName = "Some.Exe",
                    OptionsFileName = "Some.Options.json",
                    Title = "Test Some",
                    Desccription = "Winter is coming",
                    AppConfig =
                        "{ \"Header\":{ \"Guid\" :\"821f881e-56d3-4b55-afcb-26496c0768db\", \"AppVersion\": 2, \"AppTemplateVersion\": 2, \"ScanFrequencyInSeconds\":60 }, \"Blocks\":[  {\"Commands\":[  {\"PsCommand\":\"Test\", \"Code\":\"1\" } ] } ] }"
                });

'dotnet ef migrations add xxxx' results in 
**System.InvalidOperationException: The seed entity for entity type 'EFInstallPackage' cannot be added because there was no value provided for the required property 'Guid'.**

There is a value provided for 'Guid', so why?

Then I think maybe Guid is a special name, so I rename the column to 'Id' and tried this:

           modelBuilder.Entity<EFInstallPackage>().HasData(
                new EFInstallPackage()
                {
                    Id = Guid.Parse("821f881e-56d3-4b55-afcb-26496c0768db"),
                    Type = 2,
                    Version = 0,
                    ZippedAppPackageUrl = "Scripts.zip",
                    LogOnAsEncryptedPassword = "",
                    LogOnAsUser = "",
                    LogOnAsLocalSystem = true,
                    ProgramExeName = "Some.Exe",
                    OptionsFileName = "Some.Options.json",
                    Title = "Test Some",
                    Desccription = "Winter is coming",
                    AppConfig =
                        "{ \"Header\":{ \"Guid\" :\"821f881e-56d3-4b55-afcb-26496c0768db\", \"AppVersion\": 2, \"AppTemplateVersion\": 2, \"ScanFrequencyInSeconds\":60 }, \"Blocks\":[  {\"Commands\":[  {\"PsCommand\":\"Test\", \"Code\":\"1\" } ] } ] }"
                });

S**ystem.InvalidOperationException: The seed entity for entity type 'EFInstallPackage' cannot be added because there was no value provided for the required property 'LogOnAsLocalSystem; .**

Another one that is actually provided. What is going on?

Thanks

  Ben

**Comment by ajcvickers** [comment] 2018-08-06 00:49
@geedsen I have not been able to reproduce this. Can you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by geedsen** [comment] 2018-08-06 04:50
I just updated to preview 5, and THAT problem does not seem to be there any longer. But because I had the problem in the previous version, I seeded the database via some sql scripts.  But testing the problem still causes an error. this time it is telling me that it cannot seed because there would be a dunplicate record. Correct, because I already had the records inserted. But I would assume that the HasData would take of that, it would not try to insert it if the record is already there.  But I get this:

System.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_InstallPackages'. Cannot insert duplicate key in object 'dbo.InstallPackages'. The duplicate key value is (821f881e-56d3-4b55-afcb-
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:0c18d91c-5700-4056-811e-a486e6095007
Error Number:2627,State:1,Class:14
Violation of PRIMARY KEY constraint 'PK_InstallPackages'. Cannot insert duplicate key in object 'dbo.InstallPackages'. The duplicate key value is (821f881e-56d3-4b55-afcb-26496c0768db).
The statement has been terminated.
PS D:\Users\Ben\Source\Repos\Xpndr\EF>

And again this was the code:   modelBuilder.Entity<EFInstallPackage>().HasData(
            new EFInstallPackage()
            {
                Id = Guid.Parse("821f881e-56d3-4b55-afcb-26496c0768db"),
                Type = 2,
                Version = 0,
                ZippedAppPackageUrl = "Scripts.zip",
                LogOnAsEncryptedPassword = "",
                LogOnAsUser = "",
                LogOnAsLocalSystem = true,
                ProgramExeName = "Some.Exe",
                OptionsFileName = "Some.Options.json",
                Title = "Test Some",
                Desccription = "Winter is coming",
                AppConfig =
                    "{ \"Header\":{ \"Guid\" :\"821f881e-56d3-4b55-afcb-26496c0768db\", \"AppVersion\": 2, \"AppTemplateVersion\": 2, \"ScanFrequencyInSeconds\":60 }, \"Blocks\":[  {\"Commands\":[  {\"PsCommand\":\"Test\", \"Code\":\"1\" } ] } ] }"
            });

**Comment by ajcvickers** [comment] 2018-08-13 17:57
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by geedsen** [comment] 2018-08-16 15:06
I tried creating a test project, but gave up when another problem came up.  I tried to create a separate library, but the first dotnet statement gave this bogus error, telling me the framework was not found, while in the same error message it actually lists the 'missing' framework.

PS C:\Users\Ben\Documents\Visual Studio 2017\Projects\ClassLibrary3\ClassLibrary3> dotnet ef migrations add Initial
The specified framework version '2.0' could not be parsed
The specified framework 'Microsoft.NETCore.App', version '2.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      1.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.12 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.0-preview2-25407-01 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Closed** 2022-10-16 13:23 UTC
Labels: closed-could-not-reproduce, customer-reported
