### ISSUE TITLE
Unable to retrieve entities from InMemoryDatabase when entity type has a generic complex type property

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/efcore#33172] opened 2024-02-27 12:45 UTC
I have this test code:

```csharp
var options = new DbContextOptionsBuilder<EntityDbContext<DataType>>()
    .UseInMemoryDatabase(Guid.NewGuid().ToString("N"))
    //.UseSqlite($"Data Source={Guid.NewGuid().ToString("N")}.db")
    //.UseSqlServer($@"Server=(localdb)\mssqllocaldb;Database={Guid.NewGuid().ToString("N")};Trusted_Connection=True;")
    .LogTo(Console.WriteLine)
    .Options;

var factory = new PooledDbContextFactory<EntityDbContext<DataType>>(options);

await using (var context = await factory.CreateDbContextAsync())
{
    await context.Database.EnsureDeletedAsync();
    await context.Database.EnsureCreatedAsync();
}

try
{
    var expectedMessage = "Hello World!";
    int savedCount;

    await using (var context = await factory.CreateDbContextAsync())
    {

        for (var i = 1; i <= 3; i++)
        {
            var entity = new EntityType<DataType>
            {
                Data = new DataType
                {
                    Message = $"{expectedMessage} [{i}]",
                }
            };

            context.Entities.Add(entity);
        }

        savedCount = await context.SaveChangesAsync();
    }

    Console.WriteLine($"Saved Count: {savedCount}");

    await using (var context = await factory.CreateDbContextAsync())
    {
        await foreach (var entity in context.Entities)
        {
            Console.WriteLine($"""

--- Entity ---
     Id: {entity.Id}
Message: {entity.Data.Message}
--------------

""");
        }
    }
}
finally
{
    await using (var context = await factory.CreateDbContextAsync())
    {
        await context.Database.EnsureDeletedAsync();
    }
}

public class EntityDbContext<TDataType> : DbContext
{
    public EntityDbContext(DbContextOptions options) : base(options)
    {

    }

    public DbSet<EntityType<TDataType>> Entities { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<EntityType<TDataType>>().HasKey(o => o.Id);
        modelBuilder.Entity<EntityType<TDataType>>().Property(e => e.Id).ValueGeneratedOnAdd();
        modelBuilder.Entity<EntityType<TDataType>>().ComplexProperty(
            e => e.Data,
            b =>
            {
                b.IsRequired();
            });
    }
}

public class EntityType<TDataType>
{
    public int Id { get; set; }
    public TDataType Data { get; set; }
}

public class DataType
{
    public string Message { get; set; }
}
```

It works fine for Sqlite and SqlServer, but not for InMemoryDatabase.

For InMemoryDatabase, the entities are inserted and are in the database after `context.SaveChangesAsync`. But they are gone after the context is disposed.

```
dbug: 27/02/2024 12:57:29.223 CoreEventId.QueryCompilationStarting[10111] (Microsoft.EntityFrameworkCore.Query)
      Compiling query expression:
      'DbSet<EntityType<DataType>>()'
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'Property: EntityType<DataType>.Data#DataType.Message (string) Required' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitSwitchCase(SwitchCase node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitSwitch(SwitchExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.ProcessShaper(Expression shaperExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.VisitShapedQuery(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IAsyncEnumerable<TEntity>.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbSet`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Temp\Projects\EFCore\EntitiesWithGenerics\Program.cs
   at Program.<Main>$(String[] args) in C:\Temp\Projects\EFCore\EntitiesWithGenerics\Program.cs
   at Program.<Main>(String[] args)
```

What am I doing wrong?

**Comment by ajcvickers** [comment] 2024-02-27 13:24
Duplicate of #31464. The in-memory provider does not, in general, support complex types.

**Closed** 2024-02-28 13:36 UTC
Labels: closed-duplicate, customer-reported
