### ISSUE TITLE
Is there a nesting limit on IQueryable<T>.Contains

### ISSUE THREAD

**Issue by statler** [dotnet/efcore#25033] opened 2021-06-04 04:46 UTC
It is very useful for composing queries that I can create an IQueryable, and the use it in another expression with contains. One of my favourite features in fact. 

    GetRelated( IQueryable<Product> qryProduct)   
    {
        return _context.Customer.Where(x=>x.Orders.Any(o=>qryProduct.Contains(o.ProductId)));
    }

It seems though, that this cannot be nested - is this a restriction on composing queries this way? If so, is there an alternative that allows nested composition?

        System.InvalidOperationException : The LINQ expression 'DbSet<>() could not be translated. Either rewrite the query in a form that can be translated

For example, the following query works:

        int actualRecordsForProject = _context.TestRequestProperties.Where(x=> GetTestReqForUser_Expanded(_context, UserId).Contains(x.TestRequest)).Count();

        private IQueryable<TestRequest> GetTestReqForUser_Expanded(cpContext _context, int uid)
        {
            return _context.TestRequests.Where(x => x.ProjectId == ProjectId_main)
                .Where(x => x.Lot.CreatedBy == uid ||
                    x.Lot.LotUsers.Any(lu => lu.UserId == uid) ||
                    x.Lot.SubcontractorLots.Any(sl => sl.Subcontractor.SubcontractorUsers.Any(su => su.UserId == uid)));
        }

Whereas this does not:

        int actualRecordsForProject = _context.TestRequestProperties.Where(x=> GetTestReqForUser(_context, UserId).Contains(x.TestRequest)).Count();

        private IQueryable<TestRequest> GetTestReqForUser(cpContext _context, int uid)
        {            
            return _context.TestRequests.Where(x => x.ProjectId == ProjectId_main)
                .Where(x => GetSubcontractorLotQuery(_context, uid).Contains(x.Lot));
        }

        public IQueryable<Lot> GetSubcontractorLotQuery(IcpContext_base _context, int UserId)
        {
            return _context.Lots.Where(nl => nl.CreatedBy == UserId
                || nl.LotUsers.Any(lu => lu.UserId == UserId)
                || nl.SubcontractorLots.Any(sl => sl.Subcontractor.SubcontractorUsers.Any(su => su.UserId == UserId)));
        }

**Comment by AndriySvyryd** [comment] 2021-06-04 18:32
@statler Could you provide a small project that shows the issue?

**Comment by AndriySvyryd** [comment] 2021-06-12 00:52
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:36 UTC
Labels: closed-could-not-reproduce, customer-reported
