### ISSUE TITLE
Casting IQueryable to a IQueryable<InterfaceBase> causes client eval

### ISSUE THREAD

**Issue by inforithmics** [dotnet/efcore#14118] opened 2018-12-07 17:02 UTC
When a Type has an interface Implemented. I can cast the IQueryable to a IQueryable that has only this interface. On Sql Server - Entity Framework Core doesn't find the item. (on Sqlite it works).

 asking the entity Framework on this type works.
  ```IQueryable<Benutzer> content```
on this type it doesn't work.
  ```IQueryable<IBenutzer> contentInterface = content;```    

### Steps to reproduce

Sample Code: the second Assert is false Entity Framework doesn't find the Element.
```C#
  IQueryable<Benutzer> content = context.Clients.Select(f =>
                    new Benutzer
                    {
                        Id = f.client1.ToString()
                    });


 var firstId = content.First().Id;
 var itemFirst = content.FirstOrDefault(f => f.Id == firstId);
 Debug.Assert(itemFirst !=null,"Should find item");

 IQueryable<IBenutzer> contentInterface = content;                    
 var itemFirstInterface = contentInterface.FirstOrDefault(f => f.Id == firstId);
 Debug.Assert(itemFirstInterface != null, "Should find item");
```
Attached TestProject (With Database Creation)
[ConsoleApp3.zip](https://github.com/aspnet/EntityFrameworkCore/files/2658131/ConsoleApp3.zip)

### Further technical details
EF Core version: 2.2
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Windows 1809
IDE: (e.g. Visual Studio 2017 15.9)

### Complete Test Code:
```C#
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.SqlClient;
using System.Diagnostics;
using System.IO;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp3
{
    public partial class Benutzer : IBenutzer
    {
        public string Id { get; set; }
    }

    // mc_user
    [Table("client", Schema = "dbo")]
    public class client
    {
        [Column(@"client", Order = 1, TypeName = "uniqueidentifier")]
        [Required]
        [Key]
        public System.Guid client1 { get; set; }
    }

    public interface IBenutzer
    {
        string Id { get; set; } // benutzer (Primary key) (length: 50)      
    }

    public class TestContext : DbContext
    {
        public DbSet<client> Clients { get; set; }

        public string DatabasePath => Path.Combine(Environment.CurrentDirectory, "test.mdf");

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer($"Server = (localdb)\\MSSQLLocalDB;AttachDbFileName={DatabasePath};Integrated Security = True;");
            base.OnConfiguring(optionsBuilder);
        }        
    }

    class Program
    {
        static void Main(string[] args)
        {
            var context = new TestContext();
            try
            {
                if (!File.Exists(context.DatabasePath))
                {
                    var createDatabase =
                        $"CREATE DATABASE [{context.DatabasePath}] ON (NAME = Sales_dat,FILENAME = '{context.DatabasePath}')";
                    var createTable =
                        $"CREATE TABLE [{context.DatabasePath}].dbo.client(client uniqueidentifier NOT NULL, CONSTRAINT pk_client PRIMARY KEY(client ASC))";
                    using (var connection =
                        new SqlConnection(
                            "Server = (localdb)\\MSSQLLocalDB;Initial Catalog=master;Integrated Security = True;"))
                    {
                        connection.Open();
                        using (var command = connection.CreateCommand())
                        {
                            command.CommandText = createDatabase;
                            command.ExecuteNonQuery();
                            command.CommandText = createTable;
                            command.ExecuteNonQuery();
                        }
                    }
                }

                context.Clients.Add(new client() {client1 = Guid.NewGuid(),});
                context.SaveChanges();

                IQueryable<Benutzer> content = context.Clients.Select(f =>
                    new Benutzer
                    {
                        Id = f.client1.ToString()
                    });
                IQueryable<IBenutzer> contentInterface = content;                    

                var firstId = content.First().Id;
                var itemFirst = content.FirstOrDefault(f => f.Id == firstId);
                var itemFirstInterface = contentInterface.FirstOrDefault(f => f.Id == firstId);
                Debug.Assert(itemFirst !=null,"Should find item");
                Debug.Assert(itemFirstInterface != null, "Should find item");
            }
            finally
            {                
                if (File.Exists(context.DatabasePath))
                {
                    var setDBOffline = $"ALTER DATABASE[{context.DatabasePath}] SET OFFLINE WITH ROLLBACK IMMEDIATE";
                    var createDatabase =
                        $"DROP DATABASE [{context.DatabasePath}]";
                    using (var connection =
                        new SqlConnection(
                            "Server = (localdb)\\MSSQLLocalDB;Initial Catalog=master;Integrated Security = True;"))
                    {
                        connection.Open();
                        using (var command = connection.CreateCommand())
                        {
                            command.CommandText = setDBOffline;
                            command.ExecuteNonQuery();
                            command.CommandText = createDatabase;
                            command.ExecuteNonQuery();
                        }
                    }
                }
            }                                  
        }                  
    }

    
}
```
### Workaround:

Don't Cast To ```IQueryable<Interface>```
Use Like ```contentInterface.FirstOrDefault(f => EF.Functions.Like( f.Id ,firstId));```

**Comment by inforithmics** [comment] 2018-12-11 13:31
I looked at the logs of Entity Framework and I have following Log Outputs.

1. Working.Log (Log where it works)
2. NonWorking.Log (Log where it doesn't work)

In the non working Log I see following Line.

The LINQ expression 'where (new Benutzer() {Id = [f].client1.ToString()}.Id == __firstId_0)' could not be translated and will be evaluated locally.
The LINQ expression 'FirstOrDefault()' could not be translated and will be evaluated locally.

It evaluets some expression locally. client1.ToString() in C# gives lower case strings and client1.ToString() on database it gives upper case string so I think this is the reason why it doesn work.

[NonWorking.Log](https://github.com/aspnet/EntityFrameworkCore/files/2667739/NonWorking.Log)
[Working.Log](https://github.com/aspnet/EntityFrameworkCore/files/2667740/Working.Log)

**Comment by inforithmics** [comment] 2018-12-11 13:38
When I make use a ToUpperInvariant the code works.

```
IQueryable<Benutzer> content = context.Clients.Select(f =>
                    new Benutzer
                    {
                        Id = f.client1.ToString()
                    });
```

to

```
 IQueryable<Benutzer> content = context.Clients.Select(f =>
                    new Benutzer
                    {
                        Id = f.client1.ToString().ToUpperInvariant()
                    });
```
No the item is found when casting it to the interface. But it although evaluets it in both cases local. (Not using the Database).

What I find intresting is that casting the query to a different Base Type changes the Execution of the Query. (This worked in Entity Framework 6.2)

**Comment by ajcvickers** [comment] 2018-12-17 21:00
Moving this to the backlog.

@divega @smitpatel I am still not able to write clean code for the workaround suggested in triage. I think I must be missing something. Can one of you write the code?

**Comment by smitpatel** [comment] 2018-12-17 22:44
Duplicate of #12230
Once you do casting, Relinq fails to optimize the member access in FirstOrDefault which throws off translation pipeline.

**Comment by smitpatel** [comment] 2018-12-17 22:46
Work-around, apply operations which does member access on anonymous types before casting Queryable to different type. Like this
```C#
                IQueryable<Benutzer> content = db.Clients.Select(f =>
                   new Benutzer
                   {
                       Id = f.Client1.ToString()
                   });
                var firstId = content.First().Id;
                IQueryable<IBenutzer> contentInterface = content.Where(f => f.Id == firstId);

                var itemFirst = content.FirstOrDefault();
                var itemFirstInterface = contentInterface.FirstOrDefault();
                Debug.Assert(itemFirst != null, "Should find item");
                Debug.Assert(itemFirstInterface != null, "Should find item");

**Comment by PawelGerr** [comment] 2019-05-04 14:14
Similar issue as in #12230 

When projecting to a super type and afterwads using a property of its base type (base class or interface) the query is executed locally.

The reason I do this is to encapsulate some logic.

The demo incl. my experiments with expression visitors you can find on github: [BaseTypeMemberAccess_Limitation_Demos.cs](https://github.com/PawelGerr/Presentation-EntityFrameworkCore/blob/master/src/EntityFramework.Demo/Demos/BaseTypeMemberAccess_Limitation_Demos.cs)

```
public class DemoDbContext : DbContext
{
   public DbSet<Product> Products { get; set; }
}

public class ProductWrapper : IProductWrapper
{
   public Product Product { get; set; }
}

public interface IProductWrapper
{
   Product Product { get; set; }
}

private static Expression<Func<T, bool>> GetPredicate<T>()
   where T : IProductWrapper
{
   return wrapper => wrapper.Product.Name != null;
}
```

Usage:
```
Expression<Func<ProductWrapper, bool>> predicate = GetPredicate<ProductWrapper>();

// Generates statement:
//    SELECT
//       [p].[Id], [p].[GroupId], [p].[Name], [p].[RowVersion]
//    FROM
//       [Products] AS [p]
//
// Generates warning:
//    The LINQ expression 'where (Convert(new ProductWrapper() {Product = [p]}, IProductWrapper).Product.Name != null)' could not be translated and will be evaluated locally.
//
// the filtering happens in .NET instead of in database

var products = Context.Products
                      .Select(p => new ProductWrapper { Product = p })
                      .Where(predicate)
                      .ToList();
```

At first I thougt the `Convert-Expression` is the culprit but no, it isn't.
The predicate is not being translated because the property `Product` in `Select()` belongs to type `ProductWrapper` and the property `Product` in `GetPredicate()` belongs to `IProductWrapper`.

I made an experiment by rebinding the member access from `IProductWrapper.Product` to `ProductWrapper.Product` to verify the theory.

```
private class MemberExpressionRelinqVisitor : ExpressionVisitor
{
   protected override Expression VisitMember(MemberExpression node)
   {
      if (node.Expression.NodeType == ExpressionType.Convert)
      {
         var conversion = (UnaryExpression)node.Expression;

         if (conversion.Type.IsAssignableFrom(conversion.Operand.Type))
         {
            var memberType = GetMemberReturnType(node.Member);
            var member = (MemberInfo)conversion.Operand.Type.FindProperty(node.Member.Name, memberType)
                         ?? conversion.Operand.Type.FindField(node.Member.Name, memberType)
                         ?? throw new Exception("Member not found.");

            return Expression.MakeMemberAccess(conversion.Operand, member);
         }
      }

      return base.VisitMember(node);
   }

   [NotNull]
   private static Type GetMemberReturnType([NotNull] MemberInfo member)
   {
      if (member == null)
         throw new ArgumentNullException(nameof(member));

      if (member is PropertyInfo propInfo)
         return propInfo.PropertyType;

      if (member is FieldInfo fieldInfo)
         return fieldInfo.FieldType;

      if (member is MethodInfo methodInfo)
         return methodInfo.ReturnType;

      throw new ArgumentException($"Argument must be {nameof(FieldInfo)}, {nameof(PropertyInfo)} or {nameof(MethodInfo)}.", nameof(member));
   }
}
```
The experiment succeeded. The predicate is translated now.

```
// "predicate" is the one from above
var visitor = new MemberExpressionRelinqVisitor();
var newPredicate = (Expression<Func<ProductWrapper, bool>>)visitor.Visit(predicate);

var products = Context.Products
                      .Select(p => new ProductWrapper { Product = p })
                      .Where(newPredicate)
                      .ToList();
```

If you have a recommendation how to work around the limitation I'm trying to solve with the method `GetPredicate` without rewriting expressions then I would be thankful to hear it.

**Comment by progmars** [comment] 2019-08-07 11:31
@PawelGerr 

Thank you, you saved my life :) 

I had a similar issue, but in my case there was even no Convert happening. Following your example, I investigated my expressions through `VisitMember` and discovered that it has MemberExpression with the base (or interface) declaring type and not my generic type.

So, I created the following solution.

This is my generic predicate builder that caused local evaluation if used without `MemberExpressionTypeMapper` on IQueryable after Select() projection:

```
        public Expression<Func<T, bool>> GetCriteria<T>() where T : class, ISomeable
        {
            Expression<Func<T, bool>> expr = e => (e.Some == "Hello");
            // the member access of this expr will be of ISomeable and not T
            // so we attempt to remap it
            return MemberExpressionTypeMapper.RemapFrom<T>(expr, typeof(ISomeable));
        }
```

And this is MemberExpressionTypeMapper helper method, based on your examples:

  public class MemberExpressionTypeMapper : ExpressionVisitor
    {
        Type _sourceDeclaringType;
        Type _targetDeclaringType;

        public static Expression<Func<T, bool>> RemapFrom<T>(Expression<Func<T, bool>> expr, Type sourceDeclaringType)
        {
            var v = new MemberExpressionTypeMapper(sourceDeclaringType, typeof(T));
            return (Expression<Func<T, bool>>)v.Visit(expr);
        }

        public MemberExpressionTypeMapper(Type sourceDeclaringType, Type targetDeclaringType)
        {
            _sourceDeclaringType = sourceDeclaringType;
            _targetDeclaringType = targetDeclaringType;
        }

        protected override Expression VisitMember(MemberExpression node)
        {
            if (node.Member.DeclaringType == _sourceDeclaringType)
            {
                var memberType = GetMemberReturnType(node.Member);
                var member = FindProperty(_targetDeclaringType, node.Member.Name, memberType)
                             ?? FindField(_targetDeclaringType, node.Member.Name, memberType)
                             ?? throw new Exception($"Member with name '{node.Member.Name}' and member type '{memberType.DisplayName()}' " +
                             $"not found in {_targetDeclaringType.DisplayName()}.");

                return Expression.MakeMemberAccess(node.Expression, member);
            }
            
            return base.VisitMember(node);
        }
```

I'm not yet 100% sure if this is a reliable solution, will have to test it in my final system.

Here's a Gist of my initial problem:

https://gist.github.com/progmars/eeec32a533dbd2e1f85e551db1bc53f8

**Comment by inforithmics** [comment] 2020-01-11 22:18
This checkin fixed the issue https://github.com/dotnet/efcore/commit/4b42c7aee3eb90ec929acf72af94f358bfb065dd

It works now in the Master Branch

**Closed** 2020-01-13 17:29 UTC
Labels: area-query, customer-reported, type-enhancement
