### ISSUE TITLE
SQLite provider doesn't create indexes on foreign key columns

### ISSUE THREAD

**Issue by bojanrajkovic** [dotnet/efcore#3914] opened 2015-11-28 02:04 UTC
The SQLite provider claims it creates indexes on foreign key columns (http://ef.readthedocs.org/en/latest/modeling/indexes.html#conventions), but it actually doesn't in practice.

**Comment by bricelam** [comment] 2015-11-30 18:05
Dupe of #700?

**Comment by bojanrajkovic** [comment] 2015-11-30 18:07
Seems like it, though this is specific to the SQLite provider. Not sure if the other providers do this correctly.

**Closed** 2022-10-16 09:18 UTC
