### ISSUE TITLE
Scaffold-DbContext  SqlServer decimal

### ISSUE THREAD

**Issue by quan01994** [dotnet/efcore#13229] opened 2018-09-06 09:12 UTC
````cs
Microsoft.EntityFrameworkCore.Model.Validation|WARN|
No type was specified for the decimal column 'BtlastYearCompleteValue' on entity type 'BranchTarget'. 
This will cause values to be silently truncated if they do not fit in the default precision and scale. 
Explicitly specify the SQL server column type that can accommodate all the values using 'ForHasColumnType()'. 
````

in sql server 
this column type is decimal(18,2) not null

Scaffold-DbContext generate this Code
````cs
//in model
public decimal BtlastYearCompleteValue { get; set; }
//in dbcontext
entity.Property(e => e.BtlastYearCompleteValue).HasColumnName("BTLastYearCompleteValue");
````
Why report this warning?

**Comment by ajcvickers** [comment] 2018-09-06 16:07
Duplicate of #12241

**Comment by bigswede74** [comment] 2019-05-10 18:47
If I do not fix these warnings what is the truncated behavior? Does it do any rounding or just truncates to the proper decimal point precision?

No type was specified for the decimal column. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values using 'ForHasColumnType()'

**Comment by ajcvickers** [comment] 2019-05-10 18:53
@bigswede74 Is there a reason to not fix the warnings?

**Comment by bigswede74** [comment] 2019-05-10 19:01
@ajcvickers We are currently evaluating if we absolutely need to fix the warnings as the release is going out the door in a few weeks. If it does not do any rounding we will most likely deffer the issue until our next release.

**Comment by ajcvickers** [comment] 2019-05-10 19:43
@bigswede74 I believe in some cases you may seen truncation to the default, which is `decimal(18, 2)`. However, this won't always happen, and I'm not 100% you will see truncation, not rounding. @AndriySvyryd  may remember more.

**Comment by AndriySvyryd** [comment] 2019-05-10 22:49
AFAIK the values will be truncated on insertion, but in queries where they need to be converted to a value with lower precision for some operation they would be rounded.

**Closed** 2022-10-16 13:29 UTC
Labels: customer-reported
