### ISSUE TITLE
Design: 1.1.0-preview4-final tooling: appsettings.json not loading when using dotnet ef migrations command

### ISSUE THREAD

**Issue by InariTheFox** [dotnet/efcore#7423] opened 2017-01-16 15:35 UTC
After upgrading to .NET Core 1.1.0 and EF Core 1.1.0 and the associated tooling to 1.1.0-preview4-final, the dotnet cli migrations functionality fails, preventing from adding new migrations or listing existing ones.

My hypothesis is that the tooling does not respect the Startup.cs file and any configuration which exists in code except below.

When running the application (VS/IIS/donet run) the Startup.cs file is respected.

```
Exception message:
System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Repos\xxx\src\xxx\bin\Debug\netcoreapp1.0\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at xxx.Contexts.CoreDbContextFactory.Create(DbContextFactoryOptions options) in C:\Repos\xxx\src\xxx\Contexts\CoreDbContext.cs:line 249
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.GetMigrations(String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.GetMigrationsImpl(String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Repos\xxx\src\xxx\bin\Debug\netcoreapp1.0\appsettings.json'.
```

### Steps to reproduce
Using an exiting dotnet core Web API project, update the packages to support version 1.1.0.

Attempt to add a new migration using dotnet ef migrations add --context <ContextName>

#### Startup.cs
```c#
    public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);

            if (env.IsDevelopment())
            {
                // For more details on using the user secret store see http://go.microsoft.com/fwlink/?LinkID=532709
                builder.AddUserSecrets();
            }

            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit http://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo(Configuration.GetValue<string>("SecretsDirectory")))
                .SetDefaultKeyLifetime(TimeSpan.FromDays(14))
                .SetApplicationName("xxx");

            services.AddCors(options =>
            {
                options.AddPolicy("AnyOrigin", policyBuilder =>
                {
                    policyBuilder
                        .AllowAnyOrigin()
                        .AllowAnyMethod();
                });
            });

            services.Configure<MvcOptions>(options =>
            {
                options.Filters.Add(new CorsAuthorizationFilterFactory("AnyOrigin"));
            });

            services.AddMvc(options =>
            {
                options.OutputFormatters.Clear();
                options.OutputFormatters.Add(new JsonOutputFormatter(new JsonSerializerSettings()
                {
                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                }, ArrayPool<char>.Shared));
            });

            services.AddSwaggerGen(c =>
            {
                c.SingleApiVersion(
                    new Info()
                    {
                        ...
                    });
            });

            services.AddOptions();

            services.AddDbContext<ConfigurationContext>(
                options =>
                {
                    options.UseSqlServer(Configuration.GetConnectionString("ConfigurationConnection"));
                });

            services.AddDbContext<CoreDbContext>(
                options =>
                {
                    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
                });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseCors("AnyOrigin");

            app.UseSwagger();

            app.UseSwaggerUi();

            app.UseMvc();
        }
    }
```

#### Snippet of project.json
```
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Swashbuckle": "6.0.0-beta902",
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.Abstractions": "1.1.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Configuration.Binder": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },
```
### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 LTSB
IDE: Visual Studio 2015 Update 3

Somewhat similar to issue #7237

**Comment by bricelam** [comment] 2017-01-20 18:49
@InariTheFox does adding `--verbose` give any additional information?

**Comment by bricelam** [comment] 2017-01-23 23:01
Closing as a dupe of #7356

**Closed** 2022-10-16 10:50 UTC
