### ISSUE TITLE
When object repeats itself in lazy loading it is coming null

### ISSUE THREAD

**Issue by ricardorcribeiro** [dotnet/efcore#30960] opened 2023-05-23 16:45 UTC
I have an application in .Net 7 that brings me an Order with its OrderDelivery list and inside each OrderDelivery there is a Seller.

The problem I'm having is when the same Seller is repeated within another OrderDelivery, only the first one is filled in and the others are null.

![image](https://github.com/dotnet/efcore/assets/23153045/bee426b5-d670-453c-a775-bfd2d4d23763)

You can see that all the Selles are not repeated are loaded perfectly, however the ones that are repeated only the first one is loaded and the others are null.

![image](https://github.com/dotnet/efcore/assets/23153045/9c7c8cb6-7f22-4e7e-8568-48c3a26c0b4c)

![image](https://github.com/dotnet/efcore/assets/23153045/1c5f99e8-676b-4eb8-bd24-c8e42f15d818)

![image](https://github.com/dotnet/efcore/assets/23153045/1a066371-fa0a-4d4e-a768-151099114f38)
*An observation in the Seller case does not have the OrderDelivery id because the database does not have the OrderDelivery id

![image](https://github.com/dotnet/efcore/assets/23153045/904e5a9e-af03-41a0-9e22-ff430d773953)

![image](https://github.com/dotnet/efcore/assets/23153045/db336a4a-4927-4d6f-b3c6-07cfa71e5062)

![image](https://github.com/dotnet/efcore/assets/23153045/a5ed984e-bfd8-4ef7-9054-9ac03260d9ff)

Query made at the database
![image](https://github.com/dotnet/efcore/assets/23153045/afd91cf4-bfd6-4a0a-944b-b0c71154f0e1)

I believe it could be a mapping problem or some missing configuration but I don't know which one to define.

Thanks in advance for the help.

EF Core version:  7.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 7.0
Operating system: Windows

**Comment by ajcvickers** [comment] 2023-05-24 17:20
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-06-07 18:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-06-07 18:38 UTC
Labels: customer-reported
