### ISSUE TITLE
SaveChanges loads entity with Deleted state instead of deleting

### ISSUE THREAD

**Issue by xperiandri** [dotnet/efcore#13272] opened 2018-09-09 23:04 UTC
I want to remove an entity by creating an empty one with Id only. But:
1. Instead of deleting the entry on SaveChages EF loads its data.
2. If `Any` is used instead of `AnyAsync` then EF loads all records completely (whole table). WHY???

### Steps to reproduce
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.EntityFrameworkCore;

...
var canDelete = await context.RawBinders
                .AnyAsync(b => b.Id == request.Id, cancellationToken);
if (!canDelete) return DeleteResult.NotFound;

var binder = context.RawBinders.Local
                    .FirstOrDefault(b => b.Id == request.Id);
if (binder == null)
    // next line is equivalent to new RawBinder { Id = request.Id }
    binder = mapper.Map<RawBinder>(request);

context.Entry(binder).State = EntityState.Deleted;
var result = await context.SaveChangesAsync(cancellationToken);
if (result == 1)
    return DeleteResult.Deleted;
else
    return DeleteResult.NotFound;
```

Could you explain if I miss something or these are bugs?

I also tried `Attach`, `Remove` combination which does not work too.

### Further technical details
EF Core version: 2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro x64 1803
Visual Studio 2017 15.9 Preview 1

**Comment by ajcvickers** [comment] 2018-09-10 16:18
@xperiandri I have not been able to reproduce the behavior you are seeing--my code is below. Can you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

```C#
public class RawBinder
{
    public int Id { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    public DbSet<RawBinder> RawBinders { get; set; }
}

public class Program
{
    public static async Task Main()
    {
        var requestId = 0;

        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var binder = context.Add(new RawBinder()).Entity;
            
            context.SaveChanges();

            requestId = binder.Id;
        }

        using (var context = new BloggingContext())
        {
            var cancellationToken = new CancellationToken();

            var canDelete = await context.RawBinders
                .AnyAsync(b => b.Id == requestId, cancellationToken);

            if (!canDelete)
            {
                Console.WriteLine($"Could not delete for {requestId}.");
                return;
            }

            var binder = context.RawBinders.Local
                .FirstOrDefault(b => b.Id == requestId);

            if (binder == null)
                binder = new RawBinder {Id = requestId};

            context.Entry(binder).State = EntityState.Deleted;

            var result = await context.SaveChangesAsync(cancellationToken);
            
            if (result == 1)
                Console.WriteLine("Deleted");
            else
                Console.WriteLine("Not Found");
        }

        using (var context = new BloggingContext())
        {
            Console.WriteLine(context.RawBinders.Find(requestId)?.ToString() ?? "Deleted");
        }
   }
}
```

**Comment by ajcvickers** [comment] 2018-09-17 16:48
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by xperiandri** [comment] 2018-09-25 14:01
I tried to reproduce it with a piece of the original project and it does not.
I will try to reference sources to the original project and reproduce there.

**Comment by xperiandri** [comment] 2018-09-25 14:01
Do you have symbols published on some symbols server?

**Closed** 2022-10-16 13:30 UTC
Labels: closed-could-not-reproduce, customer-reported
