### ISSUE TITLE
Way to omit discriminant with multiple classes(with identical properties) sharing a table

### ISSUE THREAD

**Issue by Dasein732** [dotnet/efcore#28538] opened 2022-07-28 20:15 UTC
I have a situation where I'm extending a shared base context to add some extra functionality on top of it without modifying the underlying table structure(in this case adding the discriminant). For the sake of simplicity assume that my base context contains an Identity User entity and I want to attach various different relations to it in contexts that inherit from it.

In context1 I may have:

```
public class User1 : User
{
    // one to many or many to many relation defined in a separate table
    public ICollection<Foo> Foo {get;set;} = new();
}
```

and in context2 I may have:

```
public class User2 : User
{
    // one to one targeting user Id
    public Bar? Bar {get;set;}
}
```

Under no use case would I call the base type, I'm explicilty hiding the base Users DbSet in the extended contexts with their respective Users:

```
public new DbSet<User1> Users { get; set; } = default!;
```

I just need a way to let the EF ignore the discriminant and assume the type accessing the table is the sole owner of it since there's no actual difference that could brick anything(none of the extra relations are required).

I've tried adding a configuration for the extended types(each one is in separate assembly) targeting the same table as the base type, and this will add the missing foreign keys BUT will also add a discriminant. I've tried encapsulating this behaviour in a domain object containing both of the entities that I need, but this either gets super messy due to number of classes I need to touch or due to performance reasons since I'd have to load each related property for each 'User' object(again, I'm just using Users as an example, I have multiple thousand of these objects that I need to load relations for per request). I could also move the extra stuff down to the base class, but this would just create extra unused code in various contexts.

I assume this could work if I marked the base class abstract, but this would brick bunch of generic constraints on interfaces that don't care for the additional fields in inherited classes.

This is on EF 6.0.X

**Comment by ajcvickers** [comment] 2022-07-29 12:01
@Dasein732 Are other entity types like `Foo` or `Bar` referencing the base type via their navigation properties?

**Comment by ajcvickers** [comment] 2022-08-02 16:28
@Dasein732 In that case it should be possible to not map the base class, in which case it is not part of a mapped hierarchy. If you are seeing something different, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-08-15 14:52
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-08-15 14:52 UTC
Labels: customer-reported
