### ISSUE TITLE
Migrations - InsertData silently truncates long strings that contain newlines due to improper `CONCAT` usage.

### ISSUE THREAD

**Issue by ascott18** [dotnet/efcore#27271] opened 2022-01-24 22:52 UTC
Migrations that insert large strings that contain newlines are truncating the string due to improper use of `CONCAT`.

The first `CONCAT` (the most outer one), correctly casts its first argument to `nvarchar(max)`. However, the subsequent nested `CONCAT` calls do not do this, causing them to be silently truncated.

For the repro below, I'd expect the database to contain a string with length 10000 (10 chars per line, 1000 lines). Instead, the length of the string in the database is only 5296 characters. There is no error or warning.

The size of the resulting string maxes out at `lengthOfOutermostConcatChunk + 4000`.

### Include your code

```C#
migrationBuilder.CreateTable(
    name: "Things",
    columns: table => new
    {
        Id = table.Column<int>(nullable: false)
            .Annotation("SqlServer:Identity", "1, 1"),
        String = table.Column<string>(nullable: true)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Things", x => x.Id);
    });
    
migrationBuilder.InsertData("Things", "String", string.Concat(Enumerable.Repeat("123456789\n", 1000)));
```

### Include verbose output

Output of `dotnet ef migrations script --verbose  > migration.sql`

```
Using project 'C:\src\ef-repro\ef-repro.csproj'.
Using startup project 'C:\src\ef-repro\ef-repro.csproj'.
Writing 'C:\src\ef-repro\obj\ef-repro.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Andrew\AppData\Local\Temp\tmpBE61.tmp /verbosity:quiet /nologo C:\src\ef-repro\ef-repro.csproj
Writing 'C:\src\ef-repro\obj\ef-repro.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Andrew\AppData\Local\Temp\tmpBFE9.tmp /verbosity:quiet /nologo C:\src\ef-repro\ef-repro.csproj
Build started...
dotnet build C:\src\ef-repro\ef-repro.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.92
Build succeeded.
dotnet exec --depsfile C:\src\ef-repro\bin\Debug\net6.0\ef-repro.deps.json --additionalprobingpath C:\Users\Andrew\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\src\ef-repro\bin\Debug\net6.0\ef-repro.runtimeconfig.json C:\Users\Andrew\.dotnet\tools\.store\dotnet-ef\6.0.1\dotnet-ef\6.0.1\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll migrations script --assembly C:\src\ef-repro\bin\Debug\net6.0\ef-repro.dll --project C:\src\ef-repro\ef-repro.csproj --startup-assembly C:\src\ef-repro\bin\Debug\net6.0\ef-repro.dll --startup-project C:\src\ef-repro\ef-repro.csproj --project-dir C:\src\ef-repro\ --root-namespace ef-repro --language C# --framework net6.0 --working-dir C:\src\ef-repro --verbose
Using assembly 'ef-repro'.
Using startup assembly 'ef-repro'.
Using application base 'C:\src\ef-repro\bin\Debug\net6.0'.
Using working directory 'C:\src\ef-repro'.
Using root namespace 'ef-repro'.
Using project directory 'C:\src\ef-repro\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'ef-repro'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'Context'.
Using context 'Context'.
Finding design-time services referenced by assembly 'ef-repro'...
Finding design-time services referenced by assembly 'ef-repro'...
No referenced design-time services were found.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding IDesignTimeServices implementations in assembly 'ef-repro'...
No design-time services were found.
DetectChanges starting for 'Context'.
DetectChanges completed for 'Context'.
Generating up script for migration '20220124221538_Test'.
'Context' disposed.
IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

CREATE TABLE [Things] (
    [Id] int NOT NULL IDENTITY,
    [String] nvarchar(max) NULL,
    CONSTRAINT [PK_Things] PRIMARY KEY ([Id])
);
GO

IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'String') AND [object_id] = OBJECT_ID(N'[Things]'))
    SET IDENTITY_INSERT [Things] ON;
INSERT INTO [Things] ([String])
VALUES (CONCAT(CAST(N'123456789' AS nvarchar(max)), nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', CONCAT(nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), CONCAT(N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', CONCAT(nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), CONCAT(N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', CONCAT(nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), CONCAT(N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', CONCAT(nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10), N'123456789', nchar(10))))))))));
IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'String') AND [object_id] = OBJECT_ID(N'[Things]'))
    SET IDENTITY_INSERT [Things] OFF;
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20220124221538_Test', N'6.0.1');
GO

COMMIT;
GO

```

### Include provider and version information

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET 5.0) .NET 6
Operating system: Win 10
IDE: (e.g. Visual Studio 2019 16.3) VS 2022

**Comment by ajcvickers** [comment] 2022-01-24 23:16
Duplicate of #27206

**Comment by ascott18** [comment] 2022-01-24 23:18
Whoops, yep. All my search attempts included `InsertData`, so I didn't stumble across that one.

**Closed** 2022-10-16 20:23 UTC
Labels: customer-reported
