### ISSUE TITLE
Issue Specifying String Column Length

### ISSUE THREAD

**Issue by eriksendc** [dotnet/efcore#3746] opened 2015-11-13 17:28 UTC
I'm having an issue getting string columns to be created with some length shorter than nvarchar(max). I've tried both annotations and fluent api to set the length of a string column:

I've tried this in my model class:
            [MaxLength(50)]
            public string SomeStringProperty { get; set; }

and this in OnModelCreating() of my DbContext class...
            builder.Entity<SomeObject>().Property(p => p.SomeStringProperty).HasMaxLength(50);

In either case, when I run "dnx ef migrations add <migration-name>", the new migration is empty:

using System;
using System.Collections.Generic;
using Microsoft.Data.Entity.Migrations;

namespace AspNet5PreviewBeta8.Migrations
{
    public partial class SomeStringPropertyStringLength2 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
        }

```
    protected override void Down(MigrationBuilder migrationBuilder)
    {
    }
}
```

}

Note that the following _does_ work, but it's more of a 'catch all' right?

builder.Entity<SomeObject>().Property(p => p.SomeStringProperty).HasColumnType("nvarchar(50)");

I guess the declarative HasMaxLength() or [MaxLength] attribute seems better.

For reference, here's my project.json (defaults :
...
  "dependencies": {
    "EntityFramework.Commands": "7.0.0-beta8",
    "EntityFramework.SqlServer": "7.0.0-beta8",
...

**Comment by rowanmiller** [comment] 2015-11-13 17:36
Dupe of https://github.com/aspnet/EntityFramework/issues/3434 (a fix was just committed for it).

**Closed** 2022-10-16 09:16 UTC
