### ISSUE TITLE
Automatically query all data from DbSets in the order within the DbContext after calling SaveChanges

### ISSUE THREAD

**Issue by dovantoi** [dotnet/efcore#31452] opened 2023-08-12 09:27 UTC
My application is encountering an issue after saving newly added data. It results in a situation where, after the SaveChanges operation, EF Core seems to autonomously execute queries in the order of sorting the DbSet as defined in my DbContext class

### Include stack traces
Generated query execution expression: "
"'"queryContext => new SingleQueryingEnumerable(
(RelationalQueryContext)queryContext,
RelationalCommandCache.SelectExpression(
Projection Mapping:
EmptyProjectionMember -> Dictionary<IProperty, int> { [Property: DdKhongDuDieuKienXuatBen.IdKhongDuDieuKien (long) Required PK AfterSave:Throw, 0], [Property: DdKhongDuDieuKienXuatBen.IdPhanLoai (int) Required FK Index, 1], [Property: DdKhongDuDieuKienXuatBen.MaDinhDanh (string) MaxLength(255), 2], [Property: DdKhongDuDieuKienXuatBen.MoTa (string), 3], [Property: DdKhongDuDieuKienXuatBen.ThuTu (Nullable), 4], }
SELECT d.IdKhongDuDieuKien, d.IdPhanLoai, d.MaDinhDanh, d.MoTa, d.ThuTu
FROM DD_KhongDuDieuKienXuatBen AS d),
Func<QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator, DdKhongDuDieuKienXuatBen>,
DieuDo_BE.Models.Database.DieuDo.DieuDoDbContext,
False,
False
)"'
![image](https://github.com/dotnet/efcore/assets/142068463/3933bc1e-929d-493a-be3c-6726afe6d896)
![image](https://github.com/dotnet/efcore/assets/142068463/467cdb80-3f85-4714-bc3c-ec1eaa1d4662)

### Include provider and version information
---
EF Core version: 6.0.0
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL - 6.0.0
Target framework: NET 6.0
Operating system: Docker aspnet:6.0, sdk:6.0
IDE: Visual Studio 2022
---

EF Core version: 5.0.7
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL - 5.0.7
Target framework: NET 5.0
Operating system: Docker aspnet:5.0, sdk:5.0
IDE: Visual Studio 2022

**Comment by ErikEJ** [comment] 2023-08-12 09:29
Serilog?

**Comment by dovantoi** [comment] 2023-08-12 11:33
> Serilog?

Serilog: Version=2.10.0
Serilog.AspNetCore: Version=4.1.0
Serilog.Exceptions.EntityFrameworkCore: 7.1.0

**Comment by dovantoi** [comment] 2023-08-12 11:49
log file
[downloaded-logs-20230812-183925.log](https://github.com/dotnet/efcore/files/12327269/downloaded-logs-20230812-183925.log)

**Comment by ajcvickers** [comment] 2023-08-12 12:02
Duplicate of #24816

**Closed** 2023-08-14 08:12 UTC
Labels: customer-reported
