### ISSUE TITLE
Ability to specify serializer for ToJson() method 

### ISSUE THREAD

**Issue by ivanpolish5** [dotnet/efcore#29810] opened 2022-12-09 09:58 UTC
```
 builder.OwnsOne(m => m.MyProperty, ownedNavigationBuilder =>
  {
    ownedNavigationBuilder.ToJson();
  });
```

I would like to be able to specify serializer for `ToJson()` method so that I don't have to write 
`[JsonPropertyName("myInnerProperty")]` for each property inside of the class for it to follow camelCase naming convention.

**Comment by ajcvickers** [comment] 2022-12-09 10:06
Duplicate of #28043. Make sure to vote (👍) for that issue.

**Closed by ajcvickers** 2022-12-09 10:06 UTC
Labels: customer-reported
