### ISSUE TITLE
Geospatial support with Cosmos DB provider

### ISSUE THREAD

**Issue by clintsinger** [dotnet/efcore#22036] opened 2020-08-12 19:07 UTC
EntityFrameworkCore supports spatial types and queries.   Cosmos DB supports spatial types and queries.  They don't support spatial types and queries together.  

Bring full spatial support to EntityFrameworkCore when using the Cosmos DB provider.

**Comment by clintsinger** [comment] 2020-08-12 19:10
After changing some of my search parameters I came up with the following already reported issue.

https://github.com/dotnet/efcore/issues/17317

This feature request can be merged with that one and can be included for my support to get it working as a first class citizen.

**Comment by roji** [comment] 2020-08-12 19:56
Duplicate of #17317

**Closed** 2022-10-16 18:36 UTC
Labels: customer-reported
