### ISSUE TITLE
Group By in EF 2.1.1

### ISSUE THREAD

**Issue by RicardoDev1999** [dotnet/efcore#12609] opened 2018-07-09 17:02 UTC
I found a problem with Grouping an entity that has Collection Inside...
![image](https://user-images.githubusercontent.com/25202366/42464486-1a3a80ee-83a1-11e8-8dfa-3c28ada767a9.png)
This piece of code was suposed to generate something like this....
![image](https://user-images.githubusercontent.com/25202366/42464519-30ee66ac-83a1-11e8-843f-a98de0b697f9.png)
Wich it does... but takes about 10 minutes while using LINQPad 5 takes this long...
![image](https://user-images.githubusercontent.com/25202366/42464558-4e268de4-83a1-11e8-843c-e73140329825.png)
I Think the cause of this is that it is creating a lot of queries instead of just a bulk select...
![image](https://user-images.githubusercontent.com/25202366/42464584-6744937a-83a1-11e8-81ad-26534c5c13c8.png)
This query is executed for each Row in Users Table..
If someone could help me with this even if just telling me that it is a bug I would be glad... 

Cheers, Ricardo Duarte

**Comment by brolaugh** [comment] 2018-07-11 08:09
> LINQ’s GroupBy now can run on the database. I stress can because actually not all scenarios work

Source: [Stackify](https://stackify.com/new-in-net-core-2-1/#post-19576-_30qu3dcfvass)

My guess is that this is one of the scenarios when the GroupBy can't be done on the server-side.

**Comment by RicardoGithHub** [comment] 2018-07-11 09:07
Thanks @brolaugh for the answer. 
I talked to a senior and he said it was better make an sp for this case.
For the reason that it's presented in the source you referenced.

**Comment by divega** [comment] 2018-07-11 19:52
@smitpatel can you find the duplicate issue?

**Comment by smitpatel** [comment] 2018-07-11 22:54
Duplicate of #11976

**Closed** 2022-10-16 13:18 UTC
Labels: closed-duplicate, customer-reported
