### ISSUE TITLE
add-migration System.ArgumentNullException: Value cannot be null. Parameter name: key

### ISSUE THREAD

**Issue by jceddy** [dotnet/efcore#12402] opened 2018-06-18 19:37 UTC
Executing add-migration, I am getting System.ArgumentNullExceptionL Value cannot be null. Parameter name: key.

I got this after updating VS2017 and installing SDK 2.1.300.

My guess is that there is something amiss in my model somewhere, but would like verification that that would be a good guess, given this exception, or if it's likely to be something else. Also wondering if anyone has any hints of how to track down the source, since there are no line numbers in the stack trace and none of it references any of my solution's classes.

Here's the exception and stack trace:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.RelationalMetadataExtensions.Relational(IKey key)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<Add>d__35.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__34`1.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<Add>d__26.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<DiffCollection>d__50`1.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Further technical details
EF Core version: 2.0.3
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows Server 2008 R2
IDE: Visual Studio 2017 15.7.3

**Comment by ajcvickers** [comment] 2018-06-18 20:00
@jceddy What dependencies does your project have? Can you post the csproj file?

**Comment by jceddy** [comment] 2018-06-18 21:07
Here's the csproj file (doctored slightly  to remove anything proprietary):

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="Globals">
		<SccProjectName>%24/Framework/ProductName/Development/Dev_Core/CompanyName.ProductName.Core.S/src/CompanyName.ProductName.EntityFramework</SccProjectName>
		<SccProvider>{4CA58AB2-18FA-4F8D-95D4-32DDF27D184C}</SccProvider>
		<SccAuxPath>http://tfs.dev.CompanyName.local:8080/tfs/CompanyName%2520software</SccAuxPath>
		<SccLocalPath>.</SccLocalPath>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<DebugType>portable</DebugType>
		<AssemblyName>CompanyName.ProductName.EntityFramework</AssemblyName>
		<PackageId>CompanyName.ProductName.EntityFramework</PackageId>
		<AssetTargetFallback>$(AssetTargetFallback);dnxcore50</AssetTargetFallback>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<AssemblyVersion>3.0.2.0</AssemblyVersion>
		<FileVersion>3.0.2.0</FileVersion>
	</PropertyGroup>

	<Import Project="..\..\SolutionInfo.proj" />

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<NoWarn>1701;1702;1705;NU1603</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CompanyName.ProductNameServer.Interfaces\CompanyName.ProductNameServer.Interfaces.csproj" />
		<ProjectReference Include="..\CompanyName.ProductNameServer.Implementation\CompanyName.ProductNameServer.Implementation.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.3" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.0.2" />
		<PackageReference Include="System.Data.SqlClient" Version="4.4.3" />
		<PackageReference Include="System.Xml.XmlDocument" Version="4.3.0" />
	</ItemGroup>

	<Target Name="PostcompileScript" AfterTargets="Build">
		<Exec Command="dotnet pack --no-build --configuration $(Configuration)" />
	</Target>

</Project>

**Comment by jceddy** [comment] 2018-06-19 13:08
I think the issue was that we added a second parameter to BuildWebHost since the last time we added a migration, and didn't realize that EF looks for and uses that method, specifically.  
I added a version of that method with the original signature and it looks like its moving forward now.

**Comment by jceddy** [comment] 2018-06-19 22:13
So I thought it was fine because I encountered a different error and thought I was making progress, but now after making some changes, making sure I have the correct provider getting set up, etc., I'm back to the same error. Here is the verbose output when I run add-migration:

    Using project 'src\Framework\Server\CompanyName.ProductName.EntityFramework'.
    Using startup project 'src\Application\CompanyName.ProductName.Demo'.
    Build started...
    Build succeeded.
    C:\Program Files\dotnet\dotnet.exe exec --depsfile    D:\ProductNameCore\src\CompanyName.ProductName.Demo\bin\Debug\netcoreapp2.0\CompanyName.ProductName.Demo.deps.json --additionalprobingpath C:\Users\UserName\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig    D:\ProductNameCore\src\CompanyName.ProductName.Demo\bin\Debug\netcoreapp2.0\CompanyName.ProductName.Demo.runtimeconfig.json    C:\Users\UserName\.nuget\packages\microsoft.entityframeworkcore.tools\2.0.3\tools\netcoreapp2.0\ef.dll migrations add Release_3_1_2_0 --json --context ProductName_FrameworkEntities --verbose --no-color --prefix-output --assembly    D:\ProductNameCore\src\CompanyName.ProductName.Demo\bin\Debug\netcoreapp2.0\CompanyName.ProductName.EntityFramework.dll --startup-assembly    D:\ProductNameCore\src\CompanyName.ProductName.Demo\bin\Debug\netcoreapp2.0\CompanyName.ProductName.Demo.dll --project-dir    D:\ProductNameCore\src\CompanyName.ProductName.EntityFramework\ --root-namespace CompanyName.ProductName.EntityFramework
    Using assembly 'CompanyName.ProductName.EntityFramework'.
    Using startup assembly 'CompanyName.ProductName.Demo'.
    Using application base    'D:\ProductNameCore\src\CompanyName.ProductName.Demo\bin\Debug\netcoreapp2.0'.
    Using working directory 'D:\ProductNameCore\src\CompanyName.ProductName.Demo'.
    Using root namespace 'CompanyName.ProductName.EntityFramework'.
    Using project directory 'D:\ProductNameCore\src\CompanyName.ProductName.EntityFramework\'.
    Finding DbContext classes...
    Finding IDesignTimeDbContextFactory implementations...
    Finding application service provider...
    Finding BuildWebHost method...
    Using environment 'Development'.
    Using application service provider from BuildWebHost method on 'Startup'.
    Found DbContext 'AuthDbContext'.
    Found DbContext 'Application_FrameworkEntities'.
    Found DbContext 'ProductName_FrameworkEntities'.
    Finding DbContext classes in the project...
    Found DbContext 'ApplicationDbContext'.
    Using context 'ProductName_FrameworkEntities'.
    infoinfo: Microsoft.EntityFrameworkCore.Infrastructure[10403]
          Entity Framework Core 2.0.3-rtm-10026 initialized 'ProductName_FrameworkEntities' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: None
    : Microsoft.EntityFrameworkCore.Infrastructure[10403]
          Entity Framework Core 2.0.3-rtm-10026 initialized 'ProductName_FrameworkEntities' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: None
    Finding design-time services for provider 'Npgsql.EntityFrameworkCore.PostgreSQL'...
    Using design-time services from provider 'Npgsql.EntityFrameworkCore.PostgreSQL'.
    Finding IDesignTimeServices implementations in assembly 'CompanyName.ProductName.Demo'...
    No design-time services were found.
    System.ArgumentNullException: Value cannot be null.
    Parameter name: key
       at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
       at Microsoft.EntityFrameworkCore.RelationalMetadataExtensions.Relational(IKey key)
       at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<Add>d__35.MoveNext()
       at System.Linq.Enumerable.<CastIterator>d__34`1.MoveNext()
       at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
       at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<Add>d__26.MoveNext()
       at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<DiffCollection>d__50`1.MoveNext()
       at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
       at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
       at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IModel source, IModel target)
       at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace)
       at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
    Value cannot be null.
    Parameter name: key

**Comment by ajcvickers** [comment] 2018-06-20 23:45
@jceddy There is nothing obvious here. I think we will need a full project/solution or complete code listing to be able to fully investigate.

**Comment by jceddy** [comment] 2018-06-21 13:53
Which files are actually involved in this process? Is it just the current snapshot and the model itself, or does it also look at the previous migration file, or all migration files? I might be able to narrow it down to changes made in the last month or two.

**Comment by ajcvickers** [comment] 2018-06-21 16:30
@jceddy Probably just the current model and the snapshot, but possibly also the last migration. Anything older than the last one should not be relevant.

**Comment by ajcvickers** [comment] 2018-06-28 15:56
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by cwithfourplus** [comment] 2018-08-23 18:01
Everyone in my team of 100+ developers is getting this error after Visual Studio 2017 Enterprise upgrade to 15.8.1

![image](https://user-images.githubusercontent.com/34212924/44543085-34bcfb00-a72c-11e8-8c03-78d0c9970fb1.png)

We are on .NET Core 1.1 using SDK 1.1.10, runtime 1.1.9 and EF Core Version 1.1.6

I don't think this issue should be closed just like it

**Comment by reinux** [comment] 2021-12-05 08:12
@cwithfourplus @jceddy I know it's been a while, but did you ever find out what was going on?

**Comment by cwithfourplus** [comment] 2021-12-05 13:12
@reinux I did not get a solution to this and I rather moved to SSDT for applying database changes as it is more reliable and can be applied to SQL database out of any order, i.e. If I want I can merge any SQL object change in my release branch from dev branch and simply ask it to apply changes. The SSDT runtime automatically generates difference scripts. And at this point if you need to update data, you can do it via Pre-deployment or Post-deployment scripts.

**Comment by ErikEJ** [comment] 2021-12-05 14:37
@cwithfourplus have you tried Power Tools- it can reverse engineer EF Core code from a SSDT project.

**Comment by cwithfourplus** [comment] 2021-12-05 18:24
@reinux I am sorry I did not get it in this context. I have not tried it and if you want to be in full control of what you do, I will not go that route. 

By the way I did not put that emoji, it was added by github automatically :(

**Comment by reinux** [comment] 2021-12-05 22:01
Hmm.... I'm actually getting this exception just doing an insert.

Looking at it more closely, it's coming off a totally different call stack, so it's probably an unrelated issue... even though the message happens to be identical.

**Comment by cwithfourplus** [comment] 2021-12-06 04:20
@reinux Try "var model = new MyDbContext().Model;" and see if that gives any better error.

**Comment by reinux** [comment] 2021-12-06 04:25
I *just* found the problem... turns out I was giving it a null value 🤦‍♂️

Even with non-nullables, sometimes things sneak through, especially when you select entire entities.

The lesson here is probably always to query for individual fields.

**Closed** 2022-10-16 12:32 UTC
Labels: closed-no-further-action, customer-reported
