### ISSUE TITLE
Unit testing with SQLite db throws DllNotFoundException

### ISSUE THREAD

**Issue by giri-nitesh** [dotnet/efcore#16333] opened 2019-06-28 11:43 UTC
I have a .NET Core 2.2 solution with APIs written in it and .NET Standard 2.0 for DAC layer. I am unit testing my code with specflow and I am using SQLite in memory database. The unit test solution builds fine but I get this error when I try to run tests.
```
**Message:** The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. -> Exception has been thrown by the target of an invocation. -> Unable to load DLL 'e_sqlite3' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```
### Further technical details
EF Core version: (2.2.4)
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer Version:2.2.4)
Operating system: Windows 10
IDE: (Visual Studio 2019)

**Comment by ajcvickers** [comment] 2019-06-29 16:51
@giri-nitesh Please post a small, runnable project/solution that demonstrates the behavior you are seeing so that we can fully investigate.

**Comment by giri-nitesh** [comment] 2019-07-01 08:53
This is the sample unit test project which I created to reproduce the issue. Though I have not created the sample for my data access layer project, you could use any of the SQL Server database to reproduce the issue.
[Sample.UnitTest.zip](https://github.com/aspnet/EntityFrameworkCore/files/3344669/Sample.UnitTest.zip)

**Comment by ajcvickers** [comment] 2019-07-01 19:12
@giri-nitesh I am not able to build the project. Looks like it has missing code/dependencies.

**Comment by giri-nitesh** [comment] 2019-07-02 05:59
Yes it needs a reference of some dbContext(I have referred this as **MyDbContext**). I was not able to create a sample for the db. @ajcvickers you can use the reference of any db that uses sql server.

**Comment by ajcvickers** [comment] 2019-07-02 15:11
@giri-nitesh I'm a bit confused by why you're suggesting that I use a SQL Server database when the issue is about using SQLite. 

What would be really great is if you could create a small program (just a console application is fine) that I can _run_ and it will demonstrate the issue you are having. As soon as I am writing code to add to your solution I have to start guessing what to write, which means I can easily miss what is relevant to reproducing the issue you are seeing.

**Comment by giri-nitesh** [comment] 2019-07-02 18:38
Actually, I am using SQL Server db to build my application, and SQLite db for unit testing. Also, to reproduce the issue we just need to use a reference of any db context(which is my web application database), on which I would be unit testing by making use of SQLite db.

For example, I am using following snippet to create a SQLite db for unit testing. Here, MyDbContext is the application database (SQL Server database).
> DbContextOptionsBuilder<MyDbContext> builder = new DbContextOptionsBuilder<MyDbContext>();
            builder.UseSqlite("DataSource=:memory:", x => x.SuppressForeignKeyEnforcement());
            var dbContext = new MyDbContext(builder.Options);
            dbContext.Database.OpenConnection();

Meanwhile, I try to post a runnable project which would demo the issue.

**Comment by ajcvickers** [comment] 2019-07-12 15:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:28 UTC
Labels: closed-could-not-reproduce, customer-reported
