### ISSUE TITLE
OOM Exception occur when foreign key constraint violet

### ISSUE THREAD

**Issue by dhartimakwana** [dotnet/efcore#26219] opened 2021-09-30 10:29 UTC
Hi,

In ApplicationDbContext class we have defined all DbSet which we are using in application,

```
public virtual DbSet<TestSchool> TestSchools { get; set; }
public virtual DbSet<TestStudent> TestStudents { get; set; }
```

Here we registers a DbContext subclass called ApplicationDbContext as a scoped service in the application service provider,

```
services.AddDbContext<ApplicationDbContext>(
        options => options.UseSqlServer("name=ConnectionStrings:DefaultConnection"));
```

**Problem Statement** : When Foreign key constraint violet at that time it's loads all the records of tables (DbSet which we define in ApplicationDbContext class) in memory so memory usage is very high and OOM exception occur.
Please refer memory profiler SS for foreign key constraint violet,
![image](https://user-images.githubusercontent.com/81281122/135438848-bc2f9c07-64dc-4cac-83f8-08981bb4f4ee.png)

![image](https://user-images.githubusercontent.com/81281122/135438737-10d8c036-ba82-471e-8a1a-20da91aaf8ee.png)

Any help or hint how to approach this issue would be highly appreciated

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows
IDE: Visual Studio 2019 16.10.0

**Comment by ErikEJ** [comment] 2021-09-30 10:38
Serilog ??

**Comment by dhartimakwana** [comment] 2021-09-30 11:31
Yes

**Comment by ajcvickers** [comment] 2021-09-30 11:35
@dhartimakwana  Duplicate of #15214. You'll need to use Serilog.Exceptions.EntityFrameworkCore.

**Closed** 2022-10-16 20:09 UTC
Labels: customer-reported
