### ISSUE TITLE
dbcontext scaffold --> The given key was not found in the dictionary

### ISSUE THREAD

**Issue by 12michel34** [dotnet/efcore#3907] opened 2015-11-27 07:36 UTC
Try to run dbcontext scaffold against a remote SQL-server and got this output:
![schmal](https://cloud.githubusercontent.com/assets/3438078/11436008/c57a23e0-94e0-11e5-8362-05207ad60780.PNG)
When i try the same against another database on the same server everything works fine. With the EF6 ADO.NET Entity Data Model (EF Designer From Database) the database is also accessible without problems. What could be the reason.

**Comment by lajones** [comment] 2015-11-30 18:06
This looks identical to #3861. So closing this as a duplicate.

The cause is probably that there is an index for which we cannot find the table to which it belongs. Regardless, we should be giving better error messages. But if you can add your DB schema to that bug that may help us track down either which index is causing the problem or why the scaffolding code is failing to recognize its table.

**Closed** 2022-10-16 09:18 UTC
