### ISSUE TITLE
Dependency Injection into DbContext for HasData Seed Data

### ISSUE THREAD

**Issue by wadebee** [dotnet/efcore#12403] opened 2018-06-18 23:09 UTC
I currently have a DbContextInitializer class that loads my seed data from json files. This initializer has a dependency on IFileProvider. It all works fine now with an Initialize method that seeds like this:
`            
if (!Context.EntitySet.Any())
            {
                Context.EntitySet.AddRange(GetSeedData());
                Context.SaveChanges();
            }
`
I wanted to try to convert this over to the new EFCore 2.1 HasData implementation. However it seems HasData calls are scope-limited to the DbContext OnModelCreating event handler. 

It would be great if I could attach my DbInitializer (or even just the IFileProvider) to my DbContextOptions where I can attach it from the DbContext constructor to a member field making it accessible to OnModelCreating. 

However I don't see a way to attach anything to DbContextOptions and I can't find a way to inject anything into my DbContext derived class constructor.

Am I missing something?

**Comment by ajcvickers** [comment] 2018-06-19 00:04
@wadebee You can use normal constructor injection on the derived DbContext type.

**Comment by wadebee** [comment] 2018-06-19 02:05
Normal constructor injection fails with code migrations.

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by ajcvickers** [comment] 2018-06-20 23:48
@wadebee When using the normal patterns for an ASP.NET app startup, EF should resolve your DbContext from your service provider, so it should not need a parameterless constructor. Can you post either a full project/solution that demonstrates what you are seeing, or at least your Program.cs and Startup.cs files?

**Comment by ajcvickers** [comment] 2018-06-27 16:19
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:32 UTC
Labels: closed-could-not-reproduce, customer-reported
