### ISSUE TITLE
Issue with Include of types using nullable fields on Table Splitting

### ISSUE THREAD

**Issue by Mabiro** [dotnet/efcore#24522] opened 2021-03-26 16:43 UTC
Hello,

I am having an issue with the use of table splitting and nullable fields when trying to include navigations in a request. At first, I thought it was an Npgsql issue, but after trying with SqlServer, I get the same problem.

Basically, my setup is:
1 Parent entity
1 Partial Parent Entity which uses table splitting with the Parent Entity
1 Child entity which has a navigation property on the Partial Parent Entity

If I have a nullable field on the Parent&Partial entity, it seems like fetching the child while including the partial will not return data if the nullable field is null, due to the addition of a WHERE field IS NOT NULL clause.

I have a sample app which I stripped down to its core, all that's left to do is generate migrations and plug in a postgresql connection string :
Using EF Core 5.0.4 and Npgsql.EfCore 5.0.2

```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Console;

using System;
using System.Threading.Tasks;

namespace ConsoleApp13
{
    class Program
    {
        async static Task Main(string[] args)
        {
            var dbContextOptionsBuilder = new DbContextOptionsBuilder<MyDbContext>();
            dbContextOptionsBuilder.UseNpgsql("connectionstring");

            var dbContext = new MyDbContext(dbContextOptionsBuilder.Options);

            await dbContext.Database.MigrateAsync();

            var rootEntity = new RootEntity(Guid.NewGuid());
            await dbContext.Set<RootEntity>().AddAsync(rootEntity);
            dbContext.SaveChanges();

            var childEntity = new ChildEntity(Guid.NewGuid()) { RootEntityId = rootEntity.Id };
            await dbContext.Set<ChildEntity>().AddAsync(childEntity);
            dbContext.SaveChanges();


            var fetchedEntity = await dbContext.Set<ChildEntity>().Include(x => x.SplittedRootEntity).FirstOrDefaultAsync(x => x.Id == childEntity.Id);
        }
    }

    public class RootEntity
    {
        public RootEntity(Guid id)
        {
            Id = id;
        }

        public Guid Id { get; set; }
        public Guid? OptionalField { get; set; }
    }

    public class ChildEntity
    {
        public ChildEntity(Guid id)
        {
            Id = id;
        }

        public Guid Id { get; set; }
        public Guid RootEntityId { get; set; }

        public SplittedRootEntity SplittedRootEntity { get; set; }
    }

    public class SplittedRootEntity
    {
        public Guid Id { get; set; }
        public Guid? OptionalField { get; set; }

        public RootEntity Root { get; set; }
    }

    public class RootEntityConfiguration : IEntityTypeConfiguration<RootEntity>
    {
        public void Configure(EntityTypeBuilder<RootEntity> builder)
        {
            builder.ToTable("root");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id)
                .HasColumnName("id")
                .ValueGeneratedNever();
        }
    }

    public class SplittedRootEntityConfiguration : IEntityTypeConfiguration<SplittedRootEntity>
    {
        public void Configure(EntityTypeBuilder<SplittedRootEntity> builder)
        {
            builder.ToTable("root");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id)
                .HasColumnName("id")
                .ValueGeneratedNever();

            builder.HasOne(x => x.Root)
                .WithOne()
                .HasForeignKey<SplittedRootEntity>(x => x.Id);
        }
    }

    public class ChildEntityConfiguration : IEntityTypeConfiguration<ChildEntity>
    {
        public void Configure(EntityTypeBuilder<ChildEntity> builder)
        {
            builder.ToTable("child");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id)
                .HasColumnName("id")
                .ValueGeneratedNever();

            builder.HasOne(x => x.SplittedRootEntity)
                .WithMany()
                .HasForeignKey(x => x.RootEntityId);
        }
    }

    public class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions<MyDbContext> options)
            : base(options)
        {

        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseLoggerFactory(LoggerFactory.Create(builder => { builder.AddConsole(); }))
                .EnableSensitiveDataLogging();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.ApplyConfigurationsFromAssembly(typeof(MyDbContext).Assembly);
        }
    }

    public class MyDbContextDesignTimeFactory : IDesignTimeDbContextFactory<MyDbContext>
    {
        public MyDbContext CreateDbContext(string[] args)
        {
            Console.WriteLine("Creating new db context");

            var optionsBuilder = new DbContextOptionsBuilder<MyDbContext>();

            var options = optionsBuilder.UseNpgsql(".")
                                        .Options;

            var dbContext = new MyDbContext(options);
            return dbContext;
        }
    }
}
```

Here is the SQL query generated by the fetch + include

```sql
SELECT c.id, c."RootEntityId", t.id, t."SplittedRootEntity_OptionalField"
      FROM child AS c
      INNER JOIN (
          SELECT r.id, r."SplittedRootEntity_OptionalField"
          FROM root AS r
          INNER JOIN root AS r0 ON r.id = r0.id
          WHERE (r."SplittedRootEntity_OptionalField" IS NOT NULL)
      ) AS t ON c."RootEntityId" = t.id
      WHERE c.id = @__childEntity_Id_0
      LIMIT 1
```
As you can see, somehow there is a WHERE (r."SplittedRootEntity_OptionalField" IS NOT NULL) added in the query, even thought the field is nullable.

If I set a value for OptionalField, it will return the data correctly.

Thanks!

EF Core version: 5.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer and Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: net5.0
Operating system: Windows
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment] 2021-03-29 17:52
@Mabiro This is a duplicate of #23564. You can get the behavior you are expecting by explicitly marking the dependent as required. For example:

```C#
var fk = builder.HasOne(x => x.Root)
    .WithOne()
    .HasForeignKey<SplittedRootEntity>(x => x.Id).Metadata;

fk.IsRequiredDependent = true;
```

The same query then generates the following SQL:

```sql
      SELECT TOP(1) [c].[id], [c].[RootEntityId], [t].[id], [t].[SplittedRootEntity_OptionalField]
      FROM [child] AS [c]
      INNER JOIN (
          SELECT [r].[id], [r].[SplittedRootEntity_OptionalField]
          FROM [root] AS [r]
          INNER JOIN [root] AS [r0] ON [r].[id] = [r0].[id]
      ) AS [t] ON [c].[RootEntityId] = [t].[id]
      WHERE [c].[id] = @__childEntity_Id_0
```

**Closed** 2022-10-16 19:29 UTC
Labels: closed-duplicate, customer-reported
