### ISSUE TITLE
Stored procedures called multiple times in miliseconds

### ISSUE THREAD

**Issue by MFiliz** [dotnet/efcore#27101] opened 2022-01-03 16:20 UTC
Hi
I am using net 5 with EF core 5.0.7 version. 
I have always on 1 master and 2 slave SQL server and 6 web servers. 
2 dbcontext standing on my project , one of these readonly and other master context for insert update delete.

Generally I used linq queries with isolation level with begintransaction. My 3-5 query has stored procedure to call with fromsql method

That is the point. Sometimes especially under workload stored procedures called multiple times in miliseconds that I can see on my log table. 

Sometimes EF ignore to run procedure calls . 

Has anyone define this situation as a bug or my mistake

Regards

**Comment by ajcvickers** [comment] 2022-01-04 13:34
@MFiliz This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing (or at least reproduces what your code is doing, even if it doesn't cause the error because its not under load) so that we can investigate.

**Comment by ajcvickers** [comment] 2022-01-14 09:07
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:21 UTC
Labels: closed-could-not-reproduce, customer-reported
