### ISSUE TITLE
Upgrade from EF Core 2.x to 6.x performance degradation

### ISSUE THREAD

**Issue by SpringLeee** [dotnet/efcore#25321] opened 2021-07-23 11:11 UTC
I found that after upgrading from EF Core 2.x to EF Core 6.x，both queries and inserts are slow, I tested it many times and the results are similar

## Environment

.NET 5

EF Core 2.x

```
<PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

	<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql" Version="4.1.4-preview50" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.2.4" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.2.6" />
  </ItemGroup>
```

EF Core 6.x

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0-preview.5.21301.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0-preview.5.21301.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Npgsql" Version="6.0.0-preview5422" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.0-preview5" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="6.0.0-preview.5" />
	</ItemGroup> 

</Project>

```

## Code

```
        [HttpGet]
        public async Task RawQuery()
        {
            using var conn = new NpgsqlConnection(_configuration.GetConnectionString("PostgreSql"));

            conn.Open();
            using (var cmd = new NpgsqlCommand())
            {
                cmd.Connection = conn;
                cmd.CommandType = System.Data.CommandType.Text;
                cmd.CommandText = $"SELECT * FROM \"Students\"";
                NpgsqlDataAdapter sda = new NpgsqlDataAdapter(cmd);
                DataTable dt = new DataTable();
                sda.Fill(dt);
            }
        }

        [HttpGet]
        public async Task RawSave()
        {
            using var conn = new NpgsqlConnection(_configuration.GetConnectionString("PostgreSql"));

            conn.Open();
            using (var cmd = new NpgsqlCommand())
            {
                cmd.Connection = conn;
                cmd.CommandType = System.Data.CommandType.Text;
                cmd.CommandText = $"Insert Into \"Teachers\" values ('{Guid.NewGuid().ToString()}','Lee','Lee',now())";
                var result = await cmd.ExecuteNonQueryAsync();
            }
        }



        [HttpGet]
        public async Task<IActionResult> Query()
        { 
            var users = _schoolContext.Students.ToList();

            return await Task.FromResult(Ok(users));  
        }  

        [HttpGet]
        public async Task<IActionResult> Save()
        { 
            await _schoolContext.Teachers.AddAsync(new Teacher
            {
                Id = Guid.NewGuid().ToString(),
                FirstMidName = "Lee",
                LastName = "Lee",
                EnrollmentDate = DateTime.Now
            });

            await _schoolContext.SaveChangesAsync(); 

            return Ok(); 
        } 
```

## Results

![image](https://user-images.githubusercontent.com/15724803/126772038-cda051a8-d8a4-4682-8bbf-52b8a3459a89.png)

**Comment by ajcvickers** [comment] 2021-07-23 17:17
@AndriySvyryd to take a look.

**Comment by roji** [comment] 2021-07-25 18:18
@AndriySvyryd I should be able to take a look at this in the coming days.

**Comment by roji** [comment] 2021-07-26 16:05
I was unable to reproduce the performance gap you mention above. With my own, minimal/isolated BenchmarkDotNet benchmarks, I see the following results:

```
BenchmarkDotNet=v0.13.0, OS=ubuntu 20.10
Intel Xeon W-2133 CPU 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET SDK=5.0.200
  [Host]     : .NET 5.0.3 (5.0.321.7212), X64 RyuJIT
  DefaultJob : .NET 5.0.3 (5.0.321.7212), X64 RyuJIT

```

### Npgsql & Npgsql.EntityFrameworkCore.PostgreSQL 6.0.0-preview5

|   Method |       Mean |    Error |   StdDev |
|--------- |-----------:|---------:|---------:|
| RawQuery |   244.8 us |  5.67 us | 16.71 us |
|  RawSave | 1,210.1 us | 17.27 us | 15.31 us |
|    Query |   448.4 us | 11.81 us | 34.82 us |
|     Save | 1,942.4 us | 34.10 us | 31.90 us |

### Npgsql 4.1.9 & Npgsql.EntityFrameworkCore.PostgreSQL 2.2.4

|   Method |       Mean |    Error |   StdDev |     Median |
|--------- |-----------:|---------:|---------:|-----------:|
| RawQuery |   247.0 us |  7.13 us | 21.03 us |   251.0 us |
|  RawSave | 1,192.8 us | 18.60 us | 17.40 us | 1,195.1 us |
|    Query |   399.8 us | 10.13 us | 29.87 us |   409.5 us |
|     Save | 1,844.1 us | 24.22 us | 22.65 us | 1,847.0 us |

Here are some comments:

* The code sample is partial, with important things missing, e.g. the definitions of the Teacher and Student types. I've created what I hope are reasonable approximations, but you generally need to submit full, runnable source code.
* It's not clear how exactly you're measuring - what HTTP client software is being used, how it's parameterized, what kind of warm-up is used...
* It's generally better to isolate the operation you're trying to benchmark; in this case, a BenchmarkDotNet that purely executes the database operations is likely a better choice than a web benchmark (which may also show perf differences stemming from different ASP.NET versions). See my benchmark code below, based on your code.
* Although all the benchmark methods above are marked as async, only Save actually performs asynchronous operations. This means you're comparing sync and async operations, which have different perf profiles.
* Your "raw" and EF tests aren't really apples-to-apples comparisons. For example, your EF tests use change tracking, which adds a substantial overhead that isn't present in the raw benchmarks (you can disable change tracking to have more comparable results). Note also that in the BenchmarkDotNet code I wrote (below), DbContext pooling isn't being used, which also makes the EF perf worse than it could be. If the goal here is to compare different version of EF then that's OK, but if you're trying to measure the overhead of EF compared to raw ADO.NET, then the benchmark is very inaccurate.
* Your "save" tests add actual rows to the table; this means that as the table grows, performance may change and measurements would be skewed. It's better to repeatedly send UPDATEs instead of INSERTs in order to avoid this problem, or roll back inserts via transactions.

<details>
<summary>Benchmark code</summary>

```c#
public class Program
{
    public const string ConnectionString = "Host=localhost;Username=test;Password=test";

    [GlobalSetup]
    public async Task Setup()
    {
        using var ctx = new SchoolContext();
        await ctx.Database.EnsureDeletedAsync();
        await ctx.Database.EnsureCreatedAsync();
    }

    [Benchmark]
    public async Task RawQuery()
    {
        using var conn = new NpgsqlConnection(ConnectionString);

        conn.Open();
        using var cmd = new NpgsqlCommand("SELECT * FROM \"Students\"", conn);
        NpgsqlDataAdapter sda = new NpgsqlDataAdapter(cmd);
        DataTable dt = new DataTable();
        sda.Fill(dt);
    }

    [Benchmark]
    public async Task RawSave()
    {
        using var conn = new NpgsqlConnection(ConnectionString);

        conn.Open();
        using var cmd = new NpgsqlCommand($"Insert Into \"Teachers\" values ('{Guid.NewGuid().ToString()}','Lee','Lee',now())", conn);
        _ = await cmd.ExecuteNonQueryAsync();
    }

    [Benchmark]
    public async Task Query()
    {
        using var ctx = new SchoolContext();
        _ = ctx.Students.ToList();
    }

    [Benchmark]
    public async Task Save()
    {
        using var ctx = new SchoolContext();

        await ctx.Teachers.AddAsync(new Teacher
        {
            Id = Guid.NewGuid().ToString(),
            FirstMidName = "Lee",
            LastName = "Lee",
            EnrollmentDate = DateTime.Now
        });

        await ctx.SaveChangesAsync();
    }

    static void Main(string[] args)
        => BenchmarkRunner.Run<Program>();
}

public class SchoolContext : DbContext
{
    public DbSet<Student> Students { get; set; }
    public DbSet<Teacher> Teachers { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseNpgsql(Program.ConnectionString);
}

public class Student
{
    public string Id { get; set; }
    public string FirstMidName { get; set; }
    public string LastName { get; set; }
    public DateTime EnrollmentDate { get; set; }
}

public class Teacher
{
    public string Id { get; set; }
    public string FirstMidName { get; set; }
    public string LastName { get; set; }
    public DateTime EnrollmentDate { get; set; }
}

**Comment by SpringLeee** [comment] 2021-07-29 10:31
Thanks everyone, i carefully read Roji's suggestion,  and i also did a benchmark test, it was found that the test results of roji are roughly the same, my previous test results should not be very accurate (it may be affected by other environments),  thanks.

**Closed** 2022-10-16 19:40 UTC
Labels: closed-no-further-action, customer-reported
