### ISSUE TITLE
The specified deps.json [C:\dddddd\WebApplication2\WebApplication2\WebApplication2.deps.json] does not exist

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#23054] opened 2020-10-19 22:43 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/897046/the-specified-depsjson-cddddddwebapplication2webap.html)._

---
I'm trying to scaffold an exiting database using asp.net c0re 3.1  and EF Core .. unfortunately 
when  using PMC with Scaffold-DbContext "Server=.;D atabase=WEB50; Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Entity -force
command I am getting the following message.. The file (... deps.json is located under bin directory, but it is looking for anoter place ..

The specified deps.json [C:\dddddd\WebApplication2\WebApplication2\WebApplication2.deps.json] does not exist

I have a Casper Notebook with Windows 10 running..
I have installed VS 2019 (16.4.3)today with latest  entity core pacakeges (all 3.1.1) but nothing changed.. the previous posts did not help either..

---
#### cetinogut on 1/26/2020, 08:08 PM: 

The following is the content of .csproj file:<br>&lt;Project Sdk=&quot;Microsoft.NET.Sdk.Web&quot;&gt;<br><br>  &lt;PropertyGroup&gt;<br>    &lt;TargetFramework&gt;netcoreapp3.1&lt;/TargetFramework&gt;<br>  &lt;/PropertyGroup&gt;<br><br>  &lt;ItemGroup&gt;<br>    &lt;PackageReference Include=&quot;Microsoft.EntityFrameworkCore&quot; Version=&quot;3.1.1&quot; /&gt;<br>    &lt;PackageReference Include=&quot;Microsoft.EntityFrameworkCore.SqlServer&quot; Version=&quot;3.1.1&quot; /&gt;<br>    &lt;PackageReference Include=&quot;Microsoft.EntityFrameworkCore.Tools&quot; Version=&quot;3.1.1&quot;&gt;<br>      &lt;PrivateAssets&gt;all&lt;/PrivateAssets&gt;<br>      &lt;IncludeAssets&gt;runtime; build; native; contentfiles; analyzers; buildtransitive&lt;/IncludeAssets&gt;<br>    &lt;/PackageReference&gt;<br>  &lt;/ItemGroup&gt;<br><br><br><br>&lt;/Project&gt;<br>
#### Feedback Bot on 1/27/2020, 08:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/5/2020, 07:40 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Feedback Bot on 7/16/2020, 02:14 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Deep Choudhery [MSFT] on 10/9/2020, 02:14 PM: 

<p>Hey,</p><p>Have you experienced this issue in 16.7.x at all? We have had fixes for similar issues and believe it should be resolved in the latest versions of VS. </p><p>Please let me know,</p><p>Thanks.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2020-10-19 22:48
Duplicate of #22247

**Closed** 2022-10-16 19:05 UTC
Labels: customer-reported
