### ISSUE TITLE
Finding recursive relationships in a mapping table is mapping bad data.

### ISSUE THREAD

**Issue by bdparrish** [dotnet/efcore#6650] opened 2016-09-30 15:21 UTC
### Steps to reproduce

I want to find a parent-child graph relationship between tuples.

``` csharp
    [Table("node_edges")]
    public partial class NodeEdge
    {
        [Column("id")]
        public Guid Id { get; set; }

        [Column("name")]
        public string Name { get; set; }

        [Column("created")]
        public DateTime Created { get; set; }

        [Column("modified")]
        public DateTime Modified { get; set; }

        [Column("text")]
        public string Text { get; set; }

        [Column("hash")]
        public string Hash { get; set; }

        [Column("is_node")]
        public bool IsNode { get; set; }

        public virtual ICollection<Tuple> Sources { get; set; }

        public virtual ICollection<Tuple> Destinations { get; set; }

        public virtual ICollection<Tuple> Edges { get; set; }
    }
```

``` csharp
    [Table("tuples")]
    public partial class Tuple
    {
        [Column("source_id")]
        public Guid SourceId { get; set; }

        [Column("dest_id")]
        public Guid DestinationId { get; set; }

        [Column("edge_id")]
        public Guid EdgeId { get; set; }

        [Column("direction")]
        public TupleDirection Direction { get; set; }

        public virtual Item Source { get; set; }

        public virtual Item Destination { get; set; }

        public virtual Item Edge { get; set; }
    }
```

``` csharp
    public class PostgresContext : DbContext
    {
        public PostgresContext (DbContextOptions options) : base(options)
        {
        }

        public DbSet<Model.Item> Items { get; set; }
        public DbSet<Model.Tuple> Tuples { get; set; }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.HasPostgresExtension("uuid-ossp");

            // node_edge fields
            builder.Entity<Item>().HasKey(m => m.Id);

            // node_edge relationships
            builder.Entity<Item>().HasMany(m => m.Sources).WithOne(t => t.Source).HasForeignKey(t => t.SourceId);
            builder.Entity<Item>().HasMany(m => m.Destinations).WithOne(t => t.Destination).HasForeignKey(t => t.DestinationId);
            builder.Entity<Item>().HasMany(m => m.Edges).WithOne(t => t.Edge).HasForeignKey(t => t.EdgeId);

            // tuple fields
            builder.Entity<Tuple>().HasKey(m => m.SourceId);
            builder.Entity<Tuple>().HasKey(m => m.DestinationId);
            builder.Entity<Tuple>().HasKey(m => m.EdgeId);

            // tuple relationships
            builder.Entity<Tuple>().HasOne(m => m.Source).WithMany(i => i.Sources).HasForeignKey(m => m.SourceId);
            builder.Entity<Tuple>().HasOne(m => m.Destination).WithMany(i => i.Destinations).HasForeignKey(m => m.DestinationId);
            builder.Entity<Tuple>().HasOne(m => m.Edge).WithMany(i => i.Edges).HasForeignKey(m => m.EdgeId);

            base.OnModelCreating(builder);
        }
    }
```
### The issue

I am using a repository pattern to find all data on an MVC controller.  The DbContext is instantiated once per repository.  I am trying to find all parent-child relationships in a recursive fashion, but I am running into an issue with relationships.  When mapping database info to the model there is confusion about which model to use.  If I create a new instantiation of the DbContext, PostgresContext in this case, then everything is fine.

Here are the two options in my `Get(Guid id)` method:

Original:

``` csharp
        public Model.Item Get(Guid id)
        {
            Model.Item item = _context.Items
                .Include(i => i.Type)
                .Include(i => i.Categoricals)
                .Include(i => i.Quantitatives)
                .Include(i => i.Sources)
                .Include(i => i.Destinations)
                .Include(i => i.Edges)
                .First(i => i.Id.Equals(id));

            return item;
        }
```

``` csharp
        public Model.Item Get(Guid id)
        {
            Model.Item item = _context.Items
                .Include(i => i.Type)
                .Include(i => i.Categoricals)
                .Include(i => i.Quantitatives)
                .First(i => i.Id.Equals(id));

            var optionsBuilder = new DbContextOptionsBuilder<PostgresPrCoreContext>();
            optionsBuilder.UseNpgsql("User ID=postgres;Password=password;Host=10.10.3.191;Port=5432;Database=pr_core;Pooling=true;");

            item.Destinations = new PostgresPrCoreContext(optionsBuilder.Options).Tuples.Where(t => t.DestinationId.Equals(id)).ToList();
            item.Sources = new PostgresPrCoreContext(optionsBuilder.Options).Tuples.Where(t => t.SourceId.Equals(id)).ToList();
            item.Edges = new PostgresPrCoreContext(optionsBuilder.Options).Tuples.Where(t => t.EdgeId.Equals(id)).ToList();

            return item;
        }
```

The latter of these two methods provides the correct data.  Is this the normal way to handle this data?
### Further technical details

EF Core version: 1.0.1
Operating system: Windows 7
Visual Studio version: 

```
Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community
```

Other details about my project setup: "Npgsql.EntityFrameworkCore.PostgreSQL": "1.0.2"

**Comment by smitpatel** [comment] 2016-10-07 00:29
@bdparrish - This part seems incorrect. Based on model, `Tuple` should have composite PK.
```c#
 // tuple fields
            builder.Entity<Tuple>().HasKey(m => m.SourceId);
            builder.Entity<Tuple>().HasKey(m => m.DestinationId);
            builder.Entity<Tuple>().HasKey(m => m.EdgeId);
```
Above does not define a composite PK. It will re-define current PK and you will get EdgeId as PK finally.
To define composite PK you need to use
`builder.Entity<Tuple>().HasKey(m => new { m.SourceId, m.DestinationId, m.EdgeId });`

**Comment by bdparrish** [comment] 2016-10-07 00:52
@smitpatel, that makes sense because that table in the database is setup that way, but I have a one to many relationship for each of those keys part between an item and the three tuple keys.  Each one to many relationship from item to tuple is not giving me the right objects back.  It seems to be caching them in some manner.  I have to create a new context every time to get the new object relationships as I track up the child parent relationships between item-tuple-item-tuple-item for example.

**Comment by smitpatel** [comment] 2016-10-26 20:01
I tried reproducing this, but above configuration of classes gave cyclic dependency issue.
@bdparrish - Include should load the data automatically without new-ing up context every time.
Can you provide a full repro code with sample data?

**Comment by smitpatel** [comment] 2016-11-04 00:56
Closing since I am not able to reproduce this.

**Closed** 2022-10-16 10:37 UTC
Labels: closed-could-not-reproduce
