### ISSUE TITLE
Flaky Test: EnsuredCreated_is_noop_when_database_with_filename_exists_and_has_schema

### ISSUE THREAD

**Issue by mikeharder** [dotnet/efcore#8289] opened 2017-04-26 18:59 UTC
```
[Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.SqlServerDatabaseCreatorEnsureCreatedTest.EnsuredCreated_is_noop_when_database_with_filename_exists_and_has_schema] System.InvalidOperationException : This SqlTransaction has completed; it is no longer usable.
   at System.Data.SqlClient.SqlTransaction.ZombieCheck()
   at System.Data.SqlClient.SqlTransaction.Commit()
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Commit()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.SqlServerDatabaseCreatorEnsureCreatedTest.<EnsuredCreated_is_noop_when_database_exists_and_has_schema_test>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.SqlServerDatabaseCreatorEnsureCreatedTest.<EnsuredCreated_is_noop_when_database_with_filename_exists_and_has_schema>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

# Repros
4/26/17: http://aspnetci/viewLog.html?buildId=208861&buildTypeId=Lite_EntityFrameworkTest&tab=buildLog&filter=err

**Comment by smitpatel** [comment] 2017-04-28 19:51
I investigated this and there seems to be nothing wrong with test. The exception happens in `EnsureCreated` which is used in almost all tests and by many customer. Perhaps some random environment situation caused it but it never reproduced again.
Closing for now because there is nothing actionable.

**Closed** 2022-10-16 11:02 UTC
Labels: closed-could-not-reproduce
