### ISSUE TITLE
Entity Framework "The operation failed as details for project Xxx (Standard) could not be loaded."

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#10970] opened 2018-02-14 19:31 UTC
From VS Feedback:

Code first migration in entity framework has suddenly stopped working on one of my projects. Entering any EF command in the Package Manager Console results in an exception due to "The operation failed as details for <project name> could not be loaded. In my case <project name> happens to be a .NET 2.0 Standard library.

The only think I can think of that has changed since I last worked on this project is that I updated my version of Visual Studio 2017 to the latest version (15.5.6).

My current work-a-round seems to be to unload the .NET Standard project from the solution before attempting to perform and EF stuff on the back end project..

**Comment by JPhilC** [comment] 2018-02-15 10:10
Following a comment I saw on a similar error, but related to loading Nuget packages, with a .NET standard project I removed the '()'s from the project name and EF then started to work again. The reason I was looking for Nuget issues is that I also had this problem.

**Comment by smitpatel** [comment] 2018-02-21 20:53
Using VS 15.5.6 & EF Core 2.0.1 I am not able to reproduce this.
I have a .netcore console app as start up project and netstandard class lib (with name `ClassLibrary()`) but Migration commands are working correctly.

We will need full solution which reproduces this.

**Comment by smitpatel** [comment] 2018-03-01 00:39
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by smitpatel** [comment] 2018-03-09 00:52
This looks like issue described here https://developercommunity.visualstudio.com/content/problem/160750/nuget-bug-in-vs155.html

It is a bug in VS 15.5 and fixed in 15.6

**Closed** 2022-10-16 12:09 UTC
Labels: closed-could-not-reproduce
