### ISSUE TITLE
publish dotnet core application in docker,db connections cannot release

### ISSUE THREAD

**Issue by livarcocc** [dotnet/efcore#7954] opened 2017-03-22 15:31 UTC
_From @zhaiweihao on March 22, 2017 6:11_

I have an application  with .net core 1.1.0 and  publish it  in docker ,I find that connections in  sqlserver cannot release,
this error cause me much trouble in production environment,how can I resolve it?
when publish it in IIS ,connections are quite normal release.

I push a demo application to github,this is the address :https://github.com/zhaiweihao/DockerTest
docker version:17.03.0-ce
os :ubuntu 16.10
sql server version :Microsoft SQL Server 2012 (SP1) - 11.0.3000.0 (X64) 

I use this sql query to check connections:
select a.dbid,b.name,count(1)
from sysprocesses a
join SysDatabases b on a.dbid=b.dbid
group by a.dbid,b.name

give me a hand,Thanks!

_Copied from original issue: dotnet/cli#6106_

**Comment by ajcvickers** [comment] 2017-03-27 16:33
@zhaiweihao Can you please try this without using EF? That is, if you create and use SqlConnection's directly do you see a difference with and without docker?

**Comment by ajcvickers** [comment] 2017-03-27 19:42
Closing this a a duplicate of this issue with SQLClient: https://github.com/dotnet/corefx/issues/13422

**Closed** 2022-10-16 10:58 UTC
Labels: closed-external
