### ISSUE TITLE
Consider relaxing "SQL statements other than SELECT are recognized automatically as non-composable" for CTE

### ISSUE THREAD

**Issue by Meberem** [dotnet/efcore#16570] opened 2019-07-11 14:41 UTC
CTEs are not [recognized as composable by default](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#limitations) because they [*can*](https://docs.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-2017#guidelines-for-creating-and-using-common-table-expressions) be followed by something other than SELECT. Would it be possible to recognize when a CTE *is* followed by SELECT and allow the query to be composable?

**Comment by smitpatel** [comment] 2019-07-11 16:20
Duplicate of #4976

**Comment by smitpatel** [comment] 2019-07-11 16:21
> Would it be possible to recognize when a CTE is followed by SELECT

As for this, we explicitly decided not to do any SQL parsing to recognize features as it is prone to errors and not so provider agnostic. Hence we would have a different API, where this can specified and made it work.

**Closed** 2022-10-16 14:30 UTC
Labels: customer-reported
