### ISSUE TITLE
Exclude field(s) from query

### ISSUE THREAD

**Issue by ssougnez** [dotnet/efcore#9385] opened 2017-08-11 16:38 UTC
Hello,

say that I have a class with 20 fields that store course information and one of these field is a `longtext`. If I want to create a query that will return the *approved* courses *sorted by reading count*, I would have to do something like:

`return dbContext.Courses.Where(c => c.Approved == true).OrderByDescending(c => c.ReadingCount);`

The issue with that query is that the `longtext` field will be retrieved and it could be quite big, so if I have 100 courses, the data transfered from the database to the server could be quite big. Of course, I could do:

`return dbContext.Courses.Where(c => c.Approved == true).Select(c => new { c.Title, c.Description, ... , c.ReadingCount }.OrderByDescending(c => c.ReadingCount);`

But as I have 20 fields, it's pretty fastidious, especially if I have other queries that follow the same principle. That's why I was wondering if it would be possible to implement an `Exclude` method that would work a bit like the `Include` one except that it would be the exact opposite. The query would then become:

`return dbContext.Courses.Where(c => c.Approved == true).Exclude(c => c.Description).OrderByDescending(c => c.ReadingCount);`

There could also be an override with a `Func` returning an array to be able to exclude more fields (or something like that).

Of course, it would be up to the user not to use the excluded field in subsequent query. For example, this:

`return dbContext.Courses.Where(c => c.Approved == true).Exclude(c => c.ReadingCount).OrderByDescending(c => c.ReadingCount);`

Would fail as the `ReadingCount` field has been excluded by the user.

I'm sorry if this has already been proposed, I searched and didn't find anything.

**Comment by ajcvickers** [comment] 2017-08-17 19:24
@ssougnez Thanks for your comments. I've added a note to #1387 to look here for additional ideas and I'll close this as a duplicate of #1387 so we can track this in one place.

**Closed** 2022-10-16 11:15 UTC
