### ISSUE TITLE
Startup class ConfigureServices method not called during migration

### ISSUE THREAD

**Issue by matthieugd** [dotnet/efcore#2275] opened 2015-05-26 20:44 UTC
I have a class library project migrated from beta 3 to beta 4. In beta 3 I was able to call 

 `k ef migration add <migration name> -c <dbcontextname>`

from a command line as I provide a Startup class in my class Library project with a ConfigureServices method which configure the dbcontext .

With beta 4 I got this exception:
`System.InvalidOperationException: No data stores are configured. Configure a data store by overriding OnConfiguring in your DbContext class or in the AddDbContext method when setting up services.`

I look at the code source for ContextTool class but it's not very clear how the Startup class is used or why it would fail.

Any idea ?

**Comment by MaximBalaganskiy** [comment] 2015-05-27 00:23
Seems like Startup class is not used for migrations. The error you get indicates that your context does not have a connection string. Try setting it like this

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.UseSqlServer("connectionString");
    }

and your migrations will work.

**Comment by matthieugd** [comment] 2015-05-27 00:40
But it's not supposed to use the startup class first? If you look at the CreateContext method there's a first attempt to create from startup and then use the default ctor. 

Why the startup class is not called ?

**Comment by MaximBalaganskiy** [comment] 2015-05-27 00:51
My fault. It is called...

**Comment by MaximBalaganskiy** [comment] 2015-05-27 00:54
I've just put an exception into a startup and migration started failing for me in a fresh MVC project

**Comment by MaximBalaganskiy** [comment] 2015-05-27 01:42
So after experimenting with it a bit I've found that Startup is called when migration is called on the original MVC project and ignored when called on a class library.

**Comment by matthieugd** [comment] 2015-05-27 01:43
Did you try in a class library project? I defined an ef command and run it with the arguments (i.e. migration add <migration name> -c <dbcontextname>)

It seems that it's supported by looking at the TryCreateContextFromStartup method but the try/catch is hiding the problem since the default actor of my DbContext is called and my Startup class is not.

https://github.com/aspnet/EntityFramework/blob/7.0.0-beta4/src/EntityFramework.Commands/ContextTool.cs#L47

**Comment by MaximBalaganskiy** [comment] 2015-05-27 01:46
Yep, looking at the code seems like it should work...

**Comment by matthieugd** [comment] 2015-05-27 01:51
It seems that something is failing during the initialization of the hosting service and context. I'm going to look into it tomorrow.

**Comment by MaximBalaganskiy** [comment] 2015-05-27 03:14
Alright. I managed to make it work by creating a class library out of an MVC project and stripping almost everything from it.

**Comment by divega** [comment] 2015-05-27 04:47
> Startup is called when migration is called on the original MVC project and ignored when migration is called on a class library.

That is correct, and actually by design: on an ASP.NET application Migrations will use the __*application's*__ startup code to get the the __*application's*__ service container setup the same way it would get setup at runtime. A class library shouldn't need to have its own startup code or service container, unless it isn't really a class library but something else, e.g. a test suite or a command line app.

It would really be good for us to understand how and why you ended up wanting to get this the work in this way.

**Comment by MaximBalaganskiy** [comment] 2015-05-27 05:01
I moved the ApplicationDbContext to a separate project and added more project specific tables to it.
As I understood, I cannot currently create migrations for references assemblies. So the only option is to create migrations from the DataAccess assembly itself. But without the Startup working you cannot nicely pass a connection string to the context. Hope that clears my case :)

**Comment by matthieugd** [comment] 2015-05-27 09:41
It's a command line app use to create and apply migrations. It was working with beta 3 and it was very handy. 

What's the purpose of commands if we need an ASP.NET application to use them ?!?

**Comment by MaximBalaganskiy** [comment] 2015-05-27 10:50
@matthieugd Until https://github.com/aspnet/EntityFramework/issues/2256 is resolved I will be putting my DbContext in stripped MVC project. Works just fine.

**Comment by matthieugd** [comment] 2015-05-27 11:45
That's what I'm going to do. Thanks @MaximBalaganskiy

**Comment by matthieugd** [comment] 2015-05-27 12:13
@MaximBalaganskiy : what did you keep in your MVC stripped project? Can you share a screenshot of the solution explorer?

**Comment by MaximBalaganskiy** [comment] 2015-05-27 12:34
Will do tomorrow - the project is at work.
I think it's something in project.json. I remember even deleting wwwroot didn't brake it.

**Comment by MaximBalaganskiy** [comment] 2015-05-27 12:48
Sorry for misleading. It's the wwwroot. Just add that folder to your class library and it should work.

**Comment by matthieugd** [comment] 2015-05-27 12:55
I added the wwroot and the  "webroot": "wwwroot" in the project.json, no luck :( I'm going to start from a empty mvc project ...

**Comment by MaximBalaganskiy** [comment] 2015-05-27 13:00
I just did the same. Deleted everything. The only difference from the class library was <DevelopmentServerPort>1147</DevelopmentServerPort> tag in the xproj file

**Comment by matthieugd** [comment] 2015-05-27 13:14
I think I found it: the Startup class must have the Configure(IApplicationBuilder app) method, it's checked in one of the EnsureXXXX methods of the Hosting class.

I added in my class in my Library project and it works.

**Comment by MaximBalaganskiy** [comment] 2015-05-27 13:18
I had this method all along and it did not work for me. Tags do work though. Like I said - black magic :)

**Comment by MaximBalaganskiy** [comment] 2015-05-27 13:22
Now it's working. This is confusing.

**Comment by bricelam** [comment] 2015-05-27 17:39
The original issue sounds like a duplicate of #2219.

> Removing the code to apply migrations from the default constructor helps a lot

Yes, the constructor code is an awful workaround that I've been hoping they'd remove for a few releases now.

> I cannot currently create migrations for referenced assemblies.

You should always invoke the commands on the assembly that you want the migrations to live in. If you want this to be a different assembly than the one containing your DbContext, scaffold the first migration in the same assembly as your DbContext then move it into the desired project. You should then be able to add additional migrations to the new project.

> What's the purpose of commands if we need an ASP.NET application to use them ?!?

We have plans to create a standalone command-line interface. (See #646) Applying migrations will also be part of deploying an ASP.NET application.

> The Startup class must have the Configure(IApplicationBuilder app) method, it's checked in one of the EnsureXXXX methods of the Hosting class.

You should [file a bug on Hosting](https://github.com/aspnet/Hosting/issues/new). The method clearly isn't used for design-time scenarios.

**Comment by rowanmiller** [comment] 2015-05-29 17:29
Closing as we think we have everything from this thread already captured in other issues (see post above from @bricelam). Feel free to reopen if there is something we missed.

**Closed** 2022-10-16 08:57 UTC
