### ISSUE TITLE
Incorrect migration for changing the key from manual ID to IDENTITY

### ISSUE THREAD

**Issue by mafshin** [dotnet/efcore#6285] opened 2016-08-10 13:44 UTC
### Steps to reproduce

Having this model

```
    public class Book
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }

    public class BookContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Data Source=.\\SQLExpress;Initial Catalog=Books;Integrated Security=True");

            base.OnConfiguring(optionsBuilder);
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Book>().Property(x => x.ID).ValueGeneratedNever();            

            base.OnModelCreating(modelBuilder);
        }

        public DbSet<Book> Books { get; set; }
    }
```

in which `Book.ID` must be set manually:
- Add-Migration Initial
- Update-Database
- Make the `ID` property to be IDENTITY by commenting `ValueGeneratedNever()` line

```
            //modelBuilder.Entity<Book>().Property(x => x.ID).ValueGeneratedNever();   
```
- Add-Migration Set_Book_ID_As_Identity
- Update-Database
### The issue

The generated migration for setting the ID to IDENTITY is as follows:

```
  public partial class Set_Book_ID_As_Identity : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "ID",
                table: "Books",
                nullable: false)
                .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "ID",
                table: "Books",
                nullable: false);
        }
    }
```

resulting in this SQL

```
ALTER TABLE [Books] ALTER COLUMN [ID] int NOT NULL;
```

which doesn't set the `ID` to auto-increment identity.
### Expected behavior

To generate a migration like this 

```
            migrationBuilder.DropColumn(
                 name: "ID",
                 table: "Books");

             migrationBuilder.AddColumn<int>(
                name: "ID",
                table: "Books",
                nullable: false)
                .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
```
### Further technical details

EF Core version: 1.0
Operating system: Windows 10 x64
Visual Studio version: VS 2015 Update 3

**Comment by bricelam** [comment] 2016-08-10 16:58
Dupe of #2100 (tracked as part of #329)

**Closed** 2022-10-16 09:53 UTC
