### ISSUE TITLE
Query: Invalid operation when filtering on a navigation property

### ISSUE THREAD

**Issue by fleed** [dotnet/efcore#2624] opened 2015-07-15 05:30 UTC
The following query

```
using (var context = new TestContext())
{
    var b = context.EntityBs.First(e => e.EntityA.PropA == "A1");
    Console.WriteLine("B: {0}", b.PropB);
}
```

works as expected on EF6, but throws the exception "System.InvalidOperationException: Sequence contains more than one element" on EF7.
Same for other operators (e.g.: Last). It seems happening whenever adding filters on a navigation property.

**Comment by rowanmiller** [comment] 2015-07-15 16:33
Duplicate of https://github.com/aspnet/EntityFramework/issues/325. Translation of navigation properties is being implemented at the moment.

**Closed** 2022-10-16 09:02 UTC
