### ISSUE TITLE
scaffold schema to different namespace

### ISSUE THREAD

**Issue by mi4t23** [dotnet/efcore#5169] opened 2016-04-25 16:56 UTC
using
dnx dbcontext scaffold ...

_One expects ef7 to scaffold db objects from different schemas to subdirectories named after db schemas they live in leaving generated context in main directory._

that is:
given tables:

```
[schema1].[table1]
[schema1].[table2]
[schema2].[table1]
[schema2].[table3]

```

and running`> dnx dbcontext scaffold -o Model -c MyDbContext`
I expect the following files to be generated

```
Model\MyDbContext
Model\schema1\table1.cs
Model\schema1\table2.cs
Model\schema2\table1.cs
Model\schema2\table1.cs
```

**Comment by rowanmiller** [comment] 2016-04-25 19:23
Duplicate of https://github.com/aspnet/EntityFramework/issues/3988, leaving open for the moment so that we can discuss priority of that issue in triage.

**Comment by rowanmiller** [comment] 2016-04-29 18:10
Closing as dupe, bumped up priority of #3988

**Closed** 2022-10-16 09:38 UTC
