### ISSUE TITLE
Entity Framework Core ObjectContext.Refresh equivalent?

### ISSUE THREAD

**Issue by viveknuna** [dotnet/efcore#11706] opened 2018-04-17 13:51 UTC
With Entity Framework 6, it was possible to refresh all the context with the method : `_myObjectContext.RefreshAsync(RefreshMode.StoreWins, GetAll())`

I would like to do the same thing with Entity Framework Core, but I can't find the best way to do that.

So, what's the best way to refresh all the context with EF Core?

**Comment by ajcvickers** [comment] 2018-04-17 16:48
@viveknuna There isn't currently an equivalent in EF Core. `context.Entry(foo).Reload()` is currently the closest thing, but it only works on a single entity.

In general, we recommend using short-lived contexts that cover a single unit-of-work. This usually makes  reloading from the store unnecessary.

**Comment by viveknuna** [comment] 2018-04-17 17:49
Could you please explain “short-lived contexts that cover a single unit-of-work”. Please provide sample code if possible.

**Comment by ajcvickers** [comment] 2018-04-17 18:24
@viveknuna That is, create a context instance, query for the relevant entities, make changes, save changes, dispose of the context. See https://www.martinfowler.com/eaaCatalog/unitOfWork.html for info on the unit-of-work-pattern.

**Comment by ajcvickers** [comment] 2018-04-18 20:58
Closing as duplicate of #2296

**Closed** 2022-10-16 12:19 UTC
