### ISSUE TITLE
EF Core generates different SQL queries in Windows and Linux environments

### ISSUE THREAD

**Issue by anilyugen** [dotnet/efcore#35052] opened 2024-11-06 08:22 UTC
We are working on an infrastructure that allows logging and analyzing SQL queries generated by EF Core. 

In this context, we noticed that EF Core generates different SQL queries in Windows and Linux environments. The main reason for this difference is that the Environment.NewLine property is different in the two environments. 

The SQL query generated on a Windows server:
DECLARE @__p_1 int = 1;\r\nDECLARE @__processId_0 bigint = CAST(1 AS bigint);\r\n\r\nSELECT TOP(@__p_1) [m].[ID], [m].[CREATE_TIME], [m].[TEXT]\r\nFROM [TALK].[MESSAGE] AS [m]\r\nWHERE [m].[PROCESS_ID] = @__processId_0

The SQL query generated on a Linux server:
DECLARE @__p_1 int = 1;\nDECLARE @__processId_0 bigint = CAST(1 AS bigint);\n\nSELECT TOP(@__p_1) [m].[ID], [m].[CREATE_TIME], [m].[TEXT]\nFROM [TALK].[MESSAGE] AS [m]\nWHERE [m].[PROCESS_ID] = @__processId_0

Is there an EF Core option and configuration that will prevent this difference and ensure standardization?

**Comment by roji** [comment] 2024-11-06 14:24
Duplicate of #30775

**Comment by roji** [comment] 2024-11-06 14:25
Am closing as a duplicate (see discussion in #30775). Out of curiosity, can you provide more context on why this difference is problematic for you?

**Closed by roji** 2024-11-06 14:25 UTC
Labels: customer-reported
