### ISSUE TITLE
Feature Request: Specifying Included Columns for an Index

### ISSUE THREAD

**Issue by eriksendc** [dotnet/efcore#3748] opened 2015-11-13 18:11 UTC
Hi there,

Thanks again for the help with specifying an index using code first.

One thing that's commonly necessary in real world situations is a 'covering index', where you have the main columns that the RDBMS uses to search (seek), but then additional data is included in the index to prevent the RDBMS from having to go to the heap table to do an extra lookup. In SQL Server this list of columns goes after the INCLUDE keyword:

CREATE INDEX IX_SomeObject_SomeDateTimeProperty ON dbo.SomeObject (SomeDateTimeProperty) INCLUDE (SomeStringProperty)

I'm sure you know all this. You guys are gurus! :) Anyways, I understand that to target different RDBMS's you don't want to throw every feature of the RDBMS into EF, but I think that the concept of covering indexes is fairly mature and supported by all major RDBMS's in use today. 

Please accept this as a long-term suggestion for EF7.

Thanks and regards,
-Brian Eriksen

PS - When someone gives this a read, if there's a good resource that calls out how you deal with DB objects that EF doesn't handle, it'd be great to be directed to that. I'm transitioning to code first from database first, and I'm also used to having a database project to manage all DDL. Thanks so much in advance!

**Comment by ErikEJ** [comment] 2015-11-13 18:26
Why not use  a SSDT project in Visual Studio to manage all your database objects?

**Comment by divega** [comment] 2015-11-13 18:53
Another possible answer to this is to use the `Sql()` method in your migrations to create the objects EF doesn't know about.

**Comment by eriksendc** [comment] 2015-11-18 15:21
Thanks for considering this and providing me with direction. 

-Brian

**Comment by gdoron** [comment] 2016-03-06 06:04
I need it too.
It can be written as an extension method to IndexBuilder.

**Comment by lcalabrese** [comment] 2016-04-26 02:56
+1 being able to write this in the fluent API and have the migration builder automatically pick up when I change something would be a really useful time-saver.

**Comment by JanEggers** [comment] 2016-06-07 07:08
+1 i need that too, 

done it with sql during migration before.

but the problem is on each major release i wipe migrations and recreate a new initial migration to clean things up. on doing so i ofcourse lost all the manual index optimization that was done with sql migration rather than attributes and generated migration

**Comment by etrafiee** [comment] 2016-10-05 06:19
+1 We are looking forward to have this feature as well

**Comment by munozjoseluis** [comment] 2016-10-14 23:31
+1 I need that too, I'll have to use the method Sql.

**Comment by adyrotaru** [comment] 2016-11-20 18:34
+1

**Comment by 4tuneengineering** [comment] 2017-02-10 13:30
+1

**Comment by jpiquot** [comment] 2017-03-12 13:03
+1

**Comment by vinniep79** [comment] 2017-04-07 15:41
+1

**Comment by narendrachava** [comment] 2017-04-14 18:59
+1

**Comment by wertzui** [comment] 2017-04-20 10:05
+1

**Comment by SergeBerwert** [comment] 2017-05-01 09:20
+1

**Comment by eriksteinebach** [comment] 2017-05-01 13:29
+1

**Comment by DragosBobolea** [comment] 2017-05-10 09:38
+1

**Comment by svallis** [comment] 2017-05-16 17:45
+1

**Comment by DR9885** [comment] 2017-05-24 21:36
+1

**Comment by smitpatel** [comment] 2017-05-24 22:04
It would be useful to add  👍 reaction to top most post instead of +1 posts on the thread.

**Comment by zordark** [comment] 2017-08-31 14:26
+1

**Comment by elmadj** [comment] 2017-09-01 18:42
+1

**Comment by FinkoAI** [comment] 2017-09-27 03:58
+1

**Comment by smitpatel** [comment] 2017-10-03 19:29
based on original note when closing this issue
> We discussed in triage and concluded that for the moment using Sql(...) to create the index is the right approach. If we see a significant number of folks wanting to be able to specify included columns in the model then we may reconsider adding it to the core model.

Re-opening to re-consider based on responses so far.

**Comment by ajcvickers** [comment] 2017-10-06 19:59
Based on feedback we have moved this to the backlog. We're not currently planning on working on it for 2.1 release, but we would consider a well written community PR.

**Comment by divega** [comment] 2017-10-12 00:57
@smitpatel @ajcvickers I actually think this issue should have remained closed and we should direct customers to https://github.com/aspnet/EntityFrameworkCore/issues/4846, which is about the same thing and has more votes. See https://github.com/aspnet/EntityFrameworkCore/issues/4846#issuecomment-199456106.

**Comment by divega** [comment] 2017-10-12 02:00
Closing as a duplicate of #4846.

**Closed** 2022-10-16 09:16 UTC
Labels: help wanted, good first issue
