### ISSUE TITLE
Type Error: Select null att Union select '6A009AF8-EB56-400F-8947-9084ABCC3FE7' att

### ISSUE THREAD

**Issue by bnuzhouwei** [dotnet/efcore#28224] opened 2022-06-14 12:57 UTC
Type of value has a mismatch with column typeCouldn't store <6A009AF8-EB56-400F-8947-9084ABCC3FE7> in att Column.  Expected type is Byte[].

It seems that the type error will be throw, if we use union clause when the a row got null value using a DataTable to load a datareader.

```sql
Select null att Union select '6A009AF8-EB56-400F-8947-9084ABCC3FE7' att
```

```csharp
public override DataTable ExecuteDataTable(DbCommand command, int start = 0, int count = int.MaxValue)
        {
            var result = new DataTable();
            using (DbConnection connection = CreateConnection())
            {
                command.Connection = connection;
                using (var reader = command.ExecuteReader())
                {                    
                    result.Load(reader);
                }
                return result;
            }
        }
```

**Comment by ajcvickers** [comment] 2022-06-14 13:50
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-06-24 15:39
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-06-24 15:39 UTC
Labels: customer-reported, area-adonet-sqlite
