### ISSUE TITLE
.Net Core 2.1.6+EF Core 2.2.0 , memory leak happened

### ISSUE THREAD

**Issue by LMing123** [dotnet/efcore#14099] opened 2018-12-06 10:19 UTC
I use a function in linq expression, then GC can't collect memory.

### Steps to reproduce

```c#
    public class GuessWhatController : ControllerBase
    {
        protected GuessWhatContext context;
         public ActionResult MatchList()
        {
            var matchs = context.Matches.Include(y => y.MatchBanner).OrderByDescending(x=>x.EndTime);
            var recommends = context.Recommends.Include(y => y.Match);
            return new JsonResult(matchs.Select(x => new
            {
                id = x.ID,
                x.Title,
                startTime = x.StartTime.ToString("yyyy-MM-dd"),
                endTime = x.EndTime.ToString("yyyy-MM-dd"),
                x.NeedVIP,
                x.MatchDetail,
                x.Price,
                banner =x.MatchBanner.URL==null?GetImageUrl(x.MatchBanner.ID): x.MatchBanner.URL,  //this line have a problem
            }));
        }
        public string GetImageUrl(int? imageID)
        {
            return $"api/GuessWhat/ImageShow/{imageID}";
        }
    }
```

It cause that memory keep increasing and CG can't collect, but i change code             
```c#
 banner =x.MatchBanner.URL==null?GetImageUrl(x.MatchBanner.ID): x.MatchBanner.URL,
```
to this 
```c#
 banner =x.MatchBanner.URL==null? $"api/GuessWhat/ImageShow/{x.MatchBanner.ID}" : x.MatchBanner.URL,  
```
the problem is resolved.

### Further technical details
EF Core version: 2.2
Database Provider: Pomelo.EntityFrameworkCore.MySql
Operating system: Windows 10 1809 17763.168
IDE: Visual Studio 2017 15.9.3

**Comment by crucialize** [comment] 2018-12-06 14:55
Hey, I've also found a memory leak bug just now!

**Comment by smitpatel** [comment] 2018-12-06 16:11
Duplicate of #13048

**Comment by smitpatel** [comment] 2018-12-06 16:12
The issue here is, in order to perform client eval requested by user, we capture the closure. But closure also contains the DbContext hence memory is leaked. Easy work-around for now would be to use static method which wouldn't capture the instance of repository

**Closed** 2022-10-16 13:43 UTC
Labels: closed-duplicate, customer-reported
