### ISSUE TITLE
Remove-Migration Initialization String validation different from Add-Migration

### ISSUE THREAD

**Issue by rombethor** [dotnet/efcore#29290] opened 2022-10-07 05:15 UTC
## Bug

When running `Remove-Migration` I get the following error, which does not appear when using the exact same connection string for `Add-Migration`:

```Format of the initialization string does not conform to specification starting at index 39.```

"index 39" corresponds to the `User ID=` portion of the connection string.

### Code:

I have an implementation of `IDesignTimeDbContextFactory` to accept the connection string as an argument:
```
internal class ZeroDesignTimeDbContextFactory : IDesignTimeDbContextFactory<ZeroDbContext>
{
    public ZeroDbContext CreateDbContext(string[] args)
    {
        if (args.Length < 0)
            throw new Exception("No connection string.  Pass connection string as: Add-Migration name -Args \"Server=...\" ");
        string connectionString = args[0];
        DbContextOptionsBuilder optionsBuilder = new DbContextOptionsBuilder();
        optionsBuilder.UseSqlServer(connectionString);
        return new ZeroDbContext(optionsBuilder.Options);
    }
}
```

The connection string I used as follows (credentials obscured):

```Add-Migration Zero_M99 -Args "Server=192.168.0.181;Database=zero_mig;User ID=sa;Password=########```
 - This works fine!

```Remove-Migration -Args "Server=192.168.0.181;Database=zero_mig;User ID=sa;Password=########"```
- This throws the below error exception:

Messing around, I have found that with `Remove-Migration`, if I change `User Id` to `User` it works.

### Stack trace

```
System.ArgumentException: Format of the initialization string does not conform to specification starting at index 39.
   at Microsoft.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue) in /_/src/Microsoft.Data.SqlClient/netcore/src/Common/src/Microsoft/Data/Common/DbConnectionOptions.Common.cs:line 232
   at Microsoft.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey) in /_/src/Microsoft.Data.SqlClient/netcore/src/Common/src/Microsoft/Data/Common/DbConnectionOptions.Common.cs:line 590
   at Microsoft.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/Common/DbConnectionOptions.cs:line 27
   at Microsoft.Data.SqlClient.SqlConnectionString..ctor(String connectionString) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionString.cs:line 248
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionFactory.cs:line 139
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions) in /_/src/Microsoft.Data.SqlClient/netcore/src/Common/src/Microsoft/Data/ProviderBase/DbConnectionFactory.cs:line 230
   at Microsoft.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionHelper.cs:line 72
   at Microsoft.Data.SqlClient.SqlConnection.set_ConnectionString(String value) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs:line 516
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs:line 116
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.RemoveMigration(String projectDir, String rootNamespace, Boolean force, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.RemoveMigration(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.RemoveMigrationImpl(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.RemoveMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Format of the initialization string does not conform to specification starting at index 39.
```

### Provider and version information

EF Core version: 6.0.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2019 16.3

**Comment by ErikEJ** [comment] 2022-10-07 06:21
Remove the extra space between User and Id.

**Comment by ajcvickers** [comment] 2022-10-07 08:08
> When running Remove-Migration I get the following error, which does not appear when using the exact same connection string for Add-Migration:

Add-Migration doesn't use the connection string. Remove-Migration uses it to see if the migration being removed already exists.

**Comment by rombethor** [comment] 2022-10-07 17:41
> > When running Remove-Migration I get the following error, which does not appear when using the exact same connection string for Add-Migration:
> 
> Add-Migration doesn't use the connection string. Remove-Migration uses it to see if the migration being removed already exists.

Ok, I see that now having tried `Add-Migration` with a useless connection string.


> Remove the extra space between User and Id.

That did not work, it gave: `Keyword not supported: 'userid'.`
What I can't get my head around is that the connection string doesn't work for `Remove Migration`, yet the exact same connection string, using `User ID=` with a space and added the same way (with `optionsBuilder.UseSqlServer(connectionstring)`), works perfectly when running the app and calling `context.Database.Migrate()`.

**Comment by ajcvickers** [comment] 2022-10-11 11:24
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-10-21 10:35
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-10-21 10:35 UTC
Labels: customer-reported
