### ISSUE TITLE
Mapping does not work properly when use include and OrderBy(a => Guid.NewGuid())

### ISSUE THREAD

**Issue by mmikirtumov** [dotnet/efcore#25088] opened 2021-06-13 20:50 UTC
Tried to get data from the database with ordered randomly. We use the logic OrderBy(a => Guid.NewGuid()) to get data ordered randomly. 

When trying to get data also using include from other class together with OrderBy(a => Guid.NewGuid()) the EF cannot map properly and shows more data than it should be.
With OrderBy(a => Guid.NewGuid()) -> returns 28 results
With OrderBy(a => a.Id) -> returns 4 results

The generated SQL script returns 28 results.

### Include your code

```C#
var query = _context.Advertisements
                .Include(a => a!.AdvertisementDates)
                .OrderBy(a => Guid.NewGuid())
                .ToListAsync()

public class Advertisement
{
        public int Id { get; set; }

        public string Title { get; set; } = null!;
       
       public List<AdvertisementDate> AdvertisementDates { get; set; } = new List<AdvertisementDate>();
}

public class AdvertisementDate
{
      public int Id { get; set; }

      public int AdvertisementId { get; set; }
      public Advertisement Advertisement { get; set; } = null!;
}
```

### Include provider and version information

EF Core version: 5.0.5
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: NET 5.0
Operating system:
IDE: Rider

**Comment by smitpatel** [comment] 2021-06-13 22:49
Are you using single query or split query?

**Comment by mmikirtumov** [comment] 2021-06-14 15:33
You can see in the example that we are using a single query

```csharp
var query = _context.Advertisements
                .Include(a => a!.AdvertisementDates)
                .OrderBy(a => Guid.NewGuid())
                .ToListAsync()
```

**Comment by smitpatel** [comment] 2021-06-14 17:51
Duplicate of #5583

As per earlier resolution, we won't fix this and not supported since doing collection include requires a stable ordering to generate results and non-deterministic ordering like this breaks it. The thread has more details.

Leaving this issue open to update our docs on eager loading to mention this.

**Closed** 2022-10-16 19:37 UTC
Labels: closed-duplicate, customer-reported
