### ISSUE TITLE
IsRowVersion is not working for SqlLite in memory

### ISSUE THREAD

**Issue by mdebeus** [dotnet/efcore#13221] opened 2018-09-05 17:04 UTC
Describe what is not working as expected.
I have a property on my model, public byte[] ConcurrencyToken which I specify as IsRowVersion using FluidApi. When I add an item to a sqlite in memory database, this property is set to null. I expect this property be to initialized such that it can be used to detect concurrency conflicts.

### Steps to reproduce
Below are the contents of the project and test project I created to recreate the problem:

```c#
Project: SqlLiteRepository
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.2" />
  </ItemGroup>

File: AccountModel.cs
namespace SqlLiteRepository
{
	public class AccountModel
	{
		public string Id { get; set; }
		public string TenantId { get; set; }
		public byte[] ConcurrencyToken { get; set; }
	}
}

File: AccountsDbContext.cs
using Microsoft.EntityFrameworkCore;
namespace SqlLiteRepository
{
    public class AccountsDbContext : DbContext
    {
        protected DbSet<AccountModel> _accounts;
        public virtual DbSet<AccountModel> Accounts
        {
            get { return _accounts; }
            set { _accounts = value; }
        }
        public AccountsDbContext() { }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AccountModel>(
                e =>
                {
                    e.HasKey(a => a.Id);
                    e.HasIndex(a => a.TenantId);
                    e.Property(a => a.ConcurrencyToken).IsRowVersion();
                });
        }
    }
}

File: AccountsRepository.cs:
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using System;
using System.Linq;
using System.Threading.Tasks;
namespace SqlLiteRepository
{
    public class AccountsRepository
    {
        private AccountsDbContext _dbContext;
        public AccountsRepository(AccountsDbContext accountsDbContext = null)
        {
            _dbContext = accountsDbContext ?? new AccountsDbContext();
        }
        public async Task<AccountModel> CreateAccountAsync(AccountModel newAccount)
        {
            EntityEntry<AccountModel> changeTracker = null;
            try
            {
                changeTracker = await _dbContext.Accounts.AddAsync(newAccount);
                await _dbContext.SaveChangesAsync();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                changeTracker = null;
            }

            return changeTracker?.Entity;
        }
        public async Task<AccountModel[]> GetAccountsAsync(string tenantId = null)
        {
            return tenantId != null ?
                await _dbContext.Accounts.Where(a => a.TenantId == tenantId).ToArrayAsync()
              : await _dbContext.Accounts.ToArrayAsync();
        }
    }
}

Project: SqlLiteRowVersionNotWorkingUnitTests
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SqlLiteRepository\SqlLiteRepository.csproj" />
  </ItemGroup>
  
File: AccountsDbContextForTest.cs:
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using SqlLiteRepository;
namespace SqlLiteRowVersionNotWorkingUnitTests
{
    public class AccountsDbContextForTest : AccountsDbContext
    {
        private bool _createdEnsured;
        private SqliteConnection _connection = new SqliteConnection("Data Source=:memory:");

        public AccountsDbContextForTest() : base() { }
        public override DbSet<AccountModel> Accounts
        {
            get
            {
                if (!_createdEnsured)
                {
                    Database.EnsureCreated();
                    _createdEnsured = true;
                }

                return _accounts;
            }
            set { _accounts = value; }
        }

        public override void Dispose()
        {
            _connection.Close();
            base.Dispose();
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            _connection.Open();
            optionsBuilder.UseSqlite(_connection);
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<AccountModel>(
                e =>
                {
                    e.HasData(
                        AccountTestData.Account1,
                        AccountTestData.Account2,
                        AccountTestData.Account3);
                });
        }
    }
}

File: AccountTestData.cs:
using System;
using SqlLiteRepository;
namespace SqlLiteRowVersionNotWorkingUnitTests
{
    public static class AccountTestData
    {
        public readonly static string TenantId = Guid.NewGuid().ToString();

        public readonly static AccountModel Account1 = new AccountModel()
        {
            Id = Guid.NewGuid().ToString(),
            TenantId = TenantId,
            ConcurrencyToken = Guid.NewGuid().ToByteArray()
        };
        public readonly static AccountModel Account2 = new AccountModel()
        {
            Id = Guid.NewGuid().ToString(),
            TenantId = TenantId,
            ConcurrencyToken = Guid.NewGuid().ToByteArray()
        };
        public readonly static AccountModel Account3 = new AccountModel()
        {
            Id = Guid.NewGuid().ToString(),
            TenantId = TenantId,
            ConcurrencyToken = Guid.NewGuid().ToByteArray()
        };
    }
}

File: UnitTests.cs:
using Xunit;
using SqlLiteRepository;
using System.Threading.Tasks;
namespace SqlLiteRowVersionNotWorkingUnitTests
{
    public class UnitTests
    {
        [Fact]
        public async Task TestCreateHasNonNullRowVersion()
        {
            var newAccount = new AccountModel()
            {
                TenantId = AccountTestData.TenantId,
            };

            var repository = new AccountsRepository(new AccountsDbContextForTest());
            var createdAccount = await repository.CreateAccountAsync(newAccount);

            Assert.NotNull(createdAccount.ConcurrencyToken);
        }
    }
}


```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by smitpatel** [comment] 2018-09-05 20:37
Duplicate of #2195

**Closed** 2022-10-16 13:29 UTC
Labels: closed-duplicate, customer-reported
