### ISSUE TITLE
Owned entities: Eager loading is NOT performed automatically on owned types when the owned property is part of an included query

### ISSUE THREAD

**Issue by amattar** [dotnet/efcore#10676] opened 2018-01-10 05:51 UTC
having a model like:

```c#
public class Employee
    {
        public EmploymentData Employment { get; set; }
        public ICollection<EmployeeSkill> Skills { get; protected internal set; }
    }

public class EmploymentData
    {
        public LocalizedField Description { get; set; }
        public DateTime Date { get; set; }
    }

public class LocalizedField
    {
        public string English { get; set; }
        public string Arabic { get; set; }
    }

public class EmployeeSkill
    {
        public Guid EmployeeId { get; set; }
        public Employee Employee { get; set; }

        public LocalizedField Description { get; set; }
        public double? YearsExperience { get; set; }
        public double? Level { get; set; }
    }
```

### Steps to reproduce
Querying employee loads the EmploymentData as expected:

```c#
var emp = context<Employee>().FirstOrDefault();
var assert = emp.Employment.Description.Arabic !=null; //True
```

generated sql:

```sql
exec sp_executesql N'SELECT TOP(1) [c].[Id], [c].[Id], [c].[Employment_Date], [c].[Id], [c].[Employment_Description_Arabic], [c].[Employment_Description_English] 
FROM [Employee] AS [c]
WHERE [c].[Id] = @__id_0
ORDER BY [c].[Id]',N'@__id_0 uniqueidentifier',@__id_0='1F659811-DA68-48B1-BEF1-08D55055C45C'
```

However, including skills along with employees does not load the owned entities of the related EmployeeSkill entities

```c#
var emp = context<Employee>().Include(e => e.Skills).FirstOrDefault();

var assert = emp.Skills.First().Description.Arabic !=null; //False
```
generated sql:

```sql
exec sp_executesql N'SELECT [c.Skills].[Id], [c.Skills].[EmployeeId], [c.Skills].[Level], [c.Skills].[YearsExperience]
FROM [EmployeeSkill] AS [c.Skills]
INNER JOIN (
    SELECT DISTINCT [t1].*
    FROM (
        SELECT TOP(1) [c1].[Id]
        FROM [Employee] AS [c1]
        LEFT JOIN [Employee] AS [c.Employment1] ON [c1].[Id] = [c.Employment1].[Id]
        LEFT JOIN [Employee] AS [c.Employment.Description1] ON [c.Employment1].[Id] = [c.Employment.Description1].[Id]
        WHERE [c1].[Id] = @__id_0
        ORDER BY [c1].[Id]
    ) AS [t1]
) AS [t2] ON [c.Skills].[EmployeeId] = [t2].[Id]
ORDER BY [t2].[Id]',N'@__id_0 uniqueidentifier',@__id_0='1F659811-DA68-48B1-BEF1-08D55055C45C'
```

Obviously, the workaround is to explicitly include the owned entities as well

```c#
var emp = context<Employee>()
.Include(e => e.Skills)
.ThenInclude(s => s.Description)
.FirstOrDefault();

var assert = emp.Skills.First().Description.Arabic !=null; //True
```
generated sql:

```sql
exec sp_executesql N'SELECT [c.Skills].[Id], [c.Skills].[EmployeeId], [c.Skills].[Level], [c.Skills].[YearsExperience], [c.Skills].[Id], [c.Skills].[Description_Arabic], [c.Skills].[Description_English]
FROM [EmployeeSkill] AS [c.Skills]
INNER JOIN (
    SELECT DISTINCT [t1].*
    FROM (
        SELECT TOP(1) [c1].[Id]
        FROM [Employee] AS [c1]
        LEFT JOIN [Employee] AS [c.Employment1] ON [c1].[Id] = [c.Employment1].[Id]
        LEFT JOIN [Employee] AS [c.Employment.Description1] ON [c.Employment1].[Id] = [c.Employment.Description1].[Id]
        WHERE [c1].[Id] = @__id_0
        ORDER BY [c1].[Id]
    ) AS [t1]
) AS [t2] ON [c.Skills].[EmployeeId] = [t2].[Id]
ORDER BY [t2].[Id]',N'@__id_0 uniqueidentifier',@__id_0='1F659811-DA68-48B1-BEF1-08D55055C45C'
```

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment] 2018-01-10 16:03
Duplicate of #9210

**Closed** 2022-10-16 12:05 UTC
