### ISSUE TITLE
AsNoTracking NRE On Navigation Properties

### ISSUE THREAD

**Issue by svernyi** [dotnet/efcore#12976] opened 2018-08-12 05:38 UTC
It appears that the position of AsNoTracking heavily matters to how EF Core handles navigation properties on entities within the same query..applying .AsNoTracking() between two .Select() statements prohibits the second .Select() from using any Navigation properties unless they are explicitly .Included()-ed. 

```
Result StackTrace:	
at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

### Steps to reproduce
I've uploaded the entire repro project with a test sqlite database [here](https://shifty.site/e5jpJ).

Short of that, here are the important bits. 
Entity Structures: `Champion <1 -- n> Abilities <1 -- 1> Descriptions`
```c#
var repro = (from c in ctx.Champion
             where c.Name == "Ashe"
             select new
                 { WithDescription = c.Abilities.FirstOrDefault(w => w.Description != null) })
            .AsNoTracking() // <-- Only works without this line
            .Select(s => new
             { s.WithDescription.Description.Text })
            .FirstOrDefault();
```

It is my understanding that Entity Framework doesn't provide fix-ups for untracked entities, however it is important to note that this is happening within the same query. Perhaps more importantly, this type of error does not happen with EF 6 -- .AsNoTracking() in the middle of queries seems to not affect it the same way that it affects EF Core.

A solution is to simply move the .AsNoTracking() to the end of the query, but I was wondering if this type of behavior was intentional.

### Further technical details
EF Core version: 2.1.1
Database Provider: EFCore.SqlServer && EfCore.Sqlite
Operating system: Win10 64bit Home
IDE: Visual Studio 2017 15.7.6

**Comment by smitpatel** [comment] 2018-08-13 18:44
Duplicate of #12337

**Closed** 2022-10-16 13:25 UTC
Labels: closed-duplicate, customer-reported
