### ISSUE TITLE
Views migrations in EF-Core migrations?

### ISSUE THREAD

**Issue by AbdulrahmanXSO25** [dotnet/efcore#34530] opened 2024-08-26 10:31 UTC
Is there a way to create/drop/alter views manually in EF-Core relational?
The only way I found was to create an empty migration, add migrationBuilder.sql, and you creation script sql as an argument, and same in drop!
ToView extension method just maps an entity to existing db view..

**Comment by ajcvickers** [comment] 2024-08-27 09:54
Duplicate of #14537

**Closed by ajcvickers** 2024-08-27 09:54 UTC
Labels: customer-reported
