### ISSUE TITLE
Include with Join stopped working on preview9

### ISSUE THREAD

**Issue by smartcodinghub** [dotnet/efcore#17664] opened 2019-09-06 12:20 UTC
Having a query like this:

```
dbset
    .Include(a => a.NavigationProperty)
    .Join(dbset1, left => left.Id, right => right.Id,
        (left, right) => new { Left = left, Right = right })
    .ToList();
```

The Property "NavigationProperty" is null. This is working on preview8.

### Steps to reproduce

Having three entities with a NavigationProperty. Join a query with Includes.

### Further technical details
EF Core version: 3.0.0-preview9.19423.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.0 preview 3.0

**Comment by smitpatel** [comment] 2019-09-06 16:49
I am not able to reproduce this.
Here is the repro code
```C#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database
                db.Add(new Blog
                {
                    BlogDetails = new BlogDetails { Value = "BlogDetails" },
                    Title = "FirstBlog"
                });

                db.Add(new Author { Name = "First" });

                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                var query = db.Blogs.Include(b => b.BlogDetails)
                    .Join(db.Authors, l => l.Id, r => r.Id, (l, r) => new { l, r })
                    .ToList();

                Console.WriteLine(query[0].l.Title);
                Console.WriteLine(query[0].l.BlogDetails.Value);
                Console.WriteLine(query[0].r.Name);
            }

            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        private static ILoggerFactory ContextLoggerFactory
            => LoggerFactory.Create(b =>
            {
                b
                .AddConsole()
                .AddFilter("", LogLevel.Debug);
            });

        // Declare DBSets
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Author> Authors { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                //.UseSqlite("filename=_modelApp.db")
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                //.UseCosmos("https://localhost:8081", @"C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==", "_ModelApp")
                //.EnableSensitiveDataLogging()
                //.UseLoggerFactory(ContextLoggerFactory)
                ;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
        }
    }

    public class Blog
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public BlogDetails BlogDetails { get; set; }
    }

    public class BlogDetails
    {
        public int Id { get; set; }
        public string Value { get; set; }
    }

    public class Author
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
```
Output
```
FirstBlog
BlogDetails
First
Program finished.
```

Please post a runnable project (or modify above repro code) to demonstrate the issue you are seeing.

**Comment by DanoThom** [comment] 2019-09-09 16:24
I can confirm this too in both dotnet and aspnetcore using the above code using the latest version 3.0.0-preview9.19423.6.

Additionally, Preview9 seems to now require explicit values or a model value generator for the int Id's in each model object or it fails.

![image](https://user-images.githubusercontent.com/4973075/64548474-9abff480-d326-11e9-9e94-59b243a07d7f.png)

**Comment by smitpatel** [comment] 2019-09-09 17:27
CosmosDb does not support join on server side. Hence EF Core cannot translate it to server.

**Comment by divega** [comment] 2019-09-09 17:44
@AndriySvyryd to find the duplicate.

**Comment by smitpatel** [comment] 2019-09-09 17:45
Duplicate of #16920

**Closed** 2022-10-16 14:40 UTC
Labels: closed-duplicate, customer-reported
