### ISSUE TITLE
Owned type change not persisting if original data is null

### ISSUE THREAD

**Issue by RafaelSalguero** [dotnet/efcore#20421] opened 2020-03-26 21:11 UTC
When updating an existing owned type where originally all it's properties are null, the update is not detected by the ChangeTracker, but if a single column is assigned to a not-null value in the database, the update is executed as normally.

### Steps to reproduce
- Create an owned type where all of its properties can be null
- INSERT a row with only null values and another with some non-null values
- Updating the owned type property for the all-nulls rows doesn't do anything
- The same code for the 2nd row with some non-null values does update

``` C#
class MyTable {
 public int IdMyTable { get; set; }
 public MyOwnedType Owned { get; set; } = new MyOwnedType()
}

[Owned]
class MyOwnedType {
  public string Prop1 { get; set; }
  public string Prop2 { get; set; }
}

var row = c.MyTable.Where(x => x.IdMyTable == 1).First();

//This is done on the database only if the original row has any non-null value in owned type related columns
row.Owned.Prop1 = "hello";

//If we inspect the ChangeTracker, 2 entities are tracked for the row with non-nulls but only 1 with the all nulls row
c.SaveChanges();
```

### Further technical details

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.5.0

**Comment by AndriySvyryd** [comment] 2020-03-26 22:25
Duplicate of https://github.com/dotnet/efcore/issues/18007
Don't initialize `MyTable.Owned` in the constructor instead do it in the getter: https://github.com/dotnet/efcore/issues/20213#issuecomment-596233307

**Closed** 2022-10-16 18:17 UTC
Labels: closed-duplicate, customer-reported
