### ISSUE TITLE
Unexpected DropIndex() call generated in migration Up() method when dropping PK

### ISSUE THREAD

**Issue by lauxjpn** [dotnet/efcore#24638] opened 2021-04-12 18:22 UTC
The original issue is being tracked by https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1348.

It contains sample code and instructions that reproduce the issue:

> The issue now is the following call in your second migrations `Up()` method:
> 
> ```cs
> migrationBuilder.DropIndex(
>     name: "IX_tasks_workers_TrekkTemplateId",
>     table: "tasks_workers");
> ```
> 
> This call shouldn't be there, but appears to be generated by the EF Core differ for some inexplicable reason.
> 
> So as a quick workaround, remove the line from the `Up()` method, and your code should run fine.
> 
> The following sample code reproduces the issue for MySQL and SQL Server:
> 
> ```cs
> using System;
> using System.Collections.Generic;
> using Microsoft.EntityFrameworkCore;
> using Microsoft.Extensions.Logging;
> 
> namespace IssueConsoleTemplate
> {
>     public class IceCream
>     {
>         public int IceCreamId { get; set; }
> 
>         public ICollection<IceCream_IceCreamParlor> IceCreamIceCreamParlors { get; set; }
>     }
> 
>     public class IceCreamParlor
>     {
>         public int IceCreamParlorId { get; set; }
> 
>         public ICollection<IceCream_IceCreamParlor> IceCreamIceCreamParlors{ get; set; }
>     }
>     
>     public class IceCream_IceCreamParlor
>     {
> #if !SECOND_MIGRATION
>         public int AccidentalId { get; set; } // <-- Remove for the second migration
> #endif
>         public int IceCreamId { get; set; }
>         public int IceCreamParlorId { get; set; }
>         
>         public IceCream IceCream { get; set; }
>         public IceCreamParlor IceCreamParlor { get; set; }
>     }
> 
>     public class Context : DbContext
>     {
>         public DbSet<IceCream> IceCreams { get; set; }
>         public DbSet<IceCreamParlor> IceCreamParlors { get; set; }
> 
>         protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
>         {
>             if (!optionsBuilder.IsConfigured)
>             {
>                 // optionsBuilder.UseMySql("server=127.0.0.1;port=3306;user=root;password=;database=Issue1348_02", new MySqlServerVersion(new Version(8, 0, 21))) 
>                 optionsBuilder.UseSqlServer(@"Data Source=.\MSSQL14;Integrated Security=SSPI;Initial Catalog=Issue1348_02") 
>                     .UseLoggerFactory(
>                         LoggerFactory.Create(
>                             configure => configure
>                                 .AddConsole()
>                                 .AddFilter(level => level >= LogLevel.Information)))
>                     .EnableSensitiveDataLogging()
>                     .EnableDetailedErrors();
>             }
>         }
> 
>         protected override void OnModelCreating(ModelBuilder modelBuilder)
>         {
>             modelBuilder.Entity<IceCream_IceCreamParlor>(
>                 entity =>
>                 {
> #if !SECOND_MIGRATION
>                     entity.HasKey(e => e.AccidentalId); // <-- Remove for second migration
> #else
>                     entity.HasKey(e => new {e.IceCreamId, e.IceCreamParlorId}); // <-- Add for second migration
> #endif              
>                     // WORKAROUND:
>                     // Explicitly defining the index will prevent EF Core from dropping it later.
>                     // entity.HasIndex(e => e.IceCreamId);
>                     
>                     // This is never needed, because this index is never being dropped by EF Core.
>                     // entity.HasIndex(e => e.IceCreamParlorId);
> 
>                     entity.HasOne(e => e.IceCream)
>                         .WithMany()
>                         .HasForeignKey(e => e.IceCreamId);
> 
>                     entity.HasOne(e => e.IceCreamParlor)
>                         .WithMany()
>                         .HasForeignKey(e => e.IceCreamParlorId);
>                 });
>         }
>     }
> 
>     internal static class Program
>     {
>         private static void Main(string[] args)
>         {
>             using var context = new Context();
> 
>             context.Database.EnsureDeleted();
>             context.Database.EnsureCreated();
>         }
>     }
> }
> ```
> 
> Run the following PowerShell command from the project directory, to generate the two migrations:
> 
> `rmdir .\Migrations\ -Recurse -ErrorAction SilentlyContinue; dotnet build '-p:DefineConstants=DEBUG NET5_0 NET'; dotnet ef migrations add Initial --verbose --no-build; dotnet build '-p:DefineConstants=DEBUG NET5_0 NET SECOND_MIGRATION'; dotnet ef migrations add ChangePrimaryKey --verbose --no-build`
> 
> In this sample code, the unexpected call, that drops the index that is unrelated to the primary key, is the following from the `..._ChangePrimaryKey.cs` file:
> 
> ```cs
> protected override void Up(MigrationBuilder migrationBuilder)
> {
>     migrationBuilder.DropPrimaryKey(
>         name: "PK_IceCream_IceCreamParlor",
>         table: "IceCream_IceCreamParlor");
> 
>     //
>     // This call should not be here:
>     //
>     migrationBuilder.DropIndex(
>         name: "IX_IceCream_IceCreamParlor_IceCreamId",
>         table: "IceCream_IceCreamParlor");
> 
>     migrationBuilder.DropColumn(
>         name: "AccidentalId",
>         table: "IceCream_IceCreamParlor");
> 
>     migrationBuilder.AddPrimaryKey(
>         name: "PK_IceCream_IceCreamParlor",
>         table: "IceCream_IceCreamParlor",
>         columns: new[] { "IceCreamId", "IceCreamParlorId" });
> }
> ```
> 
> **It tries to drop the index of the `IceCreamId` column, even though it is the `AccidentalId` column that is being relieved from being the primary key, before it is later dropped completely.**
> 
> This does not happen if the index has been explicitly defined in the model.
> 
> This issue does not seem to have any negative side effects for SQL Server when the generated SQL drops the index, but MySQL is not as forgiving and returns an error if you try to drop an index, that is being used for an existing foreign key relationship.

So the scenario is, that an m:n-table was accidentally provided with an auto incrementing ID column as the PK by the user (first migration). This is being corrected by making the two FKs of the m:n-table the PK and dropping the now unneeded old PK/ID column (second migration).

The result is, that in addition to the expected statements, an unexpected `DropIndex()` call is being generated for an index of the first of the two columns (the FK to the m-side of the m:n-relationship) that participate in the new PK.

Since the m-side of the new PK is independent of the old PK (the accidental ID column), removing the old PK should not have any side effects on the index of the m-side of the new PK.

**Comment by roji** [comment] 2021-09-08 11:08
Poaching

**Comment by roji** [comment] 2021-09-08 14:03
Here's what's going on:

In the initial migration, AccidentalId is defined as the primary key. IceCreamId is defined as the foreign key, so EF Core creates indexes for it by convention (to optimize queries); we do this for all foreign keys which **aren't** keys, since keys are already implicitly indexed in the database (they need to enforce uniqueness).

In the 2nd migration, IceCreamId becomes the key; this means the (extra!) index is no longer necessary, so EF Core generates SQL to drop it. This seems like the correct behavior, otherwise we'd end up with a primary key that has an (additional) index over it, needlessly costing perf in updates.

MySQL indeed seems to have some peculiar behavior, where a foreign key can exist without an index, but once an index is defined over it, it cannot be dropped:

```sql
CREATE TABLE Blogs (
    Id int AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE Posts (
    AccidentalId int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Id int,
    CONSTRAINT `FK_Post_Blogs_Id` FOREIGN KEY (`Id`) REFERENCES `Blogs` (`Id`) ON DELETE CASCADE
);

-- At this point we have a foreign key constraint without an (explicit index)

CREATE INDEX IX_Post_Id ON Posts (`Id`);
ALTER TABLE Posts DROP INDEX IX_Post_Id; -- Cannot drop index 'IX_Post_Id': needed in a foreign key constraint
```

This may indicate that MySQL implicitly creates an index for foreign keys, just like EF Core does; then, if an explicit index is then created by the user, maybe it replaces the implicit one, and therefore cannot be dropped... @lauxjpn this would need to be confirmed, but if so, then a possible fix would be to allow EF providers to opt out of creating the foreign key index in the first place. Otherwise, when getting a DropIndexOperation in your migrations SQL generator, you could check if the index's columns correspond to a foreign key in the model, and if so, skip the operation.

/cc @AndriySvyryd

<details>
<summary>Minimal EF repro</summary>

```c#
public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseMySql("server=127.0.0.1;port=3306;user=test;password=test;database=Test", new MySqlServerVersion(new Version(8, 0, 21)))
            // .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Comment the following out for the second migration
        // modelBuilder.Entity<Post>().HasKey(b => b.AccidentalId);

        modelBuilder.Entity<Post>().HasOne(e => e.Blog)
            .WithMany()
            .HasForeignKey(e => e.Id);
    }
}

public class Blog
{
    public int Id { get; set; }
}

public class Post
{
    public int Id { get; set; }
    public int AccidentalId { get; set; }

    public Blog Blog { get; set; }
}
```

</details>

**Comment by lauxjpn** [comment] 2021-09-08 14:49
@roji Thanks for looking into this!

> In the 2nd migration, IceCreamId becomes the key; this means the (extra!) index is no longer necessary, so EF Core generates SQL to drop it.

But why is EF Core then only dropping one of the FK indices, namely the one of the `IceCreamId` column? Shouldn't it be then also dropping the index for the `IceCreamParlorId` column, since it becomes part of the PK as well and the (extra) FK related index is now obsolete too?

**Comment by roji** [comment] 2021-09-08 14:59
This is because EF Core ordering is important (within composite keys). EF basically checks if your foreign key column(s) are wholly contained in a key on the entity, but from the very start of the key. Since the foreign key here (IceCreamParlorId) isn't at the start of the composite key, EF Core retains the extra index - makes sense?

For reference, [here is the convention](https://github.com/dotnet/efcore/blob/release/6.0/src/EFCore/Metadata/Conventions/ForeignKeyIndexConvention.cs#L57) that creates the index when a foreign key is added, and [here](https://github.com/dotnet/efcore/blob/release/6.0/src/EFCore/Metadata/Conventions/ForeignKeyIndexConvention.cs#L330) is the check for whether the foreign key is already covered by a key.

(BTW I'd be curious to learn more about the MySQL specifics around this restriction, and whether an index really is created implicitly for foreign keys! If you learn anything about it please share...)

**Comment by lauxjpn** [comment] 2021-09-08 15:54
> Since the foreign key here (IceCreamParlorId) isn't at the start of the composite key, EF Core retains the extra index - makes sense?

I am not sure yet... is it, because EF Core assumes, that the database is fine with reusing the index of the new composite PK also for the first FK column in the PK, because there is no perf penalty in using a composite index for resolving only its first column?

But in that case, shouldn't the index at least be dropped _after_ the PK has been changed, to ensure that an appropriate index for the `IceCreamId` column always exists?

> (BTW I'd be curious to learn more about the MySQL specifics around this restriction, and whether an index really is created implicitly for foreign keys! If you learn anything about it please share...)

Yeah, MySQL creates an implicit index with the same name as the FK, if no explicit index with corresponding facets already exists. If a proper index is added later, the implicit index will just be renamed to the explicit name (at least that is what I assume happens internally; in the end, only the explicit index exists).

MySQL is also eager to reuse existing indexes for other purposes, which can make it difficult to drop something, if an index has been reused for another object.

**Comment by roji** [comment] 2021-09-08 16:41
>> Since the foreign key here (IceCreamParlorId) isn't at the start of the composite key, EF Core retains the extra index - makes sense?
>
> I am not sure yet... is it, because EF Core assumes, that the database is fine with reusing the index of the new composite PK also for the first FK column in the PK, because there is no perf penalty in using a composite index for resolving only its first column?

This is pretty universal database behavior AFAIK - a composite index can be used when querying only on a subset of its columns (not necessary just one), but only if the columns being queries are ordered in the same way as the composite index, from the start. This has to do with how indexes actually work behind the scenes - composite indexes conceptually "group by" the first column, then by the second, and so on. Are you aware of different behavior on this?

> But in that case, shouldn't the index at least be dropped after the PK has been changed, to ensure that an appropriate index for the IceCreamId FK always exists?

This doesn't really have anything to do with dropping the column - just with making a non-key column a key, when that column happens to also be a foreign key (you can see my repro in https://github.com/dotnet/efcore/issues/24638#issuecomment-915268639, where AccidentalId isn't dropped at all, just no longer the key). In any case, I'm not sure why the ordering here would matter...

> Yeah, MySQL creates an implicit index with the same name as the FK, if no explicit index with corresponding facets already exists. If a proper index is added later, the implicit index will just be renamed to the explicit name (at least that is what I assume happens internally; in the end, only the explicit index exists).

OK, then that definitely explains the somewhat odd behavior. If you want, we could probably allow you to opt out of creating foreign key indexes entirely (but it would be good to hear what other team members think), that would avoid index creation which doesn't actually do anything on MySQL.

**Comment by lauxjpn** [comment] 2021-09-08 18:15
> This is pretty universal database behavior AFAIK - a composite index can be used when querying only on a subset of its columns [...]

I see, so it is the reasoning behind this behavior then.  In that case, I do understand now why only one of the indices gets dropped 😄 

> In any case, I'm not sure why the ordering here would matter...

For MySQL it does matter. Take a look at the following SQL (that suffers from the issue here), that gets generated for my sample code above. If you move the statement that drops the index below the primary key change, it will work (marked with comments near the end of the script):

<details>
<summary>Generated SQL</summary>

```sql
drop database if exists `Issue1348_03`;
create database `Issue1348_03`;
use `Issue1348_03`;

CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
    `MigrationId` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `ProductVersion` varchar(32) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
) CHARACTER SET utf8mb4;

START TRANSACTION;

ALTER DATABASE CHARACTER SET utf8mb4;

CREATE TABLE `IceCreamParlors` (
    `IceCreamParlorId` int NOT NULL AUTO_INCREMENT,
    CONSTRAINT `PK_IceCreamParlors` PRIMARY KEY (`IceCreamParlorId`)
) CHARACTER SET utf8mb4;

CREATE TABLE `IceCreams` (
    `IceCreamId` int NOT NULL AUTO_INCREMENT,
    CONSTRAINT `PK_IceCreams` PRIMARY KEY (`IceCreamId`)
) CHARACTER SET utf8mb4;

CREATE TABLE `IceCream_IceCreamParlor` (
    `AccidentalId` int NOT NULL AUTO_INCREMENT,
    `IceCreamId` int NOT NULL,
    `IceCreamParlorId` int NOT NULL,
    CONSTRAINT `PK_IceCream_IceCreamParlor` PRIMARY KEY (`AccidentalId`),
    CONSTRAINT `FK_IceCream_IceCreamParlor_IceCreamParlors_IceCreamParlorId` FOREIGN KEY (`IceCreamParlorId`) REFERENCES `IceCreamParlors` (`IceCreamParlorId`) ON DELETE CASCADE,
    CONSTRAINT `FK_IceCream_IceCreamParlor_IceCreams_IceCreamId` FOREIGN KEY (`IceCreamId`) REFERENCES `IceCreams` (`IceCreamId`) ON DELETE CASCADE
) CHARACTER SET utf8mb4;

CREATE INDEX `IX_IceCream_IceCreamParlor_IceCreamId` ON `IceCream_IceCreamParlor` (`IceCreamId`);

CREATE INDEX `IX_IceCream_IceCreamParlor_IceCreamParlorId` ON `IceCream_IceCreamParlor` (`IceCreamParlorId`);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210908154110_Initial', '5.0.5');

COMMIT;

START TRANSACTION;

DROP PROCEDURE IF EXISTS `POMELO_BEFORE_DROP_PRIMARY_KEY`;
DELIMITER //
CREATE PROCEDURE `POMELO_BEFORE_DROP_PRIMARY_KEY`(IN `SCHEMA_NAME_ARGUMENT` VARCHAR(255), IN `TABLE_NAME_ARGUMENT` VARCHAR(255))

BEGIN
        DECLARE HAS_AUTO_INCREMENT_ID TINYINT(1);
        DECLARE PRIMARY_KEY_COLUMN_NAME VARCHAR(255);
        DECLARE PRIMARY_KEY_TYPE VARCHAR(255);
        DECLARE SQL_EXP VARCHAR(1000);
        SELECT COUNT(*)
                INTO HAS_AUTO_INCREMENT_ID
                FROM `information_schema`.`COLUMNS`
                WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                        AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                        AND `Extra` = 'auto_increment'
                        AND `COLUMN_KEY` = 'PRI'
                        LIMIT 1;
        IF HAS_AUTO_INCREMENT_ID THEN
                SELECT `COLUMN_TYPE`
                        INTO PRIMARY_KEY_TYPE
                        FROM `information_schema`.`COLUMNS`
                        WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                                AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                                AND `COLUMN_KEY` = 'PRI'
                        LIMIT 1;
                SELECT `COLUMN_NAME`
                        INTO PRIMARY_KEY_COLUMN_NAME
                        FROM `information_schema`.`COLUMNS`
                        WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                                AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                                AND `COLUMN_KEY` = 'PRI'
                        LIMIT 1;
                SET SQL_EXP = CONCAT('ALTER TABLE `', (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA())), '`.`', TABLE_NAME_ARGUMENT, '` MODIFY COLUMN `', PRIMARY_KEY_COLUMN_NAME, '` ', PRIMARY_KEY_TYPE, ' NOT NULL;');
                SET @SQL_EXP = SQL_EXP;
                PREPARE SQL_EXP_EXECUTE FROM @SQL_EXP;
                EXECUTE SQL_EXP_EXECUTE;
                DEALLOCATE PREPARE SQL_EXP_EXECUTE;
        END IF;
END //
DELIMITER ;

DROP PROCEDURE IF EXISTS `POMELO_AFTER_ADD_PRIMARY_KEY`;
DELIMITER //
CREATE PROCEDURE `POMELO_AFTER_ADD_PRIMARY_KEY`(IN `SCHEMA_NAME_ARGUMENT` VARCHAR(255), IN `TABLE_NAME_ARGUMENT` VARCHAR(255), IN `COLUMN_NAME_ARGUMENT` VARCHAR(255))
BEGIN
        DECLARE HAS_AUTO_INCREMENT_ID INT(11);
        DECLARE PRIMARY_KEY_COLUMN_NAME VARCHAR(255);
        DECLARE PRIMARY_KEY_TYPE VARCHAR(255);
        DECLARE SQL_EXP VARCHAR(1000);
        SELECT COUNT(*)
                INTO HAS_AUTO_INCREMENT_ID
                FROM `information_schema`.`COLUMNS`
                WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                        AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                        AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
                        AND `COLUMN_TYPE` LIKE '%int%'
                        AND `COLUMN_KEY` = 'PRI';
        IF HAS_AUTO_INCREMENT_ID THEN
                SELECT `COLUMN_TYPE`
                        INTO PRIMARY_KEY_TYPE
                        FROM `information_schema`.`COLUMNS`
                        WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                                AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                                AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
                                AND `COLUMN_TYPE` LIKE '%int%'
                                AND `COLUMN_KEY` = 'PRI';
                SELECT `COLUMN_NAME`
                        INTO PRIMARY_KEY_COLUMN_NAME
                        FROM `information_schema`.`COLUMNS`
                        WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                                AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                                AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
                                AND `COLUMN_TYPE` LIKE '%int%'
                                AND `COLUMN_KEY` = 'PRI';
                SET SQL_EXP = CONCAT('ALTER TABLE `', (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA())), '`.`', TABLE_NAME_ARGUMENT, '` MODIFY COLUMN `', PRIMARY_KEY_COLUMN_NAME, '` ', PRIMARY_KEY_TYPE, ' NOT NULL AUTO_INCREMENT;');
                SET @SQL_EXP = SQL_EXP;
                PREPARE SQL_EXP_EXECUTE FROM @SQL_EXP;
                EXECUTE SQL_EXP_EXECUTE;
                DEALLOCATE PREPARE SQL_EXP_EXECUTE;
        END IF;
END //
DELIMITER ;

CALL POMELO_BEFORE_DROP_PRIMARY_KEY(NULL, 'IceCream_IceCreamParlor');
ALTER TABLE `IceCream_IceCreamParlor` DROP PRIMARY KEY;

ALTER TABLE `IceCream_IceCreamParlor` DROP INDEX `IX_IceCream_IceCreamParlor_IceCreamId`; /* <-- FAILS, but if moved... */

ALTER TABLE `IceCream_IceCreamParlor` DROP COLUMN `AccidentalId`;

ALTER TABLE `IceCream_IceCreamParlor` ADD CONSTRAINT `PK_IceCream_IceCreamParlor` PRIMARY KEY (`IceCreamId`, `IceCreamParlorId`);

/* <-- ... to here (or further below), it will work. */

DROP PROCEDURE `POMELO_BEFORE_DROP_PRIMARY_KEY`;

DROP PROCEDURE `POMELO_AFTER_ADD_PRIMARY_KEY`;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210908154115_ChangePrimaryKey', '5.0.5');

COMMIT;
```

</details>

If the FK index gets dropped before the new compound PK index is available, MySQL does not allow the old FK index to be dropped.
But once the new compound PK index is available, MySQL has no issue with dropping the old FK index anymore.

So it seems that it basically does exactly what you outlined as the reasoning for EF Core to drop the index in the first place, just the ordering of the statements is inaccurate.

> If you want, we could probably allow you to opt out of creating foreign key indexes entirely [...]

It's worth a thought. Or we could just customize our [MigrationsModelDiffer](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Migrations/Internal/MySqlMigrationsModelDiffer.cs) implementation a bit further (we have it highly customized anyway).

I implemented a simple statement reordering mechanism just yesterday, so that we can issue specific `UPDATE` statements immediately before `ALTER COLUMN` statements.
We might be able to use a similar approach to just move the operation that drops the index below the operation for creating the PK.

**Comment by roji** [comment] 2021-09-13 13:30
> So it seems that it basically does exactly what you outlined as the reasoning for EF Core to drop the index in the first place, just the ordering of the statements is inaccurate.

Yeah, I can see this happening:

```c#
CREATE TABLE Blogs (
    Id int AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE Posts (
    AccidentalId int NOT NULL PRIMARY KEY,
    Id int,
    CONSTRAINT `FK_Post_Blogs_Id` FOREIGN KEY (`Id`) REFERENCES `Blogs` (`Id`) ON DELETE CASCADE
);

CREATE INDEX IX_Post_Id ON Posts (`Id`);

ALTER TABLE Posts DROP PRIMARY KEY;
ALTER TABLE Posts DROP INDEX IX_Post_Id; -- Cannot drop index 'IX_Post_Id': needed in a foreign key constraint
ALTER TABLE Posts ADD CONSTRAINT `PK_Posts` PRIMARY KEY (`Id`);
ALTER TABLE Posts DROP INDEX IX_Post_Id; -- Works
```

FWIW I don't think the current migration SQL is inaccurate or wrong, but rather incompatible with a MySQL quirk (but that's mostly me just being argumentative).

This seems like it could be fixed by having EF drop indexes last for a given table, after all operations have already completed. We'll discuss this.

**Comment by lauxjpn** [comment] 2021-09-13 13:46
> This seems like it could be fixed by having EF drop indexes last for a given table, after all operations have already completed. We'll discuss this.

Thanks! In the end, for us, its really just about knowing, whether this is something that can be fixed in EF Core, or whether it is something that we need to fix/workaround specifically in Pomelo.

Anyway, we will probably use this solution (reordering the statements) over the other one (of not creating explicit indices at all), because of potentially similar side effects of the later approach to the ones we have now (e.g. the fact that MySQL will only create an implicit index if no explicit one already exists, which can then lead to issues down the road, once the explicit index should be dropped but then can't, because it is already being reused).

**Comment by roji** [comment] 2021-09-13 14:00
Sure. If you do want to stop EF from creating an explicit index for foreign keys, you can just remove ForeignKeyIndexConvention from the Pomelo provider's ConventionSet (thanks @AndriySvyryd).

**Comment by roji** [comment] 2021-09-23 14:45
@lauxjpn we discussed this in triage, and the general consensus is that the EF migration operation ordering is correct, and that the MySQL provider should work around this MySQL-specific limitation. One way is to do it in the differ (which you've already customized), although a better way would be to do this in the migration SQL generator, i.e. detect the multiple operations occurring on the same table and ordering properly there. This is how table rebuilds were implemented in the Sqlite provider - that can serve as inspiration.

**Comment by lauxjpn** [comment] 2021-09-23 18:02
@roji No problem, I wasn't really expecting a change (because there could be issues with changing the index drop/create order in general, when indices with the same name get dropped and created).

We will implement it in Pomelo (we are likely to do it in the `MigrationsModelDiffer`, because it is customized already, it is where the sorting happens anyway, and it preserves the user's agency when it comes to customizing the order of migration operation execution in their `Up()`/`Down()` methods).

**Comment by roji** [comment] 2021-09-23 18:58
Sounds good, thanks @lauxjpn!

**Closed** 2022-10-16 19:31 UTC
Labels: closed-external, customer-reported
