### ISSUE TITLE
Insert data into a principal table with dependents

### ISSUE THREAD

**Issue by bamdad-b** [dotnet/efcore#25330] opened 2021-07-25 13:14 UTC
I can not insert data into a principal table with dependents by using dbContext.SaveChanges() once.
There are these two entities:

```C#
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public CompanyVehicle CompanyVehicle { get; set; }
    }
```
and

```C#
    public class CompanyVehicle
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Employee Employee { get; set; }
    }
```
Using `Entity Framework Core 5.0.8` on `SQL Server 2019`, the configuration for CompanyVehicle (The dependent) is:

```C#
    entityBuilder.HasOne(t => t.Employee)
        .WithOne(t => t.CompanyVehicle)
        .HasForeignKey<Employee>(t => t.Id)
        .IsRequired();
```

And we'll try to insert something:

```C#
    public void Create(Employee employee)
    {
        employee.CompanyVehicle = new CompanyVehicle();
        dbContext.Add<Employee>(employee);
        dbContext.SaveChanges();
    }
```

The above code used to work fine in `EF6`. Two new records in both Employee and CompanyVehicle tables were created with the same `Id`. After migrating to `EF Core 5.0.8`, dbContext.SaveChanges() throws an exception:

> System.InvalidOperationException: 'The value of 'Employee.Id' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.'

The database is designed using EF6 Code First in earlier versions of the project. After the migration, all the Get methods in repositories work fine and I'm able to insert into non-principal tables too.
As the exception suggest, It seems that the `CompanyVehicle` reference to the `Employee` is unknown (null), but even after setting it manually it won't work.

```C#
    public void Create(Employee employee)
    {
        employee.CompanyVehicle = new CompanyVehicle();
        employee.CompanyVehicle.Employee = employee;
        dbContext.Add<Employee>(employee);
        dbContext.SaveChanges();
    }
```

EF Core version: 5.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: Windows 10 Enterprise N
IDE:  Visual Studio 2019 16.10 and Visual Studio 2022 preview

**Comment by ajcvickers** [comment] 2021-07-26 16:20
@bamdad-b I am not able to reproduce this--see my code below. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
public class Employee
{
    public int Id { get; set; }
    public string Name { get; set; }
    public CompanyVehicle CompanyVehicle { get; set; }
}

public class CompanyVehicle
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Employee Employee { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .LogTo(Console.WriteLine, LogLevel.Information)
            .UseSqlServer(Your.ConnectionString)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CompanyVehicle>()
            .HasOne(t => t.Employee)
            .WithOne(t => t.CompanyVehicle)
            .HasForeignKey<Employee>(t => t.Id)
            .IsRequired();    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var employee = new Employee();
            employee.CompanyVehicle = new CompanyVehicle();
            context.Add<Employee>(employee);
            context.SaveChanges();
        }
    }
}
```

**Comment by ajcvickers** [comment] 2021-08-03 15:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:40 UTC
Labels: closed-could-not-reproduce, customer-reported
