### ISSUE TITLE
Translation of computed properties into SQL?

### ISSUE THREAD

**Issue by vflame** [dotnet/efcore#18527] opened 2019-10-23 02:19 UTC
``` C#
//Models:


public class PreferenceA
{
	public bool IsEnabled {get;set;}
}

public class PreferenceB
{
	public bool List<string> Preferences {get;set;}
}

public class UserPersonalization
{
	public PreferenceA PreferenceA{ get; set;}
	public PreferenceB PreferenceB{ get; set;}
	public bool IsPersonalized => PreferenceA.Enabled || PreferenceB.Preferences.Any();
}

public class User
{
	public UserPersonalization UserPersonalization {get;set;}
}


//Context Configuration:
builder.OwnsOne(p=>p.UserPersonalization,
personalization => 
{
	personalization.OwnsOne(p=>p.PreferenceA);
	personalization.OwnsOne(p=>p.PreferenceB, preferenceB => 
	{
		preferenceB.Property(x => x.Preferences).HasConversion(x=>x.SerializeToJson(), x=> x.DeserializeFromJson<List<string>>());
	}
});

// program:

//throws null reference exception on IsPersonalized due to PreferenceA/B not being materialized
context.Users.Where(p => p.UserPersonalization.IsPersonalized == true); 


//works but materializes everything into memory
context.Users.ToList().Where(p => p.UserPersonalization.IsPersonalized == true); 

```

Is there a mechanism for translating/mapping the above into SQL by EF Core?

### Further technical details

EF Core version:
Database provider: NpgSql
Target framework: (e.g. .NET Core 2.1)
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by smitpatel** [comment] 2019-10-23 02:25
Duplicate of #18155

**Comment by smitpatel** [comment] 2019-10-23 02:27
With EF Core 3.0 client side evaluation is not supported in Where predicate. So above query will throw exception that it cannot translate. See [documentation](https://docs.microsoft.com/en-us/ef/core/querying/client-eval) for more information.

Before 3.0, EF core processed client side Where predicate, in which case this may be bug, but we don't plan to fix it in 2.x release.

**Closed** 2022-10-16 14:51 UTC
Labels: closed-out-of-scope, customer-reported
