### ISSUE TITLE
SaveChanges failed when insert new record while trigger query "Select SCOPE_IDENTITY()"

### ISSUE THREAD

**Issue by oneandy** [dotnet/efcore#21709] opened 2020-07-21 05:20 UTC
Attached runnable project to reproduce the issue:
[EFCoreIssueWithTrigger.zip](https://github.com/dotnet/efcore/files/4957202/EFCoreIssueWithTrigger.zip)
----------------------------------------------------------------------------

My Insert failed when adding a new item and save changes under following condition:
1. The table has an Identity integer column,
2. The table has trigger on inserts, where it calls "Select SCOPE_IDENTITY()" inside the trigger

The failed message:
Message: 
    Microsoft.EntityFrameworkCore.DbUpdateException : An error occurred while updating the entries. See the inner exception for details.
      ----> System.InvalidCastException : Specified cast is not valid.
  Stack Trace: 
    AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader) line 87
    ReaderModificationCommandBatch.Execute(IRelationalConnection connection) line 251
    BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection) line 91
    RelationalDatabase.SaveChanges(IList`1 entries) line 61
    StateManager.SaveChanges(IList`1 entriesToSave) line 1063
    StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess) line 1126
    SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) line 55
    StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess) line 1090
    DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess) line 481
    DbContext.SaveChanges() line 428

**Comment by ajcvickers** [comment] 2020-07-21 18:30
@oneandy Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by oneandy** [comment] 2020-07-22 00:54
> @oneandy Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

[EFCoreIssueWithTrigger.zip](https://github.com/dotnet/efcore/files/4957206/EFCoreIssueWithTrigger.zip)

**Comment by ajcvickers** [comment] 2020-07-24 21:05
Duplicate of #12064. Stored proc is:

```sql
CREATE TRIGGER [TR_Posts_Trouble_Test]
ON [Posts]
    INSTEAD OF INSERT
AS 
BEGIN

    INSERT INTO [Posts] (Title, Content, BlogId)
    SELECT Title, Content, BlogId
    FROM Inserted

	Select SCOPE_IDENTITY() AS BlogId
END
```

**Closed** 2022-10-16 18:34 UTC
Labels: closed-duplicate, customer-reported
