### ISSUE TITLE
Adding entitites with navigation properties

### ISSUE THREAD

**Issue by dannythomas13** [dotnet/efcore#9569] opened 2017-08-25 08:31 UTC
Prior to upgrading to v2 I could do the following:

var project = Mapper.Map<Project>(vm);
this.context.Projects.Add(project);
this.context.SaveChanges();

Here is a portion of the Project class:

...
        public DateTime DateStarted { get; set; } = DateTime.Now;

        public Windfarm Windfarm { get; set; }

        public int WindfarmId { get; set; }
...

Now in the vm I have set the WindfarmId but Windfarm is set to null within the post, unnecessary to go and load it when i have the id, and with v1 this project would be correctly added.

With v2 after executing this.context.Projects.Add(project); the WindfarmId is set to -2147482647 and I'm then given null errors on the parent element.

**Comment by dannythomas13** [comment] 2017-08-25 09:30
This one may unfortunately be difficult to reproduce as there are other areas of the system where i perform similar operations but they are correctly added

**Comment by ajcvickers** [comment] 2017-08-25 17:25
@dannythomas13 I don't think we're going to be able to reproduce this without more information. Can you try to create a self-contained repro so that we can run it and debug what is happening?

**Comment by ajcvickers** [comment] 2017-09-01 18:07
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:18 UTC
Labels: closed-could-not-reproduce
