### ISSUE TITLE
Scaffold and SQL 2016 Temporal Tables properties SysTime

### ISSUE THREAD

**Issue by MBapaume** [dotnet/efcore#10845] opened 2018-02-01 14:01 UTC
Hi,

When our database context is generated with a scaffold command the properties "SysStartTime" and "SysEndTime" are created for some enties and they are missing for other tables. 
So we have to check entities one by one.
We cannot figure out the reason of this behaviour. 

Thanks

### SQL Tables
```SQL
The structure of these 2 tables seems to be identical.
Table  1 :
CREATE TABLE [dbo].[Building](
	[Id] [uniqueidentifier] NOT NULL,
	...
	[ModifiedByUserId] [uniqueidentifier] NULL,
	[SysStartTime] [datetime2](0) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEndTime] [datetime2](0) GENERATED ALWAYS AS ROW END NOT NULL,
 CONSTRAINT [PK_Building] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime])
) ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON ( HISTORY_TABLE = [History].[building_History] )
)
GO

ALTER TABLE [dbo].[Building] ADD  CONSTRAINT [DF_Building_Id]  DEFAULT (newid()) FOR [Id]
GO

Table 2 :
CREATE TABLE [dbo].[Buyer](
	[Id] [uniqueidentifier] NOT NULL,
	[ProspectId] [uniqueidentifier] NOT NULL,
	...
	[ModifiedByUserId] [uniqueidentifier] NULL,
	[SysStartTime] [datetime2](0) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEndTime] [datetime2](0) GENERATED ALWAYS AS ROW END NOT NULL,
	[Job] [nvarchar](100) NULL,
	[D_CivilityId] [uniqueidentifier] NULL,
 CONSTRAINT [PK_Buyer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime])
) ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON ( HISTORY_TABLE = [History].[Buyer_History] )
)
GO

ALTER TABLE [dbo].[Buyer] ADD  CONSTRAINT [DF_Buyer_Id]  DEFAULT (newid()) FOR [Id]
GO
```
### C# Context
```C#
Table 1 : Properties are missing
modelBuilder.Entity<Building>(entity =>
            {
                entity.HasIndex(e => e.DealItemId)
                    .HasName("FK_BUILDING_REFERENCE_DEALITEM");

                entity.HasIndex(e => e.ModifiedByUserId)
                    .HasName("FK_BUILDING_REFERENCE_USER");

                entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

                entity.Property(e => e.Name).HasMaxLength(50);

                entity.HasOne(d => d.DealItem)
                    .WithMany(p => p.Building)
                    .HasForeignKey(d => d.DealItemId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_BUILDING_REFERENCE_DEALITEM");

                entity.HasOne(d => d.ModifiedByUser)
                    .WithMany(p => p.Building)
                    .HasForeignKey(d => d.ModifiedByUserId)
                    .HasConstraintName("FK_BUILDING_REFERENCE_USER");
            });

Table 2 : Properties are present
  modelBuilder.Entity<Buyer>(entity =>
            {
                entity.HasIndex(e => e.CountryId)
                    .HasName("FK_BUYER_REFERENCE_COUNTRY");

                entity.HasIndex(e => e.FrenchCityId)
                    .HasName("FK_BUYER_REFERENCE_CITY");

                entity.HasIndex(e => e.ModifiedByUserId)
                    .HasName("FK_BUYER_REFERENCE_USERM");

                entity.HasIndex(e => e.ProspectId)
                    .HasName("FK_BUYER_REFERENCE_PROSPECT");

                entity.HasIndex(e => e.SocioProfessionalCategoryId)
                    .HasName("FK_BUYER_REFERENCE_SOCPROCAT");

                entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

             ...

                entity.Property(e => e.SysEndTime)
                    .HasColumnType("datetime2(0)")
                    .HasDefaultValueSql("(CONVERT([datetime2](0),'9999-12-31 23:59:59'))");

                entity.Property(e => e.SysStartTime)
                    .HasColumnType("datetime2(0)")
                    .HasDefaultValueSql("(dateadd(second,(-1),sysutcdatetime()))");

                entity.HasOne(d => d.Country)
                    .WithMany(p => p.Buyer)
                    .HasForeignKey(d => d.CountryId)
                    .HasConstraintName("FK_BUYER_REFERENCE_COUNTRY");

                entity.HasOne(d => d.DCivility)
                    .WithMany(p => p.Buyer)
                    .HasForeignKey(d => d.DCivilityId)
                    .HasConstraintName("FK_BUYER_REFERENCE_CIVILITY");

                entity.HasOne(d => d.FrenchCity)
                    .WithMany(p => p.Buyer)
                    .HasForeignKey(d => d.FrenchCityId)
                    .HasConstraintName("FK_BUYER_REFERENCE_CITY");

                entity.HasOne(d => d.ModifiedByUser)
                    .WithMany(p => p.Buyer)
                    .HasForeignKey(d => d.ModifiedByUserId)
                    .HasConstraintName("FK_BUYER_REFERENCE_USERM");

                entity.HasOne(d => d.Prospect)
                    .WithMany(p => p.Buyer)
                    .HasForeignKey(d => d.ProspectId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_BUYER_REFERENCE_PROSPECT");

                entity.HasOne(d => d.SocioProfessionalCategory)
                    .WithMany(p => p.Buyer)
                    .HasForeignKey(d => d.SocioProfessionalCategoryId)
                    .HasConstraintName("FK_BUYER_REFERENCE_SOCPROCAT");
            });
```
### Further technical details
EF Core version: 2.0.0
Database Provider: SQL Server 2016
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by smitpatel** [comment] 2018-02-01 21:51
@MBapaume - I am not able to reproduce it with above code snippets. I created tables using the SQL script provided and ran scaffolding but it correctly scaffolded those columns for both the tables.

**Comment by ajcvickers** [comment] 2018-02-03 00:48
@MBapaume As @smitpatel said, we haven't been able to reproduce this on our side. There may be something different about the table metadata in your database that is somehow missing in what is posted above. If you can figure out someway that we can reproduce this, then we may be able to investigate further, but without a way to reproduce this issue there is not much more we can do.

**Comment by ajcvickers** [comment] 2018-02-12 18:06
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:07 UTC
Labels: closed-could-not-reproduce
