### ISSUE TITLE
How to disable EF Core Migrations in Blazor app

### ISSUE THREAD

**Issue by AndyWDev** [dotnet/efcore#23886] opened 2021-01-14 21:14 UTC
Hi Folks,
 I am just working with EF Core in a Blazor Server application  (VS2019 16.8.3/Net 5/SQL Server)

 When trying to publish the application and setting up a local publish profile I had an error that the Microsoft.EFCore.Design package was not installed and EF Migrations could not be performed.  I fixed the error (the package needs to be installed at the project level) and can now see there is a field in the publish window the option of publishing a Migration.

When I read up about migrations - the documentation appears to suggest that this would then make changes to the database schema(s) which I do not want at all to occur.

Does anyone know how I can turn off the migrations for the **entire app** - perhaps an appsettings parameter - if not, how do I tell it there is nothing to do?

Regards.

Remember:

**Comment by ajcvickers** [comment] 2021-01-15 17:02
Duplicate of #23885

**Closed** 2022-10-16 19:18 UTC
Labels: customer-reported
