### ISSUE TITLE
Where is IDbSet<TEntity>?

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/efcore#1282] opened 2014-12-12 19:07 UTC
Previous versions of DbSet<TEntity> implemented the interface IDbSet<TEntity> (see http://msdn.microsoft.com/en-us/library/gg696460(v=vs.113).aspx).  This simplified testing of DbContext derived types.  Is there a different pattern with EF7 or will this be added back?

**Comment by twsouthwick** [comment] 2015-02-05 17:42
Any thoughts on this?  I looked in the code and saw that DbSet<TEntity> is an abstract class with pure virtual methods; however, this is still not as good as an interface when it comes to mocking for testing purposes.

**Comment by rowanmiller** [comment] 2015-02-05 19:04
@twsouthwick - Do you have specific scenarios where the interface is beneficial over the base type? The issue with interfaces is we either exclude new members or break folks who implement the interface. The base class is also slightly better for folks writing their own test doubles (rather than using a mocking framework) since you only need to implement the methods you actually use.

**Comment by rowanmiller** [comment] 2015-02-13 21:54
Closing as we have been using the base type approach in EF6.x for a few releases now and have not heard any feedback on real scenarios where this doesn't work as well.

Feel free to reopen if you want to discuss further :smile:

**Comment by pgorbas** [comment] 2017-05-24 21:08
I am looking fo IDbSet as well .  I need to mock a db context and since db contexts are basicly a group of getters and setters on DbSets, I need to be able to mock the DbSets as well.

Trying to do this under .net Core 1.0

There isn't even a public constructor.

No idea how to mock now.

**Comment by twsouthwick** [comment] 2017-05-25 18:40
@pgorbas Since `DbSet<>` is now an abstract base class, you can just use that to mock. You can either derive from it and implement the methods you care about, or use a mocking framework, which will do the same thing, but behind the scenes.

**Comment by BrianARice** [comment] 2018-07-05 12:59
I inherited a project that had IDbSet<ApplicationUser> Users... and was able to query the AspNetUsers table (not sure why this worked) with this to, for example, sort all users by UserName. This ability was kind of nice... not sure how to reproduce this behavior in Core.

**Comment by ajcvickers** [comment] 2018-07-05 18:06
@BrianARice Should be able to use the DbSet class instead.

**Comment by sikemullivan** [comment] 2018-07-25 06:03
I liked IDbSet, but I don't really need it anymore. I started coaching the use of query handlers. Makes mocking super easy.

**Comment by weitzhandler** [comment] 2020-07-20 03:40
Not only am I looking for `IDbSet<T>`, but I wish we could directly expose `IDbSet<TEntity>` properties from our `DbContext`, so we could easily mock it with a framework like Moq.

**Comment by duaneking** [comment] 2021-03-19 19:28
I just inherited some code where the removal of this interface means production code has to change because its not just being used for testing or mocking; What is the accepted solution for this?

**Comment by ajcvickers** [comment] 2021-03-19 21:41
@duaneking `IDbSet` has not been removed; it never existed in EF Core. Presumably you have been using it in EF6 or some other version of the old codebase. Can you provide some more details in how it is being used so we can suggest options for EF Core?

**Comment by duaneking** [comment] 2021-03-19 23:28
I'm looking to use etc core in a more generic way by leveraging type constraints and generics to build out more generic repositories.

**Comment by roji** [comment] 2021-03-20 06:56
@duaneking can you provide a code sample of what you're trying to do? We may be able to suggest alternatives.

**Comment by duaneking** [comment] 2021-03-29 23:21
I'm using metaprogramming to reflect out full crud API's in dotnetcore 3.1 for a given type.

**Comment by roji** [comment] 2021-03-30 14:31
@duaneking what we need to see is a code sample, not a general description of what you're trying to do.

**Comment by Seabizkit** [comment] 2021-07-05 09:48
@roji It seems like really odd that DBSet does not have an interface.. which lives outside of EFCore and EF6
it make it impossible to implement a generic repo.

look at any Repo example it will have DbContext.... which is not Generic, aka its in different namespace depending on EF6 or core.... Now, you could make IDbContext interface, but the main thing the repo does is basically DbSet..... As Dbset is From the Implementation of EF6 or EFcore, you are now suck. Aka you have to create another Repo one for each, now assuming you has it as BaseRepo, which is 99% of the time then anytime you did something like UserRepo:BaseRepo<User>, you know have to have two one for EF6 and for EFCore... aka you are duplicating your repos. This is Probably the biggest reason ppl dnt fine the migration path easy... as the is no gd reason that this should be supported.

This effectively mean you have to have Duplicated code. They can Share the same Interfaces but they cant share the same repos. 

https://stackoverflow.com/questions/48011706/net-core-generic-repository-pattern-how-to-inject-dbcontext-without-knowing-its/48012184?noredirect=1#comment120582728_48012184
```
public class GenericRepository<TEntity, TKey> : IRepository<TEntity, TKey>
    where TEntity : class, IEntity<TKey> {
    private readonly IDbContext dbContext;

    public GenericRepository(IAppDbContext dbContext) {
        this.dbContext = dbContext;
    }

    //...code removed for brevity

}
```
anything in the above class is useless unless you use **DbSet**, **DbSet** has no abstraction(interface) so you are now tided to EF6 or EFCore, its like the fundamentals of making it Generic are lost.

literally the one Interface needed... and you could have a GenericRepository between EF6 and EFCore

Making the transition between the too, so much easier!

**Comment by ajcvickers** [comment] 2021-07-11 14:24
@twsouthwick I would advise strongly against creating a common abstraction on top of EF Core and EF6. The differences between the two would make the abstraction extremely leaky.

**Comment by duaneking** [comment] 2021-07-12 22:30
@ajcvickers This can already be done using generic repositories. Its an accepted and standard pattern in C#/.Net to reference the set of the entity context directly via generics and then using metaprogramming to leverage generics to create generic repositories thanks to the interfaces provided.

`
        IQueryable<TEntity> query = context.Set<TEntityModel>();
`       

After this the query object allows all linq/etc queries.

**Comment by roji** [comment] 2021-07-13 10:18
@duaneking `IQueryable<T>` can indeed be used to abstract over DbSet in EF Core and EF6 (and possibly other LINQ providers), but which queries can actually be executed will vary greatly. This is what makes the abstraction very leaky - it's a fundamental result of how LINQ and queries work.

**Comment by duaneking** [comment] 2021-07-13 16:21
@roji Yet this is a core pattern I see repeated in many different projects.

And to be fair when its done right, its remarkably easy and functional to use.

**Comment by roji** [comment] 2021-07-13 16:33
@duaneking sure, if the range of queries being executed is very simple and restricted, it would work - but this will break down the moment more sophisticated queries are attempted. As a trivial example, Include is used in EF Core to include related entities, but that operator wouldn't be recognized by EF6 (or other providers).

**Comment by duaneking** [comment] 2021-07-13 18:48
@roji  And yet with a few lines of code you can get metaprogrammed full CRUD via REST of a models record, by simply inheriting a base controller class that leverages a repository interface.  Thankfully, not everybody needs "Include".

**Comment by roji** [comment] 2021-07-13 18:54
@duaneking if it works for your specific needs, then by all means... Though Include seems like quite a basic thing to me, and in general I'm not convinced by the need to abstract over multiple LINQ providers (except maybe for temporary transitional purposes, e.g. EF6->EF Core, though even there I wouldn't do it). But if it works, it works.

**Comment by Seabizkit** [comment] 2021-07-14 23:14
@roji and @ajcvickers  thanks for the response.

initially I couldn't figure out what was needed to be able to reused a lot of my "Repo" layers which had Interfaces over them for base level items.

So I basically about a year ago I ended up rebuilding it completely !,

after count less hours of looking at it and some refactoring and seeing the common parts separated but repeated it become easier to see where the incompatibles are. high sight is 20/20

Some of the issue is that most examples on the internet and probably good practice is to have some sort of 

```c#
IBaseEntity<Entity>
{
      int Id { get; set; }
      ..ect 
}
```

what seems like a gd idea, would be something like
 `IBaseRepo<TEntity>` and `abstract class BaseRepo<TEntity>`

```c#
 public abstract class BaseRepo<TEntity>  where TEntity : class, IBaseEntity 
    {
        protected BaseRepo(DbContext context)
        {
            _context = context;
        }
        protected DbContext _context;

        private DbSet<TEntity> _entities;

        public IQueryable<TEntity> Table => Entities;
        public  IQueryable<TEntity> TableNoTracking => Entities.AsNoTracking();
        protected DbSet<TEntity> Entities
        {
            get
            {
                if (_entities == null)
                    _entities = _context.Set<TEntity>();

                return _entities;
            }
        }
      ...ect
   }
```

So from the above you are see that **DbContext** and **DbSet** is non "interfaceable " 
I dont know enough about **DbSet** 

efCore
```
  public abstract class DbSet<TEntity> : IQueryable<TEntity>, IEnumerable<TEntity>, IEnumerable, IQueryable, IAsyncEnumerable<TEntity>, IInfrastructure<IServiceProvider>, IListSource where TEntity : class
    {
        protected DbSet();      
        public virtual LocalView<TEntity> Local { get; }       
        public virtual IEntityType EntityType { get; }
        public virtual EntityEntry<TEntity> Add([NotNullAttribute] TEntity entity);     
        public virtual ValueTask<EntityEntry<TEntity>> AddAsync([NotNullAttribute] TEntity entity, CancellationToken cancellationToken = default);
        public virtual void AddRange([NotNullAttribute] IEnumerable<TEntity> entities);
        public virtual void AddRange([NotNullAttribute] params TEntity[] entities);
        public virtual Task AddRangeAsync([NotNullAttribute] IEnumerable<TEntity> entities, CancellationToken cancellationToken = default);
        public virtual Task AddRangeAsync([NotNullAttribute] params TEntity[] entities);
        public virtual IAsyncEnumerable<TEntity> AsAsyncEnumerable();
        public virtual IQueryable<TEntity> AsQueryable();
        public virtual EntityEntry<TEntity> Attach([NotNullAttribute] TEntity entity);
        public virtual void AttachRange([NotNullAttribute] IEnumerable<TEntity> entities);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj);
        public virtual TEntity Find([CanBeNullAttribute] params object[] keyValues);
        public virtual ValueTask<TEntity> FindAsync([CanBeNullAttribute] object[] keyValues, CancellationToken cancellationToken);
        public virtual ValueTask<TEntity> FindAsync([CanBeNullAttribute] params object[] keyValues);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode();
        public virtual EntityEntry<TEntity> Remove([NotNullAttribute] TEntity entity);
        public virtual void RemoveRange([NotNullAttribute] params TEntity[] entities);
        public virtual void RemoveRange([NotNullAttribute] IEnumerable<TEntity> entities);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override string ToString();       
        public virtual EntityEntry<TEntity> Update([NotNullAttribute] TEntity entity);
        public virtual void UpdateRange([NotNullAttribute] params TEntity[] entities);
        public virtual void UpdateRange([NotNullAttribute] IEnumerable<TEntity> entities);
    }
```
ef 6
```
    public class DbSet<TEntity> : DbQuery<TEntity>, IDbSet<TEntity>, IQueryable<TEntity>, IEnumerable<TEntity>, IEnumerable, IQueryable, IInternalSetAdapter where TEntity : class
    {
     
        protected DbSet();
        public virtual ObservableCollection<TEntity> Local { get; }
        public virtual TEntity Add(TEntity entity);
        public virtual IEnumerable<TEntity> AddRange(IEnumerable<TEntity> entities);
        public virtual TEntity Attach(TEntity entity);
        public virtual TEntity Create();
        public virtual TDerivedEntity Create<TDerivedEntity>() where TDerivedEntity : class, TEntity;
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj);
        public virtual TEntity Find(params object[] keyValues);
        public virtual Task<TEntity> FindAsync(CancellationToken cancellationToken, params object[] keyValues);
        public virtual Task<TEntity> FindAsync(params object[] keyValues);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode();
        [EditorBrowsable(EditorBrowsableState.Never)]
        public Type GetType();
        public virtual TEntity Remove(TEntity entity);
        public virtual IEnumerable<TEntity> RemoveRange(IEnumerable<TEntity> entities);
        public virtual DbSqlQuery<TEntity> SqlQuery(string sql, params object[] parameters);
        public static implicit operator DbSet(DbSet<TEntity> entry);
    }
```


repo usage example:
```
  public class OrganisationRepo : BaseRepo<Organisation>, IOrganisationRepo
    {
        public OrganisationRepo(DbContext context) : base(context)
        {
        }
   public Task<List<Organisation>> GetAllByUserAsync(int userId)
        {
            var query = (from ur in Set<UserOrganisation>()
                         join org in Set<Organisation>() on ur.OrganisationId equals org.Id
                         where ur.UserId == userId
                          && ur.IsOwner
                         select org)
                      .ToListAsync();
            return query;
        }
}
```

if this could be abstracted into an interface `public virtual DbSet<TEntity> Set<TEntity>() where TEntity : class;`

where i can Get `IDbSet` which is common to both Ef6 and Efcore, which exposes the object as what ever the above would call internally as a hidden implementation. 

So the net goal would be so the BaseRepo could be used for both ef6 and efcore, 
I am probably way over simplify it, 
but would be great if they share a common `Set` pattern, i.e. Both Ef6 and Efcore both have Set entity which then allows you to write 'IQueryable'** (querys)  against them, they just don't share a common interface.

System.Data.Entity.DbContext and Microsoft.EntityFrameworkCore, both have 
`public virtual DbSet<TEntity> Set<TEntity>() where TEntity : class;` 

just feels like its so close to being able to reuse a BaseRepo Between Ef6 and EfCore if via a shared interface of sorts.

the above repo could be made more generic with passing a Dbcontext with has an interface IDbcontext, which then could be changed internally, so 

```
public abstract class BaseRepo<TEntity>  where TEntity : class, IBaseEntity 
    {
        protected BaseRepo(IDbContext context)
        {
            _context = context;
        }
        protected IDbContext _context;

        private DbSet<TEntity> _entities;

        public IQueryable<TEntity> Table => Entities;
        public  IQueryable<TEntity> TableNoTracking => Entities.AsNoTracking();
        protected DbSet<TEntity> Entities
        {
            get
            {
                if (_entities == null)
                    _entities = _context.Set<TEntity>(); .. <--- i cant set this as I cant implement a version which has an interface

                return _entities;
            }
        }
      ...ect
   }
```
but we cant put the method signature into the interface for the Set.... as its not against a interface which is common.

probably not possible but this would be amazing!

**Comment by duaneking** [comment] 2021-07-14 23:38
@Seabizkit Like this?

```
public interface IReadOnlyRepository
{
 // ... 
}
```

```
public class EntityFrameworkReadOnlyRepository<TContext> : IReadOnlyRepository  where TContext : DbContext
{
    protected readonly TContext _context;

    public EntityFrameworkReadOnlyRepository(TContext context)
    {
        _context = context;
    }
    
    public  IQueryable<TEntityModel> GetQueryable<TEntityModel>(
        Expression<Func<TEntityModel, bool>> filter = null,
        Func<IQueryable<TEntityModel>, IOrderedQueryable<TEntityModel>> orderBy = null,
        int? skip = null,
        int? take = null)
        where TEntity : class, TEntityModel
    {
        includeProperties = includeProperties ?? string.Empty;
        IQueryable<TEntityModel> query = _context.Set<TEntityModel>();

        if (filter != null)
        {
            query = query.Where(filter);
        }
        
        if (orderBy != null)
        {
            query = orderBy(query);
        }

        if (skip.HasValue)
        {
            query = query.Skip(skip.Value);
        }

        if (take.HasValue)
        {
            query = query.Take(take.Value);
        }

        return query;
    }
}
```

**Comment by duaneking** [comment] 2021-07-15 00:05
@Seabizkit The common interface is clearly IQueryable<TEntity>

```
public interface IReadOnlyRepository
{
 // Stuff you can add
}
```

```
public class EntityFrameworkBasedReadOnlyRepository<TContext> : IReadOnlyRepository  where TContext : DbContext
{
    protected readonly TContext _context;

    public EntityFrameworkBasedReadOnlyRepository(TContext context)
    {
        _context = context;
    }
    
    public  IQueryable<TEntityModel> GetQueryable<TEntityModel>(
        Expression<Func<TEntityModel, bool>> filter = null,
        Func<IQueryable<TEntityModel>, IOrderedQueryable<TEntityModel>> orderBy = null,
        int? skip = null,
        int? take = null)
        where TEntity : class, TEntityModel
    {
        includeProperties = includeProperties ?? string.Empty;
        IQueryable<TEntityModel> query = _context.Set<TEntityModel>();
        
        if (filter != null)
        {
            query = query.Where(filter);
        }
        
        if (orderBy != null)
        {
            query = orderBy(query);
        }

        if (skip.HasValue)
        {
            query = query.Skip(skip.Value);
        }

        if (take.HasValue)
        {
            query = query.Take(take.Value);
        }

        return query;
    }
}
```

If you want a fully explained version,. look up  the "pratts" version.

**Comment by Seabizkit** [comment] 2021-07-15 06:51
@duaneking you will find that that is still locked to Ef6 or Efcore as you have used _context.Set<TEntityModel>(); and implicitly used : DbContext, <--- this is different between versions.... which is not what im after.

**Comment by duaneking** [comment] 2021-07-15 17:26
What you want is not possible unless you want to use IQueryable<TEntity> as the where clause's data type constraint.

**Closed** 2022-10-16 08:48 UTC
Labels: closed-by-design, customer-reported

**Comment by duaneking** [comment] 2022-10-17 15:09
Please reopen this.

**Comment by sfostersaab** [comment] 2023-07-04 08:57
I have also been struggling with the fact that there is no IDbSet interface to be mocked. 

What is the disadvantage over providing both the abstract base class and interface to allow traditional mocking as well as that which is described in this thread?

**Comment by roji** [comment] 2023-07-04 09:27
@sfostersaab mocking DbSets generally doesn't work, since LINQ queries consist of static extension methods; one reason for not introducing IDbSet is to discourage this somewhat (although it's generally just as easy to mock abstract base classes, and DbSet does exist).

For unit testing, we recommend encapsulating your queries in repository pattern methods, and then mocking those methods. This means the LINQ operator are encapsulated within what gets mocked, and your mock can return the exact query results you want.
