### ISSUE TITLE
Fluent API Navigation Name incorrect.

### ISSUE THREAD

**Issue by dpwzone** [dotnet/efcore#31837] opened 2023-09-22 22:03 UTC
Creating a new issue, because the people responding to these are closing tickets with issues that still remain.  Does nobody any good.

Navigation is being created as "Item", and not using the navigation name supplied in the "HasOne" method.

If you're just going to say give us your code, just skip to the next ticket, and let this issue stay open for someone who actually knows how to deal with this.

**Comment by roji** [comment] 2023-09-22 22:07
@dpwzone please stop opening new issues with the same content. We do not leave issues open which have not been verified as bugs via a repro.

If you want, post your question on stackoverflow or a similar external site.

**Comment by roji** [comment] 2023-09-22 22:07
Duplicate of #31836

**Comment by dpwzone** [comment] 2023-09-22 22:08
As stated before, if you don't know what you're talking about, leave the ticket open for someone who does.

**Closed by roji** 2023-09-22 22:07 UTC
Labels: customer-reported
