### ISSUE TITLE
[RC1] Invalid migrations snapshot generated for key Fluent APIs

### ISSUE THREAD

**Issue by gabynevada** [dotnet/efcore#26045] opened 2021-09-15 16:49 UTC
We were testing Preview 7 and it was working correctly but on RC1 we're having some typing issues with the migrations that are generated with EF Core 6.

We are using SQL Server 2019 and utilizing a different Cluster Index than our primary keys, but when ef core generates the ContextModelSnapshot it generates code that fails on build.

## Model class
```c#
public partial class Entity
{
    public Guid EntityId { get; set; }
    public int ClusterId { get; set; }
}
```

## Model Configuration
```c#
  public class UserAddressConfiguration : IEntityTypeConfiguration<Entity>
  {
    public void Configure(EntityTypeBuilder<Entity> entity)
    {
      entity.ToTable("Entity", "entity");

      entity.HasKey(e => e.EntityId)
          .HasName("PKNC_Entity_EntityId")
          .IsClustered(false);

      entity.HasIndex(e => e.ClusterId)
          .HasDatabaseName("AKCI_Entity_ClusterId")
          .IsUnique()
          .IsClustered();
    }
  }
```

## Partial generated code on ContextModelSnapshot
```c#
          b.HasKey("EntityId")
              .HasName("PKNC_Entity_EntityId");

          SqlServerKeyBuilderExtensions.IsClustered(b, false); // Error here

          b.HasIndex("ClusterId")
              .IsUnique()
              .HasDatabaseName("AKCI_Entity_ClusterId");

          SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ClusterId"));
```

## Error
```
  ContextModelSnapshot.cs(131, 63): [CS1503] Argument 1: cannot convert from 'Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder' to 'Microsoft.EntityFrameworkCore.Metadata.Builders.KeyBuilder'
```

### Include provider and version information

EF Core version: 6.0.0-rc.1.21452.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Mac OS Big Sur 11.5.2
IDE: Rider / VsCode

**Comment by roji** [comment] 2021-09-15 21:29
Confirmed, this seems to be a result of #23848. I'll look at this ASAP.

<details>
<summary>Minimal repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

public class BlogContext : DbContext
{
    public DbSet<Entity> Entities { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Entity>(entity => entity.HasKey(e => e.EntityId).IsClustered(false));
    }
}

public class Entity
{
    public Guid EntityId { get; set; }
    public int ClusterId { get; set; }
}
```

Creating a migration generates an invalid model snapshot.

</details>

**Comment by chrissainty** [comment] 2021-09-16 05:14
I started the upgrade of our platform to .NET 6 RC1 yesterday. We're also using a different clustered index to the primary keys and we're seeing exactly the same issue as the OP.

**Comment by roji** [comment] 2021-09-16 05:47
This will be fixed in RC2. As a workaround, manually edit your context snapshots and replace the non-compiling code:

```c#
SqlServerKeyBuilderExtensions.IsClustered(b, false);
```

With the following:

```c#
SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("EntityId"), false);
```

(replacing EntityId with the name of your key column(s)).

**Closed** 2021-09-17 09:38 UTC
Labels: type-bug, closed-fixed, customer-reported, area-migrations
