### ISSUE TITLE
Configuring HasField of navigation properties using Fluent API in EFCore

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#8424] opened 2017-05-09 14:16 UTC
I would like to specify the backing field of a navigation property. EFCore detects a backing field that follows its default naming conventions and uses it correctly, so I believe this should be possible.

However, the problem is that HasField exists only on PropertyBuilder, not on ReferenceNavigationBuilder. Using it on a PropertyBuilder like so:
modelBuilder.Entity<Post>().Property(z => z.Blog).HasField("BlogBackingField");
Gives the following error:
Cannot call Property for the property 'Blog' on entity type 'Post' because it is configured as a navigation property. Property can only be used to configure scalar properties.

**Comment by ajcvickers** [comment] 2017-05-09 16:51
@Wain123 Duplicate of #6674, which also shows the code to do what you want with the current APIs.

**Closed** 2022-10-16 11:04 UTC
