### ISSUE TITLE
Increment DateTimeOffset with value converter

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/efcore#33190] opened 2024-02-28 18:15 UTC
I have this model that has `DateTimeOffset` properties that I need to use in Sqlite.

I've added this value converter:

```csharp
public override void Customize(ModelBuilder modelBuilder, DbContext context)
{
    base.Customize(modelBuilder, context);

    var dateTimeOffsetToDateTimeConverter = new ValueConverter<DateTimeOffset, DateTime>(
        v => v.DateTime,
        v => new DateTimeOffset(v));

    foreach (var entityType in modelBuilder.Model.GetEntityTypes())
    {
        foreach (var property in entityType.GetProperties())
        {
            if (property.ClrType == typeof(DateTimeOffset))
            {
                property.SetValueConverter(dateTimeOffsetToDateTimeConverter);
            }
        }
    }
}
```

However, when using `ExecuteUpdateAsync`  Sqlit cannot translate the query:

> ... could not be translated. Additional information: Translation of method 'System.DateTimeOffset.AddHours' failed.

Is there a way around this?

**Comment by ajcvickers** [comment] 2024-03-04 08:12
Duplicate of #10434

**Closed** 2024-03-06 19:51 UTC
Labels: customer-reported
