### ISSUE TITLE
MySQL provider shown as "coming soon", but not on roadmap

### ISSUE THREAD

**Issue by amattie** [dotnet/efcore#5682] opened 2016-06-07 21:46 UTC
MySQL is shown as a provider on the docs and is listed as "Coming Soon" here: https://docs.efproject.net/en/latest/providers/mysql/index.html. However, it's nowhere to be seen on the roadmap, here: https://github.com/aspnet/EntityFramework/wiki/Roadmap.

Filing this ticket in hopes of finding clarification as to when EF Core will have MySQL support.

**Comment by smitpatel** [comment] 2016-06-07 21:53
dupe of #5659

**Comment by Kagamine** [comment] 2016-07-12 07:11
@amattie There is an open sourced and free mysql provider for ef core now: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

**Comment by gmartinezsan** [comment] 2016-08-23 13:30
Hi all,
We have published our first version of the .net core driver and the ef core provider. Have a look if you like at nuget.
More information here:
http://insidemysql.com/mysql-connectornet-7-0-4-m3-has-been-released/

**Closed** 2022-10-16 09:44 UTC
