### ISSUE TITLE
Question: Persist model/metadata between application restarts

### ISSUE THREAD

**Issue by Tasteful** [dotnet/efcore#9926] opened 2017-09-29 10:30 UTC
Is there a way to persist/load the model/metadata between application restarts?

I was measurement my applications startup time and the creation of model/metadata was taking about 2 seconds for each startup, all model is created by code in the OnModelCreating method.

EFCore SqlServer version 1.1.2

**Comment by ajcvickers** [comment] 2017-10-04 20:35
Closing as duplicate of #1906

**Closed** 2022-10-16 11:51 UTC
