### ISSUE TITLE
Migrating to 2.1 adds extra indexes and foreign keys

### ISSUE THREAD

**Issue by dushkostanoeski** [dotnet/efcore#11393] opened 2018-03-23 08:30 UTC
I have the following data structure: 
```
public class Foo {
    public long Id;
    public virtual ICollection<Bar> Bars { get; set; }
}

public abstract class Bar {
    // properties
}

public class Bar1 : Bar {
    public long FooId { get; set; }
    public virtual Foo Foo { get; set; }
}

public class Bar2 : Bar {
    public long FooId { get; set; }
    public long Foo Foo { get; set; }
}

// these two lines are inside the OnModelCreating method in the context
modelBuilder.Entity<Bar1>.Property(x => x.FooId).HasColumnName("FooId");
modelBuilder.Entity<Bar2>.Property(x => x.FooId).HasColumnName("FooId");

```

The initial migration for the code was generated using 2.0 and the `Bar` table had only one index and one foreign key. After making changes to the model, the first migration with 2.1 added another foreign key and index to the same property. 

Is this normal, because I couldn't find anything about this change.

**Comment by divega** [comment] 2018-03-23 18:42
@smitpatel can you please find the duplicate for this?

**Comment by smitpatel** [comment] 2018-03-23 19:43
Duplicate of #11094 
Based on discussion on that, it is doubtful that we would uniqui-fy in this case.
@AndriySvyryd - thoughts?

**Comment by AndriySvyryd** [comment] 2018-03-23 20:28
@smitpatel Correct. Using the latest nightly build of 2.1 should produce the same model as 2.0

**Comment by dushkostanoeski** [comment] 2018-06-04 10:07
@AndriySvyryd I just upgraded to the 2.1.0 release, and the migration still added the extra indexes and foreign keys.

**Comment by AndriySvyryd** [comment] 2018-06-04 20:35
@dushkostanoeski You need to move the navigation `Foo` to the base - `Bar` to indicate that both derived relationships should be represented by a single FK. Otherwise you can just configure the FK name on both relationship explicitly to the same value.

**Closed** 2022-10-16 12:15 UTC
Labels: closed-duplicate
