### ISSUE TITLE
Support for non-datastore-generated ConcurrencyTokens

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#3039] opened 2015-09-06 19:27 UTC
EF7's optimistic concurrency seems to depend on a ConcurrencyToken property being defined, and on that property having `ValueGeneratedOnAddOrUpdate`. In other words, I don't see any provisions for generating the value of concurrency tokens client-side when the property isn't marked as datastore-generated.

PostgreSQL lacks a rowversion-style column type which updates automatically. In fact, it lacks easy means to define any sort of column that automatically changes on update (e.g. modification timestamp). It's possible to define triggers to do this kind of work (see [this post for example](http://www.pointbeing.net/weblog/2008/03/mysql-versus-postgresql-adding-a-last-modified-column-to-a-table.html)) but this approach isn't elegant or easy to implement.

For the PostgreSQL case it seems reasonable to simply implement `ValueGeneratedOnAddOrUpdate` via triggers. However, if a database comes along with truly no support for value generation on update then optimistic concurrency becomes impossible. So it may make sense to manage concurrency token generation at the client if `ValueGeneratedOnAddOrUpdate` isn't specified.

If you don't want to support this scenario (I'm really not sure whether such databases exist), then it might make sense to make the `ConcurrencyToken` imply `ValueGeneratedOnAddOrUpdate` as well; as things are if I add `ConcurrencyToken` to a property but forget to add `ValueGeneratedOnAddOrUpdate` things will inexplicably not work. Another option is to bomb if `ValueGeneratedOnAddOrUpdate` isn't specified (this will allow you to provide client-side generation in the future without backwards-compatibility concerns).

**Comment by bricelam** [comment] 2015-09-08 16:46
Dupe of #2195?

**Comment by roji** [comment] 2015-09-08 16:57
Indeed, sorry!

**Comment by ajcvickers** [comment] 2015-09-08 17:11
@roji I know you closed this but I just want to clarify something. Optimistic concurrency can work without there being automatic update of the concurrency token on either the client or the server if the property that is marked as the concurrency token is manually updated before some or all saves. So while it is common to use auto-update of some sort for concurrency tokens, it is still entirely valid to have any property marked as a concurrency token regardless of what other flag might be set. Therefore we would not want to, at the lowest level, have the concurrency token flag imply that some other flag is also set.

**Comment by roji** [comment] 2015-09-08 17:15
Understood @ajcvickers, thanks for the explanation! I only had the automatic token management in my head.

**Comment by bricelam** [comment] 2015-09-08 17:37
@roji I had to search for a few minutes to find that issue, so I don't blame you for not finding it. :wink:

**Comment by roji** [comment] 2015-09-08 17:42
Sure thing, we all hate dupes :)

**Comment by pantonis** [comment] 2016-03-01 11:06
I know this is closed but this feature is very very useful. Was this implemented?

**Comment by bricelam** [comment] 2016-03-01 16:49
@pantonis Not yet. Issue #2195 on the backlog is tracking this feature.

**Closed** 2022-10-16 09:07 UTC
