### ISSUE TITLE
EF 7 RC1 - The binary operator Equal is not defined for the types 'System.Guid' and 'System.Nullable`1[System.Guid]'

### ISSUE THREAD

**Issue by gabynevada** [dotnet/efcore#29120] opened 2022-09-16 02:20 UTC
## File a bug

Updated one of our project to EF 7 RC1, it works as expected until we hit any path that utilizes UserManager from Microsoft.AspNetCore.Identity

As soon as we use one of the methods, the code fails with the message **"The binary operator Equal is not defined for the types 'System.Guid' and 'System.Nullable`1[System.Guid]'"**

Any help or insight is appreciated.

### Include your code

```C#
var user = await _userManager.FindByIdAsync(userId.ToString());
// Fails
// Other code from method
```

Model

```c#
public class User : IdentityUser<Guid>
{
// Additional fields
}
```

DbContext

```c#
 public class AppContext : IdentityDbContext<User, Role, Guid, UserClaim, UserRole, UserLogin, RoleClaim, UserToken>
{
  public BioportalContext(DbContextOptions<BioportalContext> options) : base(options)
  {
  }
  public DbSet<User> User => Set<User>();
  // More...
}
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (160ms) [Parameters=[@__get_Item_0='?' (DbType = Guid)], CommandType='Text', CommandTimeout='90']
      SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[BirthDate], [u].[ClusterId], [u].[ConcurrencyStamp], [u].[Email], [u].[EmailConfirmed], [u].[FirstName], [u].[FullName], [u].[FullNameForSearch], [u].[LastName], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[MiddleName], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PatientId], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecondLastName], [u].[SecurityStamp], [u].[Sex], [u].[Ssn], [u].[Suffix], [u].[Title], [u].[TwoFactorEnabled], [u].[UserName]
      FROM [authentication].[User] AS [u]
      WHERE [u].[Id] = @__get_Item_0
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'App.Infrastructure.AppContext'.
      System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.InvalidOperationException: The binary operator Equal is not defined for the types 'System.Guid' and 'System.Nullable`1[System.Guid]'.
         at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
         at Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer.DefaultValueComparer`1.ExtractEqualsBody(Expression leftExpression, Expression rightExpression)
         at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyAccessorsFactory.CreateCurrentValueGetter[TProperty](IPropertyBase propertyBase, Boolean useStoreGeneratedValues)
         at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyAccessorsFactory.CreateGeneric[TProperty](IPropertyBase propertyBase)
         at InvokeStub_PropertyAccessorsFactory.CreateGeneric(Object, Object, IntPtr*)
         at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
         --- End of inner exception stack trace ---
         at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyAccessorsFactory.Create(IPropertyBase propertyBase)
         at Microsoft.EntityFrameworkCore.Metadata.RuntimePropertyBase.<>c.<Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimePropertyBase.get_Accessors>b__29_0(RuntimePropertyBase property)
         at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
         at Microsoft.EntityFrameworkCore.Metadata.RuntimePropertyBase.Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimePropertyBase.get_Accessors()
         at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyBaseExtensions.GetPropertyAccessors(IPropertyBase propertyBase)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.DependentKeyValueFactoryFactory.CreateSimple[TKey](IForeignKey foreignKey)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.KeyValueFactoryFactory.CreateSimpleFactory[TKey](IKey key)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.KeyValueFactoryFactory.Create[TKey](IKey key)
         at Microsoft.EntityFrameworkCore.Metadata.RuntimeKey.<>c__24`1.<Microsoft.EntityFrameworkCore.Metadata.IKey.GetPrincipalKeyValueFactory>b__24_0(RuntimeKey key)
         at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
         at Microsoft.EntityFrameworkCore.Metadata.RuntimeKey.Microsoft.EntityFrameworkCore.Metadata.IKey.GetPrincipalKeyValueFactory[TKey]()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMapFactoryFactory.CreateFactory[TKey](IKey key)
         at InvokeStub_IdentityMapFactoryFactory.CreateFactory(Object, Object, IntPtr*)
         at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
         --- End of inner exception stack trace ---
         at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMapFactoryFactory.Create(IKey key)
         at Microsoft.EntityFrameworkCore.Metadata.RuntimeKey.<>c.<Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimeKey.GetIdentityMapFactory>b__25_0(RuntimeKey key)
         at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
         at Microsoft.EntityFrameworkCore.Metadata.RuntimeKey.Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimeKey.GetIdentityMapFactory()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateIdentityMap(IKey key)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.TryGetEntry(IKey key, Object[] keyValues, Boolean throwOnNullKey, Boolean& hasNullKey)
         at Microsoft.EntityFrameworkCore.Query.QueryContext.TryGetEntry(IKey key, Object[] keyValues, Boolean throwOnNullKey, Boolean& hasNullKey)
         at lambda_method43(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.InvalidOperationException: The binary operator Equal is not defined for the types 'System.Guid' and 'System.Nullable`1[System.Guid]'.
         at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
         at Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer.DefaultValueComparer`1.ExtractEqualsBody(Expression leftExpression, Expression rightExpression)
         at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyAccessorsFactory.CreateCurrentValueGetter[TProperty](IPropertyBase propertyBase, Boolean useStoreGeneratedValues)
         at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyAccessorsFactory.CreateGeneric[TProperty](IPropertyBase propertyBase)
         at InvokeStub_PropertyAccessorsFactory.CreateGeneric(Object, Object, IntPtr*)
         at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
         --- End of inner exception stack trace ---
         at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyAccessorsFactory.Create(IPropertyBase propertyBase)
         at Microsoft.EntityFrameworkCore.Metadata.RuntimePropertyBase.<>c.<Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimePropertyBase.get_Accessors>b__29_0(RuntimePropertyBase property)
         at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
         at Microsoft.EntityFrameworkCore.Metadata.RuntimePropertyBase.Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimePropertyBase.get_Accessors()
         at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyBaseExtensions.GetPropertyAccessors(IPropertyBase propertyBase)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.DependentKeyValueFactoryFactory.CreateSimple[TKey](IForeignKey foreignKey)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.KeyValueFactoryFactory.CreateSimpleFactory[TKey](IKey key)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.KeyValueFactoryFactory.Create[TKey](IKey key)
         at Microsoft.EntityFrameworkCore.Metadata.RuntimeKey.<>c__24`1.<Microsoft.EntityFrameworkCore.Metadata.IKey.GetPrincipalKeyValueFactory>b__24_0(RuntimeKey key)
         at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
         at Microsoft.EntityFrameworkCore.Metadata.RuntimeKey.Microsoft.EntityFrameworkCore.Metadata.IKey.GetPrincipalKeyValueFactory[TKey]()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMapFactoryFactory.CreateFactory[TKey](IKey key)
         at InvokeStub_IdentityMapFactoryFactory.CreateFactory(Object, Object, IntPtr*)
         at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
         --- End of inner exception stack trace ---
         at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMapFactoryFactory.Create(IKey key)
         at Microsoft.EntityFrameworkCore.Metadata.RuntimeKey.<>c.<Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimeKey.GetIdentityMapFactory>b__25_0(RuntimeKey key)
         at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
         at Microsoft.EntityFrameworkCore.Metadata.RuntimeKey.Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimeKey.GetIdentityMapFactory()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateIdentityMap(IKey key)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.TryGetEntry(IKey key, Object[] keyValues, Boolean throwOnNullKey, Boolean& hasNullKey)
         at Microsoft.EntityFrameworkCore.Query.QueryContext.TryGetEntry(IKey key, Object[] keyValues, Boolean throwOnNullKey, Boolean& hasNullKey)
         at lambda_method43(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

### Include provider and version information

EF Core version: 7.0.0-rc.1.22426.7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: net7.0
Operating system: MacOS Monterey V12.6
IDE: Rider 2022.2.3

**Comment by smitpatel** [comment] 2022-09-16 04:50
Problematic line https://github.com/dotnet/efcore/blob/d28a1c78e31e23cb12983e6e6383d1c49abeefe2/src/EFCore/ChangeTracking/ValueComparer.cs#L249

**Comment by ajcvickers** [comment] 2022-09-16 10:52
@gabynevada I am not able to reproduce this. Can you attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate?

**Comment by gabynevada** [comment] 2022-09-16 14:35
@ajcvickers Was able to reproduce by creating a one to many relationship with another table with Guid primary key and utilizing compiled models.

Here is the minimal reproduction repo https://github.com/gabynevada/ef7-rc1-compiled-models-error

**Comment by ajcvickers** [comment] 2022-09-18 11:50
Duplicate of #28108. Verified that the provided repro works with the latest daily build.

**Closed by ajcvickers** 2022-09-18 11:50 UTC
Labels: customer-reported
