### ISSUE TITLE
Deploying DB Migrations from build output from pure PowerShell

### ISSUE THREAD

**Issue by dgee2** [dotnet/efcore#7942] opened 2017-03-21 14:43 UTC
Hi,

I'm working on a project using EF Core where we want to be able to deploy the database migrations (and probably a fresh DB) from a PowerShell prompt as part of our CI.
Is there a way that we can use PowerShell to deploy the database migrations from our built binaries without having to do some lifting and shifting of source code and the Microsoft.EntityFrameworkCore.Tools  or Microsoft.EntityFrameworkCore.Tools.DotNet package and using dotnet ef?

It is very undesirable for us to have to ship the source along with the binaries in order to run the deployment to the database and we cannot run the deployment from the Package Manager Console.

We are targeting: netcoreapp1.1
EFCore: Microsoft.EntityFrameworkCore.SqlServer: 1.1.1

Any help on this (or if you think that we're just attacking this from the wrong direction) would be massively appreciated.

**Comment by ajcvickers** [comment] 2017-03-31 22:43
@dgee2 This seems like a duplicate of issue #6313. Reading through that should give you some idea of what we have already, but as that issue indicates, this is an area where we want to make the experience better. 

Also, this scenario won't involve the PowerShell commands even when we make improvements to it, but rather a stand-alone "executable". You can of course invoke that executable from PowerShell.

**Closed** 2022-10-16 10:57 UTC
