### ISSUE TITLE
Spatialite causes native crash in spatial tests on Ubuntu impish

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#27662] opened 2022-03-17 15:10 UTC
I'm runing on Ubuntu impish (21.10), which has spatialite 5.0.1-2build1 (packages libspatialite7, libsqlite3-mod-spatialite). Trying to run the SQLite spatial tests (`dotnet test --filter SpatialQuerySqliteTest`) causes a native crashes (`Test host process crashed`, no native stack trace, though should be possible to get one).

Note that I tried downgrading to 4.3.0a-6build1, which is what Ubuntu focal uses (20.04, latest LTS), and that didn't help... Note that uninstalling libsqlite3-mod-spatialite was enough to make the error go away (tests are skipped), even though libspatialite7 is still installed.

Can investigate further /cc @bricelam

**Comment by ajcvickers** [comment] 2022-03-25 09:42
Duplicate of #22138.

**Closed** 2022-10-16 20:29 UTC
Labels: closed-duplicate
