### ISSUE TITLE
on trying to saveChanges() Microsoft.EntityFrameworkCore.Relational is asking for non exist column

### ISSUE THREAD

**Issue by arilishu** [dotnet/efcore#22101] opened 2020-08-17 20:57 UTC
i have added 2 tables from an already created database.
Leads & quotes.
Table Quotes has the lead column related to table Leads.
After trying to save a new quote the error says: 
 | InnerException | {"Invalid column name 'LeadsId'."} | System.Exception {Microsoft.Data.SqlClient.SqlException}

I have columns Lead, not LeadsId.
EF Core version:3.1.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system: Windows 10
IDE: Microsoft Visual Studio Community 2019
Version 16.4.1

**Comment by ajcvickers** [comment] 2020-08-20 17:38
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by smitpatel** [comment] 2020-09-04 14:52
EF Team Triage: Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.

**Closed** 2022-10-16 18:37 UTC
Labels: closed-could-not-reproduce, customer-reported
