### ISSUE TITLE
Mapping attribute for IsUnicode

### ISSUE THREAD

**Issue by IanKemp** [dotnet/efcore#19794] opened 2020-02-04 14:02 UTC
#### What problem are you trying to solve?

We prefer to configure our entities via properties on the entities themselves, as opposed to using the fluent syntax, because we've found it makes the code more readable. However, because not every method on `PropertyBuilder` has an associated attribute (e.g. [`IsUnicode`][1]), it's not possible to use this approach - so we either have to use a half-half approach, or go full fluent; neither of which are desirable.

#### Describe the solution you'd like 

Add attributes that mirror all available methods exposed by `PropertyBuilder` and result in the same behaviour.

This would have the additional benefit that EF would no longer have to rely on (mis)-using the attributes in the `System.Data.DataAnnotations` namespace, which are rather... overloaded at this point. That would make it easier for people to transition between fluent syntax and attributes, without needing [an entire article][2] to inform users how to map between both ways.

  [1]: https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.propertybuilder-1.isunicode
  [2]: https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt

**Comment by ajcvickers** [comment] 2020-02-04 16:18
Duplicate of #10864

**Comment by smitpatel** [comment] 2020-10-16 22:19
Design questions for @dotnet/efteam 
- Unicode attribute can be specified on any property/field/parameter. Do we need parameter support at present? We don't recognize it anywhere.
- The XML docs refers that it can be set on string properties only. Should it be string equivalent on server side? e.g. JSON converted to string using value converter, can/should user specify IsUnicode for it? In annotation? In Fluent API?
- In scaffolding do we print out Unicode if the value is going to be default value for strings (true).
Unrelated to UnicodeAttribute.
- Do we want ordering of annotations printed on entity type/properties in scaffolded code?

**Comment by smitpatel** [comment] 2020-10-21 17:34
- Specified on property. Field if convention pick it up by default once the field is mapped. Parameter support is deferred till we need it.
- XML docs should be consistent with IsUnicode fluent API.
- Scaffolding should not print attribute if default value
- Keep current ordering.

**Comment by smitpatel** [comment] 2020-10-27 02:46
Fixed in 22514

**Closed by smitpatel** 2020-10-27 02:46 UTC
Labels: area-model-building, closed-fixed, community-contribution, customer-reported, good first issue, type-enhancement

**Comment by IanKemp** [comment] 2020-10-27 12:01
Thanks guys!
