### ISSUE TITLE
"Outer apply" join can only be used once in select part of LINQ statement

### ISSUE THREAD

**Issue by David-Mawer** [dotnet/efcore#5917] opened 2016-06-30 11:51 UTC
### Steps to reproduce

The following LINQ query has an "Outer Apply" join with an IQueryable variable called "thoughtCommentJoin".

The table is aliased "tc" for the select part of the LINQ statement.

Executing the code as it stands returns the error: -

> System.ArgumentException occurred
>   HResult=-2147024809
>   Message=Property 'System.String Comment' is not defined for type 'System.String'
>   Source=System.Core
>   StackTrace:
>        at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
>   InnerException: 

This error happens without any SQL commands being sent to the database (I verified using SQL Server Profiler)

Now the strange thing, is this: -
The last 2 lines in the "select new  ..." part of the statement set values from the tc alias.
If either one of those lines is commented out, then the code executes without an error.

```
var thoughtCommentJoin = from tc in DbContext.ThoughtComments
                                      join st in DbContext.Students
                                          on tc.UserId equals st.UserId into students
                                      from st in students.DefaultIfEmpty()
                                      join te in DbContext.Teachers
                                          on tc.UserId equals te.UserId into teachers
                                      from te in teachers.DefaultIfEmpty()
                                      select new
                                             {
                                                 tc.ThoughtId,
                                                 tc.DateTime,
                                                 tc.Comment,
                                                 RespondentName = st == null
                                                     ? te.FirstName + " " + te.LastName
                                                     : st.FirstName + " " + st.LastName
                                             };

                var powerText = (int) BookRelativeLexileLevelEnum.PowerText;

                var query = from s in DbContext.Students
                            join sc in DbContext.StudentClassCrossReferences
                                on s.StudentId equals sc.StudentId
                            join t in DbContext.Thoughts
                                on new {s.UserId, sc.ClassId} equals new {t.UserId, ClassId = t.ClassId.Value}
                            join b in DbContext.Books
                                on t.BookId equals b.BookId

                            // Left join the CommonCoreSubStandards
                            join css in DbContext.CommonCoreSubStandards
                                on t.CommonCoreSubStandardId equals css.CommonCoreStandardId into
                                commonCoreStd
                            from css in commonCoreStd.DefaultIfEmpty()

                            // Outer apply the first response to the thought.
                            join tc in thoughtCommentJoin
                                on t.ThoughtId equals tc.ThoughtId into ot1
                            let tc = ot1.OrderBy(x => x.DateTime)
                                        .FirstOrDefault()

                            // Outer Apply the borrowed book record for the thought.
                            join relativeLexileLevelAtCheckout in DbContext.BorrowedBooks
                                on new {BookId = t.BookId.Value, t.UserId} equals new {relativeLexileLevelAtCheckout.BookId, relativeLexileLevelAtCheckout.UserId} into ot2
                            let relativeLexileLevelAtCheckout = ot2.Where(x => x.BorrowedDate <= t.CreatedTime)
                                        .OrderByDescending(x => x.BorrowedDate)
                                        .Select(x => (int?) x.RelativeLexileLevelAtCheckout)
                                        .FirstOrDefault()

                            // Outer Apply the Book Completion for the thought.
                            join bc in DbContext.UserBookCompletions
                                on new {BookId = t.BookId.Value, t.UserId} equals new {bc.BookId, bc.UserId} into
                                ot3
                            let bc = ot3.OrderBy(x => x.CompletionDateTime)
                                        .FirstOrDefault()

                            where sc.ClassId == classId
                                  && (Guid.Empty.Equals(testStudentId) || sc.StudentId == testStudentId)
                            select new StudentThoughtCsv()
                                   {
                                       StudentId = s.StudentId,
                                       ClassId = sc.ClassId,
                                       ThoughtId = t.ThoughtId,
                                       StudentName = (s.FirstName + ' ').TrimStart() + s.LastName,
                                       TextTitle = b.Title,
                                       // TODO: LIGAPI-1813: CASE WHEN ISNULL(bb.RelativeLexileLevelIdAtCheckout, 0) = 2 THEN 'Yes' ELSE 'No' END,
                                       PowerText =
                                           relativeLexileLevelAtCheckout == null
                                               ? "No"
                                               : (powerText == relativeLexileLevelAtCheckout ? "Yes" : "No"),
                                       NoOfPages = b.TotalPages,
                                       Lexile = b.LexileRating + "L",
                                       Category = b.ClassificationType.ToString(),
                                       Status = "", // TODO: LIGAPI-1813: 
                                       DateCreated = t.CreatedTime,
                                       StandardTag = css == null ? "" : css.CommonCoreSubStandardDescription ?? "",
                                       PageCited = t.PageNumber,
                                       Passage = t.SelectedText,
                                       ThoughtCreated = t.ThoughtText,
                                       Respondent = tc == null ? "" : tc.RespondentName ?? "",
                                       Response = tc == null ? "" : tc.Comment ?? ""
                                   };
                result = query.ToList();
```
### The issue

The issue is this: - I expect the "tc" alias in the LINQ query to work consistantly. If it works for one row of the select, then it should work for more than one row.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
> System.ArgumentException occurred
  HResult=-2147024809
  Message=Property 'System.String Comment' is not defined for type 'System.String'
  Source=System.Core
  StackTrace:
       at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
  InnerException: 


Stack trace:
>    at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)

TargetSite:
> {System.Linq.Expressions.MemberExpression Property(System.Linq.Expressions.Expression, System.Reflection.PropertyInfo)}



```
### Further technical details

EF Core version: 1.1.0-alpha1-21474
Operating system: Windows 10 Pro (64 Bit)
Visual Studio version: VS 2015

Other details about my project setup:

**Comment by rowanmiller** [comment] 2016-07-01 17:16
Hey,

We'll need something that we can run in order to reproduce and debug this one. Trying to reverse engineer your model from the query isn't really feasible.

When filing issues, if possible, try to follow the template we provide - which includes the following section:

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

~Rowan

**Comment by rowanmiller** [comment] 2016-07-05 18:13
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it. Will reopen if more info is provided.

**Closed** 2022-10-16 09:48 UTC
