### ISSUE TITLE
`EF.Functions` could not be translated and will be evaluated locally when used as key of GroupBy?

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/efcore#12822] opened 2018-07-27 09:21 UTC
#### Describe what is not working as expected.
Since #10404 is not available now, I'm trying to use `DateDiffDay` to get it for groupby, but found `EF.Functions` also not works for groupby.
`EF.Functions` could not be translated and will be evaluated locally when used as key of GroupBy?

### If you are seeing an exception, include the full exceptions details (message and stack trace).
>None

#### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
dbContext.CommDataDay
                    .GroupBy(d => (EF.Functions.DateDiffDay(new DateTime(2000, 1, 2), d.StartTime) % 7 + 7) % 7)
                    .Select(d => new { Dw = (DayOfWeek)d.Key, Value = d.Sum(d1=>d1.DeltaValue) })
                    .ToList();

dbContext.CommDataDay
                    .Select(d => new { Dw = (EF.Functions.DateDiffDay(new DateTime(2000, 1, 2), d.StartTime) % 7 + 7) % 7, d.DeltaValue })
                    .GroupBy(d => d.Dw)
                    .Select(d => new { Dw = (DayOfWeek)d.Key, Value = d.Sum(d1=>d1.DeltaValue) })
                    .ToList();
```
```
Microsoft.EntityFrameworkCore.Query Warn The LINQ expression 'GroupBy((((__Functions_0.DateDiffDay(2000/1/2 0:00:00, [d].StartTime) % 7) + 7) % 7), [d])' could not be translated and will be evaluated locally.

Microsoft.EntityFrameworkCore.Database.Command Info Executed DbCommand (67ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [d].[Start_Time], [d].[Delta_Value]
FROM [Comm_Data_Day] AS [d]
ORDER BY ((DATEDIFF(DAY, '2000-01-02T00:00:00.0000000', [d].[Start_Time]) % 7) + 7) % 7
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)`2.1.2`
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) `Microsoft.EntityFrameworkCore.SqlServer`
Operating system: `Win10 x64(1803 17134)`
IDE: (e.g. Visual Studio 2017 15.4)`VS2017 15.8p5`

**Comment by smitpatel** [comment] 2018-07-27 17:01
Can you try wrapping up your key into an anonymous type?

**Comment by smitpatel** [comment] 2018-07-27 17:01
Superset of #12476

**Comment by yyjdelete** [comment] 2018-07-28 03:12
`wrapping up your key into an anonymous type` works for me.

**Comment by smitpatel** [comment] 2018-08-01 00:34
Duplicate of #12476

**Closed** 2022-10-16 13:22 UTC
Labels: closed-duplicate, customer-reported
