### ISSUE TITLE
[UWP] [ARM] [RELEASE] Crash with Native 

### ISSUE THREAD

**Issue by nicojmb** [dotnet/efcore#6237] opened 2016-08-03 17:06 UTC
### Steps to reproduce

Run include solution in ARM and Release mode.
### The issue

App crash in ARM when run Realease Versión

In Debug Mode works in (x86, x64, ARM)
In Release Mode only works in (X86, x64)

[Solution.zip](https://github.com/aspnet/EntityFramework/files/399998/Solution.zip)
![screen crash](https://cloud.githubusercontent.com/assets/5610392/17374518/4dc6fa16-59ad-11e6-938a-82f78a4d8013.png)

```
Exception message:
Stack trace:
`   [External Code] 
    Microsoft.EntityFrameworkCore.Relational.dll!System.SharedTypeExtensions.TryGetElementType(System.Type type, System.Type interfaceOrBaseType)   Unknown
    Microsoft.EntityFrameworkCore.Relational.dll!System.Reflection.PropertyInfoExtensions.FindCandidateNavigationPropertyType(System.Reflection.PropertyInfo propertyInfo, System.Func<System.Type,bool> isPrimitiveProperty)   Unknown
    Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationalForeignKeyAttributeConvention.FindCandidateNavigationPropertyType(System.Reflection.PropertyInfo propertyInfo)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ForeignKeyAttributeConvention.FindForeignKeyAttributeOnProperty(Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType entityType, string navigationName) Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ForeignKeyAttributeConvention.Apply(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder relationshipBuilder)  Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnForeignKeyAdded(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder relationshipBuilder)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder principalEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder dependentEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToPrincipal, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToDependent, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property> dependentProperties, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property> principalProperties, bool? isUnique, bool? isRequired, Microsoft.EntityFrameworkCore.Metadata.DeleteBehavior? deleteBehavior, bool oldRelationshipInverted, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? principalEndConfigurationSource, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? configurationSource, bool runConventions)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? configurationSource, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder principalEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder dependentEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToPrincipal, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToDependent, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property> dependentProperties, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property> principalProperties, bool? isUnique, bool? isRequired, Microsoft.EntityFrameworkCore.Metadata.DeleteBehavior? deleteBehavior, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? principalEndConfigurationSource, bool oldRelationshipInverted, bool runConventions)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToPrincipal, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToDependent, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? configurationSource, bool runConventions)  Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToPrincipal, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToDependent, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? configurationSource)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(System.Reflection.PropertyInfo navigationToPrincipalProperty, System.Reflection.PropertyInfo navigationToDependentProperty, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource)  Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Relationship(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder targetEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToTarget, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? inverseNavigation, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource) Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Relationship(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder targetEntityTypeBuilder, string navigationToTargetName, string inverseNavigationName, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.CreateRelationships(System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.RelationshipCandidate> relationshipCandidates, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder)  Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.DiscoverRelationships(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder)    Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.Apply(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder)    Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAdded(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType entityType, bool runConventions)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(System.Type type, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource, bool runConventions)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(System.Type type, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource, bool runConventions)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.FindRelationshipCandidates(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.DiscoverRelationships(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder)    Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.Apply(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder)    Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAdded(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType entityType, bool runConventions)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(System.Type type, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource, bool runConventions)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(System.Type type, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource, bool runConventions)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.ModelBuilder.Entity(System.Type type)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.FindSets(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder, Microsoft.EntityFrameworkCore.DbContext context)   Unknown
    Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Infrastructure.Internal.RelationalModelSource.FindSets(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder, Microsoft.EntityFrameworkCore.DbContext context) Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(Microsoft.EntityFrameworkCore.DbContext context, Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.IConventionSetBuilder conventionSetBuilder, Microsoft.EntityFrameworkCore.Internal.IModelValidator validator)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel.AnonymousMethod__0(object k)    Unknown
    System.Collections.Concurrent.dll!System.Collections.Concurrent.ConcurrentDictionary<object,object>.GetOrAdd(object key, System.Func<object,object> valueFactory) Line 271  C#
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(Microsoft.EntityFrameworkCore.DbContext context, Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.IConventionSetBuilder conventionSetBuilder, Microsoft.EntityFrameworkCore.Internal.IModelValidator validator)  Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()    Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Internal.DbContextServices.Model.get()  Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.AddEntityFramework.AnonymousMethod__0_4(System.IServiceProvider p)    Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)    Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)  Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)   Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)  Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.RealizeService.AnonymousMethod__0(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)  Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System.Type serviceType)   Unknown
    Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(System.IServiceProvider provider, System.Type serviceType)   Unknown
    Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator>(System.IServiceProvider provider)  Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Storage.DatabaseProviderServices.GetService<System.__Canon>()   Unknown
    Microsoft.EntityFrameworkCore.Sqlite.dll!Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseProviderServices.Creator.get()    Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.AddEntityFramework.AnonymousMethod__0_11(System.IServiceProvider p)   Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)    Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)  Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)   Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)  Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.RealizeService.AnonymousMethod__0(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)  Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System.Type serviceType)   Unknown
    Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(System.IServiceProvider provider, System.Type serviceType)   Unknown
    Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Microsoft.EntityFrameworkCore.Migrations.Internal.SqliteHistoryRepository>(System.IServiceProvider provider) Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Storage.DatabaseProviderServices.GetService<System.__Canon>()   Unknown
    Microsoft.EntityFrameworkCore.Sqlite.dll!Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseProviderServices.HistoryRepository.get()  Unknown
    Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Infrastructure.RelationalServiceCollectionExtensions.AddRelational.AnonymousMethod__0_8(System.IServiceProvider p)   Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)    Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)  Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)   Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)  Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.RealizeService.AnonymousMethod__0(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)  Unknown
    Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System.Type serviceType)   Unknown
    Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService<Microsoft.EntityFrameworkCore.Migrations.IMigrator>(Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider> accessor)    Unknown
    Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade databaseFacade)   Unknown
>   UWP_Test.exe!UWP_Test.App.App() Line 29 C#
    UWP_Test.exe!UWP_Test.Program.Main.AnonymousMethod__0_0(Windows.UI.Xaml.ApplicationInitializationCallbackParams p) Line 24  C#
    [External Code] 
`

### Further technical details

EF Core version: 1.0.0
Operating system: Windows 10
Visual Studio version: VS2015 Update 3 (1.4.1 Tools)
Tested in Microsft 550 and 950 XL

```

**Comment by natemcmaster** [comment] 2016-08-03 19:00
Possible duplicate of #6183 (which is still open for investigation)

**Comment by natemcmaster** [comment] 2016-08-05 18:29
This issue has been reported multiple times to EF. To consolidate tracking the issue, I've opened https://github.com/aspnet/EntityFramework/issues/6253. I'm closing this as a duplicate for now, but feel free to continue discussion of issues specific to your app. 

We can re-open if this problem isn't solved by disabling the code optimizer.

**Closed by natemcmaster** 2016-08-05 18:29 UTC
