### ISSUE TITLE
Owned type not automatically loaded via navigation property

### ISSUE THREAD

**Issue by rollandjb** [dotnet/efcore#11130] opened 2018-03-02 07:39 UTC
Given 

```
public class Group
{
    public int Id { get; set; }
    public string Name { get; set; }
    
    public List<User> Users { get; set; }
}

public class User
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }

    public Preferences Preferences { get; set; }
}

public class Preferences
{
    public bool SendNotifications { get; set; }
}

modelBuilder.Entity<User>().OwnsOne(u => u.Preferences);
```

then accessing users via the `Users` navigation property of `Group` does not load owned property `Preferences` on each user:

```
var user = context.Groups.Include(g => g.Users).Where(u => u.Id == Id).SingleOrDefault();
Console.WriteLIne(user.Preferences); // prints null
```

Is this expected behaviour in EF Core 2.0.1?

**Comment by ajcvickers** [comment] 2018-03-02 17:43
@rollandjb This looks like a duplicate of issue #9210. Could you test with the [2.1 preview release](https://blogs.msdn.microsoft.com/dotnet/2018/02/27/announcing-entity-framework-core-2-1-preview-1/), or with our [nightly builds](https://github.com/aspnet/EntityFrameworkCore)?

**Closed** 2022-10-16 12:11 UTC
Labels: closed-duplicate
