### ISSUE TITLE
Multiple entity insert in single transaction, unique key violation fires ConcurrencyException

### ISSUE THREAD

**Issue by kenfolza** [dotnet/efcore#20648] opened 2020-04-15 15:19 UTC
Hi,

We use ef core 3.1.2 and ms sql server in our project. We have an unique key (on 'name' column) on a table.
If we try to insert one entity in a single transaction ef core fires unique key exception (DbUpdateException) as expected.
But when we try to insert different entities in a single transaction and one of the tables has a unique key violation, ef core fires DBConcurrency Exception. But it has to be a unique key exception. 

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment] 2020-04-15 16:50
Duplicate of #20649

**Closed** 2022-10-16 18:20 UTC
Labels: closed-duplicate, customer-reported
