### ISSUE TITLE
How to debug improperly insertion?

### ISSUE THREAD

**Issue by mingtong** [dotnet/efcore#24664] opened 2021-04-15 04:08 UTC
I am using 6.0.0-preview.3.21201.4 on Windows 10, SQLite

I am seeding data to an initial table, while after a bulk insertion, I found
one or more property was not insert into column, but others did, means 2000 rows data were updated, but one column is null.

How to debug the failed column?

What I have done?
1, Enabled sensitive data logging, cannot find any error.
2, View data before SaveChanges, the "Context.Table" have had the target column data.

Thanks!

**Comment by roji** [comment] 2021-04-15 07:12
[Our logging docs](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/) contain a lot of information on how to log what EF is doing; I'd specifically enable command logging to see the exact SQL being sent by EF Core, and enable sensitive data logging to see exactly which data is being sent.

Other than that, we're going to have to see a runnable code sample in order to investigate this further.

**Comment by mingtong** [comment] 2021-04-15 10:16
> [Our logging docs](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/) contain a lot of information on how to log what EF is doing; I'd specifically enable command logging to see the exact SQL being sent by EF Core, and enable sensitive data logging to see exactly which data is being sent.
> 
> Other than that, we're going to have to see a runnable code sample in order to investigate this further.

the sensitive data include the exact insert sql, but the value is showed as "p1", "p2", "px", so not sure what exact data was sent.

**Comment by roji** [comment] 2021-04-15 12:01
We're going to need a runnable code sample to help with this.

**Comment by mingtong** [comment] 2021-04-16 07:23
> We're going to need a runnable code sample to help with this.

Sorry, for data security reason, I cannot share the code and I cannot reproduce it with an example project.

I tried rename the property from "CoverArt" to "abc", then it works.
Please tell me if the "CoverArt" touched any preserved name or string?

**Comment by roji** [comment] 2021-04-16 08:59
@mingtong no, "CoverArt" isn't a reserved string anywhere as far as I know.

**Comment by ajcvickers** [comment] 2021-04-16 13:56
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:31 UTC
Labels: closed-could-not-reproduce, customer-reported
