### ISSUE TITLE
Using the same Class/Model to map to multiple similar structured tables.

### ISSUE THREAD

**Issue by SrinivasPulla** [dotnet/efcore#10272] opened 2017-11-13 09:34 UTC
Issue : Is their any chance of resolving the following issue or any other alternative that you suggest- 

Using the same class (model) to create two tables #7299.
https://github.com/aspnet/EntityFrameworkCore/issues/7299

### Further technical details
EF Core version: 2.0
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
IDE: (e.g. Visual Studio 2017)

Thanks,
Srinivas Pulla.

**Comment by ajcvickers** [comment] 2017-11-14 19:44
@SrinivasPulla Can you provide some more details on what you are trying to do? (The general answer is no, but for owned types, the same type can be used in multiple places. This may or may not help depending on what you are trying to do.)

**Comment by ajcvickers** [comment] 2017-11-22 19:52
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:58 UTC
Labels: closed-could-not-reproduce
