### ISSUE TITLE
Question: Troubleshoot slow SQL query which is fast on the SQL server

### ISSUE THREAD

**Issue by msallin** [dotnet/efcore#24169] opened 2021-02-16 15:20 UTC
We have the case of slow SQL queries which are fast on the MSSQL server.
The best example to show this is the health check. We use EF Core and the health check (which performs a `SELECT 1`).
The health check gets called every 10s by Kubernetes. We have cases in which the duration of this check is >1s.
We are unsure where the problem is and hope for hints into the right direction which help us to further investigate this issue (and maybe to locate the root cause of it).

What we can say:

- We profiled the query. The profiler shows always a duration of 0ms (which means, the query isn't actually slow. Which would be surprising anyway).
- It is not due to thread pool starvation. We used counters to observe the thread pool and it never reaches the configured min threads.
- The time is spend BEFORE the query gets executed. We know this because we the SQL-client instrumentalization and for OpenTelemetry and we log the Activity Stop (i.e. end of the SQL-Client execute).

Some more words to the last point because we think this is interesting.
We started the profiler and profiled all `SELECT 1` statements. Hence we see the end time of the query in the profiler. This end time +2-3ms is equal to the end time logged by the SQL-Client instrumentalization. 

Now we are unable to narrow down the problem further. How we can exclude EF Core, SQL Client or the Network?
We are able to use dotnet-trace, does the SQL-Client offer any additional and maybe helpful information?

### Include provider and version information

Notice that we have this behavior since we started our development (i.e. .NET 3.0).

EF Core version: 5.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: alpine linux (container)

**Comment by roji** [comment] 2021-02-16 16:01
@msallin can you reproduce this in a minimal code sample, ideally a console program?

**Comment by msallin** [comment] 2021-02-16 16:16
We were not able to reproduce this locally so far. 

But we were able to do it using the following code (Linux container, and running on our OpenShift cluster, like our other applications where we see this problem).

At the end, this is probably a infrastructure problem. However, what we also did was to create a docker container with sqlcmd and execute a `SELECT 1` all few sections. There we never saw this. 

On one hand on our side we would be very surprised if this is a problem with a component from the .NET ecosystem (ef, runtime, sqlclient) because its kind of obvious and other would have noticed it.
On the other hand, we have no indication that it is a infrastructure problem and no other team reports similar problems (which doesn't mean that they do not exist). Hence, it would be good to be able to narrow it down but we run out of ideas.

```
namespace HealthCheckTest
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            const string connectionString = "Server = *, 1433; Database = *; User Id = *; Password = *;";

            services.AddDbContext<AppDbContext>(options =>
            {
                options.UseSqlServer(connectionString)
                    .LogTo(Console.WriteLine,
                        new[]
                        {
                            DbLoggerCategory.Database.Connection.Name,
                            DbLoggerCategory.Database.Command.Name
                        },
                        LogLevel.Debug,
                        DbContextLoggerOptions.SingleLine | DbContextLoggerOptions.LocalTime);
            });

            services
                .AddHealthChecks()
                .AddDbContextCheck<AppDbContext>(tags: new[] {"ready"});

        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHealthChecks("/health/ready", new HealthCheckOptions
                {
                    Predicate = check => check.Tags.Contains("ready")
                });
                endpoints.MapHealthChecks("/health/live", new HealthCheckOptions
                {
                    Predicate = _ => false
                });
            });
        }
    }

    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options)
            : base(options)
        {
        }
    }
}
```
namespace HealthCheckTest
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            const string connectionString = "Server = *, 1433; Database = *; User Id = *; Password = *;";

            services.AddDbContext<AppDbContext>(options =>
            {
                options.UseSqlServer(connectionString)
                    .LogTo(Console.WriteLine,
                        new[]
                        {
                            DbLoggerCategory.Database.Connection.Name,
                            DbLoggerCategory.Database.Command.Name
                        },
                        LogLevel.Debug,
                        DbContextLoggerOptions.SingleLine | DbContextLoggerOptions.LocalTime);
            });

            services
                .AddHealthChecks()
                .AddDbContextCheck<AppDbContext>(tags: new[] {"ready"});

        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHealthChecks("/health/ready", new HealthCheckOptions
                {
                    Predicate = check => check.Tags.Contains("ready")
                });
                endpoints.MapHealthChecks("/health/live", new HealthCheckOptions
                {
                    Predicate = _ => false
                });
            });
        }
    }

    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options)
            : base(options)
        {
        }
    }
}
```

**Comment by ajcvickers** [comment] 2021-02-16 16:59
@msallin What does EF Core logging report as the query execution time?

**Comment by msallin** [comment] 2021-02-16 17:28
You mean the logs we get from the `LogTo(Console.WriteLine...`?

We haven't turned this on in our real applications. In the repro (code above) it logged always the whole time taken (i.e. Indicated that the time isn't lost somewhere else, that's why we turned in on in the repro).

**Comment by roji** [comment] 2021-02-22 11:35
@msallin yeah, @ajcvickers was referring to either [Simple logging](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/simple-logging) (LogTo) or [Microsoft.Extensions.Logging](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/extensions-logging?tabs=v3).

So in your repro above, EF Core's logging is also reporting >1s for the health checks, right? Also, do I understand correctly that this repro will only produce the anomalous delay when run inside your production environment (against your production database), but never when executed locally?

If so, at this point I'd fire up a package sniffer such as [wireshark](https://www.wireshark.org/) and look at exactly what's going on at the network level when the health check fires...

**Comment by msallin** [comment] 2021-02-25 09:53
> So in your repro above, EF Core's logging is also reporting >1s for the health checks, right?

Yes.

> Also, do I understand correctly that this repro will only produce the anomalous delay when run inside your production environment (against your production database), but never when executed locally?

Yes, but in the same environment with the same database but another tool (sqlcmd) does not show the same effect.
We will again test locally.

> If so, at this point I'd fire up a package sniffer such as wireshark and look at exactly what's going on at the network level when the health check fires...

This isn't possible. Well, all is possible but its not affordable. Thus my question was how I could proof with e.g. logs or traces from SQL-client that its not a problem with the runtime/ef/sqlclient but with the infrastructure. Any ideas?

**Comment by roji** [comment] 2021-02-25 10:23
If both EF Core and SqlClient are reporting long execution times, and your database is reporting short ones, then it could either be an environment issue, or possibly some issue with SqlClient (that would explain why other tools don't show it), or some application starvation issue (although you seemed to have already ruled that out).

I'm not sure what other evidence could be collected here, though... This really calls for some network sniffing IMHO - this can be done exclusively on your application server, even without a UI (e.g. just capture with tshark or similar and then analyze locally). I'm not sure what other advice I have to give...

**Comment by msallin** [comment] 2021-02-25 10:40
Oh.. I never thought of sniffing inside of my Linux container... Thanks for the hint.
We will do further investigation steps and involve our network and database guys as well.

I will post updates in this ticket and eventually close the ticket if we can rule out EF and SQL-Client.

**Comment by Plasma** [comment] 2021-02-27 05:42
If you’re using async/await, it may be the .Net scheduler delaying resuming an await callback, because it’s too busy (or threads are actually blocked) handling other callbacks.

To rule that out, try using the non-async version of the database queries.

**Comment by roji** [comment] 2021-02-27 08:13
@Plasma that's a good tip in general, but @msallin wrote about that thread pool starvation has already been ruled out.

**Comment by AndriySvyryd** [comment] 2021-03-08 20:39
I'm closing the issue for now, but will reopen if sniffing reveals that the issue is in EF

**Closed** 2022-10-16 19:23 UTC
Labels: closed-external, customer-reported
