### ISSUE TITLE
Exception handling in DbCommandInterceptor's ReaderExecuted method

### ISSUE THREAD

**Issue by nettashamir-allocate** [dotnet/efcore#33199] opened 2024-02-29 10:56 UTC
I am implementing a `DbCommandInterceptor` in order to add some caching.
In the `ReaderExecuted` method, I need to perform some actions to update the cache depending on the results of database commands. 
And clearly, if a DB exception is thrown during the command execution indicating that the db command failed, I don't want to be doing those updates.

I can see that there's a `CommandFailed` callback but this appears to be called **after** `ReaderExecuted`, by which time it's too late since there is no corresponding `CommandSucceeded` which (if it existed) is where it would make sense to make cache updates. So it looks like the updates have to be done in `ReaderExecuted` and I need to have some way of knowing whether the command failed.

Now, the only way I can see to know whether the command failed is to actually read the `DBDataReader` result. If there was an exception, this seems to be thrown when the results reader is first read. Frustratingly, it doesn't appear to have any simple properties which indicate that an exception was thrown.

So, question 1 is:  Am I missing a trick here? Is there another way to find out whether an exception was thrown without actually reading the results DbDataReader?

And, if not... Is it safe to read the results DbDataReader and just re-throw the exception up to the EF calling code? Will it deal with it in the same way as if it encountered the exception while reading the results DbDataReader itself? Or do I need to recreate the results (as I already do for cached results) with something additional to cause it to throw the same exception when the calling code tries to read it?

I appreciate that providing a `CommandSucceeded` callback would require that the result reader be read and a new readable copy created to passed into it (which would be a processing overhead which the majority of users aren't going to be using). However this additional processing could be done conditionally only if an interceptor has been configured and it would be much cleaner interface from the usage perspective,

=========================
EF Core version: 7.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0

**Comment by ajcvickers** [comment] 2024-03-14 07:47
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-03-14 07:47 UTC
Labels: customer-reported, area-interception
