### ISSUE TITLE
GroupBy query using a named type for the result is executed locally.

### ISSUE THREAD

**Issue by mburbea** [dotnet/efcore#15379] opened 2019-04-16 18:02 UTC
I'm targeting Sql Server. 
I have an object that I'd like to select out with many projected aggregates. If the object in question being selected is an anonymous object than everything is evaluated on the server. If however, the object being projected to is a named object then many queries are run. This is problematic as the ungrouped result may have millions of rows. Here is a cut down example.

### Steps to reproduce
Add the following table to some sql database:
```sql
create table Cell
(
    CellId int not null primary key clustered,
    RowId int not null,
    Quality varchar(50) not null,
    Measure1 float not null,
    Measure2 float not null,
)

Create table Row
(
    RowId int not null primary key clustered,
    Weight int not null
)
```
Add these models
```c#
    public class Cell
    {
        public int CellId { get; set; }
        public int RowId { get; set; }
        public string Quality { get; set; }
        public double Measure1 { get; set; }
        public double Measure2 { get; set; }
        public virtual Row Row { get; set; }
    }

    public class Row
    {
        public int RowId { get; set; }
        public int Weight { get; set; }
        public virtual ICollection<Cell> Cells { get; set; }
    }
    public class Result
    {
          public double WeightedMeasure1 { get;set; }
          public double WeightedMeasure2 { get;set; }
    }
```
Set up your context with the following relationship::
```
            modelBuilder.Entity<Cell>().HasOne(x => x.Row).WithMany(x => x.Cells).IsRequired();
```

Once set up execute the following code
```cs
var evaluatedOnClient = dbContext
.Cells
.Where(x=> x.Quality == "Horse")
.Select(x=> new Result
{
      WeightedMeasure1  = x.Row.Weight * x.Measure1,
      WeightedMeasure2  = x.Row.Weight * x.Measure2,
})
.GroupBy(x=> true)
.Select(x=> new Result{
WeightedMeasure1  =x.Sum(WeightedMeasure1),
WeightedMeasure2 = x.Sum(WeightedMeasure2)
})

var evaluatedOnDb = dbContext
.Cells
.Where(x=> x.Quality == "Horse")
.Select(x=> new 
{
      WeightedMeasure1  = x.Row.Weight * x.Measure1,
      WeightedMeasure2  = x.Row.Weight * x.Measure2,
})
.GroupBy(x=> true)
.Select(x=> new  {
WeightedMeasure1  =x.Sum(WeightedMeasure1),
WeightedMeasure2 = x.Sum(WeightedMeasure2)
})
```
I would expect the two to be evaluated on the server, but only the second one (using anonymous objects) is.
### Further technical details
EF Core version: 2.2.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1709
IDE: VS2017  15.9.7

**Comment by smitpatel** [comment] 2019-04-16 20:41
```C#
.Select(x=> new Result
{
      WeightedMeasure1  = x.Row.Weight * x.Measure1,
      WeightedMeasure2  = x.Row.Weight * x.Measure2,
})

**Comment by smitpatel** [comment] 2019-04-16 20:42
Duplicate of #8107

**Closed** 2022-10-16 14:17 UTC
Labels: closed-duplicate, customer-reported
