### ISSUE TITLE
Missing collection items in single query with unrelated nullable foreign key

### ISSUE THREAD

**Issue by danbergman** [dotnet/efcore#9953] opened 2017-10-03 17:07 UTC
I am having an odd issue that I think is related to not having lazy loading anymore.

I have and OrderType object:
```
public class OrderType
    {
        [Key]
        public int OrderTypeId { get; set; }

        public virtual ICollection<Stage> Stages { get; set; } = new HashSet<Stage>();
    }
```

And a Stage object:
```
public class Stage
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int StageId { get; set; }

        // FKs   
        public int? ParentStageId { get; set; }
        [ForeignKey("ParentStageId")]
        public virtual Stage ParentStage { get; set; }
         
        public int OrderTypeId { get; set; }
        [ForeignKey("OrderTypeId")]
        public virtual OrderType OrderType { get; set; }
    }
```

When I query my database with this command:
`var OrderType = _db.OrderTypes.Single(x => x.OrderTypeId == order.OrderTypeId);`

Then try to access OrderType.Stages, it has all of the objects expected except rows where ParentStageId is NULL. Any row with a NULL value in that NULLABLE field will not be returned by the query.

If I Eager load the Stages table like this:
`var OrderType = _db.OrderTypes.Include(x => x.Stages).Single(x => x.OrderTypeId == order.OrderTypeId);`

Then all the rows will be there, including the ones with NULL in the ParentStageId column. 

Does anyone have an explanation as to why this would be? I would expect if it was a Lazy loading issue, then the first query would return nothing in the collection, and the second query would include all of the rows. I cannot think of any reason why it would load all but the ones with NULL in the ParentStageId field.

Thanks
Dan

EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7 Pro x64 
IDE: Visual Studio 2017

**Comment by smitpatel** [comment] 2017-10-04 01:56
@danbergman - Are you running any other query using same db context instance? EF Core will automatically fix-up navigations if there are `Stage` entities being tracked in context instance which would point to the OrderType you queried.

**Comment by ajcvickers** [comment] 2017-10-11 18:19
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:52 UTC
Labels: closed-could-not-reproduce
