### ISSUE TITLE
Runtime error on string.StartsWith, string.EndsWith string.Contains  in lambda search filter with StringComparison

### ISSUE THREAD

**Issue by anupdg** [dotnet/efcore#27983] opened 2022-05-09 10:52 UTC
Using cosmos DB:

If I include string.StartsWith, string.EndsWith string.Contains in where clause and provide a StringComparison enum value in the method, it throws error method as -

The LINQ expression 'DbSet<Company>()
    .Where(c => c.Name.StartsWith(
        value: "Micro", 
        comparisonType: InvariantCulture))' could not be translated. Additional information: Translation of method 'string.StartsWith' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

Code-

```c#
    public class Company
    {
        public string id { get; set; } = Guid.NewGuid().ToString();
        public string? Name { get; set; }
    }

   public class CompaniesContext : DbContext
    {
        public DbSet<Company> Companies { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
                => optionsBuilder.UseCosmos(
                "https://test-data.documents.azure.com:443",
                "key",
                databaseName: "companies-data").
            LogTo(Console.WriteLine, Microsoft.Extensions.Logging.LogLevel.Information).
            EnableDetailedErrors().
            EnableSensitiveDataLogging();
        }
    }
```

Code to test:-

```c#
try
{
    var result = companiesContext.Companies.Where(c => **c.Name.StartsWith("Micro", StringComparison.InvariantCulture))**.ToList();
    foreach (var c in result)
    {
        Console.WriteLine(c);
    }
}
catch (Exception ex)
{
}
```

Stack traces:-

```
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& ) in C:\JF\efcore\src\EFCore\Query\QueryableMethodTranslatingExpressionVisitor.cs:line 108
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in C:\JF\efcore\src\EFCore\Query\QueryableMethodTranslatingExpressionVisitor.cs:line 491
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosQueryableMethodTranslatingExpressionVisitor.Visit(Expression expression) in C:\JF\efcore\src\EFCore.Cosmos\Query\Internal\CosmosQueryableMethodTranslatingExpressionVisitor.cs:line 140
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in C:\JF\efcore\src\EFCore\Query\QueryableMethodTranslatingExpressionVisitor.cs:line 121
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosQueryableMethodTranslatingExpressionVisitor.Visit(Expression expression) in C:\JF\efcore\src\EFCore.Cosmos\Query\Internal\CosmosQueryableMethodTranslatingExpressionVisitor.cs:line 140
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) in C:\JF\efcore\src\EFCore\Query\QueryCompilationContext.cs:line 189
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async) in C:\JF\efcore\src\EFCore\Storage\Database.cs:line 76
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in C:\JF\efcore\src\EFCore\Query\Internal\QueryCompiler.cs:line 111
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0() in C:\JF\efcore\src\EFCore\Query\Internal\QueryCompiler.cs:line 95
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in C:\JF\efcore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 74
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in C:\JF\efcore\src\EFCore\Query\Internal\QueryCompiler.cs:line 91
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in C:\JF\efcore\src\EFCore\Query\Internal\EntityQueryProvider.cs:line 78
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator() in C:\JF\efcore\src\EFCore\Query\Internal\EntityQueryable`.cs:line 90
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in C:\JF\POCs\POCs\New folder\CosmosEntityFrameworkPOC\Program.cs:line 10
```

**string.EndsWith string.Contains  has the similar issue.**

EF Core version: 6
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022

**Comment by roji** [comment] 2022-05-09 11:30
Duplicate of #25250

**Comment by roji** [comment] 2022-05-09 11:30
@anupdg you can see which function translations are currently supported on [this page of the docs](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/functions#string-functions).

**Comment by anupdg** [comment] 2022-05-09 12:26
This is not a duplicate issue. Rather an enhancement of the issue.
The [this](https://github.com/dotnet/efcore/pull/19563/files) PR works for methods like-
var result = companiesContext.Companies.Where(c => c.Name.StartsWith("Micro")).ToList();

but fails for -
var result = companiesContext.Companies.Where(c => c.Name.StartsWith("Micro", StringComparison.InvariantCulture)).ToList();

Notice the number of parameters.

**Comment by anupdg** [comment] 2022-05-09 12:35
> @anupdg you can see which function translations are currently supported on [this page of the docs](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/functions#string-functions).

Possibly it's not a duplicate, I don't see the support of the following 6 cases for cosmos from [this page of the docs](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/functions#string-functions) @roji, as you suggested.

**Comment by roji** [comment] 2022-05-09 12:52
@anupdg that page only lists the overloads of StartsWith/EndsWith which don't accept a StringComparison parameter (note string.Equals which does).

I renamed #25250 to make it clear that it covers StartsWith/EndsWith as well.

**Comment by anupdg** [comment] 2022-05-09 13:39
> @anupdg that page only lists the overloads of StartsWith/EndsWith which don't accept a StringComparison parameter (note string.Equals which does).
> 
> I renamed #25250 to make it clear that it covers StartsWith/EndsWith as well.

Great, thanks

**Closed** 2022-10-16 20:33 UTC
Labels: closed-duplicate, customer-reported
