### ISSUE TITLE
Invalid SQL query being generated when passing list of enums

### ISSUE THREAD

**Issue by SBFrancies** [dotnet/efcore#19598] opened 2020-01-15 15:42 UTC
When using `someListOfEnums.Cast<int>() ` in a `Where` clause with `.Contains` incorrect SQL is generated.

### Steps to reproduce

``` SQL
CREATE DATABASE Fruit

USE Fruit

CREATE TABLE Fruit
(
Id INT NOT NULL PRIMARY KEY,
Value INT NOT NULL,
)

INSERT INTO Fruit VALUES (1, 0)
INSERT INTO Fruit VALUES (3, 2)
```

``` C#
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

namespace ConsoleApp
{
    public class Program
    {https://guides.github.com/features/mastering-markdown/
        static void Main(string[] args)
        {
            FruitTable.TestMethod(new FruitContext());
        }

        public enum Fruit
        {
            Apple,
            Banana,
            Orange
        }

        public class FruitTable
        {
            public int Id { get; set; }
            public int Value { get; set; }

            public static void TestMethod(FruitContext context)
            {
                IEnumerable<Fruit> list = new Fruit[] {Fruit.Apple, Fruit.Orange};

                var breaks = list.Cast<int>();
                var works = list.Select(a => (int) a);

                var fruits1 = context.Fruit.Where(a => works.Contains(a.Value)).ToList(); //This works
                var fruits2 = context.Fruit.Where(a => breaks.Contains(a.Value)).ToList(); //This breaks
            }
        }

        public class FruitContext : DbContext
        {
            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer("Server=.;Database=fruit;Trusted_Connection=True;ConnectRetryCount=0");
            }

            public DbSet<FruitTable> Fruit { get; set; }
        }
    }
}

```

Got Exceptions? Include both the message and the stack trace

```
-->'Invalid column name 'Orange'. Invalid column name 'Apple'.'

   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConsoleApp.Program.FruitTable.TestMethod(FruitContext context) line 43
   at ConsoleApp.Program.Main(String[] args) line 15
```

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: e.g. .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.2

**Comment by ajcvickers** [comment] 2020-01-16 20:48
@roji @maumar Thoughts on this?

**Comment by roji** [comment] 2020-01-16 21:47
I just spent quite a bit of time on this area in the PostgreSQL provider, I can investigate this one.

**Comment by roji** [comment] 2020-01-17 13:33
This turned out to have nothing to do with my PG enum/array/Contains stuff, but did some investigation anyway.

```c#
var breaks = list.Cast<int>();
var fruits2 = ctx.Fruit.Where(a => breaks.Contains(a.Value)).ToList();
```

In the incoming LINQ query tree for this, the `breaks` closure constant (which gets parameterized) is a simple constant array of Fruit, with the `Cast<int>()` stripped away. I suspect this happens at some level because the Cast doesn't actually do anything, since the enum has int as its underlying type. So it's a somewhat weird situation where the FieldExpression and its FieldInfo have type IEnumerable<int>, but the type of the corresponding member on its Expression's value is of type Fruit[]. When the Fruit[] makes its way to InExpression expansion in NullabilityBasedSqlProcessingExpressionVisitor, the enum's label gets computed instead of the value.

We could detect this specifically when extracting parameters and handle it in EvaluatableExpressionFindingExpressionVisitor.VisitMember. Will wait for @smitpatel to return and validate the analysis and approach, this also is very non-urgent (has an easy workaround etc.).

**Comment by ajcvickers** [comment] 2020-01-17 19:46
Note from team discussion: the workaround here is to use `ToList`.

**Comment by ajcvickers** [comment] 2020-11-06 19:57
@smitpatel to de-dupe.

**Comment by smitpatel** [comment] 2020-11-30 22:21
Duplicate of #16098

**Closed** 2022-10-16 18:06 UTC
Labels: customer-reported, area-query
