### ISSUE TITLE
Table splitting isn't working with nonnullable reference types.

### ISSUE THREAD

**Issue by bperc2** [dotnet/efcore#18574] opened 2019-10-24 15:25 UTC
With Nullable Reference Types turned on, Entity Framework Core is unable to map two nonnullable reference types to the same column of a table.  

### Steps to reproduce

To reproduce this issue, I modified the table splitting example of the EF Core documentation: https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting

``` C#
    public class Order
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public OrderStatus? Status { get; set; }
        public DetailedOrder DetailedOrder { get; set; }
    }
```

``` C#
    public class DetailedOrder
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public OrderStatus? Status { get; set; }
        public string BillingAddress { get; set; }
        public string ShippingAddress { get; set; }
        public byte[] Version { get; set; }
    }
```

``` C#
    modelBuilder.Entity<DetailedOrder>(dob =>
    {
        dob.ToTable("Orders");
        dob.Property(o => o.Category).HasColumnName("Category");
        dob.Property(o => o.Status).HasColumnName("Status");
    });

    modelBuilder.Entity<Order>(ob =>
    {
        ob.ToTable("Orders");
        ob.Property(o => o.Category).HasColumnName("Category");
        ob.Property(o => o.Status).HasColumnName("Status");
        ob.HasOne(o => o.DetailedOrder).WithOne()
            .HasForeignKey<DetailedOrder>(o => o.Id);
    });
```

With this setup, adding a migration will fail with the following error message:

'DetailedOrder.Category' and 'Order.Category' are both mapped to column 'Category' in 'Orders' but are configured with different nullability.

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by AndriySvyryd** [comment] 2019-10-24 16:03
@bperc2 This is not supported yet.

Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/12100

**Comment by flcdrg** [comment] 2019-11-27 03:25
This is a regression from 2.2 where this *did* work.

**Closed** 2022-10-16 14:52 UTC
Labels: closed-duplicate, customer-reported

**Comment by ajcvickers** [comment] 2023-03-08 11:50
@sbojarczak Please open a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
