### ISSUE TITLE
Calling SqliteConnection from Microsoft.Data.Sqlite v6.0.0 throws TypeInitializationException

### ISSUE THREAD

**Issue by faburaya** [dotnet/efcore#26729] opened 2021-11-17 19:28 UTC
I have just upgraded the nuget package Microsoft.Data.Sqlite to version 6.0.0 and this code
```
        public IDbConnection OpenOrCreateDatabase(string databaseFilePath)
        {
            string connectionString = new SqliteConnectionStringBuilder()
            {
                Mode = SqliteOpenMode.ReadWriteCreate,
                Cache = SqliteCacheMode.Shared,
                DataSource = databaseFilePath
            }.ToString();

            return new SqliteConnection(connectionString);
        }
```
now fails with the exception reported below
```
[xUnit.net 00:00:01.41]       System.TypeInitializationException : The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
[xUnit.net 00:00:01.41]       ---- System.NullReferenceException : Object reference not set to an instance of an object.
[xUnit.net 00:00:01.41]       Stack Trace:
[xUnit.net 00:00:01.41]            at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
[xUnit.net 00:00:01.41]         D:\a\1\s\Reusable.DataAccess.Sqlite\SqliteDatabaseCreationHelper.cs(56,0): at Reusable.DataAccess.Sqlite.SqliteDatabaseCreationHelper.OpenOrCreateDatabase(String databaseFilePath)
[xUnit.net 00:00:01.41]         D:\a\1\s\Reusable.DataAccess.Sqlite.IntegrationTests\SqliteDatabaseFixture.cs(17,0): at Reusable.DataAccess.Sqlite.IntegrationTests.SqliteDatabaseFixture..ctor()
[xUnit.net 00:00:01.41]         D:\a\1\s\Reusable.DataAccess.Sqlite.IntegrationTests\SqliteDatabaseCreationHelperTest.cs(22,0): at Reusable.DataAccess.Sqlite.IntegrationTests.SqliteDatabaseCreationHelperTest..ctor()
[xUnit.net 00:00:01.41]         ----- Inner Stack Trace -----
[xUnit.net 00:00:01.41]            at Microsoft.Data.Sqlite.Utilities.ApplicationDataHelper.GetFolderPath(String propertyName)
[xUnit.net 00:00:01.41]            at Microsoft.Data.Sqlite.Utilities.ApplicationDataHelper.get_LocalFolderPath()
[xUnit.net 00:00:01.41]            at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
[xUnit.net 00:00:01.41]            at Microsoft.Data.Sqlite.SqliteConnection..cctor()
```
If I rollback to package version 5.0.12, then it works normally again.

This bug can be reproduced by running `Reusable.DataAccess.Sqlite.IntegrationTests` from this build of my project:
https://github.com/faburaya/dotNetReusable/commit/b085274e8126bb22a5d0b720b8aa9ef63c73849c

Further details of the failure can be found here:
https://dev.azure.com/faburaya/Reusable.NET/_build/results?buildId=15&view=results

**Comment by jonreis** [comment] 2021-11-18 02:43
I am having the same issue using .NET Framework non-sdk style projects and AnyCPU. 

I thought it was a bug in SQLitePCLRaw.bundle_e_sqlcipher that was fixed in v2.0.7 but I have included that version (see: https://github.com/ericsink/SQLitePCL.raw/issues/451) and I am still seeing the same issue.

**Comment by ajcvickers** [comment] 2021-11-18 09:48
@faburaya @jonreis This looks like a duplicate of #26574, which is fixed for the 6.0.1 release. Can you try with the [daily build](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md), which is EF7, but contains the fixes for 6.0.1, and report back?

**Comment by jonreis** [comment] 2021-11-18 20:49
@ajcvickers I can confirm this works fine in version: 7.0.0-alpha.1.21568.2. Thank you.

**Comment by faburaya** [comment] 2021-11-18 23:45
@ajcvickers ,
I will not be able to test this patch since I cannot leave netcore v3.1.
But it seems like you really have the fix.
I will wait for the next stable nuget package.

**Comment by ajcvickers** [comment] 2021-11-19 08:28
@faburaya Microsoft.Data.Sqlite in the daily feed will still run on .NET Core 3.1. It's only the EF stuff that requires .NET 6.

**Closed** 2022-10-16 20:15 UTC
Labels: customer-reported
