### ISSUE TITLE
[Regression] Cannot query entity with composite primary key containing collection of owned types

### ISSUE THREAD

**Issue by Neme12** [dotnet/efcore#23401] opened 2020-11-19 17:09 UTC
### Steps to reproduce
1. Start with this project file and a C# file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0" />
  </ItemGroup>

</Project>
```

```C#
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace EfCore5Test
{
    public sealed class ModuleLocalization
    {
        public Guid ModuleId { get; set; }

        public string LanguageCode { get; set; }

        public IList<FileItem> Screenshots { get; set; }
    }

    public sealed class FileItem
    {
        public int Order { get; set; }
    }

    public sealed class ApplicationDbContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=aspnet-WebApplication-6E483A89-BEE6-4A76-96CC-CEB276E5E112;Trusted_Connection=True;MultipleActiveResultSets=true");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<ModuleLocalization>(builder =>
            {
                builder.HasKey(x => new { x.ModuleId, x.LanguageCode });

                builder.Property(x => x.ModuleId).IsRequired();
                builder.Property(x => x.LanguageCode).IsRequired().IsUnicode(false).HasMaxLength(35);

                builder.OwnsMany(x => x.Screenshots);
            });
        }

        public DbSet<ModuleLocalization> ModuleLocalizations { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new ApplicationDbContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                context.ModuleLocalizations.FirstOrDefault(); // This line crashes. :(
            }
        }
    }
}
```
2. Run. An exception is thrown:
```
Unhandled exception. System.InvalidOperationException: The LINQ expression 'ShapedQueryExpression:
    QueryExpression:
        Projection Mapping:
            EmptyProjectionMember -> [EntityProjectionExpression]
        SELECT 1
        FROM FileItem AS f
    ShaperExpression: EntityShaperExpression:
            EntityType: FileItem
            ValueBufferExpression:
                ProjectionBindingExpression: EmptyProjectionMember
            IsNullable: False

    .Where(namelessParameter{0} => new object[]
    {
        (object)EF.Property<Nullable<Guid>>(EntityShaperExpression:
            EntityType: ModuleLocalization
            ValueBufferExpression:
                ProjectionBindingExpression: EmptyProjectionMember
            IsNullable: False
        , "ModuleId"),
        (object)EF.Property<string>(EntityShaperExpression:
            EntityType: ModuleLocalization
            ValueBufferExpression:
                ProjectionBindingExpression: EmptyProjectionMember
            IsNullable: False
        , "LanguageCode")
    } != null && new object[]
    {
        (object)EF.Property<Nullable<Guid>>(EntityShaperExpression:
            EntityType: ModuleLocalization
            ValueBufferExpression:
                ProjectionBindingExpression: EmptyProjectionMember
            IsNullable: False
        , "ModuleId"),
        (object)EF.Property<string>(EntityShaperExpression:
            EntityType: ModuleLocalization
            ValueBufferExpression:
                ProjectionBindingExpression: EmptyProjectionMember
            IsNullable: False
        , "LanguageCode")
    } == new object[]
    {
        (object)EF.Property<Nullable<Guid>>(namelessParameter{0}, "ModuleLocalizationModuleId"),
        (object)EF.Property<string>(namelessParameter{0}, "ModuleLocalizationLanguageCode")
    })' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.TranslateSubquery(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at EfCore5Test.Program.Main(String[] args) in C:\Users\SimonaKonickova\source\repos\EfCore5Test\EfCore5Test\Program.cs:line 57
```
It seems that to reproduce this, the owning entity type has to have a primary key of more than 1 column.
This worked properly in EF Core 3.1 - downgrading the Microsoft.EntityFrameworkCore.SqlServer package makes this work.

This is kind of a huge regression and makes collections of owned entities basically unusable for us (even the simplest of queries fails) and prevents us from upgrading. Is there any reasonable workaround?

### Include provider and version information

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10 Version 1909
IDE: Visual Studio 16.9.0 Preview 1.0

**Comment by smitpatel** [comment] 2020-11-19 17:41
Duplicate of #23130

**Closed** 2022-10-16 19:10 UTC
Labels: customer-reported
