### ISSUE TITLE
Provide support to Update Alternate Keys

### ISSUE THREAD

**Issue by ThiagoDaher** [dotnet/efcore#19336] opened 2019-12-17 04:02 UTC
By database design, some tables uses composite keys, as values are populated by businesses keys.
This strategy can take additional storage needs, but is very efficient in search.
However, EF does not allows update of value as sql server does (update Specification set Name = 'specification 1.2' where Name = 'Specification 1'; -- consider name as Unique Key).

Update in cascade is also desired in this scenario, as foreign key tables were created with update cascade in sql.

**Comment by ajcvickers** [comment] 2019-12-17 18:57
Duplicate of #4073 and #10551

**Closed** 2022-10-16 18:01 UTC
Labels: customer-reported
