### ISSUE TITLE
The 'MySqlDateTimeTypeMapping' does not support value conversions. Support for value conversions typically requires changes in the database provider.

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#13790] opened 2018-10-27 21:47 UTC
dotnet ef migrations add ...

Error occurs running 2.2.0-preview3-35497.
Reverting to 2.1.4 fixes it.

Also installed:  Pomelo.EntityFrameworkCore.MySql v2.1.2

Exception:

	   System.NotImplementedException: The 'MySqlDateTimeTypeMapping' does not support value conversions. Support for value conversions typically requires changes in the database provider.

**Comment by ajcvickers** [comment] 2018-10-29 16:03
@sam-wheat Can you post the code that works on 2.1.4 and fails on 2.2?

**Comment by sam-wheat** [comment] 2018-10-29 18:05
Well it's my entire DbContext and model and supporting objects which is pretty large and not something I want to post.  I posted the entire stack trace in my original post - something I should not have done.  You can look in the edits and see the original post.
 
The last line of my code referenced in the stack trace is:
    
    ChangeTracker.AutoDetectChangesEnabled = false;

Does this help?  

	System.NotImplementedException: The 'MySqlDateTimeTypeMapping' does not support value conversions. Support for value conversions typically requires changes in the database provider.
	at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.Clone(RelationalTypeMappingParameters parameters)
	at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.Clone(RelationalTypeMappingInfo& mappingInfo)
	at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlTypeMappingSource.FindMapping(RelationalTypeMappingInfo& mappingInfo)
	at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.<FindMappingWithConversion>b__7_0(ValueTuple`3 k)
	at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
	at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo& mappingInfo, IReadOnlyList`1 principals)
	at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(IProperty property)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.TypeMappingConvention.Apply(InternalModelBuilder modelBuilder)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
	at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
	at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
	at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
	at System.Lazy`1.CreateValue()
	at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
	at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
	at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
	at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
	at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
	at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
	at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
	at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
	at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
	at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()

**Comment by smitpatel** [comment] 2018-10-29 18:50
Duplicate of #13657

**Closed** 2022-10-16 13:37 UTC
Labels: closed-duplicate, customer-reported
