### ISSUE TITLE
Query: discriminator predicate can be pulled out of subquery for some cases (cross join or inner join)

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#16081] opened 2019-06-13 22:16 UTC
example query:

```cs
from g1 in gs
from g2 in gs
select g1.LeaderNickname != null ? g2.LeaderNickname : (string)null);
```

current sql:
```sql
SELECT CASE
    WHEN [t].[LeaderNickname] IS NOT NULL THEN [t0].[LeaderNickname]
    ELSE NULL
END
FROM (
    SELECT [g].[Nickname], [g].[SquadId], [g].[AssignedCityName], [g].[CityOrBirthName], [g].[Discriminator], [g].[FullName], [g].[HasSoulPatch], [g].[LeaderNickname], [g].[LeaderSquadId], [g].[Rank]
    FROM [Gears] AS [g]
    WHERE [g].[Discriminator] IN (N'Gear', N'Officer')
) AS [t]
CROSS JOIN (
    SELECT [g0].[Nickname], [g0].[SquadId], [g0].[AssignedCityName], [g0].[CityOrBirthName], [g0].[Discriminator], [g0].[FullName], [g0].[HasSoulPatch], [g0].[LeaderNickname], [g0].[LeaderSquadId], [g0].[Rank]
    FROM [Gears] AS [g0]
    WHERE [g0].[Discriminator] IN (N'Gear', N'Officer')
) AS [t0]
```

possible optimization:

```sql
SELECT CASE
    WHEN [g1].[LeaderNickname] IS NOT NULL
    THEN [g2].[LeaderNickname] ELSE NULL
END
FROM [Gears] AS [g1]
CROSS JOIN [Gears] AS [g2]
WHERE [g1].[Discriminator] IN (N'Officer', N'Gear') AND [g2].[Discriminator] IN (N'Officer', N'Gear') 
```

**Comment by smitpatel** [comment] 2019-08-23 00:37
Duplicate of #17161

**Closed** 2022-10-16 14:25 UTC
