### ISSUE TITLE
SQLite: unable to apply Identity Schema Migration

### ISSUE THREAD

**Issue by jwdavidson** [dotnet/efcore#2984] opened 2015-09-02 16:50 UTC
All attempts in beta6-13815 to apply an Identity schema migration for SQLite fail with a Specified cast is invalid. This happens in both the commandline and application based ApplyMigrations. Issue #2983 may pay a part.

It is however possible to apply the Identity schema migration for SqlServer to an SQLite database, however it does not work correctly as the Id columns do not have the necessary AutoIncrement argument.

**Comment by jwdavidson** [comment] 2015-09-02 17:56
It looks like the fix for #2545 may address this as well. Will check as soon as beta7 is released.

**Comment by rowanmiller** [comment] 2015-09-11 18:21
@natemcmaster can you verify this is fixed now

**Comment by natemcmaster** [comment] 2015-09-11 18:23
Yes, it was fixed in beta7. I verified when writing docs for our beta7 release. 
This is a duplicate of https://github.com/aspnet/EntityFramework/issues/2545.

**Closed** 2022-10-16 09:06 UTC
