### ISSUE TITLE
Query root of type 'FromSqlQueryRootExpression' wasn't handled by provider code. This issue happens when using a provider specific method on a different provider where it is not supported.

### ISSUE THREAD

**Issue by mohankumarbandaru** [dotnet/efcore#31023] opened 2023-06-03 01:40 UTC
## File a bug
When I upgrade the Microsoft.EntityFrameworkCore (7.0.5) and Microsoft.EntityFrameworkCore.SqlServer(7.0.5) in Core Project . I am getting below issue when we executed the unit test cases . before upgrade it was working.

**Query root of type 'FromSqlQueryRootExpression' wasn't handled by provider code. This issue happens when using a provider specific method on a different provider where it is not supported.**

Here is the stack trace :

at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at

**Comment by ajcvickers** [comment] 2023-06-03 10:26
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by roji** [comment] 2023-06-03 11:47
@mohankumarbadnaru as @ajcvickers wrote, it's difficult to tell exactly what you're doing without a code sample. However, it seems that you're trying to use SQL queries (FromSql) with the InMemory provider - that isn't supported and shouldn't have worked in older versions either; InMemory does not and cannot support SQL.

**Comment by mohankumarbadnaru** [comment] 2023-06-05 15:14
Here is the bit of code 
                var XXXXX = await _dbContext.Query_XXX.FromSqlRaw(@"SELECT * from Customer"
                                                , new SqlParameter("@CustomerId", requestBody.CustomerId))
				    .AsNoTracking()
                                    .ToListAsync();

I will share you the same project with unit test cases project

**Comment by ajcvickers** [comment] 2023-06-26 14:46
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-06-26 14:46 UTC
Labels: customer-reported
