### ISSUE TITLE
Issues with projected queries/subqueries when combined with composite keys

### ISSUE THREAD

**Issue by Erythnul** [dotnet/efcore#23898] opened 2021-01-15 13:44 UTC
Hey guys,

We're working towards being able to upgrade our landscape of services to .NET 5 + EF Core 5 and have been running some test scenarios. We run our services against a legacy database created and maintained by our DBAs, it heavily uses composite keys.

I found https://github.com/dotnet/efcore/issues/23671, which is a variant on my issue, but doesn't use projection, which looks like it allows for a workaround. My scenario doesn't really seem to work with the workaround mentioned there, nor do I think that the workaround is preferable in this case.

I would like to ask you to check the reproduction code and advise me on how to proceed.
A snippet from the reproduction repo:
```
//This is the LINQ as generated by AutoMapper
compositeKeyContext.Orders.AsNoTracking()
    .Where(x => x.Id == Program.orderId)
    .Select(
        dtoOrder => new
        {
            __MostImportantOrderLine = dtoOrder.OrderLines.FirstOrDefault(x => ((int?)x.OrderLineNumber) == dtoOrder.MostImportantOrderLine),
            Id = dtoOrder.Id
        })
    .Select(
        dtoLet => new OrderModel
        {
            MostImportantOrderLine = (dtoLet.__MostImportantOrderLine == null)
                ? null
                : new OrderLineModel
                {
                    Description = dtoLet.__MostImportantOrderLine.Description,
                    OrderLineId = dtoLet.__MostImportantOrderLine.Id
                },
            OrderId = (Guid?)dtoLet.Id
        });
```

I'm beginning to fear that the fact that https://github.com/dotnet/efcore/issues/23671 was closed as by design means that we will not be able to upgrade to EF Core 5 without a database overhaul, which I believe will not happen with our current DB.

If this is the case, I would like to ask you to reconsider fixing this instead of just changing the exception, so that these kind of scenarios can be supported in EF Core 5+.

Thanks in advance!

### Code
I've made a reproduction repository with an extremely simplified version of things that can go on in our code at times:
https://github.com/Erythnul/EFCoreIssueReproduction

### Stack trace

```
The LINQ expression 'Projection Mapping:
    EmptyProjectionMember -> [EntityProjectionExpression]
SELECT TOP(1) o.CompanyId, o.CustomerId
FROM compkey.OrderLine AS o
WHERE ((((o.CompanyId != NULL) && (o.CustomerId != NULL)) && (o.OrderId != NULL)) && (((o.CompanyId == o.CompanyId) && (o.CustomerId == o.CustomerId)) && (o.OrderId == o.OrderId))) && (o.OrderLineNumber == o.MostImportantOrderLine)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```
```
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.ScalarSubqueryExpression.Verify(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.ScalarSubqueryExpression..ctor(SelectExpression subquery)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.BindProperty(EntityReferenceExpression entityReferenceExpression, IProperty property)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TryBindMember(Expression source, MemberIdentity member)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TryRewriteEntityEquality(ExpressionType nodeType, Expression left, Expression right, Boolean equalsMethod, Expression& result)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitConditional(ConditionalExpression conditionalExpression)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EfCoreRepro.Program.Main(String[] args) in C:\Source\Git\EFCoreIssueReproduction\EFCore5\Program.cs:line 63
```

### Version information

EF Core version: 5.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0

**Comment by smitpatel** [comment] 2021-01-19 18:46
Duplicate of #23671 
Rewrite `dtoLet.__MostImportantOrderLine == null` to compare on the relevant properties being null like `dtoLet.__MostImportantOrderLine.Id == null`. You can combine multiple properties if composite key with `||`.

Earlier working behavior was either client eval or a bug if it evaluates to server and we cannot revert to it.

**Comment by Erythnul** [comment] 2021-01-19 18:50
@smitpatel thank you for your reply. I'll start an issue on the AutoMapper github to see if they will adjust to this new functionality instead.

**Comment by snappyfoo** [comment] 2021-04-10 00:31
I am dealing with the same problem but struggling to find a workaround and would greatly appreciate if anyone is able to give any pointers. @Erythnul I saw the suggestion in the linked AutoMapper issue but I'm not sure where to put "AllowNulls" as a few places I've put it don't see to have an effect. Here is a simple repo. Thank you.

<details>
<summary>Code</summary>

```C#
public class Program
{
    public static void Main(string[] args)
    {
        var mapConfig = new MapperConfiguration(x =>
        {
            x.CreateMap<Person, PersonDto>()
                .ForMember(d => d.FirstHome, o => o.MapFrom(e => e.Homes.FirstOrDefault()));

            x.CreateMap<Home, HomeDto>();
        });

        using var context = new MyContext();

        context.Database.EnsureDeleted();
        context.Database.EnsureCreated();

        context.Add(
            new Person
            {
                Name = "Bob",
                Homes = new[] {new Home {Name = "My First Home"}}
            });

        context.SaveChanges();

        var peopleFirstHomes = context.People
            .ProjectTo<PersonDto>(mapConfig)
            .ToList();
    }

    public abstract class Entity
    {
        public int TenantId { get; set; }
        public int Id { get; set; }
    }

    public class Person : Entity
    {
        public string Name { get; set; }
        public IEnumerable<Home> Homes { get; set; }
    }

    public class Home : Entity
    {
        public string Name { get; set; }
        public Person Person { get; set; }
    }

    public class PersonDto
    {
        public string Name { get; set; }
        public HomeDto FirstHome { get; set; }
    }

    public class HomeDto
    {
        public string Name { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Person> People { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var loggerFactory = new LoggerFactory();
            loggerFactory.AddProvider(new DebugLoggerProvider());

            optionsBuilder
                .UseSqlServer("Server=.;Database=FirstOrDefault;Trusted_Connection=True")
                .UseLoggerFactory(loggerFactory);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Person>().HasKey(x => new {x.TenantId, x.Id});
            modelBuilder.Entity<Home>().HasKey(x => new {x.TenantId, x.Id});
        }
    }
}
```
</details>

**Comment by snappyfoo** [comment] 2021-04-10 00:42
OK, I think I misinterpretted that AllowNull comment. The addition of `DoNotAllowNull()` in the mapping is what worked for me. Will show here in case it helps someone else:

```C#
 x.CreateMap<Person, PersonDto>()
    .ForMember(d => d.FirstHome, o =>
    {
        o.DoNotAllowNull();
        o.MapFrom(e => e.Homes.FirstOrDefault());
    });
```

```SQL
SELECT (
    SELECT TOP(1) [h].[Name]
    FROM [Home] AS [h]
    WHERE ([p].[TenantId] = [h].[PersonTenantId]) AND ([p].[Id] = [h].[PersonId])) AS [Name], [p].[Name]
FROM [People] AS [p]
```

**Closed** 2022-10-16 19:18 UTC
Labels: closed-duplicate, customer-reported
