### ISSUE TITLE
EF7 beta 6 LINQ where clause with related entity condition fails

### ISSUE THREAD

**Issue by diegoernestofarias** [dotnet/efcore#2933] opened 2015-08-27 03:55 UTC
Hi guys,

I'm using EF7 beta 6 (code first), and I have this environment:

Country Entity:
![00-country](https://cloud.githubusercontent.com/assets/13974867/9512181/0f2d8718-4c55-11e5-8626-f68eb673dde5.png)

Region Entity:
![01-region](https://cloud.githubusercontent.com/assets/13974867/9512190/19ec3b40-4c55-11e5-9949-6e1f264289bd.png)

Model Builder fluent configuration:
![03-modelbuilder-fluent-country](https://cloud.githubusercontent.com/assets/13974867/9512192/1ee3109c-4c55-11e5-85dc-f28360495670.png)

![04-modelbuilder-fluent-region](https://cloud.githubusercontent.com/assets/13974867/9512195/251d81f4-4c55-11e5-9afd-d947a2a305d0.png)

My original LINQ where expression:
![05-linq-where](https://cloud.githubusercontent.com/assets/13974867/9512207/29d52f6c-4c55-11e5-9c8f-2234add6a1e1.png)

If I inspect the Region DbSet, i have only 1 region:
![06-only1region](https://cloud.githubusercontent.com/assets/13974867/9513036/e9a9318e-4c60-11e5-9172-0599bf68784f.png)

But when the expression is evaluated, fails ("Sequence contains more than one matching element"): 
![07-ef7b6-where-fail](https://cloud.githubusercontent.com/assets/13974867/9513040/f158a5b8-4c60-11e5-94c0-ebb2ecd1b8e6.png)

If I modify the LINQ expression, not using the related entity in the where clause, it works:
![08-exprchange](https://cloud.githubusercontent.com/assets/13974867/9512214/3d767f80-4c55-11e5-9dfc-5b6fca57b122.png)

![09-works](https://cloud.githubusercontent.com/assets/13974867/9513042/fa2c15f8-4c60-11e5-9430-70f6be53afcf.png)

What you could be happening?
Any ideas?

**Comment by divega** [comment] 2015-08-27 06:03
@diegoernestofarias thanks for the detailed report. The expression `r.Country.Name` in your original query refers to a navigation property. Navigation property translation is being worked on. Most of this functionality will light up in the upcoming beta7. Otherwise you can try to use our nightly builds.

**Comment by divega** [comment] 2015-08-27 06:06
BTW, it would be great if you could try with a recent build and confirm that it works.

**Comment by divega** [comment] 2015-08-27 06:08
Possible dupe of #325.

**Comment by diegoernestofarias** [comment] 2015-08-27 14:13
Yes is a dupe! Totally clear in the roadmap:
Navigation property translation allows dotting thru navigation properties in LINQ (e.g. Products.Where(p => p.Category.Name == "Food"))

I made an attempt to try a more recent build, but I could not, because in this moment I am working with "dnx451" and some of the assemblies that I need (EntityFramework.SqlServer and EntityFramework.Commands) are not being compiled for this version of the framework. (I am right?)

**Comment by divega** [comment] 2015-08-27 14:33
@bricelam may be able to answer on whether we are compiling for dnx451.

**Comment by diegoernestofarias** [comment] 2015-08-27 14:54
I'll wait for the beta7, for now I'll go this way (very ugly, but safe :sob:):
http://blog.coderinserepeat.com/2015/01/20/combining-ef6-with-asp-net -5/

**Comment by bricelam** [comment] 2015-08-27 19:53
The `net45` build of those packages will be used when running on `dnx451`.

**Closed** 2022-10-16 09:06 UTC
