### ISSUE TITLE
How do we call stored procedures in .NET Core 3.0?

### ISSUE THREAD

**Issue by daver77** [dotnet/efcore#18186] opened 2019-10-02 13:42 UTC
I'm upgrading a .NET Framework project to .NET Core 3.0 but can't get stored procedures to work and can't find any documentation on it.

I've added my model

```
    public partial class CarParkingContext : DbContext
    {
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<usp_ManualSpaceAvailable>().HasNoKey();
        }
    }
```

and my code to call the stored proc

```
  public usp_ManualSpaceAvailable GetAvailableSpaces(DateTime from, DateTime to)
        {
            return _dbContext.Set<usp_ManualSpaceAvailable>().
                          FromSqlRaw("dbo.usp_ManualSpaceAvailabile @from={0}, @to={1}", from, to).
                          SingleOrDefault();
        }
```

Now this just returns and error

> SqlException: Incorrect syntax near '@from'.

Can anyone help please or point me to some documentation

**Comment by smitpatel** [comment] 2019-10-02 17:29
Filed https://github.com/aspnet/EntityFramework.Docs/issues/1804 to mention in docs.

Essentially duplicate of #17558

**Comment by SifisoMazibuko** [comment] 2020-10-02 07:01
The reason could be that you not executing it, just add the keyword "exec before the dbo.usp_ManualSpaceAvailabile procedure name"

**Closed** 2022-10-16 14:47 UTC
Labels: customer-reported
