### ISSUE TITLE
NullReferenceException when filtering foreign key on null parent type

### ISSUE THREAD

**Issue by Eswel** [dotnet/efcore#13448] opened 2018-09-29 16:39 UTC
Hi, I am hitting a bug when using a foreign key as a where filter. 
This works: 
```c#
ctx.Children.Where(x => x.Parent == null).Count();
```
but this throws a NullReferenceException when evaluating the closure implicit parent item
```c#
Parent nullParent = null;
 var nbOrphans2 = ctx.Children.Where(x => x.Parent == nullParent).Count();.
```
Exception details: 
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , Parent )
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrPropertyGetter`2.GetClrValue(Object instance)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedPropertyRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at EFCoreParentChildNullRelationshipBugWithInt.Program.Main(String[] args) in C:\Users\ThierryDespres\source\repos\EFCoreParentChildNullRelationshipBugWithInt\Program.cs:line 20
```

### Steps to reproduce
Just run the following sample (after initializing database)
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace EFCoreParentChildNullRelationshipBugWithInt
{
    public class Parent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        // data for seeding repository
        public static Parent Parent1 => new Parent
        {
            Id = 1,
            Name = "First Parent",
        };
        public static Parent Parent2 => new Parent
        {
            Id = 2,
            Name = "Second Parent",
        };
        public static Parent[] InitialEntries => new[] { Parent1, Parent2, };
    }
     public class Child
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int? ParentId { get; set; }

        public Parent Parent { get; set; }

        // data for seeding repository
        public static Child Orphan1 => new Child()
        {
            Id = 11,
            Name = "John Doe",
            ParentId = null,
            //Parent = null
        };
        public static Child Orphan2 => new Child()
        {
            Id = 12,
            Name = "AnneOnyme",
            ParentId = null,
            //Parent = null
        };

        public static Child Child1 => new Child()
        {
            Id = 21,
            Name = "Bob",
            ParentId = Parent.Parent1.Id,
            //Parent = Parent.Parent1
        };
        public static Child[] InitialEntries => new[] { Orphan1, Orphan2, Child1 };
    }
    class MyContext : Microsoft.EntityFrameworkCore.DbContext
    {
        public MyContext()
        {

        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseSqlServer(@"Server=(localdb)\MSSQLLocalDB;Database=EFCoreParentChildNullRelationshipBug;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            var parentModel = modelBuilder.Entity<Parent>();
            var childModel = modelBuilder.Entity<Child>();
            childModel.HasOne(x => x.Parent).WithMany().HasForeignKey(x => x.ParentId);

            modelBuilder.Entity<Parent>().HasData(Parent.InitialEntries);
            modelBuilder.Entity<Child>().HasData(Child.InitialEntries);
        }

        public DbSet<Parent> Parents { get; set; }
        public DbSet<Child> Children { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                // this works
                var nbOrphans = ctx.Children.Where(x => x.Parent == null).Count();

                // this throws NullReferenceException
                Parent nullParent = null;
                var nbOrphans2 = ctx.Children.Where(x => x.Parent == nullParent).Count();
            }
        }
    }
}
```

### Further technical details
EF Core version: 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.5

**Comment by ajcvickers** [comment] 2018-10-01 16:17
Note for triage: looks like we're trying to get a FK property value from a null entity instance.

**Comment by smitpatel** [comment] 2018-10-01 21:38
Duplicate of #12062

**Closed** 2022-10-16 13:33 UTC
Labels: closed-duplicate, customer-reported
