### ISSUE TITLE
Model-level Entity Filter Navigation Properties

### ISSUE THREAD

**Issue by fileman** [dotnet/efcore#9491] opened 2017-08-20 12:26 UTC
Companion feature to Model-level Entity Filters. (#7413 and #7450). Allow use of navigation properties in query at the model level with "many-to-many" relationship.

builder.HasQueryFilter(c => !c.IsDeleted && c.User.Any(u => u.Id == MyDbContext.UserId))

**Comment by smitpatel** [comment] 2017-08-23 21:30
duplicate of #8881

**Closed** 2022-10-16 11:17 UTC
