### ISSUE TITLE
Nullable field that is a part of unique constraint scaffolded with IsRequired()

### ISSUE THREAD

**Issue by dmitrykolchev** [dotnet/efcore#9276] opened 2017-07-27 12:51 UTC
Table [share_type] has nullable field [stock_class_id] that is a part of unique constraint. 

``` sql
CREATE TABLE [stock].[share_type](
	[id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[state] [smallint] NOT NULL,
	[name] [nvarchar](256) NOT NULL,
	[stock_type_id] [int] NOT NULL,
	[stock_class_id] [int] NULL,
	[votes_per_share] [int] NOT NULL,
	[face_value] [decimal](26, 4) NOT NULL,
	[currency_id] [int] NOT NULL,
	[modified_by] [int] NOT NULL,
	[modified_date] [datetime2](7) NOT NULL,
	 CONSTRAINT [ak_share_type_all] UNIQUE NONCLUSTERED 
	(
		[stock_type_id] ASC,
		[stock_class_id] ASC,
		[votes_per_share] ASC,
		[face_value] ASC,
		[currency_id] ASC
	)
)

```
This field [stock_class_id] scaffolded with .IsRequired. This is unexpected behavior.
``` c#
                entity.Property(e => e.StockClassId)
                    .IsRequired()
                    .HasColumnName("stock_class_id");
```
Due to this behavior, ef generates invalid queries with INNER JOIN on this field.
linq query
``` c#
await (from item in db.ShareType
                .Include(z => z.StockType)
                .Include(z => z.StockClass)
                .Include(z => z.Currency)
        where item.Id == data.ShareTypeId
        select item).SingleAsync();
```
sql result
``` sql
SELECT TOP(2) [z].[id], [z].[currency_id], [z].[face_value], [z].[modified_by], [z].[modified_date], [z].[name], [z].[state], [z].[stock_class_id], [z].[stock_type_id], [z].[votes_per_share], [s].[id], [s].[name], [s0].[id], [s0].[name], [c].[id], [c].[code], [c].[comments], [c].[minor_unit], [c].[modified_by], [c].[modified_date], [c].[name], [c].[numeric_code], [c].[state]
FROM [stock].[share_type] AS [z]
INNER JOIN [stock].[stock_type] AS [s] ON [z].[stock_type_id] = [s].[id]
INNER JOIN [stock].[stock_class] AS [s0] ON [z].[stock_class_id] = [s0].[id]
INNER JOIN [dic].[currency] AS [c] ON [z].[currency_id] = [c].[id]
WHERE [z].[id] = @__data_ShareTypeId_0
```
EFCore Version: 1.1.2

**Comment by smitpatel** [comment] 2017-07-27 21:08
duplicate of #7956
fixed in 2.0 release.

**Closed** 2022-10-16 11:13 UTC
Labels: closed-duplicate
