### ISSUE TITLE
Is there any way to know which entity is causing NullReferenceException when calling SaveChanges()?

### ISSUE THREAD

**Issue by blueelvis** [dotnet/efcore#19848] opened 2020-02-09 16:20 UTC
We have quite some entities which are referenced to each other using navigation properties and other constraints. I am working on mocking our services and I am having a really hard time in figuring out which linked entity/field is causing `NullReferenceException` while calling `SaveChanges()`. Is there any way to find out the exact entity/field where this happened?

Since we have pretty deeply nested entities, it would be really hard to track manually.

Thanks!

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: e.g. .NET Core 3.0
Operating system: Windows 10 Enterprise
IDE: Visual Studio 2019 16.3

**Comment by ajcvickers** [comment] 2020-02-09 16:36
@blueelvis Can you post a stack trace?

**Comment by ajcvickers** [comment] 2020-02-18 20:33
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:10 UTC
Labels: closed-could-not-reproduce, customer-reported
