### ISSUE TITLE
Changing column type from string to long (with identity) causes invalid SQL to be generated

### ISSUE THREAD

**Issue by lenardg** [dotnet/efcore#2618] opened 2015-07-14 13:10 UTC
In my entity class called **MyEntityType** I had a property called **MyProperty** with type **string**. I had the following rules applied in the context class to it:

``` C#
protected override void OnModelCreating(ModelBuilder builder) {
    // some other code
    builder.Entity<MyEntityType>().Property(ent=>ent.MyProperty).MaxLength(64).Required();
    // some more code
}
```

I then changed the type of the property to **long** and the definition for the column to be an identity column as follows:

``` C#
    builder.Entity<MyEntityType>().Property(ent=>ent.MyProperty).GenerateValueOnAdd();
    builder.Entity<MyEntityType>().Property(ent=>ent.MyProperty).ForSqlServer().UseIdentity();
```

The migration gets generated OK. Here is the migration that gets generated:

``` C#
            migration.AlterColumn(
                name: "MyProperty",
                table: "MyEntityType",
                type: "bigint",
                nullable: false)
                .Annotation("SqlServer:ValueGeneration", "Identity");
```

To me, this looks like what I am looking for. However, upon applying the migration, I receive:

``` C#
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'IDENTITY'.
```

Probably some illegal SQL gets generated.

I know the syntax is correct, because if instead of changing the type for **MyProperty** I add a brand new property (**MyNewProperty**) and apply the same rules, the identity field gets generated and the migration applied without problems.

I am using EF7 beta5.

**Comment by bricelam** [comment] 2015-07-14 16:07
Dupe of #2070 (Although, this one is more concise.)

**Closed** 2022-10-16 09:02 UTC
