### ISSUE TITLE
owned entity type is not working in 2.1.5 release 

### ISSUE THREAD

**Issue by mukeem1** [dotnet/efcore#13607] opened 2018-10-12 12:14 UTC
Owned Entity type is not working in latest release of .net core 2.1.5 runtime running on azure web app
which was working on .net core 2.1.0. This is throwing invalid column name error with entity name .

My app stopped working after this update even though this is working at my local machine at my machine is having version 2.1.0 runtime

> Exception message:
Invalid column name **"Price_SkuMrpId".**

```c#
public class SkuMrp 
    {
        public string Data { get; set; }
        public Price Price { get; set; }
        public int DataId { get; set; }
    }

[Owned]
    public partial class Price
    {
        public decimal Value { get; set; }
        [MaxLength(10)]
        public string Currency { get; set; }
    }
```

### Further technical details
EF Core version:  dotnet\shared\Microsoft.NETCore.App\2.1.5\
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment] 2018-10-12 16:12
@mukeem1 Can you please post a runnable project/solution or complete code listing that demonstrates the issue you are seeing.

**Comment by ajcvickers** [comment] 2018-10-22 17:54
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:34 UTC
Labels: closed-could-not-reproduce, customer-reported
