### ISSUE TITLE
.NET Entity Framweork Core  3.0-Unable to execute LINQ query with multiple join conditions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#21841] opened 2020-07-29 19:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1122641/net-entity-framweork-core-30-unable-to-execute-lin.html)._

---
<p>                var yardiUnit = await ( from u in _db. Units </p><p><strong>                                         join t in _db. Tenants on u.HMy equals t.HUnit into tmpT
                                        from tn in tmpT.Where(x=&gt; statusIds.Contains(x.StatusId.Value)). DefaultIfEmpty()
                                        </strong></p><p class=""><strong>where u.SCode == request. UnitCode</strong><br><strong></strong><br>The line in Bold is the culprit<br><br><strong>Given below is my SQL statement which I am trying to write as a LINQ Query<br></strong>From Unit u <br>LEFT JOIN TENANT t on t.HUNIT = u.HMY AND t.ISTATUS in (0, 3 )</p>
</strong></p>

---
#### Feedback Bot on 7/23/2020, 00:29 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2020-07-31 22:55
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by deleteLater** [comment] 2020-08-11 09:52
hope this will help you, it works for me. **:sunny:**
```csharp
public static IQueryable<TQuery> WhereIn<TKey, TQuery>(
   this IQueryable<TQuery> queryable,
   [NotNull] IList<TKey> values,
   [NotNull] Expression<Func<TQuery, TKey>> keySelector)
{
   if (!values.Any())
   {
       return queryable;
   }
   
   var method = values.GetType().GetMethod("Contains");
   if (method == null)
   {
       throw new InternalException($"Contains Method Not Found! Check parameter type: {nameof(values)}");
   }
   
   var call = Expression.Call(Expression.Constant(values), method, keySelector.Body);

   var clause = Expression.Lambda<Func<TQuery, bool>>(call, keySelector.Parameters);

   // queryable.Where((keySelector.Parameters) => Expression.Constant(values).Contains(keySelector.Body));
   return queryable.Where(clause);
}
```

**Comment by ajcvickers** [comment] 2020-08-17 15:18
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:35 UTC
Labels: closed-could-not-reproduce, customer-reported
