### ISSUE TITLE
Enable optional Owned Objects

### ISSUE THREAD

**Issue by frbatist** [dotnet/efcore#10818] opened 2018-01-30 10:52 UTC
There's no support for defining a Owned Object as optional (AKA Nullable).

We have classes like "User" or "Address", that are ValueObjects, not actual entities.
In some cases we want this "User" to be required, and in other cases to be optional.

It would be nice to be able to map as optional, so migrations create the columns as not null.

Something like this:

```C#
orderConfiguration.OwnsOne(p => p.OrderDetails, cb =>
    {
        cb.OwnsOne(c => c.BillingAddress).IsRequired(false);
        cb.OwnsOne(c => c.ShippingAddress);
    });
```

**Comment by AndriySvyryd** [comment] 2018-02-01 01:46
To be useful for relational providers this requires table splitting support https://github.com/aspnet/EntityFrameworkCore/issues/9005

**Comment by ajcvickers** [comment] 2018-02-03 00:12
Closing this as a duplicate of #9005 since this is the real feature that needs implementing for optional owned entities. API for configuration will be added as part of implementing that feature.

**Comment by cetk** [comment] 2019-08-14 23:24
Is it resolved in EF core 2.2 , I am getting same error ?

**Comment by ajcvickers** [comment] 2019-08-14 23:27
@cetk This issue is closed as a duplicate. Therefore, any information will be contained in the referenced issue--that is #9005--which is closed as fixed in milestone "3.0.0-preview4". This means it is fixed for 3.0, not 2.2.

**Closed** 2022-10-16 12:07 UTC
Labels: closed-duplicate
