### ISSUE TITLE
File Lock Held on SQLiteConnection After Leaving Using

### ISSUE THREAD

**Issue by corykroll** [dotnet/efcore#26669] opened 2021-11-13 18:15 UTC
Leaving the using doesn't free up the file lock like it should.
I tested with Windows 11.  Created a SQLite database (test.db).
Set debug points within the using and afterwards.

I was unable to rename the file in the using, as well as after leaving it.

Downgrading Microsoft.Data.Sqlite to 5.0.12 fixed the issue.

```C#
using (var sqliteConnection = new SqliteConnection("Filename=test.db"))
{
    sqliteConnection.Open();
}
```

Microsoft.Data.Sqlite version: 6.0
Target framework: (e.g. .NET 6.0)
Operating system: Windows 11

**Comment by roji** [comment] 2021-11-13 18:56
Duplicate of #26580

**Comment by roji** [comment] 2021-11-13 18:56
This is by design, [see breaking change note for 6.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes#connection-pool).

The SQLite provider now pools connections, improving connection speed significantly but keeping connections open. You can disable pooling by adding `Pooling=false` to the connection string or calling `SqliteConnection.ClearAllPools()` at the point where you want them to be closed.

**Comment by corykroll** [comment] 2021-11-13 20:54
@roji Thank you so much for the info!  My apologies for not spotting that in the breaking changes.

**Closed** 2022-10-16 20:14 UTC
Labels: customer-reported, area-adonet-sqlite
