### ISSUE TITLE
Duplicated Ids in HasIndex

### ISSUE THREAD

**Issue by wannadream** [dotnet/efcore#4531] opened 2016-02-10 19:41 UTC
After I did a scaffolding from database, it reports errors from compiler. I have to remove them one by one.
![ef7_1](https://cloud.githubusercontent.com/assets/6989212/12959429/346cda6e-cfeb-11e5-972d-cfd11f214164.gif)

**Comment by rowanmiller** [comment] 2016-02-10 19:49
Can you share the database schema that you scaffolded from.

**Comment by smitpatel** [comment] 2016-02-10 19:54
dupe of #3847 ?

**Comment by lajones** [comment] 2016-02-10 19:59
Yep - agree with @smitpatel - looks like a dupe of #3847. @wannadream what version of EF were you using?

**Comment by wannadream** [comment] 2016-02-10 20:17
Yes, it's duplicated with #3847.

**Closed** 2022-10-16 09:28 UTC
