### ISSUE TITLE
Nested Owned entity within a non-tablesplitting owned entity doesn't updated

### ISSUE THREAD

**Issue by altmann** [dotnet/efcore#14946] opened 2019-03-07 17:09 UTC
We try to use ToTable() for Owned Entities to support nullable owned Entities with EF Core. We configured AblehnungsInfo as Owned Entity without Tablesplitting. This Owned Entity has a nested owned Entity (Ergaenzung) and a ValueConversion property. 

ValueConversion works fine. 
Problem: Nested owned Entity can't be updated. It keeps the only value. No exception will be thrown. 

Is a nested owned entities within a non-tablesplitting owned entity supported?
Whats wrong?

```c#
entity.OwnsOne(x => x.AblehnungsInfo,
                                                           mb =>
                                                           {
                                                               mb.ToTable("AblehnungsInfo");

                                                               mb.OwnsOne(a => a.Ergaenzung);

                                                               mb.Property(a => a.InternerVermerk)
                                                                 .HasConversion(new InternerVermerkToStringConverter());
                                                           });
```

``` 
// Updating UpdateInfo
AblehnungsInfo = ablehnungsInfo;
```

### Further technical details
EF Core version: EF Core 2.2.2
Operating system: Windows 10
IDE:  Visual Studio 2017 Newest

**Comment by AndriySvyryd** [comment] 2019-03-07 18:45
This is likely a duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/12118

**Closed** 2022-10-16 13:55 UTC
Labels: customer-reported
