### ISSUE TITLE
Data corruption on DbSet.Add

### ISSUE THREAD

**Issue by Yuri6037** [dotnet/efcore#16945] opened 2019-08-04 21:04 UTC
When inserting multiple entities that has one-to-zero relationships, when adding the second one, the first one gets erased entirely.

### Steps to reproduce
Create a database schema containing an entity linked to 5 other entities as one-to-zero relationships, meaning the referenced entity does not map the container entity.

Here is an example using fluent API
```c#
                builder.HasOne(e => e.User)
                    .WithOne()
                    .HasForeignKey<Symbol>(e => e.UserId)
                    .IsRequired(false)
                    .OnDelete(DeleteBehavior.SetNull);
                builder.HasOne(e => e.Lang)
                    .WithOne()
                    .HasForeignKey<Symbol>(e => e.LangId)
                    .IsRequired(true)
                    .OnDelete(DeleteBehavior.Cascade);
                builder.HasOne(e => e.Lib)
                    .WithOne()
                    .HasForeignKey<Symbol>(e => e.LibId)
                    .IsRequired(true)
                    .OnDelete(DeleteBehavior.Cascade);
                builder.HasOne(e => e.Type)
                    .WithOne()
                    .HasForeignKey<Symbol>(e => e.TypeId)
                    .IsRequired(true)
                    .OnDelete(DeleteBehavior.Cascade);
                builder.HasOne(e => e.Import)
                    .WithOne()
                    .HasForeignKey<Symbol>(e => e.ImportId)
                    .IsRequired(false)
                    .OnDelete(DeleteBehavior.SetNull);
                builder.HasIndex(e => e.UserId).IsUnique(false);
                builder.HasIndex(e => e.LangId).IsUnique(false);
                builder.HasIndex(e => e.LibId).IsUnique(false);
                builder.HasIndex(e => e.TypeId).IsUnique(false);
                builder.HasIndex(e => e.ImportId).IsUnique(false)
```

### How to resolve
Now the question is why does removing HasIndex and replacing one-to-zero by one-to-manyzero (WithOne becomes WithMany) seem to fix the corruptions ?

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 Professional 64 bits
IDE: Visual Studio 2017 15.9.14

**Comment by ajcvickers** [comment] 2019-08-05 16:15
@Yuri6037 There isn't enough information here for me to be able to reproduce what you are seeing. Please post a small, runnable project/solution or complete code listing.

**Comment by ajcvickers** [comment] 2019-08-12 16:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:33 UTC
Labels: closed-could-not-reproduce, customer-reported
