### ISSUE TITLE
Scaffold-DbContext more than 1 Foreign to another table

### ISSUE THREAD

**Issue by davidscherf** [dotnet/efcore#18777] opened 2019-11-06 06:42 UTC
My table has
DeviceLocationId
and
ChildDeviceLocationId
that point to the DeviceLocation table

I cannot generate the entity source code

System.InvalidOperationException: The foreign key {'DeviceLocationId'} cannot be added to the entity type 'Device' because a foreign key on the same properties already exists on entity type 'Device' and also targets the key {'DeviceLocationId'} on 'DeviceLocation'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.Validate(IReadOnlyList`1 properties, Key principalKey, EntityType declaringEntityType, EntityType principalEntityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey..ctor(IReadOnlyList`1 dependentProperties, Key principalKey, EntityType dependentEntityType, EntityType principalEntityType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddForeignKey(IReadOnlyList`1 properties, Key principalKey, EntityType principalEntityType, Nullable`1 componentConfigurationSource, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType.AddForeignKey(IReadOnlyList`1 properties, IMutableKey principalKey, IMutableEntityType principalEntityType)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKey(ModelBuilder modelBuilder, DatabaseForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKeys(ModelBuilder modelBuilder, IList`1 foreignKeys)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

### Steps to reproduce

Scaffold-DbContext "Server=.;Database=Jail;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.0
Operating system: Windows 10 1903
IDE: Visual Studio 2019 16.3.7

**Comment by ErikEJ** [comment] 2019-11-06 17:14
Please share the schema of the two involved tables

**Comment by ajcvickers** [comment] 2019-11-15 17:35
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by govert-co-co** [comment] 2019-11-25 08:54
For the people who land here through their favorite search engine, this is usually caused by two identical foreign keys. If you are getting this error, double-check all the foreign keys on your table to make sure they are not accidentally identical.

**Comment by captmomo** [comment] 2019-12-31 12:50
> For the people who land here through their favorite search engine, this is usually caused by two identical foreign keys. If you are getting this error, double-check all the foreign keys on your table to make sure they are not accidentally identical.

I'm experiencing the same issue, and this is the table schema:

```
CREATE TABLE [dbo].[TOOL_LIFE_DETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FACILITY_ASSET_LINK_ID] [int] NULL,
	[CURRENT_STATE] [int] NULL,
	[PRODUCT_LIFE_POINT] [decimal](18, 8) NULL,
	[HOUR_LIFE_POINT] [decimal](18, 8) NULL,
	[IS_DELETED] [bit] NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[UPDATED_BY_PROFILE] [int] NULL,
 CONSTRAINT [PK_TOOL_LIFE_DETAILS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS] ADD  CONSTRAINT [DEFAULT_CONSTRAINT_0_FOR_IS_DELETED_TOOL_LIFE_DETAILS]  DEFAULT ((0)) FOR [IS_DELETED]
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_TOOL_LIFE_DETAILS_FACILITY_ASSET] FOREIGN KEY([FACILITY_ASSET_LINK_ID])
REFERENCES [dbo].[FACILITY_ASSET] ([ID])
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS] CHECK CONSTRAINT [FK_TOOL_LIFE_DETAILS_FACILITY_ASSET]
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_TOOL_LIFE_DETAILS_PERSONNEL] FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[PERSONNEL] ([ID])
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS] CHECK CONSTRAINT [FK_TOOL_LIFE_DETAILS_PERSONNEL]
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_TOOL_LIFE_DETAILS_PERSONNEL1] FOREIGN KEY([MODIFIED_BY])
REFERENCES [dbo].[PERSONNEL] ([ID])
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS] CHECK CONSTRAINT [FK_TOOL_LIFE_DETAILS_PERSONNEL1]
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_TOOL_LIFE_DETAILS_TOOL_LIFE_DETAILS] FOREIGN KEY([ID])
REFERENCES [dbo].[TOOL_LIFE_DETAILS] ([ID])
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS] CHECK CONSTRAINT [FK_TOOL_LIFE_DETAILS_TOOL_LIFE_DETAILS]
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_TOOL_LIFE_DETAILS_TOOL_LIFE_DETAILS1] FOREIGN KEY([ID])
REFERENCES [dbo].[TOOL_LIFE_DETAILS] ([ID])
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS] CHECK CONSTRAINT [FK_TOOL_LIFE_DETAILS_TOOL_LIFE_DETAILS1]
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_TOOL_LIFE_DETAILS_TOOL_LIFE_PROFILE] FOREIGN KEY([UPDATED_BY_PROFILE])
REFERENCES [dbo].[TOOL_LIFE_PROFILE] ([ID])
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS] CHECK CONSTRAINT [FK_TOOL_LIFE_DETAILS_TOOL_LIFE_PROFILE]
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_TOOL_LIFE_DETAILS_TOOL_STATE] FOREIGN KEY([MODIFIED_BY])
REFERENCES [dbo].[PERSONNEL] ([ID])
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS] CHECK CONSTRAINT [FK_TOOL_LIFE_DETAILS_TOOL_STATE]
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_TOOL_LIFE_DETAILS_TOOL_STATE1] FOREIGN KEY([CURRENT_STATE])
REFERENCES [dbo].[TOOL_STATE] ([ID])
GO

ALTER TABLE [dbo].[TOOL_LIFE_DETAILS] CHECK CONSTRAINT [FK_TOOL_LIFE_DETAILS_TOOL_STATE1]
GO


```

The error I get is the same:  
```
The foreign key {'ModifiedBy'} cannot be added to the entity type 'ToolLifeDetails' because a foreign key on the same properties already exists on entity type 'ToolLifeDetails' and also targets the key {'Id'} on 'Personnel'.
```

I checked the schema, and the foreign keys aren't identical. What am I doing wrong?

**Comment by MenaceSan** [comment] 2020-03-02 20:31
And to make the obvious conclusion to @govert-co-co comment. Just delete the FK that is duplicated and the issue should be solved.

**Comment by hard-rox** [comment] 2020-05-08 22:55
> For the people who land here through their favorite search engine, this is usually caused by two identical foreign keys. If you are getting this error, double-check all the foreign keys on your table to make sure they are not accidentally identical.

Man your comment is just awesome. You will never know how many lives you saved. :D

**Comment by bkegley** [comment] 2020-05-11 19:45
If anyone else stumbles here and can't identify which relationships are duplicates this [SO answer](https://stackoverflow.com/questions/58392011/foreign-key-conflict-ef-core-scaffolding?rq=1) helped me.

**Comment by Uraharadono** [comment] 2021-01-30 22:52
> If anyone else stumbles here and can't identify which relationships are duplicates this [SO answer](https://stackoverflow.com/questions/58392011/foreign-key-conflict-ef-core-scaffolding?rq=1) helped me.

Thanks a ton man, this is literally mine issue as well.

**Comment by Rikudouensof** [comment] 2022-07-26 12:25
> If anyone else stumbles here and can't identify which relationships are duplicates this [SO answer](https://stackoverflow.com/questions/58392011/foreign-key-conflict-ef-core-scaffolding?rq=1) helped me.

Thanks a bunch

**Closed** 2022-10-16 14:54 UTC
Labels: closed-could-not-reproduce, customer-reported
