### ISSUE TITLE
Multiple queries on Many to Many relationship

### ISSUE THREAD

**Issue by mdmoura** [dotnet/efcore#15002] opened 2019-03-12 22:48 UTC
I have the following Query:

```C#
      var results = await posts
        .Select(x => new PostModel {
          Id = x.Id,
          Approved = x.Approved,
          Tags = !x.PostTags.Any() ? null : x.PostTags.Select(y => new TagModel {
            Id = y.Tag.Id,
            Name = y.Tag.TagLocalizations.Where(z => z.LanguageCode == "en").Select(z => z.Name).FirstOrDefault()
          })
        }).ToListAsync();
```
When I check the debug console I see the following:

```
[22:20:42 Information] Microsoft.EntityFrameworkCore.Database.Command
Executed DbCommand (26ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [x].[Id], [x].[Approved], CASE
    WHEN NOT ((
        SELECT CASE
            WHEN EXISTS (
                SELECT 1
                FROM [PostTags] AS [f0]
                WHERE [x].[Id] = [f0].[PostId])
            THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
        END
    ) = 1)
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END
FROM [Posts] AS [x]

[22:20:43 Information] Microsoft.EntityFrameworkCore.Database.Command
Executed DbCommand (2ms) [Parameters=[@_outer_Id='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT [y].[TagId] AS [Id]
FROM [PostTags] AS [y]
WHERE @_outer_Id = [y].[PostId]
[22:20:43 Information] Microsoft.EntityFrameworkCore.Database.Command
Executed DbCommand (1ms) [Parameters=[@_outer_Id='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT [y].[TagId] AS [Id]
FROM [PostTags] AS [y]
WHERE @_outer_Id = [y].[PostId]
[22:20:43 Information] Microsoft.EntityFrameworkCore.Database.Command
Executed DbCommand (1ms) [Parameters=[@_outer_Id='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT [y].[TagId] AS [Id]
FROM [PostTags] AS [y]
WHERE @_outer_Id = [y].[PostId]
```

Why the multiple commands:

```
SELECT [y].[TagId] AS [Id]
FROM [PostTags] AS [y]
WHERE @_outer_Id = [y].[PostId]
```

Is this supposed to happen?

### Further technical details
EF Core version: 2.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: macOS 10.14.3
IDE: Visual Studio Code 1.32.1

**Comment by GeraudFabien** [comment] 2019-03-13 20:50
#13132

**Comment by ajcvickers** [comment] 2019-03-15 17:06
@smitpatel to clean-up n+1 issues.

**Comment by smitpatel** [comment] 2019-03-15 18:24
Duplicate of #13232

**Closed** 2022-10-16 13:55 UTC
Labels: closed-duplicate, customer-reported
