### ISSUE TITLE
ArgumentNullException when Where + OrderBy + GroupBy + ToListAsync

### ISSUE THREAD

**Issue by maslewandowski** [dotnet/efcore#31114] opened 2023-06-21 11:36 UTC
Console Application with .NET 7 
Nuget: 
EF Core Version 7.0.7
EF Core SqlServer 7.0.7
EF Core Tools 7.0.7
SQL Server 2019 Version 15.0.4280.7
All Running on Windows 11 64 Bit 22H2 22621.1778

**This code does not work:**
```C#
var returnValue = await context.DBSet
                .Where(b => b.Q == -1)
                .Where(b => b.W == -1)
                .Where(b => b.E == -1)
                .Where(b => b.R== 0)
                .Where(b => b.T == 0)
                .Where(b => b.Z == 0)
                .Where(b => b.U == 0)
                .OrderBy(b => b.I)
                .OrderBy(b => b.O)
                .OrderBy(b => b.P)
                .GroupBy(b => b.I)
                .ToListAsync();
```
Message: 
Test method X threw exception: 
```
System.ArgumentNullException: Value cannot be null. (Parameter 'collection')

  Stack Trace: 
List`1.InsertRange(Int32 index, IEnumerable`1 collection)
SelectExpression.ApplyProjection(Expression shaperExpression, ResultCardinality resultCardinality, QuerySplittingBehavior querySplittingBehavior)
SelectExpressionProjectionApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
RelationalQueryTranslationPostprocessor.Process(Expression query)
SqlServerQueryTranslationPostprocessor.Process(Expression query)
QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
Database.CompileQuery[TResult](Expression query, Boolean async)
QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
DatabaseProvider.Y() line 18
X() line 23
```

**This code does work:**
```C#
var returnValue = await context.DBSet
    .Where(b => b.Q == -1)
    .Where(b => b.W == -1)
    .Where(b => b.E == -1)
    .Where(b => b.R == 0)
    .Where(b => b.T == 0)
    .Where(b => b.Z == 0)
    .Where(b => b.U == 0)
    .OrderBy(b => b.I)
    .OrderBy(b => b.O)
    .OrderBy(b => b.P)
    .ToListAsync();

var groupedValue = returnValue
    .GroupBy(b => b.I)
    .ToList();
```

**Comment by ajcvickers** [comment] 2023-06-21 19:12
@maslewandowski I am not able to reproduce this; see my code below. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
using (var context = new SomeDbContext())
{
    await context.Database.EnsureDeletedAsync();
    await context.Database.EnsureCreatedAsync();

    context.AddRange(new Foo { I = 1, }, new Foo { I = 1, }, new Foo { I = 2, }, new Foo { I = 2, });
    await context.SaveChangesAsync();
}

using (var context = new SomeDbContext())
{
    var returnValue = await context.Foos
        .Where(b => b.Q == -1)
        .Where(b => b.W == -1)
        .Where(b => b.E == -1)
        .Where(b => b.R== 0)
        .Where(b => b.T == 0)
        .Where(b => b.Z == 0)
        .Where(b => b.U == 0)
        .OrderBy(b => b.I)
        .OrderBy(b => b.O)
        .OrderBy(b => b.P)
        .GroupBy(b => b.I)
        .ToListAsync();
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    public DbSet<Foo> Foos => Set<Foo>();
}

public class Foo
{
    public int Id { get; set; }
    public int Q { get; set; }
    public int W { get; set; }
    public int E { get; set; }
    public int R { get; set; }
    public int T { get; set; }
    public int Z { get; set; }
    public int U { get; set; }
    public int I { get; set; }
    public int O { get; set; }
    public int P { get; set; }
}
```

**Comment by ajcvickers** [comment] 2023-07-07 16:47
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-07-07 16:47 UTC
Labels: customer-reported
