### ISSUE TITLE
Code First Stored Procedure

### ISSUE THREAD

**Issue by wangkanai** [dotnet/efcore#6009] opened 2016-07-07 08:38 UTC
Its would be nice if Entity Framework Core have the feature to create and maintain stored procedure for sql server. The stored procedure would be developed and under code control in code first model in EF Core.

**Comment by roji** [comment] 2016-07-07 13:47
It doesn't seem like there's that much that EFCore could provide here over raw SQL, or am I missing something? Given that you can already maintain stored procedures in migrations with raw SQL, what would be the value here?

Consider also that stored procedures are very much coupled to their database systems - different databases use different server-side languages.

**Comment by rowanmiller** [comment] 2016-07-07 17:26
Duplicate of https://github.com/aspnet/EntityFramework/issues/245. We did have a migrations API in EF6 that provided an abstraction of parameters etc. but then the body of the sproc was specified in SQL. As @roji mentioned, it's not clear if that really provides that much value over just raw SQL. Regardless of the API though, having the ability to map a model to sprocs and have those sprocs maintained by migrations is something we want to do (tracked by #245).

**Closed** 2022-10-16 09:49 UTC
Labels: closed-duplicate
