### ISSUE TITLE
String [First|Last]OrDefault translation

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#24229] opened 2021-02-23 08:04 UTC
Is there a reason why `string.[First|Last]OrDefault` ([here](https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs#L341) and [here](https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs#L352)) are not translated using `LEFT` and `RIGHT` functions respectively?

**Comment by smitpatel** [comment] 2021-02-23 08:07
Original tracking issue - https://github.com/dotnet/efcore/issues/10912

@maumar mentioned Substring, @roji pointed out Left/Right and a community contribution implemented it. Did you guys do any testing to figure out which is faster or better? Or is it just whatever community contribution did, we ended up with it.

**Comment by roji** [comment] 2021-02-23 08:45
Don't quite remember anymore... It's likely that neither LEFT/RIGHT nor SUBSTRING take advantage of indexes (even though they technically could on the left side), but that's something that would need to be confirmed. Other than that it mainly seems to be a style difference.

**Comment by ErikEJ** [comment] 2021-02-23 12:54
"There is no difference at all between left and substring because left is translated to substring in the execution plan."
https://stackoverflow.com/questions/18892208/substring-vs-left-in-sql-server

**Comment by roji** [comment] 2021-02-23 13:04
There's also [this article](https://cc.davelozinski.com/sql/like-vs-substring-vs-leftright-vs-charindex) (linked from the SO above) that claims that LEFT is faster on non-indexed columns - that would seem contradictory...

**Comment by ajcvickers** [comment] 2021-03-01 17:08
Note from triage: we are closing this for now, but would consider a PR with associated perf results showing the improvement.

**Closed** 2022-10-16 19:24 UTC
Labels: closed-out-of-scope, customer-reported
