### ISSUE TITLE
IQueryable CountAsync can't work properly.

### ISSUE THREAD

**Issue by littlesmilelove** [dotnet/efcore#11438] opened 2018-03-27 03:40 UTC
When I use ef core 2.0.2 with Automapper ProjectTo, I genarate a IQueryable<T> source, however, in some data type, it work properly, but in some data type, when i apply CountAsync(), it will fails and throw the exception. In addition, the ToArrayAsync() always work properly.

```
Exception message: System.InvalidOperationException
Stack trace:
System.InvalidOperationException: The query model's result type cannot be changed to 'System.Linq.IQueryable`1[Microsoft.EntityFrameworkCore.Query.Internal.MaterializedAnonymousObject]'. The result type may only be overridden and set to values compatible with the ResultOperators' current data type ('System.Int32').
    在  Remotion.Linq.QueryModel.GetOutputDataInfo (Remotion.Linq, Version=2.2.0.0, Culture=neutral, PublicKeyToken=fee00910d6e5f53b)
    在  Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.ConvergesToSingleValue (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.AdjustForResultOperators (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.VisitSubQuery (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  System.Linq.Expressions.ExpressionVisitor.Visit (System.Linq.Expressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
    在  Remotion.Linq.Clauses.FromClauseBase.TransformExpressions (Remotion.Linq, Version=2.2.0.0, Culture=neutral, PublicKeyToken=fee00910d6e5f53b)
    在  Remotion.Linq.QueryModel.TransformExpressions (Remotion.Linq, Version=2.2.0.0, Culture=neutral, PublicKeyToken=fee00910d6e5f53b)
    在  Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.VisitSubQuery (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  System.Linq.Expressions.ExpressionVisitor.Visit (System.Linq.Expressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
    在  Remotion.Linq.Clauses.JoinClause.TransformExpressions (Remotion.Linq, Version=2.2.0.0, Culture=neutral, PublicKeyToken=fee00910d6e5f53b)
    在  Remotion.Linq.QueryModel.TransformExpressions (Remotion.Linq, Version=2.2.0.0, Culture=neutral, PublicKeyToken=fee00910d6e5f53b)
    在  Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.FindQuerySourcesRequiringMaterialization (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.EntityFrameworkCore.Query.QueryCompilationContext+QuerySourcesRequiringMaterializationFinder.AddQuerySourcesRequiringMaterialization (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CorrelatedCollectionOptimizingVisitor.Rewrite (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CorrelatedCollectionOptimizingVisitor.VisitSubQuery (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  System.Linq.Expressions.ExpressionVisitor.Visit (System.Linq.Expressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
    在  System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments (System.Linq.Expressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
    在  System.Linq.Expressions.ExpressionVisitor.VisitMethodCall (System.Linq.Expressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
    在  System.Linq.Expressions.MethodCallExpression.Accept (System.Linq.Expressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
    在  System.Linq.Expressions.ExpressionVisitor.Visit (System.Linq.Expressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
    在  System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment (System.Linq.Expressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
    在  System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding (System.Linq.Expressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
    在  System.Linq.Expressions.ExpressionVisitor.Visit (System.Linq.Expressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
    在  System.Linq.Expressions.ExpressionVisitor.VisitMemberInit (System.Linq.Expressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
    在  System.Linq.Expressions.MemberInitExpression.Accept (System.Linq.Expressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
    在  Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.TryOptimizeCorrelatedCollections (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause (Microsoft.EntityFrameworkCore.Relational, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Remotion.Linq.QueryModelVisitorBase.VisitQueryModel (Remotion.Linq, Version=2.2.0.0, Culture=neutral, PublicKeyToken=fee00910d6e5f53b)
    在  Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel (Microsoft.EntityFrameworkCore.Relational, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.CountAsync (Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  XTKJ.Fota.Utilities.DataPager.DataPager+<PageAsync>d__10`1.MoveNext (DataPager.cs:151) (XTKJ.Fota.Utilities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
    在  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  XTKJ.Fota.Utilities.DataPager.DataPager+<MapPageAsync>d__2`2.MoveNext (DataPager.cs:35) (XTKJ.Fota.Utilities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
    在  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  XTKJ.Fota.Infrastructure.Data.EFRepository`1+<MapPageAsync>d__5`1.MoveNext (EFRepository.cs:38) (XTKJ.Fota.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
    在  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  XTKJ.Fota.Api.Controllers.AdminOrderController+<GetPageAsync>d__5.MoveNext (AdminOrderController.cs:120) (XTKJ.Fota.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
    在  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Core, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Core, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Core, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Core, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext (Microsoft.AspNetCore.Routing, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext (Microsoft.AspNetCore.Authentication, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
    在  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
    在  Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext (Microsoft.AspNetCore.Diagnostics, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
```

```c#
public static async Task<DataPage<T>> PageAsync<T>(this IQueryable<T> source, int pageIndex, int pageSize)
        {
            var data = await source.Skip((pageIndex - 1) * pageSize).Take(pageSize).ToArrayAsync();
            var length = await source.CountAsync();
            return new DataPage<T>
            {
                Data = data,
                Total = length
            };
        }
```

### Further technical details
EF Core version: 2.0.2
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL 2.1.0-preview1

**Comment by smitpatel** [comment] 2018-03-27 05:01
Does it work correctly if you upgrade EF Core version to 2.1.0-preview1? EF Core 2.0.2 may not work with PostgreSQL provider 2.1.0-preview1

cc: @roji

**Comment by littlesmilelove** [comment] 2018-03-27 06:15
@smitpatel I follow your instructions upgrade  EF Core version to 2.1.0-preview1, but the same issue happened.

**Comment by littlesmilelove** [comment] 2018-03-28 06:42
@smitpatel OK.
This is the origin model. It works properly.

`public class Order
    {
        public int Id { get; set; }
        public int MobileTypeId { get; set; }
        public MobileType MobileType { get; set; }
        public int? RegionDistrictId { get; set; }
        public RegionDistrict RegionDistrict { get; set; }
        public int RegionCityId { get; set; }
        public RegionCity RegionCity { get; set; }
        [Column(TypeName = "date")]
        public DateTime StartDate { get; set; }
        public TimeSpan WorkTimeStart { get; set; }
        public TimeSpan WorkTimeEnd { get; set; }
        public int ContinuousDays { get; set; }
        public decimal Amount { get; set; }
        public OrderStatus Status { get; set; }
        public DateTime CreateTime { get; set; }
        public IList<OrderItem> OrderItems { get; set; }
        public IList<OrderRemark> OrderRemarks { get; set; }
        public OrderProgress OrderProgress { get; set; }
        public int UserId { get; set; }
        public User User { get; set; }
    }

    public enum OrderStatus
    {
        WaitForPayment,
        WaitForVerify,
        WaitForProcess,
        Processing,
        Finished,
        Failed,
        WaitForRefund,
        Canceled
    }`

When I use automapper ProjectTo this DTOModel, the issue will happen.

`public class GetPageDto
    {
        public int Id { get; set; }
        public IList<ItemDto> OrderItems { get; set; }
        public IList<RemarkDto> OrderRemarks { get; set; }

        public string MobileBrand { get; set; }
        public string MobileType { get; set; }

        public string RegionProvince { get; set; }
        public string RegionCity { get; set; }
        public DateTime StartDate { get; set; }
        public TimeSpan WorkTimeStart { get; set; }
        public TimeSpan WorkTimeEnd { get; set; }
        public int ContinuousDays { get; set; }
        public decimal Amount { get; set; }
        public OrderStatus Status { get; set; }
        public DateTime CreateTime { get; set; }
        public string Company { get; set; }
        public string Distributor { get; set; }
    }

    public class ItemDto
    {
        public int ItemNo { get; set; }
        public string IMEI { get; set; }
        public string SN { get; set; }
    }

    public class RemarkDto
    {
        public int ItemNo { get; set; }

        public string Remark { get; set; }

        public DateTime CreateTime { get; set; }
    }

    public class GetPageDtoProfile : Profile
    {
        public GetPageDtoProfile()
        {
            CreateMap<Core.Entities.Order, GetPageDto>()
                .ForMember(d => d.OrderItems, opt => opt.MapFrom(d => d.OrderItems))
                .ForMember(d => d.OrderRemarks, opt => opt.MapFrom(d => d.OrderRemarks))
                .ForMember(d => d.MobileBrand, opt => opt.MapFrom(d => d.MobileType.MobileBrand.Name))
                .ForMember(d => d.MobileType, opt => opt.MapFrom(d => d.MobileType.Name))
                .ForMember(d => d.RegionProvince, opt => opt.MapFrom(d => d.RegionCity.Province.Name))
                .ForMember(d => d.RegionCity, opt => opt.MapFrom(d => d.RegionCity.Name))
                .ForMember(d => d.Company, opt => opt.MapFrom(d => d.User.Company))
                .ForMember(d => d.Distributor, opt => opt.MapFrom(d => d.User.Distributor.Company));
        }
    }

    public class ItemDtoProfile : Profile
    {
        public ItemDtoProfile()
        {
            CreateMap<OrderItem, ItemDto>();
        }
    }

    public class RemarkDtoProfile : Profile
    {
        public RemarkDtoProfile()
        {
            CreateMap<OrderRemark, RemarkDto>();
        }
    }`

This is my MapPage function.

`public static async Task<DataPage<TDto>> MapPageAsync<T, TDto>(this IQueryable<T> source, PagingParam param)
        {
            return await source
                .ProjectTo<TDto>()
                .PageAsync(param.Page, param.PageSize);
        }`

However, I use a temporaty approach avoid the issue, but it will affect the performance.

`public static async Task<DataPage<T>> PageAsync<T>(this IQueryable<T> source, int pageIndex, int pageSize)
        {
            var data = await source.Skip((pageIndex - 1) * pageSize).Take(pageSize).ToArrayAsync();
            var length = (await source.ToListAsync()).Count;
            return new DataPage<T>
            {
                Data = data,
                Total = length
            };
        }`

**Comment by smitpatel** [comment] 2018-03-28 14:14
What is the value of `IQueryable<T> source` being passed in either of the functions?

**Comment by smitpatel** [comment] 2018-03-28 17:40
@littlesmilelove - `Order` has navigations to entities `MobileType`, `RegionCity` and many others which are being used in creating map. Please share code of all those too.

**Comment by littlesmilelove** [comment] 2018-03-29 02:35
@smitpatel The Models.
```
public class MobileType
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public bool Available { get; set; }

        public string Remark { get; set; }

        public int MobileBrandId { get; set; }

        public int TimeZoneBias { get; set; }
        public MobileBrand MobileBrand { get; set; }
  }

public class MobileBrand
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal GuidePrice { get; set; }
        public int ChangeIpAfter { get; set; }
        public IList<MobileType> MobileTypes { get; set; }
    }

public class RegionDistrict
    {
        public int Id { get; set; }
        public string Postcode { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public bool Available { get; set; }
        public int CityId { get; set; }
        public RegionCity City { get; set; }
    }

public class RegionCity
    {
        public int Id { get; set; }
        public string Postcode { get; set; }
        public string Name { get; set; }
        public bool Available { get; set; }
        public int ProvinceId { get; set; }
        public RegionProvince Province { get; set; }
        public IList<RegionDistrict> Districts { get; set; }
    }

public class RegionProvince
    {
        public int Id { get; set; }
        public string Postcode { get; set; }
        public string Name { get; set; }
        public IList<RegionCity> Cities { get; set; }
    }

public class OrderItem
    {
        public int ItemNo { get; set; }
        public string IMEI { get; set; }
        public string SN { get; set; }
        public int OrderId { get; set; }
        public Order Order { get; set; }
    }

public class OrderRemark
    {
        public int Id { get; set; }

        public string Remark { get; set; }

        public DateTime CreateTime { get; set; }
        public int OrderId { get; set; }
        public Order Order { get; set; }
    }

public class OrderProgress
    {
        public int Id { get; set; }
        public int OnDay { get; set; }
        [Required]
        [Column(TypeName = "integer[]")]
        public int[] OnItemNo { get; set; }

        public int OrderId { get; set; }
        public Order Order { get; set; }
    }
```
My origin IQueryable<T> source is DbContext.Set<Order>()
```
public IQueryable<T> Items => DbContext.Set<T>();

public async Task<DataPage<TDto>> MapPageAsync<TDto>(PagingParam param)
        {
            return await Items.MapPageAsync<T, TDto>(param);
        }
```

**Comment by smitpatel** [comment] 2018-03-30 22:26
This is the code I put together from above information https://gist.github.com/smitpatel/178569e8746de0c86040e86f55747e91

I am still not able to get the error.
Please provide us a full solution/project which demonstrate the issue.

**Comment by littlesmilelove** [comment] 2018-04-03 04:29
@smitpatel Your code use the sql server, but my code use the postgre sql. I need some time to extract the issue code from my project.

**Comment by littlesmilelove** [comment] 2018-04-03 09:35
@smitpatel I found when i degrade the PostgreSQL provider to 2.0.0, all things work properly, so i think this issue is related to the PostgreSQL provider.

**Comment by roji** [comment] 2018-04-03 10:33
@littlesmilelove it's pretty improbable that a change in the PostgreSQL provider from 2.0.0 to 2.0.1 triggered this - can you please re-confirm that you're using the same version of EF Core as you're changing the PostgreSQL provider version? Note that when you downgrade from EFCore.PG 2.0.1 to 2.0.0, by default this will also downgrade the EFCore version. So please make sure you're aware of all versions being used by all components when you compare.

**Comment by littlesmilelove** [comment] 2018-04-04 08:33
@smitpatel @roji Now my PostgreSQL provider version is 2.0.0 and my EntityFrameworkCore version is 2.0.1. The version which occur the issue  is PostgreSQL provider 2.1.0-preview1, by the way, in this preview version, the` IQueryable. Include()` with limit and offset join other tables will not work properly, you can just use my entities to test.  The generate SQL is wrong, if you need more detail info, I can roll back my code version to capture the issue.

**Comment by smitpatel** [comment] 2018-04-04 14:32
@littlesmilelove - Please share runnable project which demonstrate issue you are seeing.

**Comment by LizNettleship** [comment] 2018-04-07 18:02
I have encountered a similar issue. I worked around it by supplying a predicate (which always evaluates to true).

**Comment by littlesmilelove** [comment] 2018-04-09 12:36
@smitpatel - I want to send the project to you via email. Can you show me your email address?

**Comment by littlesmilelove** [comment] 2018-04-11 13:16
@ajcvickers I send the project to you. I only keep a api controller to demonstrate the issue.

**Comment by smitpatel** [comment] 2018-04-19 21:44
@littlesmilelove - I received your app but it does not work. When running the app, it gives error with some token and none of the pages load. Further app is creating Expression trees from external library which converts strings to expression. It is not possible to investigate for us when there is no runnable code and parts of code from various libraries which could cause issues.

Please post a runnable code stripping out any external dependencies and only using EF. If it is issue in EF then you can write a query by hand which would demonstrate the issue.

**Comment by ajcvickers** [comment] 2018-04-27 17:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:16 UTC
Labels: closed-could-not-reproduce
