### ISSUE TITLE
Microsoft.Data.Sqlite.SqliteConnection throws a System.NullReferenceException

### ISSUE THREAD

**Issue by svetovid** [dotnet/efcore#26816] opened 2021-11-24 12:18 UTC
Running an application with Sqlite DB connection throws the following exception:  
System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.

`Important!` it **DOES** work properly for target framework **net6.0-windows**, and it **DOES NOT** work for target framework **net48**

### Code
I don't know if it can be helpful

```C#
public SQLiteDatabase()
{
  Connection = new SQLiteConnection();
}
```

### Stack traces
(the part which relates to Microsoft.Data.Sqlite)

```
System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Data.Sqlite.Utilities.ApplicationDataHelper.GetFolderPath(String propertyName)
   at Microsoft.Data.Sqlite.Utilities.ApplicationDataHelper.get_LocalFolderPath()
   at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.SqliteConnection..ctor()
```

### Version information

Microsoft.Data.Sqlite version: 6.0.0
Target framework: net48
Operating system: Windows 10

**Comment by ajcvickers** [comment] 2021-11-24 21:04
Duplicate of #26574.

**Closed** 2022-10-16 20:16 UTC
Labels: customer-reported, area-adonet-sqlite
