### ISSUE TITLE
Query: string concatenation where at least one operand in null translates to null, which is different than Linq to objects

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#9201] opened 2017-07-18 22:39 UTC
```cs
string s1 = null;
string s2 = null;

var q1 = s1 + s2; // translates to null in sql, and to empty string in L2O

string s3 = null;
string s4 = "Foo";

var q2 = s3 + s4; // translates to null in sql, and to "Foo" in L2O
```

**Comment by ajcvickers** [comment] 2017-07-19 18:16
Will triage when @divega @anpete are back. (I have no strong opinion if I am not here.)

**Comment by divega** [comment] 2017-07-26 18:47
*EF triage*: we believe it would be nice if the behavior was closer to L2O. However we don't think this is urgent and it would be a nice opportunity for a contributor. 

FWIW, it would also be a minor breaking change.

**Comment by smitpatel** [comment] 2017-08-30 04:35
Duplicate of #3836

**Closed** 2022-10-16 11:12 UTC
Labels: help wanted, good first issue
