### ISSUE TITLE
too much bug in RC1

### ISSUE THREAD

**Issue by endink** [dotnet/efcore#4065] opened 2015-12-14 07:40 UTC
I very regret put my project upgrade to RC1,EF of RC1 version brings more new BUG, my project from Beta 4 to beta 8 has been work good, today I upgrade to RC1,EF was not worked, first is inherited mapping of problem, if base class has Object type property inherited mapping will throw Exception, even using has "ignore" method also has the same problem, when i fix this （remove the object propery）i think it will work fine, I am wrong !  Then new BUG（https:// Github.com/aspnet/EntityFramework/issues/3679 ）appeared , I spent the whole day did not solve, please don't release often the BUG out version, it impossible to achieve the quality of RC, ASP.NET 5 works good except the EF, would return to EF6? I really do not want to use EF7, very painful each time you upgrade, dont change the rules again and again, please!!

**Comment by endink** [comment] 2015-12-14 07:47
RC version of such a low quality as there are no tests, beta8 is much better than it !!!!!

**Comment by mikes-gh** [comment] 2015-12-14 09:10
In your case I would stick with EF 6.  You need to accept there will be bugs at this early stage in the products life-cycle.  It is not really in the spirit of opensource to blame bugs on others.  The idea is that these bugs get visibility to a wider audience and the quality of the end product actually benefits.

**Comment by endink** [comment] 2015-12-14 11:49
@mikes-gh 
In the beta stage, we are always happy to help improve the project, we think at the time to release a RC version, stable and less BUG should be the ultimate goal,but what we see is more BUG than the beta stages, rules and logic kept changing, it cannot be called RC, more appropriate perhaps beta9, It's very disappointing that more and more developers want to return back to EF6, we grow together and EF7 for half a year, but its progress is very slow, too many BUG is still opened。
Compare ASP.NET 5 (MVC), it has become more and more stable, we are confident that they can release RTM on time, what about EF7 ?  No body know how long it will take to RTM。

**Comment by ErikEJ** [comment] 2015-12-14 12:20
@endink Unfortunately, the EF team have been forced to follow the same release cycle as ASP.NET 5, so an EF RC may not mean the same as an ASP.NET RC, as you have noticed. But you have to accept that there are bugs and even regressions in software under developemnt.

**Comment by rowanmiller** [comment] 2015-12-15 18:24
Closing because there is nothing actionable here. Please continue to file bugs for individual issues that you find. 

You can find some info on using EF6 with ASP.NET 5 here; https://docs.asp.net/en/latest/data/entity-framework-6.html

**Closed** 2022-10-16 09:20 UTC
