### ISSUE TITLE
Optional navigation property could not be mapped

### ISSUE THREAD

**Issue by kennywangjin** [dotnet/efcore#6008] opened 2016-07-07 05:02 UTC
### Steps to reproduce

``` C#
class Printer
 {
        public int Id { get; set; }
        public string Specification { get; set; }
 }

class Cartridge
 {
       public int Id { get; set; }
       public string Specification { get; set; }
 }

class CartridgeTransaction
 {
        public int Id { get; set; }
        public int CartridgeId { get; set; }
        public Cartridge Cartridge { get; set; }
        public int? PrinterId { get; set; }
        public Printer Printer { get; set; }
 }

using (var dbContext=new MyDbContext())
{
       dbContext
            .CartridgeTransactions
            .Select(item=>new 
                   {
                           PrinterInfo = new Printer 
                              {
                                  Id = item.Printer.Id,
                                  Specification=item.Printer.Specification 
                              }, // if  this mapping commented, things worked.
                           CartridgeInfo = new Cartridge 
                             {
                                  Id = item.Cartridge.Id,
                                  Specification=item.Cartridge.Specification 
                             }
                   });
}
```
### The issue

As code above described, "CartridgeTransaction" has navigation properties of "Cartridge" and **optional** "Printer". When "Select" mapping, it always throw one exception of "**Argument type not match**".
If I **comment mapping of  the optional "PrinterInfo",** then it works!
### Further technical details

EF Core version: (1.0.0)
Operating system: Windows 10 Pro 1511 x64
Visual Studio version: VS2015 with Update 3

**Comment by rowanmiller** [comment] 2016-07-08 18:52
We think this is already fixed in our current code base, can you try against our nightly builds https://www.myget.org/Gallery/aspnetcidev.

**Comment by rowanmiller** [comment] 2016-07-15 20:34
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 09:49 UTC
