### ISSUE TITLE
deps.json not found due to extra backslashes being added to search path for a network drive beginning with '\\'

### ISSUE THREAD

**Issue by ColemanRocks** [dotnet/efcore#21048] opened 2020-05-26 15:23 UTC
We have a network drive called '\\\\Coleman\MyCode\'

When it searches for deps.json when trying to run the Scaffold-DbContext command it says it does not exist in '\\\\\\\Coleman\MyCode\'

**Comment by bricelam** [comment] 2020-08-14 15:53
Duplicate of #14349

**Closed** 2022-10-16 18:26 UTC
