### ISSUE TITLE
EF Core problem with Add-Migration

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#18189] opened 2019-10-02 18:12 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/757610/ef-core-problem-with-add-migration.html)._

---
Hi

There is a bug with EF Core with add-Migration when you have more than one DB Context

If you use -c instead of -context, it works as expected

When you use &quot;Add-Migration Refer001 -context ApplicationDbContext&quot; the generator adds tables from another DbContext to the migration script.

When you use &quot;Add-Migration Refer001 -c ApplicationDbContect&quot; it works as expected.

Another problem is when you use &quot;Add-Migration Refer001 -context ApplicationDbContext&quot; it also adds changes that were implemented the previous update-database using the previous migration.

This proble started within the last two VS 2019 updates.

Thanks and regards
Tony

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by bricelam** [comment] 2019-10-02 19:09
Tony, does one of your DbContext classes inherit from the other? Could you attach a repro so we can investigate further?

**Comment by albutta** [comment] 2019-10-03 04:25
Hi

No the two DB Contexts are totally isolated, The one inherits from IdentityDBContext, and the other DbContext. The one the Core web application, and the other a subscribed web application

I notices the problem a week ago, and could not trace where the problem came from.
I had to delete all migrations and the one database. The other, I manually deleted the incorrect data tables. 

I did an Add-Migration and all was well ... until i used -context instead of -c and the problem was back.

Good luck, the workaround is to not use the -context

Regards
Tony

**Comment by albutta** [comment] 2019-10-03 07:53
One more thing, it looks like the problem is with the data model classes inheriting from a BaseEntity.

It may be unrelated to the -c vs -context as I have now the error on -c as well.

Below is my base entity. 

public abstract class BaseEntity: ITrackable
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }
        public Guid TenantId { get; set; }
        public bool IsDeleted { get; set; }
    }

    public interface ITrackable
    {
        Guid TenantId { get; set; }
    }
I am using the Trackable to override the Save changes .
I set trackable.TenantId = UserTenantId; on create 
I set entry.Property("TenantId").IsModified = false; on save 
I set entry.CurrentValues["IsDeleted"] = true; on delete.

Any ideas?

**Comment by ajcvickers** [comment] 2019-10-07 20:29
@albutta We are having trouble following. Please post a small, runnable project/solution that demonstrates the behavior you are seeing so that we can investigate.

**Comment by albutta** [comment] 2019-10-09 06:14
Hi

To resolve this issue, I had to create a separate BaseEntity with a different namespace for each DBContext's data models.

I will create a basic app to demonstrate the problem.

Thanks and regards
Tony

**Comment by ajcvickers** [comment] 2019-10-18 15:59
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:47 UTC
Labels: closed-could-not-reproduce, customer-reported
