### ISSUE TITLE
The LINQ expression 'OrderBy' could not be translated when using enumerations

### ISSUE THREAD

**Issue by anisalibegic** [dotnet/efcore#19091] opened 2019-11-27 13:51 UTC
### Problem

I want to order my work items by state (enumeration) in specified order. I created a dictionary of those 'priorities' where each enumeration item has a certain priority. In v2.2.6 I was able to order by those dictionary priorities just fine but it's failing after migrating to v3.0.1.

### Steps to reproduce

Consider following dictionary of states and priorities:
```
public static readonly Dictionary<State, int> StatesOrder = new Dictionary<State, int> {
    { State.NotCompleted, 1 },
    { State.InProcess, 2 },
    { State.Completed, 3 },
};
```

Get all work items and order like this:
```
var workItems = await DatabaseContext.WorkItems.OrderBy(wi => StatesOrder[wi.State]).ToListAsync();
```

### Exception

```
System.InvalidOperationException: The LINQ expression 'OrderBy<WorkItem, int>(
    source: DbSet<WorkItem>, 
    keySelector: (w) => Dictionary<State, int> { [NotCompleted, 1], [InProcess, 2], [Preparing, 3], [OnHold, 4], [Unclear, 5], [Testing, 6], [Completed, 7], [Rejected, 8], }.get_Item(w.State))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Workaround

I have none.

### Further technical details

EF Core version: 3.0.1
Database provider: Npgsql.EntityFrameworkCore.POostgreSQL
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.9

**Comment by miguellira** [comment] 2019-11-27 14:09
@anisalibegic This is by design. In EF Core 3.x LINQ queries that cannot be translated are no longer evaluated on the client ([see breaking change](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client)).

To get the same experience as in 2.x you would have to write:
```c#
var workItems = DatabaseContext.WorkItems.AsEnumerable().OrderBy(wi => StatesOrder[wi.State]).ToList();
```
just be aware that you will be bringing down all WorkItems from the database then sorting in memory - which may not be ideal but is exactly what you've been doing.

**Comment by anisalibegic** [comment] 2019-11-27 14:27
I'm aware that calling AsEnumerable() will get all WorkItems from the database and load it into memory. Is there any other possible way to sort by enumeration on the database level?

**Comment by miguellira** [comment] 2019-11-27 15:01
This is not an issue with sorting enumerations. If you simply sorted your WorkItems by the enum property it would translate just fine. The issue is that you are assigning a priority via your dictionary mapping and the LINQ provider is not be able to translate your expression into SQL.

Either write the SQL yourself by using a `CASE` statement and `ORDER BY` or modify your data model and store the priority.

**Comment by Suchiman** [comment] 2019-12-02 09:44
```csharp
var workItems = await DatabaseContext.WorkItems.OrderBy(wi => wi.State == State.NotCompleted ? 1 : wi.State == State....).ToListAsync();
```
should work at a DB Level, although this only makes sense if you're retrieving a subset of the data, if you're selecting all data anyway, then sorting on the server doesn't make sense.

**Comment by anisalibegic** [comment] 2019-12-02 10:02
As a temporary workaround I created a table EnumerationPriorites that holds the key-value pair (enumeration index and priority) and then I do:

```
var workItems = await DatabaseContext.WorkItems.OrderBy(wi => DatabaseContext.StatesOrder.First(so => so.Index == wi.State).Priority).ToListAsync();
```

I know I'm making a subquery for every row in WorkItems table but I'll have to refactor it anyways.

**Comment by miguellira** [comment] 2019-12-02 13:48
I believe @Suchiman suggestion will result in desirable `CASE` statement I suggested and keeps your model simple. However, as he suggested if you’re planning to get all WorkItems anyway you might as well just sort outside of the DB.

Either way, consider closing this issue if you’re satisfied with your approach.

**Comment by ajcvickers** [comment] 2019-12-02 21:24
Closing as question has been answered.

**Closed** 2022-10-16 14:58 UTC
Labels: closed-no-further-action, customer-reported
