### ISSUE TITLE
Having a prefix for generated Types in reverse engineering scaffold command

### ISSUE THREAD

**Issue by Jalalx** [dotnet/efcore#24774] opened 2021-04-27 08:19 UTC
## What problem are you trying to solve? 
I use ef core scaffolder to generate models from various databases. Some models may have the same names but they're from different bounded contexts. For example, type `Order` has the same name in two databases but serves different purposes.

## Describe the solution you'd like
I want to be able to add a prefix to type names when I generate models from each database. Something like:
```sh
dotnet ef dbcontext scaffold "<my connection string>" Microsoft.EntityframeworkCore.SqlServer -o SalesModels --type-prefix Sales
```

This should generate a type named `SalesOrder` for the table `Orders` in the `Sales` database.

I also would like to contribute to this feature.
Thank you

**Comment by roji** [comment] 2021-04-27 10:59
Rather than a prefix, doesn't it make more sense to simply scaffold in specific namespaces? This option is already supported by scaffolding ([see the CLI reference](https://docs.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-dbcontext-scaffold)).

**Comment by ErikEJ** [comment] 2021-04-27 12:05
EF Core Power Tools allows you to do renaming, including based on a reg ex.

**Comment by Jalalx** [comment] 2021-04-27 14:26
@roji Yes, I am totally aware of the `--context-namespace <NAMESPACE>` option, But using namespaces always has a change of confusion and even introducing hard-to-trace bugs.

@ErikEJ Thank you but I guess it's a Visual Studio 2019 UI tool. Does it provide a command-line interface or dotnet tool?

**Comment by smitpatel** [comment] 2021-04-27 15:23
For putting in separate namespaces based on schemas when table name is same but schemas are different - #3988
For any other prefixing duplicate of #4038

**Comment by ErikEJ** [comment] 2021-04-27 15:37
@Jalalx yes, it is a VS 2019 GUI tool, it is also available as [an undocumented command line tool](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#requirements)

**Comment by roji** [comment] 2021-04-27 15:54
> But using namespaces always has a chance of confusion and even introducing hard-to-trace bugs.

I'd be interested in learning more! Namespaces as a language feature were introduced precisely to avoid having to prefix everything all the time, as in C... If you really want to, you can fully specify your namespaces every time, at which point you're basically back using prefixes everywhere.

**Comment by Jalalx** [comment] 2021-04-27 21:24
> I'd be interested in learning more! Namespaces as a language feature were introduced precisely to avoid having to prefix everything all the time...

I am not saying that namespaces are bad or not useful in this context. I just feel they don't prevent developer mistakes. Imagine having two mapped types with the same name in different namespaces (`Models.Customers.Order` and `Models.Sales.Order`): 
- The developer should always be careful to import the right namespace in order to use the right type. Sometimes even language type safety doesn't help much to prevent the mistake, for example: what if both mapped types implement the same base type (like `Entity` in models)? The Developer should be careful which type shes uses:
  ```csharp
  private readonly IRepository<Order> _repo; // interface IRepository<TEntity> where TEntity : Entity
  // ...
  var order = await _repo.GetByIdAsync(id);
  return Ok(order);
  ```
- The code-reviewer should always consider the imported namespaces when she's reviewing the code that contains mentioned type(s). What happens when the namespace is already imported before the new changes were introduced? Most online reviewing tools trim the rest of the file and if the reviewer misses the namespace section she can't say whether this code is doing fine or uses the wrong type.
- In a context where both types from namespaces are required, each time developer needs to use type aliases. Type aliasing is like variable naming and it can be different from one file to another. Developers may choose different names depending on the context, their experience on the subject, or even their mood!
- And regex find (and replace) operations...?

I am not sure if these can justify implementing `--type-prefix` option, but I am sure prefixing type names prevent those kind of mistakes.

By the way, #4038 looks good in covering things like this, but it's an old issue with very low priority and needs more work.

**Comment by ajcvickers** [comment] 2021-04-29 18:21
Note from triage: agreed that this is covered by #4038.

**Closed** 2022-10-16 19:32 UTC
Labels: customer-reported
