### ISSUE TITLE
Key attribute with multiple foreign keys breaks schema generation

### ISSUE THREAD

**Issue by bradmarder** [dotnet/efcore#9200] opened 2017-07-18 19:20 UTC
With the latest efcore 2 nightly bits, I came across this issue. I'm not sure why EF would not be able to determine the relationship given this schema. 

```
Unhandled Exception: System.InvalidOperationException: Unable to determine the relationship represented by navigation property 'Post.Author' of type 'User'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
```

```using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

using Microsoft.EntityFrameworkCore;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            var db = new Context();
            Console.WriteLine(db.Database.EnsureCreated());
            Console.ReadLine();
        }
    }

    public class Post
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; }

        public int AuthorUserId { get; set; }

        [ForeignKey(nameof(AuthorUserId))]
        public virtual User Author { get; set; }

        public int ContributorUserId { get; set; }

        [ForeignKey(nameof(ContributorUserId))]
        public virtual User Contributor { get; set; }
    }

    public class User
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; }

        [InverseProperty(nameof(Post.Author))]
        public virtual ICollection<Post> AuthoredPosts { get; private set; } = new HashSet<Post>();

        [InverseProperty(nameof(Post.Contributor))]
        public virtual ICollection<Post> ContributedToPosts { get; private set; } = new HashSet<Post>();
    }

    public class  Context : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
           optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=Test;Trusted_Connection=True;");
            base.OnConfiguring(optionsBuilder);
        }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            foreach (var relationship in builder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
            {
                relationship.DeleteBehavior = DeleteBehavior.Restrict;
            }
        }
        public DbSet<Post> Posts { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
```

The error doesn't occur if
1) The `Key` attribute is removed from `Post` and `User`
2) Only 1 navigation property is set

Note, this worked as expected in efcore 1.*

### Further technical details
EF Core version: 2.0.0-rtm-26360
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: win10 x64
IDE: Visual Studio 2017 Version 15.3.0 Preview 4.0

**Comment by smitpatel** [comment] 2017-07-18 19:21
dupe of #9180

**Closed** 2022-10-16 11:12 UTC
