### ISSUE TITLE
Can't translated `set.GroupBy(x=>x.Time.Year)` 

### ISSUE THREAD

**Issue by Cricle** [dotnet/efcore#29345] opened 2022-10-13 12:53 UTC
### Include your code

```C#
 set.GroupBy(x=>x.Time.Year).ToQueryString()
```

### Include stack traces

No

### Include verbose output

```text
System.InvalidOperationException:“The LINQ expression 'DbSet<TestData>()
    .GroupBy(x => x.Time.Year)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.”
```

### Include provider and version information

EF Core version:
Database provider: (Microsoft.EntityFrameworkCore.Sqlite)
Target framework: (.NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.3.3)

**Comment by ajcvickers** [comment] 2022-10-14 12:31
@Cricle What is the type of the `Time` property?

**Comment by ajcvickers** [comment] 2022-10-20 10:13
Duplicate of #19929.

**Closed by ajcvickers** 2022-10-20 10:13 UTC
Labels: customer-reported
