### ISSUE TITLE
I am getting lots of queries for a simple many-to-many projection.

### ISSUE THREAD

**Issue by VictorioBerra** [dotnet/efcore#12121] opened 2018-05-23 17:41 UTC
I have 3 tables set up in a many-to-many relationship. When I try and get all records of the parent down through the children I get a query per child. Aka `InventoryServer -> InventoryProductLine -> Products`.

### Steps to reproduce
Complete working code example (example C) https://github.com/VictorioBerra/AutoMapper.QueryableExtensions.Issue2643

## DbContext
```csharp
public class MyDbContext : DbContext
{
    public virtual DbSet<InventoryServer> InventoryServer { get; set; }
    public virtual DbSet<InventoryServerProductLine> InventoryProductLine { get; set; }
    public virtual DbSet<Product> Product { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        var migrationsAssembly = typeof(MyDbContext).GetTypeInfo().Assembly.GetName().Name;

        optionsBuilder.UseSqlServer("Data Source=(LocalDb)\\MSSQLLocalDB;database=Issue2643;trusted_connection=yes", sql =>
        {
            sql.MigrationsAssembly(migrationsAssembly);
        });
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Define composite key
        modelBuilder.Entity<InventoryServerProductLine>()
            .HasKey(bc => new { bc.InventoryServerId, bc.ProductId });

        // This explicit configuration is not needed, as I am properly naming my keys as per convention
        // https://www.learnentityframeworkcore.com/conventions#foreign-key
        // Testing has determined it does not change the query output
        //modelBuilder.Entity<InventoryServerProductLine>()
        //    .HasOne(bc => bc.Product)
        //    .WithMany(b => b.InventoryServerProductLines)
        //    .HasForeignKey(bc => bc.ProductId);

        //modelBuilder.Entity<InventoryServerProductLine>()
        //    .HasOne(bc => bc.InventoryServer)
        //    .WithMany(c => c.InventoryServerProductLines)
        //    .HasForeignKey(bc => bc.InventoryServerId);
    }

}
```

## Entities
```csharp
public class InventoryServer
{
    public InventoryServer()
    {
        this.InventoryServerProductLines = new HashSet<InventoryServerProductLine>();
    }

    public int Id { get; set; }
    public virtual string Name { get; set; }
    public virtual ICollection<InventoryServerProductLine> InventoryServerProductLines { get; set; }
}

public class InventoryServerProductLine
{
    public virtual int InventoryServerId { get; set; }
    public virtual int ProductId { get; set; }
    public InventoryServer InventoryServer { get; set; }
    public Product Product { get; set; }
}

public class Product
{
    public int Id { get; set; }
    public string Name { get; set; }
    public ICollection<InventoryServerProductLine> InventoryServerProductLines { get; set; }
}
```

## DTOs
```csharp
public class InventoryServerDto
{
    public int Id { get; set; }
    public string Name { get; set; }
    public List<InventoryServerProductLineDto> InventoryServerProductLines { get; set; }
}

public class InventoryServerProductLineDto
{
    public int InventoryServerId { get; set; }
    public int ProductId { get; set; }
    public ProductDto Product { get; set; }
}

public class ProductDto
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

## Query
```csharp
var records = context
.InventoryServer
.Select(x => new InventoryServerDto()
{
    Id = x.Id,
    Name = x.Name,
    InventoryServerProductLines = x.InventoryServerProductLines.Select(y => new InventoryServerProductLineDto()
    {
        InventoryServerId = y.InventoryServerId,
        ProductId = y.ProductId,
        Product = new ProductDto()
        {
            Id = y.Product.Id,
            Name = y.Product.Name
        }
    }).ToList()
})
.ToList();
```

### 1
```sql
exec sp_executesql N'SELECT [y].[InventoryServerId], [y].[ProductId] AS [Id], [y.Product].[Name]
FROM [InventoryProductLine] AS [y]
INNER JOIN [Product] AS [y.Product] ON [y].[ProductId] = [y.Product].[Id]
WHERE @_outer_Id = [y].[InventoryServerId]',N'@_outer_Id int',@_outer_Id=2
```

### 2
```sql
exec sp_executesql N'SELECT [y].[InventoryServerId], [y].[ProductId] AS [Id], [y.Product].[Name]
FROM [InventoryProductLine] AS [y]
INNER JOIN [Product] AS [y.Product] ON [y].[ProductId] = [y.Product].[Id]
WHERE @_outer_Id = [y].[InventoryServerId]',N'@_outer_Id int',@_outer_Id=1
```

### 3
```sql
SELECT [x].[Id], [x].[Name]
FROM [InventoryServer] AS [x]
```

### Further technical details
EF Core version: 2.0.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 64bit
IDE: Visual Studio 2017 15.7.0

**Comment by VictorioBerra** [comment] 2018-05-23 19:05
Related https://github.com/AutoMapper/AutoMapper/issues/2639

**Comment by smitpatel** [comment] 2018-05-24 05:28
We cannot lift the inner subquery so there will be multiple queries. scenario is drastically improved in #9282 in 2.1 release

**Comment by smitpatel** [comment] 2018-05-24 05:28
Duplicate of #9282

**Comment by VictorioBerra** [comment] 2018-05-24 14:15
@smitpatel I pulled down 2.1.0-rc1-final and ran my program again and got:

> 'No mapping to a relational type can be found for the CLR type 'ProductDto'.'

Do I need the core runtime+sdk for 2.1 to test this? Is some coincidence that they are both named 2.1?

**Closed** 2022-10-16 12:26 UTC
Labels: closed-duplicate, customer-reported
