### ISSUE TITLE
Error When Updating Owned Types

### ISSUE THREAD

**Issue by jedielson** [dotnet/efcore#10580] opened 2017-12-17 14:15 UTC
Describe what is not working as expected.

I have some domain classes, and do some operations with them, and some saves and updates.

The goal here is to use some DDD aproach using value objects.
When I need to save the aggregate, it's all ok.

Now, in my model, sometimes I need to execute something like this.

`ExecutionStatus = new ArtifactExecutionStatus("FINISHED");`

When I need to update, I get this exception.

When updating, I'm using the native `DbSet.Update(entity)` of ef-core, so, all cascades should be working.

How can I resolve it?

```
Exception message:
An unhandled exception has occurred while executing the request
System.InvalidOperationException: The instance of entity type 'ArtifactExecution.ExecutionStatus#ArtifactExecutionStatus' cannot be tracked because another instance with the key value 'ArtifactExecutionId:e1330424-a41f-4332-9d98-1c432d3367f8' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
Stack trace:
[11:43:34 ERR] An unhandled exception has occurred while executing the request
System.InvalidOperationException: The instance of entity type 'ArtifactExecution.ExecutionStatus#ArtifactExecutionStatus' cannot be tracked because another instance with the key value 'ArtifactExecutionId:e1330424-a41f-4332-9d98-1c432d3367f8' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState entityState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.NavigationReferenceChanged(InternalEntityEntry entry, INavigation navigation, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.NavigationReferenceChanged(InternalEntityEntry entry, INavigation navigation, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigation navigation)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges()
   at Microsoft.EntityFrameworkCore.DbContext.TryDetectChanges()
   at Microsoft.EntityFrameworkCore.DbContext.Entry[TEntity](TEntity entity)
   at Life.Workflow.Repository.Domain.ProcessExecutionRepository.UpdateAsync(ProcessExecution entity) in C:\Users\jedi_\Documents\SourceCodes\Murta\Life.Workflow\src\Life.Workflow.Repository\Domain\ProcessExecutionRepository.cs:line 26
   at Life.Workflow.Domain.Execution.Handlers.FinishTaskCommandHandler.<Handle>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Life.Workflow.Api.Controllers.ExecutionController.<FinishExecution>d__3.MoveNext() in C:\Users\jedi_\Documents\SourceCodes\Murta\Life.Workflow\src\Life.Workflow.Api\Controllers\ExecutionController.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

### Steps to reproduce

```c#
public class ProcessExecution : AggregateRoot
    {
    	public Guid ParticipantId { get; protected set; }
    
    	public Guid ProcessId { get; protected set; }
    
    	public Process.Process Process { get; protected set; }
    
    	public ICollection<ArtifactExecution> Executions { get; protected set; }
    }
    
    public class ArtifactExecution : Entity<Guid>
    {
    	public ProcessArtifact Artifact { get; set; }
    	public Guid ArtifactId { get; set; }
    
    	public Guid ExecutionId { get; protected set; }
    	public ProcessExecution Execution { get; protected set; }
    
    	public ArtifactExecutionStatus ExecutionStatus { get; protected set; }
    }
    
    public class ArtifactExecutionStatus : ValueObject<ArtifactExecutionStatus>
    {
    	public string Status { get; protected set; }
    
    	protected ArtifactExecutionStatus()
    	{
    
    	}
    
    	public ArtifactExecutionStatus(string status)
    	{
    		Status = status;
    	}
    }

class ProcessExecutionMap : IEntityTypeConfiguration<Workflow.Domain.Execution.ProcessExecution>
    {
    	public void Configure(EntityTypeBuilder<Workflow.Domain.Execution.ProcessExecution> builder)
    	{
    		builder.HasKey(x => x.Id);
    
    		builder.Property(x => x.ParticipantId)
    			.IsRequired();
    
    		builder.HasOne(x => x.Process)
    			.WithMany(x => x.Executions)
    			.HasForeignKey(x => x.ProcessId);
    
    		builder.HasMany(x => x.Executions)
    			.WithOne(x => x.Execution)
    			.HasForeignKey(x => x.ExecutionId);
    
    		builder.Ignore(x => x.Events);
    	}
    }
    
    class ArtifactExecutionMap : IEntityTypeConfiguration<ArtifactExecution>
    {
    	public void Configure(EntityTypeBuilder<ArtifactExecution> builder)
    	{
    		builder.HasKey(x => x.Id);
    
    		builder.HasOne(x => x.Execution)
    			.WithMany(x => x.Executions)
    			.HasForeignKey(x => x.ExecutionId);
    
    		builder.HasOne(x => x.Artifact)
    			.WithMany(x => x.Executions)
    			.HasForeignKey(x => x.ArtifactId);
    
    		builder.OwnsOne(x => x.ExecutionStatus, ob =>
    		{
    			ob.ToTable(nameof(ArtifactExecution));
    			ob.Property(x => x.Status)
    				.IsRequired()
    				.HasColumnName("Status")
    				.HasColumnType("varchar(50)");
    		});
    	}
    }
```

To rerproduce, just save some ArtifactExecutions and after, try update `ExecutionStatus`

### Further technical details
EF Core version: 2.0.0
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Microsoft Windows [version 10.0.16299.125]
IDE: (e.g. Visual Studio Community Edition 2017 15.5.2)

**Comment by smitpatel** [comment] 2017-12-17 23:12
Duplicate of #7340

**Comment by epitka** [comment] 2018-02-06 14:33
I am having exactly the same issue. Is there a fix for this?

**Closed** 2022-10-16 12:03 UTC
Labels: closed-duplicate
