### ISSUE TITLE
Unable to add EFCore 2.0 to repository assembly

### ISSUE THREAD

**Issue by scottz1** [dotnet/efcore#9715] opened 2017-09-06 21:54 UTC
I have a .Net 4.61 console app that references a repository/unit of work assembly. I only wish to install EF Core 2.0 in the sub-assembly, not the startup project.

Following this article fails as-is:  
https://docs.microsoft.com/en-us/ef/core/get-started/full-dotnet/existing-db

So do the following things FIRST...

Per this article
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection

in the startup project, edit .csproj file as text...

Change true to false in the first section...
<AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>

--------------------

In Manage Nuget packages for solution, make sure the startup project references Microsoft.EntityFrameworkCore.Design

Then build solution gives the following Warning...
Found conflicts between different versions of the same dependent assembly. 
Please set the "AutoGenerateBindingRedirects" property to true in the project file. 
For more information, see http://go.microsoft.com/fwlink/?LinkId=294190

So which SHOULD it be, true or false?

---------------------------------

For now ignore the warning. 
Open PMC, be sure to select the repository project in the dropdown, then run these commands...

Install-Package Microsoft.EntityFrameworkCore.SqlServer
Install-Package Microsoft.EntityFrameworkCore.Tools

That succeeds and adds the assembly references. Now run...

Scaffold-DbContext "Server=.\;Database=MyDB;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -output MyDbContext

This fails with error:
Unable to find provider assembly with name Microsoft.EntityFrameworkCore.SqlServer. Ensure the specified name is correct and is referenced by the project.

But that assembly is definitely in the references! I'm stuck.

Note: When I install the packages and run the scaffold command in the startup assembly, then it works. But then the repository assembly doesn’t reference Microsoft.EntityFrameworkCore (which is placed in the packages folder underneath the startup project), and the generated DbContext class is in the startup assembly. This will cause a circular reference when the repository assembly tries to use it.

**Comment by ajcvickers** [comment] 2017-09-09 00:03
@scottz1 Some questions to help us try to diagnose what is going on:
* Can you post your .csproj files (or an entire repro solution) so we can see what is referencing what and how those references are being made?
* What do you have selected as the default project in the PMC?
* Which application is selected as the startup application in Visual Studio?

**Comment by scottz1** [comment] 2017-09-09 04:19
Thank you for responding. The .csproj files are attached. The console app is called Test. The repository assembly where I'm trying to use EF Core 2.0 is called Data.
As I mentioned, when I run the Install-Package and Scaffold, the default project in PMC is the Data assembly.
Test is the Startup application in VS.
This Data.csproj file has been used in earlier versions of VS with EF6, so please let me know if I have inherited an incorrect setting. I removed EF6 from the Data project and commented out the code that was using it so I could get it to build in order to install EF Core.
[Test.csproj.txt](https://github.com/aspnet/EntityFrameworkCore/files/1289530/Test.csproj.txt)
[Data.csproj.txt](https://github.com/aspnet/EntityFrameworkCore/files/1289531/Data.csproj.txt)

**Comment by scottz1** [comment] 2017-09-09 16:30
Update: repro the error with the following clean VS17 steps -- not involving my project.
1. Create a new 4.6.1 console app (to be a new solution) and set it as the Startup project
2. Add a new .NET 4.6.1 class library to the solution
3. In Nuget, add Microsoft.EntityFrameworkCore.Design to the console app
4. In PMC, select the assembly project in the dropdown, then run...
Install-Package Microsoft.EntityFrameworkCore.SqlServer
5. Install-Package Microsoft.EntityFrameworkCore.Tools
6. Scaffold-DbContext "Server=.;Database=MyDB;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -output MyDbContext

Error: Unable to find provider assembly with name Microsoft.EntityFrameworkCore.SqlServer. Ensure the specified name is correct and is referenced by the project.

That assembly IS referenced in the class library.
Now try it another way. Delete the 4.6.1 class library from the solution and add another one targeting .Net Core 2.0. Repeat the above steps and it still gets the same error.

**Comment by smitpatel** [comment] 2017-09-11 21:15
Verified that tutorial is correct.

**Comment by scottz1** [comment] 2017-09-11 21:28
I assume you mean this tutorial is correct? https://docs.microsoft.com/en-us/ef/core/get-started/full-dotnet/existing-db

Here are the reasons I claim it fails:
1. it doesn't document setting AutoGenerateBindingRedirects to false or true
2. it doesn't specify what to do if you want to add EF core to non-startup project in solution, e.g. doesn't specify if that assembly can be .net 4.6.1 or to run the install-package in those, or to add ..Designer to the startup project
3. as listed in my Update post above, with a clean install of VS17.3, scaffold command fails with *empty* console project and empty class library.

Please advise if I'm doing something wrong.

**Comment by smitpatel** [comment] 2017-09-11 23:58
@scottz1 - Yes, that tutorial. I tried the repro steps you provided and I agree that the errors you are hitting are quite ambiguous and comes in a way to resolve them.

The tutorial is getting started guide to database first therefore it uses most basic project templates and default project properties. It does not cover scaffolding to non-startup project by design because that is somewhat advanced scenario and not basic one. I verified tutorial in the sense that if you follow the steps in tutorial, it would generate expected results. In your case you wanted to scaffold into non-startup project which is different from tutorial so its not incorrect. Perhaps we are lacking some docs to cover the scenario you want.

Going into the errors you encountered,
> So do the following things FIRST...
in the startup project, edit .csproj file as text...
Change true to false in the first section...
So which SHOULD it be, true or false?

This step is unnecessary. The reason it is not documented in tutorial is by default VS puts value to true in new project template. That value is supposed to work best. If you are modifying it (changing to false) then you are likely to hit issues and you need to be careful why you need to turn it off and what are possible consequences. You do *not* need to modify `AutoGenerateBindingRedirects` for EF Core purposes.

Now going through actual issues of splitting the projects,
Based on various things I tried, I encountered following behavior, 
- In classic csproj project, if you install EFCore package in ClassLibrary1 & reference ClassLibrary1 in ConsoleApp1, you will not have any EFCore related types in ConsoleApp1. Transitive package dependencies don't work in classic csproj. In new csproj (which supports .NET Core), behavior is different and package reference would be available transitively.

So in your case, your startup project does not have access to EFCore packages since they are installed in class library.
When you invoke commands, EFCore Tools will use default project from PMC as current project & Startup project from VS. Since your startup project is ConsoleApp, EF Tools tries to find EFCore.Design package there but it is not available. Hence you got the first error. This is ambiguous behavior on EF Core tools. EFCore.Tools package brings in .Design package transitively but it is invoked on different project than where it is looking for .Design package.
Since you followed the error and installed .Design Package, tools will look for SqlServer package but it is not installed in ConsoleApp either. (remember packages from ClassLibrary are not gonna be available in ConsoleApp transitively)

For the scenario you want to achieve, you want to use classlibrary as startup project (since that's where packages are installed), Do not install .Design package in ConsoleApp. Try running this command in ClassLibrary project
`Scaffold-DbContext "Server=.;Database=MyDB;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -output MyDbContext -StartupProject ClassLibrary1`
Above command successfully scaffolds database model in my ClassLibrary project.

Action items on EF side
- Should we have docs covering how to use EF Core Tools in a different project than startup since using a class library for EF Layer is common scenario.
- Even though Tools are invoked in ClassLib which is supposed to bring in .Design package, should we do something different here for old csproj? Like telling user that startup project is different & if they want to specify different startup project. For new csproj this would just work due to transitive references.

**Comment by scottz1** [comment] 2017-09-12 01:34
Thank you Smit. I added the -StartupProject switch you recommend. I got an error if the class library targets .NET Standard 2.0, so I deleted that project and added back in a new class library targeting 4.6.1. Then I added reference to MS.EFCore.Design in that project with nuget, and ran the 2 install-package commands pointed at the *class library*.
Then I again ran scaffold with -StartupProject and got the error that classlibrary4 doesn't reference MS.EFCore.Design (not the error about SqlServer).
I double-checked my console app .csproj to see if I have the AutoBinding, as you suggested. I still had it from previous testing, so I deleted it and reloaded the solution, but unfortunately I still get the error: class library doesn't reference EFCore.Design. Double-checked and found my dumb mistake that I had added MS.EFCore.RELATIONAL.Design. It's too easy to do that because Nuget doesn't filter the list to exactly match the search string--e.g. why are there dozens of matches when you browse for MS.EFCore.Design (only 1 exact match isn't at the top!)?
Anyway, I deleted that reference and added the correct reference, and I finally had success thanks to your help! Now I'll try it in the WPF app.
Question: should a class library that uses EF Core 2.0 target .NET Standard or .NET 4.6.1 (if the startup project is WPF 4.6.1)?

**Comment by ajcvickers** [comment] 2017-09-14 00:51
Notes from triage: the main take-home from this is that we need better docs for common tooling cases like scaffolding to a class library. @ajcvickers @divega to come up with a docs plan for this.

**Comment by ErikEJ** [comment] 2017-09-14 08:18
@scottz1 You can also use my EF Core Power Tools to scaffold code, and it will not require you to install any design dlls in your project.

**Comment by smitpatel** [comment] 2017-10-17 22:46
@ajcvickers - Should we close this as we have doc issues created? Or those issues do not cover this yet?

**Comment by ajcvickers** [comment] 2017-10-18 18:06
Tracking additional work in docs repo.

**Closed** 2022-10-16 11:48 UTC
Labels: closed-no-further-action, area-docs
