### ISSUE TITLE
groupby with a comparator

### ISSUE THREAD

**Issue by hu1buerger** [dotnet/efcore#28138] opened 2022-05-31 13:06 UTC
### Code

```C#
class Pizza{
  public Topping PizzaTopping {get; set;}
}

public PizzaTopping {
 public long TId {get; set;}
 public string additionalData {get; set;}
}

public PizzaContext : DbContext{
 public DbSet<Pizza> Pizzas {get; set;}
}
```

### Not translatable
```C#
from pizza in Pizzas
 group pizza by pizza.PizzaTopping
```

```
System.InvalidOperationException : The LINQ expression 'DbSet<Pizza>()
    .GroupBy(pizza => pizza.PizzaTopping)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'.
```

### translating but of wrong "type"
```C#
IEnumerable<IGrouping<PizzaTopping, Pizza>> res = from pizza in Pizzas
 group pizza by pizza.PizzaTopping.TId;
```
but this would drop my domain object

Would it be possible to use linq or the .GroupBy with a ValueComparator to group the data on the server?

**Comment by roji** [comment] 2022-05-31 14:52
To translate LINQ GroupBy to SQL, you need a Select afterwards that applies an aggregate function (Max, Count, etc.) - this is how the SQL GROUP BY clause works ([see the docs](https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators#groupby)). If you're not sure what you need, provide more context on exactly what you're trying to achieve in your query.

**Comment by ajcvickers** [comment] 2022-05-31 20:01
Duplicate of #19929.

**Comment by Hu1buerger** [comment] 2022-06-06 12:40
@roji i was trying to achieve to group the data by the id but still retain the domainobject. I was hoping that efcore is capable to let sql group by the long id and project the data to the domainobject by efcore.

Is that possible?

**Comment by roji** [comment] 2022-06-06 14:45
@Hu1buerger I suggest reading up a bit on SQL GROUP BY - as I wrote above, it's fundamentally different from .NET GroupBy: the latter simply groups objects by some key, whereas the former requires an aggregate function to reduce the objects to a single value. This is because relational databases work with tables-like structures (rows and columns), and the idea of groups which contain multiple objects (or rows) doesn't work there.

#19929 tracks implementing the .NET GroupBy on the client-side, i.e. in .NET; this means EF doesn't generate a SQL GROUP BY, but rather fetches all the rows from the database and performs the grouping there. If this is what you want, simply insert an AsEnumerabe() before the GroupBy, to explicitly ask EF for client evaluation ([see the docs](https://docs.microsoft.com/en-us/ef/core/querying/client-eval)):

```c#
var groupedBlogs = context.Blogs.AsEnumerable().GroupBy(b => b.Something);
```

Finally, note that grouping by a unique column (which I presume your long id is) is somewhat pointless - you're guaranteed to always get groups containing exactly one object. You may as well omit the GroupBy in that case.

**Comment by ajcvickers** [comment] 2022-09-25 11:45
This still fails in EF7 RC2, even though closed as duplicate of https://github.com/dotnet/efcore/issues/19929.

I'm assuming this isn't supported (See #29199), but if that's the case, then this should not be closed as a duplicate of #19929.

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'Inner' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.GetProjection(ProjectionBindingExpression projectionBindingExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.PopulateGroupByTerms(Expression keySelector, List`1 groupByTerms, List`1 groupByAliases, String name)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyGrouping(Expression keySelector, Expression shaperExpression, ISqlExpressionFactory sqlExpressionFactory)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateGroupBy(ShapedQueryExpression source, LambdaExpression keySelector, LambdaExpression elementSelector, LambdaExpression resultSelector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at Program.Main() in C:\local\code\AllTogetherNow\Daily\Daily.cs:line 100
```

```C#
public class Pizza
{
    public long Id { get; set; }
    public PizzaTopping PizzaTopping { get; set; }
}

public class PizzaTopping
{
    public long Id { get; set; }
    public string additionalData { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString, b => b.UseNetTopologySuite())
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    public DbSet<Pizza> Pizzas => Set<Pizza>();
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }

        using (var context = new SomeDbContext())
        {
            var query = from pizza in context.Pizzas
                        group pizza by pizza.PizzaTopping;

            foreach (var group in query)
            {
                Console.WriteLine($"Author: {group.Key}; Count = {group.Count()}");
            }
        }
    }
}
```

**Comment by ajcvickers** [comment] 2022-09-27 10:45
Duplicate of https://github.com/dotnet/efcore/issues/29199

**Comment by ajcvickers** [comment] 2022-09-27 14:49
@ajcvickers `group pizza by pizza.PizzaTopping` is grouping by a navigation property.

**Comment by Hu1buerger** [comment] 2022-09-27 14:51
sounds like this issue is beeing considered for `7.0.0`?

**Closed** 2022-10-16 20:35 UTC
Labels: customer-reported
