### ISSUE TITLE
Feature Request - Insert-Select, Update and Delete with Lambda

### ISSUE THREAD

**Issue by neurospeech** [dotnet/efcore#6567] opened 2016-09-18 09:01 UTC
I know EF is good for doing things object model ways, but sometimes bulk operations are very time consuming. I propose following features.

**Select Insert**
Lets say I want to send message to all customers with certain filter.

```
   db.Messages.InsertAsync( 
       db.Customers.Where( c=> 
            c.State == State.Active &&
                // note the navigation property
                c.Orders.Any( o=> 
                       o.State == State.Completed &&
                       o.OrderDate > startDate)
            )
            // select some fields...
           .Select(
                c=> new Message{
                     RecipientName = c.Name,
                     Subject = "Your order summary ",
                     Message = $"Thank you so much for your {c.Order
                           s.Count( o => 
                                o.State==State.Completed && 
                                o.OrderDate > startDate)} order(s)."
                }
            ) 
   );
```

The above query does not return any objects, it simply generates a big INSERT SELECT and executes on the server.

**Update/Delete - with Lambda**

```
   db.Customers.DeleteAsync( c=> c.State == State.Inactive &&  !c.Orders.Any());

   db.Customers.UpdateAsync( c=> c.State == State.Inactive &&  c.Orders.Any() )
       .Set( c => new {
             LastCheck = DateTime.UtcNow
        } );
```

**Comment by gdoron** [comment] 2016-09-19 07:15
Probably an exact duplicate of #795.

**Closed** 2022-10-16 09:58 UTC
