### ISSUE TITLE
Unnecessary join when GroupBy and Select

### ISSUE THREAD

**Issue by kern068** [dotnet/efcore#27297] opened 2022-01-27 15:32 UTC
When I do this request 

```sql
_context.Set<OrderUserEntity>()
  .Where(x => userIds.Contains(x.UserId))
  .GroupBy(
      x => new { x.UserId, x.Order.CreatedDate.Month }
  )
  .Select(x => new UserOrderStatisticByMonthModel()
  {
      UserId = x.Max(u => u.UserId),
      Month = x.Min(u => u.Order.CreatedDate),
      Total = x.Count(),
  }).ToListAsync();
```
Efcore generate this request

```sql
SELECT MAX([o].[UserId]) AS [UserId], MIN([o1].[CreatedDate]) AS [Month], COUNT(*) AS [Total]
FROM [OrderUsers] AS [o]
INNER JOIN [Orders] AS [o0] ON [o].[OrderId] = [o0].[Id]
INNER JOIN [Orders] AS [o1] ON [o].[OrderId] = [o1].[Id]
WHERE [o].[UserId] = 339593
GROUP BY [o].[UserId], DATEPART(month, [o0].[CreatedDate])
```

But we expect this one (without the double join on the Orders table)
```sql
SELECT MAX([o].[UserId]) AS [UserId], MIN([o0].[CreatedDate]) AS [Month], COUNT(*) AS [Total]
FROM [OrderUsers] AS [o]
INNER JOIN [Orders] AS [o0] ON [o].[OrderId] = [o0].[Id]
WHERE [o].[UserId] = 339593
GROUP BY [o].[UserId], DATEPART(month, [o0].[CreatedDate])
```
And you can find below the entities and the configurations

```csharp
public class OrderEntity
{
    public int Id { get; private set; }

    public IEnumerable<OrderUserEntity> OrderUsers { get; private set; }
}
```

```csharp
public class OrderUserEntity
{
    public int Id { get; private set; }

    public int UserId { get; private set; }

    public int OrderId { get; private set; }

    public OrderEntity Order { get; private set; }
}
```

```csharp
public sealed class OrderEntityConfiguration : IEntityTypeConfiguration<OrderEntity>
{
    public void Configure(EntityTypeBuilder<OrderEntity> builder)
    {
        builder.ToTable("Orders");

        builder.HasKey(x => x.Id);

        builder.Property(x => x.Id).ValueGeneratedOnAdd();
    }
}
```

```csharp
public sealed class OrderUserEntityConfiguration : IEntityTypeConfiguration<OrderUserEntity>
{
    public void Configure(EntityTypeBuilder<OrderUserEntity> builder)
    {
        builder.ToTable("OrderUsers");

        builder.HasKey(x => x.Id);

        builder.Property(x => x.Id).ValueGeneratedOnAdd();

        builder.HasIndex(x => new { x.OrderId, x.UserId }).IsUnique();

        builder.HasOne(x => x.Order).WithMany(x => x.OrderUsers).HasForeignKey(x => x.OrderId);
    }
}
```

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 6.0.1
Operating system: Macos 12.1
IDE: Visual Studio Code 1.63.2

**Comment by smitpatel** [comment] 2022-04-27 01:53
Duplicate of #27077

**Closed** 2022-10-16 20:23 UTC
Labels: closed-duplicate, customer-reported
