### ISSUE TITLE
Migrations drop and recreate foreign keys - even on "empty" migrations?

### ISSUE THREAD

**Issue by bragma** [dotnet/efcore#4288] opened 2016-01-12 15:04 UTC
I'm puzzled by the migrations generated by ef7. It seems that they first drop all FKs, then they create them back. I'm not sure why this is needed. What's even more puzzling is that the migrations generator can't understand a "useless" or "empty" migration, and still generate one even if nothing has changed in the code or DB. Just adding a migration creates code that drop and recreates FKs.
Is understanding if a migration is required totally in developer's hands? I hoped for the generator to understand if anything changed and else report "no migrations needed" or something similar...
If it's not the case, I foresee a lot of troubles ahead. I.e. developer creating migrations just because they don't recall if anything has been changed or forgetting to create migrations.

**Comment by flagbug** [comment] 2016-01-12 15:43
I'm seeing this too, especially with Asp.Net Identity

See https://github.com/aspnet/Identity/issues/697

**Comment by smitpatel** [comment] 2016-01-12 16:11
dupe of #3751 . It has been fixed already and will ship in RC2.

**Comment by bragma** [comment] 2016-01-12 16:30
Thanks for pointing out the fix. I failed to see the issue closed while searching for clues.

**Closed** 2022-10-16 09:24 UTC
