### ISSUE TITLE
Query: Support Include after GroupBy

### ISSUE THREAD

**Issue by Tratcher** [dotnet/efcore#3418] opened 2015-10-13 15:27 UTC
_From @SaphuA on October 9, 2015 9:27_

From what I understand doing a Include before a GroupBy is expected not to work. However, a recommended workaround would be to move it to after the GroupBy. This doesn't seem to be working either. Is this expected as well?

This simple query:

``` C#
_context.Stories
    .GroupBy(c => c.Title)
    .Select(c => c.First())
    .Include(c => c.Comments)
    .ToList();
```

Throws:

```
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=The expression '{[c] => First()}.Comments' passed to the Include operator could not be bound.
  Source=EntityFramework.Core
  StackTrace:
       at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<IncludeNavigations>b__29_0(IncludeQueryAnnotation annotation)
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel)
       at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
       at Microsoft.Data.Entity.Storage.RelationalDatabase.CompileQuery[TResult](QueryModel queryModel)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.Data.Entity.Query.CompiledQueryCache.CompileQuery(IDatabase database, MethodInfo compileMethodInfo, Type resultItemType, QueryModel queryModel)
       at Microsoft.Data.Entity.Query.CompiledQueryCache.<>c__7`1.<Execute>b__7_0(Expression q, IDatabase ds)
       at Microsoft.Data.Entity.Query.CompiledQueryCache.GetOrAdd(Expression query, QueryContext queryContext, IDatabase database, Boolean isAsync, Func`3 compiler)
       at Microsoft.Data.Entity.Query.CompiledQueryCache.Execute[TResult](Expression query, IDatabase database, QueryContext queryContext)
       at Microsoft.Data.Entity.Query.EntityQueryProvider.Execute[TResult](Expression expression)
       at Remotion.Linq.QueryableBase`1.GetEnumerator()
       at Microsoft.Data.Entity.EntityFrameworkQueryableExtensions.IncludableQueryable`2.GetEnumerator()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Adventure.Web.Controllers.LibraryController.Index() in C:\Users\Tijs\Repos\Adventure\src\Adventure.Web\Controllers\LibraryController.cs:line 33
  InnerException: 
```

_Copied from original issue: aspnet/Home#978_

**Comment by Tratcher** [comment] 2015-10-13 15:27
_From @Eilon on October 9, 2015 21:47_

@divega @rowanmiller

**Comment by rowanmiller** [comment] 2015-12-10 20:58
Verified that this still throws on the latest bits, though the exception is now different.

The exception occurs regardless of there the Include is placed (before or after the GroupBy).

```
Unhandled Exception: System.ArgumentException: The given expression '{[p] => First()}' does not contain the searched expression '[<generated>_1]' in a nested NewExpression with member assignments or a MemberBin
dingExpression.
Parameter name: fullExpression
   at Remotion.Linq.Clauses.ExpressionVisitors.AccessorFindingExpressionVisitor.FindAccessorLambda(Expression searchedExpression, Expression fullExpression, ParameterExpression inputParameter)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by neridonk** [comment] 2016-02-25 14:25
+1

**Comment by mikary** [comment] 2016-04-13 20:39
Calling Include after `GroupBy` is actually a more complex situation due to the need to find the proper `IQuerySource` from the resulting expression/sub-query. The recommended solution for this would be to use the `Include` before `GroupBy`; however, that feature is not working yet and should be fixed as a part of #3101.

Notes: `IncludeResultOperator.GetQuerySource` and `EntityQueryModelVisitor.IterateCompositeMemberExpression` both assume that the `NavigationPropertyPath` is either a `QuerySourceReferenceExpression` or a nested `MemberExpression`, which is not true in this case.

**Comment by anpete** [comment] 2016-05-04 22:45
@mikary Did you confirm that the query doesn't work with the Include before the GroupBy? This should be working and we have a test for it (f001a99d)

**Comment by mikary** [comment] 2016-05-04 23:20
@anpete I hadn't looked into it yet, but I just ran a sample app and it appears to be working. I passed this one on to @maumar because he said he was working the related issue.

**Comment by maumar** [comment] 2016-05-25 21:36
poaching per discussion with @anpete

**Comment by maumar** [comment] 2016-05-25 23:57
scenario works fine if one performs include before groupby, as follows:

```cs
                var result = ctx.Stories
                    .Include(c => c.Comments)
                    .GroupBy(c => c.Title)
                    .Select(c => c.First())
                    .ToList();
```

clearing milestone for re-triage

**Comment by AndriySvyryd** [comment] 2019-08-22 17:53
@smitpatel Is this wont fix/not needed now?

**Comment by smitpatel** [comment] 2019-08-22 17:58
Duplicate of #16752

**Closed** 2022-10-16 09:12 UTC
