### ISSUE TITLE
 Cannot consume scoped service from singleton

### ISSUE THREAD

**Issue by alexander-bobrov** [dotnet/efcore#27326] opened 2022-01-31 22:19 UTC
I'm trying run my app with this command **dotnet run --verbose .\MailHub.csproj** and I'm keep getting exception below
In Visual Studio everything **works** fine

There's the way I'm setting my DbContexts
```
services.AddDbContext<MailHubContext>(x => x.UseSqlite(options.ConnectionString), optionsLifetime: ServiceLifetime.Singleton);
services.AddDbContextFactory<MailHubContext>(x => x.UseSqlite(options.ConnectionString));
```

And there's full code sample:
https://github.com/alexander-bobrov/MailHub/blob/development/src/Database/Configuration/DatabaseExtension.cs

I guess it's connected with this issue:
https://github.com/dotnet/efcore/issues/25164

EF Core version: 6.0.1
Database provider: SqlLite
Target framework:. .NET 6.0
Operating system: Windows 10 Home 21H1 **and** Ubuntu 20.04
IDE: Microsoft Visual Studio Community 2022 (64-bit)  Version 17.0.5

```
[01:12:52 FTL] Start up failed
System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.EntityFrameworkCore.IDbContextFactory`1[Database.MailHubContext] Lifetime: Singleton ImplementationType: Microsoft.EntityFrameworkCore.Internal.DbContextFactory`1[Database.MailHubContext]': Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Database.MailHubContext]' from singleton 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Database.MailHubContext]'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: MailHub.Services.CleanupService.CleanupService': Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Database.MailHubContext]' from singleton 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Database.MailHubContext]'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: MailHub.Services.MailService.SmtpService': Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Database.MailHubContext]' from singleton 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Database.MailHubContext]'.) (Error while validating the service descriptor 'ServiceType: MailHub.Services.MessageService.IMessageService Lifetime: Scoped ImplementationType: MailHub.Services.MessageService.MessageService': Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Database.MailHubContext]' from singleton 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Database.MailHubContext]'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.EntityFrameworkCore.IDbContextFactory`1[Database.MailHubContext] Lifetime: Singleton ImplementationType: Microsoft.EntityFrameworkCore.Internal.DbContextFactory`1[Database.MailHubContext]': Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Database.MailHubContext]' from singleton 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Database.MailHubContext]'.
 ---> System.InvalidOperationException: Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Database.MailHubContext]' from singleton 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Database.MailHubContext]'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitScopeCache(ServiceCallSite scopedCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateCallSite(ServiceCallSite callSite)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at MailHub.Program.Main(String[] args) in C:\Projects\MailHub\src\MailHub\Program.cs:line 22
 ---> (Inner Exception #1) System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: MailHub.Services.CleanupService.CleanupService': Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Database.MailHubContext]' from singleton 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Database.MailHubContext]'.
 ---> System.InvalidOperationException: Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Database.MailHubContext]' from singleton 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Database.MailHubContext]'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitScopeCache(ServiceCallSite scopedCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateCallSite(ServiceCallSite callSite)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)<---

 ---> (Inner Exception #2) System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: MailHub.Services.MailService.SmtpService': Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Database.MailHubContext]' from singleton 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Database.MailHubContext]'.
 ---> System.InvalidOperationException: Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Database.MailHubContext]' from singleton 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Database.MailHubContext]'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitScopeCache(ServiceCallSite scopedCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateCallSite(ServiceCallSite callSite)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)<---

 ---> (Inner Exception #3) System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: MailHub.Services.MessageService.IMessageService Lifetime: Scoped ImplementationType: MailHub.Services.MessageService.MessageService': Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Database.MailHubContext]' from singleton 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Database.MailHubContext]'.
 ---> System.InvalidOperationException: Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Database.MailHubContext]' from singleton 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Database.MailHubContext]'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitScopeCache(ServiceCallSite scopedCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitScopeCache(ServiceCallSite scopedCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateCallSite(ServiceCallSite callSite)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)<---
```

**Comment by alexander-bobrov** [comment] 2022-01-31 22:53
With dotnet run MailHub.dll everything also works

**Comment by ajcvickers** [comment] 2022-02-01 09:11
@alexander-bobrov Why are you doing different registration in debug builds? is it the debug builds or the release builds that are failing?

**Comment by alexander-bobrov** [comment] 2022-02-02 04:44
> @alexander-bobrov Why are you doing different registration in debug builds? is it the debug builds or the release builds that are failing?

Context for ASP .Net controllers and factory for HostedServices(since there’s no scopes). Error appears in both debug/release.

**Comment by ajcvickers** [comment] 2022-02-04 17:06
@alexander-bobrov I am not able to reproduce this.

**Comment by esterity** [comment] 2022-02-10 02:17
Then we can close it I suppose

**Closed** 2022-10-16 20:24 UTC
Labels: closed-no-further-action, customer-reported
