### ISSUE TITLE
Cosmos Nested List Issue

### ISSUE THREAD

**Issue by msivri** [dotnet/efcore#19956] opened 2020-02-17 18:00 UTC
I was able to re-create an issue where EF Core Comos does not read the data from the collection when there is more than one collection on the 3rd level. This is difficult to explain for me but I have a repo up that can just run with steps to reproduce below. 

### Steps to reproduce
Simple GitHub Repo: https://github.com/msivri/CosmosDB.NestedTest
 
1. Create a model "Libraries" with one collection "Books".
2. Create a collection in "Books" called "Pages"
3. Create two collections in "Pages" called "Notes" and "Highlights"
4. Setup the model builder to map "OwnsMany" on all the parents (See CosmosContext.cs).
5. SaveChanges to Cosmos with Books, Pages, and Highlights (Program.cs). Highlights are present in Cosmos explorer. 
6. Read from Cosmos using First(). **Highlights are missing from the result** but are in the Cosmos explorer. (Program.cs)
 
### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: NET Core 3.1
Operating system: Windows 10
IDE:   Visual Studio 2019 16.4.1

**Comment by ajcvickers** [comment] 2020-02-17 21:09
@msivri Are you using 3.1.0 or 3.1.1?

**Comment by msivri** [comment] 2020-02-18 00:49
3.1.1

**Comment by ajcvickers** [comment] 2020-02-19 17:32
@msivri Looks like this is a duplicate of #19159 which is merged for the 3.1.3 patch tentatively planned for March.

**Closed** 2022-10-16 18:11 UTC
Labels: customer-reported
