### ISSUE TITLE
 Defaults cannot be created on columns with an IDENTITY attribute

### ISSUE THREAD

**Issue by dvdobrovolskiy** [dotnet/efcore#5995] opened 2016-07-06 14:32 UTC
### Steps to reproduce

Model with such identity field
[Key]
public int NoteId { get; set; }

generated default value and fails to update db
            migrationBuilder.AddColumn<int>(
                name: "NoteId",
                table: "Notes",
                nullable: false,
                defaultValue: 0)
                .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

in DB context I have 
public DbSet<Note> Notes { get; set; }

EF Core version: rtm
Operating system: win10
Visual Studio version: 2015 3
Other details about my project setup:

**Comment by flagbug** [comment] 2016-07-08 17:44
I'm seeing this too, if I add an integer column and configure it like

```
    e.Property(p => p.SomeInteger)
        ValueGeneratedOnAdd();
```

**Comment by rowanmiller** [comment] 2016-07-15 17:13
Closing this one as a dupe of https://github.com/aspnet/EntityFramework/issues/6035 as the other issue has more discussion etc.

**Closed** 2022-10-16 09:49 UTC
