### ISSUE TITLE
In-query Filtered Include()?

### ISSUE THREAD

**Issue by brent-russell** [dotnet/efcore#3093] opened 2015-09-10 17:41 UTC
``` C#
if (includeChildren)
{
    if (activeOnly)
    {
        query = query.Include(t => t.Children.Where(c => c.IsActive));
```

Are there any plans to support the above syntax, or another method to filter Include() content in-query?

**Comment by Suchiman** [comment] 2015-09-10 18:59
:+1: I'd really like to see something like this, always bothered me in EF6.

**Comment by rowanmiller** [comment] 2015-09-10 19:18
Duplicate of https://github.com/aspnet/EntityFramework/issues/1833

**Closed** 2022-10-16 09:08 UTC
