### ISSUE TITLE
Lazy loading with derived types

### ISSUE THREAD

**Issue by aalvarez255** [dotnet/efcore#13980] opened 2018-11-19 17:23 UTC
Hello,

I'm getting the following exception when using proxied lazy loading along with derived types:

 `InvalidOperationException: Error generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.DetachedLazyLoadingWarning: An attempt was made to lazy-load navigation property 'OtherEntity' on detached entity of type 'EntityBProxy'. Lazy-loading is not supported for detached entities or entities that are loaded with 'AsNoTracking()'.'. This exception can be suppressed or logged by passing event ID 'CoreEventId.DetachedLazyLoadingWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.`

These are my entities:
```C#
 public abstract class EntityA
 {
        public int Id { get; set; }

        [NotMapped]
        public abstract bool Condition { get; }
 }

 public class EntityB : EntityA
 {
        public int OtherEntityId { get; set; }
        public virtual OtherEntity OtherEntity { get; set; }

        public override bool Condition
        {
            get
            {
                return OtherEntity.Name == "AA";
            }
        }
 }

public class OtherEntity
{
        public int Id { get; set; }
        public string Name { get; set; }
 }
```

Here the DbContext class and DbSets:

```C#
 public class ApplicationDbContext : DbContext
    {
        public DbSet<EntityA> AEntities { get; set; }
        public DbSet<EntityB> BEntities { get; set; }
        public DbSet<OtherEntity> OtherEntities { get; set; }

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
        { }
    }
```

And the Lazy Loading set up:
```C#
services.AddDbContext<ApplicationDbContext>(options =>
               options.UseLazyLoadingProxies().
                   UseSqlServer(Configuration["ConnectionStrings:DefaultConnection"]));
```

**When I execute the following query:**

```C#
_db.AEntities.Where(x => x.Condition).ToList();
```

The `InvalidOperationException` is fired (please note that I'm not using `.AsNoTracking()`).

### Steps to reproduce
Sample project is available at: https://github.com/aalvarez255/efcore-lazyloading

Just run the solution and call a `GET /api/values`

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio Professional 2017 15.8.9

**Comment by ajcvickers** [comment] 2018-11-20 00:43
Notes for triage: this is due to client-evaluation of `Condition` on entity instances that have been created but not tracked, which then attempts to trigger lazy loading. We likely have a duplicate of this, but I haven't  found it yet...

@aalvarez255 Workaround is to move `.ToList()` before the condition:
```C#
_db.AEntities.ToList().Where(x => x.Condition);
```
Note that EF can't translate this Where clause to SQL anyway (because it uses an opaque call, not an expression tree) so this essentially does what EF would have done anyway.

Full stack trace:
```

Unhandled Exception: System.InvalidOperationException: Error generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.DetachedLazyLoadingWarning: An attempt was made to lazy-load navigation property 'OtherEntity' on detached entity of type 'EntityBProxy'. Lazy-loading is not supported for detached entities or entities that are loaded with 'AsNoTracking()'.'. This exception can be suppressed or logged by passing event ID 'CoreEventId.DetachedLazyLoadingWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`2.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, TParam1 arg1, TParam2 arg2, Exception exception)
   at Microsoft.EntityFrameworkCore.Internal.CoreLoggerExtensions.DetachedLazyLoadingWarning(IDiagnosticsLogger`1 diagnostics, DbContext context, Object entityType, String navigationName)
   at Microsoft.EntityFrameworkCore.Internal.LazyLoader.ShouldLoad(Object entity, String navigationName, NavigationEntry& navigationEntry)
   at Microsoft.EntityFrameworkCore.Internal.LazyLoader.Load(Object entity, String navigationName)
   at Microsoft.EntityFrameworkCore.Proxies.Internal.LazyLoadingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.EntityBProxy.get_OtherEntity()
   at EntityB.get_Condition() in C:\Stuff\TwoOneCore\TwoOneCore\Program.cs:line 32
   at Castle.Proxies.Invocations.EntityB_get_Condition.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.EntityBProxy.get_Condition()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.Main() in C:\Stuff\TwoOneCore\TwoOneCore\Program.cs:line 88
```
Reopro code:
```C#
public abstract class EntityA
{
    public int Id { get; set; }

    [NotMapped]
    public abstract bool Condition { get; }
}

public class EntityB : EntityA
{
    public int OtherEntityId { get; set; }
    public virtual OtherEntity OtherEntity { get; set; }

    public override bool Condition
    {
        get
        {
            return OtherEntity.Name == "AA";
        }
    }
}

public class OtherEntity
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class Order
{
    public int Id { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLazyLoadingProxies()
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    public DbSet<EntityA> AEntities { get; set; }
    public DbSet<EntityB> BEntities { get; set; }
    public DbSet<OtherEntity> OtherEntities { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new EntityB {OtherEntity = new OtherEntity()});

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            context.AEntities.ToList().Where(x => x.Condition);
        }
    }
}
```

**Closed** 2022-10-16 13:40 UTC
Labels: customer-reported
