### ISSUE TITLE
The specified deps.json [..] does not exist

### ISSUE THREAD

**Issue by bwjunkie** [dotnet/efcore#23300] opened 2020-11-13 01:33 UTC
as per Brice I'm resubmitting this problem as a new issue:

Works in CLI (sometimes) but not in PM

1- create new proj  
2- add Nuget EntityFrameworkCore , Relational , Tools , SqlServer
3- Package Manager
4 -PM> scaffold-dbcontext "server=localhost;user id=test;password=test;database=test" -usedatabasenames  Microsoft.EntityFrameworkCore.SqlServer

output
The specified deps.json [..] does not exist
The specified deps.json [C:\Users\joshm\source\repos\console_test_EF_deps.json\console_test_EF_deps.json.deps.json] does not exist

adding -verbose is shown below:

C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\Users\joshm\source\repos\console_test_EF_deps.json\console_test_EF_deps.json.deps.json --additionalprobingpath C:\Users\joshm\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --additionalprobingpath C:\Microsoft\Xamarin\NuGet C:\Users\joshm\.nuget\packages\microsoft.entityframeworkcore.tools\5.0.0\tools\netcoreapp2.0\any\ef.dll dbcontext scaffold "server=localhost;user id=test;password=test;database=test" Microsoft.EntityFrameworkCore.SqlServer --json --use-database-names --verbose --no-color --prefix-output --assembly C:\Users\joshm\source\repos\console_test_EF_deps.json\console_test_EF_deps.json.dll --startup-assembly C:\Users\joshm\source\repos\console_test_EF_deps.json\console_test_EF_deps.json.dll --project-dir C:\Users\joshm\source\repos\console_test_EF_deps.json\ --language C# --working-dir C:\Users\joshm\source\repos\console_test_EF_deps.json --root-namespace console_test_EF_deps.json
The specified deps.json [C:\Users\joshm\source\repos\console_test_EF_deps.json\console_test_EF_deps.json.deps.json] does not exist 

Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: Core 3.1
Operating system:
IDE: VS 16.8.1

REPO:

https://github.com/bwjunkie/console_test_EF_deps.json

![image](https://user-images.githubusercontent.com/1482878/99017100-e2d33c00-2514-11eb-91b9-2aa7d159ba68.png)

**Comment by bricelam** [comment] 2020-11-16 17:16
Sorry, that's a dupe. Your previous comment led me to believe that the .deps.json wasn't being generated. But, as with the other reports, it's just not looking in the right place. If you update to EF Core 5.0, you should get a better error message.

**Comment by bricelam** [comment] 2020-11-16 17:16
Sorry, that's a dupe. Your previous comment led me to believe that the .deps.json wasn't being generated. But, as with the other reports,  it's just not looking in the right place. If you update to EF Core 5.0, you should get a better error message.

**Comment by ajcvickers** [comment] 2020-11-23 16:58
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:09 UTC
Labels: customer-reported
