### ISSUE TITLE
Query performance issue: how to found the reason? and which toools to use? 

### ISSUE THREAD

**Issue by domenicocanavero** [dotnet/efcore#34369] opened 2024-08-06 15:09 UTC
I wrote a query to load a grid by page. 

**1. Query version 1**
This is my first query version to load the grid on the LoadGrid event using the parameters skip and take.
The performance are very poor when the skip value is big, with the maximum value, 34064, **this query require about 2 minutes!**

        skip = 34064;
        take = 16;
        var orders = await (from oH in dbcontext.HisOrderHeader.Include(oo => oo.HisOrderLines).AsSplitQuery()
                                 join cC in dbcontext.HisOHContainer.AsSplitQuery() on oH.Id equals cC.IdHisOrderHeader
                                 join dD in dbcontext.HisOHCDivision.AsSplitQuery() on cC.Id equals dD.IdHisOhcontainer
                                 orderby oH.EndScrap, cC.Id descending
                                 select new JoinContainersObjDto { Order = oH, Sheet = null, Container = cC, Division = dD })
                                                                               .AsNoTracking().Skip(skip).Take(take).ToListAsync();

**2. Query version 2**
The same query with **cC.Id** ordered ascending instead descending **require 1 sec.!**
        
        skip = 34064;
        take = 16;
        var orders = await (from oH in dbcontext.HisOrderHeader.Include(oo => oo.HisOrderLines).AsSplitQuery()
                                 join cC in dbcontext.HisOHContainer.AsSplitQuery() on oH.Id equals cC.IdHisOrderHeader
                                 join dD in dbcontext.HisOHCDivision.AsSplitQuery() on cC.Id equals dD.IdHisOhcontainer
                                 orderby oH.EndScrap, cC.Id
                                 select new JoinContainersObjDto { Order = oH, Sheet = null, Container = cC, Division = dD })
                                                                               .AsNoTracking().Skip(skip).Take(take).ToListAsync();

It was not easy to found what delaying my query and I don't know why different order of the column affects so much the performance.

The cC.Id is the primary key of the table.

Moreover, the log of the dbcontext in this case did not help me because the Executed sql Command in the dbcontext log have very good performance for both queries versions.

My question:
In case of similar issues with EF, which tools, procedures, docs you suggest to discover the reasons?
Thanks

**Comment by roji** [comment] 2024-08-06 15:46
@domenicocanavero your question isn't really related to EF - EF simply translates your LINQ query to SQL, and that gets executed like other, non-EF SQL queries on the databases.

As a general rule, I suggest inspecting the SQL produced by EF; ifthe SQL seems like a bad or inefficient translation, then that's indeed a question for EF - you'd open an issue with a minimal repro, where we could see both the source LINQ query and the generated SQL. However, in this case it seems like the problem isn't with the translation - WD is translating correctly, based on your "ascending" in the query; you're just asking why the SQL runs slowly on your database.

For these cases, I suggest turning to a forum dedicated to database performance, dedicated to the specific database product you're using (note that you haven't mentioned that above). You'll also have to provide more details - it's generally impossible to answer questions like "why is this query slow" given just a query, without having the full picture (e.g. what indexes are defined on your database?).

I'm going to go ahead and close this question as not related to EF, but if you suspect EF is somehow doing a bad job here, post back with specific details and we can revisit.

**Closed by roji** 2024-08-06 15:46 UTC
Labels: customer-reported

**Comment by domenicocanavero** [comment] 2024-08-07 07:34
@roji, for me the problem is not that SQL runs slowly because, in both cases, if I run the SQL commands get from the dbcontext log the results are the same, very fast, less of 1 sec.
I would like to understand what happens with EF in the execution of the first query.

Attached there are the log files and the source code of both queries.

Strange, what you think?
Any suggestions to investigate?

Thanks
[codefast.txt](https://github.com/user-attachments/files/16519903/codefast.txt)
[codeslow.txt](https://github.com/user-attachments/files/16519904/codeslow.txt)
[logfast.txt](https://github.com/user-attachments/files/16519905/logfast.txt)
[logslow.txt](https://github.com/user-attachments/files/16519906/logslow.txt)

**Comment by ajcvickers** [comment] 2024-08-07 08:08
> I would like to understand what happens with EF in the execution of the first query.

Can you be more specific about what you mean by this? Everything in the log files looks consistent and correct. EF executes the query and then fetches the results.

**Comment by domenicocanavero** [comment] 2024-08-07 08:15
... but in the first query this is the execution time reguired in seconds:
07-08-2024 09:14:28 [Information] ***** END QUERY time=123.053 *****

In the second is this:
07-08-2024 09:09:06 [Information] ***** END QUERY time=0.227 *****

and both Execution Command from dbcontext log are executed from SSMS in less of a second.

The difference between the query is descending instead ascending on a column.

Why there is this big difference on the execustion time between the linq-EF query and SSMS-SQL query?

**Comment by ajcvickers** [comment] 2024-08-07 08:26
@domenicocanavero Are you asking about the time to execute the query and get back a reader, or the time to read the results?

**Comment by roji** [comment] 2024-08-07 08:28
@domenicocanavero if I understand correctly, your query is slow with "descending" and fast without it, **regardless** of whether you test with EF code (LINQ query), or whether you paste the SQL directly into SSMS. If that's the case, then that's not en EF question, but rather a general database/SQL question.

**Comment by domenicocanavero** [comment] 2024-08-07 08:33
... sorry for my english ...
NO.
With SSMS-SQL is fast in both cases!

and my question is:
Instead, why there is this big difference with EF-Linq?

Thanks

**Comment by roji** [comment] 2024-08-07 08:35
It's very likely there's some difference between the SQL being executed by EF, and the SQL you're testing in SSMS. Please double-check the two, and post the SQL on this issue as well as specify which database you're using.

**Comment by domenicocanavero** [comment] 2024-08-07 09:00
With SSMS I used the Sql command from the dbcontext log.

My DB:
![image](https://github.com/user-attachments/assets/3f697a17-f025-4574-bf5f-a7cc0ab4bfba)

Attached the execution of both queries with SSMS.
![SSMSquery1](https://github.com/user-attachments/assets/c9bb9d9a-0ff7-415b-a33a-9c5969ddc9aa)
![SSMSquery2](https://github.com/user-attachments/assets/8c6000ef-38ad-4a2a-84c0-8907bb0531b7)

**Comment by roji** [comment] 2024-08-07 09:09
@domenicocanavero I don't see the "descending" difference you were mentioning before.

In any case, the SQLs aren't identical - replacing the parameters by constants can significantly change the way that a query executes, and could explain the performance difference here. EF currently always parameterizes the argument to Skip and Take; we're aware that this has negative performance consequences for some queries - this is tracked by #28632.

I'll also note that doing pagination over a big dataset (OFFSET 34080 is big) is generally not a good idea performance-wise; I recommend reading [our docs on the subject](https://learn.microsoft.com/en-us/ef/core/querying/pagination). Switching to the more efficient keyset pagination would also make this issue go away for you.

**Comment by roji** [comment] 2024-08-07 09:09
Duplicate of #28632

**Comment by domenicocanavero** [comment] 2024-08-07 12:27
... one more comment about ...

**This required 2 minutes**:
                   
            skip = 34064;
            take = 16;
            var orders = await (from oH in dbcontext.HisOrderHeader.Include(oo => oo.HisOrderLines).AsSplitQuery()
                                 join cC in dbcontext.HisOHContainer.AsSplitQuery() on oH.Id equals cC.IdHisOrderHeader
                                 join dD in dbcontext.HisOHCDivision.AsSplitQuery() on cC.Id equals dD.IdHisOhcontainer
                                orderby oH.EndScrap, cC.Id descending
                                select new JoinContainersObjDto { Order = oH, Sheet = null, Container = cC, Division = dD })
                                                                                           .AsNoTracking().Skip(skip).Take(take).ToListAsync();


**The SQL command generated by EF for the previous query required 1 second**:

declare @skip int = 34080, @take int = 16
SELECT [h].[Id], [h].[BomQty], [h].[BomQtyCalc], [h].[BomQtyTot], [h].[Created], [h].[Delivered], [h].[Depth], [h].[EndCut], 
             [h].[EndScrap], [h].[Height], [h].[ItemId], [h].[Material], [h].[NameOrder], 
	     [h].[NetWeight], [h].[ProdPriority], [h].[QtySched], [h].[ScrapDuration], [h].[ScrapFraction], [h].[ScrapOperator1], 
             [h].[ScrapOperator2], [h].[StartCut], [h].[StartScrap], [h].[UserCodeEndCut], 
	     [h].[UserCodeEndScrap], [h].[UserCodeStartCut], [h].[UserCodeStartScrap], [h].[UserNameEndCut], 
             [h].[UserNameEndScrap], [h].[UserNameStartCut], [h].[UserNameStartScrap], [h].[Width], [h].[WorkCenter], 
             [h0].[Id], [h1].[Id], [h0].[ContainerId], [h0].[Description], [h0].[HasRFID], [h0].[IdHisOrderHeader], [h0].[Prg], 
             [h0].[ProductionKey], [h0].[RfidCode], [h1].[IdHisOHContainer], [h1].[ItemId], [h1].[Lot], [h1].[Moved], 
             [h1].[NameOrderFrom], [h1].[NumPartsExpected], [h1].[NumPartsPresent], [h1].[Prg], [h1].[PrgContainerFrom], 
             [h1].[Supplier]
      FROM [M2FMetallurgy].[HisOrderHeader] AS [h]
      INNER JOIN [M2FMetallurgy].[HisOHContainer] AS [h0] ON [h].[Id] = [h0].[IdHisOrderHeader]
      INNER JOIN [M2FMetallurgy].[HisOHCDivision] AS [h1] ON [h0].[Id] = [h1].[IdHisOHContainer]
      ORDER BY [h].[EndScrap], [h0].[Id] DESC, [h].[Id], [h1].[Id]
      OFFSET @skip ROWS FETCH NEXT @take ROWS ONLY

I have not found any possible explanation in you suggested reading.

**Comment by roji** [comment] 2024-08-07 12:54
@domenicocanavero as I said above, please always compare two **SQL queries**, not a LINQ query and a SQL query. That is, you can look at EF's logs to see what SQL it generated, and then try running that precise SQL in SSMS. If you post two different SQLs, we can also discuss that, but I have no idea exactly what you're asking in your last message.

**Comment by domenicocanavero** [comment] 2024-08-07 13:14
> hat is, you can look at EF's logs to see what SQL it generated, and then try running that precise SQL in SSMS.

sorry, but in all my comments I have compare always the linq query with its SQL command generate by EF's log.

this is the the SQL query from EF's log:


> **The SQL command generated by EF for the previous query required 1 second**:
> 
> declare @Skip int = 34080, @take int = 16 SELECT [h].[Id], [h].[BomQty], [h].[BomQtyCalc], [h].[BomQtyTot], [h].[Created], [h].[Delivered], [h].[Depth], [h].[EndCut], [h].[EndScrap], [h].[Height], [h].[ItemId], [h].[Material], [h].[NameOrder], [h].[NetWeight], [h].[ProdPriority], [h].[QtySched], [h].[ScrapDuration], [h].[ScrapFraction], [h].[ScrapOperator1], [h].[ScrapOperator2], [h].[StartCut], [h].[StartScrap], [h].[UserCodeEndCut], [h].[UserCodeEndScrap], [h].[UserCodeStartCut], [h].[UserCodeStartScrap], [h].[UserNameEndCut], [h].[UserNameEndScrap], [h].[UserNameStartCut], [h].[UserNameStartScrap], [h].[Width], [h].[WorkCenter], [h0].[Id], [h1].[Id], [h0].[ContainerId], [h0].[Description], [h0].[HasRFID], [h0].[IdHisOrderHeader], [h0].[Prg], [h0].[ProductionKey], [h0].[RfidCode], [h1].[IdHisOHContainer], [h1].[ItemId], [h1].[Lot], [h1].[Moved], [h1].[NameOrderFrom], [h1].[NumPartsExpected], [h1].[NumPartsPresent], [h1].[Prg], [h1].[PrgContainerFrom], [h1].[Supplier] FROM [M2FMetallurgy].[HisOrderHeader] AS [h] INNER JOIN [M2FMetallurgy].[HisOHContainer] AS [h0] ON [h].[Id] = [h0].[IdHisOrderHeader] INNER JOIN [M2FMetallurgy].[HisOHCDivision] AS [h1] ON [h0].[Id] = [h1].[IdHisOHContainer] ORDER BY [h].[EndScrap], [h0].[Id] DESC, [h].[Id], [h1].[Id] OFFSET @Skip ROWS FETCH NEXT @take ROWS ONLY

EF generates it for this linq query:


> **This required 2 minutes**:
> 
> ```
>         skip = 34064;
>         take = 16;
>         var orders = await (from oH in dbcontext.HisOrderHeader.Include(oo => oo.HisOrderLines).AsSplitQuery()
>                              join cC in dbcontext.HisOHContainer.AsSplitQuery() on oH.Id equals cC.IdHisOrderHeader
>                              join dD in dbcontext.HisOHCDivision.AsSplitQuery() on cC.Id equals dD.IdHisOhcontainer
>                             orderby oH.EndScrap, cC.Id descending
>                             select new JoinContainersObjDto { Order = oH, Sheet = null, Container = cC, Division = dD })
>                                                                                        .AsNoTracking().Skip(skip).Take(tak
> ```

**Comment by domenicocanavero** [comment] 2024-08-07 13:38
> I'll also note that doing pagination over a big dataset (OFFSET 34080 is big) is generally not a good idea performance-wise; I recommend reading [our docs on the subject](https://learn.microsoft.com/en-us/ef/core/querying/pagination). Switching to the more efficient keyset pagination would also make this issue go away for you.

I use skip-take to load a grid with large dataset. The grid component calls an event handler when need data, with 2 parameters: number of records to skip and number of records to take, not always it possibile to translate the number of records to skip to the record ID. In my opinion, in this case the solution with where-condition cannot replace the skip-take options.
