### ISSUE TITLE
Modified Entities reverting to "Added" state after Add

### ISSUE THREAD

**Issue by ScorchedHands** [dotnet/efcore#11767] opened 2018-04-21 21:15 UTC
I have not put together a repro yet, but I wanted to get this on here in case someone has seen this behavior or can explain it.

I have an entity (call it Ticket) that has a collection property of children (call them TicketSubscriber).  I have a third entity (call it ChangeItem), that has a navigation property of TicketSubscriber.

First step is query for TicketSubscriber, change a property value.

Second step is add that TicketSubscriber instance to a new ChangeItem instance, assign TicketSubscriber to it's TicketSubscriber property, then add the new ChangeItem to the context (via Add method). ChangeItem's state is Added, however TicketSubscriber state becomes Added also.

SaveChanges fails with exception because TicketSubscriber is an existing record Id but the context has it's state as Added.

I have been fighting with this for two days now and no matter how I add ChangeItem. I've tried calling Update on the TicketSubscriber before assigning it to and adding ChangeItem.  Regardless of what I do, the TicketSubscriber ALWAYS ends up in the Added state, even though it was queried from the context originally and even when I have confirmed it was being tracked as Modified before calling the Add for ChangeItem.

### Further technical details
EF Core version: 2.0.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.6

**Comment by ajcvickers** [comment] 2018-04-23 16:44
@ScorchedHands Nothing here rings a bell. I think we will need a repro to be able to investigate.

**Comment by divega** [comment] 2018-04-30 18:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 12:20 UTC
Labels: closed-could-not-reproduce
