### ISSUE TITLE
Query: receiving InvalidOperationException "coalesce used with type that cannot be null"

### ISSUE THREAD

**Issue by sam-piper** [dotnet/efcore#12644] opened 2018-07-12 02:30 UTC
I'm getting an exception when I try to coalesce the result of a sub-query that returns a `DateTime?` with a column that is typed as `DateTime` - I didn't get this exception before upgrading to EF 2.1 from EF 2.0.

I've tried workarounds such as returning `DateTime` for the `DateModified` projection in `sessionQuery`, but this means I have to use a ternary condition that tests for equality to `DateTime.MinValue` when projecting into `UserGridItem`, and the SQL generated is much worse because it has to execute the sub-query defined in `sessionQuery` twice.

### Steps to reproduce
Query code:

```
var sessionQuery =
    from s in context.Set<UserSession>()
    join u in context.Set<User>() on s.UserId equals u.Id
    orderby u.Id, s.DateModified descending
    select new { s.UserId, DateModified = (DateTime?)s.DateModified };

var itemQuery =
    from u in context.Set<User>()
    select new UserGridItem
    {
        Id = u.Id,
        Name = $"{u.FirstName} {u.LastName}",
        EmailAddress = u.EmailAddress,
        LastActivityDate = sessionQuery.Where(s => s.UserId == u.Id).Select(s => s.DateModified).FirstOrDefault() ?? u.DateCreated
    };

var results = itemQuery.ToArray(); // throws here
```

Workaround (works, but generates much heavier SQL plan):
```
var sessionQuery =
    from s in context.Set<UserSession>()
    join u in context.Set<User>() on s.UserId equals u.Id
    orderby u.Id, s.DateModified descending
    select new { s.UserId, s.DateModified };

var itemQuery =
    from u in context.Set<User>()
    let lastActivity = sessionQuery.Where(s => s.UserId == u.Id).Select(s => s.DateModified).FirstOrDefault()
    select new UserGridItem
    {
        Id = u.Id,
        Name = $"{u.FirstName} {u.LastName}",
        EmailAddress = u.EmailAddress,
        LastActivityDate = lastActivity == DateTime.MinValue ? u.DateCreated : lastActivity
    };

var results = itemQuery.ToArray(); // works correctly
```
For now I guess I will have to use the workaround, but I don't see why this projection can't work as intended, it's a very common pattern in our codebase and the current workaround we are having to use is very sub-optimal.

Will this be fixed in an upcoming release? Are there better workarounds that I could use while preserving the logical intent?

### Further technical details
EF Core version: 2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: IDE Visual Studio 2017 15.7.2

**Comment by maumar** [comment] 2018-07-12 20:16
@sam-piper can you share the code listing for the entities and contents of OnModelCreating? I tried to reverse engineer the model from the query you provided, but it works correctly, producing the following sql:

```sql
SELECT [u].[Id], [u].[FirstName], [u].[LastName], [u].[EmailAddress], COALESCE((
    SELECT TOP(1) [s].[DateModified]
    FROM [UserSessions] AS [s]
    INNER JOIN [Users] AS [u0] ON [s].[UserId] = [u0].[Id]
    WHERE [s].[UserId] = [u].[Id]
    ORDER BY [u0].[Id], [s].[DateModified] DESC
), [u].[DateCreated]) AS [LastActivityDate]
FROM [Users] AS [u]
```

You can also try the following workaround, which should produce a better query:

```cs
                var sessionQuery =
                    from s in ctx.UserSessions
                    join u in ctx.Users on s.UserId equals u.Id
                    orderby u.Id, s.DateModified descending
                    select new { s.UserId, DateModified = (DateTime?)s.DateModified };

                var itemQuery =
                    from u in ctx.Users
                    select new //UserGridItem
                    {
                        u.Id,
                        u.DateCreated,
                        Name = $"{u.FirstName} {u.LastName}",
                        u.EmailAddress,
                        LastActivityDate = sessionQuery.Where(s => s.UserId == u.Id).Select(s => s.DateModified).FirstOrDefault()
                    };

                var results = itemQuery.ToList().Select(u => new UserGridItem
                {
                    Id = u.Id,
                    Name = u.Name,
                    EmailAddress = u.EmailAddress,
                    LastActivityDate = u.LastActivityDate ?? u.DateCreated
                }).ToArray();
```

**Comment by sam-piper** [comment] 2018-07-18 02:21
I can't provide the exact code we're using, unfortunately, and it's entirely possible that this error is a result of our specific codebase, if you aren't able to replicate from basic code.

Here's the OnModelCreating code and relevant configuration classes, which I've stripped down to match the sample above, in case it provides more context.

```
// in DbContext
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    // add all configurations from this assembly
    var query =
        from t in GetType().Assembly.GetTypes()
        where t.GetInterfaces().Any(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEntityTypeConfiguration<>)) && !t.ContainsGenericParameters
        select t;

    foreach (var configurationType in query)
    {
        dynamic configuration = Activator.CreateInstance(configurationType);
        modelBuilder.ApplyConfiguration(configuration);
    }
}


public class EntityConfiguration<T> : IEntityTypeConfiguration<T> where T : Entity
{
    public virtual void Configure(EntityTypeBuilder<T> builder)
    {
        // Primary key
        builder.HasKey(e => e.Id);

        // Id column
        builder.Property(e => e.Id).ValueGeneratedNever();

        // Version column
        builder.Property(e => e.Version).IsRequired().IsRowVersion().UsePropertyAccessMode(PropertyAccessMode.Property);
    }
}

public class UserSessionConfiguration : EntityConfiguration<UserSession>
{
    public override void Configure(EntityTypeBuilder<UserSession> builder)
    {
        base.Configure(builder);

        builder.HasOne<User>().WithMany().HasForeignKey(s => s.UserId);
    }
}

public class UserConfiguration : EntityConfiguration<User>
{
    public override void Configure(EntityTypeBuilder<User> builder)
    {
        base.Configure(builder);
    }
}


public abstract class Entity
{
    private Guid _id;
    private byte[] _version;
    private DateTime _dateCreated = DateTime.UtcNow;
    private DateTime _dateModified = DateTime.UtcNow;

    protected Entity()
    {
        _id = CreateId();
    }

    public Guid Id
    {
        get => _id;
        set => _id = value;
    }

    public DateTime DateCreated
    {
        get => _dateCreated;
        set => SetProperty(ref _dateCreated, value, nameof(DateCreated), true);
    }

    public DateTime DateModified
    {
        get => _dateModified;
        set => _dateModified = value;
    }

    public byte[] Version
    {
        get => _version;
        set => _version = value;
    }  

    public static Guid CreateId()
    {
        var dateBytes = BitConverter.GetBytes(DateTime.Now.Ticks);
        var guidBytes = Guid.NewGuid().ToByteArray();

        // copy the last six bytes from the date to the last six bytes of the GUID
        Array.Copy(dateBytes, dateBytes.Length - 7, guidBytes, guidBytes.Length - 7, 6);
        return new Guid(guidBytes);
    }
}


public class UserSession : Entity
{
    private Guid _userId;

    public Guid UserId
    {
        get => _userId;
        set => _userId = value;
    }
}

public class User : Entity
{
    private string _firstName;
    private string _lastName;
    private string _emailAddress;

    public string FirstName
    {
        get => _firstName;
        set => _firstName = value;
    }

    public string LastName
    {
        get => _lastName;
        set => _lastName = value;
    }

    public string EmailAddress
    {
        get => _emailAddress;
        set => _emailAddress = value;
    }
}
```

If you still can't reproduce with this code (there's a lot stripped out), then I'll have to spend more time working to isolate the issue in a separate repo.

**Comment by maumar** [comment] 2018-08-22 02:02
@sam-piper I'm still unable to reproduce the issue. Tried on current bits as well as 2.1.2. 

Here is the full repro I used:

```cs
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var s1 = new UserSession { Id = Guid.NewGuid(), DateCreated = DateTime.Now, DateModified = DateTime.Now, Version = new byte[] { 0x00, 0x01 } };
                var s2 = new UserSession { Id = Guid.NewGuid(), DateCreated = DateTime.Now, DateModified = DateTime.Now, Version = new byte[] { 0x02, 0x03 } };

                var u = new User { DateCreated = DateTime.Now, DateModified = DateTime.Now, EmailAddress = "email", FirstName = "FN", LastName = "LN", Id = Guid.NewGuid(), Version = new byte[] { 0x00, 0x01 } };
                s1.UserId = u.Id;
                s2.UserId = u.Id;

                ctx.UserSessions.AddRange(s1, s2);
                ctx.Users.Add(u);
                ctx.SaveChanges();
            }

            using (var ctx = new MyContext())
            {
                var sessionQuery =
                    from s in ctx.UserSessions
                    join u in ctx.Users on s.UserId equals u.Id
                    orderby u.Id, s.DateModified descending
                    select new { s.UserId, DateModified = (DateTime?)s.DateModified };

                var itemQuery =
                    from u in ctx.Users
                    select new
                    {
                        u.Id,
                        u.DateCreated,
                        Name = $"{u.FirstName} {u.LastName}",
                        u.EmailAddress,
                        LastActivityDate = sessionQuery.Where(s => s.UserId == u.Id).Select(s => s.DateModified).FirstOrDefault()
                    };

                var results = itemQuery.ToList().Select(u => new UserGridItem
                {
                    Id = u.Id,
                    Name = u.Name,
                    EmailAddress = u.EmailAddress,
                    LastActivityDate = u.LastActivityDate ?? u.DateCreated
                }).ToArray();
            }
        }
    }

    public class UserGridItem
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public DateTime LastActivityDate { get; set; }
    }


    public class MyContext : DbContext
    {
        public DbSet<UserSession> UserSessions { get; set; }
        public DbSet<User> Users { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=Repro12644_21;Trusted_Connection=True;MultipleActiveResultSets=True");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // add all configurations from this assembly
            var query =
                from t in GetType().Assembly.GetTypes()
                where t.GetInterfaces().Any(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEntityTypeConfiguration<>)) && !t.ContainsGenericParameters
                select t;

            foreach (var configurationType in query)
            {
                dynamic configuration = Activator.CreateInstance(configurationType);
                modelBuilder.ApplyConfiguration(configuration);
            }
        }

        public class EntityConfiguration<T> : IEntityTypeConfiguration<T> where T : Entity
        {
            public virtual void Configure(EntityTypeBuilder<T> builder)
            {
                // Primary key
                builder.HasKey(e => e.Id);

                // Id column
                builder.Property(e => e.Id).ValueGeneratedNever();

                // Version column
                builder.Property(e => e.Version).IsRequired().IsRowVersion().UsePropertyAccessMode(PropertyAccessMode.Property);
            }
        }

        public class UserSessionConfiguration : EntityConfiguration<UserSession>
        {
            public override void Configure(EntityTypeBuilder<UserSession> builder)
            {
                base.Configure(builder);

                builder.HasOne<User>().WithMany().HasForeignKey(s => s.UserId);
            }
        }

        public class UserConfiguration : EntityConfiguration<User>
        {
            public override void Configure(EntityTypeBuilder<User> builder)
            {
                base.Configure(builder);
            }
        }
    }

    public abstract class Entity
    {
        private Guid _id;
        private byte[] _version;
        private DateTime _dateCreated = DateTime.UtcNow;
        private DateTime _dateModified = DateTime.UtcNow;

        protected Entity()
        {
            _id = CreateId();
        }

        public Guid Id
        {
            get => _id;
            set => _id = value;
        }

        public DateTime DateCreated
        {
            get => _dateCreated;
            set => _dateCreated = value;
        }

        public DateTime DateModified
        {
            get => _dateModified;
            set => _dateModified = value;
        }

        public byte[] Version
        {
            get => _version;
            set => _version = value;
        }

        public static Guid CreateId()
        {
            var dateBytes = BitConverter.GetBytes(DateTime.Now.Ticks);
            var guidBytes = Guid.NewGuid().ToByteArray();

            // copy the last six bytes from the date to the last six bytes of the GUID
            Array.Copy(dateBytes, dateBytes.Length - 7, guidBytes, guidBytes.Length - 7, 6);
            return new Guid(guidBytes);
        }
    }


    public class UserSession : Entity
    {
        private Guid _userId;

        public Guid UserId
        {
            get => _userId;
            set => _userId = value;
        }
    }

    public class User : Entity
    {
        private string _firstName;
        private string _lastName;
        private string _emailAddress;

        public string FirstName
        {
            get => _firstName;
            set => _firstName = value;
        }

        public string LastName
        {
            get => _lastName;
            set => _lastName = value;
        }

        public string EmailAddress
        {
            get => _emailAddress;
            set => _emailAddress = value;
        }
    }
```

sql that gets generated is as follows:

```sql
SELECT [u].[Id], [u].[DateCreated], [u].[FirstName], [u].[LastName], [u].[EmailAddress], (
    SELECT TOP(1) [s].[DateModified]
    FROM [UserSessions] AS [s]
    INNER JOIN [Users] AS [u0] ON [s].[UserId] = [u0].[Id]
    WHERE [s].[UserId] = [u].[Id]
    ORDER BY [u0].[Id], [s].[DateModified] DESC
) AS [LastActivityDate]
FROM [Users] AS [u]
```

**Comment by maumar** [comment] 2018-08-28 20:06
Closing, as we were not able to reproduce the issue. Feel free to re-open the issue adding full repro if the problem persists.

**Closed** 2022-10-16 13:18 UTC
Labels: closed-could-not-reproduce, customer-reported
