### ISSUE TITLE
Use generic attribute for EntityTypeConfiguration attribute

### ISSUE THREAD

**Issue by JohnyL** [dotnet/efcore#30606] opened 2023-04-01 17:08 UTC
In EF Core 6.0 new [EntityTypeConfiguration](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#entitytypeconfigurationattribute) attribute was introduced. It's handy very much. Now it's possible to move configuration logic into another file in the same project or even into another assembly. But there's one problem with it.
Say, we have simple entity class and configuration for this entity.
```csharp
[EntityTypeConfiguration(typeof(ConsumerConfiguration))]
public class Consumer
{
  public required int Id { get; set; }
  public required string Name { get; set; }
}

public class ConsumerConfiguration : IEntityTypeConfiguration<Consumer>
{
  public void Configure(EntityTypeBuilder<Consumer> builder)
  {
      // Implementation omitted
  }
}
```
The problem with `EntityTypeConfiguration` is that _at compile time_ there's no check for the type used as argument for it. It means I can write the following, which will compile fine but will generate exception _at run time_:
```csharp
[EntityTypeConfiguration(typeof(int))]
public class Consumer { }
```

Since C#11 it's possible to use [generic attributes](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#generic-attributes). For `EntityTypeConfiguration` it means that we could write the following:
```csharp
[EntityTypeConfiguration<ConsumerConfiguration>]
public record Consumer { }
```
The _advantage_ is that we now can have type constraint:
```csharp
[AttributeUsage(AttributeTargets.Class)]
public sealed class EntityTypeConfigurationAttribute<T>
    : Attribute where T : IEntityTypeConfiguration<T> { }
```
If class does not implement `IEntityTypeConfiguration<>`, then code won't compile the code and IDE will show red squiggles.

**Comment by roji** [comment] 2023-04-01 19:58
Duplicate of #30072

**Closed** 2023-04-05 17:10 UTC
Labels: closed-duplicate, customer-reported
