### ISSUE TITLE
Generic Repository & Unit Of Work For Multiple Database

### ISSUE THREAD

**Issue by akbarbd** [dotnet/efcore#26898] opened 2021-12-05 08:04 UTC
I have 6 Database in one  Dot net 6 project. I want to develop a generic repository with generic Unit of work.
Please guide me how to do this.

**Comment by ajcvickers** [comment] 2021-12-06 09:01
@akbarbd Can you be more specific? For example, why do you need a repository? Why do you need it to be generic? What specific problems are you trying to solve? How do the different databases interact? Why do they need to be in a single repository? What have you tried already?

**Comment by Zefek** [comment] 2021-12-07 15:49
@akbarbd Hello, repository is nice pattern but it is designed for domain-model business pattern. So if you want to use repository pattern your business layer needs to implement domain-model pattern. You mean you want to use generic repository. Problem of generic repository is that it has methods as Add, Remove, Save and Get. When I see to another data layer pattern (repository is one of them) I can see Table Gateway pattern. What is Table Gateway pattern? It is class which has methods as Add, Remove, Save and Get. Wait ... It is generic repository :) 

So there is not question how to implement generic repository and unit of work. But there should be question "What business pattern is implemented in your business layer?" It is very important because repository pattern with transaction script (business pattern) in business layer doesn't make sense. 

Unit of Work pattern is more hard to implement and with EF Core it doesn't make sense because DbContext in EF Core implements and provides Unit Of Work pattern. For simple projects doesn't make sence to implement own repository because DbContext in EF Core implements and provides Repository pattern too. For larger projects own repository pattern makes sense but not a generic because of interface segregation principle.

**Comment by ajcvickers** [comment] 2021-12-17 12:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:18 UTC
Labels: closed-no-further-action, customer-reported
