### ISSUE TITLE
Sqlite: Add option to support COLLATE NOCASE in queries

### ISSUE THREAD

**Issue by grennis** [dotnet/efcore#5963] opened 2016-07-03 16:47 UTC
When converting from ASP.NET 4.5 to .NET Core and from SQL Server to Sqlite, I ran into an issue that data is sorted a little differently, since Sqlite is case sensitive by default. It seems that Sqlite requires to pass COLLATE NOCASE in the query, but I don't see an option for that at the query level or in `SqliteDbContextOptionsBuilder`. 

Workaround is to sort on the client, but it would be nice to have support this.

**Comment by rowanmiller** [comment] 2016-07-06 21:14
The solution at the moment is to use a raw SQL query https://docs.efproject.net/en/latest/querying/raw-sql.html. We may look at more general support for case sensitivity in the future if we see demand for it.

**Comment by roji** [comment] 2020-09-12 22:39
Duplicate of #8813

**Closed** 2022-10-16 09:48 UTC
Labels: customer-reported
