### ISSUE TITLE
Why Ef Core MinLength constraint has no effect on database configuration?

### ISSUE THREAD

**Issue by mamaly12** [dotnet/efcore#28076] opened 2022-05-22 10:50 UTC
Hi,
I just have a question which is why ef core "MinLength" constraint has no effect on database configuration?

is there a particular reason for it? and what is the best approach to do that after making changes and creating a migration, my approach is to write a code  at the end lines of migration to set constraints:

```
ALTER TABLE my_table 
ADD CONSTRAINT MY_TABLE_PASSWORD_CK CHECK (DATALENGTH(password) >=4)
```
I would be more than happy if you could give me some advice.

thank you.

**Comment by SimonCropp** [comment] 2022-05-22 21:43
duplicate of https://github.com/dotnet/efcore/issues/22180

seems to be implemented as part of EFCore.CheckConstraints https://github.com/efcore/EFCore.CheckConstraints/issues/5

**Comment by roji** [comment] 2022-05-22 22:16
Yep, see @SimonCropp's answer above. For context, by default EF Core doesn't add various check constraints since that can have an impact on performance (additional checks), and not everyone wants them. The [EFCore.CheckConstraints](https://github.com/efcore/EFCore.CheckConstraints) plugin does support this, for those who want to opt into that.

**Comment by mamaly12** [comment] 2022-05-23 03:48
Thank you @SimonCropp and @roji. I will use EFCore.CheckConstraints plugin.

**Closed** 2022-10-16 20:34 UTC
Labels: closed-out-of-scope, customer-reported
