### ISSUE TITLE
Entity framework

### ISSUE THREAD

**Issue by BREN0-MORAIS** [dotnet/efcore#22224] opened 2020-08-25 19:14 UTC
hello I am facing this problem with Entity framework core: Add-Migration: Exception when calling "Start" with "1" argument (s): "The system cannot find the file specified"
In line: 1 character: 1
+ Add-Migration initial-Agili -context RepositoryAgiliContext
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~
    + CategoryInfo: NotSpecified: (:) [Add-Migration], MethodInvocationException
    + FullyQualifiedErrorId: Win32Exception, Add-Migration

**Comment by ajcvickers** [comment] 2020-08-28 19:44
@BREN0-MORAIS Can you post the output of `dotnet --info` to find how which .NET SDKs and runtimes are installed?

**Comment by bricelam** [comment] 2020-09-03 21:17
Possibly related to #14225

**Comment by ajcvickers** [comment] 2020-09-08 15:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:38 UTC
Labels: closed-could-not-reproduce, customer-reported
