### ISSUE TITLE
Update a null value on JSON column not working

### ISSUE THREAD

**Issue by NikLuy** [dotnet/efcore#33392] opened 2024-03-25 14:24 UTC
## File a bug

When i update the column with a value i works well 
But if there is an value in the column and i want to update with an null value the update is ignored on the json column everything else is updated. 

### Include your code

```c#
 protected override void OnModelCreating(ModelBuilder modelBuilder)
 {
     base.OnModelCreating(modelBuilder);

     modelBuilder.Entity<Charger>()
         .OwnsOne(c => c.Subjekt, s => s.ToJson())
         .OwnsOne(c => c.Zustell_Subjekt, s => s.ToJson());
  }
  
  public partial class Charger
 {
        [Key]
        public Guid Id { get; set; }
        public int? Id_Subjekt { get; set; }
        public int? Id_Zustelladresse { get; set; }
        public SubjektDto? Subjekt { get; set; }
        public SubjektDto? Zustell_Subjekt { get; set; }
 }
 
 public record SubjektDto
{
    public int? Id { get; set; }
    public string? Name { get; set; }
    public string? Vorname { get; set; }
    public string? Adresse { get; set; }
    public string? PLZ { get; set; }
    public string? Ort { get; set; }
    public string? Telefon { get; set; }
    public string? Email { get; set; }
    public int? SubjektTyp { get; set; }
    public string? Strasse { get; set; }
    public int? HausNr { get; set; }
    public string? HausNrZusatz { get; set; }
}
```

SELECT [Subjekt] FROM [dbo].[Chargers] 
returns NULL 

_db.Chargers.Update(charger);  // with Value  
await _db.SaveChangesAsync();

SELECT [Subjekt] FROM [dbo].[Chargers]
returns JSON 

_db.Chargers.Update(charger);  // with Null on Subjekt
await _db.SaveChangesAsync();

SELECT [Subjekt] FROM [dbo].[Chargers]
returns JSON

**Comment by roji** [comment] 2024-03-25 14:39
@ajcvickers not sure if you're the best person to investigate this or @maumar...

**Comment by NikLuy** [comment] 2024-03-26 05:04
I work on it. The simple example workes as expected and updates the null values. 
So i have build a more complex  example to reproduce the problem.

**Comment by NikLuy** [comment] 2024-03-26 06:37
I Uploaded a simple API which has 4 Endpoints 
https://github.com/NikLuy/JsonDemo

**Comment by ajcvickers** [comment] 2024-03-26 10:00
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/4669

**Closed** 2024-03-31 10:23 UTC
Labels: customer-reported
