### ISSUE TITLE
Migrations: Support removing IDENTITY from a column

### ISSUE THREAD

**Issue by MaximBalaganskiy** [dotnet/efcore#3993] opened 2015-12-06 22:47 UTC
When an SQL table is created with Id column it gets IDENTITY by default. Adding a `ValueGeneratedNever` method call later generates a migration which does not remove this clause.

Example [repo](https://github.com/MaximBalaganskiy/IdentityColumnBug). It has two migrations - Initial will generate a table with an Identity column. The second one was supposed to remove that Identity.

**Comment by bricelam** [comment] 2015-12-09 20:08
Notes for triage: If I remember right, we're mimicking EF6 behavior because removing `IDENTITY` requires a rebuild.

**Comment by divega** [comment] 2015-12-09 20:16
BTW, we said in the past that we wanted to give the user some kind of warning rather than silently ignoring changes that would cause table rebuilds.

**Comment by rowanmiller** [comment] 2015-12-15 18:51
Dependent upon https://github.com/aspnet/EntityFramework/issues/329

**Comment by divega** [comment] 2016-04-01 18:40
This seems to be a dupe since we have decided to warn for RTM (tracked in #4783) and we need table rebuilds to work for any further improvement (tracked in #329).

cc @rowanmiller

**Comment by bricelam** [comment] 2016-10-06 20:56
Closing as a dupe of #5345. We throw now.

**Closed** 2022-10-16 09:19 UTC
