### ISSUE TITLE
Include and Take to T-SQL results in unconstrained query.

### ISSUE THREAD

**Issue by MicahZoltu** [dotnet/efcore#6037] opened 2016-07-10 02:19 UTC
### Steps to reproduce

``` c#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace TestEF
{
    public class Product
    {
        [Key]
        public Int32 Id { get; set; }
        public String Name { get; set; }

        public List<ProductTag> ProductTags { get; set; }
    }

    public class ProductTag
    {
        [Key]
        public Int32 Id { get; set; }

        [Required]
        public Int32 TagId { get; set; }
        public Tag Tag { get; set; }
        [Required]
        public Int32 ProductId { get; set; }
        public Product Product { get; set; }
    }
    public class Tag
    {
        [Key]
        public Int32 Id { get; set; }
        [Required]
        public String Name { get; set; }

        public List<ProductTag> Products { get; set; } = new List<ProductTag>();
    }

    public class MyContext : DbContext
    {
        public DbSet<Product> Products { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<ProductTag> ProductTags { get; set; }

        public MyContext() { }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=tcp:zoltubags.database.windows.net,1433;Database=test;User ID=TestLogin@zoltubags;Password=SecretPassword!;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;");
        }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                var serviceProvider = db.GetInfrastructure<IServiceProvider>();
                var loggerFactory = serviceProvider.GetService<ILoggerFactory>();
                loggerFactory.AddConsole(LogLevel.Information);
            }

            using (var db = new MyContext())
            {
                var fruit = new Tag { Name = "fruit" };
                var red = new Tag { Name = "red" };
                var yellow = new Tag { Name = "yellow" };
                db.Tags.AddRange(fruit, red, yellow);
                var apple = new Product { Name = "apple" };
                var banana = new Product { Name = "banana" };
                db.Products.AddRange(apple, banana);
                db.ProductTags.AddRange(
                    new ProductTag { Product = apple, Tag = fruit },
                    new ProductTag { Product = apple, Tag = red },
                    new ProductTag { Product = banana, Tag = fruit },
                    new ProductTag { Product = banana, Tag = yellow }
                );
                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                Console.WriteLine("Starting");
                var results = db.Products
                    .Include(product => product.ProductTags).ThenInclude(productTag => productTag.Tag)
                    .Take(1)
                    .ToList();
                Console.WriteLine(results);
            }
        }
    }
}
```
### The issue

The second query returns all products when it should only return one product.

If you remove the `Include`, the query correctly returns a single row.  With the include however, it executes a query that should return 2 rows (one for each tag on the product) but instead it returns 4 rows (two products with two tags each).  I'm not terribly familiar with T-SQL, but it appears the where clause (`WHERE EXISTS (...)`) isn't doing anything.  If you remove it, the same result set is returned.
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 10
Visual Studio version: VS2015

Other details about my project setup: Azure SQL Server

**Comment by smitpatel** [comment] 2016-07-11 20:09
Similar to #5901  but with `Take` method.

**Comment by rowanmiller** [comment] 2016-07-19 21:15
We think this is probably fixed in our working code base. Would you be able to try our nightly builds and see if the issue is resolved for you. Nightly builds are available from https://www.myget.org/Gallery/aspnetcidev.

**Comment by rowanmiller** [comment] 2016-07-25 20:31
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 09:50 UTC
