### ISSUE TITLE
Navigation Collection Cleared after first SaveChanges

### ISSUE THREAD

**Issue by fromberg100** [dotnet/efcore#16483] opened 2019-07-06 19:00 UTC
Hi,

I am having an issue when updating a collection of an existing entity.  Everything is OK when I call _dbContext.SaveChanges() the first time.  

Before calling SaveChanges(), all items in collection are marked as EntityState.Added which is Ok, and when I call SaveChanges() the items are inserted into the database.

But after that, the navigation collection is cleared and its items are marked as EntityState.Deleted, and if I call SaveChanges() again they are deleted from the database.

See structure below (simplified):
```C#
public class Parent
{

    public Parent()
    {
        this.Children = new List<ParentChild>();
    }

    public int Id { get; set; }

    public string Name { get; set; }

    public virtual IList<ParentChild> Children { get; set; }
}

public class Child
{
    public int Id { get; set; }

    public string Name { get; set; }
}

public class ParentChild
{
    public int ParentId { get; set; }

    public int ChildId { get; set; }

    public int SortOrder { get; set; }

    public virtual Parent Parent { get; set; }

    public virtual Child Child { get; set; }
}

```

The update method is as follows:
```C#
int parentId = 100;

Parent entity = _dbContext.Parents
    .Include(x => x.Children)
    .Where(x => x.Id == parentId)
    .FirstOrDefault()
    ;


entity.Children = new List<ParentChild>
{
    new ParentChild
    {
        ParentId = parentId,
        ChildId = 20,
        SortOrder = 1
    },
    new ParentChild
    {
        ParentId = parentId,
        ChildId = 25,
        SortOrder = 2
    },
    new ParentChild
    {
        ParentId = parentId,
        ChildId = 30,
        SortOrder = 3
    }
};

_dbContext.SaveChanges();

//some extra updates here

_dbContext.SaveChanges();
```
Am I doing something wrong?

**Comment by ajcvickers** [comment] 2019-07-08 16:06
@fromberg100 The update method does this:
* Loads all existing children
* Removes all existing children from navigation (because the collection is replaced) and replaces them with three new children
* SaveChanges will now delete all the existing children and insert all new children

If that's not your intention, then that might be the issue. Otherwise, please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by fromberg100** [comment] 2019-07-09 06:39
I was not clearing the collection, however, I tried and also got the same results.

I missed to include that I override Equals:

```
public class ParentChild
{
    public int ParentId { get; set; }

    public int ChildId { get; set; }

    public int SortOrder { get; set; }

    public virtual Parent Parent { get; set; }

    public virtual Child Child { get; set; }

    public override bool Equals(object obj)
    {
        if (obj == null)
        {
            return false;
        }

        var other = (ParentChild)obj;

        if (!Object.Equals(this.ParentId, other.ParentId))
            return false;
        if (!Object.Equals(this.ChildId, other.ChildId))
            return false;

        return true;
    }
}
```
When I do not override Equals, then it works ok.  I believe this is related to issue #16161

**Comment by ajcvickers** [comment] 2019-07-09 18:16
@fromberg100 Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by fromberg100** [comment] 2019-07-10 01:27
please find solution enclosed.  Please read carefully the comments I wrote specifically on top of method SetSameChildren on file Program.cs (line no. 52)

If there is anything unclear with, please let me know. 

[UpdateCollection.zip](https://github.com/aspnet/EntityFrameworkCore/files/3375359/UpdateCollection.zip)

**Comment by ajcvickers** [comment] 2019-07-15 21:19
@fromberg100 Confirmed this is a duplicate of #16161. However, note that defining `Equals` and `GetHashCode` in this way goes against best practice for .NET code since it depends on mutable state which makes the hashing unstable. See https://github.com/aspnet/EntityFrameworkCore/issues/15687#issuecomment-492280606

**Closed** 2022-10-16 14:29 UTC
Labels: closed-duplicate, customer-reported
