### ISSUE TITLE
EfCore Tools Compiles Unnecessary Projects

### ISSUE THREAD

**Issue by Mike-E-angelo** [dotnet/efcore#25524] opened 2021-08-15 16:09 UTC
## File a bug

When running EfCore Tool operations in Package Manager Console such as `Add-Migration` and `Remove-Migration`, a request appears to be made to MSBuild to build all projects that are dependent upon the target project.  This is unnecessary (and arguably wasteful) as the next build done within the IDE will do the same thing.

The result of which is two disparate builds with no caching/state involved.  This is doubled when running a script that does both `Remove-Migration` and `Add-Migration`

Expected:  When running EfCore Tool Package Manager Console commands, only the target project (and startup project if these differ) should be built.

### Include your code

```PowerShell
Remove-Migration -Project Starbeam.Model.Schema -StartupProject Starbeam.Model.Schema
Add-Migration Initial -Project Starbeam.Model.Schema -StartupProject Starbeam.Model.Schema
```
### Include stack traces

NA

### Include verbose output

Some sample output.  17 projects are built when only one (`Starbeam.Model.Schema`) is expected to be built.  The others are application projects, which sometimes take considerable time to build, especially Razor-based/compiled ones.

```
Build started...
1>------ Build started: Project: Starbeam.Model.Schema, Configuration: Debug Any CPU ------
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>Starbeam.Model.Schema -> ...\Starbeam.Model.Schema\bin\Debug\net6.0\Starbeam.Model.Schema.dll
2>------ Build started: Project: Starbeam.Testing.Implementations, Configuration: Debug Any CPU ------
3>------ Build started: Project: Starbeam.Applications.Gateway.Initialization, Configuration: Debug Any CPU ------
4>------ Build started: Project: Starbeam.Applications.Authentications, Configuration: Debug Any CPU ------
5>------ Build started: Project: content.starbeam.one, Configuration: Debug Any CPU ------
6>------ Build started: Project: events.starbeam.one, Configuration: Debug Any CPU ------
7>------ Build started: Project: Starbeam.Applications.Sales, Configuration: Debug Any CPU ------
8>------ Build started: Project: commerce.starbeam.one, Configuration: Debug Any CPU ------
9>------ Build started: Project: Starbeam.Applications.Resales, Configuration: Debug Any CPU ------
10>------ Build started: Project: Starbeam.Applications.Notifications, Configuration: Debug Any CPU ------
11>------ Build started: Project: Starbeam.Applications.Withdrawals, Configuration: Debug Any CPU ------
12>------ Build started: Project: Starbeam.Applications.Issuances, Configuration: Debug Any CPU ------
13>------ Build started: Project: Starbeam.Applications.Deposits, Configuration: Debug Any CPU ------
12>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
4>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
3>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
13>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
11>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
10>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
7>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
2>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
9>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
6>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
5>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
8>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
3>Starbeam.Applications.Gateway.Initialization -> ...\Starbeam.Applications.Gateway.Initialization\bin\Debug\net6.0\Starbeam.Applications.Gateway.Initialization.dll
14>------ Build started: Project: starbeam.one, Configuration: Debug Any CPU ------
2>Starbeam.Testing.Implementations -> ...\Starbeam.Testing.Implementations\bin\Debug\net6.0\Starbeam.Testing.Implementations.dll
15>------ Build started: Project: Starbeam.Presentation.Testing, Configuration: Debug Any CPU ------
16>------ Build started: Project: Starbeam.Applications.Gateway.Testing, Configuration: Debug Any CPU ------
17>------ Build started: Project: Starbeam.Testing, Configuration: Debug Any CPU ------
15>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
17>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
10>Starbeam.Applications.Notifications -> ...\Starbeam.Applications.Notifications\bin\Debug\net6.0\Starbeam.Applications.Notifications.dll
12>Starbeam.Applications.Issuances -> ...\Starbeam.Applications.Issuances\bin\Debug\net6.0\Starbeam.Applications.Issuances.dll
4>Starbeam.Applications.Authentications -> ...\Starbeam.Applications.Authentications\bin\Debug\net6.0\Starbeam.Applications.Authentications.dll
7>Starbeam.Applications.Sales -> ...\Starbeam.Applications.Sales\bin\Debug\net6.0\Starbeam.Applications.Sales.dll
9>Starbeam.Applications.Resales -> ...\Starbeam.Applications.Resales\bin\Debug\net6.0\Starbeam.Applications.Resales.dll
11>Starbeam.Applications.Withdrawals -> ...\Starbeam.Applications.Withdrawals\bin\Debug\net6.0\Starbeam.Applications.Withdrawals.dll
13>Starbeam.Applications.Deposits -> ...\Starbeam.Applications.Deposits\bin\Debug\net6.0\Starbeam.Applications.Deposits.dll
14>starbeam.one -> ...\starbeam.one\bin\Debug\net6.0\Starbeam.Applications.Gateway.dll
8>commerce.starbeam.one -> ...\commerce.starbeam.one\bin\Debug\net6.0\Starbeam.Applications.Commerce.dll
5>content.starbeam.one -> ...\content.starbeam.one\bin\Debug\net6.0\Starbeam.Applications.Content.dll
6>events.starbeam.one -> ...\events.starbeam.one\bin\Debug\net6.0\Starbeam.Applications.Events.dll
15>Starbeam.Presentation.Testing -> ...\Starbeam.Presentation.Testing\bin\Debug\net6.0\Starbeam.Presentation.Testing.dll
17>Starbeam.Testing -> ...\Starbeam.Testing\bin\Debug\net6.0\Starbeam.Testing.dll
16>Starbeam.Applications.Gateway.Testing -> ...\Starbeam.Applications.Gateway.Testing\bin\Debug\net6.0\Starbeam.Applications.Gateway.Testing.dll
========== Build: 17 succeeded, 0 failed, 111 up-to-date, 0 skipped ==========

Build time 00:00:16.407
Build ended at 8/15/2021 11:49:14 AM


```

### Include provider and version information

EF Core version: EfCore Tools '5.0.9'
Database provider: NA
Target framework: (e.g. .NET 5.0) `net6.0`
Operating system: Windows 10
IDE: Visual Studio 2022 Preview 3.0

**Comment by ajcvickers** [comment] 2021-08-17 10:53
Duplicate of #9716?

//cc @bricelam

**Comment by Mike-E-angelo** [comment] 2021-08-17 12:10
I did a search for this before posting, I swear @ajcvickers! 😅

That works for me.  I see that I can use CLI and can use that in the meantime as a workaround.

Thank you for all the great work you and your team are doing out there. 👍

**Closed** 2022-10-16 19:43 UTC
Labels: customer-reported
