### ISSUE TITLE
What does Add-Migration command use to compare schemas?

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#21755] opened 2020-07-23 16:08 UTC
I'm renaming several tables and columns. Since I don't want to lose the existing data, I created a migration from scratch.

    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.RenameTable(name: "Providers", schema: "dbo", newName: "Vendors", newSchema: "dbo");
        migrationBuilder.RenameTable(name: "ProviderContacts", schema: "dbo", newName: "VendorContacts", newSchema: "dbo");
        migrationBuilder.RenameColumn(name: "ProviderId", table: "AspNetUsers", newName: "VendorId", schema: "dbo");
        migrationBuilder.RenameColumn(name: "ProviderId", table: "VendorContacts", newName: "VendorId", schema: "dbo");
        migrationBuilder.RenameColumn(name: "ProviderId", table: "Locations", newName: "VendorId", schema: "dbo");
    }

I then ran `Update-Database`. But this still leaves a bunch of indexes and foreign keys that should also be renamed. So I used the `Add-Migration` command to bring any remaining changes up to date.

But I notice the new migration seems to be dropping and recreating tables and columns that my custom migration already renamed.

    migrationBuilder.DropTable(
        name: "ProviderContacts");

    migrationBuilder.DropTable(
        name: "Providers");

    migrationBuilder.DropIndex(
        name: "IX_Locations_ProviderId",
        table: "Locations");

    migrationBuilder.DropIndex(
        name: "IX_AspNetUsers_ProviderId",
        table: "AspNetUsers");

    migrationBuilder.DropColumn(
        name: "ProviderId",
        table: "Locations");

    migrationBuilder.DropColumn(
        name: "ProviderId",
        table: "AspNetUsers");

What is the `Add-Migration` command comparing and why doesn't it recognize I've already renamed these tables and columns? Is it looking at the database or something else?

How can I get it to recognize the changes in my custom migration?

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.4

**Comment by ajcvickers** [comment] 2020-07-23 22:11
Duplicate of #21754

**Closed** 2022-10-16 18:34 UTC
Labels: closed-duplicate, customer-reported
