### ISSUE TITLE
How to add a new property on your model without 'System.InvalidOperationException: 'Nullable object must have a value.''

### ISSUE THREAD

**Issue by mip1983** [dotnet/efcore#34644] opened 2024-09-10 11:56 UTC
I'm using entity framework core on CosmosDb (8.0.8). I've added a new int property to one of my models (an owned object) and now EF falls over with this error:

```
System.InvalidOperationException: 'Nullable object must have a value.'

This exception was originally thrown at this call stack:
    [External Code]
    ecoDriverAnalytics.Services.ProjectService.SearchEnquiriesAsync(ecoDriverCore.Shared.Models.Project.EnquiryFilter) in ProjectService.cs
```

I know this property will be missing on existing objects in CosmosDb.

Two questions

1) This exception is really non-descript. I'm lucky I happen to know what's changed recently, but there's no mention of what property it's having a problem with. Can this not be modified with some more information?

2) What's the best way to update data to align with model changes? This is kind of like a migration, but does CosmosDb have an equivalent?

### Include provider and version information

EF Core version: 8.0.8
Database provider: (e.g. Microsoft.EntityFrameworkCore.Cosmos)
Target framework: 8.0.401 (8.0.8)

**Comment by roji** [comment] 2024-09-12 11:52
Duplicate of #11099

**Comment by roji** [comment] 2024-09-12 11:52
@mip1983 there's unfortunately no great answer to this at the moment... See #11099 for some discussion and workarounds. I hope we'll be able to make this better.

**Closed** 2024-09-14 00:16 UTC
Labels: closed-duplicate, customer-reported
