### ISSUE TITLE
DbContext.Database.Migrate() doesn't appear to do anything

### ISSUE THREAD

**Issue by joshmouch** [dotnet/efcore#22306] opened 2020-08-28 21:21 UTC
Somewhat recently, when our migration code runs (a simple `DbContext.Database.Migrate()`), it doesn't appear to do anything.  I attached the SQL profiler, and I see a query get executed to pull the values from the `__EFMigrationHistory` table, but then nothing after that.  At this point, that table is a few versions behind, so I know there are migrations that need to be performed.

I'd like to provide further information on what I think is a bug.  Are there any logging or diagnostics I can enable to figure out why EF doesn't think it needs to migrate?

**Comment by smitpatel** [comment] 2020-08-31 17:18
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by joshmouch** [comment] 2020-08-31 18:45
@smitpatel ,  Thanks for the response!  Do you have any additional logging I can enable to see what's going on with the migrations or why it decided the migrations didn't need to be applied? Then I can create a runnable project to reproduce the problem.

**Comment by bricelam** [comment] 2020-09-03 21:22
* [Logging - EF Core](https://docs.microsoft.com/ef/core/miscellaneous/logging)
* [Logging in .NET Core](https://docs.microsoft.com/aspnet/core/fundamentals/logging)

**Comment by ajcvickers** [comment] 2020-09-11 15:33
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:38 UTC
Labels: closed-could-not-reproduce, customer-reported
