### ISSUE TITLE
Enable ForceIndex extension

### ISSUE THREAD

**Issue by neoaisac** [dotnet/efcore#16034] opened 2019-06-11 15:41 UTC
As a developer using MySQL to make a query perform better I might want to use the `FORCE INDEX` syntax to ensure MySQL won't use a table scan to query my table.

_Example:_
```
var myQuery = dbContext.Set<User>()
   .ForceIndex("IX_User_CreatedDate")
   .Where(user => user.CreatedDate > DateTime.UtcNow());
```

If I had a way to extend the query providers underneath, I could write my own `IQueryable` extension method that would enable me to do this, but as it stands, I can't.

Is there any guidance as how could I achieve this?

**Comment by smitpatel** [comment] 2019-06-11 15:43
@neoaisac - Can you write what would be the SQL generated for such query?

**Comment by neoaisac** [comment] 2019-06-11 15:58
It would be similar to...
```
SELECT *
FROM User FORCE INDEX(IX_User_CreatedDate)
WHERE CreatedDate > '2019-06-11'
```

**Comment by neoaisac** [comment] 2019-06-11 16:00
I'm trying to get this done through interception but I can't figure out how to get the Expressions connected with the interception for this, and almost everything I look into is marked as "Internal API" so it seems a bit unsafe to get it done this way.

**Comment by smitpatel** [comment] 2019-06-11 16:13
Duplicate of #6717

**Closed** 2022-10-16 14:24 UTC
Labels: customer-reported
