### ISSUE TITLE
UWP Migrations:Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions'

### ISSUE THREAD

**Issue by utpal-patel** [dotnet/efcore#6343] opened 2016-08-17 05:52 UTC

**Comment by utpal-patel** [comment] 2016-08-17 05:55
Exception Message:
Add-Migration MyFirstMigration
System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.StartupInvoker.ConfigureHostServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.StartupInvoker.ConfigureServices()
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations..ctor(ILoggerProvider loggerProvider, Assembly assembly, Assembly startupAssembly, String environment, String contentRootPath)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations..ctor(ILoggerProvider loggerProvider, Assembly assembly, AssemblyLoader startupAssemblyLoader, Assembly startupAssembly, String environment, String projectDir, String contentRootPath, String rootNamespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<>c__DisplayClass5_0.<.ctor>b__5()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

EF Core Version: 
Microsoft.EntityFrameworkCore.Sqlite: 1.0.0
Microsoft.EntityFrameworkCore.Tools: 1.0.0-preview2-final

Operating system:
Windows 10 x64

Visual Studio version: 
VS 2015 Update 3

Followed Below Link:
https://docs.efproject.net/en/latest/platforms/uwp/getting-started.html

**Comment by natemcmaster** [comment] 2016-08-18 21:31
This was a breaking change from RC2 to RTM. See https://github.com/aspnet/Announcements/issues/187. This error is generally caused by mixing pre-release preview1/1.0.0-rc2 and preview2/1.0.0 (RTM) packages. Can you share the full project.json file?

**Comment by divega** [comment] 2016-08-18 22:52
**Triage:** going ahead and closing as the symptoms are really typical of package mismatches, but feel free to respond with the information @natemcmaster asked for in case we can help.

**Comment by utpal-patel** [comment] 2016-08-19 03:49
@natemcmaster Find below **Package.Json**

{
  "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "Microsoft.ApplicationInsights": "2.1.0",
    "Microsoft.ApplicationInsights.PersistenceChannel": "1.2.3",
    "Microsoft.ApplicationInsights.WindowsApps": "1.1.1",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}

**Comment by natemcmaster** [comment] 2016-08-19 05:34
Remove EntityFramework.Commands. It's the package bringing in the old version of DependencyInjection. Commands was deprecated and replaced by the .Tools package.

**Comment by utpal-patel** [comment] 2016-08-19 06:17
@natemcmaster  if i do so and run migration command i received an error.

PM> Add-Migration MyFirstMigration
Build failed.

**Comment by natemcmaster** [comment] 2016-08-23 21:42
@utpal-patel Is your issue resolve when you fix your build errors? If removing EntityFramework.Commands causes build errors, chances are good you need to update APIs. RC1 to RC2 was a major change and will break most APIs. See  https://docs.efproject.net/en/latest/miscellaneous/rc1-rc2-upgrade.html

**Closed** 2022-10-16 09:54 UTC
Labels: closed-could-not-reproduce
