### ISSUE TITLE
LIKE operator generated for SQLite becomes case sensitive in .Net Native apps

### ISSUE THREAD

**Issue by michaldepta** [dotnet/efcore#6397] opened 2016-08-24 06:45 UTC
### Steps to reproduce

Demo project: **https://github.com/MichalDepta/efcore-sqlite-collation**
### The issue

The EF Core query results differ depending on whether .Net Native compilation is enabled in UWP app.
According to [SQLite documentation](https://sqlite.org/lang_expr.html) the LIKE operator is case insensitive. However, when an app (UWP) is built with .Net Native Toolchain, it seems to be case sensitive.

The same query returns expected results when native compilation is disabled.
### Further technical details

EF Core version: 1.0.0
Operating system: WIndows 10 (10586.164)
Universal Windows Platform: 5.2.2
Visual Studio version: VS 2015 update 3

**Comment by bricelam** [comment] 2016-08-24 16:40
Sounds a lot like #6381

**Comment by MichalDepta** [comment] 2016-08-24 20:07
Yes, I guess the reason is the same. I suppose it's problematic to translate expressions to SQL in .Net Native.

**Comment by divega** [comment] 2016-08-24 20:29
> I suppose it's problematic to translate expressions to SQL in .Net Native.

Translating LINQ expressions should be the same but for some reason we need to investigate with the .NET Native folks it is not behaving the same. Thanks for providing a repro.

**Comment by divega** [comment] 2016-08-25 23:29
I will went ahead and close this issue as a dupe of #6381 but I added some information there so that we don't forget to test this case.

**Comment by darkurse** [comment] 2017-03-22 15:18
I can see that both #6381 and this issue are closed but this is still an issue with EF Core version 1.1.1.

I still cannot apply a case insensitive filter to my SQLite queries. Looking at the source, `instr()` is still used as the expression translator for `.Contains()`. Why not use the SQLite `like()` function to do the job (if mapping the `LIKE` operator is an issue) ?

This is clearly not an edge case so I don't understand why this is still an issue. Am I missing something obvious ?

----
EF Core version: 1.1.1
Operating system: Windows 10 (10.0.14393)
full framework: net461
Visual Studio version: VS 2017 enterprise

**Comment by ajcvickers** [comment] 2017-03-23 23:29
@darkurse Can you file a new issue for this. It could be a different root cause with the same observed behavior. Please make sure include everything needed to reproduce what you are seeing.

**Closed** 2022-10-16 09:55 UTC
