### ISSUE TITLE
Fluent API Navigation Name incorrect

### ISSUE THREAD

**Issue by dpwzone** [dotnet/efcore#31838] opened 2023-09-22 22:10 UTC
Creating a new issue, because the people (@roji)  responding to these are closing tickets with issues that still remain. Does nobody any good.

Navigation is being created as "Item", and not using the navigation name supplied in the "HasOne" method.

If you're just going to say give us your code, just skip to the next ticket, and let this issue stay open for someone who actually knows how to deal with this.

**Comment by roji** [comment] 2023-09-22 22:11
@dpwzone I've requested several times that you stop opening the same issue again and again. If you continue doing so we'll have to look into getting you banned, as you're spamming this repo.

**Comment by roji** [comment] 2023-09-22 22:12
Duplicate of #31836

**Closed by roji** 2023-09-22 22:11 UTC
Labels: customer-reported

**Comment by dpwzone** [comment] 2023-09-22 22:15
Why don't you answer the question then?
