### ISSUE TITLE
Entity Framework Pluralize

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#21983] opened 2020-08-06 18:23 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1137674/entity-framework-pluralize.html)._

---
[regression]
I upgraded to 16.0.5 and for now when i scaffold Dbset are in singular unlike in the past. I want them to be in plural

---
#### Feedback Bot on 8/6/2020, 02:32 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2020-08-10 18:51
Please provide more details including which version of EF6 or EF Core is being used, which database provider, and whether or not you have made any customizations to the design-time services.

**Comment by ajcvickers** [comment] 2020-08-17 15:26
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:36 UTC
Labels: closed-could-not-reproduce, customer-reported
