### ISSUE TITLE
How do I filter by several columns simultaneously without creating a temporary table?

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#32661] opened 2023-12-22 14:23 UTC
I have a join table
```
public sealed record DemographicsInPeriod(int DemographicsId, int PeriodId)
{
    public int Id { get; private set; }
}
```
And I have a collection of pairs `(periodId, demographicsId)`.

Is there a way to filter the result set by both values?

**Comment by roji** [comment] 2023-12-22 18:44
That's not currently possible - it may end up being implemented as part of #31237 (though that's more about CLR complex types, and not necessarily about collections of value tuples).

In the meantime you can use dynamic expression generation to integrate your tuple collection as a series if ORs (though that would prevent query caching for variable numbers of collections), or use raw SQL to do something e.g. with OPENJSON.

**Comment by voroninp** [comment] 2023-12-22 20:16
What do you think? Worth creating separate feature request?

**Comment by roji** [comment] 2023-12-23 10:08
Duplicate of #11799

**Comment by roji** [comment] 2023-12-23 10:10
@voroninp I think I found the specific issue - #11799. I've made a note on #31237 to take that into account.

I'll go ahead and close this as a dup of that, but let me know if you think anything is missing etc.

**Closed by roji** 2023-12-23 10:10 UTC
Labels: customer-reported
