### ISSUE TITLE
Using Include causes the "Index was out of range" exception when trying to sort

### ISSUE THREAD

**Issue by alexandis** [dotnet/efcore#25306] opened 2021-07-21 12:05 UTC
I did not have the bugs like this in EfCore 3.x.
Now I have it in EfCore 5. I don't see what could be wrong. Here is the entity binding (Oracle is used as a DB):

            builder.Entity<FineDigitGroup>()
                .HasMany(x => x.FineDigitGroupLanguages)
                .WithOne()
                .HasPrincipalKey(x => new { x.TenantId, x.OrdinanceId, x.ClassId, x.GroupId })
                .HasForeignKey(x => new { x.TenantId, x.OrdinanceId, x.ClassId, x.GroupId });
            builder.Entity<FineDigitGroup>(b =>
            {
                b.ToTable("MD_CA_FND_GROUP", CoreDbProperties.DbSchema);
                b.ConfigureByConvention();
                b.HasKey(x => new { x.TenantId, x.OrdinanceId, x.ClassId, x.GroupId });
                b.Property(x => x.TenantId).HasColumnName("C_TENANT").IsRequired();
                b.Property(x => x.OrdinanceId).HasColumnName("C_ORDINANCE").IsRequired();
                b.Property(x => x.ClassId).HasColumnName("C_CLASS").IsRequired();
                b.Property(x => x.GroupId).HasColumnName("C_GROUP").IsRequired();
                b.Ignore(x => x.ShortDescription);
                b.MapLogProperties(); // Not relevant - binds some other fields
            });

            builder.Entity<FineDigitGroupLanguage>(b =>
            {
                b.ToTable("MD_CA_FND_GROUP_LAN", CoreDbProperties.DbSchema);
                b.ConfigureByConvention();
                b.HasKey(x => new { x.TenantId, x.OrdinanceId, x.ClassId, x.GroupId, x.LanguageCode });
                b.Property(x => x.TenantId).HasColumnName("C_TENANT").IsRequired();
                b.Property(x => x.OrdinanceId).HasColumnName("C_ORDINANCE").IsRequired();
                b.Property(x => x.ClassId).HasColumnName("C_CLASS").IsRequired();
                b.Property(x => x.GroupId).HasColumnName("C_GROUP").IsRequired();
                b.Property(x => x.LanguageCode)
                    .HasConversion(new ValueConverter<string, string>(v => v.Trim(), v => v.Trim()))
                    .HasColumnName("C_LANGUAGE").IsRequired().HasMaxLength(FineDigitGroupLanguageDbConsts.LanguageCodeMaxLength);
                b.Property(x => x.ShortDescription)
                    .HasConversion(new ValueConverter<string, string>(v => v.Trim(), v => v.Trim()))
                    .HasColumnName("S_DESC_INT").HasMaxLength(FineDigitGroupLanguageDbConsts.ShortDescriptionMaxLength);
                b.Property(x => x.FullDescription)
                    .HasConversion(new ValueConverter<string, string>(v => v.Trim(), v => v.Trim()))
                    .HasColumnName("S_DESC").HasMaxLength(FineDigitGroupLanguageDbConsts.FullDescriptionMaxLength);
                b.MapLogProperties(); // Not relevant - binds some other fields
            });

And the simplified method to get data list:

        public async Task<List<FineDigitGroup>> GetListAsync
        (
            int tenantId,
            int? ordinanceId = null,
            int? classId = null,
            int? groupId = null,
            string shortDescription = null,
            string sorting = null,
            int maxResultCount = int.MaxValue,
            int skipCount = 0,
            string userContentLangRestriction = null,
            CancellationToken cancellationToken = default
        )
        {
            var query = (await GetDbSetAsync()).Include(x => x.FineDigitGroupLanguages);

            var sortingExpression = string.IsNullOrWhiteSpace(sorting) ? FineDigitGroupDbConsts.DefaultSorting : sorting;

            return await query.OrderBy(sortingExpression).PageBy(skipCount, maxResultCount).ToListAsync(cancellationToken);
        }

When I try to sort by "classId" in my grid - I am getting the exception:

> [15:01:13 ERR] Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
>    at System.Collections.Generic.List`1.get_Item(Int32 index)
>    at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyCollectionJoin(Int32 collectionIndex, Int32 collectionId, Expression innerShaper, INavigationBase navigation, Type elementType, Boolean splitQuery)
>    at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
>    at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
>    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>    at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
>    at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
>    at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
>    at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
>    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>    at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
>    at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
>    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>    at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
>    at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
>    at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
>    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
>    at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
>    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
>    at AbxEps.Fines.FineDigitGroups.EfCoreFineDigitGroupRepository.GetListAsync(Int32 tenantId, Nullable`1 ordinanceId, Nullable`1 classId, Nullable`1 groupId, String shortDescription, String sorting, Int32 maxResultCount, Int32 skipCount, String userContentLangRestriction, CancellationToken cancellationToken) in C:\CT\AbxEps.Fines\aspnet-core\src\AbxEps.Fines.EntityFrameworkCore\FineDigitGroups\EfCoreFineDigitGroupRepository.cs:line 57

When I remove `Include(x => x.FineDigitGroupLanguages)` part - everything is fine.

Emphasizing - there is no issue with binding and getting `FineDigitGroupLanguages` data itself: it works fine as well. The problem begins when I try to sort or filter this `FineDigitGroup` list.

**Comment by smitpatel** [comment] 2021-07-21 15:42
Likely fixed in 6.0 since that code path has been removed.

**Comment by alexandis** [comment] 2021-07-22 09:06
> Likely fixed in 6.0 since that code path has been removed.

So in other words, do I need to wait till November to have this resolved:

> EF Core 6.0 is the next release after EF Core 5.0 and is currently scheduled for release in November 2021 at the same time as .NET 6.


or there's some temporary workaround?

**Comment by ajcvickers** [comment] 2021-07-26 13:53
@alexandis This is not something we can patch in 5.0 since the code changes involved would introduce too much risk. See the [planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for more information on patching.

If you are able to attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing, then we can potentially look for workarounds.

**Comment by alexandis** [comment] 2021-07-28 11:00
@ajcvickers Well.. I doubt I would be able to compose a running test solution here... But what I've noticed, this is happening when I try to use TWO "Includes" at the same time:

```
builder.Entity<FineDigit>()
    .HasMany(x => x.FineDigitTexts)
    .WithOne()
    .HasPrincipalKey(x => new { x.TenantId, x.OrdinanceId, x.Number, x.Subdivision, x.Version })
    .HasForeignKey(x => new { x.TenantId, x.OrdinanceId, x.Number, x.Subdivision, x.Version });
builder.Entity<FineDigit>()
    .HasOne(x => x.FineDigitRawKey)
    .WithMany()
    .HasPrincipalKey(x => new { x.TenantId, x.OrdinanceId, x.Number, x.Subdivision })
    .HasForeignKey(x => new { x.TenantId, x.OrdinanceId, x.Number, x.Subdivision });
```

```
public class FineDigit : LogEntity, IMustHaveTenant
{
    ...
    public FineDigitRawKey FineDigitRawKey { get; set; }
    public List<FineDigitText> FineDigitTexts { get; set; }
}
```

`var query = (await GetDbSetAsync()).Include(x => x.FineDigitRawKey).Include(x => x.FineDigitTexts) // ONLY ONE INCLUDE WORKS!`

Could you please suggest me the best way to replace this with something? I've tried to use one piece of System LINQ queryable extensions, but got confused... Probably I need to split it into two...

```
var query = from fd in await GetDbSetAsync()
            join fdt in (await GetDbContextAsync()).FineDigitTexts
            on
                new { fd.TenantId, fd.OrdinanceId, fd.Number, fd.Subdivision, fd.Version }
                equals
                new { fdt.TenantId, fdt.OrdinanceId, fdt.Number, fdt.Subdivision, fdt.Version }
            into fineDigitTexts
            join fdk in (await GetDbContextAsync()).FineDigitRawKeys
            on
                new { fd.TenantId, fd.OrdinanceId, fd.Number, fd.Subdivision }
                equals
                new { fdk.TenantId, fdk.OrdinanceId, fdk.Number, fdk.Subdivision }
            into fineDigitRawKeys
            from fineDigitRawKey in fineDigitRawKeys.DefaultIfEmpty()
            select new FineDigit
            {
                TenantId = fd.TenantId,
                ...
                FineDigitTexts = fineDigitTexts.DefaultIfEmpty(), // THIS NEEDS TO BE FILLED IN SEPARATE QUERY PROBABLY...
                FineDigitRawKey = fineDigitRawKey
            };
```

**Comment by ajcvickers** [comment] 2021-07-30 18:13
Closing as this code has been removed in the latest version and we don't have a repro.

**Closed** 2022-10-16 19:40 UTC
Labels: closed-could-not-reproduce, customer-reported
