### ISSUE TITLE
"Enumerator failed to MoveNextAsync" when using SingleOrDefaultAsync - after Save

### ISSUE THREAD

**Issue by kierenj** [dotnet/efcore#19639] opened 2020-01-19 20:54 UTC
### Steps to reproduce

I'm really sorry I don't have time right now for a full repro, but if this is tricky to track down I can put one together.

When I do a get-or-update:
```c#

            var rr = await _context.Set<ResourceReference>()
                .SingleOrDefaultAsync(r => r.Provider == "azure" && r.ResourceId == resourceId, cancel);
            if (rr == null)
            {
                _context.Set<ResourceReference>().Add(rr = new ResourceReference
                {
                    Provider = "azure",
                    ResourceId = resourceId
                });
            }
```

This works fine.

HOWEVER, if I run the above, THEN `SaveChangesAsync`, THEN exactly the same code again (same params), then the exception is triggered.

If I don't have the save call, it works fine.

```
System.InvalidOperationException: Enumerator failed to MoveNextAsync.
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
```

Pretty confused.. but even if I create a new context for every call, I still get the error.

### Further technical details

EF Core version: `3.0.0` / `3.1.1` ( just checked - still persists)
Database provider: `Microsoft.EntityFrameworkCore.SqlServer`
Target framework: `NET Core 3.0`
Operating system: `Windows 10 64-bit`
IDE: `VS Code`

**Comment by kierenj** [comment] 2020-01-19 21:24
Doing some digging, this is likely a bad error message, fixed in master (but not release/3.1), whereby if there are >1 results, this message is thrown rather than "sequence contains more than one element".

If that all adds up, please close! if more info needed, let me know. thanks

**Comment by ajcvickers** [comment] 2020-01-21 18:19
@maumar to investigate.

**Comment by CollinHerber** [comment] 2020-02-06 21:50
What was the resolution to this? I am now getting this as well.

**Comment by smitpatel** [comment] 2020-02-06 21:52
Duplicate of #18742

**Comment by kierenj** [comment] 2020-02-07 02:30
@CollinHerber  change the query or change the data: it’s because we have SingleOrDefault but there was >1 result. The bug is just that the error message is unhelpful

**Comment by CollinHerber** [comment] 2020-02-07 14:39
Hello @kierenj - Yes I understand the bug but our error logs become useless when this bug is present. The bug wasn't breaking my app but affecting my audit and logging tools.

Sorry for the misunderstanding.

**Comment by jmrnilsson** [comment] 2020-06-30 20:33
ah, yes, of course.  I believe this is I still an issue for aspnet core (ef core perhaps?) 3.1..

**Comment by huideaki** [comment] 2020-08-23 20:39
Still happens in efCore 3.1.7 when sequence contains 0 element with SingleAsync

**Comment by Davide-DD** [comment] 2020-09-11 09:24
Still happening in EF Core 3.1.8 with FirstAsync when sequence contains 0 elements

**Comment by galioni** [comment] 2020-09-20 22:05
Also still happening in EF Core 3.1.8 when calling SingleOrDefaultAsync when sequence contains 0 elements.

**Comment by smitpatel** [comment] 2020-09-21 02:55
This issue is duplicate of #18742 which has been fixed in 5.0 preview1 release. It will not work for any 3.1.x release.

**Comment by esfomeado** [comment] 2020-09-21 12:28
@smitpatel No chance of getting it back ported?

**Comment by smitpatel** [comment] 2020-09-21 14:38
@esfomeado - The issue is only about the message of the exception. Exception is still thrown since it is error. So there should be no impact on apps unless they are catching exception throwing and trying to match on the error message.

**Comment by Lechus** [comment] 2020-09-28 12:23
Still happens in efCore 3.1.8 when sequence contains 0 element with SingleAsync

**Comment by smitpatel** [comment] 2020-09-28 14:25
> This issue is duplicate of #18742 which has been fixed in 5.0 preview1 release. It will not work for any 3.1.x release.

**Closed** 2022-10-16 18:06 UTC
Labels: customer-reported

**Comment by okarpov** [comment] 2023-06-23 20:13
still occures at .net 7

**Comment by roji** [comment] 2023-06-24 17:42
@okarpov please open a new issue with a runnable, minimal code sample that shows the error happening.
