### ISSUE TITLE
When a table is renamed, migration operations are applied in the wrong order

### ISSUE THREAD

**Issue by burtonrodman** [dotnet/efcore#4808] opened 2016-03-16 01:54 UTC
When renaming a table (correct spelling in a ForSqlServerToTable extension call), the generated migration applies operations in the following order:
drop FKs (old table name), add FKs (new table name), rename table

this obviously results in an invalid object error during the phase of adding FKs.

manually moving the rename between the drop and add of FKs allows the migration to succeed.

**Comment by smitpatel** [comment] 2016-03-16 05:35
dupe of #3990

**Closed** 2022-10-16 09:33 UTC
