### ISSUE TITLE
Ability to exclude/skip/ignore parts of the model from migrations so that a table is not created (for overlapping bounded contexts)

### ISSUE THREAD

**Issue by brent-russell** [dotnet/efcore#2725] opened 2015-07-28 00:03 UTC
I suggest having an attribute that can be applied to DbSet properties in a DbContext, which indicates whether or not to include them in the migration scaffolding process.

An example use case is when part of an application's database is replicated from another environment.  Replicated entities will be included in the same DbContext as custom-developed entities so they can be queried. During development many migrations may be performed. Each time a migration is scaffolded, the replicated entities will be added to the migration, and then must be removed manually.

If an attribute only used for EF commands is too polluting to include in the DbContext, some alternatives might be: an additional config file that can be specified on the command line listing which entities should be excluded. Or perhaps additional command line arguments that allow a migration to be generated for specified entities only instead of scanning and comparing all entities.

Also consider the scenario of inherited models when looking at this feature https://github.com/aspnet/EntityFramework/issues/5572

**Comment by rowanmiller** [comment] 2015-07-30 18:40
Agreed that this would be good to enable. Generalized the title a bit as an attribute may or may not be the best way to do this. An attribute may be good sugar over a more powerful hook to exclude parts of the model.

Moving to backlog as we will look at this after the first stable release.

**Comment by wwarby** [comment] 2016-01-19 21:16
+1, this to would be extremely useful.

**Comment by maleet** [comment] 2016-03-18 12:40
+1

**Comment by ownakas1mon** [comment] 2016-06-02 13:44
+1

**Comment by soeron** [comment] 2016-09-08 12:15
+1 any status on this item?

**Comment by neridonk** [comment] 2016-11-23 08:52
+1 any status on this item?

**Comment by rowanmiller** [comment] 2016-11-23 17:44
No updates. We want to do it, but there are several items higher than it on the backlog.

**Comment by omayhemo** [comment] 2017-02-17 22:17
Those items listed have now been closed.  When can we expect inclusion?

**Comment by rowanmiller** [comment] 2017-02-17 23:33
The main features we talk about being higher priority are the ones listed here https://docs.microsoft.com/en-us/ef/efcore-and-ef6/features. There is still quite a list of them that have not been implemented.

**Comment by thiennn** [comment] 2017-03-15 11:01
I just found a workaround

1. Create another DbContext that inherit your DbContext, for example MigrationDbContext. Override the OnModelCreating method and ingore entities that you want it's table not being generated.

```cs
 protected override void OnModelCreating(ModelBuilder builder)
 {
     base.OnModelCreating(builder);
     builder.Ignore<Category>();
 }
```

2. Create another class that implement IDbContextFactory<MigrationDbContext>. For example

```cs
    public class MigrationContextFactory : IDbContextFactory<MigrationDbContext>
    {
        public MigrationDbContext Create()
        {
            var optionsBuilder = new DbContextOptionsBuilder<MigrationDbContext>();
            optionsBuilder.UseSqlite("Data Source=blog.db");

            return new MigrationDbContext(optionsBuilder.Options);
        }
    }
```
The migration tool will discover this MigrationContextFactory and use the MigrationDbContext.

**Comment by TobiasOskarsson** [comment] 2017-03-19 17:09
+1, This would make it possible to use ef core in plugin based architectures with each context inheriting from the core context with working relationships between contexts.

**Comment by Mucaccino** [comment] 2017-04-10 21:04
+1

**Comment by soeron** [comment] 2017-05-29 11:41
+1

**Comment by ganagus** [comment] 2017-12-11 07:18
+100

**Comment by dubs999** [comment] 2017-12-14 15:48
+1

**Comment by rindybo** [comment] 2017-12-27 16:45
Hope quickly,thank you

**Comment by Tarig0** [comment] 2018-01-02 19:59
To add to this, It would be nice to be able to add IgnoreBase or OnlyDeclared type options.

Though I think you would have to do something like
ModelB.Except(ModelA) 

There would be some very interesting cases such as when HasValue<> is used on a base entity

**Comment by Tarig0** [comment] 2018-01-02 20:20
Also If this goes into design, There should be a "depends on" migration attribute added to ensure that the tables that are required for the derived DBContext is inplace

**Comment by Biarity** [comment] 2018-01-03 13:43
+1 bump

**Comment by lambidu** [comment] 2018-02-08 15:40
+100500

**Comment by Hazzamanic** [comment] 2018-02-28 18:15
+1

**Comment by JunyuanZheng** [comment] 2018-04-29 04:10
+1

**Comment by JunyuanZheng** [comment] 2018-04-29 04:11
I am wondering does this means if I have IdentityDbContext & DbContext, and `ApplicationUser` (which is part of the `IdentityDbContext` & also part of the `DbContext`) will be created twice?

**Comment by nprieto95** [comment] 2018-05-31 08:08
Since no one made it explicit apart from the title on the “overlapping bounded contexts”, I add that this would be nice to have when working with DDD (Domain-Driven Design) so that beginners on that subject like me can find this more easily next time when searching for the term DDD.

**Comment by TheAifam5** [comment] 2018-06-10 15:54
When that will be in 3.0.0 release, then I'm gonna rewrite my projects to PHP or something else 😄

**Comment by arnvanhoutte** [comment] 2018-06-13 13:48
Any update about this?

**Comment by bricelam** [comment] 2018-06-13 16:02
@arnvanhoutte:

[![
divega modified the milestones: Backlog, 3.0.0 27 days ago](https://user-images.githubusercontent.com/1226749/41363295-6625b4ba-6ee8-11e8-9ec9-d724c45c11dc.png)](https://github.com/aspnet/EntityFrameworkCore/issues/2725#event-1632388748)

**Comment by alexsandro-xpt** [comment] 2018-11-17 20:00
+1
It will be useful for work within mixed fixed tables and migration tables making migration genered table working together.

**Comment by btodts** [comment] 2019-02-22 09:48
+1, definitely

**Comment by MaklaCof** [comment] 2019-02-22 13:54
Also very useful when database model is shared with another application, which handles migrations for some entities, but not all.

**Comment by bricelam** [comment] 2019-05-13 18:58
**Note to implementer**: Update the obsolete `ToView` method to call this in order to preserve its old semantics.

**Comment by cmorgan091** [comment] 2019-05-21 16:28
+1 this is key to DDD that implement a common context where there is a need for referential integrity from other contexts (multi-tenant or references to users or other common elements)

In EF6 we could hack this by implementing a CSharpMigrationCodeGenerator which overrode Generate commands to check the schema name and just return.  Have attempted this with a SqlServerMigrationsSqlGenerator in EF Core but have failed to get this to work in a similar way.  If anyone has had any luck with this I would appreciate any notes

**Comment by cmorgan091** [comment] 2019-05-28 20:28
For anybody that is interested, I have implemented a workaround that I believe allows this to work when the elements you want to exclude are part of a different schema in the database (which is what I wanted to do).

I have included this as an example in an issue I have raised here: [https://github.com/aspnet/EntityFrameworkCore/issues/15828](url)

Let me know if this helps anyone

**Comment by ajcvickers** [comment] 2019-06-06 19:30
Consider also the case of excluding FKs from the database: #15854

**Comment by ajcvickers** [comment] 2019-06-27 17:32
Proposing punt...

**Comment by echuck66** [comment] 2019-07-09 12:17
I see that another reported issue was marked as a duplicate of this one...

https://github.com/aspnet/EntityFrameworkCore/issues/14283

I'm not seeing how this is a duplicate of that issue, and was wondering if any progress had been made or fix found for the issue of subsequent migrations attempting to re-create tables that have already been created in subsequent migrations. It's like instead of attempting an 'ALTER TABLE' process, the software punts and decides to just re-create the table. This is NOT a good thing.

If I recall correctly, last year things were not so messed up with EF Core and related technologies. Today, there seems to be a lot of packages incompatible with newer ones (to be expected to some degree), but I'm also finding newer packages and technologies are not working as they should. Case in point: MySql package for EF Core has no default mechanism to convert bit to boolean. This is very basic stuff. 

Anyway, enough of my rant... is there a fix to prevent ef core migrations from attempting to re-create tables that already exist?

**Comment by ajcvickers** [comment] 2019-07-09 18:21
@echuck66 It sounds like your issue is different to the feature that is being tracked here. Can you please file a new issue and include a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by echuck66** [comment] 2019-07-10 10:08
...disregard. I think I figured out what's going on... ef core is tracking updates to the schema in the project snapshot file.  It was missing.

**Comment by ajcvickers** [comment] 2019-11-19 23:30
Also consider an attribute for at least some of this. (If it doesn't get done with the fluent API, then create a new issue for it.) See https://github.com/aspnet/EntityFrameworkCore/issues/18719#issuecomment-554751397

**Comment by MBroertjes** [comment] 2019-11-20 07:26
> Proposing punt...

This was punted for 3.0 but didn't make it? What's the new ETA for this feature? It would be of great benifit for the corporation I'm working for.

**Comment by ajcvickers** [comment] 2019-11-20 16:21
@MBroertjes We're still working on planning, but it's looking like this will be in 5.0, hence the milestone currently assigned.

**Comment by stantoxt** [comment] 2019-12-16 02:28
I hope this feature can be moved up, this is a really wanted feature.

**Comment by AndriySvyryd** [comment] 2020-01-31 01:16
Related to https://github.com/dotnet/efcore/issues/15671

**Comment by webwarrior06** [comment] 2020-06-10 11:54
I solved it checking from where the entity builder is called, (from **"add-migration Xyz" command** or the normal dbContext operations) If a migration operation calls the builder, I ignore the entity that I want to ignore just for migration purposes.
Here is my workaround;
https://stackoverflow.com/a/62281191/1928672

**Closed** 2020-06-24 01:01 UTC
Labels: area-migrations, area-model-building, closed-fixed, punted-for-3.0, type-enhancement

**Comment by aloksharma1** [comment] 2022-05-18 19:31
did this ever got added in new versions, +1000000 btw :)

**Comment by AndriySvyryd** [comment] 2022-05-18 19:50
@aloksharma1 [Yes, it's in 5.0.0 ](https://docs.microsoft.com/ef/core/modeling/entity-types?tabs=data-annotations#excluding-types-from-the-model)

**Comment by VeMike** [comment] 2023-01-13 18:01
So how would I ignore just a base class, but not a derived class using [this approach](https://learn.microsoft.com/en-us/ef/core/modeling/entity-types?tabs=data-annotations#excluding-types-from-the-model)?

Consider the following model:

```cs
[Table(nameof(Human))]
public class Human
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int HumanId { get; set; }
    
    public int Age { get; set; }
}

[Table(nameof(Developer))]
public class Developer : Human
{
    public string MainLanguage { get; set; }
}
```

The database context for this model is the following

```cs
public class FooContext : DbContext
{
    public DbSet<Developer> Developers { get; set; } = null!;

    /// <inheritdoc />
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // This is made to get TPT
        modelBuilder.Entity<Human>().ToTable(nameof(Human));
        modelBuilder.Entity<Developer>().ToTable(nameof(Developer));
        
        modelBuilder.Entity<Human>().ToTable(nameof(Human), t => t.ExcludeFromMigrations());
    }

    /// <inheritdoc />
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);

        optionsBuilder.UseSqlServer("<FooBarConnectionString>");
    }
}
```

As you can see I only want `Developer` to be in the migration. `Human` should be excluded. Why would I want to do this? I am extending an existing model and the base (`Human`) already exists in the database. I want to add `Developer` to this existing model.

But if I create a migration the whole hierarchy of `Human` is excluded (basically all classes of type `Human`). But I want the `Developer` to be created.

Of course, I could just remove the line

```cs
modelBuilder.Entity<Human>().ToTable(nameof(Human), t => t.ExcludeFromMigrations());
```

and then manually remove the added `Human` from the migration. But is there a way to do this automatically?

**Comment by ajcvickers** [comment] 2023-01-17 12:10
@VeMike Moved here: https://github.com/dotnet/efcore/issues/30079
