### ISSUE TITLE
EF Core Migrations Ignoring snapshot state when run from dotnet but not from PMC

### ISSUE THREAD

**Issue by StrangeWill** [dotnet/efcore#10367] opened 2017-11-21 16:56 UTC
Upon running `dotnet ef migration add` I am getting a *full* migration of my database from scatch.

Running `Add-Migration` from the package manager console properly generates the right migration (added a single column).

Running `dotnet ef database update` properly updates the correct database.

`dotnet ef migration add` also properly updates the snapshot file.

I'm not sure what factors may be contributing to this so as far as troubleshooting goes I'm at a loss. I have a workaround by using the PMC but the split behavior leaves me concerned that I stumbled across something.

EF Core Tools version: 1.1.0
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment] 2017-11-22 21:54
@StrangeWill Can you post a full code listing or working project that reproduces this issue? Also, do you know if it also repros using EF Core 2.0.1?

**Comment by ajcvickers** [comment] 2017-11-29 19:35
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:00 UTC
Labels: closed-could-not-reproduce
