### ISSUE TITLE
QueryRewrite: implement entity equality

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#15185] opened 2019-03-27 22:08 UTC
When comparing entities, we should compare their keys instead. Some of the functionality is handled by nav expansion, however there are cases that are not.

e.g.: order by entity key, group by entity key, join where key selectors are entities

**Comment by smitpatel** [comment] 2019-05-14 16:06
Duplicate of #15588

**Closed** 2022-10-16 13:57 UTC
