### ISSUE TITLE
DefaultIfEmpty().Max() InvalidOperationException throws 'Sequence contains no elements.'

### ISSUE THREAD

**Issue by anddrzejb** [dotnet/efcore#17988] opened 2019-09-22 07:58 UTC
After update to dotnet core 3.0 RC1 running following code 
```
var value = context.Products.Where(t => t.CategoryId == catId).Select(t => t.Version).DefaultIfEmpty().Max();
```
throws 
```
System.InvalidOperationException: Sequence contains no elements.
   at int lambda_method(Closure, QueryContext, DbDataReader, ResultContext, int[], ResultCoordinator)
   at bool Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor+QueryingEnumerable<T>+Enumerator.MoveNext()
   at TSource System.Linq.Enumerable.Single<TSource>(IEnumerable<TSource> source)
   at TResult Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute<TResult>(Expression query)
   at TResult Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute<TResult>(Expression expression)
   at TSource System.Linq.Queryable.Max<TSource>(IQueryable<TSource> source)
   at ... (my method that run the code)
```

### Steps to reproduce
Create entity that maps to a simple table Product.cs
``` C#
    [Table("tmpExtProduct", Schema = "ext")]
    public partial class Product
    {
        public int Version { get; set; }
        public int CategoryId { get; set; }        
    }
```
with context 
``` C#
        public virtual DbSet<Product> Products { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Product>(entity =>
            {
                entity.HasKey(e => e.Version)
                    .HasName("PK__Product");

                entity.Property(e => e.Version).ValueGeneratedNever();
            });

            OnModelCreatingPartial(modelBuilder);
        }
```
Minimal [repro](https://github.com/anddrzejb/EFCoreDefaultIfEmpty_Max_Bug)

### Further technical details

EF Core version: 3.0.0-rc1.19456.14
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: W10 Pro
IDE: Visual Studio 2019 16.3 Preview 4.0

**Comment by smitpatel** [comment] 2019-09-23 18:43
Currently we always throw for null result in Min/Max/Average. It should consider existence of DefaultIfEmpty or perhaps other scenarios around nullability.

**Comment by smitpatel** [comment] 2019-09-23 18:49
Work-around
```C#
var valueFail = context.Products.Where(t => t.CategoryId == catId)
                .GroupBy(e => 1)
                .Select(t => t.Max(e => e.Version))
                .ToList()[0];
```
Groupby a constant so whole table will be in one group and then apply aggregate operator.

**Comment by anddrzejb** [comment] 2019-09-23 18:56
Is your workaround better then what I found?
```C#
var value = context.Products.Where(t => t.CategoryId == catId)
            .Select(t => t.Version)
            .DefaultIfEmpty().ToList().Max();
```
This at least gives me hope for a simple replace once maybe previously working syntax comes back.

**Comment by smitpatel** [comment] 2019-09-23 20:12
@anddrzejb - The work-around I posted will process everything on server-side. In your case it will get all the versions from server side to compute max when the categoryId you are comparing gives multiple reasons.

**Comment by smitpatel** [comment] 2019-12-10 01:50
May have same root cause as #18955

**Comment by liamwang** [comment] 2020-04-24 02:59
How's it going now?

My current workaround is:
```cs
var maxSn = await Entities
    .Where(x => x.Date == date)
    .OrderByDescending(x => x.Sn)
    .Select(x => x.Sn)
    .FirstOrDefaultAsync();
```

It would be nice if provide the following API:

```cs
var maxSn= await Entities.MaxOrDefaultAsync(x => x.Sn);
```

**Comment by fellow7000** [comment] 2020-06-16 20:47
Looks like this stuff does not work even in 3.1
Why is the issue closed?..

**Comment by smitpatel** [comment] 2020-06-16 20:54
The issue is still open...

**Comment by smitpatel** [comment] 2020-08-28 01:43
Duplicate of #20589

**Comment by arendvw** [comment] 2020-11-25 17:05
> 
> 
> How's it going now?
> 
> My current workaround is:
> 
> ```cs
> var maxSn = await Entities
>     .Where(x => x.Date == date)
>     .OrderByDescending(x => x.Sn)
>     .Select(x => x.Sn)
>     .FirstOrDefaultAsync();
> ```
> 
> It would be nice if provide the following API:
> 
> ```cs
> var maxSn= await Entities.MaxOrDefaultAsync(x => x.Sn);
> ```

This workaround gets similar performance (sorting done by SQL server) in indexed cases, with the benefit of having a much less awkward syntax.

**Comment by jack0fshad0ws** [comment] 2020-12-28 02:27
Why on Earth this got broken in the first place?! This was the usual way to handle null/max in EF `DefaultIfEmpty().Max()`.. so still appears not resolved?

**Comment by titobf** [comment] 2020-12-28 14:32
@jack0fshad0ws .DefaultIfEmpty() works for me on EF 5, but .DefaultIfEmpty(0) doesn't. I initially got caught by this. Maybe check if you aren't doing the same.

**Comment by jack0fshad0ws** [comment] 2020-12-28 17:54
> @jack0fshad0ws .DefaultIfEmpty() works for me on EF 5, but .DefaultIfEmpty(0) doesn't. I initially got caught by this. Maybe check if you aren't doing the same.

Thanks, I'm still on EF Core 3 (3.1) and it's not working there, so doing `.Any` to check first.. guess gotta upgrade to 5 soon.

**Comment by engmustafak26** [comment] 2021-09-09 12:08
> Work-around
> 
> ```cs
> var valueFail = context.Products.Where(t => t.CategoryId == catId)
>                 .GroupBy(e => 1)
>                 .Select(t => t.Max(e => e.Version))
>                 .ToList()[0];
> ```
> 
> Groupby a constant so whole table will be in one group and then apply aggregate operator.

This above code break when table "Products" is empty
Code that work with all cases

> 
> ```cs
> var valueFail = context.Products.Where(t => t.CategoryId == catId)
>                 .Select(e => e.Version)
>                 .ToArray()
>                 .Append(0)
>                 .Max();
>                 
> ```

**Closed** 2022-10-16 14:43 UTC
Labels: closed-duplicate, customer-reported
