### ISSUE TITLE
Add support for Conventions in ModelBuilder

### ISSUE THREAD

**Issue by Saibamen** [dotnet/efcore#21819] opened 2020-07-28 15:24 UTC
I'm migration from EF to EF Core (preview 6 now), but there is no `AttributeToTableAnnotationConvention` and `ModelBuilder.Conventions`.

Code working for old EF:

```
var softDeletableConvetion = new AttributeToTableAnnotationConvention<SoftDeleteAttribute, string>("SoftDeleteColumnName", (type, attributes) => attributes.First().ColumnName);
_modelBuilder.Conventions.Add(softDeletableConvetion);
```

**Comment by AndriySvyryd** [comment] 2020-07-28 18:42
Duplicate of #214

Though you'll need to adjust your code even after this is implemented

**Closed** 2022-10-16 18:35 UTC
Labels: customer-reported
