### ISSUE TITLE
Remove Newtonsoft.Json from the shared framework

### ISSUE THREAD

**Issue by joshfree** [dotnet/efcore#14717] opened 2019-02-15 22:02 UTC
https://github.com/aspnet/AspNetCore/issues/4260

See https://github.com/aspnet/AspNetCore/issues/7289

/cc @ahsonkhan @bartonjs @Eilon @glennc

**Comment by ajcvickers** [comment] 2019-02-15 22:09
Duplicate of #14571

**Closed** 2022-10-16 13:52 UTC
