### ISSUE TITLE
Select include not mapping object field value！

### ISSUE THREAD

**Issue by geekyzk** [dotnet/efcore#23431] opened 2020-11-22 09:30 UTC
## File a bug

Remember:

### Include your code
Three model, for example: 
```C#
 public class OneModel {

 public ICollection<TwoModel> TwoModels{ get; set; }
}

public class TwoModel {
   public string ResourceName { get; set; }

   public decimal ResourcePrice { get; set; }
   public OneModel OneModel { get; set; }

   public long OneModelId{ get; set; }
}

public class ThreeModel {
        public OneModel OneModel { get; set; }

        public long OneModelId{ get; set; }
}
```

When using select 、include

```C#
 var threeModel= dataContext.threeModels
                .Include(c => c.OneModel)
                .ThenInclude( c => c.TwoModels)
                .First(c => c.Id == threeModelId);
```
in result , not get twoModel entity ResourcePrice field , but get other field value 

### Include stack traces
In debug , the ResourcePrice throw System.NullReferenceException . 
```

### Include provider and version information
    <PropertyGroup>
        <TargetFramework>netcoreapp5</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
    <PackageReference Include="DevExtreme.AspNet.Data" Version="2.7.1" />
    <PackageReference Include="DevExtreme.AspNet.Core" Version="20.2.3" />
    <PackageReference Include="BuildBundlerMinifier" Version="2.9.406" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="5.0.0-alpha.2" />
    <PackageReference Include="RestSharp" Version="106.11.7" />
    </ItemGroup>


In NetCore3.1 , no error for same code 。
  <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
    <PackageReference Include="DevExtreme.AspNet.Data" Version="2.7.1" />
    <PackageReference Include="DevExtreme.AspNet.Core" Version="20.2.3" />
    <PackageReference Include="RestSharp" Version="106.11.7" />
        <PackageReference Include="BuildBundlerMinifier" Version="2.9.406" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.9" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.9" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.2.3" />
    </ItemGroup>

**Comment by ajcvickers** [comment] 2020-11-22 18:17
@geekyzk Please post the full stack trace of the exception.

**Comment by geekyzk** [comment] 2020-11-23 01:51
![image](https://user-images.githubusercontent.com/21106445/99923588-58d76e80-2d71-11eb-93d0-63c6c5280819.png)
@ajcvickers  not throw exception,  just not mapping field value

**Comment by ajcvickers** [comment] 2020-11-23 17:02
@geekyzk In that case, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by joakimriedel** [comment] 2020-11-25 12:43
Related? https://github.com/dotnet/efcore/issues/23447

**Comment by ajcvickers** [comment] 2020-12-04 17:26
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:11 UTC
Labels: closed-could-not-reproduce, customer-reported
