### ISSUE TITLE
Calling Select.Distinct inside of a Select causes duplicate parent entries if a value is null

### ISSUE THREAD

**Issue by Corey-G-Adkins** [dotnet/efcore#31611] opened 2023-09-02 00:14 UTC
## Steps to Reproduce

I have a query which is projecting a database model and a child object into new objects via `Select`.

Here are simplified versions of my domain models.
```C#
public class Parent 
{
    [Key]
    public int Id { get; set; }
    public ICollection<Child> Children { get; set; }
    [NotMapped]
    public IEnumerable<string> ChildValues { get; set; }
}

public class Child
{
    [Key]
    public int Id { get; set; }
    [ForeignKey(nameof(Parent))]
    public int ParentId {get; set; }
    public string Value { get; set; }
}
```

And here is a simplified version of the query:
```C#
DbContext.Set<Parent>().Where(x => x.Id == 1).Select(x => new Parent { ChildValues = x.Children.Select(y => y.Value).Distinct() }).ToList();
```

(The actual query is projecting them into different objects than their domain models but the issue is still replicable here).

When I have stored values for `Child.Value` that are both `null` and not `null`, this query will return two `Parent` objects, one with its `ChildValues` as an empty enumerable, and another with all non-`null` values as its `ChildValues`. The expected behavior is that it returns one `Parent` with a `ChildValues` whose items are all saved variations of `Child.Value`, including `null`. Removing `Distinct` removes this duplication of `Parent`, but obviously prevents me from filtering out duplicate values in the query.

The SQL query that is generated selects an object for each combination of parent and child values, so it appears the grouping of the non-`null` values is happening in memory (which makes sense since it is not being set to a domain property), but somehow the `null` value is getting missed in that grouping and thus getting a separate parent entry returned for it.
 
```SQL
SELECT [p].[Id], [t].[Value]
FROM [dbo].[Parents] AS [p]
OUTER APPLY (
    SELECT DISTINCT [c].[Value]
    FROM [dbo].[Children] AS [c]
    WHERE (([p].[Id] = [c].[ParentId])
) AS [t]
ORDER BY [p].[Id]
```

Thanks in advance for your help!

### Provider and Version Information
EF Core version: 6.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.3.6

**Comment by maumar** [comment] 2023-09-14 21:42
dupe of https://github.com/dotnet/efcore/issues/31277 

@Corey-G-Adkins this should only happen if the projected values are all nullable. You can try a workaround where you create a dummy non-nullable property, and fill it with the same value. This way your Distinct will still work correctly (as all the dummy values are the same) and EF will have a non-nullable property to reason about when it comes to correctly bucketing the results.

**Closed** 2023-09-20 19:27 UTC
Labels: closed-duplicate, customer-reported
