### ISSUE TITLE
Always trying to delete the 'Discriminator' column even if it doesn't exist when migration

### ISSUE THREAD

**Issue by simader** [dotnet/efcore#17396] opened 2019-08-23 11:31 UTC
I have a Model, where most of my Object inherts from a BaseClass (abstract class SoftDeletableEntity) which has e.g. IsDeleted bool. But this is just used, that all the Enities have the same column. not for any hierachy per type or so. 

When I run Add-Migration Initial every works fine and I can create a new Database.

However if I run a second time Add-Migration it adds the following code is included in the migration.

```
 migrationBuilder.AddColumn<string>(
                name: "Discriminator",
                table: "User",
                nullable: false,
                defaultValue: "");

```
And so Update-Database will fail.

I am using ef core 2.2.6

**Comment by ajcvickers** [comment] 2019-09-06 16:29
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:37 UTC
Labels: closed-could-not-reproduce, customer-reported
