### ISSUE TITLE
System.NullReferenceException on .thenInclude when migrating to 2.0

### ISSUE THREAD

**Issue by tsebastiani** [dotnet/efcore#9619] opened 2017-08-30 08:05 UTC
I'm porting this application to 2.0sdk, the query that is actually causing the exception works perfectly on 1.1.

The exception is raised when an ApplicationUser has a NULL GroupId on the database.
Commenting  ".ThenInclude(g => g.Companies)" the exception doesn't happen anymore, looks like entity keeps on joining tables even if the previous relationship is not satisfied.

I tried to switch to PostgreSQL blaming on the MySQL driver maturity , but I've the same exception.

```
Exception has occurred: CLR/System.NullReferenceException
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll: 'Object reference not set to an instance of an object.'
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.IncludeLoadTreeNodeBase.<_AwaitMany>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.<_IncludeAsync>d__18`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.<_ExecuteAsync>d__8`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at HelpDesk.ControllersAPI.TicketController.<GetList>d__6.MoveNext() in 
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
           

//query that is causing the exception
var user = await dbContext.ApplicationUser
.Include(u => u.Group)
    .ThenInclude(g => g.Companies) //<== commenting this bit the exception doesn't happen anymore
.Include(u => u.UserCompanyList)
    .ThenInclude(ug => ug.Company)
.Include(u => u.UserPermissionList)
    .ThenInclude(up => up.Permission)
.Include(u => u.UserTicketList)
.Where(u => u.UserName == User.Identity.Name).FirstOrDefaultAsync();


//Group.cs
 public class Group : AbstractModel
    {
        public int Id { get; set; }
        [JsonIgnore]
        public List<Company> Companies { get; set; }
        [JsonIgnore]
        public List<ApplicationUser> Users { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Website { get; set; }
        public string VATNumber { get; set; }
        public bool isRootGroup { get; set; } = false;
        public int? ImageId { get; set; }
        [JsonIgnore]
        public Image Image { get; set; }
        public List<Template> TemplateList {get; set;}
}

//Company.cs
public class Company : AbstractModel
    {
        public int Id { get; set; }
        public int? GroupId { get; set; } //<== Group Relationship (nullable)
        [JsonIgnore]
        public Group Group { get; set; }
        [JsonIgnore]
        public List<UserCompany> UserCompanyList { get; set; }
        [JsonIgnore]
        public List<Ticket> TicketList { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Website { get; set; }
        public string VATNumber { get; set; }
        public bool IsActive { get; set; } = true;
        public int? ImageId { get; set; }
        [JsonIgnore]
        public Image Image { get; set; }
}

//ApplicationUser.cs
public class ApplicationUser : IdentityUser<int>
    {
        public UserType UserType { get; set; }
        [JsonIgnore]
        public Group Group { get; set; }
        public int? GroupId { get; set; } //<==Group Relationship (nullable)
        [JsonIgnore]
        public List<UserCompany> UserCompanyList { get; set; }
        [JsonIgnore]
        public List<UserTicket> UserTicketList { get; set; }
        [JsonIgnore]
        public List<UserPermission> UserPermissionList { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public int? ImageId { get; set; }
        [JsonIgnore]
        public Image Image { get; set; }
        public bool IsActive { get; set; } = true;
}
```

### Further technical details
EF Core version: "Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.0.0"
Database Provider: "Pomelo.EntityFrameworkCore.MySql" Version="2.0.0-rtm-10058"
Operating system: Ubuntu Linux 17.04
IDE: VSCode

**Comment by ajcvickers** [comment] 2017-08-30 23:31
Duplicate of #9038

**Comment by ajcvickers** [comment] 2017-09-12 18:57
Hi @tsebastiani. We are gathering information on the use of EF Core pre-release builds. You reported this issue shortly after the release of 2.0.0 RTM. It would be really helpful if you could let us know:

- Did you consider testing your code against the pre-release builds?
- Was there anything blocking you from using pre-release builds?
- What do you think could make it easier for you to use pre-release builds in the future?

Thanks in advance for any feedback. Hopefully this will help us to increase the value of pre-release builds going forward.

**Comment by ajcvickers** [comment] 2018-06-11 16:53
@Ali-YousefiTelori Please open a new issue including a runnable project/solution that demonstrates the behavior you are seeing.

**Comment by josefblaha** [comment] 2018-12-05 12:49
I encountered this problem in 2.1.2. Seems like upgrading to 2.2.0 fixed that.

**Closed** 2022-10-16 11:19 UTC
Labels: closed-duplicate
