### ISSUE TITLE
ToLower not working with AsQueryable  on sqlite

### ISSUE THREAD

**Issue by suatsuphi** [dotnet/efcore#27378] opened 2022-02-04 21:07 UTC
ToLower not working with AsQueryable  on sqlite but it is working on MS SQL 

```c#
[AllowAnonymous]
        [HttpPost]
        public JsonResult GetReports(string publisher = null, string tag = null)
        {
            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                string searchValue = Request.Form["search[value]"].FirstOrDefault().ToLower();

                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;

                var customerData = _unitOfWork.Reports.GetAll().Include(i => i.Publisher).Include(i => i.ReportTags).ThenInclude(i => i.Tag)
                                                               .Where(i => i.IsApproved && i.Language.Culture == CultureInfo.CurrentCulture.Name)
                                                               .OrderByDescending(i => i.ReleaseDate).AsQueryable();
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    customerData = customerData.OrderBy(i => sortColumn + " " + sortColumnDirection).AsQueryable();
                }
                if (!string.IsNullOrEmpty(searchValue))
                {
                    customerData = customerData.Where(i => i.Title.ToLower().Contains(searchValue)).AsQueryable(); 

                    //customerData = customerData.Where(i => i.Title.ToLower().Contains(searchValue)
                    //                                       || i.Summary.ToLower().Contains(searchValue)
                    //                                       || i.Publisher.Name.ToLower().Contains(searchValue)
                    //                                    ).ToList();
                }
                if (!string.IsNullOrEmpty(publisher))
                {
                    customerData = customerData.Where(i => i.Publisher.Url == publisher).AsQueryable();
                }
                if (!string.IsNullOrEmpty(tag))
                {
                    customerData = customerData.Where(i => i.ReportTags.Any(a => a.Tag.Url.Equals(tag))).AsQueryable();
                }
                recordsTotal = customerData.Count();
                var data = customerData.Skip(skip).Take(pageSize)
                                        .Select(i => new { id = i.ReportId, title = i.Title, summary = i.Summary, releaseDate = i.ReleaseDate.Value.ToShortDateString(), publisherName = i.Publisher.Name, url = i.Url })
                                        .ToList();
                var jsonData = new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data };
                return Json(jsonData);
            }
            catch
            {
                return Json("");
            }
        }
```

it is working with ToList() on sqlite

**Comment by suatsuphi** [comment] 2022-02-23 08:46
Hi,

It has a repository structure that like below

`
public interface IGenericRepository<T> where T : class
    {
        T Get(int id);
        IQueryable<T> GetAll();
        IQueryable<T> Find(Expression<Func<T, bool>> predicate);
        void Add(T entity);
        void Delete(T entity);
        void Edit(T entity);
        void AddRange([NotNullAttribute] IEnumerable<T> entities);
        void DeleteRange([NotNullAttribute] IEnumerable<T> entities);
        void EditRange([NotNullAttribute] IEnumerable<T> entities);
        void Save();
    }
`

`
    public class EfGenericRepository<T> : IGenericRepository<T> where T : class
    {
        protected readonly DbContext context;

        public EfGenericRepository(DbContext context)
        {
            this.context = context;
        }
        
        public void AddRange([NotNullAttribute] IEnumerable<T> entities)
        {
            context.Set<T>().AddRange(entities);
        }
        public void DeleteRange([NotNullAttribute] IEnumerable<T> entities)
        {
            context.Set<T>().RemoveRange(entities);
        }
        public void EditRange([NotNullAttribute] IEnumerable<T> entities)
        {
            context.Set<T>().UpdateRange(entities);
        }

        public void Add(T entity)
        {
            context.Set<T>().Add(entity);
        }

        public void Delete(T entity)
        {
            context.Set<T>().Remove(entity);
        }

        public void Edit(T entity)
        {
            context.Entry(entity).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
        }

        public IQueryable<T> Find(Expression<Func<T, bool>> predicate)
        {
            return context.Set<T>().Where(predicate);
        }

        public T Get(int id)
        {
            return context.Set<T>().Find(id);
        }

        public IQueryable<T> GetAll()
        {
            return context.Set<T>();
        }

        public void Save()
        {
            context.SaveChangesAsync();
        }
    }
`

**Comment by suatsuphi** [comment] 2022-02-23 08:52
Hi,

It has a repository structure that like below

`

public interface IGenericRepository<T> where T : class
    {
        T Get(int id);
        IQueryable<T> GetAll();
        IQueryable<T> Find(Expression<Func<T, bool>> predicate);
        void Add(T entity);
        void Delete(T entity);
        void Edit(T entity);
        void AddRange([NotNullAttribute] IEnumerable<T> entities);
        void DeleteRange([NotNullAttribute] IEnumerable<T> entities);
        void EditRange([NotNullAttribute] IEnumerable<T> entities);
        void Save();
    }


`

`

    public class EfGenericRepository<T> : IGenericRepository<T> where T : class
    {
        protected readonly DbContext context;

        public EfGenericRepository(DbContext context)
        {
            this.context = context;
        }

        public void AddRange([NotNullAttribute] IEnumerable<T> entities)
        {
            context.Set<T>().AddRange(entities);
        }
        public void DeleteRange([NotNullAttribute] IEnumerable<T> entities)
        {
            context.Set<T>().RemoveRange(entities);
        }
        public void EditRange([NotNullAttribute] IEnumerable<T> entities)
        {
            context.Set<T>().UpdateRange(entities);
        }

        public void Add(T entity)
        {
            context.Set<T>().Add(entity);
        }

        public void Delete(T entity)
        {
            context.Set<T>().Remove(entity);
        }

        public void Edit(T entity)
        {
            context.Entry(entity).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
        }

        public IQueryable<T> Find(Expression<Func<T, bool>> predicate)
        {
            return context.Set<T>().Where(predicate);
        }

        public T Get(int id)
        {
            return context.Set<T>().Find(id);
        }

        public IQueryable<T> GetAll()
        {
            return context.Set<T>();
        }

        public void Save()
        {
            context.SaveChangesAsync();
        }
    }


`

________________________________

**Comment by AndriySvyryd** [comment] 2022-02-23 19:39
@suatsuphi Please provide a complete runnable sample

**Comment by suatsuphi** [comment] 2022-02-23 20:56
Hi,

there is a sample: 
https://github.com/suatsuphi/SQLiteTest/

**Comment by ajcvickers** [comment] 2022-03-01 12:40
@suatsuphi What steps are needed to reproduce the error with that sample?

**Comment by suatsuphi** [comment] 2022-03-01 13:20
could you search 'akaryakıt ürünlerine uygulanacak' and after that change .AsQueryable() with .ToList()
could you search it again that 'akaryakıt ürünlerine uygulanacak'

```


        [AllowAnonymous]
        [HttpPost]
        public JsonResult GetReports(string publisher = null, string tag = null)
        {
            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                string searchValue = Request.Form["search[value]"].FirstOrDefault().ToLower();

                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;

                var customerData = _unitOfWork.Reports.GetAll().Include(i => i.Publisher).Include(i => i.ReportTags).ThenInclude(i => i.Tag)
                                                               .Where(i => i.IsApproved && i.Language.Culture == CultureInfo.CurrentCulture.Name)
                                                               .OrderByDescending(i => i.ReleaseDate).ToList();
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    customerData = customerData.OrderBy(i => sortColumn + " " + sortColumnDirection).ToList();
                }
                if (!string.IsNullOrEmpty(searchValue))
                {
                    customerData = customerData.Where(i => i.Title.ToLower().Contains(searchValue)
                                                           || i.Summary.ToLower().Contains(searchValue)
                                                           || i.Publisher.Name.ToLower().Contains(searchValue)
                                                        ).AsQueryable();
                }
                if (!string.IsNullOrEmpty(publisher))
                {
                    customerData = customerData.Where(i => i.Publisher.Url == publisher).ToList();
                }
                if (!string.IsNullOrEmpty(tag))
                {
                    customerData = customerData.Where(i => i.ReportTags.Any(a => a.Tag.Url.Equals(tag))).ToList();
                }
                recordsTotal = customerData.Count();
                var data = customerData.Skip(skip).Take(pageSize)
                                        .Select(i => new { id = i.ReportId, title = i.Title, summary = i.Summary, releaseDate = i.ReleaseDate.Value.ToShortDateString(), publisherName = i.Publisher.Name, url = i.Url })
                                        .ToList();
                var jsonData = new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data };
                return Json(jsonData);
            }
            catch
            {
                return Json("");
            }
        }
```

**Comment by ajcvickers** [comment] 2022-03-02 11:53
Note for triage: looks like an issue with the way SQLite handles Unicode characters. Doubt there is anything EF can do.

```C#
public class Blog
{
    public int Id { get; set; }
    public string Title { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlite("Data Source=test.db")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    public DbSet<Blog> Blogs { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog {Title = "Akaryakıt Ürünlerine Uygulanacak ÖTV Tutarlarının Güncellenmesi Hk."});
            context.SaveChanges();
        }

        using (var context = new SomeDbContext())
        {
            // Works:
            var searchValue = "uygulanacak";
            Console.WriteLine(context.Blogs.FirstOrDefault(e => e.Title.ToLower().Contains(searchValue))?.Title ?? "Not found.");
            // Doesn't work:
            searchValue = "akaryakıt ürünlerine uygulanacak";
            Console.WriteLine(context.Blogs.FirstOrDefault(e => e.Title.ToLower().Contains(searchValue))?.Title ?? "Not found.");
        }
    }
}
```

**Comment by ajcvickers** [comment] 2022-03-03 10:40
@suatsuphi `ToList()` pulls all rows from the database and then filters in-memory using .NET strings. Without `ToList()`, a query is generated to do the filtering in SQLite and only bring back the matching rows.

**Comment by suatsuphi** [comment] 2022-03-03 12:24
thank you so when I use MS SQL no problem.

**Comment by suatsuphi** [comment] 2022-03-03 19:28
is there any way to override ToLower ? 

```


using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Text;

public class Blog
{
    public int Id { get; set; }
    public string Title { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlite("Data Source=test.db")
            //.LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    public DbSet<Blog> Blogs { get; set; }
}
public static class StringExtensions
{
    public static string ToLowerAscii(this string value)
    {
        char[] originalString = value.ToLower().ToCharArray();
        StringBuilder asAscii = new StringBuilder(); // store final ascii string and Unicode points
        foreach (char c in originalString)
        { 
            // test if char is ascii, otherwise convert to Unicode Code Point
            int cint = Convert.ToInt32(c);
            if (cint <= 127 && cint >= 0)
                asAscii.Append(c);
            else
                asAscii.Append(String.Format("\\u{0:x4} ", cint).Trim());
        }

        return asAscii.ToString();
    }
}
public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog { Title = "Akaryakıt Ürünlerine Uygulanacak ÖTV Tutarlarının Güncellenmesi Hk." });
            context.SaveChanges();
        }

        using (var context = new SomeDbContext())
        {
            // Works:
            var searchValue = "uygulanacak";
            Console.WriteLine(context.Blogs.AsEnumerable().Where(e => e.Title.ToLowerAscii().Contains(searchValue.ToLowerAscii())).FirstOrDefault()?.Title ?? "Not found.");
            // Doesn't work:
            searchValue = "akaryakıt ürünlerine uygulanacak";
            Console.WriteLine(context.Blogs.AsEnumerable().Where(e => e.Title.ToLowerAscii().Contains(searchValue.ToLowerAscii())).FirstOrDefault()?.Title ?? "Not found.");
            Console.ReadKey();
        }
    }
}
 

```

**Comment by ajcvickers** [comment] 2022-03-03 20:01
@suatsuphi What are you trying to achieve? Writing C# code isn't going to change the way the SQLite database works.

**Comment by suatsuphi** [comment] 2022-03-06 14:44
I guess I have to get all database with AsEnumerable() then after can searching.  thanks.

`data.AsEnumerable().Where(i => i.Title.ToLower().Contains(searchValue.ToLower()))`

**Comment by roji** [comment] 2022-03-06 20:36
@suatsuphi you probably want to have a look at our [collations and case sensitivity doc page](https://docs.microsoft.com/en-us/ef/core/miscellaneous/collations-and-case-sensitivity): doing a case-insensitive match by using ToLower is generally not a good idea in databases, as it prevents index use. Consider defining a case-insensitive collation on the column instead.

**Comment by ajcvickers** [comment] 2022-03-07 10:38
@bricelam mentioned in triage that a user-defined function in SQLite might be used to do this. Closing form the EF side, since there is no work to be done here.

**Comment by bricelam** [comment] 2022-04-12 19:24
```cs
var connection = (SqliteConnection)context.Database.GetDbConnection();

// Override with .NET implementation
connection.CreateFunction("lower", (string x) => x.ToLower(), isDeterministic: true);
```

**Closed** 2022-10-16 20:25 UTC
Labels: closed-external, customer-reported
