### ISSUE TITLE
Find on Cosmos throws CosmosException when entity isn't found

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#24184] opened 2021-02-18 09:57 UTC
When invoking DbSet.Find with an ID that doesn't exist, the Cosmos provider throws the following exception instead of returning null.

<details>
<summary>Exception details</summary>

```
      An exception occurred while iterating over the results of a query for context type 'BlogContext'.
      Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: 69e4f10f-6ea3-4d0a-b49a-48629ed1831d; Reaso
n: ({
        "Errors": [
          "Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found"
        ]
      });
         at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal.CosmosClientWrapper.JObjectFromReadItemResponseMessage(ResponseMessage responseMessage)
         at Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal.CosmosClientWrapper.ExecuteReadItem(String containerId, String partitionKey, String resourceId)
         at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable`1.Enumerator.MoveNext()
      --- Cosmos Diagnostics ---{"DiagnosticVersion":"2","Summary":{"StartUtc":"2021-02-18T09:55:26.4161204Z","TotalElapsedTimeInMs":91.4889,"UserAgent":"cosmos-netstandard-sdk/3.1
2.0|3.11.4|01|X64|Microsoft Windows 10.0.19042|.NET Core 3.1.12| Microsoft.EntityFrameworkCore.Cosmos/5.0.0","TotalRequestCount":1,"FailedRequestCount":1},"Context":[{"Id":"GetNone
PkValue","ElapsedTimeInMs":45.7317},{"Id":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","HandlerElapsedTimeInMs":43.5706},{"Id":"Microsoft.Azure.Cosmos.Handlers.RetryHandler
","HandlerElapsedTimeInMs":43.5604},{"Id":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","HandlerElapsedTimeInMs":43.4719},{"Id":"Microsoft.Azure.Cosmos.Handlers.TransportHandler"
,"HandlerElapsedTimeInMs":5.4484},{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[],"RegionsContacted":["https://127.0.0.1:8081/"],"FailedReplicas":[]},{"Id":"Mi
crosoft.Azure.Documents.ServerStoreModel","ElapsedTimeInMs":43.2445},{"Id":"AddressResolutionStatistics","StartTimeUtc":"2021-02-18T09:55:26.4907179Z","EndTimeUtc":"2021-02-18T09:5
5:26.4922515Z","ElapsedTimeInMs":1.5336,"TargetEndpoint":"https://127.0.0.1:8081//addresses/?$resolveFor=dbs%2f9fRlAA%3d%3d%2fcolls%2f9fRlAMUmzmM%3d%2fdocs&$filter=protocol eq rntb
d&$partitionKeyRangeIds=0"},{"Id":"StoreResponseStatistics","StartTimeUtc":"2021-02-18T09:55:26.4636472Z","ResponseTimeUtc":"2021-02-18T09:55:26.5022894Z","ElapsedTimeInMs":38.6422
,"ResourceType":"Document","OperationType":"Read","LocationEndpoint":"https://127.0.0.1:8081/","ActivityId":"69e4f10f-6ea3-4d0a-b49a-48629ed1831d","StoreResult":"StorePhysicalAddre
ss: rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer8/partitions/a4cb4954-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 56, GlobalCommittedLsn: -1, PartitionKeyRangeId:
0, IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#56, UsingLocalLSN: True, TransportException: null"}]}
      Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: 69e4f10f-6ea3-4d0a-b49a-48629ed1831d; Reaso
n: ({
        "Errors": [
          "Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found"
        ]
      });
         at Microsoft.Azure.Cosmos.RespUnhandled exception. onseMessage.EnsureSuccessStatusCode()
         at Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal.CosmosClientWrapper.JObjectFromReadItemResponseMessage(ResponseMessage responseMessage)
         at Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal.CosmosClientWrapper.ExecuteReadItem(String containerId, String partitionKey, String resourceId)
         at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable`1.Enumerator.MoveNext()
      --- Cosmos Diagnostics ---{"DiagnosticVersion":"2","Summary":{"StartUtc":"2021-02-18T09:55:26.4161204Z","TotalElapsedTimeInMs":91.4889,"UserAgent":"cosmos-netstandard-sdk/3.1
2.0|3.11.4|01|X64|Microsoft Windows 10.0.19042|.NET Core 3.1.12| Microsoft.EntityFrameworkCore.Cosmos/5.0.0","TotalRequestCount":1,"FailedRequestCount":1},"Context":[{"Id":"GetNone
PkValue","ElapsedTimeInMs":45.7317},{"Id":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","HandlerElapsedTimeInMs":43.5706},{"Id":"Microsoft.Azure.Cosmos.Handlers.RetryHandler
","HandlerElapsedTimeInMs":43.5604},{"Id":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","HandlerElapsedTimeInMs":43.4719},{"Id":"Microsoft.Azure.Cosmos.Handlers.TransportHandler"
,"HandlerElapsedTimeInMs":5.4484},{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[],"RegionsContacted":["https://127.0.0.1:8081/"],"FailedReplicas":[]},{"Id":"Mi
crosoft.Azure.Documents.ServerStoreModel","ElapsedTimeInMs":43.2445},{"Id":"AddressResolutionStatistics","StartTimeUtc":"2021-02-18T09:55:26.4907179Z","EndTimeUtc":"2021-02-18T09:5
5:26.4922515Z","ElapsedTimeInMs":1.5336,"TargetEndpoint":"https://127.0.0.1:8081//addresses/?$resolveFor=dbs%2f9fRlAA%3d%3d%2fcolls%2f9fRlAMUmzmM%3d%2fdocs&$filter=protocol eq rntb
d&$partitionKeyRangeIds=0"},{"Id":"StoreResponseStatistics","StartTimeUtc":"2021-02-18T09:55:26.4636472Z","ResponseTimeUtc":"2021-02-18T09:55:26.5022894Z","ElapsedTimeInMs":38.6422
,"ResourceType":"Document","OperationType":"Read","LocationEndpoint":"https://127.0.0.1:8081/","ActivityId":"69e4f10f-6ea3-4d0a-b49a-48629ed1831d","StoreResult":"StorePhysicalAddre
ss: rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer8/partitions/a4cb4954-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 56, GlobalCommittedLsn: -1, PartitionKeyRangeId:
0, IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#56, UsingLocalLSN: True, TransportException: null"}]}
Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: 69e4f10f-6ea3-4d0a-b49a-48629ed1831d; Reason: ({
  "Errors": [
    "Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found"
  ]
});
   at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal.CosmosClientWrapper.JObjectFromReadItemResponseMessage(ResponseMessage responseMessage)
   at Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal.CosmosClientWrapper.ExecuteReadItem(String containerId, String partitionKey, String resourceId)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Find(Object[] keyValues)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Find(Object[] keyValues)
   at <Program>$.<<Main>$>d__0.MoveNext() in C:\projects\test\Program.cs:line 13
--- End of stack trace from previous location where exception was thrown ---
   at <Program>$.<<Main>$>d__0.MoveNext() in C:\projects\test\Program.cs:line 13
--- End of stack trace from previous location where exception was thrown ---
   at <Program>$.<Main>(String[] args)
--- Cosmos Diagnostics ---{"DiagnosticVersion":"2","Summary":{"StartUtc":"2021-02-18T09:55:26.4161204Z","TotalElapsedTimeInMs":91.4889,"UserAgent":"cosmos-netstandard-sdk/3.12.0|3.
11.4|01|X64|Microsoft Windows 10.0.19042|.NET Core 3.1.12| Microsoft.EntityFrameworkCore.Cosmos/5.0.0","TotalRequestCount":1,"FailedRequestCount":1},"Context":[{"Id":"GetNonePkValu
e","ElapsedTimeInMs":45.7317},{"Id":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","HandlerElapsedTimeInMs":43.5706},{"Id":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","Han
dlerElapsedTimeInMs":43.5604},{"Id":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","HandlerElapsedTimeInMs":43.4719},{"Id":"Microsoft.Azure.Cosmos.Handlers.TransportHandler","Hand
lerElapsedTimeInMs":5.4484},{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[],"RegionsContacted":["https://127.0.0.1:8081/"],"FailedReplicas":[]},{"Id":"Microsof
t.Azure.Documents.ServerStoreModel","ElapsedTimeInMs":43.2445},{"Id":"AddressResolutionStatistics","StartTimeUtc":"2021-02-18T09:55:26.4907179Z","EndTimeUtc":"2021-02-18T09:55:26.4
922515Z","ElapsedTimeInMs":1.5336,"TargetEndpoint":"https://127.0.0.1:8081//addresses/?$resolveFor=dbs%2f9fRlAA%3d%3d%2fcolls%2f9fRlAMUmzmM%3d%2fdocs&$filter=protocol eq rntbd&$par
titionKeyRangeIds=0"},{"Id":"StoreResponseStatistics","StartTimeUtc":"2021-02-18T09:55:26.4636472Z","ResponseTimeUtc":"2021-02-18T09:55:26.5022894Z","ElapsedTimeInMs":38.6422,"Reso
urceType":"Document","OperationType":"Read","LocationEndpoint":"https://127.0.0.1:8081/","ActivityId":"69e4f10f-6ea3-4d0a-b49a-48629ed1831d","StoreResult":"StorePhysicalAddress: rn
tbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer8/partitions/a4cb4954-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 56, GlobalCommittedLsn: -1, PartitionKeyRangeId: 0, IsV
alid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#56, UsingLocalLSN: True, TransportException: null"}]}
```

</details>

**Comment by AndriySvyryd** [comment] 2021-08-19 01:10
Duplicate of https://github.com/dotnet/efcore/issues/25115

**Closed** 2022-10-16 19:24 UTC
