### ISSUE TITLE
RevEng: Sqlite : Relative path for database file does not work

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#5288] opened 2016-05-07 00:07 UTC
Repro steps
Create csproj based solution console app/class library
Install EFCore.Tools/SQLite/SQLite.Design packages

```
PM> pwd

Path                                                                
----                                                                
C:\Users\smpatel\Documents\Visual Studio 2015\Projects\ClassLibrary2


PM> ls *.db


    Directory: C:\Users\smpatel\Documents\Visual Studio 2015\Projects\ClassLibrary2


Mode                LastWriteTime         Length Name                                                                                                                                                               
----                -------------         ------ ----                                                                                                                                                               
-a----        3/23/2016   4:06 PM         691200 northwind.db                                                                                                                                                       


PM> Scaffold-DbContext "Data Source=.\northwind.db" Microsoft.EntityFrameworkCore.Sqlite
Scaffold-DbContext : No coercion operator is defined between types 'System.String' and 'System.Char'.
At line:1 char:1
+ Scaffold-DbContext "Data Source=.\northwind.db" Microsoft.EntityFrame ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Scaffold-DbContext], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Scaffold-DbContext
```

The db file resides in project root directory. The scaffolding command is invoked from the same directory. The filename in connection string is provided with relative path.
1. We should handle relative paths better, at least in the context of project directory.
2. If the db file is not found then we should throw exception that file is not found. Exception msg here is very confusing.

Current work-around - Use absolute path.

**Comment by lajones** [comment] 2016-05-21 00:29
This is happening because at https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFramework.psm1#L854 we set the current directory to be the project's target directory before we pass control to the `OperationExecutor`. Note: if you turn on the `-Verbose` flag it will tell you what current directory it's using. In this case the "current directory" is the `...\bin\Debug` directory. If you arrange for `northwind.db` to end up in the `...\bin\Debug` directory then everything works as expected. 

Now this does not agree with what you see if you type `pwd` because that is the current directory before the tool is run. @rowanmiller @divega any comments on what the expectations should be for the current directory?

**Comment by bricelam** [comment] 2016-05-23 16:01
If your `project.json` includes the following...
```JSON
{
  "copyToOutput": {
    "include": "**/*.db"
  }
}
```
...or you select **Copy to Output Directory: Copy if newer** (like you should for an existing, app-local database). Things will work as expected.

**Comment by rowanmiller** [comment] 2016-05-23 23:20
Yep I agree this is by design. That is the same result you would get if you used that connection string on your app.

**Comment by lajones** [comment] 2016-05-25 20:39
Closing as by design.

**Comment by divega** [comment] 2016-05-25 22:32
I must be missing one or more things. 

The exception really says "No coercion operator is defined between types 'System.String' and 'System.Char'" and that is by design?

Also, I sort of get why you have to do the copy to output directory stuff, but how are customers supposed to figure that out?

**Comment by divega** [comment] 2016-05-28 00:56
Friendly ping on this. Based on the exception message being unhelpful, I don't think we should close this, but I am ok with postponing to 1.0.1. @rowanmiller any thoughts?

**Comment by rowanmiller** [comment] 2016-05-31 16:51
Agreed, I would expect an exception related to not being able to open the database connection. But yes, I think 1.0.1 would be fine too.

**Comment by bricelam** [comment] 2017-03-08 18:59
FYI, @smitpatel's original expectations will be met after #7588.

**Closed** 2022-10-16 09:39 UTC
Labels: type-bug, closed-out-of-scope
