### ISSUE TITLE
Query: compilation error (query source already associated with an expression) for query with groupby and let with order by

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12815] opened 2018-07-26 19:40 UTC
query:

```cs
from od in ctx.OrderDetails
let customer = od.Order.CustomerID.OrderBy(ee => ee)
group od by customer
into odg
select odg;
```

exception:
```
Query source (from Char ee in [od].Order.CustomerID) has already been associated with an expression.
	at Remotion.Linq.Clauses.QuerySourceMapping.AddMapping(IQuerySource querySource, Expression expression)
	at Remotion.Linq.Clauses.MainFromClause.Clone(CloneContext cloneContext)
	at Remotion.Linq.QueryModel.Clone(QuerySourceMapping querySourceMapping)
	at Remotion.Linq.QueryModel.CloningExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
	at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at Remotion.Linq.Clauses.ResultOperators.GroupResultOperator.TransformExpressions(Func`2 transformation)
	at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
	at Remotion.Linq.QueryModel.Clone(QuerySourceMapping querySourceMapping)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryOptimizer.FlattenSubQuery(SubQueryExpression subQueryExpression, IFromClause fromClause, QueryModel queryModel, Int32 destinationIndex)
	at Remotion.Linq.Transformations.SubQueryFromClauseFlattener.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
	at Remotion.Linq.Clauses.MainFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
	at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryOptimizer.Optimize(QueryCompilationContext queryCompilationContext, QueryModel queryModel)
	at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
	at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
	at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
	at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
	at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
	at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
	at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
	at Remotion.Linq.QueryableBase`1.GetEnumerator()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	at Microsoft.EntityFrameworkCore.Query.QueryNavigationsTestBase`1.Let_group_by_nav_prop(Boolean isAsync)
```

**Comment by ajcvickers** [comment] 2018-07-30 18:38
Let's will fix it.

**Comment by smitpatel** [comment] 2019-11-21 02:08
Duplicate of #17068

**Closed** 2022-10-16 13:22 UTC
Labels: closed-duplicate, punted-for-3.0, area-query
