### ISSUE TITLE
FirstOrDefault()

### ISSUE THREAD

**Issue by muratcanoguzhan** [dotnet/efcore#19506] opened 2020-01-07 10:21 UTC
Why I can't take one or multiple items of grouped data ? Example;

```
private static void Main()
{
    using var context = new Context();

    context.Database.EnsureDeleted();
    context.Database.EnsureCreated();

    var groups = context.IceCreams
        .GroupBy(i => i.Popularity)
        .Select(g => new { Popularity = g.Key, Count = g.Count() , g.FirstOrDefault(), g.Take(2)})
        .OrderByDescending(e => e.Popularity)
        .ToList();

    Debug.Assert(groups.Count == 3);
    Debug.Assert(groups[0].Count == 2);
}
```

These 'g.FirstOrDefault() ,g.LastOrDefault(), g.Take(2)' can be added to sql query easily like top 1.
I couldn't take also al groupedItems near the key.

_Originally posted by @domainmurat in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/934#issuecomment-571188870_

I just want to take last popularity, situation or another thing of objects.

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment] 2020-01-07 18:19
> These 'g.FirstOrDefault() ,g.LastOrDefault(), g.Take(2)' can be added to sql query easily like top 1.
I couldn't take also al groupedItems near the key.

They cannot. It is not SQL Group By query. Further you are taking first of each group, not first of a SQL query.

Duplicate of #13805

**Closed** 2022-10-16 18:04 UTC
Labels: customer-reported
