### ISSUE TITLE
Query: Recursive union and join

### ISSUE THREAD

**Issue by helderboone** [dotnet/efcore#8887] opened 2017-06-18 00:40 UTC
I have a database with Apis and SubApis (childs).
I wrote a query in order to retrive all subApis of subApis.

 var query = @"

                        with GetSubApisRecursive as (
                        select a.* from Api a
                        where a.Id = @id
                        union all
                        select s.* from Api s
                        join GetSubApisRecursive r on s.ParentApiId = r.Id)
                         select Id as Id, * from GetSubApisRecursive 
                        ";
                var subApis = db.Apis.FromSql(query, new SqlParameter("id", message.Id)).ToList();

I got this error message: InvalidOperationException: Sequence contains more than one matching element.

**Comment by anpete** [comment] 2017-06-18 23:45
@helderboone Please post the complete stack track of the exception.

**Comment by anpete** [comment] 2017-06-18 23:50
@helderboone Can you also try expanding the '*' in the projection into individual named columns?

**Comment by ajcvickers** [comment] 2017-06-26 17:52
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:08 UTC
Labels: closed-could-not-reproduce
