### ISSUE TITLE
Package manager frozen and unable to stop

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#29465] opened 2022-11-01 09:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Package-manager-frozen-and-unable-to-sto/10177976)._

---
Package manager console frozen after command: Scaffold-DbContext -Connection "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=Account.mdb;Persist Security Info=True;Jet OLEDB:Database Password=..." -Provider EntityFrameworkCore.Jet

Clicking the stop icon doesn't work.

---
#### Feedback Bot on 10/21/2022, 03:53 AM: 

(private comment, text removed)
#### Nikolche Kolev [MSFT] on 10/21/2022, 10:56 PM: 

(private comment, text removed)
#### Hrvoje Grabušić on 10/22/2022, 11:01 AM: 

(private comment, text removed)
#### Feedback Bot on 10/27/2022, 07:26 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by hrvoje-grabusic** [comment] 2022-11-01 10:43
It says "The provider is .NET Standard 2.0 compatible" and it appears to be working.
I can fetch data.

**Comment by ErikEJ** [comment] 2022-11-01 10:57
I think you have been lucky then: https://www.nuget.org/packages/EntityFrameworkCore.Jet/3.1.1#dependencies-body-tab

**Comment by ajcvickers** [comment] 2022-11-02 11:39
@hrvoje-grabusic EF Core database providers are coupled to the version of EF Core that they are written for. A provider that targets EF Core 5.0 should not be expected to work with EF Core 6.0. Regardless of this, it looks like the problem is in the provider, so please contact the provider author for further assistance.

**Comment by hrvoje-grabusic** [comment] 2022-11-02 12:14
Ok.

I see now that visual studio problems are caused by my installing incompatible nuget packages.
You can close this issue.

I created a new .NET 461 project and will use OleDBConnenction. This will do for my project.

I didn't create this EF issue i reported on visual studio console hanging and not being able to stop the command process via the stop button in the console.

I wish the nuget manager wouldn't show me incompatible packages and that VS would handle that situation a bit better but that is not an EF issue.

**Closed** 2022-11-02 12:36 UTC
