### ISSUE TITLE
Error when applying migrations on database exception page

### ISSUE THREAD

**Issue by phenning** [dotnet/efcore#4870] opened 2016-03-21 18:09 UTC
When clicking the Apply Migrations button, I get the following error:

 **An error occurred applying migrations, try applying them from the command line**

You can also apply migrations from the command line:

> dotnet ef database update

When trying to manually run the above command:

C:\dd\samples\WebApplication3\src\WebApplication3>dotnet ef database update
System.DllNotFoundException: Unable to load DLL 'sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Data.SqlClient.SNINativeMethodWrapper.UnmanagedIsTokenRestricted(IntPtr token, Boolean& isRestricted)
   at System.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr token)
   at System.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
   at System.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Commands.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Commands.Program.Main(String[] args)
Unable to load DLL 'sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by divega** [comment] 2016-03-30 20:04
The database error page issue is already tracked as #4742. 

@bricelam is working on making commands functional again but not sure if this "System.DllNotFoundException: Unable to load DLL 'sni.dll': The specified module could not be found. " is one of the problems we are tracking.

**Comment by rustd** [comment] 2016-03-30 20:38
@divega can we please track this as part of RC2.

**Comment by divega** [comment] 2016-03-30 20:40
@rustd #4742 (which you filed :smile:) is already tracked for RC2. 

I will close this one as a dupe after confirming with @bricelam that the exception on the command is something that we know about.

**Comment by rustd** [comment] 2016-03-30 20:43
Thanks! I wasn't sure this specific issue unique

**Comment by divega** [comment] 2016-03-30 20:45
Confirmed with @bricelam that the inability to find sni.dll is likely another symptom of how commands are broken right now. That is tracked in #3925. 

So closing as dupe.

**Closed** 2022-10-16 09:34 UTC
