### ISSUE TITLE
Included entities in complex projections are not loaded

### ISSUE THREAD

**Issue by abbradar** [dotnet/efcore#9609] opened 2017-08-28 21:06 UTC
When a complex projection (in `GroupJoin` in my example but may be in other cases) is used, `Include()` requests are silently ignored.

```
Exception message:
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
```

### Steps to reproduce

See https://github.com/abbradar/efcore-bug. When you uncomment [this line](https://github.com/abbradar/efcore-bug/blob/master/src/Program.cs#L34) instead it works, which means that for simple `ToList()` loading is working.

### Further technical details
EF Core version: 2.0.0
Database Provider: `Npgsql.EntityFrameworkCore.PostgreSQL`
Operating system: `Ubuntu 17.04`

**Comment by smitpatel** [comment] 2017-08-29 19:12
@abbradar - Can you post whole stack trace?
I ran your code on Windows machine with SqlServer and it worked correctly for me. This could be either issue in PostgreSQL or something specific happening on Ubuntu machine.

**Comment by abbradar** [comment] 2017-08-30 13:49
@smitpatel I cannot right now but basically [this line](https://github.com/abbradar/efcore-bug/blob/master/src/Program.cs#L39) fails because `Field` is null.

**Comment by smitpatel** [comment] 2017-08-30 15:53
Can you enable Logging at Trace level and post output of that? That would help us understand what is the exact query being evaluated and why Include is not working.

cc: @roji - If this is something known issue with PostgreSQL since SqlServer is working correctly.

**Comment by ajcvickers** [comment] 2017-09-06 18:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:18 UTC
Labels: closed-could-not-reproduce
