### ISSUE TITLE
EF Core doesn't generate OnDelete correctly

### ISSUE THREAD

**Issue by loob91** [dotnet/efcore#20981] opened 2020-05-18 14:45 UTC
In DB First schema, EF Core doesn't create delete constraint in good way. When I try to delete, I have this issue :

> The DELETE statement conflicted with the REFERENCE constraint "FK_eav_custom_values_textfield20_eav_custom_attributes". The conflict occurred in database "KHUB_DB", table "dbo.eav_custom_values_textfield20",  column 'attribute_id'.
The statement has been terminated.

This message is when I try to delete on object on my parent class with children and grand children object in it.

Here my different classes : 

Parent class : 

```
public partial class eav_custom_attributes
    {
        public eav_custom_attributes()
        {
            eav_custom_values_keyattribute_ = new HashSet<eav_custom_values_key>();
        }

        public int id { get; set; }
        public string code { get; set; }
		
        public virtual ICollection<eav_custom_values_key> eav_custom_values_keyattribute_ { get; set; }
    }
```

Children class : 

```
public eav_custom_values_key()
{
	public int id { get; set; }
	public int attribute_id { get; set; }

	public virtual eav_custom_attributes attribute_ { get; set; }
public virtual ICollection<eav_custom_values_textfield20> eav_custom_values_textfield20 { get; set; }
}
```

Grand children class : 

```
public partial class eav_product_values_textfield20
{
	public int attribute_id { get; set; }
	public int key_id { get; set; }
	public string value { get; set; }
	public string value_reverse { get; set; }

	public virtual eav_custom_attributes attribute_ { get; set; }
	public virtual eav_product_values_key key_ { get; set; }
}
```

In my SQL Server, I have created constraints as follow : 
- FK_eav_custom_values_key_eav_custom_attributes, a constraint between eav_custom_attributes.id and eav_custom_values_key.attribute_id **on delete cascade** action.
- FK_eav_custom_values_textfield20_eav_custom_values_key, a constraint between eav_custom_values_key.id and eav_product_values_textfield20.key_id **on delete cascade** action.
- FK_eav_custom_values_textfield20_eav_custom_attributes a constraint between eav_custom_attributes.id and eav_product_values_textfield20.attribute_id with **no action on delete**.

You can see below the code that EF Core generated : 

```
modelBuilder.Entity<eav_custom_attributes>(entity =>
{
	entity.HasIndex(e => new { e.entity_id, e.code })
		.HasName("attributes_entityid_code_unique_index")
		.IsUnique();
});

modelBuilder.Entity<eav_custom_values_key>(entity =>
{
	entity.Property(e => e.value)
		.IsRequired()
		.HasMaxLength(255);
					
	entity.HasOne(d => d.attribute_)
		.WithMany(p => p.eav_custom_values_keyattribute_)
		.HasForeignKey(d => d.attribute_id)
		.HasConstraintName("FK_eav_custom_values_key_eav_custom_attributes");
});
			
modelBuilder.Entity<eav_custom_values_textfield20>(entity =>
{
	entity.HasOne(d => d.attribute_)
		.WithMany(p => p.eav_custom_values_textfield20)
		.HasForeignKey(d => d.attribute_id)
		.OnDelete(DeleteBehavior.ClientSetNull)
		.HasConstraintName("FK_eav_custom_values_textfield20_eav_custom_attributes");

	entity.HasOne(d => d.key_)
		.WithMany(p => p.eav_custom_values_textfield20)
		.HasForeignKey(d => d.key_id)
		.HasConstraintName("FK_eav_custom_values_textfield20_eav_custom_values_key");
});
```

My on delete cascade constraints between eav_custom_attributes and eav_custom_values_key and between eav_custom_values_key and eav_custom_values_textfield20 become a clientSetNull constraint between eav_custom_attributes and eav_custom_values_textfield20, that just doesn't make any sense for me.

EF Core version: 3.1.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1.4
Operating system: Windows 10
IDE: Visual Studio 2019 16.5.5

**Comment by ajcvickers** [comment] 2020-05-18 16:33
@loob91 Please post the schema of the database that you are reverse engineering from.

**Comment by loob91** [comment] 2020-05-19 06:26
> 
> 
> @loob91 Please post the schema of the database that you are reverse engineering from.

No problem, this is it : 

Parent table : 
```
CREATE TABLE [dbo].[eav_custom_attributes](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[code] [nvarchar](50) NOT NULL
 CONSTRAINT [PK_eav_custom_attributes] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
```

Children table : 

```
CREATE TABLE [dbo].[eav_custom_values_key](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[attribute_id] [int] NOT NULL,
	[value] [nvarchar](255) NOT NULL,
	[value_reverse]  AS (reverse([value])) PERSISTED
 CONSTRAINT [PK_eav_custom_values_key] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[eav_custom_values_key]  WITH CHECK ADD  CONSTRAINT [FK_eav_custom_values_key_eav_custom_attributes] FOREIGN KEY([attribute_id])
REFERENCES [dbo].[eav_custom_attributes] ([id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[eav_custom_values_key] CHECK CONSTRAINT [FK_eav_custom_values_key_eav_custom_attributes]
GO

ALTER TABLE [dbo].[eav_custom_values_key]  WITH CHECK ADD  CONSTRAINT [FK_eav_custom_values_key_eav_custom_attributes1] FOREIGN KEY([variant_axe_1])
REFERENCES [dbo].[eav_custom_attributes] ([id])
GO
```

Grand children table : 

```
CREATE TABLE [dbo].[eav_custom_values_textfield20](
	[attribute_id] [int] NOT NULL,
	[key_id] [int] NOT NULL,
	[value] [nvarchar](20) NULL,
	[value_reverse]  AS (reverse([value])) PERSISTED,
 CONSTRAINT [PK_eav_custom_values_textfield20] PRIMARY KEY CLUSTERED 
(
	[attribute_id] ASC,
	[key_id] ASC,
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[eav_custom_values_textfield20]  WITH CHECK ADD  CONSTRAINT [FK_eav_custom_values_textfield20_eav_custom_attributes] FOREIGN KEY([attribute_id])
REFERENCES [dbo].[eav_custom_attributes] ([id])
GO

ALTER TABLE [dbo].[eav_custom_values_textfield20] CHECK CONSTRAINT [FK_eav_custom_values_textfield20_eav_custom_attributes]
GO

ALTER TABLE [dbo].[eav_custom_values_textfield20]  WITH CHECK ADD  CONSTRAINT [FK_eav_custom_values_textfield20_eav_custom_values_key] FOREIGN KEY([key_id])
REFERENCES [dbo].[eav_custom_values_key] ([id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[eav_custom_values_textfield20] CHECK CONSTRAINT [FK_eav_custom_values_textfield20_eav_custom_values_key]
GO
```

Thank you very much !

**Comment by ajcvickers** [comment] 2020-05-19 22:45
@loob91 I get `Foreign key 'FK_eav_custom_values_key_eav_custom_attributes1' references invalid column 'variant_axe_1' in referencing table 'eav_custom_values_key'` when attempting to create that schema.

**Comment by ajcvickers** [comment] 2020-06-01 16:40
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:25 UTC
Labels: closed-could-not-reproduce, customer-reported
