### ISSUE TITLE
behavioral option to auto include / load navigation properties, like owned entities behavior.

### ISSUE THREAD

**Issue by mhDuke** [dotnet/efcore#19301] opened 2019-12-13 06:47 UTC
Say we have `Trip` and `Ticket` types. Business logic requires `Trip.Tickets` to always be included when querying `Trip`. Conveniently designed collection of `Ticket` to be owned by `Trip`. Now, another entity requires reference to `Ticket`, which means use `HasMany()` instead of `OwnsMany()`, in turn lose the auto load for `Trip.Tickets`, going through code refactor to add `.Include()`. Adding logic to `Trip` to not initialize `Tickets` by default, so it throws and help me with forgotten .`Include()`.

it's not dramatic as i am trying to convey here, but it could be. and it's nice thing to have optional setting to auto include navigation properties.

**Comment by smitpatel** [comment] 2019-12-13 09:07
Duplicate of #2953

**Closed** 2022-10-16 18:01 UTC
Labels: customer-reported
