### ISSUE TITLE
Review Test Coverage

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#17618] opened 2019-09-04 19:43 UTC
We should analyze our test coverage to identify any major uncovered areas.

**Comment by bricelam** [comment] 2019-10-10 23:00
Areas missing automated coverage:
- Core
  - Conventions APIs (possibly just inlined)
- Relational
  - Connection resiliency
- SQL Server
  - Full text search
  - SqlServerDbFunctionsExtensions (client-side)
  - SqlServerUdtTypeMapping
- SQLite
  - Spatial
    - Custom SRIDs
    - Custom Dimensions #13767
- Design
  - MigrationsScaffolder
  - RevEng
    - Spatial
- Tools

**Comment by ajcvickers** [comment] 2020-09-17 23:01
Duplicate of #17018

**Closed** 2022-10-16 14:40 UTC
