### ISSUE TITLE
Missing column from Sql Generated

### ISSUE THREAD

**Issue by Manmeetsm** [dotnet/efcore#12934] opened 2018-08-08 15:25 UTC
EF core 2.1.1 is generating incorrect SQL for order by columns.
```c#
await context.IndustryType
  .OrderBy(x => x.Name)
  .Select(x => new LookupValue { Id = x.IndustryTypeId, Text = x.Name, Code = x.Name })
  .ToListAsync();
```
Generates : - 

```Sql
SELECT [e].[IndustryTypeId] AS [Id], [e].[Name] AS [Code] ## Missing Text Alias ##
FROM [IndustryType] AS [e]
ORDER BY [Text] 
```

It should be 

```Sql
SELECT [e].[IndustryTypeId] AS [Id], 
[e].[Name] AS [Text],  # This is Missing #
[e].[Name] AS [Code] 
FROM [IndustryType] AS [e]
ORDER BY [Text] 
```

**Comment by smitpatel** [comment] 2018-08-08 18:05
Duplicate of #12180

**Closed** 2022-10-16 13:24 UTC
Labels: closed-duplicate, customer-reported
