### ISSUE TITLE
Use COUNT with group by and then join causes error

### ISSUE THREAD

**Issue by frankcui95** [dotnet/efcore#20309] opened 2020-03-17 12:09 UTC
SQL translation isn't working as expceted.

Generated SQL:

```sql
SELECT t."HouseId", t.c AS "AccessCount", t1.c AS "CustomerCount"
      FROM (
          SELECT c."HouseId", COUNT(*)::INT AS c
          FROM "CustomerAccessHouse" AS c
          GROUP BY c."HouseId"
      ) AS t
      INNER JOIN (
          SELECT t0."HouseId", t.c
          FROM (
              SELECT c0."HouseId", c0."CustomerId"
              FROM "CustomerAccessHouse" AS c0
              GROUP BY c0."HouseId", c0."CustomerId"
          ) AS t0
          GROUP BY t0."HouseId"
      ) AS t1 ON t."HouseId" = t1."HouseId"
```

at line 8, `t.c` Should be `COUNT(*)::INT AS c`: 

``` sql
SELECT t."HouseId", t.c AS "AccessCount", t1.c AS "CustomerCount"
      FROM (
          SELECT c."HouseId", COUNT(*)::INT AS c
          FROM "CustomerAccessHouse" AS c
          GROUP BY c."HouseId"
      ) AS t
      INNER JOIN (
          SELECT t0."HouseId", COUNT(*)::INT AS c
          FROM (
              SELECT c0."HouseId", c0."CustomerId"
              FROM "CustomerAccessHouse" AS c0
              GROUP BY c0."HouseId", c0."CustomerId"
          ) AS t0
          GROUP BY t0."HouseId"
      ) AS t1 ON t."HouseId" = t1."HouseId"
```

### Steps to reproduce

``` C#

public class CustomerAccessHouse
{
   public Guid Id {get;set;}
   public Guid HouseId {get;set;}
   public Guid CustomerId {get;set;}
}
```

With query A:
``` C#
var a = source.GroupBy(x => x.HouseId)
               .Select(g => new
               {
                   HouseId = g.Key,
                   Count = g.Count(),
               });
```
With query B:
``` C#
var b = source.GroupBy(x => new
            {
                x.HouseId,
                x.CustomerId,
            })
            .Select(g => new
            {
                g.Key.HouseId,
                g.Key.CustomerId,
            })
            .GroupBy(x => x.HouseId)
            .Select(g => new
            {
                HouseId = g.Key,
                Count = g.Count(),
            });
```
Both the queries of a and b works correctly.
For query A, the genelated SQL is:
``` sql
   SELECT c."HouseId", COUNT(*)::INT AS "Count"
      FROM "CustomerAccessHouse" AS c
      GROUP BY c."HouseId"
```
For query B, the genelated SQL is:
``` sql
SELECT t."HouseId", COUNT(*)::INT AS "Count"
      FROM (
          SELECT c."HouseId", c."CustomerId"
          FROM "CustomerAccessHouse" AS c
          GROUP BY c."HouseId", c."CustomerId"
      ) AS t
      GROUP BY t."HouseId"
```
But join them with:
``` C#
var q = from t in a
                    join c in b on t.HouseId equals c.HouseId
                    select new
                    {
                        t.HouseId,
                        AccessCount = t.Count,
                        CustomerCount = c.Count,
                    };
```
An exception occurred while iterating over the results of a query for context type 

`too long, omitted`

  Exception data:
    Severity: ERROR
    SqlState: 42P01
    MessageText: invalid reference to FROM-clause entry for table "t"
    Hint: There is an entry for table "t", but it cannot be referenced from this part of the query.
    Position: 223
    File: parse_relation.c
    Line: 3225
    Routine: errorMissingRTE

### Further technical details

EF Core version: 3.1.2
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET Core 3.1
Operating system: WSL 1 (Ubuntu 18.04), Windows 10.0.18363.719
IDE: Visual Studio Code 1.43.0

**Comment by smitpatel** [comment] 2020-03-17 12:17
Duplicate of #19202

**Comment by MaiReo** [comment] 2020-03-17 12:23
@smitpatel  Oh, sorry for that

**Closed** 2022-10-16 18:16 UTC
Labels: closed-duplicate, customer-reported
