### ISSUE TITLE
How to disable check constraints on migration?

### ISSUE THREAD

**Issue by Changyoun** [dotnet/efcore#20941] opened 2020-05-13 05:38 UTC
I don't want check constraints automatically added on migration.
How to disable check constraints on migration?

Model

```c#
public enum RankGrade
{
    Grade1 = 1,
    Grade2,
    Grade3
}
public class SampleModel
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public RankGrade Grade { get; set; }
}
```

Auto generated migration class

```c#
migrationBuilder.CreateCheckConstraint(
                name: "CK_SampleModel_Grade_Enum_Constraint",
                table: "SampleModel",
                sql: "[Grade] IN(1, 2, 3)");
```

EF Core version: 5.0.0-preview.3.20181.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 Pro
IDE: Visual Studio 2019 16.5.4

**Comment by roji** [comment] 2020-05-13 06:52
@Changyoun we have already removed the enum check constraint convention from EF Core - it is now in a separate plugin. Starting from preview5 EF Core will no longer generate these constraints unless you install the plugin (see #20897).

**Comment by roji** [comment] 2020-05-13 06:53
Duplicate of #20897.

**Comment by roji** [comment] 2020-05-13 06:53
Duplicate of #20897

**Closed** 2022-10-16 18:24 UTC
Labels: closed-duplicate, customer-reported
