### ISSUE TITLE
Cannot access a disposed context instance. 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#29660] opened 2022-11-23 11:00 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-access-a-disposed-context-instanc/10198879)._

---
Hi there, 
I'm trying to access the DB using the EF. 
I can get data using a normal declaration of dbcontext on the Program file using .NET 6. 
But using GRAPHQL to access I get the error below: 
"Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection an"

Then, I've modified the dbcontext declaration on Program.cs filefrom : 

```
builder.Services.AddDbContext(options =>
{
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection"));
}
```

 using a Factory  to: 

```
builder.Services.AddPooledDbContextFactory(
       options =>
           options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));
```

And the repository is like that: 

```
   public class ProjectRepository : IProjectRepository
    {
        //private readonly Context _context;
        private readonly IDbContextFactory _contextFactory;
        public ProjectRepository(IDbContextFactory contextFactory)
        {
            _contextFactory = contextFactory;
            //_context = context;
        }

        public async Task<IEnumerable> GetProjects()
        {
            using (Context _context = _contextFactory.CreateDbContext())
            {
                return _context.Projects;
            }
        }
}
```

Please, let me know if you have any suggestions. 
Thanks.

---
#### Feedback Bot on 11/14/2022, 07:31 AM: 

(private comment, text removed)
#### Alvaro Corral on 11/14/2022, 00:22 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2022-11-23 11:02
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-11-30 20:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-11-30 20:37 UTC
