### ISSUE TITLE
OutOfMemoryException in DbContext ctor, DbSetInitializier.InitializeSets

### ISSUE THREAD

**Issue by john-luke-laue** [dotnet/efcore#14533] opened 2019-01-28 23:01 UTC
Occasionally, I'm getting an out of memory exception from EntityFarmeworkCore on my web app.
It seems to be occurring on instantiation of a DBContext. It doesn't happen consistently.
The error seems to be coming from the constructor of DBContext itself.

Any ideas as to why this is happening or how to either handle or avoid it?

```
Exception message: Exception of type 'System.OutOfMemoryException' was thrown. 
Stack trace:
at System.Collections.Generic.Dictionary`2.Resize(Int32 newSize, Boolean forceNewHashCodes)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Internal.IDbSetCache.GetOrAddSet(IDbSetSource source, Type type)
   at Microsoft.EntityFrameworkCore.Internal.DbSetInitializer.InitializeSets(DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at EspritWeb.Data.EspritContext..ctor(DbContextOptions`1 options, IUserIdProvider userIdProvider)
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at EspritWebMvc.Middleware.AdMiddleware.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EspritWebMvc.Middleware.CustomExceptionHandlerMiddleware.d__6.MoveNext()

```
### Further technical details
EF Core version: 2.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows Server 2012

**Comment by ajcvickers** [comment] 2019-01-29 00:40
@john-luke-laue What does your DbContext class look like?

**Comment by ajcvickers** [comment] 2019-02-04 17:48
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:49 UTC
Labels: closed-could-not-reproduce, customer-reported
