### ISSUE TITLE
Query: string.Concat gives different results than L2O for some types

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#13104] opened 2018-08-24 00:54 UTC
query:

```cs
from g in gs
from m in ms
orderby g.Nickname, m.Id
select new
{
	HasSoulPatch = string.Concat("HasSoulPatch " + g.HasSoulPatch, " HasSoulPatch"),
	Rank = string.Concat("Rank " + g.Rank, " Rank"),
	SquadId = string.Concat("SquadId " + g.SquadId, " SquadId"),
	Rating = string.Concat("Rating " + m.Rating, " Rating"),
	Timeline = string.Concat("Timeline " + m.Timeline, " Timeline")
}
```

result:
```
{ HasSoulPatch = HasSoulPatch 1 HasSoulPatch, Rank = Rank 1 Rank, SquadId = SquadId 1 SquadId, Rating = Rating 2.1 Rating, Timeline = Timeline 0002-01-02 10:00:00.0000000 +01:30 Timeline }
```

l2o:
```
{ HasSoulPatch = HasSoulPatch True HasSoulPatch, Rank = Rank Corporal Rank, SquadId = SquadId 1 SquadId, Rating = Rating 2.1 Rating, Timeline = Timeline 1/2/0002 10:00:00 AM +01:30 Timeline }
```

**Comment by ajcvickers** [comment] 2019-01-25 20:30
Duplicate of #14205

**Closed** 2022-10-16 13:27 UTC
Labels: closed-duplicate
