### ISSUE TITLE
Invalid attempt to call ReadAsync when reader is closed.

### ISSUE THREAD

**Issue by AJB-Sharp** [dotnet/efcore#18039] opened 2019-09-25 08:13 UTC
Hi

I have an application I have been building and upto the release a couple of day ago was working fine but now I get "Invalid attempt to call ReadAsync when reader is closed." whenever I get to a call for the following:

        public async Task<QuoteHeader> GetQuoteHeader(int quoteHeaderId)
        {
            try
            {
                var qh = await _db.QuoteHeader
                    .SingleOrDefaultAsync(q => q.QuoteHeaderId == quoteHeaderId);

                if (qh == null) return null;

                return qh;
            }
            catch (Exception)
            {
                throw;
            }
        }

This is after I have loaded a data set to a table, so the connection to SQL Server seems to be in place.

 I have tried calling this code from my index page and it works fine, but stops working when I call it from the table of data.

[
[QuotationSystem.zip](https://github.com/aspnet/EntityFrameworkCore/files/3651321/QuotationSystem.zip)
](url)

Kind regards

Alan

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment] 2019-09-25 22:07
@AJB-Sharp - I am not seeing any exception like that. I downloaded your project, restored and debugged with ISS Expression, the query runs correctly and returns null result (probably no data). Then it throws in Razor. If there is any EF issue here, can you post more steps what should I do to reproduce it.

**Comment by AJB-Sharp** [comment] 2019-09-26 07:14
Thank you for looking into it. The error appears when it was run in OnParametersSetAsync() (QuoteDetail.razor), I have since tested the code in the OnInitializedAsync() and it works. However, I now have the problem that the foreign key table objects are null when passing the table objects to functions. 

All this was working before release.

I shall raise an issue with the Blazor team as well.

**Comment by smitpatel** [comment] 2019-09-26 20:36
Duplicate of #18070

**Closed** 2022-10-16 14:44 UTC
Labels: closed-duplicate, customer-reported
