### ISSUE TITLE
Microsoft.Data.Sqlite low query performance

### ISSUE THREAD

**Issue by netnr** [dotnet/efcore#27693] opened 2022-03-24 02:35 UTC
```csharp
var vm = new SharedResultVM();
            
var connString = @"Data Source=D:\tmp\log.db";
var sqlTotal = "select count(*) from LoggingModel";
var sqlList = "select * from LoggingModel limit 30 offset 0";

{
    var conn = new System.Data.SQLite.SQLiteConnection(connString);
    conn.Open();
    vm.Log.Add($"{conn.GetType().Assembly.FullName}");

    var cmd = conn.CreateCommand();
    cmd.CommandText = sqlTotal;
    var val = cmd.ExecuteScalar();
    vm.Log.Add($"count: {val},use: {vm.PartTime()}ms");

    cmd.CommandText = sqlList;
    var reader = cmd.ExecuteReader();
    var table = new DataTable();
    table.Load(reader);

    vm.Log.Add($"table: {table.Rows.Count},use: {vm.PartTime()}ms");
}

vm.Log.Add(string.Empty);

{
    var conn = new Microsoft.Data.Sqlite.SqliteConnection(connString);
    conn.Open();
    vm.Log.Add($"{conn.GetType().Assembly.FullName}");

    var cmd = conn.CreateCommand();
    cmd.CommandText = sqlTotal;
    var val = cmd.ExecuteScalar();
    vm.Log.Add($"count: {val},use: {vm.PartTime()}ms");

    cmd.CommandText = sqlList;
    var reader = cmd.ExecuteReader();
    var table = new DataTable();
    table.Load(reader);

    vm.Log.Add($"table: {table.Rows.Count},use: {vm.PartTime()}ms");
}
```

first
```
System.Data.SQLite, Version=1.0.115.5, Culture=neutral, PublicKeyToken=db937bc2d44ff139
count: 183717,use: 100.4683ms
table: 30,use: 365.7634ms

Microsoft.Data.Sqlite, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
count: 183717,use: 81.52740000000006ms
table: 30,use: 553.9189ms
```

after
```
System.Data.SQLite, Version=1.0.115.5, Culture=neutral, PublicKeyToken=db937bc2d44ff139
count: 183717,use: 2.8659ms
table: 30,use: 2.9563ms

Microsoft.Data.Sqlite, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
count: 183717,use: 2.5612000000000004ms
table: 30,use: 562.1699ms
```
---
```
System.Data.SQLite, Version=1.0.115.5, Culture=neutral, PublicKeyToken=db937bc2d44ff139
count: 183717,use: 2.5042ms
table: 30,use: 3.9635ms

Microsoft.Data.Sqlite, Version=6.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
count: 183717,use: 1.7175000000000011ms
table: 30,use: 548.145ms
```

query is too slow

[log.zip](https://github.com/dotnet/efcore/files/8337926/log.zip)

**Comment by roji** [comment] 2022-03-24 09:39
@netnr your benchmark above is problematic in various ways:

* It isn't clear how many times you're running the code, and whether you're doing any warmup loops before measurement. It's very typical for code to run slowly the first time (the JIT needs to do its work, various caches get warmed up), and then run fast.
* It isn't clear how you're timing things (e.g. what is SharedResultVM)
* It's better to test with raw ADO.NET and not involve DataTable, which is an additional layer which could affect results.
* You're running multiple things; that could be OK, but it's always better to concentrate on a single thing first.

In general, when doing benchmarks it's very recommended to use the [BenchmarkDotNet library](https://benchmarkdotnet.org), which takes care of a lof of the complexity and pitfalls around benchmarks (warmups, determining the number of iterations, and many other things.

I put together a quick benchmark comparing Microsoft.Data.Sqlite and System.Data.Sqlite, for reading 30 rows (similar to what you've done), using BenchmarkDotNet. The benchmark shows Microsoft.Data.Sqlite being significantly faster than System.Data.Sqlite; the full results and code are below. I encourage you to copy the code and play with it for your own scenarios. If you do come across a scenario where Microsoft.Data.Sqlite is slower, please post the full benchmark code and results and we can investigate.

|                Method | Rows |      Mean |    Error |   StdDev | Ratio |
|---------------------- |----- |----------:|---------:|---------:|------:|
| Microsoft_Data_Sqlite |   30 |  27.99 us | 0.118 us | 0.105 us |  0.11 |
|    System_Data_Sqlite |   30 | 259.95 us | 1.135 us | 1.006 us |  1.00 |

<details>
<summary>Benchmark code</summary>

```c#
BenchmarkRunner.Run<Benchmarks>();

public class Benchmarks
{
    private const string Path = "/tmp/benchmark.db";

    [Params(30)]
    public int Rows { get; set; }

    [GlobalSetup]
    public void Setup()
    {
        File.Delete(Path);
        using var connection = new SqliteConnection($"Data Source={Path}");
        connection.Open();

        using var command = new SqliteCommand(@"CREATE TABLE data (id INT PRIMARY KEY, text TEXT)", connection);
        command.ExecuteNonQuery();

        command.CommandText = "INSERT INTO data (id, text) VALUES (@id, @text)";
        var idParam = new SqliteParameter { ParameterName = "id" };
        var textParam = new SqliteParameter { ParameterName = "text" };
        command.Parameters.Add(idParam);
        command.Parameters.Add(textParam);

        for (var i = 0; i < Rows; i++)
        {
            idParam.Value = i;
            textParam.Value = "Text " + i;
            command.ExecuteNonQuery();
        }
    }

    [Benchmark]
    public int Microsoft_Data_Sqlite()
    {
        using var connection = new Microsoft.Data.Sqlite.SqliteConnection($"Data Source={Path}");
        connection.Open();
        using var command = new SqliteCommand("SELECT * FROM data", connection);
        using var reader = command.ExecuteReader();

        var sum = 0;
        while (reader.Read())
        {
            sum += reader.GetInt32(0) + reader.GetString(1).Length;
        }

        return sum;
    }

    [Benchmark(Baseline = true)]
    public int System_Data_Sqlite()
    {
        using var connection = new System.Data.SQLite.SQLiteConnection($"Data Source={Path}");
        connection.Open();
        using var command = new SQLiteCommand("SELECT * FROM data", connection);
        using var reader = command.ExecuteReader();

        var sum = 0;
        while (reader.Read())
        {
            sum += reader.GetInt32(0) + reader.GetString(1).Length;
        }

        return sum;
    }
}
```

</details>

**Comment by netnr** [comment] 2022-03-24 10:02
It is indeed DataTable Load(reader) that takes longer 


change code
```
var reader = cmd.ExecuteReader();

string sum = "";
while (reader.Read())
{
    for (int i = 0; i < reader.FieldCount; i++)
    {
        sum += reader.GetString(i);
    }
}

vm.Log.Add($"sum: {sum.Length},use: {vm.PartTime()}ms");
```

result
```
System.Data.SQLite, Version=1.0.115.5, Culture=neutral, PublicKeyToken=db937bc2d44ff139
count: 183717,use: 22.7183ms
table: 30,use: 4.223500000000001ms

Microsoft.Data.Sqlite, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
count: 183717,use: 1.5591000000000008ms
sum: 1903,use: 0.39099999999999824ms
```

**Comment by ajcvickers** [comment] 2022-03-28 11:13
Duplicate of #18884.

**Closed** 2022-10-16 20:29 UTC
Labels: closed-duplicate, customer-reported
