### ISSUE TITLE
HasServiceTier for 3.1.0-preview3.19554.8 not working

### ISSUE THREAD

**Issue by patricknolan** [dotnet/efcore#18966] opened 2019-11-18 06:15 UTC
Hi,

I can set the ServiceTier of my Azure database to Basic with the following code when using the EnsureCreatedAsync method.

            modelBuilder.HasServiceTier("Basic");
            modelBuilder.Model.SetServiceTierSql("'Basic'");

However, when using MigrateAsync the Service tier is not set. What is best practice for doing this when using MigrateAsync?

**Comment by ErikEJ** [comment] 2019-11-18 16:38
Which exact EF Core version?

**Comment by AndriySvyryd** [comment] 2019-11-18 18:54
@patricknolan Can you show the migration that is generated after adding `modelBuilder.HasServiceTier("Basic");`?

**Comment by ajcvickers** [comment] 2019-11-25 17:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:56 UTC
Labels: closed-could-not-reproduce, customer-reported
