### ISSUE TITLE
Feature proposal - [REVENG] Add a default pluralizer implementation

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#17220] opened 2019-08-17 08:12 UTC
@bricelam suggests adding Humanizer as a default pluralizer for Reverse eng. See https://github.com/ErikEJ/EFCorePowerTools/issues/243 - willing to do a PR if there is interest in this?

**Comment by bricelam** [comment] 2019-08-17 20:07
Dupe of #11160

**Comment by ErikEJ** [comment] 2019-08-17 20:30
Should it be an additional NuGet package, like your EF6 pluralizer, @bricelam ?

**Comment by bricelam** [comment] 2019-08-18 01:32
No, I think EFCore. Design can reference Humanizer directly

**Closed** 2022-10-16 14:36 UTC
Labels: closed-duplicate, customer-reported
