### ISSUE TITLE
Calling a function inside a query results after many calls in a memory leak

### ISSUE THREAD

**Issue by Josvds** [dotnet/efcore#13778] opened 2018-10-26 15:31 UTC
Inside the following example I have a function call GetHours to C# code. The tQuery is a EF query.
When running this continuously the memory keeps growing. When removing the GetHours the memory usage stays the same.

`
return (from q in tQuery
		select new ModelX()
		{
			Guid = q.Guid,
			LastRun = q.LastRun,
			LastCompleted = q.LastCompleted,
			Hours = this.GetHours(q.LastCompleted)
		}).ToList();
`

**Comment by smitpatel** [comment] 2018-10-26 17:52
Duplicate of #13048

**Closed** 2022-10-16 13:37 UTC
Labels: closed-duplicate, customer-reported
