### ISSUE TITLE
Complex Query Acting Oddly under VS 2015

### ISSUE THREAD

**Issue by markolbert** [dotnet/efcore#6662] opened 2016-10-02 17:07 UTC
I ran into some odd problems building a query that I was able to work around, but I'd like to understand what went wrong with my original approach.

Essentially, I'm retrieving a bunch of Voter records from a database, optionally filtering on various fields, some of which are in entities related to Voter (e.g., Home, Location, Street). I need to end up with two pieces of data: the total number of records that satisfy the filter conditions, and the current subset/page of Voters.

I started with this:

```
            IQueryable<Voter> voters = _context.Voters
                .AsNoTracking()
                .Include( v => v.County )
                .Include( v => v.Home )
                .ThenInclude( h => h.Location )
                .ThenInclude( l => l.Street )
                .ThenInclude( s => s.City )
                .ThenInclude( c => c.County )
                .Include( v => v.Contacts )
                .Include( v => v.Ballots )
                .ThenInclude( b => b.Election )
                .Include( v => v.VoterAgencies )
                .ThenInclude( va => va.Agency )
                .Where( v =>
                    v.VoterAgencies.Any( va => va.AgencyID == agencyID )
                    && (
                        String.IsNullOrEmpty( model.City )
                        || v.Home.Location.Street.City.Name.IndexOf( model.City, StringComparison.CurrentCultureIgnoreCase ) >= 0
                    )
                    && (
                        String.IsNullOrEmpty( model.FirstName )
                        || v.FirstName.IndexOf( model.FirstName, StringComparison.CurrentCultureIgnoreCase ) >= 0
                    )
                    && (
                        String.IsNullOrEmpty( model.LastName )
                        || v.LastName.IndexOf( model.LastName, StringComparison.CurrentCultureIgnoreCase ) >= 0
                    )
                    && (
                        String.IsNullOrEmpty( model.Street )
                        || v.Home.Location.Street.Name.IndexOf( model.Street, StringComparison.CurrentCultureIgnoreCase ) >= 0
                    )
                    && (
                        model.VoterID == 0
                        || model.VoterID == v.VoterID
                    )
                );

            int numVoters = voters.Count();

            List<VoterModel> voterInfo = voters.OrderBy( v => v.Home.Location.Street.City.Name )
                .ThenBy( v => v.Home.Location.Street.Name )
                .ThenBy( v => v.Home.Location.Number )
                .ThenBy( v => v.Home.Unit )
                .ThenBy( v => v.LastName )
                .ThenBy( v => v.FirstName )
                .ThenBy( v => v.MiddleName )
                .Skip( toSkip )
                .Take( pageSize )
                .ToList();
```

However, this didn't work, apparently due to problems with applying the filter conditions (I suspect EF Core doesn't implement IndexOf for searching in text).

So the next thing I tried involved FromSql, so I could use TSQL's built-in LIKE operator:

```
            string sql = @"select v.* from Voters as v
                inner join Homes as h on v.HomeID = h.ID
                inner join Locations as l on h.LocationID = l.ID
                inner join Streets as s on l.StreetID = s.ID
                inner join Cities as c on s.CityID = c.ID
                inner join VoterAgencies as va on v.CountyID = va.CountyID and v.VoterID = va.VoterID
                where (va.AgencyID = @agencyID)
                    and (c.Name like '%' + @city + '%')
                    and (v.FirstName like '%' + @firstName + '%')
                    and (v.LastName like '%' + @lastName + '%')
                    and (s.Name like '%' + @street + '%')
                    and ((@voterID = 0) or (v.VoterID = @voterID))";

            List<SqlParameter> parameters = new List<SqlParameter>();
            parameters.Add( new SqlParameter( "@agencyID", agencyID ) );
            parameters.Add( new SqlParameter( "@city", model.City ) );
            parameters.Add( new SqlParameter( "@firstName", model.FirstName ) );
            parameters.Add( new SqlParameter( "@lastName", model.LastName ) );
            parameters.Add( new SqlParameter( "@street", model.Street ) );
            parameters.Add( new SqlParameter( "@voterID", model.VoterID ) );

            IQueryable<Voter> rawVoters = _context.Voters
                .AsNoTracking()
                .FromSql( sql, parameters.ToArray() );

            int numVoters = rawVoters.Count();

            IQueryable<Voter> voters = rawVoters
                .AsNoTracking()
                .Include( v => v.County )
                .Include( v => v.Home )
                .ThenInclude( h => h.Location )
                .ThenInclude( l => l.Street )
                .ThenInclude( s => s.City )
                .ThenInclude( c => c.County )
                .Include( v => v.Contacts )
                .Include( v => v.Ballots )
                .ThenInclude( b => b.Election )
                .Include( v => v.VoterAgencies )
                .ThenInclude( va => va.Agency )
                .OrderBy(v=>v.LastName)
                .ThenBy( v => v.FirstName )
                .ThenBy( v => v.MiddleName )
                .ThenBy( v => v.Home.Location.Street.City.Name )
                .ThenBy( v => v.Home.Location.Street.Name )
                .ThenBy( v => v.Home.Location.Number )
                .ThenBy( v => v.Home.Unit )
                .Skip( toSkip )
                .Take( pageSize )
```

But then the weirdness set in: when debugging the code, stepping over the second query -- which should've added the related entities, sorted the result, and extracted the current subset/page of Voters -- it seemed like an exception got thrown that VS 2015 didn't catch. At least, nothing seemed to happen...even after waiting for five minutes (there aren't that many voters in the database, roughly 15,000, and I'm only looking to grab 10 at a time).

What I ultimately ended up doing was this:

```
            string sql = @"select v.* from Voters as v
                inner join Homes as h on v.HomeID = h.ID
                inner join Locations as l on h.LocationID = l.ID
                inner join Streets as s on l.StreetID = s.ID
                inner join Cities as c on s.CityID = c.ID
                inner join VoterAgencies as va on v.CountyID = va.CountyID and v.VoterID = va.VoterID
                where (va.AgencyID = @agencyID)
                    and (c.Name like '%' + @city + '%')
                    and (v.FirstName like '%' + @firstName + '%')
                    and (v.LastName like '%' + @lastName + '%')
                    and (s.Name like '%' + @street + '%')
                    and ((@voterID = 0) or (v.VoterID = @voterID))";

            List<SqlParameter> parameters = new List<SqlParameter>();
            parameters.Add( new SqlParameter( "@agencyID", agencyID ) );
            parameters.Add( new SqlParameter( "@city", model.City ) );
            parameters.Add( new SqlParameter( "@firstName", model.FirstName ) );
            parameters.Add( new SqlParameter( "@lastName", model.LastName ) );
            parameters.Add( new SqlParameter( "@street", model.Street ) );
            parameters.Add( new SqlParameter( "@voterID", model.VoterID ) );

            IQueryable<Voter> rawVoters = _context.Voters
                .AsNoTracking()
                .FromSql( sql, parameters.ToArray() );

            int numVoters = rawVoters.Count();

            parameters = new List<SqlParameter>();
            parameters.Add( new SqlParameter( "@agencyID", agencyID ) );
            parameters.Add( new SqlParameter( "@city", model.City ) );
            parameters.Add( new SqlParameter( "@firstName", model.FirstName ) );
            parameters.Add( new SqlParameter( "@lastName", model.LastName ) );
            parameters.Add( new SqlParameter( "@street", model.Street ) );
            parameters.Add( new SqlParameter( "@voterID", model.VoterID ) );

            List<Voter> voterSubset = _context.Voters
                .AsNoTracking()
                .FromSql( sql, parameters.ToArray() )
                .OrderBy(v=>v.LastName)
                .ThenBy( v => v.FirstName )
                .ThenBy( v => v.MiddleName )
                .ThenBy( v => v.Home.Location.Street.City.Name )
                .ThenBy( v => v.Home.Location.Street.Name )
                .ThenBy( v => v.Home.Location.Number )
                .ThenBy( v => v.Home.Unit )
                .Skip( toSkip )
                .Take( pageSize )
                .ToList();
```

This worked, but, for starters, I don't understand why I had to re-create the SqlParameters collection. If I don't, I get an error about an SqlParameter already being attached to something. But that would seem to imply an SqlParameters collection gets attached to a specific query, and can't be re-used. Which strikes me as odd (I also didn't come across the need to avoid that in my research).

The bigger issue is that, while this approach worked, I had to abandon expanding the second retrieval of Voters to include the related entities (that's why the voterSubset query doesn't have any Includes). Instead, what I do is loop through voterSubset and re-pull each Voter, one by one, from the database, with Include statements applied. 

That works...but I don't understand why I can't just apply the Includes to the definition of voterSubset. It's also not terribly efficient to hit the database that many times, but I can live with that because all this info ultimately lets a user edit individual Voter records, and the human input is slow enough that the extra database hits won't be noticed (the Voter records get retrieved via some angular calls).

Is the problem that my underlying TSQL already defines the joins that the includes would also bring in? Or that by limiting myself to the underlying TSQL only returning the Voter fields I'm preventing the includes from being applied? I did that because otherwise the first query -- the one used to count the total number of Voters -- blows up, with some curious error message about "ID being referenced too many times in v."

Thanx in advance for any insight you can send my way.

**Comment by maumar** [comment] 2016-10-04 23:45
@markolbert could you try your original query but drop the `StringComparison.CurrentCultureIgnoreCase` from the IndexOf? EF supports translation of IndexOf to SQL, but not with this overload. If that doesn't work, could you scope down the query a bit? Also, please provide listing for your DbContext (especially OnModelCreating), and the following entities: Voter, Home, Location, Street.

**Comment by maumar** [comment] 2016-11-12 02:48
sending back to trige as there has been no reply for a long time and I believe the problem should be solved by removing Culture overload

**Comment by rowanmiller** [comment] 2016-11-14 19:03
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 10:37 UTC
