### ISSUE TITLE
Join on OpenJson primitive collections

### ISSUE THREAD

**Issue by erwan-joly** [dotnet/efcore#32407] opened 2023-11-24 22:52 UTC
## Ask a question
Not sure if this is a bug or a misunderstanding on what @roji meant here  https://github.com/dotnet/efcore/issues/13239#issuecomment-1793390415

After upgrading to dotnet 8 we still can't join primitive collection https://github.com/erwan-joly/EFBugRepro
Is it something currently supported ? My understanding is that dotnet 8 is supposed to bring the support for this ? 
https://github.com/dotnet/efcore/issues/13239#issuecomment-1307811685
https://github.com/dotnet/efcore/issues/13239#issuecomment-1793390415

My goal here is to get rid of EntityFramework.MemoryJoin https://github.com/neisbut/EntityFramework.MemoryJoin If the issue here is that the list is not IQueryable is there anyway to tell EF that this list is IQueryable so it convert it to openjson ?

### Include your code

https://github.com/erwan-joly/EFBugRepro

### Include stack traces

```
System.InvalidOperationException: 'The LINQ expression 'DbSet<TestEntity>()
    .Join(
        inner: __p_0, 
        outerKeySelector: t => (object)t.DateTime, 
        innerKeySelector: e => (object)e.DateTime, 
        resultSelector: (t, e) => new TransparentIdentifier<TestEntity, MyClass>(
            Outer = t, 
            Inner = e
        ))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'

```

### Include provider and version information

EF Core version: 8
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer): Microsoft.EntityFrameworkCore.SqlServer and Npgsql
Target framework: (e.g. .NET 6.0): dotnet 8
Operating system: windows 11
IDE: (e.g. Visual Studio 2022 17.4) Visual studio 2022 Version 17.8.0

**Comment by roji** [comment] 2023-11-26 09:45
Duplicate of #31237

**Comment by roji** [comment] 2023-11-26 09:52
@erwan-joly what you're attempting here is a join over a **non-primitive** collection:

```c#
var list = new MyClass[]
{
    new MyClass(),
    new MyClass()
    {
        MyClassId = 2
    }
};

var result = context.TestEntities.Join(list,
    x => x.DateTime,
    x => x.DateTime,
    (x, y) => new { x, y })
    .ToList();
```

That's not yet supported - it's tracked by #31237. That's a highly-voted issue, so hopefully this is something we'll be able to deliver for 9.0.

**Closed** 2023-11-26 21:16 UTC
Labels: customer-reported
