### ISSUE TITLE
Many-to-Many relationship returns infinitely recursive object graph

### ISSUE THREAD

**Issue by bill-richards** [dotnet/efcore#16540] opened 2019-07-10 06:26 UTC
## What the issue is
Querying a many-to-many relationship retrieval returns infinitely recursive object graph.

- The exception is not actually thrown, however it can be seen in the `output` window

```
System.InvalidOperationException: CurrentDepth (1000) is equal to or larger than the maximum allowed depth of 1000. Cannot write the next JSON object or array.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException(String message)
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException(Int32 currentDepth)
   at System.Text.Json.Utf8JsonWriter.WriteStartHelper(ReadOnlySpan`1 utf8PropertyName, Byte token)
   at System.Text.Json.Serialization.WriteStackFrame.WriteObjectOrArrayStart(ClassType classType, JsonEncodedText propertyName, Utf8JsonWriter writer, Boolean writeNull)
   at System.Text.Json.Serialization.WriteStackFrame.WriteObjectOrArrayStart(ClassType classType, Utf8JsonWriter writer, Boolean writeNull)
   at System.Text.Json.Serialization.JsonSerializer.WriteObject(JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.Serialization.JsonSerializer.Write(Utf8JsonWriter writer, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonSerializer.WriteAsyncCore(Object value, Type type, Stream utf8Json, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce
I have included a solution in a zip file [supply-point.zip](https://github.com/aspnet/EntityFrameworkCore/files/3375993/supply-point.zip) 

- Unzip the solution
- Run `npm install` because I've not included the `node_modules`
- Open the solution in the IDE
- Open `BoardGameController.cs` and add a break point to `line 43`
- Run in debug mode
- Register a user and log in 
- From the navigation menu select `Board Games`

### The models
```c#
    public class Artist 
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual ICollection<GameArtist> Games { get; set; } = new List<GameArtist>();
    }

    public class Game
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual ICollection<GameArtist> Artists { get; } = new List<GameArtist>();
    }

    public class GameArtist
    {
        public int GameId { get; set; }
        public virtual Game Game { get; set; }
        public int ArtistId { get; set; }
        public virtual Artist Artist { get; set; }
    }

    public class BoardGameDbContext : DbContext
    {
        public BoardGameDbContext(DbContextOptions<BoardGameDbContext> options) : base(options) {  }

        public DbSet<Artist> Artists { get; set; }
        public DbSet<Game> Games { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GameArtist>(b =>
            {
                b.HasKey(e => new { e.GameId, e.ArtistId  });
                b.HasOne(e => e.Game).WithMany(e => e.Artists).HasForeignKey(e => e.GameId);
                b.HasOne(e => e.Artist).WithMany(e => e.Games).HasForeignKey(e => e.ArtistId);
            });
        }
    }
```
### And the calling code
- NOTE:
  I know that I do not have to do the assignment to a new list object, but I did this so that I can put some breakpoints in the code and see what is going on.

```c#
	var list = new List<Game>();
	try
	{
		list.AddRange(context.Set<Game>()
			.Include(e => e.Artists)
			.ToList());
	}
	catch (Exception ex)
	{
		var message = ex.Message;
	}

	return list;
```

## An alternate approach
I did look at this issue: [https://github.com/aspnet/EntityFrameworkCore/issues/7876](url), however the approach recommended in that issue results in a different problem, where an exception is thrown.

### The modified `DbContext`

```c#
    public class BoardGameDbContext : DbContext
    {
        public BoardGameDbContext(DbContextOptions<BoardGameDbContext> options) : base(options) {  }

        public DbSet<Artist> Artists { get; set; }
        public DbSet<Game> Games { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GameArtist>(b =>
            {
                b.HasKey(e => new { e.GameId, e.ArtistId  });
                b.HasOne(e => e.Game).WithMany(e => e.Artists).HasForeignKey(e => e.GameId);
                b.HasOne(e => e.Artist).WithMany().HasForeignKey(e => e.ArtistId);
            });
        }
    }
```
### New exception
Under the above circumstance, an exception is thrown

```
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: g0.ArtistId1'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
```

### Further technical details
EF Core Version : Microsoft.EntityFrameworkCore.Tools 3.0.0-preview6.19304.10
Database Provider: Microsoft.EntityFrameworkCore.Sqlite 3.0.0-preview6.19304.10
Operating system: Windows 64
IDE: Visual Studio 2019 4.7.03190

**Comment by ajcvickers** [comment] 2019-07-12 15:55
Duplicate of #11564

**Closed** 2022-10-16 14:30 UTC
Labels: customer-reported
