### ISSUE TITLE
Converter for model type 'EquineBeast' cannot be used for 'ConsoleApp3.Rider.Mount' because its type is 'int'

### ISSUE THREAD

**Issue by HSchwichtenberg** [dotnet/efcore#11338] opened 2018-03-20 06:41 UTC
I cannot get the converter sample from the docs (https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions) to work with migrations.

Update-Database will throw an error: Converter for model type 'EquineBeast' cannot be used for 'ConsoleApp3.Rider.Mount' because its type is 'int'.

### Steps to reproduce

1. Code

```C#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ConsoleApp3
{
 class Program
 {
  static void Main(string[] args)
  {
   using (var ctx = new Context())
   {
    ctx.Database.EnsureCreated();

    var r = new Rider();

    r.Mount = EquineBeast.Donkey;
    ctx.Rider.Add(r);
    ctx.SaveChanges();

    Console.WriteLine(ctx.Rider.Count());
   }
  }
 }

 public class Rider
 {
  public int Id { get; set; }
  public EquineBeast Mount { get; set; }
 }

 public enum EquineBeast
 {
  Donkey,
  Mule,
  Horse,
  Unicorn
 }

 public partial class Context : DbContext
 {
  public virtual DbSet<Rider> Rider { get; set; }


  protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
  {
   if (!optionsBuilder.IsConfigured)
   {
    optionsBuilder.UseSqlServer(@"Server=.;Database=EFC21_Rider;Trusted_Connection=True;MultipleActiveResultSets=True;");
   }
  }

  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
   modelBuilder
       .Entity<Rider>()
       .Property(e => e.Mount)
       .HasConversion(
           v => v.ToString(),
           v => (EquineBeast)Enum.Parse(typeof(EquineBeast), v));
  }
 }
}
```

2. Add-Migration v1
3. Update-Database
Applying migration '20180320062757_v1'.
**System.ArgumentException: Converter for model type 'EquineBeast' cannot be used for 'ConsoleApp3.Rider.Mount' because its type is 'int'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalPropertyBuilder.HasConversion(ValueConverter valueConverter, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder`1.HasConversion(ValueConverter converter)
   at ConsoleApp3.Migrations.v1.<>c.<BuildTargetModel>b__2_0(EntityTypeBuilder b) in t:\ConsoleApp3\ConsoleApp3\Migrations\20180320062757_v1.Designer.cs:line 31
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(String name, Action`1 buildAction)
   at ConsoleApp3.Migrations.v1.BuildTargetModel(ModelBuilder modelBuilder) in t:\ConsoleApp3\ConsoleApp3\Migrations\20180320062757_v1.Designer.cs:line 26
   at Microsoft.EntityFrameworkCore.Migrations.Migration.<.ctor>b__4_0()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Converter for model type 'EquineBeast' cannot be used for 'ConsoleApp3.Rider.Mount' because its type is 'int'.**

### Further technical details
EF Core version :2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 2.1.0-preview1-final
Operating system: Windows 10 1709
IDE: Visual Studio 2017 15.6.1

**Comment by ajcvickers** [comment] 2018-03-20 16:18
Duplicate of #10748

**Closed** 2022-10-16 12:14 UTC
