### ISSUE TITLE
IDENTITY_INSERT error despite configuration

### ISSUE THREAD

**Issue by BratWiekszy** [dotnet/efcore#13794] opened 2018-10-28 11:19 UTC
When SaveChanges() is called, IDENTITY_INSERT error arises. Generated SQL contains [Id] column, while it mustn't.

#### What happens:
Let's say, we have column in table that has unique key constraint set. When adding model instance to context, its Id is assigned temporary id, but insert command does not include this column (correct). After SaveChanges() is called, predictable exception is thrown, signifying that unique column has duplicated value. Temp id value is not reset back, context is then disposed. When model data changes, so that duplication exists no more, new context is generated and has model added to it. Previous temp Id is considered valid value now. New insert now contains [Id] column with temp Id value, causing SQL Server identity insert error.

#### Model configuration:
I've tried `entity.Property(x => x.Id).UseSqlServerIdentityColumn();` and 
`entity.Property(x => x.Id).ValueGeneratedOnAdd();`, but both cause same behaviour.

I'm aware there's workaround for this issue, but this behaviour isn't predictable at all, and i suspect is wrong. First of all, model configuration should tell context to NEVER insert Id when identity is used, no matter value in model's property. 

##### Workaround (in case anybody stumbles upon same problem):
```c#
foreach (var entry in context.ChangeTracker.Entries())
{
	var entryId = entry.Property("Id");
	if (entryId.IsTemporary)
		entryId.CurrentValue = 0;
}
```

#### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.6

**Comment by BratWiekszy** [comment] 2018-10-28 14:46
Also, it may be worth noting that, after first SaveChanges() fails, saved model entityEntry's OriginalValue property is temp id, instead of 0, as if this Id had already been commited.

**Comment by ajcvickers** [comment] 2018-10-28 16:19
@BratWiekszy I have not been able to reproduce this--my code is below. Could you post a runnable project/solution or full code listing like that below that demonstrates the behavior you are seeing?

```C#
public class Blog
{
    public int Id { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    public DbSet<Blog> Blogs { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog());
            
            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var blog = context.Blogs.Find(1);
        }
    }
}
```

**Comment by BratWiekszy** [comment] 2018-10-29 08:47
[EFerrorRepro.zip](https://github.com/aspnet/EntityFrameworkCore/files/2524473/EFerrorRepro.zip)
Create db Test on local server beforehand

**Comment by ajcvickers** [comment] 2018-10-29 21:37
Duplicate of #10167 and see also #12378

**Closed** 2022-10-16 13:38 UTC
Labels: closed-duplicate, customer-reported
