### ISSUE TITLE
when i use EF.CompileAsyncQuery((DbContext db, Func<TEntity, bool> filter) => db.Set<TEntity>().Where(filter)),there has been an error

### ISSUE THREAD

**Issue by ClementeGao** [dotnet/efcore#26402] opened 2021-10-19 09:38 UTC
```
System.ArgumentException:“Expression of type 'System.Func`2[Domain.Entity,System.Boolean]' cannot be used for parameter of type 'System.Linq.Expressions.Expression`1[System.Func`2[Domain.Entity,System.Boolean]]' of method 'System.Linq.IQueryable`1[Domain.Entity] Where[Entity](System.Linq.IQueryable`1[Domain.Entity], System.Linq.Expressions.Expression`1[System.Func`2[Domain.Entity,System.Boolean]])' Arg_ParamName_Name”

```

**Comment by ajcvickers** [comment] 2021-11-02 13:11
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:11 UTC
Labels: closed-could-not-reproduce, customer-reported
