### ISSUE TITLE
Incorrect sql generated for query with groupby 

### ISSUE THREAD

**Issue by chrsas** [dotnet/efcore#13251] opened 2018-09-07 14:02 UTC
Context: AdventureWorksLT
EF Core: 2.1.2
LinQ:
```csharp
var builder = new DbContextOptionsBuilder<AdventureWorksLTContext>();
builder.UseSqlServer("Server=.;Database=AdventureWorksLT;Trusted_Connection=True;");
using (var db = new AdventureWorksLTContext(builder.Options))
{
    var result = from order in db.SalesOrderHeaders
                 join detail in db.SalesOrderDetails on order.SalesOrderId equals detail.SalesOrderId
                 group detail by order.DueDate.Date into go
                 select new
                 {
                     ShipDate = go.Key,
                     Amount = go.Sum(g => g.OrderQty)
                 };
    Console.WriteLine(result.ToArray().Count());
}
```
SQL:
```sql
SELECT [detail].[SalesOrderId], [detail].[SalesOrderDetailId], [detail].[ConfirmQty], [detail].[LineTotal], [detail].[ModifiedDate], [detail].[OrderQty], [detail].[ProductId], [detail].[Rowguid], [detail].[UnitPrice], [detail].[UnitPriceDiscount], [order].[DueDate]
FROM [SalesLT].[SalesOrderHeader] AS [order]
INNER JOIN [SalesLT].[SalesOrderDetail] AS [detail] ON [order].[SalesOrderId] = [detail].[SalesOrderId]
ORDER BY CONVERT(date, [order].[DueDate])
go
```
It does not grouped.

**Comment by ajcvickers** [comment] 2018-09-07 18:41
@smitpatel to find dupe.

**Comment by smitpatel** [comment] 2018-09-07 19:04
It is not invalid SQL. It does grouping on client and gives correct result.

**Comment by smitpatel** [comment] 2018-09-07 19:05
Duplicate of #10012

**Closed** 2022-10-16 13:29 UTC
Labels: closed-duplicate, customer-reported
