### ISSUE TITLE
Can I add relationship between two entitys but not create Foreign Key in database

### ISSUE THREAD

**Issue by dingsongjie** [dotnet/efcore#19618] opened 2020-01-17 09:48 UTC
This is my entity and config

```cs
    public class BacketItem : Entity
    {
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public long Price { get; set; }
    }
    public class Backet: Entity,IAggregateRoot
    {
        public string UserId { get; set; }
        public IReadOnlyCollection<BacketItem> BacketItems { get; private set; }
        public long TotalPrice { get; set; }
    }

    public class BacketEntityTypeConfiguration : IEntityTypeConfiguration<Backet.Api.Domain.AggregatesModel.BacketAggregate.Backet>
    {
        public void Configure(EntityTypeBuilder<Backet.Api.Domain.AggregatesModel.BacketAggregate.Backet> builder)
        {
            builder.ToTable(nameof(Backet.Api.Domain.AggregatesModel.BacketAggregate.Backet));

            builder.Property(m => m.Id).HasMaxLength(32);
            builder.Property(m => m.UserId).HasMaxLength(32).IsRequired();
            builder.HasMany(m => m.BacketItems).WithOne();

            builder.Ignore(m => m.DomainEvents);

            builder.HasKey(m => m.Id);
            builder.HasIndex(m => m.UserId);
        }
    }
```
This is the Migration 
```cs
            migrationBuilder.AddForeignKey(
                name: "FK_BacketItem_Backet_BacketId",
                table: "BacketItem",
                column: "BacketId",
                principalTable: "Backet",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
```

**Comment by ajcvickers** [comment] 2020-01-17 16:29
@dingsongjie Do you mean without creating a column for the FK in the database, or without creating the FK constraint in the database?

**Comment by dingsongjie** [comment] 2020-01-19 01:14
> @dingsongjie Do you mean without creating a column for the FK in the database, or without creating the FK constraint in the database?
I don't want to create any creating the FK constraint  in my database

**Comment by ajcvickers** [comment] 2020-01-24 19:58
@dingsongjie Follow-up question: why do you not want to create the constraint?

**Comment by ajcvickers** [comment] 2020-02-03 17:40
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:06 UTC
Labels: closed-out-of-scope, customer-reported
