### ISSUE TITLE
Shadow foreign key in self referencing table involved in many-to-many relationship with named join table throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by tiggris** [dotnet/efcore#30840] opened 2023-05-08 09:30 UTC
Hi,

I'm dealing with a very peculiar case including:
- TPH inheritance
- Self referencing table
- Many-to-many relationship without join entity

There is an issue when I try to query entity with shadow foreign key referencing the same table:

```
System.IndexOutOfRangeException : Index was outside the bounds of the array.

Stack Trace: 
lambda_method154(Closure , ValueBuffer )
InternalEntityEntry.ctor(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer& valueBuffer)
QueryContext.StartTracking(IEntityType entityType, Object entity, ValueBuffer valueBuffer)
lambda_method135(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
Enumerator.MoveNext()
List`1.ctor(IEnumerable`1 collection)
Enumerable.ToList[TSource](IEnumerable`1 source)
ShadowForeignKeyTests.QueryEntities_ShouldNotThrowException() line 19

```

This issue doesn't occur if:
- There is no many-to-many relationship with named join table involved
- Foreign key is declared explicitly as class property

A sample code can be found here: [https://github.com/tiggris/EFCoreShadowForeignKey](https://github.com/tiggris/EFCoreShadowForeignKey)

-----------
EF Core version: 7.0.5 (also tried 8.0.0-preview.3.23174.2)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.4.3

**Comment by AndriySvyryd** [comment] 2023-05-10 20:09
cc @ajcvickers

**Comment by ajcvickers** [comment] 2023-05-16 09:46
Duplicate of #30764.

**Closed by ajcvickers** 2023-05-16 09:46 UTC
Labels: customer-reported
