### ISSUE TITLE
Not Null Boolean Type didn't save from ChangeTracker Property

### ISSUE THREAD

**Issue by Shoogn** [dotnet/efcore#28499] opened 2022-07-23 09:27 UTC
## Not Null Boolean Type didn't save from ChangeTracker

I'm trying to save Boolean type by default by ChangeTracker property 
I have a base entity type like so
```C#
  public abstract class BaseEntity<TId>
    {
        public TId Id { get; set; }
        public DateTime? Added_Date { get; set; }
        public string AddedBy { get; set; }
        public DateTime? Modified_Date { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Guid ReferenceId { get; set; }
    }
```
And the Type that I'm trying  to save it to the database has this signature:
```C#
   public class ProductCategoryEntity : BaseEntity<int>
    {
        #region Entities

        public int BranchId { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }

        #endregion

        #region Relationship

        public virtual BranchEntity Branch { get; set; }
        public virtual ICollection<ProductEntity> Products { get; set; }

        #endregion
    }
```  

And the save method has this signature:

```C#
 public int CompleteWithAuditing<T>(string userId)
        {
            var tracker = _context.ChangeTracker;
            
            foreach (var entry in tracker.Entries())
            {
                if (entry.Entity is BaseEntity<T>)
                {
                    var entity = entry.Entity as BaseEntity<T>;

                    switch (entry.State)
                    {
                        case EntityState.Added:
                            entity.AddedBy = userId;
                            entity.Added_Date = DateTime.Now;
                            entity.IsDeleted = false; // The problem is here
                            break;

                        case EntityState.Modified:
                            entity.ModifiedBy = userId;
                            entity.Modified_Date = DateTime.Now;
                            break;

                        default:
                            break;
                    }
                }
            }

            return _context.SaveChanges();
        }
```
I'm using generic Repository, and I have an  Create method like so:
```C#
    public virtual T Create(T entity)
        {
            try
            {
                entity = _set.Add(entity).Entity;
            }
            catch (Exception ex) 
            {
                _ = ex;
            }
            return entity;
        }
```
And the main method to add the ProductCategory like so:

```C#
public async Task<ApiResult<ProductCategoryDto>> InsertProductCategoryAsync(ProductCategoryDto productCategory)
        {
            var response = new ApiResult<ProductCategoryDto>() { StatusCode = 400, Success = false };

            var validation = new ProductCategoryValidator(_sharedResources);
            var validationResult = await validation.ValidateAsync(productCategory);

            if (validationResult.Errors.Count > 0)
            {
                foreach (var error in validationResult.Errors)
                {
                    response.Errors.Add(new Error { Message = error.ErrorMessage });
                }
                return response;
            }
         
            // Check no duplication name
            Expression<Func<ProductCategoryEntity, bool>> e = (e => e.NameAr == productCategory.NameAr && e.BranchId == productCategory.BranchId);
            var isNameExist = _productCategoryRepo.IsExist(e);
            if (isNameExist)
            {
                response.Errors.Add(new Error { Message = _sharedResources.GetResource("Name_In_Arabic_Is_Already_Exist") });
                return response;
            }
            var user = _httpContextAccessor.HttpContext.User.GetCurrentUser();
            var entityToSave = _mapper.Map<ProductCategoryDto, ProductCategoryEntity>(productCategory);
            //entityToSave.IsDeleted = true;
           // entityToSave.AddedBy = user.UserId;
            _productCategoryRepo.Create(entityToSave);
           // _uow.Complete();
            _uow.CompleteWithAuditing<int>(user.UserId);
            return ApiResult<ProductCategoryDto>.SuccessResult(productCategory);

        }
```

If I commented the ( CompleteWithAuditing( ) )   method and use the default one ( Complete( ) ) it will work normally and save without any exception

```C#
            entityToSave.IsDeleted = true;
            entityToSave.AddedBy = user.UserId;
            _productCategoryRepo.Create(entityToSave);
          _uow.Complete();
         //_uow.CompleteWithAuditing<int>(user.UserId);
```
But **IsDeleted** column is never saved if I try to save it when Tracking Change by **ChangeTracker** Property

### Stack traces
```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'IsDeleted', table 'IGoInvoice_DB.product.ProductCategories'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:72e613ef-8c81-4a24-8410-2fad698b98cf
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__104_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at IGoInvoice.Application.Context.BaseDBContext.SaveChanges() in C:\Users\Mohammed\source\repos\IGoInvoice\src\Domain\IGoInvoice.Application\Context\BaseDBContext.cs:line 57
   at IGoInvoice.Repository.Persistence.UnitOfWork.CompleteWithAuditing[T](String userId) in C:\Users\Mohammed\source\repos\IGoInvoice\src\Domain\IGoInvoice.Repository.Persistence\UnitOfWork.cs:line 96
   at IGoInvoice.Service.Features.Product.ProductCategoryService.InsertProductCategoryAsync(ProductCategoryDto productCategory) in C:\Users\Mohammed\source\repos\IGoInvoice\src\Service\IGoInvoice.Service\Features\Product\ProductCategoryService.cs:line 101
   at IGoInvoice.API.Controllers.ProductCategoriesController.CreateProductCategory(ProductCategoryDto productCategoryDto) in C:\Users\Mohammed\source\repos\IGoInvoice\src\Presentaion\IGoInvoice.API\Controllers\ProductCategoriesController.cs:line 29
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Provider and version information

EF Core version: 6.0.6
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.2.3)

**Comment by ajcvickers** [comment] 2022-07-23 09:51
This issue is lacking enough information for us to be able to fully understand what is happening. In particular, it is missing the model configuration. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-08-02 13:33
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-08-02 13:33 UTC
Labels: customer-reported
