### ISSUE TITLE
Expression of type IQueryable<X> cannot be used for parameter of type IQueryable<Y> of method...

### ISSUE THREAD

**Issue by furier** [dotnet/efcore#18396] opened 2019-10-16 09:24 UTC
Some queries but not all have this exception throwing for ef core 3.0 but have worked with previous versions from 2.2 and below.

```
Expression of type 'System.Linq.IQueryable`1[Domain.Entities.Base.ClientEntityBase]' cannot be used for parameter of type 'System.Linq.IQueryable`1[Domain.Entities.Document]' of method 'System.Linq.IQueryable`1[Domain.Entities.Document] Where[Document](System.Linq.IQueryable`1[Domain.Entities.Document], System.Linq.Expressions.Expression`1[System.Func`2[Domain.Entities.Document,System.Boolean]])' (Parameter 'arg0')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
```

### Queryable DebugView

```
.Call System.Linq.Queryable.Where(
    .Call System.Linq.Queryable.Where(
        .Call System.Linq.Queryable.Where(
            .Call System.Linq.Queryable.Cast(.Call System.Linq.Queryable.Where(
                    .Call System.Linq.Queryable.Cast(.Constant<Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Domain.Entities.Document]>(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Domain.Entities.Document]))
                    ,
                    '(.Lambda #Lambda1<System.Func`2[Domain.Entities.Base.ClientEntityBase,System.Boolean]>))),
            '(.Lambda #Lambda2<System.Func`2[Domain.Entities.Document,System.Boolean]>)),
        '(.Lambda #Lambda3<System.Func`2[Domain.Entities.Document,System.Boolean]>)),
    '(.Lambda #Lambda4<System.Func`2[Domain.Entities.Document,System.Boolean]>))

.Lambda #Lambda1<System.Func`2[Domain.Entities.Base.ClientEntityBase,System.Boolean]>(Domain.Entities.Base.ClientEntityBase $x)
{
    !($x.ClientId).HasValue || $x.ClientId == .Constant<Persistence.Tenant.ProplanContext+<>c__DisplayClass387_0`1[Domain.Entities.Document]>(Persistence.Tenant.ProplanContext+<>c__DisplayClass387_0`1[Domain.Entities.Document]).clientId
    || $x.ClientShared
}

.Lambda #Lambda2<System.Func`2[Domain.Entities.Document,System.Boolean]>(Domain.Entities.Document $x) {
    !.Call System.Linq.Queryable.Contains(
        .Call System.Linq.Queryable.Select(
            .Call System.Linq.Queryable.Where(
                .Call (.Constant<GraphQL.Personal.Services.PersonalDocumentService>(GraphQL.Personal.Services.PersonalDocumentService)._context).Queryable(True)
                ,
                '(.Lambda #Lambda5<System.Func`2[Domain.Entities.Document,System.Boolean]>)),
            '(.Lambda #Lambda6<System.Func`2[Domain.Entities.Document,System.Nullable`1[System.Guid]]>)),
        (System.Nullable`1[System.Guid])$x.Id)
}

.Lambda #Lambda3<System.Func`2[Domain.Entities.Document,System.Boolean]>(Domain.Entities.Document $x) {
    $x.DocumentCategoryId == (System.Nullable`1[System.Guid])(Domain.Data.Constants+DocumentCategories.HR).Id
}

.Lambda #Lambda4<System.Func`2[Domain.Entities.Document,System.Boolean]>(Domain.Entities.Document $x) {
    !.Call System.Linq.Queryable.Any(
        .Call System.Linq.Queryable.Where(
            .Constant<GraphQL.Personal.Services.PersonalDocumentService+<>c__DisplayClass10_0>(GraphQL.Personal.Services.PersonalDocumentService+<>c__DisplayClass10_0).documentXEntities,
            '(.Lambda #Lambda7<System.Func`2[Domain.Entities.DocumentXEntity,System.Boolean]>)),
        '(.Lambda #Lambda8<System.Func`2[Domain.Entities.DocumentXEntity,System.Boolean]>))
}

.Lambda #Lambda5<System.Func`2[Domain.Entities.Document,System.Boolean]>(Domain.Entities.Document $y) {
    ($y.PreviousId).HasValue
}

.Lambda #Lambda6<System.Func`2[Domain.Entities.Document,System.Nullable`1[System.Guid]]>(Domain.Entities.Document $y)
{
    $y.PreviousId
}

.Lambda #Lambda7<System.Func`2[Domain.Entities.DocumentXEntity,System.Boolean]>(Domain.Entities.DocumentXEntity $y)
{
    $y.DocumentCommonId == $x.CommonId
}

.Lambda #Lambda8<System.Func`2[Domain.Entities.DocumentXEntity,System.Boolean]>(Domain.Entities.DocumentXEntity $z)
{
    .Call System.Linq.Enumerable.Contains(
        .Constant<GraphQL.Personal.Services.PersonalDocumentService+<>c__DisplayClass10_0>(GraphQL.Personal.Services.PersonalDocumentService+<>c__DisplayClass10_0).excludePersonIds,
        $z.EntityId) && .Call ($z.EntityName).Equals("Person")
}
```

#### Expression by RedableExpressions Visualizer

```
EntityQueryable<Document>
    .Cast<ClientEntityBase>()
    .Where(x => (!x.ClientId.HasValue || (x.ClientId == clientId)) || x.ClientShared)
    .Cast<Document>()
    .Where(
        x => !_context
            .Queryable<Document>(true)
            .Where(y => y.PreviousId.HasValue)
            .Select(y => y.PreviousId)
            .Contains((Guid?)x.Id))
    .Where(x => x.DocumentCategoryId == ((Guid?)Constants.DocumentCategories.HR.Id))
    .Where(x => !documentXEntities.Where(y => y.DocumentCommonId == x.CommonId).Any(z => excludePersonIds.Contains(z.EntityId) && z.EntityName.Equals("Person")))
```

#### Context.Queryable<T>() implementation

```
public IQueryable<TEntityType> Queryable<TEntityType>(bool filterOnClientId = true) where TEntityType : class
{
   var clientId = GetClientId();
   return filterOnClientId && typeof(ClientEntityBase).IsAssignableFrom(typeof(TEntityType))
       ? Set<TEntityType>().Cast<ClientEntityBase>().Where(x => !x.ClientId.HasValue || x.ClientId == clientId || x.ClientShared).Cast<TEntityType>()
       : Set<TEntityType>();
}
```

### Stack Trace

```
System.ArgumentException: Expression of type 'System.Linq.IQueryable`1[Domain.Entities.Base.ClientEntityBase]' cannot be used for parameter of type 'System.Linq.IQueryable`1[Domain.Entities.Document]' of method 'System.Linq.IQueryable`1[Domain.Entities.Document] Where[Document](System.Linq.IQueryable`1[Domain.Entities.Document], System.Linq.Expressions.Expression`1[System.Func`2[Domain.Entities.Document,System.Boolean]])' (Parameter 'arg0')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessWhere(NavigationExpansionExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandAndReduce(Expression query, Boolean applyInclude)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at System.Linq.Dynamic.Core.DynamicEnumerableExtensions.CastToList[T](IEnumerable source)
   at System.Linq.Dynamic.Core.DynamicEnumerableExtensions.ToDynamicList(IEnumerable source)
   at GraphQL.Core.GraphTypes.ConnectionType.BuildResponse(IQueryable queryable, Nullable`1 totalCount) in C:\Users\furie\source\repos\PPBS\GraphQL.Core\GraphTypes\ConnectionType.cs:line 90
   at GraphQL.Core.GraphTypes.ConnectionType.BuildResponse(ValueTuple`2 tuple) in C:\Users\furie\source\repos\PPBS\GraphQL.Core\GraphTypes\ConnectionType.cs:line 87
   at GraphQL.Core.GraphTypes.ConnectionType.ToConnection[T,TSource](ResolveFieldContext`1 context, IQueryable queryable) in C:\Users\furie\source\repos\PPBS\GraphQL.Core\GraphTypes\ConnectionType.cs:line 107
   at GraphQL.Core.GraphTypes.ProplanObjectGraphType`1.<>c__DisplayClass3_0`2.<Connection>b__0(ResolveFieldContext`1 gqlContext) in C:\Users\furie\source\repos\PPBS\GraphQL.Core\GraphTypes\ProplanObjectGraphType.cs:line 45
   at GraphQL.Resolvers.FuncFieldResolver`2.GraphQL.Resolvers.IFieldResolver.Resolve(ResolveFieldContext context)
   at GraphQL.Instrumentation.MiddlewareResolver.Resolve(ResolveFieldContext context)
   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node)
```

### Further technical details

EF Core version: 3.0.0, 3.1.0-preview*
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windwos 10 (1903) Build: 18362.356
IDE: Visual Studio 2019 16.3.5

**Comment by gojanpaolo** [comment] 2019-11-22 20:03
Getting this exception on `ICollection<X>` for `IQueryable<Y>` as well which is working in 2.2.6 and not in 3.0.1.

**Comment by smitpatel** [comment] 2019-11-23 02:44
Duplicate of #18087

**Comment by smitpatel** [comment] 2019-11-23 02:44
if it does not work on 3.1 then please provide a full repro code.

**Closed** 2022-10-16 14:50 UTC
Labels: closed-duplicate, customer-reported
