### ISSUE TITLE
Executing Stored Procedure in EFCore 3.0

### ISSUE THREAD

**Issue by debolakoya** [dotnet/efcore#18174] opened 2019-10-01 23:32 UTC
Prior to EFCore 3.0, a query like the one below would work 
```
var user = "johndoe";
var blogs = context.Blogs
    .FromSql($"EXECUTE dbo.GetMostPopularBlogsForUser {user}")
    .FirstOrDefaultAsync();
```
and translate to the SQL command below
```
exec sp_executesql N'Exec @p0 @p1
',N'@p0 nvarchar(4000),@p1 nvarchar(4000),@p0=N'dbo.GetMostPopularBlogsForUser ',@p1=N'johndoe'
```
With the upgrade to EFCore 3.0 and changing FromSql to either FromSqlRaw() or FromSqlInterpolated() would generate. Please note the issue happens on when you call **FirstOrDefaultAsync** 

```
exec sp_executesql N'SELECT  TOP (1) [v].[BlogId ], [v].[Url]
FROM (
    EXECUTE @p0 @p1
) AS [v]',N'@p0 nvarchar(4000),@p1 nvarchar(4000),@p0=N'dbo.GetMostPopularBlogsForUser',@p1=N'johndoe'
```
Which is an invalid SQL and hence would throw error.

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment] 2019-10-01 23:53
Duplicate of #17558

**Closed** 2022-10-16 14:46 UTC
Labels: customer-reported
