### ISSUE TITLE
HasConversion support for nested properties

### ISSUE THREAD

**Issue by qfcolin** [dotnet/efcore#17194] opened 2019-08-16 07:18 UTC
Apologies if this isn't really an issue or is already known but I couldn't find a solution online.
I have a class which has as one of its navigation properties, a list of the same class. I want to have a custom conversion on a property of this class. Using HasConversion what I am seeing is the custom conversion only applies on the parent level and not on the child level.
See code sample below:

### Steps to reproduce
```c#
public class Person
{
public string Name {get;set;}
public DateTime? DOB {get;set;}
public List<Person> Family {get;set;}
}

public class PersonMap
{
        public PersonMap(EntityTypeBuilder<Person> entityBuilder)
        {
           entityBuilder.Property(t => t.DOB).HasConversion<DateTime?>(t => t.HasValue && t.Value == DateTime.MinValue ? null : t, t => t);
        }
}
```
What I would like to happen when I write a person and their family to the DB is if the DOB is DateTime.MinValue then save it as null for that person and all the family members.

Instead what I see is only the parent level DOB is set to null and family members are saved as DateTime.Min

Thanks for any help,
Colin

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer)

**Comment by ajcvickers** [comment] 2019-11-15 20:53
Duplicate of #13850

**Closed** 2022-10-16 14:36 UTC
Labels: closed-duplicate, customer-reported
