### ISSUE TITLE
Exception when creating SQLite DB in when targetting osx-arm64 / .Net 6 (preview)

### ISSUE THREAD

**Issue by Webreaper** [dotnet/efcore#24198] opened 2021-02-19 15:57 UTC
I'm using a SQLite provider with .Net 6.0 preview 1, and EFCore 6.0, targetting Apple Silicon (osx-arm64). When the DB creation is attempted, the following exception is thrown:

```C#
Exception: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
Unhandled exception. System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: Unable to load shared library 'e_sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libe_sqlite3, 1): image not found
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
   at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.Init()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnectionState()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
```

[Discussed this with Rich Lander](https://twitter.com/runfaster2000/status/1362783355842957312), and concluded that it's likely to be because the native/unmanaged SQLite libraries can't be loaded because they're x64, not arm64. 

The project where this happens is here: https://github.com/Webreaper/Damselfly - I will try and create a small standalone repro project if I get time.

EF Core version: 6.0.100-preview.1.21103.13
Database provider: SQLite
Target framework: 6.0.100-preview.1.21103.13
Operating system: OSX 11.3 Beta (20E5172i)
Hardware: Apple MacBook Pro M1
IDE: Visual Studio for Mac 8.9 build 1593

**Comment by ajcvickers** [comment] 2021-02-19 17:11
@ericsink @bricelam This one is about SQLite on Apple silicon. What are the expectations here?

**Comment by ericsink** [comment] 2021-02-19 17:22
Support for Apple silicon will be in SQLitePCLRaw 2.0.5.  Actually the work is done and is part of the following prerelease:

https://www.nuget.org/packages/SQLitePCLRaw.core/2.0.5-pre20210119130047

(Somebody at Microsoft whose handle I don't remember did the actually work here and submitted it as a PR.)

**Comment by ajcvickers** [comment] 2021-02-19 17:24
@Webreaper Can you try with the preview linked by Eric and see if this fixes the issue?

**Comment by Webreaper** [comment] 2021-02-19 22:56
I tried pulling the package from above, and dropping the DLL into my output folder, and running, but I get the same exception. From my understanding of the structure, that's the interop C# DLL that wraps the native unmanaged SQLite code, right? If so, presumably we'd need the native DLLs rebuilt for arm64 for this to work?

**Comment by ajcvickers** [comment] 2021-02-22 18:27
@Webreaper As I understand it, the updated SQLItePCLRaw packages should contain native libraries compiled for arm64. @ericsink  should be able to confirm.

@bricelam According to the original post, this is already 6.0 preview:

> I'm using a SQLite provider with .Net 6.0 preview 1, and EFCore 6.0,

**Comment by ericsink** [comment] 2021-02-22 18:48
So the link I posted above was mostly just to give the preview version number.  Replacing just the SQLitePCLRaw.core package would be insufficient.

You are probably getting SQLitePCLRaw.bundle_e_sqlite3 by way of the efcore nuget packages.  To get the full preview, you need to update *that* nuget package to the version I mentioned:

```
<PackageReference Include="sqlitepclraw.bundle_e_sqlite3" Version="2.0.5-pre20210119130047" />
```

**Comment by Webreaper** [comment] 2021-02-22 19:04
Makes much more sense. Thanks Eric - will give that a go when I get the chance.

**Comment by Webreaper** [comment] 2021-02-23 11:57
Sadly still not working. Must be missing something. My references for the project are: 
```
<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0-preview.1.21102.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.0-preview.1.21102.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0-preview.1.21102.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="6.0.0-preview.1.21102.2" />
    <PackageReference Include="sqlitepclraw.bundle_e_sqlite3" Version="2.0.5-pre20210119130047" />
    <PackageReference Include="MetadataExtractor" Version="2.4.3" />
    <PackageReference Include="CommandLineParser" Version="2.8.0" />
    <PackageReference Include="WordPressPCL" Version="1.8.5" />
    <PackageReference Include="EFCore.BulkExtensions" Version="3.3.1" />
    <PackageReference Include="NExifTool" Version="0.9.0" />
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="4.0.0-dev-00839" />
    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.3" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta11" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0-preview.1.21102.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="font-awesome" Version="4.7.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.0-preview.1.21102.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentValidation" Version="9.5.1" />
    <PackageReference Include="SkiaSharp" Version="2.80.3-preview.40" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.80.3-preview.40" />
    <PackageReference Include="System.Text.Json" Version="6.0.0-preview.1.21102.12" />
  </ItemGroup>
```

**Comment by ajcvickers** [comment] 2021-02-23 19:16
@Webreaper Can you put together a simple project with only EF Core and SQLite dependencies and then post that here so we can investigate? Also use "Microsoft.EntityFrameworkCore.Sqlite.Core" package rather than "Microsoft.EntityFrameworkCore.Sqlite" since you're bringing your PCLraw package.

**Comment by ericsink** [comment] 2021-02-23 19:22
I should note that it is possible the osx-arm64 stuff actually isn't working yet in SQLitePCLRaw.  I'll have to check and see if anybody has verified it.  I don't have an M1 Mac to test with.

**Comment by Webreaper** [comment] 2021-02-23 21:02
I'll try and build a small standalone sample tonight and stick it on github. Haven't had a chance previously!

**Comment by Webreaper** [comment] 2021-02-23 23:44
Okay, here's a sample project: https://github.com/Webreaper/Dotnet6Sqlite

To mirror my scenario, I've created a Blazor Server project - it's a vanilla project from the VS template with no changes other than the DB model and initialisation added. However, you could no doubt repro this in a simpler console app. 

Let me know if you need anything else.

**Comment by u2m4c6** [comment] 2021-07-22 16:09
So does Sqlite not currently work on Apple Silicon? I have updated every dependency to the daily builds, including SQLitePCLRaw.

I wonder if the MAUI team is aware of this? @davidortinau 

Most MAUI development for macOS, iPad, iPhone is unusable without Sqlite support. I am preaching to the choir but mobile depends on Sqlite in production--it is not just a development tool like it is for web or some desktop apps.

**Comment by ericsink** [comment] 2021-07-22 16:19
The Apple Silicon support for SQLitePCLRaw is currently only available in the 2.0.5 pre-release versions.

**Comment by demming** [comment] 2021-08-06 13:20
Hi, I'm also affected by this issue. Any way I can assist at resolving it?

For instance, just this trivial app <https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app> produces the error. Here's my project file,

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0-preview.6.21352.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.0-preview.6.21352.1" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.0.5-pre20210521085756" />
  </ItemGroup>

</Project>
```

<details>
<summary>(Truncated) directory tree of the build</summary>

```
.
├── Properties
│   └── PublishProfiles
│       └── FolderProfile.pubxml
├── bin
│   ├── Debug
│   │   └── net6.0
│   │       ├── Humanizer.dll
│   │       ├── Microsoft.Data.Sqlite.dll
│   │       ├── Microsoft.EntityFrameworkCore.Abstractions.dll
│   │       ├── Microsoft.EntityFrameworkCore.Design.dll
│   │       ├── Microsoft.EntityFrameworkCore.Relational.dll
│   │       ├── Microsoft.EntityFrameworkCore.Sqlite.dll
│   │       ├── Microsoft.EntityFrameworkCore.dll
│   │       ├── Microsoft.Extensions.Caching.Abstractions.dll
│   │       ├── Microsoft.Extensions.Caching.Memory.dll
│   │       ├── Microsoft.Extensions.Configuration.Abstractions.dll
│   │       ├── Microsoft.Extensions.DependencyInjection.Abstractions.dll
│   │       ├── Microsoft.Extensions.DependencyInjection.dll
│   │       ├── Microsoft.Extensions.DependencyModel.dll
│   │       ├── Microsoft.Extensions.Logging.Abstractions.dll
│   │       ├── Microsoft.Extensions.Logging.dll
│   │       ├── Microsoft.Extensions.Options.dll
│   │       ├── Microsoft.Extensions.Primitives.dll
│   │       ├── SQLitePCLRaw.batteries_v2.dll
│   │       ├── SQLitePCLRaw.core.dll
│   │       ├── SQLitePCLRaw.nativelibrary.dll
│   │       ├── SQLitePCLRaw.provider.dynamic_cdecl.dll
│   │       ├──console-app.deps.json
│   │       ├──console-app.dll
│   │       ├──console-app.pdb
│   │       ├──console-app.runtimeconfig.json
│   │       ├── ref
│   │       │   └──console-app.dll
│   │       └── runtimes
│   │           ├── alpine-x64
│   │           │   └── native
│   │           │       └── libe_sqlite3.so
│   │           ├── linux-arm
│   │           │   └── native
│   │           │       └── libe_sqlite3.so
│   │           ├── linux-arm64
│   │           │   └── native
│   │           │       └── libe_sqlite3.so
│   │           ├── linux-armel
│   │           │   └── native
│   │           │       └── libe_sqlite3.so
│   │           ├── linux-mips64
│   │           │   └── native
│   │           │       └── libe_sqlite3.so
│   │           ├── linux-musl-x64
│   │           │   └── native
│   │           │       └── libe_sqlite3.so
│   │           ├── linux-x64
│   │           │   └── native
│   │           │       └── libe_sqlite3.so
│   │           ├── linux-x86
│   │           │   └── native
│   │           │       └── libe_sqlite3.so
│   │           ├── osx-x64
│   │           │   └── native
│   │           │       └── libe_sqlite3.dylib
│   │           ├── win-arm
│   │           │   └── native
│   │           │       └── e_sqlite3.dll
│   │           ├── win-arm64
│   │           │   └── native
│   │           │       └── e_sqlite3.dll
│   │           ├── win-x64
│   │           │   └── native
│   │           │       └── e_sqlite3.dll
│   │           └── win-x86
│   │               └── native

```

</details>

The "missing" library file `libe_sqlite3.dylib` is apparently there, albeit only for the `osx-x64` arch.
On the other hand, building for `osx-x64`,

```
dotnet publish -c Release -r osx-x64
```

does produce a working binary. With this, however, another issue arises, namely no table gets created, but that's a different story.

<details>
<summary>(Truncated content of) <code>console-app.deps.json</code></summary>

```json
  "targets": {
      "SQLitePCLRaw.lib.e_sqlite3/2.0.5-pre20210521085756": {
        "runtimeTargets": {
          "runtimes/alpine-x64/native/libe_sqlite3.so": {
            "rid": "alpine-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/linux-arm/native/libe_sqlite3.so": {
            "rid": "linux-arm",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/linux-arm64/native/libe_sqlite3.so": {
            "rid": "linux-arm64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/linux-armel/native/libe_sqlite3.so": {
            "rid": "linux-armel",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/linux-mips64/native/libe_sqlite3.so": {
            "rid": "linux-mips64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/linux-musl-x64/native/libe_sqlite3.so": {
            "rid": "linux-musl-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/linux-x64/native/libe_sqlite3.so": {
            "rid": "linux-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/linux-x86/native/libe_sqlite3.so": {
            "rid": "linux-x86",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/osx-x64/native/libe_sqlite3.dylib": {
            "rid": "osx-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/win-arm/native/e_sqlite3.dll": {
            "rid": "win-arm",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/win-arm64/native/e_sqlite3.dll": {
            "rid": "win-arm64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/win-x64/native/e_sqlite3.dll": {
            "rid": "win-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/win-x86/native/e_sqlite3.dll": {
            "rid": "win-x86",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          }
        }
```

</details>

<details>
<summary> Output of <code>dotnet --info</code></summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21355.2
 Commit:    7f8e0d76c0

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.5
 OS Platform: Darwin
 RID:         osx.11.0-arm64
 Base Path:   /Users/nick/Projects/dotnet/dotnet-sdk-6.0/preview.6/sdk/6.0.100-preview.6.21355.2/

Host (useful for support):
  Version: 6.0.0-preview.6.21352.12
  Commit:  770d630b28

.NET SDKs installed:
  6.0.100-preview.6.21355.2 [/Users/nick/Projects/dotnet/dotnet-sdk-6.0/preview.6/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [/Users/nick/Projects/dotnet/dotnet-sdk-6.0/preview.6/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [/Users/nick/Projects/dotnet/dotnet-sdk-6.0/preview.6/shared/Microsoft.NETCore.App]
```

Same with a global copy with the usual paths.

</summary>

**Comment by Webreaper** [comment] 2021-08-06 13:42
I think per @ericsink 's comment, until the actual raw Sqlite binaries for ARM64/M1 come out of beta, there's not much they can do about it (unless the EFCore team chose to ship 2.0.5 pre-release versions with EFCore 6-preview-7, but presumably they'd have to roll that back for when EFCore 6 'proper' was released, so it wouldn't help much. 

Meantime, we'll just have to be patient and wait a little longer for the ARM64 SDK goodness.

**Comment by demming** [comment] 2021-08-06 16:49
I see. I hope I'm not missing something, but as I see right now, @ericsink's prerelease has been referenced in EFCore.Sqlite since Jan 5, 2021, cf. da0976cb4ca4b694118fd708b6d2e2a92cef0eeb. I can't check right now, but I believe the recent Preview releases of EFCore 6.0 are likely to have been made available with the prereleases of SQLitePCLRaw-2.0.5.

**Comment by Webreaper** [comment] 2021-08-06 16:53
Interesting, I didn't realise that. I'm using EFCore 6.0 preview-4 (I can't upgrade to preview-6 because of https://github.com/dotnet/efcore/issues/25314). I'll have a look when I get a chance.

**Comment by demming** [comment] 2021-08-06 17:03
In fact, the referenced version in EFCore 6.0 Preview had been 2.0.5-pre20201231105030, but as @ericsink states above in this issue, the arm64 binaries would not be provided until a pre-release two weeks later. And in the commit 6449203147298f03b34d227de1a5b48f62060bf1, the version was bumped to the most recent release 2.0.5-pre20210521085756. Still, thereby the most recent Preview release should already incorporate the osx-arm binaries, but they aren't there.

> Support for Apple silicon will be in SQLitePCLRaw 2.0.5. Actually the work is done and is part of the following prerelease:
> 
> https://www.nuget.org/packages/SQLitePCLRaw.core/2.0.5-pre20210119130047
> 
> (Somebody at Microsoft whose handle I don't remember did the actually work here and submitted it as a PR.)

**Comment by demming** [comment] 2021-08-06 17:12
> Interesting, I didn't realise that. I'm using EFCore 6.0 preview-4 (I can't upgrade to preview-6 because of #25314). I'll have a look when I get a chance.

Hmm, yeah, I can't look into it right now, but it's not hard to match the two commit hashes to the Preview release versions. I'll try building them from source.

For the time being, I'm content with the osx-x64 SDK on the M1, as performance is secondary for that project of mine.

**Comment by Webreaper** [comment] 2021-08-06 17:41
Yep, I mostly deploy on Linux, so whilst it would be nice to run .Net native on the M1 for performance, Rosetta is still awesome.

**Comment by ericsink** [comment] 2021-08-06 19:55
Really?

```
$ unzip -l SQLitePCLRaw.lib.e_sqlite3.2.0.5-pre20210628105421.nupkg | grep osx
  3167935  2021-05-13 15:49   runtimes/osx-x64/native/libe_sqlite3.dylib
```

(grumble)

Sorry.  I thought I had done this part...

**Comment by ericsink** [comment] 2021-08-06 20:03
I think I see what happened.

```
$ ls -lR
.:
total 7164
drwxr-xr-x 1 eric 197609       0 May 13 10:49 arm64/
-rw-r--r-- 1 eric 197609 4163208 May 13 10:49 e_sqlite3.a
-rw-r--r-- 1 eric 197609 3167935 May 13 10:49 libe_sqlite3.dylib
drwxr-xr-x 1 eric 197609       0 May 13 10:49 x86_64/

./arm64:
total 3664
-rw-r--r-- 1 eric 197609 2201680 May 13 10:49 e_sqlite3.a
-rw-r--r-- 1 eric 197609 1545919 May 13 10:49 libe_sqlite3.dylib

./x86_64:
total 3480
-rw-r--r-- 1 eric 197609 1961480 May 13 10:49 e_sqlite3.a
-rw-r--r-- 1 eric 197609 1600000 May 13 10:49 libe_sqlite3.dylib
```

Over in my cb repo, there are 3 dylibs of e_sqlite3 for the Mac.  One for x64, one for arm, and one that is much bigger.  I think that third one combines the two (does Apple call that a "fat" binary?).  

And I thought that one was the only one I needed.  But even if that's true, putting it only under the osx-x64 RID would be wrong.  

I probably need to put the other two under their respective RIDs.

**Comment by DamianEdwards** [comment] 2021-08-16 04:08
I just hit this while setting up my Mac Mini. Any ETA for a fix? I see the [linked change](https://github.com/ericsink/SQLitePCL.raw/commit/dc7118017e78c5b4c515f361df47e44616cb65e7) that seems like it might fix the issue so I guess we need to wait for a release?

**Comment by ericsink** [comment] 2021-08-16 13:48
I hope to publish a new PRE-release (which could be used to test the fix for apple silicon) today or tomorrow, pending ericsink/SQLitePCL.raw#434

*E*TA for the 2.0.5 release is end of August.

**Comment by ericsink** [comment] 2021-08-17 17:41
2.0.5-pre20210817120427 is on nuget.org and should fix osx-arm64.  Somebody let me know if I got it right this time?  Thanks!

**Comment by DamianEdwards** [comment] 2021-08-17 18:57
Seems to work now thanks! However, a warning is displayed when doing the restore into a .NET 6.0 project, saying the restore was done in the context of .NET Framework (NU1701) which is surprising to me given the packages have `netstandard2.0` targets. Which package(s) should I be referencing directly? Right now I'm referencing `SQLitePCLRaw.bundle_e_sqlite3`

**Comment by ericsink** [comment] 2021-08-17 19:02
@DamianEdwards You're referencing the right package -- I've been noticing that warning as well, and I'm pretty sure it's something I need to fix.  Thanks!

**Comment by DamianEdwards** [comment] 2021-08-17 19:05
Yeah it seems the issue is in `SQLitePCLRaw.lib.e_sqlite3`.

For version 2.0.4 it has the required folders:
![image](https://user-images.githubusercontent.com/249088/129785598-a9ee1a92-2af0-4855-9f3f-c035967faf9b.png)

But for the latest 2.0.5 preview it doesn't:
![image](https://user-images.githubusercontent.com/249088/129785648-5eb6fb5b-a953-4de6-a5af-9143a71963b6.png)

**Comment by stefc** [comment] 2021-08-18 05:13
The last Package not compiled with net6.0 on my side :( the previous package compiled but break on seeking for the e_sqlite dylib. 

`/Users/stefc/Projects/.IntegrationTests.csproj : error NU1701: Das Paket "SQLitePCLRaw.lib.e_sqlite3 2.0.5-pre20210817120427" wurde nicht mit dem Projektzielframework "net6.0", sondern mit ".NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8" wiederhergestellt. Dieses Paket ist mit Ihrem Projekt möglicherweise nicht vollständig kompatibel. [/Users/stefc/Projects/txs/sustain/backend/TXS.Sust.sln]`

I'm currently work on a MacMini M1 using net6.0 preview 7. 

`Laufzeitumgebung:
 OS Name:     Mac OS X
 OS Version:  11.4
 OS Platform: Darwin
 RID:         osx.11.0-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-preview.7.21379.14/`

My Package References currently 

`<ItemGroup>
        <PackageReference Include="sqlitepclraw.bundle_e_sqlite3" Version="2.0.5-pre20210817120427" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0-preview.7.21378.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.0-preview.7.21378.4" />
        <PackageReference Include="Oracle.EntityFrameworkCore" Version="5.21.3" />
    </ItemGroup>`

**Comment by ajcvickers** [comment] 2021-08-28 07:13
@DamianEdwards PR is up already: https://github.com/dotnet/efcore/pull/25730

**Comment by bricelam** [comment] 2021-09-20 18:58
Verified. This will be fixed in the RC2 (October) release.

**Comment by bricelam** [comment] 2021-09-20 18:59
Note, in the meantime, you can work around it by manually updating the SQLitePCLRaw packages.

**Closed by bricelam** 2021-09-20 18:58 UTC
Labels: type-bug, customer-reported, area-adonet-sqlite, verify-fixed

**Comment by lndnbrg** [comment] 2021-09-21 18:02
@bricelam Sorry for asking this very newbie question... How can I update the package manually, so that the SQLite packages pick the correct version?

**Comment by rish501** [comment] 2022-04-04 10:06
Hi

This issue is not specific to arm64/M1. Having same issue on Intel MacBook 16 (running latest Big Sur) when creating a new azure functions app. Same project work fine in Windows.

**Comment by Webreaper** [comment] 2022-04-04 10:57
@rish501 This issue is very specifically targetted as OSX ARM64 on Apple Silicon. The problem did not occur when running the same project using Intel emulation (using Rosetta). 

So if you're seeing another issue where you're trying to run something on an intel Mac and it's not working, you should raise another issue, as it's not related to this issue.
