### ISSUE TITLE
TPH Inheritance - Inherited Object Retrieval along with base class

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/efcore#9879] opened 2017-09-22 16:07 UTC
In a scenario like the below image:

![image](https://user-images.githubusercontent.com/10031739/30753671-9ed6791e-9fdd-11e7-94af-42c458b331a8.png)

```
using (var context = new MyContext())
{
    var blogs = context.Person.ToList();
}

```
> **It does not retrieve the inherited objects - student and instructor by default.**

> This was not the case with EF 6. 
> 
> Is there any work around for this right now.
> 
> This feature is also needed and important for lots of scenarios.

**Comment by ajcvickers** [comment] 2017-09-22 22:39
@satyajit-behera If the entities are mapped correctly, then this should work--keep in mind that EF Core does not automatically find and map derived types, so you will need to map Student and Instructor explicitly, probably by adding calls to `modelBuilder.Entity<Student>()` and `modelBuilder.Entity<Instructor>()` in OnModelCreating. If you have done this and it still doesn't work, then please post a complete code listing or project that demonstrates the issue.

**Comment by ajcvickers** [comment] 2017-09-29 18:03
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:51 UTC
Labels: closed-could-not-reproduce
