### ISSUE TITLE
Loading Related Data with Include()

### ISSUE THREAD

**Issue by wangkanai** [dotnet/efcore#14147] opened 2018-12-12 04:30 UTC
I trying to get related data loaded with this api method
```csharp
// GET: api/Department
[HttpGet]
public async Task<ActionResult<IEnumerable<Department>>> GetDepartment()
{
    var result = await _context.Departments
        .Include(d =>d.Children)
        .Where(d => d.Parent == null)                
        .ToListAsync();
    return result;
}
```
But i just end up with follow result Code 200
```
can't parse JSON.  Raw result:

[{"id":1,"parentId":null,"parent":null,"children":[{"id":2,"parentId":1
```
using the following model
```csharp
public class Department
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public int? ParentId { get; set; }
    public Department Parent { get; set; }
    public ICollection<Department> Children { get; set; }

    public int SiteId { get; set; }
    public Site Site { get; set; }

    public int DepartmentTypeId { get; set; }
    public DepartmentType DepartmentType { get; set; }
    [Required]
    public string Title { get; set; }
    public string Description { get; set; }
}
```
The full commit could be found here https://github.com/wangkanai/Organization/commit/683398c6e909cd3dc7049afc3ede66bfcf75c470
Its not that i never got this parent child relation working, i have a working model at https://github.com/wangkanai/EntityPattern/tree/master/ParentChild

Not sure what is going on, I run debug and found that data is getting load to `var result`.
![image](https://user-images.githubusercontent.com/10666633/49847097-fba2b680-fe00-11e8-831b-c6f34e419a53.png)

Its like that `IEnumerable<Department>` is NOT parsing to `ActionResult()` or something.

Platform:
- ASP.NET Core 2.2
- EF Core 2.2

**Comment by smitpatel** [comment] 2018-12-12 21:42
Did you configure your API to ignore loops?

**Comment by smitpatel** [comment] 2018-12-12 21:43
Duplicate of https://github.com/aspnet/Mvc/issues/4160

**Comment by smitpatel** [comment] 2018-12-17 23:20
@wangkanai - ReferenceLoopHandling is not something EF Core processes. It configures the Json serialization. EF just creates result on client side. Seems like you are having issues in your serialization code path rather than EF. Given ignoring loop in results works for people using serialization, try asking question on stackoverflow.

**Closed** 2022-10-16 13:43 UTC
Labels: closed-external, customer-reported
