### ISSUE TITLE
SqlConnection.Open fails and throw Login failed for user 'sa' error suddenly after upgrading Entity Framework Core from 3.1.4 to 3.1.8

### ISSUE THREAD

**Issue by fingers10** [dotnet/efcore#22500] opened 2020-09-11 16:09 UTC
I was using `Microsoft.EntityFrameworkCore` `3.1.4` Nuget Package in my `ASP.NET Core 3.1 Web API` project to read and write to database using `TransactionScope`. I referred the [official documentation](https://docs.microsoft.com/en-us/ef/core/saving/transactions) for doing that.

Here is my code:

```c#
using (var scope = new TransactionScope(TransactionScopeOption.Required,
                new TransactionOptions { IsolationLevel = IsolationLevel.ReadCommitted }))
            {
                using (var connection = new SqlConnection(_context.Database.GetDbConnection().ConnectionString))
                {
                    connection.Open(); // ---> throws error - "Login failed for user 'sa'."

                    // Run raw ADO.NET command in the transaction
                    var command = connection.CreateCommand();
                    // updating document security in tdoc table
                    command.CommandText = query;
                    command.ExecuteNonQuery();
// --------------------- Remaining Code goes here. Removed for brevity--------------
```

Here are the Nuget Packages used.
```xml
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.4">
  <!--<PrivateAssets>all</PrivateAssets>-->
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.4" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.4" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.4">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

After updating above Nuget Packages from `3.1.4` to `3.1.8`, `connection.Open()` suddenly throws the following error.

> Login failed for user 'sa'

After some googling I found that I need to add `Persist Security Info=True;` in my connection string.

My Previous Connection String:

`Server=ServerName;Database=DatabaseName;UID=sa;PWD=password;`

I changed this to:

`Persist Security Info=True;Data Source=ServerName;Initial Catalog=DatabaseName;User Id=sa;Password=password`

But now I get the below error:

> A network-related or instance-specific error occurred while
> establishing a connection to SQL Server. The server was not found or
> was not accessible. Verify that the instance name is correct and that
> SQL Server is configured to allow remote connections. (provider:
> Shared Memory Provider, error: 40 - Could not open a connection to SQL
> Server)

when I execute `context.DbSet.FirstOrDefault()`.

Please assist on how to fix this breakage.

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer 3.1.8
Target framework: ASP.NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by smitpatel** [comment] 2020-09-11 16:15
Duplicate of https://github.com/dotnet/efcore/issues/22083

**Comment by ErikEJ** [comment] 2020-09-11 16:53
What is your server name, and which port does it listen on. Then use ip,port or hostname,port

**Closed** 2022-10-16 18:40 UTC
Labels: customer-reported
