### ISSUE TITLE
Object reference not set to an instance of an object. at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<BufferAllAsync>d__12.MoveNext()

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/efcore#8026] opened 2017-03-29 15:56 UTC
I'm awaiting a handful of EF Core Queries and I'm seeing this exception

```
Exception message:Object reference not set to an instance of an object
Stack trace:
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<BufferAllAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryContext.<RegisterValueBufferCursorAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<BufferlessMoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__6`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.<_SingleOrDefault>d__123`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DealBank.Data.DealBankRepository.<SaveDealAsync>d__4.MoveNext() in C:\Users\mdepouw\Source\Repos\MyProject\MyCode.cs:line 75
```

![image](https://cloud.githubusercontent.com/assets/14079228/24463769/b7b8f798-1475-11e7-8522-5dc069919615.png)

### Steps to reproduce
Turn off MARS and await mutliple queries I **think** will reproduce it.

MultipleActiveResultSets=false;

```c#
var task1 = GetDataAsync();
var task2 = GetData2Async();

await Task.WhenAll(task1, task2);
```

### Further technical details
EF Core version: (found in project.json or packages.config) neither of these files exist for me...
![image](https://cloud.githubusercontent.com/assets/14079228/24463884/0fdadafe-1476-11e7-89f5-a4d2d598b1a7.png)

Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10
IDE: VS 2017

**Comment by ajcvickers** [comment] 2017-03-29 16:56
@spottedmahn In general, multiple concurrent use of the same context instance is not supported. (For some pure async query cases the two async queries will be serialized, but this was done more for internal use than as something applications can rely on.)

What is interesting here is that the exception you are getting is not what I would expect to see. Do you see the same exception if you await the first call before starting the next call?

**Comment by spottedmahn** [comment] 2017-03-29 17:39
@ajcvickers interesting, thanks.

No I don't.  If I await them one by one all is good.  That's how I originally had the code but I'm trying to speed it up now...

Also, if I set MultipleActiveResultSets=true the exception goes away.

**Comment by ajcvickers** [comment] 2017-03-31 23:12
@spottedmahn Can you provide a complete code listing or project to reproduce this issue? It seems like something is going wrong here, but without knowing what calls are being made on the context and what the queries look like it is very hard to debug.

**Comment by spottedmahn** [comment] 2017-04-03 14:32
@ajcvickers I'll give it a try.  Can you point me in the direction of good scaffolding prj for EF core?

**Comment by ajcvickers** [comment] 2017-04-04 16:14
@spottedmahn Not sure what kind of scaffolding you mean. You can generate a DbContext and entity types from a database using the EF command line tools. There are some docs here: https://docs.microsoft.com/en-us/ef/core/get-started/full-dotnet/existing-db

**Comment by ajcvickers** [comment] 2017-04-12 18:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by frasdav** [comment] 2017-04-18 06:37
@ajcvickers We've run in to this problem too - I'm happy to try to build a console app to replicate if you can re-open the issue?

**Comment by ajcvickers** [comment] 2017-04-18 17:02
@frasdav Yes, a repro would be great!

**Comment by frasdav** [comment] 2017-04-25 11:29
Okay, demo console app attached. On the first run through when the database is created, there's no issue. On the second and subsequent execution, however, I get an AggregateException with an inner NullReferenceException from Microsoft.EntityFrameworkCore.Relational.

[EFCoreNullReferenceExceptionApp.zip](https://github.com/aspnet/EntityFramework/files/954851/EFCoreNullReferenceExceptionApp.zip)

**Comment by ajcvickers** [comment] 2017-04-25 16:20
@frasdav Thanks for providing the repro. What is the exception message and stack trace that you see?

Note that the code in your repro is not supported:
```C#
var applesTask = context.Apples.FindAsync(1);
var bananasTask = context.Bananas.FindAsync(1);
var orangesTask = context.Oranges.FindAsync(1);

Task.WhenAll(applesTask, bananasTask, orangesTask).Wait();
```
EF doesn't support multiple concurrent tasks on the same context instance. Each find call needs to be awaited for this to be valid code. The only reason for wanting a repro for this issue is that the exception and stack trace were not what we expected and we wanted to investigate why.

**Comment by frasdav** [comment] 2017-04-26 14:52
I get an AggregateException, with one inner:

Message:  Object reference not set to an instance of an object.
Source:  Microsoft.EntityFrameworkCore.Relational
Stack trace:

`at Microsoft.EntityFrameworkCore.Query.RelationalQueryContext.<RegisterValueBufferCursorAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<BufferlessMoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__6`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.<_FirstOrDefault>d__82`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()`

Appreciate it's unsupported, just thought you might want to know about the NullRefException. :)

**Comment by spottedmahn** [comment] 2017-04-26 15:51
hey @ajcvickers - please see this [sample code](https://github.com/spottedmahn/EfCoreException).

I'm not getting the same stack trace as above but I see the same issue.  If I perform a single await first and then use Task.WhenAll I don't get an exception.  If I perform only a Task.WhenAll I get an exception.

I'm wondering if I'm getting a different stack trace b/c this sample uses 1.1.1 and the above used 1.1.0?

**Comment by ajcvickers** [comment] 2017-04-26 16:09
@spottedmahn Thanks. 

Note for triage: When I ran the code I got an error from SqlClient. I had thought that the check for concurrent access would help for these cases, but recent discussions indicate that it is only done on non-async code paths. I wonder if there is a way we can extend it to work with async paths so that people get a better message that this is not supported. I thought we had something like this in EF6, but I may be remembering incorrectly.

**Comment by spottedmahn** [comment] 2017-04-26 20:40
@ajcvickers np.  Sounds like you were able to generate: System.InvalidOperationException: 'BeginExecuteReader requires an open and available Connection. The connection's current state is closed.'. 
 
Were you able to generate 'System.NullReferenceException: 'Object reference not set to an instance of an object.'?

**Comment by v1n1akabozo** [comment] 2017-07-28 06:42
@ajcvickers 

If i understood correctly what you said then the proper way to do this would be

```
var applesTask = await context.Apples.FindAsync(1);
var bananasTask = await context.Bananas.FindAsync(1);
var orangesTask = await context.Oranges.FindAsync(1);
```

But isn't that the same as

```
var applesTask = context.Apples.Find(1);
var bananasTask = context.Bananas.Find(1);
var orangesTask = context.Oranges.Find(1);
```

I might be missremembering this, but on the full .NET Framework we used to be able to make concurrent calls to the dbcontext without having to await them right away. As it is in the EF Core we can either chose to sacrifice memory and get more instances of the db context to make this concurrent calls or just work synchronously?

**Comment by anpete** [comment] 2017-07-28 17:33
@v1n1akabozo This should work in 2.0. I.e. You can spawn several tasks and await all of them via something like Task.WhenAll.

**Closed** 2022-10-16 10:59 UTC
Labels: closed-duplicate
