### ISSUE TITLE
EF CORE 2.2 : cannot be tracked because another instance with the key value '{Id: x}' is already being tracked

### ISSUE THREAD

**Issue by offirpeer** [dotnet/efcore#21056] opened 2020-05-27 16:10 UTC
I try to update `Business` entity and I get the above error.

Same question in sof:
https://stackoverflow.com/questions/62046852/ef-core-2-2-cannot-be-tracked-because-another-instance-with-the-key-value-id

**Startup.cs**
```
services.AddDbContext<gringoContext>(options =>
                {
                    options.UseSqlServer(_config.GetConnectionString("DefaultConnection"));
                    options.EnableSensitiveDataLogging(true);
                });
```

**Context:**
```
  modelBuilder.Entity<Businesses>(entity =>
            {
                entity.Property(e => e.BookingUrl).HasMaxLength(2083);

                entity.Property(e => e.CategoryId).HasColumnName("CategoryID");

                entity.Property(e => e.CityId).HasColumnName("CityID");

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Email)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.FacebookUrl).HasMaxLength(2083);

                entity.Property(e => e.FriendlyAddress).HasMaxLength(500);

                entity.Property(e => e.GoogleAddress)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.GooglePlaceId)
                    .HasColumnName("GooglePlaceID")
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.InstagramUrl)
                    .HasMaxLength(2083)
                    .IsUnicode(false);

                entity.Property(e => e.Lat)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Long)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(400);

                entity.Property(e => e.OwnerUserId).HasColumnName("OwnerUserID");

                entity.Property(e => e.Phone).HasMaxLength(100);

                entity.Property(e => e.SiteUrl).HasMaxLength(2083);

                entity.Property(e => e.Status).HasDefaultValueSql("((1))");

                entity.Property(e => e.UpdateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Whatsapp).HasMaxLength(100);

                entity.Property(e => e.YoutubeIframeEmbedded).IsUnicode(false);

                entity.HasOne(d => d.Category)
                    .WithMany(p => p.Businesses)
                    .HasForeignKey(d => d.CategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Businesses_Catgeories");

                entity.HasOne(d => d.City)
                    .WithMany(p => p.Businesses)
                    .HasForeignKey(d => d.CityId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Companies__CityI__4C8B54C9");

                entity.HasOne(d => d.OwnerUser)
                    .WithMany(p => p.Businesses)
                    .HasForeignKey(d => d.OwnerUserId)
                    .HasConstraintName("FK__Companies__Owner__4B973090");

                entity.HasOne(d => d.StatusNavigation)
                    .WithMany(p => p.Businesses)
                    .HasForeignKey(d => d.Status)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Businesse__Statu__58520D30");
            });
```

**BusinessController.cs**
  ```
Businesses business = await _businessUnitOfWork.BusinessRepository.GetByID(bid);
                    business.Name = "Test";
//This line throws the error.
 _businessUnitOfWork.BusinessRepository.Update(business);
                    await _businessUnitOfWork.SaveChangesAsync();
```

**BaseRespository.cs**
```
public abstract class BaseRespository<TEntity> : IBaseRepository<TEntity> where TEntity : class, IIdentifier

    {
        protected readonly gringoContext context;

        protected BaseRespository(gringoContext context)
        {
            this.context = context;
        }

 public virtual void Update(TEntity entity)
        {
            context.Set<TEntity>().Update(entity);
        }
}
```

**Comment by ajcvickers** [comment] 2020-05-27 17:57
@offirpeer EF Core 2.2 is [out-of-support](https://docs.microsoft.com/en-us/ef/core/what-is-new/). Please update to 3.1 and if you're still running into an issue, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by yang-er** [comment] 2020-06-05 10:18
How's `await _businessUnitOfWork.BusinessRepository.GetByID(bid);` working?

If you made it something like
```
from n in dbContext.News
where n.Id == bid
select new News
{
    Id = n.Id,
    Content = n.Content
}
```
it will fault.

**Comment by ajcvickers** [comment] 2020-06-05 15:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:27 UTC
Labels: closed-could-not-reproduce, customer-reported
