### ISSUE TITLE
When using ValueObjects avoid column cast in query

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#24232] opened 2021-02-23 10:52 UTC
I have the following code that I use to search for a user by his name:
```
public class User
{
	public long Id { get; set; }
	public string Name { get; set; }	
}

var dbUser = (from user in context.Users
			  where EF.Functions.Like(user.Name, "Mike")
			  select user).ToList();
```

and it translates to the following 

```
SELECT [u].[Id], [u].[Name]
FROM [Users] AS [u]
WHERE [u].[Name] LIKE N'Mike'
```

When I change though the Name property to be a ValueObject like below:

```
public class User
{
	public long Id { get; set; }
	public Name Name { get; set; }	
}
  
public class Name : ValueObject
{
	public string Value { get; }

	protected Name()
	{
	}

	private Name(string value)
	{
		Value = value;
	}

	public static Result<Name> Create(string name)
	{
		name = (name ?? string.Empty).Trim();

		if (string.IsNullOrEmpty(name))
			return Result.Failure<Name>("Name should not be empty");

		if (name.Length > ValidationDefinitions.NAME_FIELD_LENGTH)
			return Result.Failure<Name>("Name is too long");

		return Result.Success(new Name(name));
	}

	public static implicit operator string(Name name)
	{
		return name.Value.Trim();
	}

	public static explicit operator Name(string name)
	{
		return Create(name.Trim()).Value;
	}

	protected override IEnumerable<object> GetEqualityComponents()
	{
		yield return Value;
	}
}
```
and in my dbcontext I have

```
modelBuilder.Entity<User>(entity =>
            {
                entity.Property(p => p.Name)
                    .IsRequired()
                    .HasConversion(p => p.Value, p => Name.Create(p).Value)
                    .HasMaxLength(128);
            });
```
the query is translated to

```
SELECT [u].[Id], [u].[Name]
FROM [Users] AS [u]
WHERE CAST([u].[Name] AS nvarchar(max)) LIKE N'%Mike%'
```

It tries to cast Name as nvarchar(MAX). 
How can I avoid the extra cast that it does? 

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Win 10
IDE: Visual Studio 2019 16.8.5

**Comment by ajcvickers** [comment] 2021-02-23 17:58
@smitpatel to find dupe.

**Comment by smitpatel** [comment] 2021-02-23 18:06
Duplicate of #10434

**Comment by pantonis** [comment] 2021-02-23 18:11
The original issue is 3+ years old. Is there any workaround to this?

**Comment by smitpatel** [comment] 2021-02-23 18:14
In this case, value converter is not providing any value since the type is string anyway. Work-around would be to use string property directly.

**Comment by pantonis** [comment] 2021-02-23 18:22
:D So the workaround is to change the business model instead of fixing the EF issue? :) what about cases with more complex value object?

**Comment by smitpatel** [comment] 2021-02-23 18:28
A more complex value object which contains multiple scalar properties are going to use individual properties and doesn't face this issue.

**Comment by pantonis** [comment] 2021-02-24 09:22
@smitpatel Creating an invariant even for a single property IMHO is a better way of working with ValueObjects and Entities. Is this thing gonna be fixed or you don't plan to fix it in the near future?

**Comment by ajcvickers** [comment] 2021-02-24 16:20
@pantonis #10434 is in the backlog milestone but labeled with `consider-for-current-release`. This means that it is currently a stretch goal for EF Core 6.0.

**Comment by pantonis** [comment] 2021-02-25 06:47
Hope to have this in .NET 6 because as I described in large queries this might cost performance

**Closed** 2022-10-16 19:24 UTC
Labels: customer-reported
