### ISSUE TITLE
NullReferenceException for optional one to many relation between entities

### ISSUE THREAD

**Issue by sorina-vasiliu** [dotnet/efcore#9757] opened 2017-09-11 08:20 UTC
Describe what is not working as expected.
I have an optional one to many relation between two entities (code first approach) :

```C#
 public class User
{       [Key]
        public int Id { get; set; }
        public int? RoleId { get; set; }
        public Role Role { get; set; }
}

 public class Role
 {     [Key]
        public int Id { get; set; }
        public List<User> Users { get; set; }
        public List<RolePermission> Permissions { get; set; }
}

public class RolePermission
{
     public int RoleId { get; set; }
     public int PermissionId { get; set; }
     public Role Role { get; set; }
     public Permission Permission { get; set; }
}

public class Permission
{    [Key]
      public int Id { get; set; }
      public string Name { get; set; }
}
```
For retrieving a user by id from database I use the following Linq :
```C#
 var user = await this.context.Users.Include(item => item.Role)
                                             .ThenInclude(r => r.Permissions)
                                             .ThenInclude(perm => perm.Permission)
                                             .SingleOrDefaultAsync(item => item.Id == id);
```
and for retrieving all the users 
```C#
var users= this.context.Users.Include(item => item.Role)
                                                .ThenInclude(role => role.Permissions)
                                                .ThenInclude(perm => perm.Permission)
                                                .ToListAsync();
```
The problem is that when the foreign key is null ( in my case RoleId on User is null) I receive the NullReferenceException error ( see below the stack-trace). If the foreign key has value no exception is  thrown.  As a workaround I can use "SingleOrDefault()"/ "ToList()" because the synchronous methods seems to work ok, but I would prefer to use the asynchronous ones.
Is this a EF core issue or I'm doing something wrong?        

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```
System.NullReferenceException: Object reference not set to an instance of an object. 
 at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.<_IncludeAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.<_ExecuteAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<SingleOrDefault_>d__381`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ATOM.Persistance.Repositories.UserRepository.<GetUser>d__4.MoveNext() in E:\netRepos\Atom\ATOM\Persistance\Repositories\UserRepository.cs:line 90

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10
Data Base Server : Sql Server Express
IDE: (e.g. Visual Studio 2017)

**Comment by smitpatel** [comment] 2017-09-11 20:46
@sorina-vasiliu - Can you provide some sample data in which above is throwing. I am trying to reproduce the issue but it is passing for me.

**Comment by jahead** [comment] 2017-09-12 01:59
I have the same issue with a large list of includes and the only way I could solve it was using the synchronous method.

**Comment by smitpatel** [comment] 2017-09-12 19:48
Duplicate of #9038

**Closed** 2022-10-16 11:48 UTC
Labels: closed-duplicate
