### ISSUE TITLE
DefaultIfEmpty with parameter throws if entity type has a shadow key

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#13409] opened 2018-09-24 22:35 UTC
See `SimpleQueryCosmosSqlTest.Default_if_empty_top_level_arg`
>System.ArgumentNullException : Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate) in C:\enlistments\Universe\EntityFramework\src\EFCore\ChangeTracking\Internal\IdentityMap.cs:line 227
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.AddOrUpdate(InternalEntityEntry entry) in C:\enlistments\Universe\EntityFramework\src\EFCore\ChangeTracking\Internal\IdentityMap.cs:line 170
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer& valueBuffer, ISet`1 handledForeignKeys) in C:\enlistments\Universe\EntityFramework\src\EFCore\ChangeTracking\Internal\StateManager.cs:line 305
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityTrackingInfo.StartTracking(IStateManager stateManager, Object entity, ValueBuffer& valueBuffer) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\EntityTrackingInfo.cs:line 77
   at Microsoft.EntityFrameworkCore.Query.QueryContext.StartTracking(Object entity, EntityTrackingInfo entityTrackingInfo) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\QueryContext.cs:line 159
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.<>c__DisplayClass18_0`2.<_TrackEntities>b__0(TOut result) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\AsyncLinqOperatorProvider.cs:line 226
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 109
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\AsyncLinqOperatorProvider.cs:line 163
   at System.Collections.Generic.AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncEnumerableHelpers.cs:line 48
   at System.Collections.Generic.AsyncEnumerableHelpers.ToArray[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncEnumerableHelpers.cs:line 16
   at Microsoft.EntityFrameworkCore.TestUtilities.QueryAsserter`1.AssertQuery[TItem1](Func`2 actualQuery, Func`2 expectedQuery, Func`2 elementSorter, Action`2 elementAsserter, Boolean assertOrder, Int32 entryCount, Boolean isAsync) in C:\enlistments\Universe\EntityFramework\src\EFCore.Specification.Tests\TestUtilities\QueryAsserter.cs:line 306
   at Microsoft.EntityFrameworkCore.Cosmos.Sql.Query.SimpleQueryCosmosSqlTest.Default_if_empty_top_level_arg(Boolean isAsync) in C:\enlistments\Universe\EntityFramework\test\EFCore.Cosmos.Sql.FunctionalTests\Query\SimpleQueryCosmosSqlTest.cs:line 248
--- End of stack trace from previous location where exception was thrown ---

**Comment by ajcvickers** [comment] 2018-10-02 00:01
Discussed in triage. We should not track entities returned from queries if they didn't come from the database. Doing so results in entities that are in the unchanged state but for which there is (possibly) no row in the database. However, this doesn't preclude returning an entity instance that is _already_ tracked, but this must be explicitly done before executing the query.

**Comment by smitpatel** [comment] 2019-11-21 17:45
Duplicate of #17783

**Closed** 2022-10-16 13:32 UTC
Labels: closed-duplicate, punted-for-3.0, area-query
