### ISSUE TITLE
When using SplitToTable  cannot use json column

### ISSUE THREAD

**Issue by anhuizf1** [dotnet/efcore#30874] opened 2023-05-11 07:06 UTC
```C#
      modelBuilder.Entity<T1>(entity =>
            {
                entity.ToTable("stb053" )
                .SplitToTable("stb031", tb =>
               {
                   tb.Property(c => c.EntityID).HasColumnName("EntityID");
                   tb.Property(c => c.Address);
                   tb.Property(c => c.PostCode);
                   tb.Property(c => c.Chief);
                   tb.Property(c => c.ToContact);
                   tb.Property(c => c.TelephoneNo);
                   tb.Property(c => c.CountryCode);
                   tb.Property(c => c.Reserved);
                   tb.Property(c => c.Reserved2);
               })
                .SplitToTable("stb054", tb =>
                {
                    tb.Property(c => c.EntityID).HasColumnName("EntityID");
                    tb.Property(c => c.TreeID).HasColumnName("TreeID");
                    tb.Property(c => c.Statistic01);
                    tb.Property(c => c.Statistic02);
                    tb.Property(c => c.Statistic03);
                    tb.Property(c => c.Statistic04);
                    tb.Property(c => c.Statistic05);
                    tb.Property(c => c.Statistic06);
                    tb.Property(c => c.Statistic07);
                    tb.Property(c => c.Statistic08);
                }).OwnsOne(e => e.GenAttr,
                tb => {
                    tb.ToJson();
                    tb.Property(c => c.Name);
                    tb.Property(c => c.UserCode);
                });
            });


[PrimaryKey("EntityID", "TreeID")]
    public class T1
    {
        public short TreeID { get; set; } = 0;
        public int LeafID { get; set; }
        public int NameID { get; set; }
        public string NodeName { get; set; }
        public int Father { get; set; }
        public float UDFOrdinal { get; set; }
        public byte NodeDepth { get; set; }
        public byte LeafStatus { get; set; }
        public int CSTRoot { get; set; }
        public int IconID { get; set; }
        public int EntityID { get; set; }
        public string Code { get; set; }
        public DateTime CreatedTime { get; set; } = DateTime.Now;
        public int Leaf01 { get; set; }
        //json column
        public GenT1Attr GenAttr { get; set; }= null!;

       //split table1
        public string Address { get; set; } = "";
        public string PostCode { get; set; } = "";
        public string Chief { get; set; } = "";
        public string ToContact { get; set; } = "";
        public string TelephoneNo { get; set; } = "";
        public string CountryCode { get; set; } = "";
        public string Reserved { get; set; } = "";
        public int Reserved2 { get; set; }
       
      //split table2
        public long Statistic01 { get; set; }
        public long Statistic02 { get; set; }
        public long Statistic03 { get; set; }
        public long Statistic04 { get; set; }
        public long Statistic05 { get; set; }
        public long Statistic06 { get; set; }
        public long Statistic07 { get; set; }
        public long Statistic08 { get; set; }

    }

  //json object define
    public class GenT1Attr
    {
        public string Name { get; set; }
        public string UserCode { get; set; }
    }


var list = db.T1List.Where(c => c.TreeID == 1  ).ToList();
```

error:
```
System.InvalidOperationException:“Translation of 'EF.Property<GenT1Attr>(EntityShaperExpression: 
    IRAP.Test.T1
    ValueBufferExpression: 
        ProjectionBindingExpression: EmptyProjectionMember
    IsNullable: False
, "GenAttr")' failed. Either the query source is not an entity type, or the specified property does not exist on the entity type.”
```

### Include provider and version information

EF Core version: 7.05
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework:  NET 6.0
Operating system: win11 
IDE:  Visual Studio 2022 17.4

**Comment by ajcvickers** [comment] 2023-05-16 11:24
Duplicate of #28442

**Closed by ajcvickers** 2023-05-16 11:24 UTC
Labels: customer-reported
