### ISSUE TITLE
Does not generate a primary key of type string, when there is a many-to-many relationship

### ISSUE THREAD

**Issue by niqel** [dotnet/efcore#21032] opened 2020-05-24 17:33 UTC
I have a data model that uses a many-to-many relationship, I leave the code here

```C#
public class CodePostal
    {
        public string Code { get; set; }
        public virtual List<PostalSettlement> PostalSettlements { get; set; }
    }

public class Settlement
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public SettlementType SettlementType { get; set; }
        public Municipality Municipality { get; set; }
        public int IdMunicipality { get; set; }
        public virtual List<PostalSettlement> PostalSettlements { get; set; }
        public virtual List<Address> Addresses { get; set; }
    }

public class PostalSettlement
    {
        public CodePostal CodePostal { get; set; }
        public string IdCodePostal { get; set; }
        public Settlement Settlement { get; set; }
        public int IdSettlement { get; set; }
    }
```

**the third class is to simulate a many-to-many relationship according to the documentation**

and I use Fluent Api

```C#
public class MapCodePostal : IEntityTypeConfiguration<CodePostal>
    {
        public void Configure(EntityTypeBuilder<CodePostal> builder)
        {
            builder.ToTable("CodePostals");
            builder.HasKey(x => x.Code);
            builder.Property(c => c.Code).ValueGeneratedNever();
        }
    }

public class MapSettlement : IEntityTypeConfiguration<Settlement>
    {
        public void Configure(EntityTypeBuilder<Settlement> builder)
        {
            builder.ToTable("Settlements");
            builder.Property(x => x.Name).IsRequired();
            builder.HasKey(x => x.Id);

            builder.HasOne(x => x.Municipality)
                .WithMany(x => x.Settlements)
                .HasForeignKey(x => x.IdMunicipality);

            builder.HasOne(x => x.SettlementType)
                .WithMany(x => x.Settlements)
                .HasForeignKey(x => x.IdMunicipality);
        }
    }

public class MapPostalSettlement : IEntityTypeConfiguration<PostalSettlement>
    {
        public void Configure(EntityTypeBuilder<PostalSettlement> builder)
        {
            builder.ToTable("PostalSettlements");
            builder.HasKey(x => new { x.IdCodePostal, x.IdSettlement });

            builder.HasOne(x => x.CodePostal)
                .WithMany(x => x.PostalSettlements)
                .HasForeignKey(x => x.IdCodePostal);

            builder.HasOne(x => x.Settlement)
                .WithMany(x => x.PostalSettlements)
                .HasForeignKey(x => x.IdSettlement);
        }
    }
```

### InvalidOperationException: The entity type 'CodePostal' requires a primary key to be defined. If you intended to use a keyless entity type call 'HasNoKey()'.

I am not sure if it is an error in my code or an incident, but could you please support me.
Beforehand thank you very much

EF Core version:3.1.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlLite 3.1.4)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment] 2020-05-27 16:29
@niqel I don't see anything obviously wrong here. Make sure your code is actually calling `Configure` on your EntityTypeConfigurations, If that doesn't help, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-06-08 16:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:26 UTC
Labels: closed-could-not-reproduce, customer-reported
