### ISSUE TITLE
Paging with UseRowNumberForPaging in SqlServer fails to orderby rows

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/efcore#13137] opened 2018-08-28 08:15 UTC
Microsoft.EntityFrameworkCore.SqlServer Version : 2.1.2

Query generates 
``` sql
SELECT [t0]....
FROM(
SELECT ... , ROW_NUMBER() OVER(ORDER BY [a].[nAA] DESC, [a].[nEggrafaID]) AS [__RowNumber__]
FROM ...
WHERE ... 
<here is missing the order by>
) AS [t0]
WHERE ([t0].[__RowNumber__] > 0) AND ([t0].[__RowNumber__] <= (0 + 10))
<or here is missing order by __RowNumber__>
```

Our code is doing a custom select expression and then is doing paging. 
OrderBy Expression is before the Select Expression.  

Is there a workaround to add this missing orderby ?

**Comment by xrkolovos** [comment] 2018-08-28 08:28
We use Sql Server 2008 R2

**Comment by smitpatel** [comment] 2018-08-28 16:57
What is the issue here? `ORDER BY` is moved to `ROW_NUMBER` function and you don't need to specify ORDER BY clause in SQL. (at least accordingly to T-SQL documentation of `ROW_NUMBER()`)

**Comment by xrkolovos** [comment] 2018-08-30 08:06
In sqlserver2016 this works fine. In sqlServer 2008R2 this orderby is not respected. If you add this orderby i suggested it works only.

**Comment by smitpatel** [comment] 2018-08-30 20:34
@xrkolovos - Can you submit a repro project which demonstrate what you are seeing?

**Comment by ajcvickers** [comment] 2018-09-07 15:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2018-11-14 23:03
@xrkolovos If you are still using RowNumberForPaging, could you please comment on issue #13959 and let us know why?

**Comment by jfmjason** [comment] 2018-11-19 14:35
Same issue encountered. I'm using UseRowNumberForPaging for compatibility issue in sql server 2008 in my .net core 2.1 application.
When using below code,  it returns list of entity ordered by ROWNUMBER in the database table instead of returning  data ordered by empcode.

query = entity;

 query.OrderBy(i => i.EmpCode.Trim()).Skip((page - 1) * pagesize).Take(pagesize);

**Closed** 2022-10-16 13:27 UTC
Labels: closed-could-not-reproduce, customer-reported
