### ISSUE TITLE
When I  do group by,  linq query does not working

### ISSUE THREAD

**Issue by hakankaya56** [dotnet/efcore#18653] opened 2019-10-30 12:09 UTC
**This my code** =>  
```C#
using (var tigerContext = new TigerContext())
{
    var stockRemaningList = 
        from stocks in tigerContext.Stock
        join item in tigerContext.ItemsSum on stocks.LOGICALREF equals item.STOCKREF  into tempJoin 
        from leftJoined in tempJoin.DefaultIfEmpty()
        group leftJoined by stocks into grouped
        select new StocksRemaning
        {
            StockCode = grouped.Key.CODE,
            StockRef = grouped.Key.LOGICALREF,
            StockName = grouped.Key.NAME,
            ActualStock = grouped.Sum(i=>i.ONHAND)
        };
    return stockRemaningList.ToList();
}
```

**this is my error** =>  
```
The LINQ expression 'GroupBy<TransparentIdentifier<Stock, ItemsSum>, <>f__AnonymousType10<Stock>, ItemsSum>(
    source: LeftJoin<Stock, ItemsSum, int, TransparentIdentifier<Stock, ItemsSum>>(
        outer: DbSet<Stock>, 
        inner: DbSet<ItemsSum>, 
        outerKeySelector: (s) => s.LOGICALREF, 
        innerKeySelector: (ı) => ı.STOCKREF, 
        resultSelector: (s, ı) => new TransparentIdentifier<Stock, ItemsSum>(
            Outer = s, 
            Inner = ı
        )), 
    keySelector: (ti) => new { stocks = ti.Outer }, 
    elementSelector: (ti) => ti.Inner)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

**Comment by smitpatel** [comment] 2019-10-30 21:19
@hakankaya56 - The reason it fails to translate is, your query contains grouping by an entity which is not scalar which cannot be used in SQL GROUP BY clause. Please refer to our [documentation](https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators#groupby) for more details.
In order to evaluate this in server, you can rewrite your query to select only scalar columns you need in your results.
```C#
using (var tigerContext = new TigerContext())
{
    var stockRemaningList = 
        from stocks in tigerContext.Stock
        join item in tigerContext.ItemsSum on stocks.LOGICALREF equals item.STOCKREF  into tempJoin 
        from leftJoined in tempJoin.DefaultIfEmpty()
        group leftJoined by new { stocks.CODE, stocks.LOGICALREF, stocks.NAME } into grouped
        select new StocksRemaning
        {
            StockCode = grouped.Key.CODE,
            StockRef = grouped.Key.LOGICALREF,
            StockName = grouped.Key.NAME,
            ActualStock = grouped.Sum(i=>i.ONHAND)
        };
    return stockRemaningList.ToList();
}
```

**Comment by ajcvickers** [comment] 2019-11-01 17:23
@maumar to look for duplicate.

**Comment by maumar** [comment] 2019-11-01 18:17
dupe of #17653

**Closed** 2022-10-16 14:53 UTC
Labels: closed-duplicate, customer-reported
