### ISSUE TITLE
EF.Property called with wrong property name when using System.Linq.Dynamic.Core OrderBy on multiple columns

### ISSUE THREAD

**Issue by appimpact** [dotnet/efcore#19838] opened 2020-02-08 00:38 UTC
We have been using System.Linq.Dynamic.Core for quite some time to generate various dynamic queries. Since upgrade to EF Core 3.0.0/3.1.1, all application queries using .OrderBy("column1,column2 ASC") have stopped to work, with the following exception being thrown: 

"EF.Property called with wrong property name".

We have tried to revert back to .NET Core 2.2 / EF Core 2.2.6, and code works as expected.

### Steps to reproduce

An example of code that generates this error can be found on this GitHub repository:
https://github.com/App-Impact-Labs/ISSUE-EfCorePropertyCalledWithWrongPropertyName

The code above will create database, seed basic data and generate an error that can be further inspected.

### Further technical details

EF Core version: 3.0.0 - 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0 - 3.1
Operating system: Windows 10 x64, Windows Server 2016 x64
IDE: e.g. Visual Studio 2019 16.3

**Comment by smitpatel** [comment] 2020-02-08 00:48
Duplicate of #18904

**Comment by appimpact** [comment] 2020-02-08 00:52
Hi,

The workaround you've provided in https://github.com/dotnet/efcore/issues/18904 is not useful to us as we are using System.Linq.Dynamic.Core, so we cannot really expand the query the way you have specified.

Can you provide workaround for this particular issue, or at least ETA on when appropriate fix can be expected?

**Comment by appimpact** [comment] 2020-02-08 01:16
@smitpatel 

Ok, it seems it works well. We will do more testing and let you know if we notice anything unusual.

Thank you!

**Closed** 2022-10-16 18:10 UTC
Labels: customer-reported
