### ISSUE TITLE
How to avoid exeption "Unable to translate collection subquery..." when writing query with group by

### ISSUE THREAD

**Issue by majbo** [dotnet/efcore#24886] opened 2021-05-12 13:59 UTC
`Articles` and `ArticleTags` both have a property `ReplicationOrder`. I need all Articles with the MIN `ReplicationOrder` of the Article and all its ArticleTags and I need to further select the Tags for every article as a concatenated string.

``` 
            var q1 = context.Articles.Select(a => new {a.Id, a.ReplicationOrder})
                .Union(context.ArticleTags.Select(at => new {Id = at.ArticleId, at.ReplicationOrder}));

            var q2 = q1
                .GroupBy(p => p.Id, p => p.ReplicationOrder, (p, grp) => new {Id = p, ReplicationOrder = grp.Min()});

            var q4 = context.Articles
                .Join(q2, p => p.Id, q => q.Id,
                    (p, s) => new Article
                    {
                        Id = p.Id,
                        Label = p.Label,
                        ArticleTags = p.ArticleTags,
                        ReplicationOrder = s.ReplicationOrder
                    });

            var result = q4.Select(p => new
                {
                    p.Id,
                    p.Label,
                    p.ReplicationOrder,
                    Tags = string.Join(", ", p.ArticleTags.Select(at => at.Tag.Label))
                })
``` 

### Error
Unable to translate collection subquery in projection since the parent query doesn't project key columns of all of it's tables which are required to generate results on client side. This can happen when trying to correlate on keyless entity or when using 'Distinct' or 'GroupBy' operations without projecting all of the key columns.

### Steps to reproduce
I created a simple app here: (https://github.com/majbo/EfGroupingTest)
Execute the unit tests. Their both doing the same, except for the projection `Tags = string.Join(", ", p.ArticleTags.Select(at => at.Tag.Label))` that is absent at the first test.

### Further technical details
EF Core version: 5.0.6
Database provider: (e.g. Microsoft.EntityFrameworkCore.Sqlite)
Target framework: (e.g. .NET 5.0)
Operating system: Windows 10
IDE: Rider 2021.1.2

**Comment by smitpatel** [comment] 2021-08-17 21:34
Duplicate of #22049

Given repro works on 6.0 preview7

**Closed** 2022-10-16 19:34 UTC
Labels: customer-reported
