### ISSUE TITLE
Calls to `SaveChangesAsync` do not update the `EntityFrameworkEventSource` values

### ISSUE THREAD

**Issue by meggima** [dotnet/efcore#23604] opened 2020-12-07 16:11 UTC
## Actual behavior

We use the new `EntityFrameworkEventSource` to collect metrics about EF Core performance.
However, the counters `save-changes-per-second` and `total-save-changes` constantly show a value of `0` for our application.

## Expected behavior

We call `await dbContext.SaveChangesAsync()` in our code multiple times per second. So, we expect both values to be greater than zero.

## Possible cause

I digged a bit into the source code and suspect that there's a bug here:

https://github.com/dotnet/efcore/blob/243357978bfa9b457e5e5011ea13648c46d8a1e8/src/EFCore/ChangeTracking/Internal/StateManager.cs#L1115

In the `async` overload of `SaveChanges` the call to the EventSource is missing.  Compare https://github.com/dotnet/efcore/blob/243357978bfa9b457e5e5011ea13648c46d8a1e8/src/EFCore/ChangeTracking/Internal/StateManager.cs#L1097 

## Environment information

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: e.g. .NET 5.0
Operating system: Docker (Linux containers)
IDE: Visual Studio Enterprise 2019 16.8.2

**Comment by roji** [comment] 2020-12-07 16:24
Oops, you're right. Would you like to submit a PR adding the missing logging?

**Comment by meggima** [comment] 2020-12-07 16:36
> Oops, you're right. Would you like to submit a PR adding the missing logging?

Sure.

**Comment by roji** [comment] 2020-12-08 22:25
While preparing the patch for 5.0, I've come across other issues with event counters, am flagging this as a dup of #23630.

**Comment by roji** [comment] 2020-12-08 22:25
Duplicate of #23630

**Closed** 2022-10-16 19:14 UTC
Labels: customer-reported
