### ISSUE TITLE
Query execution crashes with InvalidOperationException when using calculation with nested sum

### ISSUE THREAD

**Issue by ice1e0** [dotnet/efcore#15624] opened 2019-05-05 10:06 UTC
When I do a calculation with nested data in a `new { .. }` section like this:

```c#
var query = from entry in dataSet.AsQueryable()
	select new
	{
		Id = entry.Id,
		Amount = entry.Amount,
		SettledAmount = entry.Settlements.Sum(en => en.Amount), // this works
		OpenAmount = entry.Amount - entry.Settlements.Sum(en => en.Amount) // this causes the crash
	};
var result = query.FirstOrDefault();
```

The the query execution crashes. I assume that in such cases the `entry.Settlements` field is not interpreted by the SQL query so the `.Sum(...)` function throws this error.

I would expect that this would work or give an error which is easier to understand.

### Exception
```
Exception message: System.InvalidOperationException: 'Das Objekt mit Nullwert muss einen Wert haben.' (sorry, it's German. The text says that an object which has a null value must have a value)
Stack trace:
   bei System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   bei lambda_method(Closure , QueryContext , ValueBuffer )
   bei Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   bei Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IShaper<TOut>.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   bei Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   bei Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   bei Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   bei lambda_method(Closure )
   bei Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   bei Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   bei System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   bei Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   bei Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   bei Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   bei System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
[...]
```

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 8.1
IDE: Visual Studio 2019 16.0.2

**Comment by smitpatel** [comment] 2019-05-06 16:50
Possibly `entry.Amount` is null. Can you verify data in database and types on client side?

**Comment by ajcvickers** [comment] 2019-05-13 16:07
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ice1e0** [comment] 2019-07-15 14:31
Confirmed, works now with:
```
OpenAmount = entry.Amount - (entry.Settlements.Sum(en => en.Amount) ?? 0)
```

**Closed** 2022-10-16 14:20 UTC
Labels: closed-could-not-reproduce, customer-reported
