### ISSUE TITLE
"Multiple Cascade Paths" issue on Oracle and Postgresql

### ISSUE THREAD

**Issue by hasankaplan-github** [dotnet/efcore#24574] opened 2021-04-03 05:53 UTC
Hi,

I have two entites and they are related with each other by two `one to many` relation. When I create a migration, migration is successfuly created. However at run time i get `Unable to determine the relationship represented by navigation 'Path.FromState' of type 'State'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.` exception. 
I have two `one to many` relation in 'OnModelCreating' which is given below. As far as I know the `multiple cascade paths` issue is a MsSql issue. Oracle does not have this kind of issue. Why do I get this kind of exception at runtime, is this a bug or not? Could you give some information about that? Thank you.

EntityFramework Core version: 5.0.4
Database: Oracle 19c or Postgresql

Entities:
```
   public class Path
   {
        public Guid Id { get; set; }
        public Guid FromStateId { get; set; }
        public State FromState { get; set; }
        public Guid ToStateId { get; set; }
        public State ToState { get; set; }


    }

public class State
    {
        public Guid Id { get; set; }
        public ICollection<Path> FromPaths { get; set; }
        public ICollection<Path> ToPaths { get; set; }
    }
```

Relation Configurations in 'OnModelCreating':
```
         builder.HasOne(x => x.FromState)
                .WithMany(x => x.FromPaths)
                .HasForeignKey(x => x.FromStateId)
                .OnDelete(DeleteBehavior.Cascade);

            builder.HasOne(x => x.ToState)
               .WithMany(x => x.ToPaths)
               .HasForeignKey(x => x.ToStateId)
               .OnDelete(DeleteBehavior.Cascade);
```

_**Note: If I delete 'FromPaths' and 'ToPaths' properties and empty the WithMany side of the relations, there is no exception at runtime.**_

**Comment by roji** [comment] 2021-04-03 16:56
@hasankaplan-github I've pasted your model into a simple console application, and it seems to work just fine with Npgsql. Can you please try the below and confirm what your issue is?

<details>
<summary>Working code sample</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

public class BlogContext : DbContext
{
    public DbSet<Path> Paths { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseNpgsql(@"Host=localhost;Username=test;Password=test")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Path>(builder =>
        {
            builder.HasOne(x => x.FromState)
                .WithMany(x => x.FromPaths)
                .HasForeignKey(x => x.FromStateId)
                .OnDelete(DeleteBehavior.Cascade);

            builder.HasOne(x => x.ToState)
                .WithMany(x => x.ToPaths)
                .HasForeignKey(x => x.ToStateId)
                .OnDelete(DeleteBehavior.Cascade);
        });
    }
}

public class Path
{
    public Guid Id { get; set; }
    public Guid FromStateId { get; set; }
    public State FromState { get; set; }
    public Guid ToStateId { get; set; }
    public State ToState { get; set; }
}

public class State
{
    public Guid Id { get; set; }
    public ICollection<Path> FromPaths { get; set; }
    public ICollection<Path> ToPaths { get; set; }
}
```

**Comment by ajcvickers** [comment] 2021-04-16 14:13
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:30 UTC
Labels: closed-could-not-reproduce, customer-reported
