### ISSUE TITLE
Design-time factory for Entity Framework in Azure function, pass down connection string

### ISSUE THREAD

**Issue by Bryankarlsson** [dotnet/efcore#24980] opened 2021-05-26 14:53 UTC
Hi,

I'm trying to generate migrations In my Azure function project.

I have the following project structure:

- Application
- Application.Domain
- Application.Infrastructure

I have all the EF related things in my Infrastructure layer, such as DbContext, entities, generic repository, migrations.

Im always doing like this when I create a application and want to pass down the connection string to the Infrastructure layer:

Application.Startup.cs

```C#
var client = new SecretClient(new Uri(Environment.GetEnvironmentVariable("KeyVaultUri", EnvironmentVariableTarget.Process)), new DefaultAzureCredential(), options);
var connectionString = client.GetSecret("is-database-connection").Value.Value;
builder.Services.AddDomain(connectionString);
```

Domain.Injections.cs:

```C#
    public static class Injections
    {
        public static IServiceCollection AddDomain(this IServiceCollection services, string connectionString)
        {
            services.AddTransient<ISalesItemService, SalesItemService>();        

            services.AddPersistence(connectionString);
            return services;
        }
    }
```

Infrastructure.Injections.cs:

```C#
    public static class Injections
    {
        public static IServiceCollection AddPersistence(this IServiceCollection services, string connectionString)
        {
            services.AddTransient<ISalesItemDataService, SalesItemDataService>();
            services.AddTransient(typeof(IGenericRepository<>), typeof(GenericRepository<>));

            services.AddDbContext<IOnePlmSubContext, OnePlmSubContext>(
                options => options.UseSqlServer(connectionString),
                ServiceLifetime.Transient,
                ServiceLifetime.Transient);
            return services;
        }
    }
```

This works great with regular ASP.NET applications, but now when I'm working with a Azure function project, this don't work, because I get the following error when I try to generate a migration:

> Unable to create an object of type 'OnePlmSubContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

To get rid of this error message, I have created a design-time factory, so I can start generating migrations.

But I have a problem: How can I pass down the connection string to the factory? Every example I have found, assumes that the connection string is in a appsettings.json file, but in my case, I'm retrieving the connection string from Azure Key Vault and then I pass It down to the Infrastructure layer through the Domain layer.

So how can I make my connection string available In the factory? Or Is It another way to solve this issue without using a factory and reading from appsettings.json or referencing the Infrastructure layer In the Application layer and make EF related configuration In the Startup.cs?

**Comment by ajcvickers** [comment] 2021-06-03 19:25
@Bryankarlsson What does your main method/startup code look like for your Azure Functions project?

**Comment by AndriySvyryd** [comment] 2021-06-11 23:56
cc @bricelam

**Comment by AndriySvyryd** [comment] 2021-06-11 23:57
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:35 UTC
Labels: closed-could-not-reproduce, customer-reported
