### ISSUE TITLE
EFCore.Cosmos - RequestCharge

### ISSUE THREAD

**Issue by espray** [dotnet/efcore#20514] opened 2020-04-03 15:47 UTC
Finding an operations RUs is vital for optimizing cosmos db
@AndriySvyryd how can I retrieve the RequestCharge for an operation?

-- Describe the solution you'd like --
Ability to add a CosmosRequestHandler. This can be done by `CosmosClientOptions.CustomHandlers.Add(handler)`

```
public class LoggingHandler : CosmosRequestHandler
{
  public override async Task<CosmosResponseMessage> SendAsync(CosmosRequestMessage request, CancellationToken cancellationToken)
  {
    Console.WriteLine($"{request.Method.Method} - {request.RequestUri.ToString()}");
    CosmosResponseMessage response = await base.SendAsync(request, cancellationToken);
    Console.WriteLine("Operation done");
    Console.WriteLine((int)response.StatusCode);
    return response;
  }
}
```

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.customhandlers?view=azure-dotnet#Microsoft_Azure_Cosmos_CosmosClientOptions_CustomHandlers

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.fluent.cosmosclientbuilder.addcustomhandlers?view=azure-dotnet#Microsoft_Azure_Cosmos_Fluent_CosmosClientBuilder_AddCustomHandlers_Microsoft_Azure_Cosmos_RequestHandler___

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.requesthandler?view=azure-dotnet

**Comment by ajcvickers** [comment] 2020-04-03 18:21
Duplicate of #17298

**Closed** 2022-10-16 18:19 UTC
Labels: closed-duplicate, customer-reported
