### ISSUE TITLE
2.2: Bad Error Message System.Data.SqlTypes.SqlNullValueException

### ISSUE THREAD

**Issue by NetTecture** [dotnet/efcore#19104] opened 2019-11-28 12:54 UTC
Text:

Data is Null. This method or property cannot be called on Null values."

TargetSie: get_Int32.

Problem is: I get this on an objvect with a LOT of integer fields and there is NO indication which property this happens in.

This error message should contain the name of the property that is failing to deserialize to make it easier to debug mapping errors.

The stack trace starts with:

   at System.Data.SqlClient.SqlBuffer.get_Int32()
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

and again it is not helpfull because it does not give any indication about which field is problematic.

**Comment by ajcvickers** [comment] 2019-12-02 17:22
@NetTecture Did you try using `optionsBuilder.EnableDetailedErrors()`?

**Comment by ajcvickers** [comment] 2019-12-09 18:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:58 UTC
Labels: closed-no-further-action, customer-reported
