### ISSUE TITLE
"The entity type was not found." when mixing cultures

### ISSUE THREAD

**Issue by genne** [dotnet/efcore#13318] opened 2018-09-13 13:12 UTC
If you initiate your `DbContext` on a thread with one culture (`Thread.CurrentCulture`, i.e. `en-US`), and then try to use another instance of your context using another culture (i.e. `sv-SE`), you can run into `InvalidOperationException: 'The entity type 'MyEntity' was not found. Ensure that the entity type has been added to the model.'`

It seems like the `SortedDictionary` over entity types doesn't work when you reuse it with different cultures:
https://github.com/aspnet/EntityFrameworkCore/blob/7d5488a606173df0f57da37dcab82b472fb15e45/src/EFCore/Metadata/Internal/Model.cs#L24

Perhaps you need to specify an explicit comparison method that doesn't depend on the current culture?

### Steps to reproduce
I can provide more details if needed, but example code goes something like this:

```c#
Thread.CurrentCulture = new CultureInfo("en-US");
new MyContext().Database.Migrate(); // Guess any code that initializes the model?

Thread.CurrentCulture = new CultureInfo("sv-SE");
new MyContext().Add(new MyEntity());
```

In our case `MyEntity` was called `Withdrawal`. If we renamed it to something else, i.e. `_Withdrawal`, it worked fine (we have 71 other entities in the same context, they all work fine).

```
Exception message:
System.InvalidOperationException
  HResult=0x80131509
  Message=The entity type 'Withdrawal' was not found. Ensure that the entity type has been added to the model.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateEntry(Object entity)
   at Microsoft.EntityFrameworkCore.DbContext.EntryWithoutDetectChanges[TEntity](TEntity entity)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity](TEntity entity)
```

### Further technical details
EF Core version: 2.1.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.1

**Comment by Jupakabra** [comment] 2018-09-14 07:06
Duplicate of #12617, but this provides some additional information and examples

**Closed** 2022-10-16 13:30 UTC
Labels: customer-reported
