### ISSUE TITLE
StartsWith generates incorrect sql when DbType is AnsiStringFixedLength 

### ISSUE THREAD

**Issue by muzopraha** [dotnet/efcore#32771] opened 2024-01-10 10:53 UTC
When I call either LINQ StartsWith or EF.Functions.Like on a property, that has DbType of AnsiStringFixedLength in mappingInfo in compiled model, then parameter inside SQL query is of type char. Instead, the type of the parameter shoud be varchar.

Function in C#:
```
public async Task<int> GetCount(string prefix)
{
    return await DbContext.Parameters.AsNoTracking()
        .Where(p => p.Code.StartsWith(prefix))
        .CountAsync();
}
```

The generated SQL query:
```
exec sp_executesql N'SELECT COUNT(*)
    FROM [dbo].[Parameters] AS [p]
    WHERE [p].[Code] LIKE @__prefix_0_rewritten ESCAPE ''\''',N'@__prefix_0_rewritten char(30)',@__prefix_0_rewritten='O\_%                          '
```

SQL query I want, where __prefix_0_rewritten is type of varchar:
```
exec sp_executesql N'SELECT COUNT(*)
    FROM [dbo].[Parameters] AS [p]
    WHERE [p].[Code] LIKE @__prefix_0_rewritten ESCAPE ''\''',N'@__prefix_0_rewritten varchar(30)',@__prefix_0_rewritten='O\_%'
```

The property/column configuration: 
```
builder.Property(x => x.Code)
.HasColumnName(@"Code")
.HasColumnType("char")
.IsRequired()
.IsFixedLength()
.HasMaxLength(30)
.HasConversion<StringTrimConvertor>();

```

Custom StringTrimConverter:
```
public StringTrimConvertor() : base(v => v, v => v.TrimEnd())
{
}
```

Generated code for the property in the compiled model:
```
            var code = runtimeEntityType.AddProperty(
                "Code",
                typeof(string),
                propertyInfo: typeof(Parameters).GetProperty("Code", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Parameters).GetField("<Code>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 30,
                valueConverter: new StringTrimConvertor());
            code.TypeMapping = SqlServerStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                keyComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "char(30)",
                    size: 30,
                    dbType: System.Data.DbType.AnsiStringFixedLength),
                converter: new ValueConverter<string, string>(
                    (string v) => v,
                    (string v) => v.TrimEnd()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<string, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<string, string>(
                        (string v) => v,
                        (string v) => v.TrimEnd())));
            code.AddAnnotation("Relational:ColumnName", "Code");
            code.AddAnnotation("Relational:ColumnType", "char");
            code.AddAnnotation("Relational:IsFixedLength", true);
            code.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);
```

For now I've fixed it by adding RelationalConverterMappingHints with AnsiString DbType in the StringTrimConvertor:
```
public StringTrimConvertor() : base(v => v, v => v.TrimEnd(),
            new RelationalConverterMappingHints(dbType: DbType.AnsiString))

```

### Provider and version information

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer 8.0.0
Target framework: .NET 8.0.101
Operating system: Windows 10 22H2
IDE: JetBrains Rider 2023.3.2 / Visual Studio 17.8

**Comment by ajcvickers** [comment] 2024-01-16 15:48
@muzopraha I'm not able to reproduce this--see my code below. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
using (var context = new SomeDbContext())
{
    await context.Database.EnsureDeletedAsync();
    await context.Database.EnsureCreatedAsync();

    await context.SaveChangesAsync();
}

using (var context = new SomeDbContext())
{
    var prefix = "X";
    await context.Parameters.AsNoTracking()
        .Where(p => p.Code.StartsWith(prefix))
        .CountAsync();
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Data Source=localhost;Database=One;Integrated Security=True;TrustServerCertificate=true")
            //.UseNpgsql(@"server=localhost;user id=postgres;password=nedspub1;database=One")
            //.UseSqlite(@"Data Source=dat.db")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTrackingWithIdentityResolution)
            .EnableSensitiveDataLogging();

    public DbSet<Parameter> Parameters { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Parameter>().Property(x => x.Code)
            .HasColumnName(@"Code")
            .HasColumnType("char")
            .IsRequired()
            .IsFixedLength()
            .HasMaxLength(30)
            .HasConversion<StringTrimConvertor>();
    }

    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
    }
}

public class Parameter
{
    public int Id { get; set; }
    public string Code { get; set; }
}

public class StringTrimConvertor : ValueConverter<string, string>
{
    public StringTrimConvertor() : base(v => v, v => v.TrimEnd())
    {
    }
}
```

```
info: 1/16/2024 15:44:56.066 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (25ms) [Parameters=[@__prefix_0_rewritten='X%' (Size = 30) (DbType = AnsiString)], CommandType='Text', CommandTimeout='30']
      SELECT COUNT(*)
      FROM [Parameters] AS [p]
      WHERE [p].[Code] LIKE @__prefix_0_rewritten ESCAPE '\'
```

**Comment by benOneil** [comment] 2024-01-17 02:55
Assuming this is the same issue as mine (#32779), I have a [project](https://github.com/benOneil/EF8Issue) which shows the issue.

**Comment by ajcvickers** [comment] 2024-01-18 17:21
Thanks for the repro @benOneil.

Note for triage: this is a change from 7 to 8, but it's not clear to me that behavior in 7 (or without the compiled model in 8) was intended. The column is configured as a non-Unicode fixed-length string, and hence the inferred DbType is AnsiStringFixedLength. I wonder if we have some special casing somewhere that stops this happening in the non-compiled model case, since fixed-length strings are very difficult to work with.

**Comment by ajcvickers** [comment] 2024-01-25 10:00
Verified that this is fixed in 8.0.2.

**Closed by ajcvickers** 2024-01-25 10:00 UTC
Labels: customer-reported
