### ISSUE TITLE
Invalid query generated for simple group by

### ISSUE THREAD

**Issue by NitinNotebook** [dotnet/efcore#14243] opened 2018-12-24 10:32 UTC
Describe what is not working as expected.
Simple group by generating invalid query and also warning that Sum getting evaluated in local
```C#
List<int> lstShiftIds;
var efQuery = from shiftDetail in ShiftDetailSet
                          where lstShiftIds.Contains(shiftDetail.ShiftId) 
                          group shiftDetail by new { shiftDetail.ShiftId, shiftDetail.TpId } into g                          
                          select new ShiftNetAmount
                          {
                              ShiftId = g.Key.ShiftId,
                              TpId = g.Key.TpId,
                              NetAmount = g.Sum(s=> s.Jul) 
                          };
```
Exception message:
Issue 1
Above LINQ expression generates Invalid Query:
SELECT "shiftDetail"."ShiftId", "shiftDetail"."TpId", "shiftDetail"."Jul" AS "NetAmount"
FROM "ShiftDetail" AS "shiftDetail"
WHERE "shiftDetail"."ShiftId" IN (1000000, 1000100, 1000200)
GROUP BY "shiftDetail"."ShiftId", "shiftDetail"."TpId"

Column: "shiftDetail"."Jul" is not in Group By but in select

Issue 2
Sum should be evaluated on DB Server, EF core throws following warning

Microsoft.EntityFrameworkCore.Query:Warning: The LINQ expression 'Sum()' could not be translated and will be evaluated locally.

### Steps to reproduce

```c#
EF query provided above, let me know if more information is required.
```

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlLite 2.2.0
Operating system: Win 10
IDE:  Visual Studio 2017 15.9.4

**Comment by smitpatel** [comment] 2018-12-26 20:37
I am not able to reproduce the issue based on above data. The exact same query is working fine for me.
Please submit a detailed repro code which demonstrate the issue you are seeing
Repro Code:
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database


                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                var ids = new List<int> { 1, 2, 3 };
                var efQuery = from blog in db.Blogs
                              where ids.Contains(blog.Id)
                              group blog by new { blog.Id, blog.TpId } into g
                              select new NetAmountDto
                              {
                                  Id = g.Key.Id,
                                  TpId = g.Key.TpId,
                                  NetAmount = g.Sum(s => s.Jul)
                              };

                efQuery.ToList();
            }

            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        private static ILoggerFactory LoggerFactory => new LoggerFactory().AddConsole(LogLevel.Trace);

        // Declare DBSets
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                //.UseSqlite("filename=_modelApp.db")
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(LoggerFactory);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
        }
    }

    public class Blog
    {
        public int Id { get; set; }
        public int TpId { get; set; }
        public int Jul { get; set; }
    }

    public class NetAmountDto
    {
        public int Id { get; set; }
        public int TpId { get; set; }
        public int NetAmount { get; set; }
    }
}
```

Generated SQL:
```SQL
      SELECT [blog].[Id], [blog].[TpId], SUM([blog].[Jul]) AS [NetAmount]
      FROM [Blogs] AS [blog]
      WHERE [blog].[Id] IN (1, 2, 3)
      GROUP BY [blog].[Id], [blog].[TpId]
```

**Comment by nitinmahajan10** [comment] 2018-12-29 04:32
[EfCoreSample.zip](https://github.com/aspnet/EntityFrameworkCore/files/2716058/EfCoreSample.zip)

Thank you for quick response. I have attached only relevant version of the code in solution where I was able to repro. The Query printed in (debug) output window is as follows: 
SELECT "sd"."ShiftId", "sd"."TpId", "sd"."Jan", "sd"."Feb", "sd"."Mar"
FROM "ShiftDetail" AS "sd"
WHERE "sd"."ShiftId" IN (1, 2)
GROUP BY "sd"."ShiftId", "sd"."TpId"

There is difference in the code you have sent, you are doing a sum on single column I'm trying to sum multiple columns:
Your version: 
NetAmount = g.Sum(s => s.Jul)

My Version
NetAmount = g.Sum(s => s.Jul) + g.Sum(s => s.Aug)

**Comment by ajcvickers** [comment] 2019-01-04 20:13
@smitpatel to follow up.

**Comment by smitpatel** [comment] 2019-01-04 22:10
Duplicate of #14083

**Comment by smitpatel** [comment] 2019-01-04 22:11
Duplicate of #12089

**Closed** 2022-10-16 13:45 UTC
Labels: closed-duplicate, customer-reported
