### ISSUE TITLE
InvalidCastException: Unable to cast object of type 7.0.4

### ISSUE THREAD

**Issue by double-dubs** [dotnet/efcore#30506] opened 2023-03-16 13:56 UTC
I did a minor upgrade from 7.0.3 to 7.0.4 yesterday and I started getting the following error when trying to insert a new record into the database.  Through some trial and error I discovered it was not the table I was inserting into but another table that had a has one relationship to the table.  I removed that relationship and the insert worked.  I was not inserting any data into the related table.  I then rolled back to 7.0.3 and put the relationship back and it works fine again.  Something in 7.0.4 is causing an issue.  I tried commenting out most of the fields in the problematic table, but the error still occurs.  I am not able to figure out based on the error what the root cause of the issue is,

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Update.Internal.RowForeignKeyValueFactoryFactory.Create(IForeignKeyConstraint foreignKey)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKeyConstraint.<>c.<GetRowForeignKeyValueFactory>b__28_0(ForeignKeyConstraint constraint)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKeyConstraint.GetRowForeignKeyValueFactory()
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.AddForeignKeyEdges()
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.TopologicalSort(IEnumerable`1 commands)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.<BatchCommands>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__106.MoveNext()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__110.MoveNext()
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__64.MoveNext()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__64.MoveNext()
   <Upsert>d__3.MoveNext()

This exception was originally thrown at this call stack:

Inner Exception 1:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 2:
InvalidCastException: Unable to cast object of type 'System.Func`3[System.Nullable`1[System.Guid],System.Nullable`1[System.Guid],System.Boolean]' to type 'System.Func`3[System.Guid,System.Guid,System.Boolean]'.

EF Core version: 7.0.3/7.0.4
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 7.0
Operating system: Win 11
IDE: Visual Studio 2022 17.5.2

**Comment by ajcvickers** [comment] 2023-03-29 19:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-03-29 19:38 UTC
Labels: customer-reported
