### ISSUE TITLE
Allow specifying a namespace for scaffolding

### ISSUE THREAD

**Issue by CamiloTerevinto** [dotnet/efcore#9977] opened 2017-10-05 13:31 UTC
Currently, the `dotnet ef dbcontext scaffold` command does not support a parameter to specify the namespace of the generated entities. 

I have a project whose only purpose is to scaffold databases using parameters passed from the command line, and it'd be better if the generated entities did not have the project's namespace.

Ideally, I'd expect something like this:

```
$"ef dbcontext scaffold \"{connectionString}\" Microsoft.EntityFrameworkCore.SqlServer -d -c {contextName} -o \"{outputPath}\" -f -n {generationNamespace}"
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 
IDE: Visual Studio 2017 15.3

**Comment by smitpatel** [comment] 2017-10-05 16:52
Duplicate of #9723

**Closed** 2022-10-16 11:53 UTC
