### ISSUE TITLE
The call is ambiguous between the following methods or properties [ Entity framework core ] [ OnModelCreating ]

### ISSUE THREAD

**Issue by MbarkT3STO** [dotnet/efcore#24355] opened 2021-03-09 18:47 UTC
I use `ef core`, inside y `dbcontext` class I overrided the `onModelCreating` method to configure one property in a class to be auto-increment in `sql server`

**My DbContext class:**

    public class AppDbContext:IdentityDbContext<AppUser>
    {
        public AppDbContext(DbContextOptions options) : base(options)
        {
            
        }
    
        public AppDbContext()
        {
            
        }
    
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
    
            builder.Entity<Service>().Property(service => service.ID).UseIdentityColumn(1, 1);
    
        }
    
    
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<Service> Services { get; set; }
    }

If you notice that my DbContext class is inherited from `IdentityDbContext` because I use `Identity`.

**The problem:**
The problem is visual studio show me an error

**Error:**

    Severity	Code	Description	Project	File	Line	Suppression State
    Error	CS0121	The call is ambiguous between the following methods or properties: 'Microsoft.EntityFrameworkCore.OraclePropertyBuilderExtensions.UseIdentityColumn<TProperty>(Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<TProperty>, int, int)' and 'Microsoft.EntityFrameworkCore.SqlServerPropertyBuilderExtensions.UseIdentityColumn<TProperty>(Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder<TProperty>, int, int)'

[Error Screenshot 1][1] 
[Error Screenshot 2][2]

**Additional info:**
I reference another project in my solution this project will play the repository role, and he prepared to work with `SqlServer`, `Oracle` and `MySQL`.

The project I depend on is my own project, and it is open source [that is the repository link][3]

**Please any help to fix this issue ?**

  [1]: https://i.stack.imgur.com/gMHWR.png
  [2]: https://i.stack.imgur.com/jlueX.png
  [3]: https://dev.azure.com/MBARK-Solutions/MBRepoCore

**Comment by roji** [comment] 2021-03-09 20:33
Duplicate of #16686

**Comment by roji** [comment] 2021-03-09 20:34
If you're using multiple providers which have the concept of identity columns, you're going to have to fully-qualify the method call; so instead of calling it like an extension method, call it like a static method:

```c#
OraclePropertyBuilderExtensions.UseIdentityColumn(
    builder.Entity<Service>().Property(service => service.ID), 1,1);
```

**Closed** 2022-10-16 19:27 UTC
Labels: customer-reported
