### ISSUE TITLE
Single row query throws System.OutOfMemoryException

### ISSUE THREAD

**Issue by Spaceman1861** [dotnet/efcore#9206] opened 2017-07-19 01:29 UTC
Hi Folks,

Im getting an exception when running a non async a query  on a single row with a column that contains a 20 mb xml object.

I was previously using async but went to non async due the size of the column and the way data is transfered for large cols.

Thanks for taking a look :)

```
Exception message:
Exception of type 'System.OutOfMemoryException' was thrown.
Stack trace:
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown. at
 System.String.CtorCharArrayStartLength(Char[] value, Int32 startIndex, Int32 length) at
 System.Data.SqlClient.TdsParser.TryReadSqlStringValue(SqlBuffer value, Byte type, Int32 length, Encoding encoding, Boolean isPlp, TdsParserStateObject stateObj) at
 System.Data.SqlClient.TdsParser.TryReadSqlValue(SqlBuffer value, SqlMetaDataPriv md, Int32 length, TdsParserStateObject stateObj) at
 System.Data.SqlClient.SqlDataReader.TryReadColumnInternal(Int32 i, Boolean readHeaderOnly) at
 System.Data.SqlClient.SqlDataReader.GetValues(Object[] values) at
 Microsoft.EntityFrameworkCore.Storage.Internal.UntypedRelationalValueBufferFactory.Create(DbDataReader dataReader) at
 Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer) at
 Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state) at
 Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state) at 
 Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, TState state) at 
 Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext() at
 Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext() at 
 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source) at
 lambda_method(Closure , QueryContext ) at 
 Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass20_0`1.<CompileQueryCore>b__0(QueryContext qc) at
 Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) at 
 Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) at
 System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source) at 
 SomeNameSpace.DataModule.Repository`2.Get(Expression`1 where) in /opt/atlassian/pipelines/agent/build/src/Modules/SomeNameSpace.DataModule/Repository.cs:line 445 at 
 SomeNameSpace.IntegrationServerModule.Services.IntegrationService.<>c__DisplayClass16_0.<SetResponseMessageAsync>b__0() in /opt/atlassian/pipelines/agent/build/src/Modules/SomeNameSpace.IntegrationServerModule/Services/IntegrationService.cs:line 287 at
 System.Threading.Tasks.Task`1.InnerInvoke() at
 System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at 
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at
 SomeNameSpace.IntegrationServerModule.Services.IntegrationService.<SetResponseMessageAsync>d__16.MoveNext() in /opt/atlassian/pipelines/agent/build/src/Modules/SomeNameSpace.IntegrationServerModule/Services/IntegrationService.cs:line 287 --- End of stack trace from previous location where exception was thrown --- at 
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at 
 SomeNameSpace.IntegrationServerModule.Services.IntegrationService.<MessageResponseAsync>d__15.MoveNext() in /opt/atlassian/pipelines/agent/build/src/Modules/SomeNameSpace.IntegrationServerModule/Services/IntegrationService.cs:line 261 --- End of stack trace from previous location where exception was thrown --- at 
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at
 SomeNameSpace.IpApi.Integration.Controllers.IntegrationController.<MessageResponseAsync>d__4.MoveNext() in /opt/atlassian/pipelines/agent/build/src/SomeNameSpace.IpApi.Integration/Controllers/IntegrationController.cs:line 63 --- End of stack trace from previous location where exception was thrown --- at
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at 
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at
 Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext() --- End of stack trace from previous location where exception was thrown --- at
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at
 Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext() --- End of stack trace from previous location where exception was thrown --- at 
 Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context) at
 Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at
 Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
```

### Steps to reproduce
```c#

// How the query is run
// _entitySet.Where(row => row.id = 1).FirstOrDefault();


// context setup
public class IntegrationServerDataContext : DbContext, IDataContext
{
    private readonly IConfiguration _configuration;
    private readonly IEnumerable<IDataContextProvider> _contextProviders;
    private readonly IHostingEnvironment _env;

    public IntegrationServerDataContext(IHostingEnvironment env, IConfiguration configuration, IEnumerable<IDataContextProvider> contextProviders)
    {
        _env = env;
        _configuration = configuration;
        _contextProviders = contextProviders;

        Database.SetCommandTimeout(600);
    }

    public new DbSet<TEntity> Set<TEntity>() where TEntity : class
    {
        return base.Set<TEntity>();
    }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
    {
        string connectionString;

        switch (_env.EnvironmentName)
        {
            case EnvironmentType.IntegrationTest:

                options.EnableSensitiveDataLogging();
                connectionString = _configuration.GetConnectionString("IntegrationTestConnection");
                break;

            default:

                connectionString = _configuration.GetConnectionString("DefaultConnection");
                break;
        }

        options.UseSqlServer(
            connectionString,
            optionsBuilder => optionsBuilder
                .MaxBatchSize(1000)
                .CommandTimeout(600)
                .EnableRetryOnFailure()
        ).ConfigureWarnings(
            warnings => warnings.Log(RelationalEventId.QueryClientEvaluationWarning)
        );
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        foreach (var provider in _contextProviders)
        {
            provider.OnModelCreating(modelBuilder);
        }
    }
}
```

### Further technical details
EF Core version: 1.1.2
Database Provider: Azure P1
Operating system: Azure App service Standard: 1 Large

**Comment by smitpatel** [comment] 2017-07-19 01:54
The error is coming from SqlClient. Can you test against pure ADO.Net code and see if that works?

**Comment by Spaceman1861** [comment] 2017-07-19 03:15
I bashed up this console app. It runs fine.

```c#
using System;
using System.Data.SqlClient;

namespace ConsoleApp1
{
    public class Program
    {
        static void Main()
        {
            Console.WriteLine("start");

            const string connectionString =
                "Server=tcp:REDACTED;Initial Catalog=REDACTED;Persist Security Info=False;User ID=REDACTED;Password=REDACTED;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";

            const string queryString =
                "SELECT id, [RequestXml], [ResponseXml] from [IntegrationQueues] WHERE id = 34517";

            using (var connection = new SqlConnection(connectionString))
            {
                var command = new SqlCommand(queryString, connection);
                try
                {
                    connection.Open();
                    var reader = command.ExecuteReader();
                    while (reader.Read())
                    {
                        Console.WriteLine("\t{0}\t{1}\t{2}",
                            reader[0], reader[1], reader[2]);
                    }
                    connection.Close();
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
                Console.ReadLine();
            }
        }
    }
}
```

**Comment by Spaceman1861** [comment] 2017-07-19 03:16
@smitpatel sorry forgot to tag you see above :)

**Comment by Spaceman1861** [comment] 2017-07-24 01:29
As a work around we have actually decided to go with the ado connector for now. Still very interested in fixing this for entity tho.

**Comment by smitpatel** [comment] 2017-08-01 00:26
@Spaceman1861 - Can you share a repro code which demonstrate above issue?

You would need to provide a small app using similar model & querying. A sql script to insert some sample data which is large enough to show error. & details about your SqlServer instance in Azure. There are various things involved here so it would be hard to reproduce the error unless all parameters are matched up exact same.

**Comment by Spaceman1861** [comment] 2017-08-01 02:09
@smitpatel ill put it my list and get it to you as soon as possible

**Comment by ajcvickers** [comment] 2017-09-08 18:07
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:12 UTC
Labels: closed-could-not-reproduce
