### ISSUE TITLE
Default value forced when converting an EXISTING string column to be non-nullable

### ISSUE THREAD

**Issue by timker** [dotnet/efcore#31595] opened 2023-08-31 03:08 UTC
I'm adding a non nullable string property to an existing and it forces the default value to be ''
However, if I'm creating a table from scratch (with the property), there is no default value.

There are two issue with this:

1. .HasDefaultValue(null) doesn't work, and this is no .DisableDefaultValue()

2. You database schema could different depending in the migration path you took.

It is also awkward to remove the default value,
I generally try to avoid modifying generated add migration code.
The only "pure cli way" i can find is to add a migration .HasDefaultValue('') and then add another removing  .HasDefaultValue('')
this works.... (is there a better way?)

### Include your code

```C#
using Microsoft.EntityFrameworkCore;
Console.WriteLine("Welcome");
/*
 steps
 * dotnet ef migrations add InitialCreate

 * Uncomment 
     //public string Name { get; set; } 
   in ExampleEvolution

 * dotnet ef migrations add AddRequiredNamePropertyAfterTableCreation
 
Notice:
       Observe ExampleTable & ExampleEvolution are the same
       ExampleTable.Name has no default value
       ExampleEvolution.Name has a default Value: ''

 */



public class BloggingContext : DbContext
{

    public DbSet<ExampleTable> ExampleTable { get; set; }

    public DbSet<ExampleEvolution> ExampleEvolution { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder options)  => options.UseSqlServer($"");
}

public class ExampleTable
{
    public int Id { get; set; }
    public string Name { get; set; }
}


public class ExampleEvolution
{
    public int Id { get; set; }

    // uncomment for second migration
    // public string Name { get; set; }
}


```

**Comment by bricelam** [comment] 2023-08-31 21:14
Duplicate of #25899

**Closed** 2023-09-05 17:09 UTC
Labels: closed-duplicate, customer-reported
