### ISSUE TITLE
SqlLite in-memory database to retain while app is running

### ISSUE THREAD

**Issue by Ciantic** [dotnet/efcore#5086] opened 2016-04-15 19:47 UTC
I need to use sqllite in-memory database while the app is running, right now it closes the connection after each call and the database is lost. This is useful for testing, but not so useful when one needs to have persistent sqllite in-memory database.

If I use in-memory connection string for SQLLite:

``` C#
options.UseSqlite("Data Source=:memory:");
```

Then my init code fails:

``` C#
public class InitDatabase: IInitDatabase {
    private readonly ApplicationDbContext db;
    public InitDatabase(ApplicationDbContext _db) {
        db = _db;
    }
    public void Init() {
        db.Database.EnsureCreated();
        db.Add(new ApplicationUser {
            Email = "test@example.com",
            UserName = "test"
        });
        db.SaveChanges();
    }
}

public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory) {
    // ...
    app.ApplicationServices.GetService<IInitDatabase>().Init();
}
```

According to other issue #4922 it closes the connection to database after EnsureCreated and then the memory is empty again.

My code works correctly with filebased SQLLite like this:

``` C#
options.UseSqlite("Data Source=some.db");
```

**Comment by ajcvickers** [comment] 2016-04-15 19:56
Looks like a dupe of #4922

**Comment by Ciantic** [comment] 2016-04-15 19:59
@ajcvickers sorry about that, thing is "sqllite memory" gives no open issues! Weird fulltext search.

**Comment by Ciantic** [comment] 2016-04-16 05:17
@bricelam I reopened my issue #5086 and renamed it to mean what I meant: I want to have in-memory SqlLite database to persist while the app is running.

**Comment by Ciantic** [comment] 2016-04-16 05:18
I reopen this, since what I want is a bit different: to persist in-memory database while app is running.

**Comment by Ciantic** [comment] 2016-04-16 09:53
Found a solution to persistent in-memory SqlLite database, it was simple after all:

```c#

public class Startup
{
	private SqliteConnection inMemorySqlite;
	
	public void ConfigureServices(IServiceCollection services)
	{ 
		inMemorySqlite = new SqliteConnection("Data Source=:memory:");
		
		// ... 
		services.AddDbContext<ApplicationDbContext>(options => {
			options.UseSqlite(inMemorySqlite);
		});
	}
}
```

**Comment by amir734jj** [comment] 2019-11-27 15:54
`_sqliteConnection.Open();` is needed when data-source is "in-memory".

**Closed** 2022-10-16 09:36 UTC
