### ISSUE TITLE
Generate enums inside the db with migrations

### ISSUE THREAD

**Issue by JerkerPihl** [dotnet/efcore#21143] opened 2020-06-05 07:29 UTC
**Lot of applications need to have a database that stand on it owns legs aka it have to readble and understable from any other db-worker** . An EF core coder should not be the only one.  It can from other types of statistical tool (that the developers cant or not allowed to help) or even third party DBAs that need to have more information when doing DBA work.

Tried to google if there is something like this already created for the EF but it seems to be talked about but not implemented.
There is a lot of own written solutions to this but there would be great if this is also implemented inside migrations so the data has not be written before/besides/after migrations. 

Value Conversions is not enough, because it creates magicnumbers inside the database.

It should be possible to save an enum directly to the database where it store values and keys and maps with PK/FK to the tables where it being used. If a change is being done to the enum it should be shown in an migration.

**Comment by ajcvickers** [comment] 2020-06-05 15:10
@JerkerPihl Can you be more explicit about what you mean by, "save an enum directly to the database?" Please post some example C# entity types using the enum and the corresponding database schema you would like to see created.

**Comment by ajcvickers** [comment] 2020-06-15 16:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:28 UTC
Labels: closed-could-not-reproduce, customer-reported
