### ISSUE TITLE
Exception when scaffolding SQLite database with FTS tables

### ISSUE THREAD

**Issue by Starkie** [dotnet/efcore#13528] opened 2018-10-06 10:16 UTC
Hi!
 
I detected that when trying to scaffold an existing SQLite database with [Full-Text Search tables](https://www.sqlite.org/fts3.html), the process fails with the following message:
```
Exception message: System.ArgumentException: The string argument 'storeTypeName' cannot be empty.
Stack trace: 
at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingInfo..ctor(String storeTypeName)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(String storeTypeName)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ScaffoldingTypeMapper.FindMapping(String storeType, Boolean keyOrIndex, Boolean rowVersion)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.GetTypeScaffoldingInfo(DatabaseColumn column)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitColumn(EntityTypeBuilder builder, DatabaseColumn column)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitColumns(EntityTypeBuilder builder, ICollection`1 columns)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String namespace, String language, String contextDir, String contextName, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir,String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Steps to reproduce
I prepared a little project to repro the issue, including a `test.db` with the tables: [SqliteScaffold.zip](https://github.com/aspnet/EntityFrameworkCore/files/2452903/SqliteScaffold.zip)

To prepare the database, I created an empty DB and used the following commands:

```sqlite
CREATE VIRTUAL TABLE data USING fts3();
```
Then, tried to create the scaffold:
```bash
$ dotnet ef dbcontext scaffold "DataSource=test.db" Microsoft.EntityFrameworkCore.Sqlite
```

### Workaround
I found a little workaround for this problem: exporting every individual table with the '--table' parameter, except those FTS tables. But I guess this isn't an ideal solution for bigger schemas.

```bash
$ dotnet ef dbcontext scaffold "DataSource=test.db" Microsoft.EntityFrameworkCore.Sqlite --table Test
```

### Further technical details
EF Core version: 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Ubuntu 18.04.1 LTS and Windows 10
IDE: Visual Studio Code 1.27.2

**Comment by ajcvickers** [comment] 2018-10-08 18:53
Duplicate of #13531

**Closed** 2022-10-16 13:34 UTC
Labels: closed-duplicate, customer-reported
