### ISSUE TITLE
Scaffold-DbContex: Provide an option to exclude connection string in DbContext

### ISSUE THREAD

**Issue by doggy8088** [dotnet/efcore#19218] opened 2019-12-07 12:40 UTC
When scaffolding a DbContext class, it always generate connection string in the `OnConfiguring()` method. 

```cs
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    if (!optionsBuilder.IsConfigured)
    {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
        optionsBuilder.UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=ContosoUniversity;Trusted_Connection=True;MultipleActiveResultSets=true");
    }
}
```

That cause an warning when compiling the project and we are always have to remove it manually. It will be better if `dotnet-ef` and `Scaffold-DbContex` can add another option to not generating it.

I'd like to suggest add a `-ExcludeConnectionString` option to the CLI.

```sh
dotnet ef dbcontext scaffold "Server=(localdb)\MSSQLLocalDB;Database=ContosoUniversity;Trusted_Connection=True;MultipleActiveResultSets=true" Microsoft.EntityFrameworkCore.SqlServer -o Models -ExcludeConnectionString
```

**Comment by roji** [comment] 2019-12-07 13:06
Duplicate of #10432

**Closed** 2022-10-16 18:00 UTC
Labels: closed-duplicate, customer-reported
