### ISSUE TITLE
Namespace and dotnet ef dbcontext scaffold 

### ISSUE THREAD

**Issue by RCRoederHPE** [dotnet/efcore#15421] opened 2019-04-20 00:00 UTC
I found it annoying that you cannot specify the default Namespace. Any solution? I can clean it up afterwords. But i get a build failed.

dotnet ef dbcontext scaffold "server=DEV07; Database=ProjectsNow.Schedule; Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -o Models\Schedule -c dbScheduleContext -f -d --use-database-names  --context-dir Data

**Comment by ajcvickers** [comment] 2019-04-21 23:04
Duplicate of #9723

**Closed** 2022-10-16 14:18 UTC
Labels: customer-reported
