### ISSUE TITLE
Multi-tenancy filter used in a composite key cannot be updated

### ISSUE THREAD

**Issue by herme063** [dotnet/efcore#19554] opened 2020-01-10 13:17 UTC
We have made a change recently to use multi-tenancy property as part of a primary key. Originally, we would set this property right before we call SaveChanges() (by overriding it).

This no longer works since once models are tracked, we can no longer update part of the composite key. So how do we make this work?

I would like to avoid having to set this manually in each repository.

**Comment by ajcvickers** [comment] 2020-01-10 23:48
@herme063 Please post a small, runnable project that demonstrates the change in behavior so that we can investigate.

**Comment by ajcvickers** [comment] 2020-01-17 17:21
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by herme063** [comment] 2020-01-23 14:43
[CompositeKey.zip](https://github.com/dotnet/efcore/files/4103604/CompositeKey.zip)

I have Id + TenantId as key. TenantId has a custom value generator. I can add a new entity, but when it comes to updating an existing, I get an error on SaveChanges().

**Comment by AndriySvyryd** [comment] 2020-01-31 23:08
@herme063 You need to set TenantId before updating:
```C#
var entry = dbContext.Entry(updatedEntity);
entry.Property<int>("TenantId").CurrentValue = tenantId;
entry.State = EntityState.Modified;
```

**Comment by herme063** [comment] 2020-02-01 00:43
Is there a way to do this generically? Currently I have to override Update, UpdateRange, Add, AddRange...and all the methods for attaching an entity.

**Closed** 2022-10-16 18:05 UTC
Labels: closed-no-further-action, customer-reported
