### ISSUE TITLE
Alter Identity is always added to migrations

### ISSUE THREAD

**Issue by overdravila** [dotnet/efcore#20971] opened 2020-05-15 18:06 UTC
Every time I create a migration, it adds an AlterColumn statement to change the Identity column of a property, which i have not modified. If you then try to do Update Database, it will fail, since it needs to recreate the table, and Entity Framework does not support that. Also, dropping the table is not an option, since I have data there which I can't remove. It always happen with the same entity, but it has happened with several different ones in the past.  In order for me to be able to update the database with any migration, I need to manually remove that piece of code from the migration itself. 

### Steps to reproduce

Add a new migration

### Code snippets
Generated migration file
![image](https://user-images.githubusercontent.com/4548159/82081815-3539ba00-96a4-11ea-9b31-5ebf0cb2ad19.png)

Entity 
![image](https://user-images.githubusercontent.com/4548159/82081843-3f5bb880-96a4-11ea-895c-8e3f30c7ddee.png)

DbContext
![image](https://user-images.githubusercontent.com/4548159/82081954-64e8c200-96a4-11ea-9c33-e4c6c96371ab.png)
![image](https://user-images.githubusercontent.com/4548159/82081980-6fa35700-96a4-11ea-99ed-c078bb5f2212.png)

### Exception

![image](https://user-images.githubusercontent.com/4548159/82081708-06234880-96a4-11ea-8681-92b78d6a0bad.png)

### Further technical details

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system: Windows 10
IDE: VS Code

**Comment by ajcvickers** [comment] 2020-05-18 16:18
@andresargos Is it your intention to generate an Identity column for PersonTypeID? (The code has `ValueGeneratedOnAdd` which would indicate an Identity column, but a fixed set of values in the enum, which would be unusual for an Identity column.

**Comment by andresargos** [comment] 2020-05-18 16:27
Yes, I want to generate an identity column for PersonTypeID. I want it to be auto incremental if  I add a new record on the database, but I want it to start with the data from those enums. However, this also happens randomly sometimes for other tables, where it adds an AlterColumn for an identity field I am not touching.

**Comment by ajcvickers** [comment] 2020-05-18 22:29
@andresargos I have not been able to reproduce this. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by andresargos** [comment] 2020-05-18 22:31
How should I post this? Is a link to a folder in drive okay?

**Comment by ajcvickers** [comment] 2020-05-18 23:07
@andresargos Generally people just attach the small, runnable project to this issue.

**Comment by andresargos** [comment] 2020-05-18 23:19
@ajcvickers Great, I am keeping my EF context and models in a separate project to the rest of the web api, so here's the complete EF project I am working on. I think you may need to change the context connection string. 

[ExpressMapApi.Data.zip](https://github.com/dotnet/efcore/files/4647376/ExpressMapApi.Data.zip)

**Comment by ajcvickers** [comment] 2020-05-19 21:34
I was able to reproduce this (on 3.1.4 and 5.0.0 preview 4). It appears to be caused by an enum property mapped to an Identity column.

**Comment by andresargos** [comment] 2020-05-19 22:03
So, the recommendation would be to not use enumerations mapped on identity columns, correct? Do you think it doesn't make any sense to set that column as Identity?

**Comment by ajcvickers** [comment] 2020-05-19 22:36
@andresargos This is a bug--it should work. As a workaround I would just delete the unneeded changes in the generated migrations.

**Comment by andresargos** [comment] 2020-05-20 00:10
Yeah, that's what I've kept doing. Hope it gets fixed. 

Thanks!

**Comment by smitpatel** [comment] 2020-06-01 18:02
Just wondering why am I assigned to this issue @ajcvickers ?

**Comment by bricelam** [comment] 2020-08-25 18:24
Note, it is ***not*** currently possible to mark an enum property as IDENTITY.
``` cs
modelBuilder.Entity<PersonType>().Property(r => r.PersonTypeID).UseIdentityColumn();
```
> Identity value generation cannot be used for the property 'PersonTypeID' on entity type 'PersonType' because the property type is 'PersonTypes'. Identity value generation can only be used with signed integer properties.

**Comment by ajcvickers** [comment] 2020-08-25 18:26
@bricelam What happens if you just mark it as ValueGenerated.OnAdd?

**Comment by bricelam** [comment] 2020-08-25 18:27
A non-IDENTITY column is created. Not sure what SaveChanges does.

**Comment by bricelam** [comment] 2020-08-25 18:29
*But*, there is a bug here in that we don't mark the property in the snapshot as non-IDENTITY. We need to do this because when we use the underlying type in the snapshot, ValueGenerated.OnAdd suddenly means IDENTITY which is why we get a diff every time.

**Comment by bricelam** [comment] 2020-08-25 18:42
I'll update the snapshot to look like this (note, there's no provider-specific Fluent API for this)

```cs
b.Property<int>("PersonTypeID")
    .ValueGeneratedOnAdd()
    .HasColumnType("int")
    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);
```

**Comment by bricelam** [comment] 2020-08-25 18:43
In triage, let's discuss whether we should enable enum IDENTITY properties.

**Comment by JeremyLikness** [comment] 2020-09-04 17:32
@roji ping to track possible duplicate

**Comment by bricelam** [comment] 2020-09-08 17:26
Duplicate of https://github.com/dotnet/efcore/issues/11970

**Closed** 2022-10-16 18:25 UTC
Labels: customer-reported
