### ISSUE TITLE
Scenario of code first against existing legacy database

### ISSUE THREAD

**Issue by MontyGvMC** [dotnet/efcore#15725] opened 2019-05-15 15:03 UTC
Describe what is not working as expected.

When using EFC one does not only have database first and code first. Sometimes the database is old & the database layout should be reused and recreated with EFC.

Therefor one would recreate the database using the code first approach with brings a completly new database with the exact same layout as the old database (plus the __EFMigrationHistory table).

Then running the database against the existing database it will fail with table already exists.

From that point on work gets ugly because EFC MigrationBuilder lacks support for easy things like IF TABLE EXISTS do nothing. This would allow to reuse an existing database without heavy migrations but still create the layout if it runs against a new (empty) database.

Personally I thing providing easy wrappers for adding the IF EXISTS / IF NOT EXISTS parts to the genrated SQL would enable a lot new development possiblities.

### Further technical details
EF Core version: 2.2

**Comment by ajcvickers** [comment] 2019-05-17 17:35
Triage: discuss with @bricelam

**Comment by bricelam** [comment] 2019-05-20 16:47
Duplicate of #2167?

**Closed** 2022-10-16 14:21 UTC
Labels: closed-duplicate, customer-reported
