### ISSUE TITLE
AsNoTracking returns null for NTS queries

### ISSUE THREAD

**Issue by RaminMT** [dotnet/efcore#18062] opened 2019-09-26 10:18 UTC
Hi,
We started to use `Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite` v2.2.6 in our production project in order to be able to use `Distance` method in our Linq queries and also used `.AsNoTracking()` on our query.
But after this our unit tests started to fail and after a bit debugging I noticed that using `AsNoTracking` causes the query return a result with null as points value.

### Further technical details

EF Core version: 2.2.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer in production and Microsoft.EntityFrameworkCore.InMemory in unit tests
Target framework: .NET Core 2.2
Operating system: Windows 10 1903
IDE: Rider 2019.2

**Comment by smitpatel** [comment] 2019-09-26 20:35
@RaminMT - Can you try EF Core 3.0.0 ?

**Comment by RaminMT** [comment] 2019-09-28 07:01
Yes sure, let me find a time I'll test it and will inform you

**Comment by ajcvickers** [comment] 2019-10-07 15:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:45 UTC
Labels: closed-could-not-reproduce, customer-reported
