### ISSUE TITLE
HttpGet method never returns. Hangs program.

### ISSUE THREAD

**Issue by HadiSDev** [dotnet/efcore#18581] opened 2019-10-20 10:19 UTC
### Describe the bug
When I have a HttpGet method that is supposed to return a list of DTO's it hangs after crossing the return statement. I put a breakpoint before the return statement to confirm that there are no exceptions thrown and the list from the database is returned correctly.

### To Reproduce
1. Using this version of ASP.NET Core '3.0'
2. This is my code (Simplified):
I am using:
- EFCORE 3.0
- Asp.net NewtonsoftJson

Controller: 
```C#
[HttpGet("/somethings/GetSomething")]
        public async Task<ActionResult<IEnumerable<SomeObject>>> GetSomething()
        { 
            var result = await _repository.GetSomethingFromDB().ToListAsync();
            return result;
        }
Repository:
        public IQueryable<SomeObject> GetSomethingFromDB()
        {
            var res = _context.Somethings.Include(A => A.B).ThenInclude(B => B.H)
                                          .Include(A => A.B).ThenInclude(B=> B.L)
                                          .Include(A => A.B).ThenInclude(B =>B.Q)
                                          .Select(A => new SomeObject(A));

            return res ;
        }
```
The program does not hang if I remove ".Include(A => A.B).ThenInclude(B =>B.Q)". 
But note that GetSomethingFromDB does, in fact, return the correct result both times. Program hangs after executing "return result;" statement in the Http method

### Expected behavior
Expected to return the list without hanging.

### Screenshots

###Errors
EDIT: After some time an: An unhandled exception of type 'System.StackOverflowException' occurred in System.Private.CoreLib.dll

### Additional context
Include the output of `dotnet --info`

**Comment by ajcvickers** [comment] 2019-10-24 19:07
@HadiSDev Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can fully investigate.

**Comment by HadiSDev** [comment] 2019-10-24 20:13
@ajcvickers should that include the dataset from my LocalDb? just asking :)

**Comment by ajcvickers** [comment] 2019-10-24 20:20
@HadiSDev It should be the minimal amount of code and data that we need to be able to reproduce the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-11-01 15:14
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by nivle** [comment] 2019-12-16 16:19
I am getting this error in a project, however I suspect it has something to do with reference loops, as it goes away when I remove a collection, though I was unable to repro this, cus when I made reference loop in repro, the looped data just showed up as an empty array, so idk now :D

**Closed** 2022-10-16 14:52 UTC
Labels: closed-could-not-reproduce, customer-reported
