### ISSUE TITLE
Unable to resolve service for type 'Microsoft.AspNet.Http.IHttpContextAcccessor' while attempting to activate 'NewLibrary.Models.ApplicationDbContext'.

### ISSUE THREAD

**Issue by YuriiNskyi** [dotnet/efcore#5167] opened 2016-04-25 15:46 UTC
When I'm trying to add migrations with `dnx ef migrations add Mig`, I have the following exception in console:

> Unable to resolve service for type 'Microsoft.AspNet.Http.IHttpContextAcccessor' while attempting to activate 'NewLibrary.Models.ApplicationDbContext'.

My ApplicationDbContext:

```
public class ApplicationDbContext : DbContext
{
private readonly IHttpContextAccessor _accessor;

    public ApplicationDbContext(IHttpContextAccessor accessor)
    {
        _accessor = accessor;
    }
}
```

What's the problem?

How should I correctly add dependencies to ApplicationDbContext constructor?

**Comment by rowanmiller** [comment] 2016-04-28 23:14
Duplicate of https://github.com/aspnet/EntityFramework/issues/4232. See [this comment](https://github.com/aspnet/EntityFramework/issues/4232#issuecomment-171007407) for ways to solve this. We also have https://github.com/aspnet/EntityFramework/issues/4546 to track trying to improve this area.

**Closed** 2022-10-16 09:38 UTC
