### ISSUE TITLE
adding new object with composite key deletes unrelated existing objects

### ISSUE THREAD

**Issue by unixwitch** [dotnet/efcore#20352] opened 2020-03-19 19:51 UTC
### Steps to reproduce

apologies for the long bug report; i ran into this problem in a project i'm working on, but i haven't been able to reproduce this in a simple test case so i don't have any self-contained code to attach.  i've included the database schema, EF objects and the relevant C# code.

the project is an ASP.NET Core application dealing with forms containing questions and answers.  the application needs to be able to create a new form and copy the answers from an existing form.

each form is represented by a `Form`, which is associated with a `FormType`.  the `FormType` contains `FormTypeSections`, which then contain `FormSectionItems`.  for each `Form`, we then have a list of `FormAnswer`s which are associated with a `Form` and a `FormSectionItem`.

the code to create a new Form and copy the answers from the old Form looks like this:

```csharp
        public async Task<IActionResult> OnPostAsync(string ssref, int formtypeid) {
            SSRef = ssref;
            FormType = await (
                from formType in _db.FormTypes
                where formType.Id == formtypeid
                select formType)
                .SingleAsync();

            var newForm = new Form {
                PersonId = ssref,
                FormTypeId = FormType.Id,
                Created = DateTime.Now,
            };

            _db.Forms.Add(newForm);
            await _db.SaveChangesAsync();

            // Copy answers from the old form if requested.
            if (CopyFormId != -1) {
                var oldForm = await (
                    from form in _db.Forms
                    where form.Id == CopyFormId
                    select form)
                    .SingleAsync();

                await CopyFormAnswers(_db, oldForm, newForm);
            }
            await _db.SaveChangesAsync();

            return RedirectToPage("/Forms/EditForm", new { formId = newForm.Id });
        }

        // Copy answers from an existing form to a new form.  
        public async Task CopyFormAnswers(FormContext db, Form oldForm, Form newForm) {
            // Fetch existing answers for the previous form
            var existingAnswers = await (
                from answer in db.FormAnswers
                where answer.FormId == oldForm.Id
                select answer)
                .ToListAsync();

            // We need to change the SectionItemId on each answer
            // to match the new form type, so create a mapping from
            // tag id to section item id.
            var sectionItems = await (
                from sectionItem in db.SectionItems
                where sectionItem.Section.FormTypeId == newForm.FormType.Id
                select sectionItem)
                .ToListAsync();

            var sectionItemIdByTag = new Dictionary<string, int>();
            foreach (var secItem in sectionItems)
                sectionItemIdByTag[secItem.TagId] = secItem.Id;

            // Copy each answer, changing the form id and section item id.
            foreach (var a in existingAnswers) {
                // If this tag id doesn't exist in the new form, skip it.
                if (!sectionItemIdByTag.TryGetValue(a.TagId, out var sectionItemId))
                    continue;

                var newAnswer = new FormAnswer {
                    FormId = newForm.Id,
                    SectionItemId = sectionItemId,
                    DateAnswer = a.DateAnswer,
                    TextAnswer = a.TextAnswer,
                    TagId = a.TagId,
                };

                await db.FormAnswers.AddAsync(newAnswer);
            }
        }
```

this should add a new Form, then add several new FormAnswers, and then finish.  instead, it **deletes all the FormAnswers associated with the old form** (i.e., the contents of `existingAnswers`), then adds the new ones.  the old form answers should not be deleted.

i worked around the problem by adding `.AsNoTracking()` to the `existingAnswers` query; then since EF doesn't know about the existing answers, it can't delete them.

### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 Enterprise version 1809 build 17763.1098
IDE: Visual Studio Professional 2019 16.4.5

### Database schema

```sql
CREATE TABLE dbo.FORM_TYPES (
    ID                              INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TITLE                           VARCHAR(50) NOT NULL,
    DESCRIPTION                     VARCHAR(100) NULL,
    CLASS_ID                        VARCHAR(5) NULL,
    EPISODE_TYPE                    VARCHAR(16) NULL,
    SEGMENT_CODE                    VARCHAR(16) NULL,
    STYLE                           VARCHAR(50) NULL,
    PERSON_DOC_CLASS                VARCHAR(16) NULL,
    FROM_DATE                       DATETIME NOT NULL,
    TO_DATE                         DATETIME NULL,
    CONTEXT                         VARCHAR(1) NULL,
    ID_CODE                         VARCHAR(20) NULL,
    VENDOR_VERSION_NUMBER           INTEGER NULL,
    VENDOR_VERSION_STRING           VARCHAR(40) NULL,
    AUTHORING_BODY_CODE             VARCHAR(10) NULL,
    VERSION_NUMBER                  INTEGER NULL,
    VERSION_STRING                  VARCHAR(40) NULL,
    VENDOR_PROVIDED_FLAG            VARCHAR(1) NULL,
    IS_DRAFT_FLAG                   VARCHAR(1) NULL,
    IS_DISABLED_FLAG                VARCHAR(1) NULL,
    CANNOT_BE_EDITED_FLAG           VARCHAR(1) NULL,
    SINCE_DB_VERSION                INTEGER NULL,
    SINCE_APP_VERSION               VARCHAR(40) NULL,
    LAST_UPDATED_DB_VERSION         INTEGER NULL,
    LAST_UPDATED_APP_VERSION        VARCHAR(40) NULL,
    CREATED_BY                      VARCHAR(16) NULL,
    CREATED_ACTING_FOR              VARCHAR(16) NULL,
    CREATED_ON                      DATETIME NULL,
    LAST_UPDATED_BY                 VARCHAR(16) NULL,
    LAST_UPDATED_ACTING_FOR         VARCHAR(16) NULL,
    LAST_UPDATED_ON                 DATETIME NULL,
    FORM_GROUP_CODE                 VARCHAR(20) NULL,
    CATEGORY                        VARCHAR(16) NOT NULL,
    DESIGNER_VERSION_STRING         VARCHAR(40) NULL,
    DESIGNER_VERSION_NUMBER         INTEGER NULL,
    FORMAT_VERSION_STRING           VARCHAR(40) NULL,
    FORMAT_VERSION_NUMBER           INTEGER NULL,
    CAN_GO_MOBILE_FLAG              VARCHAR(1) NULL,
    ACTION_HANDLER_CLASS_NAME       VARCHAR(200) NULL,
    DOCUMENT_CLASS                  VARCHAR(16) NULL,
    DOCUMENT_SUBCLASS               VARCHAR(16) NULL,
    IS_DIGITABLE_FLAG               VARCHAR(1) NOT NULL,
    IS_READONLY_FLAG                VARCHAR(1) NULL,
    HAS_MAND_FLDS_FLAG              VARCHAR(1) NOT NULL,
    HAS_ATTSCORES_FLAG              VARCHAR(1) NOT NULL,
    HAS_SCRIPTS_FLAG                VARCHAR(1) NOT NULL,
    is_group                        VARCHAR(1) NOT NULL,
    ID_CODE_DIGITAL_PENS_MAPPING    VARCHAR(100) NULL
);

CREATE TABLE dbo.FORM_TYPE_SECTIONS (
    ID                      INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    PAGE_NUM                INTEGER NOT NULL,
    FORM_TYPE_ID            INTEGER NOT NULL FOREIGN KEY
                                REFERENCES FORM_TYPES(ID)
                                ON DELETE CASCADE
                                ON UPDATE CASCADE,
    FROM_DATE                DATETIME NOT NULL,
    TO_DATE                  DATETIME NULL,
    GUIDANCE_POSITION_CODE   VARCHAR(40) NULL
);

CREATE TABLE dbo.SECTION_ITEMS (
    ID                              INTEGER IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    ITEM_ID                         INTEGER NOT NULL FOREIGN KEY REFERENCES ITEMS(ID),
    FROM_DATE                       DATETIME NOT NULL,
    SEQUENCE                        INTEGER NOT NULL,
    ITEM_NO                         VARCHAR(20) NULL,
    TO_DATE                         DATETIME NULL,
    SECTION_ID                      INTEGER NULL FOREIGN KEY
                                        REFERENCES FORM_TYPE_SECTIONS(ID)
                                        ON DELETE CASCADE
                                        ON UPDATE CASCADE,
    TAG_ID                          VARCHAR(100) NOT NULL,
    REPEATABLE_FLAG                 VARCHAR(1) NULL,
    SECTION_LEVEL_FLAG              VARCHAR(1) NULL,
    TYPE_CODE                       VARCHAR(40) NULL,
    GUIDANCE_PANEL_ITEM_ID          INTEGER NULL,
    GUIDANCE_POSITION_CODE          VARCHAR(40) NULL,
    LABEL_POSITION_CODE             VARCHAR(40) NULL,
    FLOW_MODE                       VARCHAR(20) NULL,
    ITEM_ALIGN                      VARCHAR(20) NULL,
    ALT_GUIDANCE_PANEL_ITEM_ID      INTEGER NULL,
    IS_GUIDANCE_PROMPT_FLAG         VARCHAR(1) NULL,
    TOP_POSITION                    INTEGER NULL,
    LEFT_POSITION                   INTEGER NULL,
    WIDTH                           INTEGER NULL,
    HEIGHT                          INTEGER NULL,
    FONT_FAMILY                     VARCHAR(100) NULL,
    FONT_SIZE                       INTEGER NULL,
    FONT_COLOUR                     VARCHAR(20) NULL,
    DISPLAY_ANSWER_BORDER_FLAG      VARCHAR(1) NULL,
    DPI_FORM_TYPE_ID                INTEGER NULL,
    DPI_CODE                        VARCHAR(255) NULL,
    DPI_PROPERTY_NAME               VARCHAR(255) NULL,
    DPI_CONTRIBUTOR_HOOK_FLAG       VARCHAR(1) NULL,
    LABEL_ALIGN                     VARCHAR(20) NULL,
    ITEM_PERCENTAGE_WIDTH           INTEGER NULL,
    DEFAULT_PRINT_STYLE_FLAG        VARCHAR(1) NULL,
    DISPLAY_BORDER_FLAG             VARCHAR(1) NULL,
    BORDER                          VARCHAR(40) NULL,
    PADDING                         VARCHAR(40) NULL,
    COLOR                           VARCHAR(40) NULL,
    DISPLAY_LEGEND_FLAG             VARCHAR(1) NULL,
    ELE_GRP_PRINT_MODE_CODE         VARCHAR(40) NULL,
    PREFER_VIEWABLE_FLAG            VARCHAR(1) NULL,
    PREFER_AMENDABLE_FLAG           VARCHAR(1) NULL,
    PREFER_PRINTABLE_FLAG           VARCHAR(1) NULL,
    IS_MANDATORY_FLAG               VARCHAR(1) NULL,
    IS_DIGITABLE_FLAG               VARCHAR(1) NOT NULL,
    TAG_ID_DIGITAL_PENS_MAPPING     VARCHAR(100) NULL,
    IS_DIG_PENS_OPT_ITEM_TEXT_FLAG  VARCHAR(1) NOT NULL,

    INDEX IDX_SECTION_ITEMS_TID_SID (TAG_ID, SECTION_ID)
);

CREATE TABLE dbo.FORMS (
    ID              INTEGER IDENTITY(1, 1) PRIMARY KEY
    ,CREATE_DATE    DATE NULL
    ,FINISH_DATE    DATE NULL
    ,FORM_TYPE_ID   INTEGER    NOT NULL FOREIGN KEY
        REFERENCES FORM_TYPES(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
    ,PERSON_ID      VARCHAR(16)
    ,EPISODE_ID     INTEGER NULL
    ,ID_CODE        VARCHAR(20)
    ,FORM_MAIN_LOGO VARCHAR(50)
);

CREATE TABLE FORM_ANSWERS (
    FORM_ID                 INTEGER    NOT NULL FOREIGN KEY REFERENCES FORMS(ID)
    ,SECTION_ITEM_ID        INTEGER    NOT NULL FOREIGN KEY REFERENCES SECTION_ITEMS(ID)
    ,DATE_ANSWER            DATE NULL
    ,NUMBER_ANSWER          DECIMAL NULL
    ,TEXT_ANSWER            TEXT NULL
    ,CREATED_BY_ID          INTEGER NULL
    ,CREATED_ACTING_FOR_ID  INTEGER NULL
    ,CREATED_ON             DATE NULL
    ,UPDATED_BY_ID          INTEGER NULL
    ,UPDATED_ACTING_FOR_ID  INTEGER NULL
    ,UPDATED_ON             DATE NULL
    ,ROW_IDENTIFIER         VARCHAR(100)
    ,FORM_TYPE_ID_CODE      VARCHAR(20)
    ,TAG_ID                 VARCHAR(100)
    ,SUBJECT_ID             INTEGER

    ,PRIMARY KEY (FORM_ID, SECTION_ITEM_ID)
    ,UNIQUE (FORM_ID, TAG_ID)
);
```

EF models:

```csharp
    [Table("FORMS")]
    public class Form {
        [Column("ID")]
        public int Id { get; set; }

        [Column("FORM_TYPE_ID")]
        public int FormTypeId { get; set; }
        public FormType FormType { get; set; }

        [Column("CREATE_DATE")]
        public DateTime Created { get; set; }

        [Column("FINISH_DATE")]
        public DateTime? Finished { get; set; }

        [Column("PERSON_ID")]
        public string PersonId { get; set; }
        public Person Person { get; set; }

        public List<FormAnswer> Answers { get; }
        public List<FormAnswerRepeating> RepeatingAnswers { get; }
    }

    [Table("FORM_ANSWERS")]
    public class FormAnswer {
        [Column("FORM_ID")]
        public int FormId { get; set; }
        public Form Form { get; set; }

        [Column("SECTION_ITEM_ID")]
        public int SectionItemId { get; set; }
        public FormSectionItem SectionItem { get; set; }

        [Column("DATE_ANSWER", TypeName = "DATE")]
        public DateTime? DateAnswer { get; set; }

        [Column("NUMBER_ANSWER", TypeName = "DECIMAL")]
        public decimal? NumberAnswer { get; set; }

        [Column("TEXT_ANSWER")]
        public string TextAnswer { get; set; }

        [Column("TAG_ID")]
        public string TagId { get; set; }

        public override string ToString() {
            return
                NumberAnswer?.ToString(CultureInfo.InvariantCulture)
                ?? DateAnswer?.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)
                ?? TextAnswer
                ?? "";
        }
    }

    [Table("FORM_TYPES")]
    public class FormType {
        [Column("ID")]
        public int Id { get; set; }

        [Column("TITLE")]
        [MaxLength(50)]
        public string Title { get; set; }

        [Column("DESCRIPTION")]
        [MaxLength(100)]
        public string Description { get; set; }

        [Column("ID_CODE")]
        [MaxLength(20)]
        public string IdCode { get; set; }

        [Column("VERSION_NUMBER")]
        public int VersionNumber { get; set; }

        public List<FormTypeSection> Sections { get; }
        public FormTypeScript Script { get; set; }
    }

    [Table("FORM_TYPE_SECTIONS")]
    public class FormTypeSection : IFormRenderable {
        [Column("ID")]
        public int Id { get; set; }

        [Column("FORM_TYPE_ID")]
        public int FormTypeId { get; set; }
        public FormType FormType { get; set; }

        [Column("PAGE_NUM")]
        public int PageNum { get; set; }

        public List<FormSectionItem> Items { get; }

        public FormTextItem Legend {
            get {
                try {
                    return (
                        from item in Items
                        where item.TypeCode == "LEGEND"
                        where item.SectionLevelFlag == "Y"
                        where item.Item.TextItemId != null
                        where item.Item.TextItem.Text != "Document Header"
                        where item.Item.TextItem.Text != "Document Footer"
                        select item.Item.TextItem
                    ).First();
                } catch (InvalidOperationException) {
                    return null;
                }
            }
        }

        static string[] _ignoreTypes = {
            "LEGEND", "CAPTION", "CONTROL_CODE", "HEADER", "FOOTER",
            "DOC_MAIN_TITLE", "IMAGE_DOC_MAIN_LOGO"
        };

        public XNode Render(Form form) {
            XElement legend = null;

            if (Legend != null)
                legend = new XElement("h2", Legend.Render(form));

            var items =
                from item in Items
                where item.SectionLevelFlag == "Y"
                where !_ignoreTypes.Contains(item.TypeCode)
                select item.Render(form);

            return new XElement("div",
                new XAttribute("class", "form-section"),
                legend,
                items);
        }
    }

    [Table("SECTION_ITEMS")]
    public class FormSectionItem : IFormRenderable {
        [Column("ID")]
        public int Id { get; set; }

        [Column("ITEM_ID")]
        public int? ItemId { get; set; }
        public FormItem Item { get; set; }

        [Column("SEQUENCE")]
        public int Sequence { get; set; }

        [Column("SECTION_ID")]
        public int SectionId { get; set; }
        public FormTypeSection Section { get; set; }

        [Column("REPEATABLE_FLAG")]
        public bool Repeatable { get; set; }

        [Column("TYPE_CODE")]
        public string TypeCode { get; set; }

        [Column("TAG_ID")]
        public string TagId { get; set; }

        [Column("SECTION_LEVEL_FLAG")]
        [MaxLength(1)]
        public string SectionLevelFlag { get; set; }

        public FormAnswer Answer { get; set; }
        public List<FormAnswerRepeating> RepeatingAnswers { get; }

        public XNode Render(Form form) {
            if (ItemId != null)
                return Item.Render(form);
            else
                return null;
        }
    }
```
```

**Comment by ajcvickers** [comment] 2020-03-20 16:49
@unixwitch I looked through your code carefully, but I don't see anything that looks like it would trigger the behavior you are seeing. I think we are going to need to get a way to reproduce what you are seeing before we can make progress here.

**Comment by unixwitch** [comment] 2020-03-20 18:24
i'll have another try at producing a test case today or tomorrow.  unfortunately the data is GDPR-protected but if i can create a test case on the real data hopeuflly i can creates some test data for it.

**Comment by ajcvickers** [comment] 2020-04-13 16:25
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:17 UTC
Labels: closed-could-not-reproduce, customer-reported
