### ISSUE TITLE
IsConcurrencyToken defined on OwnedType does not work as expected

### ISSUE THREAD

**Issue by juanmarl** [dotnet/efcore#13608] opened 2018-10-12 15:33 UTC
Changing the owned-type object throws always a `DbUpdateConcurrencyException ` when the owned type has a property set as concurrency token.. 

```
Exception message: Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException : Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.

Stack trace: 
en Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   en Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagation(Int32 commandIndex, RelationalDataReader reader)
   en Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   en Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   en Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   en Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   en Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   en Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   en Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   en Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   en Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   en Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   en Domain.Data.Tests.Shared.RepositoryTests`2.Update(T obj) en Infrastructure.Data.Tests\RepositoryTests.cs:línea 68
```

### Steps to reproduce

For example given this model:

```C#
public class Order
{
    public int Id { get; set; }
    public OrderStatus Status { get; set; }
}
[Owned]
public class OrderStatus
{
    [ConcurrencyCheck]
    public string Name { get; set; }
}
```

The following code throws a `DbUpdateConcurrencyException `:

```C#
var order = context.Orders.First();
order.Status = new Status { Name = 'Paid' };
context.SaveChanges();
```

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Visual Studio 2017 15.4

**Comment by ajcvickers** [comment] 2018-10-12 16:08
Duplicate of #12865

**Closed** 2022-10-16 13:35 UTC
Labels: customer-reported
