### ISSUE TITLE
Stored Procedure Mapping

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/efcore#15273] opened 2019-04-07 12:30 UTC
Hello,

I Have a question about Stored Procedure mapping in EF Core 2.2

I have these entities:

```csharp
 public class HomePageStoryEntry
    {
        /// Some Properties

        public List<EntryElement> Elements { get; set; } = new List<EntryElement>();
        
    }
public class EntryElement
    {
       
        public string FileName { get; set; }

        public int Width { get; set; }

        public int Height { get; set; }

        public string Alt { get; set; }

    }
```
I want to get my entities through EF Core
I tried with Linq:

```csharp
 List<HomePageStoryEntry> list = await _context.NewsFeeds
                .Include(i => i.Elements)
                .Include("Elements.Visuel")
                .Where(nf => nf.Date < limite)
                .Select(s => new HomePageStoryEntry
                {
                    BookSlug = s.BookSlug,
                    Elements = s.Elements.Select(se => new EntryElement
                    {
                        Alt = se.Visuel.Alt,
                        FileName = se.Visuel.FileName,
                        Height = se.Visuel.Height,
                        Width = se.Visuel.Width
                    }).ToList(),
                    GalerieId = s.GalerieId,
                    GalerieSlug = s.GalerieSlug,
                    Id = s.id,
                    IsOnFacebook = s.IsOnFacebook,
                    ToPublishOnFacebook = s.ToPublishOnFacebook,
                    UserPublicName = s.User.PublicName
                }).AsNoTracking()
                .ToListAsync();
````
It works fine and it's translated to two SQL Queries:

```sql
SELECT 
	[i].[BookSlug], 
	[i].[GalerieId], 
	[i].[GalerieSlug], 
	[i].[id], 
	[i].[IsOnFacebook], 
	[i].[ToPublishOnFacebook], 
	[i.User].[PublicName] AS [UserPublicName]
FROM [NewsFeeds] AS [i]
LEFT JOIN [AspNetUsers] AS [i.User] ON [i].[UserId] = [i.User].[Id]
WHERE [i].[Date] < @Limite
ORDER BY [i].[date] desc

SELECT 
[t].[id], 
[se.Visuel].[Alt], 
[se.Visuel].[FileName], 
[se.Visuel].[Height], 
[se.Visuel].[Width], 
[i.Elements].[NewsFeedId]
	FROM [NewsFeedElements] AS [i.Elements]
	INNER JOIN [Visuels] AS [se.Visuel] ON [i.Elements].[VisuelId] = [se.Visuel].[Id]
	INNER JOIN (
		SELECT [i0].[id]
		FROM [NewsFeeds] AS [i0]
		LEFT JOIN [AspNetUsers] AS [i.User0] ON [i0].[UserId] = [i.User0].[Id]
		WHERE [i0].[Date] < @Limite
	) AS [t] ON [i.Elements].[NewsFeedId] = [t].[id]
	ORDER BY [t].[id]
```
So I tried to execute it through a stored procedure
In my context
I put 
```cshrap
  public DbQuery<HomePageStoryEntry> HomePageStoryViewModel { get; set; }
```
And I call the stored procedure like this:
```csharp
await _context.Query<HomePageStoryEntry>().FromSql("EXEC GetHomePageStory").AsNoTracking().ToListAsync();
````
The result is a List of HomePageStoryEntry, but Impossible to map the list of EntryElement

I tries to activate MultipleActiveResultSets in the SQL connection string.

But no effect.

Can anyone help me or is it an issue ?

Thanks

**Comment by ajcvickers** [comment] 2019-04-08 17:22
Duplicate of #14525

**Closed** 2022-10-16 13:59 UTC
Labels: closed-duplicate, customer-reported
