### ISSUE TITLE
Synapse database first approach - FUNCTION OBJECT_SCHEMA_NAME not supported

### ISSUE THREAD

**Issue by mrzenca** [dotnet/efcore#29137] opened 2022-09-19 07:28 UTC
Hi, 

When will a version be available that allows model generation based on Azure Synapse (SQL connection)?

EF Version 7.0.0-rc.1.22426.7
dotnet ef dbcontext scaffold "..." Microsoft.EntityFrameworkCore.SqlServer -o Model
Error message: FUNCTION OBJECT_SCHEMA_NAME not supported

Thanks,
Michał

**Comment by ErikEJ** [comment] 2022-09-19 07:57
You can do that today with EF Core Power Tools, and I have a PR in (for EF Core 8)

**Comment by ajcvickers** [comment] 2022-09-19 17:29
Duplicate of #29121

**Closed by ajcvickers** 2022-09-19 17:29 UTC
Labels: customer-reported
