### ISSUE TITLE
JSON Column nullable

### ISSUE THREAD

**Issue by nw5428** [dotnet/efcore#29838] opened 2022-12-12 21:33 UTC
If I include a JSON column where the mapped class, which has a nullable member object; If the value of the column is not null and does not contain that nullable member object,  when doing a query you receive the error "The given key was not present in the dictionary"

Example:

Table FooBar with column Foo.  One row with value set to '{}'.  It could also be {"SomethingElse": 123}.  (For example a different application also writing some different stuff to the same column)

My EF Core configuration is  below

```c#
public class Bar
    {
        public string HelloWorld{ get; set; }
    }
    public class Foo
    {
        public Bar? Bar { get; set; } 
    }
    public class FooBar
    {
        public int Id { get; set; }
        public Foo? Foo { get; set; }
    }
```

```c#
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FooBar>.OwnsOne(d => d.Foo, nb =>
            {
                nb.ToJson();
                nb.OwnsOne(q => q.Bar);
            });
        }
```

**Comment by maumar** [comment] 2023-03-28 08:12
dupe of https://github.com/dotnet/efcore/issues/30028 (although it should be the other way around). 
@airwedge1 the issue is now fixed and should work in 7.0.5 patch

**Closed by maumar** 2023-03-28 08:12 UTC
Labels: customer-reported
