### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 'System.String'

### ISSUE THREAD

**Issue by jmbalanag** [dotnet/efcore#6175] opened 2016-07-27 07:08 UTC
### Steps to reproduce

``` C#
public class person_profile
{
public int approval_id {get;set;}
public string city_name {get;set;}

public virtual lib_approval lib_approval {get;set;} => has int as PK
public virtual lib_city lib_city {get;set;} =>has string as PK
}
```
## Problem occurs when accessing lib_city.city_name..

``` C#
 public class person_profileDTO
    {
        public string lib_approval_name { get; set; }
        public string lib_city_city_name { get; set; }


        public static System.Linq.Expressions.Expression<Func<person_profile, person_profileDTO>> SELECT =
            x => new person_profileDTO
            {
                lib_approval_name = x.lib_approval.name,
                lib_city_city_name = x.lib_city.city_name,

            };

    }
}
```

using this method still throws same error:

``` C#
   db.person_profile  .Include(x => x.lib_city).Select(
                    x => new 
                    {
                        person_profile_id = x.person_profile_id,

                        lib_city_city_name = x.lib_city.city_name,

                    }
                    );,
```
### The issue

When retrieving values of related tables for values with string keys, exception is thrown. For integer values there is no problem.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:  An unhandled exception has occurred while executing the request
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'DeskApp.DataLayer.person_profile'.
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.<GroupJoinIterator>d__40`4.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__22`3.MoveNext()
   at System.Linq.Enumerable.<JoinIterator>d__37`4.MoveNext()
Stack trace:
```
### Further technical details

EF Core version: 1.0.0-rc2-final
Operating system: Windows 10
Visual Studio version: 2015

Other details about my project setup:

**Comment by rowanmiller** [comment] 2016-07-27 18:20
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

**Comment by rowanmiller** [comment] 2016-07-27 18:20
You should also upgrade to the RTM release, rather than RC2.

**Comment by divega** [comment] 2016-08-02 22:12
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 09:52 UTC
Labels: closed-could-not-reproduce
