### ISSUE TITLE
LINQ Include Query with .Take(int) results in pulling all results from the database

### ISSUE THREAD

**Issue by caleblloyd** [dotnet/efcore#6569] opened 2016-09-18 21:36 UTC
### Steps to reproduce

Models:

```
public class Blog
{
    public int BlogId { get; set; }
    public string Title { get; set; }

    public List<Post> Posts { get; set; }
}

public class Post
{
    public int PostId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }

    public int BlogId { get; set; }
    public Blog Blog { get; set; }
}
```
### The issue

When I query these 2 tables using the following LINQ Expression:

```
db.Blogs.OrderByDescending(m => m.BlogId).Take(10).Include(m => m.Posts).ToList();
```

Produce the following SQL that selects All Posts from the table.

```
SELECT `p`.`PostId`, `p`.`BlogId`, `p`.`Content`, `p`.`Title`
FROM `Posts` AS `p`
WHERE EXISTS (
    SELECT 1
    FROM `Blogs` AS `m`
    WHERE `p`.`BlogId` = `m`.`BlogId`
    LIMIT 10)
ORDER BY `p`.`BlogId` DESC
```

Incorrect # of results (should be 20 since I have 2 posts per blog in my test case)

```
Showing rows 0 - 24 (26280 total, Query took 0.0003 seconds.) 
```

As you can imagine, this is quite an issue when the Posts table has 1000's of posts.
### Further technical details

EF Core version: 1.0.1
Operating system: Ubuntu 16.04

I am using the [Pomelo.EntityFramework.MySql](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) driver (I am a contributor to the project).

The joining behavior in question comes from the [IncludeExpressionVisitor.cs](https://github.com/aspnet/EntityFramework/blob/1.0.1/src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs)

**Comment by caleblloyd** [comment] 2016-09-18 23:27
Why doesn't the 2nd relational query simply use the Primary Keys from the 1st query?  So if my first query is:

    SELECT `m`.`BlogId`, `m`.`Title`
    FROM `Blogs` AS `m`
    ORDER BY `m`.`BlogId` DESC
    LIMIT 10

And my Result Set is:

    13215	MySql Wiki Blog
    13214	MySql Wiki Blog
    13213	Entity Framework Wiki Blog
    13212	MySql Wiki Blog
    13211	MySql Wiki Blog
    13210	Entity Framework Wiki Blog
    13209	MySql Wiki Blog
    13208	Entity Framework Wiki Blog
    13207	MySql Wiki Blog
    13206	Entity Framework Wiki Blog

Then why isn't the Relational Query:

    SELECT `p`.`PostId`, `p`.`BlogId`, `p`.`Content`, `p`.`Title`
    FROM `Posts` AS `p`
    WHERE `p`.`BlogId` IN (
        13215,
        13214,
        13213,
        13212,
        13211,
        13210,
        13209,
        13208,
        13207,
        13206
    )

This would achieve cut way down on the network transfer to the DbDataReader since the result set would only contain the records that were needed

**Comment by caleblloyd** [comment] 2016-09-19 03:36
When I remove these lines: [IncludeExpressionVisitor.cs#L324-L366](https://github.com/aspnet/EntityFramework/blob/1.0.1/src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs#L324-L366), the innerJoinSelectExpression in the else{} clause provides much better performance.  Generated SQL is:

	SELECT `p`.`PostId`, `p`.`BlogId`, `p`.`Content`, `p`.`Title`
	FROM `Posts` AS `p`
	INNER JOIN (
	    SELECT DISTINCT `m`.`BlogId`
	    FROM `Blogs` AS `m`
	    ORDER BY `m`.`BlogId` DESC
	    LIMIT 10
	) AS `m0` ON `p`.`BlogId` = `m0`.`BlogId`
	ORDER BY `m0`.`BlogId` DESC

Result set is the proper size (20 Records, my 10 blogs have 2 Posts per blog) and Query Performance is still very fast:

    Showing rows 0 - 19 (20 total, Query took 0.0003 seconds.)

I feel like this should be the default behavior.  I'm a little confused as to why the `canGenerateExists` is the default, is there a good reason?

**Comment by smitpatel** [comment] 2016-09-20 18:29
dupe of #6530

**Closed** 2022-10-16 09:58 UTC
