### ISSUE TITLE
GroupJoin fails in trivial case

### ISSUE THREAD

**Issue by ericjohannsen** [dotnet/efcore#17933] opened 2019-09-19 03:14 UTC
An attempt to use GroupJoin in a toy database using RC1 fails with an exception (see below).

### Steps to reproduce

The code-first database is created using
``` C#
public class Customer
{
	public virtual int ID { get; set; }
	public virtual string Name { get; set; }
}
public class Purchase
{
	public virtual int ID { get; set; }
	public virtual Customer Customer { get; set; }
	public virtual int CustomerID { get; set; }
	public virtual DateTime Date { get; set; }
	public virtual string Description { get; set; }
	public virtual decimal Price { get; set; }
}
public class LibContext : DbContext
{
	public DbSet<Customer> Customers { get; set; }
	public DbSet<Purchase> Purchases { get; set; }

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		optionsBuilder.UseSqlServer(@"Server=(local);Database=MyDbName;Trusted_Connection=True;");
	}
```
Add some data:
``` C#
using (var ctx = new LibContext())
{
	var c1 = new Customer() { Name = "Eric" };
	var c2 = new Customer() { Name = "Rose" };
	var p1a = new Purchase() { Customer = c1, Date = new DateTime(2019, 7, 11), Description = "Foo", Price = 0.99m };
	var p1b = new Purchase() { Customer = c1, Date = new DateTime(2019, 4, 2), Description = "Bar", Price = 2.99m };
	var p2 = new Purchase() { Customer = c2, Date = new DateTime(2019, 9, 21), Description = "Baz", Price = 5.99m };
	ctx.Customers.Add(c1);
	ctx.Customers.Add(c2);
	ctx.Purchases.Add(p1a);
	ctx.Purchases.Add(p1b);
	ctx.Purchases.Add(p2);

	ctx.SaveChanges();
}
```
Attempt this query
``` C#
// This way
var join =
  from c in ctx.Customers
  join p in ctx.Purchases on c.ID equals p.CustomerID
  into custPurchases
  select custPurchases;

// Or this way
var join =
  ctx.Customers
    .GroupJoin(ctx.Purchases, c => c.ID, p => p.CustomerID, (c, p) => new { c, p });
```

Result:

System.InvalidOperationException
  HResult=0x80131509
  Message=Processing of the LINQ expression 'GroupJoin<Customer, Purchase, int, <>f__AnonymousType0<Customer, IEnumerable<Purchase>>>(
    outer: DbSet<Customer>, 
    inner: DbSet<Purchase>, 
    outerKeySelector: (c) => c.ID, 
    innerKeySelector: (p) => p.CustomerID, 
    resultSelector: (c, p) => new { 
        c = c, 
        p = p
     })' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandAndReduce(Expression query, Boolean applyInclude)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at EfCoreTest.Program.Main(String[] args) in C:\Users\Eric\source\repos\EfCoreTest\EfCoreTest\Program.cs:line 30

### Further technical details

EF Core version: 3.0.0-rc1.19456.14
Database provider: (Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.2.3

**Comment by smitpatel** [comment] 2019-09-19 03:57
Duplicate of #17068

There is no equivalent of GroupJoin in database even in trivial case. It has to be evaluated on client to generate groupings.

**Comment by ericjohannsen** [comment] 2019-09-19 04:51
@smitpatel I read the closed-as-duplicate issue before posting this and it wasn't obvious to me that this is the same issue or what the fix is.

Linq to SQL and EF 6.x both execute this syntax. If EF Core has no plans to execute it, the work-around to perform it client-side should be clearly documented an communicated.

**Comment by smitpatel** [comment] 2019-09-19 05:16
@ericjohannsen - I understand that SQL would be simple if EF executed this like how EF6 & Linq to SQL did. We used to do this in past too. It is a double-edged sword to do client side evaluation like this.
For trivial case like yours, running single SQL and generating result on client side facilitate the result generation by avoiding 2 queries. But at the same time, if you composing over grouping in some way then it may not be server translated in various cases. #17068 talks about one of such issues. Doing such client eval hides fact from user that it is doing evaluation on client. There is value in doing it but obvious pitfalls. Hence we filed issue to get customer feedback on quantify those. Please upvote #17068 if you want that feature.

**Closed** 2022-10-16 14:43 UTC
Labels: customer-reported
