### ISSUE TITLE
Batch update multiple entities in a single UPDATE statement

### ISSUE THREAD

**Issue by huysentruitw** [dotnet/efcore#23090] opened 2020-10-24 14:43 UTC
**What problem are you trying to solve?**

When working with ordered lists, items need to have a SequenceNumber. When inserting items somewhere in the middle of the list, we need to shift SequenceNumbers around to create a gap before inserting the new item.  With EF Core, this means a lot of items need to be updated, while with SQL, one would do this in a single update statement:

```SQL
UPDATE ProjectItems
   SET SequenceNumber = SequenceNumber + 1
 WHERE ProjectId = @ProjectId AND SequenceNumber >= @sequenceNumberOfNewItem
```

It would be nice if there was some clean way to generate an UPDATE statement like the one above.

**Describe the solution you'd like**

What I have in mind is that it should be possible to write something like this:

```C#
await _dataContext
    .ProjectItems
    .Where(x => x.ProjectId == input.ProjectId && x.SequenceNumber >= sequenceNumberOfNewItem)
    .UpdateAsync(x => x.SequenceNumber = x.SequenceNumber + 1);
```

and probably we could leverage the existing SQL generation.

I'm not sure how this should work with tracked entities, so perhaps this should be a separate project instead of an EF Core feature, but I have no idea where to start implementing this, so any pointers on how to implement this are very much appreciated.

**Other alternatives**

Yes, I have considered other alternatives like storing decimal fractions or true fractions (Stern Brocot tree), but none of them fit my use-case.

**Comment by roji** [comment] 2020-10-25 05:55
Duplicate of #23012

**Comment by roji** [comment] 2020-10-25 05:55
Duplicate of #795

**Comment by roji** [comment] 2020-10-25 05:56
We are considering doing this for 6.0 (with high priority, I think).

**Closed** 2022-10-16 19:06 UTC
Labels: customer-reported
