### ISSUE TITLE
Suboptimal SQL generated in LEFT JOIN on SQL Server

### ISSUE THREAD

**Issue by ltrzesniewski** [dotnet/efcore#13997] opened 2018-11-22 10:48 UTC
I'm migrating from Linq2SQL to EF Core while trying to reuse existing queries as much as possible to ease the process. Many of the existing queries perform left joins by using this pattern:

```C#
from parent in context.Parent
from child in context.Children.Where(c => c.ParentId == parent.Id).DefaultIfEmpty()
```

Mainly because it's shorter and reads better than group joins.

Linq2SQL generates a simple `LEFT JOIN` in that case, but EF Core generates a `CROSS APPLY` on an inner query containing a `LEFT JOIN`, which is suboptimal.

### Steps to reproduce

Here's a simple model:

```C#
internal class TestContext : DbContext
{
    public DbSet<Foo> Foos { get; set; }
    public DbSet<Bar> Bars { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);

        if (optionsBuilder.IsConfigured)
            return;

        optionsBuilder.UseLoggerFactory(SqlConsoleLoggerProvider.LoggerFactory);
        optionsBuilder.UseSqlServer("..."); // TODO: Use a sensible connection string here
    }
}

internal class Foo
{
    public int Id { get; set; }

    public ICollection<Bar> Bars { get; set; }
}

internal class Bar
{
    public int Id { get; set; }
    public int FooId { get; set; }
}
```

The following test program:

```C#
internal static class Program
{
    [SuppressMessage("ReSharper", "AccessToDisposedClosure")]
    public static void Main()
    {
        using (var context = new TestContext())
        {
            ExecuteQuery(
                @"Left join using ""join into""",
                from foo in context.Foos
                join bar in context.Bars on foo.Id equals bar.FooId into barJoin
                from bar in barJoin.DefaultIfEmpty()
                select new { FooId = foo.Id, BarId = bar.Id }
            );

            ExecuteQuery(
                @"Left join using ""from where""",
                from foo in context.Foos
                from bar in context.Bars.Where(b => b.FooId == foo.Id).DefaultIfEmpty()
                select new { FooId = foo.Id, BarId = bar.Id }
            );

            ExecuteQuery(
                @"Left join using model",
                from foo in context.Foos
                from bar in foo.Bars.DefaultIfEmpty()
                select new { FooId = foo.Id, BarId = bar.Id }
            );
        }
    }

    private static void ExecuteQuery<T>(string name, IQueryable<T> query)
    {
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine($"--- {name} ---");
        Console.ResetColor();

        try
        {
            _ = query.AsEnumerable().FirstOrDefault();
        }
        catch (SqlException)
        {
        }
    }
}
```

Generates this output:

```SQL
--- Left join using "join into" ---
SELECT [foo].[Id] AS [FooId], [bar].[Id] AS [BarId]
FROM [Foos] AS [foo]
LEFT JOIN [Bars] AS [bar] ON [foo].[Id] = [bar].[FooId]

--- Left join using "from where" ---
SELECT [foo].[Id] AS [FooId], [t0].[Id] AS [BarId]
FROM [Foos] AS [foo]
CROSS APPLY (
    SELECT [t].*
    FROM (
        SELECT NULL AS [empty]
    ) AS [empty]
    LEFT JOIN (
        SELECT [b].*
        FROM [Bars] AS [b]
        WHERE [b].[FooId] = [foo].[Id]
    ) AS [t] ON 1 = 1
) AS [t0]

--- Left join using model ---
SELECT [foo].[Id] AS [FooId], [foo.Bars].[Id] AS [BarId]
FROM [Foos] AS [foo]
LEFT JOIN [Bars] AS [foo.Bars] ON [foo].[Id] = [foo.Bars].[FooId]
```

I expected all 3 queries to produce a `LEFT JOIN` here.

<details><summary>Logger code for completeness</summary>
<p>

```C#
internal class SqlConsoleLoggerProvider : ILoggerProvider
{
    public static LoggerFactory LoggerFactory { get; } = new LoggerFactory(new[] { new SqlConsoleLoggerProvider() });

    public ILogger CreateLogger(string categoryName)
        => new SqlConsoleLogger();

    public void Dispose()
    {
    }

    private class SqlConsoleLogger : ILogger
    {
        public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
        {
            if (eventId == RelationalEventId.CommandError || eventId == CoreEventId.QueryIterationFailed)
                return; // That's expected

            if (logLevel >= LogLevel.Warning)
            {
                Console.ForegroundColor = logLevel >= LogLevel.Error ? ConsoleColor.Red : ConsoleColor.Yellow;
                Console.WriteLine(formatter(state, exception));
                Console.ResetColor();
                Console.WriteLine();
                return;
            }

            if (eventId == RelationalEventId.CommandExecuting)
            {
                var structure = (IReadOnlyList<KeyValuePair<string, object>>)state;
                var commandText = structure.Where(i => i.Key == "commandText").Select(i => (string)i.Value).First();

                Console.WriteLine(commandText);
                Console.WriteLine();
            }
        }

        public bool IsEnabled(LogLevel logLevel)
            => logLevel >= LogLevel.Debug;

        public IDisposable BeginScope<TState>(TState state)
            => NullScope.Instance;
    }
}
```

</p>
</details>

### Further technical details
EF Core version: 2.2.0-preview3-35497
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.2

**Comment by ajcvickers** [comment] 2018-11-28 19:37
@maumar to find dupe.

**Comment by maumar** [comment] 2018-12-03 21:06
dupe of https://github.com/aspnet/EntityFrameworkCore/issues/3263

**Closed** 2022-10-16 13:41 UTC
Labels: customer-reported
