### ISSUE TITLE
Support Ordering of Child Navigation Properties When Using .Include()

### ISSUE THREAD

**Issue by rbonomo** [dotnet/efcore#16529] opened 2019-07-09 17:38 UTC
My [REDACTED]'s getting retrieved out of order (seemingly random). I need to be able to be able to retrieve child navigation properties ordered by the most basic column... the primary key (id). Also want to be able to order by other columns (I have a Position column).

Right now I have to retrieve the child properties with .Include() and THEN order it in C# code...

*Note: @ajcvickers edited this comment to remove content that violated the project’s code of conduct.*

**Comment by ajcvickers** [comment] 2019-07-09 18:28
Duplicate of #2919

**Closed** 2022-10-16 14:29 UTC
Labels: closed-duplicate, customer-reported
