### ISSUE TITLE
All foreign keys must be removed or redefined before the referenced key can be removed.

### ISSUE THREAD

**Issue by SimonOrdo** [dotnet/efcore#5449] opened 2016-05-20 18:40 UTC
Exception:

`"Cannot remove key {'Id'} from entity type 'Common.ApplicationUser' because it is referenced by a foreign key in entity type 'Common.Certificate_Pool_Info'. All foreign keys must be removed or redefined before the referenced key can be removed."
System.Exception {System.InvalidOperationException}
`

What does this error mean, in general terms?  These tables worked in RC1, but now throw an exception in RC2.  This exception was thrown when doing a simple Select on an unrelated table.

**Comment by SimonOrdo** [comment] 2016-05-20 18:42
Here is the stack trace

 ```
at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.CheckKeyNotInUse(Key key)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.RemoveKey(Key key, Boolean runConventions)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.RemoveKey(IReadOnlyList`1 properties, Boolean runConventions)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.RemoveKey(Key key, ConfigurationSource configurationSource, Boolean runConventions)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalPropertyBuilder.IsRequired(Boolean isRequired, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalPropertyBuilder.Attach(InternalEntityTypeBuilder entityTypeBuilder, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.PropertyBuildersSnapshot.Attach(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasBaseType(EntityType baseEntityType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.DerivedTypeDiscoveryConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(String name, Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.InversePropertyAttributeConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder, PropertyInfo navigationPropertyInfo, InversePropertyAttribute attribute)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.NavigationAttributeEntityTypeConvention`1.Apply(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(String name, Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.FindRelationshipCandidates(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.Apply(InternalRelationshipBuilder relationshipBuilder, Navigation navigation)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnNavigationAdded(InternalRelationshipBuilder relationshipBuilder, Navigation navigation)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(InternalEntityTypeBuilder principalEntityTypeBuilder, InternalEntityTypeBuilder dependentEntityTypeBuilder, String navigationToPrincipalName, String navigationToDependentName, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 isUnique, Nullable`1 isRequired, Nullable`1 deleteBehavior, Boolean oldRelationshipInverted, Nullable`1 principalEndConfigurationSource, Nullable`1 configurationSource, Boolean runConventions)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(Nullable`1 configurationSource, InternalEntityTypeBuilder principalEntityTypeBuilder, InternalEntityTypeBuilder dependentEntityTypeBuilder, String navigationToPrincipalName, String navigationToDependentName, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 isUnique, Nullable`1 isRequired, Nullable`1 deleteBehavior, Boolean strictPrincipal, Boolean oldRelationshipInverted, Boolean runConventions)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(String navigationToPrincipalName, String navigationToDependentName, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Relationship(InternalEntityTypeBuilder principalEntityTypeBuilder, String navigationToPrincipalName, String navigationToDependentName, ConfigurationSource configurationSource, Boolean setPrincipalEnd, Nullable`1 isUnique)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Relationship(InternalEntityTypeBuilder targetEntityTypeBuilder, PropertyInfo navigationToTarget, PropertyInfo inverseNavigation, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.InversePropertyAttributeConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder, PropertyInfo navigationPropertyInfo, InversePropertyAttribute attribute)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.NavigationAttributeEntityTypeConvention`1.Apply(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(String name, Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.InversePropertyAttributeConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder, PropertyInfo navigationPropertyInfo, InversePropertyAttribute attribute)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.NavigationAttributeEntityTypeConvention`1.Apply(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(String name, Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(Type type)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.RelationalModelSource.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass14_0.<GetModel>b__0(Object k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Storage.DatabaseProviderServices.GetService[TService]()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseProviderServices.get_QueryContextFactory()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.<>c.<AddQuery>b__1_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.<.ctor>b__2_0()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AdminWeb.Startup.Configure1(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, AdminDbContext _db) in C:\TFS\Isengard_Ex\src\AdminWeb\Startup.cs:line 206
```

**Comment by smitpatel** [comment] 2016-05-21 00:44
The error is being thrown during model building stage. Can you share you model and dbcontext?

**Comment by SimonOrdo** [comment] 2016-05-23 15:13
@smitpatel 

Context:

`public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext(DbContextOptions options)
        : base(options)
        { }
        

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {            
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Certificate_Pool_Info>(entity =>
            {
                entity.HasIndex(e => e.PoolID)
                    .HasName("PoolIDUnique")
                    .IsUnique();

                entity.Property(e => e.CreatedOn).HasColumnType("datetime");

                entity.Property(e => e.LastEditOn).HasColumnType("datetime");
            });

            modelBuilder.Entity<Certificate_Pools>(entity =>
            {
                entity.Property(e => e.AddedOn).HasColumnType("datetime");

                entity.Property(e => e.EditedOn).HasColumnType("datetime");

                entity.Property(e => e.ExhaustedOn).HasColumnType("datetime");

                entity.Property(e => e.PoolEnabled).HasDefaultValueSql("1");

                entity.HasOne(d => d.PoolInfo)
                    .WithMany(p => p.Certificate_Pools)
                    .HasPrincipalKey(p => p.PoolID)
                    .HasForeignKey(d => d.PoolInfoID)
                    .HasConstraintName("FK_Certificate_Pools_Certificate_Pool_Info");
            });

            modelBuilder.Entity<Courses>(entity =>
            {
                entity.Property(e => e.AdminMessage).HasDefaultValueSql("N''");

                entity.Property(e => e.Duration).HasDefaultValueSql("N'Unknown Duration'");

                entity.Property(e => e.IsScorm).HasDefaultValueSql("0");

                entity.Property(e => e.LastEditOn)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("getutcdate()");

                entity.Property(e => e.RemoteSyncState).HasDefaultValueSql("0");

                entity.Property(e => e.SyncId).HasDefaultValueSql("N''");

                entity.Property(e => e.Uploaded)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("getutcdate()");
            });

            modelBuilder.Entity<Package_Config>(entity =>
            {
                entity.Property(e => e.Active).HasDefaultValueSql("1");

                entity.Property(e => e.CreatedOn)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("getutcdate()");

                entity.Property(e => e.LastEditOn)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("getutcdate()");

                entity.Property(e => e.MaxBuysAllowedPerUser).HasDefaultValueSql("0");

                entity.Property(e => e.MinTimeBetweenBuys).HasDefaultValueSql("0");

                entity.Property(e => e.ProctorRequired).HasDefaultValueSql("0");
            });

            modelBuilder.Entity<Package_Courses>(entity =>
            {
                entity.HasIndex(e => new { e.CourseId, e.PackageId })
                    .HasName("CourseIdPackageIdUnique")
                    .IsUnique();
            });

            modelBuilder.Entity<Portal_FAQ>(entity =>
            {
                entity.Property(e => e.ID).ValueGeneratedNever();

                entity.Property(e => e.IsGlobal).HasDefaultValueSql("0");

                entity.Property(e => e.LastEditOn).HasColumnType("datetime");

                entity.Property(e => e.SortPriority).HasDefaultValueSql("0");
            });

            modelBuilder.Entity<Portal_SectionContent>(entity =>
            {
                entity.HasIndex(e => new { e.ContentID, e.PortalID })
                    .HasName("IX_Portal_SectionContent")
                    .IsUnique();

                entity.Property(e => e.LastEditOn)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("getutcdate()");

                entity.Property(e => e.SectionContent).HasDefaultValueSql("N''");

                entity.Property(e => e.Version).HasDefaultValueSql("0");
            });

            modelBuilder.Entity<Portal_URL>(entity =>
            {
                entity.HasIndex(e => e.URL)
                    .HasName("IX_Portal_URL_URL")
                    .IsUnique();
            });

            modelBuilder.Entity<SessionCache>(entity =>
            {
                entity.HasIndex(e => e.ExpiresAtTime)
                    .HasName("Index_ExpiresAtTime");
            });

            foreach (var relationship in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
            {
                relationship.DeleteBehavior = DeleteBehavior.Restrict;
            }
        }

        public virtual DbSet<Certificate_Pool_Info> Certificate_Pool_Info { get; set; }
        public virtual DbSet<Certificate_Pools> Certificate_Pools { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Package_Config> Package_Config { get; set; }
        public virtual DbSet<Package_Courses> Package_Courses { get; set; }
        public virtual DbSet<Portal_Config> Portal_Config { get; set; }
        public virtual DbSet<Portal_FAQ> Portal_FAQ { get; set; }
        public virtual DbSet<Portal_SectionContent> Portal_SectionContent { get; set; }
        public virtual DbSet<Portal_URL> Portal_URL { get; set; }
        public virtual DbSet<SessionCache> SessionCache { get; set; }

    }`

And the models

`public class ApplicationUser : IdentityUser
    {
        public ApplicationUser()
        {
            Admin_LAP_CertPrintLog = new HashSet<Admin_LAP_CertPrintLog>();
            Certificate_Pool_InfoCreatedByNavigation = new HashSet<Certificate_Pool_Info>();
            Certificate_Pool_InfoLastEditByNavigation = new HashSet<Certificate_Pool_Info>();
            Certificate_PoolsAddedByNavigation = new HashSet<Certificate_Pools>();
            Certificate_PoolsEditedByNavigation = new HashSet<Certificate_Pools>();
            CoursesLastEditByNavigation = new HashSet<Courses>();
            CoursesUploadedByNavigation = new HashSet<Courses>();
            Package_ConfigCreatedByNavigation = new HashSet<Package_Config>();
            Package_ConfigLastEditByNavigation = new HashSet<Package_Config>();
            Portal_FAQ = new HashSet<Portal_FAQ>();
            Portal_SectionContent = new HashSet<Portal_SectionContent>();
        }

        public string FirstName { get; set; }
        public string LastName { get; set; }

        [ForeignKey("MyPortalID")]
        [InverseProperty("AspNetUsers")]
        public virtual Portal_Config MyPortal { get; set; }

        [ForeignKey("ID")]
        public long MyPortalID { get; set; }

        public virtual ICollection<Admin_LAP_CertPrintLog> Admin_LAP_CertPrintLog { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Certificate_Pool_Info> Certificate_Pool_InfoCreatedByNavigation { get; set; }
        [InverseProperty("LastEditByNavigation")]
        public virtual ICollection<Certificate_Pool_Info> Certificate_Pool_InfoLastEditByNavigation { get; set; }
        [InverseProperty("AddedByNavigation")]
        public virtual ICollection<Certificate_Pools> Certificate_PoolsAddedByNavigation { get; set; }
        [InverseProperty("EditedByNavigation")]
        public virtual ICollection<Certificate_Pools> Certificate_PoolsEditedByNavigation { get; set; }
        [InverseProperty("LastEditByNavigation")]
        public virtual ICollection<Courses> CoursesLastEditByNavigation { get; set; }
        [InverseProperty("UploadedByNavigation")]
        public virtual ICollection<Courses> CoursesUploadedByNavigation { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Package_Config> Package_ConfigCreatedByNavigation { get; set; }
        [InverseProperty("LastEditByNavigation")]
        public virtual ICollection<Package_Config> Package_ConfigLastEditByNavigation { get; set; }
        [InverseProperty("LastEditByNavigation")]
        public virtual ICollection<Portal_FAQ> Portal_FAQ { get; set; }
        [InverseProperty("LastEditByNavigation")]
        public virtual ICollection<Portal_SectionContent> Portal_SectionContent { get; set; }

    }`


`public partial class Certificate_Pool_Info
    {
        public Certificate_Pool_Info()
        {
            Certificate_Pools = new HashSet<Certificate_Pools>();
        }

        public long ID { get; set; }
        [Required]
        public int? PoolID { get; set; }
        public string PoolName { get; set; }
        public string PoolDescription { get; set; }
        public DateTime? CreatedOn { get; set; }
        [MaxLength(450)]
        public string CreatedBy { get; set; }
        [MaxLength(450)]
        public string LastEditBy { get; set; }
        public DateTime? LastEditOn { get; set; }

        public virtual ICollection<Certificate_Pools> Certificate_Pools { get; set; }
        [ForeignKey("CreatedBy")]
        [InverseProperty("Certificate_Pool_InfoCreatedByNavigation")]
        public virtual ApplicationUser CreatedByNavigation { get; set; }
        [ForeignKey("LastEditBy")]
        [InverseProperty("Certificate_Pool_InfoLastEditByNavigation")]
        public virtual ApplicationUser LastEditByNavigation { get; set; }
    }`

**Comment by SimonOrdo** [comment] 2016-05-23 20:45
Okay. This is is somehow related to deriving a secondary DB Context from ApplicationDBContext.

` public class AdminDbContext : ApplicationDbContext
    {
        public AdminDbContext(DbContextOptions options)
        : base(options)
        {
           
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Isengard_Admin_LAP_CertPrintLog>(entity =>
            {
                entity.Property(e => e.CertDate).HasColumnType("datetime");

                entity.Property(e => e.CertNum).HasColumnType("varchar(128)");

                entity.Property(e => e.PrintedOn).HasColumnType("datetime");
            });

            base.OnModelCreating(modelBuilder);
        }

        public virtual DbSet<Admin_LAP_CertPrintLog> Isengard_Admin_LAP_CertPrintLog { get; set; }
    }`

If I have AdminDBContext injected, it bombs out with the above given error.

If I have ApplicationDBContext injected, it works.

**Comment by smitpatel** [comment] 2016-05-23 23:22
I am not able to get a repro here. There are several use defined classes which are not present in the code listing above. Can you work out a repro project and share with us?

**Comment by SimonOrdo** [comment] 2016-05-24 14:39
I will give it a go after work today.  Thanks!

**Comment by ShikiGami** [comment] 2016-05-25 07:43
I'm having the same problem also with key "Id" from ApplicationUser.

**Comment by smitpatel** [comment] 2016-05-25 23:10
@ShikiGami - A repro code would help me out identifying the issue.

**Comment by ShikiGami** [comment] 2016-05-26 05:18
@smitpatel It isn't an specific model that creates this. Basically any database that was created using RC1, and had a foreign key from a table to the default 'Id' form of IdentityUser and uses IdentityDbContext gets this under RC2.

**Comment by smitpatel** [comment] 2016-05-26 22:42
@ShikiGami - Can you post exception you are getting with full stacktrace. If exception is different then please file new issue.
I am trying to create a database using RC1, if you can provide the small repro code for classes added to Identity that would be useful in create RC1 database which fails on migration to RC2.

**Comment by smitpatel** [comment] 2016-05-27 22:51
Got repro for first exception
````
[Fact]
public virtual void Test()
{
    using (var db = new MyContext())
    {
        var model = db.Model;
    }
}

public class MyContext : DbContext
{
    public DbSet<TicketBatch> TicketBatches { get; set; }
    public DbSet<Ticket> Tickets { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<TicketBatch>().Property(e => e.Id).IsRequired(false);
    }
}

public class TicketBatch
{
    public int Id { get; set; }
    public List<Ticket> Tickets { get; set; }
}

public class Ticket
{
    public Guid TicketId { get; set; }

    public TicketBatch TicketBatch { get; set; }
}
```
The issue is when you set `IsRequired(false)` on PK, we remove key defined on that property. Removing key removes referencing FKs but while removing FKs we run conventions which could add another FK referencing same PK again. Which blocks us from removing the key and exception is thrown.
Fix would be to run the conventions on removed fks are after key is removed. So FKs added by convention would not target the key being removed.
Though that is not the only issue for this case. If `Id` property is on `ApplicationUser` is PK and we should try to find out why it is being marked as `required=false`
@SimonOrdo - This would be specific to your model only especially it involves inheritance. Do you have some class which derives from `ApplicationUser` or other way round? Or `ApplicationUser` trying to set some other class as base type.

@ShikiGami - Can you file new issue with the details of exception/stack trace and models used?

**Comment by ShikiGami** [comment] 2016-05-28 04:07
@smitpatel 
Create any model with an IdentityUser default implementation and any other Model with a Foreign key to IdentityUser Id, and you will have this problem.
The stack trace and exception are exactly the same as in this case.

**Comment by smitpatel** [comment] 2016-05-28 04:44
I will give it a try. A side question would be, why the foreign key is pointing to `IdentityUser` and not the `ApplicationUser`?

**Comment by ShikiGami** [comment] 2016-05-28 04:47
@smitpatel ApplicationUser is a name giver to the standard implementation of IdentityUser, so the foreign key is actually pointing to ApplicationUser.

**Comment by smitpatel** [comment] 2016-05-29 00:03
I tried reproducing the error on RC1 -> RC2 migrations.
Env: Windows 10, VS 2015 RTM ASP.NET Web Tools RC1
1. Create new web application from template using individual accounts
2. Add following class to model & corresponding DBSet in `ApplicationDbContext`
As required it contains FK to `ApplicationUser`
```
public class MyEntity
{
	public int Id { get; set; }
	public string ApplicationUserId { get; set; }
	public ApplicationUser ApplicationUser { get; set; }
}
```
I generated migration script to create database - https://gist.github.com/smitpatel/37061fc1266b6ac24911196d7a96693c
I moved whole project folder to another machine
new Env: VS 2015 Update 2. DotNet tools RC2
Converted from a dnx project to dotnet project. Made all changes required for application to compile.
1. Changes in `project.json` structure, package names, versions.
2. Change of namespaces to accommodates name changes
3. Changes to remove compilation error arising from changed API.
4. Added `Program.cs` for `Main` method which was in `Startup` during RC1 time.
`dotnet restore --infer-runtimes` restores all packages successfully and makes `dotnet ef` command available.
I added migration named `Second` which is generated successfully. Migration file - https://gist.github.com/smitpatel/31a3bdf4cf4328aafbc123140caadacb

@ShikiGami - Can you tell me what extra steps needed for repro?

**Comment by smitpatel** [comment] 2016-05-29 00:19
Since we know the bug for the exception though the root cause for reaching that state is still unknown (& can be multiple), I have filed issue #5573 to fix the bug for `RemoveKey` part.

**Comment by SimonOrdo** [comment] 2016-05-31 15:23
@smitpatel I did have the following class, deriving from ApplicationUser

```
namespace AdminWeb
{
    // Add profile data for application users by adding properties to the ApplicationUser class
    public class AdminApplicationUser : ApplicationUser
    {
    
    }
}
```

But, as you can see, it was still empty in this case.

**Comment by smitpatel** [comment] 2016-05-31 23:07
Clearing milestone. Unable to generate a repro here.

**Comment by divega** [comment] 2016-06-07 17:59
Closing as we haven't been able to repro. We can reactivate if additional details are provided that help produce a repro.

**Closed** 2022-10-16 09:41 UTC
