### ISSUE TITLE
Upgrade to Microsoft.EntityFrameworkCore.Sqlite 1.1.0 broke app complaince with WACK

### ISSUE THREAD

**Issue by davesmits** [dotnet/efcore#7040] opened 2016-11-17 20:46 UTC
Edited by @rowanmiller 11-29-2016

We are shipping a fix for this, but if you hit the issue in the meantime, you can install NuGet 3.5 to resolve the issue http://blog.nuget.org/20161027/Announcing-NuGet-3.5-RTM.html.

---

### Steps to reproduce
Build an app that exists of 3 projects
- the app
- winmd component with background task
- class library to share code between the to other projects

Reference Microsoft.EntityFrameworkCore.Sqlite 1.1.0 in your class library. Run wack tool

### The issue
Wack tool will report that the SQLite that is been dragged in by Microsoft.EntityFrameworkCore.Sqlite is not valid for use in UWP. Unallowed api calls to windows.
```

**Comment by ajcvickers** [comment] 2016-11-22 21:31
Confirmed that this repros. Errors are:

```
API AreFileApisANSI in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CompareStringA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CompareStringW in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CreateFileA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CreateFileMappingA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CreateFileMappingW in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CreateFileW in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API EnumSystemLocalesA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API ExitProcess in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API FatalAppExitA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.

File c:\program files\windowsapps\31e90d02-67e5-4376-8af6-1cf08b320c37_1.0.1.0_x64__detvjq7nkjf78\sqlite3.dll has failed the AppContainerCheck check.
File c:\program files\windowsapps\31e90d02-67e5-4376-8af6-1cf08b320c37_1.0.1.0_x64__detvjq7nkjf78\sqlite3.dll has failed the DBCheck check.
```

**Comment by ajcvickers** [comment] 2016-11-22 21:31
@bricelam Any ideas on this?

**Comment by bricelam** [comment] 2016-11-22 22:50
Hmm, sqlite3.dll on UWP shouldn't be using kernel32... Bad SQLite release?

**Comment by bricelam** [comment] 2016-11-22 22:51
Does downgrading the SQLite package fix it?

**Comment by davesmits** [comment] 2016-11-23 09:29
Yes downgrade to 1.0.1 fixed issue for me again

**Comment by divega** [comment] 2016-11-23 09:36
@davesmits - @bricelam meant to actually downgrade the `SQLite` package which contains the native binaries for SQLite, and not `Microsoft.EntityFrameworkCore.Sqlite`.

**Comment by ajcvickers** [comment] 2016-11-23 21:38
@davesmits @divega @bricelam It appears to be an issue with version 3.13 of the "sqlite" package. Explicitly installing version 3.12.3 while leaving all other packages the same appears to fix the problem. This seems like a reasonable workaround for now. Marking bug for re-triage so it can be assigned and followed up on appropriately.

**Comment by divega** [comment] 2016-11-24 00:11
@natemcmaster any suggestions on how to deal with this: https://github.com/aspnet/EntityFramework/issues/7040#issuecomment-262636133?

**Comment by natemcmaster** [comment] 2016-11-28 17:08
I couldn't reproduce with VS 2015 u3, NuGet 3.5.0.1737. I'm guessing the solution will be to upgrade the NuGet extension. sqlite 3.13.0 relies on the the `/runtimes/{rid}/nativeassets/{tfm}` layout which was added in NuGet 3.5 beta2 (see https://github.com/NuGet/Home/issues/2782).

@davesmits @ajcvickers what version of NuGet and Visual Studio are you using?

**Comment by ajcvickers** [comment] 2016-11-28 17:42
@natemcmaster VS 2015 Update 2; NuGet 3.4.4

**Comment by natemcmaster** [comment] 2016-11-28 17:54
The latest NuGet RTM release is 3.5.0. https://dist.nuget.org/index.html. Upgrading should solve the issue.

If users don't want to upgrade to NuGet 3.5, they can do as @ajcvickers suggested earlier- explicitly install SQLite 3.12.3

**Comment by ajcvickers** [comment] 2016-11-28 17:58
@natemcmaster How should I discover that I need to update my NuGet? Was there a notification that I missed? Some warning that I missed when installing the package? Or should this be an issue filed on NuGet that there is no way to know that it needs to be updated?

**Comment by divega** [comment] 2016-11-28 18:06
Is there a way to make a package **require** the new version of NuGet?

**Comment by natemcmaster** [comment] 2016-11-28 18:08
> How should I discover that I need to update my NuGet?

That's a good question for the NuGet team. It doesn't look like 3.5.0 has been pushed to the VS Gallery yet. 
https://marketplace.visualstudio.com/items?itemName=NuGetTeam.NuGetPackageManagerforVisualStudio2015 still shows 3.4.4

>  Is there a way to make a package require the new version of NuGet?

Yes, but we opted not to use it. We intentionally left the "minClientVersion" in [SQLite nuspec](https://github.com/natemcmaster/libsqlite3-package/blob/v3.13.0/SQLite.nuspec#L3) at 2.12 to preserve compatibility with NuGet 2 projects. UWP is the only platform that requires this upgrade to 3.5.0. There is no way to express `if UWP, require NuGet >= 3.5. Else require NuGet >= 2.12` AFAIK

cc @rrelyea @yishaigalatzer

**Comment by ErikEJ** [comment] 2016-11-28 18:11
@ajcvickers @natemcmaster The NuGet team made a deliberate decision not to auto update: http://blog.nuget.org/20161027/Announcing-NuGet-3.5-RTM.html

**Comment by natemcmaster** [comment] 2016-11-28 18:21
Wow. Would love to have heard the conversation about why VS decided to abandon the VS gallery update story.

Thanks for pointing that out @ErikEJ.

**Comment by rowanmiller** [comment] 2016-11-28 19:15
@natemcmaster can you push an update to `SQLite` to resolve this. We should either require 3.5 or not use the 3.5 features. If we require 3.5 we should make sure it is available everywhere (Xamarin, VS Code, etc.).  This is critical, so putting in the 1.1.1 patch milestone.

**Comment by natemcmaster** [comment] 2016-11-28 22:40
It looks like changing the SQLite package won't make a difference. minClientVersion isn't respected by installation by NuGet 3.4.4 on UWP projects. cref https://github.com/NuGet/Home/issues/942.

**Comment by natemcmaster** [comment] 2016-11-29 19:13
To get this change into EF, we'll need to upgrade to Microsoft.Data.Sqlite 1.1.1

**Comment by bricelam** [comment] 2016-11-29 21:09
Marking for re-triage so we can assign someone else to handle the EFCore/Microsoft.Data.Sqlite updates.

**Comment by rowanmiller** [comment] 2017-01-18 19:56
Closing as we are concerned about unknown side effects of this for various project types etc. NuGet 3.5 will become more widely adopted in the near future.

**Closed** 2022-10-16 10:42 UTC
Labels: closed-out-of-scope
