### ISSUE TITLE
EF Core Migrations initial scaffolding removes dependent assemblies from project

### ISSUE THREAD

**Issue by alexkeh** [dotnet/efcore#13447] opened 2018-09-28 23:47 UTC
I am using Visual Studio 2017 (15.8.5). I create a .NET Core console project in order to create a simple EF Core app using SQL Server.

I add the latest production versions of Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore.Design assemblies (versions 2.1.3) into the project via NuGet. I then add the typical getting started demo using the BloggingContext EF Core sample. I save the project. 

I then open the Package Manager Console in Visual Studio. I then change to the project directory. I then issue the command "dotnet ef migrations add InitialCreate -v" in order to scaffold the migration to create the initial set of tables to represent the model, which results in a failed build. 

When I view Solution Explorer, the NuGet packages are missing. 

As a workaround, I can close and re-open Visual Studio. The packages will now 
be back in Solution Explorer. When I run the same command again, it executes 
successfully. 

```
Here's the verbose trace from the migrations add command with some redactions to remove personal info:
```
[SQL Server ef verbose - redacted.txt](https://github.com/aspnet/EntityFrameworkCore/files/2430038/SQL.Server.ef.verbose.-.redacted.txt)

**Comment by alexkeh** [comment] 2018-09-28 23:49
I've also reproduced this issue with my team's own DB provider. This bug is not a SQL Server-specific issue, but something that is related to the add migrations command.

**Comment by divega** [comment] 2018-09-29 01:10
@alexkeh Thanks for reporting this. I was able to repro most of what you are seeing. However this seems to be a usability issue with NuGet in Visual Studio, and it only affects the first time you try to execute the commands just after adding the packages. 

The reason for these errors is that at the point you run `dotnet ef` (either from the PMC or a regular command line), Visual Studio has not saved the csproj file containing the package references you just added using NuGet. 

If you just try `dotnet build`, you will get the same errors.

If I <kbd>Ctrl+S</kbd> on the project file however in solution explorer or the editor, the commands run correctly. 

I am not sure if the fact that NuGet doesn't save the when you install the package (either using the UI or the PMC) has always been the behavior or if it is by design. This is something we will have to follow up on with the NuGet team. 

Note that if you haven't added a reference to Microsoft.EntityFrameworkCore.Design, you will get an error indicating that this reference is needed before you can use `dotnet ef`. But this is expected, at least currently. 

Also, one possibly important reason we don't get complains about this more often, is that the PMC command (in this case `add-migration`) is integrated with the Visual Studio project system and does take care of saving the project file before it tries to build.

**Comment by divega** [comment] 2018-09-30 20:42
@alexkeh yes, it is expected that you have to add Microsoft.EntityFrameworkCore.Tools in order to have access to the PMC tools. 

I prefer to leave this open though, to have a chance to review in our triaga, mainly because I would like to understand if the behavior of NuGet is by-design before we close this.

**Comment by divega** [comment] 2018-09-30 20:45
BTW, our documentation for this area has been recently updated. See

- https://docs.microsoft.com/en-us/ef/core/get-started/install/#get-entity-framework-core-tools
- https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell
- https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet.

**Comment by divega** [comment] 2018-10-06 15:29
@davkean this is the issue I told you about last night. I searched in 
https://github.com/dotnet/project-system but I was not able to find a previously reported issue. I will go ahead and move this one, but feel to close as duplicate.

**Comment by divega** [comment] 2018-10-06 15:31
This issue was moved to dotnet/project-system#4092

**Closed** 2022-10-16 13:33 UTC
Labels: closed-external, customer-reported
