### ISSUE TITLE
JsonColumns vs ExecuteUpdateAsync + custom serializer for JsonColums

### ISSUE THREAD

**Issue by buratinio** [dotnet/efcore#29675] opened 2022-11-25 10:01 UTC
Is it possible to use json columns and use execute update at the same time?

For example, in your example(JsonColumns: https://github.com/ajcvickers/JsonColumns/blob/main/JsonColumns/Program.cs), if I do this in line 43:
await context.Customers
    .Where(customer => customer.InformalName == "Alice")
    .ExecuteUpdateAsync(x => x.SetProperty(x => x.FullName, x=> "Mrs. " + x.FullName));
 
there is an exception, although I can run a query in the database:
UPDATE dbo.Customers c
SET c.FullName = N'Mrs. ' + c.FullName
WHERE c.InformalName = N'Alice'

The exception would make sense if json columns were affected.
Is there any way to configure it to work the way I described?

Also, is it possible to change the serializer for json columns to custom, since the default is PascalCase, but I would like snake_case or another?
Well, other than jsonPropertyName attribute or .HasJsonPropertyName.
I mean for all entities, one custom json serializer.

**Comment by ajcvickers** [comment] 2022-11-25 10:23
Duplicate of #28727 and #28043. Make sure to vote (👍) for those issues.

**Closed** 2022-11-28 13:25 UTC
Labels: customer-reported
