### ISSUE TITLE
EF migrations incorrect generation for tables renaming

### ISSUE THREAD

**Issue by ion-sapoval** [dotnet/efcore#4408] opened 2016-01-27 10:26 UTC
<b>Steps to reproduce:</b>
1. Create, by using migrations, corresponding tables in database for the new entities (with fks)
2. For entities from point 1 we are modifying table names (ex: builder.Entity< Status >().ForSqlServerToTable("Statuses");)
3. Generate migration for the new changes

<b>Result/Error:</b> 
Order of the statements is incorrect in the migration file. First it tries to drop fks from existing tables then it tries to create fks for the new/renamed tables and only after that it tries to rename tables. Renaming tables should be added before creating fks for renamed tables, otherwise it will run with errors.

**Comment by smitpatel** [comment] 2016-01-27 16:51
dupe of #3990

**Closed** 2022-10-16 09:26 UTC
