### ISSUE TITLE
Join to Select with GroupBy fails with error "Nullable object must have a value"

### ISSUE THREAD

**Issue by timClyburn** [dotnet/efcore#12663] opened 2018-07-13 11:38 UTC
I have a simple select from a table joining on to a second table containing notes. I am trying to determine if the second table has any values.
The query looks like this:
```
return from recording in context.EventRecordings
where recording.TenantGUID == tenant
join n1 in
                       (from note in context.Notes
                        group note by note.EventRecordingID into g
                        select new { EventRecordingID = g.Key })
                       on new { recording.EventRecordingsID }
                       equals new { EventRecordingsID = n1.EventRecordingID } into noteGroup
                   from noteTemp in noteGroup.DefaultIfEmpty()
select new {
Id = recording.EventRecordingsID.ToString(),
 HasNote = noteTemp !=null
}
```

The generated sql looks correct:
```
SELECT [t].[EventRecordingsID], [recording].[EventRecordingsID] AS [Id], [recording].[DateRecorded]
FROM [uri].[EventRecordings] AS [recording]
LEFT JOIN (
    SELECT [note].[EventRecordingID] AS [EventRecordingsID]
    FROM [uri].[Notes] AS [note]
    GROUP BY [note].[EventRecordingID]
) AS [t] ON [recording].[EventRecordingsID] = [t].[EventRecordingsID]
WHERE ([recording].[TenantGUID] = @__tenant_0) 
```
But I get an exception:

```
Exception message:
An exception occurred in the database while iterating the results of a query for context type '<removed>.recordingsContext'.
System.InvalidOperationException: Nullable object must have a value.
Stack trace:
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at lambda_method(Closure , QueryContext , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IShaper<TResult>.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()

System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at lambda_method(Closure , QueryContext , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IShaper<TResult>.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.dll
```

### Further technical details
EF Core version: Microsoft.EntityFrameworkCore.SqlServer 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 version 1803 (OS Build 17134.112)
IDE: Visual Studio 2017 15.7.2)

**Comment by dalibor983** [comment] 2018-07-13 12:02
I think that ef core cannot translate ```GroupBy``` to SQL.
Whenever I have ```GroupBy``` calls i'v got warning with
```
EF Core could not be translated and will be evaluated locally
```
and all other calls like ```Take, OrderBy, Skeep``` will be evaluated in memory (all data will be pulled from database in memory, it means that if your query working with billion records in database all will be pulled in local memory) :(

**Comment by timClyburn** [comment] 2018-07-13 12:09
@dalibor983, I don't think that you are correct, according to this link [https://docs.microsoft.com/en-gb/ef/core/what-is-new/ef-core-2.1#linq-groupby-translation](url) group by is supported in 2.1.1, which is the version that I am using. And if you see the generated sql in my post it is performing creating the correct group by query.

**Comment by dalibor983** [comment] 2018-07-13 13:02
@timClyburn I have **Order** and **Product** entities **N:M** related. Relation entity is **OrderItem**.

You think that ef core 2.1.1 can translate this query to SQL:
```c#
var query = from order in Database.Orders
    join orderItemTmp in Database.OrderItems on order.Id equals orderItemTmp.OrderId into orderItemGj
    from orderItem in orderItemGj.DefaultIfEmpty()
    join productTmp in Database.Products
        on new {Id = orderItem == null ? Guid.Empty : orderItem.ProductId}
        equals new {productTmp.Id} into productGj
    from product in productGj.DefaultIfEmpty()
    group new {Order = order, Product = product} by order into g
    select new
    {
        Order = g.Key,
        Products = g.Select(x => x.Product)
    };

var result = query
    .OrderBy(x => x.Order.Id)
    .Skip(10)
    .Take(10)
    .ToList();
```

**Comment by timClyburn** [comment] 2018-07-13 20:19
@dalibor983 according to this blog its possible: [https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-1-the-basics/](url) but I haven't tried it yet to see if it works.
This issue says they are working on a way to remove CLR class for the join table: [https://github.com/aspnet/EntityFrameworkCore/issues/1368](url)

**Comment by timClyburn** [comment] 2018-07-13 22:44
I think I have solved my the problem, by changing the type of what I am returning I seem to get accurate sql and no errors:
```c#
return from recording in context.EventRecordings
where recording.TenantGUID == tenant
join n1 in
                       (from note in context.Notes
                        group note by note.EventRecordingID into g
                        select new { EventRecordingID = (long?)g.Key })
                       on new { recording.EventRecordingsID }
                       equals new { EventRecordingsID = n1.EventRecordingID.Value } into noteGroup
                   from noteTemp in noteGroup.DefaultIfEmpty()
select new {
Id = recording.EventRecordingsID.ToString(),
 HasNote = noteTemp !=null
}
```

**Comment by dalibor983** [comment] 2018-07-15 08:39
You can try something like this:

```c#
from recording in context.EventRecordings
join noteTemp in context.Notes on recording.EventRecordingsID equals noteTemp.EventRecordingID into noteGj
from note in noteTemp.DefaultIfEmpty()
where recording.TenantGUID == tenant
group new {Recording = recording, Note = note} by recording into g
select new {
 Id = g.Key.EventRecordingsID.ToString(),
 HasNote = g.Any(x => x.Note != null)
}
```

**Comment by smitpatel** [comment] 2018-07-17 19:56
Duplicate of #12355

**Comment by timClyburn** [comment] 2018-07-18 07:30
@maumar @smitpatel I have worked round the initial issue, but now face the problem I mentioned a couple of days ago where the sql is not reflecting any mapping done on a field in the sub-query so I can't filter on any of those fields without bringing the data into memory. This query may be iterating over millions of rows meaning in memory is plausible.

**Closed** 2022-10-16 13:19 UTC
Labels: type-bug, closed-duplicate, customer-reported
