### ISSUE TITLE
Is there a way to use interfaces with EF Core?

### ISSUE THREAD

**Issue by bar10dr** [dotnet/efcore#29245] opened 2022-10-01 05:09 UTC
Given the following interface

```C#
public interface IScheduledRunTime
{
    [Key]
    Guid ScheduledRunTimeId { get; set; }
    DateTime StartDateToday { get; }
    bool DoIRunAtDay(DateTime Date);
    bool DoIRunNow(DateTime Date);
}
```

And the following implementations

```C#
public class ScheduledRunTimeStatic : IScheduledRunTime
{
    [Key]
    public Guid ScheduledRunTimeId { get; set; } = Guid.NewGuid();
    public DateTime DateStart { get; set; }
    public DateTime DateStop { get; set; }

    public DateTime StartDateToday => DateStart;

    public bool DoIRunAtDay(DateTime Date)
    {
        return (DateStart.Date >= Date.Date) && (DateStop.Date > Date.Date);
    }

    public bool DoIRunNow(DateTime Date)
    {
        return (DateStart <= Date) && (DateStop < Date);
    }
}
```

```C#
public class ScheduledRunTimeRepeating : IScheduledRunTime
{
    [Key]
    public Guid ScheduledRunTimeId { get; set; } = Guid.NewGuid();
    public ScheduleDay Day { get; set; }
    public DateTime FromDate { get; set; }

    public DateTime StartDateToday => FromDate;

    public bool DoIRunAtDay(DateTime Date)
    {
        return FromDate.Date >= Date.Date;
    }

    public bool DoIRunNow(DateTime Date)
    {
        return FromDate <= Date;
    }
}
```

Used in a class

```C#
public class VenueLink
{
    [Key]
    public Guid VenueLinkId { get; set; } = Guid.NewGuid();
    public IScheduledRunTime ScheduledRunTime { get; set; }
}
```

When trying to use VenueLink with EF Core, an error message pops up telling me EF Core cannot store interfaces, or that the interface has to be mapped to one specific implementation?

> System.InvalidOperationException: 'The property 'VenueLink.ScheduledRunTime' is of an interface type ('IScheduledRunTime'). If it is a navigation, manually configure the relationship for this property by casting it to a mapped entity type. Otherwise, ignore the property using the [NotMapped] attribute or 'Ignore' in 'OnModelCreating'.'

Is there a way around this problem or should I find a different solution for my implementation?

_EF Core version: 7.0.0-rc.1.22426.7
Database provider: Microsoft.EntityFrameworkCore.In-Memory
Target framework: .NET 6.0_

**Comment by ComptonAlvaro** [comment] 2022-10-04 08:39
I face this problem too when I wanted to use the state pattern with interfaces. But in my case, I could use abstract classes instead of interfaces, that for the state pattern is the same.

You could try something like that, because I am not sure if to use [key] in the derived classes it is needed or not, just it is a general vision how to implement abstract classes.

```
public abstract class ScheduledRunTimeBase
{
    [Key]
    abstract Guid ScheduledRunTimeId { get; set; }
    abstract DateTime StartDateToday { get; }
    abstract bool DoIRunAtDay(DateTime Date);
    abstract bool DoIRunNow(DateTime Date);
}




public class ScheduledRunTimeStatic : ScheduledRunTimeBase
{
    [Key]
    public override Guid ScheduledRunTimeId { get; set; } = Guid.NewGuid();
    public override DateTime DateStart { get; set; }
    public override DateTime DateStop { get; set; }

    public override DateTime StartDateToday => DateStart;

    public override bool DoIRunAtDay(DateTime Date)
    {
        return (DateStart.Date >= Date.Date) && (DateStop.Date > Date.Date);
    }

    public override bool DoIRunNow(DateTime Date)
    {
        return (DateStart <= Date) && (DateStop < Date);
    }
}
    

public class ScheduledRunTimeRepeating : ScheduledRunTimeBase
{
    [Key]
    public override Guid ScheduledRunTimeId { get; set; } = Guid.NewGuid();
    public override ScheduleDay Day { get; set; }
    public override DateTime FromDate { get; set; }

    public override DateTime StartDateToday => FromDate;

    public override bool DoIRunAtDay(DateTime Date)
    {
        return FromDate.Date >= Date.Date;
    }

    public override bool DoIRunNow(DateTime Date)
    {
        return FromDate <= Date;
    }
}
```

**Comment by ajcvickers** [comment] 2022-10-04 18:07
Duplicate of #13344.

**Closed by ajcvickers** 2022-10-04 18:07 UTC
Labels: customer-reported
