### ISSUE TITLE
Unable to find provider assembly with name Microsoft.EntityFrameworkCore.SqlServer. Ensure the specified name is correct and is referenced by the project.

### ISSUE THREAD

**Issue by koushik-aravalli** [dotnet/efcore#7027] opened 2016-11-16 12:51 UTC
### Steps to reproduce
1. Create a class Library-.Net core
2. Add Following Dependencies:

```
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
```
### The issue
When performing Scaffold-Dbcontext towards a SqlServerDB like below, Microsoft.EntityFramework.SqlServer dll is not resolved.. 
Scaffold-DbContext "Server={ConnectionString}" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -verbose
```
Exception message:
Stack trace:
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to find provider assembly with name Microsoft.EntityFrameworkCore.SqlServer. Ensure the specified name is correct and is referenced by the project. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.SqlServer, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.GetProviderDesignTimeServices(String provider, Boolean throwOnError)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.GetProviderDesignTimeServices(String provider, Boolean throwOnError)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(String provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContextAsync(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<ScaffoldContextImpl>d__22.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to find provider assembly with name Microsoft.EntityFrameworkCore.SqlServer. Ensure the specified name is correct and is referenced by the project.
```
### Further technical details

EF Core version: (found in project.json or packages.config)
Operating system: 
Visual Studio version: (e.g. VS 2013 or n/a)

Project.json:
```
{
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "NETStandard.Library": "1.6.1"
  },

  "frameworks": {
    "netcoreapp1.0": {
    },
    "netstandard1.6": {
      "imports": "dnxcore50"
    }
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final"
  },

  "buildOptions": {
    "emitEntryPoint": false,
    "preserveCompilationContext": true
  }

}
```

**Comment by bricelam** [comment] 2017-01-13 02:41
@koushik984 Are you able to repro this on the latest bits? (See #7358 for how to try them out) If so, could you share your project so we can investigate further?

**Comment by bricelam** [comment] 2017-01-24 19:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Comment by eliziario** [comment] 2017-02-08 14:49
Still happening with latest bits in a csproj project. 

`<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="$(GlobalExclude)" />
    <EmbeddedResource Include="**\*.resx" Exclude="$(GlobalExclude)" />
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <None Include=".dockerignore">
      <DependentUpon>Dockerfile</DependentUpon>
    </None>
    <None Include="docker-compose.override.yml">
      <DependentUpon>docker-compose.yml</DependentUpon>
    </None>
    <None Include="docker-compose.vs.debug.yml">
      <DependentUpon>docker-compose.yml</DependentUpon>
    </None>
    <None Include="docker-compose.vs.release.yml">
      <DependentUpon>docker-compose.yml</DependentUpon>
    </None>
    <None Include="docker-compose.yml" />
    <None Include="Dockerfile" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore">
      <Version>1.2.0-preview1-23339</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <Version>1.2.0-preview1-23339</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer">
      <Version>1.2.0-preview1-23339</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design">
      <Version>1.2.0-preview1-23339</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <Version>1.2.0-preview1-23339</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Sdk.Web">
      <Version>1.0.0-alpha-20161104-2-112</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Routing">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Console">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.Design">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore">
      <Version>1.0.0-rc1</Version>
    </PackageReference>
   
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.csproj" />
    
  </ItemGroup>

  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>`

**Comment by bricelam** [comment] 2017-02-08 16:27
@eliziario Did you try with ***Microsoft**.EntityFrameworkCore.SqlServer*?

Everything else looks right.

**Comment by eliziario** [comment] 2017-02-08 18:55
Yes, tried with it also. See the first try on PackageManager console above.

**Comment by eliziario** [comment] 2017-02-08 18:56
I was thinking about debugging it, is there are any guide for how to debug this with VS?

**Comment by bricelam** [comment] 2017-02-08 19:22
Adding `-Verbose` gives additional information that may help you debug the issue.

**Comment by eliziario** [comment] 2017-02-08 19:31
```
Using project 'src\Shared'.
Using startup project 'src\Voejar'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile "C:\Users\marcos\documents\visual studio 2017\Projects\Voejar\src\Voejar\bin\Debug\netcoreapp1.0\Voejar.deps.json" --additionalprobingpath C:\Users\marcos\.nuget\packages --runtimeconfig "C:\Users\marcos\documents\visual studio 2017\Projects\Voejar\src\Voejar\bin\Debug\netcoreapp1.0\Voejar.runtimeconfig.json" C:\Users\marcos\.nuget\packages\microsoft.entityframeworkcore.tools\1.2.0-preview1-23339\tools\netcoreapp1.0\ef.dll dbcontext scaffold "Data Source=REDACTED;Initial Catalog=BookingDB_ERP_BC_Live;Persist Security Info=True;User ID=sa;Password=REDACTED" Microsoft.EntityFrameworkCore.SqlServer --json --output-dir Models --verbose --no-color --prefix-output --assembly "C:\Users\marcos\documents\visual studio 2017\Projects\Voejar\src\Voejar\bin\Debug\netcoreapp1.0\Shared.dll" --startup-assembly "C:\Users\marcos\documents\visual studio 2017\Projects\Voejar\src\Voejar\bin\Debug\netcoreapp1.0\Voejar.dll" --project-dir "C:\Users\marcos\documents\visual studio 2017\Projects\Voejar\Shared" --content-root "C:\Users\marcos\documents\visual studio 2017\Projects\Voejar\src\Voejar" --data-dir "C:\Users\marcos\documents\visual studio 2017\Projects\Voejar\src\Voejar\bin\Debug\netcoreapp1.0\\" --root-namespace Shared
Using assembly 'Shared'.
Using startup assembly 'Voejar'.
Using application base 'C:\Users\marcos\documents\visual studio 2017\Projects\Voejar\src\Voejar\bin\Debug\netcoreapp1.0'.
Using content root 'C:\Users\marcos\documents\visual studio 2017\Projects\Voejar\src\Voejar'.
Using root namespace 'Shared'.
Using project directory 'C:\Users\marcos\documents\visual studio 2017\Projects\Voejar\Shared'.
Using data directory 'C:\Users\marcos\documents\visual studio 2017\Projects\Voejar\src\Voejar\bin\Debug\netcoreapp1.0\'.
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to find design-time provider assembly. Please install the Microsoft.EntityFrameworkCore.SqlServer.Design NuGet package and ensure that the package is referenced by the project. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.SqlServer.Design, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.GetProviderDesignTimeServices(String provider, Boolean throwOnError)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.GetProviderDesignTimeServices(String provider, Boolean throwOnError)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(String provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContextAsync(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<ScaffoldContextImpl>d__22.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to find design-time provider assembly. Please install the Microsoft.EntityFrameworkCore.SqlServer.Design NuGet package and ensure that the package is referenced by the project.

**Comment by bricelam** [comment] 2017-02-09 17:34
Do your projects look right?
Project: `Shared` (where the classes should be added)
Startup project: `Voejar` (references `Shared` and has `Microsoft.EntityFrameworkCore.SqlServer`, `Microsoft.EntityFrameworkCore.SqlServer.Design` & `Microsoft.EntityFrameworkCore.Tools` installed)

If so, could you provide your solution so we can investigate further?

**Comment by eliziario** [comment] 2017-02-13 13:55
https://drive.google.com/open?id=0ByIzqvWEVqZuWlhMRm53ZWV0dnc

**Comment by pantonis** [comment] 2017-02-20 08:25
Have the same problem on a .NET 4.6 class library project with windows service project

"Unable to find design-time provider assembly. Please install the Microsoft.EntityFrameworkCore.SqlServer.Design NuGet package and ensure that the package is referenced by the project"

**Comment by pantonis** [comment] 2017-02-20 09:04
@eliziario as a temporary workaround I downgraded back to EF Core 1.0.2 and Microsoft.EntityFrameworkCore.Tools 1.0.0-preview2-final and I am not getting this problem.

**Comment by ajcvickers** [comment] 2017-03-06 19:06
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Comment by rowana16** [comment] 2018-05-15 12:10
Ok been fighting this for a bit with the newest bits, but have solved it.
It's really easy to replicate.  I was following this [walkthrough](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db):  but skipped the create a db part since I already have one.
In the 'Reverse Engineer Your Model' section, instead of using this whole command, omit the bold part: 
Scaffold-DbContext "Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;" **Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models**

Which will lead you down this path: 
Supply values for the following parameters:
Provider: _Microsoft.EntityFrameworCore.SqlServer_
Unable to find provider assembly with name Microsoft.EntityFrameworCore.SqlServer. Ensure the specified name is correct and is referenced by the project.

The command works fine if you just include the part omitted.

**Comment by blackn1ght** [comment] 2018-09-27 16:03
@smitpatel @rowana16 does spell it correctly in the original command though.

I'm having this issue right now.  I've created a new solution with a console application project, and another .NET Core class library project that will contain the EF code, and I've installed the `Microsoft.EntityFrameworkCore.SqlServer` (2.1.3) package, and I'm getting the `Unable to find provider assembly with name Microsoft.EntityFrameworkCore.SqlServer. Ensure the specified name is correct and is referenced by the project.` error

I've run this command successfully multiple times in the recent past, so unsure why this is happening now.

.NET Core 2.1, VS2017

**Comment by ajcvickers** [comment] 2018-09-27 16:32
@blackn1ght Please file a new issue and include a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by blackn1ght** [comment] 2018-09-28 08:16
Created new issue #13436

**Comment by kbrock84** [comment] 2019-11-27 15:04
I ran into this issue, and was able to resolve it by building my project before running the command.

**Closed** 2022-10-16 10:42 UTC
Labels: closed-could-not-reproduce, customer-reported
