### ISSUE TITLE
Where's the Migration Documentation?

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/efcore#8246] opened 2017-04-20 20:22 UTC
When I filter down the [EF Core Docs](https://docs.microsoft.com/en-us/ef/core/) for migrations I'm not finding anything.  Shouldn't I find something?

![image](https://cloud.githubusercontent.com/assets/14079228/25250892/7129c6f0-25e5-11e7-8abb-e888257bce9e.png)

**Comment by bricelam** [comment] 2017-04-21 18:03
Dupe of aspnet/EntityFramework.Docs#204

Until then, the ASP.NET Core docs have a[ great article on EF Core Migrations](https://docs.microsoft.com/aspnet/core/data/ef-mvc/migrations).

**Closed** 2022-10-16 11:02 UTC
Labels: closed-duplicate
