### ISSUE TITLE
"The query has been configured to use 'QuerySplittingBehavior.SplitQuery' and contains a collection in the 'Select' call"

### ISSUE THREAD

**Issue by aradalvand** [dotnet/efcore#22868] opened 2020-10-02 09:01 UTC
Please tell me if this is a duplicate, but:

I want to avoid the "Cartesian Explosion Problem", I noticed that EF Core 5.0 has now the option to enable "split queries".

However, I found out that it's not possible to use split queries when collections are projected:
```csharp
var result = dbContext.Products.AsSplitQuery().Select(p => new BookDto
    {
        Name = p.Name,
        Rates = p.Ratings.Select(r => new RatingDto { Rate = r.Rate }).ToList(),
    }).ToList();
```

This would cause the following exception to be thrown:

> "The query has been configured to use 'QuerySplittingBehavior.SplitQuery' and contains a collection in the 'Select' call, which could not be split into separate query. Please remove 'AsSplitQuery' if applied or add 'AsSingleQuery' to the query."

Why isn't this possible? It seems perfectly reasonable!
**I'm not sure but I believe this used to work in EF Core 2.x**

Will this be implemented? It is very much needed! Thank you!

### Provider and version information:
EF Core version: 5.0.0 RC1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0

**Comment by ilmax** [comment] 2020-10-02 13:22
I just updated to 5 RC1 to test it out in our application and I'm hitting this one a lot meaning.
My scenario is a bit different, I configured the context to use the `UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery)` and then I have a query similar to the following one:

```csharp
var result = context.Products.Select(p => new ProductDto
    {
        Name = p.Name,
        Rates = p.Ratings.Select(r => new RatingDto { Rate = r.Rate }).ToList(),
    }).ToList();
```

My expectation was that setting `UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery)` could revert the behavior to what 2.2 was doing, but either I'm missing something or that's not the case.

I got the why about the exception, but at this point I have choose between changing all the queries (that will just fail at runtime) and add `.AsSingleQuery()` or keep the cartesian explosion issue introduced in 3.1.

Am I missing something?

**Comment by smitpatel** [comment] 2020-10-02 16:42
Duplicate of #21234

**Comment by AradAral** [comment] 2020-10-05 03:21
@smitpatel
Can you tell us sir approximately when would you plan to implement this? I would say this is a somewhat necessary part of the feature you've already implemented, so it'd be very much appreciated is it comes out soon in order to complete the feature.
Thanks in advance. To

**Comment by AradAral** [comment] 2020-10-05 03:26
@ilmax Well, no, you're not missing anything. EF Core 3+ just doesn't have that feature yet.

**Comment by AradAral** [comment] 2020-10-07 14:11
@smitpatel Could you please answer my question 👆 Is appreciate it

**Comment by smitpatel** [comment] 2020-10-07 14:14
Follow #21234 for updates. That issue is in backlog milestone hence it is not going to happen for 5.0. We will consider it for next release.

**Comment by AradAral** [comment] 2020-10-07 14:16
@smitpatel Okay, that sounds great. Thanks.

**Comment by AradAral** [comment] 2020-10-07 14:19
@smitpatel 

> We will consider it for the next release.

Okay, sounds great, it'd be awesome if it'll be added in the next release.

Thanks.

**Comment by johnkwaters** [comment] 2021-03-03 06:53
I am really upset by this. I have been waiting ever since 2.2 for AsSplitQuery. And now that it's here, it can't handle the use case where it's needed! I fetch a deep object graph off my Trip object with the following includes:

 {
                "CurrentBreadcrumb",
                "Route",
                "Route.Driver",
                "Route.StartsAt",
                "Route.StartsAt.TimeZone",
                "Stops",
                "Stops.Location",
                "Stops.Location.TimeZone",
                "Stops.Location.Address",
                "Stops.Location.Address.State",
                "Driver",
                "Legs",
                "Stops.Activities",
                "Stops.Activities.ActivityType",
                "Stops.Activities.Properties",
                "Stops.Activities.SurveyResult",
                "Stops.Activities.Survey",
                "TripErrors",
                "TripErrors.Stop",
                "Metrics"
            });

2.2 did it fast. 3.0. 3.1 and 5.0 use tons of memory and take a minute. SplitQuery wont process it. Am I supposed to hand code all of the parts of assembling this tree? What's the point of an ORM then? Why did you remove this feature and not add back any compatibility?

**Closed** 2022-10-16 19:03 UTC
Labels: customer-reported
