### ISSUE TITLE
Change the object with Owned Entities. properties replacement.

### ISSUE THREAD

**Issue by Ranmoro** [dotnet/efcore#12535] opened 2018-07-03 14:39 UTC
EntityFramework changes the properties of the new Owned object to the properties of the old object in the "Add" operation. The same thing happens with "Attach" action.

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq;

namespace UnitTest.OwnedEntities
{
    public class Book
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public Author Author { get; set; }
    }

    [Owned]
    public class Author
    {
        public string Name { get; set; }

        public string Description { get; set; }
    }

    public class OwnedEntitiesDemoContext : DbContext
    {
        public OwnedEntitiesDemoContext(DbContextOptions options) : base(options) { }

        public DbSet<Book> Books { get; set; }
    }

    [TestClass]
    public class OwnedEntitiesTest
    {
        public static DbContextOptions<OwnedEntitiesDemoContext>
            CreateNewContextOptions(string databaseName)
        {
            var serviceProvider = new ServiceCollection()
                .AddEntityFrameworkInMemoryDatabase()
                .BuildServiceProvider();

            var builder = new DbContextOptionsBuilder<OwnedEntitiesDemoContext>();
            builder.UseInMemoryDatabase(databaseName)
                .UseInternalServiceProvider(serviceProvider);

            return builder.Options;
        }

        [TestMethod]
        public void Owned_Entities_Update()
        {
            var options = CreateNewContextOptions("Owned_Entities_Update");
            using (var context = new OwnedEntitiesDemoContext(options))
            {
                var book = new Book
                {
                    Name = "The Sun also Rises",
                    Author = new Author
                    {
                        Name = "Ernest Hemingway",
                        Description = "Poor Faulkner. Does he really think big emotions come from big words?",
                    }
                };

                context.Books.Add(book);
                context.SaveChanges();
            }

            using (var context = new OwnedEntitiesDemoContext(options))
            {
                var oldBook = context.Books.FirstOrDefault();
                //context.Entry(oldBook).State = EntityState.Detached;
                context.Books.Remove(oldBook);

                // change book
                var newBook = new Book
                {
                    Id = oldBook.Id,
                    Name = "Alice's Adventures in Wonderland",
                    Author = new Author
                    {
                        Name = "Lewis Carroll",
                        Description = null
                    }
                };

                Assert.AreEqual("Alice's Adventures in Wonderland", newBook.Name);
                Assert.AreEqual("Lewis Carroll", newBook.Author.Name);
                Assert.IsNull(newBook.Author.Description);

                //context.Books.Attach(newBook);
                context.Books.Add(newBook);

                Assert.AreEqual("Alice's Adventures in Wonderland", newBook.Name);
                Assert.AreEqual("Lewis Carroll", newBook.Author.Name); // <-- error
                Assert.IsNull(newBook.Author.Description); // <-- error

                context.SaveChanges();
            }
        }
    }
}

```

### Further technical details
EF Core version: Version="2.1.1"
Database Provider:
 "Microsoft.EntityFrameworkCore.InMemory" Version="2.1.1"
 "Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.1"
Operating system: Windows
IDE:  Visual Studio 2017 15.7

**Comment by Ranmoro** [comment] 2018-07-03 14:44
Аfter the actions "Add" and "Attach" Owned Entities of the new object are replaced with Owned Entities of the old object.

**Comment by ajcvickers** [comment] 2018-07-06 20:06
Duplicate of #12118

**Closed** 2022-10-16 13:17 UTC
Labels: closed-duplicate, customer-reported
