### ISSUE TITLE
Lazy Load Proxies No Longer Thread Safe in EF8

### ISSUE THREAD

**Issue by pbarranis** [dotnet/efcore#32490] opened 2023-12-01 23:15 UTC
Upon upgrading to EF8, I immediately ran into an issue with the lazy loading proxies kicking out an exception when running multi-threaded queries across previous loaded data from a disposed context.

According to the quoted "team discussion" here, https://github.com/dotnet/efcore/issues/19414#issuecomment-571757977, "If context has been disposed, then access to the navigation property should be thread-safe. This allows entity instances to be passed and to and used freely in other parts of the application after loading has finished."  This is exactly my scenario (essentially an in-memory cache for my app) which is now failing.

To repro, query any table which has an FK to another table.  The returned data set must be large enough to cause thread conflicts.  100 records and 8 threads typically hits but not always, so I increased the dataset in the repro code.

```C#
var comps = Db.Companies
    .Include(r => r.State)
    .Take(1000)
    .ToList();
Db.Dispose();
Parallel.For(0, 16, id => _ = comps.Count(r => r.State == null));
```

Initially I thought the FK needed to be nullable and this was only hitting on instances where the property was null, but I ruled that out.  Even a non-nullable FK/property causes this bug.

### Exception and Stack Trace
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Collection was modified; enumeration operation may not execute.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.LazyLoader.IsLoading(ValueTuple`2 navEntry)
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.LazyLoader.Load(Object entity, String navigationName)
   at Microsoft.EntityFrameworkCore.Proxies.Internal.LazyLoadingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.InsuredProxy.get_State()
   at **(last line of user code shown above)**
```

### Include provider and version information

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer 8.0.0
Target framework: .NET 8.0
Operating system: Win 11 Home
IDE: Visual Studio 2022 17.8.2

**Comment by ajcvickers** [comment] 2023-12-05 13:51
Duplicate of #32390

**Closed** 2023-12-13 16:13 UTC
Labels: closed-duplicate, customer-reported
