### ISSUE TITLE
Want to migrate on dnx to cli with entity framework core #10196

### ISSUE THREAD

**Issue by ankurjasoria** [dotnet/efcore#10204] opened 2017-11-02 07:39 UTC
Hi Rafael/Arthur ,
Thanks for updating my previous issue #10196 !!
I am facing issue so reopen it again and I have taken  reference below url
https://github.com/dotnet/cli/blob/master/Documentation/ProjectJsonToCSProj.md

and found below issue with migrate command
Error :
PS C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform> dotnet migrate
No executable found matching command "dotnet-migrate"

I have created separate console application with the use of below cli command

dotnet new
dotnet restore
dotnet build
dotnet run

All command working fine but unable to proceed further like What is my next step ?
I am sharing you my powershall command and status as below

PS C:\test3\myApp> dotnet build
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

myApp -> C:\test3\myApp\bin\Debug\netcoreapp2.0\myApp.dll

Build succeeded.
0 Warning(s)
0 Error(s)

Time Elapsed 00:00:01.02
PS C:\test3\myApp> dotnet run
Hello World!
PS C:\test3\myApp> dotnet migrate
No project.json file found in 'C:\test3\myApp'.
Migration failed.
PS C:\test3\myApp>

Please suggest me for same ?

**Comment by ralmsdeveloper** [comment] 2017-11-02 13:40
Hello @Ankurjasoria, the information for this link [migration](https://docs.microsoft.com/dotnet/core/tools/dotnet-migrate) is more up-to-date.

My suggestion is to create a new project and copy the files to your solution.

And make all the adjustments to the files.
Today we are in another scenario, so you better create a new project and make portability

**Comment by ajcvickers** [comment] 2017-11-02 15:36
Duplicate of #10196

**Closed** 2022-10-16 11:56 UTC
