### ISSUE TITLE
Pragma Settings for SQLite

### ISSUE THREAD

**Issue by shlatchz** [dotnet/efcore#5024] opened 2016-04-09 19:23 UTC
The following code

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    var connectionStringBuilder = new SqliteConnectionStringBuilder() { DataSource = Constants.DataDBPath  };
    var connectionString = connectionStringBuilder.ToString();
    var connection = new SQLiteConnection() { ConnectionString = connectionString };
    optionsBuilder.UseSqlite(connection);
}
```

cannot receive pragma settings such as journalmode or syncmode.
How can I apply the pragma settings to the db?

I tried:

```
using (var context = new DataDBContext())
{
    var connection = context.Database.GetDbConnection();
    connection.Open();
    var command = connection.CreateCommand();
    command.CommandText = "PRAGMA synchronous=OFF; PRAGMA journal_mode=OFF; PRAGMA count_changes=OFF; PRAGMA temp_store=OFF; PRAGMA page_size=65536; PRAGMA cache_size=-16777216;";
    command.ExecuteNonQuery();
}
```

but it didn't help.

**Comment by ErikEJ** [comment] 2016-04-10 06:07
You need to do it in the same context as where you are doing the EF data access

**Comment by shlatchz** [comment] 2016-04-10 08:06
Can you please elaborate?
Are you saying that I have to do it each time I modify the DB?

**Comment by rowanmiller** [comment] 2016-04-15 18:33
@natemcmaster can you confirm?

**Comment by rowanmiller** [comment] 2016-05-11 18:48
@natemcmaster ping 😄

**Comment by natemcmaster** [comment] 2016-05-11 22:45
@shlatchz if you want to issue custom pragma statements, you need to do this every time you open a connection. Changing values via pragma statements do not persist across calls to `sqlite_open_v2`. At the moment, we don't have API in `Microsoft.Data.Sqlite.SqlConnection` to support executing something arbitrary (such as issuing pragma statements) everytime a connection opens. 

Moving up a layer in the stack. EntityFramework Core has a class that wraps `SqliteConnection`. This wrapper handles opening/closing SqliteConnection and has its own logic for issuing pragma statements when connections open. See [Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Sqlite/Storage/Internal/SqliteRelationalConnection.cs). EF lets you pass an connection object instead of a connection string if you want to manage the lifecycle of opening/closing a connection yourself.  `UseSqlite(DbConnection connection)`.

**Comment by natemcmaster** [comment] 2016-05-11 23:22
Remarking for triage: what is the work here? Add API to Microsoft.Data.Sqlite or EF?

**Comment by rowanmiller** [comment] 2016-05-12 04:40
@natemcmaster this is mostly to investigate and work out what we should do. It seems like we may want a way to easily configure pragma settings when you setup the context to target SQLite. Or it may be a more general "connection preamble" feature. It's in the 1.0.1 milestone to look at post-RTM though

**Comment by natemcmaster** [comment] 2016-06-18 01:23
I have this given this some consideration and prototyped some designs today. My current thinking leads me to believe we should consider this a duplicate of the lifecycle hooks feature (#626). Most designs I came up with end up working essentially like a general connection preamble feature. This general feature has bigger implications than just SQLite pragmas, so we should probably gather for some design work on this first.

**Comment by rowanmiller** [comment] 2016-07-06 20:51
Closing this issue as the idea of connection preamble is being tracked as part of the bigger Lifecycle Hooks feature (https://github.com/aspnet/EntityFramework/issues/626).

**Comment by rowanmiller** [comment] 2016-07-06 20:52
BTW just to make it explicit - we are not closing this because we aren't planning to implement it. We very much agree this is super useful, it's just already tracked as part of #626.

**Closed by rowanmiller** 2016-07-06 20:51 UTC
