### ISSUE TITLE
Support System.Data.SqlClient library in LINQ to SQL queries

### ISSUE THREAD

**Issue by evannah** [dotnet/efcore#23077] opened 2020-10-22 09:15 UTC
Hello,

Could you please implement support for System.Data.SqlClient library in LINQ queries that are transformed to SQL?

E.g: SqlFunctions.IsNumeric(String) method
https://docs.microsoft.com/en-us/dotnet/api/system.data.objects.sqlclient.sqlfunctions.isnumeric

Thank you in advance.
Best regards.

**Comment by roji** [comment] 2020-10-22 09:53
Duplicate of #23078

**Closed** 2022-10-16 19:06 UTC
Labels: closed-duplicate, customer-reported
