### ISSUE TITLE
Create haskey with nested owned types

### ISSUE THREAD

**Issue by ivanrodriguezfernandez** [dotnet/efcore#17995] opened 2019-09-23 08:13 UTC
I want create a primary key with all properties in value object

I implemented the following entities:

```
public class Dashboard : Entity
    {
        public Dashboard()
        {
            DashboardItems = new List<DashboardItem>();
        }

        public string Name { get; private set; }
        public List<DashboardItem> DashboardItems { get; private set; }

        public Dashboard(string name, List<DashboardItem> dashboardItems)
        {
            Name = name;
            DashboardItems = dashboardItems;
        }

        public void Update(string name, List<DashboardItem> dashboardItems)
        {
            Name = name;
            DashboardItems = dashboardItems;
        }
    }

 public class DashboardItem : ValueObject
    {
        public DashboardItem()
        {

        }
        public DashboardItem(string appViewId, Size size, Position position)
        {
            AppViewId = appViewId;
            Size = size ?? new Size(1, 1);
            Position = position ?? new Position(0, 0);
        }

        public string AppViewId { get; private set; }
        public Size Size { get; private set; }
        public Position Position { get; private set; }
        protected override IEnumerable<object> GetAtomicValues()
        {
            yield return AppViewId;
            yield return Position.X;
            yield return Position.Y;
            yield return Size.Width;
            yield return Size.Height;
        }
    }


  public class Position : ValueObject
    {
        public Position(int x = 0, int y = 0)
        {
            X = x;
            Y = y;
        }

        public int X { get; private set; }

        public int Y { get; private set; }

        protected override IEnumerable<object> GetAtomicValues()
        {
            yield return X;
            yield return Y;
        }
    }
public class Size : ValueObject
    {

        public Size(int width = 0, int height = 0)
        {
            Width = width;
            Height = height;
        }

        public int Width { get; private set; }

        public int Height { get; private set; }

        protected override IEnumerable<object> GetAtomicValues()
        {
            yield return Width;
            yield return Height;
        }
    }
```

With this configuration
```
modelBuilder.Entity<Dashboard>().HasKey(o => o.Id);

            modelBuilder.Entity<Dashboard>().OwnsMany(p => p.DashboardItems, dashboardItemsBuilder =>
            {
                dashboardItemsBuilder.HasForeignKey("DashboardId");

                dashboardItemsBuilder.OwnsOne(x => x.Size);
                dashboardItemsBuilder.OwnsOne(x => x.Position);

                dashboardItemsBuilder.HasKey("DashboardId", "AppViewId", "Size_Height", "Size_Width", "Position_X", "Position_Y");
            });
```
This configuration generate following exception

```
System.InvalidOperationException: The property 'Size_Height' cannot be added to the type 'DashboardItem' because there was no property type specified and there is no corresponding CLR property or field. To add a shadow state property the property type must be specified.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.GetOrCreateProperties(IReadOnlyList`1 propertyNames, Nullable`1 configurationSource, IReadOnlyList`1 referencedProperties, Boolean required, Boolean useDefaultType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.PrimaryKey(IReadOnlyList`1 propertyNames, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.CollectionOwnershipBuilder.HasKey(String[] propertyNames)
```
I pushed this example in 
https://github.com/ivanrodriguezfernandez/ef-core-owned-types

### Further technical details

EF Core version: 2.2.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 2.2
Operating system:
IDE: Visual Studio 2019 16.2.5

**Comment by smitpatel** [comment] 2019-09-27 21:51
@AndriySvyryd - Can you find dupe of this?

**Comment by AndriySvyryd** [comment] 2019-09-27 21:57
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/13566

**Closed** 2022-10-16 14:43 UTC
Labels: customer-reported
