### ISSUE TITLE
Allow Json property to be updated by using ExecuteUpdate or as a single property

### ISSUE THREAD

**Issue by zulander1** [dotnet/efcore#35240] opened 2024-11-29 15:50 UTC
I am using a JSON column. The issue is that I need to update a JSON column without retrieving the full dataset. Obviously, updating multiple sets in one execution is ideal. I know this wasn’t planned a long time ago (https://github.com/dotnet/efcore/issues/32367). I am using NET 9

A potential solution is to use `ExecuteUpdate`: 

Ex.: `context.Orders.Where(F => F.Id == 100000).ExecuteUpdate(f => f.SetProperty(x => x.Agent, new Employee() { EmployeeCode = "123" }));`

Or to allow Property to support complex types
```C#
foreach (var item in Enumerable.Range(1, 3))
{
	Order order = new() { Agent = new Employee() { EmployeeCode = $"123" }, Id = item };

	context.Attach(order);
	context.Entry(order).Property(nameof(Order.Agent)).IsModified = true;
}

context.SaveChanges();
```

**Comment by ajcvickers** [comment] 2024-11-29 16:20
@zulander1 `ExecuteUpdate` can already be used with complex types. This means that when #31252 is implemented, it should also be possible to use complex types mapped to JSON with `ExecuteUpdate`.

Likewise, it is already possible to mark parts of a complex type as Modified. You need to use the `ComplexProperty` method instead of `Property`. For example:

```C#
context.Entry(order).ComplexProperty(nameof(Order.Agent)).IsModified = true;
```

**Comment by ajcvickers** [comment] 2024-11-29 17:26
@zulander1 This is because you are using "owned entity types", rather than complex types. Currently the only way to map to JSON is through owned types, but this support has fundamental limitations, and so we are working on complex types to better support JSON. This is tracked by #31252.

**Comment by zulander1** [comment] 2024-11-29 18:06
Great, thanks, is there any workaround for this ?

**Comment by roji** [comment] 2024-11-30 07:33
Duplicate of #28766

**Comment by roji** [comment] 2024-11-30 07:35
Yeah, as @ajcvickers the best solution here would be to have JSON mapping via complex types; even when that's done, having ExecuteUpdate work inside JSON documents will require some extra work - that's covered by #28766.

In the meantime, you can use SQL as a workaround. If you're OK with loading the entire JSON document, then you can use regular SaveChanges - EF already supports partial updating of JSON documents (when mapped as owned entities).

**Closed by roji** 2024-11-30 07:35 UTC
Labels: customer-reported

**Comment by ajcvickers** [comment] 2024-11-30 10:28
>  EF already supports partial updating of JSON documents (when mapped as owned entities

For example, to mark all properties of an owned entity as modified:

```C#
context.Entry(order)
    .Reference(nameof(Order.Agent))
    .IsModified = true;
```

Or just a single property:

```C#
context.Entry(order)
    .Reference(nameof(Order.Agent))
    .TargetEntry!
    .Property(nameof(Employee.EmployeeCode))
    .IsModified = true;
```
