### ISSUE TITLE
Expanding a base property leads to EF.Property called with wrong property name

### ISSUE THREAD

**Issue by vbray1979** [dotnet/efcore#21546] opened 2020-07-07 13:25 UTC
I can't expand property in base class.

Assemblies affected:
 - Microsoft.AspNetCore.OData 7.4.1
 - EF Core 3.1.5

Reference: https://github.com/OData/WebApi/issues/2213#issuecomment-651991358
I am experiencing the same issue describe in test IV by @eduardoxvii which seems to be an EF Core issue.

Any idea to workaround it ?

**Comment by smitpatel** [comment] 2020-07-07 16:36
Please share a runnable code which shows the linq query and EF Core error. Without any code, we cannot provide any work-around. Further, if you are not writing queries yourself then work-arounds may not work as it involves writing a custom query which gives same result but avoids error code path.

**Comment by ajcvickers** [comment] 2020-07-17 16:00
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:32 UTC
Labels: closed-could-not-reproduce, customer-reported
