### ISSUE TITLE
Migrations with own types and base class

### ISSUE THREAD

**Issue by NooNameR** [dotnet/efcore#10602] opened 2017-12-21 13:30 UTC
Hi guys. I'm trying to use Base Entity and Base Entity Type Configuration implementations. And when i generate first migration, everything is okay. Then I add entity and trying to create new migration and I get migration which drops previous entity.

### Steps to reproduce
Create Base Entity Implementation with own type
```c#
public class Metadata
{
      public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
      public DateTime? UpdatedDate { get; set; }
      public DateTime? DeletedDate { get; set; }
}

public abstract class Entity
{
      public Guid Id { get; set; }
      public Metadata Metadata { get; set; } = new Metadata();
}
```

Then create Base Entity Type Configuration Implementation
```c#
public abstract class EntityConfiguration<T> : IEntityTypeConfiguration<T> where T : class
        {
            public void Configure(EntityTypeBuilder<T> builder)
            {
                builder.ToTable(typeof(T).Name);

                if (typeof(T).BaseType == typeof(Entity))
                    builder.OwnsOne(typeof(Metadata), "Metadata", cfg => { });
            }

            protected virtual void Initialize(EntityTypeBuilder<T> builder)
            {
            }
        }
```

Then create `Item` inherited from `Entity` and configuration from it (inherited from `EntityConfiguration`)
```c#
        public class Item : Entity
        {
            public Item()
            {
            }

            public string Name { get; set; }
        }
        public class ItemEntityConfiguration : EntityConfiguration<Item>
        {
            protected override void Initialize(EntityTypeBuilder<Item> builder)
            {
                //   builder.Property(x => x.Name).HasMaxLength(100).IsRequired();
                base.Initialize(builder);
            }
        }
```

`Context` 
```c#
 public class Context : DbContext
        {
            public Context()
            {
            }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer("connectionString");
            }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                base.OnModelCreating(modelBuilder);
                modelBuilder.ApplyConfiguration(new ItemEntityConfiguration());
            }
        }
```

Initial migration
```c#
  public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Item",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    Name = table.Column<string>(nullable: true),
                    Metadata_CreatedDate = table.Column<DateTime>(nullable: false),
                    Metadata_DeletedDate = table.Column<DateTime>(nullable: true),
                    Metadata_UpdatedDate = table.Column<DateTime>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Item", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Item");
        }
    }
```
Then add new `Item2` and `Item2Configuration`
```c#
 public class Item2 : Entity
        {
            public Item2()
            {
            }

            public string Description { get; set; }
            public decimal Price { get; set; }
        }
public class Item2EntityConfiguration : EntityConfiguration<Item2>
        {
            protected override void Initialize(EntityTypeBuilder<Item2> builder)
            {
                builder.Property(x => x.Price);
                builder.Property(x => x.Description).HasMaxLength(512).IsRequired();
                base.Initialize(builder);
            }
        }
```
add configuration to `Context`
```c#
modelBuilder.ApplyConfiguration(new Item2EntityConfiguration());
```
New migration will looks like this
```c#
public partial class Item2 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_Item",
                table: "Item");

            migrationBuilder.DropColumn(
                name: "Name",
                table: "Item");

            migrationBuilder.RenameTable(
                name: "Item",
                newName: "Item2");

            migrationBuilder.AddColumn<decimal>(
                name: "Price",
                table: "Item2",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddPrimaryKey(
                name: "PK_Item2",
                table: "Item2",
                column: "Id");

            migrationBuilder.CreateTable(
                name: "Item",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    Description = table.Column<string>(nullable: true),
                    Name = table.Column<string>(nullable: true),
                    Metadata_CreatedDate = table.Column<DateTime>(nullable: false),
                    Metadata_DeletedDate = table.Column<DateTime>(nullable: true),
                    Metadata_UpdatedDate = table.Column<DateTime>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Item", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Item");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Item2",
                table: "Item2");

            migrationBuilder.DropColumn(
                name: "Price",
                table: "Item2");

            migrationBuilder.RenameTable(
                name: "Item2",
                newName: "Item");

            migrationBuilder.AddColumn<string>(
                name: "Name",
                table: "Item",
                nullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_Item",
                table: "Item",
                column: "Id");
        }
    }
```

### Further technical details
EF Core version:
```xml
 <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
  </ItemGroup>
```
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by smitpatel** [comment] 2017-12-21 20:40
Duplicate of #10334 & 
Duplicate of #10099

**Closed** 2022-10-16 12:03 UTC
