### ISSUE TITLE
Did MaxBatchSize defaults change in EF Core 5?

### ISSUE THREAD

**Issue by colinblaise** [dotnet/efcore#24523] opened 2021-03-26 17:14 UTC
## Ask a question

Did MaxBatchSize change in EF Core 5?

We never specified the max batch size before, but after upgrading to EF Core 5, we found that when calling `DbContext.SaveChanges()` with about ~1900 updated objects, the query never actually executes and seemingly deadlocks.  `DbContext.SaveChanges()` never returns.

After adding ` sqlOptions.MaxBatchSize(100);`, `DbContext.SaveChanges()` worked as expected.  Again, we never had this problem before upgrading to EF Core 5.

### Include provider and version information

EF Core version: 5.0.4
Database provider: Npgsql
Database: Postgres 11
Target framework: (e.g. .NET 5.0)
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.4

**Comment by roji** [comment] 2021-03-27 09:01
Nothing comes to mind - AFAIK the default maximum batch size in EFCore.PG has been 1000 for years... However, since this could be a race-condition-sensitive thing, it may be that other changes in EF Core 5 cause the deadlock to appear, where in a previous version it happened to not manifest itself.

Are you seeing this happening consistency, in a deterministic manner? If so, can you submit a minimal, runnable code sample?

**Comment by colinblaise** [comment] 2021-03-29 16:25
Yes, we were able to reproduce it consistently within our own project.

I'll see what I can about getting you a code sample.

**Comment by ajcvickers** [comment] 2021-04-09 16:21
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:29 UTC
Labels: closed-could-not-reproduce, customer-reported
