### ISSUE TITLE
.HasValue property on a nullable type doesn't seem to be translated

### ISSUE THREAD

**Issue by scottdorman** [dotnet/efcore#13070] opened 2018-08-21 18:37 UTC
Given the following (simplified) model

```csharp
public class Event
{
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public intId { get; set; }
        public DateTime Occurred { get; set; }
        public DateTime? Cleared { get; set; } = null;
}
```

Given the following (also simplified) LINQ query

```csharp
var events = new List<Event>();
events.AddRange(context.Event.Where(e => e.Cleared.HasValue);
```
I would expect the generated SQL to look similar to
```sql
SELECT [e].*
FROM [Event] AS [e]
WHERE ([e].[Cleared] IS NOT NULL
```
What actually gets generated is similar to
```sql
SELECT [e].*
FROM [Event] AS [e]
```
The only way to get EF to generate the `IS NOT NULL` in the where clause is to write the LINQ query as 

```csharp
var events = new List<Event>();
events.AddRange(context.Event.Where(e => e.Cleared != null);
```

Am I missing something or is this a bug? Having to write `!= null` rather than just `.HasValue` isn't intuitive.

**Comment by ajcvickers** [comment] 2018-08-21 20:06
@scottdorman I have not been able to reproduce this; my code is below. Can you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

```C#
public class Event
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Key]
    public int Id { get; set; }
    public DateTime Occurred { get; set; }
    public DateTime? Cleared { get; set; } = null;
}

public class BloggingContext : DbContext
{
    private static readonly LoggerFactory Logger
        = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<Event>();
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Set<Event>().Where(e => e.Cleared.HasValue).ToList();
        }
    }
}
```
Log output:
```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (21ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [e].[Id], [e].[Cleared], [e].[Occurred]
      FROM [Event] AS [e]
      WHERE [e].[Cleared] IS NOT NULL
```

**Comment by ajcvickers** [comment] 2018-08-29 16:29
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:26 UTC
Labels: closed-could-not-reproduce, customer-reported
