### ISSUE TITLE
EF executing redundant query for every record in resultset when projection contains nonmapped property

### ISSUE THREAD

**Issue by mstaessen** [dotnet/efcore#7000] opened 2016-11-11 16:52 UTC
### Steps to reproduce
Repro case:

```
public class Program
    {
        public static void Main(string[] args)
        {
            using (var context = new MyContext()) {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
                context.OneSide.AddRange(Enumerable.Repeat(0, 10).Select(x => new One {
                    Id = Guid.NewGuid(),
                    Name = Guid.NewGuid().ToString(),
                    Manies = Enumerable.Repeat(0, 10).Select(y => new Many {
                        Id = Guid.NewGuid(),
                        Name = Guid.NewGuid().ToString()
                    }).ToList()
                }));
                context.SaveChanges();
            }

            using (var context = new MyContext()) {
                var results = context.OneSide
                    .OrderByDescending(x => x.Name)
                    .Select(x => new {
                        Id = x.Id,
                        Name = x.Name,
                        InverseName = x.InverseName,
                        Count = x.Manies.Count
                    })
                    .Skip(0)
                    .Take(100)
                    .ToList();

                foreach (var result in results) {
                    Debug.WriteLine(result.Count);
                }
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<One> OneSide { get; set; }

        public DbSet<Many> ManySide { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseLoggerFactory(new LoggerFactory().AddDebug(LogLevel.Trace))
                .UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=ReproMultiFetch;Trusted_Connection=True;MultipleActiveResultSets=true");
        }
    }

    public class One
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        [NotMapped]
        public string InverseName => "";

        public virtual ICollection<Many> Manies { get; set; } = new HashSet<Many>();
    }

    public class Many
    {
        public Guid Id { get; set; }

        public Guid OneId { get; set; }

        public virtual One One { get; set; }

        public string Name { get; set; }
    }
```

### The issue
For every record in the resultset, EF is executing irrelevant queries. This only happens if your query projection includes a non-mapped property.

Queries executed:

```
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (5ms) [Parameters=[@__p_0='?', @__p_1='?'], CommandType='Text', CommandTimeout='30']
SELECT [x].[Id], [x].[Name], (
    SELECT COUNT(*)
    FROM [ManySide] AS [m0]
    WHERE [x].[Id] = [m0].[OneId]
)
FROM [OneSide] AS [x]
ORDER BY [x].[Name] DESC
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [m1].[Id], [m1].[Name], [m1].[OneId]
FROM [ManySide] AS [m1]
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [m1].[Id], [m1].[Name], [m1].[OneId]
FROM [ManySide] AS [m1]
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [m1].[Id], [m1].[Name], [m1].[OneId]
FROM [ManySide] AS [m1]
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [m1].[Id], [m1].[Name], [m1].[OneId]
FROM [ManySide] AS [m1]
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [m1].[Id], [m1].[Name], [m1].[OneId]
FROM [ManySide] AS [m1]
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [m1].[Id], [m1].[Name], [m1].[OneId]
FROM [ManySide] AS [m1]
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [m1].[Id], [m1].[Name], [m1].[OneId]
FROM [ManySide] AS [m1]
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [m1].[Id], [m1].[Name], [m1].[OneId]
FROM [ManySide] AS [m1]
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [m1].[Id], [m1].[Name], [m1].[OneId]
FROM [ManySide] AS [m1]
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [m1].[Id], [m1].[Name], [m1].[OneId]
FROM [ManySide] AS [m1]
```

### Further technical details

EF Core version: 1.0.1
Operating system: Windows 10
Visual Studio version: 2015

Other details about my project setup:

**Comment by maumar** [comment] 2016-11-12 00:31
This is by design. When you include unmapped property as a part of projection (or elsewhere) it forces client evaluation on that element, which in case of anonymous type results in evaluating every element separately. This scenario has been improved in our current bits (as part of other improvement) - we will now correlate the elements from those extra queries, so only the right rows are being returned, rather then entire table. We will still produce N+1 queries though.

```
SELECT COUNT(*)
FROM [ManySide] AS [m1]
WHERE @_outer_Id = [m1].[OneId]
```

**Comment by mstaessen** [comment] 2016-11-12 08:08
Is this documented somewhere? This can have a significant impact on performance and it isn't very straightforward that the nonmapped attribute is the culprit.

**Comment by rowanmiller** [comment] 2016-11-14 21:04
@mstaessen the more general topic is covered by https://docs.microsoft.com/en-us/ef/core/querying/client-eval.

**Comment by maumar** [comment] 2016-11-14 22:18
@mstaessen It is not explicitly documented, but unmapped property is from EF perspective identical to using a client-side method. The reason is that implementation of that property could contain arbitrary client code (calling client-side method etc)

**Comment by divega** [comment] 2016-11-17 01:19
After talking with @maumar and @smitpatel we believe that we should do much better with this kind of query. 

I.e. we shouldn't be falling back to evaluating the whole projection on the client, but just do partial client evaluation of the members that are not mapped, including client-only properties and client-side method calls (even if the method arguments are server-correlated). 

Note that we already handle mixed evaluation of composite predicates in `Where()`, which is in a way similar to this. 

Reopening and clearing up milestone.

**Comment by smitpatel** [comment] 2018-04-19 21:36
Duplicate of #11186

**Closed** 2022-10-16 10:42 UTC
Labels: type-bug, punted-for-2.0
