### ISSUE TITLE
EF core 3.1 slower performance joining multiple view entity, binding to a custom response model

### ISSUE THREAD

**Issue by padhumailin** [dotnet/efcore#22044] opened 2020-08-13 08:56 UTC
we have 3 views  joined to form a custom response in net core web api.  
when i inspect the query log, the execution time shown as :
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (**3,360ms**)

but when i execute the logged query in SQL management studio it executed in 500ms. Why this difference?

```c#
from emp in EmployeedView
                                       select new Employee
                                       {
                                        Id = emp.Id,
                                        personal = new Personal
                                        {
                                            Name= emp.name,
                                            DOB = emp.dob
                                        },
                                        Departments= (from d in depts
                                                                  where d.Id == emp.Id
                                                                  select new deptmodel{ 
                                                                      Code = d.Code,
                                                                      Name = d.Name                                                                    
                                                                  }).ToList(),
                                        Roles = (from r in roles
                                                                     where r.Id == emp.Id
                                                                     select new rolesmodel
                                                                     {
                                                                         Code = r.TCode,
                                                                         Name = r.TName                                                                  
                                                                     }).ToList()
                                       })
```

### Further technical details

EF Core version: 3,1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment] 2020-08-14 18:58
@padhumailin Please post the exact SQL that EF is running (from the logs) and also the _exact_ SQL that you are running in SQL management studio.

**Comment by ajcvickers** [comment] 2020-08-28 18:26
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:36 UTC
Labels: closed-no-further-action, customer-reported
