### ISSUE TITLE
Too long constraint name for the auto-generated enum constraints

### ISSUE THREAD

**Issue by henrikdahl8240** [dotnet/efcore#20867] opened 2020-05-06 22:42 UTC
I have several cases, where the auto-generated name for an enum constraint is too long, i.e. > 128 characters. It is this feature I talk about: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#generation-of-check-constraints-for-enum-mappings

In case of foreign keys, the auto-generated constraint name may be overruled by invoking `.HasConstraintName`.

It seems like there currently is no `.HasConstraintName` for these enum related constraints. In my opinion, you need to add that, so these auto-generated names can also be overridden because otherwise these constraints will prevent usage of EF Core.

**Comment by AndriySvyryd** [comment] 2020-05-08 17:50
Duplicate of https://github.com/dotnet/efcore/issues/18958

**Closed** 2022-10-16 18:23 UTC
Labels: customer-reported
