### ISSUE TITLE
Many-to-many not respecting column names in HasKey

### ISSUE THREAD

**Issue by rlightner** [dotnet/efcore#23568] opened 2020-12-03 19:18 UTC
> Classes

```C#
public class Post
{
    [Column("id")]
    public int Id { get; set; }
    public string Name { get; set; }
    public ICollection<Tag> Tags { get; set; }
}

public class Tag
{
    [Column("id")]
    public int Id { get; set; }
    public string Text { get; set; }
    public ICollection<Post> Posts { get; set; }
}

public class PostTag {
    [Column("post_id")]
    public int PostId { get; set; }
    [Column("tag_id")]
    public int TagId { get; set; }

    public IList<Posts> {get; set;}
    public IList<Tags> {get; set;}
}
```

> Model Builder
```C#
    modelBuilder
        .Entity<Post>()
        .HasMany(p => p.Tags)
        .WithMany(p => p.Posts)
        .UsingEntity<PostTag>(
            j => j
                .HasOne(pt => pt.Tag)
                .WithMany()
                .HasForeignKey(pt => pt.TagId),
            j => j
                .HasOne(pt => pt.Post)
                .WithMany()
                .HasForeignKey(pt => pt.PostId),
            j => j.HasKey(t => new { t.PostId, t.TagId });
```
also tried with:
```C#
    modelBuilder
        .Entity<Post>()
        .HasMany(p => p.Tags)
        .WithMany(p => p.Posts)
        .UsingEntity<PostTag>(
            j => j
                .HasOne(pt => pt.Tag)
                .WithMany()
                .HasForeignKey(pt => pt.TagId),
            j => j
                .HasOne(pt => pt.Post)
                .WithMany()
                .HasForeignKey(pt => pt.PostId),
            j =>
                {
                     j.HasKey(tm => new { tm.PostId, tm.TagId});
                }
           );
```
> Generated SQL will have an incorrectly named columns appended to the query:

```sql
select t1.tag_id, t1.post_id, t1."TagId", t1."PostId" from post_tags as t1
```

**Comment by smitpatel** [comment] 2020-12-03 20:37
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

Especially where does "tag_id" & "post_id" comes in the query since it is not configured anywhere in the code.

**Comment by rlightner** [comment] 2020-12-03 21:13
@smitpatel Sorry, I had not put the column attribute on my code for this example. I've updated to show were `tag_id` and `post_id` are coming from. I will work on getting a simple solution together as well.

**Comment by ajcvickers** [comment] 2020-12-04 21:14
@rlightner I am not able to reproduce this. I had to edit your code and guess at some things because as posted it doesn't compile--see my code below. Please attach a small, runnable project or post a small, runnable code listing, like below, that reproduces what you are seeing so that we can investigate.

```C#
public class Post
{
    [Column("id")]
    public int Id { get; set; }
    public string Name { get; set; }
    public ICollection<Tag> Tags { get; set; }
}

public class Tag
{
    [Column("id")]
    public int Id { get; set; }
    public string Text { get; set; }
    public ICollection<Post> Posts { get; set; }
}

public class PostTag {
    [Column("post_id")]
    public int PostId { get; set; }
    [Column("tag_id")]
    public int TagId { get; set; }

    public Post Post {get; set;}
    public Tag Tag {get; set;}
}

public class SomeDbContext : DbContext
{
    private static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().SetMinimumLevel(LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .UseLoggerFactory(ContextLoggerFactory)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<Post>()
            .HasMany(p => p.Tags)
            .WithMany(p => p.Posts)
            .UsingEntity<PostTag>(
                j => j
                    .HasOne(pt => pt.Tag)
                    .WithMany()
                    .HasForeignKey(pt => pt.TagId),
                j => j
                    .HasOne(pt => pt.Post)
                    .WithMany()
                    .HasForeignKey(pt => pt.PostId),
                j => j.HasKey(t => new {t.PostId, t.TagId}));
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Post {Tags = new List<Tag> {new Tag()}});
            
            context.SaveChanges();
        }
        
        using (var context = new SomeDbContext())
        {
            var results = context.Set<PostTag>().ToList();
        }
    }
}
```

```
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 5.0.0 initialized 'SomeDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: SensitiveDataLoggingEnabled 
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (12ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (13ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      IF SERVERPROPERTY('EngineEdition') <> 5
      BEGIN
          ALTER DATABASE [Blogs] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
      END;
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (51ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      DROP DATABASE [Blogs];
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (337ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      CREATE DATABASE [Blogs];
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (133ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      IF SERVERPROPERTY('EngineEdition') <> 5
      BEGIN
          ALTER DATABASE [Blogs] SET READ_COMMITTED_SNAPSHOT ON;
      END;
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [Post] (
          [id] int NOT NULL IDENTITY,
          [Name] nvarchar(max) NULL,
          CONSTRAINT [PK_Post] PRIMARY KEY ([id])
      );
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [Tag] (
          [id] int NOT NULL IDENTITY,
          [Text] nvarchar(max) NULL,
          CONSTRAINT [PK_Tag] PRIMARY KEY ([id])
      );
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [PostTag] (
          [post_id] int NOT NULL,
          [tag_id] int NOT NULL,
          CONSTRAINT [PK_PostTag] PRIMARY KEY ([post_id], [tag_id]),
          CONSTRAINT [FK_PostTag_Post_post_id] FOREIGN KEY ([post_id]) REFERENCES [Post] ([id]) ON DELETE CASCADE,
          CONSTRAINT [FK_PostTag_Tag_tag_id] FOREIGN KEY ([tag_id]) REFERENCES [Tag] ([id]) ON DELETE CASCADE
      );
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE INDEX [IX_PostTag_tag_id] ON [PostTag] ([tag_id]);
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (16ms) [Parameters=[@p0=NULL (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Post] ([Name])
      VALUES (@p0);
      SELECT [id]
      FROM [Post]
      WHERE @@ROWCOUNT = 1 AND [id] = scope_identity();
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[@p0=NULL (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Tag] ([Text])
      VALUES (@p0);
      SELECT [id]
      FROM [Tag]
      WHERE @@ROWCOUNT = 1 AND [id] = scope_identity();
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[@p1='1', @p2='1'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [PostTag] ([post_id], [tag_id])
      VALUES (@p1, @p2);
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 5.0.0 initialized 'SomeDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: SensitiveDataLoggingEnabled 
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [p].[post_id], [p].[tag_id]
      FROM [PostTag] AS [p]
```

**Comment by ajcvickers** [comment] 2020-12-15 16:57
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:13 UTC
Labels: closed-could-not-reproduce, customer-reported
