### ISSUE TITLE
Json serializer options for json columns

### ISSUE THREAD

**Issue by KsanderVine** [dotnet/efcore#31113] opened 2023-06-21 11:23 UTC
Im trying to disable Unicode chars escaping (\uxxxx) in my SQL Server DB table for JSON column value.

What about to add some way to set json serializer options?
![image](https://github.com/dotnet/efcore/assets/102971285/b622f66f-2b9c-44ce-a601-b4bc98c61fe6)

##### Option 1 - Inside model builder:

```csharp
modelBuilder.Entity<MyObject>()
        .OwnsOne(v => v.ValueJSON, builder => 
        builder.ToJson(jsonSerializerOptionsHere)); 
```

##### Option 2 - While application config:

```csharp
builder.Services.AddDbContext<MyDatabase>(options => 
        options.UseSqlServer(connectionString, jsonSerializerOptionsHere);
```

This is hard to use SQL Server Management Studio, when all JSON columns looks like \uxxxx\uxxxx\uxxxx\uxxxx\uxxxx\uxxxx\uxxxx\uxxxx\uxxxx\uxxxx\uxxxx\uxxxx\uxxxx

**Comment by ajcvickers** [comment] 2023-06-21 19:00
Duplicate of #28043.

**Closed** 2023-06-26 15:08 UTC
Labels: customer-reported
