### ISSUE TITLE
Query: invalid SQL produced for query with non-trivial group aggregate and coalesce

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12658] opened 2018-07-13 00:22 UTC
query:

```cs
                var query = ctx.LevelOne.GroupBy(
                    l1 => l1.OneToOne_Required_PK.OneToOne_Required_PK.Name,
                    l1 => new
                    {
                        Id = ((int?)l1.OneToOne_Required_PK.Id ?? 0)
                    })
                .Where(g => g.Min(l1 => l1.Id + l1.Id) > 0)
                .Select(g => g.Count());

                var result = query.ToList();
```

sql:

```sql
SELECT COUNT(*)
FROM [Level1] AS [l1]
GROUP BY [l1].[Level3_Name]
HAVING MIN(COALESCE([l1].[Id], 0) AS [Id] + COALESCE([l1].[Id], 0) AS [Id]) > 0, 
```

exception:
Incorrect syntax near '+'.

**Comment by smitpatel** [comment] 2018-07-27 19:54
Duplicate of #12826

**Closed** 2022-10-16 13:19 UTC
