### ISSUE TITLE
Join with client side collections

### ISSUE THREAD

**Issue by xumix** [dotnet/efcore#12431] opened 2018-06-20 16:34 UTC
It would be great to use .Contains and .Join as translated statements like it is do with simple ```.Contains(e.Id)```

For example:
```c#
var newKeys = lc.lotContract.Select(l => new { l.IdLot, l.IdContract }).ToHashSet();
var existingKeys = (from l in importDb.Set<lotContract>()
                              join k in newKeys on new { l.IdLot, l.IdContract } equals new { k.IdLot, k.IdContract }
                              select new { l.IdLot, l.IdContract })
                        .ToHashSet();
```

### Further technical details
EF Core version: 2.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
IDE: (e.g. Visual Studio 2017 15.7)

**Comment by smitpatel** [comment] 2022-01-18 20:26
#17031

**Comment by roji** [comment] 2023-04-18 00:03
Duplicate of #17031

**Closed** 2023-04-19 19:01 UTC
Labels: closed-duplicate, customer-reported
