### ISSUE TITLE
Violation of PRIMARY KEY constraint '%PKNAME%'. Cannot insert duplicate key in object '%TABLENAME%'. The duplicate key value is (1).

### ISSUE THREAD

**Issue by Advitalitum** [dotnet/efcore#14246] opened 2018-12-25 19:40 UTC
Lazy loading doesn't work properly. If i run application more than once i get error. Here is my example:

```
An error occurred while updating the entries. See the inner exception for details.
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at ConsoleApp28.Program.Main() in C:\Users\Username\source\repos\ConsoleApp28\ConsoleApp28\Program.cs:line 29
Violation of PRIMARY KEY constraint 'PK_Courses'. Cannot insert duplicate key in object 'dbo.Courses'. The duplicate key value is (1).
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

### Steps to reproduce

```c#
internal class Program
    {
        static Program()
        {
            using (var context = new SchoolContext())
            {
                context.Database.Migrate();

                Seed(context);
            }
        }

        private static void Main()
        {
            try
            {
                using (var context = new SchoolContext())
                {
                    var student = context.Students.Single();

                    student.Course = new Course { CourseName = Guid.NewGuid().ToString() };

                    context.SaveChanges();
                }

                Console.WriteLine("End");
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception.Message);
                Console.WriteLine(exception.StackTrace);
                Console.WriteLine(exception.InnerException?.Message);
                Console.WriteLine(exception.InnerException?.StackTrace);
            }
            finally
            {
                Console.ReadLine();
            }
        }

        private static void Seed(SchoolContext context)
        {
            if (!context.Students.Any())
            {
                context.Students.Add(new Student { Name = Guid.NewGuid().ToString() });
            }

            context.SaveChanges();
        }
    }
```
Context:
```c#
public class SchoolContext : DbContext
    {
        private const string ForeignKeyPropertyName = "StudentId";

        public DbSet<Student> Students { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=Username;Database=Students;Trusted_Connection=True;MultipleActiveResultSets=true")
                .UseLazyLoadingProxies()
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        /// <inheritdoc />
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Student>().ToTable("Students");
            modelBuilder.Entity<Student>().HasKey(s => s.Id);
            modelBuilder.Entity<Student>().HasOne(s => s.Course).WithOne().HasForeignKey<Course>(ForeignKeyPropertyName).IsRequired().OnDelete(DeleteBehavior.Cascade);

            modelBuilder.Entity<Course>().ToTable("Courses");
            modelBuilder.Entity<Course>().Property<int>(ForeignKeyPropertyName);
            modelBuilder.Entity<Course>().HasKey(ForeignKeyPropertyName);
        }
    }
```
Classes:
```c#
public class Student
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public virtual Course Course { get; set; }
    }

    public class Course
    {
        public string CourseName { get; set; }
    }
```
In debug mode if i stop on breakpoint at line
```c#
student.Course = new Course { CourseName = Guid.NewGuid().ToString() };
```
and then continue it works well.

If i do not use lazy loading proxies it also works well (with Include(s => s.Course);

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 x64
IDE: Visual Studio 2017 15.9.4

**Comment by smitpatel** [comment] 2018-12-26 20:05
Duplicate of #14086

**Comment by smitpatel** [comment] 2018-12-26 20:07
Issue here is, you are assigning navigation value but you are not accessing before it. Hence `Course` is not loaded in memory. So EF Core does not know if there is an existing course which needs to be deleted first before inserting another course with same Id. It works while in debug mode because in order to show properties of Student, debugger may end up calling the getter causing `Course` to be loaded.

**Comment by Advitalitum** [comment] 2018-12-27 05:56
Thank you for feedback

**Closed** 2022-10-16 13:45 UTC
Labels: closed-duplicate, customer-reported
