### ISSUE TITLE
Feature Request: - For SqlServer generate join on table variable instead of generating WHERE IN clause when .Contains is used in the EF query

### ISSUE THREAD

**Issue by yahorsi** [dotnet/efcore#17790] opened 2019-09-12 11:52 UTC
Hi Guys!

Sometimes people need to check if the database column value is in a list of predefined values, and so we do something like filter.FunctionIds.Contains(x.FunctionId). On the Microsoft SQL Server that get's translated into the TSQL WHERE IN clause. 

Problem 1.
If a list of values changes, that will result in the query text being different. Once the query is different - SQL server must parse/compile it and in that case, it can't use a cached plan. Sometimes, especially if the list passed to .Contains is big, it might take a lot of time, but even if it's small, compiling quires is something that takes time. In our case, we observe about 20ms for the relatively small query with a small, but changing list used in .Contains.

Problem 2.
Sometimes, people don't think a lot and pass really big lists to the .Contains and that kills perf.

Solution
Make it possible to utilize Sql Server Table Variable feature, so, all the dynamic values could be passed as a parameter and instead of generating WHERE IN EntityFramework could generate join in the table variable. At least for the Microsoft SQL Server. Open question here is what type should be used to declare table variable type but that I believe has many different solutions.

Thanks

**Comment by yahorsi** [comment] 2019-09-13 12:00
Holly cow, I just have realized that this is actually already possible to achieve just by changing EF query to use FromSql & table valuated parameter.

**Comment by smitpatel** [comment] 2019-09-21 00:57
Duplicate of #13239

**Closed** 2022-10-16 14:41 UTC
Labels: customer-reported
