### ISSUE TITLE
QueryClientEvaluationWarning Exception when the 'Dto' has a base class

### ISSUE THREAD

**Issue by hrfarrokh** [dotnet/efcore#14365] opened 2019-01-10 16:54 UTC
Hi 
Please See [This](https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/326) Issue.

sincerely.

**Comment by smitpatel** [comment] 2019-01-10 20:04
Duplicate of #12230

**Closed** 2022-10-16 13:46 UTC
Labels: closed-duplicate, customer-reported
