### ISSUE TITLE
Perf: Sequential read from DbDataReader

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#14454] opened 2019-01-17 21:55 UTC

**Comment by roji** [comment] 2019-01-18 17:01
I may be missing the intent here, but doesn't EF Core need to get the full column value out anyway, to assign it to an entity property? Sequential reading seems to make sense especially when you want to stream/process a large column value without having it all in memory at the same time...

**Comment by AndriySvyryd** [comment] 2019-08-22 22:25
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/885

**Closed** 2022-10-16 13:48 UTC
Labels: area-perf
