### ISSUE TITLE
Inherited class in DbSet causes exception when using FromSqlRaw to call stored proc

### ISSUE THREAD

**Issue by sosuke3** [dotnet/efcore#19601] opened 2020-01-15 19:03 UTC
When using a DbSet with a class that inherits from a base class, and calling a stored proc with FromSqlRaw against it, EF Core 3 will throw: 'FromSqlRaw or FromSqlInterpolated was called with non-composable SQL and with a query composing over it. Consider calling `AsEnumerable` after the FromSqlRaw or FromSqlInterpolated method to perform the composition on the client side.'

### Steps to reproduce
* setup sandbox database on localhost with the following stored proc:
``` SQL
create procedure [dbo].[uspGetTestTable2]
as
	select 1 as Id,
			1 as SomeOtherField
GO
```

* Create new Framework 4.8 Console Application with the following:
``` C#
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading.Tasks;

namespace EFCoreInterfaceTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using (var db = new TestDbContext())
            {
                var tests = db.TestTables2.FromSqlRaw("uspGetTestTable2")
                    .AsNoTracking();
                var test2 = await tests.ToListAsync();
            }
        }
    }

    public class TestDbContext : DbContext
    {
        public virtual DbSet<TestTableResults2> TestTables2 { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseSqlServer("Server=localhost; Database=sandbox; Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<TestTableResults>(eb => eb.HasNoKey());
        }
    }

    public class TestTableResults
    {
        public int Id { get; set; }
    }

    public class TestTableResults2 : TestTableResults
    {
        public int SomeOtherField { get; set; }
    }
}
```
* Hit F5

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 4.8
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.2
Sql Server: 2017 (14.0.1000.169 x64)

**Comment by ajcvickers** [comment] 2020-01-16 21:04
Duplicate of #18232

**Comment by ajcvickers** [comment] 2020-01-17 19:51
@smitpatel Can you confirm this is dupe when you return.

**Closed** 2022-10-16 18:06 UTC
Labels: customer-reported
