### ISSUE TITLE
dotnet ef migrations add does not recognize data annotation Key

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/efcore#26992] opened 2021-12-13 20:58 UTC
I am using EF Core 6 command line 6.0.100 and entered the following command 

`dotnet-ef migrations add InitialCreate --context MsSqlContext --project Model --output-dir Migrations\MsSql`

and get the following error

`The entity type 'Blog' requires a primary key to be defined`

and here is what the entity looks like

`    [Table ("Blog" )]
    public partial class Blog
    {

        public Blog ()
        {}
		
	[Key]
        [DatabaseGenerated ( DatabaseGeneratedOption.Identity )]
        
        public virtual int Blog_RID
        { get; set; }

	}`

All of our entities use data annotations, why is Key not recognized?

**Comment by dgxhubbard** [comment] 2021-12-13 22:18
[CoreMigrationMs.zip](https://github.com/dotnet/efcore/files/7707284/CoreMigrationMs.zip)

In our regular code we use partial classes for our entities, one class provides all of the fields that will be used in the table (they use data annotations). The matching partial class for the entity derives from a base class BaseModel that has some bookkeeping flags, a SetField method and overrides of object methods.

When I run migrations add:

dotnet-ef migrations add InitialCreate --context SqliteGtContext --project CoreData --output-dir Migrations\Sqlite

I get the error described above

System.InvalidOperationException: The entity type 'Blog' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'.

Even though the Key data annotation is used.





**BaseModel**

`    public class BaseModel
    {
        public bool IsChanged
        { get; set; }

        protected void SetField<T> ( ref T field, T value, string propertyName )
        {
            if (!EqualityComparer<T>.Default.Equals ( field, value ))
            {
                T oldValue = field;
                T newValue = value;

                field = value;

                IsChanged = true;
            }
        }
    }
`

**Blog** 

`    [Table ( "Blogs" )]
    public partial class Blog : BaseModel
    {
        [Key]
        [DatabaseGenerated ( DatabaseGeneratedOption.Identity )]
        private int _blog_RID;
        public virtual int Blog_RID
        {
            get { return _blog_RID; }
            set { SetField ( ref _blog_RID, value, nameof ( Blog_RID ) ); }

        }


        [Required ( AllowEmptyStrings = true )]
        private string _url;
        public virtual string Url
        {
            get { return _url; }
            set { SetField ( ref _url, value, nameof ( Url ) ); }
        }


        public virtual List<Post> Posts { get; } = new List<Post>();

    }
`

**Blog Partial**

`    public partial class Blog : BaseModel
    {

        public override string ToString ()
        {
            return "Blog_RID: " + Blog_RID+ " Url: " + Url;
        }

    }

`

**Comment by dgxhubbard** [comment] 2021-12-13 22:48
Please note all of our entities use data annotations and not fluent api

**Comment by dgxhubbard** [comment] 2021-12-13 23:24
Note this same issue happens with EnsureCreate

`        private static void CreateSqlite ( SqliteGtContext context )
        {
            if (DatabaseType == DatabaseType.SQLite)
            {
                var dbPath = GtContextFactory.DbPath;
                if (File.Exists ( dbPath ))
                    File.Delete ( dbPath );
            }

            context.Database.EnsureCreated ();


            
            AddData ( context );

        }

`

**Comment by dgxhubbard** [comment] 2021-12-14 18:21
I removed the base class, BaseModel, from the entities and left the primary key names
the same (i.e. Entity_RID for example), and the error still persists. If I add IEntityTypeConfiguration classes
for Blog and Post the error disappears. So I am taking advantage of EntityTypeConfigurationAttribute to mark the configuration classes. We do not have time to move to pure fluent API. Will the combination of data annotations and fluent api cause any errors generating migrations?

**Comment by dgxhubbard** [comment] 2021-12-14 18:25
I get this warning when generating a migration

`The foreign key property 'Post.Blog_RID1' was created in shadow state because a conflicting property with the simple name 'Blog_RID' exists in the entity type, but is either not mapped, is already used for another relationship, or is incompatible with the associated primary key type. See https://aka.ms/efcore-relationships for information on mapping relationships in EF Core.`

There is a Blog_RID in Blog and Post. The first marks the primary key in Blog and the second the foreign key in Post. Why am I geting the warning?

**Comment by ajcvickers** [comment] 2021-12-16 11:39
@dgxhubbard You have the `[Key]` attribute on the backing field. It can only be used on a property.

**Comment by dgxhubbard** [comment] 2021-12-16 22:28
@ajcvickers Thanks for pointing that out

**Comment by dgxhubbard** [comment] 2021-12-16 22:30
@ajcvickers 







`
    [Table ("ActionSchedules" )]
    //[EntityTypeConfiguration ( typeof ( ActionScheduleConfiguration ) )]
    public partial class ActionSchedule
    {

        public ActionSchedule ()
        {}

        int _actionSchedule_RID;

        [Key]
        [System.Runtime.Serialization.DataMember]
        public virtual int ActionSchedule_RID
        {
            get
            {
                return _actionSchedule_RID;
            }
            set
            {
                if ( _actionSchedule_RID != value )
                {
                    SetField ( ref _actionSchedule_RID, value, "ActionSchedule_RID" );
                }
            }
        }
}

`

**Comment by dgxhubbard** [comment] 2021-12-16 22:38
@ajcvickers I switched the Key and DataMember attribute but no change error still occuring

**Comment by dgxhubbard** [comment] 2021-12-16 23:22
@ajcvickers 
Our model assembly is setup like this: one folder Containers contains the entities, and another folder ContainersPartial contains the matching partial class where we define methods that are distinct from the database properties. The entities and their partial classes are in the same namespace. In the context we have the usual DbSet<Entity> Entities. If I add a new entity with only the key column named Aaa it gets the same error.

**Comment by ajcvickers** [comment] 2021-12-17 12:53
@dgxhubbard What error are you currently discussing? When I run your sample code with annotation on the key properties, then I get the following model. It seems correct to me.

```
Model: 
  EntityType: Blog
    Properties: 
      Blog_RID (_blog_RID, int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      IsChanged (bool) Required
      Url (_url, string) Required
    Navigations: 
      Posts (List<Post>) Collection ToDependent Post Inverse: Blog
    Keys: 
      Blog_RID PK
  EntityType: Post
    Properties: 
      Post_RID (_post_RID, int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      Blog_RID (_blog_RID, int) Required
      Content (_content, string) Required
      IsChanged (bool) Required
      Title (_title, string) Required
      _blog_RID (_blog_RID, int) Required FK Index
    Navigations: 
      Blog (_blog, Blog) ToPrincipal Blog Inverse: Posts
    Keys: 
      Post_RID PK
    Foreign keys: 
      Post {'_blog_RID'} -> Blog {'Blog_RID'} ToDependent: Posts ToPrincipal: Blog Cascade
    Indexes: 
      _blog_RID 
```

**Comment by dgxhubbard** [comment] 2021-12-17 17:22
[CoreMigrationMs.zip](https://github.com/dotnet/efcore/files/7736718/CoreMigrationMs.zip)

Here is the sample code modified to have the same structure we have in our main source. Everything about about adding migrations has been pulling teeth. The latest problem in our main source is add migrations is not finding the Key attribute for data annotations. I cannot duplicate the problem in sample 
code. Trying to find out why Key is not found and probably why no data annotations would be found. 
Being unable to duplicate the issue, means I have to ask what might cause this. Using multiple db contexts  and missing something in setup of migrations could be the issue

**Comment by dgxhubbard** [comment] 2021-12-17 19:04
@ajcvickers 
Please reference #27032, we are trying to use fluent api and generate migrations that way because our Key data annotation is ignored, but  giving the a primary key and foreign key in different entities the same name is causing a shadow key to be generated.

**Comment by ajcvickers** [comment] 2022-01-04 12:11
The model I get from running your code is:

```
Model: 
  EntityType: Blog
    Properties: 
      Blog_RID (_blog_RID, int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      Url (_url, string) Required
    Navigations: 
      Posts (List<Post>) Collection ToDependent Post Inverse: Blog
    Keys: 
      Blog_RID PK
  EntityType: Post
    Properties: 
      Post_RID (_post_RID, int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      Blog_RID (_blog_RID, int) Required FK Index
      Content (_content, string) Required
      Title (_title, string) Required
    Navigations: 
      Blog (_blog, Blog) ToPrincipal Blog Inverse: Posts
    Keys: 
      Post_RID PK
    Foreign keys: 
      Post {'Blog_RID'} -> Blog {'Blog_RID'} ToDependent: Posts ToPrincipal: Blog Cascade
    Indexes: 
      Blog_RID 
```

`Blog.Blog_RID` is defined as:

```C#
[Key]
[DatabaseGenerated ( DatabaseGeneratedOption.Identity )]
public virtual int Blog_RID
{
    get { return _blog_RID; }
    set { SetField ( ref _blog_RID, value, nameof ( Blog_RID ) ); }
}
```

So the key/Identity configuration in the model matches that of the data annotations. Also, `Url` is marked as `Required` which also matches.

The same is true for `Post`, with the foreign key also set correctly in the model.

**Comment by ajcvickers** [comment] 2022-01-14 09:03
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:19 UTC
Labels: closed-could-not-reproduce, customer-reported
