### ISSUE TITLE
LINQ Unable to Compare Two Dates

### ISSUE THREAD

**Issue by bwarring24** [dotnet/efcore#20926] opened 2020-05-12 01:21 UTC
When using a LINQ expression with a where clause that compares two Datetime.Date values using an equality operator, the LINQ expression passes a Could not be translated error when using anything after the where clause (e.g. ToList(), ToArray(), .Sum(), .Average(), etc.)

### Steps to reproduce
```C#
DateTime dt = new DateTime(2020, 5, 8);
List<Trip> test = context.Trips.Where(x => x.StartTime.Value.Date == dt.Date).ToList();
```
### Error Message
```
Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.dll
An exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code
The LINQ expression 'DbSet<Trip>()
    .Where(t => t.StartTime.Value.Date == __dt_Date_0)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

### Further technical details

EF Core version: 5.0.0-preview.3.20181.2
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: .NET Core 3.1
Operating system: Windows 10 (Build 18363.815)
IDE: Visual Studio 2019 Version 16.5.4

**Comment by ajcvickers** [comment] 2020-05-15 16:34
@bwarring24 Is `StartTime` a nullable `DateTime` or something else?

**Comment by bwarring24** [comment] 2020-05-15 16:47
> @bwarring24 Is `StartTime` a nullable `DateTime` or something else?

Yes, it is a nullable DateTime.

**Comment by smitpatel** [comment] 2020-05-15 17:04
`DateTime.Value.Date` is currently not translated on Cosmos.

**Comment by ajcvickers** [comment] 2020-05-15 20:58
Duplicate of #16143

**Closed** 2022-10-16 18:24 UTC
Labels: customer-reported
