### ISSUE TITLE
Cannot compile join to SQL when using interface

### ISSUE THREAD

**Issue by Nate129** [dotnet/efcore#24654] opened 2021-04-13 22:03 UTC
Hi,

I am attempting to write a join executed server side in EF Core where an in memory collection is joined on a queryable collection from a DbContext.

Given the following classes:

``` C#
public interface IEntity
{
    object Id { get; set; }
    byte[] Version { get; set; }
}
```
``` C#
public abstract class Entity<T> : IEntity
{
    [Key] public T Id { get; set; }

    [Timestamp]
    public byte[] Version { get; set; }

    object IEntity.Id
    {
        get => Id;
        set => Id = value != null ? (T) value : default;
    }
}
```

``` C#
public class Person : Entity<Guid>
{
    public string Name { get; set; }
}
```

``` C#
public class EntityMetadata
{
    public string EntityId { get; set; }

    public byte[] Version { get; set; }
}
```
and the DbContext:

``` C#
public class TestContext : DbContext
{
    public TestContext(DbContextOptions<DbContext> options) : base(options)
    {
    }

    public DbSet<Person> People { get; set; }
}
```

If I generate sample data as such:

``` C#
context.People.AddRange(new Person(), new Person());

context.SaveChanges();

var metadata = context.People.ToList()
                .Select(p => new EntityMetadata {EntityId = p.Id.ToString(), Version = p.Version});
```

Given the following method containing the join:

``` C#
public IEnumerable<IEntity> JoinQuery(IQueryable<IEntity> set, IEnumerable<EntityMetadata> metadata)
{
    var updates = from e in set
                  join m in metadata on (string) e.Id equals m.EntityId into results
                  from m in results.DefaultIfEmpty()
                  select e;

    return updates;
}
```

When running the method:

```C#
JoinQuery(context.People, metadata).Count();
```

the following exception occurs:

```
Expression of type 'System.Func`2[EFCoreIssue.Abstractions.IEntity,System.Object]' cannot be used for parameter of type 'System.Linq.Expressions.Expression`1[System.Func`2[EFCoreIssue.Models.Person,System.Object]]' of method 'System.Linq.IQueryable`1[EFCoreIssue.Abstractions.IEntity] LeftJoin[Person,EntityMetadata,Object,IEntity](System.Linq.IQueryable`1[EFCoreIssue.Models.Person], System.Collections.Generic.IEnumerable`1[EFCoreIssue.Models.EntityMetadata], System.Linq.Expressions.Expression`1[System.Func`2[EFCoreIssue.Models.Person,System.Object]], System.Linq.Expressions.Expression`1[System.Func`2[EFCoreIssue.Models.EntityMetadata,System.Object]], System.Linq.Expressions.Expression`1[System.Func`3[EFCoreIssue.Models.Person,EFCoreIssue.Models.EntityMetadata,EFCoreIssue.Abstractions.IEntity]])' (Parameter 'arg2')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1, Expression arg2, Expression arg3, Expression arg4)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryableMethodNormalizingExpressionVisitor.TryFlattenGroupJoinSelectMany(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryableMethodNormalizingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.NormalizeQueryableMethod(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPreprocessor.NormalizeQueryableMethod(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
```

It would seem that `(string) e.Id` is the part of the join indicated in the exception.

When attempting a similar query using the same string conversion:

``` C#
public IEnumerable<IEntity> SimpleQuery(IQueryable<IEntity> set, IEnumerable<EntityMetadata> metadata)
{
    var matches = set.Where(e => metadata.Select(m => m.EntityId).Contains(((string) e.Id).ToUpper()));

    return matches;
}
```

The following SQL is generated:

``` SQL
SELECT "p"."Id", "p"."Name", "p"."Version"
      FROM "People" AS "p"
      WHERE upper(CAST("p"."Id" AS TEXT)) IN ('A044D4E5-851D-41CB-88F2-81B8D9AB7768', 'D02BB4CA-C61D-4C3B-9885-794A4CEBD7CC')
```

It seems to me that the content of the expression is not the issue, but rather the difference in the expression/func input type. Since the expression/func provided does not explicitly match the concrete type seemingly required to map the expression to SQL, the exception is thrown. However, it would seem that this type of expression type conversion is generally supported by EF Core, as evidenced by the where example provided above. 

The join statement executes without issue when evaluated client side as long as `(string)` is replaced with `.ToString()` (the former does not work in normal C# and the latter does not work in EF Core).

Is this a bug with EF Core?

EF Core version: v5.05
Database provider: Microsoft.EntityFrameworkCore.Sqlite (also fails on SQL Server)
Target framework: NET 5.0
Operating system: Windows 10
IDE: Visual Studio 16.9.3

I have created a [demo repository](https://github.com/Nate129/EFCoreIssue) containing the above code and tests which reproduce the results described above.

**Comment by smitpatel** [comment] 2021-04-13 22:24
Duplicate of #21914 

Joins where one of the collection is a client-side collection rather than a server correlated query is _not_ supported.

**Closed** 2022-10-16 19:31 UTC
Labels: closed-duplicate, customer-reported
