### ISSUE TITLE
16.8.0preview1.0 Entity Framework  error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#21984] opened 2020-08-07 18:48 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1140537/1680preview10-entity-framework-error.html)._

---
[severity:Other] [regression] [worked-in:16.7]
Update the latest version, the original normal function error

MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Builders.IndexBuilder`1<System.__Canon> Microsoft.EntityFrameworkCore.Metadata.Builders.IndexBuilder`1.HasName(System.String)'.

---
### Original Comments
(no comments)

---
#### 李东辉 solved on 8/6/2020, 07:57 PM, 0 votes: 

<p>Upgrade the Entity Framework version and the problem is resolved</p>

**Comment by ajcvickers** [comment] 2020-08-07 18:51
Which version of EF Core were you using when you encountered this issue?

**Comment by ajcvickers** [comment] 2020-08-17 15:27
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:36 UTC
Labels: closed-could-not-reproduce, customer-reported
