### ISSUE TITLE
Adjust DB context generation from DB

### ISSUE THREAD

**Issue by verdysh** [dotnet/efcore#33131] opened 2024-02-21 09:06 UTC
Hi,
I have EF Core of version 8.0.1 and MS SQL database. I use DB first approach so I generate DB context and entities from my DB using Scaffold-DbContext command from Visual Studio. There are few issues while generation:

1. In my DB context I have OnConfiguring method:
```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
	if (!optionsBuilder.IsConfigured)
	{
		optionsBuilder.UseSqlServer("Name=ConnectionStrings:MyDb");
	}
}
```
This method changes and becomes as following after update:
```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	=> optionsBuilder.UseSqlServer("Name=ConnectionStrings:MyDb");
```
	
But without `!optionsBuilder.IsConfigured` I have some exception during runtime. If necessary, I'll show exactly the error but I hope you understand what I'm talking about.

What I want: I want it doesn't remove the condition `if (!optionsBuilder.IsConfigured)` while updating.

2. I have an entity class:

```
public partial class MyEntity
{
	...
	public MyScheduleTypeEnum ScheduleType { get; set; }
	...
}
```

After update `MyScheduleTypeEnum` becomes int.

What I want: I want to keep property type as enum.

3. I have another entity with the following property:

`public Dictionary<string, string>? Data { get; set; }`

Also I have the following configuration for this property:
```
builder
    .Property(e => e.Data)
    .HasConversion(
        v => JsonConvert.SerializeObject(v, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }),
        v => JsonConvert.DeserializeObject<Dictionary<string, string>>(v, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore })
    );
```
	
After update this property becomes `string? Data` instead of `Dictionary<string, string>?`

What I want: I want to keep property type as `Dictionary<string, string>?`

Now I manually restore the code above after update. But would be great if I can get rid of this manually work with each update.

### Include provider and version information

EF Core version: 8.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0

**Comment by ajcvickers** [comment] 2024-02-21 09:35
Duplicate of #831. Consider using [customized T4 templates](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli) for at least the first of these.

**Closed** 2024-02-28 13:31 UTC
Labels: closed-duplicate, customer-reported
