### ISSUE TITLE
Disposing DbContext does not appear to dispose data

### ISSUE THREAD

**Issue by codearoo** [dotnet/efcore#7343] opened 2017-01-03 17:01 UTC
Hi. I'm having a hard time with memory leak. I am using EF Core 1.1.0 on a ASP.Net Core project with full .Net 4.6. I'm using SqlServer provider. I set up Dependency Injection ServiceProvider to AddTransient of a Dao class I made, which takes 1 instance of a DbContext class, which also I have wired up as AddTransient.

I implemented Dispose method on my Dao, and also on my DbContext class just to put a break point and verify it is getting called. In my web app I have a timer going that is refreshing data to be ready for its web clients. After running a while, the memory continues to grow. I verify that for each firing of the timed refresh, a new Dao/DbContext is created, followed by a Dispose when it's done. Still when I look at memory diagnostics after running a while, several of my DbSet's are at the top of the list with a huge number of records and memory usage. And it grows only when these timed data refreshing runs.

If I call Dispose on a DbContext, I assumed EVERYTHING in it would be released. But is that not the case? Do I need to do something else?

I also am calling GC.Collect() in the dispose just to see if that helped..  it seemed to help a little, but it still grows.

**Comment by ajcvickers** [comment] 2017-01-03 18:18
@codearoo  Could you provide some repro code? It is possible that query caching is erroneously holding onto DbSets, but to root cause that problem we will likely need to see the model and queries being used.

Also, just to confirm, your code does not keep any references to the DbContext or DbSet? (Dispose does not itself free any memory. However, once a DbContext is disposed and all references to it are cleared, then garbage collection should run to release the DbSets and other data associated with that particular instance. Note that EF does global caching of some constructs, rooted in the service provider, which will not be released, but it doesn't sound like that is what you are seeing.)

**Comment by codearoo** [comment] 2017-01-03 19:01
I will need to write some repro code. So far I have a static counter in my DbContext class in constructor and Dispose method, and I can see that it is correctly maintaining 0 instances running after it does some work. In my wrapping Dao I call the Dispose, which has its Dispose called from being wrapped in USING statements. But I'll try to write some new code to bypass all layers to help show something to reproduce.

**Comment by codearoo** [comment] 2017-01-03 19:22
Aha!  It does seem the culprit is with the ServiceProvider!

I ran this code:

`public void TestMemoryLeak()
{
	//using (var db = new xxx.EFMSSQL.MYContext("Server=MSSQL;Database=MY;Trusted_Connection=True;"))
	using (var db = this.services.GetService<xxx.EFMSSQL.MYContext>())
	{
		var data = (from x in db.V_WHATEVER select x).ToList();
	}
}
public void TestMemoryLeakAsync()
{
	Task.Run(() =>
	{
		this.TestMemoryLeak();
		Task.Delay(5 * 1000)
			.ContinueWith(x => this.TestMemoryLeakAsync());
	});
}
`

And when I explicitly called the new object creation, it ran for a while and didn't appear to have the leak. But when I changed it to use the ServiceProvider, BAM!

And this is how the DbContext is registered:
            services.AddTransient<xxx.EFMSSQL.MYContext>(x => new xxx.EFMSSQL.MYContext(mssqlConnString));

**Comment by codearoo** [comment] 2017-01-03 19:48
Back in my main application, if I replace the usage of the DI with a static method that just creates a new instance explicitly, there is no more memory leak.. (at least, not as huge as I see.)  My little test code would add some 100Megs per run when it's using the DI method!

**Comment by codearoo** [comment] 2017-01-05 13:39
Hi... so....  is there another GitHub place that I should submit this bug to?

**Comment by ajcvickers** [comment] 2017-01-05 18:46
@codearoo If there is a memory leak coming from D.I., then you can file a bug on https://github.com/aspnet/DependencyInjection. It would be useful to create a standalone repro that shows the leak.

**Comment by davidfowl** [comment] 2017-01-05 19:14
The DI container keeps track of transient disposables. They won't go away until the container is disposed.

**Comment by ajcvickers** [comment] 2017-01-05 19:19
@davidfowl Agreed, but in the original report above it is stated that the services are being disposed, which implies that the scope is being disposed, which from my quick look at the D.I. code should mean that the list of transients is cleared, which should mean that the memory is freed for GC. I haven't had chance yet to dig into what is actually happening and we haven't got a standalone repro yet, so it may well not be a problem with D.I.

**Comment by codearoo** [comment] 2017-01-05 22:48
@davidfowl Well, how do we tell the container to stop tracking them? It would mean in any typical ASP.Net that is using The ServiceCollection and Transient objects would perpetually keep increasing in size? How can you throw the container away? Isn't it supposed to be created upon App startup and there permanently for other threads to use it to get objects?

**Comment by davidfowl** [comment] 2017-01-08 01:33
@ajcvickers
>  which should mean that the memory is freed for GC

An object dump or memory profile would be the way to see if it's still rooted by anything or if the GC just hasn't run yet.

@codearoo Transient disposable objects (not all transient objects). 

> How can you throw the container away?

Which one, there's a unique scope per request so if you make transient *disposable* objects in there they'll go away at the end of the request.

> How can you throw the container away?

Call dispose on it.

> Isn't it supposed to be created upon App startup and there permanently for other threads to use it to get objects?

Not sure what you mean.

**Comment by ajcvickers** [comment] 2017-02-03 20:42
@codearoo I have not been able to reproduce this leak in either D.I. or EF. Can you please create a repro project that demonstrates the issue?

**Comment by codearoo** [comment] 2017-02-03 21:19
Yes I can.. I just have been really busy and moved on with a work around not using the DI, but still using the EF Context. Somehow it clearly makes the difference when I do not use the DI as a Transient scope. But I'll try to make some time this weekend to write up a test case.

**Comment by ajcvickers** [comment] 2017-02-13 18:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Comment by vbond007** [comment] 2021-03-08 15:18
Hi all. 
I'm reopening this issue because I have exactly the same issue.
It means that if I get a DbContext via DI, then even if DbContext is disposed, the memory is not release the memory. And if I "manually" create a new instance of the DbContext, then everything is OK.

```
int count = 0;
while (count < 1000000)
{
  using (dbContext = _serviceProvider.GetService<MyDbContext>())
  {    
     count++;
  } // Memory is never released
}

count = 0
while (count < 1000000)
{
  using (dbContext = new MyDbContext(options))
  {
     count++;
  }      // Memory is released
}
```

Any idea that could help me?

**Comment by ajcvickers** [comment] 2021-03-08 15:33
@vbond007 The DbContext must be resolved from a service scope, not from the root service provider.

**Comment by vbond007** [comment] 2021-03-08 15:50
Hi, thank you very much for this very quick reply.
I created a scope before and then got the dbContext from it:

```
var scope = _serviceProvider.CreateScope();
using (var dbContext = scope.ServiceProvider.GetRequiredService<MyDbContext>())
{
...
}

```
And it's perfect !
Thank you again.

**Closed** 2022-10-16 10:48 UTC
Labels: closed-could-not-reproduce, customer-reported
