### ISSUE TITLE
BUG: AccessViolationException when Garbage Collection occurs while reading from Sqlite

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/efcore#21469] opened 2020-06-30 13:59 UTC
When calling ````NextResult```` you may get an access violation exception if garbage collection occurs.

### To Reproduce
Run this project in release mode:
[EfTests.zip](https://github.com/dotnet/efcore/files/4852306/EfTests.zip)

### Additional context

Microsoft.Data.Sqlite version: Whatever comes with EFCore 3.1.5 (It looks like 3.1.5)
Target framework: .NET Framework
Operating system: Windows

**Comment by JonathanMagnan** [comment] 2020-06-30 15:09
I get the same issue using`Microsoft.Data.Sqlite` and I was not able to reproduce it with `System.Data.SQLite`

It looks very similar to this one: https://github.com/dotnet/efcore/issues/13987

**Comment by TonyValenti** [comment] 2020-07-01 14:16
Does anyone have a fix for this?

**Comment by ajcvickers** [comment] 2020-07-06 15:32
@TonyValenti Issue #13397 was fixed in the 5.0 previews. Can you try the latest preview (https://www.nuget.org/packages/Microsoft.Data.Sqlite/5.0.0-preview.6.20312.4) and report back if the issue still repros?

**Comment by TonyValenti** [comment] 2020-07-06 15:37
That is unfortunate.  We're stuck on .NET 4.x for the time being and won't be able to upgrade to 5x for some time.  Is there any chance the fix could be back ported?

**Comment by bricelam** [comment] 2021-09-20 20:37
I'm not able to repro this on 3.1.19

**Closed** 2022-10-16 18:31 UTC
Labels: closed-could-not-reproduce, customer-reported, area-adonet-sqlite, punted-for-5.0
