### ISSUE TITLE
Difficultly incorporating full-text search, or even incorporating stored procedure results

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#22440] opened 2020-09-08 03:37 UTC
### Problem

I'm trying to incorporate a full-text search with Entity Framework Core. It appears `EF.Functions.FreeText()` is too limited for my purposes because I need to be able to specify terms like `FORMSOF(INFLECTIONAL, abc)` and on multiple columns.

In fact, I've just given up trying to incorporate a full-text search query directly into Entity Framework so I bit the bullet and added two stored procedures.

    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"CREATE PROCEDURE [dbo].[GetFullTextSearchResults]
        @SearchTerm     nvarchar(4000),
        @SkipRows       int,
        @TakeRows       int
    AS
    BEGIN
        SET NOCOUNT ON;
        SELECT [Articles].[Id],
            [Articles].[Title],
            [Articles].[Slug],
            [Articles].[Description],
            [Categories].[Title] AS [Category],
            [Articles].[UserId],
            [AspNetUsers].[Name] AS [UserName],
            [Articles].[UtcDateModified]
        FROM [Articles]
        INNER JOIN CONTAINSTABLE([Articles], *, @SearchTerm) [t] ON [Articles].[Id] = [t].[Key]
        INNER JOIN [Subcategories] ON [Subcategories].[Id] = [Articles].[SubcategoryId]
        INNER JOIN [Categories] ON [Categories].[Id] = [Subcategories].[CategoryId]
        LEFT OUTER JOIN [AspNetUsers] ON [AspNetUsers].[Id] = [Articles].[UserId]
        WHERE [Articles].[Approved] = 1
        ORDER BY [t].[Rank] DESC
        OFFSET @SkipRows ROWS
        FETCH NEXT @TakeRows ROWS ONLY;
    END");

        migrationBuilder.Sql(@"CREATE PROCEDURE [dbo].[GetFullTextSearchCount]
        @SearchTerm      nvarchar(4000)
    AS
    BEGIN
        SET NOCOUNT ON;
        SELECT COUNT(1)
        FROM [Articles]
        INNER JOIN CONTAINSTABLE([Articles], *, @SearchTerm) [t] ON [Articles].[Id] = [t].[Key]
        WHERE [Articles].[Approved] = 1
    END");

But it looks like I *still* have no way to incorporate the results from a stored procedure into Entity Framework unless the columns returned match one of my entity models. In this case, I need related data and I don't want to return every column in my `Article` entity model.

### Solution

This really shouldn't be as difficult as it is. At this point, if I could just do an ADO.NET type of query, I'd settle for that!

That seems unfortunate. Can't we have better support for this? How about the ability to use `DbContext.Set<ArticleSummaryViewModel>().FromSqlRaw()`, and populate the view model even though it's not an entity model?

Even better, how about more direct support for full-text searches by adding functions that give me more flexibility to specify the type of full-text search I want.

### UPDATE

I'm actually rewriting an existing website. The original version (pre-Core) looks like this:

    var results = DbContext.Database.SqlQuery<ArticleSummary>("GetFullTextSearchResults @SearchTerm, @SkipRows, @TakeRows",
        new SqlParameter("@SearchTerm", fullTextQuery),
        new SqlParameter("@SkipRows", pagination.SkippedRows),
        new SqlParameter("@TakeRows", pagination.RowsPerPage)).ToList();

Note that I didn't have to set up an entity or set for `ArticleSummary`. I just did this query on the fly. Why was that taken away?

And this is *waaaay* to much hassle at this point. Why isn't there even just a command to execute an ADO.NET style query. I'll populate the columns myself if I can just get the results. The convenience of automatically populating my entity isn't worth any of this.

### UPDATE 2

And if this isn't fighting me at every turn enough, even my second stored procedure that only returns an integer value has the same problem. Do I have to create a new entity to contain a single integer?

**Comment by ErikEJ** [comment] 2020-09-08 05:56
@SoftCircuits EF Core Power Tools allows you to map stored procedures, without adding new DbSets / entity models.

**Comment by SoftCircuits** [comment] 2020-09-08 14:16
> @SoftCircuits EF Core Power Tools allows you to map stored procedures, without adding new DbSets / entity models.

Thanks. I'm trying to minimize the number of tools I bring into my project. Having results automatically mapped to my entity is convenient, but not worth any of this. Do you happen to know if there's any way to do a more ADO.NET query against a `DbContext`? I'm capable of mapping the results myself.

**Comment by ErikEJ** [comment] 2020-09-08 15:20
@SoftCircuits  I am not sure exactly what you mean by "more ADO.NET" - but I use this, which emulates the SqlQuery method from back in the EF6 days: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/RevEng.Core/DbContextExtensions

**Comment by SoftCircuits** [comment] 2020-09-08 16:03
@ErikEJ So, I'm not sure I'm understanding all of that. You're creating an extension method but then it looks like you are also setting up a non-keyed entity. Is that needed here?

I played with this a little. Can you tell me what you see as the advantages of your approach over just using an extension method that could be run on the fly without creating any entities? I'm just using a data reader and reflection to populate a generic type. This is what I have so far:

    public static async Task<IEnumerable<T>> SqlQuery<T>(this DbConnection connection, string query, params SqlParameter[] parameters) 
    {
        // TODO: Do we need to close in this case?
        if (connection.State != ConnectionState.Open)
            connection.Open();

        List<T> results = new List<T>();

        using (var cmd = connection.CreateCommand())
        {
            cmd.CommandText = query;
            cmd.CommandType = CommandType.Text;
            foreach (SqlParameter parameter in parameters)
                cmd.Parameters.Add(parameters);

            PropertyInfo[] properties = typeof(T).GetProperties(BindingFlags.Public | BindingFlags.Instance);

            using var reader = await cmd.ExecuteReaderAsync();

            while (await reader.ReadAsync())
            {
                T item = Activator.CreateInstance<T>();

                for (int i = 0; i < reader.FieldCount; i++)
                {
                    if (!await reader.IsDBNullAsync(i))
                    {
                        string name = reader.GetName(i);
                        PropertyInfo property = properties.FirstOrDefault(p => p.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
                        if (property != null && property.CanWrite)
                            property.SetValue(item, reader.GetValue(i));
                    }
                }
                results.Add(item);
            }
        }
        return results;
    }

**Comment by ErikEJ** [comment] 2020-09-08 16:08
I do not need to think about connection handling, and can participate in an EF transaction. 

But your approach looks interesting.

**Comment by ajcvickers** [comment] 2020-09-08 21:39
Duplicate of #10753.

**Closed** 2022-10-16 18:39 UTC
Labels: closed-duplicate, customer-reported
