### ISSUE TITLE
HasQueryFilter on Relationship 

### ISSUE THREAD

**Issue by MoishyS** [dotnet/efcore#30339] opened 2023-02-24 20:03 UTC
I would like to be able to have properties with filtered relationships. for example.

```
public class Blog
{
    public int BlogId { get; set; }
    public string Name { get; set; }
    public string Url { get; set; }

    public List<Post> Posts { get; set; }

    public List<Post> DeletedPosts { get; set; }
    public List<Post> PopularPosts { get; set; }
}

public class Post
{
    public int PostId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }
    public int Votes { get; set; }
    public bool IsDeleted { get; set; }

    public Blog Blog { get; set; }
}
```

and OnModelCreating
```
modelBuilder.Entity<Blog>()
        .HasMany(b => b.DeletedPosts)
        .WithOne(p => p.Blog)
        .HasQueryFilter(p => p.IsDeleted);

modelBuilder.Entity<Blog>()
        .HasMany(b => b.PopularPosts)
        .WithOne(p => p.Blog)
        .HasQueryFilter(p => p.Votes > 100);
````

**Comment by ajcvickers** [comment] 2023-02-25 15:06
Duplicate of #20339. Please vote (👍) for that issue.

**Comment by roji** [comment] 2023-02-25 16:10
Duplicate of #20339!

**Closed** 2023-02-28 19:32 UTC
Labels: customer-reported
