### ISSUE TITLE
Auto generated Guid value in Composite Key

### ISSUE THREAD

**Issue by manospasj** [dotnet/efcore#6958] opened 2016-11-07 15:44 UTC
I have an object with a composite key.
The key consists of 3 columns:
- CustomerId - int
- ServiceId - Guid
- ContractId - Auto Generated Guid

The problem is that when I try to save a new object to the database ContractId gets the value 00000000-0000-0000-0000-00000000000.

On the OnModelCreating method I have the following code to declare the key
```
modelBuilder.Entity<Contract>()
                .HasKey(n => new { n.CustomerId, n.ServiceId, n.ContractId });
```

Also, if I remove the other two columns from the key and keep only ContractId as the primary key, then it's value is auto generated as expected.

**Comment by ajcvickers** [comment] 2016-11-07 17:41
@manospasj Members of composite keys are not set to use value generation by default. You need to tell EF that you want the property to have a value generated:
```C#
modelBuilder.Entity<Contract>()
    .Property(e => e.ContractId).ValueGeneratedOnAdd();
```

**Comment by manospasj** [comment] 2016-11-08 07:44
@ajcvickers your solution seems to work and thanks for that.
I had already tried the annotation [DatabaseGenerated(DatabaseGeneratedOption.Identity)] which doen't work in this case.

I also think it is a bit weird that I have to declare this only for composite keys.
In any case, if this is by design, you should consider updating the docs.

In the [documentation](https://docs.efproject.net/en/latest/modeling/generated-properties.html) states that if you add an entity to the context that has a value assigned to the primary key property, then EF will attempt to insert that value rather than generating a new one. A property is considered to have a value assigned if it is not assigned the CLR default value (null for string, 0 for int, Guid.Empty for Guid, etc.).

**Comment by ajcvickers** [comment] 2016-11-08 17:27
Note for triage: the data annotation should work in this case--at least, it worked like that in the old stack.

@manospasj It's not done for composite keys because all the value generators are designed to generate unique keys. Therefore, only the value of that single property is needed to give the entity identity. Usually a composite key is used when no one part of the key is unique and it is only the combination of values that is unique. For example, an organization ID and a department ID. While it is possible to setup value generators for such composite scenarios most code in these cases just sets explicit values, and so we opted for that as the default behavior. In your case, I'm sure you have a reason for needing a three-part composite key even though only one part is needed to infer unique identity, which is why you can still configure some parts of composite keys to use a value generator if you want.

The documentation you reference describes the different types of value generation behavior. The property was not configured to have value generation until the call to ValueGeneratedOnAdd was made, so I think the documentation matches the behaviors observed.

**Comment by ajcvickers** [comment] 2016-11-08 18:47
Reopening because of the data annotation issue.

**Comment by manospasj** [comment] 2016-11-08 23:56
I have also found that the annotation doesn't seem to work either for single property keys. Let's say that I have a property with the annotations [Key] and [DatabaseGenerated(DatabaseGeneratedaOption.None)], when I add a new entity to my DB I get an exception saying that I can't explicitly set the primary key. Even if I remove the annotations and use fluent api, I get the same exception

**Comment by ajcvickers** [comment] 2016-11-09 00:00
@manospasj What is the full message and stack trace? Is it possible that the column in the database has not been modified even though the EF model has been changed?

**Comment by manospasj** [comment] 2016-11-09 00:06
I don't have the stack trace right now. I will post it tomorrow. But you are right, the column doesn't change. There must be something wrong with the migration, because when I add a new migration, it doesn't see any changes to this property.

**Comment by manospasj** [comment] 2016-11-09 18:49
Below is the full stack trace

```
System.Data.SqlClient.SqlException: Cannot insert explicit value for identity column in table 'DrawResults' when IDENTITY_INSERT is set to OFF.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

# Steps to reproduce
1) Create an Entity with an integer property and annotate it with [Key].
2) Create a migration and update the database.
3) You can see that in the generated migration file is declared like this
```
table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
```
4) Add the [DatabaseGenerated(DatabaseGeneratedOption.None)] annotation to the primary key.
5) Create a new migration.
6) The new migration file alters the column like this
```
migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "MyTable",
                nullable: false);
```
7) Update the database
8) Try to add a new entity to the database.

In my database, after I execute the first migration, the primary key column is specified as Identity and doesn't change after executing the second migration

**Comment by ajcvickers** [comment] 2016-11-09 19:00
Since it is an int and a SQL Server identity column it looks like this is a dupe of #5345. With 1.1 the migration should generate a warning.

**Closed** 2022-10-16 10:41 UTC
