### ISSUE TITLE
Query: Combination of .Select, .Distinct, .Include, and .OrderBy throws exception

### ISSUE THREAD

**Issue by jparish9** [dotnet/efcore#3829] opened 2015-11-20 22:20 UTC
Windows 10, VS 2015, IIS Express, SQL Server Express 2014, EF 7.0.0-rc1-final, ASP.NET 6.0.0-rc1-final

I am seeing a "Sequence contains no matching element" exception when trying to use .Select, .Distinct, .Include, and .OrderBy in the same query.

Models:

``` c#
    public class Blog
    {
        public int BlogId { get; set; }

        public string Title { get; set; }

        public ICollection<Post> Posts { get; set; }

        [ForeignKey("BlogId")]
        public virtual BlogMetadata BlogMetadata { get; set; }
    }
```

``` c#
    public class BlogMetadata
    {
        [Key]
        public int BlogId { get; set; }

        public string Metadata { get; set; }

        public virtual Blog Blog { get; set; }
    }
```

``` c#
    public class Post
    {
        public int PostId { get; set; }

        public int BlogId { get; set; }

        public Blog Blog { get; set; }

        public string PostText { get; set; }
    }
```

FK setup:

```
modelBuilder.Entity<Blog>().HasMany(b => b.Posts).WithOne(p => p.Blog);
modelBuilder.Entity<BlogMetadata>().HasOne(b => b.Blog).WithOne();  // issue 3806 workaround
modelBuilder.Entity<Blog>().HasOne(b => b.BlogMetadata).WithOne();
```

Query:

``` c#
            _dbContext.Posts
                .Select(p => p.Blog)
                .Distinct()
                .Include(b => b.BlogMetadata)
                .OrderBy(b => b.Title)
                .ToList();
```

Exception:

```
Sequence contains no matching element
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.BuildColumnExpression(IReadOnlyCollection`1 projections, TableExpressionBase tableExpression, IProperty property, IQuerySource querySource)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.BuildJoinEqualityExpression(INavigation navigation, TableExpressionBase targetTableExpression, TableExpressionBase joinExpression, IQuerySource querySource)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.<CreateIncludeRelatedValuesStrategyFactories>d__13.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.NewArrayInit(Type type, IEnumerable`1 initializers)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.VisitMethodCall(MethodCallExpression expression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.VisitMethodCall(MethodCallExpression expression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.IncludeNavigations(IncludeSpecification includeSpecification, Type resultType, LambdaExpression accessorLambda, Boolean querySourceRequiresTracking)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_0`1.<CompileQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
...
```

All 4 operations are required to see this exception, things work fine when leaving out any of them.

Given the combination of .Select and .Include, this might be related to https://github.com/aspnet/EntityFramework/issues/3565.  Feel free to close as duplicate if it's the same underlying cause.

**Comment by mikary** [comment] 2016-04-28 16:33
Still reproduces on current dev

**Comment by rowanmiller** [comment] 2016-05-09 20:11
The issue is using Include after projecting to select a navigation property. The workaround is to rewrite the query like

```c#
_dbContext.Blogs
                .Where(b => b.Posts.Any())
                .Include(b => b.BlogMetadata)
                .OrderBy(b => b.Title)
                .ToList();
```

**Comment by maumar** [comment] 2017-04-13 06:29
now we throw the following:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: arguments
   at System.Linq.Expressions.Expression.RequiresCanRead(Expression expression, String paramName)
   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression[] arguments)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in D:\git\EntityFramework\src\EFCore.Relational\Query\ExpressionVisitors\Internal\IncludeExpressionVisitor.cs:line 106
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in D:\git\EntityFramework\src\EFCore.Relational\Query\ExpressionVisitors\Internal\IncludeExpressionVisitor.cs:line 137
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.IncludeNavigations(IncludeSpecification includeSpecification, Type resultType, Expression accessorExpression, Boolean querySourceRequiresTracking) in D:\git\EntityFramework\src\EFCore.Relational\Query\RelationalQueryModelVisitor.cs:line 335
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications) in D:\git\EntityFramework\src\EFCore\Query\EntityQueryModelVisitor.cs:line 489
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications) in D:\git\EntityFramework\src\EFCore.Relational\Query\RelationalQueryModelVisitor.cs:line 276
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel, ICollection`1 includeResultOperators) in D:\git\EntityFramework\src\EFCore\Query\EntityQueryModelVisitor.cs:line 447
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel) in D:\git\EntityFramework\src\EFCore\Query\EntityQueryModelVisitor.cs:line 210
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel) in D:\git\EntityFramework\src\EFCore\Storage\Database.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType) in D:\git\EntityFramework\src\EFCore\Query\Internal\QueryCompiler.cs:line 162
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0() in D:\git\EntityFramework\src\EFCore\Query\Internal\QueryCompiler.cs:line 100
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in D:\git\EntityFramework\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 69
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in D:\git\EntityFramework\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 44
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in D:\git\EntityFramework\src\EFCore\Query\Internal\QueryCompiler.cs:line 97
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in D:\git\EntityFramework\src\EFCore\Query\Internal\EntityQueryProvider.cs:line 62
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
```

**Comment by smitpatel** [comment] 2019-08-22 20:48
Duplicate of #16752

**Closed** 2022-10-16 09:17 UTC
