### ISSUE TITLE
Cosmos DB discussion:PartitionKey

### ISSUE THREAD

**Issue by Mortana89** [dotnet/efcore#14846] opened 2019-02-27 06:07 UTC
It's not a bug, but I'd like to trigger a discussion around the setup of the PartitionKey in the CosmosDB provider.

Initially, in 2.2 preview 2, there was no support for partitionkeys. CosmosDB didn't really enforce the use of it either, unless you went for shared throughput on database level.
Because we have a database per microservice, and a collection per tenant, we did not want to pay 20€/month/collection, and thus went for the shared throughput approach.
To be able to do this we had to do some plumbing ourselves:
- we had to get the CosmosDB provider working (missing headers)
- we had to implement basic support for partitionkeys
- we had to support dynamically setting the container

Up until now this works pretty smooth, until yesterday I was digging around in the stored procedures section of Cosmos, and understood that a SP runs within a PartitionKey. And that's really sh*tty, as we've used the Id field (generated guid by EF) to set as the PK, hardcoded in the provider.
This doesn't allow us to do bulk deletes/updates though...

As the architecture of our platform was getting shaped, our revised plan was to start using Discriminator as the PartitionKey for most of the cases. This would at least allow us to do bulky things within the same entity type.

However, I was digging in the latest codebase for 3.0 preview 3(?) And saw that PartitionKey is set to 0. I didn't quite understand that, and would like to discuss if we cannot set this up using fluent api? On entity level isn't fit for all purposes as many entity types can be stored in one collection, but you can only have one PartitionKey.

What's your thoughts on this?

**Comment by ajcvickers** [comment] 2019-03-01 22:29
Triage: @AndriySvyryd to look for dupe.

**Comment by AndriySvyryd** [comment] 2019-03-01 22:36
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/12086
Partition key configuration is not implemented yet

**Closed** 2022-10-16 13:53 UTC
Labels: closed-duplicate, customer-reported
