### ISSUE TITLE
Query: Make sure arguments & argumentpropagesnullability has same size

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#25854] opened 2021-09-02 22:32 UTC
Needs a validation.

**Comment by ranma42** [comment] 2024-06-23 15:41
This was implemented in c594d314f5eb1483c00394aa233ae4f6254f7f40

**Comment by roji** [comment] 2024-06-23 22:22
Duplicate of #33852

**Closed by roji** 2024-06-23 22:22 UTC
Labels: type-enhancement, customer-reported, area-query
