### ISSUE TITLE
Query: Contains() fails on nav prop's column (nullable and non-nullable)

### ISSUE THREAD

**Issue by AlexBilonog** [dotnet/efcore#5938] opened 2016-07-01 13:55 UTC
Contains() fails on navigation property (AttendeeHistory, AttendeeHistory.Company) with nullable column (ExternalCompany column) or non-nullable (Name column, but it is part of nullable Company nav prop):

(probably to reproduce the issue you need to have in DB ExternalCompany == null and CompanyID == null respectively)

```
var searchText = "1";
db.Set<AttendeeEvent>()
    .FirstOrDefault(a => a.AttendeeHistory.ExternalCompany.Contains(searchText));

// The same issue with the second level nav prop:

db.Set<AttendeeEvent>()
    .FirstOrDefault(a => a.AttendeeHistory.Company.Name.Contains(searchText));

//Configuration:

    public class AttendeeEvent
    {
        public int ID { get; set; }
        public int? AttendeeHistoryID { get; set; }

        public AttendeeHistory AttendeeHistory { get; set; }
    }

    modelBuilder.Entity<AttendeeEvent>(entity =>
    {
        entity.HasOne(d => d.AttendeeHistory)
            .WithMany(p => p.AttendeeEvents)
            .HasForeignKey(d => d.AttendeeHistoryID);
    });

    public class AttendeeHistory
    {
        public AttendeeHistory()
        {
            AttendeeEvents = new HashSet<AttendeeEvent>();
        }

        public int ID { get; set; }
        public string ExternalCompany { get; set; }
        public int? CompanyID { get; set; }

        public ICollection<AttendeeEvent> AttendeeEvents { get; set; }
        public Company Company { get; set; }
    }

    modelBuilder.Entity<AttendeeHistory>(entity =>
    {
         entity.HasOne(d => d.Company)
                    .WithMany(p => p.AttendeeHistories)
                    .HasForeignKey(d => d.CompanyID);
    });
```

Output:

```
Executed DbCommand (168ms) [Parameters=[], CommandType='Text', CommandTimeout='600']
SELECT [a].[ID], [a].[AlternativeCompanyID], [a].[AlternativeCostCenterID], [a].[AttendeeHistoryID], [a].[AttendeeTypeVersionID], [a].[CreationDateTime], [a].[CreationUser], [a].[EventID], [a].[IsCostTranfer], [a].[IsNotParticipated], [a].[IsPlanned], [a].[LastModificationDateTime], [a].[LastModificationUser], [a.AttendeeHistory].[ID], [a.AttendeeHistory].[AttendeeAccessoryID], [a.AttendeeHistory].[AttendeeID], [a.AttendeeHistory].[AttendeeSalutationID], [a.AttendeeHistory].[Birthday], [a.AttendeeHistory].[CompanyID], [a.AttendeeHistory].[CreationDateTime], [a.AttendeeHistory].[CreationUser], [a.AttendeeHistory].[DepartmentID], [a.AttendeeHistory].[Email], [a.AttendeeHistory].[ExternalCompany], [a.AttendeeHistory].[ExternalDepartment], [a.AttendeeHistory].[FirstName], [a.AttendeeHistory].[IsActive], [a.AttendeeHistory].[IsInvitedPerson], [a.AttendeeHistory].[IsManual], [a.AttendeeHistory].[IsTechnicalRewriting], [a.AttendeeHistory].[LastModificationDateTime], [a.AttendeeHistory].[LastModificationUser], [a.AttendeeHistory].[LastName], [a.AttendeeHistory].[ParentAttendeeID], [a.AttendeeHistory].[PersonalNo], [a.AttendeeHistory].[TaxationID], [a.AttendeeHistory].[Title], [a.AttendeeHistory].[ValidFrom]
FROM [AttendeeEvent] AS [a]
LEFT JOIN [AttendeeHistory] AS [a.AttendeeHistory] ON [a].[AttendeeHistoryID] = [a.AttendeeHistory].[ID]
ORDER BY [a].[AttendeeHistoryID]

The thread 0x30cc has exited with code 0 (0x0).
The thread 0xa44 has exited with code 0 (0x0).
Closing connection to database 'XXXXXXXXXXXXX' on server 'SQL01'.
An exception occurred in the database while iterating the results of a query.
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , TransparentIdentifier`2 )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
Exception thrown: 'System.NullReferenceException' in Microsoft.EntityFrameworkCore.dll
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>EFGetStarted.ConsoleApp.vshost.exe</AppDomain><Exception><ExceptionType>System.NullReferenceException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Object reference not set to an instance of an object.</Message><StackTrace>   at lambda_method(Closure , TransparentIdentifier`2 )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.&amp;lt;&amp;gt;c__DisplayClass19_1`1.&amp;lt;CompileQuery&amp;gt;b__1(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at EFGetStarted.ConsoleApp.Program.Main() in C:\Work\Console4\EFGetStarted.ConsoleApp\Program.cs:line 16
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</StackTrace><ExceptionString>System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , TransparentIdentifier`2 )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.&amp;lt;&amp;gt;c__DisplayClass19_1`1.&amp;lt;CompileQuery&amp;gt;b__1(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at EFGetStarted.ConsoleApp.Program.Main() in C:\Work\Console4\EFGetStarted.ConsoleApp\Program.cs:line 16
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</ExceptionString></Exception></TraceRecord>
```
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 8.1
Visual Studio version: 2015 Enterprise Update 3

**Comment by rowanmiller** [comment] 2016-07-07 17:55
This is failing because the evaluation of `a => a.AttendeeHistory.ExternalCompany.Contains(searchText))` is happening on the client, rather than being pushed to the database. When the predicate is run in .NET, you get a null ref because we are literally just running that code. When we translate this to SQL, it will work because the database is more forgiving in terms of evaluating conditions against left joined data.

In the meantime, you would need to write this defensively:

```c#
db.Set<AttendeeEvent>()
    .FirstOrDefault(a => a.AttendeeHistory != null && a.AttendeeHistory.ExternalCompany.Contains(searchText));
```

**Comment by rowanmiller** [comment] 2016-07-07 17:57
Closing this one out, as we are already have several issues tracking translating conditions that involve optional navigations. cc @anpete @maumar if one of you could link to the relevant issue?

**Comment by PaulRReynolds** [comment] 2016-07-15 13:10
Hi folks, any chance of a link to the relevant issue on this one? @anpete @maumar Would be really appreciated so that we can get an idea of the milestone. Thanks!

**Comment by maumar** [comment] 2016-07-15 17:49
duplicate of https://github.com/aspnet/EntityFramework/issues/5613

**Closed** 2022-10-16 09:48 UTC
