### ISSUE TITLE
How can I dynamically check that all changed entries tracked by change tracker relate to same aggregate?

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#30007] opened 2023-01-08 17:12 UTC
I register DbContext with scoped lifetime, but I want to enforce the rule that each round of changes relates to aggregate of particular type.

```CSharp
var agg1 = dbContext.Set<Aggregate1>().First();
var agg2 = dbContext.Set<Aggregate2>().First();

agg1.ChangeState();
dbContex.SaveChanges();

agg2.ChangeState();
dbContext.SaveChanges();
```
This fragment should work fine, whereas the following one should throw:

```CSharp
var agg1 = dbContext.Set<AggregateRoot1>().First();
var agg2 = dbContext.Set<AggregateRoot2>().First();

agg1.ChangeState();
agg2.ChangeState();
dbContex.SaveChanges(); // Throws;
```

Provided, I can find aggregate roots among tracked entries, I should be able to navigate to changed entries and thus acquire types of changed aggregates.

I already asked a similar [question](https://github.com/dotnet/efcore/issues/27848), but it looks like `MaterializationInterceptor` does not help much here.

I currently use this code, to count the number of changed entries which relate to the aggregate:
```CSharp
private List<EntityEntry> GetAffectedAggregateGraphEntries(TAggregateRoot aggregateRoot) 
    =>
    GetAffectedGraphEntriesRecursive(aggregateRoot, new HashSet<object>()).ToList();

private IEnumerable<EntityEntry> GetAffectedGraphEntriesRecursive(
    object rootEntity, HashSet<object> checkedEntities)
{
    // thus we prevent cycles.
    if (checkedEntities.Contains(rootEntity))
    {
        yield break;
    }

    var rootEntityEntry = _dbContext.Entry(rootEntity);
    if (rootEntityEntry.State == EntityState.Detached)
    {
        throw new InvalidOperationException($"Root entity of type '{rootEntity.GetType()}' is not tracked.");
    }

    checkedEntities.Add(rootEntityEntry);

    var affected =
        rootEntityEntry.State == EntityState.Added
        || rootEntityEntry.State == EntityState.Modified
        || rootEntityEntry.State == EntityState.Deleted;
    if (affected)
    {
        yield return rootEntityEntry;
    }

    var newModifiedOrDeletedChildEntires = rootEntityEntry.Navigations.SelectMany(_ => _.CurrentValue switch
    {
        null => Enumerable.Empty<EntityEntry>(),
        IEnumerable seq =>
            seq.OfType<object>()
                .Where(/* except navigations to aggregates */_ => _ is not IAggregateRoot)
                .SelectMany(_ => GetAffectedGraphEntriesRecursive(_, checkedEntities)),
        { } entity when entity is not IAggregateRoot /* except navigations to aggregates */ =>
            GetAffectedGraphEntriesRecursive(entity, checkedEntities),
        _ => Enumerable.Empty<EntityEntry>()
    });

    foreach (var newModifiedOrDeletedChildEntry in newModifiedOrDeletedChildEntires)
    {
        yield return newModifiedOrDeletedChildEntry;
    }
}
```

But it does not work with deleted entities.

**Comment by ajcvickers** [comment] 2023-01-10 18:29
Duplicate of #29848.

**Closed** 2023-01-12 12:48 UTC
Labels: customer-reported
