### ISSUE TITLE
Inspect the contents of a migration bundle and view generated SQL

### ISSUE THREAD

**Issue by statler** [dotnet/efcore#31844] opened 2023-09-25 08:00 UTC
When we generate a migration bundle, it contains specific information about migrations that can be applied. I cannot find a way that this information can be inspected. Ideally I would want to be able to:
1. View the migrations that are contained in the bundle
2. Export the SQL that will be generated and applied to the database

As this is already included, if it isn't already possible, it wouldn't be hard to add options.

**Comment by ajcvickers** [comment] 2023-09-25 09:05
Duplicate of #25872

**Closed** 2023-10-02 19:24 UTC
Labels: customer-reported
