### ISSUE TITLE
Incorrect SQL Generation (DISTINCT)

### ISSUE THREAD

**Issue by Silvenga** [dotnet/efcore#14332] opened 2019-01-06 05:50 UTC
So in LinqPad I have this badly formatted query (simplified, removed conditionals):

```csharp
var query = from grain in MinionGrains
			join value in MinionGrainValues on grain.Id equals value.MinionGrainId
			select new
			{
				grain.Path,
				value.Value,
				grain.Generation
			};

var paths = (from minionGrain in MinionGrains
	            from generation in query.Where(x => x.Generation == minionGrain.Generation)
	            select minionGrain.Path)
			.Distinct()
			.ToList();
```

This generates the following SQL:

```sql
SELECT DISTINCT t."Path", t."Value", t."Generation", "minionGrain"."Path"
FROM "MinionGrains" AS "minionGrain"
CROSS JOIN LATERAL (
    SELECT grain."Path", value."Value", grain."Generation"
    FROM "MinionGrains" AS grain
    INNER JOIN "MinionGrainValues" AS value ON grain."Id" = value."MinionGrainId"
    WHERE grain."Generation" = "minionGrain"."Generation"
) AS t
GO
```

Coming from EF6, I would have expected something closer to:

```sql
SELECT DISTINCT t."Path"
FROM "MinionGrains" AS "minionGrain"
CROSS JOIN LATERAL (
    SELECT grain."Path", value."Value", grain."Generation"
    FROM "MinionGrains" AS grain
    INNER JOIN "MinionGrainValues" AS value ON grain."Id" = value."MinionGrainId"
    WHERE grain."Generation" = "minionGrain"."Generation"
) AS t
```

So two problems:
- The projection in Linq is not translating to the SQL (`t."Value", t."Generation", "minionGrain"."Path"` should not be returned)
- The distinct is applying to columns not originally selected for the distinct, only `Path` should be under the distinct.

### Further technical details
EF Core version: `2.2.0`
Database Provider: `Npgsql.EntityFrameworkCore.PostgreSQL` `2.2.0`
Operating system: `Windows`
IDE: `VS2017 15.9.4`

**Comment by smitpatel** [comment] 2019-01-06 17:55
Duplicate of #8094

**Closed** 2022-10-16 13:46 UTC
Labels: closed-duplicate, customer-reported
