### ISSUE TITLE
Update owned entity won't generate concurrency token (RowVersion) refresh

### ISSUE THREAD

**Issue by rayao** [dotnet/efcore#19719] opened 2020-01-27 13:17 UTC
I'm not sure if this has been fixed already in latest version of EFCore, I only found it on 2.2
If this is by design is there any workaround? For now I manually issue a query.

If an update only touches owned entity, the generated SQL doesn't include a SELECT clause to retrieve concurrency token (RowVersion) column.

### Steps to reproduce

class Entity
{
    public OwnedEntity {get;set;}
    public byte[] Version {get;set;}
}

class OwnedEntity
{
    public Property {get;set;}
}

The OwnedEntity is configured with split table, with an Entity object attached to DbContext, I expected updating OwnedEntity would result in Entity.Version being updated (refreshed) from DB. But that's won't happen, the generated SQL doesn't include a SELECT to retrieve new value of Version, as when the update targets Entity itself.

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 2.2
Operating system:
I think irrelevant
IDE:
I think irrelevant

**Comment by ajcvickers** [comment] 2020-01-27 16:14
Related to #14154 and #18529

/cc @AndriySvyryd

**Comment by AndriySvyryd** [comment] 2020-01-27 17:11
Duplicate of #18529
The workaround is to define a concurrency token on the owned entity (can be in shadow-state) and map it to the same column as the one declared on the owner.

**Comment by davewelsh** [comment] 2021-07-31 18:49
> The workaround is to define a concurrency token on the owned entity (can be in shadow-state) and map it to the same column as the one declared on the owner.

Could you post an example of this?

```
builder.Entity<ChildEntity>().Property("Version").IsRowVersion().SomehowMapThisToAColumnInTheParentTable()
```

**Closed** 2022-10-16 18:08 UTC
Labels: customer-reported
