### ISSUE TITLE
Dictionary<string,string> is not support as Json Columns

### ISSUE THREAD

**Issue by khalilsheikh** [dotnet/efcore#30917] opened 2023-05-17 21:50 UTC
Unable to create a 'DbContext' of type 'DbContext'. The exception 'The 'Dictionary<string, string>' property 'Type.Property' could not be mapped because the database provider does not support this type. Consider converting the property value to a type supported by the database using a value converter.See https://aka.ms/efcore-docs-value-converters for more information. Alternately, exclude the property from the model using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

**Comment by ajcvickers** [comment] 2023-05-18 07:33
Duplicate of #26903

**Closed by ajcvickers** 2023-05-18 07:33 UTC
Labels: customer-reported
