### ISSUE TITLE
`IncludeAssets` seems to break IPluralizer

### ISSUE THREAD

**Issue by dharmaturtle** [dotnet/efcore#16932] opened 2019-08-03 23:44 UTC
Upgrading from Preview 3 to 4 caused my program to be unable to find `IPluralizer`. Guilherme Battista also noticed this problem [here](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-4/#comments-1436).

I notice that if I delete the `<IncludeAssets>` tag it fixes the issue. It is unclear to me why this would fix the problem. Looking back in history, a delta between Preview3 and 4 is that 4 adds the `PrivateAssets` and `IncludeAssets` elements by default, which caused the issue to appear.

### Steps to reproduce
Add the following to a new Console.csproj:
```
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.0-preview7.19362.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
```
(This is what appears by default when you install Preview7; also available [here](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Design/3.0.0-preview7.19362.6) in the `PackageReference` tab.)

In Program.cs, add this line:
```Microsoft.EntityFrameworkCore.Design.IPluralizer myPluralizer;```
Build and notice the following error:
`The type or namespace name 'EntityFrameworkCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)`
Delete the `IncludeAssets` line, and notice that it successfully builds.
### Further technical details
EF Core version: Preview 7, though it also applies to Preview 4

**Comment by ajcvickers** [comment] 2019-08-05 14:41
Duplicate of #11506

See [Microsoft.EntityFrameworkCore.Design is now a DevelopmentDependency package](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#microsoftentityframeworkcoredesign-is-now-a-developmentdependency-package)

**Closed** 2022-10-16 14:33 UTC
Labels: customer-reported
