### ISSUE TITLE
SQL Generation Bug - Select null-able navigation property return empty list 

### ISSUE THREAD

**Issue by rexebin** [dotnet/efcore#4342] opened 2016-01-20 17:04 UTC
I have two entities, their relationship is 0 or 1 to many. 

When I use select to query the parent entity like the following, the result is an empty list:

.Select(s=>new DtoModel{
Id = s.Id,
ChildId = s.ChildId
ChildFullName =(s.Child != null) ?( s.Child.FirstName + " " + s.Child.LastName):string.Empty
}).ToList();

ChildFullName is a string property in the Dto model. In the domain class, ChildId is nullable and thus the entity can have one or no child entity.

I used SQL Server Profiler to capture the sql generated by the above select query, I found that the generated sql uses INNER JOIN to join the child entity. However in this case, a LEFT Join is correct. 

I copied the generated sql to management studio, only change INNER to LEFT, it returned the result I wanted. 

My EF7 version is 7.0.0-rc1-Final.

If there is any work around at the moment, please let me know. 

Thank you very much.

**Comment by smitpatel** [comment] 2016-01-20 17:31
dupe of #3186

**Comment by rexebin** [comment] 2016-01-20 17:41
Thanks, tried to search the problem before posting, but didn't find any. I obviously need to improve my search skills:)

**Comment by rowanmiller** [comment] 2016-01-20 17:45
@rexebin no problem... I look at every issue that comes in and I still spend a lot of searching around thinking "I'm sure we have another issue tracking this somewhere" :smile:

**Comment by smitpatel** [comment] 2016-01-20 17:53
The related issue's title was not clear enough to make it appear in search. I changed it too. :)

**Comment by rexebin** [comment] 2016-01-20 17:55
You guys are great! Thank you very much for your hard working!

Sent from Outlook Mobile




On Wed, Jan 20, 2016 at 9:53 AM -0800, "Smit Patel" <notifications@github.com> wrote:












The related issue's title was not clear enough to make it appear in search. I changed it too. :)

**Closed** 2022-10-16 09:25 UTC
