### ISSUE TITLE
Issue when creating a migration using dotnet ef migrations add Visual Studio 2019 reports a missing assembly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#24414] opened 2021-03-16 15:11 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Issue-when-creating-a-migration-using-do/1311913)._

---
[severity:I'm unable to use this version]
So I am building an ASP.Net Core Web Application after I add the references in Visual Studio 2019 to Microsoft.EntityFrameworkCore.Design and Microsoft.EntityFrameworkCore.SqlServer there are no reference errors, but when I run the command line tool dotnet ef migrations add Initial.  I get the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'EntityFrameworkCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	SportsStore	C:\Users\dmcmillan\Documents\Visual Studio 2019\Projects\SportsStore\Models\StoreDbContext.cs	1	Active

It's as if the references are disappearing.  I'm not sure if this is an issue for .NET or VS 2019 but since it comes up after I run the CLI command I thought I would post it here.

Here is the relevant parts from my csproj file

```
    
    
      all
      runtime; build; native; contentfiles; analyzers; buildtransitive
    
    

```

Really puzzled why this is happening.

---
#### Feedback Bot on 1/17/2021, 11:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2021-03-16 15:28
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2021-03-23 15:32
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:28 UTC
Labels: closed-could-not-reproduce, customer-reported
