### ISSUE TITLE
Ef Core 1.1 Error - Invalid JSON file in C:\Projects\project.json

### ISSUE THREAD

**Issue by kwameg-a** [dotnet/efcore#7173] opened 2016-12-01 22:15 UTC
Please find below the **project.json** file:
```json
{
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.AspNet.Identity": "3.0.0-rc1-final",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "NETStandard.Library": "1.6.1"
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview4-final"
  },

  "frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50"
    }
  }
}
```
### The issue
When I run the update-database command in VS Package Manager Console, I instantaneously get this error - **Invalid JSON file in C:\Projects\project.json**, without running the program and return to the command prompt as shown below:
**PM> update-database
Invalid JSON file in C:\Projects\project.json
PM>** 

EF Core version: 1.1
Operating system: 
Visual Studio version: (e.g. VS 2015)

**Comment by rowanmiller** [comment] 2016-12-07 23:09
Possibly a duplicate of https://github.com/aspnet/EntityFramework/issues/7197. Do you have a startup project that has the tools listed as a dependency? I see you have them listed in the `tools` section, but that section if just for .NET CLI Tools and would only enable `dotnet ef` at the command line, and not `Update-Database` in Package Manager Console (except you would want `Microsoft.EntityFrameworkCore.Tools.DotNet` rather than `Microsoft.EntityFrameworkCore.Tools` in the `tools` section).

I also notices you have `1.0.0-preview4-final` listed as the version, but that isn't a valid version. You want `1.1.0-preview4-final`.

Assuming you have a startup app, could you post the project.json for that too?

**Closed** 2022-10-16 10:45 UTC
Labels: closed-duplicate
