### ISSUE TITLE
SQL Function calls get client evaluated if projecting entire entity despite EvaluatableExpressionFilter properly returning false for them

### ISSUE THREAD

**Issue by rwasef1830** [dotnet/efcore#15203] opened 2019-03-29 12:25 UTC
Hello,
This is related to https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/853

The npgsql Entity Framework Core driver defines full text search functions that do not have a client implementation (throws NotSupportedException) and thus uses an `EvaluatableExpressionFilter` to tell EF Core to always server-side evaluate these functions.

In the test below (using Npgsql EF Core driver 3.0.0-preview1, but this issue is also present with the stable version which references EF Core 2.2):
```cs
[Fact]
public void Test_bug_853()
{
    using (var context = CreateContext())
    {
        var query = context.Customers
            .Where(x => x.CompanyName != null)
            .Select(
                x => new
                {
                    Recommendation = x,
                    Rank = EF.Functions.ToTsVector(x.CompanyName)
                });

        query.ToList();
    }
}
```
The test fails with a `NotSupportedException` that is thrown from `ToTsVector`. EF Core tries to client evaluate it. Changing `Recommendation = x` to `Recommendation = x.CompanyName` (ie: change from projecting entire entity to projecting any subset of it) causes the test to pass.

Digging through this in EF Core 3.0.0-preview3 I found the following:
1. In both cases the EvaluatableExpressionFilter works correctly and the function is translated to a `SqlFunctionExpression`.
2. The if condition on this line: https://github.com/aspnet/EntityFrameworkCore/blob/8f9c2cf541820969b9fc4b30a18d5f534c14ba46/src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs#L294 which gets called as part of query compilation: In case of partial projection, `targetExpression.Type` is of type `ValueBuffer` so the sqlExpression that is translated above is added to the projection and the function is server evaluated and the test passes. But in case of a full entity projection, `targetExpression.Type` is the projected entity type, so the if branch is skipped and the translated sqlExpression is discarded by the visitor, and the original expression is returned, so later on the function is client-evaluated thus throwing NotSupportedException.

Hope that helps in narrowing down what is wrong.

/cc @roji

**Comment by smitpatel** [comment] 2019-03-29 16:15
Duplicate of #11186

**Closed** 2022-10-16 13:58 UTC
Labels: closed-duplicate, customer-reported
