### ISSUE TITLE
DbContext problem

### ISSUE THREAD

**Issue by lokinfey** [dotnet/efcore#2583] opened 2015-07-09 10:40 UTC
this is my project.json 

``` json
{
  "version": "1.0.0-*",
  "description": "GdouWechat.Data Class Library",
  "tags": [""],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "EntityFramework": "7.0.0-*",
    "EntityFramework.SqlServer": "7.0.0-*",
    "EntityFramework.Relational" : "7.0.0-*",
    "EntityFramework.Commands": "7.0.0-*",
    "Microsoft.AspNet.Mvc": "6.0.0-beta5",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-*",
     "GdouWechat.Domain":""
  },
    "commands": {
        "ef" : "EntityFramework.Commands"
    },

  "frameworks": {
    "dnx451": {},
    "dnxcore50": {}
  }
}
```

my dbContext

``` c#
using System.Collections.Generic;
using System.Linq;
using GdouWechat.Domain;
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Metadata;

namespace GdouWechat.Data
{
    public class GdouWechatDataContext : DbContext
    {
        public DbSet<QuestionInfo> QuestionInfos { get; set; }
        public DbSet<LocInfo> LocInfos {get;set;}
        public DbSet<RegInfo> RegInfos {get;set;}

        public virtual void Commit()
        {
            try
            {
                base.SaveChanges();
            }
            catch 
            {


                throw;  // You can also choose to handle the exception here...
            }


        }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        { 
            modelBuilder.Entity<QuestionInfo>().Key("ID");
            modelBuilder.Entity<LocInfo>().Key("id");
            modelBuilder.Entity<RegInfo>().Key("id");

        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"");
        }



    }


}
```

I build it it said 

![2015-07-09 6 39 54](https://cloud.githubusercontent.com/assets/4607663/8593391/e769cb08-2669-11e5-8909-076753834574.png)

**Comment by natemcmaster** [comment] 2015-07-09 16:37
This bug is a duplicate of https://github.com/aspnet/EntityFramework/issues/2583 and https://github.com/aspnet/Home/issues/730. @lokinfey update those threads rather than recreating new ones for the same issue.

**Closed** 2022-10-16 09:01 UTC
