### ISSUE TITLE
EF Core 3.1.0 Linq query selects unwanted fields when global filter is applied

### ISSUE THREAD

**Issue by bharatdwarkani** [dotnet/efcore#19946] opened 2020-02-16 16:44 UTC
EF Core 3.1.0 query generated is not optimized when the global filter is applied. If two tables are joined then SQL generated for the  joined table when a global
 the filter is applied selects all columns of a table instead of just selecting a global filter column or required columns.

### Steps to reproduce
 
I have compared the SQL generated by LINQ by profiling in Azure Data Studio and dot net core console debug logs.

In the below screenshot, One query is without applying Global Filter in entity table and other on applying global filter (OrgID column is a global filter column). The query generated by Linq selects all columns (from AgentAdditionalNotifications Table) when the global filter is applied.

Another issue global filter adds where the condition for OrgId in inner subquery instead of applying where outside join

![image](https://user-images.githubusercontent.com/12810605/74608680-486ed500-5109-11ea-9287-15555814efcd.png)

**Expected optimized Output when global filter applied which is not generated by LINQ at present**

![image](https://user-images.githubusercontent.com/12810605/74609094-b8328f00-510c-11ea-9397-ce394dedb050.png) 

### Further technical details

EF Core version: 3.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) : Azure SQL
Target framework:  .NET Core 3.1 LTS
Operating system: WIndows
IDE: VS 2019

**Comment by ajcvickers** [comment] 2020-02-18 21:36
@smitpatel @maumar to find dupe.

**Comment by smitpatel** [comment] 2020-02-18 22:09
Duplicate of #17161

**Comment by bharatdwarkani** [comment] 2020-02-19 08:20
@smitpatel  I dont think it is related to issue which you have linked as duplicate. In my case issue occurs in global filter. Please revisit

**Comment by smitpatel** [comment] 2020-02-19 08:28
It is same issue. In the absence of global query filter there is no where predicate for right side of join hence it is flattened out. Even if you remove global query filter and apply a where predicate on inner source of the join it would produce the same result.

**Closed** 2022-10-16 18:11 UTC
Labels: customer-reported
