### ISSUE TITLE
Allow migrations to update data according to user logic

### ISSUE THREAD

**Issue by mc0re** [dotnet/efcore#21582] opened 2020-07-10 10:10 UTC
It'd be nice if along with `HasData` there was a model builder method, defining a more dynamic UPDATE operation, producing something like:
```
UPDATE Table SET Col1 = 'A' WHERE ColB = 'B'
```

**Comment by roji** [comment] 2020-07-10 10:29
@mc0re migrations are about taking the data described in your model via HasData, and generating the appropriate SQL to bring the database to that state. In other words, your model describes a "snapshot" of how the database should look like, and it's the migrations' job to figure out how to make that happen. If your model previously had a HasData for some entity with ColB having foo, and you now change the HasData to make ColB have bar instead, add a new migration should cause more or less the above UPDATE to be automatically generated. In other words, you shouldn't need to express the UPDATE yourself.

If you're requesting general bulk update/delete support (outside of HasData or migrations), that's tracked by #795.

**Comment by mc0re** [comment] 2020-07-10 10:38
I do need it if the product was in use for some time.

**Comment by roji** [comment] 2020-07-10 11:09
@mc0re data seeding isn't meant to be manipulated outside migrations by users - if this is done, the data gets out of sync with the model. Seeding really is meant only for static data that isn't touched by users.

However, you can always simply generate a new, empty migration and use raw SQL (migrationBuilder.Sql) to perform any update you want to put the data back in sync. Some details are available in the [migration docs](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#customize-migration-code). This should be what you're looking for.

**Comment by mc0re** [comment] 2020-07-10 12:45
I see.
So how to go about, say, a table of roles, where some roles are provided initially by the seeding, and some are added by the users later on, after the program was deployed? And now, for some bizzaire reason, I want to add an `IsAdmin` column and set it to `TRUE` if the role name starts with "A"...

**Comment by roji** [comment] 2020-07-10 14:57
>  So how to go about, say, a table of roles, where some roles are provided initially by the seeding, and some are added by the users later on, after the program was deployed? And now, for some bizzaire reason, I want to add an IsAdmin column and set it to TRUE if the role name starts with "A"...

It's OK for additional roles/users to be added outside of migrations. However, for those users managed by migrations (via data seeding, HasData), you *must* update your model's HasData yourself (i.e. add the IsAdmin column with the proper value your want). This is because as I wrote above, migrations work by comparing snapshots to see if anything changed, so your model must always have the complete information for seeding.

To put another way, your model's HasData describe a snapshot or *state*. EF Core knows how to generate migrations (and from them, SQL) to transition the database from one state to another. What you're asking for is to express a *change* in your model (i.e. express an UPDATE operation via HasData or similar), but things don't work that way.

You may also want to consider dropping data seeding, and simply managing your roles/users (or whatever) yourself, rather than via migrations.

> So writing raw SQL goes against this model.

That's true, and as long as you stick to regular data seeding - updating your seeded entities in the model definition - you don't need to do any SQL. Also, if you decide to manage your data without seeding, you can do that via the regular EF Core means without SQL.

**Comment by ajcvickers** [comment] 2020-07-10 16:26
Looks like a duplicate of #5642

**Comment by mc0re** [comment] 2020-07-10 18:42
> if you decide to manage your data without seeding...
I'm afraid I missed that part. If I add an `IsAdmin` column to `RoleEntity`, how do I fill it in for the user-created roles? With an API that allows users to modify the roles? Or did you mean something else?

**Comment by roji** [comment] 2020-07-10 19:51
@mc0re you'd fill it in like you'd modify any other EF Core entity - by querying the users you want, iterating over them, setting the IsAdmin property, and then calling SaveChanges.

**Comment by mc0re** [comment] 2020-07-10 21:49
This is a feasible solution for smaller tables, where everything fits into memory. But in a lack of support for anything else - yep, it has to do.

**Comment by ajcvickers** [comment] 2020-07-13 19:41
Closing as duplicate of #5642

**Closed** 2022-10-16 18:33 UTC
