### ISSUE TITLE
Performance issue when perform filtering using Where query in .NET 6 framework

### ISSUE THREAD

**Issue by dhivyasyncfusion** [dotnet/efcore#27525] opened 2022-03-01 09:08 UTC
### Describe the bug

Sample: https://github.com/dhivyasyncfusion/Filter

Code:

```
            Type type = dataSource.ToList().GetType().GetGenericArguments()[0];
            ParameterExpression paramExpression = Expression.Parameter(type, type?.Name);
            dataSource = dataSource.Where(Expression.Lambda<Func<T, bool>>(PredicateBuilder(dataSource, whereFilter ?? null, condition, paramExpression, type), paramExpression));
            return dataSource;
```

In our scenario we generated 1000 predicate to perform filtering, When we run the same with .net 5 we can able to get the result data immediately(~1s) in dataSource but In .net 6 it take more time (~150s) get the result before that we tried to expand the result view we are getting the below evaluation time out issue. We suspect expression.compile() will take more time evaluate the expression.

### Expected Behavior

In .NET 5 the same code took ~2 milliseconds where as in .NET 6 it takes ~150 milliseconds. Need the performance same as .NET 5. 

### Steps To Reproduce

1.	Run the sample.
2.	Click Filter button.
3.	In click handler we perform filtering(Filtering.PerformFiltering(Employees as IEnumerable<object>, query, "and")).
4.	You can get the filtered value immediately but when we try to access the result view to see the result it shows the below error.
5.	It take more time to get the result and perform ToList operation(final.ToList()).

```
            query.Add(new Filtering.WhereFilter() { Condition = "or", IsComplex = true, predicates = PredicateList });
            var final = Filtering.PerformFiltering(Employees as IEnumerable<object>, query, "and");
            var result = final.ToList();
            var data = result;
```

**Note: Put debugger in both result and data(to see the performance delay ) you can get the result immediately but it took more time to get data and perform toList.**

### Exceptions (if any)

![image](https://user-images.githubusercontent.com/33689858/156139363-698de9e3-970a-4966-90ad-0646e5328bad.png)

### .NET Version

7.0.200-preview.22055.15

**Comment by roji** [comment] 2022-03-01 13:24
@dhivyasyncfusion I can't see any Entity Framework code in your sample - it seems you are reporting a slow-down in in-memory compilation/evaluation of an expression tree? If so, this issue would belong in https://github.com/dotnet/runtime.

I also *highly* recommend producing a simple workaround that does not involve either ASP.NET or debugging/using breakpoints. It would be far better to submit a simple [BenchmarkDotNet](https://benchmarkdotnet.org) benchmark, where it is easy to immediately see the running time etc.

**Comment by syncsiva** [comment] 2022-03-03 12:05
Recreated the issue in simple console app and logged it here
https://github.com/dotnet/runtime/issues/66076

**Comment by roji** [comment] 2022-03-03 12:16
Duplicate of https://github.com/dotnet/runtime/issues/66076

**Closed** 2022-10-16 20:27 UTC
Labels: closed-external, customer-reported
