### ISSUE TITLE
Ambiguous Invocation error with Contains

### ISSUE THREAD

**Issue by eltiare** [dotnet/efcore#18469] opened 2019-10-20 18:06 UTC
Ambiguous error when trying to select models whose IDs are contained in array. 

<img width="898" alt="Screen Shot 2019-10-20 at 12 01 38 PM" src="https://user-images.githubusercontent.com/3036/67163884-b4932500-f331-11e9-8646-345f41e8cd4e.png">

### Steps to reproduce
```
var ids = new [] { 1, 2, 3 };
var models = await dbContext.Models.Where(m => ids.Contains(m.Id)).ToListAsync();
```

### Further technical details

EF Core version: 3.0
Database provider: Npgsql
Target framework: .NET Core 3.0
Operating system: MacOS 10.14.6
IDE: JetBrains Rider

**Comment by eltiare** [comment] 2019-10-25 15:28
@ajcvickers It returns `IQueryable<SignedWaiver>`

**Comment by ajcvickers** [comment] 2019-10-25 16:21
@eltiare I have not been able to reproduce this--see my code below. Please post a small project/solution or complete code listing that demonstrates the error you are seeing.

```C#
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

public class SignedWaiver
{
    public int Id { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseInMemoryDatabase("Test");
    }

    public DbSet<SignedWaiver> Models { get; set; }
}

public class Program
{
    private BloggingContext _context;
    
    public IQueryable<SignedWaiver> Scope() => _context.Models;

    public async Task Test()
    {
        _context = new BloggingContext();
        _context.Database.EnsureCreated();
        _context.Database.EnsureDeleted();
        
        var ids = new [] { 1, 2, 3 };
        var models = await Scope().Where(m => ids.Contains(m.Id)).ToListAsync();
    }
    
    public static async Task Main()
    {
        await new Program().Test();
    }
}
```

**Comment by ajcvickers** [comment] 2019-11-01 15:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:51 UTC
Labels: closed-could-not-reproduce, customer-reported
