### ISSUE TITLE
Possible to use FromSql() with a type that is not necessarily a DbSet?

### ISSUE THREAD

**Issue by csaloio** [dotnet/efcore#4653] opened 2016-02-26 20:12 UTC
If I want to execute a simple query such as listing the names of the roles in a role table I can do this:

```
var sql = "SELECT r.name FROM com.role r";
return _ctx.Roles.AsNoTracking().FromSql(sql).Select(r => r.name).ToList();
```

Which will produce SQL like:

```
 SELECT "r"."name"
      FROM (
          SELECT r.name FROM com.role r
      ) AS "r"
```

It would be nice if I could instead do something like this:

```
var sql = "SELECT r.name FROM com.role r";
return _ctx.FromSql<string>(sql).ToList();
```

so that the result set doesn't have to map to a type setup as a DbSet in the context. Is this possible or something you'd consider adding in some way?

**Comment by divega** [comment] 2016-02-26 21:29
Dupe of #1862.

**Closed** 2022-10-16 09:30 UTC
