### ISSUE TITLE
Counterintuitive property initialization

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/efcore#10783] opened 2018-01-26 23:41 UTC
When I initialize an entity property like so: 

        public string Name {
            get { return this._name; }
            set { this.SetValue(ref this._name, value, nameof(this.Name)); }
        }
        private string _name = ""; 

then the SetValue method is called by the initializing assignment ( _name = "" ). 

It seems counterintuitive. 

If it is of any interest I am using change-tracking proxies: 

            ChangeTrackingStrategy strategy = ChangeTrackingStrategy.ChangingAndChangedNotificationsWithOriginalValues;
            modelBuilder.HasChangeTrackingStrategy(strategy);

I am also using the default property access mode.

**Comment by ajcvickers** [comment] 2018-01-29 20:27
@sjb-sjb We looked at this in triage, but we don't understand how this can be true: "then the SetValue method is called by the initializing assignment ( _name = "" )." Can you explain in more detail what you mean?

**Comment by ajcvickers** [comment] 2018-02-05 18:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by sjb-sjb** [comment] 2018-10-02 03:54
Comment, this could have been due to a navigation property being set through a property setter, during a materialization that in other respects bypasses the property setters. 
See https://github.com/aspnet/EntityFramework.Docs/issues/1007

**Closed** 2022-10-16 12:06 UTC
Labels: closed-could-not-reproduce
