### ISSUE TITLE
Duplicate key exception thrown for InMemory entity insert

### ISSUE THREAD

**Issue by kakins** [dotnet/efcore#10940] opened 2018-02-11 15:31 UTC
Whenever I add a new entity instance using the InMemory provider, the primary key is not automatically incremented and a duplicate key exception is thrown.  However after about 3-4 tries performing the same operation (and seeing the exception), the entity does get inserted and the key is correctly incremented.

```
Exception message:
Stack trace:
System.ArgumentException: An item with the same key has already been added. Key: 2
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.InMemoryTable`1.Create(IUpdateEntry entry)
   at Microsoft.EntityFrameworkCore.Storage.Internal.InMemoryStore.ExecuteTransaction(IEnumerable`1 entries, IDiagnosticsLogger`1 updateLogger)
   at Microsoft.EntityFrameworkCore.Storage.Internal.InMemoryDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
```

### Steps to reproduce
```c#
    // the entity
    public class CostingAllocation
    {
        [Key]
        // I've tried adding and removing this decorator
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CostingAllocationId { get; set; }
        public int PositionSourceFactKey { get; set; }

        [ForeignKey("PositionSourceFactKey")]
        public Position Position { get; set; }

        public List<CostingAllocationInterval> Intervals { get; set; }
    }


    // the aspnet core controller that saves the entity
    [Route("api/costingallocations")]
    public class CostingAllocationController : Controller
    {
        private readonly PrepBudgetContext _context;
        private readonly IMapper _mapper;

        public CostingAllocationController(PrepBudgetContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        [HttpPost]
        public async Task<IActionResult> Post([FromBody] int positionSourceFactKey)
        {
            var allocation = new CostingAllocation { PositionSourceFactKey = positionSourceFactKey };
            _context.CostingAllocations.Add(allocation);
            _context.SaveChanges();  // Exception thrown here
            return Ok(allocation.CostingAllocationId);
        }
    }


    // here is the test data that is inserted into the InMemory db on startup
    public static class DbInit
    {
        public static void Initialize(PrepBudgetContext context)
        {
            context.CostingAllocations.AddRange(CostingAllocations());         
            context.SaveChanges();
        }

        public static IEnumerable<CostingAllocation> CostingAllocations()
        {
            return new List<CostingAllocation>
            {
                new CostingAllocation
                {
                    CostingAllocationId = 1,
                    PositionSourceFactKey = 1,
                },
                new CostingAllocation
                {
                    CostingAllocationId = 2,
                    PositionSourceFactKey = 2
                }
            };
        }
    }
```

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 7
IDE: Visual Studio 2017 15.5.6

**Comment by smitpatel** [comment] 2018-02-11 19:05
@kakins - What is the value of `positionSourceFactKey` in Post method when the exception is thrown?

**Comment by smitpatel** [comment] 2018-02-11 19:07
Also share your `Position` class. The exception may be for FK `PositionSourceFactKey` rather than PK.

**Comment by kakins** [comment] 2018-02-11 20:47
@smitpatel Thanks for the reply! 

The value of ``positionSourceFactKey`` is **4**.

Here is the Position.cs:
```
    public class Position
    {
        [Key]
        public int PositionSourceFactKey { get; set; }
        public int JobProfileDimKey { get; set; }
        public int AdlocDimKey { get; set; }
        public int WorkerDimKey { get; set; }
        public string Pin { get; set; }
        public string Workstation { get; set; }
        
        public Worker Worker { get; set; }
        public Adloc Adloc { get; set; }
        public JobProfile JobProfile { get; set; }

        public List<CostingAllocation> CostingAllocations { get; set; }
    }
```

... and here is the test data for Positions
```
       public static IEnumerable<Position> Positions()
        {
            return new List<Position>
            {
                new Position
                {
                    PositionSourceFactKey = 1,
                    JobProfileDimKey = 1,
                    WorkerDimKey = 1,
                    Workstation = "S",
                    AdlocDimKey = 1,
                    Pin = "S1234",
                },
                new Position
                {
                    PositionSourceFactKey = 2,
                    JobProfileDimKey = 2,
                    WorkerDimKey = 2,
                    Workstation = "M",
                    AdlocDimKey = 2,
                    Pin = "M9999"
                },
                new Position
                {
                    PositionSourceFactKey = 3,
                    JobProfileDimKey = 3,
                    WorkerDimKey = 3,
                    Workstation = "A",
                    AdlocDimKey = 3,
                    Pin = "A5678"
                },
                new Position
                {
                    PositionSourceFactKey = 4,
                    JobProfileDimKey = 4,
                    WorkerDimKey = 4,
                    Workstation = "S",
                    AdlocDimKey = 4,
                    Pin = "S0000"
                }
            };
        }
```

**Comment by smitpatel** [comment] 2018-02-14 00:23
@kakins - I am not able to reproduce this.
Based on the exception message, you are trying to insert CostingAllocation with CostingAllocationId = 2 and such record already exist in database. Can you debug and verify the property values of CostingAllocation you are trying to insert?

If not, please share a runnable project which shows the issue you are hitting.

**Comment by kakins** [comment] 2018-02-15 01:34
@smitpatel Thanks for looking into it.  I'm not sure I'll be able to produce a runnable project -- but I still don't see why the framework is trying to add a CostingAllocationId of 2 when all I'm adding to the InMemory db is this:
`var allocation = new CostingAllocation { PositionSourceFactKey = positionSourceFactKey };`

You can see here that I'm expecting the framework to auto generate the primary key and increment it beyond what is already stored in the database.  Yet when it tries to do so, it seems like it is trying to increment using identifiers that already exist.

**Comment by smitpatel** [comment] 2018-02-15 02:11
@kakins - I believe I have figured this out.
In your initialization phase, you are adding CostingAllocation with Id= 1 & 2 manually. When you try to add new CostingAllocation in your controller with auto-generated value, EF Core does not know about the values which are already inserted in the database. So value generator collides with existing values in the database. Best way is to let EF insert values for all the records or not to use value generation.

**Comment by ajcvickers** [comment] 2018-02-17 01:01
Closing this as a duplicate of #6872 with a note there to consider this behavior when implemeting.

**Closed** 2022-10-16 12:09 UTC
