### ISSUE TITLE
Scaffolding of Sql Server DbContext does not handle properly nvarchar(4000) columns

### ISSUE THREAD

**Issue by SergeyBarskiy** [dotnet/efcore#9438] opened 2017-08-17 02:05 UTC
If I scaffold  Sql Server Database using 'dotnet ef dbcontext scaffold', it does not handle properly nvarchar(4000) columns.  They are generated as HasType("nvarchar") without length specification.  This cause exception during model validation phase.

### Further technical details
EF Core version: 2.0 RTM
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10
IDE: Visual Studio 2017.3

**Comment by smitpatel** [comment] 2017-08-17 06:12
duplicate of #9188

**Comment by ajcvickers** [comment] 2017-09-12 17:45
Hi @SergeyBarskiy. We are gathering information on the use of EF Core pre-release builds. You reported this issue shortly after the release of 2.0.0 RTM. It would be really helpful if you could let us know:

- Did you consider testing your code against the pre-release builds?
- Was there anything blocking you from using pre-release builds?
- What do you think could make it easier for you to use pre-release builds in the future?

Thanks in advance for any feedback. Hopefully this will help us to increase the value of pre-release builds going forward.

**Comment by SergeyBarskiy** [comment] 2017-09-16 12:47
@ajcvickers 
Hey, Arthur.
No, we have not tried against pre-release builds.  
No, nothing in particular when it comes to just testing
I do not think anything else needs to be done.

We primarily stopped the investigation because of the other issue I found - startup times on a large context (1000) tables was taking 2 minutes (https://github.com/aspnet/EntityFrameworkCore/issues/9347) , which is not really acceptable to our company at this point.

**Comment by ajcvickers** [comment] 2017-09-18 18:00
@SergeyBarskiy Thanks for the feedback; much appreciated.

**Closed** 2022-10-16 11:16 UTC
Labels: closed-duplicate
