### ISSUE TITLE
preview8 - 'dotnet ef migrations add / remove' error 'The model must be finalized before GetTypeMapping can be used'

### ISSUE THREAD

**Issue by LunicLynx** [dotnet/efcore#17174] opened 2019-08-15 10:42 UTC
Still an issue in preview8. Please reopen: #16737 #16857.

#16809 did not fix this.

Also happens with `Add-Migration`.

Downgrade to `preview6` works. See https://github.com/aspnet/EntityFrameworkCore/issues/16737#issuecomment-515479316

**Comment by ajcvickers** [comment] 2019-08-15 14:34
@LunicLynx See #17145. However:
* Please post a small, runnable project/solution or complete code listing that demonstrates the scenario where you see this with `Add-Migration`. This may be a different issue.
* Please do the same if you're still seeing this and the model does not use `HasData`

**Comment by ajcvickers** [comment] 2019-08-23 15:59
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:35 UTC
Labels: closed-duplicate, customer-reported
