### ISSUE TITLE
Translation for ICollection<T>.Contains lacks parameterization

### ISSUE THREAD

**Issue by GSPP** [dotnet/efcore#21381] opened 2020-06-23 07:40 UTC
`ICollection<T>.Contains` is translated to a SQL `IN` expression on SQL Server. That's great. But the values are burned into the SQL query which causes parameterization issues. It leads to plan cache pollution and an expensive query recompile for each query executed (if the parameters are different which they usually are).

Sample code:

                    var collection = new string[] { "Test 1", "Test 2" };
                    ctx.Customers.Where(c => collection.Contains(c.Name)).ToList();

Generated SQL:

```
exec sp_executesql N'SELECT COUNT(*)
FROM [Customers] AS [c]
WHERE [c].[Name] IN (N''Test 1'', N''Test 2'')'
```

I tested this on .NET Core 3.1, EF Core 5.0.0-preview.5.20278.2.

**Comment by smitpatel** [comment] 2020-06-23 07:42
Duplicate of #13617

**Comment by GSPP** [comment] 2020-06-23 09:14
Sorry for creating a duplicate. I did not find this using the search terms that I tried.

**Closed** 2022-10-16 18:30 UTC
Labels: closed-duplicate, customer-reported
