### ISSUE TITLE
Store all enums as string global configuration

### ISSUE THREAD

**Issue by matthiaslischka** [dotnet/efcore#25929] opened 2021-09-08 09:41 UTC
I want to configure all enums to be stored as `string` instead of `int` just to be more readable in the DB.

I came up with this code to configure that globally for all enums and am wondering if there is a better way to do that or another best practice.

Also noticed that the string is nvarchar(max) - not sure if I should even care about that, but since I'm already here...

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);
    SetEnumToStringValueConverter(modelBuilder);
}

private void SetEnumToStringValueConverter(ModelBuilder modelBuilder)
{
    foreach (var property in modelBuilder.Model.GetEntityTypes().SelectMany(t => t.GetProperties()))
    {
        var enumType = GetEnumType(property.ClrType);
        if (enumType == null)
            continue;

        var type = typeof(EnumToStringConverter<>).MakeGenericType(enumType);

        var converter = Activator.CreateInstance(type, new ConverterMappingHints()) as ValueConverter;
        property.SetValueConverter(converter);
    }
}

private Type? GetEnumType(Type type)
{
    if (type.IsEnum) return type;

    var nullableUnderlyingType = Nullable.GetUnderlyingType(type);
    if (nullableUnderlyingType?.IsEnum ?? false) return nullableUnderlyingType;

    return null;
}

```

I did not find anything about global configuration in the official documentation. Did I just not find it or is it not there on purpose?
My reason for configuring it globally is because I want behavior like that to be at least consistent throughout my application.

BR Matthias

**Comment by ajcvickers** [comment] 2021-09-08 09:48
Duplicate of #10784. See https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-6-0-preview-6-configure-conventions/

**Closed** 2022-10-16 20:07 UTC
Labels: closed-duplicate, customer-reported

**Comment by tscheler** [comment] 2023-09-08 12:30
Using EFCore 7.0.10 here, this works with MariaDb:

```csharp
 configurationBuilder.Properties<Enum>().HaveConversion<string>();
```

Any objections to this approach?

**Comment by roji** [comment] 2023-09-08 14:52
@tscheler that's indeed the recommended way to do this.

**Comment by jdev-pr** [comment] 2024-08-07 12:35
> @tscheler that's indeed the recommended way to do this.

What's the recommended way when the enum can be null? I've already tried `configurationBuilder.Properties<Enum?>().HaveConversion<string>();` but it throws an exception.
