### ISSUE TITLE
Error CS0120 when scaffolding with data annotations from database tables, nameof operator

### ISSUE THREAD

**Issue by dsthode** [dotnet/efcore#17880] opened 2019-09-17 10:30 UTC
I have scaffolded my database schema using data annotations and the code generated for certain entities gives the compilation error CS0120 when building, indicating an error with the arguments to the nameof operator in the InverseProperty attribute.

The following messages is given for each class:

>  Entities\decision_tree_node.cs(31,33): error CS0120: Se requiere una referencia de objeto para el campo, método o propiedad 'decision_tree.decision_tree_node' no estáticos

> Entities\decision_tree.cs(27,33): error CS0120: Se requiere una referencia de objeto para el campo, método o propiedad 'decision_tree_node.decision_tree' no estáticos

Instead, when the database is scaffolded without data annotations the code generated compiles without error.

### Steps to reproduce
The scaffold is generated with the following command:

`dotnet-ef dbcontext scaffold "server=...;database=...;user=...;password=..." microsoft.entityframeworkcore.sqlserver -c EntityMappingEF -o Entities --context-dir . -d --use-database-names`

These are the code listings generated from each table that give the error:

decision_tree_node.cs
```cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace dataaccessef.Entities
{
    public partial class decision_tree_node
    {
        public decision_tree_node()
        {
            Inverseparent_ = new HashSet<decision_tree_node>();
            decision_tree = new HashSet<decision_tree>();
            decision_tree_responses = new HashSet<decision_tree_responses>();
            decision_tree_transitionsfrom_ = new HashSet<decision_tree_transitions>();
            decision_tree_transitionsto_ = new HashSet<decision_tree_transitions>();
        }

        [Required]
        [Column(TypeName = "text")]
        public string text { get; set; }
        [Key]
        public int id { get; set; }
        public int? parent_id { get; set; }
        public int? next_tree_id { get; set; }
        public bool? is_phantom { get; set; }
        [StringLength(50)]
        public string name { get; set; }

        [ForeignKey(nameof(next_tree_id))]
        [InverseProperty(nameof(decision_tree.decision_tree_node))]
        public virtual decision_tree next_tree_ { get; set; }
        [ForeignKey(nameof(parent_id))]
        [InverseProperty(nameof(decision_tree_node.Inverseparent_))]
        public virtual decision_tree_node parent_ { get; set; }
        [InverseProperty(nameof(decision_tree_node.parent_))]
        public virtual ICollection<decision_tree_node> Inverseparent_ { get; set; }
        [InverseProperty("root_")]
        public virtual ICollection<decision_tree> decision_tree { get; set; }
        [InverseProperty("node_")]
        public virtual ICollection<decision_tree_responses> decision_tree_responses { get; set; }
        [InverseProperty(nameof(decision_tree_transitions.from_))]
        public virtual ICollection<decision_tree_transitions> decision_tree_transitionsfrom_ { get; set; }
        [InverseProperty(nameof(decision_tree_transitions.to_))]
        public virtual ICollection<decision_tree_transitions> decision_tree_transitionsto_ { get; set; }
    }
}

```
decision_tree.cs
```cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace dataaccessef.Entities
{
    public partial class decision_tree
    {
        public decision_tree()
        {
            decision_tree_node = new HashSet<decision_tree_node>();
        }

        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(100)]
        public string description { get; set; }
        [Key]
        public int id { get; set; }
        public int? root_id { get; set; }
        [StringLength(100)]
        public string global_var { get; set; }

        [ForeignKey(nameof(root_id))]
        [InverseProperty(nameof(decision_tree_node.decision_tree))]
        public virtual decision_tree_node root_ { get; set; }
        [InverseProperty("next_tree_")]
        public virtual ICollection<decision_tree_node> decision_tree_node { get; set; }
    }
}

```

### Further technical details

dotnet --info:
```
SDK de .NET Core (reflejando cualquier global.json):
 Version:   3.0.100-preview9-014004
 Commit:    8e7ef240a5

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview9-014004\

Host (useful for support):
  Version: 3.0.0-preview9-19423-09
  Commit:  2be172345a

.NET Core SDKs installed:
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

EF Core version: 3.0.0-preview9.19423.6
Database provider:Microsoft.EntityFrameworkCore.SqlServer
Target framework: netcoreapp3.0
Operating system: Windows 7

dotnet list package
```
El proyecto "dataaccessef" tiene las referencias de paquete siguientes
   [netcoreapp3.0]:
   Paquete de nivel superior                      Solicitado        Resuelto
   > Microsoft.EntityFrameworkCore                3.0.0-preview9*   3.0.0-preview9.19423.6
   > microsoft.entityframeworkcore.design         3.0.0-preview9*   3.0.0-preview9.19423.6
   > microsoft.entityframeworkcore.sqlserver      3.0.0-preview9*   3.0.0-preview9.19423.6
```

**Comment by dsthode** [comment] 2019-09-17 12:48
Ok, I've found the problem.

The scaffolding created a `public virtual` property with the same name as the inverse relation class, in both clases.

Line 30 in decision_tree.cs:
```cs
        public virtual ICollection<decision_tree_node> decision_tree_node { get; set; }
```

And line 39 in decision_tree_node.cs.
```cs
        public virtual ICollection<decision_tree> decision_tree1 { get; set; }
```
Shouldn't this have been taken into account in the scaffolding process?

**Comment by bricelam** [comment] 2019-09-17 16:55
Duplicate of #17847

**Closed** 2022-10-16 14:42 UTC
Labels: customer-reported
