### ISSUE TITLE
Bug: dotnet-ef --output-dir ignored for ApplicationDbContextModelSnapshot and placing in default folder

### ISSUE THREAD

**Issue by lastlink** [dotnet/efcore#27631] opened 2022-03-13 00:20 UTC
## File a bug
`dotnet-ef --output-dir ignored for ApplicationDbContextModelSnapshot and placing in default folder`

### Include your code

* install tool
`dotnet tool install --global dotnet-ef` installed latest 6.0.x`
* add new migration
`dotnet ef migrations add InitialMigrations --context PostgressDataContext --project ..\App.Repository\App.Repository.csproj --output-dir Migrations/Postgress --startup-project .\App.Api.csproj`

#### Details
* rather than creating/updating `App.Repository\Migrations\Postgress\ApplicationDbContextModelSnapshot.cs`
  * instead the base `App.Repository\Migrations\ApplicationDbContextModelSnapshot.cs` gets updated. This behaved correctly in .net3.1
  * e.g.  App.Repository\ **Migrations\Postgress** \ApplicationDbContextModelSnapshot.cs, should be App.Repository\ **Migrations** \ApplicationDbContextModelSnapshot.cs

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET 5.0
Operating system:
IDE: Visual Studio 2022

part of csproj
```xml
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.15">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="5.0.14" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.14" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="5.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.10" />
```

**Comment by ajcvickers** [comment] 2022-03-15 10:38
@lastlink Have you tried this with EF Core 6.0.3?

**Comment by ajcvickers** [comment] 2022-03-25 10:39
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:28 UTC
Labels: closed-could-not-reproduce, customer-reported
