### ISSUE TITLE
FirstOrDefault breaks Include queries with collections of child items

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/efcore#12015] opened 2018-05-15 20:04 UTC
The LINQ operation `FirstOrDefault(criteria)` is supposed to be semantically identical to `Where(criteria).FirstOrDefault()`.  But here's a scenario in which it isn't:

In the database, create a parent table and a child table, which are linked by a one-to-many FK relationship, where the parent table has a PK called `ID`.  Populate the tables with data.  Generate model classes from the database.

In C#, run the following query:

```
var id = 3; //arbitrary number
var result = Context.ParentTable.Include(t => t.Children).FirstOrDefault(t => t.ID == id);
```

Assuming a matching parent exists in the database, it will be returned, with its Children collection incorrectly containing only one result, instead of the full set of associated children.

However, if you say:

```
var id = 3; //arbitrary number
var result = Context.ParentTable.Include(t => t.Children).Where(t => t.ID == id).FirstOrDefault();
```

you get the correct result, with `Children` fully populated.

### Further technical details
EF Core version: Microsoft.EntityFrameworkCore (2.1.0-preview2-final)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer (2.1.0-preview2-final)
Operating system: Windows 10
IDE: Visual Studio Professional 2017 15.6.7

**Comment by ajcvickers** [comment] 2018-05-15 20:08
@masonwheeler Do you know if this was also the behavior in the 2.0 releases of EF Core?

**Comment by masonwheeler** [comment] 2018-05-15 20:10
@ajcvickers No idea; all I have to go by is that this is broken at work, where we're using 2.1.0-preview2-final.

**Comment by smitpatel** [comment] 2018-05-15 20:18
I am not able to reproduce this in 2.1.0-preview2-final release. Relinq converts first kind of query to second kind automatically for us. We don't see the first one ever in our compiler.
The code I used
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database
                db.Add(new Blog
                {
                    Posts = new List<Post>
                    {
                        new Post(),
                        new Post(),
                        new Post(),
                        new Post()
                    }
                });

                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                var id = 1;
                var query = db.Blogs.Include(b => b.Posts).FirstOrDefault(b => b.Id == id);
                Console.WriteLine(query.Posts.Count);
            }

            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        private static ILoggerFactory LoggerFactory => new LoggerFactory().AddConsole(LogLevel.Trace);

        // Declare DBSets
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                //.UseSqlite("filename=_modelApp.db")
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(LoggerFactory);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
        }
    }

    public class Blog
    {
        public int Id { get; set; }
        public List<Post> Posts { get; set; }
    }

    public class Post
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
        public Blog Blog { get; set; }
    }
}
```

**Comment by masonwheeler** [comment] 2018-05-15 20:38
Well that's very frustrating...

**Comment by ajcvickers** [comment] 2018-05-23 18:35
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:24 UTC
Labels: closed-could-not-reproduce, customer-reported
