### ISSUE TITLE
EnableSensitiveDataLogging and using record type as ComplexProperty issue

### ISSUE THREAD

**Issue by parvic1** [dotnet/efcore#32486] opened 2023-12-01 17:03 UTC
SaveChangesAsync crashes when EnableSensitiveDataLogging is used

### Include your code
public sealed class Customer
{
    public int Id { get; set; }
    public required string Name { get; set; }
    public required Address HomeAddress { get; set; }
}

public record Address(string Line1, string? Line2, string City, string Country, string ZipCode);

public sealed class AppDbContext: DbContext
{
    public DbSet<Customer> Customers => Set<Customer>();
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<Customer>()
            .ToTable("Customers")
            .ComplexProperty(e => e.HomeAddress);
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        //optionsBuilder.LogTo(Console.WriteLine).EnableDetailedErrors();
        optionsBuilder.LogTo(Console.WriteLine).EnableSensitiveDataLogging().EnableDetailedErrors();
        optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=ConsoleAppDb;Integrated Security=True");
    }
}

internal class Program
{
    static async Task Main(string[] args)
    {
        using var db = new AppDbContext();

        //db.Database.EnsureCreated();

        //var nc = new Customer()
        //{
        //    Name = "Vic 2",
        //    HomeAddress = new Address("Manuel 2541", null, "Monterrey", "Mexico", "64800")
        //};

        //await db.Set<Customer>().AddAsync(nc);
        //await db.SaveChangesAsync();

//        db.ChangeTracker.Clear();
        var nc = await db.Customers.Where(p=>p.Id == 2).FirstOrDefaultAsync();

        if (nc != null )
        {
          nc.HomeAddress = nc.HomeAddress with { Line2 = "Unidad 21" };
        }
        await db.SaveChangesAsync();
        Console.ReadKey();
    }
}

### Include stack traces

System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'Microsoft.EntityFrameworkCore.Metadata.RuntimeComplexType' to type 'Microsoft.EntityFrameworkCore.Metadata.IEntityType'.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Diagnostics.CoreLoggerExtensions.PropertyChangeDetectedSensitive(EventDefinitionBase definition, EventData payload)
   at Microsoft.EntityFrameworkCore.Diagnostics.EventData.ToString()
   at Microsoft.EntityFrameworkCore.Diagnostics.Internal.FormattingDbContextLogger.Log(EventData eventData)
   at Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger.DispatchEventData(EventDefinitionBase definition, EventData eventData, Boolean diagnosticSourceEnabled, Boolean simpleLogEnabled)
   at Microsoft.EntityFrameworkCore.Diagnostics.CoreLoggerExtensions.PropertyChangeDetectedSensitive(IDiagnosticsLogger`1 diagnostics, InternalEntityEntry internalEntityEntry, IProperty property, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.LogChangeDetected(InternalEntityEntry entry, IProperty property, Object original, Object current)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectValueChange(InternalEntityEntry entry, IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.LocalDetectChanges(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges()
   at Microsoft.EntityFrameworkCore.DbContext.TryDetectChanges()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__63.MoveNext()

### Include provider and version information

EF Core version: 8
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: WIndows 10
IDE: Visual Studio 2022 17.8.2

**Comment by ajcvickers** [comment] 2023-12-01 17:11
Duplicate of #32198

**Closed** 2023-12-01 17:12 UTC
Labels: customer-reported
