### ISSUE TITLE
Slow DB performance with SQLite DB using EF Core in UWP app

### ISSUE THREAD

**Issue by leesmith1985** [dotnet/efcore#15328] opened 2019-04-11 13:54 UTC
Repost of my previous question on SO:
[Optimize connection to SQLite DB using EF Core in UWP app](https://stackoverflow.com/questions/55530955/optimize-connection-to-sqlite-db-using-ef-core-in-uwp-app)

I'm currently working on a C# UWP application that runs on Windows 10 IoT Core OS on an ARM processor. For this application, I am using a SQLite DB for my persistence, with Entity Framework Core as my ORM.

I have created my own DBContext and call the Migrate function on startup which creates my DB. I can also successfully create a DBContext instance in my main logic which can successfully read/write data using the model. All good so far.

However, I've noticed that the performance of creating a DbContext for each interaction with the DB is painfully slow. Although I can guarantee that only my application is accessing the database (I'm running on custom hardware with a controlled software environment), I do have multiple threads in my application that need to access the database via the DbContext. 

I need to find a way to optimize the connection to my SQLite DB in a way that is thread safe in my application. As I mentioned before, I don't have to worry about any external applications.

At first, I tried to create a SqliteConnection object externally and then pass it in to each DbContext that I create:
`_connection = new SqliteConnection(@"Data Source=main.db");`

... and then make that available to my DbContext and use in in the OnConfiguring override:

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder.UseSqlite(_connection);
}
```
... and then use the DbContext in my application like this:
```
using (var db = new MyDbContext())
{
    var data = new MyData { Timestamp = DateTime.UtcNow, Data = "123" };
    db.MyData.Add(data);
    db.SaveChanges();
}
```
```
// Example data read
MyDataListView.ItemsSource = db.MyData.ToList();
```

Taking the above approach, I noticed that the connection is closed down automatically when the DbContext is disposed, regardless of the fact that the connection was created externally. So this ends up throwing an exception the second time I create a DbContext with the connection.

Secondly, I tried to create a single DbContext once statically and share it across my entire application. So instead of creating the DbContext in a using statement as above, I tried the following:
```
// Where Context property returns a singleton instance of MyDbContext
var db = MyDbContextFactory.Context;
var data = new MyData { Timestamp = DateTime.UtcNow, Data = "123" };
db.MyData.Add(data);
db.SaveChanges();
```

This offers me the performance improvements I hoped for but I quickly realized that this is not thread safe and wider reading has confirmed that I shouldn't do this.

So does anyone have any advice on how to improve the performance when accessing SQLite DB in my case with EF Core and a multi-threaded UWP application? Many thanks in advance.

**Comment by ajcvickers** [comment] 2019-04-11 15:12
@leesmith1985 Are you seeing this performance issue only in release builds (that use .NET Native) or also in debug builds that don't use native compilation?

**Comment by ajcvickers** [comment] 2019-04-19 16:15
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:17 UTC
Labels: closed-could-not-reproduce, customer-reported
