### ISSUE TITLE
EF Core adding a migration exception using DDD and value objects

### ISSUE THREAD

**Issue by rizkengin** [dotnet/efcore#30639] opened 2023-04-05 21:07 UTC
I'm facing a very annoying issue with my application whenever I try to add a new migration using ef core I get a System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

I tried everything I can think of but nothing seems to solve this issue, I have a user aggregate and a discipline aggregate I need to map to the database using fluent api, What I'm trying to do is make the user own many discplineIds and the discipline own many userIds 

This is the User Aggregate class

```
public sealed class User : AggregateRoot<UserId>
{
    private readonly List<UserRefreshToken> _refreshTokens = new();
    private readonly List<UserCheckLog> _checkLogs = new();
    private readonly List<UserNotification> _notifications = new();
    private readonly List<ProjectLogId> _projectLogsIds = new();
    private readonly List<DisciplineId> _disciplineIds = new();


    private User(
        UserId userId,
        string firstName,
        string lastName,
        string email,
        string password,
        Role role,
        CurrentState currentState,
        int overTimeCount,
        double weeklyWorkedHours,
        bool isLocked,
        List<string> lockoutReasons,
        Uri? profilePictureUrl,
        List<string> fcmTokens,
        DateTime createdAt,
        DateTime updatedAt)
        : base(userId)
    {
        FirstName = firstName;
        LastName = lastName;
        Email = email;
        Password = password;
        Role = role;
        CurrentState = currentState;
        OverTimeCount = overTimeCount;
        WeeklyWorkedHours = weeklyWorkedHours;
        IsLocked = isLocked;
        LockoutReasons = lockoutReasons;
        ProfilePictureUrl = profilePictureUrl;
        FcmTokens = fcmTokens;
    }

    public static User Create(
        string firstName,
        string lastName,
        string email,
        string password,
        int overTimeCount,
        Uri? profilePictureUrl = null) => new(UserId.CreateUnique(), firstName, lastName, email, password, Role.User, CurrentState.LoggedOut, overTimeCount, 0, true, new(), profilePictureUrl, new(), DateTime.UtcNow, DateTime.UtcNow);

    public string FirstName { get; private set; }
    public string LastName { get; private set; }
    public string Email { get; private set; }
    public string Password { get; private set; }
    public Role Role { get; private set; }
    public CurrentState CurrentState { get; private set; }
    public int OverTimeCount { get; private set; }
    public double WeeklyWorkedHours { get; private set; }
    public bool IsLocked { get; private set; }
    public List<string> LockoutReasons { get; private set; }
    public Uri? ProfilePictureUrl { get; private set; }
    public List<string> FcmTokens { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public DateTime UpdatedAt { get; private set; }


    public IReadOnlyList<UserRefreshToken> RefreshTokens => _refreshTokens.AsReadOnly();
    public IReadOnlyList<UserCheckLog> CheckLogs => _checkLogs.AsReadOnly();
    public IReadOnlyList<UserNotification> Notifications => _notifications.AsReadOnly();
    public IReadOnlyList<ProjectLogId> ProjectLogsIds => _projectLogsIds.AsReadOnly();
    public IReadOnlyList<DisciplineId> DisciplineIds => _disciplineIds.AsReadOnly();



    #pragma warning disable CS8618 
    private User()
    {

    }
    #pragma warning restore CS8618
}
```

and this is the Discipline Aggregate class

```
public sealed class Discipline : AggregateRoot<DisciplineId>
{
    private readonly List<UserId> _usersIds = new();

    private Discipline(
        DisciplineId disciplineId,
        string name)
        : base(disciplineId)
    {
        Name = name;
    }
    public string Name { get; private set; }
    public IReadOnlyList<UserId> UsersIds => _usersIds.AsReadOnly();


    #pragma warning disable CS8618 
    private Discipline()
    {

    }
    #pragma warning restore CS8618
}
```

I'm using strongly typed Ids for both 

```
public sealed class UserId : ValueObject
{
    public Guid Value { get; private set; }

    private UserId(Guid value)
    {
        Value = value;
    }

    public static UserId Create(Guid value) => new UserId(value);
    public static UserId CreateUnique() => new UserId(Guid.NewGuid());

    protected override IEnumerable<object> GetEqualityComponents()
    {
        yield return Value;
    }
}
```

```
public sealed class DisciplineId : ValueObject
{
    public Guid Value { get; private set; }

    private DisciplineId(Guid value)
    {
        Value = value;
    }

    public static DisciplineId Create(Guid value) => new(value);
    public static DisciplineId CreateUnique() => new(Guid.NewGuid());

    protected override IEnumerable<object> GetEqualityComponents()
    {
        yield return Value;
    }
}
```

and this is the fluent api config for both

```
public class UserConfigurations : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        ConfigureUserTable(builder);
        ConfigureUserRefreshTokensTable(builder);
        ConfigureUserCheckLogsTable(builder);
        ConfigureUserNotificationsTable(builder);
        ConfigureUserProjectLogsIdsTable(builder);
        configureUserDisciplineIdsTable(builder);
    }

    private void configureUserDisciplineIdsTable(EntityTypeBuilder<User> builder)
    {
        builder.OwnsMany(u => u.DisciplineIds, dib =>
        {
            dib.ToTable("UserDisciplineIds");

            dib.WithOwner().HasForeignKey("UserId");

            dib.HasKey("Id");

            dib.Property(di => di.Value)
                .HasColumnName("DisciplineId")
                .ValueGeneratedNever();
        });

        

        builder.Metadata.FindNavigation(nameof(User.DisciplineIds))!.SetPropertyAccessMode(PropertyAccessMode.Field);
    }

    private void ConfigureUserProjectLogsIdsTable(EntityTypeBuilder<User> builder)
    {
        builder.OwnsMany(u => u.ProjectLogsIds, plb =>
        {
            plb.ToTable("UserProjectLogsIds");

            plb.WithOwner().HasForeignKey("UserId");

            plb.HasKey("Id");

            plb.Property(pl => pl.Value)
                .HasColumnName("ProjectLogId")
                .ValueGeneratedNever();
        });

        builder.Metadata.FindNavigation(nameof(User.ProjectLogsIds))!.SetPropertyAccessMode(PropertyAccessMode.Field);
    }

    private void ConfigureUserNotificationsTable(EntityTypeBuilder<User> builder)
    {
        builder.OwnsMany(u => u.Notifications, nb =>
        {
            nb.ToTable("Notifications");

            nb.WithOwner().HasForeignKey("UserId");

            nb.HasKey("Id", "UserId");

            nb.Property(n => n.Id)
                .HasColumnName("UserNotificationId")
                .ValueGeneratedNever()
                .HasConversion(
                    id => id.Value,
                    value => UserNotificationId.Create(value));

            nb.OwnsOne(n => n.Sender, sb =>{
                sb.Property(s => s.Name)
                .HasColumnName("SenderName");

                sb.Property(s => s.UserId)
                    .HasColumnName("SenderUserId")
                    .HasConversion(
                        id => id.Value,
                        value => UserId.Create(value));
            });
        });

        builder.Metadata.FindNavigation(nameof(User.Notifications))!.SetPropertyAccessMode(PropertyAccessMode.Field);
    }

    private void ConfigureUserCheckLogsTable(EntityTypeBuilder<User> builder)
    {
        builder.OwnsMany(u => u.CheckLogs, clb =>
        {
            clb.ToTable("CheckLogs");

            clb.WithOwner().HasForeignKey("UserId");

            clb.HasKey("Id", "UserId");

            clb.Property(cl => cl.Id)
                .HasColumnName("UserCheckLogId")
                .ValueGeneratedNever()
                .HasConversion(
                    id => id.Value,
                    value => UserCheckLogId.Create(value));
        });

        builder.Metadata.FindNavigation(nameof(User.CheckLogs))!.SetPropertyAccessMode(PropertyAccessMode.Field);
    }

    private void ConfigureUserRefreshTokensTable(EntityTypeBuilder<User> builder)
    {
        builder.OwnsMany(u => u.RefreshTokens, rtb =>
        {
            rtb.ToTable("RefreshTokens");

            rtb.WithOwner().HasForeignKey("UserId");

            rtb.HasKey("Id", "UserId");

            rtb.Property(rt => rt.Id)
                .HasColumnName("UserRefreshTokenId")
                .ValueGeneratedNever()
                .HasConversion(
                    id => id.Value,
                    value => UserRefreshTokenId.Create(value));
        });

        builder.Metadata.FindNavigation(nameof(User.RefreshTokens))!.SetPropertyAccessMode(PropertyAccessMode.Field);
    }

    private void ConfigureUserTable(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("Users");

        builder.HasKey(u => u.Id);

        builder.Property(u => u.Id)
            .ValueGeneratedNever()
            .HasConversion(
                id => id.Value,
                value => UserId.Create(value));

        builder.Property(u => u.FirstName)
            .HasMaxLength(50)
            .IsRequired();

        builder.Property(u => u.LastName)
            .HasMaxLength(50)
            .IsRequired();

        builder.Property(u => u.Email)
            .HasMaxLength(100)
            .IsRequired();
    }
}
```

```
public class DisciplineConfigurations : IEntityTypeConfiguration<Discipline>
{
    public void Configure(EntityTypeBuilder<Discipline> builder)
    {
        ConfigureDisciplineTable(builder);
        ConfigureDisciplineUserIdsTable(builder);
    }

    private void ConfigureDisciplineUserIdsTable(EntityTypeBuilder<Discipline> builder)
    {
        builder.OwnsMany(u => u.UsersIds, dib =>
        {
            dib.ToTable("DisciplineUsersIds");

            dib.WithOwner().HasForeignKey("DisciplineId");

            dib.HasKey("Id");

            dib.Property(di => di.Value)
                .HasColumnName("UserId")
                .ValueGeneratedNever();
        });

        builder.Metadata.FindNavigation(nameof(Discipline.UsersIds))!.SetPropertyAccessMode(PropertyAccessMode.Field);
    }

    private void ConfigureDisciplineTable(EntityTypeBuilder<Discipline> builder)
    {
        builder.ToTable("Disciplines");

        builder.HasKey(x => x.Id);

        builder.Property(p => p.Id)
                .ValueGeneratedNever()
                .HasConversion(
                    id => id.Value,
                    value => DisciplineId.Create(value));
    }
}
```

when i try to add a migration this always throws the following exception

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionBatchExtensions.Run(IConventionBatch batch, InternalForeignKeyBuilder relationshipBuilder)
>    at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder.ReuniquifyImplicitProperties(Boolean force)
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.ForeignKeyPropertyDiscoveryConvention.DiscoverProperties(IConventionForeignKeyBuilder relationshipBuilder, IConventionContext context)
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.ForeignKeyPropertyDiscoveryConvention.ProcessForeignKeyRequirednessChanged(IConventionForeignKeyBuilder relationshipBuilder, IConventionContext`1 context)
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnForeignKeyRequirednessChanged(IConventionForeignKeyBuilder relationshipBuilder)
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnForeignKeyRequirednessChangedNode.Run(ConventionDispatcher dispatcher)
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.DelayedConventionScope.Run(ConventionDispatcher dispatcher)
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run(IConventionForeignKey foreignKey)
>    at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.OwnsManyBuilder[TRelatedEntity](TypeIdentity ownedType, MemberIdentity navigation)
>    at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.OwnsMany[TRelatedEntity](Expression`1 navigationExpression, Action`1 buildAction)
>    at TimeTracker.Infrastructure.Persistence.Configurations.UserConfigurations.ConfigureUserRefreshTokensTable(EntityTypeBuilder`1 builder) in C:\Users\rizk_\source\repos\TimeTracker\TimeTracker.Infrastructure\Persistence\Configurations\UserConfigurations.cs:line 115
>    at TimeTracker.Infrastructure.Persistence.Configurations.UserConfigurations.Configure(EntityTypeBuilder`1 builder) in C:\Users\rizk_\source\repos\TimeTracker\TimeTracker.Infrastructure\Persistence\Configurations\UserConfigurations.cs:line 15
>    at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration[TEntity](IEntityTypeConfiguration`1 configuration)
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    --- End of inner exception stack trace ---
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
>    at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfigurationsFromAssembly(Assembly assembly, Func`2 predicate)
>    at TimeTracker.Infrastructure.Persistence.TimeTrackerDbContext.OnModelCreating(ModelBuilder modelBuilder) in C:\Users\rizk_\source\repos\TimeTracker\TimeTracker.Infrastructure\Persistence\TimeTrackerDbContext.cs:line 23
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
>    at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>    at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
>    at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
>    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
>    at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
>    at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
>    at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
>    at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
> Exception has been thrown by the target of an invocation.

in the exception it shows that there is a problem in line 115 which is the following method in the above config

```
builder.OwnsMany(u => u.RefreshTokens, rtb =>
        {
            rtb.ToTable("RefreshTokens");

            rtb.WithOwner().HasForeignKey("UserId");

            rtb.HasKey("Id", "UserId");

            rtb.Property(rt => rt.Id)
                .HasColumnName("UserRefreshTokenId")
                .ValueGeneratedNever()
                .HasConversion(
                    id => id.Value,
                    value => UserRefreshTokenId.Create(value));
        });
```

but after alot of debugging I noticed the following, when I delete the discipline config and try to add a migration with only the user config the migration gets generated sucessfully without problems, and when I delete the user config and only run the discipline the config the migration gets genereated sucessfully, so I tried to remove the list of userIds in the discipline aggregate and the migration was added sucessfully. 

Is this a bug or am I doing something wrong here?

**Comment by ajcvickers** [comment] 2023-04-07 15:48
Duplicate of #30373.

**Closed** 2023-04-11 11:00 UTC
Labels: customer-reported
