### ISSUE TITLE
Feature Request: Add OrWhere to Entity Framework

### ISSUE THREAD

**Issue by minhsonuit** [dotnet/efcore#16294] opened 2019-06-27 10:35 UTC
Sometime we want to build dynamics query with or condidtion
sample:
foreach(var range in status)
{
query = query.OrWhere(p=>p.Status1 == range.Status1 && p.status2 == range.status2);
}

**Comment by smitpatel** [comment] 2019-06-27 15:37
Duplicate of #13915

**Closed** 2022-10-16 14:28 UTC
Labels: closed-duplicate, customer-reported
