### ISSUE TITLE
{"Could not load type 'System.Diagnostics.CodeAnalysis.MaybeNullAttribute' from assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.":"System.Diagnostics.CodeAnalysis.MaybeNullAttribute"}

### ISSUE THREAD

**Issue by sunildixit** [dotnet/efcore#18005] opened 2019-09-23 23:00 UTC
After getting today's release of .net core 3.0. 
I have upgraded to EF core 3.0 library and we have started seeing this error

```
System.TypeLoadException: Could not load type 'System.Diagnostics.CodeAnalysis.MaybeNullAttribute' from assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.NonNullableConventionBase.IsNonNullableReferenceType(IConventionModelBuilder modelBuilder, MemberInfo memberInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.NonNullableReferencePropertyConvention.Process(IConventionPropertyBuilder propertyBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.NonNullableReferencePropertyConvention.ProcessPropertyAdded(IConventionPropertyBuilder propertyBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnPropertyAdded(IConventionPropertyBuilder propertyBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor.VisitOnPropertyAdded(OnPropertyAddedNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnPropertyAddedNode.Accept(ConventionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(ConventionNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Dispose()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelInitialized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelInitialized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model..ctor(ConventionSet conventions)
   at Microsoft.EntityFrameworkCore.ModelBuilder..ctor(ConventionSet conventions)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Microsoft.Education.AristoServices.ConnectorApp.Connectors.StateManagement.DbWorkflowExecutionStateManager.GetExecutionDetails(String executionId) in D:\code\AristoServices\src\ConnectorApp\Connectors\StateManagement\DbWorkflowExecutionStateManager.cs:line 35
   at Microsoft.Education.AristoServices.ConnectorApp.Connectors.StateManagement.DbWorkflowExecutionStateManager.UpdateExecutionStatusAsync(String executionId, WorkflowExecutionStatus executionStatus) in D:\code\AristoServices\src\ConnectorApp\Connectors\StateManagement\DbWorkflowExecutionStateManager.cs:line 92
   at Microsoft.Education.AristoServices.ConnectorApp.Web.Services.ConnectorWorkerQueueClient.SendMessageAsync(ConnectorWorkerMessage message) in D:\code\AristoServices\src\ConnectorApp\ConnectorApp.Web\Services\ConnectorWorkerQueueClient.cs:line 65
   at Microsoft.Education.AristoServices.ConnectorApp.Web.Services.ConnectorWorkerQueueClient.QueueWorkAsync[TRequestParameters](ConnectorWorkRequest`1 workRequest, String connectorType) in D:\code\AristoServices\src\ConnectorApp\ConnectorApp.Web\Services\ConnectorWorkerQueueClient.cs:line 46
   at Microsoft.Education.AristoServices.ConnectorApp.Web.Controllers.RequestController`1.QueueWork(ConnectorWorkRequest`1 payload) in D:\code\AristoServices\src\ConnectorApp\ConnectorApp.Web\Controllers\RequestController.cs:line 50
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by smitpatel** [comment] 2019-09-23 23:02
@sunildixit - This error occurred when using preview SDK of .NET Core. Can you make sure that you have uninstalled all 3.0 preview SDKs and install 3.0 RTM SDK released today?

**Comment by sunildixit** [comment] 2019-09-23 23:13
You are actually right. I just thought, that when the VS got upgraded it would've have removed the preview, which it didn't. After uninstalling it, it has started working. Thank you for your help.

**Comment by mduchev** [comment] 2019-09-25 08:49
Actually, I am using the latest stable version - 3.0.100. I haven't pre-installed any of the preview versions, and I am still getting this exception in my Xamarin projects.

**Comment by mduchev** [comment] 2019-09-26 07:00
@smitpatel

**Comment by smitpatel** [comment] 2019-09-26 07:03
@mduchev - Can you share a repro project? It may have something to do with being a Xamarin project. If we get a repro, we can isolate where is the issue and pass on to appropriate team.

**Comment by R00iBaard** [comment] 2019-09-26 11:02
Why is this issue closed? Im also getting this error after upgrading from preview 7 to public release - 3.0.100

**Comment by R00iBaard** [comment] 2019-09-26 12:59
Hey all, I resolved mine the following way :

- Make sure all .net core runtimes and SDKs are uninstalled. Run dotnet --info to see. If installing 3.0.100 didnt remove the previews, go to those dirs and manually remove them. Re install (modify) the net core 3.0.100 installation to be safe again.

- Make sure you have installed VS 2019 16.3.1

Error should disappear.

**Comment by mduchev** [comment] 2019-09-27 08:06
@smitpatel  I will try to find the time to create a repro.

@R00iBaard I have never installed any preview versions, nor do I have anything else than 3.0.100 on my device. You can see my device --info in my previous comment. This is not a solution, obviously. There is still an issue!

**Comment by cagianx** [comment] 2019-09-27 09:56
@mduchev same situation here. I notice that Visual Studio 16.3.1 is shipped with an "embedded" version of net core 3, which differ  from a standalone installation of netcore 3 sdk.
![image](https://user-images.githubusercontent.com/1827900/65760642-ab8daa00-e11d-11e9-8aea-e5b1161d5d63.png)

**Comment by cagianx** [comment] 2019-09-27 10:20
I solved by downgrading to efcore 2.6, I think there are some issue with netstandard 2.1 https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-8-and-entity-framework-6-3-preview-8/

The project is based on xamarin and it runs on net standard 2.1

**Comment by mduchev** [comment] 2019-09-27 10:38
@smitpatel Here you are a sample project.
[TestEFC3XamarinApp.zip](https://github.com/aspnet/EntityFrameworkCore/files/3662272/TestEFC3XamarinApp.zip)

Steps to reproduce:
1) Run the app
2) Click on the button.
3) When the button is clicked, we are creating a new entity of type Address.
4) After the entity is created, we are adding it to Addresses DbSet (here is where the issue occurs)
5) Before we are able to call SaveChangesAsync, the app crashes with the same exception:

_System.TypeLoadException
  Message=Could not resolve type with token 01000143 from typeref (expected class 'System.Diagnostics.CodeAnalysis.MaybeNullAttribute' in assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')_

NOTE: This is tested on Android project only. The iOS project has other issues - it can't be run on simulator, nor on a real device. There I am getting these errors:
[ios_simulator_errors.txt](https://github.com/aspnet/EntityFrameworkCore/files/3662313/ios_simulator_errors.txt)
[ios_device_errors.txt](https://github.com/aspnet/EntityFrameworkCore/files/3662320/ios_device_errors.txt)

I don't know if I there are reported already, or should I open new issues.

**Comment by mduchev** [comment] 2019-09-27 11:04
> I solved by downgrading to efcore 2.6, I think there are some issue with netstandard 2.1 https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-8-and-entity-framework-6-3-preview-8/
> 
> The project is based on xamarin and it runs on net standard 2.1

@cagianx Yes, the configuration works with no issues running EFCore 2.2.6. Either there are some issues for EFCore 3.0, or there is new configuration that we need to apply.

**Comment by smitpatel** [comment] 2019-09-28 01:01
@mduchev - Thanks for the code. I will investigate.

**Comment by groege** [comment] 2019-10-01 07:42
Same thing with Xamarin.Android.
Is the netstandard.ddl, when using Android from the net core sdk or is it supplied by Xamarin.Android?
If it is the latter, I think we just need a later netstandard.dll for Xamarin.Android (to make Android work)
I need some fixes of the 3.0.0 version so downgrading is not an option for me :(

**Comment by smitpatel** [comment] 2019-10-01 21:08
@mduchev @groege 
After going through all the comments, I am not able to test out things as my dev environment is not setup for Xamarin project. I fairly believe that this is issue with netstandard2.1 and Xamarin projects. Hence I would recommend you guys to file an issue on their repo https://github.com/xamarin/xamarin-android/issues

They would be best to help you out.

@cagianx - Regarding multiple different SDK installed for 3.0, please file an issue at https://github.com/dotnet/core-sdk/issues 

Closing this as external. EF is using netstandard2.1 API. Issues like this are likely caused by SDK or project type is not supported properly on netstandard2.1 RTM.

**Comment by AndriySvyryd** [comment] 2019-10-01 21:17
You need to target at least Xamarin.Android __10.0__ or Xamarin.Mac __5.16__ to use netstandard2.1 and EF Core 3.0.0
https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by shaks786** [comment] 2019-10-01 22:44
@AndriySvyryd  I'm targetting those versions and still getting the error

**Comment by groege** [comment] 2019-10-01 22:46
Sadly I've been using the latest versions of Visual Studio (prerelease and non prerelease)
Latest Version of VS2019 is using Xamarin.Android 10.0 and the latest prerelease is using 10.1...
Both have the same issue, I think we'll need another Xamarin.Android version with a proper dll...

**Comment by AndriySvyryd** [comment] 2019-10-01 22:53
@shaks786 @groege Check that the .csproj is actually targeting 10 as the minimum version, if so please open an issue containing a small repro project on https://github.com/xamarin/xamarin-android/issues and link here.

**Comment by groege** [comment] 2019-10-02 07:51
@AndriySvyryd Are you saying NetStandard 2.1 is only compatible with Android Q?
So not even Android Pie works? That would be disastrous...

**Comment by mduchev** [comment] 2019-10-02 08:36
@AndriySvyryd 
You are mixing Xamarin.Android SDK with the Target Android SDK. You can have Xamarin.Android 10 and still target 9 or lower. And still, the issue occurs even with Xamarin.Android 10 and targeting Android Q. 

@smitpatel 
I will report the Android and iOS issues on the corresponding projects.

**Comment by mduchev** [comment] 2019-10-02 19:18
xamarin/xamarin-macios#7153

**Closed** 2022-10-16 14:43 UTC
Labels: closed-external, customer-reported
