### ISSUE TITLE
Unable to have EnableDetailedErrors working by instanciate manually DbContext

### ISSUE THREAD

**Issue by julienGrd** [dotnet/efcore#21209] opened 2020-06-10 14:19 UTC
Hello guys, for one of my project i reuse existing code executed initially in .net framework 4 / entity framework 5 to make it work in .net core 5 /en entity framework core 5 
The existing code don't use dependency injection but instanciate the dbContext (ObjectContext) manually.
````
using (DGenEntities lContainer = new DGenEntities(connectionstring))
            {
                if(lContainer.Users.Any(lUsr => lUsr.GrpID == pGrpID))
````
with my DbContext configuring like this in the partial
````
public partial class DGenEntities
    {
        string _connectionString;
        public DGenEntities(string connectionString)
        {
            _connectionString = connectionString;
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(_connectionString);
            optionsBuilder.EnableDetailedErrors();
            //optionsBuilder.EnableSensitiveDataLogging();
            //optionsBuilder.ConfigureWarnings(c => c.Log((RelationalEventId.CommandExecuting, LogLevel.Debug)));
        }
````
with this configuration, when request are executed, nothing in logged

however, if i use the "classic" .net core way (injection)
````
pServices.AddDbContext<DGenEntities>(options =>
            {
                options.UseSqlServer(config.DGenConnectionString);
                options.EnableDetailedErrors();

            });
````
````
public class MyService
{
private DGenEntities _dbContext;
public MyService(DGenEntities dbContext)
{
     _dbContext = dbContext;
}
public void MyMethod()
{
if(_dbContext.Users.Any(lUsr => lUsr.GrpID == pGrpID))
//log works well
}
}
````

There is something which can explained this ? how i can make it work without change original code ? (the code is share between the two app, so impossible to use dependency injection)

thanks !

**Comment by ajcvickers** [comment] 2020-06-12 18:28
@julienGrd I am not able to reproduce this--see below. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

I ran this code after creating a database with a null value for the required Name property.

```C#
public static class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            var users = context.Set<User>().ToList();
        }
    }
}

public class SomeDbContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>();
    }    

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .EnableSensitiveDataLogging()
            .EnableDetailedErrors()
            .UseSqlServer(Your.SqlServerConnectionString);
}

public class User
{
    public int Id { get; set; }
    
    [Required]
    public string Name { get; set; }
}
```

With `EnableDetailedErrors` I get:
```
Unhandled exception. System.InvalidOperationException: An exception occurred while reading a database value for property 'User.Name'. The expected type was 'System.String' but the actual value was null.
 ---> System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method1(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.Main() in /home/ajcvickers/AllTogetherNow/Daily/Daily.cs:line 31
```

Without it, I get:
```
Unhandled exception. System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method1(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.Main() in /home/ajcvickers/AllTogetherNow/Daily/Daily.cs:line 31
```

So it certainly seems to be working.

**Comment by ajcvickers** [comment] 2020-06-22 16:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:29 UTC
Labels: closed-could-not-reproduce, customer-reported
