### ISSUE TITLE
Migration with comment

### ISSUE THREAD

**Issue by Zefek** [dotnet/efcore#28239] opened 2022-06-15 11:26 UTC
Hello, 
I want to ask you if there is possibility to add comments into migration C# generated code. Many of teams have rule that each method or class needs to be commented. In migration script it is easy, because Up/Down method is override and comments it should be <inheritdoc />. 
For migration class (or type) empty summary comment will be enough. Or there could be option in dotnet-ef tool to add comment when generating migration and this comment will be in summary tag. 

Thank you.

**Comment by ajcvickers** [comment] 2022-06-16 17:26
Duplicate of #10695.

**Closed** 2022-06-17 16:12 UTC
Labels: customer-reported
