### ISSUE TITLE
Verification of nullable in debug/release builds

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#26952] opened 2021-12-09 09:45 UTC
Hello,

EF 6.0

https://github.com/dotnet/efcore/blob/f8020cb8a392dc30f515f54ef4c0c8ad60c6ed33/src/EFCore.Relational/Storage/RelationalTypeMapping.cs#L502

I guess this check shouldn't depend on the build configuration.

In my opinion, debug checks should only be used to catch internal errors. Not for checking external data.

**Comment by ajcvickers** [comment] 2021-12-11 20:09
@dmitry-lipetsk Do you have a case in your provider code that would trigger this if it were not compiled out?  If so, can you provide more details on this case?

**Comment by dmitry-lipetsk** [comment] 2021-12-11 22:18
@ajcvickers 

Code that cannot be compiled cannot be executed :)

I encountered this issue with a slightly flawed test (created through copy&paste of nullable-version) that compiled without issue.

**Part of this test**

``` c#
////////////////////////////////////////////////////////////////////////////////
//NUnit tests for "EF Core Provider for LCPI OLE DB"
//                                                 Kovalenko Dmitry. 09.12.2021.
using System;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NUnit.Framework;

using xdb=lcpi.data.oledb;

namespace EFCore_LcpiOleDb_Tests.General.Work.DBMS.Firebird.V03_0_0.D1.Query.Funcs.String.SET_001.STD.Concat__str3{
////////////////////////////////////////////////////////////////////////////////
//using

using T_DATA=System.String;

////////////////////////////////////////////////////////////////////////////////
//class TestSet_001__fields_02_VARCHAR_NN

public static class TestSet_001__fields_02_VARCHAR_NN
{
 private const string c_NameOf__TABLE="TEST_MODIFY_ROW2";

 private const string c_NameOf__COL_DATA1="COL_VARCHAR_10";
 private const string c_NameOf__COL_DATA2="COL2_VARCHAR_10";
 private const string c_NameOf__COL_DATA3="COL3_VARCHAR_10";

 //-----------------------------------------------------------------------
 private sealed class MyContext:TestBaseDbContext
 {
  [Table(c_NameOf__TABLE)]
  public sealed class TEST_RECORD
  {
   [Key]
   [Column("TEST_ID")]
   public System.Int64? TEST_ID { get; set; }

#nullable enable
   [Column(c_NameOf__COL_DATA1, TypeName="VARCHAR(10)")]
   public T_DATA DATA1 { get; set; } // <--------------------------- NOT NULL DATA

   [Column(c_NameOf__COL_DATA2, TypeName="VARCHAR(10)")]
   public T_DATA DATA2 { get; set; } // <--------------------------- NOT NULL DATA

   [Column(c_NameOf__COL_DATA3, TypeName="VARCHAR(10)")]
   public T_DATA DATA3 { get; set; } // <--------------------------- NOT NULL DATA
#nullable restore

   public TEST_RECORD()
   {
    this.DATA1=string.Empty;
    this.DATA2=string.Empty;
    this.DATA3=string.Empty;
   }
  };//class TEST_RECORD

  //----------------------------------------------------------------------
  public DbSet<TEST_RECORD> testTable { get; set; }

  //----------------------------------------------------------------------
  public MyContext(xdb.OleDbTransaction tr)
   :base(tr)
  {
  }//MyContext
 };//class MyContext

 //-----------------------------------------------------------------------
 [Test]
 public static void Test_002__V_N_V()
 {
  using(var cn=LocalCnHelper.CreateCn())
  {
   cn.Open();

   using(var tr=cn.BeginTransaction())
   {
    //insert new record in external transaction
    using(var db=new MyContext(tr))
    {
     const T_DATA c_data1="ABC\0123";
     const T_DATA c_data2=null; // <-------------------- "NULL" DATA FOR "NOT NULL" COLUMN
     const T_DATA c_data3="XYZ  ";

     System.Int64 testID=Helper__InsertRow(db,c_data1,c_data2,c_data3);

     // ............. DELETED
    }//using db

    tr.Rollback();
   }//using tr
  }//using cn
 }//Test_002__V_N_V

 //-----------------------------------------------------------------------
 private static System.Int64 Helper__InsertRow(MyContext db,
                                               T_DATA    valueOfData1,
                                               T_DATA    valueOfData2,
                                               T_DATA    valueOfData3)
 {
  var newRecord=new MyContext.TEST_RECORD();

  newRecord.DATA1=valueOfData1;
  newRecord.DATA2=valueOfData2; // <------------- SETUP NULL DATA WITHOUT ANY PROBLEMS.
  newRecord.DATA3=valueOfData3;

  db.testTable.Add(newRecord);

  db.SaveChanges(); // <--------------------   THROWS EXCEPTION IN DEBUG BUILD. NO PROBLEM IN RELEASE BUILD.

  db.CheckTextOfLastExecutedCommand
   (new TestSqlTemplate()
     .T("INSERT INTO ").N(c_NameOf__TABLE).T(" (").N(c_NameOf__COL_DATA1).T(", ").N(c_NameOf__COL_DATA2).T(", ").N(c_NameOf__COL_DATA3).T(")").EOL()
     .T("VALUES (").P("p0").T(", ").P("p1").T(", ").P("p2").T(")").EOL()
     .T("RETURNING ").N("TEST_ID").EOL()
     .T("INTO ").P("p3").T(";"));

  Assert.IsTrue
   (newRecord.TEST_ID.HasValue);

  Console.WriteLine("TEST_ID: {0}",newRecord.TEST_ID.Value);

  return newRecord.TEST_ID.Value;
 }//Helper__InsertRow
};//class TestSet_001__fields_02_VARCHAR_NN

////////////////////////////////////////////////////////////////////////////////
}//namespace EFCore_LcpiOleDb_Tests.General.Work.DBMS.Firebird.V03_0_0.D1.Query.Funcs.String.SET_001.STD.Concat__str3
```

**Stack of exception [in DEBUG build]**

>  Test_002__V_N_V
>    Source: TestSet_001__fields_02_VARCHAR_NN.cs line 134
>    Duration: 3,8 sec
> 
>   Message: 
> Microsoft.EntityFrameworkCore.DbUpdateException : An error occurred while saving the entity changes. See the inner exception for details.
>   ----> System.Exception : Check.DebugAssert failed: Null value in a non-nullable parameter
> 
>   Stack Trace: 
> ReaderModificationCommandBatch.Execute(IRelationalConnection connection) line 261
> FB_Common__BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection) line 114
> RelationalDatabase.SaveChanges(IList`1 entries) line 64
> StateManager.SaveChanges(IList`1 entriesToSave) line 1137
> StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess) line 1200
> <>c.<SaveChanges>b__104_0(DbContext _, ValueTuple`2 t) line 1181
> NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) line 60
> StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess) line 1177
> DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess) line 608
> DbContext.SaveChanges() line 560
> TestSet_001__fields_02_VARCHAR_NN.Helper__InsertRow(MyContext db, String valueOfData1, String valueOfData2, String valueOfData3) line 272
> TestSet_001__fields_02_VARCHAR_NN.Test_002__V_N_V() line 149
> --Exception
> Check.DebugAssert(Boolean condition, String message) line 120
> RelationalTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable) line 502
> TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value) line 62
> RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues) line 62
> LcpiOleDb__RelationalCommand.CreateDbCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod) line 522
> LcpiOleDb__RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject) line 309
> ReaderModificationCommandBatch.Execute(IRelationalConnection connection) line 250
> 

In release build, I get the fail of my test (from DELETED section).

In real application (release build), we may get the hidden problems.

**Comment by ajcvickers** [comment] 2021-12-17 11:41
@dmitry-lipetsk Is it possible to hit this assertion from application code, for example, by setting something to null that should not be null in an application?

**Comment by ajcvickers** [comment] 2022-01-11 12:18
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:18 UTC
Labels: closed-out-of-scope, customer-reported
