### ISSUE TITLE
Linq Ef Core query doesn't include filter parameter for join table if not set in the same () parentheses

### ISSUE THREAD

**Issue by emadalsous** [dotnet/efcore#31536] opened 2023-08-23 08:58 UTC
## File a bug

Remember:

* Please check that the [documentation](https://docs.microsoft.com/ef/) does not explain the behavior you are seeing.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your bug has not already been filed.

### Include your code

To fix any bug we must first reproduce it. To make this possible, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

It is often impossible for us to reproduce a bug when working with only code snippets since we have to guess at the missing code. 

Use triple-tick code fences for any posted code. For example:

```C#
   var cityContextFilter = "All";
        var countryContextFilter = "All":
//This way doesn't include the cityContextFilter condition when i call query.ToQueryString();
   var query = from city in _context.City
                    join cityContext in _context.CityContext on city.Id equals cityContext.CityId
                    join cityContextUsage in _context.CityContextUsage on cityContext.CityContextUsageId equals cityContextUsage.Id
                    join countryContext in _context.CountryContext on cityContext.CountryContextId equals countryContext.Id
                    join countryContextUsage in _context.CountryContextUsage on countryContext.CountryContextUsageId equals countryContextUsage.Id
                    join country in _context.Country on countryContext.CountryId equals country.Id
                    where isGuid ? country.Id == countryId : country.Isoalpha3 == request.CountryIdOrIsoAlpha3
                    && cityContext.ObsFlag == false
                    && cityContextUsage.Name == cityContextFilter
                    && countryContextUsage.Name == countryContextFilter
                    && cityContextUsage.ObsFlag == false
                    && countryContext.ObsFlag == false
                    && countryContextUsage.ObsFlag == false
                    && country.ObsFlag == false
                    && (city.ObsFlag == false || !city.ObsFlag.HasValue)
                    select city;             
//QueryToString result:

DECLARE @__request_CountryIdOrIsoAlpha3_2 nvarchar(5) = N'USA';

SELECT [c].[Id], [c].[CreDt], [c].[CreUser], [c].[DqdsOperationProcessId], [c].[ModDt], [c].[ModUser], [c].[ObsDt], [c].[ObsFlag], [c].[ObsUser], [c].[OfficialName], [c].[PeriodEnd], [c].[PeriodStart], [c].[UniqueCityCode], [c].[ZipCode]
FROM [mdmhub].[City] AS [c]
INNER JOIN [mdmhub].[CityContext] AS [c0] ON [c].[Id] = [c0].[CityId]
INNER JOIN [mdmhub].[CityContextUsage] AS [c1] ON [c0].[CityContextUsageId] = [c1].[Id]
INNER JOIN [mdmhub].[CountryContext] AS [c2] ON [c0].[CountryContextId] = [c2].[Id]
INNER JOIN [mdmhub].[CountryContextUsage] AS [c3] ON [c2].[CountryContextUsageId] = [c3].[Id]
INNER JOIN [mdmhub].[Country] AS [c4] ON [c2].[CountryId] = [c4].[Id]
WHERE [c4].[ISOAlpha3] = @__request_CountryIdOrIsoAlpha3_2 AND [c0].[ObsFlag] = CAST(0 AS bit) AND [c1].[ObsFlag] = CAST(0 AS bit) AND [c2].[ObsFlag] = CAST(0 AS bit) AND [c3].[ObsFlag] = CAST(0 AS bit) AND [c4].[ObsFlag] = CAST(0 AS bit) AND ([c].[ObsFlag] = CAST(0 AS bit) OR ([c].[ObsFlag] IS NULL)) 

//No contexts filters included in the previous example

   var query = from city in _context.City
                    join cityContext in _context.CityContext on city.Id equals cityContext.CityId
                    join cityContextUsage in _context.CityContextUsage on cityContext.CityContextUsageId equals cityContextUsage.Id
                    join countryContext in _context.CountryContext on cityContext.CountryContextId equals countryContext.Id
                    join countryContextUsage in _context.CountryContextUsage on countryContext.CountryContextUsageId equals countryContextUsage.Id
                    join country in _context.Country on countryContext.CountryId equals country.Id
                    where isGuid ? country.Id == countryId : country.Isoalpha3 == request.CountryIdOrIsoAlpha3
                    && cityContext.ObsFlag == false
                    && (cityContextUsage.ObsFlag == false && cityContextUsage.Name == cityContextFilter)
                    && countryContext.ObsFlag == false
                    && (countryContextUsage.ObsFlag == false && countryContextUsage.Name == countryContextFilter)
                    && country.ObsFlag == false
                    && (city.ObsFlag == false || !city.ObsFlag.HasValue)
                    select city;    


//Query To String result Context filter are included
    
DECLARE @__request_CountryIdOrIsoAlpha3_0 nvarchar(5) = N'USA';
**DECLARE @__cityContextFilter_1 nvarchar(255) = N'Official';
DECLARE @__countryContextFilter_2 nvarchar(255) = N'Official';**

SELECT [c].[Id], [c].[CreDt], [c].[CreUser], [c].[DqdsOperationProcessId], [c].[ModDt], [c].[ModUser], [c].[ObsDt], [c].[ObsFlag], [c].[ObsUser], [c].[OfficialName], [c].[PeriodEnd], [c].[PeriodStart], [c].[UniqueCityCode], [c].[ZipCode]
FROM [mdmhub].[City] AS [c]
INNER JOIN [mdmhub].[CityContext] AS [c0] ON [c].[Id] = [c0].[CityId]
INNER JOIN [mdmhub].[CityContextUsage] AS [c1] ON [c0].[CityContextUsageId] = [c1].[Id]
INNER JOIN [mdmhub].[CountryContext] AS [c2] ON [c0].[CountryContextId] = [c2].[Id]
INNER JOIN [mdmhub].[CountryContextUsage] AS [c3] ON [c2].[CountryContextUsageId] = [c3].[Id]
INNER JOIN [mdmhub].[Country] AS [c4] ON [c2].[CountryId] = [c4].[Id]
WHERE [c4].[ISOAlpha3] = @__request_CountryIdOrIsoAlpha3_0 AND [c0].[ObsFlag] = CAST(0 AS bit) AND [c1].[ObsFlag] = CAST(0 AS bit) AND [c1].[Name] = @__cityContextFilter_1 AND [c2].[ObsFlag] = CAST(0 AS bit) AND [c3].[ObsFlag] = CAST(0 AS bit) AND [c3].[Name] = @__countryContextFilter_2 AND [c4].[ObsFlag] = CAST(0 AS bit) AND ([c].[ObsFlag] = CAST(0 AS bit) OR ([c].[ObsFlag] IS NULL))



### Include stack traces
 

```

### Include provider and version information

EF Core version: 7.0.2
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 7.0
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by roji** [comment] 2023-08-23 14:19
@emadalsous this should definitely work. See the following minimal program based on your code:

```c#
await using var context = new BlogContext();
await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

var cityContextFilter = "All";

var query = from city in context.City
    join cityContext in context.CityContext on city.Id equals cityContext.CityId
    join cityContextUsage in context.CityContextUsage on cityContext.CityContextUsageId equals cityContextUsage.Id
    where cityContextUsage.Name == cityContextFilter
    select city;

Console.WriteLine(query.ToQueryString());

public class BlogContext : DbContext
{
    public DbSet<City> City { get; set; }
    public DbSet<CityContext> CityContext { get; set; }
    public DbSet<CityContextUsage> CityContextUsage { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class City
{
    public int Id { get; set; }
    public string? Name { get; set; }
}

public class CityContext
{
    public int Id { get; set; }
    public int CityId { get; set; }
    public int CityContextUsageId { get; set; }
}

public class CityContextUsage
{
    public int Id { get; set; }
    public string? Name { get; set; }
}
```

Produces the following:

```
DECLARE @__cityContextFilter_0 nvarchar(4000) = N'All';

SELECT [c].[Id], [c].[Name]
FROM [City] AS [c]
INNER JOIN [CityContext] AS [c0] ON [c].[Id] = [c0].[CityId]
INNER JOIN [CityContextUsage] AS [c1] ON [c0].[CityContextUsageId] = [c1].[Id]
WHERE [c1].[Name] = @__cityContextFilter_0
```

Please submit a similar minimal and runnable code sample that shows the problem happening.

**Comment by emadalsous** [comment] 2023-08-23 20:09
Hi,
Could you try to adapt the query in the example you provided to the following:
```
var query = from city in context.City
    join cityContext in context.CityContext on city.Id equals cityContext.CityId
    join cityContextUsage in context.CityContextUsage on cityContext.CityContextUsageId equals cityContextUsage.Id
    where cityContextUsage.Name == cityContextFilter
 && cityContextUsage.Delete=false
    select city;
```

If you can't produce it, i will try to provide a full-example

**Comment by roji** [comment] 2023-08-24 08:59
The result is the same, everything works as expected. You'll have to provide an example.

**Comment by ajcvickers** [comment] 2023-09-20 19:18
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-09-20 19:18 UTC
Labels: customer-reported
