### ISSUE TITLE
Query Does Not Return Included Entity After Execution

### ISSUE THREAD

**Issue by nyrhonr88** [dotnet/efcore#28053] opened 2022-05-18 20:11 UTC
The below code produces a list of Sections that does not contain any Instructor entities. 

```
public class Section
    {
        [Key]
        public Guid Id { get; set; }

        public bool Deleted { get; set; }

        public int InstitutionId { get; set; }

        public List<Instructor> Instructors { get; set; } = new ();
    }
```

```
public class Instructor
    {
        [Key]
        public Guid Id { get; set; }

        public bool Deleted { get; set; }

        public int InstitutionId { get; set; }

        public Guid SectionId { get; set; }
    }
```

```
var sections = new List<Section>();
var offset = 0;
var pagedSectionCount = 500;

do
    {
      var pagedSections = dbContext.Sections
            .Where(s => s.InstitutionId == request.InstitutionId)
             .Where(s => !s.Deleted);

       await pagedSections
             .Include(s => s.Instructors.Where(i => !i.Deleted))
             .Skip(offset)
             .Take(500)
             .ToListAsync(cancellationToken);

       sections.AddRange(pagedSections);
       pagedSectionCount = pagedSections.Count();
       offset += pagedSections.Count();
      }
while (pagedSectionCount == 500);

return sections;
```

However, modifying the code to look like the below **does** include the Instructor entities:

```
var sections = new List<Section>();
var offset = 0;
var pagedSectionCount = 500;

do
    {
      var pagedSections = dbContext.Sections
            .Where(s => s.InstitutionId == request.InstitutionId)
             .Where(s => !s.Deleted);

       var pagedSectionsWithInstructors = pagedSections.Include(s => s.Instructors.Where(i => !i.Deleted));

      await pagedSectionsWithInstructors
           .Skip(offset).Take(TakeCount)
      .ToListAsync(cancellationToken);

       sections.AddRange(pagedSections);
       pagedSectionCount = pagedSections.Count();
       offset += pagedSections.Count();
      }
while (pagedSectionCount == 500);

return sections;
```

Why is it that breaking out the Include() onto a separate line returns the loaded Instructor entity?

EF Core version: 6
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET 6.0
Operating system: Windows 10 Enterprise
IDE: Visual Studio Professional 2022 17.0.5

**Comment by smitpatel** [comment] 2022-05-18 21:40
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2022-05-27 09:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:34 UTC
Labels: closed-could-not-reproduce, customer-reported
