### ISSUE TITLE
InvalidOperationException when attempting to filter on decimal data type

### ISSUE THREAD

**Issue by pranavkm** [dotnet/efcore#16279] opened 2019-06-26 17:23 UTC
Using this DbContext - https://github.com/dotnet-presentations/blazor-workshop/blob/master/src/BlazingPizza.Server/PizzaStoreContext.cs, when I attempt to filter by a decimal property - https://github.com/dotnet-presentations/blazor-workshop/blob/master/src/BlazingPizza.Shared/Topping.cs#L9 like so

```C#
var model = await context.Toppings.Where(p => p.Price < 3).ToListAsync();
```

I get an `InvalidOperationException` without a message stating what's wrong and what I need to do to fix it:

```C#
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
```

Tested using `Microsoft.EntityFramework.Sqlite` v3.0.0-preview7.19326.1

**Comment by smitpatel** [comment] 2019-06-26 17:25
SQLite blocks decimal comparisons to be server evaluated since they are stored as text.
See https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations#query-limitations

Thanks @bricelam 😄

**Comment by pranavkm** [comment] 2019-06-26 17:27
Should the exception say that this is disallowed? It wasn't clear if I was doing something wrong authoring the query since it's a vanilla InvalidOperationException with no message string.

**Comment by smitpatel** [comment] 2019-06-26 17:28
Duplicate of #16133
Welcome to bleeding edge.

**Closed** 2022-10-16 14:27 UTC
Labels: closed-duplicate, customer-reported
