### ISSUE TITLE
Apply Migrations Bundles:error

### ISSUE THREAD

**Issue by abhishukla** [dotnet/efcore#30259] opened 2023-02-12 05:19 UTC
Hi Team,
I created  the migration bundle using below command in the DevOps pipeline

task: DotNetCoreCLI@2
  displayName: 'Build dotnet bundle'
  inputs:
    command: 'custom'
    custom: 'ef'
    arguments: 'migrations bundle --self-contained --target-runtime win-x64 --verbose --configuration Bundle --force
 
using the below command to apply migrations to a SQL Server 
- task: DotNetCoreCLI@2
  displayName: 'Deploy the database changes'
  inputs:
    command: 'custom'
    custom: './efbundle.exe'
    arguments: '--connection "Data Source=''

while applying this migration bundle getting the below error

![image](https://user-images.githubusercontent.com/3404405/218294343-592f1379-254e-4b3a-b27a-b315a436665e.png)

2023-02-12T03:47:47.9463021Z A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'D:\a\1\s\'.
2023-02-12T03:47:47.9472639Z Failed to run as a self-contained app.
2023-02-12T03:47:47.9473548Z   - The application was run as a self-contained app because 'D:\a\1\s\efbundle.runtimeconfig.json' was not found.
2023-02-12T03:47:47.9474385Z   - If this should be a framework-dependent app, add the 'D:\a\1\s\efbundle.runtimeconfig.json' file and specify the appropriate framework.
2023-02-12T03:47:47.9516686Z ##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 2147516547
2023-02-12T03:47:47.9540234Z Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
2023-02-12T03:47:47.9543215Z ##[error]Dotnet command failed with non-zero exit code on the following projects : [ '' ]
2023-02-12T03:47:47.9656008Z ##[section]Finishing: Deploy the database changes

**Comment by abhishukla** [comment] 2023-02-12 05:20
Please help me on this issue.

**Comment by ajcvickers** [comment] 2023-02-13 13:11
Looks like a duplicate of #16054. @abhishukla That issue has some workarounds.

**Closed** 2023-02-15 12:31 UTC
Labels: closed-duplicate, customer-reported

**Comment by itsshiningsun** [comment] 2024-09-23 05:47
@abhishukla I am facing the same issue when trying to run the EF bundle in build server. Have you got your issue resolved?
