### ISSUE TITLE
SaveChanges => Value cannot be null : derivedType

### ISSUE THREAD

**Issue by VincentG85** [dotnet/efcore#10442] opened 2017-11-30 08:40 UTC
When removing an element from a specific DbSet, an exception is thrown after effective DB delete. 

```
Exception message: 
      Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'MyContext'.
Stack trace:
      System.ArgumentNullException: Value cannot be null.
      Parameter name: derivedType
         at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
         at Microsoft.EntityFrameworkCore.EntityTypeExtensions.IsAssignableFrom(IEntityType entityType, IEntityType derivedType)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c__DisplayClass40_1.<StopTracking>b__0(INavigation n)
         at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StopTracking(InternalEntityEntry entry)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean forceStateWhenUnknownKey)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.AcceptChanges()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.AcceptAllChanges(IEnumerable`1 changedEntries)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
```

DataProviderfrom which Update then Commit is called: 
```c#
public class LetterDataProvider : BaseDataProvider, ILetterDataProvider
{
	public LetterDataProvider(MyContext context)
	{
		_context = context;
	}
	
	public ILetter Update(ILetter iLetter)
	{
		var existingLetter = FindConcrete(iLetter.ID);
		if (existingLetter == null) throw new ArgumentOutOfRangeException("ID");

		var updatedLetter = new Letter(iLetter);

		_context.Entry(existingLetter).CurrentValues.SetValues(updatedLetter);
		UpdateCollection(existingLetter.Companies, updatedLetter.Companies, x => x.CompanyID, x => x.LetterID = iLetter.ID);
		UpdateCollection(existingLetter.FieldValidations, updatedLetter.FieldValidations, x => x.FieldValidationID, x => x.LetterID = iLetter.ID);

		return existingLetter;
	}
	
	public void Commit()
	{
		**_context.SaveChanges();**
		//Task.Run(CommitAsync).Wait();
	}
	public async Task CommitAsync()
	{
		await _context.SaveChangesAsync();
	}

	private Letter FindConcrete(int id)
	{
		var mails = _context.Letters
			.Where(m => m.ID == id && m.Center.ID == _context.CenterID)
			.Include(m => m.FieldValidations)
			.Include(m => m.Companies);

		return mails.SingleOrDefault();
	}
}
```

The base class which effectively removes the element: 
```c#
public abstract class BaseDataProvider
{
	protected MyContext _context;

	protected void UpdateCollection<TElement>(ICollection<TElement> existingCollection, ICollection<TElement> updatedCollection, 
		Func<TElement, Int32> childKeySelector, Action<TElement> parentKeySetter)
		where TElement : class
	{
		foreach (var existingElement in existingCollection)
		{
			if (!updatedCollection.Any(c => childKeySelector(c) == childKeySelector(existingElement)))
				**_context.Remove(existingElement);**
		}

		foreach (var updatedElement in updatedCollection)
		{
			parentKeySetter(updatedElement);

			var existingElement = existingCollection.SingleOrDefault(c => childKeySelector(c) == childKeySelector(updatedElement));
			if (existingElement != null)
			{
				_context.Entry(existingElement).CurrentValues.SetValues(updatedElement);
				_context.Entry(existingElement).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
			}
			else
			{
				existingCollection.Add(updatedElement);
				_context.Add(updatedElement);
			}
		}
	}
}
```

The entity involved: 
```c#
public class Letter_FieldValidation : AbstractEntity, ILetterFieldValidation
{
	[Column("Letter_ID")]
	public int LetterID { get; set; }
	public Letter Letter { get; set; }

	[Column("FieldValidation_ID")]
	public int FieldValidationID { get; set; }
	public FieldValidation FieldValidation { get; set; }

	public bool IsMandatory { get; set; }
	public string Message { get; set; }

	int IFieldValidation.ID { get => FieldValidationID; set => FieldValidationID = value; }
	string IFieldValidation.Code { get => FieldValidation?.Code; set { } /* => FieldValidation.Code = value; */ }
	string IFieldValidation.Designation { get => FieldValidation?.Designation; set { } /* => FieldValidation.Designation = value; */ }

	public Letter_FieldValidation() : base()
	{
		//FieldValidation = new FieldValidation();
	}

	public Letter_FieldValidation(ILetterFieldValidation iLetterFieldValidation) : this()
	{
		Mapper.Map(iLetterFieldValidation, this);
	}
}
```

My DbContext: 
```c#
public class MyContext : DbContext
{
	public int UserID { get; set; }
	public int CenterID { get; set; }
	private String _databaseName { get; set; }
	private ILoggerFactory _loggerFactory { get; set; }

	public DbSet<Center> Centers { get; set; }
	public DbSet<Center_Company> CenterCompanies { get; set; }

	public DbSet<Company> Companies { get; set; }

	public DbSet<Letter> Letters { get; set; }
	public DbSet<Letter_Company> Letter_Companies { get; set; }
	public DbSet<Letter_FieldValidation> Letter_FieldValidations { get; set; }
	public DbSet<LetterMacro> LetterMacros { get; set; }

	public DbSet<FieldValidation> Controls { get; set; }
	public DbSet<User> Utilisateurs { get; set; }

	public MyContext(ILoggerFactory loggerFactory, int userId, int centerId, string databaseName = null)
	{
		UserID = userId;
		CenterID = centerId;

		_databaseName = databaseName;
		_loggerFactory = loggerFactory;
	}

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		optionsBuilder.UseLoggerFactory(_loggerFactory);
		optionsBuilder.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

		var config = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
		var connectionStringBuilder = new MySqlConnectionStringBuilder(config.GetConnectionString("MySQLConnection"));
		if (_databaseName != null)
			connectionStringBuilder.Database = _databaseName;
		optionsBuilder.UseMySql(connectionStringBuilder.ConnectionString);
	}

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		foreach (var entity in modelBuilder.Model.GetEntityTypes())
		{
			entity.Relational().TableName = entity.DisplayName();
		}

		modelBuilder.ApplyConfiguration(new CenterConfiguration());
		modelBuilder.ApplyConfiguration(new Center_CompanyConfiguration());

		modelBuilder.ApplyConfiguration(new UserConfiguration());

		modelBuilder.ApplyConfiguration(new CompanyConfiguration());

		modelBuilder.ApplyConfiguration(new LetterConfiguration());
		modelBuilder.ApplyConfiguration(new LetterMacroConfiguration());

		modelBuilder.ApplyConfiguration(new Letter_FieldValidationConfiguration());
		modelBuilder.ApplyConfiguration(new Letter_CompanyConfiguration());
		modelBuilder.ApplyConfiguration(new FieldValidationConfiguration());

		modelBuilder.ApplyConfiguration(new ContentConfiguration());
	}
}
```

### Further technical details
EF Core version: 2.0.1
Database Provider: Pomelo.EntityFrameworkCore.MySql
Operating system: Windows 10 (1703)
IDE: Visual Studio 2017 Pro

**Comment by ajcvickers** [comment] 2017-12-01 20:52
@VincentG85 I have not been able to reproduce this with just the code above--there are a lot of types referenced that are not included in the code listing. I tried to start trimming it down, but was not able to get to something that made sense and was runnable. Could you please post a full runnable project/solution or code listing so we can effectively triage the issue?

**Comment by ajcvickers** [comment] 2017-12-11 19:05
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by PhilipNunn** [comment] 2018-08-20 19:48
FWIW, I hit this error when using Reload() on an entity obtained with another context. Cleanly re-querying for it on the current context fixed it.,

**Comment by alexb5dh** [comment] 2019-06-13 19:29
Also encountered it. Didn't manage to create minimal reproducible sample yet.

**Closed** 2022-10-16 12:01 UTC
Labels: closed-could-not-reproduce
