### ISSUE TITLE
How to include a property of a subclass

### ISSUE THREAD

**Issue by mkucera47** [dotnet/efcore#4124] opened 2015-12-17 21:55 UTC
I have the following model:

```
class Image
{
    public int Id { get; set; }
    public string Url { get; set; }
    public int Width { get; set; }
    public int Height { get; set; }
}

class ImagePost : BasePost
{
    public List<Image> Images { get; set; }
}

class BasePost
{
    public int Id { get; set; }
    public string Heading { get; set; }
    public string Text { get; set; }
}

class BloggingContext : DbContext
{
    public DbSet<Image> Igames { get; set; }

    public DbSet<BasePost> Posts { get; set; }

    public DbSet<ImagePost> ImagePosts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Filename=blogs.db");
    }
}
```

How can I call `Include` on `db.Posts` so that every `ImagePost` gets its `Images` property included?

**Comment by nocommonsense** [comment] 2015-12-23 16:30
What is the relationship between BasePost and ImagePost? From your model I can't see one. You will need to configure a relationship between these entities, therefore allowing you to call upon ImagePost.

**Comment by rowanmiller** [comment] 2015-12-23 21:33
Probably a dupe of https://github.com/aspnet/EntityFramework/issues/3910. I don't think there is any way to do this at the moment, though it would be good to support something like `context.Posts.Include(p => (p as ImagePost).Images)`.

**Comment by rowanmiller** [comment] 2015-12-28 19:16
Confirmed that this is currently not possible and we have #3910 tracking enabling this feature.

**Closed** 2022-10-16 09:21 UTC

**Comment by gelanquizora** [comment] 2023-05-08 02:29
> 

it's 2023 and this is now working :)

**Comment by gelanquizora** [comment] 2023-05-08 02:30
> Probably a dupe of #3910. I don't think there is any way to do this at the moment, though it would be good to support something like `context.Posts.Include(p => (p as ImagePost).Images)`.

it's 2023 and this is now working :)

**Comment by gelanquizora** [comment] 2023-05-08 02:32
> Confirmed that this is currently not possible and we have #3910 tracking enabling this feature.

> Probably a dupe of #3910. I don't think there is any way to do this at the moment, though it would be good to support something like `context.Posts.Include(p => (p as ImagePost).Images)`.

Yeah it's working! Thanks @rowanmiller!
