### ISSUE TITLE
.NET Native: ef with prism library 's throw exception

### ISSUE THREAD

**Issue by jingliancui** [dotnet/efcore#5407] opened 2016-05-18 13:09 UTC
Property 'Count' was not found on type 'System.Collections.ArrayList'.

I writed 2 sample in onedrive,you can see different between both these.
Here is the link:
https://onedrive.live.com/redir?resid=C78B7E4A6377EC22!249164&authkey=!AN8hVlZgjwIc5Bg&ithint=file%2crar

**Comment by natemcmaster** [comment] 2016-05-23 21:56
@jingliancui this issue should be fixed by upgrading to the latest UWP tools. (See  https://github.com/aspnet/Announcements/issues/170). Can you confirm you have UWP tools >= 1.3.1? 

Also, your repro project is using EF RC1. Now that we have released RC2, can you upgrade and tell us if the issue still reproduces? Our packages were renamed in this upgrade. See https://docs.efproject.net/en/latest/miscellaneous/rc1-rc2-upgrade.html for more details.

**Comment by jingliancui** [comment] 2016-05-24 07:49
@natemcmaster  That is RC2. If Please note that:
EF with PrismLibrary go throw exception.
EF without PrismLibrary is no problem.
Both two project sample I had upload to onedrive, you can try it.
The Prism team tell me that they don't know this exception is from yours or from them.....

**Comment by natemcmaster** [comment] 2016-05-24 21:51
@jingliancui my mistake. I opened the wrong rar file in your onedrive link.

After playing with the app a little, it seems the issue is related to neither Prism or Entity Framework Core. Although the error shows up from an EF stack trace, the error is the combination of re-linq (a dependency of EF) and Microsoft.ApplicationInsights. Something in Microsoft.ApplicationInsights.WindowsApps causes a side-effect on System.Collections. re-linq encounters the error because it reflects over System.Collections.

:x: Doesn't work
```js
  { "dependencies": {
    "Microsoft.ApplicationInsights.WindowsApps": "1.1.1", // <-- the source of the issue
    "Microsoft.EntityFrameworkCore.SQLite": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview1-final",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0",
    "Prism.Core": "6.1.0",
    "Prism.Unity": "6.1.0",
    "Unity": "4.0.1"
  },
```

:white_check_mark: works
```json
  "dependencies": {
    "Microsoft.EntityFrameworkCore.SQLite": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview1-final",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0",
    "Prism.Core": "6.1.0",
    "Prism.Unity": "6.1.0",
    "Unity": "4.0.1"
  },
```

Sorry to bounce you to yet another repo, but I would suggest filing an issue with https://github.com/Microsoft/ApplicationInsights-dotnet. 

I'm closing this as it's external to EF and not sure we can do anything about this. But feel free to discuss more here.

**Comment by natemcmaster** [comment] 2016-05-25 17:44
Reopening. Microsoft.ApplicationInsights.WindowsApps was red herring. This an issue with the .NET Native compiler.

**Comment by natemcmaster** [comment] 2016-05-25 18:04
Opened https://github.com/aspnet/EntityFramework/issues/5517 to track this as the same issue was reported in multiple issues.

**Closed** 2022-10-16 09:41 UTC
Labels: closed-duplicate
