### ISSUE TITLE
EF Core 7 DbContext.Database.BeginTransaction().GetDbTransaction() -> Not able to create new Transaction in same connection

### ISSUE THREAD

**Issue by manish-shipbob** [dotnet/efcore#32120] opened 2023-10-21 17:26 UTC
I am getting error - The connection is already in a transaction and cannot participate in another transaction in below code. 
Need help, as don't want to call the Connection.Close() explicitly.

```c#
// Code in Repo:
public virtual IDbTransaction BeginTransaction() => _context.Database.BeginTransaction().GetDbTransaction();
```

```c#
// code using repo object, exception in 2nd iteration:
for (int i = 0; i < 10; i++)
                {
                    using var dbTransaction = _repository.BeginTransaction();
                    {
                        try
                        {
                            var table1Data = await _repository.Get<Table1>().Take(10).ToListAsync();
                            table1Data[i].Comment = $"New Test Comment  id = {i}";
                            _repository.Update(table1Data[i]);
                            var table2Data = await _repository.Get<Table2>().Take(10).ToListAsync();
                            table2Data[i].Amount = i * 10 + 10;
                            _repository.Update(table2Data[i]);
                            dbTransaction.Commit();
                        }
                        catch (Exception ex)
                        {
                            dbTransaction.Rollback();
                        }
                    }
                }
```

Can you point out what is wrong in the above code.
General scenario is, I need to loop through objects and perform db transaction on each object. But 2nd iteration always failing.

**Comment by roji** [comment] 2023-10-22 11:54
@manish-shipbob your _repository.Update (or Get) or likely attempting to start another transaction internally; since a transaction is already in progress (the one you manually started), and database don't support nested transactions, you get an exception.

However, it's impossible to tell since you haven't posted the full code. If you need further assistance, please submit a minimal, runnable code sample.

**Comment by ajcvickers** [comment] 2023-11-08 18:34
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-11-08 18:34 UTC
Labels: customer-reported
