### ISSUE TITLE
AmbiguousMatchException: Ambiguous match found.

### ISSUE THREAD

**Issue by lborba** [dotnet/efcore#15065] opened 2019-03-18 20:08 UTC
Describe what is not working as expected.
When I try to fetch data (any simple query using EF 3), I am getting the exception below.
I have even reduced my table to its Id column only and still the error persists.
Not sure if the problem is on my end or with EF 3 itself.
Any hints?

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
**Exception message:**

AmbiguousMatchException: Ambiguous match found.
System.RuntimeType.GetMethodImplCommon(string name, int genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)

TypeInitializationException: The type initializer for 'Microsoft.EntityFrameworkCore.Storage.TypedRelationalValueBufferFactoryFactory' threw an exception.
Microsoft.EntityFrameworkCore.Storage.TypedRelationalValueBufferFactoryFactory+<>c__DisplayClass12_0.<CreateArrayInitializer>b__0(TypeMaterializationInfo mi, int i)

**Stack trace:**
TypeInitializationException: The type initializer for 'Microsoft.EntityFrameworkCore.Storage.TypedRelationalValueBufferFactoryFactory' threw an exception.
Microsoft.EntityFrameworkCore.Storage.TypedRelationalValueBufferFactoryFactory+<>c__DisplayClass12_0.<CreateArrayInitializer>b__0(TypeMaterializationInfo mi, int i)
System.Linq.Enumerable.SelectIterator<TSource, TResult>(IEnumerable<TSource> source, Func<TSource, int, TResult> selector)+MoveNext()
System.Collections.Generic.LargeArrayBuilder<T>.AddRange(IEnumerable<T> items)
System.Collections.Generic.EnumerableHelpers.ToArray<T>(IEnumerable<T> source)
System.Linq.Enumerable.ToArray<TSource>(IEnumerable<TSource> source)
System.Dynamic.Utils.CollectionExtensions.ToReadOnly<T>(IEnumerable<T> enumerable)
System.Linq.Expressions.Expression.NewArrayInit(Type type, IEnumerable<Expression> initializers)
Microsoft.EntityFrameworkCore.Storage.TypedRelationalValueBufferFactoryFactory.CreateArrayInitializer(CacheKey cacheKey, bool detailedErrorsEnabled)
Microsoft.EntityFrameworkCore.Storage.TypedRelationalValueBufferFactoryFactory.<Create>b__10_0(CacheKey k)
System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey key, Func<TKey, TValue> valueFactory)
Microsoft.EntityFrameworkCore.Storage.TypedRelationalValueBufferFactoryFactory.Create(IReadOnlyList<TypeMaterializationInfo> types)
Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.CreateValueBufferFactory(IRelationalValueBufferFactoryFactory relationalValueBufferFactoryFactory, DbDataReader dataReader)
Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.<NotifyReaderCreated>b__14_0(FactoryAndReader s)
Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized<TParam, TValue>(ref TValue target, TParam param, Func<TParam, TValue> valueFactory)
Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.NotifyReaderCreated(DbDataReader dataReader)
Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+Enumerator.BufferlessMoveNext(DbContext _, bool buffer)
Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute<TState, TResult>(TState state, Func<DbContext, TState, TResult> operation, Func<DbContext, TState, ExecutionResult<TResult>> verifySucceeded)
Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+Enumerator.MoveNext()
Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities<TOut, TIn>(IEnumerable<TOut> results, QueryContext queryContext, IList<EntityTrackingInfo> entityTrackingInfos, IList<Func<TIn, object>> entityAccessors)+MoveNext()
Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider+ExceptionInterceptor<T>+EnumeratorExceptionInterceptor.MoveNext()
System.Collections.Generic.List<T>..ctor(IEnumerable<T> collection)
System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
ShoWare.B2BAPI.ServiceFacade.Services.PerformanceService.GetPerformances() in C:\Repos\ShoWare.B2BAPI\ShoWare.B2BAPI.ServiceFacade\Services\PerformanceService.cs
ShoWare.B2BAPI.WebApi.Controllers.PerformancesController.Get(GetPerformancesRequest request) in C:\Repos\ShoWare.B2BAPI\ShoWare.B2BAPI.WebApi\Controllers\PerformancesController.cs
lambda_method(Closure , object )
Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable+Awaiter.GetResult()
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: 3.0.0-preview3.19153.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer (3.0.0-preview3.19153.1)
Operating system: Windows 10 (running on Linux Docker container)
IDE: Visual Studio 2019 RC 2

**Comment by smitpatel** [comment] 2019-03-18 20:36
Duplicate of #15008

**Closed** 2022-10-16 13:56 UTC
Labels: closed-duplicate, customer-reported
