### ISSUE TITLE
ThenInclude on base class's property causes ArgumentNullException

### ISSUE THREAD

**Issue by gregbty** [dotnet/efcore#4248] opened 2016-01-07 20:29 UTC
The following results in: `ArgumentNullException: Value cannot be null`.

``` csharp
    public abstract class Entity
    {
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public Guid? CreatedById { get; set; }
        public Guid? UpdatedById { get; set; }
        public User CreatedBy { get; set; }
        public User UpdatedBy { get; set; }
    }
```

``` csharp
    public class Company : Entity
    {
        ...
    }
```

``` csharp
   context.Set<Company>().Include(t => t.CreatedBy);
```

This was supported in EF6, so I was wondering if this was a bug or an unimplemented feature. I saw https://github.com/aspnet/EntityFramework/issues/3910 but was not sure if the two issues were equivalent.

**Comment by gregbty** [comment] 2016-01-09 03:45
After re-examining my example, it looks like what I stated above actually works. What I am having a problem with is this:

```csharp
    public abstract class Entity
    {
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public Guid? CreatedById { get; set; }
        public Guid? UpdatedById { get; set; }
        public User CreatedBy { get; set; }
        public User UpdatedBy { get; set; }
    }
```

```csharp
    public class Project : Entity
    {
        public List<Attachment> Attachments { get; set; }
    }
```

```csharp
    public class Attachment : Entity
    {
        ...
    }
```

```csharp
   context.Set<Project>().Include(t => t.CreatedBy); //works
   context.Set<Project>().Include(t => t.Attachments).ThenInclude(t => t.CreatedBy); //does not work
```

After doing some searching it looks like this is the same issue as https://github.com/aspnet/EntityFramework/issues/3994.

**Comment by smitpatel** [comment] 2016-01-14 22:45
dupe of #3994

**Closed** 2022-10-16 09:24 UTC
