### ISSUE TITLE
Edmx designer takes 5+ minute when updating from model - EF 6.1.3, VS 2015

### ISSUE THREAD

**Issue by san7hos** [dotnet/efcore#3621] opened 2015-10-31 21:25 UTC
Every time I need to update my emdx from database, the update wizard takes an incredible amount of time to do so rendering itself as not responding once you hit the finish (as finish the update) button.

I use Visual Studio 2015 and LocalDb SQL Server 2014. Some people suggested to install the Service Pack 1 to address the issue. I have installed the SP1 for LocalDb, but it has not helped. My installation of VS2015 is also rather new.

I have the latest Entity Framework 6 version.

http://stackoverflow.com/questions/32700540/update-wizard-not-responding

**Comment by ErikEJ** [comment] 2015-11-01 12:22
Hi, this issue list is for EF7, pls post any EF6 issues here: http://entityframework.codeplex.com/
Having said that, do you have the latest EF Tools MSI installed?

**Comment by San7hos** [comment] 2015-11-01 12:28
Hi Erik,

thanks for pointing that out. I will post the issue there. 

Regarding the MSI, I am not sure how to find out. However, when I go to the [EF page](https://msdn.microsoft.com/en-gb/data/ee712906), I see only downloads for VS 2012 and 2013 while i am running 2015.

**Comment by ErikEJ** [comment] 2015-11-01 12:36
I missed that - then you already have the latest Tools. Have you tried setting the Compatibility mode for the database to 110 (iso 120) ?

**Comment by San7hos** [comment] 2015-11-01 16:15
Ok, I am shocked. I had the compatibility mode set to 120. It seems it is works way faster when I set it to 110. Thanks

**Comment by rowanmiller** [comment] 2015-11-03 19:56
This is due to a performance regression in SQL Server, it was fixed in a patch but it looks like it has regressed again - we will follow up with them.

**Comment by ErikEJ** [comment] 2015-11-03 20:06
@san7hos did you install the latest CU as well ?

**Comment by divega** [comment] 2015-11-04 00:03
See http://entityframework.codeplex.com/workitem/2445 for more context on the original SQL Server 2014 regression, the workaround we put in place to compensate and how we ended up removing it in more recent versions of EF Tools.

**Comment by San7hos** [comment] 2015-11-05 11:10
@ErikEJ I think I did not. I was not really sure if it is completely compatible with the LocalDb storage. I also could not figure out whether you have to install the CUs separately or if the latest contain the previous ones. I am a big rookie in terms of using CUs :)

@divega Thanks

------

Anyway, my conclusion is that once I have time and resources on the project, I will move to code first and map the existing db to the entities. I use the VS database project to maintain the database.

**Closed** 2022-10-16 09:14 UTC
