### ISSUE TITLE
Remove With Condition

### ISSUE THREAD

**Issue by mohamedmahmoudalemam** [dotnet/efcore#14596] opened 2019-02-04 09:42 UTC
Why not add an overload to Remove and RemoveRange methods that take a predicate:
ex: context.Employees.Remove(x => x.Id ==1);
and context.Employees.RemoveRange(x => x.DepartmentId == 1);

So one sql command and no need to get either object to delete or list to delete.

**Comment by JanEggers** [comment] 2019-02-04 14:52
https://github.com/zzzprojects/EntityFramework-Plus

**Comment by mohamedmahmoudalemam** [comment] 2019-02-04 15:41
Official support will be nice.

**Comment by ajcvickers** [comment] 2019-02-04 16:59
Duplicate of #795

**Closed** 2022-10-16 13:50 UTC
Labels: customer-reported
