### ISSUE TITLE
Query :: customers.Include(c => c.Orders).SingleOrDefault() reads orders for the second customer, which is redundant

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#5148] opened 2016-04-22 01:30 UTC
For the scenario in question we create two queries:

outer - querying for the customers:

```
SELECT TOP(2) [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[Phone], [c].[PostalCode], [c].[Region]
FROM [Customers] AS [c]
ORDER BY [c].[CustomerID]
```

and inner - querying for corresponding orders:

```
SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
FROM [Orders] AS [o]
INNER JOIN (
    SELECT DISTINCT TOP(2) [c].[CustomerID]
    FROM [Customers] AS [c]
    ORDER BY [c].[CustomerID]
) AS [c0] ON [o].[CustomerID] = [c0].[CustomerID]
ORDER BY [c0].[CustomerID]
```

When executing the query we:
- materialize customer1 from the outer query, 
- materialize orders for customer1 from the inner query,
- materialize customer2 from the outer query,
- materialize orders for customer2 from the inner query,
- perform client-side SingleOrDefault() which throws exception.

We could throw earlier, after reading the second customer, we don't need to also read their corresponding orders. That would probably require custom _SingleOrDefault() method, rather than relying on the Enumerable version

**Comment by smitpatel** [comment] 2017-09-05 23:36
Duplicate of #2182

**Closed** 2022-10-16 09:37 UTC
Labels: area-perf
