### ISSUE TITLE
The whole related entity gets loaded when doing a null-check on an optionally projected member

### ISSUE THREAD

**Issue by aradalvand** [dotnet/efcore#22792] opened 2020-09-26 17:19 UTC
## How to reproduce?
Say you have: `Book` and `Author` domain classes + `BookDto` and `AuthorDto` classes which are a subselection of their respective domain classes.

Somewhere in the app, you have to expose/work with an `IQueryable<BookDto>` rather than an `IQueryable<Book>`, So, you write the following code to do the conversion, nothing complicated:

```csharp
IQueryable<BookDto> queryableDto = dbContext.Books.Select(book => new BookDto
{
    Name = book.Name,
    ...
    Author = book.Author == null ? null : new AuthorDto
    {
        Id = book.Author.Id,
        Name = book.Author.Name,
        Age = book.Author.Age
        ...
    }
});
```

And you try to do something like this:
```csharp
List<BookDto> dtos = queryableDto.Select(bDto => new BookDto
{
    Name = bDto.Name,
    Author = bDto.Author == null ? null : new AuthorDto() { Name = bDto.Author.Name }
}).ToList();
```
However, there is a big problem with the null-check in the second query (where it says `Author = bDto.Author == null ? null : new...`). Because in the `bDto.Author == null` part what happens is that Entity Framework Core retrieves the whole `Author` object with all of its columns from the database, but obviously that wasn't what the query was intending to do.
These null-checks get translated to SQL when you're working with an `IQueryable` of domain classes, of course (like in the first code block), but not when you're doing a custom projection prior to your actual querying, like what we've here.

You also can't get rid of the null-check since you have to find out whether the book has an author or not. (I know that in real life there can't be a book without an author but this is just an example)

Not to mention that I know WHY this problem occurs, it's due to the fact that when EF looks at the expression `bDto.Author == null` there, at this point it can't translate that to SQL and it simply assumes that you want the whole author, instead. So, I'm not really looking for the why.

So, currently, is there a solution for this? Even if it's a hack or weird trick I'm fine with it! And if there isn't, is there a chance that this will be fixed in future versions?

### The SQL that got generated:
For the above piece of code, EF Core generates the following SQL:
```sql
SELECT [b].[Name], CASE
    WHEN [a].[Id] IS NULL THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END, [a].[Id], [a].[Name], [a].[Age]
FROM [Books] AS [b]
LEFT JOIN [Authors] AS [a] ON [b].[AuthorId] = [a].[Id]
```
Instead, it should ideally be the following:
```sql
SELECT [b].[Name], CASE
    WHEN [a].[Id] IS NULL THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END, [a].[Name]
FROM [Books] AS [b]
LEFT JOIN [Authors] AS [a] ON [b].[AuthorId] = [a].[Id]
```
Since I haven't requested any column on the author other than `Name`.

### Other information:
EF Core version: I've tried it with both 3.1.8 (latest stable) + 5.0.0 RC
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.7

Thanks in advance.

**Comment by maumar** [comment] 2020-09-27 05:07
I've tried the following code on current bits:

```cs
        [ConditionalFact]
        public virtual void Repro22792()
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();
                var queryableDto = ctx.Books.Select(book => new BookDto
                {
                    Name = book.Name,
                    Author = book.Author == null ? null : new AuthorDto
                    {
                        Id = book.Author.Id,
                        Name = book.Author.Name,
                    }
                });

                var dtos = queryableDto.Select(bDto => new BookDto
                {
                    Name = bDto.Name,
                    Author = bDto.Author == null ? null : new AuthorDto() { Name = bDto.Author.Name }
                }).ToList();
            }
        }

        public class Book
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public string Genre { get; set; }

            public Author Author { get; set; }
        }

        public class Author
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public int Age { get; set; }
            public List<Book> Books { get; set; }
        }

        public class BookDto
        {
            public string Name { get; set; }
            public AuthorDto Author { get; set; }
        }

        public class AuthorDto
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }

        public class MyContext : DbContext
        {
            public DbSet<Book> Books { get; set; }
            public DbSet<Author> Authors { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Repro;Trusted_Connection=True;MultipleActiveResultSets=true");
            }
        }
```


and the sql i'm getting is:

```sql
SELECT [b].[Name], CASE
    WHEN [a].[Id] IS NULL THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END, [a].[Id], [a].[Name]
FROM [Books] AS [b]
LEFT JOIN [Authors] AS [a] ON [b].[AuthorId] = [a].[Id]
```

Which is what we want - null check is translated and no extra columns (age/genre) are pulled from the database.

@AradAral is the code above missing some important detail? Could you modify it to match your case or provide a full code sample instead? I'm curious that ef is producing INNER JOIN for you. That would indicate the relationship between author and book is required, so the author is always expected to be there. Since null check is what the issue is all about, this assumption is wrong (either by EF for some reason or in the model configuration)

**Comment by powermetal63** [comment] 2020-09-27 09:57
@maumar With 5.0 RC1 bits I'm getting the same translation as yours, but **with** additional `[a].[Age]` in the root `SELECT`.  According to your post, we can safely consider it already fixed I guess?

**Comment by AradAral** [comment] 2020-09-27 21:48
@maumar I think you made a mistake, there is nothing other than `Id` and `Name` in your Author DTO so that's basically "ALL the fields".
Add `Age` to your AuthorDto and project in the first project, but don't request it in the final one, and you'll see that the SQL will be:
SELECT [b].[Name], CASE
    WHEN [a].[Id] IS NULL THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END, [a].[Id], [a].[Name], [a].[Age]
FROM [Books] AS [b]
LEFT JOIN [Authors] AS [a] ON [b].[AuthorId] = [a].[Id]

The age is being retrieved unnecessarily.

**Comment by AradAral** [comment] 2020-09-27 21:50
@powermetal63 Please see my comment above ☝

**Comment by maumar** [comment] 2020-09-28 04:29
Initially we get the following expression:

```cs
DbSet<Book>()
    .Select(book => new BookDto{ 
        Name = book.Name, 
        Author = book.Author == null ? null : new AuthorDto{ 
            Id = book.Author.Id, 
            Name = book.Author.Name, 
            Age = book.Author.Age 
        }
    })
    .Select(bDto => new BookDto{ 
        Name = bDto.Name, 
        Author = bDto.Author == null ? null : new AuthorDto{ Name = bDto.Author.Name }
    })
```

during nav expansion we combine both selects into:

```cs
DbSet<Book>()
    .LeftJoin(
        inner: DbSet<Author>(), 
        outerKeySelector: b => EF.Property<Nullable<int>>(b, "AuthorId"), 
        innerKeySelector: a => EF.Property<Nullable<int>>(a, "Id"), 
        resultSelector: (o, i) => new TransparentIdentifier<Book, Author>(
            Outer = o, 
            Inner = i
        ))
    .Select(b => new BookDto{ 
        Name = b.Outer.Name, 
        Author = b.Inner == null ? null : new AuthorDto{ 
            Id = b.Inner.Id, 
            Name = b.Inner.Name, 
            Age = b.Inner.Age 
        } == null ? null : new AuthorDto{ Name = b.Inner == null ? null : new AuthorDto{ 
                Id = b.Inner.Id, 
                Name = b.Inner.Name, 
                Age = b.Inner.Age 
            }
            .Name }
    })
```

and further optimize to:

```cs
DbSet<Book>()
    .LeftJoin(
        inner: DbSet<Author>(), 
        outerKeySelector: b => EF.Property<Nullable<int>>(b, "AuthorId"), 
        innerKeySelector: a => EF.Property<Nullable<int>>(a, "Id"), 
        resultSelector: (o, i) => new TransparentIdentifier<Book, Author>(
            Outer = o, 
            Inner = i
        ))
    .Select(b => new BookDto{ 
        Name = b.Outer.Name, 
        Author = b.Inner == null || new AuthorDto{ 
            Id = b.Inner.Id, 
            Name = b.Inner.Name, 
            Age = b.Inner.Age 
        }
         == null ? null : new AuthorDto{ Name = b.Inner.Name }
    })
```

However, we can't do optimized entity equality (i.e. just compare the key to null) on Author anymore, because that information is lost when it gets projected as a dto.

@AradAral as a workaround you can add additional property to BookDto that represents the result of entity equality on the Author (when it's still an entity)

```
        public class BookDto
        {
            public string Name { get; set; }
            public bool AuthorIsNull { get; set; }   // <----  added this line
            public AuthorDto Author { get; set; }
        }
```

query:

```cs
                var queryableDto = ctx.Books.Select(book => new BookDto
                {
                    Name = book.Name,
                    AuthorIsNull = book.Author == null, // <----  added this line
                    Author = book.Author == null ? null : new AuthorDto
                    {
                        Id = book.Author.Id,
                        Name = book.Author.Name,
                        Age = book.Author.Age
                    }
                });

                var dtos = queryableDto.Select(bDto => new BookDto
                {
                    Name = bDto.Name,
                    Author = bDto.AuthorIsNull // <----  using new property rather than null check on dto
                       ? null
                       : new AuthorDto() { Name = bDto.Author.Name } 
                }).ToList();
```

should produce:

```sql
SELECT [b].[Name], CASE
    WHEN [a].[Id] IS NULL THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END, [a].[Name]
FROM [Books] AS [b]
LEFT JOIN [Authors] AS [a] ON [b].[AuthorId] = [a].[Id]
```

**Comment by AradAral** [comment] 2020-09-28 04:42
@maumar Thank you for your help.
I actually thought of the exact same solution as you, but I didn't like the idea of adding an extra ugly property to the DTO just to compensate for this problem, then after beating my head against the wall for quite a few hours, I finally found out that changing `bDto.Author == null` to `bDto.Author.Id > 0` would actually make it work, perhaps strangely enough! It would work without retrieving the `Id` of the author. The generated SQL would be:
```sql
SELECT [b].[Name], CASE
    WHEN [a].[Id] > 0 THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END, [a].[Name]
FROM [Books] AS [b]
LEFT JOIN [Authors] AS [a] ON [b].[AuthorId] = [a].[Id]
```
Pretty much piece of code as the one you just posted, except that `IS NULL` is instead `> 0`.
This is while `bDto.Author.Id == 0` or `bDto.Author.Id != 0` didn't work. It's confusing... :)

But I still think that the EF Core should address this issue, it's not an ideal situation.

**Comment by smitpatel** [comment] 2020-09-28 15:20
> But I still think that the EF Core team should really address this issue and "solve" it, it's not an ideal situation.

For any type which is not in model (like `AuthorDto`), we don't have a way to compare it to null without creating instance of it on client side. If you have a solution (which works for all scenario and not just this query), we would be happy to implement it.

**Comment by AradAral** [comment] 2020-09-28 20:30
@smitpatel I understand that.
Could please explain why `bDto.Author.Id != 0` wouldn't give the desired SQL, while `bDto.Author.Id > 0` would? This is confusing to me.

The SQL that `bDto.Author.Id != 0` would generate:
```
SELECT [b].[Name], CASE
    WHEN ([a].[Id] <> 0) OR [a].[Id] IS NULL THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END, [a].[Name]
FROM [Books] AS [b]
LEFT JOIN [Authors] AS [a] ON [b].[AuthorId] = [a].[Id]
```
The `OR [a].[Id] IS NULL` part is the problem, where does it come from?

**Comment by smitpatel** [comment] 2020-09-28 23:46
> The OR [a].[Id] IS NULL part is the problem, where does it come from? That would make the condition true for all books, with or without author.

`[a].[Id]` is nullable in database, even though the type is non-nullable in client. So when you compare it to `!= 0` you are also asserting that it being null is true result, so it gets added. More accurate check would be `bDto.Author.Id != null`. Writing that in LINQ will complain that you cannot compare int to null so you can add cast to `int?`. All that confusion comes from the point that if `bDto.Author` is null then `bDto.Author.Id` is a null ref exception. So `bDto.Author.Id` is essentially `bDto.Author != null ? b.Dto.Author.Id : (int?)null`

**Comment by AradAral** [comment] 2020-10-02 01:12
@powermetal63 Well, I'm using 5.0 RC1 too but I don't have any the problems you described. I don't exactly know what you're doing, have you written an expression visitor, and if yes, what are you doing in there?

**Comment by powermetal63** [comment] 2020-10-02 02:08
@AradAral The stack trace is bottom up with the the top being the source of exception. As you can see, all I'm doing is calling `ToList()` (on your second query with the aforementioned null check replacements). The exception is thrown by EF Core infrastructure.

**Comment by AradAral** [comment] 2020-10-02 06:37
@powermetal63 Could you share the projection code as well?

**Comment by powermetal63** [comment] 2020-10-02 08:20
@AradAral Looks like at some point of the query processing pipeline EF takes into account the nullability.

In my tests I use the model from @maumar with basically the same queries

```c#
var queryableDto = db.Books.Select(book => new BookDto
{
    Id = book.Id,
    Name = book.Name,
    Genre = book.Genre,
    Author = book.Author == null ? null : new AuthorDto
    {
        Id = book.Author.Id,
        Name = book.Author.Name,
        Age = book.Author.Age,
    },
});

var dtos = queryableDto.Select(bDto => new BookDto
{
    Name = bDto.Name,
    Author = bDto.Author.Name == null ? null : new AuthorDto { Name = bDto.Author.Name }
}).ToList();
```

and just replacing `bDto.Author == null` with aforementioned conditions.

Actually there is one trick which works - using some property with "natural null" support (from CLR types it is `string`) which normally is required in the model. For instance, if `Author.Name` is required, using `bDto.Author.Name == null` eliminates the exceptions and produces the closer to desired SQL

```sql
SELECT [b].[Name], CASE
    WHEN [a].[Name] IS NULL THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END, [a].[Name]
FROM [Books] AS [b]
LEFT JOIN [Authors] AS [a] ON [b].[AuthorId] = [a].[Id]
```

**Comment by AradAral** [comment] 2020-10-02 08:40
@powermetal63 In your first projection (from Book to BookDto), try removing the part `book.Author == null ? null : `, so it would be just `Author = new Author { ...`, and then now in your second projection change `bDto.Author.Name == null` to `bDto.Author.Id == null`, now it should work properly.

**Comment by ajcvickers** [comment] 2020-10-02 18:03
Please feel free to continue the discussion, but for tracking purposes we're closing this issue based on the analysis above.

**Closed** 2022-10-16 19:01 UTC
Labels: closed-by-design, customer-reported
