### ISSUE TITLE
Owned types and key default values unintuitive to configure

### ISSUE THREAD

**Issue by dasMulli** [dotnet/efcore#10308] opened 2017-11-15 22:45 UTC
When including owned types on an entity that used a default value sql, I expect that I can configure these based on the examples given for these features in an intuitive way.

However, it turns out that this causes an error message saying that the owned type and the entity contain a property mapped to the same column with different default values.

### Steps to reproduce

```c#
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public DbSet<Order> Orders { get; set; }
        …
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.HasSequence<int>("OrderNumbers");

            builder.Entity<Order>()
                .Property(o => o.Id)
                .HasDefaultValueSql("NEXT VALUE FOR OrderNumbers");

            builder.Entity<Order>().OwnsOne(p => p.OrderDetails, cb =>
            {
                cb.OwnsOne(c => c.BillingAddress);
                cb.OwnsOne(c => c.ShippingAddress);
            });
        }
    }

    public class Order
    {
        public int Id { get; set; }
        public OrderDetails OrderDetails { get; set; }
    }
    public class OrderDetails
    {
        public StreetAddress BillingAddress { get; set; }
        public StreetAddress ShippingAddress { get; set; }
    }
    public class StreetAddress
    {
        public string Street { get; set; }
        public string City { get; set; }
    }
```

```
> dotnet ef migrations add AddOrders
…
'Order.Id' and 'Order.OrderDetails#OrderDetails.OrderId' are both mapped to column 'Id' in 'Orders' but are configured to use different default values ('NEXT VALUE FOR
OrderNumbers' and '').
```

### Workaround

I've been able to work around this error by specifying the default value for every owned type's shadow id property:

```c#
builder.Entity<Order>()
    .Property(o => o.Id)
    .HasDefaultValueSql("NEXT VALUE FOR OrderNumbers");

builder.Entity<Order>().OwnsOne(p => p.OrderDetails, cb =>
{
    cb.Property<int>("OrderId").HasDefaultValueSql("NEXT VALUE FOR OrderNumbers");
    cb.OwnsOne(c => c.BillingAddress).Property<int>("OrderDetailsOrderId").HasDefaultValueSql("NEXT VALUE FOR OrderNumbers");
    cb.OwnsOne(c => c.ShippingAddress).Property<int>("OrderDetailsOrderId").HasDefaultValueSql("NEXT VALUE FOR OrderNumbers");
});
```

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1709
IDE: CLI 2.0.3

**Comment by smitpatel** [comment] 2017-11-15 23:06
Similar to #9771 
Setting a facet on parent PK which is sharing column with owned type throws exception unless property in owned type also configured with same facet.

**Comment by ajcvickers** [comment] 2017-11-17 21:00
Closing as a duplicate of #9771 with a note added to consider all facets.

**Closed** 2022-10-16 11:58 UTC
Labels: closed-duplicate
