### ISSUE TITLE
dbContext.<Entity>.Update() is clearing references between objects

### ISSUE THREAD

**Issue by DiegoZoracKy** [dotnet/efcore#3948] opened 2015-12-02 03:14 UTC
@rowanmiller Like you asked, i'm creating a new issue for what it seems to be another weird behavior of Update method.

Like i said, the Update method was clearing the reference between objects in some cases. But i've found right now that AsNoTracking is related to this.

In summary: When AsNoTracking is used to fetch the object that is going to be updated, all of its properties are updated correctly but its reference is lost from its relatives. When AsNoTracking is not used, its reference is kept where it should.

You can tell if it is a expected behaviour, but i think it is not.

I've created a code for you to test:

``` javascript
using Microsoft.AspNet.Mvc;
using System.Linq;
using System.Collections.Generic;
using Microsoft.Data.Entity;

public class TestUpdate
{
    public int Id { get; set; }
    public string Name { get; set; }
}
public class AnotherClass
{
    public int Id { get; set; }
    public string Name { get; set; }    
    public virtual List<TestUpdate> TestUpdates { get; set; }
}

public class MyContext : DbContext
{
    public DbSet<TestUpdate> TestUpdates { get; set; }
    public DbSet<AnotherClass> AnotherClass { get; set; }      
}           

[Route("api/[controller]")]
public class TestController : Controller
{
    private MyContext dbContext;

    public TestController(MyContext context)
    {
        dbContext = context;
    }

    [HttpGet("get/anotherclass")]
    public IActionResult GetAnotherClass()
    {
        return new ObjectResult(dbContext.AnotherClass.AsNoTracking().Include(a => a.TestUpdates).ToList());
    }

    [HttpGet("get/testupdate")]
    public IActionResult GetTestUpdate()
    {
        return new ObjectResult(dbContext.TestUpdates.AsNoTracking().ToList());
    }   

    [HttpGet("create")]
    public IActionResult Create()
    {       
        var TU = new TestUpdate();
        TU.Name = "TestUpdate";
        dbContext.TestUpdates.Add(TU);
        dbContext.SaveChanges();        

        var AC = new AnotherClass();
        AC.Name = "AnotherClass";
        AC.TestUpdates = dbContext.TestUpdates.ToList();
        dbContext.AnotherClass.Add(AC);
        dbContext.SaveChanges();

        return new ObjectResult(dbContext.AnotherClass.AsNoTracking().Include(a => a.TestUpdates).ToList());
    }   

    [HttpGet("update")]
    public IActionResult Update()
    {
        var testUpdate = dbContext.TestUpdates.FirstOrDefault();
        testUpdate.Name = "TestUpdate New Name";
        dbContext.TestUpdates.Update(testUpdate);
        dbContext.SaveChanges();

        return new ObjectResult(testUpdate);
    }

    [HttpGet("update/asnotracking")]
    public IActionResult UpdateAsNoTracking()
    {
        var testUpdate = dbContext.TestUpdates.AsNoTracking().FirstOrDefault();
        testUpdate.Name = "TestUpdate New Name AsNoTracking";
        dbContext.TestUpdates.Update(testUpdate);
        dbContext.SaveChanges();

        return new ObjectResult(testUpdate);
    }   
}   
```

Follow these steps to see it happening:

**1. /api/test/create**

You will see that an instance of `AnotherClass` is created, and it has a reference to a `TestUpdate` instance with the property `Name == "TestUpdate"`

**2. /api/test/update**

It will update the property `Name` of `TestUpdate` to `"TestUpdate New Name"`

**3. /api/test/get/anotherclass**

You will find the `AnotherClass` created initially, and the referenced `TestUpdate` will have the new value of `Name` set at the previous step.

**4. /api/test/update/asnotracking**

It will update the property `Name` to `"TestUpdate New Name AsNoTracking"`

_NOTE: The difference here is that `AsNoTracking()` was used to fetch the record that will be updated_

**5. /api/test/get/anotherclass**

Now, we can see that `TestUpdate` is not referenced anymore. **But...**

**6. /api/test/get/testupdate**

The value of `TestUpdate.Name` was updated correctly. It has not created a new object, it just erased its reference found on `AnotherClass`.

**Comment by DiegoZoracKy** [comment] 2015-12-03 13:51
Just to add. The behaviour is the same, using SQLServer or InMemory as adapters.

**Comment by rowanmiller** [comment] 2015-12-03 19:23
@DiegoZoracKy this is actually by design, let me go over the pieces that are at play here.

## Why this is happening

First up, there is no foreign key property in your `TestUpdate` class (i.e. something like `TestUpdate.AnotherClassId`). Because of this, EF introduces a Shadow State property - this is a property whose values are not stored in the CLR class but exist purely in the change tracker (you can actually see and update the value for this property via `dbContext.Entry(myTestUpdate).Property("AnotherClassId").CurrentValue`).

Secondly, AsNoTracking means that the context does not keep any info about the entities you retrieve and is only designed to be used when you are not planning to update those entities (at least not using the same context instance). 

By default things are "tracking" (as opposed to "no tracking"), so the context keeps a track of things. In the following action from your controller, the call to `Update` is actually redundant. Because this is a tracking query, EF knows about the original values for `testUpdate` and it will work out that you changed the `Name` property. In fact, calling `Update` is counter-productive because it will mark all properties as modified. If you hadn't called `Update`, EF would detect that only the `Name` property has been modified and would have sent a smaller `UPDATE` command to the database. Remember that your foreign key value is in shadow state, so in this case the context is keeping track of the value assigned to the `AnotherClassId` property (which isn't part of your CLR class).

```
    [HttpGet("update")]
    public IActionResult Update()
    {
        var testUpdate = dbContext.TestUpdates.FirstOrDefault();
        testUpdate.Name = "TestUpdate New Name";
        dbContext.TestUpdates.Update(testUpdate);
        dbContext.SaveChanges();

        return new ObjectResult(testUpdate);
    }
```

If you contrast this to `UpdateAsNoTracking()`, because it's no tracking, the context does not keep a track of any of the original values (shadow state or the ones stored in the CLR class). Therefore, you do need to call Update to make the context aware of the entity. But, because the value for `AnotherClassId` is not in the CLR class, it is considered null. When you save the entity, all the current values are written to the database - including saving `NULL` in `AnotherClassId`, thus clearing the relationship.

## Solutions

Shadow state foreign keys just do not work well in N-Tier applications. In your example, you happen to have the context instance around and could make use of a tracking query... but in reality you are probably going to query in one action and then update in another - so this will not be the case.
* The best option is just to add an `AnotherClassId` property to `TestUpdate` so that you don't lose the value assigned to it when you serialize/deserialize.
* If you really want a shadow state foreign key, then rather than marking every property as modified (using `Update`) then use dbContext.Entry(myTestUpdate).Property("Name").IsModified = true;` to let EF know which values you want it to update in the database.

**Comment by DiegoZoracKy** [comment] 2015-12-04 01:46
@rowanmiller many thanks for your time explaining this. Now i understand clearly about what was going on with `AsNoTracking` and `.Update`. And i was really calling redundantly `.Update` on the example that i wrote, thanks for pointing me that.

Now i'm just thinking about what you said here: 

*"First up, there is no foreign key property in your TestUpdate class (i.e. something like TestUpdate.AnotherClassId)"*

You are right about `TestUpdate.AnotherClassId`. We can't access in this way. But, SQL Server internally creates a FK in TestUpdate table, right? That is the FK that i was talking about. 

Thank you also for the solution ideas.

**Comment by rowanmiller** [comment] 2015-12-07 18:50
> You are right about  TestUpdate.AnotherClassId . We can't access in this way. But, SQL Server internally creates a FK in TestUpdate table, right? That is the FK that i was talking about. 

It's actually EF that creates this FK - that is the "shadow state FK" I was talking about.

**Comment by rowanmiller** [comment] 2015-12-07 18:51
**Note for triage:** If you call `Update` on an entity with shadow properties, we should consider not marking the shadow ones as modified. That way, they only become modified if you actually specify values for them.

**Comment by rowanmiller** [comment] 2015-12-08 20:39
Discussed but decided the idea of not marking shadow props as modified gets to complex. For example, what if the entity is already tracked (but it may have been tracked by a query and has values... or it could be tracked as part of a graph operation on a detached entity). Also, if we have navigations, then we may have the FK value by getting it from the related entity.

**Closed** 2022-10-16 09:19 UTC
