### ISSUE TITLE
Property 'AutoGenerateBindingRedirects' is incorrectly set to true for some project types

### ISSUE THREAD

**Issue by bekir-ozturk** [dotnet/efcore#28194] opened 2022-06-09 17:29 UTC
**Version:** 3.1.25
**.NET Framework:** 4.8

**Problem:** EFCore.Design package seems to be incorrectly setting the `AutoGenerateBindingRedirects` attribute to `true` in .NET Framework projects.

https://github.com/dotnet/efcore/blob/release/3.1/src/EFCore.Design/build/net461/Microsoft.EntityFrameworkCore.Design.props#L3
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <AutoGenerateBindingRedirects>True</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>True</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
</Project>
```

This property, however, shouldn't be set to true for full framework web projects as MSBuild uses it to determine the correct type of warning to display [here](https://github.com/dotnet/msbuild/blob/d1f5a8af82872bafadb82227ec99f2fcd7b731ec/src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs#L1230-L1241), as also briefly mentioned [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.resolveassemblyreference.supportsbindingredirectgeneration?view=msbuild-17-netcore).

**Impact:**
Having the wrong warning, users are unable to automatically fix their binding redirects and are expected to manually update their web.config files with the correct versions.
Please see the following issue: https://developercommunity.visualstudio.com/t/Double-clicking-on-assembly-version-mism/1549855

**Why is this a problem today?**
Visual Studio currently has [a bug](https://developercommunity2.visualstudio.com/t/MSBuild-targets-from-NuGet-package-are-n/818685).
- In VS 2019: props/targets files in the package dependencies are not included in the build process.
- In VS 2022: props/targets files in the package dependencies are not included in the build process:
  - for the first build that runs after the package is added to the project, or
  - for the first build that runs after the project is loaded

Since this is partially working in 2022, the problems started to arise. Once it is fully fixed, users will always get the wrong warning in full framework web projects.

Please see below how MSBuild does this: https://github.com/dotnet/msbuild/blob/4646eabe3972a84b2a74ed3024bfe1ca8fb1954c/src/Tasks/Microsoft.Common.CurrentVersion.targets#L363-L365 

```xml
 <PropertyGroup>
    <GenerateBindingRedirectsOutputType Condition="'$(OutputType)'=='exe' or '$(OutputType)'=='winexe'">true</GenerateBindingRedirectsOutputType>
    <!-- It would be a breaking change to automatically turn on binding redirects for existing projects, so turn them on only when opting into a new framework. -->
    <AutoGenerateBindingRedirects Condition="'$(AutoGenerateBindingRedirects)' == '' and '$(TargetFrameworkIdentifier)' == '.NETFramework' and '$(TargetFrameworkVersion.TrimStart(vV))' >= '4.7.2'">true</AutoGenerateBindingRedirects>
  </PropertyGroup>
```

**Comment by ajcvickers** [comment] 2022-06-13 11:11
@bekir-ozturk `GenerateBindingRedirectsOutputType` is there because otherwise using the `System.ComponentModel.Annotations` NuGet package doesn't work correctly.

**Comment by bekir-ozturk** [comment] 2022-06-17 14:19
Thanks for the reply!

Do you remember by any chance the reason why it doesn't work?
Is setting this property a fix for the issue or would you say it is rather a workaround?
Could we use the `$(OutputType)` property to conditionally set the `GenerateBindingRedirectsOutputType` in order to get this working for both the `System.ComponentModel.Annotations` package and VS?

**Comment by ajcvickers** [comment] 2022-06-20 20:17
@bekir-ozturk Binding redirects are needed to use `System.ComponentModel.Annotations` with .NET Framework. Are you saying that we should signal this in some other way for web apps? If so, what is that way?

**Comment by ajcvickers** [comment] 2022-07-13 16:33
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-07-13 16:33 UTC
Labels: customer-reported
