### ISSUE TITLE
Client side GroupBy is not supported in EF 3.0

### ISSUE THREAD

**Issue by simpleway2016** [dotnet/efcore#19663] opened 2020-01-22 02:15 UTC
``` C#
 var ret = db.UserInfo.GroupBy(m => m.phone).ToArray();
```
throw exception:
System.InvalidOperationException:“Client side GroupBy is not supported.”

EF Core version: 3.0
Database provider:Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: windows 10
IDE:Visual Studio 2019

**Comment by maumar** [comment] 2020-01-22 23:06
dupe of https://github.com/dotnet/efcore/issues/17068

**Comment by NetMage** [comment] 2020-01-23 01:40
@simpleway2016 This doesn't have a SQL translation benefit since no server side aggregation is performed; you can just put `AsEnumerable()` before the `GroupBy`.

**Closed** 2022-10-16 18:07 UTC
Labels: closed-duplicate, customer-reported
