### ISSUE TITLE
Built In Scalar Function Mapping 

### ISSUE THREAD

**Issue by tlejmi** [dotnet/efcore#19171] opened 2019-12-05 10:13 UTC
For example, if EF Core 2.2 couldn’t translate a predicate in a Where() call, it executed an SQL statement without a filter, transferred all the rows from the database, and then filtered them in-memory:

```
var specialCustomers = 
  context.Customers
    .Where(c => c.Name.StartsWith(n) && IsSpecialCustomer(c));
```
That may be acceptable if the database contains a small number of rows but can result in significant performance issues or even application failure if the database contains a large number or rows.
To evaluate a predicate condition on the client as in the previous example, developers now need to explicitly switch evaluation of the query to LINQ to Objects:
```

var special customers =
  context.Customers
    .Where(c => c.Name.StartsWith(n)) 
    .AsEnumerable() // switches to LINQ to Objects
    .Where(c => IsSpecialCustomer(c));

```

EntityFramework Core, Create and Map , scalar functions in the database to complicated builtIn 
 methods and well-known methods used by strings and numbers ...  ,  and allow developers to easily create and map scalar function, to methods. So a lot of client-side evaluation will be evaluated in the database.

**Comment by roji** [comment] 2019-12-05 14:35
@tlejmi can you clarify exactly what you're asking for?

If you're looking to define a custom function and map it to SQL, EF Core already fully supports that. We're lacking proper documentation for this (https://github.com/aspnet/EntityFramework.Docs/issues/500), but see [this comment with samples](https://github.com/aspnet/EntityFrameworkCore/issues/11295#issuecomment-373852015).

**Comment by tlejmi** [comment] 2019-12-07 09:45
what I meant is that Entity Framework will map by default c# built-in functions. 
Like mapping c# string.Reverse()  to TSQL  REVERSE ( string_expression )   so that the reverse function will not be evaluated in client-side .  and the same for the well known number and string function used as filters

**Comment by roji** [comment] 2019-12-07 12:41
@tlejmi I'm still not clear on what you're asking. EF Core knows how to translate certain methods and members, and more translations can be added if they are needed. Adding translations is not an automatic/transparent thing, and must be done manually for each case.

Are you specifically asking that we add translation support for string.Reverse? If so, you open an issue specifically for that. Otherwise you can take a look at [this class](https://github.com/aspnet/EntityFrameworkCore/blob/f780a3aef9839131aef118cd73dda625e22fb980/src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs), which defines all the string method translations

**Comment by ajcvickers** [comment] 2019-12-16 17:18
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 15:00 UTC
Labels: closed-no-further-action, customer-reported
