### ISSUE TITLE
unable to add Enitity framework package in  Class Library Project targeting .Net Standard 1.4

### ISSUE THREAD

**Issue by josephjoychristopher** [dotnet/efcore#8936] opened 2017-06-22 11:22 UTC
unable to add Enitity framework package in  Class Library Project targeting .Net Standard 1.4.  Hence, i wount be able to decouple the EF in Class library

**Comment by ajcvickers** [comment] 2017-06-22 15:29
@josephjoychristopher What version of EF Core are you using?

**Comment by ajcvickers** [comment] 2017-06-30 16:11
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:09 UTC
Labels: closed-could-not-reproduce
