### ISSUE TITLE
Globally disable the creation of foreign keys during migrations

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/efcore#27382] opened 2022-02-06 00:15 UTC
When running `context.Database.EnsureCreatedAsync()`, it does the right thing by default and creates foreign keys based on my entities.

Not all the tables in the project I'm working on currently are ready to have these constraints enabled.  Is there any way I can globally disable foreign keys somewhere when configuring my context, just to mimic what I have in other environments?

**Comment by ajcvickers** [comment] 2022-02-07 11:24
Duplicate of #15854.

**Closed** 2022-10-16 20:25 UTC
Labels: closed-duplicate, customer-reported
