### ISSUE TITLE
The string argument 'migrationId' cannot be empty.

### ISSUE THREAD

**Issue by Varorbc** [dotnet/efcore#24375] opened 2021-03-11 02:04 UTC
### Include stack traces

```
System.ArgumentException: The string argument 'migrationId' cannot be empty.
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.RemoveMigration(String projectDir, String rootNamespace, Boolean force, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.RemoveMigration(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.RemoveMigrationImpl(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.RemoveMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Include provider and version information

EF Core version:5.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system:win 10
IDE: Visual Studio 2019 16.9

**Comment by ajcvickers** [comment] 2021-03-11 22:58
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Varorbc** [comment] 2021-03-12 01:58
# step 1
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.4" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.4" />
  </ItemGroup>

</Project>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace ClassLibrary1
{
    public class TestDbContext : DbContext
    {
        public TestDbContext(DbContextOptions<TestDbContext> options)
            : base(options)
        {
        }
    }

    public class TestDbContextFactory : IDesignTimeDbContextFactory<TestDbContext>
    {
        public TestDbContext CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<TestDbContext>();
            optionsBuilder.UseSqlServer("");

            return new TestDbContext(optionsBuilder.Options);
        }
    }
}

```

# step 2
```
dotnet ef migrations add InitCreate
```

# step 3
Create a table for the target database 

```
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [NVARCHAR](150) NOT NULL,
	[ProductVersion] [NVARCHAR](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
```

# step 4
I don’t know why there are empty data in the production database 

```
INSERT INTO [dbo].[__EFMigrationsHistory]([MigrationId],[ProductVersion])VALUES(' ','3.1.6')
```

# step 5
```
dotnet ef migrations remove
```

**Comment by ajcvickers** [comment] 2021-03-16 16:26
@Varorbc You are giving the migration an empty ID:

> `INSERT INTO [dbo].[__EFMigrationsHistory]([MigrationId],[ProductVersion])VALUES(' ','3.1.6')`

As the exception message says, the migration ID cannot be empty.

**Comment by Varorbc** [comment] 2021-03-17 00:55
@ajcvickers The empty ID is not manually inserted by me, I suspect it is the abnormal data of the migration. When the tool generates the migration, can it filter out such empty data? 

In addition, I have a question, I hope you can help answer it, is the migration not based on a local snapshot, but based on the migration history of the database?

**Comment by ajcvickers** [comment] 2021-03-18 17:03
@Varorbc

> The empty ID is not manually inserted by me, I suspect it is the abnormal data of the migration.

Given this, can you provide the steps that lead to this abnormal migration, since this seems to be the root of the problem?

**Comment by Varorbc** [comment] 2021-03-19 00:10
From the data point of view, it was inserted in version 3.1.6. It's too long to reproduce

**Comment by ajcvickers** [comment] 2021-03-19 14:53
Closing this as we cannot reproduce the scenario that created a bad migration ID.

**Closed** 2022-10-16 19:27 UTC
Labels: closed-could-not-reproduce, customer-reported
