### ISSUE TITLE
Enable optional relationships when using entity splitting

### ISSUE THREAD

**Issue by bdebaere** [dotnet/efcore#9773] opened 2017-09-12 08:17 UTC
Currently in my company we have to create CRUD stored procedures to be able to work with our entities in Entity Framework 6. We would like to step away from this approach when moving to Entity Framework Core.

Please implement entity splitting with optional relations.

Thank you.

**Comment by ajcvickers** [comment] 2017-09-14 01:16
Duplicate of #620. Added a note there to consider optional relationships.

**Closed** 2022-10-16 11:49 UTC
Labels: closed-duplicate
