### ISSUE TITLE
Order for Creating Migrations is incorrect

### ISSUE THREAD

**Issue by pterevinto** [dotnet/efcore#5551] opened 2016-05-27 14:19 UTC
Whenever you rename a table, the order of the migration steps is incorrect. 
This is the scenario today:
1. Drop Foreign Keys **old** Table Name
2. Drop Primary Keys **old** Table Name
3. Add Primary Keys **new** Table Name
4. Add Foreign Keys **new** Table Name
5. Rename Table from **old** to **new**

If i'm not wrong, this is coming from [_Microsoft.EntityFrameworkCore.Relational\Migrations\Internal\MigrationsModelDiffer.cs: 219 to 232_ 
](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs#L219)

Current code is:
`return dropForeignKeyOperations
                .Concat(dropOperations)
                .Concat(dropColumnOperations)
                .Concat(dropTableOperations)
                .Concat(ensureSchemaOperations)
                .Concat(createSequenceOperations)
                .Concat(createTableOperations)
                .Concat(addColumnOperations)
                .Concat(alterOperations)
                .Concat(addForeignKeyOperations)
                .Concat(renameColumnOperations)
                .Concat(renameOperations)
                .Concat(renameTableOperations)
                .Concat(leftovers)
                .ToArray();`

Should be:
`return dropForeignKeyOperations
                .Concat(dropOperations)
                .Concat(dropColumnOperations)
                .Concat(dropTableOperations)
                .Concat(ensureSchemaOperations)
                .Concat(renameTableOperations)
                .Concat(renameOperations)
                .Concat(renameColumnOperations)
                .Concat(createSequenceOperations)
                .Concat(createTableOperations)
                .Concat(addColumnOperations)
                .Concat(alterOperations)
                .Concat(addForeignKeyOperations)
                .Concat(leftovers)
                .ToArray();`

**Comment by smitpatel** [comment] 2016-05-27 16:55
duplicate of #3990 
Already fixed in #5480

**Closed** 2022-10-16 09:43 UTC
