### ISSUE TITLE
Stored Procedures - every time I scaffold they dissapear - can you make onmodelbuilder partial

### ISSUE THREAD

**Issue by jcolon1984** [dotnet/efcore#19140] opened 2019-12-03 08:58 UTC
Every time I scaffold my store procedures are erased since the scaffold does not do this for me and my HasNoKey() has to be added manually. 
For example suppose I have two stored procedures : GetDailyRecommendationResponse, GetTracksResponse

```
  public DbSet<GetDailyRecommendationResponse> DailyRecommendationsStoredProcedure { get; set; }
        public DbSet<GetTracksResponse> GetTracksProcedure { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetDailyRecommendationResponse>(entity =>
            {
                entity.HasNoKey();
            });
            modelBuilder.Entity<GetTracksResponse>(entity =>
            {
                entity.HasNoKey();
            });
```

The scaffold command Scaffold-DbContext erases my implementation.

If the method was partial I think I could declare it in a separate file and it would not get in the way of the scaffold.

**Comment by ajcvickers** [comment] 2019-12-03 23:32
Duplicate of #12245

**Closed** 2022-10-16 14:59 UTC
Labels: customer-reported
