### ISSUE TITLE
Dotnet Ef is missing on Ubuntu 16.10 after including Microsoft.EntityFrameworkCore.Tools.DotNet package

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#7309] opened 2016-12-24 09:39 UTC
Been getting this error on Ubuntu 16.10 server with Dotnet version at 1.0.0-preview2-1-003177 in the **same directory where project.json is located and already restored**:

> No executable found matching command "dotnet-ef"

I've already included the following dependencies and restored project with:

    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final",
    "Microsoft.NETCore.App": "1.1.0",

I've already included the runtime identifier for Ubuntu in project.json. All packages are at the latest possible. Website is able to run, just can't do migration. I'm running out of ideas.

**Comment by CsharpOnLinuxDev** [comment] 2016-12-25 10:58
A workaround for anyone who is unable to get Dotnet EF to work at all:

http://stackoverflow.com/questions/31710038/how-to-apply-migrations-from-code-ef7#answer-39165764

**Comment by divega** [comment] 2017-01-06 20:11
`Microsoft.EntityFrameworkCore.Tools.DotNet` is supposed to go in the tools section (DotNetCliToolReference items in MSBUILD based projects) not as a dependency.

**Comment by CsharpOnLinuxDev** [comment] 2017-01-07 01:54
Doesn't work either.

**Comment by CsharpOnLinuxDev** [comment] 2017-01-08 07:17
@divega I've created a project from scratch and tried everything including the suggestion you provided above and still having no luck.

**Comment by divega** [comment] 2017-01-09 22:41
@CsharpOnLinuxDev please provide a repro project and we will take a look.

**Comment by rowanmiller** [comment] 2017-01-27 19:25
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 10:48 UTC
