### ISSUE TITLE
[EF Core 6 + OData] Calculate total count: Nullable object must have a value exception

### ISSUE THREAD

**Issue by tony6636** [dotnet/efcore#29566] opened 2022-11-15 14:37 UTC
Hi, I'm trying to retrieve the grouped rows from the SQL view with using OData filters. The problem is, I'm getting the exception when the `CountAsync`  for calculating the total rows based on the search criteria is being executed (the 2nd line in the `FilterAsync` method). The 1st line retrieves 10 rows, so the query works fine.

it does not matter whether I use any filters or not, the result is the same

url
```
http://localhost:9081/api/customer
```

DbContext Definition
```
public class MyDbContext : DbContext
{
    public DbSet<DetailedCustomerView> list_detailed_customers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<DetailedCustomerView>()
            .ToView("list_detailed_customers")
            .HasKey(t => t.CustomerId);
    }
}
```

view entity
```
public class DetailedCustomerView
{
    [Column("customer_id")]
    public Int64 CustomerId { get; set; }

    [Column("group_id")]
    public Int64 GroupId { get; set; }
}
```

usage
```
dbContext.list_detailed_customers
    .GroupBy(x => x.CustomerId)
    .Select(cusromerGroup => new CustomerDetailedListDto
    {
       CustomerId = cusromerGroup.First().CustomerId,
       GroupIds = cusromerGroup.Select(x => x.GroupId)
    })
    .FilterAsync(request.Options, cancellationToken);
```

CustomerDetailedListDto definition
```
public struct CustomerDetailedListDto
{
    public Int64 CustomerId { get; set; }
    public IEnumerable<Int64> GroupIds { get; set; }
}
```

ODataFilter extension
```
public static async Task<QueryResult<T>> FilterAsync<T>(this IQueryable<T> query, ODataQueryOptions options, CancellationToken cancellationToken)
{
    List<T> items = await query.ApplyTo(options, AllowedQueryOptions.None).ToListAsync(cancellationToken);
    Int32 totalCount = await query.ApplyTo(options, AllowedQueryOptions.Skip | AllowedQueryOptions.Top | AllowedQueryOptions.OrderBy).CountAsync(cancellationToken);

    return new QueryResult<T>(items, totalCount);
}
```

The View `list_detailed_customers` definition (a simplified version)
```
SELECT 
    1 AS customer_id,    
    1 AS group_id
FROM customer
UNION
SELECT
    1 AS customer_id,    
    2 AS group_id
FROM customer
```

generated query when retrieving the rows
```
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 6.0.6 initialized 'MyDbContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL:6.0.5+9d79af6e2586d5d28da253ac075706a5575a1743' with options: MaxPoolSize=1024
warn: Microsoft.EntityFrameworkCore.Query[10102]
      The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results. If the 'Distinct' operator is used after 'OrderBy', then make sure to use the 'OrderBy' operator after 'Distinct' as the ordering would otherwise get erased.
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (80ms) [Parameters=[@__TypedProperty_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
      SELECT t.c, t.customer_id, l1.group_id, l1.customer_id
      FROM (
          SELECT (
              SELECT l0.customer_id
              FROM list_detailed_customers AS l0
              WHERE l.customer_id = l0.customer_id
              LIMIT 1) AS c, l.customer_id
          FROM list_detailed_customers AS l
          GROUP BY l.customer_id
          LIMIT @__TypedProperty_0
      ) AS t
      LEFT JOIN list_detailed_customers AS l1 ON t.customer_id = l1.customer_id
      ORDER BY t.customer_id
```

For calculating the total count number, I don't see any generated sql query

### Stack trace with error message

Critical error occured: Nullable object must have a value.

```
     at System.Nullable`1.get_Value()
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ClientProjectionRemappingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ClientProjectionRemappingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyProjection(Expression shaperExpression, ResultCardinality resultCardinality, QuerySplittingBehavior querySplittingBehavior)
   at Microsoft.EntityFrameworkCore.Query.Internal.SelectExpressionProjectionApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.CountAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at MyProject.Lib.OData.FilterExtension.FilterAsync[T](IQueryable`1 query, ODataQueryOptions options, CancellationToken cancellationToken)
   at MyProject.Core.Mediator.Dispatching.Dispatcher.Dispatch[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Web.Controllers.CustomerController.GetList(ODataQueryOptions options)
   at lambda_method2589(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at MyProject.Core.Web.Middlewares.HeadersHandlerMiddleware.Invoke(HttpContext httpContext)
   at MyProject.Core.Web.Middlewares.ExceptionHandlerMiddleware.Invoke(HttpContext httpContext)
```

EF Core version: 6.0.6.0
Database provider:

- Npgsql.EntityFrameworkCore.PostgreSQL:6.0.5
- Microsoft.AspNetCore.OData 8.0.11

Target framework: NET 6.0
Operating system: Windows 11

**Comment by ajcvickers** [comment] 2022-11-19 11:01
@tony6636 Please try this with EF Core 7 and report back if you are still seeing an issue.

**Comment by ajcvickers** [comment] 2022-11-30 13:23
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-11-30 13:23 UTC
Labels: customer-reported
