### ISSUE TITLE
Change the default decimal type mapping

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#6965] opened 2016-11-07 23:47 UTC
Currently we map to decimal(18, 2), however this can cause data-loss due to silent truncation, see #6835.
If changed to decimal(38, 28) no CLR decimal will be silently truncated, as they have at most 29 significant digits and overflows are errors in SQL Server.

**Comment by ajcvickers** [comment] 2016-11-07 23:53
If we are doing this to prevent data loss, do we attempt to do it for other types that have similar issues? Like strings? If so, what string mapping will always work and will never result in data loss? If not, why are decimals different than other types?

The resultant column will be much wider, which is the main reason why we didn't do this originally. (I also did some experiments where whatever type mapping I used I was able to get some loss of data, but I may have made a mistake with this.)

Also, this will result in a migration for all existing databases,

**Comment by divega** [comment] 2016-11-08 00:13
@ajcvickers I thought we already used a default (`max`) that avoids data loss for string columns that are not keys. What am I missing? 

Besides, saving a string that doesn't fit in a string column causes an error in SQL Server, while extra digits after the decimal separator that don't fit in the scale are silently truncated. 

A decimal with a precision of 38, 28 takes 17 bytes in SQL Server, which is almost twice as much as current default which takes 9 bytes. We would keep the warning that @AndriySvyryd in the existing PR for this reason.

When we did some investigation to decide what to use for `DecimalFormatConst` to produce literal decimals without data loss and the results were consistent with @AndriySvyryd's finding. Worth double-checking probably.

**Comment by AndriySvyryd** [comment] 2016-11-08 00:17
@divega We use nvarchar(450) and varbinary(900) as the defaults if the columns are part of an index or key.
We could use nvarchar(max) and varbinary(max) in the temporary table, but it's unnecessary since truncation is an error as you said.

**Comment by ajcvickers** [comment] 2016-11-08 17:40
@AndriySvyryd That sounds acceptable for strings. Why can't we use decimal(38, 28) in the temporary table to avoid data loss in this case instead of changing the default mapping?

**Comment by ajcvickers** [comment] 2016-11-08 17:50
@AndriySvyryd With regard to strings, there will only be an exception at a point where the string or binary value happens to be too long, right? Which means an application could be running in production for a long time before the issue is encountered, right? Also, how easy is the exception to understand given that the database has wide enough columns so the application developer did nothing wrong other than not understanding this interaction between our type mapping conventions and the update pipeline in batching mode? Maybe we should issue a warning for string and binary columns as well?

**Comment by AndriySvyryd** [comment] 2016-11-08 19:03
@ajcvickers decimal(38, 28) cannot represent the values between 10^9 and 10^14 -1, but decimal(18, 2) can, so it might cause an error if we used just for the temporary table.
While the truncation errors could be tricky to diagnose, they will not result in silent data loss and as I said we could just use the max length types for the temporary table to avoid this, but potentially taking a tiny perf hit.
If we issued a warning for strings and binaries it would become less useful and more likely to be suppressed.

**Comment by ajcvickers** [comment] 2016-11-08 19:17
@AndriySvyryd So the reason to change the default to (38, 28) (the other issue) is not because it can hold anything that a .NET decimal can throw at it, but because it will cause an exception if it can't hold something that .NET decimal throws at it? And if we used it in the temporary table, then it might throw when if we used the real data type of the column, then it would succeed?

If so, then why not:
* If the data type of the column has been explicitly set, then use it.
* If the data type has been inferred, then:
 * For strings/binaries, if max length has been set, then use it to create data type, otherwise use (max) types in the temporary table.
 * For decimal, use (38, 28) in the temporary table

Would the only case that would throw then be decimals with very large values for which an explicit type has not been set?
Would any case still silently lose data?

**Comment by AndriySvyryd** [comment] 2016-11-08 19:21
@ajcvickers Correct, but we don't have configuration source information in the update pipeline.

**Comment by ajcvickers** [comment] 2016-11-08 19:23
@AndriySvyryd What is it that we need configuration source for? Do we ever set max length or unicode by convention?

**Comment by AndriySvyryd** [comment] 2016-11-08 19:33
@ajcvickers I thought we did, but no.
However using a different type for decimal in the temporary table will result in different behavior (error vs no error) depending on whether the command is batched or not.

**Comment by ajcvickers** [comment] 2016-11-08 19:41
@AndriySvyryd I think we should discuss in triage.

**Comment by rowanmiller** [comment] 2016-11-14 19:04
Closing as we decided not to change the default

**Closed** 2022-10-16 10:41 UTC
Labels: closed-out-of-scope
