### ISSUE TITLE
[HELP] Rollback - Help to find a solution

### ISSUE THREAD

**Issue by PedroVFerreira** [dotnet/efcore#9717] opened 2017-09-07 00:52 UTC
Hi.

I'm developing a WebApi in .Net Core with EF Core.

My project is structured with services and repositorys. Each business entity has your own service and your own repository (each repo has a context that was injected. ).

The problem is when I need to roolback some actions that ocurred in diferent services. Example, when I'm creating a new Event, I need to create a new Billing and new Info. So, I call each server (BillingService and InfosService) in a method at EventService. 

If I have a business exception, I need to rollback it.

```c#
// Example in Event Service
EventDTO  event = null;
BillingDTO bill = null;
InfoDTO   info = null;
try{
  event = CreateNewEvent(args);
  bill = _billingService.CreateEventBilling(event);
  info =_infoService.CreateEventInfo(event);
}
catch(Exception ex){
 // when throw excpetion, I need rollback everything

}

```
I found out a way each is deleting manually each item, like this:

```c#
// Example in Event Service
EventDTO event = null;
BillingDTO bill = null;
InfoDTO   info = null;
try{
  event = CreateNewEvent(args);
   bill = _billingService.CreateEventBilling(event);
  info =_infosService.CreateEventInfo(event);
}
catch(Exception ex){
 
  if(event != null)
    DeleteEvenr(eventt);
  if(bill != null)
     _billingService.DeleteBilling(bill);
  if(info != null)
    _infosService.DeleteInfos(info);
}

```

But, I have gotten the err :
"cannot be tracked because another instance of this type with the same key is already being tracked."
### Note
The method that adds every DTO : 
```c#
 public TEntityDTO Add(TEntityDTO entity)
        {
            var mappedEntity = Mapper.Map<TEntity>(entity);
            Db.Set<TEntity>().Add(mappedEntity);
            Db.SaveChanges();
            return Mapper.Map<TEntityDTO>(mappedEntity);
        }
```

**Comment by smitpatel** [comment] 2017-09-07 19:41
@PedroVFerreira - There is not enough code for us to reproduce this issue to find the cause of error. Please provide a complete repro code which we can run.

**Comment by ajcvickers** [comment] 2017-09-13 19:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:48 UTC
Labels: closed-could-not-reproduce
