### ISSUE TITLE
Microsoft.EntityFrameworkCore.SqlServer 3.1.[4-18] stop azure functions for logging dependency

### ISSUE THREAD

**Issue by HenrikSommer-eng** [dotnet/efcore#25613] opened 2021-08-20 12:20 UTC
## File a bug

We have updated our Azure functions to use Microsoft.EntityFrameworkCore.SqlServer 3.1.18
And have discovered that in Application Insights that the function no longer logs its dependency.

### Code example:

This code create a simple function that connect to a database.
If you downgrade the nuget package to 3.1.3 Application Insights will show a timeline:
![image](https://user-images.githubusercontent.com/60382556/130231544-7cc85e33-23da-4184-82ff-5f711cd7cab8.png)

But if you upgrade to 3.1.4 or 3.1.18 the timeline look like this:
![image](https://user-images.githubusercontent.com/60382556/130231627-1127a561-222f-40a9-8702-c6eb32112d83.png)

Note that in the example it is only Sql server we are missing a dependency log for, but if we use ServiceBus and Storage account those are also missing.

```C#
using System;
using System.IO;
using System.Threading.Tasks;
using EFCoreFunctionBug;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

[assembly: FunctionsStartup(typeof(Startup))]

namespace EFCoreFunctionBug
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddDbContext<EfFunctionBugDbContext>(options =>
                SqlServerDbContextOptionsExtensions.UseSqlServer(options, Environment.GetEnvironmentVariable("DefaultConnection")!));
        }
    }

    public class ![image](https://user-images.githubusercontent.com/60382556/130231544-7cc85e33-23da-4184-82ff-5f711cd7cab8.png)
    {
        public EfFunctionBugDbContext DbContext { get; }
        public ILogger<Function1> Log { get; }

        public Function1(EfFunctionBugDbContext dbContext, ILogger<Function1> log)
        {
            DbContext = dbContext;
            Log = log;
        }

        [FunctionName("Function1")]
        public async Task<IActionResult> Get(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest request)
        {
            Log.LogInformation("C# HTTP trigger function processed a request.");

            var data = await DbContext.Datas.FirstOrDefaultAsync();

            string responseMessage = data?.Name ?? "not found";

            return new OkObjectResult(responseMessage);
        }
    }

    public class Data
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class EfFunctionBugDbContext : DbContext
    {
        public EfFunctionBugDbContext(DbContextOptions<EfFunctionBugDbContext> options) : base(options)
        {
        }

        public DbSet<Data> Datas { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Data>(b =>
            {
                b.ToTable("Data");
                b.HasKey(p => p.Id);
                b.Property(p => p.Name).IsRequired();
            });
        }
    }
}

```

### Include provider and version information

EF Core version: 3.1.[4-18]
Database provider: (Azure SQL database )
Target framework: (netcoreapp3.1)
FUNCTIONS_EXTENSION_VERSION: ~3

**Comment by ajcvickers** [comment] 2021-08-20 12:31
Duplicate of #25339. This needs to be reported on the Azure Functions repo.

**Closed** 2022-10-16 19:43 UTC
Labels: closed-duplicate, customer-reported
