### ISSUE TITLE
Can not use EF core 3.1 in .net 6

### ISSUE THREAD

**Issue by ponyspeed888** [dotnet/efcore#28163] opened 2022-06-06 06:03 UTC
Try to use EF Core 3.1 in a .net standard library.  When using this library in .net 6 project I got this error :

System.TypeInitializationException
  Message=The type initializer for 'Microsoft.EntityFrameworkCore.Query.QueryableMethods' threw an exception.

Expected : There should be no issue as .net standard 2.0 is supported by all .net core version and EF Core 3.1 target .net standard 2.0

**Comment by ajcvickers** [comment] 2022-06-06 07:12
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ponyspeed888** [comment] 2022-06-07 03:31
[PonyEFCore31Bug.zip](https://github.com/dotnet/efcore/files/8849897/PonyEFCore31Bug.zip)
Please see attached solution, it works on .net 5, failed on .net 6, please see the readme.txt

thanks.

**Comment by ajcvickers** [comment] 2022-06-08 10:21
@ponyspeed888 This is a duplicate of #24002, which is fixed in 3.1.14. Your application is using 3.1.10, and so does not have this fix. It is important to always use the latest patch version of a release to get important fixes, including those that might impact security.

**Closed by ajcvickers** 2022-06-08 10:21 UTC
Labels: closed-duplicate, customer-reported
