### ISSUE TITLE
configured maxlength not applied to database field

### ISSUE THREAD

**Issue by luisrudge** [dotnet/efcore#1694] opened 2015-02-24 20:13 UTC
I'm setting up field length restrictions on the model builder:
![image](https://cloud.githubusercontent.com/assets/941075/6358134/32e20c62-bc48-11e4-9bc7-f8583853d1e7.png)

The migration is using this restrictions:
![image](https://cloud.githubusercontent.com/assets/941075/6358137/3b9b3090-bc48-11e4-8a6e-b80473e29f28.png)

But the snapshot doesn't have that:
![image](https://cloud.githubusercontent.com/assets/941075/6358141/4575466e-bc48-11e4-8317-8702a324adc1.png)

And the migration designer doesn't have that too:
![image](https://cloud.githubusercontent.com/assets/941075/6358145/4d20d73e-bc48-11e4-88a5-f5716421d5eb.png)

**Comment by bricelam** [comment] 2015-02-24 20:41
This is a dupe of #882

**Comment by luisrudge** [comment] 2015-02-24 22:02
Sorry I didn't looked before.

**Closed** 2022-10-16 08:52 UTC
