### ISSUE TITLE
The related entities cannot be loaded with many-to-many relationship

### ISSUE THREAD

**Issue by alugili** [dotnet/efcore#6309] opened 2016-08-12 13:06 UTC
### Steps to reproduce

Copy paste my code below
### The issue

I have defined many-to-many relationship(Libraries, Books) as shown in my code below (one library has n ..books). The data is correctly stored in the database but when I try to load the library I get always an empty collection of the joining table.

The code is ready for copy/paste for you:

```
class Program
  {
    public class Library
    {
      [Key]
      public int LibraryId { get; set; }
      public ICollection<Library2Book> Library2Books { get; set; } = new Collection<Library2Book>();
    }

    public class Book
    {
      [Key]
      public int BookId { get; set; }
      public ICollection<Library2Book> Library2Books { get; set; } = new Collection<Library2Book>();
    }

public class Library2Book
    {
      [Key]
      public int BookId { get; set; }
      public Book Book { get; set; }

      [Key]
      public int LibraryId { get; set; }
      public Library Library { get; set; }
    }

    public class MyDbContext : DbContext
    {
      public DbSet<Book> Books { get; set; }
      public DbSet<Library> Libraries { get; set; }

      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      {
        optionsBuilder.UseSqlServer(@"Server=.\;Database=EFTutorial;integrated security=True;");
        base.OnConfiguring(optionsBuilder);
      }

      protected override void OnModelCreating(ModelBuilder modelBuilder)
      {
        modelBuilder.Entity<Library2Book>().HasKey(k => new { k.LibraryId, k.BookId });

        modelBuilder.Entity<Library2Book>()
          .HasOne(x => x.Book)
          .WithMany(x => x.Library2Books)
          .HasForeignKey(x => x.BookId);

        modelBuilder.Entity<Library2Book>()
          .HasOne(x => x.Library)
          .WithMany(x => x.Library2Books)
          .HasForeignKey(x => x.LibraryId);
          base.OnModelCreating(modelBuilder);
      }
    }

   static void Main(string[] args)
    {
      using (var myDb = new MyDbContext())
      {
        // Create Db
        myDb.Database.EnsureCreated();

        // I will add two books to one library
        var book1 = new Book();
        var book2 = new Book();

        // I create the library 
        var lib = new Library();

        // I create two Library2Book which I need them 
        // To map between the books and the library
        var b2lib1 = new Library2Book();
        var b2lib2 = new Library2Book();

        // Mapping the first book to the library.
        b2lib1.Book = book1;
        b2lib2.Library = lib;

        // I map the second book to the library.
        b2lib2.Book = book2;
        b2lib2.Library = lib;

        // Linking the books (Library2Book table) to the library
        lib.Library2Books.Add(b2lib1);
        lib.Library2Books.Add(b2lib2);

        // Adding the data to the DbContext.
        myDb.Libraries.Add(lib);

        myDb.Books.Add(book1);
        myDb.Books.Add(book2);

        // Save the changes and everything should be working!
        myDb.SaveChanges();
      }
    }
  }
```

The Code result in SQL Server with help of SSM:

```
Tables:   Books    |   Libraries      |    Library2Book  |
                  1       |        1           |      1   /   1         |
                  2       |        -           |       1  /    2         |
```

After that I'm tryting to load the library like that:

```
myDb.Libraries.Include(x => x.Library2Books).ThenInclude(x => x.Book);
var lib = myDb.Libraries.First();
if (lib.Library2Books.ToList().Count == 0)
{
    // Error No Entities in Collection But Db contains 2 Library2Books for this library
}

```

// The problem!?
Library2Books  Count always == 0

```
Exception message:
Stack trace: n.a
```
### Further technical details

EF Core version:  Version="1.0.0" TargetFramework="net461"
Operating system:  Windows 7
Visual Studio version:  2015

**Comment by ajcvickers** [comment] 2016-08-12 17:39
Note for triage: I was able to reproduce this. It looks like the Include call is not working. If all of the entities are loaded into the context explicitly, then everything is hooked up appropriately.

**Comment by divega** [comment] 2016-08-12 19:04
**Triage:** we believe this is a candidate for 1.0.1.

**Comment by smitpatel** [comment] 2016-08-12 21:07
```
myDb.Libraries.Include(x => x.Library2Books).ThenInclude(x => x.Book);
var lib = myDb.Libraries.First();
if (lib.Library2Books.ToList().Count == 0)
{
    // Error No Entities in Collection But Db contains 2 Library2Books for this library
}

```
If the query is written exactly as above then `LibraryBooks` collection will be empty. The query which has `Include` call does not have `ToList()` or any other call to make that query actually evaluated in EF. Hence `myDb.Libraries.First();` will have none of the navigations loaded.

**Comment by divega** [comment] 2016-08-12 22:58
Thanks @smitpatel. 

@alugili I imagine you may have expected the calls to `Include()`/`ThenInclude()` to change `myDb.Libraries` so that all subsequent queries on it would popullate those navigation properties, but `Include()` works like other LINQ operators: it doesn't affect the source query but the behavior of the query it returns. 

cc @ajcvickers to make sure he is seeing the same thing. If that is the case we can close.

**Comment by divega** [comment] 2016-08-15 01:53
Closing for now, as we believe the behavior is by design. @alugili feel free to reopen if you still see issues after changing your code to `Include()`, `ThenInclude()` and `First()` in the same query.

**Closed** 2022-10-16 09:54 UTC
Labels: type-bug, closed-by-design
