### ISSUE TITLE
DBContext reusing object from previous requests

### ISSUE THREAD

**Issue by mantasaudickas** [dotnet/efcore#10097] opened 2017-10-17 10:02 UTC
I have a linq query which inside select creates a complex object as a part of result:

```csharp
    var addresses = (from customer in _db.Customers
        join address in _db.CustomerAddresses on customer.CustomerId equals address.CustomerId
    where customer.CustomerId == customerId
    select new
    {
        Address = new MainAddress
        {
            CustomerId = customer.CustomerId,
            CountryIso3Code = address.CountryIso3Code,
            City = address.City,
            Contacts = new CustomerContact()  // <<-- HERE is the problem
        }
    }).ToList();
```

Please notice Contacts = new CustomerContact()...
It seems like only first query gets a new object while others are reusing that object somehow even when there are different requests. I do not use or add caching here.

Expected result: new empty object after each execution.

### Steps to reproduce
I have created a solution which is reproducing behavior.

[efcoredbcontext.zip](https://github.com/aspnet/EntityFrameworkCore/files/1390623/efcoredbcontext.zip)

DBContext, Repository and Service are scoped instances. However it does not matter if I create them per scope, transient or simply using new statements - result is the same.

Solution consists of 4 projects:
ASP.NET Core 2.0, entry point CustomersController.GetMainAddress method (after start, just hit refresh and watch "contacts" property).
.NET Core 2.0 unit test project with tests using DbContext in various ways.
.NET Core 1.1 unit test project with tests using DbContext in various ways.
.NET 4.6.1 with Entity Framework 6, which generates exception during execution:
The entity or complex type 'EFCoreDBContext.Tests.Net461.Database.CustomerContact' cannot be constructed in a LINQ to Entities query.

### Further technical details
EF Core version: 1.x, 2.x
Database Provider: Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10 Pro
IDE: Visual Studio 2017

**Comment by smitpatel** [comment] 2017-10-17 19:02
Duplicate of #7983

**Closed** 2022-10-16 11:54 UTC
