### ISSUE TITLE
POCOs deriving from interfaces fail on KeyAttributeConvention validation

### ISSUE THREAD

**Issue by renierb** [dotnet/efcore#3872] opened 2015-11-24 07:44 UTC
The following POCO definition is not possible with EF7 rc1:

``` csharp
public interface IEntity
{}

[Table("tbAccount", Schema = "dbo")]
public class Account : IEntity
{
  [Key]
  public int Id {get; set;}
  public string Name {get; set;}
}
```

During runtime an InvalidOperationException is thrown from the KeyAttributeConvention class (line 25).
This is not an issue with EF6 and I encountered this limitation when migrating to EF7.

I would expect that Entity Framework doesn't care about interfaces and wouldn't expect attributes to be put inside interfaces.

**Comment by smitpatel** [comment] 2015-11-24 07:57
Creating model with above code works perfectly fine. Can you share your full model? Based on exception message, there must be some other entity type in the model which has been set as BaseType for `Account`.

**Comment by renierb** [comment] 2015-11-24 11:26
Here is a complete sample to reproduce:
```c#
public interface IEntity
{
  object Id { get; }
  ICollection<IDevice> Devices { get; }
}

public interface IDevice
{
  string DeviceId { get; }
}

[Table("tb_PlayerAccount", Schema = "dbo")]
public class Account : IEntity
{
  [Key]
  public long AccountID { get; set; }

  public string Name { get; set; }

  object IEntity.Id => AccountID;

  [NotMapped]
  ICollection<IDevice> IEntity.Devices { get; }
}

public class MyContext : DbContext
{
  public virtual DbSet<Account> PlayerAccounts { get; set; }

  protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
  {
    optionsBuilder.UseInMemoryDatabase();
  }
}

class Program
{
  static void Main(string[] args)
  {
    var account = new Account() {AccountID = 1};
    using (var context = new MyContext())
    {
      //InvalidOperationException is raised here:
      EntityEntry<Account> entry = context.Entry(account);
    }
  }
}
```
An InvalidOperationException is raised with the following information:
The derived type 'Account' cannot have KeyAttribute on property 'AccountID' since primary key can only be declared on the root type.

Please let me know if you want the repro project.

**Comment by smitpatel** [comment] 2015-11-24 16:22
@renierb - Thank you for sharing full model. The property causing issue is `object IEntity.Id => AccountID`. This is dupe of #3727 and the exception message has been improved in latest bits.

**Comment by MisterMe2** [comment] 2015-11-24 16:24
/dev/rtc0                 0600   system     system

# the DIAG device node is world writable/readable.
/dev/diag                 0666   root       root

# MirrorLink
/sys/devices/virtual/android_usb/android0/f_projector2    client_context_info    0644  system system

# the genlock client device node is world writable/readable.
/dev/genlock              0666   root      root

# gpu driver for adreno200 is globally accessible
/dev/kgsl                 0666   root       root
/dev/kgsl-3d0             0666   root       root
/dev/kgsl-2d0             0666   root       root
/dev/kgsl-2d1             0666   root       root

# these should not be world writable
/dev/ttyHS0               0600   bluetooth  bluetooth
/dev/ttyGS0               0660   system     system
/dev/sdio_tty_ciq_00      0660   system     system
/dev/pmem_audio           0660   system     audio
/dev/pmem_smipool*        0660   system     camera
/dev/oncrpc/*             0660   root       qcom_oncrpc
/dev/gss                  0660   gps        gps
/dev/msm_camera/*         0660   system     camera
/dev/radio0               0640   fm_radio   fm_radio
/dev/msm_mvs              0660   system     audio
/dev/msm_voicememo        0660   system     audio
/dev/tzcom                0660   system     audio
/dev/qce                  0660   system     audio
/dev/msm_pcm_lp_dec       0660   system     audio
/dev/smd4                 0660   system     system
/dev/smd3                 0660   bluetooth      bluetooth
/dev/smd2                 0660   bluetooth      bluetooth
/dev/smd7                 0640   radio      radio
/dev/smdcntl0             0640   radio      radio
/dev/smdcntl1             0640   radio      radio
/dev/smdcntl2             0640   radio      radio
/dev/smdcntl3             0640   radio      radio
/dev/smdcntl4             0640   radio      radio
/dev/smdcntl5             0640   radio      radio
/dev/smdcntl6             0640   radio      radio
/dev/smdcntl7             0640   radio      radio
/dev/smuxctl32            0640   radio      radio
/dev/sdioctl0             0640   radio      radio
/dev/sdioctl1             0640   radio      radio
/dev/sdioctl2             0640   radio      radio
/dev/sdioctl3             0640   radio      radio
/dev/sdioctl4             0640   radio      radio
/dev/sdioctl4             0640   radio      radio
/dev/sdioctl5             0640   radio      radio
/dev/sdioctl6             0640   radio      radio
/dev/sdioctl7             0640   radio      radio
/dev/sdioctl8             0640   radio      radio
/dev/rmnet_mux_ctrl       0640   radio      radio
/dev/hsicctl0             0640   radio      radio
/dev/hsicctl1             0640   radio      radio
/dev/hsicctl2             0640   radio      radio
/dev/hsicctl3             0640   radio      radio
/dev/htc_hsicctl          0660   radio      radio
/dev/qemu_trace           0666   system     system
/dev/gemini0              0660   system     camera
/dev/rawchip0             0660   system     camera
/dev/mdm                  0660   system     system
/dev/ttyHSL1              0660   system     system
/dev/ttyUSB0              0660   system     system
/dev/tty_sdio_00          0660   system     system
/dev/block/mmcblk0p17     0660   system     system
/dev/block/mmcblk0p18     0660   system     system
/dev/block/mmcblk0p22     0660   system     system
/dev/block/mmcblk0p23     0660   system     system
/dev/block/mmcblk0p30     0660   system     system
/dev/video*	          0660   system     camera 
#regular apps need to be able to open ion
/dev/ion                  0664   system     system

#permissions for video
/dev/msm_vidc_reg         0660  system       audio
/dev/msm_vidc_dec         0660  system       audio
/dev/msm_vidc_dec_sec     0660  system       audio
/dev/msm_vidc_enc         0660  system       audio
#permissions for audio
/dev/msm_amrnb            0660  system       audio
/dev/msm_amrwb            0660  system       audio
/dev/msm_aac              0660  system       audio
/dev/msm_multi_aac        0660  system       audio
/dev/msm_aac_in           0660  system       audio
/dev/msm_qcelp            0660  system       audio
/dev/msm_evrc             0660  system       audio
/dev/msm_fm               0660  system       audio
/dev/msm_acdb             0660  system       audio
/dev/msm_rtac             0660  system       audio
/dev/msm_wma              0660  system       audio
/dev/msm_wmapro           0660  system       audio
/dev/msm_qcelp_in         0660  system       audio
/dev/msm_evrc_in          0660  system       audio
/dev/msm_preproc_ctl      0660  system       audio
/dev/msm_a2dp_in          0640  system       audio
/dev/msm_amrnb_in         0640  system       audio
/sys/devices/virtual/smdpkt/smdcntl*       open_timeout   0664 radio radio
#permissions for sensors
/dev/msm_dsps             0660  system       system

# felica device file nodes
/dev/felica            0666   felicaclient   felicaclient
/dev/felica_pon        0666   felicaclient   felicaclient
/dev/felica_cen        0666   felicalock     felicalock
/dev/felica_rfs        0444   felicaclient   felicaclient
/dev/felica_rws        0666   felicaclient   felicaclient
/dev/felica_int        0444   felicaclient   felicaclient
/dev/felica_int_poll   0400   felicaclient   felicaclient
/dev/felica_uid        0222   felicaclient   felicaclient

# cir
/dev/ttyHSL2              0660   system       system

# HtcCarGPS
/dev/ttyHSUSB1                                 0600    system  system

# for autobot car pc
/dev/ttyHSUSB3                                 0660    autobot_access autobot_access






I need help

**Closed** 2022-10-16 09:17 UTC
