### ISSUE TITLE
Casting Error after upgrading to EFCore 5.0

### ISSUE THREAD

**Issue by Manishdidwania** [dotnet/efcore#27061] opened 2021-12-23 12:57 UTC
I have a simple solution that is working perfectly fine with EF3.1, I recently upgraded the version to EF5 with Dotnet5 and start getting strange conversion issue
The domain class

```c#
public class AirIncomingMessage:FoundationClass
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long ID { get; set; }
        [Required]
        public DateTime ReceivedTimeStamp { get; set; }

        public DateTime? LastProcessed { get; set; }

        [Required, MaxLength(300)]

        public string FromAddress { get; set; }

        [ForeignKey("CustomerOfficeID")]
        public CustomerOffice CustomerOffice { get; set; }

        public long? CustomerOfficeID { get; set; }

        [Required, StringLength(300)]
        public string MessageSubject { get; set; }

        [Required]
        public string MessageBody { get; set; }

        public bool? Processed { get; set; }

        [StringLength(300)]
        public string ErrorDetails { get; set; }

        public long? PreviousReference { get; set; }

        [StringLength(300)]
        public string JobID { get; set; }

        public AirMessageType MessageType { get; set; }//ENUM
        public int MessageVersion { get; set; }
        public int RetryCount { get; set; }

        public int MessageSequenceNo { get; set; }
        [MaxLength(8)]
        public string FlightNo { get; set; }
        public DateTime FlightDate { get; set; }

        [MaxLength(3)]
        public string FlightOrigin { get; set; }
        [MaxLength(3)]
        public string FlightDestination { get; set; }
        public bool LastMessage { get; set; }

        public bool DomesticIGM { get; set; }

        public AirIncomingMessage()
        {
            Processed = false;
            DomesticIGM = false;
        }

    }
```

**event a simple get command as follows a cast issue. I tried to create a fresh project with the exact same domain class and EF5.0 for some reason it is working. But my original project is not working.**

```c#
AirIncomingMessage = await _context.AirIncomingMessages
                    .AsNoTracking().FirstOrDefaultAsync(am=>am.ID==id);
```

error message

```
"{\"ClassName\":\"System.InvalidCastException\",\"Message\":\"Unable to cast object of type 'System.String' to type 'System.Int32'.\",\"Data\":{},\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":\"   at 
Microsoft.Data.SqlClient.SqlBuffer.get_Int32()\\r\\n   at Microsoft.Data.SqlClient.SqlDataReader.GetInt32(Int32 i)\\r\\n   at 
lambda_method328(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )\\r\\n   at 
Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()\\r\\n   at 
Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)\\r\\n   at 
Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)\\r\\n   at 
EagleAPI.Controllers.AirIncomingMessagesController.GetAirIncomingMessage(Int64 id) in D:\\\\Source\\\\EagleAPI\\\\EagleAPI\\\\Controllers\\\\Jobs\\\\Air\\\\AirIncomingMessages.cs:line 260\\r\\n   at 
lambda_method314(Closure , Object )\\r\\n   at 
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\\r\\n   at 
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\\r\\n   at 
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\\r\\n   at 
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\\r\\n   at 
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\\r\\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\\r\\n   at 
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\",\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":null,\"HResult\":-2147467262,\"Source\":\"Microsoft.Data.SqlClient\",\"WatsonBuckets\":null}"
```

**Comment by ajcvickers** [comment] 2022-01-18 15:53
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:20 UTC
Labels: closed-could-not-reproduce, customer-reported
