### ISSUE TITLE
MVC Core and Entity Framework

### ISSUE THREAD

**Issue by rolandwales10** [dotnet/efcore#12185] opened 2018-05-31 14:58 UTC
I have been using https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db to connect and existing database to a Core project.  I ran the scaffolding step to pull in the definition as follows:

Scaffold-DbContext "Server=.\local;Database=Farmshare;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models

It pulled in the tables, but not the dbContext class.

EF Core version: 2.0
Database Provider: Microsoft SQL server
Operating system: /wiudows 7
IDE: (Visual Studio 2017 15.7.2)

**Comment by sam-wheat** [comment] 2018-05-31 21:03
Look in the project where the classes for the tables were generated.  You should see a file called something like FarmshareContext.cs.  That is the dbContext.

**Comment by ajcvickers** [comment] 2018-06-04 16:29
@rolandwales10 Can you please post the full output from the scaffolding command line?

**Comment by ajcvickers** [comment] 2018-06-11 18:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:27 UTC
Labels: closed-could-not-reproduce, customer-reported
