### ISSUE TITLE
Is it ment to be that .Contains right now ignore string lenthg in linq ? 

### ISSUE THREAD

**Issue by tomaszlubocki** [dotnet/efcore#32889] opened 2024-01-22 22:28 UTC
Hello All ! 
 lets say in Db I have Person entity with Name : "Smith"  let's say the name column is varchar(5)
 Now In my app, you can filter for person Name, passing multiple names. So let's say user gives one name "Smithxxx", which then 
 goes to backend as List<string> with one element - "Smithxxx"
 
 Earlier : 
  _dbContext.Persons.Where(x=> names.Contains(x.Name)).ToList() gives 0 (correct as for me !) 
  
  Now : 
 _dbContext.Persons.Where(x=> names.Contains(x.Name)).ToList()  gives 1 

IT seems that then In .Contains only first n characters (where n is maxLength of db Column) are compared 

Is there a way (beside downgrading compatiblityLevel) to avoid the "new" behaviour ? 
Also is this a bug or feature for you? 

EF Core version: 8.0.1
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .net 8.0
Operating system: Windows 
IDE: (e.g. Visual Studio Proffessional 2022 17.8.5)

Regards,
Tomek

**Comment by roji** [comment] 2024-01-22 22:39
Duplicate of #32735

**Comment by roji** [comment] 2024-01-22 22:40
Can you confirm that the column argument to Contains (x.Name) is configured with a non-default length (i.e. not `NVARCHAR(MAX)`), and that the values in names are sometimes bigger than that column's configured length?

**Comment by tomaszlubocki** [comment] 2024-01-23 11:51
Hi roji, 
  yes the column for x.Name is exact nvarchar(15) , and the values for which I have to exectute query may be sometimes bigger than column configured lentgh, in fact is my exact case. 
  
Regards, 
Tomek

**Comment by roji** [comment] 2024-01-23 20:46
@tomaszlubocki thanks for confirming - please follow #32735 for the resolution of this bug.

**Closed by roji** 2024-01-23 20:46 UTC
Labels: customer-reported
