### ISSUE TITLE
query the navigation property by Include and return different type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#21978] opened 2020-08-06 18:59 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/483062/query-the-navigation-property-by-include-and-retur.html)._

---
<p>Currently, EF Core does not support load navigation property to return different type.  </p><p>eg. I have model like  </p><pre>class Student{
   public int Id { get; set;}
   public virtual ICollection&lt;Grade&gt; Grades { get; set;}

   ...
}

class Grade {
   public virtual GrandeInfo Info { get; set;}
   public DateTime Date { get; set;}
}

class GrandeInfo {
  public int Id { get; set;}
  public int Score { get; set;}
}
</pre><p>And I want to return the student by</p><pre>var students = applicationDbContext.Students.Where(s =&gt; s.Id ==2)
    .Select(student =&gt; new { 
        LatestGrade = student.Grades.OrderBy(g =&gt; g.Date).FirstOrDefault(),
        Id = student.Id
        }).ToList();
</pre><p>But, it will fail to return `LatestGrade`.</p><p></p><p></p><p></p><p></p>

---
#### Jane Wu [MSFT] on 3/11/2019, 03:21 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by ajcvickers** [comment] 2020-08-07 18:40
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-08-17 15:26
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:36 UTC
Labels: closed-could-not-reproduce, customer-reported
