### ISSUE TITLE
Allow a namespace to be provided to all scaffolding operations

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/efcore#19626] opened 2020-01-18 01:10 UTC
I'd love to be able to provide a namespace for the generated files. My project has an `src/` directory at the root where my C# source files begin from.

😊

**Comment by ErikEJ** [comment] 2020-01-18 07:16
EF Core Power Tools gives you full control of namespaces (for Reverse Engineering)

**Comment by atrauzzi** [comment] 2020-01-18 15:43
Does that require Visual Studio to run?

**Comment by ErikEJ** [comment] 2020-01-18 17:03
Yes, IT is a Visual Studio extension. Please create an issue if you would like a .NET Core command line version.

**Comment by atrauzzi** [comment] 2020-01-19 19:16
Is that not what this is?

**Comment by ErikEJ** [comment] 2020-01-19 20:20
Yes, bit it does not allow you full control of namespaces at the moment

**Comment by atrauzzi** [comment] 2020-01-19 20:55
Can we simply track it through this issue?

**Comment by ajcvickers** [comment] 2020-01-21 18:10
@bricelam to take a look.

**Comment by bricelam** [comment] 2020-01-21 22:55
Duplicate of #9723

**Closed** 2022-10-16 18:06 UTC
Labels: closed-duplicate, customer-reported
