### ISSUE TITLE
Entity Framework results in timeout errors, particularly when using OrderBy in conjunction with Take

### ISSUE THREAD

**Issue by stefanMinch3v** [dotnet/efcore#33158] opened 2024-02-26 12:47 UTC
Querying of a database fails with resulting in timeout.
It broke since version 8.0.0, it was working fine with the old versions 7, 6, 5 and down.
Tested on a database AzureSQL with 410_000 customers.

```C#
// this query fails with timeout
var dataFails = await CurrentDbContext.Customers
    .AsNoTracking()
    .OrderBy(x => x.CreatedDate)
    .ThenBy(x=> x.ID)
    .Take(100)
    .ToArrayAsync(cancellationToken);
    
// this query works
var dataWorks = await CurrentDbContext.Customers
    .AsNoTracking()
    .Take(100)
    .OrderBy(x => x.CreatedDate)
    .ThenBy(x=> x.ID)
    .ToArrayAsync(cancellationToken);
```
If anyone has experienced the same issue, the work-around is to switch `Take` to be above the `OrderBy`,
bear in mind that this generates one extra sub-query:
```C#
DECLARE @__p_0 int = 100;

SELECT [t].[ID], [t].[AccountNumber], [t].[AddressLine1], [t].[AddressLine2], [t].[AutoBill], [t].[BillToParent], [t].[BusinessPhone], [t].[BusinessUnitID], [t].[City], [t].[CollectiveBilling], [t].[CompanyName], [t].[CompanyVAT], [t].[Country], [t].[County], [t].[CreatedBy], [t].[CreatedDate], [t].[CurrencyCode], [t].[CustomerGroupID], [t].[EmailTemplateSetID], [t].[FullName], [t].[HomePhone]
FROM (
    SELECT TOP(@__p_0) [c].[ID], [c].[AccountNumber], [c].[AddressLine1], [c].[AddressLine2], [c].[AutoBill], [c].[BillToParent], [c].[BusinessPhone], [c].[BusinessUnitID], [c].[City], [c].[CollectiveBilling], [c].[CompanyName], [c].[CompanyVAT], [c].[Country], [c].[County], [c].[CreatedBy], [c].[CreatedDate], [c].[CurrencyCode], [c].[CustomerGroupID], [c].[EmailTemplateSetID], [c].[FullName], [c].[HomePhone]
    FROM [Customer] AS [c]
) AS [t]
ORDER BY [t].[CreatedDate], [t].[ID]
```

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer 8.0.0, 8.0.1 and 8.0.2

**Comment by roji** [comment] 2024-02-26 15:24
@stefanMinch3v these two queries mean very different things, and will return completely different results: the second returns 100 random rows, sorted by date and ID, while the first returns the first 100 rows based on the date and ID.

For the query which fails with a timeout, since you're saying it was working fine before, can you please post the SQL generated by EF for 8.0 and for 7.0?

**Comment by stefanMinch3v** [comment] 2024-02-27 08:17
@roji thank you for the quick response, the query looks the same on dotnet 7 and 8
```C#
DECLARE @__p_0 int = 100;

SELECT TOP(@__p_0) [c].[ID], [c].[AccountNumber], [c].[AddressLine1], [c].[AddressLine2], [c].[AutoBill], [c].[BillToParent], [c].[BusinessPhone], [c].[BusinessUnitID], [c].[City], [c].[CollectiveBilling], [c].[CompanyName], [c].[CompanyVAT], [c].[Country], [c].[County], [c].[CreatedBy], [c].[CreatedDate], [c].[CurrencyCode], [c].[CustomerGroupID], [c].[EmailTemplateSetID], [c].[FullName]
FROM [Customer] AS [c]
ORDER BY [c].[CreatedDate], [c].[ID]
```
When we execute it from Sql server management studio it all works well.
Will have to dig into AzureSQL then, might not be related to EF, feel free to close the issue, I will update it when we have more info from Azure.

**Comment by roji** [comment] 2024-02-27 08:29
@stefanMinch3v thanks; if the SQL is identical across the two versions, then this is unlikely to be related to EF.

I'll go ahead and close this for now, but if your investigation points to EF being the cause, please post back here and we'll revisit.

**Closed by roji** 2024-02-27 08:29 UTC
Labels: customer-reported
