### ISSUE TITLE
Linq to SQL does not take advantage of 'as' aliases

### ISSUE THREAD

**Issue by GedasFX** [dotnet/efcore#19489] opened 2020-01-06 11:16 UTC
Consider the following LINQ code:
```
            await _context.Users
                .Include(s => s.Categories)
                .Select(s => new
                {
                    Id = s.Id,
                    Name = s.Name,
                    PointsTotal = s.Categories.Sum(u => u.Points)
                })
                .OrderByDescending(e => e.PointsTotal)
                .ToListAsync();
```
A user has many categories where he can get points, and for leader board purposes I want to get the sum of the points he has.
Linq to SQL does translate the statement, however it is not optimal:
Provided:
```
      SELECT [s0].[Id] AS [Id], [s0].[Name] AS [Name], (
          SELECT SUM([s].[Points])
          FROM [UserCategories] AS [s]
          WHERE [s0].[Id] = [s].[UserId]) AS [PointsTotal]
      FROM [Users] AS [s0]
      ORDER BY (
          SELECT SUM([s1].[Points])
          FROM [UserCategories] AS [s1]
          WHERE [s0].[Id] = [s1].[UserId]) DESC
```
Expected:
```
      SELECT [s0].[Id] AS [Id], [s0].[Name] AS [Name], (
          SELECT SUM([s].[Points])
          FROM [UserCategories] AS [s]
          WHERE [s0].[Id] = [s].[UserId]) AS [PointsTotal]
      FROM [Users] AS [s0]
      ORDER BY [PointsTotal] DESC
```
Using Microsoft.EntityFrameworkCore.SqlServer 3.1.0 package

**Comment by ajcvickers** [comment] 2020-01-06 18:24
@maumar to look for duplicate or put on backlog.

**Comment by maumar** [comment] 2020-01-07 01:06
dupe of https://github.com/aspnet/EntityFrameworkCore/issues/18775

**Closed** 2022-10-16 18:04 UTC
Labels: customer-reported
