### ISSUE TITLE
Please support explicit loading of scalar properties like BLOBs without table splitting

### ISSUE THREAD

**Issue by MarcoLoetscher** [dotnet/efcore#4726] opened 2016-03-08 20:27 UTC
[8.2.3 Workaround to get lazy loading of properties](https://msdn.microsoft.com/en-us/data/hh949853.aspx#8)

**Comment by rowanmiller** [comment] 2016-03-08 21:29
Duplicate of https://github.com/aspnet/EntityFramework/issues/1387

**Closed** 2022-10-16 09:31 UTC
