### ISSUE TITLE
EF Core SQLite + NetTopologySuite error

### ISSUE THREAD

**Issue by facu-larocca-zenfolio** [dotnet/efcore#17864] opened 2019-09-16 19:38 UTC
I actually working with an SQL Server DB that uses Spatial data, particularly IPoint.
When setting everything to use SQL Server everything works fine, but for testing purposes, I wanted to configure SQLite.

This is my configuration code:

```C#
var connectionStringBuilder =
    new SqliteConnectionStringBuilder { DataSource = ":memory:" };
var connection = new SqliteConnection(connectionStringBuilder.ToString());

var options = new DbContextOptionsBuilder<BookingDbContext>()
    .UseSqlite(connection, sqliteOptions =>
    {
        sqliteOptions.UseNetTopologySuite();
    })
    .Options;

var dbContext = new BookingDbContext(options);
```

Whatever operation I try to execute against the DB I am getting this error:

> SQLite Error 1: The specified module could not be found.

And this is the stack:

> at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
> at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
> at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
> at Microsoft.EntityFrameworkCore.Infrastructure.SpatialiteLoader.Load(DbConnection connection)
> at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.LoadSpatialite()
> at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
> at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Delete()
> at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureDeleted()
> at Zenfolio.Booking.IntegrationTests.Infrastructure.DatabaseFixture.PrepareDatabase(Boolean migrate) in C:\zenfolio\zf-booking\Zenfolio.Booking.IntegrationTests\Infrastructure\DatabaseFixture.cs:line 46

There is a pending question in StackOverflow pointing this issue:
https://stackoverflow.com/questions/57558305/how-to-fix-sqlite-error-1-the-specified-module-could-not-be-found-with-ef-a

### Additional context

**Microsoft.EntityFrameworkCore.Sqlite** Version 2.6.0
**Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite** Version 2.6.0
Target framework:  .NET Core 2.2
Operating system: **Windows 10 x64**, but this service is actually running on multiple operating systems as there are many developers using different ones.

**Comment by bricelam** [comment] 2019-09-16 21:17
Could you share a project we can use to try and reproduce the issue? Are you on a 32-bit version of Windows?

**Comment by facu-larocca-zenfolio** [comment] 2019-09-17 17:21
@bricelam Thanks for your quick answer.
I tried to isolate the case and reproduce it in a separate repo, but I am not being able to do so, It just works fine, which puts me into a more complicated position.
I can't reproduce the bug in a separate repo and I can't share the repo cause it is a company's private repo.

Is there any log I can attach?

Thanks a lot!

**Comment by ericsink** [comment] 2019-09-17 17:47
> Among other things I tried, I got a different error after installing SQLitePCLRaw.bundle_e_sqlite3 2.0.2-pre20190904113843, the error I got was System.String SQLitePCL.raw.sqlite3_errstr(Int32)'.

This error (which is likely unrelated to the main issue here) is probably because SQLitePCLRaw 2.x is not compatible with EF Core versions prior to 3.0.

**Comment by facu-larocca-zenfolio** [comment] 2019-09-17 18:07
@ericstj Ok, then ignore that comment. Does not make sense at all.
Thanks.

**Comment by bricelam** [comment] 2019-09-18 00:54
Do you have multiple projects? Try installing the mod_spatialite NuGet package into the main EXE project

**Comment by facu-larocca-zenfolio** [comment] 2019-09-18 14:03
Based on your recommendation what I did was to copy the content of `mod_spatialite\4.3.0.1\runtimes\win-x64\native` into the project's bin folder (`bin\Debug\netcoreapp2.2\win10-x64`), and that solved the issue.
Somehow, some library is trying to get some assemblies using a relative path.

Could this be a bug? If so, I would be glad to help you out solve it as I have the environment already in place and I know how to reproduce it!

Thanks a lot @bricelam

**Comment by bricelam** [comment] 2019-09-18 20:37
So your csproj specifies a `<RuntimeIdentifier>`?

**Comment by bricelam** [comment] 2019-09-18 20:39
Could be related to #14093...

**Comment by facu-larocca-zenfolio** [comment] 2019-09-19 14:23
@bricelam 
No, that project does not specify any `<RuntimeIdentifier>`, It is just a regular test project running with VS CE 16.1.1

**Comment by peteryangthinkgeo** [comment] 2019-10-26 03:22
I meet this issue too, I copied the content from native to the bin folder, it can work well with container-self mode, but still not work under IIS. Any ideas?

**Comment by clarkgranum** [comment] 2019-10-31 00:38
I am having the same issue. I am running an ASP.NET Core 2.2 Application, using EF Core 2.2.0, in a framework dependent deployment. My EF project is separate from the ASP.NET Core project.

It looks like the issue is in SpatialiteLoader.cs in the FindExtension() method. The method is attempting to add the directory of the mod_spatialite.dll to the PATH Environment variable, but the path it is trying to set does not exist so the spatialite extension fails to load. The path it is trying to add on my machine is: "mod_spatialite\4.3.0.1\runtimes\win-x64\native" which is neither a correct absolute or relative path. mod_spatialite.dll is deployed with my ASP.NET Core application at "{App Content Root Path}\runtimes\win-x64\native." Shouldn't SpatialiteLoader use this path? I added my own code in Startup to add this directory to the PATH variable and this solves the issue.

**Comment by bricelam** [comment] 2020-01-07 18:53
This looks like an issue with framework-dependent deployments. I can confirm @clarkgranum's findings. As a workaround, you can use a self-contained deployment (e.g. `dotnet publish -r win10-x64`)

**Comment by bricelam** [comment] 2020-01-10 20:50
Duplicate of #15691

**Comment by sxotney** [comment] 2021-08-17 21:33
I am experiencing the this issue in preview 7 edition of Dotnet 6 when I try to build for the Bullseye-Slim docker image:

![image](https://user-images.githubusercontent.com/6230394/129802826-a096161d-3dd0-4407-8642-fbcbdb0baab9.png)

The mod_spatialite.so lib file (amongst many others) is not being copied to the bin folder at build time. 

Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'mod_spatialite.so: cannot open shared object file: No such file or directory'.

The workaround of building/publishing to a self contained app doesn't work either here.

**Closed** 2022-10-16 14:42 UTC
Labels: closed-duplicate, customer-reported, punted-for-3.1
