### ISSUE TITLE
Can't use order by Guid.NewGuid() when UseNetTopologySuite() is used

### ISSUE THREAD

**Issue by velocitysystems** [dotnet/efcore#13708] opened 2018-10-21 12:44 UTC
When UseNetToplogySuite() is used to support spatial data, any attempt at random ordering fails.
ie. `.OrderBy(q => Guid.NewGuid())`

See exception and stack trace below.

```
Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.SqlServer.Query.ExpressionTranslators.Internal.SqlServerGeometryMethodTranslator.Translate(MethodCallExpression methodCallExpression)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.RelationalCompositeMethodCallTranslator.Translate(MethodCallExpression methodCallExpression, IModel model)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitOrderByClause(OrderByClause orderByClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.OrderByClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()
```

This occurs even on a simple query where where `.Include(..)` is not used.
Tried implementing suggestions in this thread to no avail. https://github.com/aspnet/EntityFrameworkCore/issues/5583

### Steps to reproduce
```c#
var randomLocations = Context.Locations
    .Select(loc => loc.LocationId)
    .OrderBy(loc => Guid.NewGuid())
    .Take(5);
```

### Further technical details
EF Core version: 2.2.0-preview3-35497
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Professional Version 1803
Visual Studio Community 2017 v15.8.7

**Comment by ajcvickers** [comment] 2018-10-22 17:20
@bricelam Could be another dupe.

**Comment by bricelam** [comment] 2018-10-24 17:37
Dupe of #13686. Fixed in [the nightly builds](https://dotnet.myget.org/gallery/dotnet-core).

**Comment by mattrichnz** [comment] 2018-10-25 07:59
@bricelam Perfect, many thanks!
Just to confirm, this will make it into the final 2.2 RTM release?

**Closed** 2022-10-16 13:36 UTC
Labels: closed-duplicate, customer-reported
