### ISSUE TITLE
EF Commands for a Library Project

### ISSUE THREAD

**Issue by chrisjmccrum** [dotnet/efcore#4614] opened 2016-02-21 04:52 UTC
What is the proper way to use EF Commands for a Library Project? My project structure is:
- Project.Core (startup resides here and has Project.EF dependency) _dnxcore50_
- Project.EF _dnxcore50_

I added dotnet-ef tools to Project.EF and ran the add migration command from the command line and got the error below

```
C:\Users\chris\Documents\project\core\src\Project.EF
dotnet ef migrations add initial -s ..\Project.Core
```

> Could not load assembly 'Project.EF'. Ensure it is referenced by the startup project 'Project.Core'.

**Comment by bricelam** [comment] 2016-02-21 22:25
Did you get it working? Everything here looks right.

**Comment by chrisjmccrum** [comment] 2016-02-21 22:28
almost - I just actually posted a question in Jabbr because I'm stuck here. The migrations are working but when I ran update database I get an exception that I cant seem to figure out

![image](https://cloud.githubusercontent.com/assets/1857216/13205890/714dd9be-d8c0-11e5-90ba-77549eb73f85.png)

this is my project.json for the EF project

```
{
  "dependencies": {
    "Microsoft.EntityFrameworkCore": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.Commands": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-*",
    "Microsoft.AspNetCore.Hosting": "1.0.0-*",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-*",
    "OpenIddict.EF": "1.0.0-*",
    "Project.Models": "1.0.0-*"
  },

  "frameworks": {
    "dotnet5.4": {
      "imports": "portable-net451+win8",
      "dependencies": {
        "System.Data.SqlClient": "4.0.0-*"
      }
    }
  },

  "tools": {
    "dotnet-ef": "1.0.0-*"
  }
}
```

**Comment by chrisjmccrum** [comment] 2016-02-22 06:02
@bricelam do you have any advice on how I can get this working?

**Comment by bricelam** [comment] 2016-02-22 17:55
I think I'm working on a fix for this right now. It looks like the same root cause that is preventing `dotnet ef dbcontext scaffold` from working.

**Comment by chrisjmccrum** [comment] 2016-02-22 18:23
awesome to hear! I'll wait on your fix then

**Comment by rowanmiller** [comment] 2016-02-22 19:16
Covered by https://github.com/aspnet/EntityFramework/issues/3925

**Comment by capesean** [comment] 2016-02-29 12:47
@chrisjmccrum did you solve that System.Data.SqlClient issue? I'm running into it now when trying to update the database.

**Comment by chrisjmccrum** [comment] 2016-02-29 16:56
@capesean unfortunately I didn't  - I took a week off from the project but I just tried again after restoring and building everything. Now it's worst haha.

![image](https://cloud.githubusercontent.com/assets/1857216/13401700/353798ae-dedb-11e5-8e32-adf49fb1d02b.png)

> C:\Users\chris\Documents\project\core\src\Project.EF
> dotnet ef migrations add initial -s ..\Project.Core
> Process is terminated due to StackOverflowException.

If you gain any progress let me know dude - I need to get this back up and running and the EF stuff is stopping me. =(

**Comment by rowanmiller** [comment] 2016-02-29 18:14
Things are still going to be pretty volatile in our working code base for a little while yet. Things tend to work one day and then break the next as the various pieces that we depend on are churning. If RC1 works for you, then I would use that. If not, when you find a "nightly" build that works for you, I would pin to that build and not auto upgrade to the latest.

**Comment by chrisjmccrum** [comment] 2016-02-29 18:29
unfortunately RC1 doesn't work for me at the moment - but your right, once I find a nightly build that does what I need, I intend on pinning my project to it.  any thoughts on how to resolve the db command issues we're having?

**Comment by rowanmiller** [comment] 2016-02-29 22:09
@chrisjmccrum I'm not sure that there is a way to get them working at the moment. @bricelam  may have thoughts, but in general we only have things working in some very specific cases at the moment.

**Closed** 2022-10-16 09:30 UTC
