### ISSUE TITLE
"Onswone" Select failed with two tables

### ISSUE THREAD

**Issue by Gullus** [dotnet/efcore#16664] opened 2019-07-19 04:40 UTC
The following example fails.
System.NullReferenceException: “Object reference not set to an instance of an object.”
The saving of the data works.  Everything works great with one Table. In version 2.6, the example works without problems.  I work with Microsoft. EntityFrameworkCore 3.0.0-preview6.19304.10.

```C#
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    public class JgLogDb : DbContext
    {
        public string SqlVerbindung = @"Data Source=.\SqlExpress;Initial Catalog = JgTest; Integrated Security = True";

        public DbSet<TabTest1> TabTest1Set { set; get; }
        public DbSet<TabTest2> TabTest2Set { set; get; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TabTest1>().OwnsOne(p => p.MTest);
            modelBuilder.Entity<TabTest2>().OwnsOne(p => p.MTest);

            base.OnModelCreating(modelBuilder);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(SqlVerbindung);
        }
    }

    public class TabTest1
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public string Feld1 { get; set; }
        public MeinTest MTest { get; set; }
    }

    public class TabTest2
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public string Fel2 { get; set; }
        public MeinTest MTest { get; set; }
    }

    [Owned]
    public class MeinTest
    {
        public string FeldTest { get; set; }
    }

    class Program
    {
        static async Task Main()
        {
            using (var db = new JgLogDb())
            {
                await db.TabTest1Set.AddAsync(new TabTest1()
                {
                    Feld1 = "Hallo",
                    MTest = new MeinTest()
                    {
                        FeldTest = "Ballo"
                    }
                });
                await db.SaveChangesAsync();
            }

            using (var db = new JgLogDb())
            {
                var liste = await db.TabTest1Set
                    .Select(s => new
                    {
                        f1 = s.Feld1,
                        f2 = s.MTest.FeldTest
                    }).ToListAsync();

                foreach (var ds in liste)
                    Console.WriteLine($"{ds.f1}  {ds.f2}");
            }

            Console.ReadLine();
        }
    }
}
```

**Comment by ajcvickers** [comment] 2019-07-19 16:39
Note for triage: this works on 2.2 and with the current nightly builds.

**Comment by ajcvickers** [comment] 2019-07-19 19:05
Duplicate of #15285

**Comment by Gullus** [comment] 2019-07-21 16:09
Die Antwort von Microsoft.

Visual Studio Feedback System
vor 2 Tage
We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Closed** 2022-10-16 14:31 UTC
Labels: closed-duplicate, customer-reported
