### ISSUE TITLE
EntityBuilder: .OnDelete() is ignored if used after .IsRequired() and shadow property

### ISSUE THREAD

**Issue by pascal-910** [dotnet/efcore#25186] opened 2021-07-02 07:11 UTC
### Problem
When configuring a non-nullable foreign key with FluentAPI `.OnDelete()` is ignored when called after `.IsRequired()` but only if no explicit foreign key is configured for relationship in dependant entity. If I'd add a `AddressId` property in `Order` model it would work as expected.

### Code
Model
```C#
  public class Address {
      public int AddressId { get; set; }
  }

  public class Order {
      public int OrderId { get; set; }
      public Address Address { get; set; }
  }
```
FluentAPI
Case 1) Does work: DeleteBehavior: No Action is taken (see debug output below)
Case 2) Doesn't work: Default behavior Cascade is taken (see debug output below)
```C#
  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
      // 1) Does work
      modelBuilder.Entity<Order>()
          .HasOne(o => o.Address)
          .WithOne()
          .HasForeignKey<Order>("AddressId")
          .OnDelete(DeleteBehavior.NoAction)
          .IsRequired();

      // 2) Doesn't work
      modelBuilder.Entity<Order>()
          .HasOne(o => o.Address)
          .WithOne()
          .HasForeignKey<Order>("AddressId")
          .IsRequired()
          .OnDelete(DeleteBehavior.NoAction);
  }
```
**Debug ShortView**
**Case 1**
```
Model: 
  EntityType: Address
    Properties: 
      AddressId (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
    Keys: 
      AddressId PK
  EntityType: Order
    Properties: 
      OrderId (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      AddressId (no field, int) Shadow Required FK Index
    Navigations: 
      Address (Address) ToPrincipal Address
    Keys: 
      OrderId PK
    Foreign keys: 
      Order {'AddressId'} -> Address {'AddressId'} Unique ToPrincipal: Address
    Indexes: 
      AddressId  Unique
```

**Case 2**
```
Model: 
  EntityType: Address
    Properties: 
      AddressId (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
    Keys: 
      AddressId PK
  EntityType: Order
    Properties: 
      OrderId (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      AddressId (no field, int) Shadow Required FK Index
    Navigations: 
      Address (Address) ToPrincipal Address
    Keys: 
      OrderId PK
    Foreign keys: 
      Order {'AddressId'} -> Address {'AddressId'} Unique ToPrincipal: Address Cascade
    Indexes: 
      AddressId  Unique
```

Maybe also see a similar yet fixed issue  #23555, but it was the other way around (.IsRequired didn't work after .OnDelete)

EF Core version: 5.0.7
Database provider: Microsoft.EntityFrameworkCore.SqlServer / Microsoft.EntityFrameworkCore.SQlite / ... ?
Target framework: NET 5.0
Operating system: Win10.0.19042.1052
IDE: Visual Studio 2019 CE 16.10

**Comment by smitpatel** [comment] 2021-09-27 18:07
The issue is still present.
https://github.com/dotnet/efcore/blob/289e7a69b0c02f5569bbaf0ac353c21afde5e397/src/EFCore/Metadata/Internal/ForeignKey.cs#L687-L689

When changing required, the convention return new Fk to change deletebehavior to cascade but we don't pick up new FK and hence DeleteBehavior is applied on stale fk and lost.

**Comment by AndriySvyryd** [comment] 2021-09-28 15:13
We need to start a convention batch and track the FK when the conventions need to run

**Comment by AndriySvyryd** [comment] 2024-09-09 23:30
Fixed in https://github.com/dotnet/efcore/commit/f5d789529eefd886585a5e764da0cc71a13b8798

**Closed by AndriySvyryd** 2024-09-09 23:30 UTC
Labels: type-bug, customer-reported, area-model-building, punted-for-6.0, punted-for-7.0
