### ISSUE TITLE
Unable to generate model from database in Visual Studio 2017 RC

### ISSUE THREAD

**Issue by firedeepan** [dotnet/efcore#7310] opened 2016-12-24 22:54 UTC
I followed the tutorial in [this link](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db) 

When I try to execute Scaffold-DbContext "Server=Data Source=DESKTOP-COJD62N;Initial Catalog=TrainGameDB;Integrated Security=True" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -context TrainGameContext -Verbose

I am getting the following output
Build started...
Build succeeded.
dotnet exec needs a managed .dll or .exe extension. The application specified was 'F:\_IIT Level 6\UX\CW2 Backend\App2\TrainGameAPI\src\TrainGameAPI\bin\Debug\netcoreapp1.0\TrainGameAPI.runtimeconfig.json'
Process finished with non-zero exit code

I am using:
Visual Studio 2017 RC
SQL Server 2016 Developer
.NET Core 1.1.0 (I uninstalled version 1.0.1 and installed this)
Windows 10 Education

Here is the list of packages from my .csproj file (VS 2017 doesn't have a package.json file)

```
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0-preview4-final" />
    <PackageReference Include="Microsoft.NETCore.App" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.0.0" />
```

**Comment by bricelam** [comment] 2017-01-03 17:44
Dupe of #7241

**Comment by firedeepan** [comment] 2017-01-03 18:33
@alexidsa - Changing the framework version to dotNetCore 1.1.0 didn't help. I still have the issue. After updating the framework to 1.1.0, I am not able to open the project anymore (should be a visual studio issue).

**Comment by divega** [comment] 2017-01-06 20:12
@firedeepan can you provide a repro project?

**Comment by bricelam** [comment] 2017-01-09 23:37
@firedeepan The workaround for #7241 is to add the following to your csproj:

```XML
<PropertyGroup>
  <NuGetPackageRoot>$(USERPROFILE)\.nuget\packages\</NuGetPackageRoot>
</PropertyGroup
```

**Comment by bricelam** [comment] 2017-01-09 23:38
You can also try it on the latest bits. See #7358

**Comment by bricelam** [comment] 2017-01-13 02:36
Closing, but please re-open with additional information if you can't get it working on version 1.0.0-msbuild3 of the tools.

**Closed** 2022-10-16 10:48 UTC
Labels: closed-duplicate
