### ISSUE TITLE
Owned types on an owner sub-type are not loaded

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#16360] opened 2019-06-30 21:04 UTC
See Database_concurrency_token_value_is_updated_for_all_sharing_entities

The model here has:
```C#
public class Sponsor
{
        public int Id { get; set; }
        public string Name { get; set; }
}

public class TitleSponsor : Sponsor
{
    public SponsorDetails Details { get; set; }
}

public class SponsorDetails
{
    public int Days { get; set; }
    public decimal Space { get; set; }
}
```
Both these queries leave `Details` null:
```C#
var sponsor = context.Set<TitleSponsor>().Single();
```
```C#
var sponsor = context.Set<TitleSponsor>().Include(e => e.Details).Single();
```
Tested with SQL Server

**Comment by smitpatel** [comment] 2019-06-30 21:09
Duplicate of #15285?

**Comment by ajcvickers** [comment] 2019-06-30 21:10
@smitpatel Probably--just wasn't sure if this was a special case.

**Closed** 2022-10-16 14:28 UTC
Labels: closed-duplicate
