### ISSUE TITLE
Xamarin: 'dlopen failed: library "mod_spatialite.so" not found

### ISSUE THREAD

**Issue by antosubash** [dotnet/efcore#14580] opened 2019-02-01 13:59 UTC
Hi I'm trying to use the NetTopologySuite with Xamarin forms. but it is not working.

```
Exception message:
Stack trace:
Unhandled Exception:

Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'dlopen failed: library "mod_spatialite.so" not found'.
```

### Steps to reproduce
Create a Blank Xamarin Forms project
Add "Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite" package.

```c#
optionsBuilder.UseSqlite($"Filename={dbPath}", x => x.UseNetTopologySuite());
```

### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite
Operating system: Windows
IDE: Visual Studio 2017 15.8
Platform : Xamarin

Repo to Reproduce : https://github.com/antosubash/SqlLiteDemo

**Comment by ajcvickers** [comment] 2019-02-01 23:01
@divega to test

**Comment by bricelam** [comment] 2019-02-02 00:19
Duplicate of bricelam/mod_spatialite-NuGet#6

Until then, applications are responsible for providing mod_spatialite.

**Comment by ajcvickers** [comment] 2019-05-20 18:23
Closing this for now as we don't plan to do anything specific for the module in the core EF package. However, we could revisit this in the future with enough feedback.

**Comment by BrianVance** [comment] 2020-04-18 23:08
Whats the fix for this issue? Do we have to download the Nuget package for "mod_spatialite" to fix this issue or is there some other workaround?

**Comment by ajcvickers** [comment] 2020-04-20 16:00
@BrianVance Yes, I believe that is the workaround.

**Comment by MaticDiba** [comment] 2022-06-24 14:59
Unfortunately that workaround does not work on android.

**Closed** 2022-10-16 13:50 UTC
Labels: closed-duplicate, area-xamarin, customer-reported
