### ISSUE TITLE
EF Core 5 - New Migrations Adding Alter ColumnStatements For Every Identity Column

### ISSUE THREAD

**Issue by pgallagher13** [dotnet/efcore#23755] opened 2020-12-22 15:40 UTC
I recently updated from EF Core 3 to EF Core 5, since the update I was able to add 1 new migration without a problem. Since then though every migration I add is adding Alter column statements for every identity column in the database. These columns already existed as identity columns prior to the update to EF Core 5.

Attempting to run the migration results in an error:

To change the IDENTITY property of a column, the column needs to be dropped and recreated.

There have been no changes to these columns since the previous migration and I do not know why EF Core is attempting to alter them.

Example alter column in the up method:

migrationBuilder.AlterColumn<int>(
    name: "UserID",
    table: "Users",
    type: "int",
    nullable: false,
    oldClrType: typeof(int),
    oldType: "int")
    .Annotation("SqlServer:Identity", "1, 1");

Attached zip file contains 2 solutions reproducing the issue.  _EF3.sln is on EF Core 3, _EF5.sln after updating to EF Core 5.  In EF5 Migration1 was added with no changes as expected, Migration2 also should have no changes but it is generating the alter column statements. 

[EFCore5MigrationPKRepro.zip](https://github.com/dotnet/efcore/files/5730738/EFCore5MigrationPKRepro.zip)

**Comment by anranruye** [comment] 2020-12-22 16:22
Remove alter column codes from the migration class up and down methods(remain the migration class). Then add a new migration. This may help.

**Comment by pgallagher13** [comment] 2020-12-22 16:29
I have tried removing the alter column statements from the migration so that the up and down methods are empty in the migration, the next migration added has the same alter column statements in it which results in an error when running the migration.

**Comment by anranruye** [comment] 2020-12-22 17:14
see at #23725 #23456

**Comment by ajcvickers** [comment] 2020-12-22 19:25
@pgallagher13 This is a duplicate of #23456. The problem is this call in the code that EF generates:

```C#
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");
```

This is actually a call to the `NpgsqlModelBuilderExtensions.UseIdentityColumns` method, rather than the `SqlServerModelBuilderExtensions.UseIdentityColumns` method, as it should be. As a workaround replace all occurrences of the code above with:

```C#
            modelBuilder
                // .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
```

I verified this works on your repro solution.

You will need to do this each time you generate a new migration, but we are looking into patching #23456 in a 5.0,x release.

**Comment by pgallagher13** [comment] 2020-12-23 13:31
Thank you for the clarification on this issue.

**Closed** 2022-10-16 19:16 UTC
Labels: closed-duplicate, customer-reported
