### ISSUE TITLE
register DbContext with AddPooledDbContextFactory with TContextService & TContextImplementation

### ISSUE THREAD

**Issue by YoussefSell** [dotnet/efcore#28229] opened 2022-06-14 21:29 UTC
as part of respecting clean code architecture, we intend to separate or code into multiple projects where the Database related configurations are set in the Persistence project. then when we intend to access the DbCotenxt from other projects we use an Interface so that we don't interact directly with the DbContext,
```AddDbContextPool<TContextService, TContextImplementation>()``` allow as to achieve this behavior.

now when using libraries for instant HotChocolate they require you (if you want to use DbContext pooling) to register the DbContext with ```AddPooledDbContextFactory()``` it will be beneficial to add the possibility to specify a TContextService same as with ```AddDbContextPool()```

**Comment by ajcvickers** [comment] 2022-06-16 17:13
Duplicate of #24174

**Closed** 2022-06-17 16:12 UTC
Labels: customer-reported
