### ISSUE TITLE
remove redundant null semantics terms involving non-null parameters 

### ISSUE THREAD

**Issue by Varorbc** [dotnet/efcore#25838] opened 2021-09-02 08:56 UTC
#15722

### Include your code

```C#
[Table("Table_1")]
public partial class Table1
{
    [Key]
    public int Id { get; set; }

    public string? Name { get; set; }

    public DateTime CreateTime { get; set; }
}

public partial class TestContext : DbContext
{
    public TestContext()
    {
    }

    public TestContext(DbContextOptions<TestContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Table1> Table1 { get; set; }
}

var services = new ServiceCollection();
services.AddDbContext<TestContext>();
var serviceProvider = services.BuildServiceProvider();

var testContext = serviceProvider.GetRequiredService<TestContext>();
var name = "Varorbc";
var sql = testContext.Table1.Where(a => a.Name != name).ToQueryString()
Console.WriteLine(sql);

```

### Expected Behavior

```
DECLARE @__name_0 nvarchar(4000) = N'Varorbc';

SELECT [t].[Id], [t].[CreateTime], [t].[Name]
FROM [Table_1] AS [t]
WHERE [t].[Name] <> @__name_0
```

### Actual Behavior

```
DECLARE @__name_0 nvarchar(4000) = N'Varorbc';

SELECT [t].[Id], [t].[CreateTime], [t].[Name]
FROM [Table_1] AS [t]
WHERE ([t].[Name] <> @__name_0) OR [t].[Name] IS NULL
```

### Include provider and version information

EF Core version:6.0.0-preview.7.21378.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system:Win11
IDE: Visual Studio 2022 17.0

**Comment by roji** [comment] 2021-09-02 12:37
That doesn't seem redundant: in C#, `a.Name != name` would return true if a.Name is NULL, but in SQL, `[t].[Name] <> @__name_0` would return NULL in that case, which the WHERE clause would interpret as false. Am I missing something?

**Comment by Varorbc** [comment] 2021-09-02 12:45
Isn't this #15722 already optimized? Why did it reappear here?

**Comment by roji** [comment] 2021-09-02 12:49
The problem is that (a) your column is nullable, and (b) you're using the non-equality operator rather than equality. If you try equality the extra null check should go away, since it's not needed in that case.

**Comment by roji** [comment] 2021-09-02 15:13
Below is a simple code sample that should help you understand - I've taken your code above, and seeded the database with exactly one row containing NULL in the Name column.

Running the SQL which EF generates, I get 1 row as expected:

```sql
DECLARE @__name_0 nvarchar(4000) = N'Varorbc';

SELECT COUNT(*)
FROM [Table_1] AS [t]
WHERE ([t].[Name] <> @__name_0) OR [t].[Name] IS NULL;
```

If I remove the "IS NULL" check, I get 0 rows, which is incorrect (does not match the C# behavior of the LINQ query):

```sql
DECLARE @__name_0 nvarchar(4000) = N'Varorbc';

SELECT COUNT(*)
FROM [Table_1] AS [t]
WHERE [t].[Name] <> @__name_0;
```

Give it a try. The reason is, once again, because `[t].[Name] <> N'Varorbc'` produces NULL when [Name] is NULL, and the whole expression evaluates to "false" in the context of WHERE.

**Comment by Varorbc** [comment] 2021-09-03 01:12
Thank you very much for your patient explanation

**Comment by Varorbc** [comment] 2021-09-03 01:21
Thank you very much for your patient explanation.

non-equality operator in sql means that the query does not contain Null data, and ef core adds Null data by default when querying. ef core is an Orm, and its behavior should be consistent with sql.

**Comment by roji** [comment] 2021-09-03 10:57
@Varorbc have you tried the removing the null check as in my previous message? That should help you understand why it is necessary. I also recommend reading up on how NULLs are handled in in SQL, and on three-value logic... In C#, the return value of `"foo" != null` is true, whereas in SQL the return value of `'foo' <> NULL` is NULL (evaluated to false in WHERE clause). This is why EF generates the extra null check.

**Comment by Varorbc** [comment] 2021-09-03 12:37
Yes, I have tested it. I understand what you mean. What I want to know is that the behavior of unequal operations in c# and SQL is inconsistent. In c# the execution is unequal, and I get a row of data, which is null, but in SQL the execution is unequal, and I get 0 rows of data. I should be based on the behavior in c# rather than the behavior in SQL, right? In fact, I prefer 0 rows of data, because null and [name] are not equal in understanding

**Comment by Varorbc** [comment] 2021-09-03 13:39
If you need to query data that contains Null, why not query like this?
`testContext.Table1.Where(a => a.Name != name || a.Name == null`

Besides, the generated sentence is so strange. This is another issue . Do I need to submit a new issue?
```
DECLARE @__name_0 nvarchar(4000) = N'Varorbc';

SELECT [t].[Id], [t].[CreateTime], [t].[Name]
FROM [Table_1] AS [t]
WHERE (([t].[Name] <> @__name_0) OR [t].[Name] IS NULL) OR [t].[Name] IS NULL
```

**Comment by roji** [comment] 2021-09-03 15:02
> I should be based on the behavior in c# rather than the behavior in SQL, right? In fact, I prefer 0 rows of data, because null and [name] are not equal in understanding

This is not how EF Core works - by design. The overwhelming user expectation we see is for their LINQ queries - which are expressed in C# - to bring back the same results from the database is it would if executed in .NET without a database; in fact, our test suite generally makes sure that the same LINQ expression works the same way in SQL and in .NET. This means EF must sometimes "compensate" for differences between C# and SQL via extra clauses. Translation is not a matter of producing a direct, "one-to-one" SQL that looks as close as possible to the C# LINQ query, but rather for the query to produce the same results.

You should probably read [our doc page on nullability in queries](https://docs.microsoft.com/en-us/ef/core/querying/null-comparisons). Note that you can opt into "[relational semantics](https://docs.microsoft.com/en-us/ef/core/querying/null-comparisons#using-relational-null-semantics)", which will make EF behave similar to what you want. However, this is generally discouraged.

Am going to go ahead and close this issue as things are working as designed.

**Comment by Varorbc** [comment] 2021-09-03 15:28
Thank you very much for your explanation

Need additional tracking.?

`testContext.Table1.Where(a => a.Name != name || a.Name == null`

```
DECLARE @__name_0 nvarchar(4000) = N'Varorbc';

SELECT [t].[Id], [t].[CreateTime], [t].[Name]
FROM [Table_1] AS [t]
WHERE (([t].[Name] <> @__name_0) OR [t].[Name] IS NULL) OR [t].[Name] IS NULL
```

**Comment by ajcvickers** [comment] 2021-09-03 15:33
@Varorbc To be very concrete about relational semantics, adding this to your context configuration:

```C#
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0",
                b => b.UseRelationalNulls())
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

```

And running your code:

```C#
var name = "Varorbc";
var sql = ctx.Table1.Where(a => a.Name != name).ToQueryString();
Console.WriteLine(sql);
```

Results in the query you want:

```sql
SELECT [t].[Id], [t].[CreateTime], [t].[Name]
FROM [Table_1] AS [t]
WHERE [t].[Name] <> @__name_0
```

It's just not the default for the reasons Shay outlined.

**Closed** 2022-10-16 19:44 UTC
Labels: closed-by-design, customer-reported
