### ISSUE TITLE
Is EF Core planning to adopt System.Data.SQLite.Core package in Microsoft.EntityFrameworkCore.Sqlite?

### ISSUE THREAD

**Issue by Lucifer2031** [dotnet/efcore#15154] opened 2019-03-26 05:34 UTC
SQLite has officially released system.data.sqlite.Core package. Is EF Core planning to adopt System.Data.SQLite.Core package in Microsoft.EntityFrameworkCore.Sqlite?

**Comment by ajcvickers** [comment] 2019-03-29 18:56
@Lucifer2031 What are the features from System.Data.SQLite that make it a better solution for you than Microsoft.Data.Sqlite?

(Also note that the Core package for SQLite may not be what you think it is--it's not specifically for .NET Core, but rather is a package that doesn't contain the EF6 integration.)

**Comment by ajcvickers** [comment] 2019-04-05 16:26
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:57 UTC
Labels: closed-no-further-action, customer-reported
