### ISSUE TITLE
2.1 preview performance: Startup is much slower than in 2.0

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#11352] opened 2018-03-20 17:50 UTC
In 2.0, my startup (from starting the application until the first entity is loaded from DB) took about 25 seconds, in a model with 500 or so entities. In the 2.1 preview, it takes about 3 minutes.

In particular, EF is busy for about 1 minute after calling `OnConfiguring` and before calling `OnModelCreating`. This time seems to be independent of the size of the model: even if I have just one single `DbSet` in my Context, it takes 1 minute until `OnModelCreating` is called. However, if I create a new blank project with only a single entity, then `OnModelCreating` is called instantly. So, I suspect that EF spends 1 minute scanning my *entire assembly* - why are you doing this?

This might be somewhat related to issue #11231. My model is completely specified with Code First Fluent API, so EF shouldn't need to scan my assembly, and doing so anyway hurts the performance.

I used "break all" at some point during the time between `OnConfiguring` and `OnModelCreating` to view the call stack:

```
 	Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingInfo.Equals(Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingInfo other = {Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.ConcreteRelationalTypeMappingInfo})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingInfo.Equals(object obj = {Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.ConcreteRelationalTypeMappingInfo})	Unknown	Non-user code. Cannot find or open the PDB file.
 	mscorlib.dll!System.Collections.Generic.ObjectEqualityComparer<System.__Canon>.Equals(System.__Canon x, System.__Canon y)	Unknown	Non-user code. Skipped loading symbols.
 	mscorlib.dll!System.Collections.Concurrent.ConcurrentDictionary<Microsoft.EntityFrameworkCore.Storage.TypeMappingInfo, Microsoft.EntityFrameworkCore.Storage.CoreTypeMapping>.TryGetValue(Microsoft.EntityFrameworkCore.Storage.TypeMappingInfo key = {Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.ConcreteRelationalTypeMappingInfo}, out Microsoft.EntityFrameworkCore.Storage.CoreTypeMapping value = null)	Unknown	Non-user code. Skipped loading symbols.
 	mscorlib.dll!System.Collections.Concurrent.ConcurrentDictionary<Microsoft.EntityFrameworkCore.Storage.TypeMappingInfo, Microsoft.EntityFrameworkCore.Storage.CoreTypeMapping>.GetOrAdd(Microsoft.EntityFrameworkCore.Storage.TypeMappingInfo key = {Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.ConcreteRelationalTypeMappingInfo}, System.Func<Microsoft.EntityFrameworkCore.Storage.TypeMappingInfo, Microsoft.EntityFrameworkCore.Storage.CoreTypeMapping> valueFactory = {Method = Inspecting the state of an object in the debuggee of type System.Delegate is not supported in this context.})	Unknown	Non-user code. Skipped loading symbols.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Storage.TypeMappingSource.FindMappingWithConversion(Microsoft.EntityFrameworkCore.Storage.TypeMappingInfo mappingInfo = {Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.ConcreteRelationalTypeMappingInfo})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(System.Reflection.MemberInfo member = {System.Reflection.RuntimePropertyInfo})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!System.Reflection.PropertyInfoExtensions.FindCandidateNavigationPropertyType(System.Reflection.PropertyInfo propertyInfo = {System.Reflection.RuntimePropertyInfo}, Microsoft.EntityFrameworkCore.Storage.ITypeMappingSource typeMappingSource = {Microsoft.EntityFrameworkCore.Storage.Internal.OracleTypeMappingSource}, Microsoft.EntityFrameworkCore.Metadata.Internal.IParameterBindingFactories parameterBindingFactories = {Microsoft.EntityFrameworkCore.Metadata.Internal.ParameterBindingFactories})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ForeignKeyAttributeConvention.FindCandidateNavigationPropertyType(System.Reflection.PropertyInfo propertyInfo = {System.Reflection.RuntimePropertyInfo})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ForeignKeyAttributeConvention.FindForeignKeyAttributeOnProperty(Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType entityType = {Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType}, string navigationName = "Bemerkung")	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ForeignKeyAttributeConvention.Apply(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder relationshipBuilder = {Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnForeignKeyAdded(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder relationshipBuilder = {Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor.VisitOnForeignKeyAdded(Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnForeignKeyAddedNode node = {Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnForeignKeyAddedNode})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnForeignKeyAddedNode.Accept(Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor visitor = {Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionNode node = {Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnForeignKeyAddedNode})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope node = {Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope.Accept(Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor visitor = {Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionNode node = {Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope node = {Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope.Accept(Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor visitor = {Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionNode node = {Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope node = {Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope.Accept(Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor visitor = {Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionNode node = {Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope node = {Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Dispose()	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.DiscoverRelationships(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder = {Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.Apply(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder = {Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnEntityTypeAdded(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder = {Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAdded(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder = {Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType entityType = {Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(System.Type type = {Name = Inspecting the state of an object in the debuggee of type System.Type is not supported in this context. FullName = Inspecting the state of an object in the debuggee of type System.Type is not supported in this context.}, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource = Explicit)	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Microsoft.EntityFrameworkCore.Metadata.Internal.TypeIdentity type = Inspecting the state of an object in the debuggee of type System.Type is not supported in this context., Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource = Explicit, bool throwOnQuery = true)	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(System.Type type = {Name = Inspecting the state of an object in the debuggee of type System.Type is not supported in this context. FullName = Inspecting the state of an object in the debuggee of type System.Type is not supported in this context.}, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource = Explicit, bool throwOnQuery = true)	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.ModelBuilder.Entity(System.Type type = {Name = Inspecting the state of an object in the debuggee of type System.Type is not supported in this context. FullName = Inspecting the state of an object in the debuggee of type System.Type is not supported in this context.})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.FindSets(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder = {Microsoft.EntityFrameworkCore.ModelBuilder}, Microsoft.EntityFrameworkCore.DbContext context = {PI.PI_STD.DataAccess.Generated.Context.Context})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.FindSets(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder = {Microsoft.EntityFrameworkCore.ModelBuilder}, Microsoft.EntityFrameworkCore.DbContext context = {PI.PI_STD.DataAccess.Generated.Context.Context})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder = {Microsoft.EntityFrameworkCore.ModelBuilder}, Microsoft.EntityFrameworkCore.DbContext context = {PI.PI_STD.DataAccess.Generated.Context.Context})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.Customize(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder = {Microsoft.EntityFrameworkCore.ModelBuilder}, Microsoft.EntityFrameworkCore.DbContext context = {PI.PI_STD.DataAccess.Generated.Context.Context})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(Microsoft.EntityFrameworkCore.DbContext context = {PI.PI_STD.DataAccess.Generated.Context.Context}, Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.IConventionSetBuilder conventionSetBuilder = {Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.CompositeConventionSetBuilder}, Microsoft.EntityFrameworkCore.Infrastructure.IModelValidator validator = {Microsoft.EntityFrameworkCore.Internal.OracleModelValidator})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel.AnonymousMethod__1()	Unknown	Non-user code. Cannot find or open the PDB file.
 	mscorlib.dll!System.Lazy<Microsoft.EntityFrameworkCore.Metadata.IModel>.CreateValue()	Unknown	Non-user code. Skipped loading symbols.
 	mscorlib.dll!System.Lazy<Microsoft.EntityFrameworkCore.Metadata.IModel>.LazyInitValue()	Unknown	Non-user code. Skipped loading symbols.
 	mscorlib.dll!System.Lazy<Microsoft.EntityFrameworkCore.Metadata.IModel>.Value.get()	Unknown	Non-user code. Skipped loading symbols.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(Microsoft.EntityFrameworkCore.DbContext context = {PI.PI_STD.DataAccess.Generated.Context.Context}, Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.IConventionSetBuilder conventionSetBuilder = {Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.CompositeConventionSetBuilder}, Microsoft.EntityFrameworkCore.Infrastructure.IModelValidator validator = {Microsoft.EntityFrameworkCore.Internal.OracleModelValidator})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Internal.DbContextServices.Model.get()	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddCoreServices.AnonymousMethod__7_1(System.IServiceProvider p = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryCallSite factoryCallSite = {Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryCallSite}, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, object>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite = {Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryCallSite}, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope argument = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite}, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, object>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite}, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope argument = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite}, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, object>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite}, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope argument = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite}, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, object>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite}, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope argument = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite}, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.RealizeService.AnonymousMethod__0(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(System.Type serviceType = {Name = Inspecting the state of an object in the debuggee of type System.Type is not supported in this context. FullName = Inspecting the state of an object in the debuggee of type System.Type is not supported in this context.}, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngineScope = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(System.Type serviceType = {Name = Inspecting the state of an object in the debuggee of type System.Type is not supported in this context. FullName = Inspecting the state of an object in the debuggee of type System.Type is not supported in this context.})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(System.IServiceProvider provider = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope}, System.Type serviceType = {Name = Inspecting the state of an object in the debuggee of type System.Type is not supported in this context. FullName = Inspecting the state of an object in the debuggee of type System.Type is not supported in this context.})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Microsoft.EntityFrameworkCore.Internal.IDbContextDependencies>(System.IServiceProvider provider = {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope})	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.DbContext.DbContextDependencies.get()	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.DbContext.InternalServiceProvider.get()	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.DbContext.ChangeTracker.get()	Unknown	Non-user code. Cannot find or open the PDB file.
>	PI.Lib.DataAccess.dll!PI.Lib.DataAccess.EF.ContextBase.ContextBase(System.Data.Common.DbConnection connection = {Oracle.DataAccess.Client.OracleConnection}) Line 104	C#	Symbols loaded.
 	PI.PI_STD.DataAccess.dll!PI.PI_STD.DataAccess.Generated.Context.Context.Context(System.Data.Common.DbConnection con = {Oracle.DataAccess.Client.OracleConnection}) Line 33	C#	Symbols loaded.
 	PI.PI_STD.DataAccess.dll!PI.PI_STD.DataAccess.EF.ContextFactory.CreateContext(out PI.Lib.DataAccess.EF.ContextTicket ticket = null, string schemaName = "") Line 40	C#	Symbols loaded.
 	EfTest.exe!EfTest.Program.Main(string[] args = {string[0]}) Line 30	C#	Symbols loaded.
```

**Comment by ajcvickers** [comment] 2018-03-20 22:27
Note for triage: related to data in #1906 and related to work tracked by #11358 and #11196

**Comment by ajcvickers** [comment] 2018-03-22 03:14
Triage: closing as duplicate of the issues mentioned above, since those issues are tracking model building perf in 2.1.

**Closed** 2022-10-16 12:15 UTC
