### ISSUE TITLE
RowLimitingOperationWithoutOrderByWarning false positive

### ISSUE THREAD

**Issue by Kovbasiuk-Mykhailo** [dotnet/efcore#30550] opened 2023-03-22 11:06 UTC
Having this query generated by EF Core there is RowLimitingOperationWithoutOrderByWarning reported. Although it seems like the query has ordering in place.
This query was generated by OData when trying to $select a nested property which is a collection itself.

```SQL
SELECT [t].[Id], [t0].[ModelID], [t0].[DeviceId], [t0].[Type], [t0].[CreatedBy], [t0].[CreatedOn], [t0].[Thumbprint], [t0].[ValidFrom], [t0].[ValidTo], [t0].[Value], [t0].[UseInstanceForProperties]
FROM (
    SELECT TOP(@__TypedProperty_3) [d].[Id], [d].[SequenceNumber]
    FROM [Device].[Devices] AS [d]
    ORDER BY [d].[SequenceNumber]
) AS [t]
LEFT JOIN (
    SELECT [t1].[ModelID], [t1].[DeviceId], [t1].[Type], [t1].[CreatedBy], [t1].[CreatedOn], [t1].[Thumbprint], [t1].[ValidFrom], [t1].[ValidTo], [t1].[Value], [t1].[UseInstanceForProperties]
    FROM (
        SELECT @__TypedProperty_2 AS [ModelID], [c].[DeviceId], [c].[Type], [c].[CreatedBy], [c].[CreatedOn], [c].[Thumbprint], [c].[ValidFrom], [c].[ValidTo], [c].[Value], CAST(1 AS bit) AS [UseInstanceForProperties], ROW_NUMBER() OVER(PARTITION BY [c].[DeviceId] ORDER BY [c].[DeviceId], [c].[Type]) AS [row]
        FROM [Device].[Certificates] AS [c]
    ) AS [t1]
    WHERE [t1].[row] <= @__TypedProperty_1
) AS [t0] ON [t].[Id] = [t0].[DeviceId]
ORDER BY [t].[SequenceNumber], [t].[Id], [t0].[DeviceId]
```

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 7.0)

**Comment by roji** [comment] 2023-03-22 14:00
@Kovbasiuk-Mykhailo can you please try to post the LINQ query that produces this SQL? I know that you're using OData which produces the query tree, but you should be able to extract the LINQ query from it.

**Comment by ajcvickers** [comment] 2023-04-05 17:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-04-05 17:20 UTC
Labels: customer-reported
