### ISSUE TITLE
Sqlite Query: Don't apply BooleanExpressionTranslatingVisitor

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#13444] opened 2018-09-28 21:52 UTC
Because of SQLite's dynamic typing, there is no need to apply `BooleanExpressionTranslatingVisitor` on SQLite.

This is sufficient...

``` sql
SELECT X < 3
```

...and doesn't need to be translated to this.

``` sql
SELECT CASE
    WHEN X < 3
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END
```

**Comment by dmitry-lipetsk** [comment] 2018-09-29 08:58
@bricelam, you stole this problem from me :)

https://github.com/aspnet/EntityFrameworkCore/issues/13364#issuecomment-425629074

**Comment by bricelam** [comment] 2018-09-30 00:27
I slept on this, and realized it's probably was to account for `NULL`. In the database `X < 3` when `X` is `NULL` is neither `1` nor `0`, but `NULL`.

The only thing I'd change on SQLite is to remove the `CAST` since it's unnecessary.

**Comment by ajcvickers** [comment] 2018-10-03 18:41
Duplicate of #10513

**Closed** 2022-10-16 13:33 UTC
