### ISSUE TITLE
SetCommandTimeout does not SetCommandTimeout for connection.CreateCommand()

### ISSUE THREAD

**Issue by jaredcnance** [dotnet/efcore#6246] opened 2016-08-04 15:26 UTC
### Steps to reproduce

```
var connection = _context.Database.GetDbConnection();
if (connection.State != ConnectionState.Open)
  connection.Open();

_context.Database.SetCommandTimeout(180);
Console.WriteLine(connection.ConnectionTimeout);
using (var command = connection.CreateCommand())
{
  Console.WriteLine(command.CommandTimeout);
  _context.Database.SetCommandTimeout(180);
  Console.WriteLine(command.CommandTimeout);
  command.CommandText = myLongRunningQuery;

  using (var reader = command.ExecuteReader())
  {
    while (reader.Read())
    {
        // do stuff...
    }
  }
}
```
### The issue

I have a medium sized database (a few M records) and I am trying to run a query to create a report. Unfotunately, the most optimized command is not currently supported via LINQ. So, I'm using the above code to run the query. The query takes ~60s to run, but it times out. The `Console.WriteLine` methods produce the following:

```
200 // connection timeout
30 // command timeout before trying to set
30 // command timeout after trying to set
```

The command always times out at 30s.
But `Context.Database.GetCommandTimeout() = 180`. So, am I not creating the command object properly? I would imagine the preferred method is something like: `Context.MyEntities.FromSql(query)` or `Context.Database.ExecuteSqlCommand(query)`, but the problem is that the query results cannot be mapped to MyEntity and I need the results of the query not just the # of rows affected. 

```
Exception message: 
   An unhandled exception was thrown by the application.
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out

Stack trace:
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at david.web.Controllers.ReportsController.<>c__DisplayClass3_4.<GetUsage>b__3(<>f__AnonymousType3`2 dataFactory)
   at AutoMapper.Internal.EnumerableExtensions.Each[T](IEnumerable`1 items, Action`1 action)
   at david.web.Controllers.ReportsController.<>c__DisplayClass3_3.<GetUsage>b__2(DataType dataType)
   at AutoMapper.Internal.EnumerableExtensions.Each[T](IEnumerable`1 items, Action`1 action)
   at david.web.Controllers.ReportsController.<GetUsage>d__3.MoveNext()
```
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 7
Visual Studio version: 2015 Pro

Other details about my project setup:
Azure SQL database

**Comment by natemcmaster** [comment] 2016-08-04 16:24
The `.SetCommandTimeout` API controls how EF [internally creates a `DbCommand`](https://github.com/aspnet/EntityFramework/blob/1.0.0/src/Microsoft.EntityFrameworkCore.Relational/Storage/Internal/RelationalCommand.cs#L427-L430), but in the code you shared above you have dropped down into the layer below EF. You can set the timeout on a DbCommand by setting the CommandTimeout property manually. 
```c#
DbConnection connection = _context.Database.GetDbConnection();
DbCommand command = connection.CreateCommand();
command.CommandTimeout = 180; // <--- you have to set this every time you create a new DbCommand
```

See https://docs.microsoft.com/en-us/dotnet/core/api/system.data.common.dbcommand#System_Data_Common_DbCommand

Closing as the code above is working as designed, but feel free to continue discussion.

**Comment by ajcvickers** [comment] 2016-08-04 16:26
@jaredcnance Looks like you are getting the ADO.NET DbConnection object and then creating the command directly from that. Once you get the DbConnection this is not EF code anymore and EF has no way to set the command timeout. The command timeout on the EF level is set onto the underlying command when EF creates commands internally. You should set the timeout on the DbCommand directly after creating it.

Note for triage: should we consider a way for people to get a DbCommand directly that would do things like set the command timeout?

**Comment by ajcvickers** [comment] 2016-08-04 16:26
Re-opening so we can discuss in triage.

**Comment by jaredcnance** [comment] 2016-08-04 16:31
Fair enough, I didn't realize I had dropped down into `System.Data` and for some reason I thought `command.CommandTimeout` was readonly. This makes the most sense since I am not leaning on EF to map back to an entity. It does seem properly outside the scope of EF. Thanks for clarifying.

**Comment by divega** [comment] 2016-08-08 18:25
**Triage:** We will look for more feedback for configuring the `DbCommand` the same way EF Core would do it, but at the moment we don't think there is enough value to provide an API.

**Comment by derekgreer** [comment] 2018-10-08 22:10
I know this issue is closed, but I will say that this isn't at all intuitive behavior.  If you had a class DynamicHouse that had a SetDefaultLightSwitchToggle(Toggle.Off) and then you called _dynamicHouse.CreateRoom() which returned an instance of class Room which had a DefaultLightSwitchToggle property, what would you expect that value to be?  It just doesn't make sense for a composing object to have a factory method to create an object that shares the same property as the composing object and for it to not default the value to be that of the composing object.

**Comment by fededim** [comment] 2021-01-29 16:26
I'm experiencing the same issue in my project, I would agree that the context's timeout value should be reapplied also to manually created dbcommands from the context, yet I acknowledge that the command timeout property is only present in DbCommand and not in DbConnection (returned from context.Database.GetDbConnection) so this is probably unfeasible without changing DbConnection classes.

**Comment by ErikEJ** [comment] 2021-01-29 16:36
If you use SqlClient and update to 2.1, you can set the default command timeout via the connection string!

**Comment by fededim** [comment] 2021-01-29 16:48
Are you sure ? In [SqlConnectionStringBuilder documentation](https://docs.microsoft.com/en-GB/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder?view=dotnet-plat-ext-5.0) there are only 2 timeouts: ConnectTimeout and LoadBalanceTimeout. What is the name of the new parameter ?
In any case this is a global setting, maybe someone needs to change it in different situations by modifying the context property.

**Comment by ErikEJ** [comment] 2021-01-29 16:53
Yes, I am sure: https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionstringbuilder?view=sqlclient-dotnet-core-2.1

**Comment by fededim** [comment] 2021-01-29 17:00
Yep you're right CommandTimeout right there, thank you very much for the
hint!

**Comment by gfody** [comment] 2022-05-10 00:02
hit this today, I'd vote to reopen, having to use this seemingly unnecessary code in extension methods that drop down to ado:
```
using (var command = context.Database.GetDbConnection().CreateCommand())
{
    command.CommandTimeout = context.Database.GetCommandTimeout() ?? 0;
    ...
```

..no other method would be appropriate because the caller may have overridden the command timeout via `Database.SetCommandTime()`

**Comment by gfody** [comment] 2022-05-10 22:30
hit this again, it's not just when dropping down to ado - consider this extension method:
```
public static IQueryable<T> SqlQuery<T>(this DbContext context, string sql, params object[] parameters) where T : class
    => new ContextForQueryType<T>(context.Database).Set<T>().FromSqlRaw(sql, parameters);

private class ContextForQueryType<T> : DbContext where T : class
{
    private readonly DbConnection _connection;

    public ContextForQueryType(DatabaseFacade database)
    {
        _connection = database.GetDbConnection();
        base.Database.SetCommandTimeout(database.GetCommandTimeout()); // https://github.com/dotnet/efcore/issues/6246
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(_connection);
        base.OnConfiguring(optionsBuilder);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<T>().HasNoKey();
        base.OnModelCreating(modelBuilder);
    }
}

```

**Comment by ErikEJ** [comment] 2022-05-11 04:43
You can  set the CommandTimeout in the connection string these days.

**Comment by gfody** [comment] 2022-05-11 05:08
> You can  set the CommandTimeout in the connection string these days.

SetCommandTimeout is handy for specific queries expected to run longer than what you want to configure globally via connection string (or di, etc).

**Closed** 2022-10-16 09:53 UTC
Labels: closed-no-further-action, customer-reported

**Comment by jmb-mage** [comment] 2023-08-22 20:27
```
database.SetCommandTimeout(60);
var uWu = database.GetCommandTimeout();
```
uWu is null. 🌝

**Comment by taylorchasewhite** [comment] 2023-10-31 13:11
> ```
> database.SetCommandTimeout(60);
> var uWu = database.GetCommandTimeout();
> ```
> 
> uWu is null. 🌝

I got this too 👎☹️

**Comment by jmb-mage** [comment] 2023-10-31 13:42
@taylorchasewhite the way I solved this is to borrow Dapper `Query` for stored procedures and then have Dictionary of stored procedure names which will return a default or specified timeout to Dapper.  It was one of the only places I felt _forced_ to use an library other than EF Core.

**Comment by taylorchasewhite** [comment] 2023-10-31 13:44
> he way I solved this is to borrow Dapper `Query` for stored procedures and then have Dictionary of stored procedure names which will return a default or specified timeout to Dapper. It was one of the only places I felt _forced_ to use an library other than EF Core.

Nice. Thanks for the reply, I really appreciate it. Hopefully this gets cleaned up.
