### ISSUE TITLE
Consider obtaining method infos from compiler generated expressions (may help with UWP/.NET Native)

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#3294] opened 2015-10-01 18:58 UTC
[`Queryable`](https://github.com/dotnet/corefx/blob/master/src/System.Linq.Queryable/src/System/Linq/Queryable.cs) uses this pattern:

``` C#
       public static IQueryable<TSource> Where<TSource>(
           this IQueryable<TSource> source, 
           Expression<Func<TSource, bool>> predicate) 
       { 
           if (source == null) 
               throw Error.ArgumentNull("source"); 
           if (predicate == null) 
               throw Error.ArgumentNull("predicate"); 
           return source.Provider.CreateQuery<TSource>( 
               Expression.Call( 
                   null, 
                   GetMethodInfoOf(() => Queryable.Where( 
                       default(IQueryable<TSource>), 
                       default(Expression<Func<TSource, bool>>))), 
                   new Expression[] { source.Expression, Expression.Quote(predicate) } 
                   )); 
       } 
...
       private static MethodInfo GetMethodInfoOf<T>(Expression<Func<T>> expression) 
       { 
           var body = (MethodCallExpression)expression.Body; 
           return body.Method; 
       } 
```

We haven't tested yet if this actually helps but it avoids using reflection directly at runtime and in particular `MakeGeneticMethod<T>()` [which is known to be problematic with .NET Native](https://github.com/aspnet/EntityFramework/issues/3293#issuecomment-144783787).

cc @natemcmaster @anpete

**Comment by rowanmiller** [comment] 2015-10-02 19:31
@natemcmaster you may want to do this earlier to reduce directives for .NET Native

**Comment by natemcmaster** [comment] 2015-10-05 18:00
This won't work. LINQ uses `Type.MakeGenericMethod` under the hood.
See 
https://github.com/Microsoft/referencesource/blob/74706335e3b8c806f44fa0683dc1e18d3ed747c2/System.Core/Microsoft/Scripting/Ast/MethodCallExpression.cs#L999.

**Comment by divega** [comment] 2015-10-05 18:03
Interesting. Then does Queryable currently not work at all in .NET Native?

**Comment by natemcmaster** [comment] 2015-10-05 18:07
The problem is in `Expression.Call`. The overload used in the example above does not trigger a call to `MakeGenericMethod`

**Comment by divega** [comment] 2015-10-05 19:06
Still don't understand why it wouldn't work for us, sorry about that :smile: Will probably ask you in person.

**Comment by natemcmaster** [comment] 2015-10-05 19:14
Discussed in person. Will investigate more.

**Comment by natemcmaster** [comment] 2016-02-05 18:43
After further investigation, refactoring our code to avoid calls to `MakeGenericMethod` is unnecessary, at least for the sake of .NET Native. With `RuntimeTypeDiscoverer` and the `Scaffold-Directives` command (see https://github.com/aspnet/EntityFramework/pull/4197), we can generate most of the rdxml necessary to make these calls work in current UWP tooling. Furthermore, updates to .NET Native include bug fixes that alleviate these problematic scenarios. I recommend closing this issue.

**Comment by divega** [comment] 2016-02-05 22:09
Closing as per @natemcmaster's comment.

**Closed** 2022-10-16 09:10 UTC
Labels: type-cleanup, closed-out-of-scope
