### ISSUE TITLE
Nullable Reference Type for FirstOrDefaultAsync

### ISSUE THREAD

**Issue by Vake93** [dotnet/efcore#19443] opened 2019-12-31 15:48 UTC
My project has nullable reference types enabled and the following code has the warning CS8619 Nullability of reference types in value of type 'Task<User>' doesn't match target type 'Task<User?>'.

![image](https://user-images.githubusercontent.com/8337494/71626583-04387b80-2c14-11ea-97bd-234195011c25.png)

FirstOrDefaultAsync can return null and shouldn't FirstOrDefaultAsync return Task<User?> ?

### Further technical details

EF Core version: 3.1.0
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 3.1.0
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.2

**Comment by ajcvickers** [comment] 2020-01-02 19:07
@roji Thoughts?

**Comment by mqudsi** [comment] 2020-01-02 21:52
Is there a master issue tracking issues relating to non-nullable reference types, or is there a document containing known issues or limitations? We're seeing some nullability confusion regarding the values passed in to linq functors or as return values from linq expressions.

**Comment by roji** [comment] 2020-01-03 12:03
Yeah, we need to annotate our async LINQ extensions for nullability - this is part of #19007. We can close this as a duplicate of that, although there may be value in keeping this open as it's a particularly visible area of the API. Note that System.Linq [has already been annotated](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq/src/System/Linq/First.cs), so we should be following that (although async may make that a bit challenging).

> Is there a master issue tracking issues relating to non-nullable reference types, or is there a document containing known issues or limitations?

There's [the Nullable Reference Types doc page](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types) which contains most information NRTs, I'll add a note about this current limitation.

**Comment by roji** [comment] 2020-01-03 12:10
Submitted https://github.com/aspnet/EntityFramework.Docs/pull/2022

**Comment by prashantaggarwal1990** [comment] 2021-04-29 14:58
I am facing an issue after converting the project from .Net core 2.1 to 3.1. I have following linq code:

var query = _context.FileDescriptor.Where(x => x.ClientId == clientId);
var finalQuery = from entity in testquery
join nextVersion in testquery on entity.Id equals nextVersion.PreviousRevisionId into nextVersions
where !nextVersions.Any() && !entity.IsDeleted && entity.FolderId == folderId
select entity
return await finalQuery.FirstOrDefaultAsync(d => !d.IsDeleted && d.FolderId == folderId && d.FileName == fileName, token);

Getting the below error while executing:
System.InvalidOperationException: Processing of the LINQ expression 'DbSet
.Where(x => x.ClientId == __clientId_0)
.GroupJoin(
outer: DbSet
.Where(x => x.ClientId == __clientId_0),
inner: entity => (Nullable)entity.Id,
outerKeySelector: nextVersion => nextVersion.PreviousRevisionId,
innerKeySelector: (entity, nextVersions) => new {
entity = entity,
nextVersions = nextVersions
})' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_01.<ExecuteAsync>b__0() at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func1 compiler)
at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func1 compiler) at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable1 source, Expression expression, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable1 source, LambdaExpression expression, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable1 source, Expression`1 predicate, CancellationToken cancellationToken)
Please help..

**Closed** 2022-10-16 18:03 UTC
Labels: closed-duplicate, customer-reported
