### ISSUE TITLE
I think there is a design flaw in the Entity Framework Core command line tool.

### ISSUE THREAD

**Issue by daodol** [dotnet/efcore#13663] opened 2018-10-18 02:47 UTC
Entity change impact table structure。
But I think we should compare entities with the table structure and then judge the change of migration.
From what I've seen in my use, this tool only detects entity changes, and then generates migrations directly to modify the table, instead of detecting what the current table structure looks like.

**Comment by ajcvickers** [comment] 2018-10-18 15:19
Duplicate of #831

**Closed** 2022-10-16 13:35 UTC
Labels: customer-reported
