### ISSUE TITLE
update-database not updating new columns of a created table

### ISSUE THREAD

**Issue by amirzandi** [dotnet/efcore#6097] opened 2016-07-17 08:42 UTC
Hello All,
the first time I have ran add-migration [name], it worked like a charm and created a directory named Migration including all required files as well. 

After I updated my table class file and added a new column into it, I ran add-migration [newname] and it successfully created the file. In this new file, it attempts to re-create my tables again and it causes an error which is  There is already an object named 'TableName' in the database.

I have done a lot of googles, but nothing found except some manual codes.

What I wanted to know is that, every time that I need to manage and update my tables, I need to edit the class file of migrations??????? It seems not easy and rational.

Is there anyone facing this problem, or if there is a solution for this matter, I'd appreciate your helps.

PS. Either update-database -verbose or add-migration [name] -ignorechanges are showing up with a RED ERROR that this command is not included Entity Framework.

Please help.

**Comment by rdefreitas** [comment] 2016-07-18 10:48
@amirzandi can you reproduce this in a brand new project?

Also, can you provide the following?

EF Core version: (found in project.json or packages.config)
Operating system: 
Visual Studio version: (e.g. VS 2013 or n/a)

**Comment by rowanmiller** [comment] 2016-07-20 18:23
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bug, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

**Comment by rowanmiller** [comment] 2016-07-25 20:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 09:51 UTC
