### ISSUE TITLE
An issue with query filtering and aggregation, after upgrading from 6.0.0 to 6.0.16

### ISSUE THREAD

**Issue by ofirbelenky** [dotnet/efcore#33001] opened 2024-02-04 09:34 UTC
Hey,
You can see in this discussion the issue that we have:
https://github.com/dotnet/efcore/issues/31255

We created small project that reproduces this issue.
Can you please give it a look and help us solve it?
[EntityFrameWorkProjectDemo.zip](https://github.com/dotnet/efcore/files/14156206/EntityFrameWorkProjectDemo.zip)

**Comment by ajcvickers** [comment] 2024-02-05 09:47
Note for EF team: Likely duplicate of #27433. Verified that this work with 6.0.1, and was broken in 6.0.2. This was fixed for 7 and 8.

**Comment by ajcvickers** [comment] 2024-02-09 10:21
Note from team: the issue is fixed in 7 and 8 (LTS). We don't believe this means the bar for a 6.0.x patch at this time.

**Closed** 2024-02-09 10:20 UTC
Labels: closed-duplicate, customer-reported
