### ISSUE TITLE
EntityFrameworkCore.Sqlite 2.1.4 nuget lib empty

### ISSUE THREAD

**Issue by RaoufOsman** [dotnet/efcore#18852] opened 2019-11-12 02:03 UTC
Hi this is my first issue. I emailed from nuget website and was told to post here. Sorry if I didn’t follow all the instructions. I can try to provide more details. Issue is pretty straightforward. 

I’m working on a Xamarin project and we are using Microsoft.EntityFrameworkCore.Sqlite v2.1.4. We haven’t upgraded to 3.0.0 yet (coming soon). We had a prod build and we noticed an issue with the nuget package. The netstandard2.0/lib folder only contained a file that was named “_._” with a size of zero bytes. There was no dll there.  

### Steps to reproduce
Add reference to Microsoft.EntityFrameworkCore.Sqlite -v 2.1.4 to Xamarin.iOS project. Make a call to db and you’ll get a FileNotFoundException. 

Got Exceptions? Include both the message and the stack trace

Posting from my phone. Can’t upload exceptions. 

### Further technical details

EF Core version: 2.1.4
Database provider: Sqlite
Target framework: xamarinios10
Operating system: Mac OS (Catalina)
IDE: Visual Studio for Mac

Only workaround was to get the dll from a developers machine nuget cache packages folder.

**Comment by ajcvickers** [comment] 2019-11-13 16:39
@RaoufOsman Thanks for filing this issue. We will discuss in our next triage meeting.

/cc @bricelam

**Comment by ajcvickers** [comment] 2019-11-15 21:00
@RaoufOsman 2.1.4 is an old version. Have you tried this with 2.1.11 or anything newer?

**Comment by ajcvickers** [comment] 2019-11-22 22:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:55 UTC
Labels: closed-could-not-reproduce, customer-reported
