### ISSUE TITLE
ef dbcontext scaffold command fails on Azure Function project

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/efcore#14084] opened 2018-12-05 13:27 UTC
Running `dotnet ef dbcontext scaffold` on an Azure Function project fails.

The root cause of the failure is the combined behavior of the Azure Functions SDK and the EF tools. Azure Functions SDK redirects the build output to `$(OutDir)/bin` [here](https://github.com/Azure/azure-functions-vs-build-sdk/blob/c48944fafb50a23e33344006779bf5005391965c/src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets#L60). But right after the build is done it resets the `OutDir` property back to the original. I assume EF reads the property value and expects (sort of correctly) that the dll will be there.

For more details and a repro please see dotnet/core-setup#3965

**Comment by bricelam** [comment] 2018-12-07 18:46
Duplicate of Azure/azure-functions-host#2408?

**Comment by divega** [comment] 2018-12-07 20:10
EF Team Triage: We don't believe this is actionable on the EF Core side. It is an issue in Azure functions. The general workaround is to create a separate project that is not an Azure functions project to maintain your migrations.

**Comment by jefferykhan** [comment] 2021-06-11 19:35
I have found that this can still happen if your Azure Function project has a dependency on your EF project.  I was able to work around it by unloading the Azure Function project and then run the command against the EF project.

**Closed** 2022-10-16 13:42 UTC
Labels: closed-external, customer-reported
