### ISSUE TITLE
Owned entity marked as "Deleted" do not show up in their Owners "References" collection

### ISSUE THREAD

**Issue by nextstep79** [dotnet/efcore#25750] opened 2021-08-27 15:32 UTC
This might not well be a bug, but intended behavior - however, see below.

**Scenario:** "Order" entity and "ShippingAddress" as owned entity, configured as:

```C#
modelBuilder.Entity<Order>().OwnsOne(p => p.ShippingAddress);
```

**Issue:**

While updating the owned entity, in appears in the "References" collection of the Order:

e.g ShippingAddress is modified and the following code returns the related order:

```C#
ChangeTracker.Entries().Where(x => x.References.Any(y => y.TargetEntry != null && y.TargetEntry.State == **EntityState.Modified**));
```

However, while _deleting_ the owned entity the following code returns NO orders:

```C#
ChangeTracker.Entries().Where(x => x.References.Any(y => y.TargetEntry != null && y.TargetEntry.State == **EntityState.Deleted**));
```

Why so? I would expect deleted entities also to show up in the references collection.

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system:
IDE: Visual Studio 2019 16.11.2

**Comment by ajcvickers** [comment] 2021-08-28 08:45
@nextstep79 I am not able to reproduce this; see my code below. It may depend what you mean by _deleted_. In the code below I mark the address as Deleted and it shows up as Deleted in the change tracker:

```
Address {OrderId: 1} Deleted
  OrderId: 1 PK FK
  Postcode: 'DN37 7RU'
Order {Id: 1} Unchanged
  Id: 1 PK
  ShippingAddress: {OrderId: 1}
```

And the order is included in the list of entries returned:

![image](https://user-images.githubusercontent.com/1430078/131211895-bf58ae0b-a9be-48ae-86e8-1c4f7fe9fdfc.png)

However, if I simply null out the `ShippingAddress` property, then the address is marked as deleted:

```
Address {OrderId: 1} Deleted
  OrderId: 1 PK FK
  Postcode: 'DN37 7RU'
Order {Id: 1} Unchanged
  Id: 1 PK
  ShippingAddress: <null>
```

But the order doesn't show up in the list returned by `References` because the order no longer references the address:

![image](https://user-images.githubusercontent.com/1430078/131212032-280d21c7-3253-4464-abec-5d40b3f8e2ee.png)

My code:

```C#
public class Order
{
    public int Id { get; set; }
    public Address ShippingAddress { get; set; }
}

public class Address
{
    public string Postcode { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .LogTo(Console.WriteLine, LogLevel.Information)
            .UseSqlServer(Your.ConnectionString)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Order>().OwnsOne(p => p.ShippingAddress);
    }

    public DbSet<Order> Orders { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.AddRange(new Order { ShippingAddress = new Address { Postcode = "DN37 7RU"}});
            
            context.SaveChanges();
        }

        using (var context = new SomeDbContext())
        {
            var order = context.Orders.Single();

            //order.ShippingAddress = null;
            
            context.Remove(order.ShippingAddress);

            var entries = context.ChangeTracker.Entries()
                .Where(x => x.References.Any(y => y.TargetEntry != null 
                                                  && y.TargetEntry.State == EntityState.Deleted))
                .ToList();
        }
    }
}
```

**Comment by nextstep79** [comment] 2021-08-28 10:06
Yes - in can see that now - I am nulling out the `ShippingAddress` and therefore it does not shows up in the `References` list of the `Order`.

In my scenario deletion might happen just this way, nulling out the `ShippingAddress`. While `SaveChanges` - I´d like to be able to determine the Order of the ShippingAddress being in state Deleted.

Is there any way I can achieve that looking at the ShippingAddress `EntityEntry` - or any way that you can suggest?

**Comment by ajcvickers** [comment] 2021-08-31 10:58
@nextstep79 You can match the Order to its ShippingAddress by matching the order PK property value to the address FK property values. You can see these values in the debug view output I showed above.

**Closed** 2022-10-16 19:44 UTC
Labels: closed-no-further-action, customer-reported
