### ISSUE TITLE
string.Contains Lambda Where Expression fails EF Core 3.1

### ISSUE THREAD

**Issue by JohnGalt1717** [dotnet/efcore#20057] opened 2020-02-25 16:21 UTC
Entity Framework Core 2.2 with throw on client evaluation allows you to do the following:
```
var query = from o in _DbContext.Organizations
						orderby o.Name
						select new AdminOrganizationDto
						{
							Id = o.Id,
							Name = o.Name
						};


			var paramExp = Expression.Parameter(typeof(AdminOrganizationDto), "x");
			
			var memberExpression = Expression.Property(paramExp, "Name");
			var method = typeof(string).GetMethod("Contains", new[] { typeof(string) });
			var valExpression = Expression.Constant("test", typeof(string));

			var containsMethodExp = Expression.Call(memberExpression, method, valExpression);

			var lam = Expression.Lambda<Func<AdminOrganizationDto, bool>>(containsMethodExp, paramExp);

			query = query.Where(lam);

			var results = await query.ToArrayAsync();
```

Where AdminOrganization has the following structure:

public abstract class BaseDto => public class OrganizationDto : BaseDto => public class AdminOrganizationDto : OrganizationDto.

In EF Core 3.1 this fails with the following:

```
 System.InvalidOperationException : The LINQ expression 'DbSet<Organization>
        .OrderBy(o => o.Name)
        .Where(o => new AdminOrganizationDto{ 
            Id = o.Id, 
            Name = o.Name 
        }
        .Name.Contains("aecom"))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

If AdminOrganizationDto inherits directly from BaseDto or any other abstract class it works fine. As soon as AdminOrganizationDto inherits from a concrete class, it fails. The structure doesn't matter, but in my case BaseDto has an Id property, and OrganizationDto has a string Name {get; set;} property and AdminOrganization has other fields but it doesn't matter if it does or not..

**Why this matters?**

It breaks oData querying at runtime when it used to work just fine in .NET core 2.2 with throw on client evaluation turned on.

### Further technical details
EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: e.g. Visual Studio 2019 16.4

**Comment by smitpatel** [comment] 2020-02-25 16:57
Duplicate of #19087 
Being considered for patching in 3.1.x

**Closed** 2022-10-16 18:13 UTC
Labels: closed-duplicate, customer-reported
