### ISSUE TITLE
The function created by SqliteConnection.CreateFunction doesn't provide the correct byte[] parameter

### ISSUE THREAD

**Issue by KevinWan-ThinkGeo** [dotnet/efcore#18328] opened 2019-10-11 05:36 UTC
The function created by SqliteConnection.CreateFunction doesn't provide the correct byte[] parameter.

### To Reproduce

I create a [sample](https://github.com/KevinWan-ThinkGeo/Microsoft.Data.Sqlite-Sample) to reproduce this issue.

There are "geometry" and "geometryString" in the output of this sample. The "geometryString" is a string field that converted from "geometry"(byte array field) by the "CS_GeometryString" function. And I convert the "geometry" to string when I output it to the console. So they should be the same in the output. (But they don’t.) That means the "geometry" is not passed to the "CS_GeometryString" function correctly.

And it is strange that the preview version of the Microsoft.Data.Sqlite package(3.0.0-preview5.19227.1) doesn’t have this bug.

### Additional context

Microsoft.Data.Sqlite version: 3.0.0
Target framework: .NET Core 3.0
Operating system: Win10

**Comment by bricelam** [comment] 2019-10-16 17:44
Does it work if you update SQLitePCL.raw to 2.0.1? Could be the same root cause as https://github.com/ericsink/SQLitePCL.raw/issues/289

**Comment by bricelam** [comment] 2019-10-16 17:46
```xml
<ItemGroup>
  <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.0.1" />
</ItemGroup>
```

**Comment by bricelam** [comment] 2019-10-16 21:38
Confirmed. Updating SQLitePCL.raw fixed your sample. Closing as external. Note, we've already updated to this version in 3.1.0-preview1

**Comment by KevinWan-ThinkGeo** [comment] 2019-10-17 02:14
When I added the reference of "SQLitePCLRaw.bundle_e_sqlite3" package, it can work. But when I removed this package and updated the "Microsoft.Data.Sqlite" to 3.1.0-preview.1.19506.2, the sample can't work again.(the byte array is different with the 3.0.0)

**Comment by bricelam** [comment] 2019-10-17 05:46
Ah, looks like the change didn’t make it into preview1.

**Closed** 2022-10-16 14:49 UTC
Labels: closed-external, customer-reported, area-adonet-sqlite
