### ISSUE TITLE
WHERE with tuples and IN operator

### ISSUE THREAD

**Issue by rspadim** [dotnet/efcore#31492] opened 2023-08-17 14:04 UTC
Hello, I have a table with a primary key using two columns "id1, id2"

I want to search rows that contains, something like a "WHERE (id1,id2) IN ((1,1), (2,2), (3,3))"

At C# i have a list of tupple of int,int, could be possible execute this query using EF?

thanks

**Comment by roji** [comment] 2023-08-17 16:34
Duplicate of #26822

**Comment by roji** [comment] 2023-08-17 16:36
EF currently doesn't support expressing this; #26822 should make that possible. Note that SQL Server doesn't support this at all.

In the meantime, you should be able to rewrite this simply as `WHERE (id1 = 1 AND id2 = 1) OR (id1 = 2 AND (id2 = 2)` and so forth. The generated SQL is longer/uglier but I'm pretty sure there wouldn't be a performance difference (would be happy to hear about it if otherwise!).

**Closed** 2023-09-06 18:48 UTC
Labels: closed-duplicate, customer-reported
