### ISSUE TITLE
EntityFrameworkCore slow with Oracle NLS_COMP = LINGUISTIC NLS_SORT = BINARY_CI

### ISSUE THREAD

**Issue by sorcerb** [dotnet/efcore#35061] opened 2024-11-07 13:57 UTC
Hello,
Problem the request is taking too long when Session set NLS_COMP = LINGUISTIC NLS_SORT = BINARY_CI

It was tested with different Devart.Data.Oracle and Oracle.EntityFrameworkCore providers with Oracle 19c version.

After all the tests I conclude that:
1. The indexes do not work as they should.
2. Maybe the request is still being processed in the EF somehow.

All this selects in database tools (dbeaver and plsql) give good preformance, about 5-20ms.
In the small table the result is returned quickly.
If take only 1-5 rows ( Take(1) ) - the result will be fast, if it found it. If not, it will be slow - possible do a full scan.

Create simple table:
```
CREATE TABLE app."Customer" (
  "Id" NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Name" NVARCHAR2(254),
  PRIMARY KEY ("Id")
)
```
Add 2 indexes:
```
CREATE INDEX app."IX_Customer_Name_NLS" ON app."Customer" (NLSSORT("Name", 'NLS_SORT=BINARY_CI'))
CREATE INDEX app."IX_Customer_Name" ON app."Customer" ("Name")
```
Fill data with 2 000 000 rows:
```
BEGIN
    FOR i IN 1..2000000 LOOP
        INSERT INTO app."Customer" ("Name")
        VALUES (
            DBMS_RANDOM.STRING('U', 10)
        );

        IF MOD(i, 10000) = 0 THEN
            COMMIT;
        END IF;
    END LOOP;

    COMMIT;
END;
```

I try make 4 different query:
BINARY+BINARY
LINGUISTIC +BINARY
BINARY+BINARY_CI
LINGUISTIC +BINARY_CI
```
private static async Task<string> GetCustomerTime(
        string name, PersonsContext context, CancellationToken cancellationToken = default)
    {
        var timings = new StringBuilder();
        const string query = """SELECT * FROM app."Customer" WHERE "Name" LIKE {0} || '%'""";

        await context.Database.ExecuteSqlRawAsync("ALTER SESSION SET NLS_COMP = BINARY NLS_SORT = BINARY",
            cancellationToken);

        var stopwatch = Stopwatch.StartNew();
        
        for (var i = 0; i < 5; i++)
        {
            stopwatch.Restart();
            await context.Customers.FromSqlRaw(query, name).AsNoTracking().ToListAsync(cancellationToken);
            stopwatch.Stop();
            timings.AppendLine($"Query 1.{i} duration: {stopwatch.ElapsedMilliseconds} ms");
        }

        await context.Database.ExecuteSqlRawAsync("ALTER SESSION SET NLS_COMP = LINGUISTIC NLS_SORT = BINARY",
            cancellationToken);
        
        for (var i = 0; i < 5; i++)
        {
            stopwatch.Restart();
            await context.Customers.FromSqlRaw(query, name).AsNoTracking().ToListAsync(cancellationToken);
            stopwatch.Stop();
            timings.AppendLine($"Query 2.{i} duration: {stopwatch.ElapsedMilliseconds} ms");
        }

        await context.Database.ExecuteSqlRawAsync("ALTER SESSION SET NLS_COMP = BINARY NLS_SORT = BINARY_CI",
            cancellationToken);

        for (var i = 0; i < 5; i++)
        {
            stopwatch.Restart();
            await context.Customers.FromSqlRaw(query, name).AsNoTracking().ToListAsync(cancellationToken);
            stopwatch.Stop();
            timings.AppendLine($"Query 3.{i} duration: {stopwatch.ElapsedMilliseconds} ms");
        }
        
        await context.Database.ExecuteSqlRawAsync("ALTER SESSION SET NLS_COMP = LINGUISTIC NLS_SORT = BINARY_CI",
            cancellationToken);
        
        for (var i = 0; i < 5; i++)
        {
            stopwatch.Restart();
            await context.Customers.FromSqlRaw(query, name).AsNoTracking().ToListAsync(cancellationToken);
            stopwatch.Stop();
            timings.AppendLine($"Query 4.{i} duration: {stopwatch.ElapsedMilliseconds} ms");
        }
        
        return timings.ToString();
    }
```
Result:
```
Query 1.0 duration: 149 ms
Query 1.1 duration: 12 ms
Query 1.2 duration: 12 ms
Query 1.3 duration: 9 ms
Query 1.4 duration: 12 ms
Query 2.0 duration: 11 ms
Query 2.1 duration: 9 ms
Query 2.2 duration: 12 ms
Query 2.3 duration: 12 ms
Query 2.4 duration: 10 ms
Query 3.0 duration: 10 ms
Query 3.1 duration: 12 ms
Query 3.2 duration: 10 ms
Query 3.3 duration: 9 ms
Query 3.4 duration: 11 ms
Query 4.0 duration: 557 ms <----LINGUISTIC +BINARY_CI
Query 4.1 duration: 570 ms
Query 4.2 duration: 528 ms
Query 4.3 duration: 464 ms
Query 4.4 duration: 511 ms
```

I try to check execution plan in for this query:
```
await context.Database.ExecuteSqlRawAsync($"EXPLAIN PLAN FOR {query}", cancellationToken: cancellationToken);

        var planResults = await context.ExecutionPlanResults
            .FromSqlRaw("SELECT PLAN_TABLE_OUTPUT AS Plan FROM TABLE(DBMS_XPLAN.DISPLAY(FORMAT=>'BASIC PREDICATE'))")
            .AsNoTracking()
            .ToListAsync(cancellationToken: cancellationToken);
```
Execution plan use IX_Customer_Name_NLS and all scheme is same as in database tool.

I repeat once again, the executions plans same in c# and db tools, all requests in the tools work fast.
The query was compared to the tools query, it is the same. I did not see any additional data from EF.

Please help to find out the reason.

All packages last version at this moment:
Microsoft.EntityFrameworkCore 8.0.10
Oracle.EntityFrameworkCore 8.23.60
or 
Microsoft.EntityFrameworkCore 8.0.10
Devart.Data.Oracle 10.3.21
Devart.Data.Oracle.EFCore 10.321.8

Oracle 19.0c

**Comment by roji** [comment] 2024-11-09 07:31
@sorcerb the above shows you running SQL queries; when you use EF's SQL APIs (e.g. FromSqlRaw), EF doesn't manipulate the SQL in any way, but simply sends it to the database. The only place where EF is actually doing something is maybe in the typing of the DbParameter being sent (`name` above).

I'd generally recommend looking at the Oracle logs for these queries to understand better what's going on. I'd also recommend trying to do the same thing with ADO.NET (so temporarily remove EF from the equation) to check if you're seeing the same phenomenon (and again, I'd pay attention to the DbType/OracleDbType of the DbParameter being sent).

**Comment by sorcerb** [comment] 2024-11-09 14:28
Okey, I will try check oracle profiler. And add information here.
In any case this is not normal behavior of the EF.

Strange that Take(5)  work fast if table have this 5 items, and slow in rows 4 or less.

**Comment by sorcerb** [comment] 2024-11-09 15:56
I try only with Ado, the result is the same....

```
app.MapGet("/customers", async (string name) =>
{
    var customers = new List<Customer>();

    var timings = new StringBuilder();
    await using (var connection = new OracleConnection("Data Source=****"))
    {
        await connection.OpenAsync();
        
        var  query = $"""SELECT * FROM app."Customer" WHERE "Name" LIKE :name || '%'""";
        Console.WriteLine($"Generated query: {query}");
        Console.WriteLine($"Parameter namePrefix: {name}");
        
        await using (var sessionCommand = new OracleCommand("ALTER SESSION SET NLS_COMP = BINARY NLS_SORT = BINARY", connection))
        {
            await sessionCommand.ExecuteNonQueryAsync();
            Console.WriteLine("Session parameters set: NLS_COMP = LINGUISTIC, NLS_SORT = BINARY_CI");
        }
        
        var stopwatch = Stopwatch.StartNew();
        for (var i = 0; i < 5; i++)
        {
            stopwatch.Restart();
            await using (var command = new OracleCommand(query, connection))
            {
                command.Parameters.Add(new OracleParameter("name", name));

                await using (var reader = await command.ExecuteReaderAsync())
                {
                    while (await reader.ReadAsync())
                    {
                        var customer = new Customer
                        {
                            Id = reader["Id"].ToString(),
                            Name = reader["Name"].ToString()
                        };
                        customers.Add(customer);
                    }
                }
            }

            stopwatch.Stop();
            timings.AppendLine($"Query 1.{i} duration: {stopwatch.ElapsedMilliseconds} ms");
        }

        await using (var sessionCommand = new OracleCommand("ALTER SESSION SET NLS_COMP = LINGUISTIC NLS_SORT = BINARY_CI", connection))
        {
            await sessionCommand.ExecuteNonQueryAsync();
            Console.WriteLine("Session parameters set: NLS_COMP = LINGUISTIC, NLS_SORT = BINARY_CI");
        }
        
        for (var i = 0; i < 5; i++)
        {
            stopwatch.Restart();
            await using (var command = new OracleCommand(query, connection))
            {
                command.Parameters.Add(new OracleParameter("name", name));

                await using (var reader = await command.ExecuteReaderAsync())
                {
                    while (await reader.ReadAsync())
                    {
                        var customer = new Customer
                        {
                            Id = reader["Id"].ToString(),
                            Name = reader["Name"].ToString()
                        };
                        customers.Add(customer);
                    }
                }
            }

            stopwatch.Stop();
            timings.AppendLine($"Query 4.{i} duration: {stopwatch.ElapsedMilliseconds} ms");
        }
    }

    return timings.ToString();
});
```

```
Query 1.0 duration: 1 ms
Query 1.1 duration: 1 ms
Query 1.2 duration: 1 ms
Query 1.3 duration: 1 ms
Query 1.4 duration: 1 ms
Query 4.0 duration: 506 ms
Query 4.1 duration: 482 ms
Query 4.2 duration: 761 ms
Query 4.3 duration: 482 ms
Query 4.4 duration: 554 ms
```

**Comment by roji** [comment] 2024-11-10 09:41
@sorcerb I'm not sure, but it looksl ike in the devtool your query doesn't contain a parameter (`SELECT * FROM "Customer" WHERE "Name" LIKE 'test' || '%'`), but in ADO (and EF) you're using a parameter (`SELECT * FROM app."Customer" WHERE "Name" LIKE :name || '%'"`). That means you're not comparing the same thing at all: try to run the non-parameterized query from ADO and you'll likely see the same performance as in the devtool. Similarly, you should be able to execute parameterized queries in the devtool (though I'm not sure, I don't know Oracle), and you should be able to reproduce the bad performance there as well.

So I very much suspect the problem has something to do with how you're configuring your parameter (it's type), or something similar. I'd suggest reproducing the problem outside of .NET (e.g. in the devtool), and then going to general Oracle forums (or stackoverflow) for support.

Either way, I'll go ahead and close this issue as unrelated to EF (or .NET) - we're unfortunately not Oracle experts and can't really help with this kind of problem...

**Comment by sorcerb** [comment] 2024-11-10 21:17
Yes, I got this with plane sql without parameters
Init connection query duration: 3 ms
```
Query 1.0 duration: 5 ms
Query 1.1 duration: 6 ms
Query 1.2 duration: 5 ms
Query 1.3 duration: 6 ms
Query 1.4 duration: 3 ms
...
Query 4.0 duration: 4 ms
Query 4.1 duration: 4 ms
Query 4.2 duration: 4 ms
Query 4.3 duration: 4 ms
Query 4.4 duration: 4 ms
```

But this select still work fast in db tools: `SELECT * FROM AIS."Customer" WHERE "Name" LIKE :name || '%'`

I'll try to reproduce the error in it.
In any case - Thank you very much.
But in this case, we will have to write plane sql in c# code. I'll try to think how to fix this.

**Comment by roji** [comment] 2024-11-10 22:42
I'd recommend again looking closely at the parameter type being used (DbType) - that's usually the cause for this sort of problem. Any sort of mismatch could cause the database to cast from your parameter to the required type, and that causes the index to no longer get used.

**Closed** 2024-11-10 22:42 UTC
Labels: area-perf, closed-external, customer-reported, area-query

**Comment by sorcerb** [comment] 2024-11-11 09:20
I will add the answer for history, maybe it will be useful to someone.
If you use this type of conversion, the request uses NLS index and works quickly.
I will try do it from c#

```
DECLARE
    v_name NVARCHAR2(254) := N'test';
BEGIN
    FOR rec IN (
        SELECT "Name" 
        FROM AIS."Customer" 
        WHERE "Name" = NLSSORT(v_name, 'NLS_SORT=BINARY_CI')
        ORDER BY NLSSORT("Name", 'NLS_SORT=BINARY_CI')
        OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY
    ) 
    LOOP
        DBMS_OUTPUT.PUT_LINE(rec."Name");
    END LOOP;
END;
```
