### ISSUE TITLE
Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper' from assembly 'Microsoft.EntityFrameworkCore.Design, Version=6.0.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation

### ISSUE THREAD

**Issue by pawansingh168** [dotnet/efcore#30308] opened 2023-02-18 10:42 UTC
Hi Can you tell me why this issue getting  while i  doing the add-migration in ef core in .net 6. I have added latest version from nuget package manager.

**Comment by ajcvickers** [comment] 2023-02-18 10:53
@pawansingh168 Probably mismatched package versions--for example, a database provider package for one version of EF Core, with other packages from a different version. If this isn't the case, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-02-28 19:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-02-28 19:28 UTC
Labels: customer-reported

**Comment by Mishatopkek** [comment] 2025-01-13 18:53
You possibly have a newer version of the main EF Core. Check that ALL EF Core libraries have the same version
