### ISSUE TITLE
Tracking is enabled when materializing an anonymous type that contains a non-entity value from a navigation property

### ISSUE THREAD

**Issue by Jared-Henry** [dotnet/efcore#8419] opened 2017-05-09 00:58 UTC
Tracking is enabled when materializing an anonymous type that contains a non-entity value from a navigation property.

### Steps to reproduce
Full project:
[https://github.com/Jared-Henry/EFCoreBug](https://github.com/Jared-Henry/EFCoreBug)

Snippet:
```c#
//See https://docs.microsoft.com/en-us/ef/core/querying/tracking
//The following query should not track any entity objects:
var result = (from t in db.Things
                select new
                {
                    t.Id,
                    LastModifiedBy = t.LastModifiedBy.Username
                }).ToArray();
```

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Enterprise, version 1607, build 14393.447
IDE: Visual Studio Professional 2017 version 15.1 (26403.7)

**Comment by anpete** [comment] 2017-05-09 16:26
I don't think it is being tracked, you can check by seeing how many entries are in the ChangeTracker: ```context.ChangeTracker.Entries.Count()```

As to why the Thing is getting materialized, can you post the query plan? (obtained by enabling logging at the Debug level)

**Comment by ajcvickers** [comment] 2017-05-17 18:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:04 UTC
