### ISSUE TITLE
Null values returned in Child Owned Entity when Parent Owned Entity has all Null value 

### ISSUE THREAD

**Issue by scottk4106** [dotnet/efcore#23488] opened 2020-11-26 06:26 UTC
I have an Entity that references an Owned Entity (parent), which in turn references another Owned Entity (child).  When the properties of the parent Owned Entity are all null, the properties of the child Owned Entity are also all null, even though the child Owned Entity has non-null data in the database.  This problem has only occurred after moving to EF Core 5.0.  It works as expected in 3.1.10.

I have simplified the entities by using a minimum of properties for the purposes of reproducing the problem. The first query gets all records where the property on the Parent Owned Entity is null, and the property on the Child Owned Entity is not null.  From that list I filter again for records where the Child Owned Entity is not null, which should not remove any records since that filter was already applied in the query.

Here is the output using different versions of EF Core.  There are 8472 records where Email is null and FirstName is not null. 
 The correct number of records are returned in both cases. However, in EF Core 5.0, FirstName is always null when Email is null. 
 If Email is not null, then FirstName is returned correctly. In EF Core 5.0 I have confirmed with ToQueryString() that the correct SQL is being called and when I run the query manually I get the expected data.

I also added a second query to test the scenario when the property on the Parent Owned Entity was not null.  In this case it worked as expected in both versions of EF Core.

If this is a bug in EF Core 5.0, is there anything I can do to work around it?

Thanks

EF Core 3.1.10
```
Email is null:  8472      Filtered: 8472
Email not null: 17293     Filtered: 17293
```

EF Core 5.0.0
```
Email is null:  8472      Filtered: 0
Email not null: 17293     Filtered: 17293
``` 

```
class Program
{
        static void Main(string[] args)
        {
            var db = new DatabaseContext();
            List<Customer> list1 = db.Customers.Where(c => c.Contact.Email == null).Where(c => c.Contact.NameAddress.FirstName != null).ToList();
            Console.WriteLine($"Email is null:  {list1.Count()}\t  Filtered: {list1.Where(c => c.Contact.NameAddress.FirstName != null).Count()}");

            List<Customer> list2 = db.Customers.Where(c => c.Contact.Email != null).Where(c => c.Contact.NameAddress.FirstName != null).ToList();
            Console.WriteLine($"Email not null: {list2.Count()}\t  Filtered: {list2.Where(c => c.Contact.NameAddress.FirstName != null).Count()}");
        }
}

public class DatabaseContext : DbContext 
{
    const string connStr = "Server=(localdb)\\mssqllocaldb;Database=TestDb;Trusted_Connection=True;MultipleActiveResultSets=true";
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseSqlServer(connStr);

    public DbSet<Customer> Customers { get; set; }
}

public class Customer
{
    public int CustomerID { get; set; }
    public Contact Contact { get; set; } = new Contact();
}

[Owned]
public class Contact
{
    public string Email { get; set; }
    public NameAddress NameAddress { get; private set; } = new NameAddress();
}

[Owned]
public class NameAddress
{
    public string FirstName { get; set; }
}
```

**Comment by ajcvickers** [comment] 2020-11-30 19:00
@AndriySvyryd @smitpatel Not sure if this is a dupe of #23229, #23198, or #21488.

**Comment by smitpatel** [comment] 2020-11-30 19:13
When in doubt go with all of them. Or we can also leave this issue open as bug.

**Comment by AndriySvyryd** [comment] 2020-11-30 19:50
Duplicate of https://github.com/dotnet/efcore/issues/21488

**Closed** 2022-10-16 19:12 UTC
Labels: closed-duplicate, customer-reported
