### ISSUE TITLE
Reference to JetBrains is added when overriding method

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/efcore#462] opened 2014-07-26 17:12 UTC
Do this in VS:
1. Create a class that extends DbContext
2. Inside the class, type "override" and from the selection list that appears after you press space select "OnModelCreating" and let VS do its magic of adding the method and all the necessary usings.

Now look at the using statements. Notice that "using JetBrains.Annotations" was added. The overriden method looks like:

``` C#
protected override void OnModelCreating([NotNullAttribute]ModelBuilder builder)
{
    base.OnModelCreating(builder);
}
```

There is a compilation error saying that NotNullAttribute is not accessible due to its protection level.

**Comment by rowanmiller** [comment] 2015-12-08 22:16
The behavior in VS has not changed, so clearing up milestone so that we can re-triage. My suggestion is just to leave things as they are (i.e. not having the attributes for methods that we expect folks to override often).

**Comment by Eilon** [comment] 2015-12-09 07:01
@rowanmiller is there a bug on Roslyn to fix this?

**Comment by BukeMan** [comment] 2018-04-05 11:28
this issue is still being reproduced on the latest studio 2017 v15.6.4 with ReSharper 2017.3.5

**Comment by bricelam** [comment] 2018-04-05 18:24
Duplicate of dotnet/roslyn#5646

**Closed** 2022-10-16 08:42 UTC
Labels: type-bug, closed-external
