### ISSUE TITLE
Query : Contains can not be translated to "in" clause 

### ISSUE THREAD

**Issue by Anas-11** [dotnet/efcore#17939] opened 2019-09-19 15:17 UTC
Am trying to check if any element of a list exists in the DB using the following code :
var results =await  _dbContext.Brands.AsNoTracking().AnyAsync(a => brandsHashset.Contains(a.Name));
Expecting that EF will translate it to "in" clause and the list will be sent as parameters , instead am getting an exception that it can not be translated .

**Comment by smitpatel** [comment] 2019-09-19 16:35
Duplicate of #17877

**Closed** 2022-10-16 14:43 UTC
Labels: closed-duplicate, customer-reported
