### ISSUE TITLE
dotnet ef migrations script never finishes

### ISSUE THREAD

**Issue by Gimly** [dotnet/efcore#14651] opened 2019-02-08 15:03 UTC
We're using 

`dotnet ef migration script --idempotent --project .\myproject.Database.csproj --startup-project .\myproject.web.csproj --output test.sql --context CloudContext`

to generate an idempotent migration script during our build on Azure DevOps so that we can run the migration on SQL Server during a release.

The issue we're facing is that the execution of the command never finishes (the build pipeline kills it after 1h). This seems to have appeared after we have configured the "startup project" (a web app) to use Application Insights.

If we try to run it locally, we see the same result, the command successfully build the project, finds the context and starts to write the .sql file, which we can see is created completely and correctly on disk, but never finishes.

Here's the verbose log of the command:

```
Using project '.\MyProject.Database\MyProject.Database.csproj'.
Using startup project '.\MyProject.WebApi\MyProject.WebApi.csproj'.
Writing '.\MyProject.Database\obj\MyProject.Database.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\myuser\AppData\Local\Temp\tmp2A71.tmp /verbosity:quiet /nologo .\MyProject.Database\MyProject.Database.csproj
Writing '.\MyProject.WebApi\obj\MyProject.WebApi.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\myuser\AppData\Local\Temp\tmp2E6A.tmp;Configuration=Release /verbosity:quiet /nologo .\MyProject.WebApi\MyProject.WebApi.csproj
dotnet build .\MyProject.WebApi\MyProject.WebApi.csproj --configuration Release /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.29
dotnet exec --depsfile C:\sources\MyProduct\MyProject.WebApi\bin\Release\netcoreapp2.0\MyCompany.MyProduct.MyProject.WebApi.deps.json --additionalprobingpath C:\Users\myuser\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\sources\MyProduct\MyProject.WebApi\bin\Release\netcoreapp2.0\MyCompany.MyProduct.MyProject.WebApi.runtimeconfig.json "C:\Program Files\dotnet\sdk\2.1.503\DotnetTools\dotnet-ef\2.1.4\tools\netcoreapp2.1\any\tools\netcoreapp2.0\any\ef.dll" migrations script --idempotent --output test2.sql --context MyContext --assembly C:\sources\MyProduct\MyProject.WebApi\bin\Release\netcoreapp2.0\MyCompany.MyProduct.MyProject.Database.dll --startup-assembly C:\sources\MyProduct\MyProject.WebApi\bin\Release\netcoreapp2.0\MyCompany.MyProduct.MyProject.WebApi.dll --project-dir C:\sources\MyProduct\MyProject.Database\ --language C# --working-dir C:\sources\MyProduct --verbose --root-namespace MyCompany.MyProduct.MyProject.Database
Using assembly 'MyCompany.MyProduct.MyProject.Database'.
Using startup assembly 'MyCompany.MyProduct.MyProject.WebApi'.
Using application base 'C:\sources\MyProduct\MyProject.WebApi\bin\Release\netcoreapp2.0'.
Using working directory 'C:\sources\MyProduct\MyProject.WebApi'.
Using root namespace 'MyCompany.MyProduct.MyProject.Database'.
Using project directory 'C:\sources\MyProduct\MyProject.Database\'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding BuildWebHost method...
Using environment 'Development'.
Using application service provider from BuildWebHost method on 'Program'.
Found DbContext 'MyContext'.
Finding DbContext classes in the project...
Using context 'MyContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding IDesignTimeServices implementations in assembly 'MyCompany.MyProduct.MyProject.WebApi'...
No design-time services were found.
Writing 'test.sql'...
```
The system stays blocked after that "Writing" log event, and seems to stay like that forever.

### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10.0.16299
IDE: Visual Studio 2017 15.9.6

**Comment by ajcvickers** [comment] 2019-02-08 22:09
@Gimly Would it be possible to get a runnable project/solution that demonstrates the behavior you are seeing? (Something definitely looks like it is going on here, but there's not much to go on when attempting to figure out the root cause.)

**Comment by Gimly** [comment] 2019-02-11 13:26
@ajcvickers I can't share the code publicly as it's a closed source project, I'm going to try to reproduce it in something minimal that I could share. Otherwise I could check with my superiors if I can share it privately.

**Comment by circuitrider** [comment] 2019-02-12 19:51
I am getting a similar behavior with the final result completing with "Done." but it hangs indefinitely after. This fails on Win 10 and in DevOps pipelines.

I'm running the command:
`dotnet` ef database update --startup-project $webAppPipelinePath --project $webAppDataAccessPipelinePath

**Comment by ajcvickers** [comment] 2019-02-19 22:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by AlexDenton** [comment] 2020-07-21 13:43
@ajcvickers This issue is making it difficult for me to automate migrations in my pipeline. I tried mining the issues for guidance but this seems to be the only other report matching my observations. Has anything new been learned here?

**Comment by ajcvickers** [comment] 2020-07-21 18:10
@AlexDenton We have not been able to reproduce this. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by AlexDenton** [comment] 2020-07-21 18:58
Alright, I'll see if I can create a sanitized version tonight.

**Comment by joercampbell** [comment] 2020-10-06 18:52
We JUST had a very similar impact on our build, By any chance were you using BulkInserts?

**Closed** 2022-10-16 13:51 UTC
Labels: closed-could-not-reproduce, customer-reported
