### ISSUE TITLE
DbUpdateConcurrencyException.Entries only contains one Entry in a split-table scenario

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#11348] opened 2018-03-20 16:07 UTC
I have a one-to-one relationship between two entities that share the same table, with the PK property being used as the FK between them (so, a split table). If `SaveChanges` throws a `DbUpdateConcurrencyException`, the exception's `Entries` property contains only one of the two entities.

Is this intentional? How does it choose which of the two entities is in the exception?

If this is intentional: does a `DbUpdateException` *ever* have multiple entries?

**Comment by ajcvickers** [comment] 2018-03-22 03:11
@AndriySvyryd Could you try to find the duplicate for this? I was unable to find it.

**Comment by smitpatel** [comment] 2018-03-22 19:16
Duplicate of #1002

**Closed** 2022-10-16 12:15 UTC
Labels: closed-duplicate
