### ISSUE TITLE
Trigger issue with variable or temp table in OUTPUT-INTO clauses

### ISSUE THREAD

**Issue by maestro957** [dotnet/efcore#33259] opened 2024-03-06 19:54 UTC
We generated triggers for INSERT, DELETE, and UPDATE on all our tables for auditing purposes. Below is a snippet of the code. Originally, we are using variable tables in the INTO clause following the OUTPUT. These results in an error message about "the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause." As stated, we are providing a variable table in the INTO clause.  We have also tried it with temp tables with the same results.  Once we provide an actual table structured just like the variable or temp table, the trigger operates as expected. However, these "real" tables would become "polluted" with stagnate data and there's no reliable way to remove the added entries.  When EF Core is checking the DML for correctness, is it possible that it's seeing the @ or # symbols as invalid and not continuing?

Hopefully the snippet below is enough to show what we're attempting. I can provide the full trigger code, if necessary.

DECLARE @Audit TABLE (
	[Type] [char](1),
	[PK] [nvarchar](10),
	[FieldName] [varchar](50),
	[OldValue] [nvarchar](max),
	[NewValue] [nvarchar](max)
);
DECLARE @InsertedIds TABLE (
	[AuditId] Int,
	[TableName] Varchar(50),
	[PK] [nvarchar](10),
	[Type] [char](1)
);

IF (@@RowCount>0)
BEGIN
	INSERT INTO dbo.audit
	(
		[TableName],
		[PK],
		[Type],
		[UpdateDate],
		[UserName]
	)
	OUTPUT	INSERTED.AuditId, 
			INSERTED.TableName,   
			INSERTED.Pk, 
			INSERTED.Type
	INTO	@InsertedIds
	SELECT	DISTINCT '[dbo].[user_role]' AS [TableName],
			[PK], 
			[Type], 
			Getdate() AS [UpdateDate],
			ISNULL(CONVERT(nvarchar(64), CONTEXT_INFO()), CAST(SUSER_SNAME() AS nvarchar(64))) AS [UserName]
	FROM	@Audit;

	INSERT INTO dbo.audit_detail
	(
		[AuditId],
		[FieldName],
		[OldValue],
		[NewValue]
	)
	SELECT	I.[AuditId],
			A.[FieldName],
			A.[OldValue],
			A.[NewValue]
	FROM	@Audit A
			JOIN @InsertedIds I
				ON I.[PK] =  A.[PK]
				AND I.[Type] = A.[Type];
END

**Comment by maestro957** [comment] 2024-03-06 19:57
This is using EF Core 8. We have read over this article too: https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes?tabs=v7#sql-server-tables-with-triggers-or-certain-computed-columns-now-require-special-ef-core-configuration

**Comment by roji** [comment] 2024-03-06 21:19
Sorry, but what do you mean by "When EF Core is checking the DML for correctness"? The above SQL which you've posted doesn't look like anything EF itself generates, so am I correct in understanding this is raw SQL which you're executing yourself? If so, are you expecting EF to validate it for you?

**Comment by maestro957** [comment] 2024-03-06 21:23
This is a trigger that we generate. We are using SQL Server and EF Core 8. When we were using EF Core 6, the trigger would run correctly without issue as written. After we upgraded to EF Core 8, we get the error as posted: "the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause".  The only difference is now we're using EF Core 8 in our app that causes the trigger to fire.

**Comment by ErikEJ** [comment] 2024-03-06 21:30
And did you use HasTrigger ?

**Comment by maestro957** [comment] 2024-03-06 21:54
Yes, we have added HasTrigger to each of the configs. And with HasTrigger is does work. To explain further, we have an auditing that will enumerate each table within our db.  It drops all existing triggers that it previously created before recreating the triggers for all existing and new tables.  In EF Core 6, these auto-generated triggers worked flawlessly.  Now, after moving to EF Core 8, I have to go into the configs and add "HasTrigger".  The problem is with the @ or # being used in the INTO clause.  If I use a real table, it works just fine.  I'm hoping for an explanation why the INTO is failing when I use a @variable table or a #temp table.

**Comment by AsaBeckstead** [comment] 2024-03-06 21:54
If we use the HasTrigger it will work, but we would prefer not to do that as it must be added to each entity.  We performed 3 tests, not using the HasTrigger method, with the following results:

1) trigger using a table variable:
...
OUTPUT INSERTED.AuditId,
INSERTED.TableName,
INSERTED.Pk,
INSERTED.Type
INTO @InsertedIds     -- INTO table variable here
...
fails with the error above.

2) trigger using a temp table:
...
OUTPUT INSERTED.AuditId,
INSERTED.TableName,
INSERTED.Pk,
INSERTED.Type
INTO #InsertedIds     -- INTO temp table here
...
fails with the error above.

3) trigger using a standard table
trigger using a table variable:
...
OUTPUT INSERTED.AuditId,
INSERTED.TableName,
INSERTED.Pk,
INSERTED.Type
INTO InsertedIds     -- INTO table here
...
Allows the save operation to complete without error.

It appears that we are only unable to proceed with our long time approach due to the special character at the beginning of the "into table name":
@InsertedIds
#InsertedIds
InsertedIds

We would appreciate any insights.

**Comment by ErikEJ** [comment] 2024-03-06 21:57
Just do a bulk HasTrigger and move on.

**Comment by maestro957** [comment] 2024-03-06 22:05
Is there documentation on how to do a bulk HasTrigger?

**Comment by roji** [comment] 2024-03-06 22:51
> Is there documentation on how to do a bulk HasTrigger?

Yep, there's one in the EF7 breaking change note you linked to above.

**Comment by roji** [comment] 2024-03-07 17:08
That sounds more like a SQL Server question that's better asked on their forums.

**Comment by roji** [comment] 2024-03-07 21:05
@AsaBeckstead the change in EF 7 was EF's switch to using INSERT ... OUTPUT ... directly out to the user, rather than using OUTPUT INTO to a temporary table, and then selecting out from that temporary table. The OUTPUT clause - without INTO - is well-known to be incompatible with tables that have triggers; that's just a documented SQL Server limitation. Similarly, the switch from OUTPUT INTO to OUTPUT was documented as a breaking change in EF7; this was done since the performance of OUTPUT is considerably better than that of OUTPUT INTO with a temporary table.

So I'm not seeing what requires further discussion here - either on the EF side or on the SQL Server side... Everything seems to be documented on both sides. Am I missing something?

**Comment by AsaBeckstead** [comment] 2024-03-12 20:57
Thank you for the additional detail.  I'll see what we can do to alter our triggers to make them more compatible.

**Comment by roji** [comment] 2024-03-12 21:03
@AsaBeckstead this isn't about making your triggers more compatible; it's about EF's default update mechanism not being compatible with tables that have **any** triggers, when using SQL Server. Please reread the breaking change note; what you want is probably to make EF revert to the old update mechanism as described there.

I'll go ahead and close this issue as everything seems to be working as designed, and I don't see anything beyond what is already well-documented. But if things are still unclear, feel free to post back here.

**Closed by roji** 2024-03-12 21:03 UTC
Labels: customer-reported, area-save-changes, area-sqlserver
