### ISSUE TITLE
Implement Database changes with State-based approach

### ISSUE THREAD

**Issue by ansarizafar** [dotnet/efcore#21029] opened 2020-05-23 11:39 UTC
State-based approach for implementing database changes is much better than Migration-based approach https://devblogs.microsoft.com/azure-sql/devops-for-azure-sql/

I personally don't like current migration based approach in efcore that is why I am currently using scaffold command. It would be great If can have an option to use state based approach for implementing schema changes in Postgres with Efcore.

**Comment by roji** [comment] 2020-05-23 13:51
At least for SQL Server You may want to take a look at @ErikEJ's excellent [EF Power Tools](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering), which allow scaffolding a model directly from a SSDT project. #1186 tracks SSDT integration for EF Core.

For PostgreSQL, can you elaborate on how you'd manage your schema? What exactly are you looking for from EF Core?

Aside from that, it seems like you're basically asking for a database-first approach, where you'd evolve your database schema via some external tool (e.g. SSDT, DACPAC) and EF would scaffold its model from that. This would in most cases require support for updating an existing (previously-scaffolded) model from a database, tracked by #831.

**Comment by ansarizafar** [comment] 2020-05-23 15:44
I want to create/update my schema in code and then run a command dotnet ef update to implement changes in database directly without creating/storing a migration.

**Comment by roji** [comment] 2020-05-23 18:33
> I want to create/update my schema in code

What representation would your schema be in? An SQL script or something else?

**Comment by ansarizafar** [comment] 2020-05-24 04:08
I am aware of Pgrest but I am talking about a Postgres extension and not an additional external component.

**Comment by roji** [comment] 2020-05-24 09:27
@ansarizafar it looks like you want to use an external tool to manage your schema, outside of EF Core.

EF Core uses mostly a code-first approach - you define .NET types and derive the database schema from them (passing through a conceptual model). EF Core is indeed capable of generating such a code model from an existing database (that's scaffolding), and at some point will also be able to evolve that code model based on changes in the database (#831). At that point EF Core would probably match what you're looking for.

Am closing this as a duplicate of #831, but if I've misunderstood what you're asking for don't hesitate to post back and we can continue discussing.

**Comment by roji** [comment] 2020-05-24 09:27
Duplicate of #831

**Comment by ansarizafar** [comment] 2020-05-24 15:14
I am currently using scaffolding(Database first) as I don't like Ef core migrations. I want to use code-first approach without migrations. I am requesting an option/command to update my database schema from my .net types directly without creating migrations.

**Comment by roji** [comment] 2020-05-24 17:56
If you're using code-first, you will always need migrations: all that a migration is, is a way to get your database from one state to another, based on changes in your code-first model.

I think you may be unhappy for some reason with having to do this *manually*, and expect EF Core to somehow do this automatically - there are very good reason why things don't work that way. Specifically, when you change your code model (e.g. add some property to it), EF Core needs a snapshot of the model as it previously was, so that it can compare against it and know that a column has been added. This snapshot has to be generated at some point - by you.

Can you explain why exactly you don't like EF Core migrations?

**Comment by roji** [comment] 2020-05-24 18:37
Possibly a duplicate of #6214

**Comment by ansarizafar** [comment] 2020-05-25 02:33
> If you're using code-first, you will always need migrations: all that a migration is, is a way to get your database from one state to another, based on changes in your code-first model.

I agree.

> I think you may be unhappy for some reason with having to do this manually, and expect EF Core to somehow do this automatically.

We make frequent changes to our code-first model during development so I expect EF core to do it automatically during development and I would like do to it manually in production.

> there are very good reason why things don't work that way. Specifically, when you change your code model (e.g. add some property to it)

I have read previous discussions about current migration system and the reasons given, in favor by the Ef core team and the reasons against it by the developers who don't like it. What I am proposing is a parallel option.

> EF Core needs a snapshot of the model as it previously was, so that it can compare against it and know that a column has been added. This snapshot has to be generated at some point - by you. 

Currently Ef core is using the previously created snapshot to add/generate/store a new migration. Over time migrations folder becomes too big but we need to keep it. If we delete the migrations folder then Ef core can't create correct migration because now there is no previously generated snapshot. If we create a new migration now and try to apply it then we will get exception as the database schema is in different state.

In my opinion Ef core should create a diff/snapshot in the background each time we migrate (manually or automatically) by comparing code-first model with the database schema directly, without using a previously generated snapshot and apply it without storing a snapshot and migration.

**Comment by roji** [comment] 2020-05-25 07:51
> We make frequent changes to our code-first model during development so I expect EF core to do it automatically during development and I would like do to it manually in production.

@ansarizafar it does sound like you're asking for automatic migrations, which existed in EF6 (see #6214 for the discussion). That issues mentions various similar approaches, and links to other issues that would make iterative development easier.

> Currently Ef core is using the previously created snapshot to add/generate/store a new migration. Over time migrations folder becomes too big but we need to keep it. If we delete the migrations folder then Ef core can't create correct migration because now there is no previously generated snapshot. If we create a new migration now and try to apply it then we will get exception as the database schema is in different state.

That's migration squashing (#2174). It's certainly possible to remove your migrations folder and recreate a new migration; at that point you also have to empty your __EFMigrationsHistory table and insert a single row for the new migration (you can take that INSERT from the SQL script generated from the new migration). We could indeed make this a bit more streamlined, but it's quite easy to do today for many cases.

**Comment by ansarizafar** [comment] 2020-05-25 08:41
It seems that many developers are complaining about issues with current migration system. I think its better to use scaffolding at the moment than the migration system.

**Comment by ansarizafar** [comment] 2020-06-01 11:22
I propose a parallel migration system in addition to the current system which provides an APi and a command to update database schema

````
dataContext.Database.AutoMigrate();

dotnet ef automigrate

````
The proposed api can be used during development while the command can be used in production. Both the API/Command should consider ef core entity classes as a single source of truth (SSOT) and compare it with the database schema directly create a diff and update the database state each time the api/command is used . This will address the needs of single developer/small teams. I request EF core time to please consider this proposal.

**Comment by ajcvickers** [comment] 2020-06-01 14:57
The team discussed this, and we believe the request here is basically for automatic migrations, which we are not planning to implement for the reasons stated in #6214. See the discussion there for more information.

**Comment by ansarizafar** [comment] 2020-06-02 03:32
I understand the reasons stated in #6214 but there are lots of developers asking for automatic migrations. The current migration system and the proposed migration system both can live together. I hope EF core team will reconsider their decision and this proposal.

**Closed** 2022-10-16 18:26 UTC
Labels: customer-reported
