### ISSUE TITLE
ExecutionStrategy is not called for ToXXXAsync when AsNoTracking configured

### ISSUE THREAD

**Issue by alex-zyl** [dotnet/efcore#16554] opened 2019-07-10 16:58 UTC
EFCore.SqlServer 2.2.6

There's inconsistent behavior in using LINQ extension methods with and without AsNoTracking.

For non ToXXXAsync LINQ extension methods AsyncQueryingEnumerable is used which uses ExecutionStrategy internally with and without AsNoTracking.

For non ToXXXAsync (ToListAsync, ToArrayAsync, etc) LINQ extension methods:

- AsyncQueryingEnumerable is used when AsNoTracking is not called

- FastQueryAsyncEnumerableis  is used when AsNoTracking is called

Code sample: 

```csharp
await Context.Set<User>().AsNoTracking().FirstOrDefaultAsync(); //used AsyncQueryingEnumerable
await Context.Set<User>().FirstOrDefaultAsync(); //used AsyncQueryingEnumerable

await Context.Set<User>().ToListAsync(); //used AsyncQueryingEnumerable
await Context.Set<User>().AsNoTracking().ToListAsync(); //used FastQueryAsyncEnumerable
```

**Comment by ajcvickers** [comment] 2019-07-12 17:13
@AndriySvyryd to find the dupe

**Comment by AndriySvyryd** [comment] 2019-07-12 17:20
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/14730

**Closed** 2022-10-16 14:30 UTC
Labels: customer-reported
