### ISSUE TITLE
InMemroyDatabase with InMemoryDatabaseRoot gets empty database each time

### ISSUE THREAD

**Issue by EPinci** [dotnet/efcore#16643] opened 2019-07-17 18:56 UTC
EF Core version: 2.2.6

I'm trying to write integration test of an API that have a shared instance of an InMemory database. **Although I'm using an InMemoryDatabaseRoot, I always get a new empty database.**

_I'm using xunit and I have my CustomWebApplicationFactory<TStartup> as a fixture in a fixture collection to share it among the tests. Tests are decorated with the collection._

```c#
    public class CustomWebApplicationFactory<TStartup> : WebApplicationFactory<Startup>
    {
        private static readonly InMemoryDatabaseRoot databaseRoot = new InMemoryDatabaseRoot();

        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureServices(services =>
            {
                // Create a new service provider.
                var serviceProvider = new ServiceCollection()
                    .AddEntityFrameworkInMemoryDatabase()
                    .BuildServiceProvider();

                // Add a database context (AppDbContext) using an in-memory database for testing.
                services.AddDbContext<MyContext>(opts => {
                    opts.UseInMemoryDatabase("InMemoryAppDb", databaseRoot);
                    opts.UseInternalServiceProvider(serviceProvider);
                });

                // Build the service provider.
                var sp = services.BuildServiceProvider();

                // Create a scope to obtain a reference to the database contexts.
                using (var scope = sp.CreateScope())
                {
                    var scopedServices = scope.ServiceProvider;
                    var appDb = scopedServices.GetRequiredService<MyContext>();
                    var logger = scopedServices.GetRequiredService<ILogger<CustomWebApplicationFactory<TStartup>>>();

                    // Ensure the database is created.
                    appDb.Database.EnsureCreated();

                    try
                    {
                        // Seed the database with some specific test data.
                        DatabaseSeeder.PopulateTestData(appDb);

                        logger.LogInformation("Database seeded");
                    }
                    catch (Exception ex)
                    {
                        logger.LogError(ex, "An error occurred seeding the database. " +
                                            "Error: {ex.Message}");
                    }
                }
            });
        }
    }
```

Now I have verified using the debugger that the InMemory context actually takes precedence over the context defined in the SUT API. Good there: database seeding gets called and runs fine.

For a variety of reasons, sometimes in the SUT I need to create a context "manually" - aka: ```new MyContext(options)``` - and I'm pulling the ```dbContextOptions<MyContext>``` that I pass to it from the DI. I verified again with the debugger that the options pulled have the InMemory provider, the database name and the InMemoryDatabaseRoot reference.

According to the [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.inmemorydbcontextoptionsextensions.useinmemorydatabase?view=efcore-2.1#Microsoft_EntityFrameworkCore_InMemoryDbContextOptionsExtensions_UseInMemoryDatabase__1_Microsoft_EntityFrameworkCore_DbContextOptionsBuilder___0__System_String_System_Action_Microsoft_EntityFrameworkCore_Infrastructure_InMemoryDbContextOptionsBuilder__)

> All in-memory databases will be rooted in this object, allowing the application to control their lifetime. This is useful when sometimes the context instance is created explicitly with new while at other times it is resolved using dependency injection

this seems exactly my case but it is not working for me - the database I get is empty.

What am I getting wrong?

Thank you.

**Comment by ajcvickers** [comment] 2019-07-17 23:21
@EPinci Since `CustomWebApplicationFactory<TStartup>` each use of the class with a different `TStartup` will get its own static `databaseRoot`. Can you check that `databaseRoot` is the same instance in both places it is used?

If it's not that, then please post a small, _runnable_ project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-07-25 19:00
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:31 UTC
Labels: closed-could-not-reproduce, customer-reported
