### ISSUE TITLE
Change tracker ignores default value setting on non nullable properties

### ISSUE THREAD

**Issue by taadomas** [dotnet/efcore#32565] opened 2023-12-08 14:19 UTC
## Description

When you setup property as **non nullable** with default value (.**HasDefaultValue**) that equals to property **type default value** (int = 0, bool = false..), after updating entity at least once, you cannot set this property value back to default.

Example: 
- You have a Balance parameter/model that contains Value(int) and DateUpdated(datetime)
- You setup Balance.Value as non nullable and with .HasDefaultValue(0)
- You have an entry in database with Balance.Value = 100
- You try to update that entry to Balance.Value = 0. Change tracker ignores this change and Value is not being updated while saving context changes.

## Code to reproduce

You need an entity with class based parameters that contains int, boolean or other base type.

```C#
public class DefaultValuesTestEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public virtual Guid Id { get; protected init; }

    public IsActive IsActive { get; set; } = new(false, DateTime.UtcNow);
    public Count Count { get; set; } = new(0, DateTime.UtcNow);
}

public record IsActive(bool Active, DateTime DateFrom);

public record Count(int Counter, DateTime LastUpdate);
```

When configuring entity type, add .HasDefaultValue(default type value in sql) for those properties

```C#
public class DefaultValuesTestConfiguration : IEntityTypeConfiguration<DefaultValuesTestEntity>
{
    public void Configure(EntityTypeBuilder<DefaultValuesTestEntity> builder)
    {
        builder
            .HasKey(u => u.Id);
        builder
            .OwnsOne(u => u.IsActive)
            .Property(x => x.Active)
            .HasDefaultValue(false);
        builder
            .OwnsOne(u => u.Count)
            .Property(x => x.Counter)
            .HasDefaultValue(0);
    }
}
```

Insert entities to database that contains not default values for these properties.
Try to update them with default values from code:

```C#
        var testEntity = _context.DefaultValuesTestEntity.FirstOrDefault(x => x.Id == data.id);
        testEntity.Count = new Count(0, DateTime.UtcNow);
        testEntity.IsActive = new IsActive(false, DateTime.UtcNow);
        await _context.SaveChangesAsync();
```

Generated updated statement does not contain these fields:
```
dbug: 12/8/2023 16:11:48.934 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[@p2='?' (DbType = Guid), @p0='?' (DbType = DateTime2), @p1='?' (DbType = DateTime2)], CommandType='Text', CommandTimeout='30']
      SET IMPLICIT_TRANSACTIONS OFF;
      SET NOCOUNT ON;
      UPDATE [DefaultValuesTestEntity] SET [Count_LastUpdate] = @p0, [IsActive_DateFrom] = @p1
      OUTPUT INSERTED.[Count_Counter], INSERTED.[IsActive_Active]
      WHERE [Id] = @p2;
```

Notes:
update statement is correct if:
- we update these fields to be nullable
- we remove HasDefaultValue()
- we are updating not to default value
- we add .ValueGeneratedNever() together with .HasDefaultValue()

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 7.0)
Operating system:
IDE: (both Visual Studio 2022 and Rider)
Running code from IDE or as a Docker container

**Comment by devatlantis** [comment] 2023-12-08 15:23
Hey.

It is not completely clear from this: https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#database-defaults-for-booleans

Booleans should have this issue fixed in 8.0 without any additional actions needed from the user?

**Comment by devatlantis** [comment] 2023-12-12 10:44
We started looking into this in our project and we noticed that we have int properties, with non-zero default values configured, but are able to update them to 0 just fine.

Which seems to contradict the example provided here: https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#sentinel-values-and-database-defaults

The only difference I can see is that we use HasDefaultValue and the example mentions HasDefaultValueSql.

e.g. with some code redacted

```
builder.OwnsOne(p => p.SomeObject, nav =>
{
    nav.Property(p => p.SomeIntValue).HasDefaultValue(50);
});
```
```
public class SomeObject
{
    private SomeObject() { }

    public int SomeIntValue{ get; private set; }
    
}
```
We also have an enum configured as follows:

```        
builder.Property(nav => nav.ReadStatus)
.HasDefaultValue(ReadStatus.IsUnread);
```
```
public enum ReadStatus
{
    IsRead = 0,
    IsUnread = 1
}
```

Yet updating the status to `IsRead` works just fine.

So currently it is not clear, whether any fixes are needed from our end.
Could you expand under what conditions the issue occurs?

We're running EF Core 7.0.5 on an Azure SQL database.

Thank you!

**Comment by ajcvickers** [comment] 2023-12-13 11:08
@taadomas The examples you posted should fall into the category described in the docs--see my code below. If your code isn't behaving like this, then I suspect there is something else going on beyond the simple configuration.

```C#
using (var context = new SomeDbContext())
{
    await context.Database.EnsureDeletedAsync();
    await context.Database.EnsureCreatedAsync();

    context.Add(new MyEntity
    {
        ReadStatus = ReadStatus.IsRead,
        SomeObject = new(),
    });

    await context.SaveChangesAsync();
}

using (var context = new SomeDbContext())
{
    var result = context.Set<MyEntity>().Single();
    Console.WriteLine(result.ReadStatus);
    Console.WriteLine(result.SomeObject.SomeIntValue);
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Data Source=avickers420w;Database=One;Integrated Security=True;TrustServerCertificate=true")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MyEntity>(builder =>
        {
            builder.OwnsOne(p => p.SomeObject, nav => { nav.Property(p => p.SomeIntValue).HasDefaultValue(50); });
            builder.Property(nav => nav.ReadStatus)
                .HasDefaultValue(ReadStatus.IsUnread);
        });
    }
}

public class MyEntity
{
    public int Id { get; set; }
    public SomeObject SomeObject { get; set; }
    public ReadStatus ReadStatus { get; set; }
}

public class SomeObject
{
    public  SomeObject() { }

    public int SomeIntValue{ get; private set; }
}

public enum ReadStatus
{
    IsRead = 0,
    IsUnread = 1
}
```

**Comment by devatlantis** [comment] 2023-12-13 16:19
I think we have figured this out. Please correct me if I'm wrong.

It seems this only affects Inserts and I was testing on Updates.

Regarding @taadomas original issue - this seems to also be triggered even if a row for the entity already exists in the database, but an owned entity is updated by creating a new instance of an object using the `new` keyword.

So in addition to being triggered on Inserts, it can also be triggered on Updates if an Update is done with a new instance of some object.

Here is some code to demonstrate this:

```
using (var context = new SomeDbContext())
{
    await context.Database.EnsureDeletedAsync();
    await context.Database.EnsureCreatedAsync();

    context.Add(new MyEntity
    {
        SomeObject = new(),
    });

    context.Add(new MyEntity
    {
        SomeObject = new(),
    });

    await context.SaveChangesAsync();
}

var id = 1;

    // This works
using (var context = new SomeDbContext())
{
    var result = context.Set<MyEntity>().Where(x => x.Id== id).Single();
    result.SomeObject.SomeIntValue = 0;

    await context.SaveChangesAsync();
}

// This should output 0
using (var context = new SomeDbContext())
{
    var result = context.Set<MyEntity>().Where(x => x.Id == id).Single();
    Console.WriteLine(result.SomeObject.SomeIntValue);
}

id = 2; 

// This doesn't work
using (var context = new SomeDbContext())
{
    var result = context.Set<MyEntity>().Where(x => x.Id == id).Single();
    var someObject = new SomeObject();
    someObject.SomeIntValue = 0;

    result.SomeObject = someObject;

    await context.SaveChangesAsync();
}

    // This should output 50
using (var context = new SomeDbContext())
{
    var result = context.Set<MyEntity>().Where(x => x.Id == id).Single();
    Console.WriteLine(result.SomeObject.SomeIntValue);
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Data Source=localhost;Initial Catalog=TestDB;Integrated Security=true; TrustServerCertificate=True")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MyEntity>(builder =>
        {
            builder.OwnsOne(p => p.SomeObject, nav => { nav.Property(p => p.SomeIntValue).HasDefaultValue(50); });
        });
    }
}

public class MyEntity
{
    public int Id { get; set; }
    public SomeObject SomeObject { get; set; }
}

public class SomeObject
{
    public SomeObject() { }

    public int SomeIntValue { get; set; }
}
```

**Comment by ajcvickers** [comment] 2023-12-13 16:24
Yes, it only applies to database inserts, but see #30705

**Comment by devatlantis** [comment] 2023-12-14 09:53
Thanks.

It's not fully clear from #30705 what the expected behavior would be?

Wil Updating with `new` differ based on whether the table is shared or not?
Or will Updating with `new` always work same as Updating with value assignment?

I think we would prefer the second option, since we wouldn't have to worry about the entity configuration internals when writing domain level updates.

**Comment by ajcvickers** [comment] 2023-12-14 10:22
"Updating with new" is not updating. It's deleting and inserting.

**Closed** 2024-01-03 14:12 UTC
Labels: closed-no-further-action, customer-reported
