### ISSUE TITLE
Nullifying dependent field is not allowed for FK restrict

### ISSUE THREAD

**Issue by Tarig0** [dotnet/efcore#10542] opened 2017-12-12 17:24 UTC
I have a relationship that I would like to sever, but when I nullify the property in question I get the following error.

I would only expect the following exception if I deleted the item record, not if I broke the relationship.

Note: I can null the column in the SQL directly

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: InvalidOperationException: The association between entity types 'Item' and 'Person' has been severed but the foreign key for this relationship cannot be set to null. If the dependent entity should be deleted, then setup the relationship to use cascade deletes.
Stack trace:
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.HandleConceptualNulls()
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave()
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager+<SaveChangesAsync>d__59.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.EntityFrameworkCore.DbContext+<SaveChangesAsync>d__48.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.
```c#
modelBuilder.Entity<Person>().HasOne<Item>().WithMany().HasForeignKey("LeftItem").OnDelete(DeleteBehavior.Restrict);
```
```c#
public async Task RemoveAsync(string id)
{
    var prop = _db.Attach(new Person() { ID = id}).Property("LeftItem");
    prop.CurrentValue = null;
    prop.IsModified = true;
    await _db.SaveChangesAsync();
}
```

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: win10
IDE: Visual Studio 2017 15.4

**Comment by Tarig0** [comment] 2017-12-12 17:30
Looks like ClientSetNull might be my guy.

**Comment by Tarig0** [comment] 2017-12-12 17:37
I think (based on the naming) this is an unintended restriction. Since I'm modifying the dependent record and not deleting the principle record.

**Comment by ajcvickers** [comment] 2017-12-12 17:49
Duplicate of #9703

**Closed** 2022-10-16 12:02 UTC
