### ISSUE TITLE
Prevent add ORDER BY when using Include

### ISSUE THREAD

**Issue by Haza85** [dotnet/efcore#17525] opened 2019-08-30 13:34 UTC
Hi all
I have problem with query performance when using Include.
My query
```
.Include(i => i.TABLE1).ThenInclude(i => i.TableX).ThenInclude(i => i.TableY)
.Include(i => i.TABLE2)      
```
EF generate query like this:
```
SELECT TABLE1.*
FROM TABLE1
LEFT JOIN TABLE2 ON TABLE2.ID = TABLE1.FIELD1
LEFT JOIN TABLE2 ON TABLE2.ID = TABLE1.FIELD2
ORDER BY TABLE1.MYCUSTOMSORTFIELD DESC,TABLE1.ID,TABLE1.VIRTUALFIELDONTABLE2.id
LIMIT 50 OFFSET 1
```
So, two last ORDER BY condition in sql query is automatically added by EF and make query slower. Without this conditions query runs during 10ms, with conditions above 500ms.

Is exist way to prevent add this fields on ORDER BY?

**Comment by ajcvickers** [comment] 2019-08-30 21:01
@Haza85 EF needs an ordering so that value can be correlated when creating entity instances. EF doesn't do a descending order by default, so I am assuming that you have an ordering in the query which is then being modified by EF. This might be why primary key indexes are not being hit. You might try creating descending indexes on these columns to improve perf.

Beyond that, we would likely need a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing so we can fully investigate.

**Comment by ajcvickers** [comment] 2019-09-06 16:31
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:39 UTC
Labels: closed-no-further-action, customer-reported
