### ISSUE TITLE
Query: Table splitting: Optimization: Same columns projected multiple times

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#10891] opened 2018-02-06 19:12 UTC
Right now we add shared columns (PK/FK for splitting) multiple times to the projection when querying. We could improve this.

**Comment by AndriySvyryd** [comment] 2019-08-22 22:34
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/12491

**Closed** 2022-10-16 12:08 UTC
Labels: type-enhancement, area-perf, closed-duplicate
