### ISSUE TITLE
 Unnecessary SQL generation with owned types (value objects)

### ISSUE THREAD

**Issue by rafaelfgx** [dotnet/efcore#19633] opened 2020-01-18 17:13 UTC
Hi guys,

I found a situation that can be a **performance problem** using owned types to modeling value objects from DDD (Domain Driven Design).

**Entity**

```cs
public class UserEntity
{
    public UserEntity(long id, FullName fullName, Roles roles, Status status)
    {
        Id = id;
        FullName = fullName;
        Roles = roles;
        Status = status;
    }

    public long Id { get; private set; }

    public FullName FullName { get; private set; }

    public Roles Roles { get; private set; }

    public Status Status { get; private set; }
}
```
**Value Object**

```cs
public sealed class FullName : ValueObject
{
    public FullName(string name, string surname)
    {
        Name = name;
        Surname = surname;
    }

    public string Name { get; }

    public string Surname { get; }

    protected override IEnumerable<object> GetEquals()
    {
        yield return Name;
        yield return Surname;
    }
}
```

**Entity Configuration**

```cs
public sealed class UserConfiguration : IEntityTypeConfiguration<UserEntity>
{
    public void Configure(EntityTypeBuilder<UserEntity> builder)
    {
        builder.ToTable("Users", "User");

        builder.HasKey(x => x.Id);

        builder.Property(x => x.Id).IsRequired().ValueGeneratedOnAdd();
        builder.Property(x => x.Roles).IsRequired();
        builder.Property(x => x.Status).IsRequired();

        builder.OwnsOne(x => x.FullName, y =>
        {
            y.Property(x => x.Name).HasColumnName(nameof(UserEntity.FullName.Name)).IsRequired().HasMaxLength(100);
            y.Property(x => x.Surname).HasColumnName(nameof(UserEntity.FullName.Surname)).IsRequired().HasMaxLength(200);
        });
    }
}
```

Executing the following LINQ:

```cs
var user = context.Set<UserEntity>().Where(x => x.Id == 1).SingleOrDefault();
```

Results in the following SQL:

```sql
SELECT TOP(2) [u].[Id], [u].[Roles], [u].[Status], [t].[Id], [t].[Name], [t].[Surname]
FROM [User].[Users] AS [u]
LEFT JOIN (
    SELECT [u0].[Id], [u0].[Name], [u0].[Surname], [u1].[Id] AS [Id0]
    FROM [User].[Users] AS [u0]
    INNER JOIN [User].[Users] AS [u1] ON [u0].[Id] = [u1].[Id]
    WHERE [u0].[Surname] IS NOT NULL AND [u0].[Name] IS NOT NULL
) AS [t] ON [u].[Id] = [t].[Id]
WHERE [u].[Id] = CAST(1 AS bigint)
```

**The above SQL is very bad for something so simple, it should be the following SQL:**

```sql
SELECT TOP(2) [u].[Id], [u].[Roles], [u].[Status], [u].[Name], [u].[Surname]
FROM [User].[Users] AS [u]
WHERE [u].[Id] = CAST(1 AS BIGINT)
```

**The code works normally, the entity and the value object are loaded, but the generated SQL is not optimized.**

**Version: Entity Framework 3.1.**

Thank you for your attention and I am available for any information.

**Comment by ajcvickers** [comment] 2020-01-21 23:46
Duplicate of #18299

**Closed** 2022-10-16 18:06 UTC
Labels: customer-reported
