### ISSUE TITLE
Error in ChangeTracking using Local collection: System.ArgumentOutOfRangeException: Non-negative number required.

### ISSUE THREAD

**Issue by coonmoo** [dotnet/efcore#18535] opened 2019-10-23 13:17 UTC
We are using a DbContext.Objects.Local property to apply changes in memory and flushing them periodically to the DB calling SaveChangesAsync().

This error occurred after removing all objects from the DbContext.Objects.Local collection and calling DbContext.Objects.Local.ToList() afterwards.

```
System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'capacity')
   at System.Collections.Generic.List`1..ctor(Int32 capacity)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManagerExtensions.ToListForState(IStateManager stateManager, Boolean added, Boolean modified, Boolean deleted, Boolean unchanged)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_Local()
   at XXX.XXX.XXX() in d:\a\1\s\src\XXX.XXX.XXX\DbService.cs:line 613
```

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.0
Operating system: Windows Server 2019

**Comment by ajcvickers** [comment] 2019-10-24 18:40
@coonmoo I have not been able to reproduce this--see my code below. Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

```C#
public class Blog
{
    public int Id { get; set; }
    public ICollection<Post> Posts { get; set; }
}

public class Post
{
    public int Id { get; set; }
    public Blog Blog { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>();
    }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog
            {
                Posts = new List<Post>
                {
                    new Post(),
                    new Post()
                }
            });
            
            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            context.Set<Blog>().Include(e => e.Posts).Load();

            var bb = context.Set<Blog>().Local.ToList();
            var bp = context.Set<Post>().Local.ToList();
            
            context.Set<Blog>().Local.Clear();
            context.Set<Post>().Local.Clear();

            var ab = context.Set<Blog>().Local.ToList();
            var ap = context.Set<Post>().Local.ToList();
        }
    }
}
```

**Comment by ajcvickers** [comment] 2019-11-01 15:12
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by douglasg14b** [comment] 2021-09-13 00:24
Yikes, I'm getting this now.... 

Calling `_context.ChangeTracker.Entries();` results in:

> System.ArgumentOutOfRangeException: 'Non-negative number required. (Parameter 'capacity')'

>   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1..ctor(Int32 capacity)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManagerExtensions.ToListForState(IStateManager stateManager, Boolean added, Boolean modified, Boolean deleted, Boolean unchanged)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges()
   at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.TryDetectChanges()
   at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.Entries()

**Closed** 2022-10-16 14:51 UTC
Labels: closed-could-not-reproduce, customer-reported
