### ISSUE TITLE
Adding EF Core to Xamarin.Forms Android project crashes app

### ISSUE THREAD

**Issue by brianlagunas** [dotnet/efcore#10277] opened 2017-11-13 19:57 UTC
Adding the `Microsoft.EntityFrameworkCore.Sqlite` NuGet package to a Xamarin.Forms .Net Standard 2.0 application immediately crashes the app when run.  You do not have to use any of the classes in the package, just add the reference and it will crash.

### Steps to reproduce
Run the attached project
[BlankApp1.zip](https://github.com/aspnet/EntityFrameworkCore/files/1468298/BlankApp1.zip)

### Further technical details
Microsoft.EntityFrameworkCore.Sqlite: 2.0.0
Operating system: Windows 10 FCU
IDE: Visual Studio 2017 15.4.3

**Comment by ajcvickers** [comment] 2017-11-17 21:06
Assigning to @divega along with other Android investigations. Feel free to de-dupe as needed.

**Comment by erikpowa** [comment] 2017-11-21 19:59
Duplicate of #8922, [Workaround](https://github.com/aspnet/EntityFrameworkCore/issues/8922#issuecomment-345375260)

**Comment by divega** [comment] 2018-02-05 21:56
Closing as duplicate of #8922.

**Comment by vulcanlee** [comment] 2018-03-28 12:13
Is this bug  fixed and how to solve this problem?

**Closed** 2022-10-16 11:58 UTC
Labels: closed-duplicate, area-external, area-xamarin
