### ISSUE TITLE
Query: IQueryable in sub select returns error

### ISSUE THREAD

**Issue by joshmouch** [dotnet/efcore#7708] opened 2017-02-24 16:55 UTC
I have an IQueryable that works in the original EntityFramework, but isn't working in Entity Framework Core.

Basically, it looks like this (I've simplified it tremendously):

````

public class Repository {

  private DbContext dbContext;

  public IQueryable<TypeA> QueryA(Expression<Func<TypeA, bool>> filter) {
    return this.dbContext.Set<TypeA>().Where(filter);
  }

  public IQueryable<TypeB> QueryB() {
    return from b in this.dbContext.Set<TypeB>()
        let a = this.QueryA(definesomefilterherethatreferencesb).FirstOrDefault()
        where a != null
        select b;
  }
  
}

````

When I call Repository.QueryB().ToList(), I get:

````

System.NotSupportedException occurred
  HResult=-2146233067
  Message=Cannot parse expression 'value(Repository)' as it has an unsupported type. Only query sources (that is, expressions that implement IEnumerable) and query operators can be parsed.
  Source=Remotion.Linq

````

However, if I change the method QueryB to use DbContext directly, it works as expected:

````

  public IQueryable<TypeB> QueryB() {
    return from b in this.dbContext.Set<TypeB>()
        let a = this.dbContext.Set<TypeA>.FirstOrDefault(definesomefilterherethatreferencesb)
        where a != null
        select b;
  }


````

**Comment by smitpatel** [comment] 2019-09-09 18:55
Marking for re-triage. In the tree we get the client function. Even though it is returning IQueryable, it is also passing a expression to the function which correlates to outer. So there is no way to inline the particular function.

**Comment by smitpatel** [comment] 2019-09-20 18:40
When fixing this, look into what ef6 does to deal with this scenario.

**Comment by smitpatel** [comment] 2020-11-05 23:05
Exceptions
EF6
```
System.NotSupportedException: 'LINQ to Entities does not recognize the method 'System.Linq.IQueryable`1[EF6.Blog] QueryA(System.Linq.Expressions.Expression`1[System.Func`2[EF6.Blog,System.Boolean]])' method, and this method cannot be translated into a store expression.'
```
EF Core 3.1
```
System.InvalidOperationException: Processing of the LINQ expression 'Program.QueryA(b => b.Id > 5)
    .FirstOrDefault()' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
```
EF Core 5.0
```
System.InvalidOperationException: The LINQ expression 'Program.QueryA(b => b.Id > 5)
    .FirstOrDefault()' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

**Comment by ajcvickers** [comment] 2020-11-06 21:13
@joshmouch We have not been able to make the query you posed work on EF6. Please attach a small, runnable project or post a small, runnable code listing that shows the query working with EF6 so that we can investigate.

**Comment by ajcvickers** [comment] 2020-11-20 15:41
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 10:54 UTC
Labels: closed-could-not-reproduce, punted-for-2.0, customer-reported, area-query
