### ISSUE TITLE
Update database against LocalDB does not work

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#6847] opened 2016-10-23 19:44 UTC
### Steps to reproduce

ConnectionString:

```
Data Source=(LocalDB)\v13.0;Database=ProjectManager;AttachDbFilename=C:\Users\sam\AppData\Local\Projects\ProjectManager\Dev\Data\ProjectManager.mdf;Integrated Security=true;MultipleActiveResultSets=True

```

From VS command prompt:

```
dotnet ef database update 20161023181204_createdb

```
### The issue

.mdf file is not created on disk

```
Error Number:1832,State:1,Class:14
Cannot attach the file 'C:\Users\sam\AppData\Local\Projects\ProjectManager\Dev\Data\ProjectManager.mdf' as database 'ProjectManager'.

```
### Further technical details

Open MSMC:

```
create database ProjectManager on (name='ProjectManager', filename='C:\Users\sam\AppData\Local\Projects\ProjectManager\Dev\Data\ProjectManager.mdf')

```

works fine.

The error cited above is widely reported on stackoverflow etc.
Running sqllocaldb stop/delete/create/start does not work.
Running VS as admin, running command prompt as admin does not work.
Running database update against .\sqlexpress works fine.

EF Core version: (found in project.json or packages.config)
Operating system: windows 10
Visual Studio version: 2015 r3

```
{
  "version": "1.0.0-*",

  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Autofac": "4.1.1",
    "Microsoft.EntityFrameworkCore": "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools.Core": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Tools.Cli": "1.0.0-preview1-final",

    "NETStandard.Library": "1.6.0",
    "ProjectManager.Domain": "1.0.0-*",
    "ProjectManager.Model": "1.0.0-*"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "net462" ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.1-*"
        }
      }
    }
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
  }
}


```

**Comment by ajcvickers** [comment] 2016-10-24 16:36
Note for triage: Looks like a dupe of #2810.

**Comment by efidiles** [comment] 2018-01-04 14:22
Hey guys,

We just ran into this ourselves; looks like relative paths aren't supported with `AttachDbFileName`.  

```
System.Data.SqlClient.SqlException (0x80131904): Cannot attach the file '.\OurDbName.mdf' as database 'OurDbName'.
```

Just wanted to express that here for other people who might be bumping into this.  The "fix" is use absolute paths.

**Comment by mrbm2007** [comment] 2018-09-14 18:59
In my case, name of database had '-' character, after changing it to '_' it solved

**Comment by ziham20** [comment] 2019-09-03 18:50
This happens if u deleted .mdf file and sometimes it doesnt allow us create the Db that we suggested so try another Db name :D cheers :D

**Closed** 2022-10-16 10:39 UTC
Labels: closed-duplicate
