### ISSUE TITLE
Unecessary SELECT Inside LEFT Join

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#33067] opened 2024-02-12 08:04 UTC
I have the following code

```
 public class MyDbContext : DbContext
 {
     public DbSet<Book> Books { get; set; }
     public DbSet<Author> Authors { get; set; }

     protected override void OnModelCreating(ModelBuilder modelBuilder)
     {
         base.OnModelCreating(modelBuilder);

         modelBuilder.Entity<Book>()
             .HasMany(e => e.Authors)
             .WithMany(e => e.Books);
     }

     protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
     {
         optionsBuilder.UseSqlServer(@"Server=MyServer;Database=ManyToManyTest;Trusted_Connection=True;TrustServerCertificate=True")
             .EnableSensitiveDataLogging()
             .UseLoggerFactory(GetLoggerFactory());
     }

     private static ILoggerFactory GetLoggerFactory()
     {
         return LoggerFactory.Create(builder =>
         {
             builder.AddConsole().AddFilter(DbLoggerCategory.Database.Command.Name, LogLevel.Information);
         });
     }
 }

 public class Book
 {
     public int BookId { get; set; }
     public string Name { get; set; }
     public ICollection<Author> Authors { get; set; } = new List<Author>();
 }

 public class Author
 {
     public int AuthorId { get; set; }
     public string Name { get; set; }
     public ICollection<Book> Books { get; set; } = new List<Book>();
 }

 public class BookDetailDto
 {
     public string BookName { get; set; }
     public List<int> AuthorIds { get; set; }
 }
```
When I run the following code

```
 var dbContext = new MyDbContext();

 var dbResult = (from book in dbContext.Books
     select new BookDetailDto
     {
         BookName = book.Name,
         AuthorIds = book.Authors.Select(x => x.AuthorId).ToList()
     }).ToList();
```

I can see the following Sql query generated:

```
SELECT [b].[Name], [b].[BookId], [t].[AuthorId], [t].[AuthorsAuthorId], [t].[BooksBookId]
      FROM [Books] AS [b]
      LEFT JOIN (
          SELECT [a0].[AuthorId], [a].[AuthorsAuthorId], [a].[BooksBookId]
          FROM [AuthorBook] AS [a]
          INNER JOIN [Authors] AS [a0] ON [a].[AuthorsAuthorId] = [a0].[AuthorId]
      ) AS [t] ON [b].[BookId] = [t].[BooksBookId]
      ORDER BY [b].[BookId], [t].[AuthorsAuthorId], [t].[BooksBookId
```

Whereas it should be generating the following

````
SELECT [b].[Name] as BookName, [ab].AuthorsAuthorId as AuthorId
FROM [Books] AS [b]
LEFT JOIN AuthorBook [ab] ON b.BookId = ab.BooksBookId
````

### Include provider and version information

EF Core version: 8.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET8.0
Operating system: Windows 10
IDE:  Visual Studio 2022 17.8.6

**Comment by roji** [comment] 2024-02-12 09:32
Duplicate of #28077

**Comment by roji** [comment] 2024-02-12 11:22
@pantonis what makes you say this is an important optimization? Do you have query plans/benchmarks showing that the extra JOIN affects performance in a significant way?

**Comment by pantonis** [comment] 2024-02-12 11:36
It is still an extra join. Do you need a benchmark for that?

**Comment by roji** [comment] 2024-02-12 12:06
Ah, I missed that the query was actually projecting out `[t].[AuthorId]`, meaning the database can't prune the JOIN away (otherwise that could have been optimized on the database side).

So yeah, this indeed is important, and I really hope we'll get around to it, but realistically that likely won't happen for 9.0 given everything else we have planned. I do hope that for 10 we'll be able to do a concentrated push on query perf - there are various other similar issues in the backlog.

**Comment by irunjic** [comment] 2024-02-12 18:11
I just wanted to chime in and say that the fact that this issue won't be resolved until late 2025 at the earliest is disappointing news. Unnecessary joins is one of the reasons my team pushed back on introducing EF in our project.

**Comment by roji** [comment] 2024-02-12 18:52
@irunjic I agree that this is quite important, and I also would like this kind of issue to not occur with EF. I will point out that for those specific queries where something inefficient like this happens - and where the query is important enough perf-wise -  it's always possible to drop down to SQL and still have EF materialize the results. In other words, if this is a reason to not adopt EF, you always have the possibility of inspecting the SQL EF generates and do your own thing where relevant.

**Comment by pantonis** [comment] 2024-02-12 19:02
@roji We have a database with more than 20 of those cases. What is the purpose of using EF  if the most basic M2M (which I think is a fundamental in Dbs) query is not translated correctly? If you do not think this is something that needs to be fixed now but rather in a very distant feature, then I apologize for bringing up this bug.

**Comment by roji** [comment] 2024-02-12 19:25
@pantonis I agree this is important, but to put this in perspective, selecting only the key of the related entity (AuthorId) is a rather infrequent use case (the moment any other property is selected, the join is necessary anyway). Note also that #28077 has only two upvotes; upvotes aren't the only deciding factor (especially when it comes to perf!), but I very much wouldn't consider this "the most basic M2M" scenario, and that's one reason we haven't prioritized this so far.

I'd also advise against thinking "if EF can't even do X this it's probably bad at everything else".. Query optimization is a very complex and uneven field, and there are rough edges; the fact that EF specifically has an extra include in this specific case (which again, is somewhat of a corner case) doesn't imply that it doesn't do other optimizations elsewhere. Every user has their specific bug/feature which they feel is the most important, but we have to prioritize all work for the entire product.

Having written all the above, I do agree in general and beileve we should do a concentrated push on generating better SQL - it's really a matter of competing priorities. I really hope this is something we manage to do soon.

**Closed** 2024-02-29 09:42 UTC
Labels: closed-duplicate, customer-reported
