### ISSUE TITLE
Exception: The current transactionscope is already complete with C# 8 Using Declarations

### ISSUE THREAD

**Issue by jlchavez** [dotnet/efcore#23464] opened 2020-11-24 21:55 UTC
I receive the exception with message: The current transactionscope is already complete with this syntax:

```c#
using var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled)
DbContext.SaveChanges();
if (generateCount.HasValue)
    GenerateQuestions(Work, workTry, generateCount.Value);
DbContext.SaveChanges();
scope.Complete();
```

but not with:

```c#
using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
{
    DbContext.SaveChanges();
    if (generateCount.HasValue)
        GenerateQuestions(Work, workTry, generateCount.Value);
    DbContext.SaveChanges();
    scope.Complete();
}
```

And I have had the same experience with Async calls, not just this sync logic.

**Comment by roji** [comment] 2020-11-24 23:20
C# 8 using declarations don't do anything beyond calling Dispose when the variable goes out of scope, just like the pre-C# 8 using construct calls Dispose when its scope ends; check exactly what's going on after scope.Complete in your code.

If you can't find the issue, please submit a full, runnable code sample rather than the above fragments.

**Comment by jlchavez** [comment] 2020-11-24 23:35
> C# 8 using declarations don't do anything beyond calling Dispose when the variable goes out of scope, just like the pre-C# 8 using construct calls Dispose when its scope ends; check exactly what's going on after scope.Complete in your code.
> 
> If you can't find the issue, please submit a full, runnable code sample rather than the above fragments.

Yeah, I know I've been a .net developer since 2001 (alpha of version 1.0)

This is the second I hit this bug. I'll have to build a sample, because a full runnable code, of the project is like 20MB... As soon as possible as I can build it, I will share it.

**Comment by ajcvickers** [comment] 2020-12-04 17:29
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:11 UTC
Labels: closed-could-not-reproduce, customer-reported
