### ISSUE TITLE
SQLServer UseRowNumberForPaging() option can't handle column name alias

### ISSUE THREAD

**Issue by sbrakl** [dotnet/efcore#9974] opened 2017-10-05 11:01 UTC
I am using Entity Framework 2.0.0 Core with SQL Server 2008 R2. SQL Server 2008 doesn't support OFFSET keyword in the query, hence I am using UseRowNumberForPaging() for paging. i.e. Skip and Take in LINQ.

In my case, DB columns names are different from the model property names. When I used dotnet ef dbcontext scaffold tool to generate my model from Database, it have remove underscores "_" and Pascal cased the word.
e.g. column name "birth_date" would be named "BirthDate" in the model
Which good, as names are clean.

When I run the attached sample application, it would throw following exception

```
info: Microsoft.EntityFrameworkCore.Infrastructure[100403]
      Entity Framework Core 2.0.0-rtm-26452 initialized 'SampleDBContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: RowNumberPaging SensitiveDataLoggingEnabled
warn: Microsoft.EntityFrameworkCore.Database.Command[100400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
fail: Microsoft.EntityFrameworkCore.Database.Command[200102]
      Failed executing DbCommand (40ms) [Parameters=[@__p_0='5', @__p_1='5'], CommandType='Text', CommandTimeout='30']
      SELECT [t].[UserId], [t].[UserName], [t].[DateOfBirth]
      FROM (
          SELECT [b].[id] AS [UserId], [b].[first_name] AS [UserName], [b].[birth_date] AS [DateOfBirth], ROW_NUMBER() OVER(ORDER BY [DateOfBirth]) AS [__RowNumber__]
          FROM [users] AS [b]
      ) AS [t]
      WHERE ([t].[__RowNumber__] > @__p_0) AND ([t].[__RowNumber__] <= (@__p_0 + @__p_1))
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'DateOfBirth'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:df06d020-fe13-41eb-8ca6-30407a0c66ca
Error Number:207,State:1,Class:16
```

### Steps to reproduce
[efbug.zip](https://github.com/aspnet/EntityFrameworkCore/files/1359008/efbug.zip)
I have create a sample application which an reproduce the error. Do the following steps to run the application
1. Create SampleDB Database from the running SampleDB.sql. 
2. Change the connection string in the appsettings.json to point to newly created database
3. dotnet restore and dotnet run to run the application
 
Code fails at following LINQ Query
```c#
            //Get User from 5 to 10 by casting into another BusinessUser
            var subsetUsers = from b in dbContext.Users
                                select new BusinessUser
                                {
                                    UserId = b.Id,
                                    UserName = b.FirstName,
                                    DateOfBirth = b.BirthDate.Value
                                };
            var businessUsers = subsetUsers.OrderBy(u => u.DateOfBirth).Skip(5).Take(5);
```

Query which EF generated is as follow

SELECT [t].[UserId], [t].[UserName], [t].[DateOfBirth]
      FROM (
          SELECT [b].[id] AS [UserId], [b].[first_name] AS [UserName], [b].[**birth_date**] AS [**DateOfBirth**], ROW_NUMBER() OVER(ORDER BY [**DateOfBirth**]) AS [RowNumber]
          FROM [users] AS [b]
      ) AS [t]
      WHERE ([t].[RowNumber] > @__p_0) AND ([t].[RowNumber] <= (@__p_0 + @__p_1))

As you can see, in the OVER(ORDER BY [**DateOfBirth**]) clause, it has use the model property name, and not the DB Column name

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017
SQL Server Version: SQL Server 2008 R2 Standard Edition

[efbug.zip](https://github.com/aspnet/EntityFrameworkCore/files/1359008/efbug.zip)

**Comment by smitpatel** [comment] 2017-10-05 13:35
Duplicate of #9535

**Comment by ajcvickers** [comment] 2018-11-14 23:01
@sbrakl If you are still using RowNumberForPaging, could you please comment on issue #13959 and let us know why?

**Closed** 2022-10-16 11:52 UTC
Labels: closed-duplicate
