### ISSUE TITLE
Flaky test: CreateAsync_checks_for_existence_and_retries_if_no_proccess_until_it_passes

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/efcore#12782] opened 2018-07-24 23:37 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=513800&buildTypeId=XPlat_Windows_Win7_Universe) occasionally with the following error:
```
System.ArgumentException : Keyword not supported: 'PoolBlockingPeriod'.
   at System.Data.SqlClient.SqlConnectionStringBuilder.Reset(Keywords index)
   at System.Data.SqlClient.SqlConnectionStringBuilder.Clear()
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.CreateCreateOperations() in /_/src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs:line 110
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<CreateAsync>d__12.MoveNext() in /_/src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServerDatabaseCreatorTest.<Create_checks_for_existence_and_retries_until_it_passes>d__10.MoveNext() in /_/test/EFCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by ryanbrandenburg** [comment] 2018-07-24 23:37
Can_create_master_connection [failed again](http://aspnetci/viewLog.html?buildId=513800&buildTypeId=XPlat_Windows_Win7_Universe).

**Comment by smitpatel** [comment] 2018-07-24 23:38
Duplicate of #12706

**Closed** 2022-10-16 13:21 UTC
