### ISSUE TITLE
EF Core lazy loading relationship: Cannot cast from String to Int32

### ISSUE THREAD

**Issue by dongle-the-gadget** [dotnet/efcore#20507] opened 2020-04-03 00:59 UTC
I need to access a navigation property from the parent (ForumGroup.Forums) which has a type of ICollection<Forum>. When I try to access one with children, it throws cannot cast from string

Here is the code that throws the error:
``` C#
            if(forumGroup.Forums.Count > 0) (thrown here)
            {
                @foreach(var forum in forumGroup.Forums)
                {
                    <tr>
                        <td>@forum.Name</td>
                        <td>@forum.Topics.Count</td>
                        @if(forum.Topics.Count != 0)
                        {
                            <td>@forum.Topics.Select(f => f.Posts).ToList().Count</td>
                        }
                        else
                        {
                            <td>0</td>
                        }
                    </tr>
                }
            }
    public class ForumGroup
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public ForumGroupPriority Priority { get; set; }
        public virtual ICollection<Forum> Forums { get; set; } (here it throws the exception)
    }
    public class Forum
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public virtual ForumGroup ForumGroup { get; set; }
    }
```

```SQL
CREATE TABLE [dbo].[Forums] (
    [Id]                NVARCHAR (450) NOT NULL,
    [Name]              NVARCHAR (250) NOT NULL,
    [Description]       NVARCHAR (MAX) NOT NULL,
    [ForumGroupId]      NVARCHAR (450) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ForumGroups_Forums] FOREIGN KEY ([ForumGroupId]) REFERENCES [dbo].[ForumGroups] ([Id]) ON DELETE CASCADE,
);
```

``` Exception
Unable to cast object of type 'System.String' to type 'System.Int32'.
   at Microsoft.Data.SqlClient.SqlBuffer.get_Int32()
   at Microsoft.Data.SqlClient.SqlDataReader.GetInt32(Int32 i)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.Load[TSource](IQueryable`1 source)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Load(INavigation navigation, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.NavigationEntry.Load()
   at Microsoft.EntityFrameworkCore.ChangeTracking.CollectionEntry.Load()
   at Microsoft.EntityFrameworkCore.Internal.LazyLoader.Load(Object entity, String navigationName)
   at Microsoft.EntityFrameworkCore.Proxies.Internal.LazyLoadingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ForumGroupProxy.get_Forums()
```
### Further technical details

EF Core version: 3.1.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET Core 3.0) .NET Core 3.1
Operating system: Windows 10 1909 x64
IDE: (e.g. Visual Studio 2019 16.3) Visual Studio 2019 Preview Version 16.5.0 Preview 1.0

**Comment by ajcvickers** [comment] 2020-04-03 18:59
@superkid200 I don't see anything in the code you posted that would cause this. Can you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we are better able to investigate it?

**Comment by superkid200** [comment] 2020-04-04 03:49
Here's the attachment to my Visual Studio solution. It will produce the error when you go to /Forum
[MySite.zip](https://github.com/dotnet/efcore/files/4430702/MySite.zip)

**Comment by superkid200** [comment] 2020-04-04 12:15
I messed up, and forgot to include the database as well. Here is it. It works fine without logging in. The name is exactly the same as it was created.

Here's the link: [https://1drv.ms/u/s!Ap69e4tqkO-6hctOy_eBC5yrGyd7Gw?e=QCfUtX](url)

Just attach it to the LocalDB Server. Sorry for any inconveniences. GitHub doesn't let me upload the file.

**Comment by ajcvickers** [comment] 2020-04-15 17:41
@superkid200 Sorry for the long delay here. I attached the database, but running the application indicates that there are pending migrations. Attempting to apply them results in errors. This usually means that the database is out-of-sync with the code.

**Comment by ajcvickers** [comment] 2020-05-08 15:06
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:19 UTC
Labels: closed-could-not-reproduce, customer-reported
