### ISSUE TITLE
SqlException: EFCore thinks I am trying to identity insert when I never manually set the primary key.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/efcore#29040] opened 2022-09-09 23:15 UTC
### Include your code

```sql
CREATE DATABASE [Test]
GO
USE [Test]
GO

CREATE TABLE [dbo].[Foo](
    [Id]     INT        NOT NULL PRIMARY KEY IDENTITY(1, 1),
    [Foo]    VARCHAR(3) NOT NULL
)
GO
```

```cs
public class Foo
{
    [Key]
    public int Id { get; set; }
    [StringLength(3)]
    public string Foo { get; set; }

    public static Foo Create(string foo)
        => new()
        {
            Foo = foo
        };
}
```

And then to test it:
```cs
_ = await dbContext.Foo.AddAsync(Foo.Create("Bar")).ConfigureAwait(false);
_ = await dbContext.SaveChangesAsync().ConfigureAwait(false);
```
or:

```cs
_ = dbContext.Foo.Add(Foo.Create("Bar"));
_ = dbContext.SaveChanges();
```

### Include stack traces

This broke recently when I migrated from manual Sql to using the ``Add`` and then ``SaveChanges`` methods for some reason. It works with manual Sql though. I expected efcore to ignore default init primary keys with values of ``0`` on creation because runtime initialized it, I even tried testing it by making it nullable in code only and to my surprise it did nothing to fix it, I even tried do use the attribute ``[DatabaseGenerated]`` but all 3 values also changed nothing. Something must have regressed in 6.0.x? Also I do not want to turn IDENTITY_INSERT on because then all of the primary key values would be ``0`` for every record the code creates (which could have different values for the non-primary keys.

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert explicit value for identity column in table 'Foo' when IDENTITY_INSERT is set to OFF.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:a6a399a7-b696-40f0-ba9d-f8dc7168c110
Error Number:544,State:1,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

### Include verbose output

Please include `--verbose` output when filing bugs about the `dotnet ef` or Package Manager Console tools.

This is not a bug with dotnet ef, but with my program's usage of efcore (I think it's a bug in inserting values using it).

### Include provider and version information

EF Core version: 6.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.4

**Comment by AraHaan** [comment] 2022-09-09 23:36
I think that the thing should be aware when an value is an identity column and generate the insert statement without the column so I think this is a bug (probably in the sql server provider).

**Comment by AraHaan** [comment] 2022-09-10 05:34
cc: @ajcvickers

**Comment by ajcvickers** [comment] 2022-09-10 09:21
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by gumbarros** [comment] 2022-09-13 00:19
@AraHaan add the DatabaseGenerated(DatabaseGeneratedOption.Identity) attribute to your Id Column.
```cs
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
[Key]
public int Id { get; set; }
```

**Comment by AraHaan** [comment] 2022-09-13 07:26
I tried that before on my Discord bot and as soon as I used an interaction that would insert into an affected table, it resulted in the exception even with the attribute applied. However it could be that for some reason it could have been using an cached copy of the previous compilation of it.

**Comment by AraHaan** [comment] 2022-09-18 08:45
> @AraHaan add the DatabaseGenerated(DatabaseGeneratedOption.Identity) attribute to your Id Column.
> 
> ```cs
> [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
> [Key]
> public int Id { get; set; }
> ```

I tried that in my discord bot, and that still did not fix it, both when I have it target .NET 6, and .NET 7.

**Comment by ajcvickers** [comment] 2022-09-18 08:52
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-09-18 08:52 UTC
Labels: customer-reported

**Comment by AraHaan** [comment] 2022-09-18 09:05
It's interesting how I am able to run into this no matter what I change in my code. 🤔

**Comment by AraHaan** [comment] 2022-09-18 10:06
Interesting, it seems the issue probably only happens with my Discord Bot then, I tried to repro it with a small project and instead it was working.

**Comment by AraHaan** [comment] 2022-09-18 11:12
After thinking about it, the issue might actually be my insert trigger in the database for the table that I have an issue with on my discord bot.

**Comment by gurustron** [comment] 2023-06-22 22:57
@ajcvickers 

This seems to be a regression from .NET 6 to .NET 7. The similar issue can be found at [StackOverflow](https://stackoverflow.com/questions/76532791/ef-core-7-adding-a-new-object-but-the-id-value-has-a-temporary-value)

**Comment by roji** [comment] 2023-06-23 06:55
@gurustron we're still missing a minimal, runnable repro for this issue. If one is posted we can reopen the issue and investigate.

**Comment by AraHaan** [comment] 2023-06-23 13:07
I think I identified the problem in my code, somewhere in my code was setting it to the default value explicitly in one of my shortcut entity Create methods I made in my code for each of the affected entity types.
