### ISSUE TITLE
How to use HasData() with HasComputedColumnSql() ?

### ISSUE THREAD

**Issue by amoorthaemer** [dotnet/efcore#12687] opened 2018-07-17 12:50 UTC
Hi,

I have a couple of entities with computed SQL columns. When I try to seed these entities with HasData() it chokes on those columns. I can't exclude them because HasData() then complains about a missing property, and I can't fill them either because the MS SQL backend will complain that I can't supply a value for a computed column (which is obvious)

So I was wondering if there is any solution to this problem... Or maybe it has been tackled already

TIA

Bert

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio Enterprises 2017 15.7.5

**Comment by roji** [comment] 2018-07-17 14:48
Note: this is pretty much identical to the problem described in https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/518

**Comment by AndriySvyryd** [comment] 2018-07-17 22:02
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/11969

**Closed** 2022-10-16 13:19 UTC
Labels: customer-reported
