### ISSUE TITLE
The LINQ expression could not be translated after upgrading from EF Core 5 to EF Core 6

### ISSUE THREAD

**Issue by csaSall** [dotnet/efcore#26825] opened 2021-11-25 01:32 UTC
Hello,

After upgrading the project from .Net 5 / EF Core 5 to .Net 6 / EF Core 6, the following query throw exception:

`ctx.Users.GroupBy(x => x.CreatedDate).Average(x => x.Count());`

`System.InvalidOperationException: 'The LINQ expression 'DbSet<User>()
    .GroupBy(x => x.CreatedDate)
    .Average(x => x
        .AsQueryable()
        .Count())' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. `

EF Core version: 6.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer 6.0
Target framework: .NET 6.0
IDE: Visual Studio 2022 17.0.1

**Comment by smitpatel** [comment] 2021-11-29 17:44
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2021-12-07 15:24
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:16 UTC
Labels: closed-could-not-reproduce, customer-reported
