### ISSUE TITLE
GroupBy Issue

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/efcore#17612] opened 2019-09-04 13:39 UTC
.Net core 3 Preview 8

I get an exception with a very basic query

````csharp
var reviews = _context.Reviews.GroupBy(g => g.UserId).ToList();
````
or

````csharp
var reviews = _context.Reviews.GroupBy(g => g.UserId).FirstOrDefault();
````

throw an exception: must be reducible node

**Comment by smitpatel** [comment] 2019-09-04 14:41
It is client side groupby, it will throw error as translation failure in 3.0
Duplicate of #17068

**Closed** 2022-10-16 14:40 UTC
Labels: customer-reported
