### ISSUE TITLE
Long running migrations failed

### ISSUE THREAD

**Issue by asobolev01** [dotnet/efcore#8240] opened 2017-04-20 14:03 UTC
EF Code First 6.1.3
We have an issue, probably with Garbage Collector, when applying long migrations on DB. In this case we adding index on very large table.

**Exception message**: Object '/4e5b14da_612e_418e_bef1_a78633067db8/zpduder6bkbdvcrmhn48cbtr_2.rem' has been disconnected or does not exist at the server.

**Stack trace:**
```C#
System.Runtime.Remoting.RemotingException: Object '/4e5b14da_612e_418e_bef1_a78633067db8/zpduder6bkbdvcrmhn48cbtr_2.rem' has been disconnected or does not exist at the server.
    at System.Data.Entity.Migrations.Design.ToolingFacade.ToolLogger.Verbose(String sql)
    at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
    at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
    at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinTransaction(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext)
    at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinNewTransaction(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
    at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
    at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection)
    at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
    at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
    at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction)
    at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
    at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
    at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
    at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
    at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
    at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
    at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
    at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
    at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
    at System.Data.Entity.Migrations.Console.Program.Run()
    at System.Data.Entity.Migrations.Console.Program.Main(String[] args)
 ERROR: Object '/4e5b14da_612e_418e_bef1_a78633067db8/zpduder6bkbdvcrmhn48cbtr_2.rem' has been disconnected or does not exist at the server.
```

### Further technical details
EF Core version: 6.1.3 (installed from nuget)
Database Provider: System.Data.SqlClient
Operating system: Windows Server 2012
IDE: Command line runner

**Comment by ajcvickers** [comment] 2017-04-21 15:56
@asobolev01 This GitHub repo is for Entity Framework Core issues. Please file EF6 issues on https://github.com/aspnet/EntityFramework6.

That being said, this looks like a duplicate of https://github.com/aspnet/EntityFramework6/issues/96

**Closed** 2022-10-16 11:02 UTC
Labels: closed-external
