### ISSUE TITLE
Useless "using ;" cause error (Migrations CLI)

### ISSUE THREAD

**Issue by BlinkSun** [dotnet/efcore#10418] opened 2017-11-28 18:06 UTC
Hi, when I call a new migration "dotnet ef migrations add MigName", it create new CS files and update FolderDbContextModelSnapshot.cs.

When I try after "dotnet ef database update", I got a "Build Fail".

So, I need to open  FolderDbContextModelSnapshot.cs and DateTime_MigName.Designer.cs and delete the, I dont know why, useless "using ;" on the second line (after the comment) !

After that edit, "dotnet ef database upgrade" work great !

Someone know why migrations add that "using ;" line in both files ?

```c#
// <auto-generated />
using ;
```

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 7
IDE: VSCode

**Comment by ajcvickers** [comment] 2017-11-28 19:01
Duplicate of #2467

**Closed** 2022-10-16 12:01 UTC
Labels: closed-duplicate
