### ISSUE TITLE
Join on nullable entity type generates a redundant LEFT JOIN

### ISSUE THREAD

**Issue by GSPP** [dotnet/efcore#21468] opened 2020-06-30 13:02 UTC
```C#
                    _ = (from c in ctx.TestChildren
                         join p in ctx.TestParents on c.TestParent equals p
                         select new { c, p }).ToList();

    public partial class TestChild
    {
        public int ID { get; set; }
        public int? TestParentID { get; set; }
        public string Name { get; set; }

        public virtual TestParent TestParent { get; set; }
    }

    public partial class TestParent
    {
        public TestParent()
        {
            TestChildren = new HashSet<TestChild>();
        }

        public int ID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<TestChild> TestChildren { get; set; }
    }
```
Results in the following SQL:

```sql
SELECT [t].[ID], [t].[Name], [t].[TestParentID], [t1].[ID], [t1].[Name]
FROM [TestChildren] AS [t]
LEFT JOIN [TestParents] AS [t0] ON [t].[TestParentID] = [t0].[ID]
INNER JOIN [TestParents] AS [t1] ON [t0].[ID] = [t1].[ID]
```

The `LEFT JOIN` to `TestParents` appears to be used to bring in `[t0].[ID]` but that value is available already from `[t].[TestParentID]`.

Tested with EF 5 preview 6.

**Comment by smitpatel** [comment] 2020-06-30 13:42
Duplicate of #15826

**Comment by GSPP** [comment] 2020-06-30 17:18
Damn! I did look for duplicates for quite a while. Didn't hit the right keywords.

**Closed** 2022-10-16 18:31 UTC
Labels: customer-reported
