### ISSUE TITLE
Except statement performance

### ISSUE THREAD

**Issue by chrislamb139** [dotnet/efcore#11018] opened 2018-02-20 22:30 UTC
I have a table schema like this (cutdown):

`CREATE TABLE [scoWMS].[Pallet]
	[Id] [uniqueidentifier] NOT NULL,	
	[Barcode] [nvarchar](100) NOT NULL,	
CREATE TABLE [scoWMS].[Inventory](
	[Id] [uniqueidentifier] NOT NULL,	
	[PalletId] [uniqueidentifier] NULL,
	[Barcode] [nvarchar](100) NOT NULL,`

Where Inventory.PalletId points to Pallet.Id.

I'm trying to do write a query like this using EF:
```
select Barcode from scoWMS.Pallet
except 
select Distinct(PalletBarcode) from scoWMS.Inventory
```

So far I've come up with 2 ways of doing this:
```
 var emptyPallets = _context.Pallets.Select(x => x.Barcode).Except(_context.Inventories.Select(i => i.PalletBarcode)); 
var emptyPallets = (from pal in _context.Pallets select pal.Barcode).Except(from inv in _context.Inventories select inv.PalletBarcode);
```

Both queries return the expected result, but I'm a bit concerned with the SQL it was generating.
I ran a SQL Server Profiler trace to see what SQL was being executed, it is doing a select all on both tables.
```
SELECT [inv].[PalletBarcode]
FROM [scoWMS].[Inventory] AS [inv]
SELECT [pal].[Barcode]
FROM [scoWMS].[Pallet] AS [pal]
```
These are separate SQL statements returning all records from both tables, allowing LINQ to do the Except and not the database.
Is there a better way that I can write the query so that it executes the filtering on the SQL server and not in my application?
Or is the best option to just run a SQL statement (or stored proc) from EF?

I am using "Microsoft.EntityFrameworkCore": "1.1.2"

**Comment by smitpatel** [comment] 2018-02-20 22:36
Duplicate of #6812

**Closed** 2022-10-16 12:10 UTC
