### ISSUE TITLE
Oracle: Correlated_collection_with_complex_order_by_funcletized_to_constant_bool is broken

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12264] opened 2018-06-06 21:02 UTC
Test is in gears of war query test suite.

We produce the following query plan:

```
  (QueryContext queryContext) => IEnumerable<<>f__AnonymousType61<string, List<string>>> _InterceptExceptions(
  |__ source: IEnumerable<<>f__AnonymousType61<string, List<string>>> _ShapedQuery(
  |   |__ queryContext: queryContext, 
  |   |__ shaperCommandContext: SelectExpression: 
  |   |       SELECT "g"."Nickname", "g"."FullName"
  |   |       FROM "Gears" "g"
  |   |       WHERE "g"."Discriminator" IN (N'Officer', N'Gear')
  |   |       ORDER BY (SELECT 1) DESC, "g"."Nickname" NULLS FIRST, "g"."SquadId" NULLS FIRST, "g"."FullName" NULLS FIRST, 
  |   |__ shaper: (QueryContext queryContext | ValueBuffer g) => new { 
  |           string TryReadValue(g, 0, Gear.Nickname), 
  |           List<string> queryContext.QueryBuffer.CorrelateSubquery(
  |           |__ correlatedCollectionId: 0, 
  |           |__ navigation: Gear.Weapons, 
  |           |__ resultCollectionFactory: (INavigation n) => new List<string>(), 
  |           |__ outerKey: new MaterializedAnonymousObject(new object[]{ (object)!(g.IsEmpty) ? string TryReadValue(g, 1, Gear.FullName) : default(string) }), 
  |           |__ tracking: False, 
  |           |__ correlatedCollectionFactory: () => IEnumerable<Tuple<string, MaterializedAnonymousObject, MaterializedAnonymousObject>> _ShapedQuery(
  |           |   |__ queryContext: queryContext, 
  |           |   |__ shaperCommandContext: SelectExpression: 
  |           |   |       SELECT "t"."c", "t"."Nickname", "t"."SquadId", "t"."FullName", "g.Weapons"."Name", "g.Weapons"."OwnerFullName"
  |           |   |       FROM "Weapons" "g.Weapons"
  |           |   |       INNER JOIN (
  |           |   |           SELECT 0 "c", "g0"."Nickname", "g0"."SquadId", "g0"."FullName"
  |           |   |           FROM "Gears" "g0"
  |           |   |           WHERE "g0"."Discriminator" IN (N'Officer', N'Gear')
  |           |   |       ) "t" ON "g.Weapons"."OwnerFullName" = "t"."FullName"
  |           |   |       ORDER BY "t"."c" DESC, "t"."Nickname" NULLS FIRST, "t"."SquadId" NULLS FIRST, "t"."FullName" NULLS FIRST, 
  |           |   |__ shaper: (QueryContext queryContext | TransparentIdentifier<ValueBuffer, MaterializedAnonymousObject> t0) => new Tuple<string, MaterializedAnonymousObject, MaterializedAnonymousObject>(
  |           |           string TryReadValue(t0.Outer, 4, Weapon.Name), 
  |           |           new MaterializedAnonymousObject(new object[]{ (object)!(t0.Outer.IsEmpty) ? string TryReadValue(t0.Outer, 5, Weapon.OwnerFullName) : default(string) }), 
  |           |           new MaterializedAnonymousObject(new object[]
  |           |           { 
  |           |               (object)(object)object TryReadValue(t0.Outer, 1, Gear.Nickname), 
  |           |               (object)(object)object TryReadValue(t0.Outer, 2, Gear.SquadId) 
  |           |           })
  |           |       )), 
  |           |__ correlationPredicate: (MaterializedAnonymousObject o | MaterializedAnonymousObject i) => object i.GetValue(0) == default(object) || object o.GetValue(0) == default(object) ? False : (string)object o.GetValue(0) == (string)object i.GetValue(0))
  |        }), 
  |__ contextType: TestModels.GearsOfWarModel.GearsOfWarContext, 
  |__ logger: DiagnosticsLogger<Query>, 
  |__ queryContext: Unhandled parameter: queryContext)
```
  
which throws:

FROM keyword not found where expected
     at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
     at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
     at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
     at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
     at System.Data.Common.DbCommand.ExecuteReader()
     at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
     at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
     at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
     at Microsoft.EntityFrameworkCore.Oracle.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
     at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
     at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()

We shouldn't be introducing `ORDER BY (SELECT 1)` in the first query

**Comment by smitpatel** [comment] 2018-06-06 21:11
Duplicate of #10513

**Closed** 2022-10-16 12:29 UTC
Labels: closed-duplicate
