### ISSUE TITLE
Stored procedure CRUD mapping

### ISSUE THREAD

**Issue by ekaggata** [dotnet/efcore#7854] opened 2017-03-11 15:00 UTC
As an alternative to the default table query generation facilities there is to be an option to map the CRUD operations to stored procedures.

**Comment by strangeattr** [comment] 2017-03-11 15:01
Surprisingly I couldn't found this feature request submitted already. I am sorry if it has actually already been.

**Comment by strangeattr** [comment] 2017-03-11 15:06
PS: It would sound to broad so I have preferred the more specific task, ideally, however, EF Core should support purely logical application-level entities that are not represented directly by any specific table in the DB but are mapped (in their create/read/update/delete/find actions) to an additional layer of logic implemented on the DB side, on the model code side or both.

**Comment by ErikEJ** [comment] 2017-03-11 15:23
Duplicate of https://github.com/aspnet/EntityFramework/issues/245

**Closed** 2022-10-16 10:56 UTC
