### ISSUE TITLE
Easier way configure conversion for all properties of readonly struct type

### ISSUE THREAD

**Issue by RdJNL** [dotnet/efcore#25896] opened 2021-09-06 19:14 UTC
I have a readonly struct type and I'm trying to configure my model in such a way that all properties of that type (nullable or not) get the same value converter:

```C#
public sealed class MyContext : DbContext
{
    public MyContext(DbContextOptions options)
        : base(options)
    {
    }

    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        configurationBuilder
            .Properties<SimpleStruct>()
            .HaveConversion<Conv, Comp>();

        configurationBuilder
            .Properties<SimpleStruct?>()
            .HaveConversion<Conv, Comp2>();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Model stuff
    }
}

public readonly struct SimpleStruct
{
    public readonly int X;
    
    public SimpleStruct(int x)
    {
        X = x;
    }
}

internal sealed class Conv : ValueConverter<SimpleStruct, int>
{
    public Conv()
        : base(v => v.X, x => new SimpleStruct(x), null)
    {
    }
}

internal sealed class Comp : ValueComparer<SimpleStruct>
{
    public Comp()
        : base(false)
    {
    }
}

internal sealed class Comp2 : ValueComparer<SimpleStruct?>
{
    public Comp2()
        : base(false)
    {
    }
}
```

This is a lot of code for something so simple. I tried to simplify this, for example by using one ValueComparer, but that results in runtime exceptions. It would be nice if this could be done in an easier way.

**Comment by roji** [comment] 2021-09-06 19:35
Duplicate of #25416

**Comment by roji** [comment] 2021-09-06 19:36
@RdJNL this should work automatically for nullable properties in the latest bits. [Can you give the latest daily builds a try](https://docs.microsoft.com/en-us/ef/core/what-is-new/#get-it-now) and report back on the results?

**Comment by ajcvickers** [comment] 2021-09-06 19:39
@RdJNL Also, you should not need a custom value comparer for a read-only struct like that. See [Simple immutable structs](https://docs.microsoft.com/en-us/ef/core/modeling/value-comparers?tabs=ef5#simple-immutable-structs).

**Comment by RdJNL** [comment] 2021-09-06 20:49
@ajcvickers I know that, but if I use the generic overload of HaveConversion, I'm forced to provide a comparer type.

**Comment by RdJNL** [comment] 2021-09-06 21:14
@roji Just tried it with 6.0.0-rc.2.21456.1, but it doesn't work, I need separate `Properties<>()` calls. If I only configure the non-nullable type I get the following exception:
```
System.InvalidOperationException: 'The property 'A.B' is of type 'SimpleStruct?' which is not supported by the current database provider. Either change the property CLR type, or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.'
```

Best I found so far is to use the non-generic HaveConversion, which at least lets me get rid of the value comparers:

```C#
configurationBuilder
    .Properties<SimpleStruct>()
    .HaveConversion(typeof(Conv), null);

configurationBuilder
    .Properties<SimpleStruct?>()
    .HaveConversion(typeof(Conv), null);
```

**Comment by roji** [comment] 2021-09-06 21:24
/cc @AndriySvyryd 

Here's a repro using the latest release/6.0 (a0bb25fec68c07e7c123ffba28224548099f4ea9)
<details>
<summary>Repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        configurationBuilder
            .Properties<SimpleStruct>()
            .HaveConversion<Conv>();

        // configurationBuilder
            // .Properties<SimpleStruct?>()
            // .HaveConversion<Conv>();
    }
}

public class Blog
{
    public int Id { get; set; }

    public SimpleStruct SimpleStruct { get; set; }
    public SimpleStruct? SimpleStruct2 { get; set; }
}

internal sealed class Conv : ValueConverter<SimpleStruct, int>
{
    public Conv()
        : base(v => v.X, x => new SimpleStruct(x), null)
    {
    }
}

public readonly struct SimpleStruct
{
    public readonly int X;

    public SimpleStruct(int x)
    {
        X = x;
    }
}
```

**Comment by RdJNL** [comment] 2021-09-06 21:33
@roji @AndriySvyryd There's a mistake in the repro. The _ConfigureConventions_ method should be like this:

```C#
    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        configurationBuilder
            .Properties<SimpleStruct>()
            .HaveConversion(typeof(Conv), null);

        // configurationBuilder
            // .Properties<SimpleStruct?>()
            // .HaveConversion(typeof(Conv), null);
    }
```

If you use `HaveConversion<Conv>()` it's gonna try to convert the _SimpleStruct_ to a _Conv_, which is not a success.

**Comment by RdJNL** [comment] 2021-09-06 21:34
Misclick, sorry for that.

**Closed** 2021-09-10 21:40 UTC
Labels: type-enhancement, closed-fixed, customer-reported, area-model-building

**Comment by RdJNL** [comment] 2021-09-10 21:46
Thanks!
