### ISSUE TITLE
How do you make call by using stored procedure in EF core 3 using FromSqlRow?

### ISSUE THREAD

**Issue by jt4000** [dotnet/efcore#19013] opened 2019-11-21 18:13 UTC
I can't make a call with SP when I use EF core 3 using FromSQLRow.

It works in EF core 2 but not in EF core 3.

What approach should I go?

**Comment by smitpatel** [comment] 2019-11-21 20:29
Duplicate of #19014

**Closed** 2022-10-16 14:57 UTC
Labels: customer-reported
