### ISSUE TITLE
Mixed_sync_async_in_query_cache is flaky

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#16218] opened 2019-06-24 15:24 UTC
```
Microsoft.EntityFrameworkCore.Query.AsyncSimpleQuerySqlServerTest.Mixed_sync_async_in_query_cache
  No source available
   Duration: 6 ms

  Message: 
    Microsoft.Data.SqlClient.SqlException : The incoming tabular data stream (TDS) protocol stream is incorrect. The MARS TDS header contained errors.
  Stack Trace: 
    at SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    at TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
    at TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
    at SqlDataReader.TryConsumeMetaData()
    at SqlDataReader.get_MetaData()
    at SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
    at SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
    at SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
    at SqlCommand.ExecuteReader(CommandBehavior behavior)
    at RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject) in RelationalCommand.cs line: 363
    at Enumerator.MoveNext() in QueryingEnumerable.cs line: 94
    at List`1.ctor(IEnumerable`1 collection)
    at Enumerable.ToList[TSource](IEnumerable`1 source)
    at AsyncSimpleQueryTestBase`1.Mixed_sync_async_in_query_cache() in AsyncSimpleQueryTestBase.cs line: 261
    at --- End of stack trace from previous location where exception was thrown ---
```

**Comment by smitpatel** [comment] 2019-06-24 15:25
Related https://github.com/dotnet/SqlClient/issues/85

**Comment by ajcvickers** [comment] 2019-06-24 17:59
@divega to follow up with SqlClient.

**Comment by divega** [comment] 2019-06-24 19:43
@smitpatel does this happen on specific OS platforms?

**Comment by divega** [comment] 2019-06-24 20:34
I talked to @smitpatel offline and this happens on Windows, which I think it is consistent with dotnet/SqlClient#85.

**Comment by ajcvickers** [comment] 2019-07-01 16:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2019-07-01 18:16
Triage: On the backlog as blocked by dotnet/SqlClient#85 so that we can re-enable the test once that issue is fixed.

**Comment by ajcvickers** [comment] 2022-12-08 22:34
Test was reenabled as part of #27050.

**Closed** 2022-12-08 22:34 UTC
Labels: type-bug, closed-fixed, area-external, area-query
