### ISSUE TITLE
Property order not respected when using a owned class

### ISSUE THREAD

**Issue by amoorthaemer** [dotnet/efcore#12101] opened 2018-05-22 13:46 UTC
Hi,

I noticed that the ordering of database columns is not respected when including an owned class in the entity. Instead of creating the columns in declaration order, the owned class property columns are created first

Cheers
Bert

**Comment by ajcvickers** [comment] 2018-05-25 19:26
@amoorthaemer I have not been able to reproduce this--my test application is below. Can you please either update my code or post your own runnable project/solution or code listing such that it reproduces the behavior you are seeing?

```C#
public class Blog
{
    public int Id { get; set; }
    public DateTime CreatedOn { get; set; }
    public Name OwnerName { get; set; }
    public DateTime DeletedOn { get; set; }
    public Name AlternateName { get; set; }
}

public class Name
{
    public string Last { get; set; }
    public string First { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
             context.Database.EnsureDeleted();
             context.Database.EnsureCreated();
        }
    }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>(b =>
        {
            b.OwnsOne(e => e.OwnerName);
            b.OwnsOne(e => e.AlternateName);
        });
    }
}
```

```sql
      CREATE TABLE [Blogs] (
          [Id] int NOT NULL IDENTITY,
          [CreatedOn] datetime2 NOT NULL,
          [OwnerName_Last] nvarchar(max) NULL,
          [OwnerName_First] nvarchar(max) NULL,
          [DeletedOn] datetime2 NOT NULL,
          [AlternateName_Last] nvarchar(max) NULL,
          [AlternateName_First] nvarchar(max) NULL,
          CONSTRAINT [PK_Blogs] PRIMARY KEY ([Id])
      );
```

**Comment by ajcvickers** [comment] 2018-06-01 17:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:26 UTC
Labels: closed-could-not-reproduce, customer-reported
