### ISSUE TITLE
Audit login / logout entries wrap every query in SQL Server Profiler log

### ISSUE THREAD

**Issue by nettashamir-allocate** [dotnet/efcore#33900] opened 2024-06-04 14:51 UTC
I'm looking at the performance of my application using SQL Server Profiler as it is currently running very slow.
I notice that all queries sent to the DB by EFCore are wrapped in "Audit login" and "Audit logout" entries.

For eaxmple, the following two queries:

```
		var dbContext = new TestDbContext();
		var accounts = dbContext.Accounts.ToList();
		var blogs = dbContext.Blogs.ToList();
		dbContext.Dispose();
```

result in the following profiler entries:

![image](https://github.com/dotnet/efcore/assets/87973494/3ec90ab5-1805-419f-8a05-86c5111f26bc)

Is EFCore opening and closing the DB connection for each query?
If yes, is there a way to tell it to reuse the same connection or a pooled connection?

### provider and version information

EF Core version: 7.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer 7.0.5
Target framework: .NET 6.0

**Comment by ajcvickers** [comment] 2024-06-04 15:09
@nettashamir-allocate By default, EF Core opens the logical connection to the database before it does something, then closes it again as soon as it can. This is best practice for making the most efficient use of connections. Under the covers, the physical connection from the pool will not be opened and closed every time EF does a logical open. Instead, it will get a (usually) already open physical connection from the pool.

**Comment by roji** [comment] 2024-06-04 15:13
@nettashamir-allocate have you by any chance disabled pooling by setting Pooling=false on the connection string?

**Comment by ajcvickers** [comment] 2024-06-15 14:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2024-06-15 14:38 UTC
Labels: closed-no-further-action, customer-reported
