### ISSUE TITLE
ExecuteUpdateAsync don't work when using "modelBuilder.Entity<Country>().Navigation(e => e.MyFile).AutoInclude();" in Context

### ISSUE THREAD

**Issue by Andrey-2021** [dotnet/efcore#30250] opened 2023-02-10 09:39 UTC
Please check.

I have 
`class Country
{
public int MenuPosition { get; set; }

public int? MyFileId { get; set; }
public MyFile? MyFile { get; set; }
}
`

when  in  context 
I include AutoInclude:

`public class SqlDbContext : DbContext

{

  protected override void OnModelCreating(ModelBuilder modelBuilder)

    {
          modelBuilder.Entity<Country>().Navigation(e => e.MyFile).AutoInclude();
    }
}
`

It's NOT work:
(where TEntity - Country)
public async Task<BaseResponse> ChangingMenuPositionAsync<TEntity>(TEntity entity)
{
        ...
            var n = await db.Set<TEntity>()
            .Where(x => x.MenuPosition >= entity.MenuPosition)
            .ExecuteUpdateAsync(s => s.SetProperty(b => b.MenuPosition, b => b.MenuPosition + 1));
        ...
}

But,
if we DELETE 
`      modelBuilder.Entity<Country>().Navigation(e => e.MyFile).AutoInclude();`

It's WORK !!!
`var n = await db.Set<TEntity>()
.Where(x => x.MenuPosition >= entity.MenuPosition)
.ExecuteUpdateAsync(s => s.SetProperty(b => b.MenuPosition, b => b.MenuPosition + 1));`

----------------------------------------------------------------------------------
System.InvalidOperationException: "The LINQ expression 'DbSet<Country>()
    .Where(c => c.MenuPosition >= __entity_MenuPosition_0)
    .LeftJoin(
        inner: DbSet<MyFile>(), 
        outerKeySelector: c => EF.Property<int?>(c, "MyFileId"), 
        innerKeySelector: m => EF.Property<int?>(m, "Id"), 
        resultSelector: (o, i) => new TransparentIdentifier<Country, MyFile>(
            Outer = o, 
            Inner = i
        ))
    .Select(c => IncludeExpression(
        EntityExpression:
        c.Outer, 
        NavigationExpression:
        c.Inner, MyFile)
    )
    .ExecuteUpdate(s => s.SetProperty<int>(
        propertyExpression: b => b.MenuPosition, 
        valueExpression: b => b.MenuPosition + 1))' could not be translated. Additional information: The following lambda argument to 'SetProperty' does not represent a valid property to be set: 'b => b.MenuPosition'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information."

------------------------------------------------------------------------------
Microsoft.EntityFrameworkCore 7.0.0.
Microsoft.EntityFrameworkCore.SqlServer 7.0.0.
Microsoft Visual Studio Community 2022 (64) 17.4.4

**Comment by ajcvickers** [comment] 2023-02-10 10:40
Duplicate of #28727

**Closed** 2023-02-15 12:29 UTC
Labels: closed-duplicate, customer-reported

**Comment by Andrey-2021** [comment] 2023-02-15 12:33
Thanks
