### ISSUE TITLE
Contains cannot be translated.

### ISSUE THREAD

**Issue by ItsSmiffy** [dotnet/efcore#20272] opened 2020-03-13 14:30 UTC
I am trying to create a query to get all Roles a User is part of, but I cannot get the .contains method to be translated to SQL. I've tried to query the RoleMembership (many-many join table) various ways but the exception thrown always says the Linq expression cannot be translated.

```CSharp
public class Role {
   // private backing field for encapsulation
   private IList<RoleMembership> _memberships = new List<RoleMembership>();

   public IEnumerable<User> Members => _memberships.Select(x => x.User).ToList();
  
   // exposed the actual collection to try and query on that
   public IEnumerable<RoleMembership> RoleMemberships => _memberships;
}

public class RoleMembership {

  public Role Role { get; protected set; }

  public User User { get; protected set; }
}
```

Linq expressions which cannot be translated:

```CSharp

// query on members collection
DbSet<Role>.Where(role => role.Memberships.Any(m => userIds.Contains(m.Id)));

// attempted to query on the actual relationship collection
DbSet<Role>.Where(role => role.RoleMemberships.Any(m => userIds.Contains(m.User.Id)));

// attempted to query by equals 
DbSet<Role>.Where(role => role.Members.Any(m => m.Id == userId)

```

I was using EF Core version 3.0.0 when I came across the problem, but upgrading to 3.1.2 has not resolved the issue.

I've tested it with a simpler predicate on Entity Ids which succeeds so I can only presume it is to do with the collection of items and the way i'm trying to query them/declare them on the entity.

```CSharp
// this is translated to SQL fine
.Where(x => ids.contains(x.Id));
```

Further technical details
EF Core version: 3.1.2
Database provider: Pomolo

**Comment by ajcvickers** [comment] 2020-03-15 20:31
@ItsSmiffy We looked at this, but it's not clear what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces the behavior you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-03-23 16:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:16 UTC
Labels: closed-could-not-reproduce, customer-reported
