### ISSUE TITLE
Query: ArgumentNullException when using ternary operator with null comparison

### ISSUE THREAD

**Issue by Caskia** [dotnet/efcore#10374] opened 2017-11-22 09:46 UTC
#9223
This bug shows up again when I upgrade my library to 2.0.1.

The problem seems to be Boolean type.

#### Further technical details
EF Core version: 2.0.1
Database Provider: Pomelo.EntityFrameworkCore.MySql
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by smitpatel** [comment] 2017-11-22 16:17
It is fixed in 2.1.0 release and not in 2.0.1. The bug remains exist in 2.0.1 package.

**Comment by smitpatel** [comment] 2017-11-22 16:17
Duplicate of #9223

**Closed** 2022-10-16 12:00 UTC
Labels: closed-duplicate
