### ISSUE TITLE
System.InvalidOperationException with Composite Key

### ISSUE THREAD

**Issue by ctodd1** [dotnet/efcore#7236] opened 2016-12-12 14:40 UTC
The instance of entity type cannot be tracked because another instance of this type with the same key is already being tracked. When adding new entities, for most key types a unique temporary key value will be created if no key is set (i.e. if the key property is assigned the default value for its type). If you are explicitly setting key values for new entities, ensure they do not collide with existing entities or temporary values generated for other new entities. When attaching existing entities, ensure that only one entity instance with a given key value is attached to the context.

Run the attached application to reproduce.

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 x64
IDE: Visual Studio 2015 & 2017 RC
[efcore_issue.zip](https://github.com/aspnet/EntityFramework/files/646237/efcore_issue.zip)

**Comment by ajcvickers** [comment] 2016-12-12 18:03
@ctodd1 Looks like a dupe of #7084. As a workaround, try removing the Key attributes from group_id and account_id in afw_security_grouping.

**Comment by ctodd1** [comment] 2016-12-12 18:08
That worked! Thanks!

**Closed** 2022-10-16 10:46 UTC
