### ISSUE TITLE
Support for abstract types in JSON

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/efcore#30043] opened 2023-01-12 14:16 UTC
Support in EF7 and upcoming work in EF8 for JSON is coming along nicely, and I was wondering if there might be room to continue expanding on it.

This specific idea is to support of interfaces or otherwise abstract types in JSON columns, through the use of a type hint that gets embedded with the data.

I've accomplished this in the past by writing my own `.HasConversion`, accompanied by some custom `System.Text.Json` [de]serialization voodoo.  This ended up being quite useful for working with the data after it was retrieved, but obviously didn't fully integrate with EF in terms of being able to filter on properties defined by the contracts.

An example of how this could be useful is for storing arrays/collections as part of a known JSON type:

```json
{
    "configurations": [
        {
            "_discriminator": "configuration-type-1",
            "specificToBoth": "All types would have this.",
            "specificToOne": "Only type one would have this."
        },
        {
            "_discriminator": "configuration-type-2",
            "specificToBoth": "All types would have this.",
            "specificToTwo": "Only type two would have this."
        }
    ],
    "singleConfiguration": {
        "_discriminator": "configuration-type-3",
        "specificToBoth": "All types would have this.",
        "specificToThree": "Only type three would have this."
    }
}
```

This could be deserialized into something like:

```csharp
public class ApplicationSettings
{
    public IList<Configuration> Configurations { get; set; } = new();
    public Configuration SingleConfiguration { get; set; }
}

public interface Configuration
{
    public string SpecificToBoth { get; }
}

public class ConfigurationTypeOne : Configuration
{
    public string SpecificToBoth { get; set; }

    public string SpecificToOne { get; set; }
}

public class ConfigurationTypeTwo : Configuration
{
    public string SpecificToBoth { get; set; }

    public string SpecificToTwo { get; set; }
}

public class ConfigurationTypeThree : Configuration
{
    public string SpecificToBoth { get; set; }

    public string SpecificToThree { get; set; }
}
```

New EF-based JSON filtering would only allow filtering on the fields it has reason to expect, so in this case, `SpecificToBoth`.  But that alone would be quite powerful as this technique allows for a lot of dynamism in the schema without requiring migrations.

**Comment by roji** [comment] 2023-01-27 20:26
@atrauzzi is this a duplicate of #27779?

**Comment by atrauzzi** [comment] 2023-01-28 06:50
I think it likely is, but I wouldn't mind having the details I outline here merged in if possible.

There are some specifics around when the root object is a dictionary or list of an abstract type that I think could really make the feature stand out.

**Comment by roji** [comment] 2023-01-28 07:20
OK, thanks - closing as a duplicate.

I think we have this cases firmly in mind, but definitely feel free to post the above as a comment under #27779 - it could indeed help with some context.

**Comment by roji** [comment] 2023-01-28 07:20
Duplicate of #27779

**Closed by roji** 2023-01-28 07:20 UTC
Labels: type-enhancement, customer-reported
