### ISSUE TITLE
Conversion not working for different type backing field.

### ISSUE THREAD

**Issue by oguzhaneren** [dotnet/efcore#11753] opened 2018-04-20 06:26 UTC
I'm trying to bind data to getter property with Conversion but EF Core throws excpetion.

https://github.com/aspnet/EntityFrameworkCore/blob/d3335aa094b661c8c856b6a4d6391c2c713baf8d/src/EFCore/Storage/ValueConversion/ValueConverter%60.cs#L53 lines cause exception when changing type. 

If provided custom change type strategy over https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore/Storage/ValueConversion/ConverterMappingHints.cs, it can be useful and will resolve the problem.
```
Exception message: Object must implement IConvertible.
Stack trace:    at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass3_0`2.<SanitizeConverter>b__0(Object v)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

### Steps to reproduce

```c#
public class Project
{
	private ISet<Member> _members = new HashSet<Member>();
	
	public string Id {get;protected set;}
	
	public IEnumerable<Member> Members => _members;
}

public class Member
{
	public string Id {get;protected set;}
	public string Name {get;protected set;}
}

// Mapping: 
var converter = new ValueConverter<IEnumerable<Member>, string>(
    v => JsonConvert.SerializeObject(v),
    v => JsonConvert.DeserializeObject<IEnumerable<Member>>(v));

b.Property(x => x.Members)
.HasConversion(converter);
```

### Further technical details
EF Core version: 2.1.0-preview2-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro (x64)
IDE:  Visual Studio 2017 15.6.6

**Comment by tangdf** [comment] 2018-04-20 06:37
```c#
// Mapping: 
var converter = new ValueConverter<IEnumerable<Member>, string>(
v => JsonConvert.SerializeObject(v),
v => JsonConvert.DeserializeObject<HashSet<Member>>(v));
```

**Comment by oguzhaneren** [comment] 2018-04-20 06:51
@tangdf its not working, same error

**Comment by tangdf** [comment] 2018-04-20 10:33
Mapping: 
```c#
   modelBuilder.Entity<Project>(
       b =>
       {
           var converter = new ValueConverter<HashSet<Member>, string>(
               v => JsonConvert.SerializeObject(v),
               v => JsonConvert.DeserializeObject<HashSet<Member>>(v));

           b.Property(x => x.Members)
               .HasConversion(converter);
       });
```

Enitty:
```C#
   public class Project
   {
       private HashSet<Member> _members = new HashSet<Member>();

       public string Id { get; protected set; }

       public HashSet<Member> Members => _members;
   }

```

**Comment by oguzhaneren** [comment] 2018-04-20 10:53
this works but does not meet my expectations. I need to expose 'Members' property as readonly. I don't want to modify collections from the outside of model.

**Comment by ajcvickers** [comment] 2018-04-20 20:44
This is a duplicate of #11501--I tried with the current code base and it works correctly.

You may be able to test with [the nightly builds of 2.1](https://dotnet.myget.org/gallery/dotnet-core).

**Closed** 2022-10-16 12:20 UTC
Labels: closed-duplicate
