### ISSUE TITLE
Alternate key relationship mapping throws when returned as a readonly collection

### ISSUE THREAD

**Issue by ajeetys** [dotnet/efcore#11234] opened 2018-03-12 03:23 UTC
Relationship mapped based on alternate keys with a backing field and being returned as a readonly collection throws exception. This happens either through eager loading or explicit loading.

Course collection gets loaded, but the Coupons throws.

```
Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred in the database while iterating the results of a query for context type 'EFCoreTest.StudentContext'.
      System.NotSupportedException: Collection is read-only.
         at System.ThrowHelper.ThrowNotSupportedException(ExceptionResource resource)
         at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.Add(Object instance, Object value)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.AddToCollection(InternalEntityEntry entry, INavigation navigation, InternalEntityEntry value)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.ToDependentFixup(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, ISet`1 handledForeignKeys, Boolean fromQuery)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.TrackedFromQuery(InternalEntityEntry entry, ISet`1 handledForeignKeys)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.TrackedFromQuery(InternalEntityEntry entry, ISet`1 handledForeignKeys)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer valueBuffer, ISet`1 handledForeignKeys)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.StartTracking(Object entity, IEntityType entityType)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollection[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relatedEntitiesFactory, Func`3 joinPredicate)
         at lambda_method(Closure , QueryContext , Student , Object[] )
         at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._Include[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Action`3 fixup)
         at lambda_method(Closure , Student )
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
System.NotSupportedException: Collection is read-only.
   at System.ThrowHelper.ThrowNotSupportedException(ExceptionResource resource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.Add(Object instance, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.AddToCollection(InternalEntityEntry entry, INavigation navigation, InternalEntityEntry value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.ToDependentFixup(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, ISet`1 handledForeignKeys, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.TrackedFromQuery(InternalEntityEntry entry, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.TrackedFromQuery(InternalEntityEntry entry, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer valueBuffer, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.StartTracking(Object entity, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollection[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relatedEntitiesFactory, Func`3 joinPredicate)
   at lambda_method(Closure , QueryContext , Student , Object[] )
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._Include[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Action`3 fixup)
   at lambda_method(Closure , Student )
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
Unhandled Exception: System.NotSupportedException: Collection is read-only.
   at System.ThrowHelper.ThrowNotSupportedException(ExceptionResource resource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.Add(Object instance, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.AddToCollection(InternalEntityEntry entry, INavigation navigation, InternalEntityEntry value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.ToDependentFixup(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, ISet`1 handledForeignKeys, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.TrackedFromQuery(InternalEntityEntry entry, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.TrackedFromQuery(InternalEntityEntry entry, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer valueBuffer, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.StartTracking(Object entity, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollection[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relatedEntitiesFactory, Func`3 joinPredicate)
   at lambda_method(Closure , QueryContext , Student , Object[] )
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._Include[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Action`3 fixup)
   at lambda_method(Closure , Student )
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFCoreTest.Program.LoadStudents() in ..\EFCoreTest\Program.cs:line 89
   at EFCoreTest.Program.Main(String[] args) in ..\EFCoreTest\Program.cs:line 23
```

### Steps to reproduce

```c#
public class Student
{
	public int Id { get; set; }

	public string Code { get; set; }

	public string Name { get; set; }

	private readonly List<Coupon> _coupons = new List<Coupon>();
	public IEnumerable<Coupon> Coupons => _coupons.AsReadOnly();

	private readonly List<Course> _courses = new List<Course>();
	public IEnumerable<Course> Courses => _courses.AsReadOnly();

	public void AddCoupons(IEnumerable<Coupon> coupons) => _coupons.AddRange(coupons);

	public void AddCourses(IEnumerable<Course> courses) => _courses.AddRange(courses);
}

public class Course
{
	public int Id { get; set; }

	public int StudentId { get; set; }

	public string Name { get; set; }
}

public class Coupon
{
	public int Id { get; set; }

	public string StudentCode { get; set; }

	public string DiscountCode { get; set; }
}

public class StudentContext : DbContext
{
	public DbSet<Student> Students { get; set; }

	public DbSet<Coupon> Coupons { get; set; }

	public DbSet<Course> Courses { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Student>()
			.HasAlternateKey(s => s.Code);

		modelBuilder.Entity<Student>()
			.Metadata
			.FindNavigation(nameof(Student.Courses))
			.SetPropertyAccessMode(PropertyAccessMode.Field);

		modelBuilder.Entity<Student>()
			.Metadata
			.FindNavigation(nameof(Student.Coupons))
			.SetPropertyAccessMode(PropertyAccessMode.Field);

		modelBuilder.Entity<Student>()
			.HasMany(s => s.Coupons)
			.WithOne()
			.HasForeignKey(s => s.StudentCode)
			.HasPrincipalKey(c => c.Code);
	}

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=StudentDb; Trusted_Connection=True;App=StudentContext");
		optionsBuilder.EnableSensitiveDataLogging();
	}
}

class Program
{
	static void Main(string[] args)
	{
		var _context = new StudentContext();
		_context.GetService<ILoggerFactory>().AddConsole();
		_context.Database.EnsureDeleted();
		_context.Database.EnsureCreated();

		var student = InsertNewStudent(_context);

		LoadStudents();
		Console.ReadLine();
	}

	private static Student InsertNewStudent(StudentContext _context)
	{
		const string code = "ORG";
		var student = new Student
		{
			Name = "Student_1",
			Code = code
		};
		var coupons = new List<Coupon>
			{
				new Coupon
				{
					StudentCode = code, DiscountCode = "ABC"
				},
				new Coupon
				{
					StudentCode = code, DiscountCode = "PQR"
				}
			};
		student.AddCoupons(coupons);
		//student.Coupons = coupons;

		var courses = new List<Course>
		{
			new Course
			{
				Name = "Math"
			},
			new Course
			{
				Name = "Art"
			}
		};
		student.AddCourses(courses);
		//student.Courses = courses;

		_context.Students.Add(student);
		_context.SaveChanges();
		return student;
	}

	private static void LoadStudents()
	{
		var _context = new StudentContext();
		var students = _context.Students
			.Include(s => s.Courses)
			.Include(s => s.Coupons)
			.ToList();
		//_context.Entry(students.FirstOrDefault())
		//    .Collection(s => s.Coupons)
		//    .Load();
	}
}
```

Changing to below, results in no exception, but the collection is not loaded.
```c#
public IEnumerable<Coupon> Coupons => _coupons.ToList();
```
When changed to this, the collection is loaded.
```c#
public IEnumerable<Coupon> Coupons => _coupons;
```

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 15.5.7

**Comment by smitpatel** [comment] 2018-03-12 03:47
Duplicate of #10612 

As a work-around, you can define your relationship first then set PropertyAccessMode on navigations.

**Closed** 2022-10-16 12:13 UTC
Labels: closed-duplicate
