### ISSUE TITLE
Incorrect UpdateData operations generated when using BoolToStringConverter with HasData

### ISSUE THREAD

**Issue by edwiles** [dotnet/efcore#13047] opened 2018-08-17 21:35 UTC
If BoolToStringConverter is used on a property together with HasData, adding migrations includes incorrect calls to migrationBuilder.UpdateData.

### Steps to reproduce

1. Create an entity with a boolean property:

```C#
public class TestEntity
{
    public int Id { get; set; }
    public bool MyTestBool { get; set; }
}
```

2. Add configuration, and apply this during OnModelCreating as usual:

```C#
modelBuilder.Entity<TestEntity>().Property(o => o.MyTestBool).HasConversion(new BoolToStringConverter("N", "Y"));
modelBuilder.Entity<TestEntity>().HasData(new TestEntity { Id = 1, MyTestBool = true });
```

3. Add two migrations:

```C#
dotnet ef migrations add InitialCreate
dotnet ef migrations add Update1
```

4. The generated migration file nnn_InitialCreate.cs inserts the data as expected:

```C#
            migrationBuilder.InsertData(
                table: "TestEntity",
                columns: new[] { "Id", "MyTestBool" },
                values: new object[] { 1, "Y" });
```

But the file nnn_Update1.cs contains spurious UpdateData operations - in fact, if this migration is reverted then the data is left in an incorrect state:

```C#
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "TestEntity",
                keyColumn: "Id",
                keyValue: 1,
                column: "MyTestBool",
                value: "Y");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "TestEntity",
                keyColumn: "Id",
                keyValue: 1,
                column: "MyTestBool",
                value: null);
        }
```

Note that this issue does not occur without the "HasConversion" line in step 2. It also does not occur when converting enums to strings rather than booleans (maybe because enums do not generate a ValueConverter clause in the migrations designer files?).

### Further technical details
EF Core version: 2.1.1
.NET SDK: 2.1.400
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Enterprise
IDE: Visual Studio 15.7.5

**Comment by ajcvickers** [comment] 2018-08-20 18:28
@bricelam @AndriySvyryd Is this a dupe?

**Comment by AndriySvyryd** [comment] 2018-08-21 19:18
Looks like a dupe of https://github.com/aspnet/EntityFrameworkCore/issues/12194

**Closed** 2022-10-16 13:26 UTC
Labels: closed-duplicate, customer-reported
