### ISSUE TITLE
How to use a custom function in the extended function "Select" of IQueryable

### ISSUE THREAD

**Issue by iran1024** [dotnet/efcore#28914] opened 2022-08-29 06:57 UTC
How to use a custom function in the extended function "Select" of IQueryable?
![image](https://user-images.githubusercontent.com/49387318/187141566-48ff0ca4-8a8e-4d58-ae29-a6f6c8a2d3e5.png)

EF Core version: 6.0
Database provider:Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 Preview

**Comment by ajcvickers** [comment] 2022-08-30 14:35
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-09-09 18:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-09-09 18:38 UTC
Labels: customer-reported
