### ISSUE TITLE
Not changing a required value type property with a default value still creates migration steps

### ISSUE THREAD

**Issue by poke** [dotnet/efcore#3125] opened 2015-09-14 16:11 UTC
When you have a property that is required and has a default value, then creating a migration yields an `AlterColumn` migration step that essentially changes nothing:

```
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.AlterColumn<bool>(
        name: "Test",
        table: "RequiredDefaultModel",
        isNullable: false,
        defaultValue: false);
}

protected override void Down(MigrationBuilder migrationBuilder)
{
    migrationBuilder.AlterColumn<bool>(
        name: "Test",
        table: "RequiredDefaultModel",
        isNullable: false,
        defaultValue: false);
}
```

The property for this example was configured like this:

```
entity.Property(o => o.Test).Required().HasDefaultValue(false);
```

I could produce the problem only with value-type default values. I tested `bool`, `int`, `char`, and `double`. The problem does not appear with strings. It however also appears if you have `string` as the property type but supply a value type to the `HasDefaultValue` call. So if `Test` was a string above, and you passed 1 to it, it would still produce the `AlterColumn` steps.

**Comment by bricelam** [comment] 2015-09-14 17:41
Dupe of #2802? (Resolved in Beta 8)

**Closed** 2022-10-16 09:09 UTC
