### ISSUE TITLE
EF Core Compiled Model cache expiration

### ISSUE THREAD

**Issue by sherazakbar50** [dotnet/efcore#25188] opened 2021-07-02 10:50 UTC
Hi, For the first cold query ef core compiles the entire model that usually have a high cost propotional to the model size and complexity. Can this cache be invalidated when there is no request to the server and no query is executed for 20 minutes or so using dbcontext?

**Comment by roji** [comment] 2021-07-03 06:07
@sherazakbar50 the point of the new compiled model feature coming in EF 6.0 (#1906) is to reduce the first startup time, when your application first loads; the compiled model is generated via an explicit command, typically performed at design-time (or CI). Since a model cannot typically be changed after startup, I'm not sure what sense there would be in rebuilding it after inactivity... Can you provide more context on exactly what you're looking for?

**Comment by ajcvickers** [comment] 2021-07-11 14:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:38 UTC
Labels: closed-no-further-action, customer-reported
