### ISSUE TITLE
Using OwnsOne in a TPH configuration produces invalid SQL

### ISSUE THREAD

**Issue by BahKoo** [dotnet/efcore#24077] opened 2021-02-06 21:37 UTC
**EF Core version:** 3.1.11
**Database provider:** Microsoft.EntityFrameworkCore.SqlServer
**Target framework:** .NET 4.8
**Operating system:** Windows 10 Pro (20H2)
**IDE:** Visual Studio 2019 16.8.3

I have uploaded an example project reproducing the problem here: [efcore-ownsone-issue.zip](https://github.com/dotnet/efcore/files/5937721/efcore-ownsone-issue.zip)

Here is my configuration:
```
public void Configure(EntityTypeBuilder<Task> builder)
{
	builder.HasKey(t => new { t.Id });

	builder.Property(t => t.Id);
	builder.Property(t => t.Type);
	builder.OwnsOne(t => t.Hours, hours => hours.Property(t => t.Value));

	builder.HasDiscriminator(e => e.Type)
		.HasValue<ActionTask>("Action");
}
```

This configuration produces the following SQL:
```
SELECT [t].[Id], [t].[Type], [t0].[TaskId], [t0].[Value]
FROM [Tasks] AS [t]
LEFT JOIN [Tasks1] AS [t0] ON [t].[Id] = [t0].[TaskId]
WHERE [t].[Type] = N'Action'
```

The exception raised is:
```
An exception occurred while iterating over the results of a query for context type 'TestConsole.Configuration.TaskContext'.
      Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Tasks1'.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
         at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
         at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
         at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
         at System.Data.Common.DbCommand.ExecuteReader()
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
      ClientConnectionId:df190c9f-f65b-40b6-8c7f-90859f17bb75
      Error Number:208,State:1,Class:16
```

After some extensive testing I have found that valid SQL can be produced depending on the FullName of the classes involved. In this example, the FullName of my classes are:
 - EfCoreRepro.Models.ActionTask **(Child)**
 - EfCoreRepro.Models.Hours **(Owned Entity)**
 - EfCoreRepro.Models.Task **(Parent)**
 
Invalid SQL is produced when the FullNames of the classes involved are alphabetically in this order:
 - Child < Owned Entity < Parent 
 
Changing either the namespaces or class names of the classes involved to change the alphabetical order of the FullNames
prevents this problem for happening.

This problem does not occur in EF core 5 but I can't upgrade as I'm targeting .NET Framework 4.8

**Comment by ajcvickers** [comment] 2021-02-08 18:36
@AndriySvyryd @smitpatel Verified that this fails on 3.1, but passes on 5.0.2. Do we have a dupe?

5.0.2 query:

sql
```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [t].[Id], [t].[Type], [t].[Hours_Value]
      FROM [Tasks] AS [t]
```

3.1 model:

```
Model: 
  EntityType: ActionTask Base: Task
  EntityType: Hours
    Properties: 
      TaskId (no field, string) Shadow Required PK FK AfterSave:Throw
      Value (double) Required
    Keys: 
      TaskId PK
    Foreign keys: 
      Hours {'TaskId'} -> Task {'Id'} Unique Ownership ToDependent: Hours
  EntityType: Task Abstract
    Properties: 
      Id (string) Required PK AfterSave:Throw
      Type (string) Required
    Navigations: 
      Hours (Hours) ToDependent Hours
    Keys: 
      Id PK
  ```

5.0 model:

```
Model: 
  EntityType: ActionTask Base: Task
  EntityType: Hours
    Properties: 
      TaskId (no field, string) Shadow Required PK FK AfterSave:Throw
      Value (double) Required
    Keys: 
      TaskId PK
    Foreign keys: 
      Hours {'TaskId'} -> Task {'Id'} Unique Ownership ToDependent: Hours Cascade
  EntityType: Task Abstract
    Properties: 
      Id (string) Required PK AfterSave:Throw
      Type (string) Required AfterSave:Throw
    Navigations: 
      Hours (Hours) ToDependent Hours
    Keys: 
      Id PK
```

**Comment by AndriySvyryd** [comment] 2021-02-08 18:54
Duplicate of https://github.com/dotnet/efcore/issues/21601

**Comment by BahKoo** [comment] 2021-02-08 20:25
@ajcvickers Does this mean the bug exists but there is no path forward to getting this working with the .NET Framework?

**Comment by ajcvickers** [comment] 2021-02-18 16:42
That is correct. We may choose to patch this in the future, but I don't think it currently [meets the bar](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning).

**Closed** 2022-10-16 19:22 UTC
Labels: closed-duplicate, customer-reported
