### ISSUE TITLE
How to compare, migrate, and update tables and entities using EF methods

### ISSUE THREAD

**Issue by laosandegudai** [dotnet/efcore#30941] opened 2023-05-21 07:27 UTC
Using ef tool, you can easily compare, transfer and update entities, which is very powerful. It also has extensive support for many databases in the market, but I hope to directly use these methods of EF in my application, such as obtaining all database table structures and obtaining all columns of tables. Unfortunately, I find that these defenses are private in EF, what should I do?

**Comment by roji** [comment] 2023-05-22 09:21
Duplicate of #13125

**Comment by roji** [comment] 2023-05-22 09:21
@laosandegudai see https://github.com/dotnet/efcore/issues/13125#issuecomment-416286819, there's a code sample that shows how to get a "database model", which exposes all the information about your schema.

**Comment by laosandegudai** [comment] 2023-05-22 09:43
Thanks,it is.

**Closed** 2023-05-22 09:44 UTC
Labels: customer-reported
