### ISSUE TITLE
Review MethodCallTranslators that match on method name instead of MethodInfo

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#7225] opened 2016-12-09 22:24 UTC
I noticed some of our translators are doing this. We should review whether it is safe - matching on name alone can yield false positives.

**Comment by smitpatel** [comment] 2017-04-17 22:14
Dupe of https://github.com/aspnet/EntityFramework/issues/8060

**Closed** 2022-10-16 10:46 UTC
Labels: closed-duplicate
