### ISSUE TITLE
 Ef Core 5 Owned on Entity with HiLo  Error

### ISSUE THREAD

**Issue by borisgr04** [dotnet/efcore#24679] opened 2021-04-17 16:28 UTC
Ef Core 5 Owned en Entity with HiLo  it 

Build started...
Build succeeded.
System.InvalidOperationException: 'Contacto.Id' and 'Direccion.ContactoId' are both mapped to column 'Id' in 'Contacto' but are configured with different value generation strategies.

In Ef Core 3 It works correctly.

Code

```C#
public class Context : DbContext 
    {
        public DbSet<Contacto> Contacto { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder.UseSqlServer("Data Source=.\\;Database=OwnedDataBaseTest;Trusted_Connection=True;MultipleActiveResultSets=true");

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Contacto>().HasKey(t => t.Id);
            modelBuilder.Entity<Contacto>().Property(p=>p.Id).UseHiLo("Contacto_hilo");
            modelBuilder.Entity<Contacto>().OwnsOne(p => p.Direccion);
            
        }
    }

    //[Owned]
    public class Direccion 
    {
        public string Calle { get; set; }
        public string Numero { get; set; }
    }
    public class Contacto
    {
        public int Id { get; set; }
        public string Telefono { get; set; }
        public string Nombre { get; set; }
        public Direccion Direccion { get; set; }
    }
```

EF Core version: 5
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system: Windows
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment] 2021-04-19 15:52
Looks like a duplicate of #20740. /cc @AndriySvyryd

**Closed** 2022-10-16 19:31 UTC
Labels: customer-reported
