### ISSUE TITLE
IdentityUserContext does not support multi-field unique constraint

### ISSUE THREAD

**Issue by whizkidwwe1217** [dotnet/efcore#10511] opened 2017-12-08 13:41 UTC
Issue: A unique constraint is hard-coded to the IdentityUserContext. This means that it does not allow me to implement a multi-tenant users. The current architecture is only good for multi-tenant apps where each tenant database is being hosted to different servers. But in the case of multi-tenancy where companies/tenants share a single database, it's not possible to do with the current version of Asp.net core Identity library.

![image](https://user-images.githubusercontent.com/1977391/33768112-aa87f080-dc5f-11e7-9dd0-733dc9b35471.png)
Expectation: 
I should be able to make the user (IdentityUser) unique per username (NormalizeName) per CompanyId (another field). This should be also the same with identity Roles.

Related issue: https://github.com/aspnet/Identity/issues/1518

**Comment by smitpatel** [comment] 2017-12-08 20:40
Duplicate of #10489

**Comment by ajcvickers** [comment] 2017-12-11 23:15
@whizkidwwe1217 Can you give some details on why you filed what seems to be the same issue again?

**Comment by whizkidwwe1217** [comment] 2017-12-11 23:53
@ajcvickers This is a duplicate. We can close this.

**Closed** 2022-10-16 12:02 UTC
