### ISSUE TITLE
SqlException when utilizing string interpolation in a call to ExecuteSqlCommand(Async)

### ISSUE THREAD

**Issue by NightWatchman** [dotnet/efcore#9699] opened 2017-09-05 22:54 UTC
### Title
*SqlException when utilizing string interpolation in a call to ExecuteSqlCommand(Async)*

### Functional impact
*Calls to ExecuteSqlCommand (both async and non-async versions) throw an unexpected SqlException when generating valid SQL via string interpolation.*

### Minimal repro steps
[EntityFrameworkBugDemo.zip](https://github.com/aspnet/EntityFrameworkCore/files/1279209/EntityFrameworkBugDemo.zip)
*I created a sample project demonstrating the issue. The Program.Main() method is pretty straightforward and includes two sections. One works fine, the other performs the same operation and is expected to result in the same thing happening, but it throws a SqlException instead. Comment out the appropriate section and run the application (dotnet run) to see the behavior.* 

### Expected result
*The SQL statement should execute successfully without throwing a SqlException.*  

### Actual result
*The SQL statement throws a SqlException stating `Incorrect syntax near '$p0'`*  

### Further technical details
*This same code was working fine previously, but just recently started failing. Probably when I moved from DotNetCore 1.1.1 to DotNetCore 2.0.0*
* Visual Studio v15.3.2
* Microsoft SQL Server 2012 (SP3-GDR) (KB4019092) - 11.0.6251.0 (X64) Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
* Windows 7 Enterprise, Service Pack 1
* DotNetCore 2.0.0

**Comment by ajcvickers** [comment] 2017-09-08 23:47
Duplicate of #9734

**Closed** 2022-10-16 11:47 UTC
Labels: closed-duplicate
