### ISSUE TITLE
InvalidOperationException with GroupBy()

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#30495] opened 2023-03-15 21:38 UTC
The following query works fine.

    var query = DbContext.Trucks
        .Where(t => t.Departure >= startMonth && t.Departure < endMonth)
        .Where(t => t.PurchaseOrder.Product.UnitOfMeasurement == UnitOfMeasurement.Pounds);
        .Select(t => new
        {
            t.Id,
            Departure = t.Departure!.Value.Month + "/" + t.Departure!.Value.Year % 100,
            Quantity = t.InboundQuantity + t.TruckRailcars.Sum(tr => tr.Quantity) + t.StorageTrucks.Sum(st => st.Quantity)
        })
        .ToListAsync();

But the following query (I added a `GroupBy()` clause) fails.

    var query = DbContext.Trucks
        .Where(t => t.Departure >= startMonth && t.Departure < endMonth)
        .Where(t => t.PurchaseOrder.Product.UnitOfMeasurement == UnitOfMeasurement.Pounds);
        .Select(t => new
        {
            t.Id,
            Departure = t.Departure!.Value.Month + "/" + t.Departure!.Value.Year % 100,
            Quantity = t.InboundQuantity + t.TruckRailcars.Sum(tr => tr.Quantity) + t.StorageTrucks.Sum(st => st.Quantity)
        })
        .GroupBy(t => t.Departure)
        .ToListAsync();

I know I can load all the rows and then group them on the client. But the first query returns about 44,000 rows while the second one would return 12. My code would be so much more efficient if I only needed to transfer 12 rows of data.

Is there no way to have SQL group this on the server?

Here's the error text.

```
The LINQ expression 'DbSet<Truck>()
    .Join(
        inner: DbSet<Facility>(), 
        outerKeySelector: t => EF.Property<int?>(t, "FacilityId"), 
        innerKeySelector: f => EF.Property<int?>(f, "Id"), 
        resultSelector: (o, i) => new TransparentIdentifier<Truck, Facility>(
            Outer = o, 
            Inner = i
        ))
    .Join(
        inner: DbSet<Company>(), 
        outerKeySelector: t => EF.Property<int?>(t.Inner, "CompanyId"), 
        innerKeySelector: c => EF.Property<int?>(c, "Id"), 
        resultSelector: (o, i) => new TransparentIdentifier<TransparentIdentifier<Truck, Facility>, Company>(
            Outer = o, 
            Inner = i
        ))
    .Where(t => t.Inner.CompanyCode == __companyCode_0)
    .Where(t => t.Outer.Outer.Departure >= __startMonth_1 && t.Outer.Outer.Departure < __endMonth_2)
    .Join(
        inner: DbSet<PurchaseOrder>(), 
        outerKeySelector: t => EF.Property<int?>(t.Outer.Outer, "PurchaseOrderId"), 
        innerKeySelector: p => EF.Property<int?>(p, "Id"), 
        resultSelector: (o, i) => new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<Truck, Facility>, Company>, PurchaseOrder>(
            Outer = o, 
            Inner = i
        ))
    .Join(
        inner: DbSet<Product>(), 
        outerKeySelector: t => EF.Property<int?>(t.Inner, "ProductId"), 
        innerKeySelector: p0 => EF.Property<int?>(p0, "Id"), 
        resultSelector: (o, i) => new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<Truck, Facility>, Company>, PurchaseOrder>, Product>(
            Outer = o, 
            Inner = i
        ))
    .Where(t => (int)t.Inner.UnitOfMeasurement == 0)
    .Where(t => __facilityIds_3
        .Contains(t.Outer.Outer.Outer.Outer.FacilityId))
    .GroupBy(
        keySelector: namelessParameter{0} => (object)namelessParameter{0}.Outer.Outer.Outer.Outer.Departure.Value.Month + "/" + (object)(namelessParameter{0}.Outer.Outer.Outer.Outer.Departure.Value.Year % 100), 
        elementSelector: e => new { 
            Id = e.Outer.Outer.Outer.Outer.Id, 
            Departure = (object)e.Outer.Outer.Outer.Outer.Departure.Value.Month + "/" + (object)(e.Outer.Outer.Outer.Outer.Departure.Value.Year % 100), 
            Quantity = e.Outer.Outer.Outer.Outer.InboundQuantity + DbSet<TruckRailcar>()
                .Where(t0 => EF.Property<int?>(e.Outer.Outer.Outer.Outer, "Id") != null && object.Equals(
                    objA: (object)EF.Property<int?>(e.Outer.Outer.Outer.Outer, "Id"), 
                    objB: (object)EF.Property<int?>(t0, "TruckId")))
                .Sum(t0 => t0.Quantity) + DbSet<StorageTruck>()
                .Where(s => EF.Property<int?>(e.Outer.Outer.Outer.Outer, "Id") != null && object.Equals(
                    objA: (object)EF.Property<int?>(e.Outer.Outer.Outer.Outer, "Id"), 
                    objB: (object)EF.Property<int?>(s, "TruckId")))
                .Sum(s => s.Quantity)
         })' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

### Include provider and version information

EF Core version: 7.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.5.1

**Comment by roji** [comment] 2023-03-15 21:47
> I know I can load all the rows and then group them on the client. But the first query returns about 44,000 rows while the second one would return 12. My code would be so much more efficient if I only needed to transfer 12 rows of data.

Why should adding a GroupBy at the end reduce the number of rows fetched from the server?

**Comment by roji** [comment] 2023-03-16 17:33
@SoftCircuits GroupBy doesn't reduce the *data* being processed/handled in any way.. Disregarding database and SQL for a second and thinking about in-memory Enumerable GroupBy, doing GroupBy over 44k things may indeed return 12 groups, but each one of those groups would be huge; the total number of original instances is still 44k. As an operator, GroupBy only groups data, and doesn't reduce it in any way.

In SQL, a GROUP BY clause requires an aggregate function to "reduce" the groups. For example, you can do:

```c#
SELECT [b].[OwnerId], COUNT(*)
FROM [Blogs] AS [b] 
GROUP BY [b].[OwnerId]
```

... which returns all blog owners, with a the number of blogs owned for each owner. Note that the aggregate function COUNT(*) is used to "reduce" each owner's grouped blogs to its count. This indeed reduces data considerably, and is explained in [our docs](https://learn.microsoft.com/en-us/ef/core/querying/complex-query-operators#groupby).

Prior to EF Core 7.0, you had to have a select with an aggregate function after a LINQ GroupBy. EF Core 7.0 added the possibility to have GroupBy as the final query operator ([release note](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#groupby-as-final-operator)), which implies downloading all the data from the server and grouping it in the client (again, since SQL GROUP BY cannot be used alone in this way).

Is that really is your intention, i.e. to download the 44,000 rows to the client, and group them there?

**Comment by SoftCircuits** [comment] 2023-03-16 17:52
@roji Sorry. I don't know if you saw my last post. I was acknowledging your point--and my error.

> Note that the aggregate function COUNT(*) is used to "reduce" each owner's grouped blogs to its count. This indeed reduces data considerably, and is explained in [our docs](https://learn.microsoft.com/en-us/ef/core/querying/complex-query-operators#groupby).

Exactly. It's the aggregate values that I need. My previous post includes the following query.

    var results = await query
        .GroupBy(
            t => new { t.Departure!.Value.Year, t.Departure!.Value.Month },
            t => new
            {
                Departure = t.Departure!.Value,
                Quantity = t.InboundQuantity + t.TruckRailcars.Sum(tr => tr.Quantity) + t.StorageTrucks.Sum(st => st.Quantity)
            })
        .Select(g => new { Date = g.Key, Quantity = g.Sum(t => t.Quantity) })
        .ToListAsync();

Given the final `Select()`, I expect this query to only return 12 rows.

But it fails with error I showed in my previous post. And I've yet to find a workaround that works that does not involve downloading all 44,000 rows.

**Comment by SoftCircuits** [comment] 2023-03-16 18:10
@roji Thanks. You mean like this?

    var results = await query
        .GroupBy(t => new { t.Departure!.Value.Year, t.Departure!.Value.Month })
        .Select(g => new
        {
            Date = g.Key,
            Quantity = g.Sum(t => t.InboundQuantity + t.TruckRailcars.Sum(tr => tr.Quantity) + t.StorageTrucks.Sum(st => st.Quantity))
        })
        .ToListAsync();

Unfortunately, this fails too.

> Microsoft.Data.SqlClient.SqlException: 'Cannot perform an aggregate function on an expression containing an aggregate or a subquery.  
Cannot perform an aggregate function on an expression containing an aggregate or a subquery.  
Cannot perform an aggregate function on an expression containing an aggregate or a subquery.  
Cannot perform an aggregate function on an expression containing an aggregate or a subquery.'  

I think it's related to the complexity of `g.Sum(t => t.InboundQuantity + t.TruckRailcars.Sum(tr => tr.Quantity) + t.StorageTrucks.Sum(st => st.Quantity))`. These subqueries appear to be too much.

I understand there are limitations here. But after trying numerous variations, I'm kind of stuck downloading all 44,000 rows, which would be terrible.

**Comment by SoftCircuits** [comment] 2023-03-16 18:57
@roji With some help, this is the workaround I came up with. I suspect this isn't a very efficient query, but more efficient that downloading all 44,000 rows and grouping them on the client.

I wonder if there's room for EF improvements for my example.

    var inbound =
        from t in query
        group t by new { t.Departure!.Value.Year, t.Departure!.Value.Month } into g
        select new
        {
            g.Key,
            Quantity = g.Sum(x => x.InboundQuantity)
        };

    var truckRailcars =
        from t in query
        from tr in t.TruckRailcars
        group tr by new { t.Departure!.Value.Year, t.Departure!.Value.Month } into g
        select new
        {
            g.Key,
            Quantity = g.Sum(x => x.Quantity)
        };

    var storageTrucks =
        from t in query
        from st in t.StorageTrucks
        group st by new { t.Departure!.Value.Year, t.Departure!.Value.Month } into g
        select new
        {
            g.Key,
            Quantity = g.Sum(x => x.Quantity)
        };

    var resultQuery =
        from q in inbound.Concat(truckRailcars).Concat(storageTrucks)
        group q by q.Key into g
        select new
        {
            Date = g.Key,
            Quantity = g.Sum(x => x.Quantity)
        };

    var results = await resultQuery
        .ToListAsync();

**Comment by roji** [comment] 2023-03-16 20:10
I'll need a minimal runnable code repro here, to have your model etc.

**Comment by SoftCircuits** [comment] 2023-03-16 21:48
@roji Please let me know if you need anything else.

    var query = DbContext.Trucks
        .Where(t => t.Facility.Company.CompanyCode == companyCode)
        .Where(t => t.Departure >= startMonth && t.Departure < endMonth)
        .Where(t => t.PurchaseOrder.Product.UnitOfMeasurement == UnitOfMeasurement.Pounds);

    if (customerId.HasValue)
        query = query.Where(t => t.PurchaseOrder.CustomerId == customerId);

    IEnumerable<int> facilityIds = await GetUserFacilityIdsAsync(facilityId);
    query = query.Where(t => facilityIds.Contains(t.FacilityId));

    var results = await query
        .GroupBy(t => new { t.Departure!.Value.Year, t.Departure!.Value.Month })
        .Select(g => new
        {
            Date = g.Key,
            Quantity = g.Sum(t => t.InboundQuantity + t.TruckRailcars.Sum(tr => tr.Quantity) + t.StorageTrucks.Sum(st => st.Quantity))
        })
        .ToListAsync();

[Models.zip](https://github.com/dotnet/efcore/files/10996162/Models.zip)

**Comment by roji** [comment] 2023-03-21 11:23
@SoftCircuits sory, that's not a minima, runnable repro - your model seems to reference various missing types (e.g. Company references Customer, Facility references Railcar, Track...). I can spend time trying to piece together something runnable from your code, but you're in a better position to do that, and I simply don't have the extra time to spend on it.

Ideally, I need a simple, one-file console program that throws your error when it's executed, and doesn't contains **any** types or code that isn't directly needed to reproduce the error. Any extras make it more confusing and increase the time needed to investigate.

**Comment by ajcvickers** [comment] 2023-04-05 17:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-04-05 17:17 UTC
Labels: customer-reported
