### ISSUE TITLE
Query: detect cycles in defining queries and query filters

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#17322] opened 2019-08-20 23:59 UTC
Currently we only handle self reference in the defining query and/or query filter. We don't detect cycles involving multiple entities, as well as cycles that happen because navigation accesses.

**Comment by AndriySvyryd** [comment] 2019-08-21 02:01
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/17042

**Closed** 2022-10-16 14:37 UTC
Labels: closed-duplicate
