### ISSUE TITLE
Visual Studio 2022 It is not installed Microsoft.EntityFrameworkCore.SqlServer

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#32959] opened 2024-01-30 10:21 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-It-is-not-installed-M/10570123)._

---
[severity:Other]
When downloading Microsoft.EntityFrameworkCore.SQLServer - errors pop up, it is impossible to extract data from the source. I have tried all versions of the product, none are installed

---
#### Feedback Bot on 1/24/2024, 08:14 AM: 

(private comment, text removed)
#### павел дериглазов on 1/24/2024, 08:55 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2024-02-14 14:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-02-14 14:01 UTC
