### ISSUE TITLE
Unittesting with TestServer and InMemoryDatabase broken since upgrade to netcore 2.0

### ISSUE THREAD

**Issue by sambernaerdt** [dotnet/efcore#9657] opened 2017-08-31 14:19 UTC
(I tried following all the guidelines out there and searched everywhere, but I am stuck really stuck. I guess it's actually an issue introduced by netcore 2.0)

### Problem

For my integration tests I test the endpoints by making a Post, Get, ... request through the HttpClient available in the TestServer. Typically, it starts with creating a new DbContext for a named inMemoryDatabase and arranging the data in that context. Then, the HttpClient does the request and the result is evaluated. This was all working fine in netcore 1.0, but broke after upgrading to netcore 2.0.

I think it's a general issue where the DbContext retrieved through the ServiceProvider is different than the one created with the OptionsBuilder. Although they both are configured to use the same name for the InMemoryDatabase. (This was working fine in netcore 1.0)

### Steps to reproduce

Create a TestStartup class that overrides the normal startup class and uses an InMemoryDatabase with a certain name instead of the regular database context.

```
public void ConfigureServices(IServiceCollection services)
{
         [...]
         services.AddDbContext<ApplicationDbContext>(options => options.UseInMemoryDatabase("UniqueNameForThisTest"));
}
```

Create a Test. In the Test class, create the objects needed for testing with a TestServer
```   
public TestInMemoryDb()
{
            _server = new TestServer(new WebHostBuilder()
                    .UseStartup<TestStartup>());
            _client = _server.CreateClient();
            _serviceProvider = _server.Host.Services;
}
```

Also, add a method to generate a fresh context with the same InMemoryDatabase
```   
protected ApplicationDbContext GetFreshContext()
{
            var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
            optionsBuilder.UseInMemoryDatabase("UniqueNameForThisTest");
            return new ApplicationDbContext(optionsBuilder.Options);
}
```  

Now, the following test will fail:
```  
[Fact]
public void ShouldExistInRepo()
{
            var person = new Person()
            {
                Id = 1,
                FirstName = "Jack",
                LastName = "Smith"
            };

            // Fresh context
            using (var context = GetFreshContext())
            {
                context.DbSetPerson.Add(person);
                context.SaveChanges();
            }

            // Repository from service provider
            var repository = GetService<IRepositoryPerson>();
            var person = repository.Get(1);
            Assert.NotNull(person);
}
```  

When looking at the RepositoryPerson class's Get method, it would show an empty _context.DbSetPerson.

### Further technical details
EF Core version: netcoreapp2.0
Other packages:
"Microsoft.AspNetCore.TestHost" Version="2.0.0"
"Microsoft.EntityFrameworkCore.InMemory" Version="2.0.0" 
"Microsoft.NET.Test.Sdk" Version="15.3.0" 
"xunit" Version="2.2.0" 
 "xunit.runner.visualstudio" Version="2.2.0"

**Comment by ajcvickers** [comment] 2017-08-31 16:48
Duplicate of #9613

**Comment by ajcvickers** [comment] 2017-09-12 19:00
Hi @sambernaerdt. We are gathering information on the use of EF Core pre-release builds. You reported this issue shortly after the release of 2.0.0 RTM. It would be really helpful if you could let us know:

- Did you consider testing your code against the pre-release builds?
- Was there anything blocking you from using pre-release builds?
- What do you think could make it easier for you to use pre-release builds in the future?

Thanks in advance for any feedback. Hopefully this will help us to increase the value of pre-release builds going forward.

**Comment by sambernaerdt** [comment] 2017-09-13 06:42
Hi Arthur

* **Did you consider testing your code against the pre-release builds?**
Not really. As long as there are no features that I really need, I'd prefer waiting for a stable release build. Currently, I am able to wait for the next stable release, since the reported issue only affects my unit testing, which means I am able to continue developing.

* **Was there anything blocking you from using pre-release builds?**
Yes. I'm working with a MySQL database, so I need a third party library for the connection with the database. Currently, that is Pomelo.EntityFrameworkCore.Mysql. Since they need some time to update the library, I'd rather wait a bit to update EFCore. Otherwise, chances are that there'll be some issues with that library regarding compatibility with the efcore version.
    
* **What do you think could make it easier for you to use pre-release builds in the future?**
  Available through NuGet
  Information about MySql connectors and their compatibility with the builds

Kind regards
Sam

**Comment by ajcvickers** [comment] 2017-09-15 21:40
@sambernaerdt Thanks for the feedback; much appreciated.

**Closed** 2022-10-16 11:20 UTC
