### ISSUE TITLE
NotSupportedException missing for different contexts

### ISSUE THREAD

**Issue by mguinness** [dotnet/efcore#8952] opened 2017-06-23 00:32 UTC
In previous versions of EF when using different contexts within a LINQ query, the following exception would be shown:

`System.NotSupportedException: The specified LINQ expression contains references to queries that are associated with different contexts.`

However with EF Core you now get the following exception:

```
Exception message: System.ArgumentNullException : Value cannot be null.
Stack trace:
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.SqliteMetadataExtensions.Sqlite(IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitEntityQueryable(Type elementType)
   at System.Linq.Expressions.ConstantExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.CompileJoinClauseInnerSequenceExpression(JoinClause joinClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.<>c__DisplayClass69_0.<VisitJoinClause>b__0()
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index, Action baseVisitAction, MethodInfo operatorToFlatten, Boolean groupJoin)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConsoleApp1.Program.Main(String[] args) in C:\Projects\ConsoleApp1\Program.cs:line 28
```

### Steps to reproduce
The example below from [ConsoleApp1](https://github.com/aspnet/EntityFramework/files/1096474/ConsoleApp1.zip) raises the exception.  

```c#
var ctx = new Models.northwindEFContext();
var ctx2 = new Models2.northwindEFContext();

var data =
    from t in ctx.Territories
    join r in ctx2.Regions on
    t.RegionId equals r.RegionId
    select new { t, r };
```

Although not realistic code, it demonstrates that ArgumentNullException is raised which is not useful.  If NotSupportedException was raised instead it would be more meaningful to the developer.

### Further technical details
EF Core version: 1.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by smitpatel** [comment] 2017-06-23 01:00
This reproduces but the reason for null exception is we are unable to find the entity type for given clr type. Looking at both the models, they do have all the types so it should not happen. There seem to be some bug in there.

This also happens for 2.0.0-preview1

**Comment by ajcvickers** [comment] 2018-05-17 21:05
Duplicate of #11101

**Closed** 2022-10-16 11:09 UTC
Labels: type-bug, closed-duplicate
