### ISSUE TITLE
Multiple 'Count' inside a 'Select' causes properties to interfere with each other

### ISSUE THREAD

**Issue by levitatejay** [dotnet/efcore#5264] opened 2016-05-04 04:50 UTC
I'm using RC1

The following code:

`_ctx.Products
                .Select(p => new
                {
                    Id = p.Id,
                    CustomerCount = p.LicenceProducts.Count,
                    UserCount = p.ProductUsers.Count
                })
                .ToList();`

Returns a list where each CustomerCount and UserCount property has the same value.

The results change based on the order of the properties in the select... e.g. If the CustomerCount is last in the select then all UserCount props are set to the same as CustomerCount and vice versa.

**Comment by smitpatel** [comment] 2016-05-04 18:25
dupe of #3616

**Closed** 2022-10-16 09:39 UTC
