### ISSUE TITLE
Database is deleted after saving changes when using the Sqlite provider 'in-memory' mode

### ISSUE THREAD

**Issue by arnaudauroux** [dotnet/efcore#7171] opened 2016-12-01 11:26 UTC
### Steps to reproduce
The complete reproduction step solution is available here : https://github.com/arnaudauroux/dotnetcore-sqlite110-issue

### The issue
The SaveChanges method deletes the database when using the 'in-memory' mode after a call to the SaveChanges method. This issue occured in version 1.1.0.

### Further technical details

EF Core version: 1.1.0
EF Core Sqlite version: 1.1.0
DotNetCore SDK version: 1.0.0-preview2-1-003177
Operating system: Win10
Visual Studio version: VS 2015

**Comment by smitpatel** [comment] 2016-12-03 14:52
possible dupe of #6968

**Comment by rowanmiller** [comment] 2016-12-07 19:58
Closing as a dupe of #6968 (SaveChanges is closing the connection when it shouldn't be)

**Comment by arnaudauroux** [comment] 2016-12-09 10:24
Yes thanks, we have fixed the issue by opening the connection before passing it to Sqlite ;)

**Closed** 2022-10-16 10:45 UTC
Labels: closed-duplicate
