### ISSUE TITLE
ORA-00972: identity is too long

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/efcore#10212] opened 2017-11-03 13:49 UTC
When using EF Core with Devart EFCore provider for Oracle; EF 1.1.3 is generated SQL that is invalid for the provider; resulting in a exception from the database.  ORA-00972: identity is too long

**Comment by ralmsdeveloper** [comment] 2017-11-03 14:43
Hi @grahamehorner 
Does any field have more than 30 characters?

**Comment by smitpatel** [comment] 2017-11-03 15:48
Duplicate of #8255

**Comment by grahamehorner** [comment] 2017-11-04 11:51
@ralmsdeveloper the database has been designed by the Oracle DBAs and conforms to Oracle best practices the issues seems to be with nested querying when using EF core, and unfortunately modifying the model to shorten field names and/or tables that map to the database is not a option for use. 😢

**Comment by ralmsdeveloper** [comment] 2017-11-04 12:20
Could you post the class being consumed? the structure of your Context to try to help you?

**Comment by grahamehorner** [comment] 2017-11-06 21:49
FYI , the same query with the same Oracle database works when using ef core 2.0? will this be fixed in previous ef core versions?

**Comment by ajcvickers** [comment] 2017-11-06 22:28
@grahamehorner We have no plans at this time to fix this in any earlier versions.

**Comment by grahamehorner** [comment] 2017-11-07 07:13
IMHO not fixing this in previous versions force projects like OData WebApi to target .NET 2.0 even when/if EF Core is not used, as when using EF Core in the earlier release this bug would surface 😭

**Comment by afonsoft** [comment] 2022-03-07 12:34
Hi I found the solution for it at the oracle site and it is as below :

// Limit 30 char length as per Oracle

modelBuilder.Model.Relational().MaxIdentifierLength = 30;

All you need to do write this code where you are building model and it will trimmed down all your automatically created relation in to 30 chars. It will keep uniqueness in case of duplicity after trimming.

**Closed** 2022-10-16 11:56 UTC
