### ISSUE TITLE
Identity seed kept across inMemory databases

### ISSUE THREAD

**Issue by joamla96** [dotnet/efcore#13313] opened 2018-09-13 07:37 UTC
Hi.

I'm setting up my test framework to use an in memory database for the different scenarios. Each test uses a "unique" database, and each step of the test use a different context for entity framework.

Problem is, even if the tests use different "in memory" databases, and different contexts from entity framework, the identity in the database seems to increase.

### Steps to reproduce
Created 2 unit tests like so:
```
[Test]
public async Task CanGetAllFromRepository()
{
    var options = new DbContextOptionsBuilder<MyContext>()
        .UseInMemoryDatabase(databaseName: "CanGetAllFromRepository").Options;
    var testa = new User();
    var testb = new User();
    var testc = new User();

    using (var context = new MyContext(options))
    {
        await context.Users.AddAsync(testa);
        await context.Users.AddAsync(testb);
        await context.Users.AddAsync(testc);
        await context.SaveChangesAsync();
    }

    using (var context = new MyContext(options))
    {
        var repo = new UserRepository(context);
        var all = await repo.GetAllAsync();
        Assert.IsTrue(all.Count == 3);
    }
}

[Test]
public async Task CanGetByIdFromRepository()
{
    var options = new DbContextOptionsBuilder<MyContext>()
        .UseInMemoryDatabase(databaseName: "CanGetByIdFromRepository").Options;
    var testa = new User();
    var testb = new User();
    var testc = new User();

    using (var context = new SalesPortalContext(options))
    {
        await context.User.AddAsync(testa);
        await context.User.AddAsync(testb);
        await context.User.AddAsync(testc);
        await context.SaveChangesAsync();
    }

    using (var context = new MyContext(options))
    {
        var repo = new UserRepository(context);
        var usera = await repo.GetByIdAsync(1);
        var userb = await repo.GetByIdAsync(2);
        var userc = await repo.GetByIdAsync(3);

        Assert.IsNotNull(usera);
        Assert.IsNotNull(userb);
        Assert.IsNotNull(userc);
    }
}
```

When run individually, each test passes.
When run together, second test fails.

If i run the tests 1 by 1, its not an issue, but running them all together; then for the 2nd unit test the identity set ids of the users start 4, 5, 6. (When run individually, its 1, 2, 3 as expected).

### Further technical details
EF Core version: v2.1.1
Database Provider: Microsoft.EntityFrameworkCore.InMemory (v2.1.3)
Operating system: Windows 10 Enterprise 
IDE: Visual Studio 2017 15.8.3

**Comment by ajcvickers** [comment] 2018-09-13 15:17
Duplicate of #6872

**Closed** 2022-10-16 13:30 UTC
Labels: customer-reported
