### ISSUE TITLE
Scaffold single alternate key as a primary key in the EF model

### ISSUE THREAD

**Issue by slavanap** [dotnet/efcore#24369] opened 2021-03-10 16:13 UTC
`NullReferenceException` is thrown at this line:
https://github.com/dotnet/efcore/blob/v3.1.13/src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs#L2968-L2969
on an attempt to call `.HasOne` on entity with `.HasNoKey()`

`HasKeyInternal` method returns `null`, thus index `.Metadata` fails.
It happens because this expression returns `false`:
https://github.com/dotnet/efcore/blob/v3.1.13/src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs#L200-L201

Affected versions: 3.1

Demo:
```
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace ConsoleApp1 {

    public partial class Table1 {
        public string User { get; set; }

        public decimal FileId { get; set; }
        public decimal FileRowNum { get; set; }
    }

    public partial class Table2 {
        public decimal FileId { get; set; }
        public decimal RowNum { get; set; }
        public string ErrorDescription { get; set; }
        public virtual Table1 Table1Record { get; set; }
    }

    class TestContext : DbContext {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
            optionsBuilder.UseInMemoryDatabase("test");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder) {
            modelBuilder.Entity<Table1>(entity => {
                entity.HasNoKey();

            });

            modelBuilder.Entity<Table2>(entity => {
                entity.HasNoKey();

                var temp = entity.HasOne(d => d.Table1Record); // < exception here

                temp
                    .WithMany()
                    .HasPrincipalKey(p => new { p.FileId, p.FileRowNum })
                    .HasForeignKey(d => new { d.FileId, d.RowNum })
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });
        }
    }


    class Program {
        static void Main(string[] args) {
            new TestContext().Set<Table2>().Single(); // force OnModelCreating
        }
    }
}
```

P.S. The aforementioned data model is a small part of data model scaffolded from a database (database first approach).

**Comment by ajcvickers** [comment] 2021-03-10 23:27
@slavanap We should not be scaffolding this code. Can you post the schema for Table1 and Table2, including constraints?

**Comment by slavanap** [comment] 2021-03-11 07:06
@ajcvickers is there a simple way to print `DatabaseModel` object?
The database I scaffold with `Oracle.EntityFrameworkCore` is huge, I'll do my best to filter its DataModel manually.

**Comment by roji** [comment] 2021-03-11 08:10
@slavanap ideally we need the actual SQL schema, rather than a dump of DatabaseModel (which is already a processed EF Core representation). You can extract the schemas for the tables which are relevant here, rather than the entire database schema.

**Comment by slavanap** [comment] 2021-03-11 17:06
This is Oracle. `Oracle.EntityFrameworkCore` package https://www.nuget.org/packages/Oracle.EntityFrameworkCore/3.19.80
```
CREATE TABLE FILE_INCORRECT_ERR 
(
  FILE_ID NUMBER(10, 0) NOT NULL 
, ROW_NUM NUMBER(5, 0) NOT NULL 
, ERR_DSC VARCHAR2(512 BYTE) NOT NULL 
) 
;

CREATE TABLE FILE_INCORRECT_INFO
(
  LAST_NM VARCHAR2(32 BYTE) 
, FILE_ID NUMBER(10, 0) NOT NULL 
, FILE_ROW_NUM NUMBER(5, 0) NOT NULL
, CONSTRAINT fk_column
    FOREIGN KEY (FILE_ID, FILE_ROW_NUM)
    REFERENCES FILE_INCORRECT_ERR (FILE_ID, ROW_NUM)
) 
;
```

**Comment by slavanap** [comment] 2021-03-11 17:26
Notice, in package version 5.x the exception is thrown on scaffolding:
```System.InvalidOperationException: 'The key {'FileId', 'FileRowNum'} cannot be added to keyless type 'table1'```
Affected versions are 3.1.x, as mentioned in the first post.

**Comment by ajcvickers** [comment] 2021-03-16 18:40
Note from triage: when reverse engineering a database, if we find a foreign key constraint that references fields of a principal table where that table does not have a primary key, then we should make a primary key for the corresponding entity type in the EF model. If this happens more than once, then we may want to warn.

**Comment by AndriySvyryd** [comment] 2022-01-14 18:13
Duplicate of #19918

**Closed** 2022-10-16 19:27 UTC
Labels: customer-reported
