### ISSUE TITLE
Proposal: Allow ctor mapping of OwnedTypes.

### ISSUE THREAD

**Issue by glatzert** [dotnet/efcore#22637] opened 2020-09-21 12:33 UTC
I quite like the ctor mapping mechanics for entity types and tried to use the same thing for an ownedType being part of my entity.
Unfortunately mapping the owned type via constructors of the entity is not supported.

Please consider allowing the owned type in a ctor of an entity, e.g:
```
public class MyOwned { ... }

public class MyEntity {
  public MyEnttiy(MyOwned owned) { ... }
}
```

**Comment by ajcvickers** [comment] 2020-09-21 14:00
Duplicate of #12078

**Closed** 2022-10-16 18:41 UTC
Labels: customer-reported
