### ISSUE TITLE
Better handling of default value in inherited Base entity in DbContext

### ISSUE THREAD

**Issue by SidusCaelum** [dotnet/efcore#27341] opened 2022-02-02 05:46 UTC
Is there a better way to handle a base entity inheritance in a context class for shared properties? Specifically if you have a base with createdAt and updatedAt, I find that I have to manually add a HasDefaultValueSql for both properties on each table. I am using ef6 and npgsql for my db connection. 

.NET 6
EF Core version 6.0.1
npgsql 6.0.3

**DbContext.cs**
```C#
    protected override void OnModelCreating(ModelBuilder mb)
    {
        mb.Entity<User>()
            .Property(p => p.CreatedAt)
            .HasDefaultValueSql("now()");
        mb.Entity<User>()
            .Property(p => p.UpdatedAt)
            .HasDefaultValueSql("now()");
        mb.Entity<Workout>()
            .Property(p => p.CreatedAt)
            .HasDefaultValueSql("now()");
        mb.Entity<Workout>()
            .Property(p => p.UpdatedAt)
            .HasDefaultValueSql("now()");
        mb.Entity<Exercise>()
            .Property(p => p.CreatedAt)
            .HasDefaultValueSql("now()");
        mb.Entity<Exercise>()
            .Property(p => p.UpdatedAt)
            .HasDefaultValueSql("now()");
        mb.Entity<Set>()
            .Property(p => p.CreatedAt)
            .HasDefaultValueSql("now()");
        mb.Entity<Set>()
            .Property(p => p.UpdatedAt)
            .HasDefaultValueSql("now()");

        base.OnModelCreating(mb);
    }
```

**Base.cs**
```C#
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SudorNET.Db.Models;

public abstract record Base
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Key]
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}
```

**Comment by ajcvickers** [comment] 2022-02-02 17:08
@SidusCaelum Duplicate of #6787. Make sure to vote (👍) for that issue.

**Closed** 2022-10-16 20:24 UTC
Labels: closed-duplicate, customer-reported
