### ISSUE TITLE
Getting error "System.InvalidOperationException: Cannot scaffold C# literals of type 'System.Reflection.NullabilityInfoContext" in EF Core 8.0.4/8.0.8

### ISSUE THREAD

**Issue by plondhe-mdsol** [dotnet/efcore#34698] opened 2024-09-17 16:09 UTC
## I am getting scaffold related error while creating migration file in EF Core. 

Below add migration script trying in dot net tool and throws below error.
 `dotnet ef --startup-project . migrations add 20240917_add_column`

### Include stack traces

```
System.InvalidOperationException: Cannot scaffold C# literals of type 'System.Reflection.NullabilityInfoContext'. The provider should implement CoreTypeMapping.GenerateCodeLiteral to support using it at design time.
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.UnknownLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.<Fragment>g__AppendMethodCall|55_0(IMethodCallCodeFragment current, <>c__DisplayClass55_0&)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Fragment(IMethodCallCodeFragment fragment, Int32 indent)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateAnnotations(String builderName, IAnnotatable annotatable, IndentedStringBuilder stringBuilder, Dictionary`2 annotations, Boolean inChainedCall, Boolean leadingNewline, MethodInfo hasAnnotationMethodInfo)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.Generate(String modelBuilderName, IModel model, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMetadata(String migrationNamespace, Type contextType, String migrationName, String migrationId, IModel targetModel)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Cannot scaffold C# literals of type 'System.Reflection.NullabilityInfoContext'. The provider should implement CoreTypeMapping.GenerateCodeLiteral to support using it at design time.
```

### Include provider and version information

EF Core version:
Database provider: (e.g. Npgsql.EntityFrameworkCore.PostgreSQL 8.0.4) 
Microsoft.EntityFrameworkCore.Design 8.0.8 also tried with 8.0.4
Microsoft.EntityFrameworkCore.Proxies 8.0.8 also tried with 8.0.4 
Target framework: (e.g. .NET 8.0)
Operating system:
IDE: (Visual Studio 2022 17.8.4)

Any help really appreciated. Thanks!

**Comment by roji** [comment] 2024-09-17 16:12
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by plondhe-mdsol** [comment] 2024-09-17 16:19
Hello @roji 
I am not sure what code I need to post because I am just adding new migration file but recently we upgraded .net from 6.0 to 8.0 along with EF core.
I have added a new property in one of the existing entity and I am trying to create migration file using below command 
`dotnet ef --startup-project . migrations add 20240917_add_column` but somehow it is failing with above mentioned error.

**Comment by zotanmew** [comment] 2024-09-20 19:07
I'm experiencing the same issue for our project when updating EF to .NET 9 RC1 (No such errors on .NET 8). I'm so far struggling to reproduce it in an isolated codebase, but I'll keep trying.

**Comment by zotanmew** [comment] 2024-09-28 00:10
In my case I traced the issue to a field in an entity that should have been a property. For some reason, .NET 8.0 doesn't complain, while .NET 9.0 complains with this quite unhelpful error message.

**Comment by roji** [comment] 2024-09-28 06:13
Folks, I understand and I don't doubt that there's some problem here, but we really do need a repro in order to investigate and fix this. I'll go ahead and close this issue as we don't have one, but if one is posted here we can reopen.

**Closed by roji** 2024-09-28 06:13 UTC
Labels: customer-reported

**Comment by pjenei** [comment] 2024-10-14 17:20
We've experienced the same issue while updating EF 5 to EF 8. I've tried hard to reproduce it in a sample project with no luck.
A few information about the project which may help others to narrow down the problem:

- The environment is almost the same as in the first comment, except we use Microsoft.EntityFrameworkCore.SqlServer as database provider.
- Our entity classes are in a project with `<Nullable>enable</Nullable>` in the csproj file.
- The context class is in another project without `<Nullable>enable</Nullable>` in the csproj file.
- After changing the target framework from 5 to 8 in all projects in the solution, I can add a migration.
- After updating EF 5.* packages to 6.* packages, I still can add a migration.
- After updating EF 6.* packages to 7.* (or 8.*) packages, I can't add a migration, I get the same error as in the first comment.

What helped in our case: we added a `modelBuilder.Entity<EntityTypeName>().HasNoKey().ToView(null);` line for each table-valued-function that was configured in our context class. At runtime, all functions worked correctly with EF 7 and EF 8, but at design-time, the tooling needed these additional configuration lines to be able to create the database snapshot. EF 5 and EF 6 tooling worked well without these.
I hope this helps somebody.

**Comment by Red-F** [comment] 2024-10-27 15:57
It looks like having this in the model
```csharp
    // This "defensive copy" pattern prevents unwanted modifications to elements of the Lists via casting 
    public IReadOnlyCollection<string> Uids => _uids.ToList();
    private List<string> _uids = [];
```
and this in the configuration:
```csharp
         builder.Property(x => x.Uids).HasField("_uids");
```
will cause the above exception when running 'dotnet ef migrations add myMigration'.

The database is created (and usable) without issues when directly doing:

```csharp
        _context.Database.EnsureDeleted();
        _context.Database.EnsureCreated();
```

**Comment by SA-khan** [comment] 2024-11-11 10:59
I have the same issue in .NET rc2

**Comment by roji** [comment] 2024-11-25 04:48
Duplicate of #34996

**Comment by roji** [comment] 2024-11-25 04:51
Duplicate of #34996

**Comment by hugh-maaskant** [comment] 2024-11-30 17:20
Don't know if this helps but I got the same error when adding (the initial) migration after upgrading from .NET 8 / EF Core 8 to .NET 9 / EF Core 9.

- I have no `ReadOnlyCollection<string>` or similar in my model.
- I am using PostgreSQL with NodaTime
- All the test with the test database and generating the database with `EnsureCreated()` work fine

I have no clue where to begin pruning the model to make it a minimal reproduceable repo, but if somebody gives me some hint I am willing to try ...

This is the output:

```
Build succeeded.
dotnet exec --depsfile /Users/hugh/Repositories/B4f/Infra/Infra.Persistence/bin/Release/net9.0/Infra.Persistence.deps.json --additionalprobingpath /Users/hugh/.nuget/packages --runtimeconfig /Users/hugh/Repositories/B4f/Infra/Infra.Persistence/bin/Release/net9.0/Infra.Persistence.runtimeconfig.json /Users/hugh/.dotnet/tools/.store/dotnet-ef/9.0.0/dotnet-ef/9.0.0/tools/net8.0/any/tools/netcoreapp2.0/any/ef.dll migrations add --context B4F.Infra.Persistence.EfCore.B4FContext Initial --output-dir Migrations --assembly /Users/hugh/Repositories/B4f/Infra/Infra.Persistence/bin/Release/net9.0/Infra.Persistence.dll --project /Users/hugh/Repositories/B4f/Infra/Infra.Persistence/Infra.Persistence.csproj --startup-assembly /Users/hugh/Repositories/B4f/Infra/Infra.Persistence/bin/Release/net9.0/Infra.Persistence.dll --startup-project /Users/hugh/Repositories/B4f/Infra/Infra.Persistence/Infra.Persistence.csproj --project-dir /Users/hugh/Repositories/B4f/Infra/Infra.Persistence/ --root-namespace B4F.Infra.Persistence --language C# --framework net9.0 --configuration Release --nullable --working-dir /Users/hugh/Repositories/B4f --verbose
Using assembly 'Infra.Persistence'.
Using startup assembly 'Infra.Persistence'.
Using application base '/Users/hugh/Repositories/B4f/Infra/Infra.Persistence/bin/Release/net9.0'.
Using working directory '/Users/hugh/Repositories/B4f/Infra/Infra.Persistence'.
Using root namespace 'B4F.Infra.Persistence'.
Using project directory '/Users/hugh/Repositories/B4f/Infra/Infra.Persistence/'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'DesignTimeContextFactory'.
Found DbContext 'B4FContext'.
Finding DbContext classes in the project...
Using DbContext factory 'DesignTimeContextFactory'.

*** DesignTimeContextFactory.CreateDbContext() ***


*** B4FContext(options)

Using context 'B4FContext'.
Finding design-time services referenced by assembly 'Infra.Persistence'...
Finding design-time services referenced by assembly 'Infra.Persistence'...
Using design-time services from assembly 'Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime'.
Finding design-time services for provider 'Npgsql.EntityFrameworkCore.PostgreSQL'...
Using design-time services from provider 'Npgsql.EntityFrameworkCore.PostgreSQL'.
Finding IDesignTimeServices implementations in assembly 'Infra.Persistence'...
No design-time services were found.
'B4FContext' disposed.
System.InvalidOperationException: Cannot scaffold C# literals of type 'System.Reflection.NullabilityInfoContext'. The provider should implement CoreTypeMapping.GenerateCodeLiteral to support using it at design time.
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.UnknownLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.<Fragment>g__AppendMethodCall|57_0(IMethodCallCodeFragment current, <>c__DisplayClass57_0&)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Fragment(IMethodCallCodeFragment fragment, Int32 indent)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateAnnotations(String builderName, IAnnotatable annotatable, IndentedStringBuilder stringBuilder, Dictionary`2 annotations, Boolean inChainedCall, Boolean leadingNewline, MethodInfo hasAnnotationMethodInfo)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.Generate(String modelBuilderName, IModel model, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMetadata(String migrationNamespace, Type contextType, String migrationName, String migrationId, IModel targetModel)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language, Boolean dryRun)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace, Boolean dryRun)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace, Boolean dryRun)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Cannot scaffold C# literals of type 'System.Reflection.NullabilityInfoContext'. The provider should implement CoreTypeMapping.GenerateCodeLiteral to support using it at design time.

Process finished with exit code 1.

```

**Comment by roji** [comment] 2024-11-30 18:38
@hugh-maaskant what could be helpful, is if you could test with the latest 10 [daily build](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md) - which already contains the fix from #34996 - in order to confirm whether the problem goes away. If it does not, a new issue with a minimal repro would be the way to go.

**Comment by hugh-maaskant** [comment] 2024-11-30 20:24
Hi @roji thanks for the quick update (on a Saturday!). It took me a while to find out exactly how to use the daily builds, but I *think* I got it figured out and the result is that the Migration was build correctly :-)

I used the following configuration in the .csproj file (I stripped some irrelevant references here):

```
    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0-*">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.KeyPerFile" Version="9.0.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
      <PackageReference Include="NodaTime" Version="3.2.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0-*" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.0-*" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.0-*" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.1-*" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime" Version="9.0.1-*" />
    </ItemGroup>
```

And this is the NuGet.config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <disabledPackageSources>
        <clear />
    </disabledPackageSources>
    <packageSources>
        <clear />
        <add key="dotnet10" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10/nuget/v3/index.json" />
        <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    </packageSources>
</configuration>
```

Hope that is correct ...

Thanks for your help, highly appreciated!

**Comment by roji** [comment] 2024-12-01 11:18
Great, thanks for confirming!

**Comment by Everwig** [comment] 2025-01-25 16:21
> We've experienced the same issue while updating EF 5 to EF 8. I've tried hard to reproduce it in a sample project with no luck. A few information about the project which may help others to narrow down the problem:
> 
>     * The environment is almost the same as in the first comment, except we use Microsoft.EntityFrameworkCore.SqlServer as database provider.
> 
>     * Our entity classes are in a project with `<Nullable>enable</Nullable>` in the csproj file.
> 
>     * The context class is in another project without `<Nullable>enable</Nullable>` in the csproj file.
> 
>     * After changing the target framework from 5 to 8 in all projects in the solution, I can add a migration.
> 
>     * After updating EF 5.* packages to 6.* packages, I still can add a migration.
> 
>     * After updating EF 6.* packages to 7.* (or 8.*) packages, I can't add a migration, I get the same error as in the first comment.
> 
> 
> What helped in our case: we added a `modelBuilder.Entity<EntityTypeName>().HasNoKey().ToView(null);` line for each table-valued-function that was configured in our context class. At runtime, all functions worked correctly with EF 7 and EF 8, but at design-time, the tooling needed these additional configuration lines to be able to create the database snapshot. EF 5 and EF 6 tooling worked well without these. I hope this helps somebody.

Thank you @pjenei. This helped me out. I was experiencing the same issue when trying to add a table-valued function to my DbContext. Adding that one line took care of the problem for me.
