### ISSUE TITLE
DbUpdateConcurrencyException is causing EF to query every row of every table.

### ISSUE THREAD

**Issue by rose-pace** [dotnet/efcore#15000] opened 2019-03-12 20:00 UTC
We are using optimistic concurrency with using a RowVersion field for most tables. Whenever we receive a DbUpdateConcurrencyException it takes a long time to return. In Sql Server Profiler I can see that before the exception is caught A query pulling all rows for every table in our DB is being run. It appears to run each query in alphabetical order which is how the DbSets appear in our DbContext. This appears to be similar to the issue reported in #13310 but we can reproduce it consistently by setting up a situation to cause a DbUpdateConcurrencyException to be thrown. We do not have lazy loading set up so I'm not sure what could be walking through each of the DbSets in the order that they appear in our context file. This is also the same order that the entities are configured in the OnModelCreating method.

**Comment by ajcvickers** [comment] 2019-03-13 16:34
@rosspace Can you post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing? Without this we can try to investigate, but if we can't reproduce what you are seeing we likely won't get very far.

**Comment by rosspace** [comment] 2019-03-13 17:44
I'll try setting something up but in the meantime here is a gist of our DbContext file https://gist.github.com/rosspace/cd8e1c338d62508b4f9dfb2d2e407b52.

This is an Asp.Net Core 2.0 project and the context is configured:
`services.AddDbContext<ThisProjectContext>(c =>
                c.UseSqlServer(Configuration.GetConnectionString("ThisProjectConnection")));`

We are using Microsoft.EntityFrameworkCore.SqlServer v2.1.1

**Comment by rosspace** [comment] 2019-03-15 12:53
Making a small project that reproduces this behavior is proving difficult. I think I will need to go the other way and start tearing things out of my project until the behavior stops happening.

**Comment by scottsauber** [comment] 2019-03-15 13:22
@ajcvickers  - I'll also try to get a small repro going since I'm still hitting the same thing

**Comment by ajcvickers** [comment] 2019-03-22 16:36
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:55 UTC
Labels: closed-could-not-reproduce, customer-reported
