### ISSUE TITLE
Make InMemory provider enforce uniqueness of Alternate Keys

### ISSUE THREAD

**Issue by philippecp** [dotnet/efcore#3850] opened 2015-11-23 18:25 UTC
When adding two entities with the same alternate key in an InMemory database, no exception is thrown and both entities are added.

**Comment by rowanmiller** [comment] 2015-12-01 18:28
Agreed that this would be a useful thing to add to the in-memory provider. We aren't planning to do this for initial RTM. Marking as up for grabs as this would make a good contribution too.

**Comment by android2221** [comment] 2021-05-02 02:14
Is this issue still relevant? I'd like to try my hand at it.

**Comment by android2221** [comment] 2021-05-02 02:54
With a cursory glance / test I was generating errors like this when adding an object with the same alternate key: 
`The instance of entity type 'Customer' cannot be tracked because another instance with the same key value for {'MyFakeAlternatekey'} is already being tracked. When attaching existing entities....`

This would be the ideal output right? If so, we might be able to close this one.

**Comment by AndriySvyryd** [comment] 2021-05-03 17:04
@android2221 Here's a test for this:

```C#
[ConditionalFact]
public void Throws_on_duplicate_alternate_key_values()
{
    var modelBuilder = InMemoryTestHelpers.Instance.CreateConventionBuilder();
    modelBuilder.Entity<MyEntityType>(
        eb =>
        {
            eb.HasAlternateKey("AlternateId");
        });

    var optionsBuilder = new DbContextOptionsBuilder()
        .UseModel(modelBuilder.FinalizeModel())
        .UseInMemoryDatabase("AlternateKeys");

    using (var context = new DbContext(optionsBuilder.Options))
    {
        context.Add(new MyEntityType { Id = 1, AlternateId = 11});
        context.SaveChanges();
    }

    using (var context = new DbContext(optionsBuilder.Options))
    {
        context.Add(new MyEntityType { Id = 2, AlternateId = 11 });
        Assert.Throws<DbUpdateException>(() => context.SaveChanges());
    }
}

private class MyEntityType
{
    public int Id { get; set; }
    public int AlternateId { get; set; }
}
```

**Comment by android2221** [comment] 2021-05-03 17:57
@AndriySvyryd does this pass? In my testing I did not save the context between additions. If it passes, then we can close the issue right? If not, I'll dig deeper :)

**Comment by AndriySvyryd** [comment] 2021-05-03 18:15
@android2221 It doesn't pass

**Comment by android2221** [comment] 2021-05-04 02:11
This one is outside my wheelhouse, I give up.

**Comment by ajcvickers** [comment] 2022-10-26 10:19
We recommend against using the in-memory provider for testing--see [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/). While we have [no plans to remove the in-memory provider](https://github.com/dotnet/efcore/issues/18457), we will not be adding any new features to this provider because we believe valuable development time is better spent in other areas. When feasible, we plan to still fix regressions in existing behavior.

**Closed by ajcvickers** 2022-10-26 10:19 UTC
Labels: type-enhancement, propose-close, good first issue, area-in-memory
