### ISSUE TITLE
Using HasDiscriminator and OwnsOne on the same configuration causes unnecessary SQL JOINS

### ISSUE THREAD

**Issue by BahKoo** [dotnet/efcore#17786] opened 2019-09-12 02:40 UTC
When configuring both a discriminator and an owned type on the same entity, the generated SQL joins 2 queries to the same table. This seems unnecessary.

### Configuration

```
var builder = modelBuilder.Entity<Task>();

builder.HasKey(t => new { t.Id });
builder.HasDiscriminator()
	.HasValue<OriginationTask>("Origination");
builder.OwnsOne(t => t.Status);
```

### SQL

```
SELECT [t].[Id], [t].[Discriminator], [t0].[Id], [t0].[Status_Value]
FROM [Tasks] AS [t]
LEFT JOIN (
    SELECT [t.Status].*
    FROM [Tasks] AS [t.Status]
    WHERE [t.Status].[Discriminator] = N'Origination'
) AS [t0] ON [t].[Id] = [t0].[Id]
WHERE [t].[Discriminator] = N'Origination'
```

### Further technical details

EF Core version: 2.2.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Framework 4.6.1
Operating system: Windows 7 64 bit
IDE: Visual Studio 2017 15.9.14

**Comment by AndriySvyryd** [comment] 2019-09-12 03:15
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/15374

**Closed** 2022-10-16 14:41 UTC
Labels: closed-duplicate, customer-reported
