### ISSUE TITLE
HasMany now has cascading deletions

### ISSUE THREAD

**Issue by Zenexer** [dotnet/efcore#16204] opened 2019-06-21 20:28 UTC
With v3.0.0-preview6, HasMany now adds cascading deletion constraints by default.  This is a breaking change; if these cascading constraint result in a cycle, an error such as the following will appear:

```
Microsoft.Data.SqlClient.SqlException: 'Introducing FOREIGN KEY constraint 'FK_Leads_AspNetUsers_UserId' on table 'Leads' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint or index. See previous errors.'
```

**Comment by Zenexer** [comment] 2019-06-21 20:38
An example in which this breaks:

* Customer has many Inquiries with one Customer
* SupportRep has many Inquiries with one AssignedSupportRep
* SupportRep has many AssignedCustomers with one DefaultSupportRep

This worked in 2.x and 3.0.0-preview5; it results in an exception in preview6.

**Comment by ajcvickers** [comment] 2019-06-24 16:15
@Zenexer Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-07-01 16:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:26 UTC
Labels: closed-could-not-reproduce
