### ISSUE TITLE
VB.NET entities cause an exception with EE Core

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/efcore#20390] opened 2020-03-23 23:28 UTC
I published [eShopOnWeb_VB.NET](https://github.com/VBAndCs/eShopOnWeb_VB.NET) which is the VB.NET version of the Microsoft full web sample [eShopOnWeb](https://github.com/dotnet-architecture/eShopOnWeb)
The solution contains 3 projects:
1. Web.vb (a VB.NET ASP.NET Core 3.1 project).
2. Infrastructure.vb (a VB.NET .NET standard library project).
3. ApplicationCore.cs (a C# .NET standard library project):
The repo also contains a VB.NET version named ApplicationCore.vb, but if you referenced it in the solution instead of the C# version, it will causes a runtime exception. I couldn't find the source of this exception, and I compared the C# and VB.Net versions of the project and they seems identical, with no obvious VB.NET special behavior that can cause the exception.
This project contains the database entities and other classes used in query operations.
This is the exception:
>InvalidOperationException: Lambda expression used inside Include is not valid.
> Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessInclude(NavigationExpansionExpression source, Expression expression, bool thenInclude)

What is the source of this exception?
Is there any EF convention that can be broken by different naming of  properties backing fields or something similar?
Is it related to expression tree that VB generates?
How can I solve this?

**Comment by smitpatel** [comment] 2020-03-23 23:29
Likely related to expression tree VB generated. Can you get print out of expression tree VB generates in C# world?

**Comment by VBAndCs** [comment] 2020-03-23 23:36
@smitpatel 
How can I get this expression tree?
And if it differs between C# and VB.NET, how can this be solved?
Thanks.

**Comment by VBAndCs** [comment] 2020-03-23 23:37
Note: I see a note here says:
>  VBAndCs added the customer-reported label 8 minutes ago

I didn't do such a thing :)

**Comment by smitpatel** [comment] 2020-03-23 23:39
That is template thing. I am not expert in VB but I think what you could do is
- Add a C# console app to your project.
- Write your query in VB project, instead of calling ToList or any other enumerating method, call a custom method which calls into C# project you add.
- In custom method inside C# project, take input of type `IQueryable<T>`. `IQueryble.Expression` would give you the expression tree backing the queryable. Print out of that would give us some hint how the tree is differing from C# tree.

**Comment by VBAndCs** [comment] 2020-03-24 14:16
As I see, string comparison affects the expression trees. for example, in VB this lambda:
```Function(b) b.Id = basketId```

yields the expression:
```
Body = {(CompareString(b.BuyerId, value(Microsoft.eShopWeb.ApplicationCore.Specifications.BasketWithItemsSpecification+_Closure$__1-0).$VB$Local_buyerId, False) == 0)}
```

but in c#:
```
Body = {(b.BuyerId == value(Microsoft.eShopWeb.ApplicationCore.Specifications.BasketWithItemsSpecification+<>c__DisplayClass1_0).buyerId)}
```

Can this affect EF?
And how can I solve this?
I.e: How Can I convert VB expression tree to C#'s?
Or: How can I make EF accept VB's?

**Comment by smitpatel** [comment] 2020-03-24 14:26
Duplicate of #19592

**Comment by VBAndCs** [comment] 2020-03-24 15:08
@smitpatel
I don't have the same exception mentioned there, and I think there is more issues here.
Note the part
`+_Closure$__1-0).$VB$Local_buyerId` in VB which is  
`+<>c__DisplayClass1_0).buyerId` in C#
Is this OK with EF?
There is more to investigate in my App, but it is better to go step by step.

**Comment by VBAndCs** [comment] 2020-03-24 16:31
@smitpatel 
I moved the string comparison to a separate function call, and the is the resulting expression:
`Criteria = {basket => CompareStrings(basket.BuyerId, value(Microsoft.eShopWeb.ApplicationCore.Specifications.BasketWithItemsSpecification+_Closure$__1-0).$VB$Local_buyerId)}`

I still get the same exception as before, so it is due to the string comparison. Can it be the `+_Closure$__1-0).$VB$Local_buyerId` part?

**Comment by smitpatel** [comment] 2020-03-24 16:42
Your last expression tree uses `CompareStrings` function rather than `CompareString`. Can you also post exception message?

**Comment by VBAndCs** [comment] 2020-03-24 17:03
>InvalidOperationException: Lambda expression used inside Include is not valid.
 Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessInclude(NavigationExpansionExpression source, Expression expression, bool thenInclude)

**Comment by smitpatel** [comment] 2020-03-24 17:32
Can you also share VB query? What is exactly inside include?

**Comment by VBAndCs** [comment] 2020-03-24 18:12
I think this is the expression that causes the exception, because it is sent to include and the error occurs after pssing it:

In C#
`b => b.Items`
Yieds this expression:
`b => b.Items`

In VB:
`Function(basket) basket.Items`

Yieds this expression:
`basket => Convert(basket.Items, Object)`


The Expression type is:
`Expression<Func<T, object>>`
'Expression(Of Func(Of T, Object))`

So, does the convert function in VB cause any issue with EF?

**Comment by smitpatel** [comment] 2020-03-24 18:33
Include lambda does not allow convert node around it. Especially for collection navigation.
As a work-around you should be able to use string based include.

**Comment by VBAndCs** [comment] 2020-03-24 18:41
It worked!
I used `AddInclude(NameOf(Basket.Items))`
Instead of `AddInclude(Function(b) b.Items)`
And it finally works after 3 days of cahsing ghosts :)
Thanks very much for this help.
But most important, how can we eliminate this from the source?
Can you solve it in EF, or it must be solved in VB.NET LinQ (which may never happen)?

**Comment by smitpatel** [comment] 2020-03-24 18:44
We will look into fixing it in EF Core source. We account for differences in expression tree VB generates. We just need to come up with reliable set of conditions so we don't end up with bugs for C#.

**Comment by zspitz** [comment] 2020-03-24 20:25
I would suggest the same workaround I suggested [here](https://github.com/simple-odata-client/Simple.OData.Client/issues/638#issuecomment-512890629):

> Nevertheless, it might be a good idea to check if the pre-conversion node's Type (in this case x.Trips) is assignable to the post-conversion type (IEnumerable<Trip>) then the conversion should be ignored in the parsing.

**Comment by ajcvickers** [comment] 2020-03-27 21:40
The team discussed this and we feel the best course of action is for the VB code to use a strongly typed call in the same way that the C# code does.

**Comment by VBAndCs** [comment] 2020-03-27 22:25
@ajcvickers 
Thanks, but I want to ask:
>  use a strongly typed call in the same way that the C# code does.

Sorry, I see nothing different in C# code. Can you please explain how C# does the strongly typed call in this sample?

**Comment by ajcvickers** [comment] 2020-03-27 22:27
@smitpatel?

**Comment by smitpatel** [comment] 2020-03-27 22:31
Define your function which creates include strongly typed.
```VB
Protected Overridable Sub AddInclude(ByVal includeExpression As Expression(Of Func(Of T, System.Object)))
-----------> Using Func<T, System.Object> is error
-----------> Use Func<TEntity, TCollection> Make your function strongly typed.
            Includes.Add(includeExpression)
        End Sub
```

**Comment by VBAndCs** [comment] 2020-03-27 22:42
@smitpatel
As I said, I started with a C# project, translated it to VB. I changed nothing. This is the MS [eShopeOnWeb](https://github.com/dotnet-architecture/eShopOnWeb) educational sample, and it is supposed to be written by professionals to be exemplary. I myself avoid objects as I can, but this is the kind of situation where I am not the app designer, and when I tried to get rid of the object, the changes propagated to a chain of classes and interfaces that broke the app. So, I just want to get the same behavior in VB as in C#, no more or less.
Thanks.

**Comment by VBAndCs** [comment] 2020-03-27 22:45
My suggestion here, is to ignore the Convert(? , Onject) in EF, since every thing can be casted to object safely.

**Comment by smitpatel** [comment] 2020-03-27 22:46
> As I said, I started with a C# project, translated it to VB.

The translation or whatsoever is not in control of EF Core. Neither the build breaks due to change. If the API is not strongly typed then it is bad query generated by the app and EF Core fails. App developer should fix the query to make it strongly typed or else use Include with string method.

**Comment by VBAndCs** [comment] 2020-03-27 22:54
@smitpatel 
Thank you for the workaround. You helped me, but frankly not helping VB. VB faced this kind of decisions from all teams in the past few years, until it is declared frozen/dead eventually. The solution is easy, but neither VB team or EF team are willing to do it.
Thanks.

**Comment by smitpatel** [comment] 2020-03-27 23:03
I do not see why EF Core should change anything when we provided strongly typed API for sole purpose of chaining. The reason Include has `TProperty` so that you can write `ThenInclude` and get intellisense. While we do accommodate various form of expression trees, we do not make changes to accommodate and incorrect tree. We have actively refused to make changes even for C# code when users are creating incorrect trees. So language does not change anything here. Personally, the maintenance of code to support incorrect trees is not worth the value they provide.

In your case, at least you can get away without changing your function signature easily. The real fix is still, make your API stop abusing object.

**Comment by VBAndCs** [comment] 2020-03-28 00:59
@smitpatel:
OK, but then you should provide more info about the exception: what happened, and where. I spent 3 days tracing the app to find source of the problem. The message itself doesn't help, neither the calls tack that refers to async method calls, and internal .NET Core methods.
>InvalidOperationException: Lambda expression used inside Include is not valid.
Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessInclude(NavigationExpansionExpression source, Expression expression, bool thenInclude)

You need to provide the part of the expression tree that caused the error, and if possible, the lambda that built it, or the method that passes this lambda. Give us any helpful data to fix the problem.

**Comment by smitpatel** [comment] 2020-03-28 01:04
Duplicate of #17498

**Closed** 2022-10-16 18:17 UTC
Labels: closed-external, customer-reported, area-query
