### ISSUE TITLE
Runtime Error using Group By on outer joined result set

### ISSUE THREAD

**Issue by cdarrigo** [dotnet/efcore#12172] opened 2018-05-30 15:03 UTC
When I attempt to perform a group by on a result set that has an outer join, I get a runtime error. 

here's the query
```
  var query = from ta in dataContext.TransactionApplications.Where(i => !i.Deleted && i.DestinationTransactionId == chargeId)
                join p1 in dataContext.Payments.Where(i => !i.Deleted && i.SchoolId == schoolId) on ta.SourceTransactionId equals p1.Id into jPayment
                from p in jPayment.DefaultIfEmpty()
                join c1 in dataContext.Credits.Where(i => !i.Deleted & i.SchoolId == schoolId) on ta.SourceTransactionId equals c1.Id into jCredit
                from c in jCredit.DefaultIfEmpty()
                select new 
                {                   
                    PaymentId = p.Id,
                    CreditId = c.Id,
                    PaymentDate = p.Date,
                    CreditDate = c.Date,
                    ta.Amount,
                    p.PayTypeCode
                };

            var c2 = await query.GroupBy(i =>  new {i.PaymentId,i.CreditId})
                .Select(g => new
                {
                    PaymentId = g.Key.PaymentId,
                    CreditId = g.Key.CreditId,
                    Cnt = g.Count(),
                    Sum = g.Sum(i => i.Amount)
                }).ToArrayAsync();
````

Exception message:
System.InvalidOperationException: The binary operator NotEqual is not defined for the types 'Microsoft.EntityFrameworkCore.Storage.ValueBuffer' and 'Microsoft.EntityFrameworkCore.Storage.ValueBuffer'.

Stack trace:
```
at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
   at System.Linq.Expressions.Expression.NotEqual(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
   at Microsoft.EntityFrameworkCore.Query.Expressions.Internal.NullConditionalExpression.Reduce()
   at System.Linq.Expressions.Expression.ReduceAndCheck()
   at System.Linq.Expressions.Expression.ReduceExtensions()
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExtensionExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteNewExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.Create(Shaper originalShaper, LambdaExpression materializer)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at System.Collections.Generic.AsyncEnumerableHelpers.<ToArrayWithLength>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Collections.Generic.AsyncEnumerableHelpers.<ToArray>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Blackbaud.TMS.DataManagement.Service.Data.Providers.ChargeDataProvider.<GetChargeAppliedTransactionListAsync>d__24.MoveNext() in C:\Repo\tms-dmgmt-svc\src\Blackbaud.TMS.DataManagement.Service\Data\Providers\ChargeDataProvider.cs:line 845
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```
### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```
### Further technical details
EF Core version: 2.1.0-rc1-final
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10
IDE: Visual Studio 2017 15.4

**Comment by smitpatel** [comment] 2018-05-30 17:59
I got repro in 2.1.0-rc1 package. But working fine in 2.1.0 final release. Can you verify it is working for you too?

**Comment by smitpatel** [comment] 2018-05-30 18:00
Duplicate of #11831

**Comment by cdarrigo** [comment] 2018-05-30 19:17
Still getting this with 2.1.0-rc1-final.  please don't close this ticket.

**Closed** 2022-10-16 12:27 UTC
Labels: customer-reported
