### ISSUE TITLE
When using sqlite to query a large amount of data, the memory increases

### ISSUE THREAD

**Issue by luy710** [dotnet/efcore#30474] opened 2023-03-14 07:58 UTC
When using sqlite to query a large amount of data, the memory increases
eg:
```c#
 using (var scope = _serviceProvider.CreateScope())
        {

            var context = scope.ServiceProvider.GetRequiredService<FileDBContext>();
            var fileBackups = context.FileHistorys.AsNoTracking().ToList();
            context.Dispose();
            scope.Dispose();
        }
```

Large amount of data in table FileHistory

**Comment by roji** [comment] 2023-03-14 11:10
@luy710 ToList loads the entire table into memory, so that's expected to increase memory needs. [Consider streaming the results instead](https://learn.microsoft.com/en-us/ef/core/performance/efficient-querying#buffering-and-streaming).

Or are you saying that you think you're seeing a memory leak, where the memory is *never* released? If so, can you please submit a full, runnable code sample which shows this happening?

**Comment by ajcvickers** [comment] 2023-03-29 19:35
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-03-29 19:35 UTC
