### ISSUE TITLE
Unnecessary join when not using foreign key property in LINQ query

### ISSUE THREAD

**Issue by sm15455** [dotnet/efcore#24134] opened 2021-02-12 09:17 UTC
Hi,

I have an Order class and a Customer class. The Order class **doesn't** have the CustomerId property but only the Customer property of type Customer.

```C#
public class Order 
{
  public int Id { get; set;}
  public Customer Customer { get; set;}
}

public class Customer 
{
  public int Id { get; set;}
}
```

If I want to retrieve orders by customer I use the following LINQ query.

```C#
var customerId = 1;
ctx.Orders.Where(o => o.Customer.Id == customerId).ToList();
```

This is the sql generated (simplified)

```SQL
select o.* 
from Orders o
join Customer c ON o.CustomerId == c.Id
where c.Id = 1
```

The join here is unnecessary as I'm retrieving data for the Order class only. 

If I add the CustomerId property to the Order class and use that property in the LINQ query the SQL is optimized.

```C#
public class Order 
{
  public int Id { get; set;}
  public int CustomerId { get; set;}
  public Customer Customer { get; set;}
}


var customerId = 1;
ctx.Orders.Where(o => o.CustomerId == customerId).ToList();
```

This is the sql generated (simplified)
```SQL
select o.* 
from Orders o
where o.CustomerId = 1
```

I think that the generated SQL should be identical and without the SQL join in both configurations. Am I correct? Is this on your radar?

EF Core version: EF core 5.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.5

**Comment by smitpatel** [comment] 2021-02-12 17:29
Duplicate of #15826

**Closed** 2022-10-16 19:23 UTC
Labels: customer-reported
