### ISSUE TITLE
EF 1.5.0-rc2-24027 does not work with netstandard 1.5 

### ISSUE THREAD

**Issue by afoliaco** [dotnet/efcore#5832] opened 2016-06-22 02:02 UTC
Create a new class project and add Microsoft.Entityframework version 1.5.2-rc2-24027.

Note: is this a release candidate?

![2016-06-21_215417](https://cloud.githubusercontent.com/assets/5281768/16252394/bad27ce4-37fb-11e6-8511-0d0b1a50bed5.png)

**Comment by Boglen** [comment] 2016-06-22 10:32
You can wait about for five days and obtain rtm.

**Comment by natemcmaster** [comment] 2016-06-22 16:15
EF Core 1.0.0-rc2 was compatible with .NET Standard 1.3 and .NET 4.5.1, so this will install to your netstandard1.5 project. The issue you are seeing is that as of RC2 two of EF Core's dependencies (Ix-Async and re-linq) did not support .NET Standard. You can work around this in RC2 by using "imports".

```json
{
  "frameworks": {
    "netstandard1.5": {
      "imports": ["dnxcore50", "portable-net451+win8"]
    }
}
```

See https://docs.efproject.net/en/latest/miscellaneous/rc1-rc2-upgrade.html#using-imports-in-project-json for a full explanation.

The RTM release will not require using "imports": re-linq and Ix-async have upgraded to support .NET Standard.

Closing as a duplicate of #5176

**Closed** 2022-10-16 09:46 UTC
