### ISSUE TITLE
Sqlite db corrupted by log (!) entries

### ISSUE THREAD

**Issue by dellamonica** [dotnet/efcore#35215] opened 2024-11-26 13:55 UTC
## Sqlite db corrupted by log entries

I have an application that uses Microsoft.Data.Sqlite 8.0.10 in a relatively trivial way:

- Connection is opened during program start and kept open the whole time the process is open.
- The db is used as write/append-only and has a single table.
- The connection is stored as a field in an IDisposable class, and the Dispose method calls the connection Dispose. The whole code that works with the db is below.
- This program is run in the background for weeks at a time and configured to start when the machine boots.
- The application sets up logging with the code below, the only sink is the Console, _we don't write any logs to disk_.

After a few weeks of the program running, it started to crash on initialization due to a corrupted sqlite db. Opening the file on a text editor I see several places where **log entries are printed in the file**! There is nothing on _my code_ that would put those strings there.

This looks like a buffer was used after release (e.g. a possible explanation would be if (1) the sqlite side would release a buffer, (2) the logger would get hold of it, format the string using it, (3) the [buggy code] would be flush the buffer to the db file, corrupting it).

There are very few corrupted lines in the db, and they are clustered (there are about 5 parts of the .db file which contain these log entries). In the period of time this db was used, the logger certainly wrote several thousand lines to the Console, so whatever code path causes the corruption is not very frequent.

### Include your code

Logger creation:

```csharp
using var loggerFactory = LoggerFactory.Create(
    builder => builder.
        AddConsole().
        SetMinimumLevel(
            int.TryParse(config["loglevel"], out int ll)
                ? (LogLevel)ll
                : LogLevel.Debug));
var logger = loggerFactory.CreateLogger("PrinterAdapter");
```

Sqlite-related code:

```csharp
internal sealed class Db(string dbPath, ILogger logger) : IDisposable
{
    private SqliteConnection? _connection;

    public async Task Connect()
    {
        _connection = new($"Data Source={dbPath};");
        await _connection.OpenAsync();
        var cmd = new SqliteCommand(
            "CREATE TABLE IF NOT EXISTS produced_pieces (piece_id CHAR(64), timestamp DATETIME DEFAULT CURRENT_TIMESTAMP)",
            _connection);
        await cmd.ExecuteNonQueryAsync();
        cmd = new(
            "CREATE INDEX IF NOT EXISTS piece_id_index ON produced_pieces (piece_id)",
            _connection);
        await cmd.ExecuteNonQueryAsync();
    }

    public void Dispose()
    {
        _connection?.Dispose();
    }

    public async Task<bool> AddPiece(string pieceId)
    {
        if (_connection is null)
        {
            return false;
        }
        string pieceIdParam = "@piece_id";
        using var cmd = new SqliteCommand(
            $"INSERT INTO produced_pieces (piece_id) VALUES ({pieceIdParam})",
            _connection);
        cmd.Parameters.Add(new(pieceIdParam, pieceId));
        bool result = false;
        const string ErrorMessage = "Failed to insert Piece entry in the sqlite db";
        try
        {
            result = 1 == await cmd.ExecuteNonQueryAsync();
            if (!result)
            {
                logger.LogError(ErrorMessage);
            }
        }
        catch (Exception ex)
        {
            logger.LogError(ex, ErrorMessage);
        }
        return result;
    }
}

```

## Details of the corrupted file

The console log entries appear in several parts of the file. Interestingly, the log of the very crash due to the corruption appears right at the beginning of the db file. Hopefully this may be helpful to locate the bug (what could cause data to be flushed to the db *after* this type of SqliteException being thrown).

![Image](https://github.com/user-attachments/assets/22e3a751-b0cd-48ef-9a3e-8aa62bcb3965)

### Include version information

Microsoft.Data.Sqlite version:8.0.10
Target framework: NET 8.0 compiled as NAOT
Operating system: Windows

**Comment by ajcvickers** [comment] 2024-11-26 14:08
@dellamonica `SqliteConnection` and related types are not thread safe. Are you sure that you're not using the same instance from multiple thread concurrently?

**Comment by dellamonica** [comment] 2024-11-26 14:13
The program processes a stream of events, I don't see how multiple threads could be causing this behavior. At any rate, even if the types are not thread safe, corrupting the database file should *never* happen.

**Comment by ajcvickers** [comment] 2024-11-26 14:16
@dellamonica The behavior when using a non-thread safe object concurrently from multiple threads is undefined. Database corruption is not unlikely.

If this isn't the case, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by roji** [comment] 2024-11-26 15:00
@dellamonica API documentation (for .NET and for other platforms) doesn't typically specificy for each and every API whether it's safe or not for concurrent usage; for example, the documentation on .NET [HashSet](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1) make no mention of thread-safety, and yet you cannot safely use that type concurrently. The general assumption is that APIs aren't safe for concurrent usage unless the documentation specified otherwise.

Note that "supporting async" does not mean "support concurrency" - all that async means is that a thread does not block when waiting for an operation (typically I/O) to complete. It is still your responsibility to ensure that you're not e.g. starting two async operations on the same e.g. connection, if that's not supported.

Finally, you should not need a SemaphoreSlim: your responsibility is basically to not perform more than one operation concurrently on a given SqliteConnection (or use a SqliteCommand/SqliteDataReader concurrently). The recommendation - like for all ADO.NET providers - is for you to instantiate a new SqliteConnection whenever you need to do something with the database, and then dispose it when you're done. Do not attempt to reuse the same SqliteConnection instances or keep them around as members - this is where a lot of the concurrency problems come from; just keep them as local variables in your function.

Hope that all makes sense and sheds light on things.

**Comment by dellamonica** [comment] 2024-11-26 15:16
> [@dellamonica](https://github.com/dellamonica) API documentation (for .NET and for other platforms) doesn't typically specificy for each and every API whether it's safe or not for concurrent usage; for example, the documentation on .NET [HashSet](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1) make no mention of thread-safety, and yet you cannot safely use that type concurrently. The general assumption is that APIs aren't safe for concurrent usage unless the documentation specified otherwise.

Sure, HashSet is a data structure, not a db access layer, my expectations are certainly different.
What I don't expect at all is that a simple application, _that never launches a thread_, would have a concurrency problem just from the use of async.

> 
> Note that "supporting async" does not mean "support concurrency" - all that async means is that a thread does not block when waiting for an operation (typically I/O) to complete. It is still your responsibility to ensure that you're not e.g. starting two async operations on the same e.g. connection, if that's not supported.
> 

I don't see how that is happening in my code, there are no threads being launched, only async methods being called/awaited.
So, according to your recommendation, my code should not corrupt the db...

> Finally, you should not need a SemaphoreSlim: your responsibility is basically to not perform more than one operation concurrently on a given SqliteConnection (or use a SqliteCommand/SqliteDataReader concurrently). The recommendation - like for all ADO.NET providers - is for you to instantiate a new SqliteConnection whenever you need to do something with the database, and then dispose it when you're done. Do not attempt to reuse the same SqliteConnection instances or keep them around as members - this is where a lot of the concurrency problems come from; just keep them as local variables in your function.

The thing is I'm never done with the database, I'm writing streamed events (say once every 10s on average), should I open and close the connection 360 times per hour? If that does not affect perf, then I'll do that.

> 
> Hope that all makes sense and sheds light on things.

It doesn't! There is no concurrent access to the connection. Here's my program's flow.

An `IAsyncEnumerable<>` is generated and processed as a stream by several layers. One layer saves some info to the db. The processing of each item coming from the stream is done by async methods (e.g. await foreach). As I said in one of my previous replies, the only way there could be some concurrency is if something under the hood is doing it, I don't see it anywhere in my code.

**Comment by roji** [comment] 2024-11-26 19:36
> HashSet doesn't and won't have async methods

That's again not relevant to the concurrency/thread-safety question. Async is orthogonal to concurrency.

> Most importantly, ms.data.sqlite library code should not access memory that is used by something else.

MS.Data.Sqlite doesn't do that, and in fact can't - it's a pure .NET managed library; all it does it perform calls into SQLite, which itself is native.

> By reports "like this" do you mean where there is access to memory that is used by something else?

Not specifically - that specifically a detail of using SQLite, which is a native library. But concurrency issues can lead to various other forms of unexpected behavior - we get reports of that quite frequently.

Please note: I'm not saying you have a concurrency issue; I have no way of knowing that since I don't have a repro, and don't know exactly what you're doing. That's just the most common cause for this sort of error.

I'll go ahead and close this now as there's nothing immediately actionable on our side; but please feel free to post back here if you have new information, or manage to put together a repro. I can reopen at that point and investigate.

**Closed by roji** 2024-11-26 19:36 UTC
Labels: customer-reported, area-adonet-sqlite

**Comment by dellamonica** [comment] 2024-11-26 20:14
> > HashSet doesn't and won't have async methods
> 
> That's again not relevant to the concurrency/thread-safety question. Async is orthogonal to concurrency.

This line of discussion is getting nowhere, so let's move on.

> 
> > Most importantly, ms.data.sqlite library code should not access memory that is used by something else.
> 
> MS.Data.Sqlite doesn't do that, and in fact can't - it's a pure .NET managed library; all it does it perform calls into SQLite, which itself is native.

It is clear that logged text appeared in my sqlite db file, which is the explanation for the corruption, the only way I can see that happening is by some memory buffer being inadvertently shared (managed or unamanged does not really matter here).

> 
> > By reports "like this" do you mean where there is access to memory that is used by something else?
> 
> Not specifically - that specifically a detail of using SQLite, which is a native library. But concurrency issues can lead to various other forms of unexpected behavior - we get reports of that quite frequently.
> 
> Please note: I'm not saying you have a concurrency issue; I have no way of knowing that since I don't have a repro, and don't know exactly what you're doing. That's just the most common cause for this sort of error.
> 
> I'll go ahead and close this now as there's nothing immediately actionable on our side; but please feel free to post back here if you have new information, or manage to put together a repro. I can reopen at that point and investigate.

I'm suggesting that there is some memory being inadvertently shared with the logger (that's the only explanation for the contents appearing in the db file). This content also appears very early in the sqlite file (see the screenshot posted above), which might hint at what code could be executing the write. 

To me it is funny that you guys have given little thought to the fact that somehow log formatted strings (!!!) are showing up on the db file on disk! This should not happen, regardless of thread-safety. Whatever memory the connector is using should not be accessible by the logger and vice-versa.

The only other time I've seen dotnet acting funny with memory, we did find a JIT/GC bug:
https://github.com/dotnet/runtime/issues/39023
Unfortunately, this time it is difficult to reproduce it.

**Comment by roji** [comment] 2024-11-26 21:41
> It is clear that logged text appeared in my sqlite db file, which is the explanation for the corruption, the only way I can see that happening is by some memory buffer being inadvertently shared (managed or unamanged does not really matter here).

I'm repeating myself, but once again, Microsoft.Data.Sqlite is merely a pure-managed wrapper over Sqlite; managed or managed absolutely does matter here, in understanding where the possible bug is. Yes, it's always possible that there's a JIT/GC bug; even if that's the case, then you're in the wrong repo as that would have nothing to do with EF Core or Microsoft.Data.Sqlite.

> To me it is funny that you guys have given little thought to the fact that somehow log formatted strings (!!!) are showing up on the db file on disk! This should not happen, regardless of thread-safety. Whatever memory the connector is using should not be accessible by the logger and vice-versa.

I'm sorry, but that is simply not how it works. If you use a native component in a way which isn't supported - such as incorrect concurrent use - then the results really are undefined, including one component accessing the memory of another (the entire process shares a single memory space). That is the reality of how computer processes work.

Beyond all that, I'm not sure what it is that you expect here, given that we have no repro, and no indication of where the bug is coming from. I'm not saying there's not a bug in .NET, or in Sqlite, or anywhere else; despite what you're claiming, it could also still be a concurrency issue in your own code. But without some sort of repro, there's nothing I can see that we can do about it.

**Comment by dellamonica** [comment] 2024-11-27 12:34
> > It is clear that logged text appeared in my sqlite db file, which is the explanation for the corruption, the only way I can see that happening is by some memory buffer being inadvertently shared (managed or unamanged does not really matter here).
> 
> I'm repeating myself, but once again, Microsoft.Data.Sqlite is merely a pure-managed wrapper over Sqlite; managed or managed absolutely does matter here, in understanding where the possible bug is. Yes, it's always possible that there's a JIT/GC bug; even if that's the case, then you're in the wrong repo as that would have nothing to do with EF Core or Microsoft.Data.Sqlite.

Absolutely, that's not what I meant by "doesn't matter", I just meant this type of bug can occur in either. It certainly could be a bug in the native lib and not M.D.Sqlite. I don't think I'm "lucky" enough to find *two* JIT/GC bugs in my lifetime, but who knows.

> 
> > To me it is funny that you guys have given little thought to the fact that somehow log formatted strings (!!!) are showing up on the db file on disk! This should not happen, regardless of thread-safety. Whatever memory the connector is using should not be accessible by the logger and vice-versa.
> 
> I'm sorry, but that is simply not how it works. If you use a native component in a way which isn't supported - such as incorrect concurrent use - then the results really are undefined, including one component accessing the memory of another (the entire process shares a single memory space). That is the reality of how computer processes work.

It might not be your intention, but this reads _very condescending_, I know how all that works. Such memory bugs exist essentially everywhere, and it's a big reason for languages like Rust to exist. The fact that these bugs are possible is not under discussion, my point is that regardless of incorrect usage (e.g. due to concurrency) we all should strive to fix these issues. This time we had log data dumped to the disk, but it could have been any other sensitive/secret info from the process.

> 
> Beyond all that, I'm not sure what it is that you expect here, given that we have no repro, and no indication of where the bug is coming from. I'm not saying there's not a bug in .NET, or in Sqlite, or anywhere else; despite what you're claiming, it could also still be a concurrency issue in your own code. But without some sort of repro, there's nothing I can see that we can do about it.

At this point I really don't think you'll do anything. I'm just annoyed by what appears to be this line of reasoning from the people in charge of the project: "likely a concurrency misuse of the lib => expect UB => it's fine if db is corrupted AND arbitrary process memory is dumped to disk".

It is indeed unfortunate that I haven't been able to repro the bug (and as I mentioned, testing locally did not reveal any unexpected concurrency in the connection usage). Perhaps the only piece of actionable info that I submitted is one particular location of the file that got corrupted. Since I don't know this code base, it is not clear to me if this info is helpful at all, but sometimes you can narrow down what function could write to that location in the file (to me that section looks like a header). If you say that info alone is too little to go on, I'm not going to push the issue.

For now, I'll have to deploy a new version, that by design cannot have any concurrency issues on the connection, and let it run for several weeks to see if this corruption occurs again. The deployment is non-trivial because this is software installed on industrial machines, so it is a manual installation, and any time spent on these machines is costly.

Perhaps I'll setup a script that keeps monitoring the sqlite db and if it detects corruption then take a memory dump of the process, not sure if that would help though.

**Comment by cincuranet** [comment] 2024-11-27 14:23
> regardless of incorrect usage (e.g. due to concurrency) we all should strive to fix these issues

Incorrect usage is little bit of grey area. We obviously want our users to fall into pit of success and we're trying hard to do so. But we can't fix _every_ incorrect usage.

> but sometimes you can narrow down what function could write to that location in the file (to me that section looks like a header). If you say that info alone is too little to go on, I'm not going to push the issue.

I would be happy to fix that issue for you, but the info you provided is really too little to go on. As was said multiple times, repro is (always) the best. Full memory dump is not nothing, but does not guarantee understanding of the issue (definitely not a single memory dump).

**Comment by dellamonica** [comment] 2024-11-27 14:53
> I would be happy to fix that issue for you, but the info you provided is really too little to go on. As was said multiple times, repro is (always) the best. Full memory dump is not nothing, but does not guarantee understanding of the issue (definitely not a single memory dump).

Thanks, if I do get either (repro/dump) I'll get back here with an update.
