### ISSUE TITLE
Message = "No value provided for required parameter '_outer_RegisterId'."

### ISSUE THREAD

**Issue by dvdobrovolskiy** [dotnet/efcore#7996] opened 2017-03-26 13:32 UTC
I trying to have select in select

I split query in 2 parts in attempt to identify problem.

```
var results = _context.RegisterGroups.Include(i => i.Person).Include(i => i.Register)

var results2 = results.Select(s => new RegisterGroup
{
RegisterGroupId = s.RegisterGroupId,
RegisterId = s.RegisterId,
Register = s.Register,
AttendanceStatus1 = _context.Attendances.Include(i => i.Schedule).ThenInclude(i => i.Register).FirstOrDefault(f => f.Schedule.Register.RegisterId == s.RegisterId).AttendanceStatus
});
```
Here at results2 I have Error
Message = "No value provided for required parameter '_outer_RegisterId'."

Where RegisterId in results do have value
![results single row](http://static.realgrad.ru/1.jpg)

models
```
public class RegisterGroup
    {
        [Key]
        [ScaffoldColumn(false)]
        public int RegisterGroupId { get; set; }

        public int PersonId { get; set; }

        public Person Person { get; set; }

        public int RegisterId { get; set; }

        public Register Register { get; set; }

        public AttendanceStatus AttendanceStatus1 { get; set; }
}

public class Register
    {
        [Key]
        [ScaffoldColumn(false)]
        public int RegisterId { get; set; }

        public Person Teacher { get; set; }

        public Term Term { get; set; }

        public Level Level { get; set; }

        public List<RegisterGroup> RegisterGroups { get; set; }

        [Display(Name = "Lesson Duration")]
        public LessonDuration LessonDuration { get; set; }

        [Display(Name = "Course Duration")]
        public CourseDuration CourseDuration { get; set; }

        [Display(Name = "Letter")]
        public string Letter { get; set; }        
    }

public class Schedule
    {
        [Key]
        [ScaffoldColumn(false)]
        public int ScheduleId { get; set; }

        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yy}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        public Register Register { get; set; }
    }
```

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
IDE: Visual Studio 2017

**Comment by smitpatel** [comment] 2017-03-26 15:19
Dupe of #7714

**Closed** 2022-10-16 10:58 UTC
Labels: closed-duplicate
