### ISSUE TITLE
Call to public SqliteConnection() in  Xamarin.Forms UWP app causes unhandled exception

### ISSUE THREAD

**Issue by dmsi-leo** [dotnet/efcore#26882] opened 2021-12-02 20:42 UTC
## File a bug

Application type: Xamarin.Forms

Call to public SqliteConnection() from Xamarin.Forms UWP app  causes unhandled exception.
The same call works fine on iOS and Android.

### Stack trace

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Data.Sqlite.Utilities.ApplicationDataHelper.GetFolderPath(String propertyName) in /_/src/Microsoft.Data.Sqlite.Core/Utilities/ApplicationDataHelper.cs:line 42
```

### Version information

Microsoft.Data.Sqlite version: 6.0.0
Microsoft.NETCore.UniversalWindowsPlatform version: 6.2.13
Xamarin.Forms version: 5.0.0.2244
Xamarin.Forms.UWP: Target version: Windows 10, version 1903 (Build 18362)
Microsoft Visual Studio Enterprise 2019 Version 16.11.7
Target framework: Microsoft .NET Framework Version 4.8.04084
Operating system: Windows 10 Enterprise Version: 10.0.19043 Build 19043

**Comment by ajcvickers** [comment] 2021-12-02 20:56
Duplicate of #26574.

**Closed** 2022-10-16 20:17 UTC
Labels: closed-duplicate, customer-reported, area-adonet-sqlite
