### ISSUE TITLE
Migration bundle not honoring --connection setting

### ISSUE THREAD

**Issue by joer33304** [dotnet/efcore#26724] opened 2021-11-17 17:21 UTC
I am trying to execute my bundle with an explicitely set connection string (having different ones per environment) but using the --connection parameter it complains for missing app settings file is not optional:

efbundle --connection "Data Source=localhost\\SQLEXPRESS;Initial Catalog=mydb;Integrated Security=SSPI;"
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional.

**Comment by guillaume86** [comment] 2021-11-17 21:48
Related issue, "migrations remove" does not accept a --connection but does access the database.

**Comment by joer33304** [comment] 2021-11-18 16:24
> Related issue, "migrations remove" does not accept a --connection but does access the database.

I think it only doess access the db because you have an appsettings file ?

**Comment by ajcvickers** [comment] 2021-11-19 20:46
@joer33304 This message means that your "appsettings.json" file is needed to process the configuration in your application. (It's not actually a message from EF, but rather from the ASP.NET config code.) You can either change the configuration to not need appsettings (possibly only in a particular environment), or make sure that appsettings is available to the bundle. If you attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing, then we may be able to give more specific help.

@guillaume86 This is tracked by #24271.

**Comment by ajcvickers** [comment] 2021-11-28 14:13
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:15 UTC
Labels: closed-no-further-action, customer-reported
