### ISSUE TITLE
Disable lazy loading temporarily for a query

### ISSUE THREAD

**Issue by jamezamm** [dotnet/efcore#31158] opened 2023-06-29 14:41 UTC
Lazy loading is enabled by default in my web app. Whenever an entity type is JSON serialized, all navigation properties are loaded unless lazy loading is disabled. 

I would dislike to have to create separate classes for serialization just to prevent lazy loading from loading the navigation properties.

I am suggesting that when performing a query there would be an option to disable lazy loading for **ALL** navigation properties of both the queried entities and their related entities (the ones retrieved via **.Include()**).

`myDbContext.Set<Group>().Include(x => x.GroupUsers).EnableLazyLoading(false).ToList();`

The above would disable lazy loading for **ALL** navigation properties of both the **Group** and **GroupUser** entities.

**Comment by roji** [comment] 2023-06-30 13:45
@jamezamm I'm trying to understand your request; lazy loading usually designates that a navigation is **not** loaded by default, and only gets loaded when you access that property in C#, at the point when you access it ([see the docs](https://learn.microsoft.com/en-us/ef/core/querying/related-data/lazy)).

Above, it sounds like your problem isn't lazy loading, but rather the automatic loading of JSON columns ([the feature described here](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#json-columns)). Can you confirm that this is the problem you're asking to solve, and if so, what's the reason for not wanting the JSON data to be loaded automatically?

**Comment by jamezamm** [comment] 2023-07-01 10:37
@roji Thanks for replying.

Take the below as an example:

### The Entity Types
```
public class Group
{
	public string Id { get; set; }
	public string Description { get; set; }

	public virtual ICollection<GroupUser> GroupUsers { get; set; }
	public virtual ICollection<GroupPrivilege> GroupPrivileges { get; set; }
}
public class GroupUser
{
	public string GroupId { get; set; }
	public string UserId { get; set; }

	public virtual User User { get; set; }
}
public class GroupPrivilege
{
	public string GroupId { get; set; }
	public string PrivilegeId { get; set; }
}
```
### The Query

`List<Group> groups = myDbContext.Set<Group>().Include(x => x.GroupUsers).ToList();`

For the above query ONLY, I only desire the **Groups** and their **GroupUsers**. 

Now, I need the **groups** list to be serialized into json to be used in jQuery/Javascript. The process of serializing the **groups** list together with their group users will access the navigation properties **Group.GroupPrivileges** and **GroupUser.User**. 

Since I have lazy loading enabled by default on the dbcontext, both the navigation properties **Group.GroupPrivileges** and **GroupUser.User** will be fetched from the db, even tough I do not need them.

Since I want to avoid having to disable lazy loading entirely, I am suggesting a way to disable lazy loading per query basis.

`myDbContext.Set<Group>().Include(x => x.GroupUsers).EnableLazyLoading(false).ToList();`

Let me know if you need further clarification.

**Comment by ajcvickers** [comment] 2023-07-05 09:40
Duplicate of #12895

**Closed** 2023-07-07 16:54 UTC
Labels: closed-duplicate, customer-reported
