### ISSUE TITLE
EF 2.2 bug: Migration fails when changing the data type of an index

### ISSUE THREAD

**Issue by IndigoHealth** [dotnet/efcore#18879] opened 2019-11-13 01:40 UTC
Ran into this bug with .NET Framework 2.2. Just FYI, when I tried to repo it, I accidentally created the repo project with .NET Framework 3.0, and the problem didn't happen. But I'm stuck at 2.2 until an unrelated bug is fixed to allow me to upgrade to 3.0, so this problem affects me.

I created an index on a DateTime property. Then, I changed the property type to DateTimeOffset and created a new migration. When I try to update-database with the new migration, it fails with an error that says that the ALTER TABLE ALTER COLUMN command failed because one or more objects access the column.

**Repo**

1. In Visual Studio, create a new ASP.NET Core Web Application. Use ASP.NET Core 2.2, and change the Authentication to Individual User Accounts.

2. In Package Manager Console: `Update-Database`

3. Add a new entity class:

```
public class Widget
{
    public int Id { get; set; }
    public DateTime CreationDate { get; set; }
}

```
4. Add fluent configuration code to ApplicationDbContext.cs

```
public DbSet<Widget> Widgets { get; set; }

protected override void OnModelCreating(ModelBuilder builder)
{
    base.OnModelCreating(builder);

    builder.Entity<Widget>(e => {
        e.HasIndex(x => x.CreationDate);
    });
}

```
5. Add a new migration in Package Manager: `add-migration m_1`

```
using System;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace WebApplication2.Data.Migrations
{
    public partial class m_1 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Widgets",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    CreationDate = table.Column<DateTime>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Widgets", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Widgets_CreationDate",
                table: "Widgets",
                column: "CreationDate");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Widgets");
        }
    }
}
```
6. Change CreationDate from `DateTime` to `DateTimeOffset`:

```
public class Widget
{
    public int Id { get; set; }
    public DateTimeOffset CreationDate { get; set; } // Changed this line
}

```
7. Add another migration: `add-migration m_2'

```
public partial class m_2 : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AlterColumn<DateTimeOffset>(
            name: "CreationDate",
            table: "Widgets",
            nullable: false,
            oldClrType: typeof(DateTime));
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AlterColumn<DateTime>(
            name: "CreationDate",
            table: "Widgets",
            nullable: false,
            oldClrType: typeof(DateTimeOffset));
    }
}

```
8. Apply the new migrations: `update-database`

```
PM> update-database
Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.2.6-servicing-10079 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (33ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
Applying migration '20191113010739_m_1'.
Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '20191113010739_m_1'.
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (38ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [Widgets] (
          [Id] int NOT NULL IDENTITY,
          [CreationDate] datetime2 NOT NULL,
          CONSTRAINT [PK_Widgets] PRIMARY KEY ([Id])
      );
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE INDEX [IX_Widgets_CreationDate] ON [Widgets] ([CreationDate]);
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
      VALUES (N'20191113010739_m_1', N'2.2.6-servicing-10079');
Applying migration '20191113010819_m_2'.
Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '20191113010819_m_2'.
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (83ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      DECLARE @var0 sysname;
      SELECT @var0 = [d].[name]
      FROM [sys].[default_constraints] [d]
      INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
      WHERE ([d].[parent_object_id] = OBJECT_ID(N'[Widgets]') AND [c].[name] = N'CreationDate');
      IF @var0 IS NOT NULL EXEC(N'ALTER TABLE [Widgets] DROP CONSTRAINT [' + @var0 + '];');
      ALTER TABLE [Widgets] ALTER COLUMN [CreationDate] datetimeoffset NOT NULL;
System.Data.SqlClient.SqlException (0x80131904): The index 'IX_Widgets_CreationDate' is dependent on column 'CreationDate'.
ALTER TABLE ALTER COLUMN CreationDate failed because one or more objects access this column.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:86644b38-068b-44bb-bed7-37fe1d8cb930
Error Number:5074,State:1,Class:16
Failed executing DbCommand (83ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DECLARE @var0 sysname;
SELECT @var0 = [d].[name]
FROM [sys].[default_constraints] [d]
INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
WHERE ([d].[parent_object_id] = OBJECT_ID(N'[Widgets]') AND [c].[name] = N'CreationDate');
IF @var0 IS NOT NULL EXEC(N'ALTER TABLE [Widgets] DROP CONSTRAINT [' + @var0 + '];');
ALTER TABLE [Widgets] ALTER COLUMN [CreationDate] datetimeoffset NOT NULL;
System.Data.SqlClient.SqlException (0x80131904): The index 'IX_Widgets_CreationDate' is dependent on column 'CreationDate'.
ALTER TABLE ALTER COLUMN CreationDate failed because one or more objects access this column.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:86644b38-068b-44bb-bed7-37fe1d8cb930
Error Number:5074,State:1,Class:16
The index 'IX_Widgets_CreationDate' is dependent on column 'CreationDate'.
ALTER TABLE ALTER COLUMN CreationDate failed because one or more objects access this column.
```

**Comment by sbsw** [comment] 2019-11-13 01:57
I tested a workaround which seems to work: In the second migration, in both the `Up` and `Down` routines, I added a call to `DropIndex` before the `AlterColumn`, and I added a call to `CreateIndex` after the `AlterColumn`.

**Comment by bricelam** [comment] 2019-11-15 20:05
Duplicate of #12586?

**Comment by sbsw** [comment] 2020-03-29 18:43
On the subject of things you can do that would be REALLY helpful... Apparently, any new columns added to a class that inherits from another EF entity (for example, `ApplicationUser`, which inherits from `IdentityUser`) are added as **nullable** columns **even if the related C# property type is not nullable**. This means that running the scaffolded migration results in a NULL value in the new column in any existing rows, and, ultimately, a mysterious `NullReferenceException` when trying to retrieve the row. By way of example, suppose I add this property to my ApplicationUser class:

    public int MyInt { get; set; }

and my existing code has something like this to fetch data:

    var user = (from u in _db.Users
                      where u.Id = "xxx"
                      select u).FirstOrDefault();

After applying the migration, which added a NULL value to the new MyInt column in existing rows, this statement mysteriously starts throwing a `NullReferenceException`. The exception gives no clue that the underlying problem is the attempt to assign NULL to a non-nullable property, much less what the offending column (or property) might be.

There are a couple of things that the EF code could do to help in this situation.

1. If you scaffold a nullable column that maps to a non-nullable property, follow it with a commented-out SQL statement, like this:

        // If your underlying provider is SQL Server, the above statement results in
        // NULL values in existing rows. Any attempt to fetch a row that contains this
        // column will throw a NullReferenceException. You may wish to uncomment
        // and configure this statement to set a non-NULL value in existing rows:
        //migrationBuilder.Sql("UPDATE [dbo].[AspNetUsers] SET [MyInt] = 0");

2. It would be really helpful if EF would throw a more meaningful exception, with an indication that it can't assign NULL to a particular non-nullable property in a particular class.

**Comment by ajcvickers** [comment] 2020-03-30 15:26
@sbsw 

> Apparently, any new columns added to a class that inherits from another EF entity (for example, ApplicationUser, which inherits from IdentityUser) are added as nullable columns even if the related C# property type is not nullable.

TPH mapping of a hierarchy requires any column added for a derived type to be nullable because rows for other types will not have a value in that column. This is an inherent limitation of the TPH mapping.

**Closed** 2022-10-16 14:55 UTC
