### ISSUE TITLE
Paging with filter having a subentity collection

### ISSUE THREAD

**Issue by yepeekai** [dotnet/efcore#34847] opened 2024-10-07 19:36 UTC
EF adds order by to better keep track of parent and children when splitting queries.  But it adds the order to the wrong query when querying children entities.  Ex:

`context.Set<Parent>().Where(p => p.SomethingId == 8).Select(p => new { p.Id, children = p.Childs.Select(c => new { c.Id }) }).Take(25).ToListAsync()`

this query is splitted in 2, the first one go get the parents and is correct.

```
SELECT TOP(25) [p].[Id]
FROM [Parent] AS [p]
WHERE [p].[SomethingId] = 8
ORDER BY [p].[Id]
```

The second one use a sub query on the parent but the order by is on the outside query.  There is no order by where there is the select TOP

```
SELECT [c0].[Id], [c].[Id]
FROM (
    SELECT TOP(25) [p].[Id]
    FROM [Parent] AS [p]
    WHERE [p].[SomethingId] = 8
) AS [c]
INNER JOIN [Child] AS [c0] ON [c].[Id] = [c0].[ParentId]
ORDER BY [c].[Id]
```

It should be:

```
SELECT [c0].[Id], [c].[Id]
FROM (
    SELECT TOP(25) [p].[Id]
    FROM [Parent] AS [p]
    WHERE [p].[SomethingId] = 8
    ORDER BY [p].[Id]
) AS [c]
INNER JOIN [Child] AS [c0] ON [c].[Id] = [c0].[ParentId]
```

EF Core version: 8.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.11.2

**Comment by roji** [comment] 2024-10-10 08:14
Duplicate of #26808

**Closed by roji** 2024-10-10 08:14 UTC
Labels: customer-reported, area-query
