### ISSUE TITLE
Client side GroupBy is not supported.

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22743] opened 2020-09-24 23:13 UTC
Moved from discussion #22239.

### Question

From @karnik1110

i am trying to perform groupby() on northwind using linq

```C#
using(var ctx = new TempContext())
{
    var customer = (from s in ctx.Customers
                    group s by s.LastName into custByLN
                    select custByLN);
    foreach(var val in customer)
    {
        Console.WriteLine(val.Key);
        {
            foreach(var element in val)
            {
                Console.WriteLine(element.LastName);
            }
        }
    }
}
```

it has the following exception
System.InvalidOperationException: 'Client side GroupBy is not supported.'

refrence to tutorial page refered
https://www.entityframeworktutorial.net/querying-entity-graph-in-entity-framework.aspx

### Replies

From @smitpatel

See #19929
As the error message says, it is not supported. Since GroupBy is going to get all data of Customers table on client side anyway, you can use AsEnumerable to fetch whole table and apply GroupBy on client side yourself.

From @AndriySvyryd

@smitpatel We should add that to the message

From @smitpatel

Filed #22266

**Comment by smitpatel** [comment] 2020-09-25 03:46
Duplicate of #19929

**Closed** 2022-10-16 18:43 UTC
Labels: customer-reported
