### ISSUE TITLE
Howto update auto-implemented (by convention) many to many in Entity Framework Core 6 (.Net 6)?

### ISSUE THREAD

**Issue by bairog** [dotnet/efcore#29901] opened 2022-12-20 06:00 UTC
I use EF Core 6 and I have the following entites and context (simplified):
```
    public class Task
    {
       public Task()
       {
           PlaneTypes = new HashSet<PlaneType>();
       }

       public Int64 Id { get; set; }
       public String Name { get; set; }
       public virtual ICollection<PlaneType> PlaneTypes { get; set; }
    }

    public class PlaneType
    {
       public PlaneType()
       {
           Tasks = new HashSet<Task>();
       }

       public Int64 Id { get; set; }
       public String Name { get; set; }
       public virtual ICollection<Task> Tasks { get; set; }
    }

    public partial class PlanDbContext : DbContext
    {
        public PlanDbContext()   {   }

        public PlanDbContext(DbContextOptions<PlanDbContext> options)
            : base(options)   {   }

        public virtual DbSet<PlaneType> PlaneTypes { get; set; }        
        public virtual DbSet<Task> Tasks { get; set; }
        //some other DBSets

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlite("data source=DBPlanov.db;Pooling=False;");
                optionsBuilder.ConfigureWarnings(w => w.Throw(RelationalEventId.MultipleCollectionIncludeWarning));
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
             modelBuilder.Entity<Task>().HasIndex(t => new { t.Name }).IsUnique();
             modelBuilder.Entity<PlaneType>().HasIndex(pt => new { pt.Name }).IsUnique();
        }
```

As you can see I have no distinct entity for many-to-many table (it is [auto-implemented by EF Core 6](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#many-to-many) and I don't need to configure it - it is working without explicitly mapping the join table):
```
CREATE TABLE "PlaneTypeTask" (
        "PlaneTypesId" INTEGER NOT NULL,
        "TasksId" INTEGER NOT NULL,
        CONSTRAINT "PK_PlaneTypeTask" PRIMARY KEY ("PlaneTypesId", "TasksId"),
        CONSTRAINT "FK_PlaneTypeTask_PlaneTypes_PlaneTypesId" FOREIGN KEY ("PlaneTypesId") REFERENCES "PlaneTypes" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PlaneTypeTask_Tasks_TasksId" FOREIGN KEY ("TasksId") REFERENCES "Tasks" ("Id") ON DELETE CASCADE
    );
    
CREATE INDEX "IX_PlaneTypeTask_TasksId" ON "PlaneTypeTask" ("TasksId");
```
I've created a ConsoleApp to test my DbContext and emulate working in [disconnected scenario](https://learn.microsoft.com/en-us/ef/core/saving/disconnected-entities) (in fact I use that context in ASP NET Core 6 Web project - but that is simplified code):

```
    .....
    public class TaskEditModel
    {
        public Task Task { get; set; }

        //some other properties
    }  
    .....

    //emulate fetching my object from database on page load
    var CurrentTaskEditModel = new TaskEditModel();
    using (var context = new PlanDbContext())
    {
        //CurrentTaskEditModel.Task already has one PlaneType in PlaneTypes list - it is present in my database!!!
        CurrentTaskEditModel.Task = context.Tasks.Include(p => p.PlaneTypes).AsSplitQuery().First();
    }
    
    //emulate user edited Name on page
    CurrentTaskEditModel.Task.Name = "Edited name";
    
    //emulate saving object to database on post
    using (var context = new PlanDbContext())
    {
        using (var transaction = context.Database.BeginTransaction())
        {
            try
            {
                //emulate user added another PlaneType on page (with different PlaneType.Id of course)
                var planeTypeToAdd = context.PlaneTypes.Include(t => t.Tasks).AsSplitQuery().First();
                CurrentTaskEditModel.Task.PlaneTypes.Add(planeTypeToAdd);
    
                //Option1: NOT working - PlaneTypeTask table is NOT filled
                context.Attach(CurrentTaskEditModel.Task).State = EntityState.Modified;

                //Option2: NOT working also - SqliteException (SQLite Error 19: 'UNIQUE 
                //constraint failed: PlaneTypeTask.PlaneTypesId, PlaneTypeTask.TasksId')
                _context.Update(CurrentTaskEditModel.Task);

                context.SaveChanges();
                transaction.Commit();
            }
            catch (Exception ex)
            {
                transaction.Rollback();
            }
        }
    }
```
I load a Task (one PlaneType is already in a list). And I try to save it with edited name and with another PlaneType added to a list:
 1. If I use `Option1` - PlaneTypeTask table is not filled with an added PlaneType data.
 2. If I use `Option2` - UNIQUE constraint failed exception is thrown.
 3. If I comment both lines and use only `context.SaveChanges()` - no changes are saved to database at all.

I've expected auto-implemented many-to-many to just work without explicitly mapping the join table and directly working with it. But looks like something is wrong with my approach in general (the way I work with auto-implemented many-to-many). 
So what is my mistake? Thank you in advance.

### Include provider and version information
EF Core version: 6.0.12
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: NET 6.0
Operating system: Windows 10 Pro 22H2 x64
IDE: Visual Studio 2022 17.4.3

**Comment by ajcvickers** [comment] 2022-12-20 16:26
Duplicate of #28005.

@bairog This needs improvement--see #28005. For now, the best thing to do is attach the disconnected graph first, then mark entities as Modified as appropriate, and finally make changes to the graph. For example:

```C#
context.Attach(CurrentTaskEditModel.Task);
context.Entry(CurrentTaskEditModel.Task).State = EntityState.Modified;
CurrentTaskEditModel.Task.PlaneTypes.Add(planeTypeToAdd);
```

This then generated the following SQL:

```sql
INSERT INTO [PlaneTypeTask] ([PlaneTypesId], [TasksId])
VALUES (@p0, @p1);
UPDATE [Task] SET [Name] = @p2
OUTPUT 1
WHERE [Id] = @p3;
```

**Closed** 2023-01-04 12:56 UTC
Labels: closed-no-further-action, customer-reported
