### ISSUE TITLE
Entities for projection collection are tracked, but collection remains empty

### ISSUE THREAD

**Issue by mnissl** [dotnet/efcore#16817] opened 2019-07-29 15:32 UTC
This issue is basically a follow up of #16636.

```cs
var entities = context.Products.Select(p => new ProductWrapper(p)
  {
    UserName = p.UserNavigation.Name,
    Components = new MyCustomList<ComponentWrapper>(
      p.Components.Select(c => new ComponentWrapper(c)
      {
        UserName = c.UserNavigation.Name
      }))
  });
```
While EF Core 3 Preview 7 (opposed to EF Core 2.2) does track all related entities (context.ChangeTracker.Entries().Count() returns the correct number), the `Components` collection remains empty!

Using ToList() instead of newing up manually a collection works in turn:

```cs
var entities = context.Products.Select(p => new ProductWrapper(p)
  {
    UserName = p.UserNavigation.Name,
    Components = p.Components.Select(c => new ComponentWrapper(c)
      {
        UserName = c.UserNavigation.Name
      }).ToList()
  });
```
But I need to use `MyCustomList<T>` instead of `List<T>`.

### Further technical details
EF Core version: 3.0.0-preview7.19362.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1903
IDE: Visual Studio 2019 16.2.0

**Comment by ajcvickers** [comment] 2019-07-29 17:29
@smitpatel @maumar What is the expected behavior here when using a custom collection constructor?

**Comment by mnissl** [comment] 2019-07-30 07:24
> 
> 
> @smitpatel @maumar What is the expected behavior here when using a custom collection constructor?

I'd like to point out that `MyCustomList<T>` is not the issue; it also doesn't work with `new List<T>()`:

```cs
var entities = context.Products.Select(p => new ProductWrapper(p)
  {
    UserName = p.UserNavigation.Name,
    Components = new List<ComponentWrapper>(
      p.Components.Select(c => new ComponentWrapper(c)
      {
        UserName = c.UserNavigation.Name
      }))
  });
```
Combining `MyCustomList<T>` with `ToList()` doesn't work either:
```cs
var entities = context.Products.Select(p => new ProductWrapper(p)
  {
    UserName = p.UserNavigation.Name,
    Components = new MyCustomList<ComponentWrapper>(
      p.Components.Select(c => new ComponentWrapper(c)
      {
        UserName = c.UserNavigation.Name
      }).ToList())
  });
```

**Comment by smitpatel** [comment] 2019-07-30 17:43
Duplicate of #16318 

When we invoke `new List<>(...)` the passed in parameter is empty list, which we populate afterwards. Hence the created list (custom or not) remains empty.

**Closed** 2022-10-16 14:32 UTC
Labels: closed-duplicate, customer-reported
