### ISSUE TITLE
Why does Add-Migration sometimes create duplicate migrations?

### ISSUE THREAD

**Issue by joaorabelo** [dotnet/efcore#14652] opened 2019-02-08 17:37 UTC
Follow the question below on the stack!

https://stackoverflow.com/questions/19136066/why-does-add-migration-sometimes-create-duplicate-migrations

**Comment by smitpatel** [comment] 2019-02-08 18:49
@joaorabelo - Are you facing any issues? Can you provide more details? Also the question refers to EF (classic) and not EF Core.

**Comment by ajcvickers** [comment] 2019-02-15 17:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:51 UTC
Labels: closed-could-not-reproduce, customer-reported
