### ISSUE TITLE
Expose way for users to cast to any store type

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#11921] opened 2018-05-06 07:26 UTC
(previously discussed in https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/pull/315#discussion_r173611836)

In Npgsql, in some cases the same CLR type can be mapped to several store types. For example, string types are mapped to `text` by default, but they can also be mapped to `json` and even `citext`, PostgreSQL's case-insensitive string data type.

Everything works well for entity properties, where the fluent API can be used to specify the store type. However, the same is missing for other literals, parameters, etc. - users currently seem to have no way to manually specify that a string should be sent as a `json` or `citext` parameter rather than as a `text`. The current casting options all operate on CLR types, but in this case we really have only one CLR type and the cast operation cannot be represented.

To solve this, EF Core could expose an `EF.Functions.Cast()` which would accept an arbitrary store type, as a string. This would render into a simple SQL cast operation.

/cc @rwasef1830

**Comment by ajcvickers** [comment] 2018-05-07 19:06
@roji Closing this as a duplicate of #4978 since specifying the store type is conceptually the same as being able to specify some other "facet" of the mapping.

**Comment by roji** [comment] 2018-05-07 19:09
OK, thanks.

**Closed** 2022-10-16 12:23 UTC
Labels: closed-duplicate
