### ISSUE TITLE
Is there any way to configure a custom generic type to define a nullable navigation property ?

### ISSUE THREAD

**Issue by lucasteles** [dotnet/efcore#24957] opened 2021-05-22 22:49 UTC
I'm using EF Core with F# and it's common to use Option<T> types to define values that could be nullable.
I'm able to use it in simple columns and queries using  `ValueConverters` and  `IMemberTranslator`

But I could not find a way to use it in the navigation properties. The EF gives me this error when I tried to use it in the model definition:
```sh
The property 'Entity.OptionProperty' is of type 'FSharpOption<OptionProperty>' which is not supported by the current database provider. Either change the property CLR type, or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
```
Which makes sense, my entity is not a `FSharpOption<OptionProperty>`, it is an `OptionProperty`.

So, my question is, is there a way to customize how EF Core sees a navigation property? On the model definition and `.Includes()` to use the genetic type definition instead of the `FSharpOption`?

**Comment by bricelam** [comment] 2021-05-24 16:56
Duplicate of https://github.com/efcore/EFCore.FSharp/issues/29?

**Comment by lucasteles** [comment] 2021-05-24 18:19
@bricelam yes, looks like it is the same

**Closed** 2022-10-16 19:35 UTC
Labels: closed-duplicate, customer-reported
