### ISSUE TITLE
Issues with EF Core 8 Model Compilation

### ISSUE THREAD

**Issue by rzurlo** [dotnet/efcore#35305] opened 2024-12-10 15:39 UTC
I've encountered a couple of issues while working with EF Core 8 and compiling my model:

Ambiguous Reference for 'Version':
I have an entity named Version in my domain model (DomainModel.Entities.Version), but during compilation, I get the following error:
'Version' is an ambiguous reference between 'DomainModel.Entities.Version' and 'System.Version'.

Ambiguous Call for JsonSerializer.Deserialize:
I'm using the following configuration for a property in my entity:

entity.Property(e => e.TemplateData)
    .HasConversion(
        v => JsonSerializer.Serialize(v, (JsonSerializerOptions)null),
        v => JsonSerializer.Deserialize<List<TemplateDataModel>>(v, (JsonSerializerOptions)null))
    .IsRequired();

and this is in the entity: public List<TemplateDataModel> TemplateData { get; set; }

During compilation, I get this error:
"The call is ambiguous between the following methods or properties: 'JsonSerializer.Deserialize<TValue>(string, JsonSerializerOptions?)' and 'JsonSerializer.Deserialize<TValue>(string, JsonTypeInfo<TValue>)'".

It seems related to changes in APIs or EF Core 8 itself. Could you clarify if there’s a workaround or best practice for these situations?

EF Core version: 8
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 8.0)
Operating system: Windows 11
IDE: (e.g. Visual Studio 2022 17.12.3)

**Comment by ajcvickers** [comment] 2024-12-11 11:42
Duplicate of https://github.com/dotnet/efcore/issues/27203

**Comment by AndriySvyryd** [comment] 2024-12-11 23:01
The workaround is described in https://github.com/dotnet/efcore/issues/25523#issuecomment-902836615

**Closed by AndriySvyryd** 2024-12-11 23:01 UTC
Labels: customer-reported
