### ISSUE TITLE
Scaffold-DbContext does not emit warning messages for failed entity generation

### ISSUE THREAD

**Issue by Scaless** [dotnet/efcore#7682] opened 2017-02-22 16:32 UTC
When Scaffold-DbContext fails to generate an entity for a table it does not emit warning messages that describe why the generation failed.

After running Scaffold-DbContext this message is produced in the resulting DbContext:
```c#
// Unable to generate entity type for table 'dbo.TABLE'. Please see the warning messages.
```
However there are no actual warning messages in the Error List, Output Window, Package Manager Console, or any other file so I am unable to determine exactly why the generation failed.

### Steps to reproduce
Have a table that will fail to generate an entity (for example, missing a primary key)

Create a new C# .NET 4.5.2 Class Library project.
Install the EFCore packages:
```powershell
Install-Package Microsoft.EntityFrameworkCore.SqlServer
Install-Package Microsoft.EntityFrameworkCore.Tools –Pre
Install-Package Microsoft.EntityFrameworkCore.SqlServer.Design
```

Run Scaffold-DbContext
```powershell
Scaffold-DbContext "Server=servername;Database=dbname;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -Verbose
```

No warnings are generated except for the ones telling you to see the warning messages.

### Further technical details
EF Core version: 1.1.0, .NET 4.5.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 7
IDE: Visual Studio 2015 Update 3
SQL Server 2008 R2

**Comment by lajones** [comment] 2017-02-22 21:23
Looks like a dupe of #7315.

**Comment by rowanmiller** [comment] 2017-02-22 22:06
Updated title of #7315 to make it clear that it is about the larger problem.

**Closed** 2022-10-16 10:53 UTC
