### ISSUE TITLE
Cosmos DB Provider Identity Issues

### ISSUE THREAD

**Issue by tstampfel** [dotnet/efcore#20133] opened 2020-03-03 06:40 UTC
Once Cosmos DB Provider is connected and I try using SignInManager I get errors messages stating that it cannot translate "join" in SQL query. I understand that this was mentioned under limitations and that you guys are working hard to fix it, but it would be nice if this was resolved for all of us people that prefer NoSql.

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by AndriySvyryd** [comment] 2020-03-03 07:37
Duplicate of https://github.com/dotnet/aspnetcore/issues/15242

**Closed** 2022-10-16 18:14 UTC
Labels: closed-duplicate, customer-reported
