### ISSUE TITLE
EF Core 8 - please add HasOne to ComplexPropertyBuilder<T>

### ISSUE THREAD

**Issue by xeonix** [dotnet/efcore#32847] opened 2024-01-16 18:37 UTC
When using EF Core 8 `ComplexProperty` it would be nice to have a way to reference other entities from complex properties.
The idea is the same as we have with `OwnsOne` when owning property is not a separate entity but a subset of columns, logically grouped in a value object.
For this purpose we finally have `ComplexProperty` but it's missing something like that:
```C#
...
        builder.ComplexProperty(e => e.LastEdited, lastEditedBuilder =>
        {
            lastEditedBuilder.Property(e => e.ByUserId).HasColumnName("ByUserId");
            lastEditedBuilder.HasOne(e => e.ByUser).
                WithMany(e => EditedItems).
                HasPrincipalKey(e => e.UserId).
                HasForeignKey(e => e.ByUserId);
        });
...
```

**Comment by AndriySvyryd** [comment] 2024-01-17 21:56
Duplicate of https://github.com/dotnet/efcore/issues/31245

We are planning to do this eventually, but the configuration will be done through the entity type, something like
```C#
            builder.Entity<Post>().HasOne(e => e.LastEdited.ByUser).
                WithMany(e => e.EditedItems).
                HasPrincipalKey(e => e.UserId).
                HasForeignKey(e => e.LastEdited.ByUserId);
```

**Closed by AndriySvyryd** 2024-01-17 21:56 UTC
Labels: customer-reported
