### ISSUE TITLE
Writing SQL queries for non-entity types

### ISSUE THREAD

**Issue by shawn-show** [dotnet/efcore#19539] opened 2020-01-09 10:23 UTC
execute some raw sql query just like ef6

```csharp
var blogNames = context.Database.SqlQuery<string>(
                       "SELECT Name FROM dbo.Blogs").ToList();
```

**Comment by ajcvickers** [comment] 2020-01-10 22:45
Duplicate of #11624

**Closed** 2022-10-16 18:04 UTC
Labels: closed-duplicate, customer-reported
