### ISSUE TITLE
Entity State going from Added to Detached upon calling SaveChanges()

### ISSUE THREAD

**Issue by CoreySchnedl** [dotnet/efcore#19175] opened 2019-12-05 15:49 UTC
I detailed my issue here: https://stackoverflow.com/questions/59185286/entityframework-savechanges-moving-entitystate-from-added-to-detached?noredirect=1#comment104613472_59185286 

Are there any "gotchas" that I should be aware of as to why an entity would go from Added to Detached upon calling SaveChanges() while using an In Memory EF Core Database for Unit Testing?

Through debugging, I was able to figure out that it is ONLY happening upon the first Add/SaveChanges. Calling the same method a second time results in a successful, persisted insert.

**Comment by ajcvickers** [comment] 2019-12-05 22:55
@CoreySchnedl Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can fully investigate.

**Comment by ajcvickers** [comment] 2019-12-13 17:45
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 15:00 UTC
Labels: closed-could-not-reproduce, customer-reported
