### ISSUE TITLE
Support of parameterizied queries

### ISSUE THREAD

**Issue by KirylKiryanchykau** [dotnet/efcore#18015] opened 2019-09-24 10:04 UTC
Does FromSql() method support parameterizied queries?

My query looks like 
`$@"select f1, count(f2)
                    from t1
                    right join generate_series('dateTime.ToString("yyyy-MM-dd")'::timestamp, least(current_date, 'yyyy-MM-dd'), interval '{anyString}') AS g(date) on t1.something @> date
                    where t1.anyInt1 = {anyInt1} and t1.anyInt2 = {anyInt2}
                    group by date
                    order by date").ToListAsync();`

it could recognize int values, but couldn't recognize interpolated strings

Exception: `Failed executing DbCommand (19ms) [Parameters=[@p0='?', @p1='?' (DbType = Int32), @p2='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']`

I'd like to consume this one overload `public static IQueryable<TEntity> FromSql<TEntity>([NotNullAttribute] this IQueryable<TEntity> source, [NotNullAttribute][NotParameterized] FormattableString sql) where TEntity : class;`
But not this one `public static IQueryable<TEntity> FromSql<TEntity>([NotNullAttribute] this IQueryable<TEntity> source, [NotParameterized] RawSqlString sql, [NotNullAttribute] params object[] parameters) where TEntity : class;`

### Further technical details

EF Core version:
Database provider: (e.g. Npgsql.EntityFrameworkCore.PostgreSQL v2.2.4)
Target framework: (e.g. .NET Core 2.2)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.2.3)

**Comment by smitpatel** [comment] 2019-09-24 18:48
Duplicate of #10996

Closing this issue as we support parameterized queries with interpolated strings. In past it used to pick overload compiler thought was right hence you got wrong method. As a mitigation we split the method in 2 during 3.0 release. We are not going to make any changes in previous version.

cc: @roji if he knows how to pick desired method.

**Comment by roji** [comment] 2019-09-24 18:59
As @smitpatel wrote, this problem goes away in 3.0 as overloads have been renamed.

In previous versions, you should be able to select the overload by unambiguously passing a typed parameter:

```c#
FormattableString s = $"Some SQL Query.....";
ctx.FromSql(s);
```

**Closed** 2022-10-16 14:44 UTC
Labels: closed-duplicate, customer-reported
