### ISSUE TITLE
The binary operator Equal is not defined for the types 'System.Nullable`1[System.Int32]' and 'System.Object'.

### ISSUE THREAD

**Issue by kswoll** [dotnet/efcore#14987] opened 2019-03-11 20:30 UTC
Note, this is very similar to the issue I outlined here:

https://github.com/aspnet/EntityFrameworkCore/issues/13860

However, it's sufficently different I felt it worthwhile to file a new ticket.  Full repro steps at the end, but the gist is this snippet throws the error message in the subject:

```C#
            var container = await db.Containers
                .Select(x => new Container
                {
                    Targets = x.Targets.AsQueryable()
                        .Select(y => new ContainerTarget
                        {
                            Target = (y.Target.TypeA == null ? null : new TypeA())
                        })
                        .ToList()
                })
                .SingleAsync();
```

I tried to make it as simple as possible but this was the minimum to repro.

EF Core version: 3.0.0-preview3.19153.1
EF Core Sqlite version: 3.0.0-preview3.19153.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio 2019 Preview 4

**Workaround:**
Change: `Target = (y.Target.TypeA == null ? null : new TypeA())`
To: `Target = (y.Target.TypeAId == null ? null : new TypeA())`

i.e. change from an entity reference to the corresponding id property in the conditional check.

The full exception:

```
Unhandled Exception: System.InvalidOperationException: The binary operator Equal is not defined for the types 'System.Nullable`1[System.Int32]' and 'System.Object'.
   at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
   at System.Linq.Expressions.Expression.Equal(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
   at System.Linq.Expressions.Expression.MakeBinary(ExpressionType binaryType, Expression left, Expression right, Boolean liftToNull, MethodInfo method, LambdaExpression conversion)
   at System.Linq.Expressions.BinaryExpression.Update(Expression left, LambdaExpression conversion, Expression right)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ProjectionExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ProjectionExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileAsyncQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass22_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at EfCoreBug.Program.Main(String[] args) in C:\Users\kwoll\source\repos\EfCoreBug\EfCoreBug\Program.cs:line 37
   at EfCoreBug.Program.<Main>(String[] args)
```

Full example:

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

namespace EfCoreBug
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var dbConnection = new SqliteConnection("DataSource=:memory:");
            dbConnection.Open();
            var dbOptions = new DbContextOptionsBuilder<TestDb>()
                .UseSqlite(dbConnection)
                .Options;
            var db = new TestDb(dbOptions);
            db.Database.EnsureCreated();

            var dbTarget = new DbTarget
            {
                TypeA = new DbTargetTypeA()
            };
            var dbContainer = new DbContainer
            {
                Targets = new List<DbContainerTarget>()
            };
            dbContainer.Targets.Add(new DbContainerTarget
            {
                Target = dbTarget
            });
            db.Containers.Add(dbContainer);
            await db.SaveChangesAsync();

            var container = await db.Containers
                .Select(x => new Container
                {
                    Targets = x.Targets.AsQueryable()
                        .Select(y => new ContainerTarget
                        {
                            Target = (y.Target.TypeA == null ? null : new TypeA())
                        })
                        .ToList()
                })
                .SingleAsync();

        }
    }

    public class TestDb : DbContext
    {
        public DbSet<DbContainer> Containers { get; set; }

        public TestDb(DbContextOptions options) : base(options)
        {
        }
    }

    public class DbContainer
    {
        public int Id { get; set; }
        public List<DbContainerTarget> Targets { get; set; }
    }

    public class DbContainerTarget
    {
        public int Id { get; set; }
        public int TargetId { get; set; }

        public DbTarget Target { get; set; }
    }

    public class DbTarget
    {
        public int Id { get; set; }
        public int? TypeAId { get; set; }

        public DbTargetTypeA TypeA { get; set; }
    }

    public class DbTargetTypeA
    {
        public int Id { get; set; }
        
        public DbTarget Target { get; set; }
    }

    public class Target
    {
    }

    public class TypeA : Target
    {
    }

    public class ContainerTarget
    {
        public Target Target { get; set; }
    }

    public class Container
    {
        public List<ContainerTarget> Targets { get; set; }
    }
}
```

**Comment by smitpatel** [comment] 2019-12-10 00:10
Duplicate of #13860

**Closed** 2022-10-16 13:55 UTC
Labels: closed-duplicate, customer-reported
