### ISSUE TITLE
ASP.Net Core 3.1 Entity Framework 3.1.7 Stored Procedure

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#25428] opened 2021-08-04 19:22 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ASPNet-Core-31-Entity-Framework-317-/1476611)._

---
Dear Sirs,

Hope you can help,..
I am using ASP.Net Core 3.1 with Entity Framework 3.1.7.

I am confused: Having read some of the documentation on your website...
Please confirm whether ASP.Net Core 3.1, with Entity Framework 3.1.7, allow the use of Stored Procedures?

Thanks

Dave

---
#### Feedback Bot on 7/16/2021, 02:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2021-08-04 19:24
Please be more specific about how you want to use stored procedures.

**Comment by ajcvickers** [comment] 2021-08-12 16:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:42 UTC
Labels: closed-no-further-action, customer-reported
