### ISSUE TITLE
EF Core 2.0.1 Generating Nullable Timestamp Column

### ISSUE THREAD

**Issue by eriksendc** [dotnet/efcore#10357] opened 2017-11-20 22:54 UTC
Hi All,

I'm looking at a freshly created database after having upgraded to EF Core 2.0.1. I have one table that has a timestamp column. In my existing production and QA databases, the column is NOT NULL, and in a freshly created DB using 2.0.1 it is nullable.

Existing Prod & QA (created w/1.1.2):

    create table ...
    [Timestamp] [timestamp] NOT NULL,
    ....

New DB Freshly Created (w/2.0.1):

    create table ...
    [Timestamp] [timestamp] NULL,
    ....

No biggie, but I do like my SQL Compares to come out clean. So I tried changing the nullability using an alter column:

    alter table [dbo].[MeetUp] alter column [Timestamp] [timestamp] NULL

And that leads to an error:

    Msg 4927, Level 16, State 1, Line 13
    Cannot alter column 'Timestamp' to be data type timestamp.

I guess what I'm really looking for is help with migrating this change... I'm not really an expert enough to know why y'all changed the nullability.

Thanks!
-Brian Eriksen

### Further technical details
EF Core version: 1.1.2 & 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 update 4.4

**Comment by eriksendc** [comment] 2017-11-20 23:25
PS - The line of code that defines the column in my model class is:

    public byte[] Timestamp { get; set; }

and the line of code that configures / describes the Timestamp column is:

    builder.Entity<MeetUp>().Property(p => p.Timestamp).ValueGeneratedOnAddOrUpdate().IsConcurrencyToken();

**Comment by ajcvickers** [comment] 2017-11-21 17:14
Note for triage: In 1.1.2 I see this generated:
```sql
CREATE TABLE [MeetUps] (
    [Id] int NOT NULL IDENTITY,
    [Timestamp] rowversion,
    CONSTRAINT [PK_MeetUps] PRIMARY KEY ([Id])
);
```
I 2.0.1 I see this:
```sql
CREATE TABLE [MeetUps] (
    [Id] int NOT NULL IDENTITY,
    [Timestamp] rowversion NULL,
    CONSTRAINT [PK_MeetUps] PRIMARY KEY ([Id])
);
```

I'm guessing, but I haven't confirmed, that this is another consequence of #8146 in that the default is non null but now we are explicitly specifying it as null.

**Comment by ajcvickers** [comment] 2017-11-22 21:52
We discussed this in triage and decided:
* The new behavior is "correct" in that the property is nullable/optional in the model and so making in nullable/optional in the database reflect that.
* However, it shouldn't really matter in most cases because SQL Server is internally handling the value, so behavior is unlikely to change
* For normal use of Migrations, no new migration will be generated because there is no change in the nullability of the property in the model
* If an existing (old) database is reverse engineered, then the property will become required even if it wasn't originally created from a required property, but again this should not impact behavior.

So as of right now, this has become accidentally correct without any major consequences. If major consequences are discovered, then we can reconsider.

Closing as by-(accidental)-design.

**Comment by replaysMike** [comment] 2019-02-17 22:21
Thought I would contribute to this conversation as I was struggling to get this to work correctly, primarily due to a bug in `NumberToBytesConverter`.

My attempts to use `ulong` as my class RowVersion value, and the Timestamp type in SQL Server failed in multiple ways. Initially I was getting the column showing up as varbinary in SQL Server, and really what I wanted was the Timestamp type. I also don't want to use a byte[] in my class as it makes comparisons less straightforward. So in specifying the Timestamp type on the column, a ulong in my class, and having tried the suggestions above leads to EF throwing an error when fetching the data because for some reason it's being passed an empty or null byte array (I checked, all database rows have a populated timestamp value). Also, when specifying a `Timestamp` column type the auto-generated migration tries to apply a defaultValue which is invalid. Here's how I got it to work:

Table model definition:

```
public class MyTable {
  ...
  [Timestamp]
  public ulong RowVersion { get; set; }
}
```

DbContext:
```
builder.Entity<MyTable>()
                .Property(p => p.RowVersion)
                .HasConversion<byte[]>(v => BitConverter.GetBytes(v), v => BitConverter.ToUInt64(v != null && v.Length > 0 ? v : new byte[] { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }))
                .HasColumnType("Timestamp")
                .IsRowVersion();
```
Migration:
```
migrationBuilder.AddColumn<byte[]>(
  name: "RowVersion",
  table: "MyTable",
  type: "Timestamp",
  nullable: false);
  // defaultValue: new byte[] { }); -- remove this, invalid on a Timestamp type column
```

**Closed** 2022-10-16 11:59 UTC
Labels: closed-by-design
