### ISSUE TITLE
Keyless Entity (view) Navigation property with Actual entity  

### ISSUE THREAD

**Issue by NitishGawde** [dotnet/efcore#23542] opened 2020-12-01 05:48 UTC
**Code duplication And little hard to implement**: When I create the Keyless Entity (view) I need to add all same property which is already available in the Actual entity (table) 

ex.
```C#
Class Product
{
     [key]
     public int id {get;set;}

     public string name {get;set;}

    public string uom {get;set;}
//....
//....
//N numbers of properties
}

[Keyless]
Class Inventory
{
//I have to write all (depends on view) property which is already declare in Product class
      public int ProductId {get;set;}
      public Product Product {get;set;}
      public int Qty {get;set;}
//....
//....
//N numbers of properties
}


```

I think there should be something like this
**Suggestion** :
```C#
modelBuilder.Entity<Inventory>()
               .HasOne(p => p.Product)
               .WithMany(pv => pv.Inventories) // Depend on View
               .HasNavigationKey(nk => nk.ProductId);
```

**Comment by ajcvickers** [comment] 2020-12-02 19:33
@NitishGawde We discussed this, but it seems it would need new language features in C#, and possibly new capabilities in the .NET runtime, or are we missing how this can be done currently in C#?

**Comment by ajcvickers** [comment] 2020-12-15 16:56
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:13 UTC
Labels: closed-no-further-action, customer-reported
