### ISSUE TITLE
Entity Framework add migration won't add primary/foreign key drop methods before trying altering column 

### ISSUE THREAD

**Issue by manish1817** [dotnet/efcore#22544] opened 2020-09-15 12:25 UTC
Entity Framework seems to be not smart enough to detect primary/foreign key need to dropped and added again if altering primary/foreign column type is required.
It will just create dumb migration to alter column.
Resulting in failure on update-database.

Failed executing DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE [AspNetUsers] DROP CONSTRAINT [PK_AspNetUsers];
Microsoft.Data.SqlClient.SqlException (0x80131904): The constraint 'PK_AspNetUsers' is being referenced by table 'AspNetUserRoles', foreign key constraint 'FK_AspNetUserRoles_AspNetUsers_UserId'.
Could not drop constraint. See previous errors.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:c753db4b-6c2f-4397-b6f1-057cf43f05a8
Error Number:3725,State:0,Class:16
The constraint 'PK_AspNetUsers' is being referenced by table 'AspNetUserRoles', foreign key constraint 'FK_AspNetUserRoles_AspNetUsers_UserId'.
Could not drop constraint. See previous errors.

### Further technical details

EF Core version:3.1.8
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by bricelam** [comment] 2020-09-17 18:56
Duplicate of #16758 and #12586

**Closed** 2022-10-16 18:40 UTC
Labels: customer-reported
