### ISSUE TITLE
Improve exception message when reconfiguring an owned type

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#27705] opened 2022-03-25 12:22 UTC
It seems like the configuration _(Fluent API)_ for an Owned type entity is ignored. I've change the configuration for the `UserData` entity from normal _(User and UserData had their own configs)_ to owned type (now owned by User entity).

Strangely it's now changing all columntypes and some other stuff which was configured correctly before to "longtext" and also ignoring additional attributes like non-nullable (`IsRequired()`).

I couldn't find helpful solutions and tried different ways (except Attributes inside the class) without luck. Am I missing something here?

### EF Core entity configuration inside `User` entity

```C#
internal class UserConfiguration : IEntityTypeConfiguration<User>
{
  public void Configure(EntityTypeBuilder<User> builder)
  {
    // additional code removed for brevity

    builder.OwnsOne(user => user.UserData, build =>
    {
      build.ToTable("UserData");

      build.HasKey(x => x.Id);
      build.Property(x => x.Id).ValueGeneratedOnAdd();

      // every config here results in change to "longtext" inside migration script
      build.Property(x => x.Salutation).HasColumnType("varchar(15)").IsRequired();
      build.Property(x => x.FirstName).HasColumnName("FirstName").HasColumnType("varchar(50)").IsRequired();
      build.Property(x => x.Gender).HasColumnName("Gender").HasMaxLength(50).IsRequired();
      build.Property(x => x.FamilyName).HasMaxLength(50).IsRequired();
      build.Property(x => x.BirthName).HasMaxLength(50);
      });
    }
  }
}
```

### EF Core created migration script (copy&paste of related parts)

```C#
 migrationBuilder.AlterColumn<string>(
   name: "UserId",
  table: "UserData",
  type: "varchar(22)",
  maxLength: 22,
  nullable: false,
  oldClrType: typeof(int),
  oldType: "int")
  .Annotation("MySql:CharSet", "utf8mb4");

migrationBuilder.AlterColumn<string>(
  name: "Salutation",
  table: "UserData",
  type: "longtext",
  nullable: true,
  oldClrType: typeof(string),
  oldType: "varchar(15)",
  oldMaxLength: 15)
  .Annotation("MySql:CharSet", "utf8mb4")
  .OldAnnotation("MySql:CharSet", "utf8mb4");

migrationBuilder.AlterColumn<string>(
  name: "FirstName",
  table: "UserData",
  type: "longtext",
  nullable: true,
  oldClrType: typeof(string),
  oldType: "varchar(50)",
  oldMaxLength: 50)
  .Annotation("MySql:CharSet", "utf8mb4")
  .OldAnnotation("MySql:CharSet", "utf8mb4");

migrationBuilder.AlterColumn<string>(
  name: "Gender",
  table: "UserData",
  type: "longtext",
  nullable: true,
  oldClrType: typeof(string),
  oldType: "varchar(100)",
  oldMaxLength: 100)
  .Annotation("MySql:CharSet", "utf8mb4")
  .OldAnnotation("MySql:CharSet", "utf8mb4");

migrationBuilder.AlterColumn<string>(
  name: "FamilyName",
  table: "UserData",
  type: "longtext",
  nullable: true,
  oldClrType: typeof(string),
  oldType: "varchar(50)",
  oldMaxLength: 50)
  .Annotation("MySql:CharSet", "utf8mb4")
  .OldAnnotation("MySql:CharSet", "utf8mb4");

migrationBuilder.AlterColumn<string>(
  name: "BirthName",
  table: "UserData",
  type: "longtext",
  nullable: true,
  oldClrType: typeof(string),
  oldType: "varchar(50)",
  oldMaxLength: 50,
  oldNullable: true)
  .Annotation("MySql:CharSet", "utf8mb4")
  .OldAnnotation("MySql:CharSet", "utf8mb4");
```

EF Core version: 6.0.3 (latest)
Database provider: Pomelo.EntityFrameworkCore.MySql (latest)
Target framework: .NET 6.0
Operating system: Wndows 11
IDE: JetBrains Rider 2021.3.3 or VS 2022 17.1.2 (doesn't matter)

**Comment by ajcvickers** [comment] 2022-04-01 11:23
@DanielDudda I am not able to reproduce this. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ddudda174** [comment] 2022-04-05 09:42
@ajcvickers thanks for looking at it.

I've reduced the original project's code to only contain the required parts to show this bug. Here's a [link](https://github.com/ddudda174/ef-core-migrations-bug).

I'm using docker compose to run the MariaDB server instance and connect to the .net project. Maybe it has something to do with or it some configurations I have?

**Comment by ajcvickers** [comment] 2022-04-19 13:43
@ddudda174 Given that GitHub repo, what are the steps to reproduce what you are seeing? (I get unrelated errors attempting to start the app.)

**Comment by ajcvickers** [comment] 2022-04-20 09:05
@ddudda174 Does that bad model get created when you run the application, or only when you create the migration?

**Comment by ddudda174** [comment] 2022-04-20 12:19
@ajcvickers what do you mean by bad model? The entity PersonalData was created by me, and setup inside the [UserConfig](https://github.com/ddudda174/ef-core-migrations-bug/blob/main/EfCoreOwnedType.Data/Configurations/UserConfiguration.cs) class with OwnsOne. After that I run the ef core command (e.g. Add-Migration TestOwnedTypeConfig) to generate the [migration file](https://github.com/ddudda174/ef-core-migrations-bug/blob/main/EfCoreOwnedType.Data/Migrations/20220405093110_Initial.cs) which comes up with the longtext column types instead of for example varchar(64) for property "FirstName". When I simply run the app(without creating a migration and running Update-Database) then it will cause exceptions which lead to "the database does not fit the current model" error message. Am i missing something here?

**Comment by ajcvickers** [comment] 2022-04-26 10:32
@ddudda174 The issue here is that the code is configuring `PersonalData` as an owned type, but then also configuring it as a non-owned type in `SeedAdmin`, and then attempting to suppress the error that this generates by completely ignoring it in `AppDbContext`. Since it is ignored, it probably shouldn't be included in the model at all, and hence there should be no table creation for it in the migration--so this is likely a bug. However, the real issue here is that `PersonalData` can't be both configured as an owned type, and then later used as a non-owned type for seeding.

**Comment by ddudda174** [comment] 2022-04-26 10:45
@ajcvickers Just saw that owned types should be seeded after a `OwnsOne` call, correct? So my common seeding inside `SeedAdmin` with `HasData` causes it to be recognized as non-owned type (thought using anonymous object on seeding is enough/ok)? EF Core came up with the error that it is configured as non-owned type and cannot be used as owned type and I should add ignore if I don't want to use it as non-owned type. That's why I added it as I couldn't see why it was using it as non-owned type. So I try to change it to the correct seed method, but will be annoying to scather around seed data across all entities instead of using centralized methods.

> Since it is ignored, it probably shouldn't be included in the model at all, and hence there should be no table creation for it in the migration--so this is likely a bug

At least I could unveal a probably real bug :D

**Comment by ajcvickers** [comment] 2022-04-26 10:49
Note for triage: we should look at the working of the owned and non-owned message, since Ignore is very rarely the way to solve this.

> The entity type '{entityType}' cannot be configured as owned because it has already been configured as a non-owned. If you want to override previous configuration first remove the entity type from the model by calling 'Ignore'.  See https://aka.ms/efcore-docs-owned for more information and examples.

@ddudda174 

> At least I could unveal a probably real bug :D

I doubt we will fix this, since it requires a completely invalid configuration in order to get into this situation.

**Comment by ddudda174** [comment] 2022-04-27 11:11
@ajcvickers you can close this issue if you want (or keep it open for the non-owned message rework), I fixed the configuration and it's now working. Thanks for your help!

Just one more question: Is it ok to use `OwnsOne` twice to separate [configuration](https://github.com/ddudda174/ef-core-migrations-bug/blob/79531d7d235b160a6a325a5a215f9730660dae6f/EfCoreOwnedType.Data/Configurations/UserConfiguration.cs#L23) and [data seeding](https://github.com/ddudda174/ef-core-migrations-bug/blob/79531d7d235b160a6a325a5a215f9730660dae6f/EfCoreOwnedType.Data/Extensions/ModelBuilderExtensions.cs#L59) or should I better merge the calls (already tests and it's working, just wondering for best practice)?

**Closed** 2023-11-14 00:37 UTC
Labels: type-enhancement, closed-fixed, customer-reported, area-model-building
