### ISSUE TITLE
More specific exceptions to abstract database backend

### ISSUE THREAD

**Issue by glen-84** [dotnet/efcore#2044] opened 2015-04-22 08:36 UTC
See: https://entityframework.codeplex.com/workitem/1270

Doctrine's DBAL has this: https://github.com/doctrine/dbal/pull/458/files

**Comment by arangas** [comment] 2015-04-30 02:49
Yes - this seems related to #2017 (my issue) and #1808.

**Comment by rowanmiller** [comment] 2015-05-15 22:36
Duplicate of https://github.com/aspnet/EntityFramework/issues/2017

**Closed** 2022-10-16 08:55 UTC
