### ISSUE TITLE
Sqlite.NetTopologySuite caused the program to crash. Failure module:libwinpthread-1.dll

### ISSUE THREAD

**Issue by d79ima** [dotnet/efcore#25134] opened 2021-06-21 19:48 UTC
Added package Microsoft. EntityFrameworkCore.Sqlite
It works

Added package
Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite
App crashes after ~530 SQLite reads in a loop.

EF Core version: 5.0.7
Database provider: SQLite
Target framework: .NET Core 3.1
Operating system: Windows 10 x64
IDE: Visual Studio 2019 16.9.3

Attached small test solution that easily reproduces the app crash.
Also tested this test app on a clean Windows 10 environment with no Visual Studio installed, same crash.

[TestNetTopologySuite.zip](https://github.com/dotnet/efcore/files/6689123/TestNetTopologySuite.zip)

**Comment by AndriySvyryd** [comment] 2021-06-23 20:06
Duplicate of https://github.com/dotnet/efcore/issues/14561

**Closed** 2022-10-16 19:37 UTC
Labels: closed-duplicate, customer-reported
