### ISSUE TITLE
Cannot recreate database

### ISSUE THREAD

**Issue by geedsen** [dotnet/efcore#12691] opened 2018-07-17 15:04 UTC
I had a database, but wanted to start from scratch. So I deleted all Migrations and deleted the DB in sqlsrver (in Azure) '. I deleted the Migrations and created a new initial migration. Then I did a database update. It tells me the databse does already exist. (but I cannot see it in SQL studio). Here the commands I tried:
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
``` console
PS C:\WINDOWS\system32> cd D:\Users\Ben\Source\Repos\Xpndr\EF
PS D:\Users\Ben\Source\Repos\Xpndr\EF> dotnet ef database drop
Are you sure you want to drop the database 'xpndr' on server 'tcp:quadronc.database.windows.net,1433'? (y/N)
y
Entity Framework Core 2.1.1-rtm-30846 initialized 'XpndrContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: CommandTimeout=600
Dropping database 'xpndr'.
Database 'xpndr' did not exist, no action was taken.
PS D:\Users\Ben\Source\Repos\Xpndr\EF> dotnet ef database update
Failed executing DbCommand (10,268ms) [Parameters=[], CommandType='Text', CommandTimeout='600']
CREATE DATABASE [xpndr];
System.Data.SqlClient.SqlException (0x80131904): Database 'xpndr' already exists. Choose a different database name.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject st
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:23cd098c-4ee5-4c8f-ae5a-f9ed3fbb8e24
Error Number:1801,State:1,Class:16
Database 'xpndr' already exists. Choose a different database name.
PS D:\Users\Ben\Source\Repos\Xpndr\EF>
```

So it cannot find it when deleting, but when creating it says it is already there.

Trying this in SQL studio: CREATE DATABASE [xpndr];
Same Error. But the Database is not there.
Checking the Azure portal, the database is not visible in the list of databases, but it is visible in the deleted databases (3 times, I did delete and recreated it successfully before).

**Comment by divega** [comment] 2018-07-17 19:29
@geedsen can you try connecting to the database and creating it again without using EF Core? It looks like what you are seeing is Azure SQL Database behavior, independent of EF Core. Our hypothesis is that it is just taking a long time for Azure SQL Database to update its internal state to reflect the fact that the database does not exist anymore.

**Comment by ajcvickers** [comment] 2018-07-25 19:07
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:19 UTC
Labels: closed-could-not-reproduce, customer-reported
