### ISSUE TITLE
Using DateTime.Now in linq query generates difference SQL based on value is inlined or passed through variable

### ISSUE THREAD

**Issue by mshanak** [dotnet/efcore#12338] opened 2018-06-12 13:47 UTC
I had a weird issue when using the Dates in entity framework LINQ query,  the problem is when I use the  ``DateTime.Now.AddDays(-1) `` inside the LINQ directly the output SQL query is different from the output of the same query but when I declared the  ``DateTime.Now.AddDays(-1) `` as a variable .

### CASE1: 👎  
 when using the  ``DateTime.Now.AddDays(-1) `` or ``DateTime.Now.AddHours(+12)`` in Where condition in the query directly, the SQL output does not contain all constraines.
```c

  var Ids = MyProjects.Select(x => x.Id);  //array of id's [4,6,7]
        var MyTasks = _context.projectTasks.Where(y => Ids.Contains(y.ProjectId)
// the following lines
        &&  y.TaskDate >= DateTime.Now.AddDays(-1) &&
           y.TaskDate < DateTime.Now.AddHours(+12) &&

           y.Status == ProjectTaskStatus.open)
           .GroupBy(x=>x.ProjectId).ToList();
```
Output SQL

```sql
SELECT "y"."id", "y"."project_id", "y"."status", "y"."task_date", "y"."title"
     FROM "pr_project_task" AS "y"
   WHERE "y"."status" = 0
/* where  is the  y.TaskDate conditions ???*/
```

### CASE2:  👍 
When I declared  ``DateTime.Now.AddDays(-1) `` and ``DateTime.Now.AddHours(+12)``   as variables, the output SQL was as follow:

```c

     var Ids = MyProjects.Select(x => x.Id); //array of id's [4,6,7]
// declared the dates as variabes
        var date_start = DateTime.Now.AddDays(-1);
        var date_end = DateTime.Now.AddHours(+12);

        var MyTasks = _context.projectTasks .Where(y =>
          Ids.Contains(y.ProjectId)
                  && y.TaskDate >=date_start &&
           y.TaskDate < date_end &&
           y.Status == ProjectTaskStatus.open)
           .GroupBy(x=>x.ProjectId).ToList();
```
Output SQL

```SQL
SELECT "y"."id", "y"."project_id", "y"."status", "y"."task_date", "y"."title"
     FROM "pr_project_task" AS "y"
/* the where contains all constraines */
     WHERE (("y"."project_id" IN (4, 6, 7) 
                    AND ("y"."task_date" >= @__date_start_1)) 
                    AND ("y"."task_date" < @__date_end_2)) 
                    AND ("y"."status" = 0)

     ORDER BY "y"."project_id"

```

is there any explanation?

**Comment by pmiddleton** [comment] 2018-06-12 14:38
Ok I want to partially take back what I just said - it appears translators for AddDays and AddHours were added for Sql Server.  

@mshanak - What database are you running against?

**Comment by SSkovboiSS** [comment] 2018-06-12 15:27
It looks like SQLite provider.
Translation of DateTime.AddXXX methods for SQLite is already implemented(see #10525), but is a part of 2.2.0 milestone.

**Comment by mshanak** [comment] 2018-06-12 15:28
I am using  postgress, should i move this issu to the postgress dotnet library ?

**Comment by pmiddleton** [comment] 2018-06-12 15:34
@roji - I'm guessing Postgres does not translate those methods yet?

**Comment by roji** [comment] 2018-06-12 20:20
The latest versions of the Npgsql provider does translate `DateTime.Add{Hours,Days}()` - but can you  please check (and post) the version you're using to make sure?

Also, can you please try to evaluate `DateTime.Now` outside of the query, but call `Add{Hours,Days}()` on the resulting value inside the query? This will isolate things and tell us whether the problem is with `DateTime.Now` or with the `Add` methods.

**Comment by mshanak** [comment] 2018-06-13 13:08
### Package versions:

![postgress](https://user-images.githubusercontent.com/964266/41352924-6ffbe1ae-6f23-11e8-880e-3947f17ea2e7.png)




### Experiment:
when I moved the ```Add{Hours, Days}()``` inside the query, every thing worked fine. I think the problem is that the driver does not translate the ```DateTime.Now``` .

```c#



var Ids = MyProjects.Select(x => x.Id); //array of id's [4,6,7]
// declared the dates as variabes
        var date_start = DateTime.Now;
        var date_end = DateTime.Now;

        var MyTasks = _context.projectTasks .Where(y =>
          Ids.Contains(y.ProjectId)&& 

         y.TaskDate >=date_start.AddDays(-1) &&
           y.TaskDate < date_end.AddHours(+12) &&

           y.Status == ProjectTaskStatus.open)
           .GroupBy(x=>x.ProjectId).ToList();


```

output 
```sql
    SELECT "y"."id", "y"."project_id", "y"."status", "y"."task_date", "y"."title"
     FROM "pr_project_task" AS "y"
                    WHERE (("y"."project_id" IN (4,6,7) 
                    AND  ("y"."task_date" >= @__AddDays_1)) 
                    AND ("y"."task_date" < @__AddHours_2)) 
                    AND ("y"."status" = 0)


      ORDER BY "y"."project_id"

```

**Comment by pmiddleton** [comment] 2018-06-13 14:48
@mshanak - I don't see the date math happening in the query.

Is it possible to upgrade to the latest 2.1 version of ef core and the postgre driver to see if that resolves the issue?

**Comment by tuespetre** [comment] 2018-06-13 16:33
This seems more like an issue with 'funcletization'. IMO the 'core' relational processing bits should be lifting those expressions out for runtime evaluation and application to `DbParameter`s.

**Comment by smitpatel** [comment] 2018-06-13 17:07
> This seems more like an issue with 'funcletization'.

Not an issue. 😄 

When you declare `date_start` outside of query, the value of `date_start.AddDays(-1)` is still independent of results, so it is precomputed and sent to server as DbParameters. So that you can reuse the same query cache with changed parameters. Declaring `DateTime.Now` or `DateTime.Now.AddDays(-1)` as variable would not change SQL. Since both of them can be computed without going to server. As @pmiddleton noted above, it could have differences in time zone which can change results.
If you want to use server based time computations then you need to inline `DateTime.Now` inside the linq, which will not be evaluated on client side (since non-deterministic nature based on time zone) and will be translated to server.

Closing this as difference in original SQLs are because of lack of translators in postgre which is already fixed in latest version as per @roji.
And difference between inline/variable is explained above.

There is no functional issue or actionable item on EF side.

**Comment by tuespetre** [comment] 2018-06-13 17:27
> If you want to use server based time computations then you need to inline DateTime.Now inside the linq, which will not be evaluated on client side (since non-deterministic nature based on time zone) and will be translated to server.

I see. From the viewpoint of one who regularly authors LINQ queries for business applications, I'll say that declaring a variable up front to hold `DateTime.Now` and using `DateTime.Now` in the query itself come across to me as having the exact same semantics. Something about the 'principle of least astonishment' and the 'pit of success'.

**Comment by smitpatel** [comment] 2018-06-13 17:50
@tuespetre - You can call it surprise effect or limitation of expression tree. Once you define variable and use it inside the expression tree, you lose the ability to look at the definition of the variable. At that point to "match" semantics, all we can do is to make parameter for both cases instead of server translation.

But then there are customers out there who wants to use server based computations since their servers are in different timezone (not uncommon in cloud era). To go down yet another surprise, if you are running async queries, variable will get assigned before the query get scheduled. Which effectively blocks a way to run a query which upto certain point reliably based on current time. Arguably, translating to server for inline case (we would have done for variable case if that was possible), is avoiding 'pit of failure'

**Comment by pmiddleton** [comment] 2018-06-13 18:34
Ok I didn't realize the entire function call could be lifted out of the query in this case.  

@smitpatel is that specific to DateTime.Now or to any function call that can be precomputed?

**Comment by smitpatel** [comment] 2018-06-13 19:37
@pmiddleton - Anything which is not dependent on range variable (basically server values) would be evaluated on client side and sent as parameter to server. Except for a small set of functions/members which we know are non-deterministic (like DateTime.Now), they are excluded from funcletization. Here is the file which has exclusions. https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore/Query/Internal/EvaluatableExpressionFilter.cs

**Comment by smitpatel** [comment] 2018-06-13 19:38
Here is relational version https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Relational/Query/Internal/RelationalEvaluatableExpressionFilter.cs which you added to avoid evaluation of DbFunctions. :trollface:

**Comment by tuespetre** [comment] 2018-06-13 19:41
> At that point to "match" semantics, all we can do is to make parameter for both cases instead of server translation.

Yes! 😉 

It really doesn't bother me if `DateTime.Now` inline is translated to SQL *when it can be*, but in this case I'm saying they should be lifted out into expressions that are applied as parameters at runtime. In my project I use a 'second-chance' parameterization expression visitor to try and compensate for anything that couldn't be rewritten to the server before resorting to client evaluation.

> Except for a small set of functions/members which we know are non-deterministic (like DateTime.Now), they are excluded from funcletization.

Do you mean they are excluded from *partial evaluation*? I thought 'funcletization' was just replacing expression subtrees with placeholder parameters.

**Comment by smitpatel** [comment] 2018-06-13 20:10
@tuespetre - Good case. We would run into it if providers have Add* functions translated but not `DateTime.Now` where we could generate parameters for that and still use Add* translation to send to server instead of full client eval. Though due to good provide writers we haven't run into that issue. So currently, for inline case, it does not create parameter and translate to server anyway.

> Do you mean they are excluded from partial evaluation? 
They are same thing just looked from different angles. We partially evaluate expression when we can and replace the subtree with parameter.

**Comment by 491134648** [comment] 2019-11-23 10:42
Can I turn off the related conversion?

**Closed** 2022-10-16 12:30 UTC
Labels: closed-no-further-action, customer-reported
