### ISSUE TITLE
DbContext.SaveChanges Error with DI

### ISSUE THREAD

**Issue by arunprasathv** [dotnet/efcore#15313] opened 2019-04-10 21:29 UTC
@smitpatel @AndriySvyryd 
SaveChanges(true) throws following error when we inject DB context  in the constructore(.Net Core API). Even after calling ChangeTracker.AcceptAllChanges, still get the same error. 

However, works fine when I create a new context wrapped in using {}. in this case its a new instance of context not the injected one from the startup. I don't want to create an instance every time rather would prefer using injected context. 

**DI in Startup**

services.AddDbContextPool<CBContext>(options =>
            {
                options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
#if DEBUG
                options.UseLoggerFactory(loggerFactory);
#endif
                options.UseSqlServer(connectionString);
            }
            );
            services.AddScoped<IDbContext, CBContext>();

**Error**

The instance of entity type 'Billing' cannot be tracked because another instance with the same key value for {'BillingId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

**Comment by AndriySvyryd** [comment] 2019-04-10 21:37
@arunprasathv You shouldn't have an additional `AddScoped` call for the context:
```C#
services.AddDbContextPool<IDbContext, CBContext>(options =>
{
	options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
	#if DEBUG
	options.UseLoggerFactory(loggerFactory);
	#endif
	options.UseSqlServer(connectionString);
	}
);
```

**Comment by arunprasathv** [comment] 2019-04-12 16:18
This issue still exists after making this change.. it only works when i create context explicitly every time. 
@smitpatel @AndriySvyryd @ajcvickers

**Comment by ajcvickers** [comment] 2019-04-12 16:42
@arunprasathv Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-04-19 16:15
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:17 UTC
Labels: closed-could-not-reproduce, closed-no-further-action, customer-reported
