### ISSUE TITLE
Flaky test: CreateAsync_checks_for_existence_and_retries_if_cannot_open_file_until_it_passes

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/efcore#10506] opened 2017-12-07 18:51 UTC
This test sometimes fails as seen [here](http://aspnetci/viewLog.html?buildId=363348&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win10Universe#testNameId1270270944336818636).

**Comment by ajcvickers** [comment] 2017-12-11 22:12
Duplicate of #9031

**Closed** 2022-10-16 12:02 UTC
