### ISSUE TITLE
Collection of primitives to JSON column --> Navigation

### ISSUE THREAD

**Issue by E-PressSend** [dotnet/efcore#33585] opened 2024-04-22 02:48 UTC
Assuming my entities are like:

````
public class EntityA
{
    public int Key { get; set; }
    public IList<int> EntityBIds { get; set; } // List of IDs of related EntityB objects
    public ICollection<EntityB> EntityBs { get; set; } // Navigation property
}

public class EntityB
{
    public int Key { get; set; }
    public ICollection<EntityA> EntityAs { get; set; } // Navigation property
}
````

and EntityA.EntityBIds is set to be a JSON column using 
````
                entity.Property(e => e.EntityBIds ).IsUnicode(false);

````

How can I set up a Navigation bewteen EntityA and EntityB using EntityBIds?

Is it even possible?

Thanks and Regards

**Comment by AndriySvyryd** [comment] 2024-04-26 19:37
Duplicate of #30551

**Closed by AndriySvyryd** 2024-04-26 19:37 UTC
Labels: customer-reported
