### ISSUE TITLE
OnModelCreating not being called with DBSet's on DbConxted extended class

### ISSUE THREAD

**Issue by generik0** [dotnet/efcore#12948] opened 2018-08-09 09:24 UTC
Hi
Thanks for the EF Core. Its nice.
I have a very strange problem. I have some entity models and configurations i have converted from EF6 and made to nuget packages. When i add  any of these entities as a dsbet, the OnModelCreating does not get triggered (i do not have an IModel in the OnConfiguring).
The OnConfiguring does get called.

### Steps to reproduce

0. Add a net core generic host
1. Add the nuget pack with entities to a net standard projekt, referenced by the generic host
2. Add a dbcontext extended class
3. Add "protected override void OnModelCreating(ModelBuilder modelBuilder)"
4. Run host. OnModelCreating will be triggered
5. Add a DBSet with a entity from the nuget package
5. Run host. OnModelCreating will not be triggered

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer, with connectionstring from app.config
Operating system: WIn10, 
IDE: VS 15.7.6

I can provide you the nuget package via email.. Please contact me. They are private...

**Comment by ajcvickers** [comment] 2018-08-09 20:43
@generik0 Can you explain a bit more what you mean by, "OnModelCreating does not get triggered"? There isn't really anything that "triggers" OnModelCreating. It is typically run once the first time the context is used to build the model.

**Comment by generik0** [comment] 2018-08-10 04:35
@ajcvickers i know it looks and Sounds Weird. But the override OnModelCrearing does not run once. Ie it never triggers. Almost like there is an exception that I don’t get deep down in er core that doesn’t propagate up. Or something else very bad is happening...

**Comment by ajcvickers** [comment] 2018-08-10 16:17
@generik0 I think for us to be able to make progress on this we are going to need a small repro project that demonstrates the behavior you are seeing.

**Comment by generik0** [comment] 2018-08-10 16:24
@ajcvickers yes, I thought you might ask for that :-) . I will try to get something pulled out ASAP. I also have to insure the repo is private. Maybe I can add you to a vsts git repo?

**Comment by ajcvickers** [comment] 2018-08-17 17:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:24 UTC
Labels: closed-could-not-reproduce, customer-reported
