### ISSUE TITLE
Generation of check constraints for enum mappings fails for owned types

### ISSUE THREAD

**Issue by henrikdahl8240** [dotnet/efcore#20866] opened 2020-05-06 22:12 UTC
Very simple model:
```
public enum ChainMaterialKind
{
    Steel,
    Carbon
}

public class Chain
{
    public ChainMaterialKind ChainMaterial { get; set; }
}

public class Bike : IID_Version
{
    public Guid ID { get; set; }
    [Timestamp]
    public byte[] Version { get; set; }

    public virtual Chain Chain { get; set; }
}

```

Very simple mapping:

```
internal class Bike__Mapping : IEntityTypeConfiguration<Bike>
{
    public void Configure(EntityTypeBuilder<Bike> builder)
    {
        builder.OwnsOne(t => t.Chain);
    }
}

```
After invoking Add-Migration I get code like:

```
modelBuilder.Entity("DomainModel.Bike", b =>
    {
        b.OwnsOne("DomainModel.Chain", "Chain", b1 =>
            {
                b1.Property<Guid>("BikeID")
                    .HasColumnType("uniqueidentifier");

                b1.Property<int>("ChainMaterial")
                    .HasColumnType("int");

                b1.HasKey("BikeID");

                b1.ToTable("Bikes");

                b1.HasCheckConstraint("CK_Bikes_Chain_ChainMaterial_Enum_Constraint", "[Chain_ChainMaterial] IN(0, 1)");

                b1.WithOwner()
                    .HasForeignKey("BikeID");
            });
    });

```
Unfortunately this line cannot compile because `b1` does not have any `HasCheckConstraint` method:
`b1.HasCheckConstraint("CK_Bikes_Chain_ChainMaterial_Enum_Constraint", "[Chain_ChainMaterial] IN(0, 1)");`

You should obviously define the methods your auto-generated code attempts to invoke.

### Further technical details

EF Core version: 5.0 Preview 3.
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET Core 5.0 Preview 3)
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.0 Preview 4.0.

**Comment by ajcvickers** [comment] 2020-05-06 22:19
Duplicate of #20590. Fixed for preview 4.

**Comment by syedsuhaib** [comment] 2020-05-08 10:47
Preview 4 is not released yet. I am facing this issue. How do I test it out? I have downloaded the dotnet-core nightly but I could find no instructions to install efcore nightly. Please help.

**Comment by ajcvickers** [comment] 2020-05-08 15:58
@syedsuhaib You don't need the .NET Core daily build, just install the latest EF Core packages from the daily build feed, as shown here: https://github.com/dotnet/aspnetcore/blob/master/docs/DailyBuilds.md

**Closed** 2022-10-16 18:23 UTC
Labels: closed-duplicate, customer-reported
