### ISSUE TITLE
Improve `HasCheckConstraint`

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/efcore#28775] opened 2022-08-18 12:43 UTC
Currently the only way to add a checked constraint to the table is by using `HasCheckConstraint(name, sql)` extension method. There are 2 main problems here:
1. I have to specify constraint name in my own, while it can be generated automatically via convention: `CHK_<table name>_<column name>`
2. I have to write raw sql, that can be dependent on sql dialect of the db. However, I believe, most simple constraints can be taken from the expression, like the way EF Core produces sql for queries

I propose a solution. Apart from the `HasCheckConstraint` on `EntityTypeBuilder` method EF Core can provide `HasCheckConstraint(expression)` method for `PropertyBuilder`, so code like this (taken from a real project):
```cs
modelBuilder
    .Entity<TerminalIdRange>()
    .HasCheckConstraint($"CHK_{nameof(TerminalIdRanges)}_{nameof(TerminalIdRange.FirstTerminalId)}", $"\"{nameof(TerminalIdRange.FirstTerminalId)}\" > 0")
    .HasCheckConstraint($"CHK_{nameof(TerminalIdRanges)}_{nameof(TerminalIdRange.LastTerminalId)}", $"\"{nameof(TerminalIdRange.LastTerminalId)}\" > 0");
```
will be represented like this:
```cs
modelBuilder
    .Entity<TerminalIdRange>()
    .Property(r => r.FirstTerminalId)
        .HasCheckConstraint(fti => fti > 0)
    .Property(r => r.LastTerminalId)
        .HasCheckConstraint(lti => lti > 0);
```
And such implementation should correctly generate `"FirstTerminalId" > 0` sql for PostgreSql and `[FirstTerminalId] > 0` for Sql Server. Constraint names are also generated automatically: `CHK_<table name of TerminalIdRange>_FirstTerminalId` and `CHK_<table name of TerminalIdRange>_LastTerminalId`

Of course, there should be overloads to be able to override generated constraint name or write constraint in raw sql, if expression can't describe your will:
```cs
modelBuilder
    .Entity<TerminalIdRange>()
    .Property(r => r.FirstTerminalId)
        .HasCheckConstraint("CK_MyConstraintName", fti => fti > 0);
```
```cs
modelBuilder
    .Entity<TerminalIdRange>()
    .Property(r => r.FirstTerminalId)
        .HasCheckConstraint("\"FirstTerminalId\" > 0"); // Postgres dialect
```

I believe this can be a great addition for EF Core 8.

Edit: I also think that expressions should be used when generating migration scripts. Currently, migrations generate this code:
```cs
table.CheckConstraint("CHK_TerminalIdRanges_FirstTerminalId", "\"FirstTerminalId\" > 0");
```
... while, for instance, primary key declaration uses expression:
```cs
table.PrimaryKey("PK_TerminalIdRanges", x => x.Id);
```
Based on what user declared in `OnModelCreating` method, migration can reuse expression, that the user has written:
```cs
table.CheckConstraint("CHK_TerminalIdRanges_FirstTerminalId", fti => fti > 0);
```
As of constraint name, at the stage of creating migration it must be explicit, so leaving it as a string is totally right here.

**Comment by roji** [comment] 2022-08-18 13:18
The expression part is likely a duplicate of #11001; if we do this, we'd probably do it for all relevant metadata APIs at the same time (default value, computed value, check constraint...).

**Comment by ajcvickers** [comment] 2022-10-26 11:15
Closing as duplicate: see https://github.com/dotnet/efcore/issues/11001#issuecomment-1284407531

**Closed by ajcvickers** 2022-10-26 11:15 UTC
Labels: type-enhancement, propose-close, customer-reported, area-model-building
