### ISSUE TITLE
I am doing what you are suggesting but in my case it's not a controller but a business logic class. I am getting  **ArgumentNullException: Value cannot be null.  Parameter name: options**

### ISSUE THREAD

**Issue by pathmanshakir** [dotnet/efcore#14881] opened 2019-02-28 19:12 UTC
@ajcvickers  I am doing what you are suggesting but in my case it's not a controller but a business logic class. I am getting  **ArgumentNullException: Value cannot be null.  Parameter name: options**
it's because of my default constructor that I get null but If I comment out the constrcutor then the new intance of class needs parameters which I don't know what to give in. HELP PLEASE
```
 public class OvertimeRequestBusiness
    {
        public static OvertimeRequestBusiness Instance { get; } = new OvertimeRequestBusiness();
        private readonly DbContextOptions<DatabaseContext> _contextOptions;
     //default ctor
   public OvertimeRequestBusiness() : base() { }
        
  
        public OvertimeRequestBusiness(DbContextOptions<DatabaseContext> contextOptions)
        {
            _contextOptions = contextOptions;
        }
        public async Task<List<User>> GetAllUsersAsync()
        {
            using (var ctx = new DatabaseContext(_contextOptions))
            {
                var query = ctx.Users;
                var res = await query.ToListAsync();
                return res;
            }
        }
    }
```
In my controller 
```
  [Route("users")]
        [HttpGet]
        public async Task<List<User>> GetAllUsers()
        {
          return await OvertimeRequestBusiness.Instance.GetAllUsersAsync();
        }
```

_Originally posted by @pathmanshakir in https://github.com/aspnet/EntityFrameworkCore/issues/6493#issuecomment-468399066_

**Comment by ajcvickers** [comment] 2019-02-28 19:23
@pathmanshakir There isn't enough info here to effectively investigate your issue. Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by pathmanshakir** [comment] 2019-02-28 19:32
I am working on project with no repository pattern ASP.net core. I am trying to separate my business logic from controllers, kind of setting up a business layer. I do the following to get all of my users.
DbContext

**Comment by ajcvickers** [comment] 2019-02-28 21:20
@pathmanshakir The code you are posting is not in a state where I can run it. Please post a small, _runnable_ project/solution or _complete_ code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-03-08 17:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:54 UTC
Labels: closed-could-not-reproduce, customer-reported
