### ISSUE TITLE
MissingRuntimeArtifactException with Sqlite in Release mode

### ISSUE THREAD

**Issue by ViktorBergman** [dotnet/efcore#4418] opened 2016-01-27 22:58 UTC
I'm getting this exception while running my UWP app with EntityFramework.Sqlite in Release mode with .Net Native toolchain:

`Exception thrown: 'Internal.Runtime.TypeLoader.TypeBuilder.MissingTemplateException' in System.Private.TypeLoader.dll
Exception thrown: 'System.Reflection.MissingRuntimeArtifactException' in System.Private.Reflection.Core.dll
Additional information: MakeGenericMethod_NoMetadata, System.Data.Common.DbDataReader.GetFieldValue<System.DateTimeOffset>(System.Int32). For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485`

The exception occurs after making this query:
`var Cards = await Context.MembershipCards.ToListAsync();`

Debugmode does'nt trigger the exception.

Package version is 7.0.0-rc2-16769.

Not sure if it's a bug or if I'm doing something wrong, perhaps using System.DateTimeOffset is'nt valid for Sqlite? Anyways, thankful for any help.

**Comment by MattWhilden** [comment] 2016-01-28 03:01
This is trying to tell you that the .NET Native compiler wasn't able to figure out that your program would eventually need this generic instantiation. You can make sure that the compiler generates this by adding a bit to your runtime directives file. VS puts one in your UWP at Properties\Default.rd.xml. If you enable .NET Native for your DEBUG configuration it'll give you a bit better diagnostic experience.

One thing that is perpetually difficult for ahead of time compilers like .NET Native is APIs like MakeGenericMethod. We do our best but getting it completely correct is impossible.

**Comment by natemcmaster** [comment] 2016-01-28 17:44
This should be fixed when UWP upgrades the packages brought in by "Microsoft.NETCore.UniversalWindowsPlatform". Until then, you may need to add this file to your project:

https://github.com/natemcmaster/corefx/blob/9eafe668a838b43a471759e94ac877839c64ca7f/src/System.Data.Common/src/Resources/System.Data.Common.rd.xml

**Comment by natemcmaster** [comment] 2016-01-28 19:58
Closing as a duplicate of https://github.com/dotnet/corefx/pull/3917

See also https://ef.readthedocs.org/en/staging/platforms/uwp/netnative.html

**Closed** 2022-10-16 09:26 UTC
