### ISSUE TITLE
The instance of entity type cannot be tracked because another instance with the same key value for {'Id'} is already being tracked

### ISSUE THREAD

**Issue by Stan0v** [dotnet/efcore#20611] opened 2020-04-13 17:33 UTC
First of all, I migrated from EF Core 2.2 to 3.0 and this began to happen
 
Requesting profile like this:

```C#
result = await _dbContext.Profiles.AsNoTracking().FirstOrDefaultAsync(x => x.Id == profileId.Value);
```

then requesting advertisement like this:
```C#
advertisement = await GetQuery().FirstOrDefaultAsync(x => x.Id == id);
```

where GetQuery():
```C#
_dbContext.Advertisements
                    .Include(x => x.Author)
                    .Include(etc...).AsNoTracking();
```
then modifying advertisement and save it like this:

```C#
_dbContext.Advertisements.Update(advertisement);
                await _dbContext.SaveChangesAsync();
```

And I get this exception on Update for Profile entity. I wonder why if I used AsNoTracking() everywhere. 

1) if I use scoped dbContext for Updating it works fine, but according to manuals it should work fine with AsNoTracking too.

2) Also I noticed that it works fine if get profile without AsNoTracking. Like this: 
`result = await _dbContext.Profiles.FirstOrDefaultAsync(x => x.Id == profileId.Value);`
It's more strange even.

3) Finally, If sometimes I want to track entity, and sometimes not to, I come to maintain 2 different methods for entity updating (when use scoped dbContext) or check if tracked and do not call Update (but again why exception produced along with AsNoTracking?). That seems to me a bit weird.

Am I missing something?

**Comment by ajcvickers** [comment] 2020-04-14 20:48
@Stan0v It's hard to be sure with only minimal code snippets to go by, but it sounds like you are running into the issue described in #18007. There was a bug in EF Core 2.x which was fixed for 3.x, but resulted in some previous code failing where it was making use of the bug.

If this isn't the case, then please attach a small, runnable project or post a runnable code listing so that we can fully investigate.

**Comment by ajcvickers** [comment] 2020-04-27 16:14
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:20 UTC
Labels: closed-could-not-reproduce, customer-reported
