### ISSUE TITLE
Changing existing int id to DatabaseGeneratedOption.None doesn't migrate properly

### ISSUE THREAD

**Issue by burtonrodman** [dotnet/efcore#4783] opened 2016-03-13 20:21 UTC
I know this is a difficult problem, and I'm sure this is way down on the to do list if it's there at all, but wanted to get it logged...

of course a property public int id { get; set; }  with no attributes will generate [id] INT IDENTITY(1,1) NOT NULL.

adding [DatabaseGenerated(DatabaseGeneratedOption.None)] to the property and generating a migration simply drops all the FKs in the DB and does an AlterColumn without the HasAnnotation.

no actual changes are applied to the database and no errors are generated during database update.

**Comment by rowanmiller** [comment] 2016-03-21 18:43
Ultimately this requires table rebuilds (tracked by another issue), but in the meantime we will warn during apply.

**Comment by bricelam** [comment] 2016-10-06 20:55
Closing as a dupe of #5345. We'll throw now telling you to rebuild the table. Automatically doing the rebuild is tracked by #329.

**Closed** 2022-10-16 09:32 UTC
Labels: type-bug, closed-duplicate
