### ISSUE TITLE
.Include returns one level deep on FirstOrDefaultAsync() but endless level deep on ToListAsync()

### ISSUE THREAD

**Issue by axelgunn** [dotnet/efcore#14670] opened 2019-02-11 11:45 UTC
This query works, and returns Schedule and Period one level deep, Relations to Report are correctly returned as []:

            var result = await _context.Report
                .Include(i => i.Schedule)
                .Include(i => i.Period)
                .FirstOrDefaultAsync(f => f.Id == id);

This one also works but in this case the return set is multilevel deep. All Reports are returned with one Schedule and one Period object which each include all related Report instances.

            var result = await _context.Report
                .Include(i => i.Schedule)
                .Include(i => i.Period)
                .ToListAsync();
                
### Steps to reproduce
Run the above query for any relational setup like above

### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 2.2.1
Operating system: Windows (latest)
IDE: Visual Studio 2017 15.9.6

**Comment by ajcvickers** [comment] 2019-02-11 17:57
Duplicate of #11564

**Closed** 2022-10-16 13:51 UTC
Labels: customer-reported
