### ISSUE TITLE
Projection and redundant order by with Navigation propery

### ISSUE THREAD

**Issue by tomerpeled** [dotnet/efcore#8238] opened 2017-04-20 13:01 UTC
When using navigation property the generated sql query ignores the projection requested and bring all columns (for both tables).
Also an order by clause is added to the query - but I guess this maybe relates to https://github.com/aspnet/EntityFramework/issues/6861 right?

Example:

**Models:**

```
public class Player
{        
        public string PlayerId { get; set; }

        public string Nickname { get; set; }

        public string CountryId { get; set; }
        public Country County { get; set; }
}

public class Country
{
        public string CountryId { get; set; }
        public string Name { get; set; }
}

```
**The query::**

```
var playerInfo =
                    (from p in ctx.Players
                        where p.PlayerId == "123"
                        select new
                        {
                            Player = p.PlayerId,
                            Name = p.County.Name
                        })
                    .FirstOrDefaultAsync().Result;
```

**The SQL generated:**

```
SELECT p.PlayerId, p.CountryId,  p.Nickname, p_County.CountryId, p_County.Name
FROM Players AS p
LEFT JOIN Countries AS p_County ON p.CountryId = p_County.CountryId
WHERE p.PlayerId = '123'
ORDER BY p.CountryId
LIMIT 1
```

Is this a known issue?

**Comment by maumar** [comment] 2017-04-20 17:44
dupe of #6647

**Comment by tomerpeled** [comment] 2017-04-21 06:05
Thanks

**Closed** 2022-10-16 11:02 UTC
