### ISSUE TITLE
Nullable DateTime returns time as 12:00 AM

### ISSUE THREAD

**Issue by scalablecory** [dotnet/efcore#17363] opened 2019-08-21 20:41 UTC
_From @kephax on Wednesday, August 14, 2019 10:54:15 AM_

# Issue Title
When having a nullable DateTime field in a model, the Date is read from the database while the time isn't and it's set to the default time of 12:00:00 AM

# General
.NET Core 2.2
Windows 10 1903
VisualStudio 2019
mySql database

I have a model:

public class TestModel {
  ...
  public DateTime Date1 { get; set; }
  public DateTime? Date2 { get; set; }
  ...
}

The Database table is generated using the EntityFramework Core.
If I manually set a date and time in the database for Date1 and Date2, when reading the values back in code the date is correct while the time in Date2 is set to 12:00:00 AM. 
With Date1 both the date and time are read correctly.

_Copied from original issue: dotnet/core#3188_

**Comment by scalablecory** [comment] 2019-08-21 20:41
_From @carlossanlop on Wednesday, August 14, 2019 5:48:51 PM_

@divega do you know what could be happening here?

**Comment by scalablecory** [comment] 2019-08-21 20:41
_From @divega on Friday, August 16, 2019 3:54:50 AM_

@carlossanlop nothing specific comes to mind.

@kephax if you are able to provide a repro, please create an issue on https://github.com/aspnet/EntityFrameworkCore/ so the EF team can triage it.

**Comment by ajcvickers** [comment] 2019-08-21 20:47
@kephax Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can fully investigate.

**Comment by ErikEJ** [comment] 2019-08-22 09:25
Issue with MySQL provider??

**Comment by ajcvickers** [comment] 2019-08-30 16:48
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:37 UTC
Labels: closed-could-not-reproduce, customer-reported
