### ISSUE TITLE
EFC doesn't allow to disable InMemoryCache

### ISSUE THREAD

**Issue by astridpeth** [dotnet/efcore#20987] opened 2020-05-18 23:59 UTC
I have this code on my Startup.

```C#
var connection = Configuration.GetConnectionString("DefaultConnection")?.Replace("[BD_PASS]", Environment.GetEnvironmentVariable("BD_PASS"));
services.AddDbContext<BdContext>(options => options.UseSqlServer(connection));

services.AddMemoryCache(op =>
            {
                op.SizeLimit = int.Parse(Environment.GetEnvironmentVariable("CACHE_SIZE_LIMIT") ?? "10");
            });
```

The problem is that I wasn't aware that Entity Framework Core would intercept my queries against the database. So, while running

```C#
 _context.Product.ToList();
```

I am getting this message when the code above is run.
> cache entry must specify a value for size when the size limit is set

I guess this is pretty reasonable, EFC doesn't know the size of what I am querying. 

The problem is that I never asked EFC to do this for me. I want to cache the things by my self, or at least that EFC uses its IMemoryCache, not mine. 

All troubleshoots I could find on the internet, people didn't want to use SIZE_LIMIT, but I do. 

Is there anything I could do at the configuration level to say "Hey EFC, don't you bother to cache anything."

**Comment by smitpatel** [comment] 2020-05-19 00:01
Duplicate of #12157

Please share a runnable project and details of which version of EF Core you are using.

**Comment by astridpeth** [comment] 2020-05-19 01:03
I am using ASP.NET Core 2.2
I didn't found EFC on my NuGet, but I guess it is The same as ASP.NET Core.

**Closed** 2022-10-16 18:25 UTC
Labels: closed-no-further-action, customer-reported
