### ISSUE TITLE
Different writing behaviors before and after reading the navigation collection

### ISSUE THREAD

**Issue by LFusek** [dotnet/efcore#17129] opened 2019-08-13 17:06 UTC
Short description
Writing to the database behaves differently based on whether or not I read the navigation collection property of the entity.

### Steps to reproduce
Solution to replicate the bug: [EntityFrameworkTesting.zip](https://github.com/aspnet/EntityFrameworkCore/files/3497891/EntityFrameworkTesting.zip)

Solution description
So, there is `PizzaShop` entity, `Deliveryman` entity and  `PizzaShopDeliveryMan` linking entity (for many to many relationship).
My goal is to create new version of PizzaShop entity every time when any changes are made but both the original PizzaShop and new modified one are pointing via PizzaShopDeliveryMan to the same Deliveryman. I achieve this by 3 steps:

1. Get entity from database and made changes.
2. Detach modified entity and set Id to 0 so the database will think this is new entity.
3. Add entity to the database.

 In the first approach I didn't `get` anything from `pizzaShop.PizzaShopDeliveryMans`. I just `set` new collection with the same Deliveryman. Result of this approach is desired and that is original PizzaShop and new PizzaShop has both their own PizzaShopDeliveryMan linking entity connecting them to one Deliveryman.
In the second approach I `get` (lazy loaded) entities from `pizzaShop.PizzaShopDeliveryMans`. Result of this approach is that original PizzaShop lost his PizzaShopDeliveryMan linking entity (the linking entity is still there but the foreign key of PizzaShop is null), still the new PizzaShop correctly has his own new PizzaShopDeliveryMan linking entity pointing to Deliveryman.

!Note that result of the second behavior could be achieved also in the first approach if you in the step mod `get` (lazy load) `pizzaShop.PizzaShopDeliveryMans`.

So the problem is really sneaky because the writing behavior really change when you read the navigation property in any way. You can really have different changes in database just by reading property of the entity in debug mod.

### Further technical details
EF Core version: 2.2.6
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10 Pro
IDE: Visual Studio 2019 16.2.1

**Comment by ajcvickers** [comment] 2019-11-15 00:36
@LFusek I'm having trouble understanding what you are trying to do. Can you explain a bit more what you mean by, "My goal is to create new version of PizzaShop entity". What is a "new version" in this context?

**Comment by ajcvickers** [comment] 2019-11-22 22:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:35 UTC
Labels: closed-could-not-reproduce, customer-reported
