### ISSUE TITLE
Owned Entity gets deleted and inserted while updating parent entity in Entity Framework Core 3.1

### ISSUE THREAD

**Issue by fingers10** [dotnet/efcore#20918] opened 2020-05-11 15:05 UTC
I'm using `Entity Framework Core 3.1`. I have a parent entity named `Event` that owns a collection of `EventImage`.

**Event:**
```c#
public class Event : Entity, IAggregateRoot
{
    private readonly List<Participant> _participants = new List<Participant>();

    protected Event()
    {

    }

    public Event(Title title, Description description, Date date, City city, Location location,
        EventType type, Link link, Tickets totalTickets, List<EventImage> eventImages) : this()
    {
        Title = title;
        Description = description;
        Date = date;
        City = city;
        Location = location;
        Type = type;
        Link = link;
        TotalTickets = totalTickets;
        TicketsSold = Tickets.Create(0).Value;
        EventImages = eventImages;
        Active = true;
    }

    public Title Title { get; private set; }
    public Description Description { get; private set; }
    public Date Date { get; private set; }
    public City City { get; private set; }
    public Location Location { get; private set; }
    public EventType Type { get; private set; }
    public Link Link { get; private set; }
    public Tickets TotalTickets { get; private set; }
    public Tickets TicketsSold { get; private set; }
    public ICollection<EventImage> EventImages { get; set; }
    public IReadOnlyList<Participant> Participants => _participants.ToList();

    public void EditEvent(Title title, Description description, Date date, City city, Location location,
        EventType type, Link link, Tickets totalTickets, List<EventImage> eventImages, bool active)
    {
        Title = title ?? throw new ArgumentNullException(nameof(title));
        Description = description ?? throw new ArgumentNullException(nameof(description));
        Date = date;
        City = city ?? throw new ArgumentNullException(nameof(city));
        Location = location ?? throw new ArgumentNullException(nameof(location));
        Type = type ?? throw new ArgumentNullException(nameof(type));
        Link = link ?? throw new ArgumentNullException(nameof(link));
        TotalTickets = totalTickets;
        EventImages = eventImages ?? throw new ArgumentNullException(nameof(eventImages));
        Active = active;
    }
}
```

**EventImage:**
```c#
public class EventImage
{
    public ImageUrl Url { get; }

    protected EventImage()
    {
    }

    public EventImage(ImageUrl url)
        : this()
    {
        Url = url;
    }
}
```

**Event Entity Configuration:**
```c#
public class EventConfiguration : IEntityTypeConfiguration<Event>
{
    public void Configure(EntityTypeBuilder<Event> builder)
    {
        builder.HasKey(p => p.Id);

        builder.Property(p => p.Title)
                .IsRequired()
                .HasMaxLength(200)
                .HasConversion(p => p.Value, p => Title.Create(p).Value);

        builder.Property(p => p.Description)
                .IsRequired()
                .HasMaxLength(500)
                .HasConversion(p => p.Value, p => Description.Create(p).Value);

        builder.Property(p => p.Date)
                .IsRequired()
                .HasConversion(p => p.Value, p => Date.Create(p).Value);

        builder.Property(p => p.City)
                .IsRequired()
                .HasMaxLength(100)
                .HasConversion(p => p.Value, p => City.Create(p).Value);

        builder.Property(p => p.Location)
                .IsRequired()
                .HasMaxLength(100)
                .HasConversion(p => p.Value, p => Location.Create(p).Value);

        builder.HasOne(p => p.Type).WithMany();

        builder.Property(p => p.Link)
                //.IsRequired()
                .HasConversion(p => p.Value, p => Link.Create(p).Value);

        builder.Property(p => p.TotalTickets)
                .IsRequired()
                .HasConversion(p => p.Value, p => Tickets.Create(p).Value);

        builder.Property(p => p.TicketsSold)
                .IsRequired()
                .HasConversion(p => p.Value, p => Tickets.Create(p).Value);

        builder.OwnsMany(p => p.EventImages, a =>
        {
            a.ToTable("EventImages");
            a.Property(a => a.Url)
                .IsRequired()
                .HasConversion(p => p.Value, p => ImageUrl.Create(p).Value);
            a.WithOwner().HasForeignKey("EventId");
            a.Property<Guid>("Id");
        });

        builder.HasMany(p => p.Participants).WithOne(p => p.Event)
                .OnDelete(DeleteBehavior.Cascade)
                .Metadata.PrincipalToDependent.SetPropertyAccessMode(PropertyAccessMode.Field);

    }
}
```

Now whenever I update `Event` entity, `EventImage` always gets deleted and inserted.

```c#
var eventEntity = await _eventRepository.GetByIdAsync(id);

eventEntity.EditEvent(titleResult.Value, descriptionResult.Value, dateResult.Value, cityResult.Value, locationResult.Value, eventType, eventLinkResult.Value, totalTicketsResult.Value, eventImages, @event.Active);

await _eventRepository.UpdateAsync(eventEntity);
```

Here is the SQL generated by `Entity Framework Core 3.1`

```sql
SET NOCOUNT ON;
DELETE FROM [EventImages]
WHERE [EventId] = @p0 AND [Id] = @p1;
SELECT @@ROWCOUNT;

SET NOCOUNT ON;
INSERT INTO [EventImages] ([EventId], [Id], [Url])
VALUES (@p0, @p1, @p2);
SET NOCOUNT ON;

UPDATE [Events] SET [Active] = @p0, [City] = @p1, [CreatedAt] = @p2, [CreatedBy] = @p3, [Date] = @p4, [Description] = @p5, [Link] = @p6, [Location] = @p7, [ModifiedAt] = @p8, [ModifiedBy] = @p9, [TicketsSold] = @p10, [Title] = @p11, [TotalTickets] = @p12, [TypeId] = @p13
WHERE [Id] = @p14;
SELECT @@ROWCOUNT;
```

Is this the correct behavior? I'm not changing my `EventImage` but still it gets deleted and inserted.

Please assist if I'm doing anything wrong?

**Comment by fingers10** [comment] 2020-05-12 16:57
Uh.. now I understand in that case how to update collection of owned entity? EF core doesn't track the owned entity based on its values like

1. If the value is already there then mark as unchanged.
2. If the value is missing in new list then delete from original list.
3. If the value is new in the new list and it's not available in the existing list then it can be added.

Or I need to manually iterate and do this?

Please share your thoughts

**Comment by ajcvickers** [comment] 2020-05-12 18:41
@fingers10 I don't understand your question; EF does work like this. However, remember that owned entity types are not value object types; they are entity types. You can't, in general, just replace one instance with another.

**Comment by ajcvickers** [comment] 2020-05-22 16:23
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:24 UTC
Labels: closed-could-not-reproduce, customer-reported
