### ISSUE TITLE
Nested owned types migration error

### ISSUE THREAD

**Issue by hitaspdotnet** [dotnet/efcore#18350] opened 2019-10-12 15:41 UTC
I getting an error, when I try to using a owned type in multi entities. I think I got the error because `User` has used the same type.
``` C#
public class User : IEntity<Guid>
{
    public Guid Id { get; set; }
    public ContactInfo UserContactInfo { get; set; }
}

public class Listing : IEntity<Guid>
{
    public Guid Id { get; set; }
    public ContactInfo ListingContactInfo { get; set; }
}

public class ContactInfo : IOwnedType
{
    public string WebsiteUrl { get; set; }
    public Location GeoLocation { get; set; }
}

public class Location : IOwnedType
{
    public NetTopologySuite.Geometries.Point Coords { get; set; }
    public Address PhysicalAddress { get; set; }
}
public class Address : IOwnedType
{
    public string AddressLine1 { get; set; }
    public string ZipPostalCode { get; set; }
}
//User modelBuilder
userBuilder.OwnsOne(c => c.UserContactInfo, conInfo =>
{
    conInfo.ToTable("UsersContactInfo");
    conInfo.OwnsOne(ci => ci.GeoLocation, location =>
    {
        location.OwnsOne(x => x.PhysicalAddress, address =>
        {
            address.ToTable("UsersPhysicalAddresses");
        });
        location.Property(x => x.Coords).HasColumnType("geography");
        location.ToTable("UsersLocations");
    });
});
//Listing modelBuilder
listingBuilder.OwnsOne(c => c.ListingContactInfo, conInfo =>
{
    conInfo.ToTable("ListingsContactInfo");
    conInfo.OwnsOne(ci => ci.GeoLocation, location =>
    {
        location.OwnsOne(x => x.PhysicalAddress, address =>
        {
            address.ToTable("ListingsPhysicalAddresses");
        });
        location.Property(x => x.Coords).HasColumnType("geography");
        location.ToTable("ListingsLocations");
    });
});
```
```log
D:\MATA360\host\src\Hitasp.Tradegram.EntityFrameworkCore>dotnet ef database update
Applying migration '13980720151831_Initial_I'.
System.InvalidOperationException: The entity type 'Hitasp.Tradegram.Types.Location' cannot be added to the model because a weak entity type with the same name already exists.

   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(EntityType entityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(TypeIdentity& type, ConfigurationSource configurationSource, Boolean allowOwned, Boolean thr
owOnQuery)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(String name, ConfigurationSource configurationSource, Boolean allowOwned, Boolean throwOnQue
ry)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceOwnershipBuilder.FindRelatedEntityType(String relatedTypeName, String navigationName)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceOwnershipBuilder.HasOne(String relatedTypeName, String navigationName)
   at Hitasp.Tradegram.Migrations.Initial_I.<>c.<BuildTargetModel>b__2_133(ReferenceOwnershipBuilder b3) in D:\MATA360\host\src\Hitasp.Tradegram.EntityFrameworkCore\Migration
s\13980720151831_Initial_I.Designer.cs:line 3093
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceOwnershipBuilder.OwnsOne(String ownedTypeName, String navigationName, Action`1 buildAction)
   at Hitasp.Tradegram.Migrations.Initial_I.<>c.<BuildTargetModel>b__2_132(ReferenceOwnershipBuilder b2) in D:\MATA360\host\src\Hitasp.Tradegram.EntityFrameworkCore\Migration
s\13980720151831_Initial_I.Designer.cs:line 3063
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceOwnershipBuilder.OwnsOne(String ownedTypeName, String navigationName, Action`1 buildAction)
   at Hitasp.Tradegram.Migrations.Initial_I.<>c.<BuildTargetModel>b__2_131(ReferenceOwnershipBuilder b1) in D:\MATA360\host\src\Hitasp.Tradegram.EntityFrameworkCore\Migration
s\13980720151831_Initial_I.Designer.cs:line 3047
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.OwnsOne(String ownedTypeName, String navigationName, Action`1 buildAction)
   at Hitasp.Tradegram.Migrations.Initial_I.<>c.<BuildTargetModel>b__2_106(EntityTypeBuilder b) in D:\MATA360\host\src\Hitasp.Tradegram.EntityFrameworkCore\Migrations\1398072
0151831_Initial_I.Designer.cs:line 3026
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(String name, Action`1 buildAction)
   at Hitasp.Tradegram.Migrations.Initial_I.BuildTargetModel(ModelBuilder modelBuilder) in D:\MATA360\host\src\Hitasp.Tradegram.EntityFrameworkCore\Migrations\13980720151831_
Initial_I.Designer.cs:line 3019
   at Microsoft.EntityFrameworkCore.Migrations.Migration.<.ctor>b__4_0()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The entity type 'Hitasp.Tradegram.Types.Location' cannot be added to the model because a weak entity type with the same name already exists.
```
### Further technical details

EF Core version: 2.2.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 2.2
Operating system: Windows 10
IDE: Rider 2019.2.2

**Comment by hitaspdotnet** [comment] 2019-10-12 15:51
```C#
file: 13980720151831_Initial_I.Designer.cs#line3019~3100
            modelBuilder.Entity("Hitasp.Tradegram.Listings.Listing", b =>
                {
                    b.HasOne("Hitasp.Tradegram.ListingTypes.ListingType", "ListingType")
                        .WithMany()
                        .HasForeignKey("ListingTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Hitasp.Tradegram.Types.ContactInfo", "ListingContactInfo", b1 =>
                        {
                            b1.Property<Guid>("ListingId");

                            b1.Property<string>("InstagramUrl");

                            b1.Property<string>("LinkedInProfileUrl");

                            b1.Property<string>("TwitterUsername");

                            b1.Property<string>("WebsiteUrl");

                            b1.HasKey("ListingId");

                            b1.ToTable("ListingContactInfo");

                            b1.HasOne("Hitasp.Tradegram.Listings.Listing")
                                .WithOne("ListingContactInfo")
                                .HasForeignKey("Hitasp.Tradegram.Types.ContactInfo", "ListingId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("Hitasp.Tradegram.Types.Location", "GeoLocation", b2 =>
                                 {
                                    b2.Property<Guid>("ContactInfoListingId");

                                    b2.Property<Point>("Coords")
                                        .HasColumnType("geography");

                                    b2.HasKey("ContactInfoListingId");

                                    b2.ToTable("ListingLocations");

                                    b2.HasOne("Hitasp.Tradegram.Types.ContactInfo")
                                        .WithOne("GeoLocation")
                                        .HasForeignKey("Hitasp.Tradegram.Types.Location", "ContactInfoListingId")
                                        .OnDelete(DeleteBehavior.Cascade);

                                    b2.OwnsOne("Hitasp.Tradegram.Types.Address", "PhysicalAddress", b3 =>
                                        {
                                            b3.Property<Guid>("LocationContactInfoListingId");

                                            b3.Property<string>("AddressLine1");

                                            b3.Property<string>("AddressLine2");

                                            b3.Property<int?>("AreaId");

                                            b3.Property<int?>("CityId");

                                            b3.Property<int>("CountryId");

                                            b3.Property<int?>("CountyId");

                                            b3.Property<int?>("DistrictId");

                                            b3.Property<int?>("RegionId");

                                            b3.Property<int>("StateProvinceId");

                                            b3.Property<int?>("VillageId");

                                            b3.Property<string>("ZipPostalCode");

                                            b3.HasKey("LocationContactInfoListingId");

                                            b3.ToTable("ListingPhysicalAddresses");

                                            b3.HasOne("Hitasp.Tradegram.Types.Location")
                                                .WithOne("PhysicalAddress")
                                                .HasForeignKey("Hitasp.Tradegram.Types.Address", "LocationContactInfoListingId")
                                                .OnDelete(DeleteBehavior.Cascade);
                                        });
                                });
                        });
                });
```

**Comment by hitaspdotnet** [comment] 2019-10-12 17:56
I change the Location type to Entity and error gone in a sample code. I need location as owned type. Any other solutions please?

**Comment by AndriySvyryd** [comment] 2019-10-12 18:37
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/18183

**Comment by AndriySvyryd** [comment] 2019-10-12 18:42
@hitaspdotnet You would need to remove the `b3.HasOne("Hitasp.Tradegram.Types.Location")` line and the following calls. Or upgrade to 3.0.0 and use the `WithOwner` method instead.

**Comment by hitaspdotnet** [comment] 2019-10-12 19:12
@AndriySvyryd Thanks for response. 

> You would need to remove the b3.HasOne("Hitasp.Tradegram.Types.Location") line and the following calls.

for both entities?

**Comment by AndriySvyryd** [comment] 2019-10-12 19:41
@hitaspdotnet In 2.2 just one should be enough, but you can do it for both for consistency. If everything is correct adding another migration should produce one without any database changes (though the snapshot would need to be fixed for every migration)

**Closed** 2022-10-16 14:49 UTC
Labels: closed-duplicate, customer-reported
