### ISSUE TITLE
Incorrect SQL generated when using SUM with comparison operator

### ISSUE THREAD

**Issue by bradmarder** [dotnet/efcore#18200] opened 2019-10-03 02:41 UTC
If a subquery has an expression such as `x.Posts.Sum(y => y.Id)`, and there are zero posts, this should evaluate to `0`. Instead, it evaluates to `null`, and it appears the generated statement is either missing a `coalesce(sum, 0)` or `isnull` or `exists` statement.  Changing the code to `x.Posts.Any() ? x.Posts.Sum(y => y.Id) : 0` generates the intended SQL. I'm not entirely sure this is a bug though - it may be intended behavior.

```c#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFCoreBugs
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using (var db = new TestDb())
            {
                await db.Database.EnsureDeletedAsync();
                await db.Database.EnsureCreatedAsync();
                await db.Blogs.AnyAsync(x => 0 == x.Posts.Sum(y => y.Id));
            }
            Console.ReadLine();
        }
    }

    public class TestDb : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseLoggerFactory(LoggerFactory.Create(x => x.AddConsole()))
                .UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=master;Database=bugtest;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");
        }
    }

    public class Blog
    {
        public int Id { get; set; }

        [InverseProperty(nameof(Post.Blog))]
        public virtual ICollection<Post> Posts { get; } = new HashSet<Post>();
    }

    public class Post
    {
        public int Id { get; set; }
        public int BlogId { get; set; }

        [ForeignKey(nameof(BlogId))]
        public virtual Blog Blog { get; private set; }
    }
}
```

SQL Generated for EFCore 3.0.0
```SQL
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [Blogs] AS [b]
        WHERE (0 = (
            SELECT SUM([p].[Id])
            FROM [Posts] AS [p]
            WHERE [b].[Id] = [p].[BlogId])) AND (
            SELECT SUM([p].[Id])
            FROM [Posts] AS [p]
            WHERE [b].[Id] = [p].[BlogId]) IS NOT NULL) THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END
```

EFCore 2.2.6 generates a similar query, albeit still incorrect.

```SQL
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [Blogs] AS [x]
        WHERE 0 = (
            SELECT SUM([y].[Id])
            FROM [Posts] AS [y]
            WHERE [x].[Id] = [y].[BlogId]
        ))
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END
```

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: netcoreapp3.0
Operating system: win10 x64
IDE: Visual Studio 2019 16.3

**Comment by smitpatel** [comment] 2019-10-03 21:03
@bradmarder - Isn't it same as #12657?

**Comment by bradmarder** [comment] 2019-10-04 00:29
@smitpatel Yeah, definitely same root issue, but the manifestation of this is way worse, because it doesn't throw or warn - it just silently returns bad data.  I can survive with workarounds so feel free to close as dupe.

**Comment by maumar** [comment] 2019-11-01 23:07
closing as dupe of #12657

**Closed** 2022-10-16 14:47 UTC
Labels: customer-reported
