### ISSUE TITLE
Consider adding examples of filters in XML docs for HasFilter and CreateIndex

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#17512] opened 2018-12-13 23:27 UTC
When I responded to https://github.com/aspnet/EntityFramework.Docs/issues/1175 I found that what you can pass to the API isn't very discoverable (although I understand that it is provider specific).

**Comment by ajcvickers** [comment] 2019-08-30 20:21
Duplicate of #17508

**Closed** 2022-10-16 14:38 UTC
Labels: closed-duplicate
