### ISSUE TITLE
Sqlite code running in RHEL throws DllNotFoundException (for DLL sqlite3)

### ISSUE THREAD

**Issue by DonSchenck** [dotnet/efcore#5100] opened 2016-04-18 17:15 UTC
OS Name: rhel
OS Version: 7.2
OS Platform: Linux
Dotnet --version: 1.0.0-rc2-002339

Call to method "EnsureCreated" throws the following:

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'sqlite3': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.Sqlite3_sqlite3.sqlite3_open_v2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Speakr.Program.Main(String[] args)

**Comment by rowanmiller** [comment] 2016-04-18 18:57
@natemcmaster can you share the steps needed 😄

**Comment by natemcmaster** [comment] 2016-04-18 19:01
@DonSchenck do you have libsqlite3 installed on your machine? This library binds to the version of sqlite installed on the OS. cref https://github.com/aspnet/Microsoft.Data.Sqlite#requirements

You can check with:
```
ldconfig -p | grep sqlite3
```

**Comment by DonSchenck** [comment] 2016-04-18 19:02
[vagrant@rhel-cdk cli-samples-master]$ ldconfig -p | grep sqlite3
        libsqlite3.so.0 (libc6,x86-64) => /lib64/libsqlite3.so.0


Also, `which sqlite3` yields /usr/bin/sqlite3

**Comment by natemcmaster** [comment] 2016-04-18 19:07
CoreCLR should be loading `/lib64/libsqlite3.so.0`. @stephentoub on RHEL, which paths do we probe for native libraries? Or do we just rely on default behavior of `dlopen`?

**Comment by DonSchenck** [comment] 2016-04-18 19:07
Also, `sqlite3 -version` returns `3.7.17 2013-05-20 00:56:22 118a3b35693b134d56ebd780123b7fd6f1497668`

**Comment by natemcmaster** [comment] 2016-04-18 19:10
@DonSchenck `/usr/bin/sqlite3` is just a user shell. I'm not sure if it uses `dlopen` to load `libsqlite3` or if sqlite3 is statically linked in this executable. Either way, you can try working around by manipulating the folders that `dlopen` looks for. See `man dlopen`. On most *nix systems, the search path for native libraries is set in the env variable `LD_LIBRARY_PATH`

**Comment by stephentoub** [comment] 2016-04-18 19:11
> which paths do we probe for native libraries?

@sergiy-k, @janvorli, or @jkotas can probably answer this best.

**Comment by moozzyk** [comment] 2016-04-18 19:18
you can set the `LD_DEBUG`

**Comment by DonSchenck** [comment] 2016-04-18 19:28
I see it attempting to load `/lib64/libsqlite3.so`, but not `/lib64/libsqlite3.so.0'

Does that make a difference?

**Comment by natemcmaster** [comment] 2016-04-18 19:56
Yes. Try creating a symbolic link. `ln -s /lib64/libsqlite3.so.0 /lib64/libsqlite3.so`. I'm not familiar with RHEL, but on debian, this symbolic link is added automagically when installing [libsqlite3-dev](https://packages.debian.org/sid/libsqlite3-dev). This there an equivalent package for RHEL?

**Comment by DonSchenck** [comment] 2016-04-18 19:59
Thanks. I did a bad thing and just copied the original, and that worked. I've since deleted my copy and am using the symlink instead.

I'm no longer getting that error.

**Comment by DonSchenck** [comment] 2016-04-18 20:13
@natemcmaster To answer your question, `yum install sqlite3` just tells me it's already installed and there's nothing to do.

I'm going to wipe my RHEL VM and start from scratch, but your help has been wonderful. THANK YOU.

**Comment by natemcmaster** [comment] 2016-04-18 20:14
@DonSchenck I don't have RHEL...but what about `yum install libsqlite3-devel`?

**Comment by DonSchenck** [comment] 2016-04-18 20:15
Oh; I tried `libsqlite3-dev` ... I'll try your's.

**Comment by DonSchenck** [comment] 2016-04-18 20:16
(FYI You can get a copy of RHEL for free if you want to experiment)

**Comment by natemcmaster** [comment] 2016-04-18 20:46
Found the right package. I'm closing this as a duplicate of https://github.com/aspnet/Microsoft.Data.Sqlite/issues/237
```
yum install sqlite-devel
```
https://github.com/aspnet/Microsoft.Data.Sqlite#redhat

**Closed** 2022-10-16 09:36 UTC
