### ISSUE TITLE
OwnedTypes on navigation property are not automatically included

### ISSUE THREAD

**Issue by Tarig0** [dotnet/efcore#10217] opened 2017-11-03 16:57 UTC
If you retrieve an entity from the dbset the OwnedTypes are included by default. If I want to include a child entity that is not owned but has it's own owned types, these are not included by default.

```c#
db.Set<Parent>().Include(p=>child); //child owns 1 toy
```

expected consistent behavior
Either the entity is owned there for always included when the owning entity is or you must explicitly include all owned navigations

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: WIndows 10
IDE: Visual Studio 2017

**Comment by smitpatel** [comment] 2017-11-03 21:01
Duplicate of #9210

**Closed** 2022-10-16 11:56 UTC
Labels: closed-duplicate
