### ISSUE TITLE
No Children Inserted !

### ISSUE THREAD

**Issue by moataz1991** [dotnet/efcore#13119] opened 2018-08-26 01:07 UTC
Add or Updating an existing parent object after sending it to webapi controller that has unchanged/changed children and grand children 
fails ! , it should add or update parent object and automatically add,update or only attach children and grand children objects

### Steps to reproduce
1-Create Parent Object say "Building1"
2-Add "Floor1" child object to the collection of Floors in "Building1"
3-Add "Apartment1" grand child to child object apartments collection "Floor1"
4- _context.SaveChanges();
=> this is ok !
now let's bring that parent object "Building1" and add another floor say "floor2" and goto step (2)
the new child object with it's apartments collection do not get inserted to DB and no error happens !

```c#
`public class Building
{
    public long BuildingID {get;set;}
    public string Name{get;set;}
    public ICollection<Floor> Floors{get;set;}
}

public class Floor
{
    public long FloorID {get;set;}
    public string Name{get;set;}
    public ICollection<Apartment> Apartments{get;set;}
}

public class Apartment
{
    public long ApartmentID {get;set;}
    public string Name{get;set;}
...
}
`
```

### Further technical details
EF Core version: 2.1.0
Database Provider: MySql.Data 8.0.12 , Pomelo.EntityFrameworkCore.MySql 2.1.0
Operating system: Windows 10 64-bit
IDE:Visual Studio 2017 15.7

**Comment by moataz1991** [comment] 2018-08-26 08:44
i know the problem now
i was doing for the update : "...State = Modified" while i should use "context.update(model)"
bad tutorials in the internet... sry guys

**Comment by moataz1991** [comment] 2018-08-26 16:48
btw , sense this issue was not closed yet :)
when i delete child object from parent collection
it does not get deleted from database
also parent collection get duplicate when updating it with it's children collection 
in other mean , if u context.Update(Parent) 2 times
i will find duplicate of children collection and all attached to Parent

as for the example above it will be 
1-Floor1
2-Floor1
3-Floor2
4-Floor2

how to avoid this ?

**Comment by ajcvickers** [comment] 2018-08-27 17:08
@moataz1991 Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing together with a description of how it doesn't meet your expectations.

**Comment by ajcvickers** [comment] 2018-09-05 17:53
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:27 UTC
Labels: closed-could-not-reproduce, customer-reported
