### ISSUE TITLE
EF Core 7 Linq with a 'Contains" generates an SQL with an extra 'or is not null'

### ISSUE THREAD

**Issue by julienFlexsoft** [dotnet/efcore#30483] opened 2023-03-14 18:23 UTC
I recently updated EF Core 6 to 7, and now a query has become a lot slower than before without any changes. It looks like EF Core translated the LINQ query to a different SQL query.

Versions:
- .NET: 7
- EF Core: 7.0.3

This is the LINQ query:
```c#
int userId = 3;
List<string> labels = new () { "one", "two", "three" };
List<RecordEntity> alreadySyncedEvents = await _dbContext.RecordEntities
    .IgnoreQueryFilters()
    .Where(x => x.UserId == userId)
    .Where(x => labels.Contains(x.Label))
    .Include(x => x.ExtraData)
    .ToListAsync();
```

This is the generated SQL:
```sql
SELECT [a].[Id], [a].[Label], [a0].[Id], [a0].[ExtraData]
FROM [RecordEntities] AS [a]
LEFT JOIN [ExtraDataEntities] AS [a0] ON [a].[Id] = [a0].[RecordId]
WHERE ([a].[UserId] = 3) AND ([a].[Label] IN (N'one', N'two', N'three') OR ([a].[Label] IS NULL))
ORDER BY [a].[Id]
```

The problem is that the `OR ([a].[Label] IS NULL)` causes this query to return over 13k records while before the switch to EF Core 7 it returned 1. The only thing it added was the extra `OR` condition.

Is this because I don't use nullable reference types and that string is by default nullable?
Nullable reference types are completely disabled in this project.

### Include provider and version information

EF Core version: 7.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 7.0

**Comment by ajcvickers** [comment] 2023-03-29 19:35
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-03-29 19:35 UTC
Labels: customer-reported
