### ISSUE TITLE
OrderBy expression could not be translated and will be evaluated locally

### ISSUE THREAD

**Issue by quilin** [dotnet/efcore#14250] opened 2018-12-26 16:02 UTC
I have this semi-complex query that counts the most voted user post of the last 7 days:

```c#
var fromDate = dateTimeService.Now.Add(-interval);
var votedPosts =
    from vote in dbContext.Votes
    join post in dbContext.Posts on vote.PostId equals post.PostId
    group new {vote.Sign, post.PostId} by post.PostId
    into postVotes
    select new {
        PostId = postVotes.Key,
        TotalRating = postVotes.Sum(pv => pv.Sign)
    };
var bestPosts = (
    from post in dbContext.Posts
    join votedPost in votedPosts on post.PostId equals votedPost.PostId
    join room in dbContext.Rooms on post.RoomId equals room.RoomId
    join game in dbContext.Modules on room.ModuleId equals game.ModuleId
    where room.RoomAccess == RoomAccessType.Open && post.CreateDate > fromDate
    orderby votedPost.TotalRating descending,
        post.CreateDate descending
    select new BestPost
    {
        UserId = post.UserId,
        ModuleId = game.ModuleId,
        ModuleTitle = game.Title,
        PostId = post.PostId,
        PostText = post.Text,
        PostCommentary = post.Commentary,
        PostCreateDate = post.CreateDate,
        TotalRating = bestPost.TotalRating
    }).FirstOrDefault();
```

What I try to do here is to group user votes by `PostId`, sum the evaluations of their votes by field `Sign` (can be -1, 0 or 1), then join it with some additional data like game Id/Title and post texts, filter non-public or too old posts, then order it by rank and then by create date, then map it onto DTO and return the very first result if present.
All the fields here are simple basic types: the `Vote.Sign` is `int`, `Post.CreateDate` is `DateTime`, all the `*Id` are `Guid` and `Text/Title/Commentary` are `string`.
I get the warning:
```
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'orderby [bestPost].TotalRating desc' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'FirstOrDefault()' could not be translated and will be evaluated locally.
```

If I remove the sort by `TotalRating` and only leave the `CreateDate` sorting, it works fine, creates proper `LIMIT` request. But whenever I add the aggregated field `TotalRating` to the sorting, it fails to translate it to SQL. With `CreateDate` only it looks like this:

```sql
SELECT t."PostId", t."TotalRating", post."UserId", game."ModuleId", game."Title" AS "ModuleTitle", post."PostId" AS
 "PostId0", post."Text" AS "PostText", post."Commentary" AS "PostCommentary", post."CreateDate" AS "PostCreateDate"
      FROM "Posts" AS post
      INNER JOIN (
          SELECT post0."PostId", SUM(vote."Sign")::INT AS "TotalRating"
          FROM "Votes" AS vote
          INNER JOIN "Posts" AS post0 ON vote."PostId" = post0."PostId"
          GROUP BY post0."PostId"
      ) AS t ON post."PostId" = t."PostId"
      INNER JOIN "Rooms" AS room ON post."RoomId" = room."RoomId"
      INNER JOIN "Modules" AS game ON room."ModuleId" = game."ModuleId"
      WHERE (room."RoomAccess" = 0) AND (post."CreateDate" > @__fromDate_0)
      ORDER BY "PostCreateDate" DESC
      LIMIT 1
```

And it totally works for SQL to type `ORDER BY "TotalRating" DESC, "PostCreateDate" DESC`. Looks like an issue to me, but maybe I am doing something wrong?

### Further technical details
EF Core version: 2.2.0
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10 Pro
IDE: Rider 2018.3

**Comment by smitpatel** [comment] 2018-12-26 20:01
Duplicate of #8094

**Closed** 2022-10-16 13:45 UTC
Labels: closed-duplicate, customer-reported
