### ISSUE TITLE
EF Core 3.0 regression failure

### ISSUE THREAD

**Issue by laguer71** [dotnet/efcore#18122] opened 2019-09-29 06:08 UTC
the Linq Max statement isn't working as expected upgrading from 2.2.6 to 3.0.

### Steps to reproduce

Please view code in this git
https://github.com/laguer71/MigrationTest

In the project file, comment the references to EF Core 3.0 and uncoment the references to EF Core 2.2.6 to see the expected results (entity #2), and then revert to EF Core 3.0 to see the eception

We ❤ code! Include a complete code listing or attach a simplified project

``` C#
    var current = db.Entities
            .Select(ent => ent.Number)
            .DefaultIfEmpty("0")
            .Max();

         Console.WriteLine(current);
```

Got Exceptions? Include both the message and the stack trace

For `dotnet ef` and PMC, share the --verbose output
-->

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Processing of the LINQ expression 'DefaultIfEmpty<string>(
    source: Select<Entity, string>(
        source: DbSet<Entity>, 
        selector: (ent) => ent.Number), 
    defaultValue: (Unhandled parameter: __p_0))' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandAndReduce(Expression query, Boolean applyInclude)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Max[TSource](IQueryable`1 source)
   at MigrationTest.Program.Main(String[] args) in C:\Users\lague\source\repos\MigrationTest\MigrationTest\Program.cs:line 27
```

### Further technical details

EF Core version: 3.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer and InMemory)
Target framework: (e.g. .NET Core 3.0)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment] 2019-09-29 16:33
Duplicate of #17783

**Closed** 2022-10-16 14:46 UTC
Labels: closed-duplicate, customer-reported
