### ISSUE TITLE
CS0111: Type 'Initial' already defines a member called 'Down' with the same parameter types

### ISSUE THREAD

**Issue by DMW007** [dotnet/efcore#7229] opened 2016-12-11 12:52 UTC
When I'm adding a migration and call them _Initial_ like using the command `Add-Migration Initial`, I got the exception 

> CS0111: Type 'Initial' already defines a member called 'Down' with the same parameter typ es

when I try to write the changes to the Db using `Update-Database`. It seems that _Initial_ is a .NET class. When I change the name to something other like InitialMigration, it works like expected. Maybe it would be a good idea to check if migration names apply to reversed keywords and then inform the developer or defuse the name like adding a _Migration_  suffix or some other word to avoid conflicts.

**Comment by smitpatel** [comment] 2016-12-12 21:25
@DMWOO7 - I am not able to find `Initial` as .NET class. Can you tell us from where it is coming from?

**Comment by divega** [comment] 2017-01-03 19:57
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Comment by anshumandikshit** [comment] 2019-05-31 15:40
There will be a Folder called Migrations in your API .Inside that you will get a 'Initial' class .It has been created by the command Add-Migration Initial

**Closed** 2022-10-16 10:46 UTC
