### ISSUE TITLE
Recursive Insert TEnitiy design time error

### ISSUE THREAD

**Issue by aburcuburcu** [dotnet/efcore#18731] opened 2019-11-03 14:15 UTC
I have an entitiy STUDENT and it has a property GRADE. I want to insert firstly sub entities.
If I try recursive insert because GRADE can contains another sub entitiy too.

My insert function want TEntity, if I cast GRADE as TEntity, code try to assign GRADE as a STUDENT

how can I resolve this problem?

```C#
public int Insert(TEntity entity)
        {
var xx = entity.GetType().GetProperties().Where(x => x.PropertyType.FullName == item.SubPropName).FirstOrDefault();
                Type entityType = xx.PropertyType;
                    var insertableEntity = Activator.CreateInstance(entityType);
                    insertableEntity = cc;

                   var id = Insert((TEntity)insertableEntity);
                }
```

**Comment by ajcvickers** [comment] 2019-11-04 17:49
@aburcuburcu There isn't enough information here for us to be able to effectively investigate. Please post a small, runnable project/solution or complete code listing that demonstrates what you are trying to do and where it is not working.

**Comment by ajcvickers** [comment] 2019-11-11 17:05
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:53 UTC
Labels: closed-could-not-reproduce, customer-reported
