### ISSUE TITLE
Include cause invalid queries

### ISSUE THREAD

**Issue by ostorc** [dotnet/efcore#16124] opened 2019-06-17 15:02 UTC
I have a problem with Include() and ThenInclude() in new version of EF. 

I have an IQueryable<BeiType> collection:
```c#
var entites = Context.Set<BeiType>()Include(t => t.Parents).ThenInclude(t => t.Parent).Include(t => t.Children).ThenInclude(t => t.Child);
```
And have (at least) two problems:

1) When using Where on collection, EF generates invalid SQL
```SQL
SELECT [b].[Id], [b].[AddDate], [b].[AddUser], [b].[ChangeDate], [b].[ChangeUser], [b].[Group], [b].[Key], [b].[Name], [t].[ParentId], [t].[ChildId], [t].[Id], [t].[AddDate], [t].[AddUser], [t].[ChangeDate], [t].[ChangeUser], [t].[Group], [t].[Key], [t].[Name], [b0].[ParentId], [b0].[ChildId], [t0].[ParentId], [t0].[ChildId], [t0].[Id], [t0].[AddDate], [t0].[AddUser], [t0].[ChangeDate], [t0].[ChangeUser], [t0].[Group], [t0].[Key], [t0].[Name]
      FROM [BeiType] AS [b]
      LEFT JOIN (
          SELECT [b0].[ParentId], [b0].[ChildId], [b1].[Id], [b1].[AddDate], [b1].[AddUser], [b1].[ChangeDate], [b1].[ChangeUser], [b1].[Group], [b1].[Key], [b1].[Name]
          FROM [BeiTypeTag] AS [b0]
          INNER JOIN [BeiType] AS [b1] ON [b0].[ParentId] = [b1].[Id]
      ) AS [t] ON [b].[Id] = [t].[ChildId]
      LEFT JOIN (
          SELECT [b2].[ParentId], [b2].[ChildId], [b3].[Id], [b3].[AddDate], [b3].[AddUser], [b3].[ChangeDate], [b3].[ChangeUser], [b3].[Group], [b3].[Key], [b3].[Name]
          FROM [BeiTypeTag] AS [b2]
          INNER JOIN [BeiType] AS [b3] ON [b2].[ChildId] = [b3].[Id]
      ) AS [t0] ON [b].[Id] = [t0].[ParentId]
      WHERE (((@__query_0 = N'') AND @__query_0 IS NOT NULL) OR (CHARINDEX(@__query_0, [b].[Name]) > 0)) OR (((@__query_0 = N'') AND @__query_0 IS NOT NULL) OR (CHARINDEX(@__query_0, [b].[Key]) > 0))
```
```
An exception occurred while iterating over the results of a query for context type 'XXX.XXX.Api.DAL.XXXDbContext'.
      Microsoft.Data.SqlClient.SqlException (0x80131904): The multi-part identifier "b0.ParentId" could not be bound.
      The multi-part identifier "b0.ChildId" could not be bound.
      The multi-part identifier "b0.ParentId" could not be bound.
      The multi-part identifier "b0.ChildId" could not be bound.
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

2. When using FirstOrDefault(e => e.Id == query.Id):
```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.SqlExpressions.SelectExpression.ApplyCollectionJoin(Int32 collectionId, Expression shaperExpression, INavigation navigation)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalShapedQueryOptimizer.Visit(Expression query)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Pipeline.SqlServerShapedQueryOptimizer.Visit(Expression query)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryCompilationContext2.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery2[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
```

### Steps to reproduce
I have two entities:
```c#
public class BeiType
    {
        [Required]
        public BeiTypeGroup Group { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [Required]
        public string Key { get; set; }

        public virtual ICollection<BeiTypeTag> Parents { get; set; }
        public virtual ICollection<BeiTypeTag> Children { get; set; }

        // ....
    }
```
and
```c#
    public class BeiTypeTag
    {
        public virtual Guid ParentId { get; set; }
        public virtual BeiType Parent { get; set; }
        public virtual Guid ChildId { get; set; }
        public virtual BeiType Child { get; set; }
    }
```

with following mapping (only which matters):
```c#
            builder.HasKey(sc => new
            {
                sc.ParentId,
                sc.ChildId
            });

            builder.HasOne(t => t.Parent)
                .WithMany(t => t.Children)
                .HasForeignKey(t => t.ParentId)
                .OnDelete(DeleteBehavior.Restrict); // see the note at the end

            builder.HasOne(t => t.Child)
                .WithMany(t => t.Parents)
                .HasForeignKey(t => t.ChildId);
```

when I try to access data with Includes which I mentioned at start of issue I get errors. When I remove the includes everything works fine (at least the queries returns data)

### Further technical details
.NET Core Preview 6
EF Core version: 3.0.0-preview6.19304.10
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.2 Preview 2

**Comment by ostorc** [comment] 2019-06-17 15:07
Can provide more information about setup of EF, but it's private repo so can't share whole code...

**Comment by maumar** [comment] 2019-06-18 23:55
dupe of #15611

**Comment by divega** [comment] 2019-06-20 18:57
@ostorc thanks for reporting this! We will use #15611 to track the issue.

**Closed** 2022-10-16 14:25 UTC
Labels: customer-reported
