### ISSUE TITLE
Sqlite v3.1.1: "Library e_sqlite3 not found" (on net48 and xunit.runner.visualstudio v2.4.1)

### ISSUE THREAD

**Issue by ngm011** [dotnet/efcore#19893] opened 2020-02-12 14:07 UTC
When running on .NET Framework v4.8 and xUnit Test Runner for Visual Studio v2.4.1 and referencing either Microsoft.EntityFrameworkCore.Sqlite v3.1.1 or PCL raw version of the package, I'm getting:

System.Exception: "Library e_sqlite3 not found"

If I switch to 1) netcoreapp31 with Sqlite v3.1.1 or 2) stay on net48 and switch to Sqlite v2.2.6 everything works fine.

--- ngm

**Comment by ajcvickers** [comment] 2020-02-14 23:10
Duplicate of #19396

**Closed** 2022-10-16 18:10 UTC
Labels: closed-duplicate, customer-reported
