### ISSUE TITLE
Multiple many-to-many joins produce the correct SQL but the wrong result

### ISSUE THREAD

**Issue by fsmirne** [dotnet/efcore#13624] opened 2018-10-14 18:39 UTC
I'm trying to optimize a call using 2 many-to-many relationships into one call using Entity Framework v2.2.0-preview2-35157 and while I was able to produce the right SQL, the resulting object doesn't populate correctly and I get 2 warnings about unnecessary includes which were ignored as described below.

For this example, I'm using a modified **ApplicationUser** class which has a join table to **IdentityRoles<string>** and another join table to a **Store** class which represents a store location such as a mall, address, office building, etc.

What I'm trying to achieve is a call that brings back a **User** with a **Company**, **Roles** and **Stores** in one efficient SQL call but I'm having problem getting it to work correctly. I suspect there's a bug somewhere that doesn't understand nested **SelectMany** calls and ignores the results produced by the SQL call.

Here are my classes:

### ApplicationUser.cs
```C#
public class ApplicationUser : IdentityUser
{
	[Required]
	public string FullName { get; set; }

	[Required]
	public string TimeZone { get; set; }

	public int CompanyId { get; set; }

	[Required]
	public Company Company { get; set; }

	public virtual ICollection<UserStore> Stores { get; set; }
	public virtual ICollection<UserRole> Roles { get; set; }
}
```

### Company.cs
```C#
public class Company
{
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public int Id { get; set; }

	[Required]
	public string Name { get; set; }

	public virtual ICollection<Store> Stores { get; set; }
	public virtual ICollection<ApplicationUser> Users { get; set; }
}
```

### UserViewModel.cs
```C#
public class UserViewModel
{
	public string Id { get; set; }
	public string Name { get; set; }
	public string Email { get; set; }
	public string TimeZone { get; set; }
	public string PhoneNumber { get; set; }
	public int CompanyId { get; set; }
	public string Company { get; set; }
	public string Store { get; set; }
	public bool LockedOut { get; set; }
	public string Role { get; set; }
}
```

### ApplicationRole.cs
```C#
public class ApplicationRole : IdentityRole<string>
{
	public ApplicationRole() : base() { }
	public ApplicationRole(string roleName) : base(roleName) { }

	public ICollection<UserRole> Users { get; set; }
}
```

### UserRole.cs
```C#
public class UserRole
{
	public string UserId { get; set; }
	public ApplicationUser User { get; set; }

	public string RoleId { get; set; }
	public ApplicationRole Role { get; set; }
}
```

### Store.cs
```C#
public class Store
{
	public string Name { get; set; }
	public string Address { get; set; }
	public string City { get; set; }
	public string State { get; set; }
	public string PostalCode { get; set; }
	public string PhoneNumber { get; set; }

	public virtual ICollection<UserStore> Users { get; set; }
}
```

### UserStore.cs
```C#
public class UserStore
{
	public string UserId { get; set; }
	public ApplicationUser User { get; set; }

	public int StoreId { get; set; }
	public Store Store { get; set; }
}
```

### And finally, this is the call that I'm making:
```C#
var now = DateTime.UtcNow;
var users = await _userManager.Users
				.Include(u => u.Stores)
				.ThenInclude(us => us.Store)
				.Include(u => u.Roles)
				.ThenInclude(ur => ur.Role)
				.SelectMany(u => u.Stores.DefaultIfEmpty(), (u, us) => new { User = u, Store = us })
				.SelectMany(x => x.User.Roles.DefaultIfEmpty(), (x, ur) =>
				new UserViewModel
				{
					Id = x.User.Id,
					Name = x.User.FullName,
					Email = x.User.Email,
					PhoneNumber = x.User.PhoneNumber,
					Company = x.User.Company.Name,
					CompanyId = x.User.CompanyId,
					TimeZone = x.User.TimeZone,
					LockedOut = x.User.LockoutEnabled && x.User.LockoutEnd.HasValue && x.User.LockoutEnd >= now,
					Store = x.Store.Store.Name,
					Role = ur.Role.Name
				}
			).ToListAsync();
```

### Here are the logs I get during the call:
```
Microsoft.EntityFrameworkCore.Infrastructure:Information: Entity Framework Core 2.2.0-preview2-35157 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Microsoft.EntityFrameworkCore.Query:Warning: The Include operation for navigation '[u].Stores.Store' is unnecessary and was ignored because the navigation is not reachable in the final query results. See https://go.microsoft.com/fwlink/?linkid=850303 for more information.
Microsoft.EntityFrameworkCore.Query:Warning: The Include operation for navigation '[u].Roles.Role' is unnecessary and was ignored because the navigation is not reachable in the final query results. See https://go.microsoft.com/fwlink/?linkid=850303 for more information.
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (9ms) [Parameters=[@__now_0='?' (DbType = DateTimeOffset)], CommandType='Text', CommandTimeout='30']
SELECT [u].[Id], [u].[FullName] AS [Name0], [u].[Email], [u].[PhoneNumber], [u.Company].[Name] AS [Company], [u].[CompanyId], [u].[TimeZone], CASE
    WHEN (([u].[LockoutEnabled] = 1) AND [u].[LockoutEnd] IS NOT NULL) AND ([u].[LockoutEnd] >= @__now_0)
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END AS [LockedOut], [u.Stores.Store].[Name] AS [Store], [u.Roles.Role].[Name] AS [Role]
FROM [AspNetUsers] AS [u]
INNER JOIN [Companies] AS [u.Company] ON [u].[CompanyId] = [u.Company].[Id]
LEFT JOIN [UserRole] AS [u.Roles] ON [u].[Id] = [u.Roles].[UserId]
LEFT JOIN [AspNetRoles] AS [u.Roles.Role] ON [u.Roles].[RoleId] = [u.Roles.Role].[Id]
LEFT JOIN [UserStores] AS [u.Stores] ON [u].[Id] = [u.Stores].[UserId]
LEFT JOIN [Stores] AS [u.Stores.Store] ON [u.Stores].[StoreId] = [u.Stores.Store].[Id]
```

### Expected Results
At the end of this call, I expected to see **Role** and **Store** populated, but they are null. I believe due to the warnings I'm getting where the navigation properties are not being used.
Is there anything I can do to prevent this behavior?

Let em know if you need any more information and I'll be glad to provide.

### Further technical details
EF Core version: (Entity Framework v2.2.0-preview2-35157)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.8)

**Comment by maumar** [comment] 2018-10-16 19:08
The reason why includes are ignored is that in the entities that are include roots are not present in the final projection - you are only projecting scalars, so EF sees no need in actually applying includes for this query.

To enable includes, you need to project the entities, like so:

```
                var now = DateTime.UtcNow;
                var users = ctx.Users
                                .Include(u => u.Stores)
                                .ThenInclude(us => us.Store)
                                .Include(u => u.Roles)
                                .ThenInclude(ur => ur.Role)
                                .SelectMany(u => u.Stores.DefaultIfEmpty(), (u, us) => new { User = u, Store = us })
                                .SelectMany(x => x.User.Roles.DefaultIfEmpty(), (x, ur) =>
                                new //UserViewModel
                                {
                                    Id = x.User.Id,
                                    Name = x.User.FullName,
                                    Email = x.User.Email,
                                    PhoneNumber = x.User.PhoneNumber,
                                    Company = x.User.Company.Name,
                                    CompanyId = x.User.CompanyId,
                                    TimeZone = x.User.TimeZone,
                                    LockedOut = x.User.LockoutEnabled && x.User.LockoutEnd.HasValue && x.User.LockoutEnd >= now,
                                    Store = x.Store.Store.Name,
                                    Role = ur.Role.Name,
                                    UserEntity = x.User, // added
                                    StoreEntity = x.Store // added
                                }
                            ).ToList();
```

**Comment by fsmirne** [comment] 2018-10-16 19:41
Hey @maumar,

Thanks for looking into this. Unfortunately, when I include the ApplicationUser in the result, I get a very inefficient SQL. Everything is pulled back and that defeats the purpose of trying to select only the columns I need from the database.

Take a look at the log generated by your code:
```
Microsoft.EntityFrameworkCore.Infrastructure:Information: Entity Framework Core 2.2.0-preview2-35157 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [u].[Id], [u].[AccessFailedCount], [u].[CompanyId], [u].[ConcurrencyStamp], [u].[Email], [u].[EmailConfirmed], [u].[FullName] AS [Name0], [u].[LastLoginDate], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TimeZone], [u].[TwoFactorEnabled], [u].[UserName], [u.Company].[Name] AS [Company], [u.Stores.Store].[Name] AS [Store], [u.Roles.Role].[Name] AS [Role]
FROM [AspNetUsers] AS [u]
INNER JOIN [Companies] AS [u.Company] ON [u].[CompanyId] = [u.Company].[Id]
LEFT JOIN [UserRole] AS [u.Roles] ON [u].[Id] = [u.Roles].[UserId]
LEFT JOIN [ApplicationRole] AS [u.Roles.Role] ON [u.Roles].[RoleId1] = [u.Roles.Role].[Id]
LEFT JOIN [UserStores] AS [u.Stores] ON [u].[Id] = [u.Stores].[UserId]
LEFT JOIN [Stores] AS [u.Stores.Store] ON [u.Stores].[StoreId] = [u.Stores.Store].[Id]
ORDER BY [u].[Id]
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [u.Stores0].[UserId], [u.Stores0].[StoreId], [u.Store].[Id], [u.Store].[Address], [u.Store].[City], [u.Store].[CompanyId], [u.Store].[MerchantId], [u.Store].[Name], [u.Store].[PhoneNumber], [u.Store].[PostalCode], [u.Store].[State], [u.Store].[StoreId]
FROM [UserStores] AS [u.Stores0]
INNER JOIN [Stores] AS [u.Store] ON [u.Stores0].[StoreId] = [u.Store].[Id]
INNER JOIN (
    SELECT DISTINCT [u0].[Id]
    FROM [AspNetUsers] AS [u0]
    INNER JOIN [Companies] AS [u.Company0] ON [u0].[CompanyId] = [u.Company0].[Id]
    LEFT JOIN [UserRole] AS [u.Roles0] ON [u0].[Id] = [u.Roles0].[UserId]
    LEFT JOIN [ApplicationRole] AS [u.Roles.Role0] ON [u.Roles0].[RoleId1] = [u.Roles.Role0].[Id]
    LEFT JOIN [UserStores] AS [u.Stores1] ON [u0].[Id] = [u.Stores1].[UserId]
    LEFT JOIN [Stores] AS [u.Stores.Store0] ON [u.Stores1].[StoreId] = [u.Stores.Store0].[Id]
) AS [t] ON [u.Stores0].[UserId] = [t].[Id]
ORDER BY [t].[Id]
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [u.Roles1].[UserId], [u.Roles1].[RoleId], [u.Roles1].[RoleId1], [u.Role].[Id], [u.Role].[ConcurrencyStamp], [u.Role].[Name], [u.Role].[NormalizedName]
FROM [UserRole] AS [u.Roles1]
INNER JOIN [ApplicationRole] AS [u.Role] ON [u.Roles1].[RoleId1] = [u.Role].[Id]
INNER JOIN (
    SELECT DISTINCT [u1].[Id]
    FROM [AspNetUsers] AS [u1]
    INNER JOIN [Companies] AS [u.Company1] ON [u1].[CompanyId] = [u.Company1].[Id]
    LEFT JOIN [UserRole] AS [u.Roles2] ON [u1].[Id] = [u.Roles2].[UserId]
    LEFT JOIN [ApplicationRole] AS [u.Roles.Role1] ON [u.Roles2].[RoleId1] = [u.Roles.Role1].[Id]
    LEFT JOIN [UserStores] AS [u.Stores2] ON [u1].[Id] = [u.Stores2].[UserId]
    LEFT JOIN [Stores] AS [u.Stores.Store1] ON [u.Stores2].[StoreId] = [u.Stores.Store1].[Id]
) AS [t0] ON [u.Roles1].[UserId] = [t0].[Id]
ORDER BY [t0].[Id]
```

Also, I would like to avoid anonymous objects as I'm sending this to a View. This is something that I can work around, but ideally I wouldn't need to make 2 copies of the data to get to the UserViewModel object.

Do you have any idea on how to optimize this? I assume this is something very common that people want to do, meaning, most databases will have N number of many-to-many relationships and it's very common to be able to pull this data all in one SQL call.

Thanks again for your help!

**Comment by maumar** [comment] 2018-10-16 20:19
In EFCore, when we do include on collection navigations we split the query into multiple chunks to avoid pulling same data multiple times. So, if you want to fetch an entity and some of its collection navigations you will always have multiple queries - there is no easy way to do it in one query. In EF6 we used to do that but it had its problems. 

Consider a scenario with customers and orders, 2 customers, 5 orders each.
When doing it in one query we would pull the following data:

```
customer1, order11
customer1, order12
customer1, order13
customer1, order14
customer1, order15
customer2, order11
customer2, order12
customer2, order13
customer2, order14
customer2, order15
```

Total of 20 objects (customer1 and customer2 pulled unnecessarily 4 times each). With the new approach we are pulling:

Query1:
```
customer1
customer2
```

Query2:
```
order11,
order12
order13
order14
order15
order21,
order22
order23
order24
order25
```

Total of 12 objects. There is an overhead of executing multiple queries but as you include more collections (e.g. `customers.Include(c => c.Orders).ThenInclude(o => o.OrderDetails)` the number of unnecessary data that needs to get pulled blows up really quickly.

Than being said, if you only want the scalar values in the result then the include calls are not needed. Include is only useful if you are bringing back entire entities and want their navigation properties populated so you can manipulate them on the client. When u are returning only scalars and no entities, EF should automatically expand all the navigations it needs to properly extract those scalar values and buiild the final projection. The problem you are facing might be that the translation is actually incorrect.

Could you post the contents of your OnModelCreating method on DbContext and source code for all the base entities (IdentityUser, IdentityRole<T> etc) so I can investigate precisely the scenario you are dealing with?

**Comment by fsmirne** [comment] 2018-10-16 20:32
Sure. My User and Role classes are above as well as the join table classes. The only modification I made to the IdentityUser and IdentityRole is to add a navigation property so that User has a collection of Roles and a Role has a collection of users as you can see above.

Here's my OnModelCreating code. (I left only the relevant parts as this is a very big project) :
```
protected override void OnModelCreating(ModelBuilder builder)
{
	base.OnModelCreating(builder);
	// Customize the ASP.NET Identity model and override the defaults if needed.
	// For example, you can rename the ASP.NET Identity table names and more.
	// Add your customizations after calling base.OnModelCreating(builder);
		
	// Define many to many relationships
	builder.Entity<Models.UserStore>().HasKey(ub => (new { ub.UserId, ub.StoreId }));
	builder.Entity<UserRole>().HasKey(ur => (new { ur.UserId, ur.RoleId }));
}

Thanks!

**Comment by maumar** [comment] 2018-10-16 22:05
@fsmirne I'm unable to repro this. Created the following project, populated with some sample data and ran the query. Everything seems to be coming back fine - tested the results against same query on Linq to objects and they came back the same.

Can you try running the project on your environment and modify it so that it reproduces the problem? Perhaps specific data configuration is needed but it's quite hard for me to predict what that could be.

If my code will fail for you then I guess the issue is already fixed in the current build. We recently fixed a bug around this area (fix landed in preview3 - https://github.com/aspnet/EntityFrameworkCore/issues/13511) that could be what you are hitting, although the fix was correcting SQL and the query that I'm seeing in the repro is the same as yours.

Anyway, here is the full sample:

```cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace Repro13624
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var company1 = new Company
                {
                    Name = "Company1"
                };

                var company2 = new Company
                {
                    Name = "Company2"
                };

                var company3 = new Company
                {
                    Name = "Company3"
                };

                var store1 = new Store
                {
                    Address = "store address1",
                    City = "Store city1",
                    Name = "store name 1",
                    PhoneNumber = "store pn1",
                    PostalCode = "store pc1",
                    State = "store state1",
                };

                var store2 = new Store
                {
                    Address = "store address2",
                    City = "Store city2",
                    Name = "store name 2",
                    PhoneNumber = "store pn2",
                    PostalCode = "store pc2",
                    State = "store state2",
                };

                var appUser1 = new ApplicationUser
                {
                    Id = "AU1",
                    Company = company1,
                    Email = "email1",
                    FullName = "Fullname1",
                    LockoutEnabled = true,
                    LockoutEnd = new DateTime(2000, 1, 1),
                    PhoneNumber = "pn1",
                    TimeZone = "tz1"
                };

                var appUser2 = new ApplicationUser
                {
                    Id = "AU2",
                    Company = company1,
                    Email = "email2",
                    FullName = "Fullname2",
                    LockoutEnabled = true,
                    LockoutEnd = new DateTime(2002, 1, 1),
                    PhoneNumber = "pn2",
                    TimeZone = "tz2"
                };

                var appUser3 = new ApplicationUser
                {
                    Id = "AU3",
                    Company = company1,
                    Email = "email3",
                    FullName = "Fullname3",
                    LockoutEnabled = true,
                    LockoutEnd = new DateTime(2002, 1, 1),
                    PhoneNumber = "pn3",
                    TimeZone = "tz3"
                };

                var appRole1 = new ApplicationRole
                {
                    Id = "1",
                    Name = "app role1",
                };

                var appRole2 = new ApplicationRole
                {
                    Id = "2",
                    Name = "app role2",
                };

                var appRole3 = new ApplicationRole
                {
                    Id = "3",
                    Name = "app role3",
                };

                var appRole4 = new ApplicationRole
                {
                    Id = "4",
                    Name = "app role4",
                };

                var userstore11 = new UserStore { User = appUser1, Store = store1 };
                var userstore12 = new UserStore { User = appUser1, Store = store2 };
                var userstore21 = new UserStore { User = appUser2, Store = store1 };
                var userstore22 = new UserStore { User = appUser2, Store = store2 };
                var userstore32 = new UserStore { User = appUser3, Store = store2 };

                var userrole11 = new UserRole { User = appUser1, Role = appRole1 };
                var userrole13 = new UserRole { User = appUser1, Role = appRole3 };
                var userrole21 = new UserRole { User = appUser2, Role = appRole1 };
                var userrole22 = new UserRole { User = appUser2, Role = appRole2 };
                var userrole31 = new UserRole { User = appUser3, Role = appRole1 };
                var userrole32 = new UserRole { User = appUser3, Role = appRole2 };
                var userrole33 = new UserRole { User = appUser3, Role = appRole3 };

                ctx.Companies.AddRange(company1, company2, company3);
                ctx.Stores.AddRange(store1, store2);
                ctx.Users.AddRange(appUser1, appUser2, appUser3);
                ctx.AppRoles.AddRange(appRole1, appRole2, appRole3, appRole4);
                ctx.UserStores.AddRange(userstore11, userstore12, userstore21, userstore22, userstore32);
                ctx.UserRoles.AddRange(userrole11, userrole13, userrole21, userrole22, userrole31, userrole32, userrole33);

                ctx.SaveChanges();
            }

            using (var ctx = new MyContext())
            {
                var now = DateTime.UtcNow;
                var users = ctx.Users
                    .SelectMany(u => u.Stores.DefaultIfEmpty(), (u, us) => new { User = u, Store = us })
                    .SelectMany(x => x.User.Roles.DefaultIfEmpty(), (x, ur) =>
                    new UserViewModel
                    {
                        Id = x.User.Id,
                        Name = x.User.FullName,
                        Email = x.User.Email,
                        PhoneNumber = x.User.PhoneNumber,
                        Company = x.User.Company.Name,
                        CompanyId = x.User.CompanyId,
                        TimeZone = x.User.TimeZone,
                        LockedOut = x.User.LockoutEnabled && x.User.LockoutEnd.HasValue && x.User.LockoutEnd >= now,
                        Store = x.Store.Store.Name,
                        Role = ur.Role.Name,
                    }).ToList().OrderBy(e => e.Role).ThenBy(e => e.Store).ToList(); // added ordering on the client for purpose of verification

                var baseline = ctx.Users.Include(u => u.Company).Include(u => u.Stores).ThenInclude(us => us.Store).Include(u => u.Roles).ThenInclude(r => r.Role).ToList()
                    .SelectMany(u => u.Stores.DefaultIfEmpty(), (u, us) => new { User = u, Store = us })
                    .SelectMany(x => x.User.Roles.DefaultIfEmpty(), (x, ur) =>
                    new UserViewModel
                    {
                        Id = x.User.Id,
                        Name = x.User.FullName,
                        Email = x.User.Email,
                        PhoneNumber = x.User.PhoneNumber,
                        Company = x.User.Company.Name,
                        CompanyId = x.User.CompanyId,
                        TimeZone = x.User.TimeZone,
                        LockedOut = x.User.LockoutEnabled && x.User.LockoutEnd.HasValue && x.User.LockoutEnd >= now,
                        Store = x.Store.Store.Name,
                        Role = ur.Role.Name,
                    }).ToList().OrderBy(e => e.Role).ThenBy(e => e.Store).ToList();

                if (users.Count != baseline.Count)
                {
                    Console.WriteLine("wrong count");
                }

                // verification against linq to objects
                for (var i = 0; i < users.Count; i++)
                {
                    Console.WriteLine(i);
                    Console.WriteLine("Company: " + (users[i].Company == baseline[i].Company));
                    Console.WriteLine("CompanyId: " + (users[i].CompanyId == baseline[i].CompanyId));
                    Console.WriteLine("Email: " + (users[i].Email == baseline[i].Email));
                    Console.WriteLine("Id: " + (users[i].Id == baseline[i].Id));
                    Console.WriteLine("LockedOut: " + (users[i].LockedOut == baseline[i].LockedOut));
                    Console.WriteLine("Name: " + (users[i].Name == baseline[i].Name));
                    Console.WriteLine("PhoneNumber: " + (users[i].PhoneNumber == baseline[i].PhoneNumber));
                    Console.WriteLine("Role: " + (users[i].Role == baseline[i].Role));
                    Console.WriteLine("Store: " + (users[i].Store == baseline[i].Store));
                    Console.WriteLine("TimeZone: " + (users[i].TimeZone == baseline[i].TimeZone));
                }
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<ApplicationUser> Users { get; set; }

        public DbSet<Company> Companies { get; set; }

        public DbSet<ApplicationRole> AppRoles { get; set; }

        public DbSet<UserRole> UserRoles { get; set; }

        public DbSet<Store> Stores { get; set; }
        public DbSet<UserStore> UserStores {get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=Repro13624;Trusted_Connection=True;MultipleActiveResultSets=True");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserRole>().HasKey(e => new { e.UserId, e.RoleId });
            modelBuilder.Entity<UserStore>().HasKey(e => new { e.UserId, e.StoreId });
        }
    }

    public class IdentityUser
    {
        public string Id { get; set; }

        public string Email { get; set; }

        public string PhoneNumber { get; set; }

        public bool LockoutEnabled { get; set; }

        public DateTime? LockoutEnd { get; set; }
    }

    public class ApplicationUser : IdentityUser
    {
        [Required]
        public string FullName { get; set; }

        [Required]
        public string TimeZone { get; set; }

        public int CompanyId { get; set; }

        [Required]
        public Company Company { get; set; }

        public virtual ICollection<UserStore> Stores { get; set; }
        public virtual ICollection<UserRole> Roles { get; set; }
    }

    public class Company
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public virtual ICollection<Store> Stores { get; set; }
        public virtual ICollection<ApplicationUser> Users { get; set; }
    }

    public class UserViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string TimeZone { get; set; }
        public string PhoneNumber { get; set; }
        public int CompanyId { get; set; }
        public string Company { get; set; }
        public string Store { get; set; }
        public bool LockedOut { get; set; }
        public string Role { get; set; }
    }

    public class IdentityRole<T>
    {
        public string Id { get; set; }

        public T Name { get; set; }
    }

    public class ApplicationRole : IdentityRole<string>
    {
        public ICollection<UserRole> Users { get; set; }
    }

    public class UserRole
    {
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }

        public string RoleId { get; set; }
        public ApplicationRole Role { get; set; }
    }

    public class Store
    {
        public int Id { get; set; }

        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }

        public virtual ICollection<UserStore> Users { get; set; }
    }

    public class UserStore
    {
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }

        public int StoreId { get; set; }
        public Store Store { get; set; }
    }
}
```

**Closed** 2022-10-16 13:35 UTC
Labels: closed-could-not-reproduce, customer-reported
