### ISSUE TITLE
Cannot assign `null` to optional relationship if a shadow foreign key is used.

### ISSUE THREAD

**Issue by denschub** [dotnet/efcore#25217] opened 2021-07-07 19:19 UTC
Assuming the following models:

```cs
public class Banana {
  public int Id { get; set; }
  public Consumer? Consumer { get; set; }
}

public class Consumer {
  public int Id { get; set; }
}
```

Assigning a `Consumer` to a `Banana` works fine with:

```cs
myBanana.Consumer = dbContext.Consumers.First(row => row.Id == 1);
dbContext.Update(myBanana);
dbContext.SaveChanges();
```

Even though there is no explicit `ConsumerId` property as foreign key, [the documentation explicitly states](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#no-foreign-key-property)

> While it is recommended to have a foreign key property defined in the dependent entity class, it is not required. **If no foreign key property is found, a shadow foreign key property will be introduced**

and that works just fine, as the migration built a `ConsumerId` database column and is updating that.

However, it's not possible to assign `null` to that relation ever again, as trying to set it via

```cs
myBanana.Consumer = null;
dbContext.Update(myBanana);
dbContext.SaveChanges();
```

doesn't actually update the `ConsumerId` database column. You can still manually set the shadow foreign key property to `null` using

```cs
dbContext.Entry(myBanana).Property("ConsumerId").CurrentValue = null;
```

If "always explicitly define the foreign key" is the answer, then feel free to close, but I wanted to raise the issue nonetheless, given it's a bit confusing, especially since I could not find any "gotchas" about using a shadow foreign key in the docs. :)

EF Core version: 5.0.7
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 5.0.7
Target framework: .NET 5.0

**Comment by smitpatel** [comment] 2021-07-07 20:06
The issue is, EF Core doesn't know which consumer to delete because it doesn't have information about existing consumer. Navigation properties can be null or empty (in other words not loaded - unknown value) since to use an entity you don't always need all of its navigations loaded. So when you set navigation to null which was already null before, there is no changes EF can detect and issue update command. If you load the navigation from database so that `myBanana.Consumer` has value before setting it to null, EF Core will issue appropriate update command. See https://docs.microsoft.com/en-us/ef/core/querying/related-data/

If you want to delete the associated record without loading navigation, then you would have to work with the fk property and assign it appropriate value.

**Comment by denschub** [comment] 2021-07-07 20:47
Oh, that makes perfect sense! In my case, I had a no-tracking Entity that was generated via Model Binding, so I couldn't even load the related data easily. But fetching the tracked entity allowed me to use `TryUpdateModelAsync` set the assignment, and you're right, that worked.

So this is not a bug, but rather user error from an inexperienced guy. Hah. Thanks for your explanation, that helped a lot. :)

**Closed** 2022-10-16 19:39 UTC
Labels: closed-no-further-action, customer-reported
