### ISSUE TITLE
Db.db-shm and db.db-wal cannot be cleaned up automatically

### ISSUE THREAD

**Issue by 84819760** [dotnet/efcore#26845] opened 2021-11-29 11:30 UTC
class
```C#
public class Table1
{
    public long Id { get; set; }

    public string? Value { get; set; }
}

public class DbContext : Microsoft.EntityFrameworkCore.DbContext
{
    public DbSet<Table1>? Tables { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        var conn = new SqliteConnectionStringBuilder()
        {
            DataSource = @"D:\tmp\EF6.db",
        };
        optionsBuilder.UseSqlite(conn.ToString());
    }
}
```

Program.cs
```C#
using var db = new DbContext();
using var bt = db.Database.BeginTransaction();
Enumerable.Range(0, 10000)
    .Select(i => new Table1 { Value = i.ToString() })
    .ToList()
    .ForEach(item => db.Add(item));
await bt.CommitAsync();
await db.SaveChangesAsync();
```

The above code can be executed normally in `entityframeworkcore5`, and `ef6.db-shm` and `ef6.db-wal` can be cleaned up automatically.

After upgrading `entityframeworkcore6`, a write data exception will occur. Data will only be written to `ef6.db-wal`. There is no data in `ef6.db`, and `ef6.db-shm` and `ef6.db-wal` will not be cleaned up automatically. This phenomenon also occurs when `PM> Update-Database`is executed.

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.Sqlite 6.0.0)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.0.1)

**Comment by ajcvickers** [comment] 2021-11-29 11:40
Duplicate of #26422.

**Comment by 84819760** [comment] 2021-11-29 11:57
> 复本#26422.

Thank you.

**Closed** 2022-10-16 20:16 UTC
Labels: closed-duplicate, customer-reported
