### ISSUE TITLE
Add sugar to get the underlying column type

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#7461] opened 2017-01-24 08:06 UTC
Looks like ColumnType returns null unless explicitly set??

(1.2-preview1)

**Comment by ajcvickers** [comment] 2017-01-24 17:04
@ErikEJ This is by design. We discussed a lot a couple of years ago whether to store the type mappings in the model or to look them up at runtime. #7166 might change this for 2.0, but as of now the type mapping should be obtained at runtime using the IRelationalTypeMapper. That being said, I think it would be good to put some sugar over this so apps don't have to get and use the raw service. I'll leave this bug open to track that.

**Comment by ErikEJ** [comment] 2017-01-24 17:13
@ajcvickers Yes, I think that would be very useful! So for now I will have to get the Typemapper service and call FindMappping?

**Comment by ErikEJ** [comment] 2017-01-24 17:14
Sample: https://github.com/aspnet/EntityFramework/issues/7351

**Comment by ajcvickers** [comment] 2017-01-24 17:15
@ErikEJ Correct.

**Comment by RandyBuchholz** [comment] 2017-01-27 16:33
This is similar to my post about adding Type Metadata [Type Metadata - Add DataDomain Attribute and Domain Concepts #7132](https://github.com/aspnet/EntityFramework/issues/7132). 

Maybe add something along the lines of the "context" pattern. Model elements/entities could have a context container and handler for the container. This provides a general extension point for framework developers and solutions developers, and my be very helpful for provider developers.

Building on this, I can see it as a transport layer for bringing custom CLR types through (even transparently) EF. A little like Viewdata/ViewBag in MVC. If EF encounters a type it doesn't understand it can stick it into context.DataBag. It is up to the developer to be able to use it, but at least it is there.

**Comment by ajcvickers** [comment] 2017-05-27 00:58
Ended up being a dupe of #8034 since because of #7166 we are now able to have ColumnType return the correct value once the model is built, even if if no explicit store type was set.

**Closed** 2022-10-16 10:51 UTC
