### ISSUE TITLE
SqlException: "No column name was specified for column 1 of 't'" on IQueryable.Count() with Skip and Take

### ISSUE THREAD

**Issue by hvkooten** [dotnet/efcore#30239] opened 2023-02-02 15:50 UTC
### Description

Retrieving the number of records via Count() in a IQueryable with Skip() and Take() results in an exception:

### Reproduction Steps

```
var query = context.Set<TestView>().Where(q => q.ItemType== itemType).AsQueryable();
var total = query.Count();
query =query.Skip(0).Take(1000);
var subTotal = query.Count();
```

### Expected behavior

First Count() results in SQL statement:
```
exec sp_executesql N'SELECT COUNT(*)
FROM [View] AS [a]
WHERE [a].[ItemType] = @__Type_0',N'@__Type_0 nvarchar(4000)',@__Type_0=N'PO'
```
expected: returns rowcount

Second Count() results in SQL statement:
```
exec sp_executesql N'SELECT COUNT(*)
FROM (
    SELECT 1 AS column1
    FROM [View] AS [a]
    WHERE [a].[ItemType] = @__Type_0
    ORDER BY (SELECT 1)
    OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY
) AS [t]',N'@__Type_0 nvarchar(4000),@__p_1 int,@__p_2 int',@__Type_0=N'PO',@__p_1=0,@__p_2=1000
```
expected: returns 1000

### Actual behavior

Second Count() results in SQL statement:
```
exec sp_executesql N'SELECT COUNT(*)
FROM (
    SELECT 1
    FROM [View] AS [a]
    WHERE [a].[ItemType] = @__Type_0
    ORDER BY (SELECT 1)
    OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY
) AS [t]',N'@__Type_0 nvarchar(4000),@__p_1 int,@__p_2 int',@__Type_0=N'PO',@__p_1=0,@__p_2=1000
```
and throws a sqlexception: "No column name was specified for column 1 of 't'"

### Regression?

In .net 6.0 this works, but while moving to .net 7.0 we got this exception.

### Known Workarounds

`query.ToList().count;`
But this will materialize the query and send all data to memory

### Configuration

.net 7.0
development: Windows
production: Azure

### Other information

The problem is, there is no column name in the query. By adding "AS column1" in the select statement the query will work.

**Comment by maumar** [comment] 2023-02-10 09:24
looks like a dupe of https://github.com/dotnet/efcore/issues/29667

**Closed** 2023-02-15 12:21 UTC
Labels: customer-reported
