### ISSUE TITLE
Long Compilation Time and Large Designer Files in EF Core 7 Project

### ISSUE THREAD

**Issue by haoyk** [dotnet/efcore#33137] opened 2024-02-22 03:45 UTC
I am developing a project using EF Core 7, which involves around 300 tables and over 200 migrations. Each migration's Designer file is exceptionally large, leading to extended project compilation times. I am seeking advice on how to address and optimize this issue.

**Comment by ajcvickers** [comment] 2024-02-22 08:45
Duplicate of #2174

**Comment by roji** [comment] 2024-02-22 22:56
@haoyk the Designer file being exceptionally large points to you possibly including large seeding data or similar, which is highly discouraged ([see seeding docs](https://learn.microsoft.com/en-us/ef/core/modeling/data-seeding#limitations-of-model-seed-data)).

**Closed** 2024-02-28 13:33 UTC
Labels: closed-duplicate, customer-reported

**Comment by babriSakaiTech** [comment] 2024-03-27 17:13
> @haoyk the Designer file being exceptionally large points to you possibly including large seeding data or similar, which is highly discouraged ([see seeding docs](https://learn.microsoft.com/en-us/ef/core/modeling/data-seeding#limitations-of-model-seed-data)).

Hi Roji, even without seeding any data, designer files get huge quickly in large applications. For instance, there are 500+ tables in my current project, and every designer file is 30k+ lines (~1MB).  This leads to over 2 minutes of build time (instead of a few seconds without the designer files).

For now, I've added a condition to unload all designer files from the project in debug mode, and only load the last few ones when actively creating new migrations. A proper official fix would be welcome though.

**Comment by roji** [comment] 2024-03-27 18:16
For now, the only solution we can propose is to periodically squash your migrations, i.e. begin over - that makes sense when you know that all production servers are aligned on the latest migration, and keeping the history has very little value - [see the docs for that](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#resetting-all-migrations). #2174 tracks a more first-class experience for that.
