### ISSUE TITLE
Migration script issue when changing 'old' nullable types to non nullable types

### ISSUE THREAD

**Issue by administersoftware** [dotnet/efcore#18794] opened 2019-11-07 09:03 UTC
I made a change to 2 entities, in one I changed the type of one property from INT? to INT and in another entity I changed the type of one property from LONG? to LONG, yet the migration script generated me a blank Migration class, well when I say blank it had the Up and Down Methods but no migrationBuilder.AlterColumn code :(

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.0
Operating system: W10
IDE: Visual Studio 2019 16.3

**Comment by ajcvickers** [comment] 2019-11-08 21:40
@administersoftware Were the properties keys? Are they specified anywhere as `Required`?

It would really help if you could post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by administersoftware** [comment] 2019-11-08 22:33
> 
> 
> @administersoftware Were the properties keys? Are they specified anywhere as `Required`?
> 
> It would really help if you could post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

No @ajcvickers, they were just regular properties. One of the properties was originally an INT? that I changed to a LONG? and the add-migration created a script to AlterColumn, but when I then decided that I wanted the LONG? to become LONG the add-migration created a script with empty Up and Down methods.

I'll see if I can knock up a quick example for you over the next couple of days. To fix it I just provided the script within the Up and Down methods, but thought I'd better report it just in case it was an issue.

**Comment by ajcvickers** [comment] 2020-06-05 17:29
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:54 UTC
Labels: closed-could-not-reproduce, customer-reported
