### ISSUE TITLE
Injecting dbContext into startup.cs fails in EF Core 2.1 Preview 2

### ISSUE THREAD

**Issue by Metritutus** [dotnet/efcore#11891] opened 2018-05-03 19:02 UTC
Previously I have been able to inject my `DbContext` into `startup.cs` from `program.cs`.  However, now in 2.1 Preview 2 it no longer works and fails with an `InvalidOperationException` ('Cannot resolve scoped service 'MyWebAPI.Models.MyDbContext' from root provider.').

Being fairly new to all this, I'm not sure if this is a bug or if I need to somehow change the way I'm injecting my `DbContext` into `startup.cs`.  I did try to search for any existing issues or changes that may have caused this issue, but could not find anything, however that may simply be due to me not knowing the correct terminology to describe this issue.

The code to replicate this issue (taken from a stock new Web API project), the stacktrace, and other details are below:

`Program.cs`
```cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using MyWebAPI.Models;

namespace MyWebAPI
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureServices(builder =>
                {
                    builder.AddDbContext<MyDbContext>(options => options.UseInMemoryDatabase(""));
                })
                .UseStartup<Startup>();
    }
}
```
`Startup.cs`
```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using MyWebAPI.Models;

namespace MyWebAPI
{
    public class Startup
    {
        public IConfiguration Configuration { get; }
        public MyDbContext Context { get; }

        public Startup(IConfiguration configuration, MyDbContext context)
        {
            Configuration = configuration;
            Context = context;
        }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseMvc();
        }
    }
}
```

`MyDbContext.cs`
```cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyWebAPI.Models
{
    public class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions<MyDbContext> options)
             : base(options)
        {
        }
    }
}

```

Exception message: `System.InvalidOperationException: 'Cannot resolve scoped service 'MyWebAPI.MyDbContext' from root provider.'`

Stack trace:
```cs
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at MyWebAPI.Program.Main(String[] args) in c:\<REMOVED>\Program.cs:line 20
```

### Further technical details
EF Core version: 2.1 Preview 2 Final
Database Provider: May be N/A (replicated with InMemoryDatabase (as in the example above) and with SQL Server.
Operating system: Windows 10
IDE: Visual Studio 2017 15.7 Preview 4.0

**Comment by smitpatel** [comment] 2018-05-03 19:58
https://github.com/aspnet/Hosting/blob/ae9da9290eb825f4145aaaa23603186d51211e53/src/Microsoft.AspNetCore.Hosting/WebHostBuilderExtensions.cs#L50-L71

Startup class is registered as `Singleton` & DbContext is `Scoped` service. You cannot resolve a scoped service from a singleton service.

**Comment by Metritutus** [comment] 2018-05-03 21:14
> https://github.com/aspnet/Hosting/blob/ae9da9290eb825f4145aaaa23603186d51211e53/src/Microsoft.AspNetCore.Hosting/WebHostBuilderExtensions.cs#L50-L71

>
> Startup class is registered as Singleton & DbContext is Scoped service. You cannot resolve a scoped service from a singleton service.

@smitpatel If I'm reading that link correctly, the file you linked does not seem to have changed since 2017, however the code I've put in my original post works under .NET Core 2.1 Preview 1.

The code in `program.cs` will also work under .NET Core 2.0 for injecting `DbContext` into `startup.cs`.

**Comment by ajcvickers** [comment] 2018-05-04 21:31
Triage: agreed that this is a duplicate of the D.I issue linked above.

**Closed** 2022-10-16 12:23 UTC
Labels: closed-external
