### ISSUE TITLE
Feature Request: Ability to downgrade a db contexts database when using an older assembly

### ISSUE THREAD

**Issue by Tarig0** [dotnet/efcore#6046] opened 2016-07-11 17:57 UTC
The scenario:
Say you have an application utilizing code-based migrations with an initial release.

You go to deploy the next version updating the DB and pushing a website. (I currently do this with a single powershell)
All goes well release wise but there is a major bug found and the customer requires a rollback ASAP

Currently one would have to utilize the latest version of the application to downgrade the DB then restart the release process.

It would be great if there was a way to upload the downscripts to the migration table and have the migration engine detect the newer migrations and reverting them

Thanks for your consideration

**Comment by smitpatel** [comment] 2016-07-11 18:29
dupe of #2532

**Closed** 2022-10-16 09:50 UTC
