### ISSUE TITLE
Dotnet ef error "Unrecognized option '--config'"

### ISSUE THREAD

**Issue by AR1ES** [dotnet/efcore#7076] opened 2016-11-20 17:56 UTC
Command `dotnet ef migrations add xxx` not working after updating to the netcore latest version (1.1.0) from netcore 1.0.0.

I run command `dotnet ef migrations add xxx` and after compiling the project I get this error:
```
Specify --help for a list of available options and commands.
Unrecognized option '--config
```

My project json:
```
{
	"version": "1.0.0-*",

	"dependencies": {
		"Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
		"Microsoft.AspNetCore.Authentication.OAuth": "1.1.0",
		"Microsoft.AspNetCore.Diagnostics": "1.1.0",
		"Microsoft.AspNetCore.Mvc": "1.1.0",
		"Microsoft.AspNetCore.Routing": "1.1.0",
		"Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
		"Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
		"Microsoft.AspNetCore.Session": "1.1.0",
		"Microsoft.AspNetCore.StaticFiles": "1.1.0",
		"Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
		"Microsoft.Extensions.Caching.Memory": "1.1.0",
		"Microsoft.Extensions.Configuration.CommandLine": "1.1.0",
		"Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
		"Microsoft.Extensions.Configuration.Json": "1.1.0",
		"Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
		"Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
		"Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.1.0-preview4-final",
		"System.Collections.Immutable": "1.3.0"
	},

	"tools": {
		"Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final"
	},

	"frameworks": {
		"net461": {
		}
	},

	"buildOptions": {
		"emitEntryPoint": true,
		"preserveCompilationContext": true
	},

	"publishOptions": {
		"include": [
			"wwwroot",
			"Views",
			"appsettings.json",
			"appsettings.Staging.json",
			"hosting.json",
			"web.config",
			"Options/*.json"
		]
	},

	"scripts": {
		"postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
	}
}
```

**Comment by smitpatel** [comment] 2016-11-21 06:55
Fixed in aspnet/EntityFramework.Tools@10699fa2231d78e7ed5f3a4b5c10a765ec3633c1

**Comment by KolyaNET** [comment] 2016-11-21 11:58
#7071

**Comment by rowanmiller** [comment] 2016-11-21 19:29
Closing as a dupe of #7071

**Closed** 2022-10-16 10:43 UTC
