### ISSUE TITLE
Need Non-Generic Version Of EF.Property

### ISSUE THREAD

**Issue by JohnGalt1717** [dotnet/efcore#19753] opened 2020-01-30 16:12 UTC
Right now we have EF.Property<T> which allows the use of string names of a property which is great if you know the type of the property. But doesn't work if you don't know the type. 

In scenarios where you're passing a string fieldName you're almost certainly not going to know the type ahead of time, and the only way you could get the type is if you use reflection on the field or use TypeDescriptor.

It would be very nice to have a non-generic version that either took a type as a parameter OR was non-generic and just did the TypeDescriptor work in the background.

Or both.

**Comment by ajcvickers** [comment] 2020-01-30 16:55
@JohnGalt1717 Can you show how it would be used in a query? LINQ is inherently generic.

**Comment by JohnGalt1717** [comment] 2020-01-30 17:04
@ajcvickers  I'm trying to accomplish OrderByProperty<T>(this IQueryable<T> query, string propertyName)

In the past I was able to build this up using Expressions like this:

```
public static IOrderedQueryable<TSource> OrderBy<TSource>(this IQueryable<TSource> source, string propertyName)
{
    // LAMBDA: x => x.[PropertyName]
    var parameter = Expression.Parameter(typeof(TSource), "x");
    Expression property = Expression.Property(parameter, propertyName);
    var lambda = Expression.Lambda(property, parameter);

    // REFLECTION: source.OrderBy(x => x.Property)
    var orderByMethod = typeof(Queryable).GetMethods().First(x => x.Name == "OrderBy" && x.GetParameters().Length == 2);
    var orderByGeneric = orderByMethod.MakeGenericMethod(typeof(TSource), property.Type);
    var result = orderByGeneric.Invoke(null, new object[] { source, lambda });

    return (IOrderedQueryable<TSource>)result;
}


```

But this blows up with EF Core 3.1 (didn't before) so I'm trying to use EF.Property to be able to return the property and make this work.

If there's a way to make the above work in EF Core 3.1 then great, otherwise (and I think STILL), this should be valid:

query.OrderBy(x => EF.Property(x, "PropertyName")) should work (or however I get to that)

Same deal for Where: query.Where(x => EF.Property(x, "PropertyName) == (object) "Some Value") (I'm just being explicit that you have an object value that should be of the same type as EF.Property and should just work, or if the types don't match, throw in that case.

**Comment by ajcvickers** [comment] 2020-01-30 17:09
@JohnGalt1717 If you are using expressions, then generics shouldn't be a problem. Just create the generic type dynamically.

I'll discuss this with the team whether anything else is feasible.

**Comment by JohnGalt1717** [comment] 2020-01-30 17:11
@ajcvickers I am, but as noted the above code doesn't work and causes the dreaded "The query cannot be evaluated on the server, blah blah blah blah".  (I know it was evaluating on the server previously, I could see it in the generated queries.)

**Comment by ajcvickers** [comment] 2020-01-30 17:18
@JohnGalt1717 Please attach a small, runnable project or post a complete code listing that reproduces the issue you are seeing.

**Comment by JohnGalt1717** [comment] 2020-01-30 17:34
@ajcvickers  Just take any EF Core Context against whatever database you want, and use that extension method on a field in a DbSet to Order by that field.
It will blow up.  

Or use the OrderBy with EF.Property per above. It will also blow up.

Not sure why that requires a repro case when litterally any EF Core 3.1 project will fail.

**Comment by ajcvickers** [comment] 2020-02-03 20:52
@JohnGalt1717 I have not been able to reproduce this--see my code below.

```C#
public static class ThreeOne
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Product {Description = "Foo"});
            context.SaveChanges();
        }

        using (var context = new SomeDbContext())
        {
            var propertyName = "Description";
            Console.WriteLine(context.Products.OrderBy(propertyName).ToList().Count);
        }
    }

    public static IOrderedQueryable<TSource> OrderBy<TSource>(this IQueryable<TSource> source, string propertyName)
    {
        // LAMBDA: x => x.[PropertyName]
        var parameter = Expression.Parameter(typeof(TSource), "x");
        Expression property = Expression.Property(parameter, propertyName);
        var lambda = Expression.Lambda(property, parameter);

        // REFLECTION: source.OrderBy(x => x.Property)
        var orderByMethod = typeof(Queryable).GetMethods()
            .First(x => x.Name == "OrderBy" && x.GetParameters().Length == 2);
        var orderByGeneric = orderByMethod.MakeGenericMethod(typeof(TSource), property.Type);
        var result = orderByGeneric.Invoke(null, new object[] {source, lambda});

        return (IOrderedQueryable<TSource>) result;
    }
}

public class SomeDbContext : DbContext
{
     private static readonly ILoggerFactory
         Logger = LoggerFactory.Create(x => x.AddConsole()); //.SetMinimumLevel(LogLevel.Debug));

    public DbSet<Product> Products { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
             .UseLoggerFactory(Logger)
             .EnableSensitiveDataLogging()
             .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
}

public class Product
{
    public int Id { get; set; }
    public string Description { get; set; }
}
```

Output:
```
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.1 initialized 'SomeDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: SensitiveDataLoggingEnabled
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [p].[Id], [p].[Description]
      FROM [Products] AS [p]
      ORDER BY [p].[Description]
1
```

**Comment by smitpatel** [comment] 2020-02-05 17:44
Just use `EF.Property<object>(c, "propertyname");`

**Comment by ajcvickers** [comment] 2020-02-14 17:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:08 UTC
Labels: closed-could-not-reproduce, customer-reported
