### ISSUE TITLE
Suggestion: ScalarField<TPrimitive>

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/efcore#8422] opened 2017-05-09 04:43 UTC
I'm not sure whether this is a dupe of Value Types, I'd like to see a class that somewhat acts like a ComplexType, but should have the following feature set:

 - No ID
 - Stored in DB as a single Primitive field
 - Can be null/not null

I thought of having an interface recognized by EF that when implemented, treats the entity as a complex type (but allows the referring property to be nullable), and only creates one column in the database ignoring the fields in this class. I'm not asking for these fields to be searchable, But sometimes they just need to be stored and take up less columns.  
Most of the options below (except for null/not null) can be  achieved with `ComplexType`s and use of `NotMapped`, but it gets really dirty having to decorate all the properties and trying to avoid devs to mess with the DB property, especially when sharing the models in other platforms that do not necessarily use all these attributes, requiring to wrap all those attributes in `#if NET462` etc. attrs.  
This option allows many fields to be stacked in the DB as a single DB and just stick there without the hassle of taking up many columns. Merely a syntactic sugar, with the addition of allowance of null/not null.

Maybe nullability can be determined in whether the container is a reference type or a value type, but that leads to more complications so I'm gonna leave it alone.
    
    interface IScalarField<TPrimitive> //TPrimitive is what's stored in the DB
    {
      TPrimitive Serialize(); //EF will get the value from here
      void Deserialize(TPrimitive persistent); //EF will invoke this when loading entity
    }

I'm just gonna type in a couple of examples, so consider this really pseudo because I'm not even gonna highlight this on the IDE.

1.

    public Temperature : IScalarField<string>
    {
      public decimal Value { get; set; }
      public bool IsCelsius { get; set; }        
      char separator = '|';
      public string Serialize() => $"{Value}{separator}{IsCelsius ? 'C' : 'F'};
      public void Deserialize(string persistent)
      {
        var split = string.Split('|', StringSplitOptions.RemoveEmptyEntries);
        Value = decimal.Parse(split[0]);
        IsCelsius = bool.Parse(split[1]);        
      }
    }

2.

    public ScalarTimeSpan : IScalarField<long>
    {
      public TimeSpan Value { get; set; }
      public long Serialize() => Value.Ticks;
      public void Deserialize(long persistent) => Value = new TimeSpan(persistent);
    }

3:

    public ScalarStringCollection : Collection<string>, IScalarField<string>
    { 
      //override add/set fields to validate separators
      string Serialize() => string.Join(Environment.NewLine, Items);
      void Deserialize(string persistent)
      {
        var split = string.Split(Environment.NewLine, StringSplitOptions.RemoveEmptyEntries);
        AddRange(split);
      }
    }

Usage:

    public class Entity
    {
      public Temperature Temp { get; set; }
      public ScalarStringCollection AllergiesList { get; set; }
      public ScalarTimeSpan Occurrence { get; set; } 
    }

I once worked on a project that manipulates and stores MIDI data, and also faced a similar issue where you want to store many MIDI flags as a single `byte` or `int`. This pattern could have saved a lot of the dirt.  
I sure want to hear about better options or what I'm missing.

P.S. With EF6, I'm currently using a `ScalarStringCollection` to store unsearchable small arrays, and some other structs that just have to be in one column and not take up 5 columns, utilizing `ComplexType`s with hidden proxy properties.

**Comment by smitpatel** [comment] 2017-05-09 18:23
Possible dupe of #242

**Closed** 2022-10-16 11:04 UTC
