### ISSUE TITLE
Allow Value Population on Inherited Type Tables in TPT

### ISSUE THREAD

**Issue by adamreed90** [dotnet/efcore#30647] opened 2023-04-06 22:28 UTC
When using an Inherited Type, EF will not populate the value on the Derived Objects Table even if it is set. 

Ex: 
```
public class Person {
    public int Age { get; set; }
}

public class Student : Person { 
    public string Name { get; set; }
}
```

An additional fluent configuration for including the inherited property also on the derived table would be very helpful for direct table querying without the need of JOIN's

**Comment by roji** [comment] 2023-04-07 07:27
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-04-19 19:15
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-04-19 19:15 UTC
Labels: type-enhancement, customer-reported
