### ISSUE TITLE
NullReferenceException when generating SQL script for Include() and OrderBy() LINQ query.

### ISSUE THREAD

**Issue by rkaushik15** [dotnet/efcore#22970] opened 2020-10-12 11:16 UTC
### Background
I am migrating an EFCORE application form 3.1 to 5.0 when I encounter this issue.
The following LINQ query throws a NullReferenceException ( please see schema/context info below in the Test Case)

`context.tkdncef100_Blogs.Include(b => b.Posts).OrderBy(o => o.BlogId)`

### Some Analysis
I have been able to narrow down the issue a bit.
In the application, we have some validation for entity names when the model is created. (in `OnModelCreating()`) like this:

`entity.SetTableName(_ValidateName_(entity.GetTableName()));`

I am seeing different behavior when this validation is performed (exception is thrown) vs. when it is not. 
To narrow the problem down further, I removed my validation function, and the issue is still reproducible with the following statement:

`entity.SetTableName(entity.GetTableName());`

Basically, **simply calling the `SetTableName()` function is causing some change in the entity relationships, which is later causing this problem**. 

Also, when this statement is not present, only 2 tables are created in the DB and the test runs successfully. the Posts table has the information of the Name entity (please refer to the test case below). 
However, when the statement is present, 3 tables are created (Blogs, Posts, and Name) and the exception is thrown.

Please look into why this statement is causing the difference in the implementation and why this exception is thrown with this LINQ query when it would make sense that this should not be having any effect since it's **simply getting the entity name and setting it to the same thing**.

### Test Case
```
  internal class Program
  {
    private static void Main()
    {
      var dbContext = new MyContext();

      dbContext.Database.EnsureDeleted();
      dbContext.Database.EnsureCreated();

      foreach (var blog in dbContext.Blogs.Include(b => b.Posts).OrderBy(o => o.BlogId))
      {
        Console.WriteLine($"Blog {blog.Url}");

        foreach (var post in blog.Posts.OrderBy(o => o.PostId))
        {
          Console.WriteLine($"\t{post.Title}: {post.Content} by {post.AuthorName.First} {post.AuthorName.Last}");
        }
      }
    }
  }

  public class MyContext : DbContext
  {
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
      base.OnModelCreating(modelBuilder);

      foreach (var entity in modelBuilder.Model.GetEntityTypes())
      {
        if (entity.BaseType == null)
          entity.SetTableName(entity.GetTableName());

        foreach (var property in entity.GetProperties())
        {
          property.SetColumnName(property.GetColumnName());
        }

        foreach (var key in entity.GetKeys())
        {

          key.SetName(key.GetName());
        }
        foreach (var key in entity.GetForeignKeys())
        {
          key.SetConstraintName(key.GetConstraintName());
        }
        foreach (var index in entity.GetIndexes())
        {
          index.SetName(index.GetName());
        }
      }

      modelBuilder.Entity<Blog>(entity =>
      {
        entity.Property(e => e.Url).IsRequired();
        entity.Property(e => e.BlogId).ValueGeneratedNever();
      });

      modelBuilder.Entity<Post>(entity =>
      {
        entity.Property(p => p.PostId).ValueGeneratedNever();
      });

      #region BlogSeed
      modelBuilder.Entity<Blog>().HasData(new Blog { BlogId = 1, Url = "http://sample.com" });
      #endregion

      modelBuilder.Entity<Post>(entity =>
      {
        entity.HasOne(d => d.Blog)
            .WithMany(p => p.Posts)
            .HasForeignKey("BlogId");
      });

      #region PostSeed
      modelBuilder.Entity<Post>().HasData(
          new Post() { BlogId = 1, PostId = 1, Title = "First post", Content = "Test 1" });
      #endregion

      #region AnonymousPostSeed
      modelBuilder.Entity<Post>().HasData(
          new { BlogId = 1, PostId = 2, Title = "Second post", Content = "Test 2" });
      #endregion

      #region OwnedTypeSeed
      modelBuilder.Entity<Post>().OwnsOne(p => p.AuthorName).HasData(
          new { PostId = 1, First = "Andriy", Last = "Svyryd" },
          new { PostId = 2, First = "Diego", Last = "Vega" });
      #endregion
    }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
    {
      options.UseSqlServer("server=.;database=TestDb;Integrated Security=True;");
    }
  }

  public class Blog
  {
    public int BlogId { get; set; }
    public string Url { get; set; }

    public virtual ICollection<Post> Posts { get; set; }
  }
  public class Post
  {
    public int PostId { get; set; }
    public string Content { get; set; }
    public string Title { get; set; }
    public int BlogId { get; set; }
    public Blog Blog { get; set; }
    public Name AuthorName { get; set; }
  }

  public class Name
  {
    public virtual string First { get; set; }
    public virtual string Last { get; set; }
  }
```

### Stack Trace

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.GetPropertyExpressionsFromJoinedTable(IEntityType entityType, ITableBase table, TableExpressionBase tableExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.TryExpand(Expression source, MemberIdentity member)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.Expand(SelectExpression selectExpression, Expression lambdaBody)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.ExpandWeakEntities(SelectExpression selectExpression, Expression lambdaBody)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.TranslateSubquery(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at SQLServerEFCoreTest.Program.Main()
```

### Provider and Version Information

EF Core version: 5.0.0-rc.1.20451.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer 5.0.0-rc.1.20451.13
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: VS 2019 (16.7.5)

**Comment by smitpatel** [comment] 2020-10-12 16:00
Possible duplicate of #22340

**Comment by smitpatel** [comment] 2020-10-12 16:16
Provided repro works in nightly builds. Version used - 5.0.0-rtm.20509.3

You can test your app by running it against daily builds - https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md

**Closed** 2022-10-16 19:04 UTC
Labels: closed-duplicate, customer-reported
