### ISSUE TITLE
How to add EntityFramework.Commands to my DLL project?

### ISSUE THREAD

**Issue by ryancole** [dotnet/efcore#3967] opened 2015-12-03 19:28 UTC
Hi all, this is not an issue, I'm just confused and looking for a helpful explanation of how to work within the new dnx environment. I've got a solution with two projects in it - an ASP.NET project and a DLL project. I'm trying to use EF7 migrations, and so I'm trying to add `EntityFramework.Commands` to my DLL project. I keep getting the following error ...

```
Severity    Code    Description Project File    Line    Suppression State
Error   NU1002  The dependency EntityFramework.Commands 7.0.0-rc1-final in project League.Data does not support framework .NETPlatform,Version=v5.4.    League.Data C:\Users\Ryan\Projects\League\League.Data\project.json  27  
```

Here is the `project.json` file for my DLL project ...

``` json
{
  "version": "1.0.0-*",
  "description": "League.Data Class Library",
  "authors": [ "Ryan" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "commands": {
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "net451": { },
    "dotnet5.4": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
      }
    }
  },

  "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "League.Entity": "1.0.0-*"
  }
}
```

Any advice on what I need to do to make these dependencies work? I'm a little confused. Thanks!

**Comment by rowanmiller** [comment] 2015-12-08 19:43
Try changing dotnet5.4 to netcore50 in your frameworks node in project.json. If that works, this is a known issue that is being looked into.

**Comment by CraigSelbert** [comment] 2015-12-08 21:45
That worked for me.

Here is what I ended up with 

```
{
  "version": "1.0.0-*",
  "description": "Domain Class Library",
  "authors": [ "Craig Selbert" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "frameworks": {
    "dnx451": { },
    "netcore50 ": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
      }
    }
  },
  "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final"
  }
}
```

**Comment by bricelam** [comment] 2015-12-09 20:15
Dupe of #3879

**Closed** 2022-10-16 09:19 UTC
