### ISSUE TITLE
SqlException when fetching parent context DbSet from inherited context

### ISSUE THREAD

**Issue by BlairMcc** [dotnet/efcore#15639] opened 2019-05-07 00:13 UTC
When using an inherited context I am seeing a SqlConnection error on attempting to retrieve records from a DBSet on the parent context

Schema
```
ParentContext
   CoreTable

ChildContext
   CustomerTable
```

Error and stack trace
```
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'CoreTable'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MyDBAccess.GetValuations(Int64 batchId, Int64 fileLoadId) in C:\dev\MyDBAccess.cs:line 55
```

### Steps to reproduce

Parent and child db context constructors use the pattern described here (https://github.com/aspnet/EntityFrameworkCore/issues/7533#issuecomment-353669263 and https://github.com/aspnet/EntityFramework.Docs/issues/594)

Fetching data from the CoreTable works when using ParentContext, but throws this error using the ChildContext

```c#
            using (var parentContext = new ParentContext())
            {
                // Working
                coreStrings = parentContext.CoreTable
                    .AsNoTracking()
                    .Where(p => p.BatchId == batchId && p.FileLoadId == fileLoadId && !p.Ignore)
                    .Select(p => p.Name)
                    .ToList();              
            }

            using (var childContext = new ChildContext())
            {
                // Not working
                List<string> coreStrings = childContext.CoreTable
                    .AsNoTracking()
                    .Where(p => p.BatchId == batchId && p.FileLoadId == fileLoadId)
                    .Select(p => p.Name)
                    .ToList();
            }           
        }
```

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: VS2019 16.0.2

**Comment by ajcvickers** [comment] 2019-05-10 18:26
@ArchSerpo Can you please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-05-17 16:32
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:20 UTC
Labels: closed-could-not-reproduce, customer-reported
