### ISSUE TITLE
When using SignalR & EF entities are always detached

### ISSUE THREAD

**Issue by AllanMichaelsen** [dotnet/efcore#19411] opened 2019-12-25 14:07 UTC
I'm unsure if this belongs here or in EF, but I'll start here.

When I retrieve the entity the state is unchanged, but after round tripping to my application via SignalR my entity is always detached and that results in an the following scenatios:

- If I try to attach the entity it fails saying it's already tracked
- If I try to update the entity it fails with the same error

If I save changes nothing is persisted because the entity is detached and not tracked :-(

Any Ideas?

When I get my entity with this it's unchanged (the entity has tracking)
```C# 
   public async Task<DtoContact> GetById(long contactId)
    {
      var contact = await GetFirstOrDefault<long, DtoContact>(x => x.ContactId == contactId, includeFlag: FlagContactInclude.CultureInfo | FlagContactInclude.ModifiedByUnit | FlagContactInclude.ModifiedByUser, includeActive: true, includeArchived: true);
      var state = context.Entry(contact)
       .State;
      return contact;
    }
```

When I return to this method to save the state is detached
```C#
    public async Task<DtoContact> Upsert(DtoContact contact)
    {
      if (contact == null)
      {
        throw new ArgumentNullException(nameof(contact));
      }

      if (contact.ModifiedByUnit is null)
      {
        throw new ArgumentNullException(nameof(contact.ModifiedByUnit));
      }

      if (contact.ModifiedByUser is null)
      {
        throw new ArgumentNullException(nameof(contact.ModifiedByUser));
      }

      try
      {
        var state = context.Entry(contact)
         .State;
        if (state == EntityState.Added)
        {
          await context.Contact.AddAsync(contact);
        }
        else if (state == EntityState.Detached)
        {
          context.Contact.Attach(contact);
        }
        else if (state == EntityState.Modified)
        {
          context.Contact.Update(contact);
        }

        context.SaveChanges();

        return contact;
      }
      catch (Exception ex)
      {
        log.Error("Error upserting contact", ex);
        throw;
      }
    }
```

I'm out of ideas...

**Comment by roji** [comment] 2019-12-27 11:40
@AllanMichaelsen can you please submit a runnable code sample that demonstrates the exact issues you're still having? You've described various problematic scenarios above and I'd like to make sure we understand your exact problem.

**Comment by AllanMichaelsen** [comment] 2019-12-28 12:58
> @AllanMichaelsen can you please submit a runnable code sample that demonstrates the exact issues you're still having? You've described various problematic scenarios above and I'd like to make sure we understand your exact problem.

That's a difficult task as the setup of services and client is quite big. I will try to find time to do so, but it's quite a task.

The only issue I have with this though is this:

- I want to add a new item to the context (database) 
  - This entity contains other entities that are already in the context ie. referenced properties
- When adding this entity I get the error with the referenced entities already being tracked

I'm currently using the workaround as shown above where I create a new item in the service end and sets the values on that entity then adding it. This works, but seems like a hack.

**Comment by roji** [comment] 2019-12-29 11:17
@AllanMichaelsen it's still not exactly clear what you're asking. The below code sample shows us adding some entity in one context, loading it in another and referencing it from a new entity that gets added. I'm guessing you're trying to do something slightly different, try taking the below and modifying it to show what it is that isn't working for you.

```c#
class Program
{
    static void Main(string[] args)
    {
        using (var ctx = new BlogContext())
        {
            ctx.Database.EnsureDeleted();
            ctx.Database.EnsureCreated();

            ctx.Bs.Add(new B
            {
                Name = "B1",
                A = new A { Title = "Some A" }
            });
            ctx.SaveChanges();
        }

        using (var ctx = new BlogContext())
        {
            var a = ctx.As.Single(p => p.Title == "Some A");
            Console.WriteLine(ctx.Entry(a).State);
            // State is Unchanged, a is now tracked.
            ctx.Bs.Add(new B
            {
                Name = "B2",
                A = a
            });
            Console.WriteLine(ctx.Entry(a).State);  // Still Unchanged
            ctx.SaveChanges();
        }
    }
}

public class BlogContext : DbContext
{
    public DbSet<B> Bs { get; set; }
    public DbSet<A> As { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(@"...");
}

public class A
{
    public int Id { get; set; }
    public string Title { get; set; }
}

public class B
{
    public int Id { get; set; }
    public string Name { get; set; }
    public A A { get; set; }
}
```

**Comment by AllanMichaelsen** [comment] 2019-12-29 11:34
That is clear. But when put into my scenario it looks like this:

- The B2 entity is created on the client side of a SignalR service
- B2 contains an detached version of A retrieved over the SignalR service from the server
- B2 is now sent to the server to be added to the database as a new entity but with the detached A

Doing this:

`        b == entity coming from client side

        using (var ctx = new BlogContext())
        {
            ctx.Contact.Add(b)
            ctx.SaveChanges();
        }`

will throw the described error, but doing this:

`        b == entity coming from client side

        using (var ctx = new BlogContext())
        {
          b1 = new B();
          ctx.Entry(b1).CurrentValues.SetValues(b);
          ctx.Contact.Add(b1);
          ctx.SaveChanges();
        }`

It seems wrong that I have to create a new B just to have the detached A "accepted" as not being a new untracked item. I should be able to add the B entity coming from the client side directly even though having a detached A property reference.

**Comment by roji** [comment] 2019-12-29 11:54
Is there any reason you can't simply attach your entity instance that's coming from the client side? See this code:

```c#
class Program
{
    static void Main(string[] args)
    {
        A someA;

        // Imagine this is your first SignalR context, where the service returns an instance of A to the client
        using (var ctx = new BlogContext())
        {
            ctx.Database.EnsureDeleted();
            ctx.Database.EnsureCreated();

            someA = new A { Title = "Some A" };
            ctx.Bs.Add(new B
            {
                Name = "B1",
                A = someA
            });
            ctx.SaveChanges();
        }

        // This is now your second instance, where the instance previously retrieved is now attached
        using (var ctx = new BlogContext())
        {
            Console.WriteLine(ctx.Entry(someA).State); // Detached, untracked
            ctx.As.Attach(someA);
            Console.WriteLine(ctx.Entry(someA).State); // Unchanged, tracked
            ctx.Bs.Add(new B
            {
                Name = "B2",
                A = someA
            });
            Console.WriteLine(ctx.Entry(someA).State);  // Still Unchanged
            ctx.SaveChanges();
        }
    }
}

public class BlogContext : DbContext
{
    public DbSet<B> Bs { get; set; }
    public DbSet<A> As { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(@"...");
}

public class A
{
    public int Id { get; set; }
    public string Title { get; set; }
}

public class B
{
    public int Id { get; set; }
    public string Name { get; set; }
    public A A { get; set; }
}
```

It would really be much easier if you could post a simple code sample, just like I'm doing (a code sample is worth a thousand words)

**Comment by ajcvickers** [comment] 2020-01-06 17:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:03 UTC
Labels: closed-could-not-reproduce, customer-reported
