### ISSUE TITLE
Short cut for Script-Migration the last migration

### ISSUE THREAD

**Issue by cuiliang** [dotnet/efcore#32744] opened 2024-01-08 08:27 UTC
A very common scenario is to create a Migration for the latest database changes, and then generate a Script for this Migration. Currently, generating a Script can be quite troublesome as it requires finding the name of the last Migration. 

Create a command such as `Script-Migration -last` to script the last migration.

**Comment by ajcvickers** [comment] 2024-01-09 16:27
Duplicate of #26155

**Closed by ajcvickers** 2024-01-09 16:27 UTC
Labels: type-enhancement, customer-reported
