### ISSUE TITLE
Scaffold-DbContext with a nvarchar(4000) causes error

### ISSUE THREAD

**Issue by chaimzf** [dotnet/efcore#9631] opened 2017-08-30 21:34 UTC
When using the Scaffold-DbContext command to Reverse engineer your model, if there is a nvarchar(4000) field - which is equivalent to nvarchar(max) - the OnModelCreating will specify the field as **HasColumnType("nvarchar")** instead of the correct **HasMaxLength(4000)**

This will cause the following error when calling the dbcontext:

```
Exception message:
System.ArgumentException: Data type 'nvarchar' is not supported in this form. Either specify the length explicitly in the type name, for example as 'nvarchar(16)', or remove the data type and use APIs such as HasMaxLength to allow EF choose the data type.``

**Comment by ajcvickers** [comment] 2017-08-31 00:00
Duplicate of #9188

**Comment by ajcvickers** [comment] 2017-09-12 18:59
Hi @chaimzf. We are gathering information on the use of EF Core pre-release builds. You reported this issue shortly after the release of 2.0.0 RTM. It would be really helpful if you could let us know:

- Did you consider testing your code against the pre-release builds?
- Was there anything blocking you from using pre-release builds?
- What do you think could make it easier for you to use pre-release builds in the future?

Thanks in advance for any feedback. Hopefully this will help us to increase the value of pre-release builds going forward.

**Closed** 2022-10-16 11:19 UTC
Labels: closed-duplicate
