### ISSUE TITLE
Expression tree pre-processor

### ISSUE THREAD

**Issue by ice1e0** [dotnet/efcore#15275] opened 2019-04-07 22:23 UTC
I am working a lot with interfaces and generic types with EF Core.

I found out when I use a `where` linq query with the lambda expression format 
``` csharp
// NOTE: e is an TEntry generic type.
query = query.Where(e => ((IMyInterface)e).MyProperty == "100");
```
EF core is not able to parse this correctly and the result ends up in that many executions are done to the SQL query (... result => bad performance, a lot of db traffic etc.).

In my source code I checked upfront that TEntry inherits the `IMyInterface` interface, but I am not able to do a `where TEntry : IMyInterface` clause which would then make the cast not required.

I developed my own expression optimizer which is able to solve this issue particular:

``` csharp
/// <summary>
/// The Linq-to-SQL implementation in EF Core has some limitations
/// and with this ExpressionVisitor we optimize the Expression tree
/// so that it can be executed in SQL.
/// </summary>
public class DbExpressionOptimizerVisitor : ExpressionVisitor
{
    public static DbExpressionOptimizerVisitor Singletone => new DbExpressionOptimizerVisitor();

    private DbExpressionOptimizerVisitor()
    {
    }

    protected override Expression VisitUnary(UnaryExpression node)
    {
        if (node.NodeType == ExpressionType.TypeAs &&
            node.Type.IsInterface &&
            node.Operand.Type.GetInterfaces().Contains(node.Type))
        {
            // input: (MyType value) => (IMyInterface)value;
            // 
            // if the condition is given that IMyInterface is implemented by MyType
            // the casting is removed.
            //
            // output: (MyType value) => value;

            // this cast is not anymore required and can be removed
            return node.Operand;
        }

        return base.VisitUnary(node);
    }
}
```

It can be called similar to this:

``` csharp
var query = MyDbContext.MyEntry.AsQueryable();

// ..
// do here some additional stuff with generics, for example:
// query = query.Where(x => ((IMyInterface)x).MyProperty == "100");
// ...

// run the optimizer
query = query.Provider.CreateQuery<TEntry>(DbExpressionOptimizerVisitor.Singletone.Visit(query.Expression));

// execute the query on the SQL server:
var result = query.ToList();
```

OK, enough talk, to the point:

### Point 1: Register an expression tree pre-processor in EF core
I don't think this is the last time I will run into an issue where Linq-To-Sql does not perform as I want and with an adjustment of the expression tree I will be able to fix it.
Is there any way to set a `ExpressionVisitor` class as an pre-processor for the Linq-To-SQL engine in EF core, so that I can pass the `ExpressionVisitor` once to EF core and EF core will execute it automatically before the expression tree is converted to SQL?

This could probably be implemented into the `OnConfiguring(..)` method:
``` csharp
public sealed class MyDbContext : DbContext
{
    // ...
    
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseExpressionTreeOptimizer(DbExpressionOptimizerVisitor.Singletone);
    }
}
```

### Point 2: Fix the issue
Is it possible that this issue named above is solved in EF core so I don't need to use my own `ExpressionVisitor`?

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows
IDE: Visual Studio 2017 15.8.6

**Comment by ajcvickers** [comment] 2019-04-08 17:23
Duplicate of #14528

**Closed** 2022-10-16 14:17 UTC
Labels: customer-reported
