### ISSUE TITLE
Tracking of nested owned property changes

### ISSUE THREAD

**Issue by vflame** [dotnet/efcore#18528] opened 2019-10-23 02:25 UTC
Nested owned entitiy changes are not persisted unless context.Update() is called to set the properties to modified state.

``` C#
//Models:
public class PreferenceA
{
	public bool IsEnabled {get;set;}
}

public class PreferenceB
{
	public bool List<string> Preferences {get;set;}
}

public class UserPersonalization
{
	public PreferenceA PreferenceA{ get; set;}
	public PreferenceB PreferenceB{ get; set;}
	public bool IsPersonalized => PreferenceA.Enabled || PreferenceB.Preferences.Any();
}

public class User
{
	public UserPersonalization UserPersonalization {get;set;}
}


//Context Configuration:
builder.OwnsOne(p=>p.UserPersonalization,
personalization => 
{
	personalization.OwnsOne(p=>p.PreferenceA);
	personalization.OwnsOne(p=>p.PreferenceB, preferenceB => 
	{
		preferenceB.Property(x => x.Preferences).HasConversion(x=>x.SerializeToJson(), x=> x.DeserializeFromJson<List<string>>());
	}
});

// program:

//changes not persisted to database
var user = context.Users.FirstOrDefault();
user.UserPersonalization.PreferenceB.Preferences.Add("new value");
context.SaveChanges():

//changes are persisted to database
var user = context.Users.FirstOrDefault();
user.UserPersonalization.PreferenceB.Preferences.Add("new value");
context.Update(user.UserPersonalization.PreferenceB);
context.SaveChanges():



### Further technical details

EF Core version: 2.2.6
Database provider: NpgSql
Target framework: .NET core 2.2
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by smitpatel** [comment] 2019-10-23 02:28
@vflame - Can you also mention which version of EF Core you are using?

**Comment by vflame** [comment] 2019-10-23 03:07
EF Core version: 2.2.6 + Target framework: .NET core 2.2

**Comment by vflame** [comment] 2019-10-23 05:05
FWIW, adding the `[ConcurrencyCheck]` attribute to the OwnedProperty with a `HasConversion<string>()` results in a `DbConcurrencyException` where it's checking for the "new value" in the Where clause for the concurrencycheck. Works fine with primitives.

**Comment by AndriySvyryd** [comment] 2019-10-23 16:35
@vflame Could you try using EF Core 3.0.0? These issues should have been fixed.

**Comment by ajcvickers** [comment] 2019-11-01 15:11
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:51 UTC
Labels: closed-could-not-reproduce, customer-reported
