### ISSUE TITLE
If error occurred while saving changes, StateChanged event will not be triggered.

### ISSUE THREAD

**Issue by Abdulrhman5** [dotnet/efcore#26989] opened 2021-12-13 15:13 UTC
If an error occurred during `context.SaveChanges()` the `ChangeTracker.StateChanged` will not get triggered even though in the following case a tracked entity state changed from `Modified` to `Detached`.

```C#
using Microsoft.EntityFrameworkCore;
using System;

var options = new DbContextOptionsBuilder<DummyContext>().UseInMemoryDatabase("DummiesDatabase").Options;
var context = new DummyContext(options);
var entity = new DummyEntity() // entity that does not exist in the db.
{
    Id = int.MaxValue,  
    Name = "Entity1"
};
context.Update(entity);
var state1 = context.Entry(entity).State;  // Modified
try
{
    context.SaveChanges(); // expected to throw DbUpdateConcurrencyException
}
catch { }
var state2 = context.Entry(entity).State; // Deatached


public class DummyContext : DbContext
{
    public DbSet<DummyEntity> Entities { get; set; }

    public DummyContext(DbContextOptions options) : base(options)
    {
        ChangeTracker.StateChanged += ChangeTracker_StateChanged;
    }

    private void ChangeTracker_StateChanged(object? sender, Microsoft.EntityFrameworkCore.ChangeTracking.EntityStateChangedEventArgs e)
    {
        // This never gets triggered
    }
}

public class DummyEntity
{
    public int Id { get; set; }

    public string Name { get; set; }
}
```

### Include provider and version information

EF Core version: 5.0.12
Database provider: (e.g. Microsoft.EntityFrameworkCore.InMemory) 
Target framework: (e.g. .NET 5.0) 
Operating system: Windows 10
IDE: (e.g. Visual Studio 17.0.0 Preview 4.1)

**Comment by ajcvickers** [comment] 2021-12-13 16:43
@Abdulrhman5 I am not able to reproduce this. Note that the state should not change to `Detached` if the save fails; it should stay `Modified`. This is what I am seeing.

**Comment by ajcvickers** [comment] 2022-01-11 12:19
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:19 UTC
Labels: closed-could-not-reproduce, customer-reported
