### ISSUE TITLE
EF Core creating a .config folder

### ISSUE THREAD

**Issue by dpwzone** [dotnet/efcore#32836] opened 2024-01-15 22:39 UTC
Recently, started seeing a new folder called .config containing a file called dotnet-tools.json.

From what I've seen, this is resulting from ef core using dotnet tools for migrations, etc.  

Thing is, I'm not using migrations, etc., so it would be nice to have a way of turning off this superfluous folder creation, as it litters up the projects, and we have to take extra steps to make sure it doesn't go into our source control.

As a programmer of many decades, I know it's a huge **no-no** to just have stuff being put into people's projects without their consent.  Would be nice if other programmers respected people's work.

**Comment by ajcvickers** [comment] 2024-01-17 10:14
@dpwzone EF Core does not create this folder; it is created when a dotnet tool is installed locally in the project. EF never does this for you, so, assuming you didn't install it, then it must be installed by something else--maybe Visual Studio?

**Comment by ajcvickers** [comment] 2024-01-31 13:11
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-01-31 13:11 UTC
Labels: customer-reported
