### ISSUE TITLE
This is missing how to Opt-In

### ISSUE THREAD

**Issue by StingyJack** [dotnet/efcore#17572] opened 2019-06-09 23:30 UTC
Most of the time I want to "loan" an exist object to EF, but that requires that I alter every property not part of the EF table - now and forever - to have [NotMapped]. Thats a pain. So is using mapping classes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76c24b57-557f-a6d6-16f1-1da50e4744cd
* Version Independent ID: 8bee29c6-58e4-1d07-025e-0bdcead9b5a1
* Content: [Including & Excluding Properties - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/included-properties)
* Content Source: [entity-framework/core/modeling/included-properties.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/included-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-02 17:48
Duplicate of #16009

**Closed** 2022-10-16 14:39 UTC
