### ISSUE TITLE
Problems with .Includes & .AsSplitQuery - timeouts and missing navigation properties

### ISSUE THREAD

**Issue by J0nKn1ght** [dotnet/efcore#25466] opened 2021-08-09 18:41 UTC
EF Core version:  5.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0.8
Operating system: Windows 10 (20H2 - 19042.1110)
IDE: Visual Studio 2019 16.10.4

I've raised this as a question, and not a bug with EF Core, as I'm not entirely sure where the problem is occurring, but here's our scenario.  (I've not currently got time to try and create a new project to illustrate the problem.)

We have an MVC application that we're in the process of upgrading from .Net Core v2.2 -> 3.1 -> .Net 5.  This makes use of the X.PagedList library ([https://github.com/dncuug/X.PagedList](https://github.com/dncuug/X.PagedList)) to page the results of our queries.

There are 2 variables that affect the success of a specific paged query result (or lack of it).

1. The query is on an entity that has a number of navigation properties.  These have nullable Guids as the foreign key values.  For one of the related entities (let's just call it 'ComplexEntity' to avoid confusion), if the key property is populated, the query runs without problems,  However, if the key value is null, then there are problems with the query (described below).
2. The X,PagedList library has an ToPagedListAsync method which takes an IQueryable.  The library only has a dependency on .Net Standard, and so doesn't use Microsoft.EntityFrameworkCore.  It therefore converts the IQueryable to an IEnumerable, and uses the System.Linq ToList extension method as follows:

```csharp
return await Task.Run(superset.ToList, cancellationToken);
```
where 'superset' is the IEnumerable parameter.

If the statement that creates our IQueryable has the .Include for our 'ComplexEntity' entity as the last one, the ToPagedListAsync call from X.PagedList succeeds.  However, if we move it before the include for another navigation property on the object, then it generates a timeout exception running the query.  Running the SQL query generated by EF in the VS output window confirms that the query itself does not timeout - it is the code to convert it to an object collection that is failing.

If we add the .AsSplitQuery directive to the IQueryable (which seems to be the standard 'fix' for queries that have started to cause timeout exceptions in EF Core 5), the query runs successfully, but any navigation property for .Includes that appear after our 'ComplexEntity' entity will be null, even though the SQL query is returning the data for the navigation property objects correctly.

If we change the X.PagedList code so that it references Microsoft.EntityFrameworkCore, and change the call to use the IQueryable ToListAsync extension method, then the call works, whether or not the .AsSplitQuery directive is used, and whatever order the .Includes occur.

As changing the order of the .Includes affects whether the System.Linq IEnumerable ToList works or not, I don't think that this is an intrinsic issue with the X,PagedList library.

Whilst trying to debug the issue locally (with a local copy of EFCore), it seemed like it was the underlying System.Data.Common.DbDataReader that was the source of the issue, but I wasn't able to include the source for that to get any further.

The 'ComplexEntity' entity that is causing the issue has a (non-nullable) rowversion byte array property, and it also has a nullable self-join navigation property on it.  Could there be something in the data reader that causes the mapping of the returned SQL data into the object properties to fail for the instances where our 'ComplexEntity' data is null, and so it doesn't map any of the columns that follow in the SQL output into their entity instances?  Will the data reader be iterating through the SQL columns for this processing?

(I have seen a comment on #24953 indicating that there is a bug in 'nav expansion', but it doesn't include any further information.  Could this be related to that bug?)

**Comment by smitpatel** [comment] 2021-08-09 23:55
@J0nKn1ght - Without any code it is hard to say anything about queries. It may be a bug you linked or it may be a different bug or it may be something else outside of EF Core. On bare essence using Task.Run with a sync method to run it async way could also be causing a deadlock somewhere. If you can share a runnable repro code we can look into it.

**Comment by ajcvickers** [comment] 2021-08-20 10:56
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:42 UTC
Labels: closed-could-not-reproduce, customer-reported
