### ISSUE TITLE
using postgresql snake_case naming convention leads to owned types getting stored in separate tables

### ISSUE THREAD

**Issue by githubfanster** [dotnet/efcore#12587] opened 2018-07-06 14:19 UTC
Describe what is not working as expected.
----------------------------------------------------------------------------------------------------------------
using postgresql snake_case naming convention leads to owned types getting stored in separate tables

i've read that, by convention, owned types are stored in the same table as their owners.

in my first foray into using owned types, i ran into a situation where this did not happen.

after some investigation, i found out that using postgresql snake_case naming convention leads to an owned type getting stored in a table separate from its owner.

the code i'm using for converting names is similar to the code published by Andrew Lock in:

https://andrewlock.net/customising-asp-net-core-identity-ef-core-naming-conventions-for-postgresql/

protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        foreach(var entity in builder.Model.GetEntityTypes())
        {
            // Replace table names
            entity.Relational().TableName = entity.Relational().TableName.ToSnakeCase();

            // Replace column names            
            foreach(var property in entity.GetProperties())
            {
                property.Relational().ColumnName = property.Name.ToSnakeCase();
            }
			...
		}
	}
	
The code i ran to verify the cause of the problem was:

https://www.ajeetyelandur.com/2018/05/EF-Core-Owned-Types-explained/

Instead of the expected result where the value object or owned entity Address gets stored in the same table as the Student table owner, when i use Postgresql snake_case naming conventions, two physical tables are created (one for students, the other, address).

When i don't use Postgresql snake_case naming convention, i get the expected result.

I know that one option i have is whenever i need to use raw sql to do stuff, i just need to remember to put things such as column names in double quotes.

But i was just wondering if there are any other options (that is, if possible, i would like to use the postgresql snake_case naming convention [since the frequency with which our team needs to use raw sql is not negligible], AND have owned types stored with its owner table) ?
------------------------------------------------------------------------------------------------

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

[OwnedTypesDemo.zip](https://github.com/aspnet/EntityFrameworkCore/files/2170799/OwnedTypesDemo.zip)

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)"Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.1.1" 
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)"Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.1.1" 
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.4) Visual Studio 2017 15.7.4

**Comment by ajcvickers** [comment] 2018-07-06 16:30
Duplicate of #12342

**Comment by githubfanster** [comment] 2018-07-07 02:19
i followed the links
https://github.com/aspnet/EntityFrameworkCore/issues/12342, and then
https://github.com/aspnet/EntityFrameworkCore/issues/12334
and inferred that maybe if i changed my code (in the zip file i've already submitted) to:

protected override void OnModelCreating(ModelBuilder builder)
        {
            //builder.UsePostgresConventions();  //make this the last statement?
            builder.ForNpgsqlUseIdentityAlwaysColumns();
            builder.Entity<Student>()
                .OwnsOne(s => s.Home);
            builder.UsePostgresConventions();
        }

but i got the exception below instead. i don't know why.

if i comment out 
  builder.UsePostgresConventions();
entirely, the single table is generated 
 CREATE TABLE "Students" (
          "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
          "Name" text NULL,
          "Home_Street" text NULL,
          "Home_City" text NULL,
          CONSTRAINT "PK_Students" PRIMARY KEY ("Id")
      );

**** A little more guidance or explanation here would be GREATLY APPRECIATED ****

*** THE EXCEPTION I GOT ***
Unhandled Exception: System.InvalidOperationException: The keys {'Id'} on 'Student' and {'StudentId'} on 'Address' are both mapped to 'students.pk_students' but with different columns ({'id'} and {'student_id'}).
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedKeysCompatibility(IReadOnlyList`1 mappedTypes, String tableName)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at ConsoleApp1.Program.Main(String[] args) in F:\vs2017play\OwnedTypesDemo\ConsoleApp1\Program.cs:line 12
Press any key to continue . . .

**Comment by githubfanster** [comment] 2018-07-07 02:45
OK. I read https://github.com/aspnet/EntityFrameworkCore/issues/12334  again, and this seemed to worked:

in my ModelBuilderExtensions class, i just need to add the if(!entity.IsOwned()) check:

public static void UsePostgresConventions(this ModelBuilder modelBuilder)
        {
 
                foreach (var entity in modelBuilder.Model.GetEntityTypes())
                {
                    if (!entity.IsOwned())
                    {
                        // Replace table names
                        entity.Relational().TableName = entity.Relational().TableName.ToSnakeCase();
                          ....
                     }
                  }
              }

In the StudentContext class :
        protected override void OnModelCreating(ModelBuilder builder)
        {
            //builder.UsePostgresConventions();  //make this the last statement?
            builder.ForNpgsqlUseIdentityAlwaysColumns();
            builder.Entity<Student>()
                .OwnsOne(s => s.Home,
                  hm =>
                  {
                      hm.Property(h => h.Street).HasColumnName("home_street");
                      hm.Property(h => h.City).HasColumnName("home_city");
                  }
            );
            builder.UsePostgresConventions();
        }

THANKS!!!

**Closed** 2022-10-16 13:18 UTC

**Comment by ZzZombo** [comment] 2024-11-14 03:33
Sorry, is this still not addressed? Just stumbled upon this road blocker. What can I do in order to fix this issue on my end?

**Comment by roji** [comment] 2024-11-14 07:06
@ZzZombo are you referring to a problem when using the [EFCore.NamingConventions](https://github.com/efcore/EFCore.NamingConventions) plugin, with its latest version? If so, can you please open a new issue on that repository, and include a minimal, runnable code sample that would allow me to reproduce the error?

**Comment by ZzZombo** [comment] 2024-11-14 10:08
I was, but it turned out my project was screwed up due to the model snapshot file missing somehow, so all subsequent migrations were erroneous.
