### ISSUE TITLE
Primary key datatype change does not consider dropping primary key constraint in generated script

### ISSUE THREAD

**Issue by jp1482** [dotnet/efcore#32864] opened 2024-01-19 11:49 UTC
# Issue
- I have one dbcontext and it has one entity. When this entity is being created it has int Id as primary key. I have generated migration and also generated script (sql script) from this. Upto this point it works fine. Now this is being deployed so migration is applied.  
- After some days It is required to change datatype of primary key (int Id) to long Id. Generated second migration. Now generated sql script. When I apply this It did not work as expected and it gives error as script is not droppoing primary key.

# Example code.
1. Initial Code (int Id as Primary Key)
```
    public class SimpleDbContext : DbContext
    {
        public SimpleDbContext(DbContextOptions<SimpleDbContext> option)
            : base(option)
        {
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Person>(entity =>
            {
                entity.ToTable("Persons");
                entity.HasKey(x => x.Id);                
                entity.Property(x => x.FirstName).HasMaxLength(100).IsRequired();
                entity.Property(x => x.LastName).HasMaxLength(100).IsRequired();                
                entity.HasIndex(x => x.FirstName);
                entity.HasIndex(x => x.LastName);
            });

            base.OnModelCreating(modelBuilder);
        }
    }

    public class SimpleDbContextDesignFactory : Microsoft.EntityFrameworkCore.Design.IDesignTimeDbContextFactory<SimpleDbContext>
    {
        public SimpleDbContext CreateDbContext(string[] args)
        {
            var optionBuilder = new DbContextOptionsBuilder<SimpleDbContext>().UseSqlServer("");
            return new SimpleDbContext(optionBuilder.Options);
        }
    }
    public class Person
    {
        public int Id { get; set; } 
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime LastModifiedOn { get; set; }
    }
```
2. Create Initial Migration.
```
dotnet ef migrations add InitialMigration -c SimpleDbContext
```
3. Generate Sql Script  (This generated script execute against the Db in my case) (Added script in attachment as well)
```
dotnet ef migrations script -c SimpleDbContext --output C:\temp\script1.sql.txt
```
4. Upto this point it works. 
5. Now Change in Data type and now Person entity will look like this.
```
public class Person
{
    public long Id { get; set; }        
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public DateTime LastModifiedOn { get; set; }
}
```
6.  Generate second migration.
```
dotnet ef migrations add SecondMigration -c SimpleDbContext
```
7. Generate sql script between two migrations. ( added script in attachment)
```
dotnet ef migrations script InitialMigration SecondMigration -c SimpleDbContext --output C:\temp\script2.sql.txt
```
**8. Now issue at this point. If I apply this second script it will try to drop default constraint but not primary key constraint. This is required as datatype is changing.** I have added idepotentversion of script as well but same result. 

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0 (8.0.100)
Operating system:IDE:  Visual Studio 2022 17.8.4

Attachments:
[script1.sql.txt](https://github.com/dotnet/efcore/files/13988527/script1.sql.txt)
[script2.sql.txt](https://github.com/dotnet/efcore/files/13988530/script2.sql.txt)
[idemponent.sql.txt](https://github.com/dotnet/efcore/files/13988573/idemponent.sql.txt)

**Comment by ajcvickers** [comment] 2024-01-19 11:53
Duplicate of https://github.com/dotnet/efcore/issues/16758 and https://github.com/dotnet/efcore/issues/12586

**Comment by jp1482** [comment] 2024-01-19 12:37
@ajcvickers Probably this is not complete duplicate by scenario. In my case I am not narrow down the datatype. In my case initial datatype is int and later I made it long. Main issue is with generated sql script because it contains primary key constraint name but it is no where in configuration. 

- In approach to solve the issue I have tried following approach by giving key name but it is not helping. 
```
entity.HasKey(x => x.Id).HasName("PK_Persons");
```

- There is one more approach that is working but not a good option. 
- In this first I give configuration like above and when I make datatype change. I change keyname as well.

```
entity.HasKey(x => x.Id).HasName("PK_Persons_long");
```

This work as expected as it force to generate drop primary key in migration.

**Comment by jp1482** [comment] 2024-01-20 16:09
I try to look into EF Core repository and recent release branch release/8.0

As per my finding it seems that possible cause of this issue is , when dotnet ef tool search for different between source and target model and if it come across finding difference between UniqueConstraint then it is not checking type has been change between source and target.

- MigrationsModelDiffer.cs (Location : src\EFCore.Relational\Migrations\Internal)
In above CS file following code is there. 

```
 protected virtual IEnumerable<MigrationOperation> Diff(
     IEnumerable<IUniqueConstraint> source,
     IEnumerable<IUniqueConstraint> target,
     DiffContext diffContext)
     => DiffCollection(
         source,
         target,
         diffContext,
         Diff,
         Add,
         Remove,
         (s, t, c) => s.Name == t.Name
             && s.Columns.Select(p => p.Name).SequenceEqual(
                 t.Columns.Select(p => c.FindSource(p)?.Name))
             && s.GetIsPrimaryKey() == t.GetIsPrimaryKey()
             && !HasDifferences(s.GetAnnotations(), t.GetAnnotations()));
```

I have modified locally to check with test with following code that include type checknig as well.

```
protected virtual IEnumerable<MigrationOperation> Diff(
    IEnumerable<IUniqueConstraint> source,
    IEnumerable<IUniqueConstraint> target,
    DiffContext diffContext)
    => DiffCollection(
        source,
        target,
        diffContext,
        Diff,
        Add,
        Remove,
        (s, t, c) => s.Name == t.Name
            && s.Columns.Select(p => p.Name).SequenceEqual(
                t.Columns.Select(p => c.FindSource(p)?.Name))
            && s.GetIsPrimaryKey() == t.GetIsPrimaryKey()
            && s.Columns.Select(c => c.StoreType).SequenceEqual(t.Columns.Select(c => c.StoreType))
            && !HasDifferences(s.GetAnnotations(), t.GetAnnotations()));
```

Note: I have done it out of curiosity but after this condition it seems to generate drop and add constraint for primary key.  I have try to add test locally to check this. ( Test is look like following) (SqlServerModelDifferTest.cs)

```
[ConditionalFact]
public void Alter_PrimaryKey_DataType()
=> Execute(
    source => source.Entity(
        "Toad",
        x =>
        {
            x.Property<int>("Id");
            x.HasKey("Id");                
        }),
    target => target.Entity(
        "Toad",
        x =>
        {
            x.Property<long>("Id");
            x.HasKey("Id");                
        }),
    operations =>
    {
        Assert.Equal(3, operations.Count);

        var operation = Assert.IsType<DropPrimaryKeyOperation>(operations[0]);            
        _ = Assert.IsType<AlterColumnOperation>(operations[1]);
        _ = Assert.IsType<AddPrimaryKeyOperation>(operations[2]);
        Assert.Equal("Toad", operation.Table);            
    });
```

**Closed** 2024-01-25 11:21 UTC
Labels: customer-reported

**Comment by wqoq** [comment] 2024-03-25 20:48
> I try to look into EF Core repository and recent release branch release/8.0
> 
> As per my finding it seems that possible cause of this issue is , when dotnet ef tool search for different between source and target model and if it come across finding difference between UniqueConstraint then it is not checking type has been change between source and target.
> 
> * MigrationsModelDiffer.cs (Location : src\EFCore.Relational\Migrations\Internal)
>   In above CS file following code is there.
> 
> ```
>  protected virtual IEnumerable<MigrationOperation> Diff(
>      IEnumerable<IUniqueConstraint> source,
>      IEnumerable<IUniqueConstraint> target,
>      DiffContext diffContext)
>      => DiffCollection(
>          source,
>          target,
>          diffContext,
>          Diff,
>          Add,
>          Remove,
>          (s, t, c) => s.Name == t.Name
>              && s.Columns.Select(p => p.Name).SequenceEqual(
>                  t.Columns.Select(p => c.FindSource(p)?.Name))
>              && s.GetIsPrimaryKey() == t.GetIsPrimaryKey()
>              && !HasDifferences(s.GetAnnotations(), t.GetAnnotations()));
> ```
> 
> I have modified locally to check with test with following code that include type checknig as well.
> 
> ```
> protected virtual IEnumerable<MigrationOperation> Diff(
>     IEnumerable<IUniqueConstraint> source,
>     IEnumerable<IUniqueConstraint> target,
>     DiffContext diffContext)
>     => DiffCollection(
>         source,
>         target,
>         diffContext,
>         Diff,
>         Add,
>         Remove,
>         (s, t, c) => s.Name == t.Name
>             && s.Columns.Select(p => p.Name).SequenceEqual(
>                 t.Columns.Select(p => c.FindSource(p)?.Name))
>             && s.GetIsPrimaryKey() == t.GetIsPrimaryKey()
>             && s.Columns.Select(c => c.StoreType).SequenceEqual(t.Columns.Select(c => c.StoreType))
>             && !HasDifferences(s.GetAnnotations(), t.GetAnnotations()));
> ```
> 

This simple change was enough to get past my impediment. I can't say whether it works for all scenarios, but it worked for mine. I should point out I also had to do something very similar to handle any FKs referencing the same columns. It, too, was a simple matter of overriding the `IForeignKeyConstraint` version of `Diff`, and adding the necessary checks similar to the ones above.

This is what I did in addition to the above:
```
protected override IEnumerable<MigrationOperation> Diff(IEnumerable<IForeignKeyConstraint> source, IEnumerable<IForeignKeyConstraint> target, DiffContext diffContext)
{
    return DiffCollection(
        source,
        target,
        diffContext,
        Diff,
        Add,
        Remove,
        (s, t, c) => s.Name == t.Name
            && s.Columns.Select(p => p.Name).SequenceEqual(t.Columns.Select(p => c.FindSource(p)?.Name))
            && s.Columns.Select(p => p.StoreType).SequenceEqual(t.Columns.Select(p => p.StoreType)) // <-- This
            && s.PrincipalTable == c.FindSource(t.PrincipalTable)
            && s.PrincipalColumns.Select(p => p.Name).SequenceEqual(t.PrincipalColumns.Select(p => c.FindSource(p)?.Name))
            && s.PrincipalColumns.Select(p => p.StoreType).SequenceEqual(t.PrincipalColumns.Select(p => p.StoreType)) // <-- This
            && s.OnDeleteAction == t.OnDeleteAction
            && !HasDifferences(s.GetAnnotations(), t.GetAnnotations()));
}
```
