### ISSUE TITLE
Replacing the Reflection with Source Generators?

### ISSUE THREAD

**Issue by HakamFostok** [dotnet/efcore#27543] opened 2022-03-02 11:36 UTC
@stephentoub has shown great uses cases of source generators in .NET 7 to improve the performance dramatically.

https://www.youtube.com/watch?v=rwfNDyBBgks

My question: Is there any plans to use Source Generators in EF to improve the performance?
And if there is any, When?

Just a wild idea, imagine that LINQ Query on DbContext generates ADO.NET code of the SQL Query and map it to the class  (at compile time without reflection) 
<br/>Would not that be great for the performance of EF, even maybe surpass the performance of Dapper?

I searched the issues before opening this one, and I found nothing, <br/>
Sorry if there is an already opened issue for this

Thank you all

**Comment by roji** [comment] 2022-03-02 11:43
Duplicate of #24903

**Comment by roji** [comment] 2022-03-02 11:45
See also #27156. This wouldn't use source generators, but rather design-time (as opposed to built-time) source generation with Roslyn.

**Comment by HakamFostok** [comment] 2022-03-02 12:02
Thank you, this will be great and hopefully, we will see it in the product as soon as possible
Thank you for all the efforts you do to make EF better

**Closed** 2022-10-16 20:27 UTC
Labels: customer-reported
