### ISSUE TITLE
((IObjectContextAdapter)context).ObjectContext.ObjectMaterialized to convert all dates returned from the database to localtime

### ISSUE THREAD

**Issue by jvelezc** [dotnet/efcore#10681] opened 2018-01-11 05:16 UTC
Hello it was possible to tap into IObjectContextAdapter to convert dates can I have any alternative to tap into and cast the dates from the query to a specific Kind?
```C#
public class YourContext : DbContext
{
  private static readonly List<PropertyInfo> EmptyPropsList = new List<PropertyInfo>();
  private static readonly Hashtable PropsCache = new Hashtable(); // Spec promises safe for single-reader, multiple writer.
                                                                  // Spec for Dictionary makes no such promise, and while
                                                                  // it should be okay in this case, play it safe.
  private static List<PropertyInfo> GetDateProperties(Type type)
  {
    List<PropertyInfo> list = new List<PropertyInfo>();
    foreach(PropertyInfo prop in type.GetProperties())
    {
      Type valType = prop.PropertyType;
      if(valType == typeof(DateTime) || valType == typeof(DateTime?))
        list.Add(prop);
    }
    if(list.Count == 0)
      return EmptyPropsList; // Don't waste memory on lots of empty lists.
    list.TrimExcess();
    return list;
  }
  private static void FixDates(object sender, ObjectMaterializedEventArgs evArg)
  {
    object entity = evArg.Entity;
    if(entity != null)
    {
      Type eType = entity.GetType();
      List<PropertyInfo> rules = (List<PropertyInfo>)PropsCache[eType];
      if(rules == null)
        lock(PropsCache)
          PropsCache[eType] = rules = GetPropertyRules(eType); // Don't bother double-checking. Over-write is safe.
      foreach(var rule in rules)
      {
        var info = rule.PropertyInfo;
        object curVal = info.GetValue(entity);
        if(curVal != null)
          info.SetValue(entity, DateTime.SpecifyKind((DateTime)curVal, rule.Kind));
      }
    }
  }
  public YourContext()
  {
    ((IObjectContextAdapter)this).ObjectContext.ObjectMaterialized += FixDates;
    /* rest of constructor logic here */
  }
  /* rest of context class here */
}
```
as shown in these two stackoverflow
https://stackoverflow.com/questions/29496306/how-to-specify-that-datetime-objects-retrieved-from-entityframework-should-be-da 

https://stackoverflow.com/questions/4648540/entity-framework-datetime-and-utc

**Comment by ajcvickers** [comment] 2018-01-11 17:48
@jvelezc In 2.1, you will be able to do something like this:
```C#
modelBuilder
    .Entity<Foo>()
    .Property(e => e.SomeDate)
    .HasConversion(v => v, v => DateTime.SpecifyKind(v, DateTimeKind.Local));
```
This will ensure every time the date is read from the database it is specified as Local automatically. It will also work in projections, etc. which the code above does not handle.

Closing as duplicate of #242

**Closed** 2022-10-16 12:05 UTC
