### ISSUE TITLE
Lazy building of internal runtime model

### ISSUE THREAD

**Issue by noe555** [dotnet/efcore#29561] opened 2022-11-15 09:11 UTC
## What problem am I trying to solve ?

I am hitting an expected slow initialization time, of a least 3 secondes, but up to 6, for a model of ~40 entities.
I am using an Azure Function App, and thus, the cache is cleared very frequently, and it is (very) frequent to hit the initialization waiting time.
Compiled model solves the issue, but comes with all the limitations listed on the [documentation](https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#compiled-models).
I think that this problem pattern is relatively common with the development of serverless architecture and microservices, where one cannot rely on caching, and exposes multiple (if not many) endpoints, which individually only use a limited subset of the database.

## The solution I can think of

Would it be possible to have a "Lazy" runtime internal model (without Compiled model), where all Model Entities Types and their attributes, are loaded on the fly, when they are needed by queries / adds ?

For example, if in the code of my function, should I do something like :
```
  scopeServicesProvider.GetRequiredService<MyDbContext>().MyEntities
	.Where(m => m.Id == 'someId')
	.Select(m => m.OneAttribute)
	.FirstAsync(...)
```
then only add (assuming it is not already there) in the "global" internal runtime model build the underlying model of MyEntities and in it all (new) necessary fields, entities... needed by the full query expression tree (here, 'Id' and 'OneAttribute' for example), during this very bloc ? Do not load the full MyEntity entity type with all its navigating-descendants entities type, otherwise you may end up loading in the model a huge portion of the database, which would make the performance gain minimal.

By searching at similar issues or enhancement requests, I did find this [er](https://github.com/dotnet/efcore/issues/24899), which I did not understand very well, but my understanding is that it is aimed at improving the Compiled Model generated code, and thus being a different topic.

Thanks a lot for your feedbacks.

**Comment by ajcvickers** [comment] 2022-11-15 10:41
@noe555 What limitations of compiled models are preventing you from using them?

**Comment by noe555** [comment] 2022-11-15 12:30
Hi @ajcvickers , thanks for your response.

Right now there is nothing which prevents us from using compiled model. 
But the overhead of all these extra files to keep up to date, and given the fact that we don't know how our application will evolve (for example, we may need global query filters at some point) have led us into prefering accepting a longuer response time, with an adequate wording and loader in the frontend for our users over it.

This ticket is not a blocking issue, but a nice to have, and as our use cases looked common to us, we though it may be of interest for other people.

Best,
Noe

**Comment by ajcvickers** [comment] 2022-11-19 11:03
Duplicate of https://github.com/dotnet/efcore/issues/24895. Note that this can only work with something like the compiled model where all model discovery has already been performed beforehand.

**Closed by ajcvickers** 2022-11-19 11:03 UTC
Labels: customer-reported
