### ISSUE TITLE
Correct the false information that onDelete is set to ReferentialAction.ClientSetNull for optional relationships

### ISSUE THREAD

**Issue by jurgen-bayer** [dotnet/efcore#18988] opened 2019-11-16 12:18 UTC
The documentation states "By convention, cascade delete will be set to Cascade for required relationships and ClientSetNull for optional relationships.". This is false information. For optional relationships, the delete option is set to `ReferentialAction.Restrict`.

**Comment by ajcvickers** [comment] 2019-11-19 23:18
@freeboarder42 Please post a small, runnable project/solution or complete code listing that demonstrates this behavior so that we can investigate.

**Comment by ajcvickers** [comment] 2019-11-26 21:05
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:57 UTC
Labels: closed-could-not-reproduce, customer-reported
