### ISSUE TITLE
It seems that Include method does not work in some cases (EF core)

### ISSUE THREAD

**Issue by ArtemLysenko** [dotnet/efcore#9122] opened 2017-07-08 10:44 UTC
After I tried to executed my linq query  
```
(from employee in Context.Staff.Include(x => x.ProfilePhotoMetadata)
                    join service in Context.Services on employee.ServiceId equals service.Id
                    join linkToService in Context.BuildingService on service.Id equals linkToService.ServiceId
                    join b in Context.Buildings on linkToService.BuildingId equals b.Id
                    where b.Id == buildingId
                    join linkToBuilding in Context.BuildingEmpoyees on employee.Id equals linkToBuilding.EmpoyeeId
                    join building in Context.Buildings.Include(x => x.Street)
                                                      .Include(x => x.City) on linkToBuilding.BuildingId equals building.Id
                    where employee.ServiceId == serviceId && service.Id == serviceId
                                                            && !service.IsRemoved
                                                            && !building.IsRemoved
                                                            && !linkToBuilding.IsRemoved
                                                            && !employee.IsRemoved
                    group building by employee into g
                    select new
                    {
                        g.Key.Id,
                        g.Key.FirstName,
                        g.Key.LastName,
                        g.Key.MiddleName,
                        g.Key.IsKskAdmin,
                        g.Key.EmployeeType,
                        g.Key.Phone,
                        g.Key.Position,
                        g.Key.Status,
                        g.Key.ProfilePhotoMetadata, <<<<<<<< when add this line I got an error
                        g.Key.ServiceId,
                        Buildings = g.Select(building => new
                        {
                            Id = building.Id,
                            Number = building.Number,
                            Street = building.Street.LangMap(lang),
                            City = building.City.LangMap(lang)
                        })
                    }).ToList()
```
In my Staff table there is relation to FileMetadat table and when I tried to include relation Context.Staff.Include(x => x.ProfilePhotoMetadata) and then used it after grouping I got an exception

```
Exception
System.ArgumentNullException: Value cannot be null.
Parameter name: querySource
   at Remotion.Utilities.ArgumentUtility.CheckNotNull[T](String argumentName, T actualValue)
   at Remotion.Linq.Clauses.Expressions.QuerySourceReferenceExpression..ctor(IQuerySource querySource)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.RewriteNavigationProperties(List`1 properties, IQuerySource querySource, Expression declaringExpression, String propertyName, Type propertyType, Func`2 propertyCreator, Func`2 conditionalAccessPropertyCreator)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.<>c__DisplayClass20_0.<VisitMember>b__0(IEnumerable`1 ps, IQuerySource qs)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindPropertyExpressionCore[TResult](Expression propertyExpression, IQuerySource querySource, Func`3 propertyBinder)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindNavigationPathPropertyExpression[TResult](Expression propertyExpression, Func`3 propertyBinder)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   at Remotion.Linq.Parsing.RelinqExpressionVisitor.VisitNew(NewExpression expression)
   at Remotion.Linq.Clauses.SelectClause.TransformExpressions(Func`2 transformation)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.NavigationRewritingQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Ksk.DataAccess.Repositories.EmployeeRepository.GetEmpoyeesOfBuildingByService(Guid buildingId, Guid serviceId, Language lang) in C:\Users\Artem\Documents\myksk.api\src\Ksk.DataAccess\Repositories\EmployeeRepository.cs:line 161
   at Ksk.Api.Controllers.EmployeesController.GetEmployeesOfBuildingByService(Guid buildingId, Guid serviceId, Language lang) in C:\Users\Artem\Documents\myksk.api\src\Ksk.Api\Controllers\EmployeesController.cs:line 157
```

**Comment by ajcvickers** [comment] 2017-07-10 19:12
@ArtemLysenko It's very hard to figure out what is going on without more information. Can you either provide a full code listing or project that reproduces the issue, or at least a the entity types and their configuration. Also, please report the versions that are being used, as requested in the issue template.

**Comment by ajcvickers** [comment] 2017-07-17 18:16
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:11 UTC
Labels: closed-could-not-reproduce
