### ISSUE TITLE
Query: "Null TypeMapping in Sql Tree" for ternary operator

### ISSUE THREAD

**Issue by Shazhko-Artem** [dotnet/efcore#20657] opened 2020-04-16 13:18 UTC
Example: I am trying to get users from a database and cast each entity to `UserModel`. In addition, I set the `Services` property to a value based on the user value `HasPrimaryStatus`.
```c#
var base = new List<int> {1};
var extended = new List<int> {2};
var users = db.Users.Select(u => new UserModel()
{
     Services = u.HasPrimaryStatus ? extended : base
}).ToList();
````
But when I run this code, I get the following exception:
````c#
System.InvalidOperationException: Null TypeMapping in Sql Tree

   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.SqlTypeMappingVerifyingExpressionVisitor.VisitExtension(Expression node)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConsoleApp3.Program.Main(String[] args) in C:\Users\shazhko\source\repos\ConsoleApp3\ConsoleApp3\Program.cs:line 17
````

Environment Info:
- OS: Windows 10 (Version 1809)
- Framework: netcoreapp3.1
- Microsoft.EntityFrameworkCore.SqlServer: 3.1.3

**Comment by smitpatel** [comment] 2020-04-16 17:18
Duplicate of #19435

**Comment by Krithika03** [comment] 2021-02-05 18:21
I am giving ternary operator for dropdown and I am getting the same error. 
`ParentNameOptions = _context.Person.Select(a => new SelectListItem
                {
                    Value=a.BirthDate.HasValue? a.BirthDate + "-" + a.IndividualNum:Convert.ToString(a.IndividualNum),                
                    Text = a.FirstName + " " + a.MiddleName + " " + a.LastName,
                }).ToList();`

May I know how would I be able to resolve the error. Any help would be appreciated. Thank you!

**Closed** 2022-10-16 18:21 UTC
Labels: customer-reported
