### ISSUE TITLE
Renaming TemporalTable PeriodStart/PeriodEnd maps to incorrect value

### ISSUE THREAD

**Issue by bryanhunwardsen** [dotnet/efcore#32705] opened 2024-01-02 23:20 UTC
Starting w/ an empty DB, an (initializing) migration is created containing:

```C#
public class CustomerMap : EntityMappingConfiguration<Customer>
{
    public override void Map(EntityTypeBuilder<Customer> b)
    {
        b.ToTable("Customer", a => a.IsTemporal(
            x   => 
            {
                x.HasPeriodStart("SysStartTime");
                x.HasPeriodEnd("SysEndTime");
                x.UseHistoryTable("Account", "History");
            }));
    }
}
```
Which produces the below migration code:

```C#
           migrationBuilder.CreateTable(
               name: "Customer",
               columns: table => new
               {
                   SysEndTime = table.Column<DateTime>(type: "datetime2", nullable: false)
                       .Annotation("SqlServer:IsTemporal", true)
                       .Annotation("SqlServer:TemporalPeriodEndColumnName", "SysEndTime")
                       .Annotation("SqlServer:TemporalPeriodStartColumnName", "SysStartTime"),
                   SysStartTime = table.Column<DateTime>(type: "datetime2", nullable: false)
                       .Annotation("SqlServer:IsTemporal", true)
                       .Annotation("SqlServer:TemporalPeriodEndColumnName", "SysEndTime")
                       .Annotation("SqlServer:TemporalPeriodStartColumnName", "SysStartTime"),
                   CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                   CreatedBy = table.Column<string>(type: "varchar(100)", nullable: true),
                   UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                   UpdatedBy = table.Column<string>(type: "varchar(100)", nullable: true)
               }
               .Annotation("SqlServer:IsTemporal", true)
               .Annotation("SqlServer:TemporalHistoryTableName", "Customer")
               .Annotation("SqlServer:TemporalHistoryTableSchema", "History")
               .Annotation("SqlServer:TemporalPeriodEndColumnName", "SysEndTime")
               .Annotation("SqlServer:TemporalPeriodStartColumnName", "SysStartTime");
```

This produces the Table as desired.

Attempting to change the Column names for PeriodStart and PeriodEnd as such:

```C#
public class CustomerMap : EntityMappingConfiguration<Customer>
{
    public override void Map(EntityTypeBuilder<Customer> b)
    {
        b.ToTable("Customer", a => a.IsTemporal(
            x   => 
            {
                x.HasPeriodStart("BeginDate");
                x.HasPeriodEnd("EndDate");
                x.UseHistoryTable("Account", "History");
            }));
    }
}
```

Produces an incorrect migration with the following in the UP:

```C#
public partial class UpdateCustomer : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.RenameColumn(
            name: "SysStartTime",
            table: "Customer",
            newName: "EndDate"); // Should be BeginDate
        migrationBuilder.RenameColumn(
            name: "SysEndTime",
            table: "Customer",
            newName: "BeginDate"); // Should be EndDate
    }
}
```

Expected Result: The rename will map correctly into the generated migration.

EF Core version: 6.0.25
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Win 10
IDE: Visual Studio 2022 17.8.2

**Comment by maumar** [comment] 2024-01-03 01:09
dupe of https://github.com/dotnet/efcore/issues/29902. Current workaround is to rename each column separately.

**Closed** 2024-01-03 14:49 UTC
Labels: closed-duplicate, customer-reported
