### ISSUE TITLE
Bug in EFCore under .NET 6 when using records with inheritance and lazy loading

### ISSUE THREAD

**Issue by richardpawson** [dotnet/efcore#26714] opened 2021-11-16 14:46 UTC
This bug appeared when we were upgrading a substantial existing system that uses EF Core, to .NET 6.0. The error appears as this exception: 

```System.TypeLoadException: 'Return type in method 'Castle.Proxies.SubRecordProxy.<Clone>$()' on type 'Castle.Proxies.SubRecordProxy' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is not compatible with base type method 'EFCoreBugDemo.SubRecord.<Clone>$()'.'```

We have created two separate _minimal reproducible examples_ of the problem here: https://github.com/NakedObjectsGroup/NakedObjectsFramework/tree/master/BugDemo

Start with the **EFCoreBugDemoNet6** project. Running this under VS2022 will generate the exception shown above.

Note these three specific things in the example code, all of which appear to be necessary to reproduce the bug (and all of which are necessary for our own system):

-	Use of `record` as an entity type
-	Use of inheritance between `record ` types
-	Use of  `LazyLoadingProxies` 

Then try the **EFCoreBugDemoNet5** example.  Note that the C# code is identical to the .NET 6 example. Surprisingly:

-	If you run this .NET 5 example under VS2019 it runs OK.
-	If you run this .NET 5 example project from VS2022 you get the same error as in the .NET 6 example.

This suggests to us that the source of the problem might be in the compilation process rather than the libraries _per se_.  It looks to us as though Roslyn is creating the hidden `Clone` method on a `record `type differently in the latest version, such that it no longer works with EF Core.

As it stands it is impossible for us to use EF Core with .NET 6 (given the three requirements above).

**Comment by roji** [comment] 2021-11-16 16:21
Duplicate of #26602

**Closed** 2022-10-16 20:14 UTC
Labels: customer-reported
