### ISSUE TITLE
DateTimeOffset? is evaluted locally since EFCore 2.2.0

### ISSUE THREAD

**Issue by sebastianfilke** [dotnet/efcore#14333] opened 2019-01-06 10:20 UTC
After updating to ef core alle queries with Nullable DateTimeOffset are translated to locally quries. In older version 2.1.x everything was ok.

### Steps to reproduce
Here is an example how to get a locally evaluted query.

2019/01/06 11:19:57.106 | Warn | The LINQ expression 'where (([x].EndDate == null) OrElse (Convert([x].EndDate, DateTimeOffset) >= __now_0))' could not be translated and will be evaluated locally.
2019/01/06 11:19:57.106 | Warn | The LINQ expression 'FirstOrDefault()' could not be translated and will be evaluated locally.

```c#
public async Task<bool> HasActiveNotification() {
            using (var ctx = PersistenceContextFactory.CreateContext()) {
                var now = DateTimeOffset.Now;

                var notificationEntity = await ctx.Set<NotificationEntity>()
                    .Where(x => x.Active && (x.EndDate.Value == null || x.EndDate.Value >= now)).AsNoTracking().FirstOrDefaultAsync()
                    .ConfigureAwait(false);

                return notificationEntity != null;
            }
        }
```

### Further technical details
EF Core version: 2.2.0
Database Provider: SQLite
Operating system: Xamarin.Forms
IDE: Visual Studio 2017 15.9.4

**Comment by ErikEJ** [comment] 2019-01-06 11:45
I believe this is by design (for SQLite)

**Comment by smitpatel** [comment] 2019-01-06 17:56
Duplicate of #14082

**Closed** 2022-10-16 13:46 UTC
Labels: closed-duplicate, customer-reported
