### ISSUE TITLE
Support many-to-many without need to have joining class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#21979] opened 2020-08-06 18:59 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/443784/support-many-to-many-without-need-to-have-joining.html)._

---
<p>As said at: <a href="https://docs.microsoft.com/en-us/ef/core/modeling/relationships#many-to-many" target=_blank>https://docs.microsoft.com/en-us/ef/core/modeling/relationships#many-to-many</a></p><p><em>Many-to-many relationships without an entity class to represent the join table are not yet supported. </em></p><p>Please support it.</p>

---
#### Jane Wu [MSFT] on 2/2/2019, 07:31 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by ajcvickers** [comment] 2020-08-07 18:41
Duplicate of #10508. See #1368.

**Closed** 2022-10-16 18:36 UTC
Labels: closed-duplicate, customer-reported
