### ISSUE TITLE
Please add methods for ExecuteInsert & ExecuteInsertAsync 

### ISSUE THREAD

**Issue by wdhenrik** [dotnet/efcore#29894] opened 2022-12-19 20:32 UTC
I need to perform a Insert based on the result of a Select statement.  The Insert needs to be associated with the first record returned in the Select statement and uses the contents of the record to populate columns in the Insert.

For example, this SQL query would set the Work.Status to In Progress of the first job with a Work.Status of New, and would return the Id of the new Work record created for In Progress.
```
DECLARE @InsertStatus VARCHAR(50) = 'In Progress';
INSERT INTO dbo.Work (JobId,@InsertStatus)
OUTPUT Inserted.Id
            SELECT TOP 1 JobId FROM dbo.Work WHERE Status = 'New';
```
If the Select and Insert are decoupled, then the 'first' record may change between the Select and Insert, leading to concurrency issues.

I would expect the ExecuteInsertAsync syntax to be something like this:
```
await context.Work
    .Where(w => w.Job.First(w=>w.Status=="New"))
    .ExecuteInsertAsync<Work>(w => new (w.Job.Id,"In Progress"));
```
The method would require the Type to be created as a <T>parameter since the query may be involve multiple types.  In this scenario, it would be a waste of resources to Track the New work record as it is only being used to determine which JobId to use when creating the in progress Work record. This method should also bring the created Work record into the context change tracker.

**Comment by roji** [comment] 2022-12-19 23:43
Duplicate of #27320

**Closed** 2022-12-22 12:15 UTC
Labels: closed-duplicate, customer-reported
