### ISSUE TITLE
5.0 nightly breaking save of new object. Regression from earlier version

### ISSUE THREAD

**Issue by NetTecture** [dotnet/efcore#20002] opened 2020-02-20 12:28 UTC
The following code:

            var dbEquipment = new Data.Core.OBTInstallEquipment() {
                GIdentity = equipment.Identity,
                DCreateDate = DateTime.Now,

                OBTEquipment = dbEquipmentType,

                OBTBuilding = dbBuilding,
                OBTBuildingRoom = dbRoom,
                IDTLogin_FkLoginID = dbLogin
            };
            Mapper.Map(equipment, dbEquipment);

            Repository.OBTInstallEquipment.Add(dbEquipment);
            await Repository.SaveChangesAsync();

breaks. Simple like that. This is a copy/paste from a project that is in production with efcore 2.2 at the moment, so this is a regression. The whole ef code is generated, not manually maintained (using devarts EntityDeveloper) and mappings have been regenerted for EfCore 3

The error message is:

  | Name | Value | Type
-- | -- | -- | --
◢ | $exception | {"The value of 'OBTInstallEquipment.PkInstallEquipmentID' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known."} | System.InvalidOperationException

This is irrelevant. As can be seen, OBTInstallEquipment is not set in the new object. The value is unknown because this is an optional foreign key and there is no value.

Stack trace:

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__101.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__55.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by smitpatel** [comment] 2020-02-20 17:00
Please provide a repro code with model configuration to investigate further.

**Comment by ajcvickers** [comment] 2020-02-28 17:07
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:12 UTC
Labels: closed-could-not-reproduce, customer-reported
