### ISSUE TITLE
Null object instead null fields

### ISSUE THREAD

**Issue by AR1ES** [dotnet/efcore#19750] opened 2020-01-30 13:53 UTC
EFCore returns null object when all columns is null instead of return object just with null property values.

### Steps to reproduce

``` C#
	public class TestObj
	{
		public string Field1 { get; set; }
	}

	public class MyDbContext : DbContext
	{
		public DbSet<ClaimRouteAttracted> ClaimRouteAttracted { get; set; }
		protected override void OnModelCreating(ModelBuilder modelBuilder) {
			modelBuilder.Entity<TestObj>().HasNoKey();
			base.OnModelCreating(modelBuilder);
		}
	}

	class Program
	{
		static void Main(string[] args) {
			using(var db = new MyDbContext()) {
				var testCollection = db.Set<TestObj>().FromSqlRaw("SELECT '1' AS Field1 UNION ALL SELECT NULL AS Field1").ToList();

// First item is not null
// Second item is null instead of object with null Field1 value
			}
		}

	}
```

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4

**Comment by ajcvickers** [comment] 2020-01-30 16:40
Duplicate of #19537

**Closed** 2022-10-16 18:08 UTC
Labels: customer-reported
