### ISSUE TITLE
Invalid cast from 'System.Int32' to enum

### ISSUE THREAD

**Issue by dan-vasilov** [dotnet/efcore#20404] opened 2020-03-25 08:11 UTC
I am trying to read items from a CosmosDb database. The code below fails with the error "Invalid cast from 'System.Int32' to 'CosmosDbDemo.Model.OfferStatus'".

``` C#
// Referenced NuGet packages:
// - Microsoft.EntityFrameworkCore 3.1.2
// - Microsoft.EntityFrameworkCore.Cosmos 3.1.2
// - Microsoft.Extensions.DependencyInjection 3.1.2

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Azure.Cosmos.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace CosmosDbDemo
{
    #region CosmosDb parameters
    // Define here your CosmosDb database connection
    class CosmosDbParameters
    {
        public const string AccountEndPoint = "{YOUR-ACCOUNT-ENDPOINT-HERE}";
        public const string AccountKey = "{YOUR-ACCOUNT-KEY-HERE}";
        public const string DbName = "DemoIssues";
        public const string DbContainer = "Offers";
    }
    #endregion


    class Program
    {
        static async Task Main( string[] args )
        {
            // Configure services
            var serviceProvider =
                new ServiceCollection()
                .AddDbContext<OfferContext>( 
                    options => options.UseCosmos(  CosmosDbParameters.AccountEndPoint, CosmosDbParameters.AccountKey, CosmosDbParameters.DbName ) )
                .BuildServiceProvider();

            using var ctx = serviceProvider.GetService<OfferContext>();
        
            // Ensure database has been properly created.
            ctx.Database.EnsureCreated();

            // Insert some items. A future query will try to retrieve only some of them.
            await AddItems( ctx );

            // Query for some items. Reproduces the issue with enums
            // serialized as text.
            await QueryUsingEFWithServerEvaluation( ctx );

            // Query for items, but first pull all items to the client
            // and then execute a filtering operation. This one works,
            // but it's not acceptable.
            await QueryUsingEFWithClientEvaluation( ctx );
        }

        private static async Task QueryUsingEFWithClientEvaluation( OfferContext ctx )
        {
            try
            {
                var offers = await ctx
                                .Offers
                                .ToListAsync();
                offers = offers.Where( _ => _.Status == OfferStatus.Created ).ToList();

                Console.WriteLine( $"With client evaluation: {offers.Count} offers found" );
            }
            catch( Exception ex )
            {
                Console.Write( ex );
            }
        }

        private static async Task QueryUsingEFWithServerEvaluation( OfferContext ctx )
        {
            try
            {
                // The call below fails with exception
                // "Invalid cast from 'System.Int32' to 'CosmosDbDemo.Model.OfferStatus'"
                var offers = await ctx
                                .Offers
                                .Where( _ => _.Status == OfferStatus.Created  )
                                .ToListAsync();

                Console.WriteLine( $"With server evaluation: {offers.Count} offers found" );
            }
            catch( Exception ex )
            {
                Console.Write( ex );
            }
        }

        private static async Task AddItems( OfferContext ctx )
        {
            var offer = BuildOffer( "Acme Offer 1", 14 );
            ctx.Add( offer );
            offer = BuildOffer( "Acme Offer 2", 30 );
            ctx.Add( offer );
            offer = BuildOffer( "Coyote Ugly Super Offer 1", 25 );
            ctx.Add( offer );
            offer = BuildOffer( "Sloth Supercars Offer 14", 10 );
            ctx.Add( offer );
            await ctx.SaveChangesAsync();
        }

        private static Offer BuildOffer( string name, int valabilityInDays )
        {
            var result = new Offer
            {
                Id = Guid.NewGuid(),
                Name = name,
                ExpirationDateUtc = DateTime.UtcNow.Date.AddDays( valabilityInDays ),
                Status = OfferStatus.Created
            };

            return result;
        }
    }

    class Offer
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public DateTime ExpirationDateUtc { get; set; }
        public OfferStatus Status { get; set; }
    }

    enum OfferStatus
    {
        Created = 0,
        Approved = 1,
        Accepted = 2,
        Declined = 3
    }

    class OfferContext : DbContext
    {
        public OfferContext( DbContextOptions<OfferContext> options ) : base( options )
        {

        }

        public DbSet<Offer> Offers { get; set; }


        protected override void OnModelCreating( ModelBuilder modelBuilder )
        {
            modelBuilder.HasDefaultContainer( CosmosDbParameters.DbContainer );
            modelBuilder.Entity<Offer>().HasPartitionKey( _ => _.Id );
            modelBuilder.Entity<Offer>().Property( _ => _.Id )
                    .HasConversion( _ => _.ToString( "B" ), _ => Guid.Parse( _ ) );
            modelBuilder.Entity<Offer>().Property( _ => _.Status )
                    .HasConversion( _ => _.ToString(), _ => (OfferStatus)Enum.Parse( typeof( OfferStatus ), _ ) );
        }
    }

}
```
```
Exception information:
System.InvalidCastException: Invalid cast from 'System.Int32' to 'CosmosDbDemo.OfferStatus'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.Int32.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass3_0`2.<SanitizeConverter>b__0(Object v)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.QuerySqlGenerator.GenerateJToken(Object value, CoreTypeMapping typeMapping)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.QuerySqlGenerator.VisitSqlConstant(SqlConstantExpression sqlConstantExpression)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.SqlExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.QuerySqlGenerator.VisitSqlBinary(SqlBinaryExpression sqlBinaryExpression)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.SqlExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.QuerySqlGenerator.VisitSqlBinary(SqlBinaryExpression sqlBinaryExpression)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.SqlExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.QuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.SqlExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.QuerySqlGenerator.GetSqlQuery(SelectExpression selectExpression, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at CosmosDbDemo.Program.QueryUsingEFWithServerEvaluation(OfferContext ctx) in D:\Work\CosmosDbDemo\Program.cs:line 134
```

### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: .NET Core 3.1
Operating system: Windows 10.0.18363.720
IDE: Visual Studio 2019 16.5.0

**Comment by maumar** [comment] 2020-03-25 23:07
dupe of #19128

**Comment by stack111** [comment] 2020-08-12 21:57
Hello @maumar and @ajcvickers, I would like to reopen this issue. I have a consistent repro between using EFCore and AsQueryable() Linq via Cosmos DB Client. Please see referenced [github repo](https://github.com/stack111/ODataEFCore12557) to demonstrate the case. 

```
   <TargetFramework>netcoreapp3.1</TargetFramework>

    <PackageReference Include="Microsoft.AspNetCore.OData" Version="7.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.OData.Versioning" Version="4.1.1" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.12.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Cosmos" Version="3.1.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
```

The repro doesn't include include any setup data but it is reproducible even without data because the exception is thrown somewhere prior to the outbound call to Cosmos DB.

**Comment by smitpatel** [comment] 2020-08-13 18:05
Duplicate of #20916 ?

**Comment by smitpatel** [comment] 2020-08-13 18:06
We applied patch fix only for relational providers and not for cosmos.

**Comment by stack111** [comment] 2020-08-13 18:50
So not fixed for Cosmos. @smitpatel Is that being tracked?

**Comment by ajcvickers** [comment] 2020-08-14 18:33
This is fixed for Cosmos in EF Core 5.0. We don't currently plan to back-port the fix to 3.1.x.

**Comment by drdamour** [comment] 2020-10-31 03:30
@ajcvickers was there a wrokaround identified for this for us stuck on 3.1?

**Comment by ajcvickers** [comment] 2020-11-03 20:09
@smitpatel @AndriySvyryd @maumar What is the risk of patching this for Cosmos in 3.1?

**Comment by ajcvickers** [comment] 2020-11-16 23:50
@smitpatel Don't forget this 3.1.x patch candidate.

**Comment by smitpatel** [comment] 2020-11-16 23:53
<img src="https://static.magiquiz.com/wp-content/uploads/2019/01/Surprised-Pikachu.png" />

**Closed** 2021-01-14 00:34 UTC
Labels: Servicing-approved, area-cosmos, area-query, closed-fixed, customer-reported, type-bug

**Comment by stack111** [comment] 2021-01-15 19:44
Confirmed Fixed, thank you!
