### ISSUE TITLE
EFCORE performance issue

### ISSUE THREAD

**Issue by alagarit** [dotnet/efcore#24069] opened 2021-02-05 07:51 UTC
As we were using EFcore 1.1.1 with target framework 4.6.2 dbfirst approach later we did upgrade efcore 2.2.6 with targetframework .netcore2.1. 

after the migration performance is very slow. is there any keypoints to modify in core level .Please advice.

**Comment by anranruye** [comment] 2021-02-05 08:45
I have no idea. Well, note that both ef core 1.1 and ef core 2.2 are no longer supported.

**Comment by roji** [comment] 2021-02-05 10:59
@alagarit as @anranruye noted, both 1.1 and 2.2 are out of support. EF Core 3.1 still supports .NET Framework and will be supported until the December 2021, so it's highly recommended to at least switch to that.

If you still run into issues with 3.1, we'd need more details on exactly what the problem us, including a runnable code sample that demonstrates the performance issue.

**Comment by ajcvickers** [comment] 2021-02-12 16:50
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:22 UTC
Labels: closed-could-not-reproduce, customer-reported
