### ISSUE TITLE
How can i easily configure the value comparison of the change-tracker to be value-equality instead of reference-equality?

### ISSUE THREAD

**Issue by gulvklud** [dotnet/efcore#34248] opened 2024-07-19 07:48 UTC
Hi,

Is there any way to easily change all the value comparer's to use value-equality instead of reference-equality?

Specifically, I am very early in the implementation process but so far I have experienced the comparison seemed to fail for both `string` and `DateTimeOffset`, meaning that they were flagged as modified even though their value was the same - I believe it was because their references were not?

I have currently fixed the issue I am having with the following code, but I'm not a fan of having to re-iterate all the modified entries instead of having the change tracker just not flag them in the first place - surely there must be an better way?

```
public abstract class BaseDbContext(DbContextOptions options) : DbContext(options)
{
    public override Task<int> SaveChangesAsync(CancellationToken token = default)
    {
        ValidateEntityChanges(ChangeTracker.Entries());

        try
        {
            ChangeTracker.AutoDetectChangesEnabled = false;
            return base.SaveChangesAsync(token);
        }
        finally
        {
            ChangeTracker.AutoDetectChangesEnabled = true;
        }
    }

    public override int SaveChanges()
    {
        ValidateEntityChanges(ChangeTracker.Entries());

        try
        {
            ChangeTracker.AutoDetectChangesEnabled = false;
            return base.SaveChanges(); 
        }
        finally
        {
            ChangeTracker.AutoDetectChangesEnabled = true;
        }
    }

    private static void ValidateEntityChanges(IEnumerable<EntityEntry> entries)
    {
        foreach (var entry in entries.Where(entry => entry.State == EntityState.Modified))
        {
            foreach (var property in entry.Properties.Where(property => property.IsModified))
            {
                // value-equality instead of reference-equality.
                if (Equals(property.OriginalValue, property.CurrentValue))
                {
                    property.IsModified = false;
                }
            }

            if (entry.Properties.All(property => !property.IsModified))
            {
                entry.State = EntityState.Unchanged;
            }
        }
    }
}
```

**Comment by roji** [comment] 2024-07-19 08:20
> Specifically, I am very early in the implementation process but so far I have experienced the comparison seemed to fail for both string and DateTimeOffset, meaning that they were flagged as modified even though their value was the same - I believe it was because their references were not?

This doesn't sound right - these types should already be compared by value, and you shouldn't need the above code which manually changes the entity state.

Please post a minimal, runnable console app showing string/DateTimeOffset not being handled correctly.

**Comment by AndriySvyryd** [comment] 2024-08-08 20:00
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2024-08-08 20:00 UTC
Labels: customer-reported
