### ISSUE TITLE
Change Tracker very slow

### ISSUE THREAD

**Issue by llehn** [dotnet/efcore#11680] opened 2018-04-15 14:09 UTC
Using 2.0, I'm doing this per request:

1. Creating new context
2. Attaching a fairly large argregate root (object graph) with 3000 objects to the context
3. making changes to some objects
4. calling SaveChanges

The whole thing becomes unbearably slow - taking >100ms - with more than a couples hundred objects.

Is this supposed to be that slow? Am I doing something wrong? 

Thanks

**Comment by sam-wheat** [comment] 2018-04-15 21:48
[See this post](https://blog.oneunicorn.com/2012/03/12/secrets-of-detectchanges-part-3-switching-off-automatic-detectchanges/)

I find DbContext is good for tracking tens, not hundreds or thousands of entities.  A good approach is to make sure your context is short lived and your batch size is ~10 perhaps less.

    using(DbContext db = new DbContext()  // new context is very fast
	{
          for(int I = 0;i< 10;i++)
		db.Entry(entity).State = EntityState.Added; // tens, not hundreds
   
          db.SaveChanges();
	}

**Comment by ajcvickers** [comment] 2018-04-16 19:34
@llehn Can you post the code that you are using to attach/change/save?

**Comment by llehn** [comment] 2018-04-16 22:47
Here's the simplified code doing the attaching / saving:



````
private void ExecuteCommand<TCommand>(TCommand command, DomainCommandHandler<TCommand, TState> handler)
{
...
using (var dbContext = dbContextFunc())
            {
                try
                {
                    InitState(dbContext.Instance);

                    handler.ValidateCommand(command);
                    handler.ValidateCommandForState(command, state);
                    validationSucceeded = true;

                    handler.ExecuteCommand(command, state);
                    dbContext.Instance.SaveChanges();
                }
                catch (Exception exception)
                {
                    ...
                }
            }
...
}
````
InitState looks like this:
````
private void InitState(AggregateRootDbContext<TState> context)
        {
            if (state != null)
            {
                context.Attach(state);
                return;
            }

            var id = Guid.Parse(Self.Path.Name);

            state = context.Find(id);
            if (state == null)
            {
                state = context.CreateNew();
                state.Id = id;
                context.Add(state);
            }
            else
            {
                context.Attach(state);
            }
        }
````

state is a generic field (TState) in a generic class ````AggregateRootWrapper<TState>````.
Modifications happen in ````handler.ExecuteCommand(command, state)````

The code that I was profiling was using this entity (this is the concrete type of TState in this case)
````
public sealed class StorageUnit: Entity
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public IndexedList<Location, Guid> Locations { get; } 
            = new IndexedList<Location, Guid>().WithId(location => location.Id);
        ...
   }
````

In the particular case I was profiling the code was adding another entry to the ````Locations```` list:

````
public override void ExecuteCommand(AddLocationCommand command, StorageUnit state)
        {
            var location = new Location
            {
                Type = command.Type,
                ....
                IncrementTopDown = command.IncrementTopDown
            };

            state.Locations.Add(location);
        }
````

````IndexedList<>```` is a class:
````public sealed class IndexedList<T, TKey> : IList<T>````

Here's a screenshot from a profiler when running with ~3000 Locations and adding another one:
![image](https://user-images.githubusercontent.com/10240910/38838880-83765516-41d8-11e8-9cd5-b0e7f64442da.png)

**Comment by llehn** [comment] 2018-04-17 00:07
@ajcvickers just read on your block EF Core also supports non-snapshotting change tracking via INotifyStuff. I'm going to try that next.

**Comment by ajcvickers** [comment] 2018-04-18 20:54
@llehn Thanks for the additional information. I have reference this issue from #9422 to make use of the information when we work on perf here. Closing this issue as a duplicate of #9422.

**Closed** 2022-10-16 12:18 UTC
