### ISSUE TITLE
Firstotdefault async error

### ISSUE THREAD

**Issue by nadavbeno** [dotnet/efcore#15426] opened 2019-04-21 04:49 UTC
When I run the old command for example: 
```C#
await dbContext.Posts.FirstOrDefaultAsync(e=>e.Email.Equals("someone@something.com")) 
```
I get this error: Error generated for warning:

> 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'where...' could not be translated and will be evaluated locally.'. This exception can be suppressed or logged by passing event ID 'RelationalEventId.QueryClientEvaluationWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'."

What can I do about that? I've tried in the startup class: 

```C#
.ConfigureWarnings(warnings => warnings.Throw(RelationalEventId.QueryClientEvaluationWarning)) 
```

Didn't help.... What should I do?

**Comment by divega** [comment] 2019-04-21 06:37
Cc @smitpatel, @ajcvickers

**Comment by divega** [comment] 2019-04-21 06:43
@nadavbeno thanks a lot for reporting the issue here. I can not verify this at the moment, but it is possible that Equals method doesn’t get translated, but the `=` operator is. As a temporary workaround, you can try that. 

If that doesn’t help, use warnings.Warn or warnings.Ignore instead of warnings.Throw in ConfigureWarnings. things I would try is

**Comment by nadavbeno** [comment] 2019-04-21 08:59
== works... Thanks a lot!
So I'll change my cases of StringComparison.OrdinalIgnoreCase to "ToLower" in each case of compare strings... Or, do you have another idea...?
Thanks.

**Comment by divega** [comment] 2019-04-21 13:19
If you control the collation of the column (EF Core doesn’t currently have first class APIs for it, but you can achieve it writing your own DDL), you can make sure it is case insensitive and then use `==`, and that should work.

**Comment by nadavbeno** [comment] 2019-04-21 13:28
Great. Thanks a lot :)

**Comment by smitpatel** [comment] 2019-04-24 21:17
Duplicate of #1222

**Closed** 2022-10-16 14:18 UTC
Labels: customer-reported
