### ISSUE TITLE
Bug in EF Core causing unexpected MERGE statements on unrelated tables.

### ISSUE THREAD

**Issue by chris-briddock** [dotnet/efcore#34259] opened 2024-07-21 01:10 UTC
## File a bug
The below code on my project ChristopherBriddock.Identity is causing a MERGE statement to result in a Foreign Key constraint.

The table it is inserting into is SYSTEM_IDENTITY_CLIENT_APPLICATIONS and SYSTEM_IDENTITY_LINK_USER_CLIENT_APPLICATIONS.

The main table and the link table have no bearing on the SYSTEM_IDENTITY_USER_ROLE table.

### Include your code

``` csharp
  [Route($"{Routes.BaseRoute.Name}")]
public sealed class CreateApplicationEndpoint : EndpointBaseAsync
                                                .WithRequest<CreateApplicationRequest>
                                                .WithActionResult
{
    /// <summary>
    /// Provides access to application services.
    /// </summary>
    public IServiceProvider Services { get; }

    /// <summary>
    /// Logger instance for logging within this endpoint.
    /// </summary>
    public ILogger<CreateApplicationEndpoint> Logger { get; }

    /// <summary>
    /// Initializes a new instance of <see cref="CreateApplicationEndpoint"/>
    /// </summary>
    /// <param name="services">The application's service provider.</param>
    /// <param name="logger">The application logger.</param>
    public CreateApplicationEndpoint(IServiceProvider services,
                                     ILogger<CreateApplicationEndpoint> logger)
    {
        Services = services ?? throw new ArgumentNullException(nameof(services));
        Logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }
    /// <summary>
    /// Creates a new application tied to a user.
    /// </summary>
    /// <param name="request">The object which encapsulates the request body.</param>
    /// <param name="cancellationToken">The cancellation token to cancel the operation.</param>
    /// <returns></returns>
    [HttpPost($"{Routes.Applications.Create}")]
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    public override async Task<ActionResult> HandleAsync(CreateApplicationRequest request,
                                                         CancellationToken cancellationToken = default)
    {
        try
        {
            var dbContext = Services.GetRequiredService<AppDbContext>();
            var userManager = Services.GetRequiredService<UserManager<User>>();
            var userClaimsPrincipal = User.FindFirst(ClaimTypes.Email);

            if (userClaimsPrincipal is null)
                return BadRequest();

            User? user = await userManager.FindByEmailAsync(userClaimsPrincipal.Value);
            
            if (user is null)
                return BadRequest("User not found.");

            var secretBytes = Encoding.UTF8.GetBytes(Ulid.NewUlid().ToString());
            var secret = Convert.ToBase64String(secretBytes);

            var applicationExists = await dbContext.ClientApplications.AnyAsync(a => a.Name == request.Name, cancellationToken);
            
            if (applicationExists)
                return BadRequest("Application with this name already exists.");

            Logger.LogInformation("User found: {UserId}", user.Id);

            ClientApplication application = new()
            {
                Name = request.Name,
                CallbackUri = request.CallbackUri,
                RedirectUri = request.RedirectUri,
                CreatedBy = user.Email!,
                ClientSecret = secret
            };

            var userClientApplication = new UserClientApplication()
            {
                UserId = user.Id,
                ApplicationId = application.Id
            };

            await dbContext.ClientApplications.AddAsync(application, cancellationToken);
            await dbContext.UserClientApplications.AddAsync(userClientApplication, cancellationToken);
            await dbContext.SaveChangesAsync(cancellationToken);

            return StatusCode(StatusCodes.Status201Created);
        }
        catch (Exception ex)
        {
            Logger.LogError("Error in endpoint: {endpointName} - {methodName} Error details: {ex}", nameof(CreateApplicationEndpoint), nameof(HandleAsync), ex);
            return StatusCode(StatusCodes.Status500InternalServerError);
        }
    }
}
```

### Include stack traces

```
[00:51:25 INF] Executed DbCommand (4ms) [Parameters=[@p0='f234a38e-4c56-41bd-97df-9b27818d0870' (Nullable = false) (Size = 450), @p1='https://localhost:7171/callback' (Nullable = false) (Size = 4000), @p2='b3084694-f304-494e-9cd1-909ad453d843' (Nullable = false) (Size = 4000), @p3='MDFKMzk4WDZGQVFTWlBXWkUyNDJOUjhWRDc=' (Nullable = false) (Size = 4000), @p4='admin@default.com' (Nullable = false) (Size = 4000), @p5=NULL (Size = 4000), @p6=NULL (DbType = DateTime2), @p7='False', @p8=NULL (Size = 4000), @p9=NULL (DbType = DateTime2), @p10='DefaultApp' (Nullable = false) (Size = 4000), @p11='https://localhost:7171' (Nullable = false) (Size = 4000), @p12='5648e676-54cc-47b0-b64b-358f4a6be79c' (Nullable = false) (Size = 450), @p13='2fbaf45e-744b-476b-98ee-e7c5f82a97ec' (Nullable = false) (Size = 450), @p14='5648e676-54cc-47b0-b64b-358f4a6be79c' (Nullable = false) (Size = 450), @p15='773184e9-baaa-4356-8c6d-644dccbcb6ae' (Nullable = false) (Size = 450), @p16='5648e676-54cc-47b0-b64b-358f4a6be79c' (Nullable = false) (Size = 450), @p17='b4b09ec6-43d6-4721-a388-77e5618dbd18' (Nullable = false) (Size = 450), @p18='f2c23d00-e783-43a5-90eb-c8ce79db0927' (Nullable = false) (Size = 450), @p19='b4b09ec6-43d6-4721-a388-77e5618dbd18' (Nullable = false) (Size = 450), @p20='5648e676-54cc-47b0-b64b-358f4a6be79c' (Nullable = false) (Size = 450), @p21='f8134c1e-af04-49fd-8e6e-8739476513b1' (Nullable = false) (Size = 450), @p22='a0b4c18f-d78e-421d-82c1-0e4ade68dfef' (Nullable = false) (Size = 450), @p23='f234a38e-4c56-41bd-97df-9b27818d0870' (Nullable = false) (Size = 450), @p24='4a474ba0-bca4-45b2-affb-d00d1e15f3d4' (Nullable = false) (Size = 450)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [SYSTEM_IDENTITY_CLIENT_APPLICATIONS] ([Id], [CallbackUri], [ClientId], [ClientSecret], [CreatedBy], [DeletedBy], [DeletedOnUtc], [IsDeleted], [ModifiedBy], [ModifiedOnUtc], [Name], [RedirectUri])
OUTPUT INSERTED.[CreatedOnUtc], INSERTED.[PeriodEnd], INSERTED.[PeriodStart]
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11);
MERGE [SYSTEM_LINK_IDENTITY_USER_ROLES] USING (
VALUES (@p12, @p13, 0),
(@p14, @p15, 1),
(@p16, @p17, 2),
(@p18, @p19, 3),
(@p20, @p21, 4)) AS i ([RoleId], [UserId], _Position) ON 1=0
WHEN NOT MATCHED THEN
INSERT ([RoleId], [UserId])
VALUES (i.[RoleId], i.[UserId])
OUTPUT INSERTED.[PeriodEnd], INSERTED.[PeriodStart], i._Position;
INSERT INTO [SYSTEM_LINK_IDENTITY_USER_CLIENT_APPLICATIONS] ([Id], [ApplicationId], [UserId])
OUTPUT INSERTED.[PeriodEnd], INSERTED.[PeriodStart]
VALUES (@p22, @p23, @p24);
[00:51:25 ERR] An exception occurred in the database while saving changes for context type 'Persistence.Contexts.AppDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The MERGE statement conflicted with the FOREIGN KEY constraint "FK_SYSTEM_LINK_IDENTITY_USER_ROLES_SYSTEM_IDENTITY_USERS_UserId". The conflict occurred in database "ChristopherBriddock.Service.Identity", table "dbo.SYSTEM_IDENTITY_USERS", column 'Id'.
```

### Include provider and version information

EF Core version: 8.0.7
Database provider: Microsoft.EntityFrameworkCore.SqlServer)
Target framework: ..NET 8
Operating system: Debian
IDE: Visual Studio Code

**Comment by roji** [comment] 2024-07-21 07:39
This very likely means that you have en EF model where you've told EF that there's a required navigation (e.g. an application must have a user/role), but you're attempting to insert without one, triggering a violation. Carefully review what you're inserting and how your model looks like.

Beyond that, if you believe there's an EF problem, you'll have to submit a minimal, runnable console program to allow us to reproduce the problem.

**Comment by AndriySvyryd** [comment] 2024-08-08 19:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by AndriySvyryd** 2024-08-08 19:10 UTC
Labels: customer-reported
