### ISSUE TITLE
Eager Load Results In Null Collection If No Items Present

### ISSUE THREAD

**Issue by StrangeWill** [dotnet/efcore#6277] opened 2016-08-09 19:18 UTC
Given a setup like this:

```
public class SomeItem
{
    public Guid Id { get; set; }

    public ICollection<OtherThing> OtherThings { get; set; }

    protected override void OnModelCreating(EntityTypeBuilder<SomeItem> entity)
    {
    }
}

public class OtherThing
{
    public Guid Id { get; set; }

    public Guid SomeItemId { get; set; }

    public SomeItem SomeItem { get; set; }

    protected override void OnModelCreating(EntityTypeBuilder<OtherThing> entity)
    {
        entity.HasOne(e => e.SomeItem).WithMany(e => e.OtherThings).HasForeignKey(e => e.SomeItemId);
    }
}

public void QueryItems()
{
    var item = dbContext.SomeItems.Include(s => s.OtherThings).FirstOrDefault(); // Returns an item for sake of example
    item.OtherThings // this is null instead of empty collection.
}
```

We see a collection being null when it _should_ be an empty collection from what I can gather.

Am I missing something or is this a bug?

Workaround is to initialize the ICollection in the constructor, but it seems like I shouldn't have to.

**Comment by ajcvickers** [comment] 2016-08-11 00:41
@StrangeWill I am not able to reproduce this. Which version of EF Core are you using?

**Comment by ajcvickers** [comment] 2016-08-17 22:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 09:53 UTC
Labels: closed-could-not-reproduce
