### ISSUE TITLE
NU3004 When installing Microsoft.EntityFrameworkCore.SqlServer 

### ISSUE THREAD

**Issue by silverf1re** [dotnet/efcore#15822] opened 2019-05-27 21:14 UTC
Describe what is not working as expected.
I am trying to inhstall Microsoft.EntityFrameworkCore.SqlServer using the nuget window in rider IDE 
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
`@ Installing Microsoft.EntityFrameworkCore.SqlServer in SaflyAndSons started
Restoring packages for /Users/scottbush/Documents/Source/SaflyAndSonsSportingGoods/WebApp/SaflyAndSons/SaflyAndSons.csproj...
  GET https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json 104ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json
  OK https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json 427ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json 287ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json 300ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json 293ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json
  OK https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json 310ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json 289ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.sqlserver/3.0.0-preview5.19227.1/microsoft.entityframeworkcore.sqlserver.3.0.0-preview5.19227.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.sqlserver/3.0.0-preview5.19227.1/microsoft.entityframeworkcore.sqlserver.3.0.0-preview5.19227.1.nupkg 38ms
  GET https://api.nuget.org/v3-flatcontainer/system.data.sqlclient/index.json
  OK https://api.nuget.org/v3-flatcontainer/system.data.sqlclient/index.json 29ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.data.sqlclient/index.json
  OK https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.data.sqlclient/index.json 98ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/system.data.sqlclient/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/system.data.sqlclient/index.json 71ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/system.data.sqlclient/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/system.data.sqlclient/index.json 68ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/system.data.sqlclient/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/system.data.sqlclient/index.json 70ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/system.data.sqlclient/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/system.data.sqlclient/index.json 71ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/system.data.sqlclient/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/system.data.sqlclient/index.json 70ms
  GET https://api.nuget.org/v3-flatcontainer/system.data.sqlclient/4.7.0-preview5.19224.8/system.data.sqlclient.4.7.0-preview5.19224.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.data.sqlclient/4.7.0-preview5.19224.8/system.data.sqlclient.4.7.0-preview5.19224.8.nupkg 36ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.win32.registry/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.win32.registry/index.json 38ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.win32.registry/index.json
  OK https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.win32.registry/index.json 84ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/microsoft.win32.registry/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/microsoft.win32.registry/index.json 67ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/microsoft.win32.registry/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/microsoft.win32.registry/index.json 75ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/microsoft.win32.registry/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/microsoft.win32.registry/index.json 73ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/microsoft.win32.registry/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/microsoft.win32.registry/index.json 68ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/microsoft.win32.registry/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/microsoft.win32.registry/index.json 74ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.native.system.data.sqlclient.sni/index.json
  OK https://api.nuget.org/v3-flatcontainer/runtime.native.system.data.sqlclient.sni/index.json 65ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/runtime.native.system.data.sqlclient.sni/index.json
  OK https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/runtime.native.system.data.sqlclient.sni/index.json 95ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/runtime.native.system.data.sqlclient.sni/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/runtime.native.system.data.sqlclient.sni/index.json 68ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/runtime.native.system.data.sqlclient.sni/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/runtime.native.system.data.sqlclient.sni/index.json 69ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/runtime.native.system.data.sqlclient.sni/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/runtime.native.system.data.sqlclient.sni/index.json 69ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/runtime.native.system.data.sqlclient.sni/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/runtime.native.system.data.sqlclient.sni/index.json 68ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/runtime.native.system.data.sqlclient.sni/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/runtime.native.system.data.sqlclient.sni/index.json 70ms
  GET https://api.nuget.org/v3-flatcontainer/system.security.principal.windows/index.json
  OK https://api.nuget.org/v3-flatcontainer/system.security.principal.windows/index.json 32ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.security.principal.windows/index.json
  OK https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.security.principal.windows/index.json 72ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/system.security.principal.windows/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/system.security.principal.windows/index.json 394ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/system.security.principal.windows/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/system.security.principal.windows/index.json 68ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/system.security.principal.windows/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/system.security.principal.windows/index.json 70ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/system.security.principal.windows/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/system.security.principal.windows/index.json 68ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/system.security.principal.windows/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/system.security.principal.windows/index.json 68ms
  GET https://api.nuget.org/v3-flatcontainer/system.text.encoding.codepages/index.json
  OK https://api.nuget.org/v3-flatcontainer/system.text.encoding.codepages/index.json 41ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.win32.registry/4.6.0-preview5.19224.8/microsoft.win32.registry.4.6.0-preview5.19224.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.win32.registry/4.6.0-preview5.19224.8/microsoft.win32.registry.4.6.0-preview5.19224.8.nupkg 38ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.text.encoding.codepages/index.json
  OK https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.text.encoding.codepages/index.json 84ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/system.text.encoding.codepages/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/system.text.encoding.codepages/index.json 68ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/system.text.encoding.codepages/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/system.text.encoding.codepages/index.json 69ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/system.text.encoding.codepages/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/system.text.encoding.codepages/index.json 68ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/system.text.encoding.codepages/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/system.text.encoding.codepages/index.json 68ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/system.text.encoding.codepages/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/system.text.encoding.codepages/index.json 69ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.native.system.data.sqlclient.sni/4.6.0-preview5.19224.8/runtime.native.system.data.sqlclient.sni.4.6.0-preview5.19224.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.native.system.data.sqlclient.sni/4.6.0-preview5.19224.8/runtime.native.system.data.sqlclient.sni.4.6.0-preview5.19224.8.nupkg 38ms
  GET https://api.nuget.org/v3-flatcontainer/system.security.principal.windows/4.6.0-preview5.19224.8/system.security.principal.windows.4.6.0-preview5.19224.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.security.principal.windows/4.6.0-preview5.19224.8/system.security.principal.windows.4.6.0-preview5.19224.8.nupkg 35ms
  GET https://api.nuget.org/v3-flatcontainer/system.text.encoding.codepages/4.6.0-preview5.19224.8/system.text.encoding.codepages.4.6.0-preview5.19224.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.text.encoding.codepages/4.6.0-preview5.19224.8/system.text.encoding.codepages.4.6.0-preview5.19224.8.nupkg 35ms
  GET https://api.nuget.org/v3-flatcontainer/system.security.accesscontrol/index.json
  OK https://api.nuget.org/v3-flatcontainer/system.security.accesscontrol/index.json 34ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.security.accesscontrol/index.json
  OK https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.security.accesscontrol/index.json 80ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/system.security.accesscontrol/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/system.security.accesscontrol/index.json 67ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/system.security.accesscontrol/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/system.security.accesscontrol/index.json 69ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/system.security.accesscontrol/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/system.security.accesscontrol/index.json 77ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/system.security.accesscontrol/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/system.security.accesscontrol/index.json 71ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/system.security.accesscontrol/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/system.security.accesscontrol/index.json 73ms
  GET https://api.nuget.org/v3-flatcontainer/system.security.accesscontrol/4.6.0-preview5.19224.8/system.security.accesscontrol.4.6.0-preview5.19224.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.security.accesscontrol/4.6.0-preview5.19224.8/system.security.accesscontrol.4.6.0-preview5.19224.8.nupkg 22ms
Installing System.Security.AccessControl 4.6.0-preview5.19224.8.
Installing Microsoft.Win32.Registry 4.6.0-preview5.19224.8.
Installing System.Text.Encoding.CodePages 4.6.0-preview5.19224.8.
Installing System.Security.Principal.Windows 4.6.0-preview5.19224.8.
Installing runtime.native.System.Data.SqlClient.sni 4.6.0-preview5.19224.8.
NU3004: Package 'Microsoft.Win32.Registry 4.6.0-preview5.19224.8' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
NU3004: Package 'System.Security.AccessControl 4.6.0-preview5.19224.8' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
Installing Microsoft.EntityFrameworkCore.SqlServer 3.0.0-preview5.19227.1.
Installing System.Data.SqlClient 4.7.0-preview5.19224.8.
NU3004: Package 'runtime.native.System.Data.SqlClient.sni 4.6.0-preview5.19224.8' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
NU3004: Package 'Microsoft.EntityFrameworkCore.SqlServer 3.0.0-preview5.19227.1' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
NU3004: Package 'System.Security.Principal.Windows 4.6.0-preview5.19224.8' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
NU3004: Package 'System.Text.Encoding.CodePages 4.6.0-preview5.19224.8' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
NU3004: Package 'System.Data.SqlClient 4.7.0-preview5.19224.8' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
Package restore failed. Rolling back package changes for 'SaflyAndSons'.
NuGet.PackageManagement.PackageReferenceRollbackException: Package restore failed. Rolling back package changes for 'SaflyAndSons'.
  at NuGet.PackageManagement.NuGetPackageManager.ExecuteBuildIntegratedProjectActionsAsync (NuGet.ProjectManagement.Projects.BuildIntegratedNuGetProject buildIntegratedProject, System.Collections.Generic.IEnumerable`1[T] nuGetProjectActions, NuGet.ProjectManagement.INuGetProjectContext nuGetProjectContext, System.Threading.CancellationToken token) [0x00c45] in <7a2d2afbbb674cd48052281699c39e01>:0 
  at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync (NuGet.ProjectManagement.NuGetProject nuGetProject, System.Collections.Generic.IEnumerable`1[T] nuGetProjectActions, NuGet.ProjectManagement.INuGetProjectContext nuGetProjectContext, NuGet.Protocol.Core.Types.PackageDownloadContext downloadContext, System.Threading.CancellationToken token) [0x00121] in <7a2d2afbbb674cd48052281699c39e01>:0 
  at NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync (NuGet.ProjectManagement.NuGetProject nuGetProject, NuGet.Packaging.Core.PackageIdentity packageIdentity, NuGet.PackageManagement.ResolutionContext resolutionContext, NuGet.ProjectManagement.INuGetProjectContext nuGetProjectContext, NuGet.Protocol.Core.Types.PackageDownloadContext downloadContext, System.Collections.Generic.IEnumerable`1[T] primarySources, System.Collections.Generic.IEnumerable`1[T] secondarySources, System.Threading.CancellationToken token) [0x00121] in <7a2d2afbbb674cd48052281699c39e01>:0 
  at NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync (NuGet.ProjectManagement.NuGetProject nuGetProject, NuGet.Packaging.Core.PackageIdentity packageIdentity, NuGet.PackageManagement.ResolutionContext resolutionContext, NuGet.ProjectManagement.INuGetProjectContext nuGetProjectContext, System.Collections.Generic.IEnumerable`1[T] primarySources, System.Collections.Generic.IEnumerable`1[T] secondarySources, System.Threading.CancellationToken token) [0x000d3] in <7a2d2afbbb674cd48052281699c39e01>:0 
  at JetBrains.ProjectModel.NuGet.Operations.NuGetInstallOperation+<>c__DisplayClass5_0.<InstallAsync>b__0 (NuGet.ProjectManagement.NuGetProject nuGetProject, System.Threading.CancellationToken token) [0x000a5] in <2fab7ba8ef23440da9b50bb9da2e1461>:0 
  at JetBrains.ProjectModel.NuGet.Operations.NuGetInstallOperation.InstallInternal (JetBrains.ProjectModel.IProject project, System.String packageId, System.String packgeUserStr, JetBrains.ProjectModel.NuGet.Configs.NuGetFeedContext feedContext, System.Int32 nestedLevel, JetBrains.ProjectModel.NuGet.Logging.NuGetNotificationMode mode, JetBrains.ProjectModel.NuGet.Operations.NuGetOperationReporter reporter, System.Func`3[T1,T2,TResult] nativeInstall) [0x003e6] in <2fab7ba8ef23440da9b50bb9da2e1461>:0 

@ Installing Microsoft.EntityFrameworkCore.SqlServer in SaflyAndSons finished (9.764 sec)
[Notification][Install] Install failed (project: SaflyAndSons, package: Microsoft.EntityFrameworkCore.SqlServer v3.0.0-preview5.19227.1)
Package restore failed. Rolling back package changes for 'SaflyAndSons'.`


### Further technical details
EF Core version: 3.0 preview 5
Database Provider: Microsoft.EntityFrameworkCore.SqlServer preview 5
Operating system: mac
IDE: rider 2019.1

**Comment by ajcvickers** [comment] 2019-05-28 16:12
@silverf1re Can you post a small, runnable project/solution that has this issue so we can take a look?

**Comment by ajcvickers** [comment] 2019-06-06 16:09
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:22 UTC
Labels: closed-could-not-reproduce, customer-reported
