### ISSUE TITLE
Execute filtering for properties with conversions in DB

### ISSUE THREAD

**Issue by kskalski** [dotnet/efcore#15646] opened 2019-05-07 11:53 UTC
I have property that uses custom type translated to datetime column in DB. I can map it properly using ``HasConversion``, but trying to use that property in ``Where`` clause requires execution to be done locally.

I think it should be possible to support remote execution in that case: convert the value that is used in filter (e.g. on the other side of comparison with property) by the same conversion function as defined for property itself and after translating it to DB literal send for execution in DB.

```
// conversion definition:
 modelBuilder.Entity<Models.Fountain>()
  .Property(m => m.LastRun)
  .HasConversion(v => v.ToDateTimeOffset(), v => GPW.Timestamp.FromDateTimeOffset(v));

// filtering query
    var recent_fountain_run = db.Fountains
            .Where(f => f.LastRun > GPW.Timestamp.FromDateTime(DateTime.UtcNow.Subtract(TimeSpan.FromDays(2))))
            .Select(f => Tuple.Create(f.Id, f.LastRun)).FirstOrDefault();
```

causes:

```
Unhandled Exception: System.InvalidOperationException: Error generated for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'where ([f].LastRun > FromDateTime(DateTime.UtcNow.Subtract(2.00:00
:00)))' could not be translated and will be evaluated locally.'. This exception can be suppressed or logged by passing event ID 'RelationalEventId.QueryClientEvaluationWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfigurin
g' or 'AddDbContext'.
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, TParam arg)
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.QueryClientEvaluationWarning(IDiagnosticsLogger`1 diagnostics, QueryModel queryModel, Object queryModelElement)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at ProtoGardenEF.Program.SearchDb(String[] args) in D:\rep\snippets\git\ProtoGardenEF\ProtoGardenEF\Program.cs:line 56
   at ProtoGardenEF.Program.Main(String[] args) in D:\rep\snippets\git\ProtoGardenEF\ProtoGardenEF\Program.cs:line 67
```

(it works fine when I materialize the collection before filtering)

### Steps to reproduce
The full code exercising this case is in
https://github.com/kskalski/snippets/tree/master/ProtoGardenEF

run with
```
dotnet.exe run -p ProtoGardenEF timestamp_compare
```

### Further technical details
EF Core version: 3.0.0-preview5.19227.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite

**Comment by smitpatel** [comment] 2019-05-07 15:36
`DateTime.UtcNow` is server evaluated since client and server could be in different timezone. Which requires us to translate `GPW.Timestamp.FromDateTime(DateTime.UtcNow.Subtract(TimeSpan.FromDays(2))` to server. We do not know how to translate that to server hence client eval. (FromDateTime being opaque client function).

Few things
1. You can extract out that part in a variable if you do not care about DateTime.UtcNow being client eval'd when query is run and then it will translate to server. Also for comparison we do infer value converters so you can remove FromDateTime because we would apply that from other side directly before sending parameter to server.
2. SQLite has limited support about DateTimeOffset because it is stored as text. You could run into more client eval if operation on DateTimeOffset (or even DateTime) is not performed correctly by server.

**Comment by kskalski** [comment] 2019-05-07 16:16
Hm, when I tried to extract date into variable:
```
          var now = GPW.Timestamp.FromDateTime(DateTime.UtcNow.Subtract(TimeSpan.FromDays(2)));
          var recent_fountain_run = db.Fountains
            .Where(f => f.LastRun > now)
            .Select(f => Tuple.Create(f.Id, f.LastRun)).FirstOrDefault();
```
then I get similar exception
```
System.InvalidOperationException: „Error generated for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'where ([f].LastRun > __now_0)' could not be translated and will be evaluated locally.'
```

As for other points:
- it's true DateTime will cause time-zone troubles, actually the conversion is using DateTimeOffet and this is what I should have used in the code. However it still doesn't work then(``The LINQ expression 'where ([f].LastRun > FromDateTimeOffset(DateTimeOffset.UtcNow.Subtract(2.00:00:00)))' could not be translated`` even though I suppose DateTimeOffset is translatable to server by the criteria you mentioned (unless the other issue is about the exact time being used: client vs server, that is at stake here)
- Sqlite in general supports DATE type, but I just checked that the table generated by EF in the above mapping is indeed using TEXT type. This is indeed unfortunate, any reason this is the case? Does it apply to other data-base providers (I originally stumbled upon the problem in Postgres)?

**Comment by kskalski** [comment] 2019-05-07 16:22
- well, I can't skip ``FromDateTime`` call, because then the code doesn't really compile due to type-conflict, i.e. ``.Where(f => f.LastRun > DateTime.UtcNow.Subtract(TimeSpan.FromDays(2)))`` is basically comparing property of type Timestamp with value of type DateTime, whose translation to Timestamp (or Timestamp's translation to DateTime) is known to EF, but not to C# compiler

**Comment by smitpatel** [comment] 2019-05-07 17:42
> Sqlite in general supports DATE type, but I just checked that the table generated by EF in the above mapping is indeed using TEXT type. This is indeed unfortunate, any reason this is the case? Does it apply to other data-base providers (I originally stumbled upon the problem in Postgres)?

@bricelam

**Comment by smitpatel** [comment] 2019-05-07 17:48
`TimeStamp` is not something supported type. Query pipeline in 2.2 is not robust enough to figure out how value converter in all cases. All that is improving in 3.0 but if you put `FromDateTimeOffset` in where clause it is not going to translate since we don't know the conversion.

**Comment by kskalski** [comment] 2019-05-07 19:33
Yes, ``Timestamp`` is not a built-in supported type, however note that it is the type of a property that has defined type conversion to ``DateTimeOffset``:
```
// PropertyTypeBuilder<Timestamp>.HasConversion<DateTime>
 .HasConversion(v => v.ToDateTimeOffset(), v => GPW.Timestamp.FromDateTimeOffset(v));
```

I'm using 3.0-preview5, which apparently doesn't support this kind of conversion-detection, I'm looking forward to having this working before 3.0 final version ships.

**Comment by smitpatel** [comment] 2019-05-07 19:36
`DateTimeOffset` does not allow comparison on server side in Sqlite.

**Comment by kskalski** [comment] 2019-05-07 19:59
Looks like postgres provider uses `` timestamp with time zone`` type for ``DateTimeOffset``, yet I have similar problem there (actually even == operator forces client evaluation), though that is not surprising, since I guess the LINQ=>SQL conversion is provider independent (isn't it?).

A valid question remains why sqlite won't use DATE time for ``DateTimeOffset``, which by definition can be only in one timezone (UTC), so there is no possibility of mixing up time-zones.

**Comment by kskalski** [comment] 2019-05-07 20:17
To be precise, Sqlite itself actually supports comparisons and filtering automatically even if the storage type for dates is TEXT. I suppose the choice of TEXT is due to precision that alternatives provide (INTEGER is rounded up to seconds - unix epoch time and REAL is inherently prone to floating-point representation limitatons...). Maybe there should be a way to influence the choice of representation, that is a separate discussion.

**Comment by smitpatel** [comment] 2019-05-07 20:20
There is no `DATE` on SQLite storage. See https://www.sqlite.org/datatype3.html
SQLite supports whatever you want to do but comparison operation can give incorrect results since dates are stored as text.

**Comment by kskalski** [comment] 2019-05-07 20:34
True, there is no "native" DATE type, though you can actually create table with a column of type DATE (see the table under "Affinity Name Examples"), but that is just aliased to NUMERIC.

However, I am surprised that it would actually return incorrect results when used for comparison. I'm executing queries like ``select * from Fountains where LastRun > datetime('now', '-10 hour');`` on the Db created by above example project and it returns correct results. It is my understanding of the documentation that when the query operates on dates (e.g. values obtained from ``datetime`` function, which I suppose would be the way to translate ``DateTimeOffset`` values to SQL literals) then whatever is the representation of values in certain column, they are converted to datetime and compared as they should. Not sure what would happen if we started comparing two columns with different representation, e.g. ``f.LastRun > f.FirstRun``.

**Comment by markusbrueckner** [comment] 2019-05-09 07:58
Just encountered the same error: I have (well, had) a NodeTime LocalDate field in my model and tried to query using `entity.Day == someDay`, where both `entity.Day` and `someDay` are `LocalDate?`. An appropriate converion to `DateTime?` exists, yet still the query builder does not filter by day in the database. When changing `entity.Day` to `DateTime?`, and doing th conversion of `someDay` by hand outside the query expression, everything works as expected.

I'm currently on EF Core 2.1.4. Is there any chance, that the query builder will respect my conversions in 3.0?

**Comment by smitpatel** [comment] 2019-05-09 16:46
Duplicate of #12045

**Closed** 2022-10-16 14:20 UTC
Labels: closed-duplicate, customer-reported
