### ISSUE TITLE
Right approach for disabling auto-increment in EF Core 2.0

### ISSUE THREAD

**Issue by alktly** [dotnet/efcore#9463] opened 2017-08-18 09:59 UTC
Hello all,

I have been trying to disable auto-increment feature on EF Core 2.0 for an Id column in my OnModelCreating() method by trying different approaches such as;
```c#
modelBuilder.Entity<LD.Licenses.RelatedProduct>()
                   .Property(c => c.Id)
                   .ValueGeneratedNever();
```
and .Annotation("DatabaseGenerated", DatabaseGeneratedOption.None); however, nothing seem to work while I have

```c#
modelBuilder.Entity<LD.Licenses.RelatedProduct>()
                   .HasKey(c => c.Id);
```
property in my OnModelCreating() method.

At the end, I got it working with following setup with no HasKey included,

```c#
modelBuilder.Entity<LD.Licenses.RelatedProduct>()
                   .Property(c => c.Id)
                   .ValueGeneratedNever()
                   .HasAnnotation("DatabaseGenerated", DatabaseGeneratedOption.None);
```

So, my question here, is this an expected behavior or some kind of bug? Why EF does not let me set Id column as key but modify its properties such as auto-increment?

I would appreciate your thoughts!

### Further technical details
EF Core version: netcoreapp2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
IDE: Visual Studio 2017

**Comment by alktly** [comment] 2017-08-18 14:11
Just an update on this. 

It turns out it is a flaw on many to many relationship situation. 

I had tables such as License, Products and ProductLicenses. These are two entities with many to many relationship and a shared table which is called ProductLicenses. 
In OnModelCreating() table, I have placed ProductLicense properties before Product properties which caused no affect for Product properties as ProductLicense depends on it. 
Here problem is that migration runs without any error but cause these properties not to take affect. 

After I put Product properties before ProductLicense all worked just fine.

**Comment by ajcvickers** [comment] 2017-08-18 20:20
@alktly I am not able to reproduce what you are seeing. Can you look at the repro code below and see if there is something I am missing? No matter which combination of calls to HasKey I make in which order, if I also call ValuGeneratedNever, then the property is marked is not marked as ValueGenerated.OnAdd, which means it will not use store generated values.

Also, the annotation for "DatabaseGenerated" is somewhat confusing since I don't believe that EF Core ever generates or uses such an annotation.

```C#
public class RelatedProduct
{
    public int Id { get; set; }
}

public class TestContext : DbContext
{
    public DbSet<RelatedProduct> Products { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(
            @"Server=(localdb)\mssqllocaldb;Database=Test;Trusted_Connection=True;ConnectRetryCount=0");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<RelatedProduct>()
            .HasKey(c => c.Id);

        modelBuilder.Entity<RelatedProduct>()
            .Property(c => c.Id)
            .ValueGeneratedNever();
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new TestContext())
        {
            var model = context.Model; // Look at this model to see if has OnAdd or not.
        }
    }
}
```

**Comment by ajcvickers** [comment] 2017-08-25 18:09
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:16 UTC
Labels: closed-could-not-reproduce
