### ISSUE TITLE
ReferenceOwnershipBuilder HasDiscriminator

### ISSUE THREAD

**Issue by chris-stormideas** [dotnet/efcore#14877] opened 2019-02-28 17:03 UTC
I am trying to configure an owned type with inheritance, the domain model being similar to this:

```c#
public class TimeZone : FullAuditedAggregateRoot<Guid>
  {
    public virtual string Title { get; set; }
    public virtual string TimeZoneInfoId { get; set; }
    public virtual bool RequiresProvider { get; set; }
    public virtual int SortOrder { get; set; }

    public virtual FeedSetting Feed { get; set; }
}

public abstract class FeedSetting : Entity<Guid>
  {
    public static FeedSetting Empty { get; } = new DirectFeed(Feed.EST);

    protected FeedSetting()
    {
    }

    public abstract Feed GetFeed(TimeZone timezone, Provider provider);
  }
  
  public class ProviderFeedSetting : FeedSetting
  {
    public override Feed GetFeed(TimeZone timezone, Provider provider)
    {
      if (timezone.RequiresProvider && provider != null)
      {
        return provider.Feed;
      }

      return Empty.GetFeed(timezone, provider);
    }
  }

  public class DirectFeedSetting : FeedSetting
  {   
    public virtual Feed Feed { get; protected set; } = Feed.EST;

    protected DirectFeedSetting() : base()
    {
    }

    public DirectFeedSetting(Feed feed)
    {
      Feed = feed;
    }
    
    public override Feed GetFeed(TimeZone timezone, Provider provider)
    {
      return Feed;
    }
  }
```

```
Exception message: 'ReferenceOwnershipBuilder' does not contain a definition for 'HasDiscriminator' and the best extension method overload 'RelationalEntityTypeBuilderExtensions.HasDiscriminator<string>(EntityTypeBuilder, string)' requires a receiver of type 'EntityTypeBuilder'
16>Migrations/20190228155115_UpdateDateTimeOffsetToBeNullable.Designer.cs(1265,29): Error CS1929 : 'ReferenceOwnershipBuilder' does not contain a definition for 'HasDiscriminator' and the best extension method overload 'RelationalEntityTypeBuilderExtensions.HasDiscriminator<string>(EntityTypeBuilder, string)' requires a receiver of type 'EntityTypeBuilder'
Stack trace: None
```

### Steps to reproduce

```c#
protected override void OnModelCreating(ModelBuilder builder)
    {
      base.OnModelCreating(builder);
      
      builder.Entity<TimeZone>().OwnsOne(x => x.Feed)
          .OnDelete(DeleteBehavior.Cascade);

      builder.Entity<DirectFeedSetting>();
      builder.Entity<ProviderFeedSetting>();
};
    }
```

### Further technical details
Calling `.Owned` instead of `.Entity` for the 2 sub-classes causes the base type to not be picked up, and throws an error when generating migrations.  Mapping FeedSetting to its own table will also throw the same compilation problem

EF Core version: 2.2.0-rtm-35687
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Ubuntu 16.10
IDE: Visual Studio Code 1.31.1/Rider 2018.3

May be similar to https://github.com/aspnet/EntityFrameworkCore/issues/13945 and https://github.com/aspnet/EntityFrameworkCore/issues/9148, however, would like to be able to do this.  We have currently added in a custom extension method to allow it compile, code works as expected when running.

**Comment by chris-stormideas** [comment] 2019-02-28 17:06
Actually, this might be covered by https://github.com/aspnet/EntityFrameworkCore/issues/9630, didn't spot this before I raised this

**Comment by ajcvickers** [comment] 2019-02-28 21:16
Duplicate of #9630

**Closed** 2022-10-16 13:54 UTC
Labels: customer-reported
