### ISSUE TITLE
Expose StateManager.TryGetEntry in DbContext.ChangeTracker

### ISSUE THREAD

**Issue by jamezamm** [dotnet/efcore#33003] opened 2024-02-05 06:09 UTC
From **DbContext.ChangeTracker**, the only way to find a tracked entity by its primary key is to iterate over ChangeTracker.Entries(). 

Since this is not efficient, I propose exposing **StateManager.TryGetEntry** in DbContext.ChangeTracker (Ex: _ChangeTracker.FindEntry_). DbSet<T>().Find() already employs this method to locate a tracked entity by key.

Hopefully this won't be too much effort because StateManager is already utilized in the ChangeTracker class, like StateManager.Entries().

**Comment by ErikEJ** [comment] 2024-02-05 06:35
Is that not already implemented? 
https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#lookup-tracked-entities-by-primary-alternate-or-foreign-key

**Comment by jamezamm** [comment] 2024-02-05 06:50
Since a bug (which should be fixed by 8.0.2) is preventing me from switching to EF8, I did not realise this had been implemented on DbSet().Local.

Has this been implemented on DbContext.ChangeTracker?

**Comment by ajcvickers** [comment] 2024-02-05 09:23
Duplicate of #29685

**Comment by jamezamm** [comment] 2024-02-05 09:39
In my case I am working with an object that can be of any type, thus I do not know the specific type at design time.

Although DbSet().Local.FindEntry is a good feature, I would still have to access it via reflection.

For that reason I suggested to include StateManager.TryGetEntry (as FindEntry) in DbContext.ChangeTracker. 

In my opinion, this is not a duplicate of https://github.com/dotnet/efcore/issues/29685.

**Comment by ajcvickers** [comment] 2024-02-07 10:53
@jamezamm Non-generic access is covered by #21066.

**Closed** 2024-02-14 14:04 UTC
Labels: customer-reported
