### ISSUE TITLE
How to identify RU/s usage for query execution through efcore cosmos

### ISSUE THREAD

**Issue by pavitrag123** [dotnet/efcore#20860] opened 2020-05-06 15:23 UTC
We are facing throughput errors while trying to delete 200 documents in cosmos db using efcore RemoveRange and SaveChangesAsync. Our container throughput is 700. 

Is there any way to identify number of RU's utilized by delete operation of EFCore

Thank you in advance

**Comment by smitpatel** [comment] 2020-05-08 17:43
Duplicate of #17298

**Closed** 2022-10-16 18:23 UTC
Labels: closed-duplicate, customer-reported
