### ISSUE TITLE
FileLoadException  with Microsoft.Windows.Comparability

### ISSUE THREAD

**Issue by Cityonhill93** [dotnet/efcore#12120] opened 2018-05-23 17:37 UTC
I am attempting to run the database update comand (dotnet ef database update -c MyContext). When I do so, I get a FileLoadException for System.Data.SqlClient version 4.2.0.2.

What is causing this is that we have the .Net Standard Windows Comparability pack (Microsoft.Windows.Comparability) installed, which has a dependency on version 4.5.0-rc1 of  System.Data.SqlClient.

If I add an app.config with a binding redirect, I can get the command to run successfully, but my understanding is that I should not need to. It should just go to the newer version (4.5.0-rc1).

Is it possible to get this fixed? Or am I stuck with the binding redirect until the versions match up?

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
**Exception message:**
System.IO.FileLoadException: Could not load file or assembly 'System.Data.SqlClient, Version=4.2.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
**Stack trace:**
File name: 'System.Data.SqlClient, Version=4.2.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.MigrateUsingConnection(IDiagnosticsLogger`1 diagnostics, IMigrator migrator, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Steps to reproduce

1. Install EF Core Nuget Package
2. Install Windows Compatibility pack
3. Create Context and Entities
4. Create Migration(s)
5. Run dotnet ef database update -c MyContext

### Further technical details
EF Core version: 2.0.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: VS 2017 Enterprise 15.7.2

**Comment by ajcvickers** [comment] 2018-08-01 21:58
@Cityonhill93 I followed the steps above and didn't run into any errors. Could you please post a runnable project/solution that demonstrates the behavior you are seeing?

**Comment by ajcvickers** [comment] 2018-08-08 17:34
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:26 UTC
Labels: closed-could-not-reproduce, customer-reported
