### ISSUE TITLE
Not generating DbContextModelSnapshot

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#28725] opened 2022-08-15 16:47 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Not-generating-DbContextModelSnapshot/10118711)._

---
[severity:I'm unable to use this version]
When adding an initial or new migration, no DbContextModelSnapshot is being generated with .net core mvc
deps:
Microsoft.EntityFrameworkCore.Design 6.0.8
Microsoft.EntityFrameworkCore.Proxies 6.0.8
Microsoft.EntityFrameworkCore.SqlServer 6.0.8
Microsoft.EntityFrameworkCore.Tools 6.0.8

Started today (11AUG22)

I've closed VS22, deleted the .vs folder, and repaired the installation

---
#### Feedback Bot on 8/12/2022, 07:33 AM: 

(private comment, text removed)
#### Feedback Bot on 8/12/2022, 07:37 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2022-08-15 16:48
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-08-22 12:32
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-08-22 12:32 UTC
Labels: customer-reported
