### ISSUE TITLE
Update FindAsync API documentation

### ISSUE THREAD

**Issue by orestiskosko** [dotnet/efcore#19464] opened 2019-12-24 12:28 UTC
I believe that based on https://github.com/aspnet/EntityFrameworkCore/pull/15232 (merged) the documentation for returns of this API (and other mentioned APIs on pull request) should be updated accordingly to `ValueTask`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2453fd15-0659-71a6-6aa7-af264643182b
* Version Independent ID: 60017fe8-0af0-a847-0ddf-0676987c5eaf
* Content: [DbSet&lt;TEntity&gt;.FindAsync Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.findasync?view=efcore-3.1#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbSet`1.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbSet`1.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2020-05-23 22:15
Duplicate of #20733

**Closed** 2022-10-16 18:03 UTC
Labels: customer-reported
