### ISSUE TITLE
Randomly Value cannot be null in production environment

### ISSUE THREAD

**Issue by ufalak** [dotnet/efcore#17431] opened 2019-08-26 17:22 UTC
In the same linq query, in production environment i get the following exception:

> Mensaje:Value cannot be null.
> Parameter name: source
> Source:System.Linq
> InnerException:
> StackTrace:   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)

the linq runing is:

`var turnoDetalleMinutoEntre =
                Turno.TurnoDetalle.Where(td => !td.FechaBaja.HasValue &&
                                               td.MinutoDesde <= MinutoTurno && td.MinutoHasta >= MinutoTurno
                                               && (!minutoInicioFeriado.HasValue ||
                                                   td.MinutoDesde < minutoInicioFeriado.Value ||
                                                   !minutoFinFeriado.HasValue ||
                                                   td.MinutoDesde > minutoFinFeriado.Value)).FirstOrDefault(); `

**Comment by ajcvickers** [comment] 2019-09-06 16:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:38 UTC
Labels: closed-could-not-reproduce, customer-reported
