### ISSUE TITLE
Many-to-Many Fluent API Invalid Column Name

### ISSUE THREAD

**Issue by prasannapattam** [dotnet/efcore#4093] opened 2015-12-15 16:06 UTC
This code was broken from Beta 8 to RC1
This issue seems similar to #1288.
When using ThenInclude invalid column name is generated in the query (Exception: Invalid column name 'IdentityPageEntityPageId'.)

I have three models, IdentityPage, IdentityClaim and IdentityPageClaim. Here are the stripped version of these classes

``` c#
    [Table("IdentityPage")]
    public class IdentityPageEntity
    {
        [Key]
        public int PageId { get; set; }
        public string Text { get; set; }
        public List<IdentityPageClaimEntity> Claims { get; set; }
    }

    [Table("IdentityClaim")]
    public class IdentityClaimEntity
    {
        [Key]
        public int Id { get; set; }
        public string ClaimType { get; set; }
        public string ClaimValue { get; set; }
        public List<IdentityPageClaimEntity> Pages { get; set; }
    }

    [Table("IdentityPageClaim")]
    public class IdentityPageClaimEntity
    {
        [Key]
        public int Id { get; set; }
        public int PageId { get; set; }
        public int ClaimId { get; set; }
        [ForeignKey("ClaimId")]
        public IdentityClaimEntity Claim { get; set; }
        [ForeignKey("PageId")]
        public IdentityPageEntity Page { get; set; }
    }
```

Here is the query using ThenInclude

``` c#
var query = from page in dbContext.IdentityPages.Include(c => c.Claims).ThenInclude(a => a.Claim) select page;
return query.ToList();
```

The above linq generated the following select statement

``` sql
SELECT [i].[Id], [i].[ClaimId], [i].[PageId], [i].[PrimaryClaimInd], [i0].[Id], [i0].[ClaimType], [i0].[ClaimValue], [i0].[Description], 
[i0].[IdentityPageEntityPageId] -- this is the invalid column it generated
FROM [IdentityPageClaim] AS [i]
INNER JOIN (
    SELECT DISTINCT [c].[PageId]
    FROM [IdentityPage] AS [c]
) AS [c] ON [i].[PageId] = [c].[PageId]
INNER JOIN [IdentityClaim] AS [i0] ON [i].[ClaimId] = [i0].[Id]
ORDER BY [c].[PageId]
```

I also tried the below explicit configuration, but still getting the same error

``` c#
builder.Entity<IdentityPageClaimEntity>(entity =>
{
    entity.HasKey(e => e.Id);
    entity.HasOne(d => d.Claim).WithMany(p => p.Pages).HasForeignKey(d => d.ClaimId);
    entity.HasOne(d => d.Page).WithMany(p => p.Claims).HasForeignKey(d => d.PageId);
});

builder.Entity<IdentityPageEntity>(entity =>
{
    entity.HasKey(e => e.PageId);
    entity.HasMany(d => d.Claims).WithOne(p => p.Page).HasForeignKey(d => d.PageId);
});

builder.Entity<IdentityClaimEntity>(entity =>
{
    entity.HasKey(e => e.Id);
    entity.HasMany(d => d.Pages).WithOne(p => p.Claim).HasForeignKey(d => d.ClaimId);
});
```

**Comment by rowanmiller** [comment] 2015-12-17 23:07
Hey,

I'm not able to reproduce this issue on RC1 or our latest builds. Below is the code I was using to test. It successfully creates the expected schema and queries back data (both with the Fluent API configuration and without it).

The `IdentityPageEntityPageId` column (from the `IdentityClaim` table) you are seeing in the SQL statement looks like a shadow state foreign key that EF is introducing because there is a relationship in your model between `IdentityClaimEntity` and `IdentityPageEntity` (but no corresponding foreign key property in the class)... is it possible that your model had a `List<IdentityClaimEntity>` property on the `IdentityPageEntity` class?


```c#
using Microsoft.Data.Entity;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new SampleContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                db.ChangeTracker.TrackGraph(new IdentityPageClaimEntity
                {
                    Claim = new IdentityClaimEntity
                    {
                        ClaimType = "Test",
                        ClaimValue = "Four pieces of toast"
                    },
                    Page = new IdentityPageEntity
                    {
                        Text = "Hello World"
                    }
                }, n => n.Entry.State = EntityState.Added);

                db.SaveChanges();
            }

            using (var db = new SampleContext())
            {
                var query = from page in db.IdentityPages.Include(c => c.Claims).ThenInclude(a => a.Claim) select page;
                query.ToList();
            }
        }
    }

    public class SampleContext : DbContext
    {
        public DbSet<IdentityPageEntity> IdentityPages { get; set; }
        public DbSet<IdentityClaimEntity> IdentityClaims { get; set; }
        public DbSet<IdentityPageClaimEntity> IdentityPageClaims { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder builder)
        {
            builder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Repro;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            //builder.Entity<IdentityPageClaimEntity>(entity =>
            //{
            //    entity.HasKey(e => e.Id);
            //    entity.HasOne(d => d.Claim).WithMany(p => p.Pages).HasForeignKey(d => d.ClaimId);
            //    entity.HasOne(d => d.Page).WithMany(p => p.Claims).HasForeignKey(d => d.PageId);
            //});

            //builder.Entity<IdentityPageEntity>(entity =>
            //{
            //    entity.HasKey(e => e.PageId);
            //    entity.HasMany(d => d.Claims).WithOne(p => p.Page).HasForeignKey(d => d.PageId);
            //});

            //builder.Entity<IdentityClaimEntity>(entity =>
            //{
            //    entity.HasKey(e => e.Id);
            //    entity.HasMany(d => d.Pages).WithOne(p => p.Claim).HasForeignKey(d => d.ClaimId);
            //});
        }
    }

    [Table("IdentityPage")]
    public class IdentityPageEntity
    {
        [Key]
        public int PageId { get; set; }
        public string Text { get; set; }
        public List<IdentityPageClaimEntity> Claims { get; set; }
    }

    [Table("IdentityClaim")]
    public class IdentityClaimEntity
    {
        [Key]
        public int Id { get; set; }
        public string ClaimType { get; set; }
        public string ClaimValue { get; set; }
        public List<IdentityPageClaimEntity> Pages { get; set; }
    }

    [Table("IdentityPageClaim")]
    public class IdentityPageClaimEntity
    {
        [Key]
        public int Id { get; set; }
        public int PageId { get; set; }
        public int ClaimId { get; set; }
        [ForeignKey("ClaimId")]
        public IdentityClaimEntity Claim { get; set; }
        [ForeignKey("PageId")]
        public IdentityPageEntity Page { get; set; }
    }
}
```

~Rowan

**Comment by prasannapattam** [comment] 2015-12-19 06:03
I am unable to reproduce this with a new VS project. But getting this error within my existing project. I checked the nuGet packages (when compared to creating a new project). In my existing project, I removed all my other code, but still getting the same error. I suspect this is something related to project configuration.

**Comment by rowanmiller** [comment] 2015-12-22 19:03
Closing this out as there is not a lot we can do if we have no way to reproduce it. Feel free to re-open if you can provide code/project that demonstrates the issues.

**Comment by HClausing** [comment] 2016-01-29 17:02
There's a similar problem here, I can't find where I'm doing wrong. I'm testing with AdventureWorks DB. I can't relate Product and ProductSubCategory, neighter with <Product>().HasOne and <ProductSubCategory>().HasMany. It Always return a type of System.AggregateException with Invalid Column name.

Attached DbContext and classes files.
![exception](https://cloud.githubusercontent.com/assets/15158923/12682091/ea040304-c698-11e5-9ba2-2abc63d78b15.png)


[Classes.zip](https://github.com/aspnet/EntityFramework/files/110089/Classes.zip)

**Comment by divega** [comment] 2016-01-29 21:25
Reopening so we can look at @HClausing's repro (assuming it is the same issue or related).

**Comment by rowanmiller** [comment] 2016-02-02 18:26
@HClausing can you open a new issue and be sure to include a complete code listing to reproduce the issue you are seeing. 

BTW you may want to look at http://docs.efproject.net/en/latest/modeling/relationships.html to ensure you are configuring the foreign key property/column if it does not match what is discovered by convention.

**Comment by HClausing** [comment] 2016-02-02 18:55
Good afternoon for all.

I was Reading the docs again, and decided do revise all the FK's and PK's of classes, and I could see that the Property ProductCategoryID on Production.ProductSubCategory table is not PK. That's just it wrong. I'm really sorry.

Thanks for the patience and attention. The new EF is really good.

**Closed** 2022-10-16 09:20 UTC
