### ISSUE TITLE
Lazy Loading Delegate now causes duplicate property error

### ISSUE THREAD

**Issue by kramffud** [dotnet/efcore#17703] opened 2019-09-07 13:06 UTC
Something has changed.  I have been able to inject the ILazyLoader.Load method as a delegate (as described above) for the past year or so and it has worked beautifully.  Now, all of a sudden, this causes "The service property 'LazyLoader' of type 'Action&lt;object, string&gt;' cannot be added to the entity type 'MyPoco' because there is another property of the same type. Ignore one of the properties using the NotMappedAttribute or 'EntityTypeBuilder.Ignore' in 'OnModelCreating'."  Is .NET Core now injecting the delegate w/o letting me know?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data#feedback)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by AndriySvyryd** [comment] 2019-09-20 22:32
@kramffud I wasn't able to repro this issue with the code on that page using EF Core 3.0
Please create a small runnable project that shows the exception.

**Comment by smitpatel** [comment] 2019-09-27 21:27
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:40 UTC
Labels: closed-could-not-reproduce, customer-reported
