### ISSUE TITLE
Cosmos DB: Is there ANY way to currently support IDictionary<string, object>

### ISSUE THREAD

**Issue by DaleyKD** [dotnet/efcore#21265] opened 2020-06-15 14:55 UTC
I've been working all week trying to get EF Core 3.1 Cosmos DB provider to even somewhat work with an `IDictionary<string, object>`. So far, nothing is working ideally.

Is there a way to use a Value Converter? A Backing Field? Anything like that?

This limitation is making it so that I can't use EF Core for my Cosmos project.

**Comment by ajcvickers** [comment] 2020-06-15 18:54
@DaleyKD Can you provide more details on where the dictionary appears in the C# model and what the expected mapping to JSON would be?

**Comment by DaleyKD** [comment] 2020-06-15 19:40
Ideally:
```csharp
public class Foo
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [JsonProperty("id")]
    public Guid ID { get; set; }

    [Required]
    [JsonProperty("partKey")]
    public string PartitionKey { get; set; } = string.Empty;

    [JsonProperty("metaDict")]
    public IDictionary<string, object> MetadataDictionary { get; set; } = new Dictionary<string, object>();

    [JsonProperty("url")]
    public string Url { get; set; }
}
```

And the results would look like what CosmosClient writes:
```json
{
    "metaDict": {
        "@odata.etag": "\"982b588c-a06b-4f2e-b6dd-9732bdbbf143,20\"",
        "Title": "A Compliance Title",
        "GovernmentIDNumber": "8807",
        "Salary": 123456.78,
        "Location": "1600 Pennsylvania Ave NW\r\nWashington, DC 20500",
        "ContentType": "Document",
        "Created": "2020-05-28T17:03:48Z",
        "AuthorLookupId": "1073741822",
        "Modified": "2020-06-15T19:30:57Z",
        "EditorLookupId": "1073741822",
        "DocIcon": "png",
        "FileSizeDisplay": "14622",
        "ItemChildCount": "0",
        "FolderChildCount": "0",
        "_ComplianceFlags": "",
        "_ComplianceTag": "",
        "_ComplianceTagWrittenTime": "",
        "_ComplianceTagUserId": "",
        "_CommentCount": "",
        "_LikeCount": "",
        "_DisplayName": "",
        "AppAuthorLookupId": "7",
        "AppEditorLookupId": "7",
        "Edit": "0",
        "_UIVersionString": "19.0",
        "ParentVersionStringLookupId": "6",
        "ParentLeafNameLookupId": "6"
    },
    "url": "https://google.com/test.png",
    "id": "dac9bcfa-1c68-498f-95bd-4f7443752a05",
    "partKey": "202006",
    "Discriminator": "DcsItemEntry",
    "_rid": "hwE9AKmqH1oBAAAAAAAAAA==",
    "_self": "dbs/hwE9AA==/colls/hwE9AKmqH1o=/docs/hwE9AKmqH1oBAAAAAAAAAA==/",
    "_etag": "\"00000000-0000-0000-434b-7f41007b01d6\"",
    "_attachments": "attachments/",
    "_ts": 1592249459
}
```

**Comment by AndriySvyryd** [comment] 2020-06-16 18:53
Duplicate of https://github.com/dotnet/efcore/issues/9914

**Comment by DaleyKD** [comment] 2020-06-16 20:30
Maybe I'm dense, but closing this out doesn't answer my question.  Is it even possible to do this in EF Core 3.1 **at all**?

**Comment by AndriySvyryd** [comment] 2020-06-16 20:34
@DaleyKD No, there's no way of doing this in 3.1. You can try accessing the JSON directly as a workaround https://docs.microsoft.com/en-us/ef/core/providers/cosmos/unstructured-data

**Comment by DaleyKD** [comment] 2020-06-16 20:44
@AndriySvyryd : Thank you!  That's all I needed so I didn't go insane. :)

**Comment by DaleyKD** [comment] 2021-06-16 18:52
@AndriySvyryd - With EF Core 5.0 (or maybe even upcoming 6), is this possible yet?

Currently, I can't use EF Core with Cosmos because of this limitation.  I still have to use the `CosmosClient`.  ValueConverters?  Anything?

_(I'm a little embarrassed by what I currently have as my CosmosDbService because it's a nasty mix of EF Core and CosmosClient while I want to convert to full EF Core.)_

**Comment by AndriySvyryd** [comment] 2021-06-16 22:57
In EF Core 5 you can map them as owned shared type entity types:

```
modelBuilder.Entity<Foo>().OwnsOne(
    "FooMetadata",
    o => o.MetadataDictionary,
    d =>
    {
        d.Property<string>("Title");
        d.Property<string>("GovernmentIDNumber");
        ...
    });
```

**Comment by DaleyKD** [comment] 2021-06-17 00:19
If my `MetadataDictionary` is always dynamic, and I'm never fully sure what's in it, how can I possibly do this?  It's a property bag of Metadata.  It may or may not have a Title, it may or may not have "Grandma's Favorite Casserole."

**Comment by AndriySvyryd** [comment] 2021-06-17 00:42
@DaleyKD That's tracked by https://github.com/dotnet/efcore/issues/2282 and specifically for Cosmos by https://github.com/dotnet/efcore/issues/14762 and possibly https://github.com/dotnet/efcore/issues/20584

**Comment by DaleyKD** [comment] 2021-06-17 00:45
Perfect.  Thank you!

**Closed** 2022-10-16 18:29 UTC
Labels: closed-duplicate, customer-reported
