### ISSUE TITLE
Microsoft.EntityFrameworkCore.SqlServer 5.0.0 is not compatible with Desktop Bridge

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/efcore#23678] opened 2020-12-14 12:25 UTC
Context: https://github.com/dotnet/SqlClient/issues/612#issuecomment-744403258

It's fixed by a later released **minor** version.

Is bumping a dependency's **minor** version when doing **patch** version update acceptable? If no, the workaround should be properly documented, or ask the dependency to cherry-pick a new patch release.

**Comment by roji** [comment] 2020-12-14 12:30
Duplicate of #23453

**Comment by roji** [comment] 2020-12-14 12:31
@huoyaoyuan as mentioned in https://github.com/dotnet/SqlClient/issues/612, it's fine for you to add a reference to Microsoft.Data.SqlClient 2.1.0. #23453 tracks possibly changing EF Core to depend on 2.1.0 in a 5.0 patch version.

**Closed** 2022-10-16 19:15 UTC
Labels: customer-reported
