### ISSUE TITLE
group join just dont work every time it say unable to translate 

### ISSUE THREAD

**Issue by eduboardio** [dotnet/efcore#27710] opened 2022-03-26 09:15 UTC
## I tried with so many ways but group join just don't work every time it say unable to translate 

Remember:

* I checked the documentation and tried copying the same code still it never works

```cs
 var leave = await (from post in _dbContext.posts
                               join teacher in _dbContext.teachers on post.teacherId equals teacher.id
                               join attachment in _dbContext.attachments on new { id = post.id, type = (byte)1 } equals new { id = attachment.id, type = attachment.referenceType } into attachmentGroup
                               join ack in _dbContext.postAcknowleges on new { id = post.id, type = (byte)1 } equals new { id = ack.reference, type = ack.referenceType } into ackgroup
                               join cmt in _dbContext.postComments on new { id = post.id, type = (byte)AttachmentReferenceType.post } equals new { id = cmt.referenceID, type = cmt.referenceType } into cmtGroup
                               select new Post_Ou1()
                               {
                                   id = post.id,
                                   description = post.description,
                                   title = post.title,
                                   Url = post.Url,
                                   isVisible = post.isVisible,
                                   Acknowledgementcount = ackgroup.Count(),
                                   teacher = new Teacher_Ou1()
                                   {
                                       firstName = teacher.firstName,
                                       profilePitcherUrl = teacher.profilePitcherUrl,
                                       email = teacher.email,
                                       id = teacher.id,
                                       lastName = teacher.lastName,
                                       middleName = teacher.middleName,
                                       dateOfBirth = teacher.dateOfBirth,
                                   },
                                   commentCount = cmtGroup.Count(),
                                   validTillDate = post.validTillDate,
                                   UpdatedOn = post.UpdatedOn,
                                   attachments = attachmentGroup.ToList(),
                                   CreatedOn = post.CreatedOn
                               }).AsNoTracking().FirstOrDefaultAsync(x => x.id == id);
```

```C#
Console.WriteLine("Hello, World!");
```

### Include verbose output

 "error": "The LINQ expression 'DbSet<Post>()\r\n    .Join(\r\n        inner: DbSet<Teacher>(), \r\n        outerKeySelector: post => post.teacherId, \r\n        innerKeySelector: teacher => teacher.id, \r\n        resultSelector: (post, teacher) => new { \r\n            post = post, \r\n            teacher = teacher\r\n         })\r\n    .GroupJoin(\r\n        inner: DbSet<Attachment>(), \r\n        outerKeySelector: <>h__TransparentIdentifier0 => new { \r\n            id = <>h__TransparentIdentifier0.post.id, \r\n            type = 1\r\n         }, \r\n        innerKeySelector: attachment => new { \r\n            id = attachment.id, \r\n            type = attachment.referenceType\r\n         }, \r\n        resultSelector: (<>h__TransparentIdentifier0, attachmentGroup) => new Post_Ou1{ \r\n            id = <>h__TransparentIdentifier0.post.id, \r\n            description = <>h__TransparentIdentifier0.post.description, \r\n            title = <>h__TransparentIdentifier0.post.title, \r\n            Url = <>h__TransparentIdentifier0.post.Url, \r\n            isVisible = <>h__TransparentIdentifier0.post.isVisible, \r\n            teacher = new Teacher_Ou1{ \r\n                firstName = <>h__TransparentIdentifier0.teacher.firstName, \r\n                profilePitcherUrl = <>h__TransparentIdentifier0.teacher.profilePitcherUrl, \r\n                email = <>h__TransparentIdentifier0.teacher.email, \r\n                id = <>h__TransparentIdentifier0.teacher.id, \r\n                lastName = <>h__TransparentIdentifier0.teacher.lastName, \r\n                middleName = <>h__TransparentIdentifier0.teacher.middleName, \r\n                dateOfBirth = <>h__TransparentIdentifier0.teacher.dateOfBirth \r\n            }\r\n            , \r\n            validTillDate = <>h__TransparentIdentifier0.post.validTillDate, \r\n            UpdatedOn = <>h__TransparentIdentifier0.post.UpdatedOn, \r\n            attachments = attachmentGroup\r\n                .ToList(), \r\n            CreatedOn = <>h__TransparentIdentifier0.post.CreatedOn \r\n        }\r\n    )' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information."

### Include provider and version information

EF Core version: 6.3
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.3)
Operating system: Window
IDE: (e.g. Visual Studio 2022 )

**Comment by ajcvickers** [comment] 2022-04-04 10:35
@eduboardio Do you know if this worked in EF6? If so, can you post the SQL that it was translated to? Either way, can you post the SQL you expect this to be translated to?

**Comment by ajcvickers** [comment] 2022-04-19 12:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:30 UTC
Labels: closed-could-not-reproduce, customer-reported
