### ISSUE TITLE
Unable to insert entities containing Point or Polygon properties with Null

### ISSUE THREAD

**Issue by Olbrasoft** [dotnet/efcore#13797] opened 2018-10-29 08:23 UTC
public class Entity 
{
  public int Id {get; sets;}
  public IPoint Coordinates{ get; set;}
}

vat entity = new Entity();
Context.Add(entity)  => Throw exception object null reference

comment: In database column coordinates null allowed.

**Comment by ajcvickers** [comment] 2018-10-29 15:46
Duplicate of #13457

**Closed** 2022-10-16 13:38 UTC
Labels: customer-reported
