### ISSUE TITLE
[Microsoft.Data.Sqlite] Duplicated attributes while compiling in VS 2019 Preview

### ISSUE THREAD

**Issue by Matthiee** [dotnet/efcore#15355] opened 2019-04-14 08:07 UTC
I get the following compilation error while trying to build `Microsoft.Data.Sqlite` in latest Visual Studio 2019 Preview on latest master branch. 

``` Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0579	Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute	Microsoft.Data.Sqlite.Core	D:\Source\Repos\EntityFrameworkCore\artifacts\obj\Microsoft.Data.Sqlite.Core\Debug\netstandard2.0\Microsoft.Data.Sqlite.Core.AssemblyInfo.cs	15	Active
```  

Using the `build.cmd` script generates the same error. 

Manually excluding `bin` and `obj` folders from these projects fixed the issue for me. 

Should I open a PR that fixes this?

**Comment by smitpatel** [comment] 2019-04-14 17:44
Duplicate of https://github.com/dotnet/cli/issues/4710

**Closed** 2022-10-16 14:17 UTC
Labels: closed-external, customer-reported
