### ISSUE TITLE
Time out async await bei anmelden 

### ISSUE THREAD

**Issue by naelgithub** [dotnet/efcore#1419] opened 2015-01-16 11:36 UTC

**Comment by Eilon** [comment] 2015-01-16 17:48
Hi, can you please translate to English, as well as add more info on the scenario, what you tried, what errors/results you saw, and what didn't work?

**Comment by rowanmiller** [comment] 2015-01-16 19:35
__EF Team Triage:__ This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving.

Because there is very little information in this report and it's not understandable we are closing the issue. Feel free to re-activate or open a new issue if you are able to provide the required details.

**Closed** 2022-10-16 08:49 UTC
