### ISSUE TITLE
ExecuteDeleteAsync fails when an owned entity exists and the query isn't supported natively (subquery form)

### ISSUE THREAD

**Issue by the-avid-engineer** [dotnet/efcore#29690] opened 2022-11-28 06:21 UTC
## File a bug

I'm running into an unexpected `ArgumentOutOfRangeException` in a library I'm working on. I'm just switching the behavior from loading records in and then deleting them (i.e., `ToListAsync()` then `RemoveRange()` and `SaveChangesAsync()`) to using the new method which should delete everything in one trip to the database (i.e., `ExecuteDeleteAsync` )

### Include your code

Minimal Reproduction: https://github.com/the-avid-engineer/EFCoreBug

It doesn't matter what expression I use, including `.Where(x => true)` - they all throw this exception.

I saw another issue where someone mentions `ArgumentOutOfRangeException` #28137, and they mentioned owned types. I can confirm that this seems related to the `OwnsOne` relationship - the exception is not thrown for `HasOne` nor `OwnsMany`

My package (not this minimal reproduction) uses the Npgsql driver, but the issue persists even if I switch my tests to SQLite, so it doesn't appear to be a driver-specific issue.

### Include stack traces

```
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.GetProjection(ProjectionBindingExpression projectionBindingExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.BindProperty(EntityReferenceExpression entityReferenceExpression, IProperty property)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TryBindMember(Expression source, MemberIdentity member)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TryRewriteEntityEquality(ExpressionType nodeType, Expression left, Expression right, Boolean equalsMethod, Expression& result)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateExpression(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateLambdaExpression(ShapedQueryExpression shapedQueryExpression, LambdaExpression lambdaExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateAny(ShapedQueryExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.TranslateSubquery(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateExpression(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateLambdaExpression(ShapedQueryExpression shapedQueryExpression, LambdaExpression lambdaExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateExecuteDelete(ShapedQueryExpression source)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteDelete[TSource](IQueryable`1 source)
   at Program.<Main>$(String[] args) in C:\Users\theav\Documents\GitHub\EFCoreBug\Program.cs:line 34
```

### Include provider and version information

EF Core version: 7.0.0
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 7.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.4.1

**Comment by the-avid-engineer** [comment] 2022-11-28 17:03
@roji I will work on that ASAP :) I did suspect the dynamic predicate at first, but I am confident that is not the issue because the exception is thrown even if I try to delete everything (i.e., `.Where(x => true)` instead of the target records

**Comment by the-avid-engineer** [comment] 2022-11-29 01:28
@roji Here's the reproduction! https://github.com/the-avid-engineer/EFCoreBug

**Comment by the-avid-engineer** [comment] 2022-11-29 01:37
I can also confirm that it seems to be an issue with `OwnsOne`, the error goes away if the relationship is changed to `OwnsOne`

https://github.com/the-avid-engineer/EFCoreBug/pull/1

**Comment by roji** [comment] 2022-12-03 15:43
Note: repros on Sqlite but does not repro on SQL Server.

Simplified repro:

<details>

```c#
using var dbContext = new MyDbContext();
dbContext.Database.EnsureDeleted();
dbContext.Database.EnsureCreated();

var dbSet = dbContext.Set<SnapshotReference>();

// Throws:
dbSet.Where(snapshotReference => true).ExecuteDelete();

public class MyDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            // .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .UseSqlite("Filename=/tmp/foo.sqlite")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SnapshotReference>(snapshotReferenceBuilder =>
        {
            snapshotReferenceBuilder.ToTable("SnapshotReferences");

            snapshotReferenceBuilder.HasKey(snapshotReference => snapshotReference.Id);

            snapshotReferenceBuilder.HasAlternateKey(snapshotReference => new
            {
                snapshotReference.PointerId,
                snapshotReference.PointerVersionNumber
            });

            snapshotReferenceBuilder.OwnsOne(snapshotReference => snapshotReference.Snapshot,
                snapshotBuilder =>
                {
                    snapshotBuilder.ToTable("Snapshots");

                    snapshotBuilder
                        .HasKey(snapshot => new
                        {
                            snapshot.Id,
                            snapshot.VersionNumber,
                        });
                });
        });
    }
}

public class Snapshot
{
    public Guid Id { get; init; }
    public ulong VersionNumber { get; init; }
}

public class SnapshotReference
{
    public required Guid Id { get; init; }

    public required Guid PointerId { get; init; }

    public required ulong PointerVersionNumber { get; init; }

    public required Snapshot Snapshot { get; set; }
}
```

</details>

**Comment by the-avid-engineer** [comment] 2022-12-03 18:35
Interesting! I'm using Postgres in my tool, and it happens on Postgres too, but Sqlite was easier to write a repro for.

**Comment by dhedey** [comment] 2023-09-19 17:24
I'm also seeing this issue on PostgreSQL on version 7.

This works, but uncommenting either line causes a failure:
```
        var prunedTransactionCount = await dbContext
            .PendingTransactions
            // .OrderBy(pt => pt.LastSubmittedToGatewayTimestamp)
            .Where(expression)
            // .Take(10)
            .ExecuteDeleteAsync(token);
```

Swapping `ExecuteDeleteAsync` for `ToListAsync` also causes a success.

Looks like I'll have to swap this out for a raw SQL query for now.

**Comment by ErikApption** [comment] 2024-01-12 21:26
Been seeing same issue after moving some queries to AutoLoading
```cs
modelBuilder.Entity<Entity>().Navigation(e => e.Element).AutoInclude();
```
This is my workaround with the BulkDelete package
```cs
        public static async Task<int> ExecuteDeleteAsyncIfExists<TSource>(this IQueryable<TSource> source, DbContext db, CancellationToken cancellationToken = default(CancellationToken)) where TSource : class
        {
            var toDelete = await source.ToListAsync();
            if (toDelete.Count > 0)
            {
                await db.BulkDeleteAsync(toDelete);
                return toDelete.Count;
            }
            else
                return 0;
        }
```

**Comment by roji** [comment] 2024-01-15 18:59
Duplicate of #32823

**Comment by roji** [comment] 2024-01-15 18:59
Reopened this again as #32823, will close in favor of that one as there's a detailed analysis/repro there.

**Closed by roji** 2024-01-15 18:59 UTC
Labels: customer-reported
