### ISSUE TITLE
Owned entity (in same table) generates LEFT JOIN

### ISSUE THREAD

**Issue by rayao** [dotnet/efcore#20109] opened 2020-02-29 11:21 UTC
Hi,
This is just a question I need an answer, to make generated SQL more performant.
I have 2 entity types A and B, both owns an entity called "Image", A owns 5 Images, B owns 1.
I configured them the same way using "OwnsOne", but when querying A the generated SQL doesn't contain any "JOIN" clause, and when querying B there's a "LEFT JOIN" for the owned Image.
I don't understand where the difference comes from, as I said I configure the owned entities in an exactly same way.
And from documentation I can't find any clue, I think there must be some simple setting I missed, please kindly give me some help, thanks in advance.
EFCore version 2.2.4

**Comment by rayao** [comment] 2020-02-29 13:38
I did some experiments and found that JOIN query is enforced in either of following 2 cases

- Table per hierarchy. **Even the owned property is in base type**, as long as a descendant entity type is configured, JOIN is enforced in query. I guess this is to simplify SQL generation, in case the owned type is not in base type.
- Composite key. If entity key is configured as 2 or more properties, JOIN is enforced. I have no clue why.

So now my question is "**how (or is it possible) to enforce a flattened query in these 2 cases**"?

**Comment by ajcvickers** [comment] 2020-03-02 22:04
Duplicate of #18299

**Closed** 2022-10-16 18:13 UTC
Labels: closed-duplicate, customer-reported
