### ISSUE TITLE
Better support for ad-hoc queries

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#22448] opened 2020-09-08 17:50 UTC
### Objective
I just spent several hours wrestling with EF Core limitations trying to get the results of a full-text search query.

The main issue is that methods like `FromSqlRaw()` can only return data for types that have been defined as entities. Looking at some pre-EF-Core code, I was able to use `SqlQuery<>()` to return data in any data type. I don't understand why things have become so restrictive.

### Possible Solutions

Below is an extension method I came up with to provide a solution. Why can't EF include something like this for ad-hoc queries? Why is it necessary to define an entity class for simple queries that return data?

    public static async Task<IEnumerable<T>> SqlQuery<T>(this DbConnection dbConnection, string query, params SqlParameter[] parameters) where T : new()
    {
        bool wasClosed = dbConnection.State == ConnectionState.Closed;
        if (wasClosed)
            dbConnection.Open();

        List<T> results = new List<T>();

        using (var cmd = dbConnection.CreateCommand())
        {
            cmd.CommandText = query;
            cmd.CommandType = CommandType.Text;
            foreach (SqlParameter parameter in parameters)
                cmd.Parameters.Add(parameter);

            using var reader = await cmd.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                T item = Activator.CreateInstance<T>();
                for (int i = 0; i < reader.FieldCount; i++)
                {
                    if (!await reader.IsDBNullAsync(i))
                    {
                        PropertyInfo propertyInfo = typeof(T).GetProperty(reader.GetName(i), BindingFlags.Public | BindingFlags.Instance | BindingFlags.IgnoreCase);
                        if (propertyInfo != null && propertyInfo.CanWrite)
                            propertyInfo.SetValue(item, reader.GetValue(i));
                    }
                }
                results.Add(item);
            }
        }

        if (wasClosed)
            dbConnection.Close();

        return results;
    }

**Comment by ajcvickers** [comment] 2020-09-08 17:54
Duplicate of #10753 and #11624 .

**Closed** 2022-10-16 18:39 UTC
Labels: customer-reported
