### ISSUE TITLE
Unable to cast object of type 'System.Int32' to type 'System.Linq.Expressions.LambdaExpression'

### ISSUE THREAD

**Issue by granthoff1107** [dotnet/efcore#10709] opened 2018-01-15 03:56 UTC
I've already looked at this issue https://github.com/aspnet/EntityFrameworkCore/issues/10271,  

I'm aware of the closure issues so I've referenced a variable registered in a singleton.
Yet, I still am getting an error 

> Unable to cast object of type 'System.Int32' to type 'System.Linq.Expressions.LambdaExpression'

Microsoft.EntityFrameworkCore -Version 2.0.1

My code:

```C#
    public class DbAuthorizationOptions
    {
        public ConstraintOptions ConstraintOptions { get; set; } = new ConstraintOptions();
    }

    public class ConstraintOptions
    {
        protected Dictionary<Type, LambdaExpression> queryConstrations = new Dictionary<Type, LambdaExpression>();

        public void SetConstraint<T>(Expression<Func<T, bool>> constraint)
        {
            this.queryConstrations[typeof(T)] = constraint;
        }

        public Expression<Func<T, bool>> GetConstraint<T>()
        {
            return (Expression<Func<T, bool>>)this.queryConstrations[typeof(T)];
        }

        public IEnumerable<KeyValuePair<Type,LambdaExpression>> GetAllConstraints()
        {
            return this.queryConstrations;
        }
    }

    public class ContextAuthorizationOptions : DbAuthorizationOptions<AstootContext>
    {
         
         protected int _userId { get; set; } = 1;

         public ContextAuthorizationOptions(IUserAuthenticationManager authenticationManager)
         {
             ConstraintOptions.SetConstraint<Conversation>(x => x.EmployeeUserId == this._userId);
         }
    }
```
Startup:

```C#
    services.AddSingleton<DbAuthorizationOptions<AstootContext>, ContextAuthorizationOptions>();`
```
Authorized context:

```C#
    protected DbAuthorizationOptions _authorizationOptions;

    public AuthorizedDbContext(DbContextOptions options, DbAuthorizationOptions authorizationOptions)
    : base(options)
     {
         this._authorizationOptions = authorizationOptions;
     }


     protected override void OnModelCreating(ModelBuilder modelBuilder)
     {
        var contraintOptions = this._authorizationOptions.ConstraintOptions;
        foreach (var option in contraintOptions?.GetAllConstraints())
        {
            modelBuilder.Entity(option.Key).HasQueryFilter(option.Value);
        }

        base.OnModelCreating(modelBuilder);
    }
```

**Comment by anpete** [comment] 2018-01-18 21:23
@granthoff1107 Can you post the full stack trace? Thanks.

**Comment by granthoff1107** [comment] 2018-01-19 02:29
I already switched to EntityFramework-Plus for, but 
I'll revert to save you the trouble but can you answer something for me? 

           Why is the QueryFilter Immutable and is it triaged in the next version to dynamically filter? I've been doing a really sketchy work around but I would like to know the potential effects

            foreach (var option in constraintOptions)
            {
                ((EntityType)Model.FindEntityType(option.Type)).QueryFilter = option.Constraint;
            }

>System.InvalidCastException occurred
  HResult=0x80004002
  Message=Unable to cast object of type 'System.Int32' to type 'System.Linq.Expressions.LambdaExpression'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateSetFilterParametersExpressions(ParameterExpression& contextVariableExpression)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at RestEzCore.Extensions.PageExtensions.<ToPage>d__0`1.MoveNext() in C:\source\Astoot\RestEzCore\Extensions\PageExtensions.cs:line 18

**Comment by smitpatel** [comment] 2018-02-08 00:05
Duplicate of #10271

**Comment by granthoff1107** [comment] 2018-02-08 05:44
@smitpatel or @anpete  one of you answer my question before closing this,

Why is the QueryFilter Immutable and is it triaged in the next version to dynamically filter? this seems sketchy to cast the interface, but do you know what would be the effects of this?

foreach (var option in constraintOptions)
{
     ((EntityType)Model.FindEntityType(option.Type)).QueryFilter = option.Constraint;
}

**Comment by anpete** [comment] 2018-02-08 20:15
@granthoff1107 QueryFilter is immutable because the model itself is considered immutable after it has been built. Mutating the query filter in the way you describe wouldn't work because any queries that have already been compiled would use the previous value - queries are compiled and the filter expression is in-lined in the compiled query.

The standard way to affect the behavior of a filter is to capture a context field when defining the filter and then make changes to the value of that field at runtime.

**Closed** 2022-10-16 12:05 UTC
Labels: type-bug, closed-duplicate
