### ISSUE TITLE
Visual Studio could not scaffold Entity Framework controller

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#27774] opened 2022-04-06 10:04 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-could-not-scaffold-Entity-/1689578)._

---
[severity:It bothers me. A fix would be nice]
The following error message could be more explicit about what I should do to fix the issue.

! [image.png] (https://aka.ms/dc/image?name=B136887c8fb224b88968c3e19873d9f9d637825406396925077_20220310-142359-image.png&tid=136887c8fb224b88968c3e19873d9f9d637825406396925077)

This error wants me to configure dependency injection so that the ConcertDataContext can be constructed.

Also, a link explaining why scaffolding needs a valid connection string would be appreciated. I'm using code first entities and I'm not sure what the database is going to describe that my code-first DbContext does not.

---
#### Feedback Bot on 3/11/2022, 02:20 AM: 

(private comment, text removed)
#### Feedback Bot on 3/14/2022, 03:24 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2022-04-06 10:05
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-04-19 12:26
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:30 UTC
Labels: closed-could-not-reproduce, customer-reported
