### ISSUE TITLE
Failed to load 6.0.0-preview.3.21201.4/libhostfxr.dylib, no suitable image found. Mac M1

### ISSUE THREAD

**Issue by johnseed** [dotnet/efcore#24971] opened 2021-05-25 03:54 UTC
## File a bug

Remember:

* Please check that the [documentation](https://docs.microsoft.com/ef/) does not explain the behavior you are seeing.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your bug has not already been filed.

### Include your code

To fix any bug we must first reproduce it. To make this possible, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

It is often impossible for us to reproduce a bug when working with only code snippets since we have to guess at the missing code. 

Use triple-tick code fences for any posted code. 

```bash
dotnet ef dbcontext scaffold  "ConnectionString" MySql.Data.EntityFrameworkCore -o Model -f
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. 

```
Failed to load /usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib, error: dlopen(/usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib, 1): no suitable image found.  Did find:
        /usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib: mach-o, but wrong architecture
        /usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib: mach-o, but wrong architecture
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366
```

### Include verbose output

Please include `--verbose` output when filing bugs about the `dotnet ef` or Package Manager Console tools.

Use triple-tick fences for tool output. 

```
Failed to load /usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib, error: dlopen(/usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib, 1): no suitable image found.  Did find:
        /usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib: mach-o, but wrong architecture
        /usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib: mach-o, but wrong architecture
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366
```

### Include provider and version information

EF Core version: 5.0.6
Database provider: MySql.Data.EntityFrameworkCore
Target framework: 6.0.100-preview.3.21202.5
Operating system: macOS Big Sur 11.3.1 M1
IDE: console

**Comment by ajcvickers** [comment] 2021-05-25 22:41
@johnseed Looks like you are trying to use EF Core 6.0 preview 3 with an EF Core 5.0 database provider for "MySql.Data.EntityFrameworkCore". I would not expect this to work. In general, EF Core requires a database provider updated for the release you are using.

**Comment by johnseed** [comment] 2021-05-26 07:11
> @johnseed Looks like you are trying to use EF Core 6.0 preview 3 with an EF Core 5.0 database provider for "MySql.Data.EntityFrameworkCore". I would not expect this to work. In general, EF Core requires a database provider updated for the release you are using.

Thanks for pointing out, I looked up a little, MySql.Data.EntityFrameworkCore is deprecated, the new provider is MySql.EntityFrameworkCore, and third party provider is Pomelo.EntityFrameworkCore.MySql.

First, I deleted the dotnet sdk and runtime,
```bash
sudo rm -rf /usr/local/share/dotnet
```
Then reinstalled Visual Studio for Mac, rollback to dotnet 5.0.

With dotnet 5, All 3 providers work fine.
```bash
John@Johns-Mac % dotnet ef dbcontext scaffold  "ConnectionString" Pomelo.EntityFrameworkCore.MySql -o Model --schema a --schema b -f
Build started...
Build succeeded.
The Entity Framework tools version '5.0.6' is older than that of the runtime '6.0.0-preview.4.21253.1'. Update the tools for the latest features and bug fixes.
To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
John@Johns-Mac % 
```

Then I installed dotnet-sdk-6.0.100-preview.3.21202.5-osx-arm64.pkg,
rerun the command
```bash
John@Johns-Mac % dotnet ef dbcontext scaffold  "ConnectionString" Pomelo.EntityFrameworkCore.MySql -o Model --schema a --schema b -f
Failed to load /usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib, error: dlopen(/usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib, 1): no suitable image found.  Did find:
        /usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib: mach-o, but wrong architecture
        /usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib: mach-o, but wrong architecture
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366
John@Johns-Mac %
```

Actually .net 6 is totally crashed, I can't even build project
```
Failed to load /usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.6/libhostpolicy.dylib, error: dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.6/libhostpolicy.dylib, 1): no suitable image found.  Did find:
	/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.6/libhostpolicy.dylib: mach-o, but wrong architecture
	/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.6/libhostpolicy.dylib: mach-o, but wrong architecture
An error occurred while loading required library libhostpolicy.dylib from [/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.6]
The program '[3156] X.dll' has exited with code 130 (0x82).
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
```

**Comment by ajcvickers** [comment] 2021-06-01 15:48
@johnseed Please post your full .csproj file.

**Comment by johnseed** [comment] 2021-06-02 03:54
> @johnseed Please post your full .csproj file.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
 
  <ItemGroup>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="6.0.0-preview.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0-preview.4.21253.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

**Comment by grinay** [comment] 2021-06-02 12:23
@johnseed you need to add RollForward option example
<PropertyGroup>
  <TargetFramework>net5.0</TargetFramework>
  <RollForward>Major</RollForward>
</PropertyGroup>

**Comment by AndriySvyryd** [comment] 2021-06-04 17:12
cc: @bricelam

**Comment by bricelam** [comment] 2021-06-04 20:25
> I installed dotnet-sdk-6.0.100-preview.3.21202.5-osx-arm64.pkg
> /usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib: mach-o, but wrong architecture

Did you accidentally install an x64 (not arm64) version 6.0.0-preview.3.21201.4 of the runtime?

**Comment by johnseed** [comment] 2021-06-07 01:33
> > I installed dotnet-sdk-6.0.100-preview.3.21202.5-osx-arm64.pkg
> > /usr/local/share/dotnet/host/fxr/6.0.0-preview.3.21201.4/libhostfxr.dylib: mach-o, but wrong architecture
> 
> Did you accidentally install an x64 (not arm64) version of the 6.0.0-preview.3.21201.4 runtime?

I don't think so
<img width="438" alt="Screen Shot 2021-06-07 at 9 32 27 AM" src="https://user-images.githubusercontent.com/48501700/120947865-5f5c8f00-c773-11eb-8479-ab596670a2b4.png">

**Comment by bricelam** [comment] 2021-06-15 18:13
The SDK team says this is a known issue. The x64 and arm64 installers stomp over each other and cause problems. Try uninstalling, deleting everything under `/usr/local/share/dotnet` then try again.

**Comment by johnseed** [comment] 2021-06-17 09:35
> The SDK team says this is a known issue. The x64 and arm64 installers stomp over each other and cause problems. Try uninstalling, deleting everything under `/usr/local/share/dotnet` then try again.

I tried, delete and reinstall does not solve the problem.

**Comment by u2m4c6** [comment] 2021-06-19 03:57
I have also deleted everything under `/usr/local/share/dotnet`, reinstalled just .NET 6 preview 5, and am still getting this error. Any way around this?

**Comment by johnseed** [comment] 2021-06-21 03:28
> I have also deleted everything under `/usr/local/share/dotnet`, reinstalled just .NET 6 preview 5, and am still getting this error. Any way around this?

Just don't install .NET 6 on MAC M1 for now.

**Comment by bricelam** [comment] 2021-06-28 21:05
☹️ Sorry friends, I'm still trying to get access to an M1 so I can dig into this.

**Comment by nbsoftware** [comment] 2021-07-14 17:05
Seems it is doing the same thing with the latest dotnet-sdk-6.0.100-preview.6.21355.2-osx-arm64.pkg
I'm also on a M1 Mac.

```
dotnet --version
Failed to load /usr/local/share/dotnet/host/fxr/6.0.0-preview.6.21352.12/libhostfxr.dylib, error: dlopen(/usr/local/share/dotnet/host/fxr/6.0.0-preview.6.21352.12/libhostfxr.dylib, 1): no suitable image found.  Did find:
	/usr/local/share/dotnet/host/fxr/6.0.0-preview.6.21352.12/libhostfxr.dylib: mach-o, but wrong architecture
	/usr/local/share/dotnet/host/fxr/6.0.0-preview.6.21352.12/libhostfxr.dylib: mach-o, but wrong architecture
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/6.0.0-preview.6.21352.12/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366
```

**Comment by nbsoftware** [comment] 2021-07-14 17:10
Update: doing some cleaning (removing old versions) and reinstalling did make it work

```
fmeyer@FREDSM1 fxr % dotnet --version
6.0.100-preview.6.21355.2
```

Don't really get what happened there.

**Comment by johnseed** [comment] 2021-07-15 02:10
I guess it is fixed in preview6, but the debugger not working with Visual Studio for MAC, that's another issue.
```
Unable to attach to CoreCLR. Unknown Error: 0x80131c3c
```

**Comment by johnseed** [comment] 2021-07-19 07:08
My mistake, it is not completely fixed, dotnet --version, build, run is working, but the ef scaffold is not
```
John@Johns-MacBook-Pro XX.Scaffold % dotnet ef dbcontext scaffold  "xxx" Pomelo.EntityFrameworkCore.MySql -o Model --schema xxx -t tablex  -f

Failed to load /usr/local/share/dotnet/host/fxr/6.0.0-preview.6.21352.12/libhostfxr.dylib, error: dlopen(/usr/local/share/dotnet/host/fxr/6.0.0-preview.6.21352.12/libhostfxr.dylib, 1): no suitable image found.  Did find:
        /usr/local/share/dotnet/host/fxr/6.0.0-preview.6.21352.12/libhostfxr.dylib: mach-o, but wrong architecture
        /usr/local/share/dotnet/host/fxr/6.0.0-preview.6.21352.12/libhostfxr.dylib: mach-o, but wrong architecture
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/6.0.0-preview.6.21352.12/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366


John@Johns-MacBook-Pro XX.Scaffold % dotnet ef dbcontext scaffold "xxx" Npgsql.EntityFrameworkCore.PostgreSQL -o xxx -c XXContext -t tablex -f

Failed to load /usr/local/share/dotnet/host/fxr/6.0.0-preview.6.21352.12/libhostfxr.dylib, error: dlopen(/usr/local/share/dotnet/host/fxr/6.0.0-preview.6.21352.12/libhostfxr.dylib, 1): no suitable image found.  Did find:
        /usr/local/share/dotnet/host/fxr/6.0.0-preview.6.21352.12/libhostfxr.dylib: mach-o, but wrong architecture
        /usr/local/share/dotnet/host/fxr/6.0.0-preview.6.21352.12/libhostfxr.dylib: mach-o, but wrong architecture
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/6.0.0-preview.6.21352.12/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366
John@Johns-MacBook-Pro XX.Scaffold % 
```

**Comment by ErikEJ** [comment] 2021-07-19 07:58
Which provider and has it been updated for preview 6?

**Comment by johnseed** [comment] 2021-07-19 09:13
> Which provider and has it been updated for preview 6?!

[image](https://user-images.githubusercontent.com/48501700/126133217-f55c69e4-e962-4664-9932-afc29c382bc0.png)
Npgsql support preview 6.
After I updated dotnet-ef, the error disappeared, but no output as well, no matter what parameters are passed.
```
John@Johns-MacBook-Pro XX.Scaffold % dotnet tool install --global dotnet-ef --version 6.0.0-preview.6.21352.1
Tool 'dotnet-ef' was successfully updated from version '5.0.6' to version '6.0.0-preview.6.21352.1'.

John@Johns-MacBook-Pro XX.Scaffold % dotnet ef dbcontext scaffold "xxx" Npgsql.EntityFrameworkCore.PostgreSQL -o Model -c XXContext -t table1 -t table2 -f
John@Johns-MacBook-Pro XX.Scaffold % 
John@Johns-MacBook-Pro XX.Scaffold % dotnet ef dbcontext scaffold --help
John@Johns-MacBook-Pro XX.Scaffold % 
```

**Comment by ErikEJ** [comment] 2021-07-19 09:21
Are you using the daily npgsql feed?

https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL/

**Comment by johnseed** [comment] 2021-07-19 09:29
> Are you using the daily npgsql feed?
> 
> https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL/

I tried the latest package, nothing changed, the dotnet ef have no output at all, but everything works on Windows.
```
dotnet add package Npgsql.EntityFrameworkCore.PostgreSQL --version 6.0.0-preview6-ci.20210703T083753 --source https://www.myget.org/F/npgsql-unstable/api/v3/index.json
```

**Comment by roji** [comment] 2021-07-19 11:18
Note that a final Npgsql.EntityFrameworkCore.PostgreSQL preview6 version isn't out yet... Although the latest CI version is being tried above, we may want to hold off for a few days until it's released and try again.

**Comment by ajcvickers** [comment] 2021-08-06 12:58
@johnseed Can you try with [Npgsql.EntityFrameworkCore.PostgreSQL](https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL/6.0.0-preview6) now that preview 6 is released?

**Comment by johnseed** [comment] 2021-08-09 02:48
> @johnseed Can you try with [Npgsql.EntityFrameworkCore.PostgreSQL](https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL/6.0.0-preview6) now that preview 6 is released?

<img width="454" alt="image" src="https://user-images.githubusercontent.com/48501700/128655549-60db7953-1632-4edf-b28b-8c70aa057f3a.png">

The thing is, dotnet ef has no response at all, no output, nothing

**Comment by roji** [comment] 2021-08-09 07:33
@johnseed can you please post the output of `dotnet --list-sdks` and `dotnet tool list -g`?

**Comment by johnseed** [comment] 2021-08-09 10:08
> @johnseed can you please post the output of `dotnet --list-sdks` and `dotnet tool list -g`?

```bash
John@Johns-MacBook-Pro ~ % dotnet --list-sdks
3.1.409 [/usr/local/share/dotnet/sdk]
3.1.410 [/usr/local/share/dotnet/sdk]
3.1.411 [/usr/local/share/dotnet/sdk]
5.0.203 [/usr/local/share/dotnet/sdk]
5.0.301 [/usr/local/share/dotnet/sdk]
5.0.302 [/usr/local/share/dotnet/sdk]
6.0.100-preview.6.21355.2 [/usr/local/share/dotnet/sdk]
John@Johns-MacBook-Pro ~ % dotnet tool list -g
Package Id      Version      Commands
-------------------------------------
John@Johns-MacBook-Pro ~ % 
```

**Comment by dhsl** [comment] 2021-09-07 07:58
> > @johnseed can you please post the output of `dotnet --list-sdks` and `dotnet tool list -g`?
> 
> ```shell
> John@Johns-MacBook-Pro ~ % dotnet --list-sdks
> 3.1.409 [/usr/local/share/dotnet/sdk]
> 3.1.410 [/usr/local/share/dotnet/sdk]
> 3.1.411 [/usr/local/share/dotnet/sdk]
> 5.0.203 [/usr/local/share/dotnet/sdk]
> 5.0.301 [/usr/local/share/dotnet/sdk]
> 5.0.302 [/usr/local/share/dotnet/sdk]
> 6.0.100-preview.6.21355.2 [/usr/local/share/dotnet/sdk]
> John@Johns-MacBook-Pro ~ % dotnet tool list -g
> Package Id      Version      Commands
> -------------------------------------
> John@Johns-MacBook-Pro ~ % dotnet tool install --global dotnet-ef
> You can invoke the tool using the following command: dotnet-ef
> Tool 'dotnet-ef' (version '5.0.8') was successfully installed.
> John@Johns-MacBook-Pro ~ % dotnet tool list -g                   
> Package Id      Version      Commands 
> --------------------------------------
> dotnet-ef       5.0.8        dotnet-ef
> John@Johns-MacBook-Pro ~ % dotnet ef                  
> John@Johns-MacBook-Pro ~ % dotnet ef --help
> John@Johns-MacBook-Pro ~ % 
> ```

Same here. Also tested with dotnet-ef 5.0.9.
```shell
❯ dotnet ef
❯ dotnet ef --help
❯ dotnet ef notworking
❯ dotnet --list-sdks
6.0.100-preview.7.21379.14 [/usr/local/share/dotnet/sdk]
❯ dotnet tool list -g
Package Id      Version                      Commands
------------------------------------------------------
dotnet-ef       6.0.0-preview.7.21378.4      dotnet-ef

**Comment by miguellira** [comment] 2021-09-11 12:26
@johnseed and @dhsl I came here after @ajcvickers referenced this issue from mine.

I believe it has already been mentioned in this thread but probably the best thing is to ensure **_all_** your .NET Core SDKs are x64 versions even though your M1 Macs can support arm64.

I purposely avoided installing the .NET SDK on my M1 Mac until an arm64 version was made available, therefore, I do not have a version 3 or 5 of the SDK on this machine and was able to get dotnet-ef working after uninstalling the arm64 SDK and installing the x64 instead. Good luck!

**Comment by bricelam** [comment] 2021-09-20 18:53
Correct me if I'm wrong, but I think the only remaining issue here is just a duplicate of #25927.

**Comment by cagdas01** [comment] 2021-11-29 22:49
> The SDK team says this is a known issue. The x64 and arm64 installers stomp over each other and cause problems. Try uninstalling, deleting everything under `/usr/local/share/dotnet` then try again.

solved!

**Closed** 2022-10-16 19:35 UTC
Labels: customer-reported
