### ISSUE TITLE
LastOrDefault Issue

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#19741] opened 2020-01-29 19:29 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/898938/lastordefault-issue.html)._

---
<p>I am using LastOrDefault() method in my code but everytime it giving me an error. Please look into it and refine in your next update. I am using EF core 3.0.</p>

---
#### Visual Studio Feedback System on 1/28/2020, 04:41 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2020-01-29 19:31
Please attach a small, runnable project or post a complete code listing that reproduces the behavior you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-02-07 17:34
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:08 UTC
Labels: closed-could-not-reproduce, customer-reported
