### ISSUE TITLE
System.AggregateException error after updating .Net and nugets packages

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#32531] opened 2023-12-06 10:43 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemAggregateException-error-after-up/10529131)._

---
[severity:I'm unable to use this version] [regression]
After updating Microsoft.EntityFrameworkCore and Microsoft.EntityFrameworkCoreMicrosoft.EntityFrameworkCore.SqlServer to version 8.0 and updating .NET to version 17.8 I began to get "System.AggregateException" error. 

---
#### Feedback Bot on 11/30/2023, 02:10 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2024-01-03 14:06
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-01-03 14:06 UTC
