### ISSUE TITLE
Feature request: use LINQ-provider from linq2db

### ISSUE THREAD

**Issue by Kirill-Maurin** [dotnet/efcore#11657] opened 2018-04-12 13:50 UTC
Сurrently LINQ-provider in EF Core is far from perfect.
But there is a production-ready alternative: [linq2db](https://github.com/linq2db)
EF Core model can be tranlated to linq2db mapping scheme.
This will allow very cheap access to the following functionality:

1. "Group by" 
1. Nested queries
1. Extensions for easy implementation of any unsupported "out-of-box" DB-specific function or operation (like IP address comparison for PostgreSql)
1. Bulk operations 
1. Many more different features

Also, EF Core team will be able to allocate more resources for the improvement of migrations, change tracker and other unique EF Core features 

Now I use my own wrapper to transparently combine two ORM sharing one model

**Comment by ajcvickers** [comment] 2018-04-13 19:01
@Kirill-Maurin We are supportive of creating extensions that can be used with EF Core to enhance or replace some existing built-in part of the stack. To that end, we would be happy to work with the community on adding appropriate extension points to EF Core that can be used for such things. That being said, it would have to be a community driven effort, and the majority of the code should live externally to the EF Core repo.

With regard to the list of functionality that is "missing" could you be more specific on which parts are not working for you? It seems like the first three are implemented in 2.1, and #4 requires more than just changing the LINQ provider.

**Comment by Kirill-Maurin** [comment] 2018-04-16 05:32
> It seems like the first three are implemented in 2.1

Nested queries:
EF Core 2.1preview1

```
07:15:46.7670|[8]|Compiling query model: 
'from X p in DbSet<X>
select new <>f__AnonymousType3<X, string>(
    [p], 

        (from IP2Country c in DbSet<IP2Country>
        where int [c].From.CompareTo([p].IP) <= 0
        order by [c].From desc
        select [c].Country)
        .Take(1)
        .FirstOrDefault()
)'
07:15:46.8217|[8]|Optimized query model: 
'from X p in DbSet<X>
select new <>f__AnonymousType3<X, string>(
    [p], 

        (from IP2Country c in DbSet<IP2Country>
        where int [c].From.CompareTo([p].IP) <= 0
        order by [c].From desc
        select [c].Country)
        .Take(1)
        .FirstOrDefault()
)'
07:15:46.9892|[8]|(QueryContext queryContext) => IEnumerable<<>f__AnonymousType3<X, string>> _InterceptExceptions(
    source: IEnumerable<<>f__AnonymousType3<X, string>> _ShapedQuery(
        queryContext: queryContext, 
        shaperCommandContext: SelectExpression: 
            SELECT "p"."Updated", "p"."XId", "p"."IP", "p"."Port"
            FROM "Xs" AS "p", 
        shaper: TypedProjectionShaper<BufferedOffsetEntityShaper<X>, X, <>f__AnonymousType3<X, string>>), 
    contextType: P2P.PostgreSql.PostgreSqlP2PContext, 
    logger: DiagnosticsLogger<Query>, 
    queryContext: queryContext)
07:15:47.0146|[8]|Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "p"."Updated", "p"."XId", "p"."IP", "p"."Port"
FROM "Xs" AS "p"
07:15:47.0764|[8]|Executed DbCommand (63ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "p"."Updated", "p"."XId", "p"."IP", "p"."Port"
FROM "Xs" AS "p"
07:15:47.3125|[8]|A data reader was disposed.
07:15:47.3125|[8]|Executing DbCommand [Parameters=[@_outer_IP='?'], CommandType='Text', CommandTimeout='30']
SELECT "t0".*
FROM (
    SELECT "c0"."Country"
    FROM "IP2Country" AS "c0"
    WHERE "c0"."From" <= @_outer_IP
    ORDER BY "c0"."From" DESC
    LIMIT 1
) AS "t0"
ORDER BY "t0"."From" DESC
LIMIT 1
07:15:47.3890|[8]|Failed executing DbCommand (68ms) [Parameters=[@_outer_IP='?'], CommandType='Text', CommandTimeout='30']
SELECT "t0".*
FROM (
    SELECT "c0"."Country"
    FROM "IP2Country" AS "c0"
    WHERE "c0"."From" <= @_outer_IP
    ORDER BY "c0"."From" DESC
    LIMIT 1
) AS "t0"
ORDER BY "t0"."From" DESC
LIMIT 1
07:15:47.4321|[8]|An exception occurred in the database while iterating the results of a query for context type 'P2P.PostgreSql.PostgreSqlP2PContext'.
Npgsql.PostgresException (0x80004005): 42703: column t0.From does not exist
   at Npgsql.NpgsqlConnector.<DoReadMessage>d__155.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadExpecting>d__161`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlDataReader.<NextResult>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.<Execute>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__92.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_InjectParameters>d__27`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure , QueryContext , X )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()

**Comment by Kirill-Maurin** [comment] 2018-04-16 06:02
> It seems like the first three are implemented in 2.1

"group by"
No logged errors, no logged queries, no data in my application

```sql
14:30:47.3502|[1]|Entity Framework Core 2.1.0-preview1-28290 initialized 'PostgreSqlP2PContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: None
14:30:47.6162|[1]|Opening connection to database 'P2P' on server 'tcp://test:1234'.
14:30:48.0547|[13]|Opened connection to database 'P2P' on server 'tcp://test:1234'.
14:30:48.0678|[13]|Beginning transaction with isolation level 'Snapshot'.
14:30:48.2708|[5]|Compiling query model: 
'from IGrouping<<>f__AnonymousType3<string, int>, YDetails> g in 
    (from Z2Ks t2K in DbSet<Z2Ks>
    join Z2P t2P in DbSet<Z2P>
    on new <>f__AnonymousType7<DateTime, int>(
        [t2K].Updated, 
        [t2K].ZId
    ) equals new <>f__AnonymousType7<DateTime, int>(
        [t2P].ZUpdated, 
        [t2P].ZId
    )
    join P p in DbSet<P>
    on new <>f__AnonymousType0<DateTime, string>(
        [t2P].PUpdated, 
        [t2P].PId
    ) equals new <>f__AnonymousType0<DateTime, string>(
        [p].Updated, 
        [p].Id
    )
    join P2X p2T in DbSet<P2X>
    on new <>f__AnonymousType2<DateTime, string>(
        [t2P].PUpdated, 
        [t2P].PId
    ) equals new <>f__AnonymousType2<DateTime, string>(
        [p2T].PUpdated, 
        [p2T].PId
    )
    join X t in DbSet<X>
    on [p2T].XId equals [t].Id
    where [t2K].Outdated == __MaxValue_Date_0 && [p].Outdated == __MaxValue_Date_1 && [p2T].Outdated == __MaxValue_Date_2
    join Y t2P in 
        (from Y <generated>_1 in DbSet<Y>
        select [<generated>_1]).FromSql('select t2p.*, (select i2c."Country" from "IP2Country" i2c where i2c."From" < t2p."IP" order by i2c."From" desc limit 1) from "X2Ys" t2p')
    on [t].Id equals [t2P].XId
    select new YDetails{ 
        ZId = [t2K].ZId, 
        XId = [t].Id, 
        Size = [t].Size ?? 0, 
        IP = [t2P].IP, 
        Port = [t2P].Port, 
        Country = [t2P].Country, 
        Updated = [t2P].Updated 
    }
    ).GroupBy(new <>f__AnonymousType3`2(Country = [t2P].Country, ZId = [t2K].ZId), new YDetails() {ZId = [t2K].ZId, XId = [t].Id, Size = ([t].Size ?? 0), IP = [t2P].IP, Port = [t2P].Port, Country = [t2P].Country, Updated = [t2P].Updated})
from YDetails gg in [g]
select new <>f__AnonymousType4<int, string>(
    [gg].ZId, 
    [gg].Country
)'
14:30:48.3391|[5]|Optimized query model: 
'from IGrouping<<>f__AnonymousType3<string, int>, YDetails> g in 
    (from Z2Ks t2K in DbSet<Z2Ks>
    join Z2P t2P in DbSet<Z2P>
    on new <>f__AnonymousType7<DateTime, int>(
        [t2K].Updated, 
        [t2K].ZId
    ) equals new <>f__AnonymousType7<DateTime, int>(
        [t2P].ZUpdated, 
        [t2P].ZId
    )
    join P p in DbSet<P>
    on new <>f__AnonymousType0<DateTime, string>(
        [t2P].PUpdated, 
        [t2P].PId
    ) equals new <>f__AnonymousType0<DateTime, string>(
        [p].Updated, 
        [p].Id
    )
    join P2X p2T in DbSet<P2X>
    on new <>f__AnonymousType2<DateTime, string>(
        [t2P].PUpdated, 
        [t2P].PId
    ) equals new <>f__AnonymousType2<DateTime, string>(
        [p2T].PUpdated, 
        [p2T].PId
    )
    join X t in DbSet<X>
    on [p2T].XId equals [t].Id
    where [t2K].Outdated == __MaxValue_Date_0 && [p].Outdated == __MaxValue_Date_1 && [p2T].Outdated == __MaxValue_Date_2
    join Y t2P in DbSet<Y>
    on [t].Id equals [t2P].XId
    select new YDetails{ 
        ZId = [t2K].ZId, 
        XId = [t].Id, 
        Size = [t].Size ?? 0, 
        IP = [t2P].IP, 
        Port = [t2P].Port, 
        Country = [t2P].Country, 
        Updated = [t2P].Updated 
    }
    ).GroupBy(new <>f__AnonymousType3`2(Country = [t2P].Country, ZId = [t2K].ZId), new YDetails() {ZId = [t2K].ZId, XId = [t].Id, Size = ([t].Size ?? 0), IP = [t2P].IP, Port = [t2P].Port, Country = [t2P].Country, Updated = [t2P].Updated})
from YDetails gg in [g]
select new <>f__AnonymousType4<int, string>(
    [gg].ZId, 
    [gg].Country
)'
14:30:48.5713|[4]|Disposing transaction.
14:30:48.5713|[4]|Closing connection to database 'P2P' on server 'tcp://test:1234'.
14:30:48.5812|[4]|Closed connection to database 'P2P' on server 'tcp://test:1234'.

**Comment by Kirill-Maurin** [comment] 2018-04-16 06:10
> It seems like the first three are implemented in 2.1

Extension for missed "out-the-box" features
This query cannot be generated by EF Core: type of field "From" is IPAddress.

```sql
select i2c."Country" from "IP2Country" i2c where i2c."From" < t2p."IP" order by i2c."From" desc limit 1
```

A solution with linq2Db

```csharp
		[Sql.Expression( "{0} <= {1}", PreferServerSide = true, IsPredicate = true )]
		public static bool LessOrEqual( IPAddress left, IPAddress right ) => left.CompareTo( right ) <= 0;
```

**Comment by Kirill-Maurin** [comment] 2018-04-16 06:17
> #4 requires more than just changing the LINQ provider.

1. LINQ is not limited to SELECT queries
1. linq2db can do bulk operations for many DBMS, if you have a mapping scheme
1. Mapping scheme can be generated from EF Core data model

**Comment by ErikEJ** [comment] 2018-04-16 08:16
@Kirill-Maurin  have you tried preview-2 ?

**Comment by Kirill-Maurin** [comment] 2018-04-16 10:58
@roji 
Yes, Npgsql provider works well

@ErikEJ 
preview-2 are better than preview-1
I can convert IPAddress to comparable type by HasConversion() 

```sql
10:52:10.4781|[1]|Entity Framework Core 2.1.0-preview2-30571 initialized 'PostgreSqlXYZContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: None
10:52:10.5978|[1]|Opening connection to database 'XYZ' on server 'tcp://test:1234'.
10:52:11.5554|[12]|Opened connection to database 'XYZ' on server 'tcp://test:1234'.
10:52:11.5554|[12]|Beginning transaction with isolation level 'ReadCommitted'.
10:52:11.7766|[9]|Compiling query model: 
'from X2Y p in DbSet<X2Y>
select new <>f__AnonymousType3<BigInteger, string>(
    [p].IP, 

        (from IP2Country c in DbSet<IP2Country>
        where [c].From <= [p].IP
        order by [c].From asc
        select [c]).FirstOrDefault().Country
)'
10:52:11.8408|[9]|Optimized query model: 
'from X2Y p in DbSet<X2Y>
select new <>f__AnonymousType3<BigInteger, string>(
    [p].IP, 

        (from IP2Country c in DbSet<IP2Country>
        where [c].From <= [p].IP
        order by [c].From asc
        select [c].Country).FirstOrDefault()
)'
10:52:12.0420|[9]|(QueryContext queryContext) => IEnumerable<<>f__AnonymousType3<BigInteger, string>> _InterceptExceptions(
    source: IEnumerable<<>f__AnonymousType3<BigInteger, string>> _ShapedQuery(
        queryContext: queryContext, 
        shaperCommandContext: SelectExpression: 
            SELECT p."IP", (
                SELECT c."Country"
                FROM "IP2Country" AS c
                WHERE c."From" <= p."IP"
                ORDER BY c."From"
                LIMIT 1
            ) AS "Country"
            FROM "X2Ys" AS p, 
        shaper: TypedProjectionShaper<ValueBufferShaper, ValueBuffer, <>f__AnonymousType3<BigInteger, string>>), 
    contextType: XYZ.PostgreSql.PostgreSqlXYZContext, 
    logger: DiagnosticsLogger<Query>, 
    queryContext: queryContext)
10:52:12.0750|[9]|Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT p."IP", (
    SELECT c."Country"
    FROM "IP2Country" AS c
    WHERE c."From" <= p."IP"
    ORDER BY c."From"
    LIMIT 1
) AS "Country"
FROM "X2Ys" AS p
10:52:12.1803|[9]|Executed DbCommand (106ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT p."IP", (
    SELECT c."Country"
    FROM "IP2Country" AS c
    WHERE c."From" <= p."IP"
    ORDER BY c."From"
    LIMIT 1
) AS "Country"
FROM "X2Ys" AS p
```

**Comment by smitpatel** [comment] 2018-04-16 18:03
Nested query bug posted above. Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/11326 Fixed in 2.1.0-preview2

**Comment by smitpatel** [comment] 2018-04-16 18:05
GroupBy issue seems like you are generating query and enumerator but you are not iterating it. If you are not consuming group, we don't do the work to retrieve data. Given that there are customers out there using GroupBy successfully, it seems like something is amiss in user code which is causing no sql to be seen in the logs.

**Comment by Kirill-Maurin** [comment] 2018-04-17 05:16
@smitpatel

> Nested query bug posted above. Duplicate of #11326 Fixed in 2.1.0-preview2

Thanks

> GroupBy issue seems like you are generating query and enumerator but you are not iterating it.

I use the same code to reproduce. I change only query and LINQ-provider.
linq2db works fine

```sql
12:26:09.5150|[1]|Entity Framework Core 2.1.0-preview2-30571 initialized 'PostgreSqlXYZContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: None
12:26:09.6222|[1]|Opening connection to database 'XYZ' on server 'tcp://test:1234'.
12:26:10.4541|[12]|Opened connection to database 'XYZ' on server 'tcp://test:1234'.
12:26:10.4541|[12]|Beginning transaction with isolation level 'Snapshot'.
12:26:10.6298|[6]|Expression test code generated: 'E:\Temp\linq2db\ExpressionTest.0.cs'. DataConnection
12:26:11.6415|[6]|--  PostgreSQL.9.2 PostgreSQL
DECLARE @p1 Timestamp -- DateTime
SET     @p1 = '2018-04-16'
DECLARE @p2 Timestamp -- DateTime
SET     @p2 = '9999-12-31'
DECLARE @p3 Timestamp -- DateTime
SET     @p3 = '9999-12-31'
DECLARE @p4 Timestamp -- DateTime
SET     @p4 = '9999-12-31'

SELECT
	t3."Code",
	t3."Name",
	g1.c11 as c111,
	g1.c2 as c21,
	g1.c3 as c31,
	g1.c4 as c41
FROM
	(
		SELECT
			"t2K"."ZId",
			"t2P1".c1 as c11,
			Sum(Coalesce(t."Size", 0)) as c2,
			COUNT(DISTINCT t."Id") as c3,
			COUNT(DISTINCT (Cast("t2P1"."IP" as VarChar(100)) || ':' || Cast("t2P1"."Port" as VarChar(11)))) as c4
		FROM
			"Z2Keywords" "t2K"
				INNER JOIN "Z2P" "t2P" ON "t2K"."Updated" = "t2P"."ZUpdated" AND "t2K"."ZId" = "t2P"."ZId"
				INNER JOIN "P" p ON "t2P"."PUpdated" = p."Updated" AND ("t2P"."PId" IS NULL AND p."Id" IS NULL OR "t2P"."PId" = p."Id")
				INNER JOIN "P2Xs" "p2T" ON "t2P"."PUpdated" = "p2T"."PUpdated" AND ("t2P"."PId" IS NULL AND "p2T"."PId" IS NULL OR "t2P"."PId" = "p2T"."PId")
				INNER JOIN "Xs" t ON "p2T"."XId" IS NULL AND t."Id" IS NULL OR "p2T"."XId" = t."Id"
				INNER JOIN (
					SELECT
						t2."XId",
						t2."Updated",
						(
							SELECT
								t1."Country"
							FROM
								"IP2Country" t1
							WHERE
								t1."From" <= t2."IP"
							ORDER BY
								t1."From" DESC
							LIMIT 1
						) as c1,
						t2."IP",
						t2."Port"
					FROM
						"X2Ys" t2
				) "t2P1" ON t."Id" IS NULL AND "t2P1"."XId" IS NULL OR t."Id" = "t2P1"."XId"
		WHERE
			"t2P1"."Updated" = :p1 AND
			"p2T"."Outdated" = :p2 AND
			p."Outdated" = :p3 AND
			"t2K"."Outdated" = :p4
		GROUP BY
			"t2K"."ZId",
			"t2P1".c1
	) g1
		INNER JOIN "Zs" t3 ON g1."ZId" = t3."Id"
 DataConnection
12:26:11.9834|[6]|Query Execution Time: 00:00:00.3384215
 DataConnection
12:26:12.0770|[11]|Total Execution Time: 00:00:00.6172998. Rows Count: 545.
 DataConnection
```

**Comment by smitpatel** [comment] 2018-04-17 15:08
> I use the same code to reproduce. I change only query and/or LINQ-provider.
linq2db works fine

Does EF Core gives you incorrect results? Or shows you empty results when there are results? Did you verify results by EF Core? If you see that there are no results generated when you verify them, please file a new issue with detailed repro steps. (ideally a repro solution)

EF Core using streaming for results. It will create the query and do all groundwork but reading actual data for server or running SQL queries (especially in the case where there are more than 1 SQL to be run), will depend on consumption of results from client code. If you are not consuming the results of the query, EF Core will not generate client objects for result. This is pattern allows you to iterate over a large result set without running out of memory because you can keep only data in memory which is needed for current iteration. Not all ORM or linq to sql translator work this way and they may be computing results even without getting enumerated. Difference in such behaviour is not indication that EF core is not working.

**Comment by smitpatel** [comment] 2018-04-17 18:53
Verified that if you call `GetEnumerator` on query but do not enumerate the results, EF Core will not execute any SQL on server.

**Comment by MaceWindu** [comment] 2018-05-07 08:10
You asked for it...
https://github.com/linq2db/linq2db.EntityFrameworkCore

**Comment by MaceWindu** [comment] 2018-05-08 12:05
@ajcvickers 
Talking about extension points support :). We currently miss two things and use reflection for it:
- getting context options from context: https://github.com/linq2db/linq2db.EntityFrameworkCore/blob/master/Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs#L293
- getting context from EntityQueryProvider: https://github.com/linq2db/linq2db.EntityFrameworkCore/blob/master/Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs#L350

**Comment by nathan-parkinson** [comment] 2018-05-30 19:23
@MaceWindu This is awesome.  Please please continue to develop and maintain this project.  With entityframework core and linq2db effectively combined there is a full feature set.  This would be a very powerful ORM setup.  

Is there a roadmap for this project?

**Comment by MaceWindu** [comment] 2018-05-31 12:08
@nathan-parkinson not sure what we can include into roadmap. It is pretty much feature-complete project. I think next week we can release it on nuget taking into account EF.Core 2.1 release.

**Comment by nathan-parkinson** [comment] 2018-06-01 18:15
@MaceWindu Sorry, I think I'm asking the wrong question.  I suppose what i'm trying to ask is whether it is a safe option to add this into my projects. Will this be maintained and released - currently the readme states it is in early preview - or is this an experimental repo that could be discontinued at any time.

**Comment by MaceWindu** [comment] 2018-06-02 14:11
@nathan-parkinson it is in preview, because we didn't get any feedback yet from real users. We don't plan to drop this project and if it will get enought attention from users, we will consider to include it into linq2db directly later.

**Comment by nathan-parkinson** [comment] 2018-06-03 08:56
@MaceWindu Thanks for the information.  If I have any useful feedback I will let you know

**Comment by aspnet-hello** [comment] 2018-09-24 18:04
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.

**Closed** 2022-10-16 12:18 UTC
Labels: closed-no-further-action
