### ISSUE TITLE
Add migration fails with 'Unable to cast object of type 'System.Single' to type 'System.Int32'

### ISSUE THREAD

**Issue by dominique-ruest** [dotnet/efcore#18021] opened 2019-09-24 15:21 UTC
Adding a migration fails with 'Unable to cast object of type 'System.Single' to type 'System.Int32'.

### Steps to reproduce

Generate an initial migration with entity types having numerical property types. Works fine. Without changes attempt to generate another migration with a new name. The migration fails with the following error:

System.InvalidCastException: Unable to cast object of type 'System.Single' to type 'System.Int32'.
   at lambda_method(Closure , ValueBuffer )
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalShadowEntityEntry..ctor(IStateManager stateManager, IEntityType entityType, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.NewInternalEntityEntry(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.Create(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.CreateEntry(IDictionary`2 values, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Update.Internal.UpdateAdapter.CreateEntry(IDictionary`2 values, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.TrackData(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(IModel source, IModel target, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to cast object of type 'System.Single' to type 'System.Int32'.

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Visual Studio 2019

**Comment by smitpatel** [comment] 2019-09-24 18:29
Duplicate of #17851

**Comment by smitpatel** [comment] 2019-09-25 21:13
> Generate an initial migration with entity types having numerical property types. Works fine. Without changes attempt to generate another migration with a new name. The migration fails with the following error:

I tried above and it still worked for me.
@Doumda - Can you provide us a small repro? Model class & Model configuration with has data works.

**Closed** 2022-10-16 14:44 UTC
Labels: closed-duplicate, customer-reported
