### ISSUE TITLE
Runnning ef migrations may generate a code that doesn't compile

### ISSUE THREAD

**Issue by dealdiane** [dotnet/efcore#3466] opened 2015-10-17 09:39 UTC
Suppose in your project, you have a file called SomeFile.cs with the following contents in it:

```
using System;
using Microsoft.Data.Entity;

public class SampleDb : DbContext
{
    public DbSet<Pet> Pets { get; set; }
}
```

Notice the lack of namespace in the code above.

Running ef migrations will generate the following code:

```
using System;
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Infrastructure;
using Microsoft.Data.Entity.Metadata;
using Microsoft.Data.Entity.Migrations;
using ;

namespace Beta8Sample.Migrations
{
    [DbContext(typeof(SampleDb))]
    [Migration("20151017092134_MyFirstMigration")]
    partial class MyFirstMigration
    {
        // .. more auto-generated code
    }
}
```

The extra `using ;` should not be there.

**Comment by bricelam** [comment] 2015-10-17 19:34
Dupe of #2467

**Closed** 2022-10-16 09:12 UTC
