### ISSUE TITLE
Unable to publish Asp.Net Core project with multiple projects to azure.

### ISSUE THREAD

**Issue by anderse77** [dotnet/efcore#8396] opened 2017-05-05 21:41 UTC
Describe what is not working as expected.
EF migration command does not run. 

Could not find a part of the path 'M:\obj\Datahantering.EntityFrameworkCore.targets'.
M:\Datahantering med xml\ChessPortal\src\ChessPortal\Properties\PublishProfiles\ChessPortalWeb20170505075257 - Web Deploy.pubxml(37,5): Error MSB3073: The command "dotnet ef migrations script --idempotent --output "M:\Datahantering med xml\ChessPortal\src\ChessPortal\obj\Release\netcoreapp1.0\PubTmp\\GeneratedSqlFile.sql" --context  ChessPortalContext --project M:\Datahantering med xml\ChessPortal\ChessPortal.Data\\ChessPortal.Data.csproj --verbose" exited with code 1.

```
Exception message:
Stack trace:
```

### Steps to reproduce
https://github.com/anderse77/ChessPortal.git won't publish

pubxml file: 
<?xml version="1.0" encoding="utf-8"?>

<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <WebPublishMethod>MSDeploy</WebPublishMethod>
    <ResourceId>/subscriptions/196aeec1-ad2d-49da-98a2-8ca4969a14b9/resourcegroups/ChessPortalResourceGroup/providers/Microsoft.Web/sites/ChessPortalWeb20170501091610</ResourceId>
    <ResourceGroup>ChessPortalResourceGroup</ResourceGroup>
    <PublishProvider>AzureWebSite</PublishProvider>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <SiteUrlToLaunchAfterPublish>http://chessportalweb20170501091610.azurewebsites.net</SiteUrlToLaunchAfterPublish>
    <LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>
    <ExcludeApp_Data>False</ExcludeApp_Data>
    <PublishFramework>netcoreapp1.0</PublishFramework>
    <ProjectGuid>5c6cec5d-ec99-4819-bfe5-40ea8f390886</ProjectGuid>
    <MSDeployServiceURL>chessportalweb20170501091610.scm.azurewebsites.net:443</MSDeployServiceURL>
    <DeployIisAppPath>ChessPortalWeb20170501091610</DeployIisAppPath>
    <RemoteSitePhysicalPath />
    <SkipExtraFilesOnServer>True</SkipExtraFilesOnServer>
    <MSDeployPublishMethod>WMSVC</MSDeployPublishMethod>
    <EnableMSDeployBackup>True</EnableMSDeployBackup>
    <UserName>$ChessPortalWeb20170501091610</UserName>
    <_SavePWD>True</_SavePWD>
    <_DestinationType>AzureWebSite</_DestinationType>
  </PropertyGroup>
</Project>
```c#
<code listing>
```

### Further technical details
EF Core version: 1.01
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Visual Studio 2017

**Comment by smitpatel** [comment] 2017-05-08 23:31
Possible dupe of https://github.com/aspnet/EntityFramework/issues/7945

Can you verify that directory `M:\Datahantering med xml\ChessPortal\src\ChessPortal\obj\Release\netcoreapp1.0\PubTmp\` where SQL file will be created exists.
If that does not fix the issue then please post output of following command
`dotnet ef migrations script --idempotent --output "M:\Datahantering med xml\ChessPortal\src\ChessPortal\obj\Release\netcoreapp1.0\PubTmp\GeneratedSqlFile.sql" --context ChessPortalContext --project M:\Datahantering med xml\ChessPortal\ChessPortal.Data\ChessPortal.Data.csproj --verbose`

**Comment by bricelam** [comment] 2017-05-30 15:53
I suspect this is a dupe of #7710. Have you tried with EF Core version 1.0.4 or 1.1.2 yet?

**Closed** 2022-10-16 11:04 UTC
