### ISSUE TITLE
EF Core 9: HierarchyId extension registration API is missing for Azure SQL

### ISSUE THREAD

**Issue by iambtshft** [dotnet/efcore#35307] opened 2024-12-10 21:21 UTC
## Issue Brief
HierachyId is not compatible with EF 9 API added in [Introduce UseAzureSql/UseAzureSynapse as alternatives to UseSqlServer](https://github.com/dotnet/efcore/issues/33816).

## Description
In current (.NET 8 / EF 8) project EF is used with SqlServer + HierarchyId extension. Registration looks like
```csharp
builder.Services.AddDbContext<...>((sp, o) =>
{
    o.UseSqlServer(
        builder.Configuration.GetConnectionString("...."),
        s =>
        {
            s.UseAzureSqlDefaults(); // <- This is deprecated from .NET9
            s.UseHierarchyId();
        });
});
```

However if I change registration to  (EF 9 / .NET 9)
```csharp
builder.Services.AddDbContext<...>((sp, o) =>
{
    o.UseAzureSql(
        builder.Configuration.GetConnectionString("...."),
        s =>
        {
            s.UseHierarchyId(); // <-- No such method, build failed
        });
});
```
as here no support for Azure SQL was implemented.
https://github.com/dotnet/efcore/blob/4f423a02c182e7bfd61f66d54942dbf22db3e8ab/src/EFCore.SqlServer.HierarchyId/Extensions/SqlServerHierarchyIdDbContextOptionsBuilderExtensions.cs#L19-L29 

### Workaround
1. **Option 1**. Ignore deprecation warning and continue to use `UseSqlServer`
2. **Option 2**: Copy entire `SqlServerHierarchyIdDbContextOptionsBuilderExtensions` but use `AzureSqlDbContextOptionsBuilder` instead of `SqlServerDbContextOptionsBuilder`

### Expected behaviour
HierarchyId should have support for `AzureSqlDbContextOptionsBuilder`.

### Relates to
1. https://github.com/dotnet/efcore/issues/35244

**Comment by ajcvickers** [comment] 2024-12-11 10:45
Duplicate of #35244

**Closed** 2024-12-11 11:13 UTC
Labels: customer-reported
