### ISSUE TITLE
'INSERT statement conflicted with the FOREIGN KEY constraint 

### ISSUE THREAD

**Issue by digital-nomad17** [dotnet/efcore#7754] opened 2017-03-01 16:18 UTC
Hi,

I am having an issue where it seems that there is a duplication in the foreign keys that are being generated for my database. Here is the exact exception:

```
An exception of type 'System.Exception' occurred in WalkFred.dll but was not handled in user code

Additional information: System.AggregateException: One or more errors occurred. (An error occurred while updating the entries. See the inner exception for details.) ---> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_ApplicationUser_Address_AddressId". The conflict occurred in database "WalkFred-12340be6-0442-4622-b782-a7412bb7d321", table "dbo.Address", column 'AddressId'.

The statement has been terminated.

   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__107_0(Task`1 result)

   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

```
This is a rather simple project so I think I am missing something simple. Here are the models:

```
public class Address
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AddressId { get; set; }
       // some more properties
}

public class Shelter
    {
 [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ShelterId { get; set; }
       // some more properties
      [Required]
        [ForeignKey("Address")]
        public int AddressId { get; set; }
        public Address Address { get; set; }
}

public class ApplicationUser : IdentityUser
    {
        [ForeignKey("Address")]
        public int AddressId { get; set; }
        public Address Address { get; set; }
}
```

And here is the seed for the models:

```
private void CreateShelters()
        {
            EntityEntry<Address> MspcaAddress = DbContext.Addresses.Add(new Address()
            {
                Street = "350 S Huntington Ave",
                City = "Jamaica Plain",
                State = "MA",
                AreaCode = "02130",
                Latitude = 42.3228928,
                Longititude = -71.11120540000002
            });
            // more of the same data

            EntityEntry<Shelter> Mspca = 
            DbContext.Shelters.Add(new Shelter()
            {
                Name = "MCSPA",
                                                 AddressId = MspcaAddress.Entity.AddressId
                                             });
            // more of the same data
            DbContext.SaveChanges();
        }
```
I dropped the database and created it again seeing if the problem would go away. No dice - any ideas?

**Comment by ajcvickers** [comment] 2017-03-06 21:38
@AndrewCarre We are having trouble following/reproducing this issue.  Can you provide a project or complete code listing that will allow us to reproduce what you are seeing?

**Comment by ajcvickers** [comment] 2017-03-13 19:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 10:55 UTC
Labels: closed-could-not-reproduce
