### ISSUE TITLE
Concat throw an exception

### ISSUE THREAD

**Issue by simpleway2016** [dotnet/efcore#5785] opened 2016-06-16 03:59 UTC
**code:**

``` c#
 var q1 = (from m in db.tb_users
                            where m.id == 1
                            select m);
                var q2 = (from m in db.tb_users
                          where m.id == 2
                          select m);
                q1 = q1.Concat(q2);
                var data = q1.ToArray();
```

**Exception message:**
Remotion.Linq.Clauses.ResultOperators.ConcatResultOperator

**Stack trace:**

```
   在 Microsoft.Data.Entity.Query.ResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   在 Microsoft.Data.Entity.Query.Internal.RelationalResultOperatorHandler.HandlerContext.EvalOnClient(Boolean requiresClientResultOperator)
   在 Microsoft.Data.Entity.Query.Internal.RelationalResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   在 Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   在 Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   在 Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
   在 Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   在 Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   在 Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   在 Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   在 Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_0`1.<CompileQuery>b__0()
   在 Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   在 Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   在 Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   在 Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   在 Remotion.Linq.QueryableBase`1.GetEnumerator()
   在 System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   在 System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
```

**Comment by rowanmiller** [comment] 2016-06-16 18:10
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving. Following are a few questions to help us understand this bug report, for future issues please try to include this info in the initial report._

Could you share a complete code listing (or a project) that we can use to reproduce and debug the issue you are seeing?

**Comment by rowanmiller** [comment] 2016-06-24 18:06
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 09:45 UTC
