### ISSUE TITLE
Dynamically created query cannot be translated, when a referenced member is declared in the base type.

### ISSUE THREAD

**Issue by amazingfox** [dotnet/efcore#19983] opened 2020-02-19 17:06 UTC
The reason I'm handling this issue in here is, that I believe the issue lies somewhere in the query translation implementation of EF Core. I have a query that gets enriched at run time with a dynamically created expression. This is a quite a common use case for folks that need to dynamically build query filters, based on user specified criteria for filtering and sorting.

The said expression essentially appends a `OrderByDescending(x => x.Id)` to the query.  When executing the query, an `InvalidOperationException` is thrown, telling me the query cannot be translated.

The query translation fails only though, if the dynamically created portion of the expression tree references **a member of the base type** of the projection type (see *PersonResponse* and *ResponseBase* in the provided sample project). It works fine how ever, when the referenced member is part of the derived projection type.

This is odd, as I can't see anything wrong with the code that generates the expression.

The rendered expression tree of the query (I used the `Print` extension method, before the query was executed) looks also valid to me:

```
DbSet<Person>
    .AsNoTracking()
    .Select(x => new PersonResponse{ 
        Id = x.Id, 
        Name = x.Name, 
        Birthdate = x.Birthdate 
    }
    )
    .OrderByDescending(x => x.Id)
```

Compared to the one that you can see in the following exception message:

```
System.InvalidOperationException: 'The LINQ expression 'DbSet<Person>
    .OrderByDescending(p => new PersonResponse{ 
        Id = p.Id, 
        Name = p.Name, 
        Birthdate = p.Birthdate 
    }
    .Id)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'
```

### Steps to reproduce

I crafted a small project that reproduces the error. You can find it here:

https://github.com/amazingfox/EFCoreQueryTranslationIssue

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.4

**Comment by smitpatel** [comment] 2020-02-21 01:01
Duplicate of #19087

**Closed** 2022-10-16 18:12 UTC
Labels: closed-duplicate, customer-reported
