### ISSUE TITLE
Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by rameshmummidi30** [dotnet/efcore#19666] opened 2020-01-22 10:28 UTC
I have an Azure Fuction API with a single endpoint that retrieves documents from a CosmosDB collection with EF core cosmos 3.1. It work for fine but some times I experience outages on the site (site starts to respond requests with 502 - bad gateway) due to OutOfMemory exceptions
General Specifications  : 

Azure function 3.0 .
Azure cosmos Entity Framework Core 3.0
Dotnet core 3.0

### Steps to reproduce

<!--
What steps can we follow to reproduce the issue?

We ❤ code! Include a complete code listing or attach a simplified project

List<string> disptDrivers = new List<string>();
			// at any time we will have only one entry 
			List<DriversID> filteredDispathces = await _context.Set<DriverDispatch>().AsNoTracking().Where(dd => dd.Status != DriverDispatchStatusEnum.AVAILABLE.ToString()).Select(x => new DriversID { DriverId = x.DriverId }).ToListAsync();
			var query =  _context.Set<Driver>().AsNoTracking().AsEnumerable().Where(x => filteredDispathces.Find(y => y.DriverId == x.id) ==null).ToList();
			return query.Count
```

Got Exceptions? Include both the message and the stack trace

For `dotnet ef` and PMC, share the --verbose output
-->

at System.LazyHelper.Create(LazyThreadSafetyMode mode, Boolean useDefaultConstructor)

   at System.Lazy`1..ctor(Func`1 valueFactory, LazyThreadSafetyMode mode, Boolean useDefaultConstructor)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.StringNodeBase..ctor(ArraySegment`1 bufferedToken, Boolean isStringNode)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.FieldNameNode.Create(ArraySegment`1 bufferedToken)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.JsonTextParser.ParsePropertyNode(IJsonReader jsonTextReader)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.JsonTextParser.ParseObjectNode(IJsonReader jsonTextReader)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.JsonTextParser.ParseNode(IJsonReader jsonTextReader)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.JsonTextParser.ParsePropertyNode(IJsonReader jsonTextReader)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.JsonTextParser.ParseObjectNode(IJsonReader jsonTextReader)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.JsonTextParser.ParseNode(IJsonReader jsonTextReader)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.JsonTextParser.ParseArrayNode(IJsonReader jsonTextReader)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.JsonTextParser.ParseNode(IJsonReader jsonTextReader)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.JsonTextParser.ParsePropertyNode(IJsonReader jsonTextReader)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.JsonTextParser.ParseObjectNode(IJsonReader jsonTextReader)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.JsonTextParser.ParseNode(IJsonReader jsonTextReader)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.JsonTextParser.Parse(IJsonReader jsonTextReader)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator..ctor(Byte[] buffer, Boolean skipValidation)

   at Microsoft.Azure.Cosmos.Json.JsonNavigator.Create(Byte[] buffer, JsonStringDictionary jsonStringDictionary, Boolean skipValidation)

   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElementSerializer.ToCosmosElements(MemoryStream memoryStream, ResourceType resourceType, CosmosSerializationFormatOptions cosmosSerializationOptions)

   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.GetCosmosElementResponse(QueryRequestOptions requestOptions, ResourceType resourceType, ResponseMessage cosmosResponseMessage)

   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.ExecuteItemQueryAsync[RequestOptionType](Uri resourceUri, ResourceType resourceType, OperationType operationType, RequestOptionType requestOptions, SqlQuerySpec sqlQuerySpec, String continuationToken, PartitionKeyRangeIdentity partitionKeyRange, Boolean isContinuationExpected, Int32 pageSize, CancellationToken cancellationToken)

   at Microsoft.Azure.Cosmos.Query.ItemProducer.BufferMoreDocumentsAsync(CancellationToken token)

   at Microsoft.Azure.Cosmos.Query.ItemProducer.BufferMoreIfEmptyAsync(CancellationToken token)

   at Microsoft.Azure.Cosmos.Query.ItemProducer.TryMoveNextPageAsync(CancellationToken token)

   at Microsoft.Azure.Cosmos.Query.ItemProducer.MoveNextAsyncImplementationAsync(CancellationToken token)

   at Microsoft.Azure.Cosmos.Query.ItemProducer.MoveNextAsync(CancellationToken token)

   at Microsoft.Azure.Cosmos.Query.ItemProducerTree.TryMoveNextAsyncImplementationAsync(CancellationToken token)

   at Microsoft.Azure.Cosmos.Query.ItemProducerTree.ExecuteWithSplitProofingAsync(Func`2 function, Boolean functionNeedsBeReexecuted, CancellationToken cancellationToken)

   at Microsoft.Azure.Cosmos.Query.ItemProducerTree.MoveNextAsync(CancellationToken token)

   at Microsoft.Azure.Cosmos.Query.CosmosCrossPartitionQueryExecutionContext.MoveNextHelperAsync(ItemProducerTree itemProducerTree, CancellationToken cancellationToken)

   at Microsoft.Azure.Cosmos.Query.CosmosParallelItemQueryExecutionContext.InternalDrainAsync(Int32 maxElements, CancellationToken cancellationToken)

   at Microsoft.Azure.Cosmos.Query.CosmosCrossPartitionQueryExecutionContext.DrainAsync(Int32 maxElements, CancellationToken cancellationToken)

   at Microsoft.Azure.Cosmos.Query.PipelinedDocumentQueryExecutionContext.ExecuteNextAsync(CancellationToken token)

   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.ExecuteNextAsync(CancellationToken cancellationToken)

   at Microsoft.Azure.Cosmos.Query.QueryIterator.ReadNextAsync(CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal.CosmosClientWrapper.DocumentAsyncEnumerable.AsyncEnumerator.MoveNextAsync()

   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)

   at DfxDispatch.Infrastructure.Repositories.MoveRepository.GetMovesByStatusEFCore3(String moveStatus) in C:\Projects\EFCore_project\DfxDispatch\DfxDispatch.Infrastructure\Repositories\MoveRepository.cs:line 139

   at DfxDispatch.CQRS.Queries.GetMetricsQueryHandler.Handle(GetMetricsQuery request, CancellationToken cancellationToken) in C:\Projects\EFCore_project\DfxDispatch\DfxDispatch.CQRS\Queries\GetMetricsQueryHandler.cs:line 57

   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)

   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)

   at DfxDispatch.FunctionApp.MetricsFunction.Run(HttpRequest req, ILogger log) in C:\Projects\EFCore_project\DfxDispatch\DfxDispatch.FunctionApp\MetricsFunction.cs:line 33

### Further technical details

EF Core version: 3.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.cosmos)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by AndriySvyryd** [comment] 2020-01-23 20:52
@rameshmummidi30 We would need more information to be able to diagnose this. At least the model and query being run, ideally a small runnable project that shows the issue when deployed.

**Comment by ajcvickers** [comment] 2020-01-31 16:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:07 UTC
Labels: closed-could-not-reproduce, customer-reported
