### ISSUE TITLE
[Regression] Primary key max length isn't propagated to owned entity shadow foreign keys

### ISSUE THREAD

**Issue by Neme12** [dotnet/efcore#22624] opened 2020-09-20 16:20 UTC
In EF Core 3.1, I have an owned entity where the owner entity has a primary key which contains a fixed-length string column. When I upgrade EF Core to 5, the app stops working because it seems that the auto-generated shadow foreign key column for the owned entity doesn't have the proper max length anymore.

### Steps to reproduce

Run this program with EF Core 3.1. Everything works as expected:

``` c#
using Microsoft.EntityFrameworkCore;
using System;

namespace EfCoreTest
{
    sealed class Language
    {
        public string IsoCode { get; set; }
        public UserAction Created { get; set; }
    }

    sealed class UserAction
    {
        public DateTime Time { get; set; }
    }

    sealed class ApplicationDbContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=aspnet-WebApplication-6E483A89-BEE6-4A76-96CC-CEB276E5E112;Trusted_Connection=True;MultipleActiveResultSets=true");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Language>().HasKey(c => c.IsoCode);
            modelBuilder.Entity<Language>().Property(x => x.IsoCode).IsRequired().HasMaxLength(2).IsFixedLength();
            modelBuilder.Entity<Language>().OwnsOne(x => x.Created);
        }
    }

    static class Program
    {
        static void Main()
        {
            using (var context = new ApplicationDbContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
            }
        }
    }
}
```

However after updating to 5.0.0-rc.1.20451.13, I get an exception in the call to `EnsureDeleted`:
> System.InvalidOperationException: ''Language.IsoCode' and 'UserAction.LanguageIsoCode' are both mapped to column 'IsoCode' in 'Language' but are configured to use different max lengths ('2' and '').'

Luckily I found a workaround:
```c#
            modelBuilder.Entity<Language>().OwnsOne(x => x.Created, x =>
            {
                x.Property("LanguageIsoCode").HasMaxLength(2);
            });
```

### Further technical details

EF Core version: 5.0.0-rc.1.20451.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 Version 1909
IDE: Visual Studio 2019 16.8.0 Preview 3.0

**Comment by ajcvickers** [comment] 2020-09-20 19:21
Verified that this is fixed in the latest [daily build](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md).

**Comment by ajcvickers** [comment] 2020-09-21 15:34
Duplicate of #22387

**Closed** 2022-10-16 18:41 UTC
Labels: customer-reported
