### ISSUE TITLE
Order by with Projection generates wrong SQL and breaks pagination

### ISSUE THREAD

**Issue by rrdlpl** [dotnet/efcore#8521] opened 2017-05-19 21:05 UTC
The following query in linQ, which I want to order only the Organization status and code, is adding an extra order by the navigation properties of the WebServer, DistrictServer, GlobalServer and GeoEventServer.

```
Enumerable<OrganizationTableDto> content = context.Organization
                .OrderBy(o=> o.Status)
                .ThenBy(o => o.Code)
                .Skip((pagination.PageNumber - 1) * pagination.PageSize)
                .Take(pagination.PageSize)
                .Select(o => new OrganizationTableDto
                {
                    Code = o.Code,
                    Name = o.Name,
                    Status = o.Status,
                    WebServer =  o.WebServer,
                    DistrictServer = o.DistrictServer,o.DistrictServer.Name,
                    GlobalServer = o.GlobalServer,
                    GeoeventServer = o.GeoeventServer,o.GeoeventServer.Name,
                    LastPublishSummary = o.Publishes.OrderByDescending(p => p.Created).Select(p => p.Summary).FirstOrDefault()
                })
                .ToList();
```

My Model: 

```
public class Organization : AuditBaseModel
{
        private string _code = "";
        public Organization()
        {
            //Default type
            Type = DeploymentType.Cloud;
            Status = OrganizationStatus.Draft;
        } 
        public string Code
        {
            get { return _code.ToUpper(); }
            set { _code = value.ToUpper(); }
        }
     
        public string Name { get; set; }       
        public OrganizationStatus Status { get; set; }
        public string Extent { get; set; }       
        public string TimeZone { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }        
        public Server WebServer { get; set; }
        public Guid? WebServerId { get; set; }
        public Server GlobalServer { get; set; }       
        public Guid? GlobalServerId { get; set; }        
        public Server DistrictServer { get; set; }
        public Guid? DistrictServerId { get; set; }
        public Server GeoeventServer { get; set; }
        public Guid? GeoeventServerId { get; set; }       
        public ICollection<Publish> Publishes { get; set; }
}

public enum OrganizationStatus: byte
{
        Draft,
        Release,
        Publishing,
        Update
 }
	
public class Server : AuditBaseModel
{
        public string Name { get; set; }
        public ServerType Type { get; set; }
        public string DataBaseInstance { get; set; }        
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Url { get; set; }
        public string AlternativeUrl { get; set; }
        public bool Active { get; set; }
}
	
public class Publish: AuditBaseModel
{
        public Guid OrganizationId { get; set; }
        public Organization Organization { get; set; }
        public string Summary { get; set; }
}
	
	
public class AuditBaseModel : BaseModel
 {    
        [Required]
        [Column(nameof(Created), Order = 96)]
        public DateTime Created { get; set; }
        [Required]
        [Column(nameof(CreatedBy), Order = 97, TypeName = "varchar(50)")]
        public string CreatedBy { get; set; }
        [Column(nameof(Modified), Order = 98)]
        public DateTime? Modified { get; set; }
        [Column(nameof(ModifiedBy), Order = 99, TypeName = "varchar(50)")]
        public string ModifiedBy { get; set; }
 }
	
public abstract class BaseModel
{
   protected BaseModel()
   {
       Id = Guid.NewGuid();
   }       
     public Guid Id { get; set; }  
}
```
The Dto I'm returning:

```
public class OrganizationTableDto
{
       
        public string Code { get; set; }
        public string Name { get; set; }        
        public OrganizationStatus Status { get; set; }
        public Server WebServer { get; set; }       
        public Server GlobalServer { get; set; }
        public Server DistrictServer { get; set; }
        public Server GeoeventServer { get; set; }
        public bool HasPublishErrors => LastPublishSummary != null && LastPublishSummary.Contains("\"state\":\"error\"");
        public string LastPublishSummary { get; set; }        
 }
```
Generated Query:

```
SELECT [o.GeoeventServer].[Id],
       [o.GeoeventServer].[Active],
       [o.GeoeventServer].[AlternativeUrl],
       [o.GeoeventServer].[Created],
       [o.GeoeventServer].[CreatedBy],
       [o.GeoeventServer].[DataBaseInstance],
       [o.GeoeventServer].[Modified],
       [o.GeoeventServer].[ModifiedBy],
       [o.GeoeventServer].[Name],
       [o.GeoeventServer].[Password],
       [o.GeoeventServer].[Type],
       [o.GeoeventServer].[Url],
       [o.GeoeventServer].[UserName],
       [o.GlobalServer].[Id],
       [o.GlobalServer].[Active],
       [o.GlobalServer].[AlternativeUrl],
       [o.GlobalServer].[Created],
       [o.GlobalServer].[CreatedBy],
       [o.GlobalServer].[DataBaseInstance],
       [o.GlobalServer].[Modified],
       [o.GlobalServer].[ModifiedBy],
       [o.GlobalServer].[Name],
       [o.GlobalServer].[Password],
       [o.GlobalServer].[Type],
       [o.GlobalServer].[Url],
       [o.GlobalServer].[UserName],
       [o.DistrictServer].[Id],
       [o.DistrictServer].[Active],
       [o.DistrictServer].[AlternativeUrl],
       [o.DistrictServer].[Created],
       [o.DistrictServer].[CreatedBy],
       [o.DistrictServer].[DataBaseInstance],
       [o.DistrictServer].[Modified],
       [o.DistrictServer].[ModifiedBy],
       [o.DistrictServer].[Name],
       [o.DistrictServer].[Password],
       [o.DistrictServer].[Type],
       [o.DistrictServer].[Url],
       [o.DistrictServer].[UserName],
       [o.WebServer].[Id],
       [o.WebServer].[Active],
       [o.WebServer].[AlternativeUrl],
       [o.WebServer].[Created],
       [o.WebServer].[CreatedBy],
       [o.WebServer].[DataBaseInstance],
       [o.WebServer].[Modified],
       [o.WebServer].[ModifiedBy],
       [o.WebServer].[Name],
       [o.WebServer].[Password],
       [o.WebServer].[Type],
       [o.WebServer].[Url],
       [o.WebServer].[UserName],
       [t].[Code],
       [t].[Name],
       [t].[Status],
  (SELECT TOP(1) [p].[Summary]
   FROM [Publish] AS [p]
   WHERE [t].[Id] = [p].[OrganizationId]
   ORDER BY [p].[Created] DESC)
FROM
  (SELECT [o0].*
   FROM [Organizations] AS [o0]
   ORDER BY [o0].[Status],
            [o0].[Code]
   OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY) AS [t]
LEFT JOIN [Servers] AS [o.GeoeventServer] ON [t].[GeoeventServerId] = [o.GeoeventServer].[Id]
LEFT JOIN [Servers] AS [o.GlobalServer] ON [t].[GlobalServerId] = [o.GlobalServer].[Id]
LEFT JOIN [Servers] AS [o.DistrictServer] ON [t].[DistrictServerId] = [o.DistrictServer].[Id]
LEFT JOIN [Servers] AS [o.WebServer] ON [t].[WebServerId] = [o.WebServer].[Id]
ORDER BY [t].[GeoeventServerId],
         [t].[GlobalServerId],
         [t].[DistrictServerId],
         [t].[WebServerId]
```
**Expected Result** 
It shouldn't add that order by at the end because is breaking the pagination. 

This seems to be happening in EF6 too. 
http://stackoverflow.com/questions/25504754/prevent-entity-framework-adding-order-by-when-using-include
http://stackoverflow.com/questions/27508767/how-can-i-avoid-the-entity-framework-6-add-an-order-by-in-the-generated-query

### Further technical details
EF Core version: 1.1.2
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Microsoft Visual Studio Enterprise 2017 Version 15.1 (26403.7) Release

**Comment by smitpatel** [comment] 2017-05-19 21:51
dupe of #6736 
In past for query like above (navigations expanded in projection causing left join), due to materialization and various other factors, we had to evaluate each projection one by one, (N+1 queries) To allow that streaming, we add order by. due to #6736 additional order by caused user specified ordering to get ignored.

#6736 is fixed in 2.0.0-preview1 release. Along with that there are various optimizations done around left join queries.
This is the query generated in current nightly builds
```
SELECT [o.GeoeventServer].[Id], [o.GeoeventServer].[Active], [o.GeoeventServer].[AlternativeUrl], [o.GeoeventServer].[Created], [o.GeoeventServer].[CreatedBy], [o.GeoeventServer].[DataBaseInstance], [o.GeoeventServer].[Modified], [o.GeoeventServer].[ModifiedBy], [o.GeoeventServer].[Name], [o.GeoeventServer].[Password], [o.GeoeventServer].[Url], [o.GeoeventServer].[UserName], [o.GlobalServer].[Id], [o.GlobalServer].[Active], [o.GlobalServer].[AlternativeUrl], [o.GlobalServer].[Created], [o.GlobalServer].[CreatedBy], [o.GlobalServer].[DataBaseInstance], [o.GlobalServer].[Modified], [o.GlobalServer].[ModifiedBy], [o.GlobalServer].[Name], [o.GlobalServer].[Password], [o.GlobalServer].[Url], [o.GlobalServer].[UserName], [o.DistrictServer].[Id], [o.DistrictServer].[Active], [o.DistrictServer].[AlternativeUrl], [o.DistrictServer].[Created], [o.DistrictServer].[CreatedBy], [o.DistrictServer].[DataBaseInstance], [o.DistrictServer].[Modified], [o.DistrictServer].[ModifiedBy], [o.DistrictServer].[Name], [o.DistrictServer].[Password], [o.DistrictServer].[Url], [o.DistrictServer].[UserName], [o.WebServer].[Id], [o.WebServer].[Active], [o.WebServer].[AlternativeUrl], [o.WebServer].[Created], [o.WebServer].[CreatedBy], [o.WebServer].[DataBaseInstance], [o.WebServer].[Modified], [o.WebServer].[ModifiedBy], [o.WebServer].[Name], [o.WebServer].[Password], [o.WebServer].[Url], [o.WebServer].[UserName], [o].[Code], [o].[Name] AS [Name0], [o].[Status], (
          SELECT TOP(1) [p].[Summary]
          FROM [Publish] AS [p]
          WHERE [o].[Id] = [p].[OrganizationId]
          ORDER BY [p].[Created] DESC
      ) AS [LastPublishSummary]
      FROM [Organization] AS [o]
      LEFT JOIN [Server] AS [o.GeoeventServer] ON [o].[GeoeventServerId] = [o.GeoeventServer].[Id]
      LEFT JOIN [Server] AS [o.GlobalServer] ON [o].[GlobalServerId] = [o.GlobalServer].[Id]
      LEFT JOIN [Server] AS [o.DistrictServer] ON [o].[DistrictServerId] = [o.DistrictServer].[Id]
      LEFT JOIN [Server] AS [o.WebServer] ON [o].[WebServerId] = [o.WebServer].[Id]
      ORDER BY [o].[Status], [o].[Code]
      OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
```
It avoids N+1 and preserve ordering.

**Closed** 2022-10-16 11:05 UTC
