### ISSUE TITLE
AddRange doesn't add all objects in collection

### ISSUE THREAD

**Issue by D4rkTiger** [dotnet/efcore#13136] opened 2018-08-28 07:45 UTC
Hello,

I've translation tables where I put some labels but when I want to add multiple objects to table with **DbSet.AddRange** method, some objects are omitted or replaced or removed.

## The issue
The problem is when I want to add _SystemLabels_ for **Languages** group, it only add English item. And if I debug the code and re-add item it will be insert in database and keep in LocalView of DbSet.

I don't understand why AddRange doesn't keep all my items.
**PS/** The case can be reproduced for other group like **Civilities**, **Genders**, **Roles**, **Roles_Description**

As you can see on these printscreens

![debug_1](https://user-images.githubusercontent.com/1905547/44708057-6c1e0580-aaa6-11e8-9da6-0caf8668655a.png)
![debug_2](https://user-images.githubusercontent.com/1905547/44708060-6f18f600-aaa6-11e8-957d-75e36d53cbfb.png)
![debug_3](https://user-images.githubusercontent.com/1905547/44708062-717b5000-aaa6-11e8-8477-8b0cb6f998ae.png)
![debug_4](https://user-images.githubusercontent.com/1905547/44708133-9f609480-aaa6-11e8-9efa-2c77e33e4237.png)

On the last printscreen, you can see for others groups, there is some missing items (cf. _ApplicationDbInitializer.cs_ file below)

### _UserInfos_ table

```sql
CREATE TABLE [dbo].[UserInfos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](max) NULL,
	[LastName] [nvarchar](max) NULL,
	[CivilityId] [int] NULL,
	[GenderId] [int] NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[CreatedById] [int] NULL,
	[UpdatedAt] [datetime2](7) NULL,
	[UpdatedById] [int] NULL,
	[DeletedAt] [datetime2](7) NULL,
	[DeletedById] [int] NULL,
	[IsAnonymized] [bit] NOT NULL,
	[Enabled] [bit] NOT NULL,
 CONSTRAINT [PK_UserInfos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
GO

ALTER TABLE [dbo].[UserInfos]  WITH CHECK ADD  CONSTRAINT [FK_UserInfos_UserInfos_CreatedById] FOREIGN KEY([CreatedById])
REFERENCES [dbo].[UserInfos] ([Id])
GO

ALTER TABLE [dbo].[UserInfos] CHECK CONSTRAINT [FK_UserInfos_UserInfos_CreatedById]
GO

ALTER TABLE [dbo].[UserInfos]  WITH CHECK ADD  CONSTRAINT [FK_UserInfos_UserInfos_DeletedById] FOREIGN KEY([DeletedById])
REFERENCES [dbo].[UserInfos] ([Id])
GO

ALTER TABLE [dbo].[UserInfos] CHECK CONSTRAINT [FK_UserInfos_UserInfos_DeletedById]
GO

ALTER TABLE [dbo].[UserInfos]  WITH CHECK ADD  CONSTRAINT [FK_UserInfos_UserInfos_UpdatedById] FOREIGN KEY([UpdatedById])
REFERENCES [dbo].[UserInfos] ([Id])
GO

ALTER TABLE [dbo].[UserInfos] CHECK CONSTRAINT [FK_UserInfos_UserInfos_UpdatedById]
GO
```

### _SystemLabels_ table

```sql
CREATE TABLE [dbo].[SystemLabels](
	[Id] [int] NOT NULL,
	[SystemLanguageId] [int] NOT NULL,
	[Label] [nvarchar](max) NULL,
	[Keywords] [nvarchar](max) NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[CreatedById] [int] NOT NULL,
	[UpdatedAt] [datetime2](7) NULL,
	[UpdatedById] [int] NULL,
	[Group] [nvarchar](max) NULL,
CONSTRAINT [PK_SystemLabels] PRIMARY KEY CLUSTERED 
(
	[Id] ASC,
	[SystemLanguageId] ASC
)
GO

ALTER TABLE [dbo].[SystemLabels]  WITH CHECK ADD  CONSTRAINT [FK_SystemLabels_SystemLanguages_SystemLanguageId] FOREIGN KEY([SystemLanguageId])
REFERENCES [dbo].[SystemLanguages] ([Id])
GO

ALTER TABLE [dbo].[SystemLabels] CHECK CONSTRAINT [FK_SystemLabels_SystemLanguages_SystemLanguageId]
GO

ALTER TABLE [dbo].[SystemLabels]  WITH CHECK ADD  CONSTRAINT [FK_SystemLabels_UserInfos_CreatedById] FOREIGN KEY([CreatedById])
REFERENCES [dbo].[UserInfos] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[SystemLabels] CHECK CONSTRAINT [FK_SystemLabels_UserInfos_CreatedById]
GO

ALTER TABLE [dbo].[SystemLabels]  WITH CHECK ADD  CONSTRAINT [FK_SystemLabels_UserInfos_UpdatedById] FOREIGN KEY([UpdatedById])
REFERENCES [dbo].[UserInfos] ([Id])
GO

ALTER TABLE [dbo].[SystemLabels] CHECK CONSTRAINT [FK_SystemLabels_UserInfos_UpdatedById]
GO
```

### _SystemLanguages_ table

```sql
CREATE TABLE [dbo].[SystemLanguages](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SystemLabelId] [int] NULL,
	[Code] [nvarchar](max) NOT NULL,
	[IsoCode] [nvarchar](max) NOT NULL,
	[Locale] [nvarchar](max) NULL,
	[IETF] [nvarchar](max) NULL,
	[LCID] [nvarchar](max) NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[CreatedById] [int] NOT NULL,
	[UpdatedAt] [datetime2](7) NULL,
	[UpdatedById] [int] NULL,
	[StateChangedAt] [datetime2](7) NULL,
	[StateChangedById] [int] NULL,
	[Enabled] [bit] NOT NULL,
 CONSTRAINT [PK_SystemLanguages] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)

GO

ALTER TABLE [dbo].[SystemLanguages]  WITH CHECK ADD  CONSTRAINT [FK_SystemLanguages_UserInfos_CreatedById] FOREIGN KEY([CreatedById])
REFERENCES [dbo].[UserInfos] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[SystemLanguages] CHECK CONSTRAINT [FK_SystemLanguages_UserInfos_CreatedById]
GO

ALTER TABLE [dbo].[SystemLanguages]  WITH CHECK ADD  CONSTRAINT [FK_SystemLanguages_UserInfos_StateChangedById] FOREIGN KEY([StateChangedById])
REFERENCES [dbo].[UserInfos] ([Id])
GO

ALTER TABLE [dbo].[SystemLanguages] CHECK CONSTRAINT [FK_SystemLanguages_UserInfos_StateChangedById]
GO

ALTER TABLE [dbo].[SystemLanguages]  WITH CHECK ADD  CONSTRAINT [FK_SystemLanguages_UserInfos_UpdatedById] FOREIGN KEY([UpdatedById])
REFERENCES [dbo].[UserInfos] ([Id])
GO

ALTER TABLE [dbo].[SystemLanguages] CHECK CONSTRAINT [FK_SystemLanguages_UserInfos_UpdatedById]
GO
```

I write a DatabaseInitializer class to add data at the initialization of the application

### _Program.cs_ file
```c#
public class Program
    {
        public static void Main(string[] args)
        {
            var host = CreateWebHostBuilder(args).Build();

            using (var scope = host.Services.CreateScope())
            {
                var services = scope.ServiceProvider;
                try
                {
                    var context = services.GetRequiredService<ApplicationDbContext>();
                    ApplicationDbInitializer.Initialize(context);
                }
                catch (Exception ex)
                {
                    var logger = services.GetRequiredService<ILogger<Program>>();
                    logger.LogError(ex, "An error occurred while seeding the database.");
                }
            }

            host.Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args).UseStartup<Startup>();
    }
```

### _ApplicationDbInitializer.cs_ file

```c#
public static class ApplicationDbInitializer
    {
        public static void Initialize(ApplicationDbContext context)
        {
            context.Database.EnsureCreated();

            if (!context.UserInfos.Any()) {
                using (var scope = context.Database.BeginTransaction())
                {
                    try
                    {
                        context.Database.ExecuteSqlCommand("SET IDENTITY_INSERT [dbo].[UserInfos] ON");

                        context.Database.ExecuteSqlCommand("INSERT INTO [dbo].[UserInfos] (Id, CreatedAt, FirstName, LastName, [Enabled], CreatedById, IsAnonymized) VALUES (-9000, GETUTCDATE(), 'Robot User', 'Creator', 0, -9000, 0)");
                        context.Database.ExecuteSqlCommand("INSERT INTO [dbo].[UserInfos] (Id, CreatedAt, FirstName, LastName, [Enabled], CreatedById, IsAnonymized) VALUES (-8000, GETUTCDATE(), 'Robot User', 'Initiator', 0, -9000, 0)");
                        context.Database.ExecuteSqlCommand("INSERT INTO [dbo].[UserInfos] (Id, CreatedAt, FirstName, LastName, [Enabled], CreatedById, IsAnonymized) VALUES (-7000, GETUTCDATE(), 'Robot User', 'Jobber', 0, -9000, 0)");
                        context.Database.ExecuteSqlCommand("INSERT INTO [dbo].[UserInfos] (Id, CreatedAt, FirstName, LastName, [Enabled], CreatedById, IsAnonymized) VALUES (-10000, GETUTCDATE(), 'Administrateur', 'ORMA', 1, -9000, 0)");
                        context.Database.ExecuteSqlCommand("INSERT INTO [dbo].[UserInfos] (Id, CreatedAt, FirstName, LastName, [Enabled], CreatedById, IsAnonymized) VALUES (-11000, GETUTCDATE(), 'God', 'ORMA', 1, -9000, 0)");

                        context.Database.ExecuteSqlCommand("SET IDENTITY_INSERT [dbo].[UserInfos] OFF");
                        scope.Commit();
                    }
                    catch
                    {
                        scope.Rollback();
                        throw;
                    }
                }
            }

            if (!context.SystemLanguages.Any())
            {
                context.SystemLanguages.AddRange(
                    new SystemLanguage { Code = "fr", IsoCode = "fr", Locale = "fr-FR", CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Enabled = true },
                    new SystemLanguage { Code = "en", IsoCode = "en", Locale = "en-US", CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Enabled = true }
                );
                context.SaveChanges();
            }

            var frenchLanguage = context.SystemLanguages.First(x => x.Code == "fr");
            var englishLanguage = context.SystemLanguages.First(x => x.Code == "en");

            var nextLabelId = 0;
            
            if (!context.SystemLabels.Any(u => u.Group == "Languages"))
            {
                context.SystemLabels.AddRange(
                    new SystemLabel { Id = nextLabelId + 1, SystemLanguageId = frenchLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Languages", Label = "Français" },
                    new SystemLabel { Id = nextLabelId + 1, SystemLanguageId = englishLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Languages", Label = "French" },
                    new SystemLabel { Id = nextLabelId + 2, SystemLanguageId = frenchLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Languages", Label = "Anglais" },
                    new SystemLabel { Id = nextLabelId + 2, SystemLanguageId = englishLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Languages", Label = "English" }
                );
                context.SaveChanges();

                frenchLanguage.SystemLabelId = nextLabelId + 1;
                englishLanguage.SystemLabelId = nextLabelId + 2;
                context.SaveChanges();
            }
            
            if (!context.SystemLabels.Any(u => u.Group == "Civilities"))
            {
                context.SystemLabels.AddRange(
                    new SystemLabel { Id = nextLabelId + 3, SystemLanguageId = frenchLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Civilities", Label = "M." },
                    new SystemLabel { Id = nextLabelId + 3, SystemLanguageId = englishLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Civilities", Label = "Mr." },
                    new SystemLabel { Id = nextLabelId + 4, SystemLanguageId = frenchLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Civilities", Label = "Mme" },
                    new SystemLabel { Id = nextLabelId + 4, SystemLanguageId = englishLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Civilities", Label = "Mrs." },
                    new SystemLabel { Id = nextLabelId + 5, SystemLanguageId = frenchLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Civilities", Label = "Mlle" },
                    new SystemLabel { Id = nextLabelId + 5, SystemLanguageId = englishLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Civilities", Label = "Miss" }
                );
                context.SaveChanges();
            }

            if (!context.SystemLabels.Any(u => u.Group == "Genders"))
            {
                context.SystemLabels.AddRange(
                    new SystemLabel { Id = nextLabelId + 6, SystemLanguageId = frenchLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Genders", Label = "Homme" },
                    new SystemLabel { Id = nextLabelId + 6, SystemLanguageId = englishLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Genders", Label = "Male" },
                    new SystemLabel { Id = nextLabelId + 7, SystemLanguageId = frenchLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Genders", Label = "Femme" },
                    new SystemLabel { Id = nextLabelId + 7, SystemLanguageId = englishLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Genders", Label = "Female" },
                    new SystemLabel { Id = nextLabelId + 8, SystemLanguageId = frenchLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Genders", Label = "Non défini" },
                    new SystemLabel { Id = nextLabelId + 8, SystemLanguageId = englishLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Genders", Label = "Undefined" }
                );
                context.SaveChanges();
            }

            if (!context.SystemLabels.Any(u => u.Group == "Roles"))
            {
                context.SystemLabels.AddRange(
                    new SystemLabel { Id = nextLabelId + 9, SystemLanguageId = frenchLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Roles", Label = "Administrateur" },
                    new SystemLabel { Id = nextLabelId + 9, SystemLanguageId = englishLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Roles", Label = "Administrator" },
                    new SystemLabel { Id = nextLabelId + 10, SystemLanguageId = frenchLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Roles", Label = "Super-Administrateur" },
                    new SystemLabel { Id = nextLabelId + 10, SystemLanguageId = englishLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Roles", Label = "Super-Admin" },
                    new SystemLabel { Id = nextLabelId + 11, SystemLanguageId = frenchLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Roles", Label = "Utilisateur" },
                    new SystemLabel { Id = nextLabelId + 11, SystemLanguageId = englishLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Roles", Label = "User" }
                );
                context.SaveChanges();
            }

            if (!context.SystemLabels.Any(u => u.Group == "Roles_Description"))
            {
                context.SystemLabels.AddRange(
                    new SystemLabel { Id = nextLabelId + 12, SystemLanguageId = frenchLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Roles_Description", Label = "Administrateur de l'application" },
                    new SystemLabel { Id = nextLabelId + 12, SystemLanguageId = englishLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Roles_Description", Label = "Administrator of the application" },
                    new SystemLabel { Id = nextLabelId + 13, SystemLanguageId = frenchLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Roles_Description", Label = "Super-Administrateur de l'application" },
                    new SystemLabel { Id = nextLabelId + 13, SystemLanguageId = englishLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Roles_Description", Label = "Super-Admin of the application" },
                    new SystemLabel { Id = nextLabelId + 14, SystemLanguageId = frenchLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Roles_Description", Label = "Utilisateur" },
                    new SystemLabel { Id = nextLabelId + 14, SystemLanguageId = englishLanguage.Id, CreatedAt = DateTime.UtcNow, CreatedById = UserInfo.InitiatorId, Group = "Roles_Description", Label = "User" }
                );
                context.SaveChanges();
            }
        }
    }
```

Please found the rules applied for tables and also C# classes of each items

### _OnModelCreating_ method

```c#
protected override void OnModelCreating(ModelBuilder builder)
{
	base.OnModelCreating(builder);

	builder.Entity<UserInfo>(b =>
	{
		b.ToTable("UserInfos", "dbo");
		b.HasOne(u => u.CreatedBy).WithOne((Expression<Func<UserInfo, UserInfo>>)null).HasForeignKey<UserInfo>(u => u.CreatedById);
		b.HasOne(u => u.UpdatedBy).WithOne((Expression<Func<UserInfo, UserInfo>>)null).HasForeignKey<UserInfo>(u => u.UpdatedById);
		b.HasOne(u => u.DeletedBy).WithOne((Expression<Func<UserInfo, UserInfo>>)null).HasForeignKey<UserInfo>(u => u.DeletedById);
		b.HasIndex(u => u.CreatedById).IsUnique(false);
		b.HasIndex(u => u.UpdatedById).IsUnique(false);
		b.HasIndex(u => u.DeletedById).IsUnique(false);
	});

	builder.Entity<SystemLabel>(b =>
	{
		b.ToTable("SystemLabels", "dbo");
		b.HasKey(u => new { u.Id, u.SystemLanguageId });
		b.HasOne(u => u.SystemLanguage).WithOne((Expression<Func<SystemLanguage, SystemLabel>>)null).HasForeignKey<SystemLabel>(u => u.SystemLanguageId).OnDelete(DeleteBehavior.Restrict);
		b.HasOne(u => u.CreatedBy).WithOne((Expression<Func<UserInfo, SystemLabel>>)null).HasForeignKey<SystemLabel>(u => u.CreatedById);
		b.HasOne(u => u.UpdatedBy).WithOne((Expression<Func<UserInfo, SystemLabel>>)null).HasForeignKey<SystemLabel>(u => u.UpdatedById);
		b.HasIndex(u => u.Id).IsUnique(false);
		b.HasIndex(u => u.SystemLanguageId).IsUnique(false);
		b.HasIndex(u => u.CreatedById).IsUnique(false);
		b.HasIndex(u => u.UpdatedById).IsUnique(false);
	});

	builder.Entity<SystemLanguage>(b =>
	{
		b.ToTable("SystemLanguages", "dbo");
		b.Ignore(u => u.SystemLabel);
		b.HasOne(u => u.CreatedBy).WithOne((Expression<Func<UserInfo, SystemLanguage>>)null).HasForeignKey<SystemLanguage>(u => u.CreatedById);
		b.HasOne(u => u.UpdatedBy).WithOne((Expression<Func<UserInfo, SystemLanguage>>)null).HasForeignKey<SystemLanguage>(u => u.UpdatedById);
		b.HasOne(u => u.StateChangedBy).WithOne((Expression<Func<UserInfo, SystemLanguage>>)null).HasForeignKey<SystemLanguage>(u => u.StateChangedById);
		b.HasIndex(u => u.CreatedById).IsUnique(false);
		b.HasIndex(u => u.UpdatedById).IsUnique(false);
		b.HasIndex(u => u.StateChangedById).IsUnique(false);
	});
}
```

### _UserInfo.cs_ file
```c#
public partial class UserInfo
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public int? CivilityId { get; set; }

        public int? GenderId { get; set; }

        [Required]
        public DateTime CreatedAt { get; set; }

        public int? CreatedById { get; set; }

        public UserInfo CreatedBy { get; set; }

        public DateTime? UpdatedAt { get; set; }

        public int? UpdatedById { get; set; }

        public UserInfo UpdatedBy { get; set; }

        public DateTime? DeletedAt { get; set; }

        public int? DeletedById { get; set; }

        public UserInfo DeletedBy { get; set; }

        public bool IsAnonymized { get; set; }

        public bool Enabled { get; set; }
    }
```

### _SystemLanguage.cs_ file
```c#
public class SystemLanguage
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Id { get; set; }

        public int? SystemLabelId { get; set; }

        public SystemLabel SystemLabel { get; set; }

        [Required]
        public string Code { get; set; }

        [Required]
        public string IsoCode { get; set; }

        public string Locale { get; set; }

        public string IETF { get; set; }

        public string LCID { get; set; }

        [Required]
        public DateTime CreatedAt { get; set; }

        [Required]
        public int CreatedById { get; set; }

        public UserInfo CreatedBy { get; set; }

        public DateTime? UpdatedAt { get; set; }

        public int? UpdatedById { get; set; }

        public UserInfo UpdatedBy { get; set; }

        public DateTime? StateChangedAt { get; set; }

        public int? StateChangedById { get; set; }

        public UserInfo StateChangedBy { get; set; }

        public bool Enabled { get; set; }
    }
```

### _SystemLabel.cs_ file
```c#
public partial class SystemLabel
    {
        public int Id { get; set; }
        
        public int SystemLanguageId { get; set; }

        public SystemLanguage SystemLanguage { get; set; }

        public string Label { get; set; }

        public string Keywords { get; set; }

        [Required]
        public DateTime CreatedAt { get; set; }

        [Required]
        public int CreatedById { get; set; }

        public UserInfo CreatedBy { get; set; }

        public DateTime? UpdatedAt { get; set; }

        public int? UpdatedById { get; set; }

        public UserInfo UpdatedBy { get; set; }

        public string Group { get; set; }
    }
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7
IDE: Visual Studio 2017 Professional 15.8.0

**Comment by ajcvickers** [comment] 2019-11-16 23:58
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:27 UTC
Labels: closed-could-not-reproduce, customer-reported, punted-for-3.0
