### ISSUE TITLE
EF 3.1 not able to understand relationship that worked in 2.2

### ISSUE THREAD

**Issue by mariusGundersen** [dotnet/efcore#19404] opened 2019-12-26 12:43 UTC
I have an existing AspNet Core application that I'm trying to upgrade from 2.2 to 3.1. The project can be found [here](https://github.com/bardarswingclub/MemberService/tree/aspnetcore3.1). I have tried several things, all of them resulting in some error. It seems like it is unable to understand an existing relationship between the following two entities, specifically the `User` property and the `EventSignups` property:

```cs
public class EventSignup
{
    public Guid Id { get; set; }

    public Guid EventId { get; set; }

    public Event Event { get; set; }

    public string UserId { get; set; }

    public MemberUser User { get; set; }

    [Required]
    public DateTime SignedUpAt { get; set; }

    public DanceRole Role { get; set; }

    public string PartnerEmail { get; set; }

    public MemberUser Partner { get; set; }

    public int Priority { get; set; }

    public Status Status { get; set; }

    public string PaymentId { get; set; }

    [ForeignKey(nameof(PaymentId))]
    public Payment Payment { get; set; }

    public ICollection<EventSignupAuditEntry> AuditLog { get; set; } = new List<EventSignupAuditEntry>();

    public ICollection<Presence> Presence { get; set; } = new List<Presence>();

    public ICollection<QuestionAnswer> Answers { get; set; } = new List<QuestionAnswer>();
}


public class MemberUser : IdentityUser
{
    [PersonalData]
    public string FullName { get; set; }

    public ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public ICollection<MemberUserRole> UserRoles { get; set; } = new List<MemberUserRole>();

    public ICollection<EventSignup> EventSignups { get; set; } = new List<EventSignup>();

    public bool ExemptFromTrainingFee { get; set; }

    public bool ExemptFromClassesFee { get; set; }
}
```

### Steps to reproduce

Clone the project to a computer with DotNetCore 3.1 installed and start it up. It will try to run a query but get the following issue: 

```
System.InvalidOperationException: 'Unable to determine the relationship represented by navigation property 'EventSignup.User' of type 'MemberUser'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.'
```

It should be using the `UserId` property as the foreign key, but no matter what I try to do it does not seem to use it, and any migration I attempt seems to add a new column, `MemberUserId`, instead. 

I have tried to call `dotnet ef migrations add UpgradeTo31` just to see if that sorts out the problem, but it does not. It now adds a new column to the database table called `MemberUserId` and it tries to use this column as the foreign key, which will mess up all the existing data already stored in the database. 

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4

**Comment by mariusGundersen** [comment] 2019-12-29 13:42
I managed to reproduce the problem in a much smaller codebase, which you can find here: https://github.com/mariusGundersen/EntityFrameworkUpgradeProblem

How to reproduce:
* Clone the project above
* Run `dotnet ef migrations add UpgradeTo31`

The error returned is this:

```
Unable to determine the relationship represented by navigation property 'EventSignup.User' of type 'MemberUser'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
```

Now, I might try to do what the error tells me to do, and add the following to `OnModelCreating`:

```csharp
                signup
                    .HasOne(s => s.User)
                    .WithMany()
                    .HasForeignKey(s => s.UserId)
                    .HasPrincipalKey(s => s.Id)
                    .IsRequired(false);
```

Unfortunately this results in the following migration file, where a new foreign key is added:

```csharp

    public partial class UpgradeTo31 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "MemberUserId",
                table: "EventSignups",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_EventSignups_MemberUserId",
                table: "EventSignups",
                column: "MemberUserId");

            migrationBuilder.AddForeignKey(
                name: "FK_EventSignups_MemberUsers_MemberUserId",
                table: "EventSignups",
                column: "MemberUserId",
                principalTable: "MemberUsers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_EventSignups_MemberUsers_MemberUserId",
                table: "EventSignups");

            migrationBuilder.DropIndex(
                name: "IX_EventSignups_MemberUserId",
                table: "EventSignups");

            migrationBuilder.DropColumn(
                name: "MemberUserId",
                table: "EventSignups");
        }
```

This is wrong since it there is already a foreign key using the column `UserId`, so this extra foreign key is not necessary.

**Comment by ajcvickers** [comment] 2020-01-02 18:11
@mariusGundersen I'm not sure why this relationship isn't being picked up by convention--I will discuss with the team. However, picking this up by convention would also result in mapping `EventSignups` as the inverse navigation. This means the equivalent explicit configuration is something like:

```C#
signup
    .HasOne(s => s.User)
    .WithMany(e => e.EventSignups)
    .HasForeignKey(s => s.UserId)
    .HasPrincipalKey(s => s.Id)
    .IsRequired(false);
```
If `EventSignups` is not mapped in this relationship, as is the case with your mapping above, then EF creates a new relationship for this navigation property, which results in the additional FK.

**Comment by AndriySvyryd** [comment] 2020-01-22 19:36
Duplicate of https://github.com/dotnet/efcore/issues/18388

**Closed** 2022-10-16 18:03 UTC
Labels: customer-reported
