### ISSUE TITLE
Bug when used with Npgsql.EntityFrameworkCore.PostgreSQL

### ISSUE THREAD

**Issue by tanekim88** [dotnet/efcore#23822] opened 2021-01-06 09:03 UTC
How to reproduce: Create a simple Server project that uses ApplicationDbContext.
Add a DbSet with "int" as an id. (It has to be "int" or an error will not occur).

```
class Sample {
  public int Id {get; set; }
}

 public class ApplicationDbContext : DbContext
    {
        public DbSet<Sample> Samples { get; set; }

        public ApplicationDbContext(DbContextOptions options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {

        }
    }
```
Then add this in the startup.cs. (Note: it uses UseSqlServer, not UsePostgres)
```
            services.AddDbContext<ApplicationDbContext>(options =>
                      options.UseSqlServer(
                          configuration.GetConnectionString("DefaultConnection"));
```

Then just install one NuGet package.
"Npgsql.EntityFrameworkCore.PostgreSQL"

But do not use the package inside codes. Just do nothing after installing the package.

Now, try these three commands in order. Then, you will see an error.
dotnet ef migrations add init
dotnet ef migrations add init2
dotnet ef database update

What's expected: The file created from "dotnet ef migrations add init2" command should have empty migration codes.
What's observed: They are filled with some migration codes even if no codes were touched after 
"dotnet ef migrations add init" command
Result: the migration codes generated from "dotnet ef migrations add init2" cause the error.

**Comment by roji** [comment] 2021-01-06 12:24
Can you please post the contents of your init2 migration file? Also, are you referencing both the SqlServer and PostgreSQL providers?

**Comment by tanekim77** [comment] 2021-01-06 17:11
It was filled with something like the following if I remember right: 

```
 migrationBuilder.AlterColumn<int>(
            name: "Id",
            table: "Samples",
            nullable: false,
            oldClrType: typeof(int),
            oldType: "int")
            .Annotation("SqlServer:Identity", "1, 1");
```

And yes, both providers were referenced when the error occured.

**Comment by roji** [comment] 2021-01-06 21:27
Duplicate of https://github.com/dotnet/efcore/issues/23456

**Closed** 2022-10-16 19:17 UTC
Labels: customer-reported
