### ISSUE TITLE
Where Clause not mapped on automatic join?

### ISSUE THREAD

**Issue by markusvt** [dotnet/efcore#6012] opened 2016-07-07 09:01 UTC
### Steps to reproduce

I have to following model: 
`Booking (0..1) ---- (*) BookingPlace`

When I used RC1 and I did the following everything worked as expected:
`StaticServices.getMapper<BookingPlace>().Query.Where(q => q.Booking.Temporary == false).ToList().Select(q => q.BookingId))`

`StaticServices.getMapper<BookingPlace>().Query` just returns the DBSet of the Entity BookingPlace like this:
`public IQueryable<EntityType> Query => DbSet;`

So I just create a normale Query on the BookingPlace table. As I do not use <Include> to include my booking Entity in the query, nothing really should happen (I think that was the expected behaviour when I used that code in RC1)
### The issue

After updating to Core 1.0 the following happens:
1. that `Booking` table is automatically joined in the Query (guess that is a good thing so I do not need to keep track of which tables to include)
2. my Where-Clause disappears from the generated SQL  (that `q.Booking.Temporary == false` isn't mapped at all)

Here is the SQL that was tracked by the SQL Profiler:

```
SELECT [q].[Id], [q].[Bis], [q].[BookingId], [q].[JSON], [q].[PlaceId], [q].[Von], [q.Booking].[Id], [q.Booking].[Bis], [q.Booking].[ContactId], [q.Booking].[Deleted], [q.Booking].[Description], [q.Booking].[HasTime], [q.Booking].[JSON], [q.Booking].[Name], [q.Booking].[Optioniert], [q.Booking].[Optioniert_Date], [q.Booking].[Storniert], [q.Booking].[Storniert_Date], [q.Booking].[Temporary], [q.Booking].[Type], [q.Booking].[Von]
FROM [Booking_BookingPlace] AS [q]
LEFT JOIN [Booking_Booking] AS [q.Booking] ON [q].[BookingId] = [q.Booking].[Id]
ORDER BY [q].[BookingId]
```
1. Also another strange thing: if i Include the Booking Table now manually, in SQL there are 2 Joins of that Booking table
### Further technical details

EF Core version: 1.0.0
Operating system: WIndows 10
Visual Studio version: VS 2015

"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",

**Comment by rowanmiller** [comment] 2016-07-08 23:11
Duplicate of https://github.com/aspnet/EntityFramework/issues/4588

**Closed** 2022-10-16 09:49 UTC
