### ISSUE TITLE
Projections with branching causes sub-fields to not load properly

### ISSUE THREAD

**Issue by cjblomqvist** [dotnet/efcore#34205] opened 2024-07-10 20:44 UTC
Projections with any type of branching (e.g. null coalesce'ing) causes sub-fields to not load properly (generated SQL doesn't include the fields).

Repro below. I expect to Console output to be all true, but that's not the case (as clear by my comments).

I've tested both with EF Core 8.0.0 and latest preview (EF Core 9 preview 6.... something). Same result.

```C#
#nullable enable

using Microsoft.EntityFrameworkCore;

using (var context = new DemoDbContext())
{
  context.Database.EnsureDeleted();
  context.Database.EnsureCreated();

  var c = new C();
  var b2 = new B()
  {
    C = c,
  };
  var a = new A()
  {
    B2 = b2,
  };

  context.Add(a);
  context.SaveChanges();
}

using (var context = new DemoDbContext())
{
  // Doesn't work
  var a1 = context.A.Select(a => new ADto(
    (a.B1 ?? a.B2).Name,
    (a.B1 ?? a.B2).C.Name
  )).First();

  Console.WriteLine(a1.BName == "B Name"); // True
  Console.WriteLine(a1.CName == "C Name"); // False, should be true

  // Works
  var a2 = context.A.Select(a => new ADto(
    a.B1!.Name ?? a.B2.Name,
    a.B1.C.Name ?? a.B2.C.Name
  )).First();

  Console.WriteLine(a2.BName == "B Name"); // True
  Console.WriteLine(a2.CName == "C Name"); // True

  // Doesn't work either
  var a3 = context.A.Select(a => new ADto(
    (a.B1 == null ? a.B2 : a.B1).Name,
    (a.B1 == null ? a.B2 : a.B1).C.Name
  )).First();

  Console.WriteLine(a3.BName == "B Name"); // True
  Console.WriteLine(a3.CName == "C Name"); // False, should be true

  // Works
  var a4 = context.A.Select(a => new ADto(
    a.B1 == null ? a.B2.Name : a.B1.Name,
    a.B1 == null ? a.B2.C.Name : a.B1.C.Name
  )).First();

  Console.WriteLine(a4.BName == "B Name"); // True
  Console.WriteLine(a4.CName == "C Name"); // True
}

public class DemoDbContext : DbContext
{
  public DbSet<A> A { get; set; }

  protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
  {
    optionsBuilder
        .EnableSensitiveDataLogging()
        .UseSqlServer(@"Data Source=(LocalDb)\MSSQLLocalDB;Database=SixOh");
  }
}

public record ADto(string BName, string CName);

public class A
{
  public int Id {  get; set; }
  public B? B1 { get; set; }
  public B B2 { get; set; }

  public A() { }
}

public class B
{
  public int Id { get; set; }
  public string Name { get; set; } = "B Name";
  public C C { get; set; }

  public B() { }
}

public class C
{
  public int Id { get; set; }
  public string Name { get; set; } = "C Name";

  public C() { }
}
```

**Comment by maumar** [comment] 2024-07-10 23:08
dupe of https://github.com/dotnet/efcore/issues/17782

**Closed by maumar** 2024-07-10 23:08 UTC
Labels: customer-reported

**Comment by maumar** [comment] 2024-07-10 23:11
workaround is to manually include the navigations before the coalesce/conditional projection:

```cs
            var a1 = context.A.Include(x => x.B1!.C).Include(x => x.B2.C).Select(a => new ADto(
              (a.B1 ?? a.B2).Name,
              (a.B1 ?? a.B2).C.Name
            )).First();
```
