### ISSUE TITLE
Net6.0, Core Web, there is a critical error when the right table does not have a left table Id!

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#27305] opened 2022-01-28 09:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net60，Core-Web，当右表没有左表Id时，存在严重错误！/1591534)._

---
[severity:I'm unable to use this version]
VS version: Microsoft Visual Studio Community 2022 (64-bit)  
Database: MySQL 8.0.27
Project: Net 6.0, Asp.Net Core Web
Database Connection Library: Pomelo.EntityFrameworkCore.MySql

TWeb class:
```
    public partial class TWeb
    {
        public int Id { get; set; }

"Display (Name" - "Site Name")
        public string WebName { get; set; }

"Display" (Name , "URL")
        public string WebUrl { get; set; }

"Display "Name" - "Website Classification")
        public int? TTypeID { get; set; }

"Display "Name" - "Website Classification")
        public TType WebType { get; set; }
   }
```
TType class:

```
    public partial class TType
    {
        public int Id { get; set; }

"Display "Name"
        public string TypeName { get; set; }

"Display " (Name s "Number of Sites") )
        public int? WebCount { get; set; }
    }
```

The id of the TType table corresponds to the TTypeID of the TWeb table, which is a simple statement:

```

TWeb = await _context. TWebs.Include(t => t.WebType). FirstOrDefaultAsync(m => m.Id == id);
```

Error: MySqlException: Unknown column 't0. TWebId' in 'field list'
The resulting query statement is printed as:

```
      SELECT `t`.`Id`, `t`.`WebName`, `t`.`WebUrl`, `t0`.`Id`, `t0`.`TWebId`, `t0`.`TypeName`, `t0`.`WebCount`
      FROM `t_web` AS `t`
      LEFT JOIN `t_type` AS `t0` ON `t`.`TTypeID` = `t0`.`Id`
      WHERE `t`.`Id` = @__id_0
      LIMIT 1
```
This is a very serious BUG, the right table (t_type) does not have a TWebId field, the database does not have, the entity class does not have, why is there a query for this field?

---
#### min xiong on 11/22/2021, 07:04 AM: 

<p>当我复制相同的代码到新的项目，又可以没有错误的运行，但之前的项目，就是有问题，这是为什么呢？</p>

#### Feedback Bot on 11/22/2021, 08:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### min xiong on 11/22/2021, 09:43 AM: 

<p>很奇怪，我故意在 TType 中增加了 TWebId 这个字段，并描述为 NotMapped</p>
<pre><code>        <span class="hljs-keyword">public</span> <span class="hljs-keyword">int</span> Id { <span class="hljs-keyword">get</span>; <span class="hljs-keyword">set</span>; }

        [<span class="hljs-meta">Display(Name = <span class="hljs-meta-string">"类别名称"</span>)</span>]
        <span class="hljs-keyword">public</span> <span class="hljs-keyword">string</span> TypeName { <span class="hljs-keyword">get</span>; <span class="hljs-keyword">set</span>; }

        [<span class="hljs-meta">Display(Name = <span class="hljs-meta-string">"网站数量"</span>)</span>]
        <span class="hljs-keyword">public</span> <span class="hljs-keyword">int</span>? WebCount { <span class="hljs-keyword">get</span>; <span class="hljs-keyword">set</span>; }

        [<span class="hljs-meta">NotMapped</span>]
        <span class="hljs-keyword">public</span> <span class="hljs-keyword">int</span> TWebId { <span class="hljs-keyword">get</span>;<span class="hljs-keyword">set</span>; }
</code></pre>
<p>然后还是报错：</p>
<pre><code>MySqlException: Unknown column <span class="hljs-string">'t0.TWebId1'</span> <span class="hljs-keyword">in</span> <span class="hljs-string">'field list'</span>
</code></pre>
<p>难道我必须在 TType 表中增加没有用的字段 TWebId ？</p>

#### Feedback Bot on 11/23/2021, 06:47 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by smitpatel** [comment] 2022-01-28 14:54
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2022-02-14 20:23
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:23 UTC
Labels: closed-could-not-reproduce, customer-reported
