### ISSUE TITLE
Querying with a simple value conversion is evaluated client-side

### ISSUE THREAD

**Issue by arjenvrh** [dotnet/efcore#12060] opened 2018-05-18 07:17 UTC
Querying with a simple value conversion from System.Drawing.Color to Int32 is not working as expected and results in client-side evaluation.

Example setup:
```csharp
    // Entity
    public class ExampleEntity
    {
        public System.Drawing.Color? ColorValue { get; set; }
    }

    // Mapping
    entityBuilder.Property(s => s.ColorValue ).HasConversion(ColorValueConverter.Instance);

    // ValueConverter
    public class ColorValueConverter : ValueConverter<Color?, Int32?>
    {
        public static ColorValueConverter Instance = new ColorValueConverter();

        public ColorValueConverter(ConverterMappingHints mappingHints = default)
            : base(val => val != null ? (Int32)val.Value.ToArgb() : (Int32?)null,
                   val => val != null ? Color.FromArgb(val.Value) : (Color?)null,
                   mappingHints)
        {
        }
    }
```

The setup is used in a query as follows:
```csharp
System.Drawing.Color col = System.Drawing.Color.FromArgb(128, 128, 100);
IQueryable<ExampleEntity> query = context.Set<ExampleEntity>();
var result = query.Where( w => w.ColorValue == col);
```

When a similar conversion is defined for TimeSpan, this corresponding query is evaluated server-side as expected. Why is the same query with System.Drawing.Color not evaluated server-side? Is there a workaround? 

### Further technical details
EF Core version: 2.1.0 rc1 final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.0 Preview 1.1

**Comment by ajcvickers** [comment] 2018-05-18 19:58
Duplicate of #12045

**Closed** 2022-10-16 12:25 UTC
Labels: closed-duplicate, customer-reported
