### ISSUE TITLE
filter using read only alias property in Entity framework or EF core

### ISSUE THREAD

**Issue by maharasa-code** [dotnet/efcore#22456] opened 2020-09-09 04:36 UTC
I have an interface for all my database entity common properties (like created on, created by, Key).
each entity has different primary key column Name ex `City=> CityId, Country=> CountryId`, 
I want to write a common method for IsExisitingEintity
```C#
bool IsExisitingEintity (long Id, IQueryable<TEntity> entity ){
  return entity.any(x=> x.Key==id);
}
```

My Entity
```C#
class City
{
  public long CityId{get;set;}
....
  Public Key{
    get {return key;}
}
}
```
The above IsExisitingEintity generic method throws an error. Is there any way to write a generic method for check IsExisitingEintity

**Comment by ajcvickers** [comment] 2020-09-09 18:05
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-09-21 15:27
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:39 UTC
Labels: closed-could-not-reproduce, customer-reported
