### ISSUE TITLE
SQL error - The column prefix 't0' does not match with a table name or alias name used in the query.

### ISSUE THREAD

**Issue by pendelton** [dotnet/efcore#6902] opened 2016-10-30 08:53 UTC
### Steps to reproduce

I wrote that query:

``` Csharp
from usr in _dbContext.AppUsers
from asc in _dbContext.Ascents.Where(a => a.ClimberId == usr.Id && 
                                     a.AscentDate >= ascentsStartingFromDate).DefaultIfEmpty()
select new
{
      ClimberId = usr.Id,
      FirstName = usr.FirstName,
      LastName = usr.LastName
};
```
### The issue

SQL generated can not be executed on server and finaly we get error.
SQL looks like that:

``` sql
SELECT [usr].[Id], [usr].[FirstName], [usr].[LastName]
FROM [Users] AS [usr]
CROSS APPLY (
    SELECT [t0].*
    FROM (
        SELECT NULL AS [empty]
    ) AS [empty0]
    LEFT JOIN (
        SELECT [a0].*
        FROM [Ascents] AS [a0]
        WHERE ([a0].[ClimberId] = [usr].[Id]) AND ([a0].[AscentDate] >= '2016-01-01 00:00:00')
    ) AS [t] ON 1 = 1
) AS [t1]
```

Exception message:
An exception of type 'System.Data.SqlClient.SqlException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code

Additional information: The column prefix 't0' does not match with a table name or alias name used in the query.

**It is enough to remove zero from 4 line (so not SELECT [t0].\* but just SELECT [t].*) of that SQL and query work like a glance** What do you think it is a bug?
### Further technical details

Project.json

```
  "dependencies": {
    "AutoMapper": "5.1.1",
    "EntityFramework.Core": "7.0.0-rc1-final",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
    "Microsoft.EntityFrameworkCore.Design": "1.0.0-preview2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.0.0-preview2-final"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "net461": { }
  },
```

Other details about my project setup:

**Comment by smitpatel** [comment] 2016-10-30 17:55
dupe of #6636 
It is fixed in the latest release `1.1.0-preview1-final`.

**Closed** 2022-10-16 10:40 UTC
