### ISSUE TITLE
Unable to "Add Migration" or "Update" a code-first EF Core database when my database code is in a separate project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#32692] opened 2023-12-31 10:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-Add-Migration-or-Update-a-/10544656)._

---
[severity:It bothers me. A fix would be nice]
I've been trying to use Entity Framework Support in Visual Studio as documented here: https://devblogs.microsoft.com/visualstudio/web-api-development-in-visual-studio-2022/

However, since we have separate startup/controller, service and persistence projects there doesn't appear to be anyway to get it to see the EF connection.

It all works from the command line from Package Manager Console, but I always have to change the "Default project" to my persistence project.

Do we have to put everything together in a single project to get these features to work?

---
#### Feedback Bot on 12/20/2023, 02:33 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2024-01-03 14:46
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2024-01-12 17:56
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-01-12 17:56 UTC
Labels: customer-reported
