### ISSUE TITLE
transaction.Rollback() is not working in EF Core

### ISSUE THREAD

**Issue by divakarganta** [dotnet/efcore#15083] opened 2019-03-20 02:48 UTC
Hi,

I am working EF core code, I tried as below, any exception occur in _saveDocumentToDb or SaveFile catch block is executing but Rollback not happen.

```C#
try
{
await _saveDocumentToDb(entityId, file, docRequest, guid, transaction);
await EntityDocumentsStorageHelper.SaveFile(file, guid);

                transaction.Commit();
            }
            catch (Exception e)  
            {
                // TODO: BUG: This rollback does not rollback the database operation.
                transaction.Rollback();
                throw;
            }
```
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment] 2019-03-20 21:14
@divakarganta There isn't enough information here for us to be able to reproduce what you are seeing. Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-03-29 16:36
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:56 UTC
Labels: closed-could-not-reproduce, customer-reported
