### ISSUE TITLE
Database first - IPluralize with -UseDatabaseNames - Id instead of ID

### ISSUE THREAD

**Issue by yakeer** [dotnet/efcore#12773] opened 2018-07-24 17:11 UTC
Hey,
Using EF Core 2.1,
Having this annoying issue:

I'm using an IPluralize service, which finally works ok with the Table/Class names.
But the properties of the class (Columns of the table), are not strict to the Database names.
For example, Column "ID" becomes property "Id".

If I use -UseDatabaseNames, the class properties (table columns) are created ok, but the IPluralize do not work.

I'm stuck in between, I need to use both features.
How can I achieve that?

**Comment by CodeMonkey12** [comment] 2018-07-24 17:42
We are literally having the exact same issue. Any help would be appreciated!

**Comment by ErikEJ** [comment] 2018-07-24 18:40
Maybe EF Core Power Tools could help, at least with the ID vs Id issue

**Comment by yakeer** [comment] 2018-07-25 04:34
@ErikEJ  I'm aware of the EF Core Power Tools,
But it still won't give me the required solution I need with its features,
That's why I'm wondering how can I do it in a native way.

My data model is in .NET Standard class library, which causes EF Power Tools to have limited features.

**Comment by ErikEJ** [comment] 2018-07-25 19:05
Scaffolding works fine in EF Core Power Tools with .Net std libs... What limited features are you referring to,?

**Comment by ajcvickers** [comment] 2018-07-30 18:02
Duplicate of #12102

**Closed** 2022-10-16 13:21 UTC
Labels: customer-reported
