### ISSUE TITLE
What is wrong with `There is no entity type mapped to the table...`

### ISSUE THREAD

**Issue by decie** [dotnet/efcore#24062] opened 2021-02-04 09:42 UTC
When I run `update-database`, I encounter 
System.InvalidOperationException: There is no entity type mapped to the table 'tablename' used in a data operation. Either add the corresponding entity type to the model or specify the column types in the data operation.
How to fix this error?

**Comment by roji** [comment] 2021-02-04 10:11
@decie there isn't enough information in your description above, can you please submit a runnable code sample?

**Comment by KamilGadawski** [comment] 2021-02-04 13:16
I had the exact same problem. See if that helps in your case too.

TL;DR

I deleted all migrations created them again and it worked.

https://stackoverflow.com/questions/66041955/creating-a-one-to-many-relationship-ef-core-update-database-fail

**Comment by AndriySvyryd** [comment] 2021-02-05 01:23
Duplicate of https://github.com/dotnet/efcore/issues/23503

Please update to EF Core 5.0.3 and try again.

**Closed** 2022-10-16 19:22 UTC
Labels: customer-reported

**Comment by Molostov-A** [comment] 2023-04-13 12:03
I had a similar error during a downgrade migration. It turned out that the problem was that EF didn't generate the SQL script correctly (I noticed it when I requested the output of the generated script). The problem was solved by manually writing a sql commands in the migration:  `migrationBuilder.Sql("...");`
