### ISSUE TITLE
Using an IQueryable<TChild> as IQueryable<TParent> (covariance) throws "Expression of type ... cannot be used for return type ..." when calling FirstOrDefaultAsync

### ISSUE THREAD

**Issue by vanderkleij** [dotnet/efcore#18295] opened 2019-10-09 08:29 UTC
In EF core 2.2, we could use the covariance of `IQueryable<T>` to use a projected `IQueryable<TChildDto>` as an `IQueryable<TParentDto>`. In EF core 3.0, this now throws the following exception when we call `FirstOrDefaultAsync()`, `SingleOrDefaultAsync()`, `SingleAsync()` or `FirstAsync()` on the queryable.

> Expression of type 'System.Threading.Tasks.Task`1[ChildDto]' cannot be used for return type 'System.Threading.Tasks.Task`1[ParentDto]

Other materializing calls such as `FirstOrDefault()` (non-async), `ToListAsync()` and `ToList()` seem to work as expected.

### Steps to reproduce

Run the following code:

``` C#
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

internal class PersonEntity
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }
}

internal class ParentDto
{
    public int Id { get; set; }

    public string Name { get; set; }
}

internal class ChildDto : ParentDto
{
    public string Phone { get; set; }
}

internal class MyContext : DbContext
{
    public MyContext(DbContextOptions options) : base(options)
    {
    }

    public DbSet<PersonEntity> Persons { get; set; }
}

internal class Program
{
    private static void Main(string[] args)
    {
        RunAsync().Wait();
    }

    private static async Task RunAsync()
    {
        var options = new DbContextOptionsBuilder<MyContext>()
            .UseInMemoryDatabase(databaseName: "QueryableBugTest")
            .Options;

        using (var context = new MyContext(options))
        {
            IQueryable<ChildDto> childDtoQueryable = context.Persons.Select(entity => new ChildDto
            {
                Id = entity.Id,
                Name = entity.Name,
                Phone = entity.Phone
            });

            IQueryable<ParentDto> parentDtoQueryable = childDtoQueryable;

            var dto = await parentDtoQueryable.FirstOrDefaultAsync();
        }
    }
}
```

This throws the following exception:

> Expression of type 'System.Threading.Tasks.Task`1[ChildDto]' cannot be used for return type 'System.Threading.Tasks.Task`1[ParentDto]

```
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Program.<RunAsync>d__1.MoveNext() in Program.cs:line 59
```

### Further technical details

EF Core version: 3.0.0
Database provider: tested on Microsoft.EntityFrameworkCore.SqlServer and InMemory
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.2

**Comment by smitpatel** [comment] 2019-10-09 16:06
Duplicate of #17644

**Closed** 2022-10-16 14:48 UTC
Labels: closed-duplicate, customer-reported
