### ISSUE TITLE
VS2019 + UWP + EF v 2.2.6 Broken

### ISSUE THREAD

**Issue by Noemata** [dotnet/efcore#19977] opened 2020-02-19 04:55 UTC
The DB that is created produces this error at runtime:

SQLite Error 1: 'no such table:

This is because the DB is created without any tables present.  If I copy in a DB built from an older version of EF, (which has empty tables), EF 2.2.6 works.

I've lost track of what's what?  There have been so many revisions of EF for UWP and so little attention given to the UWP side of things, that both the docs and functionality are now broken.

One example of broken docs, when doing:

Add-Migration InitialCreate

If you have just one UWP project in the build tree, you get a build fail message.  No where in the docs does it stipulate to unload UWP projects, or to have a separate .Net Standard solution that does not include any UWP projects.

### Steps to reproduce

Try following your own instructions for UWP using EF 2.2.6.  Fails at multiple stages of the provided instructions when using UWP.

The last link to the docs I was able to find are here:

https://ef.readthedocs.io/en/staging/platforms/uwp/index.html

The de-emphasis of UWP is getting more than a little strange, by the way.

Oh, and if we're to use a newer version of EF, then please provide one fully working example.

**Comment by ajcvickers** [comment] 2020-02-21 22:31
EF Core 2.2 is [out-of-support](https://docs.microsoft.com/en-us/ef/core/what-is-new/) Closing this as a duplicate of #19978 for the EF comments.

**Closed** 2022-10-16 18:11 UTC
Labels: customer-reported
