### ISSUE TITLE
OutOfMemoryException on getting db context from the pool

### ISSUE THREAD

**Issue by piotrzbyszynski** [dotnet/efcore#25136] opened 2021-06-22 14:07 UTC
Hi,

I have a web api app running on 2 Azure S2 instances. Sometimes I have a short bursts of traffic that crashes whole instance, the only way to recover is restarting an app. Here is a stack trace

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Thread.StartInternal()
   at System.Threading.Thread.Start()
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
```

I have checked memory utilisation on Azure Portal using Max Private Bytes metric and it is around 500MB (nowhere near an instance 3.5GB limit)

Here is how I initialise context pool:

```
serviceCollection.AddDbContextPool<GoApiContext>((serviceProvider, optionsBuilder) =>
            {
                var connectionString = serviceProvider.GetService<ISqlDatabaseConnectionStringProvider>().GetConnectionString();
                optionsBuilder.UseSqlServer(connectionString, o =>
                {
                    o.CommandTimeout(timeout);
                    o.EnableRetryOnFailure();
                });
            }, 384);
```

Also I can see that app thread count indeed increases drastically, from usual ~80 to over 200. Could this OME be caused by the thread pool starvation?

Any help or hint how to approach this issue would be highly appreciated

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows @ Azure App Service

**Comment by ace90210** [comment] 2021-06-23 15:51
We (company i am at) are experiencing this exact same issue. We are investigating the cause still but the error is identical, we are using the same version of .net core and it only seems to happen on our deployments (which use Azure Sql Databases).

Any update on this even if its to confirm its not the cause would be appreciated so we know we are not wasting time investigating our code for the issue.

**Comment by pzbyszynski** [comment] 2021-06-25 13:43
@ace90210 FYI, I have turned off connection pooling, I use `AddDbContext` not `AddDbContextPool` and it seems to help.

@AndriySvyryd @roji I have all my commands wrapped in a transaction like so:
```
        public async Task<TResult> ExecuteAsync<TResult>(ICommand<TResult> command)
        {
            var strategy = _context.Database.CreateExecutionStrategy();

            return await strategy.ExecuteAsync(async () =>
            {
                using (var transaction = await _context.Database.BeginTransactionAsync(IsolationLevel.ReadCommitted))
                {
                    try
                    {
                        var result = await _commandExecutor.ExecuteAsync(command);
                        await transaction.CommitAsync();
                        return result;
                    }
                    catch (Exception)
                    {
                        await transaction.RollbackAsync();
                        throw;
                    }
                }
            });
        }
```

And `BeginTransactionAsync` calls this line of code which probably is blocking? Am I wrong thinking that it can contribute to thread pool starvation? Removing transactions also seems to help but unfortunately I can not do that.

Here is the code I am writing about:
https://github.com/dotnet/efcore/blob/b2fc11931a74ca2fcea070df96fb7126373f6a84/src/EFCore.Relational/Storage/RelationalConnection.cs#L392

**Comment by pzbyszynski** [comment] 2021-06-28 15:57
@AndriySvyryd @roji Unfortunately turning off connection pooling does not solve the problem

Now I am pretty sure that this is thread pool starvation issue. I have generated memory dump during one of traffic spikes that killed app service and here is what I have found in the analysis

```
The following threads in RD28187827F947_w3wp_19132.dmp are waiting in System.Threading.Monitor.Wait
31.36% of threads blocked (74 threads)

100 client connection(s) in RD28187827F947_w3wp_19132.dmp have been executing a request for more than 90 seconds.
```

All blocked threads have the same stack trace, here is an example:
```
 System.Threading.Thread.StartInternal()
   System.Threading.Thread.Start()
   Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(System.Data.Common.DbConnection, System.Threading.Tasks.TaskCompletionSource`1, Microsoft.Data.Common.DbConnectionOptions, Microsoft.Data.ProviderBase.DbConnectionInternal ByRef)
   Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(System.Data.Common.DbConnection, System.Threading.Tasks.TaskCompletionSource`1, Microsoft.Data.Common.DbConnectionOptions, Microsoft.Data.ProviderBase.DbConnectionInternal, Microsoft.Data.ProviderBase.DbConnectionInternal ByRef)
   Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(System.Data.Common.DbConnection, Microsoft.Data.ProviderBase.DbConnectionFactory, System.Threading.Tasks.TaskCompletionSource`1, Microsoft.Data.Common.DbConnectionOptions)
   Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(System.Data.Common.DbConnection, Microsoft.Data.ProviderBase.DbConnectionFactory, System.Threading.Tasks.TaskCompletionSource`1, Microsoft.Data.Common.DbConnectionOptions)
   Microsoft.Data.SqlClient.SqlConnection.TryOpen(System.Threading.Tasks.TaskCompletionSource`1)
   Microsoft.Data.SqlClient.SqlConnection.OpenAsync(System.Threading.CancellationToken)
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   Microsoft.EntityFrameworkCore.Storage.RelationalConnection+d__50.MoveNext()
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   Microsoft.EntityFrameworkCore.Storage.RelationalConnection+d__50.MoveNext()
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   Microsoft.EntityFrameworkCore.Storage.RelationalConnection+d__47.MoveNext()
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   System.Runtime.CompilerServices.TaskAwaiter`1[[System.Boolean, System.Private.CoreLib]].GetResult()
   Microsoft.EntityFrameworkCore.Storage.RelationalCommand+d__17.MoveNext()
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   System.Runtime.CompilerServices.TaskAwaiter`1[[System.__Canon, System.Private.CoreLib]].GetResult()
   Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1+AsyncEnumerator+d__18[[System.__Canon, System.Private.CoreLib]].MoveNext()
```

Any help would be highly appreciated, application thread pool starvation during traffic spikes renders app service virtually unusable :/

**Comment by AndriySvyryd** [comment] 2021-06-28 17:02
What EF Core version are you using?

@ace90210 Can you confirm that you are getting the same stack trace as above?

**Comment by pzbyszynski** [comment] 2021-06-28 17:40
@AndriySvyryd EF 3.1.3

**Comment by roji** [comment] 2021-07-12 13:19
Sorry for not responding earlier on this.

Looking at the issue above, there doesn't seem to be enough information to understand exactly what's going on. Here are some thoughts:

* [The original post above](https://github.com/dotnet/efcore/issues/25136#issue-927275158) discusses an out-of-memory exception, with the stack trace showing it is happening inside Microsoft.Data.SqlClient. As in general with OOM, the memory may be exhausted by a completely different part of the application, with the exception only being triggered when opening the connection with SqlClient (though that's probably not the case if the stack trace is very consistent). Either way, this would very likely be unrelated to EF, but rather something having to do with SqlClient.
* In addition, there seems to be some sort of thread-blocking issue. [The stack trace](https://github.com/dotnet/efcore/issues/25136#issuecomment-869804874) seems to show thread being blocked when starting new threads (i.e. Thread.Start); this is not related to the thread pool, as completely separate threads are being started. I am not sure what could trigger Thread.Start hanging - your system seems to be in some sort of unstable state which may be causing both the OOM and this block.

Is there any way you can reproduce this application state in an independent code sample? This is typically done by creating a console app which spawns multiple threads, each of which loops and performs your operation(s) until the problematic state is reproduced. Trying to create this code sample could help understand what in your real application is the source of the problem.

**Comment by roji** [comment] 2021-07-13 16:06
@pzbyszynski I understand and I agree that this kind of issue is indeed difficult to reproduce independently - but I'm not sure what else to suggest. I am unfamiliar with either OOM or Thread.Start hanging as a result of EF Core functioning - both are probably system of a system that's somehow severely destabilized (probably because of unrelated reasons...).

You may have better luck asking this on the [SqlClient repository](https://github.com/dotnet/sqlclient), since the OOM and hang occur inside that driver; but I suspect they'll also ask for some sort of repro in order to investigate.

**Comment by pzbyszynski** [comment] 2021-07-15 09:21
@roji Ok, I will try to invastigate it and reproduce it on my own. I will get back to you if I have any news on this. Thanks for your help!

**Comment by roji** [comment] 2021-07-15 15:34
@pzbyszynski good luck. As @vonzshik mentioned to me offline, you may also want to increase your maximum pool size to make connection pool exhaustion more rare; this isn't a fix, but may be a sufficient workaround. Also, since I suspect your application is in an unstable state regardless of SqlClient, this may cause OOM (or Thread.Start blocks) to surface elsewhere, confirming the diagnosis.

**Comment by roji** [comment] 2021-07-16 20:22
@pzbyszynski as it's very unlikely this issue is related to EF Core, I'm going to go ahead and close this. However, if you come up with new information we can still try to help you.

**Closed** 2022-10-16 19:37 UTC
Labels: closed-no-further-action, customer-reported
