### ISSUE TITLE
a simple work in Ef Core why this is very hard. The instance of entity type cannot be tracked because another instance with the same key value for {'Id'} is already being tracked

### ISSUE THREAD

**Issue by sajadghobadi** [dotnet/efcore#18012] opened 2019-09-24 06:58 UTC
i want to update entity with related(one-to-many) objects.
my customer classes is : 
```C#
[Table("CustomerTB")]
    public class Customer:BaseEntity
    {
        
        [Required(ErrorMessage = "Enter Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Enter Address")]
        public string Address { get; set; }
        
        public string Country { get; set; }
        
        public string City { get; set; }
        
        public string Phoneno { get; set; }

        public ICollection<Product> Products { get; set; }
    }
```

product class is : 
```C#

[Table("ProductTB")]
    public class Product:BaseEntity
    {
        [Required(ErrorMessage = "Enter Name")]
        public string Name { get; set; }
        
        public string Number { get; set; }

        public Customer Customer { get; set; }

        public int CustomerId { get; set; }

    }


```
and so my base entity is very simple 
```C#
 public class BaseEntity
    {
        [Key]
        public int Id { get; set; }
    }
```

now in my page just retrieve one object and edit some fields, then do update like this:
```

var customer = _dbContext.CustomerTB.Include(x => x.Products)
                .FirstOrDefault(c => c.Id == 3);


            _mapper.Map(customer, CustomerViewModel);
            
            CustomerViewModel.Name = "updated2";
            CustomerViewModel.Products.Last().Name = "updatedByMe";

            _mapper.Map(CustomerViewModel, customer);            


             _dbContext.CustomerTB.Update(customer);
             await _dbContext.SaveChangesAsync();


```
 i get this error:

> The instance of entity type cannot be tracked because another instance with the same key value for {'Id'} is already being tracked

**Comment by sajadghobadi** [comment] 2019-09-24 07:45
i found one notice, it is interest when  stop using automapper every thing work perfectly

**Comment by sajadghobadi** [comment] 2019-09-24 07:57
this is small and runable project  :
[https://gofile.io/?c=jj2tpa]

**Comment by smitpatel** [comment] 2019-09-24 19:12
The code supplied to reproduce this issue makes use of third-part libraries. It would help greatly to have a simplified project/solution or code listing that isolates the issue in EF.
Majorly if the issue does not happen in the absense of automapper then it is likely a bug in automapper or configuration of automapper or incorrect usage of automapper.

**Comment by smitpatel** [comment] 2019-09-27 17:31
@ajcvickers - Should call to `Update` be a no-op?

**Comment by ajcvickers** [comment] 2019-10-12 21:39
@sajadghobadi The repo project using EF Core 2.0 which has been out-of-support for some time now. Please update to the latest 3.0 release and test again. If it still fails, then please post your 3.0 project for us to take a look.

**Comment by ajcvickers** [comment] 2019-10-21 16:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:44 UTC
Labels: closed-could-not-reproduce, customer-reported
