### ISSUE TITLE
overwrite add

### ISSUE THREAD

**Issue by asleeguilez** [dotnet/efcore#16913] opened 2019-08-02 15:20 UTC
I want when adding an entity to have a particular treatment. for example, that a field name concatenates a string

**Comment by ajcvickers** [comment] 2019-08-02 17:12
@asleeguilez There isn't enough information here to be actionable. Please explain in more detail exactly what it is that you want to do. If you have tried something that you think should work but doesn't, then please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-08-09 16:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:33 UTC
Labels: closed-could-not-reproduce, customer-reported
