### ISSUE TITLE
Lock row Mysql 

### ISSUE THREAD

**Issue by aimprogman** [dotnet/efcore#14538] opened 2019-01-29 05:24 UTC
Lock row in EF CORE  Database Mysql

I can not implement  following query in EF Core

```
SELECT * FROM person WHERE id=1 FOR UPDATE
```

### Steps to reproduce
I want use it as:

```c#
this._context.Person.FirstOrDefault(a => a.id==1).ForUpdate();
```

**Comment by ajcvickers** [comment] 2019-01-30 20:21
Duplicate of #6717

**Comment by aimprogman** [comment] 2019-01-31 05:58
Thanks, I will subscibe  #6717

**Closed** 2022-10-16 13:49 UTC
Labels: closed-duplicate, customer-reported
