### ISSUE TITLE
DbQuery doesn't play nice with InMemoryDatabase

### ISSUE THREAD

**Issue by IanKemp** [dotnet/efcore#17493] opened 2019-08-29 13:48 UTC
Duplicate of #13995 but that was closed for no good reason so I'm opening this one.

```
System.ArgumentException: Expression of type 'System.Object' cannot be used for parameter of type 'Microsoft.EntityFrameworkCore.Metadata.IKey' of method 'System.Collections.Generic.IEnumerable`1[MyDataAccessProject.Entities.MyEntity] EntityQuery[VehicleChargeCycleView](Microsoft.EntityFrameworkCore.Query.QueryContext, Microsoft.EntityFrameworkCore.Metadata.IEntityType, Microsoft.EntityFrameworkCore.Metadata.IKey, System.Func`3[Microsoft.EntityFrameworkCore.Metadata.IEntityType,Microsoft.EntityFrameworkCore.Storage.MaterializationContext,System.Object], Boolean)'
Parameter name: arg2
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1, Expression arg2, Expression arg3, Expression arg4)
   at Microsoft.EntityFrameworkCore.InMemory.Query.ExpressionVisitors.Internal.InMemoryEntityQueryableExpressionVisitor.VisitEntityQueryable(Type elementType)
   at System.Linq.Expressions.ConstantExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

### Steps to reproduce

This is in an XUnit test project that is using an ASP.NET Core `TestServer` class to make requests against the web API that's being tested. The `Startup.cs` of that project contains the following:

```c#
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<MyDbContext>(o => o.UseInMemoryDatabase("TestDatabaseName"));
        }
```

The actual `DbContext` is setup like this:

```c#
    public class MyDbContext : DbContext
    {
        public DbQuery<MyEntity> MyEntities { get; set; }

        public MyDbContext(DbContextOptions<MyDbContext> options) : base(options)
        {
        }
    }
```

And finally the repository method, which is being called by a service, which is being called by the web API:

```c#
    public class MyRepository : IMyRepository
    {
        private readonly MyDbContext _context;

        public MyRepository(MyDbContext context)
        {
            _context = context;
        }

        public List<MyEntity> GetEntitities()
        {
            return _context.MyEntities.ToList(); // crashes here
        }
    }
```

As you can see, there's absolutely nothing special here. Note that it works 100% when used in a non-testing context with the `DbContext` setup to use the SQL Server provider.

### Further technical details
EF Core version: 2.2.6
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10 Version 1903 (OS Build 18362.295)
IDE: Visual Studio 2017 Professional 15.9.15

**Comment by ajcvickers** [comment] 2019-08-30 20:09
@IanKemp I have not been able to reproduce this. Can you please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-09-06 16:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by regis-ranniere** [comment] 2019-09-13 20:07
Hello, I have the same problem.

The scenario is:
- Integration tests;
- Load the database into memory;
- This database has a number of migrations and one of these migrations creates a view where I select information from two tables;
- When I upload the server for testing using 'WebApplicationFactory' and send a command:
_context.ViewToSelectData.ToList () it throws the exception placed above;

My application can not make it available, I am trying to reassemble a project to simulate the situation.

But without mounting the test server the problem is also happening.

I simulated the situation using this simple test here:

```csharp
    public class AppDbContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        public DbQuery<BlogPostsCount> BlogPostCounts { get; set; }

        public AppDbContext()
        {

        }
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            this.Database.ExecuteSqlCommand(@"CREATE VIEW View_BlogPostCounts AS 
                    SELECT b.Name, Count(p.PostId) as PostCount FROM Blogs b JOIN Posts p on p.BlogId = b.BlogId GROUP BY b.Name");

            modelBuilder
                .Query<BlogPostsCount>().ToView("View_BlogPostCounts")
                .Property(v => v.BlogName).HasColumnName("Name");


        }
    }


    public class Blog
    {
        public int BlogId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public ICollection<Post> Posts { get; set; }
    }

    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int BlogId { get; set; }
    }

    public class BlogPostsCount
    {
        public string BlogName { get; set; }
        public int PostCount { get; set; }
    }

    public class InMemoryTests
    {
        [Fact]
        public void ErrorUsingQueryInMemory()
        {
            var _opcoesContexto = new DbContextOptionsBuilder<AppDbContext>()
            .UseInMemoryDatabase(databaseName: "inMemoryDatabase")
            .Options;

            using (var dbContext = new AppDbContext(_opcoesContexto))
            {
                var blogPostsCounts = dbContext.BlogPostCounts.ToList();
            }

            Assert.True(true);
        }
}
```

**Comment by smitpatel** [comment] 2019-09-13 20:59
@regis-ranniere - InMemory database is not Sql database. You are executing SQL to create a database view and mapping your query type to view but all that has no meaning in InMemory and your entityType has no way to get data from server. You need to use defining query to map query types for InMemory database.

Also running ExecuteSqlCommand inside OnModelCreating should throw.

**Comment by SandVonSchaewen** [comment] 2020-09-30 13:04
Not Sure if it's still relevant but I encountered the same Problem. 

This Stackoverflow Article helped To get into it : [click](https://stackoverflow.com/questions/55373825/how-to-test-database-views-using-entity-framework-cores-in-memory-db-provider)

Here is the Solution:

Add this line to the modelBuilder: 
` protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
 if (Database.IsInMemory())
            {
builder.Query<BlogPostsCount>().ToQuery( () => from  b in Blogs b 
join p in POSTS on  b.BlogId equals p.BlogId  
group b.Name
  select new BlogPostsCount() {  BlogName = b.Name, PostCount = p.Count()});
}
else
{
builder.Query<BlogPostsCount>.ToView("BlogPostsCount");
}
}`

**Closed** 2022-10-16 14:38 UTC
Labels: closed-could-not-reproduce, customer-reported
