### ISSUE TITLE
SQLite Error 5: 'not an error'

### ISSUE THREAD

**Issue by Robelind** [dotnet/efcore#32512] opened 2023-12-04 14:13 UTC
I've run into the exception below and I'm having a hard time finding any information regarding it.
The information I've seen regarding error 5 is in conjunction with the message 'database is locked'.
What could be the problem here?

```
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'not an error'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Deactivate()
   at Microsoft.Data.Sqlite.SqliteConnectionInternal.Deactivate()
   at Microsoft.Data.Sqlite.SqliteConnectionPool.Return(SqliteConnectionInternal connection)
   at Microsoft.Data.Sqlite.SqliteConnection.Close()
   at System.Data.Common.DbConnection.CloseAsync()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.CloseAsync()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.CloseAsync()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.DisposeAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
```
EF Core version: 6.0.10
Database provider: Microsoft.EntityFrameworkCore.Sqlite 6.0.10
Target framework: .NET 8.0
Operating system: Windows

**Comment by Robelind** [comment] 2023-12-04 14:39
Looking at the code in SqliteConnection.Deactivate(), I understand that it can potentially have something to do with collations/functions.
I recently added a collation and some functions, based on examples from other developers, that was needed to support comparison of strings containing non-ascii characters.

```
 SqliteConnection connection = new SqliteConnection(connStr);
 connection.CreateCollation("NOCASE", (x, y) => string.Compare(x, y, true, CultureInfo.CurrentCulture));
 connection.CreateFunction("upper", (string value) => value.ToUpper(CultureInfo.CurrentCulture));
 connection.CreateFunction("lower", (string value) => value.ToLower(CultureInfo.CurrentCulture));
```

**Comment by ajcvickers** [comment] 2024-01-03 14:04
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-01-03 14:04 UTC
Labels: customer-reported
