### ISSUE TITLE
Execute Reader requires command to have transaction when connection assigned to command is in pending local trans

### ISSUE THREAD

**Issue by DNLMurthy** [dotnet/efcore#25496] opened 2021-08-12 05:01 UTC
ExecuteReader requires command to have transaction when connection assigned to command is in pending local trans

### Example code

```c#
using (SchoolDataContext db = new SchoolDataContext())
{
    using(using var Transaction = db.Database.BeginTransaction())
    {
        SudentDtls SudentDtls = (from p in db.SudentDtls where p.SudentId == SudentId && p.StatusId == (int)EStatus.ActiveStatus select p).FirstOrDefault();
        SudentDtlsHistory SudentHistory = (from p in db.SudentDtlsHistory where p.SudentId == SudentId && p.StatusId == (int)EStatus.ActiveStatus select p).FirstOrDefault();
 
        SudentDtls = Automaper<SudentDtlsHistory, SudentDtls>(SudentHistory, SudentDtls);
        SudentDtls.ModifiedBy = UserId; 
        SudentDtls.ModifiedDate = DateTime.Now; 
        db.SaveChanges(); 

        MStudentData data = SqlQueryExtensions.SqlQuery<MStudentData>(db, "GetStudentData");
        if (data != null)
        {
                        
        }
        Transaction.Commit();
    }
}
```

SqlQueryExtensions: Class at SchoolFrameWork
SqlQueryExtension method, asking for the current transaction but how to supply transaction to SqlQuery. 

## Stack Trace

```
at Microsoft.Data.SqlClient.SqlCommand.ValidateCommand(Boolean isAsync, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SchoolFrameWork.SqlQueryExtensions.SqlQuery[T](DbContext db, String sql, Boolean IsList, Object[] parameters) in D:\School_DataModified\SchoolDashboard\SchoolFrameWork\SqlQueryExtensions.cs:line 14
   at SchoolInfrastructure.Implementation.MyProfileHistory.IsApprovalRequired(SchoolDataContext context, Int32 EmployeeId) in D:\School_DataModified\SchoolDashboard\SchoolInfrastructure\Implementation\MyProfileHistory.cs:line 29
   at SchoolInfrastructure.Implementation.MyProfileHistory.InsertEmployeeData(MMyProfile myProfile, Int32 RoleId) in D:\School_DataModified\SchoolDashboard\SchoolInfrastructure\Implementation\MyProfileHistory.cs:line 72
 ```

### version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .Net Core 2.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.10.2

**Comment by ajcvickers** [comment] 2021-08-12 16:58
@DNLMurthy Can you point to or post the code for `SqlQueryExtensions`?

**Comment by ErikEJ** [comment] 2021-08-12 17:10
Maybe this can help? 
https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/ErikEJ.EntityFrameworkCore.SqlServer.SqlQuery/DbContextExtensions.cs

**Comment by ajcvickers** [comment] 2021-08-20 10:56
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2021-08-28 09:12
@viktorz You typically need to tell EF to use the transaction. For example:

```C#
dbContext.Database.UseTransaction(transaction);
```

See the [Transactions](https://docs.microsoft.com/en-us/ef/core/saving/transactions) documentation for more info.

However, I see you are also using an EF execution strategy. This complicates use of transactions. See [Execution strategies and transactions](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency#execution-strategies-and-transactions) for more info.

**Comment by viktorz** [comment] 2021-08-30 15:16
Thank you! Somehow I have missed this line in the documentation samples.
Thanks for the hint about externally managed transactions and execution strategy, I have adjusted my code to use retries on application/transaction level instead.

**Closed** 2022-10-16 19:42 UTC
Labels: closed-no-further-action, customer-reported
