### ISSUE TITLE
System.BadImageFormatException from mixed mode assembly when trying to add migration

### ISSUE THREAD

**Issue by leak** [dotnet/efcore#5511] opened 2016-05-25 12:11 UTC
### The issue

My project contains a mixed mode assembly 

```
// Global type: <Module>
// Architecture: AnyCPU (64-bit preferred)
// This assembly contains unmanaged code.
// Runtime: .NET 4.0
```

Everything (dotnet build, dotnet run, VS) works fine apart from the `dotnet ef migrations add Initial` command which fails with `System.BadImageFormatException: Could not load file or assembly`

Stacktrace points to Startup.cs where an object from said assembly is newed. Commenting out that line allows the command to finish.
### Further technical details

```
    "frameworks": {
        "net452": {
        }
    },
```

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x86

**Comment by natemcmaster** [comment] 2016-05-25 16:03
This is a possibly a duplicate of #5285 which was fixed in #5399

**Closed** 2022-10-16 09:42 UTC
