### ISSUE TITLE
NuGet Dependency Resolution

### ISSUE THREAD

**Issue by craigneblett** [dotnet/efcore#1997] opened 2015-04-06 23:39 UTC
VS 2013 Update 4 (NuGet version 2.8.50926.663)
With the nightly build source selected and pointing at https://www.myget.org/F/aspnetvnext/api/v2/, I'm getting the following:

PM> Install-Package EntityFramework.SqlServer –Pre
Attempting to resolve dependency 'EntityFramework.Relational (≥ 7.0.0-beta5-12839)'.
Install-Package : 'EntityFramework.Relational' already has a dependency defined for 'EntityFramework.Core'.
At line:1 char:1
- Install-Package EntityFramework.SqlServer –Pre
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by ErikEJ** [comment] 2015-04-07 07:13
I think you need nuget 2,8,5, which you can get from nuget.codeplex.com

**Comment by jr-araujo** [comment] 2015-04-08 17:46
Hi craigneblett, i got this error too. I tried much stuff to do this package manager command line work, but this doesn't worked. I tried this same command-line in the VS2015, i tried change the Tagert Framework from 4.5 to 4.6 in the VS2013 Update4 and doesn't works.

Anyone knows how to put this command-line to work?

**Comment by bricelam** [comment] 2015-04-08 20:15
Dupe of #1882

**Closed** 2022-10-16 08:54 UTC
