### ISSUE TITLE
How to Deploy EF Core to Azure App Services When Migrations Are in a Separate Assembly?

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/efcore#8290] opened 2017-04-26 20:59 UTC
How do I publish to Azure App Services when I have a separate migrations assembly?  [Reference](https://github.com/bricelam/Sample-SplitMigrations)

```
dotnet ef migrations add [NAME] -c MyApp.Data.MyAppContext -p ..\MyApp.Data.Migrations

dotnet ef database update -c MyApp.Data.MyAppContext -p ..\MyApp.Data.Migrations
```
Also, I have two databases so I have to specify the context when using dotnet ef from the command line; how will that impact my Azure deployment?

I found [this article](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs) but it only addresses the 'simple' case.

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
IDE: VS 2017

**Comment by ajcvickers** [comment] 2017-05-01 19:01
@spottedmahn Can you be more specific about what you are seeing? Do you get an exception? If so, what is the message and stack trace? Or does something else happen? If so, what?

**Comment by ajcvickers** [comment] 2017-05-12 18:06
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:02 UTC
