### ISSUE TITLE
Incomplete data returned by using a custom ValueObject (EntityIdentity)

### ISSUE THREAD

**Issue by IT-CASADO** [dotnet/efcore#14302] opened 2019-01-02 15:18 UTC
I’m using in one of my new projects some DDD concepts (e.g. [Entity Identity](https://enterprisecraftsmanship.com/2018/07/23/entity-identity-vs-database-primary-key/)) and we noticed some really weird behavior.

To understand the situation better I created a small GitHub [repository](https://github.com/IT-CASADO/ef-core-bug) and created some unit tests.
I’m expecting that all unit tests should be green, but one is red and I cannot figure out the reason for this.

For me it seems to be a bug in EF Core (tested > 6.1.0).

I’m expecting, that both tests **Read_by_Guid** and **Read_by_IdentityObject** returns the same data.
But unfortunately the last one failed and missed some data.

My Test Data use a Model of **Attribute** which can contain multiple **FormulaVariableAttributes**.
I’m querying for all Attributes with a given formula (4 in total). Every formula contains exactly 2 **FormulaVariableAttributes** . In total 8. But I got only 2 in unit test **Read_by_IdentityObject**!?!?

I noticed that the generated SQL Is a little bit different.

Generated SQL by **Read_by_Guid**:
`exec sp_executesql N'SELECT [e].[Id], [e].[Formula], [e].[Name], [e].[RoadmapId], [e].[TenantId]
FROM [PlanningEngine].[Attribute] AS [e]
WHERE ([e].[Formula] IS NOT NULL AND (LTRIM(RTRIM([e].[Formula])) <> N'''')) AND ([e].[RoadmapId] = @__RoadmapIdAsGuid_0)
ORDER BY [e].[Id]',N'@__RoadmapIdAsGuid_0 uniqueidentifier',@__RoadmapIdAsGuid_0='02F23226-427F-4A5F-A8FA-DB138222AF49'
go`

`exec sp_executesql N'SELECT [e.FormulaVariableAttributes].[AttributeId], [e.FormulaVariableAttributes].[VariableAttributeId], [e.FormulaVariableAttributes].[TenantId]
FROM [PlanningEngine].[AttributeFormulaVariableAttribute] AS [e.FormulaVariableAttributes]
INNER JOIN (
    SELECT [e0].[Id]
    FROM [PlanningEngine].[Attribute] AS [e0]
    WHERE ([e0].[Formula] IS NOT NULL AND (LTRIM(RTRIM([e0].[Formula])) <> N'''')) AND ([e0].[RoadmapId] = @__RoadmapIdAsGuid_0)
) AS [t] ON [e.FormulaVariableAttributes].[AttributeId] = [t].[Id]
ORDER BY [t].[Id]',N'@__RoadmapIdAsGuid_0 uniqueidentifier',@__RoadmapIdAsGuid_0='02F23226-427F-4A5F-A8FA-DB138222AF49'
Go`

Generated SQL by **Read_by_IdentityObject**:

`SELECT [e].[Id], [e].[Formula], [e].[Name], [e].[ParentId], [e].[RoadmapId], [e].[TenantId]
FROM [PlanningEngine].[Attribute] AS [e]
WHERE [e].[Formula] IS NOT NULL AND (LTRIM(RTRIM([e].[Formula])) <> N'')
ORDER BY [e].[Id]
go`

`SELECT [e.FormulaVariableAttributes].[AttributeId], [e.FormulaVariableAttributes].[VariableAttributeId], [e.FormulaVariableAttributes].[TenantId]
FROM [PlanningEngine].[AttributeFormulaVariableAttribute] AS [e.FormulaVariableAttributes]
go`

`SELECT [e1].[RoadmapId], [e1].[Id]
FROM [PlanningEngine].[Attribute] AS [e1]
WHERE [e1].[Formula] IS NOT NULL AND (LTRIM(RTRIM([e1].[Formula])) <> N'')
Go`

**Comment by ajcvickers** [comment] 2019-01-02 21:14
Note for triage: I was able to reproduce this. Looks like Include is not bringing everything in that it should.

**Comment by IT-CASADO** [comment] 2019-01-02 21:18
If I execute the generated SQL statement the needed data is included. Only the navigation property is not filled up correctly.

**Comment by ajcvickers** [comment] 2019-01-04 20:35
@smitpatel to look for duplicate.

**Comment by smitpatel** [comment] 2019-01-04 22:08
Duplicate of #13546

**Comment by IT-CASADO** [comment] 2019-01-05 20:59
Can you explain me a little bit why this is a duplicate of #14329 !?

In the case of using a Guid type in the filter condition everything is working fine with the included navigation. Only by using RoadmapId as a type something is broken. 
I don't see the relation to the duplicate item...

**Comment by smitpatel** [comment] 2019-01-06 02:50
> Note for triage: I was able to reproduce this. Looks like Include is not bringing everything in that it should.

**Comment by smitpatel** [comment] 2019-01-06 02:50
@IT-CASADO - It is duplicate of #13546 and not the one you referenced.

**Comment by IT-CASADO** [comment] 2019-01-07 14:36
@smitpatel - I checked #13546 but still I cannot see the relation to this item!? I don't make any projection i n my queries.

**Comment by smitpatel** [comment] 2019-01-07 20:18
```C#

			var formulaAttributes = context.Attributes

				.Include(e => e.FormulaVariableAttributes)

				.Where(e => !string.IsNullOrWhiteSpace(e.Formula))

				.Where(e => e.RoadmapId == TestData.RoadmapIdAsIdentityObject)

				.ToList();
```
You are projecting out `FormulaAttribute` entityType. Just because `Select` is not in the query does not mean there is no implicit projection.

**Comment by IT-CASADO** [comment] 2019-01-18 12:17
You are right, I'm using a projection. But even with using a projection I don't see the relation to the duplicated item.

I have 3 tests. All of them are using a projection!!

`		[Fact()]
		public void Read_All_Formulas()
		{
			// act
			var formulaAttributes = context.Attributes
				.Include(e => e.FormulaVariableAttributes)
				.ToList();

			// assert
			formulaAttributes.SelectMany(e => e.FormulaVariableAttributes).Count().Should().Be(8);
		}

		[Fact()]
		public void Read_by_Guid()
		{
			Guid filter = TestData.RoadmapIdAsGuid;

			// act
			var formulaAttributes = context.Attributes
				.Include(e => e.FormulaVariableAttributes)
				.Where(e => e.RoadmapId == filter)
				.ToList();

			// assert
			formulaAttributes.SelectMany(e => e.FormulaVariableAttributes).Count().Should().Be(8);
		}

		[Fact()]
		public void Read_by_IdentityObject()
		{
			RoadmapId filter = TestData.RoadmapIdAsIdentityObject;

			// act
			var formulaAttributes = context.Attributes
				.Include(e => e.FormulaVariableAttributes)
				.Where(e => e.RoadmapId == filter)
				.ToList();

			// assert
			formulaAttributes.SelectMany(e => e.FormulaVariableAttributes).Count().Should().Be(8);
		}`

But only the first two tests runs successfully.
The only difference is the type of the filter variable. 

So for me that looks like a different bug.

**Closed** 2022-10-16 13:46 UTC
Labels: customer-reported
