### ISSUE TITLE
CosmosDB does not fail if database does not exist

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#18590] opened 2019-10-25 10:41 UTC
I found that if I try to write to a CosmosDB database that does not exist it does not fail with an exception (Note: It DOES fail if you try to READ from an unknown database). The only way I can ensure that the write has worked is to get the return change value from the `SaveChangesAsync` 

I expected a write to an unknown database to fail in the same way that SQL providers do. I think this is an important issue as some people may be writing to a database and not realise that the data is not being saved. 

### Steps to reproduce

Entity 
``` C#
public class BookListNoSql
{
    [Key]
    public Guid BookId { get; set; }
    public string Title { get; set; }
    public DateTime PublishedOn { get; set; }
    public int YearPublished { get; set; }
    public decimal OrgPrice { get; set; }
    public decimal ActualPrice { get; set; }
    public string PromotionalText { get; set; }
    public string AuthorsOrdered { get; set; }
    public int ReviewsCount { get; set; }
    public double? ReviewsAverageVotes { get; set; }
}
```
DbContext
```c#
public class NoSqlDbContext : DbContext
{
    public NoSqlDbContext(DbContextOptions<NoSqlDbContext> options)
        : base(options) { }

    public DbSet<BookListNoSql> Books { get; set; }

}
```
Unit Test
NOTE: I am using Azure Cosmos DB Emulator
```C#
[Fact]
public async Task TestCosmosDbCatchFailedRequestOk()
{
    //SETUP
    var config = AppSettings.GetConfiguration();
    var builder = new DbContextOptionsBuilder<NoSqlDbContext>()
        .UseCosmos(
            config["endpoint"],
            config["authKey"],
            "UNKNOWNDATABASE");

    using (var context = new NoSqlDbContext(builder.Options))
    {
        //ATTEMPT
        var book = NoSqlTestData.CreateDummyNoSqlBook();
        context.Add(book);
        var numNoSqlChanges = await context.SaveChangesAsync();

        //VERIFY
        numNoSqlChanges.ShouldEqual(0);
    }
}
```

No Exception is thrown on a write to an unknown database. But a read from an unknown database does throw an exception.

### Further technical details
EF Core version: 3.0.0
Database provider: CosmosDB 3.0.0
Target framework:  .NET Core 3.0
Operating system:
IDE: Visual Studio 2019 16.3.1

**Comment by ajcvickers** [comment] 2019-10-25 18:20
@AndriySvyryd to find duplicate.

**Comment by AndriySvyryd** [comment] 2019-10-25 18:28
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/17624

**Closed** 2022-10-16 14:52 UTC
Labels: customer-reported
