### ISSUE TITLE
Using the same reference in two any-clauses makes EF generate duplicate SQL parameters with the same name.

### ISSUE THREAD

**Issue by MicaelFredriksson** [dotnet/efcore#16018] opened 2019-06-10 11:46 UTC
I don't know if it applies to other methods than Any, but as soon as you include two any-clauses in a where-clause, you get this issue. It seems EF doesn't recognize the same parameter is used on two places, hence try to declare an SQL parameter twice with the same name.

```
Exception message:

The variable name '@__me_0_Id' has already been declared. Variable names must be unique within a query batch or stored procedure.
--

Stack trace:

at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()   at System.Threading.Tasks.Task.Execute()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__12.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__11.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()   at UserQuery.<Main>d__0.MoveNext()
--



```

### Steps to reproduce

Simply copy and paste the code below onto an empty console project. Connection string expects a local sql express database.

```c#
public async Task Main()
{
	var builder = new Microsoft.EntityFrameworkCore.DbContextOptionsBuilder();
	builder.UseSqlServer(@"Data Source=.\sqlexpress;Integrated Security=SSPI;Initial Catalog=anybug");
	var context = new Context(builder.Options);
	
	await context.Database.EnsureCreatedAsync();
	
	
	var me = new Author { Id = Guid.NewGuid() };
	
	var crash = await context.Libraries.Where(l => 
		l.MainBooks.Any(x => x.Author == me)
		|| l.SecondaryBooks.Any(x => x.Author == me)).ToListAsync();
}


public class Context : DbContext
{
	public DbSet<Library> Libraries {get;set;}
	public DbSet<Book> Books {get;set;}
	public DbSet<Author> Authors {get;set;}
	
	
	public Context(DbContextOptions opt)
	: base(opt)
	{		
	}	
	
}

public class Library
{
	public Guid Id {get;set;}
	
	public ICollection<Book> MainBooks {get;set;}
	public ICollection<Book> SecondaryBooks {get;set;}
}

public class Book
{
	public Guid Id { get; set; }
	public Author Author { get; set; }

	[InverseProperty("MainBooks")]
	public Library MainLibrary {get;set;}	
	
	[InverseProperty("SecondaryBooks")]	
	public Library SecondayLibrary {get;set;}
}

public class Author
{
	public Guid Id {get;set;}
}

```

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Not relevant, crashes in any VS. I used LINQPad to run above example.

**Comment by smitpatel** [comment] 2019-06-10 16:41
Duplicate of #14645

**Closed** 2022-10-16 14:24 UTC
Labels: closed-duplicate, customer-reported
