### ISSUE TITLE
Can not load ONE TO MANY relation after loading a ONE TO ONE

### ISSUE THREAD

**Issue by rabirland** [dotnet/efcore#14945] opened 2019-03-07 15:38 UTC
I have the following models:

```
public class Product
{
    [Key]
    [MaxLength(64)]
    public string Code { get; set; }
    
    [...]

    public AirsoftWeapon AirsoftWeapon { get; set; }
}
```

```
public class AirsoftWeapon
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ID { get; set; }

    [ForeignKey("ProductCode")]
    public Product Product { get; set; }

    [...]

    [ForeignKey("CategoryId")]
    public WeaponCategory Category { get; set; }
}
```

```
public class WeaponCategory
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ID { get; set; }

    [...]

    public ICollection<AirsoftWeapon> Weapons { get; set; }
}
```

So in short: it is a `ONE-TO-ONE` between Product and AirsoftWeapon and a `ONE-TO-MANY` between WeaponCategory and AirsoftWeapon.

Loading the product with the AirsoftWeapon works without problem: `this._dbContext.Products.Where(m => m.Code == code).Include(p => p.AirsoftWeapon).Single()`

But in the moment I also try to load the WeaponCategory, I get an exception:
```
this._dbContext.Products.Where(m => m.Code == code)
                .Include(p => p.AirsoftWeapon)
                .ThenInclude(w =>w.Category)
                .Single();
```
Side note: I've tried with every possible parameter combinations I could find for eager loading.

The loading fails with the given exception:
`		_message	"Field 'Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Models.Product,System.Collections.Generic.IEnumerable`1[Models.AirsoftWeapon]].Inner' is not defined for type 'Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Models.Product,Models.AirsoftWeapon]'"	string`

**Comment by rabirland** [comment] 2019-03-07 15:44
It looks like loading the first level (Include) works for ONE-TO-ONE but when loading the deeper levels (ThenInclude) it automatically treats the first relational property as an IEnumerable<> and throws an exception whet it is something else.

**Comment by smitpatel** [comment] 2019-03-07 16:42
Can you try `Include(p => p.AirsoftWeapon.Category)` instead and see if that works?

**Comment by rabirland** [comment] 2019-03-07 17:46
> Can you try `Include(p => p.AirsoftWeapon.Category)` instead and see if that works?

Yep, I tried that too. Even with passing the property names as string, as probably every possible combination.

**Comment by smitpatel** [comment] 2019-03-07 18:58
@rabirland - I used following code by copy pasting your model and query and it works correctly for me.
```C#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database
                db.Add(new Product
                {
                    Code = "a",
                    AirsoftWeapon = new AirsoftWeapon
                    {
                        Category = new WeaponCategory()
                    }
                });

                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                var code = "a";
                var result = db.Products.Where(m => m.Code == code)
                    .Include(p => p.AirsoftWeapon)
                    .ThenInclude(w => w.Category)
                    .Single();
                Console.WriteLine(result.Code);
                Console.WriteLine(result.AirsoftWeapon.ID);
                Console.WriteLine(result.AirsoftWeapon.Category.ID);
            }

            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        // Declare DBSets
        public DbSet<Product> Products { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
        }
    }

    public class Product
    {
        [Key]
        public string Code { get; set; }
        public AirsoftWeapon AirsoftWeapon { get; set; }
    }

    public class AirsoftWeapon
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [ForeignKey("ProductCode")]
        public Product Product { get; set; }

        [ForeignKey("CategoryId")]
        public WeaponCategory Category { get; set; }
    }

    public class WeaponCategory
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        public ICollection<AirsoftWeapon> Weapons { get; set; }
    }
}
```

Please provide full repro code which demonstrate the issue you are seeing.

**Comment by rabirland** [comment] 2019-03-07 20:40
Okay, so I wiped out my entire database with all the previous migrations, and now it works fine. Probably one of the migrations messed up something, that in the end caused this error. If anyone cares, here is the snapshot of every migrations:
https://drive.google.com/open?id=1bonXQNbwnu0Qf35UpnoTVUz93lkPd6Dk

None of them was edited by hand, all of the migrations are auto generated by the Add-Migration command.

**Comment by rabirland** [comment] 2019-03-08 10:09
@ajcvickers EDIT: Haven't fixed. The test database indeed works and some test data in the real database works too, but as soon as I try to query the actual database with actual data, I get an error again.

**Comment by smitpatel** [comment] 2019-03-08 16:56
@rabirland - We need full repro code which throws the exception you are seeing. As I posted the code above, things are working fine for me based on what you have posted.

**Comment by rabirland** [comment] 2019-03-09 09:37
@smitpatel @ajcvickers I granted you a collaborator access to a private repo with the full solution

**Comment by smitpatel** [comment] 2019-03-12 16:25
@rabirland - Can you provide repro steps? What should I do to get your full solution to be running with my localdb and what should I do so I can see the exception happening? Your full solution is quite large and not straight-forward to see how to get the exception.

**Comment by ajcvickers** [comment] 2019-03-22 16:36
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:55 UTC
Labels: closed-could-not-reproduce, customer-reported
