### ISSUE TITLE
Duplicate role when create and atribute on same transaction

### ISSUE THREAD

**Issue by nicollaas94** [dotnet/efcore#9376] opened 2017-08-10 13:01 UTC
Describe what is not working as expected.
If create a new role and atribute that new role to an user on same transaction, the role is duplicated

If you are seeing an exception, include the full exceptions details (message and stack trace).
No exceptions

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
 internal static void SeedDefaultAccount(MyContext context)
        {
            try
            {
                
                context.BeginTransaction();
                Role role = context.Set<Role, Guid>().AsQueryable().FirstOrDefault();
                if(role == null)
                {
                    var roleManager = new RoleManager<Role, Guid>(new RoleStore<Role, Guid>(context));

                    role = new Role
                    {
                        Name = "Admin"
                    };

                    IdentityResult result = roleManager.CreateAsync(role).Result;
                    if (!result.Succeeded)
                    {
                        throw new Exception();
                    }
                }

                User user = context.Set<User, Guid>().AsQueryable().FirstOrDefault();
                if (user == null)
                {
                    var manager = new UserManager<User, Guid>(new UserStore<User, Guid>(context));
                    user = new User()
                    {
                        UserName = "UserName ",
                        Email = "Email@Email.com",
                        EmailConfirmed = true,
                        FirstName = "First",
                        LastName = "Last"
                    };


                    IdentityResult result = manager.CreateAsync(user, "password").Result;
                    if (!result.Succeeded)
                    {
                        throw new Exception();
                    }
                    manager.AddToRole<User, Guid>(user.Id, "Admin");
                }
                context.Commit();
            }
            catch (Exception)
            {
                context.Rollback();
                throw;
            }
```

this result in duplicate role "Admin"
If we commit the context before create the user, only one Admin role is created

I guess this is a bug on UserManager, can you guys confirm?

**Comment by divega** [comment] 2017-08-11 18:46
@HaoK can you please do the initial investigation this? Let us know if it is an issue with EF Core rather than with the way it is being used.

**Comment by HaoK** [comment] 2017-08-11 19:39
This usage pattern is a bit weird, but if you are trying to control when save changes are being called, you set AutoSaveChanges = false on both the Role and UserStores, can you see if that fixes things?

**Comment by nicollaas94** [comment] 2017-08-15 11:06
AutoSaveChanges are false, I'll try to get time to create an sample today

**Comment by ajcvickers** [comment] 2017-08-30 20:35
@HaoK Any more thoughts on this?

**Comment by HaoK** [comment] 2017-08-30 21:04
At this point we need a complete repro to investigate further to see if there's any bugs or if its just an issue in how things are being used in the app.

**Comment by ajcvickers** [comment] 2017-09-06 18:31
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:14 UTC
Labels: closed-could-not-reproduce
