### ISSUE TITLE
Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.3.0

### ISSUE THREAD

**Issue by Parilar** [dotnet/efcore#16948] opened 2019-08-05 07:51 UTC
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Das System kann die angegebene Datei nicht finden.`

I got a fresh dll project with Net.Core 2.2 as target. Only using 2 packages  :
-Microsoft.EntityFrameworkCore
-Microsoft.EntityFrameworkCore.Tools

#7889 doesnt solved the problem. I dont have app.config. 
Any other solutions to fix this problem ?

**Comment by Parilar** [comment] 2019-08-05 08:50
My .csproj file :

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
      <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
      <ApplicationIcon />
      <OutputType>Library</OutputType>
      <StartupObject />

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.2.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      
    </PackageReference>

  </ItemGroup>

  <ItemGroup>
    <Compile Update="Class1.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>



</Project>
```

**Comment by ajcvickers** [comment] 2019-08-05 16:22
@Parilar There isn't enough information here for me to be able to reproduce what you are seeing. Please post a small, runnable project/solution or complete code listing.

**Comment by Parilar** [comment] 2019-08-05 17:57
Attached 
[RPGCore.zip](https://github.com/aspnet/EntityFrameworkCore/files/3468772/RPGCore.zip)

**Comment by ajcvickers** [comment] 2019-08-06 18:29
@Parilar I can build your solution fine, but there's no code to run. How should I reproduce the issue?

**Comment by Parilar** [comment] 2019-08-06 18:31
@ajcvickers its an dll, if you import it to a console project it doesnt work

**Comment by ajcvickers** [comment] 2019-08-06 18:33
@Parilar Then create a solution that contains both those things together so that I can run it and see the same thing you are seeing.

**Comment by ajcvickers** [comment] 2019-08-14 16:18
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:34 UTC
Labels: closed-could-not-reproduce, customer-reported
