### ISSUE TITLE
What code is generated to process records from SqlClient?

### ISSUE THREAD

**Issue by thargol1** [dotnet/efcore#25035] opened 2021-06-04 07:42 UTC
# What code is generated to process records from SqlClient?

I was reading #24494 and looked at the performance benchmarks source code. 

The 'low level' ADO.Net code used is about the slowest you can use:

For example it uses:
```csharp
 CustomMonthAbbreviation = Convert.ToString(reader["CustomMonthAbbreviation"]),
```

But in an environment where you generate the query yourself you know all the column-indexes, you know the column types etc.

In my (old) code I use for example (generated by a custom tool):
```csharp
var data = new object[10]; // We know the number of fields a query will return and allocate buffer outside the loop
while(reader.Read()) // The reader is created with CommandBehavior.SequentialRead
{
     reader.GetValues(data); // This line is the huge performance gainer
     rows.Add(new Demo
     {
          Field0 = (int)data[0];
          Field1 = data[1] as string;
          Field2 = data[2] == DBNull.Value ? null : (datetime)data[2];
          // etc
     }
}
reader.
```
The smaller the resultset the larger the performance difference compared to the code in the benchmark. I did not keep my tests results from a few years back, but I measured improvements up to 25%.

So I went to look for the code that actually reads a record from SQL-server but got a little bit lost in this huge repository.

I did find a few calls to `GetOrdinal()` and that's something you will never need if you control the query being executed.

Is there room for improvement in the code that's generated now?

**Comment by roji** [comment] 2021-06-04 19:46
EF Core internally does not use `Convert.ToString(reader["CustomMonthAbbreviation"])`; it generally code-generates calls to GetIn32, GetString (and sometimes `GetFieldValue<T>`). Null is checked via IsDBNull, but when EF knows that a column can't contain nulls (because it's configured that way in the model), there's no null check at all.

As discussed in https://github.com/dotnet/datalab/issues/10#issuecomment-854652244, it doesn't seem like there's a significant perf benefit in using GetValues instead. In addition, this code is general for all relational providers, so it's not SqlClient-specific; and switching to GetValues as a general strategy would be a pretty bad idea. It's theoretically possible to do a specialized path for SqlClient, but that's quite non-trivial and most probably isn't worth it for the gains you saw.

**Comment by roji** [comment] 2021-06-04 19:49
BTW we have an issue for looking into the shaper delegate (the code that reads from DbDataReader): https://github.com/dotnet/efcore/issues/24799

**Comment by roji** [comment] 2021-06-04 19:49
Duplicate of #24799

**Comment by thargol1** [comment] 2021-06-07 17:35
Thanks for the good answers.

**Closed** 2022-10-16 19:36 UTC
Labels: customer-reported
