### ISSUE TITLE
Where Any + Contains is not translated

### ISSUE THREAD

**Issue by Tommigun1980** [dotnet/efcore#21086] opened 2020-05-30 00:12 UTC
A string search such as

``` C#
            var searchTerms = query.Split(' ', ',', '.', ';');

            return this.someDbContext.SomeDataSet.AsNoTracking()
                .Where(someData => searchTerms.Any(term => someData.SomeString.Contains(term)))
                .ToListAsync();
```

Results in 'xxx could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'

If this is not supported, if possible, please advice on how to rewrite it as one query that gets executed on server-side.

### Further technical details

EF Core version: Latest version 3, latest version 5 preview.
Database provider: SQLite
Target framework: .NET Core 3.1
Operating system: macOS 10.15.4
IDE: VS For Mac 8.7 Preview build 522

**Comment by roji** [comment] 2020-05-30 12:16
There isn't really a (standard) SQL construct that corresponds to what you're trying to do, which is why EF Core doesn't translate your LINQ expression. In SQL Server, you can use a LIKE expression for this:

```c#
return this.someDbContext.SomeDataSet.AsNoTracking()
    .Where(someData => EF.Functions.Like(someData.SomeString, "%[ ,.;]%"))
    .ToListAsync();
```

You could parameterize the pattern string here similarly to how your `searchTerms` is parameterized in your original query. Sqlite does not support brackets in LIKE, so unless I'm missing something you're going to have to rewrite this is a series of OR conditions.

You could simply rewrite this as multiple conditions:

someData.SomeString.Contains(' ') || someData.SomeString.Contains(',')

**Comment by Tommigun1980** [comment] 2020-05-30 12:48
> There isn't really a (standard) SQL construct that corresponds to what you're trying to do, which is why EF Core doesn't translate your LINQ expression. In SQL Server, you can use a LIKE expression for this:
> 
> ```cs
> return this.someDbContext.SomeDataSet.AsNoTracking()
>     .Where(someData => EF.Functions.Like(someData.SomeString, "%[ ,.;]%"))
>     .ToListAsync();
> ```
> 
> You could parameterize the pattern string here similarly to how your `searchTerms` is parameterized in your original query. Sqlite does not support brackets in LIKE, so unless I'm missing something you're going to have to rewrite this is a series of OR conditions.
> 
> You could simply rewrite this as multiple conditions:
> 
> someData.SomeString.Contains(' ') || someData.SomeString.Contains(',')

Hi and thanks for the reply! Oh I see.
(Regarding the suggestions; I am actually splitting the input string by certain delimiters so I don’t know the terms beforehand, hence those wouldn’t work. I am essentially comparing any word in a string against any word in a column for a match).

**Comment by roji** [comment] 2020-05-30 16:14
Understood - I'd try to see if it's possible to change the application so it doesn't have to do something like this. In particular, if the number of patterns (characters or words) which you need to search for is variable, then the LINQ queries searching for them is going to be dynamic (one version for 3, another for 4...). This is simply not a scenario that SQL handles well AFAIK - but maybe someone else from the team will have a better idea.

**Comment by Tommigun1980** [comment] 2020-05-30 16:52
> Understood - I'd try to see if it's possible to change the application so it doesn't have to do something like this. In particular, if the number of patterns (characters or words) which you need to search for is variable, then the LINQ queries searching for them is going to be dynamic (one version for 3, another for 4...). This is simply not a scenario that SQL handles well AFAIK - but maybe someone else from the team will have a better idea.

Thanks for your help, I really appreciate it. What I'm doing is essentially a really trivial search function, where the user can enter a string and I search a database for occurrences of it. When I ran into this problem a quick Googling showed multiple people suggesting the same snippet I already had, claiming it should be executed on server side, hence the initial bug report.

**Comment by MarcAnnous** [comment] 2020-05-30 21:11
searchTerms here will be a list of strings (ex. word1, word2, word3) and the Where should translate to something like:

`WHERE C LIKE '%word1%' OR C LIKE '%word2%' OR C LIKE '%word3%'`

**Comment by ajcvickers** [comment] 2020-06-01 21:57
Duplicate of #19070

**Closed** 2022-10-16 18:27 UTC
Labels: customer-reported
