### ISSUE TITLE
Migrations Bundle fails with Blazor sln

### ISSUE THREAD

**Issue by mabster** [dotnet/efcore#29491] opened 2022-11-07 03:26 UTC
Hi gang,

We have a GitHub Actions workflow that builds our hosted WASM Blazor solution, then generates a migrations bundle executable to apply to the database before deploying.

With actions/setup-dotnet@v1 everything worked fine. However, with actions/setup-dotnet@v3 the "dotnet ef migrations bundle" command is failing.

The relevant error is this, as it tries to publish the efbundle.exe file:

```
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.10\Sdk\WasmApp.targets(161,5): error : $(MicrosoftNetCoreAppRuntimePackDir)='', and cannot find %(ResolvedRuntimePack.PackageDirectory)=. One of these need to be set to a valid path [D:\a\puckster\puckster\Puckster.Client\Puckster.Client.csproj]
```

The step in our workflow is simple enough:

```
 - name: Generate EF migration script
        run: dotnet ef migrations bundle --startup-project Puckster.Server --output ./efbundle.exe --configuration Bundle --verbose
```

Can someone help? I'm about to roll back to setup-dotnet@v1 just to make sure that gets us working again, but I don't know why the bundle packaging is failing now when it worked just fine before.

**Comment by mabster** [comment] 2022-11-07 03:34
Can confirm that `dotnet ef migrations bundle` works just fine now that I've reverted to `setup-dotnet@v1`. Now trying again with `setup-dotnet@v2`.

**Comment by mabster** [comment] 2022-11-07 22:32
FYI I have created a public project that reproduces this issue!

https://github.com/mabster/efbundle-repro/

... and specifically check out this workflow run, which failed once we updated from setup-dotnet@v2 to setup-dotnet@v3:

https://github.com/mabster/efbundle-repro/actions/runs/3414555616/jobs/5682667061

Hope this helps!

**Comment by bricelam** [comment] 2023-01-10 19:19
Duplicate of https://github.com/dotnet/aspnetcore/issues/44182

**Closed by bricelam** 2023-01-10 19:19 UTC
Labels: Servicing-consider, customer-reported
