### ISSUE TITLE
SqlQuery missing from EF7... please add

### ISSUE THREAD

**Issue by giancarloa** [dotnet/efcore#4429] opened 2016-01-29 16:34 UTC
Hi... in EF6 we could query non entity projections with raw SQL using Database.SqlQuery... that was REALLY cool... but I am trying to migrate to EF7 and don't see this method... I looked around and it appears people are saying to use FromSql instead but that's an extension method off of a DbSet... in my case I don't have a DbSet for the type in question because it's not an entity... it's just a plain old projection... pretty please consider bringing SqlQuery to EF7... thank you

**Comment by rowanmiller** [comment] 2016-01-29 17:11
Duplicate of https://github.com/aspnet/EntityFramework/issues/1862

**Comment by badyalsk** [comment] 2017-02-01 14:28
In Entity Framework Core, we are not able to return some complex type(columns from different entities) from Stored Procedure using RAW SQL. It alway returns Entity in DbSet. When we are expecting to add support for this functionality in EF Core. What are the alternatives?

**Comment by doggy8088** [comment] 2018-08-13 18:56
@badyalsk The alternative should be [Query Types](https://docs.microsoft.com/en-us/ef/core/modeling/query-types) in EF Core 2.1.

**Closed** 2022-10-16 09:27 UTC
