### ISSUE TITLE
Do not build whole Solution on Add-Migration

### ISSUE THREAD

**Issue by sdunst** [dotnet/efcore#11283] opened 2018-03-15 15:59 UTC
Problem
When adding a new Migration the whole solution is build every time. Because I am working in a solution with a second Startup Project that takes a while to build, the creation of a new Migration is really slow

Possible solutions:

- I think it would be enough to only build the Startup Project of the current Add-Migration command. Especially because it is necessary, that the Startup Project references the EF-Core Assembly anyway.

**Comment by bricelam** [comment] 2018-03-16 16:25
There's [a TODO for that](https://github.com/aspnet/EntityFrameworkCore/blob/2.0.2/src/EFCore.Tools/tools/EntityFrameworkCore.psm1#L729). I tried to do it that way earlier on, but ran into limitations in the EnvDTE APIs...

**Comment by bricelam** [comment] 2018-03-16 22:24
Duplicate of #9716

**Closed** 2022-10-16 12:14 UTC
