### ISSUE TITLE
SqlNullValueException when one column of a composite FK is NULL

### ISSUE THREAD

**Issue by cchdev** [dotnet/efcore#14355] opened 2019-01-09 16:44 UTC
Given a foreign key composed of two columns.
The first column is marked 'not null'.
The second column is marked 'null'.

When materializing a record with NULL as second column value.

Then EF throws SqlNullValueException.

Expected behavior: materialize an entity with null as second property value.

This worked with EF Core 2.1.1
This issue prevents us from upgrading to EF Core 2.2+ as we are in DB First scenario with no possibility to alter the schema.

```
With 'detailed errors' option enabled.
Exception message: An exception occurred while reading a database value for property '[Property2]'. The expected type was 'System.String' but the actual value was null.
Stack trace:    at Microsoft.EntityFrameworkCore.Storage.TypedRelationalValueBufferFactoryFactory.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)
   at EfBugRepro.ReproUnitTests.DataMaterializationThrowsSqlNullException() in C:\wk\EfBugRepro\ReproUnitTests.cs:line 23
```

### Steps to reproduce
See full repro project attached with unit test.

### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10 x64
IDE: Visual Studio 2017 15.9.5
[EfBugRepro.zip](https://github.com/aspnet/EntityFrameworkCore/files/2741751/EfBugRepro.zip)

**Comment by ajcvickers** [comment] 2019-01-09 18:05
Note for triage: In 2.2, both string FK properties are marked as required, which is incorrect; see models below.

2.2:
```
Model: 
  EntityType: Catalog
    Properties: 
      BunCode (string) Required PK AfterSave:Throw 0 0 0 -1 -1
      CatCode (string) Required PK AfterSave:Throw 1 1 1 -1 -1
      CatLabel (string) 2 2 -1 -1 -1
    Keys: 
      BunCode, CatCode PK
  EntityType: Product
    Properties: 
      BunCode (string) Required PK FK Index AfterSave:Throw 0 0 0 -1 -1
      PrdCode (string) Required PK AfterSave:Throw 1 1 1 -1 -1
>>    CatCode (string) Required FK Index 2 2 2 -1 -1
      PrdLabel (string) 3 3 -1 -1 -1
    Navigations: 
      Catalog (<Catalog>k__BackingField, Catalog) ToPrincipal Catalog 0 -1 3 -1 -1
    Keys: 
      BunCode, PrdCode PK
    Foreign keys: 
      Product {'BunCode', 'CatCode'} -> Catalog {'BunCode', 'CatCode'} ToPrincipal: Catalog
```
2.1:
```
Model: 
  EntityType: Catalog
    Properties: 
      BunCode (string) Required PK AfterSave:Throw 0 0 0 -1 -1
      CatCode (string) Required PK AfterSave:Throw 1 1 1 -1 -1
      CatLabel (string) 2 2 -1 -1 -1
    Keys: 
      BunCode, CatCode PK
  EntityType: Product
    Properties: 
      BunCode (string) Required PK FK Index AfterSave:Throw 0 0 0 -1 -1
      PrdCode (string) Required PK AfterSave:Throw 1 1 1 -1 -1
>>      CatCode (string) FK Index 2 2 2 -1 -1
      PrdLabel (string) 3 3 -1 -1 -1
    Navigations: 
      Catalog (<Catalog>k__BackingField, Catalog) ToPrincipal Catalog 0 -1 3 -1 -1
    Keys: 
      BunCode, PrdCode PK
    Foreign keys: 
      Product {'BunCode', 'CatCode'} -> Catalog {'BunCode', 'CatCode'} ToPrincipal: Catalog
```
Code:
```C#
public class Catalog
{
    public string BunCode { get; set; }
    public string CatCode { get; set; }
    public string CatLabel { get; set; }
}

public class Product
{
    public string BunCode { get; set; }
    public string PrdCode { get; set; }
    public string PrdLabel { get; set; }
    public string CatCode { get; set; } // optional
    public Catalog Catalog { get; set; } // optional
}


public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Catalog>(catalog =>
        {
            catalog.ToTable("Catalog", "dbo");
            catalog.HasKey(x => new { x.BunCode, x.CatCode });
        });

        modelBuilder.Entity<Product>(product =>
        {
            product.ToTable("Product", "dbo");
            product.HasKey(x => new { x.BunCode, x.PrdCode });

            // Configure Product --> Catalog navigation property
            product.HasOne(x => x.Catalog)
                .WithMany()
                .HasForeignKey(x => new { x.BunCode, x.CatCode });
        });
    }
}
```

**Comment by AndriySvyryd** [comment] 2019-01-09 21:56
Dupe of https://github.com/aspnet/EntityFrameworkCore/issues/14157

**Closed** 2022-10-16 13:46 UTC
Labels: customer-reported
