### ISSUE TITLE
How can I perform a join operation between an in-memory list and a SQL database table using EFCore

### ISSUE THREAD

**Issue by Esperadoce** [dotnet/efcore#33414] opened 2024-03-27 13:54 UTC
I have the following code : 

```cs
List<MyComplexObject> listInMemory = new List<MyComplexObject>
{
    new MyComplexObject { Id1 = 1, Id2 = 2, Name = "Name1" },
    new MyComplexObject { Id1 = 3, Id2 = 4, Name = "Name2" }
};

// And a DbSet in your DbContext
public DbSet<MyEntity> MyEntities { get; set; }


var result = MyEntities
    .Join(listInMemory, 
          entity => new { entity.Id1, entity.Id2 }, 
          complexObject => new { complexObject.Id1, complexObject.Id2 }, 
          (entity, complexObject) => entity);
   ```
I'm trying to verify a list of elements that exist in memory against something in my database, but I'm encountering this error.

> resultSelector: (entity, complexObject) => entity)' could not be
> translated

My problem would be simpler if I only have a list of in that case i could use  something like this `.Where(entity=>listOfIds.Contains(entity.Id))`  unfortunately  I have 2 "ids" that I need to check and I tried a list.Any but didn't work either

**Comment by roji** [comment] 2024-03-27 15:00
Since 8.0, EF supports joining on a **primitive** list (that is, a list of ints, strings...) - as well as any other LINQ operator - but it does not yet support lists of complex types. #31237 is the issue tracking that.

**Comment by roji** [comment] 2024-03-27 15:01
Duplicate of #31237

**Closed by roji** 2024-03-27 15:01 UTC
Labels: customer-reported, area-query
