### ISSUE TITLE
Discriminator column ignoring base

### ISSUE THREAD

**Issue by ReginaldBull** [dotnet/efcore#9326] opened 2017-08-03 09:40 UTC
I'm having a entity RoleClaim that inherits from Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityRoleClaim.

``` C#
public class RoleClaim : IdentityRoleClaim<string>
    {
        public virtual Role Role { get; set; }
    }

In the DbContext the IdentityRoleClaim is ignored with 
protected override void OnModelCreating(ModelBuilder builder)
{
            builder.Ignore<IdentityRoleClaim<string>>();
}
```

The mapping of the class:
``` C#
        public static void Map(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<RoleClaim>()
                .ToTable("RoleClaims")
                .HasKey(x => x.Id);

            modelBuilder.Entity<RoleClaim>().Property(x => x.Id).HasColumnName("Id");
            modelBuilder.Entity<RoleClaim>().Property(x => x.ClaimType).HasColumnName("ClaimType");
            modelBuilder.Entity<RoleClaim>().Property(x => x.ClaimValue).HasColumnName("ClaimValue");
            modelBuilder.Entity<RoleClaim>().Property(x => x.RoleId).HasColumnName("RoleId");

            modelBuilder.Entity<RoleClaim>().HasOne(x => x.Role).WithMany(role => role.Claims).HasForeignKey(claim => claim.RoleId);
        }
```
But in the migration I'm still getting a Discriminator column. 

### Further technical details
EF Core version: Microsoft.EntityFrameworkCore (1.1.2)
Database Provider: MySql.Data.EntityFrameworkCore (8.0.8-dmr)
Operating system: Windows 10
IDE: Visual Studio 2017
Framework: .NETCOREAPP 1.1

**Comment by divega** [comment] 2017-08-11 09:09
@HaoK could you please help with an initial investigation of this in case it has to do with how things are configured in the model in ASP.NET Identity?

As it says above, this is 1.1.2, so there are still navigation properties.

**Comment by HaoK** [comment] 2017-08-11 18:26
@ReginaldBull can you include the entire DbContext class especially the full OnModelCreating method?

**Comment by ReginaldBull** [comment] 2017-08-22 07:59
`public class DsmIdentityEntities : IdentityDbContext
    {
        internal IConfigurationRoot Configuration { get; set; }

        public DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public DbSet<ApplicationUserRole> ApplicationUserRoles { get; set; }
        public DbSet<ApplicationRole> ApplicationRoles { get; set; }
        public DbSet<ApplicationUserToken> ApplicationUserTokens { get; set; }
        public DbSet<ApplicationUserLogin> ApplicationUserLogins { get; set; }
        public DbSet<ApplicationUserClaim> ApplicationUserClaims { get; set; }
        public DbSet<ApplicationRoleClaim> ApplicationRoleClaims { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var builder =
                new ConfigurationBuilder().AddJsonFile("appsettings.json", optional: false, reloadOnChange: false);
            Configuration = builder.Build();
            optionsBuilder.UseMySQL(Configuration.GetConnectionString("Connection"));
        }

protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Ignore<IdentityRole>();
            builder.Ignore<IdentityRoleClaim<string>>();
            builder.Ignore<IdentityUserClaim<string>>();
            builder.Ignore<IdentityUserLogin<string>>();
            builder.Ignore<IdentityUser>();
            builder.Ignore<IdentityUserRole<string>>();
            builder.Ignore<IdentityUserToken<string>>();

ApplicationRoleMapping.Map(builder);
            ApplicationRoleClaimMapping.Map(builder);
            ApplicationUserClaimMapping.Map(builder);
            ApplicationUserLoginMapping.Map(builder);
            ApplicationUserMapping.Map(builder);
            ApplicationUserRoleMapping.Map(builder);
            ApplicationUserTokenMapping.Map(builder);
}`

And for example:

` public class ApplicationUserTokenMapping
    {
        public static void Map(ModelBuilder modelBuilder)
        {
            var builder = modelBuilder.Entity<ApplicationUserToken>();
            builder.ToTable("Tokens")
                .HasKey(x => new
                {
                    x.UserId,
                    x.LoginProvider,
                    x.Name
                });
            builder.Property(x => x.UserId).HasColumnName("UserId");
            builder.Property(x => x.LoginProvider).HasColumnName("LoginProvider");
            builder.Property(x => x.Name).HasColumnName("Name");
            builder.Property(x => x.Value).HasColumnName("Value");
        }
    }`

**Comment by HaoK** [comment] 2017-08-22 16:14
@ReginaldBull can you try calling base in your OnModelCreating at the top to see if that fixes the issue?

**Comment by ReginaldBull** [comment] 2017-08-23 14:25
I have modified my OnModelCreating to this
`
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Ignore<IdentityRole>();
            builder.Ignore<IdentityRoleClaim<string>>();
            ....
            }
`
And get this exception:  

>  The index {'UserId'} cannot be added to the entity type 'IdentityUserClaim<string>' because an index on the same properties already exists on entity type 'ApplicationUserClaim'.

**Comment by ajcvickers** [comment] 2017-08-30 20:35
@HaoK Any more thoughts on this?

**Comment by HaoK** [comment] 2017-08-30 21:02
@ReginaldBull can you also include your startup ConfigureServices that shows your AddIdentity and related calls especially?

**Comment by ReginaldBull** [comment] 2017-09-04 08:25
Currently I'm using it from an UnitTest project.

**Comment by HaoK** [comment] 2017-09-05 16:58
If its a unit test, that should be easy to reproduce, can you include the minimal code needed to reproduce the issue you are seeing?

**Comment by ReginaldBull** [comment] 2017-09-11 14:52
I will try to create a minimal example for you

**Comment by ajcvickers** [comment] 2017-09-18 18:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:14 UTC
Labels: closed-could-not-reproduce
