### ISSUE TITLE
How to create a composite index with complex property ?

### ISSUE THREAD

**Issue by chouteau** [dotnet/efcore#32578] opened 2023-12-09 17:28 UTC
Example:

```C#
using Microsoft.EntityFrameworkCore;

var db = new MyDbContext();

db.Database.EnsureDeleted();
db.Database.EnsureCreated();

public class MyData
{
    public Guid Id { get; set; }
	public MyComplexProperty Complex { get; set; } = new();
}

public class MyComplexProperty
{
	public int MyId { get; set; }
	public string MyString { get; set; } = null!;
}

public class MyDbContext : DbContext
{
	public DbSet<MyData> MyData { get; set; } = null!;

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		=> optionsBuilder.UseInMemoryDatabase("MyDb");

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<MyData>()
			.ComplexProperty(e => e.Complex);

		modelBuilder.Entity<MyData>().HasIndex(i => new { i.Complex.MyId, i.Complex.MyString });
	}
}
```

I have an issue when the program is started :

```
The expression 'i => new <>f__AnonymousType0`2(MyId = i.Complex.MyId, MyString = i.Complex.MyString)' is not a valid member access expression. The expression should represent a simple property or field access: 't => t.MyProperty'. When specifying multiple properties or fields, use an anonymous type: 't => new { t.MyProperty, t.MyField }'. (Parameter 'memberAccessExpression')
```

I can't seem to find a way to create a potentially unique covering index using the new feature of Entity Framework 8 with complex properties, could you help me please ?

EF Core version: 8
Database provider: (e.g. Microsoft.EntityFrameworkCore.InMemorty or others)
Target framework: (e.g. .NET 8.0)

**Comment by ajcvickers** [comment] 2023-12-10 11:06
Duplicate of #31246. Please vote (👍) for that issue.

**Closed by ajcvickers** 2023-12-10 11:06 UTC
Labels: customer-reported
