### ISSUE TITLE
InMemoryDatabase - Different scopes sharing the same Incrementing Key intended?

### ISSUE THREAD

**Issue by divinci** [dotnet/efcore#11826] opened 2018-04-26 11:04 UTC
When using different InMemory database scopes there seems to be a shared incrementing key.

Is this intended as it seems very counter-intuitive! 

See this gist to get the gist.

https://gist.github.com/divinci/4503e13d14d449459aaa88fb9f737676

**Comment by ajcvickers** [comment] 2018-04-26 16:59
Duplicate of #6872

**Closed** 2022-10-16 12:21 UTC
