### ISSUE TITLE
Using enums a cast exception is thrown

### ISSUE THREAD

**Issue by TonyTroeff** [dotnet/efcore#19713] opened 2020-01-26 21:03 UTC
One of my entities has a property of type enum. I use PostgreSql for my database storage and when I test it manually, it works as expected. However, when I want to test it through code (where I use Sqlite), the following exception is thrown:

```
Message: 
    System.InvalidCastException : Unable to cast object of type 'MyEnumType' to type 'System.Int64'.
Stack Trace: 
    ValueComparer`1.Equals(Object left, Object right)
    ChangeDetector.LocalDetectChanges(InternalEntityEntry entry)
    ChangeDetector.DetectChanges(IStateManager stateManager)
    ChangeTracker.DetectChanges()
    DbContext.TryDetectChanges()
    DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```
I do not want to make my enum of type long just for testing purposes - I will never have as much options.
I expect that this exception should never be thrown and I can use enums of whatever type I prefer.

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4

**Comment by ajcvickers** [comment] 2020-01-27 16:18
@TonyTroeff Please attach a small, runnable project or post a complete code listing that reproduces what you are seeing so that we can investigate.

**Comment by hossamdarwish** [comment] 2020-01-28 15:22
Some providers raise this issue (Cosmos in my case).. Please try this quick workaround
Instead of
`var query = ctx.Jobs.Where(x => x.Shift == ShiftType.Day);`
Try
`var workaround = ShiftType.Day;
                var query = ctx.Jobs
                    .Where(x => x.Shift == workaround);`

**Comment by ajcvickers** [comment] 2020-01-28 17:55
Related: #19128

**Comment by ajcvickers** [comment] 2020-01-28 18:16
@maumar to take a look.

**Comment by maumar** [comment] 2020-02-01 01:02
dupe of #19128

**Comment by TonyTroeff** [comment] 2020-02-07 20:54
The values for the entity are taken from a view model. How should it be parametrized?

**Closed** 2022-10-16 18:07 UTC
Labels: customer-reported
