### ISSUE TITLE
Nullreferencexception scaffolding foreign key without primary key (regression)

### ISSUE THREAD

**Issue by kobruleht** [dotnet/efcore#29828] opened 2022-12-12 10:12 UTC
Create tables in Postgres 15 or earlier database

```
create table testdok ( dokumnr serial primary key );

CREATE table testSKONTROL (
  dokumnr integer not null  references testdok on update cascade on delete cascade deferrable
 );

```

Scaffold database using ef core data provider for PostgreSql.

Observed:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.EntityFrameworkCore.Design
  StackTrace:
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContextGenerator.TransformText() in Microsoft.EntityFrameworkCore.Scaffolding.Internal\CSharpDbContextGenerator.cs:line 254
```

<img width="887" alt="image" src="https://user-images.githubusercontent.com/1274923/207019558-d7881fa6-7851-46ea-bcde-7e812f54f2e7.png">

EF Core version: 7.0
Database provider:  https://github.com/npgsql/efcore.pg
Target framework: .NET 7.0
Operating system: Windows 11
IDE: Visual Studio 2022 Version 17.4.2

**Comment by ajcvickers** [comment] 2022-12-12 10:18
Duplicate of #29516.

**Closed by ajcvickers** 2022-12-12 10:18 UTC
Labels: customer-reported
