### ISSUE TITLE
Add documentation about what is changed/removed from EF6

### ISSUE THREAD

**Issue by mjrousos** [dotnet/efcore#3796] opened 2015-11-19 14:52 UTC
I recently ported a website that used EF6 to use EF7 instead. It would be very helpful for that scenario to have a document listing the EF6 features which are missing/changed in EF7. 

Many changes are obvious, but some are not. In my case, specifically, I didn't realize that lazy loading didn't work in EF7. So, everything _appeared_ to port over fine but related objects were all null. I spent a while trying to figure out if my model had somehow misconfigured foreign keys/relationships before realizing that the objects simply weren't loaded.

Some bullet points of 'things to know while transitioning from EF6' would have saved a lot of time.

**Comment by ErikEJ** [comment] 2015-11-19 15:10
EF7 in its current state is not designed for "porting" from EF6

**Comment by rowanmiller** [comment] 2015-11-19 17:51
Duplicate of https://github.com/aspnet/EntityFramework.Docs/issues/40

**Closed** 2022-10-16 09:16 UTC
