### ISSUE TITLE
ExecuteUpdate throws exception when entity has an autoinclude

### ISSUE THREAD

**Issue by Samuel-Castilho** [dotnet/efcore#29976] opened 2023-01-04 11:20 UTC
## File a bug

Execute update throws exception when entity has an autoinclude
If you comments the lines on OnModelCreating that sets the autoinclude the code runs seamlessly
### Include your code
```C#
using Microsoft.EntityFrameworkCore;

SimpleContext ctx = new SimpleContext();

ctx.TableA.ExecuteUpdate(spc => spc
    .SetProperty(x => x.Name, "AAAAA")
);


public class SimpleContext : DbContext
{

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Data Source=mydb.db");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ClassA>(x =>
            x.Navigation(CA => CA.NavigationProperty).AutoInclude()
        );

        modelBuilder.Entity<ClassA>().HasData(
            new ClassA[]
            {
                new ClassA(){Id= 1,Name="z"},
                new ClassA(){Id= 2,Name="x"},
                new ClassA(){Id= 3,Name="c"}
            }
        );
    }

    public DbSet<ClassA> TableA { get; set; }
    public DbSet<ClassB> TableB { get; set; }

}

public class ClassA
{
    public int Id { get; set; }
    public string Name { get; set; }
    public ClassB? NavigationProperty { get; set; }
}

public class ClassB
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

### Include stack traces

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The LINQ expression 'DbSet<ClassA>()
    .LeftJoin(
        inner: DbSet<ClassB>(), 
        outerKeySelector: c => EF.Property<int?>(c, "NavigationPropertyId"), 
        innerKeySelector: c0 => EF.Property<int?>(c0, "Id"), 
        resultSelector: (o, i) => new TransparentIdentifier<ClassA, ClassB>(
            Outer = o, 
            Inner = i
        ))
    .Select(c => IncludeExpression(
        EntityExpression:
        c.Outer, 
        NavigationExpression:
        c.Inner, NavigationProperty)
    )
    .ExecuteUpdate(spc => spc.SetProperty<string>(
        propertyExpression: x => x.Name, 
        valueExpression: "AAAAA"))' could not be translated. Additional information: The following lambda argument to 'SetProperty' does not represent a valid property to be set: 'x => x.Name'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteUpdate[TSource](IQueryable`1 source, Expression`1 setPropertyCalls)
   at Program.<Main>$(String[] args) in C:\*\Program.cs:line 5
```

### Include provider and version information

EF Core version: 7.0.1
Database provider: Microsoft.EntityFrameworkCore.Sqlite 7.0.1 (the same happens with sqlserver)
Target framework: NET 7.0
Operating system: Windows 10
IDE:  Visual Studio 2022 17.4.3

**Comment by ErikEJ** [comment] 2023-01-04 11:28
@Samuel-Castilho Where does AutoInclude() come from?

**Comment by ajcvickers** [comment] 2023-01-04 12:41
@roji Related to #28727. Does the owned type fix cover auto-includes? If not, is there a way to tell a query to ignore auto-includes?

**Comment by roji** [comment] 2023-01-05 21:03
Duplicate of #28727

**Closed** 2023-01-06 11:14 UTC
Labels: customer-reported
