### ISSUE TITLE
SQLite Identity schema generated migration creates Annotation with Compiler error

### ISSUE THREAD

**Issue by jwdavidson** [dotnet/efcore#2983] opened 2015-09-02 16:42 UTC
The beta6-13815 produces a migration from the IdentityModel with the following excerpt

```
        migration.CreateTable(
            name: "AspNetRoleClaims",
            columns: table => new
            {
                Id = table.Column(type: "INTEGER", nullable: false)
                    .Annotation("Sqlite:Autoincrement", true),
                ClaimType = table.Column(type: "TEXT", nullable: true),
                ClaimValue = table.Column(type: "TEXT", nullable: true),
                RoleId = table.Column(type: "TEXT", nullable: true)
            },
```

where the Annotation should be 

```
                    .Annotation("Sqlite:Autoincrement", "true"),
```

The Annotation definition in OperationBuilder is 

```
                     Annotation(string, string)
```

**Comment by natemcmaster** [comment] 2015-09-02 16:49
Duplicate of https://github.com/aspnet/EntityFramework/issues/2545. This will be fixed in beta 7 release.

**Closed** 2022-10-16 09:06 UTC
