### ISSUE TITLE
Base entity inheritance and readonly properties

### ISSUE THREAD

**Issue by arruw** [dotnet/efcore#6738] opened 2016-10-09 16:31 UTC
It would be cool if we could:
- configure base entity class using Fluent API
- have readonly fields that are only modified by system (EF or database)

Take a look at following code:

``` cs
public abstract class BaseEntity : IEntity
{
    private Guid _id;
    private DateTime _createdOn;
    private DateTime _modifiedOn;
    private byte[] _timestamp;

    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id => _id;

    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public DateTime CreatedOn => _createdOn;

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime ModifiedOn => _modifiedOn;

    [Timestamp]
    public byte[] Timestamp => _timestamp;
}

public class Category : BaseEntity
{
    [Required]
    public string Name { get; set; }

    public string Description { get; set; }
}
```

[BaseEntityAndReadonlyProperties.zip](https://github.com/aspnet/EntityFramework/files/518420/BaseEntityAndReadonlyProperties.zip)

What do you think? Am I missing something?
Thanks!

**Comment by rowanmiller** [comment] 2016-10-11 18:24
You can't do this with 1.0, but starting with 1.1 you can map to fields. Here is some code that shows it working using our latest nightly build of 1.1.

Note that I did configuration via `Category` so that `BaseEntity` wasn't part of the model. You could do it on `BaseEntity` but then it would be in the model and you would get everything that derives from `BaseEntity` in a single "table per hierarchy" mapping.

Also note that you don't need to explicitly configure the backing field as EF will discover `_<property name>` by convention.

```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EFCore101
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new TestContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                db.Categories.Add(new Category { Name = "Test" });
                db.SaveChanges();

                foreach (var item in db.Categories)
                {
                    Console.WriteLine($"{item.Id} : {item.Name}");
                }
            }
        }
    }

    public class TestContext : DbContext
    {
        public DbSet<Category> Categories { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Demo;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Category>()
                .Property(c => c.Id);

            modelBuilder.Entity<Category>()
                .Property(c => c.CreatedOn)
                .HasDefaultValueSql("GETDATE()");

            modelBuilder.Entity<Category>()
                .Property(c => c.ModifiedOn)
                .HasDefaultValueSql("GETDATE()");

            modelBuilder.Entity<Category>()
                .Property(c => c.Timestamp);
        }
    }

    public abstract class BaseEntity
    {
        private Guid _id;
        private DateTime _createdOn;
        private DateTime _modifiedOn;
        private byte[] _timestamp;

        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id => _id;

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public DateTime CreatedOn => _createdOn;

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime ModifiedOn => _modifiedOn;

        [Timestamp]
        public byte[] Timestamp => _timestamp;
    }

    public class Category : BaseEntity
    {
        [Required]
        public string Name { get; set; }

        public string Description { get; set; }
    }
}
```

**Comment by rowanmiller** [comment] 2016-10-11 18:25
Closing as a dupe of the field mapping feature https://github.com/aspnet/EntityFramework/issues/4461

**Closed** 2022-10-16 10:38 UTC
