### ISSUE TITLE
Query: Support IReadOnlyCollection<T>.Contains

### ISSUE THREAD

**Issue by wdnijdam** [dotnet/efcore#19320] opened 2019-12-14 11:06 UTC
IReadOnlyCollection<>.Contains() cannot be translated to SQL by EF core 3.1
EF core 2.2 supports it

Related issue of ICollection<>: https://github.com/aspnet/EntityFrameworkCore/pull/17599

It seems that a static field fails while a local variable succeeds.

### Steps to reproduce
Create DbContext using EF core 3.1
Declare static field "MyCollection" of type IReadOnlyCollection<> and assign values.
Use the field in linq query .Where(x => mycollection.Contains(x.Prop))

``` C#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp1
{
    static class Program
    { 
        private static readonly IReadOnlyCollection<int> MyCollection = new List<int> {5, 6, 7}.AsReadOnly();

        public static void Main()
        {
            using var context = new MyContext();
            context.Database.EnsureCreated();
            var x = context.Examples
                .Where(e => MyCollection.Contains(e.MyProp))
                .ToList();
            Console.Write(x.Count);
        }

        private class MyContext : DbContext
        {
            public DbSet<ExampleTable> Examples { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer(@"Server=(LocalDb)\MSSQLLocalDB;Database=EFCoreCollectionCrash;Trusted_Connection=True;MultipleActiveResultSets=true");
            }
        }

        private class ExampleTable
        {
            public int ExampleTableId { get; set; }
            public int MyProp { get; set; }
        }
        
    }
}

```

```
The LINQ expression 'DbSet<ExampleTable>
    .Where(e => (IReadOnlyCollection<int>)ReadOnlyCollection<int> { 5, 6, 7, }
        .Contains(e.MyProp))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET Core 3.1
Operating system: Windows x64

Remark this works (as local variable):

``` C#
public static void Main()
        {
            var myCollection = new List<int> {5, 6, 7}.AsReadOnly();

            using var context = new MyContext();
            context.Database.EnsureCreated();
            var x = context.Examples
                .Where(e => myCollection.Contains(e.MyProp))
                .ToList();
            Console.Write(x.Count);
        }
```

It also works if the type of the static field is changed to List<int>

**Comment by smitpatel** [comment] 2019-12-14 19:03
Duplicate of #18658

**Closed** 2022-10-16 18:01 UTC
Labels: customer-reported
