### ISSUE TITLE
context.Merge() - Allow us to Merge disconnected entities in the context, instead of marking them and their children as Added

### ISSUE THREAD

**Issue by mariopaolo** [dotnet/efcore#23044] opened 2020-10-19 05:00 UTC
EF Core is known for the change in paradigm when adding entities to the context.
If the entities are not tracked and are Added to the context, every children get marked as Added.
This causes huge headeaches in one of the most frequent use case for an ORM: query an API for some data and store its results to a database.

I can outline two scenarios where this is crucial:
- Database is empty, API is called for the first time to start populating the DB. API returns many objects and in many cases these objects have nested children that are shared. The local context is flooded with identical children, and each parent has to be scanned through its depth to avoid duplicate keys errors.
- Database has data, API is called to update data in the SQL. The first problem can manifest again, since we need to build the context from disconnected entities before, but now we need to check against the database as well and attach existing entities (here there's also logic to compare the two versions in case of update).

To solve these issues, solutions like [GraphDiff](https://github.com/zzzprojects/GraphDiff) or [Detached](https://github.com/leonardoporro/Detached-Mapper) exist: they **let you merge** new entities as they are added to the context, attaching and reusing existing entities already present in the context.
Unfortunately GraphDiff doesn't support EF Core, and Detached doesn't support every use case.

To me, this is a must have for EF Core and it shouldn't be offloaded to an external project: this would make development so much faster and it will spare us custom logic , with for loops and extensions methods for each entities.

In my specific case I am dealing with entities with existing primary keys, and I need to use them, so I use:
`[DatabaseGenerated(DatabaseGeneratedOption.None)]`
Also, my API returns entities so deeply nested it gives me headeache to approach them with EF Core.

Hence, I kindly ask you:
in the next version of EF Core, please implement methods `context.Merge[Async](entity)` and `context.MergeRange[Async](entities)` that takes the entities and attach all the existing children in the local context, indipendently of the nesting level the parent may have.
Possibly, it should take a function as an argument, to establish the update logic when scanning for and attaching entities already existing in the context.

### Steps to reproduce
Map an API response with nested objects to CodeFirst POCO entities in EF Core and try to add to database.
If parents have shared children you will get a duplicate key error when adding parent to local context. 
When data is present in the DB, you need to scan the DB as well before saving changes and reattach existing entities to avoid duplicate key errors.

### Further technical details
**EF version**: Microsoft.EntityFrameworkCore 3.1.8
**Database Provider**: EntityFramework.SqlServer
**Operating system**: Windows 10
**IDE**: Visual Studio 2019 16.7.6

**Comment by ajcvickers** [comment] 2020-10-19 16:06
Duplicate of #4526. See also #5536.

**Closed** 2022-10-16 19:05 UTC
Labels: customer-reported
