### ISSUE TITLE
Join with local collection using TVP?

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#19016] opened 2019-11-21 18:55 UTC
```C#
            var ids = new uint[] { 1, 2 };

            await AssertQueryScalar(
                async,
                ss => from e in ss.Set<Employee>()
                      join id in ids on e.EmployeeID equals id
                      select e.EmployeeID);
```
Above could be written as contains also. For tuples above syntax may help.

**Comment by smitpatel** [comment] 2020-03-16 22:23
Related #17031

**Comment by roji** [comment] 2023-04-18 00:02
Duplicate of #30426

**Closed** 2023-04-19 19:02 UTC
