### ISSUE TITLE
Provide entity model mapping dynamically

### ISSUE THREAD

**Issue by BishoyDemian** [dotnet/efcore#21015] opened 2020-05-22 03:58 UTC
I have a scenario where I'd like to provide entity mapping to entity framework at runtime where the type is not yet known at design.

I have a base DbContext class in a shared library that will be referenced by the consuming project, which will have the entity definitions (let's call it "UnknownType") based on certain interfaces/base classes. And I'd like to be able to create a DbSet<UnknownType> and use its parent interface/base class to perform entity mapping.

The elegant solution is to support mapping from interfaces (or base class). but also the ability to configure an unknown entity's model (dynamically) at runtime would work fine

**Comment by ajcvickers** [comment] 2020-05-22 20:05
@BishoyDemian The main problem with this is that LINQ is inherently based on generic types. This means if you end up with a fully dynamic, not-generic `IQueryable` there isn't much you can do with it, without using lots of nasty reflection. Do you have a plan for how you would deal with this?

**Comment by ajcvickers** [comment] 2020-06-01 16:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:26 UTC
Labels: closed-no-further-action, customer-reported
