### ISSUE TITLE
The associated entity ID wasn't generated when using AddAsync method

### ISSUE THREAD

**Issue by d18zj** [dotnet/efcore#7303] opened 2016-12-23 04:39 UTC
The post ID wasn't generated when using AddAsync method.(ps:But the Add method is ok) 

Following the testing code:

```c#
 public class Blog
    {
        public string PId { get; set; }
        public string Name { get; set; }

        public List<Post> Posts { get; set; }
    }

    public class Post
    {
        public Guid PId { get; set; }

        public string Title { get; set; }

        public string BlogId { get; set; }
    }

    public class StringPKeyGenerator : ValueGenerator<string>
    {
        public override bool GeneratesTemporaryValues => false;


        public override string Next(EntityEntry entry)
        {
            return Guid.NewGuid().ToString("N");
        }
    }

    public class GuidPKeyGenerator : ValueGenerator<Guid>
    {
        public override bool GeneratesTemporaryValues => false;


        public override Guid Next(EntityEntry entry)
        {
            return Guid.NewGuid();
        }
    }

    public class BlogContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=Test;User ID=sa ;Password=123;Connect Timeout=30");
            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blog>().HasKey(a => a.PId);
            modelBuilder.Entity<Blog>().Property(a => a.PId).HasValueGenerator<StringPKeyGenerator>();
            modelBuilder.Entity<Blog>().HasMany(a => a.Posts).WithOne().HasForeignKey(p => p.BlogId);

            modelBuilder.Entity<Post>().HasKey(a => a.PId);

            //**the default ValueGenerator also doesn't work after canceled the custom ValueGenerator.**
            //modelBuilder.Entity<Post>().Property(a => a.PId).HasValueGenerator<GuidPKeyGenerator>();

            base.OnModelCreating(modelBuilder);
        }
    }

    public class DemoTest
    {

        [Fact]
        public void Insert_Test()
        {
            var blog = new Blog
            {
                Name = "blog01",
                Posts = new List<Post>
                {
                    new Post {Title = "titl01"}
                }
            };
            var post = blog.Posts[0];

            Assert.True(string.IsNullOrEmpty(blog.PId));
            Assert.True(post.PId == Guid.Empty);

            using (var context = new BlogContext())
            {
                context.Blogs.Add(blog);

                Assert.True(!string.IsNullOrEmpty(blog.PId));
                Assert.True(post.PId != Guid.Empty);
            }

        }

        [Fact]
        public async Task Insert_Async_Test()
        {
            var blog = new Blog
            {
                Name = "blog01",
                Posts = new List<Post>
                {
                    new Post {Title = "titl01"}
                }
            };
            var post = blog.Posts[0];

            Assert.True(string.IsNullOrEmpty(blog.PId));
            Assert.True(post.PId == Guid.Empty);

            using (var context = new BlogContext())
            {
                await context.Blogs.AddAsync(blog);

                Assert.True(!string.IsNullOrEmpty(blog.PId));
                //**Failed, the post id wasn't  generated .**
                Assert.True(post.PId != Guid.Empty);
            }
        }
    }
```

### 
EF Core version: "Microsoft.EntityFrameworkCore": "1.1.0",
Database Provider: "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
Operating system: win10
IDE:  Visual Studio 2015

**Comment by ajcvickers** [comment] 2017-01-03 19:07
@d18zj This is a dupe of #7298. The value isn't being generated because the AddAsync method is failing to add child entities. Note that there is no value in using AddAsync here--you should use Add instead.

**Closed** 2022-10-16 10:47 UTC
Labels: closed-duplicate
