### ISSUE TITLE
Returns must be changed

### ISSUE THREAD

**Issue by EduardDumitru** [dotnet/efcore#20733] opened 2020-04-22 19:41 UTC
In EF Core 3.0 or later, the AddAsync method returns a ValueTask not a Task. Also, by doing this change we can now use the AddAsync as default because it won't affect the performance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be049303-fa58-10f2-1213-29047dfb8626
* Version Independent ID: f85bffe8-6c80-e6f2-e061-69fb66b5f501
* Content: [DbSet&lt;TEntity&gt;.AddAsync(TEntity, CancellationToken) Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.addasync?view=efcore-3.1#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbSet`1.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbSet`1.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2020-04-24 18:06
@smitpatel to de-dupe.

**Comment by smitpatel** [comment] 2020-04-24 18:06
Dupe of https://github.com/dotnet/EntityFramework.ApiDocs/issues/73

**Closed** 2022-10-16 18:21 UTC
Labels: closed-duplicate, area-docs
