### ISSUE TITLE
Sum on empty list

### ISSUE THREAD

**Issue by DieDrachenfaenger** [dotnet/efcore#20137] opened 2020-03-03 15:18 UTC
We are trying to calculate the sum on a list that can be empty. Because of this we are using _DefaultIfEmpty()_ to get zero if the list is empty.
But when we try to use the summed value for some further calculation in the query it looks like the sum was set to NULL and therefore the further calculation fails.

### Steps to reproduce
We created a little application to reproduce the problem.

SQL-Script to create table and some data:
```SQL
CREATE DATABASE [EfCore_EmptyListSum];
GO
Use [EfCore_EmptyListSum];
CREATE TABLE [dbo].[Employees]
(
  [EmployeeId]	[INT]	NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [Name]		[NVARCHAR](20)	NOT NULL,
  [Bonus]		[DECIMAL](10,2)	NOT NULL
);
CREATE TABLE [dbo].[Salaries]
(
  [SalaryId]	[INT]		NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [Amount]	[DECIMAL](10,2)	NOT NULL,
  [EmployeeId]	[INT]		NOT NULL  CONSTRAINT [FK_Salaries_Employees_EmployeeId] FOREIGN KEY REFERENCES [dbo].[Employees]([EmployeeId]) ON DELETE CASCADE
)

INSERT INTO [dbo].[Employees] ([Name], [Bonus]) VALUES ('Alice', 1200);
INSERT INTO [dbo].[Employees] ([Name], [Bonus]) VALUES ('Bob', 1600);
INSERT INTO [dbo].[Salaries] ([EmployeeId], [Amount]) VALUES (1, 2500);

```

C# Console application:
``` C#
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace EmptyListSum
{
  public class Program
  {
    public static void Main(string[] args)
    {
      using (var context = new Context())
      {
        var receivedSalariesByCustomer = context.Employees.Select(e => new 
        {
          e.Name,
          ReceivedSalary = (decimal?)(e.Bonus + e.ReceivedSalaries.Select(s => s.Amount).DefaultIfEmpty().Sum())
        });

        foreach (var record in receivedSalariesByCustomer)
          Console.WriteLine($"{record.Name} already earned {record.ReceivedSalary} EURO.");
        Console.ReadLine();
      }
    }

    public class Context : DbContext
    {
      public virtual DbSet<Employee> Employees { get; set; }
      public virtual DbSet<ReceivedSalary> ReceivedSalaries { get; set; }

      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      {
        if (!optionsBuilder.IsConfigured)
          optionsBuilder.UseSqlServer("data source=(local);initial catalog=EfCore_EmptyListSum;integrated security=True;");
      }

      protected override void OnModelCreating(ModelBuilder modelBuilder)
      {
        modelBuilder.Entity<Employee>(entity =>
        {
          entity.HasKey(e => e.EmployeeId);
          entity.Property(e => e.Name);
          entity.Property(e => e.Bonus);
        });

        modelBuilder.Entity<ReceivedSalary>(entity =>
        {
          entity.HasKey(s => s.ReceivedSalaryId);
          entity.Property(s => s.Amount);
          entity.Property(s => s.EmployeeId);
          entity.HasOne(s => s.Employee).WithMany(e => e.ReceivedSalaries).HasForeignKey(s => s.EmployeeId);
        });
      }
    }

    public class Employee
    {
      public int EmployeeId { get; set; }
      public string Name { get; set; }
      public decimal Bonus { get; set; }
      public virtual ICollection<ReceivedSalary> ReceivedSalaries { get; set; }
    }

    public class ReceivedSalary
    {
      public int ReceivedSalaryId { get; set; }
      public decimal Amount { get; set; }
      public int EmployeeId { get; set; }
      public Employee Employee { get; set; }
    }
  }
}
```
To make the problem more clear we cast the value to nullable decimal. Otherwise the result would be zero. 

**Expected result would be:**
Alice already earned 3700 EURO.
Bob already earned 1600 EURO.

**Actual result is:**
Alice already earned 3700 EURO.
Bob already earned  EURO.

### Further technical details

EF Core version: 3.1.2
Operating system: Windows 10
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by maumar** [comment] 2020-03-03 21:07
workaround:

```cs
                var receivedSalariesByCustomer = context.Employees.Select(e => new
                {
                    e.Name,
                    ReceivedSalary = e.Bonus + (e.ReceivedSalaries.Select(s => (decimal?)s.Amount).Sum() ?? 0)
                });
```

**Comment by maumar** [comment] 2020-03-03 21:09
dupe of https://github.com/dotnet/efcore/issues/12657

**Closed** 2022-10-16 18:14 UTC
Labels: customer-reported
