### ISSUE TITLE
ToList in Select hangs forever in EF Core 2.0

### ISSUE THREAD

**Issue by coronabytes** [dotnet/efcore#9425] opened 2017-08-16 08:54 UTC
Upgraded our aspnetcore application to 2.0 yesterday and while most things seem to work I found one query that now hangs forever in an endless loop.

The issue seems to be the ToList in the Select projection, while not the most elegant solution this was working in efcore 1.1.2.

as soon as i remove the output selection completely or or remove the ToList and save it to an IEnumerable<> instead of List<> it works.

```c#
await _context.ProcessVersions
.Where(x => x.ProcessVersionID == vid && x.Process.TenantID == tenant)
.Select(x => new ProcessViewModel
{
	ID = x.ProcessID,
	VersionID = x.ProcessVersionID,
	Revision = x.Revision,
	Name = x.Name,
	Outputs = x.Outputs.Where(y => !y.ContentLink).Select(y => new ProcessLinkViewModel
	{
		ID = y.TargetProcess.ProcessID,
		Name = y.TargetProcess.ActiveVersion.Name
	}).ToList(),
}).SingleOrDefaultAsync();
```
### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10
IDE: VS2017

**Comment by smitpatel** [comment] 2017-08-16 16:05
duplicate of https://github.com/aspnet/EntityFramework/issues/9128

**Comment by ajcvickers** [comment] 2017-09-12 17:34
Hi @core-avatar . We are gathering information on the use of EF Core pre-release builds. You reported this issue shortly after the release of 2.0.0 RTM. It would be really helpful if you could let us know:

- Did you consider testing your code against the pre-release builds?
- Was there anything blocking you from using pre-release builds?
- What do you think could make it easier for you to use pre-release builds in the future?

Thanks in advance for any feedback. Hopefully this will help us to increase the value of pre-release builds going forward.

**Closed** 2022-10-16 11:15 UTC
Labels: closed-duplicate
