### ISSUE TITLE
Single() or First() methods ignore the .Equals() for string PK property

### ISSUE THREAD

**Issue by sguryev** [dotnet/efcore#10229] opened 2017-11-07 14:54 UTC
### Primary key:
`[Key]`
`[Required, StringLength(128)]`
`public string Id { get; set; }`

### Sample:
`DbContext.Tenants.Single(t => t.Id.Equals("Customer_4_Id", StringComparison.OrdinalIgnoreCase));`
produces the following SQL code (from SQL Profiler)
`SELECT [t].[Id], [t].[CreatedDate], [t].[DeletedDate], [t].[IdentitySource], [t].[IsTrustedReseller], [t].[MaxAvailableLicenseUnits], [t].[Name], [t].[ParentId], [t].[Tid], [t].[Type]
FROM [api].[Tenants] AS [t]`

`DbContext.Tenants.Single(t => t.Id == "Customer_4_Id")`
produces the following SQL code (from SQL Profiler)
`SELECT TOP(2) [t].[Id], [t].[CreatedDate], [t].[DeletedDate], [t].[IdentitySource], [t].[IsTrustedReseller], [t].[MaxAvailableLicenseUnits], [t].[Name], [t].[ParentId], [t].[Tid], [t].[Type]
FROM [api].[Tenants] AS [t]
WHERE [t].[Id] = N'Customer_4_Id'`

### Expected behavior:
`Equals()` should be promoted as the `WHERE` filter down to the DB

### Actual behavior:
`Equals()` seems ignored after translation to the 

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1709
IDE: Visual Studio 2017 v. 15.4.2

**Comment by smitpatel** [comment] 2017-11-07 15:22
`Equals` with `StringComparison` arg is not translated to server and will be evaluated on client. Hence you are not seeing it in SQL. It is still being applied in memory (and not ignored) hence results would be correct.

**Comment by smitpatel** [comment] 2017-11-07 15:22
Duplicate of #1222

**Closed** 2022-10-16 11:57 UTC
