### ISSUE TITLE
Multiple Outgoing FK From Entity To Itself: Incoming Inverse Nav Props Not Loaded Correctly Via String Inclusion

### ISSUE THREAD

**Issue by jwbats** [dotnet/efcore#25285] opened 2021-07-19 11:27 UTC
## File a bug

I have a Comment entity. I want my comments to be nested, so I'm giving it a ParentComment property. Every comment can point to the comment above it. But I'm also thinking about my performance: I want to retrieve all child comments (both direct and indirect) when retrieving top level comments (who have ParentComment == null). Therefore, every comment can also point to its TopComment, if it is not a top level comment itself.

My inverse properties DirectChildComments and AllChildComments, are not being filled out correctly when I load them via string inclusion.

### Include your code

**Entity**

```C#
// regular props
...
public string Body { get; set; } = "";
...

// outgoing foreign keys
[ForeignKey("ParentCommentID")]
[InverseProperty("DirectChildComments")]
public Comment ParentComment { get; set; } = null;
public int? ParentCommentID { get; set; } = null;

[ForeignKey("TopCommentID")]
[InverseProperty("AllChildComments")]
public Comment TopComment { get; set; } = null;
public int? TopCommentID { get; set; } = null;

// incoming foreign keys
public List<Comment> DirectChildComments { get; set; } = new List<Comment>();
public List<Comment> AllChildComments { get; set; } = new List<Comment>();
```

**Table**

```SQL
USE [contentBASE]
GO

/****** Object:  Table [dbo].[Comment]    Script Date: 7/19/2021 1:14:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Comment](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Type] [int] NOT NULL,
	[Stars] [float] NOT NULL,
	[Body] [nvarchar](max) NULL,
	[Editable] [bit] NOT NULL,
	[Archived] [bit] NOT NULL,
	[CreatedOn] [datetime2](7) NOT NULL,
	[ModifiedOn] [datetime2](7) NOT NULL,
	[AccountID] [int] NOT NULL,
	[ParentCommentID] [int] NULL,
	[PackageID] [int] NULL,
	[TopCommentID] [int] NULL,
 CONSTRAINT [PK_Comment] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Comment]  WITH CHECK ADD  CONSTRAINT [FK_Comment_Account_AccountID] FOREIGN KEY([AccountID])
REFERENCES [dbo].[Account] ([ID])
GO

ALTER TABLE [dbo].[Comment] CHECK CONSTRAINT [FK_Comment_Account_AccountID]
GO

ALTER TABLE [dbo].[Comment]  WITH CHECK ADD  CONSTRAINT [FK_Comment_Comment_ParentCommentID] FOREIGN KEY([ParentCommentID])
REFERENCES [dbo].[Comment] ([ID])
GO

ALTER TABLE [dbo].[Comment] CHECK CONSTRAINT [FK_Comment_Comment_ParentCommentID]
GO

ALTER TABLE [dbo].[Comment]  WITH CHECK ADD  CONSTRAINT [FK_Comment_Comment_TopCommentID] FOREIGN KEY([TopCommentID])
REFERENCES [dbo].[Comment] ([ID])
GO

ALTER TABLE [dbo].[Comment] CHECK CONSTRAINT [FK_Comment_Comment_TopCommentID]
GO

ALTER TABLE [dbo].[Comment]  WITH CHECK ADD  CONSTRAINT [FK_Comment_Package_PackageID] FOREIGN KEY([PackageID])
REFERENCES [dbo].[Package] ([ID])
GO

ALTER TABLE [dbo].[Comment] CHECK CONSTRAINT [FK_Comment_Package_PackageID]
GO
```

**Test Data**

```Text
1	1	5	This is a really great package.	0	0	2021-05-21 16:23:12.0000000	2021-05-21 16:23:12.0000000	50	NULL	205	NULL
2	1	4.5	I love the artwork in this bundle.	0	0	2021-05-22 17:34:15.0000000	2021-05-22 17:34:15.0000000	51	NULL	205	NULL
3	1	4	These designs are really great value.	0	0	2021-05-23 14:24:25.0000000	2021-05-23 14:24:25.0000000	52	NULL	205	NULL
4	1	4.5	I'll definitely be buying more of these bundles.	0	0	2021-05-24 18:23:34.0000000	2021-05-24 18:23:34.0000000	53	NULL	205	NULL
5	1	5	I'm rating this a solid 5 stars out of 5!	0	0	2021-05-25 12:12:34.0000000	2021-05-25 12:12:34.0000000	54	NULL	205	NULL
7	2	0	Thanks for the feedback.	0	0	2021-06-07 14:23:34.0000000	2021-06-07 14:23:34.0000000	55	1	205	1
8	2	0	I feel the same way.	0	0	2021-06-08 10:14:23.0000000	2021-06-08 10:14:23.0000000	56	2	205	2
9	2	0	I like apple pie.	0	0	2021-06-09 14:54:23.0000000	2021-06-09 14:54:23.0000000	57	3	205	3
10	2	0	I'd love to own this package, as well.	0	0	2021-06-10 16:13:34.0000000	2021-06-10 16:13:34.0000000	58	4	205	4
11	2	0	I have no idea what to write here.	0	0	2021-06-11 17:45:23.0000000	2021-06-11 17:45:23.0000000	59	5	205	5
1002	2	0	This is another test comment.	0	0	2021-07-01 12:12:00.0000000	2021-07-01 12:12:00.0000000	60	7	205	1
1003	2	0	Zombie.	0	0	2021-07-02 16:13:00.0000000	2021-07-02 16:13:00.0000000	61	8	205	2
1004	2	0	I like pancakes.	0	0	2021-07-03 16:14:00.0000000	2021-07-03 16:14:00.0000000	62	9	205	3
1005	2	0	Give me liberty, or give me death!	0	0	2021-07-04 15:43:00.0000000	2021-07-04 15:43:00.0000000	63	10	205	4
1006	2	0	What am I doing here?	0	0	2021-07-05 17:45:00.0000000	2021-07-05 17:45:00.0000000	64	11	205	5
```

**Calling Code**

```C#
// result: both DirectChildComments & AllChildComments filled with direct child comments
// expectation: only DirectChildComments filled with direct child comments
Comment[] comments1 = await this.repoCommon.GetMulti<Comment>(x => x.PackageID == 205 && x.ParentCommentID == null, null, "DirectChildComments");

// result: both DirectChildComments & AllChildComments empty
// expectation: only AllChildComments filled with all child comments
Comment[] comments2 = await this.repoCommon.GetMulti<Comment>(x => x.PackageID == 205 && x.ParentCommentID == null, null, "AllChildComments");

// result: both DirectChildComments & AllChildComments filled with DirectChildComments
// expectation: DirectChildComments filled with direct child comments, AllChildComments filled with all child comments
Comment[] comments3 = await this.repoCommon.GetMulti<Comment>(x => x.PackageID == 205 && x.ParentCommentID == null, null, "DirectChildComments,AllChildComments");
```

**Addendum**

The test data goes 3 comment levels deep. There are 5 top level comments. Then there is 1 child comment for every top comment. Then there is 1 child comment for every child comment.

RepoCommon's string inclusion param is eventually comma-splitted and executed in an extension method as:

```C#
foreach (string include in includes)
{
	queryable = queryable.Include(include);
}
```

It works correctly for all other string inclusion calls. Including other entities that have multiple FKs to another entity (so not itself), where inverse properties are also defined.

### Include stack traces

N/A

### Include verbose output

N/A

### Include provider and version information

EF Core version: 5.08
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Win10
IDE: Visual Studio 2019 16.10.3

**Comment by smitpatel** [comment] 2021-07-19 23:29
1. AllChildComments is populated when you only included other navigation. That is expected by design. The collection is not marked as loaded but it will be partially populated. Read Tip in https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#eager-loading page. Since the comments are materialized and tracked for DirectChildComments include and they also belong to AllChildComments, they are added to that collection.
2. When including AllChildComments nothing is loaded. Can you share runnable repro code for this specifically?
3. Third case looks like 1st and indicates more that for some reason `AllChildComments` is not included at all.

The fixup behavior is not something which can be turned off. If you absolutely want only collection asked for loaded then consider doing a non-tracking query. (Though if you attach those entity to context at any point, they will still be populated in relevant collections)

**Comment by jwbats** [comment] 2021-07-20 12:17
I'll see if I can provide runnable code for this soon.

**Comment by AndriySvyryd** [comment] 2021-07-27 16:40
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.

Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by jwbats** [comment] 2021-07-30 19:44
I'm currently creating a test project for this. Oddly enough, it works correctly in my test project, despite having copy pasted my own code into it.

I'll keep digging to see what's causing my issue. If you don't hear from me again, it was a bug of my own.

**Comment by jwbats** [comment] 2021-07-31 13:19
Ok, so I couldn't reproduce it in a test project. So I figured I'd run my original project, the one where the unexpected output first occurred), again.

Lo and behold, it now works exactly as expected. How on earth this came to be, I do not know. I updated to EF Core 5.0.8 and tried it again, before submitting this bug report. I haven't updated anything EF-related in my project since.

Only thing I've done since last experiencing this problem, was install VS2022 Preview and update my EF CLI tools. I don't see how either could possibly have any relation to this issue.

Seems like the problem has solved itself, which is kind of a bummer, because now I don't know what the cause was. Should I ever run into this again, I'll post more info.

Thanks for your time, anyway.

**Closed** 2022-10-16 19:40 UTC
Labels: closed-could-not-reproduce, customer-reported
