### ISSUE TITLE
Cosmos: Getting error while join the EF core 3.0

### ISSUE THREAD

**Issue by rameshmummidi30** [dotnet/efcore#19627] opened 2020-01-18 02:56 UTC
After migration of my  Azure function project  to  3.0 entity framework cosmos 
I am using  below linq query to get entity from cosmos 

### Steps to reproduceFuction 3.0 
Context class  : 

```c#
public class DispatchContext : DbContext, IUnitOfWork
{        
        public DispatchContext(DbContextOptions<DispatchContext> options) : base(options)
	{
	    Database.EnsureCreated();
        }

	protected DispatchContext()
	{
		Database.EnsureCreated();
	}
 
        //public DbSet<Appointment> Appointments { get; set; }
        //public DbSet<Job> Jobs { get; set; }
        //public DbSet<Container> Containers { get; set; }
        public DbSet<Driver> Drivers { get; set; }
        public DbSet<DriverDispatch> DriverDispatches { get; set; }
        public DbSet<Move> Moves { get; set; }
        public DbSet<GeneratedPlans> PlansGeneratedEvents { get; set; }
	public DbSet<TerminalTurnTime> TerminalTurnTimes { get; set; }
        public DbSet<Terminal> Terminals { get; set; }
        public DbSet<AlternatePlanLeg> AlternatePlanLegs { get; set; }
        public CosmosDBsettings CosmosDBsettings { get; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
	    //modelBuilder.GetInfrastructure().Metadata.Cosmos().DefaultContainerName = "Dispatch";
	    modelBuilder.HasDefaultContainer("Dispatch");		
	    modelBuilder.ApplyConfiguration(new DriverEntityTypeConfiguration());
            modelBuilder.ApplyConfiguration(new DriverDispatchEntityTypeConfiguration());
            //modelBuilder.ApplyConfiguration(new JobEntityTypeConfiguration());
            
            modelBuilder.ApplyConfiguration(new PlansGeneratedEventConfiguration());
            modelBuilder.ApplyConfiguration(new MoveEntityTypeConfiguration());
            modelBuilder.ApplyConfiguration(new TerminalTurnTimesEventTypeConfiguration());
            modelBuilder.ApplyConfiguration(new TerminalEventTypeConfiguration());
            modelBuilder.ApplyConfiguration(new AlternatePlanLegEventTypeConfiguration());
            base.OnModelCreating(modelBuilder);
        }
        
        public async Task<bool> SaveEntitiesAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
		//throw new System.NotImplementedException();
		var result = await base.SaveChangesAsync(cancellationToken);

		return true;
	}
}
```

``` C#
var filteredDispathces = (from d in _context.Set<Driver>()
    join dd in _context.Set<DriverDispatch>() on d.id equals dd.DriverId
    where dd.PlanDate == dafaultPlanDate & dd.Status == "AT_RISK"
    select d).ToList();
```

Got Exceptions? Include both the message and the stack trace

```
The LINQ expression 'DbSet<Driver>
    .Join(
        outer: DbSet<DriverDispatch>, 
        inner: d => d.id, 
        outerKeySelector: d0 => d0.DriverId, 
        innerKeySelector: (d, d0) => new TransparentIdentifier<Driver, DriverDispatch>(
            Outer = d, 
            Inner = d0
        ))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.cosmos)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment] 2020-01-21 23:47
Duplicate of #17314

**Closed** 2022-10-16 18:06 UTC
Labels: customer-reported
