### ISSUE TITLE
Identification of commits in daily dev builds on MyGet

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2305] opened 2015-05-31 16:27 UTC
As a provider writer, that feeds on the daily dev builds from MyGet, it would be very helpful to have a way of identifying what commit was included in which daily build - mabe tags? Is this currently possible, or can it be made available?

**Comment by bricelam** [comment] 2015-06-01 02:34
Dupe of aspnet/Universe#64?

**Comment by ErikEJ** [comment] 2015-06-01 03:59
@bricelam  Yes, so I wont brace myself for it to happen, then!

**Closed** 2022-10-16 08:57 UTC
