### ISSUE TITLE
`dotnet-ef migrations add` starts entire application when CreateHostBuilder method is not present

### ISSUE THREAD

**Issue by marekott** [dotnet/efcore#28105] opened 2022-05-26 08:28 UTC
**********************
**TLTR**
When `public static IHostBuilder CreateHostBuilder(string[] args)` method is removed from `Program.cs` in a web api template project with dependencies on EF 6, generating migration with dotnet ef CLI tool starts the entire application instead of generating migration. In EF 5 this behaviour was not present.
**********************

Hello,
I've encountered strange behaviour of the dotnet ef CLI tool after updating my application to EF 6. `Program.cs` in our microservices looks like this:
```csharp
public class Program
{
    public static Task Main(string[] args) => WebHostHelper.BuildAndRunWebHostAsync<Startup>(args, validateDiConfigurationInDebug: true);
}
```
As you can see it lacks `CreateHostBuilder(string[] args)` because it wouldn't be productive to add this method in all microservices. Instead, we provide a helper method as above. Also, what is important, our application is implementing `IDesignTimeDbContextFactory` in order to control creating of `DbContext` when migrations are being added (find simple reproduction here: https://github.com/marekott/dotnet-ef-add-migration-bug-reproduction). When application had dependency on EF 5 `dotnet-ef migrations add Initial -v` command produced valid migration (logs below). After updating to EF 6 the same command starts the entire application (logs below) that needs to be killed in order to finish producing migration (which in the end is a valid one). Adding `CreateHostBuilder(string[] args)` resolves this issue, application is not started and migration is generated. However, adding this method especially that it is not used and wasn't needed for 3 years seem as a lazy solution. 

Taking everything into consideration what is a reason for this strange behaviour? It seems like a bug, especially that it has worked previously.

**Logs for EF 5**
```
PS C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi> dotnet-ef migrations add Initial
Build started...
Build succeeded.
Done. To undo this action, use 'ef migrations remove'
PS C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi> dotnet-ef migrations add Initial -v
Using project 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\SampleWebApi.csproj'.
Using startup project 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\SampleWebApi.csproj'.
Writing 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\obj\SampleWebApi.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\marek.ott\AppData\Local\Temp\tmp277A.tmp /verbosity:quiet /nologo C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\SampleWebApi.csproj
Writing 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\obj\SampleWebApi.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\marek.ott\AppData\Local\Temp\tmp2A4A.tmp /verbosity:quiet /nologo C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\SampleWebApi.csproj
Build started...
dotnet build C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\SampleWebApi.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.28
Build succeeded.
dotnet exec --depsfile C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\bin\Debug\net6.0\SampleWebApi.deps.json --additionalprobingpath C:\Users\marek.ott\.nuget\packages --runtimeconfig C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\bin\Debug\net6.0\SampleWebApi.runtimeconfig.json C:\Users\marek.ott\.dotnet\tools\.store\dotnet-ef\6.0.5\dotnet-ef\6.0.5\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll migrations add Initial --assembly C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\bin\Debug\net6.0\SampleWebApi.dll --project C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\SampleWebApi.csproj --startup-assembly C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\bin\Debug\net6.0\SampleWebApi.dll --startup-project C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\SampleWebApi.csproj --project-dir C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\ --root-namespace SampleWebApi --language C# --framework net6.0 --working-dir C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi --verbose
Using assembly 'SampleWebApi'.
Using startup assembly 'SampleWebApi'.
Using application base 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\bin\Debug\net6.0'.
Using working directory 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi'.
Using root namespace 'SampleWebApi'.
Using project directory 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'PostgresDbContextMigrationsFactory'.
Found DbContext 'SampleWebApiContext'.
Finding application service provider in assembly 'SampleWebApi'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'PostgresDbContextMigrationsFactory'.
Using context 'SampleWebApiContext'.
Finding design-time services for provider 'Npgsql.EntityFrameworkCore.PostgreSQL'...
Using design-time services from provider 'Npgsql.EntityFrameworkCore.PostgreSQL'.
Finding design-time services referenced by assembly 'SampleWebApi'...
Finding design-time services referenced by assembly 'SampleWebApi'...
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'SampleWebApi'...
No design-time services were found.
DetectChanges starting for 'SampleWebApiContext'.
DetectChanges completed for 'SampleWebApiContext'.
Writing migration to 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\Migrations\20220526065812_Initial.cs'.
Writing model snapshot to 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\Migrations\SampleWebApiContextModelSnapshot.cs'.
'SampleWebApiContext' disposed.
Done. To undo this action, use 'ef migrations remove'
```

**Logs for EF 6**
```
dotnet-ef migrations add Initial -v
Using project 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\SampleWebApi.csproj'.
Using startup project 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\SampleWebApi.csproj'.
Writing 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\obj\SampleWebApi.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\marek.ott\AppData\Local\Temp\tmp423C.tmp /verbosity:quiet /nologo C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\SampleWebApi.csproj
Writing 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\obj\SampleWebApi.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\marek.ott\AppData\Local\Temp\tmp4460.tmp /verbosity:quiet /nologo C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\SampleWebApi.csproj
Build started...
dotnet build C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\SampleWebApi.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.60
Build succeeded.
dotnet exec --depsfile C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\bin\Debug\net6.0\SampleWebApi.deps.json --additionalprobingpath C:\Users\marek.ott\.nuget\packages --runtimeconfig C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\bin\Debug\net6.0\SampleWebApi.runtimeconfig.json C:\Users\marek.ott\.dotnet\tools\.store\dotnet-ef\6.0.5\dotnet-ef\6.0.5\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll migrations add Initial --assembly C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\bin\Debug\net6.0\SampleWebApi.dll --project C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\SampleWebApi.csproj --startup-assembly C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\bin\Debug\net6.0\SampleWebApi.dll --startup-project C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\SampleWebApi.csproj --project-dir C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\ --root-namespace SampleWebApi --language C# --framework net6.0 --working-dir C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi --verbose
Using assembly 'SampleWebApi'.
Using startup assembly 'SampleWebApi'.
Using application base 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\bin\Debug\net6.0'.
Using working directory 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi'.
Using root namespace 'SampleWebApi'.
Using project directory 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'PostgresDbContextMigrationsFactory'.
Found DbContext 'SampleWebApiContext'.
Finding application service provider in assembly 'SampleWebApi'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Hosting environment: Development
Content root path: C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi
Now listening on: http://localhost:5000
Now listening on: https://localhost:5001
Application started. Press Ctrl+C to shut down.
Application is shutting down...
PS C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi> System.InvalidOperationException: The entry point exited without ever building an IHost.
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass10_0.<ResolveHostFactory>b__0(String[] args)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass13_0.<ResolveServiceProviderFactory>b__3(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: The entry point exited without ever building an IHost.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'PostgresDbContextMigrationsFactory'.
Using context 'SampleWebApiContext'.
Finding design-time services referenced by assembly 'SampleWebApi'...
Finding design-time services referenced by assembly 'SampleWebApi'...
No referenced design-time services were found.
Finding design-time services for provider 'Npgsql.EntityFrameworkCore.PostgreSQL'...
Using design-time services from provider 'Npgsql.EntityFrameworkCore.PostgreSQL'.
Finding IDesignTimeServices implementations in assembly 'SampleWebApi'...
No design-time services were found.
DetectChanges starting for 'SampleWebApiContext'.
DetectChanges completed for 'SampleWebApiContext'.
Writing migration to 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\Migrations\20220526070035_Initial.cs'.
Writing model snapshot to 'C:\Users\marek.ott\Desktop\demo\SampleWebApi\SampleWebApi\Migrations\SampleWebApiContextModelSnapshot.cs'.
'SampleWebApiContext' disposed.
Done. To undo this action, use 'ef migrations remove'
```

My dotnet ef version is:
```
Entity Framework Core .NET Command-line Tools
6.0.5
```

**Comment by ajcvickers** [comment] 2022-05-26 11:45
@marekott Running the application is an intentional change added by @davidfowl to support minimal APIs.

@davidfowl @bricelam Any thoughts here?

**Comment by bricelam** [comment] 2022-05-26 17:35
Related to https://github.com/dotnet/efcore/issues/27306#issuecomment-1128033019

**Comment by plachor** [comment] 2022-05-27 04:45
That: https://github.com/dotnet/efcore/issues/27322#issue-1119743287  would be best option for this case I believe. Since in docs you mentioned that:
 > ... The generic hosting model is an alternative model that is supported indefinitely. The generic host underpins the new hosting model and is still the primary way to host worker-based applications.
 
 Or allow to specify `IDesignTimeDbContextFactory` type explicitly in `dotnet ef` command instead of `context`.

**Comment by KrzysztofBranicki** [comment] 2022-06-03 09:07
@davidfowl During application startup lot of things can be performed: microservice can send some message to the message bus indicating that it is started, it may register itself in Consul, some data seeding can take place. None of those is expected behavior when you are using EF tooling to generate new migration. Also application may require some mandatory configuration to be provided via env variables or Kubernetes mounted file (e.g. availability zone) without which it will throw, obviously you wouldn't want to provide this configuration just to generate EF migration. Long story short it is not expected behavior that adding database migration will start your application, but if you don't want to change existing behavior then at least add ability to directly specify in CLI `IDesignTimeDbContextFactory` (as @plachor suggested) which we have implemented exactly for the reason of constructing`DbContext` for the EF CLI tooling purpose.

**Comment by bricelam** [comment] 2022-06-07 21:10
I wonder if the Hosting code should have a switch (environment variable?) that avoids calling Main entirely. Seems like a good escape hatch to have...

**Comment by KrzysztofBranicki** [comment] 2022-06-08 07:07
@bricelam I don't know what you have in mind when you say hosting code. If you mean that application should protect itself using some env variable from being unnecessarily started by EF tooling which just want to create migration then I think it is bad idea. BTW who should set this env variable? Whoever is executing migration before using `dotnet ef`? It should be rather part of `dotnet ef` to know whether it needs to start the app or just use `IDesignTimeDbContextFactory ` which is explicitly provided for that reason. We may pass name of class that implements `IDesignTimeDbContextFactory ` as a parameter to `dotnet ef`.

**Comment by ajcvickers** [comment] 2022-06-08 08:46
@KrzysztofBranicki This code is not intended to be used by just EF tooling, but by any tooling that needs to obtain the service provider. Therefore, while https://github.com/dotnet/efcore/issues/27322#issue-1119743287 and https://github.com/dotnet/efcore/issues/27306#issuecomment-1128033019 are things we intend to do on the EF side to make this better, these things won't help other commands that also use this mechanism, hence it is worth thinking about something more general in hosting that could be used by someone using any command.

@davidfowl No, which is why https://github.com/dotnet/efcore/issues/27322#issue-1119743287 is feasible. However, there is a chicken and egg problem in that if we don't know the registered context type (which might only be available via D.I.) then we might get the wrong factory type. https://github.com/dotnet/efcore/issues/27322#issue-1119743287 recognizes that this is a corner case and that the value of assuming we have found the correct one to use is higher than the risk of getting it wrong in this corner case.

**Comment by ajcvickers** [comment] 2022-06-13 14:38
@KrzysztofBranicki I agree that https://github.com/dotnet/efcore/issues/27322#issue-1119743287 can be implemented, which is why the issue is open. not closed. I'm not sure what point you are trying to make.

**Comment by ajcvickers** [comment] 2022-06-17 16:07
Closing since EF work here is covered by other issues.

**Comment by olegbaslak** [comment] 2022-09-13 17:43
Faced the same issue with the app start up, but it was a little bit tricky.

I use Autofac and have one service registered as `IStartable` (Autofac interface). It causes this service to start each time I run `database update`.

Changing `IStartable` interface with `IHostedService` and registering as HostedService in `Startup.cs` solved the issue. The service stopped executing each `database update`, preventing the script to finish.

**Closed** 2022-10-16 20:35 UTC
Labels: closed-external, customer-reported

**Comment by deereeed** [comment] 2022-11-29 18:06
> Closing since EF work here is covered by other issues.
In which tasks exactly the problem will be solved?

**Comment by ajcvickers** [comment] 2022-11-29 18:11
@deereeed https://github.com/dotnet/efcore/issues/27306#issuecomment-1128033019 and https://github.com/dotnet/efcore/issues/27322#issue-1119743287
