### ISSUE TITLE
EFCore throwing 'System.ObjectDisposedException' several minutes after successful DB Record Retrieval

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#15069] opened 2019-03-18 22:41 UTC
Describe what is not working as expected.

I am developing a UWP app based on Microsoft.NetCore.UniversalWindowsPlatform V6.2.8 and EFCore 2.2.3

The app successfully retrieves a record from a SQL  database.  Several minutes later (up to 15 minutes) the app throws a System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.'

from SNIPackets.ReadFromStreamAsync

Several issues are strange:
1) There is no further attempt to read from the database to cause this error, this happens several minutes after the successful read from the database.
2) SNIPackets.ReadFromStreamAsync requires a Stream and an SNIAsyncCallback both of which are null
3) The stack trace in incomplete with no reference to what is actually making the call
4) Changing connection and command timeout values has no effect.

Searching the web has provided no help.

Any suggestions or direction would be greatly appreciated.

Thanks.
```
Exception message:
Stack trace:
   at System.Net.Sockets.NetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 size, CancellationToken cancellationToken)
```
This is the entire stack trace, which seems truncated.  The inner exception is null.

### Steps to reproduce
Service Collection Creation in MainPage()

```C#
            _sp = new ServiceCollection()
                .AddScoped<ILoads, Loads>()
                .AddScoped<IDocks, Docks>()
                .AddScoped<IConfig, Config>()
                .AddDbContext<DataDbContext>(options => 
                    options.UseSqlServer("Data Source=app-sql-insight;Initial Catalog=MasterSchedScndVersion; UID and Password Removed;MultipleActiveResultSets=True;Persist Security Info=True"))
                .BuildServiceProvider();`
```

DI
```C#
        private readonly DataDbContext _context;

        public Docks(DataDbContext Context)
        {
            _context = Context;
        }
```

code accessing database (runs successfully and returns a record)
```C#
            try
            {
                LB = await (from l in _context.Tbl_LoadingBayLoadTicketAssignments
                                               .Include(o => o.Operation)
                            where l.BayNumber == LoadingBayNumber && l.LocationID == 10
                            select l).AsNoTracking().FirstOrDefaultAsync();

            }
            catch (Exception ex)
            {

                throw;
            }
```

The catch does not catch the exception
```

### Further technical details
EF Core version: 2.2.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer V 2.2.3
Operating system: Win 10 Target 1803
IDE: Visual Studio 2017 15.9.9

**Comment by ajcvickers** [comment] 2019-03-20 20:47
@GRS-Leedo I don't see anything obviously wrong here. We're probably going to need a full repro, and even if we repro what you're seeing it may be an issue in the ADO.NET provider or UWP rather than in EF Core. Regardless, we're going to need to be able to reproduce the behavior in order to make progress.

**Comment by GRS-Leedo** [comment] 2019-03-22 17:21
[DBTest.zip](https://github.com/aspnet/EntityFrameworkCore/files/2997557/DBTest.zip)

I apologize for my slow response, but I had pressing issues.

The attached project reproduces the problem.  You will need to add a connection string and create the table in the database.

If you set the debugger to break on CLR errors, it will break at the error.  If you don't you will see the error reported in the Output window.  It seems that if you simply ignore the error, the app will run, but that seems like a cheesy approach.  If you do break on CLR errors, you will see that it is an SQL routine causing the error.

**Comment by ajcvickers** [comment] 2019-03-25 21:18
@GRS-Leedo I wasn't able to get your app to run (probably need some additional dependencies on my machine) but looking at the code I see one thing that is wrong. If the context is registered scoped service in D.I., then a scope must be created before resolving the service from D.I. This isn't happening; instead the context is being resolved from the root service provider.

**Comment by ajcvickers** [comment] 2019-04-02 16:35
@GRS-Leedo I closed it because I could not get the application to run on my machine--the more minimal you can make the repro, the more likely we are to be able to execute it and dig into the actual code.

However, on reading the code I saw some things that were obviously wrong. In situations like this we usually push back until the known issues with the code are fixed. If after that the original issue is still happening, then at that point we can continue to try to find the root cause.

The code I saw registered the DbContext as scoped and then used it without creating a scope. If you have fixed this, then please post a new repro project that included the fixed code and I'll take another look.

**Comment by GRS-Leedo** [comment] 2019-04-04 15:21
Arthur,

I think that the app is as minimal as it can be.  It is a UWP app with references to EFCore, EFCore.SqlServer and EFCore.Tools.
[cid:image002.png@01D4EACF.1E8094A0]

It has a very simple model, a simple DataAccess method that gets a value from the table represented by the model, and a very simple user interface.

Your comment about the DBContext being scoped threw me a little since I am not declaring it as scoped,
.AddDbContext<DataDBContext>(options =>

But I was finally able to find a brief mention in documentation that the default is scoped.  Since nearly all of the documentation surrounding EF and DI related to Web apps, is there preferred practice for UWP apps?  Should the DbContext be Scoped, or Transient or a Singleton?  If you can point me to EF with DI in UWP apps, I would be more that happy to read up on them, but like I said, nearly everything related to Web apps.

Thanks,

Glen

[cid:image005.png@01CCFDFB.153168C0]<http://www.leedo.com/>
Glen Swanson | Software Developer
10707 Corporate Drive, Suite 250 | Stafford, TX 77477
T 281.201.0900 ext:1005
Follow us on Twitter<https://twitter.com/LeedoCabinetry> | Like us on Facebook<https://www.facebook.com/LeedoCabinetry>

**Comment by GRS-Leedo** [comment] 2019-04-04 22:10
I was able to cobble together various pieced of information and make changes to the code.
`namespace DBTest
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainPage : Page
    {

        private readonly ServiceProvider _sp;
        private IDataAccess _da;
        private int BayNumber;

        public MainPage()
        {
            this.InitializeComponent();

            ServiceProvider RegisterServices()
            {
                var Services = new ServiceCollection();
                Services.AddDbContext<DataDBContext>(options =>
                   options.UseSqlServer("Data Source=app-sql-insight;Initial Catalog=MasterSchedScndVersion;UID=intranet;PWD=1ntr@n3t;MultipleActiveResultSets=True;Persist Security Info=True"));
                Services.AddTransient<IDataAccess, DataAccess>();
                return Services.BuildServiceProvider();
            }

            _sp = RegisterServices();

            BayNumber = 1;

            UpdateUI();
        }



        public async void UpdateUI()
        {
            LoadingBayLoadTicketAssignments LTA = new LoadingBayLoadTicketAssignments();

            using (IServiceScope scope = _sp.CreateScope())
            {
                _da = scope.ServiceProvider.GetService<IDataAccess>();
                LTA = await _da.GetInformationByBayNumber(BayNumber);
            }

            TBLoadNumber.Text = LTA.LoadingTicketNumber.ToString();
        }

        private void NextBay_Click(object sender, RoutedEventArgs e)
        {
            if(BayNumber < 8)
            {
                BayNumber = BayNumber + 1;
            }
            else
            {
                BayNumber = 1;
            }

            UpdateUI();
        }
    }
}`

There is now a scope that is used when calling the DataAccess service.

The result of this however is no different.  After several minutes 
Exception thrown: 'System.ObjectDisposedException' in System.Net.Sockets.dllException 

Again, the app is sitting idle with no new database access attempts, so I am not sure what the issue is.

**Comment by ajcvickers** [comment] 2019-11-14 23:42
@GRS-Leedo Is `_da` used anywhere outside the service scope? If not, why is it a field? Is `LoadingTicketNumber` setup for lazy-loading?

**Comment by GRS-Leedo** [comment] 2019-11-15 14:23
Wow, a blast from the past.  Being 7 months ago, it is hard to remember why things were the way that they were.  _da was probably a field in the original code before being paired down to the bare minimum, per your request, to reproduce the problem.  No, LoadingTicketNumber is not set up for lazy loading.

Do either of these things relate to the issue reported?  If so, how?

**Comment by ajcvickers** [comment] 2019-11-15 20:52
@GRS-Leedo Because if the network is being used when something is disposed, and if this is an EF issue, then if somehow a disposed EF object is being used after being disposed (which shouldn't be possible, but we're looking for bugs here) then that could be the root cause.

Could you post the full stack trace?

**Comment by GRS-Leedo** [comment] 2019-11-19 15:33
Sorry for the delay, working on some production code that is causing me problems, oddly enough, around Entity Framework and a UWP app.  

I had to download the code from here and run it again.  The problem is that the exception shows up in the Output window but is not caught in a try-catch on the database access or by the app level Unhandled Exception event, so I can't get the full stack trace.  If I could, it would be very helpful.  The app is running waiting for the user to click a button when the exception is thrown.
![2019-11-19_09h18_19](https://user-images.githubusercontent.com/47821931/69159758-0b655900-0aae-11ea-82b4-7d04bd26cbb8.png)

**Comment by GRS-Leedo** [comment] 2019-11-19 15:47
Letting the app run longer with no user intervention, leads to a System.IO.IOException.
![2019-11-19_09h45_45](https://user-images.githubusercontent.com/47821931/69162014-9d229580-0ab1-11ea-84e9-0d2522ecf8d5.png)

**Comment by ajcvickers** [comment] 2019-11-22 19:14
@GRS-Leedo I have moved this issue to https://github.com/dotnet/SqlClient/issues/327 since I can't find any problems at the EF level, and the exception looks to be coming from SqlClient SNI code.

**Closed** 2022-10-16 13:56 UTC
Labels: closed-external, customer-reported
