### ISSUE TITLE
EF Core Skip/Take Order By

### ISSUE THREAD

**Issue by darl0026** [dotnet/efcore#14411] opened 2019-01-14 19:17 UTC
When doing a Skip/Take EF is automatically ordering by the Primary Key (which is fine by default).

But when I specify an Order By it should NOT also order by the Primary Key.  It should only use the Ordering that I specify.

Sample SQL.  If i specify to order by Name and the primary key is ID.  It should not add , [j].[ID]
exec sp_executesql N'SELECT [j].[Name]
FROM [Job] AS [j]
ORDER BY [j].[Name], [j].[ID]
OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY',N'@__p_1 int,@__p_2 int',@__p_1=0,@__p_2=10'

**Comment by ajcvickers** [comment] 2019-01-23 17:58
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:47 UTC
Labels: closed-could-not-reproduce, customer-reported
