### ISSUE TITLE
Owned entities cannot be tracked without their owner. exceptions when using inheritance

### ISSUE THREAD

**Issue by codehunter13** [dotnet/efcore#18143] opened 2019-09-30 14:19 UTC
Since i use ef core 3.0 i get the following error:
 System.InvalidOperationException: A tracking query projects owned entity without corresponding owner in result. Owned entities cannot be tracked without their owner. Either include the owner entity in the result or make query non-tracking using AsNoTracking()

The situation:
abstract Entity1 with has an owned type
entity2 inherits entity1
entity3 inherits entity1

entity4 has a collection of entity2

when i query entity4 as tracking and i include the entity 2 collection  i got the error

The code was working in previous versions.

**Comment by smitpatel** [comment] 2019-09-30 18:23
Duplicate of #18024

**Closed** 2022-10-16 14:46 UTC
Labels: customer-reported
