### ISSUE TITLE
Migration generates with error when adding new Enum column

### ISSUE THREAD

**Issue by SonicGD** [dotnet/efcore#4528] opened 2016-02-10 12:48 UTC
EF 1.0.0-rc1-final
Npgsql 3.1.0-rc1-3

Here are class Foo

``` csharp
    public class Foo
    {
        [Key]
        public Guid Id { get; set; }

        [Required]
        public Status Status { get; set; }
    }
```

And class DbContext:

``` csharp
    public class PGContext : DbContext
    {
        public DbSet<Foo> Foos { get; set; }
    }
```

Run "dnx migration add addFoo". Result: 

``` csharp
         migrationBuilder.CreateTable(
                name: "Foo",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    Status = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Foo", x => x.Id);
                });
```

Everything is ok. Now rename column

``` csharp
    public class Foo
    {
        [Key]
        public Guid Id { get; set; }

        [Required]
        public Status StatusRenamed { get; set; }
    }
```

Run "dnx migration add renameStatus". Result: 

``` csharp
            migrationBuilder.DropColumn(name: "Status", table: "Foo");
            migrationBuilder.AddColumn<int>(
                name: "StatusRenamed",
                table: "Foo",
                nullable: false,
                defaultValue: Status.0);
```

As you can see, defaultValue is set to "Status.0". Migration is broken.

**Comment by ErikEJ** [comment] 2016-02-10 12:56
What is the code for the Status Enum?

**Comment by SonicGD** [comment] 2016-02-10 13:21
Sorry,  forgot this =) 

```csharp
    public enum Status
    {
        Enabled = 1,
        Disabled = 2,
        Deleted = 3,
    }
```

**Comment by bricelam** [comment] 2016-02-10 18:01
Dupe of #4061

**Comment by SonicGD** [comment] 2016-02-11 05:11
Ok, thx.

**Closed** 2022-10-16 09:28 UTC
