### ISSUE TITLE
compiler errors in compiled model

### ISSUE THREAD

**Issue by ghosttie** [dotnet/efcore#27007] opened 2021-12-14 21:32 UTC
There are a couple class names that cause compiler errors in compiled models:

`CS0118	'CompiledModelReproducer' is a namespace but is used like a type`

This is caused by a model type having the same name as a namespace.  Normally it's possible to work around this by qualifying the type name, but the generated code does not do this.

`CS0104	'Version' is an ambiguous reference between 'CompiledModelReproducer.Models.Version' and 'System.Version'`

This is caused by a model having a name that is present in two included namespaces.  Normally it's possible to work around this by qualifying the type name, but the generated code does not do this.

[reproducer.zip](https://github.com/dotnet/efcore/files/7714896/reproducer.zip)

EF Core version: 6.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.0.3

**Comment by ajcvickers** [comment] 2021-12-17 12:33
Related to #25523.

/cc @AndriySvyryd

**Comment by ajcvickers** [comment] 2022-01-05 20:50
Duplicate of #25523.

**Closed** 2022-10-16 20:19 UTC
Labels: customer-reported
