### ISSUE TITLE
ChangeTracker not tracking Entity when using Join with DBQuery except when using Include on parent

### ISSUE THREAD

**Issue by pwaaijenberg** [dotnet/efcore#14680] opened 2019-02-12 18:55 UTC
I have a join query that joins a normal DBSet table with a DBQuery. This is needed because the query optimizer does not give me a good optimizatiion

Something like (query is simplefied a lot):

```C#
var childCountQuery = context.ChildCount.FromSql(@"SELECT P.Id AS Id, CountForCondition= Count()
FROM Child INNER JOIN Parent 
WHERE C.ParentId = P.Id AND C.Value = P.Value
GROUP BY P.Id");
```

Then I join with context.Parent and enumerate like

```C#
var myQuery = context.Parent.Join(childCountQuery, parent => parent.Id, childcount => childcount.Id, (parent, childcount) => new { parent, childcount.CountForCondition});

foreach (var myqueryitem in myquery)
{
    myqueryItem.parent.CountForCondition= myqueryitem.CountForCondition;
    yield return myqueryItem.parent.
}
```

Where CountForCondition is a 'NotMapped' property of Parent.

The query works, but parent does not get tracked (which was the whole idea of the join statement)

However, if I include a related entity on the parent (does not need to be child) parent is tracked.

so `var myQuery = context.Parent.Include(p => p.Address).Join(childCountQuery, parent => parent.Id, childcount => childcount.Id, (parent, childcount) => new { parent, childcount.CountForCondition})`;

returns the same item (with Address) and but does track parent entities. In this case however I do not want to return Address of all Parents.

Desired behaviour: parent entities are tracked, regardles of using an include in the statement

### Further technical details
EF Core version: 2.2.1 and 2.2.2.
Database Provider:Microsoft.EntityFrameworkCore.SqlServer
Operating system: Tested on Linux and Windows 10
IDE: Visual Studio 2017 15.9.6

**Comment by ajcvickers** [comment] 2019-02-22 20:12
@pwaaijenberg Query types (that is, types without keys) cannot be tracked. Currently any query that uses them should be no-tracking. The query above that ends up tracking Parent entities is a bug and this will likely change in 3.0.

Ultimately, we may enable some behaviors that allow things like this, but that's quite future looking and will depend on the evolution of query past 3.0.

**Comment by jwatkin** [comment] 2019-04-06 23:59
In my project when I perform a JOIN with a DbSet and a DbQuery and only return a list of DbSet entities, those returned DbSet entities are not tracked. For clarification, is this the intended behavior for EF Core? Thank you.

**Comment by ajcvickers** [comment] 2019-04-08 17:51
@jwatkin Yes; queries that use query types are always no-tracking.

**Comment by divega** [comment] 2019-06-24 05:51
Clearing milestone to discuss propose-close in regular triage.

**Comment by pwaaijenberg** [comment] 2019-06-24 08:07
I understand what you are all saying, but for me this is needed for performance reasons. It enables doing more complex queries with very large intermediate result sets in one go.

Queries like "select * from parent where (select count(*) from childtable) > 1) and table.status == 'somestatus'" are quite a common scenario. Imagine that this would retrieve 1000 records from a set of millions. If the parent is not tracked, we would need to retrieve all 1000 records again in a separate query.

For us, removing this kind of tracking all-together would be a breaking change. The solution we used with the join was already a work-around because the direct query was not optimized which resulted in the subquery being executed for each retrieved record.

Hope this will change your give you enough information to make your evaluation.

**Comment by ajcvickers** [comment] 2019-06-24 18:42
Closing this as in 3.0 an `AsNoTacking` must be added explicitly to make a query tracking, even if it has keyless types.

@pwaaijenberg We have no plans to implement partial tracking/not tracking here. Doing so is complicated both in understanding the semantics of what's going on, and also in the implementation.

**Comment by pwaaijenberg** [comment] 2019-06-25 20:05
@ajcvickers I'm not sure what you are trying to say. You are talking that in 3.0 AsNoTracking is needed to make a query non-tracking. If that is so, in EF 3.0 my query would be tracking by default. As you see, I have included all properties including keys in the parent table. So if you mean what you say, my bug would be 'fixed in 3.0'. Are you sure that is what you mean?

**Comment by ajcvickers** [comment] 2019-06-25 20:12
@pwaaijenberg If all the entity types have keys defined, then the query will be tracking by default. If any of the entity types do not have keys defined, then there will be an exception saying that entities without keys can only be used in tracking queries.

**Comment by pwaaijenberg** [comment] 2019-06-25 20:21
@ajcvickers That would be a breaking change. Current docs clearly support my usecase!

if you look at my query (in the initial post) my query returns both parent with full info, and a childcount. As per docs, Parent would be tracked but it is not.

var myQuery = context.Parent.Join(childCountQuery, parent => parent.Id, childcount => childcount.Id, (parent, childcount) => new { parent, childcount.CountForCondition});

If that behaviour is changed, I am sure I am one of many people that will have rework and performance degradation.

**Comment by ajcvickers** [comment] 2019-06-25 20:29
@pwaaijenberg That's because you were relying on a bug for this functionality. It wasn't supposed to work that way.

**Comment by pwaaijenberg** [comment] 2019-06-25 20:49
Only because I needed a subquery to filter the amount of child records. It works without the include if I do not need the filter. And that behaviour is fully documented and more often implemented.

 What I understand from your statement is that a simple query with a count of children will also track the parent.

**Comment by ajcvickers** [comment] 2019-06-25 20:54
@pwaaijenberg Can you point to where it is documented?

**Comment by pwaaijenberg** [comment] 2019-06-25 21:06
@ajcvickers https://docs.microsoft.com/en-us/ef/core/querying/tracking

**Tracking and projections**
Even if the result type of the query isn't an entity type, if the result contains entity types they will still be tracked by default. In the following query, which returns an anonymous type, the instances of Blog in the result set will be tracked.

```
using (var context = new BloggingContext())
{
    var blog = context.Blogs
        .Select(b =>
            new
            {
                Blog = b,
                Posts = b.Posts.Count()
            });
}

```
What I am trying to work around here is that if I use a subquery like b.Posts.Count(p => p.type == 1) instead of a straightforward b.Posts.Count() the query becomes n+1 SQL Server statements.

I expect that Join statement itself is not documented but it is a workaround suggested on various sites like stackoverflow. Just helping out the parser :)

If EF can optimize the subquery I would not need to make it harder for the parser.

**Comment by ajcvickers** [comment] 2019-06-25 21:20
@pwaaijenberg Thanks. We should update the documentation to make it clear that this applies only for tracking queries. Since keyless entity types are not allowed in tracking queries, this documentation doesn't apply. Thanks for pointing that out. /cc @divega

**Comment by pwaaijenberg** [comment] 2019-06-25 21:23
@ajcvickers @divega please explain why my query is not tracking as it is not keyless.

**Comment by ajcvickers** [comment] 2019-06-25 21:25
@pwaaijenberg If it's not keyless, then it an be tracking (all entity instances are tracked) or not-tracking (no entity instances are tracked). What I am trying to say is that it can't be half-tracking and half not.

**Comment by pwaaijenberg** [comment] 2019-06-25 21:31
Ok not fully understanding the difference. Hope Diego can do some ninja guru explaining :-)

Thanks for your time Arthur really appreciate it. When I have time (no promises) I will check what the result will be using EF Core 3.x hope it's not breaking too much and there will be a feasable upgrade path.

**Comment by divega** [comment] 2019-06-26 00:52
@pwaaijenberg in the title of the issue you mention DBQuery. I (and I think @ajcvickers too) infer from that that one of the types your query materializes is a [query type](https://docs.microsoft.com/ef/core/modeling/query-types). In EF Core 3.0 we are consolidating query types together with entity types. 

The key (pun intended) difference between what used to be known as query types and regular entity types is that the former don't have keys. Hence the new terminology we use is "key-less entities".

If your query includes such "key-less entities", then the rules that @ajcvickers explained apply: they currently cannot be involved in tracked queries, hence in 3.0 it will not be possible to have a tracked query that returns a mix of key-less entities and regular entities. 

That said, if your query returns a mix of non-mapped objects (e.g. anonymous types, DTOs, and scalar values) and regular entities, then it should be able to make that query tracked and for any entities returned from that query to be tracked. 

In fact, in 3.0 we are fixing a number of bugs in which such mix would result in the regular entities returned by the query not to be tracked even when they were supposed to be tracked.

**Comment by pwaaijenberg** [comment] 2019-06-26 11:54
Thanks! That really clarifies it and also takes away some of my worries. I learned a few new things also today.

Again, I really appreciate the time both of you have spent on this!

**Comment by divega** [comment] 2019-06-26 17:23
Glad to help. One more question: does your query really need key-less entities (e.g. because an object in the database that is mapped to one of those is the root of the query), or can you work with non-mapped objects?

**Comment by pwaaijenberg** [comment] 2019-06-26 22:42
The use of fromsql was a solution to fix imperfect translation from linq / lambda to sql (resulting in n+1 SQL queries). EF 4.x was better in that situation, it translates the complex lambda I need into one SQL statement. So I needed a //hack to make it work.

So with improved query translation in 3.0 I hope we can just use one lambda on dbcontext without using the join, DBQuery or FromSql.

And as a last resort I can also use two separate lambda statements, enumerate them and join them in memory. It is a small result set from which some items need to be updated so I want to track them.

**Comment by divega** [comment] 2019-06-27 00:24
@pwaaijenberg Understood. Sorry if I asked you to explain this again. 

For what is worth, looking at your original post, I think you could actually make the object that you use for counting children a regular entity with a key using EF Core 2.2. The key would be the id from the parent. Because the query you use is GROUP BY the id of the parent, you won't have duplicates, hence the id is a proper primary key. This should allow you to just write normal tracking queries and still use FromSql() to issue your own SQL query (this is orthogonal to regular entities or query types/key-less entities).

This might still be strange in the sense that the child count entity will also be tracked although it can never be persisted (if by mistake you ever make a change to one of them, EF Core will try to produce an updates based on the name of table that actually doesn't exists). But I think if you are careful not to change them, it can work well.

Besides any improvements in LINQ translation that might help translate b.Posts.Count(p => p.type == 1) (which BTW, I am not 100% sure when this will arrive), in the future we can lift some restrictions to make this easier.

**Comment by smitpatel** [comment] 2019-06-27 01:22
It should already be working.

**Closed** 2022-10-16 13:51 UTC
Labels: closed-out-of-scope, customer-reported
