### ISSUE TITLE
Update-database not finding migrations when solution is moved to a different computer

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#10666] opened 2018-01-09 17:02 UTC
Describe what is not working as expected.
I have a solution that I created along with migrations, successfully created the database and then uploaded to dropbox. It's using latest EF Core 2.0.1.

I pulled the solution down to another computer..running the same version of Windows 10 (FCU) and same version of VS2017 (15.5.2), the same version of SQL Server LocalDB and the same (latest) version of .NET Core installed.

When I ran update-database to create the database on this machine, I kept getting the "migrations already run" message. The new database got created along with the update-history table, but no migrations got run and nothing was added to update history.

After trying a variety of troubleshooting steps, I finally deleted migrations folder completely as well as the database, ran add-migration, and then update-database and the database got created correctly.

I can't seem to find a related issue but wanted to be sure this wasn't a duplicate (or familiar) before I added more information to this issue.

**Comment by bricelam** [comment] 2018-01-09 23:22
Doesn't sound familiar. Was the Startup project different between the two?

**Comment by julielerman** [comment] 2018-01-11 00:58
nope. Weird. I'll experiment with it some time and loop back.

**Comment by ajcvickers** [comment] 2018-01-17 20:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by julielerman** [comment] 2018-01-17 22:22
\_(ツ)_/¯   :)

**Comment by bricelam** [comment] 2018-01-17 23:26
Please loop back here with anything you find. We "timeout" all issues waiting on for a response longer than seven days in an attempt to increase our focus.

**Comment by julielerman** [comment] 2018-02-23 18:20
hey @bricelam ! I'm having the problem again ..testing when someone reported the problem from downloading my samples for Pluralsight. I will put the solution on GH and give you a link. 

This is using EF COre 2.0.3, Visual Studio 2017 15.5.6 on windows 10 latest updates.

**Comment by julielerman** [comment] 2018-02-23 18:25
Repo: https://github.com/julielerman/EFCore2MigrationsProblemForBrice
Here's a screenshot so you can see the WebApp is startup, Data is default project, there's stuff in the initial migration and response to update-database "no migrations applied. The database is already up to date."

Is there something I've done wrong with the setup by including the migrations? 

![image](https://user-images.githubusercontent.com/5007120/36610068-f2899bf8-189c-11e8-8660-76618f589a0f.png)

**Comment by smitpatel** [comment] 2018-02-23 23:57
I cloned the project and got repro.

**Comment by julielerman** [comment] 2018-02-24 01:56
is there anything obvious about my solution that would create this problem?  Since it's the 2nd one I've seen this with ...but haven't tried others ...the only common denominators are 1) Julie 2) VS2017.

**Comment by smitpatel** [comment] 2018-02-24 02:23
There wasn't anything obviously wrong with the project. When i tried adding a new migration I found out what is causing this issue.

When I added new Migration it added 2 files to my project (beside existing migrations), migration file & designer file. Both existing migrations do not have designer files associated with them.
Looking at the structure of designer file & Code to retrieve migrations, each designer file (which is partial class of migration file) has DbContextAttribute & MigrationAttribute. DbContextAttribute tells which Context it belongs to. So in this case we saw the migration but deduced they don't belong to our context and ignored them. Hence Database is up-to-date. When I copied over both the attributes to existing migrations (and updated the MigrationAttribute to correct Id), they were applied correctly to server.

(MigrationAttribute tells the MigrationId to tools. Missing MigrationAttribute was throwing, @bricelam converted it to warning in #9920)

**Comment by julielerman** [comment] 2018-02-24 02:44
oh! I wonder if those are being trashed by gitignore?

**Comment by julielerman** [comment] 2018-02-24 02:52
nothing in gitignore. I wonder if git -fxd is removing them. These were solutions to share so I was cleaning them. Will see if I can replicate that...

**Comment by julielerman** [comment] 2018-02-24 02:55
nope that isn't doing it (I didn't think so , but trying to figure out how they are not making it up to github)

**Comment by julielerman** [comment] 2018-02-24 03:15
happy to close this issue now if you got what you needed from it

**Closed** 2022-10-16 12:05 UTC
Labels: closed-no-further-action
