### ISSUE TITLE
could not be translated. Either rewrite the query in a form that can be translated

### ISSUE THREAD

**Issue by Zqasim132** [dotnet/efcore#27905] opened 2022-04-28 07:42 UTC
```c#
var query = 
    from reservation in (await GetDbSetAsync())
    join ReservationDetail in (await GetDbContextAsync()).ReservationDetails on reservation.Id equals ReservationDetail.Reservation into reservationDetails
    select new ReservationWithNavigationProperties
    {
        Reservation = reservation,
        ReservationDetails = reservationDetails.ToList()
    };

var result = await query.ToListAsync()
```

**I am getting this error**

```
System.InvalidOperationException: The LINQ expression 
DbSet<Reservation>()
    .GroupJoin(
        inner: DbSet<ReservationDetail>(), 
        outerKeySelector: reservation => (Guid?)reservation.Id, 
        innerKeySelector: ReservationDetail => ReservationDetail.Reservation, 
        resultSelector: (reservation, reservationDetails) => new ReservationWithNavigationProperties{ 
            Reservation = reservation, 
            ReservationDetails = reservationDetails
                .ToList() 
        }
    )
```

**Comment by Zqasim132** [comment] 2022-04-28 07:45
![image](https://user-images.githubusercontent.com/87508623/165703118-d67b8e6e-af56-4bc0-ac7b-1263c5c1bd01.png)

**Comment by roji** [comment] 2022-04-28 07:51
Duplicate of #19930

**Closed** 2022-10-16 20:33 UTC
Labels: closed-duplicate, customer-reported
