### ISSUE TITLE
How to create User defined functions using ef core 2.0 code first approach?

### ISSUE THREAD

**Issue by viveknuna** [dotnet/efcore#10712] opened 2018-01-15 15:09 UTC
I want to create user-defined functions using code first approach. I'm able to create Stored Procedures by add example.sql inside EntityFrameworkCore\Migrations\Stored Procedures folder but not able to find a way to create UDF, so that I can add them to migration in C# code. So once I run update-database it will create UDF in DB.

Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.5.3

**Comment by SSkovboiSS** [comment] 2018-01-15 16:51
@viveknuna please check section 'Database scalar function mapping' here:
https://docs.microsoft.com/en-us/ef/core/what-is-new/

**Comment by viveknuna** [comment] 2018-01-15 18:32
So it means Currently only scalar functions are supported and We must create the mapped function in the database, e.g. EF Core migrations will not take care of creating it. So it means I have to explicitly create function in DB as well, Migration won’t consider functions. Right?

**Comment by SSkovboiSS** [comment] 2018-01-15 19:27
Right, but you can create empty migration and declare your function there instead of explicitly creating it on database. Something like this:

```
public partial class age_at_date : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
@"CREATE FUNCTION  [AgeAtDate] (@birthDate DATETIME, @passedDate DATETIME) RETURNS INT
    AS
    BEGIN
        DECLARE @iMonthDayBirthDate INT
        DECLARE @iMonthDayPassedDate INT

        SELECT @iMonthDayBirthDate = CAST( DATEPART(mm, @birthDate)*100 + DATEPART(dd, @birthDate) AS INT)
        SELECT @iMonthDayPassedDate = CAST( DATEPART(mm, @passedDate)*100 + DATEPART(dd, @passedDate) AS INT)

        RETURN DATEDIFF(yy, @birthDate, @passedDate)
            - CASE WHEN @iMonthDayBirthDate <= @iMonthDayPassedDate
                THEN 0
                ELSE 1
              END
    END");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP FUNCTION [AgeAtDate]");
        }
    }
```

**Comment by viveknuna** [comment] 2018-01-16 05:39
Thanks a lot for your help, Its creating scalar-valued function, but in my case, I need to create table-valued function. I know its EF Core limitations that We cannot create table-valued functions, Is there any way or some hack to create a table valued function?

Thanks a lot for your help :)

**Comment by Tarig0** [comment] 2018-01-16 16:03
There's nothing stopping you from using fromsql to call the function directly.

**Comment by pmiddleton** [comment] 2018-01-16 16:36
There is already an open issue for this #9393 you can track.

**Comment by ajcvickers** [comment] 2018-01-19 20:17
Closing as a duplicate of #9393

**Closed** 2022-10-16 12:05 UTC
