### ISSUE TITLE
Guid property not being seeded with attribute DatabaseGenerated(DatabaseGeneratedOption.Identity)

### ISSUE THREAD

**Issue by bspraguetx** [dotnet/efcore#12232] opened 2018-06-04 19:15 UTC
We are currently using EF Core 2.0.2 and are trying to migrate to EF Core 2.1.0.  Most of our data entities inherit from a base class where primary key, Id, is defined as a Guid and is marked up with the attributes Key and DatabaseGenerated(DatabaseGeneratedOption.Identity). 

In both the 2.0.2 and 2.1.0, the table models look identical in regards to the way the Id column is generated, IE "Id = table.Column<Guid>(nullable: false),".  When using EF Core 2.0.2, the Id column value is being automatically set when a new item is added to a table.  When using EF Core 2.1.0, the Id column value is not being set and causing NULL insert errors.  What I want to know is whether this is a bug or a change in behavior?  If it's a change in behavior, is is documented somewhere?

**Comment by ajcvickers** [comment] 2018-06-07 17:10
@bspraguetx I haven't been able to reproduce what you are seeing. Can you please post a runnable project/solution or code listing that reproduces the behavior you are seeing? You might want to try updating the code below to make it match what you are seeing.

```C#
public class BlogBase
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }
}

public class Blog : BlogBase
{
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>();
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var blog = new Blog();
            context.Add(blog);
            context.SaveChanges();

            Console.WriteLine(blog.Id);
        }

        using (var context = new BloggingContext())
        {
            var blog = context.Set<Blog>().Single();
            Console.WriteLine(blog.Id);
        }
    }
}
```

**Comment by bspraguetx** [comment] 2018-06-07 17:13
Thanks for the feedback.  I’ll try to get to this in the next few days.

Brad Sprague
Software Engineer, Architect
Credit Union Solutions / Portico
Fiserv.
Office: 469-287-3845
Fax: 469-287-3606
www.fiserv.com<http://www.fiserv.com/>

FORTUNE Magazine World's Most Admired Companies® 2014 | 2015 | 2016 | 2017 | 2018

Facebook: Like Fiserv<http://www.facebook.com/fiserv>  ·  Twitter: Follow @Fiserv<http://www.twitter.com/fiserv>  ·  LinkedIn: Connect Fiserv<http://www.linkedin.com/company/fiserv>
Flipboard: Follow Fiserv Forward<http://fisv.co/fiserv-forward>  ·  Careers: Join Fiserv<http://fisv.co/1orAdkH>

**Comment by bspraguetx** [comment] 2018-06-11 20:35
Unfortunately, we have not been able to recreate this issue in a small ASP.Net Core application.  It works as expected.  What is the best way to go about determining why the behavior of our application changes when we upgrade?  We’re not doing anything exotic in our data entities or our DbContext object.  We’ve tried debugging into the EF Core code to try to determine why the insert statements are different but have not had any luck due to the abstract complexity of the code.  We can’t seem to walk into the spot where the insert statements are be generated.

Here are some additional details that we can provide.

All of data entities inherit from a base class that defines the Id field as GUID with the Key and DatabaseGenerated attributes set.
public abstract class EntityBase : IEntity
{
    /// <summary>
    /// The entity's primary key
    /// </summary>
    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }
}

When running with EF Core 2.0, the insert statements for the entities look like the following.  Notice that the Id column is included which is appropriate since the table schema does not define the column as being an identity column with an auto-incrementing value.

INSERT INTO [RolePermissions] ([RoleId], [PermissionId], [CreateApplication], [CreateBy], [CreateEmail], [CreateHostName], [CreateTimestamp], [Id], [ModifyApplication], [ModifyBy], [ModifyEmail], [ModifyHostName], [ModifyTimestamp])

When running with EF Core 2.1, the insert statements for the entities look like the following.  Notice that the Id column is NOT included.  This would be appropriate if the column had a default value defined in the table schema but it does not.

INSERT ([RoleId], [PermissionId], [CreateApplication], [CreateBy], [CreateEmail], [CreateHostName], [CreateTimestamp], [ModifyApplication], [ModifyBy], [ModifyEmail], [ModifyHostName], [ModifyTimestamp])

Thanks

Brad Sprague
Software Engineer, Architect
Credit Union Solutions / Portico
Fiserv.
Office: 469-287-3845
Fax: 469-287-3606
www.fiserv.com<http://www.fiserv.com/>

FORTUNE Magazine World's Most Admired Companies® 2014 | 2015 | 2016 | 2017 | 2018

Facebook: Like Fiserv<http://www.facebook.com/fiserv>  ·  Twitter: Follow @Fiserv<http://www.twitter.com/fiserv>  ·  LinkedIn: Connect Fiserv<http://www.linkedin.com/company/fiserv>
Flipboard: Follow Fiserv Forward<http://fisv.co/fiserv-forward>  ·  Careers: Join Fiserv<http://fisv.co/1orAdkH>

**Comment by ajcvickers** [comment] 2018-06-11 22:16
@bspraguetx At the moment I don't see anything else that provides any good clues as to what is going on.
Is there any other configuration of the key property?

**Comment by bspraguetx** [comment] 2018-06-12 11:51
No, there is no other configuration.  Any tips on trying to find the issue through the debugger?

Brad

**Comment by ajcvickers** [comment] 2018-06-12 16:04
@bspraguetx No, I'm out of ideas. I don't think we are going to be able to do much without a repro.

**Comment by ajcvickers** [comment] 2018-06-19 17:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:28 UTC
Labels: closed-could-not-reproduce, customer-reported
