### ISSUE TITLE
GroupJoin does not correctly translate resultSelector to SQL.

### ISSUE THREAD

**Issue by Dixin** [dotnet/efcore#7416] opened 2017-01-15 05:26 UTC
GroupJoin does not translate resultSelector correctly:
```c#
var leftOuterJoin = adventureWorks.Products.GroupJoin(
    inner: adventureWorks.Transactions,
    outerKeySelector: product => product.ProductID,
    innerKeySelector: transaction => transaction.ProductID,
    resultSelector: (product, transactions) => new
    {
        Name = product.Name,
        ActualCosts = transactions.Select(transaction => transaction.ActualCost)
    });
```
The projection is specified in the resultSelector.

In EF, the required 2 columns (and the key and a null identifier) are queried, which is correct:
```sql
SELECT 
    [Project1].[ProductID] AS [ProductID], 
    [Project1].[Name] AS [Name], 
    [Project1].[C1] AS [C1], 
    [Project1].[ActualCost] AS [ActualCost]
    FROM ( SELECT 
        [Extent1].[ProductID] AS [ProductID], 
        [Extent1].[Name] AS [Name], 
        [Extent2].[ActualCost] AS [ActualCost], 
        CASE WHEN ([Extent2].[ProductID] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1]
        FROM  [Production].[Product] AS [Extent1]
        LEFT OUTER JOIN [Production].[TransactionHistory] AS [Extent2] ON ([Extent2].[TransactionType] IN (N'P',N'S',N'W')) AND ([Extent1].[ProductID] = [Extent2].[ProductID])
    )  AS [Project1]
    ORDER BY [Project1].[ProductID] ASC, [Project1].[C1] ASC
```

However, in EF Core, all columns of both tables are queried:
```sql
SELECT 
[product].[ProductID], 
[product].[ListPrice], 
[product].[Name], 
[product].[ProductSubcategoryID], 
[product].[RowVersion], 
[transaction].[TransactionID], 
[transaction].[ActualCost], 
[transaction].[ProductID], 
[transaction].[Quantity], 
[transaction].[TransactionDate], 
[transaction].[TransactionType]
FROM [Production].[Product] AS [product]
LEFT JOIN [Production].[TransactionHistory] AS [transaction] ON [product].[ProductID] = [transaction].[ProductID]
ORDER BY [product].[ProductID]
```
It seems the resultSelector is not translated.

**Comment by maumar** [comment] 2017-01-17 20:49
dupe of https://github.com/aspnet/EntityFramework/issues/6647

**Closed** 2022-10-16 10:50 UTC
Labels: closed-duplicate
