### ISSUE TITLE
Is there a simple method to get if the database provider is a relational database provider or not?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/efcore#19486] opened 2020-01-05 10:36 UTC
I'm wanna to create an index if the database provider the a relational database provider, otherwise do not create, sometimes I would use InMemory for test, and my database may be sqlserver/mysql

for now:

I'm doing it like this:

``` csharp
if (!Database.ProviderName.Equals("Microsoft.EntityFrameworkCore.InMemory"))
{
    modelBuilder.Entity<Notice>().HasIndex(x => x.NoticeCustomPath);
}
```

and then had a look on the source, find another way:

``` csharp
if (((IDatabaseFacadeDependenciesAccessor)Database).Dependencies is
                IRelationalDatabaseFacadeDependencies)
{
    modelBuilder.Entity<Notice>().HasIndex(x => x.NoticeCustomPath);
}
```

but it was not recommended to use, I got the warning like follows:

![](https://img2018.cnblogs.com/blog/489462/202001/489462-20200105183616524-83869910.png)

so I'm wondering if there's a simple method could do help

wondering for an api like this:

``` csharp
if(Database.IsRelational())
{
    modelBuilder.Entity<Notice>().HasIndex(x => x.NoticeCustomPath);
}
```

**Comment by ErikEJ** [comment] 2020-01-05 10:42
You can use the extension methods on the .Database property:

    if (dbContext.Database.IsSqlServer())
    {
       modelBuilder.Entity<Notice>().HasIndex(x => x.NoticeCustomPath);
    }

**Comment by WeihanLi** [comment] 2020-01-05 11:00
> You can use the extension methods on the .Database property:
> 
> ```
> if (dbContext.Database.IsSqlServer())
> {
>    modelBuilder.Entity<Notice>().HasIndex(x => x.NoticeCustomPath);
> }
> ```

I use this method before, but if I wanna change my database to mysql, these code had to change to mysql, and I had to add reference for mysql provider package, and  there's an extension method like `IsRelational` , I can remove the concrete database provider references

**Comment by ajcvickers** [comment] 2020-01-06 17:51
Duplicate of #6983

**Closed** 2022-10-16 18:04 UTC
Labels: closed-duplicate, customer-reported
