### ISSUE TITLE
Cartesian join of four tables is failed to materialize

### ISSUE THREAD

**Issue by mingazhev** [dotnet/efcore#18209] opened 2019-10-03 17:59 UTC
Assume we have four tables:
- Users (bound to entity "User")
- Companies (bound to entity "Company")
- Branches (bound to entity "Branch)
- Relations (bound to entity "Relation")

User is related to company with many-to-many relation using "Relations" table. Each relation contains:
- UserId
- CompanyId
- BranchId (can be null)

To fetch all user information with single query I use query with following syntax:

``` C#
from user in _context.Users
from relation in _context.Relations.Where(r => r.UserId== user.Id)
from company in _context.Companies.Where(c => c.Id == relation.CompanyId)
from branch in _context.Branches.Where(b => b.Id == relation.BranchId).DefaultIfEmpty()
                    where user.Id == 11
                    select new UserInfo(user,
                        company,
                        branch);
```

where '11' is UserId.

This query produces the correct SQL with cross\lateral joins and this SQL query executes correct (tried manually).
But when EF tries to materialize 'Branch' entity it fails with error 

> Unable to cast object of type 'System.Int32' to type 'System.DateTime'.

Tried to fetch only branches to check if "Branch" entity is misconfigured - works perfect. Than I tried to fetch info using query above excluding "Company" - it works correct too. Removing .DefaultIfEmpty helps too.
Tried to remove existing DateTime columns in Branch - there is same error but now with casting Int32 to String.

### Steps to reproduce

1. Create Entities:
``` C#
public class User { public int Id {get;set; } }

public class Company{ public int Id {get;set; } }

public class Branch
{ 
public int Id {get;set; } 
public string Title {get;set;}
public DateTime Created {get;set;}
public DateTime Modified {get;set;}
}
public class Relation
{
 public int CompanyId {get;set; }
 public int UserId {get;set; }
 public int? BranchId {get;set; }
 }

```
And container class:
``` c#
public class UserInfo
{
  public UserInfo(User user, Company, company, Branch branch)
  {
    User = user;
    Company = company;
    Branch = branch;
  }
  public User User {get;set;}
  public Company Company {get;set;}
  public Branch Branch {get;set;}
}
```
2. Create DbSets and generate schema.
3. Create one entity for each type (Relation should contain correct Id's for user, branch and company)
3. Try execute query:
``` C#
from user in _context.Users
from relation in _context.Relations.Where(r => r.UserId== user.Id)
from company in _context.Companies.Where(c => c.Id == relation.CompanyId)
from branch in _context.Branches.Where(b => b.Id == relation.BranchId).DefaultIfEmpty()
                    where user.Id == 11
                    select new UserInfo(user,
                        company,
                        branch);
```

Exception: 

>    at Microsoft.EntityFrameworkCore.Query.EntityLoadInfo.Materialize()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.GetEntity(IKey key, EntityLoadInfo entityLoadInfo, Boolean queryStateManager, Bool
ean throwOnNullKey)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.BufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer& valueB
uffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.BufferedOffsetEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer&
valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Shape(QueryContext queryContext, Val
ueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Microsoft.EntityFrameworkCore.Query.
ExpressionVisitors.Internal.IShaper<TResult>.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, V
alueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Microsoft.EntityFrameworkCore.Quer
y.ExpressionVisitors.Internal.IShaper<TOut>.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, Canc
ellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded
, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded
, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SingleOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\So
urce\System.Interactive.Async\Single.cs:line 159
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken ca
ncellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(Cance
llationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQu
ery, IDiagnosticsLogger`1 logger, Type contextType)
   at {{domain code}}

### Further technical details

EF Core version: 2.2.4
Database provider: Npgsql.EntityFrameworkCore.PostgreSql
Target framework: .NET Core 2.2
Operating system: Windows 10 Pro
IDE: Rider 2019.2.2

**Comment by smitpatel** [comment] 2019-10-03 18:57
Please try 3.0 release.

**Comment by ajcvickers** [comment] 2019-10-10 18:47
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:47 UTC
Labels: closed-could-not-reproduce, customer-reported
