### ISSUE TITLE
Skip entity that should not have its own table in migrations

### ISSUE THREAD

**Issue by poke** [dotnet/efcore#3436] opened 2015-10-15 12:58 UTC
Hey, in order to consume stored procedures, as per #1864, I created a new entity type just to match the return type of the stored procedure. Since that entity does not reflect an actual table, I would like it to be mostly ignored by the database context though. I especially don’t want to create migrations for the entity that would result in creating a new table.

Is there any way to only register entities in a database context so that I can use them for mapping stored procedure results but ignore them for everything else?

Of course I can manually handle this for the time being by just removing the table completely from the generated migrations, but I would rather register the entity type properly in the first place. I’m aware that as per #245, support for stored procedures isn’t completed yet.

**Comment by rowanmiller** [comment] 2015-10-16 22:11
Dupe of https://github.com/aspnet/EntityFramework/issues/2725 - we agree it would be useful :smile:

**Closed** 2022-10-16 09:12 UTC
