### ISSUE TITLE
adding ef to a ef core library

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/efcore#5425] opened 2016-05-19 19:07 UTC
Hi all,I trying to rebuild a project I created with rc1, and I started trying to recreate a library with a ef context and a few api controllers to be shared among project.
To do this I created a .Net Core Class Library, copied a few classes, and opened project.json and tried to add the references to entityframework packages.
I tried to add EntityFramework.Core

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24027",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final" 
  },

  "frameworks": {
    "netstandard1.5": {
      "imports": "dnxcore50"
    }
  }
}
```

and I have the error
![untitled](https://cloud.githubusercontent.com/assets/127777/15406166/8e15068c-1e05-11e6-875a-4facf5b666a1.png)

Where can I find informations on how to create a library with ef?

**Comment by smitpatel** [comment] 2016-05-19 19:37
You will need additional imports. See issue #5176

**Comment by lucamorelli** [comment] 2016-05-19 19:47
In short have to wait for rtm? I don't understand what I have to add

**Comment by smitpatel** [comment] 2016-05-19 19:56
You need to add imports as mentioned here https://github.com/aspnet/EntityFramework/issues/5176#issuecomment-216705192

**Comment by natemcmaster** [comment] 2016-05-19 20:11
Closing as a duplicate of #5176. I have added an explanation of the workaround to our RC2 docs. (See https://github.com/aspnet/EntityFramework.Docs/pull/167).

**Closed** 2022-10-16 09:41 UTC
