### ISSUE TITLE
Migrations for default configurations are generated in wrong order

### ISSUE THREAD

**Issue by KaabiTaoufik** [dotnet/efcore#32264] opened 2023-11-09 09:28 UTC
## when running add-migration the generated insert sql queries are generated in wrong order result to update-database to fail.
**FYI : this is only a test project so don't attack me for having a password in the code** 😋 
I've been testing out EF lately and wanted to try having default users and their roles within my application for easier access when I switch working computers.

### code

```ApplicationDbContext.cs
    public class ApplicationDbContext : IdentityDbContext<Employee>
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            builder.ApplyConfiguration(new RoleSeedConfiguration());
            builder.ApplyConfiguration(new UserSeedConfiguration());
            builder.ApplyConfiguration(new UserRoleSeedConfiguration());
        }
        public DbSet<LeaveType> LeaveTypes { get; set; }
        public DbSet<LeaveAllocation> LeaveAllocations { get; set; }
    }
```

```RoleSeedConfiguration.cs

    public class RoleSeedConfiguration : IEntityTypeConfiguration<IdentityRole>
    {
        public void Configure(EntityTypeBuilder<IdentityRole> builder)
        {
            builder.HasData(
                new IdentityRole
                {
                    Id = "ebe6352a-a838-44a6-a1d8-a8daaaa5bb50",
                    Name = "Administrator",
                    NormalizedName = "ADMINISTRATOR",
                },
                new IdentityRole
                {
                    Id = "53d14e40-8320-4bea-9bfd-ca3f40a55bc4",
                    Name = "User",
                    NormalizedName = "USER",
                });
        }
    }
```

```UserSeedConfiguration.cs

    public class UserSeedConfiguration : IEntityTypeConfiguration<Employee>
    {
        public void Configure(EntityTypeBuilder<Employee> builder)
        {
            var hasher = new PasswordHasher<Employee>();
            builder.HasData(
                new Employee
                {
                    Id = "d2a475a0-482e-461e-876a-ad906172dfdb",
                    Email = "admin@test.com",
                    NormalizedEmail = "ADMIN@TEST.COM",
                    FirstName = "Sys",
                    LastName = "Admin",
                    PasswordHash = hasher.HashPassword(null, "a")
                },
                new Employee
                {
                    Id = "b20b4d78-e4bf-4cbd-9e1e-e2395464de28",
                    Email = "user@test.com",
                    NormalizedEmail = "USER@TEST.COM",
                    FirstName = "Sys",
                    LastName = "User",
                    PasswordHash = hasher.HashPassword(null, "a")
                });
        }
    }
```

```UserRoleSeedConfiguration.cs

    public class UserRoleSeedConfiguration : IEntityTypeConfiguration<IdentityUserRole<string>>
    {
        public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Microsoft.AspNetCore.Identity.IdentityUserRole<string>> builder)
        {
            builder.HasData(
                new IdentityUserRole<string>
                {
                    RoleId = "ebe6352a-a838-44a6-a1d8-a8daaaa5bb50",
                    UserId = "d2a475a0-482e-461e-876a-ad906172dfdb",
                },
                new IdentityUserRole<string>
                {
                    RoleId = "bacc28e8-48b1-4cce-9b7c-1bdf74df2464",
                    UserId = "53d14e40-8320-4bea-9bfd-ca3f40a55bc4",
                }); 
        }
    }
```

- after running add-migration here's the result:

```Inside the migration file
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.InsertData(
        table: "AspNetRoles",
        columns: new[] { "Id", "ConcurrencyStamp", "Name", "NormalizedName" },
        values: new object[,]
        {
            { "53d14e40-8320-4bea-9bfd-ca3f40a55bc4", null, "User", "USER" },
            { "ebe6352a-a838-44a6-a1d8-a8daaaa5bb50", null, "Administrator", "ADMINISTRATOR" }
        });

    migrationBuilder.InsertData(
        table: "AspNetUserRoles",
        columns: new[] { "RoleId", "UserId" },
        values: new object[] { "bacc28e8-48b1-4cce-9b7c-1bdf74df2464", "53d14e40-8320-4bea-9bfd-ca3f40a55bc4" });

    migrationBuilder.InsertData(
        table: "AspNetUsers",
        columns: new[] { "Id", "AccessFailedCount", "ConcurrencyStamp", "DateJoined", "DateOfBirth", "Email", "EmailConfirmed", "FirstName", "LastName", "LockoutEnabled", "LockoutEnd", "NormalizedEmail", "NormalizedUserName", "PasswordHash", "PhoneNumber", "PhoneNumberConfirmed", "SecurityStamp", "TaxId", "TwoFactorEnabled", "UserName" },
        values: new object[,]
        {
            { "b20b4d78-e4bf-4cbd-9e1e-e2395464de28", 0, "d8f10c75-bbef-4107-b8fc-afe08dfbe52d", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "user@test.com", false, "Sys", "User", false, null, "USER@TEST.COM", null, "AQAAAAIAAYagAAAAEPLjGd37JlUbdLGz9Mmy3YKWvq5bcQ3Z7z1iwgt3MkFBVbZ5EKj18Y73ruww8PmrQQ==", null, false, "ed95501b-6874-4c35-b24e-110fc80a22d5", null, false, null },
            { "d2a475a0-482e-461e-876a-ad906172dfdb", 0, "9b9288ac-9e2a-4a19-b26f-8fb0bd12be85", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin@test.com", false, "Sys", "Admin", false, null, "ADMIN@TEST.COM", null, "AQAAAAIAAYagAAAAEHO3pYaXiQYzYZvwnxgodJGKm8A+ikduI0lz5lMGqXRa6Q/CunaMhPPcJLRjhP/Ijw==", null, false, "54566884-4924-4822-a8d4-e12bc54e6527", null, false, null }
        });

    migrationBuilder.InsertData(
        table: "AspNetUserRoles",
        columns: new[] { "RoleId", "UserId" },
        values: new object[] { "ebe6352a-a838-44a6-a1d8-a8daaaa5bb50", "d2a475a0-482e-461e-876a-ad906172dfdb" });
}
```

- and what I expected:

```Expected migration
protected override void Up(MigrationBuilder migrationBuilder)
{

            migrationBuilder.InsertData(
                table: "AspNetRoles",
                columns: new[] { "Id", "ConcurrencyStamp", "Name", "NormalizedName" },
                values: new object[,]
                {
                    { "53d14e40-8320-4bea-9bfd-ca3f40a55bc4", null, "User", "USER" },
                    { "ebe6352a-a838-44a6-a1d8-a8daaaa5bb50", null, "Administrator", "ADMINISTRATOR" }
                });

    migrationBuilder.InsertData(
        table: "AspNetUsers",
        columns: new[] { "Id", "AccessFailedCount", "ConcurrencyStamp", "DateJoined", "DateOfBirth", "Email", "EmailConfirmed", "FirstName", "LastName", "LockoutEnabled", "LockoutEnd", "NormalizedEmail", "NormalizedUserName", "PasswordHash", "PhoneNumber", "PhoneNumberConfirmed", "SecurityStamp", "TaxId", "TwoFactorEnabled", "UserName" },
        values: new object[,]
        {
            { "b20b4d78-e4bf-4cbd-9e1e-e2395464de28", 0, "d8f10c75-bbef-4107-b8fc-afe08dfbe52d", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "user@test.com", false, "Sys", "User", false, null, "USER@TEST.COM", null, "AQAAAAIAAYagAAAAEPLjGd37JlUbdLGz9Mmy3YKWvq5bcQ3Z7z1iwgt3MkFBVbZ5EKj18Y73ruww8PmrQQ==", null, false, "ed95501b-6874-4c35-b24e-110fc80a22d5", null, false, null },
            { "d2a475a0-482e-461e-876a-ad906172dfdb", 0, "9b9288ac-9e2a-4a19-b26f-8fb0bd12be85", new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin@test.com", false, "Sys", "Admin", false, null, "ADMIN@TEST.COM", null, "AQAAAAIAAYagAAAAEHO3pYaXiQYzYZvwnxgodJGKm8A+ikduI0lz5lMGqXRa6Q/CunaMhPPcJLRjhP/Ijw==", null, false, "54566884-4924-4822-a8d4-e12bc54e6527", null, false, null }
        });

    migrationBuilder.InsertData(
        table: "AspNetUserRoles",
        columns: new[] { "RoleId", "UserId" },
        values: new object[,] { { "ebe6352a-a838-44a6-a1d8-a8daaaa5bb50", "d2a475a0-482e-461e-876a-ad906172dfdb" },
                                { "bacc28e8-48b1-4cce-9b7c-1bdf74df2464", "53d14e40-8320-4bea-9bfd-ca3f40a55bc4" }});
}
```

### provider and version information

EF Core version: 7.0.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET7.0
Operating system: Windows 11
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment] 2023-11-15 13:52
Note for triage: this is specifically about inserting model data for a dependent before the model data for the principals has been inserted.

/cc @AndriySvyryd @bricelam

**Comment by AndriySvyryd** [comment] 2023-11-15 18:06
For the second `IdentityUserRole` `UserId = "53d14e40-8320-4bea-9bfd-ca3f40a55bc4"` doesn't match any of the specified users. Did you mean to specify `"b20b4d78-e4bf-4cbd-9e1e-e2395464de28"`?

**Comment by ajcvickers** [comment] 2023-11-29 17:21
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-11-29 17:21 UTC
Labels: customer-reported
