### ISSUE TITLE
Add support for Microsoft.EntityFrameworkCore.SqlServer in UWP

### ISSUE THREAD

**Issue by tdjastrzebski** [dotnet/efcore#7932] opened 2017-03-19 10:37 UTC
Please add support for Microsoft.EntityFrameworkCore.SqlServer in UWP. 
In VS 2017 RTM attempt to add this NuGet package  fails.
(Microsoft.NETCore.UniversalWindowsPlatform latest ver 5.3.1, Microsoft.EntityFrameworkCore.SqlServer latest ver 1.1.1)

I suppose the issue is known. Probably there is a reason EF Core samples for UWP 
[Getting Started on Universal Windows Platform (UWP)](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started)
mentions SQLite only, no sample for Scaffold-DbContext.

I report this problem since I found no other reports.
So far I found no way to directly connect to SQL Server from UWP application. Instead, I found official statement saying for that Web API layer needs to be built (!).
[How to access data from SQL Server database in Win10 UWP](https://code.msdn.microsoft.com/windowsapps/How-to-access-data-from-935e360c)
I hope that is a joke :/

As a workaround I have tried creating separate .Net Standard class library as a data access layer. This did not work either. Scaffold-DbContext fails with error:
Could not load file or assembly 'System.Data.SqlClient, Version=4.1.0.0..'

**Comment by ErikEJ** [comment] 2017-03-19 10:52
Duplicate of https://github.com/dotnet/corefx/issues/6751

**Comment by ajcvickers** [comment] 2017-03-20 16:21
Copying Rowan's comment from #4692, which still applies: Closing as there is nothing actionable on the EF side - the EF SQL Server provider will work on UWP if SQL Client is enabled.

Looks like the issue @ErikEJ referenced is tracking this on the corefx side.

**Closed** 2022-10-16 10:57 UTC
