### ISSUE TITLE
.net core 2.2 + ef core connection timeout

### ISSUE THREAD

**Issue by MattHartz** [dotnet/efcore#16137] opened 2019-06-18 15:23 UTC
Hi all,

I am currently running a Service Fabric cluster locally using .net core and ef core. Everything works great in moderation, but during intergration testing I am seeing connection timeouts if ~125 requests are made within a few minute window.

If I am adding the dbcontext at startup, shouldn't the DI container be closing the connection when disposed after the API call has finished? 

If there is a best practice I am neglecting for this, I haven't been able to find a solid article on it.

There's good chance that this issue doesn't lay on ef core's hands, and I can move this where more appropriate.

### Exception Details
System.InvalidOperationException: 'Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.'

   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at ApiService.Attributes.QmeritHeaderAttribute.OnActionExecuting(ActionExecutingContext context) in C:\Users\matth\Documents\Qmerit Code\QmeritBackend\Source\Customer.API\ApiService\Attributes\QmeritHeaderAttribute.cs:line 30

### Steps to reproduce
1. Add "AddDbContext" and "UseSqlServer" with a valid connection.
2. Inject DbContext into an API controller.
3. Get FirstOrDefault of any dbset.
4. Repeat 125x via a script.

### Further technical details
EF Core version: 2.2.4
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10 + Service Fabric v .644
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment] 2019-06-20 21:33
@MattHartz @MattHartz Are you sure that this isn't because you're actually trying to use too many connections? Do you see different behavior if you use ADO.NET directly?

If this is EF related, then can you post the code that registers the `DbContext` in D.I. and the code that resolves it from D.I.?

**Comment by divega** [comment] 2019-06-20 23:27
> If I am adding the dbcontext at startup, shouldn't the DI container be closing the connection when disposed after the API call has finished?

It would be useful to know in what way you came to the conclusion that connections are not being closed. There is a connection pool that keeps physical connections open and that is by-design, so just checking some events on the server may not give you the whole picture of what is happening. 

Possible related issues (same exception observed): https://github.com/aspnet/EntityFrameworkCore/issues/15814 (not under heavy load, on linux), https://github.com/dotnet/SqlClient/issues/18 (thread starvation caused by application code blocking after async calls with .Result).

**Comment by ajcvickers** [comment] 2019-06-28 15:19
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by MattHartz** [comment] 2019-06-28 15:22
Hi all, I was able to fix this issue by updating my connection string to the database to include database pooling. I don't know why I had to do this versus using the extension method in my startup class for database pooling.

**Closed** 2022-10-16 14:26 UTC
Labels: closed-could-not-reproduce, customer-reported
