### ISSUE TITLE
How to setup the DbContext to work with multi-language value tables?

### ISSUE THREAD

**Issue by VitaliiIsaenko** [dotnet/efcore#23172] opened 2020-11-02 13:14 UTC
I got a problem with mapping my relation schema with multi-language support with EF Core ORM and desperately looking for help. I have an `Event` table `(int id, text name, int typeId)` and `EventTypeLocale` table `(int id, text locale, text name)`.

To explain why I cannot restructure my db schema to attach `EventId` to `EventTypeLocale` table - there is an example content in `EventTypeLocale`:

```
(1,'en', 'External event')
(1,'de','Externe Veranstaltung')
(2,'en', 'Internal event ')
(2,'de','Internes Ereignis')
```

And Event table has info about session + its type - `typeId` that should reference `EventTypeLocale` with FK. But, as you can see from the example data - there will be several database rows by one id (since there is a composite key `id + locale`). I want to load the type in all locates into the `EventTypeLocales` collection.

I have two classes
```
public class Event
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int TypeId { get; set; }
    public List<EventTypeLocale> EventTypeLocales { get; set; }
}
public class EventTypeLocale
{
    public int Id { get; set; }
    public string Locale { get; set; }
    public string Name { get; set; }
}
```
The complex part is to configure it in the `Context : DbContext` class. Could you help me to configure such a relation? Is there such a possibility with EF Core? Or how should I change the model/(db schema but less desirable) to achieve what I want?

[The question is also posted on SO](https://stackoverflow.com/questions/64634545/multi-language-support-ef-core-value-tables) and I asked [another question](https://stackoverflow.com/questions/58914671/setup-one-to-many-relation-with-fk-having-multiple-rows) a year ago where I got a working solution for fetching, but it restricts updating the FK field (`typeId`) because it is set up as a principal key. The "working" solution for fetching is below:
```
modelBuilder.Entity<Event>().ToTable("Event");
modelBuilder.Entity<EventTypeLocale>().ToTable("EventTypeLocale")
            .HasKey(p => new {p.Id, p.Locale});
modelBuilder.Entity<Event>()
            .HasMany(e=>e.EventTypeLocales)
            .WithOne()
            .HasForeignKey(x=>x.Id)
            .HasPrincipalKey(x=>x.TypeId);
```
Thank you in advance, I hope you have an idea on how to configure such a relation :pray:

**Comment by ajcvickers** [comment] 2020-11-09 17:21
@VitaliiIsaenko That mapping looks correct and I can't think of a way of doing this that doesn't make `TypeId` an alternate key. Therefore, this is probably a duplicate of #4073

**Closed** 2022-10-16 19:07 UTC
Labels: closed-no-further-action, customer-reported
