### ISSUE TITLE
OrderBy GroupBy Invalid column name

### ISSUE THREAD

**Issue by sylvaincaillot** [dotnet/efcore#12817] opened 2018-07-26 22:45 UTC
Hello, 

Using EF Core 2, I am trying to build a very simple Linq query used to return a json to my client.

the following works:

    _context.MyTable
    .GroupBy(g => new { type= g.TypeId })
    .Select(x => x.Count())

However, I would like to return the count list ordered by type so I wrote the following but it didn't work:

    _context.MyTable
    .GroupBy(g => new { type= g.TypeId })
    .OrderBy(o => o.Key.type)
    .Select(x => x.Count())

It returns a 'invalid column name "type"'

I don't get it, the orderby is occuring after the groupBy, I am using the key properly.
It looks like, the orderBy needs the criteria in the Slect statement to work properly.
For example, the following works:

    _context.MyTable
    .GroupBy(g => new { type= g.TypeId })
    .OrderBy(o => o.Key.type)
    .Select(x => {x.Count(), x.Key.type})

But it does not return what i want, I just want to get the count values ordered by type.

Any directions why I get this error.

S.

**Comment by milosloub** [comment] 2018-07-27 10:38
Try this: 

```
_context.MyTable
.GroupBy(g => g.TypeId)
.OrderBy(o => o.Key)
.Select(x => new { TypeId = x.Key, Count = x.Count() });
```

**Comment by sylvaincaillot** [comment] 2018-07-29 22:39
Thank you @milosloub  but this is not the output I am looking for. I just need the count to be returned not the associated ordering based on the TypeId.

Based on [suggestion in SO](https://stackoverflow.com/questions/51548387/groupby-orderby-linq-invalid-column), i have also tried the following

```
_context.MyTable
    .GroupBy(e => new { e.TypeId })
    .OrderBy(g => g.Key.TypeId)
    .Select(g => g.Count()) 
```
as this user thought it could be related with the key property aliasing but I still get a similar error with  "TypeId is an invalid column name" now.

The only workaround I found is the following:

```
(_context.MyTable
 .GroupBy(g => new { type = g.TypeId })
 .OrderBy(o => o.Key.type)
 .Select(x => new { count = x.Count(), x.Key.type })
).ToList().Select(s=>s.count)
```

which is ugly. 

Hope this bug will be fixed in the next version

**Comment by milosloub** [comment] 2018-07-30 05:49
No, you can't do something like that:
SELECT COUNT()
FROM MyTable
GROUP BY type
ORDER BY type

Because you use GROUP BY on "type" column, you have to add this column to SELECT list. It's nothing to do with EF Core, it's done by SQL design:
https://docs.microsoft.com/en-us/sql/t-sql/queries/select-group-by-transact-sql?view=sql-server-2017

So your query with 
.ToList().Select(s=>s.count)
is the right choice.

**Comment by sylvaincaillot** [comment] 2018-07-30 06:06
Thank you @milosloub.
I admit that you can not use aliasing for this type of query but if you use the column names, it is perfectly correct from an SQL point of view such this one in SQL Server:

```
SELECT COUNT(myTableid) as count    
  FROM MyTable
  GROUP BY TypeId
  ORDER BY TypeId
```
This is why I would expect the following statement to work with EFCore:

```
_context.MyTable
    .GroupBy(e => new { e.TypeId })
    .OrderBy(g => g.Key.TypeId)
    .Select(g => g.Count())
```

Thank you

S.

**Comment by smitpatel** [comment] 2018-07-31 22:28
Repro:
```C#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database


                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                db.Blogs.GroupBy(b => new { Type = b.Id }).OrderBy(g => g.Key.Type).Select(g => g.Count()).ToList();
            }

            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        private static ILoggerFactory LoggerFactory => new LoggerFactory().AddConsole(LogLevel.Trace);

        // Declare DBSets
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                //.UseSqlite("filename=_modelApp.db")
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(LoggerFactory);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
        }
    }

    public class Blog
    {
        public int Id { get; set; }
    }
}
```

**Comment by maumar** [comment] 2019-10-07 23:14
dupe of #12233

**Closed** 2022-10-16 13:22 UTC
Labels: regression, customer-reported
