### ISSUE TITLE
EF Core migrations tries to drop table named after view

### ISSUE THREAD

**Issue by CaringDev** [dotnet/efcore#23567] opened 2020-12-03 17:50 UTC
### Observed behavior (regression from 3.1.x)
Mapping [a type to a view](https://github.com/bbvch/EfMigrations/blob/9cb7bd8a85782f7b36d1aa3e82f3078e46175b1f/MyDbContext.cs#L18) generates [an entity in migrations](https://github.com/bbvch/EfMigrations/blob/9cb7bd8a85782f7b36d1aa3e82f3078e46175b1f/Migrations/20201203173946_First.Designer.cs#L23). Subsequent migrations [try to drop a table named after entity](https://github.com/bbvch/EfMigrations/blob/9cb7bd8a85782f7b36d1aa3e82f3078e46175b1f/Migrations/20201203174018_Second.cs#L9).

### Expected behavior
Views do not generate entities, no attempt to drop non-existent table.

### Include verbose output

```
$ dotnet ef migrations add First --verbose
Using project 'C:\Dev\EfMigrations\EfMigrations.csproj'.
Using startup project 'C:\Dev\EfMigrations\EfMigrations.csproj'.
Writing 'C:\Dev\EfMigrations\obj\EfMigrations.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\raphaelschweizer\AppData\Local\Temp\tmp1278.tmp /verbosity:quiet /nologo C:\Dev\EfMigrations\EfMigrations.csproj
Writing 'C:\Dev\EfMigrations\obj\EfMigrations.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\raphaelschweizer\AppData\Local\Temp\tmp178A.tmp /verbosity:quiet /nologo C:\Dev\EfMigrations\EfMigrations.csproj
Build started...
dotnet build C:\Dev\EfMigrations\EfMigrations.csproj /verbosity:quiet /nologo

Build succeeded.        
    0 Warning(s)        
    0 Error(s)

Time Elapsed 00:00:02.10
Build succeeded.
dotnet exec --depsfile C:\Dev\EfMigrations\bin\Debug\net5.0\EfMigrations.deps.json --additionalprobingpath C:\Users\raphaelschweizer\.nuget\packages --runtimeconfig C:\Dev\EfMigrations\bin\Debug\net5.0\EfMigrations.runtimeconfig.json C:\Users\raphaelschweizer\.nuget\packages\dotnet-ef\5.0.0\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll migrations add First --assembly C:\Dev\EfMigrations\bin\Debug\net5.0\EfMigrations.dll --startup-assembly C:\Dev\EfMigrations\bin\Debug\net5.0\EfMigrations.dll --project-dir C:\Dev\EfMigrations\ --language C# --working-dir C:\Dev\EfMigrations --verbose --root-namespace EfMigrations
Using assembly 'EfMigrations'.
Using startup assembly 'EfMigrations'.
Using application base 'C:\Dev\EfMigrations\bin\Debug\net5.0'.
Using working directory 'C:\Dev\EfMigrations'.
Using root namespace 'EfMigrations'.
Using project directory 'C:\Dev\EfMigrations\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'MyContextFactory'.
Found DbContext 'MyDbContext'.
Finding application service provider in assembly 'EfMigrations'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'MyContextFactory'.
Using context 'MyDbContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'EfMigrations'...
Finding design-time services referenced by assembly 'EfMigrations'...
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'EfMigrations'...
No design-time services were found.
DetectChanges starting for 'MyDbContext'.
DetectChanges completed for 'MyDbContext'.
Writing migration to 'C:\Dev\EfMigrations\Migrations\20201203174828_First.cs'.
Writing model snapshot to 'C:\Dev\EfMigrations\Migrations\MyDbContextModelSnapshot.cs'.
'MyDbContext' disposed.
Done. To undo this action, use 'ef migrations remove'
```

```
$ dotnet ef migrations add Second --verbose
Using project 'C:\Dev\EfMigrations\EfMigrations.csproj'.
Using startup project 'C:\Dev\EfMigrations\EfMigrations.csproj'.
Writing 'C:\Dev\EfMigrations\obj\EfMigrations.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\raphaelschweizer\AppData\Local\Temp\tmpF3A1.tmp /verbosity:quiet /nologo C:\Dev\EfMigrations\EfMigrations.csproj
Writing 'C:\Dev\EfMigrations\obj\EfMigrations.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\raphaelschweizer\AppData\Local\Temp\tmpF835.tmp /verbosity:quiet /nologo C:\Dev\EfMigrations\EfMigrations.csproj
Build started...
dotnet build C:\Dev\EfMigrations\EfMigrations.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.06
Build succeeded.
dotnet exec --depsfile C:\Dev\EfMigrations\bin\Debug\net5.0\EfMigrations.deps.json --additionalprobingpath C:\Users\raphaelschweizer\.nuget\packages --runtimeconfig C:\Dev\EfMigrations\bin\Debug\net5.0\EfMigrations.runtimeconfig.json C:\Users\raphaelschweizer\.nuget\packages\dotnet-ef\5.0.0\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll migrations add Second --assembly C:\Dev\EfMigrations\bin\Debug\net5.0\EfMigrations.dll 
--startup-assembly C:\Dev\EfMigrations\bin\Debug\net5.0\EfMigrations.dll --project-dir C:\Dev\EfMigrations\ --language C# --working-dir C:\Dev\EfMigrations --verbose --root-namespace EfMigrations
Using assembly 'EfMigrations'.
Using startup assembly 'EfMigrations'.
Using application base 'C:\Dev\EfMigrations\bin\Debug\net5.0'.
Using working directory 'C:\Dev\EfMigrations'.
Using root namespace 'EfMigrations'.
Using project directory 'C:\Dev\EfMigrations\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'MyContextFactory'.
Found DbContext 'MyDbContext'.
Finding application service provider in assembly 'EfMigrations'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'MyContextFactory'.
Using context 'MyDbContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'EfMigrations'...
Finding design-time services referenced by assembly 'EfMigrations'...
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'EfMigrations'...
No design-time services were found.
DetectChanges starting for 'MyDbContext'.
DetectChanges completed for 'MyDbContext'.
DetectChanges starting for 'MyDbContext'.
DetectChanges completed for 'MyDbContext'.
DetectChanges starting for 'MyDbContext'.
DetectChanges completed for 'MyDbContext'.
DetectChanges starting for 'MyDbContext'.
DetectChanges completed for 'MyDbContext'.
An operation was scaffolded that may result in the loss of data. Please review the migration for accuracy.
Writing migration to 'C:\Dev\EfMigrations\Migrations\20201203174926_Second.cs'.
Writing model snapshot to 'C:\Dev\EfMigrations\Migrations\MyDbContextModelSnapshot.cs'.
'MyDbContext' disposed.
Done. To undo this action, use 'ef migrations remove'
```

### Include provider and version information

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: netcoreapp3.1 / net5.0
Operating system: Win 10 20H2
IDE: console

**Comment by ajcvickers** [comment] 2020-12-03 18:22
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/2890

**Comment by CaringDev** [comment] 2020-12-03 18:34
@ajcvickers thanks 🙏 I did search the issues but forgot the Docs 🤷‍♂️
Going to close as this is intended breaking behavior and merely a doc issue.

**Closed** 2022-10-16 19:13 UTC
Labels: customer-reported
