### ISSUE TITLE
Asynchronous projecting entities with child collection properties

### ISSUE THREAD

**Issue by erbatista** [dotnet/efcore#9350] opened 2017-08-07 18:51 UTC
When projecting a result which have a collection property it will deadlock.

```
public class FooModel
{    
    public Guid Id { get; set; }    
    public string Name { get; set; }
    public List<ChildModel> Childs { get; set; }
}

public static async Task<List<FooModel>> ListFooModelAsync()
{
	using (var db = new AppDbContext())
	{
		var foo_items = await db.Foos
			.Include(e => e.Childs)
			.Select(e => new FooModel
			{
				Id = e.Id,            
				Name = e.Name,
				Childs = e.Childs.Select(
					child => new ChildModel { Id = child.Id, Name = child.Name })
					.ToList() //Cause deadlock
			})
			.ToListAsync()
			.ConfigureAwait(false);
		return foo_items;
	}
}

```
By removing ToList(),  the deadlock occurs as soon as I try to use the result, in this case Childs type will be `Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.EnumerableAdapter<ChildModel>`.

**Comment by smitpatel** [comment] 2017-08-07 23:13
dupe of #9128

**Closed** 2022-10-16 11:14 UTC
Labels: closed-duplicate
