### ISSUE TITLE
Including related entities causes performance degradation

### ISSUE THREAD

**Issue by yellfage** [dotnet/efcore#25218] opened 2021-07-07 19:24 UTC
The next LINQ translates into SQL, performance of which degrades depending on the number of Message entities.
Below you can find a test project where you can test this behavior. 

EF Core version: 5.0.7
Database providers: Npgsql.EntityFrameworkCore.PostgreSQL (5.0.7), Pomelo.EntityFrameworkCore.MySql (5.0.1)
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.9

Test project: [EFCore.Issue.zip](https://github.com/dotnet/efcore/files/6782348/EFCore.Issue.zip)

```csharp
builder
    .Entity<Message>()
    .HasIndex(message => new { message.ChatId, message.CreatedAt })
    .HasSortOrder(SortOrder.Ascending, SortOrder.Descending);
```

```csharp
IList<Chat> = context.Chats
    .Include(chat => chat.Messages
        .OrderByDescending(message => message.CreatedAt)
        .Take(1))
    .Where(chat => chat.Id == 1)
    .ToList();
```
Generated SQL by EF Core:
```sql
SELECT c."Id",
       t0."Id",
       t0."ChatId",
       t0."CreatedAt"
FROM "Chats" AS c
LEFT JOIN
  (SELECT t."Id",
          t."ChatId",
          t."CreatedAt"
   FROM
     (SELECT m."Id",
             m."ChatId",
             m."CreatedAt",
             ROW_NUMBER() OVER(PARTITION BY m."ChatId"
                               ORDER BY m."CreatedAt" DESC) AS ROW
      FROM "Messages" AS m) AS t
   WHERE t.row <= 1 ) AS t0 ON c."Id" = t0."ChatId"
WHERE c."Id" = 1
ORDER BY c."Id",
         t0."ChatId",
         t0."CreatedAt" DESC,
         t0."Id"
```
100,000 messages:
```
"Sort  (cost=11682.09..11765.42 rows=33333 width=20) (actual time=52.309..52.310 rows=1 loops=1)"
"  Sort Key: t.""ChatId"", t.""CreatedAt"" DESC, t.""Id"""
"  Sort Method: quicksort  Memory: 25kB"
"  ->  Nested Loop Left Join  (cost=0.57..9178.00 rows=33333 width=20) (actual time=0.036..52.304 rows=1 loops=1)"
"        Join Filter: (c.""Id"" = t.""ChatId"")"
"        ->  Index Only Scan using ""PK_Chats"" on ""Chats"" c  (cost=0.15..8.17 rows=1 width=4) (actual time=0.014..0.015 rows=1 loops=1)"
"              Index Cond: (""Id"" = 1)"
"              Heap Fetches: 1"
"        ->  Subquery Scan on t  (cost=0.42..8753.17 rows=33333 width=16) (actual time=0.021..52.286 rows=1 loops=1)"
"              Filter: (t.""row"" <= 1)"
"              Rows Removed by Filter: 99999"
"              ->  WindowAgg  (cost=0.42..7503.17 rows=100000 width=24) (actual time=0.020..48.532 rows=100000 loops=1)"
"                    ->  Index Scan using ""IX_Messages_ChatId_CreatedAt"" on ""Messages"" m  (cost=0.42..5753.17 rows=100000 width=16) (actual time=0.013..16.468 rows=100000 loops=1)"
"                          Index Cond: (""ChatId"" = 1)"
"Planning Time: 0.146 ms"
"Execution Time: 52.336 ms"
```
1,000,000 messages:
```
"Sort  (cost=135280.22..136113.55 rows=333333 width=20) (actual time=503.943..503.944 rows=1 loops=1)"
"  Sort Key: t.""ChatId"", t.""CreatedAt"" DESC, t.""Id"""
"  Sort Method: quicksort  Memory: 25kB"
"  ->  Nested Loop Left Join  (cost=0.58..97863.57 rows=333333 width=20) (actual time=0.026..503.940 rows=1 loops=1)"
"        Join Filter: (c.""Id"" = t.""ChatId"")"
"        ->  Index Only Scan using ""PK_Chats"" on ""Chats"" c  (cost=0.15..8.17 rows=1 width=4) (actual time=0.010..0.011 rows=1 loops=1)"
"              Index Cond: (""Id"" = 1)"
"              Heap Fetches: 1"
"        ->  Subquery Scan on t  (cost=0.42..93688.74 rows=333333 width=16) (actual time=0.015..503.926 rows=1 loops=1)"
"              Filter: (t.""row"" <= 1)"
"              Rows Removed by Filter: 999999"
"              ->  WindowAgg  (cost=0.42..81188.74 rows=1000000 width=24) (actual time=0.014..465.909 rows=1000000 loops=1)"
"                    ->  Index Scan using ""IX_Messages_ChatId_CreatedAt"" on ""Messages"" m  (cost=0.42..63688.74 rows=1000000 width=16) (actual time=0.009..154.595 rows=1000000 loops=1)"
"                          Index Cond: (""ChatId"" = 1)"
"Planning Time: 0.128 ms"
"Execution Time: 503.968 ms"
```

A much more efficient SQL might look like this:
```sql
SELECT c."Id",
       t0."Id",
       t0."ChatId",
       t0."CreatedAt"
FROM "Chats" AS c
LEFT JOIN LATERAL -- Or CROSS JOIN LATERAL
  (SELECT m."Id",
          m."ChatId",
          m."CreatedAt"
   FROM "Messages" AS m
   WHERE m."ChatId" = c."Id"
   ORDER BY m."CreatedAt" DESC
   LIMIT 1) AS t0 ON c."Id" = t0."ChatId"
WHERE c."Id" = 1
ORDER BY c."Id",
         t0."ChatId",
         t0."CreatedAt" DESC,
         t0."Id"
```
100,000 messages:
```
"Sort  (cost=8.68..8.69 rows=1 width=20) (actual time=0.025..0.025 rows=1 loops=1)"
"  Sort Key: t0.""ChatId"", t0.""CreatedAt"" DESC, t0.""Id"""
"  Sort Method: quicksort  Memory: 25kB"
"  ->  Nested Loop Left Join  (cost=0.57..8.67 rows=1 width=20) (actual time=0.019..0.020 rows=1 loops=1)"
"        ->  Index Only Scan using ""PK_Chats"" on ""Chats"" c  (cost=0.15..8.17 rows=1 width=4) (actual time=0.009..0.010 rows=1 loops=1)"
"              Index Cond: (""Id"" = 1)"
"              Heap Fetches: 1"
"        ->  Subquery Scan on t0  (cost=0.42..0.49 rows=1 width=16) (actual time=0.009..0.009 rows=1 loops=1)"
"              Filter: ((t0.""ChatId"" = 1) AND (c.""Id"" = t0.""ChatId""))"
"              ->  Limit  (cost=0.42..0.48 rows=1 width=16) (actual time=0.008..0.008 rows=1 loops=1)"
"                    ->  Index Scan using ""IX_Messages_ChatId_CreatedAt"" on ""Messages"" m  (cost=0.42..5753.17 rows=100000 width=16) (actual time=0.007..0.007 rows=1 loops=1)"
"                          Index Cond: (""ChatId"" = c.""Id"")"
"Planning Time: 0.121 ms"
"Execution Time: 0.044 ms"
```
1,000,000 messages:
```
"Sort  (cost=8.70..8.70 rows=1 width=20) (actual time=0.038..0.039 rows=1 loops=1)"
"  Sort Key: t0.""ChatId"", t0.""CreatedAt"" DESC, t0.""Id"""
"  Sort Method: quicksort  Memory: 25kB"
"  ->  Nested Loop Left Join  (cost=0.58..8.69 rows=1 width=20) (actual time=0.029..0.030 rows=1 loops=1)"
"        ->  Index Only Scan using ""PK_Chats"" on ""Chats"" c  (cost=0.15..8.17 rows=1 width=4) (actual time=0.013..0.013 rows=1 loops=1)"
"              Index Cond: (""Id"" = 1)"
"              Heap Fetches: 1"
"        ->  Subquery Scan on t0  (cost=0.42..0.50 rows=1 width=16) (actual time=0.015..0.015 rows=1 loops=1)"
"              Filter: ((t0.""ChatId"" = 1) AND (c.""Id"" = t0.""ChatId""))"
"              ->  Limit  (cost=0.42..0.49 rows=1 width=16) (actual time=0.014..0.014 rows=1 loops=1)"
"                    ->  Index Scan using ""IX_Messages_ChatId_CreatedAt"" on ""Messages"" m  (cost=0.42..63688.74 rows=1000000 width=16) (actual time=0.013..0.013 rows=1 loops=1)"
"                          Index Cond: (""ChatId"" = c.""Id"")"
"Planning Time: 0.122 ms"
"Execution Time: 0.057 ms"
```

**Comment by AndriySvyryd** [comment] 2021-07-09 17:13
@smitpatel cc

**Comment by smitpatel** [comment] 2021-07-09 17:20
Duplicate of #17936

**Closed** 2022-10-16 19:39 UTC
Labels: customer-reported
