### ISSUE TITLE
ToSqlQuery method not working in 6.0.0

### ISSUE THREAD

**Issue by Quynn** [dotnet/efcore#26685] opened 2021-11-15 07:21 UTC
Moving from 6.0.0-rc.2.21480.5 to 6.0.0 the extension method ToSqlQuery stopped working when used for mapping Database entities

**Comment by ajcvickers** [comment] 2021-11-15 08:14
@Quynn Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by adil-portable** [comment] 2021-11-16 03:40
Could you please share your project or code here so that I can have a look and try to solve the issue?

**Comment by Quynn** [comment] 2021-11-19 11:03
To reproduce the error just change the version in the .csproj file

[EFIssue.zip](https://github.com/dotnet/efcore/files/7569747/EFIssue.zip)

**Comment by ajcvickers** [comment] 2021-11-19 11:20
Duplicate of #26629.

**Closed** 2022-10-16 20:14 UTC
Labels: closed-duplicate, customer-reported
