### ISSUE TITLE
Make a rollback argument for migrations that rollback last migration

### ISSUE THREAD

**Issue by jepzen** [dotnet/efcore#33834] opened 2024-05-29 07:04 UTC
When you have to rollback a migration you need to run update <migration_name>. It takes time to find the name of that file.

It would super nice to have an argument like

`dotnet-ef` migrations rollback`

that would rollback last migration applied. Then you dont have to find the filename of that migration and copy paste it into your console

**Comment by roji** [comment] 2024-05-30 02:19
Duplicate of #26155

**Closed** 2024-05-30 02:19 UTC
Labels: customer-reported, area-migrations
