### ISSUE TITLE
Include not fetching other table

### ISSUE THREAD

**Issue by p2atran** [dotnet/efcore#12112] opened 2018-05-23 01:57 UTC
```
Exception message: System.NullReferenceException: Object reference not set to an instance of an object.
```

### Steps to reproduce
I'm not sure if its related to https://github.com/aspnet/EntityFrameworkCore/issues/9038,
but nothing changed in this file from my .net core 1.1 to .net core 2 migration.

When my query below calls the p.CanUserRead, the Team method is null.

```C#
public class TeamEvent :
{
        [ForeignKey("TeamId")]
        public Team Team { get; set; }
        public string TeamId { get; set; }

        public override bool CanUserRead(string userId)
        {
            return Team.CanUserRead(userId); // Team is null when called
        }
}

```

```C#
var found = await _ctx.Practices
                .Include(p => p.Participation)
                    .ThenInclude(p => p.Player)
                        .ThenInclude(p => p.User)
                .Include(m => m.Team)
                    .ThenInclude(t => t.Club)
                .Include(m => m.Team)
                    .ThenInclude(t => t.Players)
                        .ThenInclude(pt => pt.Player)
                            .ThenInclude(p => p.User)               
                .SingleOrDefaultAsync(p => p.Slug == slug && p.Team.Slug == teamSlug && (p.CanUserRead(User.GetUserId()) || isAdmin));
```

### Further technical details
EF Core version: 2.0.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: macOS 10.13.4
IDE: Visual Studio Code

**Comment by GertArnold** [comment] 2018-05-23 07:42
`Team` is not a method. What exactly is null? Also, you're querying `Practices`. That _seems_ to be a `DbSet<TeamEvent>`, but that's not clear.
In other words: you should include all code that is necessary to reproduce the issue. Also, including the stack trace of the exception would help.

**Comment by smitpatel** [comment] 2018-05-23 17:00
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by p2atran** [comment] 2018-05-23 17:32
Yeah let me revert some attempted work arounds to reproduce the bug and I'll post the stack trace. 
Practice only has two more properties. The issue is that when linq calls ```p.CanUserRead()``` It  goes to the TeamEvent class and tries to call ```Team.CanUserRead()```. However, Team is null at this point, so its actually doing ```null.CanUserRead()``` which gives the null exception.

The query I posted above includes team, so I'm not sure why it would be null. If it separate the above query and use the following to preload, then team isn't null.
```
.Include(m => m.Team)
                    .ThenInclude(t => t.Players)
                        .ThenInclude(pt => pt.Player)
                            .ThenInclude(p => p.User) 
```

```
  var preloadTeam = _ctx.Pratices..Include(m => m.Team)
                    .ThenInclude(t => t.Players)
                        .ThenInclude(pt => pt.Player)
                            .ThenInclude(p => p.User) 
                      .ToList();

// this query will now work after the preload
var found = await _ctx.Practices
                .Include(p => p.Participation)
                    .ThenInclude(p => p.Player)
                        .ThenInclude(p => p.User)
                .Include(m => m.Team)
                    .ThenInclude(t => t.Club)
                .Include(m => m.Team)
                    .ThenInclude(t => t.Players)
                        .ThenInclude(pt => pt.Player)
                            .ThenInclude(p => p.User)               
                .SingleOrDefaultAsync(p => p.Slug == slug && p.Team.Slug == teamSlug && (p.CanUserRead(User.GetUserId()) || isAdmin));

```
```
public class Practice : TeamEvent
{
        public bool IsFinalized { get; set; }
        public bool IsEvenOnly { get; set; }
}

```

**Comment by GertArnold** [comment] 2018-05-24 12:37
That's not "steps to reproduce". We should be able to paste your code into a simple VS project (e.g. Console application) and run it. Also, I think the common practice here is to edit your original post in order to improve it.

**Comment by smitpatel** [comment] 2018-05-24 16:28
Duplicate of #10471

**Comment by smitpatel** [comment] 2018-05-24 16:29
Your query is doing client eval in `SingleOrDefaultAsync` function. EF core does not give you included navigations when processing the client eval code. The linked issue has more details.

**Closed** 2022-10-16 12:26 UTC
Labels: customer-reported
