### ISSUE TITLE
Global Query Filters do not work with EF Preview 6

### ISSUE THREAD

**Issue by haacked** [dotnet/efcore#16315] opened 2019-06-27 23:32 UTC
In a simple project using Global Query Filters registered as such:

```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);

    modelBuilder.Entity<Movie>().HasQueryFilter(m => m.Genre == "Comedy");
}
```

Query filtering works fine with version 2.2.4 of the required packages.

```xml
<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SQLite" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3" />
  </ItemGroup>
```

If I take that exact same code, and simply update the package references like so:

```xml
<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.0-preview6.19304.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SQLite" Version="3.0.0-preview6.19304.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0-preview6.19304.10" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0-preview6-19319-03" />
</ItemGroup>
```

...it stops working. In examining the queries, the filter is never applied when EF Core queries the database. It seems to completely ignore the filter.

### Further technical details
Database Provider: Microsoft.EntityFrameworkCore.SqlLite
Operating system: Mac OS X

### Repros

* This is a working demo: [aspnetcoreapp-works.zip](https://github.com/aspnet/EntityFrameworkCore/files/3336972/aspnetcoreapp-works.zip)
* And this is a failing demo: [aspnetcoreapp-fails.zip](https://github.com/aspnet/EntityFrameworkCore/files/3336973/aspnetcoreapp-fails.zip)

Navigate to the Movies page. In the working demo, you should only see two movies, both are comedies. In the failing demo, you see all three movies.

**Comment by ajcvickers** [comment] 2019-06-28 19:38
@smitpatel to de-dupe.

**Comment by smitpatel** [comment] 2019-06-28 19:57
Duplicate of #15264

**Closed** 2022-10-16 14:28 UTC
Labels: customer-reported
