### ISSUE TITLE
Disable automatic 'order by' in query to decrease execution time

### ISSUE THREAD

**Issue by danisoft2** [dotnet/efcore#27746] opened 2022-04-04 09:00 UTC
There are cases that we dont want to use paging and we dont want to get order by in the query as is slows down the query,

**Comment by roji** [comment] 2022-04-04 09:03
EF Core sometimes adds ORDER BY when it's necessary for the proper loading of related entities, see #19571.

If you believe you're getting an ORDER BY which doesn't make sense, please post a runnable code sample with the model and query.

**Comment by ajcvickers** [comment] 2022-04-19 12:24
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:30 UTC
Labels: closed-no-further-action, customer-reported
