### ISSUE TITLE
Allow the change tracker to track arbitrary objects to trigger changes in defined entities.

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/efcore#23790] opened 2021-01-01 15:17 UTC
_This is in followup to https://github.com/dotnet/efcore/issues/23789._

---

### Problem

I have objects that I save to a JSON column using logic that I manage myself as part of my `DbContext`.  The serialization and deserialization work wonderfully and Entity Framework provides all the tools necessary to perform them.  Unfortunately, what EF forgot to include as part of this flexibility is a non-invasive means of preserving or supplementing automatic change detection when doing updates.

_(Alternatively, if such a mechanism exists, the docs for it are difficult to discover! 😉 )_

In order to have changes to my object trigger an update, I have to either trick EF into thinking the property has changed, or manually tell the change tracker that the containing entity is dirty.

Both techniques expose my procedural logic to idiosyncrasies of Entity Framework which should otherwise be kept under the hood or contained as configuration code in my `DbContext`. My application code should be able to work with an object graph without having to perform operations to placate EF.

> note: I do not consider `INotifyPropertyChanged` an acceptable solution as it causes a run of one-off code and pollutes my domain model more than simply doing the operations in the previous paragraph. It's also difficult to generalize without taking on risky domain model OO antipatterns.

### Suggestion

I would love to see the `DbContext` offer something along the lines of:

```csharp
modelBuilder
    .Entity<MyContainingEntity>()
    .Property((myContainingEntity) => myContainingEntity.SerializedProperty)
    .ChangesInvalidateParent();
```

(Alternate names for the method could be: `TrackAgainstParent`, `InvalidatesParent`, etc...)

What this would effectively do is tell Entity Framework to use its change tracker _behaviour_ on `SerializedProperty`, but instead of trying to dirty the state of a model corresponding to `SerializedProperty`, it would dirty the state of the parent.  In the case of my example, it would be `MyContainingEntity`.

The nice part of this approach is that Entity Framework at its core already has code to watch objects for changes to their properties. EF just needs to allow users to tap into this via `ModelBuilder` configuration.

**Comment by ajcvickers** [comment] 2021-01-01 15:21
This seems to be a duplicate of #23789. Regardless of the comments from the community on that issue, it seems like this just needs a value comparer.

**Comment by atrauzzi** [comment] 2021-01-01 18:06
It's inspired by it, but I don't think 100%.  See [this comment](https://github.com/dotnet/efcore/issues/23789#issuecomment-753358408) for more details on how this feature request differs.

**Comment by ajcvickers** [comment] 2021-01-01 18:20
@atrauzzi The fundamental problem here is that for a reference type the application needs to give EF Core some information on how to do comparisons, since the .NET default of reference quality is not appropriate. This is what value comparers allow, as described in the documentation I linked. Once EF can do this, then the property is treated as any other property, with the same change tracking behavior. The application should not need to do anything special other than tell EF Core in the EF Core configuration how to deal with the type.

**Comment by atrauzzi** [comment] 2021-01-01 18:33
But then how is EF doing change tracking for regular entities?  I don't tell it anything about those reference types and it's able to watch properties.

I think there's some confusion here: I'm not asking for EF to notice when the entity's reference changes.  I'm asking for the change tracker to [support watching entities that are just regular objects](https://github.com/dotnet/efcore/issues/23789#issuecomment-753360978).  Just like it does already.

The difference is that those changes won't be read by EF and turned into DB statements.  They'll just be there for say, something like an `IChangeDetector` to query and report to EF that a _parent_ entity is dirty.  Which again as item `2.` in my list in the other ticket, could even be sugared up a bit.  But `1.` and the ability to query the change tracker is enough even...

---

> p.s:  Feel free to continue all discussion here, I'd rather close the other ticket and continue here.

**Comment by ajcvickers** [comment] 2021-01-01 18:35
@atrauzzi Again, this is what value converters and comparers do.

**Comment by atrauzzi** [comment] 2021-01-01 18:40
In response to https://github.com/dotnet/efcore/issues/23789#issuecomment-753361785 and _"Again, this is what value converters and comparers do."_

I know what value comparers do, and I'm not questioning that, let's consider that established and that we both agree on it 100%.  

Move in a level now.

The specific logic that the value comparer performs is what I'm talking about here.  When I look at the task of writing a value comparer for my _reference type_, it looks 1:1 identical to what the EF change tracker is capable of doing.  Like, to the extent that I feel guilty of inner-platform'ing. :laughing: 

What would be really amazing is if I could just have objects registered in the EF change tracker that don't result in it trying to generate DB statements, but that it can be queried to say whether the object has changed or not.  Literally identically to what it already does for normal EF functionality.

---

If I write my own value comparer, what would be great is if I could just reach into the change tracker and say _"yo, look, I know I told you about this object earlier to watch, and you told me you're not going to generate any DB statements for it.....but has it changed?"_

(And then subsequently of course: _"Oh, it has?  Great, my value comparer is going to say the value has changed then."_)

**Comment by ajcvickers** [comment] 2021-01-01 18:43
@atrauzzi Consider this entity type:

```C#
public class Blog
{
    public int Id { get; set; }
    public string Title { get; set; }
    public DateTime UpdatedOn { get; set; }
}
```

EF can detect changes made to this type because it knows how to compare an int to an int, a string to a string, and a DateTime to a DateTime. It also doesn't need any specific snapshot mechanism because these types are either value types or immutable.

If you now add a property of a type that EF doesn't understand:

```C#
public class Blog
{
    public int Id { get; set; }
    public string Title { get; set; }
    public DateTime UpdatedOn { get; set; }
    public MyType Foo  { get; set; }
}

public class MyType
{
    public string Something  { get; set; }
    public string SomethingElse  { get; set; }
}
```

Now EF can't detect changes to the Blog entity because it doesn't know how to compare MyType to MyType to see if it has changed. (It also doesn't know how to snapshot the instance, which is needed because the type is mutable, and it doesn't know how to create a hashcode.)

**Comment by atrauzzi** [comment] 2021-01-01 18:46
@ajcvickers - I feel like you're stuck on something I've already acknowledged.  I also can probably infer that you've explained this 100s of times to other people and feel like I'm confused in a similar way to them.  I'm not going in that direction, promise.

Let me repeat: I'm not trying to have EF do what you just described.  I'm trying to facilitate a way to have the change tracker's logic for noticing when the **subordinate object**'s own properties have changed.  **Not the property of the actual entity itself**.

**Comment by ajcvickers** [comment] 2021-01-01 18:50
@atrauzzi I'll discuss with the team, but I'm pretty sure that's outside the scope of EF Core.

**Comment by atrauzzi** [comment] 2021-01-01 19:00
:pray: - If it helps the conversation at all, it might be better to emphasize that the ability to use the change tracker for this purpose is specifically to facilitate allowing better value comparers.  My opinion there is that this is actually something that's missing for EF quality of life.  It's also to help guard against people who adopt EF from being tempted into inner platforms or any other performance risks.

Here's an imaginary code example that might help as well...

```csharp
public class MyEntity
{
    public Guid Id { get; set;}
    public NotAnEntity NotAnEntity { get; set; }
}

public class NotAnEntity
{
    public string SomeWords { get; set; }
}

public class MyDbContext : DbContext
{
    public DbSet<MyEntity> MyEntities { get; set; }
}

// ...elsewhere in my code

myDbContext.Add(new MyEntity()); // Fine, yup, no problems.
myDbContext.Add(new NotAnEntity()); // Today, this will blow up, but hang on...
```

*Waves magic 4d wand...* 🪄

```csharp
myDbContext.Add(new NotAnEntity()); // It worked!

// Now, elsewhere in my code after lots of complex logic.

await myDbContext.SaveAsync(); // No query will be generated for `NotAnEntity` no matter what.
```

That said, inside of my value comparer and before the save, maybe I can do this:

```csharp
ChangeTracker
    .Entries<NotAnEntity>()
    .Where((entry) => entry.State == EntityState.Modified)
    .AnExtensionMethodThatDirtiesMyEntityEntries(ChangeTracker);
```

**Comment by anranruye** [comment] 2021-01-01 19:19
@atrauzzi  Please let me interrupt.

I don't think it's as simple as you said. Tracking an entity object and tracking objects inside an entity property has a main difference. That is, these changes of inside objects should feedback to the ancestor object. Thus the changes graph will 
be a tree structure rather than a plane structure(which is current implementation).  It can be a big project to change current behavior.

Also that is not ideal enough. Consider we have the following code:
```C#
var entity = db.Entities.First();
entity.PropertyMapToJson = new entity.PropertyMapToJson.Clone();
db.SaveChanges();
``` 
If we use change tracker to track inside changes, the `PropertyMapToJson` property will be marked as modified because the reference is changed. But in fact it is not changed because the values are not changed. Value comparer is better choice to compare the values.

**Comment by anranruye** [comment] 2021-01-01 19:45
@atrauzzi @ajcvickers 
I think there is another good choice if we don't use value comparer. EF Core only need to snapshot the provider value(original value from the database, the json string in #23789 scenario), and compare it with the new value. However, this may cause performance problem. 

I think use change tracker to monitor inside changes of an property is unnecessary and not a good choice. Unless ef core should notice the change immediately once the value is changed, which is now depend on INotifyPropertyChanged. It is possible to emit an derived entity type which implement INotifyPropertyChanged(which is like the lazy-loading does). I will open a new process to complain this.

**Comment by ajcvickers** [comment] 2021-01-05 19:16
@atrauzzi We discussed this as a team, but we don't believe it is something that we want to add to EF Core. We believe it adds extra complexity without greatly improving capabilities.

**Comment by atrauzzi** [comment] 2021-01-06 23:40
Not sure that makes sense.  Is this to say it's better for people to waste resources NIH'ing their own change tracking when EF has a perfectly good one built in already?

**Closed** 2022-10-16 19:17 UTC
Labels: closed-out-of-scope, customer-reported
