### ISSUE TITLE
Migrations: Display message on success

### ISSUE THREAD

**Issue by suhasj** [dotnet/efcore#2009] opened 2015-04-09 19:08 UTC
This is more of an experience thing. As a user if I use the Package Manager console to apply migrations, there is no successful message displayed after a successful update to the database. In addition the `apply` command does not have a `--verbose` option that displays all the steps

Repro
- Create starter web application with beta4 packages
- In the Package Manager Console run `dnvm use default` add `dnx` to the path
- run `dnx . ef migration apply` to apply the default migration

Expected:
A success message may be in green color to say that the operation was a success

Actual:
No message

![error](https://cloud.githubusercontent.com/assets/1919946/7074651/0a2304f8-deb1-11e4-97a9-0ca4edfa2013.png)

**Comment by divega** [comment] 2015-04-13 18:59
@bricelam please find if this is a dupe.

**Comment by bricelam** [comment] 2015-04-13 21:52
Dupe of #975

**Closed** 2022-10-16 08:54 UTC
