### ISSUE TITLE
List any inside queryable Any or Count

### ISSUE THREAD

**Issue by sourcenew** [dotnet/efcore#17441] opened 2019-08-27 08:07 UTC
hello

after execute:
```
var query = Context.Requests.AsQueryable();
            query = query.Include(f => f.Datas);
            query = query.Where(f => f.Datas.Count(x => x.GroupElementId == item.elementId && item.value.Any(v => v == x.Value)) > 0);
```

in result list: item.Data return null!

sorry i can't speak English. but after many test i guess this is entity bug

**Comment by sourcenew** [comment] 2019-08-27 08:08
**item.value is list
item.elementId is guid

item is my function parameter**

**Comment by ajcvickers** [comment] 2019-09-06 16:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by sourcenew** [comment] 2019-09-08 05:53
there is problem in two Any, one inside another, then related tables data not loaded correctly.

like:var result= Context.TableA.Include(TableB).Include(TableC).Any(f=>F.TableB.Any(g=>....)).ToList()

then most of result[index].TableC not have data (empty) but exactly that codes if i add a where condition work correctly

**Comment by ajcvickers** [comment] 2019-09-08 21:21
@sourcenew Please post a _runnable_ project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by sourcenew** [comment] 2019-09-09 05:47
off course, but this may take a some time. i will prepare something for you

**Closed** 2022-10-16 14:38 UTC
Labels: closed-could-not-reproduce, customer-reported
