### ISSUE TITLE
Calling the .Find() method does not use global defined query filters

### ISSUE THREAD

**Issue by ageisen2000** [dotnet/efcore#13018] opened 2018-08-15 20:39 UTC
When using a global query filter calling the Entity.Find() method does not seem to use the defined filters.

### Steps to reproduce
- Add a global query filter. In our case we are doing soft deletes with a GUID DeleteToken.
- Delete the entity using .Remove(id) and then call SaveChanges
- Use Context.Find(id) and your entity will be displayed even though we have a global query filter that should have filtered to only DeleteToken == null entries.

Using .SingleOrDefault(entity => entity.id == id) works as expected and does not return the deleted entity.

### Further technical details
EF Core version: netcoreapp2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8

**Comment by ajcvickers** [comment] 2018-08-15 22:34
Duplicate of #9405

**Closed** 2022-10-16 13:25 UTC
Labels: customer-reported
