### ISSUE TITLE
【SQLite】【EF.Functions.DateDiff】The call is ambiguous between the following methods or properties: MySqlDbFunctionsExtensions & SqlServerDbFunctionsExtensions

### ISSUE THREAD

**Issue by 12343954** [dotnet/efcore#31132] opened 2023-06-25 04:44 UTC
## The call is ambiguous between the following methods or properties: 

'Microsoft.EntityFrameworkCore.MySqlDbFunctionsExtensions.DateDiffMonth(Microsoft.EntityFrameworkCore.DbFunctions, System.DateTime, System.DateTime)' and 
'Microsoft.EntityFrameworkCore.SqlServerDbFunctionsExtensions.DateDiffMonth(Microsoft.EntityFrameworkCore.DbFunctions, System.DateTime, System.DateTime)'

### Include your code

```C#
// using sqlite database context

var wheres = PredicateBuilder.True<DispatchlistEntity>();
if (type == GG.Statistics.Type.Daily)
{
    Expression<Func<DispatchlistEntity, bool>> queries = s => EF.Functions.DateDiffMonth(s.create_time, DateTime.Now) == 1;
    wheres = wheres.AndAlso(queries);
}


var sale_data = from dispatch in _dBContext.GetDbSet<DispatchlistEntity>().AsNoTracking()
                where EF.Functions.DateDiffMonth(dispatch.create_time, DateTime.Now) == 1
                select dispatch;

var list = await _dBContext.GetDbSet<DispatchlistEntity>().AsNoTracking()
                        .Where(p => EF.Functions.DateDiffDay(p.create_time, DateTime.Now) > 0).ToListAsync();

```

### Include provider and version information

<img width="1280" alt="image" src="https://github.com/dotnet/efcore/assets/1804003/77807ae6-2e50-4772-949d-c1fbc9b25af9">

**Comment by roji** [comment] 2023-06-25 07:43
This is by design. If you're using more than one provider in the same program, simply call the extension methods statically:

```c#
where SqlServerDbFunctionsExtensions.DateDiffMonth(default, dispatch.create_time, DateTime.Now) == 1
```

**Comment by 12343954** [comment] 2023-06-25 10:14
@roji thank you for reply! it's helpful, but still not solve it.
there is no "datediff" function in SQLite DB, but in SQL Server DB and MySQL DB.
after research, fortunately, `datetime` type supports compare operation in lambda. i think it can compatible with all three databases at the same time.
It's nothing more than writing two more lines of code. hoped that the usage of `EF.Function.Datediff` will be unified all the database as soon as possible. 😄


<img width="1280" alt="image" src="https://github.com/dotnet/efcore/assets/1804003/bb6830ee-469b-4dfc-812d-2343c6ae6257">

**Comment by roji** [comment] 2023-06-25 11:11
@12343954 we purposefully don't attempt to abstract over databases unless the functionality is universal; the DATEDIFF functionality indeed doesn't exist in SQLite (or PostgreSQL), and every database (unfortunately) has its own mechanism for doing date/time arithmetic. You'll unfortunately have to write different queries for the different databases - that's the reality of the database world.

> after research, fortunately, datetime type supports compare operation in lambda. i think it can compatible with all three databases at the same time.

If you're simply looking to check whether a timestamp is bigger than another, then you indeed don't need DATEDIFF at all and can just use the C# greater-than operator. However, that doesn't work for all uses of DATEDIFF.

**Comment by 12343954** [comment] 2023-06-25 12:16
`datediff` is a very very useful db function, and i like it very much.
.NET is cross-platform and unified. simple things should not be complicated, shouldn't they?
I agree that the real world is not the perfect world, and I'm willing to try to do something until that day comes.

thank you for your reply again, very helpful to me.

**Comment by roji** [comment] 2023-06-25 13:30
As an example why `DATEDIFF` is less than ideal, consider that PostgreSQL supports simple subtraction (with `-`)  between two timestamps, yielding an "interval" type. The interval is a 1st-class PostgreSQL type, from which you can then extract days, months or whatever. This is similar to how in .NET you can subtract two DateTimes, yielding a TimeSpan (which represents an interval). This is better than `DATEDIFF`, which is only there because SQL Server doesn't have the concept of a time interval.

I'm going to go ahead and close this as everything seems to be answered, but feel free to post back here if you have any further questions.

**Closed by roji** 2023-06-25 13:30 UTC
Labels: customer-reported

**Comment by 12343954** [comment] 2023-06-25 13:52
I'm used to SQL Server DB, so my first impression was `datediff`. 
I know that the performance of calculating numbers is much higher than datetime or strings.
you're right, I'll try to use timestamps instead of datetime in the future.
thank you again!
