### ISSUE TITLE
EF Core boolean fields not able to update

### ISSUE THREAD

**Issue by veera-raghavagupta** [dotnet/efcore#23618] opened 2020-12-08 15:40 UTC
When we try to update the boolean fields in .Net Core 3.1 with EF Core. Please help us with the solution

**Comment by ajcvickers** [comment] 2020-12-08 16:40
@veera-raghavagupta Please be more specific. Ideally, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-12-15 16:59
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:14 UTC
Labels: closed-no-further-action, customer-reported
