### ISSUE TITLE
ArgumentNullException thrown during migration script using .NET 5.0.3

### ISSUE THREAD

**Issue by polom01** [dotnet/efcore#24520] opened 2021-03-26 12:00 UTC
When running ef migration script with .NET 5.0.3 or with 5.0.4 ArgumentNullException is thrown with the message "Value cannot be null. (Parameter 'o')".  When i downgrade .net to version 5.0.2 script is generated correctly. I saw that similar issue was in .net 5.0.0 preview 3 and fixed in 5.0.0-preview.5.20227.1 here is a link to issue [ https://github.com/dotnet/efcore/issues/20755]( https://github.com/dotnet/efcore/issues/20755)

`C:\Program Files\dotnet\dotnet.exe" ef migrations script --output C:\myPath\migrationScript.sql --idempotent --project C:\myPath\MyProject.Infrastructure.csproj --context MyProjectContext

Build started...
Build succeeded.
System.ArgumentNullException: Value cannot be null. (Parameter 'o')
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommandListBuilder.Append(String o)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(AlterDatabaseOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__83_5(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateScript(String fromMigration, String toMigration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.ScriptMigration(String fromMigration, String toMigration, MigrationsSqlGenerationOptions options, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigrationImpl(String fromMigration, String toMigration, Boolean idempotent, Boolean noTransactions, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Value cannot be null. (Parameter 'o')
`

EF Core version: 5.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0.4
Operating system: Windows 10

**Comment by bricelam** [comment] 2021-03-26 17:42
Duplicate of #24328

**Comment by bricelam** [comment] 2021-03-26 18:02
The workaround is to keep `modelBuilder.UseCollation()` around until 6.0.0 is released, then you'll be able to remove it. The default database collation for LocalDB is `SQL_Latin1_General_CP1_CI_AS`.

**Closed** 2022-10-16 19:29 UTC
Labels: closed-duplicate, customer-reported
