### ISSUE TITLE
Scaffold-dbcontext: Cannot combine -UseDataBaseNames with pluralizing

### ISSUE THREAD

**Issue by kirodge** [dotnet/efcore#12102] opened 2018-05-22 13:59 UTC
My DB tables use camel case, where some table names starts with a capitalized acronym (i.e. XYTableName)

scaffold-dbcontext by default generates a DBSet property named XytableName (i. e. the acronym is not capitalized) 

I can work around acronym capitalization by adding the "-UseDataBaseNames" switch to scaffold-dbcontext.
This results in a DBSet property named XYTableName (as expected)

But I also want my DBSet properties pluralized. 
For this I use "Bricelam.EntityFrameworkCore.Pluralizer" (1.0.0-rc3).

Without -UseDataBaseNames, property names are pluralized as expected (XytableNames) 
But with the -UseDatabaseNames switch no pluralizing is performed (XYTableName).

How can I get pluralized DBSet property names AND at the same time keep acronyms from the table name capitalized?

### Further technical details
Microsoft.EntityFrameworkCore.Tools (2.1.0-rc1-final)
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer (2.0.3)
IDE: Visual Studio 2017 15.7.2

**Comment by ErikEJ** [comment] 2018-05-22 14:19
+1 - EF Core Power Tools is also affected by this

**Comment by bricelam** [comment] 2018-05-23 20:07
This isn't a duplicate of #12007. The casing differences are irrelevant.

**Comment by ajcvickers** [comment] 2018-05-25 19:35
Triage: Even if UseDatabaseNames is used, navigation properties should still be pluralized if the pluzalizer has been configured. DbSet names are more questionable.

**Comment by TjeuKayim** [comment] 2019-03-13 07:33
I also experienced this issue. My database has a table named `VCenterServers`. I want the C#-class name to be `VCenterServer` (singular).

I used a workaround to override `CandidateNamingService.GenerateCandidateIdentifier()`. https://gist.github.com/TjeuKayim/ed8d28652b5936a2d289c3ff7ebf0e08.

**Comment by ganySA** [comment] 2019-06-25 07:28
Is there a solution to this.

Would it not be prudent to implement the same logic as in EF6 with DB first. I would assume that 99% of use cases would follow that approach.

The challenge here is we can get one thing or the other. Either we have the 'exact' DB names and no pluralization which will also break apps or we have some 'new' approach to converting which follows different logic to what happened in EF 6 DB first.

Is there a solution to this one?

**Comment by joshvote** [comment] 2019-11-27 09:41
We've got a mountain of tables that could benefit from this. It's one of the major pain points for our .NET 4.6 -> .NET Core 3 migration. I'd be happy to contribute a PR if someone would be able to point me in the right direction of where to start.

**Comment by LordBenjamin** [comment] 2019-12-03 17:12
Currently planning LINQ-to-SQL to EF Core migration. The difference in generated names is looking like one of the big pain points.

Looking to maintain existing `DbMetal.exe` behaviour to minimize code changes - i.e.

* Pluralise table names
* Do not modify property (column) casing (unless not valid C# of course)

We cannot yet port the entire system to .NET Core in one go. We can't use the latest EF Core (3+) as this requires `netstandard2.1`, which isn't compatible with .NET 4.7.2.

Is the above possible to do with EF Core 2.2.6? If not, will it be possible to backport a solution or is EF Core 3 too different in this area?

EF Core 2 vs 3 might not be an issue if #18141 is landing soon?

**Comment by paulovila** [comment] 2020-04-04 13:53
Hi @ajcvickers  @bricelam,
is there any progress on this one?
Regards.

**Comment by ajcvickers** [comment] 2020-04-06 15:12
@paulovila As [the milestone indicates](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning), fixing this issue is currently in the plan for 5.0.

**Closed** 2020-08-20 18:05 UTC
Labels: area-scaffolding, closed-fixed, customer-reported, poachable, type-bug
