### ISSUE TITLE
Zero value not store in db. default value saved.

### ISSUE THREAD

**Issue by bkhezry** [dotnet/efcore#15841] opened 2019-05-29 12:20 UTC
I use Aps.net Core 2.1 & EF 2.1.4
for each field from my table in SQL Server that is a number( int, float) when the passed value is zero, the default value of field stored. Another number store correct(like 1, 3 , ...)

```
entity.Property(e => e.AboveGrade)
                    .HasColumnName("aboveGrade")
                    .HasDefaultValueSql("((-1))");
```
aboveGrade type is `int`. when set it to zero, -1 will be store in db.
other numbers store correct.

**Comment by ajcvickers** [comment] 2019-06-03 16:30
Duplicate of #15839 15182

**Closed** 2022-10-16 14:22 UTC
Labels: closed-duplicate, customer-reported
