### ISSUE TITLE
Select_Subquery_Single throws

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#17242] opened 2019-08-18 22:25 UTC
```
Microsoft.EntityFrameworkCore.Query.SimpleQuerySqlServerTest.Select_Subquery_Single

System.ArgumentException : Expression of type 'System.Collections.Generic.List`1[Microsoft.EntityFrameworkCore.TestModels.Northwind.Order]' cannot be used for parameter of type 'System.Linq.IQueryable`1[Microsoft.EntityFrameworkCore.TestModels.Northwind.Order]' of method 'Microsoft.EntityFrameworkCore.TestModels.Northwind.Order First[Order](System.Linq.IQueryable`1[Microsoft.EntityFrameworkCore.TestModels.Northwind.Order])' (Parameter 'arg0')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\Internal\RelationalProjectionBindingExpressionVisitor.cs:line 128
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\Internal\RelationalProjectionBindingExpressionVisitor.cs:line 48
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 733
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\QueryableMethodTranslatingExpressionVisitor.cs:line 287
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 74
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\QueryableMethodTranslatingExpressionVisitor.cs:line 39
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 74
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\QueryCompilationContext.cs:line 68
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async) in C:\aspnet\EntityFrameworkCore\src\EFCore\Storage\Database.cs:line 71
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 106
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0() in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 96
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 84
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 59
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 92
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\EntityQueryProvider.cs:line 79
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator() in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\EntityQueryable`.cs:line 94
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.SimpleQueryTestBase`1.Select_Subquery_Single() in C:\aspnet\EntityFrameworkCore\test\EFCore.Specification.Tests\Query\SimpleQueryTestBase.cs:line 3671
   at Microsoft.EntityFrameworkCore.Query.SimpleQuerySqlServerTest.Select_Subquery_Single() in C:\aspnet\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\Query\SimpleQuerySqlServerTest.cs:line 654
```

**Comment by smitpatel** [comment] 2019-08-19 18:19
Duplicate of #10001

**Comment by smitpatel** [comment] 2019-09-11 00:26
Duplicate of #16314

**Closed** 2022-10-16 14:36 UTC
