### ISSUE TITLE
One-to-many properties not loading correctly

### ISSUE THREAD

**Issue by leontyr** [dotnet/efcore#5429] opened 2016-05-19 21:03 UTC
Ok, this is not a request for lazy loading or eager loading. I simply can't load the data I should.

I am using  "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final"

```
public class Property
{
    public int Id { get; set; }
    public int PropertyTypeId { get; set; }
    public PropertyType PropertyType { get; set; }
}

public class PropertyType
    {       
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
    }
```

If I do 

```
var properties = from x in _context.Properties
                             select x;
return properties;
```

propertyType is null. (Should it not be eager loaded since I didn't use virtual?)

If I do 

```
return properties.Include(p => p.PropertyType);
```

I get first property with the propertyType. However, within the propertyType, there is an empty properties array which causes an infinite loop for the rest of the properties to show. 

The workaround I can do is to add Newtonsoft.Json.ReferenceLoopHandling.Ignore. But this is just a one-to-many relationship. It shouldn't need it, right?

**Comment by divega** [comment] 2016-05-20 00:23
> However, within the propertyType, there is an empty properties array

I cannot repro this using EF Core 1.0 RC2 final and the code your provided. For me the `Properties` collection navigation property is populated correctly and is of type `HashSet<Property>`.

Assuming you are referring to a problem you get when you serialize the graph of objects using Json.NET, this is not the right place to report it :smile:, but FWIW, my limited understanding is that any cycle (even a one-to-many relationship with navigation properties pointing in both directions) can be a problem with JSON serialization. Common approaches to solve it include removing one of the navigation properties, annotating one of them with one of the supported "ignore" attributes and taking advantage of Json.NET's serialization settings, e.g. `ReferenceLoopHandling.Ignore` or `ReferenceLoopHandling.Serialize`.

**Comment by divega** [comment] 2016-05-20 00:25
I am closing this issue because I pretty confident that it is not an actual bug report for EF Core, but feel free to reopen it if I am wrong and please provide any additional repro code (e.g. if you have any code in `OnModelCreating()`).

**Comment by leontyr** [comment] 2016-05-20 10:28
@divega Thanks for the reply.

I agree that it is probably not a bug. The problem is caused by `HashSet<Property>` in PropertyType. I can fix it by using [NotMapped]:
```
 [NotMapped]
 public virtual ICollection<Property> Properties { get; set; }
```
Is that possible for you to clear a couple of things for me?

- Is it by design that in my case PropertyType in Property is not eager loaded even when it's not using virtual?
- Is it by design that virtual Properties in PropertyType is eager loaded (`HashSet<Property>`) when I only used `properties.Include(p => p.PropertyType)` instead of `properties.Include(p => p.PropertyType).ThenInclude(t => t.Properties)`?

**Comment by divega** [comment] 2016-05-20 13:38
> Is it by design that in my case PropertyType in Property is not eager loaded even when it's not using virtual?

Yes. Neither EF Core nor any previous version of EF has ever automatically eager loaded a property. You have to use `Include()`. 

> Is it by design that virtual Properties in PropertyType is eager loaded (HashSet<Property>) when I only used

Yes, it is a graph of objects and EF will normally fix up any relationships between objects that are retrieved. The behavior may change if you use `AsNoTracking()`,  e.g. EF will not fix up navigation properties to objects retrieved by previous queries. 

> The problem is caused by `HashSet<Property>`

If the problem is really the type, you can use a different collection type.

**Comment by leontyr** [comment] 2016-05-20 13:49
Got it. Thanks @divega!

**Closed** 2022-10-16 09:41 UTC
