### ISSUE TITLE
SQLite Database seems to maintain lock on file

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#27139] opened 2022-01-07 17:15 UTC
After accessing a SQLite database using `Microsoft.Data.Sqlite`, I get an error if I try to delete that file.

> The process cannot access the file 'D:\Users\jwood\Documents\HealthLog\JWood.hlg' because it is being used by another process.

Somehow, the library appears to maintain a lock on this file.

I am using a `using` statement for my connections;

    using SqliteConnection conn = new(GetConnectionString());
    conn.Open();

And I'm using a `using` statement for my commands.

    using SqliteCommand command = conn.CreateCommand();

Note: I am not using a `using` statement for my `SqliteParameter`s.

But, later, when I attempt to delete the database. I get an error that it's being used by another process.

I tried calling `GC.Collect()`, but that didn't help.

Does the library maintain a lock on this file somehow? And is there a way to release it?

**Comment by roji** [comment] 2022-01-07 17:21
Duplicate of #26580

**Comment by roji** [comment] 2022-01-07 17:21
This is by design, see breaking change note for 6.0.

The SQLite provider now pools connections, improving connection speed significantly but keeping connections open. You can disable pooling by adding Pooling=false to the connection string or calling SqliteConnection.ClearAllPools() at the point where you want them to be closed.

**Comment by Gigas002** [comment] 2022-02-16 14:59
Sorry, if it's a newbie question, but shouldn't `Dispose()` guarantee, that all object's resources are freed? Why not include `SqliteConnection.ClearPool(this);` call in `SqliteConnection.Dispose()`?

**Closed** 2022-10-16 20:21 UTC
Labels: closed-duplicate, customer-reported

**Comment by lionelconswork** [comment] 2025-02-28 18:03
FYI this Tuesday CERN had an outage&data loss because of this locking issue. It would be appreciated if someone from Microsoft software engineering could fix this.

**Comment by roji** [comment] 2025-02-28 18:53
@lionelconswork I'm happy to discuss this further, but the lock is being maintained by design, as part of the driver's connection pooling feature (which is important for performance reasons) - see the comment just above. As written above, users can disable pooling if they really want to, though that will likely have a negative impact on application performance.
