### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by ejikflame** [dotnet/efcore#19177] opened 2019-12-05 16:08 UTC
```C#
public void FlameParse(string Flame)
		{
			Plugin.Flame.Clear();
			Flame = Flame.Replace("{", "").Replace("}", "").Replace("[", "").Replace("]", "").Replace("\"", "");
			bool flag = Flame.StartsWith("response:id:");
            {
                Flame = Flame.Replace("response:", "");
            }
            string[] array = Flame.Split(new char[]
			{
				','
			});
			for (int i = 0; i < array.Length; i++)
			{
				string[] array2 = array[i].Split(new char[]
				{
					':'
				});
				Plugin.Flame.Add(array2[0], array2[1]);
			}
		}
```
The error in the title of the issue.
Attached a piece of code, help to solve! (

**Comment by ajcvickers** [comment] 2019-12-06 21:09
@ejikflame There doesn't seem to be any use of Entity Framework in your code. If this is an issue with EF, then please post a small, runnable project/solution or complete code listing that reproduces the behavior you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2019-12-13 17:46
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 15:00 UTC
Labels: closed-could-not-reproduce, customer-reported
