### ISSUE TITLE
EF Core migration not working 

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#15829] opened 2019-05-28 17:56 UTC
Hi All,

I a have problem about migration
Migration does not work exactly when I do the code as follows
MigrationHistory table is created but it is empty and tables not created
Can you help me where I do wrong 

EFCore version is 2.2.4

	public class MigrationContext:DbContext
    {
        public MigrationContext()
        {
            
        }

        public DbSet<Audit> Audit { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new AuditConfiguration());
            base.OnModelCreating(modelBuilder);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("data source=R7DNI9M\\SQLEXPRESS;initial catalog=NextCore;User ID=sa;Password=1q2w3e4r;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework");
        }
    }

    public class AuditConfiguration : IEntityTypeConfiguration<Audit>
    {
        public void Configure(EntityTypeBuilder<Audit> builder)
        {
            builder.ToTable(nameof(Audit));
            builder.HasKey(x => x.Id);
            builder.Property(x => x.TableName).HasMaxLength(200);
        }
    }

	class Program
    {
        static void Main(string[] args)
        {

            var context = new MigrationContext();
            context.Database.Migrate();
        }
    }

**Comment by MaximBalaganskiy** [comment] 2019-05-31 00:49
I have the same issue when `OnConfigure` is overridden - migrations are not picked up.

**Comment by smitpatel** [comment] 2019-05-31 00:50
Did you generate migration?

**Comment by MaximBalaganskiy** [comment] 2019-05-31 00:51
Yes

**Comment by smitpatel** [comment] 2019-05-31 00:51
Can you share a repro project?

**Comment by MaximBalaganskiy** [comment] 2019-05-31 01:35
Cannot reproduce. Disregard my comments, it's probably something else in my case.

**Comment by ajcvickers** [comment] 2019-06-03 15:26
@gokhanfeali We have so far not been able to reproduce this. Please post a small, runnable project/solution that reproduces the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-06-10 16:40
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:22 UTC
Labels: closed-could-not-reproduce, customer-reported
