### ISSUE TITLE
EF 5.0.2 to do list - make scaffolding work without manual intervention ("customizations") for all common relationships?

### ISSUE THREAD

**Issue by wvmstr** [dotnet/efcore#23927] opened 2021-01-20 16:10 UTC
Attempted to scaffold a mature SQL Server db, and the result is an endless list of required customizations for basic relations, as well as an endless list of other problems with cryptic error messages and blocking unknown issues.

For those of us with **existing** applications (and existing dbs) this needs to be black box simplicity, no ifs and buts.

An idea is to look at why EF 6.X can do what EF Core 5.0.1 cannot.

Another idea is to "ingest" the work EF 6.X has done when it built the Model in the first place.

**Comment by ajcvickers** [comment] 2021-01-20 16:23
@wvmstr Isn't this a duplicate of #23835?

**Comment by wvmstr** [comment] 2021-01-20 16:52
Well, yes it is.   

But this is the friendly version stating a precise goal (black box simplicity) without the emotions that came with typing the original after wasting a lot of time. 

And this one has the 5.0.2 target as a suggestion.

And there are two ideas!

I am still blocked. @roji has db and two solutions so the issues can be repro-ed.

**Comment by ErikEJ** [comment] 2021-01-20 16:57
@wvmstr are you trying to upgrade a complex EF6 app to EF Core?

**Comment by wvmstr** [comment] 2021-01-20 17:11
> @wvmstr are you trying to upgrade a complex EF6 app to EF Core?

Yes, well that depends on your definition of complex. 

Lot of tables, all sorts of relationships, mostly normalized till it hurt, then added some convenience relations. I would say a typical db for a transactional application.

**Comment by roji** [comment] 2021-01-21 12:10
Duplicate of #23835

**Comment by roji** [comment] 2021-01-21 12:10
@wvmstr I indeed have your repro - I've just not gotten around to working on it yet... I've reopened #23835 to track this work, and will close this as a duplicate for now.

**Closed** 2022-10-16 19:19 UTC
Labels: closed-duplicate, customer-reported
