### ISSUE TITLE
SetPropertyCalls<TSource> need a method

### ISSUE THREAD

**Issue by wangronghua** [dotnet/efcore#30202] opened 2023-02-03 02:06 UTC
![image](https://user-images.githubusercontent.com/19945852/216495021-32df12de-0606-45a9-ab26-13545640ce52.png)

need a method like

```
        public SetPropertyCalls<TSource> SetProperty<TProperty>(string propertyName, TProperty valueExpression)
        {
            
        }
```

**Comment by ajcvickers** [comment] 2023-02-03 10:31
Duplicate of #30149

**Closed by ajcvickers** 2023-02-03 10:31 UTC
Labels: customer-reported
