### ISSUE TITLE
Allow Interface type for NoSQL/Cosmos DB

### ISSUE THREAD

**Issue by SharpNoiZy** [dotnet/efcore#14074] opened 2018-12-04 10:22 UTC
I just tryed the EF provider for Cosmos and I want to use one of the strenght of an NoSQL DB like Cosmos.
But currently it doesn't seem to work ;(

I want to to something like:
public interface IEventData
{
}

public class Event
{
   public int Nr {get;set;}

   public IEventData Payload {get;set;}
}

public class EventABC : IEventData
{
   public string Name {get;set;}
}

public class EventXYZ : IEventData
{
   public bool IsCool {get;set;}
}

public TestDbContext : DbContext
{
  public DbSet<Event> Events {get;set;}
}

```
Exception message:
System.InvalidOperationException: 'The property 'Event.Payload' is of an interface type ('IEventData'). If it is a navigation property manually configure the relationship for this property by casting it to a mapped entity type, otherwise ignore the property using the NotMappedAttribute or 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.'
```

### Further technical details
EF Core version: 3.0.0-preview.18572.1
Database Provider: (e.g. Microsoft.EntityFrameworkCore.Cosmos)

I think this feature is needed for a NoSql DB.

Kind regards

**Comment by divega** [comment] 2018-12-07 19:54
@SharpNoiZy could you explain:
1. Why you think this may be more important for non-relational databases than relational?
2. What do you expect to be able to map in this collection? Only types that are stored in the same Cosmos DB container/collection? 
3. Is this specifically for owned entity collections that are stored nested in the JSON payload of the owner or general for all relationships?

**Comment by ajcvickers** [comment] 2018-12-14 18:22
**EF Team Triage:** Closing this issue as duplicate of #757 since the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:42 UTC
Labels: customer-reported
