### ISSUE TITLE
Parallel requests in asp core with EF core produce FOREIGN KEY constraint conflict

### ISSUE THREAD

**Issue by jozif001** [dotnet/efcore#29387] opened 2022-10-18 12:21 UTC
## Issue
am facing a weird behavior with EF core, when I try to insert multiple objects with their children from Parallel requests I get a FOREIGN KEY constraint conflict error on one of the requests and the other one is processed successfully.

## EF configuration
the child entities are configured as Owned entities.  
the DbContext has EnableRetryOnFailure() option:
```
optionsBuilder.UseSqlServer(
     "Data Source=DESKTOP-V1V687R;Initial Catalog=EF_CORE_ISSUE;Integrated Security=True",
     options =>
     {
          options.CommandTimeout(120);

          options.EnableRetryOnFailure(
               maxRetryCount: 5,
               errorNumbersToAdd: null,
               maxRetryDelay: System.TimeSpan.FromSeconds(30));
     } );
```

## code example
I have reproduced the error in a sample project, which can be found here:
https://github.com/jozif001/efcore_issue

the project contains 2 applications and ASP core API version 3.1, and a console app that sends 2 parallel requests to the API.

### Logs
I made a test with 2 parallel requests:

- first request logs: 
https://github.com/jozif001/efcore_issue/blob/master/request_logs/Request_1_Logs.txt
- second request logs: 
https://github.com/jozif001/efcore_issue/blob/master/request_logs/Request_2_Logs.txt

note: error occurred on the second request,

### Version information

Database provider: Microsoft.EntityFrameworkCore.SqlServer => version: 3.1.16
Target framework: netcoreapp3.1

**Comment by ajcvickers** [comment] 2022-10-25 09:21
@jozif001 Can you post the SQL generated by each request and the full stack trace of the exception?

**Comment by jozif001** [comment] 2022-10-25 10:39
@ajcvickers i made changes to the issue to include the logs of the requests

**Comment by jozif001** [comment] 2022-10-31 10:34
@ajcvickers I updated the example project to 6.0.10 and it worked, and by analyzing the generated SQL, I see that EF core is now generating multiple insert SQL commands for each child.
but unfortunately, when I upgraded our project to 6.0.10 it still gave us the same error. I need to do more research on the issue, 
I did notice however that the error is related to a deadlock issue, because when I remove the RetryOnFailure option
```
options.EnableRetryOnFailure(
     maxRetryCount: 5,
     errorNumbersToAdd: null,
     maxRetryDelay: System.TimeSpan.FromSeconds(30));
```
it gives me a deadlock error, and in the error message, it recommends using "EnableRetryOnFailure".

**Comment by ajcvickers** [comment] 2022-11-15 15:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-11-15 15:08 UTC
Labels: customer-reported
