### ISSUE TITLE
Changing state of an entity (retrieved with AsNoTracking) will throw an ArgumentNullException

### ISSUE THREAD

**Issue by rventurelli** [dotnet/efcore#30439] opened 2023-03-08 18:44 UTC
Changing state of an entity (retrieved with AsNoTracking) will throw a ThrowArgumentNullException.
Using EF6 this code works without problems.

Code to reproduce:

```C#
using (var context = new MyDbContext())
{
    var entity = await context.Set<MyEntity>()
        .AsNoTracking()
        .Where(_ => _.MyEntityId.Equals("ENTITY_ID"))
        .FirstOrDefaultAsync();

    Console.WriteLine("Entity retrieved");

    context.Entry(entity).State = EntityState.Modified;  // <-- THIS WILL THROW THE EXCEPTION...!!!

    context.Set<MyEntity>()
        .Update(entity);

    await context.SaveChangesAsync();
}
```

### Stack traces

```
System.ArgumentNullException: 'Value cannot be null. (Parameter 'second')'
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SequenceEqual[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.GetCurrentValue[TProperty](IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.OriginalValues..ctor(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.EnsureOriginalValues()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, Nullable`1 fallbackState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry.set_State(EntityState value)
   at EF7BugConsoleApp.Program.<Main>d__0.MoveNext() in D:\Projects\_Test\EF7BugConsoleApp\EF7BugConsoleApp\Program.cs:line 22
```

### Provider and version information

EF Core version: 7.0.3
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL (7.0.3)
Target framework: .NET 7.0
Operating system: Windows 11, Linux via Docker image (mcr.microsoft.com/dotnet/aspnet:7.0)
IDE: Visual Studio 2022 17.5.1

**Comment by ajcvickers** [comment] 2023-03-08 20:28
I am not able to reproduce this--see my code below. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
using (var context = new SomeDbContext())
{
    context.Database.EnsureDeleted();
    context.Database.EnsureCreated();

    context.Add(new MyEntity { MyEntityId = "ENTITY_ID" });
    context.SaveChanges();
}

using (var context = new SomeDbContext())
{
    var entity = await context.Set<MyEntity>()
        .AsNoTracking()
        .Where(_ => _.MyEntityId.Equals("ENTITY_ID"))
        .FirstOrDefaultAsync();

    Console.WriteLine("Entity retrieved");

    context.Entry(entity).State = EntityState.Modified;  // <-- THIS WILL THROW THE EXCEPTION...!!!

    context.Set<MyEntity>()
        .Update(entity);

    await context.SaveChangesAsync();}

public class MyEntity
{
    public string MyEntityId { get; set; }
    public int Foo { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseNpgsql("Server=127.0.0.1;Port=5432;Database=myDataBase;User Id=myUsername;Password=myPassword;")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MyEntity>();
    }
}
```

**Comment by rventurelli** [comment] 2023-03-08 21:59
Hi @ajcvickers, I've identified the problem in the concurrency token used in my entity.

In EF6 I use this code in my entity:
```c#
[ConcurrencyCheck]
[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
public byte[] RowVersion { get; set; }
```
and this code on MyDbContext.OnModelCreating method:
```c#
var rowVersionConverter = new ValueConverter<byte[], long>(v => BitConverter.ToInt64(v, 0),
    v => BitConverter.GetBytes(v));

var rowVersionComparer = new ValueComparer<byte[]>((c1, c2) => c1.SequenceEqual(c2),
    c => c.Aggregate(0, (a, v) => HashCode.Combine(a, v.GetHashCode())),
    c => c.ToArray());

modelBuilder.Entity<MyEntity>()
    .Property(_ => _.RowVersion)
    .HasColumnName("xmin")
    .HasColumnType("xid")
    .HasConversion(rowVersionConverter)
    .Metadata.SetValueComparer(rowVersionComparer);
```

I think the problem was the PostgreSql driver implementation that is changed for EF7:
[Concurrency Tokens in PostgreSQL](https://www.npgsql.org/efcore/modeling/concurrency.html?tabs=data-annotations)

Setting the RowVersion property as descibed in the official documentation I was able to resolve the problem.

For EF7 the code in my entity will be:
```c#
[Timestamp]
public uint RowVersion { get; set; }
```
and the code on MyDbContext.OnModelCreating method will be:
```c#
modelBuilder.Entity<Device>()
    .Property(_ => _.RowVersion)
    .IsRowVersion();
```

**Comment by ajcvickers** [comment] 2023-03-12 20:33
@roji Anything to do here?

**Comment by roji** [comment] 2023-04-23 20:04
Sorry for taking so long to response to this. I'm not too sure about the usage above, which value-converters a byte[] to an xid (the PG auto-concurrency token type); especially since xid is a uint and not a long.

There were indeed some changes around how xid concurrency tokens are configured in 7.0 - your new EF7 code looks good. I haven't received any other complaints about breakage moving from 6.0 to 7.0, so I'll go ahead and close this for now; but will revisit if any further reports come up.

**Closed by roji** 2023-04-23 20:04 UTC
Labels: customer-reported
