### ISSUE TITLE
DbSetFinder should finds property of DbSet<> in base type

### ISSUE THREAD

**Issue by Zefek** [dotnet/efcore#24511] opened 2021-03-25 16:47 UTC
I solve some issues throught domain model. I know DbContext is combination of Unit of Work and Repository pattern. I hope DbContext as Tracker is Unit of Work and DbSet is Repository. 
When I write my domain layer I need to create IUnitOfWork and some IRepository interfaces. IUnitOfWork I can simply implement in my DbContext. It means MyDbContext : DbContext, IUnitOfWork. I cannot create new class. 

What I want to do is create repository like MyRepository : DbSet<MyEntity>, IMyRepository. And I want to use it in MyDbContext like MyRepository MyEntityRepository { get; set; } //it is DbSet because of base type. 

I can't do this because DbSetFinder find property with DbSet<> type but don't take base types. 

So my solution (as I saw source of DbSetFinder) should by change condition in private static DbSetProperty[] FindSetsNonCached(Type contextType)
from && p.PropertyType.GetGenericTypeDefinition() == typeof(DbSet<>
to && (p.PropertyType.GetGenericTypeDefinition() == typeof(DbSet<>)
          || p.PropertyType.BaseType?.GetGenericTypeDefinition() == typeof(DbSet<>))

Is there any reason to not implement it?

**Comment by ajcvickers** [comment] 2021-03-26 14:56
@Zefek It certainly not intended that DbSets be used in this way, and it may not even be possible. How are you going to create and manage your DbSet instances?

**Comment by ajcvickers** [comment] 2021-04-06 15:19
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:29 UTC
Labels: closed-no-further-action, customer-reported
