### ISSUE TITLE
GroupJoin throws InvalidOperationException

### ISSUE THREAD

**Issue by PawelGerr** [dotnet/efcore#18023] opened 2019-09-24 18:10 UTC
The following query with a `GroupJoin` throws an `InvalidOperationException` after updating the project to EF Core 3.0.

### Query
``` C#
var groups = Context.ProductGroups
		    .GroupJoin(Context.Products,
				g => g.Id,
				p => p.GroupId, 
                                (g, p) => new
				{
					ProductGroup = g,
					Products = p
				})
				.ToList();
```

### Exception
```
Unhandled exception. System.InvalidOperationException: Processing of the LINQ expression 'GroupJoin<ProductGroup, Product, Guid, <>f__AnonymousType1<ProductGroup, IEnumerable<Product>>>(
    outer: DbSet<ProductGroup>,
    inner: DbSet<Product>,
    outerKeySelector: (g) => g.Id,
    innerKeySelector: (p) => p.GroupId,
    resultSelector: (g, p) => new {
        ProductGroup = g,
        Products = p
     })' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandAndReduce(Expression query, Boolean applyInclude)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

### Demo(s)
Look for `FetchGroups_Select_Filtered_Products_via_GroupJoin` in [Sources](https://github.com/PawelGerr/Presentation-EntityFrameworkCore/blob/EF-Core_3.0/src/EntityFramework.Demo/Demos/N_Plus_One_Queries.cs) if need more information about the model.

### Further technical details
* Microsoft.EntityFrameworkCore.SqlServer: 3.0.0
* Target framework: netcoreapp3.0

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

**Comment by smitpatel** [comment] 2019-09-24 18:23
Duplicate of #17068 

GroupJoin does not have equivalent SQL operation so grouping has to be done on client side.

**Closed** 2022-10-16 14:44 UTC
Labels: customer-reported
