### ISSUE TITLE
Default value for Id of type GUID now no longer set in EF Core 3.0?

### ISSUE THREAD

**Issue by patricknolan** [dotnet/efcore#19001] opened 2019-11-20 21:32 UTC
I Just updated to EF Core 3.0 and am getting a heap of errors.

I have an entity with an Id of type Guid. When I called the DBSet AddAsync with my new entity the Guid would be automatically populated. This meant I knew what the Guid would be prior to saving. However, since upgrading to 3.0 Id is still the default value for Guid. 

Is this a deliberate change or a bug? If it's a deliberate change it's going to make upgrading very painful for people :(

In migration void BuildTargetModel(ModelBuilder modelBuilder)
```
b.Property<Guid>("Id")
.ValueGeneratedOnAdd()
.HasDefaultValueSql("(newid())");
```

In OnModelCreating(ModelBuilder modelBuilder)

`entity.Property(e => e.Id).HasDefaultValueSql("(newid())");`

**Comment by ajcvickers** [comment] 2019-11-24 22:16
@patricknolan Are you sure that, in your 2.2 code, the GUID set before calling `SaveChanges` is the same as the GUID set after calling `SaveChanges`? The configuration posted above should generate a temporary GUID, which is then replaced by the database-generated GUID after the row has been inserted. Using my test code below on 2.2 I see the output:

```
cb17f33d-83f9-4dd3-910d-fd16f50a0d52
39f3552a-ba91-4b09-9c2c-c09cd210425b
```
which seems to confirm this.

For 3.0, we made [a change to the way temporary values are handled](https://docs.microsoft.com/ef/core/what-is-new/ef-core-3.0/breaking-changes#tkv) such that they are not stored on the entity instance but instead kept track of in the context. These means that when I run the same code on 3.0 I get:

```
00000000-0000-0000-0000-000000000000
678412e6-a1d5-44f0-b0c4-363313370a92
```
In both 2.2 and 3.0, if `HasDefaultValueSql("(newid())")` is not called, then the GUID will be generated on the client side when `Add` is called. Making this change and running the code results in:

```
ba355592-0199-45dd-4b05-08d7712ba2bb
ba355592-0199-45dd-4b05-08d7712ba2bb
```

If you are seeing something different, then please post a small, runnable project/solution or complete code listing that demonstrates what you are seeing.

```C#
public class User
{
    public Guid Id { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>().Property(e => e.Id).HasDefaultValueSql("(newid())");
    }
    
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var user = context.Add(new User()).Entity;
            Console.WriteLine(user.Id);
            
            context.SaveChanges();
            Console.WriteLine(user.Id);
        }
    }
}    
```

**Comment by ajcvickers** [comment] 2019-12-02 16:55
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:57 UTC
Labels: closed-could-not-reproduce, customer-reported
