### ISSUE TITLE
Redundant queries when using OUTER APPLY

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#27349] opened 2022-02-02 17:40 UTC
Related: 
https://github.com/dotnet/efcore/issues/22222
https://github.com/dotnet/efcore/issues/7776

Background:
We need to compare two rows from the same table side-by-side to send to a machine learning algorithm.  LINQ in attached project takes current row and next row and creates a new object with columns from both.

I formatted SQL a bit and added some column names, otherwise it is as generated by EF.
My question relates to the purpose of `SELECT TOP(1)...` statements as the values returned by those statements are already supplied by the `OUTER APPLY`.

If this is a dupe of the second ticket above, I submit this as another use case and a request to prioritize this work as it was first reported five years ago.  

Edit:  A good argument can be made that the generated SQL is unusable and that this is a bug.  That is certainly true in my case - I wound up cutting my losses with EF and writing the SQL by hand.

	SELECT 
		COALESCE((
		SELECT TOP(1) CAST([b].[CurrentVoltage] AS real)
		FROM [BatteryHistory] AS [b]
		WHERE (([b].[ModuleId] = [b1].[ModuleId]) OR ([b].[ModuleId] IS NULL AND [b1].[ModuleId] IS NULL)) AND ([b].[UpdateTime] > [b1].[UpdateTime])
		ORDER BY [b].[UpdateTime]), CAST(0 AS real)) as WHY_1 -- Supplied by NextVoltage
		
		, [t].[c] as NextVoltage -- COALESCE(...)
		, [t].[UpdateTime] as NextUpdateTime
		, [t].[c0] as NextID
		, (
			SELECT TOP(1) [b0].[UpdateTime]
			FROM [BatteryHistory] AS [b0]
			WHERE (([b0].[ModuleId] = [b1].[ModuleId]) OR ([b0].[ModuleId] IS NULL AND [b1].[ModuleId] IS NULL)) AND ([b0].[UpdateTime] > [b1].[UpdateTime])
			ORDER BY [b0].[UpdateTime]
		  ) as WHY_2 -- Supplied by NextUpdateTime
		
		, [b1].[UpdateTime]
		, CONVERT(VARCHAR(20), [b1].[ModuleId]) as ModuleID
		, CAST([b1].[CurrentVoltage] AS real) CurrentVoltage
	FROM [BatteryHistory] AS [b1]
	OUTER APPLY (
		SELECT TOP(1) 
		CAST([b2].[CurrentVoltage] AS real) AS [c]  
		, [b2].[UpdateTime]
		, 1 AS [c0]
		FROM [BatteryHistory] AS [b2]
		WHERE ([b2].[UpdateTime] > [b1].[UpdateTime]) AND (([b1].[ModuleId] = [b2].[ModuleId]) OR ([b1].[ModuleId] IS NULL AND [b2].[ModuleId] IS NULL))
		ORDER BY [b2].[UpdateTime]
	) AS [t]
	ORDER BY [b1].[UpdateTime]
	
	
Program:

    class Program
    {
        static void Main(string[] args)
        {
            Db db = new Db(new DbContextOptionsBuilder<Db>().UseSqlServer("Server=.;Database=BatteryHistoryQuery1;Trusted_Connection=True;").Options);
            CreateHistoricalData(db);
            
            var data = Query1(db);
        }

        static void CreateHistoricalData(Db db)
        {
            db.Database.EnsureDeleted();
            db.Database.EnsureCreated();
            string sql = @"insert into BatteryHistory
                        (ModuleId, ModuleKey, UpdateTime, CurrentVoltage)
                        values
                        (1, '1','2022-01-01', 1),
                        (1, '1', '2022-01-03', 2),
                        (1, '1', '2022-01-05', 3),
                        (2, '2', '2022-02-01', 1),
                        (2, '2', '2022-02-10', 2),
                        (2, '2', '2022-02-15', 3)";
            db.Database.ExecuteSqlRaw(sql);
        }

        static IEnumerable<Prediction> Query1(Db db)
        {
            var query = from b in db.BatteryHistories
                        
                        let forecast = (from fb in db.BatteryHistories
                                        where fb.ModuleId == b.ModuleId && fb.UpdateTime > b.UpdateTime
                                        orderby fb.UpdateTime
                                        select new
                                        {
                                            CurrentVoltage = (float?)fb.CurrentVoltage,
                                            UpdateTime = fb.UpdateTime
                                        }).FirstOrDefault()
                        orderby b.ModuleId
                        orderby b.UpdateTime
                        select new Prediction
                        {
                            ForecastVoltage = forecast.CurrentVoltage ?? 0,
                            ForecastPeriod = forecast == null ? 0 : (float)forecast.UpdateTime.Subtract(b.UpdateTime).TotalDays,
                            ModuleId = b.ModuleId.ToString(),
                            UpdateTime = b.UpdateTime,
                            CurrentVoltage = (float)b.CurrentVoltage
                        };
            
            string sql = query.ToQueryString();
            return query;
        
        }
    }

    public partial class Prediction
    {
        // Prediction
        public float ForecastVoltage { get; set; }
        public float ForecastPeriod { get; set; } // Number of days between UpdateTime of the current row and UpdateTime of the forecast row.
        // History
        public string ModuleId { get; set; }
        public DateTime UpdateTime { get; set; }
        public float CurrentVoltage { get; set; }
    }

    public partial class BatteryHistory
    {
     
        public long? ModuleId { get; set; }
        public string ModuleKey { get; set; }
        public DateTime UpdateTime { get; set; }
        public decimal? CurrentVoltage { get; set; }
    }

    public class Db : DbContext
    {
        public virtual DbSet<BatteryHistory> BatteryHistories { get; set; }

        public Db(DbContextOptions<Db> options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BatteryHistory>(entity =>
            {
                entity.HasNoKey();
                entity.ToTable("BatteryHistory");
                entity.HasIndex(e => e.UpdateTime, "NonClusteredIndex-20211222-124829");
                entity.HasIndex(e => e.ModuleId, "NonClusteredIndex-20211222-124919");
                entity.Property(e => e.CurrentVoltage).HasColumnType("numeric(7, 5)");
                entity.Property(e => e.UpdateTime).HasColumnType("datetime");
            });
        }
    }

Version:
EF 5.0.13
.net 5

**Comment by smitpatel** [comment] 2022-02-02 19:29
```C#
select new Prediction
                    {
                        ForecastVoltage = forecast.CurrentVoltage ?? 0,
                        ForecastPeriod = forecast == null ? 0 : (float)forecast.UpdateTime.Subtract(b.UpdateTime).TotalDays,
                        ModuleId = b.ModuleId.ToString(),
                        UpdateTime = b.UpdateTime,
                        CurrentVoltage = (float)b.CurrentVoltage
                    };
```
`forecast.CurrentVoltage` brings the first subquery.
`forecast.UpdateTime` brings the second subquery. `Subtract` is not translatable to server hence it will be evaluated on client.
`forecast == null` check forces us to generate a `OUTER APPLY` because it is an anonymous type, we generate an outer apply with 1 as column inside and if that particular column is null then resulting anonymous type will be null.

Duplicate of #7776

**Closed** 2022-10-16 20:24 UTC
Labels: customer-reported
