### ISSUE TITLE
Client evaluation of query parts

### ISSUE THREAD

**Issue by santanaguy** [dotnet/efcore#2534] opened 2015-07-04 23:05 UTC
I noticed that EF sometimes brings the data it needs from the table and then applies a filter when it can't transform an expression into SQL. Eg.

 var newdoc = context1.Documents.Where(x => x.ID > TestMethod(x.ID)).ToList(); 

This results in all documents being pulled from the database and then the Where is evaluated on the client.
I am worried this will be a problem as i might be surprised with the SQL generated by this query. Inexperient or new developers that aren't aware of this behaviour might create highly inneficient queries that evaluate on the client machine and create a lot of stress on the network. So my question is:

Is there a way to disable this feature so that i can have the old behaviour of throwing an exception back?
If not, what is the recomended pattern to avoid this kind of complications? Should i double check every query EF generates? This might prove a painpoint in big applications.

In EF6 we always had that "line" which separated the two worlds (ToList()), but now it seems a little blurred.

**Comment by rowanmiller** [comment] 2015-07-14 17:32
Duplicate of https://github.com/aspnet/EntityFramework/issues/1856
Already on the Pri0 list for the initial RTM of EF7.

**Closed** 2022-10-16 09:01 UTC
