### ISSUE TITLE
Unspecified IsRequired leads to IsRequired = true for nullable fields

### ISSUE THREAD

**Issue by jsiegmund** [dotnet/efcore#20074] opened 2020-02-26 12:36 UTC
We have used the CLI scaffolding command to create context + models based on an existing database. We were getting a lot of `SqlNullValueException`s stating `"Data is Null. This method or property cannot be called on Null values."`. 

After some investigation we found out that EF was treating nullable fields as not-nullable. Adding `IsRequired(false)` within the context manually resolves this issue, but should not have been necessary. Some details:
* For not-nullable fields, ef scaffolding generates  `IsRequired()`
* For nullable fields, ef scaffolding did not generate any additional code. I would assume that not explicitly calling IsRequired would leave the field as **not** required
* Yet the above exception is thrown for these fields and adding `IsRequired(false)` solves this issue. 

So it appears as if the default setting for fields is now: required except explicitly specified otherwise. If this is expected behavior, scaffolding should generate `IsRequired(false)` for nullable columns.

### Steps to reproduce

**DB table example:**
```sql
CREATE TABLE .[Markets](
	[MarketID] [int] NOT NULL,
	[ExternalMarketID] [varchar](50) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Description] [varchar](50) NULL,
	[Code] [varchar](10) NULL,
	[Brand] [varchar](50) NULL
) ON [PRIMARY]
```

**Generated model:**
```C#
public partial class Markets
{
    public int MarketId { get; set; }
    public string ExternalMarketId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string Code { get; set; }
    public string Brand { get; set; }
}
```` 

**Generated code in `OnModelCreating`:**
```C#
modelBuilder.Entity<Markets>(entity =>
{
    entity.HasNoKey();

    entity.ToTable("Markets", "dbo");

    entity.Property(e => e.Brand)
        .HasMaxLength(50)
        .IsUnicode(false);

    entity.Property(e => e.Code)
        .HasMaxLength(10)
        .IsUnicode(false);

    entity.Property(e => e.Description)
        .HasMaxLength(50)
        .IsUnicode(false);

    entity.Property(e => e.ExternalMarketId)
        .IsRequired()
        .HasColumnName("ExternalMarketID")
        .HasMaxLength(50)
        .IsUnicode(false);

    entity.Property(e => e.MarketId).HasColumnName("MarketID");

    entity.Property(e => e.Name)
        .IsRequired()
        .HasMaxLength(50)
        .IsUnicode(false);
});
```

**Exception when fetching list:**
```
SqlNullValueException("Data is Null. This method or property cannot be called on Null values.")
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at --- :line 40
```

### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4

**Comment by ajcvickers** [comment] 2020-02-28 17:15
@jsiegmund Do you have C# 8 nullable reference types enabled in your project?

**Comment by smitpatel** [comment] 2020-02-28 18:26
Generated code is consistent with the database table. We put IsRequired only for not null columns. And we skip it for null columns.

**Comment by ajcvickers** [comment] 2020-02-28 22:36
@jsiegmund To @smitpatel's point here, the generated code looks correct. Can you attach a small, runnable project that reproduces the queries you are running against the model that are then throwing exceptions?

**Comment by jsiegmund** [comment] 2020-02-29 13:47
I considered nullable reference types as well and ran with that option both on and off, no difference. I think it should not matter to begin with as that's more a compile time check and this error happens at runtime and comes from within the EF core code. 

I'll create a sample project, need to carve out some time for that. I'll see what I can do tomorrow.

**Comment by ajcvickers** [comment] 2020-03-09 16:13
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:13 UTC
Labels: closed-could-not-reproduce, customer-reported
