### ISSUE TITLE
Default includes

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#18342] opened 2019-10-11 14:40 UTC
I'm using EF Core Identity.
using `UserManager<TUser>` I am able to retreive a `TUser` entity - as it wraps my `DbContext`.
I've now extended my `TUser` entity to have navigation property to a child collection (aka foreign key).

Suppose now that I want to ensure that whenever a TUser is retrieved, this navigation property is eager loaded.

Consumers of `UserManager<T>` can retreive a `TUser` but as `UserManager` constructs that IQeuryable, it won't know anything about this navigation property and it won't eager load it. Therefore to fulfill my requirements, I'll have to derive my own custom `UserManager` api just to append some includes to its IQueryables.

I'd like to see the ability to configure default "Includes" for entities. Similar to the concept of global filters, being able to configure eager loading defaults during model configuration would be very useful. It means I could configure the DbContext to include User.MyCollection by default, and then no code needs to change in `UserManager<TUser>` and I don't need to derive any custom identity classes to achieve my goals.

Something like:

```
modelBuilder.Entity<User>.Include(a=>a.Roles); // Any IQueryable<User> will now by default have this include added before execution.
```

**Comment by smitpatel** [comment] 2019-10-11 20:41
Duplicate of #2953

**Closed** 2022-10-16 14:49 UTC
Labels: customer-reported
