### ISSUE TITLE
Query: incorrect sql generated for query with groupby aggregate also projecting grouping key and ordering by said key afterwards

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12650] opened 2018-07-12 17:30 UTC
query:

```cs
ctx.Orders.GroupBy(
                        o => o.OrderID, o => new
                        {
                            o.OrderID,
                            o.OrderDate
                        })
                    .Select(
                        g => new
                        {
                            g.Key,
                            Avg = g.Average(e => e.OrderID),
                            Max = g.Max(o => o.OrderDate)
                        }).OrderBy(e => e.Key).ToList();
```
sql:

```sql
SELECT [o].[OrderID] AS [Key], AVG(CAST([o].[OrderID] AS float)) AS [Avg], MAX([o].[OrderDate]) AS [Max]
FROM [Orders] AS [o]
GROUP BY [o].[OrderID]
ORDER BY [o].[OrderID] AS [Key] DESC
```

Exception:

Incorrect syntax near the keyword 'AS'.

**Comment by smitpatel** [comment] 2018-07-27 19:58
Duplicate of #12826

**Closed** 2022-10-16 13:19 UTC
Labels: type-bug, closed-duplicate
