### ISSUE TITLE
EF Core 2.0 Identity - Adding navigation properties creates new foreign keys

### ISSUE THREAD

**Issue by adnan-kamili** [dotnet/efcore#9567] opened 2017-08-25 04:19 UTC
In EF Core 2.0 Identity navigation properties are not included by default, so after upgrading, I added them. So for Many-To-Many relationship between User and Role, and One-To-Many relationship between Role and RoleClaim, I added following navigation properties:

```csharp
public class User : IdentityUser
{
    [Required]
    public string Name { get; set; }

    public virtual ICollection<IdentityUserRole<string>> Roles { get; set; }
}

public class Role : IdentityRole
{
    [Required]
    public string Name { get; set; }

    public virtual ICollection<IdentityRoleClaim<string>> Claims { get; set;}
}
```
Surprisingly it adds an additional `RoleId1 `key to `AspNetRoleClaims `table and `UserId1 `to `AspNetUserRoles `tables and all the `Find ` queries actually use new keys instead of `RoleId `and `UserId ` which are also present.

EF Core version: 2.0.0
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL v2.0.0, Pomelo.EntityFrameworkCore.MySql v2.0.0
Operating system: macOS 10.12
Repo: https://github.com/adnan-kamili/AspNetCore-Web-Api-Rest-Starter-Kit/tree/master/Models

**Comment by ajcvickers** [comment] 2017-08-25 17:19
Duplicate of #9503; see my comments there.

**Closed** 2022-10-16 11:18 UTC
Labels: closed-external
