### ISSUE TITLE
.NET 8 Preview 6: "Contains" Error => Incorrect syntax near '$'.

### ISSUE THREAD

**Issue by aherrick** [dotnet/efcore#31362] opened 2023-07-27 01:28 UTC
In .NET 7 EF Core I was able to do something like this. Works great:

```
        var beers = await (from b in Db.Beer
                           where beerIds.Contains(b.Id)
                           select b).ToListAsync();
```

In .NET 8 Preview 6 I get the following error:

`Message: "Incorrect syntax near '$'."
`

What changed? How do I need to update my query?

**Comment by ErikEJ** [comment] 2023-07-27 05:07
@aherrick it is because EF Core uses a feature that is not supported with the compatibility level of your database, it must be 130 or newer. (SQL Server 2016 or newer)

You can detect with:

```sql
SELECT compatibility_level 
FROM sys.databases 
WHERE name = 'MyDatabase';

```
You can either change the compatibility level:

```sql
ALTER DATABASE MyDatabase
SET COMPATIBILITY_LEVEL = 160

```
or tell EF Core what is actually is:

`optionsBuilder.UseSqlServer(connectionString, o => o.UseCompatibilityLevel(110));`

**Comment by ErikEJ** [comment] 2023-07-27 05:08
Duplicate of #31323

**Comment by roji** [comment] 2023-07-27 09:48
Duplicate of #31323

**Closed** 2023-07-27 09:57 UTC
Labels: customer-reported

**Comment by aherrick** [comment] 2023-07-27 10:05
thank you! and sorry for the dupe! it's confusing that even though my DB is running in Azure it still needs to be manually bumped

**Comment by ErikEJ** [comment] 2023-07-27 11:29
Azure SQL Database supports [many compatibility levels](https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-compatibility-level?view=sql-server-ver16#compatibility_level--160--150--140--130--120--110--100--90--80-)

When you create an Azure SQL DB from a .bacpac the compatibility of the source database is preserved.

And you should be careful [when switching level](https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-compatibility-level?view=sql-server-ver16#best-practices-for-upgrading-database-compatibility-level)

**Comment by Montago** [comment] 2023-12-05 12:07
> optionsBuilder.UseSqlServer(connectionString, o => o.UseCompatibilityLevel(110));

@ErikEJ  Why isn't this autodetected ? ... it should be..

**Comment by ErikEJ** [comment] 2023-12-05 12:54
@Montago To avoid unneccesary processing/sql commands during runtime.

**Comment by roji** [comment] 2023-12-05 19:16
@Montago there are various sotiatopms where we simply don't have a connection to your database when we need to generate SQL.

**Comment by Montago** [comment] 2023-12-06 07:23
@ErikEJ - EF could easily probe this property once and save it in a static variable somewhere.  My solution so far has been to do the work for EF and probe every time i construct a dbcontext :-/

**Comment by ErikEJ** [comment] 2023-12-06 07:35
@Montago You need to do this because your customers run with unknown compatibility levels?

**Comment by Mimisss** [comment] 2024-01-12 10:30
We are having the same issue:

```
public enum TestType { ... }

public static int[] TestTypes
{
    get
    {
        return new int[]  {  (int)TestType.Aimatologikes, (int)TestType.Bioxhmikes, (int)TestType.DiagnostikaTest, ... };
    }
}

visitTests = visitTests.Where(t => TestTypeHelper.TestTypes.Contains(t.Type));
```

even though our SQL Server database is of 110 compatibility level.

We are in the process of upgrading from .net core 3.1 to .net 8.

**Comment by Montago** [comment] 2024-01-12 11:18
@Mimisss  just do this : 

optionsBuilder.UseSqlServer(connectionString, o => o.UseCompatibilityLevel(110));

EF might translate incorrectly unless you limit it.

**Comment by Mimisss** [comment] 2024-01-12 11:34
> @Mimisss just do this :
> 
> optionsBuilder.UseSqlServer(connectionString, o => o.UseCompatibilityLevel(110));
> 
> EF might translate incorrectly unless you limit it.

Yes, it works. We are using SQL Server 2019, btw. Thanks.

**Comment by ErikEJ** [comment] 2024-01-12 11:49
@Mimisss It is the not the server version but your database compatibility level that matters.

**Comment by roji** [comment] 2024-01-12 11:51
@Mimisss if you're using a relatively new version of SQL Server (e.g. 2019), it should be able to handle the new syntax; so that likely means that its compatibility level is set too low. So rather than telling EF to generate older SQL (via UseCompatibilityLevel), considering raising the compatibility level setting in your SQL Server. [See the breaking change note](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#sqlserver-contains-compatibility) for more information.
