### ISSUE TITLE
EFCore 8 Preview7 - RelationalTypeMapping for a parameter doesn't seem correct while updating Json field

### ISSUE THREAD

**Issue by shvmgpt116** [dotnet/efcore#31807] opened 2023-09-19 10:13 UTC
## Ask a question

While debugging sql server GIT test for efcore 8 preview "**JsonUpdateSqlServerTest.Edit_element_in_json_collection_branch**", 
The provider is generating following SQL to update a DateTime field inside the JSON column.

SET IMPLICIT_TRANSACTIONS OFF;
SET NOCOUNT ON;
UPDATE [JsonEntitiesBasic] SET [OwnedCollectionRoot] = JSON_MODIFY([OwnedCollectionRoot], 'strict $[0].OwnedCollectionBranch[0].Date', @p0)
OUTPUT 1
WHERE [Id] = @p1

I have following doubts. Please could someone clarify.

1) The RelationalTypeMapping for the parameter "p0" is of type **SqlServerJsonTypeMapping**. 
Since p0 is used to update a single field inside the JSON data whose corresponding .NET type is DateTime, I am wandering if the RelationalTypeMapping for the parameter "p0" is correct. Shouldn't it be SqlServerDateTimeTypeMapping.

2) The value for the parameter is "2111-11-11T00:00:00".
For some database providers, this format may be incorrect to store datetime value.
Is it possible for a database provider writer to change the format of the parameter value (while inserting/updating into JSON fields) in such a way that is recognizable by the database?

### Include provider and version information

EF Core version: 8.0.0-preview.7.23375.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.7.3

**Comment by roji** [comment] 2023-09-19 14:41
When looking at code and testing features, you should really use the latest version; 8.0.0-rc.1 is now out, and looking at the latest code in the release/8.0 is even better. Otherwise you may be looking at an outdated/incomplete version of the code.

>The RelationalTypeMapping for the parameter "p0" is of type SqlServerJsonTypeMapping.
Since p0 is used to update a single field inside the JSON data whose corresponding .NET type is DateTime, I am wandering if the RelationalTypeMapping for the parameter "p0" is correct. Shouldn't it be SqlServerDateTimeTypeMapping.

JSON does not have a date/time type like it has integer, string and boolean types - timestamps are simply stored as strings. As a result, we simply pass a string argument to the JSON_MODIFY function - not a SQL Server `datetime2` type.

> For some database providers, this format may be incorrect to store datetime value.

The format in question is ISO8601, which is the industry-standard way to represent timestamps as strings, and is very wide-spread with JSON. Is there an actual issue with this in Oracle?

Regardless, yes - EF allows customizing the JSON representation of any type. We indeed have this problem with SQLite, which (similar to JSON) doesn't have a date/time type and where there are some issues around this representation. Take a look at SqliteJsonDateTimeReaderWriter, which is where we tweak the Sqlite timestamp JSON representation to omit the T.

However, AFAIK this problem really shouldn't occur elsewhere with timestamps - please let me know if there's an actual problem if this is a theoretical question.

**Comment by shvmgpt116** [comment] 2023-09-20 00:52
@roji Thank you very much for the explanation.
Since timestamps are stored as strings in JSON, shouldn't it use **SqlServerStringTypeMapping** then?

Is there any way for a provider writer to change the typemapping for the parameter?
The problem with JsonTypeMapping is that the overridden methods **CreateParameter** and **ConfigureParameter** might bind the parameter incorrectly (bind it as JSON but the parameter value is actually a string).

**Comment by roji** [comment] 2023-09-20 01:11
@shvmgpt116 it's a bit hard to understand the exact trouble you're running into - can you please provide more context on what the exact problem is? Is the issue something specific with the Oracle provider, or are you having trouble with the SQL Server provider?

**Comment by shvmgpt116** [comment] 2023-09-20 03:06
@roji 
Oracle db has native JSON data type support. While inserting the value to JSON column, we plan to bind the parameter dbtype as json. This can be done inside overridden methods **CreateParameter** inside TypeMapping class (For Ex:- OracleJsonTypeMapping).

However in the above example, there is a parameter "p0" whose value is string (not in JSON format) but the type mapping is JsonTypeMapping. So while creating the parameter in "OracleJsonTypeMapping.CreateParameter", we would bind it as (OracleDbType.Json). However binding a string value as OracleDbType.Json is not supported.

That's why I am wandering if the parameter type mapping in the above example should be StringTypeMapping rather than JsonTypeMapping. What is the reason that it is using JsonTypeMapping? 

SqlServer doesn't have such issues since it doesn't have native JSON db type support. SqlServer efcore provider simply uses dbtype Varchar to bind JSON values.

**Comment by ajcvickers** [comment] 2023-09-25 09:24
@shvmgpt116 A lot of code has changed in this area. Can you please update to the latest daily build and see if this still repros, and if it does, then please post the full model building code, entity types, and query so we can investigate.

**Comment by ajcvickers** [comment] 2023-10-11 16:25
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-10-11 16:25 UTC
Labels: customer-reported
