### ISSUE TITLE
Cannot have keys other than those declared on the root type

### ISSUE THREAD

**Issue by peirens-bart** [dotnet/efcore#5309] opened 2016-05-09 19:29 UTC
I'm having these error when running:
dnx ef migrations add BT0001 -c "ApplicationContext" -p "BookerTools.Database.EF" -v

I can't find why I'm having this error, 
I added the project that I'm using, Can someone tell me what I'm doing wrong or what that I forget to do.
Many thanks in advanced.

**Comment by ilkertskn** [comment] 2016-05-09 21:22
http://www.bricelam.net/2014/09/14/migrations-on-k.html

**Comment by peirens-bart** [comment] 2016-05-10 08:08
ilkertskn, The problem is not the command but the exception message that I get.

If I comment out the "MyDatabase" models and mappers in the context, the command is creating the emigration file.
If I uncomment the "MyDatabase" models and mappers I got the exception

```
Finding DbContext classes...
Using context 'ApplicationContext'.
System.InvalidOperationException: The derived type 'BookerTools.Business.Security.User' cannot have keys other than
   at Microsoft.Data.Entity.Metadata.Internal.EntityType.AddKey(IReadOnlyList`1 properties)
   at Microsoft.Data.Entity.Metadata.Internal.MetadataDictionary`2.GetOrAdd(Func`1 getKey, Func`1 createKey, Func`2
   at Microsoft.Data.Entity.Metadata.Internal.InternalEntityTypeBuilder.HasKey(IReadOnlyList`1 properties, Configur
   at Microsoft.Data.Entity.Metadata.Builders.EntityTypeBuilder`1.HasKey(Expression`1 keyExpression)
   at BookerTools.Database.EF.Mappers.FrameworkModelsMapper.MapEntity[T](EntityTypeBuilder`1 builder)
   at BookerTools.Database.EF.Mappers.FrameworkModelsMapper.MapAggregate[T](EntityTypeBuilder`1 builder)
   at BookerTools.Database.EF.Mappers.FrameworkModelsMapper.MapAddressAggregate[T](EntityTypeBuilder`1 builder)
   at BookerTools.Database.EF.Mappers.SecurityModelsMapper.MapUser(EntityTypeBuilder`1 builder)
   at Microsoft.Data.Entity.ModelBuilder.Entity[TEntity](Action`1 buildAction)
   at BookerTools.Database.EF.Mappers.SecurityModelsMapper.Map(ModelBuilder builder)
   at BookerTools.Database.EF.Context.ApplicationContext.OnModelCreating(ModelBuilder modelBuilder)
   at Microsoft.Data.Entity.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder convent
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provid
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider pro
   at Microsoft.Data.Entity.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextT
   at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass6_0.<AddMigration>b__0()
   at Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
The derived type 'BookerTools.Business.Security.User' cannot have keys other than those declared on the root type.
```

For me the message is strange since the User is not part of the "MyDatabase" models and if that model is the cause of the error it should throw the same exception if "MyDatabase" models and mappers are not included.

I think the problem is that some models have the same base class in Framework, and I read about not using the same property names in inheritance but the message it not saying that.
I understand the message as User has a different Primary key then the base class, what is not the case. 
But I have no idea what is causing the exception.

**Comment by rowanmiller** [comment] 2016-05-17 17:21
Looks like a dupe of https://github.com/aspnet/EntityFramework/issues/3727 which was fixed in RC2. Can you retry on the [RC2 release](https://blogs.msdn.microsoft.com/dotnet/2016/05/16/announcing-entity-framework-core-rc2/). 

Closing as we are pretty confident that this is resolved in RC2, please reply if not and we will reopen.

**Comment by peirens-bart** [comment] 2016-05-17 19:44
I was not able to test RC2, the dependency" Microsoft.EntityFrameworkCore.SqlServer 1.0.0-rc2-final" and "Microsoft.EntityFrameworkCore.Tools 1.0.0-preview1-final" is not supported.

I'm only using dnxcore50 as runtime.

**Comment by rowanmiller** [comment] 2016-05-17 21:50
Yeah you would need to move your whole project to RC2, not just the EF parts. DNX is retired in favor of .NET Core in RC2. 

Here are the applicable docs:
* [Migrating from DNX to .NET Core](http://dotnet.github.io/docs/core-concepts/dnx-migration.html)
* [Migrating from ASP.NET 5 RC1 to ASP.NET Core 1.0 RC2](https://docs.asp.net/en/latest/migration/rc1-to-rc2.html)
* [Migrating your Entity Framework Code from RC1 to RC2](https://docs.efproject.net/en/latest/miscellaneous/rc1-rc2-upgrade.html)

**Comment by peirens-bart** [comment] 2016-05-18 20:18
Rowan

I'm not totally understanding the new .Net core, is it possible to give an example of a project.json file that is using EF rc2 en is not an mvc project but a class library.

Just to give more context,
I'm using VS 2015 pro 14.0.25123.00 Update 2 and I'm keep having the same error, that the rc2 versions are not supported.

**Comment by smitpatel** [comment] 2016-05-18 20:31
Tools won't work in class library project see #5320 
this is sample project.json for .NET Core class library project to use SqlServer provider
```json
{
  "version": "1.0.0-*",

  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24027",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final"
  },
  
  "frameworks": {
    "netstandard1.3": {
      "imports": ["portable-net451+win81"]
    }
  }
}
````

**Comment by peirens-bart** [comment] 2016-05-19 18:21
All thanks for the answers,
But we are going to wait until there is a stable version that support more project types.

For the initial issue I found a work-a-round that is using rc1.

**Closed** 2022-10-16 09:40 UTC
