### ISSUE TITLE
OwnedNavigationBuilder Check Constraint 

### ISSUE THREAD

**Issue by dameeks** [dotnet/efcore#20944] opened 2020-05-13 13:53 UTC
After I upgrade to EF Core 5 preview 3, I attempted to add a column via a migration. When I reviewed the generated migration code I noticed check constraints were added for all of my enum properties on my model. However, some of those enum properties reside in Value Objects that are Owned by the root model. Now when I attempt to build I get compilation errors stating:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS1929	'OwnedNavigationBuilder' does not contain a definition for 'HasCheckConstraint' and the best extension method overload 'RelationalEntityTypeBuilderExtensions.HasCheckConstraint(EntityTypeBuilder, string, string)' requires a receiver of type 'EntityTypeBuilder'

EF Core version: 5 Preview 3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1

**Comment by ajcvickers** [comment] 2020-05-13 14:39
Duplicate of #20590

**Closed** 2022-10-16 18:25 UTC
Labels: closed-duplicate, customer-reported
