### ISSUE TITLE
Override the DbConnection to use inside ambient transaction to prevent requirement of DTC

### ISSUE THREAD

**Issue by joshmouch** [dotnet/efcore#13822] opened 2018-10-31 18:32 UTC
Is there a way to set what DbConnection will be used by EF Core?

I have a situation where an ambient transaction is started.  Then a different processes (not EF Core) uses the database inside that transaction.  Then EF Core tries to make some database changes, but when it opens the connection, it gets an error about needing a Distributed Transaction Coordinator.  This is because there are two different connections trying to use the same transaction.
The solution is to tell EF Core to use the same connection that was used for the database changes earlier in the transaction.

**Comment by joshmouch** [comment] 2018-11-01 10:53
For now I'm just using reflection to override the connection when a transaction starts and then setting it back to its original value when the transaction completes unless there is a better way:

```

var dataContextDatabase = dbContext.Database;
var databaseConnection = (SqlServerConnection)dataContextDatabase.GetInfrastructure().GetService(typeof(IRelationalConnection));
_EfCoreConnection = (LazyRef<DbConnection>)databaseConnection.GetFieldValue("_connection");
_EfCoreConnectionIsOwned = (bool)databaseConnection.GetFieldValue("_connectionOwned");
databaseConnection.SetFieldValue("_connection", new LazyRef<DbConnection>(_SharedSqlConnection));
databaseConnection.SetFieldValue("_connectionOwned", false);


```

**Comment by ajcvickers** [comment] 2018-11-01 16:41
Duplicate of #8494. But also see also discussion on #13041 and #13530 for ideas on workarounds.

**Comment by joshmouch** [comment] 2018-11-06 20:49
@ajcvickers 
Thanks!
The first solution requires Transient-scoped DbContext, and the second assumes both connections are inside EF Core, so I don't think either works for me.  I'll continue using reflection for now until this is supported.

**Closed** 2022-10-16 13:38 UTC
Labels: closed-duplicate, customer-reported
