### ISSUE TITLE
Add-Migration command fails with "Value does not fall within the expected range." error

### ISSUE THREAD

**Issue by mtycholaz** [dotnet/efcore#5394] opened 2016-05-17 20:24 UTC
http://imgur.com/Oi9FI2A

Not much to go on, so let me know what you'd like. I simple removed my existing migration to add a new one. Using UWP and SQLite

```
{
  "dependencies": {
    "FubarCoder.RestSharp.Portable": "3.1.0",
    "FubarCoder.RestSharp.Portable.OAuth": "3.1.0",
    "LightInject": "4.0.8",
    "Microsoft.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview1-final",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0",
    "Newtonsoft.Json": "8.0.3"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

I even tried a new class library project, and copied from the example [here](https://docs.efproject.net/en/latest/platforms/uwp/getting-started.html), but I still get the same error.

**Comment by smitpatel** [comment] 2016-05-17 21:43
dupe of #5383

**Closed** 2022-10-16 09:41 UTC
