### ISSUE TITLE
Many to Many configuration, no WithMany after HasMany

### ISSUE THREAD

**Issue by omuleanu** [dotnet/efcore#6541] opened 2016-09-15 17:57 UTC
in EF6 I was configuring many to many like this:

```
modelBuilder.Entity<Dinner>().HasMany(r => r.Meals).WithMany(o => o.Dinners).Map(f =>
{
    f.MapLeftKey("DinnerId");
    f.MapRightKey("MealId");
});
```

in EF Core (1.0.1) there is no WithMany after HasMany just WithOne
is this not implemented yet, or is there a different way of doing this now ?

**Comment by Shayon** [comment] 2016-09-15 18:25
This feature is [not yet supported](https://docs.efproject.net/en/latest/efcore-vs-ef6/features.html#features-not-in-ef-core) in EF Core.

For the time being, I suggest you manually create join table, as [demonstrated here.](http://ef.readthedocs.io/en/latest/modeling/relationships.html#many-to-many)

**Comment by divega** [comment] 2016-09-15 19:45
Duplicate of #1368

**Comment by rowanmiller** [comment] 2016-09-15 20:06
For modelling many-to-many in the current 1.0 bits, see https://docs.efproject.net/en/latest/modeling/relationships.html#many-to-many

**Closed** 2022-10-16 09:57 UTC
