### ISSUE TITLE
ClientEval when use access annonymous type from an subQuery after Take()

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/efcore#15014] opened 2019-03-13 12:57 UTC
Describe what is not working as expected.

Looks similar to #7844?
The below code lead to an client eval, and seems it failed to unpack `new { [x].PK }.PK`.
But it not failed if Remove `Take()`, or move `Select()` after `Take()`, or not select into an annonymous object(if there is only one key needed)

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```cs
ctx.Test001
    .Select(x => new { x.PK })
    .Take(20)
    .Select(x => ctx.Test001.Where(x1 => x1.GroupByKey == x.PK).Count())
    .ToList();
```
->
```
dbug: Microsoft.EntityFrameworkCore.Query[10101]
      Compiling query model:
      'from <>f__AnonymousType0<int> x in
          (from Test001 x in DbSet<Test001>
          select new { [x].PK }).Take(__p_0)
      select
          (from Test001 x1 in DbSet<Test001>
          where [x1].GroupByKey == [x].PK
          select [x1]).Count()'
warn: Microsoft.EntityFrameworkCore.Query[10102]
      Query: '(from Test001 x in DbSet<Test001> select  (from Test001 x1 in DbSet<Test001> where [x1].GroupByKey =...' uses a row limiting operation (Skip/Take) without OrderBy which may lead to unpredictable results.
dbug: Microsoft.EntityFrameworkCore.Query[10104]
      Optimized query model:
      '(from Test001 x in DbSet<Test001>
      select
          (from Test001 x1 in DbSet<Test001>
          where [x1].GroupByKey == new { [x].PK }.PK
          select [x1]).Count()).Take(__p_0)'
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'where ([x1].GroupByKey == new <>f__AnonymousType0`1(PK = [x].PK).PK)' could not be translated and will be evaluated locally.
```

### Further technical details
EF Core version: `3.0.0-preview3.19153.1`(also not works in old versions)
Database Provider: `Microsoft.EntityFrameworkCore.SqlServer`
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by smitpatel** [comment] 2019-03-13 20:12
Duplicate of #14515

**Closed** 2022-10-16 13:55 UTC
Labels: customer-reported
