### ISSUE TITLE
Impossible to use class hierarchy,  probably error in convention

### ISSUE THREAD

**Issue by henrikdahl8240** [dotnet/efcore#19850] opened 2020-02-09 22:21 UTC
I have a type Sub which inherits from type Super and I get this error message:
"The entity type 'Super' cannot inherit from 'Sub' because 'Super' is not a descendant of 'Sub".

The error message is definitely correct, because it seems like Entity Framework Core erroneously thinks, that Super inherits from Sub, which it obviously does not.

The exception is thrown before invocation of OnModelCreating in my DbContext takes place.

I receive this exception:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The entity type 'Super' cannot inherit from 'Sub' because 'Super' is not a descendant of 'Sub'.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.HasBaseType(EntityType newBaseType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasBaseType(EntityType baseEntityType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.DiscriminatorBuilder.HasValue(InternalEntityTypeBuilder entityTypeBuilder, Object value, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.DiscriminatorBuilder.Microsoft.EntityFrameworkCore.Metadata.Builders.IConventionDiscriminatorBuilder.HasValue(IConventionEntityType entityType, Object value, Boolean fromDataAnnotation)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.DiscriminatorConvention.ProcessEntityTypeBaseTypeChanged(IConventionEntityTypeBuilder entityTypeBuilder, IConventionEntityType newBaseType, IConventionEntityType oldBaseType, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnEntityTypeBaseTypeChanged(IConventionEntityTypeBuilder entityTypeBuilder, IConventionEntityType newBaseType, IConventionEntityType previousBaseType)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor.VisitOnBaseEntityTypeChanged(OnEntityTypeBaseTypeChangedNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeBaseTypeChangedNode.Accept(ConventionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(ConventionNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Dispose()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelInitialized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelInitialized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model..ctor(ConventionSet conventions)
   at Microsoft.EntityFrameworkCore.ModelBuilder..ctor(ConventionSet conventions)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)
```

The error message gives me the idea, that you have swapped the argument for current type and base type somewhere in some convention dealing with discriminators. I mean, that instead of verifying, that Sub is a specialization of Super, you by mistake verify, if Super is a specialization of Sub, which is obviously never the case.

<!--

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET Core 3.1)
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.4

**Comment by ErikEJ** [comment] 2020-02-10 06:12
Please share your code

**Comment by henrikdahl8240** [comment] 2020-02-12 10:59
It would obviously be quite reasonable to do that. My entity model is huge and it is not easy to isolate the problem.

In my case I could compensate for the problem by adding four DbSet properties to my DbContext. All four DbSet properties are defined for abstract entity types.

In my opinion, DbSet properties should not make any semantical impact except being roots/entry points for the persistent object model.

All four entity types have one or more abstract base types. These abstract base types all have navigation properties to other entity types.

I also had to add two explicit builder.HasBaseType<...>() invocations for concrete entity types because the convention made them to have the abstract grandfather as their base type and not their abstract father. In both cases, the entities which needed an invocation of HasBaseType<...>() have one sibling each, which were resolved with the correct base type!! I think this is a worrying asymmetry, which further indicates errors in Entity Framework Core. I have spent time making some code which could compare the base type of the clr type and the base entity type, so I could find these mistakes of Entity Framework Core and compensate them by my own invocations of HasBaseType<...>(), which overrid the result of the convention from a previous step in the process.

It is my perception, that perhaps the algorithm resolving entity types does not resolve correctly as the graph to resolve becomes cyclical. Traversing the class model along navigation properties obviously easily becomes cyclical.

Therefore I dare to conclude, that there are indeed errors in resolving the entity types by the conventions of Entity Framework Core 3.1.1.

Please allow me to mention, that I have earned a master's degree in Computer Science from Aarhus University, Denmark, and I know perfectly well, what I am doing.

If somebody responsible at Microsoft has a reasonable suggestion for something I could check, you are welcome to suggest that.

**Comment by ajcvickers** [comment] 2020-02-12 23:51
@henrikdahl8240 

> In my opinion, DbSet properties should not make any semantical impact except being roots/entry points for the persistent object model.

The reason for this is that there is a difference between:
* A base type shared by multiple entity types but which is not itself part of the database mapping--usually referred to as an unmapped base type. All entity types have an unmapped base type--it's often `System.Object` but it can be something else.
* A base type that is mapped into the TPH hierarchy.

This is relevant because `DbSet<TEntity>` is one way to tell EF to map a type. This means a type may change from an unmapped base type to a typed mapped in the TPH hierarchy when a DbSet property is introduced for it.

> I also had to add two explicit builder.HasBaseType<...>()

Typically the only use case of `HasBaseType` is to set the base type to null. If there is a case where it is needed for other situations, then this is likely a bug--if we can get code to reproduce it then we will investigate.

> Therefore I dare to conclude, that there are indeed errors in resolving the entity types by the conventions of Entity Framework Core 3.1.1.

From your description it sounds like this is indeed the case. However, unless we are able to reproduce these errors that is little we can do to fix them. Attempting to guess the specific model configuration that causes this would be futile. This is why we ask for code that we can run to reproduce the issue.

**Comment by ajcvickers** [comment] 2020-02-21 17:34
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by henrikdahl8240** [comment] 2020-03-09 07:46
@ajcvickers I would suggest you to reopen this issue using the solution which I sent you on March 6. 2020 13:46?

The mail details the few steps you should go through.

The mail includes the precise steps for reproducing this problem.

**Comment by cesarsouza** [comment] 2020-04-13 07:16
I also ran into the same problem. Adding three DbSets for extra types, including one abstract, helped solve the issue.

**Closed** 2022-10-16 18:10 UTC
Labels: closed-could-not-reproduce, customer-reported
