### ISSUE TITLE
Changes are not applied in correct order if put in via DbContext.Entry<TEntity> method

### ISSUE THREAD

**Issue by DanielTipo** [dotnet/efcore#5192] opened 2016-04-27 13:33 UTC
If changes put in via DbContext.Entry<TEntity> method, the order given by DbContext.ChangeTracker.Entries() and the order of the generated scripts on trace log are not the same. On delete it gives foreign key constraint error because it wants to delete the last item in the list which is obviously the entity referenced by the other entities.

**Comment by rowanmiller** [comment] 2016-04-28 18:03
EF does not maintain the order of operations as they were applied via the API... but we do a topological sort to ensure they are applied in an order that will succeed. Sounds like you are hitting a bug in the sort algorithm. Can you share a complete code listing that we can run to reproduce the issue you are seeing.

**Comment by rowanmiller** [comment] 2016-05-04 18:09
**EF Team Triage: ** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 09:38 UTC
