### ISSUE TITLE
Stop using <inheritdoc />

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22894] opened 2020-10-05 22:10 UTC
Docs team has confirmed that it is not supported.

**Comment by roji** [comment] 2020-10-06 15:52
See note in https://github.com/dotnet/efcore/pull/22765#issuecomment-704372254

**Comment by ajcvickers** [comment] 2020-11-25 22:31
Loop back in a few months just in case support gets added by the docs team.

**Comment by AndriySvyryd** [comment] 2021-02-24 01:03
Anti-dupe of: https://github.com/dotnet/efcore/issues/18003

**Comment by roji** [comment] 2021-02-24 08:23
Anti-dupe!

**Comment by roji** [comment] 2021-03-12 15:28
<inheritdoc /> is now supported, so we should close this.

**Closed** 2022-10-16 19:03 UTC
Labels: closed-out-of-scope, area-docs
