### ISSUE TITLE
Incorrect SQL generated when counting number of groups with a where clause.

### ISSUE THREAD

**Issue by TylerDM** [dotnet/efcore#12630] opened 2018-07-11 14:10 UTC
When attempting to count the number of groups meeting certain criteria EF will return the number of rows in the first group instead.  This appears to be due to incorrect SQL generation.

```
(
  from x in _dbContext.Tasks
  where
    x.Assignee_ID == user.ID &&
    x.Done != null
  group x by((DateTime) x.Done).Date into y
  where y.Count() > threshold
  select y
).CountAsync();
```

Which should return a single number, the count of groups.  But instead it generates this SQL code.

```
exec sp_executesql N'SELECT COUNT(*)
FROM [Tasks] AS [x]
WHERE ([x].[Assignee_ID] = @__user_ID_0) AND [x].[Done] IS NOT NULL
GROUP BY CONVERT(date, [x].[Done])
HAVING COUNT(*) > @__threshold_1',N'@__user_ID_0 uniqueidentifier,@__threshold_1 int',@__user_ID_0='1E7A6ED5-B313-4126-976B-B7D9792D75DA',@__threshold_1=500
```

Which returns

```
304
463
301
```

EF then returns 304 instead of 3.  Running the same C# code but replacing CountAsync() with.Select(y => y.Count().ToListAsync() returns the 3 numbers as expected.  If anyone else is hung on this issue I suggest working around temporarily by using .Select(y => y.Count()).ToListAsync().ContinueWith(x => x.Result.Count()).

I'm using latest everything so EF Core 2.1.1 and .Net Core 2.1.  This is my first time reporting an issue so I apologize if I've made any mistakes; upon notice I will rectify them promptly.

**Comment by divega** [comment] 2018-07-11 19:17
@maumar can you please find the duplicate?

**Comment by smitpatel** [comment] 2018-07-11 23:06
Duplicate of #12351

**Closed** 2022-10-16 13:18 UTC
Labels: closed-duplicate, customer-reported
