### ISSUE TITLE
Is there way to create database procedure from C#

### ISSUE THREAD

**Issue by torgashov** [dotnet/efcore#33979] opened 2024-06-13 08:00 UTC
Hello!
Is there way to create database procedure from C#, using ef core linq queries?
May be some this like:

string GetUserAppCode(Models.CatalogDbContext ctx, long userId)
{
     return ctx.UserInApps.First(u => u.UserId == userId).AppCode;
}

Is there any way to create database procedure for this method from C# code?

**Comment by roji** [comment] 2024-06-13 09:02
Duplicate of #33978

**Comment by roji** [comment] 2024-06-13 09:04
@torgashov you can create a SQL function in your database via the normal means (CREATE FUNCTION ...), based on the specific database you're using; at that point you'll be defining your function via SQL, not LINQ. Once your function is set up, you can map the function with EF using [user-defined function mapping](https://learn.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping).

**Comment by torgashov** [comment] 2024-06-13 09:11
Thank you for answer.

**Closed** 2024-06-13 09:15 UTC
Labels: customer-reported
