### ISSUE TITLE
Filtered Include for Reference Property

### ISSUE THREAD

**Issue by 6bee** [dotnet/efcore#33982] opened 2024-06-13 10:27 UTC
## The problem I'm trying to solve

Eager loading reference properties should allow conditions similar to what's possible via [filtered include](https://learn.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include) for _collection navigation_ properties.

Up to current latest version (9.0.0-preview.5.24306.3) the following query/linq expression
```
[EntityQueryRootExpression].Include(child => IIF((child.Parent.Condition == true), child.Parent, null))
```
throws
```
InvalidOperationException : The expression 'IIF((child.Parent.Condition == true), child.Parent, null)' is invalid inside an 'Include' operation ...
```

## The solution I'd like

I'd like to be able to define a condition for a navigation property to be loaded:
```C#
// either [probably not great from an API's perspective]
ctx.Children.Include(child => child.Parent.Condition == true ? child.Parent : null)
// or
ctx.Children.Include(child => child.Parent, parent => parent.Condition == true)
```

What's more, filtered include should allow for complex conditions potentially composed of subqueries. 
```C#
var userName = "testuser";
ctx.Children.Include(
  child => child.Parent, 
  parent => ctx.Grants.Any(grant => grant.Username == userName && grant.EntityId == parent.Id));
```

**Comment by roji** [comment] 2024-06-13 11:00
Duplicate of #24422

**Closed by roji** 2024-06-13 11:00 UTC
Labels: customer-reported, area-query
