### ISSUE TITLE
the problem about sub table

### ISSUE THREAD

**Issue by wangligen1995** [dotnet/efcore#19551] opened 2020-01-10 03:29 UTC
ef core，how to meet the sub table，we need user 100 tables to save different user information.
I need help

**Comment by ajcvickers** [comment] 2020-01-10 23:47
@wangligen1995 Please provide more details. It's very hard to help without specifics of exactly what you are trying to do.

**Comment by ajcvickers** [comment] 2020-01-17 17:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:05 UTC
Labels: closed-could-not-reproduce, customer-reported
