### ISSUE TITLE
Issue with IMaterializationInterceptor Using Complex Types

### ISSUE THREAD

**Issue by melihorhan** [dotnet/efcore#32806] opened 2024-01-13 10:11 UTC
### Description:

I've encountered a bug in `EF Core 8.0(8.1)` related to the use of complex types and the `IMaterializationInterceptor` interface. The problem arises when implementing a class with the `IMaterializationInterceptor` interface in a project using complex types.

### Steps to Reproduce:

1. Create an entity with a complex type property and configure it as necessary. This works as expected without issues.
2. Implement a class with the `IMaterializationInterceptor` interface and add it to the EF Core configuration.

#### Expected Behavior:

The application should run without errors, allowing the interception of entity materialization while using complex types.

#### Actual Behavior:

Upon adding the IMaterializationInterceptor implementation, an error occurs stating: `Expression of type 'Microsoft.EntityFrameworkCore.Metadata.RuntimeComplexType' cannot be used for constructor parameter of type 'Microsoft.EntityFrameworkCore.Metadata.IEntityType' (Parameter 'arguments[1]')`.

### Example code:

Attached is a minimal C# console project that demonstrates the issue

[ComplexTypeWithIMaterializationInterceptor.zip](https://github.com/dotnet/efcore/files/13927645/ComplexTypeWithIMaterializationInterceptor.zip)

Here is a simplified version of the code to illustrate the setup:

```C#
public class Customer : IHasRetrieved
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;
    public string? PhoneNumber { get; set; }
    [NotMapped]
    public DateTime Retrieved { get; set; }
    public Address Address { get; set; }
}

[ComplexType]
public class Address
{
    public required string Line1 { get; set; }
    public string? Line2 { get; set; }
    public required string City { get; set; }
    public required string Country { get; set; }
    public required string PostCode { get; set; }
}

public interface IHasRetrieved
{
    DateTime Retrieved { get; set; }
}

public class CustomerContext : DbContext
{
    public CustomerContext(DbContextOptions<CustomerContext> options) : base(options)
    {
    }

    private static readonly SetRetrievedInterceptor _setRetrievedInterceptor = new();

    public DbSet<Customer> Customers => Set<Customer>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>().ToTable("Customer");
        base.OnModelCreating(modelBuilder);
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) 
        => optionsBuilder.AddInterceptors(_setRetrievedInterceptor);
}

public class SetRetrievedInterceptor : IMaterializationInterceptor
{
    public object InitializedInstance(MaterializationInterceptionData materializationData, object instance)
    {
        if (instance is IHasRetrieved hasRetrieved)
        {
            hasRetrieved.Retrieved = DateTime.UtcNow;
        }

        return instance;
    }
}

```

#### Additional Context:

This issue seems to be specifically related to the integration of IMaterializationInterceptor with entities containing complex type properties in EF Core 8.0(8.1).

### Stack trace

Here is the stack trace for the exception:

```
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Dynamic.Utils.ExpressionUtils.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments, String methodParamName)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityMaterializerSource.CreateInterceptionMaterializeExpression(ITypeBase structuralType, HashSet`1 properties, IMaterializationInterceptor materializationInterceptor, ParameterBindingInfo bindingInfo, Expression constructorExpression, ParameterExpression instanceVariable, List`1 blockExpressions)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityMaterializerSource.CreateMaterializeExpression(EntityMaterializerSourceParameters parameters, Expression materializationContextExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityMaterializerSource.AddInitializeExpressions(HashSet`1 properties, ParameterBindingInfo bindingInfo, Expression instanceVariable, List`1 blockExpressions)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityMaterializerSource.<CreateInterceptionMaterializeExpression>g__CreateInitializeExpression|27_1(<>c__DisplayClass27_0& )
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityMaterializerSource.CreateInterceptionMaterializeExpression(ITypeBase structuralType, HashSet`1 properties, IMaterializationInterceptor materializationInterceptor, ParameterBindingInfo bindingInfo, Expression constructorExpression, ParameterExpression instanceVariable, List`1 blockExpressions)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityMaterializerSource.CreateMaterializeExpression(EntityMaterializerSourceParameters parameters, Expression materializationContextExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.EntityMaterializerInjectingExpressionVisitor.CreateFullMaterializeExpression(ITypeBase concreteTypeBase, ValueTuple`4 materializeExpressionContext)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.EntityMaterializerInjectingExpressionVisitor.MaterializeEntity(StructuralTypeShaperExpression shaper, ParameterExpression materializationContextVariable, ParameterExpression concreteEntityTypeVariable, ParameterExpression instanceVariable, ParameterExpression entryVariable)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.EntityMaterializerInjectingExpressionVisitor.ProcessEntityShaper(StructuralTypeShaperExpression shaper)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.EntityMaterializerInjectingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.EntityMaterializerInjectingExpressionVisitor.Inject(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.InjectEntityMaterializers(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ProcessShaper(Expression shaperExpression, RelationalCommandCache& relationalCommandCache, IReadOnlyList`1& readerColumns, LambdaExpression& relatedDataLoaders, Int32& collectionId)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQuery(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in C:\Users\melih\source\repos\ComplexTypeWithIMaterializationInterceptor\ComplexTypeWithIMaterializationInterceptor\Program.cs:line 27
```

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system:
IDE: Visual Studio 2022 17.8.3

**Comment by ajcvickers** [comment] 2024-01-13 10:45
Duplicate of #31353, for which I am working on a PR.

**Closed** 2024-01-17 09:33 UTC
Labels: closed-duplicate, customer-reported
