### ISSUE TITLE
Delete an entity that contains a dependent property (value object)

### ISSUE THREAD

**Issue by paulo673** [dotnet/efcore#24398] opened 2021-03-15 04:53 UTC
I need to delete an entity that contains a value object that is also being shared in another entity

```C#
  public void Configure(EntityTypeBuilder<Parada> builder)
        {
            builder.Property(x => x.Nome).IsRequired();

            builder.OwnsOne(x => x.Localizacao, y => {
                y.Property(x => x.Latitude).HasColumnName(nameof(Localizacao.Latitude)).IsRequired();
                y.Property(x => x.Longitude).HasColumnName(nameof(Localizacao.Longitude)).IsRequired();
            });
        }
```

```
The association between entities 'Parada' and 'Parada.Localizacao#Localizacao' with the key value '{ParadaId: 7}' has been severed, but the relationship is either marked as required or is implicitly required because the foreign key is not nullable. If the dependent/child entity should be deleted when a required relationship is severed, configure the relationship to use cascade deletes.
```

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment] 2021-03-15 16:19
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2021-03-23 15:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:27 UTC
Labels: closed-could-not-reproduce, customer-reported
