### ISSUE TITLE
Interceptors registering

### ISSUE THREAD

**Issue by MursalovAltun** [dotnet/efcore#22043] opened 2020-08-13 08:55 UTC
Setting CreatedAt, ModifiedAt, CreatedBy not using the SaveChanges() method override.
I would like to implement this the way that doesn't break Open-Closed SOLID principle.

To implement these events [#15910](https://github.com/dotnet/efcore/issues/15910) also as interceptors.
Allow registering interceptor for specific DbContext using DI separated from the AddDbContext<T>(DbContextOptionsBuilder).

**Comment by ajcvickers** [comment] 2020-08-13 18:28
Duplicate of #21578

**Closed** 2022-10-16 18:36 UTC
Labels: customer-reported
