### ISSUE TITLE
Bug when use HashSet<T> in constructor collection entity

### ISSUE THREAD

**Issue by coderstrong** [dotnet/efcore#22326] opened 2020-08-31 08:43 UTC
Sorry my english is not good.

### Steps to reproduce

``` C#
public class Review
 {
    public Review()
    {
      ReviewDetails = new HashSet<ReviewDetail>();
    }
    public long Id { get; set; }
    public Guid GuiId { get; set; }
    public string Title { get; set; }
    public virtual ICollection<ReviewDetail> ReviewDetails { get; set; }
}

var review = db.Review.Where(x => x.Id == 1).FirstOrDefault();
if(review != null)
{
  review.ReviewDetails.Add(newReviewDetail);
}
```
When I add new Review include ReviewDetail is no issue
But I add new ReviewDetail on existed Review  on database Review system crash

I have try fix error by change code in constructor. It worked
```C#
ReviewDetails = new List<ReviewDetail>();
```
Why use `HashSet` code isn't work. Some one tell me root cause please?

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 or Docker Image 3.1
IDE: Visual Studio 2019 Version 16.5.4

**Comment by ashoka250** [comment] 2020-08-31 12:16
In this particular use-case scenario you can use simple list.

**Comment by smitpatel** [comment] 2020-08-31 17:51
@coderstrong - I am not able to reproduce this based on information provided. There are also few discrepancies like you are using Guid keys in your class but in the query it is integer. Please share a complete runnable repro code which demonstrate the issue you are seeing.

**Comment by ajcvickers** [comment] 2020-09-11 15:34
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:38 UTC
Labels: closed-could-not-reproduce, customer-reported
