### ISSUE TITLE
distinct not emitted in sql when selecting a declared type

### ISSUE THREAD

**Issue by tschmit** [dotnet/efcore#7699] opened 2017-02-23 22:06 UTC
The distinct is **not translated** into sql when used after a `Select(x => new Type {})`.
The distinct is well translated with an anonymous type `Select(x => new {})`.

### Steps to reproduce

```c#
public class ThirdParty {
    public int ThirdPartyId { get; set; }
    public string Name { get; set; }
    public string NormalizedName { get; set; }
}

public class MyDataContext : DbContext {
    public DbSet<ThirdParty> ThirdParties { get; set; }
}

public class DTOTP {
    public String NormName { get; set; }
}

//The following fails: no distinct in the sql query (no effect at all in fact, distinct is totally ignored)
return _ctx.ThirdParties.Where(x => (x.NormalizedName ?? x.Name).Contains(qName)).
                Select(x => new DTOTP { NormName = x.NormalizedName ?? x.Name }).
                Distinct().
                OrderBy(x => x.NormName).ToList();

//The following runs: Distinct() is translated in the sql query emitted
return _ctx.ThirdParties.Where(x => (x.NormalizedName ?? x.Name).Contains(qName)).
                Select(x => new { NormName = x.NormalizedName ?? x.Name }).
                Distinct().
                OrderBy(x => x.NormName).ToList().
                Select(x => new DTOTP { NormName = x.NormName }).ToList();
```

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: windows 10
IDE: Visual Studio 2015

**Comment by smitpatel** [comment] 2017-02-23 22:34
dupe of #7234

**Closed** 2022-10-16 10:54 UTC
Labels: closed-duplicate
