### ISSUE TITLE
Sqlite migrations: table rebuild with spatial column errors out

### ISSUE THREAD

**Issue by d79ima** [dotnet/efcore#28384] opened 2022-07-06 20:03 UTC
**Description**
I am using EF Core 6.0,6 targeting SQLite.
I have a simple table with a few columns, including a GEOMETRY column for which i am using NetTopologySuite 6.0.6 to match EF Core version.
If i create a migration where i drop one of the regular (non-Geometry) columns, and try to create a database, will get an error with the following message: 
Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'table ef_temp_MyTableName has no column named MyGeometryColumnName'.

If i perform the same drop column migration on a table that has no Geometry columns, then it has no problems.

**System Configuration**
- NetTopologySuite version: 6.0.6
- Environment: Windows 10x64
- .NET Framework version: 6.0

[TestEFCoreFeatures.zip](https://github.com/dotnet/efcore/files/9057710/TestEFCoreFeatures.zip)

**Comment by d79ima** [comment] 2022-07-07 13:33
For now workaround is to remove the Geometry column together with the other column that actually needs to be dropped in the same migration, then create a second migration to add the Geometry column back in

**Comment by ajcvickers** [comment] 2022-07-09 18:09
Note from triage: cannot find any duplicate.

**Comment by bricelam** [comment] 2022-07-09 18:22
Duplicate of #25116

**Closed** 2022-07-09 18:27 UTC
Labels: customer-reported
