### ISSUE TITLE
How to avoid to mark as unchanged and later to modified because of a unique constrain?

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#19655] opened 2020-01-21 11:22 UTC
I have a table that has a unique constrain for two fields, (IDParent, positionInParent).

```
Parent
{
    IDParent;
}

Child
{
    IDChild;
    IDParent;
    PositionInParent;
}
```

I can only have a child in a position, and I want that when I delete a child, the childs with position +1 is change to position -1, to don't have gaps.

The problem is that when I save the changes in the dataContext, because EF not ensure the order of the operations, so I get an exception because of the unique constrain, it seems that the update of the affected childs is done before updating the deleted child.

So I am doing this, that it works, but I wonder if there is a better way to solve this problem:

    Change the state of affeted childs to unchanged.
    Save changes, so the delete child is marked as deleted.
    Change the state to affected childs to modified.
    Save changes again.

But this makes me to an extra save changes and also to use two loops to change the state of the affected childs.

Is this the unique way or there are a better way to do that?

I am using EF Core 3.0.

Thanks.

**Comment by ajcvickers** [comment] 2020-01-21 23:49
@ComptonAlvaro Can you show the code that configures the unique index in EF?

**Comment by ajcvickers** [comment] 2020-01-28 17:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:07 UTC
Labels: closed-could-not-reproduce, customer-reported
