### ISSUE TITLE
SqliteConnection Open() always throws NullRefEx.

### ISSUE THREAD

**Issue by Michal-MK** [dotnet/efcore#18827] opened 2019-11-09 15:40 UTC
### To Reproduce

Create a new Project, download the Mcrosoft.Data.Sqlite nuget pacakage, in Main() put this

ConnectionString taken from [https://www.connectionstrings.com/sqlite/](url)
```C#
SqliteConnection conn = new SqliteConnection("Data Source=./data.db");
conn.Open();
```

StackTrace:
```
   at SQLitePCL.raw.sqlite3_open_v2(String filename, sqlite3& db, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at PlaygroundFramework.Program.Main(String[] args) in 
   D:\Repositories\PlaygroundFramework\PlaygroundFramework\Program.cs:line 13
```

It has to be something trivial, because google does not find anything... or I am bad at searching

### Additional context

Microsoft.Data.Sqlite version: 3.0.0 stable
Target framework: .NETFramework 4.7.2
Operating system: Win-10 64bit

Thanks

**Comment by ajcvickers** [comment] 2019-11-11 17:21
@Michal-MK Please post a small project/solution that reproduces what you are seeing. This will allow us to investigate if it is a specific platform or some other configuration that might be causing this.

**Comment by Michal-MK** [comment] 2019-11-11 17:40
https://drive.google.com/open?id=1UCAYtXLEtDEoqMyIhaTNW5cS1adiuCBC

It is just an empty project with added nuget package and the 2 lines mentioned above.

**Comment by ajcvickers** [comment] 2019-11-11 23:13
@Michal-MK Your project is referencing `Microsoft.Data.Sqlite.Core`, which also requires work to setup [which native SQLite library to use](https://github.com/ericsink/SQLitePCL.raw).

For an easier experience, reference [`Microsoft.Data.Sqlite`](https://www.nuget.org/packages/Microsoft.Data.SQLite) which pre-configures the SQLite to use.

@ericsink Any ideas on why the exception isn't more helpful here? Is there something we should be doing differently?

/cc @bricelam

**Comment by Michal-MK** [comment] 2019-11-12 07:54
I get the same exception when I reference the non Core nuget package as well I believe. Can't test now. Is that one supposed to work out of the box?

**Comment by ericsink** [comment] 2020-03-03 00:07
Ouch!  Somehow I didn't catch it when I got tagged above. MONTHS AGO.

Sorry.

**Comment by bricelam** [comment] 2020-03-03 16:56
Duplicate of https://github.com/ericsink/SQLitePCL.raw/issues/324

**Closed** 2022-10-16 14:55 UTC
Labels: closed-external
