### ISSUE TITLE
Nullable enum property always detected as alter column operation in migration

### ISSUE THREAD

**Issue by LeroyK** [dotnet/efcore#11630] opened 2018-04-11 14:29 UTC
Nullable enum properties always result in an alter column migration operation every time you create a new migration.

### Steps to reproduce
Use the following code and create two migrations subsequently.

```c#
class Program
{
    public const string ConnectionString = "Server=.\\SQLEXPRESS;Database=Test_Design;Trusted_Connection=True;MultipleActiveResultSets=true";

    static void Main(string[] args) { }

    public class TestDesignTimeDbContextFactory : IDesignTimeDbContextFactory<TestDbContext>
    {
        public TestDbContext CreateDbContext(string[] args) => new TestDbContext(new DbContextOptionsBuilder<TestDbContext>().UseSqlServer(ConnectionString).Options);
    }

    public class TestDbContext : DbContext
    {
        public TestDbContext(DbContextOptions options) : base(options) { }
        protected TestDbContext() { }

        public DbSet<Example> Examples { get; set; }
    }

    public class Example
    {
        [Key]
        public int Id { get; set; }

        public ExampleStatus? Status { get; set; }
    }

    public enum ExampleStatus : int
    {
        Inactive = 0,
        Active = 1,
    }
}
```

The second migration should be empty, but contains:
```c#
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.AlterColumn<int>(
        name: "Status",
        table: "Examples",
        nullable: true,
        oldClrType: typeof(int));
}

protected override void Down(MigrationBuilder migrationBuilder)
{
    migrationBuilder.AlterColumn<int>(
        name: "Status",
        table: "Examples",
        nullable: false,
        oldClrType: typeof(int),
        oldNullable: true);
}
```

### Further technical details
EF Core version: 2.1.0-preview2-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 x64
IDE: Visual Studio 2017 15.6.2

**Comment by bricelam** [comment] 2018-04-11 19:54
Duplicate of #11297

Fixed in [the nightly builds](https://dotnet.myget.org/gallery/aspnetcore-dev)

**Closed** 2022-10-16 12:18 UTC
