### ISSUE TITLE
Add resource removal to ChangeTracking

### ISSUE THREAD

**Issue by Mr0N** [dotnet/efcore#29116] opened 2022-09-15 18:35 UTC
I suggest adding such a pattern to EF Core to remove unnecessary resources from ChangeTracker

```
using System;
using Microsoft.EntityFrameworkCore;

//Example Use
var myDb = new MyDbContext();
using var info = new Info();
myDb.AddInfo(info);
myDb.SaveChanges();

class MyDbContext:DbContext 
{
    public DbSet<Info> information { set; get; }
    public void AddInfo(Info info)
    {
        if(info is IChangeTrackingDispose<Info> change)
        {
            change.SetDbSet(information);
        }
        information.Add(info);
    }
}
public class Info : IChangeTrackingDispose<Info>
{
    public int Id {set;get;}
    public DbSet<Info> _dbSet { set; get; }

    public void Dispose()
    {
        (this as IChangeTrackingDispose<Info>).Close();
    }
}

interface IChangeTrackingDispose<T>:IDisposable where T : class
{

    DbSet<T> _dbSet { set; get; }
    public void SetDbSet(DbSet<T> dbSet)
    {
        _dbSet = dbSet;
    }
    private void RemoveFromChangeTraking()
    {
        ///The logic for removing this instance from Change Tracking
    }
    public void Close()
    {
        RemoveFromChangeTraking();
    }

}
```

**Comment by ajcvickers** [comment] 2022-09-16 10:57
@Mr0N Leaving implementation details aside, this doesn't align with [guidance for using the ChangeTracker](https://docs.microsoft.com/en-us/ef/core/change-tracking/).

**Comment by Mr0N** [comment] 2022-09-16 12:42
> @Mr0N Leaving implementation details aside, this doesn't align with [guidance for using the ChangeTracker](https://docs.microsoft.com/en-us/ef/core/change-tracking/).

Well, this is just an example of how it can be done, can you remove the punk that does not fit?

**Comment by Mr0N** [comment] 2022-09-16 15:31
> > @Mr0N Leaving implementation details aside, this doesn't align with [guidance for using the ChangeTracker](https://docs.microsoft.com/en-us/ef/core/change-tracking/).
> 
> Well, this is just an example of how it can be done, can you remove the punk that does not fit?

*you can show the point under which this idea does not fit

**Comment by ajcvickers** [comment] 2022-09-16 16:51
@Mr0N Detaching instances from the change tracker should only be very rarely needed. Instead, a DbContext should be created for each unit-of-work and then disposed.

**Comment by Mr0N** [comment] 2022-09-16 17:22
> DbContext

After Dispose ,DbContext, tcp connection will be closed?

**Comment by ajcvickers** [comment] 2022-09-16 18:37
> After Dispose ,DbContext, tcp connection will be closed?

These are unrelated concepts.

**Comment by Mr0N** [comment] 2022-09-16 18:38
![image](https://user-images.githubusercontent.com/61237140/190708007-c961625d-395c-4751-8c76-21e1ab7f6d4b.png)
And if you don't know how much data will be recorded?
And if we assume that files are recorded in the database and it is not clear what size the files are, for example, can the file be 2 megabytes, or can it be 2 gigabytes? It is not easy to delete such a file from memory
If you need to add 1000 objects, and you want them to be immediately recorded in the database? Because if they remain in memory, then it is a misuse of resources
Thai C# is not C++, it has a programming concept in which you don't need to keep track of memory usage, and the DbContext class doesn't really follow that concept.

**Comment by Mr0N** [comment] 2022-09-16 18:39
> > After Dispose ,DbContext, tcp connection will be closed?
> 
> These are unrelated concepts.

Why am I creating a new context, thereby wasting time creating a new connection?

**Comment by ajcvickers** [comment] 2022-09-16 18:42
The garbage collector will collect memory as appropriate.

> Why am I creating a new context, thereby wasting time creating a new connection?

Connection pooling means creating connections is cheap. Or you can use a new context with the same connection.

**Comment by Mr0N** [comment] 2022-09-16 18:45
> The garbage collector will collect memory as appropriate.
> 
> > Why am I creating a new context, thereby wasting time creating a new connection?
> 
> Connection pooling means creating connections is cheap. Or you can use a new context with the same connection.

it won't work if the context is a singleton and you'll load a million objects there, it's checked, it's a memory leak for me

yes, it's good when all this is used in ASP, and when you need a couple of lines of code, there are no pools, what to do then

**Comment by ajcvickers** [comment] 2022-09-16 18:47
> context is a singleton 

The DbContext should not be a singleton.

**Comment by ajcvickers** [comment] 2022-09-16 18:50
There is no memory leak if used appropriately.

**Comment by Mr0N** [comment] 2022-09-16 18:53
> There is no memory leak if used appropriately.

Well, let's present this logic, there is an api for uploading files, one point accepts 10 files, each file takes 1 megabyte, there are 1000 users, each user uploads 10 files at the same time, if resources could be destroyed, then there would be 1000 in memory files, and if so, then there will be 10 thousand files in the memory, 10 times more than the memory needs

**Comment by ajcvickers** [comment] 2022-09-16 18:54
Then treat each file as a single unit-of-work.

**Comment by roji** [comment] 2022-09-16 18:56
@Mr0N in case you're not aware, EF supports [context pooling](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#dbcontext-pooling) (importantly, this is orthogonal to database connection pooling). This allows you to get a DbContext instance for each unit-of-work (e.g. each file upload) with almost no overhead.

**Comment by Mr0N** [comment] 2022-09-16 18:56
> Then treat each file as a single unit-of-work.

This requires much more code than using

**Comment by Mr0N** [comment] 2022-09-16 18:57
> Then treat each file as a single unit-of-work.

and many more resources

**Comment by Mr0N** [comment] 2022-09-16 18:58
> @Mr0N in case you're not aware, EF supports [context pooling](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#dbcontext-pooling) (importantly, this is orthogonal to database connection pooling). This allows you to get a DbContext instance for each unit-of-work (e.g. each file upload) with almost no overhead.

yes cool I understood it) earlier, but DbContext is not only used in ASP

**Comment by ajcvickers** [comment] 2022-09-16 18:58
> and many more resources

This is not true.

> This requires much more code than using

As they like to say in police procedurals, "that's the job."

**Comment by ajcvickers** [comment] 2022-09-16 18:59
> yes cool I understood it) earlier, but DbContext is not only used in ASP

Context pooling works anywhere.

**Comment by Mr0N** [comment] 2022-09-16 19:10
> > yes cool I understood it) earlier, but DbContext is not only used in ASP
> 
> Context pooling works anywhere.

And if the object is taken from the pool and objects of unknown size are pushed into it somewhere? That is, the object can be 2 kilobytes, or maybe 2 gigabytes, it is not clear what to do, creating a new contest for an object that occupies 2 kilobytes is probably not very good, but for 2 a gigabyte is needed, as if it turns out that the program is going into the red in terms of speed

**Comment by Mr0N** [comment] 2022-09-16 19:11
> > > yes cool I understood it) earlier, but DbContext is not only used in ASP
> > 
> > 
> > Context pooling works anywhere.
> 
> And if the object is taken from the pool and objects of unknown size are pushed into it somewhere? That is, the object can be 2 kilobytes, or maybe 2 gigabytes, it is not clear what to do, creating a new contest for an object that occupies 2 kilobytes is probably not very good, but for 2 a gigabyte is needed, as if it turns out that the program is going into the red in terms of speed

Destruction of resources would solve this problem very well

**Comment by roji** [comment] 2022-09-16 19:17
@Mr0N I think you need to read up on some of the EF concepts being discussed here.

>> Context pooling works anywhere.
>
> And if the object is taken from the pool and objects of unknown size are pushed into it somewhere? That is, the object can be 2 kilobytes, or maybe 2 gigabytes, it is not clear what to do, creating a new contest for an object that occupies 2 kilobytes is probably not very good, but for 2 a gigabyte is needed, as if it turns out that the program is going into the red in terms of speed

The thing that gets pooled in context pooling is the context; any data tracked by it is released when the context is returned to the pool, so that it becomes eligible for reclaiming by the GC.

**Comment by Mr0N** [comment] 2022-09-16 19:20
> 

It's cool, only it still needs to be returned, and besides, there may be a possible memory leak in it

**Comment by Mr0N** [comment] 2022-09-16 19:21
> @Mr0N I think you need to read up on some of the EF concepts being discussed here.
> 
> > > Context pooling works anywhere.
> > 
> > 
> > And if the object is taken from the pool and objects of unknown size are pushed into it somewhere? That is, the object can be 2 kilobytes, or maybe 2 gigabytes, it is not clear what to do, creating a new contest for an object that occupies 2 kilobytes is probably not very good, but for 2 a gigabyte is needed, as if it turns out that the program is going into the red in terms of speed
> 
> The thing that gets pooled in context pooling is the context; any data tracked by it is "released" (unreferenced) when the context is returned to the pool, so that it becomes eligible for reclaiming by the GC. That is how a GC-based language works.

It's cool, only it still needs to be returned, and besides, there may be a possible memory leak in it

**Comment by roji** [comment] 2022-09-16 19:37
> only it still needs to be returned

If you're referring to the GC reclaiming the unreferenced memory, then that's how .NET works, and it's completely unrelated to EF, DbContext pooling, etc. Any code your write will do the same. In other words, your manual logic to remove from change tracking will also not reduce memory immediately, until the GC decides to reclaim it.

> there may be a possible memory leak in it

There's no memory leak, unless there's a bug in EF (which we would fix). Many production applications are using short-lived context with the unit-of-work pattern - with and without context pooling - and are doing so successfully.

**Comment by Mr0N** [comment] 2022-09-16 19:44
> > only it still needs to be returned
> 
> If you're referring to the GC reclaiming the unreferenced memory, then that's how .NET works, and it's completely unrelated to EF, DbContext pooling, etc. Any code your write will do the same. In other words, your manual logic to remove from change tracking will also not reduce memory immediately, until the GC decides to reclaim it.
> 
> > there may be a possible memory leak in it
> 
> There's no memory leak, unless there's a bug in EF (which we would fix). Many production applications are using short-lived context with the unit-of-work pattern - with and without context pooling - and are doing so successfully.

Well, I don’t know, if you add 20,000 objects to one context and there are no forces on them anywhere in the program, then the garbage collector will not delete these objects

**Comment by Mr0N** [comment] 2022-09-16 19:46
> > only it still needs to be returned
> 
> If you're referring to the GC reclaiming the unreferenced memory, then that's how .NET works, and it's completely unrelated to EF, DbContext pooling, etc. Any code your write will do the same. In other words, your manual logic to remove from change tracking will also not reduce memory immediately, until the GC decides to reclaim it.
> 
> > there may be a possible memory leak in it
> 
> There's no memory leak, unless there's a bug in EF (which we would fix). Many production applications are using short-lived context with the unit-of-work pattern - with and without context pooling - and are doing so successfully.

> > only it still needs to be returned
> 
> If you're referring to the GC reclaiming the unreferenced memory, then that's how .NET works, and it's completely unrelated to EF, DbContext pooling, etc. Any code your write will do the same. In other words, your manual logic to remove from change tracking will also not reduce memory immediately, until the GC decides to reclaim it.
> 
> > there may be a possible memory leak in it
> 
> There's no memory leak, unless there's a bug in EF (which we would fix). Many production applications are using short-lived context with the unit-of-work pattern - with and without context pooling - and are doing so successfully.

I understood that the deletion of these objects will not happen immediately, but then the GC will be able to delete these objects

**Comment by Mr0N** [comment] 2022-09-17 05:43
> > > There's no memory leak, unless there's a bug in EF (which we would fix). Many production applications are using short-lived context with the unit-of-work pattern - with and without context pooling - and are doing so successfully.
> > 
> > 
> > Well, I don’t know, if you add 20,000 objects to one context and there are no forces on them anywhere in the program, then the garbage collector will not delete these objects
> > [...]
> > I understood that the deletion of these objects will not happen immediately, but then the GC will be able to delete these objects
> 
> As I wrote above, when a pooled DbContext is returned to the pool, its references to your objects are severed, allowing those objects to be reclaimed by the GC. There is no memory leak involved in using DbContext pooling, otherwise that feature - which is used by many people - would have been unusable.

But I understood how it all works) this context is something like a List<T>, a new List<T> is created for each controller class, and when the user does not need a List<T> it is deleted.
There is only one problem, it is not clear how many objects the user will insert into this List<T>(DbContext).
And you don't think that it is necessary to invent a mechanism for deleting objects from List<T>(DbContext)? Because the real List<T> has such a mechanism, but DbContext does not.

**Comment by Mr0N** [comment] 2022-09-17 05:45
> 

And to make a pool so as not to delete objects from the list (DbContext) is somehow funny) to make a pool of lists

**Comment by Mr0N** [comment] 2022-09-17 10:04
in general, it would be cool if you could check if there is no thread anywhere except ChangeTracking, if there is no thread anywhere else, then such an object can be deleted, that is what GC is doing now

**Comment by Mr0N** [comment] 2022-09-17 10:05
I just don't know how to do it, and it will cost a little more in terms of resources for checking objects

**Comment by roji** [comment] 2022-09-17 11:41
> this context is something like a List, a new List is created for each controller class, and when the user does not need a List it is deleted.

The DbContext's change tracker is not some data structure which you're supposed to use just to have references to your objects; it is used specifically to track entities so that changes can be persisted to the database. Once changes have been persisted, as a general rule you no longer need the context and can dispose it (possibly returning it to the pool).

Note that if you're looking for a mechanism to clear the change tracker ("the list") with disposing the context or returning it to the pool, you can use context.ChangeTracker.Clear() which does that.

> And to make a pool so as not to delete objects from the list (DbContext) is somehow funny) to make a pool of lists

Once again, DbContext is not a list, and is not meant to be used as once. Also, take care to distinguish between the DbContext and the user objects tracked by the change tracker. DbContext has many other functions beyond change tracking (the "list" part), and it's pooled so that you wouldn't need to recreate it and all its dependent services every time you need to do something.

> in general, it would be cool if you could check if there is no thread anywhere except ChangeTracking, if there is no thread anywhere else, then such an object can be deleted, that is what GC is doing now

That... doesn't make any sense to me... Change tracking isn't a thread, it's a function of DbContext involving various data structures. If the DbContext's change tracker still references user objects, that means there are likely pending database operations which need to be performed, and those objects definitely should not be reclaimed by the GC. Again, if you'd like to release all user objects, call context.ChangeTracker.Clear().

@Mr0N we've been discussing quite a lot in the above comments, and I'm not sure further discussion would be fruitful; EF's DbContext was designed around the unit-of-work pattern, and that's how it meant to be used. I suggest familiarizing yourself with that pattern and understanding what standard EF practices look like.

**Comment by Mr0N** [comment] 2022-09-17 12:16
> > this context is something like a List, a new List is created for each controller class, and when the user does not need a List it is deleted.
> 
> The DbContext's change tracker is not some data structure which you're supposed to use just to have references to your objects; it is used specifically to track entities so that changes can be persisted to the database. Once changes have been persisted, as a general rule you no longer need the context and can dispose it (possibly returning it to the pool).
> 
> Note that if you're looking for a mechanism to clear the change tracker ("the list") with disposing the context or returning it to the pool, you can use context.ChangeTracker.Clear() which does that.
> 
> > And to make a pool so as not to delete objects from the list (DbContext) is somehow funny) to make a pool of lists
> 
> Once again, DbContext is not a list, and is not meant to be used as once. Also, take care to distinguish between the DbContext and the user objects tracked by the change tracker. DbContext has many other functions beyond change tracking (the "list" part), and it's pooled so that you wouldn't need to recreate it and all its dependent services every time you need to do something.
> 
> > in general, it would be cool if you could check if there is no thread anywhere except ChangeTracking, if there is no thread anywhere else, then such an object can be deleted, that is what GC is doing now
> 
> That... doesn't make any sense to me... Change tracking isn't a thread, it's a function of DbContext involving various data structures. If the DbContext's change tracker still references user objects, that means there are likely pending database operations which need to be performed, and those objects definitely should not be reclaimed by the GC. Again, if you'd like to release all user objects, call context.ChangeTracker.Clear().
> 
> @Mr0N we've been discussing quite a lot in the above comments, and I'm not sure further discussion would be fruitful; EF's DbContext was designed around the unit-of-work pattern, and that's how it meant to be used. I suggest familiarizing yourself with that pattern and understanding what standard EF practices look like.

What does it unfreeze if there are no more references to the object that is in ChangeTracking in the program?The object cannot really be changed in this program, the point is to track it

**Comment by Mr0N** [comment] 2022-09-17 12:18
> 

Why is there no such method?context.ChangeTracker.Remove(obj);

**Comment by roji** [comment] 2022-09-17 12:31
> What does it unfreeze if there are no more references to the object that is in ChangeTracking in the program?The object cannot really be changed in this program, the point is to track it

I'm sorry, I have no idea what you're asking - what does unfreeze mean? It's totally reasonable for a program to add some object to the context, and no longer retain any other reference to it (e.g. `context.Blogs.Add(new Blog(...));`). At that point the object is tracked - referenced by the change tracker - and will be inserted into the database when SaveChanges is called. Note that the program can still access it during this state via the change tracker.

**Comment by Mr0N** [comment] 2022-09-17 13:30
https://github.com/Mr0N/testMemoryLeak/blob/master/testMemoryLeak/Program.cs  
Why is the memory not cleared?
![image](https://user-images.githubusercontent.com/61237140/190859544-b2c682d5-8755-4e31-ad3f-18eb1e0b6828.png)

**Comment by Mr0N** [comment] 2022-09-17 14:05
![image](https://user-images.githubusercontent.com/61237140/190861038-05cb22ac-dedf-46cd-954e-d79bd899067f.png)
https://github.com/Mr0N/testMemoryLeak

**Comment by Mr0N** [comment] 2022-09-17 14:07
![image](https://user-images.githubusercontent.com/61237140/190861154-2410537a-32f2-4117-be4e-a3d9e82988f8.png)
why keep track of these instances if they are not available to the application?

**Comment by roji** [comment] 2022-09-17 16:05
Some applications may wish to continue doing changes to the entities after SaveChanges is called - it sometimes makes sense to have multiple SaveChanges on the same DbContext instance. This is why the change tracker isn't automatically emptied after calling SaveChanges. But if this is what you want to achieve, you can easily just call context.ChangeTracker.Clear after SaveChanges, or even override SaveChanges in your DbContext to always do that. #9118 tracks adding an option in EF for doing that.

But as we've written multiple times, the recommend pattern is to simply get a (possibly pooled) DbContext when you need it, and to dispose it once you no longer need it:

```c#
using (var context = pooledContextFactory.CreateDbContext()) 
{
    context.Information.Add(...);
    context.Information.SaveChanges();
}
```

What exactly is your issue with this pattern, which is the standard, recommended way for using EF?

**Comment by Mr0N** [comment] 2022-09-17 16:26
> Some applications may wish to continue doing changes to the entities after SaveChanges is called - it sometimes makes sense to have multiple SaveChanges on the same DbContext instance. This is why the change tracker isn't automatically emptied after calling SaveChanges. But if this is what you want to achieve, you can easily just call context.ChangeTracker.Clear after SaveChanges, or even override SaveChanges in your DbContext to always do that. #9118 tracks adding an option in EF for doing that.
> 
> But as we've written multiple times, the recommend pattern is to simply get a (possibly pooled) DbContext when you need it, and to dispose it once you no longer need it:
> 
> ```cs
> using (var context = pooledContextFactory.CreateDbContext()) 
> {
>     context.Information.Add(...);
>     context.Information.SaveChanges();
> }
> ```
> 
> What exactly is your issue with this pattern, which is the standard, recommended way for using EF?

come without a pool, the pool is a crutch in this case, which can make less more, sometimes.

yes, some need to enter information into the instance and some don't, so I want to have an option for those that don't need to be called on the Dispose context.

**Comment by roji** [comment] 2022-09-17 17:47
> come without a pool, the pool is a crutch in this case, which can make less more, sometimes.

That doesn't really mean anything concretely, unfortunately. You still haven't provided an actual reason why you're averse to using the pool and insisting on a single, long-lived context.

> yes, some need to enter information into the instance and some don't, so I want to have an option for those that don't need to be called on the Dispose context

You have that option - as I've indicated above, just call context.ChangeTracker.Clear() after SaveChanges; you can easily override DbContext.SaveChanges and put that there if you always want it to happen. What's missing here?

**Comment by Mr0N** [comment] 2022-09-17 17:54
> 

the Clear method for all objects, if there are 1000 objects, and the entity needs to monitor 800, but not 200, Clear will not help with this

**Comment by roji** [comment] 2022-09-17 18:31
I've done my best to describe EF best practices, and how the product was designed to be used - the conversation seems to be going in circles at this point. I think that between the above and the EF documentation you should have all the information in order to write an EF program according to best practices.

**Closed by roji** 2022-09-17 18:31 UTC
Labels: type-enhancement, customer-reported

**Comment by Mr0N** [comment] 2022-09-17 18:50
Okay, I'll write a bone code) with a memory leak!

**Comment by roji** [comment] 2022-09-17 18:51
@Mr0N there really are no memory leaks here. Carefully read the above to understand that.

**Comment by Mr0N** [comment] 2022-09-17 18:59
> @Mr0N there really are no memory leaks here. Carefully read the above to understand that.

Well, I don’t know, it might be like that if you follow the documentation and make a scoupe context or use a factory, but in any case, if you make it a singleton, there will be problems, well, maybe so be it) but I’m not used to this) because .Net controls the use of memory, never- I wouldn't have thought that the context of the database would violate it, that's why there were some problems) well, I solved them

**Comment by smitpatel** [comment] 2022-09-18 05:06
Just gonna leave it here for whoever finds it useful - https://en.wikipedia.org/wiki/Memory_leak

**Comment by LeaFrock** [comment] 2022-09-30 02:26
> but I’m not used to this

I don't think it's a reason. 

And salute to roji for his patience 👍 .

**Comment by Mr0N** [comment] 2022-11-06 17:22
> Just gonna leave it here for whoever finds it useful - https://en.wikipedia.org/wiki/Memory_leak

according to the description, it fits perfectly
