### ISSUE TITLE
Query: invalid SQL generated for groupby aggregate query projecting key sum of group key with itself

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12656] opened 2018-07-12 23:31 UTC
query:

```cs
var query = (from o in ctx.Orders
                             join c in ctx.Customers
                                 on o.CustomerID equals c.CustomerID into grouping
                             from c in grouping.DefaultIfEmpty()
                             select o)
                        .GroupBy(o => o.OrderID)
                        .Select(
                            g => new
                            {
                                Value = g.Key + g.Key,
                                Average = g.Average(o => o.OrderID)
                            });

                var result = query.ToList();
```

sql:

```sql
SELECT [o].[OrderID] AS [Key] + [o].[OrderID] AS [Key] AS [Value], AVG(CAST([o].[OrderID] AS float)) AS [Average]
FROM [Orders] AS [o]
LEFT JOIN [Customers] AS [c] ON [o].[CustomerID] = [c].[CustomerID]
GROUP BY [o].[OrderID]
```

Exception:

Incorrect syntax near '+'.

**Comment by smitpatel** [comment] 2018-07-27 19:54
Duplicate of #12826

**Closed** 2022-10-16 13:19 UTC
Labels: type-bug, closed-duplicate
