### ISSUE TITLE
Exception thrown when using lazy loading with many to many relation defined from one side only and with SplitQuery behavior

### ISSUE THREAD

**Issue by VladDragnea** [dotnet/efcore#32237] opened 2023-11-05 17:12 UTC
When using lazy loading on a navigation collection property for a many to many relation which does not have the inverse collection property defined, a NullReferenceException is thrown. This only happens when the DbContext is configured with SplitQuery as a query behavior, otherwise it works just fine with SingleQuery behavior. Also, it happens after loading the data from DB, if there are no related records in DB it won't throw.

```C#
using Microsoft.EntityFrameworkCore;

internal class Program
{
    private static void Main()
    {
        using var db = new AppDbContext();

        db.Database.EnsureDeleted();
        db.Database.EnsureCreated();

        var admin = db.Users.Single(x => x.UserId == AppDbContext.AdminUserId);
        var adminRoles = admin.Roles;

        Console.WriteLine(string.Join(", ", adminRoles.Select(r => r.RoleName)));
    }
}

public class Role
{
    public int RoleId { get; set; }
    public string RoleName { get; set; }
    //public virtual ICollection<User> Users { get; set; } = new List<User>();
}

public class User
{
    public int UserId { get; set; }
    public string UserName { get; set; }
    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}


public class AppDbContext : DbContext
{
    public const int AdminRoleId = 1, AdminUserId = 1;

    public DbSet<User> Users { get; set; }
    public DbSet<Role> Roles { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
    {
        options
            .UseLazyLoadingProxies()
            .UseSqlServer("Data Source=(local);Initial Catalog=M2MLL;Integrated Security=True;TrustServerCertificate=True",
                sqlOptions => sqlOptions.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery)); // SingleQuery
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId);
            entity.Property(e => e.RoleName).IsRequired().HasMaxLength(30);
            entity.HasData(new Role { RoleId = AdminRoleId, RoleName = "Admin Role" });
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId);
            entity.Property(e => e.UserName).IsRequired().HasMaxLength(50);
            entity.HasMany(e => e.Roles).WithMany() // e => e.Users
                .UsingEntity<Dictionary<string, object>>("UserRole",
                    r => r.HasOne<Role>().WithMany().HasForeignKey("RoleId"),
                    l => l.HasOne<User>().WithMany().HasForeignKey("UserId"),
                    j => j.HasData(new { UserId = AdminUserId, RoleId = AdminRoleId }));
            entity.HasData(new User { UserId = AdminUserId, UserName = "Admin Name" });
        });
    }
}
```
Exception is thrown at line 13: ```var adminRoles = admin.Roles;```
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.GetCollection(Object instance)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.GetOrCreateCollection(Object instance, Boolean forMaterialization)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.GetOrCreate(Object entity, Boolean forMaterialization)
   at lambda_method114(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.Load[TSource](IQueryable`1 source)
   at Microsoft.EntityFrameworkCore.Internal.ManyToManyLoader`2.Load(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.CollectionEntry.Load()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.LazyLoader.Load(Object entity, String navigationName)
   at Microsoft.EntityFrameworkCore.Proxies.Internal.LazyLoadingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.UserProxy.get_Roles()
   at Program.Main() in C:\Projects\Learning\M2MLL\Program.cs:line 13
```

EF Core version: 7.0.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0 / .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.8 Preview 6.0

**Comment by ajcvickers** [comment] 2023-11-06 11:11
Duplicate of #32225

**Closed by ajcvickers** 2023-11-06 11:11 UTC
Labels: customer-reported
