### ISSUE TITLE
Add SQL translation for between-any

### ISSUE THREAD

**Issue by skuehlshelbyMITCS** [dotnet/efcore#34580] opened 2024-08-30 19:10 UTC
I just noticed that expressions of the following format are not translatable to SQL:
Entities.Where(e => Ranges.Any(Range => Range.Begin <= Enity.Field && Enity.Field <= Range.End))
I had specifically tried this with tuples of type (DateOnly Begin, DateOnly End) in SQL Server.

It would be great to add support for this style of expression in the future.
I would expect this to translate to something like:
WHERE X BETWEEN A AND B OR WHERE X BETWEEN C AND D OR...
or
AND (X BETWEEN A AND B OR X BETWEEN C AND D OR...)
depending on context.

**Comment by roji** [comment] 2024-08-30 20:39
Duplicate of #31237

**Comment by roji** [comment] 2024-08-30 20:40
This already works if Ranges is a primitive collection, as opposed to a collection of tuples/complex types. The latter is tracked by #31237, though it would translate to different SQL.

**Closed by roji** 2024-08-30 20:40 UTC
Labels: type-enhancement, customer-reported
