### ISSUE TITLE
RC2 nullable Guid as foreign key results with in-memory evaluation - did not happen with RC1

### ISSUE THREAD

**Issue by RickBlouch** [dotnet/efcore#5514] opened 2016-05-25 15:12 UTC
I'll start by saying that I just migrated from RC1 -> RC2 and have found this issue as part of the migration process.  I do not know if it's an EF bug or if there was a change that I did not migrate properly.  I could not find any other issues on GitHub that seemed to be related, but I will admit I'm not a GitHub wizard.  I will say that this was not an issue in RC1 in my real world application.  

[NullableGuidForeignKeyIssue.zip](https://github.com/aspnet/EntityFramework/files/282248/NullableGuidForeignKeyIssue.zip)

The attached sample project demonstrates the issue.  I have greatly simplified my real world scenario to this very basic example.  In my real world application we allow for dynamic searching based on tenant configurations using LINQ expressions.  We do not know which properties on Account or Patient will be searched at development time.  In some cases the search may just be on Account and in other cases it may be on both Account and Patient.  Because this issue is happening even with this very basic example I have not included any of the above in this sample to keep it simple, however I hope you can see why I would need to build a query in this way, rather than going to _db.Patients and querying in that direction.  My real object graph has a few additional entities that are related to Account that are also utilized in the dynamic LINQ.
### The issue

When I set the foreign key property of a one to many relationship to `Guid?` it results in part of the query being evaluated in the database and part in memory.

```
    public class Patient
    {
        public Guid Id { get; set; }
        public ICollection<Account> Accounts { get; set; } = new List<Account>();
        public string Name { get; set; }
    }
```

As you can see, PatientId is `Guid?`.  Not every account has a Patient at all times.

```
    public class Account
    {
        public Guid Id { get; set; }
        public Guid? PatientId { get; set; }
        public Patient Patient { get; set; }
        public string value1 { get; set; }
    }
```

```
    public class SampleDbContext : DbContext
    {
        public DbSet<Patient> Patients { get; set; }
        public DbSet<Account> Accounts { get; set; }

        public SampleDbContext(DbContextOptions<SampleDbContext> options)
            : base(options)
        {
        }
    }
```

```
var ids = _db.Accounts
     .Where(a => a.Patient.Name == "Steve" && a.value1 == "fdsa")
     .Select(a => a.PatientId)
     .ToList();
```

Results in this query which I retrieved through SQL profiler.

```
SELECT [a].[Id], [a].[PatientId], [a].[value1], [a.Patient].[Id], [a.Patient].[Name]
FROM [Accounts] AS [a]
LEFT JOIN [Patients] AS [a.Patient] ON [a].[PatientId] = [a.Patient].[Id]
WHERE [a].[value1] = N'fdsa'
ORDER BY [a].[PatientId]
```

**I would expect the SQL to include a filter for `[a.Patient].[Name] = 'Steve'` as it did in RC1.**

Instead it's returning every column across both tables (which in my real world scenario is a lot of data) even though I specifically only asked for PatientId, and it's returning every row that matches value1 = 'fdsa' and then filtering Patient Name in memory.
### What happens when I remove Guid?

After removing the nullable Guid and making it required, and removing the seed data that is created without a Patient, the SQL is generated as expected.

Same LINQ

```
var ids = _db.Accounts
     .Where(a => a.Patient.Name == "Steve" && a.value1 == "fdsa")
     .Select(a => a.PatientId)
     .ToList();
```

Results in this query

```
SELECT [a].[PatientId]
FROM [Accounts] AS [a]
INNER JOIN [Patients] AS [a.Patient] ON [a].[PatientId] = [a.Patient].[Id]
WHERE ([a.Patient].[Name] = N'Steve') AND ([a].[value1] = N'fdsa')
```

I can't make this change though because I have accounts that do not have patients.
### Further technical details

EF Core version: RC2
Operating system: Windows
Visual Studio version: VS 2015

I have attached a sample project that demonstrates the issues.  The connection string is hardcoded in the startup file as well as some basic seed data.  The LINQ that demonstrates the issue is located in the HomeController.

**Comment by maumar** [comment] 2016-05-25 17:54
Duplicate of https://github.com/aspnet/EntityFramework/issues/4588

In RC1 we were producing INNER JOINs for all kinds of navigations (required and optional), so this would result in invalid data being returned (missing rows) for cases where the navigated value was actually null.

In RC2 we now produce LEFT OUTER JOINs correctly, but the side effect is much more complicated intermediate query, which we currently don't know how to fully translate to SQL, resulting in client evaluation that you see. The issue is scheduled to be fixed for the current milestone, according to the current plan.

**Comment by flgarrid** [comment] 2016-06-08 23:11
Any idea on how to force an inner join without having to modify the model? (i understand the consequences) 

This would be very useful while we wait for the rtm.

**Comment by maumar** [comment] 2016-06-08 23:17
@flgarrid unfortunately there is no way to do this :(

**Closed** 2022-10-16 09:42 UTC
