### ISSUE TITLE
ToDictionary and ToDictionaryAsync do not generated expected SQl

### ISSUE THREAD

**Issue by daniefer** [dotnet/efcore#17802] opened 2019-09-12 18:35 UTC
### Description
When using the ToDictionaryAsync extension, the value selector is not correctly translated to a select as expected. In fact, the generated SQL is possibly the worst way to do the requested query.

### Steps to reproduce
Given the following context and entities:
```C#
    public class MyContext : DbContext
    {
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Person> Persons { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Car>()
               .HasOne(c => c.Owner)
               .WithMany(p => p.Cars)
               .HasForeignKey(c => c.OwnerId);
        }
    }
    public class Car
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Style { get; set; }
        public string PrimaryColor { get; set; }
        public Person Owner { get; set; }
        public int OwnerId { get; set; }
    }
    public class Person
    {
        public id Id { get; set; }
        public string Name { get; set; }
        public DateTime Dob { get; set; }
        public string Gender { get; set; }
    }
```
When ToDictionary or ToDictionaryAsync is called where a join is implied
```C#
var bureaus = await _dbContext.Cars
    .ToDictionaryAsync(x => x.Id, x => x.Owner.Name);
```
The generated SQL is garbage
```SQL
SELECT [t0].[Id], [t0].[Make], [t0].[Model], [t0].[Style], [t0].[PrimaryColor], [t0].[OwnerId]
FROM [Cars] AS [t0]
GO

-- Region Parameters
DECLARE @p0 Int = 1
-- EndRegion
SELECT [t0].[Id], [t0].[Name], [t0].[Dob], [t0].[Gender]
FROM [Persons] AS [t0]
WHERE [t0].[Id] = @p0
GO

-- Region Parameters
DECLARE @p0 Int = 2
-- EndRegion
SELECT [t0].[Id], [t0].[Name], [t0].[Dob], [t0].[Gender]
FROM [Persons] AS [t0]
WHERE [t0].[Id] = @p0
GO

-- Region Parameters
DECLARE @p0 Int = 3
-- EndRegion
SELECT [t0].[Id], [t0].[Name], [t0].[Dob], [t0].[Gender]
FROM [Persons] AS [t0]
WHERE [t0].[Id] = @p0
GO

-- This pattern repeats for each FK Id retrieved for the first query
```
I would expect the generated SQL to match what the below query generates
```C#
var bureaus = await _dbContext.Cars
    .Select(x => new { x.Id, x => x.Owner.Name })
    .ToDictionaryAsync(x => x.Id, x => x.Name);
```
```SQL
SELECT [t0].[Id], [t1].[Name]
FROM [Cars] AS [t0]
INNER JOIN [Persons] AS [t1] ON [t1].[Id] = [t0].[OwnerId]
```

### Further technical details

EF Core version: 2.2.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 2.2.6
Operating system: Windows 10 Pro-  Version 10.0.18362 - Build 18362
IDE: Visual Studio 2019 16.1.6

**Comment by smitpatel** [comment] 2019-09-21 00:52
Duplicate of #16730

**Closed** 2022-10-16 14:41 UTC
Labels: closed-duplicate, customer-reported
