### ISSUE TITLE
How to model a schema with an abstract base entity in TPH strategy ?

### ISSUE THREAD

**Issue by LMinato** [dotnet/efcore#33224] opened 2024-03-03 12:08 UTC
Hi, I am currently working on a schema that has several entities derived from a base abstract class. 
The idea of making the base class abstract is that I want to enforce implementing some methods in the derived classes, but as long as EF can't instantiate the base, the migrations fails. 

```csharp
public abstract Node : Entity 
{
// Properties
// Abstract methods
}

```
trying to modeling like below 

```csharp
public sealed class ApplicationDbContext(DbContextOptions options) : DbContext(options)
{
    public DbSet<Node> Nodes { get; set; }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Node>()
            .ToTable("Nodes");
        modelBuilder.Entity<Node>()
            .HasKey(n => n.Id);
         
        modelBuilder.Entity<Node>()
            .HasDiscriminator(n => n.NodeType)
            .HasValue<DerivedNode1>(NodeType.Derived1)
            .HasValue<DerivedNode1>(NodeType.Derived1);
    }
}
```

Even trying with modeling only derived types and specifying `.HasBaseType()` hasn't helped.

Does anyone have an idea, either to fix this configuration to make EF Core happy with this mapping, or by changing the class model to be able to have one base class that provides guidance (meaning enforcing overriding methods) in the classes that inherits. 
Thanks for your help,
Lucas

**Comment by ajcvickers** [comment] 2024-03-04 07:40
> but as long as EF can't instantiate the base, the migrations fails.

In what way does it fail? This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by AndriySvyryd** [comment] 2024-03-15 23:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by AndriySvyryd** 2024-03-15 23:38 UTC
Labels: customer-reported, area-model-building
