### ISSUE TITLE
Cosmos: Refactor SqlQuery generation from SqlParameter generation

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#18033] opened 2019-09-25 00:15 UTC
So that we can reuse the Sql generated by one visit and use it with different parameter values without revisiting.
This would enable us to have SqlQuery caching based on parameter nullability

**Comment by AndriySvyryd** [comment] 2019-09-25 04:04
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/17297 ?

**Closed** 2022-10-16 14:44 UTC
Labels: closed-duplicate
