### ISSUE TITLE
When inserting data, the navigation property is empty and an error will be reported

### ISSUE THREAD

**Issue by gongzhx1998** [dotnet/efcore#27225] opened 2022-01-20 08:02 UTC
There are 2 classes and they are one to many relationship.
![image](https://user-images.githubusercontent.com/51268072/150297233-04c4ce22-99d3-477b-a723-2aeb29ce3c2a.png)
![image](https://user-images.githubusercontent.com/51268072/150297275-23227246-8556-474f-a07a-a718e3cdd387.png)

Validate before adding data in controller
![image](https://user-images.githubusercontent.com/51268072/150297425-fdff77b2-b609-48ac-8c2f-274ca8875ad1.png)

will return an error that the navigation property cannot be null

**Comment by ajcvickers** [comment] 2022-01-20 08:29
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-01-28 15:41
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:22 UTC
Labels: closed-could-not-reproduce, customer-reported
