### ISSUE TITLE
EF throws weird exception

### ISSUE THREAD

**Issue by IndigoHealth** [dotnet/efcore#29956] opened 2022-12-31 17:01 UTC
EF Core version: 7.0.1  
Database provider: Microsoft.EntityFrameworkCore.SqlServer  
Target framework: net7.0  
Operating system: Windows 11 Pro  
IDE: VS Pro version 17.4.3  

The attached program adds new parent/child records to a DbContext. But when it calls `DbContext.SaveChanges()` EF throws an `InvalidOperationException` with the Message text:

> The property 'DiagnosisLocalized.Id' has a temporary value while attempting to change the entity's state to 'Unchanged'. Either set a permanent value explicitly, or ensure that the database is configured to generate values for this property.

The complete repo is attached as a zip file.
[EntityFrameworkTest.zip](https://github.com/dotnet/efcore/files/10327691/EntityFrameworkTest.zip)

(Don't forget to execute `update-database` in the VS Package Manager Console before running the program.)

Curiously:
* The data is, in fact, committed to the database even though EF has thrown an exception.
* Removing about half of the 900+ data records makes the problem go away.
* I've seen this problem both on my Windows 11 Pro development machine and deployed to Azure.

**Comment by roji** [comment] 2023-01-02 09:43
Duplicate of #29502

**Comment by roji** [comment] 2023-01-02 09:44
@IndigoHealth this is almost certainly a bug that has already been fixed for the upcoming 7.0.3 release. Can you please try with the latest 8.0 [daily build](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md) (where the bug has already been fixed) and confirm?

**Comment by IndigoHealth** [comment] 2023-01-04 00:57
I need help figuring out how to install the latest 8.0 daily build. I created the NuGet.config file, and put copies of it in both the top-level (solution) folder and the "project" folder (next to the .csproj file). But I can't figure out the next step to access the version 8.0 NuGet packages to install them.

**Comment by roji** [comment] 2023-01-04 07:30
@IndigoHealth you only need to put a NuGet.Config at your solution root, no need to duplicate it twice.

Have you followed the instructions in [the docs](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md)? These include precise screenshots on how to select and install the prerelease packages etc.

**Comment by IndigoHealth** [comment] 2023-01-04 20:29
Hi @roji, "the docs" are predicated on some fundamental knowledge that 99% of developers lack. For most of us, consuming NuGet packages is simply magic that works, whether from the command line or the Package Manager Console. Here is a guided tour of my experience trying to follow the instructions. As it turns out, I figured out where I went wrong while I was writing this missive. I see that you are apparently the author of the documentation page. Hopefully you can use my experience to improve the page. 

We start with:

> Create a file called "NuGet.config" with the following contents and put it next to your solution or csproj file:

Simple enough. The project has a solution file in the top-level folder, and the csproj file in the project folder. I put the NuGet.config file in the top-level (solution) folder.

The next section in the docs is "Types of builds". Interesting but not actionable. Moving along...

The next section, "Package sources", repeats the original instructions to create a NuGet.config file. So far so good. Then it gives me a command "To install the daily build of dotnet-ef". Here is where things start to go off the rails.

1. When I spin up a command prompt, with the current directory set to my solution folder, and try to execute the command, it complains that dotnet-ef is already installed.
2. Larger issue: It took me a long time to realize that this magic is NOT trying to install the EF 8 NuGet packages in my project. It is apparently trying to tweak the `dotnet ef` command itself to use a newer version of the command. And I am loath to tweak the underlying NuGet machinery with magic commands that I don't fully understand, which are installing "alpha" bits that may not work. I really don't want to break everything on my development machine and have to figure out how to fix it.

After some googling, I found [this SO answer](https://stackoverflow.com/a/71698952/1637105), that teaches me about creating a local manifest and installing the tool locally to the project (or, at least, I assume that's what it's telling me).  So I execute the magic commands:

```
dotnet new tool-manifest --version 8.0.0-* --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json
dotnet tool install dotnet-ef
```

Now I have a new `dotnet-tools.json` file in the project folder. 

I assume I have done the right thing to get around my problem with "To install the daily build of `dotnet-ef`". The next step says, "To install the `dotnet new` templates". Do I need to do that? Who knows? I have no clue what `dotnet new` templates are. So I skipped that step.

After that, attempting to install version 8 packages totally failed. The VS "Manage Packages" page didn't even display "dotnet8" as an option in the "Package source" dropdown.

**Just now** I went back and executed the "To install the `dotnet new` templates" command. Bada-bing, bada-boom, the new packages are available, the project (with the updated version numbers in the csproj file) builds, and the test verifies that the **problem has gone away with the new version 8 bits.**

Here are my suggestions for how to fix the documentation page:

1. Please modify the section titled "To install the daily build of `dotnet ef`". 
  a. Rename the section to be a command: "Install the daily build..."
  b. Add a sentence or two explaining what this step is doing. Remember, we (the developers trying to follow these instructions) are clueless about NuGet machinery.
  c. Give instructions for installing locally in addition to the existing (global installation) instructions.
2. Please modify the section titled "To install the `dotnet new` templates".
  a. Rename the section to be a command: "Install the `dotnet new` templates"
  b. Add a sentence or two explaining what this step is doing.
3. Even with those two steps completed, the new packages weren't readily apparent. But I *was* able to modify the csproj file to use the "Version=8.0.0-*" syntax to successfully pull in the new NuGet packages.

**Comment by roji** [comment] 2023-01-05 11:03
@IndigoHealth thanks for your feedback, I've submitted #29983 with some changes to the daily build docs. In any case, it's good to hear that the original bug no longer exists in 8.0.0.

> The next section in the docs is "Types of builds". Interesting but not actionable. Moving along...

Note that the first section is titled "quickstart", and is all you need for getting daily builds of EF. The rest of the page is explicitly there for "full details and troubleshotting".

> It is apparently trying to tweak the dotnet ef command itself to use a newer version of the command. And I am loath to tweak the underlying NuGet machinery with magic commands that I don't fully understand, which are installing "alpha" bits that may not work. I really don't want to break everything on my development machine and have to figure out how to fix it.

The `dotnet ef` CLI tool is just part of EF itself - there's nothing magical about it; this bit of the docs just show you how to get the daily build version of `dotnet ef`, just as you're getting the daily build version of EF itself. It's true that this typically isn't necessary - older version of `dotnet ef` usually work with newer (and daily build) versions, unless there's been a specific command-line change.

In any case, I'm adding some text to make it clearer that the `dotnet ef` and template daily builds are optional, and describing exactly what they mean.

> After some googling, I found [this SO answer](https://stackoverflow.com/a/71698952/1637105), that teaches me about creating a local manifest and installing the tool locally to the project (or, at least, I assume that's what it's telling me). So I execute the magic commands:

Installing `dotnet ef` locally absolutely isn't necessary, not particularly recommended. As I wrote above, using a daily build of the `dotnet ef` tool typically isn't necessary, and when it is, it's perfectly fine to update to it globally (rather than locally). You can always downgrade back to the stable version later, just as you would with the EF NuGet packages themselves. There's nothing magical about all of this.

> Just now I went back and executed the "To install the dotnet new templates" command. Bada-bing, bada-boom, the new packages are available [...]

Installing the new templates has nothing to do with VS suddenly picking up the new feed from NuGet.config; this likely just happened because you restarted VS or some similar thing. The templates are only there for reverse-engineering existing databases, and you should only need to update them if you specifically want their daily build versions (not usually the case). I'll add a note on this.

**Closed** 2023-01-05 11:03 UTC
Labels: customer-reported

**Comment by IndigoHealth** [comment] 2023-01-05 23:21
Thanks @roji.

> There's nothing magical about all of this.

Arthur C. Clarke famously said, "Any sufficiently advanced technology is indistinguishable from magic." That is the sense in which I use the term. If I don't know what the technology is doing (which I obviously don't based on your answers), and I don't know how to fix things when the technology goes sideways on me, it is, for all intents and purposes, magic.

Anyway, thanks again!
