### ISSUE TITLE
order by, does not work in the following case

### ISSUE THREAD

**Issue by osmardavalos** [dotnet/efcore#14703] opened 2019-02-14 14:09 UTC
I'm doing a query to get a list of modules and their associated options but belonging to the user profiles, Module (1) -> (*) Option (1) -> (*) ProfileOption, but the order by is not reflected in the SQL query

```c#
var modules = bd.Module
            .Where
            (m => m.Options
                   .Any(o => o.ProfileOption
                              .Any(po => idsProfile.Contains(po.ProfileId))
                       )
            )
            .Select(m => new Module
            {
                Name = m.Name,
                Icon = m.Icon,
                Options = bd.ProfileOption
                            .Where
                            (po => idsProfile.Contains(po.ProfileId) &&
                                   po.Option.ModuleId == m.Id
                            )
                            .Select(po => new Option
                            {
                                Name = po.Option.Name,
                                Icon = po.Option.Icon,
                                Url = po.Option.Url                                
                            })
                            .OrderBy(po => po.ListOrder)
                            .ToList()
            })
            .OrderBy(m => m.Priority)
            .ToList();

. . . the resulting SQL is

SELECT [m].[Name], [m].[Icon], [m].[Id]
FROM [Security].[Module] AS [m]
WHERE EXISTS (
    SELECT 1
    FROM [Security].[Option] AS [o]
    WHERE EXISTS (
        SELECT 1
        FROM [Security].[ProfileOption] AS [po]
        WHERE [po].[ProfileId] IN (CAST(1 AS bigint)) AND ([o].[Id] = [po].[OptionId])) AND ([m].[Id] = [o].[ModuleId]))
go
exec sp_executesql N'SELECT [po.Option].[Name], [po.Option].[Icon], [po.Option].[Url]
FROM [Security].[ProfileOption] AS [po0]
INNER JOIN [Security].[Option] AS [po.Option] ON [po0].[OptionId] = [po.Option].[Id]
WHERE [po0].[ProfileId] IN (CAST(1 AS bigint)) AND ([po.Option].[ModuleId] = @_outer_Id)',N'@_outer_Id bigint',@_outer_Id=1
go

**Comment by smitpatel** [comment] 2019-02-14 18:08
It is doing N+1 client evaluation of projection. Order By will happen on client side. Hence not present in SQL. The results should be correct.

**Comment by osmardavalos** [comment] 2019-02-14 21:16
@smitpatel the problem is that the order does not apply either after bringing the data

**Comment by smitpatel** [comment] 2019-02-14 22:04
@osmardavalos - Please post a runnable project which demonstrate incorrect results so we can investigate.

**Comment by ajcvickers** [comment] 2019-02-22 17:59
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by osmardavalos** [comment] 2019-03-21 15:49
Sorry I was somewhat busy and I could not answer in time, here's the solution for them to try it out:

https://github.com/osmardavalos/TestEFCore

**Comment by smitpatel** [comment] 2019-03-21 19:32
```C#
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      (QueryContext queryContext) => IEnumerable<Module> _InterceptExceptions(
      |__ source: IEnumerable<Module> _Select(
      |   |__ source: IOrderedEnumerable<ValueBuffer> _OrderBy(
      |   |   |__ source: IEnumerable<ValueBuffer> _ShapedQuery(
      |   |   |   |__ queryContext: queryContext,
      |   |   |   |__ shaperCommandContext: SelectExpression:
      |   |   |   |       SELECT [m].[Name], [m].[Icon], [m].[Id]
      |   |   |   |       FROM [Security].[Module] AS [m]
      |   |   |   |       WHERE EXISTS (
      |   |   |   |           SELECT 1
      |   |   |   |           FROM [Security].[Option] AS [o]
      |   |   |   |           WHERE EXISTS (
      |   |   |   |               SELECT 1
      |   |   |   |               FROM [Security].[ProfileOption] AS [po]
      |   |   |   |               WHERE 0 = 1) AND ([m].[Id] = [o].[ModuleId])),
      |   |   |   |__ shaper: ValueBufferShaper),
      |   |   |__ expression: (ValueBuffer m) => new Module{
      |   |   |       Name = string TryReadValue(m, 0, Module.Name),
      |   |   |       Icon = string TryReadValue(m, 1, Module.Icon),
      |   |   |       Option = List<Option> ToList(IEnumerable<Option> _Select(
      |   |   |       |__ source: IOrderedEnumerable<TransparentIdentifier<ValueBuffer, ValueBuffer>> _OrderBy(
      |   |   |       |   |__ source: IEnumerable<TransparentIdentifier<ValueBuffer, ValueBuffer>> _InjectParameters(
      |   |   |       |   |   |__ queryContext: queryContext,
      |   |   |       |   |   |__ source: IEnumerable<TransparentIdentifier<ValueBuffer, ValueBuffer>> _ShapedQuery(
      |   |   |       |   |   |   |__ queryContext: queryContext,
      |   |   |       |   |   |   |__ shaperCommandContext: SelectExpression:
      |   |   |       |   |   |   |       SELECT [po.Option].[Name], [po.Option].[Icon], [po.Option].[Url]
      |   |   |       |   |   |   |       FROM [Security].[ProfileOption] AS [po0]
      |   |   |       |   |   |   |       INNER JOIN [Security].[Option] AS [po.Option] ON [po0].[OptionId] = [po.Option].[Id]
      |   |   |       |   |   |   |       WHERE 0 = 1,
      |   |   |       |   |   |   |__ shaper: (ValueBuffer po | ValueBuffer po.Option) => TransparentIdentifier<ValueBuffer, ValueBuffer> CreateTransparentIdentifier(
      |   |   |       |   |   |       |__ outer: po,
      |   |   |       |   |   |       |__ inner: po.Option)),
      |   |   |       |   |   |__ parameterNames: new string[]{ "_outer_Id" },
      |   |   |       |   |   |__ parameterValues: new object[]{ (object)long TryReadValue(m, 2, Module.Id) }),
      |   |   |       |   |__ expression: (TransparentIdentifier<ValueBuffer, ValueBuffer> t0) => new Option{
      |   |   |       |   |       Name = string TryReadValue(t0.Inner, 0, Option.Name),
      |   |   |       |   |       Icon = string TryReadValue(t0.Inner, 1, Option.Icon),
      |   |   |       |   |       Url = string TryReadValue(t0.Inner, 2, Option.Url)
      |   |   |       |   |__ }
      |   |   |       |   |__ .ListOrder,
      |   |   |       |   |__ orderingDirection: Asc),
      |   |   |       |__ selector: (TransparentIdentifier<ValueBuffer, ValueBuffer> t0) => new Option{
      |   |   |               Name = string TryReadValue(t0.Inner, 0, Option.Name),
      |   |   |               Icon = string TryReadValue(t0.Inner, 1, Option.Icon),
      |   |   |               Url = string TryReadValue(t0.Inner, 2, Option.Url)
      |   |   |           }
      |   |   |       ))
      |   |   |__ }
      |   |   |__ .Priority,
      |   |   |__ orderingDirection: Asc),
      |   |__ selector: (ValueBuffer m) => new Module{
      |           Name = string TryReadValue(m, 0, Module.Name),
      |           Icon = string TryReadValue(m, 1, Module.Icon),
      |           Option = List<Option> ToList(IOrderedQueryable<Option> _ToQueryable(
      |           |__ source: IEnumerable<Option> _Select(
      |           |   |__ source: IOrderedEnumerable<TransparentIdentifier<ValueBuffer, ValueBuffer>> _OrderBy(
      |           |   |   |__ source: IEnumerable<TransparentIdentifier<ValueBuffer, ValueBuffer>> _InjectParameters(
      |           |   |   |   |__ queryContext: queryContext,
      |           |   |   |   |__ source: IEnumerable<TransparentIdentifier<ValueBuffer, ValueBuffer>> _ShapedQuery(
      |           |   |   |   |   |__ queryContext: queryContext,
      |           |   |   |   |   |__ shaperCommandContext: SelectExpression:
      |           |   |   |   |   |       SELECT [po.Option0].[Name], [po.Option0].[Icon], [po.Option0].[Url]
      |           |   |   |   |   |       FROM [Security].[ProfileOption] AS [po1]
      |           |   |   |   |   |       INNER JOIN [Security].[Option] AS [po.Option0] ON [po1].[OptionId] = [po.Option0].[Id]
      |           |   |   |   |   |       WHERE 0 = 1,
      |           |   |   |   |   |__ shaper: (ValueBuffer po | ValueBuffer po.Option) => TransparentIdentifier<ValueBuffer, ValueBuffer> CreateTransparentIdentifier(
      |           |   |   |   |       |__ outer: po,
      |           |   |   |   |       |__ inner: po.Option)),
      |           |   |   |   |__ parameterNames: new string[]{ "_outer_Id1" },
      |           |   |   |   |__ parameterValues: new object[]{ (object)long TryReadValue(m, 2, Module.Id) }),
      |           |   |   |__ expression: (TransparentIdentifier<ValueBuffer, ValueBuffer> t0) => new Option{
      |           |   |   |       Name = string TryReadValue(t0.Inner, 0, Option.Name),
      |           |   |   |       Icon = string TryReadValue(t0.Inner, 1, Option.Icon),
      |           |   |   |       Url = string TryReadValue(t0.Inner, 2, Option.Url)
      |           |   |   |__ }
      |           |   |   |__ .ListOrder,
      |           |   |   |__ orderingDirection: Asc),
      |           |   |__ selector: (TransparentIdentifier<ValueBuffer, ValueBuffer> t0) => new Option{
      |           |           Name = string TryReadValue(t0.Inner, 0, Option.Name),
      |           |           Icon = string TryReadValue(t0.Inner, 1, Option.Icon),
      |           |           Url = string TryReadValue(t0.Inner, 2, Option.Url)
      |           |       }
      |           |__ ),
      |           |__ queryContext: queryContext))
      |       }
      |__ ),
      |__ contextType: TestEFCore.Model.bdTestEFCoreContext,
      |__ logger: DiagnosticsLogger<Query>,
      |__ queryContext: queryContext)
```
Both the order by are present in compiled query and happening on client side.
Client Eval Warnings
```
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'orderby new Module() {Name = [m].Name, Icon = [m].Icon, Option = {from ProfileOption po in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[TestEFCore.Model.ProfileOption]) join Option po.Option in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[TestEFCore.Model.Option]) on Property([po], "OptionId") equals Property([po.Option], "Id") where ({__idsProfile_1 => Contains([po].ProfileId)} AndAlso ([po.Option].ModuleId == [m].Id)) orderby new Option() {Name = [po.Option].Name, Icon = [po.Option].Icon, Url = [po.Option].Url}.ListOrder asc select new Option() {Name = [po.Option].Name, Icon = [po.Option].Icon, Url = [po.Option].Url}}.ToList()}.Priority asc' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'orderby new Option() {Name = [po.Option].Name, Icon = [po.Option].Icon, Url = [po.Option].Url}.ListOrder asc' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'orderby new Option() {Name = [po.Option].Name, Icon = [po.Option].Icon, Url = [po.Option].Url}.ListOrder asc' could not be translated and will be evaluated locally.
```

@osmardavalos - If you are seeing that client side ordering is not happening and giving _incorrect_ results then post a repro which demonstrate the incorrect results.

**Comment by osmardavalos** [comment] 2019-03-22 21:49
Well, I have reviewed again, and effectively the ordering is done after the execution, I mean locally, but the question is the following, to make it work I had to add in the projection:

Priority = m.Priority

which does not make sense that the query proceed, it does not help me to order it locally since that data will be 0 (zero), in any case I think that should not be a warning but rather an exception, since the OrderBy () statement is before the ToList () statement, after ToList () I can do anything under my responsibility because I know I am working with local data in memory, but before ToList () I always assume that query is translated to SQL, the command if it is translated if I put the OrderBy () before the Select (), I will take this into account, that the correct would be first Where () after OrderBy () and last Select ().

thank you, I await your comments

**Comment by ajcvickers** [comment] 2019-03-25 16:42
@osmardavalos see #14935 and #12795

**Closed** 2022-10-16 13:52 UTC
Labels: closed-could-not-reproduce, customer-reported
