### ISSUE TITLE
table name migration issue after updating to 2.0preview

### ISSUE THREAD

**Issue by joeaudette** [dotnet/efcore#9292] opened 2017-07-28 20:03 UTC
I'm updating a large app from efcore 1.1 to 2.0 preview.

For my Entity SiteSettings I previously had

    entity.ForSqlServerToTable("cs_Sites");

which seems to have gone away in 2.0 so I changed it like this:

    entity.ToTable("cs_Sites");

after a model change I generated a migration and in the migration code I see what looks incorrect to me, like it wants to rename tables like this:

    migrationBuilder.DropPrimaryKey(
			name: "PK_Sites",
			table: "Sites");
			
    migrationBuilder.RenameTable(
                name: "Sites",
                newName: "cs_Site");

but the table is already cs_Site not Sites

It also seems to want to rename a bunch of indexes ie:

    migrationBuilder.RenameIndex(
                name: "IX_Sites_SiteFolderName",
                table: "cs_Site",
                newName: "IX_cs_Site_SiteFolderName");

Why did it do that and what should I do to fix it?

**Comment by joeaudette** [comment] 2017-07-29 12:45
I "think" I may have figured out how to solve this. Looks like I should probably edit the existing ModelSnapshot that was previously generated using efcore1x which currently has this:

    b.ToTable("Sites");
    b.HasAnnotation("SqlServer:TableName", "cs_Site");

to just this:

    b.ToTable("cs_Site");

and similarly remove other .HasAnnotation that have sqlserver specific info

**Comment by bricelam** [comment] 2017-07-31 00:31
In the final version of 2.0.0, you should no longer have to update the model snapshot. We'll compensate for the change automatically.

**Comment by joeaudette** [comment] 2017-07-31 11:42
@bricelam good to know! 

Just fyi, not sure if this was needed but to get my app working in preview2 I manually edited all the .designer.cs files for previous migrations as well as the snapshot to remove all the sqlserver annotations and use the more standard syntax. I backed up my original migrations and generated a new one with 20preview then restored the originals and compared the syntax with the newly generated migration

**Comment by ajcvickers** [comment] 2017-08-14 21:47
Duplicate of #8925

**Closed** 2022-10-16 11:13 UTC
Labels: closed-duplicate
