### ISSUE TITLE
Inserting row results in success or 'FOREIGN KEY constrain error' depending on how the object was constructed in code

### ISSUE THREAD

**Issue by jorisvergeer** [dotnet/efcore#14586] opened 2019-02-01 22:32 UTC
I use a sqlite database. 

Simple model: Users <-- UserBoards --> Boards
User and Board have a Guid Id.
UserBoard is a pivot table fot the many to many relation containing the UserId and BoardId columns.

Then when I try to insert a board for a user, and then add an entry in UserBoards. Then I get `Exception message: SQLite Error 19: 'FOREIGN KEY constraint failed'.`

Now this exception only occurs when I insert like this:

```c#
context.Add(new UserBoard 
{ 
    UserId = userIdentifierGuid, 
    BoardId = boardIdentifierGuid
});
```

And it works fine when using it like this:

```c#
context.Add(new UserBoard 
{ 
  User = new User { Id = userIdentifierGuid }, 
  Board = new Board { Id = boardIdentifierGuid }
});
```

And now the shocker:
When I enable sensitive logging, and watch the generated SQL. Then they are identical both times.

```
Failed:

Failed executing DbCommand (6ms) [Parameters=[@p0='80460dcb-1017-4441-b1f1-b0163b9bccc5' (DbType = String), @p1='ad47e83e-3992-4f53-9d78-f90780d87203' (DbType = String)], CommandType='Text', CommandTimeout='30']
INSERT INTO "UserBoards" ("UserId", "BoardId")
VALUES (@p0, @p1);

Success:

        Executed DbCommand (2ms) [Parameters=[@p4='80460dcb-1017-4441-b1f1-b0163b9bccc5' (DbType = String), @p5='bc68a863-dcf8-46ba-8727-0f08b9b8c063' (DbType = String)], CommandType='Text', CommandTimeout='30']
INSERT INTO "UserBoards" ("UserId", "BoardId")
VALUES (@p4, @p5);
```

Why is this happening this way? It doesn't make sense to me.

### Further technical details
EF Core version: 2.2.1
Database Provider:  Microsoft.EntityFrameworkCore.Sqlite 2.2.1
Operating system: Windows 10 
IDE: Visual Studio 2017 15.9.6
Runtime: dotnet core 2.2.102

**Comment by ajcvickers** [comment] 2019-02-11 19:56
@jorisvergeer I have not been able to reproduce this--see my code below. Can you post a small, runnable project/solution or complete code listing (like below) that demonstrates the behavior you are seeing?

```C#
public class User
{
    public Guid Id { get; set; }
    public ICollection<UserBoard> UserBoards { get; set; }
}

public class Board
{
    public Guid Id { get; set; }
    public ICollection<UserBoard> UserBoards { get; set; }
}

public class UserBoard
{
    public Guid UserId { get; set; }
    public User User { get; set; }

    public Guid BoardId { get; set; }
    public Board Board { get; set; }
}

public class BloggingContext : DbContext
{
    //private static readonly LoggerFactory Logger
    //    = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            //.UseLoggerFactory(Logger)
            .UseSqlite("DataSource=testdb");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<UserBoard>().HasKey(e => new {e.UserId, e.BoardId});
    }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new User());

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var user = context.Set<User>().First();

            var board = context.Add(new Board()).Entity;

            context.SaveChanges();

            context.Add(new UserBoard
            {
                UserId = user.Id,
                BoardId = board.Id
            });

            context.SaveChanges();
        }
    }
}
```

**Comment by ajcvickers** [comment] 2019-02-19 21:06
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:50 UTC
Labels: closed-could-not-reproduce, customer-reported
