### ISSUE TITLE
Discriminator enum throws exception when named 'Discriminator'

### ISSUE THREAD

**Issue by vslee** [dotnet/efcore#16581] opened 2019-07-12 02:45 UTC
Consider a model with three entities: a base class and two derived classes. An enum is used as the discriminator. If the discriminator is named 'Discriminator', then this does not work. It may be easier to understand by looking at the simple program below. See the three comments in the code for more info. 

```
Exception message in EF 2.2.6: The property 'Discriminator' cannot be added to type 'Rider' because the type of the corresponding CLR property or field 'EquineBeast' does not match the specified type 'string'.
Stack trace: System.InvalidOperationException: The property 'Discriminator' cannot be added to type 'Rider' because the type of the corresponding CLR property or field 'EquineBeast' does not match the specified type 'string'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddProperty(String name, Type propertyType, MemberInfo memberInfo, ConfigurationSource configurationSource, Nullable`1 typeConfigurationSource)
```

```
Exception message in EF 3.0p6: Constructor on type 'Microsoft.EntityFrameworkCore.Design.OperationExecutor' not found.
Stack trace: System.MissingMethodException: Constructor on type 'Microsoft.EntityFrameworkCore.Design.OperationExecutor' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
```

### Steps to reproduce
```powershell
PM> Add-Migration MyFirstMigration
```
```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace DiscriminatorValueConverterTest226
{
	class Program
	{
		static void Main(string[] args) { }
	}

	public class MyContext : DbContext
	{
		public DbSet<Rider> Riders { get; set; }
		public DbSet<DonkeyRider> DonkeyRiders { get; set; }
		public DbSet<MuleRider> MuleRiders { get; set; }
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlServer(@"Data Source=" + System.Environment.MachineName +
				";Initial Catalog=discriminatorValueConverterTest;" + "Integrated Security=True" +
				";Connect Timeout=15;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");
			optionsBuilder.EnableSensitiveDataLogging();
			optionsBuilder.ConfigureWarnings(w => w.Log(
				Microsoft.EntityFrameworkCore.Diagnostics.CoreEventId.SensitiveDataLoggingEnabledWarning));
		}
		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			// modelbuilder statement #1 (will throw exception whether or not this statement is present)
			modelBuilder.Entity<Rider>()
						.Property(e => e.Discriminator)
						.HasConversion<string>();

			// modelbuilder statement #2 (will throw exception whether or not this statement is present)
			modelBuilder.Entity<Rider>()
						.HasDiscriminator<EquineBeast>("Mount")
						.HasValue(EquineBeast.Rider)
						.HasValue<DonkeyRider>(EquineBeast.Donkey)
						.HasValue<MuleRider>(EquineBeast.Mule);
		}
	}

	public enum EquineBeast
	{
		Rider,
		Donkey,
		Mule
	}

	public class Rider
	{
		public int Id { get; set; }
		public EquineBeast Discriminator { get; set; } // renaming this to something else, such as "Mount", fixes the problem in 2.2.6 (not in 3p6)
	}

	public class DonkeyRider : Rider { }
	public class MuleRider : Rider { }
}
```

### Further technical details
EF Core version: 2.2.6 or 3.0 preview 6 (different errors in each)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 pro 1903
IDE: Visual Studio 2019 16.1.3

**Comment by vslee** [comment] 2019-07-12 02:45
May be related to or a duplicate of #15553

**Comment by ajcvickers** [comment] 2019-07-12 16:11
Duplicate of #15553

**Closed** 2022-10-16 14:30 UTC
Labels: closed-duplicate, customer-reported
