### ISSUE TITLE
Update inherited Entity

### ISSUE THREAD

**Issue by koryakinp** [dotnet/efcore#5009] opened 2016-04-08 01:18 UTC
I have the following BaseballDbContext class:

```
public class BaseballDbContext : DbContext
{
   public DbSet<BaseballTeam> teams { get; set; }

   protected override void OnModelCreating(ModelBuilder modelBuilder)
   {
       modelBuilder.Entity<Hitter>();
       modelBuilder.Entity<Pitcher>();
   }
}
```

And my model classes are:

```
public class BaseballTeam
{
    public int Id { get; set; }
    public string teamName { get; set; }
    public List<BaseballPlayer> players { get; set; }
}

public abstract class BaseballPlayer
{
    public int Id { get; set; }
    public int age { get; set; }
    public string name { get; set; }
}

public class Hitter : BaseballPlayer
{
    public int homeruns { get; set; }
}

public class Pitcher : BaseballPlayer
{
    public int strikeouts { get; set; }
}
```

Now I want to update `name` and `homeruns`property of one of the hitters:

```
BaseballTeam team = _ctx.teams.Include(q => q.players).FirstOrDefault();
Hitter hitter = team.players.OfType<Hitter>().FirstOrDefault();
hitter.name = "Tulowitzki";  //that property will be update
hitter.homeruns = 399;       //but that will not :(

int i = team.players.FindIndex(q => q.Id == hitter.Id);
team.players[i] = hitter;

_ctx.Update(team);
_ctx.SaveChanges();
```

After I run the code only player's name got update, but not the homeruns property:

How to update property of both child and parent classes ?

**Comment by ajcvickers** [comment] 2016-04-08 17:25
Looks like a dupe of #4817, which is fixed in the current codebase.

**Comment by divega** [comment] 2016-04-08 18:27
Closing as we are confident that it is a dupe of #4817, but feel free to reopen if it isn't.

**Closed** 2022-10-16 09:35 UTC
