### ISSUE TITLE
EF_Core 3.0 Multiple nested collections include - include then causes program to hang

### ISSUE THREAD

**Issue by HadiSDev** [dotnet/efcore#18468] opened 2019-10-20 13:20 UTC
have 3 or more Include - Include then in a query causes the program to hang or slows the program down a lot.

### Steps to reproduce

try to create a query using LINQ and IQueryable while using 3 Include-IncludeThen combinations:

- `Include(A => A.B).ThenInclude(B => B.Q)`
- `Include(A => A.B).ThenInclude(B => B.P)`
- `Include(A => A.B).ThenInclude(B => B.L)`

Q has to be another entity
P has to the same entity type of Q
L has to be a collection  of another entity type

For example, I have a database where I store sports data. (Matches, Leagues, Bets, Teams)

I have I method where I can retrieve All available leagues, which should include the leagues, all the matches in the league, and all the bets included in each match:

``` C#
        public IQueryable<LeaguesWithMatchesDTO> GetAvailableLeagues(IEnumerable<int> leagueIds)
        {
            var leagues = _context.Leagues.Include(l => l.Matches).ThenInclude(m => m.HomeTeam)
                                          .Include(l => l.Matches).ThenInclude(m => m.AwayTeam)
                                          .Include(l => l.Matches).ThenInclude(m => m.Bets)
                                          .Where(l => leagueIds.Contains(l.LeagueId))
                                          .Select(l => DTOConverter.ConvertLeagueWithMatchesToDTO(l));

            return leagues;
        }
```

If I remove the ".Include(l => l.Matches).ThenInclude(m => m.Bets)" line then no problem occures.

### Further technical details

EF Core version: 3.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system: WIN10
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment] 2019-10-21 01:47
Duplicate of #18022

**Closed** 2022-10-16 14:51 UTC
Labels: customer-reported
