### ISSUE TITLE
SaveChangesAsync_accepts_changes_with_ConfigureAwait_true failed in C.I.

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#33489] opened 2024-04-07 20:09 UTC
```
[Check failure on line 1 in Microsoft.EntityFrameworkCore.Query.AdHocMiscellaneousQueryInMemoryTest.SaveChangesAsync_accepts_changes_with_ConfigureAwait_true](https://github.com/dotnet/efcore/pull/33488/files#annotation_20167115462) 

@azure-pipelinesazure-pipelines
/ efcore-ci
Microsoft.EntityFrameworkCore.Query.AdHocMiscellaneousQueryInMemoryTest.SaveChangesAsync_accepts_changes_with_ConfigureAwait_true
Assert.True() Failure
Expected: True
Actual:   False
   at Microsoft.EntityFrameworkCore.AdHocMiscellaneousQueryTestBase.SaveChangesAsync_accepts_changes_with_ConfigureAwait_true() in D:\a\_work\1\s\test\EFCore.Specification.Tests\Query\AdHocMiscellaneousQueryTestBase.cs:line 1401
--- End of stack trace from previous location ---
```

**Comment by AndriySvyryd** [comment] 2024-09-24 00:44
Duplicate of #34727

**Closed by AndriySvyryd** 2024-09-24 00:44 UTC
Labels: type-bug, area-test, area-in-memory, area-save-changes, punted-for-9.0
