### ISSUE TITLE
Feature Enhancement: Nondestructive bundling and rewriting of migrations

### ISSUE THREAD

**Issue by ronnyek** [dotnet/efcore#31591] opened 2023-08-30 15:06 UTC
I develop with efcore, and make heavy use of code first and migrations. I think what's there works amazingly well. 

What I've recently noticed was a need to roll up a range of migrations into a single migration with a different name. We use migrations exactly as I think most do, in every day development. That part works great. 

When we go to release the next version of our service, I'd like to be able to take everything since 1.0.0 and roll it into a single migration and call it 1.0.1.  I could then basically handle migrations for 1.0.1 by saying migrate to service version. If there is a problem and I need to rollback, I could just downgrade the service and run migrate to 1.0.0. 

I'm aware that I could effectively remove migrations I want to roll into a new bigger migration, and then create a new migration, but I don't know if I can easily say rollback everything after 1.0.0, and ideally I'd prefer not to have to go and drop those tables and recreate them.

Ultimately it'd be nice to be able to rewrite migrations by saying `dotnet ef migrations merge <since v1.0.0> to <latest> v1.0.1`. Given that would probably be fairly involved, another option would be some way of... tagging a migration and being able to use that tag as a target. So when I release push 1.0.1, I can tag the latest migration as 1.0.1. Then I just know when I deploy this service my stuff will run migration to 1.0.1 tag, otherwise if it needs to rollback, rollback to 1.0.0 tag.

I don't know. I don't care so much about how specifically the problem is solved, I just feel like migrations are fulfilling like 80-90%+ our needs and seems like it'd be natural to include some ways to maintain the created migrations in a less destructive to the dev environment way.

**Comment by roji** [comment] 2023-08-30 16:03
@ronnyek is this different from squashing migrations (#2174)? Once that's done, you'll likely be able to squash all the 1.0.0 migrations into a single migration (and call it 1.0.0), at which point you can tell EF to migrate your database the a specific version.

**Comment by ronnyek** [comment] 2023-08-30 17:21
@roji I read through that thread earlier but didn't get the impression there was necessarily going to be development made. If that other issue is something the team may evaluate for improvements for squashing (that isn't just delete migrations, delete efmigrationhistory table), I'm perfectly ok with that.. Sorry for any confusion

**Comment by roji** [comment] 2023-08-30 23:00
@ronnyek yeah, I think the migration squashing feature would cover what you're looking for. I'll go ahead and close this as a duplicate of that, but feel free to post further here or on the other issue.

**Comment by roji** [comment] 2023-08-30 23:00
Duplicate of #2174

**Closed by roji** 2023-08-30 23:00 UTC
Labels: customer-reported
