### ISSUE TITLE
Wrong exception message - SavepointsDisabledBecauseOfMARS

### ISSUE THREAD

**Issue by DimchoLakov** [dotnet/efcore#24661] opened 2021-04-14 15:04 UTC
Hi. 

I have a method that contains a transaction.

```C#
        public async Task<Result> MyMethod()
        {
            using var myTransaction = await this.dbContext
				.Database
				.BeginTransactionAsync();

            try
            {
		// Do magic
            }
            catch (Exception e)
            {
                await myTransaction.RollbackAsync();

		// Log error
            }
        }
```
I also have MARS enabled --> MultipleActiveResultSets=true.
Serilog is used for logging.

In the log I get the following message --> 
    `Savepoints are disabled because Multiple Active Result Sets (MARS) is enabled. If 'SaveChanges' fails, then the transaction 
    cannot be automatically rolled back to a known clean state. Instead, the transaction should be rolled back by the application 
    before retrying 'SaveChanges'. See https://go.microsoft.com/fwlink/?linkid=2149338 for more information. To identify the 
    code which triggers this warning, call 'ConfigureWarnings(w => 
    w.Throw(RelationalEventId.SavepointsDisabledBecauseOfMARS))'.`

The problem is that `RelationalEventId` does not contain `SavepointsDisabledBecauseOfMARS`. That's in `SqlServerEventId` instead.

### Provider and version information

EF Core version: 5.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10 Pro x64
IDE: Visual Studio 2019 16.4

**Comment by roji** [comment] 2021-04-14 15:52
Duplicate of #24019

**Closed** 2022-10-16 19:31 UTC
Labels: customer-reported
