### ISSUE TITLE
Migrations: Provide async APIs 

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#571] opened 2014-08-20 21:25 UTC
HistoryRepository etc.

**Comment by laskoviymishka** [comment] 2015-09-11 19:18
@rowanmiller @anpete @bricelam Hi everyone, I think this already implemented as part of fix for #2212 issue.

**Comment by bricelam** [comment] 2015-09-14 16:18
@laskoviymishka Good eye. Closing as a dupe of #2212

**Closed** 2022-10-16 08:42 UTC
