### ISSUE TITLE
Using Query Filter with left join generated by navigation property

### ISSUE THREAD

**Issue by dmytroshunkov** [dotnet/efcore#15933] opened 2019-06-04 08:38 UTC
Query filter configured for parent entity producing query which selects primary key value even if row was filtered out.

```c#
public class BloggingContext : DbContext
{
	public DbSet<Blog> Blogs { get; set; }
	public DbSet<Post> Posts { get; set; }

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//		=> optionsBuilder.UseInMemoryDatabase()
		=> optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=LeftJoinQueryFilter;Trusted_Connection=True;")
//			.UseLoggerFactory(Logger.MyLoggerFactory)
			;

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Blog>().HasQueryFilter(p => !p.IsDeleted);
	}
}

public class Blog
{
	public int Id { get; set; }
	public string Title { get; set; }
	public bool IsDeleted { get; set; }

	public ICollection<Post> Posts { get; set; }
}

public class Post
{
	public int Id { get; set; }
	public string Title { get; set; }

	public int? BlogId { get; set; }
	public Blog Blog { get; set; }
}

public class PostDTO
{
	public int Id { get; set; }
	public string Title { get; set; }
	public BlogDTO Blog { get; set; }
}

public class BlogDTO
{
	public int? Id { get; set; }
	public string Title { get; set; }
}

void Main()
{
	using (var context = new BloggingContext())
	{
		context.Database.EnsureDeleted();
		context.Database.EnsureCreated();

		context.Add(new Post
		{
			Title = "Post 1"
		});

		context.AddRange(new[]
		{
			new Blog {
				Title = "Blog 1",
				Posts = new[]
				{
					new Post { Title = "Post 2" },
					new Post { Title = "Post 3" },
				}
			},
			new Blog {
				Title = "Blog 2",
				IsDeleted = true,
				Posts = new[]
				{
					new Post { Title = "Post 4" },
					new Post { Title = "Post 5" }
				}
			}
		});
		
		context.SaveChanges();
	}
	
	using (var context = new BloggingContext())
	{
		var list = context.Posts.Select(p => new PostDTO
		{
			Id = p.Id,
			Title = p.Title,
			Blog = new BlogDTO
			{
				Id = p.Blog.Id,
				Title = p.Blog.Title
			}
		})
		.ToList();
		
		foreach (var post in list)
		{
			Console.WriteLine($"Post.Id: {post.Id}, Post.Title: {post.Title}, Blod.Id: {post.Blog.Id?.ToString() ?? "(null)"}, Blog.Title: {post.Blog.Title ?? "(null)"}");
		}
	}
}
```
Output:
```
Post.Id: 1, Post.Title: Post 1, Blod.Id: (null), Blog.Title: (null)
Post.Id: 2, Post.Title: Post 2, Blod.Id: 1, Blog.Title: Blog 1
Post.Id: 3, Post.Title: Post 3, Blod.Id: 1, Blog.Title: Blog 1
Post.Id: 4, Post.Title: Post 4, Blod.Id: 2, Blog.Title: (null)
Post.Id: 5, Post.Title: Post 5, Blod.Id: 2, Blog.Title: (null)
```
Notice the difference between Post with Id `1` (has no Blog initially) and those with Id `4`, `5` (Blog filtered by query filter) - **no way** to determine if parent entity was filtered out by filter (for example, checking Blog.Id for null).

Generated Sql:
```SQL
SELECT [p].[Id], [p].[Title], [p].[BlogId] AS [Id0], [t].[Title] AS [Title0]
FROM [Posts] AS [p]
LEFT JOIN (
    SELECT [p0].*
    FROM [Blogs] AS [p0]
    WHERE [p0].[IsDeleted] = 0
) AS [t] ON [p].[BlogId] = [t].[Id]
```
Generated Sql query result:
```
Id	Title	Id0	Title0
1	Post 1	NULL	NULL
2	Post 2	1	Blog 1
3	Post 3	1	Blog 1
4	Post 4	2	NULL
5	Post 5	2	NULL
```

So the problem is query filter applied to subquery before left join, but not as left join condition and value of PK for select is mapped from left side of resulted join, not the right side (which is NULL for filtered rows).

Expected query and result:
```SQL
SELECT [p].[Id], [p].[Title], [t].[Id] AS [Id0], [t].[Title] AS [Title0]
FROM [Posts] AS [p]
LEFT JOIN (
    SELECT [p0].*
    FROM [Blogs] AS [p0]
) AS [t] ON [p].[BlogId] = [t].[Id] AND [t].[IsDeleted] = 0
```
```
Id	Title	Id0	Title0
1	Post 1	NULL	NULL
2	Post 2	1	Blog 1
3	Post 3	1	Blog 1
4	Post 4	NULL	NULL
5	Post 5	NULL	NULL
```

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.9.12)

**Comment by smitpatel** [comment] 2019-06-04 14:26
Duplicate of #13517

**Closed** 2022-10-16 14:23 UTC
Labels: customer-reported
