### ISSUE TITLE
Projection 1 + N queries EF Core 2.1 preview 2

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#11777] opened 2018-04-23 10:25 UTC
Dear Maintainer,

I got an Linq query with a projection that results in `1 + 2 N` SQL queries, and I thought EF Core 2.1 would fix my problem. But it turned out it still results in the same queries.

Similar issue (which is marked as fixed)
https://github.com/aspnet/EntityFrameworkCore/issues/4007

### Steps to reproduce
UPDATED: See below for a non scalar projection query

I am using a model and query similar to this
```
public class Foo
{
    public Guid Id { get; set; }
    public Foo Parent { get; set; }
    public Guid? ParentId { get; set; }
    public ICollection<Bar> Bars { get; set; } = new List<Bar>();
}

public class Bar
{
    public Guid Id { get; set; }
    [Required] public Foo Foo { get; set; }
    [Required] public Guid FooId { get; set; }
    [Required] public bool IsSomething { get; set; }
    [Required] public int Data { get; set; }
}
```

```
await context.Foos
    .Where(foo => foo.Bars.Any(bar => bar.Data >= 0) || 
        foo.Parent.Bars.Any(baz => baz.IsSomething))
    .Select(foo => new
    {
        Foo = foo,
        IsSomething = foo.Bars.Any(bar => bar.IsSomething) || 
            foo.Parent.Bars.Any(baz => baz.IsSomething)
    })
    .ToListAsync();
```

With two foo's in the database this results in the following log:
```
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.0-preview2-30571 initialized 'Context' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (20ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [foo].[Id], [foo].[ParentId], [foo.Parent].[Id]
      FROM [Foos] AS [foo]
      LEFT JOIN [Foos] AS [foo.Parent] ON [foo].[ParentId] = [foo.Parent].[Id]
      WHERE EXISTS (
          SELECT 1
          FROM [Bars] AS [bar]
          WHERE ([bar].[Data] >= 0) AND ([foo].[Id] = [bar].[FooId])) OR EXISTS (
          SELECT 1
          FROM [Bars] AS [baz]
          WHERE ([baz].[IsSomething] = 1) AND ([foo.Parent].[Id] = [baz].[FooId]))
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[@_outer_Id='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
      SELECT CASE
          WHEN EXISTS (
              SELECT 1
              FROM [Bars] AS [bar1]
              WHERE ([bar1].[IsSomething] = 1) AND (@_outer_Id = [bar1].[FooId]))
          THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
      END
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[@_outer_Id1='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
      SELECT CASE
          WHEN EXISTS (
              SELECT 1
              FROM [Bars] AS [baz1]
              WHERE ([baz1].[IsSomething] = 1) AND (@_outer_Id1 = [baz1].[FooId]))
          THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
      END
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[@_outer_Id='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
      SELECT CASE
          WHEN EXISTS (
              SELECT 1
              FROM [Bars] AS [bar1]
              WHERE ([bar1].[IsSomething] = 1) AND (@_outer_Id = [bar1].[FooId]))
          THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
      END
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[@_outer_Id1='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
      SELECT CASE
          WHEN EXISTS (
              SELECT 1
              FROM [Bars] AS [baz1]
              WHERE ([baz1].[IsSomething] = 1) AND (@_outer_Id1 = [baz1].[FooId]))
          THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
      END
```

### Further technical details
EF Core version: 2.1.0-preview2-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1709
IDE: Visual Studio 2017 15.7 preview 4

Thank you very much.

-edit I have removed non essential code/logs

**Comment by smitpatel** [comment] 2018-04-23 17:46
Duplicate of #11186

**Comment by NiekGr** [comment] 2018-04-24 08:41
The duplicate issue is specifically about scalar projections.
I have updated my queries to do the scalar operations in memory but the queries are still `1 + N`.

I have created a new testcase
```
public class Foo
{
    public Guid Id { get; set; }
    public ICollection<Bar> Bars { get; set; } = new List<Bar>();
}

public class Bar
{
    public Guid Id { get; set; }
    [Required] public Foo Foo { get; set; }
    [Required] public Guid FooId { get; set; }
}
```
```
await context.Foos
    .Select(foo => new
    {
        Foo = foo,
        FooBar = foo.Bars.FirstOrDefault(bar => bar.Id == Guid.NewGuid()),
    })
    .ToListAsync();
```
```
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.0-preview2-30571 initialized 'Context' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [foo].[Id]
      FROM [Foos] AS [foo]
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[@_outer_Id='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [bar].[Id], [bar].[FooId]
      FROM [Bars] AS [bar]
      WHERE ([bar].[Id] = NEWID()) AND (@_outer_Id = [bar].[FooId])
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[@_outer_Id='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [bar].[Id], [bar].[FooId]
      FROM [Bars] AS [bar]
      WHERE ([bar].[Id] = NEWID()) AND (@_outer_Id = [bar].[FooId])
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[@_outer_Id='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [bar].[Id], [bar].[FooId]
      FROM [Bars] AS [bar]
      WHERE ([bar].[Id] = NEWID()) AND (@_outer_Id = [bar].[FooId])
```

**Comment by smitpatel** [comment] 2018-04-24 17:12
@NiekGr - That one would be duplicate of #10001

**Comment by NiekGr** [comment] 2018-04-25 08:09
Oké, sorry for the trouble.

Thank you for helping.

**Closed** 2022-10-16 12:20 UTC
Labels: closed-duplicate
