### ISSUE TITLE
Async method not executed!

### ISSUE THREAD

**Issue by AhmedAbuelnour** [dotnet/efcore#10041] opened 2017-10-11 10:20 UTC
I'm building an application, where my repository have all my database access logic, all of me repository methods are async

some simple queries such as 
```C#
public async Task<Product> GetByIdAsync(string id)
{
      return await  CurrentContext.Products.FindAsync(id);
}
```
it does not work some time, for example when i try to send an id for my product, the CPU goes up to 70% using, and no result is returned,  and some time the same code when i search for another product it gets it without and problem

in the case that it didn't work, i tried everything but there is nothing worked, and after converting my async query to sync it worked beautifully
```C#
public Product GetByIdAsync(string id)
{
      return CurrentContext.Products.Find(id);
}
```
I'm using EF Core 2.0 and SQL Server 2017

**Comment by ajcvickers** [comment] 2017-10-11 15:59
@A7medRamadan Unfortunately there is not enough information here for us to be able to effectively investigate the issue. Can you post a project or complete code listing that will allow us to reproduce what you are seeing?

**Comment by A7medRamadan** [comment] 2017-10-11 16:26
@ajcvickers This is not an option for me to post all of my project, but as i defined earlier.

in my computer everything works great but when i moved my project to another computer with less resources the problem starts to shows up

**Comment by ajcvickers** [comment] 2017-10-11 16:36
@A7medRamadan I understand that it may not be possible for you to send us your produce code, but if you are able to create a small project that reproduces what you are seeing, then we can investigate. As it is now, there is no way for us to reproduce what you are seeing which means we are not able to investigate in any reasonable way.

**Comment by ajcvickers** [comment] 2017-10-18 18:05
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:53 UTC
Labels: closed-could-not-reproduce
