### ISSUE TITLE
Make SQL connection string readonly at runtime

### ISSUE THREAD

**Issue by mohammad-zr** [dotnet/efcore#27256] opened 2022-01-23 11:34 UTC
Is there anyway to make connection string readonly for some selects (by adding ApplicationIntent=readonly to connection string)?
I tried `_dbContext.Database.SetConnectionString(readonlyConnectionString)` but it changes connection in whole application (instead of just that specific request)

**Comment by roji** [comment] 2022-01-23 20:50
@Esniper90 calilng _dbContext.Database.SetConnectionString should definitely affect only the context instance it's called on, and not the whole application. Please submit a runnable, minimal code sample showing the problematic behavior.

**Comment by Esniper90** [comment] 2022-01-23 21:03
> @Esniper90 calilng _dbContext.Database.SetConnectionString should definitely affect only the context instance it's called on, and not the whole application. Please submit a runnable, minimal code sample showing the problematic behavior.

I figured out that problem is because I am using `AddDbContextPool `. When I use `AddDbContext` it works. 

Now my question is that is it a good idea to use `SetConnectionString` everywhere I want to use readonly database?
Do you have any other suggestion?

**Comment by roji** [comment] 2022-01-23 21:07
See #25024 for a discussion on this.

Bottom-line, I don't think there's any particular problem with using SetConnectionString. You can even do this with AddDbContextPool - you just have to make sure to switch it back before you dispose the context instance. You can add an extension method over your DbContext which sets the connection string, and returns an IDisposable which resets it back when disposed, this way you can use this in a C# `using` statement.

**Comment by roji** [comment] 2022-01-23 21:07
Duplicate of #25024

**Closed** 2022-10-16 20:23 UTC
Labels: closed-duplicate, customer-reported
