### ISSUE TITLE
Linq statements with nested ThenIncludes() generate SQL that fails

### ISSUE THREAD

**Issue by owaits** [dotnet/efcore#16605] opened 2019-07-15 21:06 UTC
I am having problems with complex inner joins from the Linq syntax after upgrading to Preview 6. I get the error Msg 4104, Level 16, State 1, Line 21 The multi-part identifier "j1.Id" could not be bound.

Here is the Linq statement:
```
result = result
                    .Include(j => j.Areas)
                    .Include(j => j.AccountNavigation)
                    .Include(j => j.Services)
                        .ThenInclude(s => s.SupplierNavigation)
                    .Include(j => j.Services)
                        .ThenInclude(item => item.AreaQuantities)
                            .ThenInclude(q => q.ServicesNavigation)
                                .ThenInclude(q => q.SupplierNavigation)
                    .Include(j => j.HireEquipment)
                        .ThenInclude(q => q.EquipmentNavigation)
                        .ThenInclude(e => e.EquipmentItemEquipmentCategoryNavigation)
                    .Include(j => j.HireEquipment)
                        .ThenInclude(item => item.AreaQuantities)
                            .ThenInclude(q => q.HireEquipmentNavigation)
                                .ThenInclude(q => q.EquipmentNavigation)
                    .OrderBy(j=>j.StartDate);
```

and here is the SQL it runs:

```
SELECT [j].[Id], [j].[CollectionDate], [j].[DaysPerWeek], [j].[Description], [j].[Discount], [j].[EndDate], [j].[Job_Accounts], [j].[Mileage], [j].[PurchaseOrderNumber], [j].[ReturnDate], [j].[RowVersion], [j].[StartDate], [j].[Status], [j].[Title], [j].[VATRate], [a].[Id], [a].[Address1], [a].[Address2], [a].[Company], [a].[ContactName], [a].[County], [a].[DaysPerWeek], [a].[Discount], [a].[Email], [a].[Logo], [a].[MobileNumber], [a].[PhoneNumber], [a].[PostCode], [a].[Town], [j0].[Id], [j0].[Created], [j0].[CreatedBy], [j0].[Description], [j0].[JobLabels_Job], [j0].[Location], [j0].[Modified], [j0].[ModifiedBy], [j0].[Name], [j0].[Notes], [j0].[Plan], [j0].[RowVersion], [j0].[Id], [t].[Id], [t].[ApplyDiscount], [t].[Code], [t].[CostedDaily], [t].[Description], [t].[ItemVATRate], [t].[Job_JobServices], [t].[JobServices_Accounts], [t].[Quantity], [t].[RowVersion], [t].[UnitPrice], [t].[ZeroCost], [t].[Id0], [t].[Address1], [t].[Address2], [t].[Company], [t].[ContactName], [t].[County], [t].[DaysPerWeek], [t].[Discount], [t].[Email], [t].[Logo], [t].[MobileNumber], [t].[PhoneNumber], [t].[PostCode], [t].[Town], [t].[Id1], [t].[CheckCount], [t].[CheckIn], [t].[CheckOut], [t].[Created], [t].[CreatedBy], [t].[JobAreaQuantity_JobAreas], [t].[JobAreaQuantity_JobHireEquipment], [t].[JobAreaQuantity_JobServices], [t].[Modified], [t].[ModifiedBy], [t].[Quantity0], [t].[RowVersion0], [t].[TransportCode], [t].[Id00], [t].[ApplyDiscount0], [t].[Code0], [t].[CostedDaily0], [t].[Description0], [t].[ItemVATRate0], [t].[Job_JobServices0], [t].[JobServices_Accounts0], [t].[Quantity00], [t].[RowVersion00], [t].[UnitPrice0], [t].[ZeroCost0], [t].[Id10], [t].[Address10], [t].[Address20], [t].[Company0], [t].[ContactName0], [t].[County0], [t].[DaysPerWeek0], [t].[Discount0], [t].[Email0], [t].[Logo0], [t].[MobileNumber0], [t].[PhoneNumber0], [t].[PostCode0], [t].[Town0], [j1].[Id], [j4].[Id], [j4].[ItemVATRate], [j4].[JobDetails_EquipmentItem], [j4].[Job_JobHireEquipment], [j4].[Quantity], [j4].[RowVersion], [j4].[SearchHelper], [j4].[UnitPrice], [j4].[ZeroCost]
FROM [Jobs] AS [j]
INNER JOIN [AccountsSet] AS [a] ON [j].[Job_Accounts] = [a].[Id]
LEFT JOIN [JobAreas] AS [j0] ON [j].[Id] = [j0].[JobLabels_Job]
LEFT JOIN (
    SELECT [j1].[Id], [j1].[ApplyDiscount], [j1].[Code], [j1].[CostedDaily], [j1].[Description], [j1].[ItemVATRate], [j1].[Job_JobServices], [j1].[JobServices_Accounts], [j1].[Quantity], [j1].[RowVersion], [j1].[UnitPrice], [j1].[ZeroCost], [a0].[Id] AS Id0, [a0].[Address1], [a0].[Address2], [a0].[Company], [a0].[ContactName], [a0].[County], [a0].[DaysPerWeek], [a0].[Discount], [a0].[Email], [a0].[Logo], [a0].[MobileNumber], [a0].[PhoneNumber], [a0].[PostCode], [a0].[Town], [t0].[Id] AS Id1, [t0].[CheckCount], [t0].[CheckIn], [t0].[CheckOut], [t0].[Created], [t0].[CreatedBy], [t0].[JobAreaQuantity_JobAreas], [t0].[JobAreaQuantity_JobHireEquipment], [t0].[JobAreaQuantity_JobServices], [t0].[Modified], [t0].[ModifiedBy], [t0].[Quantity] AS Quantity0, [t0].[RowVersion] AS RowVersion0, [t0].[TransportCode], [t0].[Id0] AS Id00, [t0].[ApplyDiscount] AS ApplyDiscount0, [t0].[Code] AS Code0, [t0].[CostedDaily] AS CostedDaily0, [t0].[Description] AS Description0, [t0].[ItemVATRate] AS ItemVATRate0, [t0].[Job_JobServices] AS Job_JobServices0, [t0].[JobServices_Accounts] AS JobServices_Accounts0, [t0].[Quantity0] AS Quantity00, [t0].[RowVersion0] AS RowVersion00, [t0].[UnitPrice] AS UnitPrice0, [t0].[ZeroCost] AS ZeroCost0, [t0].[Id1] AS Id10, [t0].[Address1] AS Address10, [t0].[Address2] AS Address20, [t0].[Company] AS Company0, [t0].[ContactName] AS ContactName0, [t0].[County] AS County0, [t0].[DaysPerWeek] AS DaysPerWeek0, [t0].[Discount] AS Discount0, [t0].[Email] AS Email0, [t0].[Logo] AS Logo0, [t0].[MobileNumber] AS MobileNumber0, [t0].[PhoneNumber] AS PhoneNumber0, [t0].[PostCode] AS PostCode0, [t0].[Town] AS Town0
    FROM [JobServicesSet] AS [j1]
    LEFT JOIN [AccountsSet] AS [a0] ON [j1].[JobServices_Accounts] = [a0].[Id]
    LEFT JOIN (
        SELECT [j2].[Id], [j2].[CheckCount], [j2].[CheckIn], [j2].[CheckOut], [j2].[Created], [j2].[CreatedBy], [j2].[JobAreaQuantity_JobAreas], [j2].[JobAreaQuantity_JobHireEquipment], [j2].[JobAreaQuantity_JobServices], [j2].[Modified], [j2].[ModifiedBy], [j2].[Quantity], [j2].[RowVersion], [j2].[TransportCode], [j3].[Id] AS Id0, [j3].[ApplyDiscount], [j3].[Code], [j3].[CostedDaily], [j3].[Description], [j3].[ItemVATRate], [j3].[Job_JobServices], [j3].[JobServices_Accounts], [j3].[Quantity] AS Quantity0, [j3].[RowVersion] AS RowVersion0, [j3].[UnitPrice], [j3].[ZeroCost], [a1].[Id] AS Id1, [a1].[Address1], [a1].[Address2], [a1].[Company], [a1].[ContactName], [a1].[County], [a1].[DaysPerWeek], [a1].[Discount], [a1].[Email], [a1].[Logo], [a1].[MobileNumber], [a1].[PhoneNumber], [a1].[PostCode], [a1].[Town]
        FROM [JobAreaQuantities] AS [j2]
        LEFT JOIN [JobServicesSet] AS [j3] ON [j2].[JobAreaQuantity_JobServices] = [j3].[Id]
        LEFT JOIN [AccountsSet] AS [a1] ON [j3].[JobServices_Accounts] = [a1].[Id]
    ) AS [t0] ON [j1].[Id] = [t0].[JobAreaQuantity_JobServices]
) AS [t] ON [j].[Id] = [t].[Job_JobServices]
LEFT JOIN [JobHireEquipment] AS [j4] ON [j].[Id] = [j4].[Job_JobHireEquipment]
WHERE ([j].[Id] = @__id_0) AND @__id_0 IS NOT NULL
ORDER BY [j].[StartDate], [j].[Id], [a].[Id], [j0].[Id], [j1].[Id]

```

If I run this SQL manually against the database it also fails with the same error. I had to modify the [j1].[Id] to [t].[Id] to get the query to function correctly. It looks like the entity framework is generating invalid queries from the linq statement.

Here is the SQL the worked against the database.

```
declare @__id_0 int
set @__id_0 = 1

SELECT [j].[Id], [j].[CollectionDate], [j].[DaysPerWeek], [j].[Description], [j].[Discount], [j].[EndDate], [j].[Job_Accounts], [j].[Mileage], [j].[PurchaseOrderNumber], [j].[ReturnDate], [j].[RowVersion], [j].[StartDate], [j].[Status], [j].[Title], [j].[VATRate], [a].[Id], [a].[Address1], [a].[Address2], [a].[Company], [a].[ContactName], [a].[County], [a].[DaysPerWeek], [a].[Discount], [a].[Email], [a].[Logo], [a].[MobileNumber], [a].[PhoneNumber], [a].[PostCode], [a].[Town], [j0].[Id], [j0].[Created], [j0].[CreatedBy], [j0].[Description], [j0].[JobLabels_Job], [j0].[Location], [j0].[Modified], [j0].[ModifiedBy], [j0].[Name], [j0].[Notes], [j0].[Plan], [j0].[RowVersion], [j0].[Id], [t].[Id], [t].[ApplyDiscount], [t].[Code], [t].[CostedDaily], [t].[Description], [t].[ItemVATRate], [t].[Job_JobServices], [t].[JobServices_Accounts], [t].[Quantity], [t].[RowVersion], [t].[UnitPrice], [t].[ZeroCost], [t].[Id0], [t].[Address1], [t].[Address2], [t].[Company], [t].[ContactName], [t].[County], [t].[DaysPerWeek], [t].[Discount], [t].[Email], [t].[Logo], [t].[MobileNumber], [t].[PhoneNumber], [t].[PostCode], [t].[Town], [t].[Id1], [t].[CheckCount], [t].[CheckIn], [t].[CheckOut], [t].[Created], [t].[CreatedBy], [t].[JobAreaQuantity_JobAreas], [t].[JobAreaQuantity_JobHireEquipment], [t].[JobAreaQuantity_JobServices], [t].[Modified], [t].[ModifiedBy], [t].[Quantity0], [t].[RowVersion0], [t].[TransportCode], [t].[Id00], [t].[ApplyDiscount0], [t].[Code0], [t].[CostedDaily0], [t].[Description0], [t].[ItemVATRate0], [t].[Job_JobServices0], [t].[JobServices_Accounts0], [t].[Quantity00], [t].[RowVersion00], [t].[UnitPrice0], [t].[ZeroCost0], [t].[Id10], [t].[Address10], [t].[Address20], [t].[Company0], [t].[ContactName0], [t].[County0], [t].[DaysPerWeek0], [t].[Discount0], [t].[Email0], [t].[Logo0], [t].[MobileNumber0], [t].[PhoneNumber0], [t].[PostCode0], [t].[Town0], [t].[Id], [j4].[Id], [j4].[ItemVATRate], [j4].[JobDetails_EquipmentItem], [j4].[Job_JobHireEquipment], [j4].[Quantity], [j4].[RowVersion], [j4].[SearchHelper], [j4].[UnitPrice], [j4].[ZeroCost]
FROM [Jobs] AS [j]
INNER JOIN [AccountsSet] AS [a] ON [j].[Job_Accounts] = [a].[Id]
LEFT JOIN [JobAreas] AS [j0] ON [j].[Id] = [j0].[JobLabels_Job]
LEFT JOIN (
    SELECT [j1].[Id], [j1].[ApplyDiscount], [j1].[Code], [j1].[CostedDaily], [j1].[Description], [j1].[ItemVATRate], [j1].[Job_JobServices], [j1].[JobServices_Accounts], [j1].[Quantity], [j1].[RowVersion], [j1].[UnitPrice], [j1].[ZeroCost], [a0].[Id] AS Id0, [a0].[Address1], [a0].[Address2], [a0].[Company], [a0].[ContactName], [a0].[County], [a0].[DaysPerWeek], [a0].[Discount], [a0].[Email], [a0].[Logo], [a0].[MobileNumber], [a0].[PhoneNumber], [a0].[PostCode], [a0].[Town], [t0].[Id] AS Id1, [t0].[CheckCount], [t0].[CheckIn], [t0].[CheckOut], [t0].[Created], [t0].[CreatedBy], [t0].[JobAreaQuantity_JobAreas], [t0].[JobAreaQuantity_JobHireEquipment], [t0].[JobAreaQuantity_JobServices], [t0].[Modified], [t0].[ModifiedBy], [t0].[Quantity] AS Quantity0, [t0].[RowVersion] AS RowVersion0, [t0].[TransportCode], [t0].[Id0] AS Id00, [t0].[ApplyDiscount] AS ApplyDiscount0, [t0].[Code] AS Code0, [t0].[CostedDaily] AS CostedDaily0, [t0].[Description] AS Description0, [t0].[ItemVATRate] AS ItemVATRate0, [t0].[Job_JobServices] AS Job_JobServices0, [t0].[JobServices_Accounts] AS JobServices_Accounts0, [t0].[Quantity0] AS Quantity00, [t0].[RowVersion0] AS RowVersion00, [t0].[UnitPrice] AS UnitPrice0, [t0].[ZeroCost] AS ZeroCost0, [t0].[Id1] AS Id10, [t0].[Address1] AS Address10, [t0].[Address2] AS Address20, [t0].[Company] AS Company0, [t0].[ContactName] AS ContactName0, [t0].[County] AS County0, [t0].[DaysPerWeek] AS DaysPerWeek0, [t0].[Discount] AS Discount0, [t0].[Email] AS Email0, [t0].[Logo] AS Logo0, [t0].[MobileNumber] AS MobileNumber0, [t0].[PhoneNumber] AS PhoneNumber0, [t0].[PostCode] AS PostCode0, [t0].[Town] AS Town0
    FROM [JobServicesSet] AS [j1]
    LEFT JOIN [AccountsSet] AS [a0] ON [j1].[JobServices_Accounts] = [a0].[Id]
    LEFT JOIN (
        SELECT [j2].[Id], [j2].[CheckCount], [j2].[CheckIn], [j2].[CheckOut], [j2].[Created], [j2].[CreatedBy], [j2].[JobAreaQuantity_JobAreas], [j2].[JobAreaQuantity_JobHireEquipment], [j2].[JobAreaQuantity_JobServices], [j2].[Modified], [j2].[ModifiedBy], [j2].[Quantity], [j2].[RowVersion], [j2].[TransportCode], [j3].[Id] AS Id0, [j3].[ApplyDiscount], [j3].[Code], [j3].[CostedDaily], [j3].[Description], [j3].[ItemVATRate], [j3].[Job_JobServices], [j3].[JobServices_Accounts], [j3].[Quantity] AS Quantity0, [j3].[RowVersion] AS RowVersion0, [j3].[UnitPrice], [j3].[ZeroCost], [a1].[Id] AS Id1, [a1].[Address1], [a1].[Address2], [a1].[Company], [a1].[ContactName], [a1].[County], [a1].[DaysPerWeek], [a1].[Discount], [a1].[Email], [a1].[Logo], [a1].[MobileNumber], [a1].[PhoneNumber], [a1].[PostCode], [a1].[Town]
        FROM [JobAreaQuantities] AS [j2]
        LEFT JOIN [JobServicesSet] AS [j3] ON [j2].[JobAreaQuantity_JobServices] = [j3].[Id]
        LEFT JOIN [AccountsSet] AS [a1] ON [j3].[JobServices_Accounts] = [a1].[Id]
    ) AS [t0] ON [j1].[Id] = [t0].[JobAreaQuantity_JobServices]
) AS [t] ON [j].[Id] = [t].[Job_JobServices]
LEFT JOIN [JobHireEquipment] AS [j4] ON [j].[Id] = [j4].[Job_JobHireEquipment]
WHERE ([j].[Id] = @__id_0) AND @__id_0 IS NOT NULL
ORDER BY [j].[StartDate], [j].[Id], [a].[Id], [j0].[Id], [j1].[Id]
```

This code was working on Preview 5 before I upgraded to Preview 6.

**Comment by ajcvickers** [comment] 2019-07-19 19:50
Duplicate of #15611

**Closed** 2022-10-16 14:30 UTC
Labels: closed-duplicate, customer-reported
