### ISSUE TITLE
OSX connection to SQL Server within ASP.Net core

### ISSUE THREAD

**Issue by giuseppemag** [dotnet/efcore#6791] opened 2016-10-17 08:58 UTC
### Steps to reproduce

Setup SQL Server with some DB on a freshly installed Windows machine. Connect to the DB from within another Windows machine in VS Code (any ASP.Net template will do). Run the same project from the same machine with OSX installed and VS Code to see that the connection to the DB cannot be established anymore, even though network, machine, and code are the very same.
### The issue

I am trying to connect to an MSSQL server from a C# ASP.Net core application running in OSX. The MSSQL is on a separate machine which firewall is configured to let connections via TCP to port 1433 and via UDP to port 1434. 

The connection string I am passing to the `optionsBuilder.UseSqlServer` method is:

`Server=IP\SQLEXPRESS;Database=DB_NAME;user id=****;password=*****`

What is very confusing at this point is that _the very same connection string works flawlessly_ from Windows and both Visual Studio and Visual Studio Code. The moment I reboot in my OSX, then VS Code opens the project but raises the dreaded

`System.Data.SqlClient.SqlException: A network-related or 
instance-specific error occurred while establishing a connection
to SQL Server. The server was not found or was not accessible. 
Verify that the instance name is correct and that SQL Server is
configured to allow remote connections. (provider: TCP Provider, 
error: 40 - Could not open a connection to SQL Server)`

exception. I have no idea what to do, as this code should work. What does the OSX implementation of the SQL Server connector do that is so different?
### Further technical details

EF Core version: 1.0.0.0-preview2-final (EF tools), 1.0.1 (SQLServer.Design)
Operating system: OSX and Windows
Visual Studio version: VS Code (Windows and OSX)

**Comment by divega** [comment] 2016-10-17 23:46
@giuseppemag this looks like an exact duplicate of https://github.com/dotnet/corefx/issues/4346 which apparently has been fixed for .NET Core in either 1.1. or 1.2. 

According to the comment at https://github.com/dotnet/corefx/issues/4346#issuecomment-190958230 you can use the _`server name:port number`_ as a workaround.

**Comment by gbrizu** [comment] 2017-05-09 17:58
https://gist.github.com/gbrizu/7de5706e27a5009c98da2355c5ef2218

**Comment by aligenc** [comment] 2018-03-03 14:33
Your sql conn string is true. Check out if the appsettings.production.json is exist. So update the connection string in this file.

**Closed** 2022-10-16 10:38 UTC
