### ISSUE TITLE
Flag indicating running from migration bundle

### ISSUE THREAD

**Issue by mdzieg** [dotnet/efcore#34392] opened 2024-08-09 17:10 UTC
I have a code that should not be executed during design time and inside migration bundle execution.

I can easily exclude migration creation cases with `EF.IsDesignTime` flag.
Unfortunately, I do not see OOTB option to detect if my code is being executed inside the migration bundle.

I use `--startup-project` option to point the main application assembly, as there is configuration I would rather not duplicate. So I do not have any custom startup code for the migration bundle.

SOLUTION:
`EF.ExecutingFromMigrationBundle` flag to easily detect if code is executed from migration bundle.

Static flag can be set directly from generated bundle assembly or achieved in any other way.

**Comment by mdzieg** [comment] 2024-08-09 17:58
Created PR for this: https://github.com/dotnet/efcore/pull/34394

**Comment by ajcvickers** [comment] 2024-08-09 18:20
See also #33445.

@mdzieg Does there need to be a _different_ flag here?

**Comment by mdzieg** [comment] 2024-08-09 19:12
> See also #33445.
> 
> @mdzieg Does there need to be a _different_ flag here?

Good question. For my case it can be the same flag.
We can reduce complexity by setting IsDesignTime flag.

Considering that we have also scripts option, any custom code running just in a bundle context to populate data does not make sense.

Another option would be to set also extra env variable for the process in case it is needed for some corner cases. But flag(s) are more straightforward.

I am fine with either option at the moment. I can adjust my PR if needed to what we agree.

**Comment by roji** [comment] 2024-08-10 10:47
Following @ajcvickers's suggestion, I'd suggest having it be the same flag - making this issue a duplicate of #33445 - until we have an actual request/scenario where the differentiation between bundles and other design-time stuff is needed.

**Closed** 2024-08-12 10:39 UTC
Labels: customer-reported

**Comment by roji** [comment] 2024-08-12 11:17
@mdzieg patches are reserved for high-impact bug changes, see our [release policy for more details](https://learn.microsoft.com/en-us/ef/core/what-is-new/release-planning).
