### ISSUE TITLE
Entity Framework Core - Code-First throws exception

### ISSUE THREAD

**Issue by ribagyula89** [dotnet/efcore#20517] opened 2020-04-03 17:12 UTC
Good afternoon!

I don't know if somebody else run into the same problem with Code-First DB or I just missed something:

I updated to the latest 5.0...preview Nugets last week, and I tried to update my database (SQL Server 14.0.2027). The "add-migration" command created the migration file correctly, but the update-database command throws exception (I added a new property to one of my model, but the Package Manager Console said: invalid column).

I checked it, but is was a simple int column, it was valid... I cleared my DB, cleared the migration folder (and restarted my system...), and call the process (add-migration + update-database) again on the empty database. It throws another exception: after the "Applying migration..." line it throws a "System.IndexOutOfRangeException: Index was outside the bounds of the array".

If I downgrade the Nugets to the latest stable versions (3.1.3), the Code-First steps work well, create the tables and seeds the default data without any problem.

I tried it with the newest Nugets (published on April 2), but throws the same exception on an empty DB:

```
PM> update-database
Build started...
Build succeeded.
Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 5.0.0-preview.2.20159.4 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (26ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (100ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (10ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (204ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [__EFMigrationsHistory] (
          [MigrationId] nvarchar(150) NOT NULL,
          [ProductVersion] nvarchar(32) NOT NULL,
          CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
      );
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (18ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (9ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '20200403163437_Init'.
Applying migration '20200403163437_Init'.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.EntityFrameworkCore.Migrations.Operations.InsertDataOperation.GenerateModificationCommands(IModel model)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(InsertDataOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__71_28(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass15_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Index was outside the bounds of the array.
```

**Comment by ribagyula89** [comment] 2020-04-04 08:45
Hello @ajcvickers 

I created a sample project with the same structure as my original one (without the unnecessary projects and classes).

[https://github.com/ribagyula89/EFCoreExample](url)

(The DB connection string setup is in the EFCoreExample.BL.Identity.DI.ServiceCollectionExtensions.)

If you run the „add-migration [name]” command in Package Manager Console the PM creates the Migration folder and the class. If you call „update-database”, it throws the exception. (Set the Default project to „EFCoreExample.Entities” before the run because the DbContext is in this project.)

If I downgrade the following latest prerelease Nugets to 3.1.3 versions:

– Microsoft.EntityFrameworkCore [in EFCoreExample.Entities]
– Microsoft.EntityFrameworkCore.SqlServer [in EFCoreExample.Entities]
– Microsoft.AspNetCore.Identity.EntityFrameworkCore [in EFCoreExample.Entities]
– Microsoft.EntityFrameworkCore.Tools [in EFCoreExample.Server]
– Microsoft.AspNetCore.Identity.UI [in EFCoreExample.Server]

and call the „update-database” command with the existing migration class (which is created with the 5.0…prerelease package before), get the same exception.

But if I delete the Migrations folder too and run „add-migration + update-database” with the downgraded packages on a clean DB then it creates the tables with the seeded data.

Plus:

I cleared the DB and Migrations folder and update back to the latest prereleases. I commented out the SeedData(modelBuilder) call [Line 31 in EFCoreExample.EntitiesApplicationDbContext.cs].

In this case the migration+update steps worked with the latest prereleases too. So the problem is in the „private void SeedData(ModelBuilder modelBuilder)” method maybe … (maybe the RoleType enum…?)

As I mentioned in the original post, at very first I got an „invalid column” exception when I tried to update my existing DB with a plus column: I tried to add an int column to one of my table and this field was an enum property in my model class.

**Comment by ajcvickers** [comment] 2020-04-06 22:03
@AndriySvyryd This repros for me. I tried to see if it is fixed with the latest 5.0 daily, but then that runs into other errors.

**Comment by AndriySvyryd** [comment] 2020-04-07 00:08
@ajcvickers What errors?

**Comment by fabipeter** [comment] 2020-04-08 00:06
I had the same error when i updated entity framework nuggets to 5.0.0-preview.2.20159.4
but the previous one 5.0.0-preview.2.20120.8 worked, i think the 5.0.0-preview.2.20159.4 is not yet totally stable

**Comment by ajcvickers** [comment] 2020-04-15 18:47
@AndriySvyryd 

```
C:\Stuff\TheirRepros\EFCoreExample-master\EFCoreExample-master\EFCoreExample.Entities>dotnet ef database update -s ..\EFCoreExample\Server\EFCoreExample.Server.csproj
Build started...
Build succeeded.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Internal.SemanticVersionComparer' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor..ctor(IOperationReportHandler reportHandler, IDictionary args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
   at Microsoft.EntityFrameworkCore.Tools.Commands.DatabaseUpdateCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Exception has been thrown by the target of an invocation.

C:\Stuff\TheirRepros\EFCoreExample-master\EFCoreExample-master\EFCoreExample.Entities>
```

**Comment by AndriySvyryd** [comment] 2020-04-15 18:53
@ajcvickers That looks like a global tool version mismatch

**Comment by ajcvickers** [comment] 2020-04-15 19:01
@AndriySvyryd That was with the version that matched the installed SDK. This is with the version that matches the installed EF preview:

```
C:\Stuff\TheirRepros\EFCoreExample-master\EFCoreExample-master\EFCoreExample.Entities>dotnet tool uninstall --global dotnet-ef
Tool 'dotnet-ef' (version '5.0.0-preview.2.20159.4') was successfully uninstalled.

C:\Stuff\TheirRepros\EFCoreExample-master\EFCoreExample-master\EFCoreExample.Entities>dotnet tool install --global dotnet-ef --version 5.0.0-preview.4.20214.3
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '5.0.0-preview.4.20214.3') was successfully installed.

C:\Stuff\TheirRepros\EFCoreExample-master\EFCoreExample-master\EFCoreExample.Entities>dotnet ef database update -s ..\EFCoreExample\Server\EFCoreExample.Server.csproj
Build started...
Build succeeded.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Internal.SemanticVersionComparer' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor..ctor(IOperationReportHandler reportHandler, IDictionary args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
   at Microsoft.EntityFrameworkCore.Tools.Commands.DatabaseUpdateCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Exception has been thrown by the target of an invocation.

C:\Stuff\TheirRepros\EFCoreExample-master\EFCoreExample-master\EFCoreExample.Entities>
```

**Comment by AndriySvyryd** [comment] 2020-04-15 20:18
The issue is in EFCoreExample.BL.Identity.csproj
It has
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
  </ItemGroup>
```

Instead it should reference the shared framework:
```
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```

**Comment by ajcvickers** [comment] 2020-04-15 22:14
@AndriySvyryd Changed that, still getting the same error.

**Comment by AndriySvyryd** [comment] 2020-04-15 23:53
@ajcvickers Well, I don't get it on my machine (I get a different one that's fixed by the PR).

**Closed** 2020-04-15 23:59 UTC
Labels: closed-fixed, type-bug

**Comment by ajcvickers** [comment] 2020-04-16 00:42
Maybe I forgot how to use Windows already... 😉

**Comment by AndriySvyryd** [comment] 2020-04-16 01:45
I think it's because of all the daily build versions. Once we have a coherent preview4 it should become easier
