### ISSUE TITLE
Behavior of query filters with navigations vs. includes

### ISSUE THREAD

**Issue by tuespetre** [dotnet/efcore#11957] opened 2018-05-10 13:59 UTC
Last night I was working on some tests in my project and ran across this *one* test that exhibits behavior that I didn't expect:

https://github.com/aspnet/EntityFrameworkCore/blob/69f870ab1f32b3185c3599887fbe020c0f70c445/src/EFCore.Specification.Tests/Query/FiltersTestBase.cs#L114-L120

https://github.com/aspnet/EntityFrameworkCore/blob/8790253a195064fcd8b0151fb15165523489731e/test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs#L165-L181

The Customer query filter is applied to the include, but not to the expansion of the Customer navigation inside of the Order query filter. I'm not sure if this is semantically correct, or if this just avoids the dreaded infinite circular application of query filters between two or more entity types. If this is by design you can yell at me and click on 'close issue' so hard your mouse and/or trackpad shatters. 😉

**Comment by smitpatel** [comment] 2018-06-06 23:03
Filters need to be applied after running nav expansion on filter.

**Comment by smitpatel** [comment] 2019-01-25 01:07
Assigning to @maumar 
When navigations expands into new entityqueryables, it should introduce associated query filters automatically.

**Comment by smitpatel** [comment] 2019-05-28 16:36
Duplicate of #13361

**Closed** 2022-10-16 12:24 UTC
Labels: closed-duplicate
