### ISSUE TITLE
EF core should probably clear meaningless parentheses in generated sql queries

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/efcore#28615] opened 2022-08-08 08:18 UTC
In my web project I use EF core and as an example there is this C# query:
```cs
ticketsFromDb = await db.Tickets.Where(el => el.CreationPackId == pack.Id && !el.RequesterTerminalId.HasValue && !el.IsSold)
                                .OrderBy(o => EF.Functions.Random())
                                .Take(count)
                                .ToListAsync()
                                .ConfigureAwait(false);
```
... that is translated to this sql query (PostgreSQL):
```sql
SELECT t."Id", t."CreationPackId", t."IsBonus", t."IsSold", t."RequestHoldCount", t."RequesterTerminalId", t."WinSum"
FROM "Tickets" AS t
WHERE ((t."CreationPackId" = @__pack_Id_0) AND ((t."RequesterTerminalId" IS NULL))) AND NOT (t."IsSold")
ORDER BY random()
LIMIT @__p_2
```
The slight problem I see here is that in my original `.Where(...)` there are no parentheses at all, while in the sql there are many. It makes it a bit difficult to read such sql espacially from logs in console, where I do not have IDE experience and cannot just place a cursor to see the openning and closing parentheses highlighted. So I propose several simple rules, that can reduce meaningless parentheses is such cases:
1. Do not add parentheses for "simple" conditions. If to look at my query, here is a clear example: `... AND NOT (t."IsSold")`. `t."IsSold"` is a "simple" condition, so there is no need to wrap it into parentheses. Other "simple" conditions here are `t."CreationPackId" = @__pack_Id_0` and `t."RequesterTerminalId" IS NULL`. `t."RequesterTerminalId" IS NULL` is wrapped into double parentheses here for whatever reason
2. Do not add parentheses for several equal condition concatenation operators (I don't know what is theirs real name). So in condition `((A) AND B) AND C` parentheses  can be safely removed leaving just `A AND B AND C`. When there are different operators , like `A AND B OR C` parentheses should be kept even if they don't have any impact on the expression for clarity reasons I think

These 2 rules can reduce meaningless parentheses in queries, leading to better and clearer sql, that will be easier to read when debugging applications. I also should point out, that this issue is based on EF Core 6. Maybe it is already "fixed" in EF Core 7, I didn't check that.

**Comment by roji** [comment] 2022-08-08 09:48
Duplicate of #26767

**Comment by roji** [comment] 2022-08-08 09:49
Pending work in #27177

**Comment by DoctorKrolic** [comment] 2022-08-08 11:00
@roji The given issue doesn't seems to be fully duplicating this one, as it covers only the `IS NULL` case, however the work item seems to move in the right direction (though is wasn't touched for more than half of a year 😞). Should I close this issue as "not planned" then (I assume you have privileges to do this, but you haven't done it for some reason)?

**Comment by roji** [comment] 2022-08-08 11:12
Yeah, #26767 was originally planned only for that specific `IS NULL` issue, I renamed it to have the wider scope. I'll indeed close this as a duplicate now; as this is about tigher/more esthetic SQL (no functional impact), this hasn't received much attention but I'm hopeful we'll get it in at some point.

**Closed** 2022-08-08 11:12 UTC
Labels: customer-reported
