### ISSUE TITLE
Enum values fail to convert because EF has mapped them to the wrong enum when using .HasConversion<string>

### ISSUE THREAD

**Issue by acrov** [dotnet/efcore#27417] opened 2022-02-09 17:48 UTC
When querying an entity with an enum field that has been mapped with .HasConversion<string>(), Entity Framework Cosmos maps the enum value to the wrong enum and then fails to convert it.  See repro below

Minimal repro to be run with emulator:
```cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

public class WrongEnumContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseCosmos(
            "AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
            "WrongEnum");
        optionsBuilder.EnableDetailedErrors();
        optionsBuilder.EnableSensitiveDataLogging();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultContainer("WrongEnumContext");

        modelBuilder.Entity<Item>().HasKey(item => item.ItemName);

        modelBuilder.Entity<A>().Property(a => a.Color).HasConversion<string>();
        modelBuilder.Entity<A>().OwnsMany(a => a.SubItems,
            subItemBuilder => subItemBuilder.Property(a => a.Color).HasConversion<string>());

        modelBuilder.Entity<B>().Property(b => b.Color).HasConversion<string>();
        modelBuilder.Entity<B>().OwnsMany(b => b.SubItems,
            subItemBuilder => subItemBuilder.Property(b => b.Color).HasConversion<string>());
    }
}

public class Item
{
    public string ItemName { get; set; }
}

public enum ItemAColor
{
    Red,
    Yellow
}

public class A : Item
{
    public ItemAColor Color { get; set; }
    public IEnumerable<SubA> SubItems { get; set; }
}

public class SubA
{
    public ItemAColor Color { get; set; }
}

public enum ItemBColor
{
    Blue,
    Green
}

public class B : Item
{
    public ItemBColor Color { get; set; }
    public IEnumerable<SubB> SubItems { get; set; }
}

public class SubB
{
    public ItemBColor Color { get; set; }
}

public class Program
{
    public static async Task Main()
    {
        await using (var dbContext = new WrongEnumContext())
        {
            await dbContext.Database.EnsureDeletedAsync();
            await dbContext.Database.EnsureCreatedAsync();
            
            await dbContext.Set<Item>().AddAsync(new A
            {
                ItemName = "RedItemA",
                Color = ItemAColor.Red,
                SubItems = new[]
                {
                    new SubA {Color = ItemAColor.Red},
                    new SubA {Color = ItemAColor.Yellow}
                }
            });
            
            await dbContext.SaveChangesAsync();
            
            var allItemA = await dbContext.Set<A>().ToListAsync(); //ok
            var allItemB = await dbContext.Set<B>().ToListAsync(); //ok
            var allItems = await dbContext.Set<Item>().ToListAsync(); //throws
        }
    }
}
```

# Expected behaviour
The set is properly deserialised to entities with enums converted correctly.

# Actual behaviour
The enum conversion uses the incorrect enum type and fails with the following exception
_Cannot convert string value 'Red' from the database to any value in the mapped 'ItemBColor' enum._
but the EF model for class A should be using the ItemAColor enum for this.

Note this exception does not occur in EF5 because the exception was added in EF6. However I suspect the failure to map correctly
prior to EF6 was still happening but the behaviour was to fallback to using the default value of the enum so the conversion failure was silent.

### Include provider and version information

EF Core version: 6.0.2
Database provider: Microsoft.EntityFrameworkCore.Cosmos 6.0.2
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Rider or Command Line

**Comment by AndriySvyryd** [comment] 2022-02-12 02:00
It looks like both `A.SubItems` and `B.SubItems` are always included.

Probably related to https://github.com/dotnet/efcore/issues/26257

**Comment by ajcvickers** [comment] 2022-09-14 14:39
Same root cause as #26257. Verified fixed in latest daily.

**Closed** 2022-10-16 20:25 UTC
Labels: closed-duplicate, customer-reported
