### ISSUE TITLE
DateTime Kind conversion issue in IQueryable

### ISSUE THREAD

**Issue by GerbrandStap** [dotnet/efcore#16509] opened 2019-07-08 12:34 UTC
When a DateTime is loaded from the database and used to initialize an object in the IQueryable.Select(), there is something going wrong with its Kind.
Consider the following code:

```c#
var test = context.Tests.Last();
var model1 = new Model {
    DateTime = test.DateTime,
    DateTimeOffset = test.DateTime
};

var model2 = context.Tests
    .Select(t => new Model {
        DateTime = test.DateTime,
        DateTimeOffset = test.DateTime
    })
    .Last();
```

Logically the same actions are performed. But the DateTime of test and model1 will have Kind 'Local' and model2's DateTime will have Kind 'Unspecified'.
When (implicitly) converted to a DateTimeOffset, both Local and Unspecified DateTimes should result in a DateTimeOffset in the local time zone. For model1 this works as expected, but weirdly enough, model2's DateTimeOffset will be in the UTC time zone.

### Expected behavior
- Both models from the example should have the same contents, because logically they are initialized the same way.
- model1 is initialized with the values that I'd expect
- The DateTimeOffset in model2 should have been in the local time zone, given it DateTime is Unspecified ([see docs](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset.op_implicit?view=netframework-4.8))

### Steps to reproduce
This example solution demonstrates the issue: [EFDateTimeKindBug.zip](https://github.com/aspnet/EntityFrameworkCore/files/3368325/EFDateTimeKindBug.zip)

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio Enterprise 2019 Version 16.1.3

**Comment by ajcvickers** [comment] 2019-07-08 16:13
Duplicate of #4711. Recommendation is to use a `ValueConverter` as [shown here](https://github.com/aspnet/EntityFrameworkCore/issues/4711#issuecomment-358695190)

**Comment by GerbrandStap** [comment] 2019-07-10 07:45
This is not a duplicate of #4711, because I don't mind if the Kind of a DateTime to always be Unspecified. My main issue is the inconsistency of the conversion to DateTimeOffset.

I got back to my example and changed a few things. After each database operation I disposed the DbContext. Otherwise it might use in memory data, which made results even more confusing. Also the value used to convert to 'model2' was the wrong one (test vs. t), but this didn't change the result.
These changes made the Kind of the DateTime property to always be Unspecified, so leave that out of the scope here.

The DateTimeOffset in model1 is converted to the saved time in my local time zone and in model2 to the saved time in UTC, so something like:
model1 = 2019-07-10 09:41:35 +02:00
model2 = 2019-07-10 09:41:35 +00:00

So these DateTimeOffsets are two hours apart in my example.
If the DateTime values are always treated as Unspecified, the DateTimeOffset should always be converted to the local time zone ([see docs](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset.op_implicit?view=netframework-4.8)).

I've attached my updated test project: [EFDateTimeKindBug.zip](https://github.com/aspnet/EntityFrameworkCore/files/3376313/EFDateTimeKindBug.zip)

**Comment by ajcvickers** [comment] 2019-07-10 18:04
@GerbrandStap Thanks! This is, as you say, different; we will discuss.

Triage: this is the SQL we generate:
```sql
SELECT [t].[DateTime], CAST([t].[DateTime] AS datetimeoffset) AS [DateTimeOffset]
FROM [Test] AS [t]
```
So we're doing the conversion to `DataTime` in SQL Server, and it seems that this is the behavior that SQL Server has for this conversion, which differs from what .NET does.

**Comment by ajcvickers** [comment] 2019-07-12 18:06
We discussed this in triage and re don't believe it is possible to get the same behavior on SQL Server as in .NET since the `DateTime.Kind` is not retained in the SQL Server column, and the SQL Server conversion knows nothing about it.

Putting this on the backlog to consider blocking this conversion in translation.

**Comment by GerbrandStap** [comment] 2019-07-16 06:54
OK, great! Thanks for reconsidering.
It seems tricky indeed to mimic the same behavior on the SQL Server side. You don't even have the time zone information of the caller there to perform conversion correctly.
The fact that the conversion was done on the server side explains at least the behavior. And helps us for now to think of a way to solve any problems in our code. So thanks for that and I'll keep an eye on this issue.

**Comment by ajcvickers** [comment] 2020-11-07 21:24
We discussed this again in triage and despite previously saying, "Putting this on the backlog to consider blocking this conversion in translation." we realized that detecting when to block is complex to do without breaking cases where the code is currently working and returning the correct results. Therefore, we are not going to pro-actively do this unless we get more feedback that increases the value.

**Closed** 2022-10-16 14:29 UTC
Labels: type-bug, closed-out-of-scope, customer-reported, area-query
