### ISSUE TITLE
Filtering on boolean properties which are equal to false, causes the created SQL to use a non-equality check e.g "[p].[deleted_flag] <> CAST(1 AS bit)" instead of "[p].[deleted_flag] = CAST(0 AS bit)"

### ISSUE THREAD

**Issue by rxnChip** [dotnet/efcore#24942] opened 2021-05-19 21:27 UTC
The SQL provided is completely valid however is sub optimal as it can cause indexes not to be utilized in certain scenarios as it will treat the condition as a range seek. In cases where you have multiple keys on an index the non-equality check is a deal breaker as it causes the index not be fully utilized as the other keys will not be used after a range seek.

Example 

Domain 
```C#
public class ProductCompatible : AuditableEntity<int>, IAggregateRoot
    {
        public int ProductId { get; private set; }
        public int OptionProductId { get; private set; }
        public int RegionId { get; private set; }
        public bool DeletedFlag { get; private set; }

        public ProductCompatible(int productId, int optionProductId, int regionId)
        {
            this.ProductId = productId;
            this.OptionProductId = optionProductId;
            this.RegionId = regionId;
        }

        public void Delete()
        {
            this.DeletedFlag = true;
        }
    }
```
Configuration
```C#
public class ProductCompatibleConfiguration : IEntityTypeConfiguration<ProductCompatible>
    {
        public void Configure(EntityTypeBuilder<ProductCompatible> builder)
        {
            builder.HasKey(p => p.Id);

            builder.Ignore(p => p.DomainEvents);

            builder.Property(p => p.Id)
                .UseHiLo("product_compatibles_seq");

            builder.Property(p => p.DeletedFlag)
                .HasColumnType("bit")
                .IsRequired()
                .HasDefaultValue(false);

            builder.HasOne<Region>()
                .WithMany()
                .HasForeignKey(x => x.RegionId);

            builder.HasOne<Product>()
                .WithMany()
                .HasForeignKey(x => x.ProductId)
                .OnDelete(DeleteBehavior.NoAction);

            builder.HasOne<Product>()
                .WithMany()
                .HasForeignKey(x => x.OptionProductId)
                .OnDelete(DeleteBehavior.NoAction);

            builder.HasIndex(x => new { x.ProductId, x.RegionId, x.OptionProductId })
                .IncludeProperties(x => new { x.LastModifiedBy, x.LastPersisted, x.Created, x.CreatedBy, x.DeletedFlag})
                .IsUnique()
                .HasFilter("deleted_flag = 0");

        }
    }
```

Repo
```C#
public class ProductCompatibleRepository : IProductCompatibleRepository
    {
        private readonly PmCatalogueContext _context;

        public IUnitOfWork UnitOfWork
        {
            get
            {
                return _context;
            }
        }

        public ProductCompatibleRepository(PmCatalogueContext context)
        {
            _context = context;
        }

        public async Task<List<ProductCompatible>> GetAsync(List<ProductRegionOptionDto> productRegionOptions)
        {
            DataTable dt = new DataTable();
            dt.Columns.Add(new DataColumn("product_id", typeof(int)) { AllowDBNull = false });
            dt.Columns.Add(new DataColumn("region_id", typeof(int)) { AllowDBNull = false });
            dt.Columns.Add(new DataColumn("option_product_id", typeof(int)) { AllowDBNull = false });
            foreach (var productRegionOption in productRegionOptions)
            {
                DataRow dr = dt.NewRow();
                dr["product_id"] = productRegionOption.ProductId;
                dr["region_id"] = productRegionOption.RegionId;
                dr["option_product_id"] = productRegionOption.OptionProductId;
                dt.Rows.Add(dr);
            }

            var productCompatibleAlternateKeys = new SqlParameter("@product_compatibles_alternate_keys", dt) { TypeName = "dbo.product_compatibles_alternate_keys_dt", SqlDbType = SqlDbType.Structured };
            var productCompatibleQueries = _context.ProductCompatibles.FromSqlRaw(@"SELECT k.product_id, k.region_id, k.option_product_id FROM @product_compatibles_alternate_keys k", productCompatibleAlternateKeys)
                .Select(x => new { x.ProductId, x.RegionId, x.OptionProductId });

            var productCompatibles = await _context.ProductCompatibles.Where(c => c.DeletedFlag == false && productCompatibleQueries.Any(s => s.ProductId == c.ProductId && s.RegionId == c.RegionId && s.OptionProductId == c.OptionProductId))
                .Select(p => p)
                .ToListAsync();

            return productCompatibles;
        }

        public ProductCompatible Add(ProductCompatible productCompatible)
        {
            return _context.ProductCompatibles.Add(productCompatible).Entity;
        }

        public void Update(ProductCompatible productCompatible)
        {
            //The entity is being tracked and is in a connected state therefore when save entities is called it will know which properties have been changed.
        }
    }
```

Calling the repo with a productRegionOption creates the following SQL 

``` sql
DECLARE @product_compatibles_alternate_keys dbo.product_compatibles_alternate_keys_dt
INSERT INTO @product_compatibles_alternate_keys (product_id, option_product_id, region_id)
VALUES (12835, 12847, 98)

SELECT [p].[id], [p].[created], [p].[created_by], [p].[deleted_flag], [p].[last_modified_by], [p].[last_persisted], [p].[option_product_id], [p].[product_id], [p].[region_id]
FROM [product_compatibles] AS [p]
WHERE ([p].[deleted_flag] <> CAST(1 AS bit)) AND EXISTS (
    SELECT 1
    FROM (
        SELECT k.product_id, k.region_id, k.option_product_id FROM @product_compatibles_alternate_keys k
    ) AS [p0]
    WHERE (([p0].[product_id] = [p].[product_id]) AND ([p0].[region_id] = [p].[region_id])) AND ([p0].[option_product_id] = [p].[option_product_id]))
```
If the SQL code produced used [p].[deleted_flag] = CAST(0 AS bit) instead of [p].[deleted_flag] <> CAST(1 AS bit)" then my filtered index would be picked up and used, which would result in my query taking milliseconds rather than 7 seconds.     

Provider and version information

EF Core version: 5.0.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: e.g. .NET Core 3.1

**Comment by joakimriedel** [comment] 2021-05-20 17:52
similar to https://github.com/dotnet/efcore/issues/23472 ?

**Comment by longjxchina** [comment] 2021-05-31 01:07
I solved the problem by following the steps below:

1. change deleted_flag dbtype to tinyint.
2. cahnge code builder.Property(p.DeletedFlag).HasColumnType("tinyint").
3. Where(c => c.DeletedFlag == false).

**Comment by maumar** [comment] 2021-08-01 03:06
dupe of https://github.com/dotnet/efcore/issues/23472 which has already been fixed

**Closed** 2022-10-16 19:35 UTC
Labels: customer-reported
