### ISSUE TITLE
Query: nav rewrite doesn't get applied for cases when navigation is not based on qsre but more complex expression (e.g. qsre as DerivedType)

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12361] opened 2018-06-14 19:51 UTC
Repro using gears of war model:

```
ctx.Factions.Where(f => f is LocustHorde ? (f as LocustHorde).Commander == null : false)
```

**Comment by maumar** [comment] 2019-09-11 22:26
still fails on current bits

**Comment by smitpatel** [comment] 2019-09-11 22:36
Duplicate of #17475

**Closed** 2022-10-16 12:31 UTC
Labels: closed-duplicate
