### ISSUE TITLE
.Net Framework and DbContext injection

### ISSUE THREAD

**Issue by lanneshoa** [dotnet/efcore#10026] opened 2017-10-10 08:03 UTC
I'm using a web api 2 (.Net Framework 4.6.1) solution and try to migrate from EF core 1.1 to EF Core 2.0.
Using Ninject, I inject my DbContext. There is a new DbContext each time the server is called.

With Ef Core 1.1, there is no problem, EF validates the db using onModelCreating only once.

With Ef Core 2.0, EF validates each time the db using onModelCreating. I'm trying to avoid that, but I'm not able to find answer.

### Further technical details
EF Core version: 2.0
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Seven
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment] 2017-10-10 16:38
@lanneshoa The expected behavior is going to depend on how types are registered in D.I. Can you post the code where you setup your container and register the DbContext?

**Comment by lanneshoa** [comment] 2017-10-11 07:29
Using NInject

``
public static class NinjectWebCommon
    {
        private static readonly Bootstrapper bootstrapper = new Bootstrapper();

        /// <summary>
        /// Starts the application
        /// </summary>
        public static void Start()
        {
            DynamicModuleUtility.RegisterModule(typeof(OnePerRequestHttpModule));
            DynamicModuleUtility.RegisterModule(typeof(NinjectHttpModule));
            bootstrapper.Initialize(CreateKernel);
        }

        /// <summary>
        /// Stops the application.
        /// </summary>
        public static void Stop()
        {
            bootstrapper.ShutDown();
        }

        /// <summary>
        /// Creates the kernel that will manage your application.
        /// </summary>
        /// <returns>The created kernel.</returns>
        private static IKernel CreateKernel()
        {
            var kernel = new StandardKernel();
            kernel.Bind<Func<IKernel>>().ToMethod(ctx => () => new Bootstrapper().Kernel);
            kernel.Bind<IHttpModule>().To<HttpApplicationInitializationHttpModule>();
            RegisterServices(kernel);
            GlobalConfiguration.Configuration.DependencyResolver = new NinjectDependencyResolver(kernel);
            return kernel;
        }

        /// <summary>
        /// Load your modules or register your services here!
        /// </summary>
        /// <param name="kernel">The kernel.</param>
        private static void RegisterServices(IKernel kernel)
        {
            kernel.Bind<ServiceFactory<CustomCommonContext>>().To<ManagerFactory>();
        }
    }
``

Manager
``
public class ManagerFactory : ServiceFactory<CustomCommonContext>
    {
        public ManagerFactory()
        {
            this.Context = new CustomCommonContext();
        }
    }
``

ServiceFactory
``
    public abstract class ServiceFactory<DBContext> : IServiceFactory<DBContext>
        where DBContext : CustomCommonContext
    {
             public DBContext Context { get; protected set; }

             public CoachingNoteManager<ServiceFactory<DBContext>, DBContext> MyManager
        {
            get
            {
                return new MyManager<ServiceFactory<DBContext>, DBContext>(this);
            }
        }
    }
``

MyManager
``
    public class MyManager<Service, Context> : BaseManager<Service, Context>
        where Service : ServiceFactory<Context>
        where Context : CustomCommonContext
    {
        public MyManager(Service serviceFactory)
            : base(serviceFactory)
        {
        }
}
``

**Comment by ajcvickers** [comment] 2017-10-11 19:52
@lanneshoa There doesn't seem to be anything specific to EF in the code you posted. Would it be possible to post a full project or code listing that reproduces what you are seeing?

**Comment by ajcvickers** [comment] 2017-10-18 18:04
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:53 UTC
Labels: closed-could-not-reproduce
