### ISSUE TITLE
KeyNotFoundException on nullable nested object in JSON column if that object does not exist.

### ISSUE THREAD

**Issue by thomasjbarrett82** [dotnet/efcore#30062] opened 2023-01-13 21:19 UTC
Possible duplicate of [#30028](https://github.com/dotnet/efcore/issues/30028).

EF Core 7.0 will throw a KeyNotFoundException if a JSON column does not have a nullable sub-object in the record. Code sample can be found at [EFCore7JsonDemo](https://github.com/thomasjbarrett82/EFCore7JsonDemo). This error will not happen if the classes are mapped to SQL tables instead of JSON.

## Screenshots

![get all error](https://user-images.githubusercontent.com/56722550/212419604-ce1c1e9d-6f53-4a97-8530-4d0b8c147682.png)

![get one error](https://user-images.githubusercontent.com/56722550/212419605-fb00ac39-ba71-4cba-88ed-839f718cf504.png)

## Repro steps: 

1. Add a new PersonJson without an Education property - {"Id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","Name":"string"}
2. Run a debug session with the Education property on the PersonJson object and try a Get or GetAll via Swagger

EF Core version: 7.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer (SQL Server 2019)
Target framework: NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.4

**Comment by maumar** [comment] 2023-01-18 05:20
this indeed is a duplicate of https://github.com/dotnet/efcore/issues/30028 - closing

**Closed by maumar** 2023-01-18 05:20 UTC
Labels: closed-duplicate, customer-reported

**Comment by roji** [comment] 2023-01-18 09:58
Duplicate of #30028
