### ISSUE TITLE
EF Core 7 Problem when Add with entity with Identity and child entities with FK

### ISSUE THREAD

**Issue by celsobrandao** [dotnet/efcore#29586] opened 2022-11-16 13:35 UTC
Hi,

I have the following code:

```C#
//Domain:
public class Order
{
    //This is an Identity column
    public int OrderID { get; set; }
    public string Name { get; set; }
    
   //Other fields

   public virtual ICollection<Product> Products { get; set; }
}

public class Product
{
    public int OrderID { get; set; }
    public short ProductID { get; set; }
    public string Name { get; set; }
    
    //Other fields

    public virtual Order Order { get; set; }
}
```

```C#
//Mapping:
public class OrderMapping : EntityMappingConfiguration<Order>
{
    public override void Map(EntityTypeBuilder<Order> b)
    {
        b.ToTable("Orders", "dbo")
            .HasKey(x => x.OrderID);

        //This is an Identity column
        b.Property(x => x.OrderID).HasColumnName("Order")
            .ValueGeneratedOnAdd()
            .IsRequired();

        b.Property(x => x.Name).HasColumnName("Name")
            .IsRequired();

        //Other fields

        b.HasMany(x => x.Products)
            .WithOne(c => c.Order)
            .HasForeignKey(x => x.OrderID);
    }
}

public class ProductMapping : EntityMappingConfiguration<Product>
{
    public override void Map(EntityTypeBuilder<Product> b)
    {
        b.ToTable("Orders_Products", "dbo")
            .HasKey(x => new
            {
                x.OrderID,
                x.ProductID
            });

        b.Property(x => x.OrderID).HasColumnName("Order")
            .ValueGeneratedOnAdd()
            .IsRequired();

        b.Property(x => x.ProductID).HasColumnName("Product")
            .IsRequired();

        b.Property(x => x.Name).HasColumnName("Name")
            .IsRequired();

        //Other fields
    }
}
```

```C#
//Service:
Order o = new(){
	Name = "MyOrder",
	Products = new List<Product>() {		
		new(){
			ProductID = 1,
			Name = "MyProduct 1"
		}
	}
};

dbSet = context.Set<Order>();
dbSet.Add(o);
context.SaveChanges();
```

This is the executed SQL command:
```SQL

--Executing DbCommand [Parameters=[@p0='MyOrder', @p1='1', @p2='MyProduct 1' (Nullable = false) (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
DECLARE @inserted0 TABLE ([Order] int);
INSERT INTO [dbo].[Orders] ([Name])
OUTPUT INSERTED.[Order]
INTO @inserted0
VALUES (@p0);
SELECT [i].[Order] FROM @inserted0 i;

DECLARE @inserted1 TABLE ([Order] int, [Product] smallint);
INSERT INTO [dbo].[Orders_Products] ([Product], [Name])
OUTPUT INSERTED.[Order], INSERTED.[Product]
INTO @inserted1
VALUES (@p1, @p2);
SELECT [t].[Order] FROM [dbo].[Orders_Products] t
INNER JOIN @inserted1 i ON ([t].[Order] = [i].[Order]) AND ([t].[Product] = [i].[Product]);

--Cannot insert the value NULL into column 'Order', table 'Orders_Products'; column does not allow nulls. INSERT fails.
```

On EF Core 6.*, EF would insert Order on dbo.Orders and get the identity generated OrderID and use it on the dbo.Products insert. Now it doesn't. It keeps the default value of OrderID on the Products object and throws a foreign key exception on the insert command of Products.

Is this really the new behavior? If so, is there a way to make it work like it did before? Or is this a bug and is going to be fixed?

**Comment by erickcruzf** [comment] 2022-11-17 13:35
An identity pk is not replicating it's value when the graph of entities are inserted. Even though the order child entity have the valueGeneratedOnAdd configured as of the ProductMapping below:
`b.Property(x => x.OrderID).HasColumnName("Order")
            .ValueGeneratedOnAdd()
            .IsRequired();`
Then when calling SaveChanges();
The resulting query is trying to insert null on the Product's table, causing an error, as of EF 6, would get the generated value instead.

**Comment by celsobrandao** [comment] 2022-11-17 14:20
I edited my initial post with more info.

**Comment by ajcvickers** [comment] 2022-11-17 14:38
@celsobrandao I am not able to reproduce this--see my code below. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
public static class Your
{
    public static string ConnectionString = @"Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow";
}

public class Order
{
    public int OrderID { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Product> Products { get; set; }
}

public class Product
{
    public int OrderID { get; set; }
    public short ProductID { get; set; }
    public string Name { get; set; }
    public virtual Order Order { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Order>(b =>
        {
            b.ToTable("Orders", "dbo").HasKey(x => x.OrderID);
            b.Property(x => x.OrderID).HasColumnName("Order").ValueGeneratedOnAdd().IsRequired();
            b.Property(x => x.Name).HasColumnName("Name").IsRequired();
            b.HasMany(x => x.Products).WithOne(c => c.Order).HasForeignKey(x => x.OrderID);
        });

        modelBuilder.Entity<Product>(b =>
        {
            b.ToTable("Orders_Products", "dbo")
                .HasKey(x => new
                {
                    x.OrderID,
                    x.ProductID
                });

            b.Property(x => x.OrderID).HasColumnName("Order").ValueGeneratedOnAdd().IsRequired();
            b.Property(x => x.ProductID).HasColumnName("Product").IsRequired();
            b.Property(x => x.Name).HasColumnName("Name").IsRequired();
        });
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            Order o = new(){
                Name = "MyOrder",
                Products = new List<Product>() {
                    new(){
                        ProductID = 1,
                        Name = "MyProduct 1"
                    }
                }
            };

            var dbSet = context.Set<Order>();
            dbSet.Add(o);
            context.SaveChanges();
        }
    }
}
```

```
info: 11/17/2022 14:35:11.577 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (38ms) [Parameters=[@p0='MyOrder' (Nullable = false) (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SET IMPLICIT_TRANSACTIONS OFF;
      SET NOCOUNT ON;
      INSERT INTO [dbo].[Orders] ([Name])
      OUTPUT INSERTED.[Order]
      VALUES (@p0);
info: 11/17/2022 14:35:11.602 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (3ms) [Parameters=[@p1='1', @p2='1', @p3='MyProduct 1' (Nullable = false) (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SET IMPLICIT_TRANSACTIONS OFF;
      SET NOCOUNT ON;
      INSERT INTO [dbo].[Orders_Products] ([Order], [Product], [Name])
      VALUES (@p1, @p2, @p3);
```

**Comment by ajcvickers** [comment] 2022-11-28 13:21
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-11-28 13:21 UTC
Labels: customer-reported
