### ISSUE TITLE
Set and Join not working while working on EntityFramework 6

### ISSUE THREAD

**Issue by EbrahimMajdey** [dotnet/efcore#24154] opened 2021-02-15 02:39 UTC
Well I had a groupby query that doesnt work in entityframework core, I found that there is a limitation on core regarding the groupby queries so I changed it to 2 subqueries - one for keys and one for corresponding data. I tested it in regular entityframewok 6 and it is working fine .. but in core it doesnt 

 
```C#
var TermIds= new int []{1,3,4 };
 using (var context = CreateContext(commandTimeout))
 {
     context.Configuration.LazyLoadingEnabled = false;
     var result = context.Set<MonitorMatchMonitorTerm>().q.Select(s => s.MonitorTermID)
               .Where(_ => TermIds.Contains(_))
               .Distinct()
               .SelectMany(
                   key =>
                   context.Set<MonitorMatchMonitorTerm>()
                   .Join(context.Set <MonitorMatch>(),
                   _=>_.MonitorMatchID,
                   _ => _.ItemId,
                   (first,second) => new
                   {
                       MonitorTermID = first.MonitorTermID,
                       MonitorMatchID = first.MonitorMatchID,
                       Detected = second.Detected,
                       DumpID = second.DumpID,
                       ItemId = second.ItemId,
                       MatchContext = second.MatchContext

                   })
                   .Where(t => t.MonitorTermID == key)
                   .OrderByDescending(_ => _.MonitorMatchID)
                   .Take(5)
                   .Skip(0)
                   
                   .Select(_ => new BreachMatch
                   {
                       TermId = _.MonitorTermID,
                       Date = _.Detected,
                       DetailId = _.DumpID,
                       Id = _.ItemId,
                       MatchContext = _.MatchContext
                   })).ToList();

 }
```
noting that this is simply can be exchanged with GroupBy but I made it this way for entityframework core to work

The SQL generated from entityframework vs entityframework core

```sql
SELECT
    [Skip1].[MonitorTermID] AS [MonitorTermID],
    [Skip1].[Detected] AS [Detected],
    [Skip1].[DumpID] AS [DumpID],
    [Skip1].[ItemId] AS [ItemId],
    [Skip1].[MatchContext] AS [MatchContext]
    FROM   (SELECT DISTINCT
        [Extent1].[MonitorTermID] AS [MonitorTermID]
        FROM [dbo].[MonitorMatchesMonitorTerms] AS [Extent1]
        WHERE [Extent1].[MonitorTermID] IN (1, 3,4) ) AS [Distinct1]
    CROSS APPLY  (SELECT [Project3].[MonitorTermID] AS [MonitorTermID], [Project3].[ItemId] AS [ItemId], [Project3].[DumpID] AS [DumpID], [Project3].[Detected] AS [Detected], [Project3].[MatchContext] AS [MatchContext]
        FROM ( SELECT TOP (5)
            [Project2].[MonitorMatchID] AS [MonitorMatchID],
            [Project2].[MonitorTermID] AS [MonitorTermID],
            [Project2].[ItemId] AS [ItemId],
            [Project2].[DumpID] AS [DumpID],
            [Project2].[Detected] AS [Detected],
            [Project2].[MatchContext] AS [MatchContext]
            FROM ( SELECT
                [Extent2].[MonitorMatchID] AS [MonitorMatchID],
                [Extent2].[MonitorTermID] AS [MonitorTermID],
                [Extent3].[ItemId] AS [ItemId],
                [Extent3].[DumpID] AS [DumpID],
                [Extent3].[Detected] AS [Detected],
                [Extent3].[MatchContext] AS [MatchContext]
                FROM  [dbo].[MonitorMatchesMonitorTerms] AS [Extent2]
                INNER JOIN [dbo].[MonitorMatches] AS [Extent3] ON [Extent2].[MonitorMatchID] = [Extent3].[ItemId]
                WHERE [Extent2].[MonitorTermID] = [Distinct1].[MonitorTermID]
            )  AS [Project2]
            ORDER BY [Project2].[MonitorMatchID] DESC
        )  AS [Project3]
        ORDER BY row_number() OVER (ORDER BY [Project3].[MonitorMatchID] DESC)
        OFFSET 0 ROWS  ) AS [Skip1]
```

In Core this is
```sql
SELECT [t1].[MonitorTermID] AS [TermId], [t1].[Detected] AS [Date], [t1].[DumpID] AS [DetailId], [t1].[ItemId] AS [Id], [t1].[MatchContext]
      FROM (
          SELECT DISTINCT [m].[MonitorTermID]
          FROM [MonitorMatchesMonitorTerms] AS [m]
          WHERE [m].[MonitorTermID] IN (1,3,4)
      ) AS [t]
      CROSS APPLY (
          SELECT [t].[MonitorTermID], [t].[Detected], [t].[DumpID], [t].[ItemId], [t].[MatchContext], [t].[MonitorMatchID]
          FROM (
              SELECT TOP(5) [m0].[MonitorTermID], [m0].[MonitorMatchID], [m1].[Detected], [m1].[DumpID], [m1].[ItemId], [m1].[MatchContext]
              FROM [MonitorMatchesMonitorTerms] AS [m0]
              INNER JOIN [MonitorMatches] AS [m1] ON [m0].[MonitorMatchID] = [m1].[ItemId]
              WHERE [m0].[MonitorTermID] = [t].[MonitorTermID]
              ORDER BY [m0].[MonitorMatchID] DESC
          ) AS [t0]
          ORDER BY [t].[MonitorMatchID] DESC
          OFFSET 0 ROWS
      ) AS [t1]
```
It is noticeable that there is a naming issue in tables 
The right query should be

```sql
SELECT [t1].[MonitorTermID] AS [TermId], [t1].[Detected] AS [Date], [t1].[DumpID] AS [DetailId], [t1].[ItemId] AS [Id], [t1].[MatchContext]
      FROM (
          SELECT DISTINCT [m].[MonitorTermID]
          FROM [MonitorMatchesMonitorTerms] AS [m]
          WHERE [m].[MonitorTermID] IN (1857, 1870, 1896, 1921, 1922, 1923, 1924, 1925, 1927, 1994, 1995, 1996, 2049, 2132, 2133, 2138, 2139, 2140, 2197, 2203, 2204, 2205, 2219)
      ) AS [t]
      CROSS APPLY (
          SELECT [t0].[MonitorTermID], [t0].[Detected], [t0].[DumpID], [t0].[ItemId], [t0].[MatchContext], [t0].[MonitorMatchID]
          FROM (
              SELECT TOP(5) [m0].[MonitorTermID], [m0].[MonitorMatchID], [m1].[Detected], [m1].[DumpID], [m1].[ItemId], [m1].[MatchContext]
              FROM [MonitorMatchesMonitorTerms] AS [m0]
              INNER JOIN [MonitorMatches] AS [m1] ON [m0].[MonitorMatchID] = [m1].[ItemId]
              WHERE [m0].[MonitorTermID] = [t].[MonitorTermID]
              ORDER BY [m0].[MonitorMatchID] DESC
          ) AS [t0]
          ORDER BY [t0].[MonitorMatchID] DESC
          OFFSET 0 ROWS
      ) AS [t1]
```

I am not sure the reason for that is what but looks like Set to same table made the generated code refere to t instead of t0 .. might be a key pair value issue I am not sure .. Would highly appreciate any help how to fix that 

EF Core version: 3.1.8
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .netcoreframework 3.1)
Operating system: Windows
IDE:  Visual Studio 2019

**Comment by ajcvickers** [comment] 2021-02-16 22:53
This issue is lacking enough information for us to be able to find the root cause. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2021-02-26 21:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:23 UTC
Labels: closed-could-not-reproduce, customer-reported
