### ISSUE TITLE
Consider Supporting Database Constraints with InMemory Database Provider.

### ISSUE THREAD

**Issue by efaruk** [dotnet/efcore#11228] opened 2018-03-10 16:03 UTC
Following copied from offical github page: https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/testing/in-memory.md

>Some examples of this include:
>* InMemory will allow you to save data that would violate referential integrity constraints in a relational database.
>
>* If you use DefaultValueSql(string) for a property in your model, this is a relational database API and will have no effect when running against InMemory.

If InMemory won't support database constraints I can't see much value using it any way. Please consider supporting RDBMS related features. I don't see anything hard to implement those, at least couple of them like unique constraints...

If you don't consider supporting such features, then still best choice is to use Sqlite for unit testing and please don't bother yourself to implement other features, because you are not adding any value on whats already exists...

**Comment by ajcvickers** [comment] 2018-03-10 17:34
Duplicate of #2166  and #11032

**Closed** 2022-10-16 12:13 UTC
Labels: closed-duplicate
