### ISSUE TITLE
EF migrations add throws InvalidOperationException: The property 'X' cannot be added to the type 'X' because there was no property type specified...

### ISSUE THREAD

**Issue by BillyBug** [dotnet/efcore#9133] opened 2017-07-10 18:02 UTC
When using EF Core Tools 1.1.1 to add a V3 migration to a data access library, it fails with the error shown below. There are no changes to the BranchLock or Branch entities and V3 simply adds a new entity that has no relationship to these.

```
Exception message:
The property 'My.Namespace.MyProject.BranchLock' cannot be added to the type 'My.Namespace.MyProject.BranchLock' because there was no property type specified and there is no corresponding CLR property or field. To add a shadow state property the property type must be specified.

Stack trace:
System.InvalidOperationException: The property 'My.Namespace.MyProject.BranchLock' cannot be added to the type 'My.Namespace.MyProject.BranchLock' because there was no property type specified and there is no corresponding CLR property or field. To add a shadow state property the property type must be specified.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.GetOrCreateProperties(IEnumerable`1 propertyNames, ConfigurationSource configurationSource, IEnumerable`1 referencedProperties)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.HasForeignKey(IReadOnlyList`1 propertyNames, EntityType dependentEntityType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceCollectionBuilder.HasForeignKey(String[] foreignKeyPropertyNames)
   at MyDataAccess.Migrations.MyDbContextModelSnapshot.<>c.<BuildModel>b__0_31(EntityTypeBuilder b) in d:\MyRepo\src\models\MyDataAccess\Migration\MyDbContextModelSnapshot.cs:line 785
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(String name, Action`1 buildAction)
   at MyDataAccess.Migrations.MyDbContextModelSnapshot.BuildModel(ModelBuilder modelBuilder) in d:\MyRepo\src\models\MyDataAccess\Migration\MyDbContextModelSnapshot.cs:line 783
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot.<.ctor>b__1_0()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The property 'My.Namespace.MyProject.BranchLock' cannot be added to the type 'My.Namespace.MyProject.BranchLock' because there was no property type specified and there is no corresponding CLR property or field. To add a shadow state property the property type must be specified.
```

### Steps to reproduce
Using EF Core Tools 1.1.1:
ef.exe migrations add MyV3 -c MyDbContext -s "D:\MyRepo\Output\debug-amd64\MyService\MyService.exe" -a "D:\MyRepo\Output\debug-amd64\MyService\MyDataAccess.dll" -v -o D:\MyRepo\src\Models\MyDataAccess\Migration

From existing MyDbContextModelSnapshot.cs file generated when adding "V2" migration (Line 783 and 785 is in the call stack):
```c#
17: protected override void BuildModel(ModelBuilder modelBuilder)
18: {
19:   modelBuilder
20:   .HasAnnotation("ProductVersion", "1.1.2")
21:   .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
…
783:   modelBuilder.Entity("My.Namespace.MyProject.BranchLock", b =>
784:   {
785:     b.HasOne("My.Namespace.MyProject.Branch", "Branch")
786:      .WithMany()
787:      .HasForeignKey("My.Namespace.MyProject.BranchLock", "BranchId");
788:   });
…
```
(I am not be able to post the complete source code of the project.)

### Further technical details
EF Core version: 1.1 (EF Core Tools: 1.1.1 - EF Core Libs: 1.1.2)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by bricelam** [comment] 2017-07-10 22:42
Could you share the full snapshot file? Were conflicts ever merged with a version control system? Could you share the `Branch` and `BranchLock` classes (including base types, annotations, etc.)?

**Comment by BillyBug** [comment] 2017-07-11 04:11
@bricelam - I can share the location of this code privately if needed (let me know). The code does live in a GIT repo, but I don't see any sign of bad merge conflict resolutions in the history.

Today I tried deleting the snapshot file, rebuilding, and then adding the migration as if it was the first one. That worked and I compared the new snapshot with the previous file and found that the above line 787 generated was changed from:
`HasForeignKey("My.Namespace.MyProject.BranchLock", "BranchId")`
...to:
`HasForeignKey("BranchId")`

I then reverted the changes and manually edited the V2 generated snapshot file to make this one change. After rebuilding the project I was able to add the V3 migration without the error.

It almost looks like the use of ReferenceCollectionBuilder.HasForeignKey and ReferenceReferenceBuilder.HasForeignKey got mixed up. I see many references to both methods in the snapshot file, but for all other entities it is only passing two parameters when calling the ReferenceReferenceBuilder's HasForeignKey method. How it ended up in this state I don't understand.

**Comment by bricelam** [comment] 2017-08-31 21:48
I am unable to root cause this. My best guess is that at one point it changed between a 1:1 and a 1:* relationship and there was a merge conflict. Given the names of the types, it's not inconceivable that it was scaffolded like this one point: (which is valid)
``` csharp
b.HasOne("My.Namespace.MyProject.Branch", "Branch")
    .WithOne()
    .HasForeignKey("My.Namespace.MyProject.BranchLock", "BranchId");
```

**Comment by ajcvickers** [comment] 2017-09-06 18:16
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by sjb-sjb** [comment] 2018-03-06 03:09
You may want to re-open this. I had this error crop up today and was able to get it to appear / disappear at will. Of course it is buried in the middle of thousands of lines of code, but here's what I can tell you. 

I have entity base classes called NamedEntity and DatedEntity, and several derived classes from each. However only the derived classes are in the model, the base classes are not given separate DbSets. The error arises when I change this code:  

        protected override void OnModelCreating(ModelBuilder mb)
        {
            base.OnModelCreating(mb);
            mb.PreventCascadeDelete();
            mb.UseChangeTrackingEntities();
            mb.Model.GetEntityTypes().ToList().ForEach(mutableEntityType => this.OnModelCreating(mb, mutableEntityType.Name));
        }

        private void OnModelCreating(ModelBuilder mb, string entityTypeName)
        {
            Type entityType = Type.GetType(entityTypeName, true);
            // Create unique key for named entities. Note unique keys can be null, alternate keys cannot. 
            if (typeof(NamedEntity).IsAssignableFrom(entityType)) {
                mb.Entity(entityTypeName).HasIndex(nameof(NamedEntity.Name)).IsUnique(); // NOT: .HasAlternateKey( --);
            }
            // Create additional index for dated entities
            if (typeof(DatedEntity).IsAssignableFrom(entityType)) {
                mb.Entity(entityTypeName).HasIndex(nameof(DatedEntity.Date));
            }
            // Call "private static void OnModelCreating( ModelBuilder mb)" method in the entity type, if defined. 
            MethodInfo onModelCreatingMethod = entityType.GetMethod(nameof(this.OnModelCreating), BindingFlags.Static | BindingFlags.NonPublic, null, new Type[] { typeof(ModelBuilder) }, null);
            if (onModelCreatingMethod != null) {
                onModelCreatingMethod.Invoke(null, new object[] { mb });
            }
        }

... to this code: 

        protected override void OnModelCreating(ModelBuilder mb)
        {
            base.OnModelCreating(mb);
            mb.PreventCascadeDelete();
            mb.UseChangeTrackingEntities();
            mb.Model.GetEntityTypes().ToList().ForEach(mutableEntityType => this.OnModelCreating(mb, mutableEntityType));
        }

        private void OnModelCreating( ModelBuilder mb, IMutableEntityType mutableEntityType)
        {
            Type entityType = mutableEntityType.ClrType;
            // Create unique key for named entities. Note unique keys can be null, alternate keys cannot. 
            if (typeof(NamedEntity).IsAssignableFrom(entityType)) {
                mb.Entity(entityType.Name).HasIndex( nameof(NamedEntity.Name)).IsUnique(); // NOT: .HasAlternateKey( --);
            }
            // Create additional index for dated entities
            if (typeof(DatedEntity).IsAssignableFrom(entityType)) {
                mb.Entity(entityType.Name).HasIndex(nameof(DatedEntity.Date)); // *** EXCEPTION
            }
            // Call "private static void OnModelCreating( ModelBuilder mb)" method in the entity type, if defined. 
            MethodInfo onModelCreatingMethod = entityType.GetMethod(nameof(this.OnModelCreating), BindingFlags.Static | BindingFlags.NonPublic, null, new Type[] { typeof(ModelBuilder) }, null);
            if (onModelCreatingMethod != null) {
                onModelCreatingMethod.Invoke(null, new object[] { mb });
            }
        }

The exception occurs at the line marked. On the face of it, the change would not seem significant. We are just accessing the type name from mutableEntityType.ClrType.Name instead of loading the type using mutableEntityType.Name and then taking the type's name. 

However, when I break at the line marked *** and watch mb.Entity(entityTypeName), I get two different results. In the first case, mb.Entity(entityTypeName).Metadata.ClrType is correctly defined to be my class, which is called Price. But in the second case, mb.Entity(entityTypeName).Metadata.ClrType is null. 

I don't know why the problem doesn't occur for the other base class, NamedEntity. There are a couple of differences in the way the two base classes are used, though. One difference is that NamedEntity has two derived classes while DatedEntity only has one. Another difference is that the class derived from DatedEntity has a reference to one of the classes derived from NamedEntity, but there is no class in the context that has a reference to the class derived from DatedEntity. On the other hand there is no entity that has a reference to the other class derived from NamedEntity.

Maybe mb.Entity(entityType.Name) is not loading the CLR type, causing the exception when HasIndex cannot find the property in the CLR type, while in the cases where the exception did not occur the CLR type had already been loaded for other reasons? 

The PreventCascadeDelete and UseChangeTrackingEntities methods look like this: 

        static public void PreventCascadeDelete(this ModelBuilder modelBuilder)
        {
            var mutableForeignKeys = modelBuilder.Model.GetEntityTypes().SelectMany(mutableEntityType => mutableEntityType.GetForeignKeys());
            foreach (var foreignKey in mutableForeignKeys) {
                // NOT: if (foreignKey.IsRequired) ... 
                // Cascading/restricting is a separate question from whether the relationship is optional. 
                foreignKey.DeleteBehavior = DeleteBehavior.Restrict;
            }
        }

        static public void UseChangeTrackingEntities(this ModelBuilder modelBuilder)
        {
            ChangeTrackingStrategy strategy = ChangeTrackingStrategy.ChangingAndChangedNotificationsWithOriginalValues;
            modelBuilder.HasChangeTrackingStrategy(strategy);
        }

Hope this is useful for you. 

sjb

**Comment by ajcvickers** [comment] 2018-03-06 17:32
@sjb-sjb Looks like this is because in the working case you correctly use the full entity type name, which includes the namespace for entities that have CLR types, while in the case where it breaks you use the simple name (i.e. without the namespace) which is incorrect.

**Comment by sjb-sjb** [comment] 2018-03-07 00:16
Ha, I thought I tested that possibility!
Thanks for the tip.

**Closed** 2022-10-16 11:11 UTC
Labels: closed-could-not-reproduce
