### ISSUE TITLE
EF Core database first SQL server temporal table scaffold

### ISSUE THREAD

**Issue by albertcristian** [dotnet/efcore#31444] opened 2023-08-11 11:44 UTC
Hi,

I'm using EF Core in my C# application using a database first approach.
The temporal tables are being scaffolded as if they're regular tables. This is happening when targeting the UAT/DEMO/PROD environments.

**When running the scaffold against a SQL database that's running in a docker  container I'm noticing the table being correctly scaffolded**

SQL Server temporal table
```SQL
CREATE TABLE Department
(
    DeptID INT NOT NULL PRIMARY KEY CLUSTERED,
    DeptName VARCHAR(50) NOT NULL,
    ManagerID INT NULL,
    ParentDeptID INT NULL,
    ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    ValidTo DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.DepartmentHistory));
```
Scaffold command
```C#
dotnet ef dbcontext scaffold 'connect' Microsoft.EntityFrameworkCore.SqlServer `
    --namespace EFScaffoldProject.DatabaseModels `
    --force `
    --no-build `
    --no-pluralize `
    --no-onconfiguring `
    --output-dir DatabaseModels `
    --verbose `
    --table department 
```

# Generated output/result
***
Context
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Department>(entity =>
    {
        entity.HasKey(e => e.DeptId).HasName("PK__Departme__0148818E124C33C0");

        entity.Property(e => e.DeptId)
            .ValueGeneratedNever()
            .HasColumnName("DeptID");
        entity.Property(e => e.DeptName)
            .HasMaxLength(50)
            .IsUnicode(false);
        entity.Property(e => e.ManagerId).HasColumnName("ManagerID");
        entity.Property(e => e.ParentDeptId).HasColumnName("ParentDeptID");
    });

    OnModelCreatingPartial(modelBuilder);
}
}
```
Model
```C#
public partial class Department
{
    public int DeptId { get; set; }

    public string DeptName { get; set; } = null!;

    public int? ManagerId { get; set; }

    public int? ParentDeptId { get; set; }

    public DateTime ValidFrom { get; set; }

    public DateTime ValidTo { get; set; }
}
```
Scaffold log
```
Using project 'C:\dev\EFScaffoldProject\EFScaffoldProject.csproj'.
Using startup project 'C:\dev\EFScaffoldProject\EFScaffoldProject.csproj'.
Writing 'C:\dev\EFScaffoldProject\obj\EFScaffoldProject.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\A\AppData\Local\Temp\tmpC560.tmp /verbosity:quiet /nologo C:\dev\EFScaffoldProject\EFScaffoldProject.csproj
Writing 'C:\dev\EFScaffoldProject\obj\EFScaffoldProject.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\A\AppData\Local\Temp\tmpCA82.tmp /verbosity:quiet /nologo C:\dev\EFScaffoldProject\EFScaffoldProject.csproj
dotnet exec --depsfile C:\dev\EFScaffoldProject\bin\Debug\net7.0\EFScaffoldProject.deps.json --additionalprobingpath C:\Users\A\.nuget\packages --runtimeconfig C:\dev\EFScaffoldProject\bin\Debug\net7.0\EFScaffoldProject.runtimeconfig.json C:\Users\A\.dotnet\tools\.store\dotnet-ef\7.0.10\dotnet-ef\7.0.10\tools\net6.0\any\tools\netcoreapp2.0\any\ef.dll dbcontext scaffold "connect" Microsoft.EntityFrameworkCore.SqlServer --namespace EFScaffoldProject.DatabaseModels --force --no-pluralize --no-onconfiguring --output-dir DatabaseModels --table Department --assembly C:\dev\EFScaffoldProject\bin\Debug\net7.0\EFScaffoldProject.dll --project C:\dev\EFScaffoldProject\EFScaffoldProject.csproj --startup-assembly C:\dev\EFScaffoldProject\bin\Debug\net7.0\EFScaffoldProject.dll --startup-project C:\dev\EFScaffoldProject\EFScaffoldProject.csproj --project-dir C:\dev\EFScaffoldProject\ --root-namespace EFScaffoldProject --language C# --framework net7.0 --nullable --working-dir C:\dev\EFScaffoldProject --verbose
Using assembly 'EFScaffoldProject'.
Using startup assembly 'EFScaffoldProject'.
Using application base 'C:\dev\EFScaffoldProject\bin\Debug\net7.0'.
Using working directory 'C:\dev\EFScaffoldProject'.
Using root namespace 'EFScaffoldProject'.
Using project directory 'C:\dev\EFScaffoldProject\'.
Remaining arguments: .
Finding design-time services referenced by assembly 'EFScaffoldProject'...
Finding design-time services referenced by assembly 'EFScaffoldProject'...
No referenced design-time services were found.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding IDesignTimeServices implementations in assembly 'EFScaffoldProject'...
No design-time services were found.
Found default schema 'dbo'.
Found type alias with name 'sys.sysname' which maps to underlying data type nvarchar(128).
Found table with name 'dbo.Department'.
Found column with table: dbo.Department, column name: DeptID, ordinal: 1, data type: sys.int, maximum length: 4, precision: 10, scale: 0, nullable: False, identity: False, default value: (null), computed value: (null), computed value is stored: False.
Found column with table: dbo.Department, column name: DeptName, ordinal: 2, data type: sys.varchar, maximum length: 50, precision: 0, scale: 0, nullable: False, identity: False, default value: (null), computed value: (null), computed value is stored: False.
Found column with table: dbo.Department, column name: ManagerID, ordinal: 3, data type: sys.int, maximum length: 4, precision: 10, scale: 0, nullable: True, identity: False, default value: (null), computed value: (null), computed value is stored: False.
Found column with table: dbo.Department, column name: ParentDeptID, ordinal: 4, data type: sys.int, maximum length: 4, precision: 10, scale: 0, nullable: True, identity: False, default value: (null), computed value: (null), computed 
value is stored: False.
Found column with table: dbo.Department, column name: ValidFrom, ordinal: 5, data type: sys.datetime2, maximum length: 8, precision: 27, scale: 7, nullable: False, identity: False, default value: (null), computed value: (null), computed value is stored: False.
Found column with table: dbo.Department, column name: ValidTo, ordinal: 6, data type: sys.datetime2, maximum length: 8, precision: 27, scale: 7, nullable: False, identity: False, default value: (null), computed value: (null), computed value is stored: False.
Found primary key on table 'PK__Departme__0148818E124C33C0' with name 'dbo.Department'.
```

Trying to insert a new  entry or update and existing one
```C#
var dbContext = new DataContext(new Microsoft.EntityFrameworkCore.DbContextOptions<DataContext>());

dbContext.Department.Add(new Department()
{
    DeptId = 1,
    DeptName = "Dep1",
    ManagerId = 1,
    ParentDeptId = null
});
dbContext.SaveChanges();
```
Thrown exception when trying to insert/update an item

```
Microsoft.EntityFrameworkCore.DbUpdateException
  HResult=0x80131500
  Message=An error occurred while saving the entity changes. See the inner exception for details.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__107_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at EFScaffoldProject.Program.Main(String[] args) in C:\dev\EFScaffoldProject\Program.cs:line 20

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
SqlException: Cannot insert an explicit value into a GENERATED ALWAYS column in table 'MyDb.dbo.Department'. Use INSERT with a column list to exclude the GENERATED ALWAYS column, or insert a DEFAULT into GENERATED ALWAYS column.

Inner Exception 1 STACK TRACE:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)


```
EF Core version: 7(Observed same behaviour on version 6)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET7.0(Observed same behaviour on version 6)
Operating system:  Windows 10 Enterprise 22H2
IDE:  Visual Studio 2022 17.6.4
SQL Server:  14.0.3456.2 hosted on  Windows Server 2016 Datacenter (10.0)
***

# Expected output/result
This is the resulting output when scaffolding against the SQL db hosted in a docker container.
***
Context
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
  modelBuilder.Entity<Department>(entity =>
  {
      entity.HasKey(e => e.DeptId).HasName("PK__Departme__0148818E0F98EFB6");

      entity.ToTable(tb => tb.IsTemporal(ttb =>
              {
                  ttb.UseHistoryTable("DepartmentHistory", "dbo");
                  ttb
                      .HasPeriodStart("ValidFrom")
                      .HasColumnName("ValidFrom");
                  ttb
                      .HasPeriodEnd("ValidTo")
                      .HasColumnName("ValidTo");
              }));

      entity.Property(e => e.DeptId)
          .ValueGeneratedNever()
          .HasColumnName("DeptID");
      entity.Property(e => e.DeptName)
          .HasMaxLength(50)
          .IsUnicode(false);
      entity.Property(e => e.ManagerId).HasColumnName("ManagerID");
      entity.Property(e => e.ParentDeptId).HasColumnName("ParentDeptID");
  });

  OnModelCreatingPartial(modelBuilder);
}
```
Model
```C#
public partial class Department
{
    public int DeptId { get; set; }

    public string DeptName { get; set; } = null!;

    public int? ManagerId { get; set; }

    public int? ParentDeptId { get; set; }
}
```
Scaffold logs
```
Using project 'C:\dev\EFScaffoldProject\EFScaffoldProject.csproj'.
Using startup project 'C:\dev\EFScaffoldProject\EFScaffoldProject.csproj'.
Writing 'C:\dev\EFScaffoldProject\obj\EFScaffoldProject.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\A\AppData\Local\Temp\tmp7F31.tmp /verbosity:quiet /nologo C:\dev\EFScaffoldProject\EFScaffoldProject.csproj
Writing 'C:\dev\EFScaffoldProject\obj\EFScaffoldProject.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\A\AppData\Local\Temp\tmp84DF.tmp /verbosity:quiet /nologo C:\dev\EFScaffoldProject\EFScaffoldProject.csproj
dotnet exec --depsfile C:\dev\EFScaffoldProject\bin\Debug\net7.0\EFScaffoldProject.deps.json --additionalprobingpath C:\Users\A\.nuget\packages --runtimeconfig C:\dev\EFScaffoldProject\bin\Debug\net7.0\EFScaffoldProject.runtimeconfig.json C:\Users\A\.dotnet\tools\.store\dotnet-ef\7.0.10\dotnet-ef\7.0.10\tools\net6.0\any\tools\netcoreapp2.0\any\ef.dll dbcontext scaffold "connect" Microsoft.EntityFrameworkCore.SqlServer --namespace EFScaffoldProject.DatabaseModelsss --force --no-pluralize --no-onconfiguring --output-dir DatabaseModelsss --table Department --assembly C:\dev\EFScaffoldProject\bin\Debug\net7.0\EFScaffoldProject.dll --project C:\dev\EFScaffoldProject\EFScaffoldProject.csproj --startup-assembly C:\dev\EFScaffoldProject\bin\Debug\net7.0\EFScaffoldProject.dll --startup-project C:\dev\EFScaffoldProject\EFScaffoldProject.csproj --project-dir C:\dev\EFScaffoldProject\ --root-namespace EFScaffoldProject --language C# --framework net7.0 --nullable --working-dir C:\dev\EFScaffoldProject --verbose
Using assembly 'EFScaffoldProject'.
Using startup assembly 'EFScaffoldProject'.
Using application base 'C:\dev\EFScaffoldProject\bin\Debug\net7.0'.
Using working directory 'C:\dev\EFScaffoldProject'.
Using root namespace 'EFScaffoldProject'.
Using project directory 'C:\dev\EFScaffoldProject\'.
Remaining arguments: .
Finding design-time services referenced by assembly 'EFScaffoldProject'...
Finding design-time services referenced by assembly 'EFScaffoldProject'...
No referenced design-time services were found.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding IDesignTimeServices implementations in assembly 'EFScaffoldProject'...
No design-time services were found.
Found default schema 'dbo'.
Found type alias with name 'sys.sysname' which maps to underlying data type nvarchar(128).
Found table with name 'dbo.Department'.
Found column with table: dbo.Department, column name: DeptID, ordinal: 1, data type: sys.int, maximum length: 4, precision: 10, scale: 0, nullable: False, identity: False, default value: (null), computed value: (null), computed value is stored: False.
Found column with table: dbo.Department, column name: DeptName, ordinal: 2, data type: sys.varchar, maximum length: 50, precision: 0, scale: 0, nullable: False, identity: False, default value: (null), computed value: (null), computed value is stored: False.
Found column with table: dbo.Department, column name: ManagerID, ordinal: 3, data type: sys.int, maximum length: 4, precision: 10, scale: 0, nullable: True, identity: False, default value: (null), computed value: (null), computed value is stored: False.
Found column with table: dbo.Department, column name: ParentDeptID, ordinal: 4, data type: sys.int, maximum length: 4, precision: 10, scale: 0, nullable: True, identity: False, default value: (null), computed value: (null), computed 
value is stored: False.
Found primary key on table 'PK__Departme__0148818E0F98EFB6' with name 'dbo.Department'.
```
EF Core version: 7(Observed same behaviour on version 6)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET7.0(Observed same behaviour on version 6)
Operating system:  Windows 10 Enterprise 22H2
IDE:  Visual Studio 2022 17.6.4
SQL Server:  14.0.3456.2 hosted on  Ubuntu (18.04)
***

**Comment by ErikEJ** [comment] 2023-08-11 12:37
Have you double checked the table definition in the other environments?

**Comment by albertcristian** [comment] 2023-08-11 13:42
Yes, it's the same across all environments.

**Comment by ajcvickers** [comment] 2023-09-25 10:07
@albertcristian I am not able to reproduce this. Can you check the permissions on the database where it doesn't work and check that nothing has been done to lock down access to the schema definition?

**Comment by ajcvickers** [comment] 2023-10-25 18:09
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-10-25 18:09 UTC
Labels: customer-reported
