### ISSUE TITLE
InvalidOperationException: Processing of the LINQ expression 's => s     .GroupBy(t => t.Column2)     .AsQueryable()     .FirstOrDefault()' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core.

### ISSUE THREAD

**Issue by dhruvpiesoftware** [dotnet/efcore#20241] opened 2020-03-10 17:39 UTC
Hello,

When I execute the below query, I get the exception given below the query.

> Table1.GroupBy(s => s.Column1).SelectMany(s => s.GroupBy(t => t.Column2).FirstOrDefault()).ToList()

**Exception :** 

> InvalidOperationException: Processing of the LINQ expression 's => s     .GroupBy(t => t.Column2)     .AsQueryable()     .FirstOrDefault()' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core.

Please let me know best solution for the same.

Thank you.

**Comment by vovikdrg** [comment] 2020-03-10 22:27
Could you explain what do you want to achieve with that query?

**Comment by dhruvpiesoftware** [comment] 2020-03-11 05:03
Hello @vovikdrg ,

In **Table1** I want to group by **Column1**, and then in this group i want to group by **Column2** and then I want to take first group items from it. 

Column1 ||  Column2   || Column3
1                || A               || 10
1                || A               || 20
2                || B               || 30
2                || B               || 40
3                || C               || 50
3                || D               || 60
4                || A               || 70
What I want is

1              || A                || 10
2              || B                || 30
3              || C                || 50
4              || A                || 70

As result. Let me know if you still need any explanation.

Thank you.

**Comment by dhruvpiesoftware** [comment] 2020-03-12 09:59
Hello @vovikdrg ,

Is there any update on above issue?

Thank you.

**Comment by ajcvickers** [comment] 2020-03-13 18:00
@smitpatel to de-dupe.

**Comment by ajcvickers** [comment] 2020-03-13 18:01
Duplicate of #12088

**Closed** 2022-10-16 18:15 UTC
Labels: closed-duplicate, customer-reported
