### ISSUE TITLE
in Beta7, what does this error mean?  in Beta 6 ,it is OK.

### ISSUE THREAD

**Issue by lovemory** [dotnet/efcore#3067] opened 2015-09-09 08:52 UTC
A database operation failed while processing the request.

InvalidOperationException: The property 'ImageID' on entity type 'ImageStore' has a temporary value while attempting to change the entity's state to 'Unchanged'. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property. 
Applying existing migrations for ApplicationDbContext may resolve this issue
There are migrations for ApplicationDbContext that have not been applied to the database

20150909075858_InitialCreate
You can also apply migrations from the command line:

> dnx . ef migration apply

bye  the way , it doesn't exit the command "apply", and "migration" has chang to "migrations"

**Comment by rowanmiller** [comment] 2015-09-09 19:51
Can you provide sample code that we can use to reproduce and debug the issue?

**Comment by lovemory** [comment] 2015-09-10 03:58
the code is simple.

    public enum ImageCatalogType
    {
        Profile = 0
    }
    public class ImageStore
    {
        [Key]
        public Guid ImageID { get; set; }
        public int ImageCatalog { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public string Owner { get; set; }
    }

 public ActionResult Create(ImageStore  model)

        {
           
            IFormFile  file = Request.Form.Files["ImagePath"];

            if (file != null)
            {
                var parsedContentDisposition = ContentDispositionHeaderValue.Parse(file.ContentDisposition);
                var originalName = parsedContentDisposition.FileName.Replace("\"", "");

                string strFileName =UploadImageServices.SaveToFile(file, _env);
                ImageStore _image = new ImageStore();
                _image.ImageName = originalName;
                _image.ImagePath = strFileName;// path;
                _image.Owner = Context.User.GetUserId();

                _db.Add(_image);
                _db.SaveChanges(); // error happen here
            }
            
            return RedirectToAction("Index");



        }

**Comment by CuddleBunny** [comment] 2015-09-18 15:42
I also get this error when there is a pending migration, it took me a few minutes to find that the command is now `dnx ef database update`. The issue is already fixed on dev: https://github.com/aspnet/Diagnostics/pull/181

**Closed** 2022-10-16 09:08 UTC
