### ISSUE TITLE
Query: NRE when executing a complex query with functions with arguments having optional navs on InMemory provider

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#13746] opened 2018-10-24 20:21 UTC
test that fails for in memory (works fine on other providers):

Null_semantics_is_correctly_applied_for_function_comparisons_that_take_arguments_from_optional_navigation_complex

query:

```
ctx.Tags.Where(t => t.Note.Substring(0, t.Gear.Squad.Name.Length) == t.GearNickName);
```

**Comment by smitpatel** [comment] 2019-12-10 22:28
```
  Message: 
    System.InvalidOperationException : Nullable object must have a value.
  Stack Trace: 
    lambda_method(Closure , ValueBuffer )
    WhereSelectEnumerableIterator`2.MoveNext()
    Enumerator.MoveNext() line 86
    LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
    EnumerableHelpers.ToArray[T](IEnumerable`1 source)
    Enumerable.ToArray[TSource](IEnumerable`1 source)
    QueryAsserter`1.AssertQuery[TResult](Func`2 actualQuery, Func`2 expectedQuery, Func`2 elementSorter, Action`2 elementAsserter, Boolean assertOrder, Int32 entryCount, Boolean async, String testMethodName) line 87
    --- End of stack trace from previous location where exception was thrown ---
```

**Comment by smitpatel** [comment] 2019-12-10 22:29
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/17540

**Closed** 2022-10-16 13:37 UTC
Labels: area-query, area-in-memory
