### ISSUE TITLE
Self referencing loop detected for property error when updating a model

### ISSUE THREAD

**Issue by whizkidwwe1217** [dotnet/efcore#14058] opened 2018-12-01 11:58 UTC
I already set the ReferenceLoopHandling to Ignore to ignore cyclic references. However, I'm still getting the same error when trying to update a model in a DBContext.

Payload

### Steps to reproduce
```csharp
services.AddMvc(options => options.Filters.Add<RequestAbortedFilter>())
.SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
 .AddJsonOptions(options =>
{
    options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
})
```
Call dbcontext.Update()
```csharp
DbContext.Update<Item>(item);
```
Model:
```csharp
class Item
{
   public int Id { get; set; }
   public List<UnitMeasure> UnitMeasures { get; set; }
}

class UnitMeasure
{
   public int Id { get; set; }
   public int ItemId { get; set; }
   public Item Item { get; set; }
}
```
UnitMeasure Configuration
```csharp
builder.HasOne(e => e.Item)
   .WithMany(e => e.UnitMeasures)
   .HasForeignKey(e => e.ItemId)
```
Request Payload
```json
{
   "id": 2,
   "unitMeasures": [
       {
             "itemId": 2
        }
   ]
}
```
### Further technical details
EF Core version: (found in project.csproj or packages.config) 2.1.+
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment] 2018-12-03 18:21
@whizkidwwe1217 This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2018-12-12 18:50
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:42 UTC
Labels: closed-could-not-reproduce, customer-reported
