### ISSUE TITLE
CoreCLR x86 can't load sni.dll

### ISSUE THREAD

**Issue by gpeipman** [dotnet/efcore#3787] opened 2015-11-18 22:05 UTC
**The error reported here is due to an issue with SQL Client, which is being tracked by https://github.com/dotnet/corefx/issues/3760. As a workaround, you can try installing [Visual C++ Redistributable for Visual Studio 2012](https://www.microsoft.com/en-us/download/details.aspx?id=30679).**

Ported my CoreCLR x86 application to RC1 and here's what I get when connecting to database (on CoreCLR x64 everything works fine):

```
Request starting HTTP/1.1 GET http://localhost:5000/
fail: Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
      System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception. 
---> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception. 
---> System.DllNotFoundException: Unable to load DLL 'C:\Users\gpeipman\.dnx\packages\runtime.win7-x86.System.Data.SqlClient.sni\4.0.0-beta-23516\runtimes\win7-x86\native\sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
         at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath)
         at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath)
         at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadUnmanagedLibraryFromPath(String path)
         at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.LoadUnmanagedLibrary(String name)
         at Microsoft.Dnx.Host.LoaderContainer.LoadUnmanagedLibrary(String name)
         at Microsoft.Dnx.Host.DefaultLoadContext.LoadUnmanagedLibrary(String name)
         at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadUnmanagedDll(String unmanagedDllName)
```

_Edited: full stack trace [here](https://gist.githubusercontent.com/natemcmaster/18096ef52be513f805ef/raw/9446de2df8e65db23d21b78fce022396db79db6b/full_stack_trace.log)_

**Comment by natemcmaster** [comment] 2015-11-18 22:54
Possible duplicate of https://github.com/aspnet/EntityFramework/issues/1545

**Comment by rowanmiller** [comment] 2015-11-18 23:06
What OS are you running on? It could be that you need to install  [Visual C++ Redistributable for Visual Studio 2012](https://www.microsoft.com/en-us/download/details.aspx?id=30679).

**Comment by npnelson** [comment] 2015-11-19 01:10
I have a similar issue.  My EF7 app was working great (x64 CoreCLR) under beta8 on Azure Web App. I upgraded to RC1 and it works fine locally, but I get the following error when running on Azure Web App:

FileNotFoundException: Could not load the specified file.

System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)

FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Microsoft.Data.Entity.Storage.Internal.SqlServerConnection.CreateDbConnection()

Let me know if I should open a separate issue or if you want me to try to set up a simple repository so to reproduce the issue.

**Comment by rowanmiller** [comment] 2015-11-19 20:01
@npnelson that is a different issue from the one being discussed here. The one you are hitting is https://github.com/aspnet/EntityFramework/issues/3637

**Comment by natemcmaster** [comment] 2015-11-20 18:18
Our CI agent on Win7 x64 threw a similar error. It seems SqlClient and dnx still have unresolved issues in our rc2. Possibly the same problem as described above...?

```
Unable to load DLL ".dnx\packages\runtime.win7-x64.System.Data.SqlClient.sni\4.0.0-rc2-23519\runtimes\win7-x64\native\sni.dll": The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

**Comment by rowanmiller** [comment] 2015-11-23 20:54
https://github.com/dotnet/corefx/issues/3760 is being used to track this issue in SQL Client.

**Closed** 2022-10-16 09:16 UTC
