### ISSUE TITLE
Migration missing on Linux, but not on Windows.

### ISSUE THREAD

**Issue by Pentadome** [dotnet/efcore#30088] opened 2023-01-18 10:08 UTC
### Issue

I got the following unit test that is designed to check if a migration is missing from the migrations assembly:

```csharp
public void IsNotMissingMigration()
{
    var builder = new DesignTimeServicesBuilder(
        typeof(MyDbContext).Assembly,
        typeof(MyDbContext).Assembly,
        new OperationReporter(null),
        Array.Empty<string>()
    );

    var provider = builder.Build(new DesignTimeMyDbContextFactory().CreateDbContext(Array.Empty<string>()));
    var dependencies = provider.GetRequiredService<MigrationsScaffolderDependencies>();

    var migrationsModelSnapshot = dependencies.MigrationsAssembly.ModelSnapshot;
    var migrationsModel = dependencies.SnapshotModelProcessor.Process(migrationsModelSnapshot?.Model);
    var migrationsRelationalModel = migrationsModel?.GetRelationalModel();

    var dbContextRelationalModel = dependencies.Model.GetRelationalModel();

    var differences = dependencies.MigrationsModelDiffer.GetDifferences(
        migrationsRelationalModel,
        dbContextRelationalModel
    );
    differences.Should().BeEmpty();
}
```

`DesignTimeMyDbContextFactory().CreateDbContext` creates a dbcontext that is configured to connect to a relational database.

On Windows, this test passes without any problems. But on Linux (Azure Pipelines) the test fails.

```
Expected differences to be empty, but found {
Microsoft.EntityFrameworkCore.Migrations.Operations.AlterColumnOperation
{
	ClrType = System.Int32,
	Collation = <null>,
	ColumnType = "int",
	Comment = "SomeComment",
	ComputedColumnSql = "SomeSql",
	DefaultValue = <null>,
	DefaultValueSql = <null>,
	IsDestructiveChange = False,
	IsFixedLength = <null>,
	IsNullable = True,
	IsReadOnly = False,
	IsRowVersion = False,
	IsStored = True,
	IsUnicode = <null>,
	MaxLength = <null>,
	Name = "SomeName",
	OldColumn =
		Microsoft.EntityFrameworkCore.Migrations.Operations.AddColumnOperation
		{
			ClrType = System.Int32,
			Collation = <null>,
			ColumnType = "int",
			Comment = "SomeComment",
			ComputedColumnSql = "SomeSql",
			DefaultValue = <null>,
			DefaultValueSql = <null>,
			IsDestructiveChange = False,
			IsFixedLength = <null>,
			IsNullable = True,
			IsReadOnly = False,
			IsRowVersion = False,
			IsStored = True,
			IsUnicode = <null>,
			MaxLength = <null>,
			Name = <null>,  /// <-- Note: Name is null
			Precision = <null>,
			Scale = <null>,
			Schema = <null>,
			Table = <null> /// <-- Note: Table is null
		},
	Precision = <null>,
	Scale = <null>,
	Schema = <null>,
	Table = "SomeTable"
}
}
```

I know I'm using internal API in my unit test but I still wanted to report this issue.

### Workaround

Apply the following filter to the differences collection:
```csharp
private static IReadOnlyList<MigrationOperation> FilterOutBuggyDifferences(
      IReadOnlyList<MigrationOperation> operations
  )
  {
      if (Environment.OSVersion.Platform is not PlatformID.Unix || operations.Count == 0)
          return operations;

      var newCollection = new List<MigrationOperation>();

      foreach (var operation in operations)
      {
          if (
              operation
              is not AlterColumnOperation
              {
                  OldColumn.Name: null // How can name be null???
              }
          )
          {
              newCollection.Add(operation);
          }
      }
      return newCollection;
  }
```

All Ef nuget packages are 7.0.2

**Comment by ajcvickers** [comment] 2023-01-18 20:28
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-01-27 13:11
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-01-27 13:11 UTC
