### ISSUE TITLE
EF Core 2.2: Linq subquery join with groupby could not be translated and will be evaluated locally

### ISSUE THREAD

**Issue by eddyzhu1980** [dotnet/efcore#14148] opened 2018-12-12 05:00 UTC
Describe what is not working as expected.

					var sentShippingOrdersQuery= (from so in OrderShippingOrders
                                                where so.IsSent == true
                                                group so by so.OrderId into g
                                                select new {
                                                    OrderId= g.Key,
                                                    CountShippingOrderSent=g.Count()
                                                });

                    var shippingOrdersQuery= (from so in OrderShippingOrders
                                                group so by new {so.OrderId} into g
                                                join st in sentShippingOrdersQuery
                                                    on g.Key.OrderId equals st.OrderId
                                                select new {
                                                    OrderId=g.Key.OrderId,
                                                    CountShippingOrder=g.Count()
                                                });

                    var allSent= (from so in shippingOrdersQuery
                                join st in sentShippingOrdersQuery
                                    on new {so.OrderId,so.CountShippingOrder} equals new {OrderId= st.OrderId,CountShippingOrder= st.CountShippingOrderSent} 
                                select new { so.OrderId  });
                                
                    (from o in Orders
                                join s in allSent
                                    on o.Id equals s.OrderId
                            select o).Dump();

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'GroupBy(new <>f__AnonymousType19`1(OrderId = [so].OrderId), [so])' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == True) select [so] => GroupBy([so].OrderId, [so])}
select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on [g].Key.OrderId equals [st].OrderId' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'Count()' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == True) select [so] => GroupBy([so].OrderId, [so])}
select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on new <>f__AnonymousType20`2(OrderId = [g].Key.OrderId, CountShippingOrder = {[g] => Count()}) equals new <>f__AnonymousType20`2(OrderId = [st].OrderId, CountShippingOrder = [st].CountShippingOrderSent)' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'GroupBy(new <>f__AnonymousType19`1(OrderId = [so].OrderId), [so])' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == True) select [so] => GroupBy([so].OrderId, [so])}
select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on [g].Key.OrderId equals [st].OrderId' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'Count()' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == True) select [so] => GroupBy([so].OrderId, [so])}
select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on new <>f__AnonymousType20`2(OrderId = [g].Key.OrderId, CountShippingOrder = {[g] => Count()}) equals new <>f__AnonymousType20`2(OrderId = [st].OrderId, CountShippingOrder = [st].CountShippingOrderSent)' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'join <>f__AnonymousType19`1 s in {from IGrouping`2 g in {value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) => GroupBy(new <>f__AnonymousType19`1(OrderId = [so].OrderId), [so])} join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == True) select [so] => GroupBy([so].OrderId, [so])} select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on [g].Key.OrderId equals [st].OrderId join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == True) select [so] => GroupBy([so].OrderId, [so])} select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on
new <>f__AnonymousType20`2(OrderId = [g].Key.OrderId, CountShippingOrder = {[g] => Count()}) equals new <>f__AnonymousType20`2(OrderId = [st].OrderId, CountShippingOrder = [st].CountShippingOrderSent) select new <>f__AnonymousType19`1(OrderId = [g].Key.OrderId)} on [o].Id equals [s].OrderId' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'GroupBy(new <>f__AnonymousType19`1(OrderId = [so].OrderId), [so])' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == Convert(__queryObj_IsSent_Value_0, Nullable`1)) select [so] => GroupBy([so].OrderId, [so])} select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on [g].Key.OrderId equals [st].OrderId' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'Count()' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == Convert(__queryObj_IsSent_Value_0, Nullable`1)) select [so] => GroupBy([so].OrderId, [so])} select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on new <>f__AnonymousType20`2(OrderId = [g].Key.OrderId, CountShippingOrder = {[g] => Count()}) equals new <>f__AnonymousType20`2(OrderId = [st].OrderId, CountShippingOrder = [st].CountShippingOrderSent)' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'GroupBy(new <>f__AnonymousType19`1(OrderId = [so].OrderId), [so])' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == Convert(__queryObj_IsSent_Value_0, Nullable`1)) select [so] => GroupBy([so].OrderId, [so])} select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on [g].Key.OrderId equals [st].OrderId' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'Count()' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == Convert(__queryObj_IsSent_Value_0, Nullable`1)) select [so] => GroupBy([so].OrderId, [so])} select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on new <>f__AnonymousType20`2(OrderId = [g].Key.OrderId, CountShippingOrder = {[g] => Count()}) equals new <>f__AnonymousType20`2(OrderId = [st].OrderId, CountShippingOrder = [st].CountShippingOrderSent)' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'join <>f__AnonymousType19`1 s in {from IGrouping`2 g in {value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) => GroupBy(new <>f__AnonymousType19`1(OrderId = [so].OrderId), [so])} join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == Convert(__queryObj_IsSent_Value_0, Nullable`1)) select [so] => GroupBy([so].OrderId, [so])} select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on [g].Key.OrderId equals [st].OrderId join <>f__AnonymousType18`2 st
in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == Convert(__queryObj_IsSent_Value_0, Nullable`1)) select [so] => GroupBy([so].OrderId, [so])} select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on new <>f__AnonymousType20`2(OrderId = [g].Key.OrderId, CountShippingOrder = {[g] => Count()}) equals new <>f__AnonymousType20`2(OrderId = [st].OrderId, CountShippingOrder = [st].CountShippingOrderSent) select new <>f__AnonymousType19`1(OrderId = [g].Key.OrderId)} on [o].Id equals [s].OrderId' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'Count()' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[10102]
      Query: '(from Order o in DbSet<Order> join <>f__AnonymousType19<int> s in  from IGrouping<<>f__AnonymousType...' uses a row limiting operation
(Skip/Take) without OrderBy which may lead to unpredictable results.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'GroupBy(new <>f__AnonymousType19`1(OrderId = [so].OrderId), [so])' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == Convert(__queryObj_IsSent_Value_0, Nullable`1)) select [so] => GroupBy([so].OrderId, [so])} select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on [g].Key.OrderId equals [st].OrderId' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'Count()' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == Convert(__queryObj_IsSent_Value_0, Nullable`1)) select [so] => GroupBy([so].OrderId, [so])} select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on new <>f__AnonymousType20`2(OrderId = [g].Key.OrderId, CountShippingOrder = {[g] => Count()}) equals new <>f__AnonymousType20`2(OrderId = [st].OrderId, CountShippingOrder = [st].CountShippingOrderSent)' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'GroupBy(new <>f__AnonymousType19`1(OrderId = [so].OrderId), [so])' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == Convert(__queryObj_IsSent_Value_0, Nullable`1)) select [so] => GroupBy([so].OrderId, [so])} select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on [g].Key.OrderId equals [st].OrderId' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'Count()' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == Convert(__queryObj_IsSent_Value_0, Nullable`1)) select [so] => GroupBy([so].OrderId, [so])} select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on new <>f__AnonymousType20`2(OrderId = [g].Key.OrderId, CountShippingOrder = {[g] => Count()}) equals new <>f__AnonymousType20`2(OrderId = [st].OrderId, CountShippingOrder = [st].CountShippingOrderSent)' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'join <>f__AnonymousType19`1 s in {from IGrouping`2 g in {value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) => GroupBy(new <>f__AnonymousType19`1(OrderId = [so].OrderId), [so])} join <>f__AnonymousType18`2 st in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == Convert(__queryObj_IsSent_Value_0, Nullable`1)) select [so] => GroupBy([so].OrderId, [so])} select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on [g].Key.OrderId equals [st].OrderId join <>f__AnonymousType18`2 st
in {from IGrouping`2 g in {from OrderShippingOrder so in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ECommerce.API.Models.OrderShippingOrder]) where ([so].IsSent == Convert(__queryObj_IsSent_Value_0, Nullable`1)) select [so] => GroupBy([so].OrderId, [so])} select new <>f__AnonymousType18`2(OrderId = [g].Key, CountShippingOrderSent = {[g] => Count()})} on new <>f__AnonymousType20`2(OrderId = [g].Key.OrderId, CountShippingOrder = {[g] => Count()}) equals new <>f__AnonymousType20`2(OrderId = [st].OrderId, CountShippingOrder = [st].CountShippingOrderSent) select new <>f__AnonymousType19`1(OrderId = [g].Key.OrderId)} on [o].Id equals [s].OrderId' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'Skip(__p_1)' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'Take(__p_2)' could not be translated and will be evaluated locally.
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
2.2
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) SQL Server
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.4)
VS Code latest one

**Comment by smitpatel** [comment] 2018-12-12 21:38
```

                var shippingOrdersQuery= (from so in OrderShippingOrders
                                            group so by new {so.OrderId} into g
                                            join st in sentShippingOrdersQuery
                                                on g.Key.OrderId equals st.OrderId
                                            select new {
                                                OrderId=g.Key.OrderId,
                                                CountShippingOrder=g.Count()
                                            });

```
You are doing a join after group by before aggregate (which is not part of result anyway), hence we evaluate it on client.

**Comment by smitpatel** [comment] 2018-12-12 21:38
Duplicate of #10012

**Comment by eddyzhu1980** [comment] 2018-12-13 22:40
I tried it with LinqPad. It can translate it to SQL.
Can you please advise what is the correct Linq code which can be translated into SQL as per my requirement?

**Comment by smitpatel** [comment] 2018-12-13 23:10
It's not implemented feature.

**Comment by eddyzhu1980** [comment] 2018-12-13 23:45
Based EF core 2.2, can you please advise what is the alternative way to do this using Linq, which can be translated into one SQL?

**Comment by smitpatel** [comment] 2018-12-14 00:00
Just converting the join you wrote into contains filter, it would be like this
```C#
var sentShippingOrdersQuery = (from so in OrderShippingOrders
                                where so.IsSent == true
                                group so by so.OrderId into g
                                select new {
                                    OrderId = g.Key,
                                    CountShippingOrderSent = g.Count()
                                });
var shippingOrdersQuery = (from so in OrderShippingOrders
                            where sentShippingOrdersQuery.Select(c => c.OrderId).Contains(so.OrderId)
                            group so by so.OrderId into g
                            select new {
                                OrderId = g.Key,
                                CountShippingOrder = g.Count()
                            });

var allSent = (from so in shippingOrdersQuery
                join st in sentShippingOrdersQuery
                    on new {so.OrderId,so.CountShippingOrder} equals new {OrderId= st.OrderId,CountShippingOrder= st.CountShippingOrderSent} 
                select new { so.OrderId  });

var result = (from o in Orders
              join s in allSent
                on o.Id equals s.OrderId
            select o);
```

**Comment by smitpatel** [comment] 2018-12-14 00:04
Much easier way to capture the same result would be not to use group by
```C#
var result = (from o in Orders
                join s in (from so in OrderShippingOrders
                            where !OrderShippingOrders.Where(e => e.IsSent == false).Select(e => e.OrderId).Distinct().Contains(so.OrderId)
                            select so.OrderId)
                    on o.Id equals s
                select o);
```

**Comment by smitpatel** [comment] 2018-12-14 23:09
```C#
                List<Order> result = (from o in db.Orders
                                      where (from so in db.OrderShippingOrders
                                             where !db.OrderShippingOrders.Where(e => e.IsSent == false).Select(e => e.OrderId).Distinct().Contains(so.OrderId)
                                             select so.OrderId).Contains(o.Id)
                                      select o).ToList();
```
Worked perfectly for me without any client evaluation and gave correct results. If you are still facing issues with your query then we need full minimal repro code which demonstrate behavior you are seeing. Stackoverflow would be better question to ask this kind of question.

**Comment by sguryev** [comment] 2019-03-06 05:30
Hello,

Could you please provide some workaround to evaluate on the server side?
```
var snapshots = await DbContext.OpenPositionSnapshots
    //.Where(s => s.AssetClass == "FOP")
    .GroupBy(s => s.SnapshotId)
    .ToArrayAsync();
    //.FirstOrDefaultAsync();
```
This query evaluated on the client regardless of final `ToArrayAsync()` or `FirstOrDefaultAsync()` or `Where()`. 

EF Core v2.2.2

**Comment by eddyzhu1980** [comment] 2019-05-07 00:08
> ```cs
>                 List<Order> result = (from o in db.Orders
>                                       where (from so in db.OrderShippingOrders
>                                              where !db.OrderShippingOrders.Where(e => e.IsSent == false).Select(e => e.OrderId).Distinct().Contains(so.OrderId)
>                                              select so.OrderId).Contains(o.Id)
>                                       select o).ToList();
> ```
> 
> Worked perfectly for me without any client evaluation and gave correct results. If you are still facing issues with your query then we need full minimal repro code which demonstrate behavior you are seeing. Stackoverflow would be better question to ask this kind of question.

Awesome. It works. Thank you very much! sorry for late response.

**Closed** 2022-10-16 13:43 UTC
Labels: customer-reported
