### ISSUE TITLE
Not possible to asynchronously define schema name at runtime

### ISSUE THREAD

**Issue by kewinbrand** [dotnet/efcore#20600] opened 2020-04-11 04:12 UTC
Hey,

Say I have a system that uses a database that the data is separated by schema and the schemas name are discovered at runtime.
Currently what I do is inject a custom service in my migrations that discovers the correct schema (my migrations are applied at runtime for each customer when needed):

```
public partial class AddedPopulatioProperty : Migration
{
	
  private readonly ISchemaNameProvider _schemaNameProvider;
  
  public AddedPopulatioProperty(ISchemaNameProvider schemaNameProvider)
  {
  	_schemaNameProvider = schemaNameProvider;
  }
  
  protected override void Up(MigrationBuilder migrationBuilder)
  {
  	migrationBuilder.AddColumn<float>(
  		name: "Population",
  		table: "Cities",
  		nullable: true, schema: _schemaNameProvider.GetSchemaName());
  }
  
  protected override void Down(MigrationBuilder migrationBuilder)
  {
  	migrationBuilder.DropColumn(
  		name: "Population",
  		table: "Cities", schema: _schemaNameProvider.GetSchemaName());
  }
}
```

But this has a problem which is what if my GetSchemaName is async? Like making a call to a external service or getting it from a distributed cache?

Thank you so far.

**Comment by bricelam** [comment] 2020-04-14 22:09
One (slightly ugly) option is to use a custom base type for migrations:

```cs
public abstract class MyMigrationBase : Migration
{
    public static string DefaultSchema { get; set; }
}

public partial class AddedPopulatioProperty : MyMigrationBase
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
  	migrationBuilder.AddColumn<float>(
  		name: "Population",
                schema: DefaultSchema,
  		table: "Cities",
  		nullable: true);
    }
)
```

And set it before migrating:

```cs
MyMigrationBase.DefaultSchema = "mySchema";
dbContext.Database.Migrate();
```

Duplicate of https://github.com/dotnet/efcore/issues/10660 for injecting a service.

**Closed** 2022-10-16 18:20 UTC
Labels: closed-duplicate, customer-reported
