### ISSUE TITLE
Fluent API nullreference when defining composite key for abstract class if [Key] attributes not also included

### ISSUE THREAD

**Issue by JohannSig** [dotnet/efcore#15934] opened 2019-06-04 11:41 UTC
We're getting some mixed signals from EF Core documentation regarding Fluent API VS [Key] attribute usage for composite keys.

Given the following abstract and implementing class:
```c#
public abstract class AAbsoluteRanking
{
	public int GameId { get; set; }
	public int LocalId { get; set; }
	public RankingCategory RankingCategory { get; set; } // Enum
	public double Value { get; set; }
}

public class EmpireAbsoluteRanking : AAbsoluteRanking
{
	public virtual Empire Empire { get; set; }
}
```

We seek to define a composite key on the first three properties of the abstract class. 

If we add a [Key] attribute to each property (which, as mentioned [here](https://www.learnentityframeworkcore.com/configuration/fluent-api/haskey-method), is not supported in EF Core), then if we run the command ```add-migration InitialMigration```, we get the expected error:

 ```Entity type 'EmpireAbsoluteRanking' has composite primary key defined with data annotations. To set composite primary key, use fluent API.```

So we remove the [Key] attributes and define a model building method for it, using Fluent API:

```c#
private static void BuildAbsoluteModels(this ModelBuilder builder)
{
	builder.Entity<AAbsoluteRanking>()
		.HasKey(x => new { x.GameId, x.LocalId, x.RankingCategory });

	builder.Entity<EmpireAbsoluteRanking>()
		.HasOne(x => x.Empire)
		.WithMany(x => x.AbsoluteRankings)
		.HasForeignKey(x => new { x.GameId, x.LocalId })
		.IsRequired()
		.OnDelete(DeleteBehavior.Cascade);
}
```

This causes a nullreference exception when we run the command ```add-migration InitialMigration```:

```
Exception message: System.NullReferenceException: Object reference not set to an instance of an object.

Stack trace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasKeyInternal(IReadOnlyList`1 properties, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.PrimaryKey(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.PrimaryKey(IReadOnlyList`1 clrProperties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasKey(Expression`1 keyExpression)
   at Starborne.Global.RankingsApi.Contexts.XModelBuilder.BuildAbsoluteModels(ModelBuilder builder) in D:\Projects\StarborneDesktop\Starborne.Global.RankingsApi\Contexts\XModelBuilder.cs:line 37
   at Starborne.Global.RankingsApi.Contexts.XModelBuilder.BuildModels(ModelBuilder builder) in D:\Projects\StarborneDesktop\Starborne.Global.RankingsApi\Contexts\XModelBuilder.cs:line 12
   at Starborne.Global.RankingsApi.Contexts.RankingsDbContext.OnModelCreating(ModelBuilder modelBuilder) in D:\Projects\StarborneDesktop\Starborne.Global.RankingsApi\Contexts\RankingsDbContext.cs:line 31
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_2(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

Then, out of experimental desperation, we ALSO add the [Key] attributes to the abstract class properties like so: 

```c#
	public abstract class AAbsoluteRanking
	{
		[Key]
		public int GameId { get; set; }

		[Key]
		public int LocalId { get; set; }

		[Key]
		public RankingCategory RankingCategory { get; set; }
		public double Value { get; set; }
	}
```

.. and by sheer dumb luck, the migration is successfully added 🤔 

What gives?

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.1.1

**Comment by ajcvickers** [comment] 2019-06-04 16:20
@JohannSig This looks like a bug, but I have not been able to reproduce it but I had to guess at some of the missing code from your snippets above--see my code below. Can you post a small, runnable project/solution or runnable code listing (like below) that throws the exception you are seeing.

```C#
public abstract class AAbsoluteRanking
{
    public int GameId { get; set; }
    public int LocalId { get; set; }
    public RankingCategory RankingCategory { get; set; } // Enum
    public double Value { get; set; }
}

public class EmpireAbsoluteRanking : AAbsoluteRanking
{
    public virtual Empire Empire { get; set; }
}

public class Empire
{
    public int Id1 { get; set; }
    public int Id2 { get; set; }

    public ICollection<EmpireAbsoluteRanking> AbsoluteRankings { get; set; }
}

public enum RankingCategory
{
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Empire>()
            .HasKey(x => new { x.Id1, x.Id2 });

        modelBuilder.Entity<AAbsoluteRanking>()
            .HasKey(x => new { x.GameId, x.LocalId, x.RankingCategory });

        modelBuilder.Entity<EmpireAbsoluteRanking>()
            .HasOne(x => x.Empire)
            .WithMany(x => x.AbsoluteRankings)
            .HasForeignKey(x => new { x.GameId, x.LocalId })
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade);    }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }
    }
}
```

Model:
```
Model: 
  EntityType: AAbsoluteRanking Abstract
    Properties: 
      GameId (int) Required PK FK AfterSave:Throw 0 0 0 -1 -1
      LocalId (int) Required PK FK AfterSave:Throw 1 1 1 -1 -1
      RankingCategory (RankingCategory) Required PK AfterSave:Throw 2 2 2 -1 -1
      Discriminator (no field, string) Shadow Required AfterSave:Throw 3 3 -1 0 -1
      Value (double) Required 4 4 -1 -1 -1
    Keys: 
      GameId, LocalId, RankingCategory PK
  EntityType: Empire
    Properties: 
      Id1 (int) Required PK AfterSave:Throw 0 0 0 -1 -1
      Id2 (int) Required PK AfterSave:Throw 1 1 1 -1 -1
    Navigations: 
      AbsoluteRankings (<AbsoluteRankings>k__BackingField, ICollection<EmpireAbsoluteRanking>) Collection ToDependent EmpireAbsoluteRanking Inverse: Empire 0 -1 2 -1 -1
    Keys: 
      Id1, Id2 PK
  EntityType: EmpireAbsoluteRanking Base: AAbsoluteRanking
    Navigations: 
      Empire (<Empire>k__BackingField, Empire) ToPrincipal Empire Inverse: AbsoluteRankings 0 -1 3 -1 -1
    Foreign keys: 
      EmpireAbsoluteRanking {'GameId', 'LocalId'} -> Empire {'Id1', 'Id2'} ToDependent: AbsoluteRankings ToPrincipal: Empire
```

**Comment by ajcvickers** [comment] 2019-06-14 16:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:23 UTC
Labels: closed-could-not-reproduce, customer-reported
