### ISSUE TITLE
Provider Caching policies

### ISSUE THREAD

**Issue by tvkit** [dotnet/efcore#20070] opened 2020-02-26 09:46 UTC
Data not persisting to storage until context goes out of scope (via app shutdown).

A handful of small data updates are not persisting to a SQL 2019 instance with netcore 3.1.2 until I close the app. The same binaries are not exhibiting this behavior on a workstation with SQL 2017 and net core 3.1.  It's not a matter of seconds. The flush is simply not happening until shutdown. The volume of data is very low.

Adding the **EnableServiceProviderCaching(false)** option results in the immediate availability of the data on the SQL 2019 db instance -- a behavior similar to the SQL 2017 / netcore 3.1 environment. I understand this option is generally not desirable.

Are there provider caching policies that we can adjust to best serve our requirements?

**Comment by roji** [comment] 2020-02-26 17:46
@tvkit can you provide a runnable code sample that shows data not being saved? Calling SaveChanges should commit all your changes, regardless of version of SQL Server. EnableServiceProviderCaching shouldn't really be related to any of this.

**Comment by tvkit** [comment] 2020-02-28 04:21
@roji  Certainly.  Currently under water, but I'll organize something as soon as possible. The host exhibiting the behavior is going out for shipment. I'll need to reproduce the environment.

**Comment by ajcvickers** [comment] 2020-03-06 17:25
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by tvkit** [comment] 2020-03-06 18:57
@ajcvickers  There are over 1,300 open issues dating far beyond the 9 days this ticket was opened. Slow day?

**Comment by ajcvickers** [comment] 2020-03-06 19:55
@tvkit I don't understand your question. If you have a repro, then we can re-open.

**Comment by roji** [comment] 2020-03-06 20:46
@tvkit just to give more information about the process, we generally don't keep issues open and untriaged for long - we either confirm them (e.g. as a feature we want to implement) by assigning a milestone to them (which can be backlog), or we close them. This doesn't mean we won't treat your problem - as soon as you have a repro please post back here and we'll reopen and investigate.

**Closed** 2022-10-16 18:13 UTC
Labels: closed-could-not-reproduce, customer-reported
