### ISSUE TITLE
"Enumerator failed to MoveNextAsync" when there's more than 1 record when using SingleOrDefaultAsync(CancellationToken)

### ISSUE THREAD

**Issue by jeroenlandheer** [dotnet/efcore#21729] opened 2020-07-22 12:03 UTC
Related to: https://github.com/dotnet/efcore/issues/19639 

When you use `SingleOrDefaultAsync()` on a set that has *more than one* result that fits the criteria you get the error message `Enumerator failed to MoveNextAsync`. This does not describe the error correctly.

The correct message should be: `Sequence contains more than one element.`

### Steps to reproduce

TableName: Test
| FieldA | FieldB |
|--------|--------|
| 1 | A |
| 2 | A |

```
var query = from p in context.Test where p.FieldB == "A";
var err = await query.SingleOrDetaultAsync();
```

### Further technical details

EF Core version: 3.1.6
Database provider: NpgSql v3.1.4
Target framework: .NET Core 3.1
Operating system: Win10
IDE: VS2019 16.7-preview5

**Comment by smitpatel** [comment] 2020-07-22 15:29
Duplicate of #18742

**Closed** 2022-10-16 18:34 UTC
Labels: closed-duplicate, customer-reported
