### ISSUE TITLE
Allow overriding three-valued logic compensations for null equality checks

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#3035] opened 2015-09-05 16:41 UTC
Tracks discussion started in #3023.

EF Core currently generates special SQL for equality since the equality comparer cannot be used for checking null. For example, for checking if two parameters are equal the following is used: `C = D OR (C IS NULL AND D IS NULL)`.

PostgreSQL (and possibly other providers) has a `IS [NOT] DISTINCT FROM` syntax which covers exactly this scenario: checking for equality (or inequality) including null. It would be nice to allow providers to use this instead of the complicated SQL currently generated.

Since this `IS [NOT] DISTINCT FROM` is in the SQL:1999 and might be supported by other databases, it might be a good idea to implement it in EntityFramework.Relational and expose a flag to providers for using it.

**Comment by smitpatel** [comment] 2019-11-12 19:38
@roji - Do you want to investigate other provider support for this in next release?

**Comment by roji** [comment] 2019-11-13 03:35
Wow, 2015.....

I can look at it if we think it's worth it. I seem to remember rumors about this being slow, but I don't think they were substantiated.

FWIW MySQL seems to have this too [as the <=> operator](https://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html#operator_equal-to)

**Comment by smitpatel** [comment] 2020-03-15 20:22
@roji - Now that nullability based visitor is public, you can potentially achieve this.

**Comment by smitpatel** [comment] 2020-03-15 20:52
Duplicate of #10514

**Closed** 2022-10-16 09:07 UTC
Labels: closed-duplicate, area-query
