### ISSUE TITLE
Conventions :: model is configured differently based on the name of Primary Keys

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#1373] opened 2015-01-08 23:26 UTC
Consider the following model:

```
    public class Customer
    {
        public int CId { get; set; }
        public string Name { get; set; }

        public Order Order { get; set; }
    }

    public class Order
    {
        public int OId { get; set; }
        public string Name { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Order> Orders { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Customer>().Key(o => o.CId);
            modelBuilder.Entity<Order>().Key(o => o.OId);
            modelBuilder.Entity<Customer>().OneToOne(c => c.Order);
            modelBuilder.Entity<Order>().Key(o => o.OId);
        }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "MultiLevelInclude2", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var c1 = new Customer
                {
                    CId = 1,
                    Name = "Customer1"
                };

                var o1 = new Order
                {
                    OId = 1,
                    Name = "Order1"
                };

                ctx.Customers.Add(c1);
                ctx.Orders.Add(o1);

                ctx.SaveChanges();

                c1.Order = o1;

                ctx.SaveChanges();
            }
        }
    }
```

this works fine, however if the PKs on Customer and Order would be refactor-renamed into "Id", we start throwing exception:

Unhandled Exception: Microsoft.Data.Entity.Update.DbUpdateException: An error oc
curred while updating the entries. See the inner exception for details. ---> Sys
tem.Data.SqlClient.SqlException: Cannot insert explicit value for identity colum
n in table 'Customer' when IDENTITY_INSERT is set to OFF.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolea
n breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception
, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObj
ect stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand
 cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler,
TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, Run
Behavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBe
havior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 time
out, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehav
ior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletio
nSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehav
ior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, S
tring method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behav
ior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.Data.Entity.Relational.Update.ReaderModificationCommandBatch.Exe
cute(RelationalTransaction transaction, RelationalTypeMapper typeMapper, DbConte
xt context, ILogger logger) in D:\k\EntityFramework\src\EntityFramework.Relation
al\Update\ReaderModificationCommandBatch.cs:line 168
   --- End of inner exception stack trace ---
   at Microsoft.Data.Entity.Relational.Update.ReaderModificationCommandBatch.Exe
cute(RelationalTransaction transaction, RelationalTypeMapper typeMapper, DbConte
xt context, ILogger logger) in D:\k\EntityFramework\src\EntityFramework.Relation
al\Update\ReaderModificationCommandBatch.cs:line 196
   at Microsoft.Data.Entity.Relational.Update.BatchExecutor.Execute(IEnumerable`
1 commandBatches, RelationalConnection connection) in D:\k\EntityFramework\src\E
ntityFramework.Relational\Update\BatchExecutor.cs:line 68
   at Microsoft.Data.Entity.Relational.RelationalDataStore.SaveChanges(IReadOnly
List`1 stateEntries) in D:\k\EntityFramework\src\EntityFramework.Relational\Rela
tionalDataStore.cs:line 76
   at Microsoft.Data.Entity.ChangeTracking.StateManager.SaveChanges(IReadOnlyLis
t`1 entriesToSave) in D:\k\EntityFramework\src\EntityFramework.Core\ChangeTracki
ng\StateManager.cs:line 415
   at Microsoft.Data.Entity.ChangeTracking.StateManager.SaveChanges() in D:\k\En
tityFramework\src\EntityFramework.Core\ChangeTracking\StateManager.cs:line 368
   at Microsoft.Data.Entity.DbContext.SaveChanges() in D:\k\EntityFramework\src\
EntityFramework.Core\DbContext.cs:line 214
   at MultiInclude2.Program.Main(String[] args) in D:\Projects\MultiInclude2\Mul
tiInclude2\Program.cs:line 133

**Comment by maumar** [comment] 2015-01-08 23:28
Key are explicitly defined in both cases - I would expect exact same behavior if only property name is changed.

**Comment by AndriySvyryd** [comment] 2015-01-08 23:33
Currently KeyConvention finds the key and configures it to GenerateValueOnAdd.
We could separate the key configuration into another convention to make the behavior consistent if the key is specified explicitly and not found by the convention.

**Comment by rowanmiller** [comment] 2015-01-09 19:24
@AndriySvyryd Feel free to close as dupe if you have it tracked elsewhere

**Comment by AndriySvyryd** [comment] 2015-01-12 20:11
Duplicate of #1271

**Closed** 2022-10-16 08:49 UTC
Labels: type-bug
