### ISSUE TITLE
EF Core Limitations

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#19133] opened 2019-12-02 17:47 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/837965/ef-core-limitations.html)._

---
<p>I’m not clear if the following query is fundamentally not appropriate for LINQ, or if this is just a limitation that could be eliminated.</p>
<pre>var tasks = (from a in DbContext.Areas
             from g in a.Goals
             from t in g.Tasks
             let nextTaskId = g.Tasks.OrderBy(tt =&gt; tt.Sequence).Select(tt =&gt; tt.Id).DefaultIfEmpty(-1).FirstOrDefault()
             where t.ShowAlways || t.Id == nextTaskId
             select new CalendarTask
             {

                 // Member assignment

             }).ToList();
</pre><p>As it is, I get the following exception:</p>
<pre>System.InvalidOperationException: 'Processing of the LINQ expression 'OrderBy&lt;Task, int&gt;(
    source: MaterializeCollectionNavigation(Navigation: Goal.Tasks (&lt;Tasks&gt;k__BackingField, DbSet&lt;Task&gt;) Collection ToDependent Task Inverse: Goal, Where&lt;Task&gt;(
        source: NavigationExpansionExpression
            Source: Where&lt;Task&gt;(
                source: DbSet&lt;Task&gt;, 
                predicate: (t0) =&gt; Property&lt;Nullable&lt;int&gt;&gt;((Unhandled parameter: ti0).Outer.Inner, &quot;Id&quot;) == Property&lt;Nullable&lt;int&gt;&gt;(t0, &quot;GoalId&quot;))
            PendingSelector: (t0) =&gt; NavigationTreeExpression
                Value: EntityReferenceTask
                Expression: t0
        , 
        predicate: (i) =&gt; Property&lt;Nullable&lt;int&gt;&gt;(NavigationTreeExpression
            Value: EntityReferenceGoal
            Expression: (Unhandled parameter: ti0).Outer.Inner, &quot;Id&quot;) == Property&lt;Nullable&lt;int&gt;&gt;(i, &quot;GoalId&quot;))), 
    keySelector: (tt) =&gt; tt.Sequence)' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.'
</pre><p>If I comment out the line that sets `nextTaskId`, there is no error.</p><p>Is this a query that could potentially be supported? I'll readily admit I do not understand the specifics of the error message.</p>

---
#### Visual Studio Feedback System on 11/29/2019, 00:41 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2019-12-06 18:20
@smitpatel to follow up.

**Comment by smitpatel** [comment] 2019-12-06 22:27
Duplicate of #17783

**Comment by SoftCircuits** [comment] 2019-12-07 02:42
I'm not able see a description of #17783. But the title seems to indicate it's about DefaultIfEmpty(). In fact, my code still fails if I remove the call to DefaultIfEmpty(). Was the nature of this issue misunderstood.

**Comment by smitpatel** [comment] 2019-12-07 17:04
Your code contains DefaultIfEmpty with argument. Hence duplicate.

**Comment by smitpatel** [comment] 2019-12-07 17:04
In any case, share a runnable project.

**Comment by SoftCircuits** [comment] 2019-12-07 18:03
It may duplicate use of DefaultIfEmpty(). But it's a different issue that's being reported.

**Comment by ajcvickers** [comment] 2019-12-07 18:50
@SoftCircuits Please post a small, runnable project that reproduces what you are seeing.

**Comment by SoftCircuits** [comment] 2019-12-07 19:37
> @SoftCircuits Please post a small, runnable project that reproduces what you are seeing.

I'm really not sure how to do this. It would require a database, my migrations and data models, along with the code.

**Comment by ajcvickers** [comment] 2019-12-07 19:40
@SoftCircuits The idea is that you isolate the part of your code that is not working as you expect it, then create a simple model and context in a console application that reproduces that behavior.

**Comment by ajcvickers** [comment] 2019-12-16 17:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by rattymml** [comment] 2019-12-28 04:06
I have an example project that reproduces this error. What's the best way to share that?
[EF3DefaultIfEmptyError.zip](https://github.com/aspnet/EntityFrameworkCore/files/4006696/EF3DefaultIfEmptyError.zip)

**Comment by smitpatel** [comment] 2019-12-29 01:10
@rattymml - Your repro code uses DefaultIfEmpty with argument and it would be duplicate of #17783

**Closed** 2022-10-16 14:59 UTC
Labels: closed-could-not-reproduce, customer-reported
