### ISSUE TITLE
Odd issues with Preview8

### ISSUE THREAD

**Issue by foconnor-DS** [dotnet/efcore#17154] opened 2019-08-14 20:26 UTC
I updated a project from netcoreapp2.2 to netcoreapp3.0 and use Preview8 SDK as well as Microsoft.EntityFrameworkCore.SqlServer, tools and design.

I can build and run my projects locally just find. But when I try to deploy with Azure Devops, the Nuget restore says:

`NU1202: Package Microsoft.EntityFrameworkCore.SqlServer 3.0.0-preview8.19405.11 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package Microsoft.EntityFrameworkCore.SqlServer 3.0.0-preview8.19405.11 supports: netstandard2.1 (.NETStandard,Version=v2.1)`

Which makes no sense to me. 

I know this may not be EF Core's bug (because I can build it find in VS 2019), but maybe someone has seen them happen before?

I'm setting the .Net Core SDK in the pipeline to Preview8 via a global.json.

**Comment by ajcvickers** [comment] 2019-08-16 18:52
@foconnor-DS Is the preview 8 SDK installed on the DevOps agents?

**Comment by ajcvickers** [comment] 2019-08-23 15:57
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:35 UTC
Labels: closed-could-not-reproduce, customer-reported
