### ISSUE TITLE
Where Expression not translated with optional navigation property

### ISSUE THREAD

**Issue by sepplK** [dotnet/efcore#5625] opened 2016-06-02 09:07 UTC
### The issue

Where Expression is lost in SQL when using optional Navigation Property...
### Steps to reproduce

```
public class TestDbContext : IDataDbContext
{
    public DbSet<Master> Masters { get; set; }
    public DbSet<Child> Childs { get; set; }
}

public class Master
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class Child
{
    public int Id { get; set; }
    public string Name { get; set; }

    public int? MasterId { get; set; }   // nullable
    public Master Master { get; set; }
}
```

```
var dc = new TestDbContext();

var childs = dc.Childs
    .Where(c => c.Master.Name == "xxx")
    .ToList();
```

```
SELECT [c].[Id], [c].[MasterId], [c].[Name], [c.Master].[Id], [c.Master].[Name]
FROM [Childs] AS [c]
LEFT JOIN [Masters] AS [c.Master] ON [c].[MasterId] = [c.Master].[Id]
ORDER BY [c].[MasterId]
```

(Only LEFT JOIN and Where missing)

**After changing the Property [MasterId] to not-nullable it works:**

```
public class Child
{
    public int Id { get; set; }
    public string Name { get; set; }

    public int MasterId { get; set; } // not nullable
    public Master Master { get; set; }
}
```

```
SELECT [c].[Id], [c].[MasterId], [c].[Name]
FROM [Childs] AS [c]
INNER JOIN [Masters] AS [c.Master] ON [c].[MasterId] = [c.Master].[Id]
WHERE [c.Master].[Name] = N'xxx'
```
### Further technical details

EF Core version:1.0.0-rc2-final
Operating system: Windows 10 x64
Visual Studio version: VS 2015
SQL Version: 2014

**Comment by maumar** [comment] 2016-06-02 20:43
duplicate of https://github.com/aspnet/EntityFramework/issues/4588

**Closed** 2022-10-16 09:43 UTC
