### ISSUE TITLE
FirstOrDefault on empty collection of projections gives a non-null empty projection

### ISSUE THREAD

**Issue by imb590** [dotnet/efcore#19010] opened 2019-11-21 14:20 UTC
Behavior of EF Core 3.0 differs from EF Core 2.2.6 on the following query:

``` C#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

class Program
{
    static void Main(string[] args)
    {
        using (var db = new Context())
        {
            db.Database.EnsureDeleted();
            db.Database.EnsureCreated();

            db.Groups.Add(new Group());
            db.SaveChanges();

            var result = db
                .Groups
                .Select(e => new
                {
                    Item = e.Items.Select(i => new { i.Id }).FirstOrDefault(),
                })
                .FirstOrDefault();
            Console.WriteLine(result.Item == null);
        }
    }
}

public class Context : DbContext
{
    public DbSet<Group> Groups { get; set; }
    public DbSet<Item> Items { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlite("filename=test.db");
    }
}

public class Group
{
    public int Id { get; set; }
    public ICollection<Item> Items { get; set; }
}

public class Item
{
    public int Id { get; set; }
    public int GroupId { get; set; }
    public Group Group { get; set; }
}
```

With EF Core 2.2.6 the program prints "True", as expected. With EF Core 3.0.1 the same program prints "False", with an object having default fields values materialized in `result.Item`.

**Comment by smitpatel** [comment] 2019-11-21 16:18
Duplicate of #17287

**Closed** 2022-10-16 14:57 UTC
Labels: customer-reported
