### ISSUE TITLE
Adding a graph of new entities

### ISSUE THREAD

**Issue by hey-red** [dotnet/efcore#7425] opened 2017-01-16 17:03 UTC
[Docs](https://docs.microsoft.com/en-us/ef/core/saving/related-data#adding-a-graph-of-new-entities) has been obsoleted?
Currently it's wont work, and needs to manually add new posts before blog:
```C#
context.Posts.Add(new Post { Title = "Intro to C#" });
context.Posts.Add(new Post { Title = "Intro to C#" });
....
```

**Comment by ajcvickers** [comment] 2017-01-17 17:59
**EF Team Triage:** The docs are not out of date. This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

**Comment by rowanmiller** [comment] 2017-01-30 20:04
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 10:50 UTC
