### ISSUE TITLE
Owned value object not materialized after using Linq To SQL Union

### ISSUE THREAD

**Issue by Mohamad-Yousef** [dotnet/efcore#29862] opened 2022-12-15 10:04 UTC
Hello everyone

One of my entities "Entity A" owns a Money value object

```c#
EntityA_builder.OwnsOne(c => c.Amount, x=>
{
   x.Property(a => a.Value).HasColumnName("Amount");
   x.Property(a => a.CurrencyIso).HasMaxLength(3).HasColumnName("Currency").IsRequired();
});
EntityA_builder.Navigation(x => x.Amount).IsRequired();
```

I have an odd behavior here
when querying this entity alone "Query1" the Amount Navigation is materialized 
"note: both amount and currency cols has no null values in DB"
and all the following queries "Query2a" that uses the same entity joined with other entities and union-ed with another query "Query2b" its Amount Navigation is populated.

```c#
var Q2a =  from a in entityA
join b in entityB on ....
join c in entityC on ....
 where ....
 select new {a,b,c}; 

var Q2b =  from a in entityA
join b in entityB on ....
join c in entityC on ....
join d in entityD on ....
 where ....
 select new {a,b,c,d};

var Q1 = await (from a in entityA select a).ToListAsync(); // ==> Amount materialized 

var Q2 = await Q2a.Union(Q2b).ToListAsync(); // ==> Amount materialized 
```

BUT
1. If I commented out Query1
then in Query2 the amount and Currency cols are excluded from the final generated SQL script "Amount Navigation becomes NULL"

```c#
var Q2a =  from a in entityA
join b in entityB on ....
join c in entityC on ....
 where ....
 select new {a,b,c}; 

var Q2b =  from a in entityA
join b in entityB on ....
join c in entityC on ....
join d in entityD on ....
 where ....
 select new {a,b,c,d};

//var Q1 = await (from a in entityA select a).ToListAsync();

var Q2 = await Q2a.Union(Q2b).ToListAsync(); // ==> Amount not materialized 
```

2. If I commented out Query1 AND
materialized the queries Q2a and Q2b then applied the Linq to obj union operator Amount Navigation is materialized

```c#
var Q2a =  await(from a in entityA
join b in entityB on ....
join c in entityC on ....
 where ....
 select new {a,b,c}).ToListAsync(); // ==> Amount materialized

var Q2b = await( from a in entityA
join b in entityB on ....
join c in entityC on ....
join d in entityD on ....
 where ....
 select new {a,b,c,d}).ToListAsync(); // ==> Amount materialized

//var Q1 = await (from a in entityA select a).ToListAsync();

var Q2 = Q2a.Union(Q2b); // ==> Amount already materialized 
```

Does The Linq To SQL Union operator has an issue ?

Any help would be appreciated

side Questions : 
Do I have to mark the Amount as virtual in the POCO model ?
Do I have to add migration and update DB if I added/removed config like
"builder.Navigation(x => x.Amount).IsRequired();" ?

EF Core version: 7.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Win 10
IDE: Visual Studio 2022 17.4

**Comment by ajcvickers** [comment] 2022-12-22 12:12
@Mohamad-Yousef This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-01-11 20:03
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-01-11 20:03 UTC
Labels: customer-reported
