### ISSUE TITLE
Invalid Operation Translating Expression

### ISSUE THREAD

**Issue by granthoff1107** [dotnet/efcore#20895] opened 2020-05-09 04:06 UTC
I just recently upgraded to  .Net-Core 3.13.    I get an Invalid Operation exception when I run this query (which previously use to run fine in .Net-Core 2.1)

    var userIds = new List<int> { currentUserId, receiverId };
    var testb = this._context.Conversations.Where(x =>
            userIds.All(userId => x.ConversationSubscriptions.Select(cs => cs.UserId).Contains(userId)))
        .Select(x => x.Id)
        .ToList();

I get an Error:

> System.InvalidOperationException
  HResult=0x80131509
  Message=The LINQ expression 'DbSet<Conversation>
    .Where(c => __userIds_0
        .All(userId => DbSet<ConversationSubscription>
            .Where(c0 => EF.Property<Nullable<int>>(c, "Id") != null && EF.Property<Nullable<int>>(c, "Id") == EF.Property<Nullable<int>>(c0, "ConversationId"))
            .Select(c0 => c0.UserId)
            .Contains(userId)))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Astoot.Services.ConversationDTOService.<GetOrCreateConversation>d__5.MoveNext() in C:\source\Astoot\src\Astoot\Services\ConversationDTOService.cs:line 60

I have a DB structure like so:

    public partial class Conversation
    {
        public Conversation()
        {
            ConversationSubscriptions = new HashSet<ConversationSubscription>();
            Messages = new HashSet<Message>();
        }

        public int Id { get; set; }
        public DateTime Created { get; set; }

        public ICollection<ConversationSubscription> ConversationSubscriptions { get; set; }
        public ICollection<Message> Messages { get; set; }
    }

    public partial class ConversationSubscription
    {
        public int Id { get; set; }
        public int ConversationId { get; set; }
        public int UserId { get; set; }
        public DateTime SubscribeTime { get; set; }
        public bool IsSubscribed { get; set; }
        public DateTime? UnsubscribeTime { get; set; }
        public Conversation Conversation { get; set; }
        public User User { get; set; }
    }

**Comment by granthoff1107** [comment] 2020-05-09 04:11
Note: this is not a work around but just for additional info to debug with
FYI, The inverse seems to work fine:

     var test = this._context.Conversations
                .Where(x => x.ConversationSubscriptions
                    .Select(cs => cs.UserId)
                    .All(userId => userIds.Contains(userId))).FirstOrDefault();

**Comment by granthoff1107** [comment] 2020-05-09 04:15
As a workaround I'm doing this:
    
    var testb = this._context.Conversations
                .Where(x => x.ConversationSubscriptions.Select(cs => cs.UserId).Contains(currentUserId))
                .Where(x => x.ConversationSubscriptions.Select(cs => cs.UserId).Contains(receiverId))
                .Select(x => x.Id)
                .ToList();

But most people who need to use a list cannot do this, and will have to manually build their expression tree, its Jenky AF.

**Comment by smitpatel** [comment] 2020-05-09 11:17
Duplicate of #19070

**Closed** 2022-10-16 18:24 UTC
Labels: closed-duplicate, customer-reported
