### ISSUE TITLE
Getting a string[] from a UDF

### ISSUE THREAD

**Issue by TehWardy** [dotnet/efcore#17025] opened 2019-08-08 09:38 UTC
I can't seem to find anything about table valued functions in EF core is this even possible.
Here's a sample of what I would like to achieve ...

I have a role class that looks like this ...

```
[Table("Roles", Schema = "Security")]
public class Role 
{
     [Key]
     public Guid Id { get; set; }

     // this is a csv list of "privilege keys" that the role grants
     public string Privs { get; set; }
     ...
}
```

Add this to my DbContext ...

```
[DbFunction("[DMS].[GetFolderPrivList]")]
public static string[] GetFolderPrivList(string userId, Guid folderId)
{
    throw new Exception();
}
```

Then I have a UDF like this to compute a list of privs for a folder "path" (which recursively crawls the tree for inherited permissions) ...

```
CREATE FUNCTION [DMS].[GetFolderPrivList] 
(	@UserId nvarchar(450),
	@FolderId uniqueidentifier
)
RETURNS @PrivList TABLE ( priv nvarchar(100) NOT NULL)
AS
BEGIN
	INSERT INTO @PrivList (priv)
		SELECT DISTINCT *
		  FROM STRING_SPLIT((SELECT R.Privs FROM DMS.Folders P
		  JOIN [Security].FolderRoles PR ON FR.FolderId= P.Id
		  JOIN [Security].Roles R ON R.Id= FR.RoleId
		  JOIN [Security].UserRoles UR ON UR.RoleId = R.Id
		  WHERE P.Id=@FolderId AND UR.UserId=@UserId),',');

	IF (SELECT ParentId FROM [DMS].[Folders] WHERE Id=@FolderId) IS NOT NULL
	BEGIN
		INSERT INTO @PrivList (priv)
			SELECT priv
			  FROM [DMS].[GetFolderPrivList](@UserId,(SELECT ParentId FROM CMS.Pages WHERE Id=@FolderId))
			  WHERE priv NOT IN (SELECT priv FROM @PrivList)
	END	--*/
	RETURN
END;
```

I can't get EF to accept this such that I can make the call in a linq query, for example ...

```
db.GetAll<Folder>().FirstOrDefault(f => f.AppId == app.Id && f.Path.ToLower() == path.Lowered && CoreDataContext.GetFolderPrivList(user.Id, f.Id).Contains(privKey))
```

**Comment by ajcvickers** [comment] 2019-08-09 18:20
Duplicate of #4319

**Closed** 2022-10-16 14:34 UTC
Labels: closed-duplicate, customer-reported
