### ISSUE TITLE
Ignore Models from external dbcontexts

### ISSUE THREAD

**Issue by joaorsfonseca** [dotnet/efcore#16884] opened 2019-08-01 11:47 UTC
I'm trying to build some architecture where i have a butch of common stuff in one single project and reuse them in all my other projects.
One of those things is, user management (identity framework).

I'm using the **same database** for all those projects

My ProjectContext looks like this:
```c#
namespace Project.Database
{
    public class ProjectContext : DbContext
    {
        public ProjectContext(DbContextOptions<ProjectContext> options) 
            : base(options)
        {
        }

        protected ProjectContext(DbContextOptions options)
            : base(options)
        {
        }

        public DbSet<Entity1> Entity1 { get; set; }

        public DbSet<SC.Database.Models.Identity.ApplicationUser> User { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            //modelBuilder.Ignore<SC.Database.Models.Identity.ApplicationUser>();
        }
    }
}
```

Entity1 looks like this:
```c#
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Project.Database.Models
{
    public class Entity1
    {
        [Key]
        public int Id { get; set; }
        public string MyProperty { get; set; }
        public string SecondProp { get; set; }
        [Required]
        public string UserId { get; set; }
        [ForeignKey("UserId")]
        public virtual SC.Database.Models.Identity.ApplicationUser User { get; set; }
    }
}
```

As you can see, ApplicationUser is from another dll (another context) (SC is my common project).
If I uncomment the modelBuild.Ignore line the table won't be created (👍) but the foreign keys i have neither 😒

Will creating migrations, is there a way to only ignore the CreateTable and DropTable? Instead of ignore everything related with that Model.

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: Visual Studio Enterprise 2017 15.9.14

**Comment by ajcvickers** [comment] 2019-08-01 15:17
Duplicate of #2725

**Closed** 2022-10-16 14:33 UTC
Labels: closed-duplicate, customer-reported
