### ISSUE TITLE
add-migration and Update-database don`t work on VS Community 2022 Preview(1.7.5.0 Preview 2.0) 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#30090] opened 2023-01-18 11:38 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/add-migration-and-Update-database-dont-/10248380)._

---

add-migration and Update-database don`t work on VS Community 2022 Preview(1.7.5.0 Preview 2.0) 
![изображение.png](https://aka.ms/dc/image?name=B26d02c70c4e34187ad3a71a4251aff8c638088755578629022_20230109-183917-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5.png&tid=26d02c70c4e34187ad3a71a4251aff8c638088755578629022)
But on powershell all works fine 
![изображение.png](https://aka.ms/dc/image?name=Bc00ab084d7974f80b7326a0a61986ebb638088756263345552_20230109-184025-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5.png&tid=c00ab084d7974f80b7326a0a61986ebb638088756263345552)

---
#### Feedback Bot on 1/10/2023, 01:50 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2023-01-27 13:12
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-01-27 13:12 UTC
Labels: customer-reported
