### ISSUE TITLE
The LINQ expression 'Sum()' could not be translated and will be evaluated locally.

### ISSUE THREAD

**Issue by mdmoura** [dotnet/efcore#15231] opened 2019-04-02 09:01 UTC
When using SUM with GroupBy I get the following message:

The LINQ expression 'Sum()' could not be translated and will be evaluated locally.

### Steps to reproduce

The query that produces the described behaviour is:

```
var results = context.Packages.AsNoTracking()
  .Select(x => new {
    Result = x.Products
      .SelectMany(y => y.Definition.Conversions, (Product, Conversion) => new { Product = Product, Conversion = Conversion })
      .Where(y => y.Product.DefinitionId == y.Conversion.DefinitionId)
      .Select(y => new {
        Coefficient = y.Conversion.Coefficient,
        Price = y.Product.Price.Value,
      })
      .GroupBy(y => 1)
      .Select(y => new {
        Coefficient = y.Sum(z => z.Coefficient),
        Price = y.Sum(z => z.Price)
      })
    }).ToList();
```

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: macOs Mojave 10.14.3
IDE: Visual Studio Code 1.32.3

**Comment by smitpatel** [comment] 2019-04-11 00:17
Duplicate of #15279

**Comment by smitpatel** [comment] 2019-04-11 00:18
It is same query. Doing group by for nested collection like that requires outer/cross apply rather than just GroupBy so not critical for 3.0

**Closed** 2022-10-16 13:58 UTC
Labels: closed-duplicate
