### ISSUE TITLE
Saving entity with NetTopologySuite.Geometries.Polygon property throws NullReferenceException

### ISSUE THREAD

**Issue by BrandoCaserotti** [dotnet/efcore#18310] opened 2019-10-10 08:57 UTC
Trying to add an entity to the DbContext and then calling SaveChangesAsync throws NullReferenceException if NetTopologySuite is used and the Polygon property has null value.

### Steps to reproduce

This is the entity that I'm trying to save through the classic DbSet.Add + DbContext.SaveChangesAsync 
```csharp
public class Cant{

        public int Id { get; private set; }

        public string Address { get; private set; }
        public Nullable<int> Cap { get; private set; }
        public string City { get; private set; }
        public string Code { get; private set; }
        public string Description { get; private set; }
        public bool Disabled { get; private set; }
        public string Nation { get; private set; }
        public string Notes { get; private set; }
        public double Latitude { get; private set; }
        public double Longitude { get; private set; }
        public double Radius { get; private set; }
        public Polygon Location { get; private set; } //This is NetTopologySuite.Geometry.Polygon
}

```

I am not assigning a value to the Location property (therefore is null).

This is the NullReferenceException stacktrace that the DbContext throws on SaveChangesAsync:

```
at
Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerGeometryTypeMapping`1.CreateUdtTypeNameAccessor(Type paramType)
at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerGeometryTypeMapping`1<>c__DisplayClass13_0.<ConfigureParameter>b__1()
at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Func`1 valueFactory)
at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerGeometryTypeMapping`1.ConfigureParameter(DbParameter parameter)
at Microsoft.EntityFrameworkCore.Storage.RelationalGeometryTypeMapping`2.CreateParameter(DbCommand command, String name, Object value, Nullable``1 nullable)
at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
at Microsoft.EntityFrameworkCore.Storage.Relation
alCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)"
```

### Further technical details
NetTopologySuite version: 2.0.0.0
EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer, SqlServer.NetTopologySuite 3.0.0
Target framework: (e.g. .NET Core 3.0)
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by bricelam** [comment] 2019-10-16 21:51
@zap93 I'm not able to reproduce this issue. Could you share your project? Are you using a "wrapping provider"? (i.e. Is your SqlParameter object hidden inside another parameter type?)

**Comment by zap93** [comment] 2019-10-18 07:33
Hi bricelam,

I cannot fully share my project but I can share some pieces of code that could possibly be usefull to you.

This is how the DbContext is configured:

` protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(_transactionCoordinator.Connection, opts => { 
                 opts.UseNetTopologySuite(); 
            });
            }
            base.OnConfiguring(optionsBuilder);
        }`

where _transactionCoordinator.Connection is a SqlConnection.

My code is really simple,  just create the entity,  add to the DbContext ChangeTracker and then save.

I'm not using any kind of strange configuration that needs to be mentioned.

This strange behavior has began with the upgrade from preview 7 or 8 to 3.0.0, because it was working as expected at the time.

Anyway just ask me what you need to know and I would be glad to help if I can.

**Comment by ajcvickers** [comment] 2019-10-25 16:06
@bricelam Is there enough information above, or do we still need a full repro?

**Comment by bricelam** [comment] 2019-10-25 18:04
Still not enough info--that's basically the code I used to try. Need a full repro to investigate further.

**Comment by ajcvickers** [comment] 2019-11-01 15:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by AurelianTimu** [comment] 2020-11-03 02:08
I just had exactly the same issue and It took a lot of time to find the problem..

In case it helps others in the future:
I am doing something very similar as what the OP was/is doing - passing an `SqlConnection` to `optionsBuilder.UseSqlServer()` 
It turns out that in my case, the issue was caused by using the `System.Data.SqlClient` namespace. 
After I changed to `Microsoft.Data.SqlClient;` the problem was solved.

**Closed** 2022-10-16 14:48 UTC
Labels: closed-could-not-reproduce, customer-reported
