### ISSUE TITLE
TryUpdateModelAsync deadlock when using a data model lazy loaded

### ISSUE THREAD

**Issue by hadrian625** [dotnet/efcore#12866] opened 2018-08-02 11:58 UTC
Hi,

I am using dotnet core version 2.1.1 and EF core 2.1.0. I have a db context register to use lazy loading
```C#
services.AddDbContext<MyDbContext>(options => options.UseLazyLoadingProxies()
                .UseSqlServer(Configuration.GetConnectionString("ConnectionString")));
```

I have a POST action where I try to use the TryUpdateModelAsync to update a data model tracked by my db context.
The async call just hangs and never completes. If I remove the lazy loading in service configuration the TryUpdateModelAsync  just works fine.

Example code
```C#
public async Task<IActionResult> Edit(int id)
{
   MyDataModel dataModel = dbContext.Set<MyDataModel>().Find(id);
   await TryUpdateModelAsync(dataModel); //here the call hangs and never returns when using lazy loading
   .....more code
}
```
This way of working is also presented on https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/update-related-data?view=aspnetcore-2.0 and https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-2.1 but for me it owrks only if I don't use lazy loading.

**Comment by ajcvickers** [comment] 2018-08-03 18:02
@hadrian625 I have not been able to reproduce this. Could you please post a runnable project/solution that demonstrates the behavior you are seeing so that we can investigate?

**Comment by hadrian625** [comment] 2018-08-04 09:25
I will try to make a simple project to reproduce the problem after I return from holiday

Sent from Yahoo Mail on Android 
 
  On Fri, Aug 3, 2018 at 21:02, Arthur Vickers<notifications@github.com> wrote:   
@hadrian625 I have not been able to reproduce this. Could you please post a runnable project/solution that demonstrates the behavior you are seeing so that we can investigate?

**Comment by hadrian625** [comment] 2018-08-06 10:42
I can definitely say that my deep nested data model is causing this problem I tried decorating the navigation properties with  BindNever attribute, but with no success. If the navigation properties that lead to deep nesting are removed, the TryUpdateModelAsync works just fine.

**Comment by ajcvickers** [comment] 2018-08-13 17:56
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by lxh7** [comment] 2018-08-30 09:13
I've run into the same problem. It seems the problem occurs when there are bi-directional navigation properties defined. (Article <-> ArticleGroup: Article contais both ArticleGroupId and ArticleGroup as navigation properties, ArticleGroup contains Articles collection)

I'm implementing a production planning system (factory scenario), with production orders to produce a certain article, which is built using "recipes" of parts/contents (also articles). Editing a Production Order while lazy loading is enabled, loads virtually the entire database (some articles are purchased via certain purchasing channels, leading to suppliers that supply multiple articles, etc.)

I think the problem is in the fact that behind the TryUpdateModelAsync() function the Id's in the relations are set, but that subsequently the navigation properties are probed. Then the Lazy Loading then kicks in. I haven't digged into it yet, the way it is implemented is quite a complex maze of models and facades and stuff.

On Creation it works for me, as I create a new, empty object and then let it fill by TryUpdateModelAsync(). At that moment it is a plain object, not a Lazy Loading proxy.

Now I'll look into a way to prohibit binding/probing the navigation properties....

**Comment by lxh7** [comment] 2018-08-31 05:27
@ajcvickers informed me about a property on the change tracker: 

```
try
{
    _context.ChangeTracker.LazyLoadingEnabled = false;
    return await TryUpdateModelAsync(...)
}
finally
{
    _context.ChangeTracker.LazyLoadingEnabled = false;
}
```

This solves the problem!

**Closed** 2022-10-16 13:23 UTC
Labels: closed-could-not-reproduce, customer-reported
