### ISSUE TITLE
AsNoTracking breaks GroupBy

### ISSUE THREAD

**Issue by kccsf** [dotnet/efcore#16745] opened 2019-07-25 15:37 UTC
When using AsNoTracking(), client side grouping incorrectly results in a group per entity. When entities are tracked, it works as expected. Worked ok back in preview5.

### Steps to reproduce

```c#
// Group per entity
var test = dbcontext.Entity1
   .AsNoTracking()
   .Include(x => x.Entity2).ThenInclude(x => x.Entity3)
   .SingleOrDefault(x => x.Id == testId);

var groups = test.Entity2.GroupBy(x => x.Entity3);

// Grouped as expected
var test2 = dbcontext.Entity1
   .Include(x => x.Entity2).ThenInclude(x => x.Entity3)
   .SingleOrDefault(x => x.Id == testId);

var groups2 = test2.Entity2.GroupBy(x => x.Entity3);
```

### Further technical details
EF Core version: 3.0.0-preview8.19374.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: 16.3.0 Preview 1.0

**Comment by ajcvickers** [comment] 2019-07-26 22:21
@kccsf I have not been able to reproduce this--see my code below. Can you post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

```C#
public class Entity1
{
    public int Id { get; set; }
    public ICollection<Entity2> Entity2 { get; set; }
}

public class Entity2
{
    public int Id { get; set; }
    public ICollection<Entity3> Entity3 { get; set; }
}

public class Entity3
{
    public int Id { get; set; }
}

public class BloggingContext : DbContext
{
    public DbSet<Entity1> Entity1 { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Entity1
            {
                Entity2 = new List<Entity2>
                { 
                    new Entity2
                    {
                        Entity3 = new List<Entity3>
                        {
                             new Entity3()
                        }
                    }
                }
            });

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var testId = 1;

            var test = context.Entity1
               .AsNoTracking()
               .Include(x => x.Entity2).ThenInclude(x => x.Entity3)
               .SingleOrDefault(x => x.Id == testId);

            var groups = test.Entity2.GroupBy(x => x.Entity3);

            // Grouped as expected
            var test2 = context.Entity1
               .Include(x => x.Entity2).ThenInclude(x => x.Entity3)
               .SingleOrDefault(x => x.Id == testId);

            var groups2 = test2.Entity2.GroupBy(x => x.Entity3);
        }
    }
}
```

**Comment by kccsf** [comment] 2019-07-26 23:05
@ajcvickers - thanks for your efforts, will try and knock something up :-)

**Comment by kccsf** [comment] 2019-07-27 23:27
@ajcvickers
```c#
    public class Blog
    {
        public int Id { get; set; }

        public ICollection<Post> Post { get; set; }
    }

    public class Post
    {
        public int Id { get; set; }

        public Tag Tag { get; set; }

        public Blog Blog { get; set; }
    }

    public class Tag
    {
        public int Id { get; set; }
    }

    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blog { get; set; }

        public DbSet<Post> Post { get; set; }

        public DbSet<Tag> Tag { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    public class Program
    {
        public static async Task Main()
        {
            using (var context = new BloggingContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                var blog1 = new Blog();
                var blog2 = new Blog();
                context.AddRange(blog1, blog2);

                var tag1 = new Tag();
                var tag2 = new Tag();
                var tag3 = new Tag();
                var tag4 = new Tag();
                context.AddRange(tag1, tag2, tag3, tag4);

                var post1 = new Post() { Blog = blog1, Tag = tag1 };
                var post2 = new Post() { Blog = blog1, Tag = tag2 };
                var post3 = new Post() { Blog = blog1, Tag = tag1 };
                var post4 = new Post() { Blog = blog1, Tag = tag1 };
                var post5 = new Post() { Blog = blog1, Tag = tag1 };
                var post6 = new Post() { Blog = blog2, Tag = tag3 };
                var post7 = new Post() { Blog = blog2, Tag = tag3 };
                var post8 = new Post() { Blog = blog2, Tag = tag3 };
                var post9 = new Post() { Blog = blog2, Tag = tag3 };
                var post10 = new Post() { Blog = blog2, Tag = tag3 };
                var post11 = new Post() { Blog = blog2, Tag = tag4 };
                var post12 = new Post() { Blog = blog2, Tag = tag4 };
                var post13 = new Post() { Blog = blog2, Tag = tag4 };
                context.AddRange(post1, post2, post3, post4, post5, post6, post7, post8, post9, post10, post11, post12, post13);

                context.SaveChanges();
            }

            using (var context = new BloggingContext())
            {
                var testId = 1;

                var test = context.Blog
                    .AsNoTracking()
                    .Include(x => x.Post).ThenInclude(x => x.Tag)
                    .SingleOrDefault(x => x.Id == testId);

                var groups = test.Post.GroupBy(x => x.Tag); // Grouped incorrectly

                var test2 = context.Blog
                    .Include(x => x.Post).ThenInclude(x => x.Tag)
                    .SingleOrDefault(x => x.Id == testId);

                var groups2 = test2.Post.GroupBy(x => x.Tag); // Grouped correctly
            }
        }
    }
```

**Comment by ajcvickers** [comment] 2019-07-29 16:14
Note for triage: confirmed that the groups are different. In the no-tracking case, the group with key 1 appears four times instead of only once. (Could this be related to identity resolution?)

**Comment by ajcvickers** [comment] 2019-07-29 17:11
Follow up with @smitpatel

**Comment by smitpatel** [comment] 2019-07-30 18:25
Identity resolution. Since Post is including Tag, for each tag, we get a newly materialized Tag. We don't have a way to know if it would be the same.

**Comment by ajcvickers** [comment] 2019-08-05 19:47
Notes from triage: closing this as by-design, since [no-tracking queries no longer use identity resolution](#13518). This means that there is a different `Tag` instance for each `Post` in a no-tracking query. Also confirmed that this is the same behavior as EF6, which also didn't do identity resolution on no-tracking queries for the reasons described in #13518.

**Closed** 2022-10-16 14:32 UTC
Labels: closed-by-design, customer-reported
