### ISSUE TITLE
EF Core's Cascade Delete not deleting all associated records

### ISSUE THREAD

**Issue by doucsag** [dotnet/efcore#34291] opened 2024-07-26 06:46 UTC
I have a user with multiple UserRoles. When I delete said User using the UserManager, It deletes the users Admin UserRole. All other Roles assigned to this user are not deleted.  Looking at the code in the UserStore.cs 

https://github.com/dotnet/aspnetcore/blob/main/src/Identity/EntityFrameworkCore/src/UserStore.cs 

all it does is 

```cs
Context.Remove(user);
```

I have tracked it down to the line above. After this there are two changes in the change tracker. Why is it doing this? And why only one of the roles? Cause after it calls context remove it calls save changes where my code checks for soft deleted entities in the change tracker and updates them to be soft deleted instead of fully deleted.

### version information

EF Core version:
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 8
Operating system: Windows 11
IDE: Visual Studio 2022 17.8.5

**Comment by doucsag** [comment] 2024-07-26 07:12
Ok, so I've been digging a bit more and it seems to be the StateManager which applies the CascadeDelete. I haven't figured out a workaround yet or why it would only delete one Role.

**Comment by doucsag** [comment] 2024-07-26 08:16
Ok so my Solution is to set the Cascade to ClientNoAction or NoAction (not sure which one to pick in this case) but then delete the contents of the migration as I still want the cascade behavior on the db side. If anyone knows a better way, please let me know.

**Comment by arminatwork** [comment] 2024-07-26 12:41
@doucsag can you explain a better example or make clear your problem? you can set CascadeDelete to your Entity, and when you call a Remove entity, it will remove all children relations navigation.

**Comment by doucsag** [comment] 2024-07-26 14:52
@arminatwork The thing is, it doesn't. I have assigned multiple Identity UserRoles to my User and when I call Remove on my User, it removes only one of the UserRoles. Identity configures Cascade Delete by default on UserRoles but when you intercept the changes in the SaveChanges and soft delete the User instead by setting e.g. IsDeleted on it, then the User is not Deleted but a single UserRole will be deleted.

**Comment by doucsag** [comment] 2024-07-26 14:57
I have also observed this by debugging the ChangeTracker where I looked at the Count (I believe this variable is on the StateManager) which counts the changes and the changes list and upon removing the User, there were two changes and the count was "2",  one change was the User, the other was the related Role, but at the time the user had 3 roles.

**Comment by arminatwork** [comment] 2024-07-27 05:55
> @arminatwork The thing is, it doesn't. I have assigned multiple Identity UserRoles to my User and when I call Remove on my User, it removes only one of the UserRoles. Identity configures Cascade Delete by default on UserRoles but when you intercept the changes in the SaveChanges and soft delete the User instead by setting e.g. IsDeleted on it, then the User is not Deleted but a single UserRole will be deleted.

did you also set a SoftDelete configuration for UserRole?

**Comment by doucsag** [comment] 2024-07-27 13:10
@arminatwork I did not and that's why the UserRole is not being soft-deleted but that's besides the point. Sorry for the confusion. 

To clarify, my primary concern is not that the role is being deleted, but rather that only one specific role ('Admin') is affected by the delete operation while other roles remain untouched. This inconsistent behavior is puzzling.

**Comment by arminatwork** [comment] 2024-07-27 19:09
> @arminatwork I did not and that's why the UserRole is not being soft-deleted but that's besides the point. Sorry for the confusion.
> 
> To clarify, my primary concern is not that the role is being deleted, but rather that only one specific role ('Admin') is affected by the delete operation while other roles remain untouched. This inconsistent behavior is puzzling.

so if you want to not let users delete the Admin role, you can set a rule for it

**Comment by doucsag** [comment] 2024-07-28 19:58
@arminatwork No that's not what I am saying, I think there might be some misunderstandings due to language differences.

Ef core's cascade delete does not delete all associated records. There are multiple UserRoles associated with a user and upon deleting said user, ef core only deletes one UserRole.

**Comment by roji** [comment] 2024-07-29 17:06
@doucsag this issue is really missing a minimal, runnable code sample that demonstrates the problem - ideally post a small console program.

**Comment by AndriySvyryd** [comment] 2024-08-08 18:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by AndriySvyryd** 2024-08-08 18:44 UTC
Labels: customer-reported
