### ISSUE TITLE
Reverse enginnering scaffolding command fails for EF Core 3 Preview 4

### ISSUE THREAD

**Issue by AspNetWebDev** [dotnet/efcore#15502] opened 2019-04-26 04:51 UTC
I am using EF Core 3 Preview 4 inside an ASP.NET Core 3 Preview 4 application.

1. I installed dotnet-ef tool using this command

`dotnet tool install --global dotnet-ef --version 3.0.0-preview4.19216.3`

2. I added NuGet packages for Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.Relational and Microsoft.EntityFrameworkCore.SqlServer

All are `version 3.0.0-preview4.19216.3`

3. Then added NuGet package for Microsoft.EntityFrameworkCore.Design

`Version = 3.0.0-preview4.19216.3`

4. Then I issue this command at command prompt

`dotnet ef dbcontext scaffold  "Server=.;Database=MyDb;Integrated Security=true;"   Microsoft.EntityFrameworkCore.SqlServer -o Data -c MyDbContext -t MyTable1 -t MyTable2`

I get this error :

System.InvalidCastException: Unable to cast object of type 'Microsoft.EntityFram
eworkCore.Diagnostics.RelationalLoggingDefinitions' to type 'Microsoft.EntityFra
meworkCore.SqlServer.Diagnostics.Internal.SqlServerLoggingDefinitions'.
   at Microsoft.EntityFrameworkCore.SqlServer.Internal.SqlServerResources.LogFou
ndDefaultSchema(IDiagnosticsLogger logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Internal.SqlServerLoggerExtensions
.DefaultSchemaFound(IDiagnosticsLogger`1 diagnostics, String schemaName)
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerData
baseModelFactory.GetDefaultSchema(DbConnection connection)
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerData
baseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions opt
ions)
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerData
baseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions opt
ions)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffold
er.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions options, S
tring rootNamespace, String modelNamespace, String contextNamespace, String lang
uage, String contextDir, String contextName, ModelReverseEngineerOptions modelOp
tions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldC
ontext(String provider, String connectionString, String outputDir, String output
ContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tabl
es, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames
)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl
(String provider, String connectionString, String outputDir, String outputDbCont
extDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 ta
bleFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatab
aseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c
__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__
DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execu
te(Action action)
**Unable to cast object of type 'Microsoft.EntityFrameworkCore.Diagnostics.Relatio
nalLoggingDefinitions' to type 'Microsoft.EntityFrameworkCore.SqlServer.Diagnost
ics.Internal.SqlServerLoggingDefinitions'.**

What might be the problem ??

Thank you.

**Comment by roji** [comment] 2019-04-26 09:17
Duplicate of #15414

**Comment by ajcvickers** [comment] 2019-04-30 17:05
@roji Thanks for taking care of closing this. Can you also add a `closed-duplicate` tag next time?

**Comment by roji** [comment] 2019-04-30 22:21
Sorry, am still learning the ropes it seems...

**Comment by ajcvickers** [comment] 2019-04-30 22:40
@roji No need to apologize. :-)

**Closed** 2022-10-16 14:19 UTC
Labels: customer-reported
