### ISSUE TITLE
Selecting by property of related entity throws System.InvalidOperationException : Sequence contains more than one element

### ISSUE THREAD

**Issue by MikhailNazarov** [dotnet/efcore#2264] opened 2015-05-24 01:44 UTC
Hello, next line  throws System.InvalidOperationException : Sequence contains more than one element
var items = ctx.Class1.Where(c => c.Class2.Property == "value").ToList();

Repository with minimal sample code:

https://github.com/MikhailNazarov/ef_bug

**Comment by anpete** [comment] 2015-05-26 16:49
Dupe of #325 and related to #1799

**Closed** 2022-10-16 08:57 UTC
