### ISSUE TITLE
QueryFilterBuilder extension suggestion

### ISSUE THREAD

**Issue by Krzysztofz01** [dotnet/efcore#26146] opened 2021-09-22 20:07 UTC
Hello,
the documentation shows that at this point it is not possible to use multiple `HasQueryFilter()` on a given entity. Are there any plans to add such functionality in the future? Some time ago to make my work easier, I created a QueryFilterBuilder. This is a bunch of extension methods such as `AddFilter()` that can be called one after the other to combine conditions and then the `Build()` method can be called, which will combine all the rules into one `HasQueryFilter()`. Is it a functionality that can be useful as an extension or does it not fit into efcore's further development plans?

The usage looks something like this:

```
//Extraction of the rule
var filter = modelBuilder.Entity<Blog>()
   .UseQueryFilterBuilder()
   .AddFilter(b => b.Url.Contains("fish"))
   .AddFilter(b => !b.Deleted)
   .AddFilter(b => b.CommentsCount > 100)
   .BuildQueryFilter().Filter;

modelBuilder.Entity<Blog>().HasQueryFilter(filter);


//Fluent API
modelBuilder.Entity<Blog>()
   .UseQueryFilterBuilder()                     //We indicate that we will build a filter
   .AddFilter(b => b.Url.Contains("fish"))      //Adding the first rule
   .AddFilter(b => !b.Deleted)                  //Adding the second rule...
   .AddFilter(b => b.CommentsCount > 100)       //Another rule...
   .BuildQueryFilter();                         //Applying the ready filter group
```

**Comment by AndriySvyryd** [comment] 2021-09-23 03:38
Mostly a duplicate of https://github.com/dotnet/efcore/issues/10275
The proposed design might be a good external extension.

**Comment by Krzysztofz01** [comment] 2021-09-24 18:29
Here is a link to the repository with the prepared implementation and tests of my proposal.

[EFCore.QueryFilterBuilder](https://github.com/Krzysztofz01/EFCore.QueryFilterBuilder)

**Comment by ajcvickers** [comment] 2021-10-01 18:03
Added a note to #10275.

**Closed** 2022-10-16 20:08 UTC
Labels: closed-duplicate, customer-reported
