### ISSUE TITLE
Filtering over owned entity nested in another owned entity throws InvalidOperationException

### ISSUE THREAD

**Issue by MichalLechowski** [dotnet/efcore#29812] opened 2022-12-09 15:12 UTC
Hello,

I've been trying to make this work, but maybe it's just not possible currently. I am trying to make a model like this to work:

1. Regular entity class has wned entity which has another owned entity. 
2. EF Core 6.0.11
3. .NET 6
4. Provider MS SQL SERVER

Example:

```
class MyEntity {
   public Guid Guid {get;set} //this is PK
   public OwnedEntity OwnedEntity {get;set;}
}

class OwnedEntity  {
   public NestedOwnedEntity NestedOwnedEntity {get;set;}
}

record NestedOwnedEntity {
   public string MyString {get;set;}
}
```

And the configuration builder for MyEntity entity is:

```
            builder.HasKey(b => b.Guid);
            builder.OwnsOne(b => b.OwnedEntity , d=>
            {
                d.OwnsOne(r => r.NestedOwnedEntity , i =>
                {
                    i.Property(p => p.MyString).IsRequired();
                });
            });
```

The problem is whenever I try to query that structure with filtering over inner owned entity, I get:
`No backing field could be found for property and the property does not have a getter.
`

It refers to "MyEntityGuid" it's trying to find, I suppose. It's by convention as far as I understand how owned types work.

example not working query:
`_dbContext.MyEntities.Any( x => x.OwnedEntity.NestedOwnedEntity.MyString == "exampleString");`

Overall the model works and stores all the values in MyEntity table with proper column prefixes, but filtering over nested owned entity is not possible. If I remove that condition from the filter, the query gets back to work properly, of course.

Am I missing something here or it's not possible for owned entity?

Thanks for any suggestions.

**Comment by ajcvickers** [comment] 2022-12-12 11:30
Duplicate of #29442.

@MichalLechowski Read through #29442 and linked issues for an understanding of what is happening here.

**Comment by roji** [comment] 2022-12-12 12:32
Duplicate of #29442

**Closed** 2022-12-14 20:28 UTC
Labels: customer-reported
