### ISSUE TITLE
WHERE Clause is not concatenating int with string properly, only on EF 3

### ISSUE THREAD

**Issue by jsgoupil** [dotnet/efcore#20764] opened 2020-04-27 21:26 UTC
When doing a WHERE clause with a concatenation of a integer + string, the output always return null.

This works perfectly with 2.2.6.
With 3.1.3, my variables `c` and `d` are NULL.

### To Reproduce

``` C#
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace ConsoleApp5
{
    public class MyTable
    {
        public int Id { get; set; }
        public int? Code { get; set; }
        public int CodeInt { get; set; }
        public string Name { get; set; }
    }

    public class MyContext : DbContext
    {
        public MyContext(
            DbContextOptions<MyContext> options
        )
            : base(options)
        {
        }

        public DbSet<MyTable> MyTables { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var connection = new SqliteConnection("DataSource=:memory:");
            connection.Open();

            var options = new DbContextOptionsBuilder<MyContext>()
                  .UseSqlite(connection)
                  .Options;

            using var dbContext = new MyContext(options);
            dbContext.Database.EnsureCreated();
            dbContext.MyTables.Add(new MyTable
            {
                Code = 123,
                CodeInt = 456,
                Name = "ABC"
            });
            dbContext.SaveChanges();

            var a = dbContext.MyTables.Where(m => m.Code == 123).FirstOrDefault();
            var b = dbContext.MyTables.Where(m => m.Name == "ABC").FirstOrDefault();
            var c = dbContext.MyTables.Where(m => m.Code + " " + m.Name == "123 ABC").FirstOrDefault();
            var d = dbContext.MyTables.Where(m => m.CodeInt + " " + m.Name == "456 ABC").FirstOrDefault();

            Console.WriteLine("EF Core 3.1.3");
            Console.Write("A: ");
            Console.WriteLine(a);
            Console.Write("B: ");
            Console.WriteLine(b);
            Console.Write("C: ");
            Console.WriteLine(c); // Is null with 3.1.3
            Console.Write("D: ");
            Console.WriteLine(d); // Is null with 3.1.3
        }
    }
}
```

Outputs
```
EF Core 3.1.3
A: ConsoleApp5.MyTable
B: ConsoleApp5.MyTable
C:
D:
```

```
EF Core 2.2.6
A: ConsoleApp6.MyTable
B: ConsoleApp6.MyTable
C: ConsoleApp6.MyTable
D: ConsoleApp6.MyTable
```

### Additional context

Microsoft.Data.Sqlite version: 3.1.3
Target framework: .NET Core 3.1
Operating system: Windows

**Comment by ajcvickers** [comment] 2020-05-01 17:25
@maumar to find dupe.

**Comment by maumar** [comment] 2020-05-04 23:45
dupe of #18132

**Comment by kevinchalet** [comment] 2020-05-05 00:12
@ajcvickers @maumar it's worth noting that unlike the other bug report, this case didn't cause any exception, making it particularly dangerous from a security perspective (an exception as in the other case is always better than ignoring some conditions).

Is it something that would deserve a hotfix for 3.1?

**Comment by ajcvickers** [comment] 2020-05-05 14:53
@maumar Do we know why the duplicate was throwing, while this case is not?

**Comment by smitpatel** [comment] 2020-05-05 14:58
#19990

**Comment by kevinchalet** [comment] 2020-05-11 14:36
@maumar @smitpatel I read the two tickets you mentioned and it's not clear to me whether there's a way to work around this bug. Could you please shed some light on this? 😅

**Comment by kevinchalet** [comment] 2020-06-11 17:02
@smitpatel @ajcvickers thanks for the workaround, but I was expecting a more localized approach (e.g by tweaking an internal query class). This works, but it is very unpractical as it will require modifying tons of queries. Is there really no other option? 😭

**Comment by qszhuan** [comment] 2021-03-24 23:21
@kevinchalet 
I got another workaround by doing `Where(m => "" + m.CodeInt + " " + m.Name == "456 ABC")`.

The issue is fixed in EFCore 5, but seems I have to upgrade .net core 3 to .net 5 as well. That's a lot work for me at the moment.

**Closed** 2022-10-16 18:22 UTC
Labels: customer-reported
