### ISSUE TITLE
EF Core Doc's Omit System Exceptions

### ISSUE THREAD

**Issue by don4of4** [dotnet/efcore#17567] opened 2019-05-09 19:20 UTC
The EF Core documentation is inconsistent with the EF Framework 6.2 documentation in that it omits details about exceptions that can be thrown by a call to the method. 

Specifically, it excludes errors that stem from serious programming faults, like NotSupportedException, InvalidOperationException, and ObjectDisposedException.  Can EF Core emit any of these events?  If so, I would propose the documentation be updated to reflect those additional exception cases since this particular call (as well as it's non-async partner) are likely to receive a lot of developer attention.

EF 6 Docs: https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.dbcontext.savechangesasync?view=entity-framework-6.2.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aece550f-d934-0dae-c3ac-0d9b3660bd1a
* Version Independent ID: aebedd48-a65c-c92e-ab4f-f7b4fe467e03
* Content: [DbContext.SaveChangesAsync Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.savechangesasync?view=efcore-2.1#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-02 17:07
Duplicate of #17564

**Closed** 2022-10-16 14:39 UTC
