### ISSUE TITLE
ArgumentException when assigning readonly list to new object in query

### ISSUE THREAD

**Issue by CobeLapierre** [dotnet/efcore#12558] opened 2018-07-05 09:52 UTC
I'm trying to do the following:
Selecting a readonly list in a query and assign to a new object results in an argument exception.

I have an object which has a property of type IReadOnlyList.

```
class T1 {
...
private readonly List<T2> _t2s = new List<T2>();
        public virtual IReadOnlyList<T2> T2s => _t2s.AsReadOnly();
}

class T2 { ... }
```

This property is working by using the following fluent api mapping:

`builder.Metadata.FindNavigation(nameof(T1.T2)).SetPropertyAccessMode(PropertyAccessMode.Field);`

Repository:

```
var result = context.T1s.AsNoTracking().Select(x => 
                new {
                    ListOfT2 = x.T2s
                }
            ).ToList();
```

(of course my queries are a little more complex then this)

Exception:

`GenericArguments[2], 'System.Collections.Generic.IReadOnlyList`1[Domain.T2]', on 'TCollection CorrelateSubquery[TInner,TOut,TCollection](Int32, Microsoft.EntityFrameworkCore.Metadata.INavigation, System.Func`2[Microsoft.EntityFrameworkCore.Metadata.INavigation,TCollection], Microsoft.EntityFrameworkCore.Query.Internal.MaterializedAnonymousObject ByRef, Boolean, System.Func`1[System.Collections.Generic.IEnumerable`1[System.Tuple`3[TInner,Microsoft.EntityFrameworkCore.Query.Internal.MaterializedAnonymousObject,Microsoft.EntityFrameworkCore.Query.Internal.MaterializedAnonymousObject]]], System.Func`3[Microsoft.EntityFrameworkCore.Query.Internal.MaterializedAnonymousObject,Microsoft.EntityFrameworkCore.Query.Internal.MaterializedAnonymousObject,System.Boolean])' violates the constraint of type 'TCollection'.`

Sql server 2017
EF core 2.1

I Also tried to use an explicit object "class ResultDb" (instead of an anonymous type) where i defined "ListOfT2".
Tried to use the following types with ListOfT2:
IEnumerable<T2> ListOfT2 { get; set; }
IList<T2> ListOfT2 { get; set; }
IReadOnlyList<T2> ListOfT2 { get; set; }

All result in the same error.

Any ideas?
Thanks in advance.

**Comment by ajcvickers** [comment] 2018-08-05 19:25
DUplicate of #12881

**Closed** 2022-10-16 13:17 UTC
Labels: type-bug, closed-duplicate, customer-reported
