### ISSUE TITLE
InvalidOperationException saving entity

### ISSUE THREAD

**Issue by lasrol** [dotnet/efcore#3619] opened 2015-10-31 15:02 UTC
I am currently using Beta 8
#### User model

```
public class User 
{
     public string Id { get; set; }
     public string Email { get; set; }
}
```
#### Saving the entity

```
    _db.Users.Add(user);
    await _db.SaveChangesAsync();
```

When i try to save the entity i get the following exception, and i am not sure why and what this means. The entity is created in the DB, so it seems to be working, but EF throws this exception. Not sure if this is a bug, or just me doing something wrong. 

> An unhandled exception occurred while processing the request.  InvalidOperationException: The >property 'Id' on entity type 'User' has a temporary value while attempting to change the entity's >state to 'Unchanged'. Either set a permanent value explicitly or ensure that the database is >configured to generate values for this property.

**Comment by rowanmiller** [comment] 2015-11-06 18:21
Hey,

Sounds like you are probably trying to save a User without assigning a primary key value. In the following code the first SaveChanges succeeds, but the second one throws the exception you are seeing.

```c#
using Microsoft.Data.Entity;

namespace ConsoleApplication10
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var db  = new UserContext())
            {
                db.Database.EnsureCreated();

                db.Users.Add(new User { Id = "user1", Email = "user1@sample.com" });
                db.SaveChanges();

                db.Users.Add(new User { Email = "user2@sample.com" });
                db.SaveChanges();
            }
        }
    }

    public class User
    {
        public string Id { get; set; }
        public string Email { get; set; }
    }

    public class UserContext : DbContext
    {
        public DbSet<User> Users { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Demo;Trusted_Connection=True;");
        }
    }
}
```

In RC1 we have made some changes in this area to try and make things a little clearer. Instead of that exception during SaveChanges you now get this when you try to add the entity.

> System.InvalidOperationException: The instance of entity type 'ConsoleApplication10.User' cannot be tracked because it has an invalid (e.g. null or CLR default) primary key. Either set the key explicitly or consider using an IValueGenerator to generate unique key values.

**Comment by lasrol** [comment] 2015-11-06 18:26
I was under the impression that EF generates the Guid automaticly if no Id has been specified? Or shoulde i just create the guid myself?

What confuses me is that EF is creating the user, and generating the key for me but still throws me exception. From my point of view no exception has happend since it has created the user as expected.

**Comment by rowanmiller** [comment] 2015-11-06 18:31
Ok, I see the confusion. EF only generates "real" primary key values for integer and GUID keys. The GUID EF was assigning to your string key was a temporary value just to give it a unique way to keep a track of the entity internally. In RC1 we have stopped doing this and we only create temporary values where we expect the database to later replace it with a generated value during save.

**Comment by rowanmiller** [comment] 2015-11-06 18:32
So if you want EF to generate a GUID for you then just change the type of the property to a GUID and EF will happily take care of it by default.

**Comment by lasrol** [comment] 2015-11-06 19:20
Okay, i understand now. Its a was bit counter intuitive that it saved the entity :) Thanks for the help.

**Comment by xoro91** [comment] 2017-09-06 20:11
Why is TEntity primary key Id is -9223372036854774806 for int64 or -2147482647 for int32 after DbContext.DbSet.Add(TEntity);

**Comment by smitpatel** [comment] 2017-09-06 23:12
@xoro91 - Those are temporary values till actual value is generated from database during SaveChanges. To avoid clash with existing values in database, we use `int.MinValue + 1000` for int columns & `long.MinValue + 1000` for long columns. Those values would be updated once you call savechanges.

**Comment by ppumkin** [comment] 2017-12-22 11:48
I am not sure why but your temporary value sticks around after saving.. then I get this message.

I use Save or await SaveAsync using Tasks.WaitAll() for many tasks working on db context. And sometimes this occurs, when Complete gets called and the ID state is -2147482646 AFTER the await SaveChanges was completed?

But I am also having issues with threading "A second operation started on this context before a previous operation completed." and probably that is the cause of the intial issue.. 

I don't know how to solve any of them

**Comment by ajcvickers** [comment] 2017-12-22 18:11
@ppumkin DbContext is not thread-safe. That is, the same instance cannot be used by multiple threads concurrently. Tasks.WaitAll is causing that to happen, so it can't be used for this kind of thing.

**Closed** 2022-10-16 09:14 UTC
