### ISSUE TITLE
how can we filter with '@' in EF core full text serach contains

### ISSUE THREAD

**Issue by alenjosein** [dotnet/efcore#18184] opened 2019-10-02 11:09 UTC
Hi

If the filter string is '@', how can we filter the data using ef core full text serach.contains?

eg:-
query = query.Where(x => EF.Functions.Contains(x.EventInfo.Name, "\"*{filter}*\""));

here the filter is '@'. How it will work. Now I am getting empty list.

**Comment by bricelam** [comment] 2019-10-02 18:53
Full-text search is about words and phrases. I don't think it'll work with punctuation and symbols... Should you be using LIKE instead?

**Comment by alenjosein** [comment] 2019-10-03 06:37
If I use like, I cannot use index. It will take long time to filter.

**Comment by ajcvickers** [comment] 2019-10-07 20:27
@alenjosein What SQL are you expecting here?

**Comment by ajcvickers** [comment] 2019-10-14 16:36
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:47 UTC
Labels: closed-no-further-action, customer-reported
