### ISSUE TITLE
"Contains" condition is ignored

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#6355] opened 2016-08-18 13:39 UTC
Here's my code snippet:

```
var answers = answerQuery.ToList();
var questions = commonDb.AssessmentQuestions
                        .Include(q => q.Assessment)
                        .Where(q =>
                            answers.Select(a => a.AssessmentQuestionId)
                                   .Contains(q.AssessmentQuestionId))
                        .ToDictionary(q => q.AssessmentQuestionId);
```

This generates the following Sql:

```
SELECT [q].[AssessmentQuestionId], [q].[AnswerBlob], [q].[AssessmentId], [q].[CreateDate], [q].[DeletedDate], [q].[IsDeleted], [q].[QuestionNumber], [q].[QuestionText], [a].[AssessmentId], [a].[AssessmentStatusId], [a].[AssessmentTypeId], [a].[BookId], [a].[CanPageBack], [a].[CommonCoreSubstandardId], [a].[CreateDate], [a].[EBookFormatTypeId], [a].[EndLocation], [a].[LexileLevel], [a].[Metadata], [a].[Name], [a].[PageNumber], [a].[ReadingTagId], [a].[StartLocation]
FROM [dbo].[AssessmentQuestion] AS [q]
INNER JOIN [dbo].[Assessment] AS [a] ON [q].[AssessmentId] = [a].[AssessmentId]
```

What's missing?  The "WHERE" clause!
But... If I get the collection into a list first:

```
var answers = answerQuery.ToList();
var answerQuestionIds = answers.Select(a => a.AssessmentQuestionId).ToList();
var questions = commonDb.AssessmentQuestions
                        .Include(q => q.Assessment)
                        .Where(q =>
                            answerQuestionIds.Contains(q.AssessmentQuestionId))
                        .ToDictionary(q => q.AssessmentQuestionId);
```

Then the correct Sql is generated:

```
SELECT [q].[AssessmentQuestionId], [q].[AnswerBlob], [q].[AssessmentId], [q].[CreateDate], [q].[DeletedDate], [q].[IsDeleted], [q].[QuestionNumber], [q].[QuestionText], [a].[AssessmentId], [a].[AssessmentStatusId], [a].[AssessmentTypeId], [a].[BookId], [a].[CanPageBack], [a].[CommonCoreSubstandardId], [a].[CreateDate], [a].[EBookFormatTypeId], [a].[EndLocation], [a].[LexileLevel], [a].[Metadata], [a].[Name], [a].[PageNumber], [a].[ReadingTagId], [a].[StartLocation]
FROM [dbo].[AssessmentQuestion] AS [q]
INNER JOIN [dbo].[Assessment] AS [a] ON [q].[AssessmentId] = [a].[AssessmentId]
WHERE [q].[AssessmentQuestionId] IN ('df9a5a8a-495e-4c1d-fb97-08d3c76c7c17', 'd6788e37-33fe-493b-fb99-08d3c76c7c17')
```

**Comment by gdoron** [comment] 2016-08-18 16:32
Is it just with Contains?
Did you try other stuff, like Any

	 .Where(q => answers.Any(a => a.AssessmentQuestionId == q.AssessmentQuestionId))
I guess it would be the same since EF doesn't really know "expression-wise" what answers is.

**Comment by shaulbehr** [comment] 2016-08-18 18:09
No, didn't try that.  As far as I was aware, previous versions of EF didn't support .Any() on hybrid in-memory/Sql query; the only thing you could use was .Contains().

**Comment by smitpatel** [comment] 2016-08-18 18:15
Both of above generated SQL are expected behavior.
The "Contains" condition is not ignored. Since the list which should contain the data is coming from another query, EF is not able to translate it to SQL hence it will produce SQL without WHERE clause on "Contains" and do the filtering on client. The result would be correct.
In the second query, the list of data is a constant list (and not a linq query) which EF can translate to SQL by writing the values in sql hence it generates where clause and does filtering on server.

**Comment by shaulbehr** [comment] 2016-08-18 18:19
@smitpatel I believe previous versions of EF *did* support the first syntax.  The first "Contains" is applied to an Enumerable<Guid> - so why not enumerate it the same way as you do with the List<Guid>?

**Comment by smitpatel** [comment] 2016-08-18 18:37
@shaulbehr - Can you share your model classes so I can try out different queries and SQL generated?

**Comment by shaulbehr** [comment] 2016-08-18 18:57
@smitpatel sure - but it's quite a big project.  What's the minimum you need?

**Comment by smitpatel** [comment] 2016-08-18 18:59
`AssessmentQuestion`, `Answer` and `Assessment` classes. The classes which are used in above queries and relevant properties.

**Comment by shaulbehr** [comment] 2016-08-18 19:09
[Models.zip](https://github.com/aspnet/EntityFramework/files/425681/Models.zip)

**Comment by smitpatel** [comment] 2016-08-18 21:03
@shaulbehr - Thanks for the info. I have tested out different queries with the given models.
`var answers` is a constant list of answers. `Answer` is non-primitive type. You cannot represent it in SQL, hence query1 produces above SQL in which where clause is evaluated on client. In EF6, it threw exception `{"Unable to create a constant value of type 'OldModelApp.Answer'. Only primitive types or enumeration types are supported in this context."} `
In the query2, the constant list is of `Guid` type which can be written in SQL so both the versions of ef generates same query for it.
There is nothing different happening because of `Enumerable` or `List`. You cannot represent type of `Answer` in SQL.
The way to translate it to SQL would be the data is coming from server directly as a subquery.
```c#
var answers = db.Answers;
var questions = db.AssessmentQuestions
        .Include(q => q.Assessment)
        .Where(q =>
            answers.Select(a => a.AssessmentQuestionId)
                    .Contains(q.AssessmentQuestionId))
        .ToList();
```
In above query `answers` is not a list, it is rather QuerySourceReferenceExpression. (or Queryable)
The generated SQL
```T-SQL
SELECT [q].[AssessmentQuestionId], [q].[AssessmentId], [a0].[AssessmentId]
FROM [AssessmentQuestions] AS [q]
INNER JOIN [Assessments] AS [a0] ON [q].[AssessmentId] = [a0].[AssessmentId]
WHERE [q].[AssessmentQuestionId] IN (
    SELECT [a].[AssessmentQuestionId]
    FROM [Answers] AS [a]
)
```

**Comment by gdoron** [comment] 2016-08-18 21:41
When I shifted from NH to EF I realized EF can't translate the LINQ's Enumerable into literals.
But I'm almost sure NHibernate does do it (it was maybe 5 years ago).

Why aren't you checking if the parameter is an IEnumerable and treat it as a value rather than an expression?

**Comment by divega** [comment] 2016-08-19 18:28
**Triage:** we should consider funcletizing `answers.Select(a => a.AssessmentQuestionId)` in the original query. Maybe the reson we are not doing now is that we err on the side of preserving streaming and so we end up evaluating most of the query on the client.

cc @anpete

**Comment by gdoron** [comment] 2016-08-20 17:39
@divega what's the semantics of adding the issue to backlog and then closing it?
Do you track it somewhere else?

**Comment by divega** [comment] 2016-08-20 18:13
@gdoron I think it was just a mistake on my part. Thanks for asking.

**Comment by gdoron** [comment] 2016-08-20 18:44
😎 BTW, You might want to edit the title to something more informative and findable.

**Comment by amh1979** [comment] 2016-10-18 17:29
I've had the same problem.
See the screenshot!
![image](https://cloud.githubusercontent.com/assets/5894637/19488837/4e8186d6-959b-11e6-9195-08466f3f02e8.png)

There any idea?

**Comment by amh1979** [comment] 2016-10-18 17:42
OMG!
when I changed the StatusId as not Nullable, then it is correct...

**Comment by amh1979** [comment] 2016-10-21 15:54
https://github.com/aspnet/EntityFramework/issues/6483

**Comment by smitpatel** [comment] 2019-11-13 23:09
Duplicate of #13524

**Closed** 2022-10-16 09:55 UTC
