### ISSUE TITLE
Null error when preparing for pagination

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#20106] opened 2020-02-28 22:17 UTC
The following runtime error occurs when certain properties are null.

> SqlNullValueException: Data is Null. This method or property cannot be called on Null values.

No properties in the `source` are required. The `source` is populated from an EF Core query without any issues, and is sent to this function to prepare for paging. If I comment out a specific property in my model, the error goes away. The property is an `int`.

Here is the code where the error is occurring, the particular line has a comment above it.

```C#
public static async Task<PaginatedList<T>> CreateAsync(
	IQueryable<T> source, int pageIndex, int pageSize)
{
	var count = await source.CountAsync();

	// error occurs on next line
	var items = await source
		.Skip((pageIndex - 1) * pageSize)
		.Take(pageSize).ToListAsync();

	return new PaginatedList<T>(items, count, pageIndex, pageSize);
}
```

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment] 2020-03-02 17:31
@mrlife Please attach as small, runnable project or post a complete, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-03-09 16:14
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by mrlife** [comment] 2020-03-27 16:40
@ajcvickers Sorry, finally getting back to this. Can we still address with this issue?

More information: the model is hitting a view (by calling `ToView()` for the `DbSet` in `OnModelCreating()`. If I remove the fields from the model and `OnModelCreating()` for this `DbSet` that occasionally have a null value, the execution of the query by calling `ToListAsync()` runs fine.

I don't have nullable reference types enabled, so I'm not sure why it would find an exception when an optional model property would have a null value (since all model properties are optional by default with nullable reference types disabled).

**Closed** 2022-10-16 18:13 UTC
Labels: closed-could-not-reproduce, customer-reported
