### ISSUE TITLE
ef core migration generator is confused in regards to OwnsMany() ReferentialAction

### ISSUE THREAD

**Issue by mhDuke** [dotnet/efcore#18623] opened 2019-10-28 19:55 UTC
without altering a bit, no matter how many `add-migration` commands i execute the same migration class script is generated, which is trying to change the relation `onDelete` `ReferentialAction` to `Cascade` instead of `Restrict`.
When inspecting the sql server database it's set to `ON DELETE CASCADE`, which is the correct referential action behavior.

```
class Vehicle
{
    public int Id {get; set;}
    public string Name { get; set; }
    public IEnumerable<VehicleFeature> Features { get; set; }
}

class VehicleFeature
{
    public int Id {get; set;} 
    public string Name {get; set;}
}

class VehicleConfiguration : IEntityTypeConfiguration<Vehicle>
{
    public void Configure(EntityTypeBuilder<Vehicle> b)
    {
        b.OwnsMany<VehicleFeature>(e => e.Features, a =>
            {
                a.WithOwner();
                a.Property(e => e.Name).HasMaxLength(50);
            });
    }
}

public partial class dummyMigration : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
                name: "FK_VehicleFeature_Vehicles_VehicleId",
                table: "VehicleFeature");
        migrationBuilder.AddForeignKey(
                name: "FK_VehicleFeature_Vehicles_VehicleId",
                table: "VehicleFeature",
                column: "VehicleId",
                principalTable: "Vehicles",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
         migrationBuilder.DropForeignKey(
                name: "FK_VehicleFeature_Vehicles_VehicleId",
                table: "VehicleFeature");
         migrationBuilder.AddForeignKey(
                name: "FK_VehicleFeature_Vehicles_VehicleId",
                table: "VehicleFeature",
                column: "VehicleId",
                principalTable: "Vehicles",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
    }
}
```

EF Core version: 3
Database provider: Microsoft.EntityFrameworkCore.SqlServer v3
Target framework: netstandard2.1
IDE: Visual Studio 2019 16.3.6

**Comment by AndriySvyryd** [comment] 2019-10-28 20:35
Duplicate of #18045

**Closed** 2022-10-16 14:52 UTC
Labels: customer-reported
