### ISSUE TITLE
EF generates additional mapping to the same sql column with '1' postfix in column name

### ISSUE THREAD

**Issue by osemyonov** [dotnet/efcore#29503] opened 2022-11-08 17:21 UTC
### Description of the issue

When occasionally in EF entity class one SQL column is mapped twice to entity properties, EF adds '1' postfix to column mapping name and in runtime mode it fires incorrect error message about 'invalid column name'
 
### Include your code
EF entity with mapping twice to SQL table column sample:

```C#
    [Table("Facilities")]
    public partial class Facility
    {
        [Key]
        public int Id { get; set; }

        [Column("MaintenanceModule")]
        public bool IsMaintenanceModuleActive { get; set; }

        public bool MaintenanceModule { get; set; }
```

In DbContext requests to Facility entity

```C#
    var facility = _dbContext.Facilities.Find(facilityId);
```

 EF fires incorrect message error in runtime mode:

"title":"An unexpected error occurred!","status":500,"detail":"Microsoft.Data.SqlClient.SqlException (0x80131904): 
Invalid column name **MaintenanceModule1**"

### Include stack traces

The  exception message.

```
"title":"An unexpected error occurred!","status":500,"detail":"Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name \u0027MaintenanceModule1\u0027.\n"
```

### Expected behavior  

In build-time mode EF generator should provide relevant error message about the same SQL table Column is mapped twice to entity class.

### Include provider and version information

EF Core version: 6.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system:
IDE: Visual Studio 2022 17.4

**Comment by ajcvickers** [comment] 2022-11-08 17:30
Duplicate of #27747.  Make sure to vote (👍) for #27747.

**Closed** 2022-11-15 15:16 UTC
Labels: closed-duplicate, customer-reported
