### ISSUE TITLE
Trimming trailing spaces on char type

### ISSUE THREAD

**Issue by amcorch** [dotnet/efcore#10836] opened 2018-01-31 14:55 UTC
Is there any sort of hook or interception where a char column can be trimmed so that the trailing spaces are removed?

I'm looking for a solution similar to [this](https://romiller.com/2014/10/20/ef6-1workaround-trailing-blanks-issue-in-string-joins/) which is available in EF 6.1

Thanks

**Comment by ajcvickers** [comment] 2018-01-31 16:55
@amcorch In EF Core 2.1 a value converter can do this. Something like:
```C#
modelBuilder
    .Entity<Foo>()
    .Property(e => e.Bar)
    .HasConversion(v => v.Trim(), v => v.Trim());
```
This will remove any whitespace when coming out of or going into the database.

In EF Core 2.0 I don't think that there is an easy way to trim when data is coming from the database. You could override SaveChanges to trim going into the database.

**Comment by ajcvickers** [comment] 2018-01-31 16:55
Closing as duplicate of #242

**Closed** 2022-10-16 12:07 UTC
Labels: closed-duplicate
