### ISSUE TITLE
EF does not log commands

### ISSUE THREAD

**Issue by majidmadadi** [dotnet/efcore#15755] opened 2019-05-20 04:01 UTC
I'm using EF core v3.0 preview and have the following context:
```
public class MySampleDbContext : DbContext  
{  
    private readonly ILoggerFactory _loggerFactory;  
  
    public MySampleDbContext(DbContextOptions<BloggingContext> options, ILoggerFactory loggerFactory)  
        : base(options)  
    {  
        this.loggerFactory = loggerFactory;  
    }  
      
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)  
    {  
        optionsBuilder.UseLoggerFactory(this.loggerFactory);  
    }  
} 
```
but ef does not log commands sent to the db.

**Comment by ajcvickers** [comment] 2019-05-20 15:02
@majidmadadi You may be running into [this breaking change](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#query-execution-is-logged-at-debug-level). (We decided in a recent API review that we are going to revert this break, but the work hasn't been done yet.)

If this isn't it, then please file a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-05-27 19:34
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:21 UTC
Labels: closed-could-not-reproduce, customer-reported
