### ISSUE TITLE
Condition not being evaluated in Where?!

### ISSUE THREAD

**Issue by mdmoura** [dotnet/efcore#5609] opened 2016-06-01 16:13 UTC
Maybe I am missing something really obvious or this is a bug?

```
    IQueryable<Project> projects = _context.Projects.AsQueryable();
    Boolean? condition = null;
    var a = projects.Where(x => true);
    var b = projects.Where(x => condition == null);
    Boolean itemCountIsTheSame = await a.CountAsync() == await b.CountAsync();
```

Should not itemCountIsTheSame be true? I get 8 projects on "a" and 0 projects on "b"?!

To give some context on my project what I have is something like:

```
    var result = projects.Where(x => x.IsActive == query.IsActive || query.IsActive == null);
```

So I filter by Active (true or false) when query.IsActive is not null ...

**Comment by mdmoura** [comment] 2016-06-01 16:37
I did got the SQL for the following 2 queries:

        var c = await projects.Where(x => true).Select(x => x.Id).ToListAsync();

        var b = await projects.Where(x => condition == null).Select(x => x.Id).ToListAsync();

Which was:

    SELECT [x].[Id]
    FROM [Projects] AS [x]
    WHERE 1 = 1

    SELECT [x].[Id]
    FROM [Projects] AS [x]
    WHERE @__condition_0 = NULL

What am I missing?

**Comment by maumar** [comment] 2016-06-01 16:41
This is a duplicate of https://github.com/aspnet/EntityFramework/issues/5499. I got the fix ready so this will be fixed for RTM

**Comment by mdmoura** [comment] 2016-06-01 16:42
@maumar Thanks for pointing out ...

**Closed** 2022-10-16 09:43 UTC
