### ISSUE TITLE
Reverse Engineering DataAnnotations parameters don't give StringLength and others

### ISSUE THREAD

**Issue by MichelLaplane** [dotnet/efcore#5870] opened 2016-06-27 09:38 UTC
### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.
### The issue

Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```
### Further technical details

EF Core version: (found in project.json or packages.config)
Operating system: 
Visual Studio version: (e.g. VS 2013 or n/a)

Other details about my project setup:

**Comment by MichelLaplane** [comment] 2016-06-27 09:47
EntityFrameworkCore.Tools : "1.0.0-preview1-final"
EntityFrameworkCore.SqlServer : "1.0.0-rc2-final"
EntityFrameworkCore.SqlServer.Design : "1.0.0-rc2-final"

Using the Scaffold-DbContext command with -DataAnnotations parameters gives only the [Key] data attributes but not StringLength.
What are the <SwitchParameter> value of the -DataAnnotations parameters are there some values that are to be used for the StringLength

**Comment by smitpatel** [comment] 2016-06-27 16:33
Possible duplicate of #5289 
Can you try running with latest release?

**Comment by rowanmiller** [comment] 2016-06-27 18:16
Closing as dupe

**Comment by MichelLaplane** [comment] 2016-06-29 08:24
Sorry for not being explicit.
Yes, with the 1.0.0-preview1-final, the string length are generated in the OnModelCreating
....
            modelBuilder.Entity<TA_ACCESSORY_ACC>(entity =>
            {
                entity.Property(e => e.GUID_ACC).ValueGeneratedNever();
                entity.Property(e => e.NAME_ACC).HasColumnType("varchar(25)");
             });

But not in the Model.Only the [Key] is generated
    public partial class TA_ACCESSORY_ACC
    {
        [Key]
        public Guid GUID_ACC { get; set; }
        public string NAME_ACC { get; set; }
    }

Could be interesting to have this generated :

    public partial class TA_ACCESSORY_ACC
    {
        [Key]
        public Guid GUID_ACC { get; set; }
        [MaxLength(25)]
        public string NAME_ACC { get; set; }
    }

**Comment by rowanmiller** [comment] 2016-06-29 16:36
@MichelLaplane that is what should be generated when you use 1.0.0-preview2-final. Can you try upgrading and let us know if that is not what you see.

**Closed** 2022-10-16 09:47 UTC
