### ISSUE TITLE
DefaultIfEmpty() unsupported in subquery when main query has group by?

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#28119] opened 2022-05-27 21:28 UTC
I have the following LINQ (to SQL Server) query:

```C#
    var railcarsByProduct = await (from r in DbContext.Railcars
                                   let p = DbContext.ProductAliases
                                       .Where(pa => pa.Product.Company.CompanyCode == companyCode && pa.Alias == r.Product)
                                       .Select(pa => pa.Product.Name)
                                       .FirstOrDefault()
                                   where r.Facility.Company.CompanyCode == companyCode && r.Departure == null
                                   group r by p into productGroup
                                   select new { Product = productGroup.Key, Count = productGroup.Count() }
                                  ).ToListAsync();
```

This is working fine. However, there is the possibility that the `ProductAliases` subquery will return null. In that case, I want to default to `r.Product`.

I tried adding `DefaultIfEmpty()` to the subquery.

```C#
    var railcarsByProduct = await (from r in DbContext.Railcars
                                   let p = DbContext.ProductAliases
                                       .Where(pa => pa.Product.Company.CompanyCode == companyCode && pa.Alias == r.Product)
                                       .Select(pa => pa.Product.Name)
                                       .DefaultIfEmpty(r.Product)
                                       .FirstOrDefault()
                                   where r.Facility.Company.CompanyCode == companyCode && r.Departure == null
                                   group r by p into productGroup
                                   select new { Product = productGroup.Key, Count = productGroup.Count() }
                                  ).ToListAsync();
```
But this gives an error.

> 'The LINQ expression 'DbSet<ProductAlias>()
     .Where(pa => pa.Product.Company.CompanyCode == __companyCode_0 && pa.Alias == r.Outer.Outer.Product)
     .Select(pa => pa.Product.Name)
     .DefaultIfEmpty(r.Outer.Outer.Product)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'.

Next, I tried handling the null case within the `group by` clause.

```C#
    var railcarsByProduct = await (from r in DbContext.Railcars
                                   let p = DbContext.ProductAliases
                                       .Where(pa => pa.Product.Company.CompanyCode == companyCode && pa.Alias == r.Product)
                                       .Select(pa => pa.Product.Name)
                                       .FirstOrDefault()
                                   where r.Facility.Company.CompanyCode == companyCode && r.Departure == null
                                   group r by p ?? r.Product into productGroup
                                   select new { Product = productGroup.Key, Count = productGroup.Count() }
                                  ).ToListAsync();
```

But this also gives the exact same error.

Next I tried the null coalesce operator against the result of the subquery.

```C#
    var railcarsByProduct = await (from r in DbContext.Railcars
                                   let p = DbContext.ProductAliases
                                       .Where(pa => pa.Product.Company.CompanyCode == companyCode && pa.Alias == r.Product)
                                       .Select(pa => pa.Product.Name)
                                       .FirstOrDefault() ?? r.Product
                                   where r.Facility.Company.CompanyCode == companyCode && r.Departure == null
                                   group r by p into productGroup
                                   select new { Product = productGroup.Key, Count = productGroup.Count() }
                                  ).ToListAsync();
```

Again, the exact same error.

I understand could just bring down all the rows and then group them in C# code but I'd prefer not to do that. As best I can tell, what I need is just not supported. If that's the case, is it possible to add support for this?

### Provider and version information

EF Core version: 6.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.2.2

**Comment by ajcvickers** [comment] 2022-05-31 19:56
Duplicate of #17783.

**Comment by smitpatel** [comment] 2022-05-31 23:16
Note: The attempted work-arounds with "??" will _never_ generate the exact same error.

**Comment by SoftCircuits** [comment] 2022-05-31 23:48
> Note: The attempted work-arounds with "??" will _never_ generate the exact same error.

Well, it looked the same. Maybe something was different. The error doesn't have a lot of details anyway.

**Closed** 2022-10-16 20:35 UTC
Labels: customer-reported
