### ISSUE TITLE
Unable to execute "dotnet ef migrations add init"

### ISSUE THREAD

**Issue by doggy8088** [dotnet/efcore#31527] opened 2023-08-21 15:49 UTC
Here are the reproduce steps:

1. Clone my code

    ```sh
    git clone https://github.com/doggy8088/EFCore7UnableDoMigration.git
    cd EFCore7UnableDoMigration
    ```

2. Do the migration

    ```sh
    dotnet ef migrations add init
    ```

    Errors below:

    > Unable to create an object of type 'ContosoUniversityContext'. For the different patterns supported at design time, see <https://go.microsoft.com/fwlink/?linkid=851728>

Here is what I do:

1. I added a `Data\ContosoUniversityContextPartial.cs` partial class which are defined a constructor with no parameters and a `OnConfiguring` method.

    I reference from this doc: [Design-time DbContext Creation](https://learn.microsoft.com/en-us/ef/core/cli/dbcontext-creation?WT.mc_id=DT-MVP-4015686&tabs=dotnet-core-cli#using-a-constructor-with-no-parameters)

2. I expected my DbContext class should able to recognized by `dotnet-ef` tool.

### Include provider and version information

EF Core version: `7.0.10`
Database provider: `Microsoft.EntityFrameworkCore.SqlServer`
Target framework: `.NET 7.0`
Operating system: `Windows 10`
IDE: `N/A`

**Comment by vernou** [comment] 2023-08-22 13:17
I don't think `partial` is to blame.

This works :
````csharp
public class DemoContext : DbContext
{
    public DemoContext() { }

    public DemoContext(DbContextOptions options) : base(options)
    { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.UseSqlServer();
    }
}
````

And this don't work with the same error :
````csharp
public class DemoContext : DbContext
{
    public DemoContext(DbContextOptions options) : base(options)
    { }

    public DemoContext() { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.UseSqlServer();
    }
}
````

The difference is default constructor's position. When the default constructor isn't first, this produce the error. 

Partial combine each part of the class to create the real class. The element's order isn't defined and the default constructor isn't necessarily first.

**Comment by doggy8088** [comment] 2023-08-22 17:36
You are right. After I renamed my partial class filename, it's amazingly problem solved. 😅

![image](https://github.com/dotnet/efcore/assets/88981/04aa586c-3313-4430-b195-0abb60776e06)

I think this is still an issue that the EF team should deal with.

**Comment by bricelam** [comment] 2023-08-28 21:32
Duplicate of https://github.com/dotnet/runtime/issues/46132

**Comment by vernou** [comment] 2023-08-29 07:35
@bricelam
Indeed, this seems to be fixed in the next version.

I just updated the NuGet package `Microsoft.Extensions.DependencyInjection` to 8.0.0-preview.7.23375.6 and it's work.

**Closed** 2023-09-06 18:50 UTC
Labels: closed-external, customer-reported

**Comment by sageharnie** [comment] 2024-05-08 15:55
@vernou How can I go about this

**Comment by vernou** [comment] 2024-05-08 17:07
It's resolved in .NET 8.
