### ISSUE TITLE
Errors after upgrade from EF Core 1.1 to 1.1.1

### ISSUE THREAD

**Issue by axelheer** [dotnet/efcore#7799] opened 2017-03-07 09:27 UTC
After upgrading a solution to EF Core 1.1.1 some queries fail with stack traces similar to the following.

```
Result StackTrace:	
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
Result Message:	No value provided for required parameter '_outer_Id1'.
```

I'll update the issue, when I find some time to create sample code for it. Need to find workarounds first.

*Update:* here comes some code...

```c#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;
using System.Linq;
using Microsoft.EntityFrameworkCore;

// --- Models ------------------------------------------------------------------

public class Parent
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public string Name { get; set; }

    public ISet<Child> Children { get; } = new HashSet<Child>();
}

public class Child
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public Guid? ParentId { get; set; }

    public Parent Parent { get; set; }
}

// -- ViewModels ---------------------------------------------------------------

public class ResultView
{
    public string Name { get; set; }

    public int Children { get; set; }
}

// --- Context -----------------------------------------------------------------

public class ModelContext : DbContext
{
    public DbSet<Parent> Parents { get; set; }

    public DbSet<Child> Children { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        var connectionStringBuilder = new SqlConnectionStringBuilder()
        {
            DataSource = "(localdb)\\MSSQLLocalDB",
            InitialCatalog = "EFCore",
            IntegratedSecurity = true
        };

        optionsBuilder.UseSqlServer(connectionStringBuilder.ConnectionString);
    }
}

// --- Test --------------------------------------------------------------------

public class Program
{
    public static void Main(string[] args)
    {
        // Set up database
        using (var context = new ModelContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }

        // Create query
        using (var context = new ModelContext())
        {
            var query = from parent in context.Parents
                        select new ResultView
                        {
                            Name = parent.Name,
                            Children = parent.Children.Count
                        };

            query.ToList();
        }
    }
}
```

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7
IDE: Visual Studio 2015

**Comment by Wayne-Mather** [comment] 2017-03-07 21:10
I got this error and also some others when trying to use .Select(new {});

I solved it by just returning the list and then iterating it to create new object as required

**Comment by ajcvickers** [comment] 2017-03-08 20:13
@axelheer This looks like a duplicate of #7811. I am going to close this one since the other issue has more information. If you think this is not a dupe of the other issue, then please can you provide more information on how to reproduce the bug and also include the exception message you are seeing.

**Comment by axelheer** [comment] 2017-03-11 11:29
@ajcvickers it's actually quite easy to reproduce. I've added the code; exception message is already there (copied from xunit ouput, whicht puts the message *after* the stack trace...).

**Closed** 2022-10-16 10:55 UTC
