### ISSUE TITLE
EFCore CosmosDB - Seed items with navigation properties

### ISSUE THREAD

**Issue by snerte** [dotnet/efcore#27789] opened 2022-04-08 08:53 UTC
I am trying to seed complex data to a CosmosDB using EFCORE 6. 

My code is very similar to:
``` csharp
    modelBuilder.Entity<MyObject>(builder =>
            {
                builder.HasKey(entity => new
                {
                    entity.SubscriptionId,
                    entity.Date
                });

                builder.OwnsMany(_ => _.Items);

                builder.HasData(CreateMyObjectWithItems());
            });
```

Unfortunately I cannot seed because I am setting the navigation property `Items`:

`[2022-04-07T11:04:53.673Z] System.Private.CoreLib: Exception while executing function: (...). Microsoft.EntityFrameworkCore: The seed entity for entity type 'MyObject' cannot be added because it has the navigation 'Items' set. To seed relationships,  add the entity seed to 'MyObject' and specify the foreign key values {'MyObjectSubscriptionId', 'MyObjectDate'}. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the involved property values.`

`MyObject` is stored as one JSON object. There is no key relationship between the `MyObject` and `Items`. How can I seed my data?

**Comment by AndriySvyryd** [comment] 2022-04-19 05:31
Duplicate of https://github.com/dotnet/efcore/issues/10000

As the exception mentions there are shadow properties that act as a foreign key in the model. See the third example on https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding for how to specify shadow properties in seed values.

**Closed** 2022-10-16 20:31 UTC
Labels: customer-reported
