### ISSUE TITLE
Sqlite - multiple include throw not implemented exception in Preview6

### ISSUE THREAD

**Issue by BaoNTGH** [dotnet/efcore#16190] opened 2019-06-21 05:49 UTC
Trying Preview 6 with the same code as Preview 5 for Microsoft.EntityFrameworkCore.Sqlite Provider triggers NotImplementedException:

```
Exception message: The method or operation is not implemented.
Stack trace:
Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.SqlExpressions.SelectExpression.ApplyCollectionJoin(Int32 collectionId, Expression shaperExpression, INavigation navigation)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalShapedQueryOptimizer.Visit(Expression query)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryCompilationContext2.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery2[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
```

### Steps to reproduce

Preview 6 + 2 includes: exception
Preview 6 + 1 include: works
Preview 5: works with 2 includes and 1 include

```c#
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <!-- <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.0.0-preview5.19227.1" /> -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.0.0-preview6.19304.10" />
  </ItemGroup>

</Project>
```

```c#
namespace EFCore
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.EntityFrameworkCore;

    class Program
    {
        static async Task Main(string[] args)
        {
            using (var context = new Context())
            {
                await context.Database.EnsureCreatedAsync().ConfigureAwait(false);
                var people = await context.People
                    .Take(1)
                    .Include(person => person.Photos)
                    .Include(person => person.Relationships)
                    .ToListAsync()
                    .ConfigureAwait(false);

                foreach (var person in people)
                {
                    Console.WriteLine(person.Name);
                }
            }

            Console.ReadLine();
        }
    }

    class Context : DbContext
    {
        public DbSet<Person> People { get; set; }

        public DbSet<Photo> Photos { get; set; }

        public DbSet<Relationship> Relationships { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Data Source=TestDB.db");
        }
    }

    class Person
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public ICollection<Photo> Photos { get; set; }

        public ICollection<Relationship> Relationships { get; set; }
    }

    class Photo
    {
        public int Id { get; set; }

        public string Path { get; set; }

        public Person Person { get; set; }
    }

    class Relationship
    {
        public int Id { get; set; }

        public string Type { get; set; }
    }
}
```

### Further technical details
EF Core version: 3.0.0-preview6.19304.10
Database Provider: Microsoft.EntityFrameworkCore.Sqlite 
Operating system: Windows 10
IDE: Visual Studio 2019 16.1.1

**Comment by drchilds** [comment] 2019-06-23 22:32
Can confirm this issue exists with the MSSQL provider as well.

**Comment by ajcvickers** [comment] 2019-06-24 19:18
@NguyenTanBao @drchilds 
First, many thanks for trying preview 6. We really appreciate people trying the previews and filing issues on what they find.

If you haven't seen it already, there is some good information in the [preview announcement post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/) about the changes that are happening to LINQ queries for EF Core 3.0. Preview 6 is the first release containing these changes, which means we are both expecting things to be broken, but at the same time very grateful for everyone who tries the release and generated feedback.

This case is a duplicate of #15611

**Closed** 2022-10-16 14:26 UTC
