### ISSUE TITLE
duplicated left join on select of Notmapped properties

### ISSUE THREAD

**Issue by Criperum** [dotnet/efcore#21699] opened 2020-07-20 17:45 UTC
When entity has both navigation property and one or more NotMapped properties selecting those properties in query results in multiple duplicate LEFT JOINs in SQL 

Below is the sample project i've made to reproduce this issue

```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Debug;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace EFCoreTest
{
    [Table(nameof(First))]
    public class First
    {
        [Key]
        public int Id { get; set; }
        public int Field1 { get; set; }
        public int Field2 { get; set; }
        [NotMapped]
        public int Field3 { get; set; }
        [NotMapped]
        public int Field4 { get; set; }
        public ICollection<Second> Seconds { get; set; }
    }
    [Table(nameof(Second))]
    public class Second
    {
        [Key]
        public int Id { get; set; }
        public int Field1 { get; set; }
        public int Field2 { get; set; }
        public int FirstId { get; set; }
    }
    public class TestContext : DbContext
    {
        public static readonly ILoggerFactory loggerFactory = new LoggerFactory(new List<ILoggerProvider> { new DebugLoggerProvider() });
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseLoggerFactory(loggerFactory).EnableSensitiveDataLogging()
                .UseSqlServer("Server=HININP59011\\SQLEXPRESS;Initial Catalog=TestDB3;Integrated Security=true;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;");
        }
        public DbSet<First> Firsts { get; set; }
        public DbSet<Second> Seconds { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var cont = new TestContext())
            {
                var r = cont.Firsts.Include(f => f.Seconds).Select(s => new { s.Field1, s.Field2, s.Field3, s.Field4, s.Id, s.Seconds }).ToList();
            }
        }
    }
}

```

This is SQL query I got form output window:
```sql
SELECT [f].[Field1], [f].[Field2], [f].[Id], [s].[Id], [s].[Field1], [s].[Field2], [s].[FirstId], [s0].[Id], [s0].[Field1], [s0].[Field2], [s0].[FirstId], [s1].[Id], [s1].[Field1], [s1].[Field2], [s1].[FirstId]
FROM [First] AS [f]
LEFT JOIN [Second] AS [s] ON [f].[Id] = [s].[FirstId]
LEFT JOIN [Second] AS [s0] ON [f].[Id] = [s0].[FirstId]
LEFT JOIN [Second] AS [s1] ON [f].[Id] = [s1].[FirstId]
ORDER BY [f].[Id], [s].[Id], [s0].[Id], [s1].[Id]
```

As you can see there are 2 extra LEFT JOINs exactly as much as NotMapped properties are in the select expression. Removing properties from select reduces amount of extra JOINs accordingly.

### Further technical details

EF Core version: 3.1.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.4

**Comment by smitpatel** [comment] 2020-07-24 17:40
Duplicate of #15783

**Closed** 2022-10-16 18:34 UTC
Labels: customer-reported
