### ISSUE TITLE
MissingMethodException when upgrading to entity framework core with mysql

### ISSUE THREAD

**Issue by shahafal** [dotnet/efcore#7376] opened 2017-01-08 00:03 UTC
I have a working application with the following dependencies:
dot net core 1.0
entity framework core 1.0
mysql official connector 7.0.4-IR-191

due to a problem entity framework core 1.0 and mysql connector 7.0.4 have with the Contains method (see this issue: https://github.com/aspnet/EntityFramework/issues/6687)
i saw that there is a fix in the latest mysql connector 7.0.6 along with entity framework 1.1 -
as noted in the release notes here:
http://insidemysql.com/mysql-connectornet-7-0-6-m5-development-has-been-released/
```
EF Core: An SQL syntax error was emitted when the Contains operator was used in the Where predicate of a LINQ query. This fix requires the use of EF Core version
1.1 or later. (Bug #24797524)
```

so i went and upgraded my app to use:
dot net core 1.1
entity framework core 1.1
mysql official connector 7.0.6-IR31

and now i'm getting this error when i do `dotnet run`:
```
$ dotnet run
Project MyApp (.NETCoreApp,Version=v1.1) will be compiled because inputs were modified
Compiling MyApp for .NETCoreApp,Version=v1.1

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.9669143
 


Unhandled Exception: System.MissingMethodException: Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory..ctor(Microsoft.EntityFrameworkCore.Infrastructure.ISensitiveDataLogger`1<Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory>, System.Diagnostics.DiagnosticSource, Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalServiceCollectionExtensions.<>c.<AddRelational>b__0_9(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_13(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at MyApp.Dal.Context.AppDbContextFactory.Create() in /Users/user/Wip/MyApp/src/MyApp/app/dal/context/AppDbContextFactory.cs:line 16
   at MyApp.Startup..ctor(IHostingEnvironment env) in /Users/user/Wip/MyApp/src/MyApp/Startup.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at MyApp.Program.Main(String[] args) in /Users/user/Wip/MyApp/src/MyApp/Program.cs:line 11
```
this is my project.json file:
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "preserveCompilationContext": true,
    "emitEntryPoint": true
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        },
        "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
        "Microsoft.AspNetCore.Mvc": "1.1.0",
        "Microsoft.EntityFrameworkCore": "1.1.0",
        "Microsoft.EntityFrameworkCore.Relational": "1.1.0",
        "MySql.Data": "7.0.6-IR31",
        "MySql.Data.EntityFrameworkCore": "7.0.6-IR31",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
        "Microsoft.Extensions.Configuration.Json": "1.1.0",
        "Microsoft.AspNetCore.StaticFiles": "1.1.0",
        "System.Security.Cryptography.Algorithms": "4.3.0",
        "System.Text.Encoding": "4.3.0",
        "Microsoft.AspNetCore.Diagnostics": "1.1.0",
        "Microsoft.Extensions.Logging.Console": "1.1.0"
      },
      "imports": "dnxcore50"
    }
  }
}

```

this exception happened also before upgrading to dot net core 1.1 -
meaning i started by upgrading only entity framework core to 1 .1 and mysql connector to 7.0.6 and got this error, and i hoped upgrading the dot net core version from 1.0 to 1.1 (as you see in the project.json file i put) would help but the error stayed the same.

### Further technical details
EF Core version: 1.1
Database Provider: MySql.Data.EntityFrameworkCore 7.0.6-IR31
Operating system: OSX 10.11.6
IDE: Visual Studio Code 1.8.1

**Comment by ajcvickers** [comment] 2017-01-09 17:51
Dupe of #7223.

**Closed** 2022-10-16 10:49 UTC
Labels: closed-duplicate
