### ISSUE TITLE
Single Record Insertion Slow

### ISSUE THREAD

**Issue by urjapatel** [dotnet/efcore#17581] opened 2018-10-22 09:28 UTC
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

Provide an Example for how to insert single record faster.
Inserting single record into database is slower takes minimum 400ms to 800ms time for inserting single records when context.SaveChanges() is executed.

**Comment by ajcvickers** [comment] 2019-09-06 16:39
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:39 UTC
Labels: closed-could-not-reproduce
