### ISSUE TITLE
Feauture for Use Parent Instead Of Entity Type in Ef Core of Navigation property

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/efcore#22871] opened 2020-10-02 18:55 UTC
Create One Query Filter And One Relation Ship And Config One type for all That Childs Types

Iwana to Create Domain Base in another Project named Infrastructure And I Want to Create Status Model To Set State Of Records Now I Create Relation Ship with Parent of Status model in Modelbase Entity Named That a Status And Set That Id for Guid Type
and Now I wana to make all Childs of ModelBase Type Relation with Status Model
and Create QueryFilter That said Dont Get or Dont return Records Which That status is Deleted!

**Comment by ajcvickers** [comment] 2020-10-05 21:22
@sajjadarashhh I _think_ you might be looking for #10259.

**Comment by AndriySvyryd** [comment] 2020-10-12 17:40
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:03 UTC
Labels: closed-duplicate, customer-reported
