### ISSUE TITLE
change LogExecutedCommand elapsed parameter from string to int or do not send thousands seperator

### ISSUE THREAD

**Issue by dovjar** [dotnet/efcore#34281] opened 2024-07-24 15:22 UTC
current efcore logging for executed command with message template: 
Executed DbCommand ({elapsed}ms) [Parameters=[{parameters}], CommandType='{commandType}', CommandTimeout='{commandTimeout}']{newLine}{commandText}

logs elapsed metric as string.
code from RelationalCommandDiagnosticsLogger.cs
method CommandReaderExecuted
code

```
definition.Log(
                this,
                string.Format(CultureInfo.InvariantCulture, "{0:N0}", duration.TotalMilliseconds),
                command.Parameters.FormatParameters(ShouldLogParameterValues(command)),
                command.CommandType,
                command.CommandTimeout,
                Environment.NewLine,
                command.CommandText.TrimEnd());
```

duration.TotalMilliseconds is  formated using InvariantCulture with 0 decimal places. But still writes comma as thousand seperator.
e.g. 
` string.Format(CultureInfo.InvariantCulture, "{0:N0}",1234,5m) // will return 1,234
`
Therefore log tools will not recognize this value as number and you will not be able to use these metric as number. for example can't do aggregations.
 

change property to int as in the same class method:
DataReaderDisposing

```c#
if (ShouldLog(definition))
{
    _suppressDataReaderDisposingExpiration = default;
    definition.Log(this, connection.DbConnection.Database, connection.DbConnection.DataSource, (int)duration.TotalMilliseconds);
}
```

**Comment by ajcvickers** [comment] 2024-08-12 11:57
Related to #33598.

**Comment by roji** [comment] 2024-10-11 15:15
Duplicate of #3598

**Closed by roji** 2024-10-11 15:15 UTC
Labels: type-enhancement, customer-reported
