### ISSUE TITLE
Split mappings are not supported for hierarchies

### ISSUE THREAD

**Issue by Ukkie007** [dotnet/efcore#34190] opened 2024-07-09 14:53 UTC
the one in the subject.

I was able to do so in Entity Framework 6, but not in EF Core. I had no performance issues, so migrating is for me no option at this moment.

**Comment by Ukkie007** [comment] 2024-07-10 12:24
[EFCoreSplitTables.zip](https://github.com/user-attachments/files/16161882/EFCoreSplitTables.zip)

Database is included as a bacpac.
I have a working version in Entity Framework 6 with an identical database schema.

**Comment by AndriySvyryd** [comment] 2024-07-13 00:00
Duplicate of https://github.com/dotnet/efcore/issues/27970

**Closed by AndriySvyryd** 2024-07-13 00:00 UTC
Labels: customer-reported
