### ISSUE TITLE
Allow generate inner join on Include

### ISSUE THREAD

**Issue by vocko** [dotnet/efcore#26194] opened 2021-09-28 05:39 UTC
As there is no (implicit) way to generate an inner join, it might be a good idea to add an optional second parameter (called ie. `force`) of type boolean to the `Include` method that would generate an inner join on that property. It would generate more efficient queries than sub-select on the where clause.

Not sure this hasn't been suggested before, you can reject it if not suitable for some reason. Explanation would be appreciated though.

```csharp
dbContext.Parents.Include(p => p.Children, true);
```

it would generate query like this:
```sql
SELECT * FROM Parents p
INNER JOIN Children c
    ON p.Id = c.ParentId
```

instead of the current 
```csharp
dbContext.Parents
    .Include(p => p.Children)
    .Where(p => p.Children.Any());
```

what generates:
```sql
SELECT * FROM Parents p
LEFT JOIN Children c
    ON p.Id = c.ParentId
WHERE EXISTS (
    SELECT 1
    FROM Children
    WHERE c.ParentId=p.Id
)
```

Also any way of generating `IS NULL` comparison would be handy for the case above. Is there any option to generate something like `WHERE c.Id IS NULL`? I could not make EF Core to generate query like this.

**Comment by begerard** [comment] 2021-09-29 16:43
I'd also add that if your .Include() have a constraint you need to repeat it in the .Any():
```
dbContext.Parents
    .Include(p => p.Children.Where(c => c.Age < 18))
    .Where(p => p.Children.Any(c => c.Age < 18));
```

Which smell quite badly (if you change one contraint but not the other you just introduced a bug) so in definitive you are better off to do it out of the query like that:
```
var parents = dbContext.Parents.Include(p => p.Children.Where(c => c.Age < 18)) .ToListAsync();
parents.Where(p => p.Chidren.Any());
```

I found this to be a common use case, and the present choices are:
- bad code (smelly C# and slow SQL)
- overloading data (slow SQL and bandwidth eater)
- RAW SQL (inner join)

I think EF should give us a better solution for this!

**Comment by smitpatel** [comment] 2021-09-29 18:05
Duplicate of #24955

**Closed** 2022-10-16 20:09 UTC
Labels: closed-duplicate, customer-reported
