### ISSUE TITLE
Configure computed database property values using expressions

### ISSUE THREAD

**Issue by jupjohn** [dotnet/efcore#30496] opened 2023-03-16 00:08 UTC
If you wish to add a computed value to a column via EF using the Fluent API, you're required to use `PropertyBuilder.HasComputedColumnSql("your SQL code")` to set its expression. This requires that you use the target DB's flavour of SQL to write the expression which locks that computed value to a single provider (maybe not in all cases).

I would like to see the use of `Expression<TEntity>` used in a method like `HasComputedColumn` which will translate the given expression to the target SQL dialect. This allows for some slightly more complex computed values to be expressed without using a huge chunk of SQL - as well as using a language a code-first developer is comfortable with.

Tiny example:
```c#
class Person
{
    public decimal WeightInKilograms { get; init; }
    public decimal HeightInMeters { get; init; }
    public decimal BodyMassIndex { get; init; }
}

// ...

modelBuilder.Entity<Person>
    .Property(person => person.BodyMassIndex)
    .HasComputedColumn(person => person.WeightInKilograms / person.HeightInMeters ^ 2);

// Would translate to something like "[WeightInKilograms] / POWER([HeightInMeters], 2)"
```

I'm not entirely sure where the SQL translation happens so maybe this isn't possible at the model building level. If it does sound possible, I'd be keen to take a stab at implementing this feature.

**Comment by jammehcow** [comment] 2023-03-16 00:10
Slightly ties into [this comment](https://github.com/dotnet/efcore/issues/11001#issuecomment-1284407531) on #11001

**Comment by roji** [comment] 2023-03-16 00:30
Duplicate of #11001

**Closed** 2023-03-20 19:54 UTC
Labels: customer-reported
