### ISSUE TITLE
Reuse existing value of a complex property / owned type

### ISSUE THREAD

**Issue by Liero** [dotnet/efcore#33545] opened 2024-04-16 06:58 UTC
## Ask a question

Given a complex property has a default value, is it possible to reuse the property instance similar to collection navigation properties?

When fetching from database, existing instance updated with database values rather than creating whole new instance.

It would allow to pass arbitrary parameter to either ctor or as a property.

## Sample

```C#
public class Entity
{
    //mapped as a ComplexProperty
    public SideParams SideA { get; } = new SideParams { Side = "A" }; //when fetching from database, this instance would be kept.
    public SideParams SideB { get; } = new SideParams { Side = "B" };
}

public class SideParams
{
    public required string Side { get; init; } //ignored
    public int Column1 { get; set; }
    public int Column2 { get; set; }
}
```

```C#
public class Entity: IEntity
{
    public Entity()
    {
        SideA = new SideParams(this);
        SideB = new SideParams(this);   
    }
    public SideParams SideA { get; }
    public SideParams SideB { get; }
}

public class SideParams
{
    public ISideParams(IEntity parent)
    {
    }
    public int Column1 { get; set; }
    public int Column2 { get; set; }
}
```

**Comment by ajcvickers** [comment] 2024-07-20 15:28
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2024-08-12 08:29
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-08-12 08:29 UTC
Labels: customer-reported, area-query, area-change-tracking
