### ISSUE TITLE
Good to have a option to scaffold dbcontext except some table

### ISSUE THREAD

**Issue by kuntalbose** [dotnet/efcore#19183] opened 2019-12-05 18:53 UTC
Hi
Suppose in database I have 40 tables including 7 identity framework  tables,that means for the application there are 33 tables and the count of tables can be incise or decries .And if I want to generate a context for only 33 tables ,as per  [documentation ](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#dotnet-ef-dbcontext-scaffold) I need to write 33 tables name for each time when required to regenerate context for any db changes .But if we have an **except switch** then can I can specify the 7 identity tables  only in the command and run the exact same command each time with more confident.

**Comment by smitpatel** [comment] 2019-12-05 18:56
Duplicate of #6182

**Comment by ErikEJ** [comment] 2019-12-05 20:26
You can use EF Core Power Tools to do this.

**Comment by ikuntalb** [comment] 2019-12-06 02:03
Hi @ErikEJ 
Thanks for comment.Do you know is Microsoft add this feature in EF Core?

**Closed** 2022-10-16 17:59 UTC
Labels: customer-reported
