### ISSUE TITLE
NullReferenceException thrown within IncludeCompiler.WalkNavigations

### ISSUE THREAD

**Issue by optiks** [dotnet/efcore#12627] opened 2018-07-11 12:24 UTC
I'm unable to isolate this one yet, but wanted to get the issue raised ASAP as it's currently blocking us. 

I suspect the issue is due to a bad mapping on our side, however it's currently difficult to identity where that may be as the exception is not being thrown.

For context, this particular entity has a number of levels of inheritance, which may or may not be contributing.

Looking at IncludeCompiler.cs, it looks like `longestMatchFound.EntityType` is null within:

```
throw new InvalidOperationException(
                    CoreStrings.IncludeBadNavigation(
                        navigationPropertyPaths[longestMatchFound.Depth],
                        longestMatchFound.EntityType.DisplayName()));
```

```
Exception message: System.NullReferenceException: 'Object reference not set to an instance of an object.'
Stack trace:
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.EntityTypeExtensions.DisplayName(Microsoft.EntityFrameworkCore.Metadata.IEntityType type)	Unknown
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.WalkNavigations(Microsoft.EntityFrameworkCore.Metadata.IEntityType entityType, System.Collections.Generic.IReadOnlyList<string> navigationPropertyPaths, Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.IncludeLoadTree includeLoadTree)	Unknown
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.PopulateIncludeLoadTree(Microsoft.EntityFrameworkCore.Query.ResultOperators.Internal.IncludeResultOperator includeResultOperator, Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.IncludeLoadTree includeLoadTree)	Unknown
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.CreateIncludeLoadTrees(Remotion.Linq.QueryModel queryModel)	Unknown
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.CompileIncludes(Remotion.Linq.QueryModel queryModel, bool trackingQuery, bool asyncQuery)	Unknown
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(Remotion.Linq.QueryModel queryModel, bool asyncQuery)	Unknown
 	Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeQueryModel(Remotion.Linq.QueryModel queryModel, bool asyncQuery)	Unknown
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor<SomeEntity>(Remotion.Linq.QueryModel queryModel)	Unknown
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery<SomeEntity>(Remotion.Linq.QueryModel queryModel)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore<System.Collections.Generic.IEnumerable<SomeEntity>>(System.Linq.Expressions.Expression query, Microsoft.EntityFrameworkCore.Query.Internal.IQueryModelGenerator queryModelGenerator, Microsoft.EntityFrameworkCore.Storage.IDatabase database, Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger<Microsoft.EntityFrameworkCore.DbLoggerCategory.Query> logger, System.Type contextType)	Unknown
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute.AnonymousMethod__0()	Unknown
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore<System.Collections.Generic.IEnumerable<SomeEntity>>(object cacheKey, System.Func<System.Func<Microsoft.EntityFrameworkCore.Query.QueryContext, System.Collections.Generic.IEnumerable<SomeEntity>>> compiler)	Unknown
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery<System.Collections.Generic.IEnumerable<SomeEntity>>(object cacheKey, System.Func<System.Func<Microsoft.EntityFrameworkCore.Query.QueryContext, System.Collections.Generic.IEnumerable<SomeEntity>>> compiler)	Unknown
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute<System.Collections.Generic.IEnumerable<SomeEntity>>(System.Linq.Expressions.Expression query)	Unknown
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute<System.Collections.Generic.IEnumerable<SomeEntity>>(System.Linq.Expressions.Expression expression)	Unknown
```

### Steps to reproduce
Unable to isolate a repro yet.

### Further technical details
EF Core version: 2.1
Database Provider: EntityFrameworkCore.SqlServerCompact35
Operating system: Windows 10.0.17134.112
IDE: Visual Studio 2017 15.7.2

**Comment by optiks** [comment] 2018-07-11 13:37
Additional info: The trigger for this being thrown is code along the lines of:
```
class Base {
}

class Derived1 : Base {
   public ICollection<Derived1Relation> Relations { get; set; }
}

class Derived1Relation {
}

class Derived2 : Base {
}

...

var result = 
   context.Set<Base>()
      .Include(x => ((Derived1) x).Relations)
      .OfType<Derived2>() // The include above for .Relations is no longer applicable
      .ToList();
```

**Comment by ajcvickers** [comment] 2018-08-03 20:51
@smitpatel to look for duplicate.

**Comment by smitpatel** [comment] 2018-08-03 21:32
Duplicate of #11971

**Closed** 2022-10-16 13:18 UTC
Labels: closed-duplicate, customer-reported
