### ISSUE TITLE
Error: An assembly specified in the application dependencies manifest (***.deps.json) was not found

### ISSUE THREAD

**Issue by balivo** [dotnet/efcore#20937] opened 2020-05-13 00:15 UTC
I update to 3.1.4 version (design, tools, cmd tools, etc) and update VS2019 to 16.5.5...

When I run Add-Migrations from PMC the error appears:

Error:
  An assembly specified in the application dependencies manifest (MyApplication.Api.deps.json) was not found:
    package: 'MyApplication.Data.SQLServer', version: '1.0.0'
    path: 'MyApplication.Data.SQLServer.dll'

SO, when I run "dotnet ef migrations" from CMD (PowerShell), evereything works ok...

Additional info, some tests:

Test 1) When I set my "*.Data.SQLServer" project to Default (on PMC) and Startup (on Solution Explorer) Project everything works.

Test 2) When I set my "*.Data.SQLServer" project to Default (on PMC) and "*.Services.Api" at Startup (on Solution Explorer) Project, error!

At old version (3.1.1) "Test 2" works.

Tks Guys!

**Comment by ajcvickers** [comment] 2020-05-15 21:02
@balivo Can you please post your csproj files. Also, what is the current directory when running the PMC commands? And what is it when running the `dotnet ef` commands in the PMC? What arguments are you passing to the commands in each case?

**Comment by balivo** [comment] 2020-05-15 21:50
I'll try reproduce the problem in a separate project and upload here... Ok?

**Comment by ajcvickers** [comment] 2020-05-29 15:47
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:24 UTC
Labels: closed-could-not-reproduce, customer-reported
