### ISSUE TITLE
Entity Framework Core `HasConversion` property configuration not used when querying data with postgresql

### ISSUE THREAD

**Issue by natalie-o-perret** [dotnet/efcore#19589] opened 2020-01-14 22:00 UTC
I am using Entity Framework with Postgre through Npgsql, part of my configuration for the `Cashout` type which maps to the `Cashouts` table involves:

```csharp
public void Configure(EntityTypeBuilder<Cashout> builder)
{
	builder.ToTable("Cashouts");
	builder.ConfigureGuidEntity();

	builder.Property(c => c.RecipientAccountId).IsRequired();
	builder.Property(c => c.State).IsRequired().HasConversion(
	v => v!.Name, 
	v => Enumeration.FromDisplayName<CashoutState>(v));
	
	builder.HasIndex(e => e.State);
	builder.HasIndex(e => e.RecipientAccountId);

	builder.UseXminAsConcurrencyToken();
}
```

The `Cashout` type is defined as below:
```csharp
public class Cashout : GuidEntity
{
	public int RecipientAccountId { get; set; }
	public string? RecipientAccountName { get; set; }
	public decimal Amount { get;  set; }
	public string? Comment { get; set; }
	public CashoutState? State { get; set; } = CashoutState.Pending;
	public string? Reason { get; set; }
	
	public Cashout()
	{
	}
	
	public Cashout(Guid id)
		: base(id)
	{
	}
}
```

and inherits from the `GuidEntity` type:
```csharp
public abstract class GuidEntity : Entity<Guid>
{
	protected GuidEntity()
	{
		Id = Guid.Empty;
	}
	protected GuidEntity(Guid id)
	{
		Id = id;
	}

	public DateTimeOffset CreatedOn { get; private set; } = DateTimeOffset.UtcNow;
	public DateTimeOffset? UpdatedOn { get; private set; }
}
```

which itself inherits from `Entity`:
```csharp
public abstract class Entity<TKey> : IEntity<TKey>, IEquatable<Entity<TKey>>
		where TKey: struct
{
	private readonly Lazy<int> _requestedHashCode;
	private readonly Lazy<int> _requestedTransientHashCode;
		
	public virtual TKey Id { get; protected set; }

	protected Entity()
	{
		_requestedHashCode = new Lazy<int>(() => Id.GetHashCode() ^ 31);
		_requestedTransientHashCode = new Lazy<int>(() => Guid.NewGuid().GetHashCode());
	}

	public bool IsTransient() =>
		EqualityComparer<TKey>.Default.Equals(Id, default);

	public override bool Equals(object obj) =>
		Equals((obj as Entity<TKey>)!);

	public bool Equals(Entity<TKey> other)
	{
		if (other == null)
		{
			return false;
		}

		if (ReferenceEquals(this, other))
		{
			return true;
		}

		if (other.IsTransient() || this.IsTransient())
		{
			return false;
		}

		return EqualityComparer<TKey>.Default.Equals(other.Id, Id);
	}

	public override int GetHashCode() => IsTransient() ?
		_requestedTransientHashCode.Value :
		_requestedHashCode.Value;
}
```

The type of the `State` property is the `CashoutState`:
```csharp
public abstract class CashoutState : Enumeration
{
	public static CashoutState Transferred = new TransferredCashoutState();
	public static CashoutState TransferFailed = new TransferFailedCashoutState();
	
	public static CashoutState Withdrawn = new WithdrawnCashoutState();
	public static CashoutState WithdrawalFailed = new WithdrawalFailedCashoutState();
	
	public static CashoutState Pending = new PendingCashoutState();
	public static CashoutState Cancelled = new CancelledCashoutState();
	
	protected CashoutState(int id, string name)
		: base(id, name) { }

	private class TransferredCashoutState : CashoutState
	{
		public TransferredCashoutState()
			: base(1, nameof(Transferred)) { }
	}

	private class WithdrawnCashoutState : CashoutState
	{
		public WithdrawnCashoutState()
			: base(2, nameof(Withdrawn)) { }
	}

	private class WithdrawalFailedCashoutState : CashoutState
	{
		public WithdrawalFailedCashoutState()
			: base(3, nameof(WithdrawalFailed)) { }
	}
	
	private class TransferFailedCashoutState : CashoutState
	{
		public TransferFailedCashoutState()
			: base(4, nameof(TransferFailed)) { }
	}

	private class PendingCashoutState : CashoutState
	{
		public PendingCashoutState()
			: base(5, nameof(Pending)) { }
	}
	
	private class CancelledCashoutState : CashoutState
	{
		public CancelledCashoutState()
			: base(6, nameof(Cancelled)) { }
	}
}
```

and then there is yet another bit of inheritance with the `Enumeration` type:
```csharp
	public abstract class Enumeration : IComparable
	{
		public string Name { get; private set; }

		public int Id { get; private set; }

		protected Enumeration(int id, string name)
		{
			Id = id;
			Name = name;
		}

		public override string ToString() => Name;
		
		public static IEnumerable<T> GetAll<T>() where T : Enumeration =>
			typeof(T)
				.GetFields(BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly)
				.Select(f => f.GetValue(null)).Cast<T>();

		public override bool Equals(object obj)
		{
			if (!(obj is Enumeration otherValue))
				return false;

			var typeMatches = GetType() == obj.GetType();
			var valueMatches = Id.Equals(otherValue.Id);

			return typeMatches && valueMatches;
		}

		public override int GetHashCode() => 
			Id.GetHashCode();

		public static int AbsoluteDifference(Enumeration firstValue, Enumeration secondValue) =>
			Math.Abs(firstValue.Id - secondValue.Id);

		public static T FromValue<T>(int value) where T : Enumeration =>
			Parse<T, int>(value, "value", item => item.Id == value);

		public static T FromDisplayName<T>(string displayName) where T : Enumeration =>
			Parse<T, string>(displayName, "display name", item =>
				string.Equals(item.Name, displayName, StringComparison.InvariantCultureIgnoreCase));

		private static T Parse<T, TValue>(TValue value, string description, Func<T, bool> predicate) where T : Enumeration =>
			GetAll<T>().FirstOrDefault(predicate) ?? 
			throw new InvalidOperationException($"'{value}' is not a valid {description} in {typeof(T)}");

		public int CompareTo(object obj) => 
			Id.CompareTo(((Enumeration)obj).Id);
	}
```

The configuration works for persisting data:
```csharp
var cashout = new Cashout
{
	Amount = command.Amount,
	RecipientAccountId = command.RecipientAccountId,
	Comment = command.Comment,
	State = CashoutState.Pending
};	

dbContext.Cashouts.Add(cashout);
dbContext.SaveChanges();
```

but when it comes to querying data based on that state, it fails miserably, I tried respectively:

# Querying given a specific state
```csharp
var cancelledByState = await _dbContext.Cashouts.Where(x => x.State == CashoutState.Cancelled).FirstAsync();
```
throws: 
```
System.InvalidOperationException: The LINQ expression 'DbSet<Cashout>
    .Where(c => c.State.Name == __Cancelled_Name_0)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to
either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancella
tionToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

# Querying given a specific state name
```csharp
var cancelledByStateName = await _dbContext.Cashouts.Where(x => x.State.Name == CashoutState.Cancelled.Name).FirstAsync();
```
throws:
```
System.InvalidOperationException: The LINQ expression 'DbSet<Cashout>
    .Where(c => c.State.Name == __Cancelled_Name_0)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to
either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancella
tionToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

# Querying given a specific state id

```csharp
var cancelledByStateId = await _dbContext.Cashouts.Where(x => x.State.Id == CashoutState.Cancelled.Id).FirstAsync();
```
throws:
```
System.InvalidOperationException: The LINQ expression 'DbSet<Cashout>
    .Where(c => c.State.Id == __Cancelled_Id_0)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to eith
er AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancella
tionToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

I would like to find a way to query the `DbSet<Cashout>` using the state property. That is that there is a proper conversion. Is there currently a solution to that problem?

- EF Core version: 3.1.0
- Database provider: https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL 3.1.0
- Target framework: .NET Core 3.1.0
- Operating system: Windows 10 Pro. Edition
- IDE: Rider 2019.3.1

Note: it seems that it works like a charm when using the In-memory mode and failed like above whenever the context is bound to an actual sql database server.

**Comment by roji** [comment] 2020-01-15 21:14
Also opened in the Npgsql repo as https://github.com/npgsql/efcore.pg/issues/1199, have asked for a full repro there. We can wait a few days and see where this goes.

**Comment by ajcvickers** [comment] 2020-02-03 17:39
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:06 UTC
Labels: closed-could-not-reproduce, customer-reported
