### ISSUE TITLE
EF Core 1.1.2 fail: Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory[1]

### ISSUE THREAD

**Issue by robinkedia** [dotnet/efcore#9035] opened 2017-07-01 02:29 UTC
Just trying to retrieve a record using username field. EF Core throws exception. 

**Additionally, NO SQL Statement generated in Debug Console.** 

```
Exception message:
Stack trace:

fail: Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory[1]
      An exception occurred in the database while iterating the results of a query.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__31.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<BufferlessMoveNext>d__9.MoveNext()

```

### Steps to reproduce

```c#
 public bool CheckExists(Role model){
            return  this.Get(model.Name) == null ? false:true;
        }
 public async Task<Role> Get(string name){
            return await this.context.Roles.FirstOrDefaultAsync( f => f.Name == name);
        }
```
```c# Controller
 public async Task<IActionResult> Add([FromBody] Role model) {
            if(!ModelState.IsValid)
                 return BadRequest(this.PrepareResponse(ModelState.Values)
            );
            
            var exists = this.repository.CheckExists(model);
            if(exists)
            return BadRequest(  this.PrepareResponse(
                    this.applicationConfiguration.Messages[this.MessageErrorRoleExists])
            );
             this.repository.Add(model);
            await this.repository.SaveChangesAsync();
            return Ok(  this.PrepareResponse(model, 
                        this.applicationConfiguration.Messages[this.MessageSucessRoleAdd])
                    );
}
```

### Further technical details
EF Core version: 
 PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" 
 PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" 
 PackageReference Include="Microsoft.Extensions.Options" Version="1.1.2"
 PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.2"
 PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.2"

Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: MAC OS Sierra 10.12.5
IDE: (e.g. Visual Studio 2015)
VS Code v1.13.1

**Comment by robinkedia** [comment] 2017-07-01 23:41
Hi - Any update on this one?

**Comment by robinkedia** [comment] 2017-07-03 00:20
I switched from SQL Server to MySQL Pomelo and found the issue to be DB Context null. The console error for Pomelo is much clear than SQL Server one. 

`fail: Microsoft.EntityFrameworkCore.Query.Internal.MySqlQueryCompilationContextFactory[1]
      An exception occurred in the database while iterating the results of a query.
      System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
      Object name: 'AppDbContext'.
         at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
         at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
         at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.LoadNavigationProperties(Object entity, IReadOnlyList`1 navigationPath, Int32 currentNavigationIndex, IReadOnlyList`1 relatedEntities, Boolean tracking)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.<IncludeAsync>d__13.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.IncludeAsyncEnumerable`1.IncludeAsyncEnumerator`1.<MoveNext>d__7.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.<_SingleOrDefault>d__123`1.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.EntityFrameworkCore.Query.Internal.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'AppDbContext'.`

**Comment by ajcvickers** [comment] 2017-07-03 18:19
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2017-07-10 18:15
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:10 UTC
Labels: closed-could-not-reproduce
