### ISSUE TITLE
using the old many to many behavior of entity framework in ef core

### ISSUE THREAD

**Issue by julienGrd** [dotnet/efcore#20933] opened 2020-05-12 13:08 UTC
Hello guys, for some project migration i try have the same entity both in a entity framework 5 project and on a .net core project with entity framework core. I met problems with many-to-many relationship.
I know they don't use the same way to represent the relationship (entity framework hide the join table whereas ef core use it). But its a problem for me to achieve what i want.

So it is something you planned to change in the future ? for now i don't find another way than specifies a condionnal symbol attribute and manage two set of requests for each configuration

for example
in EF
ClassA
- collection<ClassB>
ClassB
- collection<ClassA>

in EF core
ClassA
- collection<JoinBA>
ClassB
- collection<JoinBA>
JoinBA
- ClassA
- ClassB

Request
````
#if EFCORE
var allB = context.JoinBACollection.select(a => a.ClassB).ToList();
#else
var allB= context.ClassBCollection.ToList();
#endif
````

Thanks for your help !

PS : It's not precise but i generate entities en the EF5 project and use the directly on the .net core project. I'm open to update the ef5 generation project if its more simple.

**Comment by ajcvickers** [comment] 2020-05-12 14:38
@julienGrd Duplicate of #10508. Discussion is in #1368.

**Closed** 2022-10-16 18:24 UTC
Labels: closed-duplicate, customer-reported
