### ISSUE TITLE
After upgrading to .Net Core 2.1 and EF Core 2.1 DeleteBehavior.Restrict is not working

### ISSUE THREAD

**Issue by nishantkagrawal** [dotnet/efcore#12505] opened 2018-06-29 13:03 UTC
## Describe what is not working as expected.

I have following models (See https://github.com/nishantkagrawal/EFCoreIssue for code)
```C#
public class CatalogCategory
{
	[Column("catalog_category_id")]
	public int CategoryId { get; set; }

	[Column("category_name")]
	[Required]
	public string CategoryName { get; set; }

	[Column("category_description")]
	public string CategoryDescription { get; set; }

	public virtual ICollection<CatalogGroup> CatalogGroups { get; set; }

	public virtual ICollection<CatalogDiscount> CatalogDiscounts { get; set; }


	public static void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<CatalogCategory>(catalogCategories =>
		{
			catalogCategories.HasMany(p => p.CatalogGroups).WithOne(g => g.CatalogCategory).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_group_category_category_id");
			catalogCategories.HasMany(p => p.CatalogDiscounts).WithOne(g => g.CatalogCategory).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_discount_category_category_id");
			catalogCategories
				.ToTable("catalog_category")
				.HasKey(k => k.CategoryId)
				.HasName("pk_catalog_category");
			catalogCategories.ToTable("catalog_category").HasIndex(p => p.CategoryName).IsUnique();
		});
	}
}

[Table("catalog_metadata")]
public class CatalogMetadata
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Key]
    [Column(name: "catalog_metadata_id", Order = 0)]
    public int Id { get; set; }

    [Column(name: "product_code")]
    [Required]
    public string ProductCode { get; set; }

    [Column(name: "start_date")]
    [Required]
    public DateTime StartDate { get; set; }

    [Column(name: "end_date")]
    [Required]
    public DateTime EndDate { get; set; }

    [Column(name: "current_volume")]
    [Required]
    public string CurrentVolume { get; set; }

    [Column(name: "pre_sell_volume")]
    [Required]
    public string PreSellVolume { get; set; }

    [Column("description")]
    [Required]
    public string Description { get; set; }

    [Column("title")]
    [Required]
    public string Title { get; set; }

    [ForeignKey("CatalogGroupId")]
    public virtual CatalogGroup CatalogGroup { get; set; }

    [Column("catalog_group_id")]
    public int CatalogGroupId { get; set; }

    [Column("attributes", TypeName = "json")]
    public string Attributes { get; set; }

    public static void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CatalogMetadata>(missingProductDetails =>
        {
            missingProductDetails.HasOne(p => p.CatalogGroup).WithMany(g => g.CatalogMetadata).IsRequired();
            missingProductDetails
                .ToTable("catalog_metadata")
                .HasKey(k => k.Id)
                .HasName("pk_catalog_metadata");
            missingProductDetails.ToTable("catalog_metadata").HasIndex(p => p.ProductCode).IsUnique();
        });
    }
}

public class CatalogDiscount
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Key]
    [Column(name: "catalog_discount_id", Order = 0)]
    public int Id { get; set; }

    [Column("order_quantity")]
    [Required]
    public string OrderQuantity { get; set; }

    [Column("discount")]
    [Required]
    public int Discount { get; set; }

    [Column("notes")]
    public string Notes { get; set; }

    [Column(name: "start_date")]
    [Required]
    public DateTime StartDate { get; set; }

    [Column(name: "end_date")]
    [Required]
    public DateTime EndDate { get; set; }

    [Column(name: "catalog_category_id")]
    public int CatalogCategoryId { get; set; }

    [ForeignKey("CatalogCategoryId")]
    public CatalogCategory CatalogCategory { get; set; }

    [Column("free_shipping")]
    [Required]
    public bool FreeShipping { get; set; }

    public static void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CatalogDiscount>(catalogDiscount =>
        {
            catalogDiscount.HasOne(p => p.CatalogCategory).WithMany(g => g.CatalogDiscounts).IsRequired();
            catalogDiscount
                .ToTable("catalog_discount")
                .HasKey(k => k.Id)
                .HasName("pk_catalog_discount");
        });
    }
}

[Table("catalog_metadata")]
public class CatalogMetadata
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Key]
    [Column(name: "catalog_metadata_id", Order = 0)]
    public int Id { get; set; }

    [Column(name: "product_code")]
    [Required]
    public string ProductCode { get; set; }

    [Column(name: "start_date")]
    [Required]
    public DateTime StartDate { get; set; }

    [Column(name: "end_date")]
    [Required]
    public DateTime EndDate { get; set; }

    [Column(name: "current_volume")]
    [Required]
    public string CurrentVolume { get; set; }

    [Column(name: "pre_sell_volume")]
    [Required]
    public string PreSellVolume { get; set; }

    [Column("description")]
    [Required]
    public string Description { get; set; }

    [Column("title")]
    [Required]
    public string Title { get; set; }

    [ForeignKey("CatalogGroupId")]
    public virtual CatalogGroup CatalogGroup { get; set; }

    [Column("catalog_group_id")]
    public int CatalogGroupId { get; set; }

    [Column("attributes", TypeName = "json")]
    public string Attributes { get; set; }

    public static void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CatalogMetadata>(missingProductDetails =>
        {
            missingProductDetails.HasOne(p => p.CatalogGroup).WithMany(g => g.CatalogMetadata).IsRequired();
            missingProductDetails
                .ToTable("catalog_metadata")
                .HasKey(k => k.Id)
                .HasName("pk_catalog_metadata");
            missingProductDetails.ToTable("catalog_metadata").HasIndex(p => p.ProductCode).IsUnique();
        });
    }
}
```

### Steps to reproduce
Prior to upgrading to .Net Core 2.1.1 the following test was passing. 
```C#
public async Task VerifyCatalogGroupDelete_Throws_InvalidOperationException_When_There_Are_Dependencies()
{
    var options = new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase("delete_cataloggroup_invalidoperationexception").Options;

    using (var context = new AppDbContext(options))
    {
        var repository = new CatalogMetadataRepository(context);

        CatalogMetadata metadata = repository.CreateCatalogMetadata(new CatalogMetadata()
        {
            ProductCode = "testProductCode",
            Description = "testProductDescription",
            Title = "testTitle",
            CatalogGroup = new CatalogGroup()
            {
                GroupName = "testGroupName",
                GroupDescription = "testGroupDescription",
                CatalogCategory = new CatalogCategory()
                {
                    CategoryId = 1,
                    CategoryName = "testCategoryName",
                },
            },
        });

        Assert.True(metadata.CatalogGroupId > 0);

        Assert.Throws<InvalidOperationException>(() => repository.DeleteCatalogGroup(metadata.CatalogGroupId));
    }
}
```
Now it fails with the following error
```
Message: Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   (No exception was thrown)
```

### Further technical details
Source Code: https://github.com/nishantkagrawal/EFCoreIssue
Master branch has .Net Core 2.0 code and Core2.1 branch has 2.1.1 code
EF Core version: 2.1.1
Database Provider: 
IDE:  Visual Studio 2017 15.7.4

Also what is the best use of DeleteBehavior in this case?

**Comment by ajcvickers** [comment] 2018-06-29 16:46
@nishantkagrawal Can you explain why the exception is the correct behavior?

**Comment by nishantkagrawal** [comment] 2018-06-30 08:55
because of these lines
```
catalogCategories.HasMany(p => p.CatalogGroups).WithOne(g => g.CatalogCategory).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_group_category_category_id");
catalogCategories.HasMany(p => p.CatalogDiscounts).WithOne(g => g.CatalogCategory).OnDelete(DeleteBehavior.Restrict).HasConstraintName("fk_discount_category_category_id");
```

**Comment by ajcvickers** [comment] 2018-07-02 21:39
Note for triage: This is failing due to changes made in https://github.com/aspnet/EntityFrameworkCore/pull/10941 which was a bug fix to stop the state manager being overly aggressive at assuming that a constraint violation exists. Instead, we let the database decide whether there is a violation or not. However, in this case the in-memory database is being used, which doesn't do referential constraint checking--issue #2166.

**Comment by ajcvickers** [comment] 2018-07-06 20:01
Closing this as duplicate of #2166, since the in-memory database should be checking the constraint here.

**Closed** 2022-10-16 13:16 UTC
Labels: regression, customer-reported
