### ISSUE TITLE
Query: Support 'is' keyword as alternative to OfType for inheritance

### ISSUE THREAD

**Issue by wdnijdam** [dotnet/efcore#4070] opened 2015-12-14 14:25 UTC
EF7 7.0.0-rc1 does not filter when using IsOfType:

`var yy = db.Items.Where(i => i is ItemA).ToList();`

translates to

```
SELECT [i].[ItemId], [i].[ItemType], [i].[PropA], [i].[PropB], [i].[PropC]
FROM [Item] AS [i]
WHERE [i].[ItemType] IN ('C', 'B', 'A')
```

while 

`var aItems = db.Items.OfType<ItemA>().ToList();`

translates to 

```
SELECT [i].[ItemId], [i].[ItemType], [i].[PropA], [i].[PropB], [i].[PropC]
FROM [Item] AS [i]
WHERE [i].[ItemType] = 'A'
```

The first statement should only allow 'A' as discrimintor value in the SQL statement. Here filtering occurs client-side. The result set is fine but pulls too much data from the SQL server.

**Comment by rowanmiller** [comment] 2015-12-22 23:15
**Note for triage** we were going to put this on the backlog, but I just tried it on the latest nightly and it actually throws now (rather than client eval). I confirmed it did work with client eval on RC1. I think it is still probably ok to go on backlog (since it's not a pattern we intended to support), but we should discuss again.

> Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.Data.Entity.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
   at Microsoft.Data.Entity.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
   at Microsoft.Data.Entity.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
   at Microsoft.Data.Entity.Query.Internal.ExpressionEqualityComparer.GetHashCode[T](IList`1 expressions)
   at Microsoft.Data.Entity.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
   at Microsoft.Data.Entity.Query.CompiledQueryCacheKeyGenerator.CompiledQueryCacheKey.GetHashCode()
   at Microsoft.Data.Entity.Query.Internal.RelationalCompiledQueryCacheKeyGenerator.RelationalCompiledQueryCacheKey.GetHashCode()
   at Microsoft.Data.Entity.Query.Internal.SqlServerCompiledQueryCacheKeyGenerator.SqlServerCompiledQueryCacheKey.GetHashCode()
   at System.Collections.Generic.ObjectEqualityComparer`1.GetHashCode(T obj)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.Extensions.Caching.Memory.MemoryCache.Set(Object key, Object value, MemoryCacheEntryOptions cacheEntryOptions)
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.Set[TItem](IMemoryCache cache, Object key, TItem value)
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

**Comment by wdnijdam** [comment] 2015-12-23 16:55
Rowan,

I use the construction .Where(x => x is DerivedY) in list screens. We need a way to filter on type without casting to that type.

For example we want all items that are of type TypeA or of type TypeB we could write:
               .Where(x => x is TypeA || x is TypeB)

This can be used in EF6 but not in EF7 at this moment.

Van: Rowan Miller [mailto:notifications@github.com]
Verzonden: woensdag 23 december 2015 0:16
Aan: aspnet/EntityFramework <EntityFramework@noreply.github.com>
CC: Willem-Derk Nijdam - GlasOperator <w.nijdam@glasoperator.nl>
Onderwerp: Re: [EntityFramework] TPH Where filter not working for TypeIs lambda (#4070)


Note for triage we were going to put this on the backlog, but I just tried it on the latest nightly and it actually throws now (rather than client eval). I confirmed it did work with client eval on RC1. I think it is still probably ok to go on backlog (since it's not a pattern we intended to support), but we should discuss again.

Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
at Microsoft.Data.Entity.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
at Microsoft.Data.Entity.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
at Microsoft.Data.Entity.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
at Microsoft.Data.Entity.Query.Internal.ExpressionEqualityComparer.GetHashCodeT<IList%601%20expressions>
at Microsoft.Data.Entity.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
at Microsoft.Data.Entity.Query.CompiledQueryCacheKeyGenerator.CompiledQueryCacheKey.GetHashCode()
at Microsoft.Data.Entity.Query.Internal.RelationalCompiledQueryCacheKeyGenerator.RelationalCompiledQueryCacheKey.GetHashCode()
at Microsoft.Data.Entity.Query.Internal.SqlServerCompiledQueryCacheKeyGenerator.SqlServerCompiledQueryCacheKey.GetHashCode()
at System.Collections.Generic.ObjectEqualityComparer1.GetHashCode(T obj)
at System.Collections.Generic.Dictionary2.Insert(TKey key, TValue value, Boolean add)
at Microsoft.Extensions.Caching.Memory.MemoryCache.Set(Object key, Object value, MemoryCacheEntryOptions cacheEntryOptions)
at Microsoft.Extensions.Caching.Memory.CacheExtensions.SetTItem<IMemoryCache%20cache,%20Object%20key,%20TItem%20value>
at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQueryTResult<Object%20cacheKey,%20Func%601%20compiler>
at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQueryTResult<Expression%20query>
at Microsoft.Data.Entity.Query.Internal.QueryCompiler.ExecuteTResult<Expression%20query>
at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.ExecuteTResult<Expression%20expression>
at Remotion.Linq.QueryableBase1.GetEnumerator()
at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)

**Comment by multiarc** [comment] 2016-05-19 14:10
@rowanmiller on the System.NotImplementedException above, actually failing all the time in RC2 release when expression contains any InvocationExpression, someone forget peace of code like this:
```csharp
case ExpressionType.Invoke:
{
    var invocationExpression = (InvocationExpression)obj;
    for (var i = 0; i< invocationExpression.Arguments.Count; i++)
    {
        hashCode += (hashCode * 397) ^ GetHashCode(invocationExpression.Arguments[i]);
    }
    hashCode += (hashCode * 397) ^ GetHashCode(invocationExpression.Expression);
    break;
}
```
I'll create new issue, seems it's still not fixed in latest builds.

**Comment by smitpatel** [comment] 2016-06-16 00:00
dupe of #5007

**Closed** 2022-10-16 09:20 UTC
Labels: type-enhancement
