### ISSUE TITLE
dotnet ef tool isn't working with dotnet-sdk-6.0.100-preview.5.21281.3-osx-arm64.pkg

### ISSUE THREAD

**Issue by grinay** [dotnet/efcore#25020] opened 2021-06-02 10:48 UTC
Hello. Can you help to figure it out. I'm trying to do a migration. But problem is that dotnet ef tool isn't working.
I have installed dotnet-sdk-6.0.100-preview.5.21281.3-osx-arm64.pkg version. And separatly trying to install different version of dotnet-ef version 5 and 6-preview, but nether work. Basically, when you type dotnet ef command, it seems runs and interrupts immediately without any outputs and errors.  What can I do to find the issue?
and command 
`dotnet tool list` return empty list, but dotnet-ef in fact installed and in my home .dotnet/tool directory

**Comment by AndriySvyryd** [comment] 2021-06-04 17:15
cc: @bricelam

**Comment by bricelam** [comment] 2021-06-04 20:28
Can you share the output of `dotnet --info`?

**Comment by AndriySvyryd** [comment] 2021-06-12 00:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:36 UTC
Labels: closed-could-not-reproduce, customer-reported
