### ISSUE TITLE
Error when web deploy to azure an application with EF on Visual Studio 2017

### ISSUE THREAD

**Issue by felipemmasan** [dotnet/efcore#7945] opened 2017-03-21 18:21 UTC
When I try to do a publish to azure of my app, visual studio shows the erro bellow:

Generating Entity framework SQL Scripts...
Executing command: dotnet ef migrations script --idempotent --output "C:\Users\felipe.m.santos\Desktop\Estudo\masonweb\src\masonweb\obj\Release\netcoreapp1.0\PubTmp\EFSQLScripts\masonweb.Models.masonwebdbContext.sql" --context masonweb.Models.masonwebdbContext
Entity framework SQL Script generation failed

**Comment by smitpatel** [comment] 2017-03-21 19:16
Can you run the command with verbose flag?

**Comment by felipemmasan** [comment] 2017-03-22 13:09
I'm not running the command. I just push the right button on the project and click on "publish"


![part3](https://cloud.githubusercontent.com/assets/19172005/24199247/95b3283c-0ee7-11e7-9abc-51f25f8ba0da.png)
![part4](https://cloud.githubusercontent.com/assets/19172005/24199249/95c96926-0ee7-11e7-928a-bcf6e92f245f.png)
![part1](https://cloud.githubusercontent.com/assets/19172005/24199251/95d11752-0ee7-11e7-9501-ec9592e630c4.png)
![part2](https://cloud.githubusercontent.com/assets/19172005/24199252/95de7d48-0ee7-11e7-9d47-e897ca64332a.png)



"

**Comment by smitpatel** [comment] 2017-03-22 14:34
As the publish step just runs bunch of commands only under the hood,
Can you run `dotnet ef migrations script --idempotent --context masonweb.Models.masonwebdbContext --verbose` from the folder `src\masonweb`? That would give more insight on why script generation is failing.

**Comment by felipemmasan** [comment] 2017-03-22 14:48
Result:
![image](https://cloud.githubusercontent.com/assets/19172005/24203798/789e669a-0ef5-11e7-8f1a-c305c6a5e686.png)

**Comment by smitpatel** [comment] 2017-03-22 14:57
Can you specify a different & valid output path while running command? That directory may not be available if not run as a part of publish step.

**Comment by felipemmasan** [comment] 2017-03-22 15:14
I created the folder "EFSQLScripts" and the command executed successfully. I did a test and I was able to publish through visual studio.

I only had one question, despite having deselected the "Apply this migration on publish" option, visual studio still executes this command. Should visual studio not stop running?

![image](https://cloud.githubusercontent.com/assets/19172005/24205077/235ddaae-0ef9-11e7-86de-8bc7dea1d8bb.png)

**Comment by smitpatel** [comment] 2017-03-22 15:24
@bricelam - For insights on tooling. Do we generate migration script even if we are not applying migrations on publish through publish wizard?

**Comment by bricelam** [comment] 2017-03-22 16:53
It shouldn't, but you'd have to double check with the team

**Comment by smitpatel** [comment] 2017-03-22 17:00
There are 2 issues here
1. EF is not creating the folder in which the output SQL script is stored. Hence `migrations script` fails to execute successfully.

2. Verify behavior if `Apply this migration on publish` is deselected then migrations script is not executed.

**Comment by ajcvickers** [comment] 2017-03-27 16:28
Assigning to @bricelam to create the folder into which the SQL Script is stored (or to push back if this is something EF shouldn't be doing.)

(We will also need to follow up with Smit's second point, but no issue for that as yet.)

**Comment by bricelam** [comment] 2017-03-30 19:03
Dupe of #5535 (fixed in 1.0.0-preview4)

**Comment by bricelam** [comment] 2017-03-31 15:54
@felipemmasan please re-open if you're still seeing this on the latest release of the tooling.

**Comment by edgarssults** [comment] 2019-10-18 11:15
I had the same error recently when trying to publish a .NET Core 2.2 app with VS 2019.

I fixed it by running 

> dotnet tool install --global dotnet-ef

**Comment by philipstratford** [comment] 2020-04-08 17:17
I'm seeing this error in VS 2019 Community (16.5.3). Haven't had any issues publishing this application until today, having updated VS this morning. The solution suggested by @edgarssults didn't work for me.

**Comment by ojorma** [comment] 2020-05-15 11:16
has anyone been able to resolve this

**Comment by woaksie** [comment] 2021-02-24 00:26
I am getting this error today with the latest VS. I don't have a SQL database and I have a custom AuthenticationStateProvider that does not use a database. Works locally but errors out when I FTP publish

![image](https://user-images.githubusercontent.com/571181/108926725-d3738c80-75f3-11eb-9d6c-be4bf7491bfb.png)

**Closed** 2022-10-16 10:57 UTC
Labels: closed-duplicate, customer-reported

**Comment by furkan-tufan** [comment] 2022-11-18 11:03
> I had the same error recently when trying to publish a .NET Core 2.2 app with VS 2019.
> 
> I fixed it by running
> 
> > dotnet tool install --global dotnet-ef

you are hero bro
