### ISSUE TITLE
EF Core 7 incorrectly detects circular dependency

### ISSUE THREAD

**Issue by Ando** [dotnet/efcore#30689] opened 2023-04-14 09:20 UTC
#### Situation:
* EF Core 7.0.5.
* Oracle driver (but the error occurs before a query is generated, so I suppose the driver does not matter?).
* A parent entity.
* An abstract child entity with two separate implementations (TBH).
   - One implementation is linked many-to-one to the parent.
   - The other is linked one-to-one to the parent (the child references the parent, not the other way around).

```cs
// Parent entity
public class Person
{
    
    [Key]
    public long Id { get; set; }

    public List<CommonAttribute> Common { get; } = new List<CommonAttribute>();
    
    public UniqueAttribute? Unique { get; set; }

}

public enum AttributeType 
{
    Common,
    Unique
}

// Abstract child entity
public abstract class Attribute
{
    
    [Key]
    public long Id { get; set; }

    public AttributeType Type { get; set; }

    public long PersonId { get; set; }
    public Person Person { get; set; }

}

public class CommonAttribute : Attribute
{
}

public class UniqueAttribute : Attribute
{
}

// Configuration
modelBuilder.Entity<Attribute>()
    .HasDiscriminator(e => e.Type)
    .HasValue<CommonAttribute >(AttributeType.Common)
    .HasValue<UniqueAttribute >(AttributeType.Unique);

modelBuilder.Entity<Person>()
    .HasMany(e => e.Common)
    .WithOne(e => e.Person)
    .HasForeignKey(e => e.PersonId);

modelBuilder.Entity<Person>()
    .HasOne(e => e.Unique)
    .WithOne(e => e.Person)
    .HasForeignKey<UniqueAttribute>(e => e.PersonId);
```

#### Problem:
When modifying two entities of the CommonAttribute type, and saving the changes. The following error occurs:

> Unable to save changes because a circular dependency was detected in the data to be saved

Curious enough, when modifying only one CommonAttribute and saving, saving goes as expected.

When testing with EF Core 6, the entities were saved successfully. So I suppose this is a regression.

**Comment by AndriySvyryd** [comment] 2023-04-14 19:37
This should be fixed in 7.0.6
Dupe of https://github.com/dotnet/efcore/issues/30601

**Closed by AndriySvyryd** 2023-04-14 19:37 UTC
Labels: customer-reported
