### ISSUE TITLE
Remove-migration on TFVC workspace does not revert Adds

### ISSUE THREAD

**Issue by Tarig0** [dotnet/efcore#9867] opened 2017-09-21 14:01 UTC
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: Object reference not set to an instance of an object.
Stack trace: at Microsoft.EntityFrameworkCore.Tools.Json.Escape(String text)
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsRemoveCommand.ReportJsonResults(IDictionary result)
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsRemoveCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
```

### Steps to reproduce
Create TFVC bound project
Create dbcontext with any entity
Run the add-migration init command
Run the remove-migration command
Observe the Files are still in an Add State

### Further technical details
EF Core version: 2.0.0
Operating system: Windows 10
IDE:  Visual Studio 2017

**Comment by smitpatel** [comment] 2017-09-21 20:42
Duplicate of #9280

**Closed** 2022-10-16 11:50 UTC
Labels: closed-duplicate
