### ISSUE TITLE
Is there a way to filter on converted columns?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/efcore#18817] opened 2019-11-07 09:28 UTC
Hi,

I was wondering if there is a way to search on a converted column.
I have my custom type "YearMonth", which is the year and month only of a date, and is converted to and from a string.
Will EF Core translate my queries on this column, so that they're represented as string in the DB?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03dfe9f6-e831-ac3f-0b90-acb9b4c0f828
* Version Independent ID: a26156d1-a4b3-7df0-e63e-b8e9f804abbf
* Content: [Value Conversions - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions#limitations)
* Content Source: [entity-framework/core/modeling/value-conversions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/value-conversions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2019-11-08 17:20
Duplicate of #10434

**Closed** 2022-10-16 14:55 UTC
Labels: customer-reported
