### ISSUE TITLE
Seed values for entity with enum Id is re-created in each migration

### ISSUE THREAD

**Issue by artemvalmus** [dotnet/efcore#13792] opened 2018-10-28 08:22 UTC
If I have an entity with Id column declared as enum, seed values are re-created in each migration but nothing was changed. In the following console application in each transaction data for GeneralSetting table is removed and re-inserted.

```c#
namespace Test
{
    public enum GeneralSettingId
    {
        [Description("First")]
        First = 1,

        [Description("Second")]
        Second,

        [Description("Third")]
        Third
    }

    public class GeneralSetting
    {
        public GeneralSettingId Id { get; set; }

        public string Value { get; set; }
    }

    public class Context : DbContext
    {
        public Context()
        {
            Database.Migrate();
        }

        public DbSet<GeneralSetting> GeneralSettings { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(
                "Server=(localdb)\\MSSQLLocalDB;Database=Test;Trusted_Connection=True");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var generalSettingIds = Enum.GetValues(typeof(GeneralSettingId)).Cast<GeneralSettingId>();

            var generalSettings = generalSettingIds.Select(x => new GeneralSetting
            {
                Id = x,
                Value = x.GetType()
                    .GetMember(x.ToString())[0]
                        .GetCustomAttributes(typeof(DescriptionAttribute), false)
                            .Cast<DescriptionAttribute>()
                            .First()
                                .Description
            }).ToArray();

            modelBuilder.Entity<GeneralSetting>().HasData(generalSettings);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new Context())
            {
                var values = ctx.GeneralSettings.ToList();

                foreach (var item in values)
                {
                    Console.WriteLine(item.Value);
                }
            }

            Console.ReadKey();
        }
    }
}
```

EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.6

**Comment by ajcvickers** [comment] 2018-10-28 16:04
Duplicate of #12194, which is fixed in 2.2

**Closed** 2022-10-16 13:37 UTC
Labels: customer-reported
