### ISSUE TITLE
EFcore database caching 

### ISSUE THREAD

**Issue by kishoretvk** [dotnet/efcore#11732] opened 2018-04-19 00:18 UTC
Describe what is not working as expected.
after adding, db conext and db repository as transient, sometimes efcore doesnot get latest data from db.
If you are seeing an exception, include the full exceptions details (message and stack trace).
"no record found or null data from db"
```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.
in the db registration

services.AddDbContext<ApplicationDbContext>(options =>
         options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")), 
         ServiceLifetime.Transient);

db repository as 
            services.AddTransient<IHorseService, HorseService>();

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system:  windows 10 
IDE: (e.g. Visual Studio 2017 15.4) visul studio 2017

More Details: 

when I registered dbcontext and repository as adscopped, the db refresh issue was very evident, but later i made dbcontext as addtransient, i was able to reduce the occurance of the database caching less frequent, now, i made both repo and context as addtransient. 
however, i wounder what would it really make efcore to get a table from db as fresh as possible. 
by the way, I also use asnotracking on each query i make. 
i've two applications from the first one i insert records and from second i try to check if they ar present. 
application 1: aspnet mvc ef 6
applicatio 2: aspnet mvc core ef core 2.0

**Comment by ajcvickers** [comment] 2018-04-19 01:01
@kishoretvk With a no-tracking query EF will always query the database directly and does not cache any of the results. If you are seeing something different than this, then can you please put together a runnable project/solution or full code listing that exhibits the behavior so that we can investigate. Unfortunately, the partial information provided above is not enough for us to be able to reproduce the issue.

**Comment by ajcvickers** [comment] 2018-04-25 18:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:19 UTC
Labels: closed-could-not-reproduce
