### ISSUE TITLE
InMemory provider does not use value converters

### ISSUE THREAD

**Issue by dziedrius** [dotnet/efcore#20647] opened 2020-04-15 15:01 UTC
I'm using 3.1.2 version of Microsoft.EntityFrameworkCore.InMemory and found out, that it does not use value converters.

Now interestingly enough, I see pull request, that addresses the issue and that is merged into master: 
https://github.com/dotnet/efcore/pull/19417

And I see code in master branch (line 33:34):
https://github.com/dotnet/efcore/blob/master/src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs

But I don't see that in release/3.1 branch:
https://github.com/dotnet/efcore/blob/release/3.1/src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs

To be fair, I'm not sure from which branch you're building releases, but fact is, that in decompiled 3.1.2 dll I don't see it (haven't checked 3.1.3, but in release notes I don't see a fit that would address it).

**Comment by smitpatel** [comment] 2020-04-15 15:03
Refer to the issue referenced in the PR #14042 It is fixed in 5.0.0-preview1

**Comment by ajcvickers** [comment] 2020-04-15 16:57
Duplicate of #14042

**Closed** 2022-10-16 18:20 UTC
Labels: closed-duplicate, customer-reported
