### ISSUE TITLE
Don't build the whole solution when using the command line tools

### ISSUE THREAD

**Issue by CyrilPaulus** [dotnet/efcore#33850] opened 2024-05-30 06:03 UTC
When using Visual Studio's command line tools, the entire solution is rebuilt each time. 

For example, running:

```sh
Update-Database
Add-Migration NewMigration
Remove-Migration 
...
```

will build the whole solution, even if the startup project is set to only the project containing the migrations.

- The build process can take a considerable amount of time if the solution is large, especially if many projects depend on the data project.
- If any project in the solution fails to compile, the entire build will fail, causing the tool to fail as well.

Ideally, when running any of these tools, only the targeted project should be rebuilt. I believe this was the behavior with EF6 on the .NET Framework.

Is this possible?

**Comment by ajcvickers** [comment] 2024-05-30 08:20
Duplicate of #9716

**Closed by ajcvickers** 2024-05-30 08:20 UTC
Labels: customer-reported
