### ISSUE TITLE
Circular dependency was detected in the data to be saved

### ISSUE THREAD

**Issue by gokhanabatay** [dotnet/efcore#30093] opened 2023-01-18 22:22 UTC
Exception: Unable to save changes because a circular dependency was detected in the data to be saved:
'MrcMerchant { 'Guid': 3111111112203472 } [Added] <-
ForeignKeyConstraint { 'merchant_guid': 3111111112203472 } MrcMerchantAddress { 'Guid': 3111111112203474 } [Added] <-
ForeignKeyConstraint { 'default_address_guid': 3111111112203474 } MrcMerchant { 'Guid': 3111111112203472 } [Added]'.

Why circular its same address instance with the same uniq id. "3111111112203474".  If I remove `MrcMerchant.MrcMerchantAddress ` then its ok but we need to get default merchant address through merchant.

If I can map `MrcMerchantAddress.MrcMerchant` both has many and has one relation on `MrcMerchant` side may be ef core could detect its not circular but ef does not allow one property to be mapped both has one and has many relation. 

I think same class with different properties could be mapped without an issue its major feature, we are struggling to convert nhibernate 5.4 to ef core 7.

```c#
public class MrcMerchant
{

    public long Guid {get;set;}
    public long DefaultAddressGuid {get;set;}
    public MrcMerchantAddress MrcMerchantAddress {get;set;}
    public List<MrcMerchantAddress> MrcMerchantAddresses {get;set;}
}

public class MrcMerchantAddress
{
  public long Guid {get;set;}
  public MrcMerchant MrcMerchant {get;set;}
  public string AddressLine {get;set;}
}
```

**Comment by ajcvickers** [comment] 2023-01-25 21:41
Duplicate of #1699.

@gokhanabatay It's a cycle because `MrcMerchantAddresses` has a foreign key to `MrcMerchants` and `MrcMerchants` has a foreign key to `MrcMerchantAddresses`. This means which ever row is inserted first will generate a constraint violation. This could be handled by first inserting one side or the other with a null FK value, then inserting the other side, then updating the FK on the first side to the correct value. This is tracked by #1699.

**Closed** 2023-01-27 13:13 UTC
Labels: closed-duplicate, customer-reported
