### ISSUE TITLE
Unable to load mod_spatialite extension into sqlite connection on .NET 7

### ISSUE THREAD

**Issue by sokolik745** [dotnet/efcore#30051] opened 2023-01-13 10:38 UTC
I am trying to load spatialite to sqlite connection (in memory db) and it is failing with strange error without any message: `Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 1: ''.'`

I isolated the problem to this short console app example:

```C#
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore.Infrastructure;

var connection = new SqliteConnection("DataSource=:memory:");
connection.Open();
connection.EnableExtensions();

SpatialiteLoader.Load(connection);

Console.ReadKey();
```

Project file looks like this:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="7.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.2" />
  </ItemGroup>

</Project>
```
Downgrade of packages did not help. I tried the workaround mentioned [here](https://learn.microsoft.com/en-us/ef/core/providers/sqlite/spatial%5C) but I am not able to get it work.

Microsoft.Data.Sqlite version: 7.0.2.0
Target framework: .NET 7
Operating system: Windows

**Comment by ajcvickers** [comment] 2023-01-13 12:18
Duplicate of #29584

**Closed** 2023-01-18 20:22 UTC
Labels: customer-reported, area-adonet-sqlite
