### ISSUE TITLE
ExecuteUpdate is not committing transactions even if included in an explicit transaction

### ISSUE THREAD

**Issue by theunstablemind** [dotnet/efcore#29578] opened 2022-11-16 04:08 UTC
I am running ef core v7 in a dotnet core v7 environment.

I am attempting to update several database records in a single statement using the new ExecuteUpdate functionality. My code looks like this.

```C#
                    using var transaction = DbContext.Database.BeginTransaction();

                    try
                    {
                        DbContext.ReservationDetails.Where(x => x.ReservationPetId.Equals(pet.Id) && x.AppointmentId.Equals(boarding.Id) && x.AppointmentServiceId == null)
                            .ExecuteUpdate(u => u.SetProperty(p => p.RoomId, p => roomId));
                        transaction.Commit();
                    }
                    catch
                    {
                        transaction.Rollback();
                    }
```

If I set a breakpoint and check the reservation details table, it appears the records have been updated. However, in my loop, the roomId that was set should no longer be available, though it is.

That said, if I update the reservation details table with this code:

```C#
var details = DbContext.ReservationDetails.Where(x => x.ReservationPetId.Equals(pet.Id) && x.AppointmentId.Equals(boarding.Id) && x.AppointmentServiceId == null).ToList();

                    details.ForEach(detail =>
                    {
                        detail.RoomId = roomId;
                        DbContext.ReservationDetails.Update(detail);
                    });
                    DbContext.SaveChanges();'
```

It works just fine.

**Comment by ajcvickers** [comment] 2022-11-16 09:11
@theunstablemind Can you explain more what this means:

> However, in my loop, the roomId that was set should no longer be available, though it is.

**Comment by theunstablemind** [comment] 2022-11-16 14:00
I have a loop in which I am processing reservations. In that loop, I look for available rooms, select one, and then assign it to the reservation. However, it is possible there is more than one pet on the reservation, but they cannot be boarded separately.

So, I assign the room and then look for available rooms again. That process looks at the assigned rooms in reservation details. Since one room has been assigned in the first iteration, it should not be available in the second. However, using ExecuteUpdate it is. Using DbContext.Update it is not.

**Comment by ajcvickers** [comment] 2022-11-16 15:48
@theunstablemind This description is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-11-23 13:11
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-11-23 13:11 UTC
Labels: customer-reported
