### ISSUE TITLE
OrderBy throws on projection to record type

### ISSUE THREAD

**Issue by JelleKerkstra** [dotnet/efcore#30325] opened 2023-02-23 07:28 UTC
After migrating from 3.1.14 to 7.0.3, OrderBy on a projection to a record type throws an InvalidOperationException.

### Code

```C#
public class Source
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public record ViewModel(int Id, string Name);

public class MyContext : DbContext
{
    public DbSet<Source> Sources { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Server=(local);Database=test;Integrated Security=True;Trust Server Certificate=True");
}

using (var context = new MyContext())
{
    await context.Sources.Select(s => new ViewModel(s.Id, s.Name)).OrderBy(vm => vm.Name).ToListAsync();
}
```

### Exception

```
Message: 
System.InvalidOperationException : The LINQ expression 'DbSet<Source>()
    .OrderBy(s => new ViewModel(
        s.Id, 
        s.Name
    ).Name)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

Stack Trace: 
QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0&)
QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
Database.CompileQuery[TResult](Expression query, Boolean async)
QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

### Provider and version information

EF Core version: 7.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Microsoft Windows 10 Enterprise 10.0.19044 Build 19044
IDE: Visual Studio 2022 17.4.5

**Comment by roji** [comment] 2023-02-23 09:17
By design, EF doesn't translate constructor invocations with parameters; looking at `new ViewModel(s.Id, s.Name)`, EF can't really know what the constructor implementation will do, e.g. which instance members will be initialized with which constructor argument, whether any transformations will take place on the arguments, etc.

You can still instantiate your own types as long as you use a parameterless constructor, and then use initializers:

```c#
public record ViewModel
{
    public int Id { get; init; }
    public string Name { get; init; }
}

await ctx.Sources.Select(s => new ViewModel { Id = s.Id, Name = s.Name }).OrderBy(vm => vm.Name).ToListAsync();
```

In theory, if EF could detect that the type is a record with an implicit primary constructor, it could make sense to allow this, assuming that the members are indeed assigned directly as per the constructor arguments; but I don't think there's a way for EF to know that.

**Comment by mycroes** [comment] 2023-02-23 10:26
I was actually expecting the `NewExpression` for records to be similar to those for anonymous types, where `Members` are included in the expression, but alas.

Anyway, the way to detect this would be as follows:
```
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;
using Shouldly;
					
public class Program
{
	public static void Main()
	{
		Expression<Func<Sample>> ex = () => new Sample(1, 2);

		var ne = ex.Body.ShouldBeOfType<NewExpression>().ShouldNotBeNull();
		var parameters = ne.Constructor.GetParameters();
		parameters.Length.ShouldBe(2);
		parameters.ShouldAllBe((p => 
			typeof(Sample).GetProperty(p.Name).SetMethod.ReturnParameter.GetRequiredCustomModifiers().Contains(typeof(IsExternalInit))
		));
		
		Console.WriteLine("Success");
	}
}

public record Sample(int X, int Y);
```
Or on dotnetfiddle: https://dotnetfiddle.net/4gHhKh.

The question is whether this is relevant at all though. It's possible to use normal properties in records which don't get the attributes and they can still be set through ctor as well. It does intrigue me that this was working in older EF Core versions, I can only guess it used to lookup properties by constructor argument names back then as well....

**Comment by mycroes** [comment] 2023-02-23 14:49
> @mycroes I'm not sure how reliable this method is, i.e. how dependable/documented it is that the presence of IsExternalInit on all constructor parameters necessarily means that it's an implicit primary constructor (i.e. with no possible user tweakability).

I'm not sure either, but more importantly I guess it doesn't make sense to support that and don't support additional properties that are set through the constructor. I guess in that case it would be better to support it based on naming convention than only for records with primary constructors.

> Which version of EF was this working on? If it's very old versions (pre-3.0), this may have simply been client-evaluated. Otherwise, it would be good to see some code showing that.

I was quite sure it was working with 3.1, but when I tried to test it and wanted to extract the SQL query I noticed it only works with `UseInMemoryDatabase(...)`, with `UseSqlServer(...)` the exact same exception is thrown.

I quickly hacked together an `ExpressionVisitor` that fills the `Members` collection, that does make it work:
```
public class RecordProjectionTests
{
    private readonly ITestOutputHelper output;

    public RecordProjectionTests(ITestOutputHelper output)
    {
        this.output = output;
    }

    [Fact]
    public async Task ProjectToRecordAndOrder()
    {
        var dbContextOptions = new DbContextOptionsBuilder<SampleDbContext>().UseSqlServer(
            $"Server=(localdb)\\mssqllocaldb;Database={Guid.NewGuid()};Trusted_Connection=True").Options;

        await using var db = new SampleDbContext(dbContextOptions);
        await db.Database.EnsureCreatedAsync();
        var query = db.Entities.Select(x => new Projection(x.Id, x.Name)).OrderBy(x => x.Name);
        query =
            query.Provider.CreateQuery(new NewExpressionMemberSetterVisitor().Visit(query.Expression)) as
                IOrderedQueryable<Projection>;
        output.WriteLine(query.ToSql());
        await query.ToListAsync();
    }
}

public static class Extensions
{
    public static string ToSql<TEntity>(this IQueryable<TEntity> query) where TEntity : class
    {
        using var enumerator = query.Provider.Execute<IEnumerable<TEntity>>(query.Expression).GetEnumerator();
        var relationalCommandCache = enumerator.Private("_relationalCommandCache");
        var selectExpression = relationalCommandCache.Private<SelectExpression>("_selectExpression");
        var factory = relationalCommandCache.Private<IQuerySqlGeneratorFactory>("_querySqlGeneratorFactory");

        var sqlGenerator = factory.Create();
        var command = sqlGenerator.GetCommand(selectExpression);

        string sql = command.CommandText;
        return sql;
    }

    private static object Private(this object obj, string privateField) =>
        obj?.GetType().GetField(privateField, BindingFlags.Instance | BindingFlags.NonPublic)?.GetValue(obj);

    private static T Private<T>(this object obj, string privateField) =>
        (T)obj?.GetType().GetField(privateField, BindingFlags.Instance | BindingFlags.NonPublic)?.GetValue(obj);
}

public record Projection(int Id, string Name);

public class Entity
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class SampleDbContext : DbContext
{
    public SampleDbContext(DbContextOptions options) : base(options)
    {
    }

    public DbSet<Entity> Entities { get; set; }
}

public class NewExpressionMemberSetterVisitor : ExpressionVisitor
{
    protected override Expression VisitNew(NewExpression node)
    {
        if (node.Members != null) return base.VisitNew(node);

        var members = node.Constructor.GetParameters().Select(a => node.Type.GetProperty(a.Name!))
            .ToArray<MemberInfo>();

        return members.All(x => x is not null)
            ? Expression.New(node.Constructor, node.Arguments.Select(Visit), members)
            : base.VisitNew(node);
    }
}
```
I'm not sure if there are current extension points that would permit usage of this visitor in recent EF versions, that would at least provide a workaround for anyone searching for this behavior.

**Comment by roji** [comment] 2023-02-23 16:01
So again, the visitor you provided above seems to simply assume that if a constructor's parameters all have corresponding properties with the same name, then it's safe to assume that the constructor simply sets those properties from the parameters. That's certainly true for implicit record primary constructors, but nothing stops you from creating a type with such a constructor that does very different things. That's the reason why we don't do this by default.

From a cursory look it seems like the wiring up would still work, though we now have [query expression interception](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#new-and-improved-interceptors-and-events), which would be a more 1st-class way to do this.

**Comment by mycroes** [comment] 2023-02-23 16:15
@roji yes, what I provided is a workaround, I agree that it should not be part of EF Core. The query expression interception would probably work for applying this in a more convenient way. Thanks for your time, I have nothing more to add.

**Comment by roji** [comment] 2023-02-23 18:27
Sure thing, thanks for the code samples and discussion.

**Closed by roji** 2023-02-23 18:27 UTC
Labels: customer-reported
