### ISSUE TITLE
Collection navigation property, some items are not loaded in the model

### ISSUE THREAD

**Issue by GustavoArriola** [dotnet/efcore#20794] opened 2020-04-30 17:05 UTC
I am applying convention relationships at Entity Framework Core
![1](https://user-images.githubusercontent.com/13947325/80733017-22878880-8adb-11ea-8b2b-aa6fec821c8c.png)
![2](https://user-images.githubusercontent.com/13947325/80733023-24514c00-8adb-11ea-8dff-a3296b1be48a.png)

. When I try to load a navigation property of type "collection", some items are loaded, others are not.
I load it in the following way:
``` C#
                result = ctx.Instrumentos
                    .Include(m => m.Materia)
                    .Include(c => c.Curso)
                .Where(i => i.CreateUserId == userId && i.AnhoLectivo == anhoLectivo && i.Etapa == etapa).ToList();  
```
EFC generates the SQL query (with inner join) perfectly, and the SQL query returns the expected values (if I run the query directly in SQL Management Studio), however EFC does not load all the navigation properties correctly ( see attached files)

### Steps to reproduce

``` C#
public class Instrumento : EntityBase
    {  
        public Int64 InstrumentoId { get; set; }
        public string Seccion { get; set; }
        public string Nombre { get; set; }       
        public int AnhoLectivo { get; set; }       
        public int Etapa { get; set; }
        public Curso Curso { get; set; }
        public Materia Materia { get; set; }
    }

 public class Materia
    {
        public long MateriaId { get; set; }
        public string Nombre { get; set; }     
        [JsonIgnore]
        public List<Instrumento> Instrumentos { get; set; }
    }
public class Curso
    {
        public Int64 CursoId { get; set; }
        public String CodigoUsuario { get; set; }
        public Int64 NivelId { get; set; }
        public String Nombre { get; set; }       
        [JsonIgnore]
        public List<Instrumento> Instrumentos { get; set; }        
    }
```
Nothing in OnModelCreating () and nothing special (except logger and connection string) in OnConfiguring ().

I did not create any migration since the database already exists in production. I am just creating the models and adapting it to the current database simulating Code First.

I have tried configuring Microsoft.EntityFrameworkCore.Proxies without success.

### Further technical details

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 PRO x64
IDE: Visual Studio 2019 16.5.4
![1](https://user-images.githubusercontent.com/13947325/80733069-34692b80-8adb-11ea-8247-3cbfd866b7e4.png)
![2](https://user-images.githubusercontent.com/13947325/80733082-37fcb280-8adb-11ea-8aae-fb0b38219aa6.png)

**Comment by roji** [comment] 2020-04-30 17:42
@GustavoArriola any chance you can post a small, runnable code sample that demonstrates the issue? It's bit hard to understand what's going on from a series of screenshots...

**Comment by GustavoArriola** [comment] 2020-04-30 20:15
@roji you can go here: [https://1drv.ms/u/s!Anfap1RYoo3OjvQ7mu-JDuSRlfnScA?e=FQwKCe](url)

Best regards,
Gustavo

**Comment by roji** [comment] 2020-04-30 20:24
@GustavoArriola that URL seems to point back here. Ideally, we'd have a minimal, runnable program - not a full project with unrelated code etc.

**Comment by GustavoArriola** [comment] 2020-04-30 20:28
What I attached was just the Visual Studio template for asp.net Core, not the actual project UI. The complete project has 33 MB compressed.

**Comment by GustavoArriola** [comment] 2020-04-30 20:33
It seems that relationships are affected when the related entity is the same, that is, the same object.

**Comment by roji** [comment] 2020-04-30 20:52
@GustavoArriola please try to isolate the minimal code that creates the problem, and ideally submit that as a simple console program - a 33MB compressed project would require us to go through a lot to make it work, understand what's happening etc.

**Comment by GustavoArriola** [comment] 2020-04-30 22:46
@roji  Here is the project! I included in it, the database "neoSchool_DB_MSSQL2017.zip".

[COREConsoleApp.zip](https://github.com/dotnet/efcore/files/4561750/COREConsoleApp.zip)

**Comment by roji** [comment] 2020-05-02 11:56
@GustavoArriola I've restored your database backup and executed your program, and everything seems to work - I can't see a problem. I get back a list of 28 instances of Instrumento, including their related entities (Curso, Materia). Can you please clarify what exactly the problem is?

![image](https://user-images.githubusercontent.com/1862641/80863446-a88f0500-8c7c-11ea-8e02-16c4fad501a5.png)

**Comment by GustavoArriola** [comment] 2020-05-02 15:24
@roji Yes, at index 0 the information is loaded correctly. The same happens with index 1, however, in index 2 it does not load the Materia property. Index 8 does not load either Curso or Materia. Can you reproduce this behavior?

**Comment by roji** [comment] 2020-05-02 15:35
No, when I run your application with your database, all the Instrumentos instances have a non-null Materia reference:

```c#
var missingMateria = result.Where(i => i.Materia is null).ToList();
```

I suggest to make sure you're connecting to the right database with the right data - there may be a confusion there. If you're looking at specific indexes, it may be a good idea to add an OrderBy to make sure the order of results is determinstic as well:

```c#
result = ctx.Instrumentos
    .Include(m => m.Materia)
    .Include(c => c.Curso)
    .Where(i => i.CreateUserId == 1 && i.AnhoLectivo == 2019 && i.Etapa == 1)
    .OrderBy(i => i.InstrumentoId)
    .ToList();
```

**Comment by GustavoArriola** [comment] 2020-05-02 15:38
No, the object is not null, however the properties within it have the default .NET values, i.e. 0 (zero) for integers or null for string.

**Comment by roji** [comment] 2020-05-02 16:52
Can you please confirm whether removing the constructor for Instrumento fixes the problem for you? In other words, leave the navigation properties as null by default, rather than instantiating them to a default Materia etc.

**Comment by ralmsdeveloper** [comment] 2020-05-02 16:53
@roji I can reproduce!

**Comment by ralmsdeveloper** [comment] 2020-05-02 16:57
You will be able to reproduce when using **Tracking** and **NoTracking**.

**AsNoTracking** works well!

![image](https://user-images.githubusercontent.com/16335882/80870384-7f6e7480-8c7c-11ea-887a-0594e8d559fd.png)
![image](https://user-images.githubusercontent.com/16335882/80870408-9dd47000-8c7c-11ea-8f46-c0483913d2fe.png)

**Comment by GustavoArriola** [comment] 2020-05-02 17:02
It works!! Why **Tracking** conflicts with the constructor?

**Comment by roji** [comment] 2020-05-02 17:05
As a general rule, you should not be initializing reference navigations to default instances - this interferes with the Include/change tracking logic. I'll see with the rest of the team about improving guidance here.

**Comment by GustavoArriola** [comment] 2020-05-02 17:06
Thank you! Sorry for this incident.

**Comment by roji** [comment] 2020-05-02 17:08
No problem at all, keeping open for now to discuss possibly improving docs.

**Comment by ajcvickers** [comment] 2020-05-02 17:38
See #18007

**Comment by roji** [comment] 2020-05-02 17:42
Duplicate of #18007

**Closed** 2022-10-16 18:22 UTC
Labels: closed-duplicate, customer-reported
