### ISSUE TITLE
camelCase property names for CosmosDB

### ISSUE THREAD

**Issue by Marusyk** [dotnet/efcore#21073] opened 2020-05-28 22:13 UTC
Is there any way to serialize property names in camelCase using CosmosDB provider instead of

```
builder.Property(o => o.Id).ToJsonProperty("id")
```
to avoid this

![image](https://user-images.githubusercontent.com/9221694/83199276-8ee0c080-a149-11ea-8bb3-0e6d1b475490.png)

**Comment by ajcvickers** [comment] 2020-05-29 21:23
Duplicate of #20588. However, see the external package https://github.com/efcore/EFCore.NamingConventions which does something similar for relational names. It should be possible to either update or fork this package to do the same for Cosmos.
/cc @roji

**Closed** 2022-10-16 18:27 UTC
Labels: closed-duplicate, customer-reported

**Comment by mtnvencenzo** [comment] 2025-03-30 00:35
See here > https://github.com/dotnet/efcore/issues/28270#issuecomment-2764309401
