### ISSUE TITLE
InvalidOperationException LINQ with Join (Regression in EF Core 3.0 Preview 6)

### ISSUE THREAD

**Issue by timmi-on-rails** [dotnet/efcore#17173] opened 2019-08-15 09:51 UTC
### Regression
`3.0.0-preview5.19227.1`
no exception

`3.0.0-preview6.19304.10`
System.InvalidOperationException: Null TypeMapping in Sql Tree

`3.0.0-preview7.19362.6`
System.InvalidOperationException: CollectionJoin: Unable to identify correlation predicate to convert to Left Join

`3.0.0-preview8.19405.11`
System.InvalidOperationException: CollectionJoin: Unable to identify correlation predicate to convert to Left Join

### Exception with version `3.0.0-preview8.19405.11` 

```
$ dotnet run
Unhandled exception. System.InvalidOperationException: CollectionJoin: Unable to identify correlation predicate to convert to Left Join
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyCollectionJoin(Int32 collectionIndex, Int32 collectionId, Expression innerShaper, INavigation navigation, Type elementType)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryOptimizer.Visit(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
   at Test.Program.Main(String[] args) in C:\Users\Tom\Desktop\test\Program.cs:line 16
```

### Code and project file

Program.cs:
```c#
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new StudentDbContext())
            {
                context.Database.EnsureCreated();

                context.Students.Select(student => new StudentDto
                {
                    Courses = student.Courses.Select(course => new CourseDto())
                }).SingleOrDefault();
            }
        }
    }

    class StudentDbContext : DbContext
    {
        public DbSet<Student> Students { get; set; }

        public DbSet<Course> Courses { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            SqliteConnection connection = new SqliteConnection("DataSource=:memory:");
            connection.Open();
            optionsBuilder.UseSqlite(connection);
        }
    }

    class Student
    {
        public int Id { get; set; }
        public ICollection<Course> Courses { get; set; }
    }

    class StudentDto
    {
        public IEnumerable<CourseDto> Courses { get; set; }
    }

    class Course
    {
        public int Id { get; set; }
    }

    class CourseDto
    {
    }
}
```

Test.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.0.0-preview8.19405.11" />
  </ItemGroup>

</Project>
```

**Comment by ajcvickers** [comment] 2019-08-15 14:39
Note for triage: verified that this works with the latest [daily build](https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md).

**Comment by ajcvickers** [comment] 2019-08-16 17:36
@smitpatel to find duplicate.

**Comment by smitpatel** [comment] 2019-08-16 18:44
Duplicate of #16330

**Closed** 2022-10-16 14:35 UTC
Labels: closed-duplicate, customer-reported
