### ISSUE TITLE
InMemory query fails to find entities from a collection using Include of a detail, when the detail is null 

### ISSUE THREAD

**Issue by paulovila** [dotnet/efcore#24317] opened 2021-03-04 14:46 UTC
InMemory query fails to find entities from a collection using Include of a detail, when the detail is null.

The assertion below (last line) should be true, regardless the ```DataSource``` detail is initialised or not (on lines 6 and 9).

```C#
var  options = new DbContextOptionsBuilder<MyContext>()
                .UseInMemoryDatabase(DateTime.Now.Ticks.ToString())
                .Options;
var context = new MyContext(options);
context.DataSeriesItems.AddRange(
                new DataSeriesItem { ModelRunId = 5 },
                new DataSeriesItem { ModelRunId = 2 },
                new DataSeriesItem { ModelRunId = 5 });
await context.SaveChangesAsync();
var seriesItems = await context
   .DataSeriesItems
   .Include(w => w.DataSource) // Fails when this line is included
   .Where(w => w.ModelRunId == 5)
   .ToArrayAsync();
Assert.AreEqual(seriesItems.Count(), 2);
```

Database provider: EFCore InMemory
Target framework: .NET 5.0.3

**Comment by smitpatel** [comment] 2021-03-04 17:13
Can you share your model and db context code?

**Comment by ajcvickers** [comment] 2021-03-12 17:12
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:26 UTC
Labels: closed-could-not-reproduce, customer-reported
