### ISSUE TITLE
Different column name in derived class (TPT)

### ISSUE THREAD

**Issue by kalatchev** [dotnet/efcore#23486] opened 2020-11-26 03:34 UTC
### .HasColumnName changes key column name in whole hierarchy, instead of given class.

I use existing DB where I have tables like that:

Sales
- **ID** int IDENTITY(1, 1) NOT NULL ... PRIMARY KEY
- ... other columns ...

SalesNhif
- **SalesID** int NOT NULL ... PRIMARY KEY ... FOREIGN KEY REFERENCES Sales(ID)
- ... other columns ...

And my mapping in EF is as follows:
```C#
[Table("Sales")]
public class Sale
{
    [Key()]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public virtual int Id { get; set; }

    ... other properties ....
}

[Table("SalesNhif")]
public class SaleNhif : Sale
{
    ... other properties ....
}
```
And in ```protected override void OnModelCreating(ModelBuilder builder)``` I have

```C#
builder.Entity<Sale>()
    .Property(s => s.Id)
    .HasColumnName("ID");

builder.Entity<SaleNhif>()
    .Property(sn => sn.Id)
    .HasColumnName("SalesID");
```
And finally, on runtime, when I execute ```cont.Sales.Take(10).ToArrayAsync().Result;``` I've got (wrapped in ```exec sp_executesql```):
```SQL
SELECT TOP(@__p_0) [s].[SalesID], ... , 
CASE WHEN [s0].[SalesID] IS NOT NULL THEN N''SaleNhif'' END AS [Discriminator]
FROM [Sales] AS [s]
LEFT JOIN [SalesNhif] AS [s0] ON [s].[SalesID] = [s0].[SalesID]
```
Note **[s].[SalesID] = [s0].[SalesID]**

If I change order of setting column names as following
```C#
builder.Entity<SaleNhif>()
    .Property(sn => sn.Id)
    .HasColumnName("SalesID");

builder.Entity<Sale>()
    .Property(s => s.Id)
    .HasColumnName("ID");
```
I have opposite (again wrong)
```SQL
SELECT TOP(@__p_0) [s].[ID], ... , 
CASE WHEN [s0].[ID] IS NOT NULL THEN N''SaleNhif'' END AS [Discriminator]
FROM [Sales] AS [s]
LEFT JOIN [SalesNhif] AS [s0] ON [s].[ID] = [s0].[ID]
```
Here both column names are 'ID': **[s].[ID] = [s0].[ID]**

**I believe this is a defect, major one when in comes to work with existing databases.**

------
EF Core version: 5.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by AndriySvyryd** [comment] 2020-11-26 08:42
Duplicate of https://github.com/dotnet/efcore/issues/19811

**Closed** 2022-10-16 19:12 UTC
Labels: customer-reported
