### ISSUE TITLE
Include issue

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/efcore#12073] opened 2018-05-20 00:42 UTC
I have an issue with include.
This call isn't working. The type navigation property isn't loaded
```
GalerieIndexViewModel model = await _ctx.Galeries
        .Include(i => i.Book)
        .Include(i => i.Book.BookType)
        .Where(g => g.Id == id)
        .Select(s => new GalerieIndexViewModel
         {
          .......... removed for clarity ........
         Properties = _ctx.VisuelProperties.Include(i => i.type).Where(p => p.galerieId == id).ToList(),
         .......... removed for clarity ........
         })
         .AsNoTracking()
         .FirstOrDefaultAsync();
```
But if I extract it from the call like this:

` model.Properties = _ctx.VisuelProperties.Include(i => i.type).Where(p => p.galerieId == id).ToList();`

It works perfectly.
I assume it's not normal.

Thanks.

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 x64 April 2018 Update
IDE: Visual Studio 2017 15.7

**Comment by SSkovboiSS** [comment] 2018-05-20 09:05
Hello @JulienM28 

You should use `ThenInclude` for that. Like this:
```
GalerieIndexViewModel model = await _ctx.Galeries
        .Include(i => i.Book)
                ThenInclude(b => b.BookType)
        .Where(g => g.Id == id)
```

See more examples at https://docs.microsoft.com/en-us/ef/core/querying/related-data#including-multiple-levels

**Comment by JulienM28** [comment] 2018-05-20 09:20
Thank you for your answer, I'll do that in the future,
but the problem isn't with
```
.Include(i => i.Book)
.Include(i => i.Book.BookType)
```
The problem is with
`Properties = _ctx.VisuelProperties.Include(i => i.type).Where(p => p.galerieId == id).ToList()`

Thanks.

**Comment by ralmsdeveloper** [comment] 2018-05-20 14:58
@JulienM28 It would be good for you to share your project so that someone here can do a repro.

As @SSkovboiSS  quoted, the most correct way would be to use `ThenInclude`

**Comment by smitpatel** [comment] 2018-05-24 19:09
Duplicate of #8722

**Closed** 2022-10-16 12:25 UTC
Labels: customer-reported
