### ISSUE TITLE
InvalidCastException upon "MyType[] myArr =  DbSet<MyType>.ToArray();"

### ISSUE THREAD

**Issue by jlarnal** [dotnet/efcore#31143] opened 2023-06-26 20:36 UTC
I get a wierd InvalidCastException on this method ( I commented-out my original linq query to get the debug ouput I included later in this post ) :

```C#
public class SassyDbContext : DbContext
{
   private DbSet<SassyUser> SassyUsers { get; set; }

   public SassyUser GetUser(string uide, string pwde)
        {
            //(from usr in SassyUsers
            // where usr.PseudonymEnc == uide && usr.PasswordEnc == pwde
            // select usr).FirstOrDefault()!;
            SassyUser[] lst = SassyUsers.ToArray();  // <- InvalidCastException... what ???
            return lst[0];
        }
 }
```

Here's the debug output of EFcore :

```
dbug: 26/06/2023 21:45:07.048 CoreEventId.QueryCompilationStarting[10111] (Microsoft.EntityFrameworkCore.Query) 
      Compiling query expression: 
      'DbSet<SassyUser>()'
dbug: 26/06/2023 21:45:07.058 CoreEventId.QueryExecutionPlanned[10107] (Microsoft.EntityFrameworkCore.Query) 
      Generated query execution expression: 
      'queryContext => new SingleQueryingEnumerable<SassyUser>(
          (RelationalQueryContext)queryContext, 
          RelationalCommandCache.QueryExpression(
              Projection Mapping:
                  EmptyProjectionMember -> Dictionary<IProperty, int> { [Property: IdentifiedObjectBase.Id (long?) Required PK AfterSave:Throw ValueGenerated.OnAdd, 0], [Property: SassyUser.CreationDate (_creationDate, DateTime?) Required PropertyAccessMode.Property, 1], [Property: SassyUser.EmailEnc (string) Ansi, 2], [Property: SassyUser.FirstName (string), 3], [Property: SassyUser.GlobalPrivileges (Privileges) Required ValueGenerated.OnAdd, 4], [Property: SassyUser.LastName (string), 5], [Property: SassyUser.PasswordEnc (string) Required Ansi, 6], [Property: SassyUser.PseudonymEnc (string) Required Ansi, 7] }
              SELECT s.Id, s.CreationDate, s.email, s.FirstName, s.GlobalPrivileges, s.LastName, s.fdsqqf, s.jlgkj
              FROM SassyUsers AS s), 
          ReaderColumn[] { ReaderColumn<long>, ReaderColumn<DateTime>, ReaderColumn<object>, ReaderColumn<object>, ReaderColumn<ulong>, ReaderColumn<object>, ReaderColumn<object>, ReaderColumn<object> }, 
          Func<QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator, SassyUser>, 
          Sassy.Model.SassyDbContext, 
          False, 
          True, 
          True
      )'
dbug: 26/06/2023 21:45:07.061 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command) 
      Creating DbCommand for 'ExecuteReader'.
dbug: 26/06/2023 21:45:07.064 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command) 
      Created DbCommand for 'ExecuteReader' (3ms).
dbug: 26/06/2023 21:45:07.067 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command) 
      Initialized DbCommand for 'ExecuteReader' (5ms).
dbug: 26/06/2023 21:45:07.069 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection) 
      Opening connection to database 'sassyDb' on server 'localhost'.
dbug: 26/06/2023 21:45:07.072 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection) 
      Opened connection to database 'sassyDb' on server 'localhost'.
dbug: 26/06/2023 21:45:07.074 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `s`.`Id`, `s`.`CreationDate`, `s`.`email`, `s`.`FirstName`, `s`.`GlobalPrivileges`, `s`.`LastName`, `s`.`fdsqqf`, `s`.`jlgkj`
      FROM `SassyUsers` AS `s`
info: 26/06/2023 21:45:07.076 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `s`.`Id`, `s`.`CreationDate`, `s`.`email`, `s`.`FirstName`, `s`.`GlobalPrivileges`, `s`.`LastName`, `s`.`fdsqqf`, `s`.`jlgkj`
      FROM `SassyUsers` AS `s`
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
'SassyAssetsExporter.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.5\System.Reflection.Metadata.dll'. Symbols loaded.
fail: 26/06/2023 21:45:07.131 CoreEventId.QueryIterationFailed[10100] (Microsoft.EntityFrameworkCore.Query) 
      An exception occurred while iterating over the results of a query for context type 'Sassy.Model.SassyDbContext'.
      System.InvalidCastException: Unable to cast object of type 'Sassy.Model.SassyDataset' to type 'Sassy.Model.SassyUser'.
         at lambda_method247(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
Exception thrown: 'System.InvalidCastException' in Microsoft.EntityFrameworkCore.Relational.dll
dbug: 26/06/2023 21:45:07.162 RelationalEventId.DataReaderClosing[20301] (Microsoft.EntityFrameworkCore.Database.Command) 
      Closing data reader to 'sassyDb' on server 'localhost'.
dbug: 26/06/2023 21:45:07.164 RelationalEventId.DataReaderDisposing[20300] (Microsoft.EntityFrameworkCore.Database.Command) 
      A data reader for 'sassyDb' on server 'localhost' is being disposed after spending 83ms reading results.
dbug: 26/06/2023 21:45:07.166 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection) 
      Closing connection to database 'sassyDb' on server 'localhost'.
dbug: 26/06/2023 21:45:07.168 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection) 
      Closed connection to database 'sassyDb' on server 'localhost' (2ms).
The program '[12584] SassyAssetsExporter.exe' has exited with code 4294967295 (0xffffffff).

```

So.... a `SELECT [whichever columns] FROM SassyUsers `is expected to being cast into SassyDataset (which is another custom class entity, neither inheriting nor inherited by SassyUser... Huh ? Why ? 
What the hell happened in " lambda_method247" ? 

Provider and version information :
EF Core version: 7
Database provider: MySql + Pomelo 7.0.0
Target framework: (e.g. .NET 6.0)
Operating system: Win 10 x64
IDE: Visual Studio 2022 x64 17.5.5)

**Comment by jlarnal** [comment] 2023-06-26 23:40
I should have included the contents of the SassyUser class along with its EF Model configurator,

Here they are :

```C#
    
    public abstract class IdentifiedObjectBase : IIdentifiedObject
    {
        public long? Id { get; set; } =  null!;
    }
    
    internal class IdentifiedObjectConfig : IEntityTypeConfiguration<IdentifiedObjectBase>
    {
        public void Configure(EntityTypeBuilder<IdentifiedObjectBase> builder)
        {
            builder
                .HasKey(e => e.Id)                
                .HasAnnotation("MySql:ValueGenerationStrategy",MySqlValueGenerationStrategy.IdentityColumn);

            builder
                .UseTpcMappingStrategy();
        }
    }
```


```C#

public class SassyUser : IdentifiedObjectBase
    {
        private DateTime? _creationDate = null;
        private static readonly byte[] __ = new byte[] { 0xd2, 0xc2, 0xd6, 0xcd, 0xb0, 0x1d, 0x4b, 0x80, 
                                                                                   0xbe, 0x60, 0x54, 0x82, 0xb1, 0xfa, 0x9a, 0xc3 }; // crude scrambling salt


        public SassyUser() { }


        public string FirstName { get; set; } = string.Empty;
        public string LastName { get; set; } = string.Empty;
     
        private ICollection<AnnotatedAsset> AuthoredAssets { get; set; } = new HashSet<AnnotatedAsset>();
        private ICollection<AnnotatedAsset> RevisedAssets { get; set; } = new HashSet<AnnotatedAsset>();
        private ICollection<TraitBase> AuthoredTraits { get; set; } = new HashSet<TraitBase>();
        private ICollection<TraitBase> RevisedTraits { get; set; } = new HashSet<TraitBase>();


        private ICollection<AssetImportSession> ImportSessions { get; set; } = new HashSet<AssetImportSession>();

        public string Pseudonym { // on-demand descrambling if the encoded prop...
            get => ModelUtils.DeScrambleString(__, PseudonymEnc);
            set => PseudonymEnc = ModelUtils.ScrambleString(__, value);
        } 
        public string PseudonymEnc { get; set; } = string.Empty;



        public string Password {
            get => ModelUtils.DeScrambleString(__, PasswordEnc);
            set => PasswordEnc = ModelUtils.ScrambleString(__, value);
        }
        public string PasswordEnc { get; set; } = string.Empty;


        public string? Email {
            get => ModelUtils.DeScrambleString(__, EmailEnc!);
            set => EmailEnc = ModelUtils.ScrambleString(__, value!);
        }
        public string? EmailEnc { get; set; } = null;


        public DateTime? CreationDate {
            get {
                if (_creationDate is null)
                    _creationDate = DateTime.Now.ToUniversalTime();
                return _creationDate;
            }
            set {
                if (value is not null)
                    _creationDate = value.Value.ToUniversalTime();
            }
        }


        public Privileges GlobalPrivileges { get; set; } = Privileges.None;
    }
```



```C#
internal class SassyUserConfig : IEntityTypeConfiguration<SassyUser>
    {
        public SassyUserConfig() { }

        public void Configure(EntityTypeBuilder<SassyUser> builder)
        {
            builder.Ignore(e => e.Pseudonym);
            builder.Ignore(e => e.Password);
            builder.Ignore(e => e.Email);
            builder.Ignore("_creationDate");


            builder
                .Property(e => e.CreationDate)
                .HasField("_creationDate")
                .UsePropertyAccessMode(PropertyAccessMode.Property)
                .IsRequired(true);


            builder
                .Property(e => e.EmailEnc)
                .IsUnicode(false)
                .HasColumnName("email")
                .HasCharSet("ASCII")
                .UseCollation("ascii_general_ci")
                .IsRequired(false);

            builder
                .Property(e => e.FirstName)
                .IsUnicode()
                .IsRequired(false);

            builder
                .Property(e => e.LastName)
                .IsUnicode()
                .IsRequired(false);

            builder
                .Property(e => e.GlobalPrivileges)
                .HasConversion<PrivilegeUlongConverter>()
                .HasDefaultValue(Privileges.None)
                .IsRequired(true);

            builder
                .Property(e => e.PseudonymEnc)
                .IsUnicode(false)
                .HasColumnName("jlgkj")
                .HasCharSet("ASCII")
                .UseCollation("ascii_general_ci")
                .IsRequired();

            builder
              .Property(e => e.PasswordEnc)
              .HasColumnName("fdsqqf")
              .IsUnicode(false)
              .HasCharSet("ASCII")
              .UseCollation("ascii_general_ci")
              .IsRequired();

            builder
                .UseTpcMappingStrategy()
                .ToTable("SassyUsers");

        }
    }
```

**Comment by jlarnal** [comment] 2023-06-26 23:44
Moreover, if I use DbSet.FromSqlRaw to fetch and materialize my SassyUser object :

```C#
 public SassyUser GetUser(string uide, string pwde)
        {
            var pseuColName = "jlgkj";
            var passColName = "fdsqqf";
            var pseu = new MySqlParameter("pseu", uide);
            var pass = new MySqlParameter("pass", pwde);
            SassyUser deflt = null!;
            return SassyUsers.FromSqlRaw($"SELECT  *  FROM sassyusers WHERE {pseuColName} = @pseu AND {passColName} = @pass LIMIT 1").SingleOrDefault(deflt);
            //(from usr in SassyUsers
            // where usr.PseudonymEnc == uide && usr.PasswordEnc == pwde
            // select usr).FirstOrDefault()!;
            
        }
```



The InvalidCastException is thrown again, but with this message instead :

```
Using 'FromSqlRaw' on DbSet of 'SassyUser' is not supported since 'SassyUser' is part of hierarchy and does not contain a discriminator property.
```

**Comment by roji** [comment] 2023-06-27 05:40
@jlarnal please submit a minimal, runnable code sample that shows the InvalidCastException happening - the above is some snippets which are missing important code (for example, IIdentifiedObject, Privileges and various other things). I recommend starting a console project and trying to reproduce the problem there - while trying to do that there's a good chance you'll understand where the problem is in your code.

**Comment by jlarnal** [comment] 2023-06-27 13:03
Maybe EFcore is trying to discriminate on the column name of the primary key ?
Because all my table indeed have identical names for their PKs

```SQL
CREATE TABLE `sassyusers` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `FirstName` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `LastName` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `jlgkj` longtext CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `fdsqqf` longtext CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `email` longtext CHARACTER SET ascii COLLATE ascii_general_ci,
  `CreationDate` datetime(6) NOT NULL,
  `GlobalPrivileges` bigint(20) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

**Comment by roji** [comment] 2023-06-27 13:54
@jlarnal it's honestly a bit difficult to follow everything you write above. The general simplification of your model does seem to be a very good direction; if you're still encountering an exception or another problem, can you please post a minimal, runnable console program that just reproduces it? A small piece of code which repros a problem is always far better than lots of text which attempts to describe things.

**Comment by jlarnal** [comment] 2023-06-27 15:21
Thanks @roji 

I did exactly that : I stripped all my class of their inheritance to `IdentifiedObject` and deleted this abstract class from my code.
The queries to the `DbSet<SassyUser>` works now. 

I'll try to recreate the issue in a console app, since I still rely on Table-Per-Class for other entity types.
e.g, 'Traits' : named criteria I store,  that might hold strings, doubles, presets of values, etc, and would have needed some time-consuming serializations I didn't want to add to my application). So they'll all inherit a `TraitBase` abstract class, from which I implement 'TraitString' , 'TraitDouble', 'TraitEnum' etc... So there's a big chance the problems I encountered earlier will arise again.

Hence the need for a test console app made from a blank slate, as you recommended. I'll mimic the Fluent descriptors I wrote in my main project as much as possible, trying to reproduce the exceptions.

**Comment by ajcvickers** [comment] 2023-07-26 19:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-07-26 19:42 UTC
Labels: closed-could-not-reproduce, customer-reported
