### ISSUE TITLE
Incorrect migration file generation for string property

### ISSUE THREAD

**Issue by armanpetrosyan23** [dotnet/efcore#13852] opened 2018-11-01 14:34 UTC
Why  HasMaxLength(number) is Needed` if I already  specified when I declared the type (HasColumnType("nvarchar(50)")). Where is used  maxlength?

Migration file
![capture_1](https://user-images.githubusercontent.com/35919382/47857988-704b0400-de04-11e8-9807-34be9d5453c7.PNG)

Entity
![capture_2](https://user-images.githubusercontent.com/35919382/47857995-7345f480-de04-11e8-804b-e25b0878229f.PNG)
 

Configuration by Fluent API
![capture_3](https://user-images.githubusercontent.com/35919382/47858000-75a84e80-de04-11e8-98c5-ce35bdc443c1.PNG)

**Comment by ajcvickers** [comment] 2018-11-01 16:49
@armanpetrosyan23 What are you trying to achieve?

**Comment by armanpetrosyan23** [comment] 2018-11-01 17:12
I want to ask, where is it used? Maxlength()

**Comment by ajcvickers** [comment] 2018-11-01 17:31
@armanpetrosyan23 Max length is in the migration because it was specified in the configuration. What is is "used" for depends on what you mean by "used". There's lots of things I _could_ write about this, but without knowing more about what you _specifically_ want to know I'm not going to randomly spew out bits of information in the hope that I cover what you are actually asking about. Please be specific about the question you are asking.

**Comment by ajcvickers** [comment] 2018-11-05 18:52
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:38 UTC
Labels: closed-could-not-reproduce, customer-reported
