### ISSUE TITLE
DB-Scaffold output doesn't work with C#8 nullable flag

### ISSUE THREAD

**Issue by GunboatDiplomat** [dotnet/efcore#17147] opened 2019-08-14 09:29 UTC
## Steps to reproduce
- add Nullable flag to the .csproj
- have a varchar nullable column in the DB (mssql)
- use DB-Scaffold to generate the entity
```c#
public string Name { get; set; }
```
- also the mapping in the modelBuilder
```c#
entity.Property(e => e.Name)
    .HasMaxLength(500)
    .IsUnicode(false);
```

When materializing a row with a NULL Name value, the following error will show:
"SqlNullValueException: Data is Null. This method or property cannot be called on Null values."

Adding .IsRequired(false) or removing the nullable flag fixes this issue.

## Expected result

DB-Scaffold should generate output that works with the nullable flag.

**Comment by roji** [comment] 2019-08-14 17:20
Duplicate of #15520

**Closed** 2022-10-16 14:35 UTC
Labels: closed-duplicate, customer-reported
