### ISSUE TITLE
What can EntityFramework be waiting for so long?

### ISSUE THREAD

**Issue by FrancoisM** [dotnet/efcore#8230] opened 2017-04-19 20:53 UTC
In that SO post, I'm trying to find out why my query response time can vary so much. It shows that the time is spent waiting. But waiting what and why?

http://stackoverflow.com/q/43503179/1826096

**Comment by ajcvickers** [comment] 2017-04-21 19:01
@FrancoisM We looking into this but there doesn't seem to be much we can do without more information. Could you dig a little more and find out if, for example, you seem the same behavior when using SQLClient with DbConnection/DbCommand/etc. directly?

**Comment by ajcvickers** [comment] 2017-04-28 18:06
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:02 UTC
Labels: closed-could-not-reproduce
