### ISSUE TITLE
Database first - ability to override default type mapping

### ISSUE THREAD

**Issue by Misiu** [dotnet/efcore#6263] opened 2016-08-08 08:32 UTC
i have simple table in MS SQL containing 2 columns:
ClientId - binary(8) primary key 
ClientName - varchar(30)

When I add that table to my model I can see that `ClientId` type = `Binary`

![snap 2016-07-29 at 09 26 38](https://cloud.githubusercontent.com/assets/1741838/17473686/14a9fdf2-5d52-11e6-8a0e-6495a0bf7d9d.png)

What I would like to do is to override that type so that inside C# code I will be able to use int instead of byte[].

`SELECT * FROM Clients WHERE ClientId = 0x0000000000000001` and `SELECT * FROM Clients WHERE ClientId = 1` are giving me same results so why not allow to specify target mapping.

This would only require simple CAST inside SQL and just for select operation, all other work fine.

I'm aware I can use stored procedures for select and updates or even use SQL view. But sometimes for very simple applications this would be big convenience.

It's easier to say `client with Id = 4067` than `client with Id =0x0000000000000FE3`

Can this be done?

**Comment by ErikEJ** [comment] 2016-08-08 09:55
This is the EF Core issue tracker? Are you using EF6 - then the issue tracker is here: https://github.com/aspnet/EntityFramework6/issues

**Comment by Misiu** [comment] 2016-08-08 09:58
@ErikEJ I thought about posting it there, but as some time I'll move to EF7 so I'd like to have that feature already working when I'll use EF7.

**Comment by ajcvickers** [comment] 2016-08-08 17:19
Type conversions are being tracked by issue #242. Closing this as a duplicate of that issue.

**Closed** 2022-10-16 09:53 UTC
