### ISSUE TITLE
T4 - How to change file names

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [dotnet/efcore#29700] opened 2022-11-29 17:56 UTC
When following this guide:
[https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-clil)
How do you modify filenames to match modifications to the class names in "EntityType.t4"

**Comment by bricelam** [comment] 2022-11-30 22:42
Duplicate of #29541

**Closed by bricelam** 2022-11-30 22:42 UTC
Labels: customer-reported
