### ISSUE TITLE
System.InvalidOperationException is thrown when trying to query using 2 entities. Unhandled Exception: System.InvalidOperationException: Sequence contains more th an one element

### ISSUE THREAD

**Issue by PrashanthIBM** [dotnet/efcore#3639] opened 2015-11-03 15:36 UTC
Hi ,

I am using EF7Beta6 and trying to combine 2 entities in a query and i am getting 
System.InvalidOperationException: Sequence contains more th an one element

In fact for all queries which uses reference to another entity in the linq query is throwing invalid operation exception.

sample program :
 var query = context.ORDERSS.Where(o => o.SHIPCOUNTRY == "Mexico").Select(o => o.Customer.CUSTOMERID);
            foreach (var val in query) // getting exception here 

```
public partial class CUSTOMERS
{

    public string CUSTOMERID { get; set; }


    public string COMPANYNAME { get; set; }


    public string CONTACTNAME { get; set; }


    public string CONTACTTITLE { get; set; }


    public string ADDRESS { get; set; }


    public string CITY { get; set; }


    public string REGION { get; set; }


    public string POSTALCODE { get; set; }


    public string COUNTRY { get; set; }


    public string PHONE { get; set; }


    public string FAX { get; set; }

    public virtual ICollection<ORDERS> ORDERS { get; set; }
}
```

 public partial class ORDERS
    {

```
    public int ORDERID { get; set; }

    public string CUSTOMERID { get; set; }


    public int? EMPLOyeeID { get; set; }


    public DateTime? ORDERDATE { get; set; }


    public DateTime? REQUIREDDATE { get; set; }


    public DateTime? SHIPPEDDATE { get; set; }

    public decimal? FREIGHT { get; set; }


    public string SHIPNAME { get; set; }


    public string SHIPADDRESS { get; set; }


    public string SHIPCITY { get; set; }


    public string SHIPREGION { get; set; }


    public string SHIPPOSTALCODE { get; set; }


    public string SHIPCOUNTRY { get; set; }

    public virtual CUSTOMERS Customer { get; set; }

    public virtual INTORDERS INTORDER { get; set; }

    public virtual ICollection<ORDERDETAILS> ORDERDETAILS { get; set; }
}
```

Stack Trace : 

   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<>c__DisplayClass61_0`1.<BindMemberExpression>b__0(IEnumerable`1 ps, IQuerySource qs) in  C:\EF7\EntityFramework-7.0.0-beta6\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 1010
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpressionCore[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder) in  C:\EF7\EntityFramework-7.0.0-beta6\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 1032
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder) in  C:\EF7\EntityFramework-7.0.0-beta6\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 1007
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpression(MemberExpression memberExpression, Action`2 memberBinder) in  C:\EF7\EntityFramework-7.0.0-beta6\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 980
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RequiresMaterializationExpressionVisitor.VisitMember(MemberExpression memberExpression) in  C:\EF7\EntityFramework-7.0.0-beta6\src\EntityFramework.Core\Query\ExpressionVisitors\RequiresMaterializationExpressionVisitor.cs:line 71
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression) in  C:\EF7\EntityFramework-7.0.0-beta6\src\EntityFramework.Core\Query\ExpressionVisitors\ExpressionVisitorBase.cs:line 13
   at Remotion.Linq.Clauses.SelectClause.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RequiresMaterializationExpressionVisitor.FindQuerySourcesRequiringMaterialization(QueryModel queryModel) in  C:\EF7\EntityFramework-7.0.0-beta6\src\EntityFramework.Core\Query\ExpressionVisitors\RequiresMaterializationExpressionVisitor.cs:line 35
   at Microsoft.Data.Entity.Query.QueryCompilationContext.FindQuerySourcesRequiringMaterialization(EntityQueryModelVisitor queryModelVisitor, QueryModel queryModel) in  C:\EF7\EntityFramework-7.0.0-beta6\src\EntityFramework.Core\Query\QueryCompilationContext.cs:line 127
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel) in  C:\EF7\EntityFramework-7.0.0-beta6\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 93
   at Microsoft.Data.Entity.Storage.RelationalDatabase.CompileQuery[TResult](QueryModel queryModel) in  C:\EF7\EntityFramework-7.0.0-beta6\src\EntityFramework.Relational\Storage\RelationalDatabase.cs:line 102

Looks similar to #3629

Please let me know if the repro needs to be corrected.

Also please let me know if the issue is fixed in new beta releases.

Thanks and Regards,
Prashanth.

**Comment by rowanmiller** [comment] 2015-11-03 19:41
Please try against the latest release (Beta 8) and let us know if this still happens (we've made a lot of progress on query since Beta6)

**Comment by PrashanthIBM** [comment] 2015-11-06 12:20
Hi Rowan,

Seems like this issue occurs even in rc1.
Check  #3675

**Comment by maumar** [comment] 2015-11-06 18:27
@PrashanthIBM 3675 looks like a different issue - its a group by scenario, which is not yet implemented. Navigation property expansion support is in, and recently we fixed a number of issues in that area. The exception you are seeing happens when we do Single() operator on a collection with more than one element - and we do that in many places.

Please upgrade to latest to see if the issue is indeed fixed. Alternatively please add code for your DbContext and sample data (if there were any) that you used to repro this on your machine and I will quickly check it again latest bits and get back to you with the results.

**Comment by maumar** [comment] 2015-11-06 18:30
@PrashanthIBM actually sample data wont be needed since its a compile time error. I just need code for your DBContext (OnModelCreating method, specifically)

**Comment by maumar** [comment] 2015-11-06 19:04
closing per verification by @AlekseyMartynov in https://github.com/aspnet/EntityFramework/issues/3675

**Closed** 2022-10-16 09:14 UTC
