### ISSUE TITLE
ThenInclude with Select unexpected behavior

### ISSUE THREAD

**Issue by daniel18acevedo** [dotnet/efcore#32796] opened 2024-01-12 12:04 UTC
### Evidence
![image](https://github.com/dotnet/efcore/assets/26153412/ca58f50f-c2b1-440b-8764-a2cff696af9f)

![image](https://github.com/dotnet/efcore/assets/26153412/83525abe-ec7e-4b03-8f89-0f3989a82f7d)

### Repo
https://github.com/daniel18acevedo/efcore-then-include-select-issue

### Include stack traces
```
Parent property is being null but Category gets included just fine
```

### Include provider and version information

EF Core version: 7.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: Windows
IDE: Visual Studio 2022 17.4

**Comment by maumar** [comment] 2024-01-17 02:55
this is query we get:

```cs
DbSet<Request>()
    .Include(r => r.Category)
    .ThenInclude(c => c.ParentCategory)
    .Where(r => r.Category.IsActive && r.Category.ParentCategoryId.HasValue)
    .GroupBy(r => r.Category)
    .Select(g => new ResultGroupByCategoryQuery{ 
        Category = g.Key, 
        Parent = g.Key.ParentCategory 
    }
    )
```

nav expansion converts it to:

```cs
DbSet<Request>()
    .Join(
        inner: DbSet<Category>(), 
        outerKeySelector: r => EF.Property<Guid?>(r, "CategoryId"), 
        innerKeySelector: c => EF.Property<Guid?>(c, "CategoryId"), 
        resultSelector: (o, i) => new TransparentIdentifier<Request, Category>(
            Outer = o, 
            Inner = i
        ))
    .Where(r => r.Inner.IsActive && r.Inner.ParentCategoryId.HasValue)
    .GroupBy(r => r.Inner)
    .Select(g => new ResultGroupByCategoryQuery{ 
        Category = g.Key, 
        Parent = g.Key.ParentCategory 
    }
    )
```

note that `Parent = g.Key.ParentCategory` has not been expanded

this results in the following translation:

```cs
ShapedQueryExpression: 
    QueryExpression: 
        Client Projections:
            0 -> Dictionary<IProperty, int> { [Property: Category.CategoryId (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd, 0], [Property: Category.IsActive (bool) Required, 1], [Property: Category.Name (string), 2], [Property: Category.ParentCategoryId (Guid?) FK Index, 3] }
        SELECT c.CategoryId, c.IsActive, c.Name, c.ParentCategoryId
        FROM Requests AS r
        INNER JOIN Categories AS c ON r.CategoryId == c.CategoryId
        WHERE c.IsActive && c.ParentCategoryId IS NOT NULL
        GROUP BY c.CategoryId, c.IsActive, c.Name, c.ParentCategoryId
    ShaperExpression: new ResultGroupByCategoryQuery{ 
            Category = StructuralTypeShaperExpression: 
                Category
                ValueBufferExpression: 
                    ProjectionBindingExpression: 0
                IsNullable: False
            , 
            Parent = StructuralTypeShaperExpression: 
                Category
                ValueBufferExpression: 
                    ProjectionBindingExpression: 0
                IsNullable: False
             == default(Category) ? null : StructuralTypeShaperExpression: 
                Category
                ValueBufferExpression: 
                    ProjectionBindingExpression: 0
                IsNullable: False
            .ParentCategory 
        }
```

we just project category entity and try to access ParentCategory on the client, which is obviously always null.

**Comment by maumar** [comment] 2024-01-17 02:56
duplicate of https://github.com/dotnet/efcore/issues/29014

**Closed** 2024-01-17 18:56 UTC
Labels: closed-duplicate, customer-reported
