### ISSUE TITLE
Error in Generated Migration Script for Microsoft.EntityFrameworkCore.SqlServer 8.0.4

### ISSUE THREAD

**Issue by MohamedTwheed** [dotnet/efcore#33651] opened 2024-05-01 09:13 UTC
## Error in Generated Migration Script for Microsoft.EntityFrameworkCore.SqlServer 8.0.4
When generating migration scripts using this version, I have encountered an error in the structure of the generated script. The generated script appears as follows:

### Generated sql script

```SQL
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'xxxxxxxxxxxx'
)
BEGIN

END;
GO

```
The issue lies in the empty BEGIN and END block enclosed within the IF NOT EXISTS condition. This seems to be incorrect syntax and causes errors when executing the script.

### EF packages used
```C#
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.4" />
```
When we downgrade the Microsoft.EntityFrameworkCore.SqlServer to version 8.0.2 the migration scripts are generated correctly.

### Expected Behavior:
The migration script generated by Microsoft.EntityFrameworkCore.SqlServer 8.0.4 should have correct syntax without empty blocks, ensuring smooth execution without errors.

### Steps to Reproduce:
Example of migration used that produced this script:

![image](https://github.com/dotnet/efcore/assets/52384343/cfa770ee-6fae-44ca-be86-7166bf47adfe)
![image](https://github.com/dotnet/efcore/assets/52384343/cc687f65-7679-4a47-a474-39f272bc766b)

* Use Microsoft.EntityFrameworkCore.SqlServer version 8.0.4.
* Generate migration scripts for a database.
* Observe the generated migration script.
### Provider and version information

EF Core version: 8.0.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 8.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.8.5)

**Comment by MohamedTwheed** [comment] 2024-05-01 10:10
We have found the issue in our sql scripts we add if it has an empty line it generates the empty begin and end scopes
for example:
![image](https://github.com/dotnet/efcore/assets/52384343/13dd9ad8-bfc6-423b-967a-6225d052e3cb)
In the above screenshot we have empty line 38 in the script which generates it.
This wasn't the case in version 8.0.2 started happening only in version 8.0.4.

**Comment by ajcvickers** [comment] 2024-05-01 14:17
Duplicate of #33337

**Closed by ajcvickers** 2024-05-01 14:17 UTC
Labels: customer-reported
