### ISSUE TITLE
add-migration 

### ISSUE THREAD

**Issue by AHMEDKAMALET** [dotnet/efcore#2391] opened 2015-06-16 16:32 UTC
i have a problem when i create my database ,i used entityframework 7 i get the message as following:
Cannot bind parameter 'FilterScript'. Cannot convert the "Id" value of type "System.String" to type "System.Management.Automation.ScriptBlock".

**Comment by rowanmiller** [comment] 2015-06-16 17:02
@AHMEDKAMALET can you share your code so that we can reproduce the issue you are seeing.

**Comment by AHMEDKAMALET** [comment] 2015-06-16 17:07
thank you mr rowanmiller first i created the model (class context,class entity)and i added the sqlserver in visual studio , iwant work with if 
my code:
//the context class
    public class Context:DbContext
    {
       
        protected override void OnConfiguring(EntityOptionsBuilder optionsBuilder)
        {
            //base.OnConfiguring(optionsBuilder);
            var connextionstring = @"Data Source=(localdb)\Projects;Initial Catalog=EF7.Context;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False";
            optionsBuilder.UseSqlServer(connextionstring);
           
        }

        public DbSet<client>clients{get;set;}
    }
 public class client//class entity
    {
        public int clientID { get; set; }
    }

just i want to create my database 
thank you

**Comment by rowanmiller** [comment] 2015-06-16 18:04
@AHMEDKAMALET are you using Windows 7?

**Comment by AHMEDKAMALET** [comment] 2015-06-16 18:28
yes ,windows 7

**Comment by AHMEDKAMALET** [comment] 2015-06-16 18:31
i used EF6 ,ity works in windows 7

**Comment by bricelam** [comment] 2015-06-16 20:20
This is probably a dupe of #2134

**Comment by AHMEDKAMALET** [comment] 2015-06-16 20:28
thank you i will try and i will say you the result

**Comment by AHMEDKAMALET** [comment] 2015-06-16 22:47
thank you so much mr bricelam you helped me , i solved my problem :+1:

**Closed** 2022-10-16 08:59 UTC
