### ISSUE TITLE
Update using composite key (which is present) inserts when it should update

### ISSUE THREAD

**Issue by alecouteurbisson** [dotnet/efcore#10767] opened 2018-01-25 11:11 UTC
The latter half of #10194 describes an issue where calling DbContext.Update() on an entity with a complete composite key inserts instead of updating and then throws because the row exists in the database.  We are seeing exactly the same issue here.

The error is occurring on a many-to-many link table which contains two integer foreign keys that together comprise the primary key.

We have a detached graph which includes an item in the many to many relationship.  We attach this to the context by calling ctx.Update(graphRoot) and the exception occurs on the SaveChanges.

Examination of the EntityEntry just prior to SaveChanges shows that the State of the link table entity is Modified, as it should be.  Nevertheless an insert statement is issued to MySql.

The workaround in #10194 does not help in our case.

```
Exception message:  MySqlException: Duplicate entry '1-1' for key 'PRIMARY'
Stack trace:
Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)\r\n   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlBatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)\r\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)\r\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()\r\n   at FhirModels.Models.ResourceManager.Update(Entry entry, String user) in C:\\Users\\Win7Dev\\Documents\\SparkSql\\src\\FhirModels\\Models\\ResourceManager.cs:line 215\r\n   at Spark.Sql.SqlFhirStore.Add(Entry entry, JWTToken token) in C:\\Users\\Win7Dev\\Documents\\SparkSql\\src\\Spark.Sql\\SqlFhirStore.cs:line 53\r\n   at Spark.Engine.Service.FhirServiceExtensions.ResourceStorageService.Add(Entry entry, JWTToken token) in C:\\Users\\Win7Dev\\Documents\\SparkSql\\src\\Spark.Engine\\Service\\FhirServiceExtensions\\ResourceStorageService.cs:line 38\r\n   at Spark.Engine.Service.FhirService.Store(Entry entry, JWTToken token) in C:\\Users\\Win7Dev\\Documents\\SparkSql\\src\\Spark.Engine\\Service\\FhirService.cs:line 413\r\n   at Spark.Engine.Service.FhirService.Put(Entry entry, JWTToken token) in C:\\Users\\Win7Dev\\Documents\\SparkSql\\src\\Spark.Engine\\Service\\FhirService.cs:line 126\r\n   at Spark.Engine.Service.FhirService.Put(IKey key, Resource resource, JWTToken token) in C:\\Users\\Win7Dev\\Documents\\SparkSql\\src\\Spark.Engine\\Service\\FhirService.cs:line 136\r\n   at Spark.Engine.Service.FhirService.Update(IKey key, Resource resource, JWTToken token) in C:\\Users\\Win7Dev\\Documents\\SparkSql\\src\\Spark.Engine\\Service\\FhirService.cs:line 201\r\n   at Spark.Controllers.FhirController.Update(String type, Resource resource, String id) in C:\\Users\\Win7Dev\\Documents\\SparkSql\\src\\Spark\\Controllers\\FhirController.cs:line 58\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"
```

### Further technical details
EF Core version: 2.0
Database Provider: Pomelo.EntityFrameworkCore.MySql
Operating system: Windows 7
IDE: Visual Studio 2017 15.4.4

**Comment by ajcvickers** [comment] 2018-01-25 17:10
@alecouteurbisson Can you please post a runnable project/solution or full code listing that will let us reproduce the behavior that you are seeing?

**Comment by ajcvickers** [comment] 2018-02-02 17:26
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:06 UTC
Labels: closed-could-not-reproduce
