### ISSUE TITLE
Scaffold entity configuration into separate files

### ISSUE THREAD

**Issue by chrisatweave** [dotnet/efcore#27777] opened 2022-04-07 03:29 UTC
Reading through the scaffolding code and the commands configuration (DbContextScaffoldCommand.Configure.cs) I couldn't find a feature that solves this problem.

I am porting a large legacy app to .NET Core, the new .NET Core codebase is a slave to the "legacy" codebase and must re-scaffold often. The legacy codebase is still in very much active development.

When scaffolding from the legacy database, the dbcontext size becomes unmanageable due to the thousands of lines of entity configuration. This causes several issues:

* Tweaking the configuration to meet the new tech stack becomes unrealistic. 
* The dbcontext can become unresponsive while the static analysis process the file (ie cache is cleared).
* Git diffs become useless after large migrations from the parent legacy code base (important for .NET Core tweaks)

Being able to specific a directory for entity configurations to be output to as individual files would solve this problem.

**Comment by ErikEJ** [comment] 2022-04-07 05:09
EF Core Power Tools contains a (preview) feature to do this.

**Comment by ajcvickers** [comment] 2022-04-07 08:52
Duplicate of #8434.

**Closed** 2022-10-16 20:30 UTC
Labels: closed-duplicate, customer-reported
