### ISSUE TITLE
SqlHierarchyId work in efcore 2 but not working in efcore3

### ISSUE THREAD

**Issue by 110vahid** [dotnet/efcore#20415] opened 2020-03-26 08:15 UTC
when using SqlHierarchyId in models and  call insert method exeption occured.
innerexception : No mapping exists from object type Microsoft.SqlServer.Types.SqlHierarchyId to a known managed provider native type.

**Comment by ajcvickers** [comment] 2020-03-26 16:19
@110vahid SqlHierarchyId minimally "worked" in EF Core 2.x on .NET Framework. It is [not supported on .NET Core](https://github.com/dotnet/SqlClient/issues/322). Also, given that EF Core 5 will [no longer run on .NET Framework](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/plan), we are not currently prioritizing making SqlHierarchyId work in EF Core.

**Comment by 110vahid** [comment] 2020-03-26 19:03
Is there a replacement for SqlHierarchy in .net core 3?

**Comment by ajcvickers** [comment] 2020-03-27 19:58
@110vahid Official support in .NET Core requires that the types be implemented, which is tracked by [SqlClient issue #322](https://github.com/dotnet/SqlClient/issues/322), referenced above.
If this gets done, then #365 is tracking support in EF Core.

Issue #365 also contains discussion of and links to some community efforts to bring an equivalent type to .NET Core.

Closing this as a duplicate of #365, which we will use for potential future support of SqlHierarchyId in EF Core.

**Closed** 2022-10-16 18:17 UTC
Labels: closed-duplicate, customer-reported
