### ISSUE TITLE
Support materialization hook

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#3943] opened 2015-12-02 00:17 UTC
Add a hook for customizing the ValueBuffer => ClrType materialization step.

Just one usage scenario among many possibilities:
Materializing an `Annotatable`. I want to put shadow properties into annotations.

**Comment by rowanmiller** [comment] 2015-12-02 19:18
Think this is a dupe of https://github.com/aspnet/EntityFramework/issues/240

**Comment by rowanmiller** [comment] 2015-12-02 19:20
BTW I think you don't actually want shadow properties right... you want a property that is stored in the CLR type but to get/set the value you don't use a property getter/setter.

**Comment by natemcmaster** [comment] 2015-12-02 22:07
Yes can be solved by #240. This could also be solved by https://github.com/aspnet/EntityFramework/issues/2968. I was aware of these issues when filing, but  still think a materialization extension point could be useful.

**Comment by natemcmaster** [comment] 2015-12-02 23:15
https://github.com/aspnet/EntityFramework/issues/2968#issuecomment-161463855

**Closed** 2022-10-16 09:18 UTC
