### ISSUE TITLE
ICollection for related entities is too permissive.

### ISSUE THREAD

**Issue by SuperJMN** [dotnet/efcore#857] opened 2014-10-13 19:12 UTC
It's a pity that we cannot have entities with read-only collections. It's a must for any Domain-Driven Design approach in order to enforce rules and restrictions. In a rich model (not anemic), entities are usually responsible for keeping relationships consistent with the model.

Forcing the usage of writeable collections **makes it easy to violate those rules and restrictions of the domain**. Please, improve it.

At least, we need a way to make Entity Framework work behind the stage to fill and navigate relations like it  already does, but also provide means to avoid every collection to have methods like Add, Delete or Insert.

**Comment by ajcvickers** [comment] 2016-07-08 17:39
Dupe of #752

**Closed** 2022-10-16 08:44 UTC
