### ISSUE TITLE
Reverse Engineer: Add extensibility point to customize file name.

### ISSUE THREAD

**Issue by irperez** [dotnet/efcore#12319] opened 2018-06-10 11:04 UTC
Hello @rowanmiller, @divega , @bricelam,

I'd like to add an extensibility point to the entity file naming.  

Currently it's set to:

https://github.com/aspnet/EntityFrameworkCore/blob/2377e8c2418b5dc9925af567b9d79c63235fbcbb/src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs#L87

I would like to open this up by adding another public interface as a public virtual property to the CSharpModelGenerator class.  Something along the lines of "**IEntityFileNameGenerator**" with a single method "**GenerateFileName**"

Here is an example:
https://gist.github.com/irperez/2ca16d2e9480f040e54e271abcc34c36

```C#
 namespace Microsoft.EntityFrameworkCore.Scaffolding.Internal
{
    public interface IEntityFileNameGenerator
    {
        string GenerateFileName(IEntityType entityType, string FileExtension);
    }
}
```

Similar to what you are doing here:
https://github.com/aspnet/EntityFrameworkCore/blob/2377e8c2418b5dc9925af567b9d79c63235fbcbb/src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs#L28

The idea is that I would create a default implementation that would default to what's being done today such as what's shown above.  **entityType.DisplayName() + FileExtension**.  

This gives third party developers the ability to overwrite that behavior and add something like so: 
```C#
entityType.DisplayName() + '.g' + FileExtension  // =>  "TestObject.g.cs"
```

This would make it easier for developers to utilize partial classes or to customize the naming to their needs.

I believe this will require an addition to this section of code to ensure the default implementation is loaded:
https://github.com/aspnet/EntityFrameworkCore/blob/a603b983d0eca46f664fb1780bec3b6ef3e8c5ac/src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs#L48-L87

We'll also need to add the IEntityFileNameGenerator as a parameter to this constructor:
https://github.com/aspnet/EntityFrameworkCore/blob/a603b983d0eca46f664fb1780bec3b6ef3e8c5ac/src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs#L34-L38

Did I miss anything?

I can provide the PR for this, but looking for approval/feedback.  Also if approved, should this be done on the "dev" branch? 

I've perform the above changes locally with all unit tests passing.

**Comment by ajcvickers** [comment] 2018-06-13 00:09
@irperez Ultimately this falls under the [Improve reverse engineering extensibility](https://github.com/aspnet/EntityFrameworkCore/issues/12050) so we wouldn't want to do anything permanent outside of that. However, we would consider a PR to add this extensibility now as long as it is done in the Internal namespace (so we can remove it later) and does not break reverse engineering for any existing providers.

Closing this issue as a duplicate of #12050 since the EF team is not planning to do anything outside of that issue.

**Closed** 2022-10-16 12:30 UTC
Labels: closed-duplicate, customer-reported
