### ISSUE TITLE
ef core ignores parameterized constructor if parameterless constructor exists

### ISSUE THREAD

**Issue by ish-1313** [dotnet/efcore#27466] opened 2022-02-17 16:00 UTC
## File a bug

documentation for ef core here https://docs.microsoft.com/en-us/ef/core/modeling/constructors states that

However, **if EF Core finds a parameterized constructor** with parameter names and types that match those of mapped properties, **then it will instead call the parameterized constructor** 

in reality if entity has parameterless constructor it will be called even if entity has parameterized one with correct properties.

```
       public cInventoryStock(int ID)
        {
            this.ID = ID;
            Debug.WriteLine("constructor without init");
        }

        public cInventoryStock()
        {
            base.Init();
            Debug.WriteLine("constructor with init");
        }
```

constructor with parameter is not called until i change parameterless to something like 

```
        public cInventoryStock(bool state = false)
        {
            base.Init();
            Debug.WriteLine("constructor with init");
        }
```

then ef core starts to call constructor with (int ID)

EF Core version: 6.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0

Windows 20H2 (19042.1526)
Microsoft Visual Studio Professional 2022
Version 17.1.0
VisualStudio.17.Release/17.1.0+32210.238

**Comment by ajcvickers** [comment] 2022-02-18 10:48
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/2571

**Comment by ish-1313** [comment] 2022-02-18 11:06
> Duplicate of [dotnet/EntityFramework.Docs#2571](https://github.com/dotnet/EntityFramework.Docs/issues/2571)

Well, it depends on point of view.. is it inconsistency in a document or bug in a code.

**Comment by ajcvickers** [comment] 2022-02-18 11:57
@ish-1313 It is by-design. We made it this way to avoid breaking existing applications with multiple constructors.

**Comment by ish-1313** [comment] 2022-02-18 12:02
> @ish-1313 It is by-design. We made it this way to avoid breaking existing applications with multiple constructors.

pity. i was planning to use constructor with parameters to get rid of unnecessary object initialization when it is loaded from db.
(or to skip propertychanged notification code).

no plans to change it in the future versions with data annotation or fluent api ?

**Comment by ish-1313** [comment] 2022-02-18 12:33
> @ish-1313 Configuration of this is tracked by #10789. It is already possible to bind explicitly to a different constructor by dropping down to lower level code. I can come up with an example if it would help.

thank you, will follow 10789. 
as for low level code example. no, thank you, i am ok with constructor with fake parameter. at least for now.. i just want to generate guid and few time stamps. and don't want to ovveride on savechanges, use fulentapi,  or other "standard methods". idea to use different constructors seems much better even now :)  thank you

**Closed** 2022-10-16 20:26 UTC
Labels: closed-duplicate, customer-reported

**Comment by cdrfenix** [comment] 2024-01-23 17:46
Does this remain true? will EFCore use the parameterless constructor even when a parameterized one exists?.

**Comment by ajcvickers** [comment] 2024-01-23 18:12
@cdrfenix Yes.
