### ISSUE TITLE
Concurrency state issues with split query

### ISSUE THREAD

**Issue by natehitze** [dotnet/efcore#25225] opened 2021-07-08 20:29 UTC
### Include your code

I'm trying to reproduce locally but this issue is currently only happening in our production environment. It is rare but comes up every few minutes on the couple endpoints that I'm using `.AsSplitQuery()` with.

The query looks like this:

```csharp
var events = await _dbContext.Events
                    .AsNoTracking()
                    .Where(...query...)
                    .AsSplitQuery()
                    .ProjectTo<DtoEvent>(MapperConfiguration)
                    .ToListAsync(cancellationToken);
```

My context is registered like this:

```csharp
services.AddDbContextPool<MyDbContext>(opt =>
    {
        opt.ReplaceService<IValueConverterSelector, MyValueConverterSelector>();
        opt.UseSqlServer(Configuration["MyDBConnectionString"], sqlOpt => 
        { 
            sqlOpt.UseNetTopologySuite();
            sqlOpt.EnableRetryOnFailure();
        });
        opt.ConfigureWarnings(warnings =>
        {
            warnings.Ignore(RelationalEventId.MultipleCollectionIncludeWarning);
        });
    });
```

~I have MARS enabled.~

### Include stack traces

Mostly I'm getting 

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader+BufferedDataRecord.GetGuid(System.Int32 ordinal) in Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader+BufferedDataRecord0
at lambda_method6756(System.Runtime.CompilerServices.Closure , Microsoft.EntityFrameworkCore.Query.QueryContext , System.Data.Common.DbDataReader ) in (unknown) line 82
at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor+ShaperProcessingExpressionVisitor+<PopulateSplitCollectionAsync>d__68`3.MoveNext() in Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor+ShaperProcessingExpressionVisitor+<PopulateSplitCollectionAsync>d__68`3 line 364
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in System.Runtime.ExceptionServices.ExceptionDispatchInfo line 17
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 55
at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor+ShaperProcessingExpressionVisitor+<TaskAwaiter>d__69.MoveNext() in Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor+ShaperProcessingExpressionVisitor+<TaskAwaiter>d__69 line 121
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in System.Runtime.ExceptionServices.ExceptionDispatchInfo line 17
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 55
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 40
at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1+AsyncEnumerator+<MoveNextAsync>d__20.MoveNext() in Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1+AsyncEnumerator+<MoveNextAsync>d__20 line 566
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in System.Runtime.ExceptionServices.ExceptionDispatchInfo line 17
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 55
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 40
at System.Threading.Tasks.ValueTask`1.get_Result() in System.Threading.Tasks.ValueTask`1 line 27
at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1.MoveNext() in Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1 line 204
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in System.Runtime.ExceptionServices.ExceptionDispatchInfo line 17
at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1.MoveNext() in Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1 line 345
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in System.Runtime.ExceptionServices.ExceptionDispatchInfo line 17
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 55
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 40
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() in System.Runtime.CompilerServices.TaskAwaiter`10

... ASP.NET/My controller code truncated
```

I did get a couple of this though:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') Actual value was 192.
at System.Collections.BitArray.ThrowArgumentOutOfRangeException(System.Int32 index) in System.Collections.BitArray line 21
at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader+BufferedDataRecord.IsDBNull(System.Int32 ordinal) in Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader+BufferedDataRecord0
at lambda_method3041(System.Runtime.CompilerServices.Closure , Microsoft.EntityFrameworkCore.Query.QueryContext , System.Data.Common.DbDataReader , Microsoft.EntityFrameworkCore.Query.Internal.ResultContext , Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryResultCoordinator ) in (unknown) line 76
at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor+ShaperProcessingExpressionVisitor+<PopulateSplitCollectionAsync>d__68`3.MoveNext() in Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor+ShaperProcessingExpressionVisitor+<PopulateSplitCollectionAsync>d__68`3 line 471
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in System.Runtime.ExceptionServices.ExceptionDispatchInfo line 17
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 55
at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor+ShaperProcessingExpressionVisitor+<TaskAwaiter>d__69.MoveNext() in Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor+ShaperProcessingExpressionVisitor+<TaskAwaiter>d__69 line 121
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in System.Runtime.ExceptionServices.ExceptionDispatchInfo line 17
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 55
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 40
at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1+AsyncEnumerator+<MoveNextAsync>d__20.MoveNext() in Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1+AsyncEnumerator+<MoveNextAsync>d__20 line 566
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in System.Runtime.ExceptionServices.ExceptionDispatchInfo line 17
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 55
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 40
at System.Threading.Tasks.ValueTask`1.get_Result() in System.Threading.Tasks.ValueTask`1 line 27
at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1.MoveNext() in Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1 line 204
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in System.Runtime.ExceptionServices.ExceptionDispatchInfo line 17
at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1.MoveNext() in Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1 line 345
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in System.Runtime.ExceptionServices.ExceptionDispatchInfo line 17
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 55
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 40
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() in System.Runtime.CompilerServices.TaskAwaiter`10

... ASP.NET/My controller code truncated
```

I just got one like this:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
File "System.ThrowHelper", line 10, in System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
  File "Microsoft.Data.SqlClient.SqlParameterCollection", line 39, in Microsoft.Data.SqlClient.SqlParameterCollection.Clear()
  File "Microsoft.EntityFrameworkCore.Storage.RelationalDataReader+<DisposeAsync>d__20", line 432, in Microsoft.EntityFrameworkCore.Storage.RelationalDataReader+<DisposeAsync>d__20.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 17, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "System.Runtime.CompilerServices.TaskAwaiter", line 55, in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task)
  File "Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1+AsyncEnumerator+<DisposeAsync>d__22", line 326, in Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1+AsyncEnumerator+<DisposeAsync>d__22.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 17, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "System.Runtime.CompilerServices.TaskAwaiter", line 55, in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task)
  File "System.Runtime.CompilerServices.TaskAwaiter", line 40, in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)
  File "Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1", line 326, in Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 17, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "System.Runtime.CompilerServices.TaskAwaiter", line 55, in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task)
  File "System.Runtime.CompilerServices.TaskAwaiter", line 40, in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)
  File "System.Runtime.CompilerServices.TaskAwaiter`1", line unknown, in System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

... ASP.NET/My controller code truncated
```

I've gotten a few of this:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at lambda_method3898(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.PopulateSplitCollectionAsync[TCollection,TElement,TRelatedEntity](Int32 collectionId, RelationalQueryContext queryContext, IExecutionStrategy executionStrategy, Boolean detailedErrorsEnabled, SplitQueryResultCoordinator resultCoordinator, RelationalCommandCache relationalCommandCache, Func`3 childIdentifier, IReadOnlyList`1 identifierValueComparers, Func`5 innerShaper, Func`4 relatedDataLoaders) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x6001951+0x287
at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.TaskAwaiter(Func`1[] taskFactories) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x6001952+0x79
at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync() in Microsoft.EntityFrameworkCore.Relational.dll:token 0x6001acc+0x236
at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken) in Microsoft.EntityFrameworkCore.dll:token 0x6000213+0xcc
at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken) in Microsoft.EntityFrameworkCore.dll:token 0x6000213+0x159

... ASP.NET/My controller code truncated
```

### Include provider and version information

EF Core version: 6.0.0-preview.5.21301.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer, 6.0.0-preview.5.21301.9
Target framework: .NET 6 preview 5, self-contained deploy
Operating system: Windows (Azure App Service)

**Comment by smitpatel** [comment] 2021-07-09 03:34
We will need a simple runnable repro code to investigate this issue.

**Comment by natehitze** [comment] 2021-07-09 19:23
I've added another stack trace to the first comment. 

I don't think a simple repro is going to be feasible for me. The model and projection have a lot of navigations (hence the split query) and I still haven't been able to replicate this anywhere but our production environment. The only change to the query was adding `.AsSplitQuery()` and most executions of the query are working fine (error rate < 1%).

Is there something I can do to narrow down the cause?

**Comment by natehitze** [comment] 2021-07-09 19:35
I've added a 4th stack trace to the first comment. I missed it among other error reports.

**Comment by smitpatel** [comment] 2021-07-09 23:42
We will need runnable repro code. Based on varying exception message, it seems like issue with multi-threading. Specifically, trying to run query on same DbContext from multiple threads which does not work since DbContext is not thread-safe.

**Comment by natehitze** [comment] 2021-07-12 23:06
I am now able to repro this reliably locally and I'm trying to figure out how to make a sample I can share here. With so many variables in the pipeline it's hard to narrow down what is needed for the repro.

Here's some more info:
- There's a short query that runs before the split query, it has never thrown
- I'm using ASP.NET's DI system, using `.AddDbContext`. I removed context pooling just in case and also tried registering as Transient, neither helped
- I use standard controller injection to get the DbContext and have the controller pared down to just Query1 -> Query2 -> return Ok, and Query2 still throws
- Locally I've only ever gotten the index out of range exception - it happens in the same method (`BufferedDataRecord.GetGuid`) every time. It's probably worth noting that these models join on Guid keys
- When I break in `BufferedDataRecord.GetGuid` and use the immediate window to evaluate the statements, none of them throw the exception
- It only throws during concurrent requests - the actual data results don't matter (as long as there are some results).

This is the smallest I can get my projection to throw:
```csharp
.Select(e => new DtoBaseCalendarEventDetail
{
    PrimaryCalendar = new DtoBaseCalendarEventPrimaryCalendarDetail
    {
         TeamsGameCalendar = e.PrimaryCalendar.TeamsGameCalendar.Select(t => new DtoBaseCalendarEventPrimaryCalendarTeam
         {
         }),
    }
})
.AsSplitQuery()
```

Here's the whole (simplified) throwing controller action:
```csharp
public async Task<ActionResult> BySubscription(
    [FromQuery, Required] Guid id,
    [FromQuery, Required] Guid token,
    [FromQuery] int? number,
    CancellationToken cancellationToken)
{
    var organizationSubscription = await Db.OrganizationSubscriptions
        .AsNoTracking()
        .Where(os => os.User.Token == token && os.OrganizationID == id)
        .Select(os => new
        {
            os.ID,
        })
        .FirstOrDefaultAsync(cancellationToken);

    if (organizationSubscription == null)
    {
        return BadRequest();
    }

    try
    {
        var g = Guid.NewGuid();
        _logger.LogInformation($"Start-Query {number}");
        var subscribedEvents = await Db.CalendarSubscriptions
            .AsNoTracking()
            .Where(cs => cs.OrganizationSubscriptionID == organizationSubscription.ID)
            .SelectMany(cs => cs.Calendar.Events)
            .Where(e => e.ID != g) // There is a complicated expression here in real code, this placeholder keeps a .Where while proving the real expression (which doesn't use e.ID) isn't the issue
            .Select(e => new DtoBaseCalendarEventDetail
            {
                PrimaryCalendar = new DtoBaseCalendarEventPrimaryCalendarDetail
                {
                     TeamsGameCalendar = e.PrimaryCalendar.TeamsGameCalendar.Select(t => new DtoBaseCalendarEventPrimaryCalendarTeam
                     {
                     }),
                }
            })
            .AsSplitQuery()
            .ToListAsync(cancellationToken);
        _logger.LogInformation($"Done-Query {number}");

        return Ok();
    }
    catch (Exception e)
    {
        throw;
    }
}
```

Is there any other information I can gather (maybe from logs/stack frames/stepping through debugger) that would help? If the problem was my misuse of the DbContext, I would think that other queries in other controllers would have had an issue at some point. I agree that it sounds like a threading issue but I think it's internal to the SplitQuery implementation.

**Comment by natehitze** [comment] 2021-07-13 13:14
@smitpatel Here is a repository for my repro: https://github.com/natehitze/efcoresplitrepro

I ran it on an empty database and the seed data included was enough to repro on every run.

**Comment by billybraga** [comment] 2021-08-18 17:15
@ajcvickers Can we expect the fix pour RC 1?

**Comment by smitpatel** [comment] 2021-08-18 21:01
I investigated this issue. Based on that and timeline of release
- This won't be fixed in rc1.
- I indeed got a repro but the repro project is complex in order to isolate the query causing issue.
- Any attempt at stripping down the repro to isolate EF Core failed to generate exception.

I will revisit this in some time after working on other bugs, but lack of small isolated repro makes it harder to investigate and fix this issue.

**Comment by billybraga** [comment] 2021-08-18 21:06
Thanks for the update.

**Comment by billybraga** [comment] 2021-08-19 18:42
I seem to have found a workaround for my situation: disable memory cache.

```csharp
services.AddDbContext<MyDbContext>(
    builder => builder
        .UseMemoryCache(
            new MemoryCache(
                new OptionsManager<MemoryCacheOptions>(
                    new OptionsFactory<MemoryCacheOptions>(
                        new List<IConfigureOptions<MemoryCacheOptions>>
                        {
                            new ConfigureOptions<MemoryCacheOptions>(
                                o => o.SizeLimit = 0
                            )
                        },
                        new List<IPostConfigureOptions<MemoryCacheOptions>>()
                    )
                )
            )
        )
)
```

**Comment by billybraga** [comment] 2021-08-20 13:32
Here is a simple repro repo: https://github.com/billybraga/EfCore6SplitQueryConcurrencyBug

**Comment by billybraga** [comment] 2021-08-20 13:42
If I'd have to guess, I'd say this is the fix: 

```patch
Index: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs b/src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
--- a/src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs	(revision 5da86b8dbefd5c5ce1b8e822ddef109ab0f5756f)
+++ b/src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs	(date 1629466799137)
@@ -1734,7 +1734,9 @@
                         RelationalCommandCache relationalCommandCache,
                         bool detailedErrorsEnabled)
                     {
-                        var relationalCommand = relationalCommandCache.GetRelationalCommand(queryContext.ParameterValues);
+                        var relationalCommandTemplate = relationalCommandCache.GetRelationalCommand(queryContext.ParameterValues);
+                        var relationalCommand = queryContext.Connection.RentCommand();
+                        relationalCommand.PopulateFrom(relationalCommandTemplate);
 
                         return relationalCommand.ExecuteReader(
                             new RelationalCommandParameterObject(
@@ -1813,7 +1815,9 @@
                         bool detailedErrorsEnabled,
                         CancellationToken cancellationToken)
                     {
-                        var relationalCommand = relationalCommandCache.GetRelationalCommand(queryContext.ParameterValues);
+                        var relationalCommandTemplate = relationalCommandCache.GetRelationalCommand(queryContext.ParameterValues);
+                        var relationalCommand = queryContext.Connection.RentCommand();
+                        relationalCommand.PopulateFrom(relationalCommandTemplate);
 
                         return await relationalCommand.ExecuteReaderAsync(
                             new RelationalCommandParameterObject(

```

...to make `PopulateSplitCollection` like `PopulateSplitIncludeCollection` and only reuse the `CommandText` and not the `RelationCommand`'s `_relationalReader`.

**Comment by billybraga** [comment] 2021-08-20 16:10
I've reproduced the problem with some unit tests and my patch seems to do the trick. Would it help if I opened at PR with the fix?

**Comment by smitpatel** [comment] 2021-08-21 00:06
Co-assigning @roji who worked on the feature adding RentCommand and friends.

**Comment by ajcvickers** [comment] 2021-08-23 19:10
Removing from milestone to discuss in triage.

**Comment by roji** [comment] 2021-08-23 19:15
@billybraga thanks for the high-quailty investigation, fix proposal and tests - everything you say is accurate. In 5.0, IRelationalCommand was completely stateless, and so multiple threads could execute it concurrently with no issue. In 6.0, as part of the query performance optimizations, IRelationalCommand now has state, including a cached _relationalReader (but also _stopwatch).

Your proposed fix is good - please submit the commit above as a PR. I'd go a step further and change RelationalCommandCache to no longer hold an IRelationalCommand, but rather something else that isn't executable (e.g. IRelationalCommandTemplate), to make sure this kind of bug doesn't occur again.

**Comment by billybraga** [comment] 2021-08-24 11:23
@roji I submitted the PR but it doesn't seem to link itself with the issue. Also, in the PR I mentionned another possible issue that I see.

**Comment by roji** [comment] 2021-08-24 13:46
@billybraga manuallyl inked the PR to the issue.

**Closed** 2021-08-24 18:25 UTC
Labels: type-bug, closed-fixed, customer-reported, area-query

**Comment by natehitze** [comment] 2021-08-24 18:47
Thanks everyone! Especially @billybraga
