### ISSUE TITLE
SqliteConventionSetBuilder.CreateModelBuilder() produces incorrect migrations

### ISSUE THREAD

**Issue by sliekens** [dotnet/efcore#34222] opened 2024-07-13 18:19 UTC
I noticed that `SqliteConventionSetBuilder.CreateModelBuilder()` usage results in different migrations code, compared to overriding `OnModelCreating(ModelBuilder)`. It's not only different, it's also not working correctly.

Specifically, the `Sqlite:Autoincrement` annotation is not generated when using the following model configuration:

``` csharp
var modelBuilder = SqliteConventionSetBuilder.CreateModelBuilder();
modelBuilder.Entity<Blog>();
optionsBuilder.UseModel(modelBuilder.FinalizeModel());
```

### Repro steps

I created two contexts
- `Blog1Context` with `override OnModelCreating(ModelBuilder)`
- `Blog2Context` with `SqliteConventionSetBuilder.CreateModelBuilder()` and `DbContextOptionsBuilder<TContext> UseModel(IModel)`

``` csharp
namespace Issue;

public class Blog
{
    public int Id { get; set; }
    public string? Url { get; set; }
}

public class Blog1Context : DbContext
{
    public DbSet<Blog> Blogs => Set<Blog>();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Data Source=blog1.db");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>();
    }

}

public class Blog2Context : DbContext
{
    public DbSet<Blog> Blogs => Set<Blog>();

    public Blog2Context(DbContextOptions<Blog2Context> options) : base(options)
    {
    }

    // Constructor for demo only
    public Blog2Context() : this(CreateOptions())
    {
    }

    // Usually this would be in a separate file like Program.cs
    private static DbContextOptions<Blog2Context> CreateOptions()
    {
        var optionsBuilder = new DbContextOptionsBuilder<Blog2Context>();
        optionsBuilder.UseSqlite("Data Source=blog2.db");

        var modelBuilder = SqliteConventionSetBuilder.CreateModelBuilder();
        modelBuilder.Entity<Blog>();
        optionsBuilder.UseModel(modelBuilder.FinalizeModel());

        return optionsBuilder.Options;
    }
}
```

Generate two migrations for each context:

``` sh
# OnModelCreating migrations (Blog1Context)
dotnet ef migrations add --context Blog1Context OnModelCreatingFirst
dotnet ef migrations add --context Blog1Context OnModelCreatingSecond

# UseModel migrations (Blog2Context)
dotnet ef migrations add --context Blog2Context UseModelFirst
dotnet ef migrations add --context Blog2Context UseModelSecond
```

#### Model snapshot

With `OnModelCreating`, the name of the `DbSet` property `"Blogs"` is used for the table name.

``` csharp
[DbContext(typeof(Blog1Context))]
partial class Blog1ContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

        modelBuilder.Entity("Issue.Blog", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Url")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Blogs");
            });
#pragma warning restore 612, 618
    }
}
```

With `UseModel`, the table name is singular form `"Blog"`, and the name of the `DbSet` property is not considered. This might be the expected behavior, but it is not clearly documented.

``` csharp
[DbContext(typeof(Blog2Context))]
partial class Blog2ContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

        modelBuilder.Entity("Issue.Blog", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Url")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Blog");
            });
#pragma warning restore 612, 618
    }
}
```

#### First migration

With `OnModelCreating`, `Sqlite:Autoincrement` annotation is added ✅:

``` csharp
/// <inheritdoc />
public partial class OnModelCreatingFirst : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Blogs",
            columns: table => new
            {
                Id = table.Column<int>(type: "INTEGER", nullable: false)
                    .Annotation("Sqlite:Autoincrement", true),
                Url = table.Column<string>(type: "TEXT", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Blogs", x => x.Id);
            });
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "Blogs");
    }
}
```

With `UseModel`, `Sqlite:Autoincrement` annotation is missing ❌:

``` csharp
/// <inheritdoc />
public partial class UseModelFirst : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Blog",
            columns: table => new
            {
                Id = table.Column<int>(type: "INTEGER", nullable: false),
                Url = table.Column<string>(type: "TEXT", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Blog", x => x.Id);
            });
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "Blog");
    }
}
```

#### Second migration

This second migration should be empty, since nothing changed.

With OnModelCreating ✅:

``` csharp
/// <inheritdoc />
public partial class OnModelCreatingSecond : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {

    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {

    }
}
```

With UseModel ❌:

It once again tries to remove the `Autoincrement` annotation... which was not added in the first place. Curiously, it does attempt to add the annotation in `Down`.

``` csharp
/// <inheritdoc />
public partial class UseModelSecond : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AlterColumn<int>(
            name: "Id",
            table: "Blog",
            type: "INTEGER",
            nullable: false,
            oldClrType: typeof(int),
            oldType: "INTEGER")
            .OldAnnotation("Sqlite:Autoincrement", true);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AlterColumn<int>(
            name: "Id",
            table: "Blog",
            type: "INTEGER",
            nullable: false,
            oldClrType: typeof(int),
            oldType: "INTEGER")
            .Annotation("Sqlite:Autoincrement", true);
    }
}
```

### Include provider and version information

EF Core version: 8.0.7
Database provider: Sqlite
Target framework: .NET 8.0.6
Operating system: Debian 12
IDE: VS Code 1.91.1

**Comment by ajcvickers** [comment] 2024-07-15 16:38
@sliekens 

> With UseModel, the table name is singular form "Blog", and the name of the DbSet property is not considered.

Yes, this is by-design.

@maumar This is almost certainly model building and should go to @AndriySvyryd.

**Comment by AndriySvyryd** [comment] 2024-07-17 01:19
Duplicate of https://github.com/dotnet/efcore/issues/33684

**Closed by AndriySvyryd** 2024-07-17 01:19 UTC
Labels: customer-reported
