### ISSUE TITLE
After call DBContext.Update property null

### ISSUE THREAD

**Issue by thanhnntq** [dotnet/efcore#12739] opened 2018-07-20 09:13 UTC
I'm using Entity Core 1.1 and when I call DbContext.Update and see in DbContext.Entry data not equal original object.
Before call Update
![image](https://user-images.githubusercontent.com/30698814/42994225-ac7bd770-8c37-11e8-946d-ebb1e21988ac.png)
After call Update and see in DbContext.Entry
![image](https://user-images.githubusercontent.com/30698814/42994255-c8418284-8c37-11e8-9afb-68a814839f0b.png)

Please help me! Thank you!

**Comment by divega** [comment] 2018-07-20 19:40
@thanhnntq can you please provide repro code as text?

**Comment by ajcvickers** [comment] 2018-07-27 15:53
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:20 UTC
Labels: closed-could-not-reproduce, customer-reported
