### ISSUE TITLE
DbContext Not Found or A relational store has been configured without specifying either the DbConnection or connection string to use.

### ISSUE THREAD

**Issue by vijayantkatyal** [dotnet/efcore#1352] opened 2015-01-03 17:11 UTC
when using  Entity Framework Commands ("7.0.0-beta1").

when running 

k ef migration add InitialCreate

i'm getting errors.

[Solution]

i try to move my Class File (where DbContext is created) to main project from separate class library and everything working as expected.

so the real problem is when using DbContext in separate Class Library.

my dbcontext file

``` C#
public class DbTables : DbContext
{

        public DbSet<class_name> class_name_alias { get; set; }

        private static bool _created = false;

        public DbTables()
        {
            if (_created)
            {
                Database.AsRelational().ApplyMigrations();
                _created = true;
            }
        }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(@"Data Source=(LocalDB)\MSSQLLocalDB;Initial Catalog=app_db;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False");
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }

    }
```

**Comment by bricelam** [comment] 2015-01-05 16:51
On which project are you running `k ef`? What does your `Startup.cs` file look like?

**Comment by vijayantkatyal** [comment] 2015-01-05 19:05
i'm running k ef command on main project, 

using System;
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Diagnostics;
using Microsoft.AspNet.Diagnostics.Entity;
using Microsoft.AspNet.Hosting;
using Microsoft.AspNet.Routing;
using Microsoft.Data.Entity;
using Microsoft.Framework.ConfigurationModel;
using Microsoft.Framework.DependencyInjection;
using Microsoft.Framework.Logging;
using Microsoft.Framework.Logging.Console;

namespace App
{
    public class Startup
    {

        public void ConfigureServices(IServiceCollection services)
        {
            // ISSUE
            services.AddEntityFramework().AddSqlServer().AddDbContext<App.DbTables>();

            
            services.AddMvc();
            services.AddSingleton<IContinents, ContinentRepository>();
        }

        public void Configure(IApplicationBuilder app,IHostingEnvironment env,ILoggerFactory loggerfactory)
        {
            loggerfactory.AddConsole();

            if(string.Equals(env.EnvironmentName,"Development",System.StringComparison.OrdinalIgnoreCase))
            {
                app.UseErrorPage(ErrorPageOptions.ShowAll);
                app.UseDatabaseErrorPage(DatabaseErrorPageOptions.ShowAll);
            }
            else
            {
                app.UseErrorHandler("/home/error");
            }

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller}/{action}/{id?}",
                    defaults: new { controller = "Home", action = "Index" });
            });
        }
    }
}

**Comment by bricelam** [comment] 2015-01-05 23:59
Ah, this is a duplicate of #823. We currently only call `Startup.ConfigureServices()` if it's in the same project as the DbContext. The default constructor of `DbTables` is preventing things from working without `Startup`. If you remove it, it should work. I recommend calling `ApplyMigrations` inside of `Startup.Configure` instead.

**Comment by vijayantkatyal** [comment] 2015-01-06 11:49
Thanks it worked. i applied migration on class library itself instead of calling Startup.ConfigureServices().

**Closed** 2022-10-16 08:48 UTC
