### ISSUE TITLE
EF Core 3.1 does not track owned entity in some cases

### ISSUE THREAD

**Issue by aochagavia** [dotnet/efcore#19892] opened 2020-02-12 13:42 UTC
For the last day I have been trying to upgrade from EF Core 2.2.6 to version 3.1.1 without success. Some of my tests are failing and I have finally managed to come up with a minimum reproducible example. It seems like I have hit a bug, or at least an undocumented breaking change.

Note 1: I set up a [repository](https://github.com/aochagavia/efcore-issue-repro) with the code for this example and xUnit tests that make the problem clearer. The master branch uses EF Core 3.1.1 and has one failing test. The ef2 branch uses EF Core 2.2.6 and the same tests pass.

Note 2: the problem doesn't happen when using the InMemory database provider. It does happen when using the SqlServer provider.

I have a parent entity (`Registration`) and an owned child entity (`Contact`):

```csharp
public class Registration
{
    public Guid Id { get; set; }
    public Contact Contact { get; set; }

    public Registration()
    {
        Contact = new Contact();
    }
}

public class Contact
{
    public string LastName { get; set; }
}
```

The relation between them is specified as follows in the `DbContext`:

```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Registration>()
        .OwnsOne(p => p.Contact);
}
```

The problem appears when following these steps (all with their own `DbContext`):

1. Create a `Registration` with a `Contact` where all the fields are null
1. Set one of the `Contact` fields to some value for the `Registration` we just created
1. Retrieve the `Registration`

I would expect the retrieved registration to contain the updated `Contact` field. However, it turns out the update was not saved by EF Core. I have done some debugging and I can see that EF Core is not tracking any object of type `Contact`.

The following code reproduces the issue in the steps I mentioned (see also https://github.com/aochagavia/efcore-issue-repro/blob/master/EfCoreExample.Tests/RawTests.cs):

```csharp
Guid? id;
using (var db = new Db())
{
    var registration = new Registration();
    db.Registrations.Add(registration);
    db.SaveChanges();
    id = registration.Id;
}

using (var db = new Db())
{
    var registration = db.Registrations.Find(id);
    registration.Contact.LastName = "Dummy";
    db.SaveChanges();
}

using (var db = new Db())
{
    var registration = db.Registrations.Find(id);
    Assert.Equal("Dummy", registration.Contact.LastName);
}
``` 

I have observed that things do work when the second step creates a new `Contact` object from scratch and assigns that to the `Registration`, instead of trying to modify the existing `Contact`. Then EF Core does pick up the change and everything is saved correctly.

I have also observed that things do work when the first step creates a `Registration` with at least one non-null field in the `Contact`. Then EF Core picks up later changes, even without replacing the `Contact` field.

Is this a bug? It was not listed among the breaking changes introduced by EF Core 3.

### Further technical details

EF Core version: 3.3.1 (I couldn't reproduce it in 2.2.6)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10

**Comment by AndriySvyryd** [comment] 2020-02-13 20:13
Duplicate of https://github.com/dotnet/efcore/issues/18007

**Closed** 2022-10-16 18:10 UTC
Labels: closed-duplicate, customer-reported
