### ISSUE TITLE
The call is ambiguous - EntityFrameworkQueryableExtensions.Include

### ISSUE THREAD

**Issue by johanskoldekrans** [dotnet/efcore#9602] opened 2017-08-28 09:31 UTC
@inject SomeContext Ctx
@using Microsoft.EntityFrameworkCore;

When injecting the context in a view I now get:

The call is ambiguous between the following methods or properties: ```
'EntityFrameworkQueryableExtensions.Include<TEntity, TProperty>(IQueryable<TEntity>, Expression<Func<TEntity, TProperty>>)' 
and 
'EntityFrameworkQueryableExtensions.Include<TEntity, TDerived, TProperty>(IQueryable<TEntity>, Expression<Func<TDerived, TProperty>>)'

### Further technical details
EF/.Net Core version: 2.1.0-preview1-26816
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10
IDE: VS 2017 15.3.2

**Comment by smitpatel** [comment] 2017-08-28 18:17
@johanskoldekrans - Can you share the code which is throwing the error?

**Comment by johanskoldekrans** [comment] 2017-08-28 19:20
I will be out of office for a few days but it was a simple ctx.table with an include and a where clause. Nothing fancy so I wrote a helper class instead (which I should have in the first place).

The injects with a call to the db should do it from the view.

> 28 aug. 2017 kl. 20:18 skrev Smit Patel <notifications@github.com>:
> 
> @johanskoldekrans - Can you share the code which is throwing the error?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 

www.penser.se
Disclaimer: www.penser.se/disclaimer

**Comment by smitpatel** [comment] 2017-08-28 19:22
@johanskoldekrans - Are you using Reflection anywhere?

**Comment by johanskoldekrans** [comment] 2017-08-28 20:37
No, I don't think we use it on this project.

> 28 aug. 2017 kl. 21:23 skrev Smit Patel <notifications@github.com>:
> 
> @johanskoldekrans - Are you using Reflection anywhere?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 

www.penser.se
Disclaimer: www.penser.se/disclaimer

**Comment by smitpatel** [comment] 2017-08-29 17:03
@johanskoldekrans - With #3910 being fixed in 2.1.0 we have added more overloads for `Include`. I tried simple dbset.inclue.where query but it works correctly for me. For some reason the code you wrote is failing to find the correct overload to use. We would need exact code listing to investigate further.

**Comment by johanskoldekrans** [comment] 2017-08-29 17:37
Just woke up from surgery, can you send me your code so maybe I can wreck it with my dbcontext when I get home on Thursday.



> 29 aug. 2017 kl. 19:03 skrev Smit Patel <notifications@github.com>:
> 
> @johanskoldekrans - With #3910 being fixed in 2.1.0 we have added more overloads for Include. I tried simple dbset.inclue.where query but it works correctly for me. For some reason the code you wrote is failing to find the correct overload to use. We would need exact code listing to investigate further.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 

www.penser.se
Disclaimer: www.penser.se/disclaimer

**Comment by johanskoldekrans** [comment] 2017-09-04 07:55
Just downgraded to .net core 2.0 because I couldn't find the windows hosting and preview1-* stopped working on server hosting version 2.0.0. I am rewriting a lot of stuff now to avoid the bugs introduced in the first version.

But how do you configure the service? Does that have anything to do with how the injection works?

**Comment by johanskoldekrans** [comment] 2017-09-04 07:57
Otherwise close this and I can try later. Same code worked for me in code-behind so it has to do something with the injection-mechanism or other related functionality. The overloads itself seems to be working fine. Otherwise I should have had thousands of errors in code-behind.

**Comment by ajcvickers** [comment] 2017-09-07 00:10
@johanskoldekrans We have been unable to reproduce the original issue, so closing this for now. If you can come up with a code listing/scenario/project that repros it, then we'd love to know. Your other comments don't seem related to the original issue--please file new issues with full details if you believe there are other EF Core bugs that need to be addressed.

**Comment by johanskoldekrans** [comment] 2017-09-07 07:10
Sorry I couldn't find the time to make a solution to reproduce the problem. I am the sole developer for a bank and are working four major projects on my own. There is no time to isolate the code. I just need to workaround as fast as I can. When I get an error like this, do you have any ideas of what I should save or log that could be of help with minimum effort? I really would like to help you guys and I feel bad when I can't find the time to make you guys a clean solution for reproducing.

Best regards,

Johan

**Closed** 2022-10-16 11:18 UTC
Labels: closed-could-not-reproduce
