### ISSUE TITLE
How to map a model to different tables dynamically in dbcontext

### ISSUE THREAD

**Issue by CatherineXiaoQiao** [dotnet/efcore#24913] opened 2021-05-17 01:43 UTC
I working on a scenario that one model would be mapped to different tables, and all those tables have the same structure. 
The model name is like this: TempABC,  tables would be like this: TempABC0001, TempABC0002......

 I have found an article on how to do this in Microsoft document library.  
[Alternating between multiple models with the same DbContext type](https://docs.microsoft.com/en-us/ef/core/modeling/dynamic-model). I followed the instruction adding code to my project, but it doesn't work at all which reminds me that is this feature only working under the latest version of EF CORE? My project is under EFCORE 3.1.14 NOT 5.0.

**Comment by AndriySvyryd** [comment] 2021-05-18 19:25
`IModelCacheKeyFactory` is supported in all versions of EF Core. Please share a small repro project for us to investigate further.

**Comment by ajcvickers** [comment] 2021-05-27 16:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:34 UTC
Labels: closed-could-not-reproduce, customer-reported
