### ISSUE TITLE
Async query on UWP throws InvalidOperationException: 'System.Reflection.MemberInfo.get_MetadataToken() cannot be used on the current platform'

### ISSUE THREAD

**Issue by UppaJung** [dotnet/efcore#6088] opened 2016-07-15 16:16 UTC
[Also posted as https://github.com/aspnet/Microsoft.Data.Sqlite/issues/277]
### Steps to reproduce

```
public class DeviceKey
{
        [Key]
        public string Key { get; set; }

        public int ParticipantId { get; set; }

        public DeviceKey()
        {
        }

        public static async Task<DeviceKey> GetAsync(ScreenTimeContext dbContext)
        {
            return await
                (from r in dbContext.DeviceKeys
                 select r)
                 .FirstOrDefaultAsync();
        }
}
```
### The issue

The query in GetAsync results in the following exception:

Exception:
System.InvalidOperationException

The API 'System.Reflection.MemberInfo.get_MetadataToken()' cannot be used on the current platform. See http://go.microsoft.com/fwlink/?LinkId=248273 for more information."

at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
### Further technical details

Platform: UWP (running via a compile to x86), VS15 update 3

```
"Microsoft.ApplicationInsights": "2.1.0",
"Microsoft.ApplicationInsights.PersistenceChannel": "1.2.3",
"Microsoft.ApplicationInsights.WindowsApps": "1.1.1",
"Microsoft.EntityFrameworkCore": "1.0.0",
"Microsoft.EntityFrameworkCore.Sqlite": "1.0.0",
"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
"Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0",
"Newtonsoft.Json": "9.0.1"
```

**Comment by natemcmaster** [comment] 2016-07-22 17:47
@UppaJung I tried to reproduce the issue using the details you shared, but did not succeed in getting the any error messages. Can you share a zip up a full repro project that reproduces the issue and share it here?

**Comment by natemcmaster** [comment] 2016-08-01 18:11
I'm closing this issue because I could not reproduce the issue and have not heard back on the request for more details. Please feel free to share more information and we can re-open the issue for further investigation.

Also worth noting: I did not find any references to MemberInfo.MetadataToken in EF. This error may originate from an external component.

**Comment by UppaJung** [comment] 2016-08-01 22:27
[EntityFrameworkBug6088.zip](https://github.com/aspnet/EntityFramework/files/394888/EntityFrameworkBug6088.zip)

**Comment by natemcmaster** [comment] 2016-08-01 23:01
Thanks for sharing a repro. This repro still does not throw the error described above. Can you make sure you have the latest UWP tools installed? https://developer.microsoft.com/en-us/windows/downloads. The latest is "Tools (1.4) and Windows 10 SDK (10.0.10586)".

----
_Side note, unrelated to reproducing the "InvalidOperationException" message._

The repro includes this:
```c#
public static async Task<Participant> GetAsync(ScreenTimeContext dbContext, int participantId)
{
    return (await
    (from r in dbContext.Participants
     where r.Id == participantId
     select r).FirstOrDefaultAsync());
}
```
This deadlocks on UWP query, likely due to a bug in Ix-Async similar to #5481 (cc @anpete). The solution for the deadlock is to use the sync version (async on SQlite doesn't buy you much since SQLite itself is synchronous) or remove the async/await keywords.

**Comment by UppaJung** [comment] 2016-08-03 17:12
Updated solution for repro.
[EntityFrameworkBug6088v2.zip](https://github.com/aspnet/EntityFramework/files/399995/EntityFrameworkBug6088v2.zip)

Regarding the use of async, I'm trying to write code that can be used both on the client-side UWP app to access local copies of data structures and on the server side (REST) to access the server's copies of the data structures.  I'm using async methods for the server-side benefits.  I realize I'm not getting any benefits from async on the client side, but sticking with the async methods seems preferable to maintaining two copies of code that both do the exact same thing.

Is there already a c# feature request to auto-generate a non-async version of every async method?  This would likely save developers from duplicating code in many situations and encourage more developers to write async methods for their libraries.

**Comment by natemcmaster** [comment] 2016-08-03 18:43
I communicated offline with @UppaJung. Even with the repro project above, I cannot reproduce the error even on a machine with a fresh install of VS2015 U3. I suspect this is an issue with UWP tooling in Visual Studio. I'm closing this because as mentioned before, EF Core itself doesn't use the "MemberInfo.MetadataToken" API and this appears to be external to EF.

As mentioned above, we discovered a secondary issue in this investigation. That async issue is tracked in #6238 

> Is there already a c# feature request to auto-generate a non-async version of every async method?

Re @UppaJung: Checkout https://github.com/dotnet/roslyn. This one kind of looks what you are asking for: https://github.com/dotnet/roslyn/issues/7769

**Closed by natemcmaster** 2016-08-03 18:43 UTC
Labels: closed-could-not-reproduce
