### ISSUE TITLE
After upgrading to .NET 8, OrderBy(x => x.StringProperty.StartsWith(query)) in a LINQ to SQL tree deletes results that do not StartWith(query).

### ISSUE THREAD

**Issue by MediocreFantasy** [dotnet/efcore#32436] opened 2023-11-28 14:13 UTC
Good morning! In our application, we have a LINQ to SQL tree like the following:

```C#
var primaryList = db.Customers.Where(c => c.CompanyName.ToLower().Contains(query))
                                .OrderByDescending(x => x.CompanyName.ToLower().StartsWith(query)))
                             .Take(50)
                             .AsSplitQuery()
                             .Select(x => new CustomerViewModel(x)) //
                             .ToList();
```

Before our upgrade to .NET 8, this query would get matching customers and have the ones whose names started with the query at top. For example, "Frank" would return "Frank's Catering", "Frank & Sons Construction", "John Frank Tax Consultant"; the use case that matters more here is when there are no customers who StartWith the given query, such as when "Police" returns "Local Town Police Station", "Other Local Town Police Department", "State Police Museum" and so on. After the upgrade, with no changes to the queries, Frank now only returns "Frank's Catering" and "Frank & Sons Construction", and "Police" returns zero results.

### Replication steps:
Given a table for an ExampleEntity that has at least one StringProperty, set up a query such as:
```C#
var query = "test";
var results = db.ExampleEntities.OrderBy(x => x.StringProperty.ToLower().Contains(query)).ToList();
//Expected results: All entities on that table, with the ones whose StringProperty contains "test" on top.
//Actual results on my machine: Same as expected results.

var otherQuery = "test";
var otherResults = db.ExampleEntities.OrderBy(x => x.StringProperty.ToLower().StartsWith(query)).ToList();
//Expected results: All entities on that table, with the ones whose StringProperty starts with "test" on top.
//Actual results on my machine: Only the entities on that table whose StringProperty starts with "test" with all others excluded. 
```

### Currently implemented workaround:
For the time being, we will be working around this by removing the StartsWith method from the ordering logic.

### Include provider and version information

EF Core version: 8.0.0
Database provider: "Microsoft SQL Server Express (64-bit)" running on "Windows Server 2022 Standard (10.0)" accessed in code via the "Microsoft.EntityFrameworkCore" package.
Target framework:  .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.8.0

**Comment by roji** [comment] 2023-11-28 17:09
This looks like a duplicate of #32432; if so, a fix has already been merged to main, and we'll hopefully also fix this for 8.0.2.

To confirm, can you please try to use a different .NET variable as the argument to Contains and StartWith? In order words, you can tweak your query as follows:

```c#
var query2 = query;
var primaryList = db.Customers.Where(c => c.CompanyName.ToLower().Contains(query))
                                .OrderByDescending(x => x.CompanyName.ToLower().StartsWith(query2)))
                             .Take(50)
                             .AsSplitQuery()
                             .Select(x => new CustomerViewModel(x)) //
                             .ToList();
```

If this makes your query work correctly, then it's indeed a duplicate of #32432, and you can use that technique as a workaround.

**Comment by roji** [comment] 2023-11-28 19:50
@MediocreFantasy no problem at all, thanks for reporting!

**Comment by roji** [comment] 2023-11-28 19:50
Duplicate of #32432

**Closed by roji** 2023-11-28 19:50 UTC
Labels: customer-reported
