### ISSUE TITLE
Using Select (for filtering included entity) results in querying the entire tables without a WHERE caluse!

### ISSUE THREAD

**Issue by gdoron** [dotnet/efcore#5808] opened 2016-06-18 21:48 UTC
### Steps to reproduce

Query: 

```
var story = Context.Stories
   .Include(x => x.User)
   .Include(x => x.Tips)
   .Include(x => x.Comments)
   .ThenInclude(x=> x.User)
   .Select(x => new Story
                    {
                        Text = x.Text,
                        Title = x.Title,
                        Comments = x.Comments.Where(c => !c.IsDeleted).ToList(),
                        Images = x.Images,
                        StoryTags = x.StoryTags,
                        User = x.User,
                        Id = x.Id,
                        Tips = x.Tips,
                        InsertDate = x.InsertDate,
                        MainImageUrl = x.MainImageUrl,
                        StoryLimitations = x.StoryLimitations,
                        StoryProducts = x.StoryProducts,
                        UserId = x.UserId,
                        YouTubeUrl = x.YouTubeUrl
                    })
   .First(x => x.Text.Contains("Alana has been"));
```

Classes:

```
public class Story
{
    public int Id { get; set; }
    public ApplicationUser User { get; set; }
    public int UserId { get; set; }
    public string Title { get; set; }
    public string Text { get; set; }
    public bool IsPublished { get; set; }
    public string YouTubeUrl { get; set; }
    public DateTime InsertDate { get; set; }
    public string MainImageUrl { get; set; }
    public List<StoryTip> Tips { get; set; }
    public List<StoryImage> Images { get; set; }
    public List<StoryTag> StoryTags { get; set; }
    public List<StoryComment> Comments { get; set; }

    public List<StoryProduct> StoryProducts { get; set; }
    public List<StoryLimitation> StoryLimitations { get; set; }
}

public class StoryComment
{
    public int Id { get; set; }
    public ApplicationUser User { get; set; }
    public int UserId { get; set; }
    public string Title { get; set; }
    public string Text { get; set; }
    public DateTime InsertDate { get; set; }
    public bool IsDeleted { get; set; }

    public Story Story { get; set; }
    public int StoryId { get; set; }
}    
```
### The issue

The generated SQL from the trace:

```
SELECT [x.User].[Id], [x.User].[AboutMe], [x.User].[AccessFailedCount], [x.User].[ConcurrencyStamp], [x.User].[Country], [x.User].[Email], [x.User].[EmailConfirmed], [x.User].[FirstName], [x.User].[InsertDate], [x.User].[LastName], [x.User].[LockoutEnabled], [x.User].[LockoutEnd], [x.User].[NormalizedEmail], [x.User].[NormalizedUserName], [x.User].[PasswordHash], [x.User].[PhoneNumber], [x.User].[PhoneNumberConfirmed], [x.User].[PictureUrl], [x.User].[SecurityStamp], [x.User].[TwoFactorEnabled], [x.User].[UserName], [x].[Text], [x].[Title], [x].[Id], [x].[InsertDate], [x].[MainImageUrl], [x].[UserId], [x].[YouTubeUrl]
FROM [Stories] AS [x]
INNER JOIN [Users] AS [x.User] ON [x].[UserId] = [x.User].[Id]
WHERE [x].[Id] = 1

SELECT [c].[Id], [c].[InsertDate], [c].[IsDeleted], [c].[StoryId], [c].[Text], [c].[Title], [c].[UserId]
FROM [StoryComments] AS [c]
WHERE [c].[IsDeleted] = 0

SELECT [s].[Id], [s].[StoryId], [s].[Url]
FROM [StoryImage] AS [s]

SELECT [s1].[Id], [s1].[InsertDate], [s1].[Order], [s1].[StoryId], [s1].[Text]
FROM [StoryTips] AS [s1]        

SELECT [s2].[LimitationId], [s2].[StoryId]
FROM [StoryLimitation] AS [s2]

SELECT [s3].[StoryId], [s3].[ProductId]
FROM [StoryProduct] AS [s3]
```
### Further technical details

EF Core version: RC2-final
Operating system: Win 10, SQL Server 12

A. Why there's no WHERE in the queries?
B. How can I force EF to run all these queries within a single SQL query with joins (please don't tell me From Sql)?

If needed, I can add you as collaborators to the private GitHub repository.

**Comment by gdoron** [comment] 2016-06-18 21:49
Related to #5807

**Comment by gdoron** [comment] 2016-06-20 17:32
@rowanmiller @divega Did you see this bug report?
I think it's a critical bug.
Unless one would check the trace for the actual executed query, it can go unnoticed and explode on production.

**Comment by ErikEJ** [comment] 2016-06-20 17:50
@gdoron I think you could disable client evaluation...

**Comment by gdoron** [comment] 2016-06-20 18:02
Yes, you're right, but not per query basis, and sometimes it is handy client side evaluation.
Anyway, it will just explode early, not fix the problem....

**Comment by rowanmiller** [comment] 2016-06-21 17:54
Closing as dupe of https://github.com/aspnet/EntityFramework/issues/5738

**Comment by IDisposable** [comment] 2016-06-24 16:27
Why wouldn't you have written the query as
```
var story = Context.Stories
   .Include(x => x.User)
   .Include(x => x.Tips)
   .Include(x => x.Comments)
   .ThenInclude(x=> x.User)
   .Where(x => x.Text.Contains("Alana has been"))
   .Select(x => new Story
                    {
                        Text = x.Text,
                        Title = x.Title,
                        Comments = x.Comments.Where(c => !c.IsDeleted).ToList(),
                        Images = x.Images,
                        StoryTags = x.StoryTags,
                        User = x.User,
                        Id = x.Id,
                        Tips = x.Tips,
                        InsertDate = x.InsertDate,
                        MainImageUrl = x.MainImageUrl,
                        StoryLimitations = x.StoryLimitations,
                        StoryProducts = x.StoryProducts,
                        UserId = x.UserId,
                        YouTubeUrl = x.YouTubeUrl
                    })
   .First();
```

(sidenote, SQL's `SELECT` field-list coming first is the worst defect of SQL.... it should have been last)

**Closed** 2022-10-16 09:45 UTC
