### ISSUE TITLE
Why can't EF serialize classes in models?

### ISSUE THREAD

**Issue by strich** [dotnet/efcore#5299] opened 2016-05-09 09:30 UTC
Suppose I have the following model:

``` csharp
public class Project {
    public int Id { get; set; }
    public Organization Organization { get; set; }
    public string Name { get; set; }
    public ICollection<Build> BuildHistory { get; set; }
    public string GitServerURL { get; set; }
    public int BuildNumberCounter { get; set; }

    public Deployment DeploymentConfig { get; set; }
}
```

The `Deployment` class is a stub - Its unique to every project and will never be shared with anything else. It'll only ever be accessed through a `Project`. It is just a collection of properties really. It could be flattened out into the `Project` class, but there are code cleanliness benefits to encapsulating them for use elsewhere in the application.

The problem I have is that it is quite a large amount of work to support this - I have to create and manage everything that goes along with `Deployment` being its own table in EF. 

The question I have is: Is there not a good reason to have the option to serialize some classes into the parent table (`Project`)?

This could be achieved either by automatically flattening to columns such as `DeploymentConfig_PropertyName` or serializing the whole thing into a single column with JSON. I realize I could probably write my own solution with backing fields or something, but this would seem like a pretty good feature request no?

**Comment by smitpatel** [comment] 2016-05-09 14:25
dupe of #246

**Comment by strich** [comment] 2016-05-09 15:32
Going to close this issue as it is a dupe of an existing feature request.

**Closed** 2022-10-16 09:39 UTC
