### ISSUE TITLE
Adding IDENTIFY to a an existing column

### ISSUE THREAD

**Issue by JanC89** [dotnet/efcore#7642] opened 2017-02-17 11:26 UTC
This is not exactly a bug, but the scenario described might benefit from a warning. 
It has to do with adding IDENTITY to an existing column.

### Steps to reproduce

1. Create a model with an ID and a additional field which you would want to be an IDENTITY column. 
```c#
public class WorkEmployment
{
        public int ID { get; set; }
        public int AnotherFieldWithIdentity { get; set; }
}
```
Notice that I "forgot" to add `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]` to the second field. 

2. Add a migration to add to the database `dotnet ef migrations add Test`
3. Update the datebase: `dotnet database update`
4. At this point you realize you forgot to add the IDENTITY flag, so you update the model (and add a new migration)
```c#
public class WorkEmployment
{
        public int ID { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AnotherFieldWithIdentity { get; set; }
}
```
5. If you inspect the migration, it will correctly have an alter column statement with the following: 
`Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)`

The problem is that (at least for MSSQL) you cannot add identity to an existing column. However, the migration will run without any errors or warnings - so you might think that the identity was correctly added. 

Would it be an idea to raise a warning in such cases?

### Further technical details
EF Core version: 1.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by ajcvickers** [comment] 2017-02-17 17:14
@JanC89 Given that the 'ID' column is identity by convention and that SQL Server can only have one identity column per table, what is the behavior you would expect for this scenario?

**Comment by ajcvickers** [comment] 2017-02-17 17:16
At least assuming only one identity column per table, this is a dupe of #5345 which is fixed in 1.1.

**Comment by rowanmiller** [comment] 2017-02-17 19:04
Closing as dupe of #5345

**Comment by JanC89** [comment] 2017-02-17 22:20
@ajcvickers 

I can see my example was not the best. 
The scenario I experienced was the following:

I had a "bridge"/join table to support a many-to-many relation. 
```c#
            builder.Entity<WorkEmployment>()
                .HasKey(x => new { x.EmployeeID, x.ProjectID });
            builder.Entity<WorkEmployment>()
                .HasOne(x => x.Employee)
                .WithMany(x => x.WorkEmployments).
                HasForeignKey(x => x.EmployeeID);

            builder.Entity<WorkEmployment>()
                .HasOne(x => x.Project)
                .WithMany(x => x.WorkEmployments).
                HasForeignKey(x => x.ProjectID);
```
with the model:
```c#
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public virtual Employee Employee { get; set; }
        public int ProjectID { get; set; }
        public virtual Project Project { get; set; }
```

When EF created the migration/table it didn't make the ID a key or IDENTITY (I know from a DB design point of view having the ID key is not needed as you have the composite key). 

So I changed to the following:
```c#
builder.Entity<WorkEmployment>()
                .HasKey(x => new { x.EmployeeID, x.ProjectID });
            builder.Entity<WorkEmployment>()
                .HasAlternateKey(x => new { x.ID });

            builder.Entity<WorkEmployment>()
                .HasOne(x => x.Employee)
                .WithMany(x => x.WorkEmployments).
                HasForeignKey(x => x.EmployeeID);

            builder.Entity<WorkEmployment>()
                .HasOne(x => x.Project)
                .WithMany(x => x.WorkEmployments).
                HasForeignKey(x => x.ProjectID);
```
and model:
```c#
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public virtual Employee Employee { get; set; }
        public int ProjectID { get; set; }
        public virtual Project Project { get; set; }
```

The migration created after these changed did in fact specity that the ID should be an IDENTITY column. But, since you cannot make a column an IDENTITY after it has been created, the column wasn't updated. 

Bottomline, when EF created a migration which alters a column and adds the IDENTITY annotation to a column, I think a warning should be raised as it is not supported on MSSQL.

**Comment by ajcvickers** [comment] 2017-02-17 23:29
@JanC89 For that case this seems to be a pure dupe of #5345.

**Comment by rowanmiller** [comment] 2017-02-17 23:32
Just to be explicit, #5345 is closed as fixed and the operation will throw if you upgrade to 1.1.

**Comment by JanC89** [comment] 2017-02-18 19:10
@ajcvickers @rowanmiller 

Thanks! I didn't saw that fix - sorry about that.

**Closed** 2022-10-16 10:53 UTC
