### ISSUE TITLE
Scaffolding stopped working: More than one DbContext/Missing Parameterless Constructor

### ISSUE THREAD

**Issue by maybevs** [dotnet/efcore#22423] opened 2020-09-06 15:50 UTC
After scaffolding and using 5 controllers there is suddenly a problem when I try to add another one.
First I had a dublicate DbContext (from Identity) but when I remove that one the scaffolding suddenly requires a parameterless ctor.
I can't figure out, why after 5 controllers before this one I'm now blocked from going any further, completely restructuring my DbContexts, or need to add new Ctors to my Context that weren't required before.

### Steps to reproduce
No Idea honestly.. The problem was just showing up suddenly and I couldn't find out why. I didn't touch the DbContext since I made the initial models.

The Model is very simple:
```
 public class MessagesModel
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Überschrift")]
        public string Title { get; set; }
        [Display(Name = "Text")]
        public string Body { get; set; }
    }
```

My Context currently looks like this:

```
public class TrainingCapacityDefaultContext : IdentityDbContext<ApplicationUser>
    {
        public TrainingCapacityDefaultContext(DbContextOptions<TrainingCapacityDefaultContext> options)
            : base(options)
        {
        }

        public DbSet<TrainingCapacityManagement.Models.Gym> Gym { get; set; }

        public DbSet<TrainingCapacityManagement.Models.GymSegment> GymSegment { get; set; }

        public DbSet<TrainingCapacityManagement.Models.Sport> Sport { get; set; }

        public DbSet<TrainingCapacityManagement.Models.Training> Training { get; set; }

        public DbSet<TrainingCapacityManagement.Models.TrainingsRegistration> TrainingsRegistration { get; set; }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }
    }

```

And I removed this part from IdentityHostingStartup (which was not commented during the first 5 scaffoldings, but again they worked without problem, but now suddenly the two DbContexts confuse EF):
```
namespace TrainingCapacityManagement.Areas.Identity
{
    public class IdentityHostingStartup : IHostingStartup
    {
        public void Configure(IWebHostBuilder builder)
        {
            builder.ConfigureServices((context, services) => {
                //services.AddDbContext<TrainingCapacityDefaultContext>(options =>
                //    options.UseSqlServer(
                //        context.Configuration.GetConnectionString("TrainingCapacityDefaultContext")));

                services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
                .AddRoles<IdentityRole>()
                    .AddEntityFrameworkStores<TrainingCapacityDefaultContext>();
            });
        }
    }
}
```

### Further technical details

EF Core version: 3.1.7.
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.2

**Comment by ajcvickers** [comment] 2020-09-08 17:28
@maybevs It's hard to know exactly what is going on without being able to reproduce what you are seeing, but it is likely due to discovery of the DbContext. The documentation for this is here: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation If you're sure that your following one of the recommended approaches, then please attempt to attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-09-18 15:16
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:39 UTC
Labels: closed-could-not-reproduce, customer-reported
