### ISSUE TITLE
Entity Framework build weird SQL when querying a Custom ValueConverter

### ISSUE THREAD

**Issue by TarquinQ** [dotnet/efcore#19966] opened 2020-02-19 00:44 UTC
Hi, I have a code-first Entity Framework setup. I am using a Model that utilises a custom ValueConverter to convert to/from a string <-> List<String> -- which works really well when storing & loading data to/from Models, but querying is a little bit off. And by a little bit, I mean a lot. :)

.Net Core 3.1, C# 8, Entity Framework 3.1.
Database is SQL Local 2019.
dbContext injected into a Controller by ASP.Net Core 3.1

Query:
``` C#
bool a = await this._dbContext.IdentityPrincipals
                    .Where(p => p.AssignedRoles.Contains(Roles.Administrator))
                    .AnyAsync();
```

Expected SQL (ok, I'm not expecting this exact SQL, and am paraphrasing quite a bit, but something like this idea):
``` SQL
      SELECT * FROM IdentityPrincipals
          WHERE AssignedRoles LIKE '%Administrator%'
      END
```

But the *Actual* SQL is:
``` SQL
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT CASE
          WHEN EXISTS (
              SELECT 1
              FROM [IdentityPrincipals] AS [i]
              WHERE CAST(1 AS bit) = CAST(0 AS bit)) THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END
```

### Steps to reproduce

``` C#
    public sealed class Roles
    {
        public const string Administrator = "Administrator";
        public const string ReadOnly = "ReadOnly";
    }

    public static class AllRoles
    {
        public static IEnumerable<string> Roles { get; } = new HashSet<string>();

        static AllRoles()
        {
            foreach (FieldInfo field in typeof(Roles).GetFields())
            {
                ((HashSet<string>)Roles).Add(field.Name);
            }
        }
    }

    public class IdentityPrincipal
    {
        public List<string> AssignedRoles { get; set; } = new List<string>(new string[] { Roles.ReadOnly } );
    }

    public class SignerContext : DbContext
    {
        public SignerContext(DbContextOptions<SignerContext> options)
            : base(options)
        {
        }

        public DbSet<IdentityPrincipal> IdentityPrincipals { get; set; } = null!;
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            var listValueComparer = new ValueComparer<List<string>>(
                (d1, d2) => d1.SequenceEqual(d2),
                d => d.GetHashCode(),
                d => d.ToList<string>());

            modelBuilder.Entity<IdentityPrincipal>().ToTable("IdentityPrincipals");
            modelBuilder.Entity<IdentityPrincipal>()
                .Property(e => e.AssignedRoles)
                .HasMaxLength(200)
                .HasConversion(
                    v => string.Join(',', v),
                    v => v.Split(',', StringSplitOptions.RemoveEmptyEntries)
                        .Where(val => AllRoles.Roles.Contains(val))
                        .ToList<string>()
                )
                .Metadata.SetValueComparer(listValueComparer);
        }
    }

   // ASP injection code left out, can be supplied if strictly necessary
    [ApiController]
    public class PrincipalsController
    {
        public PrincipalsController(SignerContext dbContext)
        {
            this._dbContext = dbContext;
        }

        [HttpGet]
        [AllowAnonymous]
        public async IAsyncEnumerable<IdentityPrincipalViewModel> GetPrincipals()
        {
            bool a = await this._dbContext.IdentityPrincipals
                    .Where(p => p.AssignedRoles.Contains(Roles.Administrator))
                    .AnyAsync();
           // a is always false here!
           // rest of unrelated code here...
        }
    }

```

No Exceptions generated.

### Further technical details

EF Core version: 3.1
Database provider:  Microsoft.EntityFrameworkCore.SqlServer;  Server=(localdb)\\mssqllocaldb
Target framework: .NET Core 3.1
Operating system:  Windows 10 1903
IDE: Visual Studio 2019 16.5

**Comment by smitpatel** [comment] 2020-02-19 00:47
Duplicate of #18970

We cannot translate it to server since there is a value converter. Fixed to throw client eval error in 5.0

**Comment by TarquinQ** [comment] 2020-02-19 00:49
Thanks

**Comment by NetTecture** [comment] 2020-02-22 19:14
@TarquinQ Does this work under 2.2? I.e. is this anotehr case of the Ef team lobotomizing the SQL generation and now blaming client evaluation for it? I have examples where in 2.2 it was server evaluated and in 3.1 ist blows with client evaluation, and @smitpatel is blaming client evaluation while in reality it is an absolutely crappy translator that does not handle more than utterly basic SQL cases.

In i.e. in your case, if Roles.Administrator has a ValueConverter to a list of strings this is NOT a case of client evaluation at all. Even when client evaluation was allowed, this should not ahve been client evaluated.  Roles.Administrator is a constant, so it can be evaluated on the cleint (the value) when building the query graph and then this can result in a query being executed on the server.

**Comment by Pilchie** [comment] 2020-02-22 21:36
@NetTecture I've hidden your comment as abusive.

This repository will not accept behavior that is not respectful and inclusive of all members of the community per it's code of conduct.  We'd like you to be a member of the community, but your current comments are offensive and will not be tolerated, regardless of whether they have technical merit.

**Comment by terrajobst** [comment] 2020-02-26 01:29
@NetTecture 

Since this isn't the first time where you posted abusive comments, we have blocked your account for 7 days. If your behavior doesn't change, we'll block your account permanently. Being critical of our products and processes is completely fine and feedback is always welcome. However, your language goes well beyond that and attacks people personally, which we will not tolerate.

**Closed** 2022-10-16 18:11 UTC
Labels: closed-duplicate, customer-reported
