### ISSUE TITLE
Support filtered Include not Global as per #1833

### ISSUE THREAD

**Issue by Allann** [dotnet/efcore#12624] opened 2018-07-11 08:47 UTC
Many have asked but I can't find any Issues other than #1833 but that is for global filters which are great, but not what I (and many others) need. What would be great is to be able to add where clause on an include.

My application has the requirement to be able to return all Modules for an Environment, or vice versa depending on which aggregate root you start on.  The result should also return the Url for the combined module/environment.
I realise this appears like a many-to-many which I know is not supported (yet), but it's not, it's a one to many to one.
I have 7 such instances in this context and finding a good solution to this structure is eluding me with ef7.

### Steps to reproduce
Not a repro but this is what I'd like to do in LINQ:

Table 1: **Environment**
Id
Name
Table 2: **EnvironmentModule**
EnvironmentId
ModuleId
Url
Table 3: **Module**
Id
Name

```
Select e.Name, m.Name, em.Url
From Environment e 
  Inner Join EnvironmentModule em On e.Id = em.EnvironmentId
  Inner Join Module m On m.Id = em.ModuleId
Where em.ModuleId = 3
```

Example Linq:
`_context.Environments.Include(e=>e.EnvironmentModule.First(em=>em.ModuleId==moduleId)).ThenInclude(em=>em.Module);`

or  better still: `_context.Environments.Include(e=>e.EnvironmentModule).ThenInclude(em=>em.Module).Where(e.EnvironmentModule.ModuleId==moduleId);`

If there is something that can achieve this please let me know because I've been working on numerous hacks to make it work including a direct SQL hack via:
`_context.Environments.FromSql("...")`

I realise I could also start with the EnvironmentModule as the root and just include the others but I have kept the description simple to show the issue.  The user can also add filters and the service can add yet others, like Environment.Name == "DEV" or Module.IsActive or Url != "https:". So whichever way you twist the includes or where constructs, the problem exists.

### Further technical details
EF Core version: 2.0.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 64
IDE: Visual Studio 2017 15.8 preview 4

**Comment by divega** [comment] 2018-07-20 22:55
@Allann #1833 is still there to track specifying inline filters in Include. The reason we mention global filters in that issue is that we have found many related customer scenarios what can be addressed with global filters, and we want customers voting for #1833 to first consider if global filters would work for them. 

Based on that, I am going to close your issue as duplicate of #1833, but I also wanted to mention that filtered include will likely be just "syntax sugar" for queries that you can already write without it. For your example, I would try something like this:

``` C#
_context.Environments
    .Where(e => e.Name == "DEV")
    .Select(e = > new 
        {
            Environment = e,
            Modules = e.EnvironmentModules
                .Where(em => em.ModuleId==moduleId && em.Module.IsActive)
                .Select(em => em.Module)
                .ToList(),
            EnvMods = e.EnvironmentModules
                .Where(em => em.ModuleId==moduleId && em.Module.IsActive)
                .ToList(),
        });
```

The obvious goal for whatever syntax we come up with for filtered include is to reduce the amount of redundant code you need to use in the query.

**Closed** 2022-10-16 13:18 UTC
Labels: customer-reported
