### ISSUE TITLE
Xamarin and Entity Framework SLOW start up.

### ISSUE THREAD

**Issue by iXmonvi33** [dotnet/efcore#13791] opened 2018-10-28 06:37 UTC
Hello,

Is there any way to fix start up of application when use entity framework, it extends initialization of app +5 seconds ;/

**Comment by ajcvickers** [comment] 2018-10-29 20:23
@patsadow2 Can you post a runnable project/solution that demonstrates that slow down?

**Comment by ajcvickers** [comment] 2018-11-05 18:50
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:37 UTC
Labels: closed-could-not-reproduce, customer-reported
