### ISSUE TITLE
Linq to sql:The timeout occurred because the timestamp function was used when querying a time field, which caused the timeout

### ISSUE THREAD

**Issue by gzj132** [dotnet/efcore#32671] opened 2023-12-25 10:56 UTC
### Description

In Linq to SQL, the generated SQL query includes window functions in the query conditions, which is causing query timeouts.  How can I resolve this issue?

### Reproduction Steps

My LINQ query looks something like this: `var now = DateTime.Now;
var x = context.Blogs.Where(b => b.DateTime >= now);` When I checked the MySQL console, this LINQ query was translated into SQL as `select * from Blogs where DateTime >= timestamp('2023-12-14 xxxxxxx')`. Due to the use of the timestamp function in this search condition, my index became ineffective. I need to prevent the generated SQL from using the timestamp function and make my index work again.

 I have always been checking the SQL statements generated by LINQ in the command window. The generated statements are parameterized. It wasn't until today when I checked the MySQL console that I discovered the direct use of MySQL window functions in the parameterized query. I really don't understand why it is done this way.

### Expected behavior

select * from Blogs where DateTime >= '2023-12-14 xxxxxxx

### Actual behavior

select * from Blogs where DateTime >=timestamp( '2023-12-14 xxxxxxx)

### Configuration

EF Core version:7.0
Database provider: (Microsoft.EntityFrameworkCore.MySql)
Target framework: (.NET 6.0)
Operating system:linux / windows
IDE: (Visual Studio 2022 17.4)

**Comment by JRahnama** [comment] 2023-12-25 17:34
This is related to MySql and is not SqlClient.

**Comment by Clockwork-Muse** [comment] 2023-12-25 18:15
> the generated SQL query includes window functions in the query conditions

Your example doesn't show an actual "window function", which is one that uses the `OVER` clause.

> My LINQ query looks something like this: `var now = DateTime.Now; var x = context.Blogs.Where(b => b.DateTime >= now);`

This isn't your actual problem, but this code is potentially problematic.  Assuming this `DateTime` column is supposed to represent an absolute timestamp (and not something that should be a local date/time, like a future calendar appointment), you should be using `UtcNow`.

> I checked the MySQL console, this LINQ query was translated into SQL as `select * from Blogs where DateTime >= timestamp('2023-12-14 xxxxxxx')`. Due to the use of the timestamp function in this search condition, my index became ineffective.

Assuming that the `DateTime` column is the `TIMESTAMP` type, you _want_ the function to be called to change the parameter to the proper type.  Calling it on the column would definitely invalidate the index.  Note that MySQL would implicitly call the same function on the constant in such a case anyways.
If the column is a string-based type, you should change the column type to one of the date-time types.

Note that there are various other reasons why indices can be ignored -  most often, if the optimizer believes that the percentage of rows returned will be above a certain amount it will perform a table scan anyways.

**Comment by roji** [comment] 2023-12-25 19:30
@gzj132 this seems like a duplicate of #32667, and still does not contain any of the necessary information, e.g. query plans or benchmark results showing that there's a problem with the generated SQL.

**Comment by gzj132** [comment] 2023-12-26 01:21
> select * from Blogs where DateTime >= timestamp('2023-12-14 xxxxxxx')

@Clockwork-Muse You are absolutely right, I have one question now, why the query statement executed in MySQL has been transformed into 
```select * from Blogs where DateTime >= timestamp('2023-12-14 xxxxxxx')```
 My query field in C# is DateTime, and the corresponding field in MySQL is also datetime, so there should be no need for conversion. Why is the result like this? I need to resolve this issue. Thank you

**Comment by gzj132** [comment] 2023-12-26 01:21
> @gzj132 this seems like a duplicate of #32667, and still does not contain any of the necessary information, e.g. query plans or benchmark results showing that there's a problem with the generated SQL.

@roji Yes, I need to solve the problem of linq to sql generating timestamp, this conversion is not necessary, I have not found any solution until now, unless I use native sql

**Comment by gzj132** [comment] 2023-12-26 01:43
> This is related to MySql and is not SqlClient.

You can give me more direct advice, like which team to go to for help, or help me solve the problem directly instead of deflecting to the topic,,My team is still waiting for me to solve this problem.thanks

**Comment by roji** [comment] 2023-12-26 07:38
@gzj132 you wrote in your original issue above that you're using "Microsoft.EntityFrameworkCore.MySql " this does not exist. There are two MySql providers: [MySql.EntityFrameworkCore](https://www.nuget.org/packages/MySql.EntityFrameworkCore) (maintained by Oracle) and [Pomelo.EntityFrameworkCore.MySql](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql) (a community-maintained project). You can check out our [providers page](https://learn.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli) to see the list of providers and their contacts, which you can use to reach out.

However, they will likely tell you the same thing I tried saying above - all we have at this point is a translation from LINQ to SQL which you claim causes index use problem; this hasn't been substantiated or verified with a query plan or benchmark, and there isn't even an actual repro - just a query and an assertion. When reporting a problem and asking for help, you have to help out and provide at least the minimum so that the maintainers are able to investigate and find a solution.

**Comment by Clockwork-Muse** [comment] 2023-12-26 07:41
> My query field in C# is DateTime, and the corresponding field in MySQL is also datetime, so there should be no need for conversion. 

C# `DateTime` absolutely positively != MySQL `DATETIME`.  At minimum the C# value would have to be converted to the db-side type, but often for certain types things are just sent as strings and then converted once in the database itself.

The [MySQL Documentation states](https://dev.mysql.com/doc/refman/5.7/en/type-conversion.html):
> If one of the arguments is a [TIMESTAMP](https://dev.mysql.com/doc/refman/5.7/en/datetime.html) or [DATETIME](https://dev.mysql.com/doc/refman/5.7/en/datetime.html) column and the other argument is a constant, the constant is converted to a timestamp before the comparison is performed. This is done to be more ODBC-friendly. This is not done for the arguments to [IN()](https://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html#operator_in). To be safe, always use complete datetime, date, or time strings when doing comparisons. For example, to achieve best results when using [BETWEEN](https://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html#operator_between) with date or time values, use [CAST()](https://dev.mysql.com/doc/refman/5.7/en/cast-functions.html#function_cast) to explicitly convert the values to the desired data type.

This is.... odd.

So, the documentation states that constants are always converted with `timestamp()` if it's some constant, even if that's not the actual destination type.  That's a weird choice to make in the first place (why not the actual destination type?), but may also be silently corrupting results depending on connection timezone settings (I'd have to read the documentation more in depth).  Anyways, it means that _for your desired statement_ you should be seeing the exact same behavior.  The implication is that this would also take effect even if the db driver is actually able to supply a parameterized query with the proper type.

... They also seem to be suggesting that using `BETWEEN` is something that should be part of normal practice, but I can guarantee you that [`BETWEEN` is best avoided, or you risk corrupting search results](https://sqlblog.org/2011/10/19/what-do-between-and-the-devil-have-in-common).  This does not endear at minimum the documentation writer to me.

<hr />

The proper place to report errors with the provider, which is likely in charge of this transformation, should be [in this Pomelo repo](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql).  Note, however, that your version of MySQL is _long_ out of support, so they may require you upgrade first.

**Comment by gzj132** [comment] 2023-12-26 08:08
> @gzj132 you wrote in your original issue above that you're using "Microsoft.EntityFrameworkCore.MySql " this does not exist. There are two MySql providers: [MySql.EntityFrameworkCore](https://www.nuget.org/packages/MySql.EntityFrameworkCore) (maintained by Oracle) and [Pomelo.EntityFrameworkCore.MySql](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql) (a community-maintained project). You can check out our [providers page](https://learn.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli) to see the list of providers and their contacts, which you can use to reach out.
> 
> However, they will likely tell you the same thing I tried saying above - all we have at this point is a translation from LINQ to SQL which you claim causes index use problem; this hasn't been substantiated or verified with a query plan or benchmark, and there isn't even an actual repro - just a query and an assertion. When reporting a problem and asking for help, you have to help out and provide at least the minimum so that the maintainers are able to investigate and find a solution.

@roji Sorry, I'm using is indeed a Pomelo. EntityFrameworkCore. MySql this library, but linq to SQL is this library work? But I think this is Linq To Sql is the base class library of.NET, this is the Sql statement that Linq translates to me, in the case of parameterization, if I didn't look at the mysql console, I wouldn't know that I added a function to the query, and as far as I know, No query with a function can trigger the index, I don't know how many more such cases, I am worried about my project, please do I also need to provide a chain of evidence to prove that the converted sql uses the function in the query condition

**Comment by gzj132** [comment] 2023-12-26 08:09
> > My query field in C# is DateTime, and the corresponding field in MySQL is also datetime, so there should be no need for conversion.
> 
> C# `DateTime` absolutely positively != MySQL `DATETIME`. At minimum the C# value would have to be converted to the db-side type, but often for certain types things are just sent as strings and then converted once in the database itself.
> 
> The [MySQL Documentation states](https://dev.mysql.com/doc/refman/5.7/en/type-conversion.html):
> 
> > If one of the arguments is a [TIMESTAMP](https://dev.mysql.com/doc/refman/5.7/en/datetime.html) or [DATETIME](https://dev.mysql.com/doc/refman/5.7/en/datetime.html) column and the other argument is a constant, the constant is converted to a timestamp before the comparison is performed. This is done to be more ODBC-friendly. This is not done for the arguments to [IN()](https://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html#operator_in). To be safe, always use complete datetime, date, or time strings when doing comparisons. For example, to achieve best results when using [BETWEEN](https://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html#operator_between) with date or time values, use [CAST()](https://dev.mysql.com/doc/refman/5.7/en/cast-functions.html#function_cast) to explicitly convert the values to the desired data type.
> 
> This is.... odd.
> 
> So, the documentation states that constants are always converted with `timestamp()` if it's some constant, even if that's not the actual destination type. That's a weird choice to make in the first place (why not the actual destination type?), but may also be silently corrupting results depending on connection timezone settings (I'd have to read the documentation more in depth). Anyways, it means that _for your desired statement_ you should be seeing the exact same behavior. The implication is that this would also take effect even if the db driver is actually able to supply a parameterized query with the proper type.
> 
> ... They also seem to be suggesting that using `BETWEEN` is something that should be part of normal practice, but I can guarantee you that [`BETWEEN` is best avoided, or you risk corrupting search results](https://sqlblog.org/2011/10/19/what-do-between-and-the-devil-have-in-common). This does not endear at minimum the documentation writer to me.
> 
> The proper place to report errors with the provider, which is likely in charge of this transformation, should be [in this Pomelo repo](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql). Note, however, that your version of MySQL is _long_ out of support, so they may require you upgrade first.

@Clockwork-Muse Thanks for your advice, I will use native sql to execute my program, I need to fix the problem first, good luck

**Comment by roji** [comment] 2023-12-26 11:18
> and as far as I know, No query with a function can trigger the index

I know very little, but that statement alone is simply incorrect in the general case. if you write a query that has SQL such as `WHERE column > func()`, then in most cases the database can simply evaluate the function call, and then using any index defined on `column`.

@gzj132 I think there may be some confusion on your side on how SQL gets evaluated by the database, and what causes actual performance issues. I recommend stepping back and examining exactly why you think the SQL is problematic, and why you think you have performance issues. As of now there's nothing here that either we or the Pomelo provider maintainers can actually work with.

**Comment by Clockwork-Muse** [comment] 2023-12-26 18:36
> I know very little about MySQL, but that statement alone is simply incorrect in the general case. if you write a query that has SQL such as `WHERE column > func()`, then in most cases the database can simply evaluate the function call, and then using any index defined on `column`.

The MySQL engine/optimizer are.... not the best.  Historically it didn't even use more than one index per statement.  I personally wouldn't touch it with a ten-foot pole (in preference for PostgreSQL).

>  I still think linq to sql belongs.

@gzj132 - The actual insertion of the `timestamp()` function is being done by the provider.  EFCore has no idea that function even exists, or what it does (date/time types in databases are poorly or not entirely standardized).

**Comment by roji** [comment] 2023-12-26 19:43
> I still think linq to sql belongs. NET base class library generation, hope. NET team can take note of this problem

As I wrote several times above, which **exact** SQL gets generated for which LINQ query is ultimately a question for each specific database provider. Comparing to a function - as in this case - certainly does not cause a problem with other databases (and I'm very surprised it does with MySQL), so there's nothing really to be done in EF itself.

In any case, the point you're missing is that you're the one expressing that particular SQL - with the function call - by including it inside your LINQ query; the way you write your LINQ query determines what SQL comes out, and that SQL is perfectly valid. As discussed above, you have the option of extracting the function call outside, in which case the value gets parameterized and no function gets generated in the SQL. That's up to you.

I'm going to go ahead and close this as I don't see an EF-side issue - I suggest you continue this conversation on the Pomelo repo, though again I don't know what they could do here.

**Comment by roji** [comment] 2023-12-26 19:43
Duplicate of #32667

**Closed by roji** 2023-12-26 19:43 UTC
