### ISSUE TITLE
EFcore throws timeout exception on calling sp which takes more than 2 minutes

### ISSUE THREAD

**Issue by kishoretvk** [dotnet/efcore#9596] opened 2017-08-27 06:20 UTC
Describe what is not working as expected.
EFCoe async call  to stored procedure with sql server db, if it takes more than 2 minutes of 
execution time , efcore throws exception! 
If you are seeing an exception, include the full exceptions details (message and stack trace).
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__26.MoveNext()
```
Exception message:
Stack trace:
```
 An unhandled exception was thrown by the application.
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out

please tr y to do the same form your side it comes

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.
any basic program with stored proc from sql server and a async api
keep delay of 2 minutes in sp! u will reproduce the issue. 
trying setting connectiontimeout from connection string, 
tried to set dbcontext.settimeout(9000)
triend to add _context.database.setcommandtimeout(900)

all these will not change commandtimeout from default 30 value,  this has devastating effects on performance. 
im not using sql queires, im running sp. so no probblem with indexers of query tunning. please adddress as its related to efcore ! 
Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2015)

**Comment by ErikEJ** [comment] 2017-08-27 06:45
As stored procedure is also a SQL query! This looks like a duplicate of your previous posts - if you do not increase the CommandTimeout on long running stored procedures/sql statements, you will always get timeout execptions. So you have 2 options:
1: Increase the CommandTimeout
2: Improve the execution time of your stored procedure by adding indexes and/or refactoring your stored procedure

**Comment by kishoretvk** [comment] 2017-08-27 14:07
yes, i did increase cocmmand timeout but in logs it shows 30,  even thought in ncreased to 9000
, 
im wokring on huge data which does take more than 2 minutes to load. 
workong data with more than 60 to 100 million records. 
ii've to join that with 5 other tables having 500k recoreds . its not issue with sql server. 

public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
{
      Database.SetCommandTimeout(9000);
}


i tried to do so but when i turned on logs, 

i i see this

Executed DbCommand (1ms) [Parameters=[@__subject_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30'] 

i've set conect timeout = 3000 in connection string. 

i also tried to do 

 _context.Database.SetCommandTimeout(3000);


even then commandtimeout doesnot change. further information. doing all this 
EFcore would call sp multiple times from sql side. and eventually give timeout eror. 



which eventually came up as below 


Exception message: 
   An unhandled exception was thrown by the application.
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out

Stack trace:
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at david.web.Controllers.ReportsController.<>c__DisplayClass3_4.<GetUsage>b__3(<>f__AnonymousType3`2 dataFactory)
   at AutoMapper.Internal.EnumerableExtensions.Each[T](IEnumerable`1 items, Action`1 action)
   at david.web.Controllers.ReportsController.<>c__DisplayClass3_3.<GetUsage>b__2(DataType dataType)
   at AutoMapper.Internal.EnumerableExtensions.Each[T](IEnumerable`1 items, Action`1 action)
   at david.web.Controllers.ReportsController.<GetUsage>d__3.MoveNext()
Further technical details

EF Core versi

as  menioned in previous post. u can see the method giving error. 

my sql server version is 2012. 

using visual studio 2015

**Comment by kishoretvk** [comment] 2017-08-27 14:08
more information a tip of this issue was sown here 

https://github.com/aspnet/EntityFrameworkCore/issues/6246

**Comment by smitpatel** [comment] 2017-08-28 01:18
Duplicate of #9513

**Closed** 2022-10-16 11:18 UTC
Labels: closed-duplicate
