### ISSUE TITLE
EF Core 5.0 : Add or remove ValueGeneratedNever in IEntityTypeConfiguration does not change anything when update existing sql server database

### ISSUE THREAD

**Issue by arfanmauko** [dotnet/efcore#28075] opened 2022-05-22 10:49 UTC
I'm build a simple Table using EFCore version 5.0.17 using code first and Fluent Api with Id column as Key  with int data type. It is successfull when I create initial migration. But when I add or remove ValueGeneratedNever option for enable or disable AutoGenerate value in database it seems not working.

### Include your code

```
class MyTableConfiguration : IEntityTypeConfiguration<MyTable>
    {
        public void Configure(EntityTypeBuilder<MyTable> builder)
        {
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id)
             .ValueGeneratedNever();
        }
    }
```

### Include provider and version information

EF Core version: 5.0.17
Database provider: =Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system:
Visual Studio 2019 16.11.15

**Comment by SimonCropp** [comment] 2022-05-22 21:47
does it work in v6?

**Comment by roji** [comment] 2022-05-23 11:53
This issue is lacking lots of information - what does "not working" mean, are you getting an exception?

Please post a runnable, self-contained code sample which shows what you're trying to do and reproduces the exception.

**Comment by AndriySvyryd** [comment] 2022-05-24 17:31
Probably a duplicate of https://github.com/dotnet/efcore/issues/2100

**Closed** 2022-10-16 20:34 UTC
Labels: closed-duplicate, customer-reported
