### ISSUE TITLE
Modify entity without querying it before

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/efcore#23012] opened 2020-10-16 07:53 UTC
Ih vae this query:

```csharp
string sqlCommand =
                @"SET NOCOUNT ON;
                    UPDATE [AspnetUsers] 
                    SET LastName = @p0,
                    FirstName = @p1,
                    PhoneNumber = @p2, 
                    PostalCode = @p3, 
                    UpdateDate = @p4
                    WHERE email = @p5";
            try
            {
                int count = await _ctx.Database.ExecuteSqlRawAsync(sqlCommand, model.LastName, model.FirstName, model.Phone, model.ZipCode, model.ZipCode, email);
                if (count != 1)
                    return false;

                return true;
            }
            catch (DbUpdateException ex)
            {
                //TODO: Logs
                return false;
            }```

Simple and efficient

If I would do the same with the classic way I would do:
```csharp
 ApplicationUser user = await _ctx.Users.FirstOrDefaultAsync(u => u.Email == "someone@somewhere.com");
            user.LastName = model.LastName;
            user.FirstName = model.FirstName;
            user.PhoneNumber = model.Phone;
            user.PostalCode = model.ZipCode;
            user.UpdateDate = DateTime.UtcNow;

            // Cause I don"='t use tracking
            _ctx.Entry(user).Property(p => p.LastName).IsModified = true;
            _ctx.Entry(user).Property(p => p.FirstName).IsModified = true;
            _ctx.Entry(user).Property(p => p.PhoneNumber).IsModified = true;
            _ctx.Entry(user).Property(p => p.PostalCode).IsModified = true;
            _ctx.Entry(user).Property(p => p.UpdateDate).IsModified = true;

            _ctx.SaveChanges();
```

But it takes two database call which is inefficient.

Is it possible to add an update method whicj can use a where  clause ?

Something like:
```csharp
 ApplicationUser user = new ApplicationUser(); 
            user.LastName = model.LastName;
            user.FirstName = model.FirstName;
            user.PhoneNumber = model.Phone;
            user.PostalCode = model.ZipCode;
            user.UpdateDate = DateTime.UtcNow;

            // Cause I don"='t use tracking
            _ctx.Entry(user).Property(p => p.LastName).IsModified = true;
            _ctx.Entry(user).Property(p => p.FirstName).IsModified = true;
            _ctx.Entry(user).Property(p => p.PhoneNumber).IsModified = true;
            _ctx.Entry(user).Property(p => p.PostalCode).IsModified = true;
            _ctx.Entry(user).Property(p => p.UpdateDate).IsModified = true;

            _ctx.SaveChanges().Where(u => u.Email == "someone@somewhere.com");
```

**Comment by roji** [comment] 2020-10-16 08:22
Duplicate of #795

**Closed** 2022-10-16 19:04 UTC
Labels: closed-duplicate, customer-reported
