### ISSUE TITLE
EF Core Migrations broke EF 6 Migrations

### ISSUE THREAD

**Issue by keerthimaryala18** [dotnet/efcore#25425] opened 2021-08-04 15:43 UTC
We have two services using different db contexts pointing to the same MySQL DB. One service uses EF6 and the other uses EF Core. Up Until now, we ran migrations only from the EF6 service and the history was maintained in _MigrationHistory. After running migrations in the EF Core service, I tried to run Migrations in the EF6 service and it seems to have lost context of the _MigrationHistory table and point to the _EFMigrationHistory table.

The _MigrationHistory table has a lot of history and I don't want to reset the migrations in that service. Is there a way to point the EF6 service back to _MigrationHistory table?

**Comment by ajcvickers** [comment] 2021-08-10 18:47
@keerthimaryala18 EF6 migrations should not be impacted by EF Core migrations. Can you post the commands and their output, using the --verbose option?

**Comment by ajcvickers** [comment] 2021-08-20 10:55
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:41 UTC
Labels: closed-could-not-reproduce, customer-reported
