### ISSUE TITLE
.UseIdentityColumn<T>(int seed , ....

### ISSUE THREAD

**Issue by reginald81** [dotnet/efcore#24222] opened 2021-02-22 15:25 UTC
SQL Server admits Int64 (BIGINT)  as maximum integer numeric value for identity COLUMNS.

To use Int64 and get the maximum number of values I have to set Int64,MinValue in  seed param.

UseIdentityColumn([NotNullAttribute] this PropertyBuilder propertyBuilder, int seed = 1, int increment = 1);
The value type for the seed parameter should be set to Int64  ?!?!?!?

**Comment by ajcvickers** [comment] 2021-09-28 11:28
Duplicate of #24840

**Closed** 2022-10-16 19:24 UTC
Labels: customer-reported
