### ISSUE TITLE
Object ID key value as autoincrement int 

### ISSUE THREAD

**Issue by OpsOwns** [dotnet/efcore#20125] opened 2020-03-02 18:25 UTC
I would like to make somthing like this

  ```csharp
  public class User
    {
        public UserId Id { get; set; }
        public string Name { get; set; }
    }
 public class UserId
    {
        public int Id { get;; }
        private UserId()
        {
        }
        public UserId(int id)
        {
            Id = id;
        }
        public static implicit operator int(UserId userId)
        {
            return userId.Id;
       }
        public static implicit operator UserId(int id)
        {
            return new UserId(id);
        }
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }

            var userId = (UserId)obj;
            return this.Id == userId.Id;
        }

        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
```

I do some research and i found something like this

```csharp
            var converter = new ValueConverter<UserId, int>(
                v => (int)v,
                v => (UserId)v,
                new ConverterMappingHints(valueGeneratorFactory: (p, t) => new TemporaryIntValueGenerator()));
            modelBuilder.Entity<User>().ToTable("UserOps");
            modelBuilder.Entity<User>().Property(x => x.Name);

            modelBuilder.Entity<User>().Property("Id")
            .ValueGeneratedOnAdd().HasConversion(converter);
            base.OnModelCreating(modelBuilder);
```

But it didn't work for me as i expected. I would like to get auto increment int on this object when i insert new item to Database.

Error:
SqlException: Cannot insert explicit value for identity column in table 'UserOps' when IDENTITY_INSERT is set to OFF

**Comment by ajcvickers** [comment] 2020-03-02 22:15
Duplicate of #11597

**Closed** 2022-10-16 18:14 UTC
Labels: customer-reported
