### ISSUE TITLE
`HasColumnType` should not be available after `HasMaxLength`

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/efcore#21855] opened 2020-07-30 10:34 UTC
Consider following code:
```cs
builder
    .Property(c => c.Name)
    .HasMaxLength(256)
    .HasColumnType("CHAR");
```
In SQL, result will be `Name (char(1), null)`, but it should be `Name (char(256), null)`, because I specify the column length using `HasMaxLength`.

I think you should change the API and don't allow user to call `HasColumnType`  after `HasMaxLength`, Or respect to the value specified by `HasMaxLength`.

### Further technical details

EF Core version: 3.1.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows
IDE: Visual Studio 2019 16.3

**Comment by ajcvickers** [comment] 2020-07-31 16:51
Duplicate of #15159

**Closed** 2022-10-16 18:35 UTC
Labels: customer-reported
