### ISSUE TITLE
EF Core 3.1 ToQuery Project DBSet to POCO

### ISSUE THREAD

**Issue by aherrick** [dotnet/efcore#18865] opened 2019-11-12 15:05 UTC
In EF Core 2.2 I was able to project a DB Set to a Query to test a SQL View in memory.

Something like this:

```C#
public IQueryable<ShipmentListView> ShipmentListView => Set<ShipmentListView>();
````

```C#
if (Database.IsInMemory())
{
    modelBuilder.Entity<ShipmentListView>().HasNoKey().ToQuery(() =>
        Shipment.AsQueryable().Select(shipment => new ShipmentListView()
        {
            ShipmentId = shipment.Id,
            EntityName = shipment.Entity == null ? "" : shipment.Entity.Name,
            CustomerId = shipment.CustomerId,
            CustomerName = shipment.CustomerName,
        }));
}
```

However in 3.1 I'm receiving errors such as:

`could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync()`

The problem seems to be with this line:
```C#
EntityName = shipment.Entity == null ? "" : shipment.Entity.Name,
```

When I try to update to use AsEnumerable:

```C#
if (Database.IsInMemory())
{
    modelBuilder.Entity<ShipmentListView>().HasNoKey().ToQuery(() =>
        Shipment.AsEnumerable().Select(shipment => new ShipmentListView()
        {
            ShipmentId = shipment.Id,
            EntityName = shipment.Entity == null ? "" : shipment.Entity.Name,
            CustomerId = shipment.CustomerId,
            CustomerName = shipment.CustomerName,
        }).AsQueryable());
}
```
I receive the following:

`{"Processing of the LINQ expression 'DbSet<Shipment>\r\n    .AsEnumerable()\r\n    .AsQueryable()' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information."}`

Is there a different way I need to project to my `ShipmentListView `so that I can handle navigation properties?

**Comment by ajcvickers** [comment] 2019-11-13 16:42
@aherrick Thanks for filing this issue. We will discuss in our next triage meeting.

**Comment by aherrick** [comment] 2019-11-15 01:27
@ajcvickers cool. Is there any recommend work around for this pretty standard scenario?

**Comment by ajcvickers** [comment] 2019-11-15 21:02
@aherrick It's not clear what is going on here. Please post a small, runnable project/solution or complete code listing so that we can investigate fully.

**Comment by ajcvickers** [comment] 2019-11-22 22:45
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ahmedtolba1984** [comment] 2020-01-24 00:18
@aherrick Did you solved it?
I am facing the same issue

**Closed** 2022-10-16 14:55 UTC
Labels: closed-could-not-reproduce, customer-reported
