### ISSUE TITLE
EF core ValueObject You don't have the data to get.

### ISSUE THREAD

**Issue by Gakki123** [dotnet/efcore#21671] opened 2020-07-17 17:31 UTC
### Steps to reproduce
ValueObject
![image](https://user-images.githubusercontent.com/33748042/87813202-12a05a80-c827-11ea-90c2-22df9ae0355d.png)

Configuration
![image](https://user-images.githubusercontent.com/33748042/87813244-26e45780-c827-11ea-8196-bdec676206b5.png)

Migrations IsRequired did not take effect.
![image](https://user-images.githubusercontent.com/33748042/87813275-319eec80-c827-11ea-90f2-6d69685c0e3a.png)

Get Property  Create &&Modify == null
![image](https://user-images.githubusercontent.com/33748042/87813587-cc97c680-c827-11ea-9bfc-b0ab78eb6a1b.png)

This is the data in the database. You can see that CreateTime has data.
![image](https://user-images.githubusercontent.com/33748042/87813677-ff41bf00-c827-11ea-8f9e-7e434c277558.png)

### Further technical details

EF Core version: 3.1.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer 3.1.6
Target framework:.NET Core 3.1
Operating system: win 10
IDE: Visual Studio 2019 16.3

**Comment by ajcvickers** [comment] 2020-07-20 16:31
@Gakki123 Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-07-31 15:39
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:34 UTC
Labels: closed-could-not-reproduce, customer-reported
