### ISSUE TITLE
Entity Framework Core attempts to use wrong options when two contexts are registered by AddDbContextPool

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#9763] opened 2017-09-11 19:11 UTC
Message: System.ArgumentException : Expression of type 'Microsoft.EntityFrameworkCore.DbContextOptions\`1[DIAddDbcontextPoolTests.DbContext2]' cannot be used for constructor parameter of type 'Microsoft.EntityFrameworkCore.DbContextOptions\`1[DIAddDbcontextPoolTests.DbContext1]'
Parameter name: arguments[0]

Unit test:
[DIAddDbcontextPoolTests.zip](https://github.com/aspnet/EntityFrameworkCore/files/1293721/DIAddDbcontextPoolTests.zip)

**Comment by smitpatel** [comment] 2017-09-11 19:25
Duplicate of #9433

**Closed** 2022-10-16 11:48 UTC
