### ISSUE TITLE
Error when creating a new migration "An item with the same key has already been added. Key: EntityId"

### ISSUE THREAD

**Issue by julienFlexsoft** [dotnet/efcore#30349] opened 2023-02-27 10:30 UTC
## File a bug

I recently upgraded my .NET project to .NET 7 and EF Core 7.0.3. Everything works fine, but I now get an error if I create a new migration. There are no changes in the DbContext, so the migration should be empty. It perfectly works in another branch that's still on .NET 6 with EF Core 6.0.14.

```
An item with the same key has already been added. Key: EntityId
```

I also tried it with version 7.0.0, 7.0.1, 7.0.2 and prerelease 8.0.0-preview.1.23111.4 and I still get the same error. And when I update all the EF Core packages to 6.0.14 everything works again.
I've seen similar bug reports here with a similar message (ex. #27504 ), but those were resolved in version 7.0.3, I assume that my issue is different.

I use the term "EntityId" in a generic class that I use for translations.
Ex.:

**BaseTranslationEntity.cs**
``` c#
    public class BaseTranslationEntity : BaseEntity, ITranslationEntity
    {
        public int EntityId { get; set; }
        public int TargetCultureId { get; set; }
        public string Value { get; set; }

        public CultureEntity TargetCulture { get; set; }
    }
```

**CountryTranslationEntity .cs**
``` c#
    public class CountryTranslationEntity : BaseTranslationEntity
    {
        public CountryEntity Country { get; set; }
    }
```

**CurrencyTranslationEntity .cs**
``` c#
    public class CurrencyTranslationEntity : BaseTranslationEntity
    {
        public CurrencyEntity Currency { get; set; }
    }
```

**CustomDbContext.cs**
```c#
        public DbSet<CountryTranslationEntity> CountryTranslationEntities { get; set; }
        public DbSet<CurrencyTranslationEntity> CurrencyTranslationEntities { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CountryEntity>()
                .HasMany(a => a.Translations)
                .WithOne(b => b.Country)
                .HasForeignKey(a => a.EntityId)
                .HasPrincipalKey(b => b.Id)
                .IsRequired().OnDelete(DeleteBehavior.Restrict);

            modelBuilder.Entity<CurrencyEntity>()
                .HasMany(a => a.Translations)
                .WithOne(b => b.Currency)
                .HasForeignKey(a => a.EntityId)
                .HasPrincipalKey(b => b.Id)
                .IsRequired().OnDelete(DeleteBehavior.Restrict);
         }
```

I use this generic class in a lot more translations, is there something here that is no longer supported by EF Core?
I read about inheritance in EF Core, but here the entity `BaseTranslationEntity` itself is not mapped to a table. It is only used inside other entities.

### Include stack traces

```
System.ArgumentException: An item with the same key has already been added. Key: EntityId
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.AddSeedData(IEntityType entityType, Dictionary`2 identityMaps, EntityState initialState)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.TrackData(IRelationalModel source, IRelationalModel target, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDataOperations(IRelationalModel source, IRelationalModel target, DiffContext diffContext)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
An item with the same key has already been added. Key: EntityId
```

### Include provider and version information

EF Core version: 7.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows 11 Pro (22H2)
IDE: Visual Studio 2022 (64bit) 17.5.0

**Comment by ajcvickers** [comment] 2023-02-28 18:24
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-03-13 12:31
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-03-13 12:31 UTC
Labels: customer-reported

**Comment by kemmis** [comment] 2023-10-09 15:32
I have this exact same issue. I upgraded from ef core 6 -> 7.0.10. Everything works except when I go to create a new migration. Did anyone figure out how to fix this issue?

**Comment by kemmis** [comment] 2023-10-09 18:03
I found my problem. In my case we were calling .HasData(a1,a2) where a1 and a2 were two different types, but with shared property names.

**Comment by ValdirLeanderson** [comment] 2024-12-06 00:34
I upgraded a project ef core from 3.1 to 8.0. I found the same problem 'System.ArgumentException: An item with the same key has already been added. Key: Id'. This problem happens because i think that dotnet 8 does not understand when a seed data already sent to database. To fix this problem you need to comment or erase all 'hasData' command into your code.  It was enough to me. I hope help you.

**Comment by roji** [comment] 2024-12-06 15:40
Everyone, this looks like an EF bug that we'd like to fix - but we need someone to put together a minimal, runnable repro (e.g. console program) that shows it happening.

**Comment by guisantos** [comment] 2024-12-16 15:24
It's happening the same with me.
EF Core version 8.0.11

`System.ArgumentException: An item with the same key has already been added. Key: GUID
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.AddSeedData(IEntityType entityType, Dictionary`2 identityMaps, EntityState initialState)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.TrackData(IRelationalModel source, IRelationalModel target, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDataOperations(IRelationalModel source, IRelationalModel target, DiffContext diffContext)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
An item with the same key has already been added. Key: GUID
`

**Comment by roji** [comment] 2024-12-16 15:28
@guisantos see my comment just above about the need for a repro. A stack trace isn't enough.

**Comment by guisantos** [comment] 2024-12-16 15:38
@roji I know, I'm trying to make one as we speak, my hypothesis is about using a generic class, I have the same scenario as the user.
I have a BaseEntity with GUID and all my classes inherit from it, only difference is that I don't have ForeignKeys to this property only a Unique constraint

**Comment by roji** [comment] 2024-12-16 15:39
@guisantos thanks for working on this - I hope you can put a repro together, we'll open and investigate when you do.

**Comment by ValdirLeanderson** [comment] 2024-12-17 03:04
@guisantos in my case I Noted if all the seeds that exist are configured for the correct class, I found one like this example.
modelBuilder.Entity<Country>(b =>
{
    …
    b.HasData(
        new City {Id u= 1, Name = "USA" },
        new City {Id = 2, Name = "Canada" },
        new City {Id = 3, Name = "Mexico" });
});
It should be a sintaxe error because City is a different entity of Country, but dotnet ef ignores it.

**Comment by guisantos** [comment] 2024-12-17 08:34
I found the issue on my project, the error is a bit misleading and was happening the same scenario as @ValdirLeanderson mention.

I instantiate the EntityTypeBuilder for class Foo and on the HasData I was checking/creating for a different class Bar.

```
public class FooConfiguration : EntityConfiguration<Foo>
{
    public override void Configure(EntityTypeBuilder<Foo> builder)
    {
        builder.HasData(new Bar
        {
            GUID = Guid.Parse("someguid),
            Id = 1,
            Title = "Test"
        });
    }
}
``` 

For some reason this was working fine with the previous version.
