### ISSUE TITLE
Discriminator with default name but different type not generated correctly in migration snapshots

### ISSUE THREAD

**Issue by Xriuk** [dotnet/efcore#35075] opened 2024-11-11 15:42 UTC
### Include your code

Having any TPH entity, and configuring the discriminator by using the default name "Discriminator":
```C#
...

modelBuilder.Entity<MyEntity>()
    .ToTable("MyTable")
    .HasDiscriminator<int>("Discriminator");

...
```

Creates a snapshot/designer file like:
```C#
...

modelBuilder.Entity("Namespace.MyEntity", b =>
    {
        ...

        b.HasDiscriminator();

        ...
    }

...
```

While it should have been:
```C#
...

modelBuilder.Entity("Namespace.MyEntity", b =>
    {
        ...

        b.HasDiscriminator<int>("Discriminator");

        ...
    }

...
```

### Reference
It appears that the culprit is here, it the discriminator has the default name, the type is ignored as well.
https://github.com/dotnet/efcore/blob/03b44a2e8d41807ca431ea776fae19827a35b2c6/src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs#L902-L919

### Include provider and version information

EF Core version: 8.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0

**Comment by roji** [comment] 2024-11-12 18:27
I'm unable to reproduce the error - this is why it's always important to submit a minimal, runnable code sample rather than partial snippets, as above.

Please take a look at the attempted repro below; this generates the following discriminator configuration in the snapshot:

```c#
b.Property<int>("Discriminator")
    .HasColumnType("int");
```

Can you please tweak this code sample to show it generating the incorrect snapshot? 

```c#
await using var context = new BlogContext();
await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

public class BlogContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(
            "Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Parent>()
            .HasDiscriminator<int>("Discriminator")
            .HasValue<Parent>(8)
            .HasValue<Child>(9);

        modelBuilder.Entity<Child>();
    }
}

public class Parent
{
    public int Id { get; set; }
}

public class Child : Parent
{
    public string ChildProperty { get; set; }
}
```

**Comment by Xriuk** [comment] 2024-11-13 12:00
That is weird, I'm not able to reproduce my error with the sample.
In my project I have a TPH with some abstract and concrete classes and a shadow discriminator of an enum type with a value converter.
<details>
<summary>DbContext</summary>

```csharp
public class BlogContext : DbContext {
	// In my project the converter just hashes the enum name to an int
	protected class Converter : ValueConverter<Type, int> {
		public Converter() :
				base(v => ((int)v) * 2, v => (Type)(v / 2)) {
		}
	}

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		=> optionsBuilder.UseSqlServer(
			"Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=<db>;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;");

	protected override void OnModelCreating(ModelBuilder modelBuilder) {
		modelBuilder.Entity<Parent>()
			.Property<Type>("Discriminator")
			.HasConversion<Converter>();

		modelBuilder.Entity<Parent>()
			.ToTable("Parent")
			.HasDiscriminator<Type>("Discriminator")
			.HasValue<Child>(Type.Child);

		modelBuilder.Entity<Child>();
	}
}

public enum Type {
	Child
}

public abstract class Parent {
	public int Id { get; set; }
}

public class Child : Parent {
	public string ChildProperty { get; set; } = null!;
}
```

</details>

Both in the sample and my main project (which is more complex) the generated snapshot is similar for the hierarchy:
<details>
<summary>Migration snapshot</summary>

```csharp
// <auto-generated />
using EFCoreTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreTest.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20241113111808_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreTest.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Discriminator")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Parent", (string)null);

                    b.HasDiscriminator();

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EFCoreTest.Child", b =>
                {
                    b.HasBaseType("EFCoreTest.Parent");

                    b.Property<string>("ChildProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue(0);
                });
#pragma warning restore 612, 618
        }
    }
}
```

</details>

But in my main project when applying the migration (even an empty one) I get the following exception:
```
Build started...
Build succeeded.
Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (72ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (73ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (54ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (53ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (57ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '20241113113456_test'.
Applying migration '20241113113456_test'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Namespace.Migrations.test.<>c.<BuildTargetModel>b__2_93(EntityTypeBuilder b) in C:\...\Migrations\20241113113456_test.Designer.cs:line 2665
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(String name, Action`1 buildAction)
   at Namespace.Migrations.test.BuildTargetModel(ModelBuilder modelBuilder) in C:\...\Migrations\20241113113456_test.Designer.cs:line 2651
   at Microsoft.EntityFrameworkCore.Migrations.Migration.<get_TargetModel>g__Create|5_0()
   at Microsoft.EntityFrameworkCore.Migrations.Migration.get_TargetModel()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass16_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```
Which in the sample corresponds to the discriminator value for the child:
```csharp
modelBuilder.Entity("EFCoreTest.Child", b =>
  {
      b.HasBaseType("EFCoreTest.Parent");

      b.Property<string>("ChildProperty")
          .IsRequired()
          .HasColumnType("nvarchar(max)");

      b.HasDiscriminator().HasValue(0); // <--- Exception points here
  });
```

And for some reason this only happens for TPH where my discriminator has the default name "Discriminator", because it generates this snapshot for the parent:
```csharp
b.HasDiscriminator();
```
while if I change it manually to:
```csharp
b.HasDiscriminator<int>("Discriminator");
```
I get no exceptions.

Similarly other TPH which do not have "Discriminator" as the discriminator name generate this snapshot for the parent automatically:
```csharp
b.HasDiscriminator<int>("Type");
```
Which causes no exceptions for me.

**Comment by roji** [comment] 2024-11-13 13:26
@Xriuk I really need a fully runnable, minimal repro, similar to what I posted... All the snippets and explanations are helpful as much as a simple, concise code sample that shows the problem.

**Comment by ajcvickers** [comment] 2024-11-29 17:40
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-11-29 17:40 UTC
Labels: customer-reported, area-migrations
