### ISSUE TITLE
EF Core 5: Cannot Save Batch Inserts

### ISSUE THREAD

**Issue by a11smiles** [dotnet/efcore#22879] opened 2020-10-04 10:12 UTC
In EF Core 3.1 (and older) along with EF Framework, I could do the following:

```csharp
var classroom = new Classroom () { Number = "MATH100", Name = "Introduction to Algebra" };
context.Classrooms.Add(classroom);
context.SaveChanges();

classroom.Students.Add(new Student() { FirstName = "John", LastName = "Doe" };
classroom.Students.Add(new Student() { FirstName = "Jane", LastName = "Dee" };
classroom.Students.Add(new Student() { FirstName = "Jack", LastName = "Daniels" };
context.SaveChanges();
```
**However, in EF Core 5.0 RC1, when I attempt to do so, I get the following error:**
```
System.InvalidOperationException : The instance of entity type 'Students' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
```
So, instead, I'm required to save after _every_ new student (which is less than ideal as it creates code bloat):
```csharp
var classroom = new Classroom () { Number = "MATH100", Name = "Introduction to Algebra" };
context.Classrooms.Add(classroom);
context.SaveChanges();

classroom.Students.Add(new Student() { FirstName = "John", LastName = "Doe" };
context.SaveChanges();
classroom.Students.Add(new Student() { FirstName = "Jane", LastName = "Dee" };
context.SaveChanges();
classroom.Students.Add(new Student() { FirstName = "Jack", LastName = "Daniels" };
context.SaveChanges();
```

### NOTE:
Please note that `Student` is an inherited type of `Person` (`Person` has another type of `Instructor`) and that I'm using TPT.

Thanks!

**Comment by ajcvickers** [comment] 2020-10-04 17:23
Duplicate of #22573.

@a11smiles This is fixed in the GA [daily builds](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md). Can you try with the daily build and report back if you're still seeing issues.

Full repro:

```C#
public class SomeDbContext : DbContext
{
    private static readonly ILoggerFactory
        Logger = LoggerFactory.Create(x => x.AddConsole());//.SetMinimumLevel(LogLevel.Debug));

    public DbSet<Classroom> Classrooms { get; set; }
    public DbSet<Person> People { get; set; }
    public DbSet<Student> Students { get; set; }
    public DbSet<Instructor> Instructors { get; set; }
    
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .EnableSensitiveDataLogging()
            .UseSqlServer(Your.ConnectionString);
}

public class Classroom
{
    public int Id { get; set; }
    public string Number { get; set; }
    public string Name { get; set; }
    
    public ICollection<Student> Students { get; } = new List<Student>();
}

[Table("People")]
public class Person
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

[Table("Students")]
public class Student : Person
{
}

[Table("Instructors")]
public class Instructor : Person
{
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }

        using(var context = new SomeDbContext())
        {
            var classroom = new Classroom () { Number = "MATH100", Name = "Introduction to Algebra" };
            context.Classrooms.Add(classroom);
            context.SaveChanges();

            classroom.Students.Add(new Student() { FirstName = "John", LastName = "Doe" });
            classroom.Students.Add(new Student() { FirstName = "Jane", LastName = "Dee" });
            classroom.Students.Add(new Student() { FirstName = "Jack", LastName = "Daniels" });
            context.SaveChanges();
        }
    }
}
```

**Comment by alecsg77** [comment] 2020-10-10 21:51
I ran in the same issue, porting the Contoso University model from EFCore 3.0 to 5.0.
I tried both the workaround saving every single insert, and using the 5.0.0-rtm.20509.3 with the batch inserts.
Both solutions worked for me.

**Closed** 2022-10-16 19:03 UTC
Labels: closed-duplicate, customer-reported
