### ISSUE TITLE
EFCore 8.0.7 Breaks Discriminator Generated Code

### ISSUE THREAD

**Issue by WynieCronje** [dotnet/efcore#34563] opened 2024-08-29 08:19 UTC
### More Info:
I have tested this by downgrading each version. The expected behavior worked in `8.0.6` and started breaking in `8.0.7`. I have a suspicion that it is related to the PR #33622 that fixed the isssue #33605 in commit: https://github.com/dotnet/efcore/pull/33622/commits/f08ecf3474b65129e4bbd24e7cd03858cc1b3dc8

### Include your code

`PatientLocator.cs`
```C#
public abstract class PatientLocator : DomainEntity
{
   public int Discriminator { get; private set; }
   ....
}
```
`EntityTypeConfiguration.cs`
```C#
b.HasDiscriminator(p => p.Discriminator)
   .HasValue<PatientAddress>(0)
   .HasValue<PatientPhone>(1)
    .HasValue<PatientEmail>(2);

b.HasOne(p => p.Patient)
   .WithMany(p => p.Locators)
    .IsRequired()
    .OnDelete(DeleteBehavior.Cascade);
```

`Snapshot on 8.0.6`
```C#
 modelBuilder.Entity("DOH.CARS.Domain.PatientDirectory.PatientLocator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PatientLocatorId");

                    b.Property<int>("Discriminator")
                        .HasColumnType("int");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientLocator");

                    b.HasDiscriminator<int>("Discriminator");

                    b.UseTphMappingStrategy();
                });
```
`Snapshot on 8.0.7`
```C#
            modelBuilder.Entity("DOH.CARS.Domain.PatientDirectory.PatientLocator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PatientLocatorId");

                    b.Property<int>("Discriminator")
                        .HasColumnType("int");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientLocator");

                    b.HasDiscriminator();

                    b.UseTphMappingStrategy();
                });
```
The Diff:
![image](https://github.com/user-attachments/assets/fe1bc60a-01a1-44c7-b2bf-20397138e818)

### Include stack traces

When running the add-migration. It fails to compile the snapshot with below error:
_Ignore the line numbers, they seem incorrect. I know the above mentioned changes causes the issue. If I manually change to old value, it all works again_

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DOH.CARS.Persistence.Migrations.AppDbContextModelSnapshot.<>c.<BuildModel>b__0_77(EntityTypeBuilder b) in /work/CARS - Clinical Appointment and Referral System/DOH.CARS.Persistance/Migrations/AppDbContextModelSnapshot.cs:line 4374
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(String name, Action`1 buildAction)
   at DOH.CARS.Persistence.Migrations.AppDbContextModelSnapshot.BuildModel(ModelBuilder modelBuilder) in /work/CARS - Clinical Appointment and Referral System/DOH.CARS.Persistance/Migrations/AppDbContextModelSnapshot.cs:line 4358
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot.CreateModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot.get_Model()
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Include provider and version information

EF Core version: Breaks in `8.0.7`,`8.0.8`
Database provider: (e.g. `Microsoft.EntityFrameworkCore.SqlServer`)
Target framework: (e.g. `.NET 8.0`)
Operating system: Both `Mac` and `Windows`
IDE: (e.g. Both `Visual Studio Code` and `Visual Studio 2022 17.8.5`)

**Comment by ajcvickers** [comment] 2024-08-29 11:57
@AndriySvyryd FYI, looks like a regression in a patch.

**Comment by AndriySvyryd** [comment] 2024-08-29 17:54
Duplicate of #34201
Should be fixed in 8.0.9

**Closed by AndriySvyryd** 2024-08-29 17:54 UTC
Labels: type-bug, regression, customer-reported, area-model-building

**Comment by stevendarby** [comment] 2024-09-13 15:14
@AndriySvyryd do you know when 8.0.9 is due? October patch tuesday?

**Comment by AndriySvyryd** [comment] 2024-09-13 15:57
@stevendarby Yes, and it will be called 8.0.10. We had to skip 8.0.9 due to some issues during the release.
