### ISSUE TITLE
.Select() Projection causes Entity to not be tracked

### ISSUE THREAD

**Issue by RickStrahl** [dotnet/efcore#18825] opened 2019-11-09 08:37 UTC
I have an application that does the following:

```cs
 [TestMethod]
public void ProjectionSelectBug()
{
    int userPk = 1;

    var user = Context.UserInfos
        .Include(p => p.Privileges)
        .Select(p => new UserInfo
        {
            UserPk = p.UserPk,
            UserId = p.UserId,
            FirstName = p.FirstName,
            LastName = p.LastName,
            Department = p.Department,
            Privileges = p.Privileges //.Where(p2 => p2.AccessKey.StartsWith("FTDB_")).ToList()
        })
        .FirstOrDefault(u => u.UserPk == userPk);

    string updatedLastName = "Updated Name";
    user.LastName = updatedLastName;

    int res = Context.SaveChanges();

    var newContext = new FtdbContext();
    var user2 = newContext.UserInfos        
        .FirstOrDefault(u => u.UserPk == userPk);

    // fails - value not updated
    Assert.AreEqual( updatedLastName, user2.LastName);
};
```            
I'm using the projection to filter the list of privileges. The query returns the correct entity along with the correct child relationship and filtered privileges.

However, the result is not tracked and when I change the entity values then `SaveChanges()` the changes are not written.

The Assert fails with user2.LastName remaining at the original, unchanged value. 

It fails with the `.Select()` projection. If I remove the projection then it works.

### Expected Behavior
I would expect a projection of an Entity Type to be tracked as long as the type is an entity type.

According to the docs at https://docs.microsoft.com/en-us/ef/core/querying/tracking#tracking-and-custom-projections, it looks to me that the above should work, but it's unclear on whether the original entity going into the projection has to stay intact. If so that seems silly - as long as an entity type is created it should be tracked.

### Config
EF Core version: 3.0

Database provider: . Microsoft.EntityFrameworkCore.SqlServer

Target framework:  .NET Core 3.0

Operating system: Windows 10

IDE: Visual Studio 2019 16.3

**Comment by smitpatel** [comment] 2019-11-09 11:55
Duplicate of #12668

**Comment by RickStrahl** [comment] 2019-11-09 18:41
Closing as I realized this is by design (and mostly makes sense :smile:).

Wish there was a way to transform an entity though so you can updated or even filter a value more easily (like the example above) - there are other ways, but this certainly would be easiest).

**Closed** 2022-10-16 14:55 UTC
Labels: closed-no-further-action, customer-reported
