### ISSUE TITLE
Nullable navigation property used in anonymous result selects all fields from main table

### ISSUE THREAD

**Issue by milanc** [dotnet/efcore#7579] opened 2017-02-09 22:12 UTC
Hi

When projecting to anonymous type generated SQL is different for nullable vs not nullable navigation properties.

I am building anonymous result based like this
dbContext.Requisitions.Select(r =>new {r.Location, r.Id})

**and if location is mapped as required** (not nullable)
(x => x.LocationId).HasColumnName(@"Location_Id").HasColumnType(@"int").**IsRequired()**

then generated SQL is this (**gets only fields needed for anonymous**)
SELECT TOP(@__p_0) [r.Location].[Location_Id], [r.Location].[Location_Nm], [r].[Req_Id]
FROM [dbo].[REQ] AS [r]
INNER JOIN [dbo].[LOCATION] AS [r.Location] ON [r].[Location_Id] = [r.Location].[Location_Id]

**but if location is not required**
(x => x.LocationId).HasColumnName(@"Location_Id").HasColumnType(@"int")

then generated SQL is this (**gets all fields from main table**)
SELECT TOP(@__p_0) [r].[Req_Id], [r].[Acct_Info_Tx], [r].[Is_Template], [r].[Location_Id],  [r].[Title_Nm], [r.Location].[Location_Id], [r.Location].[Location_Nm]
FROM [dbo].[REQ] AS [r]
LEFT JOIN [dbo].[LOCATION] AS [r.Location] ON [r].[Location_Id] = [r.Location].[Location_Id]

**Expected:**
Both generated SQL scripts are including only fields required to project to anonymous type

EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2015

Thank you

**Comment by smitpatel** [comment] 2017-02-09 22:39
dupe of #6647

**Closed** 2022-10-16 10:52 UTC
