### ISSUE TITLE
EFCore thinks Nullable SQLite numeric columns are Not Nullable

### ISSUE THREAD

**Issue by prenaut41** [dotnet/efcore#12306] opened 2018-06-08 16:21 UTC
For each entity in my data model, I'm reaching into my DbContext.Model to discover the data model for that entity.  (I use this in a controller that renders the entity's data model as JSON for consumption in my web application to automatically build forms and perform front-end data validations.)  

This has worked well using SQL Server.  However, I've run into a problem with SQLite.  It seems that if a column is a numeric type (at least non-text), then the Model builder thinks that it is non-nullable, even if it is set to be nullable.  
Not sure if it matters, but another difference with what I'm doing now is that previously with SQL Server I was using a Database-first approach.  In this case, I'm using SQLite in a code-first approach and performing migrations from VS2017.  

I do not use DataAnnotation attributes in my entity classes.  Normally, if I want a field to be required or non-nullable, I will do this in my DbContext with the Fluent API:
`        protected override void OnModelCreating(ModelBuilder modelBuilder) {
            modelBuilder.Entity<EntityClassName>(entity => {
                entity.Property(e => e.PropertyName)
                    .IsRequired();
             });
         };
`

The Create Table SQL statement in the migration from VS2017 set these columns to be nullable with the following column specification in the SQLite Create Table statement: 
> "[ColumnName] [DataType] NULL,"

So everything I see in my DbContext, Entity Classes, and the SQLite schema seem to indicate that columns should be nullable.  

When debugging in my controller, and checking the collection of Properties for each EntityType in the model, this is the case for any **text** field that was set this way, with the Property.IsNullable is found to be true as expected.  
But, the Property.IsNullable appears to be false for any column that has a SQLite type of **Integer or Real**. 
 
Any ideas?    Is this a known issue, or might I be missing something?  

### Environment:
SQLite 3.24.0
EF Core version: 2.0.3
IDE: Visual Studio 2017 15.5.2

**Comment by ajcvickers** [comment] 2018-06-15 16:54
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by prenaut41** [comment] 2018-06-18 17:36
Update - I think my original problem was because I forgot to declare my nullable fields as "int?" or "float?" with the ending "?" character to indicate they were nullable.  This resulted in EFCore applying the default for these types, which is to make them required.

**Closed** 2022-10-16 12:30 UTC
Labels: closed-could-not-reproduce, customer-reported
