### ISSUE TITLE
dotnet-ef scaffolding issue starting .NET 6

### ISSUE THREAD

**Issue by freshe** [dotnet/efcore#26631] opened 2021-11-11 15:47 UTC
Starting .NET 6 (dotnet-ef 6.0.0) I can no longer reverse engineer our company database.
Seems to be because of ambiguity of foreign key column names. No problem in dotnet-ef 5.x.

_The property or navigation 'Groups' cannot be added to the entity type 'SomeTable (Dictionary<string, object>)' because a property or navigation with the same name already exists on entity type 'SomeTable (Dictionary<string, object>)'._

Reproduced it with a small test database.

```
dotnet ef dbcontext scaffold "Server=localhost;Database=EfTest;User Id=sa;Password=password" Microsoft.EntityFrameworkCore.SqlServer --context DbContext --output-dir "Data"
```
--

```

CREATE DATABASE EfTest
GO

USE EfTest
GO

CREATE TABLE GroupTable1
(
	GroupId INT NOT NULL,
	Name NVARCHAR(100) NOT NULL

	PRIMARY KEY (GroupId)
)

CREATE TABLE GroupTable2
(
	GroupId INT NOT NULL,
	Name NVARCHAR(100) NOT NULL

	PRIMARY KEY (GroupId)
)

CREATE TABLE SomeTable
(
	SomeId INT NOT NULL,
	Name NVARCHAR(100) NOT NULL,

	PRIMARY KEY (SomeId)
)

CREATE TABLE SomeJoinTable1
(
	SomeId INT NOT NULL,
	GroupId INT NOT NULL,

	PRIMARY KEY (SomeId, GroupId),
	FOREIGN KEY (SomeId) REFERENCES SomeTable (SomeId),
	FOREIGN KEY (GroupId) REFERENCES GroupTable1 (GroupId)
)

CREATE TABLE SomeJoinTable2
(
	SomeId INT NOT NULL,
	GroupId INT NOT NULL,

	PRIMARY KEY (SomeId, GroupId),
	FOREIGN KEY (SomeId) REFERENCES SomeTable (SomeId),
	FOREIGN KEY (GroupId) REFERENCES GroupTable2 (GroupId)
)
```

**Comment by smitpatel** [comment] 2021-11-11 15:49
Duplicate of #26496

**Closed** 2022-10-16 20:13 UTC
Labels: closed-duplicate, customer-reported
