### ISSUE TITLE
Clause order is mixed up when logging SQL statements to console

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#27687] opened 2022-03-22 19:39 UTC
## File a bug

Here is the code from the db context that sets up the logging:

```C#
public static readonly ILoggerFactory CustomLoggerFactory = LoggerFactory.Create(builder =>
{
    builder
    .AddFilter((category, level) =>
        category == DbLoggerCategory.Database.Command.Name && level == LogLevel.Information)
    .AddConsole();
});
```

Here is a redacted copy of the output to the console. Notice the LINQ-like clause ordering (the code above used to produce correct SQL statement order):

```sql
FROM [TableName] AS [u]
LEFT JOIN (
    SELECT [u].[Id]
        , [u].[OtherValue]
        , [t].[SomeId]
        , [t].[AnotherId]
        , [t].[Id]
        , [t].[AValue]
    SELECT [u0].[SomeId]
        , [u0].[AnotherId]
        , [u1].[Id]
        , [u1].[AValue]
    INNER JOIN [TableName] AS [u1]
        ON [u0].[SomeId] = [u1].[Id]
    FROM [Table2Name] AS [u0]
    WHERE (
            ([u].[SomeDate] IS NOT NULL)
            AND ([u].[SomeFlag] = CAST(1 AS BIT))
            )
        AND EXISTS (
            FROM [db].[SomeView] AS [g]
            WHERE ([g].[AFlag] = CAST(1 AS TINYINT))
            )
    ) AS [t]
    ON [u].[Id] = [t].[AnotherId]
ORDER BY [u].[Id]
    , [t].[SomeId]
    , [t].[AnotherId]
SELECT 1
```

### Include provider and version information

EF Core version: 6.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: macOS 12.3
IDE: Visual Studio for Mac 17 build 8001

**Comment by smitpatel** [comment] 2022-03-22 21:51
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by smitpatel** [comment] 2022-03-23 18:49
1. Above logger registration should produce proper output only. `ToQueryString()` API should give same output.
2. This feature is not provider specific (though generated SQL may have provider specific printing.

Currently above SQL output shows that things are out of order but without looking at whole repro code which produces this, it is hard to comment what is wrong. We haven't seen this in normal workflow/test runs. There may be multiple concurrent running queries, with incorrect services or interceptors at play.

**Comment by mrlife** [comment] 2022-04-05 15:32
@ajcvickers It is taking a while to build a project that reproduces this. Is it possible to have an extension?

**Comment by ajcvickers** [comment] 2022-04-19 12:19
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:29 UTC
Labels: closed-could-not-reproduce, customer-reported
