### ISSUE TITLE
Translate Computed Properties

### ISSUE THREAD

**Issue by OsamaAlRashed** [dotnet/efcore#32276] opened 2023-11-11 21:48 UTC
I have two tables, Request and State. In the Request table, I've defined a computed property CurrentStatus as follows:

```csharp
public abstract class Request<TKey, TStatus>
    where TKey : IEquatable<TKey>
    where TStatus : struct, Enum
{
    private readonly List<State<TKey, TStatus>> _statuses = new();
    
    [NotMapped]
    public virtual TStatus? CurrentStatus
        => _statuses
            .OrderByDescending(x => x.DateSigned)
            .Select(x => x.Status)
            .FirstOrDefault();
}
```

Is there any way to translate the CurrentStatus property without the need to store it in the database explicitly or create a function? I'm looking for a solution that handles this calculation without requiring a database column and ensures efficient querying.

I've attempted to use "Computed columns," but they don't seem to support computations involving properties from other tables.

EF Core Version: 7
Database Provider: SQL Server

**Comment by roji** [comment] 2023-11-12 00:26
Duplicate of #10768

**Closed** 2023-11-15 16:12 UTC
Labels: closed-duplicate, customer-reported
