### ISSUE TITLE
Code generated by `dotnet ef dbcontext scaffold` should be marked as auto-generated

### ISSUE THREAD

**Issue by 0xced** [dotnet/efcore#28180] opened 2022-06-07 22:25 UTC
Running `dotnet ef dbcontext scaffold` generates code which often produces analyzer warnings, e.g. using directive that can be removed, virtual member call in constructor, auto-property accessor never used, etc.

Adding an `<auto-generated/>` comment in the generated code would instruct the analyzers to ignore those warnings. See https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options#exclude-generated-code and https://github.com/dotnet/roslyn/issues/3705

**Comment by smitpatel** [comment] 2022-06-08 00:02
Duplicate of #23514

**Closed by smitpatel** 2022-06-08 00:02 UTC
Labels: closed-duplicate, customer-reported

**Comment by ajcvickers** [comment] 2022-06-08 08:58
@0xced Note that the T4 templates work in 7.0 (#4038) will make it easy to add this if you need it.

**Comment by 0xced** [comment] 2022-06-08 11:16
Thanks Arthur, that's good to know. I think it would be better if `<auto-generated/>` is there **by default**, without having to manually tweak templates.

I'm a bit disappointed that #28181 was not merged, it looked like a really quick win to me, literally a 6 lines change (ignoring the tests) that would benefit everyone for a good experience out of the box.

I just came across this code I wrote some time ago to workaround this issue. 😕
```csharp
private static void AddAutogeneratedComment(DirectoryInfo directory)
{
    Parallel.ForEach(directory.GetFiles("*.cs"), file =>
    {
        var lines = new[]
        {
            "// <auto-generated />",
            "#nullable enable",
            "",
        }.Concat(File.ReadAllLines(file.FullName));
        File.WriteAllLines(file.FullName, lines);
    });
}
````
