### ISSUE TITLE
Wrong EF migration script generated from same entity

### ISSUE THREAD

**Issue by yeasin90** [dotnet/efcore#30209] opened 2023-02-04 05:03 UTC
While generating a migration, I just noticed some unwanted changes generated. I haven't made any such changes in my db entity. Below unwanted migration script that was generated:
```C#
migrationBuilder.AlterColumn<short>(
                name: "ReservationTypeId",
                table: "ReservationType",
                type: "smallint",
                nullable: false,
                oldClrType: typeof(short),
                oldType: "smallint")
                .Annotation("Relational:ColumnOrder", 0);
```
### Code
My db entity (no changes have been done here):
```C#
[Table("ReservationType")]
public class ReservationType
{
   [Key]
   [Column(Order = 0)]
   public short ReservationTypeId { get; set; }
   public string Name { get; set; }
}
```
My ef-configuration for this entity (no changes have been done here):
```C#
public class ReservationTypeConfiguration : IEntityTypeConfiguration<ReservationType>
{
   public void Configure(EntityTypeBuilder<ReservationType> builder)
   {
     builder.Property(x => x.ReservationTypeId).ValueGeneratedNever();
   }
}
```
### Version information
- "Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.13"
- "Microsoft.EntityFrameworkCore.Design" Version="6.0.13"
- "Microsoft.EntityFrameworkCore.Tools" Version="6.0.13"
- .NET6
- Visual Studio 2022

**Comment by ajcvickers** [comment] 2023-02-04 10:52
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by yeasin90** [comment] 2023-02-04 11:31
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

@ajcvickers Ok. I will need some time to make some shareable parts as this is happening in one of our production projects. What more information I can share for now: this started to happen when we updated below:
- net6.0
- "Microsoft.EntityFrameworkCore.Design" Version="6.0.11"
- "Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.11"

We were not facing such an issue on ef-migration the before the update:
- net5.0
- "Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.12"
- "Microsoft.EntityFrameworkCore.Design" Version="5.0.12"

**Comment by yeasin90** [comment] 2023-02-04 11:35
@ajcvickers And we are using regular migration command:
`add-migration <Name>`

**Comment by yeasin90** [comment] 2023-02-04 12:28
Updated below packages: 
- "Microsoft.EntityFrameworkCore.Tools" Version="7.0.2"
- "Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.2"
- "Microsoft.EntityFrameworkCore.Tools" Version="7.0.2"
- "Microsoft.EntityFrameworkCore.Design" Version="7.0.2"
- "Microsoft.Data.SqlClient" Version="5.1.0"
(keeping all my libraries/projects in .NET6)

Still the same issue on migration with the command: add-migration <Name>

**Comment by yeasin90** [comment] 2023-02-04 15:47
@ajcvickers Update on this

I downgraded the below packages to the previous version and everything works fine. The migration script is generating only the changes that I have made.

- "Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.12"
- "Microsoft.EntityFrameworkCore.Design" Version="5.0.12"

I am guessing something must have happened from **Version="6.0.11"**

**Comment by ajcvickers** [comment] 2023-02-15 12:24
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-02-15 12:24 UTC
Labels: customer-reported

**Comment by triynko** [comment] 2024-11-19 19:06
Entity framework scripted migrations are completely busted. Some combination of upgradeing from EF 6.4.4. to 6.5.1 and upgrading to SDK-style projects has resulted in "Add-Migration -Script" just randomly omitting 95% of the code passed to the Sql() call in the migration.
