### ISSUE TITLE
Developers can customize type mapping

### ISSUE THREAD

**Issue by JMccain** [dotnet/efcore#18306] opened 2019-10-10 02:52 UTC
请考虑支持 EF 自定义类型映射 和 自定义函数映射

(Consider supporting EF custom type mappings and custom function mappings)

```C#
public class A {
 public Guid? Id {get;set;}
}
```

**Comment by ajcvickers** [comment] 2019-10-10 15:17
Duplicate of #240

**Closed** 2022-10-16 14:48 UTC
Labels: closed-duplicate, customer-reported
