### ISSUE TITLE
FindAsync should return nullable TEntity when nullable reference types are enabled

### ISSUE THREAD

**Issue by ThomasBergholdWieser** [dotnet/efcore#22268] opened 2020-08-27 08:29 UTC
Currently the FindAsync method returns a non-nullable TEntity. Yet its documentation states that a null value will be returned if no entry can be found.

### Steps to reproduce

https://github.com/dotnet/efcore/blob/19a65f2fa8abef9a02f5ab45e4941dc0ee128698/src/EFCore/DbContext.cs#L1739

### Further technical details

EF Core version: 3.1.7
Database provider: not relevant
Target framework: .NET Core 3.1
Operating system: not relevant
IDE: Visual Studio 2019 Professional

**Comment by ThomasBergholdWieser** [comment] 2020-08-28 09:46
Just realized the same applies to FirstOrDefaultAsync as well (probably to some other methods too)

**Comment by ajcvickers** [comment] 2020-08-28 19:35
Duplicate of #14150.

**Closed** 2022-10-16 18:38 UTC
Labels: closed-duplicate, customer-reported
