### ISSUE TITLE
DB exception causes all data from all tables to be loaded into memory

### ISSUE THREAD

**Issue by Mads-OpenMinds** [dotnet/efcore#23831] opened 2021-01-08 13:55 UTC
After upgrading to EFCore 5.0.1 from 3.1.10 we are experiencing a weird behavior from the framework.
When the database causes an exception, e.g. a unique constraint violation, EFCore seems to iterate through all DbSet in the context and selecting all data from them.

### Include your code
A sample app demonstrating the problem is available [here](https://github.com/Mads-OpenMinds/EfProblemSample)

### Include stack traces
The stacktraces are in this case not relevant (out of memory) the SQL log just prior to the exception is however.
In the sample linked above, you will find lines likes these:
[13:25:55 INF] Executed DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "e"."Id", "e"."SomeOtherProperty"
FROM "Entity2s" AS "e"
[13:25:55 INF] Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "e"."Id", "e"."AUniqueProperty", "e"."SomeProperty"
FROM "Entity1s" AS "e"

Notice all is selected from all tables without any WHERE clause to limit results.

### Include provider and version information

EF Core version: 5.0.1
Database provider: reproduced in both  Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore.SqlLite
Target framework: .NET 5.0
Operating system: Windows 10 (problem initially experienced in our docker image based on aspnet:5.0-buster-slim)
IDE: Visual Studio 2019

**Comment by ErikEJ** [comment] 2021-01-08 14:03
Are you using Serilog.Exceptions ?
 -  see https://github.com/RehanSaeed/Serilog.Exceptions#serilogexceptionsentityframeworkcore 
(possible duplicate of #15214 )

**Comment by ErikEJ** [comment] 2021-01-08 14:12
I can set that you are indeed!

`<PackageReference Include="Serilog.Exceptions" Version="6.0.0" />`

**Comment by ajcvickers** [comment] 2021-01-08 15:00
Closing as duplicate of #15214

**Closed** 2022-10-16 19:17 UTC
Labels: closed-duplicate, customer-reported
