### ISSUE TITLE
Query: compilation error for include with groupby and FirstOrDefault/SingleOrDefault

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#8378] opened 2017-05-04 01:01 UTC
Standalone repro:

```cs
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureCreated();
            }

            using (var ctx = new MyContext())
            {
                var includes = ctx.Episodes.Include(x => x.Releases).ThenInclude(x => x.ReleaseGroup)
                    .Include(x => x.EpisodeViews);

                var query =
                    (from episodeGroup in includes.GroupBy(e => e.SeriesId)
                     select episodeGroup).SingleOrDefault();
            }
        }
    }

    public class Episode
    {
        public int Id { get; set; }
        public int SeriesId { get; set; }

        public List<Release> Releases { get; set; }
        public List<EpisodeView> EpisodeViews { get; set; }
    }

    public class Release
    {
        public int Id { get; set; }
        public ReleaseGroup ReleaseGroup { get; set; }
    }

    public class ReleaseGroup
    {
        public int Id { get; set; }
    }

    public class EpisodeView
    {
        public int Id { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Episode> Episodes { get; set; }
        public DbSet<Release> Releases { get; set; }
        public DbSet<ReleaseGroup> ReleaseGroups { get; set; }
        public DbSet<EpisodeView> EpisodeViews { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=Repro8378;Trusted_Connection=True;MultipleActiveResultSets=True");
        }
    }
```

Exception:

```
System.ArgumentException: Expression of type 'System.Object' cannot be used for parameter of type 'Microsoft.EntityFrameworkCore.Metadata.IEntityType' of method 'Void StartTracking(System.Object, Microsoft.EntityFrameworkCore.Metadata.IEntityType)'
   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1)
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.IncludeLoadTreeNodeBase.Compile(QueryCompilationContext queryCompilationContext, QueryModel queryModel, Boolean trackingQuery, Boolean asyncQuery, Int32& collectionIncludeId, QuerySourceReferenceExpression targetQuerySourceReferenceExpression) in C:\git\EntityFramework\src\EFCore\Query\Internal\IncludeCompiler.IncludeLoadTreeNodeBase.cs:line 60
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.IncludeLoadTree.Compile(QueryCompilationContext queryCompilationContext, QueryModel queryModel, Boolean trackingQuery, Boolean asyncQuery, Int32& collectionIncludeId) in C:\git\EntityFramework\src\EFCore\Query\Internal\IncludeCompiler.IncludeLoadTree.cs:line 57
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.CompileIncludes(QueryModel queryModel, Boolean trackingQuery, Boolean asyncQuery) in C:\git\EntityFramework\src\EFCore\Query\Internal\IncludeCompiler.cs:line 80
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery) in C:\git\EntityFramework\src\EFCore\Query\EntityQueryModelVisitor.cs:line 264
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery) in C:\git\EntityFramework\src\EFCore.Relational\Query\RelationalQueryModelVisitor.cs:line 1001
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel) in C:\git\EntityFramework\src\EFCore\Query\EntityQueryModelVisitor.cs:line 165
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel) in C:\git\EntityFramework\src\EFCore\Storage\Database.cs:line 70
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType) in C:\git\EntityFramework\src\EFCore\Query\Internal\QueryCompiler.cs:line 134
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0() in C:\git\EntityFramework\src\EFCore\Query\Internal\QueryCompiler.cs:line 102
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in C:\git\EntityFramework\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 69
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in C:\git\EntityFramework\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 44
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in C:\git\EntityFramework\src\EFCore\Query\Internal\QueryCompiler.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in C:\git\EntityFramework\src\EFCore\Query\Internal\EntityQueryProvider.cs:line 62
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
   at Repro8378.Program.Main(String[] args) in C:\Projects\Repro8378\Repro8378\Program.cs:line 24
```

**Comment by anpete** [comment] 2017-06-28 23:41
No longer crashes but doesn't look to be correctly applying the _Include call to the nested GB element selector.

**Comment by anpete** [comment] 2017-06-29 21:03
Confirmed fixed.

**Comment by maumar** [comment] 2017-07-03 20:05
This still breaks on current bits:


```cs
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureCreated();
            }

            using (var ctx = new MyContext())
            {
                var episodesQuery = ctx.Episodes.Include(x => x.Releases).ThenInclude(x => x.ReleaseGroup)
                    .Include(x => x.EpisodeViews);


                IQueryable<SeasonData> seasonDataQuery = from episodeGroup in episodesQuery.GroupBy(episode => new { episode.SeriesId, episode.SeasonNumber })
                    select new SeasonData
                    {
                        Episodes = episodeGroup.Select(x => new EpisodeData
                        {
                            Releases = x.Releases.Select(y => new ReleaseData
                            {
                                ReleaseGroup = y.ReleaseGroup,
                                Release = y
                            }).ToList()
                        }).ToList()
                    };

                SeasonData seasonData = seasonDataQuery.SingleOrDefault();
            }
        }
    }

    public class SeasonData
    {
        public List<EpisodeData> Episodes { get; set; }
    }

    public class EpisodeData
    {
        public List<ReleaseData> Releases { get; set; }
    }

    public class ReleaseData
    {
        public ReleaseGroup ReleaseGroup { get; set; }
        public Release Release { get; set; }
    }

    public class Episode
    {
        public int Id { get; set; }
        public int SeriesId { get; set; }
        public int SeasonNumber { get; set; }

        public List<Release> Releases { get; set; }
        public List<EpisodeView> EpisodeViews { get; set; }
    }

    public class Release
    {
        public int Id { get; set; }
        public ReleaseGroup ReleaseGroup { get; set; }
    }

    public class ReleaseGroup
    {
        public int Id { get; set; }
    }

    public class EpisodeView
    {
        public int Id { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Episode> Episodes { get; set; }
        public DbSet<Release> Releases { get; set; }
        public DbSet<ReleaseGroup> ReleaseGroups { get; set; }
        public DbSet<EpisodeView> EpisodeViews { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=Repro8378;Trusted_Connection=True;MultipleActiveResultSets=True");
        }
    }
```

**Comment by Coder-212** [comment] 2019-01-25 09:19
for LastOrDefault too

**Comment by smitpatel** [comment] 2019-09-04 06:38
Duplicate of #17068

**Closed** 2022-10-16 11:03 UTC
