### ISSUE TITLE
Negation expression in projection causes "Incorrect syntax near '='." error when executed (SqlServer)

### ISSUE THREAD

**Issue by jeremyZX** [dotnet/efcore#3202] opened 2015-09-23 16:26 UTC
I'm unable to compose a query that uses a negation expression as part of the projection.  These simple cases result in the same error:

``` c#
var studentList = context.Students
  .Select(x => new { Name = x.Name, IsActive = !x.IsInactive }).ToList();

var studentIsNotDeleted = context.Students
  .Where(x => x.Id == studentId).Select(x => !x.IsDeleted).FirstOrDefault();
```

These all throw a SqlException: `"Incorrect syntax near '='."`

The generated SQL appears to be syntactically invalid:

``` sql
SELECT [a].[IsInactive] = 0
FROM [dbo].[Students] AS [a]
```

Contrasted with EF6:

``` sql
SELECT 
    CASE WHEN ([Extent1].[IsInactive] <> cast(1 as bit)) THEN cast(1 as bit) 
    WHEN ([Extent1].[IsInactive] = 1) THEN cast(0 as bit) END AS [C1]
    FROM [dbo].[Students] AS [Extent1]
```

**Comment by divega** [comment] 2015-09-23 18:00
This scenario is described in #649 which we triaged as pri1. Conditional expressions in the projection need to be wrapped in a CASE statement, or I guess they could be evaluated in memory. 

@maumar @anpete any thoughts?

**Comment by rowanmiller** [comment] 2015-09-29 18:11
Dupe of #649
Bumping priority of #649 too

**Closed** 2022-10-16 09:09 UTC
