### ISSUE TITLE
Nullifying One to Zero or One related data while detached (sqlite) doesn't update its column on the db table upon Update call

### ISSUE THREAD

**Issue by johnnildo** [dotnet/efcore#7385] opened 2017-01-10 20:35 UTC
When a detached entity has one navigation property nullified, DbContext.Update(entity) doesn't nullify its corresponding column.

### Steps to reproduce

Execute the following code after running Add-Migration:

```c#
class One
{
    public int Id { get; set; }
    public string Text { get; set; }
    public ZeroOrOne Property { get; set; }
}

class ZeroOrOne
{
    public int Id { get; set; }
}

class TestContext : DbContext
{
    public DbSet<One> Ones { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Filename=local.db");
        base.OnConfiguring(optionsBuilder);
    }
}

class Program
{
    static void Main(string[] args)
    {
        var one = new One { Property = new ZeroOrOne(), Text = "Adding related"};
        using (var context = new TestContext())
        {
            context.Database.Migrate();
            context.Ones.Add(one);
            context.SaveChanges();
        }
        one.Text = null;
        one.Property = null;

        using (var context = new TestContext())
        {
            context.Ones.Update(one);
            context.SaveChanges();
        }
    }
}
```
### Expected results
Text column of One table to be Null. Property column of the One table to be null.

### Actual results
Text column gets nullified but Property column does not.

### Additional notes
As pointed out by Ivan Stoev on [this SO answer](http://stackoverflow.com/a/41577514/276500), this seems to be due to the fact that the shadow and navigation properties are not marked as modified by the update call.

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Irrelevant? (Windows 10)
IDE: Visual Studio 2015

**Comment by ajcvickers** [comment] 2017-01-10 21:44
Dupe of #6504. To summarize, EF isn't tracking the entity when the navigation is set to null. Once the entity is attached there is no way to tell that the navigation is not null just because the related entity is not loaded . #6504 has some ideas on how to handle this situation.

**Comment by milasch** [comment] 2017-01-11 16:07
Sorry I didn't quite get what you were suggesting on #6504 (adding the FK). What I did is the below, which seems a bit hackish. Was that what you meant?

    class One
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int? ZeroOrOneId { get; set; }
        public ZeroOrOne ZeroOrOne { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var one = new One { ZeroOrOne = new ZeroOrOne(), Text = "Adding related"};
            using (var context = new TestContext())
            {
                context.Database.Migrate();
                context.Ones.Add(one);
                context.SaveChanges();
            }
            one.Text = null;
            one.ZeroOrOne = null;

            using (var context = new TestContext())
            {
                context.Ones.Update(one);
                if (one.ZeroOrOne == null && one.ZeroOrOneId != null)
                {
                    one.ZeroOrOneId = null;
                }
                context.SaveChanges();
            }
        }
    }

**Comment by ajcvickers** [comment] 2017-01-11 17:24
@milasch That's one way to do it. You could just set ZeroOrOneId to null when you set ZeroOrOne to null, or you could just set ZeroToOne to null while it is being tracked. What is best depends on how your application is constrained. The way it is written above asserts that if any ZeroOrOne exists, then it is loaded. If this assertion doesn't hold, then the code will end up severing relationship or deleting entities when it shouldn't.

**Comment by milasch** [comment] 2017-01-11 17:41
@ajcvickers  Ah, setting ZeroOrOneId to null along with ZeroOrOne seems to do the trick, which is definitely preferred to the hack I posted. Thank you.

**Closed** 2022-10-16 10:49 UTC
