### ISSUE TITLE
[Required] attribute is ignored for owned entity type's properties

### ISSUE THREAD

**Issue by arphox** [dotnet/efcore#21141] opened 2020-06-05 04:53 UTC
Hi!

The NPGSQL team said this problem is in EF Core and not in their provider code. (npgsql/efcore.pg#1402)

In `Npgsql.EntityFrameworkCore.PostgreSQL` version `3.1.4`,
I have the following hierarchy:
```C#
public class Profile
{
    public int Id { get; set; }

    [Required]
    public string CompanyName { get; set; }

    [Required]
    public ProfileAddress Address { get; set; }
}

[Owned]
public sealed class ProfileAddress
{
    [Required]
    public string Country { get; set; }

    [Required]
    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }
}
```

and in my DbContext, only `Profile` is included as a db set:
`public DbSet<Profile> Profiles { get; set; }`

This causes the provider to generate address data inside the `Profile` table which is great, but `Country` and `AddressLine1` are nullable while I configured them to be **Required**.

This is the generated migration part:
```C#
migrationBuilder.CreateTable(
    name: "Profiles",
    columns: table => new
    {
        Id = table.Column<int>(nullable: false)
            .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
        CompanyName = table.Column<string>(nullable: false),
        Address_Country = table.Column<string>(nullable: true),
        Address_AddressLine1 = table.Column<string>(nullable: true),
        Address_AddressLine2 = table.Column<string>(nullable: true)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Profiles", x => x.Id);
    });
```

I expect both `Address_Country` and `Address_AddressLine1` to be **not** nullable, as I just configured. I also tried configuring the same with FluentAPI but that did not work for me as well.

**Comment by GertArnold** [comment] 2020-06-05 07:14
https://github.com/dotnet/efcore/issues/16943

**Comment by ajcvickers** [comment] 2020-06-05 16:00
Duplicate of #12100

**Closed** 2022-10-16 18:28 UTC
Labels: customer-reported
