### ISSUE TITLE
Being able to scaffold the MS_Description to the models.

### ISSUE THREAD

**Issue by Aangbaeck** [dotnet/efcore#19302] opened 2019-12-13 07:28 UTC
I would like to get the extended sql-property "MS_Description" as seen in the SQL Management Studio to represent the summary of properties in the models.

When I'm doing a scaffold of the database, for example

`dotnet ef dbcontext scaffold "Server=xxx.xx.xx.xx;Database=DBName;Initial Catalog=DBName;Persist Security Info=True;User ID=sa;Password=somethingSecret" Microsoft.EntityFrameworkCore.SqlServer -o Models --project ProjectName --force `

the scaffolded model should look something like this:

```
public partial class TestClass
    {
        /// <summary>
        /// Primary key or whatever i have wrote in the description
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// Description2
        /// </summary>
        public long? Parameter2 { get; set; }
    }
```

Would that be doable?

**Comment by ajcvickers** [comment] 2019-12-15 20:37
Duplicate of #19113

**Closed** 2022-10-16 18:01 UTC
Labels: closed-duplicate, customer-reported
