### ISSUE TITLE
null-coalescing operator in LINQ query giving SQLException error

### ISSUE THREAD

**Issue by jamesport079** [dotnet/efcore#14686] opened 2019-02-13 09:18 UTC
This query used to work properly in EF6 but is giving an error in EF Core.
When I try this query I get an SQLException error. I remove the null-coalescing operator (??) and it works properly. 

                var query = from p in context.Patients.AsNoTracking()
                            group p by p.Locality into localitiesGroup
                            let PatientsCount = localitiesGroup.Count()
                            orderby PatientsCount descending, localitiesGroup.Key
                            select new
                            {
                                Locality = localitiesGroup.Key ?? "Others", //Not working in EF Core
                                Count = PatientsCount
                            };

From SQL profiler I get this translated SQL that is probably raising the error:

SELECT COALESCE([p].[Locality] AS [Key], N'Others') AS [Locality], COUNT(*) AS [Count]
FROM [Patients] AS [p]
GROUP BY [p].[Locality]
ORDER BY [Count] DESC, [Key]

When I remove the null coalescing operator from the LINQ query I get this translated SQL in SQL profiler:

SELECT [p].[Locality], COUNT(*) AS [Count]
FROM [Patients] AS [p]
GROUP BY [p].[Locality]
ORDER BY [Count] DESC, [Locality]

```
Exception message:
System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Incorrect syntax near the keyword 'AS'.
  Source=.Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__12.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__11.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext() in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Aggregate.cs:line 128
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DentalDesktop.View.Dialogs.Statistics.Locality.<GetLocalityStatisticsAsync>d__1.MoveNext() in C:\Users\james\Source\Workspaces\DDesktop2\DentalDesktop\DentalDesktop\View\Dialogs\Statistics\Locality.xaml.cs:line 32
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DentalDesktop.View.Dialogs.Statistics.Locality.<Window_Loaded>d__2.MoveNext() in C:\Users\james\Source\Workspaces\DDesktop2\DentalDesktop\DentalDesktop\View\Dialogs\Statistics\Locality.xaml.cs:line 55
```

### Further technical details
EF Core version: 2.2.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.9.7)

**Comment by smitpatel** [comment] 2019-02-14 02:22
Duplicate of #12826

**Closed** 2022-10-16 13:51 UTC
Labels: closed-duplicate, customer-reported
