### ISSUE TITLE
Defining Query vs ToView

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#17804] opened 2019-09-12 18:54 UTC
If both of them are defined which one should be applied?

**Comment by bricelam** [comment] 2019-09-13 21:55
Duplicate of #17270

**Comment by smitpatel** [comment] 2019-09-13 22:01
It mentions the other way is default then what we have right now. (Currently defining query gets applied). Should we make "bug-fix"?

**Comment by bricelam** [comment] 2019-09-13 22:19
Current way sounds correct to me

**Comment by divega** [comment] 2019-09-16 17:44
Triage: We will assume the current behavior is correct for now. May revisit in #17270.

**Closed** 2022-10-16 14:41 UTC
Labels: closed-out-of-scope
