### ISSUE TITLE
Auto update internal fields on save

### ISSUE THREAD

**Issue by DimitryNechaev** [dotnet/efcore#23235] opened 2020-11-09 01:50 UTC
Have a problem autoupdating internal fields on save.
Have a base type with these fields.

Iterating though change tracker and updating these fields in `SavingChanges` handler does not work.
Unfortunately EF does not see the change, even if I call `ChangeTracker.DetectChanges()`

```C#
            var newOrder = new tblSrsOrder()
            {
                MagentoPoNumber = magentoPoNumber,
                FitmentStoreCode = branchCode,
                OrderDate = orderDate,
                OrderValue = orderValue,
            };

            ObjectContext.Add(newOrder);
            await ObjectContext.SaveChangesAsync(); // <<< Error here as CreateID is NULL
```
DbContext
```C#
...
ctor() {
            base.SavingChanges += OnSavingChanges;
}
...
        private void OnSavingChanges(object sender, SavingChangesEventArgs e)
        {
            foreach (var entityEntry in ChangeTracker.Entries()) // Iterate all made changes
            {
                if (entityEntry.Entity is HasStatusAndUserTracking tracker)
                {
                    if (entityEntry.State == EntityState.Added) // If you want to update TenantId when Order is added
                    {
// tested that debugger gets into this line, so the logic is actually executed
                        tracker.CreateID = 1; // dummy value for demonstration
                        tracker.CreateTS = DateTime.Now() // same (dummy)
                }
                ChangeTracker.DetectChanges();
            }
        }
```

I tried to tweak with `entityEntry.Property("CreateID").IsModified = true;`, setting `entityEntry.Property("CreateID").CurrentValue` - does not work either.

Please explain what is the correct way to implement such logic without overriding each overload of SaveChanges[Async] on DbContext.

### provider and version information

EF Core version: 5.0.0-rc.2.20475.6
Database provider: SqlServer
Target framework: Standard 2.1
Operating system: Windows
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment] 2020-11-09 16:40
@DimitryNechaev I don't see anything obviously wrong. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-11-20 15:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:08 UTC
Labels: closed-could-not-reproduce, customer-reported
