### ISSUE TITLE
store procedure slow only when executed from EF core

### ISSUE THREAD

**Issue by max-favilli** [dotnet/efcore#13106] opened 2018-08-24 02:06 UTC
I have the following line of code in my application:
`          var all = await _db.Query<RimsWheelsForCarNoKtype_Result>().FromSql("exec RimsWheelsForCarNoKtype {0}, {1}, {2}, {3}, {4}, {5}, {6}, {7}", maker, modelName, string.IsNullOrEmpty(chassis) ? string.Empty : chassis, year, wheelbrand, wheelmodel, wheelholes, wheelcolor).ToListAsync();
`

In VisualStudio debugger I can see it takes sometimes 8 seconds, sometimes 15 seconds, sometimes 28 seconds to execute:
![image](https://user-images.githubusercontent.com/1472899/44560337-80cd6700-a74f-11e8-84e0-3b5c1da266af.png)

In SQL Profiler I can see consistent results (15s):
![image](https://user-images.githubusercontent.com/1472899/44560087-2d0e4e00-a74e-11e8-863e-c548e894d012.png)

But if I execute the same tsql manually I can see fairly different execution times (avg 200ms):
![image](https://user-images.githubusercontent.com/1472899/44560150-8aa29a80-a74e-11e8-9e2c-31553af3bb5e.png)

Which is consistent with the results I was getting while testing the store procedure (avg 200ms):
![image](https://user-images.githubusercontent.com/1472899/44560396-d0ac2e00-a74f-11e8-8d6f-262b61dd9307.png)

I thought about leaky connections, but I have none:
![image](https://user-images.githubusercontent.com/1472899/44560439-11a44280-a750-11e8-9b47-0b60e1f5103e.png)

**Now the funniest part**, if I restart IIS and relaunch the application (it's a website) duration drops to a normal level:
![image](https://user-images.githubusercontent.com/1472899/44560559-a0b15a80-a750-11e8-978c-22a02c5ec5b7.png)

But if keep testing, after a little while it starts again to require tens of seconds to execute.

I am puzzled, and I don't know where to look for the problem.

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.1

**Comment by ajcvickers** [comment] 2018-08-24 19:11
@max-favilli Can you post a runnable project/solution or complete code listing that demonstrates this behavior? There may be other things going on EF that is impacting the performance, but that's hard to tell without running actual code that reproduces the issue.

**Comment by ajcvickers** [comment] 2018-08-31 16:50
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:27 UTC
Labels: closed-could-not-reproduce, customer-reported
