### ISSUE TITLE
Anybody know how to handle a Sqlite Blob with EF Migrations?

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22710] opened 2020-09-24 21:19 UTC
Moved from discussions.

### Question from @maxmin88

I get this error when I use the SqliteBlob:
"No suitable constructor found for entity type 'SqliteBlob'. "

I also tried using sqlite3_blob and it looks like it works but then I get the error:
"The entity type 'sqlite3_blob' requires a primary key to be defined. If you intended to use a keyless entity type call 'HasNoKey()'."
I have an int Id field in the table.

I then tried creating the migration without the Blob field (which worked fine) and then manually add the Blob field to the created Sqlite DB. And then add the Blob field back into my Entity in my context.cs. But then I get a Migration error when I try to run my project.

An example or documentation somewhere of how to use a Sqlite Blob field with Entity Framework would be very helpful. I have done internet searches and found nothing.

**Comment by bricelam** [comment] 2020-09-25 22:48
Duplicate of #19991

Currently, you have to use a `byte[]` with EF. But you could exclude the property from EF and use SqliteBlob to access the data as needed.

**Closed** 2022-10-16 18:42 UTC
Labels: closed-duplicate, customer-reported
