### ISSUE TITLE
Entities are not being tracked

### ISSUE THREAD

**Issue by ynanech** [dotnet/efcore#34130] opened 2024-07-01 06:54 UTC
## I am using EF Core to implement entity updates. After executing method one, there are no changes in the database. However, method two correctly updates the database. The only difference between the two methods is that in method one, userIds is of type IQueryable, while in method two, userIds is of type int[]. Why is it that the entities queried in method one are not being tracked?

```C#
        public async Task UpdatePostOne()
        {
            var userIds = _dbContext.Set<User>().Where(m => m.UserId == 123).Select(m => m.UserId);

            var posts= await _dbContext.Set<Post>()
                .Where(m => userIds.Contains(m.UserId) && !m.Deleted)
                .ToArrayAsync();

            foreach (var item in posts)
            {
                item.View+= 100;
            }
            await _dbContext.SaveChangesAsync();
        }


        public async Task UpdatePostTwo()
        {
            int[] userIds = [123];

            var posts= await _dbContext.Set<Post>()
                .Where(m => userIds.Contains(m.UserId) && !m.Deleted)
                .ToArrayAsync();

            foreach (var item in posts)
            {
                item.View+= 100;
            }
            await _dbContext.SaveChangesAsync();
        }
```

### Include provider and version information

EF Core version:  8.0.6
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 8.0
Operating system: Win10
IDE: (e.g. Visual Studio  2022  17.10.3)

**Comment by roji** [comment] 2024-07-01 08:31
@ynanech please submit a minimal, runnable code sample that shows the problem - a snippet isn't enough for us to investigate. Your first variant includes the query on the Users DbSet into the main query - that might not be returning the results you're expecting.

**Comment by ajcvickers** [comment] 2024-07-11 18:50
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-07-11 18:50 UTC
Labels: customer-reported
