### ISSUE TITLE
Table-Valued Parameter from local List with Join of DbSet

### ISSUE THREAD

**Issue by philippk80** [dotnet/efcore#30556] opened 2023-03-23 06:46 UTC
Hello,
I'm curious if it's possible to build something like that with ef core:

Using a table-valued parameter and fill it with data from a local List<T> using a DataTable.
After this join it with DbSet<x> and the table-valued parameter as table for the inner join.

I have done it with a rawsql. Is there a way to map and fill the table-valued parameter type and build this with ef core on the fly? (without using rawsql at all)

best regards

**Comment by roji** [comment] 2023-03-23 07:47
Duplicate of #30426

**Comment by roji** [comment] 2023-03-23 07:50
This is something we're actively working on at the moment - but with JSON rather than with table-valued parameters or DataTables. SQL Server TVPs require a type to be defined ahead of time, which isn't appropriate for a component such as EF Core. In addition, this is a SQL Server-specific feature which doesn't exist in other databases.

In contrast, SQL Server OPENJSON allows us to send an array of (primitive values) as a JSON string, and unpack that as a table in the database, allowing JOINs and other similar techniques. Benchmarks show that TVPs are actually slower than this OPENJSON, and very similar techniques around JSON exist in all other major databases as well.

See specifically https://github.com/dotnet/efcore/issues/13617#issuecomment-1471760575 for using this to translate Contains over an array of primitive values, and for benchmarks.

**Comment by yv989c** [comment] 2023-03-28 04:05
Hey @philippk80, while you're waiting, you can give [QueryableValues](https://github.com/yv989c/BlazarTech.QueryableValues) a try. It does exactly what you're asking for, and it even supports `OPENJSON` behind the scenes.

If you want to see an example that relates to your specific use case, check out [this](https://github.com/yv989c/BlazarTech.QueryableValues#complex-type-example). It shows you how to join data from your local list directly into your EF query.

By the way, I'm assuming that you're using SQL Server.

**Closed** 2023-03-29 19:42 UTC
Labels: customer-reported
