### ISSUE TITLE
Horrible Bug in DbSet<TEntity>.RemoveRange

### ISSUE THREAD

**Issue by BARatCSI** [dotnet/efcore#15975] opened 2019-06-06 16:07 UTC
RemoveRange reports:

System.InvalidOperationException: 'The property [id field] on entity type [TEntity] has a temporary value while attempting to change the entity's state to 'Deleted'. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.'

This error occurs when the id field is zero.  This premature check is absolutely incorrect!  Primary keys can be zero.

**Comment by ajcvickers** [comment] 2019-06-06 16:16
@BARatCSI Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-06-14 16:21
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:24 UTC
Labels: closed-could-not-reproduce, customer-reported
