### ISSUE TITLE
How to get English text of label from database based on table reference and field name as dynamically using function 

### ISSUE THREAD

**Issue by ahmedbarbary** [dotnet/efcore#14238] opened 2018-12-23 00:12 UTC
I make project in SQL server 2012  visualstudio2017 and technology i using entity framework core 2.1

what I need is to get text of label control from database based on table name and field name from reference table
so that i need to make function can be used to get the label text when table fields match what exist on reference file based on table and field name .
so that How to do that ?
to more explain what i need see this example
suppose i have item table and product table
Item table have two fields
Item Code
Item Name
Product table have two fields
Product No
Product Name
reference table have 5 fields

serial tablename fieldname   ArabictextforLabel EnglishtextforLabel 
1        Item      ItemCode         كود الصنف              ItemCodeVal
2        Item      ItemName         اسم الصنف              ItemNameVal        
3        Product   ProductNo        كود المنتج              ProductNoVal
4        Product   ProductName      اسم المنتج              ProductNameVal

so that when go to windows form  Items
get text for labels as (ItemCodeval then display itemnameval) for windows form for items(from database reference table)
and same thing on product view display label text as ( productnoval and productnameval) for display windows form for Products(from database reference table)
and when this text for product table and items table changed this will changed on as dynamically
this will make dynamically show text per labels

Can this available on asp.net core 2.1 entity framework core 2.1 or not and how to do it if allowed ?

actually what i need is make function get label text dynamically from reference table based on field name of label control and table name ?

**Comment by ajcvickers** [comment] 2019-01-04 19:03
Duplicate of #14251

**Closed** 2022-10-16 13:45 UTC
Labels: closed-duplicate, customer-reported
