### ISSUE TITLE
Could not load file or assembly System.ComponentModel.Annotations Version=4.2.0.0. Manifest definition does not match.

### ISSUE THREAD

**Issue by JojoEffect** [dotnet/efcore#13756] opened 2018-10-25 09:29 UTC
Hi all,

this could be the same or something related to #13268 but since my problem is not exactly the same I separate it.

**EDIT**: _since I want to build an installer and need to know all dependencies to put them into my package for distribution, I already did what is called "Workaround" in #13268._

After building an installer including all assemblies from output folder (also including the system ones as mentioned here: #13755) my installed application throws an error when initializing the DbContext with the following error:

`Could not load file or assembly 'System.ComponentModel.Annotations, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).`

```
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.CoreConventionSetBuilder.CreateConventionSet()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateConventionSet(IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Trumpf.QDSystem.QDS.Service.Database.Access.UserTable.FindByName(String normalizedName, User& user)
```

If I test this (without the installer in chain) by just deleting the `System.ComponentModel.Annotations.dll` and executing my `.exe` under the `bin` output folder (`Debug` or `Release`), I get a similar exception which points to another version of `System.ComponentModel.Annotations.dll`:

`Could not load file or assembly 'System.ComponentModel.Annotations, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.` cause it was not found.

The file version of the `System.ComponentModel.Annotations.dll` that is copied into my bin/Release (or Debug) folder is `4.6.26515.6`.

EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 15063.1324 (1703)
IDE: Visual Studio 2017 15.8.7

Any ideas? Thanks for help!

**EDIT**: _So the problem in #13268 seems not to be my problem, because that workaround does not work for me. @ajcvickers do you agree?_

**Comment by ajcvickers** [comment] 2018-10-25 16:44
@JojoEffect I'm going to close this as a dupe of #13268 since it looks like the same root cause. If it turns out not to be, then we can revisit later.

**Comment by ajcvickers** [comment] 2018-10-31 18:54
@JojoEffect I don't understand everything that is going on here and in #13268. The workarounds suggested there have not consistently worked for me or others. If we get clear guidance on that issue, and it becomes possible to apply that guidance and be sure that it is right, and if then all the issues reported in #13268 go away but this one remains, then I'll agree that this is a different issue.

I personally believe that there is a bug or bugs exhibiting in #13268, either in the package authoring, NuGet, or the runtime assembly binding. Unfortunately, it's not possible to get to a place where I can point at guidance and then point at code and say that it's not working _even given all the guidance_ because we don't have the guidance and so we don't even know what is supposed to be working.

**Closed** 2022-10-16 13:37 UTC
Labels: customer-reported
