### ISSUE TITLE
.AsNoTracking() breaks .Include(...) for 1-M related (simple) entities

### ISSUE THREAD

**Issue by baloodevil** [dotnet/efcore#18487] opened 2019-10-21 19:56 UTC
When setting AsNoTracking() on a query, .Include(...) does not work if the child object being included is a collection of 'simple' entities.  In other words, the entity does not have a relationship to any other entity, just a bag of properties.  The query for a customer that includes the relationship to the 'simple' entities always results in 0 'simple' entities, unless you remove .AsNoTracking().

So if you have "Customer" object which has "Addresses" (multiple "Address" objects), and "Address" is what I'm calling a 'simple' object, ie: just bag of values like "AddressLine1", "City", etc. without a relationship to another object.  And a "Customer" has "Sales", which are *not* 'simple'.  So they have a relationship to "Store" and "Product", etc.

### Steps to reproduce
Calling...
`var customer1 = context.Customers.AsNoTracking().Include(c => c.Addresses).SingleOrDefault(c => c.CustomerId = 1);`
results in a customer object that does not have any Addresses.

But calling...
`var customer1 = context.Customers.Include(c => c.Addresses).SingleOrDefault(c => c.CustomerId = 1);`
results in a customer object that *does* have Addresses.

Calling...
`var customer1 = context.Customers.AsNoTracking().Include(c => c.Sales).SingleOrDefault(c => c.CustomerId = 1);`
works as expected. (note the related 1-M entity is a 'complex' object (Sales) instead of a 'simple' object (Addresses).

### Further technical details

EF Core version: 2.2.6
Database provider: Microsoft.EntityFrameworkCore.InMemory (I have not tested it with SqlServer)
Target framework: 2.2.301
Operating system: Windows 10 Pro
IDE: Visual Studio 2019 16.1.6

**Update: corrected code snippets to include DbSet "Customers".

**Comment by smitpatel** [comment] 2019-10-21 20:35
@baloodevil - Try EF Core 3.0 if you haven't. The query pipeline has gone through significant changes in 3.0 and this issue may have already been fixed. If the issue still persist in 3.0 please share a small repro code demonstrating the issue. In your queries you are using `context` variable, generally which refers to DbContext but certainly query operators cannot be applied to it.

**Comment by ajcvickers** [comment] 2019-10-28 16:33
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:51 UTC
Labels: closed-could-not-reproduce, customer-reported
