### ISSUE TITLE
No support for .Net Frameork

### ISSUE THREAD

**Issue by lorinkundert** [dotnet/efcore#18736] opened 2019-11-04 04:05 UTC
So move to a modern framework, ok, Linux it is

**Comment by ajcvickers** [comment] 2019-11-04 17:51
Linux is a good choice for .NET Core.

**Comment by lorinkundert** [comment] 2019-11-05 03:50
By dropping support for .NET Framework we lose all of our 3rd party controls and that raises the pain point to where we can replace Windows desktops with Linux

**Comment by AndriySvyryd** [comment] 2019-11-05 04:33
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/18141

**Closed** 2022-10-16 14:54 UTC
Labels: closed-no-further-action, customer-reported
