### ISSUE TITLE
SQLite cannot apply aggregate operator 'Sum' on expressions of type 'decimal'. 

### ISSUE THREAD

**Issue by suatsuphi** [dotnet/efcore#29314] opened 2022-10-10 20:39 UTC
Hi,

I get this error that SQLite cannot apply aggregate operator 'Sum' on expressions of type 'decimal'. Convert the values to a supported type, or use LINQ to Objects to aggregate the results on the client side.

I searhed it. I think it can be override using sqlitefunction. Cold you help about it. I found some example from Microsoft Learn 

https://learn.microsoft.com/tr-tr/dotnet/standard/data/sqlite/user-defined-functions

But there is no example about SUM operator

```
connection.CreateFunction(
    "volume",
    (double radius, double height)
        => Math.PI * Math.Pow(radius, 2) * height);

```
and this example exists
```

connection.CreateFunction(
    "regexp",
    (string pattern, string input)
        => Regex.IsMatch(input, pattern));

```

and this example exists
```

connection.CreateAggregate(
    "stdev",

    // A tuple to maintain context between rows
    (Count: 0, Sum: 0.0, SumOfSquares: 0.0),

    // This is called for each row
    ((int Count, double Sum, double SumOfSquares) context, double value) =>
    {
        context.Count++;
        context.Sum += value;
        context.SumOfSquares += value * value;

        return context;
    },

    // This is called to get the final result
    context =>
    {
        var variance = context.SumOfSquares - context.Sum * context.Sum / context.Count;

        return Math.Sqrt(variance / context.Count);
    });

```

Is it possible to write something like this for the sum operator?

=======================================

```
[SqliteFunctionAttribute(Name = "SUM", Arguments = 1, FuncType = FunctionType.Aggregate)]
    class SqliteSum : SqliteFunction {
        public override void Step(object[] args, int stepNumber, ref object contextData) {
            if (args.Length < 1 || args[0] == null || args[0] == DBNull.Value)
                return;
            try {
                decimal d = Math.Round(Convert.ToDecimal(args[0]), 4);
                if (contextData != null) d += (Decimal)contextData;
                contextData = d;
            } catch (Exception ex) {
                WebServer.Log("Exception: {0}", ex);
            }
        }

        public override object Final(object contextData) {
            return contextData;
        }
    }
```

**Comment by suatsuphi** [comment] 2022-10-11 17:55
all sum functions as below

```

public static Task<decimal> SumAsync(
    this IQueryable<decimal> source,
    CancellationToken cancellationToken = default)
{
    Check.NotNull(source, nameof(source));

    return ExecuteAsync<decimal, Task<decimal>>(QueryableMethods.GetSumWithoutSelector(typeof(decimal)), source, cancellationToken);
}

public static Task<decimal?> SumAsync(
    this IQueryable<decimal?> source,
    CancellationToken cancellationToken = default)
{
    Check.NotNull(source, nameof(source));

    return ExecuteAsync<decimal?, Task<decimal?>>(
        QueryableMethods.GetSumWithoutSelector(typeof(decimal?)), source, cancellationToken);
}


//
public static Task<decimal> SumAsync<TSource>(
    this IQueryable<TSource> source,
    Expression<Func<TSource, decimal>> selector,
    CancellationToken cancellationToken = default)
{
    Check.NotNull(source, nameof(source));
    Check.NotNull(selector, nameof(selector));

    return ExecuteAsync<TSource, Task<decimal>>(
        QueryableMethods.GetSumWithSelector(typeof(decimal)), source, selector, cancellationToken);
}
//
public static Task<decimal?> SumAsync<TSource>(
    this IQueryable<TSource> source,
    Expression<Func<TSource, decimal?>> selector,
    CancellationToken cancellationToken = default)
{
    Check.NotNull(source, nameof(source));
    Check.NotNull(selector, nameof(selector));

    return ExecuteAsync<TSource, Task<decimal?>>(
        QueryableMethods.GetSumWithSelector(typeof(decimal?)), source, selector, cancellationToken);
}

//////////////////////////////////////////////////////////// 

//
public static decimal Sum<TSource>(this IEnumerable<TSource> source, Func<TSource, decimal> selector)
{
    if (source == null)
    {
        ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
    }

    if (selector == null)
    {
        ThrowHelper.ThrowArgumentNullException(ExceptionArgument.selector);
    }

    decimal sum = 0;
    foreach (TSource item in source)
    {
        sum += selector(item);
    }

    return sum;
}

public static decimal? Sum<TSource>(this IEnumerable<TSource> source, Func<TSource, decimal?> selector)
{
    if (source == null)
    {
        ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
    }

    if (selector == null)
    {
        ThrowHelper.ThrowArgumentNullException(ExceptionArgument.selector);
    }

    decimal sum = 0;
    foreach (TSource item in source)
    {
        decimal? v = selector(item);
        if (v != null)
        {
            sum += v.GetValueOrDefault();
        }
    }

    return sum;
}


//
public static decimal Sum(this IEnumerable<decimal> source)
{
    if (source == null)
    {
        ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
    }

    decimal sum = 0;
    foreach (decimal v in source)
    {
        sum += v;
    }

    return sum;
}

public static decimal? Sum(this IEnumerable<decimal?> source)
{
    if (source == null)
    {
        ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
    }

    decimal sum = 0;
    foreach (decimal? v in source)
    {
        if (v != null)
        {
            sum += v.GetValueOrDefault();
        }
    }

    return sum;
}
```

**Comment by ajcvickers** [comment] 2022-10-13 09:43
Duplicate of #19635.

**Closed by ajcvickers** 2022-10-13 09:43 UTC
Labels: customer-reported
