### ISSUE TITLE
Ability to cascade delete immediately (rather than on SaveChanges)

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#4290] opened 2016-01-12 18:27 UTC
This could be useful for data binding scenarios etc.

There are a few ways this could be implemented:
- An `ApplyCascadeDeletes()` API on `ChangeTracker`
- A new `CascadeImmediately` value in the `CascadeBehavior` enum
- A context wide setting for when cascade deletes are processed (on delete or on save)

**Comment by ajcvickers** [comment] 2018-02-26 21:56
Closing as duplicate of #10114 since that issue has more details.

**Closed** 2022-10-16 09:24 UTC
