### ISSUE TITLE
Sqlite with HasDefaultSchema: no such table dbo.xyz 

### ISSUE THREAD

**Issue by xaviergxf** [dotnet/efcore#10476] opened 2017-12-04 17:12 UTC
When configuring the dbcontext with hasDefaultSchema should work correctly with Sqlite and SqlServer, but instead i have the following error:

no such table dbo.xyz 

```
Exception message: SQLite Error 1: 'no such table: dbo.Languages'.
Stack trace:
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at R.Globalization.LanguageService`1.AddOrUpdateDefaultLanguage()
```

### Further technical details
EF Core version: 2.0
Database Provider: Sqlite
Operating system: Win 7 x64
IDE: Visual Studio 2017 15.4.5

**Comment by bricelam** [comment] 2017-12-04 17:56
Possibly a duplicate of #9560, but I didn't think we regressed until after 2.0.x

**Comment by ajcvickers** [comment] 2017-12-04 21:03
Closing this as a duplicate of #9560. 

@xaviergxf Can you test with the nightly feed (See https://github.com/aspnet/EntityFrameworkCore) and check that the issue is now fixed? If it is not, please request that this issue is re-opened and post a runnable project/solution or full code listing that reproduces the issue.

**Comment by xaviergxf** [comment] 2017-12-05 09:01
@ajcvickers  it works fine using the nightly feed. Thanks

**Comment by ajcvickers** [comment] 2017-12-05 16:31
@xaviergxf Thanks for testing!

**Closed** 2022-10-16 12:01 UTC
