### ISSUE TITLE
update-database -verbose

### ISSUE THREAD

**Issue by dvdobrovolskiy** [dotnet/efcore#7168] opened 2016-12-01 00:23 UTC
update-database -verbose
and 
add-migration -verbose

produces "Invalid JSON primitive: ."

**Comment by dvdobrovolskiy** [comment] 2016-12-01 00:43
Tried to ignore it
PM> add-migration -ErrorAction:Continue
cmdlet Add-Migration at command pipeline position 1
Supply values for the following parameters:
Name: x
ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\dima\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.1.0-preview4-final\tools\EntityFrameworkCore.psm1:947 char:52
+     $projectInfo = Get-Content $projectFile -Raw | ConvertFrom-Json
+                                                    ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
 
Get-Member : You must specify an object for the Get-Member cmdlet.
At C:\Users\dima\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.1.0-preview4-final\tools\EntityFrameworkCore.psm1:949 char:45
+ ... $projectInfo.frameworks | Get-Member -MemberType NoteProperty | %{ $_ ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
 
Cannot index into a null array.
At C:\Users\dima\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.1.0-preview4-final\tools\EntityFrameworkCore.psm1:955 char:12
+     return $frameworks[0]
+            ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\dima\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.1.0-preview4-final\tools\EntityFrameworkCore.psm1:947 char:52
+     $projectInfo = Get-Content $projectFile -Raw | ConvertFrom-Json
+                                                    ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
 
Get-Member : You must specify an object for the Get-Member cmdlet.
At C:\Users\dima\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.1.0-preview4-final\tools\EntityFrameworkCore.psm1:949 char:45
+ ... $projectInfo.frameworks | Get-Member -MemberType NoteProperty | %{ $_ ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
 
Cannot index into a null array.
At C:\Users\dima\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.1.0-preview4-final\tools\EntityFrameworkCore.psm1:955 char:12
+     return $frameworks[0]
+            ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\dima\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.1.0-preview4-final\tools\EntityFrameworkCore.psm1:947 char:52
+     $projectInfo = Get-Content $projectFile -Raw | ConvertFrom-Json
+                                                    ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
 
Get-Member : You must specify an object for the Get-Member cmdlet.
At C:\Users\dima\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.1.0-preview4-final\tools\EntityFrameworkCore.psm1:949 char:45
+ ... $projectInfo.frameworks | Get-Member -MemberType NoteProperty | %{ $_ ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
 
Cannot index into a null array.
At C:\Users\dima\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.1.0-preview4-final\tools\EntityFrameworkCore.psm1:955 char:12
+     return $frameworks[0]
+            ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\dima\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.1.0-preview4-final\tools\EntityFrameworkCore.psm1:947 char:52
+     $projectInfo = Get-Content $projectFile -Raw | ConvertFrom-Json
+                                                    ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
 
Get-Member : You must specify an object for the Get-Member cmdlet.
At C:\Users\dima\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.1.0-preview4-final\tools\EntityFrameworkCore.psm1:949 char:45
+ ... $projectInfo.frameworks | Get-Member -MemberType NoteProperty | %{ $_ ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
 
Cannot index into a null array.
At C:\Users\dima\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.1.0-preview4-final\tools\EntityFrameworkCore.psm1:955 char:12
+     return $frameworks[0]
+            ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Startup project 'src\Dispatcher' targets framework ''. The Entity Framework Core Package Manager Console Tools don't support this framework.
PM>

**Comment by rowanmiller** [comment] 2016-12-07 23:03
Probably a duplicate of https://github.com/aspnet/EntityFramework/issues/7197. Could you post your project.json file?

**Comment by dvdobrovolskiy** [comment] 2016-12-08 12:59
Looks like it
had // in project.json

Killed it and now I have [#7077](https://github.com/aspnet/EntityFramework/issues/7077)

The specified deps.json [C:\Users\dima\OneDrive\?????????\Visual Studio 2015\Projects\Dispatcher\src\Dispatcher\m:\build\Dispatcher\bin\Debug\netcoreapp1.0\Dispatcher.deps.json] does not exist
Process finished with non-zero exit code

Meanwhile migrations works perfectly from CMD

**Comment by rowanmiller** [comment] 2016-12-08 17:54
@dvdobrovolskiy thanks for confirming. The PowerShell commands use the PowerShell JSON parser to get some info from project.json that we can't get from the VS project system for xproj/project.json projects. One of the big upsides of .NET Core adopting MSBuild is that all this goes away by the time we release a stable version of the tool - not to in any way minimize the pain of trying to get things working at the moment.

**Closed** 2022-10-16 10:45 UTC
