### ISSUE TITLE
Microservices Shared Database Pattern with EF core

### ISSUE THREAD

**Issue by Martinn2** [dotnet/efcore#25370] opened 2021-07-30 14:49 UTC
I am trying to implement Microservices Shared Database Pattern (https://microservices.io/patterns/data/shared-database.html) with EF core.

I have these requirements for my services:

* Every service creates some tables (ideally in it´s own database)
* Every service can query from all tables created by any service
* Use code first and migrations to create databases
* Configure foreign keys across services tables using EF core.
* I want to be able to have navigation properties on any model

### Sample

Imagine two simple microservices, one is responsible for managing user data and another for user address. Models look like this:

UserMicroservice:
```C#
    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
```
UserAddressMicroservice:
```C#
    public class UserAddress
    {
        public int Id { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public int UserId { get; set; }
        public User User { get; set; }
    }
```
Every microservice has it´s own db context

### Problems:

When I migrate UserMicroservice, Users table is created. But when I migrate UserAddressMicroservice, User table is created again because it is navigation property of UserAddress. 

I am also missing Address navigation property on my User model. Ideally I would like to extend user (UserWithAddress in github example)  in UserAddressMicroservice and add Address navigation property there (but again, without creating user table). 

### What I´ve tried:

* Add User to UserAddressMicroservice´s DbContext and Ignore it, but with that I am not able to query for User.

### My thoughts:

To solve it we need a way to mark model as "_Query Only_" while still being for it to act as principal table.

Sample code can be found here: https://github.com/Martinn2/EfMicroservicesSharedDb

Is there a way to achieve this ?
### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019)

**Comment by ajcvickers** [comment] 2021-08-06 13:16
@Martinn2 I'm not sure you will be able to achieve all you want. Taking your requirements one by one:

> I want to be able to have navigation properties on any model

This requires that you have a single model.

> Every service creates some tables (ideally in it´s own database)

An EF Core model cannot span multiple databases. You can have different DbContext instances exclude parts of the model when generating migrations--see https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#excluding-parts-of-your-model. But all parts of a given model must be created by some process, and they must all be in the same database.

> Every service can query from all tables created by any service

This will work as long as the tables are mapped in the model used by the service.

> Use code first and migrations to create databases

Yes.

> Configure foreign keys across services tables using EF core.

You can have an FK mapped in multiple models, but if you want to use navigations, then they need to be in the same model.

**Comment by Martinn2** [comment] 2021-08-08 20:33
@ajcvickers Thanks a lot for reply. My solution was to remove navigations where needed and use Query Syntax instead,

The only thing that I would like to improve is access across databases. Any changes to see the feature in the future ?

Maybe somthing like this:
```C#
        [Datatase("db1")]
        public DbSet<UserAddress> Address => Set<UserAddress>();
        [Datatase("db2")]
        public DbSet<UserWithAddress> Users => Set<UserWithAddress>();
```

**Comment by roji** [comment] 2021-08-08 21:20
@Martinn2 a DbContext currently has a single connection, which corresponds to a single database, so that's unlikely to be possible.

Stepping back, what exactly would that allow you over having two separate DbContext types (one for each database), given that you wouldn't be able to translate a single SQL query that encompasses both databases? In other words, with two DbContext types, you can still have a single LINQ query which performs cross-database operations client-side (e.g. joins).

**Comment by Martinn2** [comment] 2021-08-09 07:32
It would allow me two things:

1. Creating foreign keys across databases (this is possible in MySQL which I am using) 
2. You say that I can have single cross context query, but I am getting exception:
```C#
            var addressesContext = new UserAddressDbContext();
            var usersContext = new UserDbContext();

            var query = from user in usersContext.Users
                join address in addressesContext.Address on user.Id equals address.UserId
                into res1
                from userWithAddress in res1.DefaultIfEmpty()
                select new
                {
                    User = user
                };
```

![image](https://user-images.githubusercontent.com/45663203/128672358-815152a9-521f-45dd-8925-b442b2d6a86f.png)

**Comment by roji** [comment] 2021-08-09 07:45
@Martin2 please disregard my answer above, I was unaware that SQL Server supported specifying multiple databases in the same query. In that case, this issue seems to be largely a dupe of https://github.com/dotnet/efcore/issues/4019, see especially https://github.com/dotnet/efcore/issues/4019#issuecomment-483417974 for an approach to handle this via SQL search-and-replace (in newer versions of EF Core you would do this via a [database interceptor](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#database-interception)).

Re creating foreign keys across database is something you can do today by using [raw SQL](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#adding-raw-sql) in your migrations; it isn't a perfect solution, but it works.

**Comment by Martinn2** [comment] 2021-08-09 08:22
Thank you. In that case I can close the issue. I will probably go with one DB approach for now to make it easier and to have cross provider support (I found out that SQL server does not support Cross-database foreign key references at all)

**Comment by ajcvickers** [comment] 2021-08-09 09:01
@Martinn2 Cross-database support is tracked by #6089.

**Closed** 2022-10-16 19:41 UTC
Labels: closed-no-further-action, customer-reported
