### ISSUE TITLE
ConcurrencyDetector erroneously detecting re-entry (backport request)

### ISSUE THREAD

**Issue by baudday** [dotnet/efcore#19354] opened 2019-12-18 17:39 UTC
We're having issues where we're getting an `InvalidOperationException` thrown from `ConcurrencyDetector` even though we've thoroughly scoured our code to ensure we can't possibly have concurrent access to the DbContext. In troubleshooting, we've seen significant changes in `ConcurrencyDetector` since the version that we're on (2.1), and we're suspicious that perhaps we're encountering a bug that is fixed in 3.0 but not 2.1. Is it possible to backport those changes to `ConcurrencyDetector` to 2.1? If not, is there any guidance for us as to what we might be able to do as a workaround? We're not ready for upgrading quite yet since we're also on ASP.Net Core 2.1 and we can't upgrade EF Core independently.

### Further technical details

EF Core version: 2.1
Database provider: Npgsql.EntityFrameworkCore 2.1.1
Target framework: .Net Core 2.1
Operating system: Linux

**Comment by ajcvickers** [comment] 2019-12-18 20:28
@baudday Can you post the full stack trace?

**Comment by baudday** [comment] 2019-12-18 20:54
```
Microsoft.EntityFrameworkCore.Update[10000]
An exception occurred in the database while saving changes for context type 'Prodigy.Lib.Enrollment.DataContexts.EnrollmentContext'.
    System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
    at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
    System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
    at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

**Comment by ajcvickers** [comment] 2019-12-18 20:57
@baudday Are you sure that all async calls are being awaited before a new one is started?

**Comment by baudday** [comment] 2019-12-18 20:59
Yes, we have combed through the code extensively and all async calls are being awaited

**Comment by ajcvickers** [comment] 2019-12-18 21:29
@baudday It is not impossible that we would patch 2.1 for a bad bug in the concurrency detector. However, we would have to be pretty sure that the value/risk trade-off makes sense, which means understanding exactly what you are hitting. For that we will need to reproduce what you are seeing, which almost certainly means we're going to need a small, runnable project that reproduces the behavior you are seeing.

**Comment by ajcvickers** [comment] 2020-01-02 17:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:02 UTC
Labels: closed-could-not-reproduce, customer-reported
