### ISSUE TITLE
Migration add Issue

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#1567] opened 2015-02-07 08:43 UTC
Hi Guys,

I encounter this error when i apply
k ef migration add "v.0.1" during generate the Migration.cs it error

public partial class v.0.1 : Migration
{

**Comment by bricelam** [comment] 2015-02-07 17:24
Dupe of #1067?

**Comment by rowanmiller** [comment] 2015-02-11 19:22
Should now be fixed

**Closed** 2022-10-16 08:51 UTC
