### ISSUE TITLE
Not null sql column with -1 default value

### ISSUE THREAD

**Issue by Dimigergo** [dotnet/efcore#28094] opened 2022-05-25 06:33 UTC
I have this small repo:
[EFCoreColumnDefault.zip](https://github.com/dotnet/efcore/files/8768497/EFCoreColumnDefault.zip)

In the .sql file we have a table with an IntCmn, and IntCmnDef integer column. Both are the same, but the IntCmnDef column has a defaul value with -1.

In the repo we have 3 insert, but the last two insert are the same result, with IntCmnDef column value -1.
The last inserted value should be 0, because the 0 value is not the default of the column, but a valid number.

I see, that it is complicated to determine if the user set the 0 value of the property or the C# integer default value is that, but in this case, there are errors when use a column with default value which is different from the integer default value.

EF Core Power Tools 2.5.982
EF Core 5.0.16
Visual Studio 2022 (17.1.6)

**Comment by ajcvickers** [comment] 2022-05-27 09:48
Duplicate of #701.

**Closed** 2022-10-16 20:35 UTC
Labels: closed-duplicate, customer-reported
