### ISSUE TITLE
Migrations with renamings fail

### ISSUE THREAD

**Issue by MadMonkey87** [dotnet/efcore#8927] opened 2017-06-21 19:53 UTC
Hi,

I've noticed that when using migrations that include the renaming of a column (or maybe a table) this will lead to the following exception during execution:

> Either the parameter @objname is ambiguous or the claimed @objtype (COLUMN) is wrong.

### Steps to reproduce

I have a class "Test" that is mapped to the Table "dbo.Test" using Fluent Api:
`builder.Entity<Test>().ToTable("Test");`

Now I've renamed the property "OldTitle" of my Test class to "NewTitle" and created a migration. This migration will generate the following sql script:

`EXEC sp_rename N'Test.OldTitle', N'NewTitle', N'COLUMN';

GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20170621193943_test', N'1.1.2');

GO

`

So the problems seems to be that the generated sql statements are missing the db scheme name. Even if I use something like 'builder.HasDefaultSchema("MySchemeName");' I get the same sql statements and therefore the same error.

So is this all about a EF missing to add the scheme name?

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment] 2017-06-23 18:13
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2017-06-30 16:11
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:09 UTC
Labels: closed-could-not-reproduce
