### ISSUE TITLE
upgrading to 2.0.0 broke connections to sqlite dbs with fts tables

### ISSUE THREAD

**Issue by Trolldemorted** [dotnet/efcore#10107] opened 2017-10-17 23:26 UTC
While using v1.1.2 we could use sqlite's fts5 tables by editing the migrations and sending raw sql.

After upgrading to 2.0.0, ef core can no longer open the database:
```
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.EntityFrameworkCore.dll
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in System.Private.CoreLib.dll
SQLite Error 1: 'no such module: fts5'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Signal_Windows.Storage.SignalDBContext.GetAllContactsLocked()
   at Signal_Windows.ViewModels.MainPageViewModel.<<Init>b__41_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Signal_Windows.ViewModels.MainPageViewModel.<Init>d__41.MoveNext()
```

Is the 2.0 release backed by an sqlite version without the fts5 module enabled?

### Further technical details
EF Core version:  v2.0.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: W10 Pro N x64
IDE: Visual Studio 2017 15.4

**Comment by bricelam** [comment] 2017-10-18 17:36
Duplicate of ericsink/SQLitePCL.raw#171

**Comment by bricelam** [comment] 2017-10-18 17:43
`SQLitePCLRaw.bundle_green` includes FTS4.

You should be able to go back to the previously included version of SQLite by using these packages:
* Microsoft.EntityFrameworkCore.Sqlite.Core
* SQLitePCLRaw.provider.custom_sqlite3.netstandard11
* SQLite

And calling this during app start:

``` c#
SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_custom_sqlite3());
```

**Comment by The-MAZZTer** [comment] 2017-12-20 21:17
@bricelam can you provide more details on this workaround? I am unable to get it work as I can't find or build a suitable sqlite3 dll and your workaround doesn't specify where to get one. If I stick to your steps the  SQLitePCL.SQLite3Provider_custom_sqlite3 tries to find custom_sqlite3.dll but fails as it was never present.

I copied the sqlite3.dll installed by the SQLite package to my application folder as custom_sqlite3.dll, that fixed that error but I am still getting "no such module: fts5".

I tried to build my own SQLite3 with FTS5 enabled using the instructions at https://sqlite.org/howtocompile.html and https://sqlite.org/fts5.html using VS2017, but I still receive the error "no such module: fts5" even with FTS5 enabled in the compiler defines. Messing with the sqlite3 source code a bit I am not confident the code path that loads FTS5 is ever getting called but I do not know anything about how sqlite3 works so I can't be sure.

Alternatively I also tried to downgrade to .NET Core 1.1 and 1.1.x of any 2.0.x packages I was using (AspNetCore, EFCore, etc), however that only seems to give me FTS5 support on Windows. I still get "no such module: fts5" on CentOS 7.

If you could clarify how to implement your workaround it would be much appreciated.

**Comment by bricelam** [comment] 2017-12-20 23:51
Hmm, what if you use the `SQLitePCLRaw.provider.sqlite3.netstandard11` instead?

**Comment by The-MAZZTer** [comment] 2017-12-21 01:52
I will try that. One of the issues I had was the SQLitePCLRaw.provider.* package tells you to use a SQLitePCLRaw.lib.* package (which is where I assume the sqlite3.dll is supposed to come from) but there is none for custom_sqlite3 (since you are expected to provide your own custom sqlite3!)

Unfortunately I was doing this for a work project and I am out of time to try and resolve my  issue. The workaround I had to settle on was using System.Data.SQLite which makes the project Windows-only. I am not sure when I will have a chance to revisit (we do want Linux compatibility though). Thanks for the reply.

I would encourage the Microsoft.Data.Sqlite and EFCore devs to compile in FTS5 support in a future release (also be sure to have feature parity between platforms... as I said above in Microsoft.Data.Sqlite 1.1.0 it seems to have fts5 enabled on Windows but not Linux! Though I am not 100% sure, I'd have to go back and check).

**Comment by bricelam** [comment] 2018-03-28 18:07
It's back! Update your SQLitePCL.raw package to version 1.1.10.
``` xml
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.0.2" />
<PackageReference Include="SQLitePCLRaw.bundle_green" Verison="1.1.10" />
```

**Comment by The-MAZZTer** [comment] 2018-04-09 17:56
I can confirm that including that version of SQLitePCLRaw.bundle_green allows me to use FTS5 in Microsoft.Data.Sqlite, at least on Windows (didn't test other platforms yet). TFTI!

**Closed** 2022-10-16 11:54 UTC
Labels: closed-external
