### ISSUE TITLE
Change tracking of entity, selected with conditional expression

### ISSUE THREAD

**Issue by sm-g** [dotnet/efcore#7565] opened 2017-02-07 06:52 UTC
Why ChangeTracker ignores changes of entity seleted this way?

```
var withUser = true;
var result = (from connection in _db.Connections
	 join user in _db.Users  on connection.UserId equals user.Id
	  select new
	  {
		  Connection = connection,
		  User = withUser ? user : null
	  })
	.FirstOrDefault();
			
result.User.Name = "123";
//_db.ChangeTracker.HasChanges() == false
result.Connection.Name = "123";
//_db.ChangeTracker.HasChanges() == true
```
### Further technical details
Database Provider: ("Pomelo.EntityFrameworkCore.MySql": "1.1.0")

**Comment by rowanmiller** [comment] 2017-02-13 19:06
We think there is already an issue tracking this. @anpete to find the issue and close this as a dupe

**Comment by smitpatel** [comment] 2017-08-30 04:42
Duplicate of #5008

**Closed** 2022-10-16 10:52 UTC
