### ISSUE TITLE
EF5 get hierarchy data self-reference by predicate does not work right.

### ISSUE THREAD

**Issue by FakeOwner** [dotnet/efcore#24628] opened 2021-04-10 11:38 UTC
I want to retrieve self-reference data by this method : 

`        public IEnumerable<TEntity> GetAllHierarchy(string navigationPropertyPath,
            Expression<Func<TEntity, bool>> predicate)
        {
            return _entities.Include(navigationPropertyPath).Where(predicate);
        }`

When I use `GetAllHierarchy("Children",  x => x.ParenetId == null)` data retrived by 2 level Children.
When I call the method without predicate data successfully loaded but I don't need data with ParentId

This method worked in the EF6 well but in EF5 not working right.

**Comment by ajcvickers** [comment] 2021-04-12 15:55
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by FakeOwner** [comment] 2021-04-17 06:45
Data in database table WindowCategory
Id     ParentId     Title
1           Null          T1
2           Null          T2
3           Null          T3
4             1             T1-1
5             4             T1-1-1
6             5             T1-1-1-1
7             6             T1-1-1-1-1


Data access layer : 

`        
public IEnumerable<TEntity> GetAllHierarchy(string navigationPropertyPath, Expression<Func<TEntity, bool>> predicate)
{
      return _entities.Include(navigationPropertyPath).Where(predicate);
}

public IEnumerable<TEntity> GetAllHierarchy(string navigationPropertyPath)
{
      return _entities.Include(navigationPropertyPath);
}

`

Service layer : 

`var wcResult= _dataAccessLayer.GetAllHierarchy(nameof(WindowCategory.Children), x => x.ParentId == null);`

When I pass `x => x.Parent == null` just level 1 and level 2 children loaded.


Output :  (wcResult count is 3)
wcResult contain : 
Id     ParentId     Title
1           Null          T1
2           Null          T2
3           Null          T3
4             1             T1-1 // this item is in T1 property Children.


But when I use ``var wcResult= _dataAccessLayer.GetAllHierarchy(nameof(WindowCategory.Children));``

Data loaded successfully but I do not need data with ParentId != null

Output :  (wcResult count is 7)
Id     ParentId     Title
1           Null          T1
2           Null          T2
3           Null          T3
4             1             T1-1            //  this item is in T1 property Children. It is also on the wcResult list 
5             4             T1-1-1        //  this item is in T1-1 property Children. It is also on the wcResult list 
6             5             T1-1-1-1     //  this item is in T1-1-1 property Children. It is also on the wcResult list 
7             6             T1-1-1-1-1 //  this item is in T1-1-1-1 property Children. It is also on the wcResult list

**Comment by ajcvickers** [comment] 2021-04-19 15:20
@FakeOwner What we really need here is to be able to _run your code and reproduce the error_. With snippets like you have shown above this is very difficult because we have to guess at so much. Can you put these snippets into a runnable console application that demonstrates the bad behavior. This way we can reproduce what you are seeing and investigate.

**Comment by smitpatel** [comment] 2021-04-19 21:36
@FakeOwner - `Include` API only loads exactly one level of navigation property. For tracking queries, EF Core performs identity resolution and fix-up navigations between loaded data. Because of this you are seeing above results. EF Core is not loading hierarchy. If you want to load Children collection n-level deep, you have to use `Include/ThenInclude` n times.

**Comment by ajcvickers** [comment] 2021-04-26 15:45
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:31 UTC
Labels: closed-could-not-reproduce, customer-reported
