### ISSUE TITLE
Could not load type 'System.IO.File' from assembly 'System.IO.FileSystem

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#6831] opened 2016-10-21 14:05 UTC
### Steps to reproduce

Create .net core project - project.json shown below
### The issue

Open developer command prompt type `dotnet ef`.  Program crashes immediately with error message below.

Troubleshooting I've done:
I deleted nugget cache (entire directories) per these posts:
http://stackoverflow.com/questions/30933277/how-to-clear-nuget-package-cache-using-command-line
https://github.com/aspnet/EntityFramework/issues/5886

```
c:\Git\ProjectManager\ProjectManager\src\ProjectManager.API>dotnet ef
    Project ProjectManager.Core (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
    Project ProjectManager.API (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
                         _/\__
                   ---==/    \\
             ___  ___   |.    \|\
            | __|| __|  |  )   \\\
            | _| | _|   \_/ |  //|\\
            |___||_|       /   \\\/\\
    Unhandled Exception: System.TypeLoadException: Could not load type 'System.IO.File' from assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
       at System.Diagnostics.StackTraceSymbols.GetReader(String assemblyPath, IntPtr loadedPeAddress, Int32 loadedPeSize, IntPtr inMemoryPdbAddress, Int32 inMemoryPdbSize)
       at System.Diagnostics.StackTraceSymbols.GetSourceLineInfo(String assemblyPath, IntPtr loadedPeAddress, Int32 loadedPeSize, IntPtr inMemoryPdbAddress, Int32 inMemoryPdbSize, Int32 methodToken, Int32 ilOffset, String& sourceFile, Int32& sourceLine, Int32& sourceColumn)
       at System.Diagnostics.StackFrameHelper.InitializeSourceInfo(Int32 iSkip, Boolean fNeedFileInfo, Exception exception)
       at System.Diagnostics.StackTrace.CaptureStackTrace(Int32 iSkip, Boolean fNeedFileInfo, Thread targetThread, Exception e)
       at System.Diagnostics.StackTrace..ctor(Exception e, Boolean fNeedFileInfo)
       at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
       at System.Exception.GetStackTrace(Boolean needFileInfo)
       at System.Exception.ToString(Boolean needFileLineInfo, Boolean needMessage)
       at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
```
### Further technical details

EF Core version: see project.json below
Operating system: windows 10
Visual Studio version: 2015.3
dotnet --version: 1.0.0-preview2-003131

Other details about my project setup:

```
{
      "dependencies": {
        "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
        "Microsoft.Extensions.Configuration.Json": "1.0.0",
        "Microsoft.Extensions.Logging": "1.0.0",
        "Microsoft.Extensions.Logging.Console": "1.0.0",
        "Microsoft.Extensions.Logging.Debug": "1.0.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
        "Autofac": "4.1.1",
        "Microsoft.AspNetCore.Mvc": "1.0.1",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
        "Microsoft.NETCore.App": {
          "version": "1.0.1"
        },
        "ProjectManager.Core": "1.0.0-*",
        "Microsoft.EntityFrameworkCore": "1.0.1",
        "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
        "Microsoft.EntityFrameworkCore.Tools.Cli": "1.0.0-preview1-final",
        "Microsoft.EntityFrameworkCore.Tools.Core": "1.0.0-rc2-final"
      },

      "tools": {
        "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
      },

      "runtimes": {
        "win10-x64": { } 
      },

      "frameworks": {
        "netcoreapp1.0": {
          "imports": [
            "dotnet5.6",
            "portable-net45+win8",
            "net462"
          ]
        }
      },

      "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
      },

      "runtimeOptions": {
        "configProperties": {
          "System.GC.Server": true
        }
      },

      "publishOptions": {
        "include": [
          "wwwroot",
          "Views",
          "Areas/**/Views",
          "appsettings.json",
          "web.config"
        ]
      },

      "scripts": {
        "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
      }
    }

```

**Comment by bricelam** [comment] 2017-01-10 17:18
@sam-wheat Does this repro using the latest bits? (See #7358)

**Comment by bricelam** [comment] 2017-01-24 19:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Comment by derf26** [comment] 2017-01-29 11:45
I have this same issue. I've posted a question on [StackOverflow ](http://stackoverflow.com/questions/41915522/asp-net-core-1-1-runs-fine-locally-but-when-publishing-to-azure-says-an-error-o)but it feels more and more like a bug with .NET Core as I've spent several hours trying different .nuget package combinations.

Basically I can run everything fine in debug mode, but when I publish to an Azure Web App, I get this error:
`Application startup exception: System.TypeLoadException: Could not load type 'System.IO.File' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.`

The specific line of code causing this issue is:
`services.AddMvc();`

**Closed** 2022-10-16 10:39 UTC
Labels: closed-could-not-reproduce
