### ISSUE TITLE
SaveChanges causes InvalidCastException when inserting row into a table with a date type column

### ISSUE THREAD

**Issue by larlew** [dotnet/efcore#22476] opened 2020-09-10 15:10 UTC
We have a sqlServer table with a date type column.  The dbContext.SaveChangesAsync throws an InvalidCastException inserting a record.  Note there is also an insert/update trigger on the UDF table. 

If I comment out this code in BaseDbContext for the date type column it succeeds with no error.
modelBuild.Entity<Udf>(entity => {
. . .
 //entity.Property(e => e.UdfdateValue)
                //    .HasColumnName("UDFDateValue")
                //    .HasColumnType("date");
. . .}
### Steps to reproduce

<!--
What steps can we follow to reproduce the issue?
simple code below

``` C#
// abbreviated code
using LookupValueDbContext db = _contextFactory.CreateEvaluationDbContext(schoolId);
Udf _newUdf = new Udf()
                                {
                                    SchoolId = schoolId,
                                    ParentId = _change.ParentId,
                                    UdfsetupId = _change.UdfSetupId,
                                    CreatedTime = System.DateTime.UtcNow,
                                    EditedTime = System.DateTime.UtcNow,
                                    DeletedTime = null,
                                    UdfdateValue = null
                                };
db.Entry(_newUdf).State = EntityState.Added;
await db.SaveChangesAsync();


public class LookupValueDbContext : LookupValueBaseDbContext
    {
        private readonly ShardMap _shardMap;
        private readonly int _shardingKey;
        private readonly string _baseConnectionString;

protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            System.Data.SqlClient.SqlConnection sqlConn = _shardMap.OpenConnectionForKey(
                               _shardingKey,
                               _baseConnectionString,
                               ConnectionOptions.Validate);
                      
            if (!optionsBuilder.IsConfigured)
                optionsBuilder.UseSqlServer(sqlConn);
        }
}
public partial class Udf
    {
        public int Udfid { get; set; }
        public short SchoolId { get; set; }
        public int ParentId { get; set; }
        public int UdfsetupId { get; set; }
        public int? UdfintValue { get; set; }
        public DateTime? UdfdateValue { get; set; }
        public string UdfvarcharValue { get; set; }
        public bool UdfbitValue { get; set; }
        public decimal? UdfdecimalValue { get; set; }
        public int? UdftypeId { get; set; }
        public int CreatedById { get; set; }
        public DateTime CreatedTime { get; set; }
        public int EditedById { get; set; }
        public DateTime EditedTime { get; set; }
        public int? DeletedById { get; set; }
        public DateTime? DeletedTime { get; set; }
        public byte[] RowId { get; set; }

        public virtual School School { get; set; }
        public virtual Udfsetup Udfsetup { get; set; }
        public virtual Udftype Udftype { get; set; }
    }
CREATE TABLE [dbo].[UDF](
	[UDFId] [int] IDENTITY(1,1) NOT NULL,
	[SchoolId] [smallint] NOT NULL,
	[ParentId] [int] NOT NULL,
	[UDFSetupId] [int] NOT NULL,
	[UDFIntValue] [int] NULL,
	[UDFDateValue] [date] NULL,
	[UDFVarcharValue] [varchar](4000) NULL,
	[UDFBitValue] [bit] NOT NULL,
	[UDFDecimalValue] [decimal](20, 4) NULL,
	[UDFTypeId] [int] NULL,
	[CreatedById] [int] NOT NULL,
	[CreatedTime] [datetime] NOT NULL,
	[EditedById] [int] NOT NULL,
	[EditedTime] [datetime] NOT NULL,
	[DeletedById] [int] NULL,
	[DeletedTime] [datetime] NULL,
	[RowId] [timestamp] NOT NULL,
	[SysStartTime] [datetime2](2) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEndTime] [datetime2](2) GENERATED ALWAYS AS ROW END NOT NULL,
 CONSTRAINT [PK_UDF_UDFId] PRIMARY KEY CLUSTERED 
(
	[UDFId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_UDF_ParentId_UDFSetupId_udftypeid] UNIQUE NONCLUSTERED 
(
	[ParentId] ASC,
	[UDFSetupId] ASC,
	[UDFTypeId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY],
	PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime])
) ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON ( HISTORY_TABLE = [dbo].[UDFAuditHistory] )
)
GO

ALTER TABLE [dbo].[UDF] ADD  CONSTRAINT [DF_UDF_UDFBitValue]  DEFAULT ((0)) FOR [UDFBitValue]
GO

ALTER TABLE [dbo].[UDF] ADD  CONSTRAINT [DF_UDF_CreatedTime]  DEFAULT (getdate()) FOR [CreatedTime]
GO

ALTER TABLE [dbo].[UDF] ADD  CONSTRAINT [DF_UDF_EditedTime]  DEFAULT (getdate()) FOR [EditedTime]
GO

ALTER TABLE [dbo].[UDF] ADD  CONSTRAINT [DF_UDF_SysStartTime]  DEFAULT (dateadd(second,(-1),sysutcdatetime())) FOR [SysStartTime]
GO

ALTER TABLE [dbo].[UDF] ADD  CONSTRAINT [DF_UDF_SysEndTime]  DEFAULT ('9999.12.31 23:59:59.99') FOR [SysEndTime]
GO

ALTER TABLE [dbo].[UDF]  WITH CHECK ADD  CONSTRAINT [FK_UDF_SchoolId] FOREIGN KEY([SchoolId])
REFERENCES [dbo].[School] ([SchoolID])
GO

ALTER TABLE [dbo].[UDF] CHECK CONSTRAINT [FK_UDF_SchoolId]
GO

ALTER TABLE [dbo].[UDF]  WITH CHECK ADD  CONSTRAINT [FK_UDF_UDFSetupId] FOREIGN KEY([UDFSetupId])
REFERENCES [dbo].[UDFSetup] ([UDFSetupId])
GO

ALTER TABLE [dbo].[UDF] CHECK CONSTRAINT [FK_UDF_UDFSetupId]
GO

ALTER TABLE [dbo].[UDF]  WITH CHECK ADD  CONSTRAINT [FK_UDF_UDFTypeId] FOREIGN KEY([UDFTypeId])
REFERENCES [dbo].[UDFType] ([UDFTypeId])
GO

ALTER TABLE [dbo].[UDF] CHECK CONSTRAINT [FK_UDF_UDFTypeId]
GO

Got Exceptions? Include both the message and the stack trace
{
  "error": {
    "code": "DbUpdateException",
    "message": "An error occurred while updating the entries. See the inner exception for details.",
    "userMessage": "Get Failed.",
    "target": "/api/v2/Schools/399/Udfs/Values",
    "stackTrace": "   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\r\n   at LSAC.LookupValue.DomainModel.Repositories.V2.EFLookupValueRepository.SaveUdfValuesAsync(Int16 schoolId, List`1 udfChanges, Int32 userId) in C:\\api\\Azure\\LSAC.LookupValue.ServiceFabric\\LSAC.LookupValue.DomainModel\\Repositories\\V2\\EFLookupValueRepository.cs:line 578\r\n   at LSAC.LookupValue.API.Controllers.V2.UdfsController.SaveUdfValues(Int16 schoolId, List`1 udfValues) in C:\\api\\Azure\\LSAC.LookupValue.ServiceFabric\\LSAC.LookupValue.API\\Controllers\\V2\\UdfsController.cs:line 108",
    "details": null,
    "innerErr": {
      "code": "System.InvalidCastException",
      "message": "Unable to cast object of type 'System.Data.SqlClient.SqlParameter' to type 'Microsoft.Data.SqlClient.SqlParameter'.",
      "target": "Microsoft.EntityFrameworkCore.SqlServer",
      "stackTrace": "   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDateTimeTypeMapping.ConfigureParameter(DbParameter parameter)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable)\r\n   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)\r\n   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)",
      "innerErr": null
    }
  }
}



### Further technical details

EF Core version: 3.1.8
Database: Azure SqlServer 12.0.2000.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer  (System.Data.SqlClient.SqlConnection)
Note:  Connection is opened via Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement  shardMap.OpenConnectionForKey()
Target framework: .NET Core 3.1
Operating system: Microsoft Windows 10 Enterprise
IDE:  Visual Studio 2019 16.7.1

**Comment by ajcvickers** [comment] 2020-09-11 15:44
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-09-21 15:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:40 UTC
Labels: closed-could-not-reproduce, customer-reported
