### ISSUE TITLE
Query: optimize translation of OfType - remove redundant discriminator predicate elements

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#16094] opened 2019-06-14 01:06 UTC
query:

```
ctx.Gears.OfType<Officer>()
```

generated sql:

```sql
SELECT [g].[Nickname], [g].[SquadId], [g].[AssignedCityName], [g].[CityOrBirthName], [g].[Discriminator], [g].[FullName], [g].[HasSoulPatch], [g].[LeaderNickname], [g].[LeaderSquadId], [g].[Rank]
FROM [Gears] AS [g]
WHERE [g].[Discriminator] IN (N'Gear', N'Officer') AND ([g].[Discriminator] = N'Officer')
```

should be:

```sql
SELECT [g].[Nickname], [g].[SquadId], [g].[AssignedCityName], [g].[CityOrBirthName], [g].[Discriminator], [g].[FullName], [g].[HasSoulPatch], [g].[LeaderNickname], [g].[LeaderSquadId], [g].[Rank]
FROM [Gears] AS [g]
WHERE [g].[Discriminator] = N'Officer'
```

**Comment by wgibbons1** [comment] 2019-08-11 11:40
I need to do the following but it is not working as reported by maumar above. Is this going to be fixed or am I doing something wrong?

`IEnumerable<AdminDivisionViewModel.Person> peopleWithAdminRights = await
                (from u in AppDbContext.Users
                 let hasRights = u.CdAdminRights.OfType<DivisionAdministrator>().Any(x => x.DivisionId == id)
                 let hasHigherTierRights = u.CdAdminRights.OfType<GroupAdministrator>().Any()
                 where hasRights || hasHigherTierRights
`
The SQL that is being generated is:
'WHERE [a0].[Discriminator] IN (1, 2, 4, 3)'
when it should be looking for just one of those values.

**Comment by ajcvickers** [comment] 2019-08-12 15:57
@wgibbons1 `OfType`, as defined by LINQ, means the given type _or any type that inherits from it_. Given this, it's likely the translation you are seeing is correct. If not, then please open a _new_ issue and include a small, runnable project/solution or complete code listing that demonstrates what you are seeing.

**Comment by smitpatel** [comment] 2020-03-16 19:38
Duplicate of #15808

**Closed** 2022-10-16 14:25 UTC
Labels: closed-duplicate
