### ISSUE TITLE
[Question] Is it possible to configure Table-Per-Hierarchy with a read-only discriminator?

### ISSUE THREAD

**Issue by YuKitsune** [dotnet/efcore#15530] opened 2019-04-30 02:17 UTC
### Question
I've got a DTO which should be stored in a database and also have the ability to be serialized to JSON.
I've developed a method allowing me to serialize and deserialize multiple different inheritors of an abstract class at once, which required me to add a discriminator to the base class (which just returns `GetType().FullName`).

It'd be great to be able to use this as a discriminator for the Database as well, rather than having two different discriminators in the same class.

Here's an example of what I've got:
```cs
[JsonConverter(typeof(BaseClassConverter))]
public abstract class MyBaseClass
{
...
public string FullName => GetType().FullName;
...
}

// (FullName property returns My.Namespace.Class1)
public class Class1 : MyBaseClass
{
...
}

// (FullName property returns My.Namespace.Class2)
public class Class2 : MyBaseClass
{
...
}
```

I've tried configuring this as a discriminator, but EF wants to set the discriminator value itself (`No backing field could be found for property 'FullName' of entity type 'DataPoint' and the property does not have a setter.`). Is it possible to tell EF to use this property as a discriminator without setting it?

**Comment by jzabroski** [comment] 2019-04-30 16:33
@EoinAviation +1 - Try a protected setter.

If that does not work for you, then this is very much in the same vein as the question I just asked in #15529 

We have a bunch of AutoFixture integration tests that automatically generate deep object graphs, and Microsoft.EntityFrameworkCore SaveChanges was blowing up on Discriminator field.  I am trying to figure out the exact problem today, and taking the code in `ShadowFkFixupTest.cs` as a starting point for trying to re-create the issue, but the code is incredibly terse and uses abbreviations I do not understand, hence why I created #15529 to decrypt some of the abbreviations and help improve the code.

I _do think_ that you will run into another issue I am running into, which is I can't get one-to-many child relations to work on TPH entities.  Consider the following object graph:

Discriminator: `enum ParentDiscriminator { Good = 1, Bad = 2 }` 
Table-per-hierarchy: **Abstract** `ParentBase` discriminated by `ParentDiscriminator`.  Extended by `GoodParent` and `BadParent` .
Table-per-hierarchy: **Abstract** ChildBase extended by GoodChild and BadChild.
ParentBase contains many ChildBase objects. (Alternatively, GoodParent contains many GoodChild objects and BadParent contains many BadParent objects).

Here is the SQL schema for the domain model:

```
.--------------------------------.
|  Parent                        |
+--------------------------------+
| ParentID       : bigint        |
| Discriminator  : bigint        |
| GoodParentData : varchar       |
| BadParentData  : varchar       |
'--------------------------------'
                |
               /|\
.--------------------------------.
|  Child                         |
+--------------------------------+
| ChildId        : bigint        |
| ParentId       : bigint        |
| Discriminator  : bigint        |
| GoodChildData  : varchar       |
| BadChildData   : varchar       |
'--------------------------------'                                                         
```

Here is the C# class diagram:

```
    .--------------------------------------------.     .----------------------------------------------.
    |  ParentBase <abstract>                     |     | ChildBase <abstract>                         |
    +--------------------------------------------+     +----------------------------------------------+
    | Id : long                                  |     | Id : long                                    |
    '--------------------------------------------'     '----------------------------------------------'
        |                                     |            |                                      |
       \|/                                   \|/          \|/                                    \|/
.-------------------------. .------------------------. .------------------------. .-----------------------.
| GoodParent              | | BadParent              | | GoodChild              | | BadChild              |
+-------------------------+ +------------------------+ +------------------------+ +-----------------------+
| Child : GoodChild       | | Child : BadChild       | | Parent : GoodParent    | | Parent : BadParent    |
| GoodParentData : string | | BadParentData : string | | GoodChildData : string | | BadChildData : string |
'-------------------------' '------------------------' '------------------------' '-----------------------'
```

**Comment by jzabroski** [comment] 2019-04-30 16:49
By the way, as a polite code review, do not use class names as your discriminator.  If someone wants to later rename your classes, they can't.  It's better to create unique keys for each entity.

**Comment by ajcvickers** [comment] 2019-04-30 19:08
@EoinAviation You can use a property with a no-op private setter (does not need to be protected), but you should make sure that the values it returns correspond to the discriminator values configured in the EF model. In other words, calling the setter should really be a no-op because the value of the property already contains the value that would have been set.

**Comment by jzabroski** [comment] 2019-04-30 20:28
@ajcvickers  Could the CoreStrings.resx file's resource namd `NoFieldOrSetter` be suffixed to say "Use a property with a no-op private setter or protected setter."?

**Comment by ajcvickers** [comment] 2019-04-30 21:21
@jzabroski I'm not sure why we would update the message in that way. For this specific case, that can work with care, but it certainly isn't a general solution for that exception.

I downvoted your comment because it my opinion that's over-engineering. You may have specific reasons for being careful about this, but for most people it falls into YAGNI.

**Comment by jzabroski** [comment] 2019-04-30 21:30
I don't intend for it to be a general solution - just a hint. I submitted a PR #15538 which has slightly different verbiage - I wrote as a hint that if the property is a readonly property, to consider the advice we've both suggested here.

I have not done much EFCore since November, but now that I am back at it, I am finding some of the errors hard to understand and my only saving grace is looking at the test coverage and what behaviors the framework is enforcing.  I've spent all day writing my own tests to contribute back, and to be honest, I keep double and triple checking them because the error messages are so bad that I have to assume the problem is me missing something obvious, not EntityFrameworkCore. (To be fair, I think some error messages make sense IF you worked on EF6 and understand the most common model mapping issues developers had where there were two classes with the same ShortName in the same AppDomain, as was frequently common in projects where you had co-existing Linq2Sql-legacy and EF6 data models. The new EFCore Fluent API prevents that, but creates a new set of issues where if you call something the wrong way, you get weird messages.)

Either way, do with you wish with my feedback.

**Comment by jzabroski** [comment] 2019-05-01 15:36
@ajcvickers  Related to our discussion in #15538 (now closed by me after your feedback), I have found that this is actually documented, just in a different topic: https://docs.microsoft.com/en-us/ef/core/modeling/constructors#read-only-properties

To save you time, here is verbatim quote from that section:

> Once properties are being set via the constructor it can make sense to make some of them read-only. EF Core supports this, but there are some things to look out for:
> 
> * Properties without setters are not mapped by convention. (Doing so tends to map properties that should not be mapped, such as computed properties.)
> * Using automatically generated key values requires a key property that is read-write, since the key value needs to be set by the key generator when inserting new entities.
> 
> An easy way to avoid these things is to use private setters.

**Comment by AndriySvyryd** [comment] 2019-08-22 23:33
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/2319?

**Comment by jzabroski** [comment] 2019-08-23 13:32
@AndriySvyryd I like @MatthewMWR observation of [documenting all scenarios of read-only properties](https://github.com/aspnet/EntityFrameworkCore/issues/2319#issuecomment-108548379):

> Note that there are several issues open related to read-only properties (list below). I don't mean to duplicate those, but rather ask what the intended/suggested pattern is here and if this isn't supported today to consider it for the future.
> 
> #1527
> #1311
> #1526
> #2318

#15530 is just another scenario  (or "use case") for read-only properties, not a duplicate, per say.

**Comment by jzabroski** [comment] 2019-08-23 13:34
As I mention in my previous comment, read-only properties are in fact documented - the issue is lack of linkback from other parts of EF documentation enabling this documentation to be more discoverable / findable from Google (and Bing :))

**Comment by AndriySvyryd** [comment] 2019-09-10 17:37
Docs issue: https://github.com/aspnet/EntityFramework.Docs/issues/1135

**Closed** 2022-10-16 14:19 UTC
Labels: closed-no-further-action, customer-reported

**Comment by voroninp** [comment] 2024-11-18 21:10
I think you'll reopen this issue when C# finally delvers discriminated unions =P
