### ISSUE TITLE
NET Native: Client side evaluation of queries triggered on Release mode

### ISSUE THREAD

**Issue by simader** [dotnet/efcore#18866] opened 2019-11-12 15:18 UTC
Dear EF-Core Team and Community,

We are building an offline Xamarin.Forms.UWP App, which use Microsoft.EntityFrameworkCore.Sqlite 2.2.6 and newest VS2019.
The app works perfectly in DEBUG Mode, but in RELEASE with UseDotNetNativeToolchain (.NET Native Toolchain) enabled, there are some complex queries are failing (with Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning) 

It seems similar than the following issue: #6381

We tried to build a sample for you and appreciate any help.

### Steps to reproduce

1. Download and unzip. 
[App1.zip](https://github.com/aspnet/EntityFrameworkCore/files/3836787/App1.zip)
2. Try in DEBUG => everything works
3. Change to RELEASE => you get QueryClientEvaluationWarning

### Further technical details

EF Core version: 2.2.6
Database provider: Microsoft.EntityFrameworkCore.Sqlite 
IDE: Visual Studio 2019 16.3.8
Newest .NetCore.UniversalWindowsPlattform 6.2.9

**Comment by ajcvickers** [comment] 2019-11-13 16:42
@simader Thanks for filing this issue. We will discuss in our next triage meeting.

**Comment by ajcvickers** [comment] 2019-11-15 21:03
@simader Please try this with [EF Core 3.1 preview 3](Investigate more: https://github.com/aspnet/EntityFrameworkCore/issues/18821). There are a lot of moving parts here, many of which have had updates since 2.2.

**Comment by ajcvickers** [comment] 2019-11-22 22:45
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by simader** [comment] 2019-11-25 14:54
How should i Try ef core 3.1?

So i have no idea how to try this, because EF Core 3.x needs .netStandard2.1 and .netStandard 2.1 is not supported in UWP?

**Comment by ErikEJ** [comment] 2019-11-25 16:36
@simader EF Core 3.1 supports .NET Standard 2.0 !

**Comment by simader** [comment] 2019-11-26 09:52
yes, i read it yesterday after my post. But I tried to upgrade the sample before, and I got the following error:

`error APPX1101: Payload contains two or more files with the same destination path 'e_sqlite3.dll'. Source files: 
error APPX1101: C:\Users\Admin\.nuget\packages\sqlitepclraw.lib.e_sqlite3\2.0.2\runtimes\win10-x86\nativeassets\uap10.0\e_sqlite3.dll
error APPX1101: C:\Users\Admin\.nuget\packages\sqlitepclraw.lib.e_sqlite3.v140\1.1.2\runtimes\win10-x86\native\e_sqlite3.dll`

My first thought was that this is because of the different target framework.
I appreciate any help.

**Closed** 2022-10-16 14:55 UTC
Labels: closed-could-not-reproduce, customer-reported
