### ISSUE TITLE
Database-first scaffolding generates entity names ignoring original casing

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#10678] opened 2018-01-10 18:13 UTC
I have an existing `EF6` code base, and I'm trying to port that to `EF Core`. I'm using the following command to scaffold the entity classes from my database

    Scaffold-DbContext "MyConnectionString" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models

It does generate the `DbContext` and the necessary entities. But things have changed a lot from `EF6` including the naming conventions - how to name entities, properties & navigation (the newly created entities are very different from what I had with my EF6 code).

One of the changes is - Now EF does not singularize class names from table name. e.g. if table name is 'Accessories', earlier entity class used to be 'Accessory', now it is 'Accessories'! This I've fixed using the [IPluralizer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.design.ipluralizer?view=efcore-2.0) interface.

BUT, the final entity classes created by `EF Core`, have names that ignores the original casing! See the following `Table-Name` that I have in my existing database & the `Entity-Name` that is generated by EF.

> Students >> Students
> StudentScores >> StudentScores
> XMLDetails >> Xmldetails (this is the **problem**)

This is different form `EF6` behaviour and it also reduces readability of code and developer's productivity (apart from the fact, I'm having to manually change my existing code all over which I'm trying to port).

There are related issues [9257](https://github.com/aspnet/EntityFrameworkCore/issues/9257) and [9477](https://github.com/aspnet/EntityFrameworkCore/pull/9477) but they deal with the use case - when there are two tables in DB2 with same name but different casing.

The problem seems to come from the way EF code does PascalCase-ing of the names 
```c#
//namespace Microsoft.EntityFrameworkCore.Scaffolding.Internal
//class CandidateNamingService
//method GenerateCandidateIdentifier(string originalIdentifier)
...isFirstCharacterInWord & other logic
candidateStringBuilder.Append(isFirstCharacterInWord ? char.ToUpperInvariant(c) : char.ToLowerInvariant(c));
```

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 8.1
IDE: Visual Studio Community 2017 v15.5.2

**Comment by ErikEJ** [comment] 2018-01-10 18:33
This is a duplicate/known issue, fixed in 2.1
My "EF Core Power Tools" can help you with some of your issues, and I can work with you to fix any remaining issues

**Comment by chakrabar** [comment] 2018-01-10 18:47
@ErikEJ can you direct me to the original issue/fix?
Meanwhile I'll check your [toolbox](https://github.com/ErikEJ/SqlCeToolbox), thanks.

**Comment by chakrabar** [comment] 2018-01-10 21:35
Found the issue and the fix.
This issue is a duplicate of #9820.
This fix is in #9981.

**Comment by ErikEJ** [comment] 2018-01-11 07:43
Please try the "EF Core Power Tools" https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools and report any missing features or other issues/bugs here: https://github.com/ErikEJ/SqlCeToolbox/issues - maybe we can work together to fulfill your requirements?

**Comment by ajcvickers** [comment] 2018-01-12 20:21
Closing this as duplicate. @chakrabar Changing "DOB" to "Dob" is by-design. It's a pretty common code style to do this, and, for what it's worth, it's even in the Microsoft design guidelines.

**Closed** 2022-10-16 12:05 UTC
