### ISSUE TITLE
SqlServerValueGenerationStrategy.IdentityColumn with SQLite

### ISSUE THREAD

**Issue by OneCyrus** [dotnet/efcore#18161] opened 2019-10-01 09:56 UTC
we are usign the sqlite provider and adding a migration generates code which is related to sqlserver.

```
migrationBuilder.CreateTable(
                name: "AspNetRoleClaims",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    ClaimType = table.Column<string>(nullable: true),
                    ClaimValue = table.Column<string>(nullable: true),
                    RoleId = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetRoleClaims", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AspNetRoleClaims_AspNetRoles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "AspNetRoles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });
```

the wrong code is:  **.Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),**

### Steps to reproduce

dotnet ef migrations add

Got Exceptions? Include both the message and the stack trace

no exceptions

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SQLite
Target framework: .NET Core 3.0
Operating system: Windows 10 1903
IDE: Visual Studio 2019 16.3

**Comment by smitpatel** [comment] 2019-10-01 18:47
@OneCyrus - Likely cause for error like this is, you have multiple EF Core providers installed in your project and it is picking up SqlServer provider at design time. Can you verify that you are calling only UseSqlite in your DbContext configuration (also IDesignTimeDbContextFactory implementation if you are using that too)? If everything looks fine then please share full project so that we can investigate.

**Comment by ajcvickers** [comment] 2019-10-10 00:23
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:46 UTC
Labels: closed-could-not-reproduce, customer-reported
