### ISSUE TITLE
Migrate to SQL Azure retry execution strategy

### ISSUE THREAD

**Issue by gazoonie** [dotnet/efcore#19898] opened 2020-02-12 21:29 UTC
We are attempting to handle transient errors when applying a migration to a SQL Azure database.

The problem is that the Max Retry Count is not being applied per command, but for the entire migration process. Our max retry count is set to 5 and I'll see in our logs where four separate commands are retried, but the 5th exception kills the process. Most of the time the migration is successful, but maybe every 6th time results in failure.

Here is what the execution strategy looks like:
``` C#
IExecutionStrategy strategy = dbContext.Database.CreateExecutionStrategy();
await strategy.ExecuteAsync(async () =>
{
    await dbContext.GetService<IMigrator>().MigrateAsync(migrationId);
});
```

**What is the recommended retry execution strategy for migrations?**

### Steps to reproduce
I can't think of any valuable repro steps to provide that will help further clarify the issue.
Here are the logs (trimmed for brevity and edited for privacy)
[Migration Logs.txt](https://github.com/dotnet/efcore/files/4195086/Migration.Logs.txt)

### Further technical details
The migration is kicked off as a job in Kubernetes.

EF Core version: 3.1.1
Database provider: SQL Azure database within a Standard Tier Elastic Pool
Target framework: .NET Core 3.1
Operating system: Windows 10 Enterprise
IDE: Visual Studio 2019 16.4.5

**Comment by AndriySvyryd** [comment] 2020-02-13 20:04
You can always create a different execution strategy for a given operation:
```C#
IExecutionStrategy strategy = new SqlServerRetryingExecutionStrategy(dbContext, maxRetryCount: 10);
```

**Comment by gazoonie** [comment] 2020-02-14 00:01
So you're telling me to just add more retry attempts? How is that an acceptable solution to retry tens-of-thousands of commands? (Probably more)
We currently have 52 migrations and more are added all the time.

Maybe you misunderstood the problem.
Let's say I have my retry count set to 5 and I have a migration that has 10 CREATE TABLE commands. The first command fails 3 times, but succeeds on the 4th retry. Awesome! Unfortunately, now all but 1 retry attempt is left. Let's hope there aren't any more transient errors.
If the retry counter was reset between commands, that would be great too, but there isn't a way to control that when applying a migration.

I need a way to wrap each command in the migration in its own Retry Execution Strategy. Is there built in way to get all the commands that run when applying a migration?

**Comment by AndriySvyryd** [comment] 2020-02-14 00:47
@gazoonie Sorry, I assumed you were only applying one migration at a time. In any case this is a duplicate of https://github.com/dotnet/efcore/issues/17578

**Closed** 2022-10-16 18:10 UTC
Labels: closed-no-further-action, customer-reported
