### ISSUE TITLE
Scaffold-DbContext doesn't produce AspNetUserRoles Class and DbSet

### ISSUE THREAD

**Issue by fsmirne** [dotnet/efcore#27279] opened 2022-01-25 20:50 UTC
I'm trying to use the **Scaffold-DbContext** function to create classes to query the standard Identity tables for EF Core.
I noticed that all the tables are created but the **AspNetUserRoles** does not.
The database I'm using is straight from the Web Project template without any modification.
note that the template included in visual studio does have the entity code for the table, but scaffold does not produce it.

I started using PostgreSQL but realized that the same behavior applies to SQL Server.
The original issue is listed [here](https://github.com/npgsql/EntityFramework6.Npgsql/issues/182)

Here's the Scaffold code I'm using. The database name was created by visual studio.

```C#
Scaffold-DbContext "Server=(localdb)\MSSQLLocalDB;Database=aspnet-WebApplication2-53bc9b9d-9d6a-45d4-8429-2a2761773502;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Model
```

In my opinion, scaffolding should produce code for all tables and ignoring the many to many tables seems like a flaw to me. Without those tables, it doesn't produce a 100% accurate representation of the tables that exist in the database.

### Include provider and version information

EF Core version: 6.0.1
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (.NET 6.0)
Operating system: Windows 11
IDE: (Visual Studio 2022 17.0.5)

**Comment by roji** [comment] 2022-01-25 21:41
See my answer [here](https://github.com/npgsql/efcore.pg/issues/2241#issuecomment-1021634757).

**Comment by roji** [comment] 2022-01-25 21:42
Duplicate of #4038

**Closed** 2022-10-16 20:23 UTC
Labels: closed-duplicate, customer-reported
