### ISSUE TITLE
Select uses INNER JOIN instead of LEFT JOIN

### ISSUE THREAD

**Issue by cbmek** [dotnet/efcore#4635] opened 2016-02-24 14:18 UTC
## The case

Lets say we have two objects with nullable relation one-to-many:

``` csharp
public class Post {
    public int Id { get; set; }
    public string Title{ get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
}
```

``` csharp
public class Comment {
    public int Id { get; set; }
    public string Content { get; set; }
    public int? PostId {get; set; }
    public virtual Post Post { get; set; }
}
```

We want to get all the comments with it's Posts (if any).

``` csharp
var all = _context.Comments.Include(m => m.Post).ToList();
```

it will do a single query, with LEFT JOIN, and results are correct. If Comments is not assigned to Post then Post property will equal null - PERFECT!
## The problem

...but let's use Select, like this:

``` csharp
var all = _context.Comments.Include(m => m.Post).Select(m => new { 
    Something = m.Content, 
    PostTitle = Post != null ? Post.Title : "NO POST"  
});
```

and strange thing happen, the SQL query uses INNER JOIN, so we end *_only *_with Comments witch has Post assigned. In my opinion it should still use LEFT JOIN.
## Temp solution

The only way to make it to work like it should now is to do the ToList() before Select():

``` csharp
var all = _context.Comments.Include(m => m.Post).ToList().Select(m => new { 
    Something = m.Content, 
    PostTitle = Post != null ? Post.Title : "NO POST"  
});
```

**Comment by gdoron** [comment] 2016-02-24 18:23
How does the SQL look like if you omit the `Include`:

```
var all = _context.Comments.Select(m => new { 
    Something = m.Content, 
    PostTitle = Post != null ? Post.Title : "NO POST"  
});
```

Is there any difference?

**Comment by cbmek** [comment] 2016-02-24 18:58
No, it's still INNER JOIN. And more interesting it that when you do 3 includes but use only one reference in Select, it will do only one INNER JOIN - so Select probably cancel all previous includes.

**Comment by maumar** [comment] 2016-02-24 19:12
@cbmek you can try the following:

```
from c in _context.Comments
join p in _context.Post on c.PostId equals p.Id into grouping
from p in grouping.DefaultIfEmpty()
select new { Something = p.Content, PostTitle = p != null ? p.Title : "NO POST" }
```

The actual issue of optional navigation translation to LOJ has been addressed in c4e44471b6f41f96d37b1acfbbb4cc97cd11ee89 and should be available in the next release

**Comment by maumar** [comment] 2016-02-24 19:16
@cbmek one thing I should add, there is currently no advantage of the DefaultIfEmpty approach (if it even works in released bits) over what you initially did (Include + ToList() ), since currently everything after DefaultIfEmpty will be evaluated on the client, so all properties of Comment and Post will be send to the client. We have an issue that tracks this: #4588

**Comment by maumar** [comment] 2016-02-24 19:18
@cbmek @gdoron Include doesn't work with optional navigations currently. #4589 tracks this problem

**Comment by strohhut** [comment] 2016-03-03 21:44
This bug really is extreme and only requires an optional FK to reproduce. Please fix this in RC2.

**Comment by maumar** [comment] 2016-03-03 22:18
@strohhut it is already fixed in our current dev branch

**Comment by danielcojocaru** [comment] 2020-11-28 22:59
Same problem here with 3.1. When x => false then the list is empty, but when x => true, then the list is field.
I have checked sql query and it does an inners join, instead of an left join.

```  
GroupCoachStudents.Select(gcs => new PrelimStudentDto()
{
    Student = gcs.CoachStudentUser.Student,
    DueSession = group.Sessions
        .Where(x=> false)
        .FirstOrDefault()
}),
```

**Comment by ajcvickers** [comment] 2020-11-30 21:20
@danielcojocaru This is a very old closed issues. If you're still having an issue, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Closed** 2022-10-16 09:30 UTC
Labels: closed-no-further-action, customer-reported
