### ISSUE TITLE
EFCore Contains convert openjson with type is error

### ISSUE THREAD

**Issue by MayueCif** [dotnet/efcore#32529] opened 2023-12-06 07:38 UTC
contains convert openjson with value,but value type is wrong

For example:

```C#
var d = lionKingDbContext.Users
    .Where(u => feiShuUsers.Select(fu => fu.Mobile).Contains((u.PhoneCountryCode + u.PhoneNumber)))
    .ToQueryString();
var dd = lionKingDbContext.Users
    .Where(u => feiShuUsers.Select(fu => fu.Mobile).Contains(u.PhoneNumber + u.PhoneCountryCode))
    .ToQueryString();
```
d value 
```
WHERE [u].[PhoneCountryCode] + [u].[PhoneNumber] IN (
    SELECT [s].[value]
    FROM OPENJSON(@__Select_0) WITH ([value] nvarchar(5) '$') AS [s]
)
```
dd value is
```
WHERE [u].[PhoneNumber] + [u].[PhoneCountryCode] IN (
    SELECT [s].[value]
    FROM OPENJSON(@__Select_0) WITH ([value] nvarchar(15) '$') AS [s]
)
```

the data types are nvarchar(5) and nvarchar(15).it's not worked.

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 8.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.8.2)

**Comment by ajcvickers** [comment] 2023-12-06 12:45
Duplicate of #32325

**Closed** 2023-12-08 13:18 UTC
Labels: closed-duplicate, customer-reported
