### ISSUE TITLE
Q: Avoid full table scan when scaffolding

### ISSUE THREAD

**Issue by piyey** [dotnet/efcore#9812] opened 2017-09-13 22:28 UTC
I was looking for an option that I can avoid full table scan when scaffolding, I'm working with a DB with more than 2k+ tables, and it takes a lot of time when running scaffolding.

I already search and didn't find any post about this option.

Best regards.
Thanks!

**Comment by smitpatel** [comment] 2017-09-13 23:28
Duplicate of #9568

@piyey - Thanks for feedback. That is something we are planning to do in linked issue. Once intial scan done to get list of tables to be included, every other query would run for included table only.

**Comment by piyey** [comment] 2017-09-13 23:50
Thanks @smitpatel ;)

**Closed** 2022-10-16 11:49 UTC
