### ISSUE TITLE
Unable to cast object of type 'System.Byte[]' to type 'System.String

### ISSUE THREAD

**Issue by jasondaicoder** [dotnet/efcore#9142] opened 2017-07-11 09:17 UTC
Hi guys,

I am having an issue on an entity with a string property which is saved in database as a byte array. I can generate the models using dotnet-ef, however I could not retrieve the entities via dbcontext as it always throws the below exception:

    System.InvalidOperationException: An exception occured while reading a database value for property 'Member.PostCode'. The expected type was 'System.String' but the actual value was of type 'System.Byte[]'. ---> System.InvalidCastException: Unable to cast object of type 'System.Byte[]' to type 'System.String'.
       at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.TryReadValue[TValue](ValueBuffer valueBuffer, Int32 index, IPropertyBase property)
       --- End of inner exception stack trace ---
       at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
       at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.TryReadValue[TValue](ValueBuffer valueBuffer, Int32 index, IPropertyBase property)
       at lambda_method(Closure , ValueBuffer )
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
       at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.<>c__DisplayClass3_0`1.<_ShapedQuery>b__0(ValueBuffer vb)
       at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
       --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.<_FirstOrDefault>d__82`1.MoveNext()
       --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.EntityFrameworkCore.Query.Internal.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
       --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
       --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
       --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

### Further technical details
EF Core version: (1.1.2)
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10
IDE: (e.g. Visual Studio Code)

**Comment by ajcvickers** [comment] 2017-07-11 16:09
@jasondaicoder This requires type conversions, which is being tracked by #242.

**Comment by jasondaicoder** [comment] 2017-07-11 20:41
Thanks for your reply. I understand we might need conversion if the db field type is different with the entity property type. However in my case, entity property member.postcode is string type, and in database table field member.postcode is defined as nvarchar as well. Do we still need to add the conversion? We don't have this problem with EF 6.

**Comment by ajcvickers** [comment] 2017-07-11 20:44
@jasondaicoder If it's a string in the database and a string in the model, then it should work. Can you post a full code listing or project that reproduces the issue you are seeing?

**Comment by jasondaicoder** [comment] 2017-07-11 22:09
@ajcvickers, sorry I can't share the full code with you as it's part of company application. The code is quite straight forward. 

1. Have a field PostCode as nvarchar in database table Member. The only thing it might have impact is we use encryption
   [PostCode] [nvarchar](50) COLLATE Latin1_General_BIN2 ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = [PIIColumnEncryptionKey], ENCRYPTION_TYPE = Deterministic, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NULL,
2. Have a entity model Member with a property PostCode as string. This is generated by using dotnet-ef
    public string PostCode { get; set; }
3. Call DbContext.Member.Where(m => m.Id = 1000).FirstOrDefault()
4. Get the above exception

It might be related to the encryption however we don't have the problem with EF 6.

**Comment by divega** [comment] 2017-07-11 23:25
@jasondaicoder is your application targeting .NET Framework or .NET Core? Do you have `Column Encryption Setting=Enabled` in the connection string?

**Comment by jasondaicoder** [comment] 2017-07-11 23:38
@divega , it's targeting .net core. I don't have the encryption setting in connection string, but I will try now.

**Comment by jasondaicoder** [comment] 2017-07-11 23:42
@divega, looks like the the setting is not supported in EF core, see below exception

System.ArgumentException: Keyword not supported: 'column encryption setting'.\r\n

**Comment by smitpatel** [comment] 2017-07-11 23:53
@jasondaicoder - Can you share stacktrace? Its probably SqlClient issue.

**Comment by jasondaicoder** [comment] 2017-07-11 23:59
@smitpatel , please see below detail callstack

"System.ArgumentException: Keyword not supported: 'column encryption setting'.
  at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms)
  at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
  at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
  at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
  at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
  at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
  at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
  at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection.CreateDbConnection()
  at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
  at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<BufferlessMoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__6`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.<_FirstOrDefault>d__82`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.EntityFrameworkCore.Query.Internal.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
  at Mailchimp.Services.CommandHandlers.UpdateMemberCommandHandler.<Handle>d__3.MoveNext() in c:\\Workspace\\MailchimpLambda\\src\\Mailchimp.Services\\CommandHandlers\\UpdateMemberCommandHandler.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by smitpatel** [comment] 2017-07-12 00:03
External issue https://github.com/dotnet/corefx/issues/18276

@jasondaicoder - This is not EF Core bug. The underlying SqlClient in .NET core does not support `column encryption setting`. Since the setting is not enabled, while fetching records from server, EF receives encrypted value of byte[] type which cannot be assigned to string property hence it threw exception.

**Comment by jasondaicoder** [comment] 2017-07-12 00:10
@smitpatel, thanks for the information. Looks like we found the culprit. Looks like we will need to wait for 2.0 :(

**Comment by divega** [comment] 2017-07-12 01:21
@jasondaicoder unfortunately I think you are going to have to wait until later after. The feature needs to be prioritized for SqlClient as @corivera indicated at https://github.com/dotnet/corefx/issues/18276#issuecomment-314610769 and it won't be supported in 2.0.

**Closed** 2022-10-16 11:11 UTC
Labels: closed-external, area-external
