### ISSUE TITLE
Cannot set ValueObject as database index

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#23943] opened 2021-01-23 08:22 UTC
I have the following ValueMember

```
public class ApplicationName : ValueObject
{
    public string FirstName { get; }
    public string LastName { get; }

    protected ApplicationName()
    {
    }

    private ApplicationName(string firstName, string lastName)
        : this()
    {
        FirstName = firstName;
        LastName = lastName;
    }
    
    etc...
}
```
in the following class (Asp.Net Core IdentityUser class)

```
public class ApplicationUser : IdentityUser<long>
{
    public ApplicationUserName Name { get; set; }
}
```
Those columns (FirstName, LastName) along with the Email column are part of a db index. I have the following in my dbcontext
```
modelBuilder.Entity<ApplicationUser>(x =>
{
    x.OwnsOne(p => p.Name, p =>
    {
        p.Property(pp => pp.FirstName).HasColumnName("FirstName");
        p.Property(pp => pp.LastName).HasColumnName("LastName");
    });
    x.HasIndex(p => new { p.Name, p.Email });
});
```
When I run my app I get the following error
```System.InvalidOperationException: ''Name' cannot be used as a property on entity type 'ApplicationUser' because it is configured as a navigation.```

```
at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Type propertyType, String propertyName, MemberInfo memberInfo, Nullable`1 typeConfigurationSource, Nullable`1 configurationSource)
at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(MemberInfo memberInfo, Nullable`1 configurationSource)
at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.GetOrCreateProperties(IEnumerable`1 clrMembers, Nullable`1 configurationSource)
at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasIndex(IReadOnlyList`1 clrMembers, ConfigurationSource configurationSource)
at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasIndex(Expression`1 indexExpression)
at MyApp.Backend.Infrastructure.EntityFramework.MyAppDbContext.<>c.<OnModelCreating>b__106_4(EntityTypeBuilder`1 x) in C:\SourceControl\MyApp.Backend\src\MyApp.Backend\Infrastructure\EntityFramework\MyAppDbContext.cs:line 216
at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity](Action`1 buildAction)
at MyApp.Backend.Infrastructure.EntityFramework.MyAppDbContext.OnModelCreating(ModelBuilder modelBuilder) in C:\SourceControl\MyApp.Backend\src\MyApp.Backend\Infrastructure\EntityFramework\MyAppDbContext.cs:line 207
at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
at MyApp.Backend.Infrastructure.EntityFramework.MyAppDbContext..ctor(DbContextOptions options) in C:\SourceControl\MyApp.Backend\src\MyApp.Backend\Infrastructure\EntityFramework\MyAppDbContext.cs:line 35
at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
```

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: Win10 1909
IDE: Visual Studio 2019 16.8.2

**Comment by roji** [comment] 2021-01-23 11:20
Duplicate of #11336

**Comment by roji** [comment] 2021-01-23 11:21
@pantonis see my [answer here on changing the column type for SQL Server](https://github.com/dotnet/efcore/issues/11336#issuecomment-765907817).

**Closed** 2022-10-16 19:19 UTC
Labels: customer-reported
