### ISSUE TITLE
Add support to exclude tables during scaffolding

### ISSUE THREAD

**Issue by geetmenon** [dotnet/efcore#26277] opened 2021-10-07 20:20 UTC
I am using EFCore 5.0.8. I understand that we can use the  `-Tables` switch to specify the list of tables to be included for scaffolding using `Scaffold-DbContext` command. For us, the list of tables to be included is a huge list and the list of tables to be excluded is small list. So for us it  would make sense to specify exclude tables list as opposed to specifying include tables list.  EFCore does not have a switch to specify exclude tables list in `Scaffold-DbContext` command. Can you add support for this.

**Comment by ErikEJ** [comment] 2021-10-08 06:09
Duplicate of#6182

**Closed** 2022-10-16 20:09 UTC
Labels: customer-reported
