### ISSUE TITLE
Temporal tables are not supported for table splitting but no table splitting is used

### ISSUE THREAD

**Issue by Leonvkampen** [dotnet/efcore#28931] opened 2022-08-31 08:58 UTC
Hi, 

I am getting the following error on my ProjectTask entity. 

Temporal tables are not supported for table splitting scenario. Table: 'ProjectTask'.

This is really weird because I generated a migration without any problems since this entity isn't using any table splitting. 

Code is under here anyone that can help me with this?

```C#
public class ProjectTaskConfiguration : BaseAuditableEntityConfiguration<ProjectTask>
{
    public override void Configure(EntityTypeBuilder<ProjectTask> builder)
    {
        base.Configure(builder);

        builder.ToTable(nameof(ProjectTask), s => s.IsTemporal(x => x.UseHistoryTable("ProjectTaskHistory")));

        builder.HasKey(e => new { e.ProjectId, e.TaskTemplateId });

        builder.Property(e => e.Status)
            .HasConversion<string>();

        builder.HasMany(s => s.Answers)
            .WithOne(p => p.ProjectTask)
            .HasForeignKey(f => new { f.ProjectId, f.TaskTemplateId })
            .HasPrincipalKey(p => new { p.ProjectId, p.TaskTemplateId })
            .OnDelete(DeleteBehavior.Cascade);
    }
}
```

```C#
public class ProjectTask : BaseAuditableEntity
{
    public ProjectTask(Guid projectId, Guid taskTemplateId, ProjectStatus status)
    {
        ProjectId = projectId;
        TaskTemplateId = taskTemplateId;
        Status = status;

        Answers = new List<ProjectTaskAnswer>();
    }

    public Guid ProjectId { get; init; }
    public Guid TaskTemplateId { get; init; }

    public DateTime? TaskStarted { get; set; }
    public DateTime? TaskFinished { get; set; }

    public ProjectStatus Status { get; set; }

    public List<ProjectTaskAnswer>? Answers { get; set; }
    public Project? Project { get; init; }
}
```

**Comment by ajcvickers** [comment] 2022-08-31 17:23
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by NaskoVasilev** [comment] 2022-09-01 12:38
I am getting the same problem in the this project: https://github.com/NaskoVasilev/Advanced-Concepts/tree/main/02_Temporal_Tables/TemporalTablesDemo

When I add owned entity to the employee model (https://github.com/NaskoVasilev/Advanced-Concepts/blob/main/02_Temporal_Tables/TemporalTablesDemo/TemporalTablesDemo/Data/Models/Employee.cs) and try to make a migration I get the following error: Temporal tables are not supported for table splitting scenario. Table: 'Employees'.

Does anyone have an idea to cope with this problem? Removing owned entities is not a variant!

**Comment by ajcvickers** [comment] 2022-09-01 12:59
@Leonvkampen Owned entities make use of table splitting by default. This is supported in the EF7 previews. See https://github.com/dotnet/efcore/issues/26469.

**Comment by ajcvickers** [comment] 2022-09-09 18:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-09-09 18:38 UTC
Labels: customer-reported
