### ISSUE TITLE
GroupBy with Join is evaluated locally 

### ISSUE THREAD

**Issue by cjaliaga** [dotnet/efcore#12390] opened 2018-06-17 21:08 UTC
I'm in the process of porting an app which uses EF6 to a .NET Core one with EFCore. In a GroupBy which is grouping for the ForeignKey and counting the elements of each group, as soon as I add a Join to get data from the related entity, the GroupBy cannot be translated and it's evaluated locally.      

### Steps to reproduce
I've created a simple project reproducing the issue: https://github.com/cjaliaga/GroupByWithJoinTest/ 

The queries that I'm trying are:
```c#
var mostFollowedQuerySyntax = (from f in context.FollowShows
                        group f by f.ShowId
                        into g
                        join show in context.Shows on g.Key equals show.Id
                        select new
                        {
                            Id = g.Key,
                            Followers = g.Count(),
                            Name = show.Name,
                        })
                    .OrderByDescending(s => s.Followers)
                    .FirstOrDefault();

var mostFollowedMethodSyntax = context.FollowShows
                    .GroupBy(f => f.ShowId, (key, grp) => new {Id = key, Followers = grp.Count()})
                    .Join(context.Shows, f => f.Id, s => s.Id,
                        (f, s) => new
                        {
                            Id = f.Id,
                            Followers = f.Followers,
                            Name = s.Name
                        }).OrderByDescending(s => s.Followers)
                    .FirstOrDefault();
```

The models

```c#
public class Show
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<FollowShow> Followers { get; set; }
    }

   public class FollowShow
    {
        public int Id { get; set; }
        public int ShowId { get; set; }
        public Show Show { get; set; }
        public DateTime Followed { get; set; }
    }
```
The logging output when running the first query:
```
dbug: Microsoft.EntityFrameworkCore.Query[10101]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      Compiling query model:
      '(from IGrouping<int, FollowShow> g in
          (from FollowShow f in DbSet<FollowShow>
          select [f]).GroupBy([f].ShowId, [f])
      join Show show in DbSet<Show>
      on [g].Key equals [show].Id
      order by
          (from FollowShow <generated>_1 in [g]
          select [<generated>_1]).Count() desc
      select new <>f__AnonymousType3<int, int, string>(
          [g].Key,

              (from FollowShow <generated>_1 in [g]
              select [<generated>_1]).Count(),
          [show].Name
      )).FirstOrDefault()'
dbug: Microsoft.EntityFrameworkCore.Query[10104]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      Optimized query model:
      '(from IGrouping<int, FollowShow> g in
          (from FollowShow f in DbSet<FollowShow>
          select [f]).GroupBy([f].ShowId, [f])
      join Show show in DbSet<Show>
      on [g].Key equals [show].Id
      order by
          (from FollowShow <generated>_1 in [g]
          select [<generated>_1]).Count() desc
      select new <>f__AnonymousType3<int, int, string>(
          [g].Key,

              (from FollowShow <generated>_1 in [g]
              select [<generated>_1]).Count(),
          [show].Name
      )).FirstOrDefault()'
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'GroupBy([f].ShowId, [f])' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'join Show show in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[GroupByTest.Models.Show]) on [g].Key equals [show].Id' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'orderby {[g] => Count()} desc' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'Count()' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'Count()' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'Count()' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'FirstOrDefault()' could not be translated and will be evaluated locally.
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      (QueryContext queryContext) => IEnumerable<<>f__AnonymousType3<int, int, string>> _InterceptExceptions(
          source: IEnumerable<<>f__AnonymousType3<int, int, string>> _ToSequence(() => <>f__AnonymousType3<int, int, string> FirstOrDefault(IEnumerable<<>f__AnonymousType3<int, int, string>> _Select(
                      source: IOrderedEnumerable<TransparentIdentifier<IGrouping<int, FollowShow>, ValueBuffer>> _OrderBy(
                          source: IEnumerable<TransparentIdentifier<IGrouping<int, FollowShow>, ValueBuffer>> _Join(
                              outer: IEnumerable<IGrouping<int, FollowShow>> _GroupBy(
                                  source: IEnumerable<FollowShow> _ShapedQuery(
                                      queryContext: queryContext,
                                      shaperCommandContext: SelectExpression:
                                          SELECT [f].[Id], [f].[Followed], [f].[ShowId]
                                          FROM [FollowShows] AS [f]
                                          ORDER BY [f].[ShowId],
                                      shaper: BufferedEntityShaper<FollowShow>),
                                  keySelector: (FollowShow f) => f.ShowId,
                                  elementSelector: (FollowShow f) => f),
                              inner: IEnumerable<ValueBuffer> _ShapedQuery(
                                  queryContext: queryContext,
                                  shaperCommandContext: SelectExpression:
                                      SELECT [show].[Id], [show].[Name]
                                      FROM [Shows] AS [show],
                                  shaper: ValueBufferShaper),
                              outerKeySelector: (IGrouping<int, FollowShow> g) => g.Key,
                              innerKeySelector: (ValueBuffer show) => int TryReadValue(show, 0, Show.Id),
                              resultSelector: (IGrouping<int, FollowShow> g | ValueBuffer show) => TransparentIdentifier<IGrouping<int, FollowShow>, ValueBuffer> CreateTransparentIdentifier(
                                  outer: g,
                                  inner: show)),
                          expression: (TransparentIdentifier<IGrouping<int, FollowShow>, ValueBuffer> t0) => int Count(t0.Outer),
                          orderingDirection: Desc),
                      selector: (TransparentIdentifier<IGrouping<int, FollowShow>, ValueBuffer> t0) => new <>f__AnonymousType3<int, int, string>(
                          t0.Outer.Key,
                          int Count(t0.Outer),
                          string TryReadValue(t0.Inner, 1, Show.Name)
                      )))),
          contextType: GroupByTest.ShowsDbContext,
          logger: DiagnosticsLogger<Query>,
          queryContext: queryContext)
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'TestShows' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
      Opened connection to database 'TestShows' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [f].[Id], [f].[Followed], [f].[ShowId]
      FROM [FollowShows] AS [f]
      ORDER BY [f].[ShowId]
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (81ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [f].[Id], [f].[Followed], [f].[ShowId]
      FROM [FollowShows] AS [f]
      ORDER BY [f].[ShowId]
dbug: Microsoft.EntityFrameworkCore.Database.Command[20300]
      A data reader was disposed.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [show].[Id], [show].[Name]
      FROM [Shows] AS [show]
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (13ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [show].[Id], [show].[Name]
      FROM [Shows] AS [show]
dbug: Microsoft.EntityFrameworkCore.Database.Command[20300]
```
### Further technical details
EF Core version: 2.1.0-rtm-30799
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.3

**Comment by smitpatel** [comment] 2018-06-18 23:33
Duplicate of #10012

**Closed** 2022-10-16 12:31 UTC
Labels: closed-duplicate, customer-reported
