### ISSUE TITLE
using DataDirectory in DataSource

### ISSUE THREAD

**Issue by ghost1372** [dotnet/efcore#15735] opened 2019-05-16 09:28 UTC
hi is it possible that i use DataDirectory in DataSource? i used this code but not worked
```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder.UseSqlite(@"Data Source = |DataDirectory|\db.db"));
        }
```
I could do this in app.config connectionstring before but in EFCore i cant

**Comment by ajcvickers** [comment] 2019-05-16 16:13
Duplicate of #13840

**Closed** 2022-10-16 14:21 UTC
Labels: customer-reported
