### ISSUE TITLE
Add CodeGeneratedAttribute to migrations/snapshots

### ISSUE THREAD

**Issue by Azkarell** [dotnet/efcore#25820] opened 2021-09-01 13:10 UTC
Most Code Coverage tools ignore auto generated code (for good reasons). 
Model snapshots and migrations are not marked as auto generated -> they are included in the Report.

If migrations/model snapshot is generated by ef core tools, they should be annotated by CodeGeneratedAttribute.

Maybe there are other tools that would benefit from this Attribute as well.

It certainly has not the highest priority and can be easy fixed on user site but i think auto generated code should be annotated this way.

**Comment by ajcvickers** [comment] 2021-09-01 13:21
Duplicate of #19596

**Closed** 2022-10-16 19:44 UTC
Labels: customer-reported
