### ISSUE TITLE
Configure an owned entity in order to have one to many relationship with an abstract class

### ISSUE THREAD

**Issue by dimitkos** [dotnet/efcore#29294] opened 2022-10-07 13:05 UTC
I have a class User which owns many class Post. The class posts own many class Comment and now I would like to handle a relationship between comments and reactions(reaction is an abstract class which can be like, star etc). As I read in the official doc I cannot implement reactions as owned because it has an inheritance hierarchy.

```C#
public class User
	{
       private readonly List<Post> _posts;

       public long Id{ get; }
       public string Username{ get; }
       public DateTime CreatedAt { get; }
       public IReadOnlyCollection<Post> Posts => _posts.AsReadOnly();

       private User() : base(default, default)
		{
			CreatedAt = DateTime.UtcNow;
			UpdatedAt = DateTime.UtcNow;
			_posts= new List<Post>();
		}
       //bla bla public constructor  etc
		}
```

```C#
public class Post
	{
		private readonly List<Comment> _comments;

		public long PostId { get; }
		public DateTime CreatedAt { get; }
		public IReadOnlyCollection<Comment> Comments => _comments.AsReadOnly();

		private Post()
		{
			CreatedAt = DateTime.UtcNow;
			_comments = new List<Comment>();
		}
       //bla bla public constructor  etc
	}
```
```C#
public class Comment
	{
		private readonly List<Reaction> _reactions;

		public long CommentId { get; }
		public string Text { get; }
		public DateTime CreatedAt { get; }
		public IReadOnlyCollection<Reaction> Reactions => _reactions.AsReadOnly();

		private Comment()
		{
			CreatedAt = DateTime.UtcNow;
			_reactions = new List<Reaction>();
		}
		//bla bla public ctor
	}
```
and finally the class Reaction
```C#
public abstract partial class Reaction
	{
		public long Id { get; }

		protected Reaction() { }

		protected Reaction(long id)
		{
			Id = id;
		}
	}
```
which has two child classes
the class Star
```C#
public abstract partial class Reaction
	{
		public class Star : Reaction
		{
			private readonly List<Caption> _captions;

			public decimal Value { get; private set; }
			public IReadOnlyCollection<Caption> Captions => _captions.AsReadOnly();

			public Star(long id, decimal value, IReadOnlyCollection<Caption> captions) : base(id)
			{
				Value = value;
				_captions = captions.ToList();
			}
		}
	}
```
and the class Like
```C#
public abstract partial class Reaction
	{
		public class Like : Reaction
		{
			private readonly List<Caption> _captions;

			public IReadOnlyCollection<Caption> Captions => _captions.AsReadOnly();

			public Like(long id, Caption[] captions) : base(id)
			{
				_captions = captions.ToList();
			}
		}
	}
```
Finally the class 
```C#
public class Caption
	{
		public int Id { get; }
		public string Text { get; }

		public Caption(int id, string text)
		{
			Id = id;
			Text = text;
		}
	}
```

I have stacked how to configure the database schema.
Comments cannot own many reactions due to an owned entity cannot have an inheritance hierarchy.
I tried to implement a table-per-type solution for reactions which is abstract class.

Here is the configuration
```C#
public void Configure(EntityTypeBuilder<User> builder)
		{
			builder.ToTable("Users");
			builder.HasKey(x => x.Id);

			builder.Property(x => x.Id).ValueGeneratedNever().IsRequired();
			builder.Property(x => x.Username).IsRequired();
			builder.Property(x => x.CreatedAt).IsRequired();
			
			builder.OwnsMany(x => x.Posts, post =>
			{
				post.ToTable("Posts");

				post.HasKey(PostsId);

				post.Property(x => x.PostsId).ValueGeneratedNever().IsRequired();
				post.Property(x => x.CreatedAt).IsRequired();

				post.OwnsMany(x => x.Comments, comment =>
				{
					comment.ToTable("Comments");

					comment.HasKey(CommentId);

					comment.Property(x => x.CommentId).ValueGeneratedNever().IsRequired();
					comment.Property(x => x.Text).HasMaxLength(100).IsRequired();
					comment.Property(x => x.CreatedAt).IsRequired();

					//how to continue the configuration of reactions and captions???
					
				});
			});
		}
	}
```
I don't know how to configure a relationship between comments and reactions.A comment could have many reactions(one to many) and a reaction could have many captions(one to many)
EF Core version: 6.0.6
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.3.3

**Comment by ajcvickers** [comment] 2022-10-11 11:52
@dimitkos What is the rationale for using owned types in this model?

**Comment by ajcvickers** [comment] 2022-10-21 10:36
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-10-21 10:36 UTC
Labels: customer-reported
