### ISSUE TITLE
EFCore deletes an association on DbContext.SaveChanges when an existing link is removed and then added in the same transaction

### ISSUE THREAD

**Issue by 87Alex** [dotnet/efcore#31736] opened 2023-09-14 11:38 UTC
Steps to reproduce:

1. Add two classes to a context.

```C#
    public class ManyToMany_Right {
        public virtual int ID { get; set; }
        public virtual string Name { get; set; }
        public virtual IList<ManyToMany_Left> CollectionLeft { get; set; } = new ObservableCollection<ManyToMany_Left>();
    }
    public class ManyToMany_Left {
        public virtual int ID { get; set; }
        public virtual string Name { get; set; }
        public virtual IList<ManyToMany_Right> CollectionRight { get; set; } = new ObservableCollection<ManyToMany_Right>();
    }
```

2. Create instances for each class and link between them. Save the changes.
3. Remove the ManyToMany_Left instance from CollectionLeft of the ManyToMany_Right instance and add it again.
4. Save the changes.
Expected behavior:
CollectionLeft count is 1.
Actual behavior:
CollectionLeft count is 0.

It looks like the problem lies in the FindOrCreateJoinEntry method. It finds the entry but does not update its state from Deleted to Unchanged.

```C#
var joinEntry = FindJoinEntry(arguments.Entry, arguments.OtherEntry, arguments.SkipNavigation);
        if (joinEntry != null)
        {
            SetForeignKeyProperties(
                joinEntry, arguments.Entry, arguments.SkipNavigation.ForeignKey, arguments.SetModified, arguments.FromQuery);
            SetForeignKeyProperties(
                joinEntry, arguments.OtherEntry, arguments.SkipNavigation.Inverse.ForeignKey, arguments.SetModified,
                arguments.FromQuery);
        }
```

**### version information

EF Core version: 7.0.3(7.0.10 also the same issue)
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by ajcvickers** [comment] 2023-09-25 13:01
Duplicate of #31440

**Closed** 2023-10-03 10:52 UTC
Labels: customer-reported
