### ISSUE TITLE
GetTableName() for InMemory provider isn't working as expected

### ISSUE THREAD

**Issue by antifree** [dotnet/efcore#19751] opened 2020-01-30 14:16 UTC
When we use the InMemory provider, `GetTableName()` returns EntityType Name as the default table name instead of DbSet property name. So we need to use `modelbuilder.ToTable()` to configure table names, as we expect. 

> By the way, data annotation attribute `Table` doesn't work either for InMemory provider. Possibly, it would be better to create a separate issue for this.

Other providers use DbSet property name as the default value so such behavior of InMemory provider is confusing.

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET Core 3.1 or .NET Standard 2.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by ajcvickers** [comment] 2020-01-30 17:02
Duplicate of #15015
See also #18457

**Closed** 2022-10-16 18:08 UTC
Labels: customer-reported
