### ISSUE TITLE
NullReferenceException on projection with custom method

### ISSUE THREAD

**Issue by SteffenMangold** [dotnet/efcore#13851] opened 2018-11-01 13:35 UTC
An NullReferenceException is throw if using custom method calls inside a SELECT projection.
This worked with all versions (including previews) before. 

```
Exception message:
Stack trace:
   bei Microsoft.EntityFrameworkCore.SqlServer.Query.ExpressionTranslators.Internal.SqlServerGeometryMethodTranslator.Translate(MethodCallExpression methodCallExpression)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   bei Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.RelationalCompositeMethodCallTranslator.Translate(MethodCallExpression methodCallExpression, IModel model)
   bei Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   bei Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   bei Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   bei Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitOrderByClause(OrderByClause orderByClause, QueryModel queryModel, Int32 index)
   bei Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   bei Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   bei Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   bei Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   bei Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   bei Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
   bei System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   bei System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   bei System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   bei Remotion.Linq.Parsing.RelinqExpressionVisitor.VisitNew(NewExpression expression)
   bei Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   bei Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   bei Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   bei Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   bei Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   bei Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   bei Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   bei Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   bei Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   bei Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   bei Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) 
```

### Steps to reproduce
The property `StartTime` is a simple not nullable DateTime.

```c#
var result = model.Events
	.Where(e => e.ID == eventID)
	.Select(e => new
	{
		ID = e.ID
		StartTimeEpoche = s.StartTime.ToUnixTime(),
	});
```

In debug mode I can see that the `ToUnixTime` is called for every result, but after all results the exception is thrown. In all tests the `DateTime value` parameter was never NULL.

```c#
public static long ToUnixTime(this DateTime value)
{
	DateTime epochBase = new DateTime(1970, 1, 1, 0, 0, 0, value.Kind);

	long unixTimestamp = value.Ticks - epochBase.Ticks;
	unixTimestamp /= TimeSpan.TicksPerSecond;
	return unixTimestamp;
}
```

### Further technical details
EF Core version: 2.2.0-preview3-35497
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
IDE: Visual Studio 2017 15.4

**Comment by smitpatel** [comment] 2018-11-01 15:42
Duplicate of #13686

**Closed** 2022-10-16 13:38 UTC
Labels: customer-reported
