### ISSUE TITLE
Linq Navigation join with nullable FK loads ALL(redundant) columns from second table.

### ISSUE THREAD

**Issue by borisdj** [dotnet/efcore#8191] opened 2017-04-17 16:26 UTC
Only one column from second table is specified for join, but when query is analysed from SqlProfiler it selects all columns.

### Steps to reproduce
Main Table
```c#
User
	Guid UserId (PK)
	string Email
	string FullName
	Guid? PartyId (FK nullable)
```
Join Table 
```c#
Party
	Guid PartyId (PK)
	string Name
	string Desc
	string SomeInfo
```
Linq:
```c#
var users = userRepos.Query().Where(a => !a.Deleted).OrderBy(u => u.UserId).Skip(0).Take(10);
var query = from u in users
            select new UserModel
	    {
	        UserId =  = u.UserId,
	        Email = u.Email,
		FullName = u.FullName,
		PartyId = u.PartyId,
		PartyName = u.Party.Name,
	    };
```
Profiler:
```c#
SELECT [dto.Party].[PartyId], [dto.Party].[Name], [dto.Party].[Desc], [dto.Party].[SomeInfo],
[t].[UserId], [t].[FullName], [t].[Email], [t].[PartyId]
FROM (
    SELECT [u0].*
    FROM [dbo].[User] AS [u0]
    WHERE [u0].[Deleted] = 0
    ORDER BY [u0].[UserId]
    OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
) AS [t]
LEFT JOIN [fin].[Party] AS [dto.Party] ON [t].[PartyId] = [dto.Party].[PartyId]
ORDER BY [t].[PartyId]
```

Columns **Desc** and **SomeInfo** should NOT be in query.
This showcase was simplified just to emphasis the issues.
In real scenario Party table has much more columns and some tables have more then one nullable FK, so I don't want all those column loaded from DB when I do not need them.

I am actually using AutoMapper instead of manually mapping these Properties but generated query is same in both cases. Showcase is with manual mapping just to point that it's not because of AM.

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment] 2017-04-17 18:16
@maumar to find the dupe.

**Comment by maumar** [comment] 2017-04-17 20:20
dupe of https://github.com/aspnet/EntityFramework/issues/6647

**Comment by borisdj** [comment] 2017-04-17 20:50
So it is already fixed, great.
Thx for quick response.

**Comment by maumar** [comment] 2017-04-17 21:44
@borisdj on our current bits the following SQL is generated for this scenario:

```sql
SELECT [a].[UserId], [a].[Email], [a].[FullName], [a].[PartyId], [a.Party].[Name]
FROM [Users] AS [a]
LEFT JOIN [Parties] AS [a.Party] ON [a].[PartyId] = [a.Party].[PartyId]
WHERE [a].[Deleted] = 0
ORDER BY [a].[UserId]
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
```

**Comment by borisdj** [comment] 2017-04-18 06:31
That SQL looks much better.

**Closed** 2022-10-16 11:01 UTC
