### ISSUE TITLE
SQLite Query: Translate string.Join and Concat

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#28100] opened 2022-05-25 18:39 UTC
These can be translated into the `group_concat` aggregate function.

.NET | SQL
--- | ---
string.Concat(values) | group_concat($values, '')
string.Join(separator, values) | group_concat($values, $separator)

**Comment by roji** [comment] 2022-05-25 18:58
Note slight discrepancy between string.Join and group_concat, as group_concat filters out nulls but the string.Join doesn't - you get an empty string. So to get a faithful translation, we'd need to coalesce to empty string.

**Comment by roji** [comment] 2022-05-25 20:59
Poaching (in case it wasn't abundantly clear :sweat_smile:)

**Comment by roji** [comment] 2022-05-25 21:09
Same as SQL Server (https://github.com/dotnet/efcore/issues/2981#issuecomment-1137788683):

<details>
<summary>Null semantics of group_concat</summary>

```sql
DROP TABLE IF EXISTS data;
CREATE TABLE data
(
    id INT PRIMARY KEY,
    name TEXT
);

-- Simple sample
INSERT INTO data (name) VALUES ('foo'), ('bar');
SELECT group_concat(name, ', ') FROM data; -- foo, bar

-- NULLs are ignored and the corresponding separator is not added
DELETE FROM data WHERE 1=1;
INSERT INTO data (name) VALUES ('foo'), (NULL), ('bar');
SELECT group_concat(name, ', ') FROM data; -- foo, bar

-- NULLs only results in NULL
DELETE FROM data WHERE 1=1;
INSERT INTO data (name) VALUES (NULL);
SELECT group_concat(name, ', ') FROM data; -- NULL

-- Empty table results in NULL
DELETE FROM data WHERE 1=1;
SELECT group_concat(name, ', ') FROM data; -- NULL
```

</details>

**Comment by roji** [comment] 2022-05-25 21:41
Duplicate of #2981

**Comment by roji** [comment] 2022-05-25 21:41
Doing this as part of #2981

**Closed** 2022-10-16 20:35 UTC
