### ISSUE TITLE
Feature: Add the <auto-generated> comment in migration files

### ISSUE THREAD

**Issue by Davilink** [dotnet/efcore#9915] opened 2017-09-27 23:19 UTC
Hi,

Could it be possible to add the comment : // < auto-generated >
in the top of the migration files and in the ModelSnapshot file. 

We use StyleCopAnalyzer and sadly we can't exclude a folder, so we manually add that comment to prevent the analyzer to analyze these files. 

The problem is when we add a migration, we have to manually add the comment, and what is more frustrating is when we remove a migration, the CLI recreate the model snapshot file, and we have to add the comment again. 

Plus, it is an auto generated file.

I saw an issue is open for roslyn to be able to ignore with a configuration, but it from 2015 and i don't think that will be fix in near future. https://github.com/dotnet/roslyn/issues/3705

**Comment by bricelam** [comment] 2017-09-28 15:45
Done in 2.0.0. Duplicate of #7189.

**Comment by bricelam** [comment] 2017-09-28 15:47
(But if there are still violations you'd like to see fixed, let us know and we'll consider them.)

**Closed** 2022-10-16 11:51 UTC
Labels: closed-duplicate
