### ISSUE TITLE
Include not generating join query for Lists

### ISSUE THREAD

**Issue by Jonatthu** [dotnet/efcore#9173] opened 2017-07-13 19:58 UTC
Using EF Core 1.1.2

My classes look like this

```
public class User {
    public Id {get;set;}
    public List<UserPost> UserPosts {get;set;}
}
public class Post {
    public Id {get;set;}
    public List<UserPost> UserPosts {get;set;}
}

public class UserPost {
    public User User {get;set;}
    public Post Post {get;set;}
    public int UserId {get;set;}
    public int PostId {get;set;}
}
```

My DbContext

```
public DbSet<User> Users { get; set; }
public DbSet<Post> Posts { get; set; }



    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<UserPost>()
            .HasKey(t => new { t.PostId, t.UserId });

        modelBuilder.Entity<UserPost>()
            .HasOne(pt => pt.Post)
            .WithMany(p => p.UserPost)
            .HasForeignKey(pt => pt.PostId);

        modelBuilder.Entity<UserPost>()
            .HasOne(pt => pt.User)
            .WithMany(t => t.UserPost)
            .HasForeignKey(pt => pt.UserId);
    }


```

Then when I call my query

// User Repository
`query = query.Include(x => x.UserPosts)`
This only generates SQL queries for one-to-one or just to get the user table, but not to join
one-to-many and many-to-many

Other issue is that `.ThenInclude` is giving me the same Lists and not the properties of the list, is that normal?

**Comment by smitpatel** [comment] 2017-07-13 20:05
For reference include, we join the both tables and fetch all data together with single query.
For case of Collection include, we do 2 separate queries. First query will get all parent data. And second query will get related data filtered based on parent data.

> Other issue is that .ThenInclude is giving me the same Lists and not the properties of the list, is that normal?
dupe of https://github.com/aspnet/EntityFramework/issues/4117
External issue in Roslyn https://github.com/dotnet/roslyn/issues/8237

**Comment by Jonatthu** [comment] 2017-07-13 20:10
@smitpatel I'm tracing SQL and is not doing the second query, only the parent one, or you mean the developer should call the collection in a separate service?

**Comment by Jonatthu** [comment] 2017-07-13 20:30
@smitpatel  Seems like only will generate the s

**Comment by smitpatel** [comment] 2017-07-13 21:26
@Jonatthu - Hey did you figure out what was happening?

**Comment by Jonatthu** [comment] 2017-07-13 21:49
@smitpatel Looks like only generates the second query when the first one finds results, so yes thanks!

**Closed** 2022-10-16 11:11 UTC
Labels: closed-no-further-action
