### ISSUE TITLE
TPH with a required Owned Type generates not-null columns

### ISSUE THREAD

**Issue by lakeman** [dotnet/efcore#23695] opened 2020-12-15 23:53 UTC
Adding a required owned type overrides the nullable status of columns on a sub-class in a table per-hierarchy. 

```c#
public class Owned
{
    public int Required { get; set; }
}

public abstract class BaseType
{
    public int Id { get; set; }
    public int Type { get; set; }
}

public class SubType : BaseType
{
    public int AlsoRequired { get; set; }
    public Owned Owned { get; set; }
}

void OnModelCreating(ModelBuilder builder)
{
    builder.Entity<BaseType>(e => {
        e.HasKey(b => b.Id);

        e.HasDiscriminator(b => b.Type)
            .HasValue<SubType>(1);
    });

    builder.Entity<SubType>(e =>
    {
        e.OwnsOne(e => e.Owned);
        e.Navigation(e => e.Owned)
            .IsRequired();
    });
}
```

I believe that BaseType.Owned_Required and BaseType.AlsoRequired should both be nullable. But a migration created with EF Core 5.0.1;

```c#
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.CreateTable(
        name: "BaseType",
        columns: table => new
        {
            Id = table.Column<int>(type: "int", nullable: false)
                .Annotation("SqlServer:Identity", "1, 1"),
            Type = table.Column<int>(type: "int", nullable: false),
            AlsoRequired = table.Column<int>(type: "int", nullable: true),
            Owned_Required = table.Column<int>(type: "int", nullable: false)
        },
        constraints: table =>
        {
            table.PrimaryKey("PK_BaseType", x => x.Id);
        });
}
```

**Comment by AndriySvyryd** [comment] 2020-12-16 03:01
Dupe of https://github.com/dotnet/efcore/issues/23479

**Closed** 2022-10-16 19:15 UTC
Labels: customer-reported
