### ISSUE TITLE
InMemory provider with data (via HasData()) fails when .EnsureCreated() is called on it

### ISSUE THREAD

**Issue by salaros** [dotnet/efcore#16944] opened 2019-08-04 18:31 UTC
In previous stable EF Core version (2.2.6) one could safely spawn as many InMemory context as need with pre-seeded data by using

```c#
DbContext.Database.EnsureDeleted();
DbContext.Database.EnsureCreated();
```

However in 3.0.0 preview 7 `.EnsureCreated()` seems to re-seed already seeded database. 
My tests in [this solution](https://github.com/salaros/dotnet-ef-3.0-preview7-regressions) demonstrate it.

![image](https://user-images.githubusercontent.com/675348/62427483-642a0500-b6fc-11e9-9a47-dae75fc4e99e.png)

### Steps to reproduce
Please take a look `ProviderNotCleaned` project in [this solution](https://github.com/salaros/dotnet-ef-3.0-preview7-regressions) and `InMemoryTests.ProviderNotCleaned()` xUnit test.

```c#
public class UniqueIdModel
{
    [NotMapped]
    [Required, Column(Order = 0), MinLength(36), MaxLength(36)]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid UniqueId { get; set; }
}

// ...

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
	modelBuilder
	    .Entity<UniqueIdModel>()
	    .HasKey(u => u.UniqueId);
	
	modelBuilder
	    .Entity<UniqueIdModel>()
	    .HasIndex(u => u.UniqueId)
	    .IsUnique();
	
	modelBuilder
	    .Entity<UniqueIdModel>()
	    .Property(u => u.UniqueId)
	    .HasConversion(new GuidToStringConverter());
	
	modelBuilder
	    .Entity<UniqueIdModel>()
	    .HasData(
	        new UniqueIdModel{ UniqueId = new Guid("8ac4b5f4-eac9-4fc7-b7a4-6a3ba0ae3556") },
	        new UniqueIdModel{ UniqueId = new Guid("509f3452-649f-4255-abb4-3608f3aa25db") }
	    );
}
```

### Further technical details
EF Core version: 3.0.0-preview7.19362.6
Database Provider: any (InMemory cannot be used for test, because it ignores `IsRequired()`)
Operating system: any
IDE: Visual Studio 2019 16.2

**Comment by ajcvickers** [comment] 2019-08-05 16:08
Duplicate of #16025

**Closed** 2022-10-16 14:33 UTC
Labels: customer-reported
