### ISSUE TITLE
'SingleOrDefault()' could not be translated and will be evaluated locally

### ISSUE THREAD

**Issue by matthiaslischka** [dotnet/efcore#17958] opened 2019-09-20 13:15 UTC
I know this has been around some times but I'm not sure if that shouldn't work:

I want a specific game and its winner
```csharp
var gameDto = context.Games.Where(x => x.Id == 1).Select(x => new GameDto
{
	Name = x.Name,
	Winner = x.Players.Where(y => y.IsWinner).Select(y => new PlayerDto
	{
		Name = y.Name
	}).SingleOrDefault()   // <-- QueryClientEvaluationWarning
}).Single();
```

I tried different variations to circumvent the problem (that I do not understand really).

```csharp
var gameDto = context.Games.Where(x => x.Id == 1).Select(x => new GameDto
{
	Name = x.Name,
	Winner = MapPlayer(x.Players.First( y => y.IsWinner))  // <-- QueryClientEvaluationWarning with First()
}).Single();

// ----

public static PlayerDto MapPlayer(Player player)
{
	return new PlayerDto { Name = player.Name };
}
```

What would be the correct/cleanest way to get this with one single request and without the QueryClientEvaluationWarning to be fired?

Why does that not work?

### Further technical details

EF Core version: 2.2.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 2.2

Thanks a lot and BR Matthias

**Comment by smitpatel** [comment] 2019-09-20 15:45
Duplicate of #15559

In 2.x release, use FirstOrDefault. In all other cases, we end up doing client eval just to throw exception like how linq-2-object would throw. So FirstOrDefault allows server translation. In 3.0 we changed it so that all those operator evaluates to server if they are in a subquery and only mimic throwing behavior on top level so that there is no client side eval.

**Comment by matthiaslischka** [comment] 2019-09-20 15:58
I could have sworn that I tested `FirstOrDefault` too, but you are right. Works with that.
Thanks a lot!

**Closed** 2022-10-16 14:43 UTC
Labels: closed-no-further-action, customer-reported
