### ISSUE TITLE
Properties on owned types do not respect IsRequired()

### ISSUE THREAD

**Issue by AndrewGriffithsFG** [dotnet/efcore#16552] opened 2019-07-10 15:32 UTC
### Description
Properties on owned types are nullable in the database even when `IsRequired()` is set.

### Steps to reproduce

With the follwing entities

```c#
public class Parent
{
    public int Id { get; set; }
    public OwnedType OwnedProperty { get; set; }
    
    public int ParentRequiredInt { get; set; }
    public string ParentRequiredString { get; set; }
}

public class OwnedType
{
    public int OwnedRequiredInt { get; set; }
    public string OwnedRequiredString { get; set; }
}
```

and the following configuration

```c#
modelBuilder.Entity<Parent>(entity =>
{
    entity.Property(x => x.ParentRequiredInt).IsRequired();
    entity.Property(x => x.ParentRequiredString).IsRequired();
    
    entity.OwnsOne(x => x.OwnedProperty, y =>
    {
        y.Property(a => a.OwnedRequiredInt).IsRequired();
        y.Property(a => a.OwnedRequiredString).IsRequired();
    });
});
```

Generating the migration results in:

![image](https://user-images.githubusercontent.com/43203074/60982497-2968c300-a330-11e9-82f6-ee79e280ad21.png)

The required properties on `Parent` have `nullable: false` as expected, but the required properties on `OwnedType` are `nullable: true`.

### Further technical details
EF Core version: 3.0.0-preview5
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.2 Preview 3

**Comment by smitpatel** [comment] 2019-07-10 16:58
Owned properties are optional. i.e. For given parent, `OwnedProperty` may be null. That is represented in database using null values in those columns hence you see database column being created as nullable. EF will create on client side as required for them. (If you notice `OwnedType.OwnedRequiredInt` is int type so it is never going to take null as values anyway)

**Comment by ajcvickers** [comment] 2019-07-10 19:31
@smitpatel @AndriySvyryd Isn't this a duplicate of #15607

**Comment by smitpatel** [comment] 2019-07-10 19:59
@ajcvickers - Reading the post, I don't feel they are duplicate. It is the same mismatch, when you put is `IsRequired` on a property on derived type but migration still generates a nullable column.

**Comment by AndrewGriffithsFG** [comment] 2019-07-11 08:59
The issue is with inconsistency.
An `int` property on `Parent` does not allow null values and generates a non-nullable column by default.
An `int` property on `OwnedType` does not allow null values and generates a _nullable_ column by default, and still generates a nullable column when `IsRequired` is set.

If this is expected behaviour, then it should not be possible to set `IsRequired` on owned types as it causes confusion.

**Comment by AndriySvyryd** [comment] 2019-07-11 18:37
@AndrewGriffithsFG This is expected. As you said setting `IsRequired` means the null values aren't allowed for that property. But the owned type itself is still optional. With #15607 it would be possible to make the owned navigation required as well resulting in non-nullable columns for required properties.

**Comment by ajcvickers** [comment] 2019-07-11 19:13
Commented on #15607, and now agree this should be closed.

**Closed** 2022-10-16 14:30 UTC
Labels: closed-no-further-action, customer-reported
