### ISSUE TITLE
Simple where clause in Referenced Entity not emmitted

### ISSUE THREAD

**Issue by chrisaut** [dotnet/efcore#6477] opened 2016-09-06 02:10 UTC
I have a simple Model

``` C#
    public class Blog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public IList<Article> Articles { get; set; }    
    }

    public class Article
    {
        public int Id { get; set; }
        public Blog Blog { get; set; }
    // more properties
    }

    public class BlogDbContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Article> Articles { get; set; }
        public DbSet<Author> Authors { get; set; }

        public BlogDbContext(DbContextOptions options) : base(options)
        {
        }
   }
```

When I do a simple query for all articles in a blog by name, like

``` C#
dbContext.Articles.Where(b => b.Blog.Name == blogName).ToList();
```

the emmitted SQL does not include the condition.

``` SQL
SELECT [a].[Id], [a].[AuthorId], [a].[BlogId], [a].[Content], [a].[CreateDate], [a].[ModifiedDate], [a].[PublishDate], [a].[Tags], [a].[Title], [a.Blog].[Id], [a.Blog].[Name]
FROM [Articles] AS [a]
LEFT JOIN [Blogs] AS [a.Blog] ON [a].[BlogId] = [a.Blog].[Id]
ORDER BY [a].[BlogId]
```

Instead it seems to do it in memory (result is still correct).

Is this a known limitation or am I doing something wrong?
### Further technical details

EF Core version: (found in project.json or packages.config) "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
Operating system: Win10 x64 14393
Visual Studio version: VS2015 Pro Update 3

**Comment by smitpatel** [comment] 2016-09-06 06:15
`Article.Blog` is optional navigation hence it causes client side evaluation.
Dupe of #4588

**Comment by chrisaut** [comment] 2016-09-06 06:29
I see...thank you. I couldnt find anything (wasn't sure what to search for tbh)

**Closed** 2022-10-16 09:56 UTC
