### ISSUE TITLE
Question: How to scaffold only few tables in DB first approach in EF Core.

### ISSUE THREAD

**Issue by codingonHP** [dotnet/efcore#7930] opened 2017-03-18 05:12 UTC
I am trying to do database first development in EF Core 1.1. I am following https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db to do so. What I am guessing from the command 
**Scaffold-DbContext "Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models**
is that it will generate DbContext containing all the tables in the database. My current database is having over 1000 tables and I do not need all of them for the current project. Is there a way to target only specific tables that I need during the scaffolding process?
Also, do I need to scaffold tables at all if I only need to execute Stored Procedures? Can anyone guide me on this?

**Comment by ErikEJ** [comment] 2017-03-18 06:36
For the selecting tables issue, you can use my (unofficial) VS Tool to generate the code, and it has a UI for selecting tables:  https://twitter.com/ErikEJ/status/834405829889638402

**Comment by codingonHP** [comment] 2017-03-18 08:45
@ErikEJ Thanks :)
Any thoughts on 

> Also, do I need to scaffold tables at all if I only need to execute Stored Procedures? Can anyone guide me on this?

**Comment by ErikEJ** [comment] 2017-03-18 11:45
@codingonHP Yes: why use EF Core if you only need to execute stored procedures?
If the stored procedures return results, you need some classes in your DbContext to map them to, and if they match some of your tables, then scaffolding makes sense...

**Comment by ajcvickers** [comment] 2017-03-20 18:04
@lajones Can you point @codingonHP to the documentation to do this without Erik's tool? (If we need to improve the docs, then let's make sure there is an issue for that.)

**Comment by ErikEJ** [comment] 2017-03-20 18:09
@ajcvickers The main issue is that the current tools /command line only allows you to specify "exclusions", not "inclusions"

**Comment by lajones** [comment] 2017-03-20 18:47
@codingtonHP - the docs on Scaffold-DbContext are [here](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#scaffold-dbcontext). Specifically you can include just a specific set of tables or all the tables from a specific set of schemas. See the `-Tables` and `-Schemas` flags in the documentation.

@ErikEJ - I think you meant the command-line tool only allows **inclusions** not **exclusions**.

**Comment by ErikEJ** [comment] 2017-03-20 18:56
@lajones Sorry, yes!

**Comment by ajcvickers** [comment] 2017-03-20 18:58
@divega Is this documentation okay, or should we make it more prominent?

**Comment by lajones** [comment] 2017-03-20 19:30
@divega @ajcvickers I would like to put the whole section under `Tools & Extensions` as well as / instead of under `Miscellaneous`. At least that's where I first looked for it. (That said, the things currently under `Tools & Extensions` look very different - so maybe we need to rename one or more of the sections?)

**Comment by ErikEJ** [comment] 2017-03-20 20:14
How about moving the command line reference a level up, so it is the same level in TOC as API Reference (it is a large part of the EF Core surface)

**Comment by lajones** [comment] 2017-04-03 23:52
I've opened https://github.com/aspnet/EntityFramework.Docs/issues/375 to track the docs issue. Am closing this as, @codingonHP, I think we have answered your question.

**Comment by ntgnst** [comment] 2017-10-20 09:18
Well , how can i costomize modelBuilder on model creating for Auto Increment properties and how add ValueGenerateOnAdd() method for all models best practise.
Thanks

**Comment by ajcvickers** [comment] 2017-10-20 17:08
@ntgnst When reverse engineering an existing database, the scaffolding tool should configure properties to be store-generated auto-incrementing if they are setup that way in the database. (However, note that for numeric keys, the default behavior in EF is to use store-generated keys, so this is not written out to OnModelCreating because it happens by convention anyway.)

If you are finding a case where the model generated does not match the database, then please file a new issue with full details and a code listing or project that will let us reproduce what you are seeing.

**Comment by dazbradbury** [comment] 2019-12-05 21:59
> @codingtonHP - the docs on Scaffold-DbContext are [here](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#scaffold-dbcontext). Specifically you can include just a specific set of tables or all the tables from a specific set of schemas. See the `-Tables` and `-Schemas` flags in the documentation.
> 
> @ErikEJ - I think you meant the command-line tool only allows **inclusions** not **exclusions**.

Will there ever be an **exclusions** flag? I can see arguments for both - just wondering if the decision is fixed at this point?

**Comment by zhangxuan1107** [comment] 2020-02-25 02:51
like this:

**Comment by zhangxuan1107** [comment] 2020-02-25 02:51
Scaffold-DbContext "Database=netchargedb_new;Data Source=127.0.0.1;User Id=root;Password=1234;CharSet=utf8;port=3306" MySql.Data.EntityFrameworkCore -tables t_menu,t_menu_power -OutputDir Models -f

**Closed** 2022-10-16 10:57 UTC
Labels: closed-no-further-action
