### ISSUE TITLE
LINQ: comparisonType: OrdinalIgnoreCase.. could not be translated

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#20659] opened 2020-04-16 15:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/989327/linq-comparisontype-ordinalignorecase-could-not-be.html)._

---
I'm on VS2019 . NetCore 3.1 and i'm getting error when i use comparisontype in  the LINQ:

InvalidOperationException: The LINQ expression 'DbSet<Table1> . Where(j => j.Cat == __cat_0 && j.Req.IndexOf( value: __req_1, comparisonType: OrdinalIgnoreCase) != -1 && !( j.Deleted))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync().

The code was originally from . NetCore 2.2.x and no problem with the LINQ.

My Temporary solution:
j.Req.ToUpper(). IndexOf(req. ToUpper())

---
#### Visual Studio Feedback System on 4/14/2020, 01:38 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2020-04-17 16:41
Duplicate of #1222

**Closed** 2022-10-16 18:21 UTC
Labels: customer-reported
