### ISSUE TITLE
Many to many: can not resolve other "many" side

### ISSUE THREAD

**Issue by simonachmueller** [dotnet/efcore#14736] opened 2019-02-19 08:55 UTC
I have many to many relation, in my sample it is Person <-> PersonPhoto <-> Photo
When I load Person entities, I want to filter out some entities based on data in the other side (Photo).

To do that I have a function 
```c#
Func<Person, bool> hasDescription = x => x.PersonPhotos!= null 
                                      && x.PersonPhotos.Any() 
                                      && x.PersonPhotos.Any(p => p.Photo.Description == "123");
```

When I load data such way:
```c#
var photos = db.Persons
             .Include(p => p.PersonPhotos)
             .ThenInclude(pp => pp.Photo)
             .Where(hasDescription);
Console.WriteLine(photos.Count());
```
my function gets filled Photo entities and I can see 1 in the console window, but when I do it such way
```c#
var photos = db.Persons
             .Include(p => p.PersonPhotos)
             .ThenInclude(pp => pp.Photo)
             .Where(x => hasDescription(x));
Console.WriteLine(photos.Count());
```
it does not (x.PersonPhotos list is null) and I see 0 in the console.

### Steps to reproduce

Person is
```c#
public class Person
{
	public int Id { get; set; }
	public List<PersonPhoto> PersonPhotos { get; set; }
}
```
PersonPhoto
```c#
public class PersonPhoto
{
	public int Id { get; set; }
	public int PhotoId { get; set; }
	public Photo Photo { get; set; }

	public int PersonId { get; set; }
	public Person Person { get; set; }
}
```
Photo
```c#
public class Photo
{
	public int Id { get; set; }
	public string Description { get; set; }
	public List<PersonPhoto> PersonPhotos { get; set; }
}
```
DbContext
```c#
public class SandboxDbContext : DbContext
{
	public SandboxDbContext(DbContextOptions<SandboxDbContext> argOptions):base(argOptions)
	{
		
	}
	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<PersonPhoto>().HasKey(x => new { x.PersonId, x.PhotoId});
	}


	public DbSet<Person> Persons { get; set; }
	public DbSet<Photo> Photos { get; set; }
}
```

Test code:
```c#
class Program
{
	static void Main(string[] args)
	{
		var connection = new SqliteConnection("DataSource=:memory:");
		connection.Open();

		var options = new DbContextOptionsBuilder<SandboxDbContext>()
					  .UseSqlite(connection)
					  .Options;


		using (var db = new SandboxDbContext(options))
		{
			db.Database.EnsureCreated();
		}

		using (var db = new SandboxDbContext(options))
		{
			db.Add(new Person());
			var photo = new Photo
			{
				Description = "123"
			};

			var person = new Person();

			var personPhoto = new PersonPhoto
			{
				Person = person, 
				Photo = photo
			};
			
			db.Add(personPhoto);

			db.SaveChanges();
		}

		using (var db = new SandboxDbContext(options))
		{
			Func<Person, bool> hasDescription = x => x.PersonPhotos.Any() && x.PersonPhotos.Any(p => p.Photo.Description == "123");
			var photos = db.Persons
						   .Include(p => p.PersonPhotos)
						   .ThenInclude(pp => pp.Photo)
						   .Where(x => hasDescription(x));
						   
			Console.WriteLine(photos.Count());
		}
	}
}
```

```c#

```
### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Win10
IDE: Visual Studio 2017 15.9.5

**Comment by smitpatel** [comment] 2019-02-19 19:27
Duplicate of #10471

You are using `Func<Person, bool>` which causes client eval. Considering using `Expression<Func<Person, bool>>`. With that EF can translate the predicate to server too.

**Closed** 2022-10-16 13:52 UTC
Labels: customer-reported
