### ISSUE TITLE
Join with non-anonymous type followed by GroupBy cannot be translated

### ISSUE THREAD

**Issue by byrnedo** [dotnet/efcore#13077] opened 2018-08-22 12:33 UTC
If I do a `Join` and project to something other than an anonymous object and then do a `GroupBy`, this groupby gets evaluated locally.

```
: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'GroupBy(new <>f__AnonymousType0`1(BrandName = [b].BrandName), new GroupedResult() {BrandName = [b].BrandName, Vin = [c].Vin, Rating = [b].Rating})' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'Count()' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'Count()' could not be translated and will be evaluated locally.
```

### Steps to reproduce

F
```c#

class Program {
        class GroupedResult {
            public string BrandName {get;set;}
            public int Rating {get;set;}
            public string Vin {get;set;}
        }


        class MyTestContext : DbContext {
            public virtual DbSet<Brand> Brands {get;set;}

            public class Brand {
                [Key]
                public string BrandName {get;set;}
                public int Rating {get;set;}
            }

            public class Car
            {
                [Key]
                public int Key { get; set; }

                [Required]
                [StringLength(8)]
                public string Vin { get; set; }

                [Required]
                public string Year { get; set; }

                [Required]
                public string Brand { get; set; }

                [Required]
                public string Color { get; set; }

                [Required]
                public DateTime DateLastModified { get; set; }
            }

            public static readonly LoggerFactory MyLoggerFactory = new LoggerFactory(new[] { new ConsoleLoggerProvider((filter, includeScopes) => true, true) });

            public virtual DbSet<Car> Cars { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseLoggerFactory(MyLoggerFactory); // Warning: Do not create a new ILoggerFactory instance each time 
                optionsBuilder.EnableSensitiveDataLogging();

                optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=CarsEF20;Trusted_Connection=True;");
            }
        }

       

        static void Main(string[] args)
        {
           

            var config = ParsingConfig.DefaultEFCore21;
            config.CustomTypeProvider = new C();

            var context = new MyTestContext();

            //context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var dateLastModified = new DateTime(2018, 1, 15);

            if (!context.Brands.Any())
            {
                context.Brands.Add(new MyTestContext.Brand { BrandName = "Ford", Rating = 9});
                context.Brands.Add(new MyTestContext.Brand { BrandName = "Fiat", Rating = 6});
                context.Brands.Add(new MyTestContext.Brand { BrandName = "Alfa", Rating = 4});
                context.SaveChanges();

            }
            if (!context.Cars.Any())
            {
                context.Cars.Add(new MyTestContext.Car { Brand = "Ford", Color = "Blue", Vin = "yes", Year = "2017", DateLastModified = dateLastModified });
                context.Cars.Add(new MyTestContext.Car { Brand = "Fiat", Color = "Red", Vin = "yes", Year = "2016", DateLastModified = dateLastModified.AddDays(1) });
                context.Cars.Add(new MyTestContext.Car { Brand = "Alfa", Color = "Black", Vin = "no", Year = "1979", DateLastModified = dateLastModified.AddDays(2) });
                context.Cars.Add(new MyTestContext.Car { Brand = "Alfa", Color = "Black", Vin = "a%bc", Year = "1979", DateLastModified = dateLastModified.AddDays(3) }); ;
                context.SaveChanges();
            }


            // Gets evaluated locally
            var g3 = context.Cars.Join(context.Brands, c => c.Brand, b => b.BrandName, (c,b) => new GroupedResult{BrandName = b.BrandName, Vin = c.Vin, Rating = b.Rating})
            .GroupBy(x => new {x.BrandName}).Select(x => new{ Brand= x.Key.BrandName, CountValue2 = x.Count() }).ToDynamicList();
            Console.WriteLine("GroupBy @ database {0}", JsonConvert.SerializeObject(g3, Formatting.Indented));

            // works
            var g4 = context.Cars.Join(context.Brands, c => c.Brand, b => b.BrandName, (c,b) => new {BrandName = b.BrandName, Vin = c.Vin, Rating = b.Rating})
            .GroupBy(x => new {x.BrandName}).Select(x => new{ Brand= x.Key.BrandName, CountValue2 = x.Count() }).ToDynamicList();
            Console.WriteLine("GroupBy @ database {0}", JsonConvert.SerializeObject(g3, Formatting.Indented));
        }
}

```

### Further technical details
EF Core version:  2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: mac
IDE: vscode

**Comment by smitpatel** [comment] 2018-08-23 19:31
By design.

When you create a object of Concrete type, we don't know what would be the value of property without creating the object. e.g.
```C#
public class MyDto
{
    private double _price;

    public double Price
    {
        get { return _price; }
        set
        {
            _price = value * 0.90;
        }
    }
}
```
As you can see we cannot replace MyDto.Price with the value of price we were assigning because we don't know what custom transformation happening inside concrete object.
For anonymous types there are not custom transformations possible. So we can just replace the property access with member assignment earlier.

**Comment by smitpatel** [comment] 2018-08-24 18:30
@byrnedo - Only possible option I can think of right now is Anonymous Type. We allow anonymous types to go through seamless because they are nice blocks to carry a group of properties.

Is there a reason you want to use POCO? (Since your poco is not in final results)

**Comment by ajcvickers** [comment] 2018-08-27 18:51
@divega @smitpatel to look for related issue.

**Comment by byrnedo** [comment] 2018-08-28 06:47
@smitpatel 
My use case is that I build up the query in several stages (each being a class/function).

The first stage is the `from` and `join` clauses.
Second stages applies the `where`.
Third stage applies the `select`, `group by` and `order by`.

I wanted to be able to pass a typed `IQueryable` from the first stage to the second stage.

My workaround right now is to do all the joins as properties of an entity instead, which is possibly more correct anyway.

**Comment by smitpatel** [comment] 2018-08-28 16:59
Related issue #8107

**Comment by ajcvickers** [comment] 2018-08-29 22:54
After further discussion in triage, closing this as duplicate of #8107

**Closed** 2022-10-16 13:26 UTC
Labels: closed-duplicate, customer-reported
