### ISSUE TITLE
System.ArgumentOutOfRangeException: Index was out of range when using AsSplitQuery()

### ISSUE THREAD

**Issue by Gua-naiko-che** [dotnet/efcore#26464] opened 2021-10-26 11:42 UTC
**REMARK:** this issue seems closely related to https://github.com/dotnet/efcore/issues/23311 and https://github.com/dotnet/efcore/issues/25680

An ArgumentOutOfRangeException is launched when running the following code, which uses `AsSplitQuery`:

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
class Program
{
    static void Main(string[] args)
    {
        using (var db = new MyContext())
        {
            var linqQuery = db.Skills
                .Include(s => s.Children)
                    .ThenInclude(c => c.Child)
                        .ThenInclude(s => s.Translations)
                .AsSplitQuery()
                .OrderBy(e => e.Id);
            var sqlQuery = linqQuery.ToQueryString();
        }
    }
}

public class MyContext : DbContext
{
     protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlServer("Server=.;Database=TestAsSplitQuery;Trusted_Connection=True");
    public DbSet<Skill> Skills { get; set; }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<SkillTranslation>(skillTranslation =>
        {
            skillTranslation.HasKey(t => new { t.SkillId, t.TenantId });
            skillTranslation.HasOne(p => p.Skill)
                            .WithMany(s => s.Translations)
                            .HasForeignKey(p => new { p.TenantId, p.SkillId });
        });
        modelBuilder.Entity<Skill>(skill =>
        {
            skill.HasKey(s => new { s.TenantId, s.Id });
            skill.Property(s => s.Id).ValueGeneratedOnAdd();
        });
        modelBuilder.Entity<SkillEdge>(skillEdge =>
        {
            skillEdge.HasKey(t => new { t.TenantId, t.ParentId, t.ChildId });
            skillEdge
                    .HasOne(ls => ls.Parent)
                    .WithMany(p => p.Children)
                    .HasForeignKey(ls => new { ls.TenantId, ls.ParentId })
                    .OnDelete(DeleteBehavior.Restrict);
        });
    }
}
public class SkillTranslation
{
    public Guid SkillId { get; set; }
    public Skill Skill { get; set; }
    public string TenantId { get; set; }
}
public class Skill
{
    public Guid Id { get; set; }
    public List<SkillEdge> Children { get; set; }
    public List<SkillTranslation> Translations { get; set; }
    public string TenantId { get; set; }
}
public class SkillEdge
{
    public Guid ParentId { get; set; }
    public Guid ChildId { get; set; }
    public Skill Parent { get; set; }
    public Skill Child { get; set; }
    public string TenantId { get; set; }
}
```

The problem is fixed with any these options:
- Remove the `AsSplitQuery`
- Remove the `OrderBy`
- Remove the `.ThenInclude(s => s.Translations)`
- Include the other part of the composite PK in the `OrderBy`: `.OrderBy(e => e.TenantId).ThenBy(e => e.Id)`

### Stack trace:

```
An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in System.Private.CoreLib.dll: 'Index was out of range. Must be non-negative and less than the size of the collection.'
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyCollectionJoin(Int32 collectionIndex, Int32 collectionId, Expression innerShaper, INavigationBase navigation, Type elementType, Boolean splitQuery)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToQueryString(IQueryable source)
   at Program.Main(String[] args) in C:\dev\learning\orderbycompositepk\Program.cs:line 19
```

### Provider and version information
EF Core version: 5.0.11
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10

**Comment by ajcvickers** [comment] 2021-11-02 13:15
Also works on 6.0.0-rtm.21519.8. @Gua-naiko-che Can you pleas try again and make sure you are using a recent 6.0 build, such as `6.0.0-rtm.21519.8`.

**Comment by ajcvickers** [comment] 2021-11-10 10:31
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:11 UTC
Labels: closed-duplicate, customer-reported
