### ISSUE TITLE
Error "The specified deps.json ... does not exist"

### ISSUE THREAD

**Issue by PureWeen** [dotnet/efcore#28335] opened 2022-06-28 17:49 UTC
Moved issue from https://github.com/dotnet/maui/issues/8114

### Description

When I create a new Net Maui APP Project in the Visual Studio 2022 17.3.0 Preview 2 and install EntityFramework 6, I always get the errormessage "The specified deps.json [C:\Users\matth\Desktop\Projekte\Test\bin\Debug\net6.0-android\Test.deps.json] does not exist" after entering "Enable-Migrations"

Everything works fine in Visual Studio 2022 17.2.4 in a WPF App

Dotnet Version:6.0.400-preview.22301.10

I uploaded the project to my github https://github.com/MatthiasBae/Error-deps.json

### Steps to Reproduce

1. Create new Net Maui APP Project
2. Install EntityFramework from Nuget Paket Manager
3. Enter "Enable-Migrations" into the PM Console

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 Version 21H2 Build 22000.675

### Relevant log output

```shell
PM> Enable-Migrations
The specified deps.json [C:\Users\matth\Desktop\Projekte\Test\bin\Debug\net6.0-android\Test.deps.json] does not exist
```

**Comment by ajcvickers** [comment] 2022-06-29 09:07
Duplicate of #16386.

**Closed by ajcvickers** 2022-06-29 09:07 UTC
Labels: customer-reported

**Comment by MAUIoxo** [comment] 2023-11-27 05:48
Please open it again this issue is still not solved with the Latest VS 17.9 Preview 1 and also .NET 8 in combination with .NET MAUI. I'm writing it here since the .NET MAUI Bug was closed as it is not related to MAUI, but we can't use it in a MAUI project. So please open it again

**Comment by leonedev** [comment] 2023-12-27 10:57
Same problem of @MAUIoxo, please FIX IT!

**Comment by KerryXEX** [comment] 2024-01-07 11:57
Also occurs when trying to create Migrations on latest MAUI project templat on macOS (ARM).

**Comment by smola93** [comment] 2024-01-29 17:51
This is another big issue on MAUI .NET 8 version, would it be reopened and fixed?

**Comment by Pakalo** [comment] 2024-05-23 12:37
Hello
Did someone found a solution for this problem cause i have same issue with mac os and Jetbrain Rider and nobody explain in the duplicated issue how to fix this in maui ?
Thank you

**Comment by JoseMarquesJM** [comment] 2024-07-28 19:34
Eu estou a ter o mesmo problema com o blazor e o Ef core

**Comment by Fludem** [comment] 2024-09-29 01:56
> Also occurs when trying to create Migrations on latest MAUI project templat on macOS (ARM).

Experience the same issue

**Comment by Fludem** [comment] 2025-01-02 00:23
@Arthri I agree. I also experienced this on MacOS (ARM). Android/iOS not targeted. Windows Target probably caused it in my situation. It was a while ago.

This problem and numerous others have made .NET MAUI unviable for any Desktop App. 
I understand this is beyond this issue, but I thought I'd mention it here.

I had several other issues with the tooling on MacOS. The problems would always be with using MAUI, targeting Windows, or both.

I spent 2-3 weeks on a project, and I can honestly say I probably spent 80% of that time-solving problems with Tooling or other issues that weren't the code I'd written.

**Comment by PulkitSethi1984** [comment] 2025-03-09 06:13
With such pathetic support, why don't you guys let go off this MAUI platform or just dont target it. Stuck for days impossible to move forward. Are we now suppose to write migrations by hand
