### ISSUE TITLE
Renaming tables fails (foreign keys)

### ISSUE THREAD

**Issue by ThomasPe** [dotnet/efcore#5753] opened 2016-06-14 11:42 UTC
### Steps to reproduce

I was trying to pluralize the table name from Dataset to Datasets using annotations.

``` c#
    [Table("Datasets")]
    public class Dataset
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
    }
```
### The issue

Creating the Migration file works, but on updating the database I get following error:

> Cannot find the object "Datasets" because it does not exist or you do not have permissions. 

Looking at the migration file this is due to the database being renamed after trying to recreate the foreign keys.

``` c#
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_DatasetPermission_Dataset_DatasetId",
                table: "DatasetPermission");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Dataset",
                table: "Dataset");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Datasets",
                table: "Datasets",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_DatasetPermission_Datasets_DatasetId",
                table: "DatasetPermission",
                column: "DatasetId",
                principalTable: "Datasets",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.RenameTable(
                name: "Dataset",
                newName: "Datasets");
        }

```

If you move the `RenameTable` just below the last `DropPrimaryKey`the update works just fine.
### Further technical details

``` c#
"Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc2-final",
"Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc2-final",
"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
"Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    },

```

Operating system: Windows 10
Visual Studio version: VS 2015 Update 2

Other details about my project setup: asp.net core 1 RC 2

**Comment by bricelam** [comment] 2016-06-14 16:01
This is a dupe of #3990 and should be fixed in the next release.

**Closed** 2022-10-16 09:45 UTC
