### ISSUE TITLE
SQL Default values being ignored by EF Core when using database first approach

### ISSUE THREAD

**Issue by markmcgookin** [dotnet/efcore#21121] opened 2020-06-03 08:42 UTC
When using EF core against and already created database, where there are NOT NULL columns with default values (as shown below) the default values are ignored if the corresponding property is present on the EF model when SaveChanges() is called after adding a new row

```sql
CREATE TABLE [Companies]
(
    [Id] [UNIQUEIDENTIFIER] NOT NULL DEFAULT NEWID(),
    [Name] [NVARCHAR](250) NOT NULL,
    [DummyData] [nvarchar](250) DEFAULT 'THIS IS DUMMY DATA' NOT NULL,
    CONSTRAINT [PK_Companies] PRIMARY KEY CLUSTERED 
    (
        [Id] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
```

``` C#
public class Company
{
    public Company() {}
    public Guid Id { get; set; }
    public string Name { get; set; }
    public string DummyData { get; set; }
}
```

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'DummyData', table 'dbo.Companies'; column does not allow nulls. INSERT fails.
```
However, if I leave "DummyData" off the Company class it saves fine and the default values are issued by SQL. 

Is this something that is done by design? Is there a way to set EF to use the DB default values? I'm actually surprised that EF is even able to trigger this, I assumed that the underlying SQL would trump a null insert. 

EF Core version: 3.1.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) SQL Server (Sql for linux, in a docker container)
Target framework: dotnet core 3.1
Operating system: mac os (sql on linux)
IDE: VS Code

**Comment by roji** [comment] 2020-06-03 09:07
@markmcgookin as a general rule, your EF Core model needs to correspond to your actual database schema - EF Core must be aware that your actual database column is required and has a default. Since it does not know this, it assumes you really want to insert a NULL value into DummyData (which makes sense for other scenarios), and triggers the exception.

You can configure the model appropriately by adding the following in your OnModelCreating:

```c#
modelBuilder.Entity<Company>().Property(b => b.DummyData)
    .IsRequired()
    .HasDefaultValue("THIS IS DUMMY DATA");
```

Since EF now knows the property has a default value, it will interpret a C# null as "unset" and will not send it to the database. In fact, it will also read back the database-generated value when inserting, and it should be populated on your entity after calling SaveChanges.

**Comment by markmcgookin** [comment] 2020-06-03 09:16
@roji thanks, I was just hoping that we could alter default values without having to redeploy our application code... it's much easier to just update the SQL table, which causes no app down time for us. Is this 'by-design' then?

**Comment by roji** [comment] 2020-06-03 09:41
@markmcgookin yes, this is by design - EF Core must have an accurate model of your schema, because that affects its behavior, as you can see above.

For people wanting their database to be the source of truth, it's common to [scaffold the code model from the database](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli), and to repeat the process after modifying your schema. You may want to consider doing that.

Am closing as by design, but don't hesitate to continue posting if you have further questions.

**Closed** 2022-10-16 18:28 UTC
Labels: closed-by-design, customer-reported
