### ISSUE TITLE
Crash when trying to AddRange to Db on Xamarin iOS

### ISSUE THREAD

**Issue by juripyykko** [dotnet/efcore#11188] opened 2018-03-08 13:28 UTC
I've got a NET-standard (2.0.1) Xamarin.Forms project using EF Core, and when I run this on an iPhone and try to add entries `dbContext.Courses.AddRange(courses)`, I get the exception below. The expected behavior would be that the courses were added to the database, and the MainPage got displayed. See the attached project at the bottom of this post.

This seems to be similar to:
https://github.com/aspnet/EntityFrameworkCore/issues/9249
https://github.com/aspnet/EntityFrameworkCore/issues/10206

However, according to the comments in the first one, that problem should've been fixed with mono 2017-10 which seems to be in Xamarin.iOS 11.8 (unless I misunderstood the info), which I'm already using.

```
System.ExecutionEngineException: Attempting to JIT compile method '(wrapper runtime-invoke) <Module>:runtime_invoke_void__this___int_object_int_object_DateTime_object_Decimal_int_DateTime_int (object,intptr,intptr,intptr)' while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.

  at at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/MonoMethod.cs:661
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Exception source) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:156
  at System.Linq.Expressions.Interpreter.ExceptionHelpers.UnwrapAndRethrow (System.Reflection.TargetInvocationException exception) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/Utilities.cs:172
  at System.Linq.Expressions.Interpreter.NewInstruction.Run (System.Linq.Expressions.Interpreter.InterpretedFrame frame) [0x00026] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/NewInstruction.cs:39
  at System.Linq.Expressions.Interpreter.Interpreter.Run (System.Linq.Expressions.Interpreter.InterpretedFrame frame) [0x00015] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/Interpreter.cs:63
  at System.Linq.Expressions.Interpreter.LightLambda.Run1[T0,TRet] (T0 arg0) [0x0001c] in <b73676a42c4b42e7a590265c5726ced3>:0
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry+OriginalValues..ctor (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry) [0x0000c] in <f7da5a12d702478088613d8aefc8f3d1>:0
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.EnsureOriginalValues () [0x0000d] in <f7da5a12d702478088613d8aefc8f3d1>:0
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry) [0x0000f] in <f7da5a12d702478088613d8aefc8f3d1>:0
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry) [0x0008f] in <f7da5a12d702478088613d8aefc8f3d1>:0
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState (Microsoft.EntityFrameworkCore.EntityState oldState, Microsoft.EntityFrameworkCore.EntityState newState, System.Boolean acceptChanges) [0x00141] in <f7da5a12d702478088613d8aefc8f3d1>:0
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState (Microsoft.EntityFrameworkCore.EntityState entityState, System.Boolean acceptChanges, System.Boolean forceStateWhenUnknownKey) [0x00034] in <f7da5a12d702478088613d8aefc8f3d1>:0
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction (Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntryGraphNode node) [0x00024] in <f7da5a12d702478088613d8aefc8f3d1>:0
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph (Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntryGraphNode node, System.Func`2[T,TResult] handleNode) [0x00000] in <f7da5a12d702478088613d8aefc8f3d1>:0
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry rootEntry, Microsoft.EntityFrameworkCore.EntityState entityState, System.Boolean forceStateWhenUnknownKey) [0x00020] in <f7da5a12d702478088613d8aefc8f3d1>:0
  at Microsoft.EntityFrameworkCore.DbContext.SetEntityState (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry, Microsoft.EntityFrameworkCore.EntityState entityState) [0x00013] in <f7da5a12d702478088613d8aefc8f3d1>:0
  at Microsoft.EntityFrameworkCore.DbContext.SetEntityStates (System.Collections.Generic.IEnumerable`1[T] entities, Microsoft.EntityFrameworkCore.EntityState entityState) [0x00024] in <f7da5a12d702478088613d8aefc8f3d1>:0
  at Microsoft.EntityFrameworkCore.DbContext.AddRange (System.Collections.Generic.IEnumerable`1[T] entities) [0x00012] in <f7da5a12d702478088613d8aefc8f3d1>:0
  at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1[TEntity].AddRange (System.Collections.Generic.IEnumerable`1[T] entities) [0x00000] in <f7da5a12d702478088613d8aefc8f3d1>:0
  at TestReproduceError.App..ctor (TestReproduceError.MyDbContext context) [0x0006b] in /Users/masystem/Dev/TestProjects/TestReproduceError/TestReproduceError/TestReproduceError/App.xaml.cs:18
  at TestReproduceError.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00028] in /Users/masystem/Dev/TestProjects/TestReproduceError/TestReproduceError/TestReproduceError.iOS/AppDelegate.cs:30
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/UIKit/UIApplication.cs:63
  at TestReproduceError.iOS.Application.Main (System.String[] args) [0x00001] in /Users/masystem/Dev/TestProjects/TestReproduceError/TestReproduceError/TestReproduceError.iOS/Main.cs:21
```

### Steps to reproduce
If you try to run the attached project (see bottom) on an iPhone it will crashat the AddRange below.

```c#
public App(MyDbContext context)
{
    InitializeComponent();

    var course = new Course { Name = "name", Description = "description", City = "here", FromDate = DateTime.Now, ToDate = DateTime.Now, Price = 0 };
    var courses = new List<Course>() { course };
    context.Courses.AddRange(courses);

    MainPage = new TestReproduceError.MainPage();
}
```

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 Pro
IDE: Visual Studio Community 2017 for Mac Version 7.4

[TestReproduceError.zip](https://github.com/aspnet/EntityFrameworkCore/files/1793296/TestReproduceError.zip)

**Comment by divega** [comment] 2018-03-12 18:02
Thanks @juripyykko. This indeed looks like a duplicate of #9249. The problem is that the underlying Xamarin.iOS bug which was believed to be fixed still manifested in some flavors of ARM and iOS, and hence got reactivated. 

According to https://bugzilla.xamarin.com/show_bug.cgi?id=59184#c58, a more complete fix has been committed and verified and will be included in the 15.7 release of Xamain, which I believe maps to Xamarin.iOS 11.9 (at least according to https://github.com/xamarin/xamarin-macios/wiki). I am not sure about the timing of this release.

I will close this as a duplicate, and try to get updates on the release time-frame on #9249.

**Closed** 2022-10-16 12:12 UTC
Labels: closed-duplicate
