### ISSUE TITLE
Unable to cast object of type 'System.Data.ProviderBase.DbConnectionClosedConnecting' to type 'System.Data.SqlClient.SqlInternalConnectionTds'

### ISSUE THREAD

**Issue by Bo-Yee-Woods** [dotnet/efcore#11595] opened 2018-04-09 04:44 UTC
In my startup.cs         
    
             services.AddDbContext<HotelDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"), b => 
             b.MigrationsAssembly("CtsHotel")));

in my repository

            return (resourceResponse.Total, Task.Run(() =>
            {                
                foreach (var model in resourceResponse.Terminals)
                {
                    var exists = _Db.Terminals.Any(x => x.Code == model.Code);
                    if (exists) continue;

                    var country = _Db.Countries.Find(model.CountryCode);

                    var terminal = _Mapper.Map<TerminalModel, Terminal>(model);
                    terminal.Country = country ?? throw new Exception("Country Not Found");

                    var name = _Mapper.Map<MultiLangContent, TerminalName>(model.Name);
                    name.Terminal = terminal;
                    name.Language = English;
                    _Db.Add(name); 

                    var description = _Mapper.Map<MultiLangContent, TerminalDescription> 
                    (model.Description);
                    description.Terminal = terminal;
                    description.Language = English;
                    _Db.Add(description);
                }                
            }));

Don't know why. The following exception is throwed.

System.InvalidCastException: 'Unable to cast object of type 'System.Data.ProviderBase.DbConnectionClosedConnecting' to type 'System.Data.SqlClient.SqlInternalConnectionTds'.'

Stack trace:
at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate)
   at CtsHotelLibrary.Repositories.ContentRepository.<>c__DisplayClass27_0.<FetchTerminalsAsync>b__0() in C:\Users\baoyu\Documents\Projects\Work Projects\CtsHotel\CtsHotelLibrary\Repositories\ContentRepository.cs:line 468

**Comment by smitpatel** [comment] 2018-04-09 05:02
Seems like there is some issue with the connection string. Can you trying using `SqlClient directly with the connection string and call `Open` on the connection? If that throws then perhaps https://github.com/dotnet/corefx would be more appropriate place to report.

**Comment by ajcvickers** [comment] 2018-04-16 18:04
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:17 UTC
Labels: closed-could-not-reproduce
