### ISSUE TITLE
SQLite3 Child entites do not get added when parent is added.

### ISSUE THREAD

**Issue by MJomaa** [dotnet/efcore#7524] opened 2017-02-01 16:23 UTC
SQLite3 Child entites do not get added when parent is added.

```
Example:

var teacher = new Teacher
{
    Name = "John",
    Students =
    {
         new Student { Name = "Batman" }
    }
}

await dbContext.Teachers.AddAsync(teacher);
await dbContext.SaveChangesAsync();
````

In this scenario the student doesn't get added unless I specify
```
await dbContext.Students.AddAsync(student);
```

Is this by design?

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite 1.1.0
Operating system: Windows
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment] 2017-02-01 17:05
Dupe of #7298. Workaround is to use Add instead of AddAsync. The async method just adds overhead in all but very obscure scenarios.

**Closed** 2022-10-16 10:52 UTC
