### ISSUE TITLE
Unable to use empty navigation property in split query

### ISSUE THREAD

**Issue by rick-palmsens** [dotnet/efcore#22403] opened 2020-09-04 10:56 UTC
I have entity A (measurement) reference entity B (dataset).
B is currently null, and I want to query it using the navigation property but it does not work.
```c#
var dataSet = await DataSets
    .AsQueryable()
    .Where(dataSet => dataSet == measurement.DataSet)
    .FirstAsync(); // Empty enumerable exception
```

Instead I have to use the id itself:
```c#
var dataSet = await DataSets
    .AsQueryable()
    .Where(dataSet => dataSet.Id == measurement.DataSetId)
    .FirstAsync();
```

Shouldn't the expression parser be able to figure this one out?

### Further technical details

EF Core version: 3.1.7
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: UWP
Operating system: Windows 10 (2004)
IDE: Visual Studio 2019 16.7.2

**Comment by smitpatel** [comment] 2020-09-04 14:48
@rick-palmsens - I am not able to reproduce this. Can you share a complete runnable repro code? Alternatively can you test if it works on 5.0 preview8?

**Comment by ajcvickers** [comment] 2020-09-14 15:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:39 UTC
Labels: closed-could-not-reproduce, customer-reported
