### ISSUE TITLE
Exception creating migration to Drop a table

### ISSUE THREAD

**Issue by CliveBennett** [dotnet/efcore#27418] opened 2022-02-09 21:55 UTC
Hi, im getting an Exception when trying to generate a migration to drop a table

.net 6
EF Core 6.0.1
Pomelo 6.0.1

I removed a Model entity (ApplicantProduct) from the DbContext , and removed any references to it from the codebase.

when I run

add-migration dropTableApplicantProduct -context DatabaseUnitOfWork
I get a stack trace
System.ArgumentException: An item with the same key has already been added. Key: [0, Property: iUW.Models.ApplicantProduct (Dictionary<string, object>).ProductId (no field, int) Indexer Required FK Index]

I initially logged this with MySQL Pomelo, however this has been found to be an issue in EF Core itself

See this issue for full details and stack trace, with reproducible code sample.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1613

**Comment by smitpatel** [comment] 2022-02-09 22:33
Possible duplicate of #26405

**Comment by AndriySvyryd** [comment] 2022-02-11 21:31
Try 6.0.2

**Comment by CliveBennett** [comment] 2022-02-13 18:19
Thanks, confirmed 6.0.2 fixed the issue

**Closed** 2022-10-16 20:25 UTC
Labels: closed-duplicate, customer-reported
