### ISSUE TITLE
Can't install EFCore.Tools.DotNet package via Package Mgr to .NET Corein VS2017 (windows)

### ISSUE THREAD

**Issue by arunprasathv** [dotnet/efcore#11521] opened 2018-04-02 19:44 UTC
@bricelam @smitpatel @AndriySvyryd  getting this error while adding nuget package Tools.DotNet, project is targetting .Netcore 2.0. Is there a fix for this issue?

Package 'Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.2' has a package type 'DotnetCliTool' that is not supported by project 'APIService'.

VS 2017 - Windows.

**Comment by smitpatel** [comment] 2018-04-02 19:53
Duplicate of https://github.com/NuGet/Home/issues/4190
You have to do it manually by editing csproj file.
Here are the steps in docs. https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#installing-the-tools

**Comment by arunprasathv** [comment] 2018-04-02 21:00
@smitpatel Still getting same error,

Package 'Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.2' has a package type 'DotnetCliTool' that is not supported by project 'APIService'.			0	

Here's my proj file

<PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.2" />
  </ItemGroup>

**Comment by smitpatel** [comment] 2018-04-02 21:08
I used that csproj file to restore packages. `dotnet ef` is working for me. What command are you running when you hit that error?

Also don't mix 2.0.2 & 2.1.0-preview1-final packages. Results could be unexpected.

**Comment by smitpatel** [comment] 2018-04-03 14:43
@arunprasathv - You _cannot_ add `Tools.Dotnet` package. You have to edit your csproj file and run dotnet restore.

**Comment by divega** [comment] 2018-04-04 19:47
**EF Triage:** as explained by @smitpatel this error is expected when you try to add a project dotnet CLI tool as if it was a regular package. You just don't use it that way. The good thing is that with 2.1 you won't need to do this anymore because dotnet ef will become a global tool.

**Closed** 2022-10-16 12:16 UTC
Labels: closed-external
