### ISSUE TITLE
GetColumnName doesn't always return the expected column name when dealing with TPH inheritance

### ISSUE THREAD

**Issue by kawazoe** [dotnet/efcore#33458] opened 2024-04-02 18:07 UTC
With the following data model:

```csharp
class Base {
  public int Id { get; set; }
  public string Discriminator { get; set; }
  
  public string TestBase { get; set; }
}

class FooBar : Base {
  public FooBar_Owned Owned { get; set; }
  
  public string TestInherit { get; set; }
}
class FooBar_Owned {
  public string TestOwned { get; set; }
}

class FooBizz : Base {
  public FooBizz_Owned Owned { get; set; }

  public string TestInherit { get; set; }
}
class FooBizz_Owned {
  public string TestOwned { get; set; }
}

class BaseConfiguration : IEntityTypeConfiguration<Base> {
  public void Configure(EntityTypeBuilder<Base> builder) {
    builder.UseTphMappingStrategy()
      .ToTable("Foos")
      .HasDiscriminator<string>("Discriminator")
      .HasValue<FooBar>(nameof(FooBar))
      .HasValue<FooBizz>(nameof(FooBizz))
  }
}
class FooBarConfiguration : IEntityTypeConfiguration<FooBar> {
  public void Configure(EntityTypeBuilder<FooBar> builder) {
    builder.HasBaseType<Base>();
    
    buidler.OwnsOne(b => b.Owned);
  }
}
class FooBizzConfiguration : IEntityTypeConfiguration<FooBizz> {
  public void Configure(EntityTypeBuilder<FooBizz> builder) {
    builder.HasBaseType<Base>();

    buidler.OwnsOne(b => b.Owned);
  }
}
```

The resulting schema has the following columns:

```
// From Base
Id
Discriminator
TestBase

// From FooBar
TestInherit
Owned_TestOwned

// From FooBizz
FooBizz_TestInherit
FooBizz_Owned_TestOwned
```

You will notice that only the second type "FooBizz" get prefixed in the column names. It appears like EF only prefixes columns with conflicting names as an incremental process. The names from the base class sees no prefix, as for the first concrete type (FooBar) since there is no conflict so far. It's only when it processes names for the next concrete type (FooBizz) where it starts prefixing names. Types that _do_ get prefixed don't have the proper column name returned by `GetColumnName()`.

```csharp
var baseType = builder.Metadata.Model.FindEntityType(typeof(Base));
baseType
  .GetProperty("TestBase")
  .GetColumnName(StoreObjectIdentifier.Create(baseType, StoreObjectType.Table)!.Value)
// returns TestBase - OK

var barType = builder.Metadata.Model.FindEntityType(typeof(FooBar));
barType
  .GetProperty("TestInherit")
  .GetColumnName(StoreObjectIdentifier.Create(barType, StoreObjectType.Table)!.Value)
// return TestInherit - OK

var bizzType = builder.Metadata.Model.FindEntityType(typeof(FooBizz));
bizzType
  .GetProperty("TestInherit")
  .GetColumnName(StoreObjectIdentifier.Create(bizzType, StoreObjectType.Table)!.Value)
// return TestInherit - NOT OK - should be FooBizz_TestInherit

var ownedBarType = builder.Metadata.Model.FindEntityType(typeof(FooBar));
var ownedBarNav = ownedBarType.GetNavigations().First(n => n.Name == "Owned");
ownedBarNav.TargetEntityType
  .GetProperty("TestOwned")
  .GetColumnName(StoreObjectIdentifier.Create(ownedBarNav.TargetEntityType, StoreObjectType.Table)!.Value)
// returns Owned_TestOwned - NOT OK - should be FooBar_Owned_TestOwned

var ownedBizzType = builder.Metadata.Model.FindEntityType(typeof(FooBizz));
var ownedBizzNav = ownedBizzType.GetNavigations().First(n => n.Name == "Owned");
ownedBizzNav.TargetEntityType
  .GetProperty("TestOwned")
  .GetColumnName(StoreObjectIdentifier.Create(ownedBizzNav.TargetEntityType, StoreObjectType.Table)!.Value)
// returns Owned_TestOwned - NOT OK - should be FooBizz_Owned_TestOwned
```

### Include provider and version information

EF Core version: 8.0.2
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL/8.0.2
Target framework: .NET 8
Operating system: macOS 14.4
IDE: Rider 2023.3.4

**Comment by AndriySvyryd** [comment] 2024-04-27 00:38
Duplicate of #9329

You are correct that the final column name is calculated in a later stage (when the model is finalized). Unfortunately, with the current convention infrastructure it would be prohibitively slow to calculate this while the model is being built.

@ajcvickers This is evidence that we are on the right track 😉

**Closed by AndriySvyryd** 2024-04-27 00:38 UTC
Labels: customer-reported, area-model-building

**Comment by kawazoe** [comment] 2024-04-27 00:43
@AndriySvyryd Do you have any recommendations for an alternative way of getting those values? I work on a project where we make heavy uses of TPH and dynamically set up features on our model based on the result of GetColumnName. This limitation is a real pain for us right now.

**Comment by AndriySvyryd** [comment] 2024-04-27 02:00
@kawazoe The most reliable solution for you would be to specify all the column names explicitly. If you have a large model you can write a small app that generates the configuration code based on a built model.

If you need to support a dynamic model you could implement your logic in a [`IModelFinalizingConvention`](https://learn.microsoft.com/en-us/ef/core/modeling/bulk-configuration#conventions), so it runs after the final column names have been determined, see
