### ISSUE TITLE
ef migrations add fails when using SqlHierarchyId

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/efcore#14181] opened 2018-12-16 13:50 UTC
SqlHierarchyId is not working with migrations.

This model:

```
public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
        public SqlHierarchyId NodeId{get;set;}

        public ICollection<Post> Posts { get; set; }
    }
```

Creates this snippet:
```
migrationBuilder.AddColumn<SqlHierarchyId>(
                name: "NodeId",
                table: "Blogs",
                nullable: false,
                defaultValue: Microsoft.SqlServer.Types.SqlHierarchyId.Parse(new System.Data.SqlTypes.SqlString("NULL")));
```
which fails with this message when ef migrations add is run:
Microsoft.SqlServer.Types.HierarchyIdException: 24001: SqlHierarchyId.Parse failed because the input string 'NULL' is not a valid string representation of a SqlHierarchyId node.
   at Microsoft.SqlServer.Types.SqlHierarchyId.Parse(SqlString input)
   at ConsoleApp.SQLite.Migrations.CreateDatabase.Up(MigrationBuilder migrationBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Migration.BuildOperations(Action`1 buildAction)
   at Microsoft.EntityFrameworkCore.Migrations.Migration.<.ctor>b__4_1()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Migration.get_UpOperations()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass13_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
24001: SqlHierarchyId.Parse failed because the input string 'NULL' is not a valid string representation of a SqlHierarchyId node.

### Further technical details
EF Core version: 2.2
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Window 10
IDE: Visual Studio 2017 15.9.3

**Comment by gregoryagu** [comment] 2018-12-16 13:59
Note that if the SqlHeirarchyId is nullable, then no exception is thrown.

` public SqlHierarchyId? NodeId{get;set;}`

**Comment by ajcvickers** [comment] 2020-03-27 21:29
Closing as duplicate of #365; see discussion there.

**Closed** 2022-10-16 13:44 UTC
Labels: customer-reported
