### ISSUE TITLE
Update Operation Removes Entity from Database

### ISSUE THREAD

**Issue by ahoshaiyan** [dotnet/efcore#14234] opened 2018-12-22 15:48 UTC
I have run into an unusual issue where EF will remove an entity from the database when I set the entity in the relationship to null. I might not have explained the problem well, please see below.

### Steps to reproduce
I have the following models:

Person:
```csharp
public abstract class Person : BaseModel
{
    public virtual string Name { get; set; }
    public virtual string GovernmentId { get; set; }
    public virtual DateTime BirthDate { get; set; }
    public virtual string MobileNumber { get; set; }
    public virtual int NationalityId { get; set; }
    
    [ForeignKey(nameof(NationalityId))]
    public virtual Country Nationality { get; set; }
}
```

Customer:
```csharp
public class Customer : Person
{
    public void Update(Customer model)
    {
        this.Name = model.Name;
        this.MobileNumber = MobileNumber;
        this.BirthDate = model.BirthDate;
        this.NationalityId = model.NationalityId;
        this.Nationality = model.Nationality;
    }
}
```

Country:
```csharp
public class Country : BaseModel
{
    public int Code { get; set; }
    public string Name { get; set; }
    public string Alpha2Code { get; set; }
    public string Alpha3Code { get; set; }
    public string CcTld { get; set; }
}
```

CustomerViewModel:
```csharp
public class CustomerViewModel
{
    public int Id { get; set; }
    public string Name { get; set; }
    public DateTime? BirthDate { get; set; }
    public string MobileNumber { get; set; }
    public int NationalityId { get; set; }
    public CountryViewModel Nationality { get; set; }
    public List<CountryViewModel> Nationalities { get; set; }
}
```

I have an action to edit the customer model:
```csharp
[HttpPost]
[ValidateAntiForgeryToken]
public IActionResult Edit(CustomerViewModel viewModel)
{
    if (!ModelState.IsValid)
    {
        viewModel.Nationalities = _mapper.Map<List<CountryViewModel>>(_countriesService.List());
        return View(viewModel);
    }
    var model = _mapper.Map<Customer>(viewModel);
    model = _customersService.Update(model);
    if (model == null) return NotFound();
    return RedirectToAction(nameof(Index));
}
```

Now, my business logic have the following method:
```csharp
public Customer Update(Customer model)
{
    var storedModel = Get(model.Id);
    if (storedModel == null) return null;
    storedModel.Update(model);
    _repository.Update(storedModel);
    return storedModel;
}
```

And finally the repository `Update` method:
```csharp
public void Update(TModel model)
{
    _dbCtx.Set<TModel>().Update(model);
    _dbCtx.SaveChanges();
}
```

As you might have noticed the `Update` method in `Customer` class will assign `Nationality` to the value that came from `model`, this value is `null` each time (Because the model binder for the action will not bind it to anything since my form has NationalityId instead, this is not the main point here).

Now when the changes are commited to the database, since `Nationality` became `null` and NationalityId has a value, for some odd reason EF Core will completely remove the `Customer` entity from the database. If I change the `Update` method in `Customer` and didn't take the `null` value, this will not happen.

I hope this explanation is enough, though you can ask me for the complete source code if you want more insights. Thanks

### Further technical details
EF Core version: `2.1.4-rtm-31024`
Database Provider: `MySql.Data.EntityFrameworkCore` Version `8.0.13`
Operating system: macOS Mojave

**Comment by ajcvickers** [comment] 2019-01-03 22:45
@aliio I have not been able to reproduce this using the SQL Server provider--my code below. This means that this is either an issue with the MySQL provider, which should be reported to them, or that something is missing in my attempt to reproduce what you are seeing. If the latter, then please post a runnable project/solution or complete code listing like the one show below that reproduces the behavior you are seeing.

```C#
public abstract class BaseModel
{
    public virtual int Id { get; set; }
}

public abstract class Person : BaseModel
{
    public virtual string Name { get; set; }
    public virtual string GovernmentId { get; set; }
    public virtual DateTime BirthDate { get; set; }
    public virtual string MobileNumber { get; set; }
    public virtual int NationalityId { get; set; }

    [ForeignKey(nameof(NationalityId))]
    public virtual Country Nationality { get; set; }
}


public class Customer : Person
{
    public void Update(Customer model)
    {
        this.Name = model.Name;
        this.MobileNumber = MobileNumber;
        this.BirthDate = model.BirthDate;
        this.NationalityId = model.NationalityId;
        this.Nationality = model.Nationality;
    }
}

public class Country : BaseModel
{
    public int Code { get; set; }
    public string Name { get; set; }
    public string Alpha2Code { get; set; }
    public string Alpha3Code { get; set; }
    public string CcTld { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>();
        modelBuilder.Entity<Person>();
        modelBuilder.Entity<Country>();
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var country1 = new Country();
            var country2 = new Country();

            context.AddRange(country1, country2);
            context.Add(new Customer { Nationality = country1 });

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var customer = context.Set<Customer>().Single();
            customer.Update(new Customer { NationalityId = 2 });
            context.Update(customer);
            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var customer = context.Set<Customer>().Include(e => e.Nationality).Single();
        }
    }
}
```

**Comment by ajcvickers** [comment] 2019-01-14 18:18
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:45 UTC
Labels: closed-could-not-reproduce, customer-reported
