### ISSUE TITLE
Allow accessing members of types mapped via value conversion

### ISSUE THREAD

**Issue by fingers10** [dotnet/efcore#21279] opened 2020-06-16 00:32 UTC
I'm building my app using DDD approach. I have `Book` Entity with a `Title` ValueObject in it.

**`Book` Entity:**
```c#
public class Book : Entity, IAggregateRoot
{
    protected Book()
    {
    }

    public Book(Title title) : this()
    {
        Title = title;
    }

    public Title Title { get; private set; }
}
```

**`Title` ValueObject:**
```c#
public class Title : ValueObject
{
    public string Value { get; }

    protected Title()
    {
    }

    private Title(string value) : this()
    {
        Value = value;
    }

    public static Result<Title> Create(string title)
    {
        if (string.IsNullOrWhiteSpace(title))
            return Result.Failure<Title>("Title should not be empty");

        title = title.Trim();

        if (title.Length > 100)
            return Result.Failure<Title>("Title is too long");

        return Result.Success(new Title(title));
    }

    protected override IEnumerable<object> GetEqualityComponents()
    {
        yield return Value;
    }

    public static implicit operator string(Title title)
    {
        return title.Value;
    }
}
```

**Entity Configuration:**
```c#
public class BookConfiguration : IEntityTypeConfiguration<Book>
{
    public void Configure(EntityTypeBuilder<Book> builder)
    {
        builder.ToTable("Book").HasKey(k => k.Id);

        builder.Property(p => p.Title)
                .IsRequired()
                .HasMaxLength(100)
                .HasConversion(p => p.Value, p => Title.Create(p).Value);
    }
}
```

When I make a `==` search in `Title`, it works fine.
```c#
var test = await _unitOfWork.BookRepository.Where(x => x.Title.Value == query.SearchQuery); 
```

But this fails when I make a `Contains` Search,
```c#
var test = await _unitOfWork.BookRepository.Where(x => x.Title.Value.Contains(query.SearchQuery));
```
and throws exception

> The LINQ expression 'DbSet<Book>
>     .Where(b => b.Title.Value.Contains("Two State"))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync()

As a work around, I'm using `EF Functions`

```c#
var test = await _unitOfWork.BookRepository.Where(x => EF.Functions.Like(x.Title, $"%{query.SearchQuery}%"));
```
This translates the query but this forces me to add `Microsoft.EntityFrameworkCore` in my core domain logic project.

Any assistance on how to make this work without `EF.Functions.Like`?

Here is the link to [sample repo](https://github.com/fingers10/EFCoreIssuesSample) to reproduce the issue.

### Further technical details

EF Core version: 3.1.4
Database provider: `Microsoft.EntityFrameworkCore.SqlServer`
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.2

**Comment by ajcvickers** [comment] 2020-06-16 15:45
Related: #10434

**Comment by fingers10** [comment] 2020-10-12 19:10
@ajcvickers  any plans on this? Please share your thoughts.

**Comment by roji** [comment] 2020-10-13 12:23
@fingers10 this issue is in the backlog, but has the consider-for-next-release label. This means we'll be considering it for the 6.0 release, but it will have to be prioritized against other work.

**Comment by fingers10** [comment] 2020-10-13 12:26
@roji Thanks for the inputs.

**Comment by smitpatel** [comment] 2020-10-15 18:47
Duplicate of #20721

**Closed** 2022-10-16 18:29 UTC
Labels: customer-reported
