### ISSUE TITLE
TemporalAll() exception: Either the query source is not an entity type, or the specified property does not exist on the entity type.

### ISSUE THREAD

**Issue by MikeOtown** [dotnet/efcore#30561] opened 2023-03-23 18:10 UTC
Can't access the Temporal "SysStartTime" property of my History table:

var approved = _programCtx.StatisticalDatas.TemporalAll().IgnoreQueryFilters()                        
                        .OrderBy(stat => EF.Property<DateTime>(stat, "SysStartTime"))
                        .Where(stat => stat.id == sd.id && stat.status == StatisticalDataStatusEnum.Complete)
                        .Select(stat =>
                            new
                            {
                                PeriodStart = EF.Property<DateTime>(stat, "SysStartTime")
                            })
                        .FirstOrDefault();

![image](https://user-images.githubusercontent.com/18534728/227305899-af848c85-a2b6-4dfa-8562-5ef750191f9e.png)

Full Exception Message:  Translation of 'EF.Property<DateTime>(EntityShaperExpression: 
    NCMSProgram.ServiceModel.Types.StatisticalData
    ValueBufferExpression: 
        ProjectionBindingExpression: EmptyProjectionMember
    IsNullable: False
, "SysStartTime")' failed. Either the query source is not an entity type, or the specified property does not exist on the entity type.

Exception Stack Trace:     at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateExpression(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateOrderBy(ShapedQueryExpression source, LambdaExpression keySelector, Boolean ascending)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at NCMSProgram.ServiceInterface.CompanyService.Post(GetStatisticalDatas request) in C:\Users\micha\source\repos\NCMS Audit\NCMSProgram\NCMSProgram.ServiceInterface\CompanyService.cs:line 387

Table Create DML:  CREATE TABLE [dbo].[StatisticalDatas](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[report_year] [int] NOT NULL,
	[report_period] [int] NOT NULL,
	[ncms_id] [nvarchar](max) NULL,
	[ValidUntilDate] [datetime2](7) NULL,
	[SysStartTime] [datetime2](0) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
	[SysEndTime] [datetime2](0) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,
	[report_type] [nvarchar](1000) NULL,
	[status] [int] NOT NULL,
	[archived] [bit] NOT NULL,
 CONSTRAINT [PK_StatisticalDatas] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime])
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[StatisticalDatasHistory])
)
GO

```
 <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.13" />
```

**Comment by MikeOtown** [comment] 2023-03-23 18:22
Had to add SysStartTime to my entity definition.

**Comment by MikeOtown** [comment] 2023-03-23 18:29
However, add-migration tries to add "SysStartTime" to the table even though it already exists.  If I add {NotMapped] attribute, .TemporalAll() no longer works.

**Comment by MikeOtown** [comment] 2023-03-23 18:52
Tried...

modelBuilder.Entity<StatisticalData>().ToTable(tb => tb.IsTemporal(ttb =>
            {
                ttb.HasPeriodStart("SysStartTime");
                ttb.HasPeriodEnd("SysEndTime");                
            }));

in my OnModelCreating() and SysStartTime and SysEndTime columns already exist in the table, but when I execute add-migration, migrations to add these columns are generated.

**Comment by ajcvickers** [comment] 2023-03-27 12:27
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-04-11 10:57
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-04-11 10:57 UTC
Labels: closed-no-further-action, customer-reported
