### ISSUE TITLE
Inheritance and Lazy Loading

### ISSUE THREAD

**Issue by KeKl** [dotnet/efcore#16936] opened 2019-08-04 09:49 UTC
Hi everyone,

I get an exception using lazy loading with the 
`            protected Action<object, string> LazyLoader { get; set; }`
property at the base class.
I have one ctor in the base with the overload for the lazyLoader Action and in the subclasses.

The exception:
_The service property 'LazyLoader' of type 'Action<object, string>' cannot be added to the entity type 'Food' because there is another property of the same type. Ignore one of the properties using the NotMappedAttribute or 'EntityTypeBuilder.Ignore' in 'OnModelCreating'._

Whats the proper way implementing lazy loading at inheritance with more than one subclass?

```
public abstract class Base
{
        protected Base(Action<object, string> lazyLoader)
            : this()
        {
            LazyLoader = lazyLoader;
        }	

	protected Action<object, string> LazyLoader { get; set; }
}

public class Sub
{
        private Sub(Action<object, string> lazyLoader)
            : base(lazyLoader)
        {
        }
}
```

**Comment by ajcvickers** [comment] 2019-08-05 14:45
@KeKl There isn't enough information here for me to reproduce what you are seeing. Please post a small, runnable project/solution or complete code listing so that we can investigate fully.

**Comment by KeKl** [comment] 2019-08-06 12:14
> @KeKl There isn't enough information here for me to reproduce what you are seeing. Please post a small, runnable project/solution or complete code listing so that we can investigate fully.

I created a small project. And it worked as expected. I try to reproduce it in removing unneeded parts in the big project.

**Comment by ajcvickers** [comment] 2019-08-14 16:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:33 UTC
Labels: closed-could-not-reproduce, customer-reported
