### ISSUE TITLE
Simple query fails - with test case

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#6195] opened 2016-07-28 13:38 UTC
### Steps to reproduce

Using the `InMemory` store , here is a simple xunit test case to reproduce the problem (using xunit)

``` csharp

    public class EFGitHubIssue6195
    {

        private Issue6195DbContext _db;

        public EFGitHubIssue6195()
        {
            var optionsBuilder = new DbContextOptionsBuilder<Issue6195DbContext>();
            // Create an in memory database for unit testing.
            optionsBuilder.UseInMemoryDatabase();
            _db = new Issue6195DbContext(optionsBuilder.Options);
        }

        [Fact]
        public void Reproduce()
        {
            int entityBId = 1;
            var dataObjectQuery = _db.EntityA.Where(c => c.EntityC != null && c.EntityC.IsActive);
            var boom = dataObjectQuery.ToArray();

        }

    }

    public class Issue6195DbContext : DbContext
    {

        public Issue6195DbContext(DbContextOptions<Issue6195DbContext> options) : base(options)
        {

        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<EntityA>(entity =>
            {

            });

            modelBuilder.Entity<EntityC>(entity =>
            {

            });

        }

        public virtual DbSet<EntityA> EntityA { get; set; }

        public virtual DbSet<EntityC> EntityC { get; set; }
    }

    public class EntityA
    {
        public int EntityAId { get; set; }

        public int? EntityCId { get; set; }
        public virtual EntityC EntityC { get; set; }
    }

    public class EntityC
    {
        public EntityC()
        {
            EntityA = new HashSet<EntityA>();
        }

        public int EntityCId { get; set; }

        public bool IsActive { get; set; }

        public virtual ICollection<EntityA> EntityA { get; set; }

    }

```

Exception message:

```
Expression of type 'System.Func`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Reach.Business.Tests.EntityA,System.Collections.Generic.IEnumerable`1[Reach.Business.Tests.EntityC]],Reach.Business.Tests.EntityC],System.Nullable`1[System.Boolean]]' cannot be used for parameter of type 'System.Func`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Reach.Business.Tests.EntityA,System.Collections.Generic.IEnumerable`1[Reach.Business.Tests.EntityC]],Reach.Business.Tests.EntityC],System.Boolean]' of method 'System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Reach.Business.Tests.EntityA,System.Collections.Generic.IEnumerable`1[Reach.Business.Tests.EntityC]],Reach.Business.Tests.EntityC]] _Where[TransparentIdentifier`2](System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Reach.Business.Tests.EntityA,System.Collections.Generic.IEnumerable`1[Reach.Business.Tests.EntityC]],Reach.Business.Tests.EntityC]], System.Func`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Reach.Business.Tests.EntityA,System.Collections.Generic.IEnumerable`1[Reach.Business.Tests.EntityC]],Reach.Business.Tests.EntityC],System.Boolean])'
```

Stack trace:

```
at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
  at Reach.GCv3.Business.Tests.EFGitHubIssue6195.Reproduce() in C:\Users\darrell.tunnell\Source\Repos\gc3-website\src
```
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 8.1 Enterprise N
Visual Studio version: VS2015 Update 3

**Comment by dazinator** [comment] 2016-07-28 13:43
Let me put together a simple unit test to reproduce, then I will reopen.

**Comment by maumar** [comment] 2016-07-28 18:02
This is fixed in the current dev (and I verified in was broken in RTM). Workaround is to add == true to the bool property like so:

```cs
_db.EntityA.Where(c => c.EntityC != null && c.EntityC.IsActive == true);
```

**Comment by dazinator** [comment] 2016-07-28 22:29
Ah, ok thank you :-)
Do you now have a regression test in place for this also?

**Comment by maumar** [comment] 2016-07-28 22:52
Yes, here is the commit: https://github.com/aspnet/EntityFramework/commit/add3939bd592f1c4a7f249b81d024a2ff260091d

Scenario is not exactly the same but it's the same root cause. What happens under the covers in your case is that we convert the query into:

```cs
_db.EntityA.Where(c => c.EntityC != null && (bool)(c.Entity != null ? (bool?)c.EntityC.IsActive : null));
```

We are not smart to recognize that you constrained the results to non-nullable entities already, and we apply nullability safeguards ourselves. Those safeguards were confusing a piece of code that converts boolean columns/literals to search conditions.

**Comment by dazinator** [comment] 2016-07-29 00:06
Excellent, thank you for the more detailed explaination.

**Closed** 2022-10-16 09:52 UTC
Labels: closed-duplicate
