### ISSUE TITLE
Query: invalid sql (variable has already been declared) for query with join where both sources contain reference to the same parameter

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12871] opened 2018-08-02 19:37 UTC
query:

```cs
                var local = new Customer
                {
                    CustomerID = "ANATR"
                };

                var query = (from c in ctx.Customers
                             where c == local
                             select c).Join(from c2 in ctx.Customers
                                            where c2 == local
                                            select c2, o => o, i => i, (o, i) => o).Select(e => e.CustomerID);

                var result = query.ToList();
```

sql:

```sql
SELECT [c].[CustomerID]
FROM [Customers] AS [c]
INNER JOIN (
    SELECT [c2].*
    FROM [Customers] AS [c2]
    WHERE [c2].[CustomerID] = @__local_0_CustomerID
) AS [t] ON [c].[CustomerID] = [t].[CustomerID]
WHERE [c].[CustomerID] = @__local_0_CustomerID
```

exception:

The variable name '@__local_0_CustomerID' has already been declared. Variable names must be unique within a query batch or stored procedure.

**Comment by smitpatel** [comment] 2019-06-10 16:40
Duplicate of #14645

**Closed** 2022-10-16 13:23 UTC
Labels: type-bug, closed-duplicate
