### ISSUE TITLE
compare to database tables and dbcontext dbsets for Missing Table Creation

### ISSUE THREAD

**Issue by hintsofttech** [dotnet/efcore#27195] opened 2022-01-16 17:29 UTC
If later added dbset table not exists in database, then dbcontext should compare and create it on dbcontext initialization.
but it's not comparing to database tables and dbcontext dbsets at all.
in this case, **no migration history table** will be required and migration will be automatic implemented.

**Comment by roji** [comment] 2022-01-16 21:28
Duplicate of #27160

**Comment by hintsofttech** [comment] 2022-01-17 04:10
> Duplicate of #27160

didn't get solution yet ...
that's why created new seperate issue for better focused solution.

**Closed** 2022-10-16 20:22 UTC
Labels: customer-reported
