### ISSUE TITLE
Nested entities not tracked automatically?

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#7892] opened 2017-03-15 19:25 UTC
#### Model:
```csharp
public class Question
{
    public int Id { get; set; }
    public string Text { get; set; }
    public ICollection<Answer> Answers { get; set; }

    public override string ToString() => $"Question({Id}): {Text}";
}

public class Answer
{
    public int Id { get; set; }
    public string Text { get; set; }
    public int QuestionId { get; set; }
    public Question Question { get; set; }

    public override string ToString() => $"Answer({Id}): {Text}";
}
```

#### Context:
```csharp
public class TestContext : DbContext
{
    public DbSet<Question> Questions { get; set; }
    public DbSet<Answer> Answers { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.UseSqlServer($@"Server=(localdb)\mssqllocaldb;Database=test;Trusted_Connection=True;");
    }
}
```

#### Problem:
Assume some data in the database. The query `db.Questions.Include(x => x.Answers).ToArray();` results in having all `Question`s and all `Answer`s tracked, based on `Console.WriteLine(string.Join(Environment.NewLine, db.ChangeTracker.Entries().Select(x => x.Entity.ToString())));`. While running `db.Questions.Select(x => new SomeDto() { Question = x, Answers = x.Answers }).ToArray();` tracks only all `Question`s.

This is different behavior compared to EF6. It might be even expected. But is it? And if so, is there some document where the logic is described? Maybe also some document highlighting the differences?

#### Environment
`netcoreapp1.1`, EF Core 1.1.1

**Comment by ajcvickers** [comment] 2017-03-17 19:49
Dupe of #7569

**Closed** 2022-10-16 10:56 UTC
