### ISSUE TITLE
Add-Migration EFCore tool generates NRE for specific IEntityTypeConfiguration<T> implementing type name

### ISSUE THREAD

**Issue by marinobjelopera26** [dotnet/efcore#30203] opened 2023-02-03 12:52 UTC
## Description

I have ran upon an issue with using EF Core tools while invoking `Add-Migration MigrationName`  through the Package Manager Console in Visual Studio 2022, as described below.

I have a .NET6 solution with webapi as the main, runnable part of the solution. The rest of the solution consists of supporting projects to implement functionalities in an architecture of choice. One of the project contains entities that are persisted in Persistence .NET6 project in an SQL Server instance through EF Core v7.0.0 ORM. I am defining manual configurations for entities by implementing `IEntityConfiguration<T>` interface. 

I have entity class as follows:
```C#
// These two classes are simple value objects containing a single property and static factory functions to instantiate them
public class ProductId { ... } // contains a Guid value property
public class ProductIdentifier { ... } // contains a string value property

// This class should be persisted as an owned entity type as part of the Product entity in Products table
public class ProductCoreSystem : ValueObject
{
    public string Identifier { get; private set; }
    public string Code { get; private set; }

    // object instantiation logic
}

public sealed class Product 
{
    private Product() {  } // empty ctor for EF Core purposes

    public ProductId Id { get; private set; }
    public ProductIdentifier Identifier { get; private set; }
    public ProductCoreSystem CoreSystem { get; private set; }

    // ... other Product related logic
}
```

To configure this entity persistence to the SQL server, I have the following `IEntityTypeConfiguration` implementation:
```C#
public class ProductConfigurations : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
        builder.ToTable("Products", schema: "dbo");

        builder.HasKey(p => p.Id);

        builder.Property(p => p.Id)
            .ValueGeneratedNever() // we are manually generating the ID value
            .HasConversion(
                id => id.Value,
                value => ProductId.Create(value));

        builder.Property(p => p.Identifier)
            .IsRequired()
            .HasMaxLength(30)
            .HasConversion(
                name => name.Value,
                value => ProductIdentifier.Create(value));

        builder.OwnsOne(
            p => p.CoreSystem,
            ownedBuilder => 
            {
                ownedBuilder.Property(cs => cs.Identifier)
                    .IsRequired()
                    .HasColumnType("CHAR(3)")
                    .HasColumnName(nameof(Product.Identifier));

                ownedBuilder.Property(cs => cs.Code)
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnName("CoreSystemCode");
            });
    }
}
```
DbContext is set up as follows:
```C#
public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AssemblyReference).Assembly);

        base.OnModelCreating(modelBuilder);
    }
}
```

After invoking `Add-Migration SomeMigrationName` through Visual Studio Package Manager Console, I get a NullReferenceException generated by EF Core as stated below in the Stack trace section. After rename of the `IEntityTypeConfiguration<T>` implementing type from `ProductConfigurations` to let's say, `InsProductConfigurations`, Add-Migration command successfully generates a new migration while nothing of the underlying configuration code has been changed.

This issue occurrs when the configured entity contains owned types, either one-to-one owned type or one-to-many list of owned types.

### Stack trace
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.CreateForeignKey(InternalEntityTypeBuilder principalEntityTypeBuilder, IReadOnlyList`1 dependentProperties, Key principalKey, String propertyBaseName, Nullable`1 required, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasRelationship(EntityType targetEntityType, Nullable`1 navigationToTarget, Nullable`1 inverseNavigation, Nullable`1 setTargetAsPrincipal, ConfigurationSource configurationSource, Nullable`1 required)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasOwnership(EntityType targetEntityType, MemberIdentity& navigation, Nullable`1 inverse, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Microsoft.EntityFrameworkCore.Metadata.Builders.IConventionEntityTypeBuilder.HasOwnership(IConventionEntityType targetEntityType, MemberInfo navigation, Boolean fromDataAnnotation)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.RelationshipDiscoveryConvention.CreateRelationships(IEnumerable`1 relationshipCandidates, IConventionEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.RelationshipDiscoveryConvention.Process(IConventionEntityType entityType, String navigationName, MemberInfo memberInfo, IConventionContext context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.RelationshipDiscoveryConvention.ProcessNavigationRemoved(IConventionEntityTypeBuilder sourceEntityTypeBuilder, IConventionEntityTypeBuilder targetEntityTypeBuilder, String navigationName, MemberInfo memberInfo, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnNavigationRemoved(IConventionEntityTypeBuilder sourceEntityTypeBuilder, IConventionEntityTypeBuilder targetEntityTypeBuilder, String navigationName, MemberInfo memberInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnNavigationRemovedNode.Run(ConventionDispatcher dispatcher)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.DelayedConventionScope.Run(ConventionDispatcher dispatcher)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Dispose()
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.OwnsOneBuilder[TRelatedEntity](TypeIdentity ownedType, MemberIdentity navigation)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.OwnsOne[TRelatedEntity](Expression`1 navigationExpression, Action`1 buildAction)
   at CustomNamespace.Persistence.ProductConfiguration.Configure(EntityTypeBuilder`1 builder) in C:\CustomNamespace\Persistence\ProductConfiguration.cs:line 27
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration[TEntity](IEntityTypeConfiguration`1 configuration)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfigurationsFromAssembly(Assembly assembly, Func`2 predicate)
   at CustomNamespace.Persistence.DbContext.OnModelCreating(ModelBuilder modelBuilder) in C:\CustomNamespace\Persistence\DbContext.cs:line 16
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation.
```

### Provider and version information

EF Core version: v7.0.0.
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Linux
IDE: Visual Studio 2022 17.4.4

**Comment by ajcvickers** [comment] 2023-02-04 10:58
@marinobjelopera26 This looks like a duplicate of #30107, but its hard to tell with only snippets of code. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by marinobjelopera26** [comment] 2023-02-06 07:15
@ajcvickers thank you for a quick response. 

I have created a runnable project representing what I had described, however I am unable to reproduce the issue. Unfortunately, I am not able to share the source code of the project in which it does occur due to company policy. I managed to work around this issue by simply renaming the type implementing `IEntityConfiguration<>` interface. Since I am not able to reproduce the issue in a new project, do tell if you want me to close the issue.

**Closed** 2023-02-06 10:33 UTC
Labels: customer-reported

**Comment by marinobjelopera26** [comment] 2023-03-08 09:19
@ajcvickers I have managed to reproduce the issue, it is practically a duplicate of #30373. The issue occurs when following DDD principles and the identity value object is used as a collection of owned entity types in another aggregate root. 
Can you provide me with suggestions how to work around this issue?

**Comment by ajcvickers** [comment] 2023-03-08 10:34
> Is this something that you reckon will be fixed in the future releases?

No. EF Core is unlikely to ever allow using the same CLR type as both an entity type and a value object.

**Comment by ajcvickers** [comment] 2023-03-08 11:19
@marinobjelopera26 This code `builder.OwnsMany(p => p.ProductIds,` says make the element type in the collection `p.ProductIds` an owned entity type. This makes the type `ProductId` an owned entity type. It's possible you intended to make some other type an owned entity type, but as it stands, the mapping is invalid in EF Core.

**Comment by marinobjelopera26** [comment] 2023-03-08 11:38
I think I understand now. 
Assuming the scenario that I described in the previous comment, once this code `builder.OwnsMany(p => p.ProductIds` is invoked, `ProductId` is marked as owned entity type. 
Therefore, if `ProductId` is also used as primary key on an entity (`Product)`, Product cannot contain other owned entity types since ProductId is now an owned entity type and hence cannot be used as a shadow foreign key on `ProductDetail`?

**Comment by ajcvickers** [comment] 2023-03-08 11:47
@marinobjelopera26 I don't really understand what you are saying. As far as I can tell, your terminology, in so far as I understand it from Eric Evans DDD book or EF Core concepts, doesn't map to what your code shows. For example, why would you want `ProductId` to be an entity type? It looks like a value object. Are you trying to map a collection of value objects? If so, `OwnsMany` is certainly not the way to do that-see [Collections of value objects](https://learn.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations#collections-of-value-objects). Or do you want `ProductId` to be the primary key for a collection in an aggregate? If so, the `OwnsMany` is fine, but the collection would be of the entity type, not its key type.

**Comment by marinobjelopera26** [comment] 2023-03-08 12:56
@ajcvickers apologies if I am being unclear, or setting it up wrong, still learning about DDD.

`ProductId` is indeed a value object and is used to configure a primary key on `Product` aggregate:
```csharp
public abstract class AggregateRoot<TIdentity>
    where TIdentity : notnull
{
    public TIdentity Id { get; private set; }

    // ctors
}

public class ProductId : ValueObject
{
    public Guid Value { get; private set; }

    private ProductId(Guid value)
    {
        Value = value;
    }

    public static ProductId Create(Guid value)
    {
         return new ProductId(value);      
    }

    public override IEnumerable<object> GetEqualityComponents()
    {
        yield return Value;
    }
}

public class Product : AggregateRoot<ProductId>
{
}

public class ProductConfigurations : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
        builder.HasKey(p => p.Id);

        builder.Property(p => p.Id)
            .ValueGeneratedNever()
            .HasConversion(
                id => id.Value,
                value => ProductId.Create(value));
    }
}
```

However, let's say I have another aggregate called `Client`. `Client` may have zero to n products. Within the `Client` aggregate root I want to keep track of all the `Product`s that a `Client` has. Following DDD, aggregate root can only reference other aggregate roots by their ID, in this case `ProductId`.
Hence, if I want to define a table that would relate `Client` to `Product`s, I would do it like this:
```csharp
public class Client : AggregateRoot<ClientId>
{
    private readonly List<ProductId> _productIds = new();

    // ctor

   public IReadOnlyCollection<ProductId> ProductIds => _productIds.AsReadOnly();
}

public class ClientConfigurations : IEntityTypeConfiguration<Client>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
        builder.HasKey(p => p.Id);

        builder.Property(p => p.Id)
            .ValueGeneratedNever()
            .HasConversion(
                id => id.Value,
                value => ClientId.Create(value));

        builder.OwnsMany(
            p => p.ProductIds,
            pb => 
           {
               pb.ToTable("ClientProductIds");

               pb.WithOwner().HasForeignKey("ClientId");

               pb.HasKey("Id");

               pb.Property(pid => pid.Value)
                   .ValueGeneratedNever()
                   .HasColumnName(nameof(ProductId));
           }
    }
}
```
And as far as I've seen, this works as expected. EF creates three tables, `Products`, `Clients`, `ClientProductIds`.
Now, I want to add an owned entity type `ProductSystem` to the `Product` aggregate. 
```csharp 
public class ProductSystem : ValueObject
{
    public string Identifier { get; private set; }
    public string Code { get; private set; }

    private ProductSystem(string identifier, string code)
    {
        Identifier = identifier;
        Code = code;
    }
}

public class Product : AggregateRoot<ProductId>
{
    // ...
    public ProductSystem System { get; private set; }
}
```

I configure this owned in the `ProductConfigurations` entity type with `.OwnsOne(p => p.System, sb => { ... });`:
```csharp
public class ProductConfigurations : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
         // ...

         // This will generate NRE on `InternalEntityBuilder.CreateForeignKey(...)`
        builder.OwnsOne(
            p => p.System,
            sb =>
           {
               sb.Property(s => s.Identifier)
                   .IsRequired()
                   .HasColumnType("CHAR(3)");

               sb.Property(s => s.Code)
                   .IsRequired()
                   .HasMaxLength(30);
           }
    }
```
In this scenario, `builder.OwnsOne(p => p.System, sb => { ... });` causes a `NullReferenceException` while attempting to generate a migration. What I've understood so far from you this happens because `ProductId` is configured as a collection of owned entity types on `Client`.

**Comment by ajcvickers** [comment] 2023-03-12 20:36
> Following DDD, aggregate root can only reference other aggregate roots by their ID, in this case ProductId

For the same reasons that DDD doesn't allow anything other than a manual ID here, EF also doesn't support anything other than a manual ID here. That is, you cannot set this up as a relationship that EF manages, because doing so would result in aggregates that reference each others internals.
