### ISSUE TITLE
Empty collection after eager loading only on .ToList() but .Single() works fine

### ISSUE THREAD

**Issue by rudeseagull** [dotnet/efcore#20251] opened 2020-03-11 11:29 UTC
I'm building an API with EF Core 3.1.2, ASP .NET Core and .NET Core 3.1. 
The database is SQL Server on Azure so I'm using the DB first approach. 

Before going into everything in details I want to give you a clear summary of my issue, I'm using the Query Object technique to segregate each part of my query into a single responsibility method.

```
return _context.Orders
                .AsNoTracking()
                .MapOrderToDto()
                .SingleOrDefault(o => o.ID == orderId);
```

The above code is working perfectly, `.MapOrderToDto()` return an `IQueryable<OrderDto>` with one nested collection `IQueryable<OrderProductDto>` and itself contains one more nested collection `IQueryable<OrderFileDto>`. When calling .Single() everything is flattened and the API result is as following : 

```
{
    "id": "1",
    "orderProducts": [
        {
            "orderProductId": "1",
            "orderFiles": [
                {
                    "orderFileID": "1",
                },
                {
                    "orderFileID": "2",
                }
            ]
        },
        {
            "orderProductId": "2",
            "orderFiles": [
                {
                    "orderFileID": "1",
                }
            ]
        },
    ],
}
```

As you can see, the top level Order has a child collection of OrderProduct and those OrderProduct have one child collection of OrderFile each. All collections are populated. 

Now, when doing the **exact same thing** but for several results, like this 

```
_context.Orders
                .AsNoTracking()
                .MapOrderToDto()
                .Page(pageNum, pageSize)
                .ToList()
```

The OrderFiles collection **is always empty**. Even more surprising, I'm using the OrderFiles to do some logic and set a property IsCompleted on the parent OrderProduct. Something like this 

```
IsCompleted = p.OrderFiles.Any()
```

The value of this property is always correct, for me that means that my query was able to load the OrderFile collection but it got lost during the flattening with .ToList(). 

I really don't understand this behavior at all.

### Steps to reproduce

**Simplified Models with relevant properties** 

```
public partial class Orders
    {
        public int OrderId { get; set; }
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
    }
```
```
public partial class OrderProducts
    {
        public int OrderProductId { get; set; }
        public virtual Orders Order { get; set; }
        public virtual ICollection<OrderFiles> OrderFiles { get; set; }
    }
```
```
public partial class OrderFiles
    {
        public int OrderFileId { get; set; }
        public virtual Orders OrderOrder { get; set; }
        public virtual OrderProducts OrderProduct { get; set; }
    }
```

**Mapping method for Order to OrderDto, OrderProduct to OrderProductDto and OrderFile to OrderFileDto (simplifed)**

```
public static IQueryable<OrderDto> MapOrderToDto(this IQueryable<Orders> orders)
        {
            return orders
                .Include(order => order.OrderProducts)
                    .ThenInclude(orderProduct => orderProduct.OrderFiles)
                .Select(o => new OrderDto
                {
                    ID = o.OrderId,
                    OrderProducts = o.OrderProducts.MapOrderProductToDto(),
                });
        }
```
```
public static IQueryable<OrderProductDto> MapOrderProductToDto(this ICollection<OrderProducts> products)
        {
            return products
                .AsQueryable()
                .Select(p => new OrderProductDto
                {
                    OrderProductId = p.OrderProductId,
                    // work in all cases, making me believe OrderFiles are correctly loaded
                    IsCompleted = p.OrderFiles.Any(),  
                    // work only with .Single() on the top level query
                    OrderFiles = p.OrderFiles.MapOrderProductFileToDto() 
                });
        }
```
```
public static IQueryable<OrderProductFileDto> MapOrderProductFileToDto(this ICollection<OrderFiles> files)
        {
            return files
                .AsQueryable()
                .Select(f => new OrderProductFileDto
                {
                    OrderFileID = f.OrderFileId,
                });
        }
```

**This will return a fully populated result with the OrderFile collection**
```
return _context.Orders
                .AsNoTracking()
                .MapOrderToDto()
                .SingleOrDefault(o => o.ID == orderId);
```
**This won't**
```
_context.Orders
                .AsNoTracking()
                .MapOrderToDto()
                .Page(pageNum, pageSize)
                .ToList()
```

When Logging queries they are (as i though) exactly the same except for the LEFT JOIN part where the OrderFiles are retrieved. 

**This is the end of the query when generated by .Single()**
```
LEFT JOIN (
    SELECT // removed for clarity
    FROM [OrderProducts] AS [o4]
    LEFT JOIN [OrderFiles] AS [o5] ON [o4].[OrderProductID] = [o5].[OrderProductID]
) AS [t0] ON [t].[OrderID] = [t0].[OrderID]
ORDER BY [t].[OrderID], [t0].[OrderProductID], [t0].[OrderFileID]
```
**And this is the end when generated by .ToList()**
```
LEFT JOIN [OrderProducts] AS [o4] ON [t].[OrderID] = [o4].[OrderID]
```
No trace of OrderFiles ...

Note that the current API in production is using EF6 but it's very slow due to a lot of .ToList() and foreach() at every step of the mapping. My goal is to keep everything as differed code until the final iteration on the top level query. I'm pretty happy with the result so far and .Single() prove that this can work (at least in my mind). 

### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET Core 3.1
IDE: Visual Studio 2019 16.4.5

**Comment by smitpatel** [comment] 2020-03-11 15:33
Duplicate of #18672

**Comment by rudeseagull** [comment] 2020-03-11 15:44
@smitpatel Referencing the issue already helps. Kinda reassuring to be honest. 
Is there a fix coming ? Or do I have to change the way I'm doing this ? 
Cheers.

**Closed** 2022-10-16 18:15 UTC
Labels: customer-reported
