### ISSUE TITLE
Add support for IQueryable.Append translation

### ISSUE THREAD

**Issue by jeffmccormick** [dotnet/efcore#34657] opened 2024-09-12 03:38 UTC
Support for a variety of collection operations which translate to `UNION`s was added in #6812, however `Append()` is still throwing a "could not be translated" error in v8.0.8.

```cs
var results = context.Entity.Select(e => e.Id).Append(123).ToList(); // InvalidOperationException
```

With #32337, we can now write:

```cs
var results = context.Entity.Select(e => e.Id).Concat([123]).ToList();
```

But it would be nice for the singular case to allow `Append()`, which would avoid the array allocation and (currently) the `OPENJSON` collection handling (see #32339).

**Comment by roji** [comment] 2024-09-12 09:46
Duplicate of #30669

**Closed by roji** 2024-09-12 09:46 UTC
Labels: type-enhancement, customer-reported
