### ISSUE TITLE
[BUG] CurrentValues.SetValues does not update owned types, but any other primitive properties are updated

### ISSUE THREAD

**Issue by rafaelfgx** [dotnet/efcore#25032] opened 2021-06-03 23:13 UTC
**Hi guys,**

**I have a problem with owned types. When CurrentValues.SetValues method is called to partially update an entity, primitive properties are updated correctly, but owned types are not.**

### Entity

```cs
public sealed class Customer
{
    public Customer() { }

    public Customer(long id, Name name)
    {
        Id = id;
        Name = name;
    }

    public long Id { get; private set; }

    public Name Name { get; private set; }
}
```

### Value Object (Owned Type)
```cs
public sealed record Name(string FirstName, string LastName);
```

### Entity Type Configuration

```cs
public sealed class CustomerConfiguration : IEntityTypeConfiguration<Customer>
{
    public void Configure(EntityTypeBuilder<Customer> builder)
    {
        builder.ToTable(nameof(Customer));

        builder.HasKey(customer => customer.Id);

        builder.Property(customer => customer.Id).IsRequired().ValueGeneratedOnAdd();

        builder.OwnsOne(customer => customer.Name, customerName =>
        {
            customerName.Property(name => name.FirstName).HasColumnName(nameof(Name.FirstName)).IsRequired().HasMaxLength(100);

            customerName.Property(name => name.LastName).HasColumnName(nameof(Name.LastName)).IsRequired().HasMaxLength(250);
        });
    }
}
```

### **BUG: CurrentValues.SetValues does not update owned types, but any other primitive properties are updated.**

```cs
var customer = Set.Find(1L);

var newCustomer = new
{
    Id = 1L,
    Name = new
    {
        FirstName = "Updated Name"
    }
}

_context.Entry(customer).CurrentValues.SetValues(newCustomer);
```

**Comment by AndriySvyryd** [comment] 2021-06-03 23:37
Use `context.Entry(customer).Reference("Name").TargetEntry.CurrentValues.SetValues(newCustomer.Name);`

Duplicate of https://github.com/dotnet/efcore/issues/18366

**Comment by rafaelfgx** [comment] 2021-06-04 00:46
@AndriySvyryd, thanks for answering.

How to do it dynamically? I would like to pass an object anonymous, without specify property names.

Is there any way? It would be interesting because that is the expected behavior, update all properties that are in the anonymous object.

**Comment by AndriySvyryd** [comment] 2021-06-04 01:20
I haven't tested it, but something like this:

```C#
var entry = context.Entry(entity);
var entityType = entry.Metadata;
foreach (var navigation in entityType.GetNavigations())
{
    if (navigation.IsOnDependent
        || navigation.IsCollection
        || !navigation.ForeignKey.IsOwnership)
    {
        continue;
    }

    entry.Reference(navigation.Name).TargetEntry.CurrentValues.SetValues(
        navigation.GetGetter().GetClrValue(newEntity));
}
```

And you probably will want to invoke this recursively.

**Comment by rafaelfgx** [comment] 2021-06-04 01:27
With your guidance I will test and implement what is necessary. You helped a lot, thanks again!

**Closed** 2022-10-16 19:36 UTC
Labels: customer-reported
