### ISSUE TITLE
Configuring entity framework in an IServiceCollection extension breaks tools

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/efcore#19709] opened 2020-01-25 20:55 UTC
I have an extension method in my project that looks like this:

```csharp
        // ...

        public static IServiceCollection AddMyEntityFramework(this IServiceCollection services, IConfiguration configuration)
        {
            services.AddDbContext<IdentityDbContext>((options) =>
            {
                options
                    .UseSqlServer(configuration.GetConnectionString("Identity"))
                    .UseOpenIddict();
            });

            return services;
        }

        // ...
```

When I go to generate migrations:

```powershell
dotnet ef migrations add InitialCreate --context MyProject.Api.Identity.IdentityDbContext --output-dir ./Migrations --verbose
```

I get this error:

```
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Found DbContext 'IdentityDbContext'.
Finding DbContext classes in the project...
Found DbContext 'IdentityDbContext'.
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'IdentityDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
 ---> System.MissingMethodException: No parameterless constructor defined for type 'MyProject.Api.Identity.IdentityDbContext'.
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_3.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to create an object of type 'IdentityDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

If however I simply move the body of the extension method back into `Startup.cs` and adapt it to work there:

```csharp
            // ...

            services.AddDbContext<IdentityDbContext>((options) =>
            {
                options
                    .UseSqlServer(Configuration.GetConnectionString("Identity"))
                    .UseOpenIddict();
            });

            // ...
```

It works...?? 😕

### Steps to reproduce

You can use my code above to pretty easily create a repro.

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system: Windows 10 Pro
IDE: Visual Studio Code

**Comment by ajcvickers** [comment] 2020-01-27 20:25
@atrauzzi I copied your code into a default web application and it works for me. Please post a small, runnable project that reproduces the behavior your are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-02-03 17:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:07 UTC
Labels: closed-could-not-reproduce, customer-reported
