### ISSUE TITLE
Cosmos throwing error when partitionKey defined as Key as well

### ISSUE THREAD

**Issue by UmutAkkaya** [dotnet/efcore#20320] opened 2020-03-17 21:25 UTC
I have one Guid that I defined as a partition key as well as a regular key like
``` C#
   modelBuilder.Entity<UserConfiguration>().HasKey(c => c.ClientId);
   modelBuilder.Entity<UserConfiguration>().HasPartitionKey(o => o.ClientId);
```
No errors thrown on compile time but on runtime when saving an entity the following error is thrown: 

> StartIndex cannot be less than zero. (Parameter 'startIndex')'

Afaiu this is thrown due to key being a partition key as well. Im not sure if this is an intended error, if so there needs to be a more clear error.

### Steps to reproduce

You can create a very simple object with an id and in `OnModelCreating` define that id as both key and partition key. Try adding an entity to that collection.  `_context.Add(...)` should fail with the same error

```System.ArgumentOutOfRangeException: StartIndex cannot be less than zero. (Parameter 'startIndex')
   at System.Text.StringBuilder.Remove(Int32 startIndex, Int32 length)
   at Microsoft.EntityFrameworkCore.Cosmos.ValueGeneration.Internal.IdValueGenerator.NextValue(EntityEntry entry)
   at Microsoft.EntityFrameworkCore.ValueGeneration.ValueGenerator.Next(EntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ValueGenerationManager.Generate(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity](TEntity entity)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
   at Gemstone.UserConfiguration.Api.Services.SplitService.GetExperimentForClient(String experimentName, Guid individualClientId) in C:\Projects\bw-user-configuration-ms\src\Gemstone.UserConfiguration.Api\Services\SplitService.cs:line 39
   at Gemstone.UserConfiguration.Api.Controllers.ExperimentController.GetExperiment(String experimentName, Guid individualClientId) in C:\Projects\bw-user-configuration-ms\src\Gemstone.UserConfiguration.Api\Controllers\ExperimentController.cs:line 24
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)```


### Further technical details

EF Core version: 3.1.2
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) cosmos
Target framework: (e.g. .NET Core 3.0) netcoreapp3.1
Operating system: windows
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by AndriySvyryd** [comment] 2020-03-18 03:34
Duplicate of https://github.com/dotnet/efcore/issues/18428

**Closed** 2022-10-16 18:16 UTC
Labels: customer-reported
