### ISSUE TITLE
Microsoft.EntityFrameworkCore.InMemory KeyNotFoundException 'The given key '_' was not present in the dictionary.

### ISSUE THREAD

**Issue by Truptiranpise** [dotnet/efcore#23583] opened 2020-12-04 10:32 UTC
```Microsoft.EntityFrameworkCore.InMemory KeyNotFoundException 'The given key '_' was not present in the dictionary.```

Error occurred while trying to do a nested select from a one to many DbSets.
This error occurs when my test project calls this code. Test project uses EF core with in-memory DB.

My main project uses EF core for SQL server with AspnetCore and mainproject code works, but my test project calling this code throws 'KeyNotFoundException' with this line  ```.Include(_ => _.Photos) ```

MainProject:
Microsoft.AspNetCore.App 2.1.1
Microsoft.EntityFrameworkCore.SqlServer 2.1.14
    

Test project:
netcoreapp3.1
Microsoft.EntityFrameworkCore.InMemory 2.1.4    
 
Main project code:
```C#
public class Profile {
        public Profile() {
        }

        public int Id { get; set; }
        public ICollection<Photo> Photos { get; set; }
        public Information Info { get; set; }
}
public class Information {
 public Information() {
        }
  public string Name {get; set;}
  public int Age {get; set;}
} 
public class Photo {
 public Photo() {
        }
        public int Id { get; set; }
        public string ImageUrl {get; set;}
        public Photographer Photographer {get; set;}
}
public class Photographer {
 public Photographer() {
        }
        public int Id { get; set; }
        public string Name {get; set;}
}

static void Main(string[] args)
        {
            var Id = Guid.NewGuid();
            using (var _dbContext = new AppDbContext())
            {

                var model = _dbContext.Profile
                    .Include(_ => _.Info)
                    .Include(_ => _.Photos)
                        .ThenInclude(photo => photo.Photographer)
                   .Where(x => x.Id == Id)
                   .SingleOrDefaultAsync()
            }
        }
```

### stack trace

```
System.Collections.Generic.KeyNotFoundException : The given key '__' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.DefaultQueryExpressionVisitor.GetParameterValue[T](QueryContext queryContext, String parameterName)
   at lambda_method(Closure , AnonymousObject )
   at System.Linq.Lookup`2.CreateForJoin(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.JoinIterator[TOuter,TInner,TKey,TResult](IEnumerable`1 outer, IEnumerable`1 inner, Func`2 outerKeySelector, Func`2 innerKeySelector, Func`3 resultSelector, IEqualityComparer`1 comparer)+MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollection[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relatedEntitiesFactory, Func`3 joinPredicate)
   at lambda_method(Closure , QueryContext , Profile , Object[] )
   at lambda_method(Closure , TransparentIdentifier`2 )
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at System.Linq.AsyncEnumerable.AsyncEnumerableAdapter`1.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
```

**Comment by smitpatel** [comment] 2020-12-04 16:42
Duplicate of #9849

**Closed** 2022-10-16 19:13 UTC
Labels: customer-reported
