### ISSUE TITLE
Update entity using isModified = false do update the DB sometime

### ISSUE THREAD

**Issue by Antoinedavidcytiva** [dotnet/efcore#31295] opened 2023-07-18 15:02 UTC
Hello,

I am getting a strange situation using the "IsModified = false" property when trying to update an entry but with keeping some field unchanged.

Here is my code
```

            using (var context = new DbContext())
            {
                context.Entry(toUpdate).State = EntityState.Modified;
                context.Entry(toUpdate).Property(e => e.CreatedAt).IsModified = false;
                context.Entry(toUpdate).Property(e => e.CreatedAtUtc).IsModified = false;
                context.SaveChanges();
            } 
```

CreatedAt and CreatedAtUtc are to filed of format DateTime.

With this code, on some machine, everything is working fine, entry is updated keeping theses fields unchanged. On some other machines (same code, same data) my field "CreatedAtUtc" is modified and set to a date time min value (01/01/01)... I cannot understand the difference of behavior and also do not understand if something is wrong the code above. Any recommendation or hints about the usage of IsModified = false?

Thanks,
a.

**Comment by ajcvickers** [comment] 2023-07-18 16:00
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-08-02 19:12
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-08-02 19:12 UTC
Labels: customer-reported
