### ISSUE TITLE
Method not found: 'System.String System.AppContex t.get_TargetFrameworkName()'

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [dotnet/efcore#14810] opened 2019-02-25 10:00 UTC
Hi, I'm using last version of ef core (3.0.0-preview.19074.3), It works in my computer but not working in another computer, some computers i got this error:

```charp
System.MissingMethodException: Method not found: 'System.String System.AppContex
t.get_TargetFrameworkName()'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrAccessorFactory`1.Creat
e(PropertyInfo propertyInfo, IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrAccessorFactory`1.Creat
e(PropertyInfo propertyInfo)
   at Microsoft.EntityFrameworkCore.Internal.DbSetFinder.<>c__DisplayClass2_0.<F
indSets>b__2(PropertyInfo p)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Internal.DbSetFinder.FindSets(Type contextTy
pe)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Fu
nc`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbSetFinder.FindSets(DbContext cont
ext)
   at Microsoft.EntityFrameworkCore.Internal.DbSetInitializer.InitializeSets(DbC
ontext context)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at Microsoft.EntityFrameworkCore.DbContext..ctor()
   at Azadegan.Server.DataBase.Contexts.AzadeganContext..ctor() in D:\Atitec\Old
\Azadegan\Server\Azadegan.Server.DataBase\Contexts\AzadeganContext.cs:line 63
   at Azadegan.ConsoleTest.Program.Main(String[] args) in D:\Atitec\Old\Azadegan
\Server\Azadegan.ConsoleTest\Program.cs:line 23

```

My line 23 is:

```csharp
using (AzadeganContext context = new AzadeganContext())
```

**Comment by ajcvickers** [comment] 2019-02-25 20:50
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2019-03-04 17:34
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:53 UTC
Labels: closed-could-not-reproduce, customer-reported
