### ISSUE TITLE
Query: deadlock for async query with inner ToList in conjunction with AsNoTracking and OrderBy

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12382] opened 2018-06-15 22:12 UTC
Reported here: #12337

```cs
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var b1 = new Book { Title = "b1" };
                var b2 = new Book { Title = "b1" };
                var a = new Author { Name = "a1", Books = new List<Book> { b1, b2 } };
                ctx.Books.AddRange(b1, b2);
                ctx.Authors.Add(a);
                ctx.SaveChanges();
            }

            var t = new Test().Run();
            t.Wait();
        }
    }


    public class Test
    {
        public async Task Run()
        {
            using (var ctx = new MyContext())
            {
                var query = (from a in ctx.Authors
                             select new
                             {
                                 a.Name,
                                 Books = a.Books.Select(b => b.Title).ToList()
                             })
                             .AsNoTracking()
                             .OrderBy(a => a.Name);
                await query.ToListAsync();    // Deadlock
            }
        }
    }

    public class Author
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public List<Book> Books { get; set; }
    }

    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
    }


    public class MyContext : DbContext
    {
        public DbSet<Author> Authors { get; set; }
        public DbSet<Book> Books { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=Repro12337;Trusted_Connection=True;MultipleActiveResultSets=True");
        }
    }
```

is reported to deadlock on async.

QueryPlan we generate is as follows:

```
(QueryContext queryContext) => IAsyncEnumerable<<>f__AnonymousType0<string, List<string>>> _InterceptExceptions(
|__ source: IOrderedAsyncEnumerable<<>f__AnonymousType0<string, List<string>>> _OrderBy(
|   |__ source: IAsyncEnumerable<<>f__AnonymousType0<string, List<string>>> _SelectAsync(
|   |   |__ source: IAsyncEnumerable<ValueBuffer> _ShapedQuery(
|   |   |   |__ queryContext: queryContext, 
|   |   |   |__ shaperCommandContext: SelectExpression: 
|   |   |   |       SELECT [a0].[Name], [a0].[Id]
|   |   |   |       FROM [Authors] AS [a0], 
|   |   |   |__ shaper: ValueBufferShaper), 
|   |   |__ selector: (ValueBuffer a | CancellationToken ct) => Task<<>f__AnonymousType0<string, List<string>>> _ExecuteAsync(
|   |       |__ taskFactories: new Func<Task<object>>[]{ () => Task<object> _ToObjectTask(Task<List<string>> ToList(
|   |       |   |__ source: IAsyncEnumerable<string> _Select(
|   |       |   |   |__ source: IAsyncEnumerable<ValueBuffer> _InjectParameters(
|   |       |   |   |   |__ queryContext: queryContext, 
|   |       |   |   |   |__ source: IAsyncEnumerable<ValueBuffer> _ShapedQuery(
|   |       |   |   |   |   |__ queryContext: queryContext, 
|   |       |   |   |   |   |__ shaperCommandContext: SelectExpression: 
|   |       |   |   |   |   |       SELECT [b0].[Title]
|   |       |   |   |   |   |       FROM [Books] AS [b0]
|   |       |   |   |   |   |       WHERE @_outer_Id1 = [b0].[AuthorId], 
|   |       |   |   |   |   |__ shaper: ValueBufferShaper), 
|   |       |   |   |   |__ parameterNames: new string[]{ "_outer_Id1" }, 
|   |       |   |   |   |__ parameterValues: new object[]{ (object)Nullable<int> TryReadValue(a, 1, Author.Id) }), 
|   |       |   |   |__ selector: (ValueBuffer b) => string TryReadValue(b, 0, Book.Title)), 
|   |       |   |__ cancellationToken: queryContext.CancellationToken)) }, 
|   |       |__ selector: (object[] results) => new { 
|   |               string TryReadValue(a, 0, Author.Name), 
|   |               (List<string>)results[0]
|   |            })), 
|   |__ expression: (<>f__AnonymousType0<string, List<string>> a) => a.Name, 
|   |__ orderingDirection: Asc), 
|__ contextType: Repro12337.MyContext, 
|__ logger: DiagnosticsLogger<Query>, 
|__ queryContext: queryContext)
```

**Comment by smitpatel** [comment] 2019-12-06 01:39
Duplicate of #12337

**Closed** 2022-10-16 12:31 UTC
Labels: customer-reported, area-query
