### ISSUE TITLE
Add migration doesn't work and doesn't show error message "add-migration : Value does not fall within the expected range."

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#30674] opened 2023-04-12 09:26 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-migration-doesnt-work-and-doesnt-s/10323863)._

---
[severity:I'm unable to use this version]
If I add a migration in my project I get the error add-migration : Value does not fall within the expected range.

But I didnt' get any detail of the error

PM> add-migration SepararChunk2 -verbose
Using project 'Anexo\MC.AspNetCore.Anexo.EntityFrameworkCore'.
Using startup project 'Anexo\MC.AspNetCore.Anexo.Controllers'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\NugetPackages\net7.0\MC.AspNetCore.Anexo.Controllers.deps.json" --additionalprobingpath C:\Users\lfbic\.nuget\packages C:\Users\lfbic\.nuget\packages\microsoft.entityframeworkcore.tools\7.0.4\tools\netcoreapp2.0\any\ef.dll migrations add SepararChunk2 --json --verbose --no-color --prefix-output --assembly "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\NugetPackages\ net7.0\MC.AspNetCore.Anexo.EntityFrameworkCore.dll" --project "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\MC.AspNetCore.Anexo.EntityFrameworkCore.csproj" --startup-assembly "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\NugetPackages\net7.0\MC.AspNetCore.Anexo.Controllers.dll" --startup-project "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.Controllers\MC.AspNetCore.Anexo.Controllers.csproj" -- project-dir "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\\" --language C# --configuration Debug --working-dir "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao" --root-namespace MC.AspNetCore.Anexo.EntityFrameworkCore --nullable
To undo this action, use Remove-Migration.
add-migration : Value does not fall within the expected range.
At line:1 char:1
+ add-migration SepararChunk2 -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Add-Migration], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Add-Migration

---
#### Feedback Bot on 3/28/2023, 02:45 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2023-04-12 09:30
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-04-19 19:18
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-04-19 19:18 UTC
Labels: customer-reported

**Comment by luizfbicalho** [comment] 2023-04-24 12:46
I think I have the same issue, If I try to use the add-migration I get this error, if I try to use the dotnet ef migrations I don't get any error but I don't get the migration

This project is just a library, so I addedd the appsettings.json and the ContextFactory, but I can't get the migration running and no error message

this is the verbose result


```
PS C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore> dotnet ef migrations -v add ValidacaoAnexosAzureStorage
Using project 'C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\MC.AspNetCore.Anexo.EntityFrameworkCore.csproj'.
Using startup project 'C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\MC.AspNetCore.Anexo.EntityFrameworkCore.csproj'.
Writing 'C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\obj\MC.AspNetCore.Anexo.EntityFrameworkCore.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\lfbic\AppData\Local\Temp\tmp66B9.tmp /verbosity:quiet /nologo "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\MC.AspNetCore.Anexo.EntityFrameworkCore.csproj"
Writing 'C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\obj\MC.AspNetCore.Anexo.EntityFrameworkCore.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\lfbic\AppData\Local\Temp\tmp696A.tmp /verbosity:quiet /nologo "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\MC.AspNetCore.Anexo.EntityFrameworkCore.csproj"
Build started...
dotnet build "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\MC.AspNetCore.Anexo.EntityFrameworkCore.csproj" /verbosity:quiet /nologo
C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\Migrations\20230324201741_SepararChunk.cs(46,31): warning CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<byte>() instead. [C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\MC.AspNetCore.Anexo.EntityFrameworkCore.csproj]

Build succeeded.

C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\Migrations\20230324201741_SepararChunk.cs(46,31): warning CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<byte>() instead. [C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\MC.AspNetCore.Anexo.EntityFrameworkCore.csproj]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.34
Build succeeded.
dotnet exec --depsfile "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\NugetPackages\net7.0\MC.AspNetCore.Anexo.EntityFrameworkCore.deps.json" --additionalprobingpath C:\Users\lfbic\.nuget\packages --runtimeconfig "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\NugetPackages\net7.0\MC.AspNetCore.Anexo.EntityFrameworkCore.runtimeconfig.json" C:\Users\lfbic\.dotnet\tools\.store\dotnet-ef\7.0.4\dotnet-ef\7.0.4\tools\net6.0\any\tools\netcoreapp2.0\any\ef.dll migrations add ValidacaoAnexosAzureStorage --assembly "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\NugetPackages\net7.0\MC.AspNetCore.Anexo.EntityFrameworkCore.dll" --project "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\MC.AspNetCore.Anexo.EntityFrameworkCore.csproj" --startup-assembly "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\NugetPackages\net7.0\MC.AspNetCore.Anexo.EntityFrameworkCore.dll" --startup-project "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\MC.AspNetCore.Anexo.EntityFrameworkCore.csproj" --project-dir "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore\\" --root-namespace MC.AspNetCore.Anexo.EntityFrameworkCore --language C# --framework net7.0 --nullable --working-dir "C:\ProjetosGIT\Tenper\Biblioteca Autenticacao\MC.AspNetCore.Anexo.EntityFrameworkCore" --verbose
```

**Comment by luizfbicalho** [comment] 2023-04-24 16:52
@ajcvickers  I reproduced it in a smaller project

[MC.AspNetCore.Anexo.EntityFrameworkCore.zip](https://github.com/dotnet/efcore/files/11312794/MC.AspNetCore.Anexo.EntityFrameworkCore.zip)

**Comment by ajcvickers** [comment] 2023-04-24 19:01
@luizfbicalho Still not able to reproduce this. What version of Visual Studio are you using, and on what OS?

Here's my output:

```
PM> Add-Migration One -Verbose
Using project 'MC.AspNetCore.Anexo.EntityFrameworkCore'.
Using startup project 'MC.AspNetCore.Anexo.EntityFrameworkCore'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\local\code\repros\NugetPackages\net7.0\MC.AspNetCore.Anexo.EntityFrameworkCore.deps.json --additionalprobingpath C:\Users\ajcvi\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --runtimeconfig C:\local\code\repros\NugetPackages\net7.0\MC.AspNetCore.Anexo.EntityFrameworkCore.runtimeconfig.json C:\Users\ajcvi\.nuget\packages\microsoft.entityframeworkcore.tools\7.0.5\tools\netcoreapp2.0\any\ef.dll migrations add One --json --verbose --no-color --prefix-output --assembly C:\local\code\repros\NugetPackages\net7.0\MC.AspNetCore.Anexo.EntityFrameworkCore.dll --project C:\local\code\repros\MC.AspNetCore.Anexo.EntityFrameworkCore\MC.AspNetCore.Anexo.EntityFrameworkCore.csproj --startup-assembly C:\local\code\repros\NugetPackages\net7.0\MC.AspNetCore.Anexo.EntityFrameworkCore.dll --startup-project C:\local\code\repros\MC.AspNetCore.Anexo.EntityFrameworkCore\MC.AspNetCore.Anexo.EntityFrameworkCore.csproj --project-dir C:\local\code\repros\MC.AspNetCore.Anexo.EntityFrameworkCore\ --language C# --configuration Debug --working-dir C:\local\code\repros\MC.AspNetCore.Anexo.EntityFrameworkCore --root-namespace MC.AspNetCore.Anexo.EntityFrameworkCore --nullable
Using assembly 'MC.AspNetCore.Anexo.EntityFrameworkCore'.
Using startup assembly 'MC.AspNetCore.Anexo.EntityFrameworkCore'.
Using application base 'C:\local\code\repros\NugetPackages\net7.0'.
Using working directory 'C:\local\code\repros\MC.AspNetCore.Anexo.EntityFrameworkCore'.
Using root namespace 'MC.AspNetCore.Anexo.EntityFrameworkCore'.
Using project directory 'C:\local\code\repros\MC.AspNetCore.Anexo.EntityFrameworkCore\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'AnexoModelContextFactory'.
Found DbContext 'AnexoModelContext'.
Finding application service provider in assembly 'MC.AspNetCore.Anexo.EntityFrameworkCore'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'AnexoModelContextFactory'.
Using context 'AnexoModelContext'.
Finding design-time services referenced by assembly 'MC.AspNetCore.Anexo.EntityFrameworkCore'...
Finding design-time services referenced by assembly 'MC.AspNetCore.Anexo.EntityFrameworkCore'...
No referenced design-time services were found.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding IDesignTimeServices implementations in assembly 'MC.AspNetCore.Anexo.EntityFrameworkCore'...
No design-time services were found.
Writing migration to 'C:\local\code\repros\MC.AspNetCore.Anexo.EntityFrameworkCore\Migrations\20230424190033_One.cs'.
Writing model snapshot to 'C:\local\code\repros\MC.AspNetCore.Anexo.EntityFrameworkCore\Migrations\AnexoModelContextModelSnapshot.cs'.
'AnexoModelContext' disposed.
To undo this action, use Remove-Migration.
PM>
```

**Comment by ajcvickers** [comment] 2023-04-24 19:50
In my PMC window I see this:

```
Each package is licensed to you by its owner. NuGet is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 6.6.0.61

Type 'get-help NuGet' to see all available NuGet commands.

PM> Add-Migration One -Verbose
```

So I expect you need to update the PowerShell version being used by PMC. But I don't know how to do this.

**Comment by luizfbicalho** [comment] 2023-04-24 19:55
Thanks @ajcvickers  I'll update here


But why it doesn't generate in the command line and doesn't show any error message?

**Comment by ajcvickers** [comment] 2023-04-24 19:57
> But why it doesn't generate in the command line and doesn't show any error message?

I don't know; could also be related to the vesion?

**Comment by luizfbicalho** [comment] 2023-04-24 20:02
Is there a way to run a debug version, generate a trace log, some kind of information that would help me to figure it out, everything is up to date now and I still get this error, other projects doesn't show this migration error

**Comment by ajcvickers** [comment] 2023-04-25 19:15
@luizfbicalho Not realistically. Given that the -Verbose option isn't even working, I have no idea what is going on.

**Comment by ajcvickers** [comment] 2023-04-25 19:17
@luizfbicalho Does removing references to `CommunityToolkit.Diagnostics`, `MC.WebApi.Extensions`, and `nerdbank.GitVersioning` make any difference?

**Comment by luizfbicalho** [comment] 2023-04-25 19:54
I Removed both and still the same error, 
now I updated the Visual studio to Preview 5.0, still the same error

If you have any idea of how I could give more information, or how can I send you something else to make it not work, or any way that I can create some isolated place to run this

**Comment by vitorquezada** [comment] 2024-10-15 00:51
I have the same problem.
Success message and no error messages on add migration command.
Output below.

The solution: Rename the project path to reduce the size path.
After that the command works and generates the migration.

```
dotnet ef migrations add Init -p .\src\VizeProdutos.Infra.RelationalData\VizeProdutos.Infra.RelationalData.csproj -s .\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj -c VizeDbContext -v
Using project 'D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Infra.RelationalData\VizeProdutos.Infra.RelationalData.csproj'.
Using startup project 'D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj'.
Writing 'D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Infra.RelationalData\obj\VizeProdutos.Infra.RelationalData.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\vitor\AppData\Local\Temp\tmpmcabkn.tmp /verbosity:quiet /nologo D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Infra.RelationalData\VizeProdutos.Infra.RelationalData.csproj
Writing 'D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\obj\VizeProdutos.Client.Worker.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\vitor\AppData\Local\Temp\tmpivrxhi.tmp /verbosity:quiet /nologo D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj
Build started...
dotnet build D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj /verbosity:quiet /nologo /p:PublishAot=false
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Infra.RelationalData\VizeProdutos.Infra.RelationalData.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida. [D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj]
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Common\VizeProdutos.Client.Common.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida. [D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj]
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Core.Anexos.Business\VizeProdutos.Core.Anexos.Business.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida. [D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj]
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depends on Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0) but Microsoft.PowerPlatform.Dataverse.Client 1.0.0 was not found. An approximate best match of Microsoft.PowerPlatform.Dataverse.Client 1.0.1 was resolved.
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Infra.Common\VizeProdutos.Infra.Common.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida. [D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj]
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depends on Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0) but Microsoft.PowerPlatform.Dataverse.Client 1.0.0 was not found. An approximate best match of Microsoft.PowerPlatform.Dataverse.Client 1.0.1 was resolved.
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Core.Anexos.Business\VizeProdutos.Core.Anexos.Business.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida.
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Common\VizeProdutos.Client.Common.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida.
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Infra.Common\VizeProdutos.Infra.Common.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida.
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Infra.RelationalData\VizeProdutos.Infra.RelationalData.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida.
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\Configuration\VizeTimeZoneResolver.cs(17,62): warning CS8600: Conversão de literal nula ou possível valor nulo em tipo não anulável. [D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj]
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\Jobs\HangfireJobConfiguration.cs(19,17): warning CS0618: "RecurringJob.AddOrUpdate<T>(string, Expression<Func<T, Task>>, string, TimeZoneInfo, string)" é obsoleto: "Please use AddOrUpdate<T>(string, Expression<Func<T, Task>>, string, RecurringJobOptions) instead. Will be removed in 2.0.0." [D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj]
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\Controllers\AnexoCrmController.cs(52,69): warning CS8602: Desreferência de uma referência possivelmente nula. [D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj]

Compilação com êxito.

D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Infra.RelationalData\VizeProdutos.Infra.RelationalData.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida. [D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj]
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Common\VizeProdutos.Client.Common.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida. [D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj]
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Core.Anexos.Business\VizeProdutos.Core.Anexos.Business.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida. [D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj]
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depends on Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0) but Microsoft.PowerPlatform.Dataverse.Client 1.0.0 was not found. An approximate best match of Microsoft.PowerPlatform.Dataverse.Client 1.0.1 was resolved.
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Infra.Common\VizeProdutos.Infra.Common.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida. [D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj]
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depends on Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0) but Microsoft.PowerPlatform.Dataverse.Client 1.0.0 was not found. An approximate best match of Microsoft.PowerPlatform.Dataverse.Client 1.0.1 was resolved.
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Core.Anexos.Business\VizeProdutos.Core.Anexos.Business.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida.
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Common\VizeProdutos.Client.Common.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida.
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Infra.Common\VizeProdutos.Infra.Common.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida.
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Infra.RelationalData\VizeProdutos.Infra.RelationalData.csproj : warning NU1603: Microsoft.PowerPlatform.Dataverse.Client.Dynamics 1.1.12 depende de Microsoft.PowerPlatform.Dataverse.Client (>= 1.0.0), mas Microsoft.PowerPlatform.Dataverse.Client 1.0.0 não foi encontrado. A melhor correspondência aproximada de Microsoft.PowerPlatform.Dataverse.Client 1.0.1 foi resolvida.
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\Configuration\VizeTimeZoneResolver.cs(17,62): warning CS8600: Conversão de literal nula ou possível valor nulo em tipo não anulável. [D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj]
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\Jobs\HangfireJobConfiguration.cs(19,17): warning CS0618: "RecurringJob.AddOrUpdate<T>(string, Expression<Func<T, Task>>, string, TimeZoneInfo, string)" é obsoleto: "Please use AddOrUpdate<T>(string, Expression<Func<T, Task>>, string, RecurringJobOptions) instead. Will be removed in 2.0.0." [D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj]
D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\Controllers\AnexoCrmController.cs(52,69): warning CS8602: Desreferência de uma referência possivelmente nula. [D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj]
    13 Aviso(s)
    0 Erro(s)

Tempo Decorrido 00:00:04.21
Build succeeded.
dotnet exec --depsfile D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\bin\Debug\net6.0\VizeProdutos.Client.Worker.deps.json --additionalprobingpath C:\Users\vitor\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --runtimeconfig D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\bin\Debug\net6.0\VizeProdutos.Client.Worker.runtimeconfig.json C:\Users\vitor\.dotnet\tools\.store\dotnet-ef\8.0.10\dotnet-ef\8.0.10\tools\net8.0\any\tools\netcoreapp2.0\any\ef.dll migrations add Init -c VizeDbContext --assembly D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\bin\Debug\net6.0\VizeProdutos.Infra.RelationalData.dll --project D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Infra.RelationalData\VizeProdutos.Infra.RelationalData.csproj --startup-assembly D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\bin\Debug\net6.0\VizeProdutos.Client.Worker.dll --startup-project D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Client.Worker\VizeProdutos.Client.Worker.csproj --project-dir D:\dev\Vize\VizeProdutoAnexo\src\VizeProdutos.Infra.RelationalData\ --root-namespace VizeProdutos.Infra.RelationalData --language C# --framework net6.0 --nullable --working-dir D:\dev\Vize\VizeProdutoAnexo --verbose
```

**Comment by luizfbicalho** [comment] 2024-11-20 16:14
I'm not sure if it helps, my problem I solved running the add migration in the WSL @ajcvickers 

And still fails in .net 9

**Comment by luizfbicalho** [comment] 2024-11-22 12:38
Another information on this @ajcvickers 

if i create a new VM the migration works fine, so the problem is something in this VM
But I have one other project in this VM that creates the migrations, so there is a way to go

Bottom line, I imagined that the problem was that the migration and the main project was the same, then I created a new main as a console application

and the error continued

Then I created a main that was a web API project, just like the one that worked, 
Just an empty Web API and copy the dbcontext initializer, and the migration worked fine.


With this information in mind, what do you think is going on?
