### ISSUE TITLE
Create additional .NET attributes (like data annotations) for EF Core configuration

### ISSUE THREAD

**Issue by eduherminio** [dotnet/efcore#10111] opened 2017-10-18 07:49 UTC
I guess there some good reason not to do it, but here it is the suggestion just in case.

**Comment by ajcvickers** [comment] 2017-10-18 19:53
@eduherminio The reason is that it used a combination of Key and Column for ordering, but column ordering is not the same thing as key ordering, and so this caused confusion and issues in EF6. Changing existing data annotations is also costly because of their relationship to .NET Core and .NET Framework. 

However, we see the value in being able to this and other common configuration using attributes, since the jump to the fluent API can be a big one. Therefore, we will investigate creating a new library/package with additional new EF configuration attributes that can be used alongside data annotations. This would be one of the things that would be implemented there.

**Comment by ajcvickers** [comment] 2018-02-21 20:58
See also #11003 for the specific case of configuring a composite key.

**Comment by SoaresMG** [comment] 2018-06-03 16:28
I've an application with almost 1000 tables which 100-150 use composite keys.
I didn't use a single LOC for fluent API, purely using Data Annotations.
So... I won't be able to run from fluent API because of "confusion"?
Is this the right approach?

**Comment by ajcvickers** [comment] 2018-06-05 01:11
@SoaresMG This issue is in the Backlog milestone. This means that it is not scheduled to happen for the 2.2 or 3.0 releases. We will re-assess the backlog following the 3.0 release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by SoaresMG** [comment] 2018-06-05 09:07
@ajcvickers I see... I was just trying my luck. 👍

**Comment by ajcvickers** [comment] 2018-08-13 16:37
Consider ToView. See https://github.com/aspnet/EntityFramework.Docs/issues/913

**Comment by ajcvickers** [comment] 2019-01-30 22:19
@divega to split out into different issues for each attribute.

**Comment by ajcvickers** [comment] 2019-09-04 22:04
Closing as a duplicate of #10864 since that issue has more votes.

**Closed** 2022-10-16 11:54 UTC
