### ISSUE TITLE
SqliteCommand.ExecuteReaderAsync with CommandBehavior.CloseConnection appears broken

### ISSUE THREAD

**Issue by tdinucci** [dotnet/efcore#14674] opened 2019-02-12 00:01 UTC
**Edit**: _This issue is present in v2.2.1 but not v2.0.0_

When creating an SqliteDataReader using CommandBehavior.CloseConnection from an SqliteCommand which is disposed the reader and connection are closed prematurely.

### Steps to reproduce

```c#
using (var cmd = GetDbCommand(statement))
{
     if (cmd.Connection.State != ConnectionState.Open)
         cmd.Connection.Open();

    cmd.CommandType = statement.Type;
    if (statement.Parameters != null)
    {
        // AddRange(...) seems to have a bug in SqliteCommand
        foreach (var parameter in statement.Parameters)
            cmd.Parameters.Add(parameter);
     }
    return await cmd.ExecuteReaderAsync(CommandBehavior.CloseConnection).ConfigureAwait(false);
}
```

### Further technical details
Operating system:  Ubuntu 18.04

From a very quick look it seems that the call shown below to this.DataReader.Dispose() on SqliteCommand is being called and the CommandBehavior is ignored. 

```c#
private void DisposePreparedStatements(bool disposing = true)
{
    if (disposing && this.DataReader != null)
    {
        this.DataReader.Dispose();
        this.DataReader = (SqliteDataReader) null;
    }
    ...
}
```

**Comment by ajcvickers** [comment] 2019-02-20 19:36
@bricelam to investigate for patch.

**Comment by bricelam** [comment] 2019-02-20 22:22
Duplicate of https://github.com/aspnet/Microsoft.Data.Sqlite/issues/484

BUT the architecture I have in mind for #14044 will remove the need to dispose SqliteCommand objects. It will also allow them to be disposed while their SqliteDataReader is open.

**Comment by bricelam** [comment] 2019-02-20 22:24
The workaround for your specific case is to not dispose the command object. It will get disposed when the connection is closed.

**Closed** 2022-10-16 13:51 UTC
Labels: customer-reported
