### ISSUE TITLE
default value for int property using fluent mapping produces unwanted identity specification

### ISSUE THREAD

**Issue by joeaudette** [dotnet/efcore#5431] opened 2016-05-19 21:06 UTC
In the process of migrating my [cloudscribe project](https://github.com/joeaudette/cloudscribe) from rc1 to rc2 and I ran into a problem after regenerating the migrations.

I'm using SqlServer provider

For every int property on my models if I specify a default value, the generated migration adds an unwanted identity specification. Example, the Sort property in this model:

```
public void Map(EntityTypeBuilder<Language> entity)
{
    //entity.ToTable(tableNames.TablePrefix + tableNames.LanguageTableName);
    entity.ForSqlServerToTable(tableNames.TablePrefix + tableNames.LanguageTableName);

    entity.HasKey(p => p.Id);

    entity.Property(p => p.Id)
       .ForSqlServerHasColumnType("uniqueidentifier")
       .ForSqlServerHasDefaultValueSql("newid()")
       ;

    entity.Property(p => p.Name)
    .HasMaxLength(255)
    .IsRequired()
    ;

    entity.Property(p => p.Code)
    .HasMaxLength(2)
    .IsRequired()
    ;

    entity.Property(p => p.Sort)
    .HasDefaultValue(1)
    ;

}
```

when I run the command line and generate the initial migration it generates this:

```
migrationBuilder.CreateTable(
    name: "cs_Language",
    columns: table => new
    {
        Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false, defaultValueSql: "newid()"),
        Code = table.Column<string>(nullable: false),
        Name = table.Column<string>(nullable: false),
        Sort = table.Column<int>(nullable: false, defaultValue: 1)
            .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_cs_Language", x => x.Id);
    });
```

notice the unwanted Annotation

I tried also adding

```
.ValueGeneratedNever()
```

and that seemed to get rid of the Annotation but I still got a runtime error about identity specification..

The only solution I found was to remove the .HasDefaultValue(1)

**Comment by AR1ES** [comment] 2016-05-21 12:59
I have the same problem.
As workaround I use `.HasDefaultValueSql("1")`.

**Comment by rowanmiller** [comment] 2016-05-23 20:16
Duplicate of https://github.com/aspnet/EntityFramework/issues/5384 - already assigned to fix for RTM.

**Closed** 2022-10-16 09:41 UTC
