### ISSUE TITLE
Scaffold-DbContext runs successfully but does not create any query

### ISSUE THREAD

**Issue by rich25200** [dotnet/efcore#27362] opened 2022-02-03 16:04 UTC
We have an active project which was started on .Net Core 3.1 . I'd like the move/migration to ASP.NET 6 and EFCore 6.0. I have update my models from database with this command line : 

```C#
dotnet-ef dbcontext scaffold "Data Source=XX.XX.XX.XX;Database=MyDatabase;User ID=XXPassword=XXX" Microsoft.EntityFrameworkCore.SqlServer --output-dir Context/DbContextSpvPaie --context-dir ./Context --context SpvPaieContext --force --no-onconfiguring --no-pluralize
```

My model has been updated and I can build the project without any problem.

Now when I create a API controller and I run for exemple this code 

```C#
var utilisateur = await _context.Utilisateur.FindAsync(id);
```

I have a problem in the Context.cs file
```
InvalidOperationException: Nullable object must have a value.
Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Type propertyType, string propertyName, MemberInfo memberInfo, Nullable<ConfigurationSource> typeConfigurationSource, Nullable<ConfigurationSource> configurationSource)
Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.GetActualProperties(IReadOnlyList<Property> properties, Nullable<ConfigurationSource> configurationSource)
Microsoft.EntityFrameworkCore.Metadata.Internal.InternalIndexBuilder.Attach(InternalEntityTypeBuilder entityTypeBuilder)
Microsoft.EntityFrameworkCore.Metadata.Internal.PropertiesSnapshot.Attach(InternalEntityTypeBuilder entityTypeBuilder)
Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Type propertyType, string propertyName, MemberInfo memberInfo, Nullable<ConfigurationSource> typeConfigurationSource, Nullable<ConfigurationSource> configurationSource)
Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.IndexerProperty(Type propertyType, string propertyName, Nullable<ConfigurationSource> configurationSource)
Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.IndexerProperty<TProperty>(string propertyName)
WebApplication1.Context.SpvPaieContext+<>c.<OnModelCreating>b__1142_1616(EntityTypeBuilder<Dictionary<string, object>> j) in SpvPaieContext.cs
```
-
```C#
                            j.HasKey("Id", "Entmat");
                            j.ToTable("ES_utilisateur_salarie_identification");
                            j.IndexerProperty<int>("Id").HasColumnName("id");
                            j.IndexerProperty<string>("Entmat").HasMaxLength(100);
                        });
            });
            modelBuilder.Entity<EsUtilisateurDevices>(entity =>
            {
                entity.HasKey(e => e.IdEsUtilisateurDevices);
Microsoft.EntityFrameworkCore.Metadata.Builders.CollectionCollectionBuilder<TLeftEntity, TRightEntity>.UsingEntity<TJoinEntity>(string joinEntityName, Func<EntityTypeBuilder<TJoinEntity>, ReferenceCollectionBuilder<TLeftEntity, TJoinEntity>> configureRight, Func<EntityTypeBuilder<TJoinEntity>, ReferenceCollectionBuilder<TRightEntity, TJoinEntity>> configureLeft, Action<EntityTypeBuilder<TJoinEntity>> configureJoinEntityType)
WebApplication1.Context.SpvPaieContext+<>c.<OnModelCreating>b__1142_103(EntityTypeBuilder<EsUtilisateur> entity) in SpvPaieContext.cs
-
                entity.Property(e => e.Password)
                    .HasMaxLength(255)
                    .HasColumnName("password");
                entity.Property(e => e.Salt).HasMaxLength(255);
                entity.HasMany(d => d.Entmat)
                    .WithMany(p => p.Id)
                    .UsingEntity<Dictionary<string, object>>(
                        "EsUtilisateurSalarieIdentification",
                        l => l.HasOne<SalariesIdentification>().WithMany().HasForeignKey("Entmat").HasConstraintName("SalarieAvoirEspaceSalarie"),
                        r => r.HasOne<EsUtilisateur>().WithMany().HasForeignKey("Id").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("EspaceSalarieAvoirEntmat"),
                        j =>
Microsoft.EntityFrameworkCore.ModelBuilder.Entity<TEntity>(Action<EntityTypeBuilder<TEntity>> buildAction)
WebApplication1.Context.SpvPaieContext.OnModelCreating(ModelBuilder modelBuilder) in SpvPaieContext.cs
```

I'm thinking it was my migration the problem but I have create a project from zero and I have the same problem when I use EF CORE 6 and .Net 6.

 I have tested with a new project but with .Net 5 and EF Core 5 and all is working fine.

Could you please tell me what's wrong? I have read some things and I think it's "nullable reference types in scaffolding" the problem.. How I can resolve this issue?

I want to keep the "dotnet-ef dbcontext scaffold" command line..

Thanks for your help.

### Include provider and version information

EF Core version: 6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:. NET 6.0
Operating system:
IDE: Visual Studio 2022

**Comment by AndriySvyryd** [comment] 2022-02-11 22:25
Possibly a duplicate of https://github.com/dotnet/efcore/issues/26590

Try 6.0.2. If you are still getting this error please share a small repro project with the generated code.

**Comment by Eltoney** [comment] 2022-02-17 21:33
how you solved the problem ? i have almost same thing build a new app with .net 6 and ef  6.0.2 and the build is successful but no folder is shown or created

**Comment by rich25200** [comment] 2022-02-18 15:03
My problem was not the same than you. For me, no linq sql was working in the application. I have had an error on all my requests.

**Closed** 2022-10-16 20:24 UTC
Labels: customer-reported
