### ISSUE TITLE
Look into the performance of AsNoTrackingWithIdentity

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#28579] opened 2022-08-03 07:34 UTC
We've received reports that AsNoTrackingWithIdentityResolution can perform 4 times slower compared to non-tracking queries. Of course, it's expected that identity resolution add an overhead, but this seems like a bit much. Also see how AsNoTrackingWithIdentityResolution is doing compared to tracking queries.

**Comment by ajcvickers** [comment] 2022-10-26 09:59
Duplicate of #23558.

**Closed by ajcvickers** 2022-10-26 09:59 UTC
Labels: type-enhancement, area-perf, consider-for-current-release, customer-reported, area-query, shay-loves-labels
