### ISSUE TITLE
Unable to load DLL 'sqlite3'

### ISSUE THREAD

**Issue by tmds** [dotnet/efcore#5382] opened 2016-05-17 07:11 UTC
I followed the aspnet rc2 documentation to scaffold a `Web Application` using yeoman on Ubuntu 14.04. The `dotnet ef database update` fails:

```

System.DllNotFoundException: Unable to load DLL 'sqlite3': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.Sqlite3_sqlite3.sqlite3_open_v2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
Unable to load DLL 'sqlite3': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
```

project.json contains:
`"Microsoft.EntityFrameworkCore.Sqlite": "1.0.0-rc2-final"`

**Comment by tmds** [comment] 2016-05-17 07:15
Manually installing `apt-get install -qqy sqlite3 libsqlite3-dev` fixes the issue.
Can't the native dependency be included in the package?

**Comment by ErikEJ** [comment] 2016-05-17 16:13
http://ef.readthedocs.io/en/latest/platforms/coreclr/getting-started-linux.html

**Comment by natemcmaster** [comment] 2016-05-17 16:13
It's been considered. Unfortunately, sqlite doesn't currently distribute native sqlite for linux in a NuGet package. We're working with the SQLite team to change this. See https://github.com/aspnet/Microsoft.Data.Sqlite/issues/237

And yes, as you mentioned, the solution is to install sqlite natively on linux. https://github.com/aspnet/Microsoft.Data.Sqlite#ubuntu

Closing as a duplicate of #5100

**Closed** 2022-10-16 09:40 UTC
