### ISSUE TITLE
Relational: TPC inheritance mapping pattern

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#3170] opened 2015-09-18 16:35 UTC
Consider configuring or issuing a warning to help with split identity seeding or shared sequence for the PK
FKs that point to a TPC entity type won't be enforced

- [x] Model support
- [x] Migrations support
- [x] Seed data support
- [x] SaveChanges support
- [x] Query support
- [x] End-to-end tests

Related: https://github.com/dotnet/efcore/issues/17270#issuecomment-588037768

**Comment by wangkanai** [comment] 2015-10-21 07:13
Can I make assumption that TPC is now going to be in RC? judged by the following work as expected
```
public class Program
{
    public void Main(string[] args)
    {
        var context = new InheritanceContext();
        var sarin = new Manager() {Name = "Sarin"};
        var siriphan = new Employee() {Name = "Siriphan", Manager = sarin};
        context.Managers.Add(sarin);
        context.Employees.Add(siriphan);
        context.SaveChanges();
    }
}

public class InheritanceContext : DbContext
{
    public DbSet<Manager> Managers { get; set; }
    public DbSet<Employee> Employees { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\MSSQLLocalDB;Database=Ef7Inheritance;Trusted_Connection=True;");
    }
}

public class Person
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class Manager : Person
{
    public Collection<Employee> Staffs { get; set; } 
}

public class Employee : Person
{
    public Manager Manager { get; set; }
}
```
![tpc](https://cloud.githubusercontent.com/assets/10666633/10629997/c46556c8-77fd-11e5-9cde-383c75c3fc2e.png)
This code is tested EntityFramework 7.0.0-beta8

**Comment by jimmymain** [comment] 2015-10-21 08:53
awesome!

**Comment by rowanmiller** [comment] 2015-10-21 16:12
@wangkanai you are really just getting two separate entity types with an unmapped base type. They each have a separate key space and you won't be able to run a LINQ query on `Person`. So it's not really inheritance in EF, it's two separate entity types that happen to share a base type in the CLR for implementation.

**Comment by wangkanai** [comment] 2015-10-21 17:42
If their are in same key space would that work well with sql server auto incremental primary key?

**Comment by rowanmiller** [comment] 2015-10-21 19:09
@wangkanai not with Identity (since that is per table) but you could use a sequence to generate values. What I really meant is that with true TPC you can't have Manager with Id = 1 and an Employee with Id = 1 since then you would have two instances of Person with Id = 1 (and EF would throw if you every tried to have this). In you setup this is possible since they aren't really in an inheritance hierarchy as far as EF is concerned.

**Comment by wangkanai** [comment] 2015-10-22 03:08
@rowanmiller so if in theory we make a convention to use Id as identity key as `Guid` (in theory it unique), this should work right?

**Comment by weitzhandler** [comment] 2015-10-23 14:24
I'd wanna see TPT before TPC. As @rowanmiller said, @wangkanai [example](https://github.com/aspnet/EntityFramework/issues/3170#issuecomment-149801318) will be used in rare cases when you explicitly wanna keep the entities unmapped or whatever other reason I can't think of now.
But TPT is even more important than TPH, because it can save a bunch of columns generated in each table completely DRYed and less-productive for some purposes.
Lack of TPC made me start a new project in MVC5 and give up the new beta.
Will this be implemented for the RC?

**Comment by rowanmiller** [comment] 2015-10-23 15:40
@wangkanai yep that would work. Just to be clear though... with the code you listed back at the start there is no need to ensure that the keys are unique between types since EF is treating them as completely separate types. But for true TPC, yes GUID keys is one option, or a sequence for numeric values, etc.

**Comment by jimmymain** [comment] 2015-12-04 05:50
@weitzhandler I agree. Our database teams design with high normal forms in mind. TPT is what's required. I am of the opinion that TPC is a weak compromise compared to TPT. I often need to query base classes, and TPC makes this easy. The most classic example of this is Martin Fowlers paper on [Roles](http://martinfowler.com/apsupp/roles.pdf)

**Comment by smitpatel** [comment] 2016-06-21 20:00
dupe of #2266

**Comment by weitzhandler** [comment] 2016-10-20 10:54
@jimmymain 
[Here](https://github.com/aspnet/EntityFramework/issues/2266) is the TPT discussion arena.

The funny part is that there are many things that are more convenient in ASP.NET Core (for example Identity), but in the big picture some really crucial deal-breaking features are missing (TPT).

**Comment by frogec** [comment] 2017-06-17 17:05
What is the status on this feature? This turns out to be a really important feature in our case.

**Comment by AndriySvyryd** [comment] 2017-09-19 01:16
The implementation could be simplified if we used a database model #8258

**Comment by sthiakos** [comment] 2017-11-02 16:39
+1 For Me - Note to all that you should "thumbs up" the initial post by @satyajit-behera to vote up this issue.  This and TPT is how DB's are/should be modeled.

**Comment by ite-klass** [comment] 2017-11-02 16:42
The roadmap lists both TPC and TPT as high priority. Sad to not see either of these tickets in the 2.1 or 3.0 milestone.

**Comment by ajcvickers** [comment] 2018-01-22 19:26
Note: see also #10739

**Comment by J4S0Nc** [comment] 2018-02-19 23:59
Will this ever make it in? 884 days and counting...

https://days.to/18-september/2015

**Comment by VocaTinityl** [comment] 2018-04-16 11:25
Any news about TPC ?

**Comment by ajcvickers** [comment] 2018-04-16 23:40
This issue is in the Backlog milestone. This means that it is not going to happen for the 2.1 release. We will re-assess the backlog following the 2.1 release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by alexdrl** [comment] 2018-05-28 08:27
@rowanmiller We're using TPC with something like https://github.com/aspnet/EntityFrameworkCore/issues/3170#issuecomment-149801318 but we're getting stuck trying to get one to one relationships to work. We get the following exception:


```
System.InvalidOperationException: A key cannot be configured on 'BloodPressure' because it is a derived type. The key must be configured on the root type 'Observation'. If you did not intend for 'Observation' to be included in the model, ensure that it is not included in a DbSet property on your context, referenced in a configuration call to ModelBuilder, or referenced from a navigation property on a type that is included in the model.
```

One to many relationships Works correctly, even considering that TPC is not supported in EF Core. Any idea for that?

**Comment by markusschaber** [comment] 2018-06-04 13:14
PostgreSQL supports inheritance on the table level (https://www.postgresql.org/docs/current/static/tutorial-inheritance.html). I don't know whether other databases also support this kind of inheritance, but it could map very well to C# as it's also single-inheritance, and thus be exposed in EF Core. It should deliver both optimal speed and space usage in most cases, thus performing better on average than TPC, TPH, TPT or the hackish "Use a single table for the base class, and stash all additional fields from subclasses in a JSON column" way.

**Comment by roji** [comment] 2018-06-04 13:35
@markusschaber PostgreSQL table inheritance is already tracked by #10739.

**Comment by markusschaber** [comment] 2018-06-04 13:38
@roji Thanks for the hint! Subscribing immediately :-)

**Comment by alexdrl** [comment] 2018-06-05 06:54
@ajcvickers The problem was a non-mapped reference to the abstract class that was not mapped to a table, this caused EF Core to acknowledge that table, and throwing an exception because the base class was being tracked in the context.

Based in the example by @wangkanai, this would be something like:


```csharp
public class Program
{
    public void Main(string[] args)
    {
        var context = new InheritanceContext();
        var sarin = new Manager() {Name = "Sarin"};
        var siriphan = new Employee() {Name = "Siriphan", Manager = sarin};
        context.Managers.Add(sarin);
        context.Employees.Add(siriphan);
        context.SaveChanges();
    }
}

public class InheritanceContext : DbContext
{
    public DbSet<Manager> Managers { get; set; }
    public DbSet<Employee> Employees { get; set; }
    public DbSet<Computer> Computers { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\MSSQLLocalDB;Database=Ef7Inheritance;Trusted_Connection=True;");
    }
}

public class Person
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class Manager : Person
{
    public Collection<Employee> Staffs { get; set; } 
}

public class Employee : Person
{
    public Manager Manager { get; set; }
}

public class Computer
{
    public string Name { get; set; }
    public Person User { get; set; }
}
```

Sorry, I'm trying to format the code with three backticks, but with no luck.

**Comment by ConX-Ryan** [comment] 2018-07-19 22:18
What is the timeline on this ? kind of a blocking Item for us

**Comment by AndriySvyryd** [comment] 2018-07-22 22:17
@ConX-Ryan See https://docs.microsoft.com/en-us/ef/core/what-is-new/roadmap

**Comment by Unitarian** [comment] 2018-07-30 13:14
I am having "duplicate primary key values" problem and I have read [somewhere](https://weblogs.asp.net/manavi/inheritance-mapping-strategies-with-entity-framework-code-first-ctp5-part-3-table-per-concrete-type-tpc-and-choosing-strategy-guidelines) that there are two ways to resolve this 

1. Use [DatabaseGenerated(DatabaseGenerationOption.None)] on base class primary key and not map it on child classes at all and manage Id values manually (which I don't want to do) 

2. Use the different initial seed for different types. Now I have 15 classes inherited from abstract BaseEntity class and I couldn't find any example of using the different initial seed for code first approach.

Can anyone please explain it to me how "different initial seed" works and is there any alternative to fix this without having to manage Id manually

Cheers

**Comment by brianjlowry** [comment] 2018-07-30 13:19
It continues to sit in the backlog. We had to rewrite everything in 4.7 as this was too much, and we had concerns around other things that may not be finished yet that we would find out later in our development process.

**Comment by MSiffert** [comment] 2019-03-10 16:34
In the docs about breaking changes of EF Core it says that 

> Starting with EF Core 3.0 and in preparation for adding TPT and TPC support in a later release

I assume that means TPT / TPC will be supported in 3.1 maybe 3.2?

**Comment by ajcvickers** [comment] 2019-03-10 18:30
@MSiffert It does not imply that. It just means we know it's a break we need to make, and making the break sooner is preferable to leaving it like this for longer.

**Comment by Grasher134** [comment] 2019-08-27 11:28
We are now moving a project that uses TPC to EF.Core. It is already built into architecture, is there any workaround we can use before TPC is officially supported? We used MapInheritedProperties(), but we never queried using Base type, as it was abstract. Will ordinary ToTable include inherited properties?

**Comment by mviegas** [comment] 2019-10-21 15:31
Still no news about it?! 😔

**Comment by BrianMikinski** [comment] 2020-01-08 06:44
Can we infer from the following documentation that TPC will be supported in EF Core 5.0? -

[The table-per-type (TPT) and table-per-concrete-type (TPC), which are supported by EF6, are not yet supported by EF Core. TPT is a major feature planned for EF Core 5.0.](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance)

**Comment by roji** [comment] 2020-01-08 09:18
The text says it pretty clearly - TPT is a planned feature for 5.0, while TPC is currently only considered a stretch goal and may not make it in.

**Comment by G3Kappa** [comment] 2020-03-02 10:43
Wow, do I really have to port everything back to Ef 6.4 for an  issue that has been known since 2015?



> 
> 
> @Grasher134 Using the base type as an "unmapped base class" sounds like it might work for you. This is generally a good approach, but does require that entity types don't reference the base class directly. Mapping inherited properties should not be a problem.

Yeah but how can you define navigation properties to types that are loaded dynamically, via reflection _unless_ you define them on the base class? I know it's an extremely niche use case, but it's a real one.

**Comment by G3Kappa** [comment] 2020-03-02 10:49
> 
> 
> The text says it pretty clearly - TPT is a planned feature for 5.0, while TPC is currently only considered a stretch goal and may not make it in.

I really hope it does make it in. Or rather, I would if I weren't on a deadline. I think I might have to backport everything to 6.4 now...

**Comment by imanabidi** [comment] 2020-03-08 09:30
- 2nd priority based on official high level plan. [ref](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/plan#table-per-type-tpt-inheritance-mapping)
- The next planned stable release is EF Core 5.0, scheduled for November 2020.
- daily builds are also available for download and feedback. [ref](https://docs.microsoft.com/en-us/ef/core/what-is-new/index#get-it-now)

**Comment by smitpatel** [comment] 2020-07-03 19:44
For shape of the query projection, consider discussion https://github.com/dotnet/efcore/issues/2266#issuecomment-653661902 and final decision from #21509

**Comment by pantonis** [comment] 2021-02-10 09:28
@ajcvickers @smitpatel  Does this mean that this is gonna be in EF Core 6? Btw what is the workaround until TPC is ready? I am migrating a project from EF6 and my client used TPC. Is there any workaround example?

**Comment by roji** [comment] 2021-02-10 12:48
@pantonis this issue is currently in the backlog, and not in the 6.0 milestone - that means it's not currently planned. However, it has the consider-for-next-release label, which means it's a high-priority item in case there's extra time to complete it.

Until this is done, you won't be able to migrate your EF6 model as-is, but there may be various ways to modify it to make it compatible with EF Core (TPH/TPT, or possibly something else).

**Comment by pantonis** [comment] 2021-02-10 17:19
@roji Is there any other workaround apart from TPH and TPT?

**Comment by roji** [comment] 2021-02-10 17:28
You can remodel things in some way so that you don't need TPC, but barring that, TPC is not currently supported.

**Comment by e-davidson** [comment] 2021-03-04 14:25
>this issue is currently in the backlog, and not in the 6.0 milestone

Since this issue is  marked with ef6-parity it should be part of 6.0 release due to https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/plan#ef6-query-parity

**Comment by roji** [comment] 2021-03-04 17:44
@e-davidson we indeed intend to try to reach *query* parity with EF6, but TPC isn't a query feature, it's a mapping strategy.

**Comment by roji** [comment] 2021-04-30 10:11
@zejji this is currently a "stretch goal" for EF Core 6, meaning that we may get around to it if we have extra time - but haven't commit to it. If not, it will most likely only be included in EF Core 7, and not in a point release of EF Core 6 - we only release bug fixes in point releases.

**Comment by G3Kappa** [comment] 2021-05-20 03:08
> 
> 
> You can remodel things in some way so that you don't need TPC, but barring that, TPC is not currently supported.

Not to sound annoying, but what would such ways be? I've stumbled on this problem last year and I'm glad I'm not on that project at the moment because honestly _any_ workaround ends up as an ugly mess...

**Comment by Luigi6821** [comment] 2022-02-18 17:32
Hi,
I have downloaded preview of EF 7 just to test the TPC implementation.
I am not sure is fully implemented and my question is will the final release support scenario like the following (which is fully supported by Entity Framework 6.4):
Thanks in advance

`
    #region abstract entity classes
    public abstract class BaseEntity
    { }

    public abstract class AMOS_ORDERFORM : BaseEntity
    {
        public decimal ORDERID { get; set; }

        public string FORMNO { get; set; }
        public string TITLE { get; set; }

        public decimal VENDORID { get; set; }

        [ForeignKey("VENDORID")]
        public AMOS_ADDRESS VENDOR { get; set; }

        public ICollection<AMOS_ORDERLINE> ORDERLINEs { get; set; }
    }

    public abstract class AMOS_SPAREUNIT : BaseEntity
    {
        public decimal PARTID { get; set; }

        public decimal PARTTYPEID { get; set; }

        public AMOS_SPARETYPE PARTYPE { get; set; }
    }

    public abstract class AMOS_SPARETYPE : BaseEntity
    {
        public decimal PARTTYPEID { get; set; }

        public string PARTNAME { get; set; }
    }

    public abstract class AMOS_ORDERLINE : BaseEntity
    {
        public decimal ORDERLINEID { get; set; }

        public decimal ORDERID { get; set; }

        public AMOS_ORDERFORM ORDER { get; set; }

        public string NAME { get; set; }

        public decimal? PARTID { get; set; }

        public AMOS_SPAREUNIT PART { get; set; }
    }

    public abstract class AMOS_ADDRESS : BaseEntity
    {
        public decimal ADDRESSID { get; set; }

        public string CODE { get; set; }

        public string ALPHACODE { get; set; }
    }

    public abstract class AMOS_ADDRESSCONTACT : BaseEntity
    {
        public decimal ADDRESSCONTACTID { get; set; }

        public AMOS_ADDRESS ADDRESS { get; set; }

        public decimal? ADDRESSID { get; set; }
    }
    #endregion

    public class ADDRESS : AMOS_ADDRESS
    { }

    public class ADDRESSCONTACT : AMOS_ADDRESSCONTACT
    {  }

    public class ORDERFORM : AMOS_ORDERFORM
    { }

    public class ORDERLINE : AMOS_ORDERLINE
    { }

    public class SPAREUNIT : AMOS_SPAREUNIT
    { }

    public class SPARETYPE : AMOS_SPARETYPE
    { }
`

**Comment by AndriySvyryd** [comment] 2022-02-18 17:43
@Luigi6821 This issue is still open, meaning that it hasn't been implemented yet.

**Comment by eraffel-MDSol** [comment] 2022-02-18 22:43
Is there any sort of guesstimate of when this will likely start landing in the daily builds? Excited to start playing with this. :)

**Comment by AndriySvyryd** [comment] 2022-02-18 23:21
At some point after preview 3 probably

**Closed** 2022-05-11 23:10 UTC
Labels: type-enhancement, closed-fixed, area-query, area-save-changes, area-model-building, area-migrations, area-relational-mapping, ef6-parity

**Comment by eraffel-MDSol** [comment] 2022-05-12 01:06
I haven't been following closely, but since this closed, is TPC now ready to be played with in the nightly builds?

**Comment by AndriySvyryd** [comment] 2022-05-12 07:00
@eraffel-MDSol Yes, starting with tomorrow's build

**Comment by AndriySvyryd** [comment] 2022-05-12 20:49
@Luigi6821 You need to call `modelBuilder.Entity<AMOS_ADDRESS>().UseTpcMappingStrategy()`

Also, you can't yet configure a different column name for one of the tables, that's coming in https://github.com/dotnet/efcore/issues/19811

**Comment by marchy** [comment] 2022-06-16 14:25
How are relationships from outside of an TPC hierarchy into any of its entities handled, given that no table is generated for the base/abstract entity?

For example, are any of the following supported?
(assuming the Animals entity hierarchy stated in the [announcement post](https://devblogs.microsoft.com/dotnet/announcing-ef7-preview5//#comment-15889))
```
// Example 1
class SomeExternalEntity {
    // NOT SUPPORTED in TPC?
    public Animal Animal { get; private set; }
}

// Example 2
class SomeOtherExternalEntity {
    // NOT SUPPORTED in TPC?
    public IList<Animal> Animals { get; private set; }
}
```

With both TPH and TPT, the following gets generated:
```
// Example 1
CREATE TABLE [dbo].[SomeExternalEntity](
    [AnimalID] [nvarchar](36) NOT NULL,
) ON [PRIMARY]
ALTER TABLE [dbo].[SomeExternalEntity] ADD  CONSTRAINT [PK_dbo.SomeExternalEntity] PRIMARY KEY CLUSTERED 
(
    [AnimalID] ASC
)
ALTER TABLE [dbo].[SomeExternalEntity]  WITH CHECK ADD  CONSTRAINT [FK_dbo.SomeExternalEntity_dbo.Animals_Id] FOREIGN KEY([Id])
REFERENCES [dbo].[Animals] ([Id])
```

**Comment by eraffel-MDSol** [comment] 2022-06-17 15:00
@ajcvickers With regard to the previous question, how will this work with deletes? Referencing the example given in the video, if I were to delete one of the animals, will the "Human" that references that animal as its favorite be deleted automatically, or would I have to manage preventing "orphan" records like that myself, since there's no FK constraint to enforce that.

**Comment by bachratyg** [comment] 2022-06-17 16:19
@ajcvickers does this mean that TPC uses [Bulk (i.e. set-based) update/delete (without loading data into memory) #795](https://github.com/dotnet/efcore/issues/795) under the hood or that related entities need to be in the change tracker for cascade to work properly?

**Comment by ajcvickers** [comment] 2022-06-17 16:20
@bachratyg They need to be in the change tracker.

**Comment by bachratyg** [comment] 2022-06-17 16:23
That means orphans have to be managed manually.

**Comment by ajcvickers** [comment] 2022-06-17 16:25
@bachratyg That depends on your definition of "manually". If data is appropriately loaded, then EF manages them. But if you are looking for a pattern that works well with database constructs like constraints and Identity keys, then TPC is not for you.

**Comment by bachratyg** [comment] 2022-06-17 17:49
Data being appropriately loaded would mean a read lock on the _principal_ row in all possible transactions modifying the relationship, some clever use of concurrency checks, or a business process that guarantees no concurrent phantom inserts. Either way serious steps should be taken to keep data consistent and that more or less covers my definition of  "manually".

Don't get me wrong, I don't feel either way about the implementation, I just want to be sure I fully understand the consequences.
