### ISSUE TITLE
Query : compilation error for complex query with nested groupjoins and result operators

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#7770] opened 2017-03-02 22:59 UTC
query:

```
from x in
	(from l1 in ctx.LevelOne
	 join l2 in ctx.LevelTwo on l1.Id equals l2.Level1_Optional_Id into grouping
	 from l2 in grouping.DefaultIfEmpty()
	 select l1).Take(2)
join l2_outer in ctx.LevelTwo on x.Id equals l2_outer.Level1_Optional_Id into grouping_outer
from l2_outer in grouping_outer.DefaultIfEmpty()
select l2_outer.Name;
```

This produced the following query plan:

```
TRACKED: False
(QueryContext queryContext) => IEnumerable<string> _Select(
    source: IEnumerable<TransparentIdentifier<TransparentIdentifier<Level1, IEnumerable<Level2>>, Level2>> _SelectMany(
        source: IEnumerable<TransparentIdentifier<Level1, IEnumerable<Level2>>> _GroupJoin(
            outer: IEnumerable<Level1> _Select(
                source: IEnumerable<TransparentIdentifier<Level1, Level2>> _ShapedQuery(
                    queryContext: queryContext, 
                    shaperCommandContext: SelectExpression: 
                        SELECT [t].[Id], [t].[Date], [t].[Name], [t].[OneToMany_Optional_Self_InverseId], [t].[OneToMany_Required_Self_InverseId], [t].[OneToOne_Optional_SelfId], [t].[c0], [t].[c1], [t].[Level1_Optional_Id], [t].[Level1_Required_Id], [t].[c2], [t].[OneToMany_Optional_InverseId], [t].[c3], [t].[OneToMany_Required_InverseId], [t].[c4], [t].[OneToOne_Optional_PK_InverseId], [t].[c5]
                        FROM (
                            SELECT TOP(@__p_0) [l1].[Id], [l1].[Date], [l1].[Name], [l1].[OneToMany_Optional_Self_InverseId], [l1].[OneToMany_Required_Self_InverseId], [l1].[OneToOne_Optional_SelfId], [l2].[Id] AS [c0], [l2].[Date] AS [c1], [l2].[Level1_Optional_Id], [l2].[Level1_Required_Id], [l2].[Name] AS [c2], [l2].[OneToMany_Optional_InverseId], [l2].[OneToMany_Optional_Self_InverseId] AS [c3], [l2].[OneToMany_Required_InverseId], [l2].[OneToMany_Required_Self_InverseId] AS [c4], [l2].[OneToOne_Optional_PK_InverseId], [l2].[OneToOne_Optional_SelfId] AS [c5]
                            FROM [Level1] AS [l1]
                            LEFT JOIN [Level2] AS [l2] ON [l1].[Id] = [l2].[Level1_Optional_Id]
                        ) AS [t]
                    , 
                    shaper: CompositeShaper`3
                )
                , 
                selector: (TransparentIdentifier<Level1, Level2> t1) => t1.Outer
            )
            , 
            inner: IEnumerable<Level2> _ShapedQuery(
                queryContext: queryContext, 
                shaperCommandContext: SelectExpression: 
                    SELECT [l2_outer].[Id], [l2_outer].[Date], [l2_outer].[Level1_Optional_Id], [l2_outer].[Level1_Required_Id], [l2_outer].[Name], [l2_outer].[OneToMany_Optional_InverseId], [l2_outer].[OneToMany_Optional_Self_InverseId], [l2_outer].[OneToMany_Required_InverseId], [l2_outer].[OneToMany_Required_Self_InverseId], [l2_outer].[OneToOne_Optional_PK_InverseId], [l2_outer].[OneToOne_Optional_SelfId]
                    FROM [Level2] AS [l2_outer]
                , 
                shaper: BufferedEntityShaper<Level2>
            )
            , 
            outerKeySelector: (Level1 x) => (Nullable<int>) Unhandled parameter: t1.Outer.Id, 
            innerKeySelector: (Level2 l2_outer) => l2_outer.Level1_Optional_Id, 
            resultSelector: (Level1 x | IEnumerable<Level2> grouping_outer) => TransparentIdentifier<Level1, IEnumerable<Level2>> CreateTransparentIdentifier(
                outer: x, 
                inner: grouping_outer
            )
        )
        , 
        collectionSelector: (TransparentIdentifier<Level1, IEnumerable<Level2>> t0) => IEnumerable<Level2> DefaultIfEmpty(
            source: t0.Inner
        )
        , 
        resultSelector: (TransparentIdentifier<Level1, IEnumerable<Level2>> t0 | Level2 l2_outer) => TransparentIdentifier<TransparentIdentifier<Level1, IEnumerable<Level2>>, Level2> CreateTransparentIdentifier(
            outer: t0, 
            inner: l2_outer
        )
    )
    , 
    selector: (TransparentIdentifier<TransparentIdentifier<Level1, IEnumerable<Level2>>, Level2> t1) => t1.Inner.Name
)

```

Problem here is that relinq parses this query into the following query model:

```
from Level1 x in 
    (from Level1 l1 in DbSet<Level1>
    join Level2 l2 in DbSet<Level2>
    on (Nullable<int>) l1.Id equals l2.Level1_Optional_Id into grouping
    from Level2 l2 in 
        (from Level2 <generated>_1 in grouping
        select <generated>_1)
        .DefaultIfEmpty()
    select l1)
    .Take(__p_0)
join Level2 l2_outer in DbSet<Level2>
on (Nullable<int>) l1.Id equals l2_outer.Level1_Optional_Id into grouping_outer
from Level2 l2_outer in 
    (from Level2 <generated>_1 in grouping_outer
    select <generated>_1)
    .DefaultIfEmpty()
select l2_outer.Name
```

in the 

```
join Level2 l2_outer in DbSet<Level2>
on (Nullable<int>) l1.Id equals l2_outer.Level1_Optional_Id into grouping_outer
```

outer key selector is optimized to ```l1.Id```, rather than ```x.Id```

This causes errors during compilation for us since the [l1] qsre is mapped to t1.Outer, rather than the expected: x

**Comment by tuespetre** [comment] 2017-03-02 23:07
I ran into one similar before, is this just a relinq issue?

**Comment by maumar** [comment] 2017-03-02 23:11
I think its an optimization that is detrimental to us because of the way we handle the translation. We might need to compensate, but perhaps there is a way/trick to disable it. 
@MichaelKetting what is your take on this?

**Comment by MichaelKetting** [comment] 2017-03-03 07:05
@maumar On first glance (based on 'group join' and 'wrong sub query source') this looks like https://www.re-motion.org/jira/browse/RMLNQ-105 is hitting you. I'll look into releasing this fix as an alpha-release this weekend so you can try it out. If that's not it, I'll have to go in deeper :)

**Comment by maumar** [comment] 2017-03-03 07:45
@MichaelKetting great! thanks a lot, it does seem to be the same issue

**Comment by MichaelKetting** [comment] 2017-03-06 09:57
@rowanmiller #4311 should be the other one. 
re-linq 2.2.0-alpha.2 is now online.

**Comment by ajcvickers** [comment] 2017-03-06 19:36
Closing as dupe of #4311

**Closed** 2022-10-16 10:55 UTC
Labels: area-external
