### ISSUE TITLE
UpdateRange method overload for non-tracking entities

### ISSUE THREAD

**Issue by rameshbsupekar** [dotnet/efcore#23581] opened 2020-12-04 08:45 UTC
I am using UpdateRange method multiple times on same type of dbset, for saving nontracked entities, 
fetched using AsNoTracking() and also have disabled QueryTrackingBehaviour before using context,

I am updating dbset initially updating one column and after other application logic operations, 
I fetch same dbset AsNoTracking() and I update other two columns.

For first call to UpdateRange and SaveChanges it was working fine

after few methods call not related to ef core but application logic
I am fetching again nontracked entities for same dbset type and try to save
this time UpdateRange method throws error EF Core 'another instance is already being tracked' 

Is this behaviour correct?
I feel currently this is incorrect
If i am fetching again nontracked entities for dbset modify and then call UpdateRange it should work

I am able to workaround currently by marking entities detached, with looping over entities i used in updatedrange call and after savechanges, I detach entities

I feel UpdateRange behaviour is correct if we have tracking behaviour, can we have another overload for nontracking where in UpdateRange after save entites will be marked detached

**Comment by ajcvickers** [comment] 2020-12-04 16:57
@rameshbsupekar A couple of things. First, querying an entity without tracking it (i.e. a no-tracking query) and then starting to track that entity with `Update` or `UpdateRange` is not the recommended approach. If you are going to make updates to the entity, then query it with a normal tracking query, make the changes, and call `SaveChanges`. There is no need to use the Update methods at all.

Second, use a new DbContext instance for each unit of work. This ensures that the state of updated entities is tracked for the entire unit of work, even if it involves multiple queries, but ensures that each new unit of work starts in a clean state. If you find yourself detaching entities, then that's a good indication your keeping your DbContext alive for more than a single unit-of-work.

**Comment by rameshbsupekar** [comment] 2020-12-05 16:43
Earlier I was using connected approach First update i got tracked entities and i callled savechanges after modification,
after that one stored procedure call was there, the changes executed by stored procedure were not available in second call to traced entities , so  I needed to change my approach to call asnotracking and as above mentioned UpdateRange()

**Comment by ajcvickers** [comment] 2020-12-05 21:55
@rameshbsupekar Typically a unit of work contains a single call to SaveChanges. It sounds very much like you should create a new context instance after calling SaveChanges.

**Comment by rameshbsupekar** [comment] 2020-12-06 00:29
I am using depenndency injection in asp.net core 3 methods are there in single repository , dbcontext instance is injected into constructor and is with scoped lifetime, so instance is created single time in repository, repository also constructor injected into business logic class which is transient scope, I do not know currently, in this dependency injection scenario,  how to make sure new instance for each method call to repository methods from business logic class,

**Comment by ajcvickers** [comment] 2020-12-07 17:15
@rameshbsupekar Three options:
* Register the DbContext as transient when calling AddDbContext. Then each place the context is injected will get a new instance.
* Register a DbContext factory in D.I. In EF Core 5.0, this is supported by `AddDbContextFactory`, but similar code can be implemented directly by the application when using earlier versions of EF Core.
* Don't use D.I. and instead new up DbContext instances when needed and dispose them when done.

**Comment by rameshbsupekar** [comment] 2020-12-08 04:56
Thank you for your time providing inputs

1. First option will not work in my case as my methods are in single repository so transient also inject only once inside repository constructor
3. I am sure 3 rd option will be right choice but  I have to use DI as complete application, lot of code is build that way so it will keep consistency

2. This i will need to do some POC and try out, due to time constraint i will not be able to do it now but will check in future

I am currently going with workaround i did detaching objects after update range call, which is working fine for me currently

I want to conclude with below observations

1. When we have tracking behaviour, if something directly changed using sql execution like stored procedure we do not get updated results
2. when we have Untracking behaviour we  get latest data , but after modifications we are not able to use UpdateRange multiple times, to workaround we need to detach the objects used

**Comment by ajcvickers** [comment] 2020-12-08 21:31
@rameshbsupekar If you feel there is a bug here, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate. If not, then I don't think there is anything else actionable on this issue.

**Comment by ajcvickers** [comment] 2020-12-18 17:31
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:13 UTC
Labels: closed-no-further-action, customer-reported
