### ISSUE TITLE
ChangeTracker.Entries().ToList() throwing InvalidOperationException

### ISSUE THREAD

**Issue by jasenf** [dotnet/efcore#20986] opened 2020-05-18 22:52 UTC
We've had the following code in production for quite a while:

```
public void DetachAll()
{
  var entries = ChangeTracker.Entries().ToList();
  foreach(Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry entityEntry in entries) 
  {
       if (entityEntry.Entity != null)
          entityEntry.State = EntityState.Detached;
  }
}
```

We've been keeping our packages up to date, however, the latest round of package upgrades has now started causing an exception to be thrown simply by calling ChangeTracker.Entries.ToList()

I'm curious if this is expected behavior that we should be dealing with or some new anomaly in EFCore?

We are receiving the following exception:

```
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry):184
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate):48
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry):106
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties):335
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey):53
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node):70
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey):35
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.NavigationReferenceChanged(InternalEntityEntry entry, INavigation navigation, Object oldValue, Object newValue):771
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.NavigationReferenceChanged(InternalEntityEntry entry, INavigation navigation, Object oldValue, Object newValue)
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigation navigation):374
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.LocalDetectChanges(InternalEntityEntry entry):289
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager):59
Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges():33
Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.TryDetectChanges():8
Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.Entries()
```

### Further technical details

EF Core version: 3.1.4
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system:  Azure AppService (Windows deployment)

**Comment by ajcvickers** [comment] 2020-05-19 21:45
@jasenf Did this start failing when updating from 3.1.3 to 3.1.4? If so, it's not expected. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by jasenf** [comment] 2020-05-19 22:34
Hi Arther --  I would if I could but there's no way I am able to reliably reproduce it.   Huge project, only seeing it in production.    My apologies.  It definitely has something only happens when there are tracked entities waiting to be updated.

**Comment by ajcvickers** [comment] 2020-05-20 16:12
@jasenf I doubt we'll be able to do anything without code to reproduce the issue.

**Comment by ajcvickers** [comment] 2020-06-01 16:41
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:25 UTC
Labels: closed-could-not-reproduce, customer-reported
