### ISSUE TITLE
Support for lists of primitives in EF with CosmosDb, support Guids

### ISSUE THREAD

**Issue by coffeymatt** [dotnet/efcore#28762] opened 2022-08-17 14:16 UTC
You support collections of primitives at the moment, so you can have a list of string. I'd like to store a list of Guids in the same way.

https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli#collections-of-primitive-types

Support a property like this as you do with lists of strings:

```
public IList<Guid> TechLeadIds { get; set; } = new List<Guid>();

```

(In the mean time, if I can do this with some mapping, hints would be appreciated!)

**Comment by roji** [comment] 2022-08-17 15:48
@coffeymatt did the above not work for you? If so, can you post the full error?

**Comment by AndriySvyryd** [comment] 2022-08-17 18:38
Duplicate of https://github.com/dotnet/efcore/issues/25343

**Closed by AndriySvyryd** 2022-08-17 18:38 UTC
Labels: closed-duplicate, customer-reported
