### ISSUE TITLE
EF Core 3.0 Design Tooling: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.0.0.0'

### ISSUE THREAD

**Issue by thijstijsma** [dotnet/efcore#14254] opened 2018-12-27 14:01 UTC
I'm trying out the EF Core 3.0 preview (in VS 2019, 16.0.0 Preview 1.1 on Windows 10 Pro), added the following to my project.

```
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.0-preview.18572.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0-preview.18572.1" />
```

When I want to add a migration (or just list them), I get the following error:

```
> dotnet ef migrations list
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.GetMigrations(String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.GetMigrationsImpl(String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.GetMigrations.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)


Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
```

I verified what version of Microsoft.Extensions.DependencyInjection.Abstractions is in my local NuGet cache and it seems to be 3.0.0.18326 (from the File Version entry in the Details).

**Comment by ajcvickers** [comment] 2019-01-04 23:44
@thijstijsma It's likely that there will be issues with very early previews like the first preview of .NET Core 3.0, so this is something that may just get fixed as things progress. However, if you would like us to investigate more then we'll need a simple runnable project/solution that reproduces what you are seeing so that we can dig into it.

**Comment by ajcvickers** [comment] 2019-01-14 18:18
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:45 UTC
Labels: closed-could-not-reproduce, customer-reported
