### ISSUE TITLE
Create a {VS,dnx}-less solution for generating migrations

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#2700] opened 2015-07-23 23:35 UTC
Anyone not developing within Visual Studio or dnx cannot access Ef.Commands. Generating migrations must be done by hand.

**Ideas:**
- Pure CLI tool. We _might_ be able to port [Program.cs](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Commands/Program.cs) to work .exe tool.
- Hosted solution e.g. a website where you drag and drop some *.cs file(s). and it spits out a migration.
- Xamarin Studio plugin

(# of users affected? probably a very small number)

**Comment by Grinderofl** [comment] 2015-07-24 09:06
I'm working on an internal SDK which requires EF to have the ability to delegate dbcontext creation to detecting model classes from files, as well as a simple way of working with migrations. I have a very raw version of it uploaded here: https://github.com/Grinderofl/EntityFramework7-helpers (there's even no entity type configuration).

It includes generating dbcontext by finding by base class, using the new kind of IDbSetXXX's. Migrations happen through IMigrationFacility.

**Comment by rowanmiller** [comment] 2015-07-24 16:56
Dupe of https://github.com/aspnet/EntityFramework/issues/646?

**Comment by natemcmaster** [comment] 2015-07-24 17:03
Someone. It could include a tool like #646, but we may not create a *.exe cli tool. For instance, a Xamarin Addin might be a good solution here.

**Comment by natemcmaster** [comment] 2016-08-18 18:10
With https://github.com/aspnet/EntityFramework/pull/6288, we have put all project-system and IDE specific code into separate layers. This also resolved #646 by providing "ef.exe", which consumes assemblies only in a project-system independent way.  The building blocks for creating Xamarin Studio, VS Code, or Rider tooling extensions are available in the Microsoft.EntityFrameworkCore.Design package.

Closing this general issue as we haven't received requests for tooling outside of .NET Core SDK and Visual Studio. We can reopen for more consideration if we get more feedback.

**Closed** 2022-10-16 09:03 UTC
Labels: type-enhancement, closed-out-of-scope
