### ISSUE TITLE
Deleting entities is having problems

### ISSUE THREAD

**Issue by MCFHTAGENTS** [dotnet/efcore#27221] opened 2022-01-19 20:42 UTC
I have made significant changes to my code model as I have iterated my platform (am altering primary keys and dropping multiple tables). When I run
`add-migration -context ApplicationDbContext v0.0.00012` 

I get the following stack trace:
````
System.ArgumentException: An item with the same key has already been added. Key: [0, Property: `MyClass (Dictionary<string, object>).MyMember(no field, string) Indexer FK Index MaxLength(36)]
   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetSortedProperties(IEntityType entityType, ITable table)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetSortedColumns(ITable table)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Add(ITable target, DiffContext diffContext)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
An item with the same key has already been added. Key: [0, Property: MyClass (Dictionary<string, object>).MyMember(no field, string) Indexer FK Index MaxLength(36)]
````
I have obfuscated MyClass and MyMember

The class MyClass no longer exists in my code base, although it exists in in the text for keys in the Model Snapshot both to define the table and, twice, to define two relationships, one to a table that also no longer exists and one to one that has been retained.

Am assuming this is a bug - but also can you suggest any work arounds to bring the model back in sync? I have all the code in version control so can restore easily enough

**Comment by AndriySvyryd** [comment] 2022-01-20 06:12
Duplicate of https://github.com/dotnet/efcore/issues/26405

Will be fixed in 6.0.2

**Closed** 2022-10-16 20:22 UTC
Labels: closed-duplicate, customer-reported
