### ISSUE TITLE
Migrations: duplicates foreign key and modifies onDelete

### ISSUE THREAD

**Issue by X-rus** [dotnet/efcore#4754] opened 2016-03-10 12:54 UTC
Models: [pastebin.com/W40KZxLg](http://pastebin.com/W40KZxLg)
Initial migration: [pastebin.com/zAh0V1x5](http://pastebin.com/zAh0V1x5)
Next migration (added new field Money): [pastebin.com/wdvW6LfP](http://pastebin.com/wdvW6LfP)
[MigrationBugProject.zip](https://github.com/aspnet/EntityFramework/files/167112/MigrationBugProject.zip)

**Comment by smitpatel** [comment] 2016-03-10 15:59
dupe of #3751
It is fixed in current bits and will be shipped in RC2 release

**Closed** 2022-10-16 09:32 UTC
