### ISSUE TITLE
Two One-to-One relationships to same table

### ISSUE THREAD

**Issue by PetterT2** [dotnet/efcore#16172] opened 2019-06-20 09:59 UTC
First of all it does not seem to work to have to FKs referencing the same table. According to what I understand this might be a limitation in SQL, and handled by triggers instead. 

Question:
Is there a proper way to make this work using the fluent api, i.e. using cascade or trigger?

Issue:
No way to make it not throw the exception below. I.e. no way to not generate onDelete: ReferentialAction.NoAction in the migration file. Have tried the different onDelete options but it does not work..The suggested "ON DELETE NO ACTION" does not seem to be available using the fluent api? 

(I still think the FKs should be required to at least throw exception if not handled on delete, so i don't  think optional is good)

```C#
public enum DeleteBehavior
    {
        ClientSetNull = 0,
        Restrict = 1,
        SetNull = 2,
        Cascade = 3
    }
```
is missing the NoAction which is an option in the migration files:
onDelete: ReferentialAction.NoAction

```C#
internal class PageVariationEntity
{
  public int PageId { get; set; }
  public virtual PageEntity Page { get; set; }

  public int VariationPageId { get; set; }
  public virtual PageEntity VariationPage { get; set; }
}

internal class PageEntity: AuditingEntityBase
{
     [Key, Column(Order = 1), DatabaseGenerated(DatabaseGeneratedOption.Identity)]
     public int Id { get; set; }
}
```
```C#
//fluent config:
modelBuilder.Entity<PageVariationEntity>()
            .HasOne(pv => pv.Page).WithOne().HasForeignKey<PageVariationEntity>(pv => pv.PageId).IsRequired();
            modelBuilder.Entity<PageVariationEntity>()
            .HasIndex(pv => pv.PageId);

            modelBuilder.Entity<PageVariationEntity>()
            .HasOne(pv => pv.VariationPage).WithOne().HasForeignKey<PageVariationEntity>(pv => pv.VariationPageId).IsRequired();
            modelBuilder.Entity<PageVariationEntity>()
           .HasIndex(pv => pv.VariationPageId).IsUnique();
```

Exception message:
System.Data.SqlClient.SqlException: 'Introducing FOREIGN KEY constraint 'FK_PageVariations_Pages_VariationPageId' on table 'PageVariations' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other 
FOREIGN KEY constraints.

### Steps to reproduce
Create an entity with two required foreign keys to the same table

**Comment by ajcvickers** [comment] 2019-06-20 21:48
@PetterT2 Both `Restrict` and `ClientSetNull` should work for this and give the same behavior in the database. If that's not the case, then please file a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

See also https://github.com/aspnet/EntityFrameworkCore/issues/12661#issuecomment-479642950

**Comment by ajcvickers** [comment] 2019-06-28 15:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:26 UTC
Labels: closed-could-not-reproduce
