### ISSUE TITLE
Mixing inheritance strategies

### ISSUE THREAD

**Issue by mhDuke** [dotnet/efcore#33394] opened 2024-03-25 15:32 UTC
```
abstract class Party 
{
  Guid Id { get; }
}

class Agent : Party { }

abstract class Customer : Party { }

class IndieCustomer : Customer { }

class BusinessCustomer : Customer { }
```

```
public void Configure(EntityTypeBuilder<Customer> b)
{
    b.HasDiscriminator<string>("CustomerType")
         .HasValue<BusinessCustomer>("business")
         .HasValue<IndieCustomer>("indie");
}

public void Configure(EntityTypeBuilder<Party> b)
{
  b.UseTptMappingStrategy();
}
```

adding migration results in the following error:
> Map all the entity types in the hierarchy to the same table, or remove the discriminator

It seems we cannot be mixing tph and tpt. is this by design? can we have this in the future?
I think I go for full tbh, tbc, or follow different approach. Do you guys have any advice?

```
Party_
      |-Agent
      |-Customer: indie | business
```

**Comment by roji** [comment] 2024-03-25 15:46
Duplicate of #27707

**Comment by roji** [comment] 2024-03-25 15:47
@mhDuke yes, this is by design: see #27707, #31184, #22796, #22796.

**Closed by roji** 2024-03-25 15:47 UTC
Labels: customer-reported
