### ISSUE TITLE
Project Configuration Manager Properties is blank or null

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#19570] opened 2020-01-08 19:30 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/815660/project-configuration-manager-properties-is-blank.html)._

---
Running the command
(Get-Project ApiAuthSample). ConfigurationManager.ActiveConfiguration
on a project results in Properties being reported as blank or null. This leads to a variety of problems. This showed up trying to generate and apply migrations. This issue is somehow computer environment based as running this command on the same project on another computer results in the properties showing as System.__ComObject and the migrations command work as expected on that machine.

---
#### Visual Studio Feedback System on 11/12/2019, 00:12 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 11/14/2019, 00:32 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Alan Wilton on 11/20/2019, 08:44 PM: 

<p>In VS 2019 create a new project using the ASP.NET Core Web Application Template. Choose Next, Name the project and click create. Select .NET Core, ASP.NET Core 3.0 and Web Application. Change the Authentication to Individual user accounts.Click OK and Create. Build and Run the project. Close the browser. Then Run PMC add-migration test. For most people this will work just fine. For me I get:</p><p>PM&gt; add-migration test </p><p>The specified deps.json [C:\Users\Al\Documents\Visual Studio\Projects\Test\WebApplication1\WebApplication1\WebApplication1.deps.json] does not exist</p><p>And of course if I run (Get-Project WebApplication1).ConfigurationManager.ActiveConfiguration the properties is blank.</p><pre>PM&gt; (Get-Project WebApplication1).ConfigurationManager.ActiveConfiguration
DTE               : System.__ComObject
Collection        : System.__ComObject
ConfigurationName : Debug
PlatformName      : Any CPU
Type              : 1
Owner             : Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject
Properties        : 
IsBuildable       : True
IsRunable         : True
IsDeployable      : False
Object            : Microsoft.VisualStudio.ProjectSystem.VS.Properties.CSharp.CSharpProjectConfigurationProperties
ExtenderNames     : {}
ExtenderCATID     : {89FB23F7-E591-4a2f-8E0F-64C0522FCF77}
OutputGroups      : System.__ComObject

<br></pre>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2020-01-13 17:48
@bricelam I feel like we've seen something like this before.

**Comment by bricelam** [comment] 2020-01-13 19:58
Duplicate of #16386

@davidwengier here is another report you might be able to use for debugging

**Closed** 2022-10-16 18:05 UTC
Labels: customer-reported
