### ISSUE TITLE
N+1 queries when returning entity but not when projecting properties of entity

### ISSUE THREAD

**Issue by ShamsulAmry** [dotnet/efcore#11517] opened 2018-04-01 18:34 UTC
Issue as per subject. Please see comment in code fragment below.

```c#
public class TestContext : DbContext
{
    RouteMaster { get; set; }

    public async Task TestAsync()
    {
        var badTestQuery =
            from rm in RouteMaster
            let schedules =
                from rs in rm.Schedules
                where rs.CutOffTime >= new TimeSpan(9, 0, 0) && rs.CutOffTime <= new TimeSpan(17, 0, 0)
                select rs
            select new {
                // This query will return full entity
                rm,
                HasActiveSchedule = schedules.Any()
            };

        // This will result in N+1 queries. One for RouteMaster and N for the RouteMaster's Schedules
        var badTestResult = await badTestQuery.ToArrayAsync().ConfigureAwait(false);

        var goodTestQuery =
            from rm in RouteMaster
            let schedules =
                from rs in rm.Schedules
                where rs.CutOffTime >= new TimeSpan(9, 0, 0) && rs.CutOffTime <= new TimeSpan(17, 0, 0)
                select rs
            select new {
                // This query will project all properties of the entity, same as it would be in the above bad query
                rm.Id,
                rm.RouteNumber,
                HasActiveSchedule = schedules.Any()
            };

        // This will result in one select statement with the RouteMaster's Schedules as sql subquery
        var goodTestResult = await goodTestQuery.ToArrayAsync().ConfigureAwait(false);  
    }

    class RouteMasterRecord
    {
        public Guid Id { get; private set; }
        public string RouteNumber { get; private set; }
        public IReadOnlyCollection<RouteScheduleRecord> Schedules { get; private set; }
    }

    class RouteScheduleRecord
    {
        public Guid Id {get; private set; }
        public TimeSpan CutOffTime { get; private set; }
    }
}
```

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.5.7

**Comment by divega** [comment] 2018-04-02 19:01
@smitpatel @maumar please find the duplicate.

**Comment by smitpatel** [comment] 2018-04-02 19:55
Duplicate of #11186

**Closed** 2022-10-16 12:16 UTC
