### ISSUE TITLE
The navigation '' cannot be added because it targets the keyless entity type '<TableName>'. Navigations can only target entity types with keys.

### ISSUE THREAD

**Issue by btaymaz** [dotnet/efcore#19615] opened 2020-01-17 02:01 UTC
We use database first approach. We have table without primary keys like this one:

CREATE TABLE [dbo].[SubEntryLog](
	[SubSubscriberId] [int] NOT NULL,
	[SubUserId] [int] NOT NULL,
	[SessionID] [char](24) NULL,
	[IPAddress] [char](20) NOT NULL,
	[LoginDate] [datetime] NOT NULL,
	[LogoutDate] [datetime] NULL,
	[IsMobile] [bit] NULL
)

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SubEntryLog]  WITH CHECK ADD  CONSTRAINT [fkSubEntryLog_SubSubscriberId] FOREIGN KEY([SubSubscriberId])
REFERENCES [dbo].[SubSubscriber] ([SubSubscriberId])
GO

ALTER TABLE [dbo].[SubEntryLog] CHECK CONSTRAINT [fkSubEntryLog_SubSubscriberId]
GO

ALTER TABLE [dbo].[SubEntryLog]  WITH CHECK ADD  CONSTRAINT [fkSubEntryLog_SubUserId] FOREIGN KEY([SubUserId])
REFERENCES [dbo].[SubUser] ([SubUserId])
GO

ALTER TABLE [dbo].[SubEntryLog] CHECK CONSTRAINT [fkSubEntryLog_SubUserId]
GO

### Steps to reproduce

DbContext throws error on first use.

### Further technical details

The navigation '' cannot be added because it targets the keyless entity type 'SubEntryLog'. Navigations can only target entity types with keys.

**Comment by ajcvickers** [comment] 2020-01-17 16:19
Duplicate of #18633

**Closed** 2022-10-16 18:06 UTC
Labels: customer-reported
