### ISSUE TITLE
support for Update-DbContext command

### ISSUE THREAD

**Issue by tdjastrzebski** [dotnet/efcore#5232] opened 2016-04-30 00:29 UTC
Here is a typical scenario: SQL Server DB, EF data access layer and Web API JSON web service.
And just one, quite common requirement: some table/entity fields shall not be returned by web service. They are for internal use only so they still must be present in generated entities.

The easiest solution is to decorate entity fields which are to be hidden with attribute like `[JsonIgnore]`.
Since then, any DB changes have to manually reflected in DB context code since Scaffold-DbContext command will wipe out previously set attributes. That is not good.

Another intuitive solution: inherit from generated entity class, add properties which are to be hidden with "new" access modifier (unfortunately generated properties are not virtual) and `[JsonIgnore]` attribute, use in web service instead.

Obviously, the above will not work. That is for two reasons: just adding such inherited class DbSet<> will cause "Invalid column name 'Discriminator'." exception. Second: DbSet methods will fail during runtime if fed with such inherited object. Why they are defined like:

```
public abstract class DbSet<TEntity> where TEntity : class
{
   public virtual EntityEntry<TEntity> Add(TEntity entity);
```

instead of:

```
   public virtual EntityEntry<T> Add<T>(T entity) where T : class, TEntity;
}
```

Would not that make programmer's work easier?
The entire solution seems too 'type constrained' for no apparent reason. But perhaps it is too late for such design change.

So please, at least implement Update-DbContext command,

**Comment by rowanmiller** [comment] 2016-05-04 18:00
Duplicate of https://github.com/aspnet/EntityFramework/issues/831

**Closed** 2022-10-16 09:38 UTC
