### ISSUE TITLE
Entity Framework Core : seed data error using OwnsOne

### ISSUE THREAD

**Issue by eduardosilva** [dotnet/efcore#31373] opened 2023-07-28 17:52 UTC
I'm facing an issue while trying to seed data for the `Country` entity using Entity Framework Core.

My entity classes are set up as follows:

```cs
[DebuggerDisplay("{Name,nq}")]
public class Country
{
    public int Id { [DebuggerStepThrough] get; [DebuggerStepThrough] set; }

    public string Name { [DebuggerStepThrough] get; [DebuggerStepThrough] set; }

    public string Iso3 { [DebuggerStepThrough] get; [DebuggerStepThrough] set; }

    public string Iso2 { [DebuggerStepThrough] get; [DebuggerStepThrough] set; }

    public string NumericCode { [DebuggerStepThrough] get; [DebuggerStepThrough] set; }

    public string PhoneCode { [DebuggerStepThrough] get; [DebuggerStepThrough] set; }

    public string Capital { [DebuggerStepThrough] get; [DebuggerStepThrough] set; }

    public Currency Currency { [DebuggerStepThrough] get; [DebuggerStepThrough] set; }

    public Region Region { [DebuggerStepThrough] get; [DebuggerStepThrough] set; }

    public GeoLocation GeoLocation { [DebuggerStepThrough] get; [DebuggerStepThrough] set; }
}


[DebuggerDisplay("{Name,nq}")]
public class Currency
{
    public Currency(string code, string name, string symbol)
    {
        Code = code;
        Name = name;
        Symbol = symbol;
    }

    public string Code { [DebuggerStepThrough] get; [DebuggerStepThrough] set; }

    public string Name { [DebuggerStepThrough] get; [DebuggerStepThrough] set; }

    public string Symbol { [DebuggerStepThrough] get; [DebuggerStepThrough] set; }
}
```

In my `DbContext`, I have set up the configuration for the `Country` entity using `EntityTypeConfiguration`, including a one-to-one relationship with the `Currency` entity:

```cs
public class CountryEntityTypeConfiguration : IEntityTypeConfiguration<Country>
{
    public void Configure(EntityTypeBuilder<Country> builder)
    {
        builder.ToTable("countries");

        builder.HasKey(e => e.Id);

        builder.Property(e => e.Name)
               .HasMaxLength(100)
               .IsRequired();
        builder.Property(e => e.Iso3)
               .HasMaxLength(3)
               .IsRequired();
        builder.Property(e => e.Iso2)
               .HasMaxLength(2)
               .IsRequired();
        builder.Property(e => e.NumericCode)
               .HasMaxLength(3)
               .IsRequired();
        builder.Property(e => e.PhoneCode)
               .HasMaxLength(25)
               .IsRequired();
        builder.Property(e => e.Capital)
               .HasMaxLength(100)
               .IsRequired();

        builder.OwnsOne(e => e.Currency, c => {
            c.Property(_ => _.Code)
             .HasMaxLength(3)
             .IsRequired();

            c.Property(_ => _.Name)
             .HasMaxLength(45)
             .IsRequired();

            c.Property(_ => _.Symbol)
             .HasMaxLength(10)
             .IsRequired();
        });
        builder.OwnsOne(e => e.Region, r => {
            r.Property(_ => _.Name)
             .HasMaxLength(10)
             .IsRequired();

            r.Property(_ => _.Subregion)
             .HasMaxLength(30)
             .IsRequired();

        });
        builder.OwnsOne(e => e.GeoLocation);
    }
}
```

My migration creates the table exactly as I expected:

```cs
/// <inheritdoc />
public partial class InitialCreate : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "countries",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                iso3 = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                iso2 = table.Column<string>(type: "character varying(2)", maxLength: 2, nullable: false),
                numeric_code = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                phone_code = table.Column<string>(type: "character varying(25)", maxLength: 25, nullable: false),
                capital = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                currency_code = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                currency_name = table.Column<string>(type: "character varying(45)", maxLength: 45, nullable: false),
                currency_symbol = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                region_name = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                region_subregion = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                geo_location_latitude = table.Column<double>(type: "double precision", nullable: false),
                geo_location_longitude = table.Column<double>(type: "double precision", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_countries", x => x.id);
            });
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "countries");
    }
}
```

My seed:

```cs
modelBuilder.Entity<Country>().HasData(new Country { Id = 1, Name = "Afghanistan", Iso3 = "AFG", Currency = new Currency(code: "AFN", name: "Afghan afghani", symbol: "؋")});
```

However, when I try to seed data for the Country entity using the migration below, I get an error:

> The seed entity for entity type 'Country' with the key value 'Id:1' cannot be added because it has the navigation 'Currency' set. To seed relationships, add the entity seed to 'Currency' and specify the foreign key values {'CountryId'}.

full stack trace:

```bash
[28/07/23 14:44:59:494] warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
System.InvalidOperationException: The seed entity for entity type 'Country' with the key value 'Id:1' cannot be added because it has the navigation 'Currency' set. To seed relationships, add the entity seed to 'Currency' and specify the foreign key values {'CountryId'}.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateData(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.Internal.NpgsqlModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The seed entity for entity type 'Country' with the key value 'Id:1' cannot be added because it has the navigation 'Currency' set. To seed relationships, add the entity seed to 'Currency' and specify the foreign key values {'CountryId'}.
```
SaveChanges works fine:

```cs
DataContext.Countries.Add(new Country { Id = 1, Name = "Afghanistan", Iso3 = "AFG", Iso2 = "AF", NumericCode = "004", PhoneCode = "93", Capital = "Kabul", Currency = new Currency(code: "AFN", name: "Afghan afghani", symbol: "؋"), Region = new Region(name: "Asia", subregion: "Southern Asia"), GeoLocation = new GeoLocation(latitude: 33.00000000, longitude: 65.00000000)});
DataContext.SaveChanges();
```

```bash
[28/07/23 15:21:34:371] info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      => SpanId:0f4ebdac9676379b, TraceId:3a4f505b1eb8efde307c8d94a881c450, ParentId:0000000000000000 => ConnectionId:0HMSFITR6UVGQ => RequestPath:/api/country RequestId:0HMSFITR6UVGQ:00000001 => controllers.CountryController.Insert (dotnet-ef-redis)
      Executed DbCommand (71ms) [Parameters=[@p0='1', @p1='Kabul' (Nullable = false), @p2='AF' (Nullable = false), @p3='AFG' (Nullable = false), @p4='Afghanistan' (Nullable = false), @p5='004' (Nullable = false), @p6='93' (Nullable = false), @p7='AFN' (Nullable = false), @p8='Afghan afghani' (Nullable = false), @p9='؋' (Nullable = false), @p10='33', @p11='65', @p12='Asia' (Nullable = false), @p13='Southern Asia' (Nullable = false)], CommandType='Text', CommandTimeout='30']
      INSERT INTO countries (id, capital, iso2, iso3, name, numeric_code, phone_code, currency_code, currency_name, currency_symbol, geo_location_latitude, geo_location_longitude, region_name, region_subregion)
      VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13);
[28/07/23 15:21:34:412] info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[105]
      => SpanId:0f4ebdac9676379b, TraceId:3a4f505b1eb8efde307c8d94a881c450, ParentId:0000000000000000 => ConnectionId:0HMSFITR6UVGQ => RequestPath:/api/country RequestId:0HMSFITR6UVGQ:00000001
      Executed action controllers.CountryController.Insert (dotnet-ef-redis) in 4877.6581ms
[28/07/23 15:21:34:413] info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      => SpanId:0f4ebdac9676379b, TraceId:3a4f505b1eb8efde307c8d94a881c450, ParentId:0000000000000000 => ConnectionId:0HMSFITR6UVGQ => RequestPath:/api/country RequestId:0HMSFITR6UVGQ:00000001
      Executed endpoint 'controllers.CountryController.Insert (dotnet-ef-redis)'
```

Version Informations:

* Dotnet Core version: 7.0.109
* Microsoft.EntityFrameworkCore: 7.0.8
* Npgsql.EntityFrameworkCore.PostgreSQL: 7.0.4
* Linux - Ubuntu: 
    * No LSB modules are available.
    * Distributor ID:	Ubuntu
    * Description:	Ubuntu 22.04.2 LTS
    * Release:	22.04
    * Codename:	jammy

**Comment by dolphicom** [comment] 2023-07-31 00:33
Had the same problem. #14359 pushed me in the right direction. Your seeding code should look something like

``` c#
modelBuilder.Entity<Country>(c =>
{
    c.OwnsOne(p => p.Currency, curr =>
    {
        curr.HasData(new { CountryId = 1, Code = "AFN", Name = "Afghan afghani", Symbol = "؋" });
    })
    .HasData(new Country { Id = 1, Name = "Afghanistan", Iso3 = "AFG" });
});
```

While this could solve your problem, I'm still having troubles with that. First of all, with all the respect, I don't find this very intuitive. `OwnsOne()` is an entity config method and, in my humble opinion, has nothing to do with seeding.

My main trouble, however, is that since assigning a value directly isn't possible, I can't make my property (in the given example `Country.Currency`) `required`. Am I missing something?

**Comment by eduardosilva** [comment] 2023-07-31 19:15
@dolphicom this solution worked, but I believe it should be treated as a palliative solution rather than a definitive one because:

- It is not possible to use entities to perform the seed; only dynamics can be used.
- The increase in the number of lines to maintain the same record, in my case, is multiplied by four because I have relationships with `Currency`, `Region`, and `GeoLocation`. Thus, there is one line for `Country` and each of its related properties what makes maintaining the seed very difficult is that my script has around 270 countries.

```cs
public class CountryEntityTypeConfiguration : IEntityTypeConfiguration<Country>
{
    public void Configure(EntityTypeBuilder<Country> builder)
    {
        builder.ToTable("countries");

        builder.HasKey(e => e.Id);

        builder.Property(e => e.Name)
               .HasMaxLength(100)
               .IsRequired();
        builder.Property(e => e.Iso3)
               .HasMaxLength(3)
               .IsRequired();
        builder.Property(e => e.Iso2)
               .HasMaxLength(2)
               .IsRequired();
        builder.Property(e => e.NumericCode)
               .HasMaxLength(3)
               .IsRequired();
        builder.Property(e => e.PhoneCode)
               .HasMaxLength(25)
               .IsRequired();
        builder.Property(e => e.Capital)
               .HasMaxLength(100)
               .IsRequired();

        builder.OwnsOne(e => e.Currency, c => {
              c.Property(_ => _.Code)
              .HasMaxLength(3)
              .IsRequired();

              c.Property(_ => _.Name)
              .HasMaxLength(45)
              .IsRequired();

              c.Property(_ => _.Symbol)
              .HasMaxLength(10)
              .IsRequired();

              c.HasData(
                     new { CountryId = 1, Code = "AFN", Name = "Afghan afghani", Symbol = "؋" },
                     new { CountryId = 2, Code = "EUR", Name = "Euro", Symbol = "€" }
              );

        });
        builder.OwnsOne(e => e.Region, r => {
              r.Property(_ => _.Name)
              .HasMaxLength(10)
              .IsRequired();

              r.Property(_ => _.Subregion)
              .HasMaxLength(30)
              .IsRequired();

              r.HasData(
                     new { CountryId = 1, Name =  "Asia", Subregion =  "Southern Asia" }
                     , new { CountryId = 2, Name =  "Europe", Subregion =  "Northern Europe" }
              );

        });
        builder.OwnsOne(e => e.GeoLocation, g => {
              g.HasData(
                     new { CountryId = 1, Latitude =  33.00000000, Longitude =  65.00000000 }
                     , new { CountryId = 2, Latitude =  60.11666700, Longitude =  19.90000000 }
              );
        });

        builder.HasData(
         new Country { Id = 1, Name = "Afghanistan", Iso3 = "AFG", Iso2 = "AF", NumericCode = "004", PhoneCode = "93", Capital = "Kabul" }
        , new Country { Id = 2, Name = "Aland Islands", Iso3 = "ALA", Iso2 = "AX", NumericCode = "248", PhoneCode = "+358-18", Capital = "Mariehamn" }
        );
    }
}
```

What do you think about this?

**Comment by dolphicom** [comment] 2023-07-31 19:54
I totally agree. Back in the classic EntityFramework days, there was a [`DbModelBuilder.ComplexType<TComplexType>()`](https://learn.microsoft.com/en-us/dotnet/api/system.data.entity.dbmodelbuilder.complextype?view=entity-framework-6.2.0) method, which in my opinion was much more intuitive. [Here is an example.](https://weblogs.asp.net/manavi/associations-in-ef-4-1-code-first-part-2-complex-types)

**Comment by ajcvickers** [comment] 2023-08-02 19:21
Duplicate of #10000. Please vote (👍) for that issue.

**Closed** 2023-08-09 13:10 UTC
Labels: customer-reported
