### ISSUE TITLE
Incorrect handling of boolean fields

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#20902] opened 2020-05-10 11:15 UTC
## Steps to reproduce:

Use scaffold command to generate entities.

Scaffold-DbContext "Host=localhost;Port=5432;Database=testdb;Username=postgres;Password=password" Npgsql.EntityFrameworkCore.PostgreSQL -DataAnnotations -OutputDir Models

## Expected behavior:

non nullable boolean fields should not be nullable in generated models.

## Actual behavior:

some nullable boolean fields are nullable in generated models.

### Target framework(s):

.Net Core 3.1

The (PostgreSQL) database has the columns:

"printing_enabled" bool NOT NULL DEFAULT true,
"export_data" bool NOT NULL DEFAULT false

The generated model fields are:

[Required]
[Column("printing_enabled")]
public bool? PrintingEnabled { get; set; }

[Column("export_data")]
public bool ExportData { get; set; }

I'm not sure why both are not marked as Required and why PrintingEnabled is set as nullable?

Link to db script and sample project: https://1drv.ms/u/s!AgH_tMBurHdqii95fqUolVckFnaQ?e=CO7FZi

* I've reported it on the developer community as advised: https://developercommunity.visualstudio.com/content/problem/1024595/ef-scaffold-strange-handling-of-boolean-fields.html

**Comment by ajcvickers** [comment] 2020-05-10 15:51
Duplicate of #13613

**Comment by ErikEJ** [comment] 2020-12-29 12:26
This is "fixed" in the latest daily build of EF Core Power Tools

**Closed** 2022-10-16 18:24 UTC
Labels: customer-reported
