### ISSUE TITLE
net-native internal compiler error with 2.0.0-preview1-final

### ISSUE THREAD

**Issue by DamirLisak** [dotnet/efcore#8461] opened 2017-05-13 12:09 UTC
The compiler of VS Version 15.3 (26510.0-Preview) Preview is not able to compile the Release-Version of my App which uses "Microsoft.EntityFrameworkCore.Sqlite": "2.0.0-preview1-final".
The compiler returns with this error:
\microsoft.net.native.compiler\1.6.2\tools\Microsoft.NetNative.targets(691,5): error : Internal compiler error: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. (The object reference was not set to an object instance.)

Here the output:

```
2>  Der Typ "System.Reflection.BindingFlags" wurde in mehreren Assemblys gefunden.
2>  file:///C:/Devel/Private/HandballReporter/HandballReporter.uwp/obj/x86/Release/ilc/in/System.Reflection.TypeExtensions.dll
2>  file:///C:/Users/DLisak.GIP/.nuget/packages/microsoft.net.native.compiler/1.6.2/tools/x86/ilc/lib/Private/System.Private.Reflection.dll
2>  Generating System.Reflection.DispatchProxy proxy code.
2>  Running 'DumpNativeResources' transform, heap at 425 MB.
2>  Running 'ReducedCopyInitialize' transform, heap at 425 MB.
2>  Running 'ReducedCopyEmptyTypes' transform, heap at 459 MB.
2>  Running 'ReducedCopyPopulateTypes' transform, heap at 482 MB.
2>  Running 'ReducedCopyLateMetadata' transform, heap at 462 MB.
2>  Running 'ReducedCopyMethodBodies' transform, heap at 510 MB.
2>  Running 'ReducedCopyComplete' transform, heap at 571 MB.
2>  Running 'ReducedCopyCleanup' transform, heap at 510 MB.
2>  Running 'DeveloperExperienceModeOnlyCodeRemover' transform, heap at 510 MB.
2>  Running 'ComImportDetector' transform, heap at 522 MB.
2>  Running 'McgAccessor' transform, heap at 522 MB.
2>  Running 'McgRedirect' transform, heap at 527 MB.
2>  Running 'McgRedirect' transform, heap at 542 MB.
2>  Running 'McgTypeOf' transform, heap at 544 MB.
2>  Running 'ExceptionMiniaturizer' transform, heap at 563 MB.
2>  Running 'EventSource' transform, heap at 580 MB.
2>  Running 'ValueType' transform, heap at 580 MB.
2>  Running 'Attribute' transform, heap at 580 MB.
2>  Running 'GetType' transform, heap at 581 MB.
2>  Running 'McgFixups' transform, heap at 583 MB.
2>  Running 'ResourceManagerCtor' transform, heap at 585 MB.
2>  Running 'TypeofTypeHandle' transform, heap at 585 MB.
2>  Running 'DispatchProxyIntrinsics' transform, heap at 594 MB.
2>  Running 'StaticInitData' transform, heap at 595 MB.
2>  Running 'StartupCodeInjector' transform, heap at 531 MB.
2>  Running 'InjectAppContextSwitches' transform, heap at 531 MB.
2>  Running 'ImplementLibraryDynamicInvokeHelpers' transform, heap at 531 MB.
2>  Running 'Delegate' transform, heap at 531 MB.
2>  Running 'DelegateCtorCall' transform, heap at 545 MB.
2>  Running 'LazyGenerics' transform, heap at 556 MB.
2>  Running 'AddReflectionBlockedAttributes' transform, heap at 633 MB.
2>  Running 'DisableOptimization' transform, heap at 633 MB.
2>  Running 'CreateMetadata' transform, heap at 633 MB.
2>C:\Users\DLisak.GIP\.nuget\packages\microsoft.net.native.compiler\1.6.2\tools\Microsoft.NetNative.targets(691,5): error : Internal compiler error: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
2>  Die Ausführung von Task "RunILTransforms" wurde beendet – FEHLER.
2>  Die Erstellung des Ziels "RunILTransforms" in der Datei "ILTransforms" ist abgeschlossen – FEHLER.
2>  Die Erstellung des Projekts "ILTransforms" ist abgeschlossen – FEHLER.
2>  Kompilierungsfehler
2>  
2>  Der Befehl wurde mit dem Code 1201 beendet.
2>Die Ausführung der LoggerBasedExecTask-Aufgabe ist abgeschlossen -- FEHLER.
2>Die Erstellung des Ziels "BuildNativePackage" im Projekt "HandballReporter.uwp.csproj" ist abgeschlossen -- FEHLER.
2>Ziel "LogIlcBehavioralDifference" in Datei "C:\Users\DLisak.GIP\.nuget\packages\microsoft.net.native.compiler\1.6.2\tools\Microsoft.NetNative.targets" aus Projekt "C:\Devel\Private\HandballReporter\HandballReporter.uwp\HandballReporter.uwp.csproj" (Ziel "BuildNativePackage" ist davon abhängig):
2>Die IlcErrorTask-Aufgabe wurde übersprungen, da die Bedingung "false" war . ('$(_IlcExitCode)' != '' and '$(_IlcExitCode)' >= '$(_IlcMinBehavioralExitCode)') wurde als ('1201' != '' and '1201' >= '1400') ausgewertet.
2>Die Erstellung des Ziels "LogIlcBehavioralDifference" im Projekt "HandballReporter.uwp.csproj" ist abgeschlossen.
2>Das Ziel "_CheckForCompileOutputs" wurde übersprungen. Die vorherige Erstellung war erfolgreich.
2>Das Ziel "_SGenCheckForOutputs" wurde übersprungen, da die Bedingung "false" war . ('$(_SGenGenerateSerializationAssembliesConfig)' == 'On' or ('@(WebReferenceUrl)'!='' and '$(_SGenGenerateSerializationAssembliesConfig)' == 'Auto')) wurde als ('Auto' == 'On' or (''!='' and 'Auto' == 'Auto')) ausgewertet.
2>Ziel "_CleanGetCurrentAndPriorFileWrites" in Datei "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets" aus Projekt "C:\Devel\Private\HandballReporter\HandballReporter.uwp\HandballReporter.uwp.csproj" (Ziel "_CleanRecordFileWrites" ist davon abhängig):
2>ReadLinesFromFile-Aufgabe
2>Ausführen der ReadLinesFromFile-Aufgabe beendet.
2>ConvertToAbsolutePath-Aufgabe
2>Ausführen der ConvertToAbsolutePath-Aufgabe beendet.
2>FindUnderPath-Aufgabe
2>  Der Vergleichspfad ist "C:\Devel\Private\HandballReporter\HandballReporter.uwp".
2>Ausführen der FindUnderPath-Aufgabe beendet.
2>FindUnderPath-Aufgabe
2>  Der Vergleichspfad ist "bin\x86\Release\".
2>Ausführen der FindUnderPath-Aufgabe beendet.
2>FindUnderPath-Aufgabe
2>  Der Vergleichspfad ist "obj\x86\Release\".
2>Ausführen der FindUnderPath-Aufgabe beendet.
2>RemoveDuplicates-Aufgabe
2>Ausführen der RemoveDuplicates-Aufgabe beendet.
2>Die Erstellung des Ziels "_CleanGetCurrentAndPriorFileWrites" im Projekt "HandballReporter.uwp.csproj" ist abgeschlossen.
2>Ziel "_CleanRecordFileWrites" in Datei "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets" aus Projekt "C:\Devel\Private\HandballReporter\HandballReporter.uwp\HandballReporter.uwp.csproj" (Ziel "CoreBuild" ist davon abhängig):
2>RemoveDuplicates-Aufgabe
2>Ausführen der RemoveDuplicates-Aufgabe beendet.
2>MakeDir-Aufgabe
2>Ausführen der MakeDir-Aufgabe beendet.
2>WriteLinesToFile-Aufgabe
2>Ausführen der WriteLinesToFile-Aufgabe beendet.
2>Die Erstellung des Ziels "_CleanRecordFileWrites" im Projekt "HandballReporter.uwp.csproj" ist abgeschlossen.
2>
2>Fehler beim Buildvorgang.

```
@divega : I tried to use 2.0.0-preview1-final to find out if the problem https://github.com/aspnet/EntityFramework/issues/7614 is maybe solved.

**Comment by ajcvickers** [comment] 2017-05-16 01:04
@MattWhilden This looks like an internal issue with the .NET Native compiler. Issue #7614 may be related and we have a repro from the customer for that issue if it helps. We can probably get a repro for this issue as well if it would help.

**Comment by MattWhilden** [comment] 2017-06-14 21:38
Yep. That's a real crash in the compiler. I've opened an issue in our internal tracker to get someone to dig into it. The number (in case anyone asks) is 404378. I'm jumping on a plane in an hour so I won't have time to wrestle with it myself. I'll make sure someone can investigate in my stead.

**Comment by DennisSc** [comment] 2017-06-20 21:25
I can reproduce as well: 

with the nuget package **"Microsoft.Data.SQLite"** (which, I think, is what EntityFramework.sqlite uses as well?), my app doesn't build in release mode. The same error as described above, when using "2.0.0-preview1-final": build fails in release mode, "internal compiler error: reference not set to instance of object" when creating the ilc files, on three different build systems (one of them is a hosted build agent from visualstudio.com). When compiling in debug mode, all is fine.

When switching back to "Microsoft.Data.SQLite 1.1.1", release and debug builds both  succeed.

Should I open an issue over [there](https://github.com/aspnet/Microsoft.Data.Sqlite)?

regards

**Comment by MichalStrehovsky** [comment] 2017-06-29 00:02
EF uses a feature of valuetuples that exposes a bug in .NET Native.

The bug is discussed in more detail here: dotnet/roslyn#18737.

It can be worked around by adding this line to your RD.XML (it's a file you can find in the Properties directory of your UWP project - it gets added automatically to every UWP project):

```xml
<Type Name="Microsoft.Data.Sqlite.SqliteDataReader" Browse="Excluded" Dynamic="Excluded" Serialize="Excluded" Activate="Excluded" />
```

The underlying issue is that the SqliteDataReader class has a field that looks like this:

```csharp
		[TupleElementNames(new string[]
		{
			"stmt",
			null
		})]
		private readonly Queue<ValueTuple<sqlite3_stmt, bool>> _stmtQueue;
```

The null in the `TupleElementNames` triggers the bug.

@ajcvickers - EF might want to consider shipping with a workaround. We have a fix in the pipeline, but it might take a while and might not reach all customers. Ideally, don't use valuetuples that might end up with the null in the custom attribute (I don't know under what conditions Roslyn emits those).

**Comment by ajcvickers** [comment] 2017-06-29 00:05
@MichalStrehovsky Thanks for the info. Clearing milestone to re-triage.

**Comment by ajcvickers** [comment] 2017-06-30 19:10
Closing this since it seems from comments on dotnet/roslyn#18737 this is being fixed in a timeframe that works for us.

**Closed** 2022-10-16 11:04 UTC
Labels: closed-external, area-external
