### ISSUE TITLE
[.NET 6] Migrate API - Could not find method 'AddYears' on type 'System.DateOnly'

### ISSUE THREAD

**Issue by jianmingyong** [dotnet/efcore#26860] opened 2021-12-01 01:44 UTC
If users were to use the trimming option in .NET 6, one might face this exception if they used Migrate() or MigrateAsync() API.

```
Could not find method 'AddYears' on type 'System.DateOnly' at System.SharedTypeExtensions.GetRequiredRuntimeMethod(Type type, String name, Type[] parameters)
```

For now, it can be workaround with adding a line of code (preferably in main class) or using rd.xml

```c#
/// <summary>
/// FIXME: This is required for EF Core 6.0 as it is not compatible with trimming.
/// </summary>
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
private static Type _keepDateOnly = typeof(DateOnly);
```

### Include provider and version information

EF Core version: 6.0.0
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022

#26383 #21894

**Comment by roji** [comment] 2021-12-01 07:36
Duplicate of #26288

**Comment by roji** [comment] 2021-12-01 07:37
#26288 tracks making all reflection-based method lookup compatible with trimming (rather than having an issue for each method).

**Comment by roji** [comment] 2022-01-03 13:37
@jianmingyong I've started to look into this, could you please post a full stack trace of the exception you got with AddYears? I'm specifically interested since that exception was triggered from Migrate.

**Closed** 2022-10-16 20:17 UTC
Labels: customer-reported
