### ISSUE TITLE
.NET Core CLI add migration command inconsistently using wrong DbContext constructor

### ISSUE THREAD

**Issue by darranromo** [dotnet/efcore#27963] opened 2022-05-06 07:15 UTC
We're seeing inconsistent issues with the following command:

```
dotnet ef migrations add MigrationName -v
```

After many hours of investigating, we believe the tool is (sometimes) using the wrong constructor when attempting to create our DbContext object. 

In the attached test project we've created to demonstrate the issue, our TestContext (inherits from DbContext) has several constructors:

```C#
        public TestContext() : base() { }

        private static DbContextOptions GetOptions(string connectionString) => SqlServerDbContextOptionsExtensions.UseSqlServer(new DbContextOptionsBuilder(), connectionString).Options;

        public TestContext(string connectionString) : base(GetOptions(connectionString)) { }


        public TestContext(DbContextOptions<TestContext> dbContextOptions) : base(dbContextOptions) { }
```

Our context objects are created within their own class libraries which are then consumed from either HostedService or WebAPI projects.

According to the [documentation](https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#using-a-constructor-with-no-parameters) the tool should pick up the constructor with no parameter given there is no application service provider. This has been working perfectly over a couple of projects.

The problem started when we tried to add a new table (which would have been the 43rd table) to an existing project. However, we can also replicate it with an initial add of objects.

The error would be similar to:

```
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'TestDLL'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'TestContext'.
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'TestContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[ConsoleApp2.TestContext]' while attempting to activate 'ConsoleApp2.TestContext'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_4.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_4.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

Sometimes editing the class by re-arranging the order of the constructors and re-trying will allow it to work. Sometimes the tool will pick up the connection string constructor.

In the attached project, run an initial create: dotnet ef migrations add InitialCreate -v

That worked for me with the current 39 tables (but not with 41). Then I commented in the DbSet for Class40 and did: dotnet ef migrations add class40 -v

That also worked. However, commenting in the DbSet for Class41 and doing: dotnet ef migrations add class41 -v

Failed with:

```
Using project 'C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\TestDLL.csproj'.
Using startup project 'C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\TestDLL.csproj'.
Writing 'C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\obj\TestDLL.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\darran\AppData\Local\Temp\tmp4B10.tmp /verbosity:quiet /nologo C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\TestDLL.csproj
Writing 'C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\obj\TestDLL.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\darran\AppData\Local\Temp\tmp4CB7.tmp /verbosity:quiet /nologo C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\TestDLL.csproj
Build started...
dotnet build C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\TestDLL.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.93
Build succeeded.
dotnet exec --depsfile C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\bin\Debug\net5.0\TestDLL.deps.json --additionalprobingpath C:\Users\darran\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --additionalprobingpath "C:\Program Files (x86)\Progress\ToolboxNuGetPackages" --additionalprobingpath "C:\Program Files (x86)\Microsoft\Xamarin\NuGet" --runtimeconfig C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\bin\Debug\net5.0\TestDLL.runtimeconfig.json C:\Users\darran\.dotnet\tools\.store\dotnet-ef\6.0.3\dotnet-ef\6.0.3\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll migrations add class41 --assembly C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\bin\Debug\net5.0\TestDLL.dll --project C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\TestDLL.csproj --startup-assembly C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\bin\Debug\net5.0\TestDLL.dll --startup-project C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\TestDLL.csproj --project-dir C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\ --root-namespace TestDLL --language C# --framework net5.0 --working-dir C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2 --verbose
Using assembly 'TestDLL'.
Using startup assembly 'TestDLL'.
Using application base 'C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\bin\Debug\net5.0'.
Using working directory 'C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2'.
Using root namespace 'TestDLL'.
Using project directory 'C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'TestDLL'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'TestContext'.
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'TestContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[ConsoleApp2.TestContext]' while attempting to activate 'ConsoleApp2.TestContext'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_4.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_4.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to create an object of type 'TestContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

My dotnet ef version is:
```
PS C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2> dotnet ef migrations add class41 -v^C
PS C:\Users\darran\Downloads\ConsoleApp2\ConsoleApp2> dotnet ef --version
Entity Framework Core .NET Command-line Tools
6.0.3
```

If we comment out all constructors other than the empty constructor then it always works.
[ConsoleApp2.zip](https://github.com/dotnet/efcore/files/8638249/ConsoleApp2.zip)

**Comment by bricelam** [comment] 2023-08-28 21:32
Duplicate of https://github.com/dotnet/runtime/issues/46132

**Closed** 2023-12-12 21:07 UTC
Labels: closed-external, customer-reported, punted-for-7.0
