### ISSUE TITLE
ObjectDisposedException after migration on net5

### ISSUE THREAD

**Issue by sungam3r** [dotnet/efcore#26196] opened 2021-09-28 08:23 UTC
See full repro here: [repos.zip](https://github.com/dotnet/efcore/files/7242283/repos.zip)

Works well on netcoreapp3.1 but yields `ObjectDisposedEsception: cannnot access a disposed context instance. A common cause ...` on net5.
___
netcoreapp31: 6 tests passed
net5: 5 tests passed, 1 test failed (warmup DbContextPool **after** services)

**Comment by sungam3r** [comment] 2021-09-28 08:42
UPDATE: if comment `using (var scope = _provider.CreateScope())` in `ServicesWarmUpModule` and change `scope.ServiceProvider.GetServices(serviceType);` to `_provider.GetServices(serviceType);` then all tests passed. I think that the cause of problem is inner scope - `WarmUpExtensions.WarmUp` method has already created scope: ` using var scope = provider.CreateScope();` so all code inside alll warmup modules is executed "under" this scope. So the question is, why did creating the inner scope crush this example?

**Comment by ajcvickers** [comment] 2021-09-28 16:56
@sungam3r The DbContext is disposed when the scope is disposed. This is expected behavior; I'm not sure why it wasn't doing that in 3.1, but the 5.0 behavior looks correct to me.

**Comment by sungam3r** [comment] 2021-09-28 18:47
I use `DbContextPool` (or `IDbContextPool` for net5), not `DbContext` directly. When "disposed" `DbContext` just returned (_should be_ returned as I would say) to this pool. But for net5 when I call `IDbContextPool.Rent` method it for some reason returns destroyed `DbContext` object which is obvious wrong.

**Comment by ajcvickers** [comment] 2021-09-28 18:55
@sungam3r Can you post a simple repro that shows this? The sample you have is very convoluted. Also, the way context pooling works was changed in 5.0. If you were relying on directly using the pool methods instead of relying on D.I. to do its thing, then the behavior may have changed. See https://github.com/dotnet/efcore/pull/21431. That being said, there may be a bug, so a simple repro would be useful.

**Comment by sungam3r** [comment] 2021-09-28 19:03
> Can you post a simple repro that shows this? The sample you have is very convoluted. 

Well... I already cut off from production code all non-related things from code to demonstrate this bug.

> so a simple repro would be useful.

I did not expect that this example will seem complex. I will try to make it even easier, but it will take time.

**Comment by ajcvickers** [comment] 2021-09-28 19:05
@sungam3r You said:

> But for net5 when I call IDbContextPool.Rent method it for some reason returns destroyed DbContext object which is obvious wrong.

What I'm looking for is an example of when this happens that doesn't involve the "warm-up" stuff which is very convoluted.

**Comment by sungam3r** [comment] 2021-09-28 19:35
[Solution1_net50_simpler.zip](https://github.com/dotnet/efcore/files/7246812/Solution1_net50_simpler.zip)

**Comment by sungam3r** [comment] 2021-09-28 19:50
[Solution1_net50_the_simplest.zip](https://github.com/dotnet/efcore/files/7246886/Solution1_net50_the_simplest.zip)
@ajcvickers done

**Comment by ajcvickers** [comment] 2021-09-30 11:12
@sungam3r This is because calling Rent on the pool directly bypasses the DbContext leasing mechanism. Resolving the context directly from D.I. works, as does explicitly resolving a lease. Note, however, that both renting the context directly and using the lease directly involve calling EF Core internal APIs, and so are not recommended.

Minimal repro:

```C#
public class DbWarmUpTests
{
    [Test]
    public void WarmUpDbContextPool_Should_Work()
    {
        var provider = new ServiceCollection()
            .AddDbContextPool<MyDbContext>(b => b.UseInMemoryDatabase(nameof(WarmUpDbContextPool_Should_Work)))
            .BuildServiceProvider();

        using var outerScope = provider.CreateScope();

        using (var innerScope = provider.CreateScope())
        {
            innerScope.ServiceProvider.GetService<MyDbContext>();
        }

        // This works:
        // var context = outerScope.ServiceProvider.GetService<MyDbContext>();

        // This works:
        // var lease = outerScope.ServiceProvider.GetService<IScopedDbContextLease<MyDbContext>>();
        // var context = lease.Context;

        // This fails:
        var pool = outerScope.ServiceProvider.GetService<IDbContextPool<MyDbContext>>();
        var context = (MyDbContext)pool.Rent();

        context.Persons.Any();
    }
}

public class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions<MyDbContext> options)
        : base(options)
    {
    }

    public DbSet<Person> Persons { get; set; }
}

public class Person
{
    public int Id { get; set; }
}
```

**Comment by sungam3r** [comment] 2021-09-30 17:36
My task is to maximum prepare app for handling future requests. If the app uses `DbContext` without pooling (`AddDbContext` extension method) then warmup calls supplied delegate onto injected `DbContext`, see `DbContextWarmupModule` in my initial example. If the app uses pooled `DbContext` (`AddDbContextPool`) then warmup rents `DbContext` from pool, calls supplied delegate and returns `DbContext` to pool back.

The point is that when warming up, call as much code as possible, which will be called when processing the future request. So I thought that `Rent/Return` APIs are quite suitable for this. You said that calling `Rent` directly bypasses the `DbContext` leasing mechanism. OK. Do I understand you correctly that to solve my task I do not need to work at all with `IDbContextPool`, but just to inject `DbContext` into my warmup classes? And all "pooling stuff" will be performed behind the scenes. Right? In other words, warming up with a pool or without a pool looks the same - just call some delegate onto provided/injected `DbContext`.

**Comment by ajcvickers** [comment] 2021-09-30 17:41
If you're using pooling with D.I., then you should obtain the DbContext from D.I. in the normal way. That is, request the DbContext from a scope, and it will be disposed when the scope is disposed.

**Comment by sungam3r** [comment] 2021-09-30 19:09
Thanks.

**Closed** 2022-10-16 20:09 UTC
Labels: closed-no-further-action, customer-reported
