### ISSUE TITLE
OwnsMany overrides HashSet's IEqualityComparer so that I can't use Contains to check that ValueObject exists in collection

### ISSUE THREAD

**Issue by goncharov-do** [dotnet/efcore#18367] opened 2019-10-14 17:37 UTC
I followed such recommendations for implementing ValueObjects:
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects

The problem is that If I work with manually created in memory Value Object collection, it works. If Value object collection is extracted using Entity Framework, **Contains** does not work.

I don't have idea how can I use Contains to find that element has been added in HashSet. So I can use .All.Where and find manually, but maybe you could recommend how can I use native methods like Contains from HashSet to do the same operation?

### Steps to reproduce

You can find my sample project in the following repository:
https://github.com/goncharov-do/EfCore3VOBugs/tree/hashset-behaviour

It is just console app which creates new database on local SqlServer ( "." ), removes
database "EfCoreV3Bugs", creates it, migrate, inserts test entity, and tries to find using Contains ValueObject in HashSet.

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.3

**Comment by ajcvickers** [comment] 2019-10-15 17:09
Duplicate of #4179 since `ValueObject` is not mapped as (or intended to be) an entity type. Workarounds are included in that issue--notably using a value converter to serialize the collection into a column.

Also, it might be worth learning EF without using complex patterns like those suggested in various DDD-style guidance. These patterns often make it hard to see what is actually happening.

**Comment by goncharov-do** [comment] 2019-10-16 05:26
@ajcvickers   EF Core 3 allows as to create a Collection of ValueObject stored separately from parent Entity / ValueObject. If I understand your idea correctly, you propose to store the entire collection in a serialized way. Actually I can do this using JSON Convention like

```
.HasConversion(
                    u => JsonConvert.SerializeObject(u.ToList(),
                        new JsonSerializerSettings {NullValueHandling = NullValueHandling.Ignore}),
                    u => JsonConvert.DeserializeObject<List<GradingFormScoreMapping.ExtraMapping>>(u,
                        new JsonSerializerSettings {NullValueHandling = NullValueHandling.Ignore}))

```
, but it would not be flexible in a Read scenarios. I want it to be stored in separate table, which allowed by using OwnsMany feature. So it does not solve my problem.

**Comment by goncharov-do** [comment] 2019-10-16 05:43
@ajcvickers "Mapping to a table which contains the values and collapsing that mapping down to the IEnumerable/ICollection property on the entity. (See #14115)"
The second solution does not solve my problem as well, because I don't need ValueObject to be an Entity (in context of EF, don't want to use HasMany instead of OwnsMany).

**Comment by goncharov-do** [comment] 2019-10-16 07:06
@ajcvickers One of the possible solutions I have found, is using List instead of HashSet to define backing field with ValueObjects collection. In this way no exception thrown during executing the example project. Can you please comment if any reasons not to implement it in this way? I remember in EF v2.1 it was not possible to use HashSet for OwnsMany collections.

https://github.com/goncharov-do/EfCore3VOBugs/pull/1

If you approve that solution, makes sense to remove 'closed-duplicate' label and mark as having solution.

**Comment by goncharov-do** [comment] 2019-10-16 08:40
I found the comment, which clarifies why List did not work for me before:
https://github.com/aspnet/EntityFrameworkCore/issues/10800#issuecomment-487058862

**Comment by goncharov-do** [comment] 2019-10-16 08:46
btw I still wonder why HashSet's Contains does not work, but List's works. Is it by design?

**Comment by ajcvickers** [comment] 2019-10-16 17:50
@goncharov-do Thanks for the additional info. I will investigate further.

**Comment by ajcvickers** [comment] 2019-10-16 21:52
@goncharov-do Several things are going on here. First, since a `HashSet` cannot have duplicate entries it means that, even before EF is used, the collection only contains one entry, even though two were added, because they both test as equal. (This may be intentional, of course, although it would then not be valid to switch to a List.)

Second, EF can only track a _single instance_ of a given entity type with a given key. This means that if it is your intention that the equality semantics of the value object are maintained (i.e. the first point above is intentional) then this will likely run into issues with EF since it does not work with this pattern. (The primary reason for this is that entity types don't work like DDD value objects. Sometimes owned types can be used to solve some of the same problems as value objects, but this requires a pretty good understanding of what is going on behind the abstraction.)

Third, because EF makes use of reference semantics, when EF creates a `HashSet` for you, it creates one that uses reference semantics. This is why your last check on the collection fails--it is trying to find the same object instance, rather than an instance that tests as equal.)

Using a `List` doesn't have some of these issues because it allows duplicates. However, fundamentally there still can't be duplicates in EF because EF uses reference semantics, as described above. It also doesn't match DDD value objects at all--hence my comment above that if removing duplicates is intentional, then using a List is probably not correct.)

In my opinion, trying to use owned entities as DDD-style value objects is a pit-of-failure. It can be made to work for some cases if you have a good understanding of the required semantics and what that means for mapping and functionality in EF, but it's hard to get right. Instead, use a value converter to do inline conversion between the database value and the value object, in which case #4179 is relevant again.

**Closed** 2022-10-16 14:49 UTC
Labels: closed-no-further-action, customer-reported
