### ISSUE TITLE
Scaffold without constraint names?

### ISSUE THREAD

**Issue by sbrockway** [dotnet/efcore#18911] opened 2019-11-14 18:05 UTC
Is it possible to scaffold without emitting constraint names (e.g. foreign keys)? This seems unnecessary and the binding to a name ?may? cause a problem if someone renames the constraint in the database.
Might even make sense to turn this off by default unless people opt in. If we are scaffolding from an existing database, chances are we aren't going to use EF to create the database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1601c3e-3f29-5d84-6350-2b38eeaf6adc
* Version Independent ID: 92a856d6-c5da-e215-46ac-d67c411f3ff9
* Content: [Reverse Engineering - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding)
* Content Source: [entity-framework/core/managing-schemas/scaffolding.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/scaffolding.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment] 2019-11-14 22:52
Duplicate of #10890

**Closed** 2022-10-16 14:56 UTC
Labels: customer-reported
