### ISSUE TITLE
'Add Migrations' after Migrating to 2.0

### ISSUE THREAD

**Issue by QuantumHive** [dotnet/efcore#9506] opened 2017-08-21 20:36 UTC
In `ef core 1.1`, I had some migrations like so:
[
![capture](https://user-images.githubusercontent.com/2554952/29536805-9a2305f4-86bf-11e7-9ce3-4acc65e98ae3.PNG)
](url)

So now I'm trying to [migrate to `v2.0`](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/index). So after adding a new Migration with the [Command Line Tools](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet) like this one:

`dotnet ef migrations add MigrateToAspNetCore2`

I'm getting a successfull migration:

![capture](https://user-images.githubusercontent.com/2554952/29536965-305ee452-86c0-11e7-8f3b-87e2cc578337.PNG)

**Note** that I run this in `cmd`.

Now when I look in the Solution Explorer, I see *nothing*.
When I enable `Show All Files` on the Solution Explorer, I see the following:

![capture](https://user-images.githubusercontent.com/2554952/29537085-9ea7dad6-86c0-11e7-8592-0b0569e5c311.PNG)

When I disable `Show All Files`, it's still there the same.
When I unload and reload the project:

![capture](https://user-images.githubusercontent.com/2554952/29537140-ddbff690-86c0-11e7-84c3-527bdebd0443.PNG)

Operating system: Windows 10 Build 1703
IDE: Visual Studio 2017 Version 15.3.1

**Comment by bricelam** [comment] 2017-08-22 16:37
We strongly recommend using the PMC tools (`Add-Migration` and friends) in Visual Studio since it provides a more integrated experience.

**Comment by QuantumHive** [comment] 2017-08-22 19:46
Well after trying it with the PMC tools, the migration file seems to be included immediately. However I'd like to note that when using the Command Line Tools, the issue didn't arise in the previous dotnet core version `1.1`.
Also a new issue arises when doing `Remove-Migration` after I've did `Add-Migration`:

```
PM> Add-Migration MigrateToDotNetCore2
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\Quant\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Microsoft.EntityFrameworkCore.Infrastructure[100403]
      Entity Framework Core 2.0.0-rtm-26452 initialized 'RowinContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
To undo this action, use Remove-Migration.
PM> Remove-Migration
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\Quant\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Microsoft.EntityFrameworkCore.Infrastructure[100403]
      Entity Framework Core 2.0.0-rtm-26452 initialized 'RowinContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Microsoft.EntityFrameworkCore.Database.Command[200101]
      Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'__EFMigrationsHistory');
Microsoft.EntityFrameworkCore.Database.Command[200101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
Removing migration '20170822193851_MigrateToDotNetCore2'.
Reverting model snapshot.
Done.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Tools.Json.Escape(String text)
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsRemoveCommand.ReportJsonResults(IDictionary result)
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsRemoveCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Object reference not set to an instance of an object.
{
  "migrationFile": "D:\\dev\\quantumhive\\rowinpt\\src\\rowinpt.api\\Migrations\\20170822193851_MigrateToDotNetCore2.cs",
  "metadataFile": "D:\\dev\\quantumhive\\rowinpt\\src\\rowinpt.api\\Migrations\\20170822193851_MigrateToDotNetCore2.Designer.cs",
PM> 
```

Also the migration file gets stuck in the Solution Explorer UI, but on disk doesn't exists anymore after I did `Remove-Migration`. When I reload the project, the file disappears from the Solution Explorer.

**Comment by smitpatel** [comment] 2017-08-22 19:57
@QuantumHive That error is duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/9280

**Comment by bricelam** [comment] 2017-08-23 16:01
> the issue didn't arise in the previous dotnet core version

Agree, it is a bug. VS is supposed to automatically add new files to the project. Could you report it on [dotnet/project-system](https://github.com/dotnet/project-system)?

**Closed** 2022-10-16 11:17 UTC
Labels: closed-external
