### ISSUE TITLE
Support SQL Server FILESTREAM

### ISSUE THREAD

**Issue by pankleks** [dotnet/efcore#4983] opened 2016-04-05 13:24 UTC
Hi,

How can I mark column as FILESTREAM?

I created following table:

```
create table Document (
    Id UNIQUEIDENTIFIER ROWGUIDCOL PRIMARY KEY,
    Data VARBINARY(MAX) FILESTREAM
)
```

When I generated code using scaffold it does not look like anything specific is generated to mark it as FILESTREAM.

Thanks!

**Comment by rowanmiller** [comment] 2016-04-05 20:41
We currently don't have support for `filestream`. You may just be able to treat it as a `varbinary` column... but of course you wouldn't get streaming. Moving this to the backlog to support post v1.0.0

**Comment by divega** [comment] 2016-08-08 22:17
Closing as dupe of #4573.

**Closed** 2022-10-16 09:35 UTC
