### ISSUE TITLE
Unsupported uint data type in LINQ select statement

### ISSUE THREAD

**Issue by scblason** [dotnet/efcore#14782] opened 2019-02-22 16:32 UTC
I know that there are issues (or unsupported) with unsigned values in DB.
But in this case, I'm using an uint variable to set an anonymous select object, and is throwing a casting exception:

```C#
uint test = 23;
uint idProduct = 12;
DbContext RepositoryContext = new ndsContext();
IQueryable query = from p in RepositoryContext.Products
                                                              where p.IdProduct.Equals(idProduct)  //Theres an issue reported: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/language-reference/known-issues-and-considerations-in-linq-to-entities#UnsignedIntsUnsupported but this works fine
                                                              select new
                                                              {
                                                                  IdProduct = p.IdProduct, //p.IdProduct is an uint and it works 
                                                                  IdSet = test, //This fails with a InvalidCastException
                                                                  Order = 0
                                                              };
```

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: An exception occurred while reading a database value. The expected type was 'System.UInt32' but the actual value was of type 'System.Int64'
```

### Steps to reproduce
As seen in the code above, when I use a uint variable ("test") to set an anonymous property, it treats it as an Int64 value. The thing is that this value is not from the database, its just a local variable.
Why does it fails? It's a problem with LINQ to Entities? Or maybe the provider (Pomelo)?

### Further technical details
<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="2.1.3" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.1.3" />
<PackageReference Include="Swashbuckle.AspNetCore" Version="3.0.0" />
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.1.2" />

Operating system: MacOS
IDE: Visual Studio 2017 Community for Mac 7.7.3

**Comment by ajcvickers** [comment] 2019-02-25 20:11
@scblason I have not been able to reproduce this. Can you post a small, runnable project/solution or complete code listing (like mine below) that demonstrates the behavior you are seeing?

```C#
public class Product
{
    [Key]
    public int IdProduct { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    public DbSet<Product> Products { get; set; }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.AddRange(new Product(), new Product());

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            uint test = 23;
            uint idProduct = 12;

            var query = from p in context.Products
                where p.IdProduct.Equals(idProduct)
                select new
                {
                    IdProduct = p.IdProduct,
                    IdSet = test,
                    Order = 0
                };

            var results = query.ToList();
        }
    }
}
```

**Comment by ajcvickers** [comment] 2019-03-04 17:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:53 UTC
Labels: closed-could-not-reproduce, customer-reported
