### ISSUE TITLE
ef migrations bundle error: warning MSB3026 - The process cannot access the file

### ISSUE THREAD

**Issue by ipax77** [dotnet/efcore#27544] opened 2022-03-02 12:35 UTC
Referring to [26479](https://github.com/dotnet/efcore/issues/26479):

It seems that as soon as you have a different migration-assembly the bundle process is failing e.g.:

`dotnet ef migrations bundle --project ..\mf.db\ --verbose`

`
C:\Program Files\dotnet\sdk\6.0.200\Microsoft.Common.CurrentVersion.targets(4631,5): warning MSB3026: "obj\Debug\net6.0\mf.api.dll" konnte nicht in "bin\Debug\net6.0\mf.api.dll" kopiert werden. Wiederholung 1 wird in 1000 ms gestartet. The process cannot access the file '<...>\mf.api\bin\Debug\net6.0\mf.api.dll' because it is being used by another process.
`

EF Core version: 6.0.200
Operating system: Windows and Linux

**Comment by axylophon** [comment] 2022-03-03 16:32
We have the same issue

**Comment by ajcvickers** [comment] 2022-03-04 16:41
Duplicate of #25555

**Closed** 2022-10-16 20:27 UTC
Labels: customer-reported
