### ISSUE TITLE
EFCore cli tool command "dotnet ef dbcontext scaffold" , Options: -d|--data-annotations ,'-d' is invalid

### ISSUE THREAD

**Issue by hdefucom** [dotnet/efcore#27780] opened 2022-04-07 09:38 UTC
dotnet cli tool .

Use  Oracle database to generate entities.
```
 dotnet ef dbcontext scaffold -d .....

//-d is invalid
 entity.Property(e => e.FIELD)
                    .HasMaxLength(300)
                    .IsUnicode(false);

----------------------------------------------------

 dotnet ef dbcontext scaffold  --data-annotations .....

//--data-annotations is[valid
[StringLength(300)]
[Unicode(false)]
public string FIELD { get; set; }

```
Invalid abbreviation option

Use Nuget Package,Include older versions
```
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.3">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Oracle.EntityFrameworkCore" Version="6.21.5" />
	</ItemGroup>

```

**Comment by ajcvickers** [comment] 2022-04-07 10:38
Duplicate of #26687.

**Closed** 2022-10-16 20:31 UTC
Labels: closed-duplicate, customer-reported
