### ISSUE TITLE
Sqlite.NetTopologySuite caused the program to crash.  Failure module:libwinpthread-1.dll

### ISSUE THREAD

**Issue by flyfire-cn** [dotnet/efcore#14561] opened 2019-01-31 06:52 UTC
I used it in the project
Microsoft. EntityFrameworkCore. Sqlite
It works

Installation of the
Microsoft.EntityFrameworkCore.Sqlite.Net TopologySuite
After that,
Run the program, do nothing, about twenty to forty minutes or so, the program crashes.

Exception message:
Stack trace:Application Error
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-01-31T04:38:57.419531300Z" /> 
  <EventRecordID>342764</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>ThinkPad_FlyFire</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>dotnet.exe</Data> 
  <Data>2.2.27207.3</Data> 
  <Data>5c0ab1b7</Data> 
  <Data>libwinpthread-1.dll</Data> 
  <Data>1.0.0.0</Data> 
  <Data>00000000</Data> 
  <Data>40000015</Data> 
  <Data>0000000000008dc5</Data> 
  <Data>47fc</Data> 
  <Data>01d4b919fdd00ceb</Data> 
  <Data>C:\Program Files\dotnet\dotnet.exe</Data> 
  <Data>C:\Users\lg\.nuget\packages\mod_spatialite\4.3.0.1\runtimes\win-x64\native\libwinpthread-1.dll</Data> 
  <Data>75462f9e-1755-45f5-af3a-573b3b52a2f5</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

### Steps to reproduce

```c#
        public static void Configure(DbContextOptionsBuilder<DbContext> builder, DbConnection connection)
        {
            builder.UseSqlite(connection, b =>
            {
                b.UseNetTopologySuite();
            });
        }
    }

### Further technical details
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite" Version="2.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.2.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.1" />
  </ItemGroup>
Operating system: Windows 10(1803)  17134.472、Server2008R2
IDE: (e.g. Visual Studio 2017 15.9.5)

**Comment by flyfire-cn** [comment] 2019-01-31 07:02
The ABP project template I used (.netcore)

https://aspnetboilerplate.com

Sqlite is integrated as follows

https://aspnetboilerplate.com/Pages/Documents/EF-Core-Sqlite-Integration

It's working fine.

Click on this article

https://docs.microsoft.com/zh-cn/ef/core/modeling/spatial

Installation of the

Microsoft. EntityFrameworkCore. Sqlite

Microsoft.EntityFrameworkCore.Sqlite.Net TopologySuite

Public static void Configure(DbContextOptionsBuilder builder, DbConnection connection)

{

Builder. UseSqlite (connection, b = >

{

B.U seNetTopologySuite ();

});

}

Run the project, 30 minutes or so, crash.

**Comment by ajcvickers** [comment] 2019-01-31 23:31
@flyfire-cn Can you please post a small, runnable, project/solution that demonstrates this crash so that we can investigate.

**Comment by flyfire-cn** [comment] 2019-02-02 02:07
> 
> 
> @flyfire-cn Can you please post a small, runnable, project/solution that demonstrates this crash so that we can investigate.

I created a template project。
It works well in Linux (ubuntu16.04 for Arm64+.netcore2.2SDK + libsqlite3-mod-spatialite) environment.
Error in Windows x64 environment.

https://github.com/flyfire-cn/aspnet-core-abp-sqlite

**Comment by flyfire-cn** [comment] 2019-02-03 16:02
@ajcvickers 

And I found another problem.

Once again, this test project, if released as a framework dependency, will run successfully on my linux-arm64 system.

However, if released in a standalone fashion

Dotnet publish-r linux-arm64-c Release

Display the following error message, I do not know why.

--------------------------------------------------------------------------------------

Using username "root".
 _____     _                _ _       _____ _     _____ ____
|  ___| __(_) ___ _ __   __| | |_   _| ____| |   | ____/ ___|
| |_ | '__| |/ _ \ '_ \ / _` | | | | |  _| | |   |  _|| |
|  _|| |  | |  __/ | | | (_| | | |_| | |___| |___| |__| |___
|_|  |_|  |_|\___|_| |_|\__,_|_|\__, |_____|_____|_____\____|
                                |___/

Welcome to Ubuntu core 16.04 LTS 4.14.52
System load:   0.23             Up time:       2 min            Local users:   2                                                                                        
Memory usage:  9 % of 481Mb     IP:            192.168.1.128
CPU temp:      19°C
Usage of /:    20% of 15G

 * Documentation: http://wiki.friendlyarm.com/Ubuntu
 * Forum: http://www.friendlyarm.com/Forum/

Last login: Sun Feb  3 23:53:00 2019 from 192.168.1.8
root@NanoPi-NEO2:~# cd /home/pi/spatialite
root@NanoPi-NEO2:/home/pi/spatialite# cd publish
root@NanoPi-NEO2:/home/pi/spatialite/publish# ./flyfire.IMS.Web.Host
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Application startup exception: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Infrastructure.SpatialiteLoader.FindExtension()
   at Microsoft.EntityFrameworkCore.Infrastructure.SpatialiteLoader.Load(DbConnection connection)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.LoadSpatialite()
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at flyfire.IMS.EntityFrameworkCore.Seed.Host.DefaultEditionCreator.CreateEditions() in D:\codeManager\github.com\aspnet-core-abp-sqlite\src\flyfire.IMS.EntityFrameworkCore\EntityFrameworkCore\Seed\Host\DefaultEditionCreator.cs:line 25
   at flyfire.IMS.EntityFrameworkCore.Seed.Host.InitialHostDbBuilder.Create() in D:\codeManager\github.com\aspnet-core-abp-sqlite\src\flyfire.IMS.EntityFrameworkCore\EntityFrameworkCore\Seed\Host\InitialHostDbBuilder.cs:line 14
   at flyfire.IMS.EntityFrameworkCore.Seed.SeedHelper.SeedHostDb(IMSDbContext context) in D:\codeManager\github.com\aspnet-core-abp-sqlite\src\flyfire.IMS.EntityFrameworkCore\EntityFrameworkCore\Seed\SeedHelper.cs:line 25
   at flyfire.IMS.EntityFrameworkCore.Seed.SeedHelper.WithDbContext[TDbContext](IIocResolver iocResolver, Action`1 contextAction) in D:\codeManager\github.com\aspnet-core-abp-sqlite\src\flyfire.IMS.EntityFrameworkCore\EntityFrameworkCore\Seed\SeedHelper.cs:line 41
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Abp.AbpBootstrapper.Initialize()
   at Abp.AspNetCore.AbpApplicationBuilderExtensions.InitializeAbp(IApplicationBuilder app)
   at Abp.AspNetCore.AbpApplicationBuilderExtensions.UseAbp(IApplicationBuilder app, Action`1 optionsAction)
   at flyfire.IMS.Web.Host.Startup.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in D:\codeManager\github.com\aspnet-core-abp-sqlite\src\flyfire.IMS.Web.Host\Startup\Startup.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Infrastructure.SpatialiteLoader.FindExtension()
   at Microsoft.EntityFrameworkCore.Infrastructure.SpatialiteLoader.Load(DbConnection connection)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.LoadSpatialite()
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at flyfire.IMS.EntityFrameworkCore.Seed.Host.DefaultEditionCreator.CreateEditions() in D:\codeManager\github.com\aspnet-core-abp-sqlite\src\flyfire.IMS.EntityFrameworkCore\EntityFrameworkCore\Seed\Host\DefaultEditionCreator.cs:line 25
   at flyfire.IMS.EntityFrameworkCore.Seed.Host.InitialHostDbBuilder.Create() in D:\codeManager\github.com\aspnet-core-abp-sqlite\src\flyfire.IMS.EntityFrameworkCore\EntityFrameworkCore\Seed\Host\InitialHostDbBuilder.cs:line 14
   at flyfire.IMS.EntityFrameworkCore.Seed.SeedHelper.SeedHostDb(IMSDbContext context) in D:\codeManager\github.com\aspnet-core-abp-sqlite\src\flyfire.IMS.EntityFrameworkCore\EntityFrameworkCore\Seed\SeedHelper.cs:line 25
   at flyfire.IMS.EntityFrameworkCore.Seed.SeedHelper.WithDbContext[TDbContext](IIocResolver iocResolver, Action`1 contextAction) in D:\codeManager\github.com\aspnet-core-abp-sqlite\src\flyfire.IMS.EntityFrameworkCore\EntityFrameworkCore\Seed\SeedHelper.cs:line 41
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Abp.AbpBootstrapper.Initialize()
   at Abp.AspNetCore.AbpApplicationBuilderExtensions.InitializeAbp(IApplicationBuilder app)
   at Abp.AspNetCore.AbpApplicationBuilderExtensions.UseAbp(IApplicationBuilder app, Action`1 optionsAction)
   at flyfire.IMS.Web.Host.Startup.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in D:\codeManager\github.com\aspnet-core-abp-sqlite\src\flyfire.IMS.Web.Host\Startup\Startup.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by ajcvickers** [comment] 2019-02-11 19:43
@flyfire-cn I downloaded and built the test app, but I haven'e been able to induce it to crash. Can you provide any more specific instructions for reproducing the crash?

**Comment by flyfire-cn** [comment] 2019-02-13 02:40
publish this app is test run.
it is crash.
@ajcvickers

**Comment by ajcvickers** [comment] 2019-02-19 19:03
@flyfire-cn Sorry, but I can't get this to crash. Would it be possible for you to try to isolate the problem a bit more? Attempting to debug an entire application is a bit more than I have the resources for.

**Comment by flyfire-cn** [comment] 2019-02-20 03:18
> 
> 
> @flyfire-cn Sorry, but I can't get this to crash. Would it be possible for you to try to isolate the problem a bit more? Attempting to debug an entire application is a bit more than I have the resources for.

I added two release processing files to the solution
publish_win-x64.bat
publish_linux-arm64.bat
They are under the flyfire.ims.web.host project
Run them to generate the corresponding publish file (you need to set flyfire.ims.web.host as the startup project)
Run run.bat(win) or run.sh(Linux) in the distribution folder
The exception.

Run the project directly under VS2017. It will take a long time for the exception to occur.About 30 minutes.

**Comment by ajcvickers** [comment] 2019-02-21 18:28
@flyfire-cn I managed to run the project and left it running for some time. It did not crash for me.

**Comment by staneee** [comment] 2019-02-23 10:22
> @flyfire-cn I managed to run the project and left it running for some time. It did not crash for me.

dotnet core sdk version:  2.2.101

system : windows 10 pro  1803/17134.590

---

I reproduce the problem，the problem he said exists, and the steps to reproduce it are as follows:

* Download the [source code](https://github.com/flyfire-cn/aspnet-core-abp-sqlite).
* Open powershell or CMD and switch to the flyfire.ims.web.host directory of the source code.
* run the command `dotnet publish-c release-r win-x64-o publish` .
* run the command `cd publish `
* run the command  `.\flyfire.IMS.Web.Host.exe`.


Follow these steps and problems will appear.

**Comment by flyfire-cn** [comment] 2019-02-23 10:30
> I reproduce the problem，the problem he said exists, and the steps to reproduce it are as follows:

My operating environment:
Dotnet core SDK version: 2.2.103

**Comment by flyfire-cn** [comment] 2019-03-03 11:50
@ajcvickers 
Has there been any progress on this issue recently?

**Comment by ajcvickers** [comment] 2019-03-04 17:31
@flyfire-cn I will investigate again when I get time. I'm not considering a high priority right now since I have tried and failed to reproduce this issue multiple times, and the repro code is a long way from minimal.

**Comment by faryu** [comment] 2019-03-11 14:02
I also had the same issue, with the program crashing after using the spatialite database for a while.
If I didn't access it at all the program kept running, but as soon as I read from it constantly it crashes within a minute without any read debug information or helpful exceptions.

I already used spatialite before it was supported by the EntityFramework and I found a workaround which lets me use the EF Core support, but still use my previous spatialite binaries. I have no idea why my workaround even works, but you know: Never touch a running system! ;)

So my workaround to use my previous working spatialite dll is the following:

```cs
public static void UseSpatialite(this DbContextOptionsBuilder optionsBuilder, string connectionString)
{
	var connection = new SqliteConnection(connectionString);
	UseSpatialite(optionsBuilder, connection);
}

public static void UseSpatialite(this DbContextOptionsBuilder optionsBuilder, DbConnection connection)
{
	void OnStateChanged(object sender, StateChangeEventArgs e)
	{
		if (e.CurrentState != ConnectionState.Open)
			return;

		if (sender is SqliteConnection senderConnection)
		{
			senderConnection.EnableExtensions(true);
			using (var command = senderConnection.CreateCommand())
			{
				command.CommandText = "SELECT load_extension('mod_spatialite')";
				command.ExecuteNonQuery();
			}
			senderConnection.EnableExtensions(false);
		}
	}

	connection.StateChange += OnStateChanged;

	optionsBuilder.UseSqlite(connection, opts => opts.UseNetTopologySuite());
}
```

So I just give the EntityFramework a DbConnection and handle connecting to the db myself.
By the way, this is also how I used Spatialite before EF Core 2.2.

I spend quite some time until I managed to get working spatialite binaries for windows. So in case someone want's to try them too, here they are: [Spatialite.zip](https://github.com/aspnet/EntityFrameworkCore/files/2952500/Spatialite.zip)

**Comment by ajcvickers** [comment] 2019-11-14 23:20
@faryu 

> I found a workaround which lets me use the EF Core support, but still use my previous spatialite binaries.

So you haven't seen this crash when using the older binaries with EF Core? Which version are the older binaries?

**Comment by faryu** [comment] 2019-11-15 07:50
I'm using mod_spatialite-4.3.0a.
I don't remember what exactly I did to resolve my dll issues back then, but I know that [this](http://blog.jrg.com.br/2016/04/25/Fixing-spatialite-loading-problem/) post solved it for me.

I used a already build binary of the mod_spatialite dll with it's dependencies (build at 18.01.2018) and then I replaced the libstdc++_64-6.dll file (the hint being from the linked post) with the dll from mingw64 (version x86_64-8.1.0-release-win32-seh-rt_v6-rev0).

I never had a problem caused by the database since then.

**Comment by clarkgranum** [comment] 2019-11-15 23:46
I have the same issue. For me, dotnet crashes when the processes's memory builds up. The memory build up seems to be caused by yet to be garbage collected objects that were returned from spatial queries. Looking in the task manager, dotnet starts at about 170MB and I can get it crash every time when the memory goes up to around 230MB.

I am using EF 2.2.0 and my application is running on Windows 10.

This is the log from the Event Viewer:

Faulting application name: dotnet.exe, version: 3.0.19.46305, time stamp: 0x5d7bb03a
Faulting module name: libwinpthread-1.dll, version: 1.0.0.0, time stamp: 0x00000000
Exception code: 0x40000015
Fault offset: 0x0000000000008dc5
Faulting process id: 0x51c8
Faulting application start time: 0x01d59c07d9fa5a1c
Faulting application path: C:\Program Files\dotnet\dotnet.exe
Faulting module path: C:\Users\{app path}\libwinpthread-1.dll
Report Id: f3c36362-76e4-4bde-9f34-80e88553af8f
Faulting package full name: 
Faulting package-relative application ID: 

Unfortunately I don't have much more information.

**Comment by bricelam** [comment] 2020-01-14 18:25
The "Sequence contains no matching element" error in self-contained deployments was fix in EF Core 3.1 (issue #14093)

**Comment by bricelam** [comment] 2020-01-14 19:03
I've taken a new build of SpatiaLite. Can anyone confirm whether the memory leak and crash are fixed? (add the following to your *.csproj file)

``` xml
<ItemGroup>
  <PackageReference Include="mod_spatialite" Version="4.3.0.100-rc1" />
</ItemGroup>
```

**Comment by clarkgranum** [comment] 2020-01-15 22:40
Unfortunately, the program still crashes and I get the same error with mod_spatialite 4.3.0.100-rc1:

Faulting application name: dotnet.exe, version: 3.0.19.46305, time stamp: 0x5d7bb03a
Faulting module name: libwinpthread-1.dll, version: 1.0.0.0, time stamp: 0x00000000
Exception code: 0x40000015
Fault offset: 0x0000000000008e85
Faulting process id: 0x2510
Faulting application start time: 0x01d5cbf0cdfb894c
Faulting application path: C:\Program Files\dotnet\dotnet.exe
Faulting module path: C:\Users\{appPath}\libwinpthread-1.dll
Report Id: 84ac7ff9-f786-4144-849e-a82e28322f41
Faulting package full name: 
Faulting package-relative application ID:

**Comment by ajcvickers** [comment] 2020-01-17 19:31
Note from team discussion: we are closing this issue because we have repeatedly not been able to reproduce it. We would be happy to reopen and investigate more if we can get a project that reproduces this behavior.

**Comment by clarkgranum** [comment] 2020-01-17 23:32
> Note from team discussion: we are closing this issue because we have repeatedly not been able to reproduce it. We would be happy to reopen and investigate more if we can get a project that reproduces this behavior.

Can you try this project?

https://github.com/clarkgranum/ef_core_sqlite_crash

**Comment by ajcvickers** [comment] 2020-02-03 18:56
@clarkgranum Did you reference the new build in your project? If so, can you point to where?

**Comment by clarkgranum** [comment] 2020-02-03 18:59
> @clarkgranum Did you reference the new build in your project? If so, can you point to where?

The new build of mod_spatialite (4.3.0.100-rc1)? I did not reference this in the linked project, but I can try again. I did try this new build in a different project and it still crashed for me.

**Comment by ajcvickers** [comment] 2020-02-14 17:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by clarkgranum** [comment] 2020-02-14 18:49
> **EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.
> 
> _BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions._

Can you please re-open this issue? I am able to trigger a crash within a minute after starting an asp.net core app by repeating a very simple query. I have new code below, which includes the reference to the updated mod_spatialite build. I realized the previous repository I referenced did not load properly in Visual Studio when cloned. Just clone the repository below and start the application from Visual studio (no other setup should be required):

https://github.com/clarkgranum/ef_core_spatialite_issue_14561

**Comment by ajcvickers** [comment] 2020-02-24 21:41
@bricelam I am able to reproduce this. I get a hard crash after about 157 iterations, with exit code 3. When run in the debugger it crashes the entire process. I don't get stack traces or other information. 

The crash goes away if I remove the call to `UseNetTopologySuite` but make no other changes.

**Comment by clarkgranum** [comment] 2020-02-24 21:52
> @bricelam I am able to reproduce this. I get a hard crash after about 157 iterations, with exit code 3. When run in the debugger it crashes the entire process. I don't get stack traces or other information.
> 
> The crash goes away if I remove the call to `UseNetTopologySuite` but make no other changes.

I get the same exact results, except for the number of iterations it takes to crash the program (usually 100-150 for me). Thank you for looking into this.

**Comment by bricelam** [comment] 2020-02-24 23:14
Ouch, sounds like we need to do some native debugging to understand where the problem is. Possibilities:
* An issue with managed-native marshalling (e.g. freeing memory too soon or holding onto it too long)
* Something in e_sqlite3 (SQLitePCLRaw) that's incompatible with SpatiaLite
* Something in SpatiaLite that repros without .NET or e_sqlite3

**Comment by d79ima** [comment] 2021-06-21 19:43
I can reproduce this same exact issue easily. Attached a simple tiny sample that reproduces the killing of app after 530'ish SQLite reads. Could you please take a look at it one more time. Really need a fix. 
[TestNetTopologySuite.zip](https://github.com/dotnet/efcore/files/6689102/TestNetTopologySuite.zip)
attempts.

**Comment by d79ima** [comment] 2021-06-24 13:03
@AndriySvyryd are you able to reproduce this crash on your end?

**Comment by AndriySvyryd** [comment] 2021-06-24 17:41
Yes, we can reproduce it, but it's not clear yet whether this is something we can fix.

**Comment by d79ima** [comment] 2021-06-24 17:45
Are there any good suggestions for workaround while you are looking for a fix?

**Comment by kvpt** [comment] 2021-12-03 12:59
> I've taken a new build of SpatiaLite. Can anyone confirm whether the memory leak and crash are fixed? (add the following to your *.csproj file)
> 
> ```
> <ItemGroup>
>   <PackageReference Include="mod_spatialite" Version="4.3.0.100-rc1" />
> </ItemGroup>
> ```

Just ran into the problem myself, upgraded the mod_spatialite package to this version fixed the problem for me. No more crash.

**Comment by d79ima** [comment] 2021-12-06 14:52
i tried adding the above package reference <PackageReference Include="mod_spatialite" Version="4.3.0.100-rc1" /> but it still crashes for me, just takes a bit longer than before

**Comment by kabuchanga** [comment] 2022-10-22 16:20
> > I've taken a new build of SpatiaLite. Can anyone confirm whether the memory leak and crash are fixed? (add the following to your *.csproj file)
> > ```
> > <ItemGroup>
> >   <PackageReference Include="mod_spatialite" Version="4.3.0.100-rc1" />
> > </ItemGroup>
> > ```
> 
> Just ran into the problem myself, upgraded the **mod_spatialite** package to this version fixed the problem for me. No more crash.

I test tested the PackageReference and it worked for me. Thank you for putting it together

**Comment by d79ima** [comment] 2022-10-24 13:28
@kabuchanga can you try my sample app to see if it crashes for you. I added 
```
<ItemGroup>
  <PackageReference Include="mod_spatialite" Version="4.3.0.100-rc1" />
</ItemGroup>
```
to my sample app. So now instead of crashing at around 530 iterations it crashes at around 1060 iterations.
[TestNetTopologySuite.zip](https://github.com/dotnet/efcore/files/9852001/TestNetTopologySuite.zip)

**Comment by kvpt** [comment] 2022-10-24 13:44
@d79ima I tested your sample, and reproduce the crash around 1060 too.
But for me this reproduction is missing the dispose on the connection, if you add a dispose after the close the crash doesn't happen anymore. 
I think an explicit dispose is needed here because of the native code nature of the mod_spatialite library.
So if you manually handle connections you will have to ensure that they are disposed or implement some sort of pool mecanism to reuse them.

**Comment by ajcvickers** [comment] 2023-12-08 14:22
No longer repros with 8.0 and latest Spatialite:

```xml
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite" Version="8.0.0" />
    <PackageReference Include="mod_spatialite" Version="4.3.0.1" />
```

<img width="138" alt="image" src="https://github.com/dotnet/efcore/assets/1430078/515c5668-e127-4692-b8ac-6723b7cd07ed">

**Closed by ajcvickers** 2023-12-08 14:22 UTC
Labels: type-bug, customer-reported, area-spatial, punted-for-5.0, punted-for-6.0

**Comment by d79ima** [comment] 2023-12-09 22:34
downloaded .net 8 sdk and updated the above sample app TestNetTopologySuite.zip to target .net 8 and NetTopologySuite 8.0.0.
Now as it runs i start seeing a new error: "Error too many connections max 64", and the application still crashes out at around 640 databases created.

**Comment by ajcvickers** [comment] 2023-12-10 11:12
@d79ima That crash being tracked by this issue no longer occurs with the repro code provided. If there is a different problem, then I think that would better be tracked by a new issue with a complete repro for the new problem.
