### ISSUE TITLE
flags enum property where clause not affect on sql query

### ISSUE THREAD

**Issue by MohammadAkbari** [dotnet/efcore#5823] opened 2016-06-21 07:17 UTC
For assign mutiple type to user, I use UserType enum that decorate with Flags attribute as fallow:

```
[Flags]
public enum UserType
{
    Default = 0,
    Moderator = 1,
    Doctor = 2,
    Administrator = 4,
}
public class User : IdentityUser
{
    public bool Suspended { get; set; }
    public bool Deleted { get; set; }
    public UserType UserType { get; set; }
}
```

And assign userType to user,

```
user.UserType = UserType.Moderator | UserType.Administrator;
```

when below query runs, 

```
var t = dbContext.Users.Where(e => e.UserType.HasFlag(UserType.Doctor)).ToList();
```

This sql query generate, as can be seen there is no trace of where expression in query. However, ef query result is ok, but the problem is that all User load to memroy and no filter occur in database, indeed query occur in memory

```
SELECT [e].[Id], [e].[PasswordHash], [e].[PhoneNumber], [e].[PhoneNumberConfirmed]
, [e].[SecurityStamp], [e].[Suspended], [e].[TwoFactorEnabled],[e].[UserName], [e].[UserType]
FROM [AspNetUsers] AS [e]
```

this problem not exists in ef 6.

**Comment by rowanmiller** [comment] 2016-06-21 18:31
@smitpatel did you already add bitwise support?

**Comment by smitpatel** [comment] 2016-06-21 18:47
Support for bitwise operations is already in. Though the where clause is not generated here due to `Enum.HasFlag` is not implemented yet. dupe of #5576

**Comment by rowanmiller** [comment] 2016-06-21 19:04
Thanks

**Closed** 2022-10-16 09:46 UTC
