### ISSUE TITLE
Query: DefaultIfEmpty for CLR DateTime which is SQL datetime returns SQL datetime2 default value

### ISSUE THREAD

**Issue by mczar** [dotnet/efcore#26037] opened 2021-09-15 07:02 UTC
```C#
.Select(x => x.Date).DefaultIfEmpty()
```

`DefaultIfEmpty()` for CLR `DateTime` (in `DbContext` defined as SQL `datetime`) uses SQL `datetime2` default value (which is 0001/01/01) instead of SQL `datetime` default value (which is 1753/01/01 and minimum accepted value of this type). And such situation can generate following SQL query:

```SQL
COALESCE([table].[Date], '0001-01-01T00:00:00.0000000')
```

Which, if `Date` is `datetime`, not `datetime2`, can lead to following error:

```
 Microsoft.Data.SqlClient.SqlException (0x80131904): The conversion of a varchar data type to a datetime data type resulted in an out-of-range value.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.Read()
```

**Comment by ajcvickers** [comment] 2021-09-17 16:02
@mczar Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2021-09-28 11:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:08 UTC
Labels: closed-could-not-reproduce, customer-reported
