### ISSUE TITLE
Nullable enum property type: Add-Migration creates same migration repeatedly

### ISSUE THREAD

**Issue by wmkew** [dotnet/efcore#11697] opened 2018-04-16 18:19 UTC
I create a new model class that contains a property whose data type is a nullable enum.  Adding a migration creates a table for the class and a column for the property as expected.  However, adding another migration creates code in which the property's column is altered, and this happens repeatedly for subsequent migrations.

### Steps to reproduce
**Model:**
```c#
using System;
namespace MyNamespace
{
   public partial class TestClass
   {
      public int Id { get; set; }
      public DayOfWeek? Day { get; set; }
   }
}
```
**Context:**
```c#
modelBuilder.Entity<TestClass>(entity =>
{
   entity.HasKey(e => e.Id);
   entity.Property(e => e.Day);
});
```
Run `Add-Migration NullableEnumTest1`, and note the expected table creation for `TestClass`:
```c#
protected override void Up(MigrationBuilder migrationBuilder)
{
   migrationBuilder.CreateTable(
         name: "TestClass",
         columns: table => new
         {
            Id = table.Column<int>(nullable: false)
               .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
            Day = table.Column<int>(nullable: true)
         },
         constraints: table =>
         {
            table.PrimaryKey("PK_TestClass", x => x.Id);
         });
}

protected override void Down(MigrationBuilder migrationBuilder)
{
   migrationBuilder.DropTable(
         name: "TestClass");
}
```
But now run `Add-Migration NullableEnumTest2`.  Note that a new migration gets created, which is unexpected, and this will happen repeatedly for subsequent migrations:
```c#
protected override void Up(MigrationBuilder migrationBuilder)
{
   migrationBuilder.AlterColumn<int>(
         name: "Day",
         table: "TestClass",
         nullable: true,
         oldClrType: typeof(int));
}

protected override void Down(MigrationBuilder migrationBuilder)
{
   migrationBuilder.AlterColumn<int>(
         name: "Day",
         table: "TestClass",
         nullable: false,
         oldClrType: typeof(int),
         oldNullable: true);
}
```

### Further technical details
EF Core version: 2.1.0-preview2-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 2.1.0-preview2-final
Operating system: Windows 10
IDE: Visual Studio 2017 15.6.6

**Comment by ajcvickers** [comment] 2018-04-18 20:55
Duplicate of #11297

Fixed in [the nightly builds](https://dotnet.myget.org/gallery/aspnetcore-dev)

**Closed** 2022-10-16 12:19 UTC
Labels: closed-duplicate
