### ISSUE TITLE
context.Update sets IsLoaded to false

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#20022] opened 2020-02-21 19:33 UTC
@lajones to provide details

**Comment by lajones** [comment] 2020-02-28 00:48
The problem was that at some stage during test debugging we were seeing [this line](https://github.com/dotnet/efcore/blob/master/test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs#L726) make `context.Entry(owner).Reference(o => o.Address).IsLoaded` change from true to false. But I'm no longer seeing that - so closing.

**Comment by ajcvickers** [comment] 2020-02-28 15:54
@lajones FYI Issues that can't be reproduced don't get a type label and should be closed with no milestone.

**Closed** 2022-10-16 18:12 UTC
Labels: closed-could-not-reproduce
