### ISSUE TITLE
Is there or will there be support for creating index on function column 

### ISSUE THREAD

**Issue by CamusGao** [dotnet/efcore#31418] opened 2023-08-06 11:10 UTC
On some databases, I can create an index `idx_xxx` using sql below.
```sql
create index idx_xxx on xxx(lower(a));
```
And when I perform a query like
```sql
select  * from idx_xxx where lower(a) = 'abc';
```
the index will be used.
Is there or will there be suppport for creating index on function column?

**Comment by roji** [comment] 2023-08-06 11:18
Duplicate of #28360

**Comment by roji** [comment] 2023-08-06 11:20
See https://github.com/dotnet/efcore/issues/28360#issuecomment-1666821461 for some notes on how to do this yourself.

**Closed** 2023-08-06 11:23 UTC
Labels: closed-duplicate, customer-reported

**Comment by hexxone** [comment] 2024-06-19 08:46
For anyone coming across the same problem, please take a second and vote for the issue mentioned by roji above, so that Microsoft will prioitize it for implementation.
