### ISSUE TITLE
Order By in raw sql query doesn't sort items

### ISSUE THREAD

**Issue by manospasj** [dotnet/efcore#7034] opened 2016-11-17 12:35 UTC
I have the following entity and want to use raw sql to get all the entities from database order by MyDate
```
public class MyModel {
    public DateTime MyDate { get; set; }
}
```
Below is my code
```
string sql = @"
    SELECT *
        FROM dbo.MyModel
        ORDER BY MyDate desc
        OFFSET 0 ROWS
        FETCH NEXT 10 ROWS ONLY;";

List<MyModel> models = context.MyModel.FromSql(sql).ToList();
```
The problem is that the list is not sorted by MyDate as expected.
I then tried to execute the same query directly in my Database and it returns the results sorted.

The sorting seems to work fine for other property types

**Comment by smitpatel** [comment] 2016-11-21 23:05
@manospasj - Which version of EF are you using? This works fine in 1.1.0 release.

**Comment by manospasj** [comment] 2016-11-22 08:23
@smitpatel I use EntityFrameworkCore version 1.0.1 with Sql Server.
I also get some other errors on 1.1.0, so updating to the latest release is not an option right now.

**Comment by smitpatel** [comment] 2016-11-30 20:01
This works fine in 1.0.1 release too.

**Comment by smitpatel** [comment] 2016-11-30 20:03
Closing this as unable to reproduce.

If you are still seeing issue, please provide full repro code which demonstrate the behavior and we'll re-activate the issue.

**Comment by manospasj** [comment] 2017-04-20 12:14
I finally found the root cause of this and it happens also in 1.1.1.

Let's say I have an entity named 'Customer' and an entity named 'Invoice' with a one to many relationship between these two.

Now if I want to query the Invoices using raw sql but also include the Customer entity the produced sql query is not correct.

My code looks like this:
```
context.Invoices.Include(i => i.Customer)
    .FromSql("SELECT a.* FROM dbo.Invoices AS a ORDER BY StartDate").ToList();
```

The sql query that gets executed is this:
```
SELECT [i].[Id], [i].[CustomerId], [i].[StartDate], [c].[Id]
FROM (
    SELECT a.* FROM dbo.Invoices AS a ORDER BY StartDate
) as [I]
INNER JOIN [Customers] AS [c] ON [i].[CustomerId] = [c].[Id]
ORDER BY [i].[Id]
```

Since I have declared an ORDER BY inside my raw sql I think that the `ORDER BY [i].[Id]` should be missing.

**Comment by divega** [comment] 2017-05-08 18:25
@manospasj the raw SQL query passed to the `FromSql()` method is by-design mostly opaque to EF Core. That means in this case that EF Core won't try to interpret the SQL to obtain details such as the present ORDER BY clause. 

Also, when you apply any other query operators to the `FromSql()` query EF Core will push the raw SQL down to become the derived table (i.e. a subquery in the FROM clause) for another SELECT. This is done to enable composability of queries initiated with `FromSql()` using LINQ. 

In your case you are using the `Include()` operator, which applies to the whole query independently of the place where you call it. The implementation of the `Include()` operator by-design requires introducing an ORDER BY clause, and as per the first paragraph, EF Core has now way to know that the derived table already was sorted, hence it won't do anything to preserve that order. 

On another note, I believe the simplified query in your last comment won't work for a different reason: at least on SQL Server, derived tables cannot be sorted unless they also have a TOP or OFFSET/FETCH clause. The best workaround for this is to add `TOP (100) PERCENT` to the raw query.

**Comment by divega** [comment] 2017-05-08 18:52
Reopening because @smitpatel will double-check that `Include()` to a reference works as we expected and does not introduce an ORDER BY clause.

**Comment by smitpatel** [comment] 2017-05-08 19:03
@manospasj wrote:
> Let's say I have an entity named 'Customer' and an entity named 'Invoice' with a one to many relationship between these two.

Collection navigation. By design.

**Comment by anpete** [comment] 2017-05-08 21:11
@smitpatel It depends which end is being included. Including the Customer when querying Invoices (as per the example above) is a reference Include, and hence we shouldn't be seeing an OrderBy here. 

@manospasj Please provider a more complete repro here, including entity types, context, OnModelCreating etc.

**Comment by manospasj** [comment] 2017-05-09 09:37
@divega You are right in your last paragraph. I had removed the OFFSET/FETCH from my example for clarity.

Trying to create a repro I found that this behavior changes depending on the includes that I use.

To better demonstrate my problem I have created 3 models.

**Customer.cs**
```
[Table("Customers")]
public partial class Customer {
	public Customer() {
		Invoices = new List<Invoice>();
	}

	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public int Id { get; set; }

	[InverseProperty("Customer")]
	public List<Invoice> Invoices { get; set; }
}
```

**Invoice.cs**
```
[Table("Invoices")]
public partial class Invoice {
	public Invoice() {
		InvoiceLines = new List<InvoiceLine>();
	}

	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public int Id { get; set; }

	public DateTime InvoiceDate { get; set; }

	public int CustomerId { get; set; }

	[ForeignKey("CustomerId")]
	public Customer Customer { get; set; }

	[InverseProperty("Invoice")]
	public List<InvoiceLine> InvoiceLines { get; set; }
}
```

**InvoiceLine.cs**
```
[Table("InvoiceLines")]
public partial class InvoiceLine {
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public int Id { get; set; }

	public string Item { get; set; }

	public int InvoiceId { get; set; }

	[ForeignKey("InvoiceId")]
	public Invoice Invoice { get; set; }
}
```

My DbContext  isn't something special.
**MyDbContext.cs**
```
public class MyDbContext : DbContext {
	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
		optionsBuilder.UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=Issue7034;Trusted_Connection=True;MultipleActiveResultSets=true");
	}

	public virtual DbSet<Customer> Customers { get; set; }

	public virtual DbSet<Invoice> Invoices { get; set; }
}
```

Now If want to execute the following sql
```
SELECT * FROM Invoices ORDER BY InvoiceDate ASC OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
```

including only the customers the ordering is correct
```
List<Invoice> invoices = context.Invoices.Include(i => i.Customer).FromSql(sql).ToList();
```

But if I also include the invoice lines the ordering is wrong
```
List<Invoice> invoices = context.Invoices.Include(i => i.Customer).Include(i => i.InvoiceLines).FromSql(sql).ToList();
```

The same happens if I include only the invoice lines without customers
```
List<Invoice> invoices = context.Invoices.Include(i => i.InvoiceLines).FromSql(sql).ToList();
```

I have attached a sample project to help you reproduce the issue.
[EntityFrameworkIssue7034.zip](https://github.com/aspnet/EntityFramework/files/986153/EntityFrameworkIssue7034.zip)

**Comment by smitpatel** [comment] 2017-05-09 18:15
Ordering is only introduced for collection navigations & not for reference navigation.
This is working as expected.

**Comment by divega** [comment] 2017-05-10 01:25
Thanks @manospasj for the additional information @smitpatel for verifying. 
I am ok with closing as by-design then. @manospasj the explanation in https://github.com/aspnet/EntityFramework/issues/7034#issuecomment-299949842 still applies.

cc @anpete @ajcvickers

**Closed** 2022-10-16 10:42 UTC
Labels: closed-by-design
