### ISSUE TITLE
OwnedType use HasData() throw a InvalidOperationException

### ISSUE THREAD

**Issue by jerviscui** [dotnet/efcore#25586] opened 2021-08-19 05:44 UTC
## File a bug

When I use `HasData()` method for a OwnedType, I get a `InvalidOperationException`:

> To seed relationships, add the entity seed to 'StreetAddress' and specify the foreign key values {'OrderId'}.

But, the 'StreetAddress' is not a Navigation  Property.

### Include your code

The entities:

```csharp
public class Order
{
    protected Order()
    {
    }

    public Order(long id, string buyer, string street, string city)
    {
        Id = id;
        Buyer = buyer;
        StreetAddress = new StreetAddress(street, city);
    }

    public long Id { get; protected set; }

    public string Buyer { get; protected set; }

    public StreetAddress StreetAddress { get; protected set; }
}

public class StreetAddress
{
    protected StreetAddress()
    {
    }

    public StreetAddress(string street, string city)
    {
        Street = street;
        City = city;
    }

    [StringLength(200)]
    public string Street { get; protected set; }

    [StringLength(200)]
    public string City { get; protected set; }
}
```

The test DbContext:

```csharp
public class TestDbContext : DbContext
{
    public TestDbContext(DbContextOptions<TestDbContext> options) : base(options)
    {
    }
    
    public DbSet<Order> Orders { get; set; } = null!;

    /// <inheritdoc />
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var order = modelBuilder.Entity<Order>();
        order.HasKey(o => o.Id);
        order.Property(o => o.Id).ValueGeneratedNever();
        order.OwnsOne(o => o.StreetAddress, builder =>
        {
            builder.HasIndex(o => o.City);
            builder.HasIndex(o => o.Street);
        });

        CreateSeed(modelBuilder);
    }

    private static void CreateSeed(ModelBuilder modelBuilder)
    {
        var order = new Order(1, "buyer", "street", "city");
        modelBuilder.Entity<Order>().HasData(order);
    }
}
```

### Include stack traces

```
Unhandled exception. System.InvalidOperationException: The seed entity for entity type 'Order' with the key value 'Id:1' cannot be added because it has the navigation 'StreetAddress' set. To seed relationships, add the entity seed to 'StreetAddress' and specify the foreign key values {'OrderId'}.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateData(IModel model, IDiagnosticsLogger`1 logger)
```

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment] 2021-08-20 10:37
@jerviscui `StreetAddress` is a navigation property because it navigates from the `Order` entity to the `StreetAddress` owned entity. Making an entity type owned does not change that it is still an entity type, which is why owned types are not good candidates to use as value objects--see #9906.

Closing this as a duplicate of #10000.

**Closed** 2022-10-16 19:43 UTC
Labels: customer-reported
