### ISSUE TITLE
EF Core produces different databases across variying SQLServer installations

### ISSUE THREAD

**Issue by Ruhrpottpatriot** [dotnet/efcore#10593] opened 2017-12-19 20:16 UTC
I got one instance of  SQLServer 2017 installed on my windows machine and one installed via Docker on my OSX machine. Between these two instances EFCore produces two different database tables, even though the configuration is the same.

The code to configure the database is the following:
 
  ```
        public void Configure(EntityTypeBuilder<Character> builder)
        {
            builder.ToTable("Characters");

            builder.Property(c => c.Name)
                   .IsRequired();

            builder.Property(c => c.Name)
                   .HasField("name");

            builder.HasOne(p => p.Map)
                   .WithMany()
                   .HasForeignKey(p => p.MapId);

            builder.HasKey(c => c.Name);
            builder.OwnsOne(c => c.Rotation)
                .OnDelete(DeleteBehavior.Cascade);
            builder.OwnsOne(c => c.Location)
                .OnDelete(DeleteBehavior.Cascade);
        }

        public void Configure(EntityTypeBuilder<Map> builder)
        {
            builder.ToTable("Maps");

            builder.HasKey(p => p.Name);
        }
```
The accompanying model looks like this:
```
   public class Character : IEquatable<Character>
    {
        // Remainder left out for bervity

        public string MapId { get; set; }

        public virtual Map Map { get; set; }
    }

    public class Map : IEquatable<Map>
    {
        public string Name { get; set; }

        public IEnumerable<Character> Characters { get; set; }
    }
```

The problematic property in my case are `Map` and `MapId`. As you can see I configured the `MapId` property to be the ForeignKey and the `Characters` property to be the inverse porperty on the Map object. Yet EFCore creates a ForeignKey called `MapName` and a ForeignKey called `MapId`, but only on my Windows instance of SQLServer.
The CREATE TABLE queries look like this:
```
/** Windows */
USE [GameObjects]
GO

/****** Object:  Table [dbo].[Characters]    Script Date: 19.12.2017 21:09:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Characters](
	[Name] [nvarchar](450) NOT NULL,
	[Class] [int] NOT NULL,
	[Group] [uniqueidentifier] NOT NULL,
	[Level] [int] NOT NULL,
	[MapId] [nvarchar](450) NULL,
	[MapName] [nvarchar](450) NULL,
	[OwnerId] [uniqueidentifier] NOT NULL,
	[Location_X] [real] NOT NULL,
	[Location_Y] [real] NOT NULL,
	[Location_Z] [real] NOT NULL,
	[Rotation_Pitch] [real] NOT NULL,
	[Rotation_Roll] [real] NOT NULL,
	[Rotation_Yaw] [real] NOT NULL,
 CONSTRAINT [PK_Characters] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Characters]  WITH CHECK ADD  CONSTRAINT [FK_Characters_Maps_MapId] FOREIGN KEY([MapId])
REFERENCES [dbo].[Maps] ([Name])
GO

ALTER TABLE [dbo].[Characters] CHECK CONSTRAINT [FK_Characters_Maps_MapId]
GO

ALTER TABLE [dbo].[Characters]  WITH CHECK ADD  CONSTRAINT [FK_Characters_Maps_MapName] FOREIGN KEY([MapName])
REFERENCES [dbo].[Maps] ([Name])
GO

ALTER TABLE [dbo].[Characters] CHECK CONSTRAINT [FK_Characters_Maps_MapName]
GO

/** OSX */
USE [GameObjects]
GO

/****** Object:  Table [dbo].[Characters]    Script Date: 19.12.2017 21:10:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Characters](
	[Name] [nvarchar](450) NOT NULL,
	[Class] [int] NOT NULL,
	[Level] [int] NOT NULL,
	[OwnerId] [uniqueidentifier] NOT NULL,
	[MapId] [nvarchar](450) NULL,
	[Location_X] [real] NOT NULL,
	[Location_Y] [real] NOT NULL,
	[Location_Z] [real] NOT NULL,
	[Rotation_Pitch] [real] NOT NULL,
	[Rotation_Roll] [real] NOT NULL,
	[Rotation_Yaw] [real] NOT NULL,
	[Group] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Characters] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Characters] ADD  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [Group]
GO

ALTER TABLE [dbo].[Characters]  WITH CHECK ADD  CONSTRAINT [FK_Characters_Maps_MapId] FOREIGN KEY([MapId])
REFERENCES [dbo].[Maps] ([Name])
GO

ALTER TABLE [dbo].[Characters] CHECK CONSTRAINT [FK_Characters_Maps_MapId]
GO
```

I don't think this behaviour is intended, or am I wrong? I'm pretty sure my configuration is correct, since I get the desired table on my OSX instance.

### Further technical details
EF Core version: 2.0.3 (via the "Microsoft.AspNetCore.All" package)
Database Provider: SQLServer
Operating system: Win10 x64/ OSX 10.31.1

**Comment by smitpatel** [comment] 2017-12-20 18:49
> As you can see I configured the MapId property to be the ForeignKey and the Characters property to be the inverse porperty on the Map object.

But you did not configure that. Your code has this 
```C#
builder.HasOne(p => p.Map)
                 .WithMany()
                 .HasForeignKey(p => p.MapId);
```
That means navigation `Map` uses FK `MapId` but you explicitly stated that the inverse navigation is null for this relationship. But you got `Characters` navigation in other side. Since it is not configured in any relationship, conventions will create a relationship for that which will use FK named `MapName` (Principal EntityType Name + Principal Key Column Name).

If you want only 1 relationship then you need to change your configuration to following:
```C#
builder.HasOne(p => p.Map)
    .WithMany(p => p.Characters)
    .HasForeignKey(p => p.MapId);
```

It is interesting that OS X generated different model.

**Comment by Ruhrpottpatriot** [comment] 2017-12-20 19:07
Well, that takes care of the Win10 side of things. However it's funny to see that OSX generated the correct model from the start.

**Comment by ajcvickers** [comment] 2017-12-20 19:59
@Ruhrpottpatriot Can you please post a runnable project/solution or full code listing that reproduces what you are seeing on OSX? It is very strange that the behaviors are different and we would like to dig into what might be causing this.

**Comment by Ruhrpottpatriot** [comment] 2017-12-20 20:23
Sure, I'll see if I can clean up my project tomorrow. I did some work on it and I need to roll back various things.

**Comment by Ruhrpottpatriot** [comment] 2017-12-21 20:16
A quick update: I'll try to upload it tomorrow. I found a similar, but not identical issue, which happens on both my PC and Mac.
So I want to make sure this issue is not related to an error in my config.

**Comment by ajcvickers** [comment] 2018-01-03 18:59
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:03 UTC
Labels: closed-could-not-reproduce
