### ISSUE TITLE
Generic FromSql

### ISSUE THREAD

**Issue by freshe** [dotnet/efcore#3187] opened 2015-09-22 12:03 UTC
FromSql only seems to work with classes/tables that is already mapped within your DbContext.
Is there a way/plan to make it work like the "EF6x SqlQuery<T> generic" way?

The entity type 'Test' was not found. Ensure that the entity type has been added to the model

```
    public class Test
    {
        public int id { get; set; }
    }

    public void Index()
    {
        var db = new AppDbContext();
        var data = db.Set<Test>().FromSql("SELECT id FROM table WHERE 1=1").ToList();
    }
```

**Comment by anpete** [comment] 2015-09-22 16:51
See #1862

**Comment by divega** [comment] 2015-09-22 19:17
@freshe this is a known limitation of `FromSql()` compare to EF6's `SqlQuery()` as explained in the bug @anpete linked to. Although `FromSql()` allows you to provide alternative SQL to bootstrap a `DbSet`, the `DbSet` can still only be of mapped entity type. All that said, you should be able to do this to get what you want:

``` C#
var data = db.Set<Table>()
    .FromSql("SELECT id FROM table WHERE 1=1")
    .Select(t => new Test {Id = t.Id})
    .ToList();
```
Also note that until very recently there was a bug (#3142) that that would cause the projection to be evaluated in memory, but this is now fixed in nightly builds.

**Comment by freshe** [comment] 2015-09-22 20:55
Thanks @divega @anpete for clarification and workarounds.

I have a UnitOfWork class with the SqlQuery<T> method used extensively throughout the application. If FromSql could be used in the same way it would have been easy to update the code in one place and just have it work.

**Comment by Vasimovic** [comment] 2015-09-22 21:34
Same here we use the sqlQuery method extensively throughout applications that are not rooted in the DbContext; typically to retrieve (subset) view data that is not part of the DbContext, therefore item #1862 would be invaluable

**Comment by divega** [comment] 2015-09-23 00:14
@freshe @Vasimovic thanks for the feedback. I will close this issue as a dupe of #1862 and have that one marked as up-for-grabs. We agree this capability is important but at the moment we don't plan to include it in EF 7.0 RTM.

**Closed** 2022-10-16 09:09 UTC
