### ISSUE TITLE
Problem with case sensitivity when querying a view

### ISSUE THREAD

**Issue by johnkwaters** [dotnet/efcore#8343] opened 2017-05-01 16:14 UTC
I know Views are not fully supported, but I have a simple view that I am querying, and found to my suprise that it is case sensitive. When querying a table, it is not. I am using Azure DB, and looking at the debug output, I can see that in the table case, there is a WHERE clause with CHARINDEX, and since the Azure DB collation is case insensitive this works. However, when the entity is a view, that part of the WHERE clause is missing, so I am assuming it is happening in memory (and C# is case sensitive), so that explains the difference.
But why is the WHERE being done in memory for the view? What has EF core sneakily found out about the Entity that causes it to behave differently? In my OnModelCreating the setup is very simple:

		    modelBuilder.Entity<vwTenant>(b =>
		    {
		        b.ToTable("vwTenant");
		        b.HasKey(t => t.Id);
		    });

The views is in a context property like the rest of the tables

public DbSet<vwTenant> vwTenants { get; set; }

**Comment by smitpatel** [comment] 2017-05-01 16:34
@johnkwaters - EF doesn't do special processing just because EntityType is view and not a table. Client eval happens when EF cannot translate the Where clause to SQL. Please post your queries used against table & view.

**Comment by johnkwaters** [comment] 2017-05-01 16:41
I build the SQL dynamically, this is what I see output:

(QueryContext queryContext) => IEnumerable<int> _ToSequence(
    element: int Count(
        source: IEnumerable<vwTenantDTO> _Select(
            source: IEnumerable<ValueBuffer> _Where(
                source: IEnumerable<ValueBuffer> _ShapedQuery(
                    queryContext: queryContext, 
                    shaperCommandContext: SelectExpression: 
                        SELECT [v].[NumKiosks], [v].[NumUsers], [v].[NumLocations], [v].[NumProducts], [v].[Id], [v].[Name], [v].[TenantTypeId], [v].[InvitationCode]
                        FROM [vwTenant] AS [v]
                        WHERE [v].[Active] = 1
                    , 
                    shaper: ValueBufferShaper
                )
                , 
                predicate: (ValueBuffer <generated>_3) => False || bool new vwTenantDTO{ 
                    int TryReadValue(
                        valueBuffer: <generated>_3, 
                        index: 0, 
                        property: null
                    )
                    NumKiosks = TryReadValue(<generated>_3, 0, null), 
                    int TryReadValue(
                        valueBuffer: <generated>_3, 
                        index: 1, 
                        property: null
                    )
                    NumUsers = TryReadValue(<generated>_3, 1, null), 
                    int TryReadValue(
                        valueBuffer: <generated>_3, 
                        index: 2, 
                        property: null
                    )
                    NumLocations = TryReadValue(<generated>_3, 2, null), 
                    int TryReadValue(
                        valueBuffer: <generated>_3, 
                        index: 3, 
                        property: null
                    )
                    NumProducts = TryReadValue(<generated>_3, 3, null), 
                    int TryReadValue(
                        valueBuffer: <generated>_3, 
                        index: 4, 
                        property: null
                    )
                    Id = TryReadValue(<generated>_3, 4, null), 
                    string TryReadValue(
                        valueBuffer: <generated>_3, 
                        index: 5, 
                        property: null
                    )
                    Name = TryReadValue(<generated>_3, 5, null), 
                    int TryReadValue(
                        valueBuffer: <generated>_3, 
                        index: 6, 
                        property: null
                    )
                    TenantTypeId = TryReadValue(<generated>_3, 6, null), 
                    string TryReadValue(
                        valueBuffer: <generated>_3, 
                        index: 7, 
                        property: null
                    )
                    InvitationCode = TryReadValue(<generated>_3, 7, null) 
                }
                .Name.Contains(
                    value: "vilmate"
                )
            )
            , 
            selector: (ValueBuffer <generated>_3) => new vwTenantDTO{ 
                int TryReadValue(
                    valueBuffer: <generated>_3, 
                    index: 0, 
                    property: null
                )
                NumKiosks = TryReadValue(<generated>_3, 0, null), 
                int TryReadValue(
                    valueBuffer: <generated>_3, 
                    index: 1, 
                    property: null
                )
                NumUsers = TryReadValue(<generated>_3, 1, null), 
                int TryReadValue(
                    valueBuffer: <generated>_3, 
                    index: 2, 
                    property: null
                )
                NumLocations = TryReadValue(<generated>_3, 2, null), 
                int TryReadValue(
                    valueBuffer: <generated>_3, 
                    index: 3, 
                    property: null
                )
                NumProducts = TryReadValue(<generated>_3, 3, null), 
                int TryReadValue(
                    valueBuffer: <generated>_3, 
                    index: 4, 
                    property: null
                )
                Id = TryReadValue(<generated>_3, 4, null), 
                string TryReadValue(
                    valueBuffer: <generated>_3, 
                    index: 5, 
                    property: null
                )
                Name = TryReadValue(<generated>_3, 5, null), 
                int TryReadValue(
                    valueBuffer: <generated>_3, 
                    index: 6, 
                    property: null
                )
                TenantTypeId = TryReadValue(<generated>_3, 6, null), 
                string TryReadValue(
                    valueBuffer: <generated>_3, 
                    index: 7, 
                    property: null
                )
                InvitationCode = TryReadValue(<generated>_3, 7, null) 
            }
        )
    )
)

Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection:Debug: Opening connection to database 'holojem-qa-sdb' on server 'holojem-qa-sql.database.windows.net'.
Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory:Information: Executed DbCommand (505ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [v].[NumKiosks], [v].[NumUsers], [v].[NumLocations], [v].[NumProducts], [v].[Id], [v].[Name], [v].[TenantTypeId], [v].[InvitationCode]
FROM [vwTenant] AS [v]
WHERE [v].[Active] = 1

**Comment by johnkwaters** [comment] 2017-05-01 16:43
I am programatically building the expression analog to 'where name contains 'searchString''
Basically by using the string.Contains method.
THis translates to CHARINDEX for the tables
For the view it doesnt

**Comment by johnkwaters** [comment] 2017-05-01 16:44
![view](https://cloud.githubusercontent.com/assets/3422637/25586116/b64da22c-2e52-11e7-9fb1-cfbbba9ffc93.png)

**Comment by johnkwaters** [comment] 2017-05-01 16:46
The vwTenantDTO project to looks like:

`    public class vwTenantDTO : TenantDTO
    {
        /// <summary>
        /// The number of kiosks in this tenant
        /// </summary>
        public int NumKiosks { get; set; }
        /// <summary>
        /// The number of users in this tenant
        /// </summary>
        public int NumUsers { get; set; }
        /// <summary>
        /// The number of locations in this tenant
        /// </summary>
        public int NumLocations { get; set; }
        /// <summary>
        /// The number of products in this tenant
        /// </summary>
        public int NumProducts { get; set; }
    }`

**Comment by johnkwaters** [comment] 2017-05-01 16:46
With

`    public class TenantDTO : IEntityId
    {
        /// <summary>
        /// Unique ID
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// The name of the Tenant
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// The type of tenant
        /// </summary>
        public int TenantTypeId { get; set; } = (int) TenantTypes.Tenant;
        /// <summary>
        /// The code to use when signing up new users to the tenant
        /// </summary>
        public string InvitationCode { get; set; }
    }`

**Comment by johnkwaters** [comment] 2017-05-01 16:50
One difference is that the fluent table declaration specifies a unique index on that Name field, where as the view version doesnt

**Comment by smitpatel** [comment] 2017-05-01 20:01
@johnkwaters - I am not able to reproduce this. With table and view both, I was getting contains translated to server. Unique index causes no effect on queries so that is not the reason. There may be something different in your model which is causing failed translation. Can you modifying following code so that it reproduces the issue you are seeing.

I used following code
```C#
public class Program
{
    public static void Main(string[] args)
    {
        using (var db = new MyContext())
        {
            var loggerFactory = db.GetService<ILoggerFactory>();
            loggerFactory.AddConsole(LogLevel.Information);
        }

        using (var db = new MyContext())
        {
            // Run queries
            var query = db.Blogs.Where(b => new BlogDTO
                                            {
                                                Id = b.Id,
                                                Title = b.Title
                                            }.Title.Contains("test"))
                .ToList();
        }

        Console.WriteLine("Program finished.");
    }
}


public class MyContext : DbContext
{
    // Declare DBSets
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // Select 1 provider
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;")
        //     .UseSqlite("filename=_modelApp.db")
        //     .UseInMemoryDatabase(databaseName: "_modelApp")
            .EnableSensitiveDataLogging();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Configure model
        modelBuilder.Entity<Blog>().ToTable("BlogView");
    }
}

public class Blog
{
    public int Id { get; set; }
    public string Title { get; set; }
}

public class BlogDTO
{
    public int Id { get; set; }
    public string Title { get; set; }
}
```

**Comment by smitpatel** [comment] 2017-05-08 17:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:03 UTC
Labels: closed-could-not-reproduce
