### ISSUE TITLE
ComplexTypes and Constructors to work with NullReferenceTypes

### ISSUE THREAD

**Issue by visschersm** [dotnet/efcore#26866] opened 2021-12-01 16:18 UTC
When working with ComplexTypes and NRTs I would like to use constructors to assign data to my readonly properties. 
Currently when generating migrations I get the following error message: 

> System.InvalidOperationException: No suitable constructor was found for entity type 'Product'. The following constructors had parameters that could not be bound to properties of the entity type: cannot bind 'limits' in 'Product(int id, PhysicalLimits limits)'; cannot bind 'minWeight', 'maxWeight' in 'Product(int id, int minWeight, int maxWeight)'

Following the EFCore constructor documentation: [Entity type constructors](https://docs.microsoft.com/en-us/ef/core/modeling/constructors)
And the ComplexType documentation: [Owned Entity types](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities)

I came up with the following (which gives the error):
[ComplexTypes and Constructors Repository](https://github.com/visschersm/efcore-subclasses/blob/main/Program.cs)

**Comment by ajcvickers** [comment] 2021-12-03 11:29
Duplicate of #12078.

**Closed** 2022-10-16 20:17 UTC
Labels: closed-duplicate, customer-reported
