### ISSUE TITLE
dotnet ef -e | --environment don't seem to have any effect

### ISSUE THREAD

**Issue by Davilink** [dotnet/efcore#8445] opened 2017-05-12 02:39 UTC
I try to update my database where my connectionString is specified in the appsettings.local.json, not in the appsettings.Development.json.

I keep getting : « The keyword 'integrated security' is not supported on this platform. »

```
someone@somewhere:/mnt/e/dev/src/secret/secret/WebApp$ dotnet ef database update -c MySuperDataContext -e local

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:30.42
System.NotSupportedException: The keyword 'integrated security' is not supported on this platform.
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnection
Options& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The keyword 'integrated security' is not supported on this platform.
```

### Steps to reproduce
dotnet ef database update -c MySuperDataContext -e local

appsettings.local.json
```json
{
  "ConnectionStrings": {
    "MySuperDataContext ": "Server=192.168.0.2;Initial Catalog=MySuperDB;Persist Security Info=False;User ID=mySuperUser;Password=mySuperSecretPassword;MultipleActiveResultSets=False;TrustServerCertificate=False;Connection Timeout=30;"
  }
}
```

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Linux (on Windows)
IDE: VS Code

**Comment by ajcvickers** [comment] 2017-05-15 17:10
@Davilink Can you provide a full project or code listing for what you are seeing? It's not clear from the code you posted what is going on here.

**Comment by ajcvickers** [comment] 2017-05-22 18:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:04 UTC
Labels: closed-could-not-reproduce
