### ISSUE TITLE
Cosmos: Translate subquery in filter condition

### ISSUE THREAD

**Issue by NickSevens** [dotnet/efcore#17957] opened 2019-09-20 13:12 UTC
Consider this CosmosDb document structure:
```json
{
    "Id": "f0609362-4008-4edc-ae1f-76ef1c0ef974",
    "Discriminator": "MyEntity",
    "Title": "Test entity 1",
    "id": "MyEntity|f0609362-4008-4edc-ae1f-76ef1c0ef974",
    "AuthorizedUsers": [
        {
            "Discriminator": "UserInfo",
            "DisplayName": "John Doe",
            "LoginName": "john.doe@contoso.com"
        },
        {
            "Discriminator": "UserInfo",
            "DisplayName": "Jane Doe",
            "LoginName": "jane.doe@contoso.com"
        }
    ]
}
```

When querying data I would like to perform a query which filters on AuthorizedUsers properties. E.g.:
```csharp
await _dbContext.MyEntities
                .Where(s => s.AuthorizedUsers.Any(m => m.LoginName == "jane.doe@contoso.com"))
                .ToListAsync();
```

However, this results in a query translation error:

> System.InvalidOperationException: The LINQ expression 'Where<MyEntity>(\r\n    source: DbSet<MyEntity>, \r\n    predicate: (s) => Any<UserInfo>(\r\n        source: AsQueryable<UserInfo>(Property<ICollection<UserInfo>>(s, \"AuthorizedUsers\")), \r\n        predicate: (o) => o.LoginName == \"jane.doe@contoso.com\"))' could not be translated. Either rewrite the query in a form that can be translated

**Question:** is this something that is or should be possible to achieve? The same query can be executed on CosmosDB SQL syntax, like this:
```sql
SELECT VALUE c
FROM c
WHERE EXISTS(
    SELECT VALUE u
    FROM u IN c.AuthorizedUsers
    WHERE u.LoginName = "jane.doe@contoso.com"
)
```

**Comment by smitpatel** [comment] 2019-09-20 16:54
CosmosDb also supports Exists operator. I could not find it docs (hence it hasn't implemented yet) but query runs correctly.

**Comment by NickSevens** [comment] 2019-09-20 17:25
@smitpatel you mean there is an undocumented way to achieve the same result using EF als linq? Or what do you mean exactly?

**Comment by smitpatel** [comment] 2019-09-20 19:03
I meant that it is not in cosmos docs so we did not know that such SQL was valid. Hence it does not work in EF Core yet.

**Comment by NickSevens** [comment] 2019-09-20 19:08
EXISTS operator is described here:

https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-subquery#exists-expression

In the meantime; is there an alternative way to achieve the same result with EFCore?

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Smit Patel <notifications@github.com>
Verzonden: Friday, September 20, 2019 9:04:06 PM
Aan: aspnet/EntityFrameworkCore <EntityFrameworkCore@noreply.github.com>
CC: Nick Sevens <nick_sevens@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [aspnet/EntityFrameworkCore] CosmosDB query nested data (#17957)


I meant that it is not in cosmos docs so we did not know that such SQL was valid. Hence it does not work in EF Core yet.

**Comment by smitpatel** [comment] 2019-09-20 19:10
No work-around.

**Comment by AndriySvyryd** [comment] 2019-09-20 20:25
Related to https://github.com/aspnet/EntityFrameworkCore/issues/16146

**Comment by NickSevens** [comment] 2019-09-22 19:14
@AndriySvyryd @smitpatel are there any other operators that _do_ translate into a subquery (JOIN, SELECT, ...)?

**Comment by smitpatel** [comment] 2019-09-23 17:56
@NickSevens - We don't have translation of subcollections composition in Cosmos yet. Mainly `Exists` operator or `a in root.Orders` pattern (which is used for join).

**Comment by andyamacdonald** [comment] 2020-10-28 16:04
@NickSevens did you ever happen to find a work around for this? I'm in exactly the same position and it looks like support is still missing.

@smitpatel is this something you have on the roadmap?

**Comment by athinadev** [comment] 2020-12-17 11:52
Please see this too, it should be the same error
#23704

**Comment by Aford73** [comment] 2022-02-10 08:53
Good morning all

Non-techie here but we have run into this issue in a project I'm involved in. Any updates @smitpatel on progress I can take back to the team? Bit stuck given there does not appear to be a short term workaround.

Thanks very much

**Comment by Aford73** [comment] 2022-02-10 11:35
> @Aford73 raw SQL support has been implemented in Cosmos, so you can use that for the queries which requires unsupported EF features ([see docs](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql)).

Many thanks @roji  we were aware of the raw SQL support, this can be used only if we will expose a dedicated endpoint (that won't benefit from all the features that OData adds: select, filter, top, skip, etc.) for filtering employees based on the email:

Example of possible endpoint format: v2/employees/findByEmail?value=aaa@aaa.com&ownership=Organization

 any features like select, top, skip, will require bespoke development on this dedicated endpoint.

**Comment by roji** [comment] 2022-02-10 13:13
@Aford73 that's true, though note that EF Core does allow you to compose LINQ operators over raw SQL - not sure exactly what it would look like with OData, but I'm assuming it's possible. In any case, we're not currently planning on working on this for 7.0 (the issue is in the Backlog milestone), so it may be a good idea to look at workarounds.

**Comment by Aford73** [comment] 2022-02-10 13:29
> @Aford73 that's true, though note that EF Core does allow you to compose LINQ operators over raw SQL - not sure exactly what it would look like with OData, but I'm assuming it's possible. In any case, we're not currently planning on working on this for 7.0 (the issue is in the Backlog milestone), so it may be a good idea to look at workarounds.

Thanks vey much for the response @roji we'll take a look at the LINQ possibilities

**Comment by cpalmisciano** [comment] 2022-03-21 18:55
I am running into the same issue querying array fields of any type, in EF 6.0.
Is it a work around, other than raw sql?

**Comment by sekarcse** [comment] 2022-04-08 09:10
Hi Guys,

We are also facing same kind of issue.

await _dbContext.MyEntities
                .Where(s => s.AuthorizedUsers.Any(m => m.LoginName == "jane.doe@contoso.com"))
                .ToListAsync();
                
                
 Do we have any solutions for this?

**Comment by truman303** [comment] 2022-08-17 11:35
@roji @NickSevens I tried the FromRawSql approach with an EXISTS clause, however the data I get back seems to be nested inside a "c: ..." tag, instead of returning the array at the root. I think this may be due to EFCore wrapping the SQL in a "SELECT c FROM (...) c", which I cannot seems to change to "SELECT VALUE c FROM ...". More detail here: https://stackoverflow.com/questions/73386712/how-do-i-access-the-value-using-cosmosqueryableextensions

**Comment by gabolarraguivel** [comment] 2022-10-31 23:29
Hello! Is this planned to be fixed with EF Core 7.0?

**Comment by roji** [comment] 2022-11-01 05:43
This issue is in the Backlog milestone. This means that it is not going to happen for the 7.0 release. We will re-assess the backlog following the 7.0 release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by gabolarraguivel** [comment] 2022-11-01 18:53
I think this is one of the most important things to fix, because there is no way of querying nested objects aside of using FromSqlQuery.

Forget about using LINQKit or another library that makes querying easier.

**Comment by wbuck** [comment] 2022-11-19 22:31
I’ve found that using the CosmosClient’s Linq provider is able to translate queries like this. EF Core is a great piece of tech, but it still needs some time with Cosmos in order to generate the correct expression trees.

My recommendation is to switch to using the CosmosClient Linq provider (which is also recommended by the devs who created the cosmos client library) over EF Core for the time being.

**Comment by hasmMarques** [comment] 2023-07-25 09:44
Hi,
I have a document that looks like this;
```
{
    "id": "test",
    "version": "test",
    "applicableProducts": [
        "test0",
        "test1"
    ],
    "deletedTimestamp": null
}
```

Using EF 7.0 wit a LINQ query expression it get translated into this;
```
 'DbSet<FirmwareInformation>()
          .Where(x => x.DeletedTimestamp == null && x.ApplicableProducts
              .Any(Inner => Inner == "test0"))'
```
When the query is executed I get this error:
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The LINQ expression 'Inner => Inner == "test0"' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

Do you have any solution for this besides using the the CosmosClient?

**Comment by wbuck** [comment] 2023-07-25 12:27
@hasmMarques try using `CountAsync` instead.

```C#
(await DbSet<FirmwareInformation>()
          .Where(x => x.DeletedTimestamp == null && x.ApplicableProducts)
          .Where(inner => inner == "test0")
          .CountAsync()) > 0;
```

**Comment by hasmMarques** [comment] 2023-07-26 07:45
@wbuck thanks for your reply.
Unfortunately the result is the same
```
dbug: 26-Jul-23 08:43:00.920 CoreEventId.QueryCompilationStarting[10111] (Microsoft.EntityFrameworkCore.Query)
      Compiling query expression:
      'DbSet<FirmwareInformation>()
          .Where(x => x.DeletedTimestamp == null && x.ApplicableProducts
              .Any(Inner => Inner == "test0"))
          .Count()'
dbug: 26-Jul-23 08:43:01.106 CoreEventId.ContextDisposed[10407] (Microsoft.EntityFrameworkCore.Infrastructure)
      'DpsDbContext' disposed.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The LINQ expression 'Inner => Inner == "test0"' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
         at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosSqlTranslatingExpressionVisitor.VisitLambda[T](Expression`1 lambdaExpression)
```

**Comment by hasmMarques** [comment] 2024-08-14 07:58
Hi all,

could you please inform me if the issue that I detailed [here](https://github.com/dotnet/efcore/issues/17957#issuecomment-1651158231) has been resolved in EF8 or EF9, or if a resolution is still pending.

**Comment by roji** [comment] 2024-08-14 08:17
I can confirm that the query types listed on this issue should be fully working on EF 9.0 (this is a specific case of querying over nested collections, #16926, #25364). If memory serves, preview.7 - to be released in the next few days - should already work, so once that's released can you please test with it and report back on this issue?

**Closed by roji** 2024-08-14 08:17 UTC
Labels: type-enhancement, customer-reported, area-query, area-cosmos, punted-for-6.0

**Comment by hasmMarques** [comment] 2024-08-14 08:53
> I can confirm that the query types listed on this issue should be fully working on EF 9.0 (this is a specific case of querying over nested collections, #16926, #25364). If memory serves, preview.7 - to be released in the next few days - should already work, so once that's released can you please test with it and report back on this issue?

Hi Roji,

These are excellent news. 
Yes, once EF9 is released, we will test this and report the outcome. 
Thank you for your support.

**Comment by hasmMarques** [comment] 2025-01-10 11:28
Hi,

I confirm that this issue is now fixed in EF9.

Thank you for your support!

**Comment by roji** [comment] 2025-01-10 11:29
@hasmMarques great, thanks for confirming!
