### ISSUE TITLE
Custom Code Generation

### ISSUE THREAD

**Issue by TahiAskHeart** [dotnet/efcore#21409] opened 2020-06-25 03:43 UTC
Adds the templates that EF Core uses to generate Code First models from a database so that code generation can be customized.
Example：EntityFramework.CodeTemplates.CSharp

**Comment by ErikEJ** [comment] 2020-06-25 07:08
EF Core does not use those templates (or any templates at all)

**Comment by ajcvickers** [comment] 2020-06-26 15:24
Duplicate of #4038

**Closed** 2022-10-16 18:31 UTC
Labels: closed-duplicate, customer-reported
