### ISSUE TITLE
'$78_System.Reflection.MissingRuntimeArtifactException' in Unknown Module.

### ISSUE THREAD

**Issue by adamkalicinscy** [dotnet/efcore#2929] opened 2015-08-26 20:20 UTC
I have done everything from http://ef.readthedocs.org/en/latest/getting-started/uwp.html and everything works just fine in Debug. 

In Release i have application crash with exception:

Exception thrown: '$78_System.Reflection.MissingRuntimeArtifactException' in Unknown Module.
Unhandled exception at 0x0FF132F9 (Windows.UI.Xaml.dll) in eftest46.exe:

I am using 
    "EntityFramework.Commands": "7.0.0-beta6",
    "EntityFramework.SQLite": "7.0.0-beta6",
    "Microsoft.ApplicationInsights": "1.0.0",
    "Microsoft.ApplicationInsights.PersistenceChannel": "1.0.0",
    "Microsoft.ApplicationInsights.WindowsApps": "1.0.0",
    "Microsoft.CodeAnalysis.CSharp": "1.0.0",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0"

**Comment by natemcmaster** [comment] 2015-08-26 20:46
This is because .NET Native support is not yet ready. See #623 

As a workaround, uncheck the **"Compile with .NET Native tool chain"** option in your project settings.

![image](https://cloud.githubusercontent.com/assets/2696087/9505701/c43632ac-4bf8-11e5-8fc0-e321c2e1a763.png)

**Comment by adamkalicinscy** [comment] 2015-08-27 15:49
Ok Thank you. It works with "Compile with .NET Native tool chain".

But according to this: http://blogs.msdn.com/b/dotnet/archive/2015/07/30/universal-windows-apps-in-net.aspx 

"When you submit an app, the wizard submits your app's MSIL. The store compiles it with .NET Native, optimizing your app into native machine code". 

Does in mean that my app will fail store cartification? 
I'm starting a new project, the publication of which is scheduled for next month and I must now decide how to handle sqlite database. Does this mean that if you do not find The Solution for .Net Native will not be able to publish the application?

If so then I have to use SQLite.Net-PCL

**Comment by natemcmaster** [comment] 2015-08-27 16:37
@adamkalicinscy good question. I will use my internal email powers to get a clear answer on this. I can't find one myself in the docs. I suspect the store should respect your "Release" build settings, but I'll check to be sure. If they compile to .NET Native regardless of your settings, then I need to make sure #623 is resolved soon.

**Comment by natemcmaster** [comment] 2015-08-27 18:33
@adamkalicinscy my guess was wrong. According to the authors of the post you referenced, all UWP apps will be compiled to .NET Native *regardless of your project build settings*.

Closing this issue as a duplicate of #623.

In the meantime, I recommend [these blog posts](http://blogs.msdn.com/b/dotnet/archive/tags/dotnetnative/), in particular [.NET Native Deep Dive: Help! I Hit a MissingMetadataException!](http://blogs.msdn.com/b/dotnet/archive/2014/05/21/net-native-deep-dive-help-i-hit-a-missingmetadataexception.aspx)

**Closed** 2022-10-16 09:06 UTC
