### ISSUE TITLE
Using ExecuteUpdateAsync with owned entity throws exception

### ISSUE THREAD

**Issue by WiredUK** [dotnet/efcore#30860] opened 2023-05-09 16:22 UTC
### Problem
When using the new `ExecuteUpdateAsync`/`ExecuteUpdate` methods and calling `SetProperty` on a property in an owned entity, it will throw an exception.

### Exception

Stack trace:
```
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteUpdateAsync[TSource](IQueryable`1 source, Expression`1 setPropertyCalls, CancellationToken cancellationToken)
   at UserQuery.Main(), line 10
   at UserQuery.Main(), line 10
```

Message:

> InvalidOperationException: The LINQ expression 'DbSet<Blog>()
>     .Select(b => IncludeExpression(
>         EntityExpression:
>         b, 
>         NavigationExpression:
>         EF.Property<BlogDetails>(b, "Owned"), Owned)
>     )
>     .ExecuteUpdate(updates => updates.SetProperty<string>(
>         propertyExpression: e => e.Owned.Value, 
>         valueExpression: __x_0))' could not be translated. Additional information: The following lambda argument to 'SetProperty' does not represent a valid property to be set: 'e => e.Owned.Value'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

### Repro code
```C#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var x = "Some value";

await ctx.Entities.ExecuteUpdateAsync(updates => updates.SetProperty(e => e.Name, x));  // This works fine
await ctx.Entities.ExecuteUpdateAsync(updates => updates.SetProperty(e => e.Owned.Value, x));  // This throws an exception

class BlogContext : DbContext
{
	public DbSet<Blog> Entities { get; set; }

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		=> optionsBuilder
			.UseSqlServer(@"Server=localhost;Database=test;Integrated Security=True;TrustServerCertificate=True")
			.EnableSensitiveDataLogging();
}

public class Blog
{
	public int Id { get; set; }
	public string Name { get; set; }
	public BlogDetails Owned { get; set; }
}

[Owned]
public class BlogDetails
{
	public string Value { get; set; }
}
```

### Include provider and version information

EF Core version: 7.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0)

**Comment by roji** [comment] 2023-05-09 17:09
Duplicate of #28627

**Comment by roji** [comment] 2023-05-09 17:11
You can work around this by projecting before the ExecuteUpdate:

```c#
await ctx.Entities.Select(e => e.Owned).ExecuteUpdateAsync(updates => updates.SetProperty(o => o.Value, x));
```

**Closed** 2023-05-10 20:02 UTC
Labels: customer-reported
