### ISSUE TITLE
Incorrect query generation for nested collection type

### ISSUE THREAD

**Issue by kooshan** [dotnet/efcore#13849] opened 2018-11-01 09:35 UTC
Hi,
I have a AspNetCore/EFCore/OData/Automapper application, which seams to have an issue when I try to expand an `ICollection<T>` type. I already filed an [Issue on Automapper github page](https://github.com/AutoMapper/AutoMapper/issues/2853), but it seems to be a EF-related issue.

**Comment by kooshan** [comment] 2018-11-01 22:02
Here's the expression I get using `ProjectTo<DTO>().Expression`:

```
EntityQueryable<Customer>.Select(dtoCustomer => new Customer
    {
        BankAccounts = dtoCustomer.BankAccounts.Select(dtoBankAccount => new BankAccount
            {
                AccEncrypt = dtoBankAccount.AccEncrypt,
                AccountNo = dtoBankAccount.AccountNo,
                AccountType = (dtoBankAccount.AccountType == null)
                    ? null
                    : new BankAccountType
                    {
                        Id = dtoBankAccount.AccountType.Id,
                        TypeName = dtoBankAccount.AccountType.TypeName
                    },
                AccountUsageId = dtoBankAccount.AccountUsageId,
                Bank = (dtoBankAccount.Bank == null)
                    ? null
                    : new Bank
                    {
                        Id = dtoBankAccount.Bank.Id,
                        Name = dtoBankAccount.Bank.Name,
                        NameLatin = dtoBankAccount.Bank.NameLatin
                    },
                BranchCode = dtoBankAccount.BranchCode,
                BranchLocation = (dtoBankAccount.BranchLocation == null)
                    ? null
                    : new City
                    {
                        Id = dtoBankAccount.BranchLocation.Id,
                        Name = dtoBankAccount.BranchLocation.Name,
                        NameLatin = dtoBankAccount.BranchLocation.NameLatin
                    },
                BranchName = dtoBankAccount.BranchName,
                Id = dtoBankAccount.Id,
                ShebaCode = dtoBankAccount.ShebaCode
            }).ToList(),
        ExternalId = dtoCustomer.ExternalId,
        ExtraInfo = (dtoCustomer.ExtraInfo == null)
            ? null
            : new CustomerExtraInfo
            {
                Comment = dtoCustomer.ExtraInfo.Comment,
                Flags = dtoCustomer.ExtraInfo.Flags.Select(dtoCustomerFlag => new CustomerFlag
                    {
                        Description = dtoCustomerFlag.Description,
                        Id = dtoCustomerFlag.Id,
                        Symbol = dtoCustomerFlag.Symbol
                    }).ToList(),
                Id = dtoCustomer.ExtraInfo.Id
            },
        Id = dtoCustomer.Id,
        Name = dtoCustomer.Name,
        Nationality = (dtoCustomer.Nationality == null)
            ? null
            : new Country
            {
                Id = dtoCustomer.Nationality.Id,
                Name = dtoCustomer.Nationality.Name,
                NameLatin = dtoCustomer.Nationality.NameLatin
            }
    })
```

**Comment by maumar** [comment] 2018-11-07 00:14
@kooshan can you provide listings for all the entities/dtos present in the above query, as well as the contents of OnModelCreating method on the DbContext?

**Comment by ajcvickers** [comment] 2018-11-14 18:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:38 UTC
Labels: closed-could-not-reproduce, customer-reported
