### ISSUE TITLE
EF Migration Error : Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions

### ISSUE THREAD

**Issue by fanxiaoyuan** [dotnet/efcore#15145] opened 2019-03-24 16:35 UTC
Hi, 
I've got exactly the same error https://github.com/aspnet/EntityFrameworkCore/issues/14905 while creating my first entity framework core project.
The command : dotnet ef migrations add _name_of_migration_

Here is the callstack:
PM> dotnet ef migrations add MyFirstMigration --project "Path\Of\My\Project\MyProject.csproj"

System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Microsoft.EntityFrameworkCore.DbContext]' while attempting to activate 'MyProject.Data.MyDbContext'.

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)

   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)

   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)

   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_2.<FindContextTypes>b__11()

   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)

   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)

   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)

   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)

   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()

   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()

   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Microsoft.EntityFrameworkCore.DbContext]' while attempting to activate 'MyProject.Data.MyDbContext'.

### Steps to reproduce
- Create a new asp.net core api project
- Add class MyDbContext:

```
public class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions<DbContext> options) : base(options)
        {
        }

        public DbSet<Value> Values { get; set; }
    }

```
- Value.cs:
```
    public class Value
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
```

- In startup class, add the context:
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<MyDbContext>(x => x.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        }
```

In appsettings.json
```
{
  "ConnectionStrings": {
    "DefaultConnection": "Data Source=MyProject.db" 
  },
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*"
}
```

-Package Manager Console 
>Install-Package Microsoft.EntityFrameworkCore.Sqlite
>Install-Package Microsoft.EntityFrameworkCore.Tools -Version 2.2.3
>dotnet ef migrations add MyFirstMigration --project "Path\Of\My\Project\MyProject.csproj"

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: 
Operating system: Win64
IDE: Visual Studio 2017 15.9.8

The csproj:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.2.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

**Comment by fanxiaoyuan** [comment] 2019-03-24 16:38
refering to https://github.com/aspnet/EntityFrameworkCore/issues/9547, error persists after added
ervices.AddScoped<DbContext>(sp => sp.GetService<MyDataContext>());

**Comment by ajcvickers** [comment] 2019-03-24 20:27
@fanxiaoyuan The constructor of your context class needs to be:

```C#
public MyDbContext(DbContextOptions<MyDbContext> options) : base(options)
{
}
```

**Comment by rohitj559** [comment] 2019-06-12 23:24
I had a similar issue and was able to get it fixed by following the solution above.

**Comment by k290** [comment] 2020-06-18 19:24
Commenting here in case someone else comes across this. It also gives this error if you are using an inmemory database. I had to change it to the real thing to add migrations

**Comment by cmonstoke** [comment] 2020-06-22 09:02
The above Solution results in Error	CS1503	Argument 1: cannot convert from 'Microsoft.EntityFrameworkCore.DbContextOptions<MyProject.Data.MyDbContext>' to 'Microsoft.EntityFrameworkCore.DbContextOptions<MyProject.Data.DbContext>' at compile time for me.

**Comment by juganpeeris** [comment] 2020-10-27 06:49
Same for me as @cmonstoke  Were you able to find a solution

**Comment by Alex-Horlock** [comment] 2020-11-06 16:05
Same as @cmonstoke for me too... unable to think of a solution.

**Comment by Alex-Horlock** [comment] 2020-11-06 16:16
> Same for me as @cmonstoke Were you able to find a solution

I finally found a solution here: https://stackoverflow.com/questions/45791795/unable-to-resolve-service-for-type-applicationcontext

Basically don't bother with "DbContextOptions<SomeSpecificContext> options" and use "DbContextOptions options" and it all just works.

**Comment by cmonstoke** [comment] 2020-11-06 19:52
@juganpeeris sorry been afk for a while and no I didn’t resolve this sorry.

**Comment by LuisDev99** [comment] 2020-11-11 04:28
I had multiple projects, basically a Infrastructure project that contained the Configurations/Repository and the API project which had the Startup.cs that injected dependencies.

So, in the command, I had to specify the API project (because thats where the injection occurs), like this:

`C:\some\folders\Infrastructure$  dotnet ef migrations add -s ..\MyAPI_Project\  MyInitialMigration`

Adding the `-s` flag helps entity framework find the startup project.

Evidence:

![image](https://user-images.githubusercontent.com/30758539/98765453-d085c080-23a3-11eb-9dfa-689d1f90a642.png)


I hope this picture helps (it shows my project's structure):

![image](https://user-images.githubusercontent.com/30758539/98765156-0e361980-23a3-11eb-9682-5d8b514eace9.png)

I'm very sorry for my English

**Comment by shahnawazm786** [comment] 2020-12-26 07:57
Hello viewers,
I am getting following error while adding the razor page based on model.
![image](https://user-images.githubusercontent.com/49604292/103147669-a2a2e280-477d-11eb-960c-456f441f46aa.png)

Next is
![image](https://user-images.githubusercontent.com/49604292/103147677-af273b00-477d-11eb-8fb8-8d2efdb0ec38.png)

Controller for the admin

namespace IdetityDemoProject.Controllers
{
    public class AdminController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public AdminController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ProjectRole role)
        {
            var roleExist = await _roleManager.RoleExistsAsync(role.RoleName);
            if(!roleExist)
            {
                var result = await _roleManager.CreateAsync(new IdentityRole(role.RoleName));
            }
            return View(role);
        }
    }

}
DBContext 

namespace IdetityDemoProject.Data
{
    public class DemoIdentityDBContext : IdentityDbContext<ApplicationUser>
    //public class DemoIdentityDBContext : IdentityDbContext<IdentityUser>
    {
        public DemoIdentityDBContext(DbContextOptions<DemoIdentityDBContext> options)
            : base(options)
        {
        }
        //public DemoIdentityDBContext(DbContextOptions options)
        //    : base(options) { }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
        }
    }
}

Application User
----------------
namespace IdetityDemoProject.Areas.Identity.Data
{
    // Add profile data for application users by adding properties to the ApplicationUser class
    public class ApplicationUser : IdentityUser
    {
        [PersonalData]
        [Column(TypeName ="nvarchar(25)")]
        public String FirstName { get; set; }
        [PersonalData]
        [Column(TypeName = "nvarchar(25)")]
        public String LastName { get; set; }

    }
}

Startup.cs
--
namespace IdetityDemoProject
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            //services.AddDbContext<DemoIdentityDBContext>(option =>
            //    option.UseSqlServer(Configuration.GetConnectionString("DemoIdentityDBContextConnection")));
            services.AddDefaultIdentity<ApplicationUser>().AddRoles<IdentityRole>().AddEntityFrameworkStores<DemoIdentityDBContext>();
            services.AddControllersWithViews();
            services.AddRazorPages();
            /*services.AddIdentity<ApplicationUser, IdentityRole>()
            .AddEntityFrameworkStores<DemoIdentityDBContext>()
            .AddDefaultTokenProviders();*/
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapRazorPages();
            });
        }
    }
}

Please help me to resolve the error.
Thanks

**Comment by k290** [comment] 2020-12-26 13:06
This thread needs to be locked. The issue is closed and there's more than enough potential solutions here.  Anything else should be a new issue or go to stackoverflow imo.

**Comment by ajcvickers** [comment] 2021-01-01 19:48
@shahnawazm786 Please open a new issue and include a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by fernandohre** [comment] 2022-02-16 04:54
Here is my case:
I have 3 projects:
1. Api
2. Domain
3. Infrastructure

Api references domain and infrastructure. Inside infrastructure I have MyContextClass and eveything is configured on Startup.cs.

every project are .NET 6.0 and this issue still persists, any idea?

**Comment by RafaelMFonseca** [comment] 2022-03-09 03:23
> Here is my case: I have 3 projects:
> 
> 1. Api
> 2. Domain
> 3. Infrastructure
> 
> Api references domain and infrastructure. Inside infrastructure I have MyContextClass and eveything is configured on Startup.cs.
> 
> every project are .NET 6.0 and this issue still persists, any idea?
> 
> Note: this happens only executing comand: `dotnet ef migrations add InitialCreate`
> 
> I gave up and now I'm using:
> 
> `Add-Migration ` referecing Microsoft.EntityFrameworkCore.Tools package on my project

@fernandohre one of my projects has a similar structure and i was able to run the migration by providing the initial project and the dbcontext project in the parameters:
`dotnet ef migrations add InitDatabase -s MyProject.Api -p MyProject.Infrastructure -c MyDbContext --verbose`

**Comment by Epy92** [comment] 2022-04-13 07:46
The issue occurs because the DbContextOptions is not configured. You can do this by overriding the "OnConfiguring" method.
![image](https://user-images.githubusercontent.com/19517946/163126189-b5e811a5-95c4-46a8-82c1-17dea139ea7c.png)

**Comment by fernandohre** [comment] 2022-04-14 02:15
@Epy92 yes, this is a way to solve the problem. But it's a bad practice, keeping in mind that will expose your connection string enabling direct connections.

**Comment by MilanNemeth** [comment] 2022-04-24 10:27
Hey v6.0-dotneters,

I only had this issue when trying to scaffold a new controller in an ASP.NET WebApi, and it's weird that it otherwise works in runtime:

Program.cs
```cs
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();

builder.Services.AddDbContext<DataContext>(options =>
    options
    .UseNpgsql(builder.Configuration.GetConnectionString("PgSqlConnex"))
    .EnableSensitiveDataLogging()
    .EnableDetailedErrors()
    .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking)
);

var app = builder.Build();

// Configure the HTTP request pipeline.

if (builder.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();

    using (var scope = app.Services.CreateScope())
    {
        var context = scope.ServiceProvider.GetRequiredService<DataContext>();
        context.Database.EnsureCreated();
    }
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
```

DataContext.cs
```cs
public class DataContext : DbContext
{
    public DataContext(DbContextOptions<DataContext> options) : base(options) { }

    public DbSet<DataRecord> DataRecords { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
         modelBuilder.Entity<DataRecord>()
         .Property(dr => dr.CreatedAt)
         .HasDefaultValueSql("CURRENT_TIMESTAMP");
    }

}```

So after I tried everything I found on the whole internet, the solution was in a Reddit post:
DataContextFactory in the same (migrations) assembly, as DataContext.cs:
```cs
public class DataContextFactory : IDesignTimeDbContextFactory<DataContext>
{
    public DataContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<DataContext>();

        optionsBuilder.UseNpgsql("Host=localhost:5432;Database=my_db;Username=postgres;Password=");

        return new DataContext(optionsBuilder.Options);
    }
}
```

PS.: Please be aware that these code snippets are part of a sample application for only learning purposes❗

**Comment by digitalhameed** [comment] 2022-06-16 07:36
> @fanxiaoyuan The constructor of your context class needs to be:
> 
> ```cs
> public MyDbContext(DbContextOptions<MyDbContext> options) : base(options)
> {
> }
> ```

**Comment by Iam-Luik** [comment] 2022-06-26 23:10
I had the same issue because I forgot to add one of my context's in startup :D
the code below solved my problem XD

builder.Services.AddDbContext<MeuDbContext>(options =>
{
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection"));
});

**Closed** 2022-10-16 13:57 UTC
Labels: closed-no-further-action, customer-reported

**Comment by hzexe** [comment] 2023-04-10 06:15
> Hey v6.0-dotneters,
> 
> I only had this issue when trying to scaffold a new API controller in an ASP.NET WebApi in Visual Studio 2022. It's weird though that it otherwise works in runtime:
> 
> Program.cs
> 
> ```cs
> var builder = WebApplication.CreateBuilder(args);
> 
> // Add services to the container.
> 
> builder.Services.AddControllers();
> 
> builder.Services.AddDbContext<DataContext>(options =>
>     options
>     .UseNpgsql(builder.Configuration.GetConnectionString("PgSqlConnex"))
>     .EnableSensitiveDataLogging()
>     .EnableDetailedErrors()
>     .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking)
> );
> 
> var app = builder.Build();
> 
> // Configure the HTTP request pipeline.
> 
> if (builder.Environment.IsDevelopment())
> {
>     app.UseDeveloperExceptionPage();
> 
>     using (var scope = app.Services.CreateScope())
>     {
>         var context = scope.ServiceProvider.GetRequiredService<DataContext>();
>         context.Database.EnsureCreated();
>     }
> }
> 
> app.UseHttpsRedirection();
> 
> app.UseAuthorization();
> 
> app.MapControllers();
> 
> app.Run();
> ```
> 
> DataContext.cs
> 
> ```cs
> public class DataContext : DbContext
> {
>     public DataContext(DbContextOptions<DataContext> options) : base(options) { }
> 
>     public DbSet<DataRecord> DataRecords { get; set; }
> 
>     protected override void OnModelCreating(ModelBuilder modelBuilder)
>     {
>          modelBuilder.Entity<DataRecord>()
>          .Property(dr => dr.CreatedAt)
>          .HasDefaultValueSql("CURRENT_TIMESTAMP");
>     }
> 
> }
> ```
> 
> So after I tried everything I found on the whole internet, the solution was in a Reddit post: DataContextFactory in the same (migrations) assembly, as DataContext.cs:
> 
> ```cs
> public class DataContextFactory : IDesignTimeDbContextFactory<DataContext>
> {
>     public DataContext CreateDbContext(string[] args)
>     {
>         var optionsBuilder = new DbContextOptionsBuilder<DataContext>();
> 
>         optionsBuilder.UseNpgsql("Host=localhost:5432;Database=my_db;Username=postgres;Password=");
> 
>         return new DataContext(optionsBuilder.Options);
>     }
> }
> ```
> 
> PS.: Please be aware that these code snippets are part of a sample application for only learning purposes❗

This problem doesn't always happen.
It's work for me with net 6 and 7.
There is important that they **must** in the same assembly where [the page](https://go.microsoft.com/fwlink/?linkid=851728) not pointed out
