### ISSUE TITLE
Migrations: Index wasn't dropped when altering its column

### ISSUE THREAD

**Issue by Qszer94** [dotnet/efcore#4642] opened 2016-02-25 13:35 UTC
Hello.
I think there is a small problem with migrations and unique indexes. 
I created simple schema like this:
`User --> Role <----> Permission`

In my initial migration I created these entities and I added unique index on UserName column:

``` C#
modelBuilder.Entity<User>()
                .HasIndex(u => u.UserName)
                .IsUnique();
```

Then I added [Required] adnotation to UserName column and made second migration.
When I ran `dnx ef database update` I get this error.

> The index 'IX_User_UserName' is dependent on column 'UserName'.
> The index 'IX_User_UserName' is dependent on column 'UserName'.
> ALTER TABLE ALTER COLUMN UserName failed because one or more objects access this column.

The solution was simple. I had to add manually drop/create index to migration.

It is intended effect?
Does indexes shouldn't be dropped and created automatically as foreign keys ?

**Comment by bricelam** [comment] 2016-05-20 18:15
@roji Do you know if PostgreSQL has any similar limitations?

It looks like SQL Server requires you to drop and re-create indexes when the column is narrowed. (e.g. `NULL` to `NOT NULL`; `nvarchar(30)` to `nvarchar(29)`; etc.)

It it's SQL Server-specific, I'll just fix it in the `SqlServerMigrationsSqlGenerator` otherwise, I'll make a more general fix in `MigrationsModelDiffer`.

**Comment by bricelam** [comment] 2016-05-24 16:21
Confirmed: PostgreSQL doesn't seem to care. :elephant:

**Comment by bricelam** [comment] 2016-05-24 16:27
@rowanmiller Do you have any preferences on this one? My current thinking is to detect this situation during SQL generation on SQL Server and use the backing model to rebuild the indexes. The other option is to rebuild the indexes for all providers (which don't really need it) by detecting this condition in the model differ.

**Comment by rowanmiller** [comment] 2016-05-24 18:50
I'm not too concerned, whatever we think makes the most sense. 

BTW I was going to ask about SQLite... but then 😫.

**Comment by ErikEJ** [comment] 2016-05-24 19:13
SQL CE FTW - if only it was multi-platform :smile:

**Comment by bricelam** [comment] 2016-06-01 21:13
After discussing the implementation in #5561 and some of the other alternatives, we've decided to wait and see if more customers hit this.

The scaffolded migrations were only ever intended to be our "best guess" at what operations needed to be performed in order to create a schema compatible with the specified model. You should always feel free to edit the migrations files after scaffolding them. For now, the workaround is to simply add the appropriate calls to `DropIndex` and `CreateIndex` inside of the scaffolded migration as needed.

Closing as "won't fix yet", but feel free comment if you disagree.

**Comment by rowanmiller** [comment] 2016-06-03 22:53
Also worth noting that we will reconsider our "won't fix" decision if we see more folks hitting this issue.

**Comment by adamongithub** [comment] 2016-06-29 11:25
I've just run into this on SQL Server 2014 while trying to remove a column from an index. Fortunately I found this thread so I'll drop and recreate the whole index instead.

**Comment by ralfbalzer** [comment] 2016-09-21 18:52
I have come accross the same issue today. Would be nice if that gets fixed

**Comment by bricelam** [comment] 2016-09-21 20:53
It should be fixed in the [nightly builds](https://dotnet.myget.org/gallery/aspnetcore-dev). #6102 was the (duplicate) issue used to track this work.

**Closed** 2022-10-16 09:30 UTC
