### ISSUE TITLE
Could not copy error with dotnet ef migrations bundle

### ISSUE THREAD

**Issue by gitown** [dotnet/efcore#27393] opened 2022-02-07 15:32 UTC
Hi,
I'm getting a _"Could not copy .... The process cannot access the file .... because it is being used by another process"_ error when trying to use **dotnet ef migrations bundle** on my project!
I'm sure that the concerned files are not used by any other process, also I tried with a completely new project, restarted my computer, cleaned the bin and obj folders, tried Terminal and the Developer PowerShell within Visual Studio... but I still have the same error!

Any idea about this?

Here is the full output:
```
PS D:\Workspace\TestProject> dotnet ef migrations bundle -p .\Data\ -s .\TestProject\ --verbose --prefix-output -f
verbose: Using project 'D:\Workspace\TestProject\Data\Data.csproj'.
verbose: Using startup project 'D:\Workspace\TestProject\TestProject\TestProject.csproj'.
verbose: Writing 'D:\Workspace\TestProject\Data\obj\Data.csproj.EntityFrameworkCore.targets'...
verbose: dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Mine\AppData\Local\Temp\tmp1AF.tmp /verbosity:quiet /nologo D:\Workspace\TestProject\Data\Data.csproj
verbose: Writing 'D:\Workspace\TestProject\TestProject\obj\TestProject.csproj.EntityFrameworkCore.targets'...
verbose: dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Mine\AppData\Local\Temp\tmp421.tmp /verbosity:quiet /nologo D:\Workspace\TestProject\TestProject\TestProject.csproj
info:    Build started...
verbose: dotnet build D:\Workspace\TestProject\TestProject\TestProject.csproj /verbosity:quiet /nologo
verbose:
verbose: Build succeeded.
verbose:     0 Warning(s)
verbose:     0 Error(s)
verbose:
verbose: Time Elapsed 00:00:02.96
info:    Build succeeded.
verbose: dotnet exec --depsfile D:\Workspace\TestProject\TestProject\bin\Debug\net6.0\TestProject.deps.json --additionalprobingpath C:\Users\Mine\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --runtimeconfig D:\Workspace\TestProject\TestProject\bin\Debug\net6.0\TestProject.runtimeconfig.json C:\Users\Mine\.dotnet\tools\.store\dotnet-ef\6.0.1\dotnet-ef\6.0.1\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll migrations bundle -f --assembly D:\Workspace\TestProject\TestProject\bin\Debug\net6.0\Data.dll --project D:\Workspace\TestProject\Data\Data.csproj --startup-assembly D:\Workspace\TestProject\TestProject\bin\Debug\net6.0\TestProject.dll --startup-project D:\Workspace\TestProject\TestProject\TestProject.csproj --project-dir D:\Workspace\TestProject\Data\ --root-namespace Data --language C# --framework net6.0 --nullable --working-dir D:\Workspace\TestProject --verbose --prefix-output
verbose: Using assembly 'Data'.
verbose: Using startup assembly 'TestProject'.
verbose: Using application base 'D:\Workspace\TestProject\TestProject\bin\Debug\net6.0'.
verbose: Using working directory 'D:\Workspace\TestProject\TestProject'.
verbose: Using root namespace 'Data'.
verbose: Using project directory 'D:\Workspace\TestProject\Data\'.
verbose: Remaining arguments: .
verbose: Finding DbContext classes...
verbose: Finding IDesignTimeDbContextFactory implementations...
verbose: Finding application service provider in assembly 'TestProject'...
verbose: Finding Microsoft.Extensions.Hosting service provider...
verbose: Using environment 'Development'.
verbose: Using application service provider from Microsoft.Extensions.Hosting.
verbose: Found DbContext 'MyDbContext'.
verbose: Finding DbContext classes in the project...
verbose: Using context 'MyDbContext'.
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
warn: 2022-02-07 10:12:04.993 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure)
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 6.0.1 initialized 'MyDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql:6.0.1' with options: SensitiveDataLoggingEnabled DetailedErrorsEnabled ServerVersion 8.0.27-mysql
info: 2022-02-07 10:12:05.163 CoreEventId.ContextInitialized[10403] (Microsoft.EntityFrameworkCore.Infrastructure)
      Entity Framework Core 6.0.1 initialized 'MyDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql:6.0.1' with options: SensitiveDataLoggingEnabled DetailedErrorsEnabled ServerVersion 8.0.27-mysql
info:    Building bundle...
verbose: dotnet publish --runtime win10-x64 --output C:\Users\Mine\AppData\Local\Temp\rac3npvz.mln\publish --no-self-contained
verbose: Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
verbose: Copyright (C) Microsoft Corporation. All rights reserved.
verbose:
verbose:   Determining projects to restore...
verbose:   Restored C:\Users\Mine\AppData\Local\Temp\rac3npvz.mln\efbundle.csproj (in 295 ms).
verbose:   Restored D:\Workspace\TestProject\TestProject\TestProject.csproj (in 295 ms).
verbose:   Restored D:\Workspace\TestProject\Data\Data.csproj (in 295 ms).
verbose:   Data -> D:\Workspace\TestProject\Data\bin\Debug\net6.0\Data.dll
verbose: C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(4635,5): warning MSB3026: Could not copy "obj\Debug\net6.0\TestProject.dll" to "bin\Debug\net6.0\TestProject.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'D:\Workspace\TestProject\TestProject\bin\Debug\net6.0\TestProject.dll' because it is being used by another process.  [D:\Workspace\TestProject\TestProject\TestProject.csproj]
verbose: C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(4635,5): warning MSB3026: Could not copy "obj\Debug\net6.0\TestProject.dll" to "bin\Debug\net6.0\TestProject.dll". Beginning retry 2 in 1000ms. The process cannot access the file 'D:\Workspace\TestProject\TestProject\bin\Debug\net6.0\TestProject.dll' because it is being used by another process.  [D:\Workspace\TestProject\TestProject\TestProject.csproj]
verbose: C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(4635,5): warning MSB3026: Could not copy "obj\Debug\net6.0\TestProject.dll" to "bin\Debug\net6.0\TestProject.dll". Beginning retry 3 in 1000ms. The process cannot access the file 'D:\Workspace\TestProject\TestProject\bin\Debug\net6.0\TestProject.dll' because it is being used by another process.  [D:\Workspace\TestProject\TestProject\TestProject.csproj]
verbose: C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(4635,5): warning MSB3026: Could not copy "obj\Debug\net6.0\TestProject.dll" to "bin\Debug\net6.0\TestProject.dll". Beginning retry 4 in 1000ms. The process cannot access the file 'D:\Workspace\TestProject\TestProject\bin\Debug\net6.0\TestProject.dll' because it is being used by another process.  [D:\Workspace\TestProject\TestProject\TestProject.csproj]
verbose: C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(4635,5): warning MSB3026: Could not copy "obj\Debug\net6.0\TestProject.dll" to "bin\Debug\net6.0\TestProject.dll". Beginning retry 5 in 1000ms. The process cannot access the file 'D:\Workspace\TestProject\TestProject\bin\Debug\net6.0\TestProject.dll' because it is being used by another process.  [D:\Workspace\TestProject\TestProject\TestProject.csproj]
verbose: C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(4635,5): warning MSB3026: Could not copy "obj\Debug\net6.0\TestProject.dll" to "bin\Debug\net6.0\TestProject.dll". Beginning retry 6 in 1000ms. The process cannot access the file 'D:\Workspace\TestProject\TestProject\bin\Debug\net6.0\TestProject.dll' because it is being used by another process.  [D:\Workspace\TestProject\TestProject\TestProject.csproj]
verbose: C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(4635,5): warning MSB3026: Could not copy "obj\Debug\net6.0\TestProject.dll" to "bin\Debug\net6.0\TestProject.dll". Beginning retry 7 in 1000ms. The process cannot access the file 'D:\Workspace\TestProject\TestProject\bin\Debug\net6.0\TestProject.dll' because it is being used by another process.  [D:\Workspace\TestProject\TestProject\TestProject.csproj]
verbose: C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(4635,5): warning MSB3026: Could not copy "obj\Debug\net6.0\TestProject.dll" to "bin\Debug\net6.0\TestProject.dll". Beginning retry 8 in 1000ms. The process cannot access the file 'D:\Workspace\TestProject\TestProject\bin\Debug\net6.0\TestProject.dll' because it is being used by another process.  [D:\Workspace\TestProject\TestProject\TestProject.csproj]
verbose: C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(4635,5): warning MSB3026: Could not copy "obj\Debug\net6.0\TestProject.dll" to "bin\Debug\net6.0\TestProject.dll". Beginning retry 9 in 1000ms. The process cannot access the file 'D:\Workspace\TestProject\TestProject\bin\Debug\net6.0\TestProject.dll' because it is being used by another process.  [D:\Workspace\TestProject\TestProject\TestProject.csproj]
verbose: C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(4635,5): warning MSB3026: Could not copy "obj\Debug\net6.0\TestProject.dll" to "bin\Debug\net6.0\TestProject.dll". Beginning retry 10 in 1000ms. The process cannot access the file 'D:\Workspace\TestProject\TestProject\bin\Debug\net6.0\TestProject.dll' because it is being used by another process.  [D:\Workspace\TestProject\TestProject\TestProject.csproj]
verbose: C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(4635,5): error MSB3027: Could not copy "obj\Debug\net6.0\TestProject.dll" to "bin\Debug\net6.0\TestProject.dll". Exceeded retry count of 10. Failed.  [D:\Workspace\TestProject\TestProject\TestProject.csproj]
verbose: C:\Program Files\dotnet\sdk\6.0.101\Microsoft.Common.CurrentVersion.targets(4635,5): error MSB3021: Unable to copy file "obj\Debug\net6.0\TestProject.dll" to "bin\Debug\net6.0\TestProject.dll". The process cannot access the file 'D:\Workspace\TestProject\TestProject\bin\Debug\net6.0\TestProject.dll' because it is being used by another process. [D:\Workspace\TestProject\TestProject\TestProject.csproj]
verbose: Microsoft.EntityFrameworkCore.Tools.CommandException: Build failed. Use --verbose to see errors.
verbose:    at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsBundleCommand.Execute(String[] args)
verbose:    at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
verbose:    at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
verbose:    at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
error:   Build failed. Use --verbose to see errors.
```

My environment:
EF Core version: Microsoft.EntityFrameworkCore Version=6.0.1
Database provider: Pomelo.EntityFrameworkCore.MySql Version=6.0.1
Target framework: .NET 6.0
Operating system: Windows 11 (21H2 22000.469)
IDE:  Visual Studio 2022 17.0.5

**Comment by Cerebrado** [comment] 2022-02-09 12:45
I'm getting the same error.

**Comment by AndriySvyryd** [comment] 2022-02-11 21:46
Duplicate of https://github.com/dotnet/efcore/issues/25555

**Closed** 2022-10-16 20:25 UTC
Labels: closed-duplicate, customer-reported
