### ISSUE TITLE
Migrations deadlock when migrating inside of TransactionScope

### ISSUE THREAD

**Issue by GSPP** [dotnet/efcore#2449] opened 2015-06-23 16:15 UTC
Under the following conditions a deadlock happens:
1. The schema changed
2. Automatic migrations (with data loss) are enabled
3. A TransactionScope is opened
4. A context is being "used" (I don't know what specific usage triggers this)
5. That "usage" triggers the migration
   
   ```
       using (var tran = CreateTransaction(TransactionScopeOption.Required, IsolationLevel.Serializable))
       using (var db = new EFTestContext())
       {
           var customer = new Customer()
           {
               Name = "Test",
           };
           db.Customers.Add(customer); //This deadlocks. It takes 30 seconds.
   
           tran.Complete();
       }
   
   static TransactionScope CreateTransaction(TransactionScopeOption transactionScopeOption, IsolationLevel isolationLevel)
   {
       return new TransactionScope(transactionScopeOption, new TransactionOptions() { IsolationLevel = isolationLevel, Timeout = TimeSpan.Zero });
   }
    public class Customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        //public string Name2 { get; set; } //use this to trigger some DDL
    }
     public class EFTestContext : DbContext
     {
         public DbSet<Customer> Customers { get; set; } }
   ```

(The model is abridged, I hope it's enough to repro.)

I can see two sessions in profiler and in the SQL Server DMVs:
1. The session that does the migration (altering the schema). It has not committed its transaction.
2. A session that tries to access __MigrationHistory which is still locked.

This is a distributed deadlock between two sessions. Only the timeout will eventually break it. Actually, this might not be a deadlock because I don't see any rollback in Profiler and I do not receive an exception. But it takes 30 seconds to move over that marked line. This smells like a timeout. I'm quite positive that there is a bug here.

Update: The migration did not happen. The column that I added was added according to profiler ("ADD COLUMN...") but it's not there when the program has ended (without unhandled exceptions). I think there's a rollback that I'm not noticing due to profiler settings.

**Comment by bricelam** [comment] 2015-07-14 22:35
Marking for re-triage. This issue appears to be about EF6, not EF7.

**Comment by divega** [comment] 2015-07-14 23:03
Rings a bell... http://entityframework.codeplex.com/workitem/2319

**Comment by rowanmiller** [comment] 2015-07-21 18:40
Dupe of http://entityframework.codeplex.com/workitem/2319

**Closed** 2022-10-16 08:59 UTC
Labels: type-bug
