### ISSUE TITLE
HasDefaultSchema is ignored for tables created with TPC mapping

### ISSUE THREAD

**Issue by Dubzer** [dotnet/efcore#30039] opened 2023-01-12 09:48 UTC
## File a bug
I've been trying to configure TPC mapping with EF Core 7.0.2 and seem to encounter the following bug:

When applying `.UseTpcMappingStrategy()` to the entity, which is an abstract class, all defined children ignore previously specified `modelBuilder.HasDefaultSchema()`.
Although I only checked with PostgreSQL, I've tried to debug this and I'm pretty sure it should be reproducible with any DBMS.

### Minimal repro code
```C#
using Microsoft.EntityFrameworkCore;

public abstract class SomeEntity { public int Id { get; set; } }
public class SomeChildEntity : SomeEntity { }
public class OtherEntity { public int Id { get; set; } }

public class TestContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseNpgsql("Host=localhost;Port=49153;Database=test;Username=postgres;Password=postgrespw");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("test_schema");
        modelBuilder.Entity<SomeEntity>().UseTpcMappingStrategy();
        modelBuilder.Entity<SomeChildEntity>();
        modelBuilder.Entity<OtherEntity>();
    }
}
```
Then run migration
```C#
new TestContext().Database.EnsureCreated();
```
The result of this code should be the following structure, where `SomeChildEntity` is created in database's default schema instead of specified "test_schema", while `OtherEntity` is created in expected schema 

![image](https://user-images.githubusercontent.com/18244287/212032858-7f133460-ac32-4d4d-8047-e862f976ee99.png)

### Include provider and version information

EF Core version: 7.0.2
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: net7.0

**Comment by roji** [comment] 2023-01-12 09:51
Duplicate of #29899

**Closed** 2023-01-12 12:51 UTC
Labels: customer-reported
