### ISSUE TITLE
System.InvalidOperationException: 'Unable to translate set operation after client projection has been applied. Consider moving the set operation before the last 'Select' call.'

### ISSUE THREAD

**Issue by abeerabdu** [dotnet/efcore#30942] opened 2023-05-21 10:02 UTC
EF Core version: 6.0.16
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Win 10
 

After migrating from EF4 to EF6  and .NET 4 to .NET 6 we get the above error from this query
 

```c#
public IEnumerable<UserTaskView> GetUserTopTasks(IUnitOfWork unitOfWork, int admId, int ngoId, int maxNo = 10)
        {  
            var pagination = new DeadlinePaginationView { rows = maxNo };
            var tasksQry = unitOfWork.WorkplanSubactivity.GetAssignedTasksQuery(ngoId, admId);
            var mealsQry = unitOfWork.MealActivity.GetAssignedTasksQuery(ngoId, admId);
            var query = tasksQry.Union(mealsQry);
            var data = query.OrderBy(GetOrderByExpresstion(pagination.sortBy, pagination.descending))
                            .Skip(pagination.offset).Take(pagination.rows).ToList()
                            .Select(row =>
                            {
                                var result = unitOfWork.Admin.GetUserTaskModel(row);
                                return result;
                            }).ToList();
            return data;
        }
```

**Comment by ajcvickers** [comment] 2023-05-26 12:06
Duplicate of #16298. Make sure to vote (👍) for that issue.

**Closed** 2023-05-31 18:38 UTC
Labels: closed-duplicate, customer-reported
