### ISSUE TITLE
scaffold-dbcontext hangs in PM Console [Offline]

### ISSUE THREAD

**Issue by DreamU1952** [dotnet/efcore#24472] opened 2021-03-22 16:25 UTC
I create a new .Net 5.0 console solution, within VS v16.8.4,  and install two packages:

Microsoft.EntityFrameworkCore.SqlServer   (5.0.4)
Microsoft.EntityFrameworkCore.Tools   (5.0.4)

Then I execute the following command which produces verbose output shown below after which the PM is hung, there are no output files and Package Manager Console on the Tools menu remains grayed out.

PM> scaffold-dbcontext -provider Microsoft.EntityFrameworkCore.SqlServer -connection "Data Source=sqldevi\devi;Initial Catalog=chela;Integrated Security=true;Pooling=false;Application Name=EIS" -OutputDir Entities –Context Chela  –UseDatabaseNames –Tables CardReader -Verbose
Using project 'TestScaffoldNet50'.
Using startup project 'TestScaffoldNet50'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\VS\_Rewrite\_Test\TestScaffoldNet50\bin\Debug\net5.0\TestScaffoldNet50.deps.json --additionalprobingpath C:\Users\jimt\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\DevExpress 20.2\.NET Core Desktop Libraries\Offline Packages" --additionalprobingpath "C:\Program Files (x86)\DevExpress 20.2\Components\Offline Packages" --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\VS\_Rewrite\_Test\TestScaffoldNet50\bin\Debug\net5.0\TestScaffoldNet50.runtimeconfig.json C:\Users\jimt\.nuget\packages\microsoft.entityframeworkcore.tools\5.0.4\tools\netcoreapp2.0\any\ef.dll dbcontext scaffold "Data Source=sqldevi\devi;Initial Catalog=chela;Integrated Security=true;Pooling=false;Application Name=EIS" Microsoft.EntityFrameworkCore.SqlServer --json --output-dir Entities --context Chela --table CardReader --use-database-names --verbose --no-color --prefix-output --assembly C:\VS\_Rewrite\_Test\TestScaffoldNet50\bin\Debug\net5.0\TestScaffoldNet50.dll --startup-assembly C:\VS\_Rewrite\_Test\TestScaffoldNet50\bin\Debug\net5.0\TestScaffoldNet50.dll --project-dir C:\VS\_Rewrite\_Test\TestScaffoldNet50\ --language C# --working-dir C:\VS\_Rewrite\_Test\TestScaffoldNet50 --root-namespace TestScaffoldNet50

NOTE WELL: if I close down Visual Studio, the output files appear in the Entities folder using File Explorer! Then when I re-open Visual Studio the folder appears and the table CardReader is properly scaffolded. 

What is causing the hang? 
1) I get the same hang if I try using the Preview 6.0 versions of the packages so it is not a version issue.
2) I am not running a Virus scanner so that is not getting in the way.
3) When I run Fiddler I see these tunnels:
   > dc.services.visualstudio.com:443
   > dc.services.visualstudio.com:443
   > browser.pipe.aria.microsoft.com:443
   > vortex.data.microsoft.com:443

I am suspicious of these tunnels. Is PM trying to 'phone home'? I am running in a secure environment which is not connected to the internet, i.e. offline. If PM is hanging waiting for an internet response that is never going to happen. By the same token, if you try to duplicate my experience you must do it offline. Do not let my suspicions bias you - perhaps those tunnels are created by some other background process in Visual Studio and not relevant to this issue.

**Comment by ErikEJ** [comment] 2021-03-22 16:28
What happens if you use "dotnet ef dbcontext scaffold" from a command line prompt?

**Comment by DreamU1952** [comment] 2021-03-22 17:27
Help me craft the correct command - I am not familiar with using the command line prompt. Here is my command line session and help does not list a command option with 3 arguments (which are not options). The command you listed above simply returns with 'Could not execute because the specified command or file was not found'.

C:\Program Files\dotnet>dotnet.exe

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

**Comment by ErikEJ** [comment] 2021-03-23 14:10
https://docs.microsoft.com/en-us/ef/core/cli/dotnet#installing-the-tools 

https://docs.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-dbcontext-scaffold

**Comment by DreamU1952** [comment] 2021-03-23 19:53
I managed to get the CLI command 'dotnet ef dbcontext scaffold' working, using the same connection string, specifically: 

C:\VS\_Rewrite\_Test\TestScaffoldNet50>dotnet ef dbcontext scaffold "Data Source=sqldevi\devi;Initial Catalog=chela;Integrated Security=true;Pooling=false;Application Name=EIS" Microsoft.EntityFrameworkCore.SqlServer -t InfoPhone -t InfoRequest -o Entities1 -f

Both tables were scaffolded in the Entities1 folder as expected. But the CLI did not hang as Package Manager does. I assume your point was to verify I have the correct environment and correct command which has been proven. This still leaves us with the question of why does Package Manager hang and the CLI command does not?

**Comment by ajcvickers** [comment] 2024-01-04 09:19
@DreamU1952 Does this still happen for you with the latest Visual Studio installed?

**Comment by ajcvickers** [comment] 2024-01-17 17:52
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-01-17 17:52 UTC
Labels: type-bug, propose-close, poachable, customer-reported, area-tools, punted-for-6.0
