### ISSUE TITLE
EF Migrations - complex data updates

### ISSUE THREAD

**Issue by danielbecroft** [dotnet/efcore#16613] opened 2019-07-16 07:27 UTC
I'm trying to find a way to apply complex data changes through an EF Migration process. An example of what I would like to be able to do is below:

```c#
var orders = _context.Orders.Where(_ => SalesTax < 0);

foreach (var order in orders)
{
    order.SalesTax = CalculateSalesTax(order);
}

_context.SaveChanges();
```

A different use case could be for setting up complicated static data changes/relationships.

The generated `Migration` class only has a `MigrationBuilder` parameter, when I really need access to a `DbContext` instance.

Am I missing something, or is this not an easy task to achieve with migrations? What's the best approach for dealing with these types of changes?

**Comment by n00bje** [comment] 2019-07-16 13:09
You can instantiate the DbContext yourself and it'll work.
However, you have to be aware that changing the Order entity or SalesTax column in the future might break your migration!

**Comment by ajcvickers** [comment] 2019-07-17 16:42
Note for triage: likely a duplicate of #5642

**Closed** 2022-10-16 14:30 UTC
Labels: customer-reported
