### ISSUE TITLE
EF.Functions.ILike does not work with InMemoryDatabase

### ISSUE THREAD

**Issue by olivierr91** [dotnet/efcore#10353] opened 2017-11-20 17:03 UTC
EF.Functions.ILike does not work as expected with InMemoryDatabase:

```
dbContext.Users.Add(new User("username"));
dbContext.Users.Where(u => EF.Functions.ILike(u.Username, $"%username%")).Count(); //=> 1
dbContext.Users.Where(u => EF.Functions.ILike(u.Username, $"%useRname%")).Count(); //=> 0
```

The ILike function works correctly when using the PostgreSQL implementation.

**Comment by roji** [comment] 2017-11-20 18:04
@orobert91 can you please open this in https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues and close this one? It's a totally Npgsql-specific issue. I'll try to fix this for the upcoming 2.0.1 release.

**Comment by orobert91** [comment] 2017-11-20 18:45
I think you misread the title, it is an issue with InMemoryDatabase. I just said that the function was working in PostgreSQL, the issue is with InMemoryDatabase.

**Comment by roji** [comment] 2017-11-20 19:24
You're issue may be when working with InMemoryDatabase, but the ILike function comes from the Npgsql provider (Npgsql.EntityFrameworkCore.PostgreSQL), and not from EF Core. The Npgsql provider is the one providing the C# implementation - the one executed on all providers *except* for PostgreSQL, and the one that seems to have a bug.

So please move this issue to Npgsql.EntityFrameworkCore.PostgreSQL.

**Comment by orobert91** [comment] 2017-11-20 19:28
Ok I understand, I have moved the issue to https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/267

**Closed** 2022-10-16 11:59 UTC
Labels: closed-external
