### ISSUE TITLE
Way Faster Inserts

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/efcore#31310] opened 2023-07-19 14:18 UTC
Hi EFCore Team,
I've been using EFCore's ```SaveChanges``` to mass transfer ~100,000,000 records in batches of 1,000 rows.  SaveChanges takes about 1.2 seconds to insert 1,000 rows.

I just did a test using [EF Extensions Bulk Insert](https://entityframework-extensions.net/bulk-insert) and it takes between 0.05 and 0.09 seconds to do the inserts.  It is ridiculously faster!

Anyways, it would be great if EFCore naturally had a solution that was that fast.  It would certainly help raise it on the tech benchmarks as well.

**Comment by ErikEJ** [comment] 2023-07-19 14:25
Duplicate of https://github.com/dotnet/efcore/issues/27333

**Comment by roji** [comment] 2023-07-19 14:38
Yep, this is indeed on our radar. Closing as a duplicate of of #27333.

**Comment by roji** [comment] 2023-07-19 14:38
Duplicate of #27333.

**Closed by roji** 2023-07-19 14:38 UTC
Labels: customer-reported

**Comment by ajcvickers** [comment] 2023-07-19 14:41
@TonyValenti 

> It would certainly help raise it on the tech benchmarks as well.

Which benchmarks are you referring to, specifically?
