### ISSUE TITLE
Problem updating an entity in relational database

### ISSUE THREAD

**Issue by JayVansjalia** [dotnet/efcore#32377] opened 2023-11-21 14:29 UTC
I have the following entities:
```
public class WorkflowTemplate
{
    public string? Name { get; set; }
    public string? Description { get; set; }

    public List<TemplateStep>? WorkflowSteps { get; set; }
}

public class TemplateStep
{
    [ForeignKey("WorkflowTemplate")]
    public Guid WorkflowTemplateId { get; set; }
    [JsonIgnore]
    public WorkflowTemplate? WorkflowTemplate { get; set; }

    public ICollection<TemplateStepCondition>? Conditions { get; set; }
}

public class TemplateStepCondition
{
    public Guid TemplateStepId { get; set; }

    [JsonIgnore]
    public TemplateStep? TemplateStep { get; set; }

    public Guid ConditionId { get; set; }

    [JsonIgnore]
    public Condition? Condition { get; set; }

    public ConditionType ConditionType { get; set; }
}

public class Condition
{
    public string? Name { get; set; }
    public string? Description { get; set; }

    [JsonIgnore]
    public ICollection<TemplateStepCondition>? TemplateSteps { get; set; }
}
```
Now I am trying to update a WorkflowTemplate entity using EF Core, but I'm getting the following error:

The instance of entity type 'Condition' cannot be tracked because another instance with the key value '{Id: 0000000-0000-00000-000000}'(GUID changed by me) is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.

I have tried the following approach:

```
public void UpdateWorkflowTemplate(WorkflowTemplate updatedWorkflowTemplate)
{
   var existingTemplate = await _unitOfWork.WorkflowTemplates
                                           .GetByIdAsync(templateDetails.Id);

   _mapper.Map(templateDetails, existingTemplate);

   _unitOfWork.WorkflowTemplates.Update(existingTemplate);
   var result = _unitOfWork.Save();
 }
```

Please suggest the correct way to handle such situation and suggest best practice for updating entities with EF Core.

**Comment by ajcvickers** [comment] 2023-11-21 19:13
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-12-05 20:09
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-12-05 20:09 UTC
Labels: customer-reported
