### ISSUE TITLE
Why EF Core query with explicit Cultureinfo is not converted to SQL?

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/efcore#18234] opened 2019-10-05 07:30 UTC
I have found that `IQueryable` extension methods like `.ToLower(), .Contains()` with explicit `Cultureinfo` is not converted to SQL:

For example:

`_dbContext.Employees.Where(e => e.Name.Contains(serachString,StringComparison.InvariantCultureIgnoreCase)).ToList();`

The above query is not convert to SQL in EF Core 3.0.

The thrown Exception is as follows:

> The LINQ expression 'Where<ExceptionModel>( source: DbSet<ExceptionModel>, predicate: (e) => e.RequestedUrl.Length > 50 ? e.RequestedUrl.Substring( startIndex: 0, length: 48) + ".." : e.RequestedUrl.ToLower((Unhandled parameter: __InvariantCulture_0)).Contains( value: (Unhandled parameter: __requestedUrl_1), comparisonType: InvariantCultureIgnoreCase) && e.ControllerName.ToLower((Unhandled parameter: __InvariantCulture_0)).Contains( value: (Unhandled parameter: __controllerName_2), comparisonType: InvariantCultureIgnoreCase) && e.ActionName.ToLower((Unhandled parameter: __InvariantCulture_0)).Contains( value: (Unhandled parameter: __actionName_3), comparisonType: InvariantCultureIgnoreCase) && e.ExceptionMessage.Length > 50 ? e.ExceptionMessage.Substring( startIndex: 0, length: 48) + ".." : e.ExceptionMessage.ToLower((Unhandled parameter: __InvariantCulture_0)).Contains( value: (Unhandled parameter: __exceptionMessage_4), comparisonType: InvariantCultureIgnoreCase) && e.InnerExceptionMessage != null ? e.InnerExceptionMessage.Length > 50 ? e.InnerExceptionMessage.Substring( startIndex: 0, length: 48) : e.InnerExceptionMessage : "No Inner Exception".ToLower((Unhandled parameter: __InvariantCulture_0)).Contains( value: (Unhandled parameter: __innerExceptionMessage_5), comparisonType: InvariantCultureIgnoreCase) && True)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

Note: Exception is not for the query mention in the question. This is for another model with same type of query where `Cultureinfo` is provided explicitly in `.ToLower()` and `.Contains()`. methods.

**Comment by ajcvickers** [comment] 2019-10-07 16:27
Duplicate of #1222

**Closed** 2022-10-16 14:47 UTC
Labels: customer-reported
