### ISSUE TITLE
Add support for logical XOR

### ISSUE THREAD

**Issue by OronDF343** [dotnet/efcore#34736] opened 2024-09-23 13:16 UTC
Currently, EF Core does not support logical XOR.

For example, let's say I want to find all order items not deleted that are missing `SerialNumber` or `Barcode`, but not both. This query fails to compile:

```C#
db.OrderItems.Where(i => !i.IsDeleted && (i.SerialNumber != null ^ !string.IsNullOrEmpty(i.Barcode)))
```

```
System.InvalidOperationException: The LINQ expression 'DbSet<OrderItem>()
    .Where(d => !(d.IsDeleted) && d.SerialNumber != null ^ !(string.IsNullOrEmpty(d.Barcode)))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

Instead I have to write it out like this:

```C#
db.OrderItems.Where(i => !i.IsDeleted && (i.SerialNumber != null && string.IsNullOrEmpty(i.Barcode) || i.SerialNumber == null && !string.IsNullOrEmpty(i.Barcode)))
```

It would be nice if EF Core did this translation automatically.

**Comment by roji** [comment] 2024-09-23 20:48
Duplicate of #16645

**Comment by roji** [comment] 2024-09-23 20:48
This was done for 9.0 - give the rc.1 version a try!

**Closed** 2024-09-23 20:48 UTC
Labels: customer-reported
