### ISSUE TITLE
Count with conditions can be translated to Sum operation

### ISSUE THREAD

**Issue by lgirma** [dotnet/efcore#19318] opened 2019-12-14 05:43 UTC
## Problem

In entity framework core 3.0 and above, a `Count` operation with condition inside can't be translated. A typical example could be:

```
.Count(u => u.IsLocked)
```

This will throw `System.InvalidOperationException` suggesting explicit client side evaluation.

## Possible Solution

The count with condition expression can be translated to a sum operation. So the following LINQ query:

```
.Count(<condition>)
```

can be translated into:

```
SELECT 
    SUM(CASE WHEN <condition> THEN  1 ELSE  0 END)
```

The `SUM` operation can also be changed to `COUNT` by just replacing the constant `0` with `null`

## Concrete Example

As a real-world example, consider the following LINQ query (which today will not be translated)

```
_context.Users
    .GroupBy(u => 1)
    .Select(g => new {
        LockedUsers = g.Count(u => u.IsLocked)
    });
```

can be translated to

```
SELECT 
    SUM(CASE WHEN u.IsLocked = 1 THEN  1 ELSE  0 END) LockedUsers 
FROM users u
```

**Comment by smitpatel** [comment] 2019-12-14 09:42
Duplicate of #18836

**Closed** 2022-10-16 18:01 UTC
Labels: closed-duplicate, customer-reported
