### ISSUE TITLE
Question: Advanced Monitoring

### ISSUE THREAD

**Issue by yahorsi** [dotnet/efcore#17029] opened 2019-08-08 12:16 UTC
Hi Guys,

Is that currently possible to monitor EF query compilation using diagnostics source?
Query compilation could take quite a lot of time and it would be good to see such stats in e.g. Application Insights, and that might be possible only if EF exposes such events.

PS:
If there are other long activities besides open/close connection and running sql commands it would be great to have events for them too.

Thanks

**Comment by ajcvickers** [comment] 2019-08-09 16:26
@yahorsi Do the events in `Microsoft.EntityFrameworkCore.Diagnostics.CoreEventId` and `Microsoft.EntityFrameworkCore.Diagnostics.RelationalEventId` cover what you need?

**Comment by ajcvickers** [comment] 2019-08-16 16:13
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:34 UTC
Labels: closed-could-not-reproduce, customer-reported
