### ISSUE TITLE
ValueGeneratedOnAdd on a DateTime throws on inset

### ISSUE THREAD

**Issue by plauriola** [dotnet/efcore#8577] opened 2017-05-24 19:43 UTC
### The issue
An have an entity `Client` with a property `FirstCreated` of type `DateTime`.
I tried using the Fluent API `.ValueGeneratedOnAdd();` and the Attribute API `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]` to have the current date `DateTime.Now` to be used automatically upon insert.

Save changes will throw the following exception: 
```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'FirstCreated', table 'ESJ_PriceManagement.dbo.Clients'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__26.MoveNext()
```

### Steps to reproduce
Here a sample code that we be easily wired up and tested:
```
public class Client
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Required]
    [MaxLength(16)]
    public string ClientCode { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public DateTime FirstCreated { get; set; }

    //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    //public DateTime LastUpdated { get; set; }
}
public class PriceManagementContext : DbContext
{
   public DbSet<Client> Clients { get; set; }
}

public class ClientRepository
{
    private readonly PriceManagementContext _context;

    //Inject DbContext

    public async Task TestInsert(CancellationToken ct)
    {
        var newClient = new Client
        {
            ClientCode = "Test"
        };
        newClient = await _context.Clients.AddAsync(newClient, ct);
        await _context.SaveChangesAsync(ct); //This will throw the exception
    }
}
```

### Further technical details
EF Core version: v1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer v1.1.2
Operating system: Windows 10
IDE: Visual Studio 2017

I created the DB with Migrations from package: Microsoft.EntityFrameworkCore.Tool v1.1.1

In my actual project, this use case is separated in 3 projects like follow:
1. NetStandard1.4 library 1 (contains the entities and other interfaces)
2. NetStandard1.4 library 2 (contains the DbContext, repository implementation and Migrations classes)
3. .Net Core Console app (will use all of the above to do the required processing)
I'm using .Net Core v1.1

### More

The issue also exist for `[DatabaseGenerated(DatabaseGeneratedOption.Computed)]` or `.ValueGeneratedOnAddOrUpdate();` but it's a bit different.
In this case if you try to feed it a value (IE: `DateTime.Now`) it will throw an exception that the Property is supposed to be ReadOnly. If you it leave it empty, you get the same exception as the `.ValueGeneratedOnAdd();`

**Comment by ajcvickers** [comment] 2017-05-25 16:43
@plauriola Are you trying to have DateTime.Now set automatically just before the new entity is sent to the database? Or are you trying to setup the database column to have a default constraint that generates the current date/time?

If it's the former, then there isn't really a way to do this automatically on EF Core. You could use a value generator, but it would generate the value when the entity is added to the context, not when it is saved. So the best bet would be to override SaveChanges and do it there.

If it's the latter, then look at calling HasDefaultValueSql for the property in OnModelCreating.

**Comment by ajcvickers** [comment] 2017-06-02 18:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:06 UTC
Labels: closed-could-not-reproduce
