### ISSUE TITLE
Navigations: Projected collection navigations tracking/fixup issues.

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#7569] opened 2017-02-07 19:15 UTC
Given the following query:
```c#
var results
    = context.Customers
        .Where(c => c.CustomerID == "ALFKI")
        .Select(c => c.Orders);
```
we would expect the Orders to be tracked, but they are not.

Additionally, given this variation:
```c#
var results
    = context.Customers
        .Where(c => c.CustomerID == "ALFKI")
        .Select(c => new { c, c.Orders });
```
the Customer is tracked and its Orders collection is populated. But:
- The inverse nav-prop (Order.Customer) is null.
- The Orders are not being tracked.

**Comment by maumar** [comment] 2017-05-23 01:49
dupe of #7131

**Closed by maumar** 2017-05-23 01:49 UTC
