### ISSUE TITLE
Owned entity types - EF creates very inefficient SQL

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [dotnet/efcore#18954] opened 2019-11-17 10:23 UTC
I want to split an entity with a lot of columns into a few smaller sub-entities for code clarity. Owned entity types seem to be perfect for this, and they seem to work as intended, however, the generated SQL is surprisingly inefficient.

### Steps to reproduce

Models:
```csharp
public class Device {
    [Key]
    public string Id { get; private set; }
    
    [Required]
    public string Name { get; private set; }
    
    [Required]
    public DeviceBasicStatistics BasicStatistics { get; } = new DeviceBasicStatistics();
}

public class DeviceBasicStatistics {
    public long ReportCount { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime? LastReport { get; set; }
}
```

DbContext:
```sql
public DbSet<Device> Devices { get; set; }

...


builder
    .Entity<Device>()
    .OwnsOne(d => d.BasicStatistics);
```

(With this, the Device table has such columns: `Id`, `Name`, `BasicStatistics_ReportCount`, `BasicStatistics_LastReport`, which is expected.)

Execute a simple `_dbContext.Devices.ToList()` query. The results are OK, but the executed SQL is puzzling to me.
```sql
SELECT "d"."Id", "d"."LocationId", "d"."Name", "d"."Type", "t"."Id", "t"."BasicStatistics_DeviceLastReport", "t"."BasicStatistics_DeviceReportCount"
FROM "Devices" AS "d"
LEFT JOIN (
    SELECT "d0"."Id", "d0"."BasicStatistics_DeviceLastReport", "d0"."BasicStatistics_DeviceReportCount", "d1"."Id" AS "Id0"
    FROM "Devices" AS "d0"
    INNER JOIN "Devices" AS "d1" ON "d0"."Id" = "d1"."Id"
    WHERE "d0"."BasicStatistics_DeviceReportCount" IS NOT NULL
) AS "t" ON "d"."Id" = "t"."Id"
```

1. It is doing two SELECT with two JOIN on itself, which is extremely inefficient?.
2. There is a strange `WHERE "d0"."BasicStatistics_DeviceReportCount" IS NOT NULL` clause. `BasicStatistics_DeviceReportCount` is non-nullable, so why would EF check that?
3. Since it is a one-to-one relationship within the same table, I would expect the query to be just:
```sql
SELECT "d"."Id", "d"."LocationId", "d"."Name", "d"."Type", "t"."Id", "d"."BasicStatistics_DeviceLastReport", "d"."BasicStatistics_DeviceReportCount"
FROM "Devices" AS "d"
```

Not sure if this is a bug, limitation, or expected behavior, but it sure looks weird to me.

### Further technical details
EF Core version: 3.1-preview3
Database provider: (e.g. Microsoft.EntityFrameworkCore.Sqlite)
Target framework: (e.g. .NET Core 3.1-preview3)
Operating system: Windows 10 1903

**Comment by ajcvickers** [comment] 2019-11-18 19:32
Duplicate of #18299

**Closed** 2022-10-16 14:56 UTC
Labels: closed-duplicate, customer-reported
