### ISSUE TITLE
.NET Core Geometry Sample

### ISSUE THREAD

**Issue by hn1** [dotnet/efcore#19065] opened 2019-11-25 22:16 UTC
Your code doesn't even compile!!!!!!!!!!!!!

**Comment by roji** [comment] 2019-11-26 18:57
@hn1 can you please point to the sample that doesn't compile and include the error you're seeing?

**Comment by hn1** [comment] 2019-11-26 21:34
there is only 1 code snippet on that page! and that is the one that throws
exceptions on the transformations.

**Comment by hn1** [comment] 2019-11-26 21:35
there is only 1 code snippet on that page! and that is the one that throws exceptions on the transformations.

**Comment by hn1** [comment] 2019-11-26 21:35
Have you actually run that code?

**Comment by roji** [comment] 2019-12-02 10:49
@hn1 please post a link to the page with the sample, as well as the compilation error you're seeing.

**Comment by ajcvickers** [comment] 2019-12-09 18:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by bricelam** [comment] 2020-01-02 23:25
Here's a sample based on EF Core 2.2: https://github.com/efcore/EFCoreDemos/tree/master/spatial

**Closed** 2022-10-16 14:58 UTC
Labels: closed-could-not-reproduce, customer-reported
