### ISSUE TITLE
dotnet ef migrations add - failing the second time

### ISSUE THREAD

**Issue by ANGsol** [dotnet/efcore#25098] opened 2021-06-15 06:14 UTC
1) Working first migration:
dotnet ef migrations add Initial 

2) Second migration is failing:
dotnet ef migrations add FirstUpdate

### Include stack traces

```
System.ArgumentException: Argument isn't an array or generic List (Parameter 'memberInfo')
   at Npgsql.EntityFrameworkCore.PostgreSQL.Utilities.ReferenceNullabilityDecoder.IsArrayOrListElementNonNullable(MemberInfo memberInfo) in Npgsql.EntityFrameworkCore.PostgreSQL.dll:token 0x6000277+0x1e
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlTypeMappingSource.FindMapping(IProperty property) in Npgsql.EntityFrameworkCore.PostgreSQL.dll:token 0x60002d8+0x35
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Property.<>c.<get_TypeMapping>b__78_0(IProperty property) in Microsoft.EntityFrameworkCore.dll:token 0x60029d8+0x0
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory) in Microsoft.EntityFrameworkCore.dll:token 0x6001c39+0x11
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Property.get_TypeMapping() in Microsoft.EntityFrameworkCore.dll:token 0x600132c+0x2f
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Property.Microsoft.EntityFrameworkCore.Metadata.IReadOnlyProperty.FindTypeMapping() in Microsoft.EntityFrameworkCore.dll:token 0x600134e+0x0
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.FindRelationalTypeMapping(IReadOnlyProperty property) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x60001fc+0x0
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.GetColumnType(IReadOnlyProperty property) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x60001c1+0xc
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.AddDefaultMappings(RelationalModel databaseModel, IEntityType entityType) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x60011a3+0x95
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.Create(IModel model, IRelationalAnnotationProvider relationalAnnotationProvider) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x60011a2+0x1c
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.Add(IModel model, IRelationalAnnotationProvider relationalAnnotationProvider) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x60011a1+0x0
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelRuntimeInitializer.InitializeModel(IModel model, Boolean preValidation) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x60013d3+0x16
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.<>c.<Initialize>b__4_0(ValueTuple`4 args) in Microsoft.EntityFrameworkCore.dll:token 0x6002c15+0x52
   at Microsoft.EntityFrameworkCore.Infrastructure.AnnotatableBase.<>c__30`2.<GetOrAddRuntimeAnnotationValue>b__30_0(String n, ValueTuple`3 t) in Microsoft.EntityFrameworkCore.dll:token 0x6002bef+0x0
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument) in System.Collections.Concurrent.dll:token 0x60000d4+0x4f
   at Microsoft.EntityFrameworkCore.Infrastructure.AnnotatableBase.GetOrAddRuntimeAnnotationValue[TValue,TArg](String name, Func`2 valueFactory, TArg factoryArgument) in Microsoft.EntityFrameworkCore.dll:token 0x6001958+0x2e
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger) in Microsoft.EntityFrameworkCore.dll:token 0x6001a88+0x3c
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language) in Microsoft.EntityFrameworkCore.Design.dll:token 0x60002e0+0x17a
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace) in Microsoft.EntityFrameworkCore.Design.dll:token 0x60003bd+0xa5
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace) in Microsoft.EntityFrameworkCore.Design.dll:token 0x6000337+0xc
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0() in Microsoft.EntityFrameworkCore.Design.dll:token 0x60005e2+0x0
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0() in Microsoft.EntityFrameworkCore.Design.dll:token 0x60005f4+0x0
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action) in Microsoft.EntityFrameworkCore.Design.dll:token 0x6000579+0xc
Argument isn't an array or generic List (Parameter 'memberInfo')
```

### Include provider and version information

EF Core version: 6.0.0-preview.4.21253.1
Database provider: NpgSql 6.0.0-preview4
Target framework: (e.g. .NET 6.0.0-preview.4.21253.5)
Operating system: Windows 10
IDE: Visual Studio 2019 16.10.1

**Comment by AndriySvyryd** [comment] 2021-06-15 07:36
Can you create and share a small repro project that shows this?

**Comment by roji** [comment] 2021-06-15 09:38
Duplicate of https://github.com/npgsql/efcore.pg/issues/1839

**Comment by roji** [comment] 2021-06-15 09:39
This is a bug in the preview4 version of the Npgsql provider - it's already been fixed for preview5. In the meantime you can use the [daily builds](https://www.npgsql.org/doc/installation.html#daily-builds).

**Comment by ANGsol** [comment] 2021-06-15 09:42
thank you for your support

**Closed** 2022-10-16 19:37 UTC
Labels: closed-external, customer-reported
