### ISSUE TITLE
Filtered include, and then include related entity loses the filter?

### ISSUE THREAD

**Issue by azygis** [dotnet/efcore#29010] opened 2022-09-07 12:34 UTC
### Question

In our model we have setup a TPH inheritance for several of our entities. We've hit some unexpected behaviour (at least my mind) when it comes to filtering the includes.

Our use case is:
Get object set with all locations and groups, but only non-anonymous. In each of these locations and/or groups the related navigational property should be filled with all related entities regardless of whether it has the name or not.

```C#
static Task<T> GetObjectSetAsync<T>(IQueryable<T> set, Expression<Func<T, bool>> predicate) where T : ObjectSet =>
    set.Where(predicate)
        .Include(x => x.LocationsAndGroups.Where(y => y.Name != null)).ThenInclude((EnvironmentalLawObject x) => ((Location) x).Groups)
        .Include(x => x.LocationsAndGroups.Where(y => y.Name != null)).ThenInclude((EnvironmentalLawObject x) => ((Group) x).Locations)
        .AsSplitQuery()
        .FirstAsync();
```

After running `var objectSet = await GetObjectSetAsync(_context.ObjectSets, x => x.Id == 1)`, I would expect to **not** have any entities with `Name` being `null` directly in `objectSet.LocationsAndGroups`, **but** still have such anonymous entities in either `Location` or `Group` inside the collection.

Sadly, we do get the anonymous locations not only in related entities, but also directly in `objectSet.LocationsAndGroups`. For now we're filtering those out in memory as well.

The question is, is this behavior by design, or can we do something about it?

### Provider and version information

EF Core version: 6.0.6
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL (6.0.5)
Target framework: .NET 6.0
Operating system: irrelevant, same behavior in both docker container and on Windows 10/11.

**Comment by ajcvickers** [comment] 2022-09-12 11:31
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by azygis** [comment] 2022-09-12 12:47
Okay, I did expect as much, umderstandable. We will try to create a repro project this week with entity structure as close to ours and as minimal as possible.

**Comment by ajcvickers** [comment] 2022-09-26 16:48
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-09-26 16:48 UTC
Labels: customer-reported
