### ISSUE TITLE
Group by bug: records are grouped on client

### ISSUE THREAD

**Issue by sdanyliv** [dotnet/efcore#4701] opened 2016-03-04 13:11 UTC
The following unit test passes correctly but result of group by statement is calculated on client:

``` csharp
//Northwind

        [Test]
        [Category("Grouping")]
        public void GroupByCalculatedTest()
        {
            var result =
                from o in db.Orders
                group o by o.Freight > 50 ? o.Freight > 100 ? "expensive" : "average" : "cheap"
                into g
                select g;
            var list = result.ToList();
            Assert.AreEqual(3, list.Count);
        }
```

Gnerated SQL (formatted):

``` sql
SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[Freight], [o].[OrderDate], 
  [o].[RequiredDate], [o].[ShipAddress], [o].[ShipCity], [o].[ShipCountry], [o].[ShipName], 
  [o].[ShipPostalCode], [o].[ShipRegion], [o].[ShipVia], [o].[ShippedDate]
FROM [Orders] AS [o]
```

In pessimistic case It may take all server's memory.

"EntityFramework.Core" version="7.0.0-rc1-final"
"Remotion.Linq" version="2.0.2"

**Comment by rowanmiller** [comment] 2016-03-04 17:46
Duplicate of https://github.com/aspnet/EntityFramework/issues/2341

**Closed** 2022-10-16 09:31 UTC
