### ISSUE TITLE
Data Section of appsettings.json

### ISSUE THREAD

**Issue by mikes-gh** [dotnet/efcore#5742] opened 2016-06-13 10:48 UTC
### Steps to reproduce

Open appsettings.json
### The issue

Would expect to see

ConnectionStrings section instead of

```
"Data": {
        "default": {
            "ConnectionString": "Server=someserver=somedatabase;Trusted_Connection=True;MultipleActiveResultSets=true"
        },
        "aes": {
            "ConnectionString": "Server=anotherserver=anotherdatabase;Trusted_Connection=True;MultipleActiveResultSets=true"
        }
      },
```
### Further technical details

win 7 x64
rc2
vs 2015 update 2
### Comments

I am starting to use strongly typed config.
The current structure of `Data` section of Appsettings has a hierarcy that doesn't lend itself to easy config object.

I want to do

```
"ConectionStrings": {
    "somedatabase" : Server=someserver=somedatabase;Trusted_Connection=True;MultipleActiveResultSets=true"
    "anotherdatabase": ConnectionString": "Server=anotherserver=anotherdatabase;Trusted_Connection=True;MultipleActiveResultSets=true"
}
```

This seems simpler to me but I am concerned about going against convention.
Is this a valid direction or will it work against me later as efcore develops.

**Comment by divega** [comment] 2016-06-13 15:29
@mikes-gh There is a bug in the item template for appsettings.config file in Preview1 tooling: https://github.com/aspnet/Templates/issues/589. The result is that doing Add New Item -> ASP.NET Configuration File creates a file with the outdated convention, i.e. "Data":"DefaultConnection":"ConnectionString". If that is what you are seeing please just hand edit the file to reflect the new convention?

**Comment by divega** [comment] 2016-06-13 15:32
Closing as duplicate of https://github.com/aspnet/Templates/issues/589. Please create a new issue in the Templates repo or the Configuration repo if I have failed to address your concerns. Note that this is not an EF issue.

**Comment by mikes-gh** [comment] 2016-06-13 17:03
@divega Sorry I missed that - thanks for the pointer

**Closed** 2022-10-16 09:44 UTC
