### ISSUE TITLE
MSSQL. Translation of DateTime.AddDays(double)

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#13928] opened 2018-11-09 17:47 UTC
I think, your translation of DateTime.AddDays to SQL [for MSSQL] is incorrect.

I not tested, just looked to code:

https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerDateAddTranslator.cs

**MSSQL (2016)**

Query "select DATEADD(DAY, 1.5, CONVERT(datetime,'01.01.2000'))" returns "2000-01-02 00:00:00.000"

[DateTime.AddDays(Double) Method](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.adddays?view=netframework-4.7.2)

**Remarks**
This method does not change the value of this DateTime. Instead, it returns a new DateTime whose value is the result of this operation.

The fractional part of value is the fractional part of a day. **For example, 4.5 is equivalent to 4 days, 12 hours, 0 minutes, 0 seconds, 0 milliseconds, and 0 ticks**.

**Comment by smitpatel** [comment] 2018-11-09 18:31
Duplicate of #11794

**Comment by dmitry-lipetsk** [comment] 2018-11-10 07:17
@smitpatel 

Ok, you knew about this problem.

But why you not added note about it in source code?

This small comment could prevent a copying of this issue into other providers :)

[FirebirdSql.EntityFrameworkCore.Firebird.BLA-BLA-BLA.FbDateAddTranslator](https://github.com/FirebirdSQL/NETProvider/blob/2e0a8895a0b1659c9940edeccbd27aebebd69c1e/Provider/src/FirebirdSql.EntityFrameworkCore.Firebird/Query/ExpressionTranslators/Internal/FbDateAddTranslator.cs
)

**Closed** 2022-10-16 13:39 UTC
Labels: customer-reported

**Comment by dmitry-lipetsk** [comment] 2025-06-16 10:46
![Image](https://github.com/user-attachments/assets/49d4cff2-15f9-410c-bee5-cd226608054d)

👍
