### ISSUE TITLE
Unable to Add code first migration

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#30229] opened 2023-02-08 10:11 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-Add-code-first-migration/10267759)._

---
[regression]
When i try to add a new code first migration (EF core), i get an error. 
Since my last Visual studio update, executing  Entity framework core Add-migration command give and error 
(See screenshoot)

---
#### Feedback Bot on 2/2/2023, 01:58 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2023-02-08 10:14
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-02-22 15:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-02-22 15:10 UTC
Labels: customer-reported
