### ISSUE TITLE
Question: Enterprise Library - Transient Fault Handling Application Block Support

### ISSUE THREAD

**Issue by pauldalyii** [dotnet/efcore#2004] opened 2015-04-07 22:52 UTC
Will the [Transient Fault Handling Application Block](https://msdn.microsoft.com/library/cc467894.aspx) be supported in EF7?

Are there other recommended approaches to this type of functionality in EF7 (ex; [Polly](https://github.com/michael-wolfenden/Polly/))

The patterns & practices team mentioned that EF has this (or will have this) baked in.
https://twitter.com/pauldalyii/status/585576891274375168

**Comment by divega** [comment] 2015-04-15 17:20
We eventually plan to add similar functionality to the connection resiliency in EF6.x, e.g. [automatic connection retries for SQL Azure](https://msdn.microsoft.com/en-us/dn456835) and possibly [handling of commit failures](https://msdn.microsoft.com/en-us/dn630221). We have #237 in the backlog to track this.

FWIW, it should be possible to use general purpose transient failure handling code such as the TFHAB or Polly (thanks for the link, looks interesting!) with EF in simple scenarios, e.g. if the block of code you retry includes a whole "unit of work" inside, i.e. the opening of the connection, querying, changes applied to entities and the call to `SaveChanges()`. 

The work that we did in connection resiliency in EF6.x requires a more complex interaction between the retrying logic and EF but allows for seamless usage because we can make individual operations more reliable, e.g. we transparently retry queries  (we need to keep retrying until we get a full successful execution without interruptions and which point we return the query results have been buffering), and we can control the boundaries of transactions (we know that if a failure happens during the transaction in `SaveChanges()` we only need to retry `SaveChanges()` as opposed to the whole unit of work). 

Hope this answers your question. I will go ahead and close the issue as a duplicate of #237 but let us know if you have any more feedback about this.

**Closed** 2022-10-16 08:54 UTC
