### ISSUE TITLE
Changes to derived entity property values are not updating, only parent properties.

### ISSUE THREAD

**Issue by daveajrussell** [dotnet/efcore#4941] opened 2016-03-31 13:01 UTC
Hi, 

We're experiencing an issue when trying to update a derived entity. Taking a look at the entity in the change tracker we can see the values we're expecting to see, but when SaveChanges is called, only the parent entity properties are in the generated update statement.

Our setup is;
- Register EFDbContext in Startup
- EFDbContext inherits IdentityDbContext
- Consume it from a controller action
- Try to update a derived entity

E.g. we have a parent class `CustomPageContent`:

``` csharp
public class CustomPageContent
{
        public int Id { get; set;} 
        public int DisplayOrder { get; set; }
        public int Type { get; set; }
}
```

and a child class `CustomPageContentText`:

``` csharp
public class CustomPageContentText : CustomPageContent 
{
        public string Content { get; set; }
}
```

Our code looks like (we do have a wrapper around EFDbContext, we're just using the raw context whilst we've been looking into this issue):

``` csharp
var textContent = _context.CustomPageContentTexts.FirstOrDefault(o => o.Id == 1);

textContent.DisplayOrder = 1;
textContent.Content = 'updated content';

_context.Update<CustomPageContentText>(textContent);
_context.SaveChanges();
```

When we call the update, we can see the following statement generated:

``` sql
exec sp_executesql N'SET NOCOUNT OFF;
UPDATE [CustomPageContent] SET [DisplayOrder] = @p1, [Type] = @p2
WHERE [Id] = @p0;
SELECT @@ROWCOUNT;
',N'@p0 int,@p1 int,@p2 int',@p0=1,@p1=1,@p2=1
```

Adding a derived entitiy seems to work fine, however.

**Comment by smitpatel** [comment] 2016-03-31 17:21
dupe of #4817 ?

**Comment by ajcvickers** [comment] 2016-03-31 17:47
Agreed that this is most likely a dupe of #4817 which was fixed yesterday.

**Comment by daveajrussell** [comment] 2016-03-31 18:22
Apologies fellas, seems I didn't look hard enough through the exisitng issues.

**Closed** 2022-10-16 09:34 UTC
