### ISSUE TITLE
Adding EF.Constant to prevent parameterization in query

### ISSUE THREAD

**Issue by Liero** [dotnet/efcore#31552] opened 2023-08-25 12:00 UTC
# What problem are you trying to solve?

"Query is fast in SSMS but slow in production" kind of performance issues, where query is parametrized by EF and SQL Server chooses  query execution plan suboptimal for concrete parameter value.

For example:

```sql
SELECT TOP(1000) * FROM dbo.MyView  -- fast
```

```csharp
int pageSize = 60
if (loadMore) pageSize = 1000;
ctx.MyView.Take(pageSize).ToArray();  //slow when pageSize is 1000
```

# Describe the solution you'd like 

Introduce an EF.Constant() mechanism, which is identified by EF Core and prevents parameterization.
This goes hand in hand with #28151 

```csharp
ctx.MyView.Take(() => EF.Contant(pageSize)).ToArray();
ctx.MyView.Where(b => b.Name == EF.Constant("bar"))
```

Alternatively, add support for query hints like RECOMPILE or OPTIMIZE FOR
/cc @dsyme @NinoFloris @roji

**Comment by roji** [comment] 2023-08-25 14:55
Duplicate of #28632

**Comment by roji** [comment] 2023-08-25 14:58
```c#
ctx.MyView.Take(() => EF.Contant(pageSize)).ToArray();
```

Note that if we indeed introduce an overload of Take that accepts a lambda expression, there wouldn't be any need for EF.Constant, since the expression tree itself would contain a constant node vs. a parameter. I've updated #28632 with a comment about this.

**Comment by Liero** [comment] 2023-08-30 15:20
Just to make sure it is not forgotten, Constant vs Parameter makes a difference not only in Offset/Fetch but also in Where clause, so EF.Constant would still make sense

**Comment by roji** [comment] 2023-08-30 16:00
@Liero Where doesn't have this problem since you can already control whether a constant or parameter is used, see https://github.com/dotnet/efcore/issues/28632#issuecomment-1699446938.

**Comment by roji** [comment] 2023-08-31 11:12
Proposing to keep this open to track EF.Constant as sugar to make it easy to inject Constant nodes into queries (where that makes sense for perf) without using Expression builder APIs.

Note #28151 which is the same but in the other direction, i.e. an EF.Parameter API to force parameterization.

**Comment by KLuuKer** [comment] 2023-09-22 09:22
I would actually need something like this on a whole array of int's.
Pull #13617 _MIGHT_ introduce a performance regression when used with global query filters.

I would like for it to **NOT** optimize my tenant id global query filter into a openjson call.
`x => enabledTenantIds.Contains(x.TenantId)` 
and just keep that list of id's hardcoded.

The list itself doesn't actually change all that much, and it wont generate that many extra query plans in my case.
Having this Constant call work on a Array of int would be helpful in tuning the queries just in case the planner can't handle the extra parameter.

**Comment by roji** [comment] 2023-09-22 13:54
@KLuuKer I understand, though I'd highly recommend first ensuring that there's an actual, meaningful performance regression before going into something like this (people sometimes assume perf issues where there are no actual ones, without measuring etc.).

Note also that this issue would only add sugar - you can already create an expression tree yourself and inject Constant nodes via Expression.Constant. Note also that if the **size** of enabled tenant IDs is fixed, you can parameterize the list contents instead of the entire list (`x => new[] { ids[0], ids[1] }.Contains(x.TenantId)`).

**Comment by KLuuKer** [comment] 2023-09-22 14:07
@roji how could I translate this then?
just in case so I can have a fix ready in case my boss gets angry

```
x => bool1 ? x.int1 == intx :
bool2 ? Intarray.Contains(x.int1) : 
true
```

**Comment by roji** [comment] 2023-09-22 14:25
Here's a fragment showing how to use the Expression builder APIs to created a filter with a constant list, yielding the same query as before. This issue would provide a nicer way to do the same thing without all the Expression builder APIs.

```c#
var ids = new[] { 1, 2, 3 };

// Default behavior: parameterized with OPENJSON:
// WHERE [b].[Id] IN (SELECT [i].[value] FROM OPENJSON(@__ids_0) WITH ([value] int '$') AS [i])
_ = await ctx.Blogs.Where(b => ids.Contains(b.Id)).ToListAsync();

// With constant node:
// WHERE [b].[Id] IN (1, 2, 3)
var containsMethod = typeof(Enumerable).GetMethods()
    .Single(m => m.Name == nameof(Enumerable.Contains) && m.GetParameters().Length == 2);

var blogParam = Expression.Parameter(typeof(Blog), "b");
var filter = Expression.Lambda<Func<Blog, bool>>(
    Expression.Call(
        containsMethod.MakeGenericMethod(typeof(int)),
        Expression.Constant(ids),
        Expression.Property(blogParam, nameof(Blog.Id))),
    blogParam);

_ = await ctx.Blogs.Where(filter).ToListAsync();
```

**Comment by KLuuKer** [comment] 2023-09-26 10:45
@roji i managed to turn it into one big lamda expression that matches my existing global query filter.

but for some reason i cannot turn my method call into a constant.
and i cant input the array directly using `Expression.Constant(myarray)` because it's behind a method call even if i put it in a new variable.
Also because mine is a generic thing over a bunch of types that implement a interface, i can't just manually write it...

```
 var idsExpression = Expression.Call(Expression.Constant(this), typeof(DatabaseContext).GetMethod(nameof(DatabaseContext.GetIds)));

 Expression condition2 = Expression.Condition(
     enableFilterExpression,
     Expression.Call(
         containsMethod.MakeGenericMethod(typeof(int)),
         idsExpression,
         Expression.Property(x, nameof(Blog.Id))),
     Expression.Constant(true));
```

**Comment by roji** [comment] 2023-09-26 13:47
@KLuuKer at the end of the day you have to pass a ready-made .NET array instance to Expression.Constant. You cannot "turn a method call into a constant" - a method call is a method call and therefore is not (and cannot be turned into a constant). You probably need to actually invoke the method before executing the query, and wrap its return value in Expression.Constant, passing that constant node to EF's LINQ query.

In any case, unfortunately I can't really help you debug your specific Expression building code; I recommend inspecting the sort of expression trees that the C# compiler constructs (e.g. by looking at Expressions in the debugger), and trying to construct exactly that.

**Comment by KLuuKer** [comment] 2023-09-27 04:41
@roji well i managed to recreate it and as far as i can see (from the debugview) my tree is the same.

If i run on EF 7 i get the same old constant IN(), and when upgrading to EF 8 i get the newer innerjson version.

So as far as i can see i did do everything correctly. I'm also suffering from a chicken and the egg....
I'm getting that list of id's from the same database context (i'm making sure it's done in the correct order without shooting myself in the foot)
So i kind of need that invoke of the method to be done at query time instead.

**Comment by roji** [comment] 2023-09-27 11:07
> If i run on EF 7 i get the same old constant IN(), and when upgrading to EF 8 i get the newer innerjson version.

That should mean that you're not actually injecting a constant node into the tree. [Take another look at this code sample above](https://github.com/dotnet/efcore/issues/31552#issuecomment-1731515828), and try running it with EF 8 rc1; it shows that when the list argument to Contains is a constant node, the resulting SQL contains constants rather than any JSON-based expression.

> I'm getting that list of id's from the same database context (i'm making sure it's done in the correct order without shooting myself in the foot)
> So i kind of need that invoke of the method to be done at query time instead.
> But it's output needs to be treated as "constant".

As I wrote above, execute the method outside of your query - in .NET - and get its results as a simple .NET `List<T>` or array. Then, integrate that list/array via a constant node into your EF LINQ query. You cannot put the method call directly into your LINQ query **and** have its results treated as a constant.

**Comment by roji** [comment] 2023-11-26 12:06
Note that this will unfortunately not help with Skip/Take parameterization, since these operators accept a non-lambda parameter, and therefore calling EF.Constant within their argument will simply evaluate EF.Constant (which will throw). EF.Constant isn't needed for non-top-level Skip/Take, because there we already detect the difference between parameters and constants.

However, EF.Constant would still be helpful for various other scenarios.

**Comment by roji** [comment] 2023-11-27 23:01
Reopening to consider patching.

**Closed** 2024-01-04 15:09 UTC
Labels: type-enhancement, closed-fixed, customer-reported, Servicing-approved, area-query
