### ISSUE TITLE
How do I configure properties of Json Columns in EF Core 7?

### ISSUE THREAD

**Issue by dirthsj** [dotnet/efcore#31012] opened 2023-05-31 16:36 UTC
## Ask a question

Hi, I would like to configure the properties of the column used for storing Json-Serialized values in EF 7. The schema I'm trying to make will not store anything in the column for 98% of rows, so I want to mark it as Sparse.

The only configuration option I can find is setting the column name, but that does not solve my issue. I have also tried separately using builder.Property to configure sparseness, but that fails to create a migration because it conflicts with the ownership definition.

### Include your code

```
        builder.OwnsMany(domain => domain.ExtraData, ownedBuilder => ownedBuilder.ToJson());
```

### Include stack traces

N/A

### Include verbose output
N/A

### Include provider and version information

EF Core version: Microsoft.EntityFrameworkCore/7.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer/7.0.5
Target framework: .NET 7
Operating system: Windows 10
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment] 2023-06-04 13:21
Duplicate of #28591.

**Closed** 2023-06-07 18:44 UTC
Labels: closed-duplicate, customer-reported
