### ISSUE TITLE
Filtering by navigation property without Include fails

### ISSUE THREAD

**Issue by MaximBalaganskiy** [dotnet/efcore#2047] opened 2015-04-22 12:31 UTC
Using Entity Framework version 7.0.0-beta3 in a console application to persist following classes:

```
public class Parent
{
    public int Id { get; set; }
    public string Name { get; set; }
    public List<Child> Children { get; set; }
}
public class Child
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int ParentId { get; set; }
    public Parent Parent { get; set; }
}
```

Provided that records exist in a SQL Server database, two following queries return different results:

```
// p1 is null
var p1 = context.Parents.FirstOrDefault(x => x.Children.Any());

// p2 is not null
var p2 = context.Parents.Include(x => x.Children).FirstOrDefault(x => x.Children.Any());
```

Is this a designed behavior?

**Comment by divega** [comment] 2015-05-04 06:29
@maumar can you check if this still repros and find out what the issue is? cc @anpete

**Comment by divega** [comment] 2015-05-04 06:30
Ah, I suppose this is just about navigation properties not working.

**Comment by divega** [comment] 2015-05-04 06:34
Dupe of #325. The second version of the query works because children are loaded into memory and x.Children.Any() can be correctly evaluated in memory.

**Closed** 2022-10-16 08:55 UTC
