### ISSUE TITLE
Query: invalid SQL for queries with GroupBy, OrderBy group key projecting a constant

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12564] opened 2018-07-05 20:30 UTC
query using Northwind model:

```cs
ctx.Orders.GroupBy(o => o.CustomerID).OrderBy(g => g.Key).Select(e => 42)
```

generated SQL:

```sql
SELECT 1
FROM [Orders] AS [o]
GROUP BY [o].[CustomerID]
ORDER BY [Key]
```

**Comment by maumar** [comment] 2018-07-05 20:36
Similar problem happens for group aggregate queries that project constant afterwards:

```cs
ctx.Orders.GroupBy(o => o.CustomerID)
                        .OrderBy(o => o.Count())
                        .ThenBy(o => o.Key)
                        .Select(
                            g => new
                            {
                                g.Key,
                                Count = g.Count()
                            }),
```

```sql
SELECT 1
FROM [Orders] AS [o]
GROUP BY [o].[CustomerID]
ORDER BY COUNT(*), [Key]
```

**Comment by smitpatel** [comment] 2018-07-27 19:57
Duplicate of #12826

**Closed** 2022-10-16 13:17 UTC
Labels: type-cleanup, closed-duplicate
