### ISSUE TITLE
Named In-Memory database does not reset autoincrement column [Key]

### ISSUE THREAD

**Issue by MichaelGiger** [dotnet/efcore#9991] opened 2017-10-06 06:50 UTC
With EF Core 2.0, in-memory databases must be named.

In [docs](https://docs.microsoft.com/de-ch/ef/core/miscellaneous/testing/in-memory) I found an example and following comment:

> The key to testing with this provider is the ability to tell the context to use the InMemory provider, and control the scope of the in-memory database. Typically you want a clean database for each test method.
> Here is an example of a test class that uses the InMemory database. Each test method specifies a unique database name, meaning each method has its own InMemory database.

Each test has an empty database, but an autoincrement column, e.g. Key attribute is not reset.

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Win 10
IDE: Visual Studio 2017, 15.3.0

**Comment by ajcvickers** [comment] 2017-10-06 16:06
@MichaelGiger Duplicate of the discussion on issue #6872

**Closed** 2022-10-16 11:53 UTC
