### ISSUE TITLE
boolean criteria are not being translated directly

### ISSUE THREAD

**Issue by prowe** [dotnet/efcore#26764] opened 2021-11-19 16:52 UTC
## Ask a question

We are using EF Core 5.0.11, we have a model that has a `bool IsComplete` field on it with default mapping and conversion.

If we do the following `.Where(x => x.IsComplete == false)` it gets translated into 
```SQL
WHERE [r].[IsComplete] <> CAST(1 as BIT)
```

This translation of the Boolean logic causes SQL Server to no longer hit an index that uses `IsComplete` as a column.

Is there a reason why the more streightforward `WHERE [r].[IsComplete] = CAST(0 as BIT)` couldn't be used?

Note:
We worked around this issue by doing the following:
```C#
builder.Property(x => x.IsCompleted).HasConversion<bool>(f => f, f => f);
```

EF Core version: 5.0.11
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: MacOS/Docker
IDE: VS Code

**Comment by roji** [comment] 2021-11-19 17:29
Duplicate of #23472

**Comment by roji** [comment] 2021-11-19 17:29
This is fixed in 6.0.0.

**Comment by prowe** [comment] 2021-11-19 18:43
Sweet, will update and re-test

**Comment by diogonborges** [comment] 2022-01-07 18:22
@prowe and @roji 
Have any of you flirted with the idea of not using CAST?

The reason for this is that it's not the casting to 0 or 1 makes a lot of difference to us, but when using hierarchyid using a cast to 1 for the result of of a boolean operation will result in the index not being hit.

examples:
this is a pretty terrible performance
```SELECT t.* FROM [Tenant] AS [t] WHERE [t].[NodeHierarchy].IsDescendantOf('/') = CAST( 1 AS BIT)```
this is perfectly fast
```SELECT t.* FROM [Tenant] AS [t] WHERE [t].[NodeHierarchy].IsDescendantOf('/') = 1```

**Closed** 2022-10-16 20:15 UTC
Labels: closed-duplicate, customer-reported
