### ISSUE TITLE
Don't remove table mapping for entity types used in TVFs

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#23407] opened 2020-11-19 21:20 UTC
Originally reported by @maumar 

Line to remove: https://github.com/dotnet/efcore/blob/b970bf29a46521f40862a01db9e276e6448d3cb0/src/EFCore.Relational/Metadata/Conventions/TableValuedDbFunctionConvention.cs#L97

**Comment by ajcvickers** [comment] 2020-11-20 18:52
Note from triage: consider when to map to table automatically, or not, based on how the TVF and return type is used elsewhere.

**Comment by ajcvickers** [comment] 2020-11-20 20:19
Duplicate of #23408

**Closed** 2022-10-16 19:10 UTC
Labels: closed-duplicate
