### ISSUE TITLE
Insert entity  but not insert nested object

### ISSUE THREAD

**Issue by ngonzalezromero** [dotnet/efcore#7157] opened 2016-11-29 19:59 UTC
I have this method

```C#
        public async Task<SubNetwork> SaveSubNetworkAsync(SubNetwork subNetwork)
        {
            SubNetwork subnet = null;

            if (subNetwork.SubNetworkId == 0)
            {
                subnet = new SubNetwork();
            }
            else
            {
                subnet = await FindSubNetworkByAsync(x => x.SubNetworkId == subNetwork.SubNetworkId);
            }

            subnet.State = await _context.State.FirstAsync(x => x.StateId == subNetwork.State.StateId);
            //await _sharedService.GetStateAsync(x => x.StateId == subNetwork.State.StateId);


            if (subNetwork.SubNetworkId == 0)
            {
                _context.SubNetwork.Add(subnet);
            }
            else
            {
                _context.SubNetwork.Update(subnet);
            }

            await _context.SaveChangesAsync();
            return subnet;
        }
```

if I updated the entity , I don't have problem, but if I Insert 

       Full Trace: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while                    
       updating the entries. See the inner exception for details. ---> Npgsql.PostgresException: 
       23502: null value in column "StateName" violates not-null constraint
       at Npgsql.NpgsqlConnector.<DoReadMessageAsync>d__6.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at   
      System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
      (Task task)
       at Npgsql.NpgsqlConnector.<ReadMessageWithPrependedAsync>d__5.MoveNext()

  State entity (  subnet.State) has "StateName" value always

       "Microsoft.EntityFrameworkCore": "1.1.0",
        "Microsoft.EntityFrameworkCore.Relational": "1.1.0",
        "Npgsql.EntityFrameworkCore.PostgreSQL": "1.1.0",
        "Npgsql.EntityFrameworkCore.PostgreSQL.Design": "1.1.0",

       Mac OSX
     dotnet --version 1.0.0-preview2-1-003177

**Comment by rowanmiller** [comment] 2016-12-07 17:28
Could you provide a complete code listing that we could run to debug the issue? Or a project that we can run with detailed instruction about how to hit this particular line of code.

**Comment by rowanmiller** [comment] 2016-12-12 19:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 10:45 UTC
