### ISSUE TITLE
Unable to run dotnet ef migration add on debian 10

### ISSUE THREAD

**Issue by 1988gadocansey** [dotnet/efcore#30795] opened 2023-04-29 09:41 UTC
I'm unable to run the dotnet ef migration add initialcreate on debian 10 using dotnet core 7.0 .

![Screen Shot 2023-04-29 at 9 41 05 AM](https://user-images.githubusercontent.com/7513799/235296112-f00c043a-836d-433d-bfc5-2019a41e84bb.png)

**Comment by ErikEJ** [comment] 2023-04-29 11:27
Which command did you use to install it?

**Comment by ajcvickers** [comment] 2023-05-10 09:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-05-10 09:01 UTC
Labels: customer-reported
