### ISSUE TITLE
Query: convert tests that dont use AssertQuery to use the pattern

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12501] opened 2018-06-29 00:20 UTC
Some query tests don't use AssertQuery pattern for verification. We should convert them to the pattern. Reason is that we get full result verification for the test and async execution for free.

**Comment by AndriySvyryd** [comment] 2020-09-05 00:13
Duplicate of https://github.com/dotnet/efcore/issues/21393

**Closed** 2022-10-16 13:16 UTC
Labels: closed-duplicate
