### ISSUE TITLE
Breaking Change - EF Core 3.0 Not Handling Entity Interfaces Correctly.

### ISSUE THREAD

**Issue by CompuBoy** [dotnet/efcore#18275] opened 2019-10-08 12:19 UTC
In EF Core 2.2, I could write interfaces for my entities and then I could **Cast<>()** my entity queries to their interfaces and work with interface members that we mapped on the implementing entity without any problem. But in EF Core 3.0, it is not possible and **ArgumentException** is raised.

### Steps to reproduce

Consider the following interface and the following EF Core entity:
``` C#
public interface IMyEntity
{
    Guid Id { get; set; }
}

[Table(nameof(MyEntity))]
public class MyEntity : IMyEntity
{
    [Key]
    public Guid Id { get; set; }
}
```
In EF Core 2.2, the following query was working as expected:

``` C#
var myRecords = myDbContext.MyEntities.Cast<IMyEntity>().Where(e => e.Id == Guid.Empty).ToList();
```

But in EF Core 3.0, the following exception is raised:

### Exception

> Exception has occurred: CLR/System.ArgumentException
> An unhandled exception of type 'System.ArgumentException' occurred in System.Linq.Expressions.dll: 'Expression of type 'System.Linq.IQueryable`1[TestEFCore.IMyEntity]' cannot be used for parameter of type 'System.Linq.IQueryable`1[TestEFCore.MyEntity]' of method 'System.Linq.IQueryable`1[TestEFCore.MyEntity] Where[MyEntity](System.Linq.IQueryable`1[TestEFCore.MyEntity], System.Linq.Expressions.Expression`1[System.Func`2[TestEFCore.MyEntity,System.Boolean]])''
>    at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
>    at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1)
>    at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessWhere(NavigationExpansionExpression source, LambdaExpression predicate)
>    at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
>    at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>    at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandAndReduce(Expression query, Boolean applyInclude)
>    at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
>    at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
>    at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
>    at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
>    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
>    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
>    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
>    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
> 
> 

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio Code (vLatest)

**Comment by CompuBoy** [comment] 2019-10-08 15:35
In fact, the same problem also exists for **.Join()** on interface queries. 

Cloning EF Core source code for my self, I could fix the first problem by making a slight change in **ProcessCastOfType()** method of **NavigationExpandingExpressionVisitor** class, adding an else to the inner if condition:

``` C#
                if (castEntityType != null)
                {
                    var newEntityReference = new EntityReference(castEntityType);
                    if (entityReference.IsOptional)
                    {
                        newEntityReference.MarkAsOptional();
                    }
                    newEntityReference.SetIncludePaths(entityReference.IncludePaths);

                    // Prune includes for sibling types
                    var siblingNavigations = newEntityReference.IncludePaths.Keys
                        .Where(n => !castEntityType.IsAssignableFrom(n.DeclaringEntityType)
                            && !n.DeclaringEntityType.IsAssignableFrom(castEntityType)).ToList();

                    foreach (var navigation in siblingNavigations)
                    {
                        newEntityReference.IncludePaths.Remove(navigation);
                    }

                    newStructure = newEntityReference;
                }
               //<Added>
                else
                {
                    newStructure = Expression.Default(castType);
                }
               //</Added>
```

But the problem with **Join()** requires more insight into the code.

**Comment by smitpatel** [comment] 2019-10-10 22:17
Duplicate of #18087

**Closed** 2022-10-16 14:48 UTC
Labels: customer-reported
