### ISSUE TITLE
Compiled Models in EF8 generates different SQL

### ISSUE THREAD

**Issue by benOneil** [dotnet/efcore#32779] opened 2024-01-11 05:06 UTC
In EF Core 8 when using Compiled Models, the resulting SQL changes when using StartsWith on a Database Column with Char type. The SQL query changes from varchar to char causing unexpected results.

OptionsBuilder has UseCompatibilityLevel(120) set.

```C#
var result = db.[Table].AsNoTracking().Where(x => x.[Column].StartsWith(test)).Select(y => y.[Column]).Distinct().Take(200);
```

Original Generated SQL
```SQL
DECLARE @__p_1 int = 200;
DECLARE @__test_0_rewritten varchar(10) = 'Te%';

SELECT DISTINCT TOP(@__p_1) [o].[Column]
FROM [Table] AS [o]
WHERE [o].[Column] LIKE @__test_0_rewritten ESCAPE '\'
```
Compiled Model  Generated SQL
```SQL
DECLARE @__p_1 int = 200;
DECLARE @__test_0_rewritten char(10) = 'Te%';

SELECT DISTINCT TOP(@__p_1) [o].[Column]
FROM [Table] AS [o]
WHERE [o].[Column] LIKE @__test_0_rewritten ESCAPE '\'
```

EF Core version: 8.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 8.0

**Comment by muzopraha** [comment] 2024-01-15 08:22
I have same issue: #32771

**Comment by roji** [comment] 2024-01-15 09:16
Duplicate of #32771

**Comment by roji** [comment] 2024-01-15 09:17
Closing in favor of #32771 which has more details and was opened earlier.

**Closed by roji** 2024-01-15 09:17 UTC
Labels: customer-reported
