### ISSUE TITLE
Can't create unique constraint on 2 fields where one is a nullable foreign key

### ISSUE THREAD

**Issue by TPucke** [dotnet/efcore#20075] opened 2020-02-26 18:21 UTC
My requirement is to create a unique constraint on multiple columns of a single table where one of the columns is a nullable foreign key (C# Guid? / pg uuid).  I first tried the following:
```C#
builder.Entity<FileDropDirectory>(b =>
{
    b.HasAlternateKey(x => new { x.ParentDirectoryId, x.Name });

    // other unrelated things
}
```

The declarations of these 2 fields in class FileDropDirectory are:
```C#
[ForeignKey("ParentDirectory")]
public Guid? ParentDirectoryId { get; set; }
public FileDropDirectory ParentDirectory { get; set; }

[Required]
public string Name { get; set; }
```

Without `.HasAlternateKey` the database column ParentDirectoryId is nullable, but when I add the alternate key  the column becomes NOT NULL despite the property declaration with type `Guid?`.  

I tried something else:
```C#
b.HasIndex(x => new { x.ParentDirectoryId, x.Name }).IsUnique();
```
This resulted in nullable ParentDirectoryId field.  However I was then able to add any number of records to the table that should have violated the constraint.  Looking at the table definition (SQL) in pgAdmin, a unique constraint does not appear within the CREATE TABLE statement, but there is a later CREATE INDEX statement as follows:
```sql
CREATE UNIQUE INDEX "IX_FileDropDirectory_ParentDirectoryId_Name"
  ON public."FileDropDirectory"
  USING btree
  ("ParentDirectoryId", "Name" COLLATE pg_catalog."default");
```

I don't see any way to meet the stated requirement of a unique constraint on 2 fields, one of which is a nullable Guid FK. 

### Further technical details

EF Core version: 2.2.4
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 2.2.4
Target framework: netstandard2.0 dll loaded by a Windows Forms project targeting netcoreapp3.1
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.9.20)

**Comment by ajcvickers** [comment] 2020-02-27 16:55
@roji This is about creating composite unique indexes in npgsql. Thoughts?

@TPucke EF Core 2.2 is [out-of-support](https://docs.microsoft.com/en-us/ef/core/what-is-new/) Please update to EF Core 3.1.

**Comment by TPucke** [comment] 2020-02-27 19:42
Thanks I'll look at Npgsql/EF 3.x.  I put that off because our database is on PG 9.6, so we will need to either use the Npgsql 3.x technique for respecting the no-longer-default PG bigserial type, or modify our schema to adopt the newer auto-numbering type. I need to re-familiarize with that topic. 

Also can you address whether `HasAlternateKey()` has any role in my scenario, in contrast to `HasIndex`.  Using an index that doesn't create a constraint seems at first like a non-obvious means to meet the goal, especially without knowing the rationale.

**Comment by bricelam** [comment] 2020-02-29 00:33
I feel like we've discussed this before @AndriySvyryd, doesn't HasAlternateKey make the columns required (like HasKey)? I feel like we considered not doing that in the past.

**Comment by bricelam** [comment] 2020-02-29 00:40
> I was then able to add any number of records to the table that should have violated the constraint.

Was one of the columns NULL? Most databases treat NULL values as distinct from one another--one NULL is not equal to another NULL--so values like the following would be allowed:

ParentDirectoryId | Name | Unique?
--- | --- | ---
NULL | Alpha | Yes
NULL | Alpha | Yes
00000000-0000-0000-0000-000000000000 | Alpha | Yes
00000000-0000-0000-0000-000000000000 | Alpha | No (conflicts with previous row)

**Comment by AndriySvyryd** [comment] 2020-02-29 00:47
> I feel like we've discussed this before @AndriySvyryd, doesn't HasAlternateKey make the columns required (like HasKey)? I feel like we considered not doing that in the past.

https://github.com/dotnet/efcore/issues/4415

**Comment by TPucke** [comment] 2020-02-29 01:04
> > I was then able to add any number of records to the table that should have violated the constraint.
> 
> Was one of the columns NULL? Most databases treat NULL values as distinct from one another--one NULL is not equal to another NULL--so values like the following would be allowed:
> 
> ParentDirectoryId	Name	Unique?
> NULL	Alpha	Yes
> NULL	Alpha	Yes
> 00000000-0000-0000-0000-000000000000	Alpha	Yes
> ~00000000-0000-0000-0000-000000000000~	~Alpha~	No (conflicts with previous row)

@bricelam The records I added contained a proper uuid value.  It wasn't NULL and it wasn't the default Guid.  I was evaluating whether uniqueness was being enforced at the same time that the column could be deployed without being coerced (against my intentions) to NOT NULL, and without letting the complicating factor of NULL non-equivalence affect the answer.  

Just to be clear, this occurred using the unique index, not HasAlternateKey.  I deployed the generated migration and then inserted 3 identical records directly in the database, not using EF.  This was intended to evaluate whether the uniqueness enforcement was deployed to the PostgreSQL server through the generated migration, because I'm looking for the database to do its part with relational integrity.

**Comment by roji** [comment] 2020-03-05 10:36
@TPucke I'm unable to reproduce the unique *index* issue with EF Core 3.1 on PostgreSQL: I can clearly see a unique, composite index being created over the string and nullable uuid column. Attempting to insert two rows with the same values for those two columns throws as expected. Can you please try the below, and if you still have an issue, submit a similar code sample that shows what's wrong?

```c#
class Program
{
    static void Main(string[] args)
    {
        var guid = Guid.NewGuid();
        
        using (var ctx = new BlogContext())
        {
            ctx.Database.EnsureDeleted();
            ctx.Database.EnsureCreated();

            ctx.Blogs.Add(new Blog { Name = "foo", ParentDirectoryId = guid });
            ctx.SaveChanges();
        }
        
        using (var ctx = new BlogContext())
        {
            ctx.Blogs.Add(new Blog { Name = "foo", ParentDirectoryId = guid });
            ctx.SaveChanges(); // throws duplicate key value violates unique constraint "IX_Blogs_ParentDirectoryId_Name"
        }
    }
}

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseNpgsql(...)
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>()
            .HasIndex(b => new { b.ParentDirectoryId, b.Name }).IsUnique();
    }
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Guid? ParentDirectoryId { get; set; }
}
```

The DDL used to create the schema:

```sql
CREATE TABLE "Blogs" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "ParentDirectoryId" uuid NULL,
    CONSTRAINT "PK_Blogs" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Blogs_ParentDirectoryId_Name" ON "Blogs" ("ParentDirectoryId", "Name");
```

**Comment by TPucke** [comment] 2020-03-09 15:10
I ran the sample from @roji, got the same outcome that he did, so went back to my application and repeated the original scenario.  The index worked as a constraint on uniqueness so I'm ready to call a false alarm on my part, with apology to all participants here.  

After numerous cycles of reverting and regenerating migrations to pin down what I was seeing, I probably lost track of my environment.

**Comment by roji** [comment] 2020-03-09 16:10
Thanks for getting back to us @TPucke. Will close this for now as there doesn't seem to be anything actionable on our side (except for #4415), but if you still see an issue please post back.

**Closed** 2022-10-16 18:13 UTC
Labels: closed-could-not-reproduce, customer-reported
