### ISSUE TITLE
Include on derived navigational properties breaks ToListAsync(). (2.1.0-preview1-final)

### ISSUE THREAD

**Issue by NumiLarsson** [dotnet/efcore#11171] opened 2018-03-07 09:58 UTC
Running 2.1.0-preview1-final.

Using the newly implemented "Include for derived types" e.g. (dataContext.Questions.Include(q => (q as ChildQuestion).SubQuestions) breaks ToListAsync(), but still works in ToList().

```
Exception message: One or more errors occurred.
Inner Exception message: Object reference not set to an instance of an object.
Stack trace:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ToListAsyncBugHunting.Program.Main(String[] args) in C:\Users\<MyLocalUserName>\source\repos\ToListAsyncBugHunting\ToListAsyncBugHunting\Program.cs:line 35

Inner Exception Stack Trace:
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.<_IncludeAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.<_ExecuteAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext()
```

### Steps to reproduce
Simply using any derived navigational property in a ToListAsync call seems to break it. 
I've setup two identical queries, using derived properties, and ToListAsync() fails every time.
The code example below is an easy reproduction of it.

```c#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Configuration;
using Microsoft.EntityFrameworkCore;

namespace ToListAsyncBugHunting
{
    class Program
    {
        static void Main(string[] args)
        {
            var dataContext = new DataContext();
            var querySync = dataContext.Questions.Include(q => (q as ChildQuestion).SubQuestions);
            var queryASync = dataContext.Questions.Include(q => (q as ChildQuestion).SubQuestions);
            var syncResult = querySync.ToList();
            var asyncResult = queryASync.ToListAsync();
            foreach (Question question in syncResult)
            {
                Console.WriteLine(question.Id);
                if (question is ChildQuestion cq)
                {
                    Console.WriteLine("Has childs: ");
                    foreach (Question cqSubQuestion in cq.SubQuestions)
                    {
                        Console.WriteLine("   " + cqSubQuestion.Id);
                    }
                }
            }

            Console.WriteLine("--- Sync Done ---");

            asyncResult.Wait();
            var asyncActualResult = asyncResult.Result;
            foreach (Question question in asyncActualResult)
            {
                Console.WriteLine(question.Id);
            }


        }
    }

    class DataContext : DbContext
    {
        public DataContext()
        {

        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {

            base.OnConfiguring(optionsBuilder);
            var connectionString = ConfigurationManager.ConnectionStrings["ExceedPocApp"]
                .ConnectionString;
            //Disable transaction warnings
            optionsBuilder.UseSqlServer(connectionString);
        }

        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<ChildQuestion> ChildQuestions { get; set; }
        public virtual DbSet<OtherChildQuestion> OtherChildQuestions { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Question>()
                .HasDiscriminator()
                .HasValue<ChildQuestion>("ChildQuestion")
                .HasValue<OtherChildQuestion>("OtherChildQuestion");

            modelBuilder.Entity<Question>()
                .HasOne(q => q.QuestionParent)
                .WithMany(cq => cq.SubQuestions)
                .HasForeignKey(q => q.QuestionParentId);

            modelBuilder.Entity<ChildQuestion>()
                .HasBaseType<Question>()
                .HasMany(cq => cq.SubQuestions)
                .WithOne(q => q.QuestionParent)
                .HasForeignKey(q => q.QuestionParentId);

            modelBuilder.Entity<OtherChildQuestion>()
                .HasBaseType<Question>();
        }
    }

    class Question
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? QuestionParentId { get; set; }
        public ChildQuestion QuestionParent { get; set; }
    }

    class ChildQuestion : Question
    {
        public ChildQuestion()
        {
            SubQuestions = new HashSet<Question>();
        }
        public int Answer { get; set; }

        public ICollection<Question> SubQuestions { get; set; }
    }

    class OtherChildQuestion : Question
    {
        [Column(TypeName = "ntext")]
        public string AnotherAnswer { get; set; }
    }
}
```

Database data:
![databasevalues](https://user-images.githubusercontent.com/13768506/37085829-5aca637a-21f6-11e8-9174-dcbcfb721e73.png)

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer - version: 2.1.0-preview1-final
Operating system: Windows 10 Enterprise Version 10.0.15063 Build 15063
IDE: Visual Studio Professional 2017 version 15.5.6

**Comment by smitpatel** [comment] 2018-03-07 16:38
@NumiLarsson - Thanks for reporting this issue. This is Duplicate of #10440 
If you're eager to test it out, you can try [the nightly feed](https://dotnet.myget.org/gallery/aspnetcore-dev).

**Closed** 2022-10-16 12:12 UTC
Labels: closed-duplicate
