### ISSUE TITLE
Xamarin and MS Identity - index out of range

### ISSUE THREAD

**Issue by AdamJachocki** [dotnet/efcore#19029] opened 2019-11-22 09:55 UTC
Hi, this is blocker to us. Much much blocker.

When calling Migrate() method from AppContext.Database, there is IndexOutOfRange exception. This works however outside xamarin (for example WPF).

These are last messages from output:

11-12 15:29:30.188 D/Mono ( 6636): Config attempting to parse: ‘System.ComponentModel.DataAnnotations.dll.config’.
11-12 15:29:30.188 D/Mono ( 6636): Config attempting to parse: ‘/Users/builder/jenkins/workspace/archive-mono/2019-06/android/release/sdks/out/android-x86-release/etc/mono/assemblies/System.ComponentModel.DataAnnotations/System.ComponentModel.DataAnnotations.config’.
11-12 15:29:30.188 D/Mono ( 6636): Assembly Ref addref System.ComponentModel.Annotations[0xd085c160] -> System.ComponentModel.DataAnnotations[0xd085c100]: 2
11-12 15:29:30.188 D/Mono ( 6636): Loading reference 0 of System.ComponentModel.DataAnnotations.dll asmctx DEFAULT, looking for mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
11-12 15:29:30.188 D/Mono ( 6636): Assembly Ref addref System.ComponentModel.DataAnnotations[0xd085c100] -> mscorlib[0xf0e0db40]: 57
11-12 15:29:30.212 D/Mono ( 6636): Loading reference 5 of /storage/emulated/0/Android/data/com.companyname.app5/files/.override/Microsoft.EntityFrameworkCore.dll asmctx DEFAULT, looking for System.ComponentModel.Annotations, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
11-12 15:29:30.213 D/Mono ( 6636): Unloading image System.ComponentModel.Annotations.dll [0xcf935a00].
11-12 15:29:30.214 D/Mono ( 6636): Image addref System.ComponentModel.Annotations[0xd085c0a0] (asmctx DEFAULT) -> System.ComponentModel.Annotations.dll[0xd075ab00]: 5
11-12 15:29:30.214 D/Mono ( 6636): Config attempting to parse: ‘System.ComponentModel.Annotations.dll.config’.
11-12 15:29:30.214 D/Mono ( 6636): Config attempting to parse: ‘/Users/builder/jenkins/workspace/archive-mono/2019-06/android/release/sdks/out/android-x86-release/etc/mono/assemblies/System.ComponentModel.Annotations/System.ComponentModel.Annotations.config’.
11-12 15:29:30.214 D/Mono ( 6636): Assembly Ref addref Microsoft.EntityFrameworkCore[0xf0e0e4a0] -> System.ComponentModel.Annotations[0xd085c160]: 3
11-12 15:29:30.691 D/Mono ( 6636): Loading reference 6 of /storage/emulated/0/Android/data/com.companyname.app5/files/.override/Microsoft.EntityFrameworkCore.dll asmctx DEFAULT, looking for System.Collections.Immutable, Version=1.2.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
11-12 15:29:30.691 D/Mono ( 6636): Assembly Ref addref Microsoft.EntityFrameworkCore[0xf0e0e4a0] -> System.Collections.Immutable[0xf0e0ee60]: 2
11-12 15:29:30.808 D/Mono ( 6636): Loading reference 1 of /storage/emulated/0/Android/data/com.companyname.app5/files/.override/Microsoft.Extensions.Identity.Stores.dll asmctx DEFAULT, looking for Microsoft.Extensions.Identity.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
11-12 15:29:30.809 D/Mono ( 6636): Assembly Ref addref Microsoft.Extensions.Identity.Stores[0xf0e0e980] -> Microsoft.Extensions.Identity.Core[0xf0e0e920]: 3
System.IndexOutOfRangeException: ‘Index was outside the bounds of the array.’

You have minimal reproductible solution here:
[https://github.com/AdamJachocki/EfCoreCrash](https://github.com/AdamJachocki/EfCoreCrash)

**Comment by ajcvickers** [comment] 2019-11-24 22:23
Note for triage: Nothing looks off in the project, so this looks like it is a Xamarin/Mono issue loading assemblies.

**Comment by AdamJachocki** [comment] 2019-11-25 10:21
They have redirected me to you saying that this is EFCore problem. Please, don't send me from one to other. I really need to solve this, because I can't work on project. I use EfCore mostly as a tool for database creation and migration. For now, I don't even have database, so I cannot work at all :(

**Comment by ajcvickers** [comment] 2019-11-25 17:23
@AdamJachocki Can you link to where they redirected you here?

**Comment by AdamJachocki** [comment] 2019-11-25 17:27
https://developercommunity.visualstudio.com/content/problem/816863/blocker-xamarin-and-ms-identity-index-out-of-range.html

**Comment by ajcvickers** [comment] 2019-11-25 19:59
@AdamJachocki Thanks. I am following up.

**Comment by cosminstirbu** [comment] 2020-04-22 11:38
As I was going through the list of [area-xamarin](https://github.com/dotnet/efcore/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-xamarin) issues to evaluate if EF Core would be a production ready solution for Xamarin I stumbled upon this issue.

It is not clear what is the source of this exception and if there is a workaround - I'm asking from a EF Core integration perspective, not from a Xamarin / Mono runtime perspective (e.g. are there any EF Core specific APIs that are causing this issue and that we should avoid using?)

**Comment by cosminstirbu** [comment] 2020-04-22 12:05
Interestingly enough, I did clone the linked sample and the issue reproduced.

But after updating all the nuget pacakges to the latest stable version, the Android app runs just fine.

On iOS there's a null pointer exception that I'm still investigating.

**Comment by ajcvickers** [comment] 2020-04-24 18:39
@cosminstirbu Thanks for testing this with the latest versions. We're going to close this for now, but please ping us if you're still having issues with the null pointer exception.

**Closed** 2022-10-16 14:57 UTC
Labels: closed-external, area-xamarin, customer-reported
