### ISSUE TITLE
Query: translate SequenceEqual on byte[] (and other types?)

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#8376] opened 2017-05-03 22:57 UTC
We should be able to translate Enumerable.SequenceEqual for some types.
In case of byte[] they translate directly to comparison on sql

**Comment by smitpatel** [comment] 2017-05-03 23:23
dupe of #5806 for byte[]

**Comment by ajcvickers** [comment] 2017-05-07 20:37
Notes from triage: this bug is really about deep comparisons on arrays, etc. when comparing them inside the in-memory database. Decided that this should always be a deep comparison, done by re-writing the expression, and we should consider using IStructuralComparable. Closing as dupe of #5806.

**Closed** 2022-10-16 11:03 UTC
Labels: closed-duplicate
