### ISSUE TITLE
Repeated statement in the ORDER BY clause instead of referring to the alias in the SELECT

### ISSUE THREAD

**Issue by kresimirlesic** [dotnet/efcore#23058] opened 2020-10-20 12:26 UTC
EF core repeats the SQL statement in the order by section instead of referring to the alias.

This can cause duplicate branches (possibly complex) in the execution plan which can easily be avoided using aliases.

Example:

```
db.Users.Select(x => new { OrderProperty = (complex subquery).Count() }).OrderBy(x => x.OrderProperty)
```

would be translated to something along:

select (complex sql) from Users
order by (complex sql)

**Comment by maumar** [comment] 2020-10-21 06:16
dupe of https://github.com/dotnet/efcore/issues/18775

**Closed** 2022-10-16 19:05 UTC
Labels: customer-reported
