### ISSUE TITLE
Query: compilation error (null type mapping) for query with join where key selectors are anonymous types and one of them is constat

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#15728] opened 2019-05-15 20:53 UTC
query:

```cs
from e1 in ctx.Entities1
                            join e2 in ctx.Entities2
                            on new
                            {
                                three = true
                            }
                            equals new
                            {
                                three = e2.BoolA
                            }
                            select new { e1, e2 };
```

however this works:
```cs
 from e1 in ctx.Entities1
                            join e2 in ctx.Entities2
                            on true equals e2.BoolA
                            select new { e1, e2 };
```

**Comment by smitpatel** [comment] 2019-05-15 20:59
Duplicate of #15712

**Comment by smitpatel** [comment] 2019-05-15 20:59
Duplicate of #14672

**Closed** 2022-10-16 14:21 UTC
Labels: closed-duplicate
