### ISSUE TITLE
Data type 'nvarchar' is not supported in this form. Either specify the length explicitly in the type name, for example as 'nvarchar(16)', or remove the data type and use APIs such as HasMaxLength to allow EF choose the data type.

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#9814] opened 2017-09-14 00:05 UTC
> Data type 'nvarchar' is not supported in this form. Either specify the length explicitly in the type name, for example as 'nvarchar(16)', or remove the data type and use APIs such as HasMaxLength to allow EF choose the data type.

[Related Issue](https://github.com/aspnet/EntityFrameworkCore/issues/4759)

I am receving the error message above, have tried various fixes as suggested by the related issue link above.  I've commented out all properties of my model except ID in an attempt to isolate this issue but nothing works.  I am showing my model of type Order but I have tried to query other tables in my database and I receive the same error.  Did I get lucky or is there perhaps some database level setting I need to be aware of?

Model

```
public partial class Order
{
	
	public Guid Id { get; set; }
}
```

Context

```
modelBuilder.Entity<Order>(entity =>
{
	entity.ToTable("order", "dbo");

	entity.Property(e => e.Id)
		.HasColumnName("id")
		.ValueGeneratedNever();
});
```

Query 

```
var junk = db.Orders.Take(10);
```

What I've tried 

```
modelBuilder.Entity<Order>(entity =>
{
	entity.ToTable("order", "dbo");

	entity.Property(e => e.Id)
		.HasColumnName("id")
		.ValueGeneratedNever()
		.HasColumnType("varchar(50)");  
                //.HasColumnType("guid") .HasColumnType("uniqueidentifier") .HasMaxLength(50)
});

```

**Comment by smitpatel** [comment] 2017-09-14 00:07
@sam-wheat - Which version of EF Core are you using? Did you generate your model using EF scaffolder?

**Comment by sam-wheat** [comment] 2017-09-14 00:10
EF Core 2.0.  Yes, model was generated using scaffolder.  However as shown I have commented all properties except ID in order to isolate the issue.  Also, the actual type of the column on the database is "PK, uniqueidentifier, not null".

**Comment by smitpatel** [comment] 2017-09-14 00:41
Duplicate of #9188 

That was bug in scaffolder. So if the database has type of `nvarchar(4000)` it would scaffold `nvarchar` which throws above exception at runtime. I am unsure why you would get that error on the model you have shared but perhaps if you have any other configuration in `OnModelCreating` which configures entities then above error could arise. Easy way to find the points of error would be to do a search `"nvarchar"` on your project and replace them with `nvarchar(4000)`

**Comment by MalithRukshan** [comment] 2018-03-22 02:37
I also got the same error: =>{Data type 'varchar' is not supported in this form. Either specify the length explicitly in the type name, for example as 'varchar(16)', or remove the data type and use APIs such as HasMaxLength to allow EF choose the data type.'}

before fixed :
.HasColumnType("varchar")
.HasMaxLength(50);
solution is:
.HasColumnType("varchar(50)");

It is working.

**Closed** 2022-10-16 11:49 UTC
Labels: closed-duplicate
