### ISSUE TITLE
Non-nullable [Owned] properties don't seem to work

### ISSUE THREAD

**Issue by markm77** [dotnet/efcore#22421] opened 2020-09-05 23:32 UTC
I mentioned this [here](https://github.com/dotnet/efcore/issues/22352) but decided it probably needs its own issue.

```[Owned]``` properties like those below do not appear to map to non-nullable in my testing....

```csharp
    [Owned]
    public class OwnedClass
    {
        public string MyString { get; set; }
        public bool MyBool { get; set; }
    }
```

### Further technical details

EF Core version: 5.0.0-preview.8.20407.4
Database provider: Sqlite
Target framework: .NET Core 3.1 latest (nullable enabled)
Operating system: Windows 10 latest
IDE: Rider latest

**Comment by AndriySvyryd** [comment] 2020-09-06 17:33
Duplicate of https://github.com/dotnet/efcore/issues/12100

**Closed** 2022-10-16 18:39 UTC
Labels: customer-reported
