### ISSUE TITLE
Testing with InMemory and DI (No ASP.Net)

### ISSUE THREAD

**Issue by MPasadu** [dotnet/efcore#15788] opened 2019-05-23 16:40 UTC
I think this issue is related to: https://github.com/aspnet/EntityFrameworkCore/issues/4988

I am trying to create a integration/acceptance test that writes into the inMemory db and then reads it.

But when using:

`serviceCollection.AddDbContext<ServiceContext>(options => options.UseInMemoryDatabase("Service"), ServiceLifetime.Transient);`

and then writing:

```
// This one is actually called inside a Method Write()
using (var context = serviceProvider.GetService<ServiceContext>())
{
    // do write
}
```

```
// This one is actually called inside a Method Read()
using (var context = serviceProvider.GetService<ServiceContext>())
{
    // do read
}
```

The second context is a new inMemory db that is empty. But when using ServiceLifetime.Singleton or ServiceLifetime.Scoped, I get the error messages that the context is already disposed.

Since I want to test the Methods `Write()` and `Read()`, I can't just put both logic into the same using statement.

**Comment by ajcvickers** [comment] 2019-05-24 17:15
@MPasadu This is likely due to the way the `DbContext` is being configured. Can you post the code you have that calls `AddDbContext` and/or is in `OnConfiguring`.

**Comment by ajcvickers** [comment] 2019-05-31 16:32
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:22 UTC
Labels: closed-could-not-reproduce, customer-reported
