### ISSUE TITLE
Scaffold Exclude Tables

### ISSUE THREAD

**Issue by chassq** [dotnet/efcore#10149] opened 2017-10-24 17:13 UTC
Just seeing if there is a way to tell scaffold to skip specific tables/schema? Thanks!

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10 Pro Latest
IDE: Visual Studio 2017

**Comment by bricelam** [comment] 2017-10-24 19:35
Duplicate of #6182

**Closed** 2022-10-16 11:55 UTC
