### ISSUE TITLE
"More than one DbContext was found" when migrating database in a vanilla project

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#7297] opened 2016-12-22 02:18 UTC
_From @Biarity on December 21, 2016 7:57_

When creating a new ASP.NET Core MVC project, then running:
`Add-Migration _some_name`,
`Update-Database`,
I get:
`More than one DbContext was found. Specify which one to use. Use the '-Context' parameter for PowerShell commands and the '--context' parameter for dotnet commands.`

Any idea why? Isn't `ApplicationDbContext` the only one there? But then running
`Update-Database -Context "ApplicationDbContext"` gives:
`No parameterless constructor was found on 'ApplicationDbContext'. Either add a parameterless constructor to 'ApplicationDbContext' or add an implementation of 'IDbContextFactory<ApplicationDbContext>' in the same assembly as 'ApplicationDbContext'.`

However, my `ApplicationDbContext` class has the following parameterless constructor:
`public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }`
so I'm not sure why it isn't working.

Same issue on VS 2015 & VS 2017 RC 2.

_Copied from original issue: aspnet/Mvc#5626_

**Comment by divega** [comment] 2016-12-22 02:18
_From @Eilon on December 22, 2016 1:36_

@divega any idea on this? Do you need more info to investigate?

**Comment by ajcvickers** [comment] 2017-01-03 18:22
@Biarity Not sure why you are getting the first error, but the constructor you posted is not parameterless; it has the ApplicationDbContext parameter.

**Comment by divega** [comment] 2017-01-06 19:59
@Biarity could you provide a repro project for this?

**Comment by rowanmiller** [comment] 2017-01-27 19:24
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by DoubleExposure** [comment] 2017-06-20 14:09
In this thread there are two references and each one references the other ( (Circular) #5646 references this thread #7297 and vice versa). 
What was the cause of this problem? Thanks

**Comment by bricelam** [comment] 2017-06-20 15:57
> What was the cause of this problem?

We never heard back from the original reporter, so we weren't able to understand the issue.

If you are experiencing the same problem, please file a new issue so we can investigate further.

**Closed** 2022-10-16 10:47 UTC
