### ISSUE TITLE
EF Core 5.0 Many-to-Many generating table with weird column names.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/efcore#22810] opened 2020-09-28 12:55 UTC
Here are the entities:

```
public class Post
{
    public long PostId { get; set; }
    public string Name { get; set; }

    public ICollection<Tag> Tags { get; set; }
}

public class Tag
{
    public long TagId { get; set; }
    public string Name { get; set; }

    public ICollection<Post> Posts { get; set; }
}
```

Generated migration is:

    migrationBuilder.CreateTable(
          name: "PostTag",
          columns: table => new
          {
               PostsPostId = table.Column<long>(type: "bigint", nullable: false), --> Look at the column name
               TagsTagId = table.Column<long>(type: "bigint", nullable: false) --> Look at the column name
          },
          constraints: table =>
          {
               table.PrimaryKey("PK_PostTag", x => new { x.PostsPostId, x.TagsTagId });
               table.ForeignKey(
                        name: "FK_PostTag_Posts_PostsPostId",
                        column: x => x.PostsPostId,
                        principalSchema: "Blog",
                        principalTable: "Posts",
                        principalColumn: "PostId",
                        onDelete: ReferentialAction.Cascade);
               table.ForeignKey(
                        name: "FK_PostTag_Tags_TagsTagId",
                        column: x => x.TagsTagId,
                        principalSchema: "Blog",
                        principalTable: "Tags",
                        principalColumn: "TagId",
                        onDelete: ReferentialAction.Cascade);
           });

    migrationBuilder.CreateIndex(
           name: "IX_PostTag_TagsTagId",
           table: "PostTag",
           column: "TagsTagId");

Look at the `PostTag` table's column name! These are `PostsPostId` and `TagsTagId` instead of plain `PostId` and `TagId`.

Another point to be noted: Should not many-to-many table name be `PostTags` instead of `PostTag` as EF Core generate other table names as `Posts` and `Tags`?

By the way, Is there any workaround so that I can specify the table name, left column name, and right column name as well in many-to-many join table without extra CLR class?

**Update: Even changing the column names from `PostsPostId` and `TagsTagId` to `PostId` and `TagId` during migration does not work for the query because query expect these should be `PostsPostId` and `TagsTagId`.**

Thank you.

**Comment by pantonis** [comment] 2020-09-28 14:00
@TanvirArjel ```PostsPostId ``` => TableName pluralized + PrimaryKey. In your case Post table in plural becomes Posts + PostId => PostsPostId. The same for Tag. If you want to have PostsId just rename your primary key to Id. For pluralizing issue please check [this](https://github.com/dotnet/efcore/issues/22712) where ajvickers mentioned the reason

**Comment by TanvirArjel** [comment] 2020-09-28 14:04
I have understood this but this looks weird, isn’t it? However, there should option to rename column names and table name.

**Comment by pantonis** [comment] 2020-09-28 14:31
Didn't try it but [this](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew) might work

**Comment by TanvirArjel** [comment] 2020-09-28 14:45
@pantonis No! It needs an extra CLR class as it was in EF Core 3.1.

**Comment by pantonis** [comment] 2020-09-28 14:55
Yes you need to add the join table. Documentation is incomplete. I suppose the guys at EF Core team prioritized the bug fixing and most probably they will complete docs when everything is done.

**Comment by ajcvickers** [comment] 2020-09-28 22:45
Duplicate of #22712. Documentation tracked by https://github.com/dotnet/EntityFramework.Docs/issues/1978.

**Closed** 2022-10-16 19:01 UTC
Labels: customer-reported
