### ISSUE TITLE
Query: include on groupby key doesn't get applied when the key is entity

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12340] opened 2018-06-12 19:44 UTC
query using gears of war model:

```
ctx.Gears.GroupBy(g => g.CityOfBirth)
    .OrderBy(g => g.Key.Name)
    .Select(g => g.Key)
    .Include(c => c.BornGears).ThenInclude(g => g.Weapons)
```

the includes should be applied, but they are not at the moment

**Comment by ajcvickers** [comment] 2018-06-13 00:44
Putting this on the backlog for now, but we should consider it along with #12238, which may mean that it never gets implemented.

**Comment by AndriySvyryd** [comment] 2019-08-22 22:47
Duplicate of #16752?

**Closed** 2022-10-16 12:31 UTC
