### ISSUE TITLE
Union - Can't process set operations after client evaluation

### ISSUE THREAD

**Issue by mdmoura** [dotnet/efcore#21148] opened 2020-06-05 12:59 UTC
I have the following query using EF Core 3.1:

    var products = products.Where(x => x.UserId == userId);

    var services = services.Where(x => x.UserId == userId);

    var combined = 
        
      products.Select(x => new Model {
        Id = x.Id,
        Category = new CategoryModel {
          Id = x.Group.Category.Id
        }
      })
      .Union(
        services.Select(x => new Model {
          Id = x.Id,
          Category = x.Category == null ? null : new CategoryModel {
            Id = x.Category.Id
          }
        }));

    var count = await combined.CountAsync();

On the count query I get the following error:

    Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.Relational.dll: 'Can't process set operations after client evaluation, consider moving the operation before the last Select() call (see issue #16243)'

If I remove the condition to check if Category is null:

    Category = x.Category == null ? null : new CategoryModel {
      Id = x.Category.Id
    }

And replace it by then I will not have any error.

    Category = new CategoryModel {
      Id = x.Category.Id
    }

The problem is that a Service that Category can be null.
### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system: Mac OS Catalina 10.15.4
IDE: Visual Studio Code 1.45.1

**Comment by roji** [comment] 2020-06-05 13:30
Duplicate of #16243

**Comment by roji** [comment] 2020-06-05 13:30
This is a known current limitation. However, you can rewrite your query so that the Union operation occurs before client evaluation does - see the examples in #16243.

**Comment by mdmoura** [comment] 2020-06-05 14:24
@roji I've saw that issue before. You mean using:

```
var products = products.Where(x => x.UserId == userId);

var services = services.Where(x => x.UserId == userId);

var r1 = products.Select(x => new Model {
    Id = x.Id,
    Category = new CategoryModel {
      Id = x.Group.Category.Id
    }
  })

var r2 = services.Select(x => new Model {
      Id = x.Id,
      Category = x.Category == null ? null : new CategoryModel {
        Id = x.Category.Id
      }
    }));
    
var combined = r1.Union(r2);

var count = await combined.CountAsync();
```

I also tried this but I get the same error. Am I missing something?

**Comment by roji** [comment] 2020-06-05 15:08
@mdmoura, I don't have your full code, so I can't know exactly what's going on (e.g. what are products/services?). Something in your query is triggering client evaluation, and you need to move your Union to happen before that. In your code sample, Union is the last operation, so after the client evaluation.

If you're not sure how to proceed, please post a full code sample (model+query), and I'll try to help.

**Comment by mdmoura** [comment] 2020-06-05 15:18
@roji products and services are simply IQueryables from a DbContext:

        IQueryable<Product> products = _context.Products.AsNoTracking();

        IQueryable<Service> services = _context.Services.AsNoTracking();

I just updated my previous post and will try to create a full code example.

**Comment by roji** [comment] 2020-06-05 15:34
I'm really going to need to see a runnable code sample to look into this...

**Comment by mdmoura** [comment] 2020-06-05 22:42
>> I'm really going to need to see a runnable code sample to look into this...

Sure, you will get the error on the last query, e.g., CountAsync:

        using (SqliteConnection connection = new SqliteConnection("DataSource=:memory:")) {
          
          await connection.OpenAsync();

          var options = new DbContextOptionsBuilder<DataContext>().UseSqlite(connection).Options;
        
          using (DataContext context = new DataContext(options)) {
            await context.Database.EnsureCreatedAsync();    
          }

          using (DataContext context = new DataContext(options)) {
            Random random = new Random();
            foreach (var i in Enumerable.Range(1, 8)) 
              context.Add(new Category());
            foreach (var i in Enumerable.Range(1, 4)) {
              context.Add(new Product { CategoryId = random.NextBoolean() ? new Nullable<Int32>() : random.Next(1, 8) });
              context.Add(new Service { CategoryId = random.Next(1, 8) });
            }
            context.SaveChanges();   
          }

          using (DataContext context = new DataContext(options)) {

            IQueryable<Product> products = context.Products.AsNoTracking();

            IQueryable<Service> services = context.Services.AsNoTracking();

            products = products.Where(x => x.Id > 1);

            services = services.Where(x => x.Id > 1);

            IQueryable<Model> r1 = products.Select(x => new Model {
              Id = x.Id,
              Category = x.Category == null ? null : new CategoryModel {
                Id = x.Category.Id
              }
            });

            IQueryable<Model> r2 = services.Select(x => new Model {
              Id = x.Id,
              Category = new CategoryModel {
                Id = x.Category.Id
              }
            });

            var result = r1.Union(r2);

            var count = await result.CountAsync();

          }

        };

```
  public class DataContext : DbContext {

    public DbSet<Product> Products { get; set; }
    public DbSet<Service> Services { get; set; }
    public DbSet<Category> Categories { get; set; }

    public DataContext(DbContextOptions<DataContext> options) : base(options) { }

    protected override void OnModelCreating(ModelBuilder builder) {

      builder.Entity<Product>(x => {
        x.ToTable("Products");
        x.HasKey(y => y.Id);
        x.Property(y => y.Id).UseIdentityColumn();  
        x.HasOne(y => y.Category).WithMany(y => y.Products).HasForeignKey(y => y.CategoryId).IsRequired(false);
      });

      builder.Entity<Service>(x => {
        x.ToTable("Services");
        x.HasKey(y => y.Id);
        x.Property(y => y.Id).UseIdentityColumn();  
        x.HasOne(y => y.Category).WithMany(y => y.Services).HasForeignKey(y => y.CategoryId).IsRequired(true);
      });

      builder.Entity<Category>(x => {
        x.ToTable("Categories");
        x.HasKey(y => y.Id);
        x.Property(y => y.Id).UseIdentityColumn();
      });

    }

  }

  public class Product { 
    public Int32 Id { get; set; }
    public Int32? CategoryId { get; set; }
    public virtual Category Category { get; set; }
  }

  public class Service { 
    public Int32 Id { get; set; }
    public Int32 CategoryId { get; set; }
    public virtual Category Category { get; set; }
  }

  public class Category { 
    public Int32 Id { get; set; }
    public virtual List<Product> Products { get; set; }
    public virtual List<Service> Services { get; set; }
  }

  public class Model {
    public Int32 Id { get; set; }
    public CategoryModel Category { get; set; }
  }

  public class CategoryModel {
    public Int32 Id { get; set; }
  }
```

Does this help?

**Comment by roji** [comment] 2020-06-06 09:16
@mdmoura thanks for the runnable repro - that's exactly the kind of info we need. With the help of your code I could reproduce the issue, and it's unrelated to set operations - the conditional expression causes translation failure (and therefore client evaluation) regardless of the set operation, which in turn causes the set operation to fail with the error above.

I've opened #21157 with a minimal repro for that issue, as this one is already somewhat long. As a workaround, you can omit the conditional expression: EF Core is implicitly null-safe, and your code above should produce the correct results even when a product's category is null (even if that would throw a NullReferenceException when executed in regular LINQ to Objects).

Thanks again for reporting!

**Comment by roji** [comment] 2020-06-06 09:18
Duplicate of #21157

**Closed** 2022-10-16 18:28 UTC
Labels: closed-duplicate, customer-reported
