### ISSUE TITLE
I can't add a defining query that uses a left join 

### ISSUE THREAD

**Issue by ChannelSix** [dotnet/efcore#19845] opened 2020-02-08 16:00 UTC
If I create a defining query that uses a left join in EF Core v3.1.1 I get the exception below when attempting to query the defining query. Note that I can't use navigation properties on my actual models.

If I run the exact same expression through a normal query it runs fine.

### Steps to reproduce

``` C#
    class Program
    {
        static async Task Main(string[] args)
        {
            var context = new Context();
            var adHocQuery = from p in context.Set<Parent>()
                        join c in context.Set<Child>() on p.Id equals c.ParentId into outer
                        from cLeft in outer
                        select new ParentChild
                        {
                            ParentId = p.Id,
                            ParentName = p.Name,
                            ChildId = cLeft == null ? (int?)null : cLeft.Id,
                            ChildName = cLeft == null ? null : cLeft.Name
                        };
            var adHocQueryResult = await adHocQuery.ToArrayAsync();
            var joined = await context.Set<ParentChild>().ToArrayAsync();
        }
    }

    public class Parent
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class Child
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ParentId { get; set; }
    }

    public class ParentChild
    {
        public int ParentId { get; set; }
        public string ParentName { get; set; }
        public int? ChildId { get; set; }
        public string ChildName { get; set; }
    }

    public class Context : DbContext
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Parent>()
                .HasKey(p => p.Id);
            modelBuilder.Entity<Child>()
                .HasKey(c => c.Id);

            modelBuilder.Entity<ParentChild>()
                .HasNoKey()
                .ToQuery(() =>
                    from p in Set<Parent>()
                    join c in Set<Child>() on p.Id equals c.ParentId into outer
                    from cLeft in outer
                    select new ParentChild
                    {
                        ParentId = p.Id,
                        ParentName = p.Name,
                        ChildId = cLeft == null ? (int?)null : cLeft.Id,
                        ChildName = cLeft == null ? null : cLeft.Name
                    }
            );
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder
                .UseSqlServer("server=(local);Database=EFDefiningQueryLeftJoin;Integrated Security=SSPI;")
                .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
        }
    }
```

### Exception: 
System.InvalidOperationException: 'Processing of the LINQ expression 'DbSet<Parent>
    .GroupJoin(
        outer: DbSet<Child>, 
        inner: p => p.Id, 
        outerKeySelector: c => c.ParentId, 
        innerKeySelector: (p, outer) => new { 
            p = p, 
            outer = outer
         })' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.'

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:. NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.4

**Comment by ajcvickers** [comment] 2020-02-10 18:25
@maumar to take a look.

**Comment by maumar** [comment] 2020-02-10 23:36
dupe of #19708

**Comment by maumar** [comment] 2020-02-10 23:38
@ChannelSix you can use QueryableExtensions.LeftJoin method directly as a workaround:

```
                modelBuilder.Entity<ParentChild>()
                    .HasNoKey()
                    .ToQuery(() =>
                        Set<Parent>().LeftJoin(Set<Child>(), k => k.Id, k => k.ParentId, (p, cLeft) => new ParentChild
                        {
                            ParentId = p.Id,
                            ParentName = p.Name,
                            ChildId = cLeft == null ? (int?)null : cLeft.Id,
                            ChildName = cLeft == null ? null : cLeft.Name
                        }));
```

QueryableExtensions is defined in `Microsoft.EntityFrameworkCore.Internal` namespace

**Comment by ChannelSix** [comment] 2020-02-11 08:24
Thanks for looking at this and the suggestion.

**Closed** 2022-10-16 18:10 UTC
Labels: closed-duplicate, customer-reported
