### ISSUE TITLE
Hours Wasted assuming the framework could handle a complex object save(insert, or update)

### ISSUE THREAD

**Issue by C-BERBER** [dotnet/efcore#17506] opened 2018-10-02 19:17 UTC
I foolishly assumed that the EF would understand based on all of the keying relationships I defined what was a new object vs what was to be updated (or even removed). 

It seems to me that there should be one method that performs this for any complex model.

Having to manage the implementation above will require a lot of redundant code across multiple levels of a big data model. This is a great opportunity for a framework to shine...

If it does this somewhere else and I just haven't uncovered it please let me know. 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 130521ba-2943-c640-4190-7e22af37e154
* Version Independent ID: c31908e9-2836-8efd-5df6-e9dc5b5a9a5f
* Content: [Working with entity states - EF6](https://docs.microsoft.com/en-us/ef/ef6/saving/change-tracking/entity-state)
* Content Source: [entity-framework/ef6/saving/change-tracking/entity-state.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/saving/change-tracking/entity-state.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-08-29 20:53
Duplicate of #5536

**Closed** 2022-10-16 14:38 UTC
Labels: closed-duplicate
