### ISSUE TITLE
Include of child entities is ignored with complex where clause (ef 2.1-preview)

### ISSUE THREAD

**Issue by pgroene** [dotnet/efcore#11705] opened 2018-04-17 12:06 UTC
Include is ignored when adding a complex where clause to a query

### Steps to reproduce
Create a object with child object
Make a query with a:
 `Include(c => c.Childs)`
Add a where clause
  `Where(x => x == y)`

Add a more complex Where clause
  `.Where(x=> codes.Any(c => EF.Functions.Like(x.ContractCode, c)))` 

Get the results:
   `.ToListAsync()`

The include entities are not included. Expected that they are included. When leaving out the complex where, the child entities are included.

```c#
string[] items = new string[]{ 'a',b'};

await _dbContext.Parent
            .Include(r => r.Chlild)
            .Where(r => r.Col == "val")
            .Where(r => items .Any(c => EF.Functions.Like(r, c)))
            .ToListAsync();
```

### Further technical details
EF Core version: 2.1-preview
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: windows/linux inside docker container
IDE: VS latest version

**Comment by ajcvickers** [comment] 2018-04-17 16:50
@pgroene Are you using preview1 or preview2?

**Comment by smitpatel** [comment] 2018-04-17 18:43
This works correctly for me in preview1 & preview2. Regardless of how complex the `Where` is, it would just filter out `Parent` only. And whenever `Parent` is returned any associated `Childs` are included.

Please post a runnable repro code which demonstrate the issue you are seeing.

**Comment by pgroene** [comment] 2018-04-17 19:11
@ajcvickers I use preview1 at the moment, I'll try to make a runnable sample which demonstrates the issue.

**Comment by pgroene** [comment] 2018-04-23 09:14
In the project I'm working on we see the issue, however when creating a small project the behavoir seems to be correct. Till now I was not able to figure out what causes the issue. The only thing I have not tested yet is IMigrationsAnnotationProvider or IMigrationsSqlGenerator.

**Comment by divega** [comment] 2018-04-30 18:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

Please re-open if you are able to provide a repro.

**Closed** 2022-10-16 12:19 UTC
Labels: closed-could-not-reproduce
