### ISSUE TITLE
How to setting a model with table don't have any primary key column?

### ISSUE THREAD

**Issue by ndphuong** [dotnet/efcore#9517] opened 2017-08-22 09:04 UTC
The EFCore throw exception: `The entity type  XXX requires a primary key to be defined`
But our table don't have any primary key column

How to avoid this ?

**Comment by ajcvickers** [comment] 2017-08-22 17:32
@ndphuong EF Core requires all mapped entity types to have a primary key defined. This is needed so that different entity instances can be uniquely identified for tracking.

Can you provide some details of what you are trying to do so we might be able to give some advice on how to approach it.

**Comment by ndphuong** [comment] 2017-08-23 12:09
@ajcvickers 
We are using EFCore to try access a read-only database
Some table don't have any primary key column so EF throws exception

**Comment by ajcvickers** [comment] 2017-08-23 16:58
@ndphuong This is covered by #9290 and #1862 may also have useful information for you.

Closing this as a duplicate of #9290

**Closed** 2022-10-16 11:17 UTC
Labels: closed-duplicate
