### ISSUE TITLE
Check for arithmetic overflow and SELECT with (int)? Max throws KeyNotFoundException

### ISSUE THREAD

**Issue by GraySerg** [dotnet/efcore#25305] opened 2021-07-21 11:01 UTC
## File a bug
Check option "Check for arithmetic overflow" on project
### Include your code
```C#
    public class LogContext : DbContext
    {
        public LogContext(DbContextOptions<LogContext> options) : base(options)
        {
        }
        public DbSet<AccountLog> AccountLogs { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.ApplyConfiguration(new AccountLogConfiguration());
        }
    }
    [Table("AccountLogs")]
    public class AccountLog
    {
        public AccountLog()
        {

        }
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int AccountLogId { get; }
        public string Text { get; set; }
        public DateTime Time { get; }
    }
    internal class AccountLogConfiguration : IEntityTypeConfiguration<AccountLog>
    {

        public void Configure(EntityTypeBuilder<AccountLog> builder)
        {
            builder.Property(x => x.AccountLogId);
            builder.Property(x => x.Text);
            builder.Property(x => x.Time);
        }
    }
    class Program
    {
        static async Task Main(string[] args)
        {
            var finoptions = new Microsoft.EntityFrameworkCore.DbContextOptionsBuilder<LogContext>().UseSqlServer("server=localhost;Integrated Security=SSPI;MultipleActiveResultSets=true;Initial Catalog=MyDb", options => options.EnableRetryOnFailure());
            LogContext ct = new LogContext(finoptions.Options);
            int maxCode = ct.AccountLogs.Select(x => x.AccountLogId).Max();//Works
            int maxCodeFailed = ct.AccountLogs.Select(x => (int?)x.AccountLogId).Max().GetValueOrDefault(0);//Exception here
}
}
```

### Include stack traces

   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateMax(ShapedQueryExpression source, LambdaExpression selector, Type resultType)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at ConsoleApp8.Program.<Main>d__0.MoveNext() in E:\Projects\ConsoleApp8\ConsoleApp8\Program.cs:line 72

### Include provider and version information

EF Core version:
3.1.17
Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Framework 4.8
Operating system:
Windows 10 Pro
IDE: (e.g. Visual Studio 2019 16.10.3)

**Comment by ajcvickers** [comment] 2021-07-26 13:49
@GraySerg Can you try this on EF Core 5.0? We believe it is likely fixed there. A workaround is to disable overflow checking around the query, using `unchecked`. Overflow checking is not translated to SQL, so this should not change the SQL query generated.

**Comment by ajcvickers** [comment] 2021-08-03 15:25
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by GraySerg** [comment] 2021-08-09 13:36
I can't try in on EF Core 5.0 because it's not available on .Net Framework 4.8 platform

**Closed** 2022-10-16 19:40 UTC
Labels: closed-could-not-reproduce, customer-reported
