### ISSUE TITLE
Unable to determine the relationship represented by navigation property

### ISSUE THREAD

**Issue by mkurak** [dotnet/efcore#18300] opened 2019-10-09 18:52 UTC
This error occurs between 2 tables. One of them is the "User" table and the other is the "UserMessage" table.

While this error is running in Core 2.2 version, this error occurs after Core 3 update.

`System.InvalidOperationException: Unable to determine the relationship represented by navigation property 'User.UserMessageFromUser' of type 'ICollection<UserMessage>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.`

**User Tablo Content:**
```
USE [CSBEF]
GO

/****** Object:  Table [dbo].[UserManagement_User]    Script Date: 9.10.2019 21:15:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserManagement_User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[Surname] [nvarchar](256) NULL,
	[ProfilePic] [nvarchar](256) NULL,
	[ProfileBgPic] [nvarchar](256) NULL,
	[ProfileStatusMessage] [nvarchar](512) NULL,
	[UserName] [nvarchar](32) NULL,
	[Email] [nvarchar](256) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
	[Status] [bit] NULL,
	[AddingDate] [datetime] NOT NULL,
	[UpdatingDate] [datetime] NOT NULL,
	[AddingUserId] [int] NULL,
	[UpdatingUserId] [int] NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[UserManagement_User] ADD  CONSTRAINT [DF_User_Status]  DEFAULT ((1)) FOR [Status]
GO

ALTER TABLE [dbo].[UserManagement_User] ADD  CONSTRAINT [DF_User_AddingDate]  DEFAULT (getdate()) FOR [AddingDate]
GO

ALTER TABLE [dbo].[UserManagement_User] ADD  CONSTRAINT [DF_UserManagement_User_UpdatingDate]  DEFAULT (getdate()) FOR [UpdatingDate]
GO
```

**UserMessage Table Content:**
```
USE [CSBEF]
GO

/****** Object:  Table [dbo].[UserManagement_UserMessage]    Script Date: 9.10.2019 21:15:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserManagement_UserMessage](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FromUserId] [int] NOT NULL,
	[ToUserId] [int] NOT NULL,
	[Message] [nvarchar](4000) NOT NULL,
	[ViewStatus] [bit] NOT NULL,
	[ViewDate] [datetime] NULL,
	[Status] [bit] NULL,
	[AddingDate] [datetime] NOT NULL,
	[UpdatingDate] [datetime] NOT NULL,
	[AddingUserId] [int] NULL,
	[UpdatingUserId] [int] NULL,
 CONSTRAINT [PK_UserManagement_UserMessage] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[UserManagement_UserMessage] ADD  CONSTRAINT [DF_UserManagement_UserMessage_ViewStatus]  DEFAULT ((0)) FOR [ViewStatus]
GO

ALTER TABLE [dbo].[UserManagement_UserMessage] ADD  CONSTRAINT [DF_UserManagement_UserMessage_Status_1]  DEFAULT ((1)) FOR [Status]
GO

ALTER TABLE [dbo].[UserManagement_UserMessage] ADD  CONSTRAINT [DF_UserManagement_UserMessage_AddingDate_1]  DEFAULT (getdate()) FOR [AddingDate]
GO

ALTER TABLE [dbo].[UserManagement_UserMessage] ADD  CONSTRAINT [DF_UserManagement_UserMessage_UpdatingDate_1]  DEFAULT (getdate()) FOR [UpdatingDate]
GO

ALTER TABLE [dbo].[UserManagement_UserMessage]  WITH CHECK ADD  CONSTRAINT [FK_UserManagement_UserMessage_UserManagement_User_FromUserId] FOREIGN KEY([FromUserId])
REFERENCES [dbo].[UserManagement_User] ([Id])
GO

ALTER TABLE [dbo].[UserManagement_UserMessage] CHECK CONSTRAINT [FK_UserManagement_UserMessage_UserManagement_User_FromUserId]
GO

ALTER TABLE [dbo].[UserManagement_UserMessage]  WITH CHECK ADD  CONSTRAINT [FK_UserManagement_UserMessage_UserManagement_User_ToUserId] FOREIGN KEY([ToUserId])
REFERENCES [dbo].[UserManagement_User] ([Id])
GO

ALTER TABLE [dbo].[UserManagement_UserMessage] CHECK CONSTRAINT [FK_UserManagement_UserMessage_UserManagement_User_ToUserId]
GO
```

**User POCO Model Content:**
```
using CSBEF.Core.Models;
using System.Collections.Generic;

namespace CSBEF.Module.UserManagement.Poco
{
    public partial class User : EntityModelBase
    {
        public User()
        {
            Token = new HashSet<Token>();
            UserInGroup = new HashSet<UserInGroup>();
            UserInRole = new HashSet<UserInRole>();
            UserMessageFromUser = new HashSet<UserMessage>();
            UserMessageToUser = new HashSet<UserMessage>();
        }

        public string Name { get; set; }
        public string Surname { get; set; }
        public string ProfilePic { get; set; }
        public string ProfileBgPic { get; set; }
        public string ProfileStatusMessage { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Token> Token { get; set; }
        public virtual ICollection<UserInGroup> UserInGroup { get; set; }
        public virtual ICollection<UserInRole> UserInRole { get; set; }
        public virtual ICollection<UserMessage> UserMessageFromUser { get; set; }
        public virtual ICollection<UserMessage> UserMessageToUser { get; set; }
    }
}
```

**UserMessage POCO Model Content:**
```
using CSBEF.Core.Models;
using System;

namespace CSBEF.Module.UserManagement.Poco
{
    public partial class UserMessage : EntityModelBase
    {
        public int FromUserId { get; set; }
        public int ToUserId { get; set; }
        public string Message { get; set; }
        public bool ViewStatus { get; set; }
        public DateTime? ViewDate { get; set; }

        public virtual User FromUser { get; set; }
        public virtual User ToUser { get; set; }
    }
}
```

**User table ef builder code:**
```
            modelBuilder.Entity<User>(entity =>
            {
                entity.ToTable("UserManagement_User");

                entity.Property(e => e.AddingDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(256);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(256);

                entity.Property(e => e.Password).IsRequired();

                entity.Property(e => e.ProfileBgPic).HasMaxLength(256);

                entity.Property(e => e.ProfilePic).HasMaxLength(256);

                entity.Property(e => e.ProfileStatusMessage).HasMaxLength(512);

                entity.Property(e => e.Status).HasDefaultValueSql("((1))");

                entity.Property(e => e.Surname).HasMaxLength(256);

                entity.Property(e => e.UpdatingDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.UserName).HasMaxLength(32);
            });
```

UserMessage table ef builder code:
```
            modelBuilder.Entity<UserMessage>(entity =>
            {
                entity.ToTable("UserManagement_UserMessage");

                entity.HasIndex(e => e.FromUserId);

                entity.HasIndex(e => e.ToUserId);

                entity.Property(e => e.AddingDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Message)
                    .IsRequired()
                    .HasMaxLength(4000);

                entity.Property(e => e.Status).HasDefaultValueSql("((1))");

                entity.Property(e => e.UpdatingDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ViewDate).HasColumnType("datetime");

                entity.HasOne(d => d.FromUser)
                    .WithMany(p => p.UserMessageFromUser)
                    .HasForeignKey(d => d.FromUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.ToUser)
                    .WithMany(p => p.UserMessageToUser)
                    .HasForeignKey(d => d.ToUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });
```

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer 3.0.0
Target framework: .NET Core 3
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.3

**Comment by ajcvickers** [comment] 2019-10-11 22:01
@mkurak I have not been able to reproduce this with the code supplied above. Please post a small, runnable project/solution or _complete_ code listing that demonstrates the behavior you are seeing.

**Comment by mkurak** [comment] 2019-10-12 14:37
@ajcvickers  I'm having this problem with a project on my Github profile, but I'm currently making some improvements to this project. I think it's over today. Therefore, if you give me 1-2 days, a structure will be ready for you to test comfortably. For now I've removed the Foraign connections from the POCO models, so it can work. I'll reactivate the connections when you can test them.

**Comment by ajcvickers** [comment] 2019-10-21 16:16
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:48 UTC
Labels: closed-could-not-reproduce, customer-reported
