### ISSUE TITLE
Support new LINQ methods

### ISSUE THREAD

**Issue by BenjaminBrienen** [dotnet/efcore#34767] opened 2024-09-26 16:36 UTC
Using `.Order()` in an EF Core 8 LINQ expression fails at runtime when it can't be translated to SQL.

See: https://github.com/dotnet/roslynator/issues/1541

**Comment by roji** [comment] 2024-09-27 07:24
Duplicate of #28634

**Comment by roji** [comment] 2024-09-27 07:24
This was done for 9.0.

**Closed by roji** 2024-09-27 07:24 UTC
Labels: customer-reported
