### ISSUE TITLE
Migration update fails in UWP with SQLite and EF7

### ISSUE THREAD

**Issue by yeasin90** [dotnet/efcore#5307] opened 2016-05-09 17:52 UTC
I added a new filed in my model class and generate a new migration file with the command : 
**Add-Migration MyNewMigration**

When I start the application, the following code : 

```
public App()

        {
            this.InitializeComponent();
            this.Suspending += OnSuspending;

            try
            {
                using (var db = new BloggingContext())
                {
                    db.Database.Migrate();
                }
            }
            catch(Exception ex)
            {

            }
        }
```

throws exception : **SQLite cannot support this migration operation.**

Packages I have installed are : **Install-Package EntityFramework.SQLite –Pre**
and : **Install-Package EntityFramework.Commands –Pre**

**Comment by ErikEJ** [comment] 2016-05-09 18:34
Maybe your migration is hit by one of the many sqlite limitations: http://ef.readthedocs.io/en/latest/providers/sqlite/limitations.html

**Comment by natemcmaster** [comment] 2016-05-15 03:37
From http://sqlite.org/lang_altertable.html#otheralter

> The only schema altering commands directly supported by SQLite are the "rename table" and "add column" commands.

This means to perform operations such as "DROP COLUMN", EF would need to do a table rebuild. We haven't implemented this yet.

Closing as a duplicate of https://github.com/aspnet/EntityFramework/issues/329

**Comment by rowanmiller** [comment] 2016-05-17 17:17
Opened https://github.com/aspnet/EntityFramework/issues/5389 to provide more help in this situation.

**Closed** 2022-10-16 09:40 UTC
