### ISSUE TITLE
Model creation performance regresssion from 8.0.1 to 8.0.2

### ISSUE THREAD

**Issue by ascott18** [dotnet/efcore#33274] opened 2024-03-08 21:18 UTC
## File a bug

The construction of the Model in the below code executes in the following durations on different versions of EF:

- 8.0.1: **< 1 second**
- 8.0.2: **1 minute 30 seconds**
- 9.0.0-preview.1.24081.2: **2 minutes 50 seconds**

It is a vastly simplified model from my real application (the real application has far more intricate relations between models than the linear vertical hierarchy in the below code), but it replicates the same issue for the same reasons: The queue in `Property.GetConversion` grows extremely large:

![image](https://github.com/dotnet/efcore/assets/5017521/bf8c7060-c3d7-47cd-a5eb-f4644066cb15)

Against my actual application, at some random points that I broke in with the debugger I saw it as large as 2 million items:
![image](https://github.com/dotnet/efcore/assets/5017521/b678a89a-bd0c-4efd-aacf-f889434fde38)

### Include your code

```C#

using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;

var stopwatch = Stopwatch.StartNew();

var context = new AppDbContext();
context.Model.ToString();

Console.WriteLine(stopwatch.Elapsed);

public class Tenant
{
	public int TenantId { get; set; }

	public string Name { get; set; }
}

public class ApplicationUser : TenantedBase
{
	public string UserName { get; set; }
}

[PrimaryKey(nameof(TenantId), nameof(Id))]
public abstract class TenantedBase
{
	public int Id { get; set; }
	
	public int TenantId { get; set; }
	public Tenant Tenant { get; set; }
	
	[ForeignKey("TenantId,ModifiedById")]
	public ApplicationUser ModifiedBy { get; set; }
	public int? ModifiedById { get; set; }

	[ForeignKey("TenantId,CreatedById")]
	public ApplicationUser CreatedBy { get; set; }
	public int? CreatedById { get; set; }
}

public class Entity1 :  TenantedBase { }
public class Entity2 :  TenantedBase { public int Entity1Id {get;set;} [ForeignKey("TenantId,Entity1Id")] public Entity1 Entity1 {get;set;} }
public class Entity3 :  TenantedBase { public int Entity2Id {get;set;} [ForeignKey("TenantId,Entity2Id")] public Entity2 Entity2 {get;set;} }
public class Entity4 :  TenantedBase { public int Entity3Id {get;set;} [ForeignKey("TenantId,Entity3Id")] public Entity3 Entity3 {get;set;} }
public class Entity5 :  TenantedBase { public int Entity4Id {get;set;} [ForeignKey("TenantId,Entity4Id")] public Entity4 Entity4 {get;set;} }
public class Entity6 :  TenantedBase { public int Entity5Id {get;set;} [ForeignKey("TenantId,Entity5Id")] public Entity5 Entity5 {get;set;} }
public class Entity7 :  TenantedBase { public int Entity6Id {get;set;} [ForeignKey("TenantId,Entity6Id")] public Entity6 Entity6 {get;set;} }
public class Entity8 :  TenantedBase { public int Entity7Id {get;set;} [ForeignKey("TenantId,Entity7Id")] public Entity7 Entity7 {get;set;} }
public class Entity9 :  TenantedBase { public int Entity8Id {get;set;} [ForeignKey("TenantId,Entity8Id")] public Entity8 Entity8 {get;set;} }
public class Entity10 : TenantedBase { public int Entity9Id {get;set;} [ForeignKey("TenantId,Entity9Id")] public Entity9 Entity9 {get;set;} }
public class Entity11 : TenantedBase { public int Entity10Id {get;set;} [ForeignKey("TenantId,Entity10Id")] public Entity10 Entity10 {get;set;} }
public class Entity12 : TenantedBase { public int Entity11Id {get;set;} [ForeignKey("TenantId,Entity11Id")] public Entity11 Entity11 {get;set;} }
public class Entity13 : TenantedBase { public int Entity12Id {get;set;} [ForeignKey("TenantId,Entity12Id")] public Entity12 Entity12 {get;set;} }
public class Entity14 : TenantedBase { public int Entity13Id {get;set;} [ForeignKey("TenantId,Entity13Id")] public Entity13 Entity13 {get;set;} }
public class Entity15 : TenantedBase { public int Entity14Id {get;set;} [ForeignKey("TenantId,Entity14Id")] public Entity14 Entity14 {get;set;} }
public class Entity16 : TenantedBase { public int Entity15Id {get;set;} [ForeignKey("TenantId,Entity15Id")] public Entity15 Entity15 {get;set;} }
public class Entity17 : TenantedBase { public int Entity16Id {get;set;} [ForeignKey("TenantId,Entity16Id")] public Entity16 Entity16 {get;set;} }
public class Entity18 : TenantedBase { public int Entity17Id {get;set;} [ForeignKey("TenantId,Entity17Id")] public Entity17 Entity17 {get;set;} }
public class Entity19 : TenantedBase { public int Entity18Id {get;set;} [ForeignKey("TenantId,Entity18Id")] public Entity18 Entity18 {get;set;} }
public class Entity20 : TenantedBase { public int Entity19Id {get;set;} [ForeignKey("TenantId,Entity19Id")] public Entity19 Entity19 {get;set;} }

public class AppDbContext : DbContext
{
	public DbSet<ApplicationUser> ApplicationUsers { get; set; }
	public DbSet<Tenant> Tenants { get; set; }
	
	public DbSet<Entity1> Entity1 { get; set; } 
	public DbSet<Entity2> Entity2 { get; set; } 
	public DbSet<Entity3> Entity3 { get; set; } 
	public DbSet<Entity4> Entity4 { get; set; } 
	public DbSet<Entity5> Entity5 { get; set; } 
	public DbSet<Entity6> Entity6 { get; set; } 
	public DbSet<Entity7> Entity7 { get; set; } 
	public DbSet<Entity8> Entity8 { get; set; } 
	public DbSet<Entity9> Entity9 { get; set; } 
	public DbSet<Entity10> Entity10 { get; set; }
	public DbSet<Entity11> Entity11 { get; set; }
	public DbSet<Entity12> Entity12 { get; set; }
	public DbSet<Entity13> Entity13 { get; set; }
	public DbSet<Entity14> Entity14 { get; set; }
	public DbSet<Entity15> Entity15 { get; set; }
	public DbSet<Entity16> Entity16 { get; set; }
	public DbSet<Entity17> Entity17 { get; set; }
	public DbSet<Entity18> Entity18 { get; set; }
	public DbSet<Entity19> Entity19 { get; set; }
	public DbSet<Entity20> Entity20 { get; set; }
	
	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		optionsBuilder.UseSqlServer("asdf");
	}
}
```

### Include provider and version information

EF Core version: 8.0.2
Database provider: Relational (SqlServer and Sqlite both have issue)
Target framework: .NET 8
Operating system: Win 10
IDE: N/A

**Comment by AndriySvyryd** [comment] 2024-03-15 23:25
Duplicate of https://github.com/dotnet/efcore/issues/33176

**Closed by AndriySvyryd** 2024-03-15 23:25 UTC
Labels: customer-reported, area-model-building
