### ISSUE TITLE
about EntityTypeConfiguration

### ISSUE THREAD

**Issue by yongchaohu** [dotnet/efcore#5787] opened 2016-06-16 06:25 UTC
Hello there in EF6.0 in ModelConfiguration.EntityTypeConfiguration, but EFCORE no, and in the ability to add this functionality EFCORE or EFCORE now there is no similar feature, thank you

**Comment by smitpatel** [comment] 2016-06-16 07:55
dupe of #2805 ?

**Comment by rowanmiller** [comment] 2016-06-16 16:50
Closing as dupe

**Closed** 2022-10-16 09:45 UTC
