### ISSUE TITLE
.NET Framework 4.7.2 InMemory EnsureCreated with seeded data then Add new entity throws ArgumentException : An item with the same key has already been added.

### ISSUE THREAD

**Issue by gojanpaolo** [dotnet/efcore#13322] opened 2018-09-13 18:24 UTC
I get the following exception on .NET framework 4.7.2 but not on .NET Core 2.1.

```
Exception message: System.ArgumentException: 'An item with the same key has already been added.'
Stack trace:    
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.Create(IUpdateEntry entry)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryStore.ExecuteTransaction(IReadOnlyList`1 entries, IDiagnosticsLogger`1 updateLogger)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at ClassLibrary1.Tests.EnsureCreated_then_Add_Blog() in
```

### Steps to reproduce

```c#
using Microsoft.EntityFrameworkCore;
using System;
using Xunit;

public class Tests
{
    private readonly DbContextOptions<Context> _options;

    public Tests()
    {
        _options = new DbContextOptionsBuilder<Context>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options;
    }

    [Fact]
    public void Add_Blog()
    {
        using (var ctx = new Context(_options))
        {
            ctx.Add(new Blog());
            ctx.SaveChanges();
        }
    }

    [Fact]
    public void EnsureCreated_then_Add_Blog()
    {
        using (var ctx = new Context(_options))
        {
            ctx.Database.EnsureCreated();
        }

        using (var ctx = new Context(_options))
        {
            ctx.Add(new Blog());
            ctx.SaveChanges();
        }
    }
}
public class Context : DbContext
{
    public Context(DbContextOptions<Context> options) : base(options) { }
    public DbSet<Blog> Blog { get; set; }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>(builder =>
        {
            builder.HasData(
                new Blog { BlogId = 1 });
        });
    }
}
public class Blog
{
    public int BlogId { get; set; }
}
```

### Further technical details
EF Core version: 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Win7
IDE: Visual Studio 2017 15.4

**Comment by gojanpaolo** [comment] 2018-09-13 18:46
Issue seems to be fixed on 2.2.0-preview2-35157.

**Comment by Alexxtheonly** [comment] 2018-09-14 09:55
> Issue seems to be fixed on 2.2.0-preview2-35157.

With this version I also get the error

**Comment by gojanpaolo** [comment] 2018-09-14 13:27
@Alexxtheonly Could you please try this https://github.com/gojanpaolo/ef-core-13322 ?
It has .net core, .net 4.7.2, and .net 4.7.2 w/ ef core 2.2

**Comment by gojanpaolo** [comment] 2018-09-14 14:14
So I just tested again on a new solution and issue still exists in 2.2.0-preview2-35157

**Comment by ajcvickers** [comment] 2018-09-14 19:16
Duplicate of #6872, since in-memory value generation from keys does not currently consider any existing values.

**Closed** 2022-10-16 13:31 UTC
Labels: customer-reported
