### ISSUE TITLE
DBFunction  Cast bug

### ISSUE THREAD

**Issue by lifejoyforpy** [dotnet/efcore#29441] opened 2022-10-27 05:27 UTC
i use DbFunction slove union  filed question ,but i found the efcore sql  translate has bug,
for example .
query1= from a _dbcontext.A.select(t=>new{ name=t.name.add=cast( t.d ,100)})
query2= from a _dbcontext.B.select(t=>new{ name=cast(t.bname,50).add=t.d})
query=query1.union(query2)。
cast function is  
![1666848260996](https://user-images.githubusercontent.com/38183800/198199184-34e99e2d-fcda-4dab-a974-5d6d44882ae6.jpg)
the A tablealia is p. the bTablelias is p1,
but the  unionquery all  cast (fieldArgument.TableAlias)  is  p.the cause  bname cannot bound in database .
what can i do

**Comment by roji** [comment] 2022-10-30 19:20
@lifejoyforpy it's difficult to understand from the above exactly what you're trying to do, and what problem you're trying to solve by defining your custom casting function. Please post a minimal, runnable code sample that shows the LINQ query which is failing for you, and the complete exception details with the stack trace.

**Comment by lifejoyforpy** [comment] 2022-10-30 19:21
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ajcvickers** [comment] 2022-11-07 16:12
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-11-07 16:12 UTC
Labels: customer-reported
