### ISSUE TITLE
OwnsMany primitive type support?

### ISSUE THREAD

**Issue by jasonycw** [dotnet/efcore#14115] opened 2018-12-07 09:24 UTC
Is there a way with the new `OwnsMany` to allow a entity to own a list of string from another table

Models
``` C#
public class User
{
    public Guid UserId { get; set; }
    public string Email { get; set; }
    public IEnumerable<Role> Roles { get; set; }
}
public class Role
{
    public string Value { get; set; }
}
```
DbContext
``` C#
builder.Entity<User>(m =>
{
    #region Mappings
    m.ToTable("User", "user");
    m.HasKey(x => x.UserId);

    m.OwnsMany(x => x.Roles, b =>
    {
        b.ToTable("UserRole", "user");
        b.Property<Guid>("UserId");
        b.Property<Guid>("RoleAssignmentId");
        b.HasKey("RoleAssignmentId");
        b.Property(x => x.Value)
            .HasColumnName("Role");
        b.HasForeignKey("UserId");
    });
    #endregion
});
```
The above is working and when we query for the admin user, we need to 
``` C#
_dbContext_.Set<User>().Where(x => x.Role.Value == "Admin")
```

Is there a way to simplify it to become
``` C#
public class User
{
    public Guid UserId { get; set; }
    public string Email { get; set; }
    public IEnumerable<string> Roles { get; set; }
}
//--------------------------
builder.Entity<User>(m =>
{
    #region Mappings
    m.ToTable("User", "user");
    m.HasKey(x => x.UserId);

    m.OwnsMany(x => x.Roles, b =>
    {
        b.ToTable("UserRole", "user");
        b.Property<Guid>("UserId");
        b.Property<Guid>("RoleAssignmentId");
        b.HasKey("RoleAssignmentId");
        b.Property(x => x)
            .HasColumnName("Role");
        b.HasForeignKey("UserId");
    });
    #endregion
});
```
So this could work
``` C#
_dbContext_.Set<User>().Where(x => x.Role == "Admin")
```

### Further technical details
EF Core version: 2.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 
IDE: Visual Studio 2017 15.9.3

**Comment by ajcvickers** [comment] 2018-12-17 20:50
Duplicate of #4179 for which I added some additional notes about a workaround that uses value converters.

**Closed** 2022-10-16 13:43 UTC
Labels: customer-reported
