### ISSUE TITLE
Migrations: Drop default value constraints as part of DropColumn

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#1844] opened 2015-03-17 21:40 UTC
If you specify a default value in AddColumn then there is a default constraint that needs to be dropped. We could just gen SQL that queries and drops any that are found (pretty sure that's what we did in EF6).

BTW we should also try and generate a better name, currently we let SQL Server pick one and it generates things like `DF__Product__Categor__6A30C649`.

**Comment by bricelam** [comment] 2015-03-18 21:51
Dupe of #1345?

**Comment by rowanmiller** [comment] 2015-03-19 05:57
Yep, sorry for the dupes... tried looking for existing bugs but not sure why I didn't find those ones :confused:

**Closed** 2022-10-16 08:53 UTC
Labels: type-bug
