### ISSUE TITLE
Disable lazy loading proxies on demand

### ISSUE THREAD

**Issue by MaQy** [dotnet/efcore#27570] opened 2022-03-04 12:20 UTC
Hi,

I searched for this but couldn't find any answer other than it is not possible. In EF6 you could disable proxies at any point by changing a setting in the DB Context, but this is no longer possible in EF Core. I have some operations that I perform in bulk given that EF Core is not suitable for massive database updates and in those cases I retrieve the entities using AsNoTracking. I would like to avoid the creation of proxies when that happens as it slows down the performance. In addition to that, if I have any access to any of the virtual properties (i.e. by some shared logic in those entities that is also used with lazy lading) I get an exception, even though in those cases I would be perfectly fine with them being empty. 

Is there any way of achieving this? If not, could it be considered as a new feature in the future? Just having an extension method similar to AsNoTracking like AsNoProxies or something like that would probably work.

Thanks in advance.

**Comment by ajcvickers** [comment] 2022-03-04 13:18
@MaQy There isn't currently a way to do this. It is possible to disable lazy-loading on the context by setting `context.ChangeTracker.LazyLoadingEnabled`, but I realize this is different from what you are asking for.

**Comment by AndriySvyryd** [comment] 2022-10-20 06:21
Duplicate of #12895

**Closed by AndriySvyryd** 2022-10-20 06:21 UTC
Labels: type-enhancement, customer-reported, area-query, area-proxies
