### ISSUE TITLE
Change detection ignores casing when applying an Index

### ISSUE THREAD

**Issue by minichma** [dotnet/efcore#32855] opened 2024-01-18 08:02 UTC
Change detection behaves differently for `string` columns on SQL Server depending on whether or not an Index is applied. In particular, if an Index is applied, change detection seems to ignore casing, while without an index casing is considered.

The behavior is unexpected, because from an application perspective, the question of whether a column is searchable and therefore requires an index is fully independent of whether or not the data itself is case sensitive. Consider a field storing an email address. Its reasonable to apply an index to allow searching. It might also be reasonable to apply case-insensitive collation to avoid unintended duplicates. However, ignoring casing during change detection might, e.g., prevent a user from fixing casing-typos.

The following docs don't seem to mention this behavior:
https://learn.microsoft.com/en-us/ef/core/change-tracking
https://learn.microsoft.com/en-us/ef/core/miscellaneous/collations-and-case-sensitivity

### Example Code

```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1" />
  </ItemGroup>
</Project>
```

```cs
using Microsoft.EntityFrameworkCore;

var options = new DbContextOptionsBuilder<Db>()
    .UseSqlServer("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=EfRepro")
    .Options;

Db db = new(options);
await db.Database.EnsureDeletedAsync();
await db.Database.EnsureCreatedAsync();

var originalEntity = db.Foos.Add(new Foo
{
    Bar = "abc"
}).Entity;

db.SaveChanges();

originalEntity.Bar = "ABC";
db.SaveChanges();

var readBackEntity = new Db(options).Foos.Single();

if (originalEntity.Bar == readBackEntity.Bar)
    // Wee see this if no index is applied.
    Console.WriteLine($"The result is '{readBackEntity.Bar}', which was expected.");
else
    // Wee see this if an index is applied.
    Console.WriteLine($"The result is '{readBackEntity.Bar}', but '{originalEntity.Bar}' was expected.");

public class Db : DbContext
{
    public Db(DbContextOptions<Db> options) : base(options) { }

    public DbSet<Foo> Foos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // By removing this line, change detection becomes case sensitive.
        modelBuilder.Entity<Foo>().HasIndex(x => x.Bar);

        base.OnModelCreating(modelBuilder);
    }
}

public class Foo
{
    public int ID { get; set; }
    public string Bar { get; set; }
}
```

### Expected behavior
By default, changes in casing should always be detected as such and propagated to the DB on `SaveChanges()`.

### Workaround
As a workaround, a case sensitive value comparer could be configured explicitly for all (or all affected) string-typed columns, but the side effects of doing so are not fully clear to me.

### Version information

EF Core version: 8.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.8.2

**Comment by ajcvickers** [comment] 2024-01-25 10:03
Duplicate of #32898

**Closed** 2024-01-25 18:03 UTC
Labels: closed-duplicate, customer-reported

**Comment by minichma** [comment] 2024-01-29 12:29
Thanks for fixing this. Linking the PR for documentation: https://github.com/dotnet/efcore/pull/32919
