### ISSUE TITLE
Migrations: keyless type without table/view created in ModelSnapshot

### ISSUE THREAD

**Issue by JonaBrackenwood** [dotnet/efcore#25183] opened 2021-07-01 15:53 UTC
I have e a keyless entity type that is used as the return type of a raw query. Entity and context are defined as followed:

```C#
    public class Context : DbContext
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<QueryResult>().HasNoKey().ToView(null).ToTable(null);
        }
    }

    public class QueryResult
    {
        public string Result { get; set; }
    }
```

Creating a first migration on this context works as expected and creates an empty migration file.
When creating a second migration, the following migration file is created:

```C#
    public partial class Test2 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "QueryResult");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "QueryResult",
                columns: table => new
                {
                    Result = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                });
        }
    }
```

When updating the database, this throws an error as the table doesn't and indeed shouldn't exist.
When inspecting the ContextModelSnapshot, QueryResult is present, which shouldn't be the case.

Using EF Core 5.0.7 on .NET 5.0.

**Comment by bricelam** [comment] 2021-07-02 19:03
Duplicate of #25133?

**Comment by JonaBrackenwood** [comment] 2021-07-02 19:28
> Duplicate of #25133?

Ah, indeed, didn't see that one. Thanks!

**Closed** 2022-10-16 19:38 UTC
Labels: closed-duplicate, customer-reported
