### ISSUE TITLE
JSON/Query: improve de-duplication logic for collection element access scenarios

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#29606] opened 2022-11-18 00:48 UTC
Part (or continuation) of https://github.com/dotnet/efcore/issues/28648 work.

Extracting out the de-duplication work which is going to be (mostly) complex work in shaper.
The idea is to detect cases where we already projected a given json entity and re-use it, rather than adding it to projection again. 
Examples:

```cs
One = x.MyJosnCollection,
Two = x.MyJsonCollection[2]
```

```cs
One = x.MyJosnReference
Two = x.MyJosnReference.MyNestedJsonCollection[prm]
```

We do that for references already, but it's much harder for collections because we need to keep track of ordinal keys (which never change when we de-duplicate references only). Also, collection elements are generated in the body of IncludeJsonEntityCollection, so we don't have access to individual entities at compile time. Probably will need to use the resulting collections and access their required elements. We need to pay attention to ordering of things, so that we don't access the element in JSON collection before that collection has been populated. We could maybe use similar strategy as include does - store those expressions in separate list, so that when we construct the final block expression, those collection accesses come after.

Until this is done, all queries projecting JSON which accesses element in a collection must be set to no-tracking, even if the owner entity is also projected.

**Comment by roji** [comment] 2022-11-18 11:33
@maumar is this deduplication something we do in non-JSON cases (e.g. for owned collections or collection includes)? 
For example:

```
One = x.MyNonJsonCollection
Two = x.MyNonJsonCollection.First()
```

**Comment by ajcvickers** [comment] 2022-11-19 10:54
Duplicate of #29513

**Closed by ajcvickers** 2022-11-19 10:54 UTC
Labels: needs-design, area-query, area-json
