### ISSUE TITLE
Recommend add IgnoreOnInsert and IgnoreOnUpdate attribute that limit insert or update.

### ISSUE THREAD

**Issue by RainingNight** [dotnet/efcore#6975] opened 2016-11-09 05:11 UTC
When update db by dtos with [IgnoreOnInsert] or [IgnoreOnUpdate], this is very useful!

**Comment by divega** [comment] 2016-11-09 11:27
@leshin could you provide a detailed example?

**Comment by rowanmiller** [comment] 2016-11-15 19:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 10:41 UTC
