### ISSUE TITLE
EF Core 2.0.1 to 2.1.3 - Lost in translation

### ISSUE THREAD

**Issue by DizzieDuke** [dotnet/efcore#13357] opened 2018-09-18 19:52 UTC
I recently upgraded from EF Core 2.0.1 to 2.1.3.

The LINQ query below was previously correctly translated to TSQL that was syntactically correct. This is no longer true. Removing the group by solves the problem in the short term.

```
x => _dataentitycolumnsRepository.Index().Where(y => y.ixDataColumn == x.ixDataColumn)
    .GroupBy(y => y.ixDataEntity)
    .Select(z => new { ixDataEntity = z.Key })
    .Join(_dataentitycolumnsRepository.selectDataEntity().Select(de => new { de.ixDataEntity, de.sDataEntity }).Where(de => de.sDataEntity == x.sDataColumn), dec => dec.ixDataEntity, de => de.ixDataEntity, (dec, de) => new { Dec = dec, De = de })
    .Any()
```
Is translated to:
```
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [md_vw_DataEntityColumns] AS [a]
        INNER JOIN (
            SELECT [de].[ixDataEntity], [de].[sDataEntity]
            FROM [md_vw_DataEntity] AS [de]
            WHERE [de].[sDataEntity] = @__x_sDataColumn_1
        ) AS [t] ON [a].[ixDataEntity] AS [Key] = [t].[ixDataEntity]
        WHERE [a].[ixDataColumn] = @__x_ixDataColumn_0
        GROUP BY [a].[ixDataEntity])
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END
```

**Comment by smitpatel** [comment] 2018-09-18 20:10
Duplicate of #12304

**Closed** 2022-10-16 13:31 UTC
Labels: customer-reported
