### ISSUE TITLE
EF Core 2.1 In-Memory Provider: Insert Entity with Collection Property (of same type) - Collection Items not Saved

### ISSUE THREAD

**Issue by miantosca** [dotnet/efcore#12217] opened 2018-06-03 14:07 UTC
I have a entity type Foo with a collection property Children of type ICollection<Foo>.
```C#
public class Foo
{
[Key]
Guid: Guid {get; set;}

[ForeignKey("ParentFooGuid")]
public virtual ICollection<Foo> Children{get; set;}

public Foo ParentFoo {get; set;}

public Guid? ParentFooGuid {get;set;}

}
```

I setup a 0-n Relationship in `OnModelCreating`

```C#          
modelBuilder.Entity<Foo>()
				.HasMany(i => i.Children)
				.WithOne(i => i.ParentFoo)
				.HasForeignKey(m => m.ParentFooGuid);
```
I construct an instance of Foo (MyFoo)  and add 1-n Foo's to the Children collection.

Before calling `dbSet.Add(MyFoo)` - I can see Children is populated correctly.

After calling `.Add(..)` - Children always only has one item in it - even if it had >1 before calling Add. The remaining child is always the last one added to Children.

After calling `.SaveChanges(..)` - if Children only had 1 item, the child is persisted and the parent is not.

If the Children had >1 items both MyFoo and the remaining Foo in Children (only 1 after calling `Add(...)` ) are persisted.

This works in 2.0 but not in 2.1

EF Core version: 2.1
Database Provider: In Memory
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.1

**Comment by ajcvickers** [comment] 2018-06-04 23:14
@miantosca I have not been able to reproduce this. Could you please either post a runnable project/solution or modify the test code below so that it demonstrates the behavior you are seeing?

```C#
public class Foo
{
    [Key]
    public Guid Guid {get; set; }

    [ForeignKey("ParentFooGuid")]
    public virtual ICollection<Foo> Children { get; set; }

    public Foo ParentFoo { get; set; }

    public Guid? ParentFooGuid { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseInMemoryDatabase("db");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Foo>()
            .HasMany(i => i.Children)
            .WithOne(i => i.ParentFoo)
            .HasForeignKey(m => m.ParentFooGuid);
    }
}

public class Program
{
    public static void Main()
    {
        Guid id;

        using (var context = new BloggingContext())
        {
            var foo = new Foo {Children = new List<Foo> {new Foo(), new Foo()}};

            context.Add(foo);
            context.SaveChanges();

            id = foo.Guid;

            Console.WriteLine(foo.Children.Count);
            Console.WriteLine(string.Join(", ", foo.Children.Select(e => e.Guid)));
        }

        using (var context = new BloggingContext())
        {
            var foo = context.Set<Foo>().Include(f => f.Children).Single(f => f.Guid == id);

            Console.WriteLine(foo.Children.Count);
            Console.WriteLine(string.Join(", ", foo.Children.Select(e => e.Guid)));
        }
    }
}
```

**Comment by miantosca** [comment] 2018-06-04 23:21
I will try and verify tonight – thanks for looking at it

**Comment by miantosca** [comment] 2018-06-05 15:53
I was not able to reproduce with your example - need to investigate further as to why it is not working the same

**Comment by ajcvickers** [comment] 2018-06-05 15:54
@miantosca I've seem similar things before when the collection contained duplicate instances, so you might want to check for that.

**Comment by ajcvickers** [comment] 2018-06-12 16:05
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:28 UTC
Labels: closed-could-not-reproduce, customer-reported
