### ISSUE TITLE
Deadlock in WPF when calling .Wait()

### ISSUE THREAD

**Issue by JakobFerdinand** [dotnet/efcore#12407] opened 2018-06-19 07:32 UTC
Ef Core causes a deadlock when using in a WPF Application and calling `.Wait()` on an async operation.

```csharp
var query = context.Authors.Include(a => a.Books);

var t = query.ToListAsync();
t.Wait();           // Deadlock
return t.Result;
```

I think it´s because of missing `.ConfigureAwait(false)` calls in all async operations in Ef Core.

Here´s a simple sample Project to reconstruct the Problem:
[Sample Project](https://github.com/JakobFerdinand/EfCoreDeadlockTest)

### Further technical details
EF Core version: 2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 18.03
IDE: Visual Studio 2017 15.7.4

**Comment by pmiddleton** [comment] 2018-06-19 13:16
Duplicate of #12270

**Comment by JakobFerdinand** [comment] 2018-07-12 07:16
To Fix this Problem for yourself we created a Fork and added `.ConfigureAwait(false)` to all `await` calls.

Here´s a Link to the Branch: [Configure False](https://github.com/rzlsoftware/EntityFrameworkCore/tree/feature/ConfigureAwait)

We also created a Code Analyzer to ensure not to forget any `ConfigureAwait(false)`.
You can find it [here](https://github.com/rzlsoftware/RZL.ConfigureAwaitAnalyzer) ;)

**Closed** 2022-10-16 12:32 UTC
Labels: customer-reported
