### ISSUE TITLE
EntityFrameworkCore 2.1.1 KeyNotFoundException The given key was not present in the dictionary

### ISSUE THREAD

**Issue by millertimebjm** [dotnet/efcore#12467] opened 2018-06-26 05:33 UTC
Error when using EntityFrameworkCore InMemory DbContext to look at a relationship between DbSet's,

```
Exception message:
System.Collections.Generic.KeyNotFoundException: 'The given key '__' was not present in the dictionary.'

Stack trace:
"   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.DefaultQueryExpressionVisitor.GetParameterValue[T](QueryContext queryContext, String parameterName)\r\n   at lambda_method(Closure , AnonymousObject )\r\n   at System.Linq.Lookup`2.CreateForJoin(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)\r\n   at System.Linq.Enumerable.JoinIterator[TOuter,TInner,TKey,TResult](IEnumerable`1 outer, IEnumerable`1 inner, Func`2 outerKeySelector, Func`2 innerKeySelector, Func`3 resultSelector, IEqualityComparer`1 comparer)+MoveNext()\r\n   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()\r\n   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollection[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relatedEntitiesFactory, Func`3 joinPredicate)\r\n   at lambda_method(Closure , QueryContext , Trick , Object[] )\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._Include[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Action`3 fixup)\r\n   at lambda_method(Closure , Trick )\r\n   at System.Linq.Enumerable.SelectIPartitionIterator`2.TryGetFirst(Boolean& found)\r\n   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)\r\n   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()\r\n   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)\r\n   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)\r\n   at System.Linq.Queryable.First[TSource](IQueryable`1 source)\r\n   at TestEfCore.GameTest.GameTestEfCoreError() in C:\\Users\\miller\\Documents\\Visual Studio 2017\\Projects\\TestEfCore\\GameTest.cs:line 63"
```

### Steps to reproduce
Create Class Library using Core 2.1.  Add EntityFrameworkCore SqlServer, InMemory, and Tools.  Use local Sql Server and restore database schema in which I have been able to reproduce the problem.  

Add xunit and xunit.runner.visualstudio to project.  Add Class to run xUnit test.  

```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using TestEfCore.EntityFrameworkCore.SqlServer.Models;
using Xunit;

namespace TestEfCore
{
    public class GameTest
    {
        [Fact]
        public void GameTestEfCoreError()
        {
            var optionsBuilder = new DbContextOptionsBuilder<CardContext>();
            optionsBuilder.UseInMemoryDatabase(Guid.NewGuid().ToString());

            using (var db = new CardContext(optionsBuilder.Options))
            {
                var suit = new Suit()
                {
                    Char = "a",
                    Id = 0,
                    Name = "asdf",
                };
                db.Suit.Add(suit);
                var value = new Value()
                {
                    Char = "b",
                    Name = "asdf2",
                    Points = 1,
                    Sequence = 0,
                };
                db.Value.Add(value);
                db.SaveChanges();

                var card = new Card()
                {
                    SuitId = suit.Id,
                    ValueId = value.Id,
                };
                db.Card.Add(card);
                db.SaveChanges();

                var game = new Game();
                db.Game.Add(game);
                var player = new Player();
                db.Player.Add(player);
                var gamePlayer = new GamePlayer()
                {
                    GameId = game.Id,
                    PlayerId = player.Id,
                };
                db.GamePlayer.Add(gamePlayer);
                var trick = new Trick()
                {
                    GameId = game.Id,
                    CreatedDate = DateTime.Now,
                };
                db.Trick.Add(trick);
                var trickCard = new TrickCard()
                {
                    PlayerId = player.Id,
                    TrickId = trick.Id,
                    CardId = db.Card.First().Id,
                    Sequence = 0,
                };
                db.TrickCard.Add(trickCard);
                db.SaveChanges();

                var trick2 = db.Trick.Include(_ => _.TrickCard).First();
            }
        }
    }
}
```

Sql Database code

```sql
USE [master]
GO
/****** Object:  Database [Card.Dev]    Script Date: 6/26/2018 12:23:04 AM ******/
CREATE DATABASE [Card.Dev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Card.Dev', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Card.Dev.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Card.Dev_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Card.Dev_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Card.Dev] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Card.Dev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Card.Dev] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Card.Dev] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Card.Dev] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Card.Dev] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Card.Dev] SET ARITHABORT OFF 
GO
ALTER DATABASE [Card.Dev] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Card.Dev] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Card.Dev] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Card.Dev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Card.Dev] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Card.Dev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Card.Dev] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Card.Dev] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Card.Dev] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Card.Dev] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Card.Dev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Card.Dev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Card.Dev] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Card.Dev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Card.Dev] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Card.Dev] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Card.Dev] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Card.Dev] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Card.Dev] SET  MULTI_USER 
GO
ALTER DATABASE [Card.Dev] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Card.Dev] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Card.Dev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Card.Dev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Card.Dev] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Card.Dev', N'ON'
GO
ALTER DATABASE [Card.Dev] SET QUERY_STORE = OFF
GO
USE [Card.Dev]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Card.Dev]
GO
/****** Object:  User [IIS APPPOOL\shmear]    Script Date: 6/26/2018 12:23:05 AM ******/
CREATE USER [IIS APPPOOL\shmear] FOR LOGIN [IIS APPPOOL\shmear] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_datareader] ADD MEMBER [IIS APPPOOL\shmear]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [IIS APPPOOL\shmear]
GO
/****** Object:  Table [dbo].[Board]    Script Date: 6/26/2018 12:23:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Board](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DealerPlayerId] [int] NULL,
	[TrumpSuitId] [int] NULL,
	[GameId] [int] NOT NULL,
	[Team1Wager] [int] NULL,
	[Team2Wager] [int] NULL,
	[DateTime] [datetime] NOT NULL,
 CONSTRAINT [PK__Board__3214EC073D786CAE] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Card]    Script Date: 6/26/2018 12:23:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Card](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SuitId] [int] NOT NULL,
	[ValueId] [int] NOT NULL,
 CONSTRAINT [PK__Card__3214EC070261639A] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Game]    Script Date: 6/26/2018 12:23:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Game](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Team1Points] [int] NOT NULL,
	[Team2Points] [int] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[StartedDate] [datetime] NULL,
 CONSTRAINT [PK__Game__3214EC07D19C5FE1] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GamePlayer]    Script Date: 6/26/2018 12:23:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GamePlayer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PlayerId] [int] NOT NULL,
	[GameId] [int] NOT NULL,
	[SeatNumber] [int] NOT NULL,
	[Wager] [int] NULL,
	[Ready] [bit] NOT NULL,
 CONSTRAINT [PK__GamePlay__3214EC07C6A01F52] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HandCard]    Script Date: 6/26/2018 12:23:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HandCard](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[GameId] [int] NOT NULL,
	[PlayerId] [int] NOT NULL,
	[CardId] [int] NOT NULL,
 CONSTRAINT [PK__HandCard__3214EC07F841351A] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Player]    Script Date: 6/26/2018 12:23:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Player](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[ConnectionId] [varchar](1000) NOT NULL,
	[KeepAlive] [datetime] NOT NULL,
 CONSTRAINT [PK__Player__3214EC0779BF3402] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Suit]    Script Date: 6/26/2018 12:23:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Suit](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](10) NOT NULL,
	[Char] [nvarchar](1) NOT NULL,
 CONSTRAINT [PK__Suit__3214EC0752F30A5F] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Trick]    Script Date: 6/26/2018 12:23:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Trick](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[GameId] [int] NOT NULL,
	[WinningPlayerId] [int] NULL,
	[Sequence] [int] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[CompletedDate] [datetime] NULL,
 CONSTRAINT [PK__Trick__3214EC076A315D17] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TrickCard]    Script Date: 6/26/2018 12:23:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TrickCard](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TrickId] [int] NOT NULL,
	[PlayerId] [int] NOT NULL,
	[CardId] [int] NOT NULL,
	[Sequence] [int] NOT NULL,
 CONSTRAINT [PK__TrickCar__3214EC07AA10B1EC] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Value]    Script Date: 6/26/2018 12:23:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Value](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](10) NOT NULL,
	[Char] [nvarchar](1) NOT NULL,
	[Points] [int] NOT NULL,
	[Sequence] [int] NOT NULL,
 CONSTRAINT [PK__Value__3214EC07D62ED94D] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Board] ADD  CONSTRAINT [DF_Board_DateTime]  DEFAULT (getdate()) FOR [DateTime]
GO
ALTER TABLE [dbo].[Board]  WITH CHECK ADD  CONSTRAINT [FK_Board_Game] FOREIGN KEY([GameId])
REFERENCES [dbo].[Game] ([Id])
GO
ALTER TABLE [dbo].[Board] CHECK CONSTRAINT [FK_Board_Game]
GO
ALTER TABLE [dbo].[Board]  WITH CHECK ADD  CONSTRAINT [FK_Board_Player] FOREIGN KEY([DealerPlayerId])
REFERENCES [dbo].[Player] ([Id])
GO
ALTER TABLE [dbo].[Board] CHECK CONSTRAINT [FK_Board_Player]
GO
ALTER TABLE [dbo].[Board]  WITH CHECK ADD  CONSTRAINT [FK_Board_Suit] FOREIGN KEY([TrumpSuitId])
REFERENCES [dbo].[Suit] ([Id])
GO
ALTER TABLE [dbo].[Board] CHECK CONSTRAINT [FK_Board_Suit]
GO
ALTER TABLE [dbo].[Card]  WITH CHECK ADD  CONSTRAINT [FK_Card_Suit] FOREIGN KEY([SuitId])
REFERENCES [dbo].[Suit] ([Id])
GO
ALTER TABLE [dbo].[Card] CHECK CONSTRAINT [FK_Card_Suit]
GO
ALTER TABLE [dbo].[Card]  WITH CHECK ADD  CONSTRAINT [FK_Card_Value] FOREIGN KEY([ValueId])
REFERENCES [dbo].[Value] ([Id])
GO
ALTER TABLE [dbo].[Card] CHECK CONSTRAINT [FK_Card_Value]
GO
ALTER TABLE [dbo].[GamePlayer]  WITH CHECK ADD  CONSTRAINT [FK_GamePlayer_Game] FOREIGN KEY([GameId])
REFERENCES [dbo].[Game] ([Id])
GO
ALTER TABLE [dbo].[GamePlayer] CHECK CONSTRAINT [FK_GamePlayer_Game]
GO
ALTER TABLE [dbo].[GamePlayer]  WITH CHECK ADD  CONSTRAINT [FK_GamePlayer_Player] FOREIGN KEY([PlayerId])
REFERENCES [dbo].[Player] ([Id])
GO
ALTER TABLE [dbo].[GamePlayer] CHECK CONSTRAINT [FK_GamePlayer_Player]
GO
ALTER TABLE [dbo].[HandCard]  WITH CHECK ADD  CONSTRAINT [FK_HandCard_Card] FOREIGN KEY([CardId])
REFERENCES [dbo].[Card] ([Id])
GO
ALTER TABLE [dbo].[HandCard] CHECK CONSTRAINT [FK_HandCard_Card]
GO
ALTER TABLE [dbo].[HandCard]  WITH CHECK ADD  CONSTRAINT [FK_HandCard_Game] FOREIGN KEY([GameId])
REFERENCES [dbo].[Game] ([Id])
GO
ALTER TABLE [dbo].[HandCard] CHECK CONSTRAINT [FK_HandCard_Game]
GO
ALTER TABLE [dbo].[HandCard]  WITH CHECK ADD  CONSTRAINT [FK_HandCard_Player] FOREIGN KEY([PlayerId])
REFERENCES [dbo].[Player] ([Id])
GO
ALTER TABLE [dbo].[HandCard] CHECK CONSTRAINT [FK_HandCard_Player]
GO
ALTER TABLE [dbo].[Trick]  WITH CHECK ADD  CONSTRAINT [FK_Trick_Game] FOREIGN KEY([GameId])
REFERENCES [dbo].[Game] ([Id])
GO
ALTER TABLE [dbo].[Trick] CHECK CONSTRAINT [FK_Trick_Game]
GO
ALTER TABLE [dbo].[Trick]  WITH CHECK ADD  CONSTRAINT [FK_Trick_Player] FOREIGN KEY([WinningPlayerId])
REFERENCES [dbo].[Player] ([Id])
GO
ALTER TABLE [dbo].[Trick] CHECK CONSTRAINT [FK_Trick_Player]
GO
ALTER TABLE [dbo].[TrickCard]  WITH CHECK ADD  CONSTRAINT [FK_TrickCard_Card] FOREIGN KEY([CardId])
REFERENCES [dbo].[Card] ([Id])
GO
ALTER TABLE [dbo].[TrickCard] CHECK CONSTRAINT [FK_TrickCard_Card]
GO
ALTER TABLE [dbo].[TrickCard]  WITH CHECK ADD  CONSTRAINT [FK_TrickCard_Player] FOREIGN KEY([PlayerId])
REFERENCES [dbo].[Player] ([Id])
GO
ALTER TABLE [dbo].[TrickCard] CHECK CONSTRAINT [FK_TrickCard_Player]
GO
ALTER TABLE [dbo].[TrickCard]  WITH CHECK ADD  CONSTRAINT [FK_TrickCard_Trick] FOREIGN KEY([TrickId])
REFERENCES [dbo].[Trick] ([Id])
GO
ALTER TABLE [dbo].[TrickCard] CHECK CONSTRAINT [FK_TrickCard_Trick]
GO
USE [master]
GO
ALTER DATABASE [Card.Dev] SET  READ_WRITE 
GO
```

Execute the Scaffold command.

```c#
Scaffold-DbContext "Server=localhost;Database=Card.Dev;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir EntityFrameworkCore\SqlServer\Models -context CardContext -f -v 
```

Execute xUnit test and the last line will get the error.

Project file after adding nuget packages

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="2.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.1" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
  </ItemGroup>

</Project>
```

### Further technical details
Visual Studio Community 15.7.2
Sql Server 2016

**Comment by ajcvickers** [comment] 2018-06-26 15:56
Duplicate of #11593

**Comment by millertimebjm** [comment] 2018-06-26 16:12
Interesting problem, thanks for finding this.  

For reference, here is the comment with the solution.  Don't use underscores "_" for lambda expressions.  
https://github.com/aspnet/EntityFrameworkCore/issues/11593#issuecomment-379901936

**Closed** 2022-10-16 13:15 UTC
Labels: customer-reported
