### ISSUE TITLE
Entity deletions without loading them into memory

### ISSUE THREAD

**Issue by olivierr91** [dotnet/efcore#12681] opened 2018-07-16 18:56 UTC
Please consider adding an overload to the Remove() method accepting a predicate so we can delete entities matching the predicate without loading them into memory.

For example:

`MyContext.PurchaseOrders.Remove(po => po.Status == Status.Canceled);`

Currently the only way to delete entities in EF is by loading entities into memory and calling .Remove() or .RemoveRange().

**Comment by AmmarBashir** [comment] 2018-07-16 19:03
Yes this is most awaiting feature since birth of Entity framework

**Comment by smitpatel** [comment] 2018-07-17 20:01
Duplicate of #795

**Closed** 2022-10-16 13:19 UTC
Labels: customer-reported
