### ISSUE TITLE
Failed when using SqlLinq.Max()

### ISSUE THREAD

**Issue by gusleo** [dotnet/efcore#10406] opened 2017-11-27 10:02 UTC
Describe what is not working as expected.

```
Exception message: Sequence contains no elements.
Stack trace:
```

### Steps to reproduce
First you can create table with no data, then run query.Max() or query.MaxAsync()
Before, on asp.net core 1 their no issue, but when migrate to asp.net core 2.0 show the error above

 var query = (from c in MediCoreContext.HospitalAppointment
                         where c.HospitalId == hospitalId && c.MedicalStaffId == medicalStaffId
                         select c.QueueNumber);
int  queueNumber = await query.MaxAsync();

**Comment by ajcvickers** [comment] 2017-11-27 18:38
Duplicate of #10086, which is itself closed as by-design.

**Closed** 2022-10-16 12:01 UTC
