### ISSUE TITLE
Getting "Value cannot be null.Parameter name: querySource" 

### ISSUE THREAD

**Issue by sampathdr** [dotnet/efcore#14020] opened 2018-11-27 12:54 UTC
Describe what is not working as expected.
Getting Value cannot be null.Parameter name: querySource
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Value cannot be null.
Parameter name: querySource

Stack trace:
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.FindEntityType(IQuerySource querySource)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.NullCheckRemovalTestingVisitor.<AnalyzeTestExpression>b__8_0(IProperty p, IQuerySource qs)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.<>c__DisplayClass95_0.<BindMethodCallExpression>b__0(IProperty property, IQuerySource querySource)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.<>c__DisplayClass92_0`1.<BindMethodCallExpression>b__0(IReadOnlyList`1 ps, IQuerySource qs)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindPropertyExpressionCore[TResult](Expression propertyExpression, IQuerySource querySource, Func`3 propertyBinder)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindMethodCallExpression(MethodCallExpression methodCallExpression, Action`2 methodCallBinder)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.NullCheckRemovalTestingVisitor.CanRemoveNullCheck(Expression testExpression, Expression resultExpression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitConditional(ConditionalExpression expression)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AutoMapperIssue.Program.Main(String[] args) in C:\Users\S\source\repos\AutoMapperIssue\AutoMapperIssue\Program.cs:line 43
```

### Steps to reproduce
project/solution to reproduce the issue.
https://github.com/sampathdr/AutoMapperNullIssue

Initially I got this exception when using with Automapper. 
```c#
var Users = context.Users.ProjectTo<UserViewModel>().ToList();
```
After that I have modified the code by removing automapper projection, so it is easy to isolate the issue.  
Following is the modified code. Wrote this code by analyzing Automapper Expression.
```c#
using (EfContext context2 = new EfContext())
      {
        var Users2 = context2.Users.Select(dtoUser =>
          new UserViewModel()
          {
            Region = ((dtoUser == null
                        || dtoUser.RegAddress == null
                        || dtoUser.RegAddress.Country == null
                        || dtoUser.RegAddress.Country.Region == null) ? null
                        : dtoUser.RegAddress.Country.Region) == null ? null :
            new RegionViewModel()
            {
              Id = ((dtoUser == null 
                      || dtoUser.RegAddress == null 
                      || dtoUser.RegAddress.Country == null 
                      || dtoUser.RegAddress.Country.Region == null) ? null : 
                      dtoUser.RegAddress.Country.Region).Id
            }
          }
          ).ToList();
      }
```

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.0

**Comment by smitpatel** [comment] 2018-11-27 19:46
Related to #12148

**Comment by sampathdr** [comment] 2018-11-28 08:37
@smitpatel  Any workaround or any suggestion to make this work?

**Comment by smitpatel** [comment] 2019-06-06 00:32
Duplicate of #12148

**Closed** 2022-10-16 13:41 UTC
Labels: closed-duplicate, customer-reported
