### ISSUE TITLE
Possible Race Condition in ChangeTracking.Internal.StateManager in 2.2

### ISSUE THREAD

**Issue by rfuhrer** [dotnet/efcore#14419] opened 2019-01-15 00:38 UTC
I'm trying to create a new object in the database and it's failing 80+% of the time, but occasionally it does work.  There's lots of places in my application that do similar operations, yet this one seems to be erroring out since upgrading to 2.2.  Looks like I'm not the only one with the issue: (https://stackoverflow.com/questions/54135675/after-upgrade-to-net-core-2-2-inserts-via-ef-were-failing-with-error).  This is happening to me on my dev machine and also when deployed to Azure.

It looks to me like the DB operations is succeeding but then it blows up while trying to update the entity's ID with the new DB created ID.  Reverting back to 2.1 solves the issue

Stack Trace with DB Log:
```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]

      Executed DbCommand (3ms) [Parameters=[@p0='True', @p1='0', @p2='0', @p3='0', @p4='40', @p5='' (Size = 4000), @p6='' (DbType = DateTime2), @p7='MPT-3092' (Size = 4000), @p8='0', @p9='0'], CommandType='Text', CommandTimeout='60']

      SET NOCOUNT ON;

      INSERT INTO [tMWDComponent] ([Active], [CirculatingHoursImport], [CirculatingHoursLifetimeImport], [MWDKitId], [MwdComponentTypeId], [Comments], [ResetDate], [SerialNumber], [TotalHoursImport], [TotalHoursLifetimeImport])

      VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9);

      SELECT [Id]

      FROM [tMWDComponent]

      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (3ms) [Parameters=[@p0='True', @p1='0', @p2='0', @p3='0', @p4='40', @p5='' (Size = 4000), @p6='' (DbType = DateTime2), @p7='MPT-3092' (Size = 4000), @p8='0', @p9='0'], CommandType='Text', CommandTimeout='60']

SET NOCOUNT ON;

INSERT INTO [tMWDComponent] ([Active], [CirculatingHoursImport], [CirculatingHoursLifetimeImport], [MWDKitId], [MwdComponentTypeId], [Comments], [ResetDate], [SerialNumber], [TotalHoursImport], [TotalHoursLifetimeImport])

VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9);

SELECT [Id]

FROM [tMWDComponent]

WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.*key*.RemoteDependency","time":"2019-01-15T00:12:17.3884897Z","iKey":"*key*","tags":{"ai.application.ver":"1.0.0.0","ai.cloud.roleInstance":"PS173","ai.user.id":"i/4Mc","ai.operation.id":"11391666a062554da2a484b0014ce1f4","ai.operation.parentId":"11391666a062554da2a484b0014ce1f4","ai.operation.name":"POST MwdComponent/CreateComponent","ai.location.ip":"127.0.0.1","ai.internal.sdkVersion":"rdddsc:2.8.1-19196","ai.internal.nodeName":"PS173"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"PS173 | prime_dev","id":"e3fc95623b884858873dacca3a2667b9","data":"SET NOCOUNT ON;\r\nINSERT INTO [tMWDComponent] ([Active], [CirculatingHoursImport], [CirculatingHoursLifetimeImport], [MWDKitId], [MwdComponentTypeId], [Comments], [ResetDate], [SerialNumber], [TotalHoursImport], [TotalHoursLifetimeImport])\r\nVALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9);\r\nSELECT [Id]\r\nFROM [tMWDComponent]\r\nWHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();","duration":"00:00:00.0033715","success":true,"type":"SQL","target":"PS173 | prime_dev","properties":{"_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')","AspNetCoreEnvironment":"Development","DeveloperMode":"true"}}}}

fail: Microsoft.EntityFrameworkCore.Update[10000]

      An exception occurred in the database while saving changes for context type 'Prime.Core.Data.ApplicationDbContext'.

      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.ArgumentNullException: Value cannot be null.

      Parameter name: key

         at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)

         at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)

         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.FindIdentityMap(IKey key)

         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetDependents(InternalEntityEntry principalEntry, IForeignKey foreignKey)

         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 containingPrincipalKeys, IReadOnlyList`1 containingForeignKeys, Object oldValue, Object newValue)

         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 keys, IReadOnlyList`1 foreignKeys, Object oldValue, Object newValue)

         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectKeyChange(InternalEntityEntry entry, IProperty property)

         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.PropertyChanged(InternalEntityEntry entry, IPropertyBase propertyBase, Boolean setModified)

         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.PropertyChanged(InternalEntityEntry entry, IPropertyBase property, Boolean setModified)

         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean setModified)

         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetCurrentValue(IPropertyBase propertyBase, Object value)

         at Microsoft.EntityFrameworkCore.Update.ColumnModification.set_Value(Object value)

         at Microsoft.EntityFrameworkCore.Update.ModificationCommand.PropagateResults(ValueBuffer valueBuffer)

         at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagationAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)

         at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)

         --- End of inner exception stack trace ---

         at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)

         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)

         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)

         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)

         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)

         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)

         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.ArgumentNullException: Value cannot be null.

Parameter name: key

   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)

   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.FindIdentityMap(IKey key)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetDependents(InternalEntityEntry principalEntry, IForeignKey foreignKey)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 containingPrincipalKeys, IReadOnlyList`1 containingForeignKeys, Object oldValue, Object newValue)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 keys, IReadOnlyList`1 foreignKeys, Object oldValue, Object newValue)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectKeyChange(InternalEntityEntry entry, IProperty property)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.PropertyChanged(InternalEntityEntry entry, IPropertyBase propertyBase, Boolean setModified)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.PropertyChanged(InternalEntityEntry entry, IPropertyBase property, Boolean setModified)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean setModified)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetCurrentValue(IPropertyBase propertyBase, Object value)

   at Microsoft.EntityFrameworkCore.Update.ColumnModification.set_Value(Object value)

   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.PropagateResults(ValueBuffer valueBuffer)

   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagationAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

Microsoft.EntityFrameworkCore.Update:Error: An exception occurred in the database while saving changes for context type 'Prime.Core.Data.ApplicationDbContext'.

Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.ArgumentNullException: Value cannot be null.

Parameter name: key

   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)

   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.FindIdentityMap(IKey key)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetDependents(InternalEntityEntry principalEntry, IForeignKey foreignKey)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 containingPrincipalKeys, IReadOnlyList`1 containingForeignKeys, Object oldValue, Object newValue)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 keys, IReadOnlyList`1 foreignKeys, Object oldValue, Object newValue)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectKeyChange(InternalEntityEntry entry, IProperty property)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.PropertyChanged(InternalEntityEntry entry, IPropertyBase propertyBase, Boolean setModified)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.PropertyChanged(InternalEntityEntry entry, IPropertyBase property, Boolean setModified)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean setModified)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetCurrentValue(IPropertyBase propertyBase, Object value)

   at Microsoft.EntityFrameworkCore.Update.ColumnModification.set_Value(Object value)

   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.PropagateResults(ValueBuffer valueBuffer)

   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagationAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)



Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.ArgumentNullException: Value cannot be null.

Parameter name: key

   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)

   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.FindIdentityMap(IKey key)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetDependents(InternalEntityEntry principalEntry, IForeignKey foreignKey)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 containingPrincipalKeys, IReadOnlyList`1 containingForeignKeys, Object oldValue, Object newValue)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 keys, IReadOnlyList`1 foreignKeys, Object oldValue, Object newValue)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectKeyChange(InternalEntityEntry entry, IProperty property)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.PropertyChanged(InternalEntityEntry entry, IPropertyBase propertyBase, Boolean setModified)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.PropertyChanged(InternalEntityEntry entry, IPropertyBase property, Boolean setModified)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean setModified)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetCurrentValue(IPropertyBase propertyBase, Object value)

   at Microsoft.EntityFrameworkCore.Update.ColumnModification.set_Value(Object value)

   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.PropagateResults(ValueBuffer valueBuffer)

   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagationAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

Exception thrown: 'Microsoft.EntityFrameworkCore.DbUpdateException' in System.Private.CoreLib.dll

```

### Steps to reproduce
I tried removing anything complicated about this insert and still get the error.  Here's the code I'm running with the commented out lines being the things I thought might have been causing it, but did not solve the issue when removed:
```c#
var component = new MWDComponent
            {
                Active = true,
                OldComments = "",
                MwdComponentTypeId = createParams.TypeId,
                SerialNumber = createParams.Serial.Trim(),
                ResetDate = DateTime.UtcNow,
                // Statuses = new List<MWDComponentStatusHistory>(),
            };
            // component.Statuses.Add(new MWDComponentStatusHistory
            // {
            //     // MWDComponent = component,
            //     MWDComponentStatusId = MWDComponentStatus.InShopId,
            //     AddressId = createParams.ShopId,
            //     UserId = userInfo.UserId,
            //     When = DateTime.UtcNow,
            // });
            _context.MwdComponents.Add(component);
            await _context.SaveChangesAsync();
```

Other Relevant code:
```c#
[Table("tMWDComponent")]
    public class MWDComponent
    {
        [Column("Id")]
        public int Id { get; set; }
        public int MWDKitId { get; set; }
        public virtual MwdKit MwdKit { get; set; }
        public int MwdComponentTypeId { get; set; }
        public MwdComponentType MwdComponentType { get; set; }
        public string SerialNumber { get; set; }
        [Column("Comments")]
        public string OldComments { get; set; }
        public decimal CirculatingHoursImport { get; set; }
        public decimal TotalHoursImport { get; set; }
        public decimal CirculatingHoursLifetimeImport { get; set; }
        public decimal TotalHoursLifetimeImport { get; set; }
        public DateTime? ResetDate { get; set; }
        public bool Active { get; set; }
        public ICollection<RunComponent> RunComponents { get; set; }
        public ICollection<MWDComponentReset> Resets { get; set; }
        public ICollection<MWDComponentFlagged> Flags { get; set; }
        public ICollection<MWDComponentStatusHistory> Statuses { get; set; }
        public ICollection<MWDComponentComment> Comments { get; set; }
        public ICollection<MWDSubcomponent> Subcomponents { get; set; }
    }
```
There's no fluent API entries for this table

### Further technical details
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.3.31.10" />
    <PackageReference Include="Elmah.Io.AspNetCore" Version="3.6.63" />
    <PackageReference Include="EPPlus.Core" Version="1.5.4" />
    <PackageReference Include="IdentityModel" Version="3.10.5" />
    <PackageReference Include="MailKit" Version="2.1.2" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.5.1" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.1">
      <NoWarn>NU1608</NoWarn>
    </PackageReference>
  </ItemGroup>

</Project>
```
Operating system: Windows 10, also happens on a site deployed to azure
IDE: VSCode

**Comment by ajcvickers** [comment] 2019-01-15 00:44
@rfuhrer How is the DbContext lifetime managed. (DbContext is not thread safe; the same instance cannot be used safely from concurrent threads.)

**Comment by rfuhrer** [comment] 2019-01-15 00:51
@ajcvickers It's being inserted into my controller and my understanding was that a new instance is created with every request. The issue also happens on my dev machine when I'm the only person on the site and only sending a single request so I'm pretty sure that isn't the issue.

```c#
//Controller
public BaseController(ApplicationDbContext context)
        {
            _context = context;
        }
//Startup.cs
services.AddDbContextPool<ApplicationDbContext>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"), settings => settings.EnableRetryOnFailure().CommandTimeout(60));
                options.EnableSensitiveDataLogging();
            });
```

**Comment by rfuhrer** [comment] 2019-01-15 00:57
@ajcvickers Turns out you were on to something though! I just fixed the issue by changing `services.AddDbContextPool<ApplicationDbContext>` to `services.AddDbContext<ApplicationDbContext>`

Seems like there's a bug when using the connection pool version of EF.  Feel free to rename this issue or let me know if there's another team that needs to know about this (if it's not EF but ASP.net or something)

**Comment by ajcvickers** [comment] 2019-01-15 00:58
@rfuhrer Thanks--we will investigate.

**Comment by smitpatel** [comment] 2019-01-15 16:32
Stack trade is quite similar to #14226

**Comment by ajcvickers** [comment] 2020-09-05 19:43
I'm not able to reproduce this in current bits. Evidence above is that this is related to pooling, which has been redesigned in 5.0. Closing as no-repro, but we can open again if we get a runnable repro on 5.0.

**Closed** 2022-10-16 13:47 UTC
Labels: closed-could-not-reproduce, customer-reported
