### ISSUE TITLE
Exception when calling AddDbContextPool more than once

### ISSUE THREAD

**Issue by yogster** [dotnet/efcore#9574] opened 2017-08-25 14:02 UTC
My Web API connects to two DbContexts (let's call them `DbA` and `DbB`). I have updated the code to make use of the new `AddDbContextPool` method available in EF 2.0. When I run the Web API and an instance of `DbB` is retrieved through Dependency Injection, I get the following exception:

```
Exception message:

System.ArgumentException: 'Expression of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[DbB]' cannot be used for constructor parameter of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[DbA]''

Stack trace:

   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Dynamic.Utils.ExpressionUtils.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments, String methodParamName)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, Expression[] arguments)
   at Microsoft.EntityFrameworkCore.Internal.DbContextPool`1.CreateActivator(DbContextOptions options)
   at Microsoft.EntityFrameworkCore.Internal.DbContextPool`1..ctor(DbContextOptions options)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__2`1.<AddDbContextPool>b__2_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at WebAPI.Startup.<Configure>d__3.MoveNext() in C:\Users\xxx\Source\Repos\WebAPI\src\WebAPI\Startup.cs:line 159

```

### Steps to reproduce
```c#
//In ConfigureServices()
services
    .AddEntityFrameworkSqlServer()
    .AddDbContextPool<DbA>(options => /*options here*/)
    .AddDbContextPool<DbB>(options => /*options here*/);

//In Configure()
var context = app.ApplicationServices.GetRequiredService<WebApiDbContext>();
```

The exception is thrown independently of the order in which `AddDbContextPool` is called. Interestingly, calling `AddDbContext` instead of the second call to `AddDbContextPool` throws the same exception, but **calling `AddDbContext` instead of the first call does not throw an exception**.

I have tried using `DbContextOptions<T>` explicitly in the DbContext constructors as described [here](https://github.com/aspnet/Identity/issues/962), but it still throws an exception.

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 (15.3.2)

**Comment by ajcvickers** [comment] 2017-08-25 20:27
Duplicate of #9433

**Comment by ajcvickers** [comment] 2017-09-12 18:22
Hi @jbergasa. We are gathering information on the use of EF Core pre-release builds. You reported this issue shortly after the release of 2.0.0 RTM. It would be really helpful if you could let us know:

- Did you consider testing your code against the pre-release builds?
- Was there anything blocking you from using pre-release builds?
- What do you think could make it easier for you to use pre-release builds in the future?

Thanks in advance for any feedback. Hopefully this will help us to increase the value of pre-release builds going forward.

**Closed** 2022-10-16 11:18 UTC
Labels: closed-duplicate
