### ISSUE TITLE
SqlLite does not support ToJson()?  

### ISSUE THREAD

**Issue by MacMcDell** [dotnet/efcore#31094] opened 2023-06-16 13:53 UTC
using ```<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.7" /> <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.5">```

usage - Class Library Unit Testing

This issue tracker is for - 
I am attempting to run SQLLite In Memory db for my unit testing and following the following supported documentation here: https://github.com/dotnet/EntityFramework.Docs/blob/main/samples/core/Testing/TestingWithoutTheDatabase/SqliteInMemoryBloggingControllerTest.cs

Unfortunately every time it attempts to add objects of any complexity, I am getting a crash at this point with the following message: 
In RelationalModel.cs (line 469) I am getting a NRE on the following column within one of my DBSets.  

I can only assume this has something to do with my OnModelCreating setup code: 
```C#
 modelBuilder.Entity<MyDbMap>(entity =>
        {
            entity.ToTable("MyDbMaps");
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.HasKey(e => new { e.CustomerId, e.MyDbPartnerId });
            entity.HasOne(d => d.MyDbPartner).WithMany(p => p.MyDbMaps)
                .HasForeignKey(d => d.MyDbPartnerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MyDbMaps_MyDbPartner");
                // THIS SECTION I ASSUME IS BAD? 
            entity.OwnsOne(x => x.Mappings, b =>
            {
                b.ToJson();
                b.OwnsMany<MatchSuccess>(x => x.MatchSuccess,
                    successbuilder =>
                    {
                        successbuilder.Property(x => x.Meta)
                            .HasConversion(
                                v => JsonSerializer.Serialize(v, new JsonSerializerOptions()),
                                v => JsonSerializer.Deserialize<Dictionary<string, string>>(v,
                                    new JsonSerializerOptions() { }));
                        successbuilder.ToJson();
                    });
                b.OwnsMany<MatchFailure>(x => x.MatchFailures,
                    failureBuilder => failureBuilder.ToJson<MappingResponse, MatchFailure>());
            });
        });
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.CreateTableMapping(IRelationalTypeMappingSource relationalTypeMappingSource, IEntityType entityType, IEntityType mappedType, StoreObjectIdentifier mappedTable, RelationalModel databaseModel, List`1 tableMappings, Boolean includesDerivedTypes, Nullable`1 isSplitEntityTypePrincipal)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.AddTables(RelationalModel databaseModel, IEntityType entityType, IRelationalTypeMappingSource relationalTypeMappingSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.Create(IModel model, IRelationalAnnotationProvider relationalAnnotationProvider, IRelationalTypeMappingSource relationalTypeMappingSource, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.Add(IModel model, IRelationalAnnotationProvider relationalAnnotationProvider, IRelationalTypeMappingSource relationalTypeMappingSource, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelRuntimeInitializer.InitializeModel(IModel model, Boolean designTime, Boolean prevalidation)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   ```

## Implementation ##  - following almost verbatim of the provided sqlLite example
``` C#
public class SqliteInMemoryBloggingControllerTest : IDisposable
{
    private readonly DbConnection _connection;
    private readonly DbContextOptions<MyDbDbContext> _contextOptions;

    #region ConstructorAndDispose

    public SqliteInMemoryBloggingControllerTest()
    {
        // Create and open a connection. This creates the SQLite in-memory database, which will persist until the connection is closed
        // at the end of the test (see Dispose below).
        _connection = new SqliteConnection("Filename=:memory:");
        _connection.Open();

        // These options will be used by the context instances in this test suite, including the connection opened above.
        _contextOptions = new DbContextOptionsBuilder<MyDbDbContext>()
            .UseSqlite(_connection)
            .Options;

        // Create the schema and seed some data
        using var context = new MyDbDbContext(_contextOptions);

        
        context.MyDbPartners.AddRange(FakeRepository.MyDbPartners());
        context.MyDbMaps.AddRange(FakeRepository.MyDbMaps());
        context.MyDbPolicies.AddRange(FakeRepository.MyDbPolicies());
        context.MyDbPolicySpaces.Add(new MyDbPolicySpaces()
        {
            MyDbPartnerId = (int)Partner.Foo,
            MyDbPolicyId = 1,
            Spaces = new Dictionary<string, string>()
            {
                { "236129", "12341" },
                { "50159", "12340" },
                { "269506", "1234" }

            },

        });
        
        
        context.SaveChanges();
    }

    MyDbDbContext CreateContext() => new MyDbDbContext(_contextOptions);

    public void Dispose() => _connection.Dispose();


    [TestMethod]
    public void GetBlog()
    {
        using MyDbDbContext context = CreateContext();

        var result = context.MyDbMaps.ToList(); 
        Assert.IsTrue(result.Count > 0);

    }
```

![image](https://github.com/dotnet/EntityFramework.Docs/assets/1512821/876909a3-7cb1-4e28-9e07-a51fb9d0bb76)

**Comment by MacMcDell** [comment] 2023-06-16 14:07
This problem seems to erupt from the jsonColumnTypeMapping. 
![image](https://github.com/dotnet/efcore/assets/1512821/8ddaaaac-3e5d-4e0e-a2f1-ca1580c88f13)

it goes into this FindMappingWithConversion.. of clrType = System.Text.Json.. but the principals is null.. so it hits a lower down overload where it FindMappingWithConversion(mappingInfo, null, null) 
![image](https://github.com/dotnet/efcore/assets/1512821/3d5fbbc1-59d8-4156-b636-7f25341e815d)

finally resolvedMapping is null.. ..so everything donwnstream is null.

**Comment by roji** [comment] 2023-06-16 14:27
JSON columns support isn't available for SQLite in EF Core 7 - this has been implemented for the upcoming 8.0 ([docs](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#json-columns-for-sqlite)). You can try the latest 8.0 preview to see the feature at work.

**Comment by maumar** [comment] 2023-06-17 01:16
dupe of https://github.com/dotnet/efcore/issues/28816

**Comment by MacMcDell** [comment] 2023-06-17 15:17
Thanks for this update. I will check it out.

**Closed** 2023-06-18 10:03 UTC
Labels: closed-duplicate, customer-reported, area-adonet-sqlite
