### ISSUE TITLE
Cannot update the 1-m property out of DbContext

### ISSUE THREAD

**Issue by heku** [dotnet/efcore#10174] opened 2017-10-27 15:28 UTC
I found an issue that EF Core cannot update an entity with a 1-m property if we update it out of DbContext, for example, I have two models `Group` and `GroupItem`, the `Group` has a set of `GroupItems` and every `GroupItem` belongs to one `Group`. In this case, if we updated a `Group`'s `GroupItems` out of DbContext, then DbContext cannot save the changes. 

`Attempted to update or delete an entity that does not exist in the store.`

I think the exception means my `GroupItem` use a compiste key and which is changed so that EF Core cannot find any entity in the database, however, EF Core should support this situation as the code has a exact purpose, It's obvious in below code that I want to update the Group(G-001)'s Items to `value-1` and `value-4`.

```c#
// EFCoreTest.csproj

//<Project Sdk = "Microsoft.NET.Sdk" >
//  <PropertyGroup>
//    <TargetFramework>netcoreapp2.0</TargetFramework>
//    <IsPackable>false</IsPackable>
//  </PropertyGroup>
//  <ItemGroup>
//    <PackageReference Include = "Microsoft.EntityFrameworkCore" Version="2.0.0" />
//    <PackageReference Include = "Microsoft.EntityFrameworkCore.InMemory" Version="2.0.0" />
//    <PackageReference Include = "Microsoft.EntityFrameworkCore.Sqlite" Version="2.0.0" />
//    <PackageReference Include = "Microsoft.Extensions.Logging.Debug" Version="2.0.0" />
//    <PackageReference Include = "Microsoft.NET.Test.Sdk" Version="15.3.0" />
//    <PackageReference Include = "xunit" Version="2.3.0" />
//    <PackageReference Include = "xunit.runner.visualstudio" Version="2.3.0" />
//  </ItemGroup>
//</Project>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace EFCoreTest
{
    internal class Group
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public List<GroupItem> Items { get; set; }
    }
    internal class GroupItem
    {
        public string GroupId { get; set; }
        public string ItemValue { get; set; }
    }

    internal class EfContext : DbContext
    {
        public EfContext(DbContextOptions options) : base(options) { }

        public DbSet<Group> Groups { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<GroupItem>().HasKey(x => new { x.GroupId, x.ItemValue });

            modelBuilder.Entity<Group>().HasKey(x => x.Id);
            modelBuilder.Entity<Group>().HasMany(x => x.Items).WithOne().HasForeignKey(t => t.GroupId).IsRequired();
        }
    }

    internal static class MockContext
    {
        private static readonly ILoggerFactory DebugLogFactory = new LoggerFactory().AddDebug();

        public static EfContext UseInMemory(string databaseName = null)
        {
            var options = new DbContextOptionsBuilder<EfContext>()
                .UseInMemoryDatabase(databaseName ?? Guid.NewGuid().ToString())
                .UseLoggerFactory(DebugLogFactory)
                .Options;

            return new EfContext(options);
        }
    }

    public class UnitTest
    {
        [Fact]
        public async Task UpdateOutOfContextTest()
        {
            var group = new Group
            {
                Id = "G-001",
                Name = "group name",
                Items = new List<GroupItem> {
                    new GroupItem{ GroupId="G-001", ItemValue="value-1"},
                    new GroupItem{ GroupId="G-001", ItemValue="value-2"},
                    new GroupItem{ GroupId="G-001", ItemValue="value-3"}
                }
            };
            using (var ctx = MockContext.UseInMemory("UpdateTest"))
            {
                ctx.Groups.Add(group);
                await ctx.SaveChangesAsync();
            }

            // Update out of DbContext scope
            group.Name = "group name updated";
            group.Items = new List<GroupItem> {
                new GroupItem{ GroupId="G-001", ItemValue="value-1"},
                new GroupItem{ GroupId="G-001", ItemValue="value-4"}
            };
            using (var ctx = MockContext.UseInMemory("UpdateTest"))
            {
                ctx.Groups.Update(group);
                await ctx.SaveChangesAsync();  // Throw the exception below

                var g = await ctx.Groups.Include(x => x.Items).SingleAsync(x => x.Id == "G-001");
                Assert.Equal("group name updated", g.Name);
                Assert.Equal(new[] { "value-1", "value-4" }, g.Items.Select(x => x.ItemValue).ToArray());
            }
        }
    }
}
```

```
Message: Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException : 
Attempted to update or delete an entity that does not exist in the store.

Test Name:	EFCoreTest.UnitTest.UpdateOutOfContextTest
Test FullName:	EFCoreTest.UnitTest.UpdateOutOfContextTest
Test Source:	C:\Codes\Learn2017\EFCoreTest\UnitTest.cs : line 77
Test Outcome:	Failed
Test Duration:	0:00:00.156

Result StackTrace:	
at Microsoft.EntityFrameworkCore.Storage.Internal.InMemoryTable`1.Update(IUpdateEntry entry)
   at Microsoft.EntityFrameworkCore.Storage.Internal.InMemoryStore.ExecuteTransaction(IEnumerable`1 entries, IDiagnosticsLogger`1 updateLogger)
   at Microsoft.EntityFrameworkCore.Storage.Internal.InMemoryDatabase.SaveChangesAsync(IReadOnlyList`1 entries, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EFCoreTest.UnitTest.<UpdateOutOfContextTest>d__0.MoveNext() in C:\Codes\Learn2017\EFCoreTest\UnitTest.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException : Attempted to update or delete an entity that does not exist in the store.
```

### Further technical details

EF Core version:  2.0
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10 Pro N 1709
IDE: Visual Studio Community 2017 Version 15.4.1

**Comment by heku** [comment] 2017-10-29 03:39
Even if I add a primary key `Id` to `GroupItem`, EF Core still cannot detect the purpose correctly.

```c#
    internal class Group
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public List<GroupItem> Items { get; set; }
    }
    internal class GroupItem
    {
        public string Id { get; set; }
        public string GroupId { get; set; }
        public string ItemValue { get; set; }
    }

    internal class EfContext : DbContext
    {
        public EfContext(DbContextOptions options) : base(options) { }

        public DbSet<Group> Groups { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<GroupItem>().HasKey(x => x.Id);

            modelBuilder.Entity<Group>().HasKey(x => x.Id);
            modelBuilder.Entity<Group>().HasMany(x => x.Items).WithOne().HasForeignKey(t => t.GroupId).IsRequired();
        }
    }

    internal static class MockContext
    {
        private static readonly ILoggerFactory DebugLogFactory = new LoggerFactory().AddDebug();

        public static EfContext UseInMemory(string databaseName = null)
        {
            var options = new DbContextOptionsBuilder<EfContext>()
                .UseInMemoryDatabase(databaseName ?? Guid.NewGuid().ToString())
                .UseLoggerFactory(DebugLogFactory)
                .Options;

            return new EfContext(options);
        }
    }

    public class UnitTest
    {
        [Fact]
        public async Task UpdateOutOfContextTest()
        {
            var group = new Group
            {
                Id = "G-001",
                Name = "group name",
                Items = new List<GroupItem> {
                    new GroupItem{ Id="item-1", GroupId="G-001", ItemValue="value-1"},
                    new GroupItem{ Id="item-2", GroupId="G-001", ItemValue="value-2"},
                    new GroupItem{ Id="item-3", GroupId="G-001", ItemValue="value-3"}
                }
            };
            using (var ctx = MockContext.UseInMemory("UpdateTest"))
            {
                ctx.Groups.Add(group);
                await ctx.SaveChangesAsync();
            }

            // Update out of DbContext scope
            group.Name = "group name updated";
            group.Items = new List<GroupItem> {
                new GroupItem{ Id="item-1", GroupId="G-001", ItemValue="value-1"},
                new GroupItem{ Id="item-2", GroupId="G-001", ItemValue="value-4"}
            };
            using (var ctx = MockContext.UseInMemory("UpdateTest"))
            {
                ctx.Groups.Update(group);
                await ctx.SaveChangesAsync();

                var g = await ctx.Groups.Include(x => x.Items).SingleAsync(x => x.Id == "G-001");
                Assert.Equal("group name updated", g.Name);
                Assert.Equal(new[] { "value-1", "value-4" }, g.Items.Select(x => x.ItemValue).ToArray());//Failed
            }
        }
    }
```

```
Test Name:	EFCoreTest.UnitTest.UpdateOutOfContextTest
Test FullName:	EFCoreTest.UnitTest.UpdateOutOfContextTest
Test Source:	C:\Codes\Learn2017\EFCoreTest\UnitTest.cs : line 205
Test Outcome:	Failed
Test Duration:	0:00:00.238

Result StackTrace:	
at EFCoreTest.UnitTest.<UpdateOutOfContextTest>d__0.MoveNext() in C:\Codes\Learn2017\EFCoreTest\UnitTest.cs:line 235
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	
Assert.Equal() Failure
Expected: String[] ["value-1", "value-4"]
Actual:   String[] ["value-1", "value-4", "value-3"]
```

`value-3` isn't deleted, which should be deleted.

**Comment by hekufriend** [comment] 2017-10-29 15:07
You suck, guy ~~ the issue isn't caused by what you said, of course you could update out of DbContext scope, the root cause is you are trying to update the value doesn't exist!!!!!

First, please update as below. Sure you would also get the same issue after this update. 
var group = new Group
{
    Id = "G-001",
    Name = "group name",
    Items = new List<GroupItem> {
    new GroupItem{ GroupId="G-001", ItemValue="value-1"}
}

group.Items = new List<GroupItem> {
new GroupItem{ GroupId="G-001", ItemValue="value-2"}
};

Second, set the correct primary key. Here is the root cause, you use ID and Value as the primary key, while updating, if there is no ID and Value, the exception appears. 
modelBuilder.Entity<GroupItem>().HasKey(x => new { x.GroupId });

**Comment by Tarig0** [comment] 2017-10-30 00:26
Looks like the issue here is you want to delete/add items to the many part of the relationship. Attaching the parent entity as updated will also flag ALL children as updated. So when ef generates the sql it will be an update statement every time.

You will have to tell ef remove item2 and item3 and add item4 to get the desired result.

**Comment by heku** [comment] 2017-10-30 01:12
@Tarig0 , thank you for reply, Yes, you are exact right, but I suppose EF could take care of these(delete/add) as it knows all the relationship so it can delete the group item without any problem here.

**Comment by Tarig0** [comment] 2017-10-30 01:33
Ef has no idea on the relationships in the dB when you attach it. To get ef to "remember" its dB state you will need to query the db first then manipulate the returned items property, with out reassigning it.

**Comment by Tarig0** [comment] 2017-10-30 01:35
The preferred option is for your front end to return added items and deleted items as two lists the attach those as added and deleted ranges.

**Comment by heku** [comment] 2017-10-30 02:08
@Tarig0 Thanks, I believe that would work, my option is the `OnModelCreating` method has tell EF the relationship(one GroupItem belongs to only one Group), and above code purpose is straightforward to update the group's item to item1 and item4, EF really has the ability to do these. Of cause, maybe I worked a wrong direction, just leave this issue opened to see if there is any other feedback.

**Comment by ajcvickers** [comment] 2017-10-30 17:24
@heku Working with graphs of disconnected entities can be tricky. I have been updating the documentation on this. It's not final, but you can see the docs in the PR here: https://github.com/aspnet/EntityFramework.Docs/pull/541

**Comment by dmitry-pavlov** [comment] 2018-01-02 19:17
Sometimes `Attempted to update or delete an entity that does not exist in the store.` exception is raised when your DB scheme is not up to date. Make sure the database scheme is consistent with your entities.

**Comment by Mike-EEE** [comment] 2020-02-20 11:07
In my case I was getting the exception discussed in this thread (first result in Google search) and I fixed it by changing this:

```
context.Entries.Add(new Model.AuthorizationEntry {Id = Guid.NewGuid(), Query = parameter.Query, Context = context});
```

to this:

```
context.Entries.Add(new Model.AuthorizationEntry {Query = parameter.Query, Context = context});
```

Which I am totally OK with. 😁

**Closed** 2022-10-16 11:56 UTC
Labels: closed-by-design
