### ISSUE TITLE
OUTPUT clause without INTO clause

### ISSUE THREAD

**Issue by louislewis2** [dotnet/efcore#3292] opened 2015-10-01 09:11 UTC
We are migrating an application from Asp.Net 4 using EF 6, to Asp.Net 5 with EF 7.
Today I started porting some of the persistence code, and got caught with this error.

The target table 'Project' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.

This problem was not visible in our original application. Is there anything we can do that would allow us to use EF 7? We are not in control of the triggers that may or may not reside on the tables. We are doing integration with an existing application and triggers are created by the host application.

**Comment by rowanmiller** [comment] 2015-10-02 19:24
Closing as a dupe of #1441 and following up there

**Closed** 2022-10-16 09:10 UTC
