### ISSUE TITLE
Scaffold-DbContext not importing similar table names in different Schemas

### ISSUE THREAD

**Issue by JipingWang** [dotnet/efcore#11250] opened 2018-03-13 15:56 UTC
Scaffold-DbContext not importing same table names in different Schemas

### Steps to reproduce
dbo.mytable and tmp.myTable Schemas have similar table names.
Scaffold-DbContext imports both Entity propertites in MyDbContext, but
not only creates one POCO class mytable.
So, building fails. 
### solution
Have to rename one table to be imported.

**Comment by bricelam** [comment] 2018-03-13 17:01
Duplicate of #3988

**Closed** 2022-10-16 12:13 UTC
