### ISSUE TITLE
Failing test: CreateAsync_checks_for_existence_and_retries_if_timeout_until_it_passes

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/efcore#12783] opened 2018-07-24 23:38 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=513800&buildTypeId=XPlat_Windows_Win7_Universe) occasionally with the following error:
```
System.ArgumentException : Keyword not supported: 'PoolBlockingPeriod'.
   at System.Data.SqlClient.SqlConnectionStringBuilder.Reset(Keywords index)
   at System.Data.SqlClient.SqlConnectionStringBuilder.Clear()
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.CreateCreateOperations() in /_/src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs:line 110
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<CreateAsync>d__12.MoveNext() in /_/src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServerDatabaseCreatorTest.<Create_checks_for_existence_and_retries_until_it_passes>d__10.MoveNext() in /_/test/EFCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by ryanbrandenburg** [comment] 2018-07-24 23:38
CreateAsync_checks_for_existence_and_retries_if_cannot_open_file_until_it_passes [failed again](http://aspnetci/viewLog.html?buildId=513800&buildTypeId=XPlat_Windows_Win7_Universe).

**Comment by ryanbrandenburg** [comment] 2018-07-24 23:42
Create_checks_for_existence_and_retries_if_cannot_open_file_until_it_passes [failed again](http://aspnetci/viewLog.html?buildId=513794&buildTypeId=XPlat_Windows_Win8_Universe).

**Comment by ryanbrandenburg** [comment] 2018-07-24 23:46
Create_checks_for_existence_and_retries_if_cannot_open_file_until_it_passes [failed again](http://aspnetci/viewLog.html?buildId=513790&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

**Comment by ryanbrandenburg** [comment] 2018-07-24 23:50
Master_connection_string_contains_filename [failed again](http://aspnetci/viewLog.html?buildId=513788&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

**Comment by Eilon** [comment] 2018-07-25 18:31
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this test failure caused by product code flakiness? (Either our product, or another product we depend on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

@ajcvickers - please assign.

**Comment by ajcvickers** [comment] 2018-07-30 18:05
Duplicate of #12706

**Closed** 2022-10-16 13:21 UTC
