### ISSUE TITLE
sharing same column in a table shared between two entities results in InvalidOperationException at ValidateSharedColumnsCompatibility

### ISSUE THREAD

**Issue by mhDuke** [dotnet/efcore#19139] opened 2019-12-03 05:41 UTC
@ajcvickers when i try to `add-migration` i get
>  'Party.Name' and 'Agent.Name' are both mapped to column 'Name' in 'Parties' but are configured with different nullability.
[efTableSharing.zip](https://github.com/aspnet/EntityFrameworkCore/files/3914779/efTableSharing.zip)

```
public class Party
    {
        public int Id { get; private set; }
        public string Name { get; private set; }
    }
public class Agent
    {
        public int Id { get; private set; }
        public string Name { get; private set; }
    }

```
```
public void Configure(EntityTypeBuilder<Party> b)
        {
            b.ToTable("Parties");

            b.Property(e => e.Name).HasColumnName(nameof(Party.Name))
                .HasMaxLength(100)
                .IsRequired();

            b.HasOne<Agent>().WithOne()
                .HasForeignKey<Agent>(e => e.Id);
        }
public void Configure(EntityTypeBuilder<Agent> b)
        {
            b.ToTable("Parties");

            b.Property(e => e.Name).HasColumnName(nameof(Agent.Name))
                .HasMaxLength(100)
                .IsRequired();
        }
```
//cc @AndriySvyryd

**Comment by ajcvickers** [comment] 2019-12-06 20:47
@MHDuke I was able to reproduce this with 3.0, but it works with 3.1. Can you try with 3.1?

@AndriySvyryd Duplicate?

**Comment by AndriySvyryd** [comment] 2019-12-06 20:48
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/17820

**Closed** 2022-10-16 14:59 UTC
Labels: customer-reported
