### ISSUE TITLE
SelectMany query on OwnsMany relationship throws exception

### ISSUE THREAD

**Issue by jp2masa** [dotnet/efcore#27120] opened 2022-01-05 19:13 UTC
I have this `OwnsMany` relationship:

```cs
modelBuilder.Entity<User>()
    .OwnsMany(x => x.Sessions)
    .WithOwner(x => x.User);
```

And I'm trying to do this query:

```cs
var session = await _db.Users
    .SelectMany(x => x.Sessions)
    .SingleOrDefaultAsync(x => x.RefreshToken == token)
```

And I get this exception:

```
System.InvalidOperationException: 'A tracking query is attempting to project an owned entity without a corresponding owner in its result, but owned entities cannot be tracked without their owner. Either include the owner entity in the result or make the query non-tracking using 'AsNoTracking'.'
```

<details>
    <summary>Stack trace</summary>
    <pre>
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.EntityMaterializerInjectingExpressionVisitor.Inject(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.InjectEntityMaterializers(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.ProcessShaper(Expression shaperExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.VisitShapedQuery(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
    </pre>
</details>

I tried multiple variants, like the following, but none of them work:

1. `Include` after `SelectMany`:

    ```cs
    var session = await _db.Users
        .SelectMany(x => x.Sessions)
        .Include(x => x.User)
        .SingleOrDefaultAsync(x => x.RefreshToken == token)
    ```

2. `AsNoTracking` with `Include` (circular reference error):

    ```cs
    var session = await _db.Users
        .SelectMany(x => x.Sessions)
        .Include(x => x.User)
        .AsNoTracking()
        .SingleOrDefaultAsync(x => x.RefreshToken == token)
    ```

3. `AsQueryable().Include` inside `SelectMany` (I honestly thought this one would work, but no luck...):

    ```cs
    var session = await _db.Users
        .SelectMany(x => x.Sessions.AsQueryable().Include(x => x.User))
        .SingleOrDefaultAsync(x => x.RefreshToken == token)
    ```

`AsNoTracking` without `Include` works, but the owner, i.e. `session.User` is `null`, which is not what I want. I also tried other variants with `Select` and similar, trying to `Include(x => x.User)` in different contexts, but it's always the same error...

**Comment by ajcvickers** [comment] 2022-01-10 10:43
Note from triage: @smitpatel to investigate workarounds and find dupe.

**Comment by smitpatel** [comment] 2022-01-11 17:54
Duplicate of #24807

**Comment by smitpatel** [comment] 2022-01-12 00:18
This is unsupported by design.

Your result contain a particular owned object which matches the filter predicate. You are not retrieving the owner of it in the result hence you must do a non-tracking query. But including `User` navigation will also include `Sessions` navigation since it is pointing to owned entity which are automatically loaded when querying. This will create a cycle which is not breakable. Since it is one to many relationship, for a given Session's User, it can have multiple Sessions including first one. A no tracking query cannot load that cycle else the Session from result and the one inside collection will not match. Owned navigations are always eager loaded and cannot be switched off.

Reconsider the model if you need the result in that structure or do a separate query to assign `User` navigation.

**Comment by jp2masa** [comment] 2022-01-13 02:03
Unfortunately it looks like owned relationships are pretty much unhelpful on most cases... I had to convert all owned relationships to one-to-one or one-to-many at this point, although semantically they're actually owned.

**Closed** 2022-10-16 20:21 UTC
Labels: closed-by-design, customer-reported
