### ISSUE TITLE
Feature request: allow owned entities to be structs

### ISSUE THREAD

**Issue by Neme12** [dotnet/efcore#14236] opened 2018-12-22 19:45 UTC
For owned entities that are inlined into their owner entity's table, the semantics of a struct make a lot of sense and are much more in line with how the entity ends up being stored. These entities do not have an identity. Their properties are inlined into their owners just like struct's fields are inlined into their containing type. Just like structs, they cannot be null because a collection of columns cannot be null independent of the columns themselves being null. They are value objects.

In addition to this, having a property whose type is a custom struct could automatically make it an owned entity without needing any configuration.

**Comment by ajcvickers** [comment] 2018-12-22 22:37
Duplicate of #13947. (Value conversions already work for structs and the semantics aligns much better to value objects than owned entities do.)

**Comment by Neme12** [comment] 2018-12-22 23:14
That's not a duplicate :confused: I don't want to implement a conversion for every owned entity type. I simply want an entity type that is a struct.

**Closed** 2022-10-16 13:45 UTC
Labels: closed-duplicate, customer-reported

**Comment by voroninp** [comment] 2023-12-20 14:52
Looks like Owned Entities became a dead-end.
