### ISSUE TITLE
Exception occur while Registraing a new User in .NetCoreApp

### ISSUE THREAD

**Issue by HassanSiddique** [dotnet/efcore#5950] opened 2016-07-01 21:16 UTC
### The issue

Exception occur while Registring a new user in .NetCoreApp v1.0.0-rc2-3002702
### STACK

**OverflowException: Arithmetic operation resulted in an overflow.**

System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)

```

EF Core version: EF 7 / EF Core
Operating system: Windows 8.1
Visual Studio version: VS 2015 

```

**Comment by rowanmiller** [comment] 2016-07-06 21:59
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bug, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

**Comment by rowanmiller** [comment] 2016-07-06 21:59
Also, I noticed you are using RC2. Have you tried this with the RTM release?

**Comment by HassanSiddique** [comment] 2016-07-10 17:09
@rowanmiller  Yes, I tried RTM release but same error occur 
I search a lot but nothing found helpful

I just Create .NetCore Web Application with individual user authentication and tried to register a new user but same error occur..

**Comment by rowanmiller** [comment] 2016-07-29 23:23
Hey,

I wasn't able to reproduce this:

1. Clean install of Windows 8.1
2. Visual Studio 2015 Update 3
3. .NET Core 1.0.0 - VS 2015 Tooling Preview 2
4. File -> New Project...
5. ASP.NET Core Application (.NET Core)
6. Web Application template with Individual Authentication
7. Debug -> Start Without Debugging
8. Click Register
9. Complete and submit form
10. Database Error Page shows
11. Click Apply Migrations
12. Refresh page (registration completes)

I have heard of folks having issue with LocalDB on Win8.1, maybe use Server Explorer to see if you can connect to the `(localdb)\mssqllocaldb` SQL Server instance?

~Rowan

**Comment by divega** [comment] 2016-08-08 18:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 09:48 UTC
