### ISSUE TITLE
error CS0246: The type or namespace name 'SqliteConnection' could not be found (are you missing   a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by mahavirjadhav** [dotnet/efcore#30686] opened 2023-04-13 23:57 UTC
Hello, 
I am geeting error for following code ( AuthPermissions.SetupExtensions class)
```c#
   private static SqliteConnection SetupSqliteInMemoryConnection()
        {
            var connectionStringBuilder = new SqliteConnectionStringBuilder { DataSource = ":memory:" };
            var connectionString = connectionStringBuilder.ToString();
            var connection = new SqliteConnection(connectionString);
            connection.Open();  //see https://github.com/aspnet/EntityFramework/issues/6968
            return connection;
        }
```

error CS0246: The type or namespace name 'SqliteConnection' could not be found (are you missing   a using directive or an assembly reference?)

Please can you help.

**Comment by ajcvickers** [comment] 2023-04-26 16:24
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-04-26 16:24 UTC
Labels: customer-reported

**Comment by noloader** [comment] 2023-07-03 09:43
I'm having this issue, too.

The problem I'm running into is, Microsoft's documentation does not say which reference to add: https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlite.sqliteconnection . So I don't know how to fix the compile error:

```
> csc.exe -target:exe -out:datatest.exe -reference:mscorlib.dll,system.core.dll,system.data.dll datatest.cs
Microsoft (R) Visual C# Compiler version 2.10.0.0 (b9fb1610)
Copyright (C) Microsoft Corporation. All rights reserved.

datatest.cs(4,19): error CS0234: The type or namespace name 'SQLite' does not exist in the namespace 'System.Data' (are you missing an assembly reference?)
datatest.cs(5,19): error CS0234: The type or namespace name 'SQLite' does not exist in the namespace 'System.Data' (are you missing an assembly reference?)
```

In the old days, Microsoft's documentation used to tell us which libraries or DLLs we needed to include. It would be nice to see that again.

**Comment by roji** [comment] 2023-07-03 19:53
@noloader in modern .NET development it really is recommended to use nuget; [our docs](https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/?tabs=netcore-cli) show how to do this and which package is needed, and any IDE can automatically add the necessary `using` directives.
