### ISSUE TITLE
Migrations / Temporal Tables: Temporal SYSTEM_TIME period is already defined on table when executing idempotent script

### ISSUE THREAD

**Issue by dylinmaust** [dotnet/efcore#26252] opened 2021-10-05 15:56 UTC
EF Core 6 RC1 migrations generate an idempotent script which fails on subsequent runs. Should ADD PERIOD FOR SYSTEM_TIME commands be wrapped in `EXEC`?

> Temporal SYSTEM_TIME period is already defined on table 'dbo.Posts'.

The offending command in the SQL script:
```
IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20210928175334_EnablePostTemporalTables')
BEGIN
    ALTER TABLE [Posts] ADD PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
END;
GO
```

Model configuration:

```
builder.ToTable("Posts", tb => tb.IsTemporal(ttb =>
{
    ttb.HasPeriodStart("ValidFrom");
    ttb.HasPeriodEnd("ValidTo");
    ttb.UseHistoryTable("PostsHistory");
}));
```

### Include provider and version information

EF Core version: 6.0.0-rc.1.21452.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: Mac OS
IDE: Visual Studio Code

**Comment by ajcvickers** [comment] 2021-10-05 16:00
@dylinmaust Duplicate of #26166, which should be fixed in the latest [daily build](https://github.com/dotnet/efcore/blob/release/6.0/docs/DailyBuilds.md). Can you give it a try?

**Comment by dylinmaust** [comment] 2021-10-05 16:03
@ajcvickers Sorry I missed that! Thank you for the reference - will use the daily build.

**Closed** 2022-10-16 20:09 UTC
Labels: customer-reported
