### ISSUE TITLE
Remove entities without requiring them to be loaded

### ISSUE THREAD

**Issue by CrossBound** [dotnet/efcore#14639] opened 2019-02-07 17:32 UTC
With existing EF, we don't have the ability to delete entities from the database without first requiring them to be loaded into the context or working around by directly SQLing the context's connection to the database. 

Normal usage might be something like this.
```C#
using (var db = new BloggingContext())
{
    var recordsToDelete = db.Blogs
        .Where(b => b.BlogId > 1);

    foreach(var blog in recordsToDelete)
    {
        db.Blogs.Remove(blog);
    }

    db.SaveChanges();
}
```

This works, but is inefficient because it requires at a minimum 2 round-trips to the server.

I know there are workarounds such as reverting to ADO.NET or manipulating the change tracker, but support for this should be built-in to the remove command. 

I Propose that the Remove command be modified to accept a predicate which can directly be executed against the database without requiring retrieval first.

Example of what _should_ be supported:
```C#
using (var db = new BloggingContext())
{
    db.blogs.Remove(b => b.BlogID > 1);
}
```
From my perspective, it should be relatively easy to translate the above code to the following SQL:
```
DELETE FROM dbo.Blogs WHERE BlogID > 1;
```

**Comment by smitpatel** [comment] 2019-02-07 18:21
Duplicate of #795

**Closed** 2022-10-16 13:51 UTC
Labels: closed-duplicate, customer-reported
