### ISSUE TITLE
Query :: nested Conditional expressions could be optimized 

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#2881] opened 2015-08-19 18:20 UTC
Currently nested Conditional expressions are not optimized, we translate them to:
CASE WHEN c1 THEN r1 ELSE (CASE WHEN c2 THEN r2 ELSE r3 END) END

We could instead simplify it to:
CASE WHEN c1 THEN r1 WHEN r2 THEN r2 ELSE r3 END

**Comment by divega** [comment] 2015-08-19 22:02
FWIW, SQL Server has a limit of 10 levels of nesting and this did become an issue with previous versions of EF because we used to generate nested case statements often, so we had to do case flattening as a bug fix rather than as optimization. Not saying that we are anywhere near this with EF7.

**Comment by smitpatel** [comment] 2019-11-15 06:00
Closing as duplicate of #12729

**Comment by Yen-David** [comment] 2019-12-06 22:58
@smitpatel, it's not really a duplicate. It was fixed in .Net Core 2.2 but appeared again in .Net Core 3.0! You must re-close it (close it again).

**Closed** 2022-10-16 09:05 UTC
Labels: closed-duplicate
