### ISSUE TITLE
Tracking issue when adding new entity with new navigational properties

### ISSUE THREAD

**Issue by fmiskuly-eastman** [dotnet/efcore#27838] opened 2022-04-18 20:55 UTC
I am using EF Core 3.1.23 w .NET Core 3.1

**Explanation:**

I am storing information about an xml file in a database. 

The Xml File is stored in the following format: 

```
<section name="NAME">
        <key name="NAME" value="0" />
        ...
</section>
```

The xml file has around 40 sections, each with 1 - 20 fields (keys) 

- Each section has many keys
- Each key has 1 section

**Corresponding Database classes:**

```C#
    public class XmlKey
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual XmlSection XmlSection { get; set; }
        public int? XmlSectionId { get; set; }
    }

    public class XmlSection
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }

        public List<XmlKey> Keys { get; set; }
    }

    public class XmlMapping
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public virtual XmlKey XmlKey { get; set; }
        public int? XmlKeyId { get; set; }

        public int Value { get; set; }
    }

```

- Each Mapping is a key and a value
- Each configuration has many mappings

**Executed code:** 

```C#
    using (DatabaseContext dbContext = new DatabaseContext())
            {

                //create new configuration and add to list of nav props
                var config = new XmlConfiguration()
                {
                    Name = Name,
                    Mappings = XmlMappings.ToList()
                };

                dbContext.XmlConfigurations.Attach(config);
                dbContext.SaveChanges();
            }
```

When attemping to create a new configuration, and adding new mappings to that configuration, if 2 mapped keys have the same section *the following error* is produced: 

*'The instance of entity type 'XmlSection' cannot be tracked because another instance with the key value '{Id: 12}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.'*

I am assuming this happens after adding the first mapping with key 1 and section 1, when adding key 2 with section 1, section 1 is already tracked.

The (theoretical) flow of this would go: 

1) Create new xml mappings in UI by selecting a Key and a Value (all keys have same section)
2) Create new configuration containing a list of mappings
3) Save mappings now that we know we are for sure saving this configuration
4) Save configuration, add mappings to configuration

However this results in the error above. 

**How to avoid this behavior?** I have tried attaching, detaching, loading the navigation props AsNoTracking();, adding nav props instead of setting list explicitly, changed db context options. 

I am very confused as to me this seems to be completely normal EF behavior

**Comment by ajcvickers** [comment] 2022-04-19 12:51
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-04-28 13:06
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:32 UTC
Labels: closed-could-not-reproduce, customer-reported
