### ISSUE TITLE
System.NullReferenceException on navigational property (2.0)

### ISSUE THREAD

**Issue by MaklaCof** [dotnet/efcore#9464] opened 2017-08-18 10:33 UTC
This query:
```
var resultWorks = await this.context.Carts
                .Where(t => t.OwnerId == this.LoggedInUserId)
                .Select(t => new
                {
                    something = t.Configuration != null && t.Configuration.Parameters != null ? t.Configuration.Parameters.ToArray() : null
                })
                .ToArrayAsync();

```
Entity framework class:
```
//Partial DbCart:
        public int? ConfigurationId { get; set; }
        public DbConfiguration Configuration { get; set; }

//Partial DbConfiguration 
public List<DbConfigurationParameter> Parameters { get; set; }
```
throws error
```
Exception message: System.NullReferenceException: 'Object reference not set to an instance of an object.'
Stack trace:
Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler+<_IncludeAsync>d__18.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor+<_ExecuteAsync>d__8.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+AsyncSelectEnumerable+AsyncSelectEnumerator+<MoveNext>d__3.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider+ExceptionInterceptor+EnumeratorExceptionInterceptor+<MoveNext>d__5.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
System.Collections.Generic.AsyncEnumerableHelpers+<ToArrayWithLength>d__1.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
System.Collections.Generic.AsyncEnumerableHelpers+<ToArray>d__0.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

### Further technical details
EF Core version: (2.0)
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer) - SQL Server 2016
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017)

Query is part of bigger query, which freeze entire execution of code. Step over (F10) never actually step over and web request nevery finish executing (there is no response to client, no error nothing).
This worked with EF Core 1.1.2.
```
return await this.context.Carts
                .Where(t => t.OwnerId == this.LoggedInUserId)
                .OrderBy(t => t.Order).ThenBy(t => t.Id)
                .Select(t => new ViewCartModel()
                {
                    id = t.Id,
                    quantity = t.Quantity,
                    model = t.Title,
                    modelId = t.ModelId,
                    configurationId = t.ConfigurationId,
                    processing = false,
                    price = t.Configuration.Parameters
                        .Where(t2 => t2.Parameter.PriceType == ePriceType.Price)
                        .Select(t2 => BitConverter.ToDouble(t2.ParameterValue.Value, 0))
                        .Sum()
                })
                .ToArrayAsync();
```

**Comment by ajcvickers** [comment] 2017-08-18 18:42
@maumar After investigation let's circle back and see if we should patch.

**Comment by ivanovmv90** [comment] 2017-08-21 05:46
Looks like problem with async methods. For me, problem dissapeared after changing ToListAsync() with ToList().

Also, https://github.com/aspnet/EntityFrameworkCore/issues/9449

**Comment by MaklaCof** [comment] 2017-08-21 07:15
For me too. Thank you very much. I really needed a workaround (until bug is fixed) for this.

**Comment by maumar** [comment] 2017-08-22 23:03
dupe of #9038 
@MaklaCof I listed some workarounds in the original issue

**Comment by ajcvickers** [comment] 2017-09-12 17:55
Hi @MaklaCof. We are gathering information on the use of EF Core pre-release builds. You reported this issue shortly after the release of 2.0.0 RTM. It would be really helpful if you could let us know:

- Did you consider testing your code against the pre-release builds?
- Was there anything blocking you from using pre-release builds?
- What do you think could make it easier for you to use pre-release builds in the future?

Thanks in advance for any feedback. Hopefully this will help us to increase the value of pre-release builds going forward.

**Comment by MaklaCof** [comment] 2017-09-13 05:22
> Did you consider testing your code against the pre-release builds?

Yes, but other libraries hold me back, because they didn't support pre-release .NET Core 2.0.
> What do you think could make it easier for you to use pre-release builds in the future?

Faster bug fix and **new** build after someone find a bug. It is hard if you found a bug that requires from you to write different query (like this one) and you stuck with your code. You have to write workarounds in every place or move to other task. 
This bug for example force me to change over 70 queries to sync and after a new release I will have to change it back to async. And since bug is already fixed for a month, but you can not provide a hot-fix, I assume same will happened with pre-release. So in pre-release there are a lot of more bug, some like this one and it would seriously slow me down when coding. I can not say to my boss that I am behind by schedule because someone fixed bug, but can not make new release. He wants result not excuses.

I should add that you did a great job with EF (I never use it before and I came from Delphi, PHP, Javascript world). I really like how queries can be written with EF.  
I really miss some feature where we could lower the request made to server, but [EF Plus](https://github.com/zzzprojects/EntityFramework-Plus) solve it. I mean update and delete without querying first.

**Comment by ajcvickers** [comment] 2017-09-15 21:56
@MaklaCof Thanks for the feedback; much appreciated.

**Closed** 2022-10-16 11:16 UTC
