### ISSUE TITLE
EF Core 5.0 RC1 Identity with Nullable Reference Types fails

### ISSUE THREAD

**Issue by gabynevada** [dotnet/efcore#22812] opened 2020-09-28 16:09 UTC
When nullable reference types are enabled, the UserManager.FindByEmailAsync(string email) and other UserManager calls fails with **Data is Null. This method or property cannot be called on Null values.**

```
  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>
```

```c#
  public class UserForLoginDto
  {
    public UserForLoginDto(string email, string password)
    {
      this.Email = email;
      this.Password = password;
    }
    [EmailAddress]
    [Required]
    public string Email { get; set; }
    [MinLength(8, ErrorMessage = "Password must be more than 8 characters long.")]
    [Required]
    public string Password { get; set; }
    public string? ReCaptchaResponseToken { get; set; }
  }
```

Fails here
```c#
var user = await _userManager.FindByEmailAsync(userForLoginDto.Email);
```

If nullable reference types are disabled, it starts working properly.

Here is the error message:
```
Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'Bioportal.API.Models.BioportalContext'.
      System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
         at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
         at Microsoft.Data.SqlClient.SqlBuffer.get_String()
         at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
         at lambda_method181(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
         at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
         at Microsoft.Data.SqlClient.SqlBuffer.get_String()
         at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
         at lambda_method181(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

### Provider and version information

EF Core version: 5.0.0-rc.1.20451.17
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10 Pro Build 1863
IDE: Visual Studio Code

**Comment by roji** [comment] 2020-09-28 16:42
@gabynevada is UserForLoginDto being mapped to the database via EF Core, or is it a type whose Email property you're passing to FindByEmailAsync?

More generally, can you please post a minimal project which reproduces the problem?

**Comment by gabynevada** [comment] 2020-09-28 16:56
@roji It's mapped via a .Net Core Controller from a JSON body.

During debugging I can confirm that the Email property in the Dto has a an email string value, and after turning off nullable reference types it works as expected.

It appears that the problem is with the EF Core Identity services as all other EF Core calls work except where we utilize the UserManager.

I'll see if I can make and post a project with the problem.

**Comment by roji** [comment] 2020-10-13 12:49
@gabynevada any luck with that sample project? I've just scaffolded a basic ASP.NET webapp with identity, turned on identity, and it seems like I can use FindByEmailAsync just fine. If there's indeed an issue here, the window for fixing anything is almost closed for 5.0 - so a speedy response would be great.

**Comment by Saibamen** [comment] 2020-10-13 14:38
@roji: How many RCs do you planning to release? Only 2?

**Comment by roji** [comment] 2020-10-13 15:51
Yeah, RC2 should be out today (definitely too late for that), the next one would be the final GA release.

**Comment by ajcvickers** [comment] 2020-10-26 16:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:02 UTC
Labels: closed-could-not-reproduce, customer-reported
