### ISSUE TITLE
Cryptic NullpointerException instead of TimeoutException when using "await using", ToList() and SplitQueryBehaviour

### ISSUE THREAD

**Issue by Maskoe** [dotnet/efcore#25452] opened 2021-08-08 15:03 UTC
## File a bug

Hello,

I am running this code

```
 var connStr = "Server=Azure; " +
     "Initial Catalog=MyCatalog; " +
     "Persist Security Info=False; " +
     "User ID=superadmin; " +
     "Password=secret; " +
     "MultipleActiveResultSets=False; " +
     "Encrypt=True; " +
     "TrustServerCertificate=False; " +
     "Connection Timeout=90;";

 var options = new DbContextOptionsBuilder<MyContext>()
     .UseSqlServer(connStr, o => o.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery))
     .Options;

 await using var context = new MyContext(options);

 var result = context.Parents
    .Include(x => x.Children1)
    .Include(x => x.Children2)
    .Include(x => x.Children3)
    .Include(x => x.Children4)
    .ToList();
```

and I'm getting the following Exception:

```
Exception thrown: 'Microsoft.Data.SqlClient.SqlException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'System.NullReferenceException' in Microsoft.EntityFrameworkCore.Relational.dll
Object reference not set to an instance of an object.
at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.Dispose()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at ConsoleApp1.Program.<Main>d__0.MoveNext() in C:\Projects\IFF\src\NetCore\ConsoleApp1\Program.cs:line 21
```

I apologize for not being able to provide a ready to run example, but I only have access to a company azure account.
This exception happens after about ~30 seconds every single time.

If I remove the `await `from `await using`, I get the expected TimeoutException.
If I use `await ... ToListAsync()` , I get the expected TimeoutException.
If i use `SingleQueryBehaviour`, I get the expected TimeoutException.

### Include provider and version information

EF Core version: 5.0.8 
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Win10
IDE:  Visual Studio 2019 16.10.4

**Comment by smitpatel** [comment] 2021-08-10 16:59
Duplicate of #23157

**Closed** 2022-10-16 19:42 UTC
Labels: closed-duplicate, customer-reported
