### ISSUE TITLE
Invalid attempt to call ReadAsync when reader is closed.

### ISSUE THREAD

**Issue by AJB-Sharp** [dotnet/efcore#18070] opened 2019-09-26 07:20 UTC
I have raise a bug with EFC (Invalid attempt to call ReadAsync when reader is closed. #18039) and had a response saying the error is through in Blazor. Please can someone have a look as my code was working fine before release.

**Comment by smitpatel** [comment] 2019-09-26 16:54
@AJB-Sharp - Please provide a code which demonstrate the issue you are seeing and does not use any package outside of EF Core.

**Comment by ajcvickers** [comment] 2019-10-07 15:53
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:45 UTC
Labels: closed-could-not-reproduce, customer-reported
