### ISSUE TITLE
I expected client evaluation exception using a expression property in my select

### ISSUE THREAD

**Issue by flindby** [dotnet/efcore#27841] opened 2022-04-19 14:25 UTC
When I unintentionally used an expression property instead of a constant in my select, the generated SQL represented the whole entity (whole object graph) instead of just the properties in the select list. I thought that I would have been presented a "client evaluation exception" or similar. Is it possible to configure EF Core to throw when using a property instead of a constant for instance?

```
public class Foo : FooBase
{
    public override string DefinitionId => FooDefinitionIdName;
    public const string FooDefinitionIdName = "my_const_string";

    public string FooName { get;set; }

    // Other properties and relations
}

public abstract class FooBase
{
    public abstract string DefinitionId { get; }
}

public class FooInfo
{
    public string Name { get;set; }
    public string DefinitionId { get; set; }
}

public async Task<FooInfo> GetFooInfoByIdAsync(string id)
{
    return await DbContext.Set
        .AsNoTracking()
        .Where(foo => foo.Id == id)
        .Select(foo => new FooInfo
        {
            Name = foo.FooName,
            DefinitionId = foo.DefinitionId // <--- This is the cause that generates SQL for the whole object graph
        })
        .FirstOrDefaultAsync();
}
```

EF Core version: 6.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0)
Operating system: Windows 10
IDE: Visual Studio 2022 17.1

**Comment by roji** [comment] 2022-04-19 16:03
@flindby there's no option for making EF Core throw when using a property, since using a property is very frequently what users really need to do. You'll have to review that your queries are written to do what you actually want them to.

**Comment by stevendarby** [comment] 2022-04-19 19:12
Related? https://github.com/dotnet/efcore/issues/24509

**Comment by smitpatel** [comment] 2022-04-20 00:23
Duplicate of #24509

**Closed** 2022-10-16 20:32 UTC
Labels: closed-duplicate, customer-reported
