### ISSUE TITLE
"dotnet ef migrations bundle" => bundle.exe unexpected exit code on failing migrations

### ISSUE THREAD

**Issue by mrlux** [dotnet/efcore#27783] opened 2022-04-07 13:34 UTC
## Question
I'm using the 'new' ```dotnet ef migrations bundle``` command to create a bundle migration executable
I package this into a docker file to run as a pre-deployment step of my release process (using argocd).

What I noticed is that when the bundle application runs into an exception like a missing connection string as an example the exit code is 1 (failure). This is expected behavior. 

The thing that I did not expect is that when the bundle application starts but hits an exception in one of the migrations itself the exit code is 0 (success). As this exit code passed to the docker container exit code my pre-deployment step thinks all is good and continues the deployment.

I am wondering if I'm doing something wrong as I would expect that the main usage of this bundle application would be in a pre-deployment scenario being:

- Build/release pipeline
- Pre-deployment hooks using helm or argocd
- ....

## Proposed solution/change
It would be nice if we could pass an exit code toggle/option to the bundle application on how to respond to failing migrations

```
efbundle --hard-fail-on-migration-failure
```

#### Docker file
```Docker
FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

ENV CONNECTION=''
ENV DATABASE_NAME=''

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Sample.Infrastructure/Sample.Infrastructure.csproj", "Sample.Infrastructure/"]
COPY ["Sample.Core/Sample.Core.csproj", "Sample.Core/"]
RUN dotnet restore "Sample.Infrastructure/Sample.Infrastructure.csproj"
COPY . .
WORKDIR "/src/Sample.Infrastructure"
RUN dotnet build "Sample.Infrastructure.csproj" -c Release -o /app/build

RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

FROM build AS publish
RUN dotnet ef migrations bundle --project Sample.Infrastructure.csproj -r linux-x64 --verbose --configuration Bundle --self-contained -f -o /app/efbundle

FROM base AS final
WORKDIR /app
COPY --from=publish /app/efbundle .

ENTRYPOINT ./efbundle --prefix-output --verbose --connection "${CONNECTION}" | sed 's/{CATALOG_NAME}/'$DATABASE_NAME'/;'
```

#### Log output
```log
info:    Microsoft.Data.SqlClient.SqlException (0x80131904): Reference to database and/or server name in 'samplxxxx.dbo.EVChargers' is not supported in this version of SQL Server.
info:       at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
info:       at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
info:       at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
info:       at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
info:       at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
info:       at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
info:       at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
info:       at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
info:       at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
info:       at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
info:       at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
info:       at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
info:       at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsBundle.ExecuteInternal(String[] args)
info:       at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsBundle.<>c__DisplayClass6_0.<Configure>b__0(String[] args)
info:       at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
info:       at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsBundle.Execute(String context, Assembly assembly, Assembly startupAssembly, String[] args)
info:    ClientConnectionId:5e3b07c9-2e34-4232-9787-dce9dd15362a
info:    Error Number:40515,State:1,Class:15
error:   Reference to database and/or server name in 'samplxxxx.dbo.EVChargers' is not supported in this version of SQL Server.
```

![image](https://user-images.githubusercontent.com/2972751/162222879-68480928-dc4a-49e2-9090-82ad06a1e64c.png)

**Comment by alexdresko** [comment] 2022-04-21 18:14
I landed here because I was trying to find out how the bundle application handles SQL timeouts. We have a few migrations that take longer than the default timeout to complete, so we call `DbContext.Database.SetCommandTimeout(...)` just before running the migrations.

My concern now is that efbundle.exe won't let us know if a SQL timeout occurs due to a specific migration.

**Comment by roji** [comment] 2022-04-21 18:32
@alexdresko on most providers, you can set the command timeout via the connection string by adding `Command Timeout=X` where X is the timeout in seconds.

**Comment by alexdresko** [comment] 2022-04-22 13:13
> @alexdresko on most providers, you can set the command timeout via the connection string by adding Command Timeout=X where X is the timeout in seconds.

This is an acceptable solution, but not ideal from a devops perspective. I'll now have to manage multiple nearly duplicate connection strings. It would be nice if a single connection string could be used for both.  It'd be ideal, if possible, to add a `--timeout` option to efbundle.exe.

**Comment by roji** [comment] 2022-04-25 09:08
@alexdresko I've opened #27878 to track that specific request.

**Comment by bricelam** [comment] 2022-08-26 21:36
@mrlux I'm not able to repro this. The exit code is non-zero when an error occurs:

```
C:\Users\bricelam\source\repos\ConsoleApp38\ConsoleApp38>efbundle
Applying migration '20220826212701_InitialCreate'.
Failed executing DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
THROW 50000, 'This is a SQL error.', 0;
Microsoft.Data.SqlClient.SqlException (0x80131904): This is a SQL error.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsBundle.ExecuteInternal(String[] args)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsBundle.<>c__DisplayClass6_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsBundle.Execute(String context, Assembly assembly, Assembly startupAssembly, String[] args)
ClientConnectionId:02b6fcc3-cb6a-4445-8789-5f2e6893d2b9
Error Number:50000,State:0,Class:16
This is a SQL error.

C:\Users\bricelam\source\repos\ConsoleApp38\ConsoleApp38>ECHO %ERRORLEVEL%
1
```

Are you perhaps failing to propagate the exit code from inside a script?

**Comment by ajcvickers** [comment] 2022-09-06 17:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:31 UTC
Labels: closed-could-not-reproduce, customer-reported
