### ISSUE TITLE
Created query for projection with ownedMany and join is wrong

### ISSUE THREAD

**Issue by KillerBoogie** [dotnet/efcore#34749] opened 2024-09-24 20:33 UTC
Update: I also got a null exception. I connected it first to the wrong query, but it was a constructor issue for the DTO. I corrected the code below.

Below is the relevant code. It is part of a bigger project. It is not easy and very time consuming to create a reduced working project. I hope the issue can be understood by the posted code.

This is the projection that causes the issue. It just tries to return location data with nested cover images. The image Uri, width and height is pulled from the Image collection. Therefore a join is created. 

``` 
List<LocationMLResponse> Locations;

var query = dbContext.Location.AsNoTracking().AsSplitQuery()
            .Select(location => new LocationMLResponse(
             location.Id.Value,
             location.Name.ToStringDictionary(),
             location.CoverImages
                 .Join(dbContext.Image.AsNoTracking(),
                 danceCoverImage => danceCoverImage.ImageId,
                 image => image.Id,
                 (danceCoverImage, image) => new ImageItemResponse(
                     danceCoverImage.ImageId.Value,
                     danceCoverImage.DisplayOrder,
                     danceCoverImage.Language == null ? null : danceCoverImage.Language.Tag,
                     danceCoverImage.ScreenSize == null ? null : danceCoverImage.ScreenSize.Value,
                     danceCoverImage.FocusPointX,
                     danceCoverImage.FocusPointY,
                     image.Uri.ToString(),
                     image.MetaData.Width,
                     image.MetaData.Height
                 )).ToList(),
             location.Address.MapToDto(),
             location.Created,
             location.LastModified,
             location.Version
             ));

 Locations = await query.ToListAsync();
 
 public record LocationMLResponse(
   object Id,
   Dictionary<string, string> Name,
   List<ImageItemResponse> CoverImage,
   AddressDto Address,
   DateTime Created,
   DateTime LastModified,
   ulong Version
   )
 ```
The projection creates 3 queries. The first 2 queries are sufficient and would return the correct result. The 3rd query is unnecessary. I don't understand why it is created. It leads to a wrong response.

 ```
 SELECT [l].[LocationId], [l].[Name], [l].[Created], [l].[CreatedBy], [l].[CreatedInNameOf], [l].[LastModified], [l].[LastModifiedBy], [l].[LastModifiedInNameOf], [l].[TId], [l].[Version], [l].[Address_City], [l].[Address_CountryId], [l].[Address_CountryName], [l].[Address_DeliveryInstruction], [l].[Address_State], [l].[Address_Street], [l].[Address_StreetAffix], [l].[Address_StreetNumber], [l].[Address_ZipCode]
 FROM [VC].[Location] AS [l]
 ORDER BY [l].[LocationId]
 
SELECT [t].[ImageId], [t].[DisplayOrder], [t].[Language], [t].[ScreenSize], [t].[FocusPointX], [t].[FocusPointY], [t].[Uri], [t].[c], [t].[c0], [l].[LocationId]
FROM [VC].[Location] AS [l]
INNER JOIN (
    SELECT [l0].[ImageId], [l0].[DisplayOrder], [l0].[Language], [l0].[ScreenSize], [l0].[FocusPointX], [l0].[FocusPointY], [i].[Uri], CAST([i].[MetaData_Width] AS bigint) AS [c], CAST([i].[MetaData_Height] AS bigint) AS [c0], [l0].[LocationId]
    FROM [VC].[LocationCoverImage] AS [l0]
    INNER JOIN [VC].[Image] AS [i] ON [l0].[ImageId] = [i].[ImageId]
) AS [t] ON [l].[LocationId] = [t].[LocationId]
ORDER BY [l].[LocationId]

SELECT [l0].[TId], [l0].[DisplayOrder], [l0].[FocusPointX], [l0].[FocusPointY], [l0].[ImageId], [l0].[Language], [l0].[LocationId], [l0].[ScreenSize], [l].[LocationId]
FROM [VC].[Location] AS [l]
INNER JOIN [VC].[LocationCoverImage] AS [l0] ON [l].[LocationId] = [l0].[LocationId]
ORDER BY [l].[LocationId]
 ```
 
I also tried without SplitQuery. The result again has an additional `LEFT JOIN` that makes no sense.

```
SELECT [l].[LocationId], [l].[Name], [t].[ImageId], [t].[DisplayOrder], [t].[Language], [t].[ScreenSize], [t].[FocusPointX], [t].[FocusPointY], [t].[Uri], [t].[c], [t].[c0], [t].[TId], [t].[ImageId0], [l].[Created], [l].[CreatedBy], [l].[CreatedInNameOf], [l].[LastModified], [l].[LastModifiedBy], [l].[LastModifiedInNameOf], [l].[TId], [l].[Version], [l].[Address_City], [l].[Address_CountryId], [l].[Address_CountryName], [l].[Address_DeliveryInstruction], [l].[Address_State], [l].[Address_Street], [l].[Address_StreetAffix], [l].[Address_StreetNumber], [l].[Address_ZipCode], [l1].[TId], [l1].[DisplayOrder], [l1].[FocusPointX], [l1].[FocusPointY], [l1].[ImageId], [l1].[Language], [l1].[LocationId], [l1].[ScreenSize]
FROM [VC].[Location] AS [l]
LEFT JOIN (
    SELECT [l0].[ImageId], [l0].[DisplayOrder], [l0].[Language], [l0].[ScreenSize], [l0].[FocusPointX], [l0].[FocusPointY], [i].[Uri], CAST([i].[MetaData_Width] AS bigint) AS [c], CAST([i].[MetaData_Height] AS bigint) AS [c0], [l0].[TId], [i].[ImageId] AS [ImageId0], [l0].[LocationId]
    FROM [VC].[LocationCoverImage] AS [l0]
    INNER JOIN [VC].[Image] AS [i] ON [l0].[ImageId] = [i].[ImageId]
) AS [t] ON [l].[LocationId] = [t].[LocationId]
LEFT JOIN [VC].[LocationCoverImage] AS [l1] ON [l].[LocationId] = [l1].[LocationId]
ORDER BY [l].[LocationId], [t].[TId], [t].[ImageId0]

```

The `Location` object has a list of `ImageItems`. `ImageItems` link to images from the Image collection with additional properties. ML<> and MLRequired<> are value objects that allow storing text in different languages. LocationName and Address are also value objects.

```
public class Location : VersionedEntity<LocationId>
{
    public MLRequired<LocationName> Name { get; private set; }
    public IReadOnlyList<ImageItem> CoverImages => _coverImages.AsReadOnly();
    private List<ImageItem> _coverImages;
    public Address Address { get; private set; }

#pragma warning disable CS8618 
        private Location() { }
#pragma warning restore CS8618 
 }
 
 public record ImageItem (
      ImageId ImageId,
      int? DisplayOrder = null,
      Language? Language = null,
      ScreenSize? ScreenSize = null,
      decimal? FocusPointX = null, 
      decimal? FocusPointY = null
      );
  
public class Image : VersionedEntity<ImageId>
{
    public FileName FileName { get; private set; }
    public ML<ImageDescription> Description { get; private set; }
    public Uri Uri { get; private set; }
    public ImageMetaData MetaData { get; private set; }

#pragma warning disable CS8618
        protected Image() { }
#pragma warning restore CS8618  
}

public record ImageMetaData
{
    public int? Width { get; private set; }
    public int? Height { get; private set; }
    public int? Size { get; private set; }

    private ImageMetaData(int? size, int? width, int? height)
    {
        Size = size;
        Width = width;
        Height = height;
    }
}       
```

This is the EF Core configuration for Location. Since we use guids as ids we add a technical cluster key (TId).

``` 
public class LocationConfiguration : IEntityTypeConfiguration<Location>
{
    public void Configure(EntityTypeBuilder<Location> entity)
    {
        entity.ToTable("Location", VCDbContext.Schema);

        entity.Property<int>("TId").UseIdentityColumn().HasColumnOrder(0);
        entity.HasIndex("TId").IsUnique().IsClustered();

        entity.HasKey(e => e.Id).IsClustered(false);
        entity.Property(e => e.Id).HasColumnName(nameof(LocationId)).HasColumnOrder(1);

        entity.Property(e => e.Name);

        entity.OwnsMany(e => e.CoverImages, ci =>
        {
            ci.ToTable("LocationCoverImage");
            ci.WithOwner().HasForeignKey("LocationId").HasConstraintName("FK_LocationCoverImage_Location_LocationId");
            ci.HasIndex("LocationId").HasDatabaseName("IX_LocationCoverImage_LocationId");
            ci.Property<long>("TId").HasColumnOrder(0);
            ci.HasKey("TId");
            ci.Property(i => i.ImageId).HasColumnName("ImageId").IsRequired();
            ci.HasOne<Image>()
                .WithMany()
                .HasForeignKey(i => i.ImageId)
                .HasConstraintName("FK_LocationCoverImage_ImageId")
                .OnDelete(DeleteBehavior.NoAction);
            ci.Property(i => i.DisplayOrder);
            ci.Property(i => i.FocusPointX).HasPrecision(precision:4, scale:2);
            ci.Property(i => i.FocusPointY).HasPrecision(precision:4, scale:2);
        });

        entity.ComplexProperty(e => e.Address).Property(e => e.DeliveryInstruction);
        entity.ComplexProperty(e => e.Address).Property(e => e.Street);
        entity.ComplexProperty(e => e.Address).Property(e => e.StreetNumber);
        entity.ComplexProperty(e => e.Address).Property(e => e.StreetAffix);
        entity.ComplexProperty(e => e.Address).Property(e => e.ZipCode);
        entity.ComplexProperty(e => e.Address).Property(e => e.City);
        entity.ComplexProperty(e => e.Address).Property(e => e.State);
        entity.ComplexProperty(e => e.Address).Property(e => e.CountryId);
        entity.ComplexProperty(e => e.Address).Property(e => e.CountryName);

        entity.Property(e => e.Version).IsRowVersion().HasConversion<byte[]>();
    }
}
```

Image Configuration:

```
 public class ImageConfiguration : IEntityTypeConfiguration<Image>
 {
     public void Configure(EntityTypeBuilder<Image> entity)
     {
         entity.ToTable("Image", VCDbContext.Schema);

         entity.Property<int>("TId").UseIdentityColumn().HasColumnOrder(0);
         entity.HasIndex("TId").IsUnique().IsClustered();

         entity.HasKey(e => e.Id).IsClustered(false);
         entity.Property(e => e.Id).HasColumnName(nameof(ImageId)).HasColumnOrder(1);

         entity.Property(e => e.FileName).HasMaxLength(FileName.MaxLength).HasColumnOrder(2);
         entity.HasIndex("FileName").IsUnique();
         entity.Property(e => e.Description).HasColumnOrder(3);

         entity.Property(e => e.Uri).HasColumnOrder(4);
         entity.HasIndex("Uri").IsUnique();
         entity.ComplexProperty(e => e.MetaData).Property(e => e.Width).HasColumnOrder(5);
         entity.ComplexProperty(e => e.MetaData).Property(e => e.Height).HasColumnOrder(6);
         entity.ComplexProperty(e => e.MetaData).Property(e => e.Size).HasColumnOrder(7);

         entity.Property(e => e.Version).IsRowVersion().HasConversion<byte[]>();
     }
 }
 ```

---
EF Core version: 8.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 8.0
Operating system: Win 11
Visual Studio 2022 17.11.4

**Comment by KillerBoogie** [comment] 2024-09-25 14:25
For #34750 I tested with v9.0 rc1. The problem still exists with rc1.

**Comment by maumar** [comment] 2024-09-26 00:45
@KillerBoogie we need a full repro to effectively investigate this problem. It's not immediately obvious what's going on here. I tried to reverse-engineer the repro based on code you provided, but I was unsuccessful.

**Comment by KillerBoogie** [comment] 2024-09-26 14:24
@maumar : I stripped down the project. You can access it at https://github.com/KillerBoogie/ef-core-join-query-bug/tree/main

**Comment by KillerBoogie** [comment] 2024-09-30 15:02
@maumar: Have you been able to check the project?

**Comment by KillerBoogie** [comment] 2024-10-01 15:06
Since I can't continue with my project, I was searching for clues. I found a hint that due to `ownsMany` EF Core might eager load the collection in addition to the projection and that `.IgnoreAutoIncludes()` might help.

I tried it without `AsSplitQuery()`, but the generated query was still false.

```
 SELECT [l].[LocationId], [l].[Name], [s].[TId], [s].[DisplayOrder], [s].[FocusPointX], [s].[FocusPointY], [s].[ImageId], [s].[Language], [s].[LocationId], [s].[ScreenSize], [s].[ImageId0], [s].[Created], [s].[CreatedBy], [s].[CreatedInNameOf], [s].[Description], [s].[FileName], [s].[LastModified], [s].[LastModifiedBy], [s].[LastModifiedInNameOf], [s].[TId0], [s].[Uri], [s].[Version], [s].[MetaData_Height], [s].[MetaData_Size], [s].[MetaData_Width], [l].[Created], [l].[CreatedBy], [l].[CreatedInNameOf], [l].[LastModified], [l].[LastModifiedBy], [l].[LastModifiedInNameOf], [l].[TId], [l].[Version], [l].[Address_City], [l].[Address_CountryId], [l].[Address_CountryName], [l].[Address_DeliveryInstruction], [l].[Address_State], [l].[Address_Street], [l].[Address_StreetAffix], [l].[Address_StreetNumber], [l].[Address_ZipCode], [l1].[TId], [l1].[DisplayOrder], [l1].[FocusPointX], [l1].[FocusPointY], [l1].[ImageId], [l1].[Language], [l1].[LocationId], [l1].[ScreenSize]
 FROM [VC].[Location] AS [l]
 LEFT JOIN (
     SELECT [l0].[TId], [l0].[DisplayOrder], [l0].[FocusPointX], [l0].[FocusPointY], [l0].[ImageId], [l0].[Language], [l0].[LocationId], [l0].[ScreenSize], [i].[ImageId] AS [ImageId0], [i].[Created], [i].[CreatedBy], [i].[CreatedInNameOf], [i].[Description], [i].[FileName], [i].[LastModified], [i].[LastModifiedBy], [i].[LastModifiedInNameOf], [i].[TId] AS [TId0], [i].[Uri], [i].[Version], [i].[MetaData_Height], [i].[MetaData_Size], [i].[MetaData_Width]
     FROM [VC].[LocationCoverImage] AS [l0]
     INNER JOIN [VC].[Image] AS [i] ON [l0].[ImageId] = [i].[ImageId]
 ) AS [s] ON [l].[LocationId] = [s].[LocationId]
 LEFT JOIN [VC].[LocationCoverImage] AS [l1] ON [l].[LocationId] = [l1].[LocationId]
 ORDER BY [l].[LocationId], [s].[TId], [s].[ImageId0]
```
But, when I used it together as `IgnoreAutoIncludes().AsSplitQuery()` the created query looked better. It eliminated the extra wrong query, but it created an unnecessary sub query and pulled unnecessary fields from the image table.

My frustration with EF Core reaches a boiling limit.

```
SELECT [l].[LocationId], [l].[Name], [l].[Created], [l].[CreatedBy], [l].[CreatedInNameOf], [l].[LastModified], [l].[LastModifiedBy], [l].[LastModifiedInNameOf], [l].[TId], [l].[Version], [l].[Address_City], [l].[Address_CountryId], [l].[Address_CountryName], [l].[Address_DeliveryInstruction], [l].[Address_State], [l].[Address_Street], [l].[Address_StreetAffix], [l].[Address_StreetNumber], [l].[Address_ZipCode]
FROM [VC].[Location] AS [l]
ORDER BY [l].[LocationId]

 SELECT [s].[TId], [s].[DisplayOrder], [s].[FocusPointX], [s].[FocusPointY], [s].[ImageId], [s].[Language], [s].[LocationId], [s].[ScreenSize], [s].[ImageId0], [s].[Created], [s].[CreatedBy], [s].[CreatedInNameOf], [s].[Description], [s].[FileName], [s].[LastModified], [s].[LastModifiedBy], [s].[LastModifiedInNameOf], [s].[TId0], [s].[Uri], [s].[Version], [s].[MetaData_Height], [s].[MetaData_Size], [s].[MetaData_Width], [l].[LocationId]
 FROM [VC].[Location] AS [l]
 INNER JOIN (
     SELECT [l3].[TId], [l3].[DisplayOrder], [l3].[FocusPointX], [l3].[FocusPointY], [l3].[ImageId], [l3].[Language], [l3].[LocationId], [l3].[ScreenSize], [i0].[ImageId] AS [ImageId0], [i0].[Created], [i0].[CreatedBy], [i0].[CreatedInNameOf], [i0].[Description], [i0].[FileName], [i0].[LastModified], [i0].[LastModifiedBy], [i0].[LastModifiedInNameOf], [i0].[TId] AS [TId0], [i0].[Uri], [i0].[Version], [i0].[MetaData_Height], [i0].[MetaData_Size], [i0].[MetaData_Width]
     FROM [VC].[LocationCoverImage] AS [l3]
     INNER JOIN [VC].[Image] AS [i0] ON [l3].[ImageId] = [i0].[ImageId]
 ) AS [s] ON [l].[LocationId] = [s].[LocationId]
 ORDER BY [l].[LocationId]
```

**Comment by maumar** [comment] 2024-10-02 07:46
@KillerBoogie thanks for the repo, I'm able to access. I'm currently in the process of analyzing and simplifying the code. Unfortunately I can't clone a random repo from the internet and run it on my machine - I need to build things from scratch and that takes some time, as the project is quite complicated. I will post update once I have a (hopefully) failing minimal repro

**Comment by maumar** [comment] 2024-10-04 04:14
@KillerBoogie I'm able to reproduce this. Extra join is coming from `location.Address.MapToDto(),`

Location contains owned collection `CoverImages` (mapped to table `LocationCoverImage`, and it also contains complex property Address, which is being projected. Nav expansion is injecting include call for CoverImages (since it's eagerly loaded), even though the entity itself is not going to be projected (complex property alone is). 

Minimal repro:

```cs
    [ConditionalFact]
    public async Task ComplexTypeOwnedType()
    {
        using var ctx = new MyContext();
        await ctx.Database.EnsureDeletedAsync();
        await ctx.Database.EnsureCreatedAsync();

        var query = ctx.Entities.Select(x => x.Complex).ToList();
    }

    public class MyEntity
    {
        public int Id { get; set; }

        public List<MyOwned> OwnedCollection { get; set; }
        public MyComplex Complex { get; set; }
    }

    public class MyOwned
    {
        public string Name { get; set; }
    }

    public class MyComplex
    {
        public int Foo { get; set; }
        public decimal Bar { get; set; }
    }


    public class MyContext : DbContext
    {
        public DbSet<MyEntity> Entities { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MyEntity>(b =>
            {
                b.OwnsMany(x => x.OwnedCollection);
                b.ComplexProperty(x => x.Complex).IsRequired();
            });
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                    .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Repro;Trusted_Connection=True;MultipleActiveResultSets=true")
                    .LogTo(Console.WriteLine, LogLevel.Information)
                    .EnableSensitiveDataLogging();
        }
    }

```

**Comment by maumar** [comment] 2024-10-04 04:18
problem is in IncludeExpandingExpressionVisitor.VisitMember 

https://github.com/dotnet/efcore/blob/67254af14db19dbf17f04b0b3cae3881d09ccee0/src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs#L561

we block generation of includes if member is a primitive property but don't do the same for complex. 

We could do:

```cs
                var complex = entityType?.FindComplexProperty(memberExpression.Member);
                if (complex != null)
                {
                    return memberExpression;
                }
```

**Comment by KillerBoogie** [comment] 2024-10-04 15:27
Maurycy, thank you for your reply. Do I understand correctly, that this won't be fixed until version 10? If yes, does it mean the only options I have is to use OwnsOne instead of ComplexProperty or to use RawSQL with `For Json` on SQL Server?

**Comment by maumar** [comment] 2024-10-04 20:05
@KillerBoogie that's correct - we are closing down on EF 9 release, only fixing most critical issues at this point. This bug is not critical - it has perf implications as it brings more from the database than it should, but the data that is eventually presented to the user is correct (so no data corruption)

Using owned entities rather than complex types is a good solution if the extra join is a significant problem in your case. Unfortunately, `IgnoreAutoIncludes` doesn't work on owned types, that would have been a great solution.

**Comment by maumar** [comment] 2024-10-09 06:48
@KillerBoogie unfortunately EF Core release schedule has been decided way above our heads, as it's coordinated across entire .NET (see https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) FWIW, the issue is now fixed in the main branch so it will be available from the first preview of EF 10. Although I understand that most companies are reluctant to use previews.

**Comment by roji** [comment] 2024-10-09 10:42
To add to @maumar's comment, @KillerBoogie see the EF [release planning document](https://learn.microsoft.com/en-us/ef/core/what-is-new/release-planning). For important bugs that affect many users and where the fix is low-risk, we sometimes backport the fix to patches of released versions.

**Closed** 2024-10-20 06:31 UTC
Labels: type-bug, closed-fixed, customer-reported, area-query, area-complex-types
