### ISSUE TITLE
.Net 5 EF Core database create is much slower than .Net Core 3.1

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/efcore#23574] opened 2020-12-03 22:11 UTC
We are on the latest EF Core on .Net 5. We recently upgraded all of apps to .Net 5 from
EF Core 3.1. When we create a sample database on .Net 5 it takes about 10 mins. On 
.Net Core 3.1 it took about 2 to 3 minutes. Exactly why is EF Core on .Net 5 so much slower.
This is using Sql Server as DBM and standard .net sql client.

**Comment by ajcvickers** [comment] 2020-12-03 22:23
@dgxhubbard This issue is lacking enough information for us to be able to investigate. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by dgxhubbard** [comment] 2020-12-03 23:28
I wish I could I would be more than happy to the project is much to large.
I can get on a skype, zoom etc call.

**Comment by dgxhubbard** [comment] 2020-12-03 23:30
The best that I could do is create a small sample console app and run a db create under
net core 3.1 and .net 5

**Comment by roji** [comment] 2020-12-05 15:24
@dgxhubbard can you please check whether you're encountering the same slowness when just *building* the project (as opposed to when doing `dotnet ef database create`)? If so, this could be a dup of #23426/#23291.

Otherwise, a small sample project would be needed for us to investigate.

**Comment by dgxhubbard** [comment] 2020-12-06 02:40
VS is slower compiling. We are not using command line to create database.
Is this what you mean?

**Comment by dgxhubbard** [comment] 2020-12-06 02:48
I wont be able to create a sample for another week

**Comment by roji** [comment] 2020-12-06 17:32
@dgxhubbard if VS is indeed slower compiling, and this isn't specifically about database create, then as I wrote above this may simply be #23291. Can you confirm which version of VS you're using?

**Comment by dgxhubbard** [comment] 2020-12-06 23:51
I am using 16.8.1. I will update and try it

**Comment by dgxhubbard** [comment] 2020-12-07 17:57
I updated to 16.8.2, but that did not clear the problem up.
On .net 5 running sql server client the database create is 8 mins, on .net core 3.1 this used to be about 3 mins.
On .net 5 running Microsoft.Data.SqliteCore the database create is 12 mins and on .net core 3.1 it used to about 6 to 7 mins.

**Comment by roji** [comment] 2020-12-07 18:15
@dgxhubbard in that case I'm going to need some sort of runnable repro in order to investigate.

**Comment by dgxhubbard** [comment] 2020-12-07 20:51
Will do. Need a week to get to it

**Comment by dgxhubbard** [comment] 2020-12-08 18:22
I upgraded entity framework core from 5.0.0 to 5.0.1 and associated libraries.
This caused sqlserver create to go from 8 mins to 1 mine and sqlite cretate
to go from 12 mins to 5 1/2 mins.

**Comment by ErikEJ** [comment] 2020-12-08 18:56
@dgxhubbard I assume you also update VS to 16.8.3, which gave you .NET 5.0.1

**Comment by dgxhubbard** [comment] 2020-12-09 00:13
Yes I did as well as changing installers to use 5.0.1 runtime

**Comment by dgxhubbard** [comment] 2020-12-09 02:38
But I do have a question what is the TFM for .net 5.0.1 in my project files?

**Comment by roji** [comment] 2020-12-09 06:27
@dgxhubbard there is no TFM for .NET 5.0.1 - there is only the `net5.0` TFM. Patch versions of .NET Core are released without the creation of a new TFM - no public surface API changes are done.

EF Core 5.0.1 didn't contain any fixes related to build slowness etc. However, as @ErikEJ wrote above I'm assuming that along with EF you also upgraded your .NET SDK and/or Visual Studio, and that was the actual thing which fixed it.

**Comment by roji** [comment] 2020-12-09 06:28
Duplicate of #23291

**Closed** 2022-10-16 19:13 UTC
Labels: closed-duplicate, customer-reported
