### ISSUE TITLE
EF set temp ID's in DbContext.ChangeTracker.Entries() to int.MinValue + 1001

### ISSUE THREAD

**Issue by paule96** [dotnet/efcore#12159] opened 2018-05-28 18:15 UTC
This PR is releated to #10167 

> Describe what is not working as expected.

If a **new** entity is added to the changetracker , it's primary key gets a temp Id. This might destroy an applications business logik when using EF. Like in the [AutoHistory](https://github.com/Arch/AutoHistory) extension.

> If you are seeing an exception, include the full exceptions details (message and stack trace).

No exception trace because, this is a logical issue.

### Steps to reproduce

1. Create a new C# Project and add ef core models and context.
2. Use a MS - SQL Server (this is importent)
3. Write something like this:
```csharp
context.Add(new User("Elton", "John"));
var expectThatAllValuesAreNull = context.ChangeTracker.Entries().Select(e => 
   {
         var keyPropertyName = e.Metadata.FindPrimaryKey().FirstOrDefault().Name; 
// this must be null because the primary key is set in the database and can only have a value after saving.
         return e.Property(keyPropertyName).CurrentValue;
});
foreach(var result in expectThatAllValuesAreNull){
// This would output allways: "int.MinValue + 1001"
Console.WriteLine(result);
}
```

This example shows only the behaivor for ```Microsoft.EntityFrameworkCore.SqlServer``` provider. Other Providers have other problems ...

@ajcvickers please join the conversation because you hopefully can explain why the temp ID's exsists and how we can remove them...

**Comment by ajcvickers** [comment] 2018-06-05 16:00
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by paule96** [comment] 2018-07-12 16:37
Sorry I was very busy in the last time. But I see you start working on a solution. So I add the reference to this here:


#12378

**Closed** 2022-10-16 12:27 UTC
Labels: closed-could-not-reproduce, customer-reported
