### ISSUE TITLE
Code Generator doesn't emit '<auto-generated />' on files.

### ISSUE THREAD

**Issue by DRAirey1** [dotnet/efcore#17863] opened 2019-09-16 19:31 UTC
Build a project that includes and Entity Framework data model.
Go to the Package Manager Console
type 'add-migration InitialMigration'
two files are generated: **&lt;some long number&gt;_InitialMigration.cs** and **&lt;some long number&gt;_InitialMigration.Designer.cs**.  The designer file properly has the '&lt;autogenerated/&gt;' tag at the start and so the code analyzers skip those files.
The first file doesn't, and so the analyzers spit out copious messages when you have a migration in your project.  Please either fix your generated code so that it's compliance with best coding practices, or put the tag at the start of the file so the analyzers know to skip it.

**Comment by bricelam** [comment] 2019-09-17 17:01
Duplicate of #10203

What are the analyzer messages?

**Comment by DRAirey1** [comment] 2019-09-17 17:16
5>Migrations\20190915204946_InitialMigration.cs(1,1,1,14): warning SA1200: Using directive should appear within a namespace declaration
5>Migrations\20190915204946_InitialMigration.cs(2,1,2,48): warning SA1200: Using directive should appear within a namespace declaration
5>Migrations\20190915204946_InitialMigration.cs(6,26,6,42): warning SA1601: Partial elements should be documented
5>Migrations\20190915204946_InitialMigration.cs(1,1,1,1): warning SA1633: The file header is missing or not located at the top of the file.
5>Migrations\20190915204946_InitialMigration.cs(18,21,18,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(31,21,31,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(46,21,46,67): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(61,21,61,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(75,21,75,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(89,21,89,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(103,21,103,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(117,21,117,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(131,21,131,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(145,21,145,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(159,21,159,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(236,21,236,76): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(250,21,250,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(264,21,264,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(281,21,281,81): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(295,21,295,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(309,21,309,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(323,21,323,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(336,21,336,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(350,21,350,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(366,21,366,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(379,21,379,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(392,21,392,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(406,21,406,89): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(419,21,419,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(431,21,431,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(451,21,451,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(478,21,478,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(498,21,498,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(520,21,520,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(541,21,541,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(566,21,566,90): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(600,21,600,62): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(621,21,621,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(642,21,642,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(670,21,670,81): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(698,21,698,85): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(720,21,720,91): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(748,21,748,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(770,21,770,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(798,21,798,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(819,21,819,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(839,21,839,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(859,21,859,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(885,21,885,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(906,21,906,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(926,21,926,68): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(958,21,958,70): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(994,21,994,91): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1014,21,1014,72): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1041,21,1041,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1069,21,1069,101): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1101,21,1101,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1127,21,1127,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1149,21,1149,82): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1177,21,1177,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1204,21,1204,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1230,21,1230,72): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1263,21,1263,69): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1304,21,1304,73): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1380,21,1380,65): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1429,21,1429,74): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1506,21,1506,66): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1535,21,1535,66): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1563,21,1563,66): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1602,21,1602,72): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1680,21,1680,72): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1797,21,1797,72): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(1898,21,1898,93): warning SA1413: Use trailing comma in multi-line initializers
5>Migrations\20190915204946_InitialMigration.cs(2746,33,2746,37): warning SA1600: Elements should be documented
5>Migrations\20190915204946_InitialMigration.cs(2748,13,2748,29): warning CA1062: In externally visible method 'void InitialMigration.Down(MigrationBuilder migrationBuilder)', validate parameter 'migrationBuilder' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.
5>Migrations\20190915204946_InitialMigration.cs(8,33,8,35): warning SA1600: Elements should be documented
5>Migrations\20190915204946_InitialMigration.cs(10,13,10,29): warning CA1062: In externally visible method 'void InitialMigration.Up(MigrationBuilder migrationBuilder)', validate parameter 'migrationBuilder' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.

**Comment by smitpatel** [comment] 2019-09-20 17:31
Discuss with @ajcvickers

**Comment by smitpatel** [comment] 2019-09-20 18:47
Closing as duplicate of #10203

**Closed** 2022-10-16 14:42 UTC
Labels: closed-duplicate, customer-reported
