### ISSUE TITLE
DbContext.AddRange under Xamarin/iOS with derived entity classes

### ISSUE THREAD

**Issue by rob2212** [dotnet/efcore#10206] opened 2017-11-02 15:13 UTC
I'm using the EF core 2.0 framework within a .NET Standard 2.0 assembly in different projects.

I've a simple inheritance entity structure with an abstract base class 'NavigableElement' and some derived classes e.g. a 'Folder' class. In my db context I've declared a  DbSet using my base class.

`public DbSet<NavigableElement> Elements { get; set; }`

I've registered all my derived classes according to the documentation.

`protected override void OnModelCreating(ModelBuilder modelBuilder)
{
			modelBuilder.Entity<FrameworkElement>();
			modelBuilder.Entity<Folder>();
			modelBuilder.Entity<FrameworkType>();
			modelBuilder.Entity<CustomElement>();	
}`

If I have written some code to fill my database using the AddRange method of the DbSet. The code works fine with a .NET core as well as a full .NET framework console application. It also works with the iPhone simulator. But AddRange throws an exception when I run the code on a real iPhone via Visual Studio 2017 debugger. It does not matter if a pass a specific collection of elements or a List of base type to AddRange.

```
Folder f = new Folder();
List<NavigableElement> list = new List<NavigableElement>();
list.Add(f);

context.Elements.AddRange(f);
```
 
```
Folder f = new Folder();
List<Folder> list = new List<Folder>();
list.Add(f);

context.Elements.AddRange(f);
```

```
Exception message: Attempting to JIT compile method '(wrapper runtime-invoke) <Module>:runtime_invoke_void__this___int_object_object_object_Nullable`1<int>_object_Guid_Nullable`1<int>_object_Guid (object,intptr,intptr,intptr)' while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.

Stack trace:   at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:661 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151 
  at System.Linq.Expressions.Interpreter.ExceptionHelpers.UnwrapAndRethrow (System.Reflection.TargetInvocationException exception) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/Utilities.cs:174 
  at System.Linq.Expressions.Interpreter.NewInstruction.Run (System.Linq.Expressions.Interpreter.InterpretedFrame frame) [0x00026] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/NewInstruction.cs:39 
  at System.Linq.Expressions.Interpreter.Interpreter.Run (System.Linq.Expressions.Interpreter.InterpretedFrame frame) [0x00015] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/Interpreter.cs:63 
  at System.Linq.Expressions.Interpreter.LightLambda.Run1[T0,TRet] (T0 arg0) [0x0001c] in <773264786149499a986a13db6a7d46fe>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry+OriginalValues..ctor (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry) [0x0000c] in <0998bf911f014e7884d2695c95a67016>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.EnsureOriginalValues () [0x0000d] in <0998bf911f014e7884d2695c95a67016>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry) [0x0000f] in <0998bf911f014e7884d2695c95a67016>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry) [0x0008f] in <0998bf911f014e7884d2695c95a67016>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState (Microsoft.EntityFrameworkCore.EntityState oldState, Microsoft.EntityFrameworkCore.EntityState newState, System.Boolean acceptChanges) [0x00141] in <0998bf911f014e7884d2695c95a67016>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState (Microsoft.EntityFrameworkCore.EntityState entityState, System.Boolean acceptChanges, System.Boolean forceStateWhenUnknownKey) [0x00034] in <0998bf911f014e7884d2695c95a67016>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction (Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntryGraphNode node) [0x00024] in <0998bf911f014e7884d2695c95a67016>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph (Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntryGraphNode node, System.Func`2[T,TResult] handleNode) [0x00000] in <0998bf911f014e7884d2695c95a67016>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry rootEntry, Microsoft.EntityFrameworkCore.EntityState entityState, System.Boolean forceStateWhenUnknownKey) [0x00020] in <0998bf911f014e7884d2695c95a67016>:0 
  at Microsoft.EntityFrameworkCore.DbContext.SetEntityState (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry, Microsoft.EntityFrameworkCore.EntityState entityState) [0x00013] in <0998bf911f014e7884d2695c95a67016>:0 
  at Microsoft.EntityFrameworkCore.DbContext.SetEntityStates (System.Collections.Generic.IEnumerable`1[T] entities, Microsoft.EntityFrameworkCore.EntityState entityState) [0x00024] in <0998bf911f014e7884d2695c95a67016>:0 
  at Microsoft.EntityFrameworkCore.DbContext.AddRange (System.Collections.Generic.IEnumerable`1[T] entities) [0x00012] in <0998bf911f014e7884d2695c95a67016>:0 
  at Microsoft.EntityFrameworkCore.DbContext.AddRange (System.Object[] entities) [0x00006] in <0998bf911f014e7884d2695c95a67016>:0 
  at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1[TEntity].AddRange (TEntity[] entities) [0x00000] in <0998bf911f014e7884d2695c95a67016>:0 
  at Erdmann.FW.LocationDatabase.DatabaseContentBuilder.Run (Erdmann.FW.LocationDatabase.LocationDbContext context) [0x00028] in E:\IRISSYS\Source\OP-Tools\Erdmann\Erdmann.FW.LocationDatabase\Erdmann.FW.LocationDatabase\DatabaseContentBuilder.cs:33 
  at Erdmann.FW.LocationDatabase.DatabaseManager.FillDatabase (Erdmann.FW.LocationDatabase.DataSources.IDataSource source) [0x0002a] in E:\IRISSYS\Source\OP-Tools\Erdmann\Erdmann.FW.LocationDatabase\Erdmann.FW.LocationDatabase\DatabaseManager.cs:64 
  at TestApp.MainViewModel.Run () [0x00049] in E:\IRISSYS\Source\OP-Tools\Erdmann\Erdmann.FW.LocationDatabase\TestApp\TestApp.Shared\MainViewModel.cs:56 
```

### Further technical details
EF Core version: v2.0.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 / iOS11.1
IDE: Visual Studio 2017 (v.15.4.1)

**Comment by rob2212** [comment] 2017-11-02 17:01
Maybe it helps how the entities look like:

```
public abstract class NavigableElement
    {
		[Key]
		public int StorageId { get; set; }
		public Guid ObjectId { get; set; }
		public Guid TypeId { get; set; }
		public String Name { get; set; }
		public String Comment { get; set; }
		public String FromKm { get; set; }
		public String ToKm { get; set; }
		public Image Image { get; set; }

		public int? ParentId { get; set; }
		[ForeignKey("ParentId")]		
		public NavigableElement Parent { get; set; }

		[InverseProperty("Parent")]
		public List<NavigableElement> Children { get; set; }

		public ExtendedData Data { get; set; }		

		public NavigableElement()
		{
			this.Children = new List<NavigableElement>();
		}
	}
```

```
public class ExtendedData
    {
		[Key]
		public int StorageId { get; set; }
		public String Blob { get; set; }

		public ExtendedData()
		{			
		}
	}
```

```
public class Folder : NavigableElement
    {
    }
```

**Comment by rob2212** [comment] 2017-11-03 11:07
I did some more investigations. I don't think the primary issue is inheritance, but the number of properties in my NavigtableElemenet class.

If I create a plain entity without inheritance, the exceptions stops comming with a certain number of properties.

Works:
```
public class TestElement
	{
		[Key]
		public int StorageId { get; set; }
		public Guid ObjectId { get; set; }
		public Guid TypeId { get; set; }
		public String Name { get; set; }
		//public String Comment { get; set; }
		//public String FromKm { get; set; }
		//public String ToKm { get; set; }
		//public Image Image { get; set; }

		//public int? ParentId { get; set; }
		//[ForeignKey("ParentId")]		
		//public TestElement Parent { get; set; }

		//[InverseProperty("Parent")]
		//public List<TestElement> Children { get; set; }

		//public ExtendedData Data { get; set; }		

		public TestElement()
		{
			//this.Children = new List<TestElement>();			
		}
	}
```

Does not work:
```
public class TestElement
	{
		[Key]
		public int StorageId { get; set; }
		public Guid ObjectId { get; set; }
		public Guid TypeId { get; set; }
		public String Name { get; set; }
		public String Comment { get; set; }
		//public String FromKm { get; set; }
		//public String ToKm { get; set; }
		//public Image Image { get; set; }

		//public int? ParentId { get; set; }
		//[ForeignKey("ParentId")]		
		//public TestElement Parent { get; set; }

		//[InverseProperty("Parent")]
		//public List<TestElement> Children { get; set; }

		//public ExtendedData Data { get; set; }		

		public TestElement()
		{
			//this.Children = new List<TestElement>();			
		}
	}
```
Is it related to: 
[https://bugzilla.xamarin.com/show_bug.cgi?id=58424](https://bugzilla.xamarin.com/show_bug.cgi?id=58424)

Any workarounds?

**Comment by ajcvickers** [comment] 2017-11-03 15:42
@rob2212 Looks like a duplicate of #9249, which is an external issue in mono that is being fixed by then. /cc @divega who has been tracking this.

**Comment by divega** [comment] 2017-11-03 21:18
@rob2212 that Xamarin issue was resolved as duplicate of https://bugzilla.xamarin.com/show_bug.cgi?id=59184 some time ago, and the latter was fixed last week. 

The fix is currently in the mono:2017-10 branch, which means [it will be included in Mono 5.8](http://www.mono-project.com/docs/about-mono/versioning/#mono-source-versioning). I am not sure what version of Xamarin.iOS will be based in Mono 5.8, but the [latest as of now is based on 5.4](https://developer.xamarin.com/releases/ios/xamarin.ios_11/xamarin.ios_11.4/). 

Perhaps @marek-safar can help us get an ETA, which would also be helpful for us to validate the fix.

**Comment by divega** [comment] 2017-11-03 21:24
@rob2212 to your specific question, I don't think there is any ideal workaround but what we saw is that the issue is sensitive to:

- the number of properties in the entity
- the types of the properties (including nullability)
- the processor architecture (ARM64 vs. 32 bits have different limits)

(See https://github.com/aspnet/EntityFrameworkCore/issues/9249#issuecomment-332686413 for a thorough test)

So, if it is possible for you to refactor your model to satisfy the limitations, that could be a workaround.

**Comment by marek-safar** [comment] 2017-11-04 04:19
@rob2212 2017-10 is pretty fresh branch and it should be included in what we call internally dev15-6 Xamarin rollout which is next XI version after 11.4

**Comment by rob2212** [comment] 2017-11-04 06:50
Thanks for the clarification. Have you a rough ETA? Is still this year? This is production blocking for our product and I need to know if we have to look for another approach to implement our database accces

**Comment by marek-safar** [comment] 2017-11-04 14:14
Right now this is not scheduled for releasing this year

**Closed** 2022-10-16 11:56 UTC
Labels: closed-duplicate
