### ISSUE TITLE
Using EF Core 7 in net6 project

### ISSUE THREAD

**Issue by phatcher** [dotnet/efcore#30085] opened 2023-01-17 21:19 UTC
Although you are publishing EF Core 7 with net6.0 support, the rest of the ecosystem doesn't want to play ball.

For example, in an ASP.NET project the health check system gives up and [gives a 500 error](https://github.com/dotnet/aspnetcore/issues/45278). I'd like to have the performance boost of EF 7, but it seems impossible to use without upgrading my app to net7.

Couple of suggestions...

1. Conditional compilation in a patch of EF 7 so that the dependencies for net6 are the 6.x versions e.g. Microsoft.Extensions.Configuration.Abstractions
1. Strong warnings that you might not be able to adopt EF 7 in a net6 app

I understand that effort might mean that the patch might not be possible, but the warning at least might save someone a day or two of frustration ;-)

EF Core version: 7.x
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  net6.0

**Comment by ajcvickers** [comment] 2023-01-17 21:27
You should be able to use the ASP.NET Core 6.0 Health Checks package in an ASP.NET Core 6.0 app but with EF Core 7.0 packages. (Note this is very different from using the 7.0 Health checks package, which will not work in an ASP.NET Corte 6.0 application.) If this isn't working, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by phatcher** [comment] 2023-01-17 23:19
Thanks will do

**Comment by ajcvickers** [comment] 2023-02-01 20:13
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-02-01 20:13 UTC
Labels: customer-reported
