### ISSUE TITLE
Support to DbCompiledModel and Multi tenancy 

### ISSUE THREAD

**Issue by ste4net** [dotnet/efcore#4410] opened 2016-01-27 10:55 UTC
Trying to port an MVC+EF5 web app to EF7 i realize that it is no more possible to instantiate a new Context passing a compiled model (DbComiledModel).
It was usefull (for us) for multi tenancy purpose.
This is an app with table dedicate to each tenant and tables (like asp identity tables) shared between all tenants.
Ex (codefirst mapping):

``` cs
[...]
private static DbCompiledModel GetCompiled(DbConnection connection, string tenantSchema)
{
  builder.Entity<UserCompany>();
  builder.Entity<Invoice>().ToTable("Invoices", tenantSchema);
}
[...]
private static ConcurrentDictionary<string, DbCompiledModel> modelCache = new ConcurrentDictionary<string, DbCompiledModel>();
public static MyContext Create(string tenantSchema, DbConnection connection)
{
  DbCompiledModel compiledModel;
  if (tenantSchema == null || tenantSchema.Trim().Length == 0) tenantSchema = "/";
  compiledModel = modelCache.GetOrAdd(tenantSchema, (t) => GetCompiled(connection, t));
  return new MyContext(connection, compiledModel) { TenantSchema = tenantSchema };
}
[...]
```

Every time a new tenant is requested (depending by the user)  Dbcontext is re-compiled for the new tenant and:
1-DbCompiledModel is saved in a ConcurrentDictionary to be used for next requests (for the same tenant)
2-DbContext saved in HttpRequest items to be used in from the same request.

This can be done using DbCompiledModel from EF5 because with this it is possible to cache the copiled model without using the EF5 caching system that can't be used due the presence of multi-tenancy/schema.

Maybe there is a better way do to this job in EF7 but i didn't found yet and i didn't found an alternative to DbCompiledModel.

**Comment by smitpatel** [comment] 2016-01-27 16:43
dupe of #1906 ?

**Comment by rowanmiller** [comment] 2016-01-27 18:02
You can do this already, here is what the code looks like

```c#
        private static IModel GetCompiled(DbConnection connection, string tenantSchema)
        {
            var builder = new ModelBuilder();
            builder.Entity<UserCompany>();
            builder.Entity<Invoice>().ToTable("Invoices", tenantSchema);
            return builder.Model;
        }
```

```c#
        private static ConcurrentDictionary<string, IModel> modelCache = new ConcurrentDictionary<string, IModel>();
        public static MyContext Create(string tenantSchema, DbConnection connection)
        {
            IModel compiledModel;
            if (tenantSchema == null || tenantSchema.Trim().Length == 0) tenantSchema = "/";
            compiledModel = modelCache.GetOrAdd(tenantSchema, (t) => GetCompiled(connection, t));

            var optionsBuilder = new DbContextOptionsBuilder<MyContext>();
            optionsBuilder.UseSqlServer(connection);
            optionsBuilder.UseModel(compiledModel);

            return new MyContext(optionsBuilder.Options) { TenantSchema = tenantSchema };
        }
```

You would not override OnConfiguring or OnModelCreating in the context, since all the config/model is done externally.

```c#
    public class MyContext : DbContext
    {
        public MyContext(DbContextOptions<MyContext> options)
            : base(options)
        { }

        ...
    }
```

**Comment by ste4net** [comment] 2016-01-27 18:27
Thank you very much.
So if I understood.
IModel is in fact the "compiled" model, all the heavy operations  (mapping/binding) has been already done (at builder.Model call point) and results saved for next use.
If I am not wrong your updated code should be useful also for another type of multi-tenancy application; when we need different DB for each tenant.
Thank you very much.

**Comment by rowanmiller** [comment] 2016-01-27 20:10
@ste4net yes `IModel` is the same concept as `DbCompiledModel`. And yes, it works well for using the same model to connect to different databases too.

**Comment by rowanmiller** [comment] 2016-01-27 20:11
Closing this out as I think we have answered your question now.

**Comment by ste4net** [comment] 2016-01-29 11:13
Yes. You have answered. Thank you.
Now I have to understand what's the best way to intercept the Context creation with DI .
Looking the source code it's doesn't seems to be the right choice to use the default extension methods AddEntityFramework().AddDbContext because AddDbContext create a singleton instances of  DbContextOptions and DbContextOptions Of T that is not what I need for this use case.
Maybe this should be enough to remove AddDbContext adding a scoped instance with custom activator.
```cs
             services.AddEntityFramework().AddSqlServer();
            services.AddScoped<ApplicationDbContext>(MyCtxCreator.CreateForUserTenant);
```

**Comment by ste4net** [comment] 2016-01-29 11:15
Yes. You have answered. Thank you.
 Now I have to understand what's the best way to intercept the Context creation with DI .
 Looking the source code it's doesn't seems to be the right choice to use the default extension methods AddEntityFramework().AddDbContext because AddDbContext create a singleton instances of DbContextOptions and DbContextOptions Of T that is not what I need for this use case.
 Maybe this should be enough to remove AddDbContext adding a scoped instance with custom activator.

           services.AddEntityFramework().AddSqlServer();
           services.AddScoped<MyContext>(MyCtxCreator.CreateForUserTenant);

**Comment by rowanmiller** [comment] 2016-01-29 17:18
@ste4net yes that is what you should do (it's essentially what AddDbContext does under the covers).

**Comment by unlimitedcoders** [comment] 2016-01-30 20:39
I tried the above sample but it is not creating any tables when I am running context.Database.Migrate or EnsureCreated.

**Comment by rowanmiller** [comment] 2016-02-01 17:39
@unlimitedcoders can you open a new issue and include your complete code listing so that we can see what it going wrong (BTW `Migrate` wouldn't work unless you have migrations for the context in your project... but EnsureCreated should work)

**Comment by ste4net** [comment] 2016-02-17 11:53
This is just to complete the thread (hope it could be usefull for others). 
Does not exist a parameterless constructor for ModelBuilder anyway i would like to use sql server conventions ( #3909 ) and i have to use the asp.net identity too. 
So... this is the code i am writing sure it could be improved...

Note: I know there will be problem with Migrations but i create a specific post for that (#4583) .

```cs

 public class MyContextFactory : IDbContextFactory<ApplicationDbContext>
    {
        public ApplicationDbContext Create()
        {
	    // THIS IS FOR MIGRATION ONLY
            string connection = GetConnectionStringHere();
            return CreateForTenant("Tenant_Code", connection);
        }
        public static ApplicationDbContext CreateForTenant(IServiceProvider srvProv)
        {
	    //THIS IS THE METHOD CONFIGURED IN STARTUP
            ITenantProvider TntProv = srvProv.GetService<ITenantProvider>();
            string connection = GetConnectionStringHere();
            string currtenant = TntProv.GetCurrentTenant(); // <<<< GET TENANT CODE FROM SESSION/CACHE;
            return CreateForTenant(currtenant, connection);
        }
        private static ApplicationDbContext CreateForTenant(string TenantCode, string connection)
        {
            return ApplicationDbContext.Create(TenantCode, connection);
        }
    }
[...]

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser, IdentityRole, string>
    {
        public string TenantSchema { get; set; }
        public ApplicationDbContext(DbContextOptions options) : base(options) { }
        private ApplicationDbContext() : base() { }
        private static IModel GetCompiled(string tenantSchema)
        {
            //https://github.com/aspnet/EntityFramework/issues/3909
            var serviceCollection = new ServiceCollection();
            serviceCollection.AddEntityFramework().AddSqlServer();
            var serviceProvider = serviceCollection.BuildServiceProvider();
            var coreConventionSetBuilder = new CoreConventionSetBuilder();
            var sqlConventionSetBuilder = new SqlServerConventionSetBuilder(new SqlServerTypeMapper());
            var conventionSet = sqlConventionSetBuilder.AddConventions(coreConventionSetBuilder.CreateConventionSet());

            var builder = new ModelBuilder(conventionSet);
            builder.Entity<UserCompany>();
	    //Cal Manually OnModelCreating from base class to create model objects relatet di Asp.Net identity (not nice)
            (new ApplicationDbContext()).OnModelCreating(builder);  
            builder.Entity<Invoice>().ToTable("Invoices", tenantSchema);

            return builder.Model;
        }

        private static ConcurrentDictionary<string, IModel> modelCache = new ConcurrentDictionary<string, IModel>();

   	private static ApplicationDbContext Create(string tenantSchema, string connectionstring)
        {

            IModel compiledModel;
            if (tenantSchema == null || tenantSchema.Trim().Length == 0) tenantSchema = "/";
            compiledModel = modelCache.GetOrAdd(tenantSchema, (t) => GetCompiled(t));

            var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();

            optionsBuilder.UseSqlServer(connectionstring);
            optionsBuilder.UseModel(compiledModel);

            return new ApplicationDbContext(optionsBuilder.Options) { TenantSchema = tenantSchema };
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }
    }

```

**Comment by sadjadbp** [comment] 2018-05-12 00:45
This won't work any more with EF Core 2.1

**Comment by divega** [comment] 2018-05-12 01:31
@sadjadbp could clarify exactly what does not work and how it fails? Ideally please create a new issue including a repro.

**Comment by sadjadbp** [comment] 2018-05-12 03:18
@divega cannot have one compiled model to connect to many DBs. Same issue that was discussed here, but the resolution won't work on 2.1 anymore. Actually this solution won't work on EF Core 2.0; I had to make a bit of modification to use SqlConventionsetBuilder.Build but that stopped working in 2.1.

**Comment by sadjadbp** [comment] 2018-05-12 07:30
What I'm looking for is same Compiled model different connection strings. I have a DB per tenant (elastic DB) but don't want to wait for model to be compiled per tenant request (or at least their request). What I ended up doing is inside OnConfiguring set the model that was created via previous call to OnModelBinding.

If you know an issue like this I'll link my question over there otherwise I'll create a new one (unless the answer is obvious)

**Comment by divega** [comment] 2018-05-12 18:30
@sadjadbp I believe if you just create the model normally in OnModelCreating and pass a different connection string to UseSqlServer for each tenant (either in OnConfiguring or passing a delegate that does this in AddDbContext) you should automatically get what you need.

Cc @ajcvickers in case he knows of any caveats with sharing the service container when the connection string changes.

**Comment by ajcvickers** [comment] 2018-05-14 18:55
@sadjadbp @divega The connection string does not influence the cache key, so it is normal and expected that multiple connections to different databases will share the same model, so long as they are using the same database provider. For a given provider, the only thing that influences the model cache by default is the DbContext type.

**Comment by ste4net** [comment] 2018-06-03 14:52
I was successfully using this approach with 2.0 . <br/>
Indeed there are issues now with 2.1 Calling _base.OnModelCreating(builder);_
there is an error with internal service provider.
I am studying the new 2.1 source code to understand what are services needed any suggestion will be really appreciated.

<br/>
CallStack<br/>
```
 at MyTestContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) 
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityUserContext`5.GetStoreOptions()
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityUserContext`5.OnModelCreating(ModelBuilder builder)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityDbContext`8.OnModelCreating(ModelBuilder builder)
   at MyTestContext.CustomCreateModel(String tenantSchema, ModelBuilder builder, Boolean sharedOnly)

```

**Comment by ste4net** [comment] 2018-06-06 10:05
@divega I confirm that this approach can't work anymore starting from 2.1
<br/>
During my tests i see that inheriting from IdentityDbContext you can't just use the OnModelCreating method to manually create the model outside the dbContext class.
<br/>
It needs services and a serviceProvider not just a modelBuilder as parameter.
<br/><br/>
But… reading source code i see that EFCore already use exactly the same approach (**_ConcurrentDictionary_**) to cache the "compiled" model ( **_IModel_** ). 
<br/>Searching a way to use the existing method i found that cache key is provided by **_IModelCacheKeyFactory_** that normally consider equals all **_IModel_** produced by the same DbContext you just have to make a custom key based on tenant.
<br/><br/>
This post from @bricelam saved me a lot of time. 
https://stackoverflow.com/questions/41979215/how-to-implement-imodelcachekeyfactory-in-ef-core
<br/>
Works perfectly with 2.1 too.

**Closed** 2022-10-16 09:26 UTC
