### ISSUE TITLE
Windows Identity User Impersonation adds ~1.3s overhead on each query

### ISSUE THREAD

**Issue by The-MAZZTer** [dotnet/efcore#10143] opened 2017-10-23 20:33 UTC
When making any query (eg db.Table.Any() is enough), query overheads are 1.3s. It's 100% consistent for me. Code running outside of the impersonation sees normal query times.

### Steps to reproduce

Unfortunately this was code for my employer so I can't really provide a good sample. Plus you need a whole database schema. But I can give you the pseudocode:

```c#
// Get user's token from an IIS request first
WindowsIdentity.RunImpersonated(userToken, () => {
    using (SomeDbContext db = new SomeDbContext()) {
        db.SomeTable.Any(); // Takes 1.3s
    }
});
```

```c#
using (SomeDbContext db = new SomeDbContext()) {
    db.SomeTable.Any(); // Takes normal query time.
}
```

If more is needed I can make something when I am not on my employer's time.

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows Server 2012 R2
IDE: VS2017 15.3.5

(I know my VS is out of date, I do not have admin rights on all my work PCs and I want to keep the versions in sync.)

Problem was observed using remote debugging (but also was easy enough to see when not debugging due to the long delays).
Problem was observed with both release and debug builds.

The 1.3s overhead is not due to impersonation itself. Impersonation is only taking <1ms in my tests.

My workaround is to use WindowsIdentity.RunImpersonated with the original token from the user account used to run the process (eg call WindowsIdentity.GetCurrent() on process start and save this reference to pass in later).

**Comment by ajcvickers** [comment] 2017-10-25 19:30
@danmosemsft @bartonjs We can investigate this from the EF side, but we wanted to check first whether there is something in WindowsIdentity that would explain what is happening. Are you guys the right people to ask, and if not do you know who we can loop in with WindowsIdentity experience?

**Comment by karelz** [comment] 2017-10-25 21:02
@brentschmaltz that seems like in your area (WindowsIdentity) - did you see anything like that before?

@The-MAZZTer without a repro it will be very hard to root cause.
Did you run it on .NET Core or on .NET Framework?
Is it something you can isolate into a small repro on your side?
Does it happen only under load or also when there is nothing else running?
Does it repro only against production database, or even empty toy database?

Would you be able to collect ETL traces of the delay? (e.g. via [PerfView](https://www.microsoft.com/en-us/download/details.aspx?id=28567) + see [tutorials](https://channel9.msdn.com/Series/PerfView-Tutorial)) If you could then share a callstack (potentially anonymized / shortened), we may be able to find out what is happening.

**Comment by The-MAZZTer** [comment] 2017-10-25 23:10
.NET Core 2.0, did not test in .NET Framework.

There was nothing else in particular happening, and I confirmed my workaround does in fact fix it with no other changes to my application. Application was not under load, it was only handling a single web request wherein a single database query was taking place.

I had initially deleted and recreated the database (very little data in it, 3-5 rows per table max) as part of my debugging, with no change in query time,.

And again, when I applied my workaround, the query time dropped to expected levels.

Due to IT policy I cannot install non-approved software. I will try and see if I can create a small repro case from scratch at home, however.

**Comment by karelz** [comment] 2017-10-25 23:36
Thanks that's useful information - something is truly wrong here. If you can recreate a simple standalone repro, that would be great help! Thank you!

**Comment by The-MAZZTer** [comment] 2017-10-26 00:41
Unfortunately I cannot reproduce on my home PC. When impersonating another user I get an error when attempting a database query, which I was not getting at work:

Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 14: 'unable to open database file'.'

The ACLs are set properly on the file to allow the user access. Interestingly, I have never seen this problem at work when doing database operations while impersonating a user.

**Comment by karelz** [comment] 2017-10-26 16:31
So what is different in your work environment that you can do impersonation without the above error?

**Comment by The-MAZZTer** [comment] 2017-10-26 23:10
I have no idea. There's plenty of differences I may not be able to account for. For example off the top of my head:

Work environment:
- Multiple Active Directory Domains (though both the user the application is running under as well as the impersonated user are from the same AD domain)
- Windows Server 2012 R2
- IIS
- Application and data running off of secondary drive

Home environment
- No Active Directory
- Windows 10 FCU
- IIS Express
- Application and data running off of Windows drive (with normal ACLs in place... though granting Full Control to Everyone to my user profile, where the project is running from, didn't help).

I suppose the delay could be some weird AD query timeout or something.

**Comment by brentschmaltz** [comment] 2017-10-27 17:51
@The-MAZZTer your loop about shows impersonation with every access. What happens if you impersonate then make multiple calls? (apologies if this was answered above, skipped some text :-) )

**Comment by karelz** [comment] 2017-10-27 19:30
@The-MAZZTer so what happens when you run your isolated repro you tried at home in the work environment? Are you able to reproduce it there?

In nutshell: To make further progress, we need you to find a minimal repro in some environment (e.g. at work). Then we can attempt to repeat same repro in other environments where we can do proper perf analysis. Or we can give you steps how to analyze the perf using tools available to you in your lockdown environment.

**Comment by The-MAZZTer** [comment] 2017-10-27 22:53
@brentschmaltz Each query was producing a 1.3s overhead even if I did multiple queries while impersonated without calling .RunImperonated again.. Sorry if that was not clear.

**Comment by The-MAZZTer** [comment] 2017-10-30 15:28
My minimal repro case is working at work. Here's the code:

https://github.com/The-MAZZTer/WindowsIdentityEFCoreSlowdown

**Comment by karelz** [comment] 2017-10-30 15:59
Great! Can you try to investigate perf of the minimal repro? If you can't use PerfView, try VisualStudio to find out where the time is spent (e.g. blocked time callstack). That might help @brentschmaltz to dig deeper.

**Comment by The-MAZZTer** [comment] 2017-10-30 16:18
I suspect the difference is the presence of Active Directory. That is not something I think I could really test, though.

I should probably take a break from this for a bit but I will try to directly use Microsoft.Data.Sqlite (IIRC EFC uses this internally) in my repro case to see if I see the same delay. Then I guess I could also try System.Data.SQLite (from the SQLite team) as well. That could help isolate the issue.

But for now I think I will try stepping through my test code to see if I can get info about where the time is being spent as you requested. I think last time I tried I could not get any deeper than my own code (but Just My Code may have been on).

**Comment by ajcvickers** [comment] 2017-11-09 01:58
@The-MAZZTer Any updates on this from your side?

**Comment by The-MAZZTer** [comment] 2017-11-10 13:10
Sorry been busy with life, haven't had time to work on this.

**Comment by ajcvickers** [comment] 2017-11-10 19:00
@The-MAZZTer I'm going to close this for now since we are unable to repro what you are seeing and you don't currently have time to do further investigation. Please feel free to open a new issue if you are able to get back to this. I would suggest filing it on https://github.com/dotnet/corefx rather than here unless it is root-caused to something EF specific.

**Closed** 2022-10-16 11:55 UTC
Labels: closed-could-not-reproduce
