### ISSUE TITLE
Script generation requires connectionString

### ISSUE THREAD

**Issue by severisv** [dotnet/efcore#13107] opened 2018-08-24 07:59 UTC
Running `dotnet ef migrations script` without a connectionstring causes it to fail: "The string argument 'connectionString' cannot be empty."

Running the command without a connectionstring on present is not uncommon on build servers.

Adding a dummy connectionString causes it not to fail.

### Steps to reproduce
Run dotnet ef migrations script on any EF Core project.

**Comment by bricelam** [comment] 2018-08-24 15:58
Possible duplicate of #9244

**Comment by ajcvickers** [comment] 2018-08-29 21:31
This is covered by the work in #9244, #8494, and #8427

**Closed** 2022-10-16 13:27 UTC
Labels: closed-duplicate, customer-reported
