### ISSUE TITLE
Derived entity returns wrong number of items when combined with select

### ISSUE THREAD

**Issue by AndreVianna** [dotnet/efcore#4545] opened 2016-02-12 16:00 UTC
Here is a sample scenario:

```
public class Place
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class Home : Place {
    public string Address { get; set; }
}

public class SomeDbContext : IdentityDbContext<SomeUser>
{
    public DbSet<Place> Places { get; set; }
    public DbSet<Home> Homes { get; set; }
    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        builder.Entity<Place>().HasDiscriminator<string>("Type").HasValue<Place>("Place").HasValue<Home>("Home");
    }
}

public static partial class SampleData
{
    public static void Initialize(IServiceProvider serviceProvider) {
        var context = serviceProvider.GetService<SomeDbContext>();
        context.Database.Migrate();
        if (!context.Places.Any()) {
            context.Places.AddRange(
                new Place { Name = "Place 1" },
                new Place { Name = "Place 2" },
                new Place { Name = "Place 3" },
                new Place { Name = "Place 4" },
                new Place { Name = "Place 5" }
            );
            context.SaveChanges();
        }
        if (!context.Homes.Any()) {
            context.Homes.AddRange(
                new Home { Name = "Home 1", Address = "Address 1" },
                new Home { Name = "Home 2", Address = "Address 2" },
                new Home { Name = "Home 3", Address = "Address 3" },
                new Home { Name = "Home 4", Address = "Address 4" },
                new Home { Name = "Home 5", Address = "Address 5" }
            );
            context.SaveChanges();
        }
}
```

Here are the test cases with the expected values and results

```
var test1 = context.Places.ToArray(); // Expected 10 records -> Result 10 ==> OK
var test2 = context.Homes.ToArray(); // Expected 5 records -> Result 5 ==> OK
var test3 = context.Homes.Select(c => c.Name).ToArray();  // Expected 5 records -> Result 10 ==> Error!!!
//Ugly workaround
var test4 = context.Places.OfType<Home>().Select(c => c.Name).ToArray();  // Expected 5 records -> Result 5 ==> OK

```

Here is my environment:

```
{
  "version": "1.0.0-*",
  "description": "ErrorSample Class Library",
  "authors": [ "Andre Vianna" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.DependencyInjection": "1.0.0-rc1-final"
  },

  "commands": {
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Threading": "4.0.11-beta-23516",
      }
    }
  }

}

```

**Comment by rowanmiller** [comment] 2016-02-12 17:50
Duplicate of https://github.com/aspnet/EntityFramework/issues/4412

**Closed** 2022-10-16 09:29 UTC
