### ISSUE TITLE
The value for foreign key is not returned!

### ISSUE THREAD

**Issue by MasHero7** [dotnet/efcore#13990] opened 2018-11-21 07:32 UTC
Hi all,
I've applied all steps at this link for my existing DB:
https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db
My database contains a lot of tables with foreign keys relations. But when I run the web pages like 'edit' for example the page returned the value of the code not the related foreign key value like this:
https://i.imgur.com/tGdM1m3.png
Why? and How to slove please?

**Comment by ajcvickers** [comment] 2018-12-03 18:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:40 UTC
Labels: closed-could-not-reproduce, customer-reported
