### ISSUE TITLE
Custom Sql exceptions for constraint violations, configured through Fluent Api

### ISSUE THREAD

**Issue by arvinyorro** [dotnet/efcore#33861] opened 2024-05-31 09:43 UTC
### What problem are you trying to solve?
I want to simplify the implementation of custom SQL exceptions for constraints and other SQL violations

Custom exceptions are usually done like this:
```csharp
public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
{
    try
    {
        return await base.SaveChangesAsync(cancellationToken);
    }
    catch (DbUpdateException ex)
    {
        if (ex.InnerException is SqlException)
        {
            // Example for SQL Server, adapt for other databases
            switch (sqlException.Number)
            {
                case 2627: // Unique constraint error
                    throw new UniqueConstraintViolationException("A unique constraint violation occurred.");
                case 547:  // Foreign key violation
                    throw new ForeignKeyConstraintViolationException("A foreign key constraint violation occurred.");
                // Add cases for other constraint violations as needed
            }
        }
        
        throw; // Rethrow if the exception is not handled
    }
}
```

### Describe the solution you'd like

I would like a solution that can be configured through Fluent Api (for instance).

```csharp
builder.HasOne(m => m.User)
    .WithMany(m => m.Payments)
    .HasForeignKey(m => new { m.PaymentKey, })
    .HasPrincipalKey(c => new { c.PaymentKey, })
    .HasConstraintName("FK_Payment_User")
    .HasConstraintException<DuplicatePaymentKeyException>(); // 👈 Configure like this.
```

Where `DuplicatePaymentKeyException` implements `SqlException`.

**Comment by roji** [comment] 2024-05-31 09:49
@arvinyorro you're probably looking for [EntityFramework.Exceptions](https://learn.microsoft.com/en-us/ef/core/extensions/#entityframeworkexceptions).

**Comment by arvinyorro** [comment] 2024-05-31 09:50
> @arvinyorro you're probably looking for [EntityFramework.Exceptions](https://learn.microsoft.com/en-us/ef/core/extensions/#entityframeworkexceptions).

Is it typically implemented like my example above?

**Comment by ajcvickers** [comment] 2024-06-04 15:59
Duplicate of #4700

**Closed** 2024-06-04 17:03 UTC
Labels: customer-reported
