### ISSUE TITLE
Linq to Sql vs Entity Famework Core - Speed Test

### ISSUE THREAD

**Issue by Gfweis** [dotnet/efcore#7997] opened 2017-03-26 16:12 UTC
I decided to start learning something about .Net Core and Entity Framework for Core. Since most of our apps rely heavily on data access, I decided to start with the Entity Framework for .Net Core. After creating a working app, I decided to run the same the same query using Linq to SQL and test the response time. The database was local (running on the same machine). The EF code was created based on the following article… Data Points - Run EF Core on Both .NET Framework and .NET Core (https://msdn.microsoft.com/en-us/magazine/mt742867.aspx).

Linq to Sql vs Entity Famework Core – Speed Test

Linq to SQL in .net Library and called from .Net Console App Entity Framework Core in a Core Library called same .Net Console App

The query transfers table fields to a DTO object

Records in Table: 1,906,643; Records returned in Query: 78; Linq to SQL: 3 Seconds; Entity Framework Core: 19 Seconds

Similar Query for Both Linq to SQL and EF Core…
```c#
public IEnumerable<PackageDataDTO> GetAll(string Building, string Status="All")
{
    using (var context = new PackageDataEF.PackageDataContext(_options))
    {
        var Lst = from Dbo in context.PackageData
                  where Dbo.BuildingNumber.Equals(Building)
                  && (Dbo.Status.Equals("All") || Dbo.Status.Equals(Status))
                  select new PackageDataDTO
                  {
                      RecordGuid = Dbo.RecordGuid,
                      //TimeStamp = Dbo.TimeStamp,
                      BuildingNumber = Dbo.BuildingNumber,
                      UnitNumber = Dbo.UnitNumber,
                      TrackingNumber = Dbo.TrackingNumber,
                      Carrier = Dbo.Carrier,
                      PackageType = Dbo.PackageType,
                      PackageLocation = Dbo.PackageLocation,
                      StorageArea = Dbo.StorageArea,
                      DateOfReceiptUTC = Dbo.DateOfReceiptUTC,
                      DateLastChangeUTC = Dbo.DateLastChangeUTC,
                      Status = Dbo.Status,
                      ResidentId = Dbo.ResidentId,
                      NotificationBy = Dbo.NotificationBy,
                      CallSid = Dbo.CallSid,
                      Comments = Dbo.Comments,
                      DeliveredTo = Dbo.DeliveredTo,
                      DeliveredBy = Dbo.DeliveredBy,
                      DeliveryNotes = Dbo.DeliveryNotes,
                      DeliveryConfirmation = Dbo.DeliveryConfirmation,
                      DelayedNotification = Dbo.DelayedNotification,
                      GroupedNotification = Dbo.GroupedNotification,
                      ButtonOnReceipt = Dbo.ButtonOnReceipt,
                  };
        return Lst.ToList();
    }
}
```
Is there really that much of a speed difference or am I doing something wrong?

Timing all steps, everything runs is milliseconds until it hits .ToList(). Three subsequent identical queries all run in milliseconds including .ToList(); 

Thanks in advance for any guidance.
<code listing>
```

### Further technical details
EF Core version: 1.1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer v 1.1.1.0
Operating system: Windoews 10
IDE: Visual Studio 2017 Community

**Comment by Gfweis** [comment] 2017-03-27 14:57
I kept playing and decided to try a different approach.
<
 string Query = string.Format("Select * from PackageData Where Buildingnumber='{0}' and (Status='All' or Status='{1}')", Building, Status);
 var Lst = context.PackageData.FromSql(Query).ToList();
>
The result was returned in 3 seconds vs the 20 seconds that it took for the Linq query shown above.

Why is there such a difference?

**Comment by gdoron** [comment] 2017-03-27 15:19
@Gfweis you should check the generated SQL, that's most probably the reason.

**Comment by Gfweis** [comment] 2017-03-27 16:03
Isn't it the Entity Framework's responsibility to do the conversion to SQL? Or, does each query have to be checked to make sure that the Entity Framework makes the proper conversion before implementation?

**Comment by gdoron** [comment] 2017-03-27 16:28
Of course it is entity framework responsibility, but like always with ORM and specially with a relatively new one, sometimes you need to make sure the ORM generates good SQL.

Usually when stuff are slow in EF, it's the SQL.

**Comment by Gfweis** [comment] 2017-03-27 16:38
I will start watch in the SQL and testing the queries both ways before actual implementation.
Appreciate the follow up - thanks and have a really great day!

**Comment by divega** [comment] 2017-05-08 04:53
Found while scrubbing issues closed without resolution. Reopening since this could be an interesting test to look at while focusing on perf.

**Comment by anpete** [comment] 2017-05-08 16:59
@Gfweis Please post the query plan, which can be obtained by enabling logging at the Debug level.

**Comment by Gfweis** [comment] 2017-05-08 22:03
@anpete ... not sure how to provide the information that you are looking for. I looked under debug (VS 2017) for  a logging option - nothing found. Can you provide more details on exactly how to gather the information?

**Comment by anpete** [comment] 2017-05-08 22:08
@Gfweis Add a logger like https://www.nuget.org/packages/Microsoft.Extensions.Logging.Console and then set EF to use it in OnConfiguring:

```.UseLoggerFactory(new LoggerFactory().AddConsole());```

**Comment by ajcvickers** [comment] 2017-05-15 18:06
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 10:58 UTC
Labels: closed-could-not-reproduce
