### ISSUE TITLE
The specified deps.json [..] does not exist

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#28188] opened 2022-06-08 14:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-specified-depsjson--does-not-ex/10061484)._

---
We are trying to create Model class and DB contexts for particular MDF file by executing following comment but it was failed with following error. Could you please check and update solution for this issue?

>Scaffold-DbContext "Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Kl\source\repos\BlazorApp2\BlazorApp2\Data1\NORTHWND.MDF;Integrated Security=True" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Model -Context "Samplecontext" -DataAnnotations

![image.png](https://aka.ms/dc/image?name=B74c7ff46014647e8a0fd82b50fc8832a637898473930341087_20220603-153259-image.png&tid=74c7ff46014647e8a0fd82b50fc8832a637898473930341087)

---
#### Feedback Bot on 6/6/2022, 06:59 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2022-06-08 14:46
Duplicate of #16386.

**Closed by ajcvickers** 2022-06-08 14:46 UTC
Labels: closed-duplicate, customer-reported
