### ISSUE TITLE
How to define a view with linq query results?

### ISSUE THREAD

**Issue by ByZhouhang** [dotnet/efcore#27822] opened 2022-04-14 02:18 UTC
## How to define a view with linq query results

```C#

In Project, There are many similar queries, only some fields are different, 
how to write a "generic query" (similar to a view, but is defined in the code using linq  not raw sql, so that good maintenance), 
we can query on the basis of this "generic query"

```

### Include provider and version information

EF Core version: EF Core 6.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)

**Comment by roji** [comment] 2022-04-15 10:14
The above is missing details - please provide a concrete scenario with a model and the various queries you're looking to generate.

**Comment by ajcvickers** [comment] 2022-04-23 10:31
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:31 UTC
Labels: closed-could-not-reproduce, customer-reported
