### ISSUE TITLE
[Question] Conditional Include()

### ISSUE THREAD

**Issue by joacar** [dotnet/efcore#8016] opened 2017-03-28 13:08 UTC
Is it possible to compose a "conditional include" using LINQ syntax to generate SQL like `LEFT JOIN A ON A.Id ON B.Id AND A.SomeCondition = 1`?

Using query syntax it is possible by creating an anonymous class acting as key

```c#
from person in Persons
join platform from Youtube on 
new { PersonId = person.Id, IsLocked = {0,1} } 
equals 
new { PersonId = platform.PersonId, IsLocked = platform.IsLocked }
```

If this could be expressed like `Persons.Include(p => p.Youtube, youtube => IsLocked == {0,1})` that would be neat.

In my case I'm filtering `Persons` that can have multiple social platforms, some of them that might be locked and shouldn't be included in the result set. The person, however, should be included since it might have other platforms that might not be locked.

Hope it make sense :)

Thanks!

**Comment by smitpatel** [comment] 2017-03-28 13:35
dupe of #1833?

**Comment by joacar** [comment] 2017-03-28 13:37
Yeah looks like what I want to achieve. Close it and i'll subscribe to that issue (y)

**Closed** 2022-10-16 10:58 UTC
Labels: closed-duplicate
