### ISSUE TITLE
plural vs. singular issue

### ISSUE THREAD

**Issue by tdjastrzebski** [dotnet/efcore#5239] opened 2016-05-01 12:13 UTC
In 99% cases DB developers creating a DB table for, let's say, customer name it Customer**s**, not Customer. Northwind, Contoso and other numerous examples available.

However, code developers expect Customer class/entity and Customer**s** data context collection.

This is the reality. EF Core does not seem to respect it yet scaffolding database context.

**Comment by divega** [comment] 2016-05-01 14:23
Dupe of #3060.

**Closed** 2022-10-16 09:38 UTC
