### ISSUE TITLE
EF Core Query Translation Bug: Missing Elements in SQL for Complex GroupBy with Union and Cross Join

### ISSUE THREAD

**Issue by ashpetrosyan97** [dotnet/efcore#33244] opened 2024-03-05 11:05 UTC
# Issue: Incomplete SQL Translation for Complex EF Query Involving Grouping and Cross Join

## Description

We have encountered an issue where a complex Entity Framework Core query involving grouping, a union of two sequences, and a subsequent cross join does not translate correctly to SQL. The EF query intends to filter users based on a set of conditions applied to their orders and a cross join with a derived table from split values. However, the generated SQL seems to miss significant parts of the logic, particularly around the union and cross join operations.

## Entity Framework Query

The EF Core LINQ query is as follows:

```csharp
var queryable = context.Users.Where(u =>
    u.Orders.GroupBy(o => o.StartDate.Date, (k, g) => g.Select(o => new OrderData
            {
                Id = o.Id,
                StartDate = o.StartDate,
                EndDate = o.EndDate
            })
            .Union(u.WorkingScheme.WorkingDays.Where(w => w.Day == k.DayOfWeek).SelectMany(
                a => context.Split("0,1", ","), (day, b) => new OrderData
                {
                    Id = b.Value == "0" ? 0 : int.MaxValue,
                    EndDate = b.Value == "0" ? k.Date + day.StartTime.ToTimeSpan() : k.Date + day.EndTime.ToTimeSpan(),
                    StartDate = b.Value == "1" ? k.Date + day.EndTime.ToTimeSpan() : k.Date + day.StartTime.ToTimeSpan()
                })))
        .Select(t =>
            t.SelectMany(current => t.Take(1),
                (current, prev) => current.StartDate - prev.EndDate > TimeSpan.FromMinutes(1)).Count(a => a) > 0
        ).Any());
```

This query is designed to perform a complex data retrieval operation, where it groups the orders by their start date, unions the results with another dataset, and applies a condition based on the cross join result.

## Translated SQL

The SQL generated by EF Core is as follows:

```sql
SELECT u.id, u.name
FROM users AS u
LEFT JOIN working_scheme AS w ON u.id = w.user_id
WHERE EXISTS (
    SELECT 1
    FROM (
        SELECT o.id, o.end_date, o.name, o.start_date, o.user_id, date_trunc('day', o.start_date, 'UTC') AS "Key"
        FROM orders AS o
        WHERE u.id = o.user_id
    ) AS t
    GROUP BY t."Key")
```

## Issue Details

The translated SQL does not reflect the entire logic of the original EF query. Key elements, particularly related to the union operation and the subsequent cross join logic, are absent. The expected SQL should include more complex join operations and possibly a more detailed subquery that encapsulates the logic expressed in the original LINQ query.

## Expected Behavior

The expected SQL should accurately represent the LINQ query's logic, including all grouping, union, and cross join operations. It should ensure that all conditions and transformations specified in the EF query are translated correctly and included in the SQL output.

## Steps to Reproduce

1. Clone the source code from the repository: [WrongTranslationsExample](https://github.com/ashpetrosyan97/WrongTranslationsExample).
2. Execute the provided EF query in an environment where the EF Core is set up to log the generated SQL.
3. Observe the generated SQL and compare it with the expected SQL logic that should include the union and cross join transformations.

1. Execute the provided EF query in an environment where the EF Core is set up to log the generated SQL.
2. Observe the generated SQL and compare it with the expected SQL logic that should include the union and cross join transformations.

**Comment by roji** [comment] 2024-03-09 10:13
Thanks for the minimal repro - confirmed that there's an issue here (possibly several); see below for a minimal repro on SQL Server for further investigation.

Here is your query, reformatted for easier readability and only slightly simplified:

```c#
var queryable = context.Users
    .Where(u =>
        u.Orders
            .GroupBy(
                o => o.StartDate.Date,
                (k, g) =>
                    g
                        .Select(o => new OrderData
                        {
                            Id = o.Id,
                            StartDate = o.StartDate,
                            EndDate = o.EndDate
                        })
                        .Union(u.WorkingScheme.WorkingDays.SelectMany(
                            a => context.Split("0,1", ","), (day, b) => new OrderData
                            {
                                Id = b.Value == "0" ? 0 : int.MaxValue,
                                EndDate = k.Date,
                                StartDate = k.Date
                            })))
            .Select(t =>
                t.SelectMany(current => t.Take(1),
                    (current, prev) => current.StartDate - prev.EndDate > TimeSpan.FromMinutes(1)).Count(a => a) > 0)
            .Any());
```

And the SQL:

```sql
SELECT [u].[Id], [u].[Name]
FROM [Users] AS [u]
LEFT JOIN [WorkingScheme] AS [w] ON [u].[Id] = [w].[UserId]
WHERE EXISTS (
    SELECT 1
    FROM (
        SELECT [o].[Id], [o].[EndDate], [o].[Name], [o].[StartDate], [o].[UserId], CONVERT(date, [o].[StartDate]) AS [Key]
        FROM [Orders] AS [o]
        WHERE [u].[Id] = [o].[UserId]
    ) AS [t]
    GROUP BY [t].[Key])
```

Here are some observations; 

* First of all, doing Select() followed by Any() generally doesn't make sense; since the Any() returns a simple bool indicating whether there are any elements, applying a projection on the elements right before with Select() is meaningless. the Select() can be stripped away from the query, and EF is *probably* doing that - this is why you're not seeing it in the SQL.
* The same logic applies to your use of the GroupBy() overload with two parameters: your GroupBy groups by the StartDate, but then projects the result elements via a result selector (that's the part where there's a Union). This again has no effect on the query results, since an Any() is composed right afterwards

At this point your query can be reduced to the following:

```c#
var queryable = context.Users
    .Where(u => u.Orders
        .GroupBy(o => o.StartDate.Date)
        .Any());
```

... which generates the same SQL as your original query.

However, doing GroupBy() follows by Any() is also somewhat useless: the Any() will return true as long as there's any pre-grouped element (since that would ensure at least one group), so you're effecting just asking for users who have any order:

```c#
var queryable = context.Users.Where(u => u.Orders.Any());
```

Which produces the following SQL:

```sql
SELECT [u].[Id], [u].[Name]
FROM [Users] AS [u]
WHERE EXISTS (
    SELECT 1
    FROM [Orders] AS [o]
    WHERE [u].[Id] = [o].[UserId])
```

If you're still convinced the SQL translation is incorrect, I'd recommend trying to think of a situation where your original query and the simplified proposal above actually produce different results (and trying to actually making that happen in a test).

Some possible issues I can see:
* In the original query, the LEFT JOIN on WorkingScheme is in the query although it isn't referenced - it can/should be pruned (our current pruning is quite restricted in general)
* GROUP BY can be stripped away inside EXISTS, just like we strip away the projection (this is a low-value optimization/SQL improvement - useful only when the user writes needlessly complex LINQ as above).

<details>
<summary>Test code for SQL Server for reference</summary>

```c#
await using var context = new BlogContext();
await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

var queryable = context.Users
    .Where(u =>
        u.Orders
            .GroupBy(
                o => o.StartDate.Date,
                (k, g) =>
                    g
                        .Select(o => new OrderData
                        {
                            Id = o.Id,
                            StartDate = o.StartDate,
                            EndDate = o.EndDate
                        })
                        .Union(u.WorkingScheme.WorkingDays.SelectMany(
                            a => context.Split("0,1", ","), (day, b) => new OrderData
                            {
                                Id = b.Value == "0" ? 0 : int.MaxValue,
                                EndDate = k.Date,
                                StartDate = k.Date
                            })))
            .Any());

Console.WriteLine(queryable.ToQueryString());

public class BlogContext : DbContext
{
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<WorkingScheme> WorkingScheme { get; set; }
    public virtual DbSet<WorkingDay> WorkingDays { get; set; }
    public virtual DbSet<Order> Orders { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            // .UseNpgsql("Host=localhost;Username=test;Password=test")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        // configurationBuilder.Properties<DateTime>().HaveColumnType("timestamptz").HavePrecision(0)
        //     .HaveConversion<DateValueConverter>();
        configurationBuilder.Properties<DateTime>()/*.HaveColumnType("timestamptz")*/.HavePrecision(0)
            .HaveConversion<DateValueConverter>();
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.HasDbFunction(GetType().GetMethod(nameof(Split))!).HasName("string_split");
        modelBuilder.Entity<Result>().HasNoKey().ToTable(e => e.ExcludeFromMigrations());


        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.HasMany(d => d.Orders).WithOne(p => p.User)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);


            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<WorkingScheme>(e =>
        {
            e.HasIndex(p => p.UserId)
                .IsUnique();

            e.HasOne(p => p.User)
                .WithOne(s => s.WorkingScheme)
                .HasForeignKey<WorkingScheme>(w => w.UserId);
        });

        modelBuilder.Entity<WorkingDay>(e =>
        {
            e.HasOne(p => p.WorkingScheme)
                .WithMany(s => s.WorkingDays)
                .HasForeignKey(p => p.WorkingSchemeId);

            e.HasIndex(p => new { p.WorkingSchemeId, p.Day })
                .IsUnique();

            e.Property(p => p.Day)
                .HasConversion(new EnumToStringConverter<DayOfWeek>());
        });


    }
    public IQueryable<Result> Split(string input, string separator)
        => FromExpression(() => Split(input, separator));
}

public class User
{
    public int Id { get; set; }

    public string Name { get; set; }

    public WorkingScheme WorkingScheme { get; set; }
    public virtual ICollection<Order> Orders { get; set; }
}


public class Order
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int UserId { get; set; }

    public virtual User User { get; set; }
    public DateTime StartDate { get; set; }
    public DateTime EndDate { get; set; }
}


public partial class WorkingDay
{
    public int Id { get; set; }
    public TimeOnly StartTime { get; set; }
    public TimeOnly EndTime { get; set; }
    public DayOfWeek Day { get; set; }
    public int WorkingSchemeId { get; set; }
    public WorkingScheme WorkingScheme { get; set; }
}

public class WorkingScheme
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public User User { get; set; }
    public ICollection<WorkingDay> WorkingDays { get; set; }

    [NotMapped]
    public static WorkingScheme Default => new()
    {
        WorkingDays = new[]
        {
            new WorkingDay { Day = DayOfWeek.Monday, StartTime = new TimeOnly(9, 0, 0), EndTime = new TimeOnly(18, 0, 0) },
            new WorkingDay { Day = DayOfWeek.Tuesday, StartTime = new TimeOnly(9, 0, 0), EndTime = new TimeOnly(18, 0, 0) },
            new WorkingDay
                { Day = DayOfWeek.Wednesday, StartTime = new TimeOnly(9, 0, 0), EndTime = new TimeOnly(18, 0, 0) },
            new WorkingDay
                { Day = DayOfWeek.Thursday, StartTime = new TimeOnly(9, 0, 0), EndTime = new TimeOnly(18, 0, 0) },
            new WorkingDay { Day = DayOfWeek.Friday, StartTime = new TimeOnly(9, 0, 0), EndTime = new TimeOnly(18, 0, 0) }
        }
    };
}

public record OrderData
{
    public int Id { get; set; }
    public DateTime StartDate { get; set; }
    public DateTime EndDate { get; set; }
}

public class DateValueConverter : ValueConverter<DateTime, DateTime>
{
    public DateValueConverter() : base(v => DateTime.SpecifyKind(v, DateTimeKind.Utc), v => DateTime.SpecifyKind(v, DateTimeKind.Utc))
    {
    }
}
public class Result
{
    public string Value { get; set; }
}
```

</details>

**Comment by ashpetrosyan97** [comment] 2024-03-13 13:25
Thanks for the response. 
The main idea of this query is to group each user's orders by start date, add 2 fake orders in each group,  and after sorting each group get gap intervals between grouped items. After computing intervals, it need to filter users who have interval greater than or equal to given.

**Comment by roji** [comment] 2024-03-13 16:34
@ashpetrosyan97 unless I'm misunderstanding things, your textual description doesn't correspond to the actual LINQ query you posted above. I looked at the LINQ query, and the EF translation - stripping out the Union and various other parts - seems correct, as per my comment above. I need to see an actual LINQ query which you think translates incorrectly.

**Comment by roji** [comment] 2024-03-13 23:50
@ashpetrosyan97 it's up to you to figure out the LINQ query that expresses what you want; your query currently contains an Any, meaning you're querying for Users that has any Order (therefore all projections on the orders become irrelevant). I'd suggest first trying to write a LINQ query that works in memory - against a regular .NET array - and then try to execute that via EF.

**Comment by roji** [comment] 2024-03-19 10:26
@ashpetrosyan97 I'm going to go ahead and close this as you haven't provided an actual LINQ query that translates incorrectly. If you post back a clear LINQ query with a correponding SQL that you believe to be incorrect, I can reopen and investigate. Otherwise, I suggest reading up on LINQ in general to understand what the different operators do and how to construct the query you need.

**Closed by roji** 2024-03-19 10:26 UTC
Labels: customer-reported, area-query

**Comment by ashpetrosyan97** [comment] 2024-03-19 15:49
I was not able to change the existing query without using any after selection, there still is open question how make framework to translate union with groupby and and check condition on it. Thanks for responding.
