### ISSUE TITLE
EF7 doesn't save entities while EF6 does

### ISSUE THREAD

**Issue by JohnyL** [dotnet/efcore#2629] opened 2015-07-15 17:52 UTC
I have create test solution with two projects - with EF6 and EF7. Here's code:

**1. Entities**

``` C#
public class Blog
{
    public Blog()
    {
        Posts = new List<Post>();
    }
    public int Id { get; set; }
    public string Url { get; set; }
    public List<Post> Posts { get; set; }
}

public class Post
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }
    public int BlogId { get; set; }
    public Blog Blog { get; set; }
}
```

**2. EF6 context**

``` C#
public class TestContext : DbContext
{

    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }

    public TestContext() : base("name=Test")
    {
        this.Configuration.AutoDetectChangesEnabled = true;
        this.Configuration.LazyLoadingEnabled = false;
        this.Configuration.ProxyCreationEnabled = false;
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        modelBuilder.Configurations.Add(new BlogConfiguration());
        modelBuilder.Configurations.Add(new PostConfiguration());
    }
}

public class BlogConfiguration : EntityTypeConfiguration<Blog>
{
    public BlogConfiguration()
    {
        this.ToTable("Blog");
        this.HasKey(p => p.Id);
        this.Property(p => p.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
        this.HasMany(p => p.Posts).WithRequired(p => p.Blog);
    }
}

public class PostConfiguration : EntityTypeConfiguration<Post>
{
    public PostConfiguration()
    {
        this.ToTable("Post");
        this.HasKey(p => p.Id);
        this.Property(p => p.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
    }
}
```

**3. EF7 context**

``` C#
public class TestContext : DbContext
{

    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(System.Configuration.ConfigurationManager.ConnectionStrings["Test"].ConnectionString);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        ConfigureBlog(modelBuilder);
        ConfigurePost(modelBuilder);
    }

    private void ConfigureBlog(ModelBuilder modelBuilder)
    {
        var blogEntity = modelBuilder.Entity<Blog>();
        blogEntity.ToTable("Blog").Key(p => p.Id);
        blogEntity.Collection(p => p.Posts).InverseReference(p => p.Blog);
    }

    private void ConfigurePost(ModelBuilder modelBuilder)
    {
        var postEntity = modelBuilder.Entity<Post>();
        postEntity.ToTable("Post").Key(p => p.Id);
        postEntity.Reference(p => p.Blog).InverseCollection(p => p.Posts);
    }

}
```

**4. Test procedure**

``` C#
private void OnSaveData(object sender, EventArgs e)
{
    using (var db = new TestContext())
    {
        var blog = new Blog { Id = 1, Url = "http://www.somesite.com" };
        var post1 = new Post { Id = 1, Title = "Title1", Content = "Content1", Blog = blog };
        var post2 = new Post { Id = 2, Title = "Title2", Content = "Content2", Blog = blog };
        blog.Posts.AddRange(new[] { post1, post2 });
        db.Blogs.Add(blog);
        int records = db.SaveChanges();
        MessageBox.Show($"{records} records were saved.");
    }
}
```

Here's result:
EF6. 1 record - in Blog table. 2 records in Post table.
EF7. 1 record - in Blog table. 0 records in Post table.

I guess, I've configured relations in EF7 correctly, but no records are saved into Post table.

**Comment by maumar** [comment] 2015-07-16 01:02
Duplicate of https://github.com/aspnet/EntityFramework/issues/2387

**Closed** 2022-10-16 09:02 UTC
