### ISSUE TITLE
Update Entity with Computed column in sql

### ISSUE THREAD

**Issue by ampalla** [dotnet/efcore#5793] opened 2016-06-16 18:02 UTC
When updating an entity with computed column in sql, I get the error:

> Column 'inserted.Status' cannot be referenced in the OUTPUT clause because the column definition contains a subquery or references a function that performs user or system data access. A function is assumed by default to perform data access if it is not schemabound. Consider removing the subquery or function from the column definition or removing the column from the OUTPUT clause

As also mentioned by @xrkolovos  at issue #5282, when updating an entity with property set as computed by scalar function, the column is included in the output sql statement, as follows:

```
UPDATE [Subjects] SET [CouncilId] = @p1, ... [SubjectGroupId] = @p14
OUTPUT INSERTED.[SubjectStatus]
INTO @inserted0
WHERE [Id] = @p0;
SELECT [SubjectStatus] FROM @inserted0;
```

This results to error in SQL Server

**Comment by ajcvickers** [comment] 2016-06-17 16:47
@ampalla Can you post repro code for this? Please include entity classes, anything in OnConfiguring, and how you are querying/attaching/modifying/saving/etc. in your app.

**Comment by rdefreitas** [comment] 2016-06-23 04:10
When this is resolved, aspnet/EntityFramework.Docs#122 needs to be updated.

**Comment by rowanmiller** [comment] 2016-06-24 18:07
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Comment by rowanmiller** [comment] 2016-06-24 18:07
@rdefreitas the issue blocking the docs is actually already fixed (I'll update the doc and sample)

**Comment by skimedic** [comment] 2016-07-08 23:51
@rowanmiller - I'm hitting this same issue in RTM - please let me know if this should be reopened or a new issue. Of course it could be a problem between my keyboard and chair as well...

I have code I can send you (it's the code for the new book) if that will help.  There are actually two issues that I am running into, don't know if they are related or if the other one should be a new issue.

1) As mentioned above, when I have a computed column based on a scalar function, I can't update the record.  I have an Order table and an OrderDetail table.  I have a scalar function that computes the total cost of an order (summing all of the order detail records) to display on the Order table.  Here are the abbreviated details:

Property definition:
        `public class Order : EntityBase
         {
               public int CustomerId { get; set; }
               public string CategoryName {get;set;}
               [DataType(DataType.Currency)]
               [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
               public decimal? OrderTotalComputed { get; set; }
               //shortened for brevity
           }`        
OnModelCreating:
            'modelBuilder.Entity<Order>(entity =>
            {
                entity.Property(e => e.OrderTotalComputed)
                    .HasColumnType("money")
                    .HasComputedColumnSql("Store.GetOrderTotal([Id])");
                    //.ValueGeneratedOnAddOrUpdate();
            });'
when I first create an order record, it works fine.  If I update the CategoryName (for example), I get the following error:
Result StackTrace:	
at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at SpyStore.DAL.Tests.Context.OrderTests.ShouldUpdateAnOrder() in C:\GitHub\Responsive\CodeSamples\Chapter05-EF\RTM\SpyStore.DAL\test\SpyStore.DAL.Tests\Context\OrderTests.cs:line 42
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
Result Message:	
An error occurred while updating the entries. See the inner exception for details.
Column 'inserted.OrderTotalComputed' cannot be referenced in the OUTPUT clause because the column definition contains a subquery or references a function that performs user or system data access. A function is assumed by default to perform data access if it is not schemabound. Consider removing the subquery or function from the column definition or removing the column from the OUTPUT clause.
In the attached code, execute the SpyStore.DAL.Tests.Context.OrderTests.ShouldUpdateAnOrder test to see the error in action.

2. The second issue is that when I have such a computed column, if I add/update order detail records in a DbContext, the computed column doesn't update in my entity.  However, if I create a new Context, I get the correct value.  The new DbContext test is illustrated with this test: SpyStore.DAL.Tests.Context.OrderTests.ShouldGetOrderTotal (this test uses a new DbContext than the one that seeded the data)
The failing test (where the value doesn't get udpated in the same DbContext) is here: 
SpyStore.DAL.Tests.Context.OrderTests.ShouldGetOrderTotalAfterAddingAnOrderDetail
[SpyStore.DAL.zip](https://github.com/aspnet/EntityFramework/files/355272/SpyStore.DAL.zip)

**Closed** 2022-10-16 09:45 UTC
