### ISSUE TITLE
Couldn't Load File or Assembly - EntityFrameworkCore 

### ISSUE THREAD

**Issue by mvermef** [dotnet/efcore#7109] opened 2016-11-23 16:25 UTC
### The issue
Line	Suppression State Error: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

this has been recurring since previous 2 versions (1.0, 1.01, etc)..  It occurs on every viewmodel / view associated with my project.  The viewmodel is set on the view within the page's datacontext property in XAML.

    <Page.DataContext>
       <vm:SettingsPageViewModel x:Name="ViewModel" />
    </Page.DataContext>

___doesn't cause issues with compilation or running.  Is this something correctable on my end?___

### Further technical details

EF Core version: 1.1
Operating system:  Windows 10 AU
Visual Studio version: 2015 U3

Other details about my project setup:  UWP application with App.config for assembly binding

**Comment by rowanmiller** [comment] 2016-11-23 17:30
Looks like a duplicate of https://github.com/aspnet/EntityFramework/issues/7069 (which I am looking into)

**Comment by mvermef** [comment] 2016-11-23 17:59
Slight difference i don't use __using__ to instantiate the context in the viewmodels.  They are all ctor instantiated for the request.

**Comment by rowanmiller** [comment] 2016-11-23 18:31
I think that detail is probably irrelevant to the underlying issue, but can you just post an example of the view model code so that I can take it into account when I investigate #7069. Closing this one out, but you can post the code here still (or on #7069 is fine too).

**Closed** 2022-10-16 10:44 UTC
