### ISSUE TITLE
Timeout expired exception on querying non-indexed columns 

### ISSUE THREAD

**Issue by alex-zyl** [dotnet/efcore#9682] opened 2017-09-01 23:01 UTC
Tested on 1.1.2 and 2.0.

Database hosted in Azure SQL contains table with the following structure:
```
Id PK uniqueidentifier
Timestamp datetimeoffset
TenantId uniqueidentifier
other columns
```

Table has only clustered index, contains more than 200k records.

Recently EF started failing by timeout when executing the following query:

```dbContext
.TaskRecords
.Where(r => r.TenantId == tenantId)
.OrderByDescending(item => item.Timestamp)
.Skip(0)
.Take(10)
.ToListAsync();
```

Query store analysis shown that EF generates the following SQL:

```
exec sp_executesql N'SELECT [r].[Id],[r].[TenantId], [r].[Timestamp], [r].
[OTHER_COLUMNS]
FROM [TaskRecords] AS [r]
WHERE [r].[TenantId] =@__tenantId_0
ORDER BY [r].[Timestamp] DESC
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY',N'@__tenantId_0 uniqueidentifier,@__p_1 
int,@__p_2 int',@__tenantId_0 ='645B38D4-1009-47CF-8519-
182865827F22',@__p_1=0,@__p_2=10
```

which executes in less than 1 second when running from SSMS or SqlCommand

I created few console applications to compare behavior between EF 6.1.3, EFCore 1.1.2 and EFCore 2.0

```
static void Main(string[] args)
{
    var context = new DbContext(...);
    var result = context.TaskRecords
    .Where(r => r.TenantId == tenantId)
    .OrderByDescending(item => item.Timestamp)
    .Skip(0)
    .Take(10)
    .ToList(); // WORKS FINE

    result = GetRecords();
}

public static List<TaskRecords> GetRecords()
{
    var context = new DbContext(...);
    return context.TaskRecords
    .Where(r => r.TenantId == tenantId)
    .OrderByDescending(item => item.Timestamp)
    .Skip(0)
    .Take(10)
    .ToList();
}
```

TaskRecords class contains 18 properties (nullable/nonnullable Guids/DateTimeOffset, strings, int)

EF 6.1.3 executes both queries in less than 1 second
EFCore 1.1.2 and 2.0 execute the query within Main method in less than 1 second, but fail by time out when executing from GetRecords method.

Observations:
1. Replacing OrderByDescending with OrderBy  - no timeout
2. Commenting out one random property from TaskRecords entity class - no timeout

**Comment by ajcvickers** [comment] 2017-09-07 00:31
@alex-zyl We don't think that there is enough information here to be able to reproduce what you are seeing. Could you provide a full code listing or project that exhibits the issue?

**Comment by alex-zyl** [comment] 2017-09-07 09:11
@ajcvickers 
Thanks for the reply.

I can upload test project to github and provide the link, but it seems that there's also a problem in the database itself. 
I made a copy of our database  on the same Azure server and ran the app against it and got no issues. I noticed that request fails after clustered index fragmentation goes above 10%.

I'll try to prepare test database where this issue can be reproduced.

**Comment by ajcvickers** [comment] 2017-09-07 16:13
@alex-zyl Given what you say, I'd guess this is more likely an issue with SQL Azure than with EF. You might get better answers following up directly with those folks.

**Comment by ajcvickers** [comment] 2017-09-13 18:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:20 UTC
Labels: closed-external
