### ISSUE TITLE
InMemory provider ignores unique keys

### ISSUE THREAD

**Issue by hameedfs** [dotnet/efcore#4516] opened 2016-02-08 11:03 UTC
InMemory provider ignores unique key constraints defined in the model. Attached is a test code that shows the behavior comparing it to SQLite.

**Comment by hameedfs** [comment] 2016-02-08 11:04
[UniqueIdTests.zip](https://github.com/aspnet/EntityFramework/files/121464/UniqueIdTests.zip)

**Comment by rowanmiller** [comment] 2016-02-12 18:11
Duplicate of https://github.com/aspnet/EntityFramework/issues/3850

**Closed** 2022-10-16 09:28 UTC
