### ISSUE TITLE
dbset Find method missing

### ISSUE THREAD

**Issue by johnciliberti** [dotnet/efcore#2012] opened 2015-04-13 03:38 UTC
Expecting to see the DbSet.Find(id) method  but it does not seem to exist.

Is this a feature that will not be supported in EF 7? If so, I think you should reconsider since this is a very commonly used feature.

**Comment by ErikEJ** [comment] 2015-04-13 05:21
Duplicate of https://github.com/aspnet/EntityFramework/issues/797

**Closed** 2022-10-16 08:54 UTC
