### ISSUE TITLE
Add --dry-run to dotnet ef database update

### ISSUE THREAD

**Issue by EricStG** [dotnet/efcore#23608] opened 2020-12-07 19:45 UTC
I'd like to be able to see what is going to happen when I run `dotnet ef database update` to a specific database without actually applying it.

Currently, we can get a script using `dotnet ef dbcontext script` but that requires knowing the current migration version.

Adding a `--dry-run` option to dotnet ef database update and that would output the script to be executed

**Comment by ajcvickers** [comment] 2020-12-11 19:44
Duplicate of #1775

**Closed** 2022-10-16 19:14 UTC
Labels: closed-duplicate, customer-reported
