### ISSUE TITLE
Client side GroupBy is not supported in EF 3.0

### ISSUE THREAD

**Issue by mdmoura** [dotnet/efcore#18102] opened 2019-09-27 16:49 UTC
I have the following Entity Framework Core 3.0 query:

    var units = await context.Units
      .SelectMany(y => y.UnitsI18N)
      .OrderBy(y => y.Name)
      .GroupBy(y => y.LanguageCode)
      .ToDictionaryAsync(y => y.Key, y => y.Select(z => z.Name));

And I get the following error:

<details>

Exception has occurred: CLR/System.InvalidOperationException
An exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Client side GroupBy is not supported.'
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQueryExpression(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToDictionaryAsync>d__90`3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DataSeed.<ExportDatabase>d__10.MoveNext() in /Users/Me/Project/DataSeed.cs:line 168
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Nupaya.Seed.DataSeed.<AddDataAsync>d__6.MoveNext() in /Users/Me/Project/DataSeed.cs:line 72
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

</details>

The exact same query was working in Entity Framework 2.2.

Why am I getting this error if I am not running the query on the client?

To run the query on the client, or part of it, I would do the following:

    var units = context.Units
      .SelectMany(y => y.UnitsI18N)
      .OrderBy(y => y.Name)
      .AsEnumerable()
      .GroupBy(y => y.LanguageCode)
      .ToDictionary(y => y.Key, y => y.Select(z => z.Name));

Now it works ...

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.0
Operating system: MacOs Mojave 10.14.6
IDE: Visual Studio Code 1.38.1

**Comment by smitpatel** [comment] 2019-09-27 16:50
Duplicate of #17068

**Comment by mdmoura** [comment] 2019-09-27 16:59
@smitpatel I checked #17068 ... So EF 3.0 does not support GroupBy unless it is on the client?

What about the Following SQL query?

```
SELECT *
FROM Customers
GROUP BY Country
HAVING COUNT(CustomerID) > 5;
```

Should I load all Customers into memory? Maybe I am missing something.

About my original query is there a way to change it so it runs on the client?

Not sure what EF team is suggesting us to on these situations.

**Comment by smitpatel** [comment] 2019-09-27 17:01
The SQL you posted is invalid SQL in SqlServer.
```
Msg 8120, Level 16, State 1, Line 1
Column 'Customers.CustomerID' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
```

**Comment by mdmoura** [comment] 2019-09-27 17:06
@smitpatel Correct, I meant:

```
SELECT COUNT(CustomerID), Country
FROM Customers
GROUP BY Country
HAVING COUNT(CustomerID) > 5;
```

**Comment by mdmoura** [comment] 2019-09-27 17:12
@smitpatel Shouldn't this be working:

      var units = await _context.Units
        .SelectMany(x => x.UnitsI18N, (unit, unitI18N) => new { LanguageCode = unitI18N.LanguageCode, Name = unitI18N.Name })
        .OrderBy(x => x.Name)
        .GroupBy(x => x.LanguageCode)
        .ToDictionaryAsync(x => x.Key, x => x.Select(y => y.Name));

**Comment by smitpatel** [comment] 2019-09-27 20:23
Your SQL query and linq query are different results. I am not sure what point are you trying to make.

**Comment by roji** [comment] 2019-09-28 15:57
> The exact same query was working in Entity Framework 2.2.

@mdmoura just to make sure you understand, your query was also running on the client in with EF Core 2.2. The only change is that version 3.0 requires you to explicit opt into client evaluation. As to why your LINQ query can't be translated to SQL, I think @smitpatel addressed that above.

**Comment by mdmoura** [comment] 2019-09-28 21:04
@roji Yes, I saw now that the Query was running on the Client in ASP.NET Core 2.2. It was not a critical query as it is only seeding the database on development machine.

On the application itself I had EF Core 2.2 to throw an exception when client evaluation occurs.

I also know that the fields used in a GroupBy must be in a select, e.g.:

```
SELECT COUNT(UnitId), Type
FROM Units
GROUP BY Type
```

What I am trying to figure out is how the following query can be changed, or if can be changed, so that the GroupBy is executed on the server and not on the client:

    var units = await _context.Units
      .SelectMany(x => x.UnitsI18N, (unit, unitI18N) => new { LanguageCode = unitI18N.LanguageCode, Name = unitI18N.Name })
      .OrderBy(x => x.Name)
      .GroupBy(x => x.LanguageCode)
      .ToDictionaryAsync(x => x.Key, x => x.Select(y => y.Name))

When I write the following:

    .SelectMany(x => x.UnitsI18N, (unit, unitI18N) => new { LanguageCode = unitI18N.LanguageCode, Name = unitI18N.Name })

I am trying to select fields and not objects being one of those fields, LanguageCode, the one used in GroupBy so that evaluates on the Server. But it still giving me the Client exception.

I am just trying to understand the logic in Linq that allows GroupBy to run on the server.

**Comment by roji** [comment] 2019-09-28 22:50
Take a look at #17068 to better understand how LINQ GroupBy translates (and doesn't translate) to SQL GROUP BY. tl;dr SQL GROUP BY requires an aggregate operator to reduce the groups to scalar (e.g. COUNT, MAX...). The typical LINQ pattern here would be to first have a Select, applying the aggregate operator, and then GroupBy.

**Closed** 2022-10-16 14:45 UTC
Labels: customer-reported
