### ISSUE TITLE
EF core 3 global query filter cannot translate contain expression

### ISSUE THREAD

**Issue by dimz87** [dotnet/efcore#18465] opened 2019-10-19 19:31 UTC
In the EF Core version 2.2 i can create a query filter with contain as the filtering expression, in the version 3.0 it will throw exception that showing it cannot be translated.

### Steps to reproduce

In the db context class create an entity with query filter

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
          
            base.OnModelCreating(modelBuilder);
modelBuilder.Entity<Company>().HasQueryFilter(c =>
          _companyCodes.Contains(c.Code));
}
```

The filter will always produce exception:

`The LINQ expression 'Where<Company>(
    source: DbSet<Company>, 
    predicate: (c) => (Unhandled parameter: __ef_filter__p_0) || (Unhandled parameter: __ef_filter___companyCodes_1).Contains(c.Code))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.`

As it is located in the queryfilter i cannot use asasyncenumberable or to list, how to mitigate this issue in ef 3 ?

### Further technical details

EF Core version: 3.0
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.5

**Comment by smitpatel** [comment] 2019-10-20 06:35
What is the type of `_companyCodes`?

**Comment by dimz87** [comment] 2019-10-20 10:41
The companyCode is guid.

**Comment by smitpatel** [comment] 2019-10-20 21:05
Could be duplicate of #17342
Can you try running with 3.1-preview1 package?

**Comment by dimz87** [comment] 2019-10-21 01:16
Hi smith, already and got same result.

**Comment by smitpatel** [comment] 2019-10-21 01:39
@dimz87 - can you share a small repro code which demonstrate the issue?

**Comment by dimz87** [comment] 2019-10-21 01:53
> @dimz87 - can you share a small repro code which demonstrate the issue?

Sorry, i have clarify my comment, pleas see my comment

**Closed** 2022-10-16 14:51 UTC
Labels: closed-duplicate, customer-reported
