### ISSUE TITLE
EF core 5.0 doesn't detect change to DateTimeOffset's offset

### ISSUE THREAD

**Issue by clement911** [dotnet/efcore#24567] opened 2021-04-02 12:10 UTC
I see the following bug with EF 5.0

```
var entity = dbCtx.Find<MyEntity>(123);//Load from DB context
entity.MyDateTimeOffset = entity.MyDateTimeOffset.ToOffset(entity.MyDateTimeOffset.Add(TimeSpan.FromHours(2)));//Switch the offset by 2 hours
ctx.Entry(order).State; //Return Unchanged but expecting Modified
```

I believe this happens because `IEquatable<DateTimeOffset>` considers that two `DateTimeOffset`s are equal if they represent the same absolute time.
However, from a DB perspective, the code above should detect the change and persist the new offset in the column (which is of type `datetimeoffset` in Sql Azure)

**Comment by dengere** [comment] 2021-04-04 10:50
I can't reproduce it, 
it could be something missed. entity.MyDateTimeOffset.Add(TimeSpan.FromHours(2)) produce new DateTimeOffset object. ToOffset acccept only  TimeSpan, and it can not convert from DateTimeOffset to TimeSpan.

**Comment by clement911** [comment] 2021-04-06 08:15
Here is a more comprehensive repro, using the InMemoryDatabase provider.

Program.cs
```
using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;

namespace ReproEFOffset
{
    public class MyEntity
    {
        [Key]
        public int Id { get; set; }

        public DateTimeOffset UpdatedAt { get; set; }
    }

    public class MyContext : DbContext
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<MyEntity>().HasKey(i => i.Id);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseInMemoryDatabase("MyDb");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var ctx = new MyContext();
            var entity = new MyEntity { Id = 1, UpdatedAt = DateTimeOffset.UtcNow };
            ctx.Add(entity);
            ctx.SaveChanges();

            entity.UpdatedAt = entity.UpdatedAt.ToOffset(TimeSpan.FromHours(-6));
            var entityState = ctx.Entry(entity).State;
            Console.WriteLine(entityState);//Displays Unchanged but expecting Modified
        }
    }
}

```

.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="5.0.4" />
  </ItemGroup>

</Project>

```

**Comment by roji** [comment] 2021-04-06 08:35
I can confirm this repros - and as @clement911 this is due to the equality behavior .NET defines for DateTimeOffset, which doesn't take timezone differences into account.

**Comment by clement911** [comment] 2021-04-06 09:27
Thanks @roji , can this be prioritized for the next release?

**Comment by roji** [comment] 2021-04-07 12:13
@clement911 I've submitted a fix for this. In the meantime you can set up your own value comparer with the right behavior as described [in the docs](https://docs.microsoft.com/en-us/ef/core/modeling/value-comparers?tabs=ef5#overriding-the-default-comparer):

```c#
modelBuilder.Entity<Blog>().Property(b => b.DateTimeOffset)
    .Metadata
    .SetValueComparer(new ValueComparer<DateTimeOffset>(
        (dto1, dto2) => dto1 == dto2 && dto1.Offset == dto2.Offset,
        dto => dto.GetHashCode()));
```

**Comment by clement911** [comment] 2021-04-07 12:29
Awesome. Thanks for the quick fix!

**Closed** 2021-04-08 09:52 UTC
Labels: area-type-mapping, closed-fixed, customer-reported, type-bug
