### ISSUE TITLE
External disconnected entity change tracking system to interact with EF-server

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/efcore#8744] opened 2017-06-06 09:06 UTC
Related to #5536 #4424 #8739

I'd want the entire metadata and tracking system in EF to be extracted to an external non-EF dependent assembly, so to allow change-tracking and interaction with the EF-enabled-server from a non-EF client.

There should also be a minimized graph that efficiently serializes only the necessary data, meaning for added entities: the entire entity, delete entities: the id, for modified, only modified properties along with their values.

For example

Server (get):

    var query = _DbContext
      .Contacts
      .Include(c => c.Phones)
      .Include(c => c.Addresses)
      .Include(c => c.Portfolio)
        .ThenInclude(p => p.Notes);
    return Ok(await query.ToTrackableGraphAsync()); //or wrap graph elsewhere afterwards
    //returns proxy entities that implement an interface including graph metadata

Client:     

Each entity in graph is a proxy class that implements an interface that exposes some change tracking and graph stuff or managed via a centralized EF client tool. Each entity should also have a Guid etc. that goes along the wire regardless of its DB id, so we can identify it regardless of its state.
A serializer will construct the proper `IGraphChangeData` for client/server, or should be a concrete.

    var contacts = await efClient.GetAsync<Contact>();     
    
    //perform changes add, delete, change in any of the graph
    IGraphChangeData data = efClient.GetGraphChanges();
    IGraphChangeResult result = await efClient.SaveAsync(data);
    efClient.RefreshGraph(contacts, result);

Server (put):

    _DbContext.AttachGraph(IGraphChangeData data);
    try { 
      var result = await _DbContext.SaveChangesAsync();
      return Ok(result);

This is so compelling.

**Comment by ErikEJ** [comment] 2017-06-06 10:35
@weitzhandler http://trackableentities.github.io/ (currently not support for EF Core) ?

**Comment by weitzhandler** [comment] 2017-06-06 17:31
@ErikEJ 
That's just that!
It looks like that project isn't maintained. No support for VS 2017 and this compelling project looks a bit neglected.
Would still be nice having this or a similar repo conducted by MS.

**Comment by ErikEJ** [comment] 2017-06-06 17:36
Ping @tonysneed - any comments?

**Comment by weitzhandler** [comment] 2017-06-06 19:53
@ErikEJ 
Have you used it? Sorry for getting a way from the discussion, I hope you can help:

- Can I use Trackable Entities without its T4 templates? What do I have to include in my shared entities (server/client)
- How do I send an entire graph to the server (for instance PUT action), what should the controller action expect?

**Comment by tonysneed** [comment] 2017-06-06 20:31
Hi and thanks for the ping! Yes you absolutely can use TE without the T4 templates.  The server bits just need two properties on an entity: TrackingState enum and ModifiedProperties string array (for partial updates).

The reason for the T4 templates really is for a) convenience and b) on the client to support change tracking.

Hope this helps!

**Comment by weitzhandler** [comment] 2017-06-06 20:43
@tonysneed wow tx for your quick answer.

- How about the client entities? I noticed there is `EntityBase` and `ModelBase`, which of them?
- Still unsure what the pattern of the put action accepting a graph should look like.

**Comment by tonysneed** [comment] 2017-06-06 20:59
EntityBase is what you want on the client. Have a look at the sample in the TE repo: https://github.com/TrackableEntities/trackable-entities/tree/develop/Samples/VS2013/WebApiSample

By the way, the T4 templates are just NuGet packages, so they can be used on their own without the VS extension.

The Put action is quite simple: just call ApplyChanges on the DbContext, passing in the top objects(s) in the graph. See the OrdersController in the sample for all the actions and best practices: https://github.com/TrackableEntities/trackable-entities/blob/develop/Samples/VS2013/WebApiSample/WebApiSample.WebApi/Controllers/OrderController.cs

Cheers,
Tony

**Comment by weitzhandler** [comment] 2017-06-07 02:47
Thank you very much Tony!!!

Would be a great idea adding your project to [.NET foundation](https://dotnetfoundation.org) and draw more community attention to it.

**Comment by tonysneed** [comment] 2017-06-07 02:57
Happy to be of service! Would be great to make it into the .NET Foundation, but I think they are pretty selective. :))

I am working on a port to .NET Standard 2.0. Have been waiting also on an update to the graph API in EF Core v2, which is needed for the TE API, so I'll sync up with that soon.

Cheers,
Tony

**Comment by weitzhandler** [comment] 2017-06-07 04:16
Well [here](https://github.com/dotnet/home/blob/master/guidance/new-projects.md)'s their checklist. I'm sure you've gone that far you'll go that bit more to make it into the dnf...

Should I close this issue?

**Comment by weitzhandler** [comment] 2017-06-07 04:19
Well [here](https://github.com/dotnet/home/blob/master/guidance/new-projects.md)'s their checklist. I'm sure you've gone that far you'll go that bit more to make it into the dnf...

Should I close this issue or keep it open for the reference of for some MS ppl to see it?

And BTW, ([self-quoting](https://github.com/aspnet/EntityFramework/issues/8744#issuecomment-306559924)):

> It looks like that project isn't maintained tho. No support for VS 2017 and this compelling project looks a bit neglected.

Apparently I was utterly wrong...

**Comment by tonysneed** [comment] 2017-06-07 13:25
I'm also planning on a release of the VS extension for VS 2017. That takes some time because of the multi-project templates.

**Comment by ajcvickers** [comment] 2017-06-08 16:54
@tonysneed Curious what APIs you are waiting on?

**Comment by tonysneed** [comment] 2017-06-08 17:25
@ajcvickers It's #7389 Provide access to referencing entity in TrackGraph. Looks like it's in the [2.0.0 milestone](https://github.com/aspnet/EntityFramework/milestone/30).

**Comment by ajcvickers** [comment] 2017-06-08 17:27
@tonysneed Yep, it is. I'll make sure it gets done. 😸 Would be interested to hear any other feedback you have while working on this. New APIs, confusing behaviors, etc.

**Comment by tonysneed** [comment] 2017-06-08 17:43
@ajcvickers Thanks for working on that!  I'll be sure to grab the nightlies and start playing. 😄   Happy to provide feedback on the API's!

**Comment by ajcvickers** [comment] 2017-06-12 19:19
Closing as a dupe of #5536 with a comment there to look at this discussion when implementing.

**Closed** 2022-10-16 11:07 UTC
Labels: closed-duplicate
