### ISSUE TITLE
DefaultIfEmpty causing ArgumentException in left join since 2.1.1

### ISSUE THREAD

**Issue by vladislav-naydenov** [dotnet/efcore#12683] opened 2018-07-16 21:18 UTC
After update of EF Core 2.0 to 2.1.1 the following query started throwing ArgumentException: Expression of type `SmileOn.Models.Localization.Entity.Localization` cannot be used for parameter of type `Microsoft.EntityFrameworkCore.Storage.ValueBuffer`

```
var leftJoin =
                this.DbContext.Localizations.GroupJoin(this.DbContext.LocalizationMissingKeys, ll => new { ll.LKey, ll.SubKey },
                    lmk => new { lmk.LKey, lmk.SubKey }, (ll, left) => new { ll, left })
                    .SelectMany(@t => @t.left.DefaultIfEmpty(new LocalizationMissingKey
                    {
                        LocalizationMissingKeyId = default(int),
                        LKey = @t.ll.LKey,
                        SubKey = @t.ll.SubKey
                    }), (@t, lmk) => new JoinResult
                    {
                        Localization = @t.ll,
                        LocalizationMissingKey = lmk
                    });

            var rightJoin =
                this.DbContext.LocalizationMissingKeys.GroupJoin(this.DbContext.Localizations, lmk => new { lmk.LKey, lmk.SubKey },
                    ll => new { ll.LKey, ll.SubKey }, (lmk, right) => new { lmk, right })
                    .SelectMany(@t => @t.right.DefaultIfEmpty(new Localization
                    {
                        LocalizationId = default(int),
                        LKey = @t.lmk.LKey,
                        SubKey = @t.lmk.SubKey,
                        ValidFrom = default(DateTime),
                        ValidTo = default(DateTime),
                        LocalizationValues = default(ICollection<LocalizationValue>)
                    }), (@t, ll) => new JoinResult
                    {
                        Localization = ll,
                        LocalizationMissingKey = @t.lmk
                    });

			var localizationResultQuery = leftJoin.Union(rightJoin).Select(fj => new LocalizationTempResult
			{
			    LocalizationId = fj.Localization != null ? fj.Localization.LocalizationId : 0,
			    ValidFrom = fj.Localization != null ? (fj.Localization.ValidFrom ?? new DateTime(2012, 1, 1, 0, 0, 0, 0)) : new DateTime(2012, 1, 1, 0, 0, 0, 0),
			    ValidTo = fj.Localization != null ? (fj.Localization.ValidTo ?? new DateTime(9999, 1, 1, 0, 0, 0, 0)) : new DateTime(9999, 1, 1, 0, 0, 0, 0),
			    LKey = fj.Localization != null ? (fj.Localization.LKey ?? fj.LocalizationMissingKey.LKey) : fj.LocalizationMissingKey.LKey,
			    SubKey = fj.Localization != null ? (fj.Localization.SubKey ?? fj.LocalizationMissingKey.SubKey) : fj.LocalizationMissingKey.SubKey
            }).GroupBy(rs => new { rs.LKey, rs.SubKey })
				.GroupJoin(this.DbContext.Localizations, ltr => new { ltr.Key.LKey, ltr.Key.SubKey },
					ll => new { ll.LKey, ll.SubKey },
					(ltr, lls) => new { ltr.Key, lls })
				.SelectMany(@t => @t.lls.DefaultIfEmpty(new Localization
                {
					LocalizationId = default(int),
					LKey = @t.Key.LKey,
					SubKey = @t.Key.SubKey,
					ValidFrom = default(DateTime),
					ValidTo = default(DateTime),
					LocalizationValues = default(ICollection<LocalizationValue>)
				}), (ltr, ll) => new { Localization = ll })
				.GroupJoin(this.DbContext.LocalizationValues.Include(lv => lv.Localization).Include(lv => lv.Language),
					ll => ll.Localization.LocalizationId, lv => lv.Localization.LocalizationId,
					(ll, lv) => new { ll, lv })
				.SelectMany(t => t.lv.DefaultIfEmpty(new LocalizationValue
				{
					LocalizationValueId = default(int),
					LocalizationId = t.ll.Localization.LocalizationId,
					Localization = t.ll.Localization,
					Value = default(string),
					Language = default(Language),
					LanguageId = default(int),
					CreateUser = default(User),
					CreateDateTime = default(DateTime)
				}), (t, lv) => new { t.ll.Localization, LocalizationValue = lv })
				.Select(rs => new LocalizationResultSet
				{
					LKey =
						rs.LocalizationValue.Localization != null
							? rs.LocalizationValue.Localization.LKey
							: rs.Localization.LKey,
					SubKey =
						rs.LocalizationValue.Localization != null
							? rs.LocalizationValue.Localization.SubKey
							: rs.Localization.SubKey,
					LocalizationId = rs.Localization.LocalizationId,
					Language = rs.LocalizationValue.Language,
					ValidFrom = rs.Localization.ValidFrom,
					ValidTo = rs.Localization.ValidTo,
					Value = rs.LocalizationValue.Value,
					CreateDateTime = rs.LocalizationValue.CreateDateTime,
					CreateUser = rs.LocalizationValue.CreateUser
				});
```

Exception message: 
```
System.ArgumentException`: Expression of type `SmileOn.Models.Localization.Entity.Localization` cannot be used for parameter of type `Microsoft.EntityFrameworkCore.Storage.ValueBuffer` of method `System.Collections.Generic.IEnumerable[Microsoft.EntityFrameworkCore.Storage.ValueBuffer] DefaultIfEmpty[ValueBuffer](System.Collections.Generic.IEnumerable[Microsoft.EntityFrameworkCore.Storage.ValueBuffer], Microsoft.EntityFrameworkCore.Storage.ValueBuffer)`
Stack trace:
`System.ArgumentException`: Expression of type `SmileOn.Models.Localization.Entity.Localization` cannot be used for parameter of type `Microsoft.EntityFrameworkCore.Storage.ValueBuffer` of method `System.Collections.Generic.IEnumerable[Microsoft.EntityFrameworkCore.Storage.ValueBuffer] DefaultIfEmpty[ValueBuffer](System.Collections.Generic.IEnumerable[Microsoft.EntityFrameworkCore.Storage.ValueBuffer], Microsoft.EntityFrameworkCore.Storage.ValueBuffer)
   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1)
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleDefaultIfEmpty(EntityQueryModelVisitor entityQueryModelVisitor, DefaultIfEmptyResultOperator defaultIfEmptyResultOperator, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.<>c.<.cctor>b__33_7(EntityQueryModelVisitor v, ResultOperatorBase r, QueryModel q)
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandlerContext.EvalOnClient(Boolean requiresClientResultOperator)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.ResultOperatorBase.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSubQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.LiftSubQuery(IQuerySource querySource, SubQueryExpression subQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.CompileAdditionalFromClauseExpression(AdditionalFromClause additionalFromClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitAdditionalFromClause(AdditionalFromClause fromClause, QueryModel queryModel, Int32 index)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitAdditionalFromClause(AdditionalFromClause fromClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.AdditionalFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SmileOn.Data.Repository.Localizations.LocalizationRepository.SelectLocalizationResultSets(String identifier, String key, String subKey)
   at SmileOn.Data.Repository.Localizations.LocalizationRepository.LoadLocalizations(Int32 pageNumber, Int32 pageSize, String key, String subKey, String identifier)
   at SmileOn.Web.Admin.Controllers.LocalizationController.LoadLocalizationData(DataTableParameters parameters)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NWebsec.AspNetCore.Middleware.Middleware.CspMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.5

**Comment by smitpatel** [comment] 2019-11-21 01:01
Duplicate of #17783

**Closed** 2022-10-16 13:19 UTC
Labels: customer-reported, area-query
