### ISSUE TITLE
Build initialize (Path no recognized)

### ISSUE THREAD

**Issue by wangkanai** [dotnet/efcore#1921] opened 2015-03-27 15:04 UTC
Could anybody help. I'm getting error when trying to build

```
PS D:\Sources\EntityFramework> .\build.cmd
WARNING: Found a KRE_HOME environment variable. This variable has been deprecated and should be removed, or it may interfere with DNVM and the .NET Execution environment
Adding C:\Users\Sarin Na Wangkanai\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5-11380\bin to process PATH
'""C:\Users\Sarin' is not recognized as an internal or external command, operable program or batch file.
```

**Comment by bricelam** [comment] 2015-03-27 16:17
Yikes, looks like a bug for the [aspnet/dnvm](https://github.com/aspnet/dnvm) repo

**Comment by wangkanai** [comment] 2015-03-28 04:30
Well, i had a look at it. is about my username having spaces. I tried hardcore the path, but this script build.bat goes much deeper then it.
```
PS D:\Sources\GitHub\dnvm> .\build
Downloading latest version of NuGet.exe...
'Na' is not recognized as an internal or external command, operable program or batch file.
'.nuget\NuGet.exe' is not recognized as an internal or external command, operable program or batch file.
'.nuget\NuGet.exe' is not recognized as an internal or external command, operable program or batch file.
The system cannot find the path specified.
PS D:\Sources\GitHub\dnvm>
```
if you are asking my %LocalAppData% is as follow
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Sarin Na Wangkanai>%LocalAppData%
'C:\Users\Sarin' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Sarin Na Wangkanai>
```
Sorry for the long name.

**Comment by bricelam** [comment] 2015-03-28 14:48
(Dupe of aspnet/dnvm#190)

**Closed** 2022-10-16 08:53 UTC
