### ISSUE TITLE
Tools: Use launchSettings.json selected profile in Visual Studio Package Manager Console

### ISSUE THREAD

**Issue by KasperLK** [dotnet/efcore#23138] opened 2020-10-29 16:30 UTC
When I use Visual Studio's Package Manager Console to run eg. Update-Database, the EF Tools always uses the connectionstring from appsettings.Development.json instead of the appsettings for the environment specified in the launchSettings.json profile that I have selected in Visual Studio.

**Comment by ajcvickers** [comment] 2020-10-30 21:24
Duplicate of #8695

**Closed** 2022-10-16 19:07 UTC
Labels: closed-duplicate, customer-reported
