### ISSUE TITLE
Scaffolding: Disable skip navigations flag

### ISSUE THREAD

**Issue by Snoopy-hub** [dotnet/efcore#27930] opened 2022-05-02 17:07 UTC
Actually question straight forward - is there a way to disable skip-navigations for ```dotnet-ef``` scaffolding? 
I have support for several versions of DAL layer (netcoreapp3.1, net5.0 and net6.0), already modified scaffolding scenarios to have separate configs per target framework etc. But its very hard right now to deal with skip-navigations as some expected entity types disappeared (as I need them for EF Core Identity support, and it requires to have such an entity type as ```UserRoles```, well anyway this problem is out of question's scope).
If there is no such flag there yet, would be great to have it, because now I'll need to play with Metadata API to remove those automatic model types while configuring ```DbContext```.

Microsoft.EntityFrameworkCore.Design: 6.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio Enterprise 2022

**Comment by ajcvickers** [comment] 2022-05-02 17:12
Duplicate of #26820

**Closed** 2022-10-16 20:33 UTC
Labels: customer-reported
