### ISSUE TITLE
Migrations detect false positive change for numeric properties with default values

### ISSUE THREAD

**Issue by jums** [dotnet/efcore#3004] opened 2015-09-03 21:34 UTC
Adding a new migration detects a change in entity properties that are numeric, `boolean` and `int` at least (string seems unaffected), even though nothing has changed. This leads to the created migration calling `migrationBuilder.AlterColumn(...)` with the old column specs in both Up and Down identically. Gotta manually clean them up every time I create a new migration. 

The problem has been there from beta3 to beta7 at least.

[I made an example of this based on the beta7 starter project](https://github.com/jums/EF7NumericDefaultValueProblem) 

Specifically [this "empty" migration defines the problem](https://github.com/jums/EF7NumericDefaultValueProblem/blob/master/src/EF7BooleanDefaultValue/Migrations/20150903205547_Nothing.cs).

**Comment by smitpatel** [comment] 2015-09-04 00:14
possible dupe of #2802 ?

**Comment by jums** [comment] 2015-09-04 07:49
Yes, seems like the same problem and likely fixed in #2859 for beta8.

**Comment by rowanmiller** [comment] 2015-09-11 18:41
Feel free to reopen if you still see the issue on Beta 8

**Closed** 2022-10-16 09:07 UTC
