### ISSUE TITLE
Exception raised "System.BadImageFormatException: Bad method token", on executing DbCommand.ExecuteReader

### ISSUE THREAD

**Issue by alexjuv** [dotnet/efcore#18967] opened 2019-11-18 07:38 UTC
There is exception raised, and all db communication will be failure unless we restart IIS application pool. The error likes:
Message: Error Desctiption:System.BadImageFormatException: Bad method token.
   at System.Data.Common.DbCommand.ExecuteReader()
   at Repository.Extensions.DbContextExtensions.ExecuteReader(DatabaseFacade facade, String sql, CommandBehavior behavior, SqlParameter[] parameters) in 
.....

### Steps to reproduce
1. Hosting asp.net core application via IIS
2. web.config is using as below:
<aspNetCore processPath="dotnet" arguments=".\AA.ServiceAPI.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout">
3. codes

``` c#
private static DbDataReader ExecuteReader(this DatabaseFacade facade, string sql, CommandBehavior behavior = CommandBehavior.Default, params SqlParameter[] parameters)
        {
            DbDataReader reader = null;
            using (var cmd = facade.GetDbConnection().CreateCommand())
            {
                
                cmd.CommandText = sql;
                if (parameters != null && parameters.Any())
                {
                    cmd.Parameters.AddRange(parameters);
                }
                if (cmd.Connection.State != ConnectionState.Open)
                {
                    cmd.Connection.Open();
                }

                if (behavior == CommandBehavior.Default)
                {
                   // exception raised on this line
                    reader = cmd.ExecuteReader();
                }
                else
                {
                    reader = cmd.ExecuteReader(behavior);
                }
            }
            return reader;
        }
```

### Further technical details

EF Core version: 2.2.6
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET Core 2.2.5/2.2.7
(on server, there are .net core 2.1.6 installed as well)
Operating system: Microsoft Windows Server 2012 R2 Standard

**Comment by ErikEJ** [comment] 2019-11-18 16:39
No EF Core code seems to be involved here?

**Comment by ajcvickers** [comment] 2019-11-18 19:51
@alexjuv This often indicates a mismatch between 32-bit and 64-bit assembly usage. Please check that the machine architecture is consistent throughout the solution and deployment.

**Comment by ajcvickers** [comment] 2019-11-25 17:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:56 UTC
Labels: closed-could-not-reproduce, customer-reported
