### ISSUE TITLE
Required-to-optional (one-to-zero or one-to-one) relationships - not supported/bug?

### ISSUE THREAD

**Issue by kierenj** [dotnet/efcore#6466] opened 2016-09-03 07:22 UTC
Apologies if I've just misunderstood - trying to get the EF Core version of https://msdn.microsoft.com/en-us/data/jj591620.aspx#RequiredToOptional I think.
### Steps to reproduce

``` c#
public class Main
{
    public Guid Id { get; set; }
    public string Something { get; set; }
    public MoreDetail OptionalDetail { get; set; }
}

public class MoreDetail
{
    public Guid MainId { get; set; }
    public Main Main { get; set; }
    public string MoreInfo { get; set; }
}

// model building code:

mainBuilder.HasOne(m => m.OptionalDetail).WithOne(d => d.Main).IsRequired(false);`
```
### The issue

Intended:
- MoreDetail is an optional 'child' table of Main
- The primary key would be MainId; it doesn't need its own ID

Actual:
- `The entity type 'Main' requires a key to be defined.`

Attempted:
- Adding `moreDetailBuilder.HasKey(d => d.MainId)`. Yields the same error.
- Adding `.HasForeignKey<MoreDetail>(d => d.MainId)` to Main model builder code. Gives `The foreign key {'MainId'} on entity type 'MoreDetail' cannot be marked as optional because it does not contain any property of a nullable type. Any foreign key can be marked as required, but only foreign keys with at least one property of a nullable type and which is not part of primary key can be marked as optional.`.

```
Exception message: System.InvalidOperationException: The entity type 'Main' requires a key to be defined.
Stack trace:
   at Microsoft.EntityFrameworkCore.Internal.ModelValidator.ShowError(String message)
   at Microsoft.EntityFrameworkCore.Internal.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.Execute(CommonOptions commonOptions, String name, String outputDir, String context, String environment, Action`1 reporter)
   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
```
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 10 1511
Visual Studio version: n/a commandline

**Comment by kierenj** [comment] 2016-09-03 14:55
I also just tried `IsRequired(true)`, which works - mostly - until it comes to query time.  I can create a "main" entity with or without a child, but at query time it generates an `INNER JOIN` and so no results are returned.

Is this just not supported?  Is there a viable workaround?

**Comment by ajcvickers** [comment] 2016-09-06 16:32
@kierenj It seems that you want to do two conflicting things:
* You want the relationship to be optional. This means that the FK must be nullable.
* You don't want child entity to have a separate FK property. This means that the FK property is also the PK property, and PKs can not be nullable.

It maybe that the meaning of an "optional" relationship is not clear in the case of 1:1 relationships. An optional relationship means that the child (MoreDetail in your case) can exist without any parent entity. This is represented by child having a null FK, indicating that it is not related to any parent.

Conversely, a "required" relationship means that if the child exists, then a parent must also exist. This is enforced by making the FK non-nullable and then by both EF and the relational database asserting that the value of this FK matches some PK value of the parent entity.

Note that neither optional or required relationships say anything about whether or not a child entity exists for for any parent entity. Regardless of the relationship type it is valid to have a parent entity without any related child entity.

**Comment by kierenj** [comment] 2016-09-06 17:10
Thanks for the reply!  I tried making the relationship "required", but EF generated an INNER JOIN to the child entity, meaning queries are generated which mean the child entity is always required.  That seems to be contradictory to your final statement?

**Comment by divega** [comment] 2016-09-06 17:34
@kierenj can you post the query? You could be hitting https://github.com/aspnet/EntityFramework/issues/6177, which should be fixed in nightly builds.

**Comment by divega** [comment] 2016-09-07 18:22
Closing as dupe of #6177.

**Closed** 2022-10-16 09:56 UTC
Labels: closed-duplicate
