### ISSUE TITLE
Add-Migration Does Nothing

### ISSUE THREAD

**Issue by elmojo** [dotnet/efcore#10485] opened 2017-12-05 19:57 UTC
I added Microsoft.EntityFrameworkCore.Tools to my project, used the Package Manager Console, selected the Default Project which contains my context and typed "Add-Migration Initial".

Nothing happens, I just get a new command prompt, nothing is created, no error messages displayed.

**Comment by smitpatel** [comment] 2017-12-05 20:02
Possible duplicate of #10298 
Can you share details of dotnet/ef tools versions? Project type?

**Comment by elmojo** [comment] 2017-12-05 20:32
Microsoft.EntityFrameworkCore.Tools v2.0.1
.NET Core v.2.0.0
Project Type: class library .NET Core

**Comment by elmojo** [comment] 2017-12-05 20:36
Adding the work around line "<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>" mentioned in #10298 to the project file got me an error message finally (cannot find appsettings.json).

**Comment by elmojo** [comment] 2017-12-05 20:40
Another issue noticed though, I have to have the project with the DatabaseContext selected as the startup project in order to get the migration tool to not fail with a "could not load assembly" error.  I've never needed to do this in the past.

**Comment by dmuino1986** [comment] 2018-03-23 05:51
i got the same issue please can anyone help me?

**Comment by bricelam** [comment] 2018-03-23 16:52
@dmuino1986 Update EF Core pacakges to version 2.0.2.

**Comment by dmuino1986** [comment] 2018-03-24 15:41
thanks bricelam it work

**Closed** 2022-10-16 12:02 UTC
