### ISSUE TITLE
Error update entity

### ISSUE THREAD

**Issue by JonathanUzcateguiG** [dotnet/efcore#12282] opened 2018-06-07 15:39 UTC
Describe what is not working as expected.

I am making a unit test of the method UPDATE  of my business class. To do this test first I get an entity modified and I try to update it, but it gives an error.

```
Exception message:

System.InvalidOperationException: The instance of entity type 'Person' cannot be tracked because another instance with the same key value for {'ID'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging'
```
in the methodById I use AsNoTracking
```C#
   public T FindById(long id)
        {
            return dbSet.AsNoTracking().FirstOrDefault<T>(x => x.ID == id);
          
        }
```
and dbset is loaded from is controcutor
```C#
  private readonly DbContext context;
        private readonly DbSet<T> dbSet;
        //  private DbSet<T> myEntity;

        public BaseRepository(DbContext dbContext)
        {
            context = dbContext;
            this.dbSet = context.Set<T>();
            
        }
```
### Steps to reproduce
run the test

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE:  Visual Studio 2017 15.3

**Comment by smitpatel** [comment] 2018-06-07 20:30
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2018-06-15 16:55
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:29 UTC
Labels: closed-could-not-reproduce, customer-reported
