### ISSUE TITLE
Expression with casting can't be translated after porting from EF6

### ISSUE THREAD

**Issue by dglozano** [dotnet/efcore#24416] opened 2021-03-16 16:32 UTC
We have ported an existing application from EF6 to EF Core 3.1. In the process of doing so, we came across a situation in which a query that was previously working now fails at runtime because it contains an `Expression` that can't be translated.
 
```
public class Task : SqlUserUpdatableSequenceBase
{
    ...

    public override Expression<Func<TEntity, bool>> GetSameSequencePredicate<TEntity>()
        => entity => (entity as Task).ProjectId == ProjectId;

    ...
}
```

```
private List<ItemSequence> UpdateSequenceInternal<TEntity>(TEntity entity, ItemSequence sequence)
            where TEntity : SqlUserUpdatableSequenceBase
        {
           ...

            var query = Context.Set<TEntity>().AsQueryable();
            query = query.Where(entity.GetSameSequencePredicate<TEntity>());

           ...
        }
```

So it seems that the cast `(entity as Task)` in the Expression is what cannot be translated by EF Core.

I had previously managed to get around it by adding a type to `SqlUserUpdatableSequenceBase<T>` like this:

```
public class Task : SqlUserUpdatableSequenceBase<Task>
{
    ...

     public override Expression<Func<Task, bool>> GetSameSequencePredicate()
            => x => x.ProjectId == ProjectId;
    ...
}
       
```

But since that approach limit us a bit, I was still wondering if it is possible to rewrite such expression so that the casting would be successfully translated by EF Core.

### Include provider and version information
EF Core version: 3.1.7
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)

**Comment by smitpatel** [comment] 2021-03-16 17:09
Can you provide a full repro and what exception it throws? We believe that normal `as` operator works as long as you access a mapped property right after.

**Comment by dglozano** [comment] 2021-03-16 20:51
Will work on creating a reproducible case and be back to you, thanks.

**Comment by ajcvickers** [comment] 2021-03-26 14:46
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:28 UTC
Labels: closed-could-not-reproduce, customer-reported
