### ISSUE TITLE
Design: Failure when UseMiddleware(args) is used

### ISSUE THREAD

**Issue by zugzwangm** [dotnet/efcore#10502] opened 2017-12-07 02:25 UTC
`dotnet ef migrations list`  (and possibly other commands) fails when Startup.Configure() adds a Middleware with `app.UseMiddleware<MyMiddleware>(args)`. **The app works flawlessly while running normally.**

Workaround is to avoid using `param object[] args` when calling UseMiddleware(), and inject everything through DI.

```
Application startup exception: System.InvalidOperationException: A suitable constructor for type 'MyProject.Web.MasterServer.WebSocketManager.WebSocketManagerMiddleware' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.MapExtensions.Map(IApplicationBuilder app, PathString pathMatch, Action`1 configuration)
   at MyProject.Web.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, IServiceProvider serviceProvider, ILoggerFactory loggerFactory, IAntiforgery antiforgery) in D:\...\Startup.cs:line 234
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
[2017-12-07 02:12:13] crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
                            Application startup exception
System.InvalidOperationException: A suitable constructor for type 'MyProject.Web.MasterServer.WebSocketManager.WebSocketManagerMiddleware' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.MapExtensions.Map(IApplicationBuilder app, PathString pathMatch, Action`1 configuration)
   at MyProject.Web.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, IServiceProvider serviceProvider, ILoggerFactory loggerFactory, IAntiforgery antiforgery) in D:\...\Startup.cs:line 234
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider. Error: A suitable constructor for type 'MyProject.Web.MasterServer.WebSocketManager.WebSocketManagerMiddleware' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
Unable to create an object of type 'ApplicationDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<ApplicationDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.
PM> dotnet ef migrations list
```
### Further technical details
EF Core version: 2.0
Operating system: Win10
IDE: Visual Studio 2017 15.4.5

**Comment by bricelam** [comment] 2017-12-08 17:11
Is there an argument it's expecting to be present? Maybe it's specified in `launchSettings.json`... (see #8695)

**Comment by bricelam** [comment] 2017-12-13 17:37
I wonder if this has been mitigated in 2.1 by aspnet/Hosting#1263

**Comment by ajcvickers** [comment] 2017-12-13 20:10
@divega Note: update forward link in message.

**Comment by hscanlan** [comment] 2017-12-31 18:01
How do you actually fix this problem? I have the exact same thing when trying to migrate. But when I run my app, it works perfectly fine.

What am I missing here?

**Comment by bricelam** [comment] 2018-01-22 17:40
@zugzwangm @hscanlan Do you have a repro project I can use to dig into this?

**Comment by bricelam** [comment] 2018-01-22 20:41
I'm not able to repro this with the information provided. Here's what I tried:

``` csharp
app.UseMiddleware<MyMiddleware>(new MyDependency());
```

``` csharp
class MyMiddleware
{
    public MyMiddleware(RequestDelegate next, MyDependency dependency)
    {
    }

    public Task Invoke(HttpContext httpContext)
        => Task.CompletedTask;
}

class MyDependency
{
}
```

**Comment by cobrafast** [comment] 2018-01-24 03:35
I'm stuck with this too.

The only difference I can see, is that I use `serviceProvider.GetService<MyDependency>()` to retrieve the instance passed to the middleware, because in my case `MyDependency` has dependencies of its own that I want to have handled by dependency injection (which works fine during runtime).  
The service was previously set during `ConfigureServices` as a singleton.

Perhaps if you change your attempt to the following (which is quite close to what I'm actually using) you can reproduce it (I did not try it this isolated though).  

```csharp
services.AddSingleton(typeof(MyOtherDependency));
services.AddSingleton(typeof(MyDependency));
```

```csharp
app.UseMiddleware<MyMiddleware>(serviceProvider.GetService<MyDependency>());
```

```csharp
class MyMiddleware { /* (snip) (use your code) */ }
class MyDependency
{
	public MyDependency(MyOtherDependency dep, IServiceScopeFactory ssf)
	{ }
}
class MyOtherDependency { }
```

**Comment by cobrafast** [comment] 2018-01-24 05:09
Seems like a workaround is to comment out the offending `app.UseMiddleware(...)` call, do the migration, and comment back in.

**Comment by bricelam** [comment] 2018-01-24 17:10
Still not able to repro it. Let me know if you can isolate the issue.

**Comment by ajcvickers** [comment] 2018-02-02 17:24
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:02 UTC
Labels: closed-could-not-reproduce
