### ISSUE TITLE
Unable to set a property to null with lazy loading enabled

### ISSUE THREAD

**Issue by arabasso** [dotnet/efcore#21287] opened 2020-06-16 12:31 UTC
I'm running the following code:

```
...
var customer = context.Find<Customer>(viewModel.CustomerId);

if (viewModel.StatusId == 0)
{
    customer.Status = null;
}

else
{
    customer.Status = context.Find<CustomerStatus>(viewModel.StatusId);
}

context.Update(customer);
context.SaveChanges();
...
```
Does not work. It only works if I explicitly load the property:

```
var customer = context.Find<Customer>(viewModel.CustomerId);

context.Entry(customer).Reference(m => m.Status).Load();

if (viewModel.StatusId == 0)
{
    customer.Status = null;
}

else
{
    customer.Status = context.Find<CustomerStatus>(viewModel.StatusId);
}

context.Update(customer);
context.SaveChanges();
```

### Steps to reproduce

- Enable lazy loading with `UseLazyLoadingProxies`

### Further technical details

EF Core version: 3.1.5
Database provider: Pomelo.EntityFrameworkCore.MySql or MySql.Data.EntityFrameworkCore
Target framework: .NET Core 3.1
Operating system: Windows 10 Pro 2004
IDE: Visual Studio 2019 16.6.2

**Comment by ajcvickers** [comment] 2020-06-16 15:20
Duplicate of #14086

**Closed** 2022-10-16 18:29 UTC
Labels: customer-reported
