### ISSUE TITLE
Add a check in specification tests suite to help providers discover missing implementations

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#11210] opened 2018-03-09 12:39 UTC
In order to help providers discover new features, (that will have new specification tests), add some kind of check in the spec test to warn consumers of the spec test that it has not been implemented.

@ajcvickers @AndriySvyryd 

//cc @cincuranet @roji @caleblloyd 

(Feel free to close if this is a duplicate)

**Comment by roji** [comment] 2018-03-09 16:19
Duplicate of #10934?

**Comment by ErikEJ** [comment] 2018-03-09 16:27
Indeed!

**Closed** 2022-10-16 12:12 UTC
