### ISSUE TITLE
#An operation was scaffolded that may result in the loss of data. Please review the migration for accuracy.

### ISSUE THREAD

**Issue by RagabMohamedRagab** [dotnet/efcore#25794] opened 2021-08-30 21:36 UTC
# Deleting All Migration In your Solution in VS And Database Name in SSMS

- [ ]  Starting From The Begin

- [ ]  Add-Migration "NameOfMigration"

- [ ]   Update-Database -Verbose

_Originally posted by @ragabmoh2ooo in https://github.com/dotnet/efcore/issues/16684#issuecomment-908716774_

**Comment by ajcvickers** [comment] 2021-08-31 07:30
@ragabmoh2ooo Can you explain a bit more what exactly your problem or question is?

**Comment by ajcvickers** [comment] 2021-09-07 11:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:44 UTC
Labels: closed-no-further-action, customer-reported

**Comment by AKANS22** [comment] 2023-10-21 19:06
I am having the same error too

**Comment by roji** [comment] 2023-10-22 11:26
@AKANS22 please open a new issue with a full, runnable repro. There's not enough information above for us to understand what's going on.
