### ISSUE TITLE
Relationalship is not discovered if NotMappedAttribute is used on one navigation

### ISSUE THREAD

**Issue by danielkaczmarek** [dotnet/efcore#18335] opened 2019-10-11 11:47 UTC
Container can have many ContainerOccupant.  ContainerOccupant can occupy many containers. This second list needs to be NotMapped because we run custom logic to fill it in. In EF 6 we simply set the NavigationProperty to be NotMapped and it works, in EF Core it does not work. It tells me to use NotMapped or Ignore while its already marked as NotMapped.

### Steps to reproduce
    
    public class Container : AbstractAudit
    {
        public int ContainerId { get; set; }
        public IList<ContainerOccupant> ContainerOccupants { get; set; }
    }

    public class ContainerOccupant
    {
        public int ContainerOccupantId { get; set; }

        [NotMapped]
        public IList<Container> OtherOccupiedContainers { get; set; }
    }

### Further technical details

EF Core version: 3.0
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (.NET Core 3.0)
Operating system:
IDE: (Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment] 2019-10-14 20:23
Note for triage: validated that this repros in 3.0.

**Comment by smitpatel** [comment] 2019-10-21 20:31
The issue is not `NotMappedAttribute` here. It is collection navigation on both sides. So we don't create relationship. Later when the ambiguity is resolved due to `NotMapped` we did not discover relations again. Duplicate of #18388

If `ContainerOccupant` is discovered before `Container` then it works.

Manual work-around:
```C#
modelBuilder.Entity<Container>().HasMany(e => e.ContainerOccupants);
```

**Comment by smitpatel** [comment] 2019-10-21 20:32
Duplicate of #18388

**Closed** 2022-10-16 14:49 UTC
Labels: closed-duplicate, customer-reported
