### ISSUE TITLE
Database Migration from 2.2 -> 3.1 when changing DeleteBehaviour.Restrict -> DeleteBehaviour.ClientNoAction generates migration where foreign keys are dropped and recreated

### ISSUE THREAD

**Issue by GoksuAkin** [dotnet/efcore#21071] opened 2020-05-28 17:37 UTC
We were expecting not to have any migrations at all.

### Steps to reproduce

<!--
What steps can we follow to reproduce the issue?
You can replace the framework references between 2.2.6 and 3.1.0 :) 
We ❤ code! Include a complete code listing or attach a simplified project

[DBMigrationRepro.zip](https://github.com/dotnet/efcore/files/4697315/DBMigrationRepro.zip)
I attached the repro example solution hope it helps !

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by roji** [comment] 2020-05-28 22:04
@GoksuAkin can you please post a runnable code sample with clear instructions on how to reproduce the error? It's not really possible for us to investigate without that.

**Comment by ajcvickers** [comment] 2020-06-08 16:02
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:27 UTC
Labels: closed-could-not-reproduce, customer-reported
