### ISSUE TITLE
How to override specific fluent configuration

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#17908] opened 2019-09-18 12:31 UTC
I am deriving a `DbContext` from this `IdentityDbContext` which as you can see, configures a Unique Index for role names:

https://github.com/aspnet/AspNetCore/blob/6e35229b015f0164c0876e2f6dc051409b1d1390/src/Identity/EntityFrameworkCore/src/IdentityDbContext.cs#L131

In my derived `DbContext` I want to keep the base model configuration - except I don't want to keep the Unique index because I don't want role names to be unique - I want Rolename + Tenant Id to be unique.

So I thought I'd reconfigure that entity:

```csharp

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder); // base class configures some stuff
 
          // we don't like the role configuration applied by default, namely the unique index so tweak that
           builder.Entity<Role>(b =>
            {
                b.HasKey(r => r.Id);
                b.HasIndex(nameof(Role.NormalizedName), TenantIdPropertyName).HasName("RoleNameIndex").IsUnique();             

            });
```

However this doesn't work because it seems my index is additive - the index configured by the base class is still active. For example when I use `dotnet ef` to generate migrations it fails with the following error:

> dotnet ef migrations add InitialCreate --startup-project ../Hub.Server --project ..\Hub.Data\Hub.Data.csproj --configuration Release
System.InvalidOperationException: The indexes {'NormalizedName', 'TenantId'} on 'Role' and {'NormalizedName'} on 'Role' are both mapped to 'Role.RoleNameIndex' but with different columns ({'NormalizedName', 'TenantId'} and {'NormalizedName'}).
   at Microsoft.EntityFrameworkCore.Metadata.Internal.IndexExtensions.AreCompatible(IIndex index, IIndex duplicateIndex, Boolean shouldThrow)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedIndexesCompatibility(IReadOnlyList`1 mappedTypes, String tableName)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.Validate()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_2(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The indexes {'NormalizedName', 'TenantId'} on 'Role' and {'NormalizedName'} on 'Role' are both mapped to 'Role.RoleNameIndex' but with different columns ({'NormalizedName', 'TenantId'} and {'NormalizedName'}).

So my question is, is there a way using fluent configuration to override / remove / amend a previoulsy configured entity - in my particular case - that unique index?

**Comment by dazinator** [comment] 2019-09-18 12:46
I ended up creating the following extension method to remove a particular index. But I feel there should be a way to clear any configuration for an entire entity so that it can be reconfigured from scratch perhaps.

The method I came up with after exploring the api briefly:

```
       private void RemoveIndex<TEntity>(ModelBuilder builder, string propertyName)
        {
            var entityTypeModel = builder.Model.FindEntityType(typeof(TEntity));
            var prop = entityTypeModel.GetProperty(propertyName);
            entityTypeModel.RemoveIndex(new[] { prop });
        }

```

Usage:


```csharp

         // The base class configured roles pretty well, except we need to customise the index.
         RemoveIndex<Role>(builder, nameof(Role.NormalizedName));

            builder.Entity<Role>(b =>
            {              
                b.HasIndex(nameof(Role.NormalizedName), TenantIdPropertyName).HasName("RoleNameIndex").IsUnique();
              
            });

```

**Comment by AndriySvyryd** [comment] 2019-09-19 03:09
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/7605

**Closed** 2022-10-16 14:43 UTC
Labels: closed-duplicate, customer-reported
