### ISSUE TITLE
ExecuteUpdateAsync in EF Core: set property based on Logic throws InvalidOperation Exception

### ISSUE THREAD

**Issue by AhmedElbatt** [dotnet/efcore#30119] opened 2023-01-23 16:02 UTC
### Include your code

Usually the best way to ask a clear question and get a quick response is to show your code. Preferably, attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

For example:

```C#
var xx = await _context.WebidPersons.ExecuteUpdateAsync(x => x.SetProperty(a => a.EmployeeInfo, x => x.EmployeeInfo.ReturnAsEncrypted());

```
The extension method I want to implement is basically like that:
```C#

  public static string ReturnAsEncrypted(this string value)
  {
     // logic that encrypt the EmployeeInfo
  }
```
The output is an exception : System.InvalidOperationException the expression could not be translated. Additional information: The following lambda argument to 'SetProperty' does not represent a valid property to be set: 'x => x.EmployeeInfo.ReturnAsEncrypted'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
  Source=Microsoft.EntityFrameworkCore.Relational

**Comment by ajcvickers** [comment] 2023-01-24 18:50
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-02-08 19:48
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-02-08 19:48 UTC
Labels: customer-reported
