### ISSUE TITLE
Evaluate obsolete APIs from 2.2 and consider removing them in 3.0.0

### ISSUE THREAD

**Issue by Eilon** [dotnet/efcore#14559] opened 2019-01-30 21:37 UTC
Here's everything marked obsolete in 'master' in this repo. Please use the links below to compare master and release/2.2 to see if this is a pre-existing obsolete message for a member that can now be deleted. For each item consider whether to log a bug because we will take an action, and then check the checkbox to mark it as done (even if there's no further action).

#### (1) src\EFCore.Relational\Storage\RelationalTypeMapping.cs
Links: <a href="https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/Storage/RelationalTypeMapping.cs#L131">[master]</a> | <a href="https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/src/EFCore.Relational/Storage/RelationalTypeMapping.cs#L131">[release/2.2]</a>
[File a bug for this](https://github.com/aspnet/EntityFrameworkCore/issues/new?body=Remove%20this%20obsolete%20member%20in%20%28src%2FEFCore.Relational%2FStorage%2FRelationalTypeMapping.cs%29%5Bhttps%3A%2F%2Fgithub.com%2Faspnet%2FEntityFrameworkCore%2Fblob%2Fmaster%2Fsrc%2FEFCore.Relational%2FStorage%2FRelationalTypeMapping.cs%23L131%5D%3A%0D%0A%0D%0A%60%60%60c%23%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%5BObsolete%28%22This%20is%20provided%20for%20compatibility%20with%202.1%20providers%20and%20shouldn%27t%20be%20used%22%29%5D%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20public%20bool%20PrecisionAndScaleOverriden%20%7B%20get%3B%20%7D%0D%0A%0D%0A%60%60%60%0D%0A%0D%0AAnd%20file%20a%20new%20issue%20in%20https%3A%2F%2Fgithub.com%2Faspnet%2FAnnouncements%2Fissues%2F%20if%20this%20is%20a%20notable%20breaking%20change.%0D%0A&labels=breaking-change&title=Remove%20obsolete%20member%20in%20src/EFCore.Relational/Storage/RelationalTypeMapping.cs&milestone=3.0.0-preview3)
* [ ] I attest that I have taken appropriate action on this item

```c#
            [Obsolete("This is provided for compatibility with 2.1 providers and shouldn't be used")]
            public bool PrecisionAndScaleOverriden { get; }

```

---

#### (2) test\EFCore.Specification.Tests\TestUtilities\Xunit\SkippedTestCase.cs
Links: <a href="https://github.com/aspnet/EntityFrameworkCore/blob/master/test/EFCore.Specification.Tests/TestUtilities/Xunit/SkippedTestCase.cs#L22">[master]</a> | <a href="https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/test/EFCore.Specification.Tests/TestUtilities/Xunit/SkippedTestCase.cs#L22">[release/2.2]</a>
[File a bug for this](https://github.com/aspnet/EntityFrameworkCore/issues/new?body=Remove%20this%20obsolete%20member%20in%20%28test%2FEFCore.Specification.Tests%2FTestUtilities%2FXunit%2FSkippedTestCase.cs%29%5Bhttps%3A%2F%2Fgithub.com%2Faspnet%2FEntityFrameworkCore%2Fblob%2Fmaster%2Ftest%2FEFCore.Specification.Tests%2FTestUtilities%2FXunit%2FSkippedTestCase.cs%23L22%5D%3A%0D%0A%0D%0A%60%60%60c%23%0D%0A%20%20%20%20%20%20%20%20%5BObsolete%28%22Called%20by%20the%20de-serializer%3B%20should%20only%20be%20called%20by%20deriving%20classes%20for%20de-serialization%20purposes%22%29%5D%0D%0A%20%20%20%20%20%20%20%20public%20SkippedTestCase%28%29%0D%0A%20%20%20%20%20%20%20%20%7B%0D%0A%60%60%60%0D%0A%0D%0AAnd%20file%20a%20new%20issue%20in%20https%3A%2F%2Fgithub.com%2Faspnet%2FAnnouncements%2Fissues%2F%20if%20this%20is%20a%20notable%20breaking%20change.%0D%0A&labels=breaking-change&title=Remove%20obsolete%20member%20in%20test/EFCore.Specification.Tests/TestUtilities/Xunit/SkippedTestCase.cs&milestone=3.0.0-preview3)
* [ ] I attest that I have taken appropriate action on this item

```c#
        [Obsolete("Called by the de-serializer; should only be called by deriving classes for de-serialization purposes")]
        public SkippedTestCase()
        {
```

---

**Comment by ajcvickers** [comment] 2019-02-04 17:38
Top one is a duplicate of #12405. Second one is by-design in test to stop this constructor being called accidentally.

**Closed** 2022-10-16 13:49 UTC
Labels: closed-duplicate
