### ISSUE TITLE
Generic EF.Property usage throws InvalidOperationException

### ISSUE THREAD

**Issue by kyubisation** [dotnet/efcore#3837] opened 2015-11-21 20:06 UTC
I'm not quite sure whether this is a bug or just something I have to live with.

Trying to use EF.Property in a generic model usage throws a InvalidOperationException (System.InvalidOperationException : The EF.Property<T> method may only be used within LINQ queries.)

See FailingGenericFilterTest in the EfTest example class.

```
Test Name:  EfTest.FailingGenericFilterTest
Test FullName:  EfTest.EfTest.FailingGenericFilterTest
Test Source:    ...\EfTest\src\EfTest\EfTest.cs : line 35
Test Outcome:   Failed
Test Duration:  0:00:00.523

Result StackTrace:  
at Microsoft.Data.Entity.EF.Property[TProperty](Object entity, String propertyName)
   at lambda_method(Closure , Model )
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_1`1.<CompileQuery>b__1(QueryContext qc)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at EfTest.EfTest.FailingGenericFilterTest() in ...\EfTest\src\EfTest\EfTest.cs:line 37
Result Message: The EF.Property<T> method may only be used within LINQ queries.
```
### Minimal repro steps

Use the following project.json and class and run the xunit tests.

``` javascript
{
  "projects": [ "src" ],
  "sdk": {
    "version": "1.0.0-rc1-final"
  }
}
```

``` c#
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.Data.Entity;
using Xunit;

namespace EfTest
{
    public delegate IQueryable<TModel> Filter<TModel>(IQueryable<TModel> queryable, string filter);

    public class EfTest : IDisposable
    {
        private readonly TestContext _context;

        public EfTest()
        {
            _context = new TestContext();
        }

        public void Dispose()
        {
            _context.Database.EnsureDeleted();
            _context.Dispose();
        }

        [Fact]
        public void WorkingFilterTest()
        {
            var filter = (Filter<Model>)
                ((q, f) => q.Where(m => EF.Property<string>(m, nameof(Model.Name)) == f));
            Assert.Equal(1, filter(_context.Set<Model>(), "Test1").Count());
        }

        [Fact]
        public void FailingGenericFilterTest()
        {
            var filter = GenericFilter<Model>();
            Assert.Equal(1, filter(_context.Set<Model>(), "Test1").Count());
        }

        private Filter<TModel> GenericFilter<TModel>()
        {
            return (q, f) => q.Where(m => EF.Property<string>(m, nameof(Model.Name)) == f);
        }
    }

    public sealed class TestContext : DbContext
    {
        public TestContext() : base(new OptionBuilder().Options)
        {
            Add(new Model { Name = "Test1" });
            Add(new Model { Name = "Test2" });
            SaveChanges();
        }

        public DbSet<Model> Models { get; set; }

        private class OptionBuilder : DbContextOptionsBuilder<TestContext>
        {
            public OptionBuilder()
            {
                this.UseInMemoryDatabase();
            }
        }
    }

    public class Model
    {
        [Key]
        public string Name { get; set; }
    }
}
```

``` javascript
{
  "version": "1.0.0-*",

  "dependencies": {
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.InMemory": "7.0.0-rc1-final",
    "xunit": "2.1.0",
    "xunit.runner.dnx": "2.1.0-rc1-build204"
  },

  "commands": {
    "test": "xunit.runner.dnx"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
      }
    }
  }
}
```

**Comment by VismaCommerce** [comment] 2015-12-10 08:15
Has there been any progress regarding the investigation of this bug? We have started running into it, seemingly just by installing the 1.0.0-rc1-update1 from get.asp.net.

**Comment by divega** [comment] 2016-03-22 01:36
@kyubisation @VismaCommerce I believe I have just hit the same issue independently and it still repros in the latest bits. See #4875. 

In the meanwhile you can try adding a generic constraint to the generic filter methods, e.g. for the example above:

``` C#
        private Filter<TModel> GenericFilter<TModel>() where TModel: class
        {
            return (q, f) => q.Where(m => EF.Property<string>(m, nameof(Model.Name)) == f);
        }
```
This should prevent the compiler from introducing the unnecessary cast that is causing EF not to be able to recognize the call.

**Comment by divega** [comment] 2016-03-22 01:46
Closing in favor of #4875 just because there is some more information about the causes in that bug. @kyubisation @VismaCommerce thanks for the heads up on this.

**Closed** 2022-10-16 09:17 UTC
