### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by avechuche** [dotnet/efcore#26757] opened 2021-11-18 23:11 UTC
I have the following SP and I want to call it from "FromSqlRaw". The problem is that I get the following error, I already know why it is (properties with the same name) but each one has its table alias and I don't know why it doesn't work. Is this a limitation / bug or is it my problem? 

SP:
https://pastebin.com/dWp8ZJyc

```
An item with the same key has already been added. Key: EntityID
System.ArgumentException: An item with the same key has already been added. Key: EntityID
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.BuildIndexMap(IReadOnlyList`1 columnNames, DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

### Include provider and version information

EF Core version: 5.0.11
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: W10
IDE: Visual Studio 2019 16.11.5

**Comment by adil-portable** [comment] 2021-11-21 14:04
When you run this query it will give you the same column names even though you have provided the different table alias. You need to provide different column names to make it work. For example i.type as IType.

**Comment by ajcvickers** [comment] 2021-11-22 19:48
@avechuche When you return create instances of entities with a key from a tracking query, then each instance must have a unique key. Using a no-tracking query will avoid this problem.

**Comment by avechuche** [comment] 2021-11-23 17:26
@ajcvickers Hi, I already tried that, but it still doesn't work :(

**Comment by ajcvickers** [comment] 2021-11-23 17:27
@avechuche Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by adil82pk** [comment] 2021-11-24 04:10
try using the below code in the startup file  
services.AddScoped(provider =>
            {
                var optionsBuilder = new DbContextOptionsBuilder<DbContext>();
                var options = optionsBuilder.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking).Options;
}

or after you call SP
IQueryable<T> query = ....;
query.AsNoTracking().ToList()

**Comment by avechuche** [comment] 2021-11-30 12:34
@adil82pk @ajcvickers   Sorry for the delay. 
@adil82pk This does not work, I tried it before and the error persists. 

Maybe it's my mistake. I'm trying to get the following: A list of items, with their respective last moves. Is it possible to do that with "FromSqlRaw"? 

```
public class ItemSP
{
	public string EntityID { get; set; }
	
	...

	public List<MovementsSP> Movements { get; set; }
}

public class MovementsSP
{
	public string EntityID { get; set; }
	
	public decimal Balance { get; set; }

	...
}
```

`_databaseContext.Set<ItemSP>().FromSqlRaw("SP_MYSP {0}", "MY_PARAMETER").ToList();`

**Comment by ajcvickers** [comment] 2021-12-03 12:18
@avechuche Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2021-12-14 16:25
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:15 UTC
Labels: closed-could-not-reproduce, customer-reported
