### ISSUE TITLE
EF & MAUI Android Release - Format of the initialization string does not conform to specification starting at index 0

### ISSUE THREAD

**Issue by Igor-9309** [dotnet/efcore#32553] opened 2023-11-15 19:58 UTC
### Description

But I have discovered that my application runs successfully with EFCore-SQLite only in debug.
Whenever I publish for android then crash at startup.

EFCore version: 8.0.0
MAUI version: 8.0.3

```
android.runtime.JavaProxyThrowable: [System.ArgumentNullException]: ArgumentNull_Generic Arg_ParamName_Name, source
	at System.Linq.ThrowHelper.ThrowArgumentNullException(Unknown Source:0)
	at System.Linq.Enumerable.All(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValueGenerationConvention.GetValueGenerated(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.RelationalValueGenerationConvention.GetValueGenerated(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.RelationalValueGenerationConvention.GetValueGenerated(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValueGenerationConvention.ProcessEntityTypePrimaryKeyChanged(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+ImmediateConventionScope.OnEntityTypePrimaryKeyChanged(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+OnEntityTypePrimaryKeyChangedNode.Run(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+DelayedConventionScope.Run(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+ConventionBatch.Run(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+ConventionBatch.Dispose(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+ImmediateConventionScope.OnModelInitialized(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelInitialized(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Internal.Model..ctor(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.ModelBuilder..ctor(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.ModelConfigurationBuilder.CreateModelBuilder(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model(Unknown Source:0)
```

### Link to public reproduction project repository

https://github.com/Igor-9309/MauiApp9.git

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android

**Comment by ajcvickers** [comment] 2023-12-08 09:33
@steveisok How can customers ensure that all trimming and AOT options are switched off?

**Comment by steveisok** [comment] 2023-12-08 14:31
> @steveisok How can customers ensure that all trimming and AOT options are switched off?

This should be enough:

`/p:PublishTrimmed=false /p:AndroidEnableProfiledAot=false /p:RunAOTCompilation=false`

NOTE: if you have AOT on, you cannot turn off trimming. The .NET Android SDK will stop the build and error out by design.

**Comment by bengavin** [comment] 2023-12-13 13:18
Turning off the mentioned flags isn't fixing it for me, we had switch to Debug builds to eliminate the failing behavior. :(

**Comment by steveisok** [comment] 2023-12-13 17:20
> Turning off the mentioned flags isn't fixing it for me, we had switch to Debug builds to eliminate the failing behavior. :(

I know in my previous comment I indicated:

> This should be enough:
> /p:PublishTrimmed=false /p:AndroidEnableProfiledAot=false /p:RunAOTCompilation=false

To be clear, I was answering the question only around turning off AOT and trimming. That was not to work around the issue, which I believe is efcore related.

**Comment by AndriySvyryd** [comment] 2023-12-22 01:18
This is a runtime issue. Filed an issue with a repro that doesn't reference EF - https://github.com/dotnet/runtime/issues/96264

**Comment by AndriySvyryd** [comment] 2024-01-11 21:37
The underlying bug was fixed in .NET SDK 8.0.101. Please update and report if you still experience any issues.

**Closed by AndriySvyryd** 2024-01-11 21:37 UTC
Labels: type-bug, closed-external, area-external, customer-reported, area-platform, resourcing-discussion

**Comment by lambdageek** [comment] 2024-01-11 22:26
> The underlying bug was fixed in .NET SDK 8.0.101. Please update and report if you still experience any issues.

We also backported the runtime fix to .NET 7 and .NET 6.  All the servicing releases that went out yesterday should have the fix
