### ISSUE TITLE
Super slow first request

### ISSUE THREAD

**Issue by NicolasDorier** [dotnet/efcore#13484] opened 2018-10-03 11:56 UTC
I have around 14 tables, and the first request (which happen to be done by `.Migrate`) is awfully slow.
I guess it compiles the model, first request takes 6 seconds. Next requests are almost instant.

Is there some trick to decrease the slowness? It takes forever to start/debug an integration test because of this.

**Comment by ajcvickers** [comment] 2018-10-03 16:16
@NicolasDorier There's not much to go on here. A runnable project/solution or code listing that demonstrates the behavior would be ideal. If that's not possible, then at least some snippets of code that show what is happening on startup would be useful to give us something more to work with for suggestions.

**Comment by NicolasDorier** [comment] 2018-10-03 23:58
@ajcvickers I will make a repro later today. But basically: Have 14 tables, call `Migrate()` first time => 6 seconds. Call a second time => Less than one second.

I thought this was well known issue in entity framework core.

**Comment by ajcvickers** [comment] 2018-10-04 00:00
@NicolasDorier Not with only 14 tables, and the call to Migrate also makes it unusual.

**Comment by ajcvickers** [comment] 2018-10-10 17:59
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by NicolasDorier** [comment] 2018-10-11 02:46
My apologize, I did not had time. Will reopen once I have a repro.

**Closed** 2022-10-16 13:33 UTC
Labels: closed-could-not-reproduce, customer-reported
