### ISSUE TITLE
Reliability on getting generated ID of inserted items using C# 9 immutable records as models

### ISSUE THREAD

**Issue by Peluko** [dotnet/efcore#30837] opened 2023-05-06 23:55 UTC
Hello. I'm testing the use of C# 9 records as models for EF and I've confirmed that, albeit being immutable, the record object passed to ```.Add()``` gets its autogenerated ID field updated after ```.SaveChanges()```.

I think that this behaviour is intentional (and very convenient, of course), but as it clashes directly with the immutability of records, I want to ask if I can rely on this behaviour for future developments. I'm unable to find anything about it on the available documentation.

Regards.

**Comment by roji** [comment] 2023-05-08 10:14
Duplicate of #11457

**Comment by roji** [comment] 2023-05-08 10:16
EF doesn't currently have a full story for truly immutable CLR types; such a full story would mean eventually refraining from updating the immutable entity with the database-generated ID. Instead, a new instance would be created and returned with the new ID. However, if the current behavior is what you want, that should be fine - we'll very likely always allow you to e.g. have a private writable field, where EF would inject the ID. This way, although the type technically isn't fully immutable, it doesn't publicly expose APIs for mutation.

**Closed** 2023-05-10 09:14 UTC
Labels: closed-duplicate, customer-reported
