### ISSUE TITLE
Distinguish cancellation from failure to allow different logging strategies

### ISSUE THREAD

**Issue by ascott18** [dotnet/efcore#19526] opened 2020-01-08 21:04 UTC
**What problem are you trying to solve?**
Right now, logs for exceptions thrown due to `CancellationToken` cancellation are categorized as `Microsoft.EntityFrameworkCore.Query[10100]`. I want to be able to keep logging all other kinds of query errors, but not ones for intentional cancellations. In my application, I'm passing aspnetcore's `HttpContext.RequestedAborted` token to my async EF query evaluations. If the client hangs up, there's no reason to keep querying the database working to evaluate what are in some cases quite complex search queries in an intranet application (e.g. if the client changed their search criteria, or just left the page).

We'd like to not pollute our logs with these exceptions that are fully expected. We have an `ActionFilter` where we handle the exception as far as aspnetcore is concerned, but EF itself still logs the error.

For example:
```
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'My.App.AppDbContext'.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
         at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
         at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
```

**Describe the solution you'd like**

Create a dedicated log category for `OperationCanceledException`s that are caused by userspace-provided CancellationTokens that I can then setup a regular logging filter against.

Alternatively, just do not log `OperationCanceledException` at all if the `CancellationToken` has been triggered, since this is generally always an intentional outcome if the user has passed a `CancellationToken` to their query evaulations. This would be a much simpler path, but may have unintended consequences.

**Comment by ajcvickers** [comment] 2020-01-11 21:54
Note from team discussion: putting this on the backlog to consider generating a different logging event when the exception is "TaskCanceledException".

**Comment by MattJacobi-ESO** [comment] 2020-05-06 19:49
I'm having this problem as well. I would like to provide some additional context. Sometimes cancellation can actually generate multiple errors, some of which cannot be identified as being caused by cancellation.

For example, if you trigger the cancellation token before the database connection is made, you'll actually get two errors logged:

**Error #1**
```Microsoft.EntityFrameworkCore.Database.Connection: An error occurred using the connection to database '<mydb>' on server '<myserver>'.```
**Error #2**
```Microsoft.EntityFrameworkCore.Query: An exception occurred while iterating over the results of a query for context type '<mydbcontext>'.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
<callstack>```

Error #2 is noise -- and I'd love to be able to suppress it -- but it is at least possible to conclude that the error is likely due to a cancellation token. You can use the presence of "TaskCanceledException" to filter it out.

However, if you look at Error #1, there is no indication that this was actually caused by cancellation. This can lead to unnecessary investigation. And there is also no way to filter it out as "noise".

**Comment by 4lexKislitsyn** [comment] 2021-05-07 06:48
> You can use the presence of "TaskCanceledException" to filter it out

`OperationCanceledException` can be filter out too. It can be thrown from `ThrowIfCancellationRequested` method, e.g. [here](https://github.com/dotnet/efcore/blob/main/src/EFCore/Storage/ExecutionStrategy.cs#L274)

**Comment by plachor** [comment] 2021-05-14 14:05
Similar in my case, when request is aborted I see 2 log entries with `Error` severity level:
```
"MessageTemplate: "Failed executing DbCommand ({elapsed}ms) [Parameters=[{parameters}], CommandType='{commandType}', CommandTimeout='{commandTimeout}']{newLine}{commandText}",
"SourceContext": "Microsoft.EntityFrameworkCore.Database.Command"
```
and 
```
"MessageTemplate": "An exception occurred while iterating over the results of a query for context type '{contextType}'.{newline}{error}",
"SourceContext": "Microsoft.EntityFrameworkCore.Query"
```
Second one contains information regarding cause which was `OperationCanceledException`, but first one has no such indicator. Still I'm far away from parsing some string property to check if it is operation cancelled -  I would need than to recheck this with my request cancellation token to be 100% sure this something I can suppress or not. 

Best solution for my scenario would be a setting on DbContext allowing to lower severity of all logs from `Error` to `Debug` that are outcome of a cancellation token being cancelled but only for the one that was passed to the root invocation.

**Comment by KrzysztofBranicki** [comment] 2021-05-15 14:44
@ajcvickers Hi, is there any timeline where we can expect a fix for this bug? The way it is working currently basically renders all APIs that use `CancellationToken` useless. Unless someone doesn't mind polluting his logs with flood of errors that aren't really errors (highly unlikely for any production application). My scenario is the same as others in this issue - passing ASP.CORE HTTP request related `CancellationToken` to handle scenarios like browser closed, F5, frontend auto complete searches etc.

**Comment by jxlarrea** [comment] 2021-05-19 06:26
Same here. My ASP.NET Core application is unnecessarily logging thousands of TaskCanceledException errors every day due to CancellationToken being passed to EF Core queries. It is insane that this hasn't been resolved yet.

**Comment by adomass** [comment] 2021-05-19 13:30
I think this should have a label urgent-fix not consider-for-next-release. Logging system is spammed with those errors and we are waiting for this fix for a year.

**Comment by Aequoris** [comment] 2021-06-02 04:45
Agreed, it is very annoying, and drowning out real errors.

**Comment by KrzysztofBranicki** [comment] 2021-07-19 12:58
@ajcvickers can we expect this to be fixed in 6.0?

**Comment by ajcvickers** [comment] 2021-07-19 20:06
@KrzysztofBranicki No, this is in the backlog milestone, which means it is not planned to be fixed for 6.0. See [release-planning](https://docs.microsoft.com/en-gb/ef/core/what-is-new/release-planning) for information about how we plan which features go into a release. While this is an important, there are currently [53 feature requests that have more votes than this one](https://github.com/dotnet/efcore/issues?page=1&q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc), so it didn't make it into 6.0.

**Comment by brockallen** [comment] 2021-11-30 18:40
Just came across this ourselves. Here's what shows in the customer log:

```
[13:29:48 Error] Microsoft.EntityFrameworkCore.Database.Connection
An error occurred using the connection to database 'Duende.EntityFramework-6.0.0' on server '(localdb)\mssqllocaldb'.

[13:29:48 Error] Microsoft.EntityFrameworkCore.Query
An exception occurred while iterating over the results of a query for context type 'Duende.IdentityServer.EntityFramework.DbContexts.ConfigurationDbContext'.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

Which of course, looks scary for a false positive "error" condition. I'd think a flag to suppress this might be a way forward?

**Comment by roji** [comment] 2021-12-01 08:56
@brockallen we plan to address this in EF Core 7.0.

**Comment by Liero** [comment] 2021-12-03 14:48
Please, reconsider fixing this sooner than v7.0. There is no workaround and it causing serious troubles under heavy workload

**Comment by roji** [comment] 2021-12-03 14:59
@Liero I do intend to do this relatively early in the 7.0 work cycle, and at that point you'll be able to use 7.0.0 previews (which are generally very stable). However, there will not be a minor release before 7.0 with this change.

You may be able to work around this by implementing filtering outside of EF Core, i.e. by searching for TaskCanceledException in the log message text etc.

**Comment by BryceBarbara** [comment] 2021-12-03 17:08
Here's a helper function I use in my log filter to determine if it's an exception that I can suppress.

```cs
private static bool IsCancellationException(Exception ex)
{
    if (ex == null) return false;
    if (ex is IOException && ex.Message == "The client reset the request stream.")
        return true;
    if (ex is Microsoft.AspNetCore.Connections.ConnectionResetException)
        return true;
    // .NET SQL has a number of different exceptions thrown when operations are cancelled
    if (ex.Source == "Microsoft.Data.SqlClient" && ex.Message == "Operation cancelled by user.")
        return true;
    if ((ex is Microsoft.Data.SqlClient.SqlException || ex is System.Data.SqlClient.SqlException) &&
        ex.Message.Contains("Operation cancelled by user"))
        return true;
    return false;
}
```

**Comment by Liero** [comment] 2021-12-04 09:45
@BryceBarbara: How do you apply this filter?

I was only able to filter application insights using ITelemeryProcessor, but the .NET Logging only allows filtering based on category and severity as far as I know

BTW, here is how I catch the exception:

```csharp
try
{
   products = dbContext.Products.ToArray(cancellationToken)
}
catch when (cancellationToken.IsCancellationRequested) {}
```

**Comment by BryceBarbara** [comment] 2021-12-08 17:49
@Liero 

The project I'm working on uses a [custom middleware class](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-6.0) to suppress the unneeded exceptions. Although everyone's use case will be different, I'll share my approach here in case it's useful for anyone else.

The middleware class:
```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Primitives;
using Microsoft.Net.Http.Headers;

public class StandardizedExceptionMiddleware
{
    private static readonly HashSet<MediaType> JsonContentTypes = new HashSet<MediaType>
    {
        new MediaType("text/json"),
        new MediaType("application/json"),
    };

    private readonly RequestDelegate _next;
    private readonly ILogger<StandardizedExceptionMiddleware> _logger;

    public StandardizedExceptionMiddleware(RequestDelegate next, ILogger<StandardizedExceptionMiddleware> logger)
    {
        _next = next;
        _logger = logger;
    }

    public async Task Invoke(HttpContext context)
    {
        try
        {
            await _next(context).ConfigureAwait(false);
        }
        catch (Exception ex)
        {
            if (IsCancellationException(ex))
            {
                if (context.RequestAborted.IsCancellationRequested)
                {
                    // Try to ensure cancelled requests don't get reported as 5xx errors
                    context.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                }
                return;
            }
            LogException(context, ex);
            if (!context.Response.HasStarted && await HandleExceptionAsync(context, ex).ConfigureAwait(false))
            {
                return;
            }
            // This exception wasn't handled so let it bubble up
            throw;
        }
    }

    private void LogException(HttpContext context, Exception exception)
    {
        var routeData = context.GetRouteData();
        var controller = routeData?.Values["controller"]?.ToString();
        var action = routeData?.Values["action"]?.ToString();
        if (!string.IsNullOrEmpty(controller) && !string.IsNullOrWhiteSpace(action))
        {
            _logger.LogError(exception, "Unhandled exception in {Controller}/{Action}", controller, action);
        }
        else
        {
            _logger.LogError(exception, "Unhandled exception");
        }
    }

    private static bool IsCancellationException(Exception ex)
    {
        if (ex == null) return false;
        if (ex is OperationCanceledException)
            return true;
        if (ex is System.IO.IOException && ex.Message == "The client reset the request stream.")
            return true;
        if (ex is Microsoft.AspNetCore.Connections.ConnectionResetException)
            return true;
        // .NET SQL has a number of different exceptions thrown when operations are cancelled
        if (ex.Source == "Microsoft.Data.SqlClient" && ex.Message == "Operation cancelled by user.")
            return true;
        if ((ex is Microsoft.Data.SqlClient.SqlException || ex is System.Data.SqlClient.SqlException) &&
            ex.Message.Contains("Operation cancelled by user"))
            return true;
        return false;
    }

    /// <summary>
    /// Attempts to handle sending the error response for provided context.
    /// </summary>
    /// <param name="context">The context needing a response.</param>
    /// <param name="exception">The exception that was thrown.</param>
    /// <returns>Returns true if the exception was handled and a response has been sent.</returns>
    private static async Task<bool> HandleExceptionAsync(HttpContext context, Exception exception)
    {
        if (!IsAcceptingJson(context) || exception == null) return false;

        context.Response.ContentType = "application/json";
        // this is a custom class we use, replace this with your own error response type
        var error = new StandardErrorResult(FrontEndExceptionHelpers.GetFriendlyExceptionMessage(exception));
        await JsonSerializer.SerializeAsync(context.Response.Body, error).ConfigureAwait(false);
        return true;
    }

    /// <summary>
    /// Determines if the HTTP request for the context is expecting a JSON response.
    /// </summary>
    /// <param name="context">The context containing the request.</param>
    private static bool IsAcceptingJson(HttpContext context)
    {
        var requestAccept = context.Request.Headers[HeaderNames.Accept];
        // Only consider it accepting JSON if it's explicitly stated in the request headers
        return !StringValues.IsNullOrEmpty(requestAccept) && IsSubsetOfAnyJsonContentType(requestAccept);
    }

    /// <summary>
    /// Determines if the media type provided is a subset of one of the media types in <see cref="JsonContentTypes"/>.
    /// </summary>
    /// <param name="requestMediaType">The media type to inspect.</param>
    private static bool IsSubsetOfAnyJsonContentType(string requestMediaType)
    {
        var requestedType = new MediaType(requestMediaType);
        return JsonContentTypes.Any(acceptedType => requestedType.IsSubsetOf(acceptedType));
    }
}
```

And we add the middleware to the `Startup.cs`'s `Configure` method as so:
```cs

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    // ...
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
        app.UseDatabaseErrorPage();
    }
    else
    {
        app.UseExceptionHandler("/Error");
        app.UseHsts();
    }
    app.UseMiddleware<StandardizedExceptionMiddleware>();
    // ...
}
```

**Comment by roji** [comment] 2021-12-12 17:11
Ran into a wall when trying to identify SqlExceptions representing cancellations - see https://github.com/dotnet/EntityFramework.Docs/pull/3617.

If there really is no way to reliably identify cancellation with SqlClient, we could also check whether the user cancellation token has been triggered. However:

* Because of a race condition, there could be a non-cancellation SqlException bubbling up just as the user triggered their token, and we'd log incorrectly.
* At least in theory, the command could be canceled not via the cancellation token.

**Closed** 2021-12-14 11:52 UTC
Labels: type-enhancement, customer-reported, area-query, area-save-changes

**Comment by roji** [comment] 2021-12-14 11:55
This is now merged - cancellations are now logged via log new cancellation events (which are debug by default) rather than failure.

The default behavior is to identify OperationCanceledException as cancellation events. Providers can create their own IExecutionDetector and add specific logic for identifying cancellation exceptions as necessary. For SqlClient, since there's apparently no way to identify cancellation from the exception, the cancellation token is checked instead, which isn't ideal. We can fix this if SqlClient correct the problem on their side.

**Comment by brockallen** [comment] 2022-11-01 19:38
> This is now merged - cancellations are now logged via log new cancellation events (which are debug by default) rather than failure.
> The default behavior is to identify OperationCanceledException as cancellation events. Providers can create their own IExecutionDetector and add specific logic for identifying cancellation exceptions as necessary. For SqlClient, since there's apparently no way to identify cancellation from the exception, the cancellation token is checked instead, which isn't ideal. We can fix this if SqlClient correct the problem on their side.

I've tested on .NET 7 RC2 and as far as I can tell this has the same behavior. Do you have sample code for what I can now do to distinguish, or must this be done down at the provider level (lower than normal app code)?

**Comment by brockallen** [comment] 2023-01-24 20:03
Sorry to rekindle this thread, but is it documented or can you provide any insight into when an OperationCanceledException is thrown vs when a TaskCanceledException is thrown? We're trying to tune the filter and don't want to use OperationCanceledException is that's too broad and suppresses other meaningful exceptions/conditions. TIA!

// @josephdecock

**Comment by roji** [comment] 2023-01-25 10:35
EF itself considers any OperationCanceledException as meaning that the operation was canceled, e.g. for the purposes of logging an error vs. a cancellation; I'd suggest you do the same. In the general case you shouldn't be catching TaskCanceledException, but rather OperationCanceledException.

**Comment by brockallen** [comment] 2023-01-25 14:09
Thank you @roji!

**Comment by ascott18** [comment] 2023-02-13 17:16
@sommmen This issue was about modifying the logging that EF does when there's a cancellation, not about changing the exceptions that SqlClient throws. See https://github.com/dotnet/SqlClient/issues/26, which was linked earlier in this issue.

**Comment by pampua84** [comment] 2023-03-22 09:57
Hi, while doing some tests I also have the same problem, on EF Core 6 I always get an exception like this first (without any details):

`[10:00:16 ERR] An error occurred using the connection to database 'Test' on server 'Server01'. <s1:Microsoft.EntityFrameworkCore.Database.Connection> `

always followed by this exception:

`[10:00:16 ERR] An exception occurred while iterating over the results of a query for context type 'Duende.IdentityServer.EntityFramework.DbContexts.ConfigurationDbContext'.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync() <s1:Microsoft.EntityFrameworkCore.Query> 80000317-0005-9e00-b63f-84710c7967bb
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
`

but the cancellation from what is due, in this way I can not understand the cause of the problem and therefore find a solution. Can you help me?

**Comment by roji** [comment] 2023-03-22 14:23
I'm not sure exactly what you're asking, but you seem to be passing a cancellation token to your query, and then someone is triggering that cancellation token, causing the cancellation exception above.

In any case, this issue is about distinguish cancellation from failure in EF's logging, and your question doesn't seem to be related to this in any way. If you need assistance, please open a new issue with a minimal, runnable code sample.

**Comment by sayowayah** [comment] 2023-04-12 02:13
Just wondering if this is still partially an issue? I'm still seeing some `Microsoft.EntityFrameworkCore.Database.Connection.ConnectionError` error logs when a task is cancelled. My `OperationCanceledException` handler is properly triggering for the same request, so it seems the new `OperationCanceledException` is throwing, but EF still logs that `Database.Connection.ConnectionError` somewhere along the way. It seems that @roji  had some back and forth with someone [here](https://stackoverflow.com/questions/75243488/ef-core-7-task-cancellation-exception) about the same/similar issue, but I don't see a resolution.

I was thinking about configuring EF to drop `RelationalEventId.ConnectionError` logs to warning, but that doesn't seem great if there's actually some other non-cancellation-related error.

More details in case my specific settings are related:
* `Microsoft.EntityFrameworkCore.SqlServer` 7.0.3
* Azure SQL Managed Instance
* Details for this particular query
    * Wrapped in a `TransactionScope` with `IsolationLevel.ReadUncommitted`
    * `Database.SetCommandTimeout(60)`
    * `AsNoTracking()`

**Comment by roji** [comment] 2023-04-12 07:08
@sayowayah as far as I know the issue isolved... If you're seeing otherwise, we're going to need to see some sort of runnable repro to investigate. The SO issue linked to above was unable to do so.

**Comment by ravindUwU** [comment] 2025-02-27 14:58
Hi @roji 👋. In the repro below, the `CancellationToken` is cancelled _before_ the query starts. EF core tries to open the connection using `OpenAsync` which throws an `OperationCanceledException`, caught via `catch (Exception e)` and logged using `ConnectionErrorAsync` as an error "Opening connection to database '...' on server '...'", and rethrown [here](https://github.com/dotnet/efcore/blob/30eb1fbb88f6bc7fe31217f83933122a2a403e59/src/EFCore.Relational/Storage/RelationalConnection.cs#L754-L786).

![](https://github.com/user-attachments/assets/ee3c2ef4-38d7-446b-8bfa-a9b67804bd88)

Shouldn't this catch be something like `catch (Exception e) when (e is not OperationCanceledException)` so that cancellations aren't logged by EF? 🤔

```csharp
static async Task Main()
{
	var sp = new ServiceCollection()
		.AddDbContext<Db>()
		.AddLogging((options) => options
			.SetMinimumLevel(LogLevel.Debug)
			.AddSimpleConsole()
			.AddFilter("Microsoft.EntityFrameworkCore.Query", LogLevel.None)
			.AddFilter("Microsoft.EntityFrameworkCore.Infrastructure", LogLevel.None)
		)
		.BuildServiceProvider();

	using var scope = sp.CreateScope();
	var db = scope.ServiceProvider.GetRequiredService<Db>();

	var s = new CancellationTokenSource();
	s.Cancel();

	try
	{
		Console.WriteLine("query");
		await db.Entities.FromSqlRaw("SELECT 1 AS id").ToListAsync(s.Token);
	}
	catch (OperationCanceledException)
	{
		Console.WriteLine("cancelled; ignored");
	}
}

[Table("entity")]
class Entity
{
	[Column("id")]
	public required int Id { get; set; }
}

partial class Db(DbContextOptions<Db> options) : DbContext(options)
{
	public required DbSet<Entity> Entities { get; init; }
}
```

Output below. The highlighted lines are caused by the `OperationCanceledException` being logged by EF.

```diff
 query
 dbug: Microsoft.EntityFrameworkCore.Database.Connection[20005]
       Creating DbConnection.
 dbug: Microsoft.EntityFrameworkCore.Database.Connection[20006]
       Created DbConnection. (10ms).
 dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
       Opening connection to database 'main' on server 'owo.db'.
-fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
-      An error occurred using the connection to database 'main' on server 'owo.db'.
 cancelled; ignored
 dbug: Microsoft.EntityFrameworkCore.Database.Connection[20007]
       Disposing connection to database 'main' on server 'owo.db'.
 dbug: Microsoft.EntityFrameworkCore.Database.Connection[20008]
       Disposed connection to database 'main' on server 'owo.db' (0ms).
```

**Comment by roji** [comment] 2025-02-28 19:45
@ravindUwU can you please post this as a new issue?

**Comment by ravindUwU** [comment] 2025-03-01 00:57
Thanks @roji! #35708 😊

**Comment by 0xced** [comment] 2025-10-16 08:41
> Providers can create their own IExecutionDetector and add specific logic for identifying cancellation exceptions as necessary.

You meant `IExceptionDetector` 😉.

For people skimming through issues related to https://github.com/dotnet/SqlClient/issues/26, writing a custom `IExceptionDetector` will only affect EF Core logs. This will **not** turn `SqlException` into a proper `OperationCanceledException`. For this, a custom `IExecutionStrategy` would be needed. See https://github.com/0xced/efmssql for more information.
