### ISSUE TITLE
Value Objects are not eager Loaded

### ISSUE THREAD

**Issue by Brezelmann** [dotnet/efcore#13758] opened 2018-10-25 10:20 UTC
**Describe what is not working as expected.**
Yesterday I played arround a bit with a custom User Store Implementation for Asp.Net Core Identity. There is a Method given that searches all Users based on its UserClaims.
Therefore I tried loading all Users like this: 
`con.Claims.Where(x => x.Type.Equals("Type 0") && x.Value.Equals("Value 0"))
                    .Include(y => y.User).Select(z => z.User).ToListAsync()`

Here I assumed that the FullName Value Object gets eager loaded by default (as stated in the Microsoft Docs), but that was not the case. It stayed null. Only by adding an Include call like this:
`con.Claims.Where(x => x.Type.Equals("Type 0") && x.Value.Equals("Value 0"))
                    .Include(y => y.User).Select(z => z.User).Include(a => a.Name).ToListAsync()`

The ValueObject gets loaded. In my Humble Opinion that seems a little bit weird especially when the Value Object is not an extra Table but 4 Fields in the Users Table. It should get eager loaded by default (like the docs stating it)

**### Steps to reproduce**
I Posted a Project with two simple Unit Tests on Github. One that is failing (using the first Code snippet) and one that is working (using the second code snippet). Here ist the [link](https://github.com/Brezelmann/Error)

**### Further technical details**
EF Core version: 2.14
Database Provider: InMemory in Testing and SQL in Production both version 2.1.4 happens on both
Operating system: Windows 10 Education
IDE: Visual Studio 2017 15.8.8

**Comment by ajcvickers** [comment] 2018-10-25 17:46
Note for triage: Likely a duplicate of #13546

**Closed** 2022-10-16 13:37 UTC
Labels: closed-duplicate, customer-reported
