### ISSUE TITLE
Feature Request: Create display name from database description column property

### ISSUE THREAD

**Issue by VR-Architect** [dotnet/efcore#6149] opened 2016-07-23 15:06 UTC
If using a database first and database update first methodology, it would be great to have Scaffold-DbContext command add the display meta-data to each column in the model automatically from the value in the MS-SQL's description column property. Why?

If we make changes to our database design via the database, then re-run Scaffold-DbContext to update our models, we lose any settings we set for display name.

BTW, what would be very, very awesome is if MS-SQL could add these fields to their column properties,  OR VS2015 could somehow enrich the column properties :
- Display Name
- Display Format
- RegEx Validation, etc.

**Comment by rowanmiller** [comment] 2016-07-27 17:19
We aren't planning to do this since it's not clear that Description would translate to DisplayName (in fact when we've seen requests like this in the past, folks have often wanted them added as xml doc comments rather than display name). 

That said, in the future we do want to make the reverse engineer process more extensible so that folks can wire up things like this without too much work.

**Comment by Varorbc** [comment] 2018-09-03 03:27
@rowanmiller Is there a plan to add this feature?

**Comment by divega** [comment] 2018-09-03 07:11
@Varorbc this issue has been closed for a long time, and is mostly a duplicate of #131116. 

So the answer is the same as 
https://github.com/aspnet/EntityFrameworkCore/issues/13116#issuecomment-417113811.

**Comment by auspex** [comment] 2019-01-25 13:58
@divega @rowanmiller I read that last question as "is there a plan to add the feature mentioned by Rowan?" I.e. _"we do want to make the reverse engineer process more extensible so that folks can wire up things like this without too much work"_. I don't mind doing this myself, but I'd really appreciate if you guys would do the heavy lifting :-) I haven't come across anything that suggests this is even in the planning.

**Comment by ajcvickers** [comment] 2019-01-25 18:19
@auspex See #4038

**Closed** 2022-10-16 09:51 UTC
Labels: closed-out-of-scope
