### ISSUE TITLE
Bug with GroupJoin of IQueryable and DbSet

### ISSUE THREAD

**Issue by SillyCoon** [dotnet/efcore#18444] opened 2019-10-18 10:24 UTC
I have IQueryable with Join in it. When I try to use GroupJoin with inner DbSet, I get not groupped values, just like after left outer join, but values are in collection. But when I use Select to DbSet, I get right groupped result, not matter what projection was made.

### Steps to reproduce

My code:

```
 var AsWithJoin = dbContext.Set<A>().Join(
                dbContext.Set<C>(),
                u => u.CId,
                s => s.CId,
                (u, s) => new
                {
                    u.Id,
                    u.CId,
                    s.Status
                }); // Any projection

            var withSelectAB = dbContext.Set<AB>().Select(us => new {us.BId, us.AId});
            var withoutSelectAB = dbContext.Set<AB>();

// right, contains 1970 not groupped values
var t1 = AsWithJoin.GroupJoin(withoutSelectAB,
                u => u.Id,
                us => us.AId,
                (u, us) => new
                    {
                        u.Id,
                        Bs = us
                    }
                ).ToList();
// wrong, contains 1360 groupped values
var t2 = AsWithJoin.GroupJoin(withSelectAB,
                u => u.Id,
                us => us.AId,
                (u, us) => new
                {
                    u.Id,
                    Bs = us
                }
            ).ToList();
```

### Further technical details

EF Core version: 2.2.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 2.2
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.5

**Comment by ajcvickers** [comment] 2019-10-18 19:28
@SillyCoon Please post a small, _runnable_ project/solution or _complete_ code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-10-25 16:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:50 UTC
Labels: closed-could-not-reproduce, customer-reported
