### ISSUE TITLE
Include after select not load navigation property

### ISSUE THREAD

**Issue by MohammadAkbari** [dotnet/efcore#7435] opened 2017-01-18 06:37 UTC
I use entity framework core 1.1.
I have a query like below, and I expect to users who have UserProfile by using Include, load UserProfile. but this query always return UserProfile null .

Query:

    var user = dbContext.UserMappers
		.Where(e => e.OldUserId == id)
		.Select(e => e.User)
		.Include(e=>e.UserProfile)
		.FirstOrDefault();

Models:

    public class UserMapper
    {
        [Key, ForeignKey(nameof(User))]
        public string UserId { get; set; }
        public User User { get; set; }
        public int OldUserId { get; set; }
    }
	
    public class User : IdentityUser
    {
        public bool Suspended { get; set; }
        public string Nickname { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
	
    public class UserProfile : ICommonDate
    {
        [Key, ForeignKey(nameof(User))]
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Telephone { get; set; }
    }

**Comment by maumar** [comment] 2017-05-01 21:21
dupe of 6451

**Closed** 2022-10-16 10:50 UTC
Labels: closed-duplicate
