### ISSUE TITLE
Consider using protected instead of private for services members

### ISSUE THREAD

**Issue by cdie** [dotnet/efcore#8114] opened 2017-04-10 14:41 UTC
I need to rewrite a custom implementation of StateManager. In fact, I only need a specific method to do a different test. To do so, I inherits from StateManager class. But many members are private, so I need to redefine them, same way they're defined in base class just for my method needs.
Also, I have to use reflection to fill base one with my values. It would be more easy if they're proected

### Further technical details
EF Core version: 1.1.1

**Comment by ajcvickers** [comment] 2017-04-10 15:35
@cdie We try to keep the correct balance between public API service, internal API service put exposed as public, and truly private implementation details of the code. If there are specific cases where something that is private needs to be protected, then we would consider that case. Given that, can you provide some more details as to what you need access to and why? Or alternatively, if it is a small change it might be easier to just send a PR and we can access it there.

**Comment by ajcvickers** [comment] 2017-04-17 18:06
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:00 UTC
Labels: closed-could-not-reproduce
