### ISSUE TITLE
How to debug duplicate key issue during SaveChanges

### ISSUE THREAD

**Issue by herme063** [dotnet/efcore#12090] opened 2018-05-21 20:45 UTC
On the call to SaveChanges() an ArgumentException is thrown when a call to Dictionary.Add fails. Unfortunately the key is not readable `ArgumentException: An item with the same key has already been added. Key: System.Object[]` and there is no indication about the tracked entity type which has the issue.

How do we debug from here?

Thank you,

**Comment by smitpatel** [comment] 2018-05-21 21:50
Seems like Duplicate of #11505

**Comment by ajcvickers** [comment] 2018-05-23 20:10
@herme063 Can you confirm if #11505 covers the issue you are seeing?

**Comment by herme063** [comment] 2018-05-24 03:35
In my scenario I am not using filter index. After deleting some of the many to many data I was able to get past this error. I am still not sure how. So I really do not have much of case here,

**Closed** 2022-10-16 12:25 UTC
Labels: closed-could-not-reproduce, customer-reported
