### ISSUE TITLE
Daily Build 23524.5 UseSQLServer LogTo method requires explicit package ref to logging

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#32204] opened 2023-11-01 19:56 UTC
Just switched from rc.2 to daily build and going back to rc.2. 

UseSqlServer(...).LogTo wouldn't compile. I added a package ref to 
` <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0-*" />
`to csproj. Maybe its missing in dependencies??

SO it built but then it wouldn't run saying about 10 different packages couldn't be found. 
![image](https://github.com/dotnet/efcore/assets/5007120/df8af51d-2e42-48e8-ae82-e8313a1b3d69)

Sorry I can't chase it down...just going back to rc.2

EF Core version: 8.0.0-rtm.23524.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET 8.0)
Operating system: windows 10 ..yes I know
IDE: Visual Studio 2022 preview 17.8 preview 6)

**Comment by ErikEJ** [comment] 2023-11-02 06:24
@julielerman The most recent daily builds are broken, wait for Nov 14th.

**Comment by ajcvickers** [comment] 2023-11-02 12:05
@julielerman You can use 8.0.0-rtm.23517.11 or the .NET 9 builds. The current EF8 builds are not broken, but unfortunately they can only be used by people with access to internal builds of other things in .NET. I know this sucks, but there's nothing we can do about it.

**Comment by ajcvickers** [comment] 2023-11-02 12:27
Duplicate of #32171

**Closed by ajcvickers** 2023-11-02 12:27 UTC
Labels: customer-reported
