### ISSUE TITLE
The naming convention of custom foreign keys and shadow attributes conflicts. Types that can be null cannot be null during migration

### ISSUE THREAD

**Issue by zhuangState** [dotnet/efcore#29298] opened 2022-10-08 15:30 UTC
The naming convention of custom foreign keys and shadow attributes conflicts. Types that can be null cannot be null during migration
Nullable AccountID
![image](https://user-images.githubusercontent.com/98197028/194715115-73d9c639-0b2a-4d30-912c-65cb5d34dd87.png)

Migration result cannot be empty
![image](https://user-images.githubusercontent.com/98197028/194715154-a81ebfce-86d2-43fb-97e1-b436768a45a6.png)

If you do not use the name AccountID, this problem will not be caused

**Comment by zhuangState** [comment] 2022-10-08 15:33
It is normal without specifying a foreign key

![image](https://user-images.githubusercontent.com/98197028/194715367-14aa8391-5431-43ab-9e05-2ac82dd59f37.png)
![image](https://user-images.githubusercontent.com/98197028/194715376-48df6036-8529-4e46-84c3-6466edf02131.png)

**Comment by ErikEJ** [comment] 2022-10-08 15:37
Which EF Core version and provider?

**Comment by zhuangState** [comment] 2022-10-08 15:56
> 

Hello, version 6.0.9

**Comment by ajcvickers** [comment] 2022-10-08 17:35
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-10-19 19:22
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-10-19 19:22 UTC
Labels: customer-reported
