### ISSUE TITLE
Ef Core 5.0 Can't get the store procedure result

### ISSUE THREAD

**Issue by vinothfl** [dotnet/efcore#23804] opened 2021-01-04 20:18 UTC
SELECT  
i.Id AS Id, 
i.InvoiceNo AS InvoiceNumber      
,i.InvoiceDate AS InvoiceDate      
,au.UserName AS AppUserName      
,au.GSTIN AS AppUserGSTIN      
,au.Address AS AppUserAddress      
,au.City AS AppUserCity      
,au.State AS AppUserState      
,du.[Name] AS DeliveryName      
,du.GSTIN AS DeliveryGSTIN      
,du.Address AS DeliveryAddress      
,du.City AS DeliveryCity      
,du.State AS DeliveryState      
,ru.[Name] AS RecipientName      
,ru.GSTIN AS RecipientGSTIN      
,ru.Address AS RecipientAddress      
,ru.City AS RecipientCity      
,ru.State AS RecipientState      
,i.GST      
,i.HasTaxReverseCharge      
,i.IsIGST      
,i.InvoiceCount      
,i.TotalTaxableAmount      
,i.TotalTax      
,i.InvoiceTotal      
      
FROM Invoice i WITH(NOLOCK)      
--JOIN InvoiceItem ii WITH(NOLOCK) ON i.Id=ii.InvoiceId      
JOIN AppUser au WITH(NOLOCK) ON i.AppUserId=au.Id      
JOIN Delivery du WITH(NOLOCK) ON i.DeliveryUserId=du.Id      
JOIN Recipient ru WITH(NOLOCK) ON i.RecipientUserId=ru.Id      
WHERE i.Id=@InvoiceId AND i.IsActive=1   

the above sp processing query can;t get the result from ef core.

**Comment by ErikEJ** [comment] 2021-01-04 20:19
Please share a full repro.

**Comment by ajcvickers** [comment] 2021-01-11 15:56
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:17 UTC
Labels: closed-could-not-reproduce, customer-reported
