### ISSUE TITLE
DB2 does not support correlated subquery in order by clause

### ISSUE THREAD

**Issue by ShamsulAmry** [dotnet/efcore#13710] opened 2018-10-22 08:14 UTC
I'm writing my own provider for DB2 (one of the reason is because the existing official provider is not up to date), and am using EF Core's release/2.1 branch for development.

There are few test failures, which I found out is because DB2 does not support correlated subquery in order by clause. It can only support correlated subquery in projection or where clause. (source: [Correlated subqueries](https://www.ibm.com/support/knowledgecenter/en/SSGU8G_12.1.0/com.ibm.sqlt.doc/ids_sqt_181.htm))

Would like to get input on what should be the best way going forward around this issue. Ignore affected test cases? I am looking at `SqlTranslatingExpressionVisitor` but am not so sure how to handle that class.

**Comment by ajcvickers** [comment] 2018-10-22 18:41
@smitpatel to provide some guidance.

**Comment by smitpatel** [comment] 2018-10-22 19:06
Duplicate of #8032

**Comment by smitpatel** [comment] 2018-10-22 19:06
@ShamsulAmry - Can you confirm, if the issue you are facing is same as the #8032

**Comment by ShamsulAmry** [comment] 2018-10-23 05:39
@smitpatel - Yes, I added the reference link to #8032

**Closed** 2022-10-16 13:36 UTC
Labels: customer-reported
