### ISSUE TITLE
Seeding problem, there was no value provided for the required property

### ISSUE THREAD

**Issue by chravikishore** [dotnet/efcore#13615] opened 2018-10-13 10:46 UTC
I had this model 
```c#
    public class Customer 
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int? Under { get; set; }
        public string Description { get; set; }
        public bool IsDefault { get; set; }
    }
```
and has following mapping
```c#
            entityTypeBuilder
                .ToTable("Customers");
            entityTypeBuilder
                .HasKey(e => e.ID);
            entityTypeBuilder
                .Property(e => e.Name)
                .IsRequired();
            entityTypeBuilder
                .Property(e => e.Description)
                .HasMaxLength(250);
            entityTypeBuilder
                .Property<bool>("IsDeleted")
                .HasDefaultValue(false)
                .IsRequired();
```
When I create seed like below 
```c#
            entityTypeBuilder
                .HasData(new Customer() { ID = 1, Name = "Customer name", Under = null, Description = "some descr", IsDefault = true },);
```
I am getting error. 

> **The seed entity for entity type 'Customer' cannot be added because there was no value provided for the required property 'IsDeleted'.**

Field showing error has a default value defined and only database field which does not have property on model object

```
Exception message:
Stack trace:
System.InvalidOperationException: The seed entity for entity type 'Customer' cannot be added because there was no value provided for the required property 'IsDeleted'.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateData(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The seed entity for entity type 'Customer' cannot be added because there was no value provided for the required property 'IsDeleted'.

```
```
### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.1

**Comment by ajcvickers** [comment] 2018-10-15 16:38
@chravikishore Duplicate of #12525

**Closed** 2022-10-16 13:35 UTC
Labels: closed-duplicate, customer-reported
