### ISSUE TITLE
building an app with PublishTrimmed trims too much

### ISSUE THREAD

**Issue by lechgu** [dotnet/efcore#27069] opened 2021-12-28 14:57 UTC
I have an asp.net core app with ef core.
The app uses PublishTrimmed=true and it causes the app fail in runtime with error coming from the sql translator that
"Round not found on Math".
The app runs in the docker container on Azure Kubernetes Service.
Removing PublishTrimmed=true seems to be a workaround but it make the image larger, so it would be good if this is fixed.

The packages used with the versions:
---------------------------------
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
    <PackageReference Include="dotenv.net" Version="3.1.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.41.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.41.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.1" />
    <PackageReference Include="Microsoft.Identity.Web" Version="1.21.1" />

------------

The Dockerfile:
------------
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

COPY Service/ ./Service
COPY protos/ ./protos

RUN dotnet publish Service -c release --self-contained -r linux-musl-x64 -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:PublishTrimmed=true

FROM mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine
RUN apk add --no-cache icu-libs
COPY --from=build /app/Service/bin/release/net6.0/linux-musl-x64/publish/Service /usr/local/bin/identity

ENV PORT=80
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
ENV Logging__LogLevel__Microsoft=Information

CMD [ "identity" ]
--------------

**Comment by roji** [comment] 2021-12-28 21:44
Duplicate of #26288

**Closed** 2022-10-16 20:20 UTC
Labels: closed-duplicate, customer-reported
