### ISSUE TITLE
FromSqlRaw or FromSqlInterpolated was called with non-composable SQL and with a query composing over it

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/efcore#22558] opened 2020-09-16 10:21 UTC
I'm trying to compose a raw query that *should* be composable with Linq operators, but I get this error:

> FromSqlRaw or FromSqlInterpolated was called with non-composable SQL and with a query composing over it. Consider calling `AsEnumerable` after the FromSqlRaw or FromSqlInterpolated method to perform the composition on the client side.

### Steps to reproduce

Run this code:

```csharp
class Foo
{
    public int Id { get; set; }
    public int CategoryId { get; set; }
    public DateTime StartDate { get; set; }
    public ICollection<FooTranslation> Translations { get; set; } = new HashSet<FooTranslation>();
}

class FooTranslation
{
    public int FooId { get; set; }
    public string Lang { get; set; }
    public string Name { get; set; }
    public string Content { get; set; }
}

class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions<MyDbContext> options)
        : base(options)
    {
    }
    
    public DbSet<Foo> Foos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        
        modelBuilder.Entity<Foo>(entity =>
        {
            entity.ToTable("Foos");
            entity.HasKey(f => f.Id);
            entity.OwnsMany(f => f.Translations, e =>
            {
                e.ToTable("FooTranslations");
                e.HasKey(t => new {t.FooId, t.Lang});
                e.Property(t => t.Lang).IsRequired().HasMaxLength(2);
                e.Property(t => t.Name).IsRequired().HasMaxLength(100);
                e.Property(t => t.Content).IsRequired().HasMaxLength(200);
            });
        });
    }
}

...

var sql = @"
WITH foosWithRownum as (
    SELECT Id, CategoryId, StartDate,
        ROW_NUMBER() OVER (PARTITION BY CategoryId ORDER BY StartDate DESC, Id DESC) rownum
    FROM Foos
    WHERE StartDate < CURRENT_TIMESTAMP
)
SELECT f.*, t.FooId, t.Lang, t.Name, t.Content
FROM foosWithRownum f
LEFT JOIN FooTranslations t ON f.Id = t.FooId
WHERE f.rownum = 1";

IQueryable<Foo> query = dbContext.Foos.FromSqlRaw(sql);

// Add sorts and projections to query with Linq, and execute it
query = query.OrderBy(...)
var result = query.Select(...).ToList();
```
This gives the error above.

As far as I can tell, my raw SQL should be composable, according to the rules [here](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#composing-with-linq). There is an `ORDER BY`, but it's in an OVER clause in a CTE, so it shouldn't prevent the whole query from being composable. I tried adding `OFFSET 0` as suggested in the docs, but I get a syntax error (it's probably not supported in an OVER clause). I also tried adding `TOP 100 PERCENT` to the SELECT clause, but it didn't change anything.

Is there any way I can run this query with EF Core ?

What is really strange is that I get the same error if I directly call `ToList()` on the result of `FromSqlRaw()`, even though I'm not composing with anything.

### Further technical details

EF Core version: 3.1.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: irrelevant, I can easily reproduce without any IDE

**Comment by thomaslevesque** [comment] 2020-09-16 12:09
Ah, I see. In 3.1, the SQL is just matched against a regex to check that it starts with SELECT
https://github.com/dotnet/efcore/blob/cd947bdc054a976fc6f82990d8d47b3a292f9ba7/src/EFCore.Relational/Query/QuerySqlGenerator.cs#L19

So I guess it's impossible to use a CTE with FromSqlRaw/FromSqlInterpolated... I think it's a pretty severe limitation. There are many queries that can't be translated from Linq to SQL, and writing them directly in SQL often involves a CTE. This means there are many queries that are completely impossible to run with EF.

As a workaround, is there a way to materialize an entity from a DbDataReader?

**Comment by ErikEJ** [comment] 2020-09-16 12:36
Have you tried with .AsEnumerable()

**Comment by thomaslevesque** [comment] 2020-09-16 12:43
@ErikEJ yes, same error. But anyway I don't want AsEnumerable. I want the query to run completely on the database, not in memory.
Anyway, even without the regex check, it wouldn't work with a CTE; I managed to circumvent the check (with a horrible reflection hack), but the generated SQL is invalid. I think a CTE can't appear in a subquery.

I worked around the issue by using a subquery instead of a CTE:

```sql
SELECT f.*
FROM (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY CategoryId ORDER BY StartDate DESC, Id DESC) rownum
    FROM Foos
    WHERE StartDate < CURRENT_TIMESTAMP
) f
WHERE f.rownum = 1
```

**Comment by ErikEJ** [comment] 2020-09-16 12:46
Yes, I am not sure SQL Server allows you to compose over a CTE.

**Comment by paulresdat** [comment] 2021-03-11 19:08
We've found this breaks when using AutoMapper when previously it didn't in 3.1.  The fix is to put this into a List first before casting to an IQueryable that AutoMapper can use.

```csharp
EntityQuerable<SystemQueueReceive> rowsFromStoredProcedure = PrepareProcedure();
var queryable = rowsFromStoredProcedure.ToList()
return queryable.AsQueryable()
  .ProjectTo<T2>(mapperConfig)
  .ToList()
  .FirstOrDefault()
```

If there's a better way to do it, I'm all ears.

**Comment by bitxwise** [comment] 2021-03-28 02:59
I see that this is a closed issue, but doesn't this requirement for beginning with SELECT effectively break support for querying via stored procedure?

**Comment by bitxwise** [comment] 2021-03-28 03:29
I see that this is a closed issue, but doesn't the required to start with SELECT break support for querying via stored procedure?

Support for stored procedures should still be available according to [documentation](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql) (albeit from October 2019), and multiple other popular blog posts from as recent as September 2020 - which is confusing...

As for potential workarounds...

`Database.ExecuteSqlCommand` is only intended for INSERT, UPDATE, and DELETE - with no support for SELECT.

`Database.GetDbConnection` can allow devs to leverage ADO.NET, but manually mapping values from a `DbDataReader` is cumbersome and doesn't support tracking.

**Comment by jbennink** [comment] 2022-02-10 12:46
I sometimes have small sql scripts that do some logic in the sql and since updating from ef6 full I have notived that this started not  working. I know this might be horrible but I have sql in there that I can copy-paste out to SMSS and run there without many changes. like so:

```
-- Entity framework raw sql parameter renames
declare @campaignid int = @p0;
declare @fromdate datetime = @p1;
declare @todate datetime = @p2;
-- DIRTY HACK FOR NOW
IF @campaignid=-1
 set @campaignid=null;
-- Return the Last appiintment made overall or on 1 campaign
SELECT TOP 1 appointment.createddtm
, agent.resid as agentid, RTrim(agent.name) as agentname
, calendar.resid as calendarid, RTrim(calendar.name) as calendarname
, appointment.fromdate, appointment.appointmentid
FROM appointment appointment with (nolock) 
join clentries entry with (nolock) on appointment.clentryid = entry.clentryid 
join clentryattempts attempt with (nolock) on entry.clentryid=attempt.clentryid and entry.nrofattempts=attempt.attemptnr -- Hmmm last attempt is not always correct
join resdefs agent with (nolock) ON appointment.createduserid=agent.resid 
join resdefs calendar with (nolock) ON appointment.calendarid=calendar.resid 
WHERE appointment.statid=0 
and appointment.fromdate > DateAdd(DAY,-7,getdate())
and appointment.createddtm between @fromdate and @todate 
and (@campaignid is null or attempt.campaignid = @campaignid)
ORDER BY appointment.createddtm DESC

```

which used to work but since migrating to net5.0 and efcore it stopped working

**Comment by camerontbelt** [comment] 2022-10-12 21:56
Is there a fix for this?

**Comment by thomaslevesque** [comment] 2022-10-13 01:31
> Is there a fix for this?

No. And the issue was tagged `closed-by-design`, so I guess there won't be a fix...

**Comment by ajcvickers** [comment] 2022-10-13 09:10
@camerontbelt If you have a case where the SQL _is composable_ but EF Core is saying that it isn't, then please open a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Closed** 2022-10-16 18:40 UTC
Labels: closed-by-design, customer-reported
