### ISSUE TITLE
Npgsql.NpgsqlException: Exception while reading from stream

### ISSUE THREAD

**Issue by robbpriestley** [dotnet/efcore#5404] opened 2016-05-18 02:28 UTC
Trying to get EF working with PostgreSQL using ASP.NET Core 1.0

Worked through a series of dependency, reference, and compile issues.

Successfully did a `dotnet ef migrations add initial` 

(That means it had to compile)

When trying a `dotnet ef database update` I get:

> `Npgsql.NpgsqlException: Exception while reading from stream ---> System.IO.IOException: Unable to read data from the transport connection: Operation timed out. ---> System.Net.Sockets.SocketException: Operation timed out`

But there's no way it can be a timeout in the traditional sense. It happens almost instantaneously. Additionally, I have verified the connection via SQL client to my PostreSQL instance (hosted on Amazon RDS, freshly rebooted, and apparently healthy). I'm sure it's not a goofy typo in my connection string or something like that because I double-checked it. 

Here's what I think are my relevant dependencies:

`"Microsoft.EntityFrameworkCore": "1.0.0-*",`
`"Microsoft.EntityFrameworkCore.Tools": "1.0.0-*",`
`"Npgsql": "3.1.0-*",`
`"Npgsql.EntityFrameworkCore.PostgreSQL": "1.0.0-rc2-release1"`

**Comment by anpete** [comment] 2016-05-18 02:35
cc @roji

**Comment by roji** [comment] 2016-05-18 07:04
@robbpriestley this is probably a duplicate of https://github.com/npgsql/npgsql/issues/1100, let's continue the conversation there. Some notes:

* Please post the OS and version you're on
* You should depend on Npgsql "3.1.0" - remove the floating asterisk. You should probably do the same with EFCore (1.0.0-rc2-final) and EFCore.Tools(1.0.0-preview1-final)
* Can you make sure your NuGet.Config doesn't contain any myget feeds, clear you NuGet caches (%APPLOCALDATA%\.Nuget, %USERPROFILE%\.nuget\packages) and try again?
* Npgsql issues should be opened in [Npgsql.EntityFrameworkCore.PostgreSQL](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL) if they're EFCore-specific, or in [Npgsql](https://github.com/npgsql/Npgsql) if they're at the ADO.NET level.

**Comment by robbpriestley** [comment] 2016-05-18 13:48
@roji thanks. I followed your advice above, issue persists. I'll head over to [npgsql/npgsql#1100](https://github.com/npgsql/npgsql/issues/1100) and check things out. OSX by the way.

**Closed** 2022-10-16 09:41 UTC
