### ISSUE TITLE
Adding to one instance's navigation list is removing entities from another instance's navigation list

### ISSUE THREAD

**Issue by kimimaru4000** [dotnet/efcore#23158] opened 2020-10-30 23:23 UTC
### Include provider and version information

EF Core version: 3.1.8, 3.1.9, 5.0.0-rc.2.20475.6
Database provider: System.Data.SQLite
Target framework: .NET Core 3.1
Operating system: GNU/Linux, potentially Windows and macOS as well

Sidenote: I have not been able to isolate this issue outside my own application.

### Issue
I have `User` models with a `List<UserAbility>` navigation property. There is a static method to update a given user's abilities, adding abilities that aren't present, and enabling them if they are. When updating one user's abilities, saving changes, closing the context, then updating **another** user's abilities, **it removes some of the first user's abilities** despite that user object not being modified at all.

`UserAbility` is a model that references a `PermissionAbility` model, with a `PermAbility` navigation property. [UserAbility model](https://github.com/teamradish/TRTwitchPlaysBot/blob/ModularRefactor/TRBot/TRBot.Data/Models/UserAbility.cs#L27), [User model](https://github.com/teamradish/TRTwitchPlaysBot/blob/ModularRefactor/TRBot/TRBot.Data/Models/User.cs#L29), [PermissionAbility model](https://github.com/teamradish/TRTwitchPlaysBot/blob/ModularRefactor/TRBot/TRBot.Permissions/PermissionAbility.cs#L25).

Here are their relationships, shortened to the relevant bits:
```
modelBuilder.Entity<User>().ToTable("Users", "users");
modelBuilder.Entity<User>(entity =>
{
    entity.HasKey(e => e.id);
    entity.HasMany(e => e.UserAbilities).WithOne(c => c.user).HasForeignKey(u => u.user_id).IsRequired().OnDelete(DeleteBehavior.Cascade);
    entity.HasIndex(e => e.Name);
});

modelBuilder.Entity<PermissionAbility>().ToTable("PermissionAbilities", "permissionabilities");
modelBuilder.Entity<PermissionAbility>(entity =>
{
    entity.HasKey(e => e.id);
    entity.HasIndex(e => e.Name).IsUnique();
});

modelBuilder.Entity<UserAbility>().ToTable("UserAbilities", "userabilities");
modelBuilder.Entity<UserAbility>(entity =>
{
    entity.HasKey(e => e.id);
    entity.HasOne(e => e.PermAbility).WithOne().HasForeignKey<UserAbility>(u => u.permability_id).IsRequired();
    entity.HasIndex(e => new { e.user_id, e.permability_id }).IsUnique();
});
```
Finally, [here is the code updating user abilities](https://github.com/teamradish/TRTwitchPlaysBot/blob/ModularRefactor/TRBot/TRBot.Data/DataHelper.cs#L274) along with [the calling code](https://github.com/teamradish/TRTwitchPlaysBot/blob/ModularRefactor/TRBot/TRBot.Commands/Commands/UpdateUserAbilitiesCommand.cs#L96).

### Reproducing
Reproducing this bug requires a GNU/Linux system (untested on Windows/macOS). Please [download the following project](https://ln2.sync.com/dl/583ac76c0/etrdp4n8-geqi7jiq-kujqc4a7-ungh6x83) and run it in a terminal with `./TRBot.Main`. If it complains about virtual controllers, enable uinput with `sudo modprobe uinput` and give read-write access to it with `sudo chmod a+rw /dev/uinput`. If you wish to build yourself, the full code repository is [here](https://github.com/teamradish/TRTwitchPlaysBot/tree/ModularRefactor) ([build steps](https://github.com/teamradish/TRTwitchPlaysBot/blob/ModularRefactor/Wiki/Building.md)). If building yourself, use the SQLite database file provided in the downloadable project's **Data** folder.

Once it starts, perform the following actions:
1. Type "!userabilities" in the console (yes, while the application is running) and hit enter. It should say that you, "terminaluser", have no abilities.
2. Type "!updateabilities" and hit enter. It should have added 18 abilities. Confirm this with "!userabilities" again afterwards.
3. Type "!updateabilities user2" and hit enter to update the abilities for "user2". Observe that instead of saving 10 changes, there are 20, including some removals as indicated by the logs.
4. Type "!userabilities" again and see that your user, "terminaluser", has fewer abilities now.

To reproduce again, open the **Data/TRBotData.db** file in SQLite or a SQLite browser, and delete all rows in the `UserAbilities` column.

### Attempts
I have tried various solutions, including putting all the code for `UpdateUserAutoGrantAbilities` directly inside the own method, completely removing all other calls to `SaveChanges` outside the given instance, and logging everything I can. Nothing has yielded a different result thus far. At this point I'm led to believe it's a bug with EF Core.

**Comment by ajcvickers** [comment] 2020-11-02 19:11
@tdeeb Can you post the Debug-level log output you see when running this code?

**Comment by tdeeb** [comment] 2020-11-02 21:05
Hi @ajcvickers, you can find the logs below:

[EFCore_23158_BugLogs.txt](https://github.com/dotnet/efcore/files/5478010/EFCore_23158_BugLogs.txt)

Please let me know if you have any questions. I enabled sensitive data logging to output the keys, but I have removed all truly sensitive data from the file. Thank you very much!

**Comment by tdeeb** [comment] 2020-11-03 21:03
@ajcvickers Has the debug log helped? I have since fixed a problem where I was accidentally opening another DbContext while one was open, but the issue persists even with the fix.

**Comment by tdeeb** [comment] 2020-11-05 06:03
Update: Issue persists even if setting the relationships as not required and using `DeleteBehavior.NoAction`.

**Comment by ajcvickers** [comment] 2020-11-06 17:50
@tdeeb In the logs I see this:

```
dbug: 11/02/2020 12:57:53.634 CoreEventId.StateChanged[10807] (Microsoft.EntityFrameworkCore.ChangeTracking) 
      The 'UserAbility' entity with key '{id: 513}' tracked by 'BotDBContext' changed state from 'Unchanged' to 'Modified'.
dbug: 11/02/2020 12:57:53.638 CoreEventId.CascadeDeleteOrphan[10003] (Microsoft.EntityFrameworkCore.Update) 
      An entity of type 'UserAbility' with key '{id: 513}' changed to 'Deleted' state due to severed required relationship to its parent entity of type 'PermissionAbility'.
```

So it looks like at some point `UserAbility` ends up with a nulled-out navigation or FK to 'PermissionAbility'. SInce this is a required relationship, the FK cannot be set to null, and so the `UserAbility` is marked as Deleted.

I have not been able to map this back to your code, and I can't run your code on my machine due to permissions. I would be happy to investigate further if you can reproduce this in a form that I can easily run and debug.

**Comment by tdeeb** [comment] 2020-11-06 18:08
That's the part I'm stumped at. I'm not removing any elements from the list nor nulling the navigation/FK. This leads me to believe that this is the same bug as https://github.com/dotnet/efcore/issues/23180.

**Comment by ajcvickers** [comment] 2020-11-20 15:43
@tdeeb Did you make any progress on reproducing this in a form that we can easily run and debug?

**Comment by tdeeb** [comment] 2020-11-20 19:30
Hi @ajcvickers, unfortunately not, but I've deduced that this is the same bug caused by #23180. After adding `UserAbilities` to the navigation list, they are set to null since `UserAbility` has 2 principal keys: `User` and `PermissionAbility`. The change tracker then sees that they're null and removes them from the navigation list. This is supported by the fact that when I update abilities multiple times on different users, I eventually hit a null reference exception.

**Closed** 2022-10-16 19:07 UTC
Labels: customer-reported
