### ISSUE TITLE
Error with loading the Spatialite extension with v7 of sqlite provider

### ISSUE THREAD

**Issue by dalguy1972** [dotnet/efcore#29833] opened 2022-12-12 15:47 UTC
Using the previous version of the Microsoft.Data.Sqlite (v 6.0.10), I was able to load either the 32-bit or 64-bit version of the spatialite libraries so that I could load spatialite tables with a SHAPE/geospatial column and manipulate them.   When I tried to update the driver to version 7, the code did not work any more and returned an error on the LoadExtension function "'SQLite Error 1: ''.'.   I tried doing this keeping it as .NET 6 and then .NET 7 and got the same results.   I ran it both as it was working as a x64 project and tried it with the Any CPU option, as well as trying the 32-bit libraries and running it as a 32-bit application.   It seems to be specific to the new version of the program, not the .NET version.

### Include version information

Microsoft.Data.Sqlite version: 7.0.0
Target framework: (tried on .NET 6.0 and .NET 7.0)
Operating system:  Windows 11

[tstSpatialiteOnDotNet7.zip](https://github.com/dotnet/efcore/files/10209653/tstSpatialiteOnDotNet7.zip)

**Comment by szekelymatyas** [comment] 2022-12-14 09:45
Same issue here. Im currently using 7.0.0-rc.1.22426.7 which is working fine. When rc 2 hit i run into the same issue. Tried to update to 7.0.0 when came out. Same issue. 7.0.1 has the same issue. Probably degrade to 6 if i cant find any solution.

**Comment by ajcvickers** [comment] 2022-12-15 10:51
Duplicate of #29584.

**Closed** 2022-12-20 16:37 UTC
Labels: closed-duplicate, customer-reported, area-adonet-sqlite
