### ISSUE TITLE
Exception when creating new migration after updating from 6.0-rc.1 to 6.0-rc.2 or 6.0-rtm (daily)

### ISSUE THREAD

**Issue by schuettecarsten** [dotnet/efcore#26405] opened 2021-10-19 20:12 UTC
I've updated my test solution from net6.0-rc.1 and efcore6.0-rc.1 to rc.2 versions. Then I try to add a new migration that drops a table from model class `CloudManagementTool.DataAccess.Model.Supplier.SupInvoiceReconciliationFile` and should create a new table from model class `CloudManagementTool.DataAccess.Model.Supplier.SupInvoice`.

When running the `Add-Migration` command from Package Manager Console, I get the following exception:

```
System.ArgumentException: An item with the same key has already been added. Key: [0, Property: CloudManagementTool.DataAccess.Model.Supplier.SupInvoiceReconciliationFile (Dictionary<string, object>).TenantID (no field, long) Indexer Required FK Index]
   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetSortedProperties(IEntityType entityType, ITable table)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetSortedColumns(ITable table)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Add(ITable target, DiffContext diffContext)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
An item with the same key has already been added. Key: [0, Property: CloudManagementTool.DataAccess.Model.Supplier.SupInvoiceReconciliationFile (Dictionary<string, object>).TenantID (no field, long) Indexer Required FK Index]
```

As the class from the error no longer exists in the code, I have no idea how to fix or workaround this error.

I cannot find any error in the existing migrations, in the class for the new table and in the existing code. The previous code worked as expected. Then I downgraded netcore6.0 and efcore6.0 back to rc.1 and using that version, adding a new migration works without any issues.

```
PM> Add-Migration RefactorSupplier
Build started...
Build succeeded.
An operation was scaffolded that may result in the loss of data. Please review the migration for accuracy.
To undo this action, use Remove-Migration.
```

Working EF Core Product Version: 6.0.0-rc.1.21452.10
Failing EF Core Product Version: 6.0.0-rc.2.21480.5

**Comment by ajcvickers** [comment] 2021-10-21 08:16
@schuettecarsten Please try this with the latest [daily build](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md). If you are still running into errors, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by schuettecarsten** [comment] 2021-10-21 13:25
Woohoo, sorry, the issue is still there with latest rtm version, but it looks like it only occurs when a table is dropped and a new table is created, and both table names are very similar. In my case, the dropped table name is `InvoiceReconciliationFile` and the new tables are named `Invoice` and `ReconciliationFile`, all in schema `sup`.

**Comment by ajcvickers** [comment] 2021-11-05 16:34
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by SmithE65** [comment] 2021-11-12 00:55
This is not the exact scenario as above but I get the same stack trace.  I think I have a repro here: https://github.com/SmithE65/TableRename

Maybe not as minimal as could be.
```csharp
public class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions options) : base(options)
    {
    }

    public DbSet<Entity1>? Entity1s { get; set; }
    public DbSet<Entity2>? Entity2s { get; set; }
    public DbSet<Entity3>? Entity3s { get; set; }
}

// ....

public class Entity1
{
    public int Id { get; set; }
    public int Entity2Id { get; set; }
    [ForeignKey(nameof(Entity2Id))]
    public Entity2? Entity2Navigation { get; set; }
    public int Entity3Id { get; set; }
    [ForeignKey(nameof(Entity3Id))]
    public Entity3? Entity3Navigation { get; set; }
}

public class Entity2
{
    public int Id { get; set; }
    [InverseProperty(nameof(Entity1.Entity2Navigation))]
    public ICollection<Entity1> Entity1s { get; set; } = new List<Entity1>();
}

public class Entity3
{
    public int Id { get; set; }
    [InverseProperty(nameof(Entity1.Entity3Navigation))]
    public ICollection<Entity1> Entity1s { get; set; } = new List<Entity1>();
}
```
I create the three entities as above, create an Initial migration, rename Entity1 class and rename Entity1s DbSet, and attempt to create a second migration.  Migration fails with below exception and trace:
```
System.ArgumentException: An item with the same key has already been added. Key: [0, Property: TableRename.Entity1 (Dictionary<string, object>).Entity3Id (no field, int) Indexer Required FK Index]
   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetSortedProperties(IEntityType entityType, ITable table)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetSortedColumns(ITable table)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Add(ITable target, DiffContext diffContext)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
An item with the same key has already been added. Key: [0, Property: TableRename.Entity1 (Dictionary<string, object>).Entity3Id (no field, int) Indexer Required FK Index]
```
If I rename just the Entity1 class, create an empty migration, rename the DbSet, and then create a migration with the table rename, everything works as expected.  I have to change BOTH for the migration to fail.

**Comment by ajcvickers** [comment] 2021-11-16 23:10
Confirmed repro.

**Comment by christallire** [comment] 2021-11-27 01:28
I get this a lot and I think this should be addressed ASAP.

I get this almost everything when I'm trying to delete or rename the table. @ajcvickers

**Comment by christallire** [comment] 2021-11-27 01:40
Deleting a table can be manually workaround by
Deleting TWO fluent model builder statements in the snapshot file. and in DBMS.

I think renaming can be done in the same manner, but this is a temporary solution. not ideal, but it can make it work anyways..

**Comment by davidkarlsson** [comment] 2021-11-29 16:30
I'm also getting this error when I try to add a migration that removes a table. Is there any workaround that still lets you scaffold a migration that drops the table somehow?

Or is the only solution to manually delete any trace of the table from the snapshot file and then add then manually add the drop table sql to an empty migration? Is this a viable workaround or could it mess up some internal state that I'm unaware of?

**Comment by ajcvickers** [comment] 2021-11-29 16:49
@davidkarlsson We will discuss when all the required people are available.

**Comment by Martijn-W** [comment] 2021-12-09 09:39
@ajcvickers is there any update on this?
I just had to drop all migrations and start over because of this bug. Luckily our code is not production ready yet, so only our development environment was affected. But it would suck if we had encountered this bug on production ready software.
Sadly manually editing the snapshot file was not an option due to the many changes that were made to the database model.

**Comment by ihordeyneka** [comment] 2021-12-09 09:48
I have the same problem - rename/delete tables are basically broken now. Would be great to know if there's any idea when this will be fixed.

**Comment by ajcvickers** [comment] 2021-12-09 10:07
Note from triage: we're looking into this for the 6.0.2 patch. See the [planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for more information on how we decide what to patch.

**Comment by schuettecarsten** [comment] 2021-12-09 17:29
> Note from triage: we're looking into this for the 6.0.2 patch. 
Thank you. Version 6.0.2 will be released mid of January 2022, is that correct?

**Comment by AndriySvyryd** [comment] 2021-12-09 21:35
> Thank you. Version 6.0.2 will be released mid of January 2022, is that correct?

It's scheduled for February 2022 due to many people taking vacations in December.

**Comment by glenkitchen** [comment] 2021-12-22 05:50
This worked for me. Undelete entities for now. (Will delete after 6.0.2. released)

**Comment by warappa** [comment] 2021-12-29 11:08
In my case I was replacing the term `Download` with `Asset` in my whole model, with the term being used in foreign keys, tables, navigation properties etc.

`dotnet ef migrations add ...` raised the mentioned exception.

### Workaround
1. Rename foreign keys, navigation properties, collections etc as you wish
2. In the entity type configurations, ensure the **entity-table-names** containing this name are **still using the *old* name** (i.e. "Downloads", "DownloadTranslations") - read: ensure all `.ToTable(...)` expressions use the old name, and, if they don't exist, add them.   
(I *think* foreign key names etc. can already use the new name)
3. Create a new migration with `dotnet ef migrations add ...` - **no exception**
4. Rename the tables to their new names (i.e. "Assets", "AssetTranslations")
5. Create a new migration with `dotnet ef migrations add ...` - **no exception**

### Infos
EF Core version: 6.0.1
EF Core tool version: 6.0.1

**Comment by mattstewart1189** [comment] 2021-12-30 21:28
@warappa thanks for this. I was able to take care of my renames quickly. I had a few a couple weeks ago that had me pulling my hair out.

**Comment by systemutvecklare** [comment] 2022-01-03 13:10
I also got this error when dropping a table and some related tables. A solution that worked for me when removing an entity and getting this error was to 

1. Remove one navigation property (and corresponding foreign key) at a time from the entity and create a migration for each removal. 
2. When no more navigation properties were left in the entity I could remove it and create a final migration without the error message.

In my case I couldn't wait for a new release in february. I spent a whole day with trial and errors before succeeding

**Closed** 2022-01-04 11:18 UTC
Labels: type-bug, closed-fixed, regression, customer-reported, Servicing-approved, area-migrations

**Comment by Tragetaschen** [comment] 2022-01-12 12:28
I know it's fixed and scheduled for Release, but not having access to a preview package for the patch release to unblock the scenarios that are affected is… annoying (see https://github.com/dotnet/efcore/issues/26632#issuecomment-989896297).
I wish there was a better way than waiting for several weeks :-/

**Comment by ajcvickers** [comment] 2022-01-12 12:49
@Tragetaschen Agreed. However, you can use the 7.0.0 [daily build](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md), which has the 6.0.2 patches in it, and not much else at this point in the release cycle.

**Comment by MCFHTAGENTS** [comment] 2022-01-20 07:42
Silly question - where do I find .NET Core 7? as there is a dependency on that (obviously) for the proposed fix - I have an April deadline for some changes and can't wait until February!

**Comment by ajcvickers** [comment] 2022-01-20 08:28
@MCFHTAGENTS 

> here is a dependency on that (obviously) for the proposed fix

There should not be any dependency on .NET 7. Where are you seeing that?

**Comment by MCFHTAGENTS** [comment] 2022-01-20 08:33
When trying to install the packages:

````
NU1202: Package Microsoft.AspNetCore.Identity.EntityFrameworkCore 7.0.0-alpha.1.22069.7 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Microsoft.AspNetCore.Identity.EntityFrameworkCore 7.0.0-alpha.1.22069.7 supports: net7.0 (.NETCoreApp,Version=v7.0)

NU1202: Package Microsoft.AspNetCore.DataProtection.EntityFrameworkCore 7.0.0-alpha.1.22069.7 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Microsoft.AspNetCore.DataProtection.EntityFrameworkCore 7.0.0-alpha.1.22069.7 supports: net7.0 (.NETCoreApp,Version=v7.0)
````

**Comment by ajcvickers** [comment] 2022-01-20 09:13
@MCFHTAGENTS Do you need to update your ASP.NET Core packages as well?  The EF Core packages should work with .NET 6, without updating any ASP.NET packages.

**Comment by MCFHTAGENTS** [comment] 2022-01-20 09:16
That is very likely! Where do I get them from - assume I need another nuget feed for example?!

**Comment by ajcvickers** [comment] 2022-01-20 09:17
@MCFHTAGENTS They are in the daily build feed shown in the instructions linked above.

**Comment by ajcvickers** [comment] 2022-01-20 10:17
@MCFHTAGENTS Looks like the daily builds might not work for ASP.NET Core applications.

**Comment by MCFHTAGENTS** [comment] 2022-01-20 10:26
hmm - oh to get a nightly for 6.0.2.....

**Comment by Sebazzz** [comment] 2022-01-21 14:48
There is no nightly for 6.0.2 and using 7.0.0 was not trivial . I resorted to removing the affected tables (that needed deletion) from the snapshot file, then generate the migration.

**Comment by shubhamranjan** [comment] 2022-02-03 20:22
> I also got this error when dropping a table and some related tables. A solution that worked for me when removing an entity and getting this error was to
> 
>     1. Remove one navigation property (and corresponding foreign key) at a time from the entity and create a migration for each removal.
> 
>     2. When no more navigation properties were left in the entity I could remove it and create a final migration without the error message.
> 
> 
> In my case I couldn't wait for a new release in february. I spent a whole day with trial and errors before succeeding

To anyone who can't wait for the fix. IMO, this is the easiest workaround available.
