### ISSUE TITLE
Any search with Where clause fails in EF Core for Complex types

### ISSUE THREAD

**Issue by fingers10** [dotnet/efcore#22292] opened 2020-08-28 10:18 UTC
I'm trying to select rows in table that matches any items in a given list. I have done this previously with `List<string>` and that worked. Now I'm trying the same with `List<ComplexType>` and it fails.

**`Test` Entity:**

```c#
public class Test
{
    protected Test()
    {
    }

    public string jobno { get; set; }
    public int objno { get; set; }
}
```
**`DbContext` and Entity Configuration:**

```c#
public class TestContext : DbContext
{
    public DbSet<Test> Test { get; set; }

    static ILoggerFactory ContextLoggerFactory
    => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=.\\;Database=Test;Trusted_Connection=true;")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Test>(entity =>
        {
            entity.HasKey(e => new { e.jobno, e.objno });
        });
    }
}
```

**ComplexType to Search:**

```c#
public class JobAndDocumentId
{
    public string JobId { get; set; }
    public int ObjNo { get; set; }
}
```

**Steps to Reproduce:**

```c#
class Program
{
    static async Task Main(string[] args)
    {
        var jobDocumentIds = new List<JobAndDocumentId> {
            new JobAndDocumentId { JobId = "TEST", ObjNo = 1 },
            new JobAndDocumentId { JobId = "TEST", ObjNo = 2 },
            new JobAndDocumentId { JobId = "TEST", ObjNo = 3 } };

        using var ctx = new TestContext();
        //ctx.Database.EnsureDeleted();
        //ctx.Database.EnsureCreated();

        var conditions = jobDocumentIds.Select(x => $"(RTRIM(LTRIM(JOBNO)) = '{x.JobId}' AND OBJNO = {x.ObjNo})").ToList();
        var condition = string.Join(" OR ", conditions);

        // works
        var rawtest = ctx.Test.FromSqlRaw($"SELECT * FROM TEST WHERE {condition}").ToList();

        // fails
        var test = ctx.Test.Where(x => jobDocumentIds.Any(y => x.jobno.Trim() == y.JobId && x.objno == y.ObjNo)).ToList();
    }
}
```

When I use `FromSqlRaw`, it works fine.

```c#
var rawtest = ctx.Test.FromSqlRaw($"SELECT * FROM TEST WHERE {condition}").ToList();
```

But this fails when I make a Any Search,
```c#
var test = ctx.Test.Where(x => jobDocumentIds.Any(y => x.jobno.Trim() == y.JobId && x.objno == y.ObjNo)).ToList();
```

and throws exception

>The LINQ expression 'DbSet<Test>.Where(t => __jobDocumentIds_0.Any(y => t.jobno.Trim() == y.JobId && t.objno == y.ObjNo))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

Any assistance on how to make this work without `FromSqlRaw`?

### Further technical details

EF Core version: 3.1.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.2

**Comment by ajcvickers** [comment] 2020-08-28 17:44
@smitpatel to de-dupe.

**Comment by smitpatel** [comment] 2020-08-28 17:46
Duplicate of #19070

**Closed** 2022-10-16 18:38 UTC
Labels: customer-reported
