### ISSUE TITLE
MIgrations :: invalid migration created during table rename with navigations - need topological sort

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#1980] opened 2015-04-02 18:02 UTC
example of a migration created:

```
            migration.DropForeignKey(name: "FK_Gear_City_AssignedCityNameId", table: "Gear");
            migration.DropForeignKey(name: "FK_Gear_City_CityOrBirthName", table: "Gear");
            migration.AlterColumn(
                name: "CityOrBirthName",
                table: "Gear",
                type: "nvarchar(450)",
                nullable: false);
            migration.AddForeignKey(
                name: "FK_Gear_MyTable_City_AssignedCityNameId",
                table: "Gear",
                column: "AssignedCityNameId",
                referencedTable: "MyTable_City",
                referencedColumn: "NameId");
            migration.AddForeignKey(
                name: "FK_Gear_MyTable_City_CityOrBirthName",
                table: "Gear",
                column: "CityOrBirthName",
                referencedTable: "MyTable_City",
                referencedColumn: "NameId");
            migration.RenameTable(
                name: "City",
                newName: "MyTable_City");
```

Exception:

System.Data.SqlClient.SqlException (0x80131904): Foreign key 'FK_Gear_MyTable_City_AssignedCityNameId' references invalid table 'MyTable_City'.
At line:1 char:1
- dnx . ef migration apply
- ~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (System.Data.Sql...'MyTable_City'.:String) [], RemoteException
  - FullyQualifiedErrorId : NativeCommandError

Could not create constraint. See previous errors.
   at System.Data.SqlClient.SqlConnection.OnError(SqlExcepti
on exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.<>c__DisplayClass7_0.<ExecuteNonQuery>b__0()
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.Execute(IRelationalConnection connection, Func`1 action)
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.ExecuteNonQuery(IRelationalConnection connection, DbTransaction transaction, IEnumerable`1 sqlBatches)
   at Microsoft.Data.Entity.Relational.Migrations.Migrator.Execute(IEnumerable`1 sqlBatches, Boolean ensureDatabase)
   at Microsoft.Data.Entity.Relational.Migrations.Migrator.ApplyMigrations(String targetMigration)
   at Microsoft.Data.Entity.Commands.MigrationTool.ApplyMigration(String migrationName, String contextTypeName)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass10_0.<ApplyMigration>b__0()
   at Microsoft.Data.Entity.Commands.Program.ExecuteInDirectory(String startupProject, Func`1 invoke)
   at Microsoft.Data.Entity.Commands.Program.ApplyMigration(String migration, String context, String startupProject)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass7_2.<Main>b__8()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Data.Entity.Commands.Program.Main(String[] args)

**Comment by bricelam** [comment] 2015-04-13 21:53
Dupe of #1907

**Closed** 2022-10-16 08:54 UTC
