### ISSUE TITLE
Add support for many-to-many relations without navigation property

### ISSUE THREAD

**Issue by momvart** [dotnet/efcore#23286] opened 2020-11-12 16:43 UTC
Sometimes, it happens that we are only interested in one side of a many-to-many relationship. So, there would be only one navigation property in one of the entries.

Example:
```cs
public class Widget 
{
    public int Id { get; set; }
    public string Name { get; set; }
}
public class User
{
    public int Id { get; set; }
    public string Username { get; set; }
    public ICollection<Widget> StarredWidgets { get; set; }
}
```
This is a [question ](https://stackoverflow.com/questions/16718699/map-many-to-many-relationship-without-navigation-property) asked on stackoverflow and the accepted answer is this which uses an empty version of `WithMany` (Entity Framework):
```cs
modelBuilder.Entity<User>()
    .HasMany(u => u.StarredWidgets)
    .WithMany() // <- no parameter here because there is no navigation property
    .Map(m =>
    {
        m.MapLeftKey("UserId");
        m.MapRightKey("WidgetId");
        m.ToTable("UserWidgets");
    });
```

Is it possible to add support for defining this kind of relationship?

**Comment by ajcvickers** [comment] 2020-11-12 16:52
Duplicate of #3864. Make sure to vote for that issue!

**Closed** 2022-10-16 19:09 UTC
Labels: closed-duplicate, customer-reported
