### ISSUE TITLE
Better translation of string comparison

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#19733] opened 2020-01-28 22:26 UTC
For `string.Compare(s1, s2) > 0`, we currently [generate](https://github.com/dotnet/efcore/blob/9abd61d3fb4cdd1041f25fe2e10c70ee3dc4055e/src/EFCore.Relational/Query/Internal/ComparisonTranslator.cs#L13):

```sql
SELECT [b].[Id], [b].[Name]
FROM [Blogs] AS [b]
WHERE CASE
    WHEN N'hello' = [b].[Name] THEN 0
    WHEN N'hello' > [b].[Name] THEN 1
    WHEN N'hello' < [b].[Name] THEN -1
END > 0
```

We could pattern-match this and just do `WHERE N'hello' > [b].[Name]` - I suspect this may actually use string indexes in at least some databases.

(same also for string.CompareTo)

**Comment by maumar** [comment] 2020-01-29 19:39
dupe of https://github.com/dotnet/efcore/issues/16092

**Closed** 2022-10-16 18:08 UTC
