### ISSUE TITLE
Select method fails when objects have numeric properties smaller than Int64

### ISSUE THREAD

**Issue by CJPrindle** [dotnet/efcore#20113] opened 2020-03-01 02:55 UTC
When attempting to select rows from Sql Server that match a property value of the current entity an error is raised stating: **Unable to cast object of type 'System.Int64' to type 'System.Int32'**

The result of the operation should a list of IDs of the records that match the values specified in the **Select** method criteria.

To fix the issue I must change all the properties in my entity object from Int32 to Int64.

### Steps to reproduce

The entity is defined as:

```C#
public class SampleEntity
{
    [Key]
    [Column(Order = 0)]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ID { get; set; }

    public string Name { get; set; }
     
    public int Port { get; set; }
}
```
My call is defined as:

```C#
query.Select<SampleEntity, List<int>>(
     se => se.Port == sampleEntity.Port,
     se => new List<SampleEntity>() { se.ID });
```      

Which calls the **Select** method:

```C#
public virtual IList<TReturn> Select<T, TReturn>(Expression<Func<T, bool>> criteria,
    Expression<Func<T, TReturn>> selector) where T : class =>
    DatabaseContext.Set<T>().AsNoTracking()
        .Where(criteria)
        .Select(selector)
        .ToList();
```

### Error Details

```
_System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.Int64' to type 'System.Int32'.
  Source=Microsoft.Data.SqlClient
  StackTrace:
   at Microsoft.Data.SqlClient.SqlBuffer.get_Int32()
   at Microsoft.Data.SqlClient.SqlDataReader.GetInt32(Int32 i)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in /_/src/EFCore/Query/Internal/QueryCompiler.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in /_/src/EFCore/Query/Internal/EntityQueryProvider.cs:line 79
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at NewTheory.Core.Data.Query.Select[T,TReturn](Expression`1 criteria, Expression`1 selector) in C:\code\New Theory 2\NewTheory\Core\Data\Query.cs:line 502
   at ConsoleTest.QueryTests.FindTests() in C:\code\New Theory 2\NewTheory\Test\ConsoleTest\QueryTests.cs:line 45
   at ConsoleTest.Program.Main() in C:\code\New Theory 2\NewTheory\Test\ConsoleTest\Program.cs:line 12_
```
### Further technical details

EF Core version: 3.1.2
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Standard 2.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.1

**Comment by ErikEJ** [comment] 2020-03-01 08:35
Could you share your SQL Server table definition? (CREATE TABLE statement)

**Comment by ajcvickers** [comment] 2020-03-09 16:15
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:14 UTC
Labels: closed-could-not-reproduce, customer-reported
