### ISSUE TITLE
CS8619 nullable warning when call 'FirstOrDefaultAsync(...)' method.

### ISSUE THREAD

**Issue by wu-yafeng** [dotnet/efcore#24287] opened 2021-02-26 06:10 UTC
## Problem
Asynchronous method should return nullable-reference-type.

``` csharp
        public Task<Entity?> Find()
        {
            return DbContext.Entities.FirstOrDefaultAsync(); // this line will report warn 'CS8619' 
        }
```

## Solution

Use sync method: `FirstOrDefault(...)`

or

add `async` to method :`public Task<Entity?> Find()`

EFCore asynchronous API:`FirstOrDefaultAsync()` declared returns a non-nullable-reference-type. It should returns a nullable-reference-type.

**Comment by roji** [comment] 2021-02-26 08:11
Duplicate of #19007

**Comment by roji** [comment] 2021-02-26 08:13
@wu-yafeng EF Core 5.0 isn't yet annotated for nullable reference types, but work is ongoing for 6.0, which will be completely annotated. 6.0-preview2 should already be substantially annotated, including the case you've indicated above.

**Closed** 2022-10-16 19:25 UTC
Labels: closed-duplicate, customer-reported
