### ISSUE TITLE
I can't use "dotnet ef database update --environment RELEASE"

### ISSUE THREAD

**Issue by codeoflin** [dotnet/efcore#17984] opened 2019-09-21 17:20 UTC
I saw some argv in this website, but it does not work for me:

https://www.learnentityframeworkcore.com/migrations/commands/cli-commands
![image](https://user-images.githubusercontent.com/45932283/65376834-779c2a00-dcc2-11e9-8723-dab5f24d2a7f.png)

![image](https://user-images.githubusercontent.com/45932283/65171600-d9f9ee00-da68-11e9-9e23-f4a9f19a9955.png)

![image](https://user-images.githubusercontent.com/45932283/65171699-188fa880-da69-11e9-911a-f7d0922d2fb7.png)

what should I replace?

**Comment by smitpatel** [comment] 2019-09-21 18:22
Duplicate of #15026

**Closed** 2022-10-16 14:43 UTC
Labels: customer-reported
