### ISSUE TITLE
Getting SqlNullValueException after upgrading to .Net Core 2.2

### ISSUE THREAD

**Issue by JoeManJoe2016** [dotnet/efcore#14467] opened 2019-01-19 15:16 UTC
I was using .Net Core 2.1 and everything was fine. I just upgraded to .Net Core 2.2, and have started to see the following error: "SqlNullValueException: Data is Null. This method or property cannot be called on Null values."
My code lines are:

`var sl = _context.Assets.OrderBy(e => e.Name);
var slCnt = sl.Count();
            var selectlist = new SelectList(sl, "AssetId", "Name").ToList();`

On hitting the last of the 3 statements above, the code breaks with the said error. The 'sl' object is created, and I can get the count from the first two statements. Also, both AssetId and Name are non-null fields in the database, and I have checked to confirm that there is no null value in either column.

I should point out that all other SelectLists (for the other entities) work well even in 2.2.  I am just not sure what is different with the Assets entity which has not changed since upgrading to 2.2.

### Further technical details
EF Core version: 2.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.5

**Comment by khatrizeeshan** [comment] 2019-03-16 06:31
Facing the same issue, is there any work around?

**Comment by khatrizeeshan** [comment] 2019-03-16 06:35
| Name | Value | Type
-- | -- | -- | --
  | StackTrace | "   at System.Data.SqlClient.SqlBuffer.get_DateTime()\r\n   at System.Data.SqlClient.SqlDataReader.GetDateTime(Int32 i)\r\n   at lambda_method(Closure , DbDataReader , DbContext )\r\n   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider._FastQuery[TEntity](RelationalQueryContext relationalQueryContext, ShaperCommandContext shaperCommandContext, Func`3 materializer, Type contextType, IDiagnosticsLogger`1 logger)+MoveNext()\r\n   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at IGMP.Service.SearchService.Search(PagedSorted`1 pagedSorted) in D:\\Projects\\igmp\\source\\repos\\igmp-server\\IGMP.Service\\SearchService.cs:line 82\r\n   at IGMP.WebApi.Controllers.SearchController.Post(PagedSorted`1 parameters) in D:\\Projects\\igmp\\source\\repos\\igmp-server\\IGMP.WebApi\\Controllers\\SearchController.cs:line 23\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()" | string

**Comment by ajcvickers** [comment] 2019-03-18 15:52
@khatrizeeshan Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can fully investigate.

**Comment by ajcvickers** [comment] 2019-03-25 16:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by cryeshiren** [comment] 2019-04-22 08:02
@ajcvickers Why did you close the question? It's a serious problem, and I have the same problem.

**Comment by ajcvickers** [comment] 2019-04-22 16:34
@cryeshiren We haven't been able to reproduce. If you can post a small, runnable project/solution or complete code listing then we will will be able to fully investigate.

**Comment by khatrizeeshan** [comment] 2019-04-24 10:37
@dong have you made your date variable nullable?

I had the same issue and i made the above mentioned mistake.

**Comment by cryeshiren** [comment] 2019-04-29 09:18
@khatrizeeshan yes, I have some nullable field, mapping the allow null database field,
so, should I remove the nullable type?

**Comment by cryeshiren** [comment] 2019-04-29 09:24
I use some nullable guid and nullable DateTime in .net core 2.1, what should I do?
@ajcvickers @khatrizeeshan

**Comment by cryeshiren** [comment] 2019-04-29 09:30
This problem occurs  with nullable guid or nullable datetime, in my project

**Comment by smitpatel** [comment] 2019-04-29 16:42
This error happens when materializing query results is expecting non-null values but the value in results in database contains NULL. The cause of error could be bad data, incorrect model or bug in query pipeline to infer the type nullability correctly. Without a repro project we cannot determine the cause. Please post a runnable project which demonstrate the issue.

**Comment by ajcvickers** [comment] 2019-05-06 16:14
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by Enngage** [comment] 2019-05-17 12:29
I've experienced this issue when going from .NET Core 2.2 to 3-preview5 and it was caused by the fact I had abstract Entity class that contained `[Required]` attribute on `nullable `property. I would assume that same thing can happen if you configure required property via fluent API. 

.Net Core 2.2 didn't seem to care and it worked perfectly fine, but the correct behavior is the one implemented in .NET Core 3 and this has admittedly been my mistake.

For reference I had something like:

```
public abstract class BaseEntityWithOptionalUserStamp<TEntity> : BaseEntity<TEntity>, IEntityWithOptionalUserStamp where TEntity : class, IEntity, new()
    {
        [Required]
        public int? CreatedByUserId { get; set; }

        public User CreatedByUser { get; set; }
    }
```

**Comment by diepng** [comment] 2019-07-22 02:36
I have an ASP .NET core 2.1 web application for some time now. I has been working just fine and after  upgrading to .NET core 2.2, I'm now getting this error "SqlNullValueException: Data is Null. This method or property cannot be called on Null values.". It's frustrating but I'm sure with enough time I'll figure it out.

**Comment by progmars** [comment] 2019-07-24 16:01
So, that means we cannot put validation attributes on our entities because that might break EF. Sigh. Ok, will have to do the validation on a separate viewmodel entities only.

**Comment by smitpatel** [comment] 2019-07-24 19:03
> So, that means we cannot put validation attributes on our entities because that might break EF. 

That is incorrect conclusion. You can put `Required` attribute as needed but when reading value of such column from database it has to have a value. If it has null, it will throw exception. i.e. if data in database does not match the validation attributes you use then it is error.

**Comment by ajcvickers** [comment] 2019-07-24 19:29
Also, EF can be configured (in `OnModelCreating`) to ignore the `Required` attribute and allow nulls.

**Comment by progmars** [comment] 2019-07-24 20:01
> If it has null, it will throw exception. i.e. if data in database does not match the validation attributes you use then it is error.

Yes, that's exactly how I ended here - I put a `[Required]` on a nullable `DateTime?` property (it needs to be nullable to avoid being set to default value when no value received, leading to `[Required]` never working during HTTP POST validation scenarios) and then I got that exception when reading a list of entities from the database.

> Also, EF can be configured (in `OnModelCreating`) to ignore the `Required` attribute and allow nulls.

Thanks for the hint, that might be useful.

**Comment by jwhitener6** [comment] 2019-11-04 04:22
This was my issue migrating from 2.2 to Core 3.0. spent far too much time figuring this out. It makes sense that [required] would mean non-nullable but I saw nothing in the change notes.

Thanks

**Closed** 2022-10-16 13:48 UTC
Labels: closed-could-not-reproduce, customer-reported
