### ISSUE TITLE
Wierd casting/type conversion behavior between tinyint and byte thows exception

### ISSUE THREAD

**Issue by mrmartan** [dotnet/efcore#12886] opened 2018-08-03 14:41 UTC
I am mapping byte property to SQL Server's tinyint column and this is what I am getting.

**An exception occurred while reading a database value for property 'EventContentMetadata.Id'. The expected type was 'System.Byte' but the actual value was of type 'System.String'. ---&gt; System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Byte'.**

```
[14:08:32 DBG] Executing DbCommand [Parameters=[@__newMetadata_ContentType_0='application/msgpack' (Size = 200), @__newMetadata_ContentEncoding_1='LZ4' (Size = 100)], CommandType='Text', CommandTimeout='30']
SELECT TOP(2) [ecm].[Id], [ecm].[ContentEncoding], [ecm].[ContentType]
FROM [EventContentMetadata] AS [ecm]
WHERE ([ecm].[ContentType] = @__newMetadata_ContentType_0) AND ([ecm].[ContentEncoding] = @__newMetadata_ContentEncoding_1)
[14:08:32 DBG] Opened connection to database 'XXX' on server 'XXX'.
[14:08:32 DBG] Executing DbCommand [Parameters=[@__newMetadata_ContentType_0='application/msgpack' (Size = 200), @__newMetadata_ContentEncoding_1='LZ4' (Size = 100)], CommandType='Text', CommandTimeout='30']
SELECT TOP(2) [ecm].[Id], [ecm].[ContentEncoding], [ecm].[ContentType]
FROM [EventContentMetadata] AS [ecm]
WHERE ([ecm].[ContentType] = @__newMetadata_ContentType_0) AND ([ecm].[ContentEncoding] = @__newMetadata_ContentEncoding_1)
[14:08:32 INF] Executed DbCommand (0ms) [Parameters=[@__newMetadata_ContentType_0='application/msgpack' (Size = 200), @__newMetadata_ContentEncoding_1='LZ4' (Size = 100)], CommandType='Text', CommandTimeout='30']
SELECT TOP(2) [ecm].[Id], [ecm].[ContentEncoding], [ecm].[ContentType]
FROM [EventContentMetadata] AS [ecm]
WHERE ([ecm].[ContentType] = @__newMetadata_ContentType_0) AND ([ecm].[ContentEncoding] = @__newMetadata_ContentEncoding_1)
[14:08:32 DBG] A data reader was disposed.
[14:08:32 DBG] Closing connection to database 'XXX' on server 'XXX'.
[14:08:32 DBG] Closed connection to database 'XXX' on server 'XXX'.
[14:08:32 ERR] An exception occurred in the database while iterating the results of a query for context type 'MyDbContext'.
System.InvalidOperationException: An exception occurred while reading a database value for property 'EventContentMetadata.Id'. The expected type was 'System.Byte' but the actual value was of type 'System.String'. ---&gt; System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Byte'.
   at System.Data.SqlClient.SqlBuffer.get_Byte()
   at System.Data.SqlClient.SqlDataReader.GetByte(Int32 i)
   at lambda_method(Closure , DbDataReader )
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
System.InvalidOperationException: An exception occurred while reading a database value for property 'EventContentMetadata.Id'. The expected type was 'System.Byte' but the actual value was of type 'System.String'. ---&gt; System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Byte'.
   at System.Data.SqlClient.SqlBuffer.get_Byte()
   at System.Data.SqlClient.SqlDataReader.GetByte(Int32 i)
   at lambda_method(Closure , DbDataReader )
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext() 
```

Model
```c#
public class EventContentMetadata
{
    public byte Id { get; set; }

    public string ContentType { get; set; }
    public string ContentEncoding { get; set; }

    public ICollection<Event> Events { get; set; } 
}
```
Mapping
```c#
modelBuilder.Entity<EventContentMetadata>(entity =>
{
    entity.ToTable("EventContentMetadata");

    entity.HasKey(e => e.Id).ForSqlServerIsClustered();
    entity.Property(e => e.Id).HasColumnType("tinyint").UseSqlServerIdentityColumn();

    entity.Property(e => e.ContentEncoding).HasColumnType("nvarchar(100)").HasMaxLength(100).IsRequired();
    entity.Property(e => e.ContentType).HasColumnType("nvarchar(200)").HasMaxLength(200).IsRequired();
});
```
Database
```sql
CREATE TABLE [dbo].[EventContentMetadata](
	[Id] [tinyint] IDENTITY(1,1) NOT NULL,
	[ContentType] [nvarchar](200) NOT NULL,
	[ContentEncoding] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_EventContentMetadata] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer, SQL Server running on Windows - Compatibility level - SQL Server 2017 (140)
Operating system: linux docker container
Runtime: microsoft/dotnet:2.1.2-aspnetcore-runtime

**Comment by ajcvickers** [comment] 2018-08-06 01:11
@mrmartan I have not been able to reproduce this. Can you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by mrmartan** [comment] 2018-08-06 07:56
Well, the problem is I cannot reproduce it on purpose myself (although I have not tried mixed environment, app on Linux, DB on Windows). I just know it happens repeatedly but not reliably (I forgot to write in the opener that it does not happen all the time). If I were able to reproduce it I might collect SQL Server's traces as well.

I did thought you might be able to find the bug though. See the exception message states `Unable to cast object of type 'System.String' to type 'System.Byte'.` but the in the stack trace you can see `GetBytes(Int32)` being called. Calling `GetBytes(Int32)` might make sense as I can imagine you treat db's tinyint as Int32.

Could this be an issue in System.Data.SqlClient?

Additionally, over the weekend I noticed this same issue was happening for other type pairs. I could post you all of them.

Unfortunately I can't tell when this started to happen. I am sure it was not happening on .NET/EFC 2.0 and SQL Server 2014

**Comment by mrmartan** [comment] 2018-08-08 11:41
So I have found out that this is actually caused by a single query. I am also conviced it is a bug on your part.

This query does **not** cause the issue:
```c#
await this.context.RealizedConsents
    .Where(rc =>
            rc.State == OneSqlStore.ConsentState.Given
        && rc.PurposeName == command.Purpose.Name
        && (rc.UpdatedAt < consentHadToBeGivenAtLeastAt
            || (rc.RevokeRequestedAt.HasValue && rc.RevokeRequestedAt < revokeRequestHadToBeGivenAtLeastAt)))
    .Select(rc => new Domain.QueryModel.Consent
    {
        Purpose = rc.PurposeName,
        Subject = new Domain.QueryModel.Subject
        {
            SubjectId = rc.SubjectId,
            FirstName = rc.SubjectFirstName,
            MiddleName = string.Empty,
            LastName = rc.SubjectLastName,
            Email = rc.SubjectEmail,
            Phone = rc.SubjectPhone
        },
        State = Domain.QueryModel.ConsentState.Given,
        AdditionalData = rc.AdditionalData
    })
    .ToListAsync(cancellation);
```

This query **does** cause the isuue (notice the OrderBy and Take calls):
```c#
await this.readContext.RealizedConsents
    .Where(rc =>
            rc.State == OneSqlStore.ConsentState.Given
        && rc.PurposeName == command.Purpose.Name
        && (rc.UpdatedAt < consentHadToBeGivenAtLeastAt
            || (rc.RevokeRequestedAt.HasValue && rc.RevokeRequestedAt < revokeRequestHadToBeGivenAtLeastAt)))
    .OrderBy(rc => rc.UpdatedAt)
    .Take(500) // does not matter how many
    .Select(rc => new Domain.QueryModel.Consent
    {
        Purpose = rc.PurposeName,
        Subject = new Domain.QueryModel.Subject
        {
            SubjectId = rc.SubjectId,
            FirstName = rc.SubjectFirstName,
            MiddleName = string.Empty,
            LastName = rc.SubjectLastName,
            Email = rc.SubjectEmail,
            Phone = rc.SubjectPhone
        },
        State = Domain.QueryModel.ConsentState.Given,
        AdditionalData = rc.AdditionalData
    })
    .ToListAsync(cancellation);
```

```c#
public class OneSqlStore : DbContext
{
    // other code ommited

    public DbSet<RealizedConsent> RealizedConsents { get; set; }
}

public class RealizedConsent
{
    public RealizedConsent()
    {
        this.SubjectFirstName = string.Empty;
        this.SubjectLastName = string.Empty;
        this.SubjectEmail = string.Empty;
        this.SubjectPhone = string.Empty;
        this.AdditionalData = string.Empty;
    }

    public int Id { get; set; }

    public string SubjectId { get; set; }

    public string PurposeName { get; set; }

    public string SubjectFirstName { get; set; }

    public string SubjectLastName { get; set; }

    public string SubjectEmail { get; set; }

    public string SubjectPhone { get; set; }

    public string AdditionalData { get; set; }

    public ConsentState State { get; set; }
    public DateTimeOffset UpdatedAt { get; set; }
    public DateTimeOffset? RevokeRequestedAt { get; set; }
}

public enum ConsentState
{
    Revoked = 0,
    Given = 1
}
```

Also notice that the model I posted when opening this issue is not part of the query. In fact I am getting the exception (casting string to type defined by model) all across my model for all queries made on the same instance of DbContext (or rather within the same IoC's scope) when using either of `IServiceCollection.AddDbContext` and `IServiceCollection.AddDbContextPool`

**Comment by mrmartan** [comment] 2018-08-08 11:55
@ajcvickers If this additional info will still not help you reproduce it I might try build and reproduce it seperately from the project I am working on although I do not know if I find the time. Currently I am looking for a way to add the OrderBy/Take clauses back, but I am not aple to reproduce the issue localy and on demand (I stress it happens consistently in our staging environment and only when I add back the OrderBy/Take clauses) which leads me to think that this is a thread-safety issue.

**Comment by maumar** [comment] 2018-08-08 21:34
@mrmartan  I tried reproducing this with additional information provided but still no luck. Standalone repro would be most helpful. I cobbled together the following project:

```
namespace Repro12886
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var rc1 = new RealizedConsent
                {
                    State = ConsentState.Given,
                    PurposeName = "Foo",
                    AdditionalData = "AD1",
                    SubjectEmail = "SE1",
                    SubjectFirstName = "FN1",
                    SubjectLastName = "LN1",
                    SubjectPhone = "P1",
                    UpdatedAt = new DateTimeOffset(new DateTime(1222, 1, 1)),
                };


                var rc2 = new RealizedConsent
                {
                    State = ConsentState.Given,
                    PurposeName = "Foo",
                    AdditionalData = "AD2",
                    SubjectEmail = "SE2",
                    SubjectFirstName = "FN2",
                    SubjectLastName = "LN2",
                    SubjectPhone = "P2",
                    UpdatedAt = new DateTimeOffset(new DateTime(1922, 1, 1)),
                };

                var rc3 = new RealizedConsent
                {
                    State = ConsentState.Given,
                    PurposeName = "Bar",
                    AdditionalData = "AD3",
                    SubjectEmail = "SE3",
                    SubjectFirstName = "FN3",
                    SubjectLastName = "LN3",
                    SubjectPhone = "P3",
                    UpdatedAt = new DateTimeOffset(new DateTime(1932, 1, 1)),
                };


                ctx.RealizedConsents.AddRange(rc1, rc2, rc3);
                ctx.SaveChanges();
            }

            using (var ctx = new MyContext())
            {
                var purposeName = "Foo";
                var consentHadToBeGivenAtLeastAt = new DateTimeOffset(new DateTime(2000, 1, 1));
                var revokeRequestHadToBeGivenAtLeastAt = new DateTimeOffset(new DateTime(2020, 1, 1));

                var query = ctx.RealizedConsents
                    .Where(rc =>
                            rc.State == ConsentState.Given
                        && rc.PurposeName == purposeName
                        && (rc.UpdatedAt < consentHadToBeGivenAtLeastAt
                            || (rc.RevokeRequestedAt.HasValue && rc.RevokeRequestedAt < revokeRequestHadToBeGivenAtLeastAt)))
                    .OrderBy(rc => rc.UpdatedAt)
                    .Take(500) // does not matter how many
                    .Select(rc => new ConsentDTO
                    {
                        Purpose = rc.PurposeName,
                        Subject = new SubjectDTO
                        {
                            SubjectId = rc.SubjectId,
                            FirstName = rc.SubjectFirstName,
                            MiddleName = string.Empty,
                            LastName = rc.SubjectLastName,
                            Email = rc.SubjectEmail,
                            Phone = rc.SubjectPhone
                        },
                        State = ConsentState.Given,
                        AdditionalData = rc.AdditionalData
                    });

                var result = query.ToList();
            }
        }
    }

    public class ConsentDTO
    {
        public string Purpose { get; set; }
        public SubjectDTO Subject { get; set; }
        public ConsentState State { get; set; }
        public string AdditionalData { get; set; }

    }

    public class SubjectDTO
    {
        public string SubjectId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<RealizedConsent> RealizedConsents { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=Repro12886;Trusted_Connection=True;MultipleActiveResultSets=True");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<EventContentMetadata>(entity =>
            {
                entity.ToTable("EventContentMetadata");

                entity.HasKey(e => e.Id).ForSqlServerIsClustered();
                entity.Property(e => e.Id).HasColumnType("tinyint").UseSqlServerIdentityColumn();

                entity.Property(e => e.ContentEncoding).HasColumnType("nvarchar(100)").HasMaxLength(100).IsRequired();
                entity.Property(e => e.ContentType).HasColumnType("nvarchar(200)").HasMaxLength(200).IsRequired();
            });
        }
    }

    public class RealizedConsent
    {
        public RealizedConsent()
        {
            this.SubjectFirstName = string.Empty;
            this.SubjectLastName = string.Empty;
            this.SubjectEmail = string.Empty;
            this.SubjectPhone = string.Empty;
            this.AdditionalData = string.Empty;
        }

        public int Id { get; set; }

        public string SubjectId { get; set; }

        public string PurposeName { get; set; }

        public string SubjectFirstName { get; set; }

        public string SubjectLastName { get; set; }

        public string SubjectEmail { get; set; }

        public string SubjectPhone { get; set; }

        public string AdditionalData { get; set; }

        public ConsentState State { get; set; }
        public DateTimeOffset UpdatedAt { get; set; }
        public DateTimeOffset? RevokeRequestedAt { get; set; }
    }

    public enum ConsentState
    {
        Revoked = 0,
        Given = 1
    }


    public class EventContentMetadata
    {
        public byte Id { get; set; }

        public string ContentType { get; set; }
        public string ContentEncoding { get; set; }

        public ICollection<Event> Events { get; set; }
    }

    public class Event
    {
        public int Id { get; set; }
    }

}
```

and it produces an expected query:

```
(QueryContext queryContext) => IEnumerable<ConsentDTO> _InterceptExceptions(
|__ source: IEnumerable<ConsentDTO> _ShapedQuery(
|   |__ queryContext: queryContext, 
|   |__ shaperCommandContext: SelectExpression: 
|   |       SELECT TOP(@__p_3) [rc].[PurposeName] AS [Purpose], [rc].[SubjectId], [rc].[SubjectFirstName] AS [FirstName], [rc].[SubjectLastName] AS [LastName], [rc].[SubjectEmail] AS [Email], [rc].[SubjectPhone] AS [Phone], [rc].[AdditionalData]
|   |       FROM [RealizedConsents] AS [rc]
|   |       WHERE (([rc].[State] = 1) AND ([rc].[PurposeName] = @__purposeName_0)) AND (([rc].[UpdatedAt] < @__consentHadToBeGivenAtLeastAt_1) OR ([rc].[RevokeRequestedAt] IS NOT NULL AND ([rc].[RevokeRequestedAt] < @__revokeRequestHadToBeGivenAtLeastAt_2)))
|   |       ORDER BY [rc].[UpdatedAt], 
|   |__ shaper: (QueryContext queryContext | ValueBuffer rc) => new ConsentDTO{ 
|           Purpose = string TryReadValue(rc, 0, RealizedConsent.PurposeName), 
|           Subject = new SubjectDTO{ 
|               SubjectId = string TryReadValue(rc, 1, RealizedConsent.SubjectId), 
|               FirstName = string TryReadValue(rc, 2, RealizedConsent.SubjectFirstName), 
|               MiddleName = "", 
|               LastName = string TryReadValue(rc, 3, RealizedConsent.SubjectLastName), 
|               Email = string TryReadValue(rc, 4, RealizedConsent.SubjectEmail), 
|               Phone = string TryReadValue(rc, 5, RealizedConsent.SubjectPhone) 
|           }
|           , 
|           State = Given, 
|           AdditionalData = string TryReadValue(rc, 6, RealizedConsent.AdditionalData) 
|       }
|__ ), 
|__ contextType: Repro12886.MyContext, 
|__ logger: DiagnosticsLogger<Query>, 
|__ queryContext: Unhandled parameter: queryContext)
```

**Comment by ajcvickers** [comment] 2018-08-15 17:27
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by mrmartan** [comment] 2018-08-16 12:04
Using the query that cause the issue (incl. OrderBy/Take) and adding AsNoTracking call I was able to work around the issue.

```c#
await this.readContext.RealizedConsents
    .Where(rc =>
            rc.State == OneSqlStore.ConsentState.Given
        && rc.PurposeName == command.Purpose.Name
        && (rc.UpdatedAt < consentHadToBeGivenAtLeastAt
            || (rc.RevokeRequestedAt.HasValue && rc.RevokeRequestedAt < revokeRequestHadToBeGivenAtLeastAt)))
    .OrderBy(rc => rc.UpdatedAt)
    .Take(500) // does not matter how many
    .Select(rc => new Domain.QueryModel.Consent
    {
        Purpose = rc.PurposeName,
        Subject = new Domain.QueryModel.Subject
        {
            SubjectId = rc.SubjectId,
            FirstName = rc.SubjectFirstName,
            MiddleName = string.Empty,
            LastName = rc.SubjectLastName,
            Email = rc.SubjectEmail,
            Phone = rc.SubjectPhone
        },
        State = Domain.QueryModel.ConsentState.Given,
        AdditionalData = rc.AdditionalData
    })
    .AsNoTracking()
    .ToListAsync(cancellation);
```

@maumar's attempt at reproducing it could not really be successful as it did not introduce any concurrency.

**Closed** 2022-10-16 13:23 UTC
Labels: closed-could-not-reproduce, customer-reported
