### ISSUE TITLE
$select not working on property HasConversion

### ISSUE THREAD

**Issue by keatkeat87** [dotnet/efcore#19628] opened 2020-01-18 03:15 UTC
This issue is related to https://github.com/OData/WebApi/issues/2010
when using HasConversion convert List to json and use odata $select, it will throw a error 
![image](https://user-images.githubusercontent.com/8691013/72657768-60a4e480-39e3-11ea-9423-2de7d6d72c81.png)

### Steps to reproduce
1.git clone https://github.com/keatkeat87/odata--select-HasConversion-issue.git
2.dotnet ef migrations add init
3.dotnet ef database update
4.F5
5.visit /odata/Products?$select=images
 
  

### Further technical details
EF Core version: 3.1.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system:
IDE: (e.g. Visual Studio 2019 16.4)

**Comment by keatkeat87** [comment] 2020-01-22 14:25
@ajcvickers I am so sorry, I missed the update. 
I already update the git. please follow the steps to reproduce.
thank you so much

**Comment by ajcvickers** [comment] 2020-01-23 23:52
@keatkeat87 Thanks; I was able to reproduce this now. I'm not 100% sure what is going on, but it appears to be related to having a property in the model that is a collection but mapped as a regular property, rather than a navigation.

```C#
public class Product
{
    public int Id { get; set; }
    public List<Image> images { get; set; } = new List<Image>();
}
```
```C#
modelBuilder
    .Entity<Product>()
    .Property(c => c.images)
    .HasConversion(
        c => JsonConvert.SerializeObject(c), 
        s => JsonConvert.DeserializeObject<List<Image>>(s));
```
Something then gets confused in the OData/MVC/EF boundary--I expect it might be trying to include related entities rather than just treating it as a normal property.

I was able to workaround this by wrapping the `List<>` in another type so that it doesn't appear to be a navigation property.

```C#
public class Product
{
    public int Id { get; set; }
    public string name { get; set; }
    public Image image { get; set; }
    public ListOfImages images { get; set; } = new ListOfImages();
}

public class ListOfImages
{
    public List<Image> Images { get; set; } = new List<Image>();
}
```
```C#
modelBuilder
    .Entity<Product>()
    .Property(c => c.images)
    .HasConversion(
        c => JsonConvert.SerializeObject(c.Images), 
        s => new ListOfImages { Images = JsonConvert.DeserializeObject<List<Image>>(s)}); ```
```

Stack trace:
```
System.ArgumentException: Expression of type 'System.Object' cannot be used for parameter of type 'System.String' of method 'Project.Entity.Image GetParameterValue[Image](Microsoft.EntityFrameworkCore.Query.QueryContext, System.String)' (Parameter 'arg1')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](IAsyncEnumerable`1 value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncEnumerable(ActionContext context, ObjectResult result, IAsyncEnumerable`1 asyncEnumerable)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by smitpatel** [comment] 2020-01-24 04:38
@ajcvickers - 3.1 or 5.0? Also can you post the equivalent linq query?

**Comment by ajcvickers** [comment] 2020-01-24 16:21
@smitpatel 3.1 so far, but I should try it on 5.0. I haven't figured out how to get the LINQ query yet--I have some work to do here. :-)

**Comment by ajcvickers** [comment] 2020-02-03 19:28
@smitpatel Still repros on master. This is what I see in the logs:

```
[11:23:58 INF] Entity Framework Core 5.0.0-dev initialized 'CustomerOrderContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: SensitiveDataLoggingEnabled 
[11:23:59 DBG] queryContext => new QueryingEnumerable<<>f__AnonymousType1<List<Image>>>(
    (RelationalQueryContext)queryContext,
    RelationalCommandCache,
    null,
    null,
    Func<QueryContext, DbDataReader, ResultContext, int[], ResultCoordinator, <>f__AnonymousType1<List<Image>>>,
    Project.Entity.CustomerOrderContext,
    DiagnosticsLogger<Query>
)
[11:23:59 DBG] Creating DbCommand for 'ExecuteReader'.
[11:23:59 DBG] Created DbCommand for 'ExecuteReader' (27ms).
[11:23:59 DBG] Opening connection to database 'TestOd' on server '(localdb)\mssqllocaldb'.
[11:24:00 DBG] Opened connection to database 'TestOd' on server '(localdb)\mssqllocaldb'.
[11:24:00 DBG] Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [p].[images]
FROM [Products] AS [p]
```

I was expecting to also see the shape of the query in the logs. Is this logging not implemented?

**Comment by smitpatel** [comment] 2020-02-05 17:48
Logging went behind wall of command caching. @maumar is working on it.

**Comment by ajcvickers** [comment] 2020-02-08 23:54
Note from team discussion: need to bring this up with OData.

**Comment by maumar** [comment] 2020-02-10 23:51
logging PR was just checked in, so we should be able to see the SQL now.

**Comment by aiscrim** [comment] 2020-02-12 16:19
Just to add some details: I'm having the same problem migrating a project from ASP.NET Core 2.2 to 3.1. It was working fine, now if I query an OData entity passing any array or list field to the $select parameter, it crashes with the same above mentioned error.
**Note**: in my case I have no HasConversion() configuration!

**Comment by ajcvickers** [comment] 2020-02-14 23:57
@aiscrim Please create a new issue and include a small, runnable project that reproduces the error you are seeing.

**Comment by ajcvickers** [comment] 2020-07-30 22:03
With the latest OData and the latest daily build of EF Core, the logs show the following.

@maumar @smitpatel Does this provide any additional information?

```
2020-07-30 15:01:01.107 -07:00 [INF] Request starting HTTP/2.0 GET https://localhost:44326/odata/Products?$select=images  
2020-07-30 15:01:01.107 -07:00 [DBG] The request path /odata/Products does not match a supported file type
2020-07-30 15:01:01.108 -07:00 [DBG] No candidates found for the request path '/odata/Products'
2020-07-30 15:01:01.108 -07:00 [DBG] Request did not match any endpoints
2020-07-30 15:01:01.126 -07:00 [DBG] Request successfully matched the route with name 'odata' and template 'odata/{*odataPath}'
2020-07-30 15:01:01.137 -07:00 [INF] Route matched with {action = "Get", controller = "Products", page = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Get() on controller Project.ProductsController (Project).
2020-07-30 15:01:01.137 -07:00 [DBG] Execution plan of authorization filters (in the following order): ["None"]
2020-07-30 15:01:01.137 -07:00 [DBG] Execution plan of resource filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter"]
2020-07-30 15:01:01.137 -07:00 [DBG] Execution plan of action filters (in the following order): ["Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000)","Microsoft.AspNet.OData.EnableQueryAttribute (Order: 0)"]
2020-07-30 15:01:01.137 -07:00 [DBG] Execution plan of exception filters (in the following order): ["None"]
2020-07-30 15:01:01.137 -07:00 [DBG] Execution plan of result filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter","Microsoft.AspNet.OData.EnableQueryAttribute (Order: 0)"]
2020-07-30 15:01:01.137 -07:00 [DBG] Executing controller factory for controller Project.ProductsController (Project)
2020-07-30 15:01:01.138 -07:00 [DBG] Executed controller factory for controller Project.ProductsController (Project)
2020-07-30 15:01:01.156 -07:00 [INF] Entity Framework Core 5.0.0-rc.1.20380.1 initialized 'CustomerOrderContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: SensitiveDataLoggingEnabled 
2020-07-30 15:01:01.258 -07:00 [DBG] queryContext => new SingleQueryingEnumerable<<>f__AnonymousType1<List<Image>>>(
    (RelationalQueryContext)queryContext, 
    RelationalCommandCache.SelectExpression(
        Projection Mapping:
            images -> 0
        SELECT p.images
        FROM Products AS p), 
    Func<QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator, <>f__AnonymousType1<List<Image>>>, 
    Project.Entity.CustomerOrderContext, 
    False
)
2020-07-30 15:01:01.271 -07:00 [DBG] Creating DbCommand for 'ExecuteReader'.
2020-07-30 15:01:01.271 -07:00 [DBG] Created DbCommand for 'ExecuteReader' (0ms).
2020-07-30 15:01:01.271 -07:00 [DBG] Opening connection to database 'ConTest112' on server '(localdb)\mssqllocaldb'.
2020-07-30 15:01:01.272 -07:00 [DBG] Opened connection to database 'ConTest112' on server '(localdb)\mssqllocaldb'.
2020-07-30 15:01:01.272 -07:00 [DBG] Executing DbCommand [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT [p].[images]
FROM [Products] AS [p]
2020-07-30 15:01:01.274 -07:00 [INF] Executed DbCommand (1ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT [p].[images]
FROM [Products] AS [p]
2020-07-30 15:01:01.288 -07:00 [DBG] A data reader was disposed.
2020-07-30 15:01:01.288 -07:00 [DBG] Closing connection to database 'ConTest112' on server '(localdb)\mssqllocaldb'.
2020-07-30 15:01:01.288 -07:00 [DBG] Closed connection to database 'ConTest112' on server '(localdb)\mssqllocaldb'.
2020-07-30 15:01:01.357 -07:00 [DBG] Buffering IAsyncEnumerable instance of type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[[Microsoft.AspNet.OData.Query.Expressions.SelectExpandBinder+SelectSome`1[[Project.Entity.Product, Project, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.AspNetCore.OData, Version=7.4.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]'.
2020-07-30 15:01:01.381 -07:00 [INF] Executed action Project.ProductsController.Get (Project) in 243.5335ms
2020-07-30 15:01:01.381 -07:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The LINQ expression '$it' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncEnumerable(ActionContext context, ObjectResult result, Object asyncEnumerable, Func`2 reader)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-07-30 15:01:01.407 -07:00 [DBG] 'CustomerOrderContext' disposed.
2020-07-30 15:01:01.407 -07:00 [INF] Request finished in 300.6241ms 500 text/html; charset=utf-8
```

**Comment by smitpatel** [comment] 2020-07-30 22:09
We need actual LINQ query now since this is translation error.

**Comment by ajcvickers** [comment] 2020-07-30 22:12
@smitpatel Did you ever figure out how to get this from OData?

**Comment by smitpatel** [comment] 2020-07-30 22:13
No, @maumar said he may know.

**Comment by maumar** [comment] 2020-08-12 20:50
here is the query we get from odata:

```
DbSet<Product>()
    .Select(namelessParameter{0} => new SelectSome<Product>{ 
        ModelID = TypedLinqParameterContainer<string>.TypedProperty, 
        Container = new NamedPropertyWithNext0<IEnumerable<SelectAll<Image>>>{ 
            Name = "images", 
            Value = namelessParameter{0}.images
                .Select(namelessParameter{1} => new SelectAll<Image>{ 
                    ModelID = TypedLinqParameterContainer<string>.TypedProperty, 
                    Instance = namelessParameter{1}, 
                    UseInstanceForProperties = True 
                }
                ), 
            Next0 = new AutoSelectedNamedProperty<Nullable<int>>{ 
                Name = "Id", 
                Value = (Nullable<int>)namelessParameter{0}.Id 
            }
             
        }
         
    }
    )
```

we get this query shape when images are configured as collection (working case) and as property with type conversion (failing case). When constructing its queries, Odata seems to assume that property which is List<EntityType> is always a collection, regardless of whether it is explicitly configured to be a property.

**Comment by maumar** [comment] 2020-08-12 20:52
EF itself works correctly in this case. Query:

```
var products = _context.Products.Select(p => new { p.images }).ToList();
```

correctly identifies p.images as property rather than collection

**Comment by ajcvickers** [comment] 2020-08-14 18:31
Note from triage: @maumar to file an issue on OData.

**Comment by maumar** [comment] 2020-09-03 01:54
filed https://github.com/OData/WebApi/issues/2269, closing this one

**Closed** 2022-10-16 18:06 UTC
Labels: closed-external, customer-reported
