### ISSUE TITLE
Error message "Value cannot be null. Parameter name: frameworkName" is misleading

### ISSUE THREAD

**Issue by Turochamp** [dotnet/efcore#21760] opened 2020-07-23 20:01 UTC
**How to recreate:**

1. Code first DbContext using Fluent Api
2. AlbumIndex Poco with directory navigation as _IReadOnlyCollection_ property with backing private field that's _readonly_.

**Result:**
EF Core throws exception "Value cannot be null. Parameter name: frameworkName" when AlbumIndex instance is added. 

**My expected:**
Exception thrown should include the entity causing the error, thus be more helpful, instead of a internal parameter name.

**Code**

```C#
class AlbumIndexContext : DbContext
    {
        public DbSet<AlbumIndex> AlbumIndex { get; set; }
        public DbSet<Directory> Directories { get; set; }
        public DbSet<Model.Photo> Photos { get; set; }

        public AlbumIndexContext(DbContextOptions<AlbumIndexContext> options) :base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.\SQLExpress;Database=AlbumIndex1;Trusted_Connection=True;MultipleActiveResultSets=true;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AlbumIndex>().HasKey(e => e.Id);
            modelBuilder.Entity<AlbumIndex>().Property(e => e.Created);
            modelBuilder.Entity<AlbumIndex>().Property(e => e.ComputerName);
            modelBuilder.Entity<AlbumIndex>().Property(e => e.DirectoryPath);
            modelBuilder.Entity<AlbumIndex>().UsePropertyAccessMode(PropertyAccessMode.Field);

            modelBuilder.Entity<Directory>().HasKey(e => e.Id);
            modelBuilder.Entity<Directory>().Ignore(e => e.Path);
            modelBuilder.Entity<Directory>().Property(e => e.RelativePath).HasColumnName("Path");

           // cropped
        }
    }
```

```C#
internal class AlbumIndex
    {
        private List<Photo> _photos;
        private readonly List<Directory> _directories;

        public IReadOnlyCollection<Directory> Directories => _directories;
         // cropped
```

**Comment by ajcvickers** [comment] 2020-07-24 16:00
@Turochamp Please post the full stack trace from the exception.

**Comment by Turochamp** [comment] 2020-07-28 18:47
@ajcvickers Here is the stack trace:

   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrCollectionAccessorFactory.Create(INavigation navigation)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.AddToCollection(INavigation navigation, InternalEntityEntry value, Boolean forMaterialization)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.AddToCollection(InternalEntityEntry entry, INavigation navigation, InternalEntityEntry value, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.ToDependentFixup(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.FireStateChanged(EntityState oldState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Turochamp.Photo.Infrastructure.Repository.AlbumIndexRepository.Insert(AlbumIndex albumIndex) in C:\Src\TuroPhoto\PhotoLibraryCatalog\AlbumIndex1\Infrastructure\Repository\AlbumIndexRepository.cs:line 18
   at Turochamp.Photo.Controller.IndexAlbumController.Run() in C:\Src\TuroPhoto\PhotoLibraryCatalog\AlbumIndex1\Controller\IndexAlbumController.cs:line 53
   at Turochamp.Photo.Program.Main(String directory) in C:\Src\TuroPhoto\PhotoLibraryCatalog\AlbumIndex1\Program.cs:line 38

**Comment by Turochamp** [comment] 2020-07-28 19:15
@ajcvickers After removing the readonly, ef core throws another misleading error message at the end of a save. Do you want it here or as a separate issue?

Stack trace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrAccessorFactory`1.Create(MemberInfo memberInfo, IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrPropertySetterFactory.Create(IPropertyBase property)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.WritePropertyValue(IPropertyBase propertyBase, Object value, Boolean forMaterialization)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete, CurrentValueType valueType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.AcceptChanges()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.AcceptAllChanges(IReadOnlyList`1 changedEntries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Turochamp.Photo.Infrastructure.Repository.AlbumIndexRepository.Save() in C:\Src\TuroPhoto\PhotoLibraryCatalog\AlbumIndex1\Infrastructure\Repository\AlbumIndexRepository.cs:line 23
   at Turochamp.Photo.Controller.IndexAlbumController.Run() in C:\Src\TuroPhoto\PhotoLibraryCatalog\AlbumIndex1\Controller\IndexAlbumController.cs:line 54
   at Turochamp.Photo.Program.Main(String directory) in C:\Src\TuroPhoto\PhotoLibraryCatalog\AlbumIndex1\Program.cs:line 38

**Comment by AndriySvyryd** [comment] 2020-07-28 21:30
@Turochamp Can you provide the full source for `OnModelCreating`, `AlbumIndex`, `Directory`, and `Model.Photo`?

**Comment by Turochamp** [comment] 2020-07-29 08:04
@AndriySvyryd Here is the source code

```
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AlbumIndex>().HasKey(e => e.Id);
            modelBuilder.Entity<AlbumIndex>().Property(e => e.Created);
            modelBuilder.Entity<AlbumIndex>().Property(e => e.ComputerName);
            modelBuilder.Entity<AlbumIndex>().Property(e => e.DirectoryPath);

            modelBuilder.Entity<Directory>().HasKey(e => e.Id);
            modelBuilder.Entity<Directory>().Property(e => e.RelativePath).HasColumnName("Path");
            modelBuilder.Entity<Directory>().Ignore(e => e.Path);

            modelBuilder.Entity<Model.Photo>().HasKey(e => e.Id);
            modelBuilder.Entity<Model.Photo>().Property(e => e.RelativeSourceFilePath).HasColumnName("FilePath");
            modelBuilder.Entity<Model.Photo>().Ignore(e => e.SourceFilePath);
            modelBuilder.Entity<Model.Photo>().Property(e => e.DateTimeFromFile);
            modelBuilder.Entity<Model.Photo>().Ignore(e => e.ImageMetaData);
        }
```

```
    internal class AlbumIndex
    {
        private List<Photo> _photos;
        public IReadOnlyCollection<Photo> Photos => _photos;
        
        private List<Directory> _directories;
        public IReadOnlyCollection<Directory> Directories => _directories;

        public int Id { get; }
        public string ComputerName { get; }
        public string DirectoryPath { get; }
        public DateTime Created { get; }

        public AlbumIndex(string computerName, string directoryPath, List<Photo> photos) : this()
        {
            ComputerName = computerName;
            DirectoryPath = directoryPath;
            _photos = photos;
        }

        public AlbumIndex()
        {
            Created = DateTime.Now;
            _directories = new List<Directory>();
            _photos = new List<Photo>();
        }
        ...
``
    internal class Directory
    {
        public Directory(string path) : this()
        {
            Path = path;
            Photos = new List<Photo>();
        }

        public Directory() { }


        public int Id { get; }
        public string Path { get; }
        public List<Photo> Photos { get; private set; }
        public string RelativePath { get; internal set; }
        ...
```

```
    class Photo : IEquatable<Photo>
    {
        public static Photo Create(string filePath, PhotoPathType pathType = PhotoPathType.Source)
        {
            if (pathType != PhotoPathType.Source)
            {
                throw new NotImplementedException("Currently only supports PhotoPathType.Source.");
            }

            return new Photo(filePath);
        }

        public Photo()
        {
        }

        public Photo(string filePath, PhotoPathType pathType = PhotoPathType.Source)
        {
            SourceFilePath = filePath;
        }

        /// <summary>
        /// Hash key based upon source file path and file datetime. Hash is deterministic, but not
        /// guaranteed to be unique.
        /// </summary>
        public string Key
        {
            get => $"{DateTimeFromFile.Ticks};{SourceFileName}";
        }

        public string SourceFilePath { get; set; }

        public string SourceFileName => Path.GetFileName(SourceFilePath);

        public string SourceDirectory => Path.GetDirectoryName(SourceFilePath);

        public string RelativeSourceFilePath { get; set; }

        public ImageMetaData ImageMetaData { get; set; }

        private DateTime? _dateTimeFromFile;
        public DateTime DateTimeFromFile
        {
            get
            {
                if (!_dateTimeFromFile.HasValue)
                {
                    ReadDateTimeFromFile();
                }

                Debug.Assert(_dateTimeFromFile != null, nameof(_dateTimeFromFile) + " != null");
                return _dateTimeFromFile.Value;
            }
        }

        public int Id { get; }

        public void ReadDateTimeFromFile()
        {
            _dateTimeFromFile = File.GetCreationTime(SourceFilePath);
        }

        public override string ToString()
        {
            return SourceFileName;
        }

        public bool Equals(Photo other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;
            return string.Equals(Key, other.Key);
        }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != this.GetType()) return false;
            return Equals((Photo)obj);
        }

        public override int GetHashCode()
        {
            return (Key != null ? Key.GetHashCode() : 0);
        }

        ...
    }
```

**Comment by ajcvickers** [comment] 2020-08-03 16:04
Note for triage: I am not able to reproduce this with the snippets provided, but I had to change so much code to make it compile that I don't think it means much.

@Turochamp Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-08-14 15:54
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:34 UTC
Labels: closed-could-not-reproduce, customer-reported
