### ISSUE TITLE
Reverse engineering (Scaffold) for FK with Delete Rule: No Action - not working

### ISSUE THREAD

**Issue by borisdj** [dotnet/efcore#7617] opened 2017-02-15 14:41 UTC
When doing reverse engineering (Scaffold-DbContext) from database to EF Entities, _Delete Rule_ of FK is being ignored. When it's Cascade it's OK since that is default but nonCascade gets converted to Cascade and if we later recreated DB it would not be the same.

### Steps to reproduce
For example if in DB we have FK column with _Delete Rule: **No Action**_ 
After running command _Scaffold-DbContext_ in created DbContext
we will get
```c#
entity.HasOne(d => d.Genre)
    .WithMany(p => p.Movie)
    .HasForeignKey(d => d.GenreId);
```
and it should be
```c#
entity.HasOne(d => d.Genre)
    .WithMany(p => p.Movie)
    .HasForeignKey(d => d.GenreId)
    .OnDelete(DeleteBehavior.Restrict);
```

### Further technical details
EF Core version: 1.1.0
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10 Home
IDE: (Visual Studio Community 2015 Update 3)
SQL Server 2016 Developer Edition

**Comment by lajones** [comment] 2017-04-10 23:56
@borisdj I'm assuming the foreign key allows nulls? If so that would explain it - see below.

@ajcvickers @bricelam At https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.Design/Scaffolding/Internal/ScaffoldingUtilities.cs#L133 we declare that the `defaultOnDeleteAction` is `Cascade` if the FK is Required and `Restrict` otherwise.  If the `OnDelete(...)` we would scaffold matches the default then following the "don't output configuration which would be the default anyway" rule we don't output that.

Questions:
1. Is the `defaultOnDeleteAction` calculation still correct as far as generating the model is concerned?
2. If we only output when the delete action has a "non-default" value, does Migrations follow the same rule i.e. does Migrations use the same default delete action calculation?
3. If it does, is Migrations aware of what the database considers its default delete action and output the appropriate SQL so that things round-trip correctly?

**Comment by ajcvickers** [comment] 2017-04-11 17:05
@lajones 
1. Yes. Cascade is the convention for required FKs, Restrict for optional FKs (although this really is not specified explicitly)
2. If the FK is required, then conventions will run and set Cascade, so the model that Migrations gets will have Cascade set. So, in principle, yes, although Migrations itself just follows what conventions have done to the model.
3. Migrations just outputs what is in the model, but I'm not aware of any situations where this approach doesn't work.

**Comment by lajones** [comment] 2017-04-11 18:20
Thanks @ajcvickers. @borisdj I'm going to close this as by design. But if the above does not explain what you are seeing feel free to re-open.

**Comment by borisdj** [comment] 2017-04-11 23:23
@lajones
Yes, FK allowed NULL in this scenario.
I wasn't aware that default behavior depends on Nullability.
Taking that into the consideration, it's all fine, there is no bug.
These are possible combinations:
Null
  SQLCascade   - Default
  SQLNoAction - ReferentialAction.Restrict(explicit)
NotNull
  SQLNoAction - Default
  SQLCascade   - ReferentialAction.Cascade(explicit)

**Comment by lajones** [comment] 2017-04-12 00:09
@borisdj Glad we sorted that out. Thanks for the confirmation.

**Closed** 2022-10-16 10:53 UTC
Labels: closed-by-design
