### ISSUE TITLE
SQL Server: Insert new object throws deadlock

### ISSUE THREAD

**Issue by rolandoldengarm** [dotnet/efcore#6444] opened 2016-08-31 04:42 UTC
### Steps to reproduce

An object with child objects, with multiple child objects.
### The issue

My domain model is, simplified:
Hotel

> Hotel Rooms
> 
> > Room Pictures
> > Room Amenities

Since I've added Room Amenities, I get a deadlock when inserting a new Hotel (blank database).

I've done a SQL Server trace, and I see a read committed lock (Shared) on PK_HotelRoomDefinition.
Looking at the previously executed queries, I see THREE queries (why THREE)? First one inserts the hotel, the two others insert pictures, amenities, and rooms.
My guess is that query 1 wants to read the room inserted room from query 2, and/or vice versa.

The weird thing is, that sometimes it works, sometimes not.
Also, just did another test, and deadlocked on just adding Pictures and Amenities in 1 query?
### Further technical details

EF Core version: 7.0.0-rc1-final
Operating system: Win 10
Visual Studio version: VS2015
SQL Server: LocalDB

/edit
When I clear amenities before inserting, I don't get the deadlock anymore... So it must be those TWO foreign key relations that's causing the issue here.

```
hotel.RoomDefinitions.ToList().ForEach(r => r.Amenities = null);
```

**Comment by divega** [comment] 2016-08-31 05:08
@rolandoldengarm any chance you could share a repro project?

**Comment by rolandoldengarm** [comment] 2016-08-31 05:10
As usual it's a big project, but now I've nailed it down I'll try to give it a go.

**Comment by rolandoldengarm** [comment] 2016-08-31 08:19
@divega before I spend a lot of time replicating this, it's good to know we're still on RC1. So, not on the latest EntityFramework. We can't upgrade to 1.0 / RC2 due to dependencies not compatible (like Redis).

Is this maybe an issue that has already been fixed? I don't want to spend a lot of time investigating this, because there is probably a workaround by inserting the child objects one at a time...

**Comment by divega** [comment] 2016-08-31 18:52
@rolandoldengarm does this repro when you have two or more requests saving changes on the database or does it happen with only one?

We did not have changes in the way we sort operations between RC1 and RTM.

**Comment by rolandoldengarm** [comment] 2016-08-31 21:01
It happens when adding ONE object to the database, in ONE thread.

Would it matter that it's LocalDB? I've updated Visual Studio / SQL to the latest versions.

**Comment by rolandoldengarm** [comment] 2016-09-01 07:29
@divega Just did a bit more research. Our webjob was invoking the web api more than once at a time, causing multiple inserts at the same time. 
So, multiple inserts into the same table, at the same time, can cause deadlocks? 
Very strange to be honest.

We've implemented a queue size of 1, implemented await/async, to only have one insert at a time, but it does not feel right.

**Comment by divega** [comment] 2016-09-02 18:22
@rolandoldengarm thanks for the update. If you can provide a repro we can try it with RTM bits and investigate further.

**Comment by divega** [comment] 2016-09-07 18:15
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Comment by rolandoldengarm** [comment] 2016-09-07 20:00
@divega yeah sorry, we were busy upgrading to 1.0.
If it happens again, I'll get a repro. For now, avoiding multiple inserts at the same time has solved the issue

**Comment by divega** [comment] 2016-09-08 04:17
Sure, no worries. Please reactivate when you can provide a repro.

**Closed** 2022-10-16 09:56 UTC
Labels: closed-could-not-reproduce
