### ISSUE TITLE
Add support for ComplexProperty fields in alternate key configurations

### ISSUE THREAD

**Issue by TonEnfer** [dotnet/efcore#34794] opened 2024-09-30 11:01 UTC
I tried to configure the complex property fields as part of the alternate key:
```csharp
public class ModelEntityTypeConfiguration: IEntityTypeConfiguration<Model>
{
    #region IEntityTypeConfiguration<Model>

    public void Configure(EntityTypeBuilder<Model> builder)
    {
        builder.ComplexProperty(
            x => x.ComplexProperty,
            propertyBuilder => propertyBuilder.IsRequired()
        );

        builder.HasAlternateKey(x => new
            {
                x.SimpleProperty,
                x.ComplexProperty.Field1,
                x.ComplexProperty.Field2
            }
        );
    }

    #endregion
}
```
For this configuration I get the error:

> Unable to create a 'DbContext' of type 'context'. The exception 'The expression 'x => new <>f__AnonymousType8`3(SimpleProperty= x.SimpleProperty, Field1= x.ComplexProperty.Field1, Field2= x.ComplexProperty.Field2)' is not a valid member access expression. The expression should represent a simple property or field access: 't => t.MyProperty'. When specifying multiple properties or fields, use an anonymous type: 't => new { t.MyProperty, t.MyField }'. (Parameter 'memberAccessExpression')' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

It seems that in the case of complex properties this limitation is not very relevant, since they become separate columns of the table, i.e. indexes can be created for them and they can be used to create constraints at the DB level.
Maybe this limitation can be removed by reworking the code? Or is it fundamental given the architecture of EF Core and supporting such functionality will require significant effort?

If it matters, I'm using the Npgsql provider, but this error doesn't seem to be dependent on it

**Comment by TonEnfer** [comment] 2024-10-01 08:39
In addition to the above description, I also encountered that properties from Complex Property cannot be referenced in foreign keys, although in case of relational database these properties are separate columns and keys can be created at DB level but not at EF Core level

**Comment by AndriySvyryd** [comment] 2024-10-03 22:17
Duplicate of https://github.com/dotnet/efcore/issues/31246 and https://github.com/dotnet/efcore/issues/31245

**Closed by AndriySvyryd** 2024-10-03 22:17 UTC
Labels: type-enhancement, customer-reported
