### ISSUE TITLE
Application startup exception: MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown database

### ISSUE THREAD

**Issue by viveknuna** [dotnet/efcore#12480] opened 2018-06-27 13:39 UTC
I have deployed the Asp.NEt Core application on IIS. I get the below exception when I try to browse it. But my database exists. 

> Application startup exception: MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown database

**Logs:**

> warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
>       Using an in-memory repository. Keys will not be persisted to storage.
> warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
>       Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
> info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
>       Creating key {98bbcd98-dbcb-4f7e-855d-d2b91729cfb1} with creation date 2018-06-27 12:42:47Z, activation date 2018-06-27 12:42:47Z, and expiration date 2018-09-25 12:42:47Z.
> warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
>       No XML encryptor configured. Key {98bbcd98-dbcb-4f7e-855d-d2b91729cfb1} may be persisted to storage in unencrypted form.
> Application startup exception: MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown database 'spardb'
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
>    at MySqlConnector.Core.ServerSession.<SwitchAuthenticationAsync>d__58.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 342
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySqlConnector.Core.ServerSession.<ConnectAsync>d__56.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 256
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__0.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 92
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__77.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 355
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__19.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 160
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 137
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
>    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.BeginTransaction(DatabaseFacade databaseFacade, IsolationLevel isolationLevel)
>    at Abp.EntityFrameworkCore.Uow.DbContextEfCoreTransactionStrategy.CreateDbContext[TDbContext](String connectionString, IDbContextResolver dbContextResolver)
>    at Abp.EntityFrameworkCore.Uow.EfCoreUnitOfWork.GetOrCreateDbContext[TDbContext](Nullable`1 multiTenancySide)
>    at Nec.Spar.EntityFrameworkCore.Seed.SeedHelper.WithDbContext[TDbContext](IIocResolver iocResolver, Action`1 contextAction) in C:\Spar\FoodKioskSolution\Nec.Spar\src\Nec.Spar.EntityFrameworkCore\EntityFrameworkCore\Seed\SeedHelper.cs:line 43
>    at System.Collections.Generic.List`1.ForEach(Action`1 action)
>    at Abp.AbpBootstrapper.Initialize()
>    at Abp.AspNetCore.AbpApplicationBuilderExtensions.UseAbp(IApplicationBuilder app, Action`1 optionsAction)
>    at Nec.Spar.Web.Host.Startup.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Spar\FoodKioskSolution\Nec.Spar\src\Nec.Spar.Web.Host\Startup\Startup.cs:line 102
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
> crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
>       Application startup exception
> MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown database 'spardb'
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
>    at MySqlConnector.Core.ServerSession.<SwitchAuthenticationAsync>d__58.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 342
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySqlConnector.Core.ServerSession.<ConnectAsync>d__56.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 256
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__0.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 92
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__77.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 355
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__19.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 160
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 137
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
>    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.BeginTransaction(DatabaseFacade databaseFacade, IsolationLevel isolationLevel)
>    at Abp.EntityFrameworkCore.Uow.DbContextEfCoreTransactionStrategy.CreateDbContext[TDbContext](String connectionString, IDbContextResolver dbContextResolver)
>    at Abp.EntityFrameworkCore.Uow.EfCoreUnitOfWork.GetOrCreateDbContext[TDbContext](Nullable`1 multiTenancySide)
>    at Nec.Spar.EntityFrameworkCore.Seed.SeedHelper.WithDbContext[TDbContext](IIocResolver iocResolver, Action`1 contextAction) in C:\Spar\FoodKioskSolution\Nec.Spar\src\Nec.Spar.EntityFrameworkCore\EntityFrameworkCore\Seed\SeedHelper.cs:line 43
>    at System.Collections.Generic.List`1.ForEach(Action`1 action)
>    at Abp.AbpBootstrapper.Initialize()
>    at Abp.AspNetCore.AbpApplicationBuilderExtensions.UseAbp(IApplicationBuilder app, Action`1 optionsAction)
>    at Nec.Spar.Web.Host.Startup.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Spar\FoodKioskSolution\Nec.Spar\src\Nec.Spar.Web.Host\Startup\Startup.cs:line 102
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
> Hosting environment: Production
> Content root path: C:\Published\PublishOutput
> Now listening on: http://localhost:4725
> Application started. Press Ctrl+C to shut down.
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost/swaggar  
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 168.6654ms 500 text/html; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost/swaggar  
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 0.363ms 500 text/html; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost/swaggar  
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 0.2192ms 500 text/html; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost/swaggar  
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 0.3408ms 500 text/html; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost/swaggar  
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 0.2087ms 500 text/html; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost/swaggar  
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 0.3917ms 500 text/html; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost/swaggar  
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 0.3248ms 500 text/html; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost/swaggar  
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 0.3079ms 500 text/html; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost/swaggar  
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 0.2387ms 500 text/html; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 POST http://127.0.0.1:4725/SWAGGAR/iisintegration  0
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 0.4856ms 500 text/html; charset=utf-8
> Application is shutting down...

**Environment:**

Windows 10
MySQL 8.0.11
.Net Core SDK: 2.1.201

**Comment by ajcvickers** [comment] 2018-06-28 16:11
@viveknuna Can you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can fully investigate?

**Comment by smitpatel** [comment] 2018-06-28 16:31
Perhaps some typo in the connection string related to escaping.

**Comment by viveknuna** [comment] 2018-06-28 16:59
@ajcvickers can you please share your email id?

**Comment by viveknuna** [comment] 2018-06-28 17:00
@smitpatel but same connection string works if I add as a website

**Comment by ajcvickers** [comment] 2018-06-28 17:02
@viveknuna avickers

**Comment by viveknuna** [comment] 2018-06-28 17:23
@ajcvickers avickers@gmail.com?

**Comment by ajcvickers** [comment] 2018-06-28 18:05
@viveknuna Nope, sorry. At microsoft.com. Sorry, thought that was implied.

**Comment by viveknuna** [comment] 2018-06-29 13:10
@ajcvickers please check your mail.

**Comment by ajcvickers** [comment] 2018-07-02 17:31
@viveknuna I don't have access to the link you sent.

**Comment by viveknuna** [comment] 2018-07-03 04:29
@ajcvickers can you please try now.

**Comment by viveknuna** [comment] 2018-07-05 14:50
@ajcvickers Please let me know if you have any update on this?

**Comment by viveknuna** [comment] 2018-07-06 07:17
@ajcvickers Thanks for your response.
It shows the above **Preparing download** for some time, but gets downloaded. I have tested this on my local machine.

I am able to directly access the MySQL database.

**Comment by ajcvickers** [comment] 2018-07-06 15:22
@viveknuna What does the code look like that directly accesses the database compared to the code that uses EF?

**Comment by divega** [comment] 2018-07-16 18:36
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 13:16 UTC
Labels: closed-could-not-reproduce, customer-reported
