### ISSUE TITLE
EF7 One to one relation results tables associated with simple one to many relationship 

### ISSUE THREAD

**Issue by BehnamAbdy** [dotnet/efcore#4792] opened 2016-03-14 19:24 UTC
Even when I try  the sample code in Microsoft ef7 one to one docs the result is blog and blogimage as one to many  
Sample from Ms site https://docs.efproject.net/en/latest/modeling/relationships.html#one-to-one

class MyContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<BlogImage> BlogImages { get; set; }

```
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>()
            .HasOne(p => p.BlogImage)
            .WithOne(i => i.Blog)
            .HasForeignKey<BlogImage>(b => b.BlogForeignKey);
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }

    public BlogImage BlogImage { get; set; }
}

public class BlogImage
{
    public int BlogImageId { get; set; }
    public byte[] Image { get; set; }
    public string Caption { get; set; }

    public int BlogForeignKey { get; set; }
    public Blog Blog { get; set; }
}
```

**Comment by rowanmiller** [comment] 2016-03-22 23:47
Are you using RC1? If so, the work to introduce indexes on FK properties wasn't yet done. We've since implemented this so that you'll get a unique index on the FK property of a one-to-one (https://github.com/aspnet/EntityFramework/pull/3764). This will ship in RC2.

**Comment by BehnamAbdy** [comment] 2016-03-26 04:08
yes im using the "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final"
thank u anyway and i hope u release the RC2 soon

**Comment by 1amirjalai** [comment] 2016-05-31 07:06
the problem still exist in rc2

**Comment by divega** [comment] 2016-05-31 11:45
Reopening. From talking to @ajcvickers and @smitpatel it seems we don't affect the uniqueness of the FK side when setting up a 1:1 relationship.

**Comment by ajcvickers** [comment] 2016-05-31 16:31
@divega I don't think we talked about this. The code above explicitly creates a one to one relationship using the fluent API. The original bug was the Migrations ignores our metadata about this and instead relies on the idea that we will by convention also create a unique index for the FK column. Therefore if you use Migrations to create the database you will get a unique index on the FK column, unless you remove that unique index, in which case you won't. Regardless, the relationship is always one to one in our metadata and treated as such.

What we discussed on Friday was that if the relationship would be one to many in our metadata because it has only one reference nav property, then we won't check to see if the app put an explicit unique index on the FK property and use this to change the relationship to one to one.

**Comment by rowanmiller** [comment] 2016-05-31 18:09
@1amirjalai can you open a new issue with details of the issue you are seeing (be sure to include code to reproduce the issue etc.).

**Comment by 1amirjalai** [comment] 2016-06-02 05:10
@rowanmiller the issue is created here #5623

**Comment by divega** [comment] 2016-06-02 16:20
Closing this as all the relevant details are in #5623.

**Closed** 2022-10-16 09:32 UTC
