### ISSUE TITLE
Entity Framework Core, computed column does not appear in WHERE clause

### ISSUE THREAD

**Issue by MichaelGiger** [dotnet/efcore#9979] opened 2017-10-05 17:59 UTC
Hi

I have generated the entity model from an existing database (Scaffold-DbContext).
The table [CfgData] has following computed column [LoggerId]:
((CONVERT([bigint],[configurationID],(0))+(10000000)*CONVERT([bigint],[stationID],(0)))+(1000000000)*CONVERT([bigint],[loggerPrefix],(0)))

I had performance problem when I ran the following query:

```c#
using (var ctx = new DbContext(options))
{
    cfgDataList = await ctx.CfgData.Where(w => loggerIds.Contains((long)w.LoggerId) && w.Status).ToListAsync();
}
```

In the SQL Server Profiler, I've seen that the LoggerIDs are not included in the WHERE clause!

This is the SQL command that the Entity Framework is running:
SELECT [w].[configurationID], [w].[stationID], ....
FROM [dbo].[CFGData] AS [w]
WHERE [w].[status] = 1

Is this a known issue?

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10
IDE: Visual Studio 2017, 15.3.0

**Comment by smitpatel** [comment] 2017-10-05 18:52
Does it work if you remove cast to `long`? Contains translation was very narrow in 1.x release. It has been improved significantly in 2.0 release.

**Comment by MichaelGiger** [comment] 2017-10-06 06:53
It works fine with EF Core 2.0.0

**Comment by smitpatel** [comment] 2017-10-06 15:13
@MichaelGiger - Thanks for confirmation. In 1.x releases, `Contains` only worked if the parameter passed to it is simple member access like `c.Id` (no Cast or anything else otherwise). That restriction has been lifted in 2.0 now it can generate In for broader set of queries. Closing this issue as 2.0 already fixed such queries.

**Comment by smitpatel** [comment] 2017-10-06 15:15
Duplicate of #6937

**Closed** 2022-10-16 11:53 UTC
Labels: closed-duplicate
