### ISSUE TITLE
NullReferenceException while saving changes

### ISSUE THREAD

**Issue by mrmartan** [dotnet/efcore#12864] opened 2018-08-02 11:29 UTC
```c#
using (var transaction = await this.sqlStore.Database.BeginTransactionAsync(IsolationLevel.ReadCommitted, cancellationToken))
            {
                var storeEvent = new OneSqlStore.Event { EventTypeId = eventType.Id, ContentMetadataId = contentMetadata.Id, ContentId = @event.Id };
                await this.sqlStore.Events.AddAsync(storeEvent, cancellationToken);

                // get denormalizers - to define read-model state changes
                var denormalizers = this.serviceProvider.GetServices(typeof(IDenormalizer<>).MakeGenericType(@event.GetType()));
                var handleMethod = typeof(IHandleEvent<>).MakeGenericType(@event.GetType()).GetMethod(nameof(IHandleEvent<Event>.Handle));
                if (handleMethod == null)
                {
                    throw new InvalidOperationException($"Unable to get '{nameof(IHandleEvent<Event>.Handle)}' method for IEventHandler for '{@event.GetType()}' event.");
                }

                // process and write read-model changes to DbContext
                foreach (var denormalizer in denormalizers)
                {
                    await (Task)handleMethod.Invoke(denormalizer, new object[] { @event, cancellationToken });
                }

                storeEvent.Content = MessagePack.LZ4MessagePackSerializer.NonGeneric.Serialize(@event.GetType(), @event, MessagePack.Resolvers.ContractlessStandardResolver.Instance);

                await this.sqlStore.SaveChangesAsync(cancellationToken);
                transaction.Commit();
            }
```
## Logged error
```
EventId_Id
    10000
EventId_Name
    Microsoft.EntityFrameworkCore.Update.SaveChangesFailed
ExceptionMessage
    Object reference not set to an instance of an object.
ExceptionSource
    System.Data.SqlClient
SourceContext
    Microsoft.EntityFrameworkCore.Update
StackTrace
at System.Data.SqlClient.SqlInternalTransaction.GetServerTransactionLevel()
   at System.Data.SqlClient.SqlInternalTransaction.CheckTransactionLevelAndZombie()
   at System.Data.SqlClient.SqlInternalTransaction.Rollback()
   at System.Data.SqlClient.SqlTransaction.Dispose(Boolean disposing)
   at System.Data.Common.DbTransaction.Dispose()
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Dispose()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer (SQL Server 2017)
Operating system: linux container - microsoft/dotnet:2.1.1-aspnetcore-runtime

**Comment by ajcvickers** [comment] 2018-08-06 00:42
@mrmartan I have not been able to reproduce this. Could you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by mrmartan** [comment] 2018-08-06 08:04
Will try. We have suspicion that it happened during DB's shutdown. You should in any case look at the source of NullReferenceException a put a null check there 🙂

**Comment by ajcvickers** [comment] 2018-08-13 17:56
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by JobaDiniz** [comment] 2020-05-25 19:12
This error occurred in Azure App Service (.net framework) and I don't even know where to begin to look about the cause of it... none db connection worked anymore, the only thing to do was to restart azure app service, after that, the error went away - so weird.

**Comment by mrmartan** [comment] 2020-05-25 20:06
@JobaDiniz I think you might have better luck opening new issue and referencing this. I would think it possible to trace down a `NullReferenceException` without reproducing the issue first but it seems not.

**Closed** 2022-10-16 13:23 UTC
Labels: closed-could-not-reproduce, customer-reported
