### ISSUE TITLE
Error when Updating from ASP.NET Core 1.0 to 1.1

### ISSUE THREAD

**Issue by saf-itpro** [dotnet/efcore#7055] opened 2016-11-18 17:58 UTC
Following this [Official ASP.NET Article][1] I updated from ASP.NET Core 1.0 to 1.1. But when compiling my ASP.NET Core project I get the following error in AccountController.cs file:

**Error**:

    The call is ambiguous between the following methods or properties: 'System.Security.Claims.PrincipalExtensions.FindFirstValue(System.Security.Claims.ClaimsPrincipal, string)' and 'System.Security.Claims.PrincipalExtensions.FindFirstValue(System.Security.Claims.ClaimsPrincipal, string)'

*The error is at following at line `var email = info.Principal.FindFirstValue(ClaimTypes.Email);` at the end of following action method*:

    public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
            {
                if (remoteError != null)
                {
                    ModelState.AddModelError(string.Empty, $"Error from external provider: {remoteError}");
                    return View(nameof(Login));
                }
                var info = await _signInManager.GetExternalLoginInfoAsync();
                if (info == null)
                {
                    return RedirectToAction(nameof(Login));
                }
    
                // Sign in the user with this external login provider if the user already has a login.
                var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation(5, "User logged in with {Name} provider.", info.LoginProvider);
                    return RedirectToLocal(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToAction(nameof(SendCode), new { ReturnUrl = returnUrl });
                }
                if (result.IsLockedOut)
                {
                    return View("Lockout");
                }
                else
                {
                    // If the user does not have an account, then ask the user to create an account.
                    ViewData["ReturnUrl"] = returnUrl;
                    ViewData["LoginProvider"] = info.LoginProvider;
                    var email = info.Principal.FindFirstValue(ClaimTypes.Email);
                    return View("ExternalLoginConfirmation", new ExternalLoginConfirmationViewModel { Email = email });
                }
            }

**project.json**:

    {
      "userSecretsId": "aspnet-ABCTest-6af8ade3-87ff-4468-a9ce-8bb69c696ab8",
    
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.1.0",
          "type": "platform"
        },
        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
        "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
        "Microsoft.AspNetCore.Mvc": "1.1.0",
        "Microsoft.AspNetCore.Mvc.Core": "1.1.0",
        "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
        "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
        "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
        "Microsoft.AspNetCore.Diagnostics": "1.1.0",
        "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
        "Microsoft.AspNetCore.Identity": "1.1.0",
        "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
        "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
        "Microsoft.AspNetCore.StaticFiles": "1.1.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
        "Microsoft.Extensions.Configuration.Json": "1.1.0",
        "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
        "Microsoft.Extensions.Logging": "1.1.0",
        "Microsoft.Extensions.Logging.Console": "1.1.0",
        "Microsoft.Extensions.Logging.Debug": "1.1.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
        "Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.1.0-preview4-final",
        "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.1.0-preview4-final"  },
    
      "tools": {
        "BundlerMinifier.Core": "2.0.238"  },
    
      "frameworks": {
        "netcoreapp1.1": {
          "imports": [
            "dotnet5.6",
            "portable-net45+win8"
          ]
        }
      },
    
      "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
      },
    
      "runtimeOptions": {
        "configProperties": {
          "System.GC.Server": true
        }
      },
    
      "publishOptions": {
        "include": [
          "wwwroot",
          "Views",
          "Areas/**/Views",
          "appsettings.json",
          "web.config"
        ]
      },
    
      "scripts": {
        "prepublish": [ "bower install", "dotnet bundle" ],
        "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
      }
    }

  [1]: https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-1-1/

**Comment by rowanmiller** [comment] 2016-11-18 18:12
I think the issue is probably related to this line:

```
"Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
```

I think that package is for pre-Core versions of ASP.NET Identity. Can you try removing it?

**Comment by divega** [comment] 2016-11-18 19:00
That one should actually be changed to 

``` JSON
"Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
```

It is ASP.NET Core but from before it was named that way.

**Comment by rowanmiller** [comment] 2016-11-18 19:13
@divega that one is already listed in the supplied project.json, so I think removing the first dependency should be enough.

**Comment by divega** [comment] 2016-11-18 20:21
@rowanmiller got it.

@saf-itpro please let us know if removing that entry helps.

**Comment by rowanmiller** [comment] 2016-11-21 19:11
Closing as we are pretty confident this was the issue

**Comment by saf-itpro** [comment] 2016-11-24 04:05
@divega I do confirm that your assertion is correct. It's working now.

**Closed** 2022-10-16 10:43 UTC
