### ISSUE TITLE
Increment number value

### ISSUE THREAD

**Issue by mixandmatch025** [dotnet/efcore#14035] opened 2018-11-29 06:54 UTC
What is the best approach to increment a value using EF Core?
Something that will translate to - 
```sql
UPDATE totals 
   SET total = total + 1
WHERE name = 'bill';
```

**Comment by roji** [comment] 2018-12-02 09:40
Duplicate of #795

**Comment by ajcvickers** [comment] 2018-12-03 20:40
@mixandmatch025 In addition, you can do this by executing the raw SQL. For example:
```C#
context.Database.ExecuteSqlCommand(
    "UPDATE totals SET total = total + 1 WHERE name = 'bill'");
```
However, keep in mind that any entities that are currently tracked may become stale since the change being made is opaque to EF.

**Closed** 2022-10-16 13:41 UTC
Labels: closed-duplicate, customer-reported
