### ISSUE TITLE
Don't scaffold indexes and constraints

### ISSUE THREAD

**Issue by GSPP** [dotnet/efcore#21438] opened 2020-06-28 10:00 UTC
`Scaffold-DbContext` scaffolds indexes and constraints by including calls to `HasConstraintName` and `HasIndex`. This information appears to be unused when migrations are not used. `HasComputedColumnSql` is possible unused as well (not sure).

As the database indexing and constraint structure changes, re-scaffolding will cause spurious source code changes that are not meaningful. This causes source control changes and noise when reviewing. It also makes the model source code longer and more tedious to read.

I suggest adding an option to `Scaffold-DbContext` to avoid scripting out physical database structures that have no semantic effect on Entity Framework.

**Comment by ajcvickers** [comment] 2020-06-28 17:15
Duplicate of #10890. Note however that indexes are sometimes used for ordering in the update pipeline.

**Closed** 2022-10-16 18:31 UTC
Labels: closed-duplicate, customer-reported
