### ISSUE TITLE
"Unable to load shared library 'e_sqlite3' or one of its dependencies" on M1 macOS

### ISSUE THREAD

**Issue by u2m4c6** [dotnet/efcore#25307] opened 2021-07-21 15:18 UTC
### Include your code

Opening Sqlite db with EF Core

```C#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https: //go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlite(
                    "Data [path_to_db];Mode=ReadOnly");
            }
        }
```

### Include stack traces
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: Unable to load shared library 'e_sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libe_sqlite3, 1): image not found
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError) in System.Private.CoreLib.dll:token 0x6004b23+0xf
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath) in System.Private.CoreLib.dll:token 0x6004b2a+0x35
   at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags) in SQLitePCLRaw.nativelibrary.dll:token 0x6000001+0x0
   at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags) in SQLitePCLRaw.batteries_v2.dll:token 0x6000002+0x10
   at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags) in SQLitePCLRaw.batteries_v2.dll:token 0x6000003+0x0
   at SQLitePCL.Batteries_V2.Init() in SQLitePCLRaw.batteries_v2.dll:token 0x6000004+0x0
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x600525c+0x78
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in System.Private.CoreLib.dll:token 0x60050f8+0x0
   at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize() in Microsoft.Data.Sqlite.dll:token 0x60001d8+0x20
   at Microsoft.Data.Sqlite.SqliteConnection..cctor() in Microsoft.Data.Sqlite.dll:token 0x60000a1+0x0
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString) in Microsoft.Data.Sqlite.dll:token 0x60000a3+0x0
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.CreateDbConnection() in Microsoft.EntityFrameworkCore.Sqlite.dll:token 0x6000158+0x0
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection() in Microsoft.EntityFrameworkCore.Relational.dll:token 0x600049b+0x25
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateDbCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x6000460+0x5e
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x600045e+0x66
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x6001b0b+0x86
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__19_0(DbContext _, Enumerator enumerator) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x6001f13+0x0
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) in Microsoft.EntityFrameworkCore.dll:token 0x6000472+0x0
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext() in Microsoft.EntityFrameworkCore.Relational.dll:token 0x6001b0a+0x0
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found) in System.Linq.dll:token 0x60000f6+0x43
   at lambda_method12(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in Microsoft.EntityFrameworkCore.dll:token 0x6000885+0x70
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in Microsoft.EntityFrameworkCore.dll:token 0x6000819+0x0
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source) in System.Linq.Queryable.dll:token 0x6000130+0xe
   at ConsoleUI.Program.Main()
```

### Include version information

Microsoft.Data.Sqlite version: 6.0.0-rc-1.21370.4
Target framework: .NET 6.0
Operating system:
macOS Big Sur Arm64

dotnet --info:
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21370.2
 Commit:    64c36e46ff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.4
 OS Platform: Darwin
 RID:         osx.11.0-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-rc.1.21370.2/

Host (useful for support):
  Version: 6.0.0-rc.1.21369.2
  Commit:  f7e4c26181

.NET SDKs installed:
  6.0.100-preview.5.21302.13 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.6.21355.2 [/usr/local/share/dotnet/sdk]
  6.0.100-rc.1.21370.2 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21367.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21369.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by u2m4c6** [comment] 2021-07-21 15:20
I forgot to mention: my code runs fine on Windows 10/11 with the same Nuget packages/version of .NET 6 preview.

**Comment by AndriySvyryd** [comment] 2021-07-23 17:20
Duplicate of https://github.com/dotnet/efcore/issues/24198

**Closed** 2022-10-16 19:40 UTC
Labels: closed-duplicate, customer-reported, area-adonet-sqlite
