### ISSUE TITLE
Migrations: Error reverting to previous migration and removing the current one

### ISSUE THREAD

**Issue by suhasj** [dotnet/efcore#2008] opened 2015-04-09 18:38 UTC
I was able to reproduce this consistently on a machine with dnx 1.0.0-beta4-11467 and EF package versions 7.0.0-beta4-12817.

Repro:
- Create a file new web starter project with latest WTE shipping above mentioned packages
- In command line run `dnx . ef migration apply` to apply the migration that is checked in with templates
- For the `ApplicationUser`, add another property of type string, say City
- Run migration to update the model `dnx . ef migration add updateage`
- Apply migration `dnx . ef migration apply`

Now my scenario is that  I want to revert to the previous migration and delete the new one so, I run 
- `dnx . ef migration apply <name of the previous one>`
- `dnx . ef migration remove`

The remove command gives me the below error 

```
PM> dnx . ef migration remove
Using context 'ApplicationDbContext'.
dnx : System.InvalidOperationException: The migration '20150409181030_updateage' has already been applied to the database. Unapply it and try again. If the 
migration has been applied to other databases, consider reverting its changes using a new migration.
At line:1 char:1
+ dnx . ef migration remove
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.InvalidO... new migration.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

   a
t Microsoft.Data.Entity.Commands.Migrations.MigrationScaffolder.RemoveMigration(String projectDir, String rootNamespace)
   at Microsoft.Data.Entity.Commands.MigrationTool.RemoveMigration(String contextTypeName, String rootNamespace, String projectDir)

  at Microsoft.Data.Entity.Commands.Program.RemoveMigration(String context)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass7_5.<Main>b__14()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)

   at Microsoft.Data.Entity.Commands.Program.Main(String[] args)
```

This is confusing since reverting to the previous migration did not throw any error. I checked the database and the newly added column was removed as was the _MigrationHistory table updated to the previous migration name so applying the previous migration was indeed successful.

**Comment by bricelam** [comment] 2015-05-04 18:42
@suhasj I can't repro this locally...

**Comment by suhasj** [comment] 2015-05-04 19:45
@bricelam I can still repro it. II'll drop by later

**Comment by bricelam** [comment] 2015-05-05 18:58
Just tried your exact steps on a fresh install of Windows 8.1 Enterprise and Visual Studio Enterprise 2015 RC, and it worked for me. Are you using RC? It sounds like you may be hitting something like #1818 which was fixed in Templates for RC.

**Comment by bricelam** [comment] 2015-05-08 16:14
@suhasj You removed the DbContext's awful constructor, right? If not, the migration will be re-applied whenever an instance is created (even by the tool).

**Comment by bricelam** [comment] 2015-05-28 17:02
Closing. I'll assume this was caused by the workaround in templates.

**Closed** 2022-10-16 08:54 UTC
