### ISSUE TITLE
[question] Does EF Core 2.0 support GroupBy translate to SQL ?

### ISSUE THREAD

**Issue by John0King** [dotnet/efcore#9411] opened 2017-08-15 03:56 UTC
> Improved translation will enable more queries to successfully execute, with more logic being evaluated in the database (rather than in-memory) and less data being unnecessarily retrieved from the database. A lot of this has been completed for 2.0 Preview 1, **with the main exception being GroupBy translation**

I read it from wiki , what happened ?

**Comment by smitpatel** [comment] 2017-08-15 04:02
duplicate of #2341 
It is being implemented in 2.1.0

**Closed** 2022-10-16 11:15 UTC
Labels: closed-duplicate
