### ISSUE TITLE
Operation is not valid due to the current state of the object

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/efcore#16126] opened 2019-06-17 19:19 UTC
I just installed .NET Core 3 preview6 SKD and I get an error with a query:

Here's my query

`````csharp
  TicketDetailsDto dto = await _ctx.Tickets
        .Where(t => t.Id == id)
        .Select(s => new TicketDetailsDto
        {
            CreationDate = s.CreationDate,
            Id = s.Id,
            Priority = s.Priority,
            Status = s.Status,
            Title = s.Title,
            Type = s.Type,
            User = _ctx.Users.Where(u => u.Id == s.UserId).Select(se => new ApplicationUserDto
            {
                FirstName = se.FirstName,
                LastName = se.LastName,
            }).FirstOrDefault(),
            AssignedTo = _ctx.Users.Where(u => u.Id == s.AssignedToId).Select(se => new ApplicationUserDto
                    {
                        FirstName = se.FirstName,
                        LastName = se.LastName,
                    }).FirstOrDefault(),

                })
                 .AsNoTracking()
                .FirstOrDefaultAsync();
`````

where

````csharp
public class TicketDetailsDto
    {
        public int Id { get; set; }

        public TicketPriority Priority { get; set; }

        public TicketType Type { get; set; }

        public TicketStatus Status { get; set; }

        public string Title { get; set; }

        public DateTime CreationDate { get; set; }

        public ApplicationUserDto User { get; set; }

        public ApplicationUserDto AssignedTo { get; set; }
      }
````

And

````csharp
    public class ApplicationUserDto
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }
     }
````

When executing I get an error:

Operation is not valid due to the current state of the object.

But if I write my request in three parts, this way:

````csharp
            TicketDetailsDto dto = await _ctx.Tickets
                .Where(t => t.Id == id)
                .Select(s => new TicketDetailsDto
                {
                    CreationDate = s.CreationDate,
                    Id = s.Id,
                    Priority = s.Priority,
                    Status = s.Status,
                    Title = s.Title,
                    Type = s.Type,
                    UserId=s.UserId,
                    AssignedToId=s.AssignedToId
                    //User = _ctx.Users.Where(u => u.Id == s.UserId).Select(se => new ApplicationUserDto
                    //{
                    //    FirstName = se.FirstName,
                    //    LastName = se.LastName,
                    //}).FirstOrDefault(),
                    //AssignedTo = _ctx.Users.Where(u => u.Id == s.AssignedToId).Select(se => new ApplicationUserDto
                    //{
                    //    FirstName = se.FirstName,
                    //    LastName = se.LastName,
                    //}).FirstOrDefault(),
                })
                 .AsNoTracking()
                .FirstOrDefaultAsync();

            dto.User = _ctx.Users.Where(u => u.Id == dto.UserId).Select(se => new ApplicationUserDto
            {
                FirstName = se.FirstName,
                LastName = se.LastName,
            }).FirstOrDefault();
            dto.AssignedTo = _ctx.Users.Where(u => u.Id == dto.AssignedToId).Select(se => new ApplicationUserDto
            {
                FirstName = se.FirstName,
                LastName = se.LastName,
            }).FirstOrDefault();

````

It works fine.

Any Idea ?

Thanks.

**Comment by Avidin** [comment] 2019-06-20 07:51
I have the same issue by using SQL views. (.NET Core 3.0.0-preview6.19304.10)
I used Scaffold-DbContext to get the model of the SQL Views and tables.

Datacontext:
public virtual DbSet<MyView> ViewSurveySummary { get; set; }
...
 modelBuilder.Entity<MyView>(entity => { entity.HasNoKey(); });
...

I want call something like ...
  return _context.MyView.OrderBy(o => o.Name).ToList();
... but i get the error: Operation is not valid due to the current state of the object

If i call to the tables no issues.
Any Idea? 
Thanks

**Comment by JulienM28** [comment] 2019-06-20 18:15
Here the stack trace:

   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.SqlExpressions.SubSelectExpression.Verify(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.SqlExpressions.SubSelectExpression..ctor(SelectExpression subquery)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryCompilationContext2.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery2[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at ProjectManagementSuite.Services.TicketService.GetTicketDetailsAsync(Int32 id) in C:\Team Foundation Workspace\Project Management Suite\ProjectManagementSuite.Services\TicketService.cs:line 106

**Comment by smitpatel** [comment] 2019-06-20 21:15
Duplicate of #10001

**Comment by JulienM28** [comment] 2019-06-21 17:25
Is it really the same issue ?

My problem here is an eception not the fact that many requests are done.

I prefer many requests :)

**Closed** 2022-10-16 14:26 UTC
Labels: customer-reported
