### ISSUE TITLE
EF 1.1.1 update EF 1.1.2 Throw Exception

### ISSUE THREAD

**Issue by a764578566** [dotnet/efcore#8535] opened 2017-05-21 02:52 UTC
EF 1.1.1 update EF 1.1.2 Throw Exception:
`using (var db = _dbContext.Database.BeginTransaction())`
`{`
     `//to do post put`
     `db.Commit();`
`}`
`Task.Run(()=>{`
    `//to do query`
`})`

{
  "name": "Microsoft.ApplicationInsights.Dev.Message",
  "time": "2017-05-21T02:47:53.1603026Z",
  "tags": {
    "ai.internal.sdkVersion": "aspnet5c:2.1.0-beta1",
    "ai.location.ip": "192.168.60.57",
    "ai.operation.name": "GET MaintenanceTeams/GetAssignList",
    "ai.cloud.roleInstance": "DESKTOP-8NCRL9O",
    "ai.internal.nodeName": "DESKTOP-8NCRL9O",
    "ai.application.ver": "1.0.0.0",
    "ai.operation.id": "0HL4VUEUSTP6U",
    "ai.operation.parentId": "0HL4VUEUSTP6U"
  },
  "data": {
    "baseType": "MessageData",
    "baseData": {
      "ver": 2,
      "message": "An exception occurred in the database while iterating the results of a query.\r\nSystem.InvalidOperationException: Invalid attempt to call Read when reader is closed.\r\n   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)\r\n   at System.Data.SqlClient.SqlDataReader.Read()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)\r\n   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)\r\n   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()\r\n   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()",
      "severityLevel": "Error",
      "properties": {
        "Exception": "System.InvalidOperationException: Invalid attempt to call Read when reader is closed.\r\n   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)\r\n   at System.Data.SqlClient.SqlDataReader.Read()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)\r\n   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)\r\n   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()\r\n   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()",
        "AspNetCoreEnvironment": "Development",
        "CategoryName": "Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory",
        "DeveloperMode": "true"
      }
    }
  }
}

**Comment by divega** [comment] 2017-05-21 03:03
@a764578566 does this reproduce if you `await` on the `Task` returned by `Task.Run()`? Otherwise, can you please provide complete repto code?

**Comment by a764578566** [comment] 2017-05-21 03:23
@divega  don't await on the Task returned by Task.Run()   
Task Run(()=>{
//to do query and push message to app 
//not affect return whether the operation is a success
});

**Comment by divega** [comment] 2017-05-21 04:11
@a764578566 if the delegate passed to `Task.Run()` contained any calls to the `DbContext`, including EF queries, that would likely be the cause of the error. That query will execute in a different thread and in the meanwhile the transaction will be disposed (I am basing this only on the code you posted, but likely the connection will be closed as well when the `DbContext` gets disposed). 

In summary, if you are going to use the context in a separate thread, you need to `await` to make sure nothing else does anything on the context in originated thread until the `Task` is completed.

**Comment by a764578566** [comment] 2017-05-21 05:39
@divega Thanks 
I wonder why it's wrong in EF 1.1.2

**Comment by ajcvickers** [comment] 2017-05-22 19:01
Closing this as by-design, per @divega's comments above. @a764578566 If this has been working for you in the past, it's only because you have been getting lucky with the timing of the threads. It would never have been expected to work reliably with any version of EF.

**Closed** 2022-10-16 11:05 UTC
Labels: closed-by-design
