### ISSUE TITLE
DbFunction mapping works with a single parameter, but not with two

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#13195] opened 2018-09-02 14:38 UTC
EF Core 2.1.0

In my DbContext class:
```
        [DbFunction("single_param_fn")]
        public static bool SingleParamFunction(DateTime dt)
        {
            throw new Exception("Not implemented in code; this is a DB function.");
        }

        [DbFunction("diff_seconds")]
        public static double DiffSeconds(DateTime start, DateTime end)
        {
            throw new Exception("Not implemented in code; this is a DB function.");
        }
```
Usage:
```
var x = db.Things.Select(t => MyDbContext.SingleParamFunction(t.Date)).FirstOrDefault(); // this works
var y = db.OtherThings.Select(o => MyDbContext.DiffSeconds(t.Start, t.End)).FirstOrDefault(); // this doesn't
```
exception thrown:
> System.Exception: Not implemented in code; this is a DB function.

**Comment by pmiddleton** [comment] 2018-09-02 18:44
Your second query is falling back to client evaluation.  

The lambda parameter in the second query is defined as ```o``` but you are binding to ```t.Start``` and ```t.End```.  What is ```t``` and where is it defined?  Did you really mean to bind to ```o.Start``` and ```o.End```?

**Comment by shaulbehr** [comment] 2018-09-03 02:03
Yes, my bad, I typed it out wrong. It's meant to be o not t.

**Comment by shaulbehr** [comment] 2018-09-03 11:12
@pmiddleton :

> Your second query is falling back to client evaluation.

I can see that. But why?

**Comment by pmiddleton** [comment] 2018-09-03 15:59
I can not reproduce your issue.  Do you have a small sample app which shows the problem you can share?

**Comment by pmiddleton** [comment] 2018-09-03 18:28
I just noticed you are doing a FirstOrDefault without and OrderBy.  I believe you are dropping to client eval because of that.  

You should be getting a warning about nondeterministic results.

See this article on how to configure warnings if you don't know how to setup them up.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder.configurewarnings?view=efcore-2.1

**Comment by pmiddleton** [comment] 2018-09-03 18:36
I ran a test and missing the orderby should not be dropping you to client eval.  I'm back to needing a example app as I can't repo.

**Comment by ajcvickers** [comment] 2018-09-10 17:52
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:28 UTC
Labels: closed-could-not-reproduce, customer-reported
