### ISSUE TITLE
Pooled DbContext doesn't close underlying connection - regression from .NET 5

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/efcore#27399] opened 2022-02-08 06:06 UTC
## File a bug

I can't find this explicitly mentioned in docs, existing issues, or EFCore's tests.

I have some code that requires digging into the underlying ADO connection, since EFCore does not support Streams (`SequentialAccess` + `ExecuteReader` + `GetStream`). (I also use `Response.RegisterForDisposeAsync` since I pass the stream to ASP.NET Core's `FileStreamResult`, but that part is irrelevant (I think) as I reproduced this without it.)

To do this in .NET 5 I used `context.Database.GetDbConnection()` to get ahold of the underlying EFCore-owned connection, then opened it and ran my query. This worked perfectly fine.

After updating to .NET 6 and EFCore 6, this underlying connection remains open. This first surfaced in my integration tests as a failure to delete the test database after the main part of the test completes.

I've included a reproducible sample below. Running this with `dotnet run --framework net5.0` succeeds, and running this with `dotnet run --framework net6.0` crashes after about 20 seconds with an exception after timing out:

```plain
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot drop database "MyCoolDatabase" because it is currently in use. 
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at net6_efcore_repro.Program.DropDatabaseAsync(String databaseName) in C:\Data\Temp\net6-efcore-repro\Program.cs:line 73
   at net6_efcore_repro.Program.Main(String[] args) in C:\Data\Temp\net6-efcore-repro\Program.cs:line 41
   at net6_efcore_repro.Program.<Main>(String[] args)
ClientConnectionId:9b182c9f-cfb5-481d-8229-fd912e6c8ab4
Error Number:3702,State:4,Class:16
```

### Include your code

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net5.0;net6.0</TargetFrameworks>
    <RootNamespace>net6_efcore_repro</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.13" Condition="'$(TargetFramework)' == 'net5.0'" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.1" Condition="'$(TargetFramework)' == 'net6.0'" />
  </ItemGroup>

</Project>
```

```csharp
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Threading.Tasks;

namespace net6_efcore_repro
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var databaseName = "MyCoolDatabase";

            await CreateDatabaseAsync(databaseName);
            Console.WriteLine("Created database.");

            try
            {
                await using var services = new ServiceCollection()
                    .AddDbContextPool<MyDbContext>(options =>
                        options.UseSqlServer(connectionString: GetConnectionString(databaseName)))
                    .BuildServiceProvider();

                using var context = services.GetRequiredService<MyDbContext>();

                // The connection itself is owned by EFCore so we do not dispose of it.
                var connection = context.Database.GetDbConnection();

                using var command = connection.CreateCommand();
                command.CommandText = "SELECT 'Hello, World!';";

                await connection.OpenAsync();
                var result = await command.ExecuteScalarAsync();

                Console.WriteLine($"Command result: {result}");
            }
            finally
            {
                Console.WriteLine("Dropping database...");
                await DropDatabaseAsync(databaseName);
                Console.WriteLine("Dropped database.");
            }
        }

        static string GetConnectionString(string databaseName)
            => new SqlConnectionStringBuilder
            {
                DataSource = ".",
                InitialCatalog = databaseName,
                IntegratedSecurity = true,
                MultipleActiveResultSets = true,
                Pooling = false,
                Encrypt = false,
            }.ConnectionString;

        static async Task CreateDatabaseAsync(string databaseName)
        {
            using var connection = new SqlConnection(GetConnectionString("master"));
            using var command = connection.CreateCommand();
            command.CommandText = $"CREATE DATABASE [{databaseName}]";

            await connection.OpenAsync();
            await command.ExecuteNonQueryAsync();
        }
        static async Task DropDatabaseAsync(string databaseName)
        {
            using var connection = new SqlConnection(GetConnectionString("master"));
            using var command = connection.CreateCommand();
            command.CommandText = $"DROP DATABASE [{databaseName}]";

            await connection.OpenAsync();
            await command.ExecuteNonQueryAsync();
        }
    }

    class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions options)
            : base(options)
        {
        }
    }
}
```

### Include provider and version information

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Microsoft Windows 11 Version 21H2 (OS Build 22000.438)
IDE: Microsoft Visual Studio Professional 2022 (64-bit) Version 17.0.5

### Additional notes

As a workaround^ I can close the connection if it was closed when I acquired it, e.g.:

```csharp
var connection = context.Database.GetDbConnection();

var connectionStartedClosed = connection.State == ConnectionState.Closed;
if (connectionStartedClosed)
{
    await connection.OpenAsync().ConfigureAwait(false);
    Response.RegisterForDisposeAsync(new CloseConnectionDisposable(connection));
}
```

^ or perhaps I should have been doing this all along? The docs aren't very clear about the lifecycle expectations on the connection returned by `GetDbConnection()` other than it is owned by EFCore if the DbContext was constructed with a connection string, or owned by the application if the DbContext was constructed with a connection object. There isn't any further information about open/close/disposal.

**Comment by roji** [comment] 2022-02-08 08:13
Duplicate of #27308

**Comment by yaakov-h** [comment] 2022-02-08 22:44
@roji I'm not so sure it's an exact duplicate, as neither of the workarounds listed there (`context.Database.OpenConnectionAsync()` or `context.Database.EnlistTransaction(Transaction.Current)`) fix this one.

**Comment by roji** [comment] 2022-02-08 22:51
@yaakov-h it may indeed be a slight variation, but the root cause is ultimately the same - when a pooled DbContext is returned to its pool, the state of its DbConnection isn't being reset.

In general, if your code does the opening, I'd recommend it also be responsible for doing the closing...

**Closed** 2022-10-16 20:25 UTC
Labels: customer-reported
