### ISSUE TITLE
Randomly Invalid SQL(Unreasonable error)

### ISSUE THREAD

**Issue by Daivdhuang** [dotnet/efcore#7047] opened 2016-11-18 02:34 UTC
### Steps to reproduce
When i import over 2000 data, it randomly generated error sql(every time not the same)
And There's no law to find

### The issue
Using EF6.1.3 to write data into SQL server 2008 ,But it General invald column name,the column is Unreadable fields
I'm sure my Database is not include there invalid columns

If you are seeing an exception, include the full exceptions details (message and stack trace).
![image](https://cloud.githubusercontent.com/assets/23544734/20416165/0f36f9e4-ad78-11e6-838d-b0ea8a7c8892.png)

```
Exception message:
System.Data.Entity.Infrastructure.DbUpdateException: 更新条目时出错。有关详细信息，请参阅内部异常。 ---> System.Data.Entity.Core.UpdateException: 更新条目时出错。有关详细信息，请参阅内部异常。 ---> System.Data.SqlClient.SqlException: 关键字 'FROM' 附近有语法错误。
   在 System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   在 System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   在 System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   在 System.Data.SqlClient.SqlDataReader.get_MetaData()
   在 System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   在 System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   在 System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 LXMall.Model.Repositories.OrderSaleRepository.AddFreshFoodOrder(List`1 myFreshOrderExList) 位置 e:\Project_File\LXMall\LXMall.Model\Repositories\Order\OrderSaleRepository.cs:行号 2432
```

### Further technical details
Here is another sample for randomly generated Invald SQL

![image](https://cloud.githubusercontent.com/assets/23544734/20416315/1a79bc46-ad79-11e6-9d12-8f72e45184e8.png)

![image](https://cloud.githubusercontent.com/assets/23544734/20416553/942c3a0e-ad7a-11e6-95fd-be6e2e392e96.png)

EF Core version: EF 6.1.3
Operating system: win7 64X
Visual Studio version: VS2012

**Comment by rowanmiller** [comment] 2016-11-22 18:48
cc @divega just a reminder to follow up on this one 😄

**Comment by divega** [comment] 2016-11-29 00:51
@Daivdhuang sorry for not coming back to you earlier. We discussed the issue within the team since we have never seen any behavior like this reported before. This is just a shot in the dark but here are a few ideas that came up: 

1. If your application performed concurrent execution from multiple threads on the same `DbContext` instance the contents of any data structures used by it could get corrupted (`DbContext` and most of EF APIs are not thread safe).
2. You could be getting this due to a code defect in a wrapping EF provider or in an DbCommand interceptor that could affect the generated SQL.
3. This could be caused by some sort of hardware problem, e.g. on the network, memory, etc.

Barring those options if you are able to reproduce this consistently on different machines and you are sure you are not using non-thread safe EF APIs concurrently, we would be very grateful if you could provide a repro.

Also moving this issue to the EF6 repository (this repository is the EF Core, previously known as EF7).

**Comment by divega** [comment] 2016-11-29 00:52
This issue was moved to aspnet/EntityFramework6#117

**Closed** 2022-10-16 10:42 UTC
Labels: closed-external
