### ISSUE TITLE
Insert does not work with instead of insert triggers that generate PKEY values

### ISSUE THREAD

**Issue by cfauchere** [dotnet/efcore#19721] opened 2020-01-26 02:29 UTC
# Issue Title

Inserting entity with composite key which one of the value is generated by instead of trigger fails.

# General

SQL SERVER 2014
EF CORE 2.2

My entity has a composite PKEY PartitionId, EntityId, both being BIGINT. I want the EntityId value to only increment for a given value of PartitionId. Eg (1,1) (1,2) (1,3) (2,1) (2,2) etc. using IDENTITY column for EntityId leads to (1,1) (1,2) (1,3) (2,4) (2,5). To achieve this I use an instead of insert trigger that generate the value for EntityId (PartitionId comes from the mid tier). 
Using SQL profiler I figured that EF Core upon SaveChange generates a INSERT statement and a SELECT statement with a where condition EntityId = scope_identity() which leads to no row to be returned.

**Comment by ajcvickers** [comment] 2020-01-27 16:27
@cfauchere [EF Core 2.2 is out of support](https://docs.microsoft.com/ef/core/what-is-new/). Please update to EF Core 3.1.

**Comment by ajcvickers** [comment] 2020-02-03 17:45
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:08 UTC
Labels: closed-could-not-reproduce, customer-reported
