### ISSUE TITLE
Does sql server provide support new JSON data type?

### ISSUE THREAD

**Issue by clement911** [dotnet/efcore#34754] opened 2024-09-25 05:21 UTC
The [new JSON data type](https://learn.microsoft.com/en-us/sql/t-sql/data-types/json-data-type?view=azuresqldb-current) is now available in public preview.

Is it possible to map a property to a column of type JSON?

**Comment by roji** [comment] 2024-09-25 05:59
Duplicate of #32150

**Comment by roji** [comment] 2024-09-25 05:59
@clement911 yes, we have done work for 9.0 to allow this - but this relies on underlying SqlClient support as well, and that's not yet in place. I've opened https://github.com/dotnet/EntityFramework.Docs/issues/4818 to track documenting this - you can follow that issue.

**Closed by roji** 2024-09-25 05:59 UTC
Labels: customer-reported

**Comment by clement911** [comment] 2024-09-25 06:05
Thanks @roji

**Comment by clement911** [comment] 2024-10-30 22:02
Just to let you know that the latest preview release of SqlClient appears to have support for the new JSON type.
https://github.com/dotnet/SqlClient/releases/tag/v6.0.0-preview2

**Comment by roji** [comment] 2024-10-30 22:16
@clement911 thanks, yep - we're aware. We've been working with daily builds to do the EF support here, it's good to have a public preview now.

**Comment by clement911** [comment] 2024-10-30 22:21
Thanks @roji, that's great news.
