### ISSUE TITLE
Error when trying to parameterize Property from ExecuteUpdateAsync: "Unable to cast object of type 'System.Linq.Expressions.TypedParameterExpression' to type 'System.Linq.Expressions.LambdaExpression'."

### ISSUE THREAD

**Issue by Kokujou** [dotnet/efcore#31946] opened 2023-10-03 17:13 UTC
All i'm trying to do is creating a function UpdateProperty in my C# frontend that accepts a Func<Entity, PropertyType> and then calling it with 

```
public async Task changeProperty<T>(Func<MyEntity, T> property, T value)
_dbContext.MyEntity.ExecuteUpdateAsync(x=>x.SetProperty(property, vlalue))
```

the types are even matching, it's not failing on compile time but on runtime. which makes no sense for me at all. SetProperty doesn't even accept an Expression.
if i manually call it with x=>x.Property, value it works fine. 

i already figured out that i need to disable my auto-includes so the query doesn't break, but now i'm completely confused. 

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 7
Operating system: Windows 10 Pro x64
IDE: Visual Studio 2022 17.4

**Comment by roji** [comment] 2023-10-04 09:33
@Kokujou it's not possible to help you without a minimal, runnable code sample - the above text doesn't contain enough details.

If you're trying to build build something that runs ExecuteUpdateAsync dynamically, then you'll have to pass a correct expression tree argument to it. SetProperty doesn't accept an Expression, because ExecuteUpdateAsync itself accepts one; the method signature is:

```c#
public static Task<int> ExecuteUpdateAsync<TSource>(
    this IQueryable<TSource> source,
    Expression<Func<SetPropertyCalls<TSource>, SetPropertyCalls<TSource>>> setPropertyCalls,
    CancellationToken cancellationToken = default)
```

To properly construct the tree, I recommend you start out with a non-dynamic sample invocation such as the following:

```c#
await ctx.Blogs.ExecuteUpdateAsync(s => s.SetProperty(b => b.Name, "foo"));
```

At this point you can extract the expression tree argument to a variable:

```c#
Expression<Func<SetPropertyCalls<Blog>, SetPropertyCalls<Blog>>> expression = s => s.SetProperty(b => b.Name, "foo");
```

You can now examine the variable in the debugger to see the exact structure that you'll need to build.

**Comment by Kokujou** [comment] 2023-10-04 12:23
so you're saying instead of extracting only the function i can ever extract the whole SetPropertyCalls OR i can manually construct an expression with Expression API to take the Func<...> i'm receiving and parse it into a valid expression?

this sounds like a really long and roundabout solution... i can go with that for now but for me the Expression API is like Voodoo, so many stuff i don't understand, almost like Assembler. 

It'd be really nice if there was somekind of API from EFCore where you could make it more dynamic. i know there's a bug ticket for accepting string-property-names which has been declined but maybe there are other options that are more likely to be accepted?

**Comment by roji** [comment] 2023-10-04 12:30
@Kokujou you indeed have to get familiar with the Expression API for what you're doing, and it indeed isn't trivial. A good way is to inspect (via the debugger) the Expression tree that gets constructed for you when you use C#, and then try to replicate that exact structure yourself - that's the process I described above.

> It'd be really nice if there was somekind of API from EFCore where you could make it more dynamic. i know there's a bug ticket for accepting string-property-names which has been declined but maybe there are other options that are more likely to be accepted?

I agree that better support should exist for constructing ExecuteUpdate dynamically, this is what #29654 tracks; but for now it has received very little interest/votes. I'll go ahead and close this as a duplicate of that, but feel free to post back if you have further questions etc.

**Comment by roji** [comment] 2023-10-04 12:30
Duplicate of #29654

**Closed by roji** 2023-10-04 12:30 UTC
Labels: customer-reported
