### ISSUE TITLE
OwnsOne failed with two Tables

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#16754] opened 2019-07-25 22:22 UTC
Hi,
The following example fails (System.NullReferenceException: &quot;Object reference not set to an instance of an object.&quot;). Everything works great with one Table. Can someone help me?
Thank's

```
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    public class JgLogDb : DbContext
    {
        public string SqlVerbindung = @&quot;Data Source=.\SqlExpress;Initial Catalog = JgTest; Integrated Security = True&quot;;

public DbSet&lt;TabTest1&gt; TabTest1Set { set; get; }
        public DbSet&lt;TabTest2&gt; TabTest2Set { set; get; }

protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

modelBuilder.Entity&lt;TabTest1&gt;(). OwnsOne(p =&gt; p.MTest);
            modelBuilder.Entity&lt;TabTest2&gt;(). OwnsOne(p =&gt; p.MTest);

base. OnModelCreating(modelBuilder);
        }

protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(SqlVerbindung);
        }
    }

public class TabTest1
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public string Feld1 { get; set; }
        public MeinTest MTest { get; set; }
    }

public class TabTest2
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public string Fel2 { get; set; }
        public MeinTest MTest { get; set; }
    }

public class MeinTest
    {
        public string FeldTest { get; set; }
    }

class Program
    {
        static async Task Main()
        {
            using (var db = new JgLogDb())
            {
                await db. TabTest1Set.AddAsync(new TabTest1()
                {
                    Feld1 = &quot;Hallo&quot;,
                    MTest = new MeinTest()
                    {
                        FeldTest = &quot;Ballo&quot;
                    }
                });
                await db. SaveChangesAsync();
            }

using (var db = new JgLogDb())
            {
                var liste = await db. TabTest1Set
                    . Select(s =&gt; new
                    {
                        f1 = s.Feld1,
                        f2 = s.MTest.FeldTest
                    }). ToListAsync();

foreach (var ds in liste)
                    Console.WriteLine($&quot;{ds.f1}  {ds.f2}&quot;);
            }

Console.ReadLine();
        }
    }
}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/651197/ownsone-failed-with-two-tables.html
VSTS ticketId: 948993_
_These are the original issue comments:_

joerg on 7/18/2019, 02:06 AM (7 days ago): I work with Microsoft. EntityFrameworkCore 3.0.0-preview6.19304.10
Visual Studio Feedback System on 7/19/2019, 01:04 AM (6 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by ajcvickers** [comment] 2019-07-25 23:59
Duplicate of #15285

**Closed** 2022-10-16 14:32 UTC
Labels: customer-reported
