### ISSUE TITLE
Simple soft delete of a child entry does not remove entity from already loaded parent collection navigation properties

### ISSUE THREAD

**Issue by FitzyCodesThings** [dotnet/efcore#22103] opened 2020-08-17 21:55 UTC
When implementing a basic soft delete using global query filters to exclude entities where `IsDeleted` is true (perfectly straightforward), I've run into an issue.

While using the same scope for the DbContext in which a child entity has been deleted, any **parent** entities that have ICollections containing the soft deleted entity will still have the child in their collection.

The entity present in the collection WILL have been updated to have `IsDeleted` set to true, but it's as if I'd need to rerun the query filter or completely reload the parent entity as if from a fresh DbContext in order to get rid of it (I can also, of course, manually remove the item from the parent in the code that called for the child to be deleted).

I've also tried `db.Entry(parentEntity).Reload()` as well as detaching the parent object from the context and requerying. Result is identical: child still present in collection with `IsDeleted` set to true.

As soon as the DbContext is disposed and built anew, everything works as expected: no deleted entity.

**I've setup an ultra simple demo repo here:
https://github.com/FitzyCodesThings/EFCoreSoftDeleteQueryFilterTest**

I'm sure there's a way to access the parent and manually remove the item in `SaveChanges`, but I'm too dumb to figure it out if so.

### Further technical details

EF Core version: 3.1.7
Database provider: InMemory and SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10

**Comment by FitzyCodesThings** [comment] 2020-08-18 02:07
Looking back at how we did soft deletes in EF 6, it looks like I could probably run a raw query to update the table directly and set the `IsDeleted` flag, then detach the entity, but this would be a non-ideal workaround.

**Comment by ajcvickers** [comment] 2020-08-25 16:31
@FitzyCodesThings I've been playing around with this a bit, but it isn't easy to do this in a general purpose way in SaveChanges. Maybe @JonPSmith has some ideas since I know he has been working on soft delete patterns for EF Core?

**Comment by JonPSmith** [comment] 2020-08-25 18:34
Hi @FitzyCodesThings,

I looked at your issue and your code and I think you are asking why EF Core doesn't remove an `Address` from a collection of addresses in your `Student` entity class. 

Assuming that I understood your question I can say that EF Core won't remove any entity class that has been read it. It might change its `State`, but it won't remove an entity class. It only 'obeys' the soft delete when you read something from the database.

I also wanted to point out that the `Remove` method doesn't just set the entity class's `State` to `Deleted` and this can cause (small) problems with your "Remove means Soft Delete". For instance, if you set the `OnDelete` behaviour to `ClientCascade` on your `Student`, then deleting the  `Student` would set `State` all of the  `Student`'s `Addresses` to `Deleted`. That might not what you want. This doesn't mean your approach won't work, but be careful on some side effects.

Also be aware that EF Core's setting of `State` is different (improved!) to EF6's setting of the `State` so you might see different results on EF6 and EF Core when removing an entity with relationships.

Finally you might like to look at a detailed article I wrote on [soft delete and query filters](https://www.thereformedprogrammer.net/ef-core-in-depth-soft-deleting-data-with-global-query-filters/) where I look at some of the deeper parts. It also shows how to automate the configuration of soft deletes. I'm also working on a ['clever' soft delete library](https://github.com/JonPSmith/EfCore.SoftDeleteServices) which also supports cascade soft delete and handles Query Filters that have multiple parts, e.g. provides a query that shows soft deleted entities while still applying the multi-tenant part of the Query Filter. Its not out yet because it uses some EF Core 5 features.

**Comment by FitzyCodesThings** [comment] 2020-08-25 18:55
Thanks for the detailed reply @JonPSmith!

This is an interesting conundrum. In a "hard delete," we'd see that an instance of `Address` IS removed from the `Student` entity's collection of `Address`es (as loaded in the context in the same context instance/scope) , but in the soft delete scenario, it won't be removed. As you said, with a "fresh" context, it reapplies the query filter and we're good to go.

I get why (mostly), it's just an unfortunate behavior that I need to account for.

In my specific use case, I've got an AJAX action that soft deletes a `Vehicle` from a `LoanApplication`'s collection (`HashSet` in this case) of collaterals. I then return the updated list of collaterals back to the View to re-render the list on the page, but the old vehicle is still there. 

To get the `Vehicle` to disappear from the list, I either have to refresh the entire page (which news up a fresh scoped context) or I'd have to manually dispose the DB context and create a new one, requery, and THEN return the results (since I've found no way so far to force a reload or "fresh" load on the parent entity).

I'll take a look at the links you provided and see if there's something else I might be missing.

Thanks again!

**Comment by JonPSmith** [comment] 2020-08-25 19:04
Well, I stand corrected. I hadn't tested that so thanks for letting me know about that.

Yes, I also had that problem. You could try reading the the `LoanApplication` using `AsNoTracking` - *think* that would not like up to the already loaded and tracked version (I haven't tested that but I think it will work).

In EF Core 5 there is a very useful method `context.ChangeTracker.Clear()` which quickly detaches all the tracked entities (same as fresh scoped context). That might help too.

**Comment by smitpatel** [comment] 2020-08-31 18:10
Closing as duplicate of #19695

As mentioned above, EF Core does not update the collection when soft deleting children.

**Closed** 2022-10-16 18:37 UTC
Labels: customer-reported
