### ISSUE TITLE
Mapping a class hierarchy with owned types: unexpected splitted table layout

### ISSUE THREAD

**Issue by marcwittke** [dotnet/efcore#22641] opened 2020-09-21 19:44 UTC
Assuming this domain model that is mapped using the fluent API

![image](https://user-images.githubusercontent.com/4075651/93813665-d70c7d00-fc29-11ea-9c4a-b2246d4c377a.png)

I started with the hierarchy of `Entity`, `SimpleEntity` and `ExtendedEntity`:

```csharp
public class MyDbContext : DbContext
{
    public DbSet<SimpleEntity> SimpleEntities { get; set; }
    public DbSet<ExtendedEntity> ExtendedEntities { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Data Source=:memory:;Version=3;New=True;");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SimpleEntity>(baseEntityBuilder =>
        {
            baseEntityBuilder.Property(simpleEntity => simpleEntity.Name).HasMaxLength(100);
        });
        
        modelBuilder.Entity<ExtendedEntity>(extendedEntityBuilder =>
        {
            extendedEntityBuilder.HasBaseType<SimpleEntity>();
            extendedEntityBuilder.Property(extendedEntity => extendedEntity.ExtendedName).HasMaxLength(1000).IsRequired();
        });
    }
}
```

The resulting migration looks good. So I added the owned entity type `OwnedOne` the the `SimpleEntity`:

```csharp
modelBuilder.Entity<SimpleEntity>(baseEntityBuilder =>
{
    baseEntityBuilder.Property(simpleEntity => simpleEntity.Name).HasMaxLength(100);
    baseEntityBuilder.OwnsOne(simpleEntity => simpleEntity.OwnedOne, ownedOneBuilder =>
    {
        ownedOneBuilder.Property(ownedOne => ownedOne.Name1).HasMaxLength(120);
    });
});
```

cleared migrations and started over. The resulting migration, however, creates two tables, `SimpleEntities` and `SimpleEntities1`

```csharp
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.CreateTable(
        name: "SimpleEntities",
        columns: table => new
        {
            Id = table.Column<int>(nullable: false)
                .Annotation("Sqlite:Autoincrement", true),
            Name = table.Column<string>(maxLength: 100, nullable: true),
            Timestamp = table.Column<DateTime>(nullable: false),
            Discriminator = table.Column<string>(nullable: false),
            ExtendedName = table.Column<string>(maxLength: 1000, nullable: true)
        },
        constraints: table =>
        {
            table.PrimaryKey("PK_SimpleEntities", x => x.Id);
        });

    migrationBuilder.CreateTable(
        name: "SimpleEntities1",
        columns: table => new
        {
            SimpleEntityId = table.Column<int>(nullable: false),
            Name1 = table.Column<string>(maxLength: 120, nullable: true),
            Number2 = table.Column<int>(nullable: false)
        },
        constraints: table =>
        {
            table.PrimaryKey("PK_SimpleEntities1", x => x.SimpleEntityId);
            table.ForeignKey(
                name: "FK_SimpleEntities1_SimpleEntities_SimpleEntityId",
                column: x => x.SimpleEntityId,
                principalTable: "SimpleEntities",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        });
}
```

Full project: https://github.com/marcwittke/EfCoreOwnedEntites note the branch `base-entity-has-owned`

### Further technical details

EF Core version: 3.1.3 also reproduced with 3.1.8
Database provider: Npgsql/SqlServer/Sqlite, tried all of them
Target framework:  .NET Core 3.1
Operating system: GNU/Linux (Fedora 32)
IDE: JetBrains Rider 2020.2

**Comment by AndriySvyryd** [comment] 2020-09-26 20:02
Duplicate of https://github.com/dotnet/efcore/issues/19543

**Closed** 2022-10-16 18:41 UTC
Labels: closed-duplicate, customer-reported
