### ISSUE TITLE
Global conversion for a custom type

### ISSUE THREAD

**Issue by ivankarpey** [dotnet/efcore#14707] opened 2019-02-14 19:24 UTC
It would be a nice if it will be possible to somehow once define a conversion for a type and it's later used in every model without explicitly setting conversion for each property.

For example, I have a custom `Id` type which needs to be converted to a `string`. I use this `Id` almost on every model, so it will be helpful to just define this conversion once.

**Comment by ajcvickers** [comment] 2019-02-14 19:35
Duplicate of #10784

**Closed** 2022-10-16 13:52 UTC
Labels: customer-reported
