### ISSUE TITLE
Look into using the new Microsoft.Extensions.Logging compile-time source generator

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#24988] opened 2021-05-27 13:49 UTC
Could reduce a lot of boilerplate, possibly also better perf.

https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-4/#microsoft-extensions-logging-compile-time-source-generator

**Comment by ajcvickers** [comment] 2022-01-21 19:56
Duplicate of #27060

**Closed** 2022-10-16 19:35 UTC
