### ISSUE TITLE
Updated to 2.1 preview1:  The best match for foreign key properties {'SomeId' : string} are incompatible with the principal key {'TempId' : int}.`

### ISSUE THREAD

**Issue by brendanalexdr** [dotnet/efcore#11095] opened 2018-02-28 17:08 UTC
Just upgraded from Asp.net Core 2.0 to 2.1 preview1.  Same for EF Core.  Now I am getting the following error: 
`Microsoft.EntityFrameworkCore.Model[10602]  The best match for foreign key properties {'SomeId' : string} are incompatible with the principal key {'TempId' : int}.`

Any ideas?

**Comment by ajcvickers** [comment] 2018-02-28 17:53
@nukuuk Assuming these are just log messages and are not actually breaking anything, then this looks like a duplicate of #10918. Can you confirm?

**Comment by nukuuk** [comment] 2018-02-28 18:07
@ajcvickers yes I think you are correct.  I am getting an EF Core related error/problem but seems the source of the problem is not related to these log messages.

**Closed** 2022-10-16 12:11 UTC
Labels: closed-duplicate
