### ISSUE TITLE
Inefficient query

### ISSUE THREAD

**Issue by Dev0033** [dotnet/efcore#23004] opened 2020-10-15 08:47 UTC
I noticed that EF is doing a rather inefficient query
If I made query like:
```C#
var baseQuery = db.Blogs.FromSqlRaw("SELECT * FROM Blogs");

var q1 = baseQuery.Select(b => new Test() { Id = b.BlogId }).ToList();

public class Test
  {
    public int Id { get; set; }
  }
```
Query to the server would be:
SELECT * FROM Blogs

It should be:
SELECT [b].[BlogId] AS [Id]
FROM 
 (
  SELECT * FROM Blogs
 ) AS [b]

If I add Take-parameter to ef query
```C#
var q2 = baseQuery.Select(b => new Test() { Id = b.BlogId }).Take(100).ToList();
```
Query to the server would be:
exec sp_executesql N'SELECT TOP(@__p_1) [b].[BlogId] AS [Id]
FROM (
    SELECT * FROM Blogs
) AS [b]',N'@__p_1 int',@__p_1=100
As it should be.

So why ef can't capsulate sql query correctly without Take-parameter?
Sample:
[EFGetStarted.zip](https://github.com/dotnet/efcore/files/5383502/EFGetStarted.zip)

**Comment by smitpatel** [comment] 2020-10-15 14:32
Duplicate of #16079

**Closed** 2022-10-16 19:04 UTC
Labels: customer-reported
