### ISSUE TITLE
Scaffolding Issue With Temporal Table Hidden Columns - Value cannot be null.

### ISSUE THREAD

**Issue by Beammer** [dotnet/efcore#16632] opened 2019-07-17 06:35 UTC
We were running dotnet ef scaffold against a table configured for temporal table support. The SysStart and SysEnd columns were set to HIDDEN but included in an Index. 

```sql
CREATE NONCLUSTERED INDEX [IX_scRawData_LightspeedOpenDealDetailUnitPart_IsDeleted2] 
	ON [scRawData].[LightspeedOpenDealDetailUnitPart] ([IsDeleted]) 
	INCLUDE ([Cost], [DealDetailUnitUid], [DealerId], [Description], [DupeVersion], [EndpointEventId], [PartNumber], [Price], [Qty], [Retail], [RowHash], [SetupInstall], [SupplierCode], [SysEnd], [SysStart], [Uid]);
```

When scaffold tried to build this table the following error occurred:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: column
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.GetPropertyName(DatabaseColumn column)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitIndex(EntityTypeBuilder builder, DatabaseIndex index)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitIndexes(EntityTypeBuilder builder, ICollection`1 indexes)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Value cannot be null.
Parameter name: column
```

Once we removed the SysStart and SysEnd from the Index the scaffold worked as expected.

Need a better error message for stuff like this I think. It was a process of elimination to figure this out. Also I can see under certain instances the scaffold does include the HIDDEN SysStart/SysEnd columns in the models even if HIDDEN is configured. Given that shouldn't the scaffold ignore HIDDEN on index validation?

### Further technical details
EF Core version: 3.0.0-preview 6.19304.10
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 with all latest patches/updates
IDE: Visual Studio 2019 16.2.0 Preview 3.0

**Comment by ErikEJ** [comment] 2019-07-17 12:52
Your main issue is a duplicate of #16316, which I an currently looking at a fix for.

>> Also I can see under certain instances the scaffold does include the HIDDEN SysStart/SysEnd columns in the models even if HIDDEN is configured. 

Can you provide a repro for that?

**Comment by Beammer** [comment] 2019-07-18 11:07
Thanks for responding so fast! My fault I must have been looking at this incorrectly when I said

> Also I can see under certain instances the scaffold does include the HIDDEN SysStart/SysEnd columns in the models even if HIDDEN is configured.

I ran scaffold again and did not see the hidden columns coming in as model properties. I believe you can close this issue. Thanks!

**Closed** 2022-10-16 14:30 UTC
Labels: customer-reported
