### ISSUE TITLE
Select only specific column for included table result in multiple round trip to server

### ISSUE THREAD

**Issue by MaklaCof** [dotnet/efcore#9297] opened 2017-07-29 09:57 UTC
I think this should transform to single query but it does not:
```
    var result= this.context.MainTable
        .Include(t => t.DetailTable)
        .Select(t => new {
            id = t.Id,
            values = t.DetailTable.Select(t2 => t2.SomeField)
        })
        .ToArray();

```
First query is run to query MainTable and then for each row in MainTable another query is run to get SomeField value from DetailTable.
I am using EF 1.1.2.

I though that I am doing something wrong, so I ask question on [SO](https://stackoverflow.com/questions/45387603/select-with-fields-to-include-in-detail-table-with-ef-core), but it was suggested that this is a bug.

**Comment by smitpatel** [comment] 2017-07-31 17:40
Following up on this on Stackoverflow.

**Comment by maumar** [comment] 2017-07-31 19:04
dupe of https://github.com/aspnet/EntityFramework/issues/4007. https://github.com/aspnet/EntityFramework/issues/9282 (stretch goal for 2.1 release would solve this)

**Closed** 2022-10-16 11:13 UTC
Labels: closed-duplicate
