### ISSUE TITLE
Linq Code no longer working since upgrading to .Net 8.0. Same query works fine in 7.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#32532] opened 2023-12-06 10:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Linq-Code-no-longer-working-since-upgrad/10526243)._

---
var payments = await _repository. OpenPayments.AsNoTracking(). Where(p => (p.TillNumber == "" || p.AuthorizationStatus == 1)). Select(q => q.OrderNumber). ToListAsync();
var orders = await _repository. OpenOrders.AsNoTracking(). Where(r => string. IsNullOrEmpty(r.OpenTerminalNumber) && !payments. Contains(r.OrderNumber)). ToListAsync();

The second line that contains the !payments. Contains causes an error to be thrown in .Net Core 8.0

The error is 

"Incorrect syntax near '$'."

at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand. <ExecuteReaderAsync>d__18.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand. <ExecuteReaderAsync>d__18.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator. <InitializeReaderAsync>d__21.MoveNext()
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy. <ExecuteAsync>d__7`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator. <MoveNextAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions. <ToListAsync>d__67`1.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions. <ToListAsync>d__67`1.MoveNext()
   at Infor.SmartSeries.EndOfDay.EodFunctions. <CloseReopenedOrders>d__24.MoveNext() in V:\SmartSeries\Infor.SmartSeries.EndOfDay\EodFunctions.cs:line 756

---
#### Feedback Bot on 11/28/2023, 02:24 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2023-12-06 10:59
See [Contains in LINQ queries may stop working on older SQL Server versions](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#contains-in-linq-queries-may-stop-working-on-older-sql-server-versions).

**Comment by Planitron** [comment] 2023-12-10 10:52
I have the same problem with contains and any !

The query works in entity 7 and not in 8.0
In lambda query linq , have any ideas?

**Comment by roji** [comment] 2023-12-11 05:20
@Planitron have you read the link posted above? If you're still having trouble after that, please open a new issue with the full details; posting "query doesn't work" doesn't provide any information and doesn't allow us to help you.

**Comment by Planitron** [comment] 2023-12-11 08:46
Hello 

i write a code on the northwind to reproduce

1. First, make sure you have the Northwind database installed on your Microsoft SQL Server or use any other database of your choice.

2. Configure Entity Framework Core to connect to your Northwind database. You'll need to create a DbContext class that corresponds to your database tables.


```
using Microsoft.EntityFrameworkCore;

public class NorthwindDbContext : DbContext
{
    public DbSet<Product> Products { get; set; }
    public DbSet<Category> Categories { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer("YourConnectionStringHere");
    }
}
```



3- Now, create a method to reproduce your query logic:



```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

public class Program
{
    public static void Main()
    {
        ReproduceQuery();
    }

    public static void ReproduceQuery()
    {
        using (var context = new NorthwindDbContext())
        {
            var filter = new YourFilterDto(); // Initialize your filter as needed

            var predicate = PredicateBuilder.True<Product>();

            // Reproduce your predicate-building logic here
            if (filter.CategoryIds.Count > 0)
            {
                predicate = predicate.And(p => filter.CategoryIds.Contains(p.CategoryId));
            }

            if (filter.DiscontinuedOnly)
            {
                predicate = predicate.And(p => p.Discontinued);
            }

            // Add more conditions to the predicate as needed

            Expression<Func<Product, bool>> finalPredicate = predicate;

            var query = context.Products.Where(finalPredicate);

            List<Product> products = query.ToList();

            // Now, you can use the 'products' list to check if the issue you encounter in your application is also reproduced here using the Northwind database.
        }
    }
}
```


thanks

**Comment by ErikEJ** [comment] 2023-12-11 09:04
@Planitron Perhaps create a new issue and explain what "not working" means?

**Comment by Planitron** [comment] 2023-12-11 09:08
Hello @ErikEJ 

Ok , i create an issue, it's about 

filter.CategoryIds.Contains(p.CategoryId)  

or with any 

predicate = predicate.And(p => filter.CategoryIds.Any(categoryId => categoryId == p.CategoryId));

thanks

**Comment by roji** [comment] 2023-12-11 10:24
@Planitron I can't see any issue created by you. Please create a new issue on this github repo with a fully runnable, minimal code sample, as well as the error you're seeing - you haven't provided that above. Also, note that `predicate.And(...)` isn't part of EF Core - it's some sort of 3rd-party extension, so we can't help with that. Please submit a code sample that uses only regular LINQ operators.

**Comment by Planitron** [comment] 2023-12-13 16:07
Hello roji 

predicate.And  , it's a little library write in native C# code , with System.Linq.Expressions

http://www.albahari.com/nutshell/predicatebuilder.aspx

**Comment by ajcvickers** [comment] 2023-12-15 14:50
@Planitron As @roji said, please create a **new issue** on this github repo with a **fully runnable, minimal code sample, as well as the error you're seeing**.

**Comment by Planitron** [comment] 2023-12-15 14:58
i ll try this week end !

**Comment by ajcvickers** [comment] 2024-01-04 10:45
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-01-04 10:45 UTC
Labels: closed-could-not-reproduce, customer-reported
