### ISSUE TITLE
..._Enum_Constraint constraint name too long

### ISSUE THREAD

**Issue by henrikdahl8240** [dotnet/efcore#21010] opened 2020-05-21 20:28 UTC
I am using .NET 5.0 Preview 4.

I get an ..._Enum_Constraint constraint name too long exception when running Update-Database, i.e. constraint name more than 128 characters long.

What do I do about that, can I for instance select my own name using fluent configuration by some method?

**Comment by smitpatel** [comment] 2020-05-21 21:12
Duplicate of #18958 would resolve this.

**Comment by roji** [comment] 2020-05-21 22:11
Note also that automatic check constraints for enums has been moved out of EF Core to a plugin (#20897).

**Comment by henrikdahl8240** [comment] 2020-05-21 22:32
So how do I actually switch generation of these constraints off?

Shouldn't there be a `HasConstraintName(name)` method for setting the name yourself analogous to `ReferenceCollectionBuilder<T>.HasConstraintName(name)`?

**Comment by roji** [comment] 2020-05-21 22:42
@henrikdahl8240 the constraints will be off by default starting with preview5, but for preview4 you'd have to jump through some hoops to disable them. As this is a temporary situation, the easiest at this point would simply be to add a migration and manually remove them or change the name. In any case, am going to go ahead and close this issue as a duplicate.

**Comment by roji** [comment] 2020-05-21 22:42
Duplicate of #18958

**Closed** 2022-10-16 18:26 UTC
Labels: customer-reported
