### ISSUE TITLE
Attempting to insert invalid foreign key results in entity framework querying every table in the database

### ISSUE THREAD

**Issue by statler** [dotnet/efcore#24268] opened 2021-02-25 06:33 UTC
When inserting a new record with an invalid foreign key (in this case -1), an exception is thrown as expected when SaveChangesAsync is called. 
_The INSERT statement conflicted with the FOREIGN KEY constraint (Exception 1)_

Attempting to continue simply regenerates the error continuously. If the option to 'Break when this exception type is thrown' is deselected, then a different error is thrown
_Microsoft.EntityFrameworkCore.DbUpdateException  (Exception 2)_

Attempting to continue through this exception results in what appears at first to be deadlock with an ever increasing memory profile - in this case it is an APS.NET web api on Azure, which it eventually crashes.

The exception is not actually thrown back to the caller and cannot be caught.

Running it locally with a SQL profiler in place shows that entity framework actually starts running queries on every table in the model - in this case about 200 of them.

I have absolutely no idea what is going on.

Exception 1

```
Microsoft.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=The INSERT statement conflicted with the FOREIGN KEY constraint "FK_WorkType_ProjectID". The conflict occurred in database "civilpro-dev", table "dbo.Project", column 'ProjectID'.
The statement has been terminated.
  Source=Core Microsoft SqlClient Data Provider
  StackTrace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

```

```
>	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlConnection.OnError(Microsoft.Data.SqlClient.SqlException exception = {"The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_WorkType_ProjectID\". The conflict occurred in database \"civilpro-dev\", table \"dbo.Project\", column 'ProjectID'.\r\nThe statement has been terminated."}, bool breakConnection = false, System.Action<System.Action> wrapCloseInAction = null)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlInternalConnection.OnError(Microsoft.Data.SqlClient.SqlException exception = {"The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_WorkType_ProjectID\". The conflict occurred in database \"civilpro-dev\", table \"dbo.Project\", column 'ProjectID'.\r\nThe statement has been terminated."}, bool breakConnection = false, System.Action<System.Action> wrapCloseInAction = null)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(Microsoft.Data.SqlClient.TdsParserStateObject stateObj = {Microsoft.Data.SqlClient.TdsParserStateObjectNative}, bool callerHasConnectionLock = false, bool asyncClose = false)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.TdsParser.TryRun(Microsoft.Data.SqlClient.RunBehavior runBehavior, Microsoft.Data.SqlClient.SqlCommand cmdHandler, Microsoft.Data.SqlClient.SqlDataReader dataStream, Microsoft.Data.SqlClient.BulkCopySimpleResultSet bulkCopyHandler, Microsoft.Data.SqlClient.TdsParserStateObject stateObj, out bool dataReady)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlDataReader.MetaData.get()	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(Microsoft.Data.SqlClient.SqlDataReader ds = {Microsoft.Data.SqlClient.SqlDataReader}, Microsoft.Data.SqlClient.RunBehavior runBehavior = ReturnImmediately, string resetOptionsString = null, bool isInternal = false, bool forDescribeParameterEncryption = false, bool shouldCacheForAlwaysEncrypted = true)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(bool isInternal = false, bool forDescribeParameterEncryption = false)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteReader(System.IAsyncResult asyncResult = Id = 117, Status = RanToCompletion, Method = "{null}", Result = "", bool isInternal = false, string endMethod = "EndExecuteReader")	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(System.IAsyncResult asyncResult = Id = 117, Status = RanToCompletion, Method = "{null}", Result = "")	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(System.IAsyncResult asyncResult = Id = 117, Status = RanToCompletion, Method = "{null}", Result = "")	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.TaskFactory<System.__Canon>.FromAsyncCoreLogic(System.IAsyncResult iar, System.Func<System.IAsyncResult, System.__Canon> endFunction, System.Action<System.IAsyncResult> endAction, System.Threading.Tasks.Task<System.__Canon> promise = Id = 106, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}", bool requiresSynchronization = true)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.TaskFactory<Microsoft.Data.SqlClient.SqlDataReader>.FromAsyncImpl.AnonymousMethod__0(System.IAsyncResult iar = Id = 117, Status = RanToCompletion, Method = "{null}", Result = "")	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlCommand.BeginExecuteReaderInternal.AnonymousMethod__163_1(System.Threading.Tasks.Task<object> task = Id = 117, Status = RanToCompletion, Method = "{null}", Result = "", object state = {Method = {System.Reflection.RuntimeMethodInfo}})	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.ContinuationTaskFromResultTask<object>.InnerInvoke()	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task..cctor.AnonymousMethod__277_0(object obj)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread threadPoolThread = {System.Threading.Thread}, System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot = Id = 107, Status = Running, Method = "Void <BeginExecuteReaderInternal>b__163_1(System.Threading.Tasks.Task`1[System.Object], System.Object)", System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown

```

Exception 2

```
Microsoft.EntityFrameworkCore.DbUpdateException
  HResult=0x80131500
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__29.MoveNext()

  This exception was originally thrown at this call stack:
    Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReaderAsync.AnonymousMethod__169_0(System.Threading.Tasks.Task<Microsoft.Data.SqlClient.SqlDataReader>)
    System.Threading.Tasks.ContinuationResultTaskFromResultTask<TAntecedentResult, TResult>.InnerInvoke()
    System.Threading.Tasks.Task..cctor.AnonymousMethod__277_0(object)
    System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, object)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task, System.Threading.Thread)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.GetResult()
    ...
    [Call Stack Truncated]

Inner Exception 1:
SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_WorkType_ProjectID". The conflict occurred in database "civilpro-dev", table "dbo.Project", column 'ProjectID'.
The statement has been terminated.

```

### Include provider and version information

EF Core version: EEF Core 5.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 5.0
Operating system: Win 10 64
IDE: Visual Studio 2019 16.3

**Comment by smitpatel** [comment] 2021-02-25 07:25
Duplicate of #15214

**Closed** 2022-10-16 19:25 UTC
Labels: closed-duplicate, customer-reported
