### ISSUE TITLE
EF Core 3.1 not allowing to update parent and child entities together in one-to-many relationship

### ISSUE THREAD

**Issue by fingers10** [dotnet/efcore#20869] opened 2020-05-07 00:36 UTC
I'm following DDD approach and have a parent and child entity with one-to-many relationship configured as shown below:

**Parent Entity:**
```c#
public class AnnotationEntity
{
    public int Id { get; private set; }
    public string Value { get; private set; }
    
    private readonly List<AnnotationObjectEntity> _annotationObjects = new List<AnnotationObjectEntity>();
    public virtual IReadOnlyList<AnnotationObjectEntity> AnnotationObjects => _annotationObjects.ToList();

    protected AnnotationEntity()
    {

    }

    private AnnotationEntity(string value) : this()
    {
        Value = value;
    }

    private void UpdateContainer(string container)
    {
        Value = container;
    }

    public void AddAnnotation(AnnotationObjectEntity annotationObject)
    {
        if (!_annotationObjects.Any(x => x.Id == annotationObject.Id))
        {
            var annotationObjectEntity = new AnnotationObjectEntity
            (
                annotationObject.Id,
                annotationObject.PageNumber,
                annotationObject.AnnotationType
            );
            _annotationObjects.Add(annotationObjectEntity);
            return;
        }

        var existingAnnotation = _annotationObjects.FirstOrDefault(x => x.Id.Equals(annotationObject.Id));

        if (existingAnnotation != null)
        {
            existingAnnotation.Update(annotationObject);
        }
    }

    public void RemoveAnnotation(Guid id)
    {
        XDocument annotation = XDocument.Parse(Value);

        var annotationObjectEntity = _annotationObjects.FirstOrDefault(x => x.Id == id);

        if (annotationObjectEntity != null)
        {
            _annotationObjects.Remove(annotationObjectEntity);
            annotation.Descendants("Object").Where(x => x.Element("Guid").Value == annotationObjectEntity.Id.ToString()).Remove();
        }

        UpdateContainer(annotation.ToString());
    }

    public static AnnotationEntity Create(string annotation)
    {
        XDocument doc = XDocument.Parse(annotation);
        var documentAnnotations = new List<AnnotationEntity>();

        var annotationEntity = new AnnotationEntity
            (
                annotation
            );

        doc.Descendants("Container").ToList().ForEach(container =>
        {
            container.Descendants("Object").ToList().ForEach(annotationObject =>
            {
                var annotationObjectEntity = new AnnotationObjectEntity
                (
                    Guid.Parse(annotationObject.Element("Guid").Value.ToString()),
                    Convert.ToInt32(container.Element("PageNumber").Value.ToString()),
                    true
                );

                annotationEntity.AddAnnotation(annotationObjectEntity);
            });

        });

        return annotationEntity;
    }

    public void UpdateAnnotation(string modifiedAnnotationXml)
    {
        var modifiedAnnotationEntity = Create(modifiedAnnotationXml);

        //Removing deleted entities
        var deletedAnnotationsId = _annotationObjects.Where(x => !modifiedAnnotationEntity.AnnotationObjects.Any(y => y.Id.Equals(x.Id))).Select(x => x.Id).ToList();

        foreach (var annotationId in deletedAnnotationsId)
        {
            RemoveAnnotation(annotationId);
        }

        XDocument annotation = XDocument.Parse(Value);
        XDocument modifiedAnnotation = XDocument.Parse(modifiedAnnotationXml);

        //update or add
        foreach (var annotationObject in modifiedAnnotationEntity.AnnotationObjects)
        {
            AddAnnotation(annotationObject);
            annotation.Descendants("Object").Where(x => x.Element("Guid").Value == annotationObject.Id.ToString()).Remove();
            // extract annotation object xml from modified xml and add to existing xml

            var modifiedAnnotationObject = modifiedAnnotation.Descendants("Object").SingleOrDefault(x => x.Element("Guid").Value == annotationObject.Id.ToString());
            annotation
                .Descendants("Container").SingleOrDefault(x => x.Element("PageNumber").Value == annotationObject.PageNumber.ToString())
                .Descendants("Objects").SingleOrDefault()
                .Add(modifiedAnnotationObject);

            UpdateContainer(annotation.ToString());
        }
    }
}
```

**Child Entity:**
```c#
public class AnnotationObjectEntity
{
    public Guid Id { get; private set; }
    public int PageNumber { get; private set; }
    public bool AnnotationType { get; private set; }
    
    public AnnotationEntity Annotation { get; }

    protected AnnotationObjectEntity()
    {

    }

    public AnnotationObjectEntity(Guid id, int pageNumber, bool annotationType) : this()
    {
        Id = id;
        PageNumber = pageNumber;
        AnnotationType = annotationType;
    }

    public void Update(AnnotationObjectEntity annotationObject)
    {
        PageNumber = annotationObject.PageNumber;
        AnnotationType = annotationObject.AnnotationType;
    }
}
```

I have configured my entities in my `DbContext` as shown below:

**DbContext:**
```c#
protected override void OnModelCreating(ModelBuilder modelBuilder) 
{
    modelBuilder.Entity<AnnotationEntity>(x =>
    {
        x.Property(y => y.Value).IsRequired();

       x.HasMany(p => p.AnnotationObjects).WithOne(p => p.Annotation)
            .OnDelete(DeleteBehavior.Cascade)
            .Metadata.PrincipalToDependent.SetPropertyAccessMode(PropertyAccessMode.Field);
    });
    modelBuilder.Entity<AnnotationObjectEntity>(x =>
    {
        x.HasKey(k => k.Id);
        x.Property(p => p.Id).HasColumnName("Id");
        x.HasOne(p => p.Annotation).WithMany(p => p.AnnotationObjects);
    });
}
```

After reading the parent entity along with child entity and if I remove/update existing child and add new child and when I try to call save to database as shown below:

**Repository:**
```c#
annotationEntity.UpdateAnnotation(annotationToUpdate);
_context.Annotation.Attach(annotationEntity);

//var changes = _context.ChangeTracker.Entries().Where(x => x.Entity is AnnotationObjectEntity).Select(x => (AnnotationObjectEntity)x.Entity).ToList();

//foreach (var change in changes)
//{
//   _context.Entry(change).State = EntityState.Added;
//}

await _context.SaveChangesAsync();
```

I get the following error:

> Database operation expected to affect 1 row(s) but actually affected 0
> row(s). Data may have been modified or deleted since entities were
> loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for
> information on understanding and handling optimistic concurrency
> exceptions.

Upon further analysis I found that this happens when I add new child objects to the parent object. And also I noticed that `ChangeTracker` has the Entity State as `Modified` for newly added entities. When I change it manually to `Added`. Then `SaveChangesAsync()` works.

Please assist on what I'm doing wrong and why `ChangeTracker()` wrongly detects the `Added` entity state as `Modified`.

**Comment by ajcvickers** [comment] 2020-05-07 22:00
@fingers10 If this:

```C#
_context.Annotation.Attach(annotationEntity);
await _context.SaveChangesAsync();
```
is the only interaction with the context, then nothing should be marked as modified. So I think something else must be going on. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by fingers10** [comment] 2020-05-08 09:27
@ajcvickers Here is the working [example repo](https://github.com/fingers10/DddAndEFCore) to reproduce this issue.

Steps to Reproduce and Run:
1. Clone the Repo from Above link.
2. Run SQL Script from `5_Annotation.sql` file in the solution to your database.
3. Ensure connection string from `appsettings.json` to point to your database.
4. Just run the app.
5. The `Main()` method in `Program.cs` will be hit.
6. `var result5 = Execute(x => x.AddAnnotation());` will create the data in db.
7. Next Line, `var result6 = Execute(x => x.UpdateAnnotation());` will throw the exception when you try to update.

Please let me know if you need any further inputs from my end.

**Comment by ajcvickers** [comment] 2020-05-12 16:42
@fingers10 The code in the override of SaveChanges results in tracking two different entity instances that have the same key. One is marked as Deleted, the other is marked as Modified. EF can only track a single instance with a given key. I'm not sure why we're not throwing as soon as the second instance is tracked--this is something we will investigate.

**Comment by fingers10** [comment] 2020-05-12 17:00
@ajcvickers two different parent entities? I'm removing a child entity and adding a new child entity and both will have different GUID. So there shouldn't not be any clash in keys

**Comment by ajcvickers** [comment] 2020-05-12 17:11
@fingers10 Two different children. It's fairly obvious in the debugger if you look at the entries tracked.

**Comment by fingers10** [comment] 2020-05-12 17:30
@ajcvickers I have double checked multiple times before posting here. Two child entities are having different GUID's. If you have a closer look in the below screen shot, the first child entity has key in which first part ends with `a4` while the second child entity has key in which the first part ends with `a3`.

| Key | Child | ChangeTracker |
|-----|-------|------------------|
|`8ba222a3-5cb1-4772-9657-224bfc640fb7` | First | This is Added but change tracker detects as Modified
|`8ba222a4-5cb1-4772-9657-224bfc640fb7` | Second | This is Deleted and change tracker detects that perfectly

![image](https://user-images.githubusercontent.com/43729469/81725817-09e87c80-94a4-11ea-8cc5-0baac2bdd942.png)

**Comment by ajcvickers** [comment] 2020-05-12 18:20
@fingers10 You are correct--I missed the one digit difference. :-)

Digging deeper, it looks like one of the children has it's parent set to null:

![image](https://user-images.githubusercontent.com/1430078/81729954-b1809300-9441-11ea-852c-9fd6b7a211a0.png)

This causes it to be marked as Deleted since it can't exist without it's parent. One of the other children is marked as Unchanged (even though it looks like it's new), but then a change is detected and hence it becomes modified.

![image](https://user-images.githubusercontent.com/1430078/81730383-4daa9a00-9442-11ea-83c5-d3721252ba7e.png)

I'm not suggesting ways to fix this because I don't understand enough about what the code is trying to do, especially in the way it is switching entities back and forth between states.

**Comment by fingers10** [comment] 2020-05-13 15:25
@ajcvickers Delete is working correct. With Add, I'm just creating child entity objects in my code and adding it to list in parent entity. Nothing complex. Still Am I missing anything? as I can see that Status of newly added entity is changed instead of added?

**Comment by fingers10** [comment] 2020-05-14 10:16
@ajcvickers I narrowed down the issue. In my code while creating child entities I'm explicitly setting the child entities PK in my code. 

This works while adding child entity together with parent entity.

But when I do the same while updating the parent entity, I get this issue. So I manually changed the entity state of child entities to `EntityState.Added`. This resolved the issue.

Is this the intended fix? Please suggest.

**Comment by ajcvickers** [comment] 2020-05-14 16:13
@fingers10 Typically if you're using store-generated keys, then you should not set the key value on any new entity--that is an entity that should be inserted. EF will then use the key value to determine whether the entity should be inserted or updated.

On the other hand, if you are not using generated keys, then make sure that your entity types is configured as such and make state changes manually.

**Comment by fingers10** [comment] 2020-05-16 14:34
@ajcvickers Thanks for your support.

> @fingers10 The code in the override of SaveChanges results in tracking two different entity instances that have the same key. One is marked as Deleted, the other is marked as Modified. EF can only track a single instance with a given key. I'm not sure why we're not throwing as soon as the second instance is tracked--**this is something we will investigate**.

If the above one needs to be investigated then we can keep this open otherwise we can close this thread.

**Closed** 2022-10-16 18:24 UTC
Labels: closed-no-further-action, customer-reported
