### ISSUE TITLE
Can't update boolean property from True to False in Owned Entity

### ISSUE THREAD

**Issue by F0b0s** [dotnet/efcore#20110] opened 2020-02-29 12:16 UTC
I'm using a model with owned entity like this:
```C#
public class Company
 {
        public int Id { get; set; }
        public string Name { get; set; }

        public Settings Settings { get; set; }
 }
 
[Owned]
public class Settings
{
        public bool StandartAccess { get; set; }
        public bool ExtendedAcces { get; set; }
        public bool Flag1 { get; set; }
        public string Name { get; set; }
}
```
I update owned entity like this:
```C#
company.Settings = new Settings()
            {
                StandartAccess = false,
                ExtendedAcces = false,
                Flag1 = false
            };
```
After calling SaveChanges i'm expecting that values will be stored in db.
Really it works as follows:
For string field `Name` in owned entity it always updates values from null -> string, and from string -> null(not presented in example).
For boolean fields updating from false to true is working always, from true to false working only with InMemory Provider, with SqlServer provider it doesn't updates.

### Steps to reproduce

I've created a repo with two projects with the same code. One for InMemory Provider and another with SqlServer Provider. In console it shows different results after updating boolean property of owned entity from true to false.
https://github.com/F0b0s/EfOwnedEntitiesTests

With ef logging when updating from true to false i see:
```
dbug: Microsoft.EntityFrameworkCore.Update[10004]
      SaveChanges starting for 'MyContext'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10800]
      DetectChanges starting for 'MyContext'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10805]
      Navigation property 'Company.Settings' for entity with key '{Id: 20}' detected as changed.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Settings' entity with key '{CompanyId: 20}' tracked by 'MyContext' changed from 'Unchanged' to 'Deleted'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10806]
      Context 'MyContext' started tracking 'Settings' entity with key '{CompanyId: 20}'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10801]
      DetectChanges completed for 'MyContext'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'OwnedTest' on server '.\SQLExpress'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
      Opened connection to database 'OwnedTest' on server '.\SQLExpress'.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20209]
      Beginning transaction with isolation level 'Unspecified'.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20200]
      Began transaction with isolation level 'ReadCommitted'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Company' entity with key '{Id: 20}' tracked by 'MyContext' changed from 'Unchanged' to 'Modified'.
Name: 'Test company', Id: 20, StandartAccess: True, ExtendedAccess: True, Flag1: True
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20210]
      Committing transaction.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20202]
      Committing transaction.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20002]
      Closing connection to database 'OwnedTest' on server '.\SQLExpress'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20003]
      Closed connection to database 'OwnedTest' on server '.\SQLExpress'.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20204]
      Disposing transaction.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Settings' entity with key '{CompanyId: 20}' tracked by 'MyContext' changed from 'Deleted' to 'Detached'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Settings' entity with key '{CompanyId: 20}' tracked by 'MyContext' changed from 'Added' to 'Unchanged'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Company' entity with key '{Id: 20}' tracked by 'MyContext' changed from 'Modified' to 'Unchanged'.
dbug: Microsoft.EntityFrameworkCore.Update[10005]
      SaveChanges completed for 'MyContext' with 0 entities written to the database.
```
but the same code with updating from false to true gives:
```
      SaveChanges starting for 'MyContext'.
Name: 'Test company', Id: 17, StandartAccess: True, ExtendedAccess: False, Flag1: False
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10800]
      DetectChanges starting for 'MyContext'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10805]
      Navigation property 'Company.Settings' for entity with key '{Id: 17}' detected as changed.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Settings' entity with key '{CompanyId: 17}' tracked by 'MyContext' changed from 'Unchanged' to 'Deleted'.
Name: 'Test company', Id: 17, StandartAccess: True, ExtendedAccess: False, Flag1: False
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10806]
      Context 'MyContext' started tracking 'Settings' entity with key '{CompanyId: 17}'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10801]
      DetectChanges completed for 'MyContext'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'OwnedTest' on server '.\SQLExpress'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
      Opened connection to database 'OwnedTest' on server '.\SQLExpress'.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20209]
      Beginning transaction with isolation level 'Unspecified'.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20200]
      Began transaction with isolation level 'ReadCommitted'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Company' entity with key '{Id: 17}' tracked by 'MyContext' changed from 'Unchanged' to 'Modified'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20103]
      Creating DbCommand for 'ExecuteReader'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20104]
      Created DbCommand for 'ExecuteReader' (0ms).
dbug: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[@p1='17', @p0='True'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      UPDATE [Companies] SET [Settings_StandartAccess] = @p0
      WHERE [Id] = @p1;
      SELECT [Settings_ExtendedAcces], [Settings_Flag1]
      FROM [Companies]
      WHERE @@ROWCOUNT = 1 AND [Id] = @p1;
dbug: Microsoft.EntityFrameworkCore.Database.Command[20300]
      A data reader was disposed.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20210]
      Committing transaction.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20202]
      Committing transaction.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20002]
      Closing connection to database 'OwnedTest' on server '.\SQLExpress'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20003]
      Closed connection to database 'OwnedTest' on server '.\SQLExpress'.
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20204]
      Disposing transaction.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Settings' entity with key '{CompanyId: 17}' tracked by 'MyContext' changed from 'Deleted' to 'Detached'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Settings' entity with key '{CompanyId: 17}' tracked by 'MyContext' changed from 'Added' to 'Unchanged'.
dbug: Microsoft.EntityFrameworkCore.ChangeTracking[10807]
      The 'Company' entity with key '{Id: 17}' tracked by 'MyContext' changed from 'Modified' to 'Unchanged'.
dbug: Microsoft.EntityFrameworkCore.Update[10005]
      SaveChanges completed for 'MyContext' with 1 entities written to the database.
```

### Further technical details
EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 Pro 10.0.17134
IDE: Visual Studio Professional 2019 16.4.2

Table structure in migration for SqlServer
```C#
migrationBuilder.CreateTable(
                name: "Companies",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(nullable: true),
                    Settings_StandartAccess = table.Column<bool>(nullable: true, defaultValue: false),
                    Settings_ExtendedAcces = table.Column<bool>(nullable: true, defaultValue: false),
                    Settings_Flag1 = table.Column<bool>(nullable: true, defaultValue: false),
                    Settings_Name = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Companies", x => x.Id);
                });
```

**Comment by ajcvickers** [comment] 2020-03-02 21:51
Note for team: I am able to reproduce this, although I am not sure exactly what is happening. It appears that the new owned entity is not being correctly detected due to the store-generated properties. Mutating the owned entity works. It may be something we have already fixed.
/cc @AndriySvyryd

**Comment by lajones** [comment] 2020-03-10 00:08
Not fixed in master. I can repro on both master and 3.1.2. Note that setting each `bool` property on `Settings` to `HasDefaultValue(false)` is important. Without that it doesn't repro.

**Comment by lajones** [comment] 2020-03-10 23:26
You're running into #9627. It's long so let me say - the workaround I think you want is to add `ValueGeneratedNever()` to your properties' configuration, e.g. instead of:

```C#
                        ps.Property(p => p.StandartAccess)
                            .IsRequired()
                            .HasDefaultValue(false);
```

put:

```C#
                        ps.Property(p => p.StandartAccess)
                            .IsRequired()
                            .HasDefaultValue(false)
                            .ValueGeneratedNever();
```

An alternative would be to declare the properties as `bool?` instead of `bool`.

The problem is that `HasDefaultValue()` on a property informs us that the database generates values for the corresponding column. At that point we assume that if that property has its default value (for a `bool` this is `false`) then what you want to do is let the database generate the value. Only if it has a value which is not the default (in this case `true`) will we pass it on to the database.

The first solution above fixes this by telling us "despite the fact that this property has a default value do not assume that the database generates values for this property"; the second because the default value of a `bool?` is `null`, so `false` can now be differentiated from that.

**Closed** 2022-10-16 18:13 UTC
Labels: closed-duplicate, customer-reported
