### ISSUE TITLE
Invalid Column Name for ThenIncluded navigation property in inner select statement

### ISSUE THREAD

**Issue by prodenx** [dotnet/efcore#16853] opened 2019-07-30 19:31 UTC
I have issue with second level navigation properties
The code:

```C#
      _productRepository.GetAll.Include(i => i.Defects).ThenInclude(i => i.Defect)
                .ThenInclude(i => i.Translations).Where(i => i.Defects.Count() > 0).GroupBy(i => i.OperatorId).Select(
                    g =>
                        new OperatorDefectsStatOutputDto()
                        {
                            Operator = g.Key.ToString(),
                            DefectsStat = g.SelectMany(i => i.Defects).Where(i => i.Defect.DefectTypeId == 3)
                                .GroupBy(i => i.DefectCode).Select(gd => new TupleDto()
                                {
                                    Item1 = gd.FirstOrDefault().Defect.Translations
                                                .FirstOrDefault(i => i.Language == "en")
                                                .Title,
                                    Item2 = gd.Count()
                                }).ToList()
                        }).OrderByDescending(i => i.DefectsStat.Sum(d => d.Item2)).ToList();
```
I am getting error:
      System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Language'.
Invalid column name 'Title'.

The columns exist on db and dbContext. Other queries with Defects table work:

```C#
    _productDefectsRepository.GetAll().Include(i => i.Defect).ThenInclude(i => i.Translations).FirstOrDefault(i => i.Defect.DefectTypeId == 3).Defect.Translations
                            .FirstOrDefault(i => i.Language == "en").Title;
```

The entities used in app:

```C#
    [Table("Products")]
    public class Product: Entity<long>
    {
        public string Article { get; set; }

        [ForeignKey("ProductId")]
        public ICollection<ProductDefect> Defects { get; set; }
    }

    [Table("ProductDefects")]
    public class ProductDefect: FullAuditedEntity
    {
        [NotMapped]
        public override int Id { get; set; }

        public long ProductId { get; set; }

        public int DefectCode { get; set; }

        [ForeignKey("DefectCode")]
        public Defect Defect { get; set; }
    }

    [Table("Defects")]
    public class Defect: FullAuditedEntity<int>, IMultiLingualEntity<DefectTranslation>
    {
        [NotMapped]
        public override int Id { get; set; }

        [Key]
        public int Code { get; set; }

        public int? DefectTypeId { get; set; }

        public ICollection<DefectTranslation> Translations { get; set; }
    }

    public class DefectTranslation : Entity, IEntityTranslation<Defect>
    {
        [Required]
        [Column(TypeName = "nvarchar(64)")]
        public string Title { get; set; }

        [Column(TypeName = "varchar(16)")]
        public string Language { get; set; }
        public Defect Core { get; set; }
        public int CoreId { get; set; }
    }
```

The context:

```C#
        public virtual DbSet<Defect> Defects { get; set; }
        public virtual DbSet<DefectTranslation> DefectTranslations { get; set; }
        public virtual DbSet<ProductDefect> ShoePairDefects { get; set; }
        public virtual DbSet<Product> Products{ get; set; }

            modelBuilder.Entity<Product>(b =>
            {
                
            });

            modelBuilder.Entity<Defect>(b =>
            {
                b.Property(e => e.IsEnabled).HasDefaultValue(true);
                b.HasIndex(e => e.DefectTypeId);
            });

            modelBuilder.Entity<ProductDefect>(b =>
            {
                b.HasKey(e => new { e.ProductId, e.DefectCode });
            });
```

Could you help me to resolve the issue, pls?

UPD: .net core 2.2 and aspnetboilerplate are used

**Comment by smitpatel** [comment] 2019-07-30 19:37
Can you provide more details?

**Comment by prodenx** [comment] 2019-07-30 19:38
Sure. Missclicked and saved without description. On process

**Comment by prodenx** [comment] 2019-07-30 20:14
@smitpatel Have updated. Please take a look.

**Comment by prodenx** [comment] 2019-08-13 10:04
Hi everyone. Any luck with that? :)

**Comment by ajcvickers** [comment] 2019-08-13 17:09
@prodenx We are currently tightly focused on the 3.0 release. We intend to get back to investigating this after we have wrapped up there.

**Comment by ajcvickers** [comment] 2019-11-15 22:45
@smitpatel to respond.

**Comment by smitpatel** [comment] 2019-11-16 00:50
Your query contains GroupBy which does not apply aggregate hence it does not correspond to SQL group by. See https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators#groupby for more details. Hence there is no SQL translation possible for above query.

Starting with 3.0 we do not allow client evaluation of GroupBy so above query is not supported. Closing this as by design.

**Comment by prodenx** [comment] 2019-11-16 04:22
Thanks fir info

**Closed** 2022-10-16 14:33 UTC
Labels: closed-by-design, customer-reported
