### ISSUE TITLE
Scaffolding of SQL Server indexes with included columns is broken

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#19351] opened 2019-12-18 13:46 UTC
Included columns are returned in the index's regular (key) column list. Test for SqlServerDatabaseModelFactoryTest:

```c#
        [ConditionalFact]
        public void Index_with_included_properties()
        {
            Test(
                @"
CREATE TABLE IncludedColumnsIndexTable (
    Id int,
    IndexedColumn int NULL,
    IncludedColumn int NULL
);

CREATE INDEX IX_IncludedColumns ON IncludedColumnsIndexTable ( IndexedColumn ) INCLUDE ( IncludedColumn );",
                Enumerable.Empty<string>(),
                Enumerable.Empty<string>(),
                dbModel =>
                {
                    var index = Assert.Single(dbModel.Tables.Single().Indexes);

                    // ReSharper disable once PossibleNullReferenceException
                    Assert.Equal("dbo", index.Table.Schema);
                    Assert.Equal("IncludedColumnsIndexTable", index.Table.Name);
                    Assert.Equal("IX_IncludedColumns", index.Name);
                    Assert.Equal("IndexColumn", Assert.Single(index.Columns).Name);
                },
                "DROP TABLE IncludedColumnsIndexTable;");
        }
```

/cc @bricelam

**Comment by ErikEJ** [comment] 2019-12-18 16:31
I think there is a dupe somewhere...

**Comment by bricelam** [comment] 2020-01-02 22:31
Duplicate of #17083

**Closed** 2022-10-16 18:02 UTC
