### ISSUE TITLE
double 0 saves as 1 ???

### ISSUE THREAD

**Issue by fjallemark** [dotnet/efcore#31589] opened 2023-08-30 10:15 UTC
I got a strange behaviour trying to save a zero C# double value into a SQL Server float column. The zero value of the *ownedShare* property becomes 1 in the database column! Using raw ADO works perfectly. The entity mapping does not touch the *ownedShare* property.

```C#
ownership.OwnedShare = 0.0; // property is double
dbContext.ModuleOwnerships.Add(ownership);
var result = await dbContext.SaveChangesAsync();
```

```SQL
CREATE TABLE [dbo].[ModuleOwnership] (
    [Id]                    INT IDENTITY (1, 1) NOT NULL,
    [PersonId]              INT NULL,
    [GroupId]               INT NULL,
    [ModuleId]              INT NOT NULL,
    [OwnedShare]            FLOAT (53) DEFAULT ((1)) NOT NULL
    CONSTRAINT [PK_ModuleOwnership] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ModuleOwnership_Group] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Group] ([Id]),
    CONSTRAINT [FK_ModuleOwnership_Module] FOREIGN KEY ([ModuleId]) REFERENCES [dbo].[Module] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_ModuleOwnership_Person] FOREIGN KEY ([PersonId]) REFERENCES [dbo].[Person] ([Id])
);
```

```C#
var connection = dbContext.Database.GetDbConnection() as SqlConnection;
if (connection is null) throw new ArgumentException(nameof(connection));
var sql = "INSERT INTO ModuleOwnership (PersonId, GroupId, ModuleId, OwnedShare) VALUES (@PersonId, @GroupId, @ModuleId, @OwnedShare)";
var command = connection.CreateCommand();
command.CommandText = sql;
command.CommandType = System.Data.CommandType.Text;
command.Parameters.AddWithValue("@PersonId", ownership.PersonId.HasValue ? ownership.PersonId.Value : DBNull.Value);
command.Parameters.AddWithValue("@GroupId", ownership.GroupId.HasValue ? ownership.GroupId.Value : DBNull.Value);
command.Parameters.AddWithValue("@ModuleId", ownership.ModuleId);
command.Parameters.AddWithValue("@OwnedShare", 0);
connection.Open();
var result = await command.ExecuteNonQueryAsync(  );
connection.Close();
return result;
```

### Include provider and version information

EF Core version: 7.0.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 7.0)
Operating system: Azure + local development on Windows 10
IDE: Visual Studio 2022 17.7.2)

**Comment by bricelam** [comment] 2023-08-30 21:15
The column is non-nullable and has a default value (of `1`). EF Core uses the CLR default value (`default(double)` or `0`) to determine if a property is unset and the column's default constraint should be used. There are a couple of ways to work around this behavior and insert `0` instead:

1. Remove the default constraint (HasDefaultValue) from your EF model. This will tell EF never to use database's default constraint.
2. Make the CLR type nullable (`double?`) this will change the CLR default value to `null` allowing you to insert `0`. Note in this case, if you try and save `null`, you'll get the database default value of `1` instead, so even though the property is nullable in EF, the column is still never null and can keep its `NOT NULL` constraint.

**Comment by fjallemark** [comment] 2023-08-31 06:17
Thanks @bricelam for quick reply. I suspected that it had something to do if value was 0. I also suppose changing the default value in the column from 1 to 0 solves the problem.

**Comment by ajcvickers** [comment] 2023-09-05 17:03
Duplicate of #701

**Closed by ajcvickers** 2023-09-05 17:03 UTC
Labels: customer-reported
