### ISSUE TITLE
Wrong aliases for columns in select statements

### ISSUE THREAD

**Issue by meancrazy** [dotnet/efcore#12703] opened 2018-07-18 12:29 UTC
If I use aliases or specify column name different from property name EF have problem with generating SQL with `left join` and `group by` statements. E.g. I receive code like this:
```sql
SELECT [x].[Date],
    [x].[Amount] AS [Entity1Amount],
    [x].[Amount] AS [Entity1Amount] + SUM([x].[Amount]) AS [Sum] -- here is the problem
FROM [Entity1Set] AS [x]
LEFT JOIN [Entity2Set] AS [x0]
    ON [x].[Date] = [x0].[Date]
GROUP BY [x].[Date],
    [x].[Amount]
```

### Steps to reproduce
Save files, change connection string in two places and run following commands:
```
dotnet ef migrations add InitialCreate
dotnet ef database update
dotnet test
```
Full listing of test project:
EFCoreError.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.8.0" />
    <PackageReference Include="MicrosoftExtensions.Logging.Xunit" Version="1.0.0" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>
</Project>
```
UnitTest1.cs:
```c#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Xunit;
using Xunit;
using Xunit.Abstractions;

namespace EfCoreError
{
    public class UnitTest1
    {
        public UnitTest1(ITestOutputHelper testOutputHelper)
        {
            var loggerFactory = new LoggerFactory(new[]
            {
                new XunitLoggerProvider(testOutputHelper)
            });
            
            var options = new DbContextOptionsBuilder<Context>().UseLoggerFactory(loggerFactory)
                                                                .UseSqlServer("...")
                                                                .EnableSensitiveDataLogging()
                                                                .Options;

            _context = new Context(options);
        }

        private readonly Context _context;

        [Fact]
        public void Test1()
        {
            var query = _context.Entity1Set
                                .GroupJoin(_context.Entity2Set,
                                           x => x.Date,
                                           x => x.Date,
                                           (e1, e2) => new { e1, e2 })
                                .SelectMany(x => x.e2.DefaultIfEmpty(),
                                            (x, e2) => new
                                            {
                                                x.e1.Date,
                                                Entity1Amount = x.e1.Amount,
                                                Entity2Amount = e2.Amount,
                                            })
                                .GroupBy(x => new
                                {
                                    x.Date,
                                    x.Entity1Amount
                                })
                                .Select(x => new
                                {
                                    x.Key.Date,
                                    x.Key.Entity1Amount,
                                    Sum = x.Key.Entity1Amount + x.Sum(o => o.Entity1Amount)
                                })
                                .ToList();
        }
    }

    public class Entity1
    {
        public int Id { get; set; }

        public DateTimeOffset Date { get; set; }

        public int Amount { get; set; }
    }

    public class Entity2
    {
        public int Id { get; set; }

        public DateTimeOffset Date { get; set; }

        public int Amount { get; set; }
    }

    public class Context : DbContext, IDesignTimeDbContextFactory<Context>
    {
        public DbSet<Entity1> Entity1Set { get; set; }

        public DbSet<Entity2> Entity2Set { get; set; }

        public Context(DbContextOptions options) : base(options)
        {
        }

        public Context()
        {
        }

        public Context CreateDbContext(string[] args)
        {
            var options = new DbContextOptionsBuilder<Context>()
                .UseSqlServer("...")
                .EnableSensitiveDataLogging()
                .Options;

            return new Context(options);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            // So if I describe column name I'll receive same incorrect SQL:
            // modelBuilder.Entity<Entity1>().Property(x => x.Amount).HasColumnName("MySuperColumnName");
        }
    }
}
```

### Further technical details
EF Core version: `2.1.1`
Database Provider: `Microsoft.EntityFrameworkCore.SqlServer`
Operating system: `Windows 10`
IDE:  `Visual Studio 2017 15.7.4`

**Comment by divega** [comment] 2018-07-20 18:40
@smitpatel will find the dupe.

**Comment by smitpatel** [comment] 2018-07-24 05:59
Duplicate of #12656

**Closed** 2022-10-16 13:20 UTC
Labels: closed-duplicate, customer-reported
