### ISSUE TITLE
Include extension points?

### ISSUE THREAD

**Issue by dneimke** [dotnet/efcore#4991] opened 2016-04-05 23:05 UTC
We have designed our application to include the notion of soft-deleting Entities.  e.g. a IsDeleted flag on the Entity indicates that it is soft-deleted whereas a hard-delete does a physical delete on the data in the database.

Are there any extension points when using Include's that would allow us to filter out soft-deleted Entities from result sets?

Example:

```
var employees = employeeService.FindAll().Include(e => e.Address)
```

In the above example, employeeService's FindAll method filters soft-deleted data at the top level but it would be nice to have an unobtrusive way to filter Addresses to return only non soft-deleted rows.

**Comment by dneimke** [comment] 2016-04-06 07:02
You can probably close th

**Comment by gdoron** [comment] 2016-08-01 10:15
@rowanmiller @Bartmax
Do you know what happened to issue #1833?
I get 404, but I know there was such an issue (I got email notifications for that issue, and this one was closed as a duplicate of it) and as AFAIK GitHub doesn't provide an API for deleting issues.

Anyway, both me and @Bartmax asked how can we do stuff like

	.Include(x=> x.Images.Where(image => !image.IsDeleted)

Is there a different issue tracking it?
I searched quite a lot but couldn't find anything.

**Comment by gdoron** [comment] 2016-08-01 19:03
Hmm, #1833 is working again.
Not sure what was the issue.

**Closed** 2022-10-16 09:35 UTC
