### ISSUE TITLE
DbQuery FromSql issue when sp returns Date instead DateTime

### ISSUE THREAD

**Issue by NGancevich** [dotnet/efcore#13435] opened 2018-09-28 07:52 UTC
I'm using asp.net core 2.1 and code first. I need get data from sp

```C#
public DbQuery<StatisticCallsEntry> StatisticCalls

public IQueryable<StatisticCallsEntry> GetStatisticCalls(short companyId, DateTime start, DateTime end)
        {
            return ctx.StatisticCalls.FromSql("exec dbo.usp_Statistic_Calls @companyId, @start, @end", new SqlParameter("@companyId", companyId), new SqlParameter("@start", start), new SqlParameter("@end", end));


        }


 public class StatisticCallsEntry
    {
        public DateTime Date { get; set; }
        //public string ManagerName { get; set; }
        public int OutgoingCount { get; set; }
        public int IncomingCount { get; set; }
        public int OutgoingSeconds{ get; set; }
        public int IncomingSeconds { get; set; }
        public int Total => OutgoingCount + IncomingCount;
        public int TotalSeconds => OutgoingSeconds + IncomingSeconds;
    }
```
If sp return Date column as 'Date' type it doesn't work. If I change Date column type to datetime - it's working. 

Please advise

**Comment by NGancevich** [comment] 2018-09-28 08:07
I also find If I renamed class property from Date to StateDate it's also working

**Comment by ajcvickers** [comment] 2018-09-28 21:04
@NGancevich Can you post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by NGancevich** [comment] 2018-09-29 11:56
@ajcvickers , unfortunately I can't upload the project but it's wrote all needed code to reproduce the issue.

**Comment by ajcvickers** [comment] 2018-10-01 16:36
@NGancevich I attempted to add in other code needed to reoproduce what you are seeing, but it is working for me:
```C#
public class BackingTable
{
    public int Id { get; set; }

    [Column(TypeName = "date")]
    public DateTime Date { get; set; }
    //public string ManagerName { get; set; }
    public int OutgoingCount { get; set; }
    public int IncomingCount { get; set; }
    public int OutgoingSeconds { get; set; }
    public int IncomingSeconds { get; set; }
}

public class StatisticCallsEntry
{
    public DateTime Date { get; set; }
    //public string ManagerName { get; set; }
    public int OutgoingCount { get; set; }
    public int IncomingCount { get; set; }
    public int OutgoingSeconds { get; set; }
    public int IncomingSeconds { get; set; }
    public int Total => OutgoingCount + IncomingCount;
    public int TotalSeconds => OutgoingSeconds + IncomingSeconds;
}

public class BloggingContext : DbContext
{
    private static readonly LoggerFactory Logger
        = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    public DbQuery<StatisticCallsEntry> StatisticCalls { get; set; }

    public IQueryable<StatisticCallsEntry> GetStatisticCalls(short companyId, DateTime start, DateTime end)
    {
        return StatisticCalls.FromSql(
            "exec dbo.usp_Statistic_Calls @companyId, @start, @end", 
            new SqlParameter("@companyId", companyId), 
            new SqlParameter("@start", start), 
            new SqlParameter("@end", end));
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BackingTable>();
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var connection = context.Database.GetDbConnection();
            var command = connection.CreateCommand();
            command.CommandText = @"
CREATE PROCEDURE usp_Statistic_Calls @companyId smallint, @start datetime2, @end datetime2
AS
SELECT Date, OutgoingCount, IncomingCount, OutgoingSeconds, IncomingSeconds
FROM BackingTable";

            connection.Open();
            command.ExecuteNonQuery();
            connection.Close();

            context.Add(new BackingTable()
            {
                Date = new DateTime(1973, 9, 3)
            });

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var results = context.GetStatisticCalls(1, DateTime.Now, DateTime.Now).ToList();
        }
    }
}
```

**Comment by NGancevich** [comment] 2018-10-01 16:57
@ajcvickers , but I used Fromsql method to get sp data.

**Comment by ajcvickers** [comment] 2018-10-01 17:09
@NGancevich I'm using the same code you posted to get the data, which uses `FromSql`.

**Comment by NGancevich** [comment] 2018-10-01 17:16
@ajcvickers , yes. You have the same. It's weird .  Did you have any entry in your table?

**Comment by ajcvickers** [comment] 2018-10-01 17:36
@NGancevich Yes. The full code as a console app is posted above.

**Comment by ajcvickers** [comment] 2018-10-08 17:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:32 UTC
Labels: closed-could-not-reproduce, customer-reported
