### ISSUE TITLE
Memory Leak in EF Core?

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [dotnet/efcore#14640] opened 2019-02-07 17:39 UTC
Hi, My project has a big query with linq queryable, and I have memory leak issues, when I execute my query, memory usage goes up each every request, no GC.Collect helped me. however I used using keyword for my context in every requests.

I uploaded the dump file you can check it in vs 2017 enterprice and see where is the memory leak problems, I uploaded an attached image too.

ef core nuget package version:
3.0.0-preview.19074.3

![ef core memory problem](https://user-images.githubusercontent.com/5262218/52430578-aa225980-2b1b-11e9-94fb-94a7e41ac828.png)

[dump file](http://dev.atitec.ir:4321/Expert.ConsoleWindowsServer.zip)

**Comment by Ali-YousefiTelori** [comment] 2019-02-07 20:16
full query:

```csharp
private static MessageContract<List<ShopInfo>> FilterShopInfoes(ShopFilterInfo filterInfo)
        {
            using (ExpertContext context = new ExpertContext(false))
            {
                IQueryable<ShopContractInfo> query = context.ShopInfoes
                    .Include(x => x.FileInfoes)
                    .Include(x => x.CategoryInfo)
                    .AsNoTracking()
                    .AsQueryable().Select(x => new ShopContractInfo()
                    {
                        Rate = x.RateInfoes.Select(y => (double)y.Rate).DefaultIfEmpty(0).Average(y => y),
                        CommentCount = x.CommentInfoes.Count,
                        ProductsVitrinCount = x.ProductInfoes.Count(y => y.IsVitrin),
                        ProductsNotVitrinCount = x.ProductInfoes.Count(y => !y.IsVitrin),
                        Comments = x.CommentInfoes.AsQueryable().SelectPageAsQueryable(0, 10),
                        ShopInfo = x
                    });
                query = query.Where(x => x.ShopInfo.IsEnabled);

                if (filterInfo.UserId.HasValue)
                    query = query.Where(x => x.ShopInfo.UserId == filterInfo.UserId);

                if (filterInfo.StartDateTime != null)
                {
                    DateTime date = filterInfo.StartDateTime.Value.Date;
                    query = query.Where(x => x.ShopInfo.CreatedDateTime >= date);
                }
                if (filterInfo.EndDateTime != null)
                {
                    DateTime date = filterInfo.EndDateTime.Value.Date;
                    query = query.Where(x => x.ShopInfo.CreatedDateTime <= date);
                }
                if (!string.IsNullOrEmpty(filterInfo.Text))
                {
                    query = query.Where(x => x.ShopInfo.Name.Contains(filterInfo.Text));
                }

                if (filterInfo.ShopSaleType.HasValue)
                {
                    query = query.Where(x => x.ShopInfo.SaleType == filterInfo.ShopSaleType || x.ShopInfo.SaleType == ShopSaleType.Both);
                }

                if (filterInfo.CanSend.HasValue)
                {
                    query = query.Where(x => x.ShopInfo.CanSend == filterInfo.CanSend);
                }

                if (filterInfo.CategoryId.HasValue)
                {
                    query = query.Where(x => x.ShopInfo.CategoryId == filterInfo.CategoryId);
                }
                if (!string.IsNullOrEmpty(filterInfo.CityName))
                {
                    query = query.Where(x => x.ShopInfo.CityName == filterInfo.CityName);
                }
                query = query.OrderByDescending(x => x.ShopInfo.CreatedDateTime);

                List<ShopContractInfo> result = null;
                if (filterInfo.Latitude.HasValue && filterInfo.Longitude.HasValue)
                {
                    MessageContract<(double X1, double Y1, double X2, double Y2, double Length)> rect = GetEarthRectangle();
                    Rectangle rectangle = new Rectangle(new Point(rect.Data.X1, rect.Data.Y1), new Point(rect.Data.X2, rect.Data.Y2));
                    int index = RectangleUtil.GetRectIndexByPoint(new Point(filterInfo.Latitude.Value, filterInfo.Longitude.Value), rectangle, rect.Data.Length);

                    int[] indexes = RectangleUtil.GetListOfIndexes(index, rectangle, rect.Data.Length).ToArray();
                    query = query.Where(x => indexes.Contains(index));
                    result = query.ToList();

                    GeoCoordinate sCoord = new GeoCoordinate(filterInfo.Latitude.Value, filterInfo.Longitude.Value);
                    IEnumerable<ShopContractInfo> query2 = result.Where(x => CheckIsNear(x.ShopInfo, sCoord));
                    result = query2.SelectPage(filterInfo.Index, filterInfo.Length);
                }
                else
                {
                    result = query.SelectPage(filterInfo.Index, filterInfo.Length);


                }

                foreach (ShopContractInfo x in result)
                {
                    x.ShopInfo.Rate = x.Rate;
                    x.ShopInfo.CommentCount = x.CommentCount;
                    x.ShopInfo.ProductsVitrinCount = x.ProductsVitrinCount;
                    x.ShopInfo.ProductsNotVitrinCount = x.ProductsNotVitrinCount;
                    x.ShopInfo.CommentInfoes = x.Comments.ToList();
                }

                return result.Select(x => x.ShopInfo).ToList().Success();
            }
        }
        private static bool CheckIsNear(ShopInfo shopInfo, GeoCoordinate sCoord)
        {
            if (!shopInfo.Latitude.HasValue || !shopInfo.Longitude.HasValue)
                return false;
            GeoCoordinate eCoord = new GeoCoordinate(shopInfo.Latitude.Value, shopInfo.Longitude.Value);
            double distance = sCoord.GetDistanceTo(eCoord);
            if (distance <= SettingInfo.GetSettingInteger("NearShopDistance"))
            {
                return true;
            }
            else
                return false;
        }


        public static MessageContract<(double X1, double Y1, double X2, double Y2, double Length)> GetEarthRectangle()
        {
            return (40.011517, 43.570553, 23.613212, 63.823850, 0.0063613231552163).Success();
        }
```

**Comment by smitpatel** [comment] 2019-02-07 20:21
What is your connection string? Specifically do you have MARS enabled? How much data is on server side? Given the shape of query, there would be a lot of client evaluation.

**Comment by Ali-YousefiTelori** [comment] 2019-02-07 20:43
my connection string is :
Server=.;initial catalog=Expert;User ID=uid;Password=pass

I don't know what is MARS.
data is not large my database is 80MB but users request is comming always,i have more servers just for this server i have this problem.

**Comment by smitpatel** [comment] 2019-02-08 19:02
@Ali-YousefiTelori - Just for info, this is [documentation](https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-multiple-active-result-sets-mars?view=sql-server-2017) about MARS if you are interested.

By default MARS is off. (looking at your connectionstring that would be case here too). Further since there is collection include we do send multiple queries causing one of the query to buffer. Also there is a lot of client evaluation involved so I would suspect large amount of data is being fetched from server.

There are few things which will improve above scenario in 3.0 release. First we won't be doing so much of client evaluation, hence unexpectedly fetching large data from server would be gone. Further according to #12098, we will use single query for includes. What that means is, we wouldn't need buffering internally. Hence in your case, a no-tracking query would not get/store more data than what is current result row is.

**Comment by Mart-Bogdan** [comment] 2019-02-09 15:22
@Ali-YousefiTelori take a look at this #13048 issue, perhaps it's related

**Comment by Ali-YousefiTelori** [comment] 2019-02-10 19:28
@smitpatel  after I activated MARS I think problems gone, my app after 2 days is 80MB in memory. Thank you for your answer

**Comment by ajcvickers** [comment] 2019-02-11 18:09
Duplicate of #12098

**Comment by Ali-YousefiTelori** [comment] 2019-02-23 14:29
MARS feature not works too, but its better, i have two reset my server every week because of memory leack problem,

**Closed** 2022-10-16 13:51 UTC
Labels: customer-reported
