### ISSUE TITLE
OwnedType throws error entity type is sharing the table

### ISSUE THREAD

**Issue by cetk** [dotnet/efcore#17165] opened 2019-08-15 01:04 UTC
I am using .net Core 2.2 and EFCOre 2.2.6 and having error for Owned Type

Hers is my code

    public class StorageSummary
    {
        public int Id { get; set; }
        public StorageDetailSummary Original { get; set; }
        public StorageDetailSummary Initial { get; set; }
        public StorageDetailSummary Accepted { get; set; }
    }

    [Owned]
    public class StorageDetailSummary
    {
        public decimal? PrimaryTow { get; set; }
        public decimal? LaborCost { get; set; }
    }
   

      In dbcontext
    
                     modelBuilder.Entity<StorageSummary>(table =>
                    {
                       table.OwnsOne(
                       a => a.Original, 
                      original =>
                     {
		           original.Property(x => x.PrimaryTow).HasColumnName("OriginalPrimaryTow");
                          original.Property(x => x.LaborCost).HasColumnName("OriginalLaborCost");
                    });
                });

When I add to dbCOntext and SaveChanges I get the error as 
  
The entity of type 'StorageSummary' is sharing the table 'StorageCheck.StorageSummaries' with entities of type 'StorageSummary.Initial#StorageDetailSummary', but there is no entity of this type with the same key value that has been marked as 'Added'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values.

**Comment by ajcvickers** [comment] 2019-08-15 14:54
Duplicate of #9005. In EF Core 2.2, when an owner and an owned type share the same table, then the owner must always have an associated owned type.

**Comment by kashania** [comment] 2020-02-21 05:46
always you need to initialize the this StorageDetailSummary when you add it to the entity

**Closed** 2022-10-16 14:35 UTC
Labels: closed-duplicate, customer-reported
