### ISSUE TITLE
How can I override a MaxLength convention with an attribute?

### ISSUE THREAD

**Issue by kbaley** [dotnet/efcore#28655] opened 2022-08-10 21:39 UTC
## Ask a question

I've define a convention in `ConfigureConventions` where all strings are to have a max length of 256. I'd like to override this for some properties, for example by setting the type to `nvarchar(max)` and setting `[MaxLength(int.MaxValue)]`. This correctly sets the column type but the maxLength is still 256.

If I set the max length in `OnModelCreating`, it works fine but I was wondering if there was a way to do it with the data annotations.

### Include your code

DB Context

```C#
protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder) {
    base.ConfigureConventions(configurationBuilder);

    configurationBuilder.Properties<string>()
        .HaveMaxLength(256);
}
```

Domain object

```C#
public class MyObject {
	// ...
    [Column(TypeName = "nvarchar(MAX)")]
    [MaxLength(int.MaxValue)]
    public string Notes { get; set; }
}
```

(Note: I also tried `[StringLength(int.MaxValue)]`

Resulting migration code:

```C#
    // ...
   Notes = table.Column<string>(type: "nvarchar(MAX)", maxLength: 256, nullable: false),
    // ...
```

### Include provider and version information

EF Core version: 6.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer 6.0.5
Target framework: .NET 6.0
Operating system: MacOS 12.3.1
IDE: VS Code 1.70.0

**Comment by kbaley** [comment] 2022-08-10 21:50
Quick update: If I specify these attributes:

```C#
[Column(TypeName = "nvarchar"]
[MaxLength(100)
```
then I get the following in the migration:

```C#
Notes = table.Column<string>(type: "nvarchar(2147483647)", maxLength: 2147483647, nullable: false),
```

So in this case, it _is_ overriding the maxLength property but it seems to be using `int.MaxValue`

**Comment by roji** [comment] 2022-08-11 06:29
Duplicate of #28541

**Comment by roji** [comment] 2022-08-11 06:29
Unfortunately that isn't possible; code in ConfigureConventions cannot be overridden via attributes (but can be overridden via the Fluent API).

**Closed** 2022-08-15 14:54 UTC
Labels: customer-reported
