### ISSUE TITLE
EF Core returns only first child per parent for keyless entities

### ISSUE THREAD

**Issue by verynewuser** [dotnet/efcore#20247] opened 2020-03-10 23:20 UTC
If we define two entities, one a normal entity and the other a keyless entity and try to fetch them from database, using some common column between them, through LINQ, only the first child item is returned for keyless entity.

### Steps to reproduce

For example the object model is this:
``` C#
public class ItemViewModel
{
    public Item ItemObject { get; set; }
    public IEnumerable<LineItem> Fields { get; set; } = new List<LineItem>();
}

public class Item
{
    public int ItemId { get; set; }
    public DateTime DatePurchased { get; set; }
}

public class LineItem
{
    public int ItemId { get; set; }
    public string Name { get; set; }
}
```
The database contains Items and LineItems tables, corresponding to the object model. I am using the below written LINQ expression to retrieve an `ItemViewModel` object, provided an Item ID.
``` C#
var i = from i in _dbContext.Items
        where i.ItemId == 123
        select new ItemViewModel
        {
            ItemObject = i,
            Fields = from field in _dbContext.LineItems
                     where field.ItemId == i.ItemId
                     select field
        };            
var viewModel = await i.SingleOrDefaultAsync();
```
The code compiles fine but after its execution the viewModel.Fields property contains only one list item whereas there are three Line Items against ItemID:123, in the database table.

The SQL generated by this snippet (captured through SQL Profiler) returns three line items, through a LEFT JOIN. That means the generated SQL is fine but something is not going well with Entity Framework but I don't know what? Here is the generated SQL query which correctly gives me three rows:

``` SQL
SELECT 
    [t].[ItemId], [t].[DatePurchased], 
    [s0].[ItemId], [s0].[Name]
FROM 
    (
    SELECT 
        TOP(2) [s].[ItemId], [s].[DatePurchased]
    FROM 
        [Items] AS [s]
    WHERE 
        [s].[ItemId] = 123
    ) AS [t]
LEFT JOIN [LineItems] AS [s0] ON [t].[ItemId] = [s0].[ItemId]
ORDER BY [t].[ItemId]
```

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1

**Comment by davidroth** [comment] 2020-03-11 07:19
Works on my machine:

![image](https://user-images.githubusercontent.com/338856/76391890-be650580-6370-11ea-9239-5546cacd0902.png)

```csharp
void Main()
{
var context = new SampleContext();
	context.Database.EnsureDeleted();
	context.Database.EnsureCreated();

	foreach (var _ in Enumerable.Range(1, 10))
	{
		var item = new Item();
		context.Items.Add(item);

		context.SaveChanges();

		foreach (var i in Enumerable.Range(1, 10))
		{
			context.LineItems.Add(new LineItem() { ItemId = item.ItemId });
		}

		context.SaveChanges();
	}
	
	context = new SampleContext();
	var result = from i in context.Items
			where i.ItemId == 2
			select new ItemViewModel
			{
				ItemObject = i,
				Fields = from field in context.LineItems
						 where field.ItemId == i.ItemId
						 select field
			};
			
	var viewModel = await result.SingleOrDefaultAsync();
}
class SampleContext : DbContext
{
	public DbSet<Item> Items { get; set; }
	public DbSet<LineItem> LineItems { get; set; }

	public SampleContext() {}

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		base.OnConfiguring(optionsBuilder);
		//optionsBuilder.UseInMemoryDatabase("test");
		optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=efcoreitemtesting;Integrated Security = true");

	}
}

public class ItemViewModel
{
	public Item ItemObject { get; set; }
	public IEnumerable<LineItem> Fields { get; set; } = new List<LineItem>();
}

public class Item
{
	public int ItemId { get; set; }
	public DateTime DatePurchased { get; set; }
}

public class LineItem
{
	public int LineItemId { get; set; }
	public int ItemId { get; set; }
	public string Name { get; set; }
}
```

**Comment by ajcvickers** [comment] 2020-03-12 20:06
@verynewuser I am also not able to reproduce this. Please attach a small, runnable project or a complete, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by powermetal63** [comment] 2020-03-13 22:09
It's reproducible. Also see [Simon_Weaver](https://stackoverflow.com/users/16940/simon-weaver) comments under [this SO post](https://stackoverflow.com/a/56156393/5202563) where I've heard about this behavior for the first time and was able to reproduce it.

The key here is **keyless**, e.g. 

    optionsBuilder.Entity<LineItem>().HasNoKey();

and the effect is that all materialized subcollections contain **single** and also **one and the same** (probably first) `LineItem`.

**Comment by ajcvickers** [comment] 2020-03-15 21:45
@powermetal63 It's hard to see how making LineItem keyless makes sense with this model. If it is intended to be keyless, then we would also need to see the rest of the model configuration. I tried playing with it some more, but I'm guessing too much about what the intention of the model is here. That's why I asked for a small, runnable project or a complete, runnable code listing that reproduces what what is happening so that we can investigate.

**Comment by ajcvickers** [comment] 2020-03-23 15:50
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:15 UTC
Labels: closed-could-not-reproduce, customer-reported
