### ISSUE TITLE
EF Database Update fails silently when using NetTopologySuite with SQLite

### ISSUE THREAD

**Issue by mphollas** [dotnet/efcore#20607] opened 2020-04-12 07:29 UTC
As the title states, when I try to apply a migration it fails silently, as in no error or indication that it failed other than the DB not being updated.

I am using the 
- dotnet blazorserver template 
- core 3.1.3
- OSx
-  PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite" Version="3.1.3"
with the following at startup
```
services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlite(
                    Configuration.GetConnectionString("DefaultConnection"),e=>e.UseNetTopologySuite()));
```
and a model extending IdentityUser where I am adding the following
```
public class AppUser : IdentityUser
 {
public Point Location { get; set; }
}
```
then create a migration and apply using update database. Without error, you should find the DB not updated

Expected result: Updated

**Comment by ajcvickers** [comment] 2020-04-13 15:35
@mphollas Please post post the output from running `dotnet ef database update --verbose`.

**Comment by ajcvickers** [comment] 2020-04-24 16:22
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:20 UTC
Labels: closed-could-not-reproduce, customer-reported
