### ISSUE TITLE
Scaffolding Issue when using DatabaseNames

### ISSUE THREAD

**Issue by rposener** [dotnet/efcore#13121] opened 2018-08-26 15:38 UTC
Please change the ReplacementScaffoldingModelFactory to allow using a IPluralizerService even when using DatabaseNames.  This opens a great world of possibilities where we can inject our own PluralizerService and name things in a manner that works well.  As it currently stands, we must either opt into your CSharpUniqueNamer - which mandates removal of non-alphanumeric characters (e.g. underscores in table names) in order to use pluralization.  As we have a legacy database which uses pluralization in table names inconsistently, we have always used pluralization, but otherwise kept to our table names.

### Further technical details
EF Core version: 2.1 current
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by bricelam** [comment] 2018-08-27 16:26
Duplicate of #12102

**Closed** 2022-10-16 13:27 UTC
Labels: closed-duplicate, customer-reported
