### ISSUE TITLE
Distinct in sub-query breaks NON NULL filter

### ISSUE THREAD

**Issue by slipdef** [dotnet/efcore#22007] opened 2020-08-10 15:53 UTC
I'm really not sure what caused the issue but you can see in the below screenshot that Where(l => l != null) coupled with Distinct doesn't produce expected result (=empty array). If I remove distinct all works fine, I get empty array.

![image](https://user-images.githubusercontent.com/4365327/89802400-aed62c80-db5b-11ea-93c3-86aa84660a46.png)

### Further technical details

EF Core version: EF Core 5 Preview 7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.5

**Comment by smitpatel** [comment] 2020-08-10 17:34
Duplicate of #15873 

Unsupported scenario. Once you apply Distinct we don't have way to get enough data out of result to correlate the elements to outer results to generate proper lists of inner elements.

**Comment by slipdef** [comment] 2020-08-10 18:06
@smitpatel any workaround? Because client-side evaluation doesn't work as well surprisingly:
Distinct().ToArray().Where(l => l != null).ToArray()

**Comment by smitpatel** [comment] 2020-08-10 18:17
You need to get the related data in a separate query and connect them manually on client side.

**Closed** 2022-10-16 18:36 UTC
Labels: closed-duplicate, customer-reported
