### ISSUE TITLE
Prevent Entity Framework adding ORDER BY when using Include

### ISSUE THREAD

**Issue by sonyks** [dotnet/efcore#20397] opened 2020-03-24 22:36 UTC
We have a query similar to the following:
```
var blogs = db.Blogs
                    .Include(b => b.Posts)
                    .Where(b => b.BlogId == 1)
                    .ToArray();
```
The problem is that when we add .Include(x => x.Posts), the ORDER BY statement that Entity Framework adds to the generated SQL causes the query to take a long time to execute - something like the below:
```
SELECT [b].[BlogId], [b].[Name], [b].[Url]
FROM [Blogs] AS [b]
WHERE [b].[BlogId] = 1
ORDER BY [b].[BlogId]
```
Another issue is related to Include\Where using. In the previous sample the SQL Profiler detects 2 requests on the server side. The question is why we have two sql queries instead of one?

```
SELECT [b].[BlogId], [b].[Name], [b].[Url]
FROM [Blogs] AS [b]
WHERE [b].[BlogId] = 1
ORDER BY [b].[BlogId]
go
SELECT [b.Posts].[PostId], [b.Posts].[BlogId], [b.Posts].[Content], [b.Posts].[IsDeleted], [b.Posts].[Title]
FROM [Posts] AS [b.Posts]
INNER JOIN (
    SELECT [b0].[BlogId]
    FROM [Blogs] AS [b0]
    WHERE [b0].[BlogId] = 1
) AS [t] ON [b.Posts].[BlogId] = [t].[BlogId]
ORDER BY [t].[BlogId]
go
```

The same code without Include generates an optimal sql query.
```
var blogs = (from b in db.Blogs
                             join p in db.Posts on b.BlogId equals p.BlogId
                             where b.BlogId == 1
                             select b)
                        .ToArray();
```
SQL output:
```
SELECT [b].[BlogId], [b].[Name], [b].[Url]
FROM [Blogs] AS [b]
INNER JOIN [Posts] AS [p] ON [b].[BlogId] = [p].[BlogId]
WHERE [b].[BlogId] = 1
```

### Steps to reproduce

Below you will find the source code which helps you to reproduce the issue
```
public class Blog
{
    public int BlogId { get; set; }
    public string Name { get; set; }
    public string Url { get; set; }

    public List<Post> Posts { get; set; }
}

public class Post
{
    public int PostId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }
    public bool IsDeleted { get; set; }

    public int BlogId { get; set; }
    public Blog Blog { get; set; }
}

public class BloggingContext : DbContext
{
    public BloggingContext(DbContextOptions<BloggingContext> options) : base(options)
    {
        Database.EnsureDeleted();
        Database.EnsureCreated();
    }

    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }
       
}

class Program
{
    static void Main(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<BloggingContext>();
        optionsBuilder.UseSqlServer("Server=localhost;Database=BlogDB;Trusted_Connection=True;", providerOptions => providerOptions.CommandTimeout(60));

        using (var db = new BloggingContext(optionsBuilder.Options))
        {
            var blog = new Blog
            {
                Name = "My Blog",
                Url = "https://www.7-zip.org/"
            };

            var posts = new List<Post>()
            {
                new Post
                {
                    Title = "post 1",
                    Content = "content 1"
                },
                new Post
                {
                    Title = "post 2",
                    Content = "content 2"
                }
            };

            blog.Posts = new List<Post>();
            blog.Posts.AddRange(posts);

            db.Blogs.Add(blog);
            db.SaveChanges();

            //Before 
            var blogs = db.Blogs
                .Include(b => b.Posts)
                .Where(b => b.BlogId == 1)
                .ToArray();

            foreach (var b in blogs)
            {
                Console.WriteLine(b.Name);
            }
        }
    }
}
```

### Further technical details

EF Core version: 2.2.6 & 3.1.3
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system: Windows 10 Enterprise
IDE: (e.g. Visual Studio 2019 16.4.6)

**Comment by maumar** [comment] 2020-03-26 19:39
dupe of https://github.com/dotnet/efcore/issues/19828

Wrt second part, in 3.x we issue single query for include cases.

**Closed** 2022-10-16 18:17 UTC
Labels: customer-reported

**Comment by hri123phapale** [comment] 2023-10-18 10:48
var blogs = (from b in db.Blogs
                             join p in db.Posts on b.BlogId equals p.BlogId
                             where b.BlogId == 1
                             select b)
                        .ToArray();

If you include anything from table p in select it adds the default orderby

**Comment by roji** [comment] 2023-10-18 10:56
Duplicate of #29171
