### ISSUE TITLE
Change detection converting Null to -2147482647 (Int32.Min + 1) on nullable FK . SaveChanges() fails with FK constraint error.

### ISSUE THREAD

**Issue by DanielHillebrandSWMS** [dotnet/efcore#19552] opened 2020-01-10 11:07 UTC
I have found a case where setting a navigation property to Null causes SaveChanges() to fail, because the Change Detection is trying to insert the value -2147482647 into the database instead of Null. 

I have been able to reproduce the issue both with .Net Core 3.1 and also 4.6.2. I will attach a complete solution with unit-test code.

I don't know if it's important for the issue, but I got my Models and Context in a separate netstandard2.0 lib.

I have found the issue in production code, migrating a project from EF 2.2.6 to EF 3.1. It worked with EF 2.2.6.

### Steps to reproduce

(calling SaveChanges() after each step)

* Add new parent entry
* Add new child entry
* Fetch parent entry and set nav-property of parent entry to child entry
* Set nav-property of parent entry to Null (Throws on SaveChanges())

```
   public class BloggingContext : DbContext
    {
        public static readonly ILoggerFactory loggerFactory = new LoggerFactory(new[] {
            new DebugLoggerProvider()
        });

        public DbSet<Blog> Blogs { get; set; }
        public DbSet<BlogType> BlogTypes { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            options.UseSqlServer("Data Source=localhost;Initial Catalog=EF31_NullableNavPropError;Persist Security Info=True;Integrated Security=SSPI;");
            options.UseLoggerFactory(loggerFactory);
            options.EnableSensitiveDataLogging();
        }
    }

```
  ```
  public class Blog
    {
        public int BlogId { get; set; }

        public int? BlogTypeId { get; set; }

        public virtual BlogType BlogType { get; set; }
    }
```

```
    public class BlogType
    {
        public int BlogTypeId { get; set; }

        public virtual ICollection<Blog> Blogs { get; set; }
    }
```

```
   [TestMethod]
        public void AssignBlogTypeForAlreadyExistingBlog_SetBlogTypeNavToNull_ShouldWorkButFails()
        {
            var context = new BloggingContext();

            // Clean db
            context.Blogs.RemoveRange(context.Blogs);
            context.BlogTypes.RemoveRange(context.BlogTypes);

            // Create Blog
            context.Blogs.Add(new Blog());
            context.SaveChanges();

            // Create BlogType and assign to Blog
            var blogType = new BlogType();
            context.SaveChanges();

            context.Blogs.Single().BlogType = blogType;
            context.SaveChanges();

            Assert.AreEqual(context.Blogs.Single().BlogTypeId, context.BlogTypes.Single().BlogTypeId);

            // Set BlogType to NULL
            var blog = context.Blogs.Single();
            blog.BlogType = null;
            context.SaveChanges(); // Here is where it throws

            // Assert
            blog = context.Blogs.Single();

            Assert.AreEqual(null, blog.BlogType);
            Assert.AreEqual(null, blog.BlogTypeId);
        }
```

**EF Core log with Change Detection, SQL and Stack Trace:**

```
Microsoft.EntityFrameworkCore.Database.Command: Debug: A data reader was disposed.
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Closing connection to database 'EF31_NullableNavPropError' on server 'localhost'.
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Closed connection to database 'EF31_NullableNavPropError' on server 'localhost'.
Microsoft.EntityFrameworkCore.Update: Debug: SaveChanges starting for 'BloggingContext'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: DetectChanges starting for 'BloggingContext'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Navigation property 'Blog.BlogType' for entity with key '{BlogId: 32}' detected as changed.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: The 'Blog' entity with key '{BlogId: 32}' tracked by 'BloggingContext' changed from 'Unchanged' to 'Modified'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Foreign key property 'Blog.BlogTypeId' detected as changed from '31' to '-2147482647' for entity with key '{BlogId: 32}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: DetectChanges completed for 'BloggingContext'.
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Opening connection to database 'EF31_NullableNavPropError' on server 'localhost'.
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Opened connection to database 'EF31_NullableNavPropError' on server 'localhost'.
Microsoft.EntityFrameworkCore.Database.Transaction: Debug: Beginning transaction with isolation level 'Unspecified'.
Microsoft.EntityFrameworkCore.Database.Transaction: Debug: Began transaction with isolation level 'ReadCommitted'.
Microsoft.EntityFrameworkCore.Database.Command: Debug: Creating DbCommand for 'ExecuteReader'.
Microsoft.EntityFrameworkCore.Database.Command: Debug: Created DbCommand for 'ExecuteReader' (1ms).
Microsoft.EntityFrameworkCore.Database.Command: Debug: Executing DbCommand [Parameters=[@p1='32', @p0='-2147482647' (Nullable = true)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
UPDATE [Blogs] SET [BlogTypeId] = @p0
WHERE [BlogId] = @p1;
SELECT @@ROWCOUNT;
Microsoft.EntityFrameworkCore.Database.Command: Error: Failed executing DbCommand (3ms) [Parameters=[@p1='32', @p0='-2147482647' (Nullable = true)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
UPDATE [Blogs] SET [BlogTypeId] = @p0
WHERE [BlogId] = @p1;
SELECT @@ROWCOUNT;
Microsoft.EntityFrameworkCore.Database.Transaction: Debug: Disposing transaction.
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Closing connection to database 'EF31_NullableNavPropError' on server 'localhost'.
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Closed connection to database 'EF31_NullableNavPropError' on server 'localhost'.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.0\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.0\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.EntityFrameworkCore.Update: Error: An exception occurred in the database while saving changes for context type 'EfContextLib.BloggingContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_Blogs_BlogTypes_BlogTypeId". The conflict occurred in database "EF31_NullableNavPropError", table "dbo.BlogTypes", column 'BlogTypeId'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:199104db-f299-4ecd-bd2a-99072b4b4d01
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)

Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_Blogs_BlogTypes_BlogTypeId". The conflict occurred in database "EF31_NullableNavPropError", table "dbo.BlogTypes", column 'BlogTypeId'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:199104db-f299-4ecd-bd2a-99072b4b4d01
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Exception thrown: 'Microsoft.EntityFrameworkCore.DbUpdateException' in Microsoft.EntityFrameworkCore.dll
An exception of type 'Microsoft.EntityFrameworkCore.DbUpdateException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code
An error occurred while updating the entries. See the inner exception for details.

```
-->

### Further technical details

EF Core version: 3.1.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1 and NET Framework 4.6.2 (both tested and included in Solution)
Operating system: Windows 10 Pro (1903)
IDE: Visual Studio 2019 16.4.2
[EF31_NullableNavPropToMinINT_cleaned.zip](https://github.com/dotnet/efcore/files/4045243/EF31_NullableNavPropToMinINT_cleaned.zip)

**Comment by DanielHillebrandSWMS** [comment] 2020-01-10 16:23
I just debugged the test again and realized that I did not add the BlogType entry explicitely, but implicetly because it was referenced by the nav prop.

Whe adding it (`context.BlogTypes.Add(blogType);`) explicitly it works.

Here is a new version of the test that does not fail anymore. 

**Please note that this workaround does not make any sense to me and imho does not explain the cause for the reported issue.**

    ```
    [TestMethod]
        public void AssignBlogTypeForAlreadyExistingBlog_SetBlogTypeNavToNull_WorksWhenBlogTypeAddedToContextFirst()
        {
            var context = new BloggingContext();

            // Clean db
            context.Blogs.RemoveRange(context.Blogs);
            context.BlogTypes.RemoveRange(context.BlogTypes);

            // Create Blog
            context.Blogs.Add(new Blog());
            context.SaveChanges();

            // Create BlogType and assign to Blog
            var blogType = new BlogType();
            context.BlogTypes.Add(blogType); //This line was not in the first test version. Adding this fixes the test.
            context.SaveChanges();

            context.Blogs.Single().BlogType = blogType;
            context.SaveChanges();

            Assert.AreEqual(context.Blogs.Single().BlogTypeId, context.BlogTypes.Single().BlogTypeId);

            // Set BlogType to NULL
            var blog = context.Blogs.Single();
            blog.BlogType = null;
            context.SaveChanges();

            // Assert
            blog = context.Blogs.Single();

            Assert.AreEqual(null, blog.BlogType);
            Assert.AreEqual(null, blog.BlogTypeId);
        }

```

**Comment by ajcvickers** [comment] 2020-01-13 22:19
Duplicate of #19137

@DanielHillebrandSWMS I verified that the tests pass with the current daily builds.

**Closed** 2022-10-16 18:05 UTC
Labels: customer-reported
