### ISSUE TITLE
Add sample to API docs for Find

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#12906] opened 2018-08-06 19:41 UTC
Moved from https://github.com/aspnet/EntityFramework.Docs/issues/855 posted by @samaune

**Comment by antonioortizpola** [comment] 2018-08-06 22:07
Voting to close this issue. I do not see the docs as

> too many line with meaning less

First, I am guessing that it should be "too many meaningless lines" or maybe "too many lines with no meaning", but correct me if I am wrong, I am not a native speaker so I could be misunderstanding something.

On the other hand i am not so sure that the problem is the docs, as I see it could be that you need to practice your English more.
I mean, the find function is really easy to follow, you put a Type as Entity an object as ID (maybe some objects if it is a complex PK) and then the method return the entity if finds it or null if not, in this case I do not see how an example could be more clear.

Something like

```
...
class Blog {
    int Id { get; set; }
    string Name { get; set; }
}
...
var id = 1;
var entity = context.Find(Blog, 1);
if(blog == null) {
    //entity not found
}
```

I do not see hoe this could be more clarifying than the actual explanation, even the text also clarifies the usage of the EF cache if the entity is present, something that is very hard to explain with a simple code fragment example.

**Comment by ajcvickers** [comment] 2019-04-22 17:39
Discussed in triage and agreed that there isn't an example usage here that we could put in the API docs that would really help.

**Closed** 2022-10-16 13:23 UTC
Labels: closed-out-of-scope, area-docs, customer-reported
