### ISSUE TITLE
EFCore Set null one property of entity on preview 9 

### ISSUE THREAD

**Issue by Maci94** [dotnet/efcore#17769] opened 2019-09-11 09:57 UTC
I need to save a entity that implements baseEntity 

If i modify IdStatus, efcore Update it correctly, but if idStatus value does not change on other props updating => for some reason efcore set it to null 

idStatus = 20 => try to update to 12 => success 

idStatus = 12 => try to update description => idStatus = null, desc ok 

i'm on

 - .net core 3.0 preview 9

 - efcore 3.0 preview 9

 - database first model creating

 - i use baseManager with iBaseEntity as common crud manager (IBaseEntity has id, DateMod ,UserMod

 - TTableEntity implements IBaseEntity interface

 - error seems occur only on IdStatus (nullable smallint, short?), but it works fine with other "nullable smallint, short?" prop

NOTES:
- updated obj does not have tracking so i need to take an istance of same obj then copy props to it => then save 
- before 'SaveChanges()' idstatus is still 20

**Some CODE for You**
**- Update Method (base manager<TTableEntity> where TTableEntity:class)**
```C#
    public void Update(TTableEntity updated, int userid)
		{
			toSave = GetById(updated.Idnrr);

			PropertyCopierExtention<TTableEntity, TTableEntity>.Copy(updated, toSave);
                        //tosave.idstatus == 20 ! 
			toSave.DateMod = DateTime.Now;
			toSave.UserMod = (short)userid;

			_dbContext.Update(toSave);
			_dbcontext.SaveChanges();//after save => idstatus == null
		}
	public interface ISimpleEntity
	{
		int Idnrr { get; set; }
	}
	*public interface IBaseEntity : ISimpleEntity
	{
		short? UserIns { get; set; }
		DateTime? DateIns { get; set; }
		short? UserMod { get; set; }
		DateTime? DateMod { get; set; }
	}
    public partial class Tbl : IBaseEntity { }//i have to do this in other file
    public partial class Tbl
    {
        
        *public int Idnrr { get; set; }
        public string Description { get; set; }
        public DateTime? startDate { get; set; }
        public DateTime? endDate { get; set; }
        public short? IdStatus { get; set; }
        public byte? id2{ get; set; }
        public short? IdRequester { get; set; }
        *public short? UserIns { get; set; }
        *public DateTime? DateIns { get; set; }
        *public short? UserMod { get; set; }
        *public DateTime? DateMod { get; set; }
        //other 140 public props
    }
```
**- PropertyCopier code **
 ```C#    
    
```C# 
public static void Copy(TSource source, TTarget target)
		{
			var sourceProperties = source.GetType().GetProperties();
			var targetProperties = target.GetType().GetProperties();

			foreach (var sourceProperty in sourceProperties)
			{
				var targetProperty = targetProperties.SingleOrDefault(x =>
					sourceProperty.Name.ToLower() == x.Name.ToLower() && sourceProperty.PropertyType == x.PropertyType);
				if (targetProperty == null)
					continue;
				var value = sourceProperty.GetValue(source);
				targetProperty.SetValue(target, value);
			}
		}`

    

```

EDIT: 
the problem appear if i run the test with PropertyCopierExtention<TTableEntity, TTableEntity>.Copy()
instead of run the test without it and set idStatus manually (toSave.idstatus = update.idstatus )

if i use "propCopier" and i do not modify idStatus => saveChanges set it to nulla on saving

**Comment by AndriySvyryd** [comment] 2019-09-11 17:57
@Maci94 Can you provide a small runnable project that shows this behavior?

**Comment by Maci94** [comment] 2019-09-13 13:13
@AndrewBoklashko i've added more examples , i hope you can help me 
i've just updated .net core 3.0 to preview 9 and ef Core too
i didn't know what to do

**Comment by AndrewBoklashko** [comment] 2019-09-13 15:12
@AndriySvyryd

**Comment by AndriySvyryd** [comment] 2019-09-13 19:33
@Maci94 I cannot reproduce this. Please create a GitHub repo with a __runnable__ project.

**Comment by Maci94** [comment] 2019-09-16 07:25
i did more test on it and i found the snippets causes problem 
View edit Post

**Comment by Maci94** [comment] 2019-09-16 07:36
> @AndriySvyryd

uhm , sorry

**Comment by smitpatel** [comment] 2019-09-26 19:43
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-10-07 15:50
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:41 UTC
Labels: closed-could-not-reproduce, customer-reported
