### ISSUE TITLE
Loading entity from DB does not properly load owned entities (In SQL Server Provider) 

### ISSUE THREAD

**Issue by J-Yen** [dotnet/efcore#24165] opened 2021-02-16 13:07 UTC
**Description**
When loading an entity from the DB, some owned dependent types are not fetched correctly using the SQL Server Provider. It happens when there is an owned dependent that itself references one or more owned dependents, but has no other primitive properties with a value.

**Expected behavior**
Owned types should always be fetched when one or more nested properties have a value.

**Code to reproduce**
```C#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace OwnedDependentNotIncludedInFetch
{
    class Program
    {
        static void Main(string[] args)
        {
            var aggregateRoot = new AnAggregateRoot
            {
                Id = Guid.NewGuid().ToString(),
                AProperty = "My aggregate root",
                OwnedDependent1 = new OwnedDependent1
                {
                    MyProperty = null, // When this is null the nested owned dependent is not included in fetch
                    OwnedDependent2 = new OwnedDependent2
                    {
                        MyProperty = "Nested owned dependent"
                    }
                }
            };

            using (var dbContext = new ExampleContext())
            {
                dbContext.Database.EnsureCreated();
                dbContext.AnAggregateRoots.Add(aggregateRoot);
                dbContext.SaveChanges();
            }

            using (var dbContext = new ExampleContext())
            {
                var fetchedAggregateRoot = dbContext.AnAggregateRoots
                    .Include(x => x.OwnedDependent1)
                    .SingleOrDefault(x => x.Id == aggregateRoot.Id);
                Console.WriteLine(JsonConvert.SerializeObject(fetchedAggregateRoot));
            }

            Console.ReadLine();
        }

        public class ExampleContext : DbContext
        {
            public DbSet<AnAggregateRoot> AnAggregateRoots { get; set; }
            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
                => optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=TestDb;Trusted_Connection=True;MultipleActiveResultSets=true");
            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                base.OnModelCreating(modelBuilder);
                modelBuilder.Entity<AnAggregateRoot>()
                    .HasKey(x => x.Id);
                modelBuilder.Entity<AnAggregateRoot>()
                    .Property(x => x.Id).ValueGeneratedNever();
                modelBuilder.Entity<AnAggregateRoot>()
                    .OwnsOne(x => x.OwnedDependent1, x => x.OwnsOne(y => y.OwnedDependent2));
            }
        }

        public class AnAggregateRoot
        {
            public string Id { get; set; }
            public string AProperty { get; set; }
            public OwnedDependent1 OwnedDependent1 { get; set; }
        }
        
        public class OwnedDependent1
        {
            public string MyProperty { get; set; }
            public OwnedDependent2 OwnedDependent2 { get; set; }
        }
        
        public class OwnedDependent2
        {
            public string MyProperty { get; set; }
        }
    }
}
```
Console output:
```json
{
    "Id": "960c1a74-3bd7-4a42-a702-7c973c06fb19",
    "AProperty": "My aggregate root",
    "OwnedDependent1": null
}
```

**Provider and version information**
EF Core version:
EF Core version: 5.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 1909
IDE: Visual Studio 2019 16.7.6

This sample is working in EF Core 3.1.12 so it's a regression bug.

**Comment by ajcvickers** [comment] 2021-02-16 17:47
@smitpatel to de-dupe

**Comment by smitpatel** [comment] 2021-02-16 18:46
Duplicate of #23564

**Closed** 2022-10-16 19:23 UTC
Labels: customer-reported
