### ISSUE TITLE
An expression of non-boolean type specified in a context where a condition is expected

### ISSUE THREAD

**Issue by liddled** [dotnet/efcore#4964] opened 2016-04-02 10:08 UTC
SQL error when querying nested collection.

```
var accountId = 1;
var categoryIds = new List<int> { 1, 2, 3 };

var entities = _dbContext.Transactions
    .Where(x => x.AccountId == accountId)
    .Where(x => x.Categories.Any(y => categoryIds.Contains(y.Id)));
    .ToList();

```

Generated SQL produces error "An expression of non-boolean type specified in a context where a condition is expected".

I've added a comment where the statement should include '= 1' which fixes the problem.

```
SELECT *
FROM [Transaction] AS [x]
INNER JOIN [Account] AS [a] ON [x].[account_id] = [a].[id]
WHERE [x].[account_id] = 1 AND (
    SELECT CASE
        WHEN EXISTS (
            SELECT 1
            FROM [category] AS [y]
            WHERE [y].[id] IN (1,2,3) AND ([x].[id] = [y].[transaction_id]))
            THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
        END
    ) -- if add '= 1' here then fixes problem
      ORDER BY [x].[id]
```

**Comment by smitpatel** [comment] 2016-04-02 12:45
dupe of #4877

**Closed** 2022-10-16 09:35 UTC
