### ISSUE TITLE
[Suggestion] When a table names exists in more than one schema, dbcontext scaffold should use namespace as discriminator

### ISSUE THREAD

**Issue by pranavkm** [dotnet/efcore#5836] opened 2016-06-22 18:50 UTC
Consider tables `dbo.Person` and `test.Person`. When I scaffold these tables, the scaffolder picks (seemingly in no specific order) types `Person` and `Person1`. Instead, it could use the namespace to discriminate types in this case.

**Comment by rowanmiller** [comment] 2016-06-22 19:27
Duplicate of https://github.com/aspnet/EntityFramework/issues/3988

**Closed** 2022-10-16 09:46 UTC
