### ISSUE TITLE
Index-included properties are treated as columns, not properties

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#19602] opened 2020-01-15 20:16 UTC
First raised in https://github.com/npgsql/efcore.pg/issues/1201 for Npgsql, but looks to be the same bug for the SQL Server provider: the included properties annotation contains properties names, but SqlServerMigrationsSqlGenerator renders them as column names directly. This fails if the column name differs from the property name.

When fixing this, add a migration test in #19039, and add one to Npgsql too.

**Comment by roji** [comment] 2020-01-15 20:17
@bricelam any idea if we have this bug elsewhere in migrations?

**Comment by ajcvickers** [comment] 2020-01-17 18:54
@roji to check if this is fixed on master.

**Comment by bricelam** [comment] 2020-01-17 23:56
Duplicate of https://github.com/dotnet/efcore/issues/14087

**Comment by roji** [comment] 2020-01-23 15:22
Confirmed, this has already been fixed in SQL Server but Npgsql wasn't updated.

**Closed** 2022-10-16 18:06 UTC
