### ISSUE TITLE
Scaffolding - invalid fluent config for SQL Server index .IncludeProperties()

### ISSUE THREAD

**Issue by ascott18** [dotnet/efcore#22248] opened 2020-08-26 17:37 UTC
The following model was scaffolded (excerpt of a specific problematic table below) with `--data-annotations`, although I don't think `--data-annotations` is affecting anything here. The model throws validation errors when attempting to use it due to the underlying column name being scaffolded for `.IncludeProperties()` index fluent configuration instead of the C# property name (which seems to be what is expected there - when I switched to the C# property name, it works correctly).

``` C#
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace EfBug
{
    class Program
    {
        static void Main(string[] args)
        {
            new Context().DailyLogs.First();
        }
    }

    public class Context : DbContext 
    {
        public DbSet<DailyLog> DailyLogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) 
        {
            optionsBuilder.UseSqlServer("Server=localhost;Database=Test");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder) 
        {
            modelBuilder.Entity<DailyLog>(entity =>
            {
                entity.HasKey(e => new { e.Id, e.BusinessDate, e.TransactionKey });

                entity.HasIndex(e => e.Uin, "IX_DAILY_LOG_2")
                    .IncludeProperties(new[] { "BUSINESS_DATE", "ID", "TRANSACTION_KEY" });

                entity.HasIndex(e => e.Uin, "IX_DAILY_LOG_3")
                    .IncludeProperties(new[] { "BUSINESS_DATE", "TRANSACTION_KEY" });
            });
        }
    }

    [Table("DAILY_LOG")]
    [Index(nameof(BusinessDate), Name = "IX_DAILY_LOG")]
    public partial class DailyLog
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Key]
        [Column("BUSINESS_DATE", TypeName = "datetime")]
        public DateTime BusinessDate { get; set; }
        [Key]
        [Column("TRANSACTION_KEY", TypeName = "numeric(18, 0)")]
        public decimal TransactionKey { get; set; }
        [Column("UIN", TypeName = "numeric(18, 0)")]
        public decimal Uin { get; set; }

        public string Description { get; set; }

        // Other irrelevant properties...
    }
}
```

Upon `dotnet run`ning the application:

```
Unhandled exception. System.InvalidOperationException: Include property 'DailyLog.BUSINESS_DATE' not found
   at Microsoft.EntityFrameworkCore.SqlServer.Internal.SqlServerModelValidator.ValidateIndexIncludeProperties(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValidatingConvention.ProcessModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)  
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)  
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)
   at EfBug.Program.Main(String[] args) in C:\src\EfBug\Program.cs:line 13
```

### Further technical details

EF Core version: 5.0.0-rc.1.20426.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: netcoreapp3.1
Operating system: Win10
IDE: VS 2019 16.6.5

**Comment by ascott18** [comment] 2020-08-26 17:46
Seems to have been introduced with https://github.com/dotnet/efcore/pull/22148, probably a duplicate of https://github.com/dotnet/efcore/issues/22150 ?

**Comment by ajcvickers** [comment] 2020-08-28 19:34
@ascott18 Closing as duplicate of #22150. Please up-vote that issue.

**Closed** 2022-10-16 18:38 UTC
Labels: customer-reported
