### ISSUE TITLE
Entity mapped to Table and View with computed columns

### ISSUE THREAD

**Issue by phillipbritain** [dotnet/efcore#24692] opened 2021-04-19 22:29 UTC
With EF Core 5 we are now able to map entities to both a Table and a View. If the View contains all of the columns from the Table, but also additional computed columns, can we configure the entity and mapping to work appropriately? For example, if I update an entity, EF updates the Table, but I need the computed columns from the View to be re-evaluated after the Table update. As it stands right now, EF tries to re-evaluate the computed fields from the Table which fails since those columns don't exist. If EF is supposed to be pulling from the View for every read, why is it reading from the Table in this case?

Also, is it possible to add these additional columns from the View directly to the C# entity and have EF migrations behave appropriately for the View columns? As it stands right now, if I leave the View columns mapped, EF migrations will attempt to create those columns on the Table and not the View.

Entity:

```
public class Blog {

    public int Id {get;set;}

    public string Name {get;set;}

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public string Status {get; private set}

}
```

SQL Table:

```
Table Blogs {

    Id,

    Name

}
```

SQL View:

```
View BlogsView {

    SELECT * FROM Blogs,

    <INSERT COMPLEX QUERY HERE> AS Status

}
```

EF Core Map:

```
protected override void OnModelCreating(ModelBuilder modelBuilder) {

    modelBuilder.Entity<Blog>().ToTable("Blogs").ToView("BlogsView");

}
```

EF Core version: 5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by AndriySvyryd** [comment] 2021-04-23 05:57
Currently all properties must be mapped to both table and view columns. https://github.com/dotnet/efcore/issues/14121 would allow to exclude properties.

**Comment by ajcvickers** [comment] 2021-04-23 21:21
Note from triage: closing as a duplicate of #14121.

**Closed** 2022-10-16 19:31 UTC
Labels: closed-duplicate, customer-reported
