### ISSUE TITLE
Asp Net Core / Postgres / Idle Connections

### ISSUE THREAD

**Issue by groege** [dotnet/efcore#9992] opened 2017-10-06 11:27 UTC
When using Asp Net Core I have 13 **idle** database connections (three of them might be from Hangfire? I'm using "using" in this case so i hope those are not of those 13).
The issue is that even when pooling is not enabled, those connections stay idle.
Is there a way to disallow idle connections and close them immediately if not used?
The thing is we're using PostgreSQL and it has a very low connection limit (especially running the server on Windows) and multiple instances of our app (for each customer a separate ASP NET CORE instance).
Which means we run out of max connections.

### Further technical details
EF Core version: 2.0
Database Provider: Npgsql
Operating system: Windows Server 2012 R2
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment] 2017-10-06 16:24
@groege EF is not intentionally doing anything in this area. EF relies on opening and closing connections on the underlying ADO.NET provider. So this means there could be:
* A bug in EF or the Npgsql EF proivder that is causing connections to not be closed/disposed
* A bug in the underlying Npgsql ADO.NET provider
* An intentional behavior at the ADO.NET layer

In order to help us narrow it down, could you:
* See if this repros with a simple application that doesn't use EF?
  * If so, the bug should probably be moved to a different tracker
  * If not, then try to post a repro here so we can investigate more

/cc @roji (Npgsql)

**Comment by ajcvickers** [comment] 2017-10-13 18:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by roji** [comment] 2017-10-29 19:07
Sorry for not writing earlier.

For the Npgsql angle, if you're specifying `Pooling=false` in your connection string than you're using physical connections - close them (by disposing your DbContext) should physically close the connection.

If you think you've encountered an issue, please post a repro to https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL.

**Closed** 2022-10-16 11:53 UTC
Labels: closed-could-not-reproduce
