### ISSUE TITLE
Error when connect database transient failure in Visual Studio 2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#30546] opened 2023-03-22 09:57 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-when-connect-database-transient-fa/10297699)._

---
[severity:I'm unable to use this version]
I am using VS2022 and when I am trying to run any Linq query agaisnt the NPGSql database and I receive the next error:

`An exception has been raised that is likely due to a transient failure`

I tried to change my UnitOfWork code from:

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseNpgsql(ApplicationSettings.Database.ConnectionString, options =>
                {
                    options. CommandTimeout(ApplicationSettings.Database.CommandTimeout);
                    options. SetPostgresVersion(Version.Parse(ApplicationSettings.Database.Version));
                });
        }
```

To:

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseNpgsql(ApplicationSettings.Database.ConnectionString, options =>
                {
                    options. CommandTimeout(ApplicationSettings.Database.CommandTimeout);
                    options. SetPostgresVersion(Version.Parse(ApplicationSettings.Database.Version));
                    options. EnableRetryOnFailure(5, TimeSpan.FromSeconds(10), null);
                });
            base. OnConfiguring(optionsBuilder);
        }
```

In this case, I received the next error:

```
The maximum number of retries (5) was exceeded while executing database operations with 'NpgsqlRetryingExecutionStrategy

**Trace**
```

```
System.InvalidOperationException
  HResult=0x80131509
  Message=An exception has been raised that is likely due to a transient failure.
  Source=Npgsql.EntityFrameworkCore.PostgreSQL
  StackTrace:
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at UKIAwardsShared.DataLayer.Repository`1.Get(Expression`1 predicate) in C:\Projects\UKI\UKIAwards\. UKIAwardsShared\UKIAwardsShared\DataLayer\Repository.cs:line 35
   at UKIAwardsFaqs.Services.FaqsService.FaqsService.HasPermission(String enterpriseId) in C:\Projects\UKI\UKIAwards\UKIAwardsFaqs\UKIAwardsFaqs\Services\FaqsService\FaqsService.cs:line 151
   at UKIAwardsFaqs.Services.FaqsService.FaqsService.Get(String countryCode, String enterpriseId, Int32 id) in C:\Projects\UKI\UKIAwards\UKIAwardsFaqs\UKIAwardsFaqs\Services\FaqsService\FaqsService.cs:line 45
   at UKIAwardsFaqs.Controllers.DataController.Get(Int32 id) in C:\Projects\UKI\UKIAwards\UKIAwardsFaqs\UKIAwardsFaqs\Controllers\DataController.cs:line 41
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
NpgsqlException: Exception while connecting

Inner Exception 2:
TimeoutException: Timeout during connection attempt
```

**Details**

`Internal error in the expression evaluator.`

---
#### Feedback Bot on 3/3/2023, 06:09 AM: 

(private comment, text removed)
#### Elias Merabet Ponton on 3/7/2023, 07:59 AM: 

(private comment, text removed)
#### Elias Merabet Ponton on 3/9/2023, 08:00 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2023-04-05 17:19
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-04-05 17:19 UTC
Labels: customer-reported
