### ISSUE TITLE
Switch to use reflection nullability API

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#16062] opened 2019-06-13 08:07 UTC
Once https://github.com/dotnet/corefx/issues/38087 is done, we should switch to that instead of interpreting [NullableAttribute] ourselves (our method is probably broken by now).

**Comment by ajcvickers** [comment] 2019-06-13 21:50
@roji Isn't this a duplicate of #15830?

**Comment by roji** [comment] 2019-06-13 22:54
It most certainly is!

**Closed** 2022-10-16 14:25 UTC
