### ISSUE TITLE
UseLazyLoadingProxies enforces every entity to use lazy loading

### ISSUE THREAD

**Issue by bugproof** [dotnet/efcore#11907] opened 2018-05-04 14:03 UTC
I'm just testing lazy loading feature in EF Core 2.1

https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading

It seems like using it enforces marking all navigation properties with `virtual`. And if I don't do so I get this exception:

> UseLazyLoadingProxies requires all entity types to be public, unsealed, have virtual navigation properties, and have a public or protected constructor.

Is this by design? Or is it better if I use "Lazy-loading without proxies" if I want to have some entities loaded differently.

The documentation doesn't mention this:

> EF Core will then enable lazy-loading for any navigation property that can be overridden--that is, it must be virtual and on a class that can be inherited from

But it seems like all navigation properties must be virtual whether I want to use it or not.

**Comment by ralmsdeveloper** [comment] 2018-05-04 14:15
This is by design enforcing all properties to be of the virtual type when LazyLoad is enabled.

**Comment by ajcvickers** [comment] 2018-05-04 16:17
Duplicate of #10787

**Comment by dfcowan** [comment] 2021-08-03 15:13
It would be helpful for the documentation to mention this. As it's written today it implies that only virtual properties will be overridden. 

> EF Core will then enable lazy loading for any navigation property that can be overridden--that is, it must be virtual and on a class that can be inherited from.

 from https://docs.microsoft.com/en-us/ef/core/querying/related-data/lazy

**Closed** 2022-10-16 12:23 UTC
Labels: closed-duplicate, customer-reported
