### ISSUE TITLE
Being able to guarantee certain entity types are readonly (not tracked) at the dbcontext level, during Model configuration.

### ISSUE THREAD

**Issue by Poltuu** [dotnet/efcore#35046] opened 2024-11-05 16:15 UTC
### What problem are you trying to solve? 

Some entities in my dbContext should never be modified.

### Describe the solution you'd like 

Being able to define a tracking strategy  at the entity level to declare them readonly (or not tracked) would be appreciated.
This should take priority on `.AsTracking()` usage on `IQueryable`.

### Personal Take
Adding a `NoTracking`  enum member on the `ChangeTrackingStrategy` seems to be the obvious API design decision IMO.

Setup would then look like this:
 `builder.HasChangeTrackingStrategy(ChangeTrackingStrategy.NoTracking);`.

**Comment by AndriySvyryd** [comment] 2024-11-07 22:16
Duplicate of https://github.com/dotnet/efcore/issues/7586

**Closed by AndriySvyryd** 2024-11-07 22:16 UTC
Labels: customer-reported
