### ISSUE TITLE
EF Core Using multiple properties with backing fields with owned type causes exception on SaveChanges()

### ISSUE THREAD

**Issue by SamVanheer** [dotnet/efcore#19446] opened 2019-12-31 19:25 UTC
When using multiple properties with backing fields with an owned type with the InMemory database, inserting an entity into the database and calling `SaveChanges()` causes an exception.

This does not happen if there is only one property with backing field, or if the second property uses an auto generated backing field.

I found issue #9044 which indicates that owned types cannot be used with backing fields, but i want EF to work with the property only. The backing field is intended to be used with `INotifyPropertyChanged` to raise the `PropertyChanged` event.

I don't know if using a backing field manually can result in EF trying to use the backing field instead of the property, but based on [the code](https://github.com/aspnet/EntityFrameworkCore/blob/2c341ee6cb9721fdaedbe3cb3b302c8b7a3fe008/src/EFCore/Metadata/Conventions/BackingFieldConvention.cs#L136-L149) used by EF to locate backing fields it should be behaving consistently regardless of whether i'm using an auto property or a property with a manually defined backing field.

While debugging i noticed that the InMemory database internally creates a table for Vector3, which seems odd to me because i assume the `Owned` attribute is supposed to prevent creation of a table, and instead store the data in the tables of any owner types.

The list of pending changes contains 2 vectors with the same foreign key to the `Axis` object, which seems to be the key that causes the exception.

### Steps to reproduce

This is the code that causes the problem:
```C#
[Owned]
public class Vector3
{
    public float X { get; set; }
    public float Y { get; set; }
    public float Z { get; set; }
}

public sealed class Axis
{
    public Guid Id { get; set; }

    private Vector3 _position = new Vector3();

    public Vector3 Position
    {
        get => _position;
        set => _position = value;
    }

    private Vector3 _range = new Vector3();

    public Vector3 Range
    {
        get => _range;
        set => _range = value;
    }
}

public class AppContext : DbContext
{
    public DbSet<Axis> Axes { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        var root = new InMemoryDatabaseRoot();

        optionsBuilder.UseInMemoryDatabase("Test", root);
    }
}

using var context = new AppContext();

var axis = new Axis();

context.Axes.Add(axis);

context.SaveChanges();
```

A minimal program reproducing the issue can be found here: https://github.com/SamVanheer/EntityFrameworkOwnedBug

Exception:
```
System.ArgumentException: 'An item with the same key has already been added. Key: edb9c61d-6550-4837-ae2f-16a3fe106d39'
```

Stack trace:
```
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.Create(IUpdateEntry entry)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryStore.ExecuteTransaction(IList`1 entries, IDiagnosticsLogger`1 updateLogger)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at EntityFrameworkOwnedBug.Program.Main(String[] args) in C:\Users\Sam\Documents\GitHub\EntityFrameworkOwnedBug\EntityFrameworkOwnedBug\Program.cs:line 13
```

### Further technical details

EF Core version: 3.1.0
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: Net Core 3.1
Operating system: Windows 8.1
IDE: Visual Studio 2019 16.4

**Comment by ajcvickers** [comment] 2020-01-02 19:20
@SamVanheer Looks like this is a duplicate of #18007. See comment here: https://github.com/aspnet/EntityFrameworkCore/issues/18947#issuecomment-555739809

/cc @AndriySvyryd Is #18007 sufficient for tracking both owned and non-owned cases?

**Comment by SamVanheer** [comment] 2020-01-02 19:42
Looks like #18007 is indeed the same issue.

So i should just initialize the properties when i create a new entity on the application side then?

**Comment by AndriySvyryd** [comment] 2020-01-02 19:51
There shouldn't be anything special about it being owned.

@SamVanheer As a workaround you can have a nullable field wrapped in non-nullable property.

**Comment by SamVanheer** [comment] 2020-01-02 21:28
I see, that did the trick. Here's the code for anyone who wants to know how it can be done:
```
private Vector3 _position;

public Vector3 Position
{
    get => _position ??= new Vector3();
    set => _position = value;
}

private Vector3 _range;

public Vector3 Range
{
    get => _range ??= new Vector3();
    set => _range = value;
}
```

The implementation in my code raises `PropertyChanged` as well but it's otherwise identical.

**Closed** 2022-10-16 18:03 UTC
Labels: customer-reported
