### ISSUE TITLE
How to resolve DbContext in package-by-feature or other "vertical slice" architectures?

### ISSUE THREAD

**Issue by douglasg14b** [dotnet/efcore#26447] opened 2021-10-24 01:37 UTC
## Preface

Similar to `feature-folder` architecture, `package-by-feature` vertically slices the codebase to achieve much better cohesion, However, EF Core seems to get right in the way of that since a `DbSet` can only be of a concrete type, and we can't really "register" our entities in a non-coupled fashion.

This is one (of many) long-standing architectures (This one articled/ written on circa ~2005 by "Uncle Bob") that are relatively easy to use with Asp.Net Core, but sibling projects seems to produce difficulties.

Can EF Core work in a vertically sliced application where the slices are assemblies without forcing the application to break from it's architecture?

### Include your code

Say you have this structure, each feature is a different project/assembly.:

```
App.Feature.Feature1
  -- Feature1.cs
  -- Feature1Service.cs
  -- Feature1Controller.cs
App.Feature.Feature2
  -- Feature2.cs
  -- Feature2Service.cs
  -- Feature2Controller.cs
App.Feature.Feature3
  -- Feature3.cs
  -- Feature3Service.cs
  -- Feature3Controller.cs
... etc
```

Each feature entity is a DDD styled aggregate, so it is self-contained and defends its own invariants, as opposed to it simply being a POCO. 

Each feature service needs a `DbContext` and may want access to load entities from another feature. However, there is no way to define a "shared" DbContext without creating an assembly that is a circular-reference. An outside assembly would need to reference each feature assembly to use the `Feature` in each of the context's the DbSet`, and each assembly would then need to reference that assembly to use that `DbContext`

This could be solved in a few ways:

* Use interfaces for the DbSet models of each of the feature's entities, and configure the concrete type with Ef Core within each of the assemblies
   * You can now have a shared assembly that defines all the interfaces, and each of the other feature assemblies need not even hold references to each other.
   * Each assembly is responsible for configuring itself with EF Core
   * This is Dependency Inversion
* Move all the features into a single project and separate them by folder.
   * This is unworkable since we are sacrificing nearly all the advantages of having separate assemblies
* Move all the feature entities into an assembly
   * This is also unworkable, this would be a kludge that sacrifices the advantages of having the features in separate assemblies in the first place
  
**I imagine I'm missing some feature/aspect of EF Core that enables this. How can EF Core work with this sort of architecture?**

**Comment by ajcvickers** [comment] 2021-11-03 13:07
@douglasg14b I think it would help us understand what it is you are looking for if we could see something a bit more concrete. Two possibilities for this are:

* A skeleton set of projects and code that assume EF Core is implemented/factored the way you want it so that we can see exactly what the D.I. boundaries looks like, and understand how the services interact.
* A pointer to a real application implemented using this kind of architecture, regardless of whether that application uses EF Core or not.

Would it be possible to provide one or both of these things?

**Comment by douglasg14b** [comment] 2021-11-07 22:42
I can do that!

I'm kinda hammered right now, so it will take a bit of time to circle back around to this. 

<hr>

As for the 2nd request though, that gets difficult as I only know of proprietary ones (From current and past employers and client). The best I could suggest is reading material, a quick google search will reveal plenty of discussions on the topic.

**Comment by roji** [comment] 2021-11-08 09:37
@douglasg14b sure thing, and thanks for your time on this. FWIW my [comment above](https://github.com/dotnet/efcore/issues/26447#issuecomment-950310103) wasn't meant to cast doubt or to ask you to justify anything - just curiosity about the pattern and a desire to know more.

In any case, a simple skeleton solution would go a long way to help us understand exactly what's being requested and how we can help address it from the EF Core side.

**Comment by Ciantic** [comment] 2021-11-29 20:55
> we can't really "register" our entities in a non-coupled fashion

I think I know what you mean, but I found solution that works for sharing entities between packages, but still having just one DbContext in the main application.

Note that DbSet property is *not required* for querying anymore, you can just add the entities with Fluent API:

In feature package:
```c#
public class Thing
{
    public Guid Id { get; set; }
    public string Name { get; set; } = "";
}

public class Other
{
    public Guid Id { get; set; }
    public string Name { get; set; } = "";
}

public static class ModelBuilderExtension {
    
    public static void AddMyStuff(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Thing>(); // Notice that DbSet is not required!
        modelBuilder.Entity<Other>();
    }
}
```

In main app package:

```C#
public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
    : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.AddMyStuff(); // <-- This registers the entities
        base.OnModelCreating(modelBuilder);
    }
}
```

You can even make Repositories in the feature package if you make a decision e.g. to register AppDbContext as a DbContext service.

Notice that you don't need the DbSet to make queries, adding or changing the entities:

```c#
dbContext.Add(new Thing() {
	Name = "Foo"
});
dbContext.SaveChanges();
dbContext.Set<Thing>().Where(p => p.Input == "Foo").First();
```

**Comment by ajcvickers** [comment] 2022-01-11 12:15
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:11 UTC
Labels: closed-no-further-action, customer-reported
