### ISSUE TITLE
Bad scaffolding for char(n) columns in SQL Server - length is not scaffolded.

### ISSUE THREAD

**Issue by ascott18** [dotnet/efcore#22121] opened 2020-08-18 20:41 UTC
OnModelCreating and/or annotations are not scaffolded correctly for `char(n)` columns for SQL Server, leading to model validation errors:

```
Message: 
    System.ArgumentException : Data type 'char' for property 'Code1' is not supported in this form. Either specify the length explicitly in the type name, for example as 'char(16)', or remove the data type and use APIs such as HasMaxLength to allow EF choose the data type.
  Stack Trace: 
    SqlServerTypeMappingSource.ValidateMapping(CoreTypeMapping mapping, IProperty property)
    RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo& mappingInfo, IReadOnlyList`1 principals)
    RelationalTypeMappingSource.FindMapping(IProperty property)
    TypeMappingConvention.ProcessModelFinalizing(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
    ImmediateConventionScope.OnModelFinalizing(IConventionModelBuilder modelBuilder)
    ConventionDispatcher.OnModelFinalizing(IConventionModelBuilder modelBuilder)
    Model.FinalizeModel()
    ModelBuilder.FinalizeModel()
    ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
    ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
    DbContextServices.CreateModel()
    DbContextServices.get_Model()
    <>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
    CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
    CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
    CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
    CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
    CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
    CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
    CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
    CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
    CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
    CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
    CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
    <>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
    ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
    ServiceProviderEngineScope.GetService(Type serviceType)
    ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
    ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
    DbContext.get_DbContextDependencies()
    DbContext.get_InternalServiceProvider()
    DbContext.get_DbContextDependencies()
    DbContext.get_Model()
    InternalDbSet`1.get_EntityType()
    InternalDbSet`1.CheckState()
    InternalDbSet`1.get_EntityQueryable()
    IEnumerable<TEntity>.GetEnumerator()
    List`1.ctor(IEnumerable`1 collection)
    Enumerable.ToList[TSource](IEnumerable`1 source)
    UnitTest1.Test1() line 15
    --- End of stack trace from previous location where exception was thrown ---
```

The scaffolded model definition for the property (specifies IsFixedLength, but doesn't specify the actual length): 
``` c#
entity.Property(e => e.Code1)
    .IsUnicode(false)
    .HasColumnName("Code")
    .IsFixedLength(true);
```

### Steps to reproduce

Create a blank SQL Server database with a table with a `char(n)` column. E.g.:

``` sql
CREATE TABLE Codes (
	CodeId [int] NOT NULL,
	Code [char](3) NOT NULL,
	CONSTRAINT [PK_Codes] PRIMARY KEY CLUSTERED (CodeId ASC)
);
```

Then, scaffold it: `dotnet ef dbcontext scaffold "Server=localhost;Database=EfScaffoldBug;Trusted_Connection=True" Microsoft.EntityFrameworkCore.SqlServer --data-annotations`

Then, attempt to use the context:

``` C#
        [Fact]
        public void Test1()
        {
            new EfScaffoldBugContext().Codes.ToList();
        }
```

### Further technical details

EF Core version: 5.0.0-preview.7.20365.15
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: netcoreapp3.1
Operating system: Win10
IDE: VS 2019 16.6.5

**Comment by smitpatel** [comment] 2020-08-18 21:04
Probably duplicate of #21816 
Where data annotations missed scaffolding StringLength and fluent API would assume it did and won't put the length in the model.

**Comment by ascott18** [comment] 2020-08-18 21:13
Looks like it is indeed a dupe of that. Thanks for checking!

**Closed** 2022-10-16 18:37 UTC
Labels: customer-reported
