### ISSUE TITLE
How to detect and ignore BooleanExpressionTranslatingVisitor in Accept method?

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#13364] opened 2018-09-19 06:27 UTC
I want to generate SQL like:
`
WHERE ("r"."COL_VARCHAR_10" STARTING WITH 'ABC')
`

EFCore adds the "=TRUE" and I see SQL:
`
WHERE ("r"."COL_VARCHAR_10" STARTING WITH 'ABC') = TRUE
`

MyExpression class:

```c#
{
 //...
 public override ExpressionType NodeType
 {
  get
  {
   return ExpressionType.Extension;
  }//get
 }//NodeType

 public override bool CanReduce
 {
  get
  {
   return false;
  }//get
 }//CanReduce

 public override Type Type
 {
  get
  {
   return typeof(bool);
  }//get
 }//Type
 //....
};//class
```
I can resolve this problem through adding into MyExpression.Accept the next condition:

```c#
if(visitor.GetType().FullName=="Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator+BooleanExpressionTranslatingVisitor")
  {
   return his;
  }
```

But not sure, that is right decision.

How I may say to EFCore `do not add "=TRUE"` to boolean-expression?

**Comment by dmitry-lipetsk** [comment] 2018-09-19 08:07
I found the point, where EFCore adds the "=TRUE"

```
Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.BooleanExpressionTranslatingVisitor.BuildCompareToExpression(System.Linq.Expressions.Expression expression, bool compareTo)Строка 2104	C#
Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.BooleanExpressionTranslatingVisitor.ConvertToSearchCondition(System.Linq.Expressions.Expression expression)Строка 2110	C#
Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.BooleanExpressionTranslatingVisitor.ApplyConversion(System.Linq.Expressions.Expression expression)Строка 2075	C#
Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.BooleanExpressionTranslatingVisitor.VisitExtension(System.Linq.Expressions.Expression extensionExpression)Строка 2068	C#
System.Linq.Expressions.dll!System.Linq.Expressions.Expression.Accept(System.Linq.Expressions.ExpressionVisitor visitor)Строка 164	C#
EntityFrameworkCore.DataProvider.Lcpi.OleDb.nets2_0.debug.dll!EntityFrameworkCore.DataProvider.Lcpi.OleDb.Dbms.Firebird.Common.Query.Expressions.FB_Common__Expression__String_StartsWith.Accept(System.Linq.Expressions.ExpressionVisitor visitor)Строка 65	C#
```

```c#
            private static Expression BuildCompareToExpression(Expression expression, bool compareTo)
            {
                var equalExpression = Expression.Equal(
                    expression,
                    Expression.Constant(compareTo, expression.Type));

                // Compensate for type change since Expression.Equal always returns expression of boolean type
                return expression.Type == typeof(bool)
                    ? (Expression)equalExpression
                    : Expression.Convert(equalExpression, expression.Type);
            }

```

This method called from:
```c#
            private static Expression ConvertToSearchCondition(Expression expression)
                => IsSearchCondition(expression) // <-------- returns false
                    ? expression
                    : BuildCompareToExpression(expression, compareTo: true);

```

Decision made in:
```c#
            private static bool IsSearchCondition(Expression expression)
            {
                expression = expression.RemoveConvert();

                return !(expression is BinaryExpression)
                    && expression.NodeType != ExpressionType.Not
                    && expression.NodeType != ExpressionType.Extension
                    ? false
                    : expression.IsComparisonOperation()
                       || expression.IsLogicalOperation()
                       || expression.NodeType == ExpressionType.Not
                       || expression is ExistsExpression
                       || expression is InExpression
                       || expression is IsNullExpression
                       || expression is LikeExpression
                       || expression is StringCompareExpression;
            }
```

My offer - need add into EFCore a new special public interface without any method - IsSearchConditionExpression, which will inherited by ExistsExpression, InExpression, IsNullExpression, LikeExpression, StringCompareExpression and by other (my) external Expression classes.

```c#
            private static bool IsSearchCondition(Expression expression)
            {
                expression = expression.RemoveConvert();

                return !(expression is BinaryExpression)
                    && expression.NodeType != ExpressionType.Not
                    && expression.NodeType != ExpressionType.Extension
                    ? false
                    : expression.IsComparisonOperation()
                       || expression.IsLogicalOperation()
                       || expression.NodeType == ExpressionType.Not
                       || expression is IsSearchConditionExpression;
            }
```

-----
Or empty class:
```c#
class SearchConditionExpression:Expression
{
};//class SearchConditionExpression
```

Which will be inherited by ExistsExpression, InExpression, IsNullExpression, LikeExpression, StringCompareExpression and by other (my) external Expression classes.

In this case, IsSearchCondition will be look as:
```c#
            private static bool IsSearchCondition(Expression expression)
            {
                expression = expression.RemoveConvert();

                return !(expression is BinaryExpression)
                    && expression.NodeType != ExpressionType.Not
                    && expression.NodeType != ExpressionType.Extension
                    ? false
                    : expression.IsComparisonOperation()
                       || expression.IsLogicalOperation()
                       || expression.NodeType == ExpressionType.Not
                       || expression is SearchConditionExpression;
            }
```

What do you think about this?

**Comment by ajcvickers** [comment] 2018-09-19 18:55
@smitpatel to find dupe.

**Comment by smitpatel** [comment] 2018-09-19 21:00
Duplicate of #10513

**Comment by smitpatel** [comment] 2018-09-19 21:01
Specifically we discussed in #9143 exactly same thing that providers cannot influence this visitor. There are multiple ways to resolve it out. In 3.0 timeframe we will make it to move in proper place so that providers can opt into behavior of appending "true" and also influence the value/search condition determination of custom expression types.

**Comment by dmitry-lipetsk** [comment] 2018-09-20 04:09
@smitpatel,

The limitations in external code kills me :)

Could you implement (in current master branch) one of my (temporary) decision for this issue?

I can create PR with (Base)SearchConditionExpression class.

When you implement in 3.0 the "true" decision for this problem, I will use it.

**Comment by dmitry-lipetsk** [comment] 2018-09-20 04:51
Simplified and updated code of IsSearchCondition:

```c#
            private static bool IsSearchCondition(Expression expression)
            {
                expression = expression.RemoveConvert();

                //prevention of "FAILSE=TRUE" condition generation
                if(expression is ConstantExpression constantExpression)
                   return constantExpression.Type == typeof(bool);

                if(expression.NodeType == ExpressionType.Not)
                    return true;

                if(expression is SearchConditionExpression)
                    return true;

                if(expression.IsLogicalOperation())
                    return true;

                if(expression.IsComparisonOperation())
                    return true;

                return false;
            }

```

**Comment by dmitry-lipetsk** [comment] 2018-09-29 08:57
@ajcvickers,

I think, need finish my current work with translation and look to finished changes in DefaultQuerySqlGenerator.

Today I changed the DefaultQuerySqlGenerator.BooleanExpressionTranslatingVisitor.ConvertToValue for avoid generation a "CASE"-statement in SQL.

```c#
            private static Expression ConvertToValue(Expression expression)
            {
                if(!IsSearchCondition(expression))
                   return expression;

                if(expression.Type == typeof(bool))
                   return expression;

                var newExpression = Expression.Convert(expression, typeof(bool));

                return newExpression;
/*
                => IsSearchCondition(expression)
                    ? Expression.Condition(
                        expression.Type == typeof(bool)
                            ? expression
                            : Expression.Convert(expression, typeof(bool)),
                        Expression.Constant(true, expression.Type),
                        Expression.Constant(false, expression.Type))
                    : expression;
*/
            }
```

Could I offer to you (EFCore team) a little offer for code style?

Please, do not use complex expression in "return c?r1:r2". Use simple:

```c#
if(c)
 return r1;

return r2;
```
Thanks you.

**Comment by smitpatel** [comment] 2018-10-01 22:58
@dmitry-lipetsk - We don't use such code style (no braces for if conditions). We combine return statements whenever possible.

**Comment by dmitry-lipetsk** [comment] 2019-03-29 10:23
Hello,

Could you look to my proposal for fix this issue and comment it?

If it is completelly incorrect - please offer another solution.

Thanks.

**Comment by dmitry-lipetsk** [comment] 2019-03-29 10:31
Additional info.

I use SearchConditionExpression as base class of my followed expression nodes:
- FB_Common__Sql_ENode__String_Contains
- FB_Common__Sql_ENode__String_EndsWith__through_RIGHT
- FB_Common__Sql_ENode__String_StartsWith

**Comment by smitpatel** [comment] 2019-03-29 16:20
@dmitry-lipetsk - In 3.0 query pipeline, converting to search condition (appending = true) becomes SqlServer provider specific behavior. So other providers who don't have such limitation does not have to deal with it. If FireBird has limitation like that you can follow processing like SqlServer and add a specific visitor to do conversion as needed. Since visitor is provided by providers, it would be straight forward for you to identify condition or not. As of now, we decided not to add extra metadata in SQL tree in relational layer since search condition/value is not restriction in all providers. This gives us shorter SQL for providers where it is not needed.

**Comment by dmitry-lipetsk** [comment] 2019-03-29 17:41
> @dmitry-lipetsk - In 3.0 query pipeline, converting to search condition (appending = true) **becomes SqlServer provider specific behavior**. So other providers who don't have such limitation does not have to deal with it.

If I understand correctly, this will be implemented in the near time.

And I can just delete SearchConditionExpression and the corresponding changes.

This is good news.

Thanks.

**Closed** 2022-10-16 13:31 UTC
Labels: closed-duplicate, customer-reported
