### ISSUE TITLE
Support Call `ToListAsync()` or other async method on None async `IQueryable`

### ISSUE THREAD

**Issue by John0King** [dotnet/efcore#11737] opened 2018-04-19 09:46 UTC
https://github.com/aspnet/EntityFrameworkCore/blob/2d987b669db52095e4754aea86aa04f9d068d417/src/EFCore/EntityFrameworkQueryableExtensions.cs#L2837-L2858

Why not return `Task.FromResult<T>`  when the provider is not `IAsyncQueryProvider` ?

That allow us to call EF-Core's async extension mthod on any `IQueryable<T>` object.

**Comment by tuespetre** [comment] 2018-04-21 18:08
I kind of agree but I am also kind of curious to see framework-defined async enumerables/queryables and their corresponding extension methods land (planned for C# 8.0.)

**Comment by ajcvickers** [comment] 2018-04-23 19:51
Duplicate of #9179

**Closed** 2022-10-16 12:19 UTC
