### ISSUE TITLE
Cosmos driver not creating unique index (on storage emulator)

### ISSUE THREAD

**Issue by Soundman32** [dotnet/efcore#21238] opened 2020-06-12 16:42 UTC
I am trying to create a unique constraint on a Cosmos collection, using the Entity Framework Core Cosmos driver.

This is how I'm configuring the entity
```
public void Configure(EntityTypeBuilder<TenantIdentifier> builder)
{
            builder.ToContainer("TenantIdentifiers");
            builder.HasPartitionKey(k => k.PartitionKey);
            builder.HasIndex(k => k.Identifier).IsUnique();
}
```

I can successfully store 2 documents with the same Identifier field.

The indexing policy on the collection looks like this:
{
    "indexingMode": "consistent",
    "automatic": true,
    "includedPaths": [
        {
            "path": "/*",
            "indexes": [
                {
                    "kind": "Range",
                    "dataType": "Number",
                    "precision": -1
                },
                {
                    "kind": "Range",
                    "dataType": "String",
                    "precision": -1
                }
            ]
        }
    ],
    "excludedPaths": [
        {
            "path": "/\"_etag\"/?"
        }
    ]
}

### Further technical details

EF Core version: 3.1.4
Database provider: Cosmos
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.2

**Comment by AndriySvyryd** [comment] 2020-06-12 22:21
Duplicate of https://github.com/dotnet/efcore/issues/17303

**Closed** 2022-10-16 18:29 UTC
Labels: customer-reported
