### ISSUE TITLE
Redundant warning - The LINQ expression 'Max()' could not be translated and will be evaluated locally.

### ISSUE THREAD

**Issue by Mertsch** [dotnet/efcore#9722] opened 2017-09-07 12:10 UTC
I am running a .Max() query against the DB

```
this.maxAccountId = this.db.Accounts.AsNoTracking()
    .Where(f => f.ScanId == this.scanId)
    .Max(a => a.Id);
```

The log then states
```
Microsoft.EntityFrameworkCore.Query[200500]: Warning: The LINQ expression 'Max()' could not be translated and will be evaluated locally.
Microsoft.EntityFrameworkCore.Database.Command[200101]: Information: Executed DbCommand (3ms) [Parameters=[@__scanId_0='?'], CommandType='Text', CommandTimeout='30']
SELECT MAX([f].[Id])
FROM [Accounts] AS [f]
WHERE [f].[ScanId] = @__scanId_0
```

and I am wondering if `Warning: The LINQ expression 'Max()' could not be translated and will be evaluated locally.` is actually true, since the generated query looks like a proper SQL query

### Further technical details
EF Core version: 2.0.0 (2.0.0-rtm-26452)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: win 10
IDE: VS2017 15.3.3

**Comment by smitpatel** [comment] 2017-09-07 12:12
Duplicate of #9516

**Comment by anpete** [comment] 2017-09-08 16:49
Actually dupe of #9726 - I ended up keeping the newer one because I looked at that first.

**Closed** 2022-10-16 11:48 UTC
Labels: closed-duplicate
