### ISSUE TITLE
c# ef core migration generate programatically 

### ISSUE THREAD

**Issue by mahdiyar021** [dotnet/efcore#33926] opened 2024-06-07 13:21 UTC
there is a help on issue #9339 but it doest work on new dot net ef core 8 class name is different is there any help to find class for generating migration ???

### Include provider and version information
EF Core version:8.6
Target framework: (e.g. .NET 8.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by ajcvickers** [comment] 2024-06-07 14:08
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by mahdiyar021** [comment] 2024-06-08 01:16
try to generate migration and scaffold migration programatically .  i found this peace of code but i think class names in not net 8 

`
   var designTimeServiceCollection = new ServiceCollection()
                    .AddEntityFrameworkDesignTimeServices()
                    .AddSingleton<MigrationsScaffolder>()
                    .AddDbContextDesignTimeServices(db);

                //new SqlServerDesignTimeServices().ConfigureDesignTimeServices(designTimeServiceCollection);
                var provider = db.GetService<IDatabaseProvider>().Name;
                Assembly providerAssembly;
                providerAssembly = Assembly.Load(new AssemblyName(provider));
                var providerServicesAttribute = providerAssembly.GetCustomAttribute<DesignTimeProviderServicesAttribute>();
                var designTimeServicesType = providerAssembly.GetType(
                    providerServicesAttribute.TypeName,
                    throwOnError: true,
                    ignoreCase: false);
                var providerDesignTimeServices = (IDesignTimeServices)Activator.CreateInstance(designTimeServicesType);
                providerDesignTimeServices.ConfigureDesignTimeServices(designTimeServiceCollection);

                var designTimeServices = designTimeServiceCollection.BuildServiceProvider();

                var scaffolder = designTimeServices.GetRequiredService<MigrationsScaffolder>();

                var migration = scaffolder.ScaffoldMigration(
                    migName,
                    contextType.Namespace,
                    MigrationSubNamespace);
`

**Comment by ajcvickers** [comment] 2024-06-08 08:52
@mahdiyar021 When we ask for a repro, what we mean is you need to post a _small_ project containing the code _that we can run_. This code should fail in the way you are seeing. We can then investigate this behavior and either confirm it is a bug, or try to help you in some other way.

**Comment by ajcvickers** [comment] 2024-06-15 14:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-06-15 14:44 UTC
Labels: customer-reported
