### ISSUE TITLE
SQLite default column value overrides the passed value on initial create.

### ISSUE THREAD

**Issue by Allann** [dotnet/efcore#7347] opened 2017-01-04 06:20 UTC
When saving an initial record into a SQLite table, the default column value overrides the passed in value.

[DefaultTest.zip](https://github.com/aspnet/EntityFramework/files/684028/DefaultTest.zip)

### Steps to reproduce
I have attached a small project that demonstrates the issue.  I have left it as close as possible to my implementation just in case it's something I'm doing.

Load the project in VS2015, restore dependencies, build and run the xUnit tests (1 passes and 1 fails).

#### Explanation of test project
In the test `CarrierFacts.Carrier_List_Success` the 3 entities are added to the database, this is actually where the failure emanates from as the 3rd entity (OOL) has the `IsActive` flag set to true.  This can be checked in the `CarrierBuilder.SetEditor` method where you can check that the 3 entities do have their IsActive flags set correctly, then when `SaveChanges` is called on the DbConext, and the context table records are viewed, you can see the `IsActive` flag no longer matches. 

### Further technical details
EF Core version: 1.1.0 (found in project.json or packages.config)
Database Provider: Microsoft.EntityFrameworkCore.Sqlite)
Operating system: Windows 10 (64 bit)
IDE: (e.g. Visual Studio 2015)

**Comment by Allann** [comment] 2017-01-04 21:44
Further information for this:

- If I remove the line   `b.Property(p => p.IsActive).HasDefaultValue(true);`  from the CarrierConfiguration mapping file, the test begins to pass.
- If I update the record after the initial create, the record updates successfully.

**Comment by jcramer** [comment] 2017-01-04 22:17
I am having the exact same issue using v1.1 using SQL express.  It does seem like a bug because when I set the default value to "false" using the fluent API `HasDefaultValue(false);` the implemented value of true is not overwritten by the db's default value.  Do experience this same thing? Or does this overwriting occur regardless of using true or false as the default value?

I found the following stackoverflow issues related to this, but it didn't really solve the problem:
[How to set another value on a boolean with defaut value with Entity Framework Core?](http://stackoverflow.com/questions/38570246/how-to-set-another-value-on-a-boolean-with-defaut-value-with-entity-framework-co)

**Comment by ajcvickers** [comment] 2017-01-04 22:27
Dupe of #7089. Short answer is to use a `Nullable<bool>` property. This lets EF know to use the default value if the property is set to null, otherwise insert the value that has been set.

**Comment by jcramer** [comment] 2017-01-04 22:54
This worked for me. Thanks!

**Comment by Allann** [comment] 2017-01-05 02:17
me too.  thanks

**Comment by Allann** [comment] 2017-01-05 04:22
Actually it doesn't.  "I have included this comment in the duplicate too"

@ajcvickers You are completely correct in that that will "work-around" the issue, however, I don't want the domain object to rely on a particular database mapping to work. I NEED the field to be not nullable as it is not allowed to be null. What you are suggesting is the field is allowed to be null at some stage, as long as it's set before being sent to the database. My viewmodel field is nullable, but that is a particular user/UX scenario and doesn't normally require these fields. But the dto and domain classes both have this set as bool not nullable.

Note: I use code first via a domain class and a separate mapping class. I would need to set the domain object field to nullable, and remember to set the mapping for that field to required. This would have been implied if the field remained non-nullable.

> As an aside this is new in EF core as behaves differently in EF6. This means that many will have to change their code base when moving to EF core.

Much of our legacy code relies on primitive types with database defaults, having to change all these to nullable will be a huge task especially since this is a hidden side-effect and not expected behavior. If I set a value on a field, I expect that value to be inserted into the database and not have it overridden by a default constraint when inserted into the database.

If this is to be the "rule", then I highly recommend putting an exception in the database generation logic that states that ALL fields with defaults NEED to map to nullable properties. Either that, or ignore default values when set against non-nullable properties.

Isn't the answer to this issue simply:
_EF Core uses the default value if the column is not included in the insert statement or is null on a nullable column._

**Comment by ensemblebd** [comment] 2019-10-09 03:40
Occurs in .net 4.6.2 as well. Probably higher.

Not trying to necro, but jesus this is a bad one. 
SQL Default values override passed values of the model. 
That's some crazy shit. 

Only truly viable option is to create the record, then update it afterwards. Since EF6 makes invalid assumptions about how the database is meant to be operated. 

Who in their right mind would make a non-nullable column with a default value (so as to enforce strict model usage with proper values passed), and then entirely ignore INSERT values in favor of whatever default the sql db has. That's next level dude. Next. Level.

Took a long time to find this. Still a problem in 2019. But after all the other issues I've encountered, I'm not surprised. EF6 is meant for dev's who conform to EF6, not for database admins who want to make their life easier and ensure their employees stay true to proper code. 
That should be a massive surgeon general warning label.
More like tear your hair out and stuff it in your face after spending 6 hours debugging, then pollute your code with workarounds.

To say I'm angry, is an understatement. Good job Microsoft. 0/10 on usability for this one.
And love seeing how you close the ticket in favor of not solving the problem - 10/10 classic.

**Comment by bricelam** [comment] 2019-10-09 16:17
EF Core uses the CLR default value to determine if it should use the SQL default.

With a `bool` property:

.NET | SQL
--- | ---
false | 1 (via DEFAULT)
true | 1

With a `bool?` property:

.NET | SQL
--- | ---
null | 1 (via DEFAULT)
false | 0
true | 1

It sounds like you don't really want a DEFAULT constraint in the database. Maybe defaulting the CLR property is a more appropriate solution for your application.

**Closed** 2022-10-16 10:48 UTC
