### ISSUE TITLE
I can't perform a Migration 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#30437] opened 2023-03-08 10:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/I-cant-perform-a-Migration-/10290802)._

---
When I have installed the NuGet packages necessary for the solution I want to perform and created the necessary classes for it I try to perform the first Migration and I get the following error message: 
Exception when calling "GetInterface" with the arguments "2": "Online: 29 Character: 34
+                 }. GetNewClosure()
+                                  ~
An expression was expected after '('.

Online: 36 Character: 22
+     }. GetNewClosure()
+                      ~
An expression was expected after '('.

Online: 39 Character: 1
+ | $InterfaceType.GetMembers() %{
+ ~
Empty piping elements are not allowed."
In C:\program files\microsoft visual studio\2022\preview\common7\ide\commonextensions\microsoft\nuget\Modules\NuGet\profile.ps1: 109 Character: 5
+ [NuGetConsole.Host.PowerShell.Implementation.PSTypeWrapper]::GetI ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParseException
 
Add-Migration: You cannot call a method on a null expression.
Online: 1 Character: 1
+ Add-Migration InitialCreate
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo : InvalidOperation: (:) [Add-Migration], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Add-Migration
 
Please, someone could clarify why I get this message.
Thanks a lot.

---
#### Feedback Bot on 2/27/2023, 02:52 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2023-03-20 19:50
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-03-20 19:50 UTC
Labels: customer-reported
