### ISSUE TITLE
Problem when changing the type of table-per-hierarchy entry

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#7509] opened 2017-01-30 08:47 UTC
I am building an example of using the table-per-hierarchy (TPH) feature in EF Core. I have a base class called `Book` and at derived class called `BookWithPromotion`. I want to update an entry to change from one to the other, i.e. I want to change an entry that is currently a `Book` type to a `BookWithPromotion` type. But when I do that I hit the "...cannot be tracked because another instance of this type with the same key is already being tracked" issue - see issue #7340.

*I through I had found one way round this by reading the original entry with `AsNoTracking()`, building the new entry and use `Update`. (not a nice solution, but possible). However, this causes another problem - see issue #7510.*

### Exception and stack trace
```
The instance of entity type 'BookPromotion' cannot be tracked because another instance of this type with the same key is already being tracked. When adding new entities, for most key types a unique temporary key value will be created if no key is set (i.e. if the key property is assigned the default value for its type). If you are explicitly setting key values for new entities, ensure they do not collide with existing entities or temporary values generated for other new entities. When attaching existing entities, ensure that only one entity instance with a given key value is attached to the context.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at TryEfCoreTHP.UnitTests.TestThp.WriteBookPromotion() in C:\Users\Jon\Documents\Visual Studio 2015\Projects\TryEfCoreTHP\src\TryEfCoreTHP\UnitTests\TestThp.cs:line 50
```

### Steps to reproduce

The following Unit Test fails on the second call to `SaveChanges`.
```c#
[Fact]
public void UpdateBookToPromotion()
{
    //SETUP
    var inMemDb = new SqliteInMemory();

    using (var context = inMemDb.GetContextWithSetup())
    {
        var book = new Book {Title = "Book", Price = 2};
        context.Books.Add(book);
        context.SaveChanges();

        //ATTEMPT
        var bookProm = new BookPromotion
        {
            BookId = book.BookId,
            Title = book.Title,
            OldPrice = book.Price,
            Price = 1,
            PromotionText = "This promotion"
        };
        context.Books.Update(bookProm);
        context.SaveChanges();

        //VERIFY
        context.Books.Single().GetType().ShouldEqual(typeof(BookPromotion));
    }
}
```
The classes are:
```c#
    public class Book
    {
        public int BookId { get; set; }
        public bool HasPromotion { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
    }
```
```c#
    public class BookPromotion : Book
    {
        public decimal OldPrice { get; set; }
        public string PromotionText { get; set; }
    }
```
The DbContext is:
```c#
public class MyDbContext : DbContext
{
    public DbSet<Book> Books { get; set; }

    public MyDbContext(
        DbContextOptions<MyDbContext> options)      
        : base(options) { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Book>()
            .HasDiscriminator<bool>("HasPromotion")
            .HasValue<Book>(false)
            .HasValue<BookPromotion>(true);
    }
}
```

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio 2015, Update 3.

**Comment by ajcvickers** [comment] 2017-01-31 17:34
@JonPSmith Closing this as a dupe of #7340.

Some more details: EF doesn't support type mutation for a number of reasons, one of them being that the CLR doesn't support type mutation--.NET does not let an object that was a Book become a BookPromotion, or vice versa. That being said, the code you posted is obviously not doing this. It is instead attempting to delete an entity with a given identity in the same unit-of-work where a new entity with the same identity is being created. This is what #7340 is about. As with all cases like this, it can, of course be handled by calling SaveChanges to do the delete first, followed by adding the new entity and calling SaveChanges again.

**Comment by JonPSmith** [comment] 2017-01-31 19:20
Hi @ajcvickers ,

Thanks for that. Yes, I agree it is a duplicate of #7430. Having seen your comments on #7510 I think the code above is the only way I could achieve mutation. I think my use case is valid use of TPH, but I accept that you may define mutation of TPH as invalid in EF Core.

PS. Two SaveChanges is not an option I would ever use in an example, for obvious reasons.

**Comment by ajcvickers** [comment] 2017-01-31 20:14
@JonPSmith What are the reasons for now using two SaveChanges?

**Comment by JonPSmith** [comment] 2017-01-31 20:34
Oh, sorry. In my examples I am always aiming for *atomic* updates - they either all work or all fail. I think that is good thing to get in people's mind.

Also, in my own/client projects, which are all web applications, I never use multiple calls to SaveChanges (other than inside a transaction) - my rule is, if the request contains a database update then one, and only one call to SaveChanges should be done.

**Comment by ajcvickers** [comment] 2017-01-31 20:37
@JonPSmith This would be a great place to use a transaction.

**Comment by JonPSmith** [comment] 2017-02-01 08:16
Yep - that would be a way round it. Bit heavy though. Is there any view on whether #7340 is going to be changed?

**Comment by ajcvickers** [comment] 2017-02-01 17:51
@JonPSmith When you say it's a bit heavy, do you mean because there is more code? In both cases there will be a transaction, the only difference is whether EF creates the transaction for a single SaveChanges call or whether you tell EF to use the transaction for more than one call. So something like this:
```C#
using (var context = new MyDbContext())
{
    var book = context.Books
        .Include(p => p.Promotion)
        .First(p => p.Promotion != null);

    book.Promotion = new PriceOffer
    {
        NewPrice = book.Price / 2,
        PromotionalText = "Half price today!"
    };

    context.SaveChanges();
}
```
Becomes:
```C#
using (var context = new MyDbContext())
{
    var book = context.Books
        .Include(p => p.Promotion)
        .First(p => p.Promotion != null);

    using (var transaction = context.Database.BeginTransaction())
    {
        book.Promotion = null;
        context.SaveChanges();

        book.Promotion = new PriceOffer
        {
            NewPrice = book.Price / 2,
            PromotionalText = "Half price today!"
        };

        context.SaveChanges();

        transaction.Commit();
    }
}
```
Doesn't look too bad to me; only a few lines more code, and very similar in terms of what is sent to the database.

With regard to #7340, we have been thinking about it, but there are ambiguities around the semantics that add complexity because of having two entities tracked at the same time that both have the same identity. For example, if we find another FK that refers to that identity, should it be fixed up to point to the one marked for deletion or the newly added on? It is possible to come up with scenarios where both behaviors would be correct. My best guess at this point is that nothing will change in this area for 2.0, and it may still be that we choose to never do this.

**Comment by JonPSmith** [comment] 2017-02-01 19:40
Hi @ajcvickers,

Thanks for a really excellent and helpful comment. Yes, my comment that is was "a bit heavy" was about extra code needed for transactions. I *think* I might personally use that, but for the examples I am producing for others then it's a bit heavy.

Thanks for the feedback on #7340. It's helpful as I am writing examples and I can avoid/warn people about this. 

Thanks again.

**Closed** 2022-10-16 10:51 UTC
Labels: closed-duplicate
