### ISSUE TITLE
Incremental scaffold existing database

### ISSUE THREAD

**Issue by Liero** [dotnet/efcore#25071] opened 2021-06-10 08:08 UTC
### What problem are you trying to solve? 

When I want to scaffold new table to existing Db Context, the EF Core CLI regenerates all classes which dismiss any changes I might have done.

When I explicitly tell to scaffold only particular Tables, relationships to exiting entities are ignored.

### Describe the solution you'd like

I would like to perform incremental update of my model. It would load existing model model configuration, add new entities and configuration classes without regenerating entire model.

e.g.:
`dotnet ef dbcontext scaffold "Server=localhost;Database=Blogging" Microsoft.EntityFrameworkCore.SqlServer --table NewTable --incremental`

**Comment by roji** [comment] 2021-06-10 09:52
Duplicate of #831

**Comment by roji** [comment] 2021-06-10 09:53
@Liero you probably want to take a look at @ErikEJ's [EF Core Power Tools](https://github.com/ErikEJ/EFCorePowerTools/wiki), which should help you with that.

**Comment by Liero** [comment] 2021-06-11 07:45
@roji: #831 is simmilar, but I would still like to be to able to add just one entity to the model. Or update just one entity in the model.

Let's say there are Blog and Post entities, in the DB. When I run:
`dotnet ef dbcontext update "Server=localhost;Database=Blogging" Microsoft.EntityFrameworkCore.SqlServer --table Blog`

relationship to Post will not be lost.


Regarding EF Core Power Tools: As far as I know, they allow to choose tables to generate, but adding a single table is not possible. It rewrites all existing entities and removes any customizations except .partial.cs

**Comment by roji** [comment] 2021-06-11 09:11
@Liero what would be the behavior if you tell us to scaffold Posts, but haven't yet scaffolded Blogs? Or if you've scaffolded Blogs, but the type of its primary key column has changed in the database since then, and so the foreign key on Posts is no longer compatible?

In general, tables in relational databases tend to have relationships between themselves, and trying to pick a single table out seems like it would open up a whole lot of issues.

What is your usage scenarios which requires scaffolding only one table?

**Comment by ErikEJ** [comment] 2021-06-11 10:35
What kind of customizations do you need that the options of Power Tools and partial classes cannot fulfill?

**Comment by Liero** [comment] 2021-06-12 12:26
> What kind of customizations do you need that the options of Power Tools and partial classes cannot fulfill?

I have refactored the entities to use Owned type, for example

**Comment by ErikEJ** [comment] 2021-06-12 14:24
Ok, so you are mixing domain modelling and database first.

**Comment by Liero** [comment] 2021-06-12 16:17
Well, yes, I'm actually converting old CRUD-sgyled application into modern with as much DD features as possible.
Mostly I just need to scaffold a new view.

**Comment by ErikEJ** [comment] 2021-06-12 19:18
I think you have chosen that path of manual changes in that case.

**Closed** 2022-10-16 19:36 UTC
Labels: closed-duplicate, customer-reported
