### ISSUE TITLE
NullReferenceException on Where(d => d.Property.HasValue)

### ISSUE THREAD

**Issue by SteffenMangold** [dotnet/efcore#13737] opened 2018-10-24 11:21 UTC
Simple "where" query throws an exception. This is new in Preview 3.

```
Exception message:
System.NullReferenceException

Stack trace:
   bei lambda_method(Closure , InternalEntityEntry )
   bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.OriginalValues..ctor(InternalEntityEntry entry)
   bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.EnsureOriginalValues()
   bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe(InternalEntityEntry entry)
   bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer& valueBuffer, ISet`1 handledForeignKeys)
   bei Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.StartTracking(Object entity, IEntityType entityType)
   bei lambda_method(Closure , QueryContext , DataLogger , Object[] )
   bei Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._Include[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Action`3 fixup)
   bei lambda_method(Closure , TransparentIdentifier`2 )
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   bei Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
var dataLoggers = azureModel.Objects
                    .Include(d => d.SubObject)
                    .Where(d => d.SubObjectID.HasValue)
                    .ToList();
```

### Further technical details
EF Core version: 2.2.0-preview3-35497
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by ajcvickers** [comment] 2018-10-24 16:34
@SteffenMangold I have not been able to reproduce this--my code is below. Can you post a runnable project/solution or complete code listing like that below that demonstrates the behavior you are seeing.

```C#
public class DataLogger
{
    public int Id { get; set; }

    public int? SubObjectId { get; set; }
    public SubObject SubObject { get; set; }
}

public class SubObject
{
    public int Id { get; set; }
}

public class BloggingContext : DbContext
{
    //private static readonly LoggerFactory Logger
    //    = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            //.UseLoggerFactory(Logger)
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    public DbSet<DataLogger> Objects { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new DataLogger { SubObject = new SubObject() });

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var dataLoggers = context.Objects
                .Include(d => d.SubObject)
                .Where(d => d.SubObjectId.HasValue)
                .ToList();
        }
    }
}
```

**Comment by SteffenMangold** [comment] 2018-10-24 22:45
With `model.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;` the error is not thrown.

Full Code:
`public partial class DataLogger
{
	public long ID { get; set; }
	public string Name { get; set; }

	public Project Project { get; set; }
}

public partial class Project : IEntityTypeConfiguration<Project>
{
	public Project()
	{
		DataLogger = new HashSet<DataLogger>();
	}

	public long ID { get; set; }
	public string Name { get; set; }

	public ICollection<DataLogger> DataLogger { get; set; }
}

modelBuilder.Entity<DataLogger>(entity =>
{
	entity.HasIndex(e => new { e.ID, e.ProjectID })
		.HasName("IX_DataLogger_ProjectID")
		.IsUnique()
		.HasFilter("([ProjectID] IS NOT NULL)");

	entity.Property(e => e.Name).HasMaxLength(50);

	entity.Property(e => e.ProjectID).HasColumnName("ProjectID");

	entity.HasOne(d => d.Project)
		.WithMany(p => p.DataLogger)
		.HasForeignKey(d => d.ProjectID)
		.OnDelete(DeleteBehavior.Cascade)
		.HasConstraintName("FK_DataLogger_Project");
});

modelBuilder.Entity<DataLogger>(entity =>
{	
	entity.Property(e => e.Name)
		.IsRequired()
		.HasMaxLength(50);
}
`

Query:
`var dataLoggers = azureModel.DataLoggers
                    .Include(d => d.Project)
                    .Where(d => d.ProjectID.HasValue)
                    .ToList();`

**Comment by ajcvickers** [comment] 2018-10-25 16:31
@SteffenMangold Still does not repro for me:
```C#
public partial class DataLogger
{
    public long ID { get; set; }
    public string Name { get; set; }

    public long? ProjectID { get; set; }
    public Project Project { get; set; }
}

public partial class Project
{
    public Project()
    {
        DataLogger = new HashSet<DataLogger>();
    }

    public long ID { get; set; }
    public string Name { get; set; }

    public ICollection<DataLogger> DataLogger { get; set; }
}


public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    public DbSet<DataLogger> DataLoggers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DataLogger>(entity =>
        {
            entity.HasIndex(e => new { e.ID, e.ProjectID })
                .HasName("IX_DataLogger_ProjectID")
                .IsUnique()
                .HasFilter("([ProjectID] IS NOT NULL)");

            entity.Property(e => e.Name).HasMaxLength(50);

            entity.Property(e => e.ProjectID).HasColumnName("ProjectID");

            entity.HasOne(d => d.Project)
                .WithMany(p => p.DataLogger)
                .HasForeignKey(d => d.ProjectID)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_DataLogger_Project");
        });

        modelBuilder.Entity<DataLogger>(entity =>
        {
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.AddRange(
                new DataLogger
                {
                    Name = "D1",
                    Project = new Project
                    {
                        Name = "P"
                    }
                },
                new DataLogger
                {
                    Name = "D2",
                });

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var dataLoggers = context.DataLoggers
                .Include(d => d.Project)
                .Where(d => d.ProjectID.HasValue)
                .ToList();
        }
    }
}
```

**Comment by SteffenMangold** [comment] 2018-10-25 19:53
Thats absolut strange, with downgrad to preview-2 it works again. Its somethink with the changetracker

**Comment by ajcvickers** [comment] 2018-10-25 21:05
@SteffenMangold So what version are you able to reproduce this on? I have been trying with 2.2 preview 3, but it doesn't repro for me there.

**Comment by ajcvickers** [comment] 2018-10-31 17:21
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:36 UTC
Labels: closed-could-not-reproduce, customer-reported
