### ISSUE TITLE
Migrations are not ignored by code analyzers

### ISSUE THREAD

**Issue by salaros** [dotnet/efcore#19788] opened 2020-02-04 10:17 UTC
Code-first DB migrations shall be excluded from StyleCop/FxCop etc analysis

Please consider adding the following comment to ALL migration-related files

```xml
// <auto-generated/>
```

![image](https://user-images.githubusercontent.com/675348/73735943-0f218700-4751-11ea-81f7-35271cabce56.png)

**Comment by ajcvickers** [comment] 2020-02-04 17:39
Duplicate of #10203

**Closed** 2022-10-16 18:09 UTC
Labels: customer-reported

**Comment by hades200082** [comment] 2025-01-17 14:40
These days you can add the following to your .editorconfig file (adjust the file path in the square brackets as needed)

```ini
# Do not apply code styles to generated migration files
[**/Migrations/*.cs]
generated_code = true
```

**Comment by hades200082** [comment] 2025-01-27 17:22
@salaros There is a semantic meaning to the `<auto-generated/>` annotation already defined by Microsoft in the Roslyn analyzers.

It's a special marker typically placed at the top of code files that are **automatically generated by a tool or a build process**. It serves as a signal to developers and tools that **the file is not intended to be manually edited**, as any changes made to it may be overwritten the next time the file is regenerated.

It's that second bold part that's the problem here - _the file is not intended to be manually edited_ - because EF Migrations _are_ intended to be manually edited after generation. That's why they don't carry this annotation by default.

Thus, if you want to exclude them from code analysis you need to do one of the following:

1. Manually edit each file to add the annotation (usually undesirable)
2. Add some code to your migrations project that prefixes the generated files as discussed in [#10203](https://github.com/dotnet/efcore/issues/10203)
3. Add the section I mentioned above to your `.editorconfig` file 

I prefer the last option as it means I don't need extra code in my projects and the `.editorconfig` is checked in anyway for my team AND its what configures & drives my code analysis tools anyway.
