### ISSUE TITLE
Improve exception for many-to-many self reference

### ISSUE THREAD

**Issue by samuelpsfung** [dotnet/efcore#24773] opened 2021-04-27 07:38 UTC
Using EF Core 5.0.4, MySql.EntityFrameworkCore 5.0.0

EF is able to generate the schema for the below relationship and save the 1st member John. Then I create 2nd member Peter and adds John as his friend, it throws an exception. 

```c#
public class Member
{
    public int ID { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Member> Friends { get; set; }
}
```

```c#
modelBuilder.Entity<Member>(e =>
{
    e.HasMany(p => p.Friends)
     .WithMany(p => p.Friends)
     .UsingEntity<Dictionary<string, object>>(
        "MemberFriends",
        j => j.HasOne<Member>()
            .WithMany()
            .HasForeignKey("MemberID")
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade),
        j => j.HasOne<Member>()
            .WithMany()
            .HasForeignKey("FriendID")
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade))
     .HasKey("MemberID", "FriendID");
});
```

```c#
using (var dbContext = host.Services.GetRequiredService<MemberDbContext>())
{
    var john = new Member { Name = "John" };
    dbContext.Add(john);
    dbContext.SaveChanges();
}

using (var dbContext = host.Services.GetRequiredService<MemberDbContext>())
{
    var john = dbContext.Set<Member>().Where(m => m.Name == "John").Single();
    var peter = new Member {
        Name = "Peter",
        Friends = new List<Member> { john }
    };
    dbContext.Add(peter); // throws exception
    dbContext.SaveChanges();
}
```
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyBaseExtensions.GetStoreGeneratedIndex(IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.get_Item(IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.SetForeignKeyProperties(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey, Boolean setModified, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.FindOrCreateJoinEntry(InternalEntityEntry entry, InternalEntityEntry otherEntry, ISkipNavigation skipNavigation, Boolean fromQuery, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.FireStateChanged(EntityState oldState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity](TEntity entity)
```

**Comment by samuelpsfung** [comment] 2021-04-27 08:33
I changed to define a class for the join entity type, another exception is throw:

```c#
public class MemberFriend
{
    public int MemberID { get; set; }
    public virtual Member Member { get; set; }

    public int FriendID { get; set; }
    public virtual Member Friend { get; set; }
}
```

```c#
modelBuilder.Entity<Member>(e =>
{
    e.HasMany(p => p.Friends)
     .WithMany(p => p.Friends)
     .UsingEntity<MemberFriend>(
        j => j.HasOne(p => p.Member)
            .WithMany()
            .HasForeignKey(p => p.MemberID)
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade),
        j => j.HasOne(p => p.Friend)
            .WithMany()
            .HasForeignKey(p => p.FriendID)
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade),
        j => j.HasKey(p => new { p.MemberID, p.FriendID })
     );
});
```
```
System.InvalidOperationException
  HResult=0x80131509
  Message=The value of 'MemberFriend.FriendID' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at MySql.EntityFrameworkCore.Storage.Internal.MySQLExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
```

**Comment by ajcvickers** [comment] 2021-04-27 16:18
@samuelpsfung EF Core doesn't support a single navigation property acting on both ends of the relationship. You'll need to have two collections, one for each direction:

```C#
public class Member
{
    public int ID { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Member> MyFriends { get; set; }
    public virtual ICollection<Member> FriendsWithMe { get; set; }
}
```

One of these can be made `private` if necessary.

@AndriySvyryd Seems like we should detect this and throw a better exception.

**Comment by samuelpsfung** [comment] 2021-04-28 02:36
@ajcvickers 
> One of these can be made private if necessary.

Lazy loading can't work with private property.

```c#
private ICollection<Member> FriendsWithMe { get; set; }

e.HasMany(p => p.MyFriends)
 .WithMany("FirendsWithMe");
```
```
Property 'FirendsWithMe' on entity type 'Member' is mapped without a CLR property. 'UseChangeTrackingProxies' requires all entity types to be public, unsealed, have virtual properties, and have a public or protected constructor. 'UseLazyLoadingProxies' requires only the navigation properties be virtual.
```

**Comment by AndriySvyryd** [comment] 2021-08-31 17:00
Duplicate of #23362

**Closed** 2021-09-14 14:25 UTC
Labels: type-bug, closed-fixed, customer-reported, area-model-building

**Comment by rizkengin** [comment] 2024-07-29 04:26
> Thanks @ajcvickers, this works,
> 
> ```cs
> e.HasMany(p => p.MyFriends)
>   .WithMany(p => p.FriendsWithMe);
> ```
> 
> But I am not satisfied with the generated schema,
> 
> ```
> CREATE TABLE `MemberMember` (
>     `FriendsWithMeID` int NOT NULL,
>     `MyFriendsID` int NOT NULL,
>     PRIMARY KEY (`FriendsWithMeID`, `MyFriendsID`),
>     CONSTRAINT `FK_MemberMember_Member_FriendsWithMeID` FOREIGN KEY (`FriendsWithMeID`) REFERENCES `Member` (`ID`) ON DELETE CASCADE,
>     CONSTRAINT `FK_MemberMember_Member_MyFriendsID` FOREIGN KEY (`MyFriendsID`) REFERENCES `Member` (`ID`) ON DELETE CASCADE
> );
> ```
> 
> So I add `UsingEntity()` to give more readable table/column names,
> 
> ```
> e.HasMany(p => p.MyFriends)
>    .WithMany(p => p.FriendsWithMe)
>    .UsingEntity<Dictionary<string, object>>(
>       "MemberFriends",
>       j => j.HasOne<Member>()
>           .WithMany()
>           .HasForeignKey("MemberID")
>           .IsRequired()
>           .OnDelete(DeleteBehavior.Cascade),
>       j => j.HasOne<Member>()
>           .WithMany()
>           .HasForeignKey("FriendID")
>           .IsRequired()
>           .OnDelete(DeleteBehavior.Cascade),
>       j => j.HasKey("MemberID", "FriendID")
>   );
> ```
> 
> Then the same exception is thrown.


> Thanks @ajcvickers, this works,
> 
> ```cs
> e.HasMany(p => p.MyFriends)
>   .WithMany(p => p.FriendsWithMe);
> ```
> 
> But I am not satisfied with the generated schema,
> 
> ```
> CREATE TABLE `MemberMember` (
>     `FriendsWithMeID` int NOT NULL,
>     `MyFriendsID` int NOT NULL,
>     PRIMARY KEY (`FriendsWithMeID`, `MyFriendsID`),
>     CONSTRAINT `FK_MemberMember_Member_FriendsWithMeID` FOREIGN KEY (`FriendsWithMeID`) REFERENCES `Member` (`ID`) ON DELETE CASCADE,
>     CONSTRAINT `FK_MemberMember_Member_MyFriendsID` FOREIGN KEY (`MyFriendsID`) REFERENCES `Member` (`ID`) ON DELETE CASCADE
> );
> ```
> 
> So I add `UsingEntity()` to give more readable table/column names,
> 
> ```
> e.HasMany(p => p.MyFriends)
>    .WithMany(p => p.FriendsWithMe)
>    .UsingEntity<Dictionary<string, object>>(
>       "MemberFriends",
>       j => j.HasOne<Member>()
>           .WithMany()
>           .HasForeignKey("MemberID")
>           .IsRequired()
>           .OnDelete(DeleteBehavior.Cascade),
>       j => j.HasOne<Member>()
>           .WithMany()
>           .HasForeignKey("FriendID")
>           .IsRequired()
>           .OnDelete(DeleteBehavior.Cascade),
>       j => j.HasKey("MemberID", "FriendID")
>   );
> ```
> 
> Then the same exception is thrown.

I'm expriencing the same issue with self referencing many to many and UsingEntity<> for readable table columns. the same exception gets thrown do you have an update on this?

**Comment by ajcvickers** [comment] 2024-08-12 11:50
@rizkengin Please open a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
