### ISSUE TITLE
must be reducible node exception on previously working query

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#12861] opened 2018-08-02 00:46 UTC
My reason for reporting this is that it was working - exactly as shown - under EF 6.     
```C#
    var query = db.ContentItems.Where(x => x.Active && x.ContentGroupID.HasValue && x.PublishDate.HasValue && x.MenuContentItems.Any(y => y.MenuID == menuID));

	if (groupColumn == "GroupID")
	{
		
		result = await (from q in query
						group q by q.ContentGroupID into groups
						select new KeyValuePair<string, string>(groups.Key.ToString(), db.ContentGroups.First(x => x.ID == groups.Key).Description)).ToListAsync();
	}
	else if (groupColumn == "PubDate")
	{
		result = await (from q in query
						group q by q.PublishDate.Value.Year.ToString() + "-" + q.PublishDate.Value.Month.ToString().PadLeft(2, '0') + "-01" into groups
						select new KeyValuePair<string, string>(groups.Key, groups.First().PublishDate.Value.ToString("MMMM") + " " + groups.First().PublishDate.Value.Year.ToString())).OrderByDescending(x => x.Key).ToListAsync();
	}
```

ContentItem.cs
```C#		
	public class ContentItem
    {
        public int ID { get; set; }
        public ContentItemType ContentType { get; set; }
        public int? ContentGroupID { get; set; }
        public DateTime? PublishDate { get; set; }
        public DateTime? LastModifyDate { get; set; }
        public string ChangeFrequency { get; set; }
        public decimal Priority { get; set; }
        public bool Active { get; set; }
        public string Slug { get; set; }
        public string Title { get; set; }
        public string MenuText { get; set; }
        public string URL { get; set; }
        public string Abstract { get; set; }
        public string Icon { get; set; }
        public string Tags { get; set; }
        public bool AllowComments { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ContentGroup ContentGroup { get; set; }
        public virtual ICollection<MenuContentItem> MenuContentItems { get; set; }
    }
```
[Possibly related ](https://github.com/aspnet/EntityFrameworkCore/issues/12721)

Using EF Core 2.1.1

**Comment by ajcvickers** [comment] 2018-08-04 00:07
@sam-wheat We're having trouble reproducing this. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2018-08-10 17:46
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:22 UTC
Labels: closed-could-not-reproduce, customer-reported
