### ISSUE TITLE
Crash with OR predicate when running in docker

### ISSUE THREAD

**Issue by darind** [dotnet/efcore#24412] opened 2021-03-16 13:58 UTC
### Include your code

Clone the following repo: https://github.com/darind/SQLiteTest

and build the docker image using the following command:

```
docker build -t sqlite-test:1.0.0 .
```

The offending query is the following:

```
var events = await context.Set<Parent>()
    .Where(x => x.SenderId == 5 || x.ReceiverId == 4)
    .ToListAsync();
```

The problem is the OR operator used in the predicate. If I replace the query with the following then it works:

```
var events = await context.Set<Parent>()
    .Where(x => x.SenderId == 5)
    .ToListAsync();
```

### Include stack traces

The program crashes without any stacktrace when it tries to execute this query. It is important to note that the crash doesn't occur on any host OS. For example the code works fine on a MacOS 11.2.2 host but it crashes on Ubuntu 18.04 even though in both cases it runs inside docker.

This is the output:

```
Sending build context to Docker daemon  86.02kB
Step 1/6 : FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine as build
 ---> 8a8399b1655a
Step 2/6 : WORKDIR /source
 ---> Using cache
 ---> 671c042570ca
Step 3/6 : COPY SQLiteTest/*.csproj ./SQLiteTest/
 ---> 5e6ac1f930cb
Step 4/6 : COPY SQLiteTest/. ./SQLiteTest/
 ---> a1db98401af5
Step 5/6 : WORKDIR /source/SQLiteTest
 ---> Running in 15f4519706a3
Removing intermediate container 15f4519706a3
 ---> ddd6b250ddc9
Step 6/6 : RUN dotnet run .
 ---> Running in fc1fcdc68869
BEFORE QUERY
The command '/bin/sh -c dotnet run .' returned a non-zero code: 139
```

### Include version information

Microsoft.Data.Sqlite version: 5.0.4
Target framework: .NET 5.0
Operating system: 18.04.1-Ubuntu SMP Wed Jan 6 22:31:04 UTC 2021

**Comment by darind** [comment] 2021-03-16 14:22
@roji, I have linked to a very minimal git repo exhibiting the issue: https://github.com/darind/SQLiteTest

Just clone the repo and run the docker build command as shown in my post.

I cannot provide a stacktrace because there is no such. The process simply exits without any messages.

**Comment by darind** [comment] 2021-03-16 14:59
Another observation: it seems that the issue is related to the `mcr.microsoft.com/dotnet/sdk:5.0-alpine` docker image. If I use the `mcr.microsoft.com/dotnet/sdk:5.0` image then it works fine.

**Comment by darind** [comment] 2021-03-16 15:17
In this specific issue the host OS also seems to make a difference. It works on MacOS and crashes on Ubuntu.

**Comment by ajcvickers** [comment] 2021-03-19 16:36
Possible duplicate of #24189

**Closed** 2022-10-16 19:28 UTC
Labels: closed-duplicate, customer-reported, area-adonet-sqlite
