### ISSUE TITLE
Nested owned types are reset during DetectChanges

### ISSUE THREAD

**Issue by juilan-softpark** [dotnet/efcore#16635] opened 2019-07-17 11:18 UTC
Nested owned entities do not get updated. As far as I can see in the docs, it should be possible to have a type owned by a type owned by an entity. However, when you such an entity is loaded and the nested entity changed, the values of the nested entity get reset to their last loaded value in DbContext.SaveChanges() or more specifically in ChangeTracker.DetectChanges(),

### Example domain and context:
```c#
internal class Course
{
    public Guid Id { get; private set; }
    public TrackPeriod Period { get; private set; } 
}

internal class TrackPeriod
{
    public int Track { get; private set; } 
    public Date Beginning { get; private set; } 
    public Date End { get; private set; }
}
internal class Date
{
    public int Year { get; private set; } = 1;
    public int Month { get; private set; } = 1;
    public int Day { get; private set; } = 1;
}

internal class CoursesContext : DbContext
{
    public CoursesContext(DbContextOptions<CoursesContext> options) : base(options)
    {
    }

    public DbSet<Course> Courses { get; private set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        
        modelBuilder.Entity<Course>().OwnsOne(t => t.Period);
        
        var datePeriodModelBuilder = modelBuilder.Entity<TrackPeriod>();
        datePeriodModelBuilder.OwnsOne(t => t.Beginning);
        datePeriodModelBuilder.OwnsOne(t => t.End);
    }
}
```

### Steps to reproduce:
1. Open db context
1. Add new Course and SaveChanges()
1. Open new db context
1. Load and modify previously added course.
1. Call SaveChanges()
During the last call to SaveChanges() the nested entity's values are reset to the ones it was loaded with.

### Further technical details
EF Core version: 2.2.6 (latest 3.0.0-preview6.19304.10 throws an Exception during query generation)
Database Provider: InMemory, SQLite, SqlServer
Operating system: Win10 64-bit
IDE: Visual Studio 2019

### Sample project:

[EFCoreOwnsTest.zip](https://github.com/aspnet/EntityFrameworkCore/files/3401587/EFCoreOwnsTest.zip)

**Comment by ajcvickers** [comment] 2019-07-17 22:40
Verified that this is fixed in the current 3.0 code. Probably a duplicate of #12118

**Closed** 2022-10-16 14:31 UTC
Labels: customer-reported
