### ISSUE TITLE
NullReferenceException during load of owned child

### ISSUE THREAD

**Issue by Rikarin** [dotnet/efcore#11434] opened 2018-03-26 20:12 UTC
Hi,
I got a null reference exception when I try to lazy load value object.

```c#
class Measurement {
  public int Num {get;set}
}

class Bar {
  public virtual Measurement Foo1 {get;set;}
  public virtual Measurement Foo2 {get;set;}
}

// Configuration
builder.OwnsOne(x => x.Foo1);
builder.OwnsOne(x => x.Foo2);

var bar = _barRepository.Get(42);
var foo = bar.Foo1; // NullReferenceException
```

It works fine with one value object, but it's throwing exception with multiple ones.

```
Exception message:
      An unhandled exception has occurred [ERR_2646F84C]: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.NewInternalEntityEntry(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.Create(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer valueBuffer, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.StartTracking(Object entity, IEntityType entityType)
   at lambda_method(Closure , QueryContext , Measurement , Object[] )
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._Include[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Action`3 fixup)
   at lambda_method(Closure , TransparentIdentifier`2 )
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.Load[TSource](IQueryable`1 source)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Load(INavigation navigation, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.NavigationEntry.Load()
   at Microsoft.EntityFrameworkCore.ChangeTracking.CollectionEntry.Load()
   at Microsoft.EntityFrameworkCore.Internal.LazyLoader.Load(Object entity, String navigationName)
   at Microsoft.EntityFrameworkCore.Proxies.Internal.LazyLoadingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
....
```

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: MacOS High Sierra
IDE: VS for Mac

**Comment by ajcvickers** [comment] 2018-03-28 00:43
@Rikarin I have not been able to reproduce the behavior you are seeing. Can you post a runnable project/solution or a complete code listing that reproduces the issue?

(Note that should work regardless of lazy-loading should since owned types are automatically eagerly loaded when the owner is queried.)

**Comment by divega** [comment] 2018-04-04 19:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 12:16 UTC
Labels: closed-could-not-reproduce
