### ISSUE TITLE
Include and ThenInclude sub properties causes System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/efcore#12926] opened 2018-08-07 23:42 UTC
_From @harsha89vyas on July 19, 2018 15:54_

The following include sequence causes the **System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct**
.Include(x => x.A)
                                                        .ThenInclude(x => x.B)
                                                        .ThenInclude(x => x.C)
                                                     .Include(x => x.A)
                                                        .ThenInclude(x => x.B)
                                                        .ThenInclude(x => x.D)
                                                        .ThenInclude(x => x.E)
                                                     .Include(x => x.A)
                                                        .ThenInclude(x => x.B)
                                                        .ThenInclude(x => x.D)
                                                        .ThenInclude(a => a.F)
                                                     .Include(x => x.A)
                                                        .ThenInclude(x => x.B)
                                                        .ThenInclude(x => x.D)
                                                        .ThenInclude(a => a.G)
                                                     .Include(x => x.A)
                                                        .ThenInclude(x => x.B)
                                                        .ThenInclude(x => x.D)
                                                        .ThenInclude(a => a.C)
                                                        .ThenInclude(a => a.H)

This happens due to the fix https://github.com/dotnet/coreclr/pull/16991 applied due to issue https://github.com/dotnet/corefx/issues/28123

_Copied from original issue: dotnet/coreclr#19027_

**Comment by RussKeldorph** [comment] 2018-08-07 23:42
_From @benaadams on July 19, 2018 16:55_

Added an issue to corefx so its easier to find information about this exception in search dotnet/corefx#31186

**Comment by ajcvickers** [comment] 2018-08-07 23:49
@harsha89vyas This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing. Also, please post the full stack trace from the exception.

**Comment by ajcvickers** [comment] 2018-08-15 17:29
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:24 UTC
Labels: closed-could-not-reproduce, customer-reported
