### ISSUE TITLE
Model compiler fails to include namespace in generated code

### ISSUE THREAD

**Issue by nettashamir-allocate** [dotnet/efcore#30857] opened 2023-05-09 12:37 UTC
Running the model compiler, in some cases, fails to add the namespace of classes it refers to in the generated code.
Two examples I've encountered are included in the repro code below:

In Framework.csproj we have the following entity base class:

```
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Framework;

public abstract class ChangeSet {
	public abstract long ID { get; }
}

public abstract class ChangeSetMappings<TChangeSet> : IEntityTypeConfiguration<TChangeSet> where TChangeSet : ChangeSet {
	public virtual void Configure(EntityTypeBuilder<TChangeSet> entity) {
		entity.ToTable(typeof(TChangeSet).Name);
		entity.HasKey(e => e.ID);
		entity.Property(e => e.ID)
			.HasColumnName("ChangeSetID")
			.HasField("id");
	}
}
```

And in BugRepro.csproj we have the concrete subtype:

```
using Framework;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BugRepro.Product;

public class ChangeSet : Framework.ChangeSet {

	protected long id;

	public static ChangeSet Create(string name) { return new ChangeSet { id = 1, Name = name }; } //, created = created }; }
	public override long ID { get { return id; } }
	public string Name { get; set; }

}

public class ChangeSetMappings : ChangeSetMappings<ChangeSet> {

	public override void Configure(EntityTypeBuilder<ChangeSet> entity) {
		base.Configure(entity);
		entity.Property(e => e.Name);
	}
}
```

And the DbContext which also configures a t-sql function mapping: 

```
using BugRepro.DataAccess;
using BugRepro.Product;
using Microsoft.EntityFrameworkCore;

namespace BugRepro;

public class TestDbContext : DbContext {

	private const string DATA_SOURCE = ""; //Insert DataSource string here eg. YOUR_MACHINE_NAME\\DB_INSTANCE_NAME
	const string CONNECTION_STRING = $"Data Source={DATA_SOURCE};Initial Catalog=TestEFCoreBugs;Integrated Security=True;TrustServerCertificate=True";

	public DbSet<ChangeSet> ChangeSets { get; set; }

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
		optionsBuilder.UseSqlServer(CONNECTION_STRING);
		optionsBuilder.UseModel(CompiledContextModels.TestDbContextModel.Instance);
	}

	protected override void OnModelCreating(ModelBuilder modelBuilder) {
		modelBuilder.ApplyConfiguration(new ChangeSetMappings());

		// configure t-sql function
		var methodInfo = typeof(DatabaseFunctions).GetMethod(nameof(DatabaseFunctions.HashBytes), new []{typeof(string), typeof(string)});
		modelBuilder.HasDbFunction(methodInfo).HasName("HASHBYTES").IsBuiltIn();
	}
}
```

```
namespace BugRepro.DataAccess;

public class DatabaseFunctions {
	public static Byte[] HashBytes(string algorithm, string value) =>
		throw new NotSupportedException("Dummy function");
}
```

Running the model compiler using:

`dotnet ef dbcontext optimize -o CompiledContextModels -c TestDbContext --verbose`

Results in the following classes generated:

### ChangeSetEntityType.cs

```
// <auto-generated />
using System;
using System.Reflection;
using BugRepro.Product;
using Framework;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BugRepro.CompiledContextModels
{
    internal partial class ChangeSetEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "BugRepro.Product.ChangeSet",
                typeof(ChangeSet),
                baseEntityType);

            var iD = runtimeEntityType.AddProperty(
                "ID",
                typeof(long),
                propertyInfo: typeof(ChangeSet).GetProperty("ID", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChangeSet).GetField("id", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw);
            iD.AddAnnotation("Relational:ColumnName", "ChangeSetID");
            iD.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(ChangeSet).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChangeSet).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            name.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { iD });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }
...

```

Where the inclusion of the `using Framework;` results in a set of compilation **errors** of the form:

> Error	CS0104	'ChangeSet' is an ambiguous reference between 'BugRepro.Product.ChangeSet' and 'Framework.ChangeSet'

I would expect that references to ChangeSet should include the namespace qualifier to disambiguate.

### TestDbContextModelBuilder.cs

```
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BugRepro.CompiledContextModels
{
    public partial class TestDbContextModel
    {
        partial void Initialize()
        {
            var changeSet = ChangeSetEntityType.Create(this);

            ChangeSetEntityType.CreateAnnotations(changeSet);

            var functions = new SortedDictionary<string, IDbFunction>();
            var hashBytes = new RuntimeDbFunction(
                "BugRepro.DataAccess.DatabaseFunctions.HashBytes(string,string)",
                this,
                typeof(byte[]),
                "HASHBYTES",
                storeType: "varbinary(max)",
                methodInfo: typeof(DatabaseFunctions).GetMethod(
                    "HashBytes",
                    BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly,
                    null,
                    new Type[] { typeof(string), typeof(string) },
                    null),
                scalar: true,
                nullable: true,
                builtIn: true);
...
```
Where `DatabaseFunctions` is also missing the namespace qualifier.

A full repro VS solution is included here: 
[Missing namespaces.zip](https://github.com/dotnet/efcore/files/11430920/Missing.namespaces.zip)

### Provider and version information

EF Core version: 7.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer 7.0.5
Target framework: NET 6.0
Operating system: Win 11
IDE: Visual Studio 2022 17.5.4

**Comment by AndriySvyryd** [comment] 2023-05-10 20:20
Duplicate of #25523, #27203

**Closed by AndriySvyryd** 2023-05-10 20:21 UTC
Labels: customer-reported
