### ISSUE TITLE
A DbContext instance cannot be used inside OnConfiguring since it is still being configured at this point

### ISSUE THREAD

**Issue by dhirajdhakal09** [dotnet/efcore#26920] opened 2021-12-07 10:17 UTC
I am trying to insert multiple users using Task.WhenAll, but I am always encountered with the exception An attempt was made to use the context while it is being configured. A DbContext instance cannot be used inside OnConfiguring since it is still being configured at this point. Here is my code..
```C#
    public async Task Funtion1()
     {
        List<Task> trackedTasks = new List<Task>();
        foreach (var multipleUserModel in request.CreateMultipleUsersModels)
        {
            User user = new User
            {
                UserName = multipleUserModel.Email,
                Email = multipleUserModel.Email,
                Role = multipleUserModel.Role
            }; ;
            trackedTasks.Add(Task.Run(() =>

             CreateUser(user, multipleUserModel))) ;
        }
        await Task.WhenAll(trackedTasks);
   }
   private async Task CreateUser(User user, CreateUsersModel model)
    {
        try
        {
            await _validator.ValidateAsync(model, options => options.ThrowOnFailures());

            user.DomainEvents.Add(new CreateUserEvent(user));

            await _identityService.CreateAsync(user);

            //await Task.Delay(10);
            
        }
        catch(Exception ex)
        {
            Console.WriteLine("Exception >> {0}", ex.Message);
        }
        finally
        {

        }

    }

public async Task<Role> GetRoleByIDAsync(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            return role;
        }

 public async Task<bool> CreateAsync(User user, string role)
        {
            var result = await _userManager.CreateAsync(user);
            if (result.Succeeded)
            {
                await _userManager.AddToRoleAsync(user, role);
                return result.Succeeded;
            }

        }
```
This is how i have configured the dbcontext for dependency injection
```C#
services.AddDbContext<AirleadDbContext>(options =>
        {
            options.UseSqlServer(configuration.GetConnectionString("Airlead"));

        });
        services.AddScoped<IAirleadDbContext>(provider => provider.GetService<AirleadDbContext>());
```

And this is my dbContext

```
  public class SomeDbContext : IdentityDbContext<User, Role, string>, ISomeDbContext
{
    private readonly IDomainEventService _domainEventService;

    //TODO: arrange all dbsets alphabetically
    public DbSet<Table1> Subscriptions { get; set; }

    public SomeDbContext(DbContextOptions<SomeDbContext> options,
                            IDomainEventService domainEventService) :
        base(options)
    {
    }

    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken)
    {
        var result = await base.SaveChangesAsync(cancellationToken);
        await DispatchEvent();
        return result;
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
    }
}
```
This is the full exception and by the way I also got another exception at the same place when running another time, so these exceptions occur interchangeably

```
An attempt was made to use the context while it is being configured. A DbContext instance cannot be used inside OnConfiguring since it is still being configured at this point. This can happen if a second operation is started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.

    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.RoleStore`5.get_Roles()
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.RoleStore`5.FindByIdAsync(String id, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.RoleManager`1.FindByIdAsync(String roleId)
   at Infrastructure.Services.IdentityService.<GetRoleByIDAsync>d__16.MoveNext() in D:\Airsend\airleads-api\Infrastructure\Services\IdentityService.cs:line 103
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Application.Users.Commands.Create.CreateUsersCommandHandler.<CreateUser>d__4.MoveNext() in D:\Airsend\airleads-api\Application\Users\Commands\Create\CreateUsersCommand.cs:line 66
```

Exception 2
```
System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

**Comment by ajcvickers** [comment] 2021-12-07 10:22
@dhirajdhakal09 You are accessing the same DbContext from multiple threads concurrently. See [Avoiding DbContext threading issues](https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/#avoiding-dbcontext-threading-issues).

**Comment by dhirajdhakal09** [comment] 2021-12-07 11:07
@ajcvickers Isn't a new dbContext created when configured as services.Transient<DbContext> from the startup everytime when request is preformed, I mean even when it runs concurrently?

**Comment by ajcvickers** [comment] 2021-12-07 14:27
@dhirajdhakal09 This:

```C#
services.AddDbContext<AirleadDbContext>(options =>
        {
            options.UseSqlServer(configuration.GetConnectionString("Airlead"));

        });
        services.AddScoped<IAirleadDbContext>(provider => provider.GetService<AirleadDbContext>());
```

configures the context as `Scoped`.

**Comment by dhirajdhakal09** [comment] 2021-12-08 03:12
@ajcvickers Yes that configures as Scoped, however I had tried with Transient too but the result was same.

**Comment by ajcvickers** [comment] 2021-12-08 08:16
@dhirajdhakal09 In that case, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2021-12-17 12:39
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:18 UTC
Labels: closed-could-not-reproduce, customer-reported

**Comment by MatrixRonny** [comment] 2023-05-23 14:05
Here is a minimum code sample that reproduces this problem. Slight variations of the code throw different exceptions, see comments. I have tested with Microsoft.EntityFrameworkCore.SqlServer 7.0.5. Must enable migrations before running the code.

``` C#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System.ComponentModel.DataAnnotations;

internal class Program
{
    private static void Main(string[] args)
    {
        Host.CreateDefaultBuilder(args)
       .ConfigureServices(ConfigureServices)
       .Build()
       .Run();
    }

    private static void ConfigureServices(HostBuilderContext host, IServiceCollection services)
    {
        services.AddDbContext<AppDbContext>(options => options.UseSqlServer(
            "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=TestDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
        ));

        services.AddHostedService<TestMethod>();
    }
}

public class Person
{
    public int Id { get; set; }

    [Required]
    public string FullName { get; set; } = null!;

    public DateTime BirthDay { get; set; }
}

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    { }

    public DbSet<Person> People { get; set; } = null!;
}

internal class TestMethod : BackgroundService
{
    private IServiceProvider _serviceProvider;

    public TestMethod(IServiceProvider serviceProvider)
    {
        _serviceProvider = serviceProvider;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        //TODO: Uncomment to receive another exception
        //using (var scope = _serviceProvider.CreateScope())
        //{
        //    _serviceProvider.GetRequiredService<AppDbContext>().Database.Migrate();
        //}

        Func<Task> incrementDate = async () =>
        {
            using (var scope = _serviceProvider.CreateScope())
            {
                var appContext = _serviceProvider.GetRequiredService<AppDbContext>();

                //TODO: Comment transaction for yet another exception.
                using (var transaction = appContext.Database.BeginTransaction())
                {
                    Person person = new Person
                    {
                        FullName = "John Doe",
                        BirthDay = DateTime.Parse("2020-10-05")
                    };
                    appContext.People.Add(person);
                    appContext.SaveChanges();
                    await Task.Delay(3000);
                }
            }
        };

        Task.WaitAll(
            Task.Run(async () => await incrementDate().ConfigureAwait(false)),
            Task.Run(async () => await incrementDate().ConfigureAwait(false))
        );
    }
}
```
