### ISSUE TITLE
Single Item Navigation Property generating inner join, assuming referenced object exists

### ISSUE THREAD

**Issue by NetTecture** [dotnet/efcore#13883] opened 2018-11-05 08:01 UTC
Current release 2.1.4

The following LINQ:

```C#
var items = await repository.OBTIncident
.Include(x => x.OBTIncidentResponse)
.Where(x => x.GIdentity == randomIdentity)
.FirstOrDefaultAsync();
```

generates the following SQL, which is exactly totally wrong (superflous properties removed).

```sql
SELECT TOP(1) [x].[pkIncidentID],
    [x].[bIsSkipped], [x].[dClosedDate], [x].[dCreateDate], [x].[dDueDate], [x].[dRefDate],
    [x.OBTIncidentResponse].[pkIncidentResponseID], [x.OBTIncidentResponse].[bIsDefectProcessed],
FROM[dbo].[OB_TIncident] AS[x]
INNER JOIN[dbo].[OB_TIncidentResponse] AS[x.OBTIncidentResponse] ON [x].[fkIncidentResponseID] = [x.OBTIncidentResponse].[pkIncidentResponseID]
WHERE[x].[gIdentity] = @__randomIdentity_0
```

The OBTIncidentResponse relationship is defined as:

```C#
builder.Property<int?>(x => x.FkIncidentResponseID).HasColumnName(@"fkIncidentResponseID").HasColumnType(@"int").ValueGeneratedNever();
builder.HasOne(x => x.OBTIncidentResponse).WithOne(op => op.OBTIncident).IsRequired(false).HasForeignKey(typeof(OBTIncident), @"FkIncidentResponseID");
```

This makes no sense. The relationship is optional. The FK is nullable. With an inner join, it is assumed a response exists, and rows without response are filtered out. Flat out wrong. EF 6 generated proper outer joins here.

What can I do to bypass thegeneration of an inner join here, which filters out all Incidents without IncidentResponse? Funny enough, if I check whether the navigation property is null, i end up getting a generated SQL that looks like this:

```sql
INNER JOIN[dbo].[OB_TIncidentResponse] AS[x.OBTIncidentResponse] ON[x].[fkIncidentResponseID] = [x.OBTIncidentResponse].[pkIncidentResponseID]
WHERE[x].[fkIncidentResponseID] IS NULL
```

This logically makes zero sense and produces wrong results with missing rows.

**Comment by ajcvickers** [comment] 2018-11-05 20:09
Triage: This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2018-11-12 17:22
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by NetTecture** [comment] 2018-11-18 19:34
@ajcvickers I have nailed it down to a simple example that has 2 elements.

In the core you have an IncidentResponse defined as:

            builder.ToTable(@"OB_TIncident", @"dbo");
            builder.Property<int>(x => x.PkIncidentID).HasColumnName(@"pkIncidentID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd();
            builder.Property<int?>(x => x.FkIncidentResponseID).HasColumnName(@"fkIncidentResponseID").HasColumnType(@"int").ValueGeneratedNever();
            builder.HasKey(@"PkIncidentID");
            builder.HasOne(x => x.OBTIncidentResponse).WithOne(op => op.OBTIncident).IsRequired(false).HasForeignKey(typeof(OBTIncident), @"FkIncidentResponseID");
            
and a LINQ that reads:

                var query = repository.OBTIncident
                    .Include(x => x.OBTIncidentResponse)
                    ;

The SQL that is generated is....

SELECT [x].[pkIncidentID], [x].[fkIncidentResponseID], [x.OBTIncidentResponse].[pkIncidentResponseID]
FROM [dbo].[OB_TIncident] AS [x]
INNER JOIN [dbo].[OB_TIncidentResponse] AS [x.OBTIncidentResponse] ON [x].[fkIncidentResponseID] = [x.OBTIncidentResponse].[pkIncidentResponseID]

which is wrong. Inner join ASSUMES a response exists, but the navigation property reads IsRequired(false). This is also correct - not all incidents have responses, so this field is defined as int? and is not required.

A test code is uploaded. Make a solution, set up references and execute the Test Bug4711. Set a breakpoint so you can see the SQL. Data connection is in but invalid (and not needed, the sql is extracted before the query ever executes). Number is our internal tracking number. All other elements have been removed, so the example is as trivial as it gets.

[CodeBug13883.zip](https://github.com/aspnet/EntityFrameworkCore/files/2593136/CodeBug13883.zip)

This is as easy as it gets.

**Comment by ajcvickers** [comment] 2018-11-19 18:00
Note for triage: query debug output:
```
dbug: Microsoft.EntityFrameworkCore.Query[10104]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      Optimized query model:
      'from OBTIncident x in DbSet<OBTIncident>
      join OBTIncidentResponse x.OBTIncidentResponse in DbSet<OBTIncidentResponse>
      on Property([x], "FkIncidentResponseID") equals (Nullable<int>)Property([x.OBTIncidentResponse], "PkIncidentResponseID")
      select OBTIncident _Include(
          queryContext: queryContext,
          entity: [x],
          included: new object[]{ [x.OBTIncidentResponse] },
          fixup: (QueryContext queryContext | OBTIncident entity | object[] included) =>
          {
              void queryContext.QueryBuffer.StartTracking(
                  entity: entity,
                  entityType: EntityType: OBTIncident)
              return !(bool ReferenceEquals(included[0], null)) ?
              {
                  void queryContext.QueryBuffer.StartTracking(
                      entity: included[0],
                      entityType: EntityType: OBTIncidentResponse)
                  void SetRelationshipSnapshotValue(
                      stateManager: queryContext.StateManager,
                      navigation: OBTIncident.OBTIncidentResponse,
                      entity: entity,
                      value: included[0])
                  return void SetRelationshipSnapshotValue(
                      stateManager: queryContext.StateManager,
                      navigation: OBTIncidentResponse.OBTIncident,
                      entity: included[0],
                      value: entity)
              }
               :
              {
                  void SetRelationshipIsLoaded(
                      stateManager: queryContext.StateManager,
                      navigation: OBTIncident.OBTIncidentResponse,
                      entity: entity)
                  return default(void)
              }

          }
      )'
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      (QueryContext queryContext) => IEnumerable<OBTIncident> _InterceptExceptions(
          source: IEnumerable<OBTIncident> _TrackEntities(
              results: IEnumerable<OBTIncident> _Select(
                  source: IEnumerable<TransparentIdentifier<OBTIncident, OBTIncidentResponse>> _ShapedQuery(
                      queryContext: queryContext,
                      shaperCommandContext: SelectExpression:
                          SELECT [x].[pkIncidentID], [x].[fkIncidentResponseID], [x.OBTIncidentResponse].[pkIncidentResponseID]
                          FROM [dbo].[OB_TIncident] AS [x]
                          INNER JOIN [dbo].[OB_TIncidentResponse] AS [x.OBTIncidentResponse] ON [x].[fkIncidentResponseID] = [x.OBTIncidentResponse].[pkIncidentResponseID],
                      shaper: TypedCompositeShaper<BufferedOffsetEntityShaper<OBTIncident>, OBTIncident, BufferedOffsetEntityShaper<OBTIncidentResponse>, OBTIncidentResponse, TransparentIdentifier<OBTIncident, OBTIncidentResponse>>),
                  selector: (TransparentIdentifier<OBTIncident, OBTIncidentResponse> t0) => OBTIncident _Include(
                      queryContext: queryContext,
                      entity: t0.Outer,
                      included: new object[]{ t0.Inner },
                      fixup: (QueryContext queryContext | OBTIncident entity | object[] included) =>
                      {
                          void queryContext.QueryBuffer.StartTracking(
                              entity: entity,
                              entityType: EntityType: OBTIncident)
                          return !(bool ReferenceEquals(included[0], null)) ?
                          {
                              void queryContext.QueryBuffer.StartTracking(
                                  entity: included[0],
                                  entityType: EntityType: OBTIncidentResponse)
                              void SetRelationshipSnapshotValue(
                                  stateManager: queryContext.StateManager,
                                  navigation: OBTIncident.OBTIncidentResponse,
                                  entity: entity,
                                  value: included[0])
                              return void SetRelationshipSnapshotValue(
                                  stateManager: queryContext.StateManager,
                                  navigation: OBTIncidentResponse.OBTIncident,
                                  entity: included[0],
                                  value: entity)
                          }
                           :
                          {
                              void SetRelationshipIsLoaded(
                                  stateManager: queryContext.StateManager,
                                  navigation: OBTIncident.OBTIncidentResponse,
                                  entity: entity)
                              return default(void)
                          }
                      }
                  )),
              queryContext: Unhandled parameter: queryContext,
              entityTrackingInfos: { itemType: OBTIncident },
              entityAccessors: List<Func<OBTIncident, object>>
              {
                  Func<OBTIncident, OBTIncident>,
              }
          ),
          contextType: BloggingContext,
          logger: DiagnosticsLogger<Query>,
          queryContext: Unhandled parameter: queryContext)
dbug: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [x].[pkIncidentID], [x].[fkIncidentResponseID], [x.OBTIncidentResponse].[pkIncidentResponseID]
      FROM [dbo].[OB_TIncident] AS [x]
      INNER JOIN [dbo].[OB_TIncidentResponse] AS [x.OBTIncidentResponse] ON [x].[fkIncidentResponseID] = [x.OBTIncidentResponse].[pkIncidentResponseID]
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (100ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [x].[pkIncidentID], [x].[fkIncidentResponseID], [x.OBTIncidentResponse].[pkIncidentResponseID]
      FROM [dbo].[OB_TIncident] AS [x]
      INNER JOIN [dbo].[OB_TIncidentResponse] AS [x.OBTIncidentResponse] ON [x].[fkIncidentResponseID] = [x.OBTIncidentResponse].[pkIncidentResponseID]
```

**Comment by NetTecture** [comment] 2018-11-19 20:06
@ajcvickers I hate to tell you, but if you read it again you will see the elationship is NOT redefined.

There are sides:

a: Incident -> IncidentResponse. IncidentResponse is NOT required.
b: IncidentResponse -> Incident IS required.

Translate:
a: No every Incident has a response
b: every response that exists MUST have a valid pointer to an incident.

The requirements are not contrary and according to the code there is no redefinition as source and target are exchanged. This is also part of the db - the pointer right there is from TIncident to TIncidentResponse and the pointer is nullable.

Sorry, basic logic here. No redefinition. TIncident is, in old EF6 terms, the principal that must exist, while the secondary object is optional.

This is old code, and in the meantime I have a refactoring moving the pointer to IncidentResponse, but still this is a problem in expressing this in EfCore.

If anything, it is extremely crappy programming. IF you are right:

> it is then later re-defined as required here:

then this should not be possible and throw an exception. It does not. This makes it, at a minimum, a maintenance and programming nightmare - finding an error is bad if you have zero support for debugging.

**Comment by ajcvickers** [comment] 2018-11-19 20:10
@NetTecture That's not the way that API works. First, the `Required` call does not apply to the navigation property or to one side or other of the relationship; it makes the entire relationship required or not. Second, Code First is, and has always been, last one wins. So if you re-define the same relationship multiple times, then the last one wins.

**Closed** 2022-10-16 13:39 UTC
Labels: closed-could-not-reproduce, customer-reported
