### ISSUE TITLE
EF Core 3.1.4 creates a migration over and over again?

### ISSUE THREAD

**Issue by atmike** [dotnet/efcore#21637] opened 2020-07-15 15:19 UTC
Hi
We have a project where we removed some of the Entities then we performed a add-migration which deleted these entities from the DB. Actually you should only get an empty migration afterwards, but unfortunately EF creates a migration over and over again in which EF tries to delete tables and ForeignKeys that do not exist. Even if I run add-migration 10 times in a row the same script always comes out.

My question is, how can I prevent that EF creates these migrations?

UPDATE:
In the meantime I found out that this problem occurs when we add entities as a view in our context:

`modelBuilder.Entity<DefectCategory>().ToView("MASTER_DEFECTCATEGORY");`

But this applies only to some of the entities we add as views. Some work and some don't, without me being able to see what the difference is.

Thanks for your help

Michael

### Steps to reproduce

What steps can we follow to reproduce the issue?
We have two Solutions. 
In the first one (BaseEntites) we define the Entities and we have a context and the migrations to generate the Database
In Solution two we use the Entities from BaseEntites as Satellites and use ToView to keep them out of the Migrations. 
This worked fine until we updatet from 3.1.0 to 3.1.4 

``` C#
`modelBuilder.Entity<DefectCategory>().ToView("MASTER_DEFECTCATEGORY");`
```

Got Exceptions? Include both the message and the stack trace
=> No exception

For `dotnet ef` and PMC, share the --verbose output
```
add-migration "test5" -verbose 
Using project 'Retrofit.DataAccess'.
Using startup project 'Retrofit.DataAccess'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile "E:\Projects\Formel D\BaseDev\output.bin\netcoreapp3.1\Retrofit.DataAccess.deps.json" --additionalprobingpath C:\Users\MichaelKrösc_avb0nhq\.nuget\packages --additionalprobingpath C:\Microsoft\Xamarin\NuGet --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig "E:\Projects\Formel D\BaseDev\output.bin\netcoreapp3.1\Retrofit.DataAccess.runtimeconfig.json" C:\Users\MichaelKrösc_avb0nhq\.nuget\packages\microsoft.entityframeworkcore.tools\3.1.4\tools\netcoreapp2.0\any\ef.dll migrations add test5 --json --verbose --no-color --prefix-output --assembly "E:\Projects\Formel D\BaseDev\output.bin\netcoreapp3.1\Retrofit.DataAccess.dll" --startup-assembly "E:\Projects\Formel D\BaseDev\output.bin\netcoreapp3.1\Retrofit.DataAccess.dll" --project-dir "E:\Projects\Formel D\BaseDev\eApps.Retrofit\Retrofit.DataAccess\\" --language C# --working-dir "E:\Projects\Formel D\BaseDev\eApps.Retrofit" --root-namespace Retrofit.DataAccess
Using assembly 'Retrofit.DataAccess'.
Using startup assembly 'Retrofit.DataAccess'.
Using application base 'E:\Projects\Formel D\BaseDev\output.bin\netcoreapp3.1'.
Using working directory 'E:\Projects\Formel D\BaseDev\eApps.Retrofit\Retrofit.DataAccess'.
Using root namespace 'Retrofit.DataAccess'.
Using project directory 'E:\Projects\Formel D\BaseDev\eApps.Retrofit\Retrofit.DataAccess\'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'RetrofitDbContextFactory'.
Found DbContext 'RetrofitDbContext'.
Finding application service provider...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'RetrofitDbContextFactory'.
Using context 'RetrofitDbContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'Retrofit.DataAccess'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'Retrofit.DataAccess'...
No design-time services were found.
DetectChanges starting for 'RetrofitDbContext'.
DetectChanges completed for 'RetrofitDbContext'.
DetectChanges starting for 'RetrofitDbContext'.
DetectChanges completed for 'RetrofitDbContext'.
DetectChanges starting for 'RetrofitDbContext'.
DetectChanges completed for 'RetrofitDbContext'.
DetectChanges starting for 'RetrofitDbContext'.
DetectChanges completed for 'RetrofitDbContext'.
An operation was scaffolded that may result in the loss of data. Please review the migration for accuracy.
Writing migration to 'E:\Projects\Formel D\BaseDev\eApps.Retrofit\Retrofit.DataAccess\Migrations\20200715151106_test5.cs'.
Writing model snapshot to 'E:\Projects\Formel D\BaseDev\eApps.Retrofit\Retrofit.DataAccess\Migrations\RetrofitDbContextModelSnapshot.cs'.
'RetrofitDbContext' disposed.
To undo this action, use Remove-Migration.
```

### Further technical details

EF Core version: 3.1.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windwos 10 1903
IDE: Visual Studio 2019 16.5.4

**Comment by ErikEJ** [comment] 2020-07-15 15:46
Add HasNoKey() ??

**Comment by smitpatel** [comment] 2020-07-17 17:40
Duplicate of #21165

**Comment by atmike** [comment] 2020-07-17 20:55
> Add HasNoKey() ??
@ErikEJ thank you for you answer but I'm not sure that this is a correct solution. When I add HasNoKey() I get the following Exception because he can't build the Relation!?!?!

`Unable to determine the relationship represented by navigation property 'CustomerDefectCategory.DefectCategory' of type 'DefectCategory'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
`
@smitpatel I had a look add #21165 but I do not see why this has something to do with my Problem!?!? so can you please reopen this case again?

Regards
Michael

**Comment by smitpatel** [comment] 2020-07-17 21:48
@atmike - We believe that this issue is duplicate of the other based on the root cause that keyless entity types were not scaffolded in model snapshot which caused relationship between keyless entity and keyed entity to be generate same migration repeatedly.
Please try nightly builds which contains fix for duplicated issue, if you still see issue in nightly builds then provide us a repro code so that we can investigate.

**Comment by atmike** [comment] 2020-07-20 08:08
@smitpatel Thanks for the info!
can you tell me where I can find the nuget source for the nightly build? The only source I could find was https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.json
and there the builds stops at Version 3.1.1 and go on with 5.0.0-alpha...

![image](https://user-images.githubusercontent.com/22487185/87914258-ab75e680-ca70-11ea-9806-2d413f20d198.png)

Thanks for your help
Michael

**Comment by smitpatel** [comment] 2020-07-20 14:56
This article will help. https://github.com/dotnet/aspnetcore/blob/master/docs/DailyBuilds.md

**Closed** 2022-10-16 18:33 UTC
Labels: customer-reported
