### ISSUE TITLE
StackoverflowException on generating Migrations

### ISSUE THREAD

**Issue by markusvt** [dotnet/efcore#7609] opened 2017-02-14 09:07 UTC
I got the following model:

A main class called 'Item' and 3 Subclasses 'Media', 'Folder', 'Symlink' that are Subclasses of Item. I need to create a 1-to-many relation between Symlink and Item, so that one Symlink has 1 'LinkedItem' and an Item has a list of 'Symlinks'.

My Code of Item:
```
[Table("Cloud_ItemSet")]
public class Item : IEntity
{
        public long Id { get; set; }
        .....
        [InverseProperty("LinkedItem")]
        public virtual ICollection<Symlink> Symlinks { get; set; } = new HashSet<Symlink>();
}
```

And Code of Symlink:
```
public class Symlink : Item
{
        public int Action { get; set; } = 0;

        [ForeignKey("LinkedItem_Id")]
        public virtual Item LinkedItem { get; set; }
        public long? LinkedItem_Id { get; set; }
}
```

When I generate the migration file with 'dotnet ef migrations add Test', after a while a Stackoverflow Exception occurs and a dialogue "ef isn't working anymore" appears.

Maybe what also is interesting: i got a 1-to-many relationship between Item and Folder to (so that 1 Folder can have many Items, and 1 Item has 1 Folder, a normal composition pattern for that). 
Mapping that Relationship works without problem, only the other direction like in Symlink doesnt work.

Also: If I remove the `[InverseProperty("LinkedItem")]` Attribute and add a `[NotMapped]` to the Symlinks-Collection, generating the migration file works again.

Edit: I just saw: if i change the 'Symlinks' Collection in Item to `private ICollection<Symlink> Symlinks { get; set; } = new HashSet<Symlink>();` it works also with the `[InverseProperty("LinkedItem")]`Attribute

**Comment by rowanmiller** [comment] 2017-02-14 19:07
Can you confirm what version of EF Core you are using? We think we may have already fixed this.

**Comment by bricelam** [comment] 2017-02-14 19:37
The bug I thought it could be (#3799) was fixed in 1.0.0-rc2, so it's probably a different issue.

**Comment by markusvt** [comment] 2017-02-14 20:29
i am using EF Core 1.1
here from my project.json file:
```
  "Microsoft.EntityFrameworkCore": "1.1.0",
  "Microsoft.EntityFrameworkCore.Design": "1.1.0",
  "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
  "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
   ```

**Comment by markusvt** [comment] 2017-02-15 07:45
maybe if it helps: i got the same problem on another entity that doesnt have any inheritance:
there is a class called "User" and another class called "CloudUser", and there is a 1-to-1 relationship between them.
When I model a normal foreign-key / inverseProperty relationship, that stackoverflow occurs. Also when I let the InverseProperty stay 'public virtual' with a  [NotMapped] Attribute the Exception occurs. I needed to make the property 'private' so that it worked

**Comment by AndriySvyryd** [comment] 2017-02-15 19:47
This is likely dupe of https://github.com/aspnet/EntityFramework/issues/7057

**Comment by AndriySvyryd** [comment] 2017-06-02 22:47
Doesn't repro in 2.0.0

**Closed** 2022-10-16 10:53 UTC
Labels: closed-could-not-reproduce
