### ISSUE TITLE
ICollection<T> doesn't translate to SQL

### ISSUE THREAD

**Issue by jirkafajfr** [dotnet/efcore#18639] opened 2019-10-29 16:58 UTC
When `ICollection<T>` is used in `Where(...)` it does not generate proper SQL query and crashes with request for query rewrite.

### Steps to reproduce

I've created following repo https://github.com/jirkafajfr/EfCore-CollectionInExpressionProblem which demonstrates the problem. Essentially when `ICollection<T>` comes to the expression it can't be translated where array or list would work just fine. 

#### Crashes
```C#
ICollection<int> ids = new List<int>
{
    1,
    2
};

_context.Blogs
    .Where(post => ids.Contains(post.BlogId))
    .Should()
    .NotBeEmpty();
```

```
System.InvalidOperationException : The LINQ expression 'Where<Blog>(
    source: DbSet<Blog>, 
    predicate: (b) => (Unhandled parameter: __ids_0).Contains(b.BlogId))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

#### Works fine

```C#
var ids = new List<int>
{
    1,
    2
};

_context.Blogs
    .Where(post => ids.Contains(post.BlogId))
    .Should()
    .NotBeEmpty();
```

### Notes

The attached repo demonstrates that this used to work in _EfCore 2.2_ but is not broken with _EfCore 3.0_

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.Sqlite, Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET Core 3.0
Operating system: Windows 10, Linux (attached docker)
IDE: Visual Studio 2019 16.3

**Comment by ajcvickers** [comment] 2019-10-29 17:31
Duplicate of #17342. Verified tests are passing with latest [daily build](https://docs.microsoft.com/en-us/ef/core/).

**Closed** 2022-10-16 14:53 UTC
Labels: customer-reported
