### ISSUE TITLE
Returning Action result with no content gives 500 response error

### ISSUE THREAD

**Issue by CutieDaisy** [dotnet/efcore#22436] opened 2020-09-07 14:04 UTC
### Describe the bug
After updating to ASP.NET Core version 5.0.0-preview 8, 
when an action result with no content is returned I get a 500 response error

### To Reproduce
`  [HttpGet]
        public IActionResult Get()
        {
            return Ok(); // with no object returned;
           // return NoContent();
        }`

### Exceptions (if any)
Browser Response : Status Code: 500 Internal 

### Further technical details
- ASP.NET Core version 5.0.0-preview.8
- Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 
- Microsoft Visual Studio Enterprise 2019 Preview
   Version 16.8.0 Preview 2.1

**Comment by roji** [comment] 2020-09-07 21:36
There's no code provided in this issue, please submit a minimal, runnable code sample that reproduces your issue so we can investigate it.

**Comment by AndriySvyryd** [comment] 2020-09-07 23:39
Duplicate of https://github.com/dotnet/efcore/issues/22255

**Closed** 2022-10-16 18:39 UTC
Labels: closed-duplicate, customer-reported
