### ISSUE TITLE
ValueObject == null, Property could not be translated

### ISSUE THREAD

**Issue by TheBekker** [dotnet/efcore#31593] opened 2023-08-30 18:23 UTC
I've setup EF Core with Cosmos DB and really its been working pretty well.
But now having to do some more specific queries other then just getting data based on ID's, i'm running into issues.

What I have setup:

```C#
//DB Set
public DbSet<ClnkEvent> ClnkEvents => Set<ClnkEvent>();

//Models builder
modelBuilder.Entity<ClnkEvent>()
    .ToContainer(EventContainerConfig.ContainerName)
    .HasPartitionKey(x => x.EventId)
    .HasKey(x => x.Key);

modelBuilder.Entity<ClnkEvent>()
    .Property(x => x.Key)
    .HasValueGenerator<DiscriminatorAndGuidValueGenerator>()
    .ToJsonProperty("id");

modelBuilder.Entity<ClnkEvent>()
    .Property(x => x.LastModified)
    .ToJsonProperty("_ts");

//Entity
//BaseEntity has Key (string) and LastModified (DateTime)
//There are value converters setup for the two strongly typed ids (EventId & CreatorId)
public class ClnkEvent : BaseEntity
{
    public ClnkEventId EventId { get; set; }
    public UserProfileId CreatorId { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset UpdatedAt { get; set; }
    public DateTimeOffset VotingEndsAt { get; set; }
    public WhenOption? When { get; set; }
    public WhereOption? Where { get; set; }
    public ICollection<WhereOption> WhereOptions { get; set; } = new List<WhereOption>();
    public ICollection<WhenOption> WhenOptions { get; set; } = new List<WhenOption>();
}

//Value Obejcts
public class WhereOption : ValueObject
{
    public Guid VenueId { get; private set; }
    public override IEnumerable<object?> GetEqualityComponents()
    {
        yield return VenueId;
    }

    public static WhereOption Create(Guid venueId)
    {
        return new WhereOption()
        {
            VenueId = venueId
        }; 
    }

    private WhereOption(){}
}

public class WhenOption : ValueObject
{
    public DateTimeOffset Timestamp { get; private set; }
    public override IEnumerable<object?> GetEqualityComponents()
    {
        yield return Timestamp;
    }

    public static WhenOption Create(DateTimeOffset timestamp)
    {
        var whenOption = new WhenOption()
        {
            Timestamp = timestamp
        };
        return whenOption;
    }

    private WhenOption(){}
}

//Baseclase
public abstract class ValueObject : IEquatable<ValueObject>
{
    public abstract IEnumerable<object?> GetEqualityComponents();

    public override bool Equals(object? obj)
    {
        if (obj is null || obj.GetType() != GetType())
        {
            return false;
        }

        var valueObject = (ValueObject)obj;

        return GetEqualityComponents()
            .SequenceEqual(valueObject.GetEqualityComponents());
    }

    public static bool operator ==(ValueObject? left, ValueObject? right)
    {
        return Equals(left, right);
    }

    public static bool operator !=(ValueObject? left, ValueObject? right)
    {
        return !Equals(left, right);
    }

    public override int GetHashCode()
    {
        return GetEqualityComponents()
            .Select(x => x?.GetHashCode() ?? 0)
            .Aggregate((x, y) => x ^ y);
    }

    public bool Equals(ValueObject? other)
    {
        return Equals((object?)other);
    }
}

```

Now with this setup I write a simple LINQ where query:

```C#
var clnkEvents = await _applicationDbContext.ClnkEvents
    .Where(x =>
        x.Where == null
        && x.When == null
    )
    .OrderBy(x => x.UpdatedAt)
    .Take(1000) //Limit the workload
    .ToListAsync();
```

I then get the following error:

```
Exception: System.AggregateException: One or more errors occurred. (The LINQ expression 'DbSet<ClnkEvent>()
        .Where(c => EF.Property<WhereOption>(c, "Where") == null && EF.Property<WhenOption>(c, "When") == null)' could not be translated. Additional information: Translation of member 'Key' on entity type 'ClnkEvent.Where#WhereOption' failed. This commonly occurs when the specified member is unmapped.
    Translation of member 'Key' on entity type 'ClnkEvent.When#WhenOption' failed. This commonly occurs when the specified member is unmapped. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.)
    ---> System.InvalidOperationException: The LINQ expression 'DbSet<ClnkEvent>()
        .Where(c => EF.Property<WhereOption>(c, "Where") == null && EF.Property<WhenOption>(c, "When") == null)' could not be translated. Additional information: Translation of member 'Key' on entity type 'ClnkEvent.Where#WhereOption' failed. This commonly occurs when the specified member is unmapped.
    Translation of member 'Key' on entity type 'ClnkEvent.When#WhenOption' failed. This commonly occurs when the specified member is unmapped. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
    at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosQueryableMethodTranslatingExpressionVisitor.Visit(Expression expression)
    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
    at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosQueryableMethodTranslatingExpressionVisitor.Visit(Expression expression)
    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
    at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosQueryableMethodTranslatingExpressionVisitor.Visit(Expression expression)
    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
    at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosQueryableMethodTranslatingExpressionVisitor.Visit(Expression expression)
    at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
    at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
```

Env. info:

EF Core version: 7.0.7
Database provider: Microsoft.EntityFrameworkCore.Cosmos 
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Microsoft Visual Studio 2022 17.6.6

**Comment by ajcvickers** [comment] 2023-09-13 17:16
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate. In particular, there is no code showing the `Key` property and how it is configured and used.

**Comment by ajcvickers** [comment] 2023-10-01 11:12
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-10-01 11:12 UTC
Labels: customer-reported
