### ISSUE TITLE
Flaky test: Create_checks_for_existence_and_retries_if_cannot_open_file_until_it_passes

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/efcore#12781] opened 2018-07-24 23:26 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=513808&buildTypeId=XPlat_Windows_Win2008r2_Universe) occasionally with the following error:
```
System.ArgumentException : Keyword not supported: 'PoolBlockingPeriod'.
   at System.Data.SqlClient.SqlConnectionStringBuilder.Reset(Keywords index)
   at System.Data.SqlClient.SqlConnectionStringBuilder.Clear()
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.CreateCreateOperations() in /_/src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs:line 110
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Create() in /_/src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs:line 61
   at Microsoft.EntityFrameworkCore.SqlServerDatabaseCreatorTest.<Create_checks_for_existence_and_retries_until_it_passes>d__10.MoveNext() in /_/test/EFCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by ryanbrandenburg** [comment] 2018-07-24 23:31
Create_checks_for_existence_and_retries_if_cannot_attach_file_until_it_passes [failed again](http://aspnetci/viewLog.html?buildId=513798&buildTypeId=XPlat_Windows_Win10Universe).

**Comment by ryanbrandenburg** [comment] 2018-07-24 23:36
Create_checks_for_existence_and_retries_if_no_proccess_until_it_passes [failed again](http://aspnetci/viewLog.html?buildId=513800&buildTypeId=XPlat_Windows_Win7_Universe).

**Comment by smitpatel** [comment] 2018-07-24 23:37
Duplicate of #12706

**Comment by smitpatel** [comment] 2018-07-24 23:37
It is not test issue. It is infra issue. Please avoid creating duplicated issues.

**Comment by ryanbrandenburg** [comment] 2018-07-25 18:30
The above was all done by a bot (I'm going to add messages letting people know that soon, and preferably had the bot show as a different account). The bot makes an effort to recognize and group similar issues, but does so based on exception messages. So when the messages are different enough it creates different issues.

That all said, this IS a test issue because it fails the tests. If we can't fix these tests at the moment for whatever reason then the thing to do is to skip them.

CC @ajcvickers in case he wants to weight in.

**Closed** 2022-10-16 13:21 UTC
