### ISSUE TITLE
SqlServer FillFactor for PK is missing

### ISSUE THREAD

**Issue by bryanhunwardsen** [dotnet/efcore#32803] opened 2024-01-12 20:08 UTC
"FillFactor" was added several versions ago but it is incomplete/broken.
.HasFillFactor() is only settable on explicit/defined Indexes.
In SqlServer, FillFactor can be set on the PK without additional complexity to the Schema.
This is not available with the FillFactor implementation of EFC 8. 
This is an incomplete implementation of the feature which is why I am filing as a bug and not as a feature request.

To advertise FillFactor is supported in EF, code like this:
```C#
builder.HasKey(x => x.Id).HasFillFactor(90);
```
Should produce Sql Schema as:
```sql
CREATE TABLE [dbo].[MyTable](
	[Id] [int] IDENTITY(1,1) NOT NULL
 CONSTRAINT [PK_MyTable] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
```

or at a minimum, provide a fluent option that ultimately executes the following sql as it will cover the PK:
```sql
ALTER TABLE MyTable REBUILD WITH (FILLFACTOR = 90);
GO
```

EF Core version: 8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Win10
IDE: Visual Studio 2022 17.4

**Comment by roji** [comment] 2024-01-12 21:52
Yeah, this makes sense. For now, you can insert the ALTER TABLE SQL directly in your migrations to work around this.

**Comment by bryanhunwardsen** [comment] 2024-01-13 13:44
> Yeah, this makes sense. For now, you can insert the ALTER TABLE SQL directly in your migrations to work around this.

Unfortunately this is not the case, if the migration epoch is reset, or just rolled back/deleted and regenerated, these changes are lost, would have to be manually reapplied, and are therefore not sufficiently durable. (This is exactly the use case I am addressing currently)

I was able to implement a custom CSharpMigrationOperationGenerator that injects the FillFactor sql script into into the migration Up for each TableCreate and TableAlter Up operations, it is oversimplified, heavy handed, and fragile. Still would prefer a proper fluent implementation from EFCore.

**Comment by roji** [comment] 2024-01-13 13:51
> Unfortunately this is not the case, if the migration epoch is reset, or just rolled back/deleted and regenerated, these changes are lost, would have to be manually reapplied, and are therefore not sufficiently durable. (This is exactly the use case I am addressing currently)

That's true, but this amounts to saying that SQL can never be used in migrations; we're unfortunately unable to provide built-in migration support for each and every supported feature of all databases out there - there's far too many, and modeling all the possibilities of all DDL variants is simply unfeasible.

I do agree we should implement this (after all we do have it for indexes) - I'm just saying that it's unlikely to be prioritized. It's also not an very difficult thing to do, if you're interested in contributing it./

**Comment by deano-hunter** [comment] 2024-01-19 16:29
I would be interested in picking this up as a first issue.

It looks like adding the WITH options and including FILLFACTOR for primary keys to the SQL Generators is what is needed so that HasFillFactor can be used with key properties.

Looking through the code, this looks relatively straight forward.  While there will be a few changes to handle adding the [FillFactor](https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs) constant for primary keys, the main code will be in the [SqlServerMigrationsSqlGenerator](https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs), [SqlServerKeyExtensions](https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Extensions/SqlServerKeyExtensions.cs), [SqlServerKeyBuilderExtensions](https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Extensions/SqlServerKeyBuilderExtensions.cs) classes.

**Comment by bryanhunwardsen** [comment] 2024-01-19 19:02
> I would be interested in picking this up as a first issue.
> 
> It looks like adding the WITH options and including FILLFACTOR for primary keys to the SQL Generators is what is needed so that HasFillFactor can be used with key properties.
> 
> Looking through the code, this looks relatively straight forward. While there will be a few changes to handle adding the [FillFactor](https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs) constant for primary keys, the main code will be in the [SqlServerMigrationsSqlGenerator](https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs), [SqlServerKeyExtensions](https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Extensions/SqlServerKeyExtensions.cs), [SqlServerKeyBuilderExtensions](https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Extensions/SqlServerKeyBuilderExtensions.cs) classes.

Please note, .HasAlternateKey() should be included with this work to fill the gap to a complete feature.

**Comment by ajcvickers** [comment] 2024-01-22 12:03
@deano-hunter Sounds good; go for it!

**Closed** 2024-02-16 09:10 UTC
Labels: type-enhancement, customer-reported, good first issue, area-migrations, area-sqlserver

**Comment by wexman** [comment] 2024-12-11 13:30
Just so i get it right: the scaffold command generates this code although it is not implemented? Leaving me with an unusable DbContext that does not compile?

**Comment by roji** [comment] 2024-12-11 18:39
@wexman I'm not aware of EF scaffolding this code - is this something you're seeing?

**Comment by wexman** [comment] 2024-12-12 07:49
@roji yes - I've been using `dotnet ef dbcontext scaffold` to import and old (ancient?) sql server database and it generated HasFillFactor(90) on 82 primary keys, generating 82 compile errors...

**Comment by ErikEJ** [comment] 2024-12-12 08:05
@wexman Which EF Core version do you target at runtime?

**Comment by wexman** [comment] 2024-12-12 08:25
@ErikEJ I'm using 8.0.11

**Comment by roji** [comment] 2024-12-18 15:29
@wexman I gave this a try; when using EF 8.0.11, EF does not scaffold HasFillFactor() on the key for me - double-check exactly which version you're referencing when scaffolding. When i reference EF 9.0, I can see HasFillFactor() getting scaffolded, and that works correctly when creating a new databases, as expected.

If you're still having troubles with this, please open a new issue with detailed instructions on how to reproduce the error.

**Comment by wexman** [comment] 2025-01-07 14:09
@roji just coming back to this after the new year's holidays...

What versions do you need exactly? `dotnet ef --version` outputs 8.0.3

**Comment by roji** [comment] 2025-01-07 14:10
What version of EF (specifically the Design package) does your csproj reference)?

**Comment by wexman** [comment] 2025-01-07 14:24
Hmm, that is 8.0.11...

**Comment by roji** [comment] 2025-01-07 19:58
@wexman OK, if you manage to reproduce, please open a new issue with the minimal repro and we'll investigate. In the meantime I'll minimize the comments here.
