### ISSUE TITLE
dotnet ef --update-database “Microsoft.DotNet.Cli.Utils.dll” exception

### ISSUE THREAD

**Issue by skorunka** [dotnet/efcore#5934] opened 2016-07-01 12:34 UTC
I got this exception:

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.Cli.Utils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)

after executing "dotnet ef --update-database"

dotnet --info :

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:

Version: 1.0.0-preview2-003121

Commit SHA-1 hash: 1e9d529bc5

Runtime Environment:

OS Name: Windows

OS Version: 10.0.10586

OS Platform: Windows

RID: win10-x64

project.json

{
    "buildOptions": {
        "emitEntryPoint": true
    },
    "dependencies": {
        "Microsoft.AspNetCore.Hosting.Abstractions": "1.0.0",
        "Microsoft.AspNetCore.Http.Abstractions": "1.0.0",
        "Microsoft.EntityFrameworkCore": "1.0.0",
        "Microsoft.EntityFrameworkCore.Relational": "1.0.0",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
        "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.0",
        "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
        "Microsoft.Extensions.Configuration": "1.0.0",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
        "Microsoft.Extensions.Configuration.Json": "1.0.0",
        "Microsoft.DotNet.Cli.Utils": "1.0.0-preview2-003121"
    },
    "frameworks": {
        "net461": {}
    },
    "runtimes": {
        "win-anycpu": {}
    },
    "tools": {
        "Microsoft.EntityFrameworkCore.Tools": {
            "version": "1.0.0-preview2-final",
            "imports": [
                "portable-net452+win81"
            ]
        }
    }
}

Any idea? thank you.

**Comment by natemcmaster** [comment] 2016-07-01 12:56
This is likely a duplicate of https://github.com/aspnet/EntityFramework/issues/5886. Remove "imports". Clear your caches and try installing again. (see https://github.com/aspnet/EntityFramework/issues/5458#issuecomment-221912806).

cross-ref https://github.com/dotnet/cli/issues/2978

**Comment by skorunka** [comment] 2016-07-01 14:29
Cheers.

**Comment by fszakka** [comment] 2016-07-09 07:09
how to clear the caches

**Closed** 2022-10-16 09:48 UTC
Labels: closed-duplicate
