### ISSUE TITLE
EFCore.InMemory - Key does not get auto-incremented upon adding new item

### ISSUE THREAD

**Issue by babak-f** [dotnet/efcore#13400] opened 2018-09-24 10:36 UTC
I'm using an in-memory EF database. 

I populate the entity table for cars with 5 items (seeded from an external file). On these items, I specify the ID (primary key) explicitly. 

Then when I try to add a new item without specifying the ID, it tries to add the item with an ID of 1, instead of 6. It clearly results in a conflict (exception - see below), since there is already an element with ID of 1. 

In other words, the library cannot detect that there are already items in the table with IDs 1 to 5, and that the ID it has to assign to the next element (auto-increment) should be 6, not 1. 

I don't have this problem when I use the same exact code with an MS SQL database. 

```
Exception message: System.ArgumentException : An item with the same key has already been added. Key: 1
Stack trace:
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.Create(IUpdateEntry entry)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryStore.ExecuteTransaction(IReadOnlyList`1 entries, IDiagnosticsLogger`1 updateLogger)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
```

### Steps to reproduce
1. Create model classes and configure the DB context as shown below: 

```c#
public class Car {
	public int Id { get; set; }
	public string Name { get; set; }
	public string Description { get; set; }
}

public class ApplicationDbContext : DbContext
{
	public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
		: base(options)
	{
	}

	protected override void OnModelCreating(ModelBuilder builder)
	{
		base.OnModelCreating(builder);
	}

	public virtual DbSet<Car> Cars { get; set; }
}

public class InMemoryApplicationDbContext : ApplicationDbContext
{
	public InMemoryApplicationDbContext(string dbName)
		: base(new DbContextOptionsBuilder<ApplicationDbContext>()
			.UseInMemoryDatabase(dbName)
			.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking)
			.Options) { }
}
```

2. Populate `ApplicationDbContext.Cars` using 5 elements (for example) by using the the snippet below (for IDs 1 through 5): 
```c#
var car = new Car
{
	Id = 1,
	Name = "Car 1", 
	Description = "Test car"
};
_context.Cars.Add(car);
_context.SaveChanges();
```

3. Run the `InsertTestCar` method from the class below. 
```c#
public class CarRepository
{
	private readonly ApplicationDbContext _context;

	public CarRepository(ApplicationDbContext context)
	{
		_context = context;
	}

	public void InsertTestCar()
	{
		var car = new Car
		{
			Name = "Test", 
			Description = "Test"
		};
		_context.Cars.Add(car);
		_context.SaveChanges(); // Exception thrown here
	}
}
```

### Further technical details
EF Core version: 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10
IDE: Visual Studio Pro 2017 15.8.3

**Comment by ajcvickers** [comment] 2018-09-24 17:50
Duplicate of #6872

**Closed** 2022-10-16 13:32 UTC
Labels: closed-duplicate, customer-reported
