### ISSUE TITLE
Query generated for CosmosDB has syntax error for $select

### ISSUE THREAD

**Issue by yan0lovesha** [dotnet/efcore#20885] opened 2020-05-08 04:32 UTC
When use OData with CosmosDB through EntityFramework, and the request contains $select clause, the generated CosmosDB query has syntax error. $select is a very basic usage of OData. So this basically makes OData with CosmosDb doesn't work.

### Steps to reproduce
1. Setup a WebApi project that uses OData, EFCore and CosmosDB. 
2. Do a query contains $select=prop1. 
3. Error will be returned.

The error detail is like: Syntax error, incorrect syntax near 'Value'. 

I debugged into the code. The CosmosDB query generated by Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.QuerySqlGenerator is like below:

SELECT "d45f9d5d-2edf-4c11-93e7-7e034515f319" AS ModelID, "Name" AS Name, c["Name"] AS **Value**, "Id" AS Name0, c["Id"] AS Value0
FROM root c
WHERE (c["Discriminator"] = "TodoItem")
ORDER BY c["Id"]
OFFSET 0 LIMIT 1000

This query is using “Value" as an alias. But Value is reserved by CosmosDB. Syntax error happened.

#### Possible Suggestions
1: Do not use NamedPropertyWithNext0 to build the Expression.
2: Don't generate query like that. Generate query like below. It allows to output Value as a field name:
SELECT VALUE {
    "ModelID": "d45f9d5d-2edf-4c11-93e7-7e034515f319",
    "Name": "Name",
    "Value": c["Name"],
    "Name0": "Id",
    "Value0": c["Id"]
}
FROM root c
WHERE (c["Discriminator"] = "TodoItem")
ORDER BY c["Id"]
OFFSET 0 LIMIT 1000

### Further technical details

EF Core version: 3.1.3
Database provider: (e.g. Microsoft.EntityFrameworkCore.Cosmos)
Target framework: (e.g. .NET Core 3.1)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.5.4)

**Comment by smitpatel** [comment] 2020-05-08 04:55
Duplicate of #20557

**Closed** 2022-10-16 18:24 UTC
Labels: customer-reported
