### ISSUE TITLE
_MigrationHistory is not created in Database, when specifying the Schema

### ISSUE THREAD

**Issue by TheRealLenon** [dotnet/efcore#23644] opened 2020-12-09 22:44 UTC
When specifying an Schema other then the default ``dbo`` on the latest MSSQL-Docker-Image there is no _MigrationHistory table created in the whole database.

The Migration as well as the ModelSnapshot are containing the ``migrationBuilder.EnsureSchema(name: "KoIdentity");`` and ``modelBuilder.HasDefaultSchema("KoIdentity")``.

The Database itself only contains in the desired Schema only the Users & VerificationCodes table.

The DbContext:
```C#
	public class KoIdentityDbContext: DbContext
	{
		public KoIdentityDbContext(){}
		
		public KoIdentityDbContext(DbContextOptions<KoIdentityDbContext> options): base(options){}

		#region Required

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			modelBuilder.HasDefaultSchema("KoIdentity");
		}

		#endregion
		
		public DbSet<KoUser> 				Users 				{ get; set; }
		public DbSet<KoVerificationCodes> 	VerificationCodes	{ get; set; }
	}
```

### The Output when adding migration & updating database
```
C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api>dotnet ef migrations add InitialCreate --verbose
Using project 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\KoIdentity.Api.csproj'.
Using startup project 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\KoIdentity.Api.csproj'.
Writing 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\obj\KoIdentity.Api.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\pko\AppData\Local\Temp\tmp7055.tmp /verbosity:quiet /nologo C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\KoIdentity.Api.csproj
Writing 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\obj\KoIdentity.Api.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\pko\AppData\Local\Temp\tmp7576.tmp /verbosity:quiet /nologo C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\KoIdentity.Api.csproj
Build started...
dotnet build C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\KoIdentity.Api.csproj /verbosity:quiet /nologo

Der Buildvorgang wurde erfolgreich ausgeführt.
    0 Warnung(en)
    0 Fehler

Verstrichene Zeit 00:00:02.92
Build succeeded.
dotnet exec --depsfile C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\bin\Debug\net5.0\KoIdentity.Api.deps.json --additionalprobingpath C:\Users\pko\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\bin\Debug\net5.0\KoIdentity.Api.runtimeconfig.json C:\Users\pko\.dotnet\tools\.store\dotnet-ef\5.0.0\dotnet-ef\5.0.0\tools\netcoreapp3.1\any\tools\net
coreapp2.0\any\ef.dll migrations add InitialCreate --assembly C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\bin\Debug\net5.0\KoIdentity.Api.dll --startup-assembly C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\bin\Debug\net5.0\KoIdentity.Api.dll --project-dir C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\ --language C# --working-dir C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api --verbose --root-namespace KoIdentity.Api
Using assembly 'KoIdentity.Api'.
Using startup assembly 'KoIdentity.Api'.
Using application base 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\bin\Debug\net5.0'.
Using working directory 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api'.
Using root namespace 'KoIdentity.Api'.
Using project directory 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'KoIdentity.Api'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Found DbContext 'KoIdentityDbContext'.
Finding DbContext classes in the project...
Using context 'KoIdentityDbContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'KoIdentity.Api'...
Finding design-time services referenced by assembly 'KoIdentity.Api'...
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'KoIdentity.Api'...
No design-time services were found.
Writing migration to 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\Migrations\20201209223622_InitialCreate.cs'.
Writing model snapshot to 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\Migrations\KoIdentityDbContextModelSnapshot.cs'.
Done. To undo this action, use 'ef migrations remove'

C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api>dotnet ef database update --verbose
Using project 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\KoIdentity.Api.csproj'.
Using startup project 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\KoIdentity.Api.csproj'.
Writing 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\obj\KoIdentity.Api.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\pko\AppData\Local\Temp\tmpB9E1.tmp /verbosity:quiet /nologo C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\KoIdentity.Api.csproj
Writing 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\obj\KoIdentity.Api.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\pko\AppData\Local\Temp\tmpBE28.tmp /verbosity:quiet /nologo C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\KoIdentity.Api.csproj
Build started...
dotnet build C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\KoIdentity.Api.csproj /verbosity:quiet /nologo

Der Buildvorgang wurde erfolgreich ausgeführt.
    0 Warnung(en)
    0 Fehler

Verstrichene Zeit 00:00:02.42
Build succeeded.
dotnet exec --depsfile C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\bin\Debug\net5.0\KoIdentity.Api.deps.json --additionalprobingpath C:\Users\pko\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\bin\Debug\net5.0\KoIdentity.Api.runtimeconfig.json C:\Users\pko\.dotnet\tools\.store\dotnet-ef\5.0.0\dotnet-ef\5.0.0\tools\netcoreapp3.1\any\tools\net
coreapp2.0\any\ef.dll database update --assembly C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\bin\Debug\net5.0\KoIdentity.Api.dll --startup-assembly C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\bin\Debug\net5.0\KoIdentity.Api.dll --project-dir C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\ --language C# --working-dir C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api --verbose --root-namespace KoIdentity.Api
Using assembly 'KoIdentity.Api'.
Using startup assembly 'KoIdentity.Api'.
Using application base 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\bin\Debug\net5.0'.
Using working directory 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api'.
Using root namespace 'KoIdentity.Api'.
Using project directory 'C:\Users\pko\_dev\Personal\KoIdentity\src\KoIdentity.Api\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'KoIdentity.Api'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Found DbContext 'KoIdentityDbContext'.
Finding DbContext classes in the project...
Using context 'KoIdentityDbContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'KoIdentity.Api'...
Finding design-time services referenced by assembly 'KoIdentity.Api'...
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'KoIdentity.Api'...
No design-time services were found.
Done.

```

### Include provider and version information

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: The command is run by the cmd / Git Bash

**Comment by ajcvickers** [comment] 2020-12-11 19:27
@TheRealLenon The Migrations history table always stays in `dbo` by default so that it can always be found. However, you can change this; see the docs here: https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/history-table

**Comment by ajcvickers** [comment] 2020-12-11 20:24
@TheRealLenon Sorry for missing that. Can you please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by TheRealLenon** [comment] 2020-12-11 22:58
The following Code should work. Since i´m not aware on how to attach whole projects.

Please be aware, that i used the Docker-MSSQL Database(If it is important). 
I used the following docker command to create it:
```
docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Secure' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest
```
Instructions can be found [here](https://hub.docker.com/_/microsoft-mssql-server)

I refer to the Schema name: ``TestSchema``

Also include the ``ConnectionString`` to the appsettings.json
```
  "ConnectionStrings": {
    "LOCAL": "SERVER=localhost,1433;Database=KoDev;User=sa;Password=Secure;"
  }
```

The **Data Project**, which includes the following dependencies:
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.1" />
    </ItemGroup>

</Project>
```
Here are the Data Files:
```cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Data;
using Microsoft.EntityFrameworkCore;

namespace Data
{
	[Table("User")]
	public class KoUser
	{
		[Key] 		public Guid 	Id 				{ get; set; }
		
		[Required]	public string 	Username 		{ get; set; }
	}
}

namespace DatabaseContextNamespace
{
	public class TestDbContext: DbContext
	{
		public TestDbContext(){}
		public TestDbContext(DbContextOptions<TestDbContext> options): base(options){}

		#region Required
		
		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			modelBuilder.HasDefaultSchema("TestSchema");
		}

		#endregion
		
		public DbSet<KoUser> 				Users 				{ get; set; }
	}
}
```

The API, which includes the following dependencies:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.0" NoWarn="NU1605" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.0" NoWarn="NU1605" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Data\Data.csproj" />
    </ItemGroup>

</Project>

```

Please change the ``Startup.cs`` from the Web-API to the following:
```cs
	public class Startup
	{
		public Startup(IConfiguration configuration)
		{
			Configuration = configuration;
		}

		public IConfiguration Configuration { get; }

		// This method gets called by the runtime. Use this method to add services to the container.
		public void ConfigureServices(IServiceCollection services)
		{
			services.AddDbContext<TestDbContext>(optionsAction =>
				optionsAction.UseSqlServer(Configuration.GetConnectionString("LOCAL"),
					b => b.MigrationsAssembly("API")));

			services.AddControllers();
			services.AddSwaggerGen(c => { c.SwaggerDoc("v1", new OpenApiInfo {Title = "API", Version = "v1"}); });
		}

		// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
		public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
		{
			if (env.IsDevelopment())
			{
				app.UseDeveloperExceptionPage();
				app.UseSwagger();
				app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "API v1"));
			}

			app.UseHttpsRedirection();

			app.UseRouting();

			app.UseAuthorization();

			app.UseEndpoints(endpoints => { endpoints.MapControllers(); });
		}
	}
```

**Comment by bricelam** [comment] 2021-01-04 23:38
I'm not able to repro this (dbo.__EFMigrationsHistory is created).

@TheRealLenon Can you attach a ZIP file of your solution? (click the bar at the bottom of the comment text box to attach files)

**Comment by ajcvickers** [comment] 2021-01-15 16:23
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:14 UTC
Labels: closed-could-not-reproduce, customer-reported
