### ISSUE TITLE
The incoming tabular data stream (TDS) protocol stream is incorrect. The MARS TDS header contained errors

### ISSUE THREAD

**Issue by mayconbeserra** [dotnet/efcore#15818] opened 2019-05-27 12:05 UTC
### Issue

Failed executing DbCommand ("2"ms) [Parameters=["@__GetType_Name_0='?' (Size = 500)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(2) [t].[Enabled]
FROM [FEAT_TOGGLES] AS [t]
WHERE [t].[Id] = @__GetType_Name_0"

```
Exception message: The incoming tabular data stream (TDS) protocol stream is incorrect. The MARS TDS header contained errors
Stack trace: 
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
ClientConnectionId:bc4a97f2-580d-4b5a-8597-e69539b14bae
Error Number:4011,State:3,Class:16"
```

```
Connection String (Default config for MARS): Server=xpto1;Database=db1;User Id=user;Password=pwd;
```

We have a small table for our toggles and we started having issues with MARS. Is this an issue with EFCore, SQLClient or the Database?

### Further technical details
EF Core version:  2.1
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Linux container

**Comment by ajcvickers** [comment] 2019-05-27 18:41
@mayconbeserra This is an issue either SqlClient or that database. It looks like a duplicate of https://github.com/dotnet/SqlClient/issues/85. If not, then please file a new issue on that repo.

**Closed** 2022-10-16 14:22 UTC
Labels: closed-external, customer-reported
