### ISSUE TITLE
Any way to set default `JsonSerializerOptions`?

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/efcore#27991] opened 2022-05-10 15:56 UTC
Is there any way to globally configure the `System.Text.Json` `JsonSerializerOptions` that EF Core uses?

**Comment by roji** [comment] 2022-05-10 19:07
Duplicate of https://github.com/npgsql/efcore.pg/issues/1107

**Comment by roji** [comment] 2022-05-10 19:11
@maumar leaving open in case you want to track this separately for EF Core JSON support in relational.

As previously discussed, this isn't as simple as just configuring the JsonSerializerOptions which EF Core passes to System.Text.Json, since some options would also need to affect query SQL that gets generated. A good example is [PropertyNamingPolicy](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.propertynamingpolicy?view=net-6.0#system-text-json-jsonserializeroptions-propertynamingpolicy), which would need to affect serialization/deserialization (done by System.Text.Json), but also the query pipeilne (when generating JSON property names in SQL).

Other options may only be meaningful to System.Text.Json for serialization/deserialization, and wouldn't pose a problem.

**Comment by AndriySvyryd** [comment] 2022-05-17 19:14
Duplicate of https://github.com/dotnet/efcore/issues/28043

**Closed** 2022-10-16 20:33 UTC
Labels: customer-reported
