### ISSUE TITLE
Package manager console crash on Add-Migration

### ISSUE THREAD

**Issue by m0glan** [dotnet/efcore#23972] opened 2021-01-25 18:38 UTC
# Configuration
- .NET Framework 4.6.2
- EntityFramework Core 3.1.6
- Microsoft.Data.Sqlite 3.1.6
- e_sqlcipher bundle 2.0.2
- Visual Studio 2019

# Issue
Migrating a project from EntityFramework 6 to EntityFramework Core. I added all the design time dependencies and an implementation of `IDesignTimeDbContextFactory<T>`. When running `Add-Migration Initial` in the PMC, I get:
```
Build started...
Build succeeded.
```
and then it gets stuck with no error. Clicking the red square (stop button) does not do anything. When I close Visual Studio 2019, I notice a new process _starts_ (after VS closure) in the task manager, ef32.exe. Checking the git repository status, I can see the migration files and the database are added, but database is completely empty (no schema, no data). 

The thing is that I did the same process (or so I think) to migrate another one of our projects to EntityFramework Core with no issues, so really don't see what could've gone wrong here.

Any help appreciated.

**Comment by ajcvickers** [comment] 2021-02-01 23:20
@vmoglan Can you attach a repro project that results in this behavior so that we can investigate. Also, do you know where "ef32.exe" comes from? (The path to the executable in the file system might provide a clue.)

**Comment by ajcvickers** [comment] 2021-02-12 16:41
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:20 UTC
Labels: closed-could-not-reproduce, customer-reported
