### ISSUE TITLE
ArgumentException on loading database values of object owned by owned object

### ISSUE THREAD

**Issue by Phomor** [dotnet/efcore#27899] opened 2022-04-27 14:12 UTC
### Bug and code

EF Core 3.1 is throwing an ArgumentException on loading the database values of an object that's owned by an object that's owned itself and part of a collection. 
[Project for reproduction](https://github.com/dotnet/efcore/files/8572727/ConsoleApp1.zip).

### Stack trace:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Expression of type 'System.Collections.Generic.ICollection`1[EFModeling.OwnedEntities.Post]' cannot be used for return type 'EFModeling.OwnedEntities.Post'
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Select[TSource,TResult](IQueryable`1 source, String propertyName)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.BuildQueryRoot(IEntityType ownerOrDefiningEntityType, IEntityType entityType, String navigationName)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.BuildQueryRoot(IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.BuildQueryRoot(IEntityType ownerOrDefiningEntityType, IEntityType entityType, String navigationName)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.BuildQueryRoot(IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1..ctor(IStateManager stateManager, IDbSetSource setSource, IDbSetCache setCache, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinderSource.<>c__3`1.<CreateConstructor>b__3_0(IStateManager s, IDbSetSource src, IDbSetCache c, IEntityType t)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinderSource.Create(IStateManager stateManager, IDbSetSource setSource, IDbSetCache setCache, IEntityType type)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinderFactory.Create(IEntityType type)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.CreateEntityFinder(IEntityType entityType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry.get_Finder()
   at Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry.GetDatabaseValues()
   at EFModeling.OwnedEntities.Program.Main(String[] args) in ConsoleApp1\Program.cs:line 44
```

### Provider and version information

EF Core version: 3.1.24
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Win 10 21H2
IDE: Visual Studio Commmunity 2022 17.1.6

**Comment by ajcvickers** [comment] 2022-04-28 14:27
Duplicate of #22084. Verified no exception is thrown on 6.0.4.

**Closed** 2022-10-16 20:32 UTC
Labels: customer-reported
