### ISSUE TITLE
dotnet ef migrations script does not group SQL statements

### ISSUE THREAD

**Issue by Zjokke** [dotnet/efcore#28202] opened 2022-06-10 15:04 UTC
## dotnet ef migrations script does not group SQL statements

When using Entity Framework Core 3.22, the `dotnet ef migrations script` command does not group the different SQL statements from a single migration. This can result in the migration GUID being added to the migration table without all SQL statements being executed.

Example: assume the migration contains 3 SQL statements (SQL1, SQL2, SQL3). The generated script then contains:
```
IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'MigrationGuid')
BEGIN
    EXECUTE SQL1;
END;
GO

IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'MigrationGuid')
BEGIN
    EXECUTE SQL2;
END;
GO

IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'MigrationGuid')
BEGIN
    EXECUTE SQL3;
END;
GO

IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'MigrationGuid')
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'N'MigrationGuid', N'3.1.22');
END;
GO
```
Suppose SQL2 fails, then SQL1 and SQL3 are executed and the migration GUID is added to the migration table without SQL2 being executed. Adding the migration GUID to the migration table should only be done after successful execution of the contained SQL statements.

**Comment by roji** [comment] 2022-06-10 16:23
Duplicate of #22616

**Closed** 2022-06-14 16:07 UTC
Labels: closed-duplicate, customer-reported
