### ISSUE TITLE
Neither SaveChanges nor EntityEntry.ReloadAsync include navigation properties with AutoInclude.

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#32408] opened 2023-11-25 08:11 UTC
I have a trust issue here. =) If I marked navigation property as `AutoInclude` I expect it would be....well...automatically ncluded when entity is (re)loaded.

Ok, it's arguable whether SaveChanges should be responsible for fixing up not loaded relationships, but `EntityEntry.ReloadAsync` MUST fetch navigations mapped with `AutoInclude`.

Currently I have to call:
```
await DbContext.SaveChangesAsync(cancellationToken);

var entry = DbContext.Entry(aggregate);
await entry.ReloadAsync(cancellationToken); // this does not include :-( 
foreach (var n in entry.Navigations)
{
    // TODO: check navigation is annotated with AutoInclude
    await entry.Navigation(n.Metadata).LoadAsync(cancellationToken);
}
```

**Comment by voroninp** [comment] 2023-11-25 08:18
And regarding this comment:
> // TODO: check navigation is annotated with AutoInclude

How can I check it?

**Comment by ajcvickers** [comment] 2023-11-27 12:11
Duplicate of #13890

**Comment by voroninp** [comment] 2023-11-29 08:43
@ajcvickers , ok, and how can I get the information whether Navigation should be  autoincluded?

**Comment by ajcvickers** [comment] 2023-12-04 16:20
`navigation.Metadata.IsEagerLoaded`

**Closed** 2023-12-04 16:20 UTC
Labels: customer-reported
