### ISSUE TITLE
Winui Database.Migrate() does not create new database if it does not already exist

### ISSUE THREAD

**Issue by karmelcorn** [dotnet/efcore#30797] opened 2023-04-30 00:58 UTC
1. The DB context is created in a separate project from the WinUI startup project.
2. If you run Add-Migration, build succeed but no migration files are created
3. If you run `dotnet ef migrations add initialcreate --project DBContextProject`, migration files are created.
4. If you run `donet ef database update --project DBContextProject`, sqlite db is created. 
5. Subsequent migrations are applied directly when you run the app. 

However, if you do not create the db first in step 4. 
`context.Database.Migrate();` in the WinUI you get the following error:
`Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 14: 'unable to open database file'.'`

`context.Database.Migrate();` should have created the db and applied the migrations if the db does not exist. Now there is no way to programmatically create the db if one does not already exist. 

Also, `Add-Migration `should have worked to create the migration files. 

### Include provider and version information

EF Core version:  Microsoft.EntityFrameworkCore 6.0.10
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6.0
Operating system: Windows 10
IDE: (e.g. Visual Studio 2022 17.3.6)

**Comment by ajcvickers** [comment] 2023-05-01 17:08
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-05-10 09:02
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-05-10 09:02 UTC
Labels: customer-reported
