### ISSUE TITLE
DetachedLazyLoadingWarning error happening when it shouldn't

### ISSUE THREAD

**Issue by martinRocks** [dotnet/efcore#14390] opened 2019-01-11 14:35 UTC
I’m working a 3-teir web application using dot net core 2.2.101 and entity framework core 2.2.1 to connect to SQL server 2016.  I’m getting the below error when the application tries uses lazy loading to navigate to another table.  

I have created a very small application that smashes all the layers of my bigger application into a single web application for demonstration purposes. 
It seems that if I put a ‘ToList()’ on the end data line (line 19 in ServiceData.GetData) everything works fine.  However, what I want to do is let the web layer (the controller in this project) decide what values it needs and let lazy loading pull only those fields.

Error generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.DetachedLazyLoadingWarning: An attempt was made to lazy-load navigation property 'Parent' on detached entity of type 'TableChildProxy'. Lazy-loading is not supported for detached entities or entities that are loaded with 'AsNoTracking()'.'. This exception can be suppressed or logged by passing event ID 'CoreEventId.DetachedLazyLoadingWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.'
[EfCoreLazyExample.zip](https://github.com/aspnet/EntityFrameworkCore/files/2749951/EfCoreLazyExample.zip)

**Comment by ajcvickers** [comment] 2019-01-12 00:31
Duplicate of #12761

**Closed** 2022-10-16 13:47 UTC
Labels: customer-reported
