### ISSUE TITLE
Ensure DbUpdateConcurrencyException.StateEntires contains the most accurate set of entries

### ISSUE THREAD

**Issue by davidroth** [dotnet/efcore#1002] opened 2014-11-04 09:02 UTC
I am currently testing optimistic concurrency with batching updates.
If I update multiple entities at once, and more than 1 entity update fails due to an invalid ConcurrencyToken, DbUpdateConcurrencyException contains only the first failed entity.

Since EF7 uses batching updates, I would expect the StateEntries-Collection to contain all failed updates (all entities where @RowCount returns 0) and not only the first one.

Here is an example:

``` csharp
private void UpdateStuff()
{
    using (var db = new BloggingContext())
    {
        var blogs = db.Blogs.OrderBy(x => x.BlogId).Take(10).ToList();
        foreach(var blog in blogs)
        {
            blog.Url += "2";
        }
        ConcurrentUpdate();

        try
        {
            db.SaveChanges();
        }
        catch(DbUpdateConcurrencyException ex)
        {
            // ex.StateEntries contains only 1 entry, even though 2 records failed to update.
            // Expected: 2 Entries since 2 updates failed.
        }
        Console.WriteLine("finished");
    }
}

private void ConcurrentUpdate()
{
    using (var db = new BloggingContext())
    {
        var blogs = db.Blogs.OrderBy(x => x.BlogId).Skip(4).Take(2).ToList();
        foreach (var blog in blogs)
        {
            blog.Url += "1";
            blog.Version += 1;
        }

        db.SaveChanges();
    }
}
```

**Comment by ajcvickers** [comment] 2016-07-08 17:44
Note for triage: we should decide to do this, or close./

**Comment by rowanmiller** [comment] 2016-07-08 19:08
We won't really be able to do this until we iterate on batching implementation.

**Comment by ajcvickers** [comment] 2017-09-08 00:42
We discussed this again in triage and decided to close it for now because use of optimistic concurrency with a manual resolution process (which is where this would be most useful) does not seem to be that common. However, we will reconsider this with enough feedback. Also, we would be interested in taking a community PR for this, although it is not trivial especially in terms of not causing regressions for other SaveChanges scenarios.

**Closed** 2022-10-16 08:45 UTC
Labels: type-enhancement, closed-out-of-scope, punted-for-2.0
