### ISSUE TITLE
applicationDbContext.Database.BeginTransaction() does not work with Aspnetusers table .

### ISSUE THREAD

**Issue by Risanshita** [dotnet/efcore#10758] opened 2018-01-24 08:02 UTC
I want to implement transaction with asp .net core identities table. i have two databases for one database it works but for identity database doesn't.

It doesn't throw any exception 

This is my code.----

```C#
using (var identitydbContextTransaction = applicationDbContext.Database.BeginTransaction()) // for identity database
                        {
                            var user = new ApplicationUser { UserName = model.Email, Email = model.Email, PhoneNumber = model.PhoneNumber };
                            var result = await _userManager.CreateAsync(user, model.Password);
                            if (result.Succeeded)
                            {
                                    try
                                    {
                                        using (IDbContextTransaction transaction = TaskService.GetTransaction()) // TaskService.GetTransaction() Get transaction for another database
                                        {
                                            SaveEntity(savedUser, model);
                                            throw new Exception();
                                            transaction.Commit();
                                        }
                                        identitydbContextTransaction.Commit();
                                    }
                                    catch
                                    {
                                        identitydbContextTransaction.Rollback();
                                        throw;
                                    }
                            }
                        }
```

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7
IDE:  Visual Studio 2017

**Comment by ajcvickers** [comment] 2018-01-24 17:49
@Risanshita What does SaveEntity do? Hasn't the save already happened as part of CreateAsync?

**Comment by Risanshita** [comment] 2018-01-25 05:09
SaveEntity is just a method, we are using to save data in some other tables.

**Comment by ajcvickers** [comment] 2018-01-25 17:13
@Risanshita I don't think there is enough information here for us to be able to reproduce what you are seeing. Can you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we are better able to investigate it?

**Comment by ajcvickers** [comment] 2018-02-02 17:26
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by Risanshita** [comment] 2018-03-03 21:18
I fixed it ..... it was my fault . thnx

**Closed** 2022-10-16 12:06 UTC
Labels: closed-could-not-reproduce
