### ISSUE TITLE
ValueGeneratedOnAdd() not applied when seeding data with EntityTypeBuilder<T>.HasData()

### ISSUE THREAD

**Issue by Mimetis** [dotnet/efcore#13206] opened 2018-09-04 12:16 UTC
Hello guys.

Basically, the `ValueGeneratedOnAdd()` method seems to not work as expected when seeding data (and using the `HasData()` method from the `EntityTypeBuilder<T>` object instance.

For instance, I've used a modified version of the light (and old :) ) **AdventureWorks** database.
In the **Address** table, we have two autogenerated columns : `rowguid` and `ModifiedDate`.

First of all, here is the `OnModelCreating` stuff I've written so far (I've skipped the properties not involved in the *not expected result* I've noticed)

``` csharp
modelBuilder.Entity<Address>(entity =>
{
    entity.Property(e => e.ModifiedDate)
        .HasColumnType("datetime")
        .ValueGeneratedOnAdd()
        .HasDefaultValueSql("(getdate())");

    entity.Property(e => e.Rowguid)
        .HasColumnName("rowguid")
        .ValueGeneratedOnAdd()
        .HasDefaultValueSql("(newid())");
});

```
Here is the code used when seeding data:
``` csharp
modelBuilder.Entity<Address>().HasData(
   new Address { AddressId = 1, AddressLine1 = "8713 Yosemite Ct.", 
              City = "Bothell", StateProvince = "Washington", 
              CountryRegion = "United States", PostalCode = "98011" });
```
And here is the code generated by SQL:

``` sql
IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'AddressID', N'AddressLine1', N'AddressLine2', N'City', N'CountryRegion', N'ModifiedDate', N'PostalCode', N'rowguid', N'StateProvince') AND [object_id] = OBJECT_ID(N'[Address]'))
    SET IDENTITY_INSERT [Address] ON;

INSERT INTO [Address] ([AddressID], [AddressLine1], [AddressLine2], [City], [CountryRegion], [ModifiedDate], [PostalCode], [rowguid], [StateProvince])
VALUES (1, N'8713 Yosemite Ct.', NULL, N'Bothell', N'United States', '0001-01-01T00:00:00.000', N'98011', '00000000-0000-0000-0000-000000000000', N'Washington')

IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'AddressID', N'AddressLine1', N'AddressLine2', N'City', N'CountryRegion', N'ModifiedDate', N'PostalCode', N'rowguid', N'StateProvince') AND [object_id] = OBJECT_ID(N'[Address]'))
    SET IDENTITY_INSERT [Address] OFF;
```
As you can see, the `INSERT INTO` clause are generated with both `ModifiedDate` and `rowguid` columns.   
And the values used are the default type values (`0001-01-01T00:00:00.000` and `00000000-0000-0000-0000-000000000000`)   
And as you may expect, SQL Server will fail since `0001-01-01T00:00:00.000` is not allowed. (and by the way, I would prefer to let the database generates the correct values)

In the opposite, this code (if I'm not seeding before) is working correctly:

``` csharp
using (var dbcontext = new AdventureWorksContext(serverRun))
{
    var add = new Address { AddressLine1 = "8713 Yosemite Ct.", City = "Bothell", StateProvince = "Washington", CountryRegion = "United States", PostalCode = "98011" };
    dbcontext.Address.Add(add);
    dbcontext.SaveChanges();
}

```
The SQL Trace generated by EF Core:
``` sql
exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [Address] ([AddressID], [AddressLine1], [AddressLine2], [City], [CountryRegion], [PostalCode], [StateProvince])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6);
SELECT [ModifiedDate], [rowguid]
FROM [Address]
WHERE @@ROWCOUNT = 1 AND [AddressID] = @p0;

',N'@p0 int,@p1 nvarchar(60),@p2 nvarchar(60),@p3 nvarchar(30),@p4 nvarchar(50),@p5 nvarchar(15),@p6 nvarchar(50)',@p0=1,@p1=N'8713 Yosemite Ct.',@p2=NULL,@p3=N'Bothell',@p4=N'United States',@p5=N'98011',@p6=N'Washington'
```

Did I miss something ?

Sebastien

**Comment by ajcvickers** [comment] 2018-09-05 18:44
@AndriySvyryd to find dupe.

**Comment by AndriySvyryd** [comment] 2018-09-05 20:02
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/11969

**Closed** 2022-10-16 13:29 UTC
Labels: customer-reported
