### ISSUE TITLE
System.InvalidOperationException: The operands for operator 'Equal' do not match the parameters of method 'op_Equality'.

### ISSUE THREAD

**Issue by masoud-bahrami** [dotnet/efcore#11248] opened 2018-03-13 10:29 UTC
I used the EF 6 and then upgrade source code to dot net core 2 and so i was update EF to EF core 2.
I have some EF query like this:

```
var query = ctx.GetDbSet<Core.DomainEntities.Entity.Agenda>()
                    .Include("LoadingLocation")
                    .AsQueryable();

                if (!message.IncludeDeleted)
                    query = query.Where(agenda => !agenda.MarkAsRemove);

                if (!string.IsNullOrWhiteSpace(message.SearchText))
                {
                    var searchText = message.SearchText.ToLower();
                    query = query.Where(agenda => agenda.WaybillSeries.ToLower().Contains(searchText));
                }

                var totalCount = query.Count();

                var result = new AgendasQueryResult
                {
                    TotalCount = totalCount,
                    Entities = query.Select(agenda => new AgendaResult
                    {
                        Id = agenda.Id,
                        Description = agenda.Description,
                        LoadingLocation = agenda.LoadingLocation == null
                            ?null: new DualViewModel
                            {
                                Id = agenda.LoadingLocation.Id,
                                Title = agenda.LoadingLocation.Name
                            },
                        SmartCardNumber = agenda.Driver.SmartCardNumber,
                        TrailerId = agenda.Trailer.Id,
                                         ExportDate = agenda.ExportDate,
                    }).ToList()
                };
```

Although I had no error before, I'm facing this error now
{System.InvalidOperationException: The operands for operator 'Equal' do not match the parameters of method 'op_Equality'.
   at System.Linq.Expressions.Expression.GetMethodBasedBinaryOperator(ExpressionType binaryType, Expression left, Expression right, MethodInfo method, Boolean liftToNull)}

And if remove 
```
   LoadingLocation = agenda.LoadingLocation == null
                            ?null: new DualViewModel
                            {
                                Id = agenda.LoadingLocation.Id,
                                Title = agenda.LoadingLocation.Name
                            },
```
this code will be run whiteout any error.

I this i can't use operand like (!= or == null). 
Please correct me if i mistake.
Thanks a lot

**Comment by masoud-bahrami** [comment] 2018-03-13 10:46
I think reference equality by using (== or !=) which is used by EF core run into problem since it compare two different object.
I replace `agenda.LoadingLocation == null`   with  `agenda.LoadingLocation.Equals(null)`

**Comment by Jagbri** [comment] 2018-04-13 10:00
I have the same error when I try to compare two GUIDs from one entity and a related properties collection, but in this case use Equals() doesn't work either.

Example app:
```
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new AppContext())
            {
                var guid = Guid.NewGuid();
                var element = new Element
                {
                    Id = guid,
                    Properties = new List<RelatedProperty>{
                        new RelatedProperty
                        {
                            Id = guid
                        }
                    }
                };

                context.Add(element);
                context.SaveChanges();
     
                //Results Views throws an exception
                var result = context.Elements.Where(e => e.Properties.Last().Id == e.Id);
            }
        }
    }

    public class AppContext : DbContext
    {
        public DbSet<Element> Elements { get; set; }
        public DbSet<RelatedProperty> RelatedProperties { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInMemoryDatabase("InMemoryDB");
        }
    }

    public class Element
    {
        public Guid Id { get; set; }
        public ICollection<RelatedProperty> Properties { get; set; }
    }

    public class RelatedProperty
    {
        public Guid Id { get; set; }
    }
```

StackTrace

  ```
 at System.Linq.Expressions.Expression.GetMethodBasedBinaryOperator(ExpressionType binaryType, Expression left, Expression right, MethodInfo method, Boolean liftToNull)
   at System.Linq.Expressions.Expression.Equal(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
   at System.Linq.Expressions.Expression.MakeBinary(ExpressionType binaryType, Expression left, Expression right, Boolean liftToNull, MethodInfo method, LambdaExpression conversion)
   at System.Linq.Expressions.BinaryExpression.Update(Expression left, LambdaExpression conversion, Expression right)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.WhereClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()

```
Entity Framework Core 2.0.2
Windows 10 1709
Visual studio 2017 community 15.6.6

**Comment by tgourley** [comment] 2018-05-01 12:09
I have run across post in my search for answers for this problem.

I have EF Core 2 in my app, and I am doing a simple null check on a navigation property inside a tracked object.  I have tried both using == as well as Equals().

`x => x.AccountType == null`
`x => x.AccountType.Equals(null)`

The (from the comments above) is that I am overriding/implementing the IEquatable interface.

`public override bool Equals(object obj)
{
	return this.Equals(obj as AccountType);
}

public bool Equals(AccountType p)
{
	// If parameter is null, return false.
	if (Object.ReferenceEquals(p, null))
	{
		return false;
	}

	// Optimization for a common success case.
	if (Object.ReferenceEquals(this, p))
	{
		return true;
	}

	// If run-time types are not exactly the same, return false.
	if (this.GetType() != p.GetType())
	{
		return false;
	}

	// Return true if the fields match.
	// Note that the base class is not invoked because it is
	// System.Object, which defines Equals as reference equality.
	return AccountTypeCode == p.AccountTypeCode;
}

public bool Equals(AccountType x, AccountType y)
{
	return x.Equals(y);
}

public override int GetHashCode()
{
	return AccountTypeCode.GetHashCode();
}

public static bool operator ==(AccountType lhs, AccountType rhs)
{
	// Check for null on left side.
	if (Object.ReferenceEquals(lhs, null))
	{
		if (Object.ReferenceEquals(rhs, null))
		{
			// null == null = true.
			return true;
		}

		// Only the left side is null.
		return false;
	}

	// Equals handles case of null on right side.
	return lhs.Equals(rhs);
}

public static bool operator !=(AccountType lhs, AccountType rhs)
{
	return !(lhs == rhs);
}`

**Comment by tgourley** [comment] 2018-05-01 12:27
Per the answers in this StackOverflow page: [https://stackoverflow.com/questions/16741503/strange-exception-thrown-when-defining-an-expression-with-between-a-generic-s]

I tried putting the check inside a Func and it indeed worked.

`Func<AccountType, AccountType, bool> func = (value, nullableValue) => value == nullableValue;`

**Comment by smitpatel** [comment] 2018-05-01 21:07
Removing milestone here.
@masoud-bahrami - I tried to repro the issue by using code you provided but things are working without error. Can you post self-contained repro code which can be run?

**Comment by smitpatel** [comment] 2018-05-01 21:14
@Jagbri - Your issue may have same exception but it has totally different root cause. The OP has issue when comparing navigation to null. In your case, you are having problems with using Last result operator member access. I have separated out your issue and it is being tracked #11869

**Comment by smitpatel** [comment] 2018-05-01 21:16
@tgourley - Please provide repro code for the issue you are seeing. Using Func is not a solution. By using Func you are basically making it opaque in Expression Tree forcing EF Core to client eval it. Hence it works. Which is not incorrect but client evaluation could have perf disadvantages.
In the code snippet you have posted, there are no models/query. We are still looking for a repro code of this issue.

**Comment by tgourley** [comment] 2018-05-02 01:29
I totally agree that Func is not a solution exactly for the client-side comparison.  This is part of a larger project, I will try to pull out the code to post here.

Details:  EF Core 2, PostgreSQL, class implements the IEquatable interface.

**Comment by ajcvickers** [comment] 2018-05-11 18:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:13 UTC
Labels: closed-could-not-reproduce
