### ISSUE TITLE
Migration file is generated with same content

### ISSUE THREAD

**Issue by darkcompet** [dotnet/efcore#29879] opened 2022-12-17 08:14 UTC
## File a bug

Hi,

When I repeat 2 actions: `add migration`, `update database`, the migration file is newly generated with same content at each time even though DbContext, Model, ModelBuilder classes are NOT modified.
Note: this was not happened at efcore 6.0.

Below is commands that I have tested. Please refer to `Source code` and `Verbose output` sections for detail.

```bash
dotnet ef migrations add Test1
dotnet ef database update

dotnet ef migrations add Test2
dotnet ef database update

dotnet ef migrations add Test3
dotnet ef database update
```

### Source code

Below are 3 classes which I use: DbContext, Model and ModelBuilder.

- DbContext class:

```C#
namespace App;

using System.Transactions;
using Microsoft.EntityFrameworkCore;

public class AppDbContext : DbContext {
	public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

	public DbSet<MstAppModel> apps { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder) {
		MstAppModelBuilder.OnModelCreating(modelBuilder);
	}
}
```

- Model class:

```C#
namespace App;

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

[Table("mst_app")]
[Index(nameof(os_type), IsUnique = true)]
public class MstAppModel {
	[Key]
	[Column("id")]
	public int id { get; set; }

	/// [See const] Which OS is (android, ios,...)
	[Required]
	[Column("os_type", TypeName = "tinyint")]
	public byte os_type { get; set; }

	/// App version, for eg,. "2.12.108"
	[Required]
	[Column("app_version", TypeName = "varchar(32)"), MaxLength(32)]
	public string app_version { get; set; }

	[Required]
	[Column("created_at")]
	public DateTime created_at { get; set; }

	[Column("updated_at")]
	public DateTime? updated_at { get; set; }
}
```

- ModelBuilder class:

```C#
namespace App;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Tool.Compet.Core;

public class MstAppModelBuilder {
	public static void OnModelCreating(ModelBuilder modelBuilder) {
		// [Modelizing]
		// Generate default datetime when add.
		modelBuilder.Entity<MstAppModel>().Property(model => model.created_at).HasDefaultValueSql("getutcdate()");

		// [Seeding]
		modelBuilder.Entity<MstAppModel>().ToTable("mst_app").HasData(
			new MstAppModel {
				id = 1,
				os_type = 1,
				app_version = "1.0.0",
			},
			new MstAppModel {
				id = 2,
				os_type = 2,
				app_version = "1.0.0",
			},
			new MstAppModel {
				id = 3,
				os_type = 3,
				app_version = "1.0.0",
			},
			new MstAppModel {
				id = 4,
				os_type = 4,
				app_version = "1.0.0",
			},
			new MstAppModel {
				id = 5,
				os_type = 5,
				app_version = "1.0.0",
			}
		);
	}
}
```

### Verbose output

Here is migration class generated at each time run: `dotnet ef migrations add TestGenerateMigrationOfMasterTable`

```C#
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Adabet.Migrations
{
    /// <inheritdoc />
    public partial class TestGenerateMigrationOfMasterTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "mst_app",
                keyColumn: "id",
                keyValue: 1,
                columns: new[] { "app_version", "os_type" },
                values: new object[] { "1.0.0", (byte)1 });

            migrationBuilder.UpdateData(
                table: "mst_app",
                keyColumn: "id",
                keyValue: 2,
                columns: new[] { "app_version", "os_type" },
                values: new object[] { "1.0.0", (byte)2 });

            migrationBuilder.UpdateData(
                table: "mst_app",
                keyColumn: "id",
                keyValue: 3,
                columns: new[] { "app_version", "os_type" },
                values: new object[] { "1.0.0", (byte)3 });

            migrationBuilder.UpdateData(
                table: "mst_app",
                keyColumn: "id",
                keyValue: 4,
                columns: new[] { "app_version", "os_type" },
                values: new object[] { "1.0.0", (byte)4 });

            migrationBuilder.UpdateData(
                table: "mst_app",
                keyColumn: "id",
                keyValue: 5,
                columns: new[] { "app_version", "os_type" },
                values: new object[] { "1.0.0", (byte)5 });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "mst_app",
                keyColumn: "id",
                keyValue: 1,
                columns: new[] { "app_version", "os_type" },
                values: new object[] { null, (byte)0 });

            migrationBuilder.UpdateData(
                table: "mst_app",
                keyColumn: "id",
                keyValue: 2,
                columns: new[] { "app_version", "os_type" },
                values: new object[] { null, (byte)0 });

            migrationBuilder.UpdateData(
                table: "mst_app",
                keyColumn: "id",
                keyValue: 3,
                columns: new[] { "app_version", "os_type" },
                values: new object[] { null, (byte)0 });

            migrationBuilder.UpdateData(
                table: "mst_app",
                keyColumn: "id",
                keyValue: 4,
                columns: new[] { "app_version", "os_type" },
                values: new object[] { null, (byte)0 });

            migrationBuilder.UpdateData(
                table: "mst_app",
                keyColumn: "id",
                keyValue: 5,
                columns: new[] { "app_version", "os_type" },
                values: new object[] { null, (byte)0 });
        }
    }
}
```

### Include provider and version information

EF Core version: 7.0.0, 7.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: MacOS M1 latest version
IDE: Visual Studio Code latest version

**Comment by AndriySvyryd** [comment] 2023-01-04 21:01
Duplicate of #29450

**Closed by AndriySvyryd** 2023-01-04 21:01 UTC
Labels: customer-reported
