### ISSUE TITLE
Completely Useless error message when both verbose and/or debug are enabled.

### ISSUE THREAD

**Issue by BrianMinister** [dotnet/efcore#19562] opened 2020-01-10 22:18 UTC
I ran ``add-migration SetEmailToNonUnique -context ApplicationDbContext -outputdir Migrations/ApplicationDb -startupproject Lcp.Fortify.Ux -verbose -debug``. This code compiles fine in VS 2019, but in powershell or Package Manager Console I get:
````
PM>  add-migration SetEmailToNonUnique -context ApplicationDbContext -outputdir Migrations/ApplicationDb -startupproject Lcp.Fortify.Ux -verbose -debug 
Using project 'src\Lcp.Fortify.Data'.
Using startup project 'src\Lcp.Fortify.Ux'.
Build started...
Build failed.
````
I did find what was causing my build to fail, in that one of my minor projects in my solution was miss tagged as a console app, when it was supposed to be a library. 

The **Build failed.** when running either debug or verbose should dump useful information like what project caused the failure.

EF Core version: 2.2.6 (Though I am more concerned that this is addressed in future versions._
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 2.2)
Operating system: Win 10 Pro 64
IDE: Version 16.5.0 Preview 1.0

**Comment by ajcvickers** [comment] 2020-01-13 17:39
@bricelam Can we change how we execute build to include more output when `-verbose` is used?

**Comment by bricelam** [comment] 2020-01-13 20:02
Duplicate of #12654

**Closed** 2022-10-16 18:05 UTC
Labels: customer-reported
