### ISSUE TITLE
ASP.NET 5/EF 7: Could not load file or assembly 'System.Data.SqlClient'

### ISSUE THREAD

**Issue by f0rt** [dotnet/efcore#3905] opened 2015-11-26 19:34 UTC
Hi team,

I'm deploying ASP.NET 5 application to Azure. After successful deploy and opening my site in the browser I'm getting the error:
FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

I had similar issue using ASP.NET 4 explained here: http://stackoverflow.com/questions/21641435/error-no-entity-framework-provider-found-for-the-ado-net-provider-with-invarian
The solution named "the terrible hack" worked for me then. :)

Do you have any ideas what might be causing the problem and how to fix it?

Thanks in advance!

**Comment by f0rt** [comment] 2015-11-27 22:09
System.Data.SqlClient is referenced in my project by EntityFramework.MicrosoftSqlServer. I've added direct dependency in project.json. My guess was that the dependency is not downloaded/deployed because it is not directly referenced. It failed again with the same error. I've added some code in startup.cs to prevent any deployment optimization (if exists) and the application crashed with "An error occurred while starting the application.".

**Comment by Sebazzz** [comment] 2015-11-28 22:21
Having the same issue here in [my application](https://github.com/Sebazzz/financial-app).

**Comment by Sebazzz** [comment] 2015-11-28 22:49
This appears to be a duplicate of #3637.

**Comment by Sebazzz** [comment] 2015-11-28 23:07
It appears that the real issue is a dependency problem of SqlClient which is being tracked in dotnet/corefx as [#3760](https://github.com/dotnet/corefx/issues/3760). Not sure what solution is possible in the mean time.

**Comment by f0rt** [comment] 2015-11-28 23:49
It is strange but I have a dnx50 job that is working with the same code.

**Comment by Sebazzz** [comment] 2015-11-29 11:55
That's odd.

I've just created a fresh VM on Azure with Ubuntu and I'm still having the issue:

```
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
       ---> System.IO.FileNotFoundException: Could not load the specified file.
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

**Comment by rowanmiller** [comment] 2015-11-30 19:43
Closing as this is a dupe of #3637... which is actually an issue in DNX (a fix is being worked on at the moment).

https://github.com/dotnet/corefx/issues/3760 is actually a different issue which results in an exception about not being able to load the native assemblies (rather than System.Data.SqlClient).

**Closed** 2022-10-16 09:18 UTC
