### ISSUE TITLE
EF Core code first Inheritance of separate tables

### ISSUE THREAD

**Issue by borisdj** [dotnet/efcore#8728] opened 2017-06-05 11:58 UTC
Say I have a table Company defined in following entity:
```c#
    public class Company
    {
        public Guid CompanyId { get; set; }
    
        [Required]
        public string Name { get; set; }
    
        [MaxLength(50)]
        public string Uid { get; set; }
    
        ...
    }
```
And I need another table CompanyHistory that will have all fields of Company extended with `CompanyHistoryId, EffectiveDate, DEffectiveDate`.
I have tried it like this:
```c#
    public class CompanyHistory : Company
    {
        public Guid CompanyHistoryId { get; set; }
    
        public virtual Company { get; set; }
    }
```
But instead of 2 tables, migration makes only 1 table 'Company' where it combines all the columns.

I could get what I want like this:
```c#
    public class CompanyHistory
    {
        public Guid CompanyHistoryId { get; set; }
    
        public Guid CompanyId { get; set; }
        public virtual Company Company { get; set; }
    
        [Required]
        public string Name { get; set; }
    
        [MaxLength(50)]
        public string Uid { get; set; }
    
        ...
    }
```

But can the same be achieved using inheritance, so that I don't have to write all the columns again.

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by soeron** [comment] 2017-06-05 13:03
I am guessing you are looking for Table Per Type inheritance, which is very needed feature not yet implemented. You can look here https://github.com/aspnet/EntityFramework/issues/2266 for more info.

**Comment by borisdj** [comment] 2017-06-05 17:26
It seems so, and looks like it's not implemented yet.
However I have figured how to achieve want I want with a little different structure.
Define first CompanyBase (abstract) class and then derive from it both Company and CompanyHistory.
```c#
    public class CompanyBase
    {
        public Guid CompanyId { get; set; }
    
        [Required]
        public string Name { get; set; }
    
        [MaxLength(50)]
        public string Uid { get; set; }
    
        ...
    }
```
```c#
    public class Company : CompanyBase
    {
        public Guid CompanyId { get; set; }
    }
```
```c#
    public class CompanyHistory : CompanyBase
    {
        public Guid CompanyHistoryId { get; set; }

        public DateTime EffectiveDate { get; set; }

        public DateTime? DeffectiveDate { get; set; }
    }
```

**Comment by ajcvickers** [comment] 2017-06-05 23:01
@borisdj We typically refer to this type of mapping as TPC. This is being tracked by issue #3170, so I'm going to close this issue as a duplicate of that one.

The workaround that you posted should work as long as CompanyBase is not mapped. This implies that there cannot be any references from entity types to the CompanyBase class--they must all reference one of the derived classes.

**Comment by borisdj** [comment] 2017-06-06 06:20
Yes, and CompanyBase is not mapped, I have just added 'abstract':
`abstract CompanyBase class...`

**Closed** 2022-10-16 11:07 UTC
