### ISSUE TITLE
EF Core - Migration - Subsequent migrations re-creates table that is already created by another migration (Foreign Key)

### ISSUE THREAD

**Issue by tonyawad88** [dotnet/efcore#14283] opened 2019-01-01 15:41 UTC
Describe what is not working as expected.

Hello,
I did a research on previous issues and on Stackoverflow but couldn't find an answer to this.
I basically have 2 migrations. Migration 1 db context has a table called Company. Migration 2 db context has a table called Department.

Department has a foreign key CompanyId with a Company.
**Company:**
```
[Table("Companies")]
    public class Company
    {
        [Key]
        public Guid CompanyId { get; set; }
        public string CompanyCode { get; set; }
    }
```

**Departments:**
```
[Table("Departments")]
    public class Department
    {
        [Key]
        public Guid DepartmentId { get; set; }
        public string DepartmentCode { get; set; }
        [ForeignKey("Company")]
        public Guid CompanyId { get; set; }

        public Company Company { get; set; }
    }
```

When I try to run the add migrations `dotnet ef migrations add migration2 -c Migration2DbContext -o Data/Migrations/Migration2`

The code generated tries to re-create the Companies table again. Is there a way to suppress this but keep the foreign key relationship?

The workaround I currently have is clunky, I have to go inside the generated code and remove every create table. I am hoping there is a better way.

Thank you so much!
### Further technical details
EF Core version:  2.1.4-rtm-31024
Database Provider: Pomelo.EntityFrameworkCore.MySql 2.1.4
Operating system: Windows 10
IDE: VS2017

**Comment by ajcvickers** [comment] 2019-01-02 21:30
Duplicate of #2725

**Comment by echuck66** [comment] 2019-07-09 12:10
Are there any updates on this? I'm having this issue as well.

Microsoft.EntityFrameworkCore 2.2.4
MySql.Data.EntityFrameworkCore 8.0.16

This is very frustrating.

**Closed** 2022-10-16 13:46 UTC
Labels: customer-reported
