### ISSUE TITLE
EF Core connection Failed to load ..\x86\SNI.dll

### ISSUE THREAD

**Issue by estyfen** [dotnet/efcore#20473] opened 2020-03-31 00:15 UTC
I have a desktop winforms application, which uses entity framework core to work with a SQL Server database.
During the debugging cycle the application runs without problem, makes the connections correctly and executes the queries correctly. When publishing the .exe application, and putting it on the end customer's computer, it fails.

Attached small project to reproduce the error.  [Download](https://1drv.ms/u/s!AnSJXzxKKqQFivE3Vl38iQ70jxooEw?e=E9ywNX)
Attached animated git with evidence. [Download](https://1drv.ms/u/s!AnSJXzxKKqQFivE4dcy4enzidWeuZg?e=mSWTdG)

Attention: The problem **does not occur** on the developer machine with Visual Studio. The problem occurs on the end customer's computer.

### Steps to reproduce
1. Compile the attached project
2. Copy the results _/Release_ to a Windows folder, **on a different computer than the development one**. To simulate this I use SandBox of windows 10, to have an isolated space.
3. Run the WinEFCore.exe application.
4. Click on the "Click here testing" button. It doesn't matter that the connection string is wrong. The problem can be reproduced as is.
5. Expected result: The query is executed through the EF Core provider, However, in this case, you should get database connection error.
6. Current result:  Failed to load ..\x86\SNI.dll

### Stack trace
``` C#
System.TypeInitializationException: Se produjo una excepción en el inicializador de tipo de 'Microsoft.Data.SqlClient.TdsParser'. ---> System.TypeInitializationException: Se produjo una excepción en el inicializador de tipo de 'Microsoft.Data.SqlClient.SNILoadHandle'. ---> System.TypeInitializationException: Se produjo una excepción en el inicializador de tipo de 'Microsoft.Data.SqlClient.SNINativeMethodWrapper'. ---> System.ComponentModel.Win32Exception: Failed to load C:\Pruebas\Release\x86\SNI.dll
   en Microsoft.Data.SqlClient.SNINativeMethodWrapper..cctor() en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\Interop\SNINativeMethodWrapper.cs:línea 64
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Microsoft.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize()
   en Microsoft.Data.SqlClient.SNILoadHandle..ctor() en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\TdsParserSafeHandles.cs:línea 31
   en Microsoft.Data.SqlClient.SNILoadHandle..cctor() en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\TdsParserSafeHandles.cs:línea 16
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Microsoft.Data.SqlClient.TdsParser..cctor() en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\TdsParser.cs:línea 156
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Microsoft.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous) en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\TdsParser.cs:línea 32
   en Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout) en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlInternalConnectionTds.cs:línea 1546
   en Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance) en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlInternalConnectionTds.cs:línea 1442
   en Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, ServerCertificateValidationCallback serverCallback, ClientCertificateRetrievalCallback clientCallback, DbConnectionPool pool, String accessToken, SqlClientOriginalNetworkAddressInfo originalNetworkAddressInfo, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager) en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlInternalConnectionTds.cs:línea 425
   en Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions) en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlConnectionFactory.cs:línea 121
   en Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions) en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionFactory.cs:línea 143
   en Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionPool.cs:línea 870
   en Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionPool.cs:línea 1807
   en Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection) en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionPool.cs:línea 1293
   en Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection) en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionPool.cs:línea 1191
   en Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionFactory.cs:línea 302
   en Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionInternal.cs:línea 683
   en Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionClosed.cs:línea 65
   en Microsoft.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry) en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlConnection.cs:línea 1605
   en Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry) en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlConnection.cs:línea 1599
   en Microsoft.Data.SqlClient.SqlConnection.Open() en E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlConnection.cs:línea 1250
   en Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   en Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   en Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   en Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   en Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   en Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   en System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   en System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   en WinAppEFCore.Form1.button1_Click(Object sender, EventArgs e) en F:\CODFT\WinAppEFCore\WinAppEFCore\Form1.cs:línea 22
   en System.Windows.Forms.Control.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ButtonBase.WndProc(Message& m)
   en System.Windows.Forms.Button.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

Please help. I have stopped the entire publication of a new version of our product.
@ajcvickers @cheenamalhotra @roji @bricelam 

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Framework 4.6.1
Operating system:
Windows 10 Pro, Visual Studio 2019 16.5.0

**Comment by pmiddleton** [comment] 2020-03-31 02:20
looks related to https://github.com/dotnet/SqlClient/issues/385

**Comment by estyfen** [comment] 2020-03-31 14:17
> 
> 
> looks related to [dotnet/SqlClient#385](https://github.com/dotnet/SqlClient/issues/385)

Hi, thanks, But my case is with a WinForms desktop application with destination .NET Framework 4.6.1. If you look at the code I attached for testing, it is something very small and normal, and it presents the problem.

**Comment by ajcvickers** [comment] 2020-04-01 16:31
@estyfen EF Core 3.1 is a .NET Standard 2.0 library. This means that it has a minimum .NET Framework version of 4.7.2, as described [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) and [here](https://docs.microsoft.com/en-us/ef/core/platforms/)

Are you sure all the machines you are running on have at least 4.7.2 installed?

**Comment by estyfen** [comment] 2020-04-01 16:50
> 
> 
> @estyfen EF Core 3.1 is a .NET Standard 2.0 library. This means that it has a minimum .NET Framework version of 4.7.2, as described [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) and [here](https://docs.microsoft.com/en-us/ef/core/platforms/)
> 
> Are you sure all the machines you are running on have at least 4.7.2 installed?

I will immediately check and tell you. Thank you!! @ajcvickers

**Comment by estyfen** [comment] 2020-04-02 21:43
Hi @ajcvickers , 

I did the review and testing:

1. I updated the project with target platform: .net framework 4.7.2
2. I compile and copy the Release in an isolated azure virtual machine with windows 10 Pro 64bits update available with .net framework 4.8, therefore .4.7.2 is already included.
3. I run the WinAppEFCore.exe
4. I click on the Test button, and the same error occurs :( 

> System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.TdsParser' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SNILoadHandle' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SNINativeMethodWrapper' threw an exception. ---> System.ComponentModel.Win32Exception: Failed to load C:\AppTest\Release\x86\SNI.dll

I think the problem has to do with something that you already worked on [here](https://github.com/dotnet/runtime/issues/26543)
It has some similarity but I do not see clarity of how it was solved.

**Comment by ajcvickers** [comment] 2020-04-02 21:48
@estyfen It's probably related to or [a duplicate of one the issues in the SqlClient repo](https://github.com/dotnet/SqlClient/issues?q=is%3Aissue+is%3Aopen+SNI+label%3A%22%3Apage_facing_up%3A+Native+SNI%22) I wanted to make sure you were running on a supported platform before directing you there.

@cheenamalhotra Does this look like a duplicate to you? If not it probably belongs in SqlClient.

**Comment by estyfen** [comment] 2020-04-02 22:09
@ajcvickers Thanks for your answer. I am going to do the review of open problems in sql repo.

**Comment by cheenamalhotra** [comment] 2020-04-02 22:18
> Attention: The problem does not occur on the developer machine with Visual Studio. The problem occurs on the end customer's computer.

It maybe due to missing VC++ runtime on customer's machine. Could you try referencing package "**Microsoft.Data.SqlClient.SNI:v1.1.1**" directly in your project along with **Microsoft.Data.SqlClient:1.1.1** as that removes dependency on VC++ Runtime.

**Comment by estyfen** [comment] 2020-04-02 22:48
> 
> 
> > Attention: The problem does not occur on the developer machine with Visual Studio. The problem occurs on the end customer's computer.
> 
> It maybe due to missing VC++ runtime on customer's machine. Could you try referencing package "**Microsoft.Data.SqlClient.SNI:v1.1.1**" directly in your project along with **Microsoft.Data.SqlClient:1.1.1** as that removes dependency on VC++ Runtime.

@cheenamalhotra @ajcvickers I could already solve it with your recommendation.
A thousand thanks for giving me back my life. You are a blessing to the community .  Until next time!! :)

**Closed** 2022-10-16 18:18 UTC
Labels: closed-no-further-action, customer-reported
