### ISSUE TITLE
Nuget Package Broken?? (beta7-13983)

### ISSUE THREAD

**Issue by NJKA001** [dotnet/efcore#2851] opened 2015-08-15 20:56 UTC
Hi, I'm trying to get EF7 running for the first time using VS2015 .Net (4.6) (also tried 4.5)

Following the Wicki Get Started Guide.
First this is when I do the "Add-Migration MyFirstMigration" step from the nugget console I get
"Exception has been thrown by the target of an invocation."

If I try and run the app I get the following exception from the DbContext constructor.
An unhandled exception of type 'System.TypeInitializationException' occurred in EntityFramework.Core.dll

Additional information: The type initializer for 'System.Collections.Immutable.ImmutableDictionary`2' threw an exception.

Is the Nuget package broken, of does it need some voodoo.
Thanks

**Comment by ErikEJ** [comment] 2015-08-16 07:39
Try to add this to your app.cofig:

    <runtime>
      <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a"/>
        <bindingRedirect oldVersion="1.1.36.0" newVersion="1.1.37.0"/>
      </dependentAssembly>
      </assemblyBinding>
      </runtime>

**Comment by bricelam** [comment] 2015-08-17 20:45
Yes, use a binding redirect. Roslyn is compiled against 1.1.36, but the latest is 1.1.37.

**Comment by rowanmiller** [comment] 2015-08-19 18:36
Dupe of https://github.com/aspnet/EntityFramework/issues/2855

**Closed** 2022-10-16 09:05 UTC
