### ISSUE TITLE
Value cannot be null. Parameter name: left

### ISSUE THREAD

**Issue by jceddy** [dotnet/efcore#10821] opened 2018-01-30 17:50 UTC
I am doing a LINQ join and am getting the error message "Value cannot be null. Parameter name: left".

Here's the exception:

```
e = {System.ArgumentNullException: Value cannot be null.
{System.ArgumentNullException: Value cannot be null.
Parameter name: left
   at System.Dynamic.Utils.ContractUtils.RequiresNotNull(Object value, String paramName, Int32 index)
   at System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(Expression expression, String paramName, Int32 idx)
   at System.Linq.Expressions.Expression.AndAlso(Expression left, Expression right, MethodInfo method)
   at System.Linq.Expressions.Expression.AndAlso(Expression left, Expression right)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitConditional(ConditionalExpression expression)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   at Remotion.Linq.Parsing.RelinqExpressionVisitor.VisitNew(NewExpression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MyNamespace.EntityFramework.Programmability.StoredProcedures.usp_Data_Get.Execute(Dictionary`2 parameters) in D:\path-to\MyNamespace.EntityFramework\Programmability\StoredProcedures\usp_Data_Get.cs:line 118
   at MyNamespace.EntityFramework.DatabaseProgrammabilityBase.Execute(IDbDataParameter[] parameters) in D:\path-to\MyNamespace.EntityFramework\Programmability\DatabaseProgrammabilityBase.cs:line 36
   at MyNamspace.DatabaseContextManager.GetLinqFromProcedure[T](String procedureName, Func`2 mappingFunc, DbParameter[] parameters) in D:\path-to\MyNamespace.EntityFramework\DatabaseContextManager.cs:line 293}
```

Here is the LINQ query:

```c#
var union3 = (from o in context.Organizations.Where(x => accessOrgIds.Contains(x.Id))
   join sr in context.SecurityRoles on secRoleId equals sr.Id into leftJoin
  from lj in leftJoin.DefaultIfEmpty()
  where (o.StatusId == 1)
  && (secRoleId == 0 || (lj != null && lj.Id == secRoleId))
  select new
  {
    SecurityRoleId = lj == null ? secRoleId : lj.Id,
    OrganizationId = o.Id,
    OrganizationName = o.Name,
    SecurityRoleName = lj == null ? string.Empty : lj.Name,
    IsSelected = -1,
    Description = lj == null ? null : lj.Description,
    IsSystem = lj == null ? false : lj.IsSystem,
    IsCompany = lj == null ? false : lj.IsCompany,
    StatusId = lj == null ? (short)1 : lj.StatusId,
    IsAdmin = lj == null ? false : lj.IsAdmin
  }).ToList();
```

context.Organizations references a table that contains data
context.SecurityRoles references a table that contains data
secRoleId is an int == -1

The error seems to imply that either context.Organizations or context.SecurityRoles is null, but neither of them are.

I will try to come up with a "toy" repro that I can give you...the code I'm referencing here is embedded fairly deep inside an enterprise system that would require exposing proprietary code to give much more detail than I already have.

### Further technical details
EF Core version: 2.0.1
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL (version 2.0.1)
Operating system: Windows Server 2008 R2 Standard
IDE: Visual Studio 2017 Version 15.5.3

**Comment by maumar** [comment] 2018-02-06 01:20
This issue seems to be fixed in latest bits. I tried the following repro:

```cs
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();
            }

            var accessOrgIds = new[] { 1, 2, 3 };
            var secRoleId = 1;

            using (var context = new MyContext())
            {
                var union3 = (from o in context.Organizations.Where(x => accessOrgIds.Contains(x.Id))
                              join sr in context.SecurityRoles on secRoleId equals sr.Id into leftJoin
                              from lj in leftJoin.DefaultIfEmpty()
                              where (o.StatusId == 1)
                              && (secRoleId == 0 || (lj != null && lj.Id == secRoleId))
                              select new
                              {
                                  SecurityRoleId = lj == null ? secRoleId : lj.Id,
                                  OrganizationId = o.Id,
                                  OrganizationName = o.Name,
                                  SecurityRoleName = lj == null ? string.Empty : lj.Name,
                                  IsSelected = -1,
                                  Description = lj == null ? null : lj.Description,
                                  IsSystem = lj == null ? false : lj.IsSystem,
                                  IsCompany = lj == null ? false : lj.IsCompany,
                                  StatusId = lj == null ? (short)1 : lj.StatusId,
                                  IsAdmin = lj == null ? false : lj.IsAdmin
                              }).ToList();
            }
        }
    }

    public class Organization
    {
        public int Id { get; set; }
        public int StatusId { get; set; }
        public string Name { get; set; }
    }

    public class SecurityRole
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsSystem { get; set; }
        public bool IsCompany { get; set; }
        public short StatusId { get; set; }
        public bool IsAdmin { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<SecurityRole> SecurityRoles { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=Repro10821;Trusted_Connection=True;MultipleActiveResultSets=True");
        }
    }
```

@jceddy if the repro I reverse engineered works in your environment, please let me know what are the differences between it and your actual product that does reproduce the issue (alternatively provide the complete repro, if thats easier).

**Comment by smitpatel** [comment] 2018-02-06 06:06
Duplicate of #9223

**Closed** 2022-10-16 12:07 UTC
Labels: closed-duplicate
