### ISSUE TITLE
[CONFIRMED BUG] Wrong implementation of IDesignTimeDbContextFactory is picked during migration generation!

### ISSUE THREAD

**Issue by tx8821** [dotnet/efcore#23023] opened 2020-10-16 19:05 UTC
## Setup:

I have to support both SqlServer and PostgreSQL in my project. I have my main db context class (`MyContext`) used throughout application, and for SqlServer migrations. I have another marker class `MyContextPg` derived from `MyContext` specifically used for generating migrations for PostgreSQL.

    public class MyContextPg : MyContext
    {
        public MyContextPg(DbContextOptions<MyContext> options) : base(options)
        {
            // Empty
        }
    }

Then I have two `IDesignTimeDbContextFactory` implementations to be discovered and used by migration generation tools.

For PostgreSQL:

    public class DesignTimeMyContextPgFactory : IDesignTimeDbContextFactory<MyContextPg>
    {
        public MyContextPg CreateDbContext(string[] args)
        {
            return new MyContextPg(
                new DbContextOptionsBuilder<MyContext>()
                .UseNpgsql("NOT_NEEDED")
                .Options);
        }
    }

... and for SqlServer:

    public class DesignTimeMyContextFactory : IDesignTimeDbContextFactory<MyContext>
    {
        public MyContext CreateDbContext(string[] args)
        {
            return new MyContext(
                new DbContextOptionsBuilder<MyContext>()
                .UseSqlServer("NOT_NEEDED")
                .Options);
        }
    }

I use following command to generate migrations for SQL Server for example:

`add-migration Initial -Context MyContext -OutputDir Migrations\SqlServer`

## The bug:

The problem is following: **Incorrect `IDesignTimeDbContextFactory` implementation is picked!** Instead of picking correct implementation based on context type (specified as `-Context` command line argument), it picks the first one it encounters! These two implementations are defined in same `*.cs` file, and basically if I move `DesignTimeMyContextFactory` (i.e. Sql Server variant) atop it gets picked up, and if I write `DesignTimeMyContextPgFactory` (i.e. Postgres variant) first - it gets picked up!

I'm completely unable to use `IDesignTimeDbContextFactory` method, as I can't provide more than one implementation (which is my requirement as I have to support two database providers)!

## Provider and version information:

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer **and** Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET Core 3.1
Operating system: Win 10
IDE: Visual Studio 2019

**Comment by Saibamen** [comment] 2020-10-17 09:43
What is your EF Core version (which version of `3.1` are you using)?
Your Visual Studio version?

Does this also happen in EF Core 5 RC2?

**Comment by tx8821** [comment] 2020-10-17 19:34
Here is the version info:

Startup project (ASP.NET Core Web API project):
`    <TargetFramework>netcoreapp3.1</TargetFramework>
`

Data project (where migrations are generated):
```
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.9" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.4" />
  </ItemGroup>

```
Running `dotnet --version` in PMC gives: `3.1.403`
Visual Studio 2019 version is: `16.7.6`
I'm unable to test with EF Core 5 RC versions at the moment, unfortunately.

**Comment by bricelam** [comment] 2020-10-19 02:00
Duplicate of #11611

**Comment by tx8821** [comment] 2020-10-20 15:39
@bricelam @ajcvickers So is this fixed in .NET 5.0?

**Comment by ajcvickers** [comment] 2020-10-20 15:44
@tx8821 Yes.

**Closed** 2022-10-16 19:05 UTC
Labels: customer-reported
