### ISSUE TITLE
Bind navigation property from many-to-many to entity directly

### ISSUE THREAD

**Issue by slava-se** [dotnet/efcore#32516] opened 2023-12-04 23:10 UTC
I'm implementing referral user logic and my current working implementation is

```
public class User
{
    [Key]
    public int Id { get; set; }
    public UserReferral? ReferringUser { get; set; }
    public List<UserReferral> ReferredUsers { get; set; } = null!;
}
```
```
public class UserReferral
{
    [Key]
    public int Id { get; set; }
    public int ReferringUserId { get; set; }
    public int ReferredUserId { get; set; }

    public User ReferringUser { get; set; } = null!;
    public User ReferredUser { get; set; } = null!;
}
```
As one can see on the User entity I have navigation properties to access reffering/referred users. My model configuration:

```
modelBuilder.Entity<User>()
    .HasOne(u => u.ReferringUser)
    .WithOne(u => u.ReferredUser);

modelBuilder.Entity<User>()
    .HasMany(u => u.ReferredUsers)
    .WithOne(u => u.ReferringUser)
    .HasForeignKey(u => u.ReferringUserId);
```
**Question**: Is it possible to configure mapping to have UserReferral.ReferringUser and UserReferral.ReferredUser  on the User entity directly being able to include them during data loading from DbContext skipping including the UserReferral like this?

```
public class User
{
    [Key]
    public int Id { get; set; }
    public User? ReferringUser { get; set; }
    public List<User> ReferredUsers { get; set; } = null!;
}

_dbContext.Users
.Include(u => u.ReferringUser )
.Include(u => u.ReferredUsers )
```
I'm on the latest .NET 8 / EF-Core 8, NpgSql 8

**Comment by ajcvickers** [comment] 2023-12-05 19:45
@slava-se Can a given `User` have more than one `ReferringUser`? If so, this seems like a [many-to-many relationship](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many) which can be mapped using a join table either explicitly or implicitly, as described in the docs. However, `User` would have to have two collection navs:

```C#
public class User
{
    [Key]
    public int Id { get; set; }
    public List<User> ReferringUser { get; set; } = null!;
    public List<User> ReferredUsers { get; set; } = null!;
}
```

If each `User` only has one `ReferringUser`, then I'm not sure what the join table does. Can you explain?

**Comment by slava-se** [comment] 2023-12-05 19:54
@ajcvickers you can think hier about simple referral programm.
You can share a referral/invitation link to all your friends
1) If a friend registers with your link then you will be the only referring user for his new account (1:1) so the Property describes who was your inviting person.
2) The List ReferredUsers holds all user ids who registered through the link you've shared, that could be 10000 friends who registered through your link so it's a list.
So I went hier for n:m relationship because every user can be invited but can also invite other people.
P.S. I'm aware that I could have just added int? ReferringUserId directly to the User table but prefer to not adding an additional column which will be null most of the times and the table is already big enough

**Comment by ajcvickers** [comment] 2023-12-08 12:58
Without the `ReferringUserId` column, what in the database determines which user is the referring user?

**Comment by slava-se** [comment] 2023-12-08 20:03
> Without the `ReferringUserId` column, what in the database determines which user is the referring user?

@ajcvickers  entry in UserReferral

**Comment by ajcvickers** [comment] 2023-12-09 12:10
@slava-se But when the data is saved to the database, what in the database, not in your objects, determines which user is the referring user?

**Comment by slava-se** [comment] 2023-12-12 16:10
@ajcvickers entry in the table UserReferral in the database

**Comment by ajcvickers** [comment] 2024-01-17 17:58
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-01-17 17:58 UTC
Labels: customer-reported
