### ISSUE TITLE
Nullreference exception when "navigating too far" in projection

### ISSUE THREAD

**Issue by brunolau** [dotnet/efcore#12840] opened 2018-07-29 21:37 UTC
After calling FirstOrDefault() inside Select I can't navigate to 2nd-level navigation proeperty

```
Exception message:
Object reference not set to an instance of an object.

Stack trace:
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at EfCoreErrReproduction.Program.CrashIt() in C:\Users\Bruno\Desktop\EfCoreErrReproduction\Program.cs:line 27
   at EfCoreErrReproduction.Program.Main(String[] args) in C:\Users\Bruno\Desktop\EfCoreErrReproduction\Program.cs:line 15
```

### Steps to reproduce
[EfCoreErrReproduction.zip](https://github.com/aspnet/EntityFrameworkCore/files/2239207/EfCoreErrReproduction.zip)

```c#
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace EfCoreErrReproduction
{
    class Program
    {
        static void Main(string[] args)
        {
            PrepareContext();
            CrashIt();
        }

        private static void CrashIt()
        {
            var db = new StrippedDownContext();
            var ok = db.FreerideDefinition.Where(p => p.Id == 1).Select(p => new
            {
                GuestlistName = p.Name,
                TicketName = p.FreerideDefinitionTicketDates.FirstOrDefault().TicketDate.TicketId
            }).FirstOrDefault();

            var crash = db.FreerideDefinition.Where(p => p.Id == 1).Select(p => new
            {
                GuestlistName = p.Name,
                TicketName = p.FreerideDefinitionTicketDates.FirstOrDefault().TicketDate.Ticket.Name
            }).FirstOrDefault();
        }

        private static void PrepareContext()
        {
            var db = new StrippedDownContext();
            var newTicket = new Ticket() { Name = "Ticket 1" };
            var newTicketDate = new TicketDate() { Ticket = newTicket };
            newTicket.TicketDates.Add(newTicketDate);
            db.Tickets.Add(newTicket);

            var newDefinition = new FreerideDefinition() { Name = "Definition x" };
            var newMap = new FreerideDefinitionTicketDate
            {
                FreerideDefinition = newDefinition,
                TicketDate = newTicketDate
            };

            db.FreerideDefinition.Add(newDefinition);
            db.FreerideDefinitionTicketDates.Add(newMap);
            db.SaveChanges();
        }
    }

    public class StrippedDownContext : DbContext
    {
        public StrippedDownContext()
        {
        }

        public StrippedDownContext(DbContextOptions<StrippedDownContext> options)
            : base(options)
        {
        }


        public virtual DbSet<FreerideDefinition> FreerideDefinition { get; set; }
        public virtual DbSet<FreerideDefinitionTicketDate> FreerideDefinitionTicketDates { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TicketDate> TicketDates { get; set; }


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseInMemoryDatabase(databaseName: "Add_writes_to_database");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FreerideDefinition>(entity =>
            {
                entity.ToTable("FreerideDefinition");

                entity.HasIndex(e => e.Name);
            });

            modelBuilder.Entity<FreerideDefinitionTicketDate>(entity =>
            {
                entity.ToTable("FreerideDefinitionTicketDates");

                entity.HasIndex(e => e.TicketDateId);

                entity.HasOne(d => d.FreerideDefinition)
                    .WithMany(p => p.FreerideDefinitionTicketDates)
                    .HasForeignKey(d => d.FreerideDefinitionId);

                entity.HasOne(d => d.TicketDate)
                    .WithMany(p => p.FreerideDefinitionTicketDates)
                    .HasForeignKey(d => d.TicketDateId);
            });

            modelBuilder.Entity<Ticket>(entity =>
            {
                entity.ToTable("Ticket");
            });

            modelBuilder.Entity<TicketDate>(entity =>
            {
                entity.ToTable("TicketDate");
                entity.HasOne(d => d.Ticket)
                    .WithMany(p => p.TicketDates)
                    .HasForeignKey(d => d.TicketId)
                    .OnDelete(DeleteBehavior.Cascade);
            });

        }
    }

    public partial class FreerideDefinition
    {
        public FreerideDefinition()
        {
            FreerideDefinitionTicketDates = new HashSet<FreerideDefinitionTicketDate>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<FreerideDefinitionTicketDate> FreerideDefinitionTicketDates { get; set; }
    }

    public partial class FreerideDefinitionTicketDate
    {
        public int Id { get; set; }
        public int FreerideDefinitionId { get; set; }
        public int TicketDateId { get; set; }

        public FreerideDefinition FreerideDefinition { get; set; }
        public TicketDate TicketDate { get; set; }
    }

    public partial class TicketDate
    {
        public TicketDate()
        {
            FreerideDefinitionTicketDates = new HashSet<FreerideDefinitionTicketDate>();
        }

        public TicketDate(int id) : this()
        {
            Id = id;
        }

        public int Id { get; set; }
        public int TicketId { get; set; }

        public Ticket Ticket { get; set; }
        public ICollection<FreerideDefinitionTicketDate> FreerideDefinitionTicketDates { get; set; }
    }

    public partial class Ticket
    {
        public Ticket()
        {
            TicketDates = new HashSet<TicketDate>();
        }

        public Ticket(int id) : this()
        {
            Id = id;
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<TicketDate> TicketDates { get; set; }
    }
}
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.InMemory
Operating system: Win 10 Enterprise x64
IDE: Visual Studio 2017 15.7.5

**Comment by maumar** [comment] 2018-07-31 17:55
duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/8526

**Closed** 2022-10-16 13:22 UTC
Labels: type-bug, closed-duplicate, customer-reported
