### ISSUE TITLE
SQLite: Deletion is not cascaded to untracked entities

### ISSUE THREAD

**Issue by volleyms** [dotnet/efcore#7278] opened 2016-12-20 11:37 UTC
### Observation
Even though foreign keys are defined adequately in code and database, deletion only works correctly for tracked entities, as well for one-to-zero/one relationships as for one-to-many relationships.
In case of untracked entities only the principal entities are deleted and no cascading in performed by the database, though documented differently at [https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete#cascading-to-untracked-entities]().

EF database logging shows that `PRAGMA foreign_keys=ON;` is executed, nevertheless the contraints are ignored. Executing deletion manually (e.g. with DB Browser for SQLite), deletion is cascaded correctly.

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite (1.1.0)
Operating system: Windows 10
IDE: Visual Studio 2015 (Update 3)

**Comment by ajcvickers** [comment] 2016-12-20 17:59
@volleyms I have been unable to reproduce this. Here is a console application showing cascade deletes working. Could you look at this and see what might need to be changed to reproduce what you are seeing?
```C#
public class Blog
{
    public int Id { get; set; }
    public string Title { get; set; }

    public ICollection<Post> Posts { get; set; }
}

public class Post
{
    public int Id { get; set; }
    public string Title { get; set; }

    public int BlogId { get; set; }
    public Blog Blog { get; set; }
}

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite(@"Data Source=.db");
    }
}

public class Program
{
    private static void Main()
    { 
        using (var context = new BlogContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog
            {
                Posts = new List<Post> {  new Post { Title = "Old" } }
            });

            context.SaveChanges();
        }

        using (var context = new BlogContext())
        {
            Console.WriteLine(context.Posts.Count());
        }

        using (var context = new BlogContext())
        {
            context.Remove(context.Blogs.Single());

            context.SaveChanges();
        }
        
        using (var context = new BlogContext())
        {
            Console.WriteLine(context.Posts.Count());
        }
    }
}
```

**Comment by volleyms** [comment] 2016-12-21 09:25
Hello Arthur,

thanks for the quick reply.

Please find attached a project which shows the effect after the first
deletion (the first deletion works correctly).

In my productive code I had the problem even with
"database.RemoveRange(database.Users)".


Regards

2016-12-20 18:59 GMT+01:00 Arthur Vickers <notifications@github.com>:

**Comment by ajcvickers** [comment] 2017-01-11 21:43
@volleyms The relationship between User and Setting is optional because the FK property UserId is nullable. By convention, EF will only configure cascade deletes for required relationships. You can make the relationship required by adding `.IsRequired()` to its configuration in OnModelCreating.

**Comment by volleyms** [comment] 2017-01-12 07:35
Hello Arthur,

I cannot agree:

1. UserId is defined as (part of) the primary key in both tables. The schema which is created by Add-Migration defines all primary key columns as non-nullable.

2. Even if all properties defined as keys are additionally defined as required, just like you suggested, the schema created by Add-Migration is identical, and the program behavior does not change.

3. The DeleteBehavior.OnCascade is defined in the schema as well, so it must be performed.

4. Finally, the behavior is buggy all the time: The first deletion is cascaded, the following deletions are not cascaded which is not OK as such, and leaves the database in an inconsistent/illegal state.

**Comment by ajcvickers** [comment] 2017-01-12 17:58
@volleyms I will investigate further.

**Comment by ajcvickers** [comment] 2017-01-13 18:20
Note for triage: I was able to reproduce this and it appears to be an issue with either SQLite or the provider. The database is created with the cascade delete and for the first entity deleted the cascade is applied, but for the next four it is not applied. The exact same code run against SQL Server results in all cascade deletes happening correctly.

**Comment by ajcvickers** [comment] 2017-02-01 22:34
Closing this as a dupe of #6968, which is fixed. This probably requires some explanation. What is happening here is that the connection count was being thrown off by the extra call to Close. This in turn meant that after the first delete all future deletes were being done without the pragma to turn on FKs, which meant that SQLite did not perform cascades. Also see #7527.

**Closed** 2022-10-16 10:47 UTC
