### ISSUE TITLE
Dynamic Linq predicate fails for DateTime

### ISSUE THREAD

**Issue by dixitsuneel** [dotnet/efcore#12696] opened 2018-07-17 22:07 UTC
If the model contains a DateTime field
```c#
class Entity {
   public DateTIme DateLastModified {get;set;}
}
```

if I apply a filter  using 
```c#
queryable.Where("DateLastModified>'2018-07-17'")
```

then with Ef Core 2.1 I am seeing that the query is translated to

```sql
where DateLastModified>'2018-07-17T00:00:00.0000000'
```
This leads to the sql query being failed with error Conversion failed when converting date and/or time from character string.

It wasn't an issue with Ef Core 2.0 but I am seeing this issue with Ef Core 2.1.1

I checked in EF Core 2.0 and the same code will be generated as 

```sql
WHERE [DateLastModified] > '2018-07-18T00:00:00.000'
```

This one worked without any problem. It's these extra zeroes which is causing this issue.

**Comment by dixitsuneel** [comment] 2018-07-18 17:51
Yes.

**Comment by divega** [comment] 2018-07-20 18:35
@smitpatel will find a previous issue about a similar problem.

**Comment by dixitsuneel** [comment] 2018-07-24 14:41
I think I have found the issue with EF Core 2.1. In my model I have DateTime but in the EntityConfiguration I haven't marked it to be of DateTime type. In Db it is datetime though. It seems like that EF Core 2.1 now automatically infers the sql type to be datetime2 instead of datetime now and that's why we have those extra zeroes causing the error at the db level. 

I have verified that wasn't the case with Ef 2.0. Probably this is a breaking change. I haven't seen any documentation around it in the release notes.

**Comment by smitpatel** [comment] 2018-07-24 15:23
Duplicate of #11262

**Comment by nefcanto** [comment] 2018-11-30 05:38
So, for those of us who use `datetime` field, what configuration should we do to make it work? I don't want to change my data types to `datetime2`.

**Comment by smitpatel** [comment] 2018-11-30 08:06
@nefcanto - [This Docs](https://docs.microsoft.com/en-us/ef/core/modeling/relational/data-types) provide how to configure your model on code side to map correct database type. You don't have to change your data types in your database. You just need to configure EF code model correctly with what you have in your database.

**Comment by nefcanto** [comment] 2018-11-30 09:51
Yep, that worked. Thank you.

**Closed** 2022-10-16 13:20 UTC
Labels: customer-reported
