### ISSUE TITLE
After upgrading to 2.2.0-preview3-35497 getting new errors Type.Inner not defined etc.

### ISSUE THREAD

**Issue by tannenbaums** [dotnet/efcore#13800] opened 2018-10-29 18:52 UTC
Started getting multiple errors, such as this after upgrading from 2.1.4 to 2.2.0-preview3-35497:

Field 'Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[DAL.Model.TblBusinessRule,System.Collections.Generic.IEnumerable`1[DAL.Model.TblField]].Inner' is not defined for type 'Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[DAL.Model.TblBusinessRule,DAL.Model.TblField]'

This code has been working with EF Core 2.0.2 and 2.1.4, first time getting these...

### Further technical details
EF Core version: (2.2.0-preview3-35497
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 7
IDE: (e.g. Visual Studio 2017 15.8.6)

**Comment by ajcvickers** [comment] 2018-10-29 20:30
@tannenbaums Have you updated all packages to consistent 2.2 versions? If so and you still see errors, then please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can fully investigate.

**Comment by tannenbaums** [comment] 2018-10-29 22:30
So sorry, false alarm. I had a local issue where I changed a db field from required to optional but my model still had IsRequired(). I guess the previous versions of ef where more forgiving :) we are all good. Thank you for all your help!

**Comment by tannenbaums** [comment] 2018-10-30 14:31
Hi,

Thank you so much for your response. I closed the issue below. But I do have a new question: The reason I upgraded to 2.2.0-preview3-35497
is because of a promised bug fix for bug #12482, but it seems to still be broken. I still get the same exact error, and I can see the SQL being generated looks exactly the same:

Conversion failed when converting the nvarchar value '2018-10-19' to data type bit.

exec sp_executesql N'SET NOCOUNT ON;
DECLARE @inserted0 TABLE ([Id] int, [_Position] [int]);
MERGE [tblFieldValue] USING (
VALUES (@p0, @p1, @p2, 0),
(@p3, @p4, @p5, 1),
(@p6, @p7, @p8, 2),
(@p9, @p10, @p11, 3),
(@p12, @p13, @p14, 4),
(@p15, @p16, @p17, 5)) AS i ([EntityId], [FieldId], [Value], _Position) ON 1=0
WHEN NOT MATCHED THEN
INSERT ([EntityId], [FieldId], [Value])
VALUES (i.[EntityId], i.[FieldId], i.[Value])
OUTPUT INSERTED.[Id], i._Position
INTO @inserted0;

SELECT [t].[Id] FROM [tblFieldValue] t
INNER JOIN @inserted0 i ON ([t].[Id] = [i].[Id])
ORDER BY [i].[_Position];

',N'@p0 int,@p1 int,@p2 bit,@p3 int,@p4 int,@p5 bit,@p6 int,@p7 int,@p8 nvarchar(10),@p9 int,@p10 int,@p11 nvarchar(4000),@p12 int,@p13 int,@p14 nvarchar(4000),@p15 int,@p16 int,@p17 nvarchar(4000)',@p0=36,@p1=9,@p2=1,@p3=36,@p4=10,@p5=1,@p6=36,@p7=11,@p8=N'2018-10-19',@p9=36,@p10=12,@p11=NULL,@p12=36,@p13=13,@p14=NULL,@p15=36,@p16=14,@p17=NULL


Thank you so much,
[Logo2]


Daniel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by ajcvickers** [comment] 2018-10-30 15:31
@tannenbaums #12382 has not been fixed for 2.2. This is why the issue is still "Open" and the milestone is set to "3.0".

**Comment by tannenbaums** [comment] 2018-10-30 15:39
Oh sorry about that, my bad! Appreciate your help!!

**Comment by tannenbaums** [comment] 2018-10-30 15:57
Can I ask you though:
What’s the best way to tell what bugs are fixed in just the given version? If I filter by: label:closed-fixed, I believe I get all bug fixes from all the versions…

Thank you,
Daniel Tannenbaum

**Comment by ajcvickers** [comment] 2018-10-30 16:35
@tannenbaums Go to https://github.com/aspnet/EntityFrameworkCore/milestones and then choose a milestone (you can choose an open or closed one) and click on the link for closed issues.

**Comment by tannenbaums** [comment] 2018-10-30 16:50
I see and thank you for that.
One thing I’m still not sure I understand, within milestones you have specific preview versions, how do I know which bug fixes made it to the last preview?
Thank You,
Daniel Tannenbaum

**Comment by ajcvickers** [comment] 2018-10-30 16:59
@tannenbaums The 2.2 preview 3 milestone contains everything fixed in the preview 3 release that was not already fixed before that. The 2.2.0 milestone contains everything fixed after preview 3 that will be contained in the 2.2.0 RTM release.

**Comment by tannenbaums** [comment] 2018-10-30 17:17
Oh I see.
So if I understand correctly there should be a Milestone called: The 2.2 preview 3 milestone. Is there any way for me to see it? It’s not showing up on the Milestones list…


[cid:image002.png@01D47052.DFFE9660]
Thank you,
Daniel Tannenbaum

**Closed** 2022-10-16 13:38 UTC
Labels: closed-no-further-action, customer-reported
