### ISSUE TITLE
The specified deps.json does not exist

### ISSUE THREAD

**Issue by EssamAlaa14** [dotnet/efcore#25531] opened 2021-08-16 06:58 UTC
## File a bug

Remember:

Each package is licensed to you by its owner. NuGet is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 5.11.0.10

Type 'get-help NuGet' to see all available NuGet commands.

PM> add-migration m2
Build started...
Build succeeded.
The specified deps.json [C:\Users\Essam Alaa\source\repos\WebApplication1\WebApplication1\WebApplication1.deps.json] does not exist

### Include your code

To fix any bug we must first reproduce it. To make this possible, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

It is often impossible for us to reproduce a bug when working with only code snippets since we have to guess at the missing code. 

Use triple-tick code fences for any posted code. For example:

```C#
Console.WriteLine("Hello, World!");
```

### Include verbose output

PM> dotnet ef --verbose

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.400

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
dotnet : Could not execute because the specified command or file was not found.
At line:1 char:1
+ dotnet ef --verbose
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Could not execu... was not found.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 Community latest version

**Comment by ajcvickers** [comment] 2021-08-16 08:46
Duplicate of #16386

**Closed** 2022-10-16 19:43 UTC
Labels: closed-duplicate, customer-reported
