### ISSUE TITLE
Feature: GroupBy aggregate value from owned entities

### ISSUE THREAD

**Issue by Zetanova** [dotnet/efcore#24591] opened 2021-04-05 22:01 UTC
With efcore 5 it is not possible to create an aggregate  from an owned entity.

Following throws an exception
```csharp

[Owned]
public sealed class Stats
{
     public int Value1 { get; set; }
}

var query = context.Records
.GroupBy(n => n.Category)
.Select(g => new 
{
      Category = g.Key,
      Total: g.Sum(n => n.Stats.Value1) 
});
```

Same query and it **works**
```csharp
var query = context.Records
.Select(n => new 
{
      n.Category,
      n.Stats.Value1
})
.GroupBy(n => n.Category)
.Select(g => new 
{
      Category = g.Key,
      Total: g.Sum(n => n.Value1) 
});
```

**Comment by smitpatel** [comment] 2021-04-05 22:08
Duplicate of #22609

**Comment by Zetanova** [comment] 2021-04-05 22:24
ok, did found it

**Closed** 2022-10-16 19:30 UTC
Labels: customer-reported
