### ISSUE TITLE
EF closes connection while having an open transaction

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/efcore#4643] opened 2016-02-25 13:51 UTC
I have the problem that EF closes the DB connection after the first command inside a user initiated transaction. This causes the following commit of the transaction to fail.

Example (partial):

``` csharp
using (var transaction = await dbContext.Database.BeginTransactionAsync(IsolationLevel.ReadUncommitted))
{
    var dbComic =
        await dbContext
            .Comics
            .Include(x => x.CrawlerInfo)
            .Include(x => x.CoverImage)
            .Include(x => x.ComicTags).ThenInclude(x => x.Tag)
            .SingleOrDefaultAsync(c => c.Source.Id == comicSource.Id && c.ExternalId == details.Id);
    transaction.Commit();
}
```

Output (partial):

```
Microsoft.Data.Entity.Storage.Internal.SqlServerConnection:Verbose: Opening connection 'Server=.\SQLEXPRESS;Database=Comics;Trusted_Connection=True;Integrated Security=True;'.
Microsoft.Data.Entity.Storage.Internal.SqlServerConnection:Verbose: Beginning transaction with isolation level 'ReadUncommitted'.
Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory:Verbose: Compiling query model: 'from Comic c in {value(Microsoft.Data.Entity.Query.Internal.EntityQueryable`1[ComicGrabber.Entities.Comic]) => AnnotateQuery(Include([x].CrawlerInfo)) => AnnotateQuery(Include([x].CoverImage)) => AnnotateQuery(Include([x].ComicTagsTag))} where (([c].Source.Id == __comicSource_Id_0) AndAlso ([c].ExternalId == __details_Id_1)) select [c] => SingleOrDefault()'
Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory:Verbose: Optimized query model: 'from Comic x in value(Microsoft.Data.Entity.Query.Internal.EntityQueryable`1[ComicGrabber.Entities.Comic]) where ((Convert(Property([x], "SourceId")) == __comicSource_Id_0) AndAlso ([x].ExternalId == __details_Id_1)) select [x] => SingleOrDefault()'
Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory:Verbose: Including navigation: 'ComicGrabber.Entities.Comic.ComicTags.ComicGrabber.Entities.ComicTag.Tag'
Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory:Verbose: Including navigation: 'ComicGrabber.Entities.Comic.CrawlerInfo'
Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory:Verbose: Including navigation: 'ComicGrabber.Entities.Comic.CoverImage'
Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory:Verbose: TRACKED: True
(QueryContext prm0) => IAsyncEnumerable<Comic> TaskToSequence(
    task: Task<Comic> SingleOrDefault(
        source: IAsyncEnumerable<Comic> _Include(
            queryContext: (RelationalQueryContext) prm0, 
            innerResults: IAsyncEnumerable<Comic> _Include(
                queryContext: (RelationalQueryContext) prm0, 
                innerResults: IAsyncEnumerable<Comic> _Include(
                    queryContext: (RelationalQueryContext) prm0, 
                    innerResults: IAsyncEnumerable<Comic> _ShapedQuery(
                        queryContext: prm0, 
                        commandBuilder: SelectExpression: 
                            SELECT TOP(2) [x].[Id], [x].[CoverImageId], [x].[CultureName], [x].[Description], [x].[ExternalId], [x].[Homepage], [x].[OriginalTitle], [x].[Rating], [x].[SourceId], [x].[Status], [x].[Title], [c].[Id], [c].[LastSync], [i].[Id], [i].[BlobName], [i].[FileName], [i].[Height], [i].[MimeType], [i].[Width]
                            FROM [Comic] AS [x]
                            LEFT JOIN [ComicCrawlerInfo] AS [c] ON [c].[Id] = [x].[Id]
                            LEFT JOIN [ImageInfo] AS [i] ON [x].[CoverImageId] = [i].[Id]
                            WHERE ([x].[SourceId] = @__comicSource_Id_0) AND ([x].[ExternalId] = @__details_Id_1)
                            ORDER BY [x].[Id]
                        , 
                        shaper: (ValueBuffer prm1) => Comic CreateEntity(
                            querySource: from Comic x in value(Internal.EntityQueryable`1[ComicGrabber.Entities.Comic]), 
                            valueBuffer: prm1, 
                            valueBufferOffset: 0, 
                            queryContext: prm0, 
                            entityType: ComicGrabber.Entities.Comic, 
                            trackingQuery: True, 
                            keyValueFactory: SimpleKeyValueFactory`1, 
                            materializer: (ValueBuffer prm2) => 
                            {
                                var var3
                                var3 = new Comic()
                                var3.Id = (Guid) object prm2.get_Item(0)
                                var3.CultureName = (string) object prm2.get_Item(2)
                                var3.Description = (string) object prm2.get_Item(3)
                                var3.ExternalId = (string) object prm2.get_Item(4)
                                var3.Homepage = (string) object prm2.get_Item(5)
                                var3.OriginalTitle = (string) object prm2.get_Item(6)
                                var3.Rating = (Nullable<decimal>) object prm2.get_Item(7)
                                var3.Status = (ComicStatus) object prm2.get_Item(9)
                                var3.Title = (string) object prm2.get_Item(10)
                                var3
                            }
                            , 
                            allowNullResult: False, 
                            useQueryBuffer: True
                        )
                    )
                    , 
                    entityAccessor: Unhandled expression type: Default
                    , 
                    navigationPath: INavigation[] { Comic.CoverImage, }, 
                    includeRelatedValuesStrategyFactories: new Func<IAsyncIncludeRelatedValuesStrategy>[]{ () => IAsyncIncludeRelatedValuesStrategy _CreateReferenceIncludeStrategy(
                            relationalQueryContext: (RelationalQueryContext) prm0, 
                            valueBufferOffset: 13, 
                            queryIndex: 0, 
                            materializer: (ValueBuffer prm4) => 
                            {
                                var var5
                                var5 = new ImageInfo()
                                var5.Id = (Guid) object prm4.get_Item(0)
                                var5.BlobName = (string) object prm4.get_Item(1)
                                var5.FileName = (string) object prm4.get_Item(2)
                                var5.Height = (int) object prm4.get_Item(3)
                                var5.MimeType = (string) object prm4.get_Item(4)
                                var5.Width = (int) object prm4.get_Item(5)
                                var5
                            }
                        )
                         }
                    , 
                    querySourceRequiresTracking: True
                )
                , 
                entityAccessor: Unhandled expression type: Default
                , 
                navigationPath: INavigation[] { Comic.CrawlerInfo, }, 
                includeRelatedValuesStrategyFactories: new Func<IAsyncIncludeRelatedValuesStrategy>[]{ () => IAsyncIncludeRelatedValuesStrategy _CreateReferenceIncludeStrategy(
                        relationalQueryContext: (RelationalQueryContext) prm0, 
                        valueBufferOffset: 11, 
                        queryIndex: 0, 
                        materializer: (ValueBuffer prm6) => 
                        {
                            var var7
                            var7 = new ComicCrawlerInfo()
                            var7.Id = (Guid) object prm6.get_Item(0)
                            var7.LastSync = (DateTimeOffset) object prm6.get_Item(1)
                            var7
                        }
                    )
                     }
                , 
                querySourceRequiresTracking: True
            )
            , 
            entityAccessor: Unhandled expression type: Default
            , 
            navigationPath: INavigation[] { Comic.ComicTags, ComicTag.Tag, }, 
            includeRelatedValuesStrategyFactories: new Func<IAsyncIncludeRelatedValuesStrategy>[]
            { 
                () => IAsyncIncludeRelatedValuesStrategy _CreateCollectionIncludeStrategy(
                    relatedValueBuffers: IAsyncEnumerable<ValueBuffer> _Query(
                        queryContext: prm0, 
                        commandBuilder: SelectExpression: 
                            SELECT [c].[Id], [c].[ComicId], [c].[TagId], [t].[Id], [t].[AgeRequirement], [t].[IsNsfw], [t].[Key], [t].[Name]
                            FROM [ComicTag] AS [c]
                            INNER JOIN (
                                SELECT DISTINCT TOP(2) [x].[Id]
                                FROM [Comic] AS [x]
                                WHERE ([x].[SourceId] = @__comicSource_Id_0) AND ([x].[ExternalId] = @__details_Id_1)
                            ) AS [x] ON [c].[ComicId] = [x].[Id]
                            INNER JOIN [Tag] AS [t] ON [c].[TagId] = [t].[Id]
                            ORDER BY [x].[Id]
                        , 
                        queryIndex: 1
                    )
                    , 
                    materializer: (ValueBuffer prm8) => 
                    {
                        var var9
                        var9 = new ComicTag()
                        var9.Id = (Guid) object prm8.get_Item(0)
                        var9
                    }
                )
                , 
                () => IAsyncIncludeRelatedValuesStrategy _CreateReferenceIncludeStrategy(
                    relationalQueryContext: (RelationalQueryContext) prm0, 
                    valueBufferOffset: 3, 
                    queryIndex: 1, 
                    materializer: (ValueBuffer prm10) => 
                    {
                        var var11
                        var11 = new Tag()
                        var11.Id = (Guid) object prm10.get_Item(0)
                        var11.AgeRequirement = (Nullable<int>) object prm10.get_Item(1)
                        var11.IsNsfw = (bool) object prm10.get_Item(2)
                        var11.Key = (string) object prm10.get_Item(3)
                        var11.Name = (string) object prm10.get_Item(4)
                        var11
                    }
                )

            }
            , 
            querySourceRequiresTracking: True
        )
        , 
        cancellationToken: prm0.CancellationToken
    )
)

Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (1ms) [Parameters=[@__comicSource_Id_0='?', @__details_Id_1='?'], CommandType='Text', CommandTimeout='30']
SELECT TOP(2) [x].[Id], [x].[CoverImageId], [x].[CultureName], [x].[Description], [x].[ExternalId], [x].[Homepage], [x].[OriginalTitle], [x].[Rating], [x].[SourceId], [x].[Status], [x].[Title], [c].[Id], [c].[LastSync], [i].[Id], [i].[BlobName], [i].[FileName], [i].[Height], [i].[MimeType], [i].[Width]
FROM [Comic] AS [x]
LEFT JOIN [ComicCrawlerInfo] AS [c] ON [c].[Id] = [x].[Id]
LEFT JOIN [ImageInfo] AS [i] ON [x].[CoverImageId] = [i].[Id]
WHERE ([x].[SourceId] = @__comicSource_Id_0) AND ([x].[ExternalId] = @__details_Id_1)
ORDER BY [x].[Id]
Microsoft.Data.Entity.Storage.Internal.SqlServerConnection:Verbose: Closing connection 'Server=.\SQLEXPRESS;Database=Comics;Trusted_Connection=True;Integrated Security=True;'.
Microsoft.Data.Entity.Storage.Internal.SqlServerConnection:Verbose: Committing transaction.
Ausnahme ausgelöst: "System.InvalidOperationException" in System.Data.SqlClient.dll
Ausnahme ausgelöst: "System.InvalidOperationException" in mscorlib.ni.dll
ComicGrabber.Crawler.MangaFox.MangaFoxCrawler:Error: Error while grabbing -6mm no Taboo (6mm_no_taboo): This SqlTransaction has completed; it is no longer usable.
System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
   at System.Data.SqlClient.SqlTransaction.ZombieCheck()
   at System.Data.SqlClient.SqlTransaction.Commit()
   at Microsoft.Data.Entity.Storage.RelationalTransaction.Commit()
   at ComicGrabber.Crawler.MangaFox.MangaFoxCrawler.<CrawlComicAsync>d__15.MoveNext() in C:\Users\Mark\Documents\Visual Studio 2015\Projects\SimpleComicGrabber\ComicGrabber.Crawler.MangaFox\MangaFoxCrawler.cs:line 626
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ComicGrabber.Crawler.MangaFox.MangaFoxCrawler.<CrawlAsync>d__9.MoveNext() in C:\Users\Mark\Documents\Visual Studio 2015\Projects\SimpleComicGrabber\ComicGrabber.Crawler.MangaFox\MangaFoxCrawler.cs:line 71
```

I'm using the following package:

``` json
"EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
```

This happened on a `Win10 x64` machine while debugging with `dnx-coreclr-win-x64.1.0.0-rc1-update1`.

EDIT: It also happens when I use `dnx-clr-win-x64.1.0.0-rc1-update1`.

**Comment by rowanmiller** [comment] 2016-02-26 19:45
Agreed that we should adopt the same behavior we had in EF6. The workaround for the moment is to open and close the connection manually (via `context.Database`).

**Comment by mikrasilnikov** [comment] 2016-02-28 14:44
I've also encountered this problem with RC1. It seems that EF does somthing wrong with underlying connection when including related collection of entities (like user.Blogs) when query of users returns empty result set.

```
var resultList = context.Users
   .Include(user => user.Blogs)
   .Where(user => user.Name == "Kevin")
   .ToList();

transaction.Commit(); // This will throw if there are no users with Name equal to "Kevin"
```

This also reproduces with
`.ToListAsync()`
`.SingleOrDefault()`
`.SingleOrDefaultAsync()`
`.FirstOrDefault()`
`.FirstOrDefaultAsync()`



Try this code:
```
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Microsoft.Data.Entity;

namespace EfCore_Include_ToList
{
	class Program
	{
		static void Main(string[] args)
		{
			using (var context = new BlogsContext())
			{
				context.Database.EnsureDeleted();
				context.Database.EnsureCreated();
				context.Users.Add(new User { Name = "James" });
				context.SaveChanges();
			}
			
			using (var context = new BlogsContext())
			{
				using (var transaction = context.Database.BeginTransaction(IsolationLevel.Serializable))
				{
					var emptyResults = context.Users
						// .Include(user => user.Blogs)
						.Where(user => user.Name == "Kevin")
						.ToList();

					transaction.Commit(); // Does not throw.
				}
			}
			
			using (var context = new BlogsContext())
			{
				using (var transaction = context.Database.BeginTransaction(IsolationLevel.Serializable))
				{
					var emptyResults = context.Users
						.Include(user => user.Blogs)
						.Where(user => user.Name == "Kevin")
						.ToList();

					try
					{
						transaction.Commit(); // Throws
					}
					catch (Exception e)
					{
						Console.WriteLine($"Exception: {e.Message}");
					}
				}
			}

			Console.WriteLine("done");
			Console.ReadLine();
		}
	}

	public class User
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public virtual ICollection<Blog> Blogs { get; set; }
	}

	public class Blog
	{
		public int Id { get; set; }
		public string Name { get; set; }

		public User User { get; set; }
		public int UserId { get; set; }
	}

	public class BlogsContext : DbContext
	{
		public DbSet<User> Users { get; set; }
		public DbSet<Blog> Blogs { get; set; }

		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlServer(@"Data Source=.\SQLEXPRESS;Initial Catalog=EfCore1;Integrated Security=True");
		}

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);

			modelBuilder.Entity<Blog>()
				.HasOne(b => b.User)
				.WithMany(u => u.Blogs)
				.HasForeignKey(b => b.UserId);
		}
	}
}

```

**Comment by JakeGinnivan** [comment] 2016-03-17 23:45
I am having the same issue as @mikrasilnikov. Except my issue is inside my authentication.

```
            return await _authDbContext
                .Set<Domain.User>()
                .Include(u => u.Claims)
                .FirstOrDefaultAsync(u => u.NormalisedEmail == normalizedEmail, cancellationToken: cancellationToken);
```

By adding the `.Include(u => u.Claims)` EF closes my connection after the query. The workaround suggested by @rowanmiller does not work. As far as I can tell my workaround is to go back to EF6?

**Comment by mikrasilnikov** [comment] 2016-03-18 06:52
There is a workaround (but not an efficient one).

```
public static async Task<TEntity> SafeFirstOrDefaultAsync<TEntity>(this IQueryable<TEntity> query)
	where TEntity : class
{
	if (await query.AnyAsync())
		return await query.FirstAsync();

	return default(TEntity);
}
```

**Comment by allangomessl** [comment] 2016-06-08 14:06
```
using (var transaction = _dbContext.Database.BeginTransaction())
{
    var data = _dbContext.Masters.Include(master => master.Details).ToList();
    //data.Count = 0
    transaction.Commit(); //Throw "This SqlTransaction has completed; it is no longer usable."
}

public class Master
{
     public int Id { get; set; }
     public string Name { get; set; }
     public IList<Detail> Details { get; set; }
}

public class Detail
{
     public int Id { get; set; }
     public string Name { get; set; }
}
```

**Comment by AllysonSilva** [comment] 2016-06-08 14:26
It turns out that somehow it when the result of an INNER JOIN is
empty, so Entity Framework closes the connection with the database. It is not possible to make any changes. For while this isn't resolved, I check if the DB is open so that I can work with him.


```c-sharp
var optionsBuilder = new DbContextOptionsBuilder();
optionsBuilder.UseSqlite("Filename=./App.db");

using (var context = new DbContext(optionsBuilder.Options))
{
    var connection = context.Database.GetDbConnection();
    var status = connection.State;
    
    if (status == System.Data.ConnectionState.Closed) 
    {
        
        using (var transaction = context.Database.BeginTransaction()) // OPEN DB //
        {
            try
            {
                
                var resultList = context.MyEntities
                    .Include(x => x.Include01)
                    .ThenInclude(x => x.Include001)
                    .Include(x => x.Include02)
                    .ThenInclude(x => x.Include002)
                    .ToList();

                if (status == System.Data.ConnectionState.Open)
                    transaction.Commit();
                
            } catch (Exception e) {
                
                if (status == System.Data.ConnectionState.Open)
                    transaction.Rollback();
                    
            }
        }
        
    }
}
```

**Comment by smitpatel** [comment] 2016-06-08 15:07
dupe of #5628

**Closed** 2022-10-16 09:30 UTC
Labels: type-bug
