### ISSUE TITLE
Query runs slow via EF core but fast on SSMS

### ISSUE THREAD

**Issue by meghaaprasad** [dotnet/efcore#24391] opened 2021-03-13 03:03 UTC
Hello,

I have a simple query running from my  .Net core api application using EF Core that runs very slow in application (around 30s) but on SSMS it returns in about 1s
Query is

```sql
SELECT [a].[Id], [a].[EntityId], [a].[EntityType], [a].[InputPresCount], [a].[InputUserCount], [a].[OutputDomainPresCount], [a].[OutputEmailCount], [a].[OutputUserPresCount], [a].[Priority], [a].[ProcessingEndDateUtc], [a].[ProcessingStartDateUtc], [a].[ProgressPercentage], [a].[Request], [a].[RequestTypeId], [a].[SalesPersonCompanyId], [a].[SalesPersonId], [a].[SubmittedDateUtc], [a].[UmpPermissionQueueStatusId]
FROM [PermissionQueue] AS [a]
WHERE [a].[EntityId] = 1234567
```

The [a].[Request] is nvarchar(max) type column

**Comment by roji** [comment] 2021-03-13 12:28
@meghaaprasad there's a good chance SSMS limits the number of results it asks for, whereas in EF the entire query results are retrieved - check how many rows you're actually retrieving in both cases. Also, it's worth turning on [EF's logging feature](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/simple-logging) to make sure it's sending the SQL you think it is.

Otherwise, there's not much we can do with an isolated SQL query - can you please submit a minimal EF Code repro, including a schema and data characteristics? EF

**Comment by ErikEJ** [comment] 2021-03-13 12:34
Or do you use the Async API with EF Core to read blobs?

**Comment by meghaaprasad** [comment] 2021-03-23 14:24
apologies on late reply. Yes I am querying the blob and converting to my
list using .ToListAsync(). I jave tried using .ToList() but that times out

**Comment by roji** [comment] 2021-03-23 15:40
@meghaaprasad then I think we're going to need a runnable code sample which reproduces the problem in order to investigate this...

**Comment by ayushguptacoder** [comment] 2021-03-24 03:49
@roji 
I have a similar issue where merely querying the data via EF Core is 6x slower than using SQLClient.
I have attached the benchmarks for local and remote DB. Please let me know if you want me to open a new issue and attach a sample project there.

![ActualDatabase](https://user-images.githubusercontent.com/47259520/112251746-0cb21300-8c19-11eb-9657-695139f7cb58.png)
![LocalDatabase](https://user-images.githubusercontent.com/47259520/112251750-0de34000-8c19-11eb-9737-b66166f38944.png)

**Comment by ayushguptacoder** [comment] 2021-03-24 04:27
Sample project showing 3x+ slowness when compared to SQLClient. This gets exaggerated when running against a remote database.
The project contains the migration which creates a single table and fills it with 36000 rows. The benchmark code is also in there.
[EFCoreBenchmarking.zip](https://github.com/dotnet/efcore/files/6194376/EFCoreBenchmarking.zip)
![image](https://user-images.githubusercontent.com/47259520/112254889-8dbfd900-8c1e-11eb-8fc1-3dc89454334b.png)

**Comment by roji** [comment] 2021-03-24 06:13
@ayushguptacoder thanks for the full benchmark, that's exactly what we need in order to investigate issues/performance.

* Any particular reason to use RunStrategy.ColdStart, and to limit the target count to 5? EF definitely imposes a startup overhead (e.g. query compilation), which we typically don't want to take into account when measuring; since ColdStart disables pilot and warmup, it could be including various startup actions in the measurements, skewing results.
* Your GetData_NoTracking_AsList includes a Console.WriteLine, which is sure to skew results.

After removing ColdStart and the Console.WriteLine, and adding an async SQL test, I get the following results:

```
|                         Method |      Mean |    Error |    StdDev |    Median |       Min |       Max |
|------------------------------- |----------:|---------:|----------:|----------:|----------:|----------:|
| GetData_NoTracking_AsAsyncList | 178.21 ms | 3.537 ms |  5.712 ms | 179.19 ms | 164.06 ms | 185.83 ms |
|      GetData_NoTracking_AsList | 129.74 ms | 9.373 ms | 26.893 ms | 112.52 ms | 108.72 ms | 197.52 ms |
|          RetreiveingDataViaSql |  50.46 ms | 0.374 ms |  0.331 ms |  50.44 ms |  50.04 ms |  50.94 ms |
|     RetreiveingDataViaSqlAsync | 131.31 ms | 2.615 ms |  6.163 ms | 131.62 ms | 118.30 ms | 146.32 ms |
```

This shows a x2.5 difference between EF Core and raw SQL in the sync scenario, and a x1.3 difference in the async scenario. The slowness of the async scenario here is most probably SqlClient's async implementation, which could be optimized.

Beyond this, there are some other EF high-perf features which are likely to considerably close the remaining gap; for example, EF's compiled queries remove the overhead of finding the cached SQL (and materializer/shaper). In addition, I'm currently working on improving EF Core's runtime performance, so 6.0 should improve these results further; I suggest following #23611 to see this work, and also to see how to write the EF benchmark code more efficiently.

**Comment by roji** [comment] 2021-03-24 06:17
@ayushguptacoder answered you in #24494.

**Comment by ajcvickers** [comment] 2021-04-01 16:05
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:27 UTC
Labels: closed-could-not-reproduce, customer-reported
