### ISSUE TITLE
Invalid column name when implementing delete behavior 

### ISSUE THREAD

**Issue by iriza84** [dotnet/efcore#11724] opened 2018-04-18 19:32 UTC
Hi,

Is this an issue or am I missing something?
I'm trying to implement delete behavior, as consecuence, deleting records is successful, just as I expected BUT when I try to query the data, I get errors like "Invalid column name 'MetricId1'.", of course is invalid because I never created that column, I created MetricId, so why is looking for that column?
As soon as I remove the delete behavior starts working OK, but of course I don't have this feature and I need it. Could you help me please?

OnModelCreated
```
modelBuilder.Entity<Metric>().ToTable("Metric");
            modelBuilder.Entity<Metric>().HasMany(typeof(BoardMetric)).WithOne().OnDelete(DeleteBehavior.Cascade);
```

Metric class
```
public class Metric
{
        **[Some properties here]**

        [InverseProperty("Metric"), Display(Name = "Boards")]
        public IList<BoardMetric> BoardMetrics { get; set; }
}
```

BoardMetric class
```
public class BoardMetric
{
     **[Some properties here]**

        [ForeignKey("Metric")]
        public int MetricId { get; set; }

        public Metric Metric { get; set; }
}
```

Metric Table
```
CREATE TABLE [dbo].[Metric](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	**[Some fields here]**
 CONSTRAINT [PK_Metric] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
```

BoardMetric table
```
CREATE TABLE [dbo].[BoardMetric](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MetricId] [int] NOT NULL,
	[BoardId] [int] NOT NULL,
 CONSTRAINT [PK_BoardMetric] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
```

Constraints and foreight keys
```
ALTER TABLE [dbo].[BoardMetric]  WITH CHECK ADD  CONSTRAINT [FK_BoardMetric_Board] FOREIGN KEY([BoardId])
REFERENCES [dbo].[Board] ([Id]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[BoardMetric] CHECK CONSTRAINT [FK_BoardMetric_Board]
GO

ALTER TABLE [dbo].[BoardMetric]  WITH CHECK ADD  CONSTRAINT [FK_BoardMetric_Metric] FOREIGN KEY([MetricId])
REFERENCES [dbo].[Metric] ([Id]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[BoardMetric] CHECK CONSTRAINT [FK_BoardMetric_Metric]
GO
```

**Comment by ajcvickers** [comment] 2018-04-18 22:10
Duplicate of https://github.com/aspnet/EntityFramework.Docs/issues/686 and answered there.

**Comment by iriza84** [comment] 2018-04-18 22:13
No, that didn´t solve anything

`modelBuilder.Entity<Metric>().HasMany(typeof(BoardMetric)).WithOne("Metric").OnDelete(DeleteBehavior.Cascade);`

it's still looking for MetricId1

**Comment by iriza84** [comment] 2018-04-18 22:27
well, those definitions are available, I don't know why.
Thanks a lot, it's working now.

**Closed** 2022-10-16 12:19 UTC
