### ISSUE TITLE
Numerous Issues passing a geometry parameter to a query

### ISSUE THREAD

**Issue by lawrencephillips** [dotnet/efcore#13992] opened 2018-11-21 15:18 UTC
Sample code:
```C#
var geometryFactory = new OgcCompliantGeometryFactory(new PrecisionModel(PrecisionModels.Floating), 27700);
var extentGeometry = new WKTReader(geometryFactory).Read(extent);
 var results = _Context.Cases
.Where(c => c.GridReference != null && 
  c.GridReference.Within(extentGeometry))
...
```

1. The geometry parameter is of type varbinary so queries such as: extentGeometry.Contains(c.GridReference) throw a SQL exception

2. The varbinary sent actually has the X/Y co-ordinates backwards for example:
WTK in extent string: 
```
POLYGON((371162.5815447777 102934.05565338745,
                 671089.3393572777 102934.05565338745,
		 671089.3393572777 242741.18455963745,
		 371162.5815447777 242741.18455963745,
		 371162.5815447777 102934.05565338745))
```
extentGeometry.ToString():
```
{POLYGON((371162.5815447777 102934.05565338745,
		671089.33935727773 102934.05565338745, 
		671089.33935727773 242741.18455963745, 
		371162.58154477773 242741.18455963745, 
		371162.58154477773 102934.05565338745))}
```

Intercepting the SQL sent to SQLServer
```sql
exec sp_executesql N'
SELECT CAST(@__extentGeometry_0 AS Geometry).STAsText();

SELECT [c].[Id], [c].[Address], [c].[GridReference], [c].[Ordered], [c].[PostCode], [c].[PropertyType], [c].[Source], [c].[SourceId]
FROM [Cases] AS [c]
WHERE ([c].[GridReference] IS NOT NULL AND ([c].[GridReference].STWithin(@__extentGeometry_0) = 1))',
N'@__extentGeometry_0 varbinary(112),@__cutoffDate_1 datetime2(7)',@__extentGeometry_0=0x346C000001040500000070CEF4E36021F940667980536AA7164170CEF4E36021F940B33CC0ADE27A24413867FA79A9A10D41B33CC0ADE27A24413867FA79A9A10D41667980536AA7164170CEF4E36021F940667980536AA7164101000000020000000001000000FFFFFFFF0000000003,@__cutoffDate_1='2008-11-21 00:00:00'

SELECT CAST(@__extentGeometry_0 AS Geometry).STAsText():
```
POLYGON ((102934.05565338745 371162.58154477773, 
		102934.05565338745 671089.33935727773, 
		242741.18455963745 671089.33935727773, 
		242741.18455963745 371162.58154477773, 
		102934.05565338745 371162.58154477773))
```



### Further technical details
EF Core version: 2.2.0-preview3-35497
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by ajcvickers** [comment] 2018-11-28 21:32
@lawrencephillips There isn't enough information here for us to be able to reproduce what you are seeing. Could you post a runnable project/solution or complete code listing that demonstrates the issue?

**Comment by divega** [comment] 2018-12-07 19:41
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 13:41 UTC
Labels: closed-could-not-reproduce, customer-reported
