### ISSUE TITLE
Table per Hierarchy + HasConversion: SELECT query contains the same column multiple times

### ISSUE THREAD

**Issue by sir-boformer** [dotnet/efcore#13676] opened 2018-10-18 22:28 UTC
Maybe related to #12491

I have a type hierarchy where entity subtypes store some complex metadata as JSON in a "Data" column. That means there are multiple entities sharing the same column:

```c#
    public class School : Building
    {
        [Column("Data")]
        public SchoolData Data { get; set; }
    }
    public class University : Building
    {
        [Column("Data")]
        public UniversityData Data { get; set; }
    }
```

I'm using `HasConversion` to convert the metadata objects to strings with `JsonConvert`.

Code First correctly generates a table with a single "Data" nvarchar column.

The problem: When I query the list of `Building`s, the "Data" column is listed up multiple times in the generated SQL query:

```sql
                                                        ┌──bad!──┐
SELECT [b].[Id], [b].[Address], [b].[Type], [b].[Data], [b].[Data]
FROM [Buildings] AS [b]
WHERE [b].[Type] IN (N'University', N'School')
````

The problem gets worse when there are many subtypes.

This only happens when `HasConversion` and the properties in the model have different types.

### Steps to reproduce

```c#
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace RelationPlayground.Model.Example
{
    public abstract class Building
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Address { get; set; }
    }

    public class School : Building
    {
        [Column("Data")]
        public SchoolData Data { get; set; }
    }

    public class SchoolData
    {
        public string Principal { get; set; }
    }

    public class University : Building
    {
        [Column("Data")]
        public UniversityData Data { get; set; }
    }

    public class UniversityData
    {
        public string President { get; set; }
    }

    public class SampleDbContext : DbContext
    {
        public DbSet<Building> Buildings { get; set; }

        public SampleDbContext(DbContextOptions<SampleDbContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Building>()
                .HasDiscriminator<string>("Type")
                .HasValue<School>("School")
                .HasValue<University>("University");

            modelBuilder.Entity<School>(builder =>
            {
                builder.Property(s => s.Data).HasConversion(
                    data => JsonConvert.SerializeObject(data),
                    dataString => JsonConvert.DeserializeObject<SchoolData>(dataString)
               );
            });

            modelBuilder.Entity<University>(builder =>
            {
                builder.Property(s => s.Data).HasConversion(
                    data => JsonConvert.SerializeObject(data),
                    dataString => JsonConvert.DeserializeObject<UniversityData>(dataString)
                );
            });
        }

        public List<Building> GetAllBuildings()
        {
            return Buildings.ToList();
        }
    }
}
```
Call `GetAllBuildings()` and inspect the query.

### Further technical details
EF Core version: 2.1.1
Database Provider: SQL Server
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.1

**Comment by sir-boformer** [comment] 2018-10-19 00:41
In general it seems like TPH and value converters are not playing together very well. I noticed that my value converters tried to convert the value of each row in the result set, even those with a different discriminator value.

**Comment by ajcvickers** [comment] 2018-10-22 16:39
@sir-boformer I have not been able to reproduce this on 2.1.4--I posted my full code below. Can you take a look and see what I might be missing?

```C#
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace RelationPlayground.Model.Example
{
    public class Program
    {
        public static void Main()
        {
            using (var context = new SampleDbContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                context.Add(new School {Address = "Here", Data = new SchoolData {Principal = "Bill"}});
                context.Add(new University { Address = "There", Data = new UniversityData { President = "Bob" } });

                context.SaveChanges();
            }

            using (var context = new SampleDbContext())
            {
                var buildings = context.GetAllBuildings();
            }
        }
    }

    public abstract class Building
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Address { get; set; }
    }

    public class School : Building
    {
        [Column("Data")]
        public SchoolData Data { get; set; }
    }

    public class SchoolData
    {
        public string Principal { get; set; }
    }

    public class University : Building
    {
        [Column("Data")]
        public UniversityData Data { get; set; }
    }

    public class UniversityData
    {
        public string President { get; set; }
    }

    public class SampleDbContext : DbContext
    {
        public DbSet<Building> Buildings { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Building>()
                .HasDiscriminator<string>("Type")
                .HasValue<School>("School")
                .HasValue<University>("University");

            modelBuilder.Entity<School>(builder =>
            {
                builder.Property(s => s.Data).HasConversion(
                    data => JsonConvert.SerializeObject(data),
                    dataString => JsonConvert.DeserializeObject<SchoolData>(dataString)
               );
            });

            modelBuilder.Entity<University>(builder =>
            {
                builder.Property(s => s.Data).HasConversion(
                    data => JsonConvert.SerializeObject(data),
                    dataString => JsonConvert.DeserializeObject<UniversityData>(dataString)
                );
            });
        }

        public List<Building> GetAllBuildings()
        {
            return Buildings.ToList();
        }
    }
}
```

**Comment by ajcvickers** [comment] 2018-10-29 17:45
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:36 UTC
Labels: closed-could-not-reproduce, customer-reported
