### ISSUE TITLE
Translate ImmutableHashSet<T>.Contains() and HashSet<T>.Contains()

### ISSUE THREAD

**Issue by ronnygunawan** [dotnet/efcore#18857] opened 2019-11-12 07:03 UTC
Current EF Core doesn't translate `IImmutableHashSet<T>.Contains()` and `HashSet<T>.Contains()`:
```cs
public async Task<List<Person>> GetMultipleAsync(ImmutableHashSet<int> ids) {
    return await (from p in _dbContext.People
                  where ids.Contains(p.Id)
                  select p).ToListAsync();
}

public async Task<List<Person>> GetMultipleAsync(HashSet<int> ids) {
    return await (from p in _dbContext.People
                  where ids.Contains(p.Id)
                  select p).ToListAsync();
}
```

Please add translation of `IImmutableHashSet<T>.Contains()` and `HashSet<T>.Contains()` to `Query/Internal/ContainsTranslator.cs`

**Comment by ajcvickers** [comment] 2019-11-13 16:39
@ronnygunawan Thanks for filing this issue. We will discuss in our next triage meeting.

**Comment by smitpatel** [comment] 2019-11-13 16:49
cc: @roji - did we cover these types already?

**Comment by roji** [comment] 2019-11-13 22:07
Yes, Contains on any ICollection<T> should be handled by #18634. The fix is going out in 3.1.0-preview3, which should get released in the next couple of days - @ronnygunawan can you please test on it when it's available?

**Comment by roji** [comment] 2019-11-13 22:09
Duplicate of #17342

**Closed** 2022-10-16 14:55 UTC
Labels: closed-duplicate, customer-reported
