### ISSUE TITLE
HasDefaultValueSql and ValueGeneratedOnAdd behaviour

### ISSUE THREAD

**Issue by incompletude** [dotnet/efcore#11319] opened 2018-03-18 18:33 UTC
Windows, PostgreSQL, lastest releases.

This following behavior seems a little strange:

```
                // password TEXT NOT NULL

                entity.Property(e => e.Password)
                    .HasColumnName("password")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValueSql("fn_create_password()");
                    .IsRequired();
```

If `user.Password` is null, this will throw a not null exception on password while adding. Is this expected?

Also, is there a way to access the `user.Password` reference inside `.HasDefaultValueSql()` ? 
```
                    .HasDefaultValueSql(`fn_create_password(user.Password reference?)`);
```
Thx,

**Comment by ajcvickers** [comment] 2018-03-19 19:42
@incompletude Typical use for HasDefaultValueSql is to get a value generated when none was specified. Reading between the lines it seems like what you are attempting is:
* Password property can be set or null
* Either way, password is included in the insert
* Something such as a trigger runs which changes the password as it is being saved
* That new value is read back and the entity is updated with the new value

Is this correct? (If so, I will attempt to give some guidance, but I wanted to make sure I am addressing the questions you want answered before going into details.)

**Comment by incompletude** [comment] 2018-03-19 19:59
Hey @ajcvickers, thx for all your help.

I have done the following:

```
CREATE FUNCTION tr_criar_ou_alterar_usuario()
RETURNS TRIGGER AS $$
BEGIN

    IF NEW.senha IS NOT NULL THEN

        SELECT
            ces.fn_criar_senha(NEW.senha),
            ces.fn_criar_chave()
        INTO
            NEW.senha,
            NEW.chave;

    ELSE

        NEW.senha := OLD.senha;
        NEW.chave := OLD.chave;

    END IF;

    RETURN NEW;

END; $$
LANGUAGE 'plpgsql';

CREATE TRIGGER tr_usuarios_criar_usuario
BEFORE INSERT OR UPDATE
ON usuarios
FOR EACH ROW
EXECUTE PROCEDURE tr_criar_ou_alterar_usuario();

                entity.Property(e => e.Senha)
                    .HasColumnName("senha")
                    .IsRequired();

                entity.Property(e => e.Chave)
                    .HasColumnName("chave")
                    .IsRequired();
```
On create, the password is required, and the trigger fills it correctly. On update, if the property is filled, a new password and token is also set.

Is this the correct approach?

**Comment by ajcvickers** [comment] 2018-08-10 20:05
@incompletude Sorry for being slow on this. Can you post a a runnable project/solution of complete code listing that shows the behavior of PropertySaveBehavior.Ignore?

**Comment by ajcvickers** [comment] 2018-08-27 17:35
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:14 UTC
Labels: closed-could-not-reproduce
