### ISSUE TITLE
.NET6 exception on Linq queries with EntityFramework 5

### ISSUE THREAD

**Issue by danylorudakovskyi** [dotnet/efcore#26635] opened 2021-11-10 22:44 UTC
Trying to use Microsoft.EntityFrameworkCore.Design 5.0.2 and Microsoft.EntityFrameworkCore.SqlServer 5.0.2
with .NET6. Getting this exception on all Linq queries (ToList(), FirstOrDefault(),  etc.):

System.TypeInitializationException: The type initializer for 'Microsoft.EntityFrameworkCore.Query.QueryableMethods' threw an exception.

 ```
---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethods..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Query.QueryableMethods.get_FirstOrDefaultWithPredicate()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Lmn.Express.Application.Services.Auth.AuthService.LoginAsync(CredentialDto input) in 
```

```
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethods..cctor()
```

After updating these packages to version 6.0.0 the problem is fixed. But in current project we have no ability to update these packages(

There wasn't this exception on .netcoreapp3.1.400

**Comment by smitpatel** [comment] 2021-11-11 18:30
Duplicate of #24002

**Comment by smitpatel** [comment] 2021-11-11 18:31
Patch version 5.0.5 resolved the issue.

**Comment by okarpov** [comment] 2022-10-12 17:32
still same:

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HML9ALBI2NR7", Request id "0HML9ALBI2NR7:00000142": An unhandled exception was thrown by the application.
      System.Exception: ?.........   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
         at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
         at Program.ParseParams(HttpContext context) in ...\Program.cs:line 3175
       ---> System.InvalidOperationException: Sequence contains more than one matching element
         at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
         at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
         at Program.ParseParams(HttpContext context) in \Program.cs:line 3175
         --- End of inner exception stack trace ---
         at Program.ParseParams(HttpContext context) in \Program.cs:line 3450
         at Program.<>c.<Main>b__36_56(HttpContext context) in \Program.cs:line 1494
         at lambda_method38(Closure , Object , HttpContext )
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
      --- End of stack trace from previous location ---
         at Program.<>c.<<Main>b__36_58>d.MoveNext() in \Program.cs:line 1758
      --- End of stack trace from previous location ---
         at Program.<>c.<<Main>b__36_50>d.MoveNext() in \Program.cs:line 831
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by roji** [comment] 2022-10-12 18:31
@okarpov your stack trace doesn't seem to have EF Core in it, so this seems unrelated. If you think otherwise, please open a new issue with a minimal, runnable code sample which reproduces the error.

**Comment by okarpov** [comment] 2022-10-12 19:39
sure, now I figure out it as well. But don't you like to figure out what is going on behind that? i mean it is always curiouse where we go, what we get?!

I've been working with .net core 6 + linux for the last six months, and i can confirm it really behaves different on windows and linux.

so what the hell? DotNet was declared as multi/cross - platform, and what i see? every single particular case - we get different behaviour. (((

sad to see it

**Closed** 2022-10-16 20:13 UTC
Labels: customer-reported
