### ISSUE TITLE
Enable overrides for scripted schema generation

### ISSUE THREAD

**Issue by mwwhited** [dotnet/efcore#31026] opened 2023-06-03 21:14 UTC
When generating SQL Migration scripts they are generated in a way that require customization before being included in SQL Server Projects.  

It would be nice to have the ability to either remove the `IF SCHEMA_ID(...` line entirely or at least be able to generate the migration with just the `CREATE SCHEMA` command.  

This would allow for using `dotnet ef dbcontext script ...` to target an output file directly in the sql server project without any additional post processing.

**Comment by mwwhited** [comment] 2023-06-03 21:17
My current solution is to use a custom SqlServerMigrationSqlGenerator that overloads `Generate(EnsureSchemaOperation...`

My preference would be to not have to add a custom migration and just have an additional command line parameter on the `ef dbcontext script` command

```
    public class ExtendedSqlServerMigrationsSqlGenerator : SqlServerMigrationsSqlGenerator
    {
        public ExtendedSqlServerMigrationsSqlGenerator(
            MigrationsSqlGeneratorDependencies dependencies, 
            ICommandBatchPreparer commandBatchPreparer
            ) : base(dependencies, commandBatchPreparer)
        {
        }

        protected override void Generate(
            EnsureSchemaOperation operation, 
            IModel? model, 
            MigrationCommandListBuilder builder
            )
        {
            if (string.Equals(operation.Name, "dbo", StringComparison.OrdinalIgnoreCase))
                return;

            builder
                .Append("CREATE SCHEMA "+ Dependencies.SqlGenerationHelper.DelimitIdentifier(operation.Name))
                .AppendLine(Dependencies.SqlGenerationHelper.StatementTerminator)
                .EndCommand();
        }
    }
```

**Comment by roji** [comment] 2023-06-04 10:19
@mwwhited can you provide more context on why you're trying to get rid of `IF SCHEMA_ID(`? It's perfectly legal T-SQL syntax.

**Comment by mwwhited** [comment] 2023-06-04 10:21
It is not valid in an sql server project. Use an sql server project directly importing get output of the generated script and you will see the issue.

**Comment by mwwhited** [comment] 2023-06-04 10:25
Being able to import the output directly into an sql prop gets rid of the need for migrations and schema compares.  This dramatically reduces merge issues in large teams.  It also allows ssdt/dac to do what is it good at versus messing with migration order.

**Comment by roji** [comment] 2023-06-04 10:28
Copying migration SQL into a SQL Server project certainly isn't something we've seem many people doing.. Assuming your SQL Server project is managed in source control, how do you deal with merge issues when two people update it at the same time?

Regardless, I'm assuming that the problem isn't just with schema creation, but with any T-SQL `IF` construct? If so, we use conditions in various other migrations types (e.g. database creation, checking for InMemory, checking for identity columns...); in those cases I don't think there's a simpler alternative, so I'm not sure how this could be done in a general way.

**Comment by mwwhited** [comment] 2023-06-04 10:36
The person that merged the entity model just needs to have the script regenerated.  I have this as a build task so it's transparent for the dev.  

What I've seen most others do it either just use migrations (which is a massive pain for large projects) or ignore the generated immigrations and run manual schema compares to SSDT then rollback the migration.  These are much messier options than what I am proposing.  

I have a feeling many people don't use SSDT with EF because it's so painful.  But just changing this one line of generated output and adding a single step to a build pipeline makes all the pain go away. It also opens the ability to do things like have a reference dacpac for just the dbcontext then use dacpac references so things that are directly developed with the database such are stored procedures and views.

**Comment by ajcvickers** [comment] 2023-06-04 10:44
@ErikEJ Any thoughts here?

**Comment by mwwhited** [comment] 2023-06-04 10:49
I don't recall other conditions causing issues but most more advanced features are added in the sqlproj not though EF since we don't generally use migrations. 

This is a new app I was standing up so I recently ran into this issue again.  

In some of my larger projects I also have customized migrations that have been developed over time so I may have previously worked around them and just never thought to report the suggestion.  

Long term is would be nice to have an attribute+interface that can be applied to entity classes/properties to extend migrations more easily.  Would be awesome to have an attribute to classify PII and similar fields that require masking.  I currently do this though a custom migration extension.

**Comment by roji** [comment] 2023-06-04 10:58
> The person that merged the entity model just needs to have the script regenerated. I have this as a build task so it's transparent for the dev.

I'm not really trying to argue for migrations over your approach - to each his own, and whatever works for you works for you.. But that's very similar to the way conflicts are resolved in regular migration projects: if there's a conflict because someone already pushed a migration, simply revert your own and regenerate it on top of the new one. As long as this isn't a "real" conflict (i.e. both of you touching the same column), it should be fairly transparent/mechanical.

In any case, I definitely don't know enough about sqlproj (@ErikEJ may indeed be able to help), but I'm not sure it would make sense to add a whole mode to migrations because sqlproj doesn't support full T-SQL etc. (again, given that CREATE SCHEMA most probably isn't the only problem)...

**Comment by mwwhited** [comment] 2023-06-04 11:09
Fair enough.  And you definitely do not need to take the suggestion if you guys don't want to maintain it.  Though I would note that often just because you don't hear or see things in conferences doesn't mean people don't use them.  I'm not even sure if anyone else has even tried to directly import the generated sql scripts or if they did an gave up because of issues like this.  

Again, I just thought to mention it while starting this new project before I duplicate my larger migration extension again.

**Comment by ErikEJ** [comment] 2023-06-04 11:21
Why not go full database first instead , I have support for generating DbContext and classes directly from a .sqlproj (actually a .dacpac,) both in EF Core Power Tools and as a NuGet package?

**Comment by mwwhited** [comment] 2023-06-04 11:25
I would but the majority of the teams I work with prefer code first.

**Comment by ajcvickers** [comment] 2023-06-19 13:18
We discussed this, but decided it is not an area we plan to invest. Hopefully, the SQL tools will improve such that they can handle any t-sql script.

**Closed** 2023-06-26 14:47 UTC
Labels: closed-no-further-action, customer-reported
