### ISSUE TITLE
Remove foreign entity and then delete that entity from database

### ISSUE THREAD

**Issue by TomislavSmvc** [dotnet/efcore#18953] opened 2019-11-17 09:36 UTC
In EF core 2.1 this worked just fine:
``` C#
EntityEntry<Product> product = dbContext.Attach(new Product { productid = productID.Value, bildID = null });
product.Property(x => x.bildID).IsModified = true;
Document oldBild = new Document(oldBildID.Value);
dbContext.Attach(oldBild);
dbContext.Remove(oldBild);
dbContext.SaveChanges();
```
But with EF core 3.0 this just dosn't work anymore, i get the foreign key constraint exception.

> Microsoft.EntityFrameworkCore.Update: Error: An exception occurred in the database while saving changes for context type 'EnerixBackendBLL5.DAL.MainContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Cannot delete or update a parent row: a foreign key constraint fails (`enerix_webapp_dotnet`.`product`, CONSTRAINT `FK_product_document_bildID` FOREIGN KEY (`bildID`) REFERENCES `document` (`documentid`) ON DELETE NO ACTION)
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Cannot delete or update a parent row: a foreign key constraint fails (`enerix_webapp_dotnet`.`product`, CONSTRAINT `FK_product_document_bildID` FOREIGN KEY (`bildID`) REFERENCES `document` (`documentid`) ON DELETE NO ACTION)
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 130
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 391
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 62
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 217
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)

### Further technical details

EF Core version: 3.0
Database provider: (Pomelo.EntityFrameworkCore.MySql)
Target framework: (Core 3.0)
IDE: (Visual Studio 2019 16.3.7)

**Comment by ajcvickers** [comment] 2019-11-19 22:12
@TomislavSmvc Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by TomislavSmvc** [comment] 2019-11-19 22:21
Unfortunatly i dont have the time to do that. Maybe i could do that, but idk when.

I will create it when if i catch the time for that

**Comment by ajcvickers** [comment] 2019-11-25 17:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:56 UTC
Labels: closed-could-not-reproduce, customer-reported
