### ISSUE TITLE
Could not upgrade Microsoft.EntityFrameworkCore.Design to 1.1.4

### ISSUE THREAD

**Issue by maxwang** [dotnet/efcore#10309] opened 2017-11-15 22:49 UTC
Dear Sir/Madam,

I tried to upgrade Microsoft.EntityFrameworkCore.Design from 1.1.3 to 1.1.4 from Visual Studio 2017.

But got the error as :
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: Microsoft.EntityFrameworkCore.Design from 1.1.4 to 1.1.3. Reference the package directly from the project to select a different version. 
 Website -> Microsoft.EntityFrameworkCore.Tools 1.1.4 -> Microsoft.EntityFrameworkCore.Design (>= 1.1.4) 
 Website -> Microsoft.EntityFrameworkCore.Design (>= 1.1.3)	Website	

I already checked Microsoft.EntityFrameworkCore.Tools is 1.1.4. 

### Steps to reproduce
Upgrade from Nuget Package Manager

Console.WriteLine("Hello World!");
```

### Further technical details
Visual Studio 2007 
Version 15.4.3

**Comment by smitpatel** [comment] 2017-11-15 23:02
Can you share csproj file or packages.config for Website?

**Comment by maxwang** [comment] 2017-11-16 01:18
Thank you.
My project does not have packages.config. 
Please check my project csproj:
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
  </PropertyGroup>

  <PropertyGroup>
    <UserSecretsId>aspnet-Website-7d13f2cc-4dc1-4428-a8c1-84182cfa40cf</UserSecretsId>
  </PropertyGroup>
 
  <ItemGroup>
    <PackageReference Include="AdminLTE" Version="2.3.3" />
    <PackageReference Include="Bitdefender.Webgen" Version="1.0.0" />
    <PackageReference Include="BuildBundlerMinifier" Version="2.6.362" />
    <PackageReference Include="jquery.datatables" Version="1.10.15" />
    <PackageReference Include="jQuery.UI.Combined" Version="1.12.1" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.4" />
    <PackageReference Include="Microsoft.AspNetCore.ResponseCompression" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.3" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.3" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.2" />
    <PackageReference Include="MyobProxy" Version="1.0.6" />
    <PackageReference Include="NETCore.MailKit" Version="1.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="PaulMiami.AspNetCore.Mvc.Recaptcha" Version="1.2.1" />
    <PackageReference Include="SharedLibraryCore" Version="1.0.1" />
    <PackageReference Include="Stripe.net" Version="11.5.0" />
    <PackageReference Include="System.ComponentModel.TypeConverter" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Serialization.Formatters" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Xml.XmlDocument" Version="4.3.0" />
    <PackageReference Include="ZohoBooksProxy" Version="1.0.29" />
    <PackageReference Include="ZohoCRMCoreProxy" Version="1.0.12" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.1" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="1.0.1" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Data\Migrations\" />
    <Folder Include="Views\BitDefender\Partials\" />
    <Folder Include="Views\Shared\DisplayTemplates\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Controllers\InternalHomeController.Calculator.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="appsettings.development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>

**Comment by smitpatel** [comment] 2017-11-16 01:27
I took above file and ran dotnet restore on it, it did not give me any package downgrade warnings. I also updated EFCore.Design package to 1.1.4 and it also worked without warning.

**Comment by maxwang** [comment] 2017-11-16 02:45
Hi Smit,

Thank you. It works when I manually update the csproj file. Do not know why this does not work when I tried to use NuGet package manager.

**Comment by smitpatel** [comment] 2017-11-16 02:59
I cannot say on top of my head why it doesn't work. I will try running it on my end tomorrow. But most likely this is something out of control of EF. Best thing to do would be to submit issue to VS using VS feedback system.

**Comment by maxwang** [comment] 2017-11-16 04:50
Hi Smit,

It is possible it is a bug of VS. I check out the project and create a new branch for this project with Git and tried to upgrade to 1.1.4 to have a look it works or not.
Maybe it is a package cache issue. Thanks anyway.

**Comment by ajcvickers** [comment] 2017-11-22 19:53
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:58 UTC
Labels: closed-could-not-reproduce
