### ISSUE TITLE
EF Core 2.2 group by with where condition evaluated locally

### ISSUE THREAD

**Issue by zulander1** [dotnet/efcore#14695] opened 2019-02-13 21:50 UTC
I've looked in to isuse [12255](https://github.com/aspnet/EntityFrameworkCore/issues/12255) and  [14148](https://github.com/aspnet/EntityFrameworkCore/issues/14148) it seem be the same thing..

It's wired how the log is showing twice the same message ...

```
[16:44:21 WRN] Query: '(from Payments <generated>_1 in [tpgrp] select [<generated>_1].Amount).First()' uses First/FirstOrDefault/Last/LastOrDefault operation without OrderBy and filter which may lead to unpredictable results.
[16:44:21 WRN] The LINQ expression 'GroupBy([p].Id, [p])' could not be translated and will be evaluated locally.
[16:44:21 WRN] The LINQ expression 'First()' could not be translated and will be evaluated locally.
[16:44:21 WRN] The LINQ expression 'First()' could not be translated and will be evaluated locally.
[16:44:21 WRN] The LINQ expression 'DefaultIfEmpty()' could not be translated and will be evaluated locally.
[16:44:21 WRN] The LINQ expression 'DefaultIfEmpty()' could not be translated and will be evaluated locally.
[16:44:21 WRN] The LINQ expression 'Sum()' could not be translated and will be evaluated locally.
[16:44:21 WRN] The LINQ expression 'Sum()' could not be translated and will be evaluated locally.
```

```c#

            var query = (from tp in context.TransactionLinePayments.AsNoTracking()
                         join p in context.Payments.AsNoTracking() on tp.PaymentsId equals p.Id
                         where p.Deleted == false
                         group p by p.Id into tpgrp
                         select new { tpgrp.First().Amount }
                       ).Select(x => x.Amount).DefaultIfEmpty().Sum(); 

```

Entity Framework Core 2.2.0-rtm-35687

**EDIT Fixed issue by:**
 

```
            var query = (from tp in context.TransactionLinePayments.AsNoTracking()
                         join p in context.Payments.AsNoTracking() on tp.PaymentsId equals p.Id
                         where p.Deleted == false && tp.TransactionLine.Deleted == false && tp.TransactionLine.Transaction.Deleted
                         group p by new { p.Id, p.Amount } into tpgrp
                         select new { tpgrp.Key.Amount }
                       ).Select(x => x.Amount).DefaultIfEmpty().Sum();

```

**Comment by smitpatel** [comment] 2019-02-14 02:20
Duplicate of #12088

**Closed** 2022-10-16 13:51 UTC
Labels: customer-reported
