### ISSUE TITLE
Includes Not Honored After Recreating Context

### ISSUE THREAD

**Issue by markolbert** [dotnet/efcore#7013] opened 2016-11-14 18:18 UTC
I posted a question about this over on stackoverflow (http://stackoverflow.com/questions/40594653/include-ignored-after-recreating-context), but since then I discovered a workaround which I believe highlights an issue in EF Core.

I have two entities linked in a one to many relationship:

```
public class Voter
{
    public int CountyID { get; set; }
    public County County { get; set; }
    public int VoterID { get; set; }
    public ICollection<VoterAgency> VoterAgencies { get; set; }
}

public class VoterAgency
{
    public int AgencyID { get; set; }
    public Agency Agency { get; set; }
    public int CountyID { get; set; }
    public County County { get; set; }
    public int VoterID { get; set; }
    public Voter Voter { get; set; }
}
```

I'm processing entries returned from an underlying SqlServer database in batches, and part of the processing requires checking the entries in each Voter's VoterAgency collection. I batch extract Voters by sorting on VoterID which, while not unique in and of itself, is unique when I filter based on CountyID:

```
int batch = 0;
List<Voter> dbVoters = null;

while( (dbVoters = Context.Voters
    .Include( v => v.VoterAgencies )
    .Where( v =>
        v.CountyID == County.ID
        && v.VoterAgencies.Any( va => va.AgencyID == Agency.ID ) )
    .OrderBy( v => v.VoterID )
    .Skip( batch * 1000 )
    .Take( 1000 )
    .ToList()).Count() > 0 )
{
    // do stuff
    // regenerate context
    batch++;
}
```

On the first pass through the loop, the VoterAgencies collection in the set of Voters being returned is populated, as expected (I know the Voters have VoterAgency entities related to them from checking the underlying database).

But on the next pass through the loop, after recreating the context and bumping the batch counter, the VoterAgencies collection isn't populated, although it should be.

In working the problem, I found that the following approach works as expected:

```
List<int> dbVoterIDs = Context.Voters
    .Where( v =>
           v.CountyID == County.ID
           && v.VoterAgencies.Any( va => va.AgencyID == Agency.ID ) )
    .OrderBy( v => v.VoterID )
    .Select( v => v.VoterID )
    .ToList();

    while( true )
    {
        List<int> curDbVoterIDs = dbVoterIDs.Skip( batch * _regenLines )
            .Take( _regenLines )
            .ToList();

        if( curDbVoterIDs.Count == 0 ) break;

        List<Voter> dbVoters = Context.Voters
            .Include( v => v.VoterAgencies )
            .Where( v => v.CountyID == County.ID && curDbVoterIDs.Any( x => x == v.VoterID ) )
            .ToList();

```

If I had to guess, there's a problem with something in the library's Skip code, and how it interacts with the Including logic, because the first pass through the original version's loop would not have done a skip (i.e., because batch was 0).

I can live with the workaround I discovered, but it's both counterintuitive and hits the database more often than the first, simpler approach. So if there's a way to fix the first approach, I'd love to hear it.

**Comment by rowanmiller** [comment] 2016-11-15 18:50
Can you share the SQL that is being generated for the first and second iteration?

**Comment by markolbert** [comment] 2016-11-15 20:03
I'd be happy to, but I was under the impression -- obviously wrong -- that there wasn't a way, yet, to look at the generated SQL. I'll look into how to do that, but if you'd care to share the instructions here that might be faster.

**Comment by rowanmiller** [comment] 2016-11-15 20:43
I usually just run SQL Server Profiler. You can also wire up logging in EF https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging.

**Comment by markolbert** [comment] 2016-11-15 22:29
Another personal "D'Oh!" moment: I'm embarrassed to admit how long I've been using SSMS, and never noticed, or even thought to look to see if it had, a profiler. Which is kind of an obvious feature for something like SSMS.

In any event, I was able to determine what the problem is. I've attached the t-sql export for the trace file for your reference, but here's my analysis.

EF evaluates the query in two steps: (1) grab the first/next thousand records from the Voters table, sorted by CountyID and VoterID; and (2) grab the first/next thousand records from VoterAgencies that correspond to the retrieved Voters.

The problem is in the second query. The EF generator produces the following (I've left out the parameter definitions; **@__p_2** is the number of records to skip/offset, while **@__p_3** is the number of records to take):

```
SELECT [v0].[AgencyID], [v0].[CountyID], [v0].[VoterID]
FROM [VoterAgencies] AS [v0]
WHERE EXISTS (
    SELECT 1
    FROM [Voters] AS [v]
    WHERE (([v].[CountyID] = @__County_ID_0) AND EXISTS (
        SELECT 1
        FROM [VoterAgencies] AS [va]
        WHERE ([va].[AgencyID] = @__Agency_ID_1) AND (([v].[CountyID] = [va].[CountyID]) AND ([v].[VoterID] = [va].[VoterID])))) AND (([v0].[CountyID] = [v].[CountyID]) AND ([v0].[VoterID] = [v].[VoterID]))
    ORDER BY @@ROWCOUNT
    OFFSET @__p_2 ROWS FETCH NEXT @__p_3 ROWS ONLY)
ORDER BY [v0].[VoterID], [v0].[CountyID]
```

The OFFSET clause is in the wrong place; it's currently part of the EXISTS test, which, since it returns only a single record, or null, will always result in null if you offset it by more than 0 records.

Changing the generated T-SQL to the following solves the problem:

```
SELECT [v0].[AgencyID], [v0].[CountyID], [v0].[VoterID]
FROM [VoterAgencies] AS [v0]
WHERE EXISTS (
    SELECT 1
    FROM [Voters] AS [v]
    WHERE (([v].[CountyID] = @__County_ID_0) AND EXISTS (
        SELECT 1
        FROM [VoterAgencies] AS [va]
        WHERE ([va].[AgencyID] = @__Agency_ID_1) AND (([v].[CountyID] = [va].[CountyID]) AND ([v].[VoterID] = [va].[VoterID])))) AND (([v0].[CountyID] = [v].[CountyID]) AND ([v0].[VoterID] = [v].[VoterID]))
	)
ORDER BY [v0].[VoterID], [v0].[CountyID]
OFFSET @__p_2 ROWS FETCH NEXT @__p_3 ROWS ONLY
```

This involves moving the OFFSET clause to the order query frame. Implementation is left as an exercise for the reader (sorry, couldn't resist :)).

Let me know if you need any more information. And, again, thanx for the tip on the Profiler, and the logging capability.

[Trace.txt](https://github.com/aspnet/EntityFramework/files/593292/Trace.txt)

**Comment by rowanmiller** [comment] 2016-11-15 23:20
Thanks, I think this aligns with what @smitpatel speculated. He will take a look at the issue.

**Comment by smitpatel** [comment] 2016-11-16 01:29
@markolbert - Can you try running it with EF version 1.1.0-preview1 to see if queries are working correctly? This is dupe of #5901 and it was properly fixed with #6607 which is available in preview release. I tried running a repro and we are now generating `INNER JOIN` instead of `WHERE EXISTS` which should give correct results.

**Comment by markolbert** [comment] 2016-11-16 18:56
Sure. Won't be able to get to it until later today or tomorrow, but I'll let you know if the preview release solves the problem.

**Comment by smitpatel** [comment] 2016-11-16 19:25
@markolbert - You can also use 1.1 RTM. It is released just today. 😄

**Comment by markolbert** [comment] 2016-11-17 05:16
I was unsuccessful in testing 1.1 RTM, but that may be because I hadn't actually installed 1.1 RTM.

What I did was go into project.json, and enter "1.1.0" for Microsoft.EntityFrameworkCore (it's been 1.0.1 for a while). I didn't change anything else.

Saving project.json caused an update within VS 2015. But when I ran the app it crashed on a totally unrelated part of the program, which previously had been working. The exception was:

System.TypeLoadException occurred
  HResult=-2146233054
  Message=Method 'Apply' in type 'Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationalColumnAttributeConvention' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
  Source=Microsoft.EntityFrameworkCore.Relational
  TypeName=Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationalColumnAttributeConvention
  StackTrace:
       at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationalConventionSetBuilder.AddConventions(ConventionSet conventionSet)
       at Microsoft.EntityFrameworkCore.Metadata.Conventions.SqlServerConventionSetBuilder.AddConventions(ConventionSet conventionSet)
       at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
       at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
       at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
       at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
       at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
       at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.<>c.<AddQuery>b__1_1(IServiceProvider p)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
       at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
       at Microsoft.EntityFrameworkCore.DbContext.get_QueryProvider()
       at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.<.ctor>b__3_0()
       at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
       at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
       at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
       at UploadProcessor.DataJob.Initialize() in C:\Programming\ConnellCampaigns\src\UploadProcessor\DataJob.cs:line 47
  InnerException: 

If there's another way to install 1.1 RTM, rather than through project.json, please let me know and I'll try again.

**Comment by divega** [comment] 2016-11-17 05:43
@markolbert the error shows a version mismatch between Microsoft.EntityFrameworkCore and Microsoft.EntityFrameworkCore.Relational. Please try updating all the Microsoft .NET libraries that were 1.0.x to 1.1.0 at the same time.

**Comment by markolbert** [comment] 2016-11-17 06:48
Thanx. I updated all of the EF & ASPNET/MVC stuff via NuGet at the solution level and the exception went away.

More importantly, the problem with not populating the related collection on the second, third,... passes after context regeneration also went away.

Thanks for the quick replies and help.

**Comment by markolbert** [comment] 2016-11-17 16:46
As a possibly-unrelated follow-up, I had to revert back to 1.0.0 because upgrading broke my MVC Core app. The exception was:

System.IO.FileLoadException was unhandled
Message: An unhandled exception of type 'System.IO.FileLoadException' occurred in Unknown Module.
Additional information: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by markolbert** [comment] 2016-11-17 16:55
Well, reverting >>didn't<< solve the problem. Now I get:

System.IO.FileLoadException was unhandled
Message: An unhandled exception of type 'System.IO.FileLoadException' occurred in Unknown Module.
Additional information: Could not load file or assembly 'Microsoft.AspNetCore.Hosting, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I cannot find ANY reference to AspNetCore.Hosting in my project.json files. What the heck is going on?

No offense, but suggesting that people test stuff shouldn't result in wrecking their ability to do work...

**Comment by divega** [comment] 2016-11-17 16:57
@markolbert at first glance those exceptions both seem like version mismatches as well. If you can post your project.json we may be able to help.

**Comment by markolbert** [comment] 2016-11-17 17:24
Here you go:

```
{
  "userSecretsId": "aspnet-ConnellCampaigns-ddb1a50a-eba1-4870-91d4-4d26457f64ce",

  "dependencies": {
    "AutoMapper": "5.1.1",
    "BundlerMinifier.Core": "2.2.296",
    "ConnellData": "1.0.0-*",
    "ConnellDataCore": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Azure.WebJobs": "1.1.2",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.1",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.Extensions.Caching.Memory": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.WindowsAzure.ConfigurationManager": "3.2.3",
    "Serilog": "2.3.0",
    "Serilog.Extensions.Logging": "1.2.0",
    "Serilog.Sinks.Literate": "2.0.0",
    "Serilog.Sinks.RollingFile": "3.2.0",
    "UploadFramework": "1.0.0-*",
    "WindowsAzure.Storage": "7.2.1"
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "net46": {
      "frameworkAssemblies": {
        "System.IO.Compression": "4.0.0.0"
      },
      "dependencies": {
      }
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

```

**Comment by markolbert** [comment] 2016-11-17 17:33
Based on advice from over on the AspNetCore site, I cleared the bin directory and rebuilt the solution, which solved the problem.

 The app's config file had a lot of references to later versions of assemblies that it shouldn't have contained after I regressed the app. 

But what confuses me is that I did a "Clean Solution" and Rebuild before asking for help, because I've seen similar problems caused by cruft. I thought "Clean Solution" wiped out the contents of the bin directory...but it didn't in this case (I checked). I had to delete the directory contents manually. Apparently, the behavior of Clean changed somewhere along the way. When did that happen?

**Comment by divega** [comment] 2016-11-17 18:30
Glad you got it to work again. Curious, is the app now working in 1.0 or 1.1? I suspect the two erros you saw had similar causes.

>... Apparently, the behavior of Clean changed somewhere along the way... 

Not completely sure but it sounds like it could be an issue with project.json-based tooling. Since we are in the process of switching to MSBuild based projects it is unlikely that the same issue will apply. In the meanwhile please use the workaround.

**Comment by smitpatel** [comment] 2016-11-21 23:13
@divega - Close this since the app is working again?

**Closed** 2022-10-16 10:42 UTC
