### ISSUE TITLE
Can't update row when UseHistoryTable is enabled.

### ISSUE THREAD

**Issue by warkakw** [dotnet/efcore#33397] opened 2024-03-25 20:49 UTC
Hi 

Microsoft.EntityFrameworkCore: 8.0.3
Microsoft.EntityFrameworkCore.SqlServer: 8.0.3

I use EF Core Power Tools with Reverse Engineer.

My MS SQL db table has system versioning on. Data table and historical table have equals columns. 

Autogenereted context has this:

       .ToTable(tb => tb.IsTemporal(ttb =>
            {
                ttb.UseHistoryTable("Project", "history");
                ttb
                    .HasPeriodStart("SysStartTime")
                    .HasColumnName("SysStartTime");
                ttb
                    .HasPeriodEnd("SysEndTime")
                    .HasColumnName("SysEndTime");
            }));

When I try update row i see error: 

"Unable to cast object of type 'System.Int32' to type 'System.DateTime'." in

   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.<ConsumeResultSetAsync>d__4.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.<ConsumeAsync>d__2.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__50.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__50.MoveNext()
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.<ExecuteAsync>d__15.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__111.MoveNext()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__115.MoveNext()
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__63.MoveNext()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__63.MoveNext()

If I remove code in context file (shown above) update works.

**Comment by ErikEJ** [comment] 2024-03-26 07:04
Are you generating from a .dacpac?

**Comment by warkakw** [comment] 2024-03-26 07:59
No, like this:
![image](https://github.com/dotnet/efcore/assets/25364534/e0b1d21e-b08e-4189-848e-f1f3686e6f49)
![image](https://github.com/dotnet/efcore/assets/25364534/fbeb56a0-eed1-4c79-978a-0f6735e822b2)
![image](https://github.com/dotnet/efcore/assets/25364534/75f0a0bb-8c2a-487a-8e1e-28d459631e1a)
![image](https://github.com/dotnet/efcore/assets/25364534/d63033e0-066c-414f-bb74-c4cd6c137a2c)
![image](https://github.com/dotnet/efcore/assets/25364534/cd391edf-9fb1-4c79-8dc6-778ee607c673)

What is interesting, other tables with history works properly.

**Comment by maumar** [comment] 2024-04-11 00:55
can you try latest EF 9 preview? We have done a large refactoring to how migrations deal with temporal tables, which fixes a lot of bugs in the area - https://github.com/dotnet/efcore/pull/32239

**Comment by ajcvickers** [comment] 2024-05-15 13:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-05-15 13:20 UTC
Labels: customer-reported, area-save-changes, area-sqlserver, area-temporal-tables
