### ISSUE TITLE
ArgumentNullException thrown during migration using .NET 5 preview 3

### ISSUE THREAD

**Issue by martincostello** [dotnet/efcore#20755] opened 2020-04-26 14:28 UTC
When running an existing working DB migration with .NET Core 3.1 against .NET 5 preview 3, an `ArgumentNullException` is thrown with the message `"Value cannot be null. (Parameter 'o')"`

```
   System.ArgumentNullException : Value cannot be null. (Parameter 'o')
  Stack Trace:
     at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommandListBuilder.Append(Object o)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.ColumnDefinition(String schema, String table, Str
ing name, ColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.ColumnDefinition(String schema, String t
able, String name, ColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.ColumnDefinition(AddColumnOperation operation, IM
odel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.CreateTableColumns(CreateTableOperation operation
, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(CreateTableOperation operation, IModel m
odel, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(CreateTableOperation operation,
 IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__71_11(MigrationsSqlGenerator g, Mi
grationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel mod
el, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, I
Model model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model
)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IMo
del model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass15_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken
 cancellationToken)
   at TodoApp.Tests.TodoRepositoryTests.Can_Create_Update_And_Delete_Todo_Items() in C:\Coding\sqllocaldb\samples\TodoA
pp.Tests\TodoRepositoryTests.cs:line 53
--- End of stack trace from previous location ---
```

### Steps to reproduce

To reproduce, follow these steps:

  1. Clone https://github.com/martincostello/sqllocaldb/pull/234/commits/df356c6f631454a5f867ffbeaa90810f1d252c0d
  1. ` cd .\samples\TodoApp.Tests\`
  1. `dotnet test`

Example logs from CI build for the above commit: [logs](https://github.com/martincostello/sqllocaldb/pull/234/checks?check_run_id=619868802#step:4:109)

### Further technical details

EF Core version: `5.0.0-preview.3.20181.2`
Database provider: `Microsoft.EntityFrameworkCore.SqlServer`
Target framework: `.NET 5 preview 3 (SDK 5.0.100-preview.3.20216.6)`
Operating system: `Windows 10 x64 (10.0.18362)`
IDE: `Microsoft Visual Studio Enterprise 2019 Preview 16.6.0 Preview 4.0`

**Comment by ajcvickers** [comment] 2020-04-27 19:23
@martincostello Can you try with the latest [daily build](https://github.com/dotnet/aspnetcore/blob/master/docs/DailyBuilds.md)? We made some recent changes that may have also fixed this.

**Comment by martincostello** [comment] 2020-04-27 20:24
@ajcvickers Test passes with `5.0.0-preview.5.20227.1`.

**Comment by ajcvickers** [comment] 2020-04-27 21:04
@AndriySvyryd @bricelam Dupe or close as fixed in 5?

**Comment by AndriySvyryd** [comment] 2020-04-28 01:03
Duplicate of https://github.com/dotnet/efcore/issues/20517

**Closed** 2022-10-16 18:22 UTC
Labels: customer-reported
