### ISSUE TITLE
ArgumentOutOfRangeException when using DefaultIfEmpty

### ISSUE THREAD

**Issue by joshmouch** [dotnet/efcore#7925] opened 2017-03-17 16:30 UTC
I'm using version 1.1.1 and am currently trying to find a workaround for the problem I reported here: https://github.com/aspnet/EntityFramework/issues/7915.

So I've rewritten the LINQ query to use DefaultIfEmpty(), but now I'm getting an ArgumentOutOfRangeException from the QueryCompiler.

Here is the query:

````

var results = (from e1 in this.Repository.DataContext.EntityOne
                                from e2 in e1.EntityTwo.DefaultIfEmpty()
								select new
                                {
                                    e1.PropertyOne,
                                }
    ).ToList();

````

And here are the exception details:

> 
> System.ArgumentOutOfRangeException occurred
>   HResult=0x80131502
>   Message=Index was out of range. Must be non-negative and less than the size of the collection.
>   Source=<Cannot evaluate the exception source>
>   StackTrace:
> <Cannot evaluate the exception stack trace>
> 
>    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>    at System.Collections.ObjectModel.Collection`1.RemoveAt(Int32 index)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.RewriteSelectManyNavigationsIntoJoins(QuerySourceReferenceExpression outerQuerySourceReferenceExpression, IEnumerable`1 navigations, AdditionalFromClause additionalFromClauseBeingProcessed)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.RewriteNavigationProperties(List`1 properties, IQuerySource querySource, Expression declaringExpression, String propertyName, Type propertyType, Func`2 propertyCreator, Func`2 conditionalAccessPropertyCreator)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.<>c__DisplayClass20_0.<VisitMember>b__0(IEnumerable`1 ps, IQuerySource qs)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindPropertyExpressionCore[TResult](Expression propertyExpression, IQuerySource querySource, Func`3 propertyBinder)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindNavigationPathPropertyExpression[TResult](Expression propertyExpression, Func`3 propertyBinder)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitMember(MemberExpression node)
>    at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
>    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>    at Remotion.Linq.Clauses.FromClauseBase.TransformExpressions(Func`2 transformation)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ExpressionTransformingQueryModelVisitor`1.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
>    at Remotion.Linq.Clauses.MainFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
>    at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
>    at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
>    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>    at Remotion.Linq.Clauses.FromClauseBase.TransformExpressions(Func`2 transformation)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.NavigationRewritingQueryModelVisitor.VisitAdditionalFromClause(AdditionalFromClause fromClause, QueryModel queryModel, Int32 index)
>    at Remotion.Linq.Clauses.AdditionalFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
>    at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
>    at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
>    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
>    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
>    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
>    at Remotion.Linq.QueryableBase`1.GetEnumerator()
>    at LinqKit.ExpandableQuery`1.GetEnumerator()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>

**Comment by maumar** [comment] 2017-03-17 17:41
duplicate of #6879 (fixed in 2.0.0)

**Closed** 2022-10-16 10:57 UTC
Labels: closed-duplicate
