### ISSUE TITLE
Using HasKey(...).IsClustered() generates invalid code inside database snapshot

### ISSUE THREAD

**Issue by JakeYallop** [dotnet/efcore#26179] opened 2021-09-26 18:37 UTC
Runnable repro [here](https://github.com/JakeYallop/EFCoreIsClusteredRepro).

The following code  `HasKey(...).IsClustered()`:

```csharp
using Microsoft.EntityFrameworkCore;

Console.WriteLine("Hello, World!");

public class Context : DbContext
{
    public DbSet<MyObject> MyObjects { get; set; } = null!;
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\MSSQLLocalDB;Integrated Security=true");
        base.OnConfiguring(optionsBuilder);
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MyObject>().HasKey(x => x.Id).IsClustered();
        base.OnModelCreating(modelBuilder);
    }

}

public class MyObject
{
    public int Id { get; set; }
    public string Property { get; set; } = null!;
}
```

Generates the following code for the database model snapshot after running `dotnet ef migrations add initial`:

```csharp
// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreIsClusteredRepro.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.1.21452.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b); //<--- compile time error here

                    b.ToTable("MyObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
```

Which throws the following error at compile time:

```
CS1503	Argument 1: cannot convert from 'Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder' to 'Microsoft.EntityFrameworkCore.Metadata.Builders.KeyBuilder'
```

This build error also prevents the user from removing the migration without manually fixing the code, as the build fails.

### Include provider and version information

EF Core version:  6.0.0-rc.1.21452.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0 RC1

```
> dotnet ef --version
Entity Framework Core .NET Command-line Tools
6.0.0-preview.6.21352.1
```

**Comment by roji** [comment] 2021-09-26 18:42
Duplicate of #26045

**Comment by roji** [comment] 2021-09-26 18:42
This has been fixed for rc2, can you try a daily build and confirm that the issue is fixed there?

**Comment by JakeYallop** [comment] 2021-09-26 19:02
Tested with the latest daily build and can confirm the issue is no longer reproduceable.

**Closed** 2022-10-16 20:09 UTC
Labels: closed-duplicate, customer-reported
