### ISSUE TITLE
No DbContext was found in assembly 'CoreDatabaseStandard'.

### ISSUE THREAD

**Issue by kbrow20** [dotnet/efcore#25230] opened 2021-07-09 18:37 UTC
I am getting the following error:

No DbContext was found in assembly 'CoreDatabaseStandard'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

![image](https://user-images.githubusercontent.com/5554132/125121097-07d67980-e0b9-11eb-98f3-18599a1e517d.png)

I had to downgrade my EF project thanks to PhotonServer not supporting Core .Net 1 to 3 and .Net 5. So I had to make my new EF project 2.0 Net Standard Library to have it work with .Net Framework. It was working previously when I had all my projects at .Net5. So I have a PhotonServer application that is running at .Net 4.7.2 and WebAPI that is running at .Net5. 

So I am having a hard time running Add-Migration Initialize -Project CoreDatabaseStandard

Plus in my WebAPI it seems that it isn't getting the users out of the database that was created from my previous database project that was using .Net5.  

```C#
        [UseDbContext(typeof(AppDbContext))]
         public async Task<AuthenticatedToken> GetAuthenticationToken(AuthenticationTokenInput authenticationTokenInput, [ScopedService] AppDbContext context, [Service] UserManager<AccountUser> userManager, [Service] ITopicEventSender eventSender, CancellationToken cancellationToken)
         {
              AccountUser user = await userManager.FindByNameAsync(authenticationTokenInput.UserName); <= Errors out right here
              bool confirmed = await userManager.CheckPasswordAsync(user, authenticationTokenInput.Password);
         }

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using System;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace CoreDatabaseStandard.EntityFramework
{
      public class AppDbContext : IdentityDbContext<AccountUser, IdentityRole<int>, int>
      {
      }
}
```

I also can't seem to find a good way with my AppDbContext to create a Initializer so I can populate data into my tables. 
I find plenty on how to do it with EntityFramework that isn't related to IdentityDbContext. I just want to do this:

```C#
public DbSet<Galaxy> Galaxies { get; set; } <= Insert MilkyWay
public DbSet<Planet> Planets { get; set; } <= Insert Earth, Mars, and etc
```

**Comment by ajcvickers** [comment] 2021-07-11 14:05
@kbrow20 Mixing EF Core versions like this is not supported. In particular, the Identity reference is bringing in and expecting a 2.x version of EF Core, while you are directly referencing EF Core 3.1. Note also that ASP.NET Core and EF Core 2.2 are [no longer supported](https://docs.microsoft.com/en-us/ef/core/what-is-new/). You will need to update everything to 3.1 or 5.0, or alternately downgrade everything to 2.1, although keep in mind that 2.1 goes out-of-support in August.

**Comment by kbrow20** [comment] 2021-07-12 18:03
@ajcvickers so I have to go to 2.1?  I don't want to do this at all. I want to stay with .net5. I have to stay with .net standard 2.0 until Photon Server supports .net5 or core. I need EF to work with .Net Framework 4.7.2.

**Comment by ErikEJ** [comment] 2021-07-12 18:15
EF Core 3.1 runs under .net Framework

**Comment by kbrow20** [comment] 2021-07-13 13:06
@ErikEJ So my issue is I need to find the EF Core 3.1 for the Identity?

**Comment by ErikEJ** [comment] 2021-07-13 13:13
If you want EF Core and Identity to work with .NET Framework, you must stay at 2.1 or 2.2.

**Comment by kbrow20** [comment] 2021-07-13 13:20
![image](https://user-images.githubusercontent.com/5554132/125458825-02fc221a-ea4f-4ab2-be9a-e751f53d4937.png)

So is this better?

**Comment by kbrow20** [comment] 2021-07-13 13:34
@ErikEJ Like I said I don't want to be using this. Third party dependencies are forcing me to use it. What dll do I use with these to create a initializer to inject data into my tables? The other issue I will downgrade my stuff and test again.

**Comment by ErikEJ** [comment] 2021-07-13 13:36
This? https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding

**Comment by kbrow20** [comment] 2021-07-13 14:06
```
modelBuilder.Entity<Planet>().HasData(
                new Planet
                {
                    Id = 1,
                    PlanetName = "Mercury"
                }
            );
            modelBuilder.Entity<Planet>().HasData(
                new Planet
                {
                    Id = 2,
                    PlanetName = "Venus"
                }
            );
            modelBuilder.Entity<Planet>().HasData(
                new Planet
                {
                    Id = 3,
                    PlanetName = "Earth"
                }
            );
            modelBuilder.Entity<Planet>().HasData(
                new Planet
                {
                    Id = 4,
                    PlanetName = "Mars"
                }
            );
```

So this approach will add the records into the table inside of the OnModelCreating?

**Comment by ajcvickers** [comment] 2021-07-16 16:35
@kbrow20 Do you have any further specific questions?

**Comment by ajcvickers** [comment] 2021-07-23 16:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:39 UTC
Labels: closed-no-further-action, customer-reported
