### ISSUE TITLE
Insert fails when model has tables with same name in different schemas

### ISSUE THREAD

**Issue by Alexander-Leontiev** [dotnet/efcore#30087] opened 2023-01-18 07:26 UTC
I'm in progress of updating EF Core to version 7 from 3.
In my DB model I have some tables, which have same names but different schemas. My current EF Core 3.1.15 copes well with it.
However EF Core 7.0.1 fails to handle it. If I try to save new entities for different schemas at once, EF generates wrong queries with negative values for FK columns.

My model looks like the following:

```
[Table("User", Schema = "dbo")]
public class User {
    [Key]
    public int Id { get; set; }
    public string Name { get; set; }
    
    public virtual UserSettings Settings { get; set; }
    public virtual UserSettingsAnotherSchema AnotherSettings { get; set; }
} 

[Table("UserSettings", Schema = "dbo")]
public class UserSettings {
    [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int UserId { get; set; }

    public string SomeColumn { get; set; }

    public virtual User User { get; set; }
}

[Table("UserSettings", Schema = "another")]
public class UserSettingsAnotherSchema {
    [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int UserId { get; set; }
    public string AnotherColumn { get; set; }
        
    public virtual User User { get; set; }
}
```

When I try to save new User with Settings properties been initialized, EF generates queries like:

```
exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [dbo].[User] ([Name])
OUTPUT INSERTED.[Id]
VALUES (@p0);
INSERT INTO [dbo].[UserSettings] ([UserId], [SomeColumn])
VALUES (@p1, @p2);
',N'@p0 nvarchar(4000),@p1 int,@p2 nvarchar(4000)',@p0=N'test2',@p1=-2147482647,@p2=N'test2'

exec sp_executesql N'SET NOCOUNT ON;
MERGE [dbo].[User] USING (
VALUES (@p0, 0),
(@p1, 1)) AS i ([Name], _Position) ON 1=0
WHEN NOT MATCHED THEN
INSERT ([Name])
VALUES (i.[Name])
OUTPUT INSERTED.[Id], i._Position;
INSERT INTO [dbo].[UserSettings] ([UserId], [SomeColumn])
VALUES (@p2, @p3),
(@p4, @p5);
',N'@p0 nvarchar(4000),@p1 nvarchar(4000),@p2 int,@p3 nvarchar(4000),@p4 int,@p5 nvarchar(4000)',@p0=N'test2',@p1=N'test1',@p2=-2147482647,@p3=N'test2',@p4=-2147482646,@p5=N'test1'
```

As you can see, instead of using generated PK value from parent table EF tries to insert some synthetic negative values into FK columns of child tables.

Project to reproduce the issue: [EfTest.zip](https://github.com/dotnet/efcore/files/10443012/EfTest.zip)

EF Core version: 7.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: net6.0

**Comment by roji** [comment] 2023-01-18 09:56
@Alexander-Leontiev can you please try the latest 8.0 [daily build](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md)? There have been several fixes around this area for 7.0.2 and 7.0.3, testing the daily build would tell us whether your issue is a dup of one of those.

**Comment by Alexander-Leontiev** [comment] 2023-01-18 10:48
@roji 7.0.2 still has the issue. 7.0.3 failed to be restored.
However, 8.0.0-alpha.1.23067.1 fixes my issue. I hope it's possible to backport it to some 7.* release.

**Comment by roji** [comment] 2023-01-18 10:55
If 7.0.0 fixed the issue, then 7.0.3 already contained the fix - all the fixes in this area have already been backported.

**Comment by Alexander-Leontiev** [comment] 2023-01-18 10:58
@roji sounds great! When 7.0.3 public release is expected?

**Comment by roji** [comment] 2023-01-18 11:03
Not long - in mid-February.

**Comment by ajcvickers** [comment] 2023-01-19 14:54
Duplicate of #29741

**Closed by ajcvickers** 2023-01-19 14:54 UTC
Labels: customer-reported
