### ISSUE TITLE
Disposing DbContext scoped to a Razor component lifetime throws InvalidOperationException on quick refreshes

### ISSUE THREAD

**Issue by amal-stack** [dotnet/efcore#25291] opened 2021-07-20 10:22 UTC
I'm trying to scope a DB Context to the lifetime of a Razor component that needs to execute a lot of queries throughout its lifetime. I found this as a better alternative to creating a new DB Context per operation and I am following the instructions at [Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0#scope-to-the-component-lifetime-5x).
## Context
I have a `DbContext` which is created in `OnInitializedAsync()`  of a Razor component using the injected `IDbContextFactory<AppDbContext>` and scoped to the lifetime of a Razor component. For this, the Razor component implements `IDisposable` and hence has a `Dispose` method. There is a complex EF Core query being executed in `OnInitializedAsync`. A flag `isDbContextBusy` indicates if the DB context is busy.

## Code
```razor
@inject IDbContextFactory<AppDbContext>
@implements IDisposable

...
@code {
    private AppDbContext dbContext;
    private bool isDbContextBusy;

    protected override async Task OnInitializedAsync()
    {
        dbContext = DbContextFactory.CreateDbContext();
        isDbContextBusy = true;
        try { var entites = await dbContext.Entites.AsSplitQuery().{Any Complex Query Here }; }
        finally { isDbContextBusy = false; }
    }
    
    public void Dispose() => dbContext?.Dispose();
}
```
## Problem
This works as expected. However, when I keep hitting refresh multiple times quickly in succession(as a minor stress test), the `dbContext?.Dispose()` in the component's `Dispose()` method ends up throwing an `InvalidOperationException` exception:
```
System.InvalidOperationException: 'Can't close, connection is in state Connecting'
``` 
I suppose refreshing the page ends the lifetime of the component which then attempts to call `Dispose()` before the `DbContext` is initialized. 
### Stack Trace
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Can't close, connection is in state Connecting
  Source=Npgsql
  StackTrace:
   at Npgsql.NpgsqlConnection.Close(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.Close()
   at Npgsql.NpgsqlConnection.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.EntityFrameworkCore.DbContext.Dispose()
   at KSD.ModelCollege.LearningAssessmentSystem.Areas.Users.Views.Accounts.InputStudentInfo.Dispose() in {Project Directory}\Areas\Users\Views\Accounts\InputStudentInfo.razor:line 247
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)

```

### Provider and version information

EF Core version: 5.0.6
Database provider: Npgsql (5.0.5)
Target framework: .NET 5.0
Operating system: Microsoft Windows Version 21H1 (OS Build 19043.1110)
IDE: Visual Studio 2019 16.10.3

**Comment by amal-stack** [comment] 2021-07-22 05:39
@JeremyLikness It would be great if you can suggest a temporary workaround or alternative solution to deal with this scenario. Or do you think the only way  is to use a `DbContext` per operation?

**Comment by JeremyLikness** [comment] 2021-09-14 19:53
@amal-stack can you tell me why you're trying to persist the context? Contexts spin up fast so there shouldn't be a performance concern, especially since it is in the context of the user (i.e. this doesn't necessarily help with concurrency because simultaneous users get their own contexts anyway). The whole purpose of introducing the factory and per-operation was to avoid side effects of the unique context in the scenario you are mentioning. If there is something flawed with the per-operation approach I'd love that feedback, otherwise that is my recommendation. Let me know in case there is something we need to address in code or docs.

**Comment by amal-stack** [comment] 2021-09-19 18:07
@JeremyLikness I actually have a component where child entities are lazy-loaded. I had a list of parent entities, where every time a user would click on one of the items, its child entities would be loaded from the database. This is similar to a case when a user would select a country and then the states of the country would appear.  I came across [this](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0#scope-to-the-component-lifetime-1) section of the docs which mentions scoping a context to the component lifetime as a possible alternative and just wanted to report this caveat. At the moment, I am using a context per operation and it works perfectly fine.

**Comment by JeremyLikness** [comment] 2021-12-21 17:03
@amal-stack I'm trying to reproduce this but am not getting the same error. Are you able to build a small sample project that throws the exception? I have some ideas around a fix but need it to break first. If you are experiencing acceptable performance using one-per-op then let me know too and I can close this.

**Comment by ajcvickers** [comment] 2022-09-07 11:14
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:40 UTC
Labels: closed-could-not-reproduce, customer-reported
