### ISSUE TITLE
[EF7] Migration files not being generated properly

### ISSUE THREAD

**Issue by vishalkdotcom** [dotnet/efcore#4510] opened 2016-02-06 17:42 UTC
After hitting `dnx ef migrations add initial` I am getting below three migration files:
1. 20160206164941_initial.cs
2. 20160206164941_initial.Designer.cs
3. PhotoGalleryContextModelSnapshot.cs

Except first file, other two have some issues. 
- An empty using statement is being generated.
- BuildTargetModel is throwing compiler error
  ![image](https://cloud.githubusercontent.com/assets/342746/12868031/7af66ccc-cd23-11e5-9b89-c1fab20e1d90.png)
- Duplicate 'DbContext' attribute
  ![image](https://cloud.githubusercontent.com/assets/342746/12868044/e5cb8442-cd23-11e5-8157-eb80a89e511b.png)
- Duplicate 'Migration' attribute

**20160206164941_initial.Designer.cs**

```
using System;
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Infrastructure;
using Microsoft.Data.Entity.Metadata;
using Microsoft.Data.Entity.Migrations;
using ;

namespace photogallery.Migrations
{
    [DbContext(typeof(PhotoGalleryContext))]
    [Migration("20160206164941_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc1-16348")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                }
        }
     }
}
```

**PhotoGalleryContextModelSnapshot.cs**

```
using System;
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Infrastructure;
using Microsoft.Data.Entity.Metadata;
using Microsoft.Data.Entity.Migrations;
using ;

namespace photogallery.Migrations
{
    [DbContext(typeof(PhotoGalleryContext))]
    partial class PhotoGalleryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc1-16348")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Description")
                        .HasAnnotation("MaxLength", 500);

                    b.Property<string>("Title")
                        .HasAnnotation("MaxLength", 100);

                    b.HasKey("Id");
                });

        }
    }
}

```

**project.json**

```
{
    "webroot": "wwwroot",
    "userSecretsId": "PhotoGallery",
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },
    "tooling": {
        "defaultNamespace": "photo_gallery"
    },
    "dependencies": {
        "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
        "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
        "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
        "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
        "Microsoft.Framework.DependencyInjection": "1.0.0-beta8",
        "EntityFramework.Commands": "7.0.0-rc1-final",
        "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
        "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
        "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
        "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
        "AutoMapper.Data": "1.0.0-beta1",
        "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final"
    },
    "commands": {
        "web": "Microsoft.AspNet.Server.Kestrel",
        "ef": "EntityFramework.Commands"
    },
    "frameworks": {
        "dnx451": {},
        "dnxcore50": {
            "dependencies": {
                "System.Security.Cryptography.Algorithms": "4.0.0-beta-23516"
            }
        }
    },
    "exclude": [
        "wwwroot",
        "node_modules"
    ],
    "publishExclude": [
        "**.user",
        "**.vspscc"
    ]
}
```

Could anyone please suggest on this.

**Comment by bricelam** [comment] 2016-02-08 18:24
The empty using statement could be a dupe of #2467

**Comment by rowanmiller** [comment] 2016-02-09 00:11
@vshal526 can you confirm if your context is in a namespace?

**Comment by vshal526** [comment] 2016-02-09 08:52
@rowanmiller No, I haven't wrapped the context inside a namespace. Although, I have already provided the default namespace in the project.json.

```
...
"tooling": {
        "defaultNamespace": "photo_gallery"
    },
...
```

**Comment by bricelam** [comment] 2016-02-09 18:25
Whoa! We support specifying the default namespace in project.json? This is the first I've seen that.

**Comment by rowanmiller** [comment] 2016-02-09 19:52
I think we now have this covered by https://github.com/aspnet/EntityFramework/issues/2467 and #4524.

**Closed** 2022-10-16 09:28 UTC
