### ISSUE TITLE
Make it Possible for Migration Tool to Create Columns in Respectfull Order

### ISSUE THREAD

**Issue by HEBOS** [dotnet/efcore#11717] opened 2018-04-18 06:19 UTC
Migration tool does not create columns in respectful order.

### Steps to reproduce
Can you please define an attribute for the entity, that would help migration tool to create columns in respectful order.
Currently, if we have derived classes it puts primary key column first, then foreign key columns, and finally all other in alphabetical order, which looks really messy.

Suppose we have a class

[NotMapped]
public class BaseClass
{
   public int Id {get; set;}
   public string Afield {get; set;}
   public string Cfield {get; set;}
   public string Xfield {get; set;}
}

public class InheritedClass : BaseClass
{
   public string Bfield {get; set;}
}

I would expect that I would get in database BaseClass columns first and after that inherited class.
But this is done in alphabetical order (besides primary and foreign keys).

I suggest you add an attribute, so the developer could decide which approach to take.

[OrderEntity(OrderEntityType, KeysFirst)]

KeysFirst is a boolean.

OrderEntityPriority is an enum.

public enum OrderEntityPriority
{
  Keys,
  BaseClass,
  InheritedClass,
  Alphabetical
}

With that given, I would use my classes as follows:

[NotMapped]
public class BaseClass
{
   public int Id {get; set;}
   public string Afield {get; set;}
   public string Cfield {get; set;}
   public string Xfield {get; set;}
}

[OrderEntity(OrderEntityPriority.BaseClass, true)]
public class InheritedClass : BaseClass
{
   public string Bfield {get; set;}
}

### Further technical details
EF Core version: 2.0.2
Database Provider: Microsoft SQL
Operating system:  Windows 10
IDE: (e.g. Visual Studio 2017 15.4) 2017.15.4

**Comment by ajcvickers** [comment] 2018-04-18 15:26
Duplicate of #2272

**Closed** 2022-10-16 12:19 UTC
Labels: closed-duplicate
