### ISSUE TITLE
HasQueryFilter In memory only

### ISSUE THREAD

**Issue by badre429** [dotnet/efcore#14432] opened 2019-01-15 21:01 UTC
In memory HasQueryFilter where the filter is based on dependency injection 
modelBuilder.Entity<Project>().HasQueryFilter(p.Id => EmployeeService.IsInProject(p.Id));

**Comment by ajcvickers** [comment] 2019-01-16 21:00
@badre429 Can you please provide more details. (Otherwise we're speculating as to what you mean...)

**Comment by ajcvickers** [comment] 2019-01-23 17:59
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:47 UTC
Labels: closed-could-not-reproduce, customer-reported
