### ISSUE TITLE
OwnsMany generates multiple delete statements instead of a single SQL statement (EF Core 7.0.4)

### ISSUE THREAD

**Issue by HamidEbr** [dotnet/efcore#30590] opened 2023-03-28 12:37 UTC
I have a **WatchCategoryEntity** class that has a collection of **WatchCategorySymbolEntity** child entities defined using **OwnsMany** in my EF Core 5 configuration:

```
public class WatchCategoryEntity : BaseShardEntity, IAggregateRoot
{
    // ...

    private readonly List<WatchCategorySymbolEntity> _watchCategorySymbols = new();
    public IReadOnlyList<WatchCategorySymbolEntity> WatchCategorySymbols => _watchCategorySymbols;

    public void DeleteSymbolRange(IEnumerable<string> symbolIsins)
    {
        _watchCategorySymbols.RemoveAll(s => symbolIsins.Contains(s.SymbolIsin));
    }

    // ...
}

public class WatchCategorySymbolEntity
{
    public string SymbolIsin { get; init; }
}

internal sealed class WatchCategoryConfig : IEntityTypeConfiguration<WatchCategoryEntity>
{
    public void Configure(EntityTypeBuilder<WatchCategoryEntity> builder)
    {
        builder.Property(p => p.Id).HasColumnType("char(32)");
        builder.Property(p => p.Name).HasColumnType("nvarchar").IsUnicode().HasMaxLength(200).IsRequired();
        builder.Property(p => p.Order).IsRequired(false);
        builder.Property(p => p.IsDefault).IsRequired();
        builder.OwnsMany(p => p.WatchCategorySymbols,
            b =>
            {
                b.WithOwner().HasForeignKey("WatchCategoryId");
                b.ToTable("WatchCategorySymbols");
                b.Property("Id").HasColumnType("bigint");
                b.Property(i => i.SymbolIsin).HasMaxLength(12);
            });

        var navigation = builder.Metadata.FindNavigation(nameof(WatchCategoryEntity.WatchCategorySymbols));
        navigation.SetPropertyAccessMode(PropertyAccessMode.Field);
    }
}
```

When I call **DeleteSymbolRange** on a **WatchCategoryEntity** instance and then call **SaveChangesAsync()** on my DbContext, EF Core generates multiple delete statements instead of a single SQL statement. I expect EF Core to generate a single SQL statement with a **DELETE...IN** clause for better performance.

Is there any way to configure EF Core to generate a single delete statement instead of multiple delete statements when deleting child entities with OwnsMany? Or is there any workaround that can achieve the same result?

**Comment by roji** [comment] 2023-03-28 13:39
Duplicate of #27550

**Closed** 2023-03-29 19:46 UTC
Labels: closed-duplicate, customer-reported
