### ISSUE TITLE
Problem with System.Int16 (short) parameter

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#15490] opened 2019-04-24 19:48 UTC
Hello,

Can anybody research/test the following example:

**Test table contains single row (ID=1)**
``` c#
  [Table("DUAL")]
  public sealed class DUAL
  {
   [Key]
   [Column("ID")]
   public Int32 ID { get; set; }
  };//class DUAL
```

**Test code**
``` c#
 private static Int64 FFF(Int64 v)
 {
  return v;
 }//FFF

 //-----------------------------------------------------------------------
 [Test]
 public static void Test___00___ByEF()
 {
  using(var cn=Helper__CreateCn())
  {
   cn.Open();

   using(var tr=cn.BeginTransaction())
   {
    //insert new record in external transaction
    using(var db=new MyContext(tr))
    {
     short vv2=0; // <---- problem with short. with int - all is ok.

     var recs=db.dualTable.Where(r => FFF(r.ID+vv2)==1);

     int nRecs=0;

     foreach(var r in recs)
     {
      ++nRecs;
     }//foreach r

     Assert.AreEqual
      (1,
       nRecs);
    }//using db

    tr.Rollback();
   }//using tr
  }//using cn
 }//Test___00___ByEF
```

I have get the error **"Message: System.InvalidCastException : Unable to cast object of type 'System.Int16' to type 'System.Int32'."**

When I change "short vv2=0;" to "int vv2=0;", all works without problems.

**Error stack**
> Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.DefaultQueryExpressionVisitor.GetParameterValue[T](QueryContext queryContext, String parameterName) in D:\Users\Dima\GitHUB2\aspnet\EntityFrameworkCore\work\src\EFCore\Query\ExpressionVisitors\Internal\DefaultQueryExpressionVisitor.cs:line 123
>    at lambda_method(Closure , DUAL )
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
>    at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext() in D:\Users\Dima\GitHUB2\aspnet\EntityFrameworkCore\work\src\EFCore\Query\Internal\LinqOperatorProvider.cs:line 194
>    at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext() in D:\Users\Dima\GitHUB2\aspnet\EntityFrameworkCore\work\src\EFCore\Query\Internal\LinqOperatorProvider.cs:line 156
>    at ef_core__lcpi_oledb__ntests.Work.DBMS.Firebird.V03_0_0.Query.Translators.Math.Abs.Short.Work_Translators__Math_Abs_Short___Expr.Test___00___ByEF() in D:\Users\Dima\Work2\TestCode\users\Dima\TestCode\EFCore_LcpiOleDb_v1\ntest\Source\Work\DBMS\Firebird\V03_0_0\Query\Translators\Math\Abs\Short\Work_Translators__Math_Abs_Short___Expr.cs:line 90
> 

**Location of problem code**
https://github.com/aspnet/EntityFrameworkCore/blob/da97584154e6337fdba1e348098b1a951967ea1d/src/EFCore/Query/ExpressionVisitors/Internal/DefaultQueryExpressionVisitor.cs#L121-L123

Here T==typeof(System.Int32) and parameter ("__vv2_0") has short value (0)

![image](https://user-images.githubusercontent.com/4594554/56688527-a5fce580-66e1-11e9-9a2c-8b6046613593.png)

![image](https://user-images.githubusercontent.com/4594554/56688678-faa06080-66e1-11e9-89c7-945ad4e78628.png)

**Question**
It is problem within EFCore or result of my modifications / incorrect code?

**Comment by dmitry-lipetsk** [comment] 2019-04-24 20:07
My temporary solution:

**Old code**
https://github.com/aspnet/EntityFrameworkCore/blob/da97584154e6337fdba1e348098b1a951967ea1d/src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs#L284-L289

**New code**
``` c#
            //var parameter = Expression.Parameter(expression.Type, parameterName);

            Expression parameter;

            if(Object.ReferenceEquals(parameterValue,null))
            {
               parameter=Expression.Parameter(expression.Type, parameterName);
            }
            else
            {
               parameter=Expression.Parameter(parameterValue.GetType(), parameterName);

               if(!expression.Type.Equals(parameterValue.GetType()))
               {
                    parameter=Expression.Convert(parameter,expression.Type);
               }
            }

            _evaluatedValues.Add(expression, parameter);

            return parameter;
        }

```

**Comment by smitpatel** [comment] 2019-04-24 20:24
Duplicate of #15330

**Closed** 2022-10-16 14:18 UTC
Labels: customer-reported
