### ISSUE TITLE
Set provisioned throughput for cosmos db using EFcore

### ISSUE THREAD

**Issue by pavitrag123** [dotnet/efcore#19074] opened 2019-11-26 09:40 UTC
Is there a way to set provisioned throughput at cosmos database level while using efcore like below. 

using Microsoft.Azure.Documents.Client

![image](https://user-images.githubusercontent.com/19691194/69617262-f5333c00-105d-11ea-9d0f-24e0ef8664ce.png)

**Comment by AndriySvyryd** [comment] 2019-11-27 00:41
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/17301

**Closed** 2022-10-16 14:58 UTC
Labels: customer-reported
