### ISSUE TITLE
Blazor Server project (preview9) fails with Cosmos DB for Identity

### ISSUE THREAD

**Issue by simonziegler** [dotnet/efcore#17829] opened 2019-09-13 10:22 UTC
# Issue description
I am trying to use Cosmos DB as my database for identity in a preview9 Blazor Server app. This crashes when I attempt to register an account, showing the screen below. I have put an example of this on GitHub for reference, with minimal change to the out-of-the-box Blazor Server template app. To recreate, download the project, use the Azure Cosmos DB Emulator and update the connection parameters accordingly in the call to services.AddDbContext in Startup.cs (code snippet below).

# Code Repository
https://github.com/simonziegler/BlazorCosmosIdentityTest01

# Code snippet

```
            // =============================================================================
            // Updated to target local Cosmos DB rathern than local SQL Server
            // Note: you will need to change the Key "C2y..." for your Cosmos connection
            // =============================================================================
            //services.AddDbContext<ApplicationDbContext>(options =>
            //    options.UseSqlServer(
            //        Configuration.GetConnectionString("DefaultConnection")));
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseCosmos(
                    "https://localhost:8081",
                    "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
                    "BlazorIdentity"));
            // =============================================================================
            // End of changes
            // =============================================================================
```

# Screen grab immediately after attempting to register a new user
![image](https://user-images.githubusercontent.com/11708435/64855895-c25dd800-d618-11e9-9a7f-27ef3fd67c28.png)

**Comment by smitpatel** [comment] 2019-09-13 16:20
Duplicate of #17435

**Closed** 2022-10-16 14:42 UTC
Labels: customer-reported
