### ISSUE TITLE
How to insert item without track by EFCore

### ISSUE THREAD

**Issue by Flithor** [dotnet/efcore#30901] opened 2023-05-16 09:27 UTC
I'm testing on insert 100M item on 30+field table, and one of field has auto-generate value in database.
I found that EFCore always query the auto-generate field value of the item just inserted after each insert due to the existence of the database generated value, which caused insert unusually inefficient.

**Comment by ajcvickers** [comment] 2023-05-16 09:32
Duplicate of #29897

**Comment by Flithor** [comment] 2023-05-16 09:35
@ajcvickers Is there any way to stop EFCore to query the database generated values after each insert?

**Comment by ajcvickers** [comment] 2023-05-16 09:36
Not currently.

**Closed** 2023-05-16 11:37 UTC
Labels: customer-reported

**Comment by roji** [comment] 2023-05-16 12:32
@Flithor I'm generally not aware of a case where the fetching of the database-generated ID on its own significantly slows down insertion - is this something you've actually verified in benchmarking? If so, can you please share that?
