### ISSUE TITLE
AsNoTracking() with Microsoft.EntityFrameworkCore.InMemory does not work

### ISSUE THREAD

**Issue by t-ashraf** [dotnet/efcore#14676] opened 2019-02-12 11:03 UTC
The unit test below **fails**. The status returned is Unhealthy.

Source Code:
```c#
var lastMigration = await _efContext.FlywaySchemaHistory
.AsNoTracking()
.OrderByDescending(p => p.InstalledOn)
.FirstOrDefaultAsync(x => x.Success && !string.IsNullOrEmpty(x.Version), cancellationToken);

if (lastMigration != null)
{
  var description = $"Last migration: {lastMigration.Version}";
  return HealthCheckResult.Healthy(description);
}
else
{
  const string description = "Flyway migration query failed";                    
  return HealthCheckResult.Unhealthy(description);
}
```
Unit Test Source Code:
```c#
[Test]
        public async Task OneVersionedSuccessfulMigration_Status_Healthy()
        {
            // Arrange
            const HealthStatus expectedStatus = HealthStatus.Healthy;
            const string version = "1.0.0";
            const bool success = true;
            var target = new FlywayMigrationHealthCheck(EFContext);
            var context = new HealthCheckContext();
            var firstMigration = new FlywaySchemaHistory
            {
                InstalledOn = DateTime.UtcNow,
                InstalledRank = 1,
                Script = "",
                Success = success,
                Version = version
            };
            EFContext.Add(firstMigration);
            await EFContext.SaveChangesAsync();

            // Act
            var result = await target.CheckHealthAsync(context);

            // Assert
            result.Should().NotBeNull();
            result.Status.Should().Be(expectedStatus);
        }
```

- If I call the product source code using the HealthCheck API, it works **correctly** (using Npgsql.EntityFrameworkCore.PostgreSQL).
- If I **remove** `.AsNoTracking()` from the product source code, the unit test **passes**. 
- I have tried to move the `.AsNoTracking()` to after the OrderBy to no avail.

Setup:
EntityFrameworkCore - 2.2.1
NUnit - 3.11.0
Database Provider - Microsoft.EntityFrameworkCore.InMemory (for unit testing purposes only)

**Comment by ajcvickers** [comment] 2019-02-19 20:49
@t-ashraf I have not been able to reproduce this issue--see my code below. Can you post a small, runnable project/solution or complete code listing (like below) that reproduces the behavior you are seeing.

```C#
public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseInMemoryDatabase("Edward Heath");
    }

    public DbSet<FlywaySchemaHistory> FlywaySchemaHistory { get; set; }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            var firstMigration = new FlywaySchemaHistory
            {
                InstalledOn = DateTime.UtcNow,
                InstalledRank = 1,
                Script = "",
                Success = true,
                Version = "1"
            };
            context.Add(firstMigration);
            await context.SaveChangesAsync();

            Console.WriteLine(await CheckHealthAsync(context));
        }
    }

    public static async Task<bool> CheckHealthAsync(BloggingContext context)
    {
        var lastMigration = await context.FlywaySchemaHistory
            .AsNoTracking()
            .OrderByDescending(p => p.InstalledOn)
            .FirstOrDefaultAsync(x => x.Success && !string.IsNullOrEmpty(x.Version));

        return lastMigration != null;
    }
}

public class FlywaySchemaHistory
{
    public int Id { get; set; }
    public DateTime InstalledOn { get; set; }
    public int InstalledRank { get; set; }
    public string Script { get; set; }
    public bool Success { get; set; }
    public string Version { get; set; }
}
```

**Comment by ajcvickers** [comment] 2019-03-01 17:18
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:51 UTC
Labels: closed-could-not-reproduce, customer-reported
