### ISSUE TITLE
Invalid cast when using ternary operator with SQL Backend

### ISSUE THREAD

**Issue by joshbartley** [dotnet/efcore#11681] opened 2018-04-15 17:36 UTC
I have a EF query that pulls back a nullable TimeSpan since the datatype in SQL is "time". I did a quick conversion and received an exception casting a Decimal to a Nullable Int64/long, even though there is no Decimal present in the code I am writing since TotalSeconds is a double. I pulled everything out of my main app and started a new dotnet core console app using 2.0 and EF Core 2.0.2, details are below.

To trigger the exception, it seems any hard coded value will cause the values to go to SQL Server and come back as a decimal(maybe?) and then can't be casted down.
```c#
x.PhoneDuration.HasValue ? 4294967296L : 4294967296L
```
EF Core produces the following SQL for this function
```sql
SELECT CASE
    WHEN [x].[PhoneDuration] IS NOT NULL
    THEN 4294967296 ELSE 4294967296
END AS [Duration] FROM [Call] AS [x]
```
I then pulled it out into a separate static function, and no exceptions were produced. Both methods produce the same sql, while the static function is the only way that works.

```
Exception message:
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.Decimal' to type 'System.Nullable`1[System.Int64]'.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConsoleApp1.Program.Main(String[] args) in c:\users\user\documents\visual studio 2017\Projects\ConsoleApp1\ConsoleApp1\Program.cs:line 33
```

### Steps to reproduce
```c#
        static void Main(string[] args)
        { //new console app since I wanted to test it 
            var _context = new EFContext();

            calls = _context.Call.Where(x => x.PersonId == 1).Select(x => new Calls()
            {
                Duration = ConvertTimespan(x.PhoneDuration) //works
            }).ToList();

            calls = _context.PersonContacted.Where(x => x.PersonId == 1).Select(x => new Calls()
            {
                Duration = x.Call.HasValue ? 4294967296L : 4294967296L //fails
            }).ToList();
        }
        static long? ConvertTimespan(TimeSpan? value)
        {
            return value.HasValue ? (long)value.Value.TotalSeconds : new long?();
        }
```

```c#
    public class Call
    {
        [Key]
        public long PersonContactId { get; set; }
        public long PersonId { get; set; }
        public TimeSpan? PhoneDuration { get; set; } 
    }
```
```sql
CREATE TABLE [dbo].[Call](
	[PersonContactId] [bigint] IDENTITY(1,1) NOT NULL,
	[PersonId] [bigint] NOT NULL,
	[PhoneDuration] [time](2) NULL
)
```
Query sent by EF
```sql
SELECT CASE
    WHEN [x].[PhoneDuration] IS NOT NULL
    THEN 4294967296 ELSE 4294967296
END AS [Duration]
FROM [PersonContacted] AS [x]
WHERE [x].[PersonId] = 1
```

### Further technical details
EF Core version: netcoreapp2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.6.6
Microsoft.EntityFrameworkCore 2.0.2
Microsoft.EntityFrameworkCore.SqlServer 2.0.2

**Comment by smitpatel** [comment] 2018-04-15 17:42
Duplicate of #9070 

Fixed in 2.1.0-preview2

**Closed** 2022-10-16 12:18 UTC
