### ISSUE TITLE
Disable Pluarlizer when using dotnet-ef dbcontext Scaffold

### ISSUE THREAD

**Issue by ganySA** [dotnet/efcore#16395] opened 2019-07-02 12:54 UTC
.net core 3.0

When i try scaffold from my database it now groans about not having Bricelam.EntityFrameworkCore.Pluralizer. But i do not want to pluralize any of the entities so i can maintain backward compatibility to other libraries.

How can i disable the pluralizer? The behaviour in .net 2.2 was more expected, that only if the library was added would it pluralize.

**Comment by bricelam** [comment] 2019-07-05 17:00
It has to be installed somewhere if it's finding `[assembly: DesignTimeServicesReference("...Bricelam.EntityFrameworkCore.Pluralizer")]`.

In 3.0, I believe we updated it to look inside the target project in addition to the startup project. Could you share your csproj files?

**Comment by ganySA** [comment] 2019-07-06 03:31
The project is quite complex i have about 4 sub projects in the solution.
I removed the pluralizer from the .core execution project and from my data project not from the others. What seems to happen is that it picks up there is a pluralizer somewhere but when it gets to execute it cant find it. I think most likely i need to remove it from all the sub projects.

**Comment by ajcvickers** [comment] 2019-07-08 17:42
@ganySA It shouldn't be possible to get in a state where the package is picked up, but then the DLL is not found. Could you post a small project/solution that has this behavior?

**Comment by ajcvickers** [comment] 2019-07-15 15:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:28 UTC
Labels: closed-could-not-reproduce, customer-reported
