### ISSUE TITLE
Naming a migration "DateTimeOffset" doesn't work

### ISSUE THREAD

**Issue by mgutekunst** [dotnet/efcore#25072] opened 2021-06-10 08:31 UTC
Hi, 

we added a migration that alters a property type from `DateTime` to `DateTimeOffset`. The Migration itself looks as follows:
```C#
    public partial class DateTimeOffset : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<DateTimeOffset>(
                name: "LastModified",
                schema: "dbo",
                table: "Test",
                type: "datetimeoffset",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "datetime2");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<DateTime>(
                name: "LastModified",
                schema: "dbo",
                table: "Test",
                type: "datetime2",
                nullable: false,
                oldClrType: typeof(DateTimeOffset),
                oldType: "datetimeoffset");
        }
    }

```

Unfortunately, after this migration is created, calls to `dotnet ef migrations add` fail with the following exception:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Initialize(ColumnOperation columnOperation, IColumn column, RelationalTypeMapping typeMapping, Boolean isNullable, IEnumerable`1 migrationsAnnotations, Boolean inline)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(IColumn source, IColumn target, DiffContext diffContext)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(ITable source, ITable target, DiffContext diffContext)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```
We were also able to reproduce that issue in a sample project that only contains an inital migration that creates the table and adds a column for a property of type `DateTime` and the migration shown above, 

We used ef version 5.0.7 to create the migrations
```

                     _/\__
               ---==/    \\
         ___  ___   |.    \|\
        | __|| __|  |  )   \\\
        | _| | _|   \_/ |  //|\\
        |___||_|       /   \\\/\\

Entity Framework Core .NET Command-line Tools 5.0.7
```

Could you help us solve our issue? Is something wrong with our migration?

Kind regards, 
Manuel Gutekunst

**Comment by roji** [comment] 2021-06-10 09:23
This did not repro for me using 5.0.7 with the following steps:

* Create a blank project with an entity that has a DateTime property
* Add an initial migration
* Change the property's type from DateTime to DateTimeOffset
* Add a 2nd migration
* Add a new string property
* Add a 3rd migration

My 2nd migration looks very similar to the code you posted above, but I have no problem either creating the 3rd migration or updating the database with these 3 migrations.

Can you please provide precise steps to reproduce this, and/or provide the sample project you've put together?

**Comment by roji** [comment] 2021-06-10 11:25
@mgutekunst the issue here is that you migration's name is `DateTimeOffset`. This means that the migration *type* is DateTimeOffset, and so when the migration code within contains e.g. `AlterColumn<DateTimeOffset>`, that refers to your own migration type and not to System.DateTimeOffset. If you rename your

@bricelam are we aware/tracking this issue? Adding something to the scaffolded type name should help (maybe the timestamp??).

**Comment by mgutekunst** [comment] 2021-06-11 04:53
oh...

thanks for claryfying @roji . Renaming the Migrations class solved our issue.

**Comment by roji** [comment] 2021-06-11 18:10
Triage discussion - if we see other people hitting this, we may add something to the type name for the migration (e.g. the timestamp, like we already do in the file name).

**Comment by bricelam** [comment] 2022-10-19 22:22
Duplicate of #26954

**Closed by bricelam** 2022-10-19 22:22 UTC
Labels: customer-reported

**Comment by jfshark** [comment] 2024-02-07 15:56
Ran into this issue. Spent 2 hours, trying to understand, what is going on
