### ISSUE TITLE
Group By misbehaves with specific class while working with anonymous

### ISSUE THREAD

**Issue by vpikalev** [dotnet/efcore#11345] opened 2018-03-20 15:13 UTC
For some reason group by evaluates in memory when selecting AgentsFilterOptions.OfficeItem items, but translated to group by sql clause when selecting anonymous class items of pretty much the same stucture.

### Steps to reproduce
This code snippet produces the following sql
```c#
public class AgentsFilterOptions
{
        public class OfficeItem
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }
}

//build expression by means of LinqKit

var temp = _context.Set<Agent>().Where(expression.Expand())
.GroupBy(x => new { x.OfficeId, x.Office.Name })
.Select(x => new AgentsFilterOptions.OfficeItem { Id = x.Key.OfficeId, Name = x.Key.Name }).ToList();
var temp2 = _context.Set<Agent>().Where(expression.Expand())
.GroupBy(x => new { x.OfficeId, x.Office.Name })
.Select(x => new { Id = x.Key.OfficeId, Name = x.Key.Name }).ToList();
```

```SQL
exec sp_executesql N'SELECT [f].[Id], [f].[AgentUrl], [f].[Alias], [f.Office].[Name]
FROM [Agent] AS [f]
INNER JOIN [Office] AS [f.Office] ON [f].[OfficeId] = [f.Office].[Id]
WHERE (([f.Office].[CompanyId] = @__companyId_0) AND ([f].[Deleted] = 0)) AND ([f].[HideOnCompanyWebsite] = 0)
ORDER BY [f].[OfficeId], [f.Office].[Name]',N'@__companyId_0 int',@__companyId_0=1862

exec sp_executesql N'SELECT [f].[OfficeId], [f.Office].[Name]
FROM [Agent] AS [f]
INNER JOIN [Office] AS [f.Office] ON [f].[OfficeId] = [f.Office].[Id]
WHERE (([f.Office].[CompanyId] = @__companyId_0) AND ([f].[Deleted] = 0)) AND ([f].[HideOnCompanyWebsite] = 0)
GROUP BY [f].[OfficeId], [f.Office].[Name]',N'@__companyId_0 int',@__companyId_0=1862
```

### Further technical details
EF Core version:  2.1.0-preview1-final
3d party dependencies: LinqKit.Microsoft.EntityFrameworkCore Version="1.1.15"
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 64bit
IDE: (Visual Studio 2017 15.6

**Comment by smitpatel** [comment] 2018-03-21 01:05
Duplicate of #11176 
Fixed in nightly builds.

**Closed** 2022-10-16 12:15 UTC
Labels: closed-duplicate
