### ISSUE TITLE
Type inference not correct for ToDictionaryAsync

### ISSUE THREAD

**Issue by cceuroform** [dotnet/efcore#19540] opened 2020-01-09 11:02 UTC
The type inference for ToDictionaryAsync and ToDictionary are not the same.

### Steps to reproduce

```C#
class OptionalData
{
}

OptionalData? CreateOptional(Data data)
{
	return null;
}
var test1 = await ctx.Data.ToDictionaryAsync(p=>p.Key, p=>CreateOptional(p))
var test2 = ctx.Data.ToDictionary(p=>p.Key, p=>CreateOptional(p))

type of test1 is Dictionary<Key,OptionalData>
type of test2 is Dictionary<Key,OptionalData?>
```

### Further technical details

EF Core version: Microsoft.EntityFrameworkCore, Version=3.0.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: Net Standard 2.1
Operating system: WIN 10
IDE: VS Version 16.5.0 Preview 1.0

**Comment by ajcvickers** [comment] 2020-01-09 16:41
Duplicate of #19443

**Closed** 2022-10-16 18:04 UTC
Labels: customer-reported
