### ISSUE TITLE
Data type Decimal(n,0) causes an exception in SQL server by create and update

### ISSUE THREAD

**Issue by GuyDavidBanks** [dotnet/efcore#33139] opened 2024-02-22 11:17 UTC
I reverse engineered (scaffold) a legacy database system that contains some decimal data types with 0 precision e.g. decimal(3,0), etc.
They have the correct data types in the Model and can be read using the context.  The issue comes when I try to write values, the generated SQL always adds a decimal point followed by 0 to and SQL server throws and exception as the precision is 0 and it does not allow for this, even though no data is corrupted or lost.

I am using DotNet Entity Framework 8.0 and the legacy database has compatibility mode 100, not ideal, but it is a legacy system and we cannot break the existing software.  If I change the data types to integer etc. the issue goes away, but breaks some of the older software.  I do not set the context to use comparability mode 100, I simply write my LINQ queries to allow for the compatibility issues.

I am not sure if the issue is DotNet or the SQL server, but either the decimal place should not be sent or the SQL Sever should allow for a ,0 and no data is lost.

I know this wouldn't be an issue had the better data types been used in the first place, but the issue is that the legacy system has code that can;t be updated as the ADO was embedded in an old silver-light application.

This is really easy to reproduce and seeing as my original fix was to change the data types to int etc.  I no longer see the error, but in integration testing it breaks the legacy software.

If you need me too I can reproduce the issues and send to the stack traces, but I think the issue is clear without needing to do so.

**Comment by ajcvickers** [comment] 2024-02-22 11:24
Note for team triage: looks like a dupe of https://github.com/dotnet/SqlClient/issues/1214

**Closed** 2024-02-28 13:33 UTC
Labels: closed-external, customer-reported
