### ISSUE TITLE
Primitive Collections with ValueConverters

### ISSUE THREAD

**Issue by Jejuni** [dotnet/efcore#34063] opened 2024-06-22 14:30 UTC
Is using primitive collections in conjunction with a Value Converter a supported scenario?

For instance, simplified code:

```cs
public class MySmartEnum
{
    public static readonly MySmartEnum First = new() { Name = "First", Value = 1 };
    public static readonly MySmartEnum Second = new() { Name = "Second", Value = 2 };
    public required int Value { get; init; }
    public required string Name { get; init; }
}

public class MySmartEnumValueConverter() : 
   ValueConverter<MySmartEnum, int>(v => v.Value, v => v == 1 ? MySmartEnum.First : MySmartEnum.Second);

public class User
{
    public required List<MySmartEnum> SmartEnums { get; init; }
}

internal class MyContext : DbContext
{
    public DbSet<User> Users => Set<User>();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(
            @"Server=localhost,5433;Initial Catalog=test;User Id=sa;Password=xxx;TrustServerCertificate=true");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(b =>
        {
            b.PrimitiveCollection(x => x.SmartEnums);
        });
    }

    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        configurationBuilder.Properties(typeof(MySmartEnum)).HaveConversion<MySmartEnumValueConverter>();
    }
}
```

This, however, does not work an fails with the exception:

`System.InvalidOperationException: 'The 'List<MySmartEnum>' property 'User.SmartEnums' could not be mapped because the database provider does not support this type. Consider converting the property value to a type supported by the database using a value converter. See https://aka.ms/efcore-docs-value-converters for more information. Alternately, exclude the property from the model using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.'
`

The exception points towards value converter, but I've already got one.

**Comment by cincuranet** [comment] 2024-06-25 08:50
Duplicate of #31616. Make sure to vote (👍) for #31616.

**Closed** 2024-06-25 08:51 UTC
Labels: customer-reported, area-primitive-collections

**Comment by ajcvickers** [comment] 2024-06-26 09:13
I think this is more a duplicate of #33688 and by extension #31413.
