### ISSUE TITLE
EntityFramework 7 support in Class library targeting dotnet5.4

### ISSUE THREAD

**Issue by stevejgordon** [dotnet/efcore#3888] opened 2015-11-25 09:35 UTC
I recently created a new Class Library Package where I planned to move my Data Access code away from my MVC web site project. I had this working against the dnx46 and dnxcore50 frameworks in project.json. Note that I had to set those frameworks up as the default for a new Class Library Package is net451 and dotnet5.4

I have since read some guidance that suggests the preferred new naming to use on the frameworks should be net46 and dotnet5.4 so I changed them back. I now get errors stating

The dependancy EntityFramework.Commands 7.0.0-rc1-final in project xxxx does not support framework .NETPlatform,Version=v5.4

Is this correct and if so should I be safe to continue using dnxcore50 and dnx46 which appear to work?

**Comment by rowanmiller** [comment] 2015-12-01 19:35
Dupe of https://github.com/aspnet/EntityFramework/issues/3879

**Closed** 2022-10-16 09:17 UTC
