### ISSUE TITLE
Support casting db types

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#3942] opened 2015-12-02 00:12 UTC
Casting db types not supported first-class. This can only be accomplished with `FromSql`.

`sys.index_columns.key_ordinal` is `BIT` which maps to `byte`.
`ColumnModel.PrimaryKeyOrdinal` is `int`. Materializing throws an `InvalidCastException`.

Workaround:
- .FromSql() with `CAST (ic.key_ordinal AS INT)`

Could overlap with a solution for #3932

**Comment by rowanmiller** [comment] 2015-12-08 20:37
**Triage:** This scenario is a dupe of https://github.com/aspnet/EntityFramework/issues/242. That feature would probably support this by reading it back as `BIT` but then allowing you to map it to an `int` property (rather than doing the conversion inline in the query).

**Closed** 2022-10-16 09:18 UTC
