### ISSUE TITLE
Altering a nullable column to be not nullable with a default value fails during migration

### ISSUE THREAD

**Issue by ChristopherHaws** [dotnet/efcore#26807] opened 2021-11-23 20:17 UTC
The following migration results in the following SQL migration script which fails. The `ADD DEFAULT` query should run before the `ALTER COLUMN` script.

```C#
migrationBuilder.AlterColumn<string>(
    name: "Column",
    schema: "Schema",
    table: "Table",
    type: "nvarchar(max)",
    nullable: false,
    defaultValueSql: "'[]'",
    oldClrType: typeof(string),
    oldType: "nvarchar(max)",
    oldNullable: true);
```

```sql
ALTER TABLE [Schema].[Table] ALTER COLUMN [Column] nvarchar(max) NOT NULL;
ALTER TABLE [Schema].[Table] ADD DEFAULT ('[]') FOR [Column];
```

### SQL Exception
```
Cannot insert the value NULL into column 'Column', table 'db.Schema.Table'; column does not allow nulls. UPDATE fails. 
```

### Include provider and version information

EF Core version: 6.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6
Operating system: Windows 11
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment] 2021-11-25 09:26
Duplicate of #21765? /cc @bricelam

**Comment by HerrNiklasRaab** [comment] 2021-11-28 14:23
Same here, but in my case, the column I want to make non-nullable has no null values, but it still fails to migrate. Which seems different then this issue, what is described here: https://github.com/dotnet/efcore/issues/21765#issuecomment-663275383

**Comment by roji** [comment] 2021-11-30 16:05
> The ADD DEFAULT query should run before the ALTER COLUMN script.

The ordering actually doesn't matter - if add the default before making the column non-nullable, you still get the error (see https://github.com/npgsql/npgsql/issues/4186#issuecomment-982512914). And yeah, seems like this is a dup of #21765.

**Closed** 2022-10-16 20:15 UTC
Labels: closed-duplicate, customer-reported
