### ISSUE TITLE
migrate database when dbcontext is in different assembly

### ISSUE THREAD

**Issue by alesdvorakcz** [dotnet/efcore#14463] opened 2019-01-18 22:58 UTC
Hello,
I have DbContext, all entities and migrations in separate project (.net standard class library) but I want to run 'dotnet ef database update' from asp.net core app. Project has reference and in my Startup class I register dbContext to DI container in standard way:

```c#
services.AddDbContext<AppDbContext>(options =>
  options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"))
);
```
I found [this article in documentation](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#using-the-tools) so I think this scenario should be possible. The idea is to migrate database referenced by connection string in configuration.

However when I run `dotnet ef database update` I get this error:
```
No DbContext was found in assembly 'mZakazka.Backend.WebApi'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.
```
I also tried `dotnet ef database update --project path/to/database/csproj` but then it says I need to implement `IDesignTimeDbContextFactory<AppDbContext>` in my db project but I dont want to do this.

Is there any way how to make it work?

TargetFramework: netcoreapp2
Microsoft.AspNetCore.All version: 2.1.4
Microsoft.EntityFrameworkCore version: 2.1.3

**Comment by Casimodo72** [comment] 2019-01-23 14:56
AFAIK the ef core tools do not invoke anything on the Startup class. I.e. the stuff you configure there is not accessible/visible to the ef core tools.
In case you want to add the IDesignTimeDbContextFactory at some point, here's one of mine:
```c#
/// <summary>
/// See: https://www.blinkingcaret.com/2018/03/28/setting-up-ef-core/
/// "dotnet ef" will look for a class that implements IDesignTimeDbContextFactory<T> 
/// in the project that contains the DbContext derived class or the project where 
/// you are running donet ef under (this is the project where you navigate to in the 
/// terminal and type donet ef).
/// </summary>
public class DesignTimeGaDbContextFactory : Microsoft.EntityFrameworkCore.Design.IDesignTimeDbContextFactory<GaDbContext>
{
    public GaDbContext CreateDbContext(string[] args)
    {
        var cbuilder = new ConfigurationBuilder();
        cbuilder.SetBasePath(System.IO.Directory.GetCurrentDirectory());
        cbuilder.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
        // TODO: Is there a way to get the environment here and do I need it anyway?
        // cbuilder.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);

        cbuilder.AddEnvironmentVariables();

        if (args != null)
            cbuilder.AddCommandLine(args);

        var config = cbuilder.Build();

        var connectionString = config.GetConnectionString("GeoProjectConnection");
        if (string.IsNullOrEmpty(connectionString))
            throw new InvalidOperationException("Failed to create GaDbContext: Connection string not found in configuration.");

        var options = new DbContextOptionsBuilder<GaDbContext>()
           .UseSqlServer(connectionString)
           .Options;

        return new GaDbContext(options);
    }
}
```

**Comment by alesdvorakcz** [comment] 2019-01-23 18:39
Thanks, I curently use DesignTimeDbContextFactory too. But I need to make sure I will copy right appsettings.json to database project as well. I thought it should work automatically somehow and thats why I am asking.
I also found [this in documentation](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation#from-application-services)
it says "If your startup project is an ASP.NET Core app, the tools try to obtain the DbContext object from the application's service provider."

**Comment by zakar1ya** [comment] 2019-01-23 20:07
Hi, did you try `--startup-project YourAspNetCoreProj` option?

**Comment by ajcvickers** [comment] 2019-01-23 20:56
@alesdvorakcz Based on the information above, this is something that should work if the startup project is specified, as described in the docs. If not, then please post a small, runnable solution that reproduces the projects and dependencies and that shows the error you are seeing.

**Comment by alesdvorakcz** [comment] 2019-01-23 21:06
I think I tried startup-project too but I am not sure because I tried so many things :) I will create small repo to replicate my problem

**Comment by ajcvickers** [comment] 2019-01-30 18:07
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:48 UTC
Labels: closed-could-not-reproduce, customer-reported
