### ISSUE TITLE
EnsureCreatedAsync does not allow to set collation

### ISSUE THREAD

**Issue by Ciantic** [dotnet/efcore#6565] opened 2016-09-17 19:26 UTC
I have a database I drop each time I start a debug server, and then recreate it. The problem is that 
`EnsureCreatedAsync` does not allow to define collation.

Here is a really ugly workaround:

``` c#
await db.Database.EnsureDeletedAsync();
var builder = new SqlConnectionStringBuilder(db.Database.GetDbConnection().ConnectionString) { InitialCatalog = "master" };
builder.Remove("AttachDBFilename");
using (var connection = new SqlServerConnection(new DbContextOptionsBuilder().UseSqlServer(builder.ConnectionString).Options, logger))
{
    connection.Open();
    using (var command = new SqlCommand())
    {
        command.Connection = connection.DbConnection as SqlConnection;
        command.CommandType = System.Data.CommandType.Text;
        command.CommandText = "CREATE DATABASE [mvcApiTest] COLLATE Finnish_Swedish_CI_AS;";
        await command.ExecuteNonQueryAsync();
    }
}
await db.Database.EnsureCreatedAsync();
```

**Comment by rowanmiller** [comment] 2016-09-23 17:50
Dupe of #6577

**Closed** 2022-10-16 09:58 UTC
