### ISSUE TITLE
Database migration creates wrong name when AspNet Identity Role is customized

### ISSUE THREAD

**Issue by ilijevicdenis** [dotnet/efcore#29688] opened 2022-11-27 19:47 UTC
Steps for reproducing: 

1.  Extend identity Role, switch from the int to the Guid type for the primary key

![image](https://user-images.githubusercontent.com/5293299/204156127-8f1bb33d-44d0-4fc3-a630-2ec080707f2e.png)

2. Inside DataContext which extends identity context override on the model  define a new Table name like this

![image](https://user-images.githubusercontent.com/5293299/204156220-528054db-8a8c-4647-b50d-6ae92ca93e34.png)

3. Run migration from the package manager and open the migration file

Result: 
![image](https://user-images.githubusercontent.com/5293299/204156279-40578ef4-6c86-45c9-ac2d-8d761c7aa306.png)

Toolset used: 

![image](https://user-images.githubusercontent.com/5293299/204156348-2f941788-811d-40bc-aed2-15eca17950ff.png)

Effected database: Sql Server, Postgres

**Comment by ajcvickers** [comment] 2022-11-27 19:52
@ilijevicdenis Customizing the Identity model is not easy. Make sure to follow the directions here carefully: https://learn.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-7.0

**Comment by ilijevicdenis** [comment] 2022-11-27 19:54
Well, EF 6 did generated correct name :)

**Comment by ajcvickers** [comment] 2022-12-05 18:54
I am not able to reproduce this. The primary key constraint name is correctly set to "DeltaIdentityRole":

```C#
table.PrimaryKey("DeltaIdentityRole", x => x.Id);
```

Note that setting the constraint name will not change the table name. If this was happening before (which seems very doubtful), then that was a bug.

**Comment by ajcvickers** [comment] 2022-12-14 20:23
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-12-14 20:23 UTC
Labels: customer-reported
