### ISSUE TITLE
Implement appropriate patterns for listening/interception/eventing on StateEntry and elsewhere

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#737] opened 2014-10-01 20:24 UTC
Currently we have an IEntityStateListener interface which is used for listening to changes to state entries. (The name should probably change.) Consider if the listener pattern is appropriate or if events or maybe even interception would be a better fit here. Likewise for "lifecycle hooks" throughout the stack.

**Comment by divega** [comment] 2017-01-13 23:55
@ajcvickers found this issue in the backlog. Should it be closed as a dupe of #626?

**Comment by ajcvickers** [comment] 2017-01-17 18:23
@divega It probably can be. It was originally a different issue to track what kind of "eventing/interception" mechanism to use throughout the stack, but I think that can be covered when we start work on 626.

**Closed** 2022-10-16 08:43 UTC
