### ISSUE TITLE
Support for WHERE in an INDEX

### ISSUE THREAD

**Issue by chassq** [dotnet/efcore#9158] opened 2017-07-12 07:53 UTC
It looks like the scaffolding may not support a WHERE clause on an index? We have an index:

CREATE UNIQUE NONCLUSTERED INDEX [UIX_table_IsDefault]
    ON [table](ProfileId ASC, [IsDefault] ASC) WHERE IsDefault = 1;

The scaffold code looks like:
entity.HasIndex(e => new { e.ProfileId, e.IsDefault })
                    .HasName("UIX_table_IsDefault")
                    .IsUnique();

The scaffold code does not seem to represent the WHERE in the index? Just wanted to see if someone knew if this is supported and if so how to specify the WHERE in the code. If not is it on the roadmap?

Thanks!

### Further technical details
EF Core version: Microsoft.NETCore.App 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 1.1.2 -> Azure SQL - latest version
Operating system: Windows 10 all latest patches
IDE: Visual studio 2017

**Comment by ArieJones** [comment] 2017-07-12 14:31
Have you tried HasFilter ? That is what you are trying to create a filtered index. 
Cheers!
AJ

**Comment by smitpatel** [comment] 2017-07-12 15:12
dupe of #5817 which was fixed in 2.0.0-preview1 release.

**Comment by chassq** [comment] 2017-07-12 16:34
Thank you! Will have to wait for the 2.0.0 release. Much appreciated!

**Closed** 2022-10-16 11:11 UTC
Labels: closed-duplicate
