### ISSUE TITLE
"The operation cannot be completed because the DbContext has been disposed" when multiple request

### ISSUE THREAD

**Issue by glb1028** [dotnet/efcore#4327] opened 2016-01-18 10:42 UTC
i use WCF RESTFull + EF, when call the service one by one, it works fine. but when call it with multiple request, the first request is ok, else maybe got the error.

my code is:

``` C#
using (ContextCore context = new ContextCore(Config.ConnectionString))
{
          response = new Product().GetProductList(context);
          return response;
}

public List<ProductEntity> GetProductList(ContextCore context)
{
        return  Repository<ProductEntity>(context).Select().ToList();
}

public class ContextCore : System.Data.Entity.DbContext, IDbContext
{
        public ContextCore(string connectionString)
            : base(connectionString)
        {
            Configuration.ProxyCreationEnabled = false;
            Configuration.ValidateOnSaveEnabled = false;
        }
......
}
```

**Comment by rowanmiller** [comment] 2016-01-19 21:34
Looks like this is EF6 - which belongs over at http://entityframework.codeplex.com/. We also probably need a way to reproduce the issue. In general, EF works fine in a multi-threaded environment which makes me think you have two requests/threads trying to use the same instance of a context (which is not supported). We probably need a full project that demonstrated the issue so that we can debug it.

**Comment by rowanmiller** [comment] 2016-01-20 18:56
Closing as this is an EF6 issue (code uses APIs that do not exist in EF7/EFCore). Feel free to open an issue in http://entityframework.codeplex.com/ but be sure to include a complete sample that we can use to reproduce the issue.

**Closed** 2022-10-16 09:25 UTC
