### ISSUE TITLE
AddAsync method does not work as expected with inheritance when discriminator is part of primary key

### ISSUE THREAD

**Issue by rajmondburgaj** [dotnet/efcore#24130] opened 2021-02-11 20:17 UTC
I am trying to build a simple schema where I put all translations in one table and I should have the discriminator as part of the primary key.

Here is my base class:

```c#
    public abstract class TranslationEntity
    {
        public long EntityId { get; set; }

        [Column(TypeName = "varchar(2)")]  
        public string TwoLetterCode { get; set; } = "";

        /// <summary>
        /// Dont remove this because it is used to define the primary key
        /// </summary>
        private EntityType EntityType { get; set; }

        [Column(TypeName = "varchar(500)")] 
        public string Translation { get; set; } = "";

        public DateTime CreatedOn { get; set; } = DateTime.UtcNow;
         
        public DateTime? ModifiedOn { get; set; }
    }

    public enum EntityType : short
    {
        Tournament = 1,
        SubTournament = 2,
        Sport = 3,
        Category = 4,
        Venue = 5,
        Competition = 6,
        Group = 7,
        Season = 8
    } 
```

The discriminator column is EntityType, it is private property because I dont want to have external access to this property, because as per my understanding it should be modified and used only by entity framework core itself for its operations.

Then I add child classes(below is an example):

```c#
    public class GroupTranslationEntity : TranslationEntity
    {
    }
```
Below is my OnModelCreating method:

```c#

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TranslationEntity>(x => x.HasKey("EntityId", "TwoLetterCode", "EntityType"));

            modelBuilder.Entity<TranslationEntity>()
                .HasDiscriminator<EntityType>("EntityType")
                .HasValue<TournamentTranslationEntity>(EntityType.Tournament)
                .HasValue<SubTournamentTranslationEntity>(EntityType.SubTournament)
                .HasValue<SportTranslationEntity>(EntityType.Sport)
                .HasValue<CategoryTranslationEntity>(EntityType.Category)
                .HasValue<CompetitionTranslationEntity>(EntityType.Competition)
                .HasValue<VenueTranslationEntity>(EntityType.Venue)
                .HasValue<GroupTranslationEntity>(EntityType.Group)
                .HasValue<SeasonTranslationEntity>(EntityType.Season); 
                 
            base.OnModelCreating(modelBuilder);
        }
```

I have also built a generic method to add or update translations like below:

```c#


        internal async Task<OperationResultNoResult<ErrorType>> SaveTranslationAsync<T>(TranslationRequest request)
            where T : TranslationEntity, new()
        {
            var entity = await inventoryContext.Set<T>()
                .FirstOrDefaultAsync(x => x.TwoLetterCode == request.TwoLetterCode && x.EntityId == request.EntityId);

            if (entity != null)
            {
                entity.Translation = request.Translation;
                entity.ModifiedOn = DateTime.UtcNow;
                logger.LogInformation(
                    $"Entity: {request.EntityId} - {request.EntityType} - {request.TwoLetterCode} is updated.");
            }
            else
            {
                var newEntity = new T
                {
                    TwoLetterCode = request.TwoLetterCode,
                    EntityId = request.EntityId,
                    Translation = request.Translation
                };

                await inventoryContext.Set<T>().AddAsync(newEntity);
                logger.LogInformation(
                    $"Entity: {request.EntityId} - {request.EntityType} - {request.TwoLetterCode} is added.");
            }

            await inventoryContext.SaveChangesAsync();

            return OperationResultNoResult<ErrorType>.Ok();
        }
```

When calling the method `FirstOrDefaultAsync` it will add the correct `EntityType` value in the sql `where` clause. But, when the `AddAsync` method is called it does not add the correct `EntityType` value, but it adds a 0 value instead.

So, I think these two methods are inconsistent!
I think they both should add the correct entityType values accordingly and not use `0` instead.

I am using version 3.1.12 of entity framework core and `Pomelo.EntityFrameworkCore.MySql 3.2.4`

I dont think this is a Pamelo issue because i was able to reproduce the same when using In memory db context.

**Comment by ajcvickers** [comment] 2021-02-12 17:26
Duplicate of #18126

**Closed** 2022-10-16 19:23 UTC
Labels: closed-duplicate, customer-reported
