### ISSUE TITLE
ReadUnCommitted isolationlevel not working with EF Core

### ISSUE THREAD

**Issue by hamedhajiloo** [dotnet/efcore#24565] opened 2021-04-02 03:56 UTC
For isolation level "ReadUncommitted", we should create a transaction:
```
using var transaction = await db.Database.BeginTransactionAsync(isolationLevel: System.Data.IsolationLevel.ReadUncommitted);

try
{
    // Run the query
    await transaction.CommitAsync();
}
catch (Exception)
{ 
    await transaction.RollbackAsync();
}

```
But xEvent Profiler show this profile login:
![image](https://user-images.githubusercontent.com/45947371/113378113-6f2eb000-938b-11eb-835d-b37547910bdd.png)
This login profile is using "Read Committed"!

According to the link below, we have to create two transections:
https://stackoverflow.com/questions/17018938/set-transaction-isolation-level-read-uncommitted-not-taking-or-am-i-looking-i

```
using var tran = await db.Database.BeginTransactionAsync(isolationLevel: System.Data.IsolationLevel.ReadUncommitted);

try
{
    // without any query
    await tran .CommitAsync();
}
catch (Exception)
{ 
    await tran .RollbackAsync();
}

using var transaction = await db.Database.BeginTransactionAsync(isolationLevel: System.Data.IsolationLevel.ReadUncommitted);

try
{
    // Run query
    await transaction.CommitAsync();
}
catch (Exception)
{
    await transaction.RollbackAsync();
}
```

It does not seem like a good idea to open and close the transaction twice.

**Comment by roji** [comment] 2021-04-06 13:17
@hamedhajiloo I could reproduce any issue with the isolation level - please see the attempted code sample at the bottom of the issue. After beginning a transaction with ReadUncommitted, querying the isolation level of the session from sys.dm_exec_sessions returns the value 1, which corresponds to ReadUncommitted ([see the SQL Server docs](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-sessions-transact-sql?view=sql-server-ver15)).

Can you please submit a runnable code sample (similar to what I've posted below) which reproduces the problematic behavior?

> According to the link below, we have to create two transections [...]

@hamedhajiloo the link you posted seems to be a user confusion as to what the parameter-less Sqlconnection.BeginTransaction does (see the accepted answer) - I don't see how it's related to do creating two transactions

**Comment by ajcvickers** [comment] 2021-04-16 14:13
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:30 UTC
Labels: closed-could-not-reproduce, customer-reported
