### ISSUE TITLE
e_sqlite3.dll API not supported Store certification failure for ARM64

### ISSUE THREAD

**Issue by BioTurboNick** [dotnet/efcore#18368] opened 2019-10-14 17:45 UTC
Submitted an app built for ARM64 to Windows store which uses EFCore Sqlite. Previously in store with no issues for ARM, x86, x64. Failure is only on the ARM64 package:

```
API sqlite3_aggregate_context in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_aggregate_count in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_backup_finish in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_backup_init in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_backup_pagecount in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_backup_remaining in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_backup_step in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_bind_blob in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_bind_double in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_bind_int in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_bind_int64 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_bind_null in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_bind_parameter_count in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_bind_parameter_index in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_bind_parameter_name in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_bind_text in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_bind_text16 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_bind_zeroblob in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_blob_bytes in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_blob_close in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_blob_open in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_blob_read in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_blob_write in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_busy_timeout in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_changes in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_clear_bindings in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_close in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_close_v2 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_blob in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_bytes in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_count in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_database_name in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_database_name16 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_decltype in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_decltype16 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_double in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_int in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_int64 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_name in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_name16 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_origin_name in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_origin_name16 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_table_name in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_table_name16 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_text in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_text16 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_column_type in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_commit_hook in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_compileoption_get in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_compileoption_used in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_complete in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_config in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_create_collation in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_create_function_v2 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_data_count in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_db_filename in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_db_handle in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_db_readonly in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_db_status in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_enable_load_extension in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_enable_shared_cache in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_errcode in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_errmsg in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_errstr in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_exec in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_extended_errcode in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_extended_result_codes in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_file_control in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_finalize in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_free in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_get_autocommit in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_initialize in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_interrupt in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_last_insert_rowid in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_libversion in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_libversion_number in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_load_extension in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_log in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_malloc in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_memory_highwater in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_memory_used in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_next_stmt in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_open in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_open16 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_open_v2 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_prepare in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_prepare_v2 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_profile in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_progress_handler in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_realloc in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_reset in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_result_blob in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_result_double in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_result_error in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_result_error16 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_result_error_code in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_result_error_nomem in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_result_error_toobig in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_result_int in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_result_int64 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_result_null in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_result_text in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_result_text16 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_result_zeroblob in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_rollback_hook in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_set_authorizer in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_shutdown in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_sourceid in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_sql in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_status in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_step in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_stmt_busy in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_stmt_readonly in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_stmt_status in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_table_column_metadata in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_threadsafe in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_total_changes in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_trace in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_update_hook in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_user_data in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_value_blob in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_value_bytes in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_value_double in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_value_int in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_value_int64 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_value_text in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_value_text16 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_value_type in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_vfs_find in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_wal_autocheckpoint in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_wal_checkpoint in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_wal_checkpoint_v2 in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
API sqlite3_win32_set_directory in e_sqlite3.dll is not supported for this application type. HemocytometerSidekick.UWP.dll calls this API.
```

### Additional context

Microsoft.Data.Sqlite version: 2.2.6
Target framework: UWP 18362
Operating system: Windows 10 18362.418

**Comment by bricelam** [comment] 2019-10-17 18:53
Duplicate of https://github.com/ericsink/SQLitePCL.raw/issues/254

**Closed** 2022-10-16 14:49 UTC
Labels: closed-external, customer-reported, area-adonet-sqlite
