### ISSUE TITLE
Poor performance because of DbCommand.ExecuteReaderAsync() when reading big string

### ISSUE THREAD

**Issue by forestbat** [dotnet/efcore#17373] opened 2019-08-22 07:56 UTC
https://www.cnblogs.com/dudu/p/10423126.html
If you don't know Chinese，see these：
https://stackoverflow.com/questions/40496012/poor-performance-when-loading-entity-with-large-string-property-using-entity-fra
https://stackoverflow.com/questions/28543293/entity-framework-async-operation-takes-ten-times-as-long-to-complete/28619983#28619983
This problem has existed from 2015 to now，if use Dapper's CommandBehavior.SequentialAccess，the problem has disappeared.
### Further technical details
EF Core version: 2.2.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows or Linux
IDE: Visual Studio 2019 16.3

**Comment by AndriySvyryd** [comment] 2019-08-22 17:45
This is likely a duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/885

**Comment by forestbat** [comment] 2019-08-22 18:01
> This is likely a duplicate of #885

Yes it's duplicate，however you seem to do nothing.

**Closed** 2022-10-16 14:37 UTC
Labels: customer-reported
