### ISSUE TITLE
C# nullable datetime to smalldatetime null

### ISSUE THREAD

**Issue by ldsenow** [dotnet/efcore#21076] opened 2020-05-28 23:58 UTC
Hi there,

I have a File class with a nullable IssueDate and my db schema of this field is a smalldatetime type.
My mapping for EF core as below. When I try to insert a null value of IssueDate, it throws exception.
My question is what the practice should I take to avoid having this issue?

Many thanks
### Steps to reproduce

``` C#
class File {
public DateTime? IssueDate { get; set; }
}


builder.Property(x => x.IssueDate).IsRequired(false).HasColumnType("smalldatetime");
```

Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The conversion of a datetime2 data type to a smalldatetime data type resulted in an out-of-range value.
The statement has been terminated.

### Further technical details

EF Core version: EF Core 3.1.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET Core 3.0
Operating system:
IDE: Visual Studio 2019 16.3

**Comment by ldsenow** [comment] 2020-05-29 00:01
public class File{
public DateTime? IssueDate{get;set;}
}

builder.Property(x => x.IssueDate).IsRequired(false).HasColumnType("smalldatetime");

**Comment by maumar** [comment] 2020-05-29 01:31
@ldsenow I used the following repro code and everything works as expected on 3.1.4. Can you modify the code below so that it shows the problem?

```cs
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var f = new File { IssueDate = null };
                ctx.Files.Add(f);
                ctx.SaveChanges();
            }
        }
    }

    public class File
    {
        public int Id { get; set; }
        public DateTime? IssueDate { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<File> Files { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<File>().Property(x => x.IssueDate).IsRequired(false).HasColumnType("smalldatetime");
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Repro21076;Trusted_Connection=True;MultipleActiveResultSets=true");
        }
    }

```

**Comment by ajcvickers** [comment] 2020-06-08 16:03
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:27 UTC
Labels: closed-could-not-reproduce, customer-reported
