### ISSUE TITLE
ExcludeProperty instead of Select() inclusively per query

### ISSUE THREAD

**Issue by jsheely** [dotnet/efcore#22683] opened 2020-09-23 15:16 UTC
I would like to be able to exclude certain properties from the SQL that is fetched without having to inclusively add each property I want in a .Select()

Example:

```
// Model
public class Product {
    public int Id {get;set;}
    public string Name {get;set;}
    public string BigBloatedJson {get;set;}
}

// Exclude BigBloatedJson property to get (select Id, Name from Product where Id =@Id)
dbContext.Product.Where(x => x.Id == Id).ExcludeProperty(x => x.BigBloatedJson).FirstOrDefault();

// Instead of what you have to do now
dbContext.Product.Where(x => x.Id == Id).Select(x => new Product {Id = x.Id, Name = x.Name}).FirstOrDefault();
```

In this simple example I only have a couple properties. But in a larger entity and one that make have base class inheritance it becomes much more tedious.

Is this even possible with the current architecture? Has anyone done it? Is there a better way?

**Comment by ajcvickers** [comment] 2020-09-25 21:11
Duplicate of #1387

**Closed** 2022-10-16 18:42 UTC
Labels: customer-reported
