### ISSUE TITLE
I cannot do a migration from package manager

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#24113] opened 2021-02-10 19:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/I-cannot-do-a-migration-from-package-man/1320682)._

---
[severity:It's more difficult to complete my work]
I have a brand new laptop which I have downloaded and installed Visual Studio 2019 on to.

Everything looks fine but I cannot do code first add migration from package manager.

PM> add-migration test123
The specified deps.json [C:\Users\xxxxx\source\Repos\ProjectPortal\xxxxx.Web\xxxxx.Web.deps.json] does not exist

---
#### Feedback Bot on 1/26/2021, 05:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2021-02-10 19:39
Duplicate of #16386

**Closed** 2022-10-16 19:22 UTC
Labels: closed-duplicate, customer-reported
