### ISSUE TITLE
Azure SQL options does not work

### ISSUE THREAD

**Issue by pchrist84** [dotnet/efcore#21359] opened 2020-06-21 21:55 UTC
Hi there!
When I use modelBuilder.HasServiceTier("Basic") in OnModelCreating I get an error: ''**Microsoft.Data.SqlClient.SqlException**: 'Incorrect syntax near '('.'"

![log](https://user-images.githubusercontent.com/67243357/85235947-a3973800-b419-11ea-96f4-50d5bcf3816f.PNG)

### Steps to reproduce

`
 protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasServiceTier("Basic");
            modelBuilder.RemovePluralizingTableNameConvention();

            foreach (var relationship in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
            {
                relationship.DeleteBehavior = DeleteBehavior.Restrict;
            }

            modelBuilder.ApplyConfiguration(new ArticleBasicInfoConfiguration());
            modelBuilder.ApplyConfiguration(new ArticleBatchConfiguration());

            base.OnModelCreating(modelBuilder);
        }`

### Further technical details

EF Core version: 3.1.5
Target framework: .NET Core 3.1
Operating system: IDE: Visual Studio 2019 16.6

**Comment by AndriySvyryd** [comment] 2020-06-22 15:48
These options only work on Azure SQL Database. Is that what you are targeting when you are applying the migration?

**Comment by ajcvickers** [comment] 2020-06-29 14:58
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:30 UTC
Labels: closed-could-not-reproduce, customer-reported
