### ISSUE TITLE
Feature proposal: Add support for primitive arrays with InMemoryDatabase

### ISSUE THREAD

**Issue by olivierr91** [dotnet/efcore#10600] opened 2017-12-21 04:01 UTC
Most database providers (Npgsql) seem to support primitive arrays (string[], bool[], etc...), but InMemoryDatabase do not. The current workaround is to use a different setter/getter and serialize/deserialize to a string.  It would be nice to add support for this with InMemoryDatabase so we do not have to use different getter/setter methods for testing.

**Comment by ajcvickers** [comment] 2018-01-03 23:33
Notes from triage: Support for this in the in-memory database should be done using general mechanisms in EF to map to collections of primitive types, once this is implemented. See #4179. Some EF Core providers (e.g. npgsql) have their own type mappings for this, which can work with limitations--for example, see #9753. Something like this could be done for the in-memory provider, but overall we feel it would be better done as a non-custom mapping.

**Comment by AndriySvyryd** [comment] 2020-08-12 16:13
Duplicate of https://github.com/dotnet/efcore/issues/11926

**Closed** 2022-10-16 12:03 UTC
