### ISSUE TITLE
How to convert from IModel to RelationalModel and preserve annotations EFC

### ISSUE THREAD

**Issue by Browniee97** [dotnet/efcore#29980] opened 2023-01-04 22:53 UTC
I am trying get the differences between two IModels. using IMigrationsModelDiffer.GetDifferences(). In EFCore 6 this requires two relationalModels rather than IModels. I can convert the IModels to RelationalModels using GetRelationalModel extension method for IModel however this approach does not preserve the annotations and any annotations that were on the IModel are not copied to the generated RelationalModel. Since GetDifferences relies on the annotations to work its magic it isnt able to detect differences between the two models.

The following code demonstrates this:

```
var oldRelationalModel = oldModel.GetRelationalModel();
Log.Information("Old IModel Annotations: {0}", oldModel.GetAnnotations().Count());
Log.Information("Old RelationalModel Annotations: {0}", oldRelationalModel.GetAnnotations().Count());

var newRelationalModel = newModel.GetRelationalModel();
Log.Information("Old IModel Annotations: {0}", newModel.GetAnnotations().Count());
Log.Information("Old RelationalModel Annotations: {0}", newRelationalModel.GetAnnotations().Count());

var modelDiffer = _db.GetService<IMigrationsModelDiffer>();
var operations = modelDiffer.GetDifferences(oldRelationalModel, newRelationalModel);
```

Which has the following output
```
[15:57:46 INF] Old IModel Annotations: 5
[15:57:46 INF] Old RelationalModel Annotations: 0
[15:57:46 INF] Old IModel Annotations: 5
[15:57:46 INF] Old RelationalModel Annotations: 0
```

Also note that in this example operations will not contain anything, even where there are verified and observed differences between the two models. This is due to the annotations not being copied.

### My Environment
Target framework: net6.0
Database provider: Microsoft.EntityFrameworkCore 6.0.4
Operating system: Windows 10 64bit
IDE: JetBrains Rider 2022.2.3

**Comment by ajcvickers** [comment] 2023-01-12 11:34
@Browniee97 We discussed this and have a few questions:
* What are the annotations that need to be copied over? Are they custom annotations that you have created?
* What will the annotations be used for?
* What is the purpose of doing the model diff? That is, what do you do with the result of the diff once it is obtained?

**Comment by ajcvickers** [comment] 2023-01-27 13:07
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-01-27 13:07 UTC
Labels: customer-reported
