### ISSUE TITLE
NotMapped property attached to db column work or not depending declaration format

### ISSUE THREAD

**Issue by brunofrance** [dotnet/efcore#29615] opened 2022-11-18 17:29 UTC
Hello,

We can write properties differently, but it is a proble when using EFCore to SQL server: 

[NotMapped] public int PP_ { get { return Int1; } set { Int1 = value; } }
=> 👍works, is translated as "where Int1 = xxx" for example

[NotMapped] public int Category_ { get => Int2; set => Int2 = value; }
=> 😢doesn't works,

EF Core version: 7.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system:
IDE: Visual Studio 2022 17.4

**Comment by roji** [comment] 2022-11-18 17:42
@brunofrance please attach a minimal, runnable code sample which shows what's not working for you.

**Comment by brunofrance** [comment] 2022-11-18 18:49
Sorry, the problem is different :

Using the column Int1 :
`(from x in DC.LEntityDatas.OfType<LEntity_PP>() where x.Int1 != 0 select x.Int1).FirstOrDefault()  `   => OK

Using the property PP_ associated to int1 int the Select section
`(from x in DC.LEntityDatas.OfType<LEntity_PP>() where x.Int1 != 0 select x.PP_).FirstOrDefault()`     => OK
 _[NotMapped] public int PP_ { get { return Int1; } set { Int1 = value; } }_

Using the property PP_ associated to int1 int the Where section
`(from x in DC.LEntityDatas.OfType<LEntity_PP>() where x.**PP_** != 0 select x.PP_).FirstOrDefault()`     => ERROR

So it's just strange that with select, EF translate PP_ to Int1, but with Where, throw the exception
> Translation of member 'PP_' on entity type 'LEntity_PP' failed. This commonly occurs when the specified member is unmapped

**Comment by roji** [comment] 2022-11-18 21:05
Assuming that your Int1 property is mapped but your PP_ property is not, the above is expected; EF cannot translate a filter with an unmapped property to SQL (there's no column in the database). However, in the last select you can specify an unmapped property, since EF supports client evaluation in the last select ([read these docs to know more](https://learn.microsoft.com/en-us/ef/core/querying/client-eval)). Doing so probably won't be useful - PP_ isn't populated when the entity is instantiated, but it is a valid query and doesn't error.

**Comment by brunofrance** [comment] 2022-11-21 08:49
Thanks roji. So it's not a bug, sorry.

Perhaps you can help me to know if there is a solution in my case
My table "LEntityData" can contain various datas switch a discriminator.

- if discriminator is "1", Int1 is a "PP_"
- if disciminator is "2", Int1 is a "QF_" 

Is there a solution to map "Int1" to the property "PP_" in my class LEntity_PP , and to map the same column "Int1" to "QF_" in my other class LEntity_QF ?

my code :
`public partial class LEntity_PP : LEntityData
{
   [NotMapped, JsonIgnore] public int PP_ { get => Int1; set => Int1 = value; }
}
public partial class LEntity_QF : LEntityData
{
   [NotMapped, JsonIgnore] public int QF_ { get => Int1; set => Int1 = value; }
}

modelBuilder.Entity<LEntityData>()
            .HasDiscriminator<LEntityData.EntityDataType>("TypeP")
            .HasValue<LEntityData>(LEntityData.EntityDataType.NoFilter)
            .HasValue<LEntityData_PP>(LEntityData.EntityDataType.PP) // 1
            .HasValue<LEntityData_QF>(LEntityData.EntityDataType.QF) // 2`

Thanks

**Comment by roji** [comment] 2022-11-21 09:36
What's wrong with the code you posted above? It looks OK to me.

**Comment by roji** [comment] 2022-11-21 15:46
If you'd like to query by a property, it must be mapped.

Why not map PP_ and QF_, and if you want, you can have an unmapped Int1 that returns they value based on the discrimiator? If you're using TPH mapping, you can have PP_ and QF_ map to the same column in the database by setting the column name to the same thing via HasColumnName.

**Comment by ajcvickers** [comment] 2022-12-01 13:41
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-12-01 13:41 UTC
Labels: closed-no-further-action, customer-reported
