### ISSUE TITLE
NetCore App with Mono - DllNotFoundException

### ISSUE THREAD

**Issue by deinok** [dotnet/efcore#12322] opened 2018-06-11 11:30 UTC
Hi, I have a NetCore app that i need to run in a linux-x86.
NetCore don't support linux-x86, only x64 and arm. So I have to use Mono, targeting net471.

Everything works fine except Microsoft.EntityFrameworkCore.Sqlite.
Seems like i'm having a `System.DllNotFoundException: e_sqlite3`

I'm doing something in an incorrect way?

* dotnet --version (On Compilation machine) [dotnet--version.log](https://github.com/ericsink/SQLitePCL.raw/files/2044512/dotnet--version.log)
* mono --version (On Execution machine) [mono--version.log](https://github.com/ericsink/SQLitePCL.raw/files/2044474/mono--version.log)
* mono *.exe (`dotnet publish --configuration Release --framework net471`)(Executed on the execution machine) [execution-log.log](https://github.com/ericsink/SQLitePCL.raw/files/2044521/execution-log.log)

**Comment by bricelam** [comment] 2018-06-11 17:43
Duplicate of ericsink/SQLitePCL.raw#221

**Comment by deinok** [comment] 2018-06-11 17:47
@bricelam Yes, the point is that using directly SQLitePCL works, but not when I use EntityFrameworkCore.SQLite

**Comment by bricelam** [comment] 2018-06-11 20:51
Ah, then it's probably just [NuGet weirdness](https://github.com/NuGet/Home/issues/6091). Try installing `Microsoft.EntityFrameworkCore.Sqlite` (or `Microsoft.Data.Sqlite` or `SQLitePCLRaw.bundle_green`) directly into your EXE project.

**Closed** 2022-10-16 12:30 UTC
Labels: closed-could-not-reproduce, customer-reported
