### ISSUE TITLE
User-defined function mapping not working when resolving context through dependency injection.

### ISSUE THREAD

**Issue by shumkis** [dotnet/efcore#28668] opened 2022-08-11 08:29 UTC
Hello,

I've been trying to map scalar function from DB. Did everything exactly as specified in https://docs.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping with no luck. I inject DBContext through Dependecy injection using an interface. And when I try to use scalar function in queries,  „throw new NotSupportedException();“ implementation of the method is always executed. If I create a new instance of DBContext with "using" keyword, everything works fine and DB function get's called.

**Comment by ajcvickers** [comment] 2022-08-11 14:11
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-08-22 12:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-08-22 12:30 UTC
