### ISSUE TITLE
Linq RemoveRange, allow use of join with fields matching

### ISSUE THREAD

**Issue by ice1e0** [dotnet/efcore#20191] opened 2020-03-05 20:37 UTC
I use implement normally the cascading delete for foreign keys in my application code myself instead of using the default mechanism.

In EF Core 2.2 I could execute the following:

``` c#
// this list is generated somehow in the system
ICollection<EntityB> entries = new List<EntityB>(){
	new EntityB { Key = "1234" },
	new EntityB { Key = "4321" }
};

// here we delete all EntryA entities which are referenced by the EntityB entities I hold in the list
dataContext.Set<EntityA>().RemoveRange(
	from a in dataContext.Set<EntityA>().AsQueryable()
	join b in entries on a.key equals b.key
	select a
);
```

Nice code style...

After the upgrade to EF Core 3.1 this doesn't work anymore, and I have to build something like this:
``` c#
ICollection<EntityB> entries = new List<EntityB>(){
	new EntityB { Key = "1234" },
	new EntityB { Key = "4321" }
};

var bKeysToDelete = entries.Select(g => g.Key).ToList();

fiscalPeriodRepo.RemoveRange(
	from a in dataContext.Set<EntityA>().AsQueryable()
	where bKeysToDelete.Contains(a.Key)
	select fiscalPeriod
);
```

I expect a SQL execution similar to this:
``` sql
DELETE FROM EntityA
WHERE EntityA.Key IN ('1234', '4321')

-- or --

DELETE FROM EntityA
WHERE EntityA.Key IN @ParameterList

-- or --

DELETE FROM EntityA
WHERE EntityA.Key = '1234' OR EntityA.Key = '4321'
```

I think this is now more confusing code style now; and when I have multiple key fields, I don't see another option than to iterate through the objects and make a single deletion.

I think there must be a better option available... I think LinqToSql is there to make live easy and source code more readable...

**Comment by smitpatel** [comment] 2020-03-06 01:59
Duplicate of #795

**Comment by sdanyliv** [comment] 2020-03-06 15:21
@ice1e0, I don’t want to be intrusive, but you can try our extension [linq2db.EntityFrameworkCore](https://github.com/linq2db/linq2db.EntityFrameworkCore)
Then you can remove records by `Delete` extension.
```
var query = from a in dataContext.Set<EntityA>()
	where bKeysToDelete.Contains(a.Key)
	select a

query.Delete();
```

**Closed** 2022-10-16 18:14 UTC
Labels: closed-duplicate, customer-reported
