### ISSUE TITLE
Optimistic concurrency check should be configurable

### ISSUE THREAD

**Issue by MarcoLoetscher** [dotnet/efcore#6218] opened 2016-08-01 12:39 UTC
[How concurrency tokens work in EF](https://docs.efproject.net/en/latest/modeling/concurrency.html?highlight=concurrency#how-concurrency-tokens-work-in-ef). UPDATE and DELETE commands are treated equally in EF Core. I think the DELETE command should only have the primary key in the WHERE clause. If an entity has already been deleted by another user, DbUpdateConcurrencyException should't be thrown because it is not relevant. If I want to delete an entity, it is also not relevat whether it has been changed in the meantime by another user.

In an UPDATE command the WHERE clause should be configurable, like the DataSet. It should be possible to include all the modified properties in the WHERE clause (ConflictOption.CompareAllSearchableValues).
[DbCommandBuilder.ConflictOption Property](https://msdn.microsoft.com/en-us/library/system.data.common.dbcommandbuilder.conflictoption%28v=vs.110%29.aspx), [ConflictOption Enumeration](https://msdn.microsoft.com/en-us/library/system.data.conflictoption%28v=vs.110%29.aspx)
I am aware that the concurrency check in EF core is the same as in EF 6.x, but I think that things can be improved in EF Core.
Thanks a lot.

**Comment by roji** [comment] 2022-10-19 07:21
The question of disabling concurrency checking for delete is covered by #10443, see specifically https://github.com/dotnet/efcore/issues/10443#issuecomment-1264600042; this is part of a larger question of allowing more configurability around optimistic concurrency. For example, doing optimistic concurrency checking on updates usually makes no sense if no concurrency token isn't defined.

The other thing requested by the OP is the ability to define all properties as concurrency tokens. I think that's an anti-pattern in most (possibly all) cases, for performance reasons. However, we already allow defining multiple concurrency tokens, so the user is free to do that if they wish; a user convention could allow automating this as well.

So proposing to close this as a dup of #10443.

**Comment by roji** [comment] 2022-10-19 07:21
Duplicate of #10443

**Closed** 2022-10-20 10:03 UTC
