### ISSUE TITLE
migrationBuilder.UpdateData() translates TimeOnly to wrong time in SQL (AM/PM Issue)

### ISSUE THREAD

**Issue by jlorek** [dotnet/efcore#32229] opened 2023-11-03 16:41 UTC
Hey 👋

Given the following simple class.

```C#
public class Foo
{
    Guid Id { get; set }
    TimeOnly MyTime { get; set; }
}
````

Using `migrationBuilder.UpdateData()` in a Migration file creates wrong values in SQL.

```C#
migrationBuilder.UpdateData(
    table: "Foo",
    keyColumn: "Id",
    keyValue: "123",
    columns: new[]
    {
        "MyTime",
    },
    values: new object[]
    {
        new TimeOnly(21, 45),
    });
```

When running `dotnet ef migrations script` the TimeOnly object resolves to `09:45:00`, which looks like AM/PM is not taken into account here.

```sql
UPDATE [Foo] SET [MyTime] = '09:45:00'
WHERE [Id] = '123';
SELECT @@ROWCOUNT;
```

But when applying the migrations in the Application with `dbContext.Database.MigrateAsync()` the correct Time `21:45:00` is written to the database.

### Include provider and version information

EF Core version: 7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 7.0
Operating system: macOS

**Comment by ajcvickers** [comment] 2023-11-06 14:45
@jlorek Given that TimeOnly is not supported out-of-the-box on EF7, how are you mapping it here? Can you please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by jlorek** [comment] 2023-11-15 07:59
@ajcvickers Thanks for pointing that out, i almost forgot we hat to build some custom code for this. It's pretty simple code, but i will construct a small, runnable example the upcoming days.

```
    public static ModelConfigurationBuilder ConvertTimeOnlyToTime(this ModelConfigurationBuilder instance)
    {
        instance.Properties<TimeOnly>()
            .HaveConversion<TimeOnlyConverter>()
            .HaveColumnType("time");

        return instance;
    }
```

```
    public TimeOnlyConverter() : base(
        timeOnly => timeOnly.ToTimeSpan(),
        timeSpan => TimeOnly.FromTimeSpan(timeSpan))
    { }
```

**Comment by ajcvickers** [comment] 2023-11-29 17:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-11-29 17:20 UTC
Labels: customer-reported
