### ISSUE TITLE
AsSplitQuery() extension should use multiple result sets to reduce database roundtrips to 1

### ISSUE THREAD

**Issue by t00** [dotnet/efcore#24550] opened 2021-03-31 06:25 UTC
Currently AsSplitQuery() correctly generates several separate queries with a shared set of parameters, helping to avoid cartesian explosion on queries including dependent tables with multiple related rows.

The problem is that these queries are executed as separate commands, each adding up an additional database round-trip. Since ADO providers allow multiple result sets, this should be the default behavior to reduce number of round-trips from n to 1.

**Comment by roji** [comment] 2021-03-31 07:01
Duplicate of #10878

**Closed** 2022-10-16 19:30 UTC
Labels: customer-reported
