### ISSUE TITLE
Proposal: Better exception message for "Nullable object must have a value."

### ISSUE THREAD

**Issue by reinux** [dotnet/efcore#26934] opened 2021-12-07 19:41 UTC
Right now, what's effectively a null reference exception is just reported as "InvalidOperationException: Nullable object must have a value."

This is confusing and time-consuming for several reasons:

- The language feature is a nullable reference type, but the problem is that it's specifically a non-nullable to which a null is attempting to be assigned, so "Nullable object" is extremely misleading.
- InvalidOperationException is extremely broad.
- There's no indication as to which field or column is causing the exception, so it's a total guessing game as to where the null is coming in from.

It would be useful if the exception actually described which fields/columns are involved in the exception, e.g.:

> Attempting to assign null value to non-nullable field CompanyId.

**Comment by ajcvickers** [comment] 2021-12-11 20:02
@reinux In most cases like this using `EnableDetailedErrors` will provide much more helpful information.  See [Detailed query exceptions](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/simple-logging#detailed-query-exceptions). Can you give this a try and report back with a complete code example if it doesn't help?

**Comment by ajcvickers** [comment] 2022-01-11 12:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:18 UTC
Labels: closed-no-further-action, customer-reported
