### ISSUE TITLE
The query processor ran out of internal resources

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#25871] opened 2021-09-03 20:32 UTC
## Ask a question

Users can filter on a number of criteria in an app. I'm seeing the following error when running a query that has a lot of filters. This mostly translates to an `Exists` statement for most filter criteria, which are spread across multiple tables.

> The query processor ran out of internal resources and could not produce a query plan. This is a rare event and only expected for extremely complex queries or queries that reference a very large number of tables or partitions. Please simplify the query. If you believe you have received this message in error, contact Customer Support Services for more information.

When I take the SQL from the Application Output and reassemble with the query parameters, it runs just fine.

Why would it be different for EF Core and is it something I can mitigate?

### Include provider and version information

EF Core version: 5.0.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: macOS 11.5.2
IDE: Visual Studio 2022 for Mac build 2706

**Comment by ajcvickers** [comment] 2021-09-04 08:07
@mrlife Can you copy the SQL from the query DebugView (or use `ToQueryString`) and post here so that we can see?

**Comment by mrlife** [comment] 2021-09-07 14:21
@ajcvickers Thank you, here is the SQL with names changed. Note that each instance of `'123'` was a unique value in the original SQL. This takes about 6 seconds to run in Azure Data Studio.

```sql
SELECT COUNT(*)
      FROM [dbo].[my_view] AS [e]
      WHERE ((((((((((((((((([e].[MyFlag] = CAST(1 AS tinyint)) AND [e].[special_id] IN (N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123', N'123')) AND ([e].[MyFlag] = CAST(1 AS tinyint))) AND EXISTS (
          SELECT 1
          FROM MyTable AS [c]
          LEFT JOIN MyTable2 AS [c0] ON [c].[Id] = [c0].[MyId]
          WHERE (([c].[special_id] = [e].[special_id]) OR ([c].[special_id] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
              SELECT 1
              FROM MyTable6 AS [c1]
              INNER JOIN [People] AS [u] ON [c1].[MyId3] = [u].[Id]
              WHERE ([c0].[Id] IS NOT NULL AND ([c0].[Id] = [c1].[MyId2])) AND [u].[special_id2] IN (N'123', N'123')))) AND EXISTS (
          SELECT 1
          FROM MyTable AS [c2]
          LEFT JOIN MyTable2 AS [c3] ON [c2].[Id] = [c3].[MyId]
          WHERE (([c2].[special_id] = [e].[special_id]) OR ([c2].[special_id] IS NULL AND [e].[special_id] IS NULL)) AND (('a' LIKE N'123') OR (CHARINDEX('a', [c3].[Goal]) > 0)))) AND EXISTS (
          SELECT 1
          FROM MyTable AS [c4]
          LEFT JOIN MyTable2 AS [c5] ON [c4].[Id] = [c5].[MyId]
          WHERE (([c4].[special_id] = [e].[special_id]) OR ([c4].[special_id] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
              SELECT 1
              FROM MyTable7 AS [c6]
              WHERE ([c5].[Id] IS NOT NULL AND ([c5].[Id] = [c6].[MyId4])) AND ([c6].[MyId10] = 3)))) AND EXISTS (
          SELECT 1
          FROM MyTable AS [c7]
          LEFT JOIN MyTable2 AS [c8] ON [c7].[Id] = [c8].[MyId]
          WHERE (([c7].[special_id] = [e].[special_id]) OR ([c7].[special_id] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
              SELECT 1
              FROM MyTable7 AS [c9]
              LEFT JOIN [People] AS [u0] ON [c9].[MyId9] = [u0].[Id]
              WHERE ([c8].[Id] IS NOT NULL AND ([c8].[Id] = [c9].[MyId4])) AND ([u0].[special_id2] = '123')))) AND EXISTS (
          SELECT 1
          FROM MyTable AS [c10]
          LEFT JOIN MyTable2 AS [c11] ON [c10].[Id] = [c11].[MyId]
          WHERE (([c10].[special_id] = [e].[special_id]) OR ([c10].[special_id] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
              SELECT 1
              FROM MyTable7 AS [c12]
              WHERE ([c11].[Id] IS NOT NULL AND ([c11].[Id] = [c12].[MyId4])) AND (('d' LIKE N'123') OR (CHARINDEX('d', [c12].[MyText]) > 0))))) AND EXISTS (
          SELECT 1
          FROM MyTable AS [c13]
          LEFT JOIN MyTable2 AS [c14] ON [c13].[Id] = [c14].[MyId]
          WHERE (([c13].[special_id] = [e].[special_id]) OR ([c13].[special_id] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
              SELECT 1
              FROM MyTable7 AS [c15]
              WHERE ([c14].[Id] IS NOT NULL AND ([c14].[Id] = [c15].[MyId4])) AND ([c15].[MyDate1] = '2021-09-25T00:00:00.0000000')))) AND EXISTS (
          SELECT 1
          FROM MyTable AS [c16]
          WHERE (([c16].[special_id] = [e].[special_id]) OR ([c16].[special_id] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
              SELECT 1
              FROM MyTable3 AS [c17]
              WHERE ([c16].[Id] = [c17].[MyId]) AND ([c17].[MyId5] = '123')))) AND EXISTS (
          SELECT 1
          FROM MyTable AS [c18]
          WHERE (([c18].[special_id] = [e].[special_id]) OR ([c18].[special_id] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
              SELECT 1
              FROM MyTable3 AS [c19]
              WHERE ([c18].[Id] = [c19].[MyId]) AND ([c19].[MyId6] = '123')))) AND EXISTS (
          SELECT 1
          FROM MyTable AS [c20]
          WHERE (([c20].[special_id] = [e].[special_id]) OR ([c20].[special_id] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
              SELECT 1
              FROM MyTable3 AS [c21]
              WHERE ([c20].[Id] = [c21].[MyId]) AND ([c21].[MyDate2] = '2021-10-04T00:00:00.0000000')))) AND EXISTS (
          SELECT 1
          FROM MyTable AS [c22]
          WHERE (([c22].[special_id] = [e].[special_id]) OR ([c22].[special_id] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
              SELECT 1
              FROM MyTable3 AS [c23]
              WHERE ([c22].[Id] = [c23].[MyId]) AND ([c23].[MyText] = 'd')))) AND EXISTS (
          SELECT 1
          FROM MyTable AS [c24]
          WHERE (([c24].[special_id] = [e].[special_id]) OR ([c24].[special_id] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
              SELECT 1
              FROM MyTable4 AS [c25]
              WHERE ([c24].[Id] = [c25].[MyId]) AND ([c25].[MyId7] = '123')))) AND EXISTS (
          SELECT 1
          FROM MyTable AS [c26]
          WHERE (([c26].[special_id] = [e].[special_id]) OR ([c26].[special_id] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
              SELECT 1
              FROM MyTable4 AS [c27]
              WHERE ([c26].[Id] = [c27].[MyId]) AND (('d' LIKE N'123') OR (CHARINDEX('d', [c27].[MyText]) > 0))))) AND EXISTS (
          SELECT 1
          FROM MyTable AS [c28]
          WHERE (([c28].[special_id] = [e].[special_id]) OR ([c28].[special_id] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
              SELECT 1
              FROM MyTable5 AS [c29]
              LEFT JOIN [People] AS [u1] ON [c29].[MyId8] = [u1].[Id]
              WHERE ([c28].[Id] = [c29].[MyId]) AND ([u1].[special_id2] = '123')))) AND EXISTS (
          SELECT 1
          FROM MyTable AS [c30]
          WHERE (([c30].[special_id] = [e].[special_id]) OR ([c30].[special_id] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
              SELECT 1
              FROM MyTable5 AS [c31]
              WHERE ([c30].[Id] = [c31].[MyId]) AND (('a' LIKE N'123') OR (CHARINDEX('a', [c31].[MyText]) > 0))))) AND EXISTS (
          SELECT 1
          FROM MyTable AS [c32]
          WHERE (([c32].[special_id] = [e].[special_id]) OR ([c32].[special_id] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
              SELECT 1
              FROM MyTable5 AS [c33]
              WHERE ([c32].[Id] = [c33].[MyId]) AND (('a' LIKE N'123') OR (CHARINDEX('a', [c33].[MyText]) > 0))))
```

**Comment by ajcvickers** [comment] 2021-09-07 15:17
@mrlife So, just to be clear, the query generated has _no parameters_? In other words, the output from ToQueryString doesn't contain any `DECLARE` statements at the start?

**Comment by mrlife** [comment] 2021-09-07 15:40
@ajcvickers Sorry, the query was from the Application Output window with the parameter values modified for privacy and interpolated into the query. Would the raw ToQueryString output be more useful?

**Comment by ajcvickers** [comment] 2021-09-07 15:44
@mrlife Yes, because parameterization is very important to what query plan is used.

**Comment by mrlife** [comment] 2021-09-07 16:47
@ajcvickers Here is the output of ToQueryString with values, table names, etc. modified for privacy.

```sql
DECLARE @__Trim_2 nvarchar(4000) = N'd';
DECLARE @__var1 int = 1;
DECLARE @__var2 nvarchar(4000) = N'123';
DECLARE @__Trim_5 nvarchar(4000) = N'd';
DECLARE @__var3 datetime2 = '2021-10-01T00:00:00.0000000';
DECLARE @__var4 nvarchar(4000) = N'105';
DECLARE @__var5 nvarchar(4000) = N'1';
DECLARE @__var6 datetime2 = '2021-10-01T00:00:00.0000000';
DECLARE @__Trim_10 nvarchar(4000) = N'd';
DECLARE @__var7 int = 1;
DECLARE @__Trim_12 nvarchar(4000) = N'd';
DECLARE @__var8 nvarchar(4000) = N'456';
DECLARE @__Trim_14 nvarchar(4000) = N'd';
DECLARE @__Trim_15 nvarchar(4000) = N'd';

SELECT COUNT(*)
FROM [datamart].[entity_level] AS [e]
WHERE ((((((((((((((((([e].[MyFlag] = CAST(1 AS tinyint)) AND [e].[special_id] IN (N'1',N'2',N'3',N'4',N'5',N'6',N'7',N'8',N'9',N'10',N'11',N'12',N'13',N'14',N'15',N'16',N'17',N'18',N'19',N'20',N'21',N'22',N'23',N'24',N'25',N'26',N'27',N'28',N'29',N'30',N'31',N'32',N'33',N'34',N'35',N'36',N'37',N'38',N'39',N'40',N'41',N'42',N'43',N'44',N'45',N'46',N'47',N'48',N'49',N'50',N'51',N'52',N'53',N'54',N'55',N'56',N'57',N'58',N'59',N'60',N'61',N'62',N'63',N'64',N'65',N'66',N'67',N'68',N'69',N'70',N'71',N'72',N'73',N'74',N'75',N'76',N'77',N'78',N'79',N'80',N'81',N'82',N'83',N'84',N'85',N'86',N'87',N'88',N'89',N'90',N'91',N'92',N'93',N'94',N'95',N'96',N'97',N'98',N'99',N'100',N'101',N'102',N'103',N'104',N'105',N'106',N'107',N'108',N'109',N'110',N'111',N'112',N'113',N'114',N'115',N'116',N'117',N'118',N'119',N'120',N'121',N'122',N'123',N'124',N'125',N'126',N'127',N'128',N'129',N'130',N'131',N'132',N'133',N'134',N'135',N'136',N'137',N'138',N'139',N'140',N'141',N'142',N'143',N'144',N'145',N'146',N'147',N'148',N'149',N'150',N'151',N'152',N'153',N'154',N'155',N'156',N'157',N'158',N'159',N'160',N'161',N'162',N'163',N'164',N'165',N'166',N'167',N'168',N'169',N'170',N'171',N'172',N'173',N'174',N'175',N'176',N'177',N'178',N'179',N'180',N'181',N'182',N'183',N'184',N'185',N'186',N'187',N'188',N'189',N'190',N'191',N'192',N'193',N'194',N'195',N'196',N'197',N'198',N'199',N'200',N'201',N'202',N'203',N'204',N'205',N'206',N'207',N'208',N'209',N'210',N'211',N'212',N'213',N'214',N'215',N'216')) AND ([e].[MyFlag] = CAST(1 AS tinyint))) AND EXISTS (
    SELECT 1
    FROM MyTable AS [c]
    LEFT JOIN MyTable2 AS [c0] ON [c].[Id] = [c0].[MyTable2_Id]
    WHERE (([c].[SpecialId] = [e].[special_id]) OR ([c].[SpecialId] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
        SELECT 1
        FROM MyTable7 AS [c1]
        INNER JOIN [People] AS [u] ON [c1].[MyId2] = [u].[Id]
        WHERE ([c0].[Id] IS NOT NULL AND ([c0].[Id] = [c1].[MyId8])) AND [u].[special_id2] IN (N'234', N'567')))) AND EXISTS (
    SELECT 1
    FROM MyTable AS [c2]
    LEFT JOIN MyTable2 AS [c3] ON [c2].[Id] = [c3].[MyTable2_Id]
    WHERE (([c2].[SpecialId] = [e].[special_id]) OR ([c2].[SpecialId] IS NULL AND [e].[special_id] IS NULL)) AND ((@__Trim_2 LIKE N'') OR (CHARINDEX(@__Trim_2, [c3].[Notes]) > 0)))) AND EXISTS (
    SELECT 1
    FROM MyTable AS [c4]
    LEFT JOIN MyTable2 AS [c5] ON [c4].[Id] = [c5].[MyTable2_Id]
    WHERE (([c4].[SpecialId] = [e].[special_id]) OR ([c4].[SpecialId] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
        SELECT 1
        FROM MyTable3 AS [c6]
        WHERE ([c5].[Id] IS NOT NULL AND ([c5].[Id] = [c6].[MyId3])) AND ([c6].[MyId9] = @__var1)))) AND EXISTS (
    SELECT 1
    FROM MyTable AS [c7]
    LEFT JOIN MyTable2 AS [c8] ON [c7].[Id] = [c8].[MyTable2_Id]
    WHERE (([c7].[SpecialId] = [e].[special_id]) OR ([c7].[SpecialId] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
        SELECT 1
        FROM MyTable3 AS [c9]
        LEFT JOIN [People] AS [u0] ON [c9].[MyId10] = [u0].[Id]
        WHERE ([c8].[Id] IS NOT NULL AND ([c8].[Id] = [c9].[MyId3])) AND ([u0].[special_id2] = @__var2)))) AND EXISTS (
    SELECT 1
    FROM MyTable AS [c10]
    LEFT JOIN MyTable2 AS [c11] ON [c10].[Id] = [c11].[MyTable2_Id]
    WHERE (([c10].[SpecialId] = [e].[special_id]) OR ([c10].[SpecialId] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
        SELECT 1
        FROM MyTable3 AS [c12]
        WHERE ([c11].[Id] IS NOT NULL AND ([c11].[Id] = [c12].[MyId3])) AND ((@__Trim_5 LIKE N'') OR (CHARINDEX(@__Trim_5, [c12].[Notes2]) > 0))))) AND EXISTS (
    SELECT 1
    FROM MyTable AS [c13]
    LEFT JOIN MyTable2 AS [c14] ON [c13].[Id] = [c14].[MyTable2_Id]
    WHERE (([c13].[SpecialId] = [e].[special_id]) OR ([c13].[SpecialId] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
        SELECT 1
        FROM MyTable3 AS [c15]
        WHERE ([c14].[Id] IS NOT NULL AND ([c14].[Id] = [c15].[MyId3])) AND ([c15].[MyDate2] = @__var3)))) AND EXISTS (
    SELECT 1
    FROM MyTable AS [c16]
    WHERE (([c16].[SpecialId] = [e].[special_id]) OR ([c16].[SpecialId] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
        SELECT 1
        FROM MyTable4 AS [c17]
        WHERE ([c16].[Id] = [c17].[MyTable2_Id]) AND ([c17].[MyId7] = @__var4)))) AND EXISTS (
    SELECT 1
    FROM MyTable AS [c18]
    WHERE (([c18].[SpecialId] = [e].[special_id]) OR ([c18].[SpecialId] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
        SELECT 1
        FROM MyTable4 AS [c19]
        WHERE ([c18].[Id] = [c19].[MyTable2_Id]) AND ([c19].[MyId4] = @__var5)))) AND EXISTS (
    SELECT 1
    FROM MyTable AS [c20]
    WHERE (([c20].[SpecialId] = [e].[special_id]) OR ([c20].[SpecialId] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
        SELECT 1
        FROM MyTable4 AS [c21]
        WHERE ([c20].[Id] = [c21].[MyTable2_Id]) AND ([c21].[MyDate] = @__var6)))) AND EXISTS (
    SELECT 1
    FROM MyTable AS [c22]
    WHERE (([c22].[SpecialId] = [e].[special_id]) OR ([c22].[SpecialId] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
        SELECT 1
        FROM MyTable4 AS [c23]
        WHERE ([c22].[Id] = [c23].[MyTable2_Id]) AND ([c23].[Notes3] = @__Trim_10)))) AND EXISTS (
    SELECT 1
    FROM MyTable AS [c24]
    WHERE (([c24].[SpecialId] = [e].[special_id]) OR ([c24].[SpecialId] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
        SELECT 1
        FROM MyTable5 AS [c25]
        WHERE ([c24].[Id] = [c25].[MyTable2_Id]) AND ([c25].[MyId5] = @__var7)))) AND EXISTS (
    SELECT 1
    FROM MyTable AS [c26]
    WHERE (([c26].[SpecialId] = [e].[special_id]) OR ([c26].[SpecialId] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
        SELECT 1
        FROM MyTable5 AS [c27]
        WHERE ([c26].[Id] = [c27].[MyTable2_Id]) AND ((@__Trim_12 LIKE N'') OR (CHARINDEX(@__Trim_12, [c27].[Notes4]) > 0))))) AND EXISTS (
    SELECT 1
    FROM MyTable AS [c28]
    WHERE (([c28].[SpecialId] = [e].[special_id]) OR ([c28].[SpecialId] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
        SELECT 1
        FROM MyTable6 AS [c29]
        LEFT JOIN [People] AS [u1] ON [c29].[MyId6] = [u1].[Id]
        WHERE ([c28].[Id] = [c29].[MyTable2_Id]) AND ([u1].[special_id2] = @__var8)))) AND EXISTS (
    SELECT 1
    FROM MyTable AS [c30]
    WHERE (([c30].[SpecialId] = [e].[special_id]) OR ([c30].[SpecialId] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
        SELECT 1
        FROM MyTable6 AS [c31]
        WHERE ([c30].[Id] = [c31].[MyTable2_Id]) AND ((@__Trim_14 LIKE N'') OR (CHARINDEX(@__Trim_14, [c31].[Notes5]) > 0))))) AND EXISTS (
    SELECT 1
    FROM MyTable AS [c32]
    WHERE (([c32].[SpecialId] = [e].[special_id]) OR ([c32].[SpecialId] IS NULL AND [e].[special_id] IS NULL)) AND EXISTS (
        SELECT 1
        FROM MyTable6 AS [c33]
        WHERE ([c32].[Id] = [c33].[MyTable2_Id]) AND ((@__Trim_15 LIKE N'') OR (CHARINDEX(@__Trim_15, [c33].[Notes6]) > 0))))
ORDER BY [e].[entity_id]
```

**Comment by ajcvickers** [comment] 2021-09-07 17:50
@mrlife If you copy and paste that query directly into SQL Management Studio, with the parameters declared and their correct values, then what does the execution plan look like?

**Comment by ajcvickers** [comment] 2021-09-07 17:52
Likely duplicate of #13617.

**Comment by mrlife** [comment] 2021-09-07 19:27
@ajcvickers It's pretty big. Is there anything specific I can provide?

**Comment by ajcvickers** [comment] 2021-09-11 10:37
@mrlife Would be good to see the whole thing, if that's not too difficult.

Note from triage: closing this as a duplicate of #13617.

**Comment by mrlife** [comment] 2021-09-14 15:35
@ajcvickers I can do that but would need to change names and values - would that pose any issue on your end?

**Closed** 2022-10-16 19:45 UTC
Labels: customer-reported
