### ISSUE TITLE
ValueGeneratedNever Not working?

### ISSUE THREAD

**Issue by chobo2** [dotnet/efcore#12404] opened 2018-06-18 23:46 UTC
I am trying to build a country table in ef core 2.1 and I don't need an identity column set but when I try to turn it off it still gets set.

```C#
public class CountryConfig : IEntityTypeConfiguration<Country>
{
    public void Configure(EntityTypeBuilder<Country> builder)
    {
        builder.HasKey(x => x.Id);
        builder.Property(x => x.Id).ValueGeneratedNever();

        builder.Property(x => x.Name).HasMaxLength(50).IsRequired();
    }
}


```
  but this is what gets generated when I add my migration (Add-Migration Name)

```C#
      migrationBuilder.CreateTable(
                name: "Countries",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(maxLength: 50, nullable: false),
                    Code = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Countries", x => x.Id);
                });
```

**Comment by ajcvickers** [comment] 2018-06-19 00:02
@chobo2 I am not able to reproduce this. My test code an the migration generated are below. Can you post a runnable project/solution or code listing that reproduces the behavior you are seeing?
```C#
public class Country
{
    public int Id { get; set; }

    public string Name { get; set; }
    public string Code { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        new CountryConfig().Configure(modelBuilder.Entity<Country>());
    }
}

public class CountryConfig : IEntityTypeConfiguration<Country>
{
    public void Configure(EntityTypeBuilder<Country> builder)
    {
        builder.HasKey(x => x.Id);
        builder.Property(x => x.Id).ValueGeneratedNever();

        builder.Property(x => x.Name).HasMaxLength(50).IsRequired();
    }
}
```
```C#
public partial class Name : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Country",
            columns: table => new
            {
                Id = table.Column<int>(nullable: false),
                Name = table.Column<string>(maxLength: 50, nullable: false),
                Code = table.Column<string>(nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Country", x => x.Id);
            });
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "Country");
    }
}
```

**Comment by chobo2** [comment] 2018-06-19 02:34
@ajcvickers 

hmm, I created a new project and I get what you get. So there must be something wrong with my project but I have no clue what it could be.

**Comment by ajcvickers** [comment] 2018-06-25 17:50
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by jasonrmh** [comment] 2020-02-22 13:31
I have been having this issue.
An old thread, but this may answer why @chobo2 original datbase has the id column as identity...

I this the problem was because I had already added my migration BEFORE I updated the migrationBuilder with .ValueGeneratedNever();

```
public class CountryConfig : IEntityTypeConfiguration<Country>
{
    public void Configure(EntityTypeBuilder<Country> builder)
    {
        builder.HasKey(x => x.Id);
        builder.Property(x => x.Id).ValueGeneratedNever(); // <<< This line was added AFTER migration had already been created.

        builder.Property(x => x.Name).HasMaxLength(50).IsRequired();
    }
}
```

I deleted my migrations folder fro solution ( as its the initial migration anyway), then added it again:
```
Add-Migration Initial
Update-Database
```
Its now working as expected, with my Id column no longer being configured as an IDENTITY column.

Hope this helps!

**Closed** 2022-10-16 12:32 UTC
Labels: closed-could-not-reproduce, customer-reported
