### ISSUE TITLE
EntityTypeBuilder.ToFunction vs ModelBuilder.HasDbFunction inconsistencies in inheritance mapping?

### ISSUE THREAD

**Issue by Schlurcher** [dotnet/efcore#33408] opened 2024-03-26 13:39 UTC
If I define a a TVF on the context it is usable and handles inheritance and materialization correctly.

```
modelBuilder.HasDbFunction(typeof(AdmsContext).GetMethod(nameof(UserFileSystem))!)
	.HasName("fn_filesystem")
	.HasSchema("dbo");
```

```
var data = await Context.UserFileSystem()
	.Take(100)
	.ToListAsync();
```

![grafik](https://github.com/dotnet/efcore/assets/973681/656ec012-470a-4bac-9415-fa6937111a70)

If I try to map the function in an EntityTypeConfiguration it immediatly throws and complains that derived types cannot be mapped to functions. Am I missing something in my EntityTypeConfiguration? Mapping to derived types clearly works in the first scenario, why would it be different when directly mapping an EntityType / DbSet.

```
System.InvalidOperationException
The entity type 'FileSystemArchiveVirtual' is mapped to the 'DbFunction' named 'fn_filesystem', but is derived from 'FileSystemObject'. Derived entity types cannot be mapped to a function.
```

```
public class FileSystemObjectConfiguration : IEntityTypeConfiguration<FileSystemObject>
{
	public void Configure(EntityTypeBuilder<FileSystemObject> builder)
	{
		builder.ToFunction("fn_filesystem");

		builder.HasKey(x => x.Path);

		builder.Property(x => x.ObjectId);
		
		builder.HasDiscriminator(x => x.ObjectTypeId)
			.HasValue<FileSystemCompany>(FileSystemObjectType.Company)
			.HasValue<FileSystemArchiveVirtual>(FileSystemObjectType.ArchiveVirtual)
			.HasValue<FileSystemDossier>(FileSystemObjectType.Dossier)
			.HasValue<FileSystemFile>(FileSystemObjectType.File);
		
		builder.HasOne<FileSystemObject>(x => x.Parent)
			.WithMany(x => x.Children)
			.HasForeignKey(x => x.ParentPath);

		builder.Property(x => x.ParentPath).ValueGeneratedOnUpdateSometimes();
	}
}
```

**Comment by roji** [comment] 2024-03-26 14:40
```c#
modelBuilder.HasDbFunction(typeof(AdmsContext).GetMethod(nameof(UserFileSystem))!)
	.HasName("fn_filesystem")
	.HasSchema("dbo");

var data = await Context.UserFileSystem()
	.Take(100)
	.ToListAsync();
```

Here you simply seem to be invoking the UserFileSystem() function, as a plain .NET function; whatever its .NET implementation is will get executed; you should be able to remove HasDbFunction: that's about allowing the function in question to be used **inside** LINQ queries. In other words, your TVF function here really being "mapped" at all (or at least, you're not using it as such).

**Comment by AndriySvyryd** [comment] 2024-04-26 20:42
Duplicate of #19970

**Closed by AndriySvyryd** 2024-04-26 20:42 UTC
Labels: customer-reported, area-model-building
