### ISSUE TITLE
Entity Framework concurrent savechanges deadlock

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#15006] opened 2019-03-13 08:52 UTC
I am writing a quite simple Multiuser WPF application where each user can modify / delete his own data. Means each user can see all the data of other users but is not allowed to modify or delete it. The whole application performs well until 2 or more clients hit the savechanges method at the same time, then i often run into a Database Deadlock.

I have no idea why it comes to that deadlock, as it is not possible that the same data is modified or deleted at the same time by different users.

I wrote a short program that demonstates the behaviour. The delete method at the end simulates two users deleting their own data at the same time.

Here is my DbContext and Datamodel:

```
public class Context : DbContext
{
    public DbSet<City> dbsCities          { get; set; }
    public DbSet<House> dbsHouses   { get; set; }
    public DbSet<Person> dbsPersons  { get; set; }

    public Context() : base(@"Server=.\SQLExpress;Database=test;Trusted_Connection=Yes;Connection Timeout=5")
    {
        Configuration.AutoDetectChangesEnabled = true;
        Configuration.LazyLoadingEnabled = false;
        Configuration.ProxyCreationEnabled = false;
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        modelBuilder.Entity<City>().HasMany(c => c.Houses).WithRequired(c => c.City).WillCascadeOnDelete(true);
        modelBuilder.Entity<House>().HasMany(p => p.Residents).WithRequired(p => p.House).WillCascadeOnDelete(true);
    }
}

public class City
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public virtual ICollection<House> Houses { get; set; }

    public City()
    {
        Id = Guid.NewGuid();
        Houses = new List<House>();
    }
}

public class House
{
    public Guid Id                                    { get; set; }
    public int Number                             { get; set; }
    public string Code                             { get; set; }
    public virtual City City                       { get; set; }
    public virtual ICollection<Person> Residents    { get; set; }

    public House()
    {
        Id = Guid.NewGuid();
        Residents = new List<Person>();
    }
}


public class Person
{
    public Guid Id          { get; set; }
    public string Firstname { get; set; }
    public string Lastname  { get; set; }

    public virtual House House { get; set; }

    public Person()
    {
        Id = Guid.NewGuid();
    }
}

```
And here the code to generate testdata:

```
using (Context ctx = new Context())
        {
            List<City> cities = new List<City>() { new City() { Name = "New York" } };
            for (int h = 1; h <= 50; h++)
            {
                string code = "A";
                if (h % 2 == 0)
                    code = "B";
                House house = new House() {Number = h, Code = code };
                cities[0].Houses.Add(house);
                for (int i = 0; i <= 100; i++)
                    house.Residents.Add(new Person() { Firstname = "A", Lastname = "B" });
            }

            ctx.dbsCities.AddRange(cities);
            ctx.SaveChanges();
        }
```
Finally the Method that causes the deadlock:

```
private void Delete(object sender, RoutedEventArgs e)
    {
        string[] to = new string[] {"A", "B"};
        Parallel.ForEach(to, code =>
        {
            DeleteHouses(code);
        });
    }
    private void DeleteHouses(string code)
    {
        using (var ctx = new Context())
        {
            ctx.Database.Log += Console.WriteLine;
            var todel = ctx.dbsHouses.Where(d=>d.Code == code);
            if (todel != null)
            {
                ctx.dbsHouses.RemoveRange(todel);
                ctx.SaveChanges();
            }
        }
    }
```

if i update the DeleteHouses Method and use plain T-SQL like this, the queries are executed without deadlock.

```
using (var ctx = new Context())
            {
                ctx.Database.ExecuteSqlCommand($"delete from houses where [code] = '{code}'");
            }
```

Attached you can finde a solution that demonstrates my problem.

[DisconnectedEntities.zip](https://github.com/aspnet/EntityFrameworkCore/files/2960532/DisconnectedEntities.zip)

**Comment by ajcvickers** [comment] 2019-03-13 19:13
@blent This looks like a duplicate of the issue that [was already filed for EF6](https://github.com/aspnet/EntityFramework6/issues/723). Since the code above is EF6 code, I'm closing this as external.

**Comment by blenet** [comment] 2019-03-14 10:06
@ajcvickers i also posted it here, as i did not get an answer in the other forum and thought that it maybe could also be answered here.

**Closed** 2022-10-16 13:55 UTC
Labels: closed-external, customer-reported
