### ISSUE TITLE
[Cosmos]  Related items get partially loaded

### ISSUE THREAD

**Issue by bobbyangers** [dotnet/efcore#23777] opened 2020-12-29 05:28 UTC
EF Core version:
Database provider:  Microsoft.EntityFrameworkCore.Cosmos
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.3

So I created a brand new CosmoDB and container, using the local Emulator

I add 2 **masterModel** which have each 3 related **detailModel**

```C#
public class MasterModel
{
  public Guid Id { get; set; }
  public string Name { get; set; }
  public ICollection<DetailModel> Items { get; set; }
}
public class DetailModel
{
  public Guid Id { get; set; }
  public string Name { get; set; }
  public MasterModel Parent { get; set; }
}
```
## When I run this....

```C#
await using (var db1 = new VDbPocContext(options))
{
	var list1 = await db1.Details.AsQueryable().Take(5).ToListAsync();
	ShowResult(list1);

	var key1 = GuidHelper.Get(1);
	var main1 = await db1.Masters.FindAsync(key1);
	ShowResult(main1);

	var key2 = GuidHelper.Get(2);
	var main2 = await db1.Masters.FindAsync(key2);
	ShowResult(main2);
}
```

## The second master (main2) is missing an item.
```
{
  "id": "00000000-0000-0000-0000-000000000001",
  "name": "Name1f01a62c-9c59-4fe4-8b70-1122b30b43e6",
  "items": [
    {
      "id": "00000000-0000-0000-0000-000000000010",
      "name": "Nameb57dcb50-4c7b-4868-a4f9-bafe5a1ce8f1",
      "parentId": "00000000-0000-0000-0000-000000000001"
    },
    {
      "id": "00000000-0000-0000-0000-000000000011",
      "name": "Name05c54676-7771-42ca-bf2c-a478a34ecf84",
      "parentId": "00000000-0000-0000-0000-000000000001"
    },
    {
      "id": "00000000-0000-0000-0000-000000000012",
      "name": "Namea10126c9-a6cf-4ba9-a728-331a6986e50d",
      "parentId": "00000000-0000-0000-0000-000000000001"
    }
  ]
}
--------------------------------------------------
{
  "id": "00000000-0000-0000-0000-000000000002",
  "name": "Name433bb9aa-64f3-4358-8884-4c988f95c761",
  "items": [
    {
      "id": "00000000-0000-0000-0000-000000000020",
      "name": "Name8d55313d-7e76-47d2-99e6-6c393626f0c9",
      "parentId": "00000000-0000-0000-0000-000000000002"
    },
    {
      "id": "00000000-0000-0000-0000-000000000021",
      "name": "Name0efcb704-64ba-4965-a256-796bf8671002",
      "parentId": "00000000-0000-0000-0000-000000000002"
    }
  ]
}
```

**Comment by ajcvickers** [comment] 2021-01-05 19:55
@bobbyangers Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2021-01-15 16:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:16 UTC
Labels: closed-could-not-reproduce, customer-reported
