### ISSUE TITLE
Most of Expression ignored when generating SQL

### ISSUE THREAD

**Issue by joshmouch** [dotnet/efcore#8071] opened 2017-04-04 21:00 UTC
I am using LinqKit to generate an Expression which I then use with EF Core 1.1.1 to get some entities.  However, most of the expression is being ignored to create the SQL which hits the database.

For example:

```
List<Guid> taskTypeIds = ...;
var filter1 = Linq.Expr<Task, bool>(t =>
				   t.DeleteFlag == false
				   && t.TaskTypeId != null
				   && taskTypeIds.Contains(t.TaskTypeId.Value)
				   && t.TaskId != this.Task.TaskId);

var filter2 = Linq.Expr<Task, bool>(t => t.FkId == this.Task.FkId);

var filter = filter1.And(filter2);

var results = dataContext.Task.Where(filter).ToList();
```

The Expression looks like this:
```

{t => (((((t.DeleteFlag == False) AndAlso (t.TaskTypeId != null)) AndAlso value(Class1+<>c__DisplayClass2_0).taskTypeIds.Contains(t.TaskTypeId.Value)) AndAlso (t.TaskId != value(Class2).Task.TaskId)) AndAlso Invoke(t => (t.FkId== value(Class2).Task.FkId), t))}`

```

However, the SQL looks like this:
```

exec sp_executesql N'SELECT ...
FROM [Task] AS [t]
WHERE [t].[FkID] = @__Task_FkId_2',N'@__Task_FkId_2 uniqueidentifier',@__Task_FkId_2='48EEDD83-EB93-4A12-8889-DADEFF5AF7B6'

```

You can see that only the portion of the Expression after the word "Invoke" is being considered when building the SQL.

If I continue on to add additional logic to the filter using LinqKit's "And" extension, only the last Expression added will be used in the SQL.  For example:

```
filter = filter.And(filter3)
```

The Expression will have an additional "AndAlso Invoke(t => ....)" and the SQL will use only that last bit of the expression.

**Comment by joshmouch** [comment] 2017-04-04 21:30
So the odd thing is, if I comment out the
`&& taskTypeIds.Contains(t.TaskTypeId.Value)`
from the first expression, everything works as expected.

Still trying different things....

**Comment by joshmouch** [comment] 2017-04-04 21:43
It turns out the ".Value" is triggering the bug.

If I add:

```
List<Guid?> convertedTaskTypeIds = taskTypeIds.Cast<Guid?>.ToList();
```

Then change
```
&& taskTypeIds.Contains(t.TaskTypeId.Value)
```
to
```
&& convertedTaskTypeIds.Contains(t.TaskTypeId)
```

Then things work as expected.

**Comment by maumar** [comment] 2017-04-04 22:00
dupe of https://github.com/aspnet/EntityFramework/issues/4247

**Comment by joshmouch** [comment] 2017-04-04 22:02
@maumar I see that this is a dupe of #4247, but I think there might be a bigger issue here.  I should be getting some sort of exception thrown instead of just silently having my SQL generated incorrectly.  It's acting like any part of the Expression it can't evaluate just gets thrown out silently.

**Comment by maumar** [comment] 2017-04-04 22:04
@joshmouch I assumed the untranslated parts would be executed on the client. Is this not the case?

**Comment by maumar** [comment] 2017-04-04 22:06
generally what *should* be happening for Where clauses is that the part that we can translate to SQL is executed in form of SQL statement, and the part that we cant translate is then filtered out in memory. You should still get the correct results, and the query plan should reflect additional client-side _Where(...) method.

**Comment by joshmouch** [comment] 2017-04-04 22:06
@maumar That may be the case.  I have the flag disabled to throw exceptions when there is client-side evaluation because it was hitting too many false positives.

**Comment by maumar** [comment] 2017-04-04 22:08
@joshmouch I see, if after enabling the flag you don't get a warning then there is definitely something bad going on (please reopen the bug if that's the case). Otherwise it's just an issue of not translating Value to server.

**Closed** 2022-10-16 10:59 UTC
