### ISSUE TITLE
Does EF support database alias?

### ISSUE THREAD

**Issue by cloudscore** [dotnet/efcore#18893] opened 2019-11-13 22:59 UTC
SQLite supports attaching additional database file to existing connection and then we can join/union 2 tables in 2 databases. In our case we have 2 accounts which has separate database files. The table schema in the 2 db are same. When we union the same table in 2 db files and run some filters we need to specify database alias name in the query string. I didn't find EF API to support database alias. Is this something doable or in the road map?

FYI the doc for database alias: https://www.tutorialspoint.com/sqlite/sqlite_attach_database.htm

**Comment by ajcvickers** [comment] 2019-11-18 19:14
@bricelam I can't find the dupe for this. Any ideas?

**Comment by bricelam** [comment] 2019-11-18 19:20
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/4019

**Comment by bricelam** [comment] 2019-11-18 20:04
As a workaround, you can specify the database-qualified table name using FromSql()

**Closed** 2022-10-16 14:55 UTC
Labels: closed-duplicate, customer-reported
