### ISSUE TITLE
AutoInclude property of owned entities

### ISSUE THREAD

**Issue by JonaBrackenwood** [dotnet/efcore#34292] opened 2024-07-26 09:21 UTC
I want to be able to AutoInclude a property of an owned entity type.

Currently I have three tables that all have an owned Address.
```C#
builder.Entity<Customers>().OwnsOne(x => x.Address).HasOne(x => x.Country).WithMany();
builder.Entity<Organizations>().OwnsOne(x => x.Address).HasOne(x => x.Country).WithMany();
builder.Entity<Supplier>().OwnsOne(x => x.Address).HasOne(x => x.Country).WithMany();
```
This Address includes a Country, which I must include everywehere that the address is used.

I want to be able to include this Country automatically, so these includes everywhere:
```C#
context.Customers.Include(x => x.Address.Country)
context.Organizations.Include(x => x.Address.Country)
context.Suppliers.Include(x => x.Address.Country)
```

Can be replaced by one global AutoInclude:
```C#
modelBuilder.Entity<Address>().Navigation(x => x.Country).AutoInclude();
```

Currently this just produces the error `The entity type 'Address' cannot be configured as non-owned because it has already been configured as a owned. If you want to override previous configuration first remove the entity type from the model by calling 'Ignore'.`

**Comment by JonaBrackenwood** [comment] 2024-07-26 17:37
> > modelBuilder.Entity()
> 
> This configures Address as its own, separate non-owned entity type (i.e. with its own table), which conflicts with the other cnofiguration of it as owned - that's why you're getting the error.
> 
> Have you considered simply configuring Address itself as Owned where its used, as opposed to using AutoInclude?

It's already configured as owned and that's why I'm getting the exception, and that is all working correctly. I just want to AutoInclude a property on the owned type which you can't do at the moment.

**Comment by roji** [comment] 2024-07-26 20:26
Sorry, I meant to ask why not configure Country as owned (as opposed to auto-include)?

**Comment by JonaBrackenwood** [comment] 2024-07-26 20:56
In this case Country is a list of possible/configured countries and also has relations to other entity types, so it can't be only owned by address. Wouldn't that just make it functionally the same as a string property named Country?

**Comment by roji** [comment] 2024-07-26 21:28
Understood - no, if you want Country to be in its own table with addresses referencing it by foreign key, and joins every time you load it, this is indeed the right modeling; the alternative would be to indeed just have it as a string column with possibly a check constraint, this can be modeled either as a simple property or as an owned entity/complex type.

In any case, I don't think there's currently a way to configure all navigations pointing to an entity type to be auto-loading (which is your original request) - @AndriySvyryd @ajcvickers does this ring any bells?

**Comment by AndriySvyryd** [comment] 2024-08-08 18:54
This is essentially a duplicate of https://github.com/dotnet/efcore/issues/2953

**Closed** 2024-08-08 18:55 UTC
Labels: customer-reported
