### ISSUE TITLE
Error on add Entity on database

### ISSUE THREAD

**Issue by aguirmrc** [dotnet/efcore#5582] opened 2016-05-31 12:41 UTC
### Steps to reproduce

When we insert an entity that has a property that is a class of one to one and the parent class is the inheritance of an inheritance.

Example:
- Class Client inherits Individual who inherits Person 
- Person have one Address (one-to-one with Person)
- The registering Person and all Individual usually occurs , but to register the Client, the exception occurs
### The issue

Error on save entity on database

Exception : An error occurred while updating the entries. See the inner exception for details.
Inner Exception: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Address_Person_IdPerson". The conflict occurred in database "Xxxxxxx", table "dbo.Person", column 'IdPerson'.
The statement has been terminated.

Obs. ModelState IsValid and all propertys fill.
Sorry my bad english.

Stack trace:    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)

```

### Further technical details
EF Core version: 1.0.0-rc2-final
Operating system: 
Visual Studio version: 2015 Update 2
```

**Comment by rowanmiller** [comment] 2016-06-06 00:24
@aguirmrc we haven't been able to piece this one together from the details provided. Could you share a complete code listing that we can run to see the issue? Alternatively you can share a solution/project if that is easier.

**Comment by rowanmiller** [comment] 2016-06-13 20:23
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 09:43 UTC
Labels: closed-could-not-reproduce, customer-reported
