### ISSUE TITLE
Migrations didn't create ModelSnapshot  

### ISSUE THREAD

**Issue by xsoheilalizadeh** [dotnet/efcore#30031] opened 2023-01-11 14:57 UTC
## Ask a question

I already have three migrations, each for a specific dbcontext, but none of them have the ModelSnapshot file, I noticed this when I was trying to create a new migration for one of my dbcontext and the new migration is trying to recreate all the tables which means it's not aware of the other existing migrations. Those three migrations are already applied to the DB in production. I'd like to find out why it didn't create the snapshot file in the first place and how I can solve this.

### Configuration

```c#
void ConfigureDbContext(DbContextOptionsBuilder options)
{
    options.UseNpgsql(builder.Configuration["Services:PostgresSQL:ConnectionString"],
        o =>
        {
            o.MigrationsAssembly(typeof(DbMigrator).Assembly.FullName);
        });
}
```

![image](https://user-images.githubusercontent.com/22220356/211835137-fcb51854-d380-419a-850b-6ae3753e6442.png)

### Verbose output

```
C:\Stuff\AllTogetherNow\FiveOh>dotnet ef dbcontext list --verbose
Using assembly 'x.Identity'.
Using startup assembly 'x.Identity'.
Using application base 'C:\Users\x\code\x\src\x.Identity\bin\Debug\net7.0'.
Using working directory 'C:\Users\x\code\x\src\x.Identity'.
Using root namespace 'x.Identity'.
Using project directory 'C:\Users\x\code\x\src\Buzz.Identity\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'x.Identity'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Found DbContext 'ApplicationDbContext'.
Found DbContext 'ConfigurationDbContext'.
Found DbContext 'PersistedGrantDbContext'.
Finding DbContext classes in the project...
x.Identity.Data.ApplicationDbContext
x.Identity.Data.ConfigurationDbContext
x.Identity.Data.PersistedGrantDbContext
```

### Version information

```csproj
    <ItemGroup>
        <PackageReference Include="Duende.IdentityServer" Version="6.2.0" />
        <PackageReference Include="Duende.IdentityServer.AspNetIdentity" Version="6.2.0" />
        <PackageReference Include="Duende.IdentityServer.EntityFramework" Version="6.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="7.0.0" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>
```

Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 7.0

**Comment by ajcvickers** [comment] 2023-01-11 20:45
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by xsoheilalizadeh** [comment] 2023-01-12 11:17
I tried to make a sample project to reproduce it with the same code, but surprisingly it created the snapshot file in the fresh project. What are the possibilities for a snapshot not being created? Is there a way that I could debug this?

**Comment by ajcvickers** [comment] 2023-01-24 17:29
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-01-24 17:29 UTC
Labels: customer-reported

**Comment by timaiv** [comment] 2023-05-04 09:30
Hi!
@ajcvickers 
This happened to me twice when I renamed the Migrations folder to MigrationsOld and excluded MigrationsOld from the project.
In this case, migration (.cs and designer.cs) are created, but without a snapshot.

And each time I spent a lot of time looking for the problem.
