### ISSUE TITLE
How populate a SQL Server table from Entity Framework C# - navigation property

### ISSUE THREAD

**Issue by rsslldblsnglll** [dotnet/efcore#15246] opened 2019-04-03 14:15 UTC
Hi,
I have a DB in SQL server which contain some table who are used to model the n - n relationship. 
For example:
The relation between A and B is n - n
in my db I have A, B and AB which contains (idA,idB) as primary key. 

in c# I used the Entity Framework so I have the entities A and B but AB is only a navigation property. So, how I can populate the table AB knowing that it is not an entity but a navigation property? 

var db = newmyDBEntities();
db.A.Add(dbA) 
db.B.Add(dbB);

there is something like db.AB.Add(...)?

**Comment by ajcvickers** [comment] 2019-04-03 15:47
@rsslldblsnglll There's not much to go on here--for example, can you explain this in a bit more detail: "AB is only a navigation property", Typically in EF Core, a many-to-many relationship involves three entity types _that act like any other entity types_.

In general, for us to be able to help in an effective manner, please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-04-11 15:24
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:59 UTC
Labels: closed-could-not-reproduce, customer-reported
