### ISSUE TITLE
Sqlite beta 6 query throwed an InvalidOperationException

### ISSUE THREAD

**Issue by yukozh** [dotnet/efcore#2924] opened 2015-08-26 10:23 UTC
```
        ViewBag.Catalogs = DB.Posts
            .Include(x => x.Catalog)
            .Where(x => !string.IsNullOrEmpty(x.CatalogId) && !x.IsPage)
            .OrderByDescending(x => x.Catalog.PRI)
            .GroupBy(x => new { Id = x.CatalogId, Title = x.Catalog.Title })
            .Select(x => new
            {
                Id = x.Key.Id,
                Title = x.Key.Title,
                Count = x.Count()
            })
            .ToList();

at System.Linq.Enumerable.Single<TSource>(IEnumerable<TSource> source) 
at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<>c__DisplayClass61_0<TResult>.<BindMemberExpression>b__0(IEnumerable<IPropertyBase> ps, IQuerySource qs) 
at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpressionCore<TResult>(MemberExpression memberExpression, IQuerySource querySource, Func<IEnumerable<IPropertyBase>, IQuerySource, TResult> memberBinder)
at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpression<TResult>(MemberExpression memberExpression, IQuerySource querySource, Func<IProperty, IQuerySource, TResult> memberBinder)
at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpression(MemberExpression memberExpression, Action<IProperty, IQuerySource> memberBinder) 
at Microsoft.Data.Entity.Query.ExpressionVisitors.RequiresMaterializationExpressionVisitor.VisitMember(MemberExpression memberExpression) 
at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor) 
at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node) 
at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression) 
at Remotion.Linq.Clauses.Ordering.TransformExpressions(Func<Expression, Expression> transformation) 
at Remotion.Linq.Clauses.OrderByClause.TransformExpressions(Func<Expression, Expression> transformation) 
at Remotion.Linq.QueryModel.TransformExpressions(Func<Expression, Expression> transformation) 
at Microsoft.Data.Entity.Query.ExpressionVisitors.RequiresMaterializationExpressionVisitor.VisitSubQuery(SubQueryExpression subQueryExpression) 
at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor) 
at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node) 
at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression) 
at Remotion.Linq.Clauses.FromClauseBase.TransformExpressions(Func<Expression, Expression> transformation) 
at Remotion.Linq.QueryModel.TransformExpressions(Func<Expression, Expression> transformation) 
at Microsoft.Data.Entity.Query.ExpressionVisitors.RequiresMaterializationExpressionVisitor.FindQuerySourcesRequiringMaterialization(QueryModel queryModel) 
at Microsoft.Data.Entity.Query.QueryCompilationContext.FindQuerySourcesRequiringMaterialization(EntityQueryModelVisitor queryModelVisitor, QueryModel queryModel) 
at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor<TResult>(QueryModel queryModel) 
at Microsoft.Data.Entity.Storage.RelationalDatabase.CompileQuery<TResult>(QueryModel queryModel) 
--- exception rethrown --- 
at Microsoft.Data.Entity.Query.CompiledQueryCache.CompileQuery(IDatabase database, MethodInfo compileMethodInfo, Type resultItemType, QueryModel queryModel) 
at Microsoft.Data.Entity.Query.CompiledQueryCache.<>c__7<TResult>.<Execute>b__7_0(Expression q, IDatabase ds) 
at Microsoft.Data.Entity.Query.CompiledQueryCache.GetOrAdd(Expression query, QueryContext queryContext, IDatabase database, Boolean isAsync, Func<Expression, IDatabase, CompiledQueryCache.CompiledQuery> compiler)
at Microsoft.Data.Entity.Query.CompiledQueryCache.Execute<TResult>(Expression query, IDatabase database, QueryContext queryContext) 
at Microsoft.Data.Entity.Query.EntityQueryProvider.Execute<TResult>(Expression expression) 
at Remotion.Linq.QueryableBase<T>.GetEnumerator() 
at System.Collections.Generic.List<T>..ctor(IEnumerable<T> collection) 
at System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source) 
at CodeComb.vNext.Sample.YuukoBlog.Controllers.BaseController.Prepare() in Y:\项目\CodeComb.vNext\src\CodeComb.vNext.Sample.YuukoBlog\Controllers\BaseController.cs:line 34 
at Microsoft.AspNet.Mvc.BaseController.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next) in Y:\项目\CodeComb.vNext\src\CodeComb.vNext\Base\BaseController.cs:line 58
at Microsoft.AspNet.Mvc.Filters.ControllerActionFilter.<OnActionExecutionAsync>d__4.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeActionFilterAsync>d__49.MoveNext() 
--- exception rethrown --- 
at Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeAsync>d__40.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Mvc.MvcRouteHandler.<InvokeActionAsync>d__4.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Mvc.MvcRouteHandler.<RouteAsync>d__3.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__25.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Session.SessionMiddleware.<Invoke>d__8.MoveNext() 
--- exception rethrown --- 
at Microsoft.AspNet.Session.SessionMiddleware.<Invoke>d__8.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass29_0.<<Start>b__0>d.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.<ProcessRequestAsyncImpl>d__10.MoveNext() 
--- exception rethrown --- 
at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.<ProcessRequestAsyncImpl>d__10.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Loader.IIS.HttpApplicationBase.<InvokeProcessRequestAsyncImpl>d__9.MoveNext()
```

**Comment by ErikEJ** [comment] 2015-08-26 10:27
I think you cannot do this:

    Title = x.Key.**Title**,

Until beta 7 (or maybe even beta 8)

**Comment by Kagamine** [comment] 2015-08-26 10:36
Can I do that in SqlServer beta 6?

**Comment by Kagamine** [comment] 2015-08-26 10:41
there is the same problem in this:

            ViewBag.Calendars = DB.Posts
                .Where(x => !string.IsNullOrEmpty(x.CatalogId) && !x.IsPage)
                .OrderByDescending(x => x.Time)
                .GroupBy(x => new { Year = x.Time.Year, Month = x.Time.Month })
                .Select(x => new {
                    Year = x.Key.Year,
                    Month = x.Key.Month,
                    Count = x.Count()
                })
                .ToList();

**Comment by Kagamine** [comment] 2015-08-27 00:17
Oh, it seems that I cannot use string.IsNullOrEmpty() during querying.

**Comment by rowanmiller** [comment] 2015-08-28 18:42
Dupe of #325 - navigation property translation is being implemented now

**Closed** 2022-10-16 09:06 UTC
