### ISSUE TITLE
Invoke in expression tree throws NotImplementedException

### ISSUE THREAD

**Issue by jacob-robertson** [dotnet/efcore#5445] opened 2016-05-20 14:24 UTC
In my use case, I'm building the filters that are passed into the `IQueryable.Where()` call dynamically.  Since I've updated to the RC2 release, any expression tree passed in causes a `NotImplementedException` to be thrown.  According to the stack trace, the culprit is here:

```
at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
```

I've attached a sample that should demonstrate the issue.  

```
Expression<Func<Guitar, bool>> expression = g => g.Model.Id == modelId;
var param = Expression.Parameter(typeof(Guitar), "g");

Guid modelId = context.GuitarModels.FirstOrDefault().Id;

var guitars = context.Guitars
    //This works
    .Where(expression);
    //This does not   
    .Where(Expression.Lambda<Func<Guitar, bool>>(Expression.Invoke(expression, param), param));
```

[EFTester.zip](https://github.com/aspnet/EntityFramework/files/274759/EFTester.zip)

**Comment by maumar** [comment] 2016-05-20 22:33
duplicate of https://github.com/aspnet/EntityFramework/issues/4705

**Closed** 2022-10-16 09:41 UTC
