### ISSUE TITLE
Navigation properties without foreign keys

### ISSUE THREAD

**Issue by p3rh5g** [dotnet/efcore#20744] opened 2020-04-24 15:09 UTC
I want to be able to use `Include` without a database relation. This is possible using LINQ `Join`.

Right now the best example I have is where I want to be able to get log items when I get something that has been logged, but my log entity doesn't have relations to every other entity.

If I can add a navigation property wihtout a foreign key it would be clear to everyone that there is a relationship between the entities and it would be easier to work with includes than joins because how they are "joined" has already been set up in the DbContext configuration.

Example configuration for `IEntityTypeConfiguration<User>`:
```
builder
    .HasMany(user => user.Logs)
    .HasRelationWithoutForeignKey(user => new { Type = "User", Id = user.Id },
                                  log => new { Type = log.Entity, Id = log.EntityId });
```

Used in code just like navigations properties today:

```
_dbContext.Users
          .Include(u => u.Logs)
          .Where(u => u.Id == userId)
          .FirstOrDefault();
```

**Comment by ajcvickers** [comment] 2020-04-24 16:45
Duplicate of #15854

**Closed** 2022-10-16 18:21 UTC
Labels: customer-reported
