### ISSUE TITLE
Strange exception when aiming for Lazy loading without proxies

### ISSUE THREAD

**Issue by henrikdahl8240** [dotnet/efcore#24453] opened 2021-03-19 17:19 UTC
I have tried to follow the instructions at https://docs.microsoft.com/en-us/ef/core/querying/related-data/lazy

I however use inheritance, which I have done in the "usual" way.

My code:
```
internal enum BikeShop__DiscriminatorKind
{
    BikeShop_AAA = 0,
    BikeShop_BBB = 1
}

public abstract class BikeShop
{
    public BikeShop()
    {
    }

    protected BikeShop(ILazyLoader lazyLoader)
    {
        LazyLoader = lazyLoader;
    }

    protected ILazyLoader LazyLoader { get; set; }

    public Guid ID { get; set; }
    [Timestamp]
    public byte[] Version { get; set; }
    [Display(Name = "Display Priority")]
    public int DisplayPriority { get; set; }

    [Required]
    public string Name { get; set; }
    public string Description { get; set; }

    public virtual ICollection<BikeShop_BBB> ShopChildren { get; set; }

    public virtual ICollection<World> Contents { get; set; }
}

public class BikeShop_AAA : BikeShop
{
    internal static BikeShop__DiscriminatorKind DiscriminatorValue => BikeShop__DiscriminatorKind.BikeShop_AAA;

    public BikeShop_AAA()
    {
    }

    private BikeShop_AAA(ILazyLoader lazyLoader) : base(lazyLoader)
    {
    }
}

public class BikeShop_BBB : BikeShop
{
    internal static BikeShop__DiscriminatorKind DiscriminatorValue => BikeShop__DiscriminatorKind.BikeShop_BBB;

    public BikeShop_BBB()
    {
    }

    private BikeShop_BBB(ILazyLoader lazyLoader) : base(lazyLoader)
    {
    }

    public Guid ShopParentID { get; set; }
    public virtual BikeShop ShopParent { get; set; }
}

```
To my surprise I get this exception:
```
PM> Add-Migration ...
Build started...
Build succeeded.
System.InvalidOperationException: The service property 'LazyLoader' of type 'ILazyLoader' cannot be added to the entity type 'BikeShop_BBB' because there is another property of the same type. Ignore one of the properties using the [NotMapped] attribute or 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ServicePropertyDiscoveryConvention.ProcessModelFinalizing(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalizing(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalizing(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The service property 'LazyLoader' of type 'ILazyLoader' cannot be added to the entity type 'BikeShop_BBB' because there is another property of the same type. Ignore one of the properties using the [NotMapped] attribute or 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
PM> 

```

Have I done something wrong or is there an error in Entity Framework Core 5.0.4?

**Comment by smitpatel** [comment] 2021-03-19 17:37
Possible duplicate of #23968

**Comment by henrikdahl8240** [comment] 2021-03-19 17:46
I suppose that Lazy loading without proxies should work with inheritance because otherwise it's obviously quite useless. Do you have an example of how to do it when entity types use intehitance?

**Comment by henrikdahl8240** [comment] 2021-03-20 06:59
If it actually doesn't work, will it then be fixed in .NET 5.0.5?

**Comment by ajcvickers** [comment] 2021-03-20 23:05
@henrikdahl8240 I investigated #23968, and it turns out this is only a problem with _publicly visible_ service properties. Making the lazy loader property private should be a reasonable workaround. If you need a publicly visible property, then you should be able to create a `[NotMapped]` property for that.

**Comment by henrikdahl8240** [comment] 2021-03-21 08:38
@ajcvickers But the LazyLoader is not public, it's protected so it can also be used inside the subclasses. How should it be done in a case like this, which is just like the usual case with Mammal, Dog and Cat. Should the LazyLoader property have visibility protected and be marked with NotMapped or should each class in the inheritance hierarchy have its own private LazyLoader property or is it up to me?

**Closed** 2022-10-16 19:29 UTC
Labels: customer-reported
