### ISSUE TITLE
Add-Migration error if assembly is named "EF"

### ISSUE THREAD

**Issue by tibitoth** [dotnet/efcore#11397] opened 2018-03-23 16:43 UTC
If I name my (Console) project/assembly "EF", Add-Migration command is not working and results an error with the following message:
`No DbContext was found in assembly 'ef'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.`

Of course my context class is neither abstract nor generic.

### Steps to reproduce
1. Create a .NET Core 2.0 project with name `EF`
2. Add the following NuGet packages:

```XML
<ItemGroup>
  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.2" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.2" />
</ItemGroup>
```
3. Add the following classes to the project

```C#
using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.EntityFrameworkCore;

namespace EF
{
    public class NorthwindContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);

            optionsBuilder.UseSqlServer(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=i6rxee;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");
        }

        public DbSet<Product> Products { get; set; }
    }
}
```

```C#
namespace EF
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
```

```C#
using System;

namespace EF
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

4. Run `Add-Migration Init` from Package Manager Console

### Remarks
If I rename the assembly's name in the project's properties from "EF" to "EF2", the error is gone.

### Further technical details
IDE: (e.g. Visual Studio 2017 15.6.3)

**Comment by divega** [comment] 2018-03-23 18:37
__EF Triage:__ this happens because when you execute dotnet ef or add migration, we use an assembly called EF (ef.dll or ef.exe). We won't load the project assembly. We don't believe that this is enough priority to fix.

**Comment by bricelam** [comment] 2018-03-23 19:32
Duplicate of #8035

**Comment by totht91** [comment] 2018-03-23 19:49
I understand but please provide some more informative error message then because I have wasted 10 or more minutes in a classroom as an instructor.

**Comment by pstricks-fans** [comment] 2020-10-04 13:38
Yes. The error message should be more specific. I got the same error yesterday.

**Closed** 2022-10-16 12:15 UTC
Labels: closed-out-of-scope, customer-reported
