### ISSUE TITLE
upgrading efcore2.2.6 to efcore 3.1 in wpf project with .net 4.8

### ISSUE THREAD

**Issue by METBABA** [dotnet/efcore#19278] opened 2019-12-11 17:20 UTC
İ have a project with framework 4.8 and i try to upgrade efcore 2.2.6 to efcore 3.1  and get a lots of error saying confilicts linq join or where or others with efcore. How am l solve this problem help please

4>D:\Project\Visual Studio 2019\Projects\..\..\xxx.cs(1534,43,1534,48): error CS0121: The call is ambiguous between the following methods or properties: 'System.Linq.Queryable.Where<TSource>(System.Linq.IQueryable<TSource>, System.Linq.Expressions.Expression<System.Func<TSource, bool>>)' and 'System.Linq.AsyncEnumerable.Where<TSource>(System.Collections.Generic.IAsyncEnumerable<TSource>, System.Func<TSource, bool>)'

**Comment by ajcvickers** [comment] 2019-12-12 20:27
Duplicate of #18124

**Closed** 2022-10-16 18:00 UTC
Labels: customer-reported
