### ISSUE TITLE
SqlException Timeout expired on Azure SQL Database

### ISSUE THREAD

**Issue by corradolab** [dotnet/efcore#13572] opened 2018-10-10 15:55 UTC
A simple query which extract a single record from an indexed table time out while running against Azure SQL Database.

Same query execute correctly in less then a second:
- on a local database
- on Azure while executed from SSMS

```
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (30,169ms) [Parameters=[@__gestoreID_0='?' (DbType = Int16), @__vRilevazioneExt_PuntoVendita_PuntoVenditaID_1='?' (Size = 450), @__vRilevazioneExt_Data_2='?' (DbType = DateTimeOffset)], CommandType='Text', CommandTimeout='30']
      SELECT [x].[GestoreID], [x].[Data], [x].[PuntoVenditaID], [x].[EvaDts], [x].[RilevazioneTracciatoID], [x].[XML]
      FROM [RilevazioniTracciati] AS [x]
      WHERE (([x].[GestoreID] = @__gestoreID_0) AND ([x].[PuntoVenditaID] = @__vRilevazioneExt_PuntoVendita_PuntoVenditaID_1)) AND ([x].[Data] = @__vRilevazioneExt_Data_2)
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (258): Tempo di attesa scaduto
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
ClientConnectionId:c3da69f0-98cc-41c0-a722-38c119186eba
Error Number:-2,State:0,Class:11
: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (30,169ms) [Parameters=[@__gestoreID_0='?' (DbType = Int16), @__vRilevazioneExt_PuntoVendita_PuntoVenditaID_1='?' (Size = 450), @__vRilevazioneExt_Data_2='?' (DbType = DateTimeOffset)], CommandType='Text', CommandTimeout='30']
      SELECT [x].[GestoreID], [x].[Data], [x].[PuntoVenditaID], [x].[EvaDts], [x].[RilevazioneTracciatoID], [x].[XML]
      FROM [RilevazioniTracciati] AS [x]
      WHERE (([x].[GestoreID] = @__gestoreID_0) AND ([x].[PuntoVenditaID] = @__vRilevazioneExt_PuntoVendita_PuntoVenditaID_1)) AND ([x].[Data] = @__vRilevazioneExt_Data_2)
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (258): Tempo di attesa scaduto
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
ClientConnectionId:c3da69f0-98cc-41c0-a722-38c119186eba
Error Number:-2,State:0,Class:11
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred in the database while iterating the results of a query for context type 'Rileva.Entities.RilevaContext'.
      System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (258): Tempo di attesa scaduto
         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
         at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
         at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
      ClientConnectionId:c3da69f0-98cc-41c0-a722-38c119186eba
      Error Number:-2,State:0,Class:11
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (258): Tempo di attesa scaduto
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

### Steps to reproduce
Very simple query which generate correct SQL as per above log

```c#
var queryResult = await context.RilevazioniTracciati
  .Where(x => x.GestoreID == gestoreID
    && x.PuntoVenditaID == vRilevazioneExt.PuntoVendita.PuntoVenditaID
    && x.Data == vRilevazioneExt.Data)
  .ToListAsync()
```

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: WebApp on Azure
IDE: Visual Studio 2017 15.8.6

**Comment by ajcvickers** [comment] 2018-10-15 17:28
@corradolab Can you post the _exact_ query as executed in SSMS?

**Comment by ajcvickers** [comment] 2018-10-22 17:53
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ToniaDemchuk** [comment] 2018-12-05 13:10
I have the same issue.

I'm trying to query Azure SQL through code and it throws timeout expired (runs more than 30 sec). But when trying to execute this query in SSMS - executes less that 1 sec.

I'm using the *query type* mapping and FromSQL for my query with several left joins and where conditions. Complex queries that use *entity type* mapping works fast (faster than 1 sec).

I'm using the S0 plan on Azure SQL with little concurrent usage (up to 10 concurrent requests).

**Comment by rfink** [comment] 2020-05-20 19:28
I've definitely had this same issue on multiple queries - less than 3-4 second queries in SSMS that will timeout after 60 seconds in EF

**Closed** 2022-10-16 13:34 UTC
Labels: closed-could-not-reproduce, customer-reported
