### ISSUE TITLE
Automatic update/remove associated relationship

### ISSUE THREAD

**Issue by aborderon** [dotnet/efcore#13994] opened 2018-11-21 20:47 UTC
Hello,
I'm here to get some information about using EntityFramework core for relationship management.

Indeed, let's take the example with the following models.

A first entity "Dashboard":
```c#
public class DashboardEntity
{
    [Key]
    public int Id {get; set; }

    [Required]
    public string Name {get; set; }

    public IEnumerable <DashboardIndicatorRelationEntity> Indicators {get; set; }
}
```
A second entity "Indicator":
```c#
public class IndicatorEntity
{
    public int Id {get; set; }

    [Required]
    public string Name {get; set; }

    public IEnumerable <DashboardIndicatorRelationEntity> Dashboards {get; set; }
}
```
And an entity for the relationship:
```c#
public class DashboardIndicatorRelationEntity
{
    [Required]
    public int DashboardId {get; set; }

    [Required]
    public int IndicatorId {get; set; }

    public DashboardEntity Dashboard {get; set; }

    public IndicatorEntity Indicator {get; set; }
}
```
Here is the configuration of the relationship in the Fluent API:
```c#
builder.HasKey (di => new {di.IndicatorId, di.DashboardId});

builder.HasOne (di => di.Indicator)
    .WithMany (i => i.Dashboards)
    .HasForeignKey (di => di.IndicatorId);

builder.HasOne (di => di.Dashboard)
    .WithMany (d => d.Indicators)
    .HasForeignKey (di => di.DashboardId);
```
When creating a new Dashboard with indicators associated with the creation, I do not have any problem.

For example :
```c#
_context.DashboardEntity.Add (dashboard);
await _context.SaveChangesAsync ();
```
Entity adds in database the new Dashbord with the indicators, so it manages the relationship automatically when adding.

On the other hand, **I encounter more problem when updating the entity and the deletion of relations.**

Let's take the example where I already have a single Dashboard in database which therefore has an ID = 1 and two Indicator (Indicator 1 and Indicator 2). Only Indicator 1 is associated with Dashboard 1.

If I want to update the Dashboard's relations by adding the Indicator 2 and deleting the old relation with the Indicator 1, I proceed as follows:
```c#
var updateDashboard = new DashboardEntity
{
    Id = 1,
    Name = "Dashboard Name",
    Indicators = new DashboardIndicatorRelationEntity () {
        IndicatorId = 2
    }
};

_context.Entry (updateDashboard) .State = EntityState.Modified;
await _context.SaveChangesAsync ();
```
**This does not work, the new relationship with Indicator 2 is well added, but the old relation with Indicator 1 is always present.**

I tried with an Update:
```c#
_context.DashboardEntity.Update (updateDashboard);
await _context.SaveChangesAsync ();
```
But there is no difference, the result is the same.

I managed to work around the problem by removing the relationship manually with Remove:
```c#
var dashboard = _context.DashboardEntity.FindAsync (updateDashboard.id);
var indicator = new DashboardIndicatorRelationEntity {DashboardId = 1, IndicatorId = 1};
dashboard.Indicators.Remove (indicator);
await _context.SaveChangesAsync ();
```
Which is not very practical ... Because it forces to juggle with the remove and the update to update the relations of an entity.

Do you have a more suitable solution to manage changes (addition, deletion) automatically when updating an entity that has related relationships?

Thank you.

### Technical details
EF Core version: Microsoft.AspNetCore.App : 2.1.5
Database Provider: Pomelo.EntityFrameworkCore.MySql : 2.1.2
Operating system: Ubuntu 18.04
IDE: Visual Studio Code

**Comment by ajcvickers** [comment] 2018-11-26 17:46
@aborderon In a many-to-many relationship such as this, adding a new relationship between the two entities does not remove an existing relationship; that's basically the point of a many-to-many relationship. Can you explain a bit more why in this case you expect an existing relationship to be removed when a new relationship is added?

**Comment by ajcvickers** [comment] 2018-12-03 18:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:41 UTC
Labels: closed-could-not-reproduce, customer-reported
