### ISSUE TITLE
Converting values to primitive types in primitive collections

### ISSUE THREAD

**Issue by frankbuckley** [dotnet/efcore#30893] opened 2023-05-15 10:17 UTC
May be related to #25343 and possibly covered by #30677.

The work on primitive collections now enables:

```c#
public class Article
{
    public IList<string> Keywords { get; }
}

// Maps to JSON string array in text column and facilitates querying
builder.Property(e => e.Keywords);
```

Which is super helpful!

However, it does not appear to be possible to configure a value converter to provide a conversion to a primitive type to be stored as a primitive collection - for example:

```c#
public class Article
{
    public IList<Tag> Tags{ get; }
}

// Does not work: System.InvalidCastException : Unable to cast object of type 'System.Linq.Expressions.Expression1`1[System.Func`2[System.Object,System.String]]' to type 'System.Linq.Expressions.Expression`1[System.Func`2[System.Collections.Generic.IEnumerable`1[System.String],System.String]]'.
builder.Property(e => e.Tags).HasConversion(new TagListToStringEnumerableConverter());
```

While we can already use something like a `TagListToJsonStringConverter` today, that does not enable the primitive collections query enhancements.

Might something like this might be supported?

**Comment by roji** [comment] 2023-05-16 08:27
@frankbuckley this should be possible by configuring a value converter on the **element** of the primitive collection, rather than on the collection itself. We're currently lacking APIs to configure anything on the element (e.g. store type, requiredness), but this is definitely something that's planned for 8.0. The tracking issue for that is #30730 (I've added a note there to test this).

**Comment by roji** [comment] 2023-05-16 08:27
Duplicate of #30730

**Closed** 2023-05-16 10:58 UTC
Labels: closed-duplicate, customer-reported
