### ISSUE TITLE
Map to customized (dynamically generated but with same structure) tables entity framework core

### ISSUE THREAD

**Issue by hnviradiya** [dotnet/efcore#15753] opened 2019-05-19 09:12 UTC
Can't there be a mapping of multiple tables (dynamically N tables) to same class.

I have multiple tables generated at runtime. I want to query them. What is a solution to this?

Cant create classes. As tables are generated at runtime.

E.g. table_1, table_2. table_3, ...table_N should map to "table" class. To which I should be able to provide parameter that which table to query on.

Currently onmodelcreating we are using fixed string method named "toTable". Where we can provide fixed string of table name we want to map to. It would be great if we can provide this dynamically.

there are multiple requirements like this on stackoverflow for which people are not getting answered for  as per requirement of OP.

https://stackoverflow.com/questions/56135928/map-to-customized-dynamically-generated-but-with-same-structure-tables-entity/56202714#56202714

https://stackoverflow.com/questions/38372618/multiple-tables-with-same-structure-entity-framework

https://stackoverflow.com/questions/31035238/dynamic-table-name-with-entity-framework

**Comment by ajcvickers** [comment] 2019-05-20 15:10
@hnviradiya Can you explain a bit more how you would use this kind mapping? For example, what would be the code you would write for a query against "table_3"? Also, would all tables have the same columns? If not, how would this be handled? (I'm asking these questions to try to distill down to what EF would need to support for this to work.)

**Comment by hnviradiya** [comment] 2019-05-20 15:52
All tables have same db structure (basically this is a partition of own implementation to handle large datasets).
I can write something like 
dbcontext.DbSet<TableType>("TableName") which will map TableType to TableName mapping..???

isn't this possible?

**Comment by ajcvickers** [comment] 2019-05-20 16:05
@hnviradiya So then what is the CLR type `Table` and how does it relate to this?

**Comment by hnviradiya** [comment] 2019-05-20 16:09
Table is a model (not dbset, but model). because all tables have same structure we can use it in generic way?

**Comment by ajcvickers** [comment] 2019-05-20 16:12
@hnviradiya Okay, so you do have a class that you want to map, you just want to dynamically change which table it maps to. Is this correct?

**Comment by hnviradiya** [comment] 2019-05-20 16:12
yes :)

**Comment by sdanyliv** [comment] 2019-05-20 16:54
Generating query for such tables is not a problem. But it also needs ChangeTracker extension point.
Also user may require Database and Linked Server support also. This is a typical situation for projects with a history when CodeFirst is not an option at all.

@hnviradiya, i suggest to tryout [this extension](https://github.com/linq2db/linq2db.EntityFrameworkCore#linq2dbentityframeworkcore)  :alien:
And you will be able to write such queries:
```cs
var items = context.DbSet<Table>().ToLinqToDBTable().TableName("table_3")
  .Where(...)
  .ToList();
```
For sure ChangeTracker will be not availaible but CRUD operation can be performed in other way:
```cs
var affected = context.DbSet<Table>().ToLinqToDBTable().TableName("table_3")
  .Where(...)
  .Set(v => v.Field, someValue)
  .Update();
```

**Comment by hnviradiya** [comment] 2019-05-20 18:32
Great, that will work for me. Thanks :)

**Comment by ajcvickers** [comment] 2019-05-20 18:33
This is essentially a duplicate of #15671

**Comment by jyller** [comment] 2022-02-15 05:34
What's the best course of action now ？ The sdanyLIV scheme above is now not working ？

**Closed** 2022-10-16 14:21 UTC
Labels: customer-reported

**Comment by dvora2000** [comment] 2023-01-18 21:12
Hi
I have similar  task with dynamic tables in entity framework.
My problem is how to craete those tables. 
The table has to be created when client user send string to api.
the table name is the string. and columns are static.
Is it possible to do that in entity framework? how?
thanks

**Comment by jonathanlocke** [comment] 2023-11-08 13:36
I also have this issue.
