### ISSUE TITLE
SqlServer provider translates StartsWith/EndsWith using TSQL LEN which ignores trailing whitespace

### ISSUE THREAD

**Issue by obohaciak** [dotnet/efcore#20407] opened 2020-03-25 12:58 UTC
SqlServer provider translates `string.StartsWith` using TSQL [LEN](https://docs.microsoft.com/en-us/sql/t-sql/functions/len-transact-sql) which ignores trailing whitespace.

### Steps to reproduce

Let there be an entity named *Entity* with string property *Name* mapping to *NVARCHAR* column. Consider the simplified LINQ expression below:
```C#
using DbContext dbContext = new DbContext();
dbContext.Set<Entity>().Where(e => e.Name.StartsWith(/* e.Name.Substring(0,0) + */ "N "));
```

`SqlServerStringMethodTranslator.TranslateStartsEndsWith` translates `StartsWith` function as
```SQL
WHERE (N'N ' = N'''') OR (LEFT([e].[Name], LEN(N'N ')) = N'N ')
```
LEN excludes all trailing whitespace, yielding wrong results when pattern to be tested contains any. 

If the *Entity* table contained sample data as below, all of them would have been returned.

| Name | Returned |
| ------ |:----------:|
| 'N N'   | Correct |
| 'N'       | Wrong |
| 'NN'    | Wrong |

Testing the hypothesis in SQL Server Management Studio, SELECT LEN('N ') gives 1. For a more extreme case, we can consider LEN('      ') which gives 0. 

Please note this affects 'string.EndsWith' too. The problem only appears when the pattern to be tested is not constant (`SqlConstantExpression`). That's why I included the commented out part in the LINQ query which stops it from being a constant.

### Further technical details

EF Core version: 3.1.1
Database provider: **specific to Microsoft.EntityFrameworkCore.SqlServer**
Target framework: .NET Core 3.1
Operating system: Win 10
IDE: Visual Studio 2019 16.5

**Comment by obohaciak** [comment] 2020-03-25 13:11
An addendum to the original bug description - if the pattern to be tested is a constant, the generated SQL query uses LIKE 'N %' which works as expected.

**Comment by ajcvickers** [comment] 2020-03-25 15:48
Duplicate of #19402

**Closed** 2022-10-16 18:17 UTC
Labels: closed-duplicate, customer-reported
