### ISSUE TITLE
.OnDelete(DeleteBehavior.Restrict) doesn't disable cascaded delete

### ISSUE THREAD

**Issue by rezamohamed** [dotnet/efcore#6204] opened 2016-07-28 23:20 UTC
I am creating my model with .OnDelete(DeleteBehavior.Restrict); so as to disable Cascaded Delete (like EF6 WillCascadeOnDelete(False)) but the SQL table schema shows that the tables have ON DELETE CASCADE.

**Comment by ajcvickers** [comment] 2016-07-28 23:23
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

**Comment by divega** [comment] 2016-08-02 22:15
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 09:52 UTC
Labels: closed-could-not-reproduce
