### ISSUE TITLE
efcore 6 bundle error

### ISSUE THREAD

**Issue by eslamo** [dotnet/efcore#26479] opened 2021-10-28 13:43 UTC
.Net Version: 6.0.100-rc.2.21505.57
Ef Tools Version: 6.0.0-rc.2.21480.5
Visual Studio Version: 17.0.0 Preview 7.0

dotnet ef migrations bundle --project Project/Project.csproj --startup-project Project/Project.csproj--force --verbose --configuration Release

###
C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\Microsoft.Common.CurrentVersion.targets(4635,5): error MSB3027: Could not copy "obj\Release\net6.0\Project.dll" to "bin\Release\net6.0\Project.dll". Exceeded retry count of 10. Failed.  [D:\VisualStudioProjects\S\Project\Project.csproj]
C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\Microsoft.Common.CurrentVersion.targets(4635,5): error MSB3021: Unable to copy file "obj\Release\net6.0\Project.dll" to "bin\Release\net6.0\Project.dll". The process cannot access the file 'D:\VisualStudioProjects\S\Project\bin\Release\net6.0\Project.dll' because it is being used by another process. [D:\VisualStudioProjects\S\Project\Project.csproj]
Microsoft.EntityFrameworkCore.Tools.CommandException: Build failed. Use --verbose to see errors.
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsBundleCommand.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Build failed. Use --verbose to see errors.
###

Same error occurs on visual studio and devops pipline

Tired to clean obj/bin directories, restarted visual studio, cleaned devops _work directories nothing happens always same error

**Comment by ajcvickers** [comment] 2021-11-02 12:42
@eslamo Looks related to #25555. However, it is interesting that in this case it is failing this way in the devops pipeline. Can you provide some more information about the environment for that pipeline? Is it runnin on the same machine that you are doing Visual Studio builds? Also, are you using VS Code at all?

**Comment by eslamo** [comment] 2021-11-02 15:27
@ajcvickers for Devops it's running on 2019 server with agent for windows running on the same machine and I don't use VS Code. I only use VS

By the way I tried an OSX agent and It built without this issue I think this issue is only related to windows cause I tried it in Windows 10 for local build and Devops pipeline using windows agent and I had the same result for error.

**Comment by ErikEJ** [comment] 2021-11-02 16:02
Virus scanner??

**Comment by ajcvickers** [comment] 2021-11-16 09:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:12 UTC
Labels: closed-could-not-reproduce, customer-reported
