### ISSUE TITLE
Initialization of an object, extracted to a common method, does not work properly

### ISSUE THREAD

**Issue by TonyTroeff** [dotnet/efcore#19832] opened 2020-02-07 21:07 UTC
I have got different entities and related view models in my project. The view model initialization logic is used in many places and I decided to extract it in a common method.
For example:
![image](https://user-images.githubusercontent.com/33567383/74065370-677cb100-49fd-11ea-8671-a6fe38721ad3.png)
![image](https://user-images.githubusercontent.com/33567383/74065894-947d9380-49fe-11ea-8f00-3cdc27df2fc8.png)

### Steps to reproduce
Although the view model does not need all of the properties - they all are being queried. (In this case - the 'Title' property is unused).
![image](https://user-images.githubusercontent.com/33567383/74065597-f093e800-49fd-11ea-859f-bf4efb3873e1.png)
The other problem is that a `AnswerGroups` here is a navigation property to another table, but it is not joined in the sent query.

### Further technical details

EF Core version: 3.1.1
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 Enterprise, 16.4.4

**Comment by ajcvickers** [comment] 2020-02-12 03:04
@TonyTroeff It looks like the behavior is probably dependent on the specific EF Core mappings being used. Please try to extract this behavior into a small, self-contained, runnable project and attach that project or post its full code listing here. Doing this ensures we have the EF Core mappings and any other factors needed to reproduce what you are seeing.

As an aside, attaching a project or posting _text_ is much more useful than embedded images. This is because I am going to want to run your code and to do that from an image is very time consuming.

**Comment by ajcvickers** [comment] 2020-02-18 20:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:09 UTC
Labels: closed-could-not-reproduce, customer-reported
