### ISSUE TITLE
Table splitting is not being used by default for owned types

### ISSUE THREAD

**Issue by dgmagno** [dotnet/efcore#20488] opened 2020-04-01 20:27 UTC
Table splitting is not being used by default for owned types.

### Steps to reproduce

``` C#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.Extensions.Logging;

namespace EFCoreBug
{
    public abstract class OrderEntity
    {
        public long Id { get; set; }
        public OrderBarrency Barrency { get; set; }
    }

    public class BaseOrderEntity : OrderEntity
    {
    }

    public class OrderBarrency
    {
        public string Code { get; set; }
    }

    class OrderEntityConfiguration : IEntityTypeConfiguration<OrderEntity>
    {
        const string TableName = "OrderEntities";

        public void Configure(EntityTypeBuilder<OrderEntity> builder)
        {
            builder
                .ToTable(TableName)
                .HasKey(t => t.Id);

            builder.OwnsOne(t => t.Barrency, a =>
            {
                //a.ToTable(TableName); Uncommenting this seems to solve the problem
            });
        }
    }

    class DefaultOrderTableConfiguration : IEntityTypeConfiguration<BaseOrderEntity>
    {
        public void Configure(EntityTypeBuilder<BaseOrderEntity> builder)
        {
            builder.HasBaseType<OrderEntity>();
        }
    }

    public class DataContext : DbContext
    {
        public static readonly ILoggerFactory MyLoggerFactory
            = LoggerFactory.Create(builder => { builder.AddConsole(); });

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseLoggerFactory(MyLoggerFactory)
                .UseSqlServer(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=OwnsOneBug;");
        }

        public DbSet<OrderEntity> OrderEntities { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new OrderEntityConfiguration());

            // removing inheritance also fixes the extra table creation for owned entity
            modelBuilder.ApplyConfiguration(new DefaultOrderTableConfiguration()); 
        }
    }

    public class Program
    {
        public static void Main()
        {
            using (var context = new DataContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
            }
        }
    }
}
```

### Further technical details

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 Enterprise Version 1809 Build 17763.1098
IDE: Visual Studio Professional 2019 16.5.1

**Comment by smitpatel** [comment] 2020-04-01 20:37
Duplicate of #19279

**Closed** 2022-10-16 18:18 UTC
Labels: customer-reported
