### ISSUE TITLE
Entity Framework Core 2.0 Scaffold-DbContext returns Build Error

### ISSUE THREAD

**Issue by LakshmiPrasanna-Human** [dotnet/efcore#9515] opened 2017-08-22 08:07 UTC
In visual Studio 2017, create a .NET core class library project with Target Framework as 2.0 (No project.json).

Have included below packages by Package Manager console.

Microsoft.EntityFrameworkCore.SqlServer
Microsoft.EntityFrameworkCore.SqlServer.Design
Microsoft.EntityFrameworkCore.Tools
Microsoft.VisualStudio.Web.CodeGeneration.Design
While running below Scaffold-DbContext command from Package Manager console of same project , getting Build Failed error.

### Steps to reproduce
Scaffold-DbContext "Data Source=HTGHTFG135611L;Initial Catalog=HHH;Persist Security Info=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir DBModels -force -v 

Also tried with giving username and password

### Further technical details
EF Core version: 2
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer)
Operating system:  Windows 8 32 bit
IDE:  Visual Studio 2017 community edition

**Comment by bricelam** [comment] 2017-08-22 16:59
If you manually build the project (e.g. using Ctrl+Shift+B) you should be able to see what the errors are.

**Comment by smitpatel** [comment] 2017-08-22 18:46
> Microsoft.EntityFrameworkCore.SqlServer.Design

This package is no longer in 2.0 release. You need to remove reference to it.

**Comment by LakshmiPrasanna-Human** [comment] 2017-08-23 04:23
1. I have removed "Microsoft.EntityFrameworkCore.SqlServer.Design"
2. Build the project , its not showing any build errors. Build is successful.
3. When running Scaffold-DBContext from powershell command , it throwing the same error.
PM> Scaffold-DbContext "Data Source=HTGHTFG135611L;Initial Catalog=HHH;Persist Security Info=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir DBModels -force -v
Using project 'HHH.DataModel'.
Using startup project 'HHH.DataModel'.
Build started...
Build failed.

**Comment by LakshmiPrasanna-Human** [comment] 2017-08-23 04:24
Appreciate, if i can details more quickly

**Comment by pmrozek** [comment] 2017-08-23 09:10
I have the same problem with my project (class library - Visual Studio Pro 2017 15.3.2).
My project settings: 
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
</Project>

NuGet Package Manager Console: 
PM> Scaffold-DbContext "Server=(local);Database=CrossPlatform;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models  -force
Build failed.

**Comment by bricelam** [comment] 2017-08-23 15:39
We may need someone on [dotnet/project-system](https://github.com/dotnet/project-system) to help investigate. Our tool just calls the following. No additional information is available from the EnvDTE interfaces.

```ps1
$DTE.Solution.SolutionBuild.Build($true)
if ($DTE.Solution.SolutionBuild.LastBuildInfo)
{
    throw 'Build failed.'
}
```

**Comment by pmrozek** [comment] 2017-08-23 16:01
Sure, please find the attached file (project + database).

[CrossPlatform.zip](https://github.com/aspnet/EntityFrameworkCore/files/1246111/CrossPlatform.zip)

**Comment by LakshmiPrasanna-Human** [comment] 2017-08-24 06:22
Hi, The issue got resolved in my case. However i still see a bug in this. Below is the 

Current Solution:  My current solution has three projects. One of the project(ProjectA) has build errors. In ProjectB i am running the Scaffold command from Project Management Console. In project Management Console , ProjectB is clearly selected. In this scenario its throwing error "Build Error" and code files are not auto generated.  

Work Around: I have unloaded ProjectA and re run the command. Now code files are not auto generated.  
However ProjectA and ProjectB are not related to each other. Also in Project Management Console, i am selected ProjectB, why should it look for ProjectA build errors.

**Comment by bricelam** [comment] 2017-08-24 16:02
> I have selected ProjectB, why should it look for ProjectA build errors.

There were bugs in certain project types when we tried to only build the selected project, so we had to resort to building the entire solution. 

There's [a TODO](https://github.com/aspnet/EntityFrameworkCore/blob/rel/2.0.0/src/EFCore.Tools/tools/EntityFrameworkCore.psm1#L775) in the code for finding a reliable way to build just the selected project.

**Comment by syndicatedshannon** [comment] 2017-09-04 02:28
This dependency on building the entire solution to build the data models is quite an obstacle, since the data models are at the lowest layers of my solution dependencies. Add this to the list of non-starters in EF Core for me.

**Comment by syndicatedshannon** [comment] 2017-09-04 02:30
LakshmiPrasanna-Human 👍 : we are using your workaround to unload projects, to manually operate in a DB-first approach. Sadly it makes it nearly impossible to create any automated development tooling for this.

**Comment by ErikEJ** [comment] 2017-09-04 05:05
@syndicatedshannon you can use SQLite toolbox to generate the model, does not require anything to be compiled

**Comment by syndicatedshannon** [comment] 2017-09-04 17:12
@ErikEJ : Thank you for that. I wasn't aware of that tool.

I know this is a tangent, but I see it mentions generation directly from DACPAC, and creating EF Core models directly from my SQL Server Data Project (which is currently the authority for my schema 'truth') would simplify things greatly for me. Currently the only reason I generate from a database instance is as a round-about step to get code from my schema.

I also see that SQLite Toolbox depends on https://marketplace.visualstudio.com/items?itemName=SimonHughes.EntityFrameworkReversePOCOGenerator , which has "Support EF Core" on its TODO list.

Do you know offhand if the relationship between SQLite Toolbox and this dependency invalidates it for this idea?

**Comment by ErikEJ** [comment] 2017-09-04 17:44
@syndicatedshannon Well, that particular feature only works for EF6 yes. 

It is quite simple to deploy your dacpac to a "blank" localdb database (either via gui or using a command line script) , and then run reverse engineer from that, using the SQLite Toolbox. 

For the command line script to do that, you can use sqlcmd.exe + sqlpackage.exe to create the database and deploy the dacpac file. 

Are you looking for a way to create the reverse engineer code from a standalone command line tool? (Not using dotnet ef or PMC in VS)

**Comment by syndicatedshannon** [comment] 2017-09-04 18:10
@ErikEJ : Yes, the "blank" localdb workflow is exactly how I ended up here commenting about the inability to generate code on a project that wouldn't build, above :) . I was currently doing it manually and resolving workflow bugs, and was just about to script it out, so thank you for the tool references (sqlcmd.exe + sqlpackage.exe).

> Are you looking for a way to create the reverse engineer code from a standalone command line tool?

Well, in a perfect world, it would run on changes, ideally processing deltas only, as part of MSBuild. This would update my data models when my DB Schema changes (e.g. via Git submodule version bump), ensuring that the code always matches the DB Schema it is associated with.

The desire to run as part of an MSBuild change-detect is why my ideal scenario doesn't have a stopover in a DB instance.

I could easily be missing some generally-accepted solution to this problem.

Hope that clarifies.

**Comment by syndicatedshannon** [comment] 2017-09-04 18:21
Maybe it's simplest to say that my desire is to fail build if EF Models don't match DB Schema, in a DB-First EF Core environment.

**Comment by syndicatedshannon** [comment] 2017-09-04 18:42
Thinking more about what/why you were asking, I probably didn't really clarify my goal.

My current near-term plan is to create an MSBuild Task that runs whenever any file in my DB Schema project is newer than a timestamp file stored in my EF Core Model project.

An example of a C# class that implements ITask doing this:
 - conditionally run based on file timestamps (MSBuild does this internally)
 - use SQL SMO/DMO to create a new instance from DACPAC (sadly DMO is prone to version issues)
 - initiate SQLite Toolbox reverse engineer by a process I haven't researched yet
 - update timestamps when complete

**Comment by ErikEJ** [comment] 2017-09-04 19:08
Re  step 2: DacFX should be used for that, not SMO

Re step 3: Sounds like you are asking for a command line tool!

**Comment by bricelam** [comment] 2017-09-05 18:05
@pmrozek I am not able to reproduce the issue on the solution you provided. Does unload projects work around the issue for you?

**Comment by bricelam** [comment] 2017-09-05 18:07
Notes for triage: We should create a new issue about only building the startup project and not the entire solution.

**Comment by syndicatedshannon** [comment] 2017-09-06 18:49
This issue occurs in my current project. I cannot share my code, but I don't think it should be necessary.
It seems clear from the code snippets above (https://github.com/aspnet/EntityFrameworkCore/issues/9515#issuecomment-324375818) that if the entire solution does not build, the scaffold will fail.

That means the solution can easily become 'wedged', where if the developer deletes or modifies the database, discovers the modification is incorrect, and tries to modify it again, they will be unable to resolve the issue without reverting their work.

Additionally, because the scaffold may result in renames or removals, any automated processes/tooling would need to clean models first, also resulting in a solution that won't build, and therefore a paradoxical tooling requirement.

**Comment by ajcvickers** [comment] 2017-09-07 00:06
We have created a new issue to cover building only the startup project rather than the solution--see #9716.

There's a lot of other discussion in this thread not directly related to this. Some of it is covered by the work being done for #831 (Update model from database). Feel free to comment with thoughts on that issue. If there are other specific EF things that you feel are not being tracked anywhere, then please file new issues to track them so that we can manage them better.

**Comment by satvik1986** [comment] 2018-03-22 05:03
how to generate domain from existing database using scaffold in entityframework core?.

**Comment by satvik1986** [comment] 2018-03-22 05:27
Scaffold-DbContext "server=servername;database=testDb;user=test;password=newpass;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer  -Context "testContext"

**# Getting error**

System.Data.SqlClient.SqlException (0x80131904): Failed to generate SSPI context.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.SqlServerDatabaseModelFactory.Create(DbConnection connection, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.SqlServerDatabaseModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ModelScaffolder.Generate(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String projectPath, String outputPath, String rootNamespace, String contextName, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:b527a95f-e41b-499d-ba39-c359653928b0
Failed to generate SSPI context.

**Comment by ErikEJ** [comment] 2018-03-22 11:56
@satvik1986 Please do not add to existing issues, also, this is a SQL logon issue, not an EF Core issue

**Comment by faisal5170** [comment] 2018-07-13 11:53
System.InvalidOperationException: Instance failure.
   at System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerDatabaseModelFactory.Create(DbConnection connection, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerDatabaseModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String namespace, String language, String contextDir, String contextName, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Instance failure.

@ErikEJ  when I fire "Scaffold-DbContext "Data Source=Faisal-Pathan\\SQLEXPRESS;Initial Catalog=DemoDB;User ID=sa;Password=vision" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models" getting error

**Comment by ErikEJ** [comment] 2018-07-13 12:16
@faisal5170 pls raise a new issue with a reproduction - can you connect without having EF Core involved?

**Comment by faisal5170** [comment] 2018-07-13 12:21
Hello sir @ErikEJ  ,
I have one question, If we change in context class which genertaed by "Scaffold-DbContext" this command in .net core and we change static connection-string  to dynamic connection-string logic and then we want to update table so we fire again same command at that time whole dbcontext class will be change (as new) any suggestion to just update entity class with old changes ?

**Closed** 2022-10-16 11:17 UTC
Labels: closed-no-further-action
