### ISSUE TITLE
Redundant order by when selecting subquery field

### ISSUE THREAD

**Issue by rofenix2** [dotnet/efcore#27590] opened 2022-03-08 01:55 UTC
Hi, i don't know if this is intended behavior but when i try to order by a field that has a subquery, EFCore generates a copy of the subquery instead of using the field.

For example i have a "Post" table with "PostLike" table (1..N):

```C#
var test = (from post in Context.Set<Post>()
                 select new
                 {
                     Likes = post.Likes.Count
                 }).OrderByDescending(x => x.Likes);
var query = test.ToQueryString();
```

Gives me the following query:

```
SELECT (
    SELECT COUNT(*)
    FROM [Social].[PostLike] AS [p1]
    WHERE [p].[PostId] = [p1].[PostId]) AS [Likes]
FROM [Social].[Post] AS [p]
ORDER BY (
    SELECT COUNT(*)
    FROM [Social].[PostLike] AS [p0]
    WHERE [p].[PostId] = [p0].[PostId]) DESC
```

Instead of:

```
SELECT (
    SELECT COUNT(*)
    FROM [Social].[PostLike] AS [p1]
    WHERE [p].[PostId] = [p1].[PostId]) AS [Likes]
FROM [Social].[Post] AS [p]
ORDER BY Likes DESC
```
Is there any way to fix this?.
Currently using EFCore 7 preview 1.22076.6 with the same ver for SQL Server provider.

**Comment by maumar** [comment] 2022-03-08 03:11
dupe of https://github.com/dotnet/efcore/issues/18775

**Closed** 2022-10-16 20:28 UTC
Labels: customer-reported
