### ISSUE TITLE
DbScaffold with C# 9 records

### ISSUE THREAD

**Issue by jernejk** [dotnet/efcore#23236] opened 2020-11-09 05:31 UTC
We are currently working for a client where we only query SQL Server and almost never change it.
With help of `dotnet ef dbcontext` we are generating all of the necessary models and DbContext.
There were several other project in the past where we weren't allowed to modify the DB.

Atm, all of our queries use `.NoTracking()` and down the line, we map them into records if we can use .NET 5.

Is it possible to scaffold models as records `dotnet ef dbcontext`?
I believe this would be great for scenarios where it is expected that the DB is read-only and prevents devs from modifying the models. Any attempts for updating would have to be delibrate (setting the modified record as tracked?).

**Comment by roji** [comment] 2020-11-09 06:47
Duplicate of #4038

**Comment by roji** [comment] 2020-11-09 06:48
It's certainly a compelling idea for non-tracking scenarios where immutability is desired. #4038 is about providing full template customization of scaffolded models, so if that's done anything becomes possible.

**Comment by ErikEJ** [comment] 2020-11-09 06:51
@jernejk potentially the HandleBars extension may be able to do that for you.

**Comment by ajcvickers** [comment] 2020-11-09 15:25
Wonder if we should keep this open to gather feedback on records specifically?

**Comment by ajcvickers** [comment] 2020-11-09 19:26
Triage: closing as a duplicate of #4038. Be sure to vote for that issue!

**Closed** 2022-10-16 19:08 UTC
Labels: closed-duplicate, customer-reported
