### ISSUE TITLE
EF Core slower than EF 6

### ISSUE THREAD

**Issue by MinhMit** [dotnet/efcore#30048] opened 2023-01-13 02:07 UTC
Hi, 

I upgrading my project from EF 6 to EF Core 7.0.1

Source project from netcoreapp2.0 and use EntityFramework 6.4.4

Destination project to net7.0 enable TieredPGO and use Microsoft.EntityFrameworkCore.SqlServer 7.0.2

Same query and same database destination project slow than source project

Query:
![image](https://user-images.githubusercontent.com/5819667/212220308-29469116-1e82-49a0-a26b-bf8c54fa2d53.png)

EF 6.4.4 result
![image_2023_01_13T01_55_19_965Z](https://user-images.githubusercontent.com/5819667/212220345-54f2de8f-2ec9-463b-a414-ebe3dd123987.png)

EF Core 7.0.2 result
![image_2023_01_13T01_59_25_989Z](https://user-images.githubusercontent.com/5819667/212220433-c89ad994-2533-4825-be37-61b0a95354cf.png)

Add DbContextPool for both projects
![image](https://user-images.githubusercontent.com/5819667/212220582-1c9fda03-454c-42ad-83ed-745663da304d.png)

AsQueryable for both projects
![image](https://user-images.githubusercontent.com/5819667/212220851-18fc41fe-c4ca-4bba-af49-e94910186f02.png)

What can I do to improve performance?
Thank for your support.

**Comment by gfoidl** [comment] 2023-01-13 09:50
> net7.0 enable TieredPGO

Then you shouldn't measure with `Stopwatch` as tiering won't be able to produce optimized code. So either
* use a dedicated benchmarking tool like https://benchmarkdotnet.org/
* "warmup" your benchmarks within a loop (say 100 iterations) with some delay in between (say 100 ms every 10 iterations) in order for tiering to kick in

BTW: this is not only for tiering, also for GC to reach a kind of steady state, etc. 
And this is targeting server workloads.

For command-line apps that start, execute, shut-down you could use R2R to get better perf.

**Comment by roji** [comment] 2023-01-13 16:10
As @gfoidl wrote, please use BenchmarkDotNet to make sure your benchmarks are accurate. If you're still seeing EF Core performing slowly, please submit your minimal, runnable BenchmarkDotNet benchmark here and we'll investigate. In almost all cases of reports we've received like this, the benchmark itself was flawed in some way.

**Comment by MinhMit** [comment] 2023-01-13 17:44
I used BenchmarkDotNet 

Benchmark:
![Capture6](https://user-images.githubusercontent.com/5819667/212385299-178afb8a-5597-4687-b744-90957b754756.PNG)

Result for 100 records:
![Capture2](https://user-images.githubusercontent.com/5819667/212385398-7db25cbe-c3a4-4dde-86e0-b1582ea8e252.PNG)
![Capture3](https://user-images.githubusercontent.com/5819667/212385416-670c7433-a8ab-4afd-8068-4346a1d9f9c4.PNG)

Result for 1000 records:
![Capture4](https://user-images.githubusercontent.com/5819667/212385478-2d4ca284-e51c-44c3-b612-3f45a44dad09.PNG)
![Capture5](https://user-images.githubusercontent.com/5819667/212385490-8a77c058-9cc1-4cae-ae10-4a8f31904d30.PNG)

I don't see much of a difference?
What can I do for now?

Thank for your support.

**Comment by ErikEJ** [comment] 2023-01-13 17:54
Enjoy the benefits of EF Core? :smile:

**Comment by roji** [comment] 2023-01-13 18:12
@MinhMit please post actual code rather than screenshots - screenshots can't be copy-pasted (etc.).

In any case, what's your precise question about the result, what are your expectations?

**Comment by ilmax** [comment] 2023-01-13 18:36
It also looks like BenchmarkDotNet is warning you about having the debugger attached. In order to get more accurate measurement don't run the benchamrk application with a debugger attached

**Comment by MinhMit** [comment] 2023-01-14 02:57
I used release mode to measure with Benchmark but the results were not very impressive.

Result with 1000 records / per 2085759 records in database

![Capture1](https://user-images.githubusercontent.com/5819667/212447470-0d4d7e55-4a90-43bd-ade6-55804c669378.PNG)
![Capture](https://user-images.githubusercontent.com/5819667/212447473-fd5bfcaf-bb56-44e3-86d3-f455a9eb03a3.PNG)

As far as I know EF Core is faster than EF Framework. But here I don't see a big change in performance.
Does this issue involve EF Core? Or is there actually only that slight improvement?
What can I do to improve performance?

Here my code
Customer class:
```
public class Consumer
{
	[Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public override Guid? Id { get; set; }
        public string PrimaryEmail { get; set; }
        public bool? EmailVerified { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
}
```

ApplicationDbContext class:

```
public class ApplicationDbContext : DbContext
{
        public DbSet<Consumer> Consumers { get; set; }
        public ApplicationDbContext(DbContextOptions options) : base(options)
        {}

	protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
		modelBuilder.Entity<Consumer>().HasIndex(x => x.PrimaryEmail).IsUnique();
		base.OnModelCreating(modelBuilder);
	}
}
```

Benchmark class:

```
[Benchmark]
        public void ConcatStringsUsingStringBuilder()
        {
            var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
            optionsBuilder.UseSqlServer("Server=localhost;Database=20230111-patched;User Id=sa;password=abcde12345-;Trusted_Connection=False;MultipleActiveResultSets=true;TrustServerCertificate=true;");
            var emails = new List<string>()
            {
//sensitive data
            };
            var sb = new StringBuilder();
            foreach (var email in emails)
            {
                using (var applicationDbContext = new ApplicationDbContext(optionsBuilder.Options))
                {
                    var test = applicationDbContext.Consumers.AsNoTracking().FirstOrDefault(entity => entity.PrimaryEmail == email);
                }
            }
        }
```

**Comment by roji** [comment] 2023-01-14 14:24
@MinhMit the above isn't a complete benchmark; specifically, the code seems to be for EF Core only - where's the code testing the non-core EF 6?

Please post a full, runnable BenchmarkDotNet benchmark, rather than bits and snippets.

> What can I do to improve performance?

We have [extensive documentation on performance](https://learn.microsoft.com/en-us/ef/core/performance/). For example, it's highly recommended to turn on [context pooling](https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#dbcontext-pooling
) if you care about high performance.

**Comment by MinhMit** [comment] 2023-01-14 17:25
@roji  Because of sensitive and private information of project, I can't share database here.

However, as I noted, old project uses EntityFramework 6.4.4 and Netcoreapp 2.0.
I am currently updating to net7.0 and Microsoft.EntityFrameworkCore.SqlServer 7.0.2.
The code for both projects is the same, yet neither project's performance has changed significantly. Can I make a mistake or use EF and .NET?

I just started using Benchmark. Would you kindly explain what else I need to give you?

Thank for your support

**Comment by roji** [comment] 2023-01-15 01:01
> Because of sensitive and private information of project, I can't share database here.

@MinhMit I don't need to see any sensitive/private information - you should be able to put together a minimal, self-contained benchmark (without your project's specific data), and share it's full source code here. Otherwise, there's no way of knowing what exactly you're doing or where any perf issues are coming from; all we can do is discuss in general and not go into specifics.

This is similar as a bug report, where we frequently need a self-contained, runnable code sample which reproduces the bug. Once that's supplied, I can see the issue running on my machine and can investigate in detail what's going on.

**Comment by ajcvickers** [comment] 2023-01-27 13:09
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-01-27 13:09 UTC
Labels: customer-reported
