### ISSUE TITLE
Global Filter with Paging

### ISSUE THREAD

**Issue by eZawer** [dotnet/efcore#13433] opened 2018-09-27 22:10 UTC
When using global filters with paging (take/skip) the the generated SQL looks something like:

SELECT *
FROM (
    SELECT *  FROM GL.Account   ORDER BY   Id asc  OFFSET 0 ROWS FETCH NEXT 50 ROWS ONLY
) AS [t]
WHERE [t].[CompanyId] = 1
ORDER BY [t].[XPath]

As Noted from above the filter applied to the outer query which means that the inner query will fetch first 50 records regardless of their tenant or companyId, you may have thousands of records for company 1 and get only 10 records from above statement because the first 50 recrods has 40 records in other tanant and only 10 records from filtered company.

### Further technical details
EF Core version: 2
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Windows 10 x64
IDE:  Visual Studio 2017 15.7

**Comment by smitpatel** [comment] 2018-10-01 23:13
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2018-10-08 17:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:32 UTC
Labels: closed-could-not-reproduce, customer-reported
