### ISSUE TITLE
Generating entities into a different project than the configuration/dbcontext

### ISSUE THREAD

**Issue by aplocher** [dotnet/efcore#15315] opened 2019-04-10 22:11 UTC
Is it currently possible to generate the entities into a separate project from the DbContext and Configuration?  

I've seen that I can generate the output to a different folder in a different project (using the command below), but the problem is, it still utilizes the Data project's namespaces.

`dotnet ef dbcontext scaffold -c EastwindDbContext "data source=(local)\SQL17;initial catalog=Eastwind;Integrated Security=True" "Microsoft.EntityFrameworkCore.SqlServer" --startup-project "..\Eastwind.Api" --output-dir "..\Eastwind.Core\Entities" --force --verbose`

That command will generate entities under the Eastwind.Core\Entities folder, but it uses the Eastwind.Data namespace. I would like them to use the Eastwind.Core.Entities namespace.

Some background:

I'm not sure if this is a bad practice (I'm open to a discussion about this), but I would like to regenerate my POCO entities and Configuration/DbContext as the database changes and use the POCO entities as my domain entities in my core projects.  I would like to keep my  database project with all the database-specific plumbing (DB Context, Fluent configuration stuff).

### Further technical details
EF Core version: 2.2.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 Enterprise

Thank you

**Comment by ErikEJ** [comment] 2019-04-11 17:24
EF Core Power Tools can do this for you

**Comment by aplocher** [comment] 2019-04-12 03:49
@ErikEJ thank you I just loaded it up and this is very helpful and will likely be the route I take to handle this.  My only issue (albeit a small one) is that it appears I will need to run this in the two projects each time and then manually add a "using" at the top to point to the Core project in the Configuration/DbContext .cs file.  

I don't suppose there's anyway to trigger the reverse engineering process from the command line is there?  If so, I could have a single .bat file that handles both the Data and Core projects and then use some fancy parsing to add the 'using' statement in to the DbContext/Config file pretty easily.

Thanks!

**Comment by aplocher** [comment] 2019-04-12 03:53
Oh, looks like the handlebar templates can address the "using".  Still would be nice to generate command line so I can reload everything with a double-click instead of going through the dialogs, but this will definitely work if that's not possible.

Thanks again!

**Comment by ErikEJ** [comment] 2019-04-12 05:09
Command line tooling is in progress

**Comment by ajcvickers** [comment] 2019-04-15 18:20
@aplocher Have you tried using the [`context-dir`](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#dotnet-ef-dbcontext-scaffold) option?

**Comment by ajcvickers** [comment] 2019-04-26 16:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:17 UTC
Labels: closed-could-not-reproduce, customer-reported
