### ISSUE TITLE
Saving 26k objects in context with property AutoDetectChangesEnabled set to false takes much more time than in EF6

### ISSUE THREAD

**Issue by MarcinSzyszka** [dotnet/efcore#5165] opened 2016-04-25 08:37 UTC
Hi. 
In previous version (EF6) when Configuration.AutoDetectChangesEnabled is set to false and I add to context 26k objects, and call SaveChanges() - saving operation takes 40 seconds. 
In Entity Framework Core this operation with property ChangeTracker.AutoDetectChangesEnabled = false, and with the same count and type of objects takes 15 minuts. 
Where is the problem or what I'm doing wrong?

**Comment by ErikEJ** [comment] 2016-04-25 10:19
Which EF version? - a number of performance impovements have been made in RC 2

**Comment by MarcinSzyszka** [comment] 2016-04-25 10:26
7.0.0-rc1-final - package in project.json and 7.0.0-rc1-16348 - Product Version in DbContextModelSnapshot

**Comment by MarcinSzyszka** [comment] 2016-04-25 10:27
When I will be able to use RC2? :)

**Comment by ErikEJ** [comment] 2016-04-25 11:31
Soooon!

**Comment by rowanmiller** [comment] 2016-04-28 23:11
Duplicate of https://github.com/aspnet/EntityFramework/issues/4831

**Closed** 2022-10-16 09:38 UTC
