### ISSUE TITLE
Problem when I add migration

### ISSUE THREAD

**Issue by WiliamGP** [dotnet/efcore#6086] opened 2016-07-15 10:34 UTC
I'm developing an application UWP and when I add migration an error occurs stating that the entity needs a primary key, but the primary key is defined in the code. Follow the error and the class code. Someone can help me?

Best Regards! 

Error:
The entity type 'object' requires a key to be defined.

Class:

``` C#
public class Exercicio
{
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int idExercicio { get; set; }
        [Required]
        public string descricao { get; set; }
}
```

**Comment by natemcmaster** [comment] 2016-07-15 16:44
This is likely a duplicate of #5945. DataAnnotations are currently broken on UWP due to changes in the BCL. See https://github.com/aspnet/EntityFramework/issues/5945#issuecomment-230854436 for a workaround.

**Comment by WiliamGP** [comment] 2016-07-16 02:14
@natemcmaster thanks, now it works! Best Regards!

**Closed** 2022-10-16 09:51 UTC
