### ISSUE TITLE
Issue with Identity Columns

### ISSUE THREAD

**Issue by tdyrkacz** [dotnet/efcore#18210] opened 2019-10-03 18:32 UTC
I have a problem with latest version 3.0 of core entity framework. When i try to use the database context i get the error that my table has more than one identity key when in fact it has none. It is a table where the PK is made up of multiple foreign keys to other tables where those columns are identity columns.

This worked fine in 2.2.6 I already tried re-scaffolding my database.

Error:

System.InvalidOperationException: The properties 'InstrumentFieldData.DataFeedKey', 'InstrumentFieldData.InstrumentKey', 'InstrumentFieldData.FieldKey', 'InstrumentFieldData.ContextPatternKey' are configured to use 'Identity' value generator and are mapped to the same table 'MarketData.InstrumentFieldData'. Only one column per table can be configured as 'Identity'. Call 'ValueGeneratedNever' for properties that should not use 'Identity'.
Stack Trace:
at SqlServerModelValidator.ValidateSharedColumnsCompatibility(IReadOnlyList1 mappedTypes, String tableName, IDiagnosticsLogger1 logger)
at RelationalModelValidator.ValidateSharedTableCompatibility(IModel model, IDiagnosticsLogger1 logger) at RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger1 logger)
at SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)

### Steps to reproduce

Create a table with multiple FKs that are identiy columns on other tables and make them your PK on the table. Then run a query against the table.

### Further technical details

EF Core version:3.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system: Windows 2010
IDE: (Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment] 2019-10-09 19:01
@tdyrkacz I attempted to reproduce this following the steps:

My code is below--I don't see any exceptions when it runs. Can you update my repro code so that it demonstrates the behavior you are seeing?

```C#
public class One
{
    public int Id { get; set; }
}

public class Two
{
    public int Id { get; set; }
}

public class Three
{
    public int Id { get; set; }
}

public class A
{
    public One One { get; set; } 
    public int OneId { get; set; } 
    
    public Two Two { get; set; } 
    public int TwoId { get; set; } 

    public Three Three { get; set; } 
    public int ThreeId { get; set; } 
}

public class BloggingContext : DbContext
{
    private static readonly ILoggerFactory Logger
        = LoggerFactory.Create(x => x.AddConsole());
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<A>().HasKey(e => new {e.OneId, e.TwoId, e.ThreeId});
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0")
            .UseLoggerFactory(Logger);
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var results = context.Set<A>()
                .Include(e => e.One)
                .Include(e => e.Two)
                .Include(e => e.Three)
                .ToList();
        }
    }
}
```

**Comment by ajcvickers** [comment] 2019-10-18 15:59
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:47 UTC
Labels: closed-could-not-reproduce, customer-reported
