### ISSUE TITLE
Navigation property doesn't work with non-Nullable types.

### ISSUE THREAD

**Issue by Anakael** [dotnet/efcore#25405] opened 2021-08-03 16:21 UTC
When querying data from DB to models non-Nullable properties don't update.

Examples:

```csharp
class Student
{
public Student(School school)
{
   School = school;
}

private Student()
{
   School = new(...); // Create with default invalid properties due to enabled Nullable in projects.
}

public School School { get; } // Doesn't work
public School? School {get;} // Work
}
```
Seems like EF Core doesn't update navigation properties that is not null

Is there any workaround for that?

**Comment by ajcvickers** [comment] 2021-08-06 13:43
Duplicate of #18007 and #23851.

**Closed** 2022-10-16 19:41 UTC
Labels: closed-duplicate, customer-reported
