### ISSUE TITLE
Unable to get multiple dataset from store procedure

### ISSUE THREAD

**Issue by bilalmalik777** [dotnet/efcore#19142] opened 2019-12-03 10:55 UTC
I am trying to get multiple data sets from sp via FromSql in Dotnet core 2.2, but unfortunately, I am not getting success. does Dotnet core provide support to get multiple data set from one sp

**Comment by ajcvickers** [comment] 2019-12-04 19:46
Duplicate of #8127

**Closed** 2022-10-16 14:59 UTC
Labels: customer-reported
