### ISSUE TITLE
Return values of SingleOrDefaultAsync incorrect when nullable reference types are enabled

### ISSUE THREAD

**Issue by dannyBies** [dotnet/efcore#21793] opened 2020-07-26 13:12 UTC
In my project I have nullable reference types enabled.
```<Nullable>enable</Nullable>```

I believe the return type is incorrect for the following methods in EntityFrameworkQueryableExtensions.cs
- FirstOrDefaultAsync
- LastOrDefaultAsync
- SingleOrDefaultAsync

I believe those methods should use the [return: MaybeNull] attribute just like equivalent [System.Linq](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq/src/System/Linq/First.cs#L33) methods do.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/3967506/88479762-ca351b00-cf51-11ea-91b0-ca78b9d5e68e.png)

I would expect a build error at foundInvite.Expired as this could return null.

### Further technical details

EF Core version: 5.0.0-preview.7.20365.15
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET5
Operating system: Windows 10
IDE: 16.7.0 Preview 5.0

**Comment by roji** [comment] 2020-07-26 14:29
Simply adding [MaybeNull] isn't the right solution here for the async methods, see https://github.com/dotnet/efcore/pull/21794#issuecomment-663994783.

**Comment by roji** [comment] 2020-07-26 14:29
Duplicate of #19007

**Comment by roji** [comment] 2020-07-31 11:27
@dannyBies T? is being added for C# 9, which would be the correct annotation for this (as it allows annotating the nested generic type parameter): Note: for LINQ async operators (e.g. FirstOrDefaultAsync): dotnet/roslyn#45993 (but depends on C# 9)

**Comment by dannyBies** [comment] 2020-07-31 12:06
That's great, thanks for letting me know! Any idea when this will be usable in this project? I can make the necessary changes once T? is available here.

**Comment by roji** [comment] 2020-07-31 12:31
We're definitely not going to be doing any nullability annotation work for the upcoming 5.0 release (which is being stabilized), but I really hope we have time to that for 6.0. Track #19007 to know what's going on.

**Closed** 2022-10-16 18:34 UTC
Labels: customer-reported
