### ISSUE TITLE
Multiple queries being generated when entire element selected

### ISSUE THREAD

**Issue by meyerovb** [dotnet/efcore#14326] opened 2019-01-05 03:42 UTC
EF is producing multiple queries (n+1) instead of a single query with a subquery when the selection contains the entire element instead of just part of it.

### Steps to reproduce
Set up a project as per https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db?tabs=visual-studio

```c#
context.Blogs.Select(a => new { a.Url, a.Posts.Count }).ToList();
```
runs this
```sql
SELECT [a].[Url], (
    SELECT COUNT(*)
    FROM [Posts] AS [p]
    WHERE [a].[BlogId] = [p].[BlogId]
) AS [Count]
FROM [Blogs] AS [a]
```

```c#
context.Blogs.Select(a => new { a, a.Posts.Count }).ToList();
```
runs this
```sql
SELECT [a].[BlogId], [a].[Url]
FROM [Blogs] AS [a]

exec sp_executesql N'SELECT COUNT(*)
FROM [Posts] AS [p0]
WHERE @_outer_BlogId = [p0].[BlogId]',N'@_outer_BlogId int',@_outer_BlogId=2
```

### Further technical details
EF Core version: 2.2
Database Provider: mssqllocaldb
Operating system: Win10
IDE: (e.g. Visual Studio 2017 15.9.4)

**Comment by ajcvickers** [comment] 2019-01-07 19:20
@smitpatel to find dupe.

**Comment by smitpatel** [comment] 2019-01-07 19:48
Duplicate of #11186

**Closed** 2022-10-16 13:46 UTC
Labels: customer-reported
