### ISSUE TITLE
Allow migrations bundle executable to run arbitrary script.

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#27701] opened 2022-03-25 08:31 UTC
I want migrations bundle to be able to run arbitrary SQL.

For example, I'd like to be able to drop database before running migrations. (need it for testing migrations as a step of CI/CD pipeline)

**Comment by ErikEJ** [comment] 2022-03-25 09:08
@voroninp Add a script step before running the bundle?

**Comment by voroninp** [comment] 2022-03-25 09:16
@ErikEJ Is it a question or proposal? I'd need a CLI tool to run that script, right?

**Comment by ErikEJ** [comment] 2022-03-25 09:42
Proposal - Azure DevOps has tasks for this, possibly GitHub actions also. (Depending on your RDBMS of course)

**Comment by roji** [comment] 2022-03-26 08:14
@voroninp you can already integrate arbitrary raw SQL inside specific migrations ([see docs](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#adding-raw-sql)). For SQL that isn't part of the migrations (like dropping a database), as @ErikEJ suggests this can be done outside of EF Core in a separate build step.

**Comment by ajcvickers** [comment] 2022-03-28 11:17
Duplicate of #24710.

**Comment by voroninp** [comment] 2022-03-28 11:37
@ajcvickers I am not sure this is the exact duplicate. I want it to be a part of CLI, not fixed one

`efbundle --connection "..." --command "..."`

**Comment by ajcvickers** [comment] 2022-03-28 11:40
@voroninp We will discuss, but I think its very unlikely that we will implement that. Bundles are designed to include (i.e. "bundle") the SQL that needs to be executed. Passing the SQL in on the command ling kind of defeats the purpose.

**Comment by ajcvickers** [comment] 2022-04-04 10:32
Discussed it triage; this is not something we are going to do.

**Closed** 2022-10-16 20:29 UTC
Labels: closed-out-of-scope, customer-reported
