### ISSUE TITLE
Support translating value objects that are using a converter

### ISSUE THREAD

**Issue by adampaquette** [dotnet/efcore#31994] opened 2023-10-08 02:51 UTC
### Context
We are using immutable value objects that wraps primitives with validations in our entities.

A value object (VO) could be represented as the following:
```c#
public record CustomerName
{
    public string Value { get; }

    public CustomerName(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ValidationException("CustomerName can't be empty.");
        }

        value = Normalize(value);

        if (value.Length > 100)
        {
            throw new ValidationException("CustomerName exceeds the maximum length of 100 characters.");
        }

        Value = value;
    }

    public static CustomerName From(string value)
        => new(value);

    public string Normalize(string value)
        => CultureInfo.CurrentCulture.TextInfo.ToTitleCase(value).Trim();
}
```
99% of our  VO are Domain Primitives, they only contain a single property and we don't want to treat them as complex objects, so we use converters in the configuration:
```c#
cb.Property(c => c.Name).HasConversion(name => name.Value, s => CustomerName.From(s));
```

### Actual use
To make a search query translate to Sql, we need to cast the VO as a `string` because the underlying property `Value` does not exist in the database and sometimes we have to cast as object before casting as string.
```c#
db.Customers.Where(c => ((string)c.FirstName).Contains(firstName.Value)));
```

### Expected use
We would like to be able to access the underlying property in the query as valid C# code and still generate the correct Sql.
```c#
db.Customers.Where(c => c.FirstName.Value.Contains(firstName.Value)));
```

I've made a test case here: https://github.com/adampaquette/efcore/pull/1
I would need guidance on how to achieve this.
Thank you

**Comment by roji** [comment] 2023-10-08 12:25
Duplicate of #10434

**Closed** 2023-10-11 16:33 UTC
Labels: customer-reported
