### ISSUE TITLE
Dropping a database throws InvalidOperationException after UserSecrets changes

### ISSUE THREAD

**Issue by mattrobineau** [dotnet/efcore#7859] opened 2017-03-12 06:29 UTC
I currently migrated from VS 2016 over to VS 2017. With the new EF tools, you must update the Startup.cs as mentioned in [this announcement](https://github.com/aspnet/Announcements/issues/223). Startup will now use the new `AddUserSecrets<Startup>()` method instead of `AddUserSecrets()`.

The following exception is thrown when trying to drop a database:

```
H:\Visual Studio Projects\Stories 2017\src\Stories>dotnet ef database drop -c StoriesDbContext

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.86
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Storage.IRelationalConnection'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextInfo(String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.GetContextInfoImpl(String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Storage.IRelationalConnection'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
```

### Steps to reproduce
This is the previously working Startup.cs with the changes to AddUserSecrets

```c#
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using SimpleInjector;
using SimpleInjector.Integration.AspNetCore;
using SimpleInjector.Integration.AspNetCore.Mvc;
using Stories.Data.DbContexts;
using Stories.Extensions;
using Stories.Services;

namespace Stories
{
    public class Startup
    {

        private Container container = new Container();

        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);

            if (env.IsDevelopment())
            {
                // For more details on using the user secret store see http://go.microsoft.com/fwlink/?LinkID=532709
                builder.AddUserSecrets<Startup>();

                // This will push telemetry data through Application Insights pipeline faster, allowing you to view results immediately.
                builder.AddApplicationInsightsSettings(developerMode: true);
            }

            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddApplicationInsightsTelemetry(Configuration);

            services.AddDbContext<StoriesDbContext>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

            services.AddMvc();

            services.AddSingleton<IControllerActivator>(new SimpleInjectorControllerActivator(container));
            services.AddSingleton<IViewComponentActivator>(new SimpleInjectorViewComponentActivator(container));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseSimpleInjectorAspNetRequestScoping(container);

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationScheme = "StoriesCookieAuthentication",
                LoginPath = new PathString("/auth/login"),
                AccessDeniedPath = new PathString("/auth/login"),
                AutomaticAuthenticate = true,
                AutomaticChallenge = true
            });

            container.Options.DefaultScopedLifestyle = new AspNetRequestLifestyle();

            InitializeContainer(app);

            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            // Todo: This has some setup to do so we can start monitoring
            // https://blogs.msdn.microsoft.com/webdev/2015/05/19/application-insights-for-asp-net-5-youre-in-control/

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }
            using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope())
            {
                serviceScope.ServiceProvider.GetService<StoriesDbContext>().Database.Migrate();                
            }

            app.SeedData();

            app.UseStaticFiles();

            // Add external authentication middleware below. To configure them please see http://go.microsoft.com/fwlink/?LinkID=532715

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");

                routes.MapRoute(
                    name: "story",
                    template: "story/{hashId}/{*slug}",
                    defaults: new { controller = "Story", action = "Index" }
                    );
            });
        }

        private void InitializeContainer(IApplicationBuilder app)
        {
            // Add application presentation components
            container.RegisterMvcControllers(app);
            container.RegisterMvcViewComponents(app);

            // Add application services.
            container.Register<IEmailSender, AuthMessageSender>(Lifestyle.Transient);
            container.Register<ISmsSender, AuthMessageSender>(Lifestyle.Transient);

            container.Register<IDbContext>(() => app.ApplicationServices.GetService<StoriesDbContext>());
            container.Register<IStoryService, StoryService>();
            container.Register<IAuthenticationService, AuthenticationService>();
            container.Register<IPasswordService, PasswordService>();
            container.Register<IUserService, UserService>();
            container.Register<ICommentService, CommentService>();
            container.Register<IVoteService, VoteService>();
        }
    }
}
```

DbContext

```c#
using Microsoft.AspNetCore.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Stories.Data.Entities;
using Stories.Data.Entities.Mappings;
using Stories.Extensions;
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Stories.Data.DbContexts
{
    public class StoriesDbContext : DbContext, IDbContext
    {
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Story> Stories { get; set; }    
        public DbSet<UserSettings> UserSettings { get; set; }
        public DbSet<Vote> Votes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }

        public StoriesDbContext()
        {

        }

        public StoriesDbContext(DbContextOptions<StoriesDbContext> options)
            : base(options)
        {
        }
        
        protected override void OnModelCreating(ModelBuilder builder)
        {
            // Remove Cascade Delete on all entities
            foreach (var relationship in builder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
            {
                relationship.DeleteBehavior = DeleteBehavior.Restrict;
            }
            
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);

            builder.RegisterEntityMapping<Comment, CommentMap>();
            builder.RegisterEntityMapping<Story, StoryMap>();
            builder.RegisterEntityMapping<User, UserMap>();
            builder.RegisterEntityMapping<Role, RoleMap>();
            builder.RegisterEntityMapping<UserRole, UserRoleMap>();
            builder.RegisterEntityMapping<Vote, VoteMap>();
        }

        public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            var time = DateTime.UtcNow;

            foreach (var entry in ChangeTracker.Entries().Where(e => e.Entity is ITimestamp && (e.State == EntityState.Added || e.State == EntityState.Modified)))
            {
                if(entry.State == EntityState.Added)
                {
                    entry.Property("CreatedDate").CurrentValue = time;
                }

                entry.Property("ModifiedDate").CurrentValue = time;
            }
            return await base.SaveChangesAsync(cancellationToken);
        }
    }
}
```

### Further technical details
EF Core version: <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.1" />
Database Provider:Microsoft.EntityFrameworkCore.SqlServer 1.1.1
Operating system: Win 10
IDE: 2017

**Comment by ajcvickers** [comment] 2017-03-13 20:44
@mattrobineau I have been unable to reproduce this issue with the code posted. One possibility is that somehow there are mismatched versions of the EF assemblies in your project. Can you check that everything is updated to 1.1.1? If the error persists, could you please provide a full project that reproduces the issue?

**Comment by mattrobineau** [comment] 2017-03-15 00:55
According to Nuget, everything is up to date. 
You can find the repo here.
https://bitbucket.org/mattrobineau/stories/branch/stories_vs2017

**Comment by mattrobineau** [comment] 2017-03-15 19:09
Removing the StoriesDbContext's default ctor has fixed the issue. 

I will close this issue since the problem has been resolved by remove the default ctor.
However, it would seem that the EF Core 1.1 tooling has introduced a bug that was not present in the EF Core 1.0 tooling.

**Comment by divega** [comment] 2017-05-08 06:02
I consider this a duplicate of #6826. A parameterless constructor should not cause this issue in 2.0.

**Closed** 2022-10-16 10:56 UTC
