### ISSUE TITLE
EF Core 2.2.4 Group By Still Being Evaluated Locally?

### ISSUE THREAD

**Issue by chobo2** [dotnet/efcore#19525] opened 2020-01-08 19:48 UTC
Hi

I am using "Microsoft.EntityFrameworkCore (2.2.4)" and I am seeing this "warning" in my log files

> The LINQ expression 'GroupBy(new <>f__AnonymousType95`2(Date = [x].CreatedDate.Date, EmployeeId = [x].EmployeeId), [x])' could not be translated and will be evaluated locally

My query looks like this

```
var groupedEvents = dbContext.EventTrackings
    .Where(x => // where clause )
    .GroupBy(x => new { x.CreatedDate.Date, x.EmployeeId })
    .OrderBy(x => x.Key.Date)
    .ToList();
```

I tried to removing CreatedDate to see if that was the problem but I am still getting it

> The LINQ expression 'GroupBy([x].EmployeeId, [x])' could not be translated and will be evaluated locally.

```
var groupedEvents = dbContext.EventTrackings
    .Where(x => // where clause )
    .GroupBy(x => x.EmployeeId )
    .OrderBy(x => x.Key.Date)
    .ToList();
```

I read here that after 2.1 this should not be happening: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.1

> Before version 2.1, in EF Core the GroupBy LINQ operator would always be evaluated in memory. We now support translating it to the SQL GROUP BY clause in most common cases.
> 
> This example shows a query with GroupBy used to compute various aggregate functions:

**Comment by ajcvickers** [comment] 2020-01-11 21:53
Duplicate of #17068

**Closed** 2022-10-16 18:04 UTC
Labels: closed-duplicate, customer-reported
