### ISSUE TITLE
Remote EF Core microservice based execution

### ISSUE THREAD

**Issue by GoNextGroup** [dotnet/efcore#20977] opened 2020-05-18 00:03 UTC
Hello.

Let's imagine that we use microservice architecture with EF Core, where some services use "shared" database (for example OrderDatabase, which is used by Business core microservice and Cargo filled microservice, nevermind).

So, I use DbContexts for connection to this database and, of course, I need to use atomic transactions here and caches.

But, now there is no distributed transactions / distribution lockers in EF Core, if I'm not mistaken.

So, I have 2 questions (small and big).

1) Will EF Core be realized distributed transactions and distributed lock for selected tables?
Let me explain my idea.
Imagine, that you need to read an information from 3 tables, analyze it and write information in 4th table. So, in this case you DO NOT need to lock 1st, 2nd, 3rd tables, just only 4th for read/write.
Sometimes it needs to lock tables for reading, sometimes for writing, sometimes both. Now there is no way to lock tables.

2) It will be great to have an ability to create one "entry point" for EF Core database microservice, which allows to execute/cache queries/results, lock tables and etc. 
For example,  AddDbContext can be realized as a proxy over, for example, gRPC service.
Will something like this be realized somewhen in the future?

Thank you. Hope, it's not too stupid.

**Comment by roji** [comment] 2020-05-18 12:25
@GoNextGroup the term "distributed transactions" usually refers to a single transaction spanning multiple *databases* (as opposed to tables). Transactions can always span multiple tables.

> Will EF Core be realized distributed transactions and distributed lock for selected tables?

You can start regular database transactions via EF Core, just like you can regardless of EF Core - [see the docs](https://docs.microsoft.com/en-us/ef/core/saving/transactions). What exactly transactions guarantee and how they are implemented depends on your chosen transaction isolation level, and your specific database (e.g. SQL Server, PostgreSQL). For example, SQL Server has two modes for the "read committed" isolation level - one implemented via locking, and another via snapshotting ([see this blog series for more info](https://sqlperformance.com/2014/07/t-sql-queries/isolation-levels)). In any case, if locking of any tables/rows are involved, this is something that the database will do for your implicitly - you typically aren't supposed to worry about this as a user. 

>  For example, AddDbContext can be realized as a proxy over, for example, gRPC service.

It would be good to have more details on exactly what you're looking for - it sounds like maybe you're looking for something like OData or GraphQL backed by EF Core. The EF team doesn't have any specific product product for this, though there are various projects in this direction.

**Comment by ajcvickers** [comment] 2020-06-01 16:39
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:25 UTC
Labels: closed-could-not-reproduce, customer-reported
