### ISSUE TITLE
Configure backing field in child object

### ISSUE THREAD

**Issue by johntyrrell** [dotnet/efcore#35060] opened 2024-11-07 13:55 UTC
We sometimes have a collection of objects and we would like to be able to add custom logic to the collection without having to make it automatically mutable and without having to write the logic in the parent class.

I know you can use a backing field to only expose a read only list.
But if we would like to add a new item and check for duplicates, we would need to add this logic to the parent.
For example:
```
public class Child
{
  public string Name { get; set; }
}

public class Parent
{
  private List<Child> _children;
  public IReadOnlyList<Child> Children => _children.AsReadOnly();

  public void AddChild(Child child)
  {
    if (!_children.Contains(child))
    {
      _children.Add(child);
    }
  }
}
```

We would like to move the logic of the list to a custom object like this:
```
public class Child
{
  public string Name { get; set; }
}

public class Parent
{
  public ChildCollection Children { get; } = new();
}

public class ChildCollection : IEnumerable<Child>
{
  private List<Child> _children;

  public void Add(Child child)
  {
    if (!_children.Contains(child)) // or whatever other logic is needed
    {
      _children.Add(child);
    }
  }

  public IEnumerator<Child> GetEnumerator() => _children.GetEnumerator();
}
```
We could then configure this in the Parent class configuration:
```
builder.Property(x => x.Children).HasField("Children._children");
```

What needs to be done:
- HasField needs to support object hierarchy. ex: "Children._children"
- The FieldInfo lookup based on the name needs to support this lookup. We could go all recursive, but then you would need to lookout for a stackoverflow. For now one level support would be a great improvement.
- Because ChildCollection is an IEnumerable we should be able to use it in Include/ThenInclude statements in queries.

**Comment by AndriySvyryd** [comment] 2024-11-07 21:57
Duplicate of https://github.com/dotnet/efcore/issues/2968
It would allow to use any custom logic for setting and getting

**Closed by AndriySvyryd** 2024-11-07 21:57 UTC
Labels: type-enhancement, customer-reported
