### ISSUE TITLE
EF Core with binary data

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#16753] opened 2019-07-25 22:20 UTC
I created 2 entities:
        [MaxLength(24)]
        public byte[] Array1 { get; set; }

[MaxLength(24)]
        public byte? [] Array2 { get; set; }

When trying to add a migration for SQL I got an error on the second array stating that a nullable byta array wasn't allowed.

Removing this, I had success.

Looking at array1 in the database, I see that EF has created a varbinary(24) NULL column.

Having told me it can't create a nullable binary, it then did it.
It also made the type a variable size, not fixed.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/641354/ef-core-with-binary-data.html
VSTS ticketId: 945237_
_These are the original issue comments:_

Visual Studio Feedback System on 7/12/2019, 02:22 AM (13 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by ajcvickers** [comment] 2019-07-25 23:56
Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can fully investigate.

**Comment by ajcvickers** [comment] 2019-08-02 15:04
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment] 2019-08-02 15:04
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:32 UTC
Labels: closed-could-not-reproduce, customer-reported
