### ISSUE TITLE
Exception : "The current TransactionScope is already complete", even when no explicit TransactionScope is used

### ISSUE THREAD

**Issue by akasgup** [dotnet/efcore#25351] opened 2021-07-28 15:22 UTC
## Bug
My application has received below exception which is transient in nature.
Frequency is very less (0.05%), thus issue is rarely reproducable.
I am not using TransactionScope anywhere in my code.

In my application's service layer, I do an async query on SQL through EFCore.
Exception occurred in ToListAsync(cancellationToken) line in MyAppService class (code given below).

Stacktrace suggests that EFCore tries to access the current TransactionScope but it was already complete.
There is no log entry in Interceptor ConnectionOpening code (code given below), for this unsuccessful call.

```
An exception occurred while iterating over the results of a query for context type 'MyApplication.MyAppDbContext'.
System.InvalidOperationException: The current TransactionScope is already complete.
   at System.Transactions.Transaction.get_Current()
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.OnFirstExecution()
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at MyApplication.MyAppService`2.GetAllAsync(CancellationToken cancellationToken)
```

### Configuration

Startup.cs
```C#
public void ConfigureServices(IServiceCollection services)
{
	// Configure DbContext	
	services.AddDbContext<MyAppDbContext>((provider, builder) => builder
		.UseSqlServer(
			ConnectionString,
			options => options.EnableRetryOnFailure(maxRetryCount: 5, maxRetryDelay: TimeSpan.FromSeconds(30), errorNumbersToAdd: null))
		.AddInterceptors(new MyAppDbConnectionInterceptor()));
	services.AddScoped<MyAppDbContext>();
	
	// Configure DbHandler	
	services.AddScoped<MyAppDbHandler>();
	
	// Configure Mapper	
	services.AddScoped(sp =>
	{
		return new AutoMapper.MapperConfiguration(cfg =>
		{
			cfg.AddProfile<MyAppMapperProfile>();
			cfg.AddDataReaderMapping();
		}).CreateMapper();
	});
	
	// Configure Service
	services.AddScoped<MyAppService>();
}
```

MyAppDbConnectionInterceptor.cs
```C#
public class MyAppDbConnectionInterceptor : Microsoft.EntityFrameworkCore.Diagnostics.DbConnectionInterceptor
{
	public override ValueTask<InterceptionResult> ConnectionOpeningAsync(DbConnection connection, ConnectionEventData eventData, InterceptionResult result, CancellationToken cancellationToken = default)
	{
		return this.SetAccessTokenAsync(connection, result);
	}

	public override InterceptionResult ConnectionOpening(DbConnection connection, ConnectionEventData eventData, InterceptionResult result)
	{
		return this.SetAccessTokenAsync(connection, result).GetAwaiter().GetResult();
	}

	private async ValueTask<InterceptionResult> SetAccessTokenAsync(DbConnection connection, InterceptionResult result)
	{
		if (connection is not SqlConnection sqlConnection)
		{
			return result;
		}
		
		// LogInformation("Got ConnectionOpening request, Setting AccessToken");
		// ((SqlConnection)connection).AccessToken = AccessToken;
		return result;
	}
}
```

### Code for DbContext, DbHandler, DbConfiguration and DbEntity

MyAppDbContext.cs
```C#
public class MyAppDbContext : Microsoft.EntityFrameworkCore.DbContext
{
	public MyAppDbContext(DbContextOptions options)
		: base(options)
	{
	}

	public IQueryable<MyAppDbEntity> AsQueryable()
	{
		return this.Set<MyAppDbEntity>();
	}

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.ApplyConfiguration(new MyAppDbEntityConfiguration());
	}

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		optionsBuilder.UseLazyLoadingProxies();
		base.OnConfiguring(optionsBuilder);
	}
}
```

MyAppDbHandler.cs
```C#
public class MyAppDbHandler
{
	private readonly MyAppDbContext context;

	public MyAppDbHandler (MyAppDbContext context)
	{
		this.context = context;
	}

	public IQueryable<MyAppDbEntity> GetAll()
	{
		return this.context.AsQueryable();
	}
}
```

MyAppDbEntityConfiguration.cs
```C#
public sealed class MyAppDbEntityConfiguration : IEntityTypeConfiguration<MyAppDbEntity>
{
	public void Configure(EntityTypeBuilder<MyAppDbEntity> builder)
	{
		builder.ToTable("MyAppEntity").HasKey(e => e.Id);
		builder.Property(e => e.DisplayName).IsRequired();
	}
}
```

MyAppDbEntity.cs
```C#
public class MyAppDbEntity
{
	public Guid Id { get; set; }

	public string DisplayName { get; set; } = null!;
}
```

### Code for Service, and Mapper

MyAppService.cs
```C#
public class MyAppService
{
	private AutoMapper.IMapper mapper;
	private MyAppDbHandler handler;
	
	public MyAppService(AutoMapper.IMapper mapper, MyAppDbHandler handler)
	{
		this.mapper = mapper;
		this.handler = handler;
	}

	public async Task<IList<MyAppExternalEntity>> GetAllAsync(CancellationToken cancellationToken = default)
	{
		return await this.handler.GetAll()
			.Select(e => this.Mapper.Map<MyAppExternalEntity, MyAppDbEntity>(e))
			.ToListAsync(cancellationToken);
	}
}
```

MyAppMapperProfile.cs
```C#
public class MyAppMapperProfile : AutoMapper.Profile
{
	public MyAppMapperProfile()
	{
		this.CreateMap<MyAppExternalEntity, MyAppDbEntity>()
			.ReverseMap();
	}
}
```

MyAppExternalEntity.cs
```C#
public class MyAppExternalEntity
{
	public Guid Id { get; set; }

	public string DisplayName { get; set; } = null!;
}
```

### Provider and version information

EntityFrameworkCore: 5.0.5
AutoMapper: 10.1.1
TargetFramework: net5.0
RuntimeIdentifier: win7-x64

**Comment by ajcvickers** [comment] 2021-07-30 18:36
@akasgup There is nothing obvious here that could be causing this. Are you using any other packages/dependencies that might be doing things with TransactionScope? Could you be using the same DbContext or DbConnection from multiple threads concurrently? Possibly by starting multiple async operations in parallel on the same context?

**Comment by akasgup** [comment] 2021-08-02 11:21
@ajcvickers Thanks for looking into this.

No, I don't have any dependency in my app which might affect TransactionScope. 
Apart from few AspNetCore :
```
Microsoft.ServiceFabric.AspNetCore.HttpSys Version=5.0.514
Microsoft.AspNetCore.OData Version=7.5.8
Microsoft.OData.Core Version=7.8.3
Microsoft.OData.Edm Version=7.8.3
```

DbContext has scoped lifetime, where I do a GetAll call and ToListAsync is the only async call for the http request.
Database table has a relation with other table and a foreign key setup. Ef core is expected to fetch the navigation entity in the same get call.

```
public class MyAppDbEntity
{
	public Guid Id { get; set; }
	public string DisplayName { get; set; } = null!;
	public Guid NavDbEntityId { get; set; }
        public virtual MyAppNavDbEntity NavDbEntity{ get; set; } = null!;
}
```
```
public sealed class MyAppDbEntityConfiguration : IEntityTypeConfiguration<MyAppDbEntity>
{
	public void Configure(EntityTypeBuilder<MyAppDbEntity> builder)
	{
		builder.ToTable("MyAppEntity").HasKey(e => e.Id);
		builder.Property(e => e.DisplayName).IsRequired();
		builder.Property(e => e.NavDbEntity)
                	.WithMany()
	                .HasForeignKey(e => e.NavDbEntityId);
	}
}
public sealed class MyAppNavDbEntityConfiguration : IEntityTypeConfiguration<MyAppNavDbEntity>
{
	public void Configure(EntityTypeBuilder<MyAppNavDbEntity> builder)
	{
		builder.ToTable("MyAppEntity").HasKey(e => e.Id);
		builder.Property(e => e.DisplayName).IsRequired();
	}
}
```

Logs from success scenario
```
[EntityFrameworkCore.Infrastructure] Entity Framework Core 5.0.5 initialized 'MyAppDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: using lazy-loading proxies 

[MyAppDbConnectionInterceptor] Got ConnectionOpening request, Setting AccessToken

[EntityFrameworkCore.Database.Command] Executed DbCommand (2ms) [CommandType='Text', CommandTimeout='30']
SELECT [i].[Id], [i].[NavDbEntityId], [i].[DisplayName], [n].[Id], [n].[DisplayName]
FROM [MyAppDbEntity] AS [i]
INNER JOIN [MyAppNavDbEntity] AS [n] ON [i].[NavDbEntityId] = [n].[Id]
```

Logs from failure scenario (current issue) 
```
[EntityFrameworkCore.Infrastructure] Entity Framework Core 5.0.5 initialized 'MyAppDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: using lazy-loading proxies 

[MyAppService_GetAllAsync] An exception occurred while iterating over the results of a query for context type 'MyApplication.MyAppDbContext'. System.InvalidOperationException: The current TransactionScope is already complete.
```

**Comment by ajcvickers** [comment] 2021-08-03 18:00
@akasgup I looked at this some more, but unfortunately I don't see anything that could be wrong, and without a way to reproduce what you are seeing I don't have any more ideas. I realize that creating a repro for this is likely very hard/impossible, but I think it's likely the only way to make progress.

**Comment by ajcvickers** [comment] 2021-08-12 16:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:41 UTC
Labels: closed-could-not-reproduce, customer-reported
