### ISSUE TITLE
SQL Server: Map array of primitives to separate table

### ISSUE THREAD

**Issue by bcallaghan-et** [dotnet/efcore#20614] opened 2020-04-13 19:48 UTC
Arrays of primitive values currently have no mapping or conversion applied to them by default, causing an error during model creation. I would like these properties to be mapped to their own table, just like collections of any other type would.

Here is my current workaround:
```cs
public class MyEntity
{
    public long[] Items { get; set; }
    public ICollection<PrimitiveWrapper<long>> ItemsCollection => Items.ToList();
}

[Owned]
public class PrimitiveWrapper<T>
{
    public PrimitiveWrapper(T value)
    {
        Value = value;
    }
    public T Value { get; private set; }
}
```
Note that the real `MyEntity` is auto-generated and largely outside of my control. I can add new properties (through a partial class) but I can't modify the original array property.

I would like the SQL Server provider to do this type of conversion for me or at least make it a global option I can turn on. The end result would be a sub-table consisting of a PK, FK to the original table, and a non-null column named Value. It may not be the "cleanest" or most "normalized" solution, but it seems to be the best option for working around the lack of arrays in SQL Server itself.

**Comment by ajcvickers** [comment] 2020-04-14 20:34
Duplicate of #4179

**Closed** 2022-10-16 18:20 UTC
Labels: closed-duplicate, customer-reported
