### ISSUE TITLE
Missing "using" into mymigration.Designer.cs and MyContextModelSnapshot.cs

### ISSUE THREAD

**Issue by berets76** [dotnet/efcore#11841] opened 2018-04-27 18:20 UTC
I added new property to an entity, run "add-migration MyMigration", migration was correctly created, but when i run "update-database" I got tons of errors

![image](https://user-images.githubusercontent.com/9038856/39377881-fe7fb99c-4a56-11e8-8d88-d8462da05cdf.png)

because MyMigration.Designer.cs and MyContextModelSnapshot.cs missing an using

![image](https://user-images.githubusercontent.com/9038856/39378138-c76a065a-4a57-11e8-916f-6dc5b7c449de.png)

precisely

> using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

Once added, "update-database" runs succesfully.

### Steps to reproduce
Run "add-migration" and "update-database"

### Further technical details
EF Core version: 2.1.0-preview2-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 64 bit
IDE: Visual Studio 2017 15.7.0 Preview 5

**Comment by smitpatel** [comment] 2018-04-27 21:08
Duplicate of #11806

**Closed** 2022-10-16 12:22 UTC
