### ISSUE TITLE
dbcontext scaffold - tables without primary key defined

### ISSUE THREAD

**Issue by 12michel34** [dotnet/efcore#5913] opened 2016-06-30 05:52 UTC
I tried to scaffold a dbcontext from a database from a 3th party vendor. Unfortunately the tables of this database have no primary key explicit defined. The scaffold command fails with:

Unable to identify the primary key for table 'abc'.
Unable to generate entity type for table 'abc'.

In the past we have connected to the database with edmx data-model and there was no problem. Is it possible to scaffold without primary key or to set a option on the command wich defines the primary key field?

**Comment by rowanmiller** [comment] 2016-06-30 17:39
Currently it is not supported. We would be tackling the ability to scaffold something without a key as part of https://github.com/aspnet/EntityFramework/issues/1679 (I realize your scenario is a table without a key, but it would be covered by that feature). In the meantime, you would need exclude that table from the reverse engineer, and then manually add the entity and specify the properties that EF should use as the key.

**Comment by hubert17** [comment] 2018-03-26 16:48
It's March 2018. 
[https://stackoverflow.com/questions/39701068/scaffold-dbcontext-creating-model-for-table-without-a-primary-key](https://stackoverflow.com/questions/39701068/scaffold-dbcontext-creating-model-for-table-without-a-primary-key?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

**Comment by talsuk5** [comment] 2018-08-15 19:45
@hubert17 , you're wrong, it's August 2018 😂
two years and counting?

**Comment by divega** [comment] 2018-08-30 13:49
@boris008 this issue was closed a long time ago, but we are tracking reverse engineering of views into query types in #1679 for EF Core 2.2. We can consider reverse engineering tables without primary keys in a similar fashion. cc @bricelam

**Comment by bricelam** [comment] 2018-08-30 22:29
Yes, I was going to tackle #5719 at the same time.

**Comment by darkguy2008** [comment] 2018-09-12 04:13
I'm facing the same issue, just got my project blocked due to this...

**Comment by KaeTar** [comment] 2018-10-11 20:05
Just need it to actually generate the model and throw a //TODO: in there indicating the need to define a key.   I am fine with it throwing an error still if you try to use a class that doesn't define the key.   But I am tired of hand creating models so I can manually define the key using attributes, it would be nice if the model existed so I could add the key attributes

**Comment by Elbeaux** [comment] 2018-10-16 22:54
> 
> 
> Just need it to actually generate the model and throw a //TODO: in there indicating the need to define a key. I am fine with it throwing an error still if you try to use a class that doesn't define the key. But I am tired of hand creating models so I can manually define the key using attributes, it would be nice if the model existed so I could add the key attributes

I agree!

**Comment by eltiare** [comment] 2018-10-25 17:57
I'm really not looking forward to generating dozens of 50+ tables by hand, many of which do not have primary keys defined. :(

**Comment by sirobert** [comment] 2018-11-27 11:55
What is the status of it?

**Comment by ajcvickers** [comment] 2018-11-27 16:49
@sirobert It's closed. See comments above.

**Comment by boris008** [comment] 2018-11-28 08:58
And solution? I need scaffold model from database structure and tables has no primary keys.

**Comment by OUANGDRAK78** [comment] 2019-01-15 11:08
Up, same for me...

**Comment by asinesi** [comment] 2019-02-25 16:17
Up, same for me....

**Comment by bricelam** [comment] 2019-02-25 18:53
Note, this issues was closed as a duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/5719

**Comment by rbonomo** [comment] 2019-08-08 22:02
You folks over at ****soft should really focus more on your customers and their needs.

**Comment by rodiaua** [comment] 2020-03-11 15:34
> Currently it is not supported. We would be tackling the ability to scaffold something without a key as part of #1679 (I realize your scenario is a table without a key, but it would be covered by that feature). In the meantime, you would need exclude that table from the reverse engineer, and then manually add the entity and specify the properties that EF should use as the key.

How can we exclude the table from the reverse engineer?

**Closed** 2022-10-16 09:48 UTC
Labels: closed-duplicate
