### ISSUE TITLE
Calling user defined function cosmos

### ISSUE THREAD

**Issue by anupdg** [dotnet/efcore#28014] opened 2022-05-12 11:18 UTC
Hello there,

I have two questions-

- I am trying to call a user-defined function in cosmos DB from entity framework core through DB context
- Also looking for an option to call ARRAY_CONTAINS through entity framework

My data access layer is as GraphQL.net => GraphQL.EntityFramework => EntityFrameworkCore.Cosmos => CosmosDb

Regards

**Comment by smitpatel** [comment] 2022-05-12 17:17
Duplicate of #15338

**Closed** 2022-10-16 20:34 UTC
Labels: closed-duplicate, customer-reported
