### ISSUE TITLE
Migrations bundle add a paramter to select the used schema

### ISSUE THREAD

**Issue by Bjego** [dotnet/efcore#31997] opened 2023-10-09 08:47 UTC
Hi, 
I'm suggesting a new parameter for the generated bundle executables to set a specific schema during the migration.

Right now, I can only set the connectionstring as a parameter to my bundle. When I'm using e.g. Oracle , I can't set the used schema via the connectionstring. When I now use an admin account for DDL - Updates - I have to create triggers, so that my schema is changed for that user (in oracle : user = schema).
It would be great, if I could switch the used schema for my migration just with a simple parameter (as long I haven't hardcoded any schemas in my DBContext / Migrations)

A new parameter like --schema="myschema"

So that I can run my migrations into a specific schema, with this command:
```bash
./efbundle --connection "$CONNECTIONSTRING" --schema="appDd"
```

**Comment by ajcvickers** [comment] 2023-10-12 11:09
Duplicate of #9965

**Closed** 2023-10-16 19:22 UTC
Labels: customer-reported
