### ISSUE TITLE
Query: double groupby with tracking throws in NRE in runtime

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#11916] opened 2018-05-04 23:16 UTC
Repro using IncludeTestBase model:

```
            using (var context = CreateContext())
            {
                var groups = 
                    context.Orders.Include(e => e.OrderDetails))
                    .GroupBy(o => new { o.OrderID, o.OrderDate })
                    .GroupBy(g => g.Key.OrderDate);

                var employee = async
                    ? await groups.ToListAsync()
                    : groups.ToList();
            }
```

problem is in the tracking logic: when we are looking at a grouping, we assume that it's elements are entities and try to track those - we should be checking recursively and inject `TrackGroupedEntities` into the first (innermost) group by in the query plan tree, instead of the outermost.

**Comment by smitpatel** [comment] 2019-09-05 03:10
Duplicate of #17068

**Closed** 2022-10-16 12:23 UTC
