### ISSUE TITLE
IProperty.GetColumnName() does not return the sql column name for complex types?

### ISSUE THREAD

**Issue by Wasserwecken** [dotnet/efcore#34215] opened 2024-07-12 08:21 UTC
Im not quite sure but I am expecting the sql column name when calling `IProperty.GetColumnName()`.
This behaviour never stats that but what else should the column name then be? Sorry if im wrong!

I noticed my code failing when I added an entity with a repeated complex type.
The prefix of the column names for the complex type properties is just missing.
I was expecting the same name as in the migration, or in the database.

![image](https://github.com/user-attachments/assets/c2ed94cd-dbbd-454c-940e-e412ed88ccf9)

### Include your code
```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using System.ComponentModel.DataAnnotations.Schema;


using (var ctx = new AppDbContext())
{
    ctx.Database.Migrate();
    ctx.Add(new Item() { Primary = new() { Whatever = "Foo" }, Secondary = new() { Whatever = "Bar" } });
    ctx.SaveChanges();
}


using (var ctx = new AppDbContext())
{
    var type = ctx.Set<Item>().EntityType;
    var props = type.GetFlattenedProperties();
    var names = props.Select(e => e.GetColumnName());

    foreach (var name in names)
        Console.WriteLine(name);

    var mapping = props.ToDictionary(e => e.GetColumnName(), e => e);
}


[ComplexType]
public class Info
{
    public string Whatever { get; set; }
}

public class Item
{
    public int Id { get; set; }
    public Info Primary { get; set; }
    public Info Secondary { get; set; }
}


public class AppDbContext : DbContext
{
    public DbSet<Item> Items { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder builder)
    {
        //builder.LogTo(Console.WriteLine, new[] { RelationalEventId.CommandExecuting }).EnableSensitiveDataLogging();
        builder.UseSqlite(@"Data Source=data.db;");
    }
}
```

### Include provider and version information

EF Core version: 8.0.7
Database provider: Microsoft.EntityFrameworkCore.SQLite
Target framework: .NET 8.0

**Comment by AndriySvyryd** [comment] 2024-07-12 22:55
Same root cause as #33458

The final column name is calculated in a later stage (when the model is finalized). Unfortunately, with the current convention infrastructure it would be prohibitively slow to calculate this while the model is being built.

Duplicate of https://github.com/dotnet/efcore/issues/9329

**Closed by AndriySvyryd** 2024-07-12 22:55 UTC
Labels: customer-reported
