### ISSUE TITLE
Migration generates bad columns for HasData

### ISSUE THREAD

**Issue by YeskaNova** [dotnet/efcore#20666] opened 2020-04-17 12:09 UTC
If you generate the migration for SqliteDbContext, and then try to Migrate, you'll have an IndexOutOfRangeException.

The issue is that in the migration, there are 7 columns but only 3 values ( it seems that Strings are not injected ) :
``` C#

            migrationBuilder.InsertData(
                table: "User",
                columns: new[] { "Id", "Email", "FirstName", "IsDeleted", "LastModifiedOn", "LastName", "Login" },
                values: new object[] { (short)1, false, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) });
```

### Steps to reproduce
``` C#
    public class User
    {
        public short Id { get; set; }
        public string Login { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime LastModifiedOn { get; set; }
    }
    public class SqliteDbContext : DbContext
    {
        public ISet<User> Users { get; set; }

        public SqliteDbContext(DbContextOptions options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>().HasData(new User() { Id = 1 });

        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            var sc = new ServiceCollection();
            sc.AddDbContext<SqliteDbContext>(op => op.UseSqlite("Data Source=database.db;"));
            using (var provider = sc.BuildServiceProvider())
            using (var scope = provider.CreateScope())
            {
                scope.ServiceProvider.GetService<SqliteDbContext>().Database.Migrate();

            }
        }
    }
    public class DbContextFactory : IDesignTimeDbContextFactory<SqliteDbContext>
    {
        public SqliteDbContext CreateDbContext(string[] args)
        {
            var sc = new ServiceCollection();
            sc.AddDbContext<SqliteDbContext>(op => op.UseSqlite("Data Source=database.db;"));
            var provider = sc.BuildServiceProvider();
            var scope = provider.CreateScope();
            return scope.ServiceProvider.GetService<SqliteDbContext>();
        }
    }
```

### Further technical details

EF Core version: 5.0.0-preview.4.20216.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) issue in both
Target framework: (e.g. .NET Core 3.0) 5.0
Operating system: Windows 10 Pro
IDE: (e.g. Visual Studio 2019 16.3) VS 2019

**Comment by ajcvickers** [comment] 2020-04-17 15:22
@YeskaNova The values of all the string properties in your seed entity (`new User() { Id = 1 }`) are null. Is there a reason you need nulls to be explicitly inserted here?

**Comment by YeskaNova** [comment] 2020-04-17 18:35
@ajcvickers I don't need explicit null insertion. I only need this migration to work, but it fails, you can give it a try, it throws an exception ( EF core 5.0 preview not 3.1 ). In my real project, not this repro, the exception was explicit about the fact that the columns.Count is different from the values.Count ( which is understandable, values is just an array of values, if it doesn't have the same size as columns array, there is no deterministic way to know which value go to which column ).

**Comment by ajcvickers** [comment] 2020-04-17 18:41
@YeskaNova Sorry, I was too quick jumping to a conclusion and missed that mismatch. This does look like a bug.

**Comment by AndriySvyryd** [comment] 2020-07-22 19:16
Duplicate of https://github.com/dotnet/efcore/issues/21244

**Closed** 2022-10-16 18:21 UTC
Labels: customer-reported
