### ISSUE TITLE
fails on _IncludeAsync

### ISSUE THREAD

**Issue by dvlkv** [dotnet/efcore#9449] opened 2017-08-17 20:13 UTC
```
Exception message:
Microsoft.EntityFrameworkCore.Query[100100]
      An exception occurred in the database while iterating the results of a query for context type 'Astral.CHS.Database.DatabaseContext'.
      System.NullReferenceException: Object reference not set to an instance of an object.

Stack trace:
at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.<_IncludeAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.<_ExecuteAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.<IncludeCollectionAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.<_IncludeAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.<_ExecuteAsync>d__8`1.MoveNext()

```

### Steps to reproduce
Make many includes into your query, filter it and try to get data. It would fail if your are using async methods.

```c#
query = query.Where(...);
query = query.Incude(...).ThenIncude(...);

            var entities = await query
                .OrderByDescending(a => a.CreationDate)
                .ToListAsync();
But if:

var entities = query
                .OrderByDescending(a => a.CreationDate)
                .ToList();
It Works
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10 Pro
IDE: Rider 2017.1

**Comment by smitpatel** [comment] 2017-08-17 23:03
Similar to #9306

**Comment by ajcvickers** [comment] 2017-08-18 19:30
@maumar It seems possible that this and #9306 are duplicates for the same unerlying cause as #9038. Can you check this?

**Comment by ajcvickers** [comment] 2017-08-18 19:34
Also, if they are not duplicates, then let's consider for patch as a separate issue.

**Comment by maumar** [comment] 2017-08-22 23:06
dupe of #9038

**Comment by ajcvickers** [comment] 2017-09-12 17:49
Hi @DiE-MaRMeLaDe. We are gathering information on the use of EF Core pre-release builds. You reported this issue shortly after the release of 2.0.0 RTM. It would be really helpful if you could let us know:

- Did you consider testing your code against the pre-release builds?
- Was there anything blocking you from using pre-release builds?
- What do you think could make it easier for you to use pre-release builds in the future?

Thanks in advance for any feedback. Hopefully this will help us to increase the value of pre-release builds going forward.

**Closed** 2022-10-16 11:16 UTC
