### ISSUE TITLE
is this a bug? changes not visible when using `AsNoTracking`

### ISSUE THREAD

**Issue by opensrcken** [dotnet/efcore#6954] opened 2016-11-07 09:17 UTC
### Steps to reproduce
```C#
var entity = await context.SomeEntity.Where(Q => Q.Id == Id).FirstOrDefaultAsync();
entity.SomeField = "changed value";
await context.SaveChangesAsync();

// same query, except without tracking
entity = await context.SomeEntity.AsNoTracking().Where(Q => Q.Id == Id).FirstOrDefaultAsync();

// assertion fails unexpectedly
Assert.Equal(entity.SomeField, "changed value");
```

### Further technical details

EF Core version: 1.0.0-preview2-final
Operating system: windows 10
Visual Studio version: VS 2015 Community

**Comment by ajcvickers** [comment] 2016-11-07 18:04
@opensrcken This does not repro for me. Executing those statements in that order will result in the assertion passing. Could you provide a full repro, perhaps in a console application?

**Comment by rowanmiller** [comment] 2016-11-14 19:03
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 10:41 UTC
