### ISSUE TITLE
Unexpected result for EF Core Include, Orderby and Take for one to many

### ISSUE THREAD

**Issue by Edward-Zhou** [dotnet/efcore#15541] opened 2019-05-01 05:24 UTC
Describe what is not working as expected.

### Steps to reproduce
`Model ` 

```
public class Entities
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual List<Children1> Children1 { get; set; }
    }
    public class Children1
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
```
`Test Data`
Entities
1 | N1
2 | N2
3 | N3
4 | N4
5 | N5
6 | N6
Child1 

1 | C1 | 1
-- | -- | --
2 | C2 | 1
3 | C3 | 2
4 | C4 | 2
5 | C5 | 3
6 | C6 | 3
7 | C7 | 4
8 | C8 | 4

`Query `

```
            var entities = await _appDbContext.Entities
                        .Include(p => p.Children1)
                        .OrderBy(p => Guid.NewGuid())
                        .Take(2)
                        .ToListAsync();

```
`Result`  
Unexpected result, sometimes, the children1 will return count as 0 even through the entities contains children1.

After checking the generated sql, it's  
```
DECLARE @__p_0 int = 2
SELECT TOP(@__p_0) [p].[Id], [p].[Name]
FROM [Entities] AS [p]
ORDER BY NEWID(), [p].[Id]

SELECT [p.Children1].[Id], [p.Children1].[EntitiesId], [p.Children1].[Name]
FROM [Children1] AS [p.Children1]
INNER JOIN (
    SELECT TOP(@__p_0) [p0].[Id], NEWID() AS [c]
    FROM [Entities] AS [p0]
    ORDER BY [c], [p0].[Id]
) AS [t] ON [p.Children1].[EntitiesId] = [t].[Id]
ORDER BY [t].[c], [t].[Id]
```
It splits the EF Core query to two queries which cause the `OrderBy(p => Guid.NewGuid())` generated different values in two queries.

**Comment by ajcvickers** [comment] 2019-05-03 21:44
This is a duplicate of #13082, which for relational providers will be fixed by #12098

**Closed** 2022-10-16 14:19 UTC
Labels: closed-duplicate, customer-reported
