### ISSUE TITLE
Remove-Migration command description

### ISSUE THREAD

**Issue by CeciAc** [dotnet/efcore#20380] opened 2020-03-20 13:41 UTC
@programista25 commented on [Fri Mar 20 2020](https://github.com/dotnet/EntityFramework.Docs.pl-pl/issues/5)

It would be nice if you write how to remove migration if it is created with output parameter. I've tried Remove-Migration -o "Migrations" but got this:
Remove-Migration : Parameter cannot be processed because the parameter name 'o' is ambiguous. Possible matches include: -OutVariable -OutBuffer.
At line:1 char:18
Could you update the description for such case?

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migracje — EF Core](https://docs.microsoft.com/pl-pl/ef/core/managing-schemas/migrations/?tabs=vs#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs.pl-pl/blob/live/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

---

@srvbpigh commented on [Fri Mar 20 2020](https://github.com/dotnet/EntityFramework.Docs.pl-pl/issues/5#issuecomment-601567766)

Hello, @programista25
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lajones** [comment] 2020-05-11 00:34
`Remove-Migration` is a Powershell command. As for all commands, it allows the PowerShell common parameters - [see here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-7) - that's what causes the error message you're seeing.

However for `Remove-Migration` these do nothing. If you'd like to see what options are available for `Remove-Migration` type `Get-Help Remove-Migration`. Also there is [documentation on this](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=vs).

In this case `Remove-Migration` should remove the last migration wherever it is - you should not need to specify `-o`. 

Using `Microsoft.EntityFrameworkCore.*` packages version 3.1.3 I am unable to reproduce your problem - the migration and snapshot files are both successfully removed, leaving an empty `CustomMigrationFolder` folder. Can you provide more detail about exactly what your setup is, especially what version of EF you are using, and preferably your project just before you run `Remove-Migration`. Thanks.

**Comment by programista25** [comment] 2020-05-11 13:55
Did you try to reproduce error if you have migrations in other folder that default? In my case, when I'm adding new migrations using `-o`, `Remove-Migration` doesn't remove any migration, but only reset model snapshot file to empty.

**Comment by lajones** [comment] 2020-05-11 15:27
@programista25 I followed the directions specified in [your comment above](https://github.com/dotnet/efcore/issues/20380#issuecomment-602427333). I.e. I did:

`Add-Migration InitialMigration -o "CustomMigrationFolder"`

followed by:

`Remove-Migration`

That directory is already a "folder other than the default" - so I'm not quite sure what you meant by that.

As I said - everything worked fine for me on 3.1.3. If there are other steps needed to set up the scenario or if you are using a different version of EF please let us know. If this is reproducible on your end then please construct a small project which shows the problem and send it to us.

**Comment by ajcvickers** [comment] 2020-06-05 17:40
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:17 UTC
Labels: closed-could-not-reproduce, customer-reported
