### ISSUE TITLE
NET Core 3.1 - Scaffold - Could not load file or assembly System.Runtime, Version=4.2.2.0

### ISSUE THREAD

**Issue by singhabhi17** [dotnet/efcore#22963] opened 2020-10-12 03:26 UTC
## File a bug
while scaffolding  getting the error 

![image](https://user-images.githubusercontent.com/71499140/95701821-3594ac00-0c68-11eb-82a0-9f1682b9d60a.png)

![image](https://user-images.githubusercontent.com/71499140/95701958-958b5280-0c68-11eb-9197-dee4e7f34883.png)

**Comment by AndriySvyryd** [comment] 2020-10-12 17:15
@bricelam

**Comment by bricelam** [comment] 2020-10-12 19:15
Could you share the csproj of WebApplication1? Does `-Verbose` provide any additional information?

**Comment by singhabhi17** [comment] 2020-10-13 04:06
Hi @bricelam 
The sample file is attached. 
Let me know how to resolve this issue.
thanks 
[ClassLibrary.zip](https://github.com/dotnet/efcore/files/5368867/ClassLibrary.zip)

**Comment by bricelam** [comment] 2020-10-13 15:57
Hmm... nothing obviously wrong in there. I'm afraid we're going to need a full repro to diagnose this.

**Comment by ajcvickers** [comment] 2020-10-23 16:21
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:04 UTC
Labels: closed-could-not-reproduce, customer-reported
