### ISSUE TITLE
System.Interactive.Async causes compile error for IAsyncEnumerable on .NET Core 3.0

### ISSUE THREAD

**Issue by jnm2** [dotnet/efcore#14239] opened 2018-12-23 05:09 UTC
If you reference the type IAsyncEnumerable in a .NET Core 3.0 project that references Entity Framework Core, System.Interactive.Async causes a compile error:

> CS0433 The type 'IAsyncEnumerable\<T>' exists in both 'System.Interactive.Async, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' and 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.0" />
  </ItemGroup>

</Project>
```

Is there any chance that this has already been addressed in a preview feed of Entity Framework Core or  System.Interactive.Async?

**Comment by divega** [comment] 2019-01-04 22:38
@jnm2 This is a point in time issue that should go away once we implement #12047. We haven't started on that yet, and we are still in fact discussing how we are going to approach it. 

It is possible that upgrading the System.Interactive.Async dependency to a newer version will be part of the solution, but even this isn't certain yet. 

In the meantime, you can use full namespace (or namespace aliasing) to deambiguate. I will close this issue as duplicate of #12047.

**Comment by smitpatel** [comment] 2019-01-04 22:40
This is how it is done in this repo
https://github.com/aspnet/EntityFrameworkCore/blob/master/Directory.Build.targets

**Comment by jnm2** [comment] 2019-01-04 23:35
@divega Great to know it's getting attention! No hurry since it's a preview. I'll subscribe to that issue so I know when the friction is gone for this project.

I don't think using a full namespace will disambiguate, by the way. This isn't the first time I'm had to hack up something just like https://github.com/aspnet/EntityFrameworkCore/blob/master/Directory.Build.targets and add extern aliases to loads of source files, so I now give that whole experience a very respectful berth.

**Comment by divega** [comment] 2019-01-07 22:14
@jnm2 you are right, namespace aliasing isn't enough. Thanks @smitpatel for the assist.

**Comment by holajan** [comment] 2020-01-14 11:39
I recently had similar problem, with my **netcoreapp3.1** project using **EntityFrameworkCore** (3.1.0) and **IAsyncEnumerable<T>** interface.
My build ended with this error:

> error CS0433: The type 'IAsyncEnumerable<T>' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

In my case the problem was caused by using **nuget restore** command (not dotnet restore) and I had **old version of nuget.exe**. Upgrading to latest nuget.exe fixed the build.

**Closed** 2022-10-16 13:45 UTC
Labels: customer-reported
