### ISSUE TITLE
Includes impacting on SQL generation

### ISSUE THREAD

**Issue by dneimke** [dotnet/efcore#3415] opened 2015-10-13 02:02 UTC
Forgive me if this is a naive question but, how does the in which Include statements are added impact the resultant query that is generated?  E.g.

Will this...

return DbSet.Where(predicate)
                .Include(e => e.AAA)
                .Include(e => e.BBB)
                .Include(e => e.CCC);

Always give the same result as this...

return DbSet.Where(predicate)
                .Include(e => e.CCC)
                .Include(e => e.AAA)
                .Include(e => e.BBB);

If so, are there any good articles that I can read to understand how to use Include statements effectively?

**Comment by whyi** [comment] 2015-10-13 17:15
I am curious too. Given that those two would returns the same results I would assume EF ends up generating the same SQL statements. (perhaps with WHERE and AND clauses) I think it's fair to assume that EF does its SQL generation and optimization based on the general use but if there's a specific case in which the order of the expression is important then we should think about it although I think user can always write raw SQL to handle it. Just my 2 cents.

**Comment by rowanmiller** [comment] 2015-10-13 22:59
It's really up to the query pipeline to work out the best thing to do. For the most part it doesn't really matter what order things are done in when it comes to joins or additional queries for related data, so you will generally see things applied in the order you specify them. Bottom line is that you shouldn't really need to worry about it though.

**Comment by dneimke** [comment] 2015-10-14 01:57
Thanks @rowanmiller.  A reason for asking is that I am experiencing a number of issues when using the latest (nightly) EF stuff where the Order of Includes is having a significant issue.  I was trying to understand how to determine whether this was an EF7 bug or whether it is expected behavior.

**Comment by maumar** [comment] 2015-10-14 03:00
@dneimke can you provide repro code (entities, dbcontext, and query used) so we can take a look? Order shouldn't matter

**Comment by dneimke** [comment] 2015-10-14 03:09
Thanks @maumar leave it with me and I will get you a repro.  Might take me a day to get it for you as I will need to create a smaller working demo from our production/dev model

**Comment by maumar** [comment] 2015-10-14 03:57
@dneimke no rush, I got plenty of bugs to work on in the meantime

**Comment by rowanmiller** [comment] 2015-10-14 15:49
Moving out of Discussion since it sounds like this may be a bug, we will triage once the repro is provided.

**Comment by whyi** [comment] 2015-10-14 17:11
Would there be an invitation for the triage? I would like to attend if there's no conflict with my schedule.

**Comment by rowanmiller** [comment] 2015-10-14 17:25
@whyi our triage meetings are just for a small group of folks from the EF team who decide on prioritization etc. to ensure we have a cohesive release.

**Comment by dneimke** [comment] 2015-10-15 05:23
@maumar, I'm really concerned that you will run out of items to work on!  :)

I've made a start but haven't yet been able to directly reproduce the inconsistent behavior.

    https://github.com/dneimke/EFLibrary/tree/develop

I will ping you when a repro is available.

**Comment by maumar** [comment] 2015-10-15 09:05
@dneimke sounds good, thanks

**Comment by maumar** [comment] 2015-10-15 22:50
Potentially related issue: https://github.com/aspnet/EntityFramework/issues/3180

**Comment by rowanmiller** [comment] 2015-10-16 22:16
@dneimke we're closing this one out for the moment since there is nothing for us to act on. If you find an issue that you can provide code to reproduce can you just open a new issue.

**Comment by dneimke** [comment] 2015-10-16 23:55
Thanks @rowanmiller, will do

**Closed** 2022-10-16 09:12 UTC
