### ISSUE TITLE
Autorollback doesn't work after upgrading to EF Core 3.0

### ISSUE THREAD

**Issue by MichalLechowski** [dotnet/efcore#18657] opened 2019-10-30 16:00 UTC
Project: WebAPI .NET Core 3.0
EF release: EF Core 3.0
Test framework: xUnit 2.4.1 (latest)
DB: MsSql 2016

The issue is Autorollback on scope dispose stopped working, it was working fine before upgrading to 3.0. The example code is here: [CLICK](https://github.com/xunit/samples.xunit/blob/master/AutoRollbackExample/AutoRollbackAttribute.cs)

It's used as attribute for Class or Method so it's simply:

```
[Fact]
[Autorollback]
public async Task TestMethod(){}
```

It used to rollback db changes after method ends, now it does nothing even though Dispose() method is called and there is no exceptions or any suspicious behavior. I've already asked xUnit team and they suggested reporting EF 3.0 issue. DB is a real one, not in-memory.

Is that a real issue or does 3.0 need some additional settings to make it work fine again?

**Comment by ajcvickers** [comment] 2019-10-30 16:21
@MichalLechowski What is the `Autorollback` attribute and where does it come from?

**Comment by smitpatel** [comment] 2019-10-30 18:42
@ajcvickers - It is coming from xunit. Runs some code before & after the test. The OP has link to the attribute if that helps in what processing it does and how it would work with EF.

**Comment by MichalLechowski** [comment] 2019-10-30 18:47
> 
> 
> @MichalLechowski What is the `Autorollback` attribute and where does it come from?

There's a link in the first post, start from there.



> 
> 
> @ajcvickers - It is coming from xunit. Runs some code before & after the test. The OP has link to the attribute if that helps in what processing it does and how it would work with EF.

Yep and it's pretty basic stuff, it simply creates instance of transaction scope before method and calls Dispose() on scope instance after method ends.

**Comment by ajcvickers** [comment] 2019-11-04 20:02
@MichalLechowski The attribute is working for me--my test code is below. In the test I update a value in the database, confirm that it has updated in the test. Without Rollback, the test fails the second time it is run. With rollback it can be run many times, indicating that the change was committed.

Can you please post a small, runnable project/solution that demonstrates the behavior you are seeing.

```C#
    public class UnitTest1
    {
        [Fact]
        [AutoRollback]
        public void Test1()
        {
            using (var context = new BloggingContext())
            {
                var x = context.Set<Blog>().Single();
                
                Assert.Equal(0, x.NotId);
                
                x.NotId = -99;

                context.SaveChanges();
            }
            
            using (var context = new BloggingContext())
            {
                var x = context.Set<Blog>().Single();
                
                Assert.Equal(-99, x.NotId);
            }
        }
    }
    
    /// <summary>
    /// Apply this attribute to your test method to automatically create a <see cref="TransactionScope"/>
    /// that is rolled back when the test is finished.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
    public sealed class AutoRollbackAttribute : BeforeAfterTestAttribute
    {
        TransactionScope scope;

        /// <summary>
        /// Gets or sets whether transaction flow across thread continuations is enabled for TransactionScope.
        /// By default transaction flow across thread continuations is enabled.
        /// </summary>
        public TransactionScopeAsyncFlowOption AsyncFlowOption { get; set; } = TransactionScopeAsyncFlowOption.Enabled;

        /// <summary>
        /// Gets or sets the isolation level of the transaction.
        /// Default value is <see cref="IsolationLevel"/>.Unspecified.
        /// </summary>
        public IsolationLevel IsolationLevel { get; set; } = IsolationLevel.Unspecified;

        /// <summary>
        /// Gets or sets the scope option for the transaction.
        /// Default value is <see cref="TransactionScopeOption"/>.Required.
        /// </summary>
        public TransactionScopeOption ScopeOption { get; set; } = TransactionScopeOption.Required;

        /// <summary>
        /// Gets or sets the timeout of the transaction, in milliseconds.
        /// By default, the transaction will not timeout.
        /// </summary>
        public long TimeoutInMS { get; set; } = -1;

        /// <summary>
        /// Rolls back the transaction.
        /// </summary>
        public override void After(MethodInfo methodUnderTest)
        {
            scope.Dispose();
        }

        /// <summary>
        /// Creates the transaction.
        /// </summary>
        public override void Before(MethodInfo methodUnderTest)
        {
            var options = new TransactionOptions { IsolationLevel = IsolationLevel };
            if (TimeoutInMS > 0)
                options.Timeout = TimeSpan.FromMilliseconds(TimeoutInMS);

            scope = new TransactionScope(ScopeOption, options, AsyncFlowOption);
        }
    }
}
```

**Comment by MichalLechowski** [comment] 2019-11-05 10:38
Ok, so your example is pretty basic and I guess it might work fine when context is retrieved inside test method. But that's just a guess. In my case there's a whole test setup and context is provided by Fixture.

Something like this (I can't copy/paste production code, sory) so I'll try to write something similar with crucial aspects:

```
[Collection("collectionname")]
public class TestClass
{

private readonly TestHostFixture _testHostFixture;

public TestClass(TestHostFixture testHostFixture)
{
     _testHostFixture = testHostFixture;
}

[Fact]
[AutoRollback]
public async Task TestSomething()
{
   var response = await testHostFixture.Client.PostAsync(path, object);
   Assert.Equal(HttpStatusCode.OK, response.StatusCode);
}

}
```

So that's how the test looks like but there's nothing special in it. But the test config might be something that causes the issue:

```
 public abstract class TestHostFixture : ICollectionFixture<WebApplicationFactory<IntegrationTestsStartup>>
    {
        public readonly HttpClient Client;
        public readonly DbContext Context;
        public readonly AppSettings AppSettings;
        public TestHostFixture(string userName, string password) //params here to use through other, specific classes (different kind of test users)
        {
            var factory = new CustomWebApplicationFactory();
            Client = factory.CreateClient();

            var user = new AuthenticateCommand()
            {
                UserName = userName, 
                Password = password
            };

            var jsoncontent = JsonConvert.SerializeObject(user);
            var httpcontent = new StringContent(jsoncontent, Encoding.UTF8, "application/json");
            var result = Client.PostAsync("/authenticateEndpoint", httpcontent);
            var token = JsonConvert.DeserializeObject<UserModel>(result.Result.Content.ReadAsStringAsync().Result);

            Client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token.Token);

            var provider = factory.Server.Host.Services;
            Context = provider.GetRequiredService<DbContext>();
            AppSettings = provider.GetRequiredService<AppSettings>();
        }
    }
```

where IntegrationTestsStartup is a class that inherits from app Startup, in a nutshell:
- sets new instance and get jsons, creates context:

```
public IntegrationTestsStartup(IHostingEnvironment env) :
            base(new ConfigurationBuilder()
                 .SetBasePath(env.ContentRootPath)
                 .AddJsonFile("appsettings.tests.json", optional: false, reloadOnChange: true)
                 .AddJsonFile("appsettings.tests.local.json", optional: true, reloadOnChange: true)
                 .AddEnvironmentVariables()
                 .Build())
        {
        }
```

```
services.AddDbContext<DbContext>(
                 options => options.UseSqlServer(Configuration.GetConnectionString("CONNSTRING"), b => b.MigrationsAssembly("MIGRATION_PROJECT"))
            );
```
- Applies migrations
- Seeds data + test data

```
  public override void SeedData(IServiceScope serviceScope)
        {
            base.SeedData(serviceScope); //base means Startup seed (system seed)
            new IntegrationTestData().SeedData(serviceScope.ServiceProvider.GetService<DbContext>()); //this is additional test data seed
        }
```

So that's pretty much it. Does this help?

**Comment by ajcvickers** [comment] 2019-11-05 17:31
@MichalLechowski The part that EF plays in all this seems very minimal--that is, EF enlists the connection into a transaction scope if one has been created. Currently I don't see anything indicating that that is not working. If you are able to create a small, runnable project/solution that demonstrates the behavior you are seeing, then we will investigate further.

**Comment by ajcvickers** [comment] 2019-11-15 17:32
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:53 UTC
Labels: closed-could-not-reproduce, customer-reported
