### ISSUE TITLE
Issue with Code First Approach

### ISSUE THREAD

**Issue by nilekshdhimer91** [dotnet/efcore#21603] opened 2020-07-13 10:38 UTC
I am try to create database things using Code first approach.

When I try to write following code with a Fluent API:

  
![image](https://user-images.githubusercontent.com/18172809/87295360-ad94ee00-c522-11ea-8c41-27cbdb41e2ac.png)

Here in above code I already wrote behavior for OnDelete rule. But when I am going to create new migration for it, then it will return(generate) following migration code:

![image](https://user-images.githubusercontent.com/18172809/87295542-02386900-c523-11ea-9d40-b1e6eb49d13c.png)

 

### Further technical details

EF Core version: 5 Preview 6.20312.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.3

**Comment by ajcvickers** [comment] 2020-07-24 15:50
@nilekshdhimer91 I have not been able to reproduce this. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2020-07-31 15:38
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:33 UTC
Labels: closed-could-not-reproduce, customer-reported
