### ISSUE TITLE
Support file-scoped namespace declarations in generated .cs files

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/efcore#25223] opened 2021-07-08 18:47 UTC
C# 10 introduces support for file-scoped namespace declarations and the [.NET 6 templates are being updated to use this new syntax ](https://github.com/dotnet/templating/issues/3359).

It would be great if the .cs files generated into the project by the EF tooling (`dotnet ef`) supported emitting namespaces using this new syntax. It could either:
- simply default to using the new syntax when the project targets .NET 6 (unless the project explicitly targets a lower version of C#)
- perhaps in addition sniff the content of .cs files in the project to determine which namespace declaration syntax the project is using and match that (e.g. match the first namespace declaration found in a .cs file with a depth-first search from project root)
- default to using the new syntax for .NET 6 targeted projects and support an option to opt-out of this behavior

**Comment by AndriySvyryd** [comment] 2021-07-09 17:25
Spec: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/file-scoped-namespaces.md

**Comment by bricelam** [comment] 2021-07-09 17:32
Do we even care about older versions of C#? Typically, we've treated the default C# version of EF's minimum TFM as the minimum required version of C# in our tools.

**Comment by DamianEdwards** [comment] 2021-07-09 18:10
What happens when I use `dotnet ef` 6.0 to add migrations to a project targeting .NET 5?

**Comment by bricelam** [comment] 2021-07-09 18:41
You'll get code generated by version 5.0 of the Microsoft.EntityFrameworkCore.Design package

**Comment by bricelam** [comment] 2021-07-09 18:42
(Assuming you're using EF Core 5 since EF Core 6 requires .NET 6)

**Comment by bricelam** [comment] 2021-07-09 18:44
Note also that if you're using EF Core 3.1 on .NET 6, you'll get code generated by EF Core 3.1. The version of dotnet-ef is largely irreleveant.

**Comment by DamianEdwards** [comment] 2021-07-09 18:57
Got it. That sounds great then. Are you suggesting then that perhaps migrations code should just be emitted using whatever language idioms we've decided are the most modern, and match what we've used in the project templates?

**Comment by bricelam** [comment] 2021-07-09 20:33
Yep! See also #14545

**Comment by AraHaan** [comment] 2022-03-06 00:07
I think another option is to do:
- add option ``--use-file-scoped`` for generating code from db (including the context)
- add option ``--global-using`` with the global usings the code normally adds on top of the generated code files to avoid them from being in the code files (but would require manually adding them with ``<Using Include="..." />``).

**Comment by roji** [comment] 2022-03-06 08:52
@AraHaan adding a switch for each and every possible code generation option isn't a good approach. Note that for EF Core 7.0, we plan to add [templating support](#4038), which would allow scaffolded models to be tweaked exactly as you want them. We'll likely make the default template modern (e.g. using file-scoped namespaces), but users would be able to tweak the template to remove one feature or another.

**Comment by ErikEJ** [comment] 2022-03-06 08:55
@AraHaan And there is Handlebars template support available today.

**Comment by DamianEdwards** [comment] 2022-03-09 18:51
FYI there's early plans to have `dotnet new` auto-invoke `dotnet format` after project creation which will format code according to the users' `editor.config` preferences (including things like file-scoped namespaces). We should likely think about a complimentary approach for the files generated by EF Core.

**Comment by roji** [comment] 2022-03-09 20:09
Our shiny new templates mechanism could somehow be aware of certain operation in .editorconfig and react accordingly?

**Comment by AraHaan** [comment] 2022-03-09 20:26
Wait the templates mechanism is now live?

**Comment by roji** [comment] 2022-03-09 20:27
Not quite, first support was has just been merged but the feature isn't yet complete.

**Comment by AraHaan** [comment] 2022-03-09 20:28
Cool, is there plans to add support for it for generating code for:
- stored procedures
- functions
- views

from the new templates feature as well?

**Comment by ErikEJ** [comment] 2022-03-09 20:48
@AraHaan views are supported. Sprocs and functions from SQL is possible in EF Core Power Tools.

**Comment by DamianEdwards** [comment] 2022-03-10 17:26
@roji it would simply need to call `dotnet format` after generating any code, or we leave that as an exercise for the user and simply ensure the emitted code matches the defaults elsewhere (VS templates, etc.).

**Comment by bricelam** [comment] 2022-04-26 18:42
Duplicate of #14545

**Comment by solrevdev** [comment] 2022-09-16 08:42
This is a closed issue but EF Core is not respecting my project and generating the older style namespacing when generating a migration or is this going to be a .NET 7 thing. 

Or is there anything I should be doing to make it work aka a command line flag etc.

Thanks all!

**Comment by ajcvickers** [comment] 2022-09-16 08:46
@solrevdev This is covered by [scaffolding templates](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#custom-reverse-engineering-templates) in EF7. If you are using EF7, then you should get file-scoped namespaces by default, but can edit the templates to do something different.

**Comment by solrevdev** [comment] 2022-09-16 08:48
> @solrevdev This is covered by [scaffolding templates](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#custom-reverse-engineering-templates) in EF7. If you are using EF7, then you should get file-scoped namespaces by default, but can edit the templates to do something different.

Ahh an EF7 thing. I will upgrade once its ready so for now I'll just fix manually no problem. Thanks so much for replying!

**Closed** 2022-10-16 19:39 UTC

**Comment by AraHaan** [comment] 2022-11-16 13:48
I feel like if you want to use file scoped namespaces that you must resort to doing database first.

**Comment by solrevdev** [comment] 2022-11-16 14:57
> @solrevdev EF7's templates covers database scaffolding (reverse engineering), not migration code. Modernizing migration C# code would be covered by #14545.
> 
> @AraHaan I definitely don't think that missing file-scoped namespace declarations is a good reason to abandon migrations or switch to database first.

Ahhh ok that makes sense! I’ll start watching the open issue #14545 

Thanks for clearing that up for me much appreciated 🙏
