### ISSUE TITLE
Invalid cast exception while performing updates inside transaction scope

### ISSUE THREAD

**Issue by shanmugam-siva** [dotnet/efcore#13422] opened 2018-09-26 21:25 UTC
Issue:
Invalid cast exception is thrown when we try to save multiple entities in a single transaction scope. It doesn’t occur consistently. It happens when entities are in the particular order.

```
Exception message: System.InvalidCastException: 'Unable to cast object of type 'TradeReportLineage' to type 'MarketTradeReportLineage'.'
Stack trace:
 at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.Remove(Object instance, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.RemoveFromCollection(InternalEntityEntry entry, INavigation navigation, IClrCollectionAccessor collectionAccessor, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 containingPrincipalKeys, IReadOnlyList`1 containingForeignKeys, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 keys, IReadOnlyList`1 foreignKeys, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectKeyChange(InternalEntityEntry entry, IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.PropertyChanged(InternalEntityEntry entry, IPropertyBase property, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.SetForeignKeyProperties(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, ISet`1 handledForeignKeys, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)

```

### Steps to reproduce
Consider following are the entities to be saved.
```
DataSet1 : {
	Id : 0,
    DataSetTypeId : 4,
    DataSetItems <MarketTradeReportDataSetItemVersion> : [ {
								Id: 1,
										Lineage<MarketTradeReportLineage> : [ { 
										DataSetItemId : 1,
										DataSetItemType : 4,
										SourceDataSetId : 2,
										SourceDataSetItemId : 1
										}
										]
                          }]
}


DataSet2 : {
Id : 2,
DataSetTypeId : 5,
DataSetItems <NormalisedTradeReportDataSetItemVersion> : [{
			Id: 1,
			Lineage<TradeReportLineage> : []
			}]
}
```
If we try to save the entities in the order of DataSet2 and DataSet1 , it throws an Invalid Cast Exception “Unable to cast object of type 'TradeReportLineage' to type 'MarketTradeReportLineage'.”. It works perfectly fine when it’s saved in the order of DataSet1 first and then DataSet2. 

Below is the full list of c# code to reproduce the issue.

```c#
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage;

namespace Test
{
       public abstract class BaseDataSet : IEntity
    {
        public virtual int Id { get; set; }
        public int SpecificationId { get; set; }

        public int DataSetTypeId { get; set; }

        public DateTime CreatedFor { get; set; }
    }

    public class DataSetVersion<TItemType> : BaseDataSet
        where TItemType : DataSetItemVersionBase
    {
        public virtual List<TItemType> DataSetItems { get; set; }
    }

    public class DataSetItemVersionBase : IEntity
    {
        public int Id { get; set; }
        public int DataSetId { get; set; }
   
    }

    public abstract class DataSetItemVersion<TLineage, TItem> : DataSetItemVersionBase
        where TLineage : IDataSetItemLineage<TItem>, new()
        where TItem : DataSetItemVersionBase
    {
        public IList<TLineage> Lineage { get; set; }
    }

    public sealed class NormalisedTradeReportDataSetItemVersion : DataSetItemVersion<TradeReportLineage, NormalisedTradeReportDataSetItemVersion>
    {
        public int Value { get; set; }
        public DataSetVersion<NormalisedTradeReportDataSetItemVersion> DataSet { get; set; }
    }

    public sealed class MarketTradeReportDataSetItemVersion : DataSetItemVersion<MarketTradeReportLineage, MarketTradeReportDataSetItemVersion>
    {
        public string Value { get; set; }
        public DataSetVersion<MarketTradeReportDataSetItemVersion> DataSet { get; set; }
    }


    public abstract class DataSetItemLineage  : IEntity
    {
        public virtual int Id { get; set; }

        public int DataSetItemId { get; set; }

        public int SourceDataSetId { get; set; }

        public int SourceDataSetItemId { get; set; }

    }

    public class MarketTradeReportLineage : DataSetItemLineage,
        IDataSetItemLineage<MarketTradeReportDataSetItemVersion>
    {
        public MarketTradeReportDataSetItemVersion DataSetItem { get; set; }
    }

    public class TradeReportLineage : DataSetItemLineage,
        IDataSetItemLineage<NormalisedTradeReportDataSetItemVersion>
    {
        public NormalisedTradeReportDataSetItemVersion DataSetItem { get; set; }
    }

    public interface IDataSetItemLineage<TItem>
    {
        TItem DataSetItem { get; set; }

        int SourceDataSetId { get; set; }

        int SourceDataSetItemId { get; set; }
    }

    public class BaseDataSetMapper : EntityMapper<BaseDataSet>
    {
        protected override void MapEntity(EntityTypeBuilder<BaseDataSet> entityBuilder)
        {
            entityBuilder.ToTable("DataSet", "dbo");

        }
    }


    public class NormalisedTradeReportDataSetItemEntityMapper : EntityMapper<NormalisedTradeReportDataSetItemVersion>
    {
        protected override void MapEntity(EntityTypeBuilder<NormalisedTradeReportDataSetItemVersion> entityBuilder)
        {
            entityBuilder.ToTable("NormalisedTradeReportDataSetItem", "dbo");

            entityBuilder.HasOne(e => e.DataSet)
                .WithMany(e => e.DataSetItems)
                .HasForeignKey(e => e.DataSetId)
                .HasConstraintName("FK_NormalisedTradeReportDataSetItem_DataSet");

            entityBuilder.HasMany(e => e.Lineage)
                .WithOne(l => l.DataSetItem)
                .HasForeignKey(e => e.DataSetItemId);
        }
    }

    public class MarketTradeReportDataSetItemEntityMapper : EntityMapper<MarketTradeReportDataSetItemVersion>
    {
        protected override void MapEntity(EntityTypeBuilder<MarketTradeReportDataSetItemVersion> entityBuilder)
        {
            entityBuilder.ToTable("MarketTradeReportDataSetItem", "dbo");

            entityBuilder.HasOne(e => e.DataSet)
                .WithMany(e => e.DataSetItems)
                .HasForeignKey(e => e.DataSetId)
                .HasConstraintName("FK_MarketTradeReportDataSetItem_DataSet");

            entityBuilder.HasMany(e => e.Lineage)
                .WithOne(l => l.DataSetItem)
                .HasForeignKey(e => e.DataSetItemId);
        }
    }

    public class DataSetItemLineageEntityMapper : EntityMapper<DataSetItemLineage>
    {
        protected override void MapEntity(EntityTypeBuilder<DataSetItemLineage> entityBuilder)
        {
            entityBuilder.ToTable("DataSetItemLineage", "dbo");

            entityBuilder.HasDiscriminator<int>("DataSetItemTypeId")
                .HasValue<MarketTradeReportLineage>(4)
                .HasValue<TradeReportLineage>(5);
            base.MapEntity(entityBuilder);
        }
    }



    public abstract class EntityMapper<TEntity> : IEntityMapper
        where TEntity : class, IEntity
    {
        public void Map(ModelBuilder builder)
        {
            var entityBuilder = builder.Entity<TEntity>();
            MapEntity(entityBuilder);
        }

        protected virtual void MapEntity(EntityTypeBuilder<TEntity> entityBuilder)
        {
            entityBuilder.Property(e => e.Id).ValueGeneratedOnAdd();
        }

    }

    public interface IEntity
    {
        int Id { get; set; }
    }

    public interface IEntityMapper
    {
        void Map(ModelBuilder builder);
    }


    public class DataSetSaveService<TItemType>
        where TItemType: DataSetItemVersionBase
    {
        protected DataBaseContext DbContext { get; }
        protected DataSetSaveService(DataBaseContext dbContext)
        {
            DbContext = dbContext;
        }
        public async void SaveDataSets(List<DataSetVersion<TItemType>> dataSets)
        {
            using (var tx = await DbContext.BeginTransactionAsync(IsolationLevel.Snapshot))
            {
                foreach (var dataset in dataSets)
                {
                    if (dataset.Id == 0)
                    {
                        DbContext.Set<DataSetVersion<TItemType>>().Add(dataset);
                    }

                    await DbContext.SaveChangesAsync();
                }
            }
        }
    }

    public class DataBaseContext: DbContext 
    {
        public virtual async Task<IDbContextTransaction> BeginTransactionAsync(IsolationLevel isolationLevel)
        {
            var tx = await Database.BeginTransactionAsync(isolationLevel);
            return tx;
        }
    }
}
```

### Further technical details
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 1.1
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment] 2018-09-27 16:00
@shanmugam-siva Can you post the code that creates DataSetSaveService and calls SaveDataSets?

**Comment by ajcvickers** [comment] 2018-10-05 17:50
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:32 UTC
Labels: closed-could-not-reproduce, customer-reported
