### ISSUE TITLE
Ef Core automatically includes collection causing performance issue due to response size

### ISSUE THREAD

**Issue by chukwu** [dotnet/efcore#16211] opened 2019-06-23 08:41 UTC
```
    public class EventInfo
    {
        [Key]
        public int EventInfoId { get; set; }

        public Customer Customer { get; set; }

        public int EventLocaleId { get; set; }
        [ForeignKey("EventLocaleId")]
        public LocaleInfo EventLocale { get; set; }

        public int EventTypeId { get; set; }
        [ForeignKey("EventTypeId")]
        public EventType EventType { get; set; }

        public List<EventActivity> EventActivities { get; set; } //Many to many relation

    }
```
The above model is a simple model but each time I query as below:
```
EventInfo eventInfo = await _appDbContext.EventInfoes
                .Include(i => i.EventActivities)
                    .ThenInclude(i => i.Activity)
                        .ThenInclude(i => i.Translations)
                .Include(i => i.EventActivities)
                    .ThenInclude(i => i.SelectedSupplier)
                        .ThenInclude(i => i.VendorLocale)
                .FirstOrDefaultAsync(f => f.EventInfoId == id);
```

EventLocale is always fetched without any INCLUDE but others such as EventType is set to null. Same happens when i drill down the eventActivities collection

```
eventInfo?.EventActivities.ForEach(item =>
            {
                    item.EventInfo = null;           //Parent element EventInFo is also fetched
                    item.SelectedSupplier.EventActivities = null;  // Parent element fetch also

            });
```

Is this an expected behavior.

**Comment by ajcvickers** [comment] 2019-06-24 16:19
Duplicate of #13577

**Closed** 2022-10-16 14:26 UTC
