### ISSUE TITLE
Change type of an existing column

### ISSUE THREAD

**Issue by seriouz** [dotnet/efcore#5843] opened 2016-06-23 18:35 UTC
I tried to change the type from a int to another class.

``` csharp
public class Permission
{
    public int PermissionId { get; set; }
    public int CreatedBy { get; set; }
}
```

to

``` csharp
public class Permission
{
    public int PermissionId { get; set; }
    public ApplicationUser CreatedBy { get; set; }
}
```

> System.InvalidOperationException: The property 'CreatedBy' cannot be added to the entity type 'Permission' because a navigation property with the same name already exists on entity type 'Permission'.

What is the way for changing column types?

**Comment by rowanmiller** [comment] 2016-06-24 18:33
@seriouz can you post the full stack trace for the exception.

**Comment by AndriySvyryd** [comment] 2016-08-18 23:36
@seriouz I wasn't able to reproduce the error. Could you provide the full model or a repro project?

**Comment by divega** [comment] 2016-08-19 18:12
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 09:46 UTC
Labels: type-bug, closed-could-not-reproduce
