### ISSUE TITLE
Index was outside the bounds of the array. .net core 2.0

### ISSUE THREAD

**Issue by Yoztastic** [dotnet/efcore#14491] opened 2019-01-23 12:06 UTC
Describe what is not working as expected.

On spinning up 4 services exact same binary on 4 linux instances one instance repeatedly throw the following exception, when a call resulted in a requirement to hydrate an entity from database.

`Index was outside the bounds of the array.` 

`   at bool System.Collections.Generic.Dictionary<TKey, TValue>.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at string Microsoft.EntityFrameworkCore.Metadata.Internal.Model.GetDisplayName(Type type)
   at EntityType Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FindEntityType(Type type)
   at Expression Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.EntityEqualityRewritingExpressionVisitor.RewriteNullEquality(ExpressionType nodeType, Expression nonNullExpression)
   at Expression Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.EntityEqualityRewritingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Expression System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Expression Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.EntityEqualityRewritingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at void Remotion.Linq.Clauses.WhereClause.TransformExpressions(Func<Expression, Expression> transformation)
   at void Remotion.Linq.QueryModel.TransformExpressions(Func<Expression, Expression> transformation)
   at void Microsoft.EntityFrameworkCore.Query.Internal.QueryOptimizer.Optimize(QueryCompilationContext queryCompilationContext, QueryModel queryModel)
   at void Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, bool asyncQuery)
   at void Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, bool asyncQuery)
   at Func<QueryContext, IAsyncEnumerable<TResult>> Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor<TResult>(QueryModel queryModel)
   at Func<QueryContext, TFunc> Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore<TFunc>(object cacheKey, Func<Func<QueryContext, TFunc>> compiler)
   at Task<TResult> Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync<TResult>(Expression query, CancellationToken cancellationToken)
   at Task<TResult> Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync<TResult>(Expression expression, CancellationToken cancellationToken)
   at Task<TResult> Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync<TSource, TResult>(MethodInfo operatorMethodInfo, IQueryable<TSource> source, CancellationToken cancellationToken)
   at Task<TSource> Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken)`

Restarting the service fixed the issue. So to reproduce would be hard. 

Using 
Microsoft.EntityFrameworkCore.Design (2.1.1)
Microsoft.EntityFrameworkCore.SqlServer (2.1.1)
Microsoft.Extensions.Configuration.json (2.0.1)
Microsoft.AspNetCore.All (2.0.7)

Seems real odd it is throwing on a TryInsert. 

Can't really expect a fix as it is not really broken but there must be some opportunity for non deterministic behaviour. Thought it worth putting here in case anyone experiences the same.

**Comment by ajcvickers** [comment] 2019-01-23 17:25
@Yoztastic Can you try running on .NET Core 2.1 or 2.2? .NET Core 2.0 is out of support.

**Comment by ajcvickers** [comment] 2019-01-30 18:07
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:48 UTC
Labels: closed-could-not-reproduce, customer-reported
