### ISSUE TITLE
ArgumentException: Invalid value for key 'attachdbfilename'.

### ISSUE THREAD

**Issue by hannespreishuber** [dotnet/efcore#13785] opened 2018-10-27 06:38 UTC
I try to use app_data dynamic attached database. As I can see from source code should be supported? Attachdbfilename with DataDirectory?

Visual Studio ASP.NET core Project EF 2.1 (actual)
appsettings.json
    "ConnectionString1": "Data Source=(localdb)\\mssqllocaldb;AttachDbFilename=|DataDirectory|\\rechnung.mdf;Integrated Security=True; MultipleActiveResultSets=True"

Startup.cs Startup
  string appRoot = Directory.GetCurrentDirectory();
   AppDomain.CurrentDomain.SetData("DataDirectory", Path.Combine(appRoot, "App_Data"));

configureservice
.AddDbContext<ModelRechnung>(options =>
            options.UseSqlServer(
                   Configuration.GetConnectionString("ConnectionString1"))
           );

Modelclass constructor
     public ModelRechnung(DbContextOptions<ModelRechnung> options):base(options)

Exception on program.cs
ArgumentException: Invalid value for key 'attachdbfilename'.

at 
  var context = services.GetRequiredService<ModelRechnung>();
   context.Database.EnsureCreated();

**Comment by ErikEJ** [comment] 2018-10-27 06:47
Maybe it only works with full .net framework?

**Comment by hannespreishuber** [comment] 2018-10-27 07:47
>           Maybe it only works with full .net framework?

I am really curios you are answering "Maybe" and have no glue

look at https://github.com/aspnet/EntityFrameworkCore/blob/a588722e10f34a12b9cea3d655fd26aafd91051b/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs#L669-L685

**Comment by bricelam** [comment] 2018-10-27 19:56
Dupe of dotnet/corefx#19492?

**Comment by hannespreishuber** [comment] 2018-10-29 09:37
@bricelam sure? what is the function ExpandFileName in the sqlserver lib code, shown before? 
I tried to get the step into F11 debugging working, to see what really happens at ensurecreated, but didnt work for me.
A overall issue is, keep versioning in track and changes. Works not in 2.0 can be solved in 2.1, who knows.

**Comment by bricelam** [comment] 2018-10-29 17:32
In other words, the EF code works as expected on .NET Framework, but SqlClient fails on .NET Core before that EF code has a chance to run.

**Comment by hannespreishuber** [comment] 2018-10-29 17:59
I am not a Github Guru, but is that issue a corefx issue? I would expect as EF SQLClient issue?

**Comment by ErikEJ** [comment] 2018-10-29 18:37
SqlClient is a CoreFx property, not owned by the EF team

**Closed** 2022-10-16 13:37 UTC
Labels: closed-external, customer-reported
