### ISSUE TITLE
Installing Microsoft.EntityFrameworkCore.Design on WinUI project breaks the project

### ISSUE THREAD

**Issue by marekt77** [dotnet/efcore#28631] opened 2022-08-09 01:04 UTC
I am using: 

Visual Studio 2022 ver: 17.2.6
Windows App SDK 1.1.3
Dot Net 6.0
Microsoft.EntityFrameworkCore.Design 6.0.7

I have my Win UI 3 app running fine.

I then install the NuGet package: Microsoft.EntityFrameworkCore.Design
It installs correctly.

When I go to run the app again, post package install, I get the following errors:

```
SeverityCodeDescriptionProjectFileLineSuppression State
ErrorAPPX1101Payload contains two or more files with the same destination path 'ProjectBookshelfWinUI3.deps.json'. Source files: 
C:\Users\mtyrp\source\repos\ProjectBookshelfWinUI3\ProjectBookshelfWinUI3\obj\x64\Debug\net6.0-windows10.0.19041.0\ProjectBookshelfWinUI3.deps.json
C:\Users\mtyrp\source\repos\ProjectBookshelfWinUI3\ProjectBookshelfWinUI3\bin\x64\Debug\net6.0-windows10.0.19041.0\ProjectBookshelfWinUI3.deps.jsonProjectBookshelfWinUI3C:\Users\mtyrp\.nuget\packages\microsoft.windowsappsdk\1.1.3\buildTransitive\[http://Microsoft.Build](https://t.co/pnXnH9NTml).Msix.Packaging.targets1479
SeverityCodeDescriptionProjectFileLineSuppression State

ErrorAPPX0002Task 'WinAppSdkRemovePayloadDuplicates' failed. Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
ProjectBookshelfWinUI3C:\Users\mtyrp\.nuget\packages\microsoft.windowsappsdk\1.1.3\buildTransitive\[http://Microsoft.Build](https://t.co/pnXnH9NTml).Msix.Packaging.targets1479
```

If I remove the NuGet package it runs again, no errors.

Any ideas why this is happening simply by installing a NuGet package?

**Comment by ajcvickers** [comment] 2022-08-11 13:21
Duplicate of #26973.

**Closed by ajcvickers** 2022-08-11 13:21 UTC
Labels: customer-reported
