### ISSUE TITLE
"Build failed" error message without useful information

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#29394] opened 2022-10-19 08:38 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Build-failed-error-message-without-use/10162175)._

---
Hello, Team!

When trying to use the Add-Migration command in Package Manager Console, I get a "Build Failed" error message without any additional info on what went wrong. Can you please fix this?

---
#### Feedback Bot on 10/3/2022, 10:25 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2022-10-19 08:41
Duplicate of #12654.

**Closed by ajcvickers** 2022-10-19 08:41 UTC
Labels: customer-reported
