### ISSUE TITLE
Support `Sum()` for `TimeSpan.Ticks`

### ISSUE THREAD

**Issue by aradalvand** [dotnet/efcore#27103] opened 2022-01-04 03:36 UTC
I was surprised to see there wasn't already-existing issue for this. Let me know if there is though, I couldn't find anything relevant.
Assume you have a property of type `TimeSpan` in an entity class, like so:
```csharp
public class Video
{
    public TimeSpan Duration { get; set; }
}
```
Also assume the following configuration:
```csharp
builder.Property(v => v.Duration)
    .HasConversion<long>();
```
Now, currently, if you want to get the sum of the durations of a number of videos, EF Core would throw an error telling you that the expression cannot be translated into SQL:
```csharp
long sumOfDurations = dbContext.Videos.Sum(v => v.Duration.Ticks);
```

Causes the following exception to be thrown:
```
System.InvalidOperationException: 'The LINQ expression 'DbSet<Video>()
    .Sum(e => e.Duration.Ticks)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'
```

While there's obviously a very straightforward way to translate this into SQL, since the database column corresponding to `Video.Duration` is in fact the number of ticks (a `bigint` or `long`), why not just treat every occurrence of the expression `video.Duration.Ticks` as equivalent to that column? So `.Sum(v => v.Duration.Ticks)` should simply be translated into the SQL `SUM` function:
```sql
SUM([l].[Duration])
```

**Comment by CaiusJard** [comment] 2022-01-04 09:29
As a workaround can you have a `long Ticks` field with a NotMapped property that `TimeSpan.FromTicks` it? Use one in your client side code and the other in your querying.. ?

**Comment by roji** [comment] 2022-01-04 09:38
Duplicate of #10434

**Comment by roji** [comment] 2022-01-04 09:41
@AradAral EF Core doesn't currently do translation of method/member calls when the type is value converted. It's certainly possible to translate the Ticks member to the value-converted long value, but consider that TimeSpan can be value-converted to any number of other types other than long (int, string...).

**Comment by roji** [comment] 2023-11-27 07:35
@lonix1 could you please open a separate issue with a minimal, runnable code sample? It's difficult to investigate based on an isolated query snippet, and you haven't even said which database you're using.

**Comment by roji** [comment] 2023-11-27 07:36
@ajcvickers does this track something other than #10434?

**Comment by roji** [comment] 2023-11-27 08:32
@lonix1 are you using a value converter on your Duration like the OP does?

**Comment by roji** [comment] 2023-11-27 08:37
@lonix1 then that's indeed unrelated to this. You probably want to take a look at https://github.com/npgsql/efcore.pg/issues/2339.

**Closed** 2023-11-30 13:21 UTC
Labels: closed-duplicate, customer-reported
