### ISSUE TITLE
Using FromSql and Include seems to render an inner join

### ISSUE THREAD

**Issue by johanskoldekrans** [dotnet/efcore#6392] opened 2016-08-23 11:01 UTC
This results in 10 returned rows:

``` C#
context.SomeTable.FromSql("Select top 10 * from SomeTable").ToList();
```

If I want to use a navigation property and include another table I seem to get an inner join that only returns rows that are in table SomeData:

``` C#
context.SomeTable.FromSql("Select top 10 * from SomeTable").Include(f => f.SomeData).ToList();
```

Is this behavior as designed? Can I somehow make it do a left join without rewriting it using the from-syntax?

EF Core version: 1.1.0-alpha1
Operating system: 
Visual Studio version: VS 2015

**Comment by smitpatel** [comment] 2016-08-23 16:00
Inner join or left join depends on if the nature of navigation `f.SomeData`. Can you share more info about your model?

**Comment by johanskoldekrans** [comment] 2016-08-23 17:54
I am out of office at the moment here in Sweden but it behaves as expected if I don't use FromSql. In this case I have a query that isn't suitable for linq and was surprised to even see the option to use Include. I can send for you tomorrow on the entities.

**Comment by johanskoldekrans** [comment] 2016-08-24 08:42
I have tried to make it anonymous and readable. Hopefully it is correct.

`public partial class SomeTable`
`{`
`public int AColumn { get; set; }`
`public int SomeDataID {get;set;}`
`public virtual SomeDataItem SomeData { get; set; }`
`}`

`modelBuilder.Entity<SomeTable>(entity =>`
            `{`
               ` entity.HasKey(e => new { e.AColumn })`
                   ` .HasName("PK_SomeTable");`

                `entity.HasOne(d => d.SomeData)`
                   ` .WithMany(p => p.SomeTable)`
                    `.HasForeignKey(d => d.SomeDataID)`
                    `.OnDelete(DeleteBehavior.Restrict)`
                    `.HasConstraintName("FK_SomeTable_SomeData");`
            `});`

**Comment by smitpatel** [comment] 2016-08-24 21:22
@johanskoldekrans - Thanks for detailed information. This is intended behavior.
There is one-to-many relationship between `SomeDataItem` & `SomeTable`. Foreign key property for this relationship is `SomeDataID` which is of non-nullable type `int`. Which means fk property cannot be null, hence `SomeTable` will always have `SomeDataItem` associated with it. Further the delete behavior is also set to `Restrict` so `SomeDataItem` cannot be deleted before all associated `SomeTable` are removed. Given that results of `INNER JOIN` & `LEFT JOIN` are essentially same. Since there is no missing keys in `SomeDataItem` (2nd query source).
If `SomeDataID` is of type `int?` then `Include` would produce `Left Join`.

Why do you want to produce a `Left Join`?

**Comment by johanskoldekrans** [comment] 2016-08-25 08:54
My first thought was that I made a mistake anonymizing the code but the second thought was much more terrifying. It is an old database not made by me and it has 0 (zero) values int the int column (SomeDataID) to imply a left join. The foreign key is a **nocheck** constraint which isnt reflected in the scaffolding. The FromSQL seems to handle this differently with includes than the .Where/.Include.

**Comment by johanskoldekrans** [comment] 2016-08-25 08:55
This is terrible database design and quite understandable if nocheck contraints isnt supported. I was shocked to see this was the case... I thought it was a nullable int. Sorry.

**Comment by divega** [comment] 2016-08-25 23:44
@johanskoldekrans I am closing this as by-design but in case it helps, some workarounds that come to mind:
1. Fix the schema, the data data in the database and the property in your object model to use null values to represent null values :smile:
2. Add a row on the principal side with the PK value of zero. This row will represent a null instance for this table.
3. Make the property `int?` so that EF Core starts producing LEFT OUTER JOINs. This won't fix the lack of referential consistence in the data but it should allow dependent rows that have an invalid FK values to be returned from queries.

**Comment by johanskoldekrans** [comment] 2016-08-26 14:41
@divega 1. Can't change since this is a big old database from our supplier 2. See 1 :-) 3. Did that as a workaround

However I still saw different behaviour by EF between .Where/.Include and .FromSql/.Include. But handling databases like this is almost impossible. I will copy the data I need to another database and scaffold from there instead. Thanks for the help and sorry for not checking this up better in the first place.

**Comment by divega** [comment] 2016-08-26 15:09
No worries! If you find unexpected differences between standard LINQ queries and `FromSql()` we would really appreciate if you could open a new issue.

**Closed** 2022-10-16 09:55 UTC
Labels: closed-by-design
