### ISSUE TITLE
HasQueryFilter not support DateTime

### ISSUE THREAD

**Issue by Wonderdch** [dotnet/efcore#18811] opened 2019-11-08 01:42 UTC
DateTime cann't convert to SQL correctly.

### Steps to reproduce
``` C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<PlanBasicInfo>()
        .HasQueryFilter(p => p.CheckDate >= Convert.ToDateTime("2019-01-01"));
}
```

SQL generated by EF Core
``` SQL
SELECT [p].[FBillNo], [p].[FCheckDate], [p].[FItemID], [p].[FNote], [p].[FPlanFinishDate], [p].[FAuxQty], [p].[FPlanCommitDate], [p].[FAuxQtyPass], [p].[FAuxStockQty], [p].[FWorkTypeID]
FROM [ICMO] AS [p]
WHERE [p].[FCheckDate] >= '2019-01-01T00:00:00.0000000'
```

### Error Trace

System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=从字符串向 datetime 转换时失败。
  Source=Core .Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Read()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Plan.MVC.Controllers.HomeController.Index() in F:\GitHub\ProductionPlan\Plan.MVC\Controllers\HomeController.cs:line 20
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()

### Further technical details

EF Core version:2.2.3-servicing-35854
Database provider:  Microsoft.SqlServer
Target framework: .NET Core 2.2
Operating system:Win7
IDE: Visual Studio 2017 15.9.17

**Comment by MintPlayer** [comment] 2019-11-08 13:14
```
class Program
{
    static void Main(string[] args)
    {
        using (var ctx = new BlogContext())
        {
            ctx.Database.EnsureDeleted();
            ctx.Database.EnsureCreated();
            var people = ctx.PlanInfos.ToList();
        }
    }
}

public class BlogContext : DbContext
{
    const string connection_string = @"Server=(localdb)\mssqllocaldb;Database=Issue18811;Trusted_Connection=True;ConnectRetryCount=0";
    public DbSet<PlanBasicInfo> PlanInfos { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(connection_string);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PlanBasicInfo>()
            .HasQueryFilter(p => p.CheckDate >= Convert.ToDateTime("2019-01-01"))
            .HasData(
                new PlanBasicInfo
                {
                    Id = 1,
                    CheckDate = new DateTime(2018, 7, 8)
                },
                new PlanBasicInfo
                {
                    Id = 2,
                    CheckDate = new DateTime(2018, 12, 8)
                },
                new PlanBasicInfo
                {
                    Id = 3,
                    CheckDate = new DateTime(2019, 1, 8)
                },
                new PlanBasicInfo
                {
                    Id = 4,
                    CheckDate = new DateTime(2019, 7, 8)
                });
    }
}

public class PlanBasicInfo
{
    public int Id { get; set; }
    public DateTime CheckDate { get; set; }
}
```

I'm however able to run this example:
- Target framework: .NET Core 2.2
- NuGet:
    - Microsoft.EntityFrameworkCore.SqlServer @ 2.2.3

Repository: https://github.com/MintPlayer/Issue18811

**Comment by smitpatel** [comment] 2019-11-08 15:27
@Wonderdch - Can you try 3.0 (or 3.1-preview2 release) from nuget. We believe this issue is fixed in 3.x release already.

**Comment by ajcvickers** [comment] 2019-11-08 17:57
Note for triage: SQL generated is now:
```sql
SELECT [p].[Id], [p].[CheckDate]
      FROM [PlanInfos] AS [p]
      WHERE [p].[CheckDate] >= '2019-01-01T00:00:00.0000000'

```

**Comment by ajcvickers** [comment] 2019-11-08 21:43
Further note: verified that if the column is mapped to something other than datetime2, then this now works in 3.1. 

```C#
class Program
{
    static void Main(string[] args)
    {
        using (var ctx = new BlogContext())
        {
            ctx.Database.EnsureDeleted();
            ctx.Database.EnsureCreated();
            var people = ctx.PlanInfos.ToList();
        }
    }
}

public class BlogContext : DbContext
{
    private static readonly ILoggerFactory Logger = LoggerFactory.Create(x => x.AddConsole());
    const string connection_string = @"Server=(localdb)\mssqllocaldb;Database=Issue18811;Trusted_Connection=True;ConnectRetryCount=0";
    public DbSet<PlanBasicInfo> PlanInfos { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(connection_string).UseLoggerFactory(Logger);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PlanBasicInfo>()
            .HasQueryFilter(p => p.CheckDate >= Convert.ToDateTime("2019-01-01"))
            .HasData(
                new PlanBasicInfo
                {
                    Id = 1,
                    CheckDate = new DateTime(2018, 7, 8)
                },
                new PlanBasicInfo
                {
                    Id = 2,
                    CheckDate = new DateTime(2018, 12, 8)
                },
                new PlanBasicInfo
                {
                    Id = 3,
                    CheckDate = new DateTime(2019, 1, 8)
                },
                new PlanBasicInfo
                {
                    Id = 4,
                    CheckDate = new DateTime(2019, 7, 8)
                });
    }
}

public class PlanBasicInfo
{
    public int Id { get; set; }
    
    [Column(TypeName = "datetime")]
    public DateTime CheckDate { get; set; }
}
```

```sql
SELECT [p].[Id], [p].[CheckDate]
FROM [PlanInfos] AS [p]
WHERE [p].[CheckDate] >= '2019-01-01T00:00:00.000'
```

**Comment by ajcvickers** [comment] 2019-11-08 21:46
Duplicate of #14095

**Closed** 2022-10-16 14:54 UTC
Labels: closed-duplicate, customer-reported
