### ISSUE TITLE
Ignore specific property in a query

### ISSUE THREAD

**Issue by steven62f** [dotnet/efcore#20747] opened 2020-04-24 18:46 UTC
I have an entity with a byte[] property to store photo. This entity is referenced by many others entities. When I request these other entities, I often have to include the entity that contains the photo, but in the end, I don't care about this photo. It is only used in very specific cases.

On one of my requests, I recover more than 4 MB of data. I added the "NoMapped" attribute on the photo property and the data volume went down to 200 KB. Unfortunately, the "NotMapped" attribute is not suitable. In some cases, I have to recover the photo data.

It would be very useful, during a request, to be able to ignore the retrieval of specific properties.

Ex - Retrieve all persons, all properties excepts Photo :
`_context.Persons.Ignore(p => p.Photo).ToListAsync()`

Ex - Retrieve all persons and associated Invoices, excepts photo inside :
`_context.Persons.Include(p => p.Invoices.Ignore(i => i.Photo)).ToListAsync()`

**Comment by smitpatel** [comment] 2020-04-24 18:48
Duplicate of #1387

**Closed** 2022-10-16 18:22 UTC
Labels: customer-reported
