### ISSUE TITLE
Compsite Keys with Byte types seem to be broken

### ISSUE THREAD

**Issue by eriksch2709** [dotnet/efcore#12999] opened 2018-08-14 18:45 UTC
I have a context with a join table where the join table is comprised of a composite foreign key and an Identity to form a many to many link. I can query each of the objects directly and get results back from the database without issue. However, when I use the join table and the Include() syntax to get a list of the objects in the many to many relation ship an InvalidCastException is throw. I have implemented these relationships before and the only differences here is the composite key and the usage of a Byte data type as the identity of one of the pieces of the composite key.

```
Exception message:

System.InvalidCastException: Unable to cast object of type 'System.Byte' to type 'System.Int32'.
   at Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer`1.GetHashCode(Object instance)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.CompositeValueFactory.CompositeCustomComparer.GetHashCode(Object[] obj)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Microsoft.EntityFrameworkCore.Query.Internal.WeakReferenceIdentityMap`1.Add(ValueBuffer& valueBuffer, Object entity)
   at Microsoft.EntityFrameworkCore.Query.Internal.WeakReferenceIdentityMap`1.Microsoft.EntityFrameworkCore.Query.Internal.IWeakReferenceIdentityMap.Add(ValueBuffer& valueBuffer, Object entity)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.GetEntity(IKey key, EntityLoadInfo entityLoadInfo, Boolean queryStateManager, Boolean throwOnNullKey)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.BufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.BufferedOffsetEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ContactManager.API.Services.ContactsRepository.GetBillingContact(Int32 id) in C:\Source\DotNetCore\ContactManager.API\ContactManager.API\Services\ContactsRepository.cs:line 31
   at ContactManager.API.Controllers.BillingCustomersController.GetBillingCustomer(Int32 id) in C:\Source\DotNetCore\ContactManager.API\ContactManager.API\Controllers\BillingCustomersController.cs:line 38
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
```c#
relevant  code:
JOIN Entity in context

builder.Entity<LocationAddresses>(entity =>
            {
                entity.ToTable("contact_location_addresses");
                entity.HasKey(e => new { e.ContactId, e.LocationContactId, e.LocationId, e.AddressTypeId });
                entity.HasOne(e => e.Contact);
                entity.HasOne(e => e.Location);
                entity.HasOne(e => e.AddressType);
                entity.HasOne(e => e.Address);

                entity.Property(e => e.ContactId).HasColumnName("contact_id");
                entity.Property(e => e.LocationContactId).HasColumnName("contact_id");
                entity.Property(e => e.LocationId).HasColumnName("location_id");
                entity.Property(e => e.AddressTypeId).HasColumnName("address_type").HasColumnType("tinyint");
                entity.Property(e => e.AddressId).HasColumnName("address_id");

            });

builder.Entity<Location>(entity =>
            {
                entity.ToTable("contact_locations");
                entity.HasKey(e => new { e.ContactId, e.Id });
                entity.HasOne(e => e.Contact)
                      .WithMany(cont => cont.Locations)
                      .HasForeignKey(loc => loc.ContactId);

                entity.Property(e => e.ContactId).HasColumnName("contact_id");
                entity.Property(e => e.Id).HasColumnName("location_id");
                entity.Property(e => e.LocationName).HasColumnName("location_name");
                entity.Property(e => e.InactiveDate).HasColumnName("inactive_date");
                entity.Property(e => e.Note).HasColumnName("note");
                entity.Property(e => e.IsPrimary).HasColumnName("is_primary");
                entity.Property(e => e.EmailAddress).HasColumnName("email_address");
                entity.Property(e => e.PrimaryPhoneNumber).HasColumnName("phone_number");
                entity.Property(e => e.SecondaryPhoneNumber).HasColumnName("secondary_phone_number");
                entity.Property(e => e.FaxNumber).HasColumnName("fax_number");
                entity.Property(e => e.ClaimsFaxNumber).HasColumnName("claims_fax_number");
                entity.Property(e => e.TwentyFourHrClaimNumber).HasColumnName("claim_24_hour_phone_number");
            });

builder.Entity<ContactBase>(entity =>
            {
                entity.ToTable("contact_master");
                entity.HasKey(e => e.Id);
                entity.HasOne(e => e.ContactType);
                entity.HasMany(e => e.Locations)
                      .WithOne(loc => loc.Contact)
                      .HasForeignKey(loc => new { loc.ContactId, loc.Id });

                entity.Property(e => e.Id).HasColumnName("contact_id");
                entity.Property(e => e.ContactTypeId).HasColumnName("contact_type");
                entity.Property(e => e.InactiveDate).HasColumnName("inactive_date");
                entity.Property(e => e.FileAs).HasColumnName("file_as");
                entity.Property(e => e.EnteredUserId).HasColumnName("entered_user_id");
                entity.Property(e => e.EnteredDate).HasColumnName("entered_date");
                entity.Property(e => e.DepartmentId).HasColumnName("department_id");
                entity.Property(e => e.TaxId).HasColumnName("tax_id");
                entity.Property(e => e.Tax1099Exempt).HasColumnName("tax_1099_exempt");
                entity.Property(e => e.Tax1099MergeContactId).HasColumnName("tax_1099_merge_contact_id");
                entity.Property(e => e.PayableType).HasColumnName("payable_type");
                entity.Property(e => e.Name1).HasColumnName("name_1");
                entity.Property(e => e.Name2).HasColumnName("name_2");
                entity.Property(e => e.Name3).HasColumnName("name_3");
                entity.Property(e => e.Note).HasColumnName("note");
                entity.Property(e => e.IndividualId).HasColumnName("indiv_id");
                entity.Property(e => e.ContactSearchName).HasColumnName("full_contact_name_search");
                entity.Property(e => e.WebsiteUrl).HasColumnName("website_url");
            });

builder.Entity<Address>(entity =>
            {
                entity.ToTable("addresses");
                entity.HasKey(e => e.Id);
                entity.HasOne(e => e.Country);

                entity.Property(e => e.Id).HasColumnName("address_id");
                entity.Property(e => e.Name1).HasColumnName("name_1");
                entity.Property(e => e.Name2).HasColumnName("name_2");
                entity.Property(e => e.Name3).HasColumnName("name_3");
                entity.Property(e => e.AddressLine1).HasColumnName("address_1");
                entity.Property(e => e.AddressLine2).HasColumnName("address_2");
                entity.Property(e => e.City).HasColumnName("city");
                entity.Property(e => e.State).HasColumnName("state");
                entity.Property(e => e.Zip5).HasColumnName("zip5");
                entity.Property(e => e.Zip4).HasColumnName("zip4");
                entity.Property(e => e.CountryCode).HasColumnName("country_code");
                entity.Property(e => e.County).HasColumnName("county");
                entity.Property(e => e.Township).HasColumnName("township");
                entity.Property(e => e.Latitude).HasColumnName("y_lat");
                entity.Property(e => e.Longitude).HasColumnName("x_long");
            });

Address.cs
public class Address
    {
        public int Id { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip5 { get; set; }
        public string Zip4 { get; set; }
        public string CountryCode { get; set; }
        public virtual Country Country { get; set; }
        public string County { get; set; }
        public string Township { get; set; }
        public float? Latitude { get; set; }
        public float? Longitude { get; set; }

    }

ContactBase.cs
public class ContactBase
{
        public int Id { get; set; }
        public byte ContactTypeId { get; set; }
        public virtual ContactType ContactType { get; set; }
        public DateTime? InactiveDate { get; set; }
        public string FileAs { get; set; }
        public int EnteredUserId { get; set; }
        public DateTime? EnteredDate { get; set; }
        public int? DepartmentId { get; set; }
        public string TaxId { get; set; }
        public bool Tax1099Exempt { get; set; }
        public int? Tax1099MergeContactId { get; set; }
        public int? PayableType { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Note { get; set; }
        public int? IndividualId { get; set; }
        public string ContactSearchName { get; set; }
        public string WebsiteUrl { get; set; }
        public virtual ICollection<Location> Locations { get; set; } = new List<Location>();


        public BillingSettings BillingSettings { get; set; }

}

Location.cs
public class Location
    {
        public int Id { get; set; }
        public int ContactId { get; set; }
        public virtual ContactBase Contact { get; set; }
        public string LocationName { get; set; }
        public DateTime? InactiveDate { get; set; }
        public string Note { get; set; }
        public bool IsPrimary { get; set; }
        public string EmailAddress { get; set; }
        public string PrimaryPhoneNumber { get; set; }
        public string SecondaryPhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string ClaimsFaxNumber { get; set; }
        public string TwentyFourHrClaimNumber { get; set; }

    }


LocationAddresses.cs
public class LocationAddresses
    {
        public int ContactId { get; set; }
        public virtual ContactBase Contact { get; set; }
        public int LocationId { get; set; }
        public int LocationContactId { get; set; }
        public virtual Location Location { get; set; }
        public byte AddressTypeId { get; set; }
        public virtual AddressType AddressType { get; set; }
        public int AddressId { get; set; }
        public virtual Address Address { get; set; }
    }

Calling the following results in NO error:
var contact = _context.LocationAddresses.Where(locAddr => locAddr.ContactId == id).ToList();

Calling the following results in the above error:
var contact = _context.LocationAddresses.Where(locAddr => locAddr.ContactId == id).Include(locAddr => locAddr.Location).ToList();

However, I can access a DbSet of the above included type without issue:
var location = _context.Locations.Where(loc => loc.ContactId == id).ToList();

I can even use the Include syntax on that DbSet:
var location = _context.Locations.Where(loc => loc.ContactId == id).Include(loc => loc.Contact).ToList();
```

### Further technical details
EF Core version: 2.1.2 But results are the same in 2.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7 Pro
IDE: Visual Studio 2017 15.7.5

**Comment by ajcvickers** [comment] 2018-08-15 19:27
@eriksch2709 With the code posted above, I get a model validation error: 
> The relationship from 'Location.Contact' to 'ContactBase.Locations' with foreign key properties {'ContactId' : int, 'Id' : int} cannot target the primary key {'Id' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.

Could you please post a runnable project/solution or complete code listing that builds the model successfully and then demonstrates the behavior you are seeing?

**Comment by eriksch2709** [comment] 2018-08-15 19:55
Yeah, forgive my ignorance as this is the first time I've engaged with an enterprise code base directly via github, but would it make it easier if I Zipped the relevant code files and attached them? Trying to copy it all might get a little messy.

**Comment by ajcvickers** [comment] 2018-08-15 20:12
@eriksch2709 Ideally simplify the repro code so that it only contains the parts that cause the issue--it's often more efficient for you to do that than us. If it can't be simplified, then the most important thing is that it runs and demonstrates the behavior. Attaching or posting is fine either way.

**Comment by ajcvickers** [comment] 2018-08-27 17:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:25 UTC
Labels: closed-could-not-reproduce, customer-reported
