### ISSUE TITLE
Warning about unpredictability when using Single() or equivalent operators is unclear

### ISSUE THREAD

**Issue by Hylaean** [dotnet/efcore#23939] opened 2021-01-22 17:36 UTC
While I understand the generated query fetches a max of two records and it doesn't necessarily has an order by, the result of the EF call is predictable as it either a single record or an exception, hence this warning can seem as a leaky abstraction and I've seen developers wonder about its origin.

"The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results."

It should be possible to examine the context with caused the query to be generated before emitting this warning, or modify the error message.

**Comment by ajcvickers** [comment] 2021-01-26 23:12
@Hylaean In what situations are you seeing this? (This should not be the behavior for Single except in some query-splitting cases.) Ideally, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Zero3** [comment] 2021-02-04 18:31
@ajcvickers happens to me too, with `builder.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery)` and basic queries like this:

````
return data.Set<User>()
	.Where(user => user.Id == id)
	.Include(user => user.Roles)
	.SingleOrDefault() ?? throw new Exception("User not found");
````

**Comment by Zero3** [comment] 2021-02-04 19:38
Seems like this is a duplicate of https://github.com/dotnet/efcore/issues/22579.

**Comment by Hylaean** [comment] 2021-02-05 10:43
Thanks

**Closed** 2022-10-16 19:19 UTC
Labels: closed-duplicate, customer-reported
