### ISSUE TITLE
Add OwnedNavigationBuilder.ToView()

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#15663] opened 2019-05-08 21:08 UTC
For completeness, we should let you call ToView on owned types.

Note, this also depends on the outcome of #14787

**Comment by AndriySvyryd** [comment] 2019-11-04 18:00
This is now a dupe of https://github.com/aspnet/EntityFrameworkCore/issues/17890

**Closed** 2022-10-16 14:20 UTC
Labels: closed-duplicate
