### ISSUE TITLE
Cannot use owned types for query types.

### ISSUE THREAD

**Issue by FilipVanBouwel** [dotnet/efcore#14265] opened 2018-12-29 14:44 UTC
I'm using DDD and have one domain that manages employees. Then I have another domain where I only want to read employees (separate class with a subset of employee properties), hence I'm using a DbQuery set in that domain. I'll keep it short and relevant and only add the first name and last name here. Then I have a DbContext that has a DbQuery set of employees.

````C#
public class Employee
{
	public string FirstName { get; set; }
	public string LastName { get; set; }
}

public class MyDbContext : DbContext
{
	public DbQuery<Employee> Employees { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.ApplyConfiguration(new EmployeeConfiguration());
	}
}

public class EmployeeConfiguration : IQueryTypeConfiguration<Employee>
{
	public void Configure(QueryTypeBuilder<Employee> builder)
	{
	}
}
````

Now I would like to use my Name value type that I also use in many other places because that already has a first and last name property and some utility methods. I would like to change my code to the following : 

````C#
public class Employee
{
	public Name Name { get; set; }
}

public class MyDbContext : DbContext
{
	public DbQuery<Employee> Employees { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.ApplyConfiguration(new EmployeeConfiguration());
	}
}

public class EmployeeConfiguration : IQueryTypeConfiguration<Employee>
{
	public void Configure(QueryTypeBuilder<Employee> builder)
	{
			builder.OwnsOne(e => e.Name).Property(e => e.FirstName);
			builder.OwnsOne(e => e.Name).Property(e => e.LastName);
	}
}
````

But EF Core won't let me do this because the QueryTypeBuilder does not have a OwnsOne method. I would like to see support added so we can use owned types (value types in DDD) on query types.

**Comment by ajcvickers** [comment] 2019-01-04 23:55
@FilipVanBouwel The main problem here is that owned entity types aren't really a great way to map DDD value objects, even though there is behavior overlap between the two. Mapping value objects as regular properties using type conversions is much closer semantically, and would work in this case, but is limited currently by #13947

The conceptual problem with using owned entity types here is that all entity types require a primary key to be defined, while query types explicitly do not have any primary key. Owned entity types can look like they don't have a key, which is why there is behavior overlap with value objects, but in fact they do have a key that is in part derived from the primary key of the owner entity type. But since the owner in this case is a query type, the mechanism falls down.

Closing this as a duplicate of #13947 since using that mechanism for value objects will be the best way to support this going forward.

**Comment by FilipVanBouwel** [comment] 2019-01-05 00:10
I personally don't like the solution from #13947 : you're duplicating the fields from the value object into every entity that uses that value object. I would much prefer to have a way to express a mapping from a property to multiple columns.

**Comment by ajcvickers** [comment] 2019-01-05 00:22
@FilipVanBouwel That's what #13947 is tracking. The examples shown in that issue are some of the things people are doing to workaround lack of support for this.

**Comment by FilipVanBouwel** [comment] 2019-01-05 00:30
I see. My solution atm is using a DbSet for the employee type in the domain that should only read them, but throwing an exception in SaveChanges if I see that someone is trying to add/modify/delete an employee. Every DbContext decides which entity types can be modified or only read.

**Closed** 2022-10-16 13:45 UTC
Labels: customer-reported
