### ISSUE TITLE
Query: projecting anonymous type containing entity and subquery returning a scalar results in N+1 queries

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#8083] opened 2017-04-05 22:18 UTC
Repro:

```
                var query = from g in ctx.Gears
                            where g.HasSoulPatch
                            orderby g.Nickname
                            select new { Gear = g, WeaponsCount = g.Weapons.Count };
```

produces:

```
SELECT [g].[Nickname], [g].[SquadId], [g].[AssignedCityName], [g].[CityOrBirthName], [g].[Discriminator], [g].[FullName], [g].[HasSoulPatch], [g].[LeaderNickname], [g].[LeaderSquadId], [g].[Rank]
  FROM [Gear] AS [g]
  WHERE [g].[Discriminator] IN (N'Officer', N'Gear') AND ([g].[HasSoulPatch] = 1)
  ORDER BY [g].[Nickname]
  
  @_outer_FullName: Damon Baird (Size = 450)
  
  SELECT COUNT(*)
  FROM [Weapon] AS [w0]
  WHERE @_outer_FullName = [w0].[OwnerFullName]
  
  @_outer_FullName: Marcus Fenix (Size = 450)
  
  SELECT COUNT(*)
  FROM [Weapon] AS [w0]
  WHERE @_outer_FullName = [w0].[OwnerFullName]
```

We should be able to produce a single query, and we do, if instead of gear we project it's properties individually.

**Comment by smitpatel** [comment] 2019-05-02 18:00
Duplicate of #11186

**Closed** 2022-10-16 11:00 UTC
Labels: closed-duplicate
