### ISSUE TITLE
Scaffold-DbContext in EF Core results are different from models from edmx ( using Database first approach)

### ISSUE THREAD

**Issue by geetmenon** [dotnet/efcore#26060] opened 2021-09-16 07:28 UTC
In EF 6, if I have a User table, a Role table and UserRole table (user can have many roles), when I had generated models from edmx (i.e. using Database first approach), I had ended up with
a) User Model with a collection of Roles, i.e.  `public virtual ICollection<Role> Roles { get; set; }`
b) Role Model with a collection of User, i.e. `public virtual ICollection<User> Users { get; set; }`

However in EF Core using Scaffold-DbContext with NoPluralize flag, I end up with
a) User Model with a collection of UserRoles, i.e. `public virtual ICollection<UserRole> UserRole { get; set; }`
b) Role Model with a collection of UserRoles, i.e. `public virtual ICollection<UserRole> UserRole { get; set; }`
c) UserRole Model with a navigation property to User and another one to Role, i.e. `public virtual Role Role { get; set; }` and `public virtual User User { get; set; }`

What is/are the parameter(s) I need to pass in Scaffold-DbContext in EF Core to get the same results as what I had got with EF 6?

Related to #25503

**Comment by roji** [comment] 2021-09-16 07:40
Duplicate of #22475

**Comment by roji** [comment] 2021-09-16 07:41
@geetmenon can you give 6.0.0-rc.1 a try? It should work as expected there.

**Closed** 2022-10-16 20:08 UTC
Labels: customer-reported
