### ISSUE TITLE
Best pratice for DB downgrade through efbundle in CI/CD

### ISSUE THREAD

**Issue by begerard** [dotnet/efcore#31637] opened 2023-09-05 18:54 UTC
I use the efbundle to automate the migrations of my database during deployment inside Azure Devops Release (but could be any other CD tool).

It works naturally to apply new migrations by comparing with the history table, but how can I handle the case of a version rollback that had migrations? The new efbundle will miss those migrations so it can't of course run the "Down" methods.

Is the best practice to put those database offline, manually call the "lastest" efbundle with the right "old" migration by argument (which is a source of dumb mistake), put the database online and then deploy the "old" version?

I'm looking at ways to automate or semi-automate this processus, as database downgrades are quite sensitive operations but are not considered in the documentation.

**Comment by roji** [comment] 2023-09-05 20:18
"Downgrading" a database schema is typically done through a new migration which reverts a previous one, i.e. that is the exact mirror image of it. In other words, if you'd like to undo a migration which added a column, add a new migration which removes that same column. Your normal flow of applying the latest migration would then automatically apply it.

Calling the Down methods is typically a manual process - not automated in CI/CD - execute because deployment failed in some way.

**Comment by begerard** [comment] 2023-09-06 08:46
Yes, I see how making a new migration is a good way to allow the CI/CD to handle this automatically, but when we want to quickly undo a bad deployment, the fastest and most prudent way seems to be to reuse the precedent artefact, not generating a new one.

It's tricky to revert a migration in a fully automated way because sometimes we will prefer to rollback the whole database with a backup, but most of the time the downgrade is the best solution. I know we can specify a migration by both it's name and it's rank from 0 (initial) to the bundle, but is it possible to have something like a negative number (rollback X migrations by targeting the "rank - X" migration) or even a comparison between two bundle (with a command like "current_artefact\efbundle.exe --rollbackTo old_artefact\efbundle.exe" and it will automatically downgrade to the latest migration of the old bundle)?

That would reduce the complexity of a rollback which would reduce the errors humans make in this sort of situation :)

**Comment by roji** [comment] 2023-09-06 09:25
Being able to say "update to the migration state before the last" (e.g. via a negative number) makes sense to me, and I think we've discussed this before - @bricelam do we have this tracked already somewhere? It would be a bit like `git checkout HEAD~1`.

**Comment by bricelam** [comment] 2023-09-07 17:24
#21615

**Comment by roji** [comment] 2023-09-08 11:22
Duplicate of #21615

**Comment by roji** [comment] 2023-09-08 11:22
@begerard I'm going to go ahead and close this as a duplicate of #21615, but feel free to continue posting here if you have further questions etc.

**Closed by roji** 2023-09-08 11:22 UTC
Labels: customer-reported
