### ISSUE TITLE
.Sum() should coalesce by default instead of returning NULL

### ISSUE THREAD

**Issue by fschlaef** [dotnet/efcore#17492] opened 2019-08-29 12:45 UTC
If you do an operation like this :

`.Select(i => 20 - i.Invoice.Sum(iv => iv.Amount))`

And `i.Invoice` is null, EF will translate as `20 - NULL` which in SQL is `NULL`. 
This should translate as `20 - 0` instead. 

This is an improvement from 2.0 where this would throw an `InvalidOperationException`, see https://github.com/aspnet/EntityFrameworkCore/issues/12520, but still not satisfying since now EF silently returns a wrong and unexpected result.

There is a workaround but it is convoluted :

`Select(i => 20 - ((double?)i.Invoice.Sum(iv => iv.Amount) ?? 0.0))`

We cast as `double?` to be able to use null-coalescing and now EF correctly wraps the expression in `COALESCE`. 

Tested on 3.0.0-rc1, full repro :

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace _17483Repro
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new MyContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
                context.Item.Add(new Item());
                context.SaveChanges();

                var badResult = context.Item
                    .Select(i => 20 - i.Invoice.Sum(iv => iv.Amount)) // Should return 20, but returns 0 because EF translates this as 20 - NULL which is 0 in SQL)
                    .FirstOrDefault();

                Debug.WriteLine("THIS QUERY IS NOT WORKING : " + badResult);

                // Workaround
                var goodResult = context.Item
                    .Select(i => 20 - ((double?)i.Invoice.Sum(iv => iv.Amount) ?? 0.0)) // By manually casting to nullable type and coalescing to 0, EF correctly COALESCEs the SUM expression
                    .FirstOrDefault();

                Debug.WriteLine("THIS QUERY IS WORKING : " + goodResult);
            }
        }
    }

    public class MyContext : DbContext
    {
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Item> Item { get; set; }

        private readonly ILoggerFactory logger = LoggerFactory.Create(c => c.AddDebug());

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            string connectionString = "Server=.;Database=Repro17483;Trusted_Connection=True;MultipleActiveResultSets=true";

            optionsBuilder.UseSqlServer(connectionString)
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(logger);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Invoice>(entity =>
            {
                entity.HasIndex(e => e.ItemFk)
                    .HasName("IX_Invoice_ItemId");

                entity.HasOne(d => d.ItemFkNavigation)
                    .WithMany(p => p.Invoice)
                    .HasForeignKey(d => d.ItemFk)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Invoice_Item_ItemId");
            });
        }
    }


    public partial class Invoice
    {
        public int Id { get; set; }
        public double Amount { get; set; }
        public int ItemFk { get; set; }

        public Item ItemFkNavigation { get; set; }
    }

    public partial class Item
    {
        public Item()
        {
            Invoice = new HashSet<Invoice>();
        }

        public int Id { get; set; }
        public ICollection<Invoice> Invoice { get; set; }
    }
}
```

### Further technical details
EF Core version: 3.0.0-rc1.19428.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 x64
IDE: Visual Studio 2019 16.3.0 Preview 2.0

**Comment by smitpatel** [comment] 2019-08-29 17:58
Duplicate of #12657

**Closed** 2022-10-16 14:38 UTC
Labels: customer-reported
