### ISSUE TITLE
using the in-memory database with multiple includes error

### ISSUE THREAD

**Issue by AntonioArnau** [dotnet/efcore#24338] opened 2021-03-08 08:22 UTC
The unittest using the in-memory database provider fails to execute the query when I have two level includes. The first level is include a collection then include a nullable navigation property

I get a  error: System.InvalidOperationException : The binary operator Equal is not defined for the types 'System.Nullable'1[System.Int32]' and 'System.Int32'.

Example: Class Charge, has Collection ChageDetails and ChargeDetails has a nullable navigation property Client
When I make a include (ChageDetails .Client)  it give the error.
In other examples when the navigation property is not nullable , there is no error

I use EF Core 5.0.3

Thanks in advanced

**Comment by AndriySvyryd** [comment] 2021-03-08 20:47
Please provide a small self-contained repro project that shows this issue,

**Comment by ajcvickers** [comment] 2021-03-15 16:06
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:26 UTC
Labels: closed-no-further-action, customer-reported
