### ISSUE TITLE
include navigation with inherit class

### ISSUE THREAD

**Issue by hi-xiaoxin** [dotnet/efcore#6215] opened 2016-08-01 02:40 UTC
hi : 

 i have three classes like this:

``` C#
class ClassBase { ...} 
class ClassA {  ClassOther1 NavigationA }
class ClassB {  ClassOther2 NavigationB }
```

in EFCore , I build model like this:

``` C#
builder.HasDiscriminator(m => m.Type).HasValue<ClassA>(...)
builder.HasDiscriminator(m => m.Type).HasValue<ClassB>(...)
```

it works well.

then,  i want get all EntityType ( typeof classbase) and include the navigation A/B  
`ctx.Set<ClassBase>().include( ...)`

i do not know how, and i tried

``` C#
ctx.Set<ClassBase>()
    .OfType<ClassA>().Include(m=>m.NavigationA)
    .OfType<ClassB>().Include(m=>m.NavigationB)
```

but it's error

I need help ,thank you!

xiaoxin

**Comment by divega** [comment] 2016-08-15 07:06
@xiaoxin1983 currently there is no supported way to write a single query that would include related entities for multiple derived types in the hierachy. 

Issue #3910 in the backlog represents an enhancement that could allow this.

In the meanwhile my recommendation is to use separate queries, e.g.:

``` C#
var as = ctx.Set<ClassBase>()
    .OfType<ClassA>().Include(m=>m.NavigationA).ToList();

var bs = ctx.Set<ClassBase>()
    .OfType<ClassB>().Include(m=>m.NavigationB).ToList();

```

**Comment by divega** [comment] 2016-08-15 07:06
Closing as duplicate of #3910.

**Closed** 2022-10-16 09:52 UTC
