### ISSUE TITLE
Perf regression in EF

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/efcore#16405] opened 2019-07-02 22:23 UTC
It seems a change went in today and regressed the Single Query performance for all the EF-involved scenarios:
![image](https://user-images.githubusercontent.com/34246760/60550530-2b51d700-9cdd-11e9-9e2f-6133f02d4239.png)

**Comment by ajcvickers** [comment] 2019-07-02 22:26
@roji Please add this to your existing perf work this week.

**Comment by DamianEdwards** [comment] 2019-07-02 22:48
Note that not all of those scenarios are EF, some use raw ADO.NET, and others use Dapper. So whatever's caused this is affecting all variants, not just EF.

**Comment by smitpatel** [comment] 2019-07-02 22:48
Where is the source code for those tests?

**Comment by DamianEdwards** [comment] 2019-07-02 22:49
https://github.com/aspnet/Benchmarks/tree/master/src/Benchmarks

**Comment by roji** [comment] 2019-07-03 10:41
The regression seems to have disappeared:

![image](https://user-images.githubusercontent.com/1862641/60584962-dff80100-9d8e-11e9-8047-2256806e4617.png)

It's pretty weird: the drop only shows on Linux+Physical, the others are pretty flat. It's also odd for only SingleQuery to regress, across raw/dapper/EF, but no other DB benchmarks to show anything.

I'd put my money on some unrelated environmental thing (some process inadvertently running at the same time as the benchmark?), but let's follow closely.

Closing for now unless anyone has any objections.

**Comment by roji** [comment] 2019-07-03 11:07
One more important note (@smitpatel and others): the TechEmpower tests are pinned to preview5 of EF Core, since we're running with Npgsql which does not constantly follow master branch - so nothing we currently do in EF Core would actually show up here. We do have the newish EF Core microbenchmarks tab in PowerBI which does follow continuous EF Core perf.

I typically sync up Npgsql every preview release, but didn't do it for preview6 (plan to do so for preview7 as soon as that's released).

**Closed** 2022-10-16 14:29 UTC
Labels: closed-could-not-reproduce
