### ISSUE TITLE
Question: Is it possible to include Exteded Delete / update queries

### ISSUE THREAD

**Issue by JanEggers** [dotnet/efcore#5094] opened 2016-04-17 09:47 UTC
Hi 

i think it would be a good idea to include 

https://github.com/loresoft/EntityFramework.Extended

delete / update query capabilities in this project

**Comment by rowanmiller** [comment] 2016-04-20 17:47
Duplicate of https://github.com/aspnet/EntityFramework/issues/795. Not currently supported, but on our backlog.

**Closed** 2022-10-16 09:36 UTC
