### ISSUE TITLE
EF Core 2.0 Possible regression when filtering results

### ISSUE THREAD

**Issue by gimatech** [dotnet/efcore#11341] opened 2018-03-20 11:48 UTC
Code that works fine in EF Core1.1.5 fails using EF Core 2.0.2 (same in 2.1 preview).
We are working on a 40+ projects solution with a lot of repositories.

Migrating from EF Core 1.1.x to 2.0.x we have found that a lot of our queries now are failing with a NullReferenceException, or missing data on our endpoints, due to Navigation properties not materialized when using a filter (Where clause) that cannot be translated in SQL, so executed locally.

Not sure if it is a bug, but I didn't find anything in the release notes related to this behavior change.

I add a SLN example with the exact same code running EF Core 1 or 2
[EF1vsEF2.zip](https://github.com/aspnet/EntityFrameworkCore/files/1829073/EF1vsEF2.zip)

The example is using the SQLite provider running an InMemory DB, but we use Azure SQL Databases in our project...with the same outcome.

Here is the Program.cs file (all needs self contained):
```c#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

namespace EF1
{
    static class Program
    {
        class Entity
        {
            [Key]
            public int EntityID { get; set; }

            public int StatusID { get; set; }

            [ForeignKey("StatusID")]
            [InverseProperty("Entities")]
            public virtual Status Status { get; set; }
        }

        class Status
        {
            [Key]
            public int StatusID { get; set; }

            [Required]
            public string Code { get; set; }


            [InverseProperty("Status")]
            public ICollection<Entity> Entities { get; set; }

            public Status()
            {
                Entities = new HashSet<Entity>();
            }
        }

        class AppDbContext : DbContext
        {
            public DbSet<Entity> Entities { get; set; }
            public DbSet<Status> Statuses { get; set; }
            public AppDbContext(DbContextOptions options) : base(options)
            {
            }
        }

        static async Task Main(string[] args)
        {
            var connection = new SqliteConnection("DataSource=:memory:");
            connection.Open();

            var options = new DbContextOptionsBuilder<AppDbContext>()
                .UseSqlite(connection)
                .Options;

            try
            {
                //Seed DB
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("EF CORE 1.1.5 Test");

                using (var ctx = new AppDbContext(options))
                {
                    ctx.Database.EnsureCreated();

                    var status = new Status { Code = "CODE VALUE" };
                    var entity = new Entity { Status = status };

                    ctx.Add(entity);
                    ctx.SaveChanges();
                }

                //Fetch data
                using (var ctx = new AppDbContext(options))
                {
                    var entities = await ctx.Entities
                        .Include(e => e.Status)
                        .Where(e => e.FakeFilterNotRenderedInSQL())
                        .ToListAsync();

                    foreach (var entity in entities)
                    {
                        Console.ForegroundColor = entity.Status == null ? ConsoleColor.Red : ConsoleColor.Green;
                        Console.WriteLine($"After Materialization -> Entity has ID: {entity.EntityID}, Status code: {entity.Status?.Code ?? "Not Materialized"}");
                        Console.ForegroundColor = ConsoleColor.White;
                    }
                }
            }
            finally
            {
                connection.Close();
            }

            Console.ReadKey();
            
        }

        static bool FakeFilterNotRenderedInSQL(this Entity entity)
        {
            Console.ForegroundColor = entity.Status == null ? ConsoleColor.Red : ConsoleColor.Green;
            Console.WriteLine($"Inside IQueryable<Entity>.Where clause -> Entity has ID: {entity.EntityID}, Status code: {entity.Status?.Code ?? "Not Materialized"}");
            Console.ForegroundColor = ConsoleColor.White;
            return true;
        }
    }
}
```
Here is the outputs:

![image](https://user-images.githubusercontent.com/8150414/37652349-83fd2364-2c3b-11e8-8f26-31cdf2fa40e7.png)

Our migration is in standby because identifying all code that could be impacted by that regression will need a significat amount of time and tests.

A workaround is to materialize the entities before filtering, but it is not a satisfying solution regarding all code needed to be modified.

Best regards.

**Comment by maumar** [comment] 2018-03-21 18:06
somewhat similar to https://github.com/aspnet/EntityFrameworkCore/issues/10471

**Comment by gimatech** [comment] 2018-03-21 18:45
@maumar Thank you for pointing me this issue #10471, I hadn't found it before posting mine.
This issue doesn't mention the version of EF Core, and it was closed "by design".
I can't really understand that something that seems to be a regression, at least for me, can be closed "by design" without a breaking change notification in the release notes...
I can understand if it is a decision taken for the sake of performances, but we, as users, don't have to learn it the hard way :-(
This was working in the previous version, and the worst part is that it fails only at runtime!
Our unit tests coverage is not perfect, we catch some errors but probably not all...which could be fine on a small project...our project is a little bit bigger :-)

What is proposed in the #10497 let me perplex...Statements like "would have a chance to..." usually don't fit well with software development and maintenance. I would prefer "have" or "not have" materialisation of Navigation Properties, by design, but be aware of new limitations.

**Comment by ajcvickers** [comment] 2018-03-22 02:54
@maumar Would you consider this a duplicate of #10471 or a separate issue?

**Comment by smitpatel** [comment] 2018-03-22 03:05
This should be duplicate of #10471
It may have worked in previous version accidently. We never tried to populate all navigations asked in include before falling back to client evaluation.

**Comment by divega** [comment] 2018-03-23 19:00
@maumar please add the reference to this scenario in the Include unification issue. Then you can close as duplicate.

**Comment by maumar** [comment] 2018-03-23 20:19
Correlated collection + include unification could help this scenario - problem currently is that we generate query plan for include before we know that client evaluation is needed. Unification will push that to VisitQueryModel phase, at which point we already know that predicate needs client evaluation and can come up with a different execution plan.

**Closed** 2022-10-16 12:14 UTC
Labels: closed-duplicate
