### ISSUE TITLE
Query: fails on combination of nav props filters

### ISSUE THREAD

**Issue by AlexBilonog** [dotnet/efcore#5940] opened 2016-07-01 17:36 UTC
Query fails on **_special_** combination of nav props filters:

```
            using (var db = new TheContext())
            {
                var searchText = "1";
                db.Set<PrincipalTable>()
                    .Where(a =>
                            a.NullableDependentTable1.Name.Contains(searchText)
                            || a.DependentTable2.Name.Contains(searchText)
                            || a.NullableDependentTable3.Name.Contains(searchText)
                            )
                    .ToList();

                // The same issue with similar queries like this:

                db.Set<PrincipalTable>()
                    .Where(a =>
                            a.NullableDependentTable1.Name == "1"
                            || a.DependentTable2.Name == "1"
                            || a.NullableDependentTable3.Name == "1"
                            )
                    .ToList();
            }
```

// Configuration (no matter: explicit configuration or by conventions like here):

```
    public class PrincipalTable : IEntity
    {
        public int ID { get; set; }
        public int? DependentTable1ID { get; set; }
        public int DependentTable2ID { get; set; }
        public int? DependentTable3ID { get; set; }

        public NullableDependentTable1 NullableDependentTable1 { get; set; }
        public DependentTable2 DependentTable2 { get; set; }
        public NullableDependentTable3 NullableDependentTable3 { get; set; }

        public void Configure(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PrincipalTable>(entity =>
            {
            });
        }
    }

    public class NullableDependentTable1
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }

    public class DependentTable2
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }

    public class NullableDependentTable3
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
```

**Exception**:

```
An unhandled exception of type 'System.InvalidCastException' occurred in Microsoft.EntityFrameworkCore.dll

Additional information: Unable to cast object of type 'System.Linq.Expressions.Expression`1[System.Func`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[EFGetStarted.ConsoleApp.Entities.PrincipalTable,System.Collections.Generic.IEnumerable`1[EFGetStarted.ConsoleApp.Entities.NullableDependentTable3]],EFGetStarted.ConsoleApp.Entities.NullableDependentTable3],System.Int32]]' to type 'System.Linq.Expressions.ConstantExpression'.

   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.QueryFlattener.Flatten(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index, Action baseVisitAction, MethodInfo operatorToFlatten, Boolean outerJoin)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitGroupJoinClause(GroupJoinClause groupJoinClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.GroupJoinClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFGetStarted.ConsoleApp.Program.Main() in C:\Work\Console4\EFGetStarted.ConsoleApp\Program.cs:line 16
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 8.1
Visual Studio version: 2015 Enterprise Update 3

**Comment by anpete** [comment] 2016-07-01 17:37
Dupe of #4539

**Closed** 2022-10-16 09:48 UTC
