### ISSUE TITLE
Seeding Owned Entity Type using HasData throws exception on Add-Migration

### ISSUE THREAD

**Issue by rkieslinger** [dotnet/efcore#17006] opened 2019-08-07 08:46 UTC
We want to seed some data using the `HasData` API. For simple entities it works great. But if we want to seed data for an entity with an `Owned Type`, we get the following exception, when we are executing the `Add-Migration` command:

```
System.ArgumentNullException: Value cannot be null.
Parametername: derivedType
   bei Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   bei Microsoft.EntityFrameworkCore.EntityTypeExtensions.IsAssignableFrom(IEntityType entityType, IEntityType derivedType)
   bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c__DisplayClass60_1.<StopTracking>b__0(INavigation n)
   bei System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StopTracking(InternalEntityEntry entry)
   bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Nullable`1 forceStateWhenUnknownKey)
   bei Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffData(TableMapping source, TableMapping target, DiffContext diffContext)
   bei Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<Diff>d__35.MoveNext()
   bei Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<DiffCollection>d__73`1.MoveNext()
   bei System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   bei System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   bei System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   bei System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   bei Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   bei Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IModel source, IModel target)
   bei Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   bei Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   bei Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   bei Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   bei Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   bei Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Value cannot be null.
Parameter name: derivedType
```

Unfortunately I couldn't reproduce the problem in a small sample project, so we debugged it to the point, where the exception gets thrown. The reason for the exception is, that in this line, the method `FindRuntimeEntityType` returns null:

https://github.com/aspnet/EntityFrameworkCore/blob/c2a39d700963f71c0035fa297aae6ec430578951/src/EFCore/ChangeTracking/Internal/StateManager.cs#L646

What I don't understand is, why this method searches our `Owned Type` in our entity types. Our `Owned Type` is a `DateRange`, which consists of two `DateTime` properties. Of course this type isn't an entity. But neither is your type `Name` an entity in your sample project, so why does it work there?

https://github.com/aspnet/EntityFramework.Docs/blob/8c89ca4ec2c7122af1525f94b833516f5719205d/samples/core/Modeling/DataSeeding/Name.cs#L3

### Further technical details
EF Core version: 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.1.6

**Comment by ajcvickers** [comment] 2019-08-07 15:44
@rolix7 Several issues in this area have been fixed since the 2.1 release. For example: #11969 #13276 #12211 #11984 #11969. Please try with 2.2.6, and if the problem persists, then please post a small, runnable project/solution or complete code listing that demonstrates the issue.

**Comment by rolix7** [comment] 2019-08-08 14:50
Thanks, we'll try that. But it can take a few weeks, because it's a huge enterprise solution. I'll report, if the problem is gone after switching to 2.2.6+.

**Comment by ajcvickers** [comment] 2019-08-16 16:13
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by rolix7** [comment] 2019-08-22 13:34
We dug a little bit deeper into ef core code and are now able to reproduce the issue. Here's the sample app: https://github.com/rzlsoftware/EFCoreDataSeedingOwnedTypesIssue

**Comment by ajcvickers** [comment] 2019-08-22 14:57
@rolix7 I have re-opened the issue so we can look at it again in triage.

**Comment by rkieslinger** [comment] 2019-08-28 08:10
After upgrading to the latest 3.0 previews (.net core and ef core) I get a different error:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: The model must be finalized before 'GetTypeMapping' can be used. Ensure that either 'OnModelCreating' has completed or, if using a stand-alone 'ModelBuilder', that 'FinalizeModel' has been called.
   at Microsoft.EntityFrameworkCore.PropertyExtensions.GetTypeMapping(IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SimplePrincipalKeyValueFactory`1..ctor(IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.KeyValueFactoryFactory.CreateSimpleFactory[TKey](IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.KeyValueFactoryFactory.Create[TKey](IKey key)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Key.<>c__19`1.<GetPrincipalKeyValueFactory>b__19_0(Key k)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Key.GetPrincipalKeyValueFactory[TKey]()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.KeyExtensions.GetPrincipalKeyValueFactory[TKey](IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMapFactoryFactory.CreateFactory[TKey](IKey key)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMapFactoryFactory.Create(IKey key)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Key.<>c.<get_IdentityMapFactory>b__18_0(Key k)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Key.get_IdentityMapFactory()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.KeyExtensions.GetIdentityMapFactory(IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateIdentityMap(IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.Microsoft.EntityFrameworkCore.Update.IUpdateEntry.set_EntityState(EntityState value)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.TrackData(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(IModel source, IModel target, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation.
```

**Comment by ajcvickers** [comment] 2019-09-06 16:26
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:34 UTC
Labels: closed-could-not-reproduce, customer-reported
