### ISSUE TITLE
NullReferenceException using .Select with Aliased Column

### ISSUE THREAD

**Issue by SecretivePerson** [dotnet/efcore#16192] opened 2019-06-21 11:34 UTC
NullReferenceException thrown in TypedRelationalValueBufferFactoryFactory.CacheKey.GetHashCode() when doing .Select()

I'm not permitted to release our code, but the following should replicate:

```C#
public class ExampleClass
{
        [Column("Column With Space")]
        public string Column_With_Space { get; set; }
}

public partial class ExampleContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Query<ExampleClass>();
    }
    public virtual IQueryable<ExampleClass> ExampleQuery()
    {
        return Query<ExampleClass>().FromSql("exec sp_ExampleQuery");
    }
    public void ThrowAnException()
    {
        var err = ExampleQuery().Select(obj=> new { MyField=obj.Column_With_Space }).ToList();
    }
}
```

I have fixed this locally by amending CreateValueBufferFactory in Microsoft.EntityFrameworkCore.Query.Sql.Internal.FromSqlNonComposedQuerySqlGenerator.

In this method, if the expression is not a column expression, it is left as null, and later throws an exception.
While debugging, the column with spaces was an AliasExpression, rather than a ColumnExpression.

My solution was to amend

`if (SelectExpression.Projection[i] is ColumnExpression columnExpression)`

to

```C#
var expression = SelectExpression.Projection[i];
if (expression is AliasExpression aliasExpression)
{
    expression = aliasExpression.Expression;
}
if (expression is ColumnExpression columnExpression)
```

I am using 2.2, but the code seems to be the same in 3.0.

**Comment by smitpatel** [comment] 2019-06-21 15:51
@SecretivePerson - Please share full repro code for the issue you are seeing. 3.0 the code is there but not used in query pipeline anymore. So at least for querying, the underlying issue is non-existent.

**Comment by ajcvickers** [comment] 2019-06-28 15:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:26 UTC
Labels: closed-could-not-reproduce
