### ISSUE TITLE
API throwing has exited with code 3221225477 (0xc0000005) 'Access violation'

### ISSUE THREAD

**Issue by Gregory-Lange** [dotnet/efcore#34251] opened 2024-07-19 15:15 UTC
When I do an .Include for a table it is throwing an access violation error.  I have run the SQL that EF uses directly on the server and it runs and returns just fine but in the application it does not.  I can't give out the exact tables but below is the gest of what I am doing.  I cannot use a joining table due to other data needed to be on that "joining" table.

Table breakdown
person:
Id Uniqueidentifier PK NOT NULL
FirstName nvarchar(75)
LastName nvarchar(75)

Clinician:
Id Uniqueidentifier PK NOT NULL
FirstName nvarchar(75)
LastName nvarchar(75)

ClinicanAssignment:
Id Uniqueidentifier PK NOT NULL
PersonId Uniqueidentifier NOT NULL
ClinicianId Uniqueidentifier NOT NULL
...OTHER COLUMNS...

If I run a query to just get Person or Clinician it works and returns, however if I do an Include for ClinicianAssignment it will then throw the access violation error.  All tables are in the same schema and the configurations has the one to many configured from perons to clinicianassignment and clinician to clinicianassignment.  I removed the autoinclude from the configuration as it never rendered data with it active. I have never had this kind of issue with these kinds of tables until i moved to .Net 8.

.Net 8 8.0.204
MS SQL Server 2019

**Comment by ajcvickers** [comment] 2024-07-19 15:25
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Gregory-Lange** [comment] 2024-07-22 12:26
So I have been able to isolated down to class initialization on navigation properties. Whenever I new() up a one to one to remove the informational warning of "object could be null" is when this occurs.  I have tried with a few of the entities and has happened on each of them.   However, many to many are fine due to the fact they are initialized with a `new HashSet<>()`.

**Comment by AndriySvyryd** [comment] 2024-08-08 19:08
@Gregory-Lange Please provide a small repro project

**Comment by ajcvickers** [comment] 2024-08-26 11:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-08-26 11:20 UTC
Labels: customer-reported
