### ISSUE TITLE
Wrong type mapping for bool and DateTime on Reverse Engeneering from existing Sqlite Database

### ISSUE THREAD

**Issue by powerqubit** [dotnet/efcore#23026] opened 2020-10-17 01:43 UTC
When scaffolding a DbContext via Package Manager Console using
 
```Scaffold-DbContext -f "Datasource=C:/pqmb.db" Microsoft.EntityFrameworkCore.Sqlite -OutputDir Database\Model -DataAnnotations```

the context is created but database columns containing **"Datetime" or "bool" field types are always mapped to byte[]** albeit **data annotations are aware of the correct types**.

```C#
    [Table("VersionFrame")]
    public partial class VersionFrame
    {
        [Column(TypeName = "int")]
        public long VersionFrameId { get; set; }
        [Column(TypeName = "int")]
        public string Name { get; set; }
        [Column(TypeName = "bigint")]
        public long RoVersionId { get; set; }
        [Column(TypeName = "bigint")]
        public long TiVersionId { get; set; }
        [Column(TypeName = "date")]         // type is ok
        public byte[] StartDate { get; set; }    // wrong mapping
        [Column(TypeName = "date")]         // type is ok
        public byte[] EndDate { get; set; }     // wrong mapping
        [Column(TypeName = "bool")]         // type is ok
        public byte[] IsCurrent { get; set; }    // wrong mapping
    }
```

If I manually replace each "byte[]" with the right type (DateTime & bool) the application performs as expected.

using:
Target framework: netcoreapp3.0
"Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.0-rc.2.20475.6" (and previous versions)  
"Microsoft.EntityFrameworkCore.Tools" Version="5.0.0-rc.2.20475.6" (and previous versions)

**Comment by bricelam** [comment] 2020-10-19 02:01
Duplicate of #8824

**Closed** 2022-10-16 19:05 UTC
Labels: customer-reported
