### ISSUE TITLE
Multiple references to nested owned entities generates broken migration

### ISSUE THREAD

**Issue by RamunasAdamonis** [dotnet/efcore#16698] opened 2019-07-23 08:38 UTC
### Intro

We have a nested owned entities which we wanted to re-use in our model, but after doing so it lead to the point where it was generating "broken" migration which was trying to drop `key` property of owned entity and so on. (key of owned entity is not actually stored). I have extracted this into small sample and create a repository: [efcore_broken_migration](https://github.com/RamunasAdamonis/efcore_broken_migration)

### Steps to reproduce
* Clone the repository
* Delete migrations folder
* Create a migration. It creates what seems to be a normal migration (I use command: `dotnet ef migrations add Migration_1`)
* Create a second migration without any changes to a code. It creates migration with statements like this: 
```c#
migrationBuilder.DropColumn(
    name: "AddressVOClientDetailsVOBusinessClientId",
    table: "Orders");
```
Here: `AddressVO` is an owned entity for entity `Order`.

### Issues: 
1. It should generate empty migration since there are no code changes
2. Generated migration makes no sense (a.k.a. broken migration)
3. All subsequent migrations generate that broken code.

### More insights

Now if I try to fiddle around with the model it starts throwing some exceptions.

1. ```Unable to determine the relationship represented by navigation property```

#### Steps to reproduce

* Delete migrations folder
* Open `DatabaseContext.cs`
* Change: 
```c#
        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.ApplyConfiguration(new RegularClientConfiguration());
            builder.ApplyConfiguration(new BusinessClientConfiguration());

            builder.ApplyConfiguration(new OrderConfiguration());
        }
```
To: 
```c#
        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.ApplyConfiguration(new OrderConfiguration());

            builder.ApplyConfiguration(new RegularClientConfiguration());
            builder.ApplyConfiguration(new BusinessClientConfiguration());
        }
```
(Changing only the order of configurations)
* Try to create migration 

It throws following error (Without creating migration! which in my opinion is a way better than taking modelSnapshot in a broken state):

```
Exception message: Unable to determine the relationship represented by navigation property 'Order.DeliveryAddress#AddressVO.PrimaryAddress' of type 'AddressDTO'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
Stack trace: at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.Validate()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_2(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

2. ```The entity type <Type> cannot be added to the model because a weak entity type with the same name already exists```

#### Steps to reproduce

* Undo the changes to `DatabaseContext.cs`
* Delete migrations folder if any.
* Open `Order.cs`
* Rename class name `Order` to `ReguralOrder`
* Create a migration. Again it creates what seems to be normal migration.
* Create second migration. It throws the following: 

```
Exception message:The entity type 'ef_bug.AddressVO' cannot be added to the model because a weak entity type with the same name already exists.
Stack trace: at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(EntityType entityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(String name, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(TypeIdentity& type, ConfigurationSource configurationSource, Boolean allowOwned, Boolean throwOnQuery)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(String name, ConfigurationSource configurationSource, Boolean allowOwned, Boolean throwOnQuery)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceOwnershipBuilder.FindRelatedEntityType(String relatedTypeName, String navigationName)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceOwnershipBuilder.HasOne(String relatedTypeName, String navigationName)
   at ef_bug.Migrations.DatabaseContextModelSnapshot.<>c.<BuildModel>b__0_13(ReferenceOwnershipBuilder b3) in C:\Users\Ramunas Adamonis\Stuff\Sources\ef_bug\Migrations\DatabaseContextModelSnapshot.cs:line 179
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceOwnershipBuilder.OwnsOne(String ownedTypeName, String navigationName, Action`1 buildAction)
   at ef_bug.Migrations.DatabaseContextModelSnapshot.<>c.<BuildModel>b__0_12(ReferenceOwnershipBuilder b2) in C:\Users\Ramunas Adamonis\Stuff\Sources\ef_bug\Migrations\DatabaseContextModelSnapshot.cs:line 169
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceOwnershipBuilder.OwnsOne(String ownedTypeName, String navigationName, Action`1 buildAction)
   at ef_bug.Migrations.DatabaseContextModelSnapshot.<>c.<BuildModel>b__0_11(ReferenceOwnershipBuilder b1) in C:\Users\Ramunas Adamonis\Stuff\Sources\ef_bug\Migrations\DatabaseContextModelSnapshot.cs:line 156
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.OwnsOne(String ownedTypeName, String navigationName, Action`1 buildAction)
   at ef_bug.Migrations.DatabaseContextModelSnapshot.<>c.<BuildModel>b__0_5(EntityTypeBuilder b) in C:\Users\Ramunas Adamonis\Stuff\Sources\ef_bug\Migrations\DatabaseContextModelSnapshot.cs:line 143
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(String name, Action`1 buildAction)
   at ef_bug.Migrations.DatabaseContextModelSnapshot.BuildModel(ModelBuilder modelBuilder) in C:\Users\Ramunas Adamonis\Stuff\Sources\ef_bug\Migrations\DatabaseContextModelSnapshot.cs:line 137
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot.<.ctor>b__1_0()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot.get_Model()
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

It is very weird that ordering of confuguration or even naming of a class changes the behavior of the error, but I hope it helps a bit. 

My humble apologies if I didn't narrowed the issue to a specific point, but I hope my repo will help to gain some insights for the issue. Let me know if you need anything from my side or having trouble to replicate the issues.

### Further technical details
EF Core version: 2.2.6-servicing-10079
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio Code 1.36.1

**Comment by ajcvickers** [comment] 2019-07-25 16:37
This is a duplicate of #9148 since the entity types are being configured as both non-owned and owned.

**Comment by RamunasAdamonis** [comment] 2019-07-26 13:59
@ajcvickers it is not really the case here, there is no entity that is configured both non-owned and owned. I have also tried to update repository to EF Core 3.0 (3.0.0-preview7.19362.6) and it still produces same broken migration.

**Comment by ajcvickers** [comment] 2019-07-26 16:07
@RamunasAdamonis When running the code, I thought that there were both `IEntityTypeConfiguration<TEntity>` and `OwnsOne<T>` for the same `TEntity`. If that's not the case then I will investigate some more.

**Comment by ajcvickers** [comment] 2019-07-26 23:19
@RamunasAdamonis I was able to reproduce this on the current nightlies.

@AndriySvyryd Could be a dupe? Here's the model:
```
Model: 
  EntityType: BusinessClient
    Properties: 
      Id (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd
      ClientId (no field, Nullable<Guid>) Shadow FK Index
    Navigations: 
      ClientDetails (<ClientDetails>k__BackingField, ClientDetailsVO) ToDependent BusinessClient.ClientDetails#ClientDetailsVO
    Keys: 
      Id PK
    Foreign keys: 
      BusinessClient {'ClientId'} -> Client {'Id'} ToDependent: BusinessClients
  EntityType: Client
    Properties: 
      Id (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd
    Navigations: 
      BusinessClients (_businessClients, IEnumerable<BusinessClient>) Collection ToDependent BusinessClient
      RegularClients (_regularClients, IEnumerable<RegularClient>) Collection ToDependent RegularClient
    Keys: 
      Id PK
  EntityType: Order
    Properties: 
      Id (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd
    Navigations: 
      DeliveryAddress (<DeliveryAddress>k__BackingField, AddressVO) ToDependent Order.DeliveryAddress#AddressVO
    Keys: 
      Id PK
  EntityType: RegularClient
    Properties: 
      Id (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd
      ClientId (no field, Nullable<Guid>) Shadow FK Index
    Navigations: 
      ClientDetails (<ClientDetails>k__BackingField, ClientDetailsVO) ToDependent RegularClient.ClientDetails#ClientDetailsVO
    Keys: 
      Id PK
    Foreign keys: 
      RegularClient {'ClientId'} -> Client {'Id'} ToDependent: RegularClients
  EntityType: BusinessClient.ClientDetails#ClientDetailsVO.Address#AddressVO.PrimaryAddress#AddressDTO
    Properties: 
      AddressVOClientDetailsVOBusinessClientId (no field, Guid) Shadow Required PK FK AfterSave:Throw
      Street (string)
    Keys: 
      AddressVOClientDetailsVOBusinessClientId PK
    Foreign keys: 
      BusinessClient.ClientDetails#ClientDetailsVO.Address#AddressVO.PrimaryAddress#AddressDTO {'AddressVOClientDetailsVOBusinessClientId'} -> BusinessClient.ClientDetails#ClientDetailsVO.Address#AddressVO {'ClientDetailsVOBusinessClientId'} Unique Ownership ToDependent: PrimaryAddress
  EntityType: RegularClient.ClientDetails#ClientDetailsVO.Address#AddressVO.PrimaryAddress#AddressDTO
    Properties: 
      AddressVOClientDetailsVORegularClientId (no field, Guid) Shadow Required PK FK AfterSave:Throw
      Street (string)
    Keys: 
      AddressVOClientDetailsVORegularClientId PK
    Foreign keys: 
      RegularClient.ClientDetails#ClientDetailsVO.Address#AddressVO.PrimaryAddress#AddressDTO {'AddressVOClientDetailsVORegularClientId'} -> RegularClient.ClientDetails#ClientDetailsVO.Address#AddressVO {'ClientDetailsVORegularClientId'} Unique Ownership ToDependent: PrimaryAddress
  EntityType: Order.DeliveryAddress#AddressVO.PrimaryAddress#AddressDTO
    Properties: 
      AddressVOOrderId (no field, Guid) Shadow Required PK FK AfterSave:Throw
      Street (string)
    Keys: 
      AddressVOOrderId PK
    Foreign keys: 
      Order.DeliveryAddress#AddressVO.PrimaryAddress#AddressDTO {'AddressVOOrderId'} -> Order.DeliveryAddress#AddressVO {'OrderId'} Unique Ownership ToDependent: PrimaryAddress
  EntityType: BusinessClient.ClientDetails#ClientDetailsVO.Address#AddressVO.SecondaryAddress#AddressDTO
    Properties: 
      AddressVOClientDetailsVOBusinessClientId (no field, Guid) Shadow Required PK FK AfterSave:Throw
      Street (string)
    Keys: 
      AddressVOClientDetailsVOBusinessClientId PK
    Foreign keys: 
      BusinessClient.ClientDetails#ClientDetailsVO.Address#AddressVO.SecondaryAddress#AddressDTO {'AddressVOClientDetailsVOBusinessClientId'} -> BusinessClient.ClientDetails#ClientDetailsVO.Address#AddressVO {'ClientDetailsVOBusinessClientId'} Unique Ownership ToDependent: SecondaryAddress
  EntityType: RegularClient.ClientDetails#ClientDetailsVO.Address#AddressVO.SecondaryAddress#AddressDTO
    Properties: 
      AddressVOClientDetailsVORegularClientId (no field, Guid) Shadow Required PK FK AfterSave:Throw
      Street (string)
    Keys: 
      AddressVOClientDetailsVORegularClientId PK
    Foreign keys: 
      RegularClient.ClientDetails#ClientDetailsVO.Address#AddressVO.SecondaryAddress#AddressDTO {'AddressVOClientDetailsVORegularClientId'} -> RegularClient.ClientDetails#ClientDetailsVO.Address#AddressVO {'ClientDetailsVORegularClientId'} Unique Ownership ToDependent: SecondaryAddress
  EntityType: Order.DeliveryAddress#AddressVO.SecondaryAddress#AddressDTO
    Properties: 
      AddressVOOrderId (no field, Guid) Shadow Required PK FK AfterSave:Throw
      Street (string)
    Keys: 
      AddressVOOrderId PK
    Foreign keys: 
      Order.DeliveryAddress#AddressVO.SecondaryAddress#AddressDTO {'AddressVOOrderId'} -> Order.DeliveryAddress#AddressVO {'OrderId'} Unique Ownership ToDependent: SecondaryAddress
  EntityType: BusinessClient.ClientDetails#ClientDetailsVO.Address#AddressVO
    Properties: 
      ClientDetailsVOBusinessClientId (no field, Guid) Shadow Required PK FK AfterSave:Throw
    Navigations: 
      PrimaryAddress (<PrimaryAddress>k__BackingField, AddressDTO) ToDependent BusinessClient.ClientDetails#ClientDetailsVO.Address#AddressVO.PrimaryAddress#AddressDTO
      SecondaryAddress (<SecondaryAddress>k__BackingField, AddressDTO) ToDependent BusinessClient.ClientDetails#ClientDetailsVO.Address#AddressVO.SecondaryAddress#AddressDTO
    Keys: 
      ClientDetailsVOBusinessClientId PK
    Foreign keys: 
      BusinessClient.ClientDetails#ClientDetailsVO.Address#AddressVO {'ClientDetailsVOBusinessClientId'} -> BusinessClient.ClientDetails#ClientDetailsVO {'BusinessClientId'} Unique Ownership ToDependent: Address
  EntityType: RegularClient.ClientDetails#ClientDetailsVO.Address#AddressVO
    Properties: 
      ClientDetailsVORegularClientId (no field, Guid) Shadow Required PK FK AfterSave:Throw
    Navigations: 
      PrimaryAddress (<PrimaryAddress>k__BackingField, AddressDTO) ToDependent RegularClient.ClientDetails#ClientDetailsVO.Address#AddressVO.PrimaryAddress#AddressDTO
      SecondaryAddress (<SecondaryAddress>k__BackingField, AddressDTO) ToDependent RegularClient.ClientDetails#ClientDetailsVO.Address#AddressVO.SecondaryAddress#AddressDTO
    Keys: 
      ClientDetailsVORegularClientId PK
    Foreign keys: 
      RegularClient.ClientDetails#ClientDetailsVO.Address#AddressVO {'ClientDetailsVORegularClientId'} -> RegularClient.ClientDetails#ClientDetailsVO {'RegularClientId'} Unique Ownership ToDependent: Address
    Annotations: 
      ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.ConstructorBinding
  EntityType: Order.DeliveryAddress#AddressVO
    Properties: 
      OrderId (no field, Guid) Shadow Required PK FK AfterSave:Throw
    Navigations: 
      PrimaryAddress (<PrimaryAddress>k__BackingField, AddressDTO) ToDependent Order.DeliveryAddress#AddressVO.PrimaryAddress#AddressDTO
      SecondaryAddress (<SecondaryAddress>k__BackingField, AddressDTO) ToDependent Order.DeliveryAddress#AddressVO.SecondaryAddress#AddressDTO
    Keys: 
      OrderId PK
    Foreign keys: 
      Order.DeliveryAddress#AddressVO {'OrderId'} -> Order {'Id'} Unique Ownership ToDependent: DeliveryAddress
    Annotations: 
      ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.ConstructorBinding
  EntityType: BusinessClient.ClientDetails#ClientDetailsVO
    Properties: 
      BusinessClientId (no field, Guid) Shadow Required PK FK AfterSave:Throw
    Navigations: 
      Address (<Address>k__BackingField, AddressVO) ToDependent BusinessClient.ClientDetails#ClientDetailsVO.Address#AddressVO
    Keys: 
      BusinessClientId PK
    Foreign keys: 
      BusinessClient.ClientDetails#ClientDetailsVO {'BusinessClientId'} -> BusinessClient {'Id'} Unique Ownership ToDependent: ClientDetails
    Annotations: 
      ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.ConstructorBinding
  EntityType: RegularClient.ClientDetails#ClientDetailsVO
    Properties: 
      RegularClientId (no field, Guid) Shadow Required PK FK AfterSave:Throw
    Navigations: 
      Address (<Address>k__BackingField, AddressVO) ToDependent RegularClient.ClientDetails#ClientDetailsVO.Address#AddressVO
    Keys: 
      RegularClientId PK
    Foreign keys: 
      RegularClient.ClientDetails#ClientDetailsVO {'RegularClientId'} -> RegularClient {'Id'} Unique Ownership ToDependent: ClientDetails
Annotations: 
  ProductVersion: 3.0.0-preview8.19376.10
  Relational:MaxIdentifierLength: 128
  SqlServer:ValueGenerationStrategy: IdentityColumn
```

**Comment by AndriySvyryd** [comment] 2019-10-21 21:42
The first issue is a duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/18045
The reordering and renaming issues don't repro on 3.1

**Closed** 2022-10-16 14:31 UTC
Labels: customer-reported
