### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jalilnhctg** [dotnet/efcore#23677] opened 2020-12-14 04:44 UTC
There was an error running the selected code generator: 'The entity type 'DepartmentInfo' requires a primary key to be defined. If you intended to use a keyless entity type call 'HasNokey()'.'
![Error](https://user-images.githubusercontent.com/71256212/102041306-48a73200-3df9-11eb-950a-49281af0f992.PNG)

**Comment by roji** [comment] 2020-12-14 08:27
@jalilnhctg please post a full code sample - an error message isn't enough for us understand what you're doing.

**Comment by ajcvickers** [comment] 2021-01-04 16:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:15 UTC
Labels: closed-could-not-reproduce, customer-reported
