### ISSUE TITLE
Migrations :: exception thrown after adding DbSet declaration to the context - table name has changed but it's not being picked up

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#4805] opened 2016-03-15 21:12 UTC
I used to have a model that didn't declare DbSet on the context for one of the entities, so the table created was the same as the name of the entity. After adding the DbSet, the name should be changed to plural, but migrator doesn't figure it out, and throws:

System.Data.SqlClient.SqlException (0x80131904): Cannot find the object "StashTabs" because it does not exist or you do not have permissions.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandExtensions.ExecuteNonQuery(IEnumerable`1 commands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Execute(IEnumerable`1 relationalCommands)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

Model before the migration (from previous migration designer.cs):

```
    [DbContext(typeof(PoeSniperContext))]
    [Migration("20160315204209_Mig04")]
    partial class Mig04
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "1.0.0-rc2-20207")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Account", b =>
                {
                    b.Property<string>("AccountName");

                    b.Property<string>("LastCharacterName");

                    b.HasKey("AccountName");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Model.Item", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("Name");

                    b.Property<string>("AccountName");

                    b.Property<bool>("Corrupted");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("Ilvl");

                    b.Property<string>("League");

                    b.Property<string>("TypeLine");

                    b.HasKey("Id", "Name");

                    b.HasIndex("AccountName", "League");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("Model.ItemFeedChunk", b =>
                {
                    b.Property<string>("ChunkId");

                    b.Property<int>("Index");

                    b.Property<string>("PreviousChunkId");

                    b.Property<int?>("PreviousIndex");

                    b.HasKey("ChunkId", "Index");

                    b.HasIndex("PreviousChunkId", "PreviousIndex");

                    b.ToTable("ItemFeedChunks");
                });

            modelBuilder.Entity("Model.ItemMod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ItemId");

                    b.Property<string>("ItemName");

                    b.Property<string>("MagicalItemId");

                    b.Property<string>("MagicalItemName");

                    b.Property<int?>("NameId");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.HasIndex("NameId");

                    b.HasIndex("ItemId", "ItemName");

                    b.HasIndex("MagicalItemId", "MagicalItemName");

                    b.ToTable("ItemMod");
                });

            modelBuilder.Entity("Model.ItemModName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("ItemModName");
                });

            modelBuilder.Entity("Model.ItemRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ItemId");

                    b.Property<string>("ItemName");

                    b.Property<string>("Name");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "ItemName");

                    b.ToTable("ItemRequirement");
                });

            modelBuilder.Entity("Model.Stash", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("AccountName");

                    b.Property<string>("ItemFeedChunkChunkId");

                    b.Property<int?>("ItemFeedChunkIndex");

                    b.Property<string>("League");

                    b.HasKey("Id", "AccountName");

                    b.HasIndex("AccountName");

                    b.HasIndex("ItemFeedChunkChunkId", "ItemFeedChunkIndex");

                    b.ToTable("Stashes");
                });

            modelBuilder.Entity("Model.StashTab", b =>
                {
                    b.Property<string>("AccountName");

                    b.Property<string>("League");

                    b.Property<string>("StashAccountName");

                    b.Property<string>("StashId");

                    b.Property<string>("TabName");

                    b.HasKey("AccountName", "League");

                    b.HasIndex("StashId", "StashAccountName");

                    b.ToTable("StashTab");
                });

            modelBuilder.Entity("Model.MagicalItem", b =>
                {
                    b.HasBaseType("Model.Item");

                    b.Property<bool>("Identified");

                    b.ToTable("MagicalItem");

                    b.HasDiscriminator().HasValue("MagicalItem");
                });

            modelBuilder.Entity("Model.UniqueItem", b =>
                {
                    b.HasBaseType("Model.MagicalItem");

                    b.Property<string>("FlavorText");

                    b.ToTable("UniqueItem");

                    b.HasDiscriminator().HasValue("UniqueItem");
                });

            modelBuilder.Entity("Model.Item", b =>
                {
                    b.HasOne("Model.StashTab")
                        .WithMany()
                        .HasForeignKey("AccountName", "League");
                });

            modelBuilder.Entity("Model.ItemFeedChunk", b =>
                {
                    b.HasOne("Model.ItemFeedChunk")
                        .WithOne()
                        .HasForeignKey("Model.ItemFeedChunk", "PreviousChunkId", "PreviousIndex");
                });

            modelBuilder.Entity("Model.ItemMod", b =>
                {
                    b.HasOne("Model.ItemModName")
                        .WithMany()
                        .HasForeignKey("NameId");

                    b.HasOne("Model.Item")
                        .WithMany()
                        .HasForeignKey("ItemId", "ItemName");

                    b.HasOne("Model.MagicalItem")
                        .WithMany()
                        .HasForeignKey("MagicalItemId", "MagicalItemName");
                });

            modelBuilder.Entity("Model.ItemRequirement", b =>
                {
                    b.HasOne("Model.Item")
                        .WithMany()
                        .HasForeignKey("ItemId", "ItemName");
                });

            modelBuilder.Entity("Model.Stash", b =>
                {
                    b.HasOne("Model.Account")
                        .WithMany()
                        .HasForeignKey("AccountName")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Model.ItemFeedChunk")
                        .WithMany()
                        .HasForeignKey("ItemFeedChunkChunkId", "ItemFeedChunkIndex");
                });

            modelBuilder.Entity("Model.StashTab", b =>
                {
                    b.HasOne("Model.Stash")
                        .WithMany()
                        .HasForeignKey("StashId", "StashAccountName");
                });
        }
    }
```

Current model:

```
    public class Account
    {
        public string AccountName { get; set; }

        public List<Stash> Stashes { get; set; }

        public string LastCharacterName { get; set; }
    }

    public class Item
    {
        // composite key, Name can be null
        public string Id { get; set; }
        public string Name { get; set; }

        public int Ilvl { get; set; }
        public string TypeLine { get; set; }
        public bool Corrupted { get; set; }

        public List<ItemRequirement> Requirements { get; set; }

        public List<ItemMod> ImplicitMods { get; set; }
    }

    public class ItemFeedChunk
    {
        // composite key
        public string ChunkId { get; set; }
        public int Index { get; set; }

        public string PreviousChunkId { get; set; }
        public int? PreviousIndex { get; set; }

        // 1-1 optional self-reference
        public ItemFeedChunk PreviousChunk { get; set; }

        public List<Stash> Stashes { get; set; }
    }

    public class ItemMod
    {
        public int Id { get; set; }

        public ItemModName Name { get; set; }
        public decimal Value { get; set; }
    }

    public class ItemModName
    {
        public int Id { get; set; }

        public string Text { get; set; }
    }

    public class ItemRequirement
    {
        public int Id { get; set; }

        public string Name { get; set; }
        public int Value { get; set; }
    }

    public class MagicalItem : Item
    {
        public List<ItemMod> ExplicitMods { get; set; }

        public bool Identified { get; set; }
    }

    public class Stash
    {
        // composite key
        public string AccountName { get; set; }
        public string League { get; set; }


        public Account Account { get; set; }
        public List<StashTab> StashTabs { get; set; }
    }

    public class StashTab
    {
        public string Id { get; set; }

        public string TabName { get; set; }

        public Stash Stash { get; set; }

        public List<Item> Items { get; set; }
    }

    public class UniqueItem : MagicalItem
    {
        public string FlavorText { get; set; }
    }

    public class PoeSniperContext : DbContext
    {
        public DbSet<ItemFeedChunk> ItemFeedChunks { get; set; }
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Stash> Stashes { get; set; }
        public DbSet<StashTab> StashTabs { get; set; }
        public DbSet<Item> Items { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var connectionString = new SqlConnectionStringBuilder
            {
                DataSource = ".",
                InitialCatalog = "PoeSniper",
                MultipleActiveResultSets = true,
                IntegratedSecurity = true
            }.ToString();

            optionsBuilder.UseSqlServer(connectionString);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ItemFeedChunk>().HasKey(e => new { e.ChunkId, e.Index });
            modelBuilder.Entity<ItemFeedChunk>().HasOne(e => e.PreviousChunk).WithOne().HasForeignKey<ItemFeedChunk>(e => new { e.PreviousChunkId, e.PreviousIndex }).IsRequired(false);

            modelBuilder.Entity<Account>().HasKey(e => e.AccountName);

            modelBuilder.Entity<Stash>().HasKey(e => new { e.AccountName, e.League });
            modelBuilder.Entity<Stash>().HasOne(e => e.Account).WithMany(e => e.Stashes).HasForeignKey("AccountName");
            modelBuilder.Entity<Stash>().HasMany(e => e.StashTabs).WithOne(e => e.Stash).HasForeignKey("AccountName", "League");

            modelBuilder.Entity<StashTab>().HasKey(e => new { e.Id });
            modelBuilder.Entity<StashTab>().HasMany(e => e.Items).WithOne().HasForeignKey("StashTabId");

            modelBuilder.Entity<Item>().HasKey(e => new { e.Id, e.Name });
            modelBuilder.Entity<MagicalItem>().HasBaseType<Item>();
            modelBuilder.Entity<UniqueItem>().HasBaseType<MagicalItem>();
        }
    }
```

Migration being generated:

```
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Items_StashTab_AccountName_League",
                table: "Items");

            migrationBuilder.DropForeignKey(
                name: "FK_Stashes_Account_AccountName",
                table: "Stashes");

            migrationBuilder.DropForeignKey(
                name: "FK_StashTab_Stashes_StashId_StashAccountName",
                table: "StashTab");

            migrationBuilder.DropPrimaryKey(
                name: "PK_StashTab",
                table: "StashTab");

            migrationBuilder.DropIndex(
                name: "IX_StashTab_StashId_StashAccountName",
                table: "StashTab");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Stashes",
                table: "Stashes");

            migrationBuilder.DropIndex(
                name: "IX_Items_AccountName_League",
                table: "Items");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Account",
                table: "Account");

            migrationBuilder.DropColumn(
                name: "StashAccountName",
                table: "StashTab");

            migrationBuilder.DropColumn(
                name: "StashId",
                table: "StashTab");

            migrationBuilder.DropColumn(
                name: "Id",
                table: "Stashes");

            migrationBuilder.DropColumn(
                name: "AccountName",
                table: "Items");

            migrationBuilder.DropColumn(
                name: "League",
                table: "Items");

            migrationBuilder.AlterColumn<string>(
                name: "League",
                table: "StashTab",
                nullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "AccountName",
                table: "StashTab",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Id",
                table: "StashTabs",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddPrimaryKey(
                name: "PK_StashTabs",
                table: "StashTabs",
                column: "Id");

            migrationBuilder.CreateIndex(
                name: "IX_StashTabs_AccountName_League",
                table: "StashTabs",
                columns: new[] { "AccountName", "League" });

            migrationBuilder.AlterColumn<string>(
                name: "League",
                table: "Stashes",
                nullable: false);

            migrationBuilder.AddPrimaryKey(
                name: "PK_Stashes",
                table: "Stashes",
                columns: new[] { "AccountName", "League" });

            migrationBuilder.AddColumn<string>(
                name: "StashTabId",
                table: "Items",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Items_StashTabId",
                table: "Items",
                column: "StashTabId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Accounts",
                table: "Accounts",
                column: "AccountName");

            migrationBuilder.AddForeignKey(
                name: "FK_Items_StashTabs_StashTabId",
                table: "Items",
                column: "StashTabId",
                principalTable: "StashTabs",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Stashes_Accounts_AccountName",
                table: "Stashes",
                column: "AccountName",
                principalTable: "Accounts",
                principalColumn: "AccountName",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_StashTabs_Stashes_AccountName_League",
                table: "StashTabs",
                columns: new[] { "AccountName", "League" },
                principalTable: "Stashes",
                principalColumns: new[] { "AccountName", "League" },
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.RenameTable(
                name: "StashTab",
                newName: "StashTabs");

            migrationBuilder.RenameTable(
                name: "Account",
                newName: "Accounts");
        }
```

**Comment by smitpatel** [comment] 2016-03-15 23:49
dupe of #3990

**Closed** 2022-10-16 09:32 UTC
