### ISSUE TITLE
It work for me 

### ISSUE THREAD

**Issue by Xm3a01** [dotnet/efcore#31484] opened 2023-08-16 17:35 UTC
I did the following:

- dotnet tool install --global dotnet-ef
- uninstalling and re-installing
- run terminal as administrator 

None of these worked.

**The fix for me was adding `C:\Users\{YOURUSER}\.dotnet\tools` manwally to the PATH**

_Originally posted by @rekardev1 in https://github.com/dotnet/efcore/issues/19861#issuecomment-1622220428_

**Comment by bricelam** [comment] 2023-08-28 21:13
Did you restart after installing .NET?

**Comment by ajcvickers** [comment] 2023-09-20 19:16
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-09-20 19:16 UTC
