### ISSUE TITLE
How to include multiple child elements / Wrong SQL generated for joins

### ISSUE THREAD

**Issue by SilverioMiranda** [dotnet/efcore#7335] opened 2017-01-02 00:54 UTC
I have this query :

```
var ret = _context.Set<ProdutoPreco>()
                .Include(x => x.Produto).ThenInclude(x => x.ProdutoClasse)
                .Include(x => x.Produto).ThenInclude(x => x.ProdutoGrupo)
                .Include(x => x.Produto).ThenInclude(x => x.UnidadeMedida)
                .Include(x => x.Produto).ThenInclude(x => x.Fabricante)
                .Include(x => x.Produto).ThenInclude(x => x.ProdutoMedicamento)
                .Include(x => x.ProdutoEstoque)
                .Include(x => x.Comissao);
```

The generated query is the following :

```
SELECT `x`.`ProdutoId`, ....
FROM `produto_preco` AS `x`
INNER JOIN `produto` AS `p` ON `x`.`ProdutoId` = `p`.`Id`
INNER JOIN `produto_classe` AS `p0` ON `p`.`ProdutoClasseId` = `p0`.`Id`
INNER JOIN `produto` AS `p1` ON `x`.`ProdutoId` = `p1`.`Id`
INNER JOIN `produto_grupo` AS `p2` ON `p1`.`ProdutoGrupoId` = `p2`.`Id`
INNER JOIN `produto` AS `p3` ON `x`.`ProdutoId` = `p3`.`Id`
LEFT JOIN `produto_unidade_medida` AS `p4` ON `p3`.`UnidadeMedidaId` = `p4`.`Id`
INNER JOIN `produto` AS `p5` ON `x`.`ProdutoId` = `p5`.`Id`
INNER JOIN `Fabricante` AS `f` ON `p5`.`FabricanteId` = `f`.`Id`
INNER JOIN `produto` AS `p6` ON `x`.`ProdutoId` = `p6`.`Id`
LEFT JOIN `produto_medicamento` AS `p7` ON `p7`.`Id` = `p6`.`Id`
LEFT JOIN `produto_estoque` AS `p8` ON (`p8`.`ProdutoId` = `x`.`ProdutoId`) AND (`p8`.`LojaId` = `x`.`LojaId`)
LEFT JOIN `produto_comissao` AS `p9` ON `x`.`ComissaoId` = `p9`.`Id`
WHERE
...
```

As we can see the include join "produto" table so many times, and i dont see in documentation any way to do this include in other way

Thanks

Further technical details

EF Core version: 1.1.0
Database Provider: SapientGuardian.EntityFrameworkCore.MySql
Operating system: Win 10
IDE: Visual Studio 2015

**Comment by SilverioMiranda** [comment] 2017-01-07 04:46
I found duplicate : [https://github.com/aspnet/EntityFramework/issues/6647](https://github.com/aspnet/EntityFramework/issues/6647)

**Comment by Robula** [comment] 2017-05-30 12:26
Is that actually a duplicate of the issue? I'm experiencing the exact same as your question (multiple joins to the same table in output SQL).

**Comment by ajcvickers** [comment] 2017-05-31 02:49
@Robula Should be fixed in the current codebase. Can you try the 2.0.0 preview release from NuGet? If it still repros for you with 2.0, then please open a new issue with full details on how to reproduce what you are seeing.

**Closed** 2022-10-16 10:48 UTC
