### ISSUE TITLE
Add Code First API for creating non-primary keys

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#1087] opened 2014-11-17 23:43 UTC
Otherwise it's not possible to add annotations to them without dropping down to metadata API.

**Comment by bricelam** [comment] 2015-05-05 21:58
Because of this, the model snapshot will lose any alternate keys that are not the target of a foreign key. Also any annotations on alternate keys will be lost.
/cc @smitpatel

**Comment by rowanmiller** [comment] 2015-05-15 22:34
Dupe of https://github.com/aspnet/EntityFramework/issues/2164

**Closed** 2022-10-16 08:46 UTC
