### ISSUE TITLE
Logical NOT before contains does not include NULL check

### ISSUE THREAD

**Issue by S1r-Lanzelot** [dotnet/efcore#14171] opened 2018-12-14 20:15 UTC
I have a piece of code that looks like the following:
```c#
public List<string> ResolveDomicileIdsByForeignGeoId(IEnumerable<int?> geoIds)
        {
            var domIds = myContext.DomicileMappings
                .Where(x => !geoIds.Contains(x.GeoId))
                .Select(x => x.DomicileId).Distinct().ToList();
            return domIds;
        }
```

The `GeoId` column in the `DomicileMappings` table is `nullable`. 

The generated sql for this query is as follows:
```sql
SELECT DISTINCT [x].[DomicileId]
FROM [DomicileMappings] AS [x]
WHERE [x].[GeoId] NOT IN (77)
```

However I would expect it to check for nulls as well, as follows:
```sql
SELECT DISTINCT [x].[DomicileId]
FROM [DomicileMappings] AS [x]
WHERE [x].[GeoId] NOT IN (77) OR [x].[GeoId] IS NULL
```

since the column is nullable. Am I wrong to expect this?

### Further technical details
EF Core version: v2.2.0
Database Provider: Sql Server (Azure)

**Comment by S1r-Lanzelot** [comment] 2018-12-14 20:31
Furthermore, I would expect this to work in Linq To Sql as it works with in memory objects:
```c#
            List<int?> hi = new List<int?>();
            List<int?> yo = new List<int?>();

            yo.Add(1);
            hi.Add(1);
            hi.Add(2);
            hi.Add(null);

            var r = hi.Where(x => !yo.Contains(x)).ToList();
//r = 2, null
```

**Comment by smitpatel** [comment] 2018-12-17 21:32
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by smitpatel** [comment] 2018-12-17 21:33
Following code
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database

                db.AddRange(
                    new Blog { Value = null },
                    new Blog { Value = 2 }
                    );

                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                var ids = new List<int?>
                {
                    1,
                    2,
                    null
                };
                var query = db.Blogs
                    .Where(b => !ids.Contains(b.Value))
                    .ToList();
                Console.WriteLine(query.Count);
            }

            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        private static ILoggerFactory LoggerFactory => new LoggerFactory().AddConsole(LogLevel.Trace);

        // Declare DBSets
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                //.UseSqlite("filename=_modelApp.db")
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(LoggerFactory);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
        }
    }

    public class Blog
    {
        public int Id { get; set; }
        public int? Value { get; set; }
    }
}
```
Generated SQL
```SQL
      SELECT [b].[Id], [b].[Value]
      FROM [Blogs] AS [b]
      WHERE [b].[Value] NOT IN (1, 2) AND [b].[Value] IS NOT NULL
```
EF Core version 2.2.0-rtm-35687

**Comment by S1r-Lanzelot** [comment] 2018-12-17 22:15
@smitpatel thanks for looking at this. I will work on submitting a project to reproduce the issue tonight. Looking at the example code briefly, I wonder if you instantiate the list with just: `var ids = new List<int?>
                {
                    1
                };`
it will replicate the issue... The generated query you posted is different from what I am after.

Regardless, Ill get a reproducable project up soon. Thanks.

**Comment by maumar** [comment] 2019-12-05 03:33
dupe of #11464

**Closed** 2022-10-16 13:44 UTC
Labels: customer-reported
