### ISSUE TITLE
Use views when reverse engineering database for POCO models

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/efcore#5528] opened 2016-05-26 03:52 UTC
Currently when using `Scaffold-DbContext` SQL views are not taken into account. Are there any plans to add model generation for views?

**Comment by lajones** [comment] 2016-05-26 16:23
Closing as dupe of #1679. https://github.com/aspnet/EntityFramework/wiki/Roadmap mentions that this is on the Backlog but no anticipated date yet.

**Closed** 2022-10-16 09:42 UTC
