### ISSUE TITLE
Include not working properly with InMemoryDatabase

### ISSUE THREAD

**Issue by stefan-landgraf-is24** [dotnet/efcore#14462] opened 2019-01-18 17:08 UTC
When fetching an entity which does not have a parent entity, including the parent removes the entity from the result. It worked correctly in 2.0 and fails since migrating to 2.2.

```C#
var options = new DbContextOptionsBuilder<OrderContext>()
	.UseInMemoryDatabase(databaseName: "Add_writes_to_database")
	.Options;

using (var context = new OrderContext(options))
{
	// prepare parent entity
	var order = new Order() { Id = 1 };
	context.Add(order);
	context.SaveChanges();

	// prepare child without parent
	var orderItemWithoutParent = new OrderItem() { Id = 1 };
	context.Add(orderItemWithoutParent);
	context.SaveChanges();

	// prepare child with parent
	var orderItemWithParent = new OrderItem() { Id = 2, Order = order };
	context.Add(orderItemWithParent);
	context.SaveChanges();
}

using (var context = new OrderContext(options))
{
	// OK with Include if entity has Parent
	var orderItemWithParent = context.OrderItems
		.Include(o => o.Order)
		.FirstOrDefault(o => o.Id == 2);

	Assert.NotNull(orderItemWithParent);

	// OK for entity without parent without Include
	var orderItemWithoutParent = context.OrderItems
		.FirstOrDefault(o => o.Id==1);

	Assert.NotNull(orderItemWithoutParent);

	// FAILS for entity without parent because of Include
	orderItemWithoutParent = context.OrderItems
		.Include(o => o.Order)
		.FirstOrDefault(o => o.Id == 1);

	Assert.NotNull(orderItemWithoutParent);
}
```

### Steps to reproduce
Repro project is attached [Demo.zip](https://github.com/aspnet/EntityFrameworkCore/files/2773895/Demo.zip)

**Comment by stefan-landgraf-is24** [comment] 2019-01-22 15:25
This behaviour is limited to relationships, where the FK-Property is not nullable:

This will FAIL:
`public class OrderItem
    {
        public int Id { get; set; }
        public Order Order { get; set; }
        public int OrderId { get; set; } // <= int
    }
`
This will SUCCEED:
`public class OrderItem
    {
        public int Id { get; set; }
        public Order Order { get; set; }
        public int? OrderId { get; set; } // <= int?
    }
`

This is annoying, as the advantage of using the InMemory provider is not to have to keep up referential integrity. I don't want to make all my FKs nullable to make my tests run again.

**Comment by alekrist** [comment] 2019-01-22 16:18
Please fix this as it is also blocking us to upgrade to v2.2

**Comment by ajcvickers** [comment] 2019-01-22 17:40
Duplicate of #9470 See also #2166 and #13146

**Closed** 2022-10-16 13:48 UTC
Labels: customer-reported
