### ISSUE TITLE
RC2 System.InvalidCastException: Specified cast is not valid

### ISSUE THREAD

**Issue by Mitch528** [dotnet/efcore#5371] opened 2016-05-15 22:59 UTC
This error occurs when trying to select a DateTime. I only get this error on Linux, whereas on Windows it works fine.

I'm using:
- Ubuntu 14.04.4
- .NET 4.5.1 with mono
- SQL Server on Azure

Example:

``` csharp
var user = await (from u in _applicationDbContext.Users
                            where u.UserName == model.Username
                            select new { u.TimeRegistered }).SingleOrDefaultAsync();
```

``` csharp
public class ApplicationUser : IdentityUser
{
    public DateTime TimeRegistered { get; set; }
}

public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
       : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        // Customize the ASP.NET Identity model and override the defaults if needed.
        // For example, you can rename the ASP.NET Identity table names and more.
        // Add your customizations after calling base.OnModelCreating(builder);
    }
}

```

```
fail: Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory[1]
      An exception occurred in the database while iterating the results of a query.
      System.InvalidCastException: Specified cast is not valid.
        at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,Microsoft.EntityFrameworkCore.Storage.ValueBuffer)
        at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper`1[TEntity].Shape (Microsoft.EntityFrameworkCore.Query.QueryContext queryContext, ValueBuffer valueBuffer) <0x42699920 + 0x0010f> in <filename unknown>:0
        at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider+<>c__DisplayClass3_0`1[T].<_ShapedQuery>b__0 (ValueBuffer vb) <0x42699890 + 0x0005a> in <filename unknown>:0
        at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider+SelectAsyncEnumerable`2+SelectAsyncEnumerator[TSource,TResult].get_Current () <0x42699780 + 0x00049> in <filename unknown>:0
        at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider+<_SingleOrDefault>d__118`1[TSource].MoveNext () <0x42698180 + 0x002d6> in <filename unknown>:0
      --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f5f100018a0 + 0x00029> in <filename unknown>:0
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7f5f0ffff880 + 0x000a7> in <filename unknown>:0
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7f5f0ffff800 + 0x0006b> in <filename unknown>:0
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7f5f0ffff7b0 + 0x0003a> in <filename unknown>:0
        at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7f5f0ffffaa0 + 0x00017> in <filename unknown>:0
        at Microsoft.EntityFrameworkCore.Query.Internal.TaskResultAsyncEnumerable`1+Enumerator+<MoveNext>d__3[T].MoveNext () <0x42645be0 + 0x001cf> in <filename unknown>:0
      --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f5f100018a0 + 0x00029> in <filename unknown>:0
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7f5f0ffff880 + 0x000a7> in <filename unknown>:0
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7f5f0ffff800 + 0x0006b> in <filename unknown>:0
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7f5f0ffff7b0 + 0x0003a> in <filename unknown>:0
        at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7f5f102c4e80 + 0x00012> 24213 in <filename unknown>:0
        at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider+ExceptionInterceptor`1+EnumeratorExceptionInterceptor+<MoveNext>d__5[T].MoveNext () <0x42644330 + 0x004a5> in <filename unknown>:0
System.InvalidCastException: Specified cast is not valid.
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,Microsoft.EntityFrameworkCore.Storage.ValueBuffer)
  at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper`1[TEntity].Shape (Microsoft.EntityFrameworkCore.Query.QueryContext queryContext, ValueBuffer valueBuffer) <0x42699920 + 0x0010f> in <filename unknown>:0
  at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider+<>c__DisplayClass3_0`1[T].<_ShapedQuery>b__0 (ValueBuffer vb) <0x42699890 + 0x0005a> in <filename unknown>:0
  at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider+SelectAsyncEnumerable`2+SelectAsyncEnumerator[TSource,TResult].get_Current () <0x42699780 + 0x00049> in <filename unknown>:0
  at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider+<_SingleOrDefault>d__118`1[TSource].MoveNext () <0x42698180 + 0x002d6> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f5f100018a0 + 0x00029> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7f5f0ffff880 + 0x000a7> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7f5f0ffff800 + 0x0006b> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7f5f0ffff7b0 + 0x0003a> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7f5f0ffffaa0 + 0x00017> in <filename unknown>:0
  at Microsoft.EntityFrameworkCore.Query.Internal.TaskResultAsyncEnumerable`1+Enumerator+<MoveNext>d__3[T].MoveNext () <0x42645be0 + 0x001cf> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f5f100018a0 + 0x00029> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7f5f0ffff880 + 0x000a7> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7f5f0ffff800 + 0x0006b> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7f5f0ffff7b0 + 0x0003a> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7f5f102c4e80 + 0x00012> 24213 in <filename unknown>:0
  at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider+ExceptionInterceptor`1+EnumeratorExceptionInterceptor+<MoveNext>d__5[T].MoveNext () <0x42644330 + 0x004a5> in <filename unknown>:0
```

**Comment by ErikEJ** [comment] 2016-05-16 06:28
Dupe of https://github.com/aspnet/EntityFramework/issues/2596

**Comment by natemcmaster** [comment] 2016-05-16 17:26
@Mitch528 last time I checked, Mono has known issues with SqlClient and LINQ. 

Also, we recommend .NET Core for Linux instead of Mono for running an app that does Linux => SQL Azure

**Comment by rowanmiller** [comment] 2016-05-18 17:39
This is an issue in Mono - I believe this is the corresponding bug in the Mono issue tracker https://bugzilla.xamarin.com/show_bug.cgi?id=24719.

**Comment by rowanmiller** [comment] 2016-05-18 17:42
See also https://github.com/mono/mono/pull/1773

**Closed** 2022-10-16 09:40 UTC
