### ISSUE TITLE
Xamarin IOS ArgumentNullException in full linking mode. (EntityFrameworkCore.Sqlite)

### ISSUE THREAD

**Issue by gyb001** [dotnet/efcore#24788] opened 2021-04-27 19:45 UTC
I have a Xamarin IOS/Android app which use EntityFreamworkCoreSqlite 5.0.5. 
Trying make full linked version. Android is ok, after read this: [Issue](https://github.com/dotnet/efcore/issues/10963) and add AndroidLinkSkip to Csproj. 
But in **ios** i'm unable to run app with Link All. Work fine in Dont Link and Link Freamwork SDK only. Therefore i think it Linker problem.
No matter that run in Release / Debug / Simulator / RealDevice
When i use the db context for data **_modification_** i got exception. like: `_context.RemoveRange(_context.poi); ` or `_context.AddRange(newPoi);` (_newPoi has correct value and work in android Full link, ios  Dont Link and ios  Link Freamwork SDK)

Exception:  [(Full)](https://pastebin.com/3vvSqq7E)
```
Unhandled Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: source
  at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T] (T value, System.String parameterName) [0x00014] in <60b4caed95534d9e9bba8e623d3661ff>:0 
  at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.Include[TEntity,TProperty] (System.Linq.IQueryable1[T] source, System.Linq.Expressions.Expression1[TDelegate] navigationPropertyPath) [0x00000] in <60b4caed95534d9e9bba8e623d3661ff>:0 
  at myapp.App.Update (System.Threading.Tasks.Task1[TResult] retval) [0x0035b] in F:\a\myapp\myapp\App.xaml.cs:123
```
When trying to **_get_** data from database return null.
Install app in  Dont Link mode. First time create the sqlite db, and seed the it with data.  After a lot of restert everything is fine. [Image](https://ibb.co/sC0Xnj1)
Change to Full Link mode and run again(whitout delete app and keep sqlite.db file). Context always return null. [Image](https://ibb.co/CBYHfTY)
Change back Dont link mode (whitout delete app and keep sqlite.db file) work again. 

```
IOS.csproj
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhoneSimulator' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\iPhoneSimulator\Debug</OutputPath>
    <DefineConstants>DEBUG</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <MtouchArch>x86_64</MtouchArch>
    <MtouchLink>Full</MtouchLink>
    <MtouchDebug>true</MtouchDebug>
    <CodesignKey>iPhone Developer</CodesignKey>
    <CodesignProvision>
    </CodesignProvision>
    <MtouchFloat32>true</MtouchFloat32>
    <MtouchFastDev>true</MtouchFastDev>
    <MtouchSdkVersion>14.4</MtouchSdkVersion>
    <OptimizePNGs>false</OptimizePNGs>
    <MtouchHttpClientHandler>HttpClientHandler</MtouchHttpClientHandler>
    <MtouchNoSymbolStrip>false</MtouchNoSymbolStrip>
    <MtouchEnableSGenConc>false</MtouchEnableSGenConc>
    <MtouchExtraArgs> --linkskip=Microsoft.EntityFrameworkCore --linkskip=Microsoft.EntityFrameworkCore.Relational --linkskip=Microsoft.EntityFrameworkCore.Sqlite --linkskip=Remotion.Linq --linkskip=Microsoft.Data.Sqlite.Core --linkskip=Microsoft.EntityFrameworkCore.Sqlite.Core --linkskip=Microsoft.Extensions.DependencyInjection.Abstractions --linkskip=Microsoft.Extensions.DependencyInjection --linkskip=Microsoft.Extensions.Logging.Abstractions --linkskip=Microsoft.Extensions.Logging --linkskip=Microsoft.Extensions.Caching.Abstractions --linkskip=Microsoft.Extensions.Caching.Memory --linkskip=Microsoft.Extensions.Options --linkskip=Microsoft.Extensions.Primitives --linkskip=System.Reflection --linkskip=System.Reflection.Primitives --linkskip=System.Linq --linkskip=System.Linq.Expressions --linkskip=System.Linq.Queryable  --linkskip=System.Text.Json</MtouchExtraArgs>
  </PropertyGroup>
```
[LinkerDescription](https://pastebin.com/Fqdhcmec)
```
  <ItemGroup>
    <LinkDescription Include="LinkDescription.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </LinkDescription>
  </ItemGroup>
```

```
Shared project: 
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
	<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WarningLevel>0</WarningLevel>
	
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.5" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2012" />
  </ItemGroup>
```
```
AppDelegate
  public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            SQLitePCL.Batteries.Init();
```
Latest VS 2019 community and 2019 Enterprise Preview

Any tipp?

**Comment by gyb001** [comment] 2021-04-28 08:54
Ok. there is a problem with context. 
When linker is active always return null. 

Install app in  Dont Link mode. First time create the sqlite db, and seed the it with data.  After a lot of restert everything is fine. [Image](https://ibb.co/0Y90NNp)
Change to Full Link mode and run again(whitout delete app and keep sqlite.db file). Context always return null. [Image](https://ibb.co/CBYHfTY)
Change back Dont link mode (whitout delete app and keep sqlite.db file) work again.

**Comment by ajcvickers** [comment] 2021-04-28 20:17
Related: #10963

**Comment by ajcvickers** [comment] 2021-04-29 18:25
Verified that this is a duplicate of #10963.

**Closed** 2022-10-16 19:32 UTC
Labels: closed-duplicate, customer-reported
