### ISSUE TITLE
Query/InMemory: incorrect order of elements for query with SelectMany-Where-Take, and double orderby

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#21421] opened 2020-06-26 02:28 UTC
failing test:

SelectMany_predicate_with_non_equality_comparison_with_Take_doesnt_convert_to_join

**Comment by smitpatel** [comment] 2020-06-26 02:32
Duplicate of #17537?

**Closed** 2022-10-16 18:31 UTC
