### ISSUE TITLE
weird dbcontext behavior reading uncommitted updated record

### ISSUE THREAD

**Issue by max-favilli** [dotnet/efcore#17427] opened 2019-08-26 14:43 UTC
In the following code.

```C#
    cartitems old_ci = db.cartitems.FirstOrDefault(i => i.itemid == iteming.itemid);
    cartitems new_ci = db.cartitems.FirstOrDefault(i => i.itemid == iteming.new_itemid);

    new_ci.cartid = old_ci.cartid
    old_ci.cartid = -1;

    cartitems items= db.cartitems.Where(i => i.cartid == new_ci.cartid).ToList();
```

Assuming cartitems contains only one item at the beginning, `items` in the last line contains `old_ci` with property `cartid` set to -1, and no entry for `new_ci`.

I migrated this code from an old net classic project using EF6 where the result was different, `items` at the end contained only one entry with `new_ci` values with `cartid` property set to the new value.

**Is this the intende behavior with EF Core?**

Or am I doing something wrong?

In the actual project the first part of my explanatory code is in one method, the late read from cartitems is in a different one, they are both called sequentially inside the same controller within the same scope of `dbContext`, which is injected as a service in `startup.cs` with `services.AddDbContext`

_Why I am doing this._ The application is doing changes to some data (basically changing the customer cart), recalculating some other data (cart totals) and then depending on the outcome is saving or not saving the changes to the database.

EF Core version: 2.2.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro 1809 17763.678
IDE: VisualStudio 2019 16.2.3

**Comment by ajcvickers** [comment] 2019-09-06 16:29
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:38 UTC
Labels: closed-could-not-reproduce, customer-reported
