### ISSUE TITLE
Creating QueryTask

### ISSUE THREAD

**Issue by aburakab** [dotnet/efcore#22002] opened 2020-08-10 09:46 UTC
`QueryTask` will help us to do a single roundtrip for all queries.

```csharp
var customersQueryTask = context.Customers.AsQueryTask();
var productsQueryTask = context.Products.AsQueryTask();

// One roundtrip to Database
await QueryTask.WhenAll(customersQueryTask, productsQueryTask);
var customer = customersQueryTask.Result;
var products = productsQueryTask.Result;
```
I'm not sure if we have something similar in the current version?

**Updated:**
Looks like the Future Queries Here are doing the same thing
https://entityframework-plus.net/query-future

**Comment by roji** [comment] 2020-08-10 13:27
Duplicate of #10879

**Comment by roji** [comment] 2020-08-10 13:27
Executing multiple LINQ queries in a single batch/roundtrip is trakced by #10879.

Specifically for the code above, AsQueryTask isn't part of EF Core or standard .NET, where is it coming from? Note that EF Plus is a separate product that isn't maintained by the EF Core team.

**Comment by aburakab** [comment] 2020-08-10 13:30
It's just an Idea (AsQueryTask is not exist)! and I realized that it's called ".Future" in that Product.

**Comment by roji** [comment] 2020-08-10 13:31
OK, thanks for clarifying. This indeed looks like a duplicate of #10879.

**Closed** 2022-10-16 18:36 UTC
Labels: customer-reported
