### ISSUE TITLE
Cannot add an owned entity if owner was originally saved without one - "no entity of this type with the same key value that has been marked as 'Added'" error

### ISSUE THREAD

**Issue by jonathanmoffatt** [dotnet/efcore#18991] opened 2019-11-20 00:17 UTC
Previously in EF Core 2.2 we would ensure that owned entities were always newed up in the constructor of the owner.

Under EF Core 3.0, however, changes to our owned entities are not being persisted if the owner was originally saved with an owned entity with all fields set to null.

I figure this is due to the breaking change "[dependent entities sharing the table with the principal are now optional](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#de)"?

However, if I try to add the owned entity to the owner later I get the error:

```
The entity of type 'Address' is sharing the table 'dbo.Order' with entities of type 'Order', 
but there is no entity of this type with the same key value that has been marked as 'Added'.
```

Can anyone tell me what I'm doing wrong? I know I can add a required property to the entity type which would solve the problem... but surely this shouldn't be required just so I can set an owned entity later?

### Steps to reproduce

``` c#
class Program
{
    static void Main()
    {
        Console.WriteLine("Running...");
        using (var db = new OurContext())
        {
            Order order = db.Orders.SingleOrDefault();
            if (order != null)
            {
                db.Remove(order);
                db.SaveChanges();
                Console.WriteLine("...removed existing order");
            }
        }

        // if Order is created with postal address, it can be updated fine
        using (var db = new OurContext())
        {
            db.Add(new Order
            {
                Description = "works when owned entity is populated",
                ShippingAddress = new Address {Postcode = "2606", Suburb = "OCONNOR"}
            });
            db.SaveChanges();
            Console.WriteLine("...created new order with shipping address");
        }
        using (var db = new OurContext())
        {
            Order order = db.Orders.Single();
            order.ShippingAddress.Suburb = "LYNEHAM";
            db.SaveChanges();
            Console.WriteLine("...updated shipping address");
        }
        using (var db = new OurContext())
        {
            Order order = db.Orders.Single();
            Console.WriteLine($"...shipping address suburb is {order.ShippingAddress.Suburb}");
        }
        using (var db = new OurContext())
        {
            Order order = db.Orders.Single();
            db.Remove(order);
            db.SaveChanges();
            Console.WriteLine("...deleted order");
        }

        // but if Order is created without a shipping address, I don't seem to be able to add one
        using (var db = new OurContext())
        {
            db.Add(new Order {Description = "saves OK with a null owned entity"});
            db.SaveChanges();
            Console.WriteLine("...created new order without a shipping address");
        }
        
        Console.WriteLine("...trying to add a shipping address to order");
        using (var db = new OurContext())
        {
            Order order = db.Orders.Single();
            order.ShippingAddress = new Address {Postcode = "2606", Suburb = "CHIFLEY"};
            try
            {
                // this errors with message:
                // "The entity of type 'Address' is sharing the table 'dbo.Order' with entities of type 'Order',
                // but there is no entity of this type with the same key value that has been marked as 'Added'."
                db.SaveChanges();
            }
            catch (Exception ex)
            {
                Console.WriteLine("...failed");
                Console.WriteLine(ex.ToString());
            }
        }

    }

}

public class Order
{
    public int Id { get; set; }
    public string Description { get; set; }
    public Address ShippingAddress { get; set; }
}

public class Address
{
    public string Suburb { get; set; }
    public string Postcode { get; set; }
}

public class OrderMapping : IEntityTypeConfiguration<Order>
{
    public void Configure(EntityTypeBuilder<Order> entity)
    {
        entity.ToTable("Order", "dbo");
        entity.HasKey(e => e.Id);
        entity.Property(e => e.Id).IsRequired().ValueGeneratedOnAdd();
        entity.Property(e => e.Description);
        entity.OwnsOne(e => e.ShippingAddress);
    }
}

public class OurContext : DbContext
{
    public DbSet<Order> Orders { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(
                "Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=EfOwnedEntityTestbed;Data Source=(local)\\MSSQLSERVER2017");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new OrderMapping());
    }
}

public class DesignTimeDbContextFactory : IDesignTimeDbContextFactory<OurContext>
{
    public OurContext CreateDbContext(string[] args) => new OurContext();
}

```

### Further technical details

EF Core version: 3.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Win 10
IDE: Visual Studio 2019 16.3.5

**Comment by AndriySvyryd** [comment] 2019-11-20 02:49
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/17422

**Closed** 2022-10-16 14:57 UTC
Labels: customer-reported
