### ISSUE TITLE
Still this issue not being fixed until now 

### ISSUE THREAD

**Issue by M-JOXx** [dotnet/efcore#34265] opened 2024-07-22 07:00 UTC
hello 

I'm  working  on **blazor** application using simple repository pattern 

but it throw this exception 
**The instance of entity type 'Product' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked.**

**I Follow these steps** 
- First I have fetch the product first  ( Also i use AsNoTracking() but none of them it work):

//Product Repository
 ```
   public Product GetById(Guid? Id)
    {
        try
        {
            if(Id is not null)
            {

                var data = _context
                    .Products;

                var product = data
                    .FirstOrDefault(x => x.Id == Id);

                if (product is not null)
                {
                    return product;
                }
            }

        }
        catch (Exception ex)
        {
            _logger.LogInformation(ex.Message);
        }

        return null;
    }
```

- Then Update the product 

     public async Task<Product> Edit(Product entity)
  {
      try
      {
          _context
              .Products
              .Update(entity);

          await _context.SaveChangesAsync();

          return entity;
      }
      catch (Exception ex)
      {
          _logger.LogInformation(ex.Message);
      }

      return null;
  }
```



// Program.cs

     ```
  builder.Services.AddDbContext<ApplicationDBContext>(options =>
      options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection"));

      builder.Services.AddServices();
```



// ServicesExtentions.cs

```
  public static IServiceCollection AddServices(this IServiceCollection services)
 {
     services.AddScoped<ICategory, CategoryRepository>();
     services.AddScoped<IProduct, ProductRepository>();

     return services;
 }
```

**Comment by ajcvickers** [comment] 2024-08-12 08:41
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2024-08-26 11:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-08-26 11:20 UTC
Labels: customer-reported, area-change-tracking
