### ISSUE TITLE
Bug in Navigation Fixer when replacing records that contain a HashSet

### ISSUE THREAD

**Issue by InspiringCode** [dotnet/efcore#26745] opened 2021-11-18 10:41 UTC
# Summary

Given the following steps:
1. An entity has a one-to-one relationship to a record type (`User` has `UserInfo`)
2. The record type has a HashSet (`ProxyAddress`)
3. The record intsance is replaced with a new instance that has a different (but overlapping) HashSet of children
4. The changes are saved

Then the overlapping items of the HashSet are removed erroneously from the HashSet of the new record instance.

I have attached a running example: [BugDemo.zip](https://github.com/dotnet/efcore/files/7562086/BugDemo.zip).

# Entities

```csharp
internal class User : Entity {
    public UserInfo Infos { get; set; }
}

internal record UserInfo {
    public Guid Id { get; set; } = Guid.NewGuid();

    // If HashSet is changed to List everything works perfectly fine!
    public HashSet<ProxyAddress> ProxyAddresses { get; set; } = new();
}

internal record ProxyAddress(string Mail);
```

# Mapping

```csharp
internal class RecordListBugDb : DemoDbBase {
    protected override void CreateModel(ModelBuilder mb) {
        mb.Entity<User>(e => {
            e.HasOne(x => x.Infos).WithOne().HasForeignKey<UserInfo>(x => x.Id);
            e.Navigation(x => x.Infos).AutoInclude(true);
        });

        mb.Entity<UserInfo>(e => {
            e.OwnsMany(x => x.ProxyAddresses, r => {
                r.WithOwner().HasForeignKey("UserId");
                r.HasKey("UserId", nameof(ProxyAddress.Mail));
            });
        });
    }
}
```

# Code to reproduce

```csharp
var db = new RecordListBugDb();
User u = new User {
    Infos = new UserInfo {
        ProxyAddresses = { new ProxyAddress("A1"), new ProxyAddress("A2") }
    }
};
db.Add(u);
db.SaveChanges();

db = new();

u = db.Set<User>().Find(u.Id);
u.Infos = u.Infos with {
    ProxyAddresses = new() { new ProxyAddress("A1"), new ProxyAddress("A3") }
};
db.SaveChanges();


// This should print "A1" and "A3", but just "A3" is printed
foreach (ProxyAddress adr in u.Infos.ProxyAddresses)
    Console.WriteLine(adr.Mail);
```

# Supposed source of bug

The removal occurs when `SaveChanges` is called. I tried to replace `HashSet` with a custom `ISet` and set a breakpoint in the `Remove` method. It is called by the `NavigationFixer` class. With the custom `ISet` the behavior was even stranger (all items where removed). The interesting part seems to be:

```csharp
foreach (var newValue in added)
{
    var newTargetEntry = stateManager.GetOrCreateEntry(newValue, targetEntityType);
    [...]
    var foreignKey = ((INavigation)navigationBase).ForeignKey;

    // For a dependent added to the collection, remove it from the collection of
    // the principal entity that it was previously part of
    var oldPrincipalEntry = stateManager.FindPrincipalUsingRelationshipSnapshot(newTargetEntry, foreignKey);
    if (oldPrincipalEntry != null
        && oldPrincipalEntry != entry)
    {
        RemoveFromCollection(oldPrincipalEntry, navigationBase, newTargetEntry);
    }

    // Set the FK properties on added dependents to match this principal
    SetForeignKeyProperties(newTargetEntry, entry, foreignKey, setModified: true, fromQuery: false);

    // Set the inverse navigation to point to this principal
    SetNavigation(newTargetEntry, inverse, entry, fromQuery: false);
    [...]
```

### Version infos:
EF Core version: 5.0.12
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0

**Comment by ajcvickers** [comment] 2021-11-18 10:55
Duplicate of #25610. See https://github.com/dotnet/efcore/issues/25610#issuecomment-904566909

**Comment by InspiringCode** [comment] 2021-11-18 11:16
> Duplicate of #25610. See [#25610 (comment)](https://github.com/dotnet/efcore/issues/25610#issuecomment-904566909)

Thank you very much for the fast reply! The suggested solution (Reference Equality) is not really a solution. Must of the time one wants to use a HashSet exactly because you want value semantics, otherwise one could just simply use a list...

**Comment by ajcvickers** [comment] 2021-11-18 11:24
@InspiringCode EF Core doesn't support multiple instances of the same entity. Generally, using objects with value semantics as entity types is not going to work.

**Closed** 2022-10-16 20:15 UTC
Labels: closed-duplicate, customer-reported
