### ISSUE TITLE
null exception when I try to include a property which parent can be null

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#9659] opened 2017-08-31 15:12 UTC
I am try to do this query:

`await myDbContext.MyType.Where(x => x.ID = 1 || x.ID == 2)
.Include(x => x.MyPropertyThatAllowsNull).ThenInclude(x => x.MyPropertyThatNotAllowNull)
.ToListAsync();`

But I get an exception of null reference.

If I only try to include the first property, MyPropertyThatAllowsNull it works but if I try to include MyPropertyThatNotAllowNull I get the exception.

Type of MyPropertyThatAllowsNull is MyTypeB and MyPropertyThatNotAllowNull is a ICollection of MyTypeC.

Really I guess that this case is simple enough to prepare an example, but if you need, I could do it.

Thanks.

EDIT: If I use the sync method (ToList()) I don't get this error.

**Comment by ajcvickers** [comment] 2017-08-31 16:56
@ComptonAlvaro What version of EF Core are you using, what provider are you using, and what is the full stack trace?

**Comment by ComptonAlvaro** [comment] 2017-08-31 17:20
I am using Microsoft.EntityFrameworkCore.SqlServer 2.0.0 as data provider and Microsoft.EntityFrameworkCore 2.0.0 as EF Core version.

The stack trace is this:
`"   en Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.<_IncludeAsync>d__18`1.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.<_ExecuteAsync>d__8`1.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   en Myproject.<MyMethodAsync>d__22.MoveNext()"`

**Comment by johanskoldekrans** [comment] 2017-09-04 09:13
I get this on 2.0.0 as well. Looks fixed in 2.1.0-preview1 but will you do a patch soon? Cannot publish previews in production and I have spent almost five days rewriting code to make 2.0 fixed so downgrading to efcore/dotnet core 1.1.0 isnt a solution.

Why do you both add new functionality and bug fixes to version 2.1 instead of patching fixes of obvious bugs directly to 2.0?

**Comment by grokky1** [comment] 2017-09-04 11:07
@johanskoldekrans I assume you're using the latest myget `2.1.0-preview1-26905`.

Are you using the `Microsoft.EntityFrameworkCore` or for `Microsoft.AspNetCore.All` nuget package?

**Comment by johanskoldekrans** [comment] 2017-09-04 11:25
Can I use Microsoft.AspNetCore.All for EntityFramework as well?
```

<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="2.0.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>
```

**Comment by grokky1** [comment] 2017-09-04 13:44
@johanskoldekrans Yes it's the new "metapackage".

**Comment by johanskoldekrans** [comment] 2017-09-04 14:10
2.1.0-preview1-26816 was the last one I worked with. As stated above this works in the previews but I can't publish preview into production.

I have also looked for newer versions of the server hosting for windows but haven't found any yet that can host the newest preview-builds on an IIS. 

So above works in the latest fixes you have made but I am looking for a patch for 2.0 since this is not something you can wait for that long to get fixed.

Ps. I will fix the ref to the metapackage although it only works if you are not targeting .net framework. the documentation is unclear on why/why not this is the case. Removing all refs didn't work for me in the beginning. Maybe it is fixed now.

**Comment by grokky1** [comment] 2017-09-04 16:53
@johanskoldekrans Agreed.

But was I meant was are you using version `2.1.0-preview1-26816` for ALL the packages you listed above, or only for the `Microsoft.EntityFramework.*` packages?

**Comment by johanskoldekrans** [comment] 2017-09-04 17:04
@grokky1 Oh, sorry. :-)

Yes all packages from Microsoft was the same version. I try to keep them all together, easier now when they all are released simultaneously.

**Comment by smitpatel** [comment] 2017-09-12 19:48
Duplicate of #9038

**Comment by Looooooka** [comment] 2018-06-08 12:02
this is broken in the 2.1 release
queries which worked in 2.0 throw this exception. 

I had to change all queries from

select t.Value).DefaultIfEmpty(0).Sum()
to
select t).Sum(tc => (Decimal?)tc.Value) ?? 0


and using .First instead of .FirstAsync

because event with the fix the async version kept throwing:

System.InvalidOperationException: 'No coercion operator is defined between types 'System.Threading.Tasks.Task`1[System.Decimal]' and 'System.Nullable`1[System.Decimal]'.'

**Comment by Looooooka** [comment] 2018-06-08 18:12
Uploaded a sample and opened issue 12308

**Closed** 2022-10-16 11:20 UTC
