### ISSUE TITLE
ValueGeneratedOnAdd does not work with ValueConverter

### ISSUE THREAD

**Issue by rick-palmsens** [dotnet/efcore#23117] opened 2020-10-28 13:45 UTC
### Description

I have a strongly typed key and a value converter that can convert between the key and the internal `Guid`. However, when I try to combine it with `ValueGeneratedOnAdd`, it seems to forget how to do the conversion.

### The Converter
```C#
public class EntityReferenceConverter<TEntity> : ValueConverter<EntityReference<TEntity>, Guid>
    where TEntity : class, IEntity
{
    public EntityReferenceConverter():
        base(entityReference => entityReference.Value,
             guid => new EntityReference<TEntity>(guid),
             new ConverterMappingHints(valueGeneratorFactory: (p, t) => new TemporaryGuidValueGenerator()))
    {
    }
}
```

### The Configuration
```C#
builder
    .HasKey(entity => entity.Id);

builder
    .Property(entity => entity.Id)
    .ValueGeneratedOnAdd()
    .HasConversion(new EntityReferenceConverter<TEntity>());
```

### The Exception
> Unable to cast object of type 'System.Guid' to type 'PalmSens.Core.Domain.Values.EntityReference`1[PalmSens.Core.Domain.Entities.Session]'.

### The StackTrace
```
   at Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer`1.Equals(Object left, Object right)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.<>c__DisplayClass86_0.<ValuesEqualFunc>b__0(Object l, Object r)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete, CurrentValueType valueType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetTemporaryValue(IProperty property, Object value, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ValueGenerationManager.Generate(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity](TEntity entity)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
   at PalmSens.Core.Application.Commands.NewSession.Handler.Handle(Command command, IDatabaseContext databaseContext, CancellationToken cancellationToken) in C:\...\NewSession.cs:line 38
```

### Version Info
EF Core version: 3.1.9
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET Standard 2.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.6

**Comment by davidroth** [comment] 2020-10-28 15:06
I think this is already tracked by: https://github.com/dotnet/efcore/issues/11597

**Comment by ajcvickers** [comment] 2020-10-30 19:39
@rick-palmsens I am not able to reproduce the exception you are seeing--see my code below. Instead I see `System.NotSupportedException: Value generation is not supported for property 'Blog.Id' because it has a 'EntityReferenceConverter<Blog>' converter configured. Configure the property to not use value generation using 'ValueGenerated.Never' or 'DatabaseGeneratedOption.None' and specify explicit values instead.` which is what I would expect based on #11597.

If you think there is another issue here, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog());
        
            context.SaveChanges();
        }
        
        using (var context = new SomeDbContext())
        {
            var blog = context.Set<Blog>().Single();
        }
    }
}

public class SomeDbContext : DbContext
{
    private static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().SetMinimumLevel(LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>()
            .HasKey(entity => entity.Id);

        modelBuilder.Entity<Blog>()
            .Property(entity => entity.Id)
            .ValueGeneratedOnAdd()
            .HasConversion(new EntityReferenceConverter<Blog>());
    }
}

public interface IEntity
{
}

public class Blog : IEntity
{
    public EntityReference<Blog> Id { get; set; }
}

public class EntityReference<TEntity>
{
    public EntityReference(Guid value)
    {
        Value = value;
    }

    public Guid Value { get; set; }
}

public class EntityReferenceConverter<TEntity> : ValueConverter<EntityReference<TEntity>, Guid>
    where TEntity : class, IEntity
{
    public EntityReferenceConverter():
        base(entityReference => entityReference.Value,
            guid => new EntityReference<TEntity>(guid))
    {
    }
}
```

**Comment by ajcvickers** [comment] 2020-11-09 15:54
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:06 UTC
Labels: closed-could-not-reproduce, customer-reported
