### ISSUE TITLE
Is there a method to intercept query expression tree in EF Core?

### ISSUE THREAD

**Issue by Li7ye** [dotnet/efcore#24711] opened 2021-04-21 09:59 UTC
For instance, a certain entity has two global filters. However, I want to disable one of the global filters in the certain condition without calling `IgnoreQueryFilters` function and explicitly invoking `Where` function in `Queryable` class. 

Please give me advice for this requirment. Thanks.

**Comment by roji** [comment] 2021-04-22 08:58
Duplicate of #24721

**Closed** 2022-10-16 19:32 UTC
Labels: closed-duplicate, customer-reported
