### ISSUE TITLE
DbContext Instance gets Disposed.

### ISSUE THREAD

**Issue by yadavvineet** [dotnet/efcore#29197] opened 2022-09-24 22:11 UTC
## Overview, 
I am facing a Weird issue. To give a high level understanding, i have the following set of code. 
Controller -> Business Layer -> Controller (validate first level result with input) -> Business Layer (further processing) -> Result to controller .
However, I am facing this challange that when the flow goes to Business Layer, second time, it does a get query which succeeds and then it tries to save something. At that point EF throws the exception that Instance is already disposed. 

## What i am using 
i am using Pomelo with EF version 6.0.2. Tried reverting to 6.0.1, no resort

### What i have validated. 

- All async await usages, 
- All dispos calls / using blocks - there is none.
- Tried passing in reference or removing the order / flow in second call,  - it doesnt worked. 
- There is nothing in the call which could ignite the dispose object

## What worked. 
I removed the middle controller flow.  and it worked without any code  / flow change, which was breaking earlier.
now flow is like : Controller - Business Layer - Controller. 
I have not seen this type of error earlier in such flow where if the call goes out  of a **method** in a class (business layer) objects are disposed. Further, in second call to business layer method, there is a get call which succeeds all the time, but the next update fails. Its a plain  update on an object on navigation property.

**Intrestingly,** by just removing hop to controller , it works. 

### Include provider and version information

EF Core version: 6.0.9
Database provider: Pomelo.EntityFrameworkCore.MySql 6.0.2
Target framework: .NET 6
Operating system: WIndows 11, VS 22

PS: There is not much of code i can share, if needed i can come up on a call to show the issue. I did tried exploring multiple forums to see if i am missing something, but everything seems to be by the book. and this is first time i have seen the issue.

**Comment by roji** [comment] 2022-09-24 22:21
@yadavvineet it's a bit hard to understand from such a textual description exactly what you're doing; but what's very probable is that one of your layers is disposing your DbContext instance, and then some other layer attempts to use that context. If you need further assistance in pinpointing the problem, you'll have to submit a minimal, runnable code sample which demonstrates the issue.

**Comment by yadavvineet** [comment] 2022-09-24 22:28
thanks @roji  let me see if i can try to do a minimal version to add here.

**Comment by ajcvickers** [comment] 2022-10-11 11:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-10-11 11:42 UTC
Labels: customer-reported
