### ISSUE TITLE
Policy validation

### ISSUE THREAD

**Issue by marianogenovese** [dotnet/efcore#6440] opened 2016-08-30 21:57 UTC
I want to implement a policy validation for entities where i can pre check if a user can insert/update/delete/query an entity, but i dont see anything at ef core level, at db command level maybe in IUpdateSqlGenerator for insert/update/delete but i think this is not right because is not on top of all specific database providers (implementations), is there something at core level or something at tree level like IDbCommandTreeInterceptor (EF6) ?

My motive to make this question is because i need to implement a web application with owasp security controls in mind, specialy  A4 – Insecure Direct Object References. A policy validation is usefull to add a security level to data access.

Thanks.

**Comment by skimmilk** [comment] 2016-08-31 05:27
Authorizing requests coming from the web should really be done in the application layer, not the database.  [Here's a framework](https://docs.asp.net/en/latest/security/authentication/identity.html) that's very useful for authentication & authorization which integrates with EF Core and ASP.NET MVC, and is also written by the same .NET teams at Microsoft.  So try checking out [aspnet/Identity](https://github.com/aspnet/Identity) or some other framework first.

**Comment by marianogenovese** [comment] 2016-08-31 15:30
I know that framework, but some security validations are in database layer like i can only query/create/delete/update some entities with specific values because my user profile must have that specific value, for example i can only query records from a organization in which my user profile has been asigned.

**Comment by divega** [comment] 2016-10-13 01:55
In general it should be possible to perform this kind of validation at the application level if there are controller actions that map to CUD operations on specific tables. The controller actions could then inspect values and execute additional logic to decide whether the operation is allowed for the specific user.

But if the mapping between the controller action and the database objects and operations isn't 1:1 then I agree there would be value in having a way to achieve this kind of validation in the data layer.

We currently don't have any feature we have designed to do this. E.g. there is no `IDbCommandTreeInterceptor` in EF Core and update commands are not represented as expressions that can be parsed and reasoned about. 

Currently it should be possible to satisfy some validation needs by overriding the `SaveChanges()` method as described in the blog post at https://blogs.msdn.microsoft.com/dotnet/2016/09/29/implementing-seeding-custom-conventions-and-interceptors-in-ef-core-1-0/. 

Deeper support for this scenario could be added as part of lifecycle hooks (see #626).

**Comment by divega** [comment] 2016-10-13 01:58
Note for triage: I think this can be closed as a dupe of lifecycle hooks #626. I added a comment there about this scenario.

**Closed** 2022-10-16 09:56 UTC
