### ISSUE TITLE
Self referencing table auto includes parent and child properties

### ISSUE THREAD

**Issue by dpedrelli** [dotnet/efcore#11149] opened 2018-03-04 17:22 UTC
Describe what is not working as expected.
I have a self referencing table, with a one-to-many relationship, define in Fluent API.  It includes a virtual property for the parent, and a virtual ObservableCollection<> for the children.  There are other one-to-many relationships, with virtual properties, that point to other tables.  When I use EntityFramework to query the table, it automatically includes both the self-referencing, parent and children properties, even though I do not specify .Include().  The secondary related tables, I do not specify .Include, and they are not returned.  One row has more than 8,000 child rows, and it is causing my WepAPI calls to fail.

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
public class Supplier
{
        public virtual Supplier ParentCompany { get; set; }
        public virtual ObservableCollection<Supplier> ChildCompanies { get; set; }
        public virtual SupplierMember MemberSupplier { get; set; }
        public virtual ObservableCollection<SupplierAlias> Aliases { get; set; }
        public virtual ObservableCollection<SupplierContact> Contacts{ get; set; }
}

var result = await _context.Supplier.Include(e => e.MemberSupplier).OrderBy(e => e.CompanyName).ToListAsync();
```

result includes MemberSupplier, which is expected.  It does not include Aliases or Contacts, because I did not specify them.  However, it does include ParentCompany and ChildCompanies.  I expect these properties to not be included.

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7
IDE: Visual Studio 2017 15.5.7

**Comment by ajcvickers** [comment] 2018-03-05 18:33
@dpedrelli What you describe seems to be working as designed. That is, when performing a normal tracking query, all relationships between entities in the query are "fixed up"--i.e. the navigation properties are set/populated with entities based on the FK values in the loaded entities. This happens regardless of whether or not Include is used explicitly on those relationships. This is a service provided by the context when entities are tracked, so to avoid this behavior a no-tracking query can be used. With a no-tracking query, only the relationship explicitly included will have navigation properties set/populated. However, note that both sides of the relationship will be fixed up regardless of which side is used to specify the relationship in the Include call. 

If this doesn't answer your question, then can you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing so we are able to investigate more?

**Closed** 2022-10-16 12:12 UTC
Labels: closed-by-design
