### ISSUE TITLE
C# 9 Top-Level Statements prevents Update-Database from working

### ISSUE THREAD

**Issue by dolphyns** [dotnet/efcore#24149] opened 2021-02-14 05:52 UTC
Message from the Update-Database
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly '###'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.

If I rollback to the full Program.Main it works.

I apologize for the brevity if my text. It is the first time I open an issue and I am not ever very sure it is really a bug.

**Comment by Youssef1313** [comment] 2021-02-14 08:06
This could be an external issue. Resolving `CreateHostBuilder` is done by dotnet/runtime:

https://github.com/dotnet/runtime/blob/4634681ec8271a2ff2a4c959a8471fc90702f553/src/libraries/Microsoft.Extensions.HostFactoryResolver/src/HostFactoryResolver.cs

**Comment by Youssef1313** [comment] 2021-02-14 08:07
Most likely, the following line is returning null:

https://github.com/dotnet/runtime/blob/4634681ec8271a2ff2a4c959a8471fc90702f553/src/libraries/Microsoft.Extensions.HostFactoryResolver/src/HostFactoryResolver.cs#L36

**Comment by ErikEJ** [comment] 2021-02-14 08:13
Duplicate of #23471

**Closed** 2022-10-16 19:23 UTC
Labels: closed-duplicate, customer-reported
