### ISSUE TITLE
Where clause with navigation property not translate correctly and then it's evaluate locally

### ISSUE THREAD

**Issue by augugiacoEnta** [dotnet/efcore#6797] opened 2016-10-17 17:45 UTC
Hi everybody,

I have a problem with a small query in the where clause in EF Core. I have a entity "Charge" that have a nulleable property called TicketId and I have an entity called Ticket with some properties.
The problem is this:

If I execute this query: 

dbContext.Charges.Where(x => x.Ticket.DateCreated >= DateTime.Today).ToList();

The result is this:

SELECT [x].[Id], [x].[Amount], [x].[Date], [x].[TicketId], [x.Ticket].[Id], [x.Ticket].[Amount], [x.Ticket].[DateCreated]
FROM [Charges] AS [x]
LEFT JOIN [Tickets] AS [x.Ticket] ON [x].[TicketId] = [x.Ticket].[Id]
ORDER BY [x].[TicketId]

As you see, there is not any where clause in the query.

In the output, I have this:

Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Warning: The LINQ expression 'DefaultIfEmpty()' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Warning: The LINQ expression 'DefaultIfEmpty()' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Warning: The LINQ expression 'from Ticket x.Ticket in {[x.Ticket_group] => DefaultIfEmpty()}' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Warning: The LINQ expression '(IIF(([x.Ticket] != null), Convert([x.Ticket].DateCreated), null) >= Convert(__Today_0))' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.

I have 1.0.1 EF Core version.

I attached a small runneable for that you can test this!

[EfCoreBug.zip](https://github.com/aspnet/EntityFramework/files/534264/EfCoreBug.zip)

Thanks a lot!

Regards!

Augusto.

**Comment by maumar** [comment] 2016-10-17 17:56
This is a duplicate of https://github.com/aspnet/EntityFramework/issues/4588. The issue is fixed now and will be released in 1.1.0

**Closed** 2022-10-16 10:38 UTC
