### ISSUE TITLE
OData Expand- Value cannot be null. (Parameter 'key')

### ISSUE THREAD

**Issue by huiali** [dotnet/efcore#21562] opened 2020-07-08 13:28 UTC
expand
GET : https://localhost:5002/oq/A?$expand=B($expand=C)-->
ERROR --> Value cannot be null. (Parameter 'key')

Sample：
[https://github.com/huiali/odata-sample](https://github.com/huiali/odata-sample)
OData Issues:
[https://github.com/OData/WebApi/issues/2218](https://github.com/OData/WebApi/issues/2218)

EF Core version:
Database provider: (e.g. Pomelo.EntityFrameworkCore.MySql)
Target framework: (e.g. .NET Core 3.1)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment] 2020-07-09 15:48
Since the exception stack trace only involves OData model building but not likely an EF issue. I am closing this as duplicate of https://github.com/OData/WebApi/issues/2124

If the root cause of error comes to EF Core then we can reopen.

**Closed** 2022-10-16 18:32 UTC
Labels: closed-external, customer-reported
