### ISSUE TITLE
Enable required dependents when using table splitting

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#15607] opened 2019-05-03 21:41 UTC
See #9005 and #15521

Note that this does not mean requireness needs to be enforced. It just means that we assume if the relationship is configured as required that we don't need to do anything special to enable it to be optional.

**Comment by ajcvickers** [comment] 2019-07-11 19:04
Talked again to @AndriySvyryd and @smitpatel on this. Despite what I said in May I now understand why it makes sense to punt this.

This change would allow a dependent in a split table to have all null values for it's properties, and yet still get an entity instance materialized. This is not the same as making the relationship required, since that still allows a principal to exist without a dependent. This therefore requires new API, and is, relatively speaking a corner case.

**Comment by AndriySvyryd** [comment] 2019-09-08 21:15
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/12100

**Closed** 2022-10-16 14:20 UTC
Labels: closed-duplicate
