### ISSUE TITLE
Same table multiple classes

### ISSUE THREAD

**Issue by herme063** [dotnet/efcore#13162] opened 2018-08-30 02:48 UTC
Let me first start with: this is not table hierarchy. 

I have 2 assemblies that share the same **concept** Person. In the 1st assembly, Person is a class with 5 properties but in the 2nd one it only has 2 properties (the bare minimum Id and Name). Each assembly has a db context. I am creating a 3rd assembly to enable a combined code first migration for both db contexts. I am using fluent api to configure both models: ToTable("People", "dbo").

When I create the migration, I get the following message: `Cannot use table 'dbo.People' for entity type 'Person' since it is being used for entity type 'Person' and there is no relationship between their primary keys.`

Is there a way I can make this work? If not, what is the correct way to handle this scenario.

**Comment by ajcvickers** [comment] 2018-08-30 17:58
Note for triage: consider creating the PK to PK relationship automatically in this case?

@herme063 Something like this:
```C#
namespace One
{
    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

namespace Two
{
    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Birthday { get; set; }
    }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<One.Person>(b =>
        {
            b.HasOne<Two.Person>().WithOne().HasForeignKey<Two.Person>(e => e.Id);
            b.ToTable("People");
            b.Property(e => e.Name).HasColumnName(nameof(One.Person.Name));
        });

        builder.Entity<Two.Person>(b =>
        {
            b.ToTable("People");
            b.Property(e => e.Name).HasColumnName(nameof(One.Person.Name));
        });
    }
}
```
Couple of notes on this:
* The relationship is configured between the two PK properties with no navigations; navigations can be added if needed.
* Properties, like Name, that exist in both types will by convention get mapped to different columns, but this can be overridden as shown above by explicitly mapping them to the same column.

**Comment by herme063** [comment] 2018-08-30 20:39
Looks good, thank you.

**Comment by ajcvickers** [comment] 2018-09-05 20:00
Discussed in triage, and decided that at least for now the relationship needs to be configured such that the principal and dependent are know, which is important for support of option dependents with table splitting.

**Comment by leandrocervelin** [comment] 2019-04-24 11:45
@ajcvickers Hi, could you help me with a doubt, please?
I have different contexts in two different domains and each domain contains an entity "country". The contexts do not know each other and I can not configure how you have done in the above example. The issue is that I am getting the error: "There is already an object named 'Country' in the database." What is the best approach in this case, please?

**Comment by ajcvickers** [comment] 2019-04-24 14:55
@leandrocervelin Sounds like you might be having migrations for both context types create the Country table. We have a feature (#2725) for allowing an entity type to be excluded from the migrations of one or the other context types. For now, the way to handle this is to edit the migration for one context type and remove the parts that create this table.

**Comment by leandrocervelin** [comment] 2019-04-24 15:26
Thank you very much for reply @ajcvickers.
If I understood correctly, you mean use something like this: 

modelBuilder.Ignore<Country>();

But, there is a collection that exists only for this entity, and if I use this approach, the FK will not be created in the other table. If I'm not wrong, of course.

Thank you again.

**Comment by progmars** [comment] 2019-08-05 22:00
I have a similar problem with a table which needs two representation entity classes - one with full set of fields and the other one with partial fields. While the trick with
`b.HasOne<Two.Person>().WithOne().HasForeignKey<Two.Person>(e => e.Id);` worked for reading and update, it still failed when attempting to create the full-featured entity with an error:
```
The entity of type 'X' is sharing the table 'Xes' with entities of type 'SimplifiedX', but there is no entity of this type with the same key value that has been marked as 'Added'. 
```

I guess, I'll have to create an SQL view just to decouple that simplified entity from the  'Xes' table. I'd really like not to, because that's a legacy chaotic database and it takes lots of bureaucracy to negotiate the changes with the maintainers of the database.

Is there any way to tell EF "please ignore the fact that these two entities have the same table name; treat them as totally unrelated"?

**Comment by AndriySvyryd** [comment] 2019-08-06 03:44
@progmars https://github.com/aspnet/EntityFrameworkCore/issues/15310 should allow your scenario to work as expected

**Comment by MHDuke** [comment] 2019-11-30 12:51
@ajcvickers when i try to `add-migration` i get
>  'Party.Name' and 'Agent.Name' are both mapped to column 'Name' in 'Parties' but are configured with different nullability.
public class Entity
   {
       public virtual int Id { get; protected set; }
   }

public class Party : Entity
    {
        public string Name { get; private set; }
        public decimal CreditLimit { get; private set; }
    }
public class Agent : Entity
    {
        public string Name { get; private set; }
    }

```
```
public void Configure(EntityTypeBuilder<Party> b)
        {
            b.ToTable("Parties");

            b.Property(e => e.Name).HasColumnName(nameof(Party.Name))
                .HasMaxLength(100)
                .IsRequired();

            b.HasOne<Agent>().WithOne()
                .HasForeignKey<Agent>(e => e.Id)
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Property(e => e.CreditLimit)
                .IsRequired()
                .HasColumnType("decimal(18,2)");
        }
public void Configure(EntityTypeBuilder<Agent> b)
        {
            b.ToTable("Parties");

            b.Property(e => e.Name).HasColumnName(nameof(Agent.Name))
                .HasMaxLength(100)
                .IsRequired();
        }
```

**Comment by ajcvickers** [comment] 2019-12-02 22:43
@MHDuke Please file a new issue and include a small, runnable project/solution or complete code listing.

**Comment by AndriySvyryd** [comment] 2019-12-03 08:42
@MHDuke Try the 3.1 preview

**Comment by Savitri1403** [comment] 2020-02-19 13:18
Hi team, I am trying to use single table and create versions of the api's

public class EntityBase
   {
       public virtual int Id { get; protected set; }
   }

public class PartyV1 : EntityBase
    {
        public string Name { get; private set; }
        public decimal CreditLimit { get; private set; }
    }
public class PartyV2 : EntityBase
    {
        public string Name { get; private set; }
       public string Address { get; private set; }
    }


**and added model binding as below example**

builder.Entity<One.Person>(b =>
        {
            b.HasOne<Two.Person>().WithOne().HasForeignKey<Two.Person>(e => e.Id);
            b.ToTable("People");
            b.Property(e => e.Name).HasColumnName(nameof(One.Person.Name));
        });

        builder.Entity<Two.Person>(b =>
        {
            b.ToTable("People");
            b.Property(e => e.Name).HasColumnName(nameof(Two.Person.Name));
        });

but the entity framework is failing and giving me error as
**"The entity of type 'V2' is sharing the table 'V1' with entities of type 'V1', but there is no entity of this type with the same key value '{Id: -2147482647}' that has been marked as 'Added'."**

can anyone please help me here?

**Comment by AndriySvyryd** [comment] 2020-02-19 17:27
@herme063 If each row contains both `PartyV1` and `PartyV2` entities then when inserting one you need to also insert the other one with the same `Id`. If you have more questions open a new issue with a small runnable project that shows the exception.

**Closed** 2022-10-16 13:28 UTC
Labels: closed-no-further-action, customer-reported

**Comment by alexandis** [comment] 2023-01-26 21:40
Following up, I still can't figure out how to resolve the following issue in the best way and avoid the error related to binding to the same table:

**Shared project**:
```
builder.Entity<CompanyLicence>(b =>
{
    b.ToTable("CT_CA_COMP_LIC");
    ....Simplified binding
}
```

**Consuming project**:
```
builder.Entity<CompanyLicence>(b =>
{
    b.ToTable("CT_CA_COMP_LIC");
    ....Advanced binding
}
```

`CompanyLicence` surely have the same key in both projects.

**Comment by alexandis** [comment] 2023-01-26 23:27
Following up, I still can't figure out how to resolve the following issue in the best way and avoid the error related to binding to the same table:

Shared project:

builder.Entity<CompanyLicence>(b =>
{
    b.ToTable("CT_CA_COMP_LIC");
    ....Simplified binding
}
Consuming project:

builder.Entity<CompanyLicence>(b =>
{
    b.ToTable("CT_CA_COMP_LIC");
    ....Advanced binding
}
CompanyLicence surely has the same PK in both projects - the difference is that shared project has a simplifed version of this entity. Another note: in the consuming project this entity is used for all kinds of CRUD operations, in the shared project it's only reading...

cl.HasOne<ConsumingContext.CompanyLicence>().WithOne().HasForeignKey<SharedContext.CompanyLicence>(cl => cl.Id); did not work out for me, I've got:
**The database operation was expected to affect 1 row(s), but actually affected 0 row(s)** exception while trying to modify the consuming project's entity...

**Comment by roji** [comment] 2023-01-27 10:52
@alexandis can you please open a new issue with a runnable, minimal code sample that shows the error happening?
