### ISSUE TITLE
RemoveConvert does not remove convert 

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#3267] opened 2015-09-29 21:30 UTC
Upgrades to compiler has broken ExpressionExtensions.RemoveConvert CI is failing with this error:

```
System.ArgumentException : The properties expression 'e => Convert(e).Code' is not valid. The expression should represent a property access: 't => t.MyProperty'. When specifying multiple properties use an anonymous type: 't => new { t.MyProperty1, t.MyProperty2 }'.
      Parameter name: propertyAccessExpression
      Stack Trace:
        .\ef\src\EntityFramework.Core\Extensions\Internal\ExpressionExtensions.cs(47,0): at System.Linq.Expressions.ExpressionExtensions.GetPropertyAccessList(LambdaExpression propertyAccessExpression)
```

RemoveConvert does not actually remove the convert expression.

**Comment by natemcmaster** [comment] 2015-09-29 21:32
Possibly related to the latest changes in `Microsoft.CodeAnalysis.CSharp.1.1.0-beta1-20150928-02`

**Comment by natemcmaster** [comment] 2015-09-29 23:12
Fixed with ba69049733d4124dd08ae90dbca52392005b5428

**Comment by TylerWoods** [comment] 2015-10-16 22:03
I have just upgraded to Beta8, and I immediately ran into this.  However, I am working with EF6 instead of EF7.  This leads me to believe that the problem is likely somewhere else, and this fix is just a workaround.

In any case, this seems like the best place to start by reporting it.  If anyone can point me to a better place to report the bug, I will gladly do so.

**Comment by natemcmaster** [comment] 2015-10-16 22:06
@TylerWoods thanks for posting. EF6 development and issues are tracked at https://entityframework.codeplex.com.

**Comment by rowanmiller** [comment] 2015-10-16 22:09
@TylerWoods probably https://github.com/dotnet/roslyn/issues/4471. This was then fixed by https://github.com/VSadov/roslyn/commit/2bd86a00f832be161ec4a3bfab21fbcc9cb2d87e, we are finding out when the fix will make it's way to public bits.

**Comment by cherrydev** [comment] 2015-10-23 00:17
@TylerWoods Have you found a workaround for this yet?

**Comment by TylerWoods** [comment] 2015-10-23 13:53
Unfortunately, no.  I've tried several different casts to try to avoid the Convert, and had no luck at all.  

This is from an adaptation of Identity 3.0 to use EF6.  The linq expression is very simple, so there's very little I'm able to do:
```
protected override void OnModelCreating(DbModelBuilder builder)
{
   base.OnModelCreating(builder);
   builder.Entity<TUser>().HasKey(u => u.Id);
   // more initialization, but this is sufficient to cause the error
}
```

And here's the error:
>Exception thrown: 'System.InvalidOperationException' in EntityFramework.dll
>
>Additional information: The properties expression 'u => Convert(u).Id' is not valid. The expression should represent a property: C#: 't => t.MyProperty'  VB.Net: 'Function(t) t.MyProperty'. When specifying multiple properties use an anonymous type: C#: 't => new { t.MyProperty1, t.MyProperty2 }'  VB.Net: 'Function(t) New With { t.MyProperty1, t.MyProperty2 }'.

Based on @rowanmiller 's comment, our team is sticking with Beta 7 for now, in hopes that the roslyn update will be relatively soon.  

But as you mentioned in the comment on the dotnet/roslyn#4471 thread, we're pretty much stuck until either roslyn or EF6 (unlikely) is fixed.

**Comment by cherrydev** [comment] 2015-10-23 17:15
@TylerWoods Yep, the situation I'm working with right now is exactly the same: Identity Framework 3 with EF6.  Have you attempted to use the daily DNX builds to see if that roslyn change is out there yet?  That's my next step...

**Comment by TylerWoods** [comment] 2015-10-27 15:41
@cherrydev I'm just now getting back to this and see that you've already tried in https://github.com/aspnet/dnx/issues/3082.

**Comment by TylerWoods** [comment] 2015-10-27 16:06
On the outside chance that this could be addressed in EF6, I have created an issue over there as well: https://entityframework.codeplex.com/workitem/2846

**Comment by cherrydev** [comment] 2015-10-27 19:08
Thanks @TylerWoods.  As you can see in dotnet/roslyn#4471 it's possible that this issue will be fixed in the compiler with the next version, but I currently have no way to determine whether or not it is since I can't determine a way to get DNX to use it.

**Comment by divega** [comment] 2015-10-29 22:55
@TylerWoods I just tried a recent build of DNX and it seems that the convert expression isn't included, so I think @vsadov's latest fix for https://github.com/dotnet/roslyn/issues/4471 removed the regression. 

Just to confirm, do you have a pre-release of Visual Studio 2015 Update 1 installed?

**Comment by TylerWoods** [comment] 2015-10-30 13:22
Not yet.  I'll see about getting that today and see if it resolves the issue for me.

**Comment by divega** [comment] 2015-10-30 14:20
@TylerWoods I just asked about Visual Studio 2015 Update 1 because I believe the CTP contains the regression in the compiler. I am not recommending that you try it.

**Comment by TylerWoods** [comment] 2015-10-30 14:25
Ah, I understand.  That's unfortunate.  I'll look into using the daily builds instead.  Thanks for the heads-up!

**Closed** 2022-10-16 09:10 UTC
