### ISSUE TITLE
Missing DeleteBehavior in snapshot for owned type in another table.

### ISSUE THREAD

**Issue by lakeman** [dotnet/efcore#18614] opened 2019-10-28 05:57 UTC
I have an owned type, saved to a different table, both tables with a simple integer key.

```C#
    builder
                .OwnsOne(e => e.Value)
                .ToTable("item_value");
```

 When I generated a migration in ef core 2.2, the snapshot used to specify the delete behavior of this FK explicitly. The snapshot generated from ef core 3 does not. Simplified diff;

```C#
-                            b1.HasOne("Namespace.Item")
-                                .WithOne("ItemValue")
-                                .HasForeignKey("Namespace.Value", "ItemId")
-                                .OnDelete(DeleteBehavior.Cascade);
+                            b1.WithOwner()
+                                .HasForeignKey("ItemId");
```

Loading this snapshot initialises this foreign key with DeleteBehaviour.ClientSetNull. MigrationsModelDiffer treats this as a difference from the current model, so every subsequent migration causes this key to be dropped and recreated unnecessarily;

```C#
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_item_value_item_id",
                table: "item_value");

            migrationBuilder.AddForeignKey(
                name: "FK_item_value_item_id",
                table: "item_value",
                column: "id",
                principalTable: "item",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_item_value_item_id",
                table: "item_value");

            migrationBuilder.AddForeignKey(
                name: "FK_item_value_item_id",
                table: "item_value",
                column: "id",
                principalTable: "item",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }
```

**Comment by ajcvickers** [comment] 2019-10-28 17:16
@AndriySvyryd to find dupe.

**Comment by AndriySvyryd** [comment] 2019-10-28 18:13
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/18045

**Closed** 2022-10-16 14:52 UTC
Labels: customer-reported
