### ISSUE TITLE
Not creating fields in the sequence of the class using the [ Column ( Order = ..) ]

### ISSUE THREAD

**Issue by ralmsdeveloper** [dotnet/efcore#6081] opened 2016-07-14 19:48 UTC
**I have a class and as the EF Core creates the table does not meet the class order.**

```
[Table("clientes")]
    public class Clientes
    {
        [Key]
        [Display(Name = "Código")]
        [Column(Order = 1)]
        public int clienteid { get; set; }

        [Display(Name = "Tipo Contribuinte")]
        [Column(Order = 2)]
        public int tipocontribuinte { get; set; }

        [Display(Name = "CNPJ/CPF")]
        [StringLength(14)]
        [Column(TypeName = "varchar(18)", Order = 3)]
        [Required] 
        public string cnpj { get; set; }

        [Display(Name = "I.E/RG")]
        [StringLength(16)]
        [Column(TypeName = "varchar(16)", Order = 4)]
        public string inscest { get; set; }


        [Display(Name = "Razão Social")]
        [StringLength(50)]
        [Column(TypeName = "varchar(50)", Order = 5)]
        [Required(AllowEmptyStrings =false)]
        public string razsocial { get; set; }

        [Display(Name = "Fantasia")]
        [StringLength(50)]
        [Column(TypeName = "varchar(50)", Order = 6)]
        [Required]
        public string fantasia { get; set; }


        [Display(Name = "Estado")]
        [StringLength(2)]
        [Column(TypeName = "varchar(2)", Order = 7)]
        public string estado { get; set; }
} 
```

**I'm using [ Column ( Order = ..) ]**

EF Core version: 1.0 RTM
Operating system:  Windows 10 x64 
Visual Studio version: 2015 Update 3

**Comment by ajcvickers** [comment] 2016-07-14 19:50
Duplicate of #2272

**Comment by ralmsdeveloper** [comment] 2016-07-14 19:54
So there is no definitive position on the matter ? or when it will be resolved ?

**Closed** 2022-10-16 09:51 UTC
Labels: closed-duplicate
