### ISSUE TITLE
ToJson should be configurable to not emit default values/allow missing properties when (De)serializing the column

### ISSUE THREAD

**Issue by Skintkingle** [dotnet/efcore#34376] opened 2024-08-07 09:20 UTC
We have gone through a process of improving and changing the object that is related to the Json column. As such new properties were added. This left missing data in existing rows. For example:

`public record JsonData(int AValue);`
gets changed to
`public record JsonData(int AValue, bool IsAGoodValue);`

Now all existing rows basically have the column related to this data as:
`{ "AValue": 4}`
When loading that column, it fails as it doesn't have a value for IsAGoodValue.

It would be nice to be able to specify to set default values for missing properties, just like System.Text.Json (and other libraries) do when properties are missing in the json.

This would also be helpful to keep column sizes down if we can avoid emiting default values as well (which is a logical extension to this). Especially if the object has many properties that are mostly the default for their type.

**Comment by maumar** [comment] 2024-08-08 02:40
related to https://github.com/dotnet/efcore/issues/32301

**Comment by roji** [comment] 2024-08-08 13:08
Yeah, we should probably close this as a duplicate of #32301, unless we maybe want to track separately for relational/Cosmos/etc.

@ajcvickers thoughts?

**Comment by Skintkingle** [comment] 2024-08-08 14:34
Ah sorry, I didn't see that, I searched for "ToJson" to look for existing issues. #32301 looks very the same. Happy to close this unless it serves as some kind of distinction for you.

**Closed** 2024-08-12 10:38 UTC
Labels: customer-reported
