### ISSUE TITLE
AddDbContextPool  Many to Many Related Entities Insert Fails 

### ISSUE THREAD

**Issue by suryawomshi** [dotnet/efcore#20515] opened 2020-04-03 16:17 UTC
Unable to save entity with many to many relationship

Inject services with DbContextPool<MyDbContext>  (works fine with DBContext<MyDbContext>) 
entity has 4 Many to Many Relation of which 1 Has 2 many to many relation

Account --> AccountAddresses -> Address
                  AccountEmails -> Emails
                  AccountPhones -> Phones
                 AccountPerson --------------------->PersonEmails--->Phones
                                                                           PersonPhones---->Emails

Call           await  _dbContext.AddAsync(entity);
                await _dbContext.SaveChangesAsync();

            
```

Got Exceptions? Include both the message and the stack trace

Microsoft.EntityFrameworkCore.ChangeTracking: Debug: 'BSSCRMContext' generated temporary value '-2147482647' for the 'Id' property of new 'Account' entity.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'BSSCRMContext' started tracking 'Account' entity with key '{Id: -2147482647}'.

Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'BSSCRMContext' started tracking 'AccountAddress' entity with key '{AccountId: -2147482647, AddressId: -2147482647}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: 'BSSCRMContext' generated temporary value '-2147482646' for the 'AddressId' property of new 'Address' entity.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Foreign key property 'AccountAddress.AddressId' detected as changed from '-2147482647' to '-2147482646' for entity with key '{AccountId: -2147482647, AddressId: -2147482646}'.

Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'BSSCRMContext' started tracking 'Address' entity with key '{AddressId: -2147482646}'.


Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'BSSCRMContext' started tracking 'AccountEmail' entity with key '{AccountId: -2147482647, EmailId: -2147482647}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: 'BSSCRMContext' generated temporary value '-2147482646' for the 'EmailId' property of new 'Email' entity.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Foreign key property 'AccountEmail.EmailId' detected as changed from '-2147482647' to '-2147482646' for entity with key '{AccountId: -2147482647, EmailId: -2147482646}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'BSSCRMContext' started tracking 'Email' entity with key '{EmailId: -2147482646}'.


Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'BSSCRMContext' started tracking 'AccountPerson' entity with key '{AccountId: -2147482647, PersonId: -2147482647}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: 'BSSCRMContext' generated temporary value '-2147482646' for the 'Id' property of new 'Person' entity.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Foreign key property 'AccountPerson.PersonId' detected as changed from '-2147482647' to '-2147482646' for entity with key '{AccountId: -2147482647, PersonId: -2147482646}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'BSSCRMContext' started tracking 'Person' entity with key '{Id: -2147482646}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'BSSCRMContext' started tracking 'PersonEmail' entity with key '{PersonId: -2147482646, EmailId: -2147482645}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: 'BSSCRMContext' generated temporary value '-2147482644' for the 'EmailId' property of new 'Email' entity.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Foreign key property 'PersonEmail.EmailId' detected as changed from '-2147482645' to '-2147482644' for entity with key '{PersonId: -2147482646, EmailId: -2147482644}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'BSSCRMContext' started tracking 'Email' entity with key '{EmailId: -2147482644}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'BSSCRMContext' started tracking 'PersonPhone' entity with key '{PersonId: -2147482646, PhoneId: -2147482647}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: 'BSSCRMContext' generated temporary value '-2147482646' for the 'PhoneId' property of new 'Phone' entity.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Foreign key property 'PersonPhone.PhoneId' detected as changed from '-2147482647' to '-2147482646' for entity with key '{PersonId: -2147482646, PhoneId: -2147482646}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'BSSCRMContext' started tracking 'Phone' entity with key '{PhoneId: -2147482646}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'BSSCRMContext' started tracking 'AccountPhone' entity with key '{AccountId: -2147482647, PhoneId: -2147482645}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: 'BSSCRMContext' generated temporary value '-2147482644' for the 'PhoneId' property of new 'Phone' entity.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Foreign key property 'AccountPhone.PhoneId' detected as changed from '-2147482645' to '-2147482644' for entity with key '{AccountId: -2147482647, PhoneId: -2147482644}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'BSSCRMContext' started tracking 'Phone' entity with key '{PhoneId: -2147482644}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: DetectChanges starting for 'BSSCRMContext'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: DetectChanges completed for 'BSSCRMContext'.
Microsoft.EntityFrameworkCore.Database.Transaction: Debug: Beginning transaction with isolation level 'Unspecified'.
Microsoft.EntityFrameworkCore.Database.Transaction: Debug: Began transaction with isolation level 'ReadCommitted'.
Microsoft.EntityFrameworkCore.Database.Command: Debug: Creating DbCommand for 'ExecuteReader'.
Microsoft.EntityFrameworkCore.Database.Command: Debug: Created DbCommand for 'ExecuteReader' (1ms).
Microsoft.EntityFrameworkCore.Database.Command: Debug: Executing DbCommand [Parameters=[@p0=NULL (Size = 25), @p1='Chandrashekar K' (Nullable = false) (Size = 200), @p2=NULL (Size = 4000), @p3=NULL (Size = 20), @p4=NULL, @p5=NULL (Size = 100), @p6=NULL (Size = 100), @p7=NULL (Size = 100), @p8='2', @p9=NULL (Size = 100), @p10=NULL (Size = 100), @p11=NULL (Size = 20), @p12='Unit-1' (Nullable = false) (Size = 100), @p13=NULL (Size = 10), @p14=NULL (Size = 100), @p15='info@uniquepunch.in' (Nullable = false) (Size = 100), @p16='info@uniquepunch.in' (Nullable = false) (Size = 100), @p17='False', @p18='Chandrashekar' (Nullable = false) (Size = 50), @p19='K' (Size = 4000), @p20=NULL (Size = 4000), @p21='0', @p22='+918028363797' (Nullable = false) (Size = 15), @p23='+918028363797' (Nullable = false) (Size = 15)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Accounts] ([CIN], [Name], [Notes], [PAN])
VALUES (@p0, @p1, @p2, @p3);
SELECT [Id]
FROM [Accounts]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

INSERT INTO [Address] ([Active], [Address1], [Address2], [Address3], [AddressType], [City], [Country], [GSTIN], [Name], [PostalCode], [State])
VALUES (@p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14);
SELECT [AddressId]
FROM [Address]
WHERE @@ROWCOUNT = 1 AND [AddressId] = scope_identity();

DECLARE @inserted2 TABLE ([EmailId] int, [_Position] [int]);
MERGE [Email] USING (
VALUES (@p15, 0),
(@p16, 1)) AS i ([EmailAddress], _Position) ON 1=0
WHEN NOT MATCHED THEN
INSERT ([EmailAddress])
VALUES (i.[EmailAddress])
OUTPUT INSERTED.[EmailId], i._Position
INTO @inserted2;

SELECT [t].[EmailId] FROM [Email] t
INNER JOIN @inserted2 i ON ([t].[EmailId] = [i].[EmailId])
ORDER BY [i].[_Position];

INSERT INTO [Persons] ([Active], [FirstName], [LastName], [Notes], [Title])
VALUES (@p17, @p18, @p19, @p20, @p21);
SELECT [Id]
FROM [Persons]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

DECLARE @inserted5 TABLE ([PhoneId] int, [_Position] [int]);
MERGE [Phone] USING (
VALUES (@p22, 0),
(@p23, 1)) AS i ([PhoneNumber], _Position) ON 1=0
WHEN NOT MATCHED THEN
INSERT ([PhoneNumber])
VALUES (i.[PhoneNumber])
OUTPUT INSERTED.[PhoneId], i._Position
INTO @inserted5;

SELECT [t].[PhoneId] FROM [Phone] t
INNER JOIN @inserted5 i ON ([t].[PhoneId] = [i].[PhoneId])
ORDER BY [i].[_Position];
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Foreign key property 'Account.Id' detected as changed from '-2147482647' to '2' for entity with key '{Id: 2}'.
Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer: Error: Connection ID "17798225733273780235", Request ID "8000000c-0001-f700-b63f-84710c7967bb": An unhandled exception was thrown by the application.

System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
   at Microsoft.Data.SqlClient.SqlInternalTransaction.Rollback()
   at Microsoft.Data.SqlClient.SqlInternalTransaction.Dispose(Boolean disposing)
   at Microsoft.Data.SqlClient.SqlInternalTransaction.Dispose()
   at Microsoft.Data.SqlClient.SqlTransaction.Dispose(Boolean disposing)
   at System.Data.Common.DbTransaction.Dispose()
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Dispose()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Dispose()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Microsoft.EntityFrameworkCore.Infrastructure.IResettableService.ResetState()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IResettableService.ResetState()
   at Microsoft.EntityFrameworkCore.Internal.DbContextPool`1.Return(TContext context)
   at Microsoft.EntityFrameworkCore.Internal.DbContextPool`1.Lease.System.IAsyncDisposable.DisposeAsync()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.<>c__DisplayClass15_0.<<DisposeAsync>g__Await|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Http.Features.RequestServicesFeature.<DisposeAsync>g__Awaited|9_0(RequestServicesFeature servicesFeature, ValueTask vt)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.FireOnCompleted()
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Foreign key property 'Address.AddressId' detected as changed from '-2147482646' to '2' for entity with key '{AddressId: 2}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Foreign key property 'Email.EmailId' detected as changed from '-2147482646' to '3' for entity with key '{EmailId: 3}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Foreign key property 'Email.EmailId' detected as changed from '-2147482644' to '4' for entity with key '{EmailId: 4}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Foreign key property 'Person.Id' detected as changed from '-2147482646' to '2' for entity with key '{Id: 2}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Foreign key property 'Phone.PhoneId' detected as changed from '-2147482646' to '3' for entity with key '{PhoneId: 3}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Foreign key property 'Phone.PhoneId' detected as changed from '-2147482644' to '4' for entity with key '{PhoneId: 4}'.
Microsoft.EntityFrameworkCore.Database.Command: Debug: A data reader was disposed.
Microsoft.EntityFrameworkCore.Database.Command: Debug: Creating DbCommand for 'ExecuteReader'.
Microsoft.EntityFrameworkCore.Database.Command: Debug: Created DbCommand for 'ExecuteReader' (2ms).
Microsoft.EntityFrameworkCore.Database.Command: Debug: Executing DbCommand [Parameters=[@p24='-2147482647', @p25='-2147482646', @p26='-2147482647', @p27='-2147482646', @p28='-2147482647', @p29='-2147482646', @p30='-2147482647', @p31='-2147482644', @p32='-2147482646', @p33='-2147482644', @p34='-2147482646', @p35='-2147482646'], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [AccountAddresses] ([AccountId], [AddressId])
VALUES (@p24, @p25);
INSERT INTO [AccountEmails] ([AccountId], [EmailId])
VALUES (@p26, @p27);
INSERT INTO [AccountPersons] ([AccountId], [PersonId])
VALUES (@p28, @p29);
INSERT INTO [AccountPhones] ([AccountId], [PhoneId])
VALUES (@p30, @p31);
INSERT INTO [PersonEmails] ([PersonId], [EmailId])
VALUES (@p32, @p33);
INSERT INTO [PersonPhones] ([PersonId], [PhoneId])
VALUES (@p34, @p35);
Exception thrown: 'Microsoft.EntityFrameworkCore.DbUpdateException' in System.Private.CoreLib.dll

For `dotnet ef` and PMC, share the --verbose output
-->
Entity Framework Core .NET Command-line Tools 3.1.3



### Further technical details

EF Core version: "3.1.3"
Database provider: "Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.3"
Target framework: netcoreapp3.1
Operating system: Win 10 Professional for Workstation 64bit
IDE: Visual Studio 2019 16.5.2

**Comment by ajcvickers** [comment] 2020-04-03 16:54
@suryawomshi From the exception, it looks like the same context instance or the same DbConnection may be being used concurrently by multiple threads. However, that's just a guess. 
So we can investigate more, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

**Comment by suryawomshi** [comment] 2020-04-04 03:34
@ajcvickers I am using the architecture specified in 
https://github.com/dotnet-architecture/eShopOnWeb

If you still need a project i will create small sample project and upload it some time

**Comment by ajcvickers** [comment] 2020-04-06 16:29
@suryawomshi Thanks for the additional information.

Note for team: I suspect something is going on with D.I. here. The DbContext is being resolved by a scoped open generic, which I think should work, but looks like is not working here.

**Comment by ajcvickers** [comment] 2020-06-16 21:55
@suryawomshi I am not able to reproduce this using the project you posted. Can you also post the steps needed to see the exception?

**Comment by ajcvickers** [comment] 2020-07-06 15:23
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:19 UTC
Labels: closed-could-not-reproduce, customer-reported
