### ISSUE TITLE
OrderBy on Navigation Property Fails

### ISSUE THREAD

**Issue by maganuk** [dotnet/efcore#13081] opened 2018-08-22 18:45 UTC
The following query fails. Apologies if this is duplicate, but I couldn't find the relevant thread.

```
Exception message: NullReferenceException: Object reference not set to an instance of an object.
```

### Steps to reproduce
```c#
    class Program
    {
        static void Main(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<TestContext>();
            optionsBuilder.UseSqlServer("Server=(LocalDb)\\MSSQLLocalDB;Database=TestingCore;Trusted_Connection=true;MultipleActiveResultSets=true");
            var dbContext = new TestContext(optionsBuilder.Options);
            dbContext.Database.EnsureDeleted();
            dbContext.Database.EnsureCreated();

            var Car1 = new Vehicle()
            {
                Title = "Car1",
                Type = new VehicleType
                {
                    Title = "Saloon"
                }
            };
            var Car2 = new Vehicle()
            {
                Title = "Car2"
            };
            dbContext.Vehicles.Add(Car1);
            dbContext.Vehicles.Add(Car2);
            dbContext.SaveChanges();
            var vehicles = dbContext.Vehicles
                .Select(x => new
                {
                    x.Title,
                    Type = x.Type == null ? null : new
                    {
                        x.Type.ID,
                        x.Type.Title
                    }
                })
                .OrderBy(x => x.Type.Title)
                .ToList();
        }
    }

    public class TestContext : DbContext
    {
        public TestContext(DbContextOptions<TestContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }

        public DbSet<Vehicle> Vehicles { get; set; }
        public DbSet<VehicleType> VehicleTypes { get; set; }
    }

    public class Vehicle
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public VehicleType Type { get; set; }
    }

    public class VehicleType
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public ICollection<Vehicle> Vehicles { get; set; }
    }
```

### Further technical details
EF Core version: 2.1 and 2.2-Preview1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8

**Comment by maganuk** [comment] 2018-08-22 18:51
Also, doing `.Where(x => x.Type.Title.Contains("Car"))` instead of the ordeby the query still fails

**Comment by smitpatel** [comment] 2018-08-23 19:35
If `x.Type` is null then aren't you dereferencing a null pointer?

**Comment by maganuk** [comment] 2018-08-23 20:11
Yup. But shouldn't that check be done the translator? Works with EF6.

**Comment by ajcvickers** [comment] 2018-08-28 19:42
@smitpatel Can you find the issue about general null compensation in query?

**Comment by smitpatel** [comment] 2018-08-28 20:35
Duplicate of #12294

**Comment by smitpatel** [comment] 2018-08-28 20:35
Looks like we don't have general issue tracking it.

**Comment by ajcvickers** [comment] 2018-08-29 18:16
@divega to create an issue for general null compensation.

**Comment by divega** [comment] 2018-08-30 00:13
@ajcvickers yup, at least the title was written to cover the whole set of cases.

**Closed** 2022-10-16 13:26 UTC
Labels: closed-duplicate, customer-reported
