### ISSUE TITLE
FilePath generated by Update-Database command is incorrect

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#23625] opened 2020-12-08 19:13 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/FilePath-generated-by-Update-Database-co/1272665)._

---
[severity:I'm unable to use this version]
I have created a Blazor Server application, with Individual Account Authentication
I shorted the default database name in appsettings.json.

"DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=TemplateAuthDB; Trusted_Connection=True; MultipleActiveResultSets=true"

I opened Package Manager Console and executed:

PM> UPDATE-DATABASE

I get this error:

CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\superTemplateAuthDB.mdf'.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.

NOTE: that a slash is missing after the default user folder, which is: C:\Users\super.  This is causing a problem of course because it can't create a database in the C:\Users folder (nor should it).

How do I resolve this?  

TIA,

Miles

---
#### Feedback Bot on 11/30/2020, 06:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2020-12-08 19:15
Duplicate of #18632

**Closed** 2022-10-16 19:14 UTC
Labels: closed-external, customer-reported
