### ISSUE TITLE
in the Startup(IHostingEnvironment env), env.WebRootPath is null when using migration commands

### ISSUE THREAD

**Issue by sharabiania** [dotnet/efcore#4529] opened 2016-02-10 17:47 UTC
When I try to add a new migration (e.g. `dnx ef migrations add MyMigration`), I get compilation errors in the _Package Manager Console_ due to `env.WebRootPath` being `null` in the `Startup` constructor.

This property is not null when building and running the project.

**Comment by bricelam** [comment] 2016-02-10 18:01
Dupe of #4494

**Closed** 2022-10-16 09:28 UTC
