### ISSUE TITLE
ExecuteUpdate returns error when updating entity contains owned type 

### ISSUE THREAD

**Issue by VardanKosakyan** [dotnet/efcore#30696] opened 2023-04-14 17:22 UTC
ExecuteUpdate returns the following error when updating entity contains owned type.

could not be translated. Additional information: The following lambda argument to 'SetProperty' does not represent a valid property to be set: 'p => p.StorageTemperature'

     //Query
       Products
	.Where( p => p.Name.StartsWith("c"))	
	.ExecuteUpdate(e => e.SetProperty( p => p.StorageTemperature, p => p.StorageTemperature + 1));

    //entity
    public class Product
    {
        public int Id { get; set; }
        public String Name { get; set; }
        public int CategoryId { get; set; }
        public Category Category  { get; set;}      
        private Price _price;      
        public Decimal StorageTemperature { get; set; }
        
        public Price Price
        {
            get => _price;
            set
            {
                _price = value;              
            }
        }        
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }

    }

 //configuration

    modelBuilder.Entity<Product>()
          .OwnsOne(p => p.Price,
              bld =>
              {
                  bld.ToTable("Products");
                  bld.UsePropertyAccessMode(PropertyAccessMode.Field);
              })
          .OwnsMany( p => p.PriceHistory, bld =>
              {
                  bld.ToJson();
                  bld.OwnsOne(o => o.Price);
              });

**Comment by roji** [comment] 2023-04-14 19:29
Duplicate of #30528

**Closed** 2023-04-17 12:13 UTC
Labels: customer-reported
