### ISSUE TITLE
Materializing IQueryable with ToListAsync throws a NullReferenceException

### ISSUE THREAD

**Issue by juliopk** [dotnet/efcore#10126] opened 2017-10-20 12:26 UTC
I'm trying to query data with navigation properties, but when a 1-1 relationship is null and nested relationships are queried the the materialization fails with a NullReferenceException.

Previously with EF Core 1.1 it worked properly.
```
Exception message: Object reference not set to an instance of an object.
Stack trace:    at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.<_IncludeAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.<_ExecuteAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext()
```

### Steps to reproduce
```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;

namespace ConsoleApp4
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new FooContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
                context.Add(new Foo() { });
                context.SaveChanges();
            }

            using (var context = new FooContext())
            {
                var results = context.Set<Foo>().AsNoTracking().Include("Bar.Items");
                var itemsOK = results.ToList(); //this works
                var itemsFail = results.ToListAsync().Result; // this fails

            }

            Console.WriteLine("Hello World!");
        }
    }
    public class Foo
    {
        public int Id { get; set; }
        public Bar Bar { get; set; }
    }
    public class Bar
    {
        public int Id { get; set; }
        public int FooId { get; set; }
        public ICollection<Baz> Items { get; set; } = new ObservableCollection<Baz>();
    }
    public class Baz
    {
        public int Id { get; set; }
    }
    public class FooContext : DbContext
    {
        public DbSet<Foo> Foos { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=foo_database;Trusted_Connection=True;");
        }
    }
}
```

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10
IDE: Visual Studio 2017

**Comment by smitpatel** [comment] 2017-10-20 19:39
Duplicate of #9038

**Closed** 2022-10-16 11:55 UTC
