### ISSUE TITLE
EF.Functions.FreeText to support multiple columns

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#22418] opened 2020-09-05 17:03 UTC
When I use full-text search, often I will index more than one column. For example, an article table would have the main text. But I'd also want to search the description and keywords columns as well.

I see `EF.Functions.FreeText` has been added to simplify using full-text search with Entity Framework. However, this method only appears to support a single column.

Could it be enhanced to support more than one column?

**Comment by bricelam** [comment] 2020-09-08 17:22
Duplicate of https://github.com/dotnet/efcore/issues/10462

**Comment by bricelam** [comment] 2020-09-08 17:23
...which itself may be part of https://github.com/dotnet/efcore/issues/13495

**Closed** 2022-10-16 18:39 UTC
Labels: closed-duplicate, customer-reported
