### ISSUE TITLE
Add-Migration InitialCreate

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#31008] opened 2023-05-31 10:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-Migration-InitialCreate/10372206)._

---
When I run the Add-Migration InitialCreate command, visual studio 2022 gets stuck without doing anything and I can't stop, pause or go to another option, the application gets stuck.
It should create a Migrations folder and it doesn't do anything and it doesn't give any errors either.
Attached capture of how it stays.

---
#### Feedback Bot on 5/24/2023, 01:38 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2023-05-31 10:47
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-06-14 19:13
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-06-14 19:13 UTC
Labels: customer-reported
