### ISSUE TITLE
Group join is not working in EF core

### ISSUE THREAD

**Issue by ChristalVins** [dotnet/efcore#18905] opened 2019-11-14 16:16 UTC
public class NewsPost
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PostId { get; set; }
        [Required]
        [MaxLength(30)]
        public string PostName { get; set; }
        [Required]
        public string PostContent { get; set; }
        public string PostImageUrl { get; set; }
        [MaxLength(150)]
        public string PostDate { get; set; }

        public virtual ICollection<Like> Likes { get; } = new List<Like>();
        public virtual ICollection<Comment> Comment { get; set; }
    }
public class Like
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int LikeId { get; set; }
        [Required]
        [MaxLength(30)]
        public string LikeName { get; set; }
        public string LikeDate { get; set; }

        // Foreign key
        [Display(Name = "NewsPost")]
        public int PostId { get; set; }
        [ForeignKey("PostId")]
        public virtual NewsPost NewsPost { get; set; }
    }

var groupJoin = _context.NewsPosts.GroupJoin(_context.Likes,  //inner sequence
                                std => std.PostId, //outerKeySelector 
                                s => s.PostId,     //innerKeySelector
                                (std, studentsGroup) => new // resultSelector 
                                {
                                    NewsPost = std,
                                    like = studentsGroup
                                    
                                });

### Steps to reproduce
![image](https://user-images.githubusercontent.com/14306827/68874962-0f008500-0728-11ea-81ca-b5477288638d.png)

![image](https://user-images.githubusercontent.com/14306827/68874850-e2e50400-0727-11ea-876d-e15169fd4be7.png)

Please solve the issues and give me your inputs

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment] 2019-11-14 18:21
Duplicate of #17068

**Closed** 2022-10-16 14:56 UTC
Labels: closed-duplicate, customer-reported
