### ISSUE TITLE
Complex property causes "The multi-part identifier "xxx" could not be bound" after GroupBy + Select(x => x.First())

### ISSUE THREAD

**Issue by GeorgeKarlinzer** [dotnet/efcore#33183] opened 2024-02-28 04:14 UTC
### Description
When I try to get distinct records by property with complex property I get an "The multi-part identifier "xxx" could not be bound" error.

#### Models
```c#
internal class Supplier
{
    public Guid Id { get; set; }
    public Size Size { get; set; }
}
internal class Size
{
    public int Height { get; set; }
}
```
#### Configuration
```cs
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Supplier>()
            .ComplexProperty(x => x.Size);

    base.OnModelCreating(modelBuilder);
}
```
#### Query
```c#
var data = dbContext
    .Set<Supplier>()
    .GroupBy(x => x.Id)
    .Select(y => y.First())
    .ToList();
```

### Error
`Microsoft.Data.SqlClient.SqlException: 'The multi-part identifier "s.Size_Height" could not be bound.'`

### Generated SQL
```sql
SELECT [t0].[Id], [t0].[Name], [t0].[Size_Height]
      FROM (
          SELECT [s].[Id]
          FROM [Supplier] AS [s]
          GROUP BY [s].[Id]
      ) AS [t]
      LEFT JOIN (
          SELECT [t1].[Id], [t1].[Name], [t1].[Size_Height]
          FROM (
              SELECT [s0].[Id], [s0].[Name], [s].[Size_Height], ROW_NUMBER() OVER(PARTITION BY [s0].[Id] ORDER BY [s0].[Id]) AS [row]
              FROM [Supplier] AS [s0]
          ) AS [t1]
          WHERE [t1].[row] <= 1
      ) AS [t0] ON [t].[Id] = [t0].[Id]
```

As I understand instead of `[s].[Size_Height]` should be `[s0].[Size_Height]`, but for some reason ef core breaks on the complex property and uses wrong alias.

.Net version: 8
Ef Core version: 8.0.0

**Comment by maumar** [comment] 2024-02-28 05:12
dupe of https://github.com/dotnet/efcore/issues/32911

**Comment by maumar** [comment] 2024-02-28 05:12
another one @roji

**Comment by roji** [comment] 2024-02-28 11:11
Yeah, let's bring up patching in today's triage meeting.

**Comment by maumar** [comment] 2024-02-29 02:45
this one still repros on main. Will investigate for the fix

**Comment by maumar** [comment] 2024-02-29 08:58
problem here is that in groupby scenarios, we clone the subquery and assign new alias to it. However TableMap is stored in form of Dictionary<ITableBase, string>, so the (cloning) visitor doesn't go through it and doesn't update table to the new alias. Later when we try to produce complex type columns (in the GenerateComplexPropertyShaperExpression) we use the old alias, and that results in bad sql. @roji

**Closed** 2024-05-04 18:11 UTC
Labels: type-bug, closed-fixed, customer-reported, area-groupby

**Comment by adamzest** [comment] 2024-05-30 10:43
> opening for possible patch

Hi. Will this patch be for 8.x please? I'm experiencing this exact issue having just upgraded from EF core 6 to 8 and switched to use complex types instead of OwnsOne but groupbys fail exactly as described by the OP.

Thanks

**Comment by adamzest** [comment] 2024-06-10 09:41
> Thanks for the investigation @maumar, another bug of mine... :(
> 
> It should be pretty straightforward to have the cloning visitor update the table map - if memory serves, in the 8.0 codebase it already manipulates non-expressresions on EntityTypeProjectionBindingExpression. However, this is an area of the code that changed quite a lot in main, so backporting may not be as straightforward.
> 
> I'd suggest fixing in main for now and waiting to see how many people run into this before backporting...

@roji  @ajcvickers 

It would be great to get this fixed in v8 given v9 is a few months away if at all possible please. This is blocking our migration from a mix of EF6/EFCore 6 to EFCore 8 as complex types just dont work for us without this fix.

Many thanks

**Comment by roji** [comment] 2024-06-10 10:15
@adamzest the fix for this big is non-trivial, and it could be risky to backport it to 8.0, as it may end up breaking other scenarios and destabilizing things. We haven't seen many users running into this yet, we could definitely reconsider if more users report being blocked by it.
