### ISSUE TITLE
Generating code from an existing database "AggregateException"

### ISSUE THREAD

**Issue by AmineKhi** [dotnet/efcore#3201] opened 2015-09-23 14:09 UTC
I'm trying to generate code from my database but i get errors : System.AggregateException: One or more errors occurred. ---> Method not found

this is my project.json:
//////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\
{
"webroot": "wwwroot",
"version": "1.0.0-*",

"dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-beta5",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta7",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta5",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta5",
    "EntityFramework.SqlServer": "7.0.0-beta8-15797",
    "EntityFramework.Commands": "7.0.0-beta8-15797",
    "EntityFramework.SqlServer.Design": "7.0.0-beta8-15797",
    "Remotion.Linq": "2.0.0-rc-001"
},

"commands": {
  "web": "Microsoft.AspNet.Hosting --config hosting.ini",
  "ef": "EntityFramework.Commands"
},

"frameworks": {
    "dnx451": { },
    "dnxcore50": { }
},

"exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
],
"publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
]
}
//////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\

And I'm using this command :
dnx ef dbcontext scaffold "ConnectionString" EntityFramework.SqlServer

Thank you.

**Comment by lajones** [comment] 2015-09-23 17:32
Closing as a dupe of #3135.

**Closed** 2022-10-16 09:09 UTC
