### ISSUE TITLE
Is it possible in the scaffold command to implement INotifyPropertyChanged interface?

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#15516] opened 2019-04-28 09:14 UTC
I would like to work with entities that notify the changes of the properties, so I would like to implement the INotifyPropertyChanged interface in each entity.

However, I don't see the way to tell to the scaffold command that I would like it implments this interface in each entity. Is it possible or I have to implement by myself the interface in each entitiy and property?

If it is not possible, could it be possible in the future, as a new feature of the scaffold command?

Thanks.

**Comment by ErikEJ** [comment] 2019-04-28 13:44
I think EF Core Power Tools with Handlebars templates would enable that scenario.

**Comment by ajcvickers** [comment] 2019-05-03 21:16
Closing as duplicate of #4038 and #15516

**Closed** 2022-10-16 14:19 UTC
Labels: customer-reported
