### ISSUE TITLE
How to get the mapping only, without also having to create the table?

### ISSUE THREAD

**Issue by rhires** [dotnet/efcore#8819] opened 2017-06-12 01:41 UTC
The usual process for running migrations from the command line is initiated by something like this: `dotnet ef migrations add MyMigration` 
 
This process creates two files in my Migrations folder. One is `*MyMigration.designer.cs` and the other is `*MyMigrationmigration.cs`. 

The second step - `dotnet ef database update` is where I start to have issues - if I already have a table that I've created in SQL, the "CREATE TABLE" command is redundant, and the 2nd step will fail. So I have to manually comment out that part in order for the migration to succeed. 

Is there a way to avoid having to manually edit the migration file and just have EF Core do the mapping for me? This is somewhere between database first and model first. So really, I want a "sync first" kind of migration - make sure that my models match the database tables, and that my database tables match my models. 

Or maybe a new command, like `dotnet ef sync`, which would do that. It would create the *designer.cs file without also creating the migration file, unless the migration file was needed because a model was different from a table. But in other cases, it would see that I have a table called "Redundencies" and a model called "Redundencies" but that only the mapping was missing, so it would just do that part. 

Is there anything like that now, and I just missed it in the docs?

**Comment by ajcvickers** [comment] 2017-06-12 19:25
It looks like the general idea here is covered by #2167. That is, you have some existing database elements, and then you want to start doing Migrations. Closing as a duplicate of that issue.

**Closed** 2022-10-16 11:08 UTC
