### ISSUE TITLE
EF core throws exception while using HasValue with nullable int 

### ISSUE THREAD

**Issue by KesavanRadhakrishnan** [dotnet/efcore#19852] opened 2020-02-10 13:02 UTC
EF Core: HasValue throws Exception while it's using with nullable int on Linq.

### Steps to reproduce
![image](https://user-images.githubusercontent.com/60881833/74151745-da22a200-4c32-11ea-9370-a2023d74d152.png)

<!--
What steps can we follow to reproduce the issue?

We ❤ code! Include a complete code listing or attach a simplified project

``` C#
```csharp
`
```
```

Got Exceptions? Include both the message and the stack trace

For `dotnet ef` and PMC, share the --verbose output
-->



### Further technical details

EF Core version: 3.1.1
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: NET Core 3.1.1
Operating system: Windows
IDE: Visual Studio 2019 16.3

**Comment by ajcvickers** [comment] 2020-02-10 18:27
@maumar to take a look and request repro if needed.

**Comment by maumar** [comment] 2020-02-10 23:16
@KesavanRadhakrishnan I am unable to reproduce this locally. I tried to reverse engineer the scenario based on the information you provided. Ended up with the following code:

```cs
    class Program
    {
        static async Task Main(string[] args)
        {
            using var ctx = new MyContext();
            await ctx.Database.EnsureDeletedAsync();
            await ctx.Database.EnsureCreatedAsync();

            var user1 = new User { IsActive = true, UserName = "name1", UserEmailId = "email1" };
            ctx.Users.Add(user1);

            var question1 = new Question { IsActive = true };
            await ctx.Questions.AddAsync(question1);
            await ctx.SaveChangesAsync();

            var qc1 = new QuestionCustomer { IsActive = true, Question = question1, User = user1 };
            await ctx.QuestionCustomerMapper.AddAsync(qc1);
            await ctx.SaveChangesAsync();

             var questionId = 1;

            var query = from question in ctx.Questions.Where(i => i.IsActive && i.QuestionId == questionId)
                        from questionMapper in ctx.QuestionCustomerMapper.Where(i => i.IsActive && i.QuestionId == question.QuestionId)
                        from user in ctx.Users.Where(i => i.IsActive && questionMapper.UserId.HasValue && i.UserId == questionMapper.UserId.Value)
                        select new CustomerUserDetails
                        {
                            CustomerId = user.UserId,
                            CustomerName = user.UserName,
                            CustomerEmail = user.UserEmailId,
                            IsOwner = true,
                        };

            var result = await query.ToListAsync();
        }
    }

    public class MyContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=Repro19852;Trusted_Connection=True;MultipleActiveResultSets=True");
        }

        public DbSet<Question> Questions { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<QuestionCustomer> QuestionCustomerMapper { get; set; }

        protected override void OnModelCreating(ModelBuilder mb)
        {
            mb.Entity<QuestionCustomer>().HasKey(x => new { x.QuestionId, x.UserId });
            mb.Entity<QuestionCustomer>().HasOne(x => x.User).WithMany(x => x.QuestionCustomers).HasForeignKey(x => x.UserId);
            mb.Entity<QuestionCustomer>().HasOne(x => x.Question).WithMany(x => x.QuestionCustomers).HasForeignKey(x => x.QuestionId);
        }
    }

    public class Question
    {
        public int QuestionId { get; set; }
        public bool IsActive { get; set; }
        public List<QuestionCustomer> QuestionCustomers { get; set; }
    }

    public class User
    {
        public int UserId { get; set; }
        public bool IsActive { get; set; }
        public string UserName { get; set; }
        public string UserEmailId { get; set; }
        public List<QuestionCustomer> QuestionCustomers { get; set; }
    }

    public class QuestionCustomer
    {
        public int QuestionId { get; set; }
        public bool IsActive { get; set; }

        public int? UserId { get; set; }

        public Question Question { get; set; }
        public User User { get; set; }
    }

    public class CustomerUserDetails
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public bool IsOwner { get; set; }
    }
```

Can you please provide a full repro for the issue, or modify the code above so that the exception gets thrown?

**Comment by KesavanRadhakrishnan** [comment] 2020-02-17 09:29
@maumar sorry for the delay, Your repro replicates, database provider as MS Sql, but I have used the postgreSql(Npgsql.EntityFrameworkCore.PostgreSQL).

**Comment by ajcvickers** [comment] 2020-02-19 20:44
@roji Possible PostgreSQL issue?

**Comment by roji** [comment] 2020-02-20 09:48
@KesavanRadhakrishnan I've just executed @maumar's [attempted repro](https://github.com/dotnet/efcore/issues/19852#issuecomment-584405621) with Npgsql 3.1 and it executes without any error. Can you please confirm whether that runs for you or not?

What we need is a runnable code sample, like the one @maumar wrote above, which causes the exception to occur - then we can start investigating the cause.

**Comment by KesavanRadhakrishnan** [comment] 2020-02-22 07:10
@roji I have attached my full project below, which throwing error, Please review it.

Program.cs
------------
using System;
using System.Linq;
using System.Threading.Tasks;
using ConsoleApp2.Models;

namespace ConsoleApp2
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using var ctx = new sampledbcontextContext();

        var questionId = 1;
            try
            {

                var query = from question in ctx.Question.Where(i => i.IsActive && i.QuestionId == questionId)
                            from questionMapper in ctx.Questioncustommapper.Where(i => i.IsActive && i.QuestionId == question.QuestionId)
                            from user in ctx.User.Where(i => i.IsActive && **questionMapper.UserId.HasValue** && i.UserId == **questionMapper.UserId.Value**)
                            select new CustomerUserDetails
                            {
                                CustomerId = user.UserId,
                                CustomerName = user.UserName,
                                CustomerEmail = user.UserEmailId,
                                IsOwner = true,
                            };

                var result = query.ToList();
            }
            catch (Exception ex)
            { 
            }
        }
    }
    public class CustomerUserDetails
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public bool IsOwner { get; set; }
    }
}

DbContext
------------

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ConsoleApp2.Models
{
    public partial class sampledbcontextContext : DbContext
    {
        public sampledbcontextContext()
        {
        }

        public sampledbcontextContext(DbContextOptions<sampledbcontextContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Questioncustommapper> Questioncustommapper { get; set; }
        public virtual DbSet<User> User { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("----");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Questioncustommapper>(entity =>
            {
                entity.HasKey(e => e.MapperId)
                    .HasName("PK__question__49305D26C0CCAB");

                entity.ToTable("questioncustommapper");

                entity.HasOne(d => d.Question)
                    .WithMany(p => p.Questioncustommapper)
                    .HasForeignKey(d => d.QuestionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__questionc__Quest__46F928");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.Questioncustommapper)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK__questionc__UserI__441D61");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.Property(e => e.UserEmailId)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.UserName)
                    .HasMaxLength(30)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

Is it clear? and also i have mark bold, which makes problem, if i modified it like as mentioned below it's working fine.
 var query = from question in ctx.Question.Where(i => i.IsActive && i.QuestionId == questionId)
                            from questionMapper in ctx.Questioncustommapper.Where(i => i.IsActive && i.QuestionId == question.QuestionId)
                            from user in ctx.User.Where(i => i.IsActive && i.UserId == questionMapper.UserId)
                            select new CustomerUserDetails
                            {
                                CustomerId = user.UserId,
                                CustomerName = user.UserName,
                                CustomerEmail = user.UserEmailId,
                                IsOwner = true,
                            };

**Comment by KesavanRadhakrishnan** [comment] 2020-02-22 07:19
@maumar Can you please review it, I have done changes.

**Comment by roji** [comment] 2020-02-22 08:44
Confirmed that this throws ("The multi-part identifier "q0.UserId" could not be bound"), and removing the HasValue makes the error go away.

However, after 4cbc5d79b4df0fb999a502d20f586f0aefd5a0fa the JOIN is replaced by a CROSS APPLY and the query works correctly, making this a probable dup of #19825. Leaving to @maumar to confirm there's nothing else going on and to close.

@KesavanRadhakrishnan as a workaround you can simply remove the HasValue check, it's not actually necessary to your query.

Simplified repro and SQL (pre-4cbc5d79b4df0fb999a502d20f586f0aefd5a0fa):

```c#
class Program
{
    static void Main(string[] args)
    {
        using var ctx = new sampledbcontextContext();

        ctx.Database.EnsureDeleted();
        ctx.Database.EnsureCreated();
        
        var query =
            from question in ctx.Question
            from questionMapper in ctx.Questioncustommapper.Where(i => i.QuestionId == question.QuestionId)
            from user in ctx.User.Where(i => questionMapper.UserId.HasValue && i.UserId == questionMapper.UserId.Value)
            select user;

        var result = query.ToList();
    }
}

public class sampledbcontextContext : DbContext
{
    public virtual DbSet<Question> Question { get; set; }
    public virtual DbSet<Questioncustommapper> Questioncustommapper { get; set; }
    public virtual DbSet<User> User { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
                .UseSqlServer("...")
                .UseLoggerFactory(ContextLoggerFactory);
}

public class Question
{
    public int QuestionId { get; set; }

    public virtual ICollection<Questioncustommapper> Questioncustommapper { get; set; }
}

public class Questioncustommapper
{
    public int Id { get; set; }
    public int QuestionId { get; set; }
    public int? UserId { get; set; }
}

public class User
{
    public int UserId { get; set; }

    public virtual ICollection<Questioncustommapper> Questioncustommapper { get; set; }
}
```

SQL (pre-4cbc5d79b4df0fb999a502d20f586f0aefd5a0fa):

```sql
SELECT [t].[UserId]
FROM [Question] AS [q]
INNER JOIN [Questioncustommapper] AS [q0] ON [q].[QuestionId] = [q0].[QuestionId]
INNER JOIN (
    SELECT [u].[UserId]
    FROM [User] AS [u]
    WHERE [q0].[UserId] IS NOT NULL
) AS [t] ON [q0].[UserId] = [t].[UserId]
```

SQL (post-4cbc5d79b4df0fb999a502d20f586f0aefd5a0fa):

```sql
SELECT [t].[UserId]
FROM [Question] AS [q]
INNER JOIN [Questioncustommapper] AS [q0] ON [q].[QuestionId] = [q0].[QuestionId]
CROSS APPLY (
    SELECT [u].[UserId]
    FROM [User] AS [u]
    WHERE [q0].[UserId] IS NOT NULL AND ([q0].[UserId] = [u].[UserId])
) AS [t]
```

**Comment by maumar** [comment] 2020-02-24 20:37
it is indeed a duplicate of #19825, closing as such

**Closed** 2022-10-16 18:10 UTC
Labels: customer-reported
