### ISSUE TITLE
Sub-queries on a query type with defining query are executed locally

### ISSUE THREAD

**Issue by andriysavin** [dotnet/efcore#12763] opened 2018-07-23 12:19 UTC
In my DB context I have these entities (all code is simplified):

```
public DbSet<Tenant> Tenants { get; set; }
public DbSet<User> Users { get; set; }

```
I think that details about entities are not that important here. Now I want to create a query-only repository with another model in addition to what I have. I have following class for a user which also includes tenant organization name:

```
public sealed class UserInfo
{
    public string Id { get; set; }
    public int? TenantId { get; set; }
    public string UserName { get; set; } 
    public string TenantOrganizationName { get; set; }
}

```

I configure it as a EF Query Type with defining query on top of the main entities:

```
builder.Query<UserInfo>().ToQuery(() =>
    from u in Users
    join t in Tenants
    on u.TenantId equals t.Id
    select new UserInfo
    {
        Id = u.Id,
        UserName = u.UserName,
        TenantId = u.TenantId,
        TenantOrganizationName = t.OrganizationName
    });

```

Now I define a couple of queries in my repository using this query type:

Find a user by ID
`await DbContext.Query<UserInfo>().SingleOrDefaultAsync(u => u.Id == userId)`

Get all users ordered by user name
`await DbContext.Query<UserInfo>().OrderBy(u => u.UserName).ToArrayAsync()`

And both of these queries **produce warnings which say that filtering by Id and OrderBy can't be translated and will be executed locally**. That's pretty surprising, since UserInfo is part of the model.

Even more, similar sub-query on the main model works perfectly. Lets define a method which kind of simulates defining query:

```
private IQueryable<UserInfo> GetUserInfoQuery()
{
    return from u in DbContext.Users.AsNoTracking()
           join t in DbContext.Tenants.AsNoTracking()
           on u.TenantId equals t.Id
           select new UserInfo
           {
               Id = u.Id,
               UserName = u.UserName,
               TenantId = u.TenantId,
               TenantOrganizationName = t.OrganizationName
           };
}

```

Now lets try the same queries:

```
var query = GetUserInfoQuery();
await query.SingleOrDefaultAsync(u => u.Id == userId)
```

```
var query = GetUserInfoQuery();
await query.OrderBy(u => u.UserName).ToArrayAsync();
```

These are translated to SQL with no problems. Note that the filter and OrderBy are executed against UserInfo.

### Further technical details
EF Core version: 2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.5

**Comment by smitpatel** [comment] 2018-07-31 16:56
Repro: 
```C#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database


                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                db.Query<UserInfo>().Where(u => u.Id == "").ToList();

                var query = GetUserInfoQuery(db);
                query.Where(u => u.Id == "").ToList();
            }

            Console.WriteLine("Program finished.");
        }

        private static IQueryable<UserInfo> GetUserInfoQuery(MyContext db)
        {
            return from u in db.Users.AsNoTracking()
                   join t in db.Tenants.AsNoTracking()
                   on u.TenantId equals t.Id
                   select new UserInfo
                   {
                       Id = u.Id,
                       UserName = u.UserName,
                       TenantId = u.TenantId,
                       TenantOrganizationName = t.OrganizationName
                   };
        }

    }


    public class MyContext : DbContext
    {
        private static ILoggerFactory LoggerFactory => new LoggerFactory().AddConsole(LogLevel.Trace);

        // Declare DBSets
        public DbSet<Tenant> Tenants { get; set; }
        public DbSet<User> Users { get; set; }


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                //.UseSqlite("filename=_modelApp.db")
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(LoggerFactory);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
            modelBuilder.Query<UserInfo>().ToQuery(() =>
            from u in Users
            join t in Tenants
            on u.TenantId equals t.Id
            select new UserInfo
            {
                Id = u.Id,
                UserName = u.UserName,
                TenantId = u.TenantId,
                TenantOrganizationName = t.OrganizationName
            });
        }
    }

    public class User
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public int TenantId { get; set; }
    }

    public class Tenant
    {
        public int Id { get; set; }
        public string OrganizationName { get; set; }
    }

    public class UserInfo
    {
        public string Id { get; set; }
        public int? TenantId { get; set; }
        public string UserName { get; set; }
        public string TenantOrganizationName { get; set; }
    }

}
```

I am hitting exception while using ToQuery variation.
```
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.0-rtm-30799 initialized 'MyContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: SensitiveDataLoggingEnabled
dbug: Microsoft.EntityFrameworkCore.Query[10101]
      Compiling query model:
      'from UserInfo u in DbSet<UserInfo>
      where [u].Id == ""
      select [u]'
dbug: Microsoft.EntityFrameworkCore.Query[10104]
      Optimized query model:
      'from UserInfo u in
          from User u in DbSet<User>
          join Tenant t in DbSet<Tenant>
          on [u].TenantId equals [t].Id
          select new UserInfo{
              Id = [u].Id,
              UserName = [u].UserName,
              TenantId = (Nullable<int>)[u].TenantId,
              TenantOrganizationName = [t].OrganizationName
          }

      where [u].Id == ""
      select [u]'

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: tableExpression
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.Query.Expressions.ColumnExpression..ctor(String name, IProperty property, TableExpressionBase tableExpression)
   at Microsoft.EntityFrameworkCore.Query.Expressions.SelectExpression.BindProperty(IProperty property, IQuerySource querySource)
   at Microsoft.EntityFrameworkCore.Query.Expressions.SelectExpression.BindProperty(IProperty property, IQuerySource querySource)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.<TryBindMemberOrMethodToSelectExpression>b__28_1[TExpression](IProperty property, IQuerySource querySource, SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.BindMemberOrMethod[TResult](Func`4 memberBinder, IQuerySource querySource, IProperty property, Boolean bindSubQueries)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.<>c__DisplayClass105_0`1.<BindMemberExpression>b__0(IProperty property, IQuerySource qs)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.<>c__DisplayClass91_0`1.<BindMemberExpression>b__0(IReadOnlyList`1 ps, IQuerySource qs)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindPropertyExpressionCore[TResult](Expression propertyExpression, IQuerySource querySource, Func`3 propertyBinder)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, Func`4 memberBinder, Boolean bindSubQueries)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.TryBindMemberOrMethodToSelectExpression[TExpression](TExpression sourceExpression, Func`4 binder)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.ProcessComparisonExpression(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression expression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.ExpressionVisitors.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFSampleApp.Program.Main(String[] args) in D:\code\EFSampleApp\EFSampleApp\Program.cs:line 27
```

**Comment by andriysavin** [comment] 2018-07-31 20:50
Funny, I've just tried to reproduce this issue again on my real application, and now it fails with the same exception (instead of warnings).

**Comment by smitpatel** [comment] 2018-07-31 22:43
Duplicate of #11792

**Closed** 2022-10-16 13:21 UTC
Labels: closed-duplicate, customer-reported
