### ISSUE TITLE
Composite keys with one auto incrementing field fails on AddRange()

### ISSUE THREAD

**Issue by dligge** [dotnet/efcore#6575] opened 2016-09-20 03:00 UTC
### Steps to reproduce

I'm trying to set up a table with a composite key, where one of the fields autoincrements. Here's the relevant code from the model and context classes:

In the model class:

```
[Key]
[DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Might not be needed, just trying to make it work
public int EventId { get; set; }

[Required]
public string UserId { get; set; }
```

In the DB context:

```
public DbSet<Event> Events { get; set; }
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Event>()
        .HasKey(e => new { e.EventId, e.UserId });
}
```
### The issue

In the application code, EventId is never directly set - I'm leaving that up to the database. When trying to insert multiple events (all of which have EventId=0, the default value) I get this error on the .AddRange() call:

```
Exception message: An exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code

Additional information: The instance of entity type 'Event' cannot be tracked because another instance of this type with the same key is already being tracked. When adding new entities, for most key types a unique temporary key value will be created if no key is set (i.e. if the key property is assigned the default value for its type). If you are explicitly setting key values for new entities, ensure they do not collide with existing entities or temporary values generated for other new entities. When attaching existing entities, ensure that only one entity instance with a given key value is attached to the context.
Stack trace:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityStates(IEnumerable`1 entities, EntityState entityState)
   at <my application's code>
```
### Further technical details

EF Core version: 1.0.1
Operating system: Windows 7
Visual Studio version:  VS 2015

Other details about my project setup: I've run database migrations (to postgres) with these classes, and the resulting SQL table looks correct - the primary key is a composite key of the two Ids, and the EventId field is set to autoincrement.

If I remove the composite key declaration in OnModelCreating(), then I can insert in bulk just fine, and the EventId is populated correctly.

**Comment by ajcvickers** [comment] 2016-09-20 16:33
Note for triage: I was able to reproduce this with the RTM release but it does not repro with the latest bits. I believe it is likely a duplicate of #5776.

@dligge You should be able to work around the issue by setting the EventId property to store generated _after_ the HasKey call. For example:
```C#
modelBuilder.Entity<Event>(b =>
{
    b.HasKey(e => new { e.EventId, e.UserId });
    b.Property(e => e.EventId).ValueGeneratedOnAdd();
});
```

**Closed** 2022-10-16 09:58 UTC
