### ISSUE TITLE
One to many relationship > Mandatory FK with DeleteBehaviour Restricted > does not allow removing child entities

### ISSUE THREAD

**Issue by maulik-modi** [dotnet/efcore#25241] opened 2021-07-12 13:30 UTC
We are trying to use DDD style repository pattern per Aggregate root but unable to delete child entities with FK association: DeleteBehavior Restricted. Please find attached sample with *Blog* and *Post*. 

**Constraint**
We are not allowed to use Delete Behaviour: Cascade in EF Core or Database as both may lead to accidental data loss.

### Include your code
```
 public class Post
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
        public Blog Blog { get; set; }
    }

public class Blog
    {
        public int Id { get; set; }
        public ICollection<Post> Posts { get; set; }
    }

 public class BlogRepository : IBlog
    {
        private readonly BlogContext _applicationdbContext;

        public BlogRepository(BlogContext dbContext)
        {
            _applicationdbContext = dbContext;
        }

        public Blog Get(int id)
        {
            var blog = _applicationdbContext.Blogs
                        .Where(s => s.Id == id)
                        .AsSplitQuery()
                        .Include(s => s.Posts)
                        .FirstOrDefault();

            return blog;
        }

  public void SaveChanges()
        {
            _applicationdbContext.SaveChanges();
        }
}

 public class Program
    {

        public static void Main()
        {
            var collection = new ServiceCollection();
            collection
                .AddDbContext<BlogContext>()
                .AddScoped<IBlog, BlogRepository>();

            var service = collection.BuildServiceProvider();
            var _repo = service.GetService<IBlog>();

            //Fetching Record
            var blog = _repo.Get(1);

            //Updating BlogID with existing Post
            var data = blog.Posts.FirstOrDefault();
            if (data != null)
                data.BlogId = 2;

            ///Removing post from entity
            int postId = data.Id;
            var removeData = blog.Posts.FirstOrDefault(x => x.Id != postId);
            if (removeData != null)
                blog.Posts.Remove(removeData);

            // Adding New Post with blog
            var post = new Post();
            blog.Posts.Add(post);
       
            _repo.SaveChanges();
        }
    }

 public class PostConfig : IEntityTypeConfiguration<Post>
    {
        public void Configure(EntityTypeBuilder<Post> builder)
        {
            builder.ToTable("post");
            builder.HasKey(t => t.Id);
            builder.HasOne(d => d.Blog)
            .WithMany(p => p.Posts)
            .HasForeignKey(d => d.BlogId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_Blog_Id_Post_BlogID");
        }
    }

  public class BlogConfig : IEntityTypeConfiguration<Blog>
    {
        public void Configure(EntityTypeBuilder<Blog> builder)
        {
            builder.ToTable("blog");
            builder.HasKey(t => t.Id);
        }
    }

 public class BlogContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql(
                "Server=localhost;port=5432;user id=postgres;password=password;database=SampleDB;pooling=true;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new BlogConfig());

            modelBuilder.ApplyConfiguration(new PostConfig());
        }
    }
```

[RestrictDelete.zip](https://github.com/dotnet/efcore/files/6801505/RestrictDelete.zip)

### Include stack traces

```
              Error:The association between entity types 'Blog' and 'Post' has been severed, 
            but the relationship is either marked as required or is implicitly required because the foreign key is not nullable.
 
            If the dependent/ child entity should be deleted when a required relationship is severed, 
            configure the relationship to use cascade deletes. Consider using 'DbContextOptionsBuilder.
             EnableSensitiveDataLogging' to see the key values.'

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.HandleConceptualNulls(Boolean sensitiveLoggingEnabled, Boolean force, Boolean isCascadeDelete)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete, CurrentValueType valueType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.ConditionallyNullForeignKeyProperties(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.NavigationCollectionChanged(InternalEntityEntry entry, INavigationBase navigationBase, IEnumerable`1 added, IEnumerable`1 removed)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.NavigationCollectionChanged(InternalEntityEntry entry, INavigationBase navigationBase, IEnumerable`1 added, IEnumerable`1 removed)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigationBase navigationBase)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.LocalDetectChanges(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges()
   at Microsoft.EntityFrameworkCore.DbContext.TryDetectChanges()
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at CascadeDelete.BlogRepository.SaveChanges() in D:\Projects\POC\CascadeDelete\CascadeDelete\BlogRepository.cs:line 40
   at CascadeDelete.Program.Main() in D:\Projects\POC\CascadeDelete\CascadeDelete\Program.cs:line 51
```

### Include provider and version information

EF Core version: 5.0.7
Database provider: NpgSQL
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE:  Visual Studio 2019

**Comment by ajcvickers** [comment] 2021-07-15 16:54
@maulik-modi The problem is with this code:

```C#
int postId = data.Id;
var removeData = blog.Posts.FirstOrDefault(x => x.Id != postId);
if (removeData != null)
    blog.Posts.Remove(removeData);
```

In this code, the Post is removed from the Posts collection on the Blog. This means that this Post is no longer associated with the given Blog. However, this does not mark the Post as deleted, only severed from its existing relationship. You can manually mark the Post as Deleted, in which case it will be deleted when SaveChanges is called. If the Post is not marked as Deleted, then a few things can happen depending on how the relationship is configured:
* If the relationship is marked for cascades, then the Post will be deleted when SaveChanges is called.
* Otherwise, if the relationship is optional and the FK is nullable, then the FK will be set to null when SaveChanges is called.
* Otherwise, the entity is in a state that cannot be persisted to the database because the FK does not have a valid value and cannot be nulled. This is the case you are hitting, and hence and exception is thrown.

Consider having a good read of the [Change Tracking docs](https://docs.microsoft.com/en-us/ef/core/change-tracking/), and in particular [Changing Foreign Keys and Navigations](https://docs.microsoft.com/en-us/ef/core/change-tracking/relationship-changes).

**Comment by maulik-modi** [comment] 2021-07-16 04:55
@ajcvickers , As per documentation link you shared, we are expecting **Deleting Orphans** behaviour under **Required relationship**. Can you explain why below code results in Delete query and our sample throws error!

```
var post = dotNetBlog.Posts.Single(e => e.Title == "Announcing F# 5");
dotNetBlog.Posts.Remove(post);
```

Results in

```
DELETE FROM "Posts"
WHERE "Id" = @p0;
SELECT changes();

```

![image](https://user-images.githubusercontent.com/34910430/125893542-b626cbe8-6da8-4330-b4eb-5a1abbda312c.png)

**Comment by ajcvickers** [comment] 2021-07-19 18:20
@maulik-modi 

1. Yes, or by setting the state directly. See https://docs.microsoft.com/en-us/ef/core/change-tracking/#entity-states, https://docs.microsoft.com/en-us/ef/core/change-tracking/entity-entries#working-with-the-entity, and https://docs.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking#deleting-existing-entities
2. Typically, don't set the relationship to Restrict. The default behavior for required relationships is Cascade, which means that the child cannot live without its parent. See https://docs.microsoft.com/en-us/ef/core/change-tracking/relationship-changes#changing-relationships-using-navigations

**Closed** 2022-10-16 19:39 UTC
Labels: closed-no-further-action, customer-reported
