### ISSUE TITLE
CosmosDB: ChangeTracker does not allow 2 entities with same ID but different PartitionKey

### ISSUE THREAD

**Issue by MartinKosicky** [dotnet/efcore#33903] opened 2024-06-04 18:35 UTC
According to CosmosDB documentation you can have the same "id" in diferent logical partitions. 

Suppose i have this class
```
class ComputerRecord
{
    public string ComputerId {get;set;}    // in fluent configured to as Key and mapped to "id"
    public string CustomerId {get;set;}      // in fluent configured as PartitionKey
    public string Note {get;set;}
}
```
However if i try to add into db context 2 entities with id ="id1" but one has partitionKey set to "pk1" and another to "pk2" ,  I get error that:

`System.InvalidOperationException: The instance of entity type 'ComputerRecord' cannot be tracked because another instance with the same key value for {'ComputerId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.`

Even more serious is when we do something like this
```
var computer1 = ctx.Computers.Where(f=>f.CustomerId == "s1" && f.ComputerId == "c1").First();
computer1.Note = "newNote";
var computer2 = ctx.Computers.Where(f=>f.CustomerId == "s2" && f.ComputerId == "c1").First();
// computer2.Note is also newNote
```

as this can lead to data corruption

**Comment by ajcvickers** [comment] 2024-06-05 11:15
@MartinKosicky Both ID properties should be included in the primary key definition used by EF Core. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2024-07-01 14:03
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-07-01 14:03 UTC
Labels: customer-reported, area-cosmos
