### ISSUE TITLE
Entity property 'DefaultValue' does not work.

### ISSUE THREAD

**Issue by SF-Simon** [dotnet/efcore#30377] opened 2023-03-01 16:43 UTC
hello everyone.
I use EF7+Sqlite, my test code, which is the key part, and I have omitted the rest.

```
    public class Token
    {
        public int Id { get; set; }

        [DefaultValue("Default Name")]
        public string Name { get; set; } = string.Empty;

        [DefaultValue(true)]
        public bool IsUpload { get; set; } = true;

        [DefaultValue(typeof(DateTime), "datetime('now', 'localtime')")]
        public DateTime? ValidFrom { get; set; } = DateTime.MinValue;

        [DefaultValue("datetime('now', 'localtime')")]
        public DateTime CreatedTime { set; get; } = DateTime.Now;

       public DateTime HasDefaultValueTime { set; get; } = DateTime.Now;
    }


    public class TestDbContext : DbContext
    {
        public DbSet<Token> Token { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Token>().Property(token => token.CreatedTime).HasDefaultValueSql("datetime('now', 'localtime')");
        }
    }
```
_Add-Migration InitialCreate_
Generated the "InitialCreate. cs" file code:
```
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Token",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Name = table.Column<string>(type: "TEXT", nullable: false), // There is no code to generate default values.
                    IsUpload = table.Column<bool>(type: "INTEGER", nullable: false), // There is no code to generate default values.
                    ValidFrom = table.Column<DateTime>(type: "TEXT", nullable: true), // There is no code to generate default values.
                    CreatedTime = table.Column<DateTime>(type: "TEXT", nullable: false), // There is no code to generate default values.
                    HasDefaultValueTime = table.Column<DateTime>(type: "TEXT", nullable: false, defaultValueSql: "datetime('now', 'localtime')")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Token", x => x.Id);
                });
        }
```

It can be seen that unless the _HasDefaultValueSql_ method is used in _OnModelCreating_, the migration code does not generate any parameters and values related to the default value.

In other words, this does not meet my expectations for the entity attribute _DefaultValue_. It seems to have no constraints.

At the beginning, I thought that as long as I added the _DefaultValue_ entity attribute to the field, the creation code of the same column as the _HasDefaultValueTime_ field would be generated, but the result showed that I was wrong and it did not meet my expectations.

I tried to view the document and found that there was no information about the entity attribute, but it does exist.

So I want to ask, is my use method wrong, or is it useless?

**Comment by ajcvickers** [comment] 2023-03-01 17:17
Duplicate of #19546. Please vote (👍) for that issue.

**Closed** 2023-03-08 13:42 UTC
Labels: closed-duplicate, customer-reported
