### ISSUE TITLE
ExecutionStrategy does not apply to Migrate() and various other functions

### ISSUE THREAD

**Issue by brian-poteet-ni** [dotnet/efcore#27450] opened 2022-02-15 21:03 UTC
## File a bug

The default EnableRetryOnFailure() retry strategy supported by Npgsql applies to standard database transactions, but does not catch connection failures when calling functions such as Migrate(), GetMigrations(), EnsureCreated(), etc.

This issue was initially reported on the Npgsql github but it appears this is an EF Core issue. See here for more details: https://github.com/npgsql/efcore.pg/issues/155#issuecomment-503175566

### Include your code

```C#
optionsBuilder.UseNpgsql(connectionString, options => options.EnableRetryOnFailure());
...
_database.Database.GetService<IMigrator>().Migrate(migrationName);
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
Unhandled exception. Npgsql.NpgsqlException: Exception while connecting.
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.<RawOpen>d__152.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Npgsql.NpgsqlConnector.<Open>d__148.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Npgsql.NpgsqlConnection.Open()
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
```

### Include provider and version information

EF Core version:
Database provider: Npgsql.EntityFramework.PostgreSQL
Target framework: .NET Framework 4.6.2
Operating system: Windows 10
IDE: Visual Studio 2022

**Comment by roji** [comment] 2022-02-16 11:15
As @AndriySvyryd wrote in https://github.com/npgsql/efcore.pg/issues/155#issuecomment-503175566, the main issue is migration operations which cannot be executed in a transaction - but we could still do retries for the others.

Note #22616 which is about wrapping all migrations in a single transaction, when possible (and IIRC only for SQL scripts). In that case, retrying would mean retrying the whole thing (all migrations).

**Comment by bricelam** [comment] 2022-10-19 22:26
Duplicate of #17578

**Closed by bricelam** 2022-10-19 22:26 UTC
Labels: customer-reported
