### ISSUE TITLE
Fire event when DbContext is served from pool

### ISSUE THREAD

**Issue by msawczyn** [dotnet/efcore#23774] opened 2020-12-28 15:29 UTC
https://github.com/dotnet/efcore/issues/14169

If there were an event available on the pool that raised when a DbContext object was served from the pool, client code could perform request-scoped (or any other type of) legal reconfiguration ad hoc.

**Comment by ajcvickers** [comment] 2021-01-01 18:02
Duplicate of #17086

**Closed** 2022-10-16 19:16 UTC
Labels: closed-duplicate, customer-reported
