### ISSUE TITLE
Migrations stopped working

### ISSUE THREAD

**Issue by xavirm** [dotnet/efcore#6788] opened 2016-10-15 18:09 UTC
First, a couple of days ago, a new version of ASP.NET Core downloaded to my Visual Studio 2015.
In one of my projects, migrations stopped working.
Created new project and everything worked fine.
Several days after that incident, I was working with another ASP.NET Core project (a different one), successfully made a couple of migrations, but then the third just run fine (no error messages) but the database didn't reflect the Model changes.
Because I run add-migration and update-database commands "successfully", now I cannot remove-migration and I have not my database updated.
What should I do ?
Thanks a lot.
Regards,

**Comment by bricelam** [comment] 2016-10-17 15:44
Could you post the output of running `Update-Database -Verbose`?

**Comment by bricelam** [comment] 2016-11-02 19:40
Closing since I have not been able to reproduce this. Feel free to re-open with additional information.

**Closed** 2022-10-16 10:38 UTC
Labels: closed-could-not-reproduce
