### ISSUE TITLE
[Sqlite] [iOS] Value cannot be null parameter name : key

### ISSUE THREAD

**Issue by Montaser1998** [dotnet/efcore#20286] opened 2020-03-14 22:02 UTC
### Steps to reproduce
1-Create Project Xamarin.Forms
2- Install Microsoft.EntityFrameworkCore.Sqlite on Xamarin.iOS
3- Add class to used DbContext
4- Get Path database form iOS Project 
``` C#
public string GetFullPath(string databaseFileName)
{
   var sqlitePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "..", "Library", "MetaData");
   if (!Directory.Exists(sqlitePath))
       Directory.CreateDirectory(sqlitePath);
   var fullPathSqlite = $"{sqlitePath}/{databaseFileName}";
   if (!File.Exists(fullPathSqlite))
       File.Create(fullPathSqlite);
   return fullPathSqlite;
}
```
4- Run iOS Project
5- Show Error Message 
![image](https://user-images.githubusercontent.com/16105378/76689867-f7d49400-6642-11ea-97ee-4d8b25db8d1a.png)

This stacktrace:
```
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:488 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:240 
  at Microsoft.EntityFrameworkCore.Sqlite.Query.Internal.SqliteDateTimeAddTranslator..ctor (Microsoft.EntityFrameworkCore.Query.ISqlExpressionFactory sqlExpressionFactory) [0x000c5] in <7b7aa88a95d54aa786bada86edd4821a>:0 
  at Microsoft.EntityFrameworkCore.Sqlite.Query.Internal.SqliteMethodCallTranslatorProvider..ctor (Microsoft.EntityFrameworkCore.Query.RelationalMethodCallTranslatorProviderDependencies dependencies) [0x0001d] in <7b7aa88a95d54aa786bada86edd4821a>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:936 
```
**Notes: I am add this attribute : [assembly: Preserve(typeof(System.Linq.Queryable), AllMembers = true)]
and add this line in main.cs : SQLitePCL.Batteries_V2.Init(); and no thing to working to hide this issue
but if make Linker Behavior : to Don't Link it's run**

### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework:  .NET Standard 2.1, Xamarin.iOS
Operating system: iOS
IDE: Visual Studio 2019 16.4.6

**Comment by ajcvickers** [comment] 2020-03-16 20:18
@JeremyLikness Just a heads-up that we assigned this to you to do some initial investigation into what is happening on Xamarin/iOS here.

**Comment by smitpatel** [comment] 2020-03-20 17:34
Duplicate of #10963 
See discussion in #14091

**Closed** 2022-10-16 18:16 UTC
Labels: customer-reported, area-platform
