### ISSUE TITLE
Nullable foreign key property deletes self entity from the database when set to null 

### ISSUE THREAD

**Issue by VincentVanclef** [dotnet/efcore#27260] opened 2022-01-24 12:17 UTC
Hi there,

So recently we had issues with a client reporting data being deleted, and we asked him for a step-by-step on what he did before the data went missing. We were a bit confused, as the step did not call for any direct Delete methods. So we went and checked our table configurations for any bugged Cascading Deletes. 

However, the cascading delete looks to be correct both code-wise and in the database (We always use the build in RelationalDatabaseCreator to ensure the DB and Code is in sync). The class has a nullable property, which was a foreign key, when that property was set to NULL, it deleted the class entity from the database? This makes no sense to me.

Im not so sure whether this is a bug, or intended, in either case I would love to know why this is happening.

1. Create CAR entity:
![image](https://user-images.githubusercontent.com/541084/150781278-f121ed3f-4696-4b97-aa50-792c3e045b3e.png)

2. Attach two Drivers to the car
![image](https://user-images.githubusercontent.com/541084/150781343-2cfa0fb8-7efe-4c35-b295-d48531616412.png)

So far so good..

Now, i want to remove the CAR from Driver 1 by setting CarId to NULL, this triggers a DELETE command to the database and completely removes the driver, why is this? The foreign key ive set in the DriverConfiguration should (from how i understand it) make it so IF the Car gets deleted, then the Driver is deleted as well. 

![image](https://user-images.githubusercontent.com/541084/150781492-3c3482b7-3d57-4182-b556-53149514ca3a.png)

I have attached the demo project here: [test.zip](https://github.com/dotnet/efcore/files/7925429/test.zip)

EF Core version: 6.0.0
Database provider:  Microsoft.EntityFrameworkCore.SqlServer 6.0.0
Target framework: (e.g. .NET 5.0) .net 6
Operating system: windows 10
IDE: visual studio 2022

**Comment by ajcvickers** [comment] 2022-01-24 12:32
Duplicate of #27174.

**Closed** 2022-10-16 20:23 UTC
Labels: closed-duplicate, customer-reported
