### ISSUE TITLE
InvalidOperationException after upgrading to net core 3.0

### ISSUE THREAD

**Issue by KeKl** [dotnet/efcore#17090] opened 2019-08-12 08:34 UTC
Already posted in the asp.net repo. Wasnt Cure if it´s an ef or identity issue.

### Describe the bug
After upgrading to net core 3.0 and related ef core I get an exception
InvalidOperationException: Operation is not valid due to the current state of the object.

What I do is looking for activities for the user:
`await _context.Activities.Where(x => x.Owner == user).ToListAsync();`

If I check 
`await _context.Activities.Where(x => x.OwnerId == userId).ToListAsync();`
everything is working as expected.

How can I debug this? Any hints what has changed in ef core 3?
This also happens with user set to null.

Smalles Project I can extract:
https://kevinklein.visualstudio.com/NewRepo

**Comment by ajcvickers** [comment] 2019-08-12 16:07
@KeKl Can you try with the latest [daily build](https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md). If it still fails, then please post the full stack trace.

**Comment by jsheetzati** [comment] 2019-08-15 01:51
Also seeing this error with latest daily build + latest preview SDK.

System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Translate(InMemoryQueryExpression queryExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at CustomCode
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__0() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\AsyncTestSyncContext.cs:line 68

**Comment by ajcvickers** [comment] 2019-08-15 14:50
@jsheetzati Have you tried the latest daily build?

**Comment by smitpatel** [comment] 2019-08-15 14:56
Duplicate of #15855

Second issue is altogether different issue.

**Comment by jsheetzati** [comment] 2019-08-15 15:21
@ajcvickers Not seeing the same issue anymore with 3.0.0-preview9.19415.1. Thanks!!

**Closed** 2022-10-16 14:35 UTC
Labels: closed-no-further-action, customer-reported
