### ISSUE TITLE
Custom ChangeTracker to properties

### ISSUE THREAD

**Issue by ErliSoares** [dotnet/efcore#10644] opened 2018-01-04 19:18 UTC
Is possible add a custom ChangeTracker to properties?
It would be something like ChangeTracker.TrackGraph (,), but global for all entities.
I want to do something similar with:

```CSHARP
public class EntityParent
{
    public int Id { get; set; }

    [Save(UpdateOnly)]
    public EntityChild ChildOne { get; set; }

    [Save(Never)]
    public EntityChild ChildTwo { get; set; }
}

public class EntityChild
{
    public int Id { get; set; }
}
```
Make changes according to attributes.

Sorry for my English

**Comment by ajcvickers** [comment] 2018-01-08 16:45
@ErliSoares Can you explain a bit more what these attributes would do? I don't think there is anything like this now, but I would like to understand if it makes sense to put something on the backlog.

**Comment by ajcvickers** [comment] 2018-01-17 19:54
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:04 UTC
Labels: closed-could-not-reproduce
