### ISSUE TITLE
Cannot access a disposed context instance.

### ISSUE THREAD

**Issue by pariashiri1984** [dotnet/efcore#24397] opened 2021-03-14 11:12 UTC
I face this error when I try to update my views from DB.
I added a partial class to my EF auto-generated class:
```
public partial class TblCustomer
{
        private  Mycontext _context;
.
.
.
 public int getSortedCount()
        {
            var parameterReturn = new SqlParameter
            {
                ParameterName = "result",
                SqlDbType = System.Data.SqlDbType.Int,
                Direction = System.Data.ParameterDirection.Output,
            };
            var paramID = new SqlParameter
            {
                ParameterName = "id",
                SqlDbType = System.Data.SqlDbType.Int,
                Direction = System.Data.ParameterDirection.Input,
                Value = CustomerId
            };
            _context.Database
                .ExecuteSqlRaw("exec sp_getCountSortedByCustomerID @id,@result output", paramID, parameterReturn);
            return (int)parameterReturn.Value;
        }
}
```
when I try to execute getSortedCount() function for the second time I have this error. 
in my startup 

```
 services.AddDbContext<Mycontext>
                (option => 
                option.UseSqlServer(Configuration.GetConnectionString("DB")),
                ServiceLifetime.Transient, ServiceLifetime.Transient);
```
and the error is :
ObjectDisposedException: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances. Object name: 'Mycontext'.

EF Core version: 5
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:WIindow 10
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment] 2021-03-16 20:37
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2021-03-26 14:46
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:27 UTC
Labels: closed-could-not-reproduce, customer-reported
