### ISSUE TITLE
Insert in dbcontext always uses default value for int and bit data types

### ISSUE THREAD

**Issue by ibruynin** [dotnet/efcore#8540] opened 2017-05-22 12:44 UTC
If the SQL table contains a default value for and int (or a bit - I tried both, maybe even for all data types), the call to SaveChanges() defaults the value, even it is supplied.

Using the following nuget dependencies:
* Microsoft.EntityFrameworkCore.SqlServer.Design (1.1.2)
* Microsoft.EntityFrameworkCore (1.1.2)
* Microsoft.EntityFrameworkCore.Tools (1.1.2)

#### Create the database (using VS2017 built-in database)
```
CREATE TABLE [dbo].[AotPackage]
(
	[Id] INT IDENTITY NOT NULL PRIMARY KEY,
	Name nvarchar(100), 
        [CodeUpgrade] INT NOT NULL DEFAULT 1
);
CREATE TABLE [dbo].[AotModel]
(
	[Id] INT IDENTITY NOT NULL PRIMARY KEY,
	Name nvarchar(100) NOT NULL,
	PackageId int REFERENCES AotPackage(Id) NOT NULL
);
```
Publish connect string:
```
Data Source=(localdb)\MSSQLLocalDB;Integrated Security=True;Persist Security Info=False;Pooling=False;MultipleActiveResultSets=False;Connect Timeout=60;Encrypt=False;TrustServerCertificate=True
```

#### reverse engineer the database
```
Scaffold-DbContext "Server=(localdb)\mssqllocaldb;Database=ReproDb;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -Force
```
#### reverse engineer the database
```c#
var context = new ReproDbContext();
AotPackage p = new AotPackage()
            {
                Name = "test", 
                CodeUpgrade = 0, // << this one will be defaulted to 1
                AotModel = new AotModel[] {
                    new AotModel()
                    {
                        Name = "test"
                    }
                }
            };
context.AotPackage.Add(p);
context.SaveChanges();
```

note: this is a partial code snippet - I guess it's enough to repro.

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10 (Creator update)
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment] 2017-05-22 17:18
Duplicate of #7089

**Comment by ibruynin** [comment] 2017-05-29 07:38
Hi @ajcvickers 
I read about the duplicate issue #7089 and the related ones. 
I can see and understand the issue about 0 (which is the CLR default value) being replaced by the SQL default value.
Is there really no other option (e.g. replacing the int with Integer) to resolve the IMHO *really unexpected* behavior? If not, are there still plans to generate warnings? I did not find any open issues related to that.
Cheers.

**Comment by ajcvickers** [comment] 2017-05-31 02:43
@ibruynin We discussed warnings and decided to only warn for bools--see #7163. The main problem here is that any behavior is unexpected depending on where you approach the issue from. The discussions here and over the years have shown that:
- Some people expect the store default to be used always. They are surprised that when a property has a value, then the store default is not used.
- Some people expect the store default never to be used. They are surprised when a store default is used when they have not specifically requested it.

In general, the most useful behavior is to allow the store default to be used only when a specific value has not been set. But when working POCO objects there is no obvious way to do that. I haven't seen anything that we think is a better option than what we have.

**Closed** 2022-10-16 11:05 UTC
Labels: closed-duplicate
