### ISSUE TITLE
How to deploy EF Migration at Release Time With Azure Pipelines

### ISSUE THREAD

**Issue by BertCotton** [dotnet/efcore#15228] opened 2019-04-01 22:12 UTC
Is there any documentation for doing EF Migration at release time?  We are using the Azure Pipeline builds and could do it at build time, but that doesn't work because we need to to build once and deploy to each environment.
We do not want to do it at app runtime either.  We want it to be a part of the release.

The only way that I've found to do it is to create a script 'dotnet ef migrations script..' during the build against a *.db file in the repo (which isn't ideal) and then ru nthat sql file during the release.

**Comment by ajcvickers** [comment] 2019-04-05 19:21
This is essentially a duplicate of #9841. @BertCotton There is some good information in the discussion on that issue, including a link to a post by Ben Day that should be quite useful.

**Comment by BertCotton** [comment] 2019-04-05 19:44
That's unfortunate.  Maybe some good information but not a solution.  Crazy that has been requested for over 6 months and still no solution.  Definitely not something that would be production ready.

**Closed** 2022-10-16 13:58 UTC
Labels: customer-reported
