### ISSUE TITLE
Performance issue query char(10) column using varchar(max)

### ISSUE THREAD

**Issue by wdnijdam** [dotnet/efcore#19579] opened 2020-01-13 16:23 UTC
I use a char(10) column in my database and also have mapped it.

When executing a query EF core generates a query with a varchar(max) sql variable in the ExecuteSql. SQL server will not use my index in this case. 

EF should also set the length of the variable correctly. The variable created should be exactly the same type as the column to prevent any issues.

### Steps to reproduce
In the mapping I use a fixed length column

```c#
            builder.Property(so => so.ConnectionId)
                .HasColumnName("ConnectionId")
                .HasColumnType("char(10)")
                .IsUnicode(false)
                .IsFixedLength()
                .HasMaxLength(10);
```

Linq query:
```c#
public static Task<string> GetAccessInstance(string connectionId, GoBossEntities goBossDb)
        {
            return goBossDb.SupplierOrders
                .TagWith("GoBossBiz.GetAccessInstance")
                .OfType<SupplierOrderWba>()
                .Where(so => so.ConnectionId == connectionId &&
                             so.ConnectionId != null &&
                             so.OutServiceDt == null &&
                             so.StateId != SupplierOrderStateId.DeniedIgnore)
                .OrderByDescending(so => so.SupplierOrderId)
                .Select(x => x.AccessInstanceId)
                .FirstOrDefaultAsync();
        }
```

Results in this query:
```sql
exec sp_executesql N'-- GoBossBiz.GetAccessInstance

SELECT TOP(1) [so].[WbaAccessInstanceId]
FROM [dbo].[SupplierOrder] AS [so]
WHERE ([so].[SupplierTypeId] = ''WBA'') AND (((([so].[ConnectionId] = @__connectionId_0) AND [so].[ConnectionId] IS NOT NULL) AND [so].[OutServiceDt] IS NULL) AND ([so].[StateId] <> CAST(31 AS tinyint)))
ORDER BY [so].[SupplierOrderId] DESC',N'@__connectionId_0 varchar(max) ',@__connectionId_0='1234567890'
```

### Further technical details
EF version: 2.2
Database Provider: EntityFramework.SqlServer
Operating system:  Windows 10

This is the index that is not used. It will be used if I manually alter the varchar(max) to varchar(100) or char(10) in the query. This is also a strange limitation on the SQL server side.

```sql
CREATE NONCLUSTERED INDEX [IX_SupplierOrder_ConnectionId] ON [dbo].[SupplierOrder]
(
	[ConnectionId] ASC,
	[SupplierTypeId] ASC
)
WHERE ([ConnectionId] IS NOT NULL)
```

If needed I could extract a small example from my code. That would require some effort so let me know if a working example is required.

Regards,

Willem-Derk Nijdam

**Comment by ajcvickers** [comment] 2020-01-13 16:45
Duplicate of #14555

**Comment by wdnijdam** [comment] 2020-01-14 11:49
Work around:

`return await goBossEntities.SupplierOrders
                    .FromSql("select * from [dbo].[SupplierOrder]") // Work around to change search to varchar(10)
                    .TagWith(nameof(GoBossRepository) + ":" + nameof(GetWbaAccessInstance))
                    .OfType<SupplierOrderWba>()
                    .Where(so => so.ConnectionId == connectionId &&
                                 so.ConnectionId != null &&
                                 so.OutServiceDt == null &&
                                 so.StateId != SupplierOrderStateId.DeniedIgnore)
                    .OrderByDescending(so => so.SupplierOrderId)
                    .Select(x => x.AccessInstanceId)
                    .FirstOrDefaultAsync(cancellationToken);`

This produces varchar(10) as variable

**Closed** 2022-10-16 18:05 UTC
Labels: closed-duplicate, customer-reported
