### ISSUE TITLE
Reference and IsModified

### ISSUE THREAD

**Issue by FlyingWraptor** [dotnet/efcore#19131] opened 2019-12-02 17:07 UTC
I'm currently unit-testing my repository and hit a barrier.
The update function should ignore any changes made to the reference of the publisher for the album

### Steps to reproduce

```csharp
this._dbContext.Entry(album)
    .Reference(o => o.Publisher)
    .IsModified = false;
```

The Album has the property:
```csharp
public Account Publisher { get; set; }
```

Testing this:
```csharp
album.Publisher = this._dbcontext.DbContext.Accounts.First(a => a.Id == 2);
Assert.NotEqual((ulong)2, album.Publisher.Id);

// Result:
// Expected: Not 2
// Actual:   2
```

### Further technical details

EF Core version: 3.0.0
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: .NET STANDARD 2.1
Operating system: Windows 10 v1909
IDE: Visual Code

**Comment by ajcvickers** [comment] 2019-12-02 21:58
@FlyingWraptor I am not able to reproduce this--see my code below. Setting `IsModified` to false is marking the FK as as not modified, which means it is not saved. Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

```C#
public class Publisher
{
    public int Id { get; set; }
    public ICollection<Blog> Blogs { get; set; }
}

public class Blog
{
    public int Id { get; set; }
    public Publisher Publisher { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>();
    }
    
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var blog = new Blog {Publisher = new Publisher()};
            context.Add(blog);

            context.SaveChanges();

            Console.WriteLine(blog.Publisher.Id);
        }

        using (var context = new BloggingContext())
        {
            var blog = context.Set<Blog>().Include(e => e.Publisher).Single();
            
            Console.WriteLine(blog.Publisher.Id);

            blog.Publisher = new Publisher();

            context.Entry(blog).Reference(e => e.Publisher).IsModified = false;

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var blog = context.Set<Blog>().Include(e => e.Publisher).Single();
            
            Console.WriteLine(blog.Publisher.Id);
        }
    }
}
```

**Comment by FlyingWraptor** [comment] 2019-12-03 07:50
You can find the full library here:
https://gitlab.com/wheezie/apitools.aspnetcore

Links to the applicable files:
https://gitlab.com/wheezie/apitools.aspnetcore/blob/master/ApiTools.AspNetCore/Repos/AlbumRepository.cs
https://gitlab.com/wheezie/apitools.aspnetcore/blob/master/ApiTools.AspNetCore.EF/Models/Albums.cs
https://gitlab.com/wheezie/apitools.aspnetcore/blob/master/ApiTools.AspNetCore.Tests/Repos/AlbumRepository/AlbumRepositoryTests_updating.cs


The automated test results can be found here:
https://gitlab.com/wheezie/apitools.aspnetcore/-/jobs/367511045

**Comment by FlyingWraptor** [comment] 2019-12-03 07:59
Perhaps this is an in-memory  db issue?

**Comment by ajcvickers** [comment] 2019-12-04 23:51
@FlyingWraptor Thanks for the additional info. It looks like the FK property is correctly marked as not modifed, which means the change is not saved. However, the original value is not restored, nor does fixup happen. I will discuss with the team.

**Comment by FlyingWraptor** [comment] 2019-12-05 07:36
I suppose I could fix this by adding a FK id property and using that to modify the target entity, but that would take away the point of such EF feature

**Comment by FlyingWraptor** [comment] 2019-12-07 18:43
@ajcvickers is there any other solution to bypass this for now? This can't really wait till 5.0

**Comment by ajcvickers** [comment] 2019-12-09 17:58
@FlyingWraptor Yes; mark the FK property as not-modified. Anything done to the navigation property is really just sugar for acting on the FK property anyway.

**Closed** 2020-06-15 15:08 UTC
Labels: area-change-tracking, closed-fixed, customer-reported, type-bug
