### ISSUE TITLE
ef migrations add always scaffolds Drop-/AddForeignKey for every FK

### ISSUE THREAD

**Issue by Schlurcher** [dotnet/efcore#3761] opened 2015-11-16 12:07 UTC
When scaffolding a new migration with `dnx ef migration add` I lately end up with a Drop-/AddForeignKey for every FK in my schema. Everytime. Even if I just add migrations back to back without model changes inbetween. 

I don't know if this has anything to do with the fact that I renamed ApplicationUser to AppUser and explicitely added an AppRole. It seems to coincide with the first time this happened in a migration.

Here's the related part of my model:

``` csharp
public class DataContext : IdentityDbContext<AppUser, AppRole, string>
{
    public DbSet<Video> Videos { get; set; }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        builder.Entity<Video>(b =>
        {
            b.HasIndex(v => v.Slug).IsUnique();
        });

        builder.Entity<AppUser>(b =>
        {
            b.HasIndex(r => r.UserName).IsUnique();
            b.HasIndex(r => r.Email).IsUnique();
        });

        builder.Entity<AppRole>(b =>
        {
            b.HasIndex(r => r.Name).IsUnique();
        });
    }
}

public class AppUser : IdentityUser
{
    [Required]
    [Display(Name = "Benutzername")]
    public override string UserName { get; set; }

    [Required]
    [EmailAddress]
    [Display(Name = "E-Mail")]
    public override string Email { get; set; }

    [NotMapped]
    public ICollection<Character> Characters { get; set; }

    [NotMapped]
    public Character PrimaryCharacter { get; set; }
}

public class AppRole : IdentityRole
{
    [Required]
    public override string Name { get; set; }
}
```

**Comment by Schlurcher** [comment] 2015-11-16 13:49
After thinking about and playing around with this some more, maybe this is related to #3545 somehow?

**Comment by Schlurcher** [comment] 2015-11-16 16:51
Spent more time looking at the migrations and I think it's related to .OnDelete(DeleteBehavior.Cascade).

Unless ```.OnDelete(DeleteBehavior.Restrict)``` is specified, Up() is scaffolded as ```ReferentialAction.Cascade``` and Down() as ```.Restrict``` even if the FK was ON DELETE CASCADE.

**Comment by smitpatel** [comment] 2015-11-16 17:35
dupe of #3751

**Closed** 2022-10-16 09:16 UTC
