### ISSUE TITLE
Why does EF Core try to create objects that are not present in the class?

### ISSUE THREAD

**Issue by carumsoft** [dotnet/efcore#30636] opened 2023-04-05 15:50 UTC
My classes:
```C#
public abstract class UserBase : Entity
{
    public string Name { get; set; }
}

public class UserA : UserBase
{
    public UserSymbol UserSymbol { get; set; }
}

public class UserB : UserBase
{

}

public record UserSymbol
    {
        public string Text { get; init; }
        public UserSymbol(string text)
        {
            if (text is null)
            {
                throw new ArgumentNullException(nameof(text));
            }

            Text = text;
        }
    }
```

My data in sqlLite database:
id | Name | Discriminator | UserSymbol_Text
1 | user b | UserB | null

Execution:
```C#
var list = ERPContext.UserBases.ToList();
```

THE PROBLEM:
![obraz](https://user-images.githubusercontent.com/103263820/230134684-8cb9d828-ec2b-4d0f-a54f-a079b53f5d14.png)

Why EF is creating UserSymbol object for UserB object? There is no UserSymbol in UserB  class.

**Comment by ajcvickers** [comment] 2023-04-06 11:52
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ChrisJollyAU** [comment] 2023-04-13 16:54
@ajcvickers This looks like an inheritance question.

- A base entity with just 1 property (Name)
- 2 derived types with with only `UserA` containing an extra property `UserSymbol`
- The database has 1 row of type `UserB`

Given that the query is for the base type (`UserBase`) and that there is only `UserB` in the database, why would it be trying to create and map the `UserSymbol` property (which would imply it is trying to create a `UserA` object?

**Comment by ajcvickers** [comment] 2023-04-19 19:13
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-04-19 19:13 UTC
Labels: customer-reported
