### ISSUE TITLE
Tools ignore $(BaseIntermediateOutputPath)

### ISSUE THREAD

**Issue by oakio** [dotnet/efcore#18060] opened 2019-09-26 09:22 UTC
Tools ignore custom `$(BaseIntermediateOutputPath)`

### Steps to reproduce
1. Create a project
2. Open <project_name>.csproj and change `$(BaseIntermediateOutputPath)`
3. Run `dotnet ef` command
4. Expected that file `<project_name>.csproj.EntityFrameworkCore.targets` was created inside `$(BaseIntermediateOutputPath)`, but was `<project_root>/obj`

See `buildExtensionsDir` variable inside `class Microsoft.EntityFrameworkCore.Tools.Project`:
```C#
if (buildExtensionsDir == null)
{
    buildExtensionsDir = Path.Combine(Path.GetDirectoryName(file), "obj");
}

Directory.CreateDirectory(buildExtensionsDir);

var efTargetsPath = Path.Combine(
    buildExtensionsDir,
    Path.GetFileName(file) + ".EntityFrameworkCore.targets");
using (var input = typeof(Resources).GetTypeInfo().Assembly.GetManifestResourceStream(
    "Microsoft.EntityFrameworkCore.Tools.Resources.EntityFrameworkCore.targets"))
using (var output = File.OpenWrite(efTargetsPath))
{
    // NB: Copy always in case it changes
    Reporter.WriteVerbose(Resources.WritingFile(efTargetsPath));
    input.CopyTo(output);
}
```
[Related issue](https://github.com/aspnet/EntityFrameworkCore/issues/7685)

### Further technical details

EF Core version: 3.0.0
Target framework: .NET Core 3.0
Operating system: Windows 10 x64
IDE: Visual Studio 2019 16.3

**Comment by bricelam** [comment] 2019-09-26 21:42
Are you setting BaseIntermediateOutputPath correctly? You need to set it *before* the SDK files get injected.

```xml
<Project> <!-- DON'T PUT Sdk="Microsoft.NET.Sdk" HERE -->
  <PropertyGroup>
    <BaseIntermediateOutputPath>myobj\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <!-- csproj contents here -->

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
```
``` sh
dotnet ef --msbuildprojectextensionspath myobj\
```

**Comment by oakio** [comment] 2019-09-27 07:13
>Are you setting BaseIntermediateOutputPath correctly

Yes.

>Option `--msbuildprojectextensionspath`

This looks like a workaround.

If tools require `Microsoft.EntityFrameworkCore.Design` nuget package, then maybe to distribute `<project_name>.csproj.EntityFrameworkCore.targets` via MSBuild .targets and .props files inside this nuget package?

**Comment by bricelam** [comment] 2019-09-27 21:50
We should look at this again in a future release to see if there's anything we can improve. We ran into a lot of problems trying to reference MSBuild to evaluate the project properties. If I remember correctly the two major problems were, 1) we'd have to ship the MSBuild binaries with our tool, and 2) that version might get out of sync with the version in the SDK.

**Comment by bricelam** [comment] 2019-10-01 01:51
Those were just some design notes to consider when thinking about how we can make the experience better in a future EF Core release. Ideally, you shouldn’t have to specify —msbuildprojectextensionspath

**Comment by ajcvickers** [comment] 2019-11-20 19:57
Duplicate of #18840

**Closed** 2022-10-16 14:45 UTC
Labels: customer-reported
