### ISSUE TITLE
Open DataReader edge case

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#11627] opened 2018-04-11 09:50 UTC
This is a bit of an edge case, but I simplified it down, and it's repeatable. 
EF Core version 2.1.0-preview1-final
```
	using (var db = new MyDbContext())
	using (var tx = db.Database.BeginTransaction())
	{
		var q1 = db.Things
				   .Join(db.OtherThings, x => x.ThingId, y => y.ThingId,
					   (x, y) => y.Name);
		var q2 = db.SomeThings.Where(s => s.SomeCondition).Select(s => s.Name);
		var result = q1.Union(q2).ToList();
		Console.WriteLine(result);
		tx.Commit();
	}
```
The `Commit()` throws an exception:
```
System.InvalidOperationException : There is already an open DataReader associated with this Command which must be closed first.
   at System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
   at System.Data.SqlClient.SqlInternalTransaction.Rollback()
   at System.Data.SqlClient.SqlTransaction.Dispose(Boolean disposing)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Dispose()
```

**Comment by smitpatel** [comment] 2018-04-11 19:39
I tried following test in Northwind fixture
```C#
[Fact]
public virtual void Test()
{
    using (var context = CreateContext())
    {
        using (var tx = context.Database.BeginTransaction())
        {
            var query1 = context.Customers
                .Join(context.Orders, x => x.CustomerID, y => y.CustomerID,
                (x, y) => y.OrderID);
            var query2 = context.Orders.Where(o => o.OrderID < 10500).Select(o => o.OrderID);
            var result = query1.Union(query2).ToList();
            Console.WriteLine(result);
            tx.Commit();
        }

    }
}
```
It passed successfully. (with MARS=true/false both cases)
Can you post a self-contained repro which throws exception?

**Comment by ajcvickers** [comment] 2018-04-18 16:27
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:18 UTC
Labels: closed-could-not-reproduce
