### ISSUE TITLE
MaxLength property with adding more than one record on SaveChanges()

### ISSUE THREAD

**Issue by ice1e0** [dotnet/efcore#12218] opened 2018-06-03 14:30 UTC
I've created a data entity with several string members. To define the length of the string fields in the database I've added the attribute `MaxLength` to the fields.

I use it in an WPF application by binding `CollectionViewSource.GetDefaultView(dbSet.Local.ToObservableCollection())` to the datagrid.

To save the changes to the database I use an extra button which executes `DbContext.SaveChanges();`.

When I add one row to the data grid and save the changes, it works. But when I add two rows and call save changes, an exception is thrown at `DbContext.SaveChanges();`, see below.

When I try to add the same records without using the `MaxLength` attribute (the database has already been created with the MaxLength attribute active), I am able to save the records to the database. So it looks like that there is something wrong with `MaxLength`.

```
Expcetion type: Microsoft.EntityFrameworkCore.DbUpdateException
Exception message: An error occurred while updating the entries. See the inner exception for details.

Stack trace:
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at *****.ViewModelBase.DataContextViewModel`1.Save(Object obj) in C:\git\*****\ViewModelBase\Data\DataContextViewModel.cs:line 33
   at *****.ViewModelBase.RelayCommand.Execute(Object parameter) in C:\git\*****\ViewModelBase\Command\RelayCommand.cs:line 57
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
```

Inner Exception:
```
Exception type: System.Data.SqlClient.SqlException
Exception message: String or binary data would be truncated.
The statement has been terminated.

Stack trace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

### Further technical details
EF Core version: 2.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 8.1 Pro
IDE: Visual Studio 2017 15.6.6
.NET Framework: 4.6.1

**Comment by ajcvickers** [comment] 2018-06-04 23:16
@ice1e0 I have not been able to reproduce the behavior you are seeing. Could you post a runnable project/solution or complete code listing that demonstrates the issue?

**Comment by ajcvickers** [comment] 2018-06-11 18:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ice1e0** [comment] 2018-06-14 00:43
Sorry for the late response.

I've created now an app which you can use to reproduce the error: [WpfApp1.zip](https://github.com/aspnet/EntityFrameworkCore/files/2100405/WpfApp1.zip)

Steps to reproduce:
---------------------
1. open with visual studio
2. open Package-Manager-Konsole and type in `Update-Package -reinstall`
3. create an empty database in your database (e.g. `TestDatabase`)
4. go to file `DatabaseContext.cs` and update the connection string fitting to your environment.
5. complile and start the software
6. click button `Create new row`, edit the row and then click `Save`. That works.
7. now do the same but create two rows and after you've created the two rows, click on `Save`. You will get the error described above.

Side note:
---------------
* the primary key `Number` is filled automatically with an GUID. That is not the plan. I have now clue why this happens.
* the idea is that the primary key is filled out by the user, not by the database. With other words: I want to use a natural key, not a surrogate key. See also blog article [When (And How) to Use Surrogate Keys
](https://www.sisense.com/blog/when-and-how-to-use-surrogate-keys/).

**Comment by ajcvickers** [comment] 2018-06-14 19:55
@ice1e0 I can only get the exception when the value in one of the properties is longer than the max-length specified. This seems consistent no matter how many rows are added at the same time.

The reason for the GUID is that EF needs a primary key value in order to track the added entity, and since none was provided EF will create a GUID instead. If you set the key value to something else before calling Add, then EF will use whatever you set. For example, you could set, "New Item 1", "New Item 2", and so on. For example:
```C#
private int _newItemNumber = 1;

private void NewRow_Click(object sender, RoutedEventArgs e)
{
    DataEntity newRow = new DataEntity { Number = "New Item " + _newItemNumber++ };
    _collection.Add(newRow);

    this.DataGrid1.CurrentItem = newRow;
}
```

**Comment by ajcvickers** [comment] 2018-06-15 21:02
See also #12378

**Comment by ajcvickers** [comment] 2018-06-25 17:48
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ice1e0** [comment] 2018-07-21 20:46
Just want to send a note to proper close this issue: I was not able to reproduce the error so no more investigation needed.
#12378 looks good tho, hope we can get this in the next minor version :-)

**Closed** 2022-10-16 12:28 UTC
Labels: closed-could-not-reproduce, customer-reported
