### ISSUE TITLE
Compiled model: The binary operator Equal is not defined for the types 'System.Int32' and 'System.Nullable`1[System.Int32]'

### ISSUE THREAD

**Issue by ronymeyer** [dotnet/efcore#28676] opened 2022-08-11 14:19 UTC
We have an issue with compiled models that lots of calls error with "The binary operator Equal is not defined for the types 'System.Int32' and 'System.Nullable`1[System.Int32]'".

Example:
`An unhandled exception occurred while processing the request.
InvalidOperationException: The binary operator Equal is not defined for the types 'System.Int32' and 'System.Nullable`1[System.Int32]'.
System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, string opName, Expression left, Expression right, bool liftToNull)

TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeMethodHandle.InvokeMethod(object target, ref Span<object> arguments, Signature sig, bool constructor, bool wrapExceptions)

TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeMethodHandle.InvokeMethod(object target, ref Span<object> arguments, Signature sig, bool constructor, bool wrapExceptions)

Stack Query Cookies Headers Routing
InvalidOperationException: The binary operator Equal is not defined for the types 'System.Int32' and 'System.Nullable`1[System.Int32]'.
System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, string opName, Expression left, Expression right, bool liftToNull)
System.Linq.Expressions.Expression.Equal(Expression left, Expression right, bool liftToNull, MethodInfo method)
Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyAccessorsFactory.CreateCurrentValueGetter<TProperty>(IPropertyBase propertyBase, bool useStoreGeneratedValues)
Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyAccessorsFactory.CreateGeneric<TProperty>(IPropertyBase propertyBase)

Show raw exception details
TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeMethodHandle.InvokeMethod(object target, ref Span<object> arguments, Signature sig, bool constructor, bool wrapExceptions)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyAccessorsFactory.Create(IPropertyBase propertyBase)
Microsoft.EntityFrameworkCore.Metadata.RuntimePropertyBase.Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimePropertyBase.get_Accessors()
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.DependentKeyValueFactoryFactory.CreateSimple<TKey>(IForeignKey foreignKey)
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.KeyValueFactoryFactory.CreateSimpleFactory<TKey>(IKey key)
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.KeyValueFactoryFactory.Create<TKey>(IKey key)
Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized<TParam, TValue>(ref TValue target, TParam param, Func<TParam, TValue> valueFactory)
Microsoft.EntityFrameworkCore.Metadata.RuntimeKey.Microsoft.EntityFrameworkCore.Metadata.IKey.GetPrincipalKeyValueFactory<TKey>()
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMapFactoryFactory.CreateFactory<TKey>(IKey key)

Show raw exception details
TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeMethodHandle.InvokeMethod(object target, ref Span<object> arguments, Signature sig, bool constructor, bool wrapExceptions)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMapFactoryFactory.Create(IKey key)
Microsoft.EntityFrameworkCore.Metadata.RuntimeKey.Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimeKey.GetIdentityMapFactory()
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateIdentityMap(IKey key)
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.TryGetEntry(IKey key, object[] keyValues, bool throwOnNullKey, out bool hasNullKey)
lambda_method520(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable<T>+AsyncEnumerator.MoveNextAsync()
Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken)
CompanyName.MVC.ViewComponents.MenuViewComponent.InvokeAsync() in MenuViewComponent.cs
+
                var menuItems = await context.MenuItems.Where(m => m.ParentId == null && m.ClosedOn >= DateTime.UtcNow).ToListAsync();`

MenuItem entity:
`// EF auto generated file.
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
using Microsoft.EntityFrameworkCore;

namespace CompanyName.Entity.Metadata
{
    [Table("MenuItem")]
    public class MenuItem : BaseEntity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [AdditionalMetadata("EntityPropertyId", 3545)]
        [Display(Name = "MenuItemId")]
        public virtual Int32 MenuItemId { get; set; }

        [Required]
        [AdditionalMetadata("EntityPropertyId", 3546)]
        [MaxLength(256)]
        [Display(Name = "Prompt",Description="The text that will be used to pick the item in the menu.")]
        public virtual String Prompt { get; set; }

        [AdditionalMetadata("EntityPropertyId", 3547)]
        [MaxLength(450)]
        [Display(Name = "Description")]
        public virtual String Description { get; set; }

        [AdditionalMetadata("EntityPropertyId", 3548)]
        [Display(Name = "Parent",Description="The parent item in the menu.")]
        public virtual Int32? ParentId { get; set; }

        [AdditionalMetadata("EntityPropertyId", 3549)]
        [Display(Name = "Item",Description="The item that should be displayed on the Entity.")]
        public virtual String ItemId { get; set; }

        [AdditionalMetadata("EntityPropertyId", 3550)]
        [MaxLength(450)]
        [Display(Name = "Entity",Description="The entity on which the item is associated with. ")]
        public virtual String EntityId { get; set; }

        [AdditionalMetadata("EntityPropertyId", 3559)]
        [Display(Name = "Sequence")]
        public virtual Int32 Sequence { get; set; }

        public MenuItem()
        {
            Prompt = String.Empty;
            Description = null;
            ParentId = null;
            ItemId = null;
            EntityId = null;
            Sequence = 0;
        }

        // Foreign Keys
        //[AssociationId(315)]
        [IgnoreDataMember]
        [ForeignKey("EntityId")]
        public virtual FinanceKey.Entity.Metadata.Entity Entity { get; set; }
        //[AssociationId(317)]
        [IgnoreDataMember]
        [ForeignKey("ParentId")]
        public virtual MenuItem Parent { get; set; }

        // Collections
        //[AssociationId(318)]
        [IgnoreDataMember]
        [InverseProperty("Parent")]
        public virtual ICollection<MenuItem> MenuItems { get; set; }

        // Not mapped properties
        [NotMapped]
        public override object KeyValue { get { return MenuItemId; } }
        [ScaffoldColumn(false)]
        [NotMapped]
        public override string KeyName { get { return "MenuItemId"; } }
    }
}
`

Base entity:
`using CompanyName.Entity.Core;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace CompanyName.Entity
{
    public abstract class BaseEntity
    {
        [ScaffoldColumn(false)]
        public virtual int? CreatedById { get; set; }
        [ScaffoldColumn(false)]
        public virtual DateTime CreatedOn { get; set; }
        [ScaffoldColumn(false)]
        public virtual int? UpdatedById { get; set; }
        [ScaffoldColumn(false)]
        public virtual DateTime UpdateOn { get; set; }
        [ScaffoldColumn(false)]
        public virtual int? ClosedById { get; set; }
        [ScaffoldColumn(false)]
        public virtual DateTime ClosedOn { get; set; }
        [ScaffoldColumn(false)]
        [NotMapped]
        public bool Active => ClosedOn > DateTime.UtcNow;
        [ScaffoldColumn(false)]
        [Timestamp]
        public virtual byte[] RowVersion { get; set; }
        [ScaffoldColumn(false)]
        public virtual string SessionId { get; set; }

        //FK
        [ForeignKey("CreatedById")]
        [IgnoreDataMember]
        public virtual SystemAccount CreatedBy { get; set; }
        [ForeignKey("UpdatedById")]
        [IgnoreDataMember]
        public virtual SystemAccount UpdatedBy { get; set; }
        [ForeignKey("ClosedById")]
        [IgnoreDataMember]
        public virtual SystemAccount ClosedBy { get; set; }

        /// <summary>
        /// overwritten in entity
        /// </summary>
        [NotMapped]
        public abstract object KeyValue { get; }

        /// <summary>
        /// overwritten in entity
        /// </summary>
        [NotMapped]
        public abstract string KeyName { get; }

        protected BaseEntity()
        {
            CreatedOn = DateTime.UtcNow;
            CreatedById = User.Id;
            UpdatedById = CreatedById;
            ClosedById = UpdatedById;
            UpdateOn = DateTime.UtcNow;
            ClosedOn = DateTime.MaxValue;
            SessionId = User.SessionId;
        }
    }
}
`

Compile model of MenuItem:
`// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using FinanceKey.Entity.Core;
using FinanceKey.Entity.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Proxies.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace FinanceKey.Entity.Models
{
    internal partial class MenuItemEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "FinanceKey.Entity.Metadata.MenuItem",
                typeof(MenuItem),
                baseEntityType,
                changeTrackingStrategy: ChangeTrackingStrategy.ChangingAndChangedNotifications);

            var menuItemId = runtimeEntityType.AddProperty(
                "MenuItemId",
                typeof(int),
                propertyInfo: typeof(MenuItem).GetProperty("MenuItemId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MenuItem).GetField("<MenuItemId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw);
            menuItemId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var closedById = runtimeEntityType.AddProperty(
                "ClosedById",
                typeof(int?),
                propertyInfo: typeof(BaseEntity).GetProperty("ClosedById", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<ClosedById>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            closedById.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var closedOn = runtimeEntityType.AddProperty(
                "ClosedOn",
                typeof(DateTime),
                propertyInfo: typeof(BaseEntity).GetProperty("ClosedOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<ClosedOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            closedOn.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var createdById = runtimeEntityType.AddProperty(
                "CreatedById",
                typeof(int?),
                propertyInfo: typeof(BaseEntity).GetProperty("CreatedById", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<CreatedById>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            createdById.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var createdOn = runtimeEntityType.AddProperty(
                "CreatedOn",
                typeof(DateTime),
                propertyInfo: typeof(BaseEntity).GetProperty("CreatedOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<CreatedOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            createdOn.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(MenuItem).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MenuItem).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 450);
            description.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var entityId = runtimeEntityType.AddProperty(
                "EntityId",
                typeof(string),
                propertyInfo: typeof(MenuItem).GetProperty("EntityId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MenuItem).GetField("<EntityId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 450);
            entityId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var itemId = runtimeEntityType.AddProperty(
                "ItemId",
                typeof(string),
                propertyInfo: typeof(MenuItem).GetProperty("ItemId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MenuItem).GetField("<ItemId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            itemId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var parentId = runtimeEntityType.AddProperty(
                "ParentId",
                typeof(int?),
                propertyInfo: typeof(MenuItem).GetProperty("ParentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MenuItem).GetField("<ParentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            parentId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var prompt = runtimeEntityType.AddProperty(
                "Prompt",
                typeof(string),
                propertyInfo: typeof(MenuItem).GetProperty("Prompt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MenuItem).GetField("<Prompt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 256);
            prompt.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var rowVersion = runtimeEntityType.AddProperty(
                "RowVersion",
                typeof(byte[]),
                propertyInfo: typeof(BaseEntity).GetProperty("RowVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<RowVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                concurrencyToken: true,
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore);
            rowVersion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sequence = runtimeEntityType.AddProperty(
                "Sequence",
                typeof(int),
                propertyInfo: typeof(MenuItem).GetProperty("Sequence", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MenuItem).GetField("<Sequence>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            sequence.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sessionId = runtimeEntityType.AddProperty(
                "SessionId",
                typeof(string),
                propertyInfo: typeof(BaseEntity).GetProperty("SessionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<SessionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            sessionId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var updateOn = runtimeEntityType.AddProperty(
                "UpdateOn",
                typeof(DateTime),
                propertyInfo: typeof(BaseEntity).GetProperty("UpdateOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<UpdateOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            updateOn.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var updatedById = runtimeEntityType.AddProperty(
                "UpdatedById",
                typeof(int?),
                propertyInfo: typeof(BaseEntity).GetProperty("UpdatedById", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<UpdatedById>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            updatedById.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var lazyLoader = runtimeEntityType.AddServiceProperty(
                "LazyLoader",
                propertyInfo: typeof(IProxyLazyLoader).GetProperty("LazyLoader", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var key = runtimeEntityType.AddKey(
                new[] { menuItemId });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { closedById });

            var index0 = runtimeEntityType.AddIndex(
                new[] { createdById });

            var index1 = runtimeEntityType.AddIndex(
                new[] { entityId });

            var index2 = runtimeEntityType.AddIndex(
                new[] { parentId });

            var index3 = runtimeEntityType.AddIndex(
                new[] { updatedById });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ClosedById") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("SystemAccountId") }),
                principalEntityType);

            var closedBy = declaringEntityType.AddNavigation("ClosedBy",
                runtimeForeignKey,
                onDependent: true,
                typeof(SystemAccount),
                propertyInfo: typeof(BaseEntity).GetProperty("ClosedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<ClosedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                propertyAccessMode: PropertyAccessMode.Field);

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("CreatedById") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("SystemAccountId") }),
                principalEntityType);

            var createdBy = declaringEntityType.AddNavigation("CreatedBy",
                runtimeForeignKey,
                onDependent: true,
                typeof(SystemAccount),
                propertyInfo: typeof(BaseEntity).GetProperty("CreatedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<CreatedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                propertyAccessMode: PropertyAccessMode.Field);

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("EntityId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("EntityId") }),
                principalEntityType);

            var entity = declaringEntityType.AddNavigation("Entity",
                runtimeForeignKey,
                onDependent: true,
                typeof(FinanceKey.Entity.Metadata.Entity),
                propertyInfo: typeof(MenuItem).GetProperty("Entity", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MenuItem).GetField("<Entity>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                propertyAccessMode: PropertyAccessMode.Field);

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey4(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ParentId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("MenuItemId") }),
                principalEntityType);

            var parent = declaringEntityType.AddNavigation("Parent",
                runtimeForeignKey,
                onDependent: true,
                typeof(MenuItem),
                propertyInfo: typeof(MenuItem).GetProperty("Parent", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MenuItem).GetField("<Parent>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                propertyAccessMode: PropertyAccessMode.Field);

            var menuItems = principalEntityType.AddNavigation("MenuItems",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<MenuItem>),
                propertyInfo: typeof(MenuItem).GetProperty("MenuItems", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MenuItem).GetField("<MenuItems>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                propertyAccessMode: PropertyAccessMode.Field);

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey5(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UpdatedById") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("SystemAccountId") }),
                principalEntityType);

            var updatedBy = declaringEntityType.AddNavigation("UpdatedBy",
                runtimeForeignKey,
                onDependent: true,
                typeof(SystemAccount),
                propertyInfo: typeof(BaseEntity).GetProperty("UpdatedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<UpdatedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                propertyAccessMode: PropertyAccessMode.Field);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "MenuItem");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
`

Furthermore we validated the whole model that there are no miss matches between the entity files and the databases (all int and int? columns match).

Is there a better way to actually see which column is causing this issue?

**Comment by ajcvickers** [comment] 2022-08-11 14:31
Duplicate of #28108

**Closed** 2022-08-11 14:59 UTC
Labels: customer-reported
