### ISSUE TITLE
Tests SQLite in memory throw exception SQLite Error 1: 'near ":" : syntax using "DataSource=:memory:"

### ISSUE THREAD

**Issue by angelicaflausino** [dotnet/efcore#16885] opened 2019-08-01 12:05 UTC
I followed the examples of SQLite implementation for in-memory testing, but when executing the line **context.Database.EnsureCreated();** the exception is thrown

> SQLite Error 1: 'near ":" : syntax using "DataSource=:memory:"

### Steps to reproduce
I followed exactly the same steps of this example: [https://www.meziantou.net/testing-ef-core-in-memory-using-sqlite.htm](url)

```c#
public SampleDbContext CreateContext()
    {
        if (_connection == null)
        {
            _connection = new SqliteConnection("DataSource=:memory:");
            _connection.Open();

            var options = CreateOptions();
            using (var context = new SampleDbContext(options))
            {
                context.Database.EnsureCreated();
            }
        }

        return new SampleDbContext(CreateOptions());
    }
```

Can someone help me? Thanks

### Further technical details
EF Core version: 2.2.0
Database Provider: (e.g. Microsoft.EntityFrameworkCore.Sqlite 2.2.2)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.9.14)

**Comment by ajcvickers** [comment] 2019-08-01 16:00
@angelicaflausino If there is something wrong with that blog post, then it's probably a good idea to follow up with the author. If you think there is an issue with EF, then please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-08-09 16:16
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:33 UTC
Labels: closed-could-not-reproduce, customer-reported
