### ISSUE TITLE
Invalid column enum name on update database

### ISSUE THREAD

**Issue by gnilsson** [dotnet/efcore#28050] opened 2022-05-18 18:12 UTC
The problem discussed at issue #21037 still exists under a specific and unusual condition.

Consider this code where the enum is converted with an implicit operator to a complex type that is stored via a value converter.

```C#
    public static void Seed(ModelBuilder modelBuilder)
    {
        var carCategorys = new CarCategory[]
        {
            new CarCategory
            {
                Name = (Name)"Småbil",
                PricingModel = (PricingModel)EPricingModel.Low,
                Id = Identifier.New(),
            },
            new CarCategory
            {
                Name = (Name)"Kombi",
                PricingModel = (PricingModel)EPricingModel.Mid,
                Id = Identifier.New(),
            },
            new CarCategory
            {
                Name = (Name)"Lastbil",
                PricingModel = (PricingModel)EPricingModel.High,
                Id = Identifier.New(),
            }
        };

        modelBuilder.Entity<CarCategory>().HasData(carCategorys);
    }
```

Exposing this problem during seed:

```
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Name', N'PricingModel') AND [object_id] = OBJECT_ID(N'[CarCategorys]'))
          SET IDENTITY_INSERT [CarCategorys] ON;
      INSERT INTO [CarCategorys] ([Id], [Name], [PricingModel])
      VALUES ('04e0e9cf-d9e6-4ad8-a980-504e3a81b06d', N'Småbil', None);
      IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Name', N'PricingModel') AND [object_id] = OBJECT_ID(N'[CarCategorys]'))
          SET IDENTITY_INSERT [CarCategorys] OFF;
Failed executing DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Name', N'PricingModel') AND [object_id] = OBJECT_ID(N'[CarCategorys]'))
    SET IDENTITY_INSERT [CarCategorys] ON;
INSERT INTO [CarCategorys] ([Id], [Name], [PricingModel])
VALUES ('04e0e9cf-d9e6-4ad8-a980-504e3a81b06d', N'Småbil', None);
IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Name', N'PricingModel') AND [object_id] = OBJECT_ID(N'[CarCategorys]'))
    SET IDENTITY_INSERT [CarCategorys] OFF;
...
Error Number:207,State:1,Class:16
Invalid column name 'None'.
```

'None' being the 0 value of the enum.

My workaround was to  remove the property from seed and allow it to be null.

EF Core version: 6.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Framework: net6.0
VS: 2022 17.1.6

**Comment by AndriySvyryd** [comment] 2022-05-21 01:54
We believe this was fixed by 0dc7cadca422f684470bfc3113564b6131dddf4a in 7.0.0-preview5. Please try it when it becomes available or use a [daily build](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md)
If the issue persist please provide all referenced types.

**Comment by gnilsson** [comment] 2022-05-21 10:27
Alright of course, thank you will check it.

**Comment by ajcvickers** [comment] 2022-05-31 10:37
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:34 UTC
Labels: customer-reported
