### ISSUE TITLE
Getting Entity names into a list for DDL

### ISSUE THREAD

**Issue by nexawo** [dotnet/efcore#18671] opened 2019-10-31 04:32 UTC
I am working on a project using EFCore with CodeFirstapproach and I am stuck in an issue which is to get all entities or table names into a list and show them in a view as a DropDown List.

**Comment by ajcvickers** [comment] 2019-11-01 15:21
@nexawo This question is too vague. For example, at what point do you want to get all entities? From the built model?

**Comment by ajcvickers** [comment] 2019-11-08 16:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:53 UTC
Labels: closed-could-not-reproduce, customer-reported
