### ISSUE TITLE
After running the Cli the many to many tables are missing.

### ISSUE THREAD

**Issue by jayson-centeno** [dotnet/efcore#30050] opened 2023-01-13 10:08 UTC
![image](https://user-images.githubusercontent.com/5885994/212293678-cb6e8a60-cc5f-444a-9505-843e6482834e.png)

![image](https://user-images.githubusercontent.com/5885994/212294014-55cb8415-0a44-4096-8d31-5f059cb27f68.png)

Please help. Just migrated my code to EFCore 7

**Comment by roji** [comment] 2023-01-13 11:43
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-01-13 11:50
@jayson-centeno You don't say which version you are updating from, but it could be this breaking change: [Many-to-many relationships without mapped join entities are now scaffolded](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes#many-to-many).

**Comment by ajcvickers** [comment] 2023-01-24 17:32
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-01-24 17:32 UTC
Labels: customer-reported
