### ISSUE TITLE
EFCore.SqlServer.FunctionalTest hanging on Linux VM (Ubuntu 16.04 LTS and 18.10)

### ISSUE THREAD

**Issue by Gary-Zh** [dotnet/efcore#15333] opened 2019-04-11 21:58 UTC
When I was running EFCore.SqlServer.FunctionalTest on Linux VM, the test hangs frequently.
The test runs but does not finish. dotnet process looks hanging as well, it consumes 0 CPU usage but does not terminate.
When it doesn't hang, the test finishes within 10 mins on my VM, but it could hang hours and I had to manually terminate the test execution.

Here's what I did:
Create a completely clean Ubuntu VM (I've tried version 18.10 and 16.04).
Install git and clone EFCore repo.
Go to EFCore root folder and run `./build.sh -c Release -v d`

`export Test__SqlServer__DefaultConnection="Data Source=192.xxx.xxx.xxx;DataBase=master;UID={id};PWD={pwd};Connect Timeout=60;ConnectRetryCount=0;"` (in order not to skip tests)

`./test.sh -projects /test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj -configuration Release -v d`

Sometimes the test finishes successfully and gives me the test result file. Sometimes it just hangs.
Here's the log file being generated when it hangs:
[EFCore.SqlServer.FunctionalTests_netcoreapp3.0_x64.log](https://github.com/aspnet/EntityFrameworkCore/files/3070752/EFCore.SqlServer.FunctionalTests_netcoreapp3.0_x64.log)

The screenshot shows the dotnet process is hanging:
![EFCore_Test](https://user-images.githubusercontent.com/45860872/55995536-986b4880-5c69-11e9-9a36-cc658b13c84b.PNG)

### Further technical details
EF Core version: latest in master branch
Operating system: Ubuntu 16.04 LTS and 18.0.

**Comment by Gary-Zh** [comment] 2019-04-11 21:58
It does not hang on Windows

**Comment by ajcvickers** [comment] 2019-04-15 16:06
@Gary-Zh How many logical CPUs are you using when you run the tests on Linux?

**Comment by Gary-Zh** [comment] 2019-04-15 17:17
@ajcvickers  I have 3 logical CPUs on my VM.
![image](https://user-images.githubusercontent.com/45860872/56152071-96560200-5f67-11e9-9786-58755d5de712.png)

**Comment by ajcvickers** [comment] 2019-04-22 17:06
@roji to try running locally on Linux.

**Comment by roji** [comment] 2019-04-29 11:31
Tested locally - everything seems OK, no deadlocks...

(ran tests on daeb665356dc48ff4ff34976e92f33d03228811c, on Ubuntu 19.04, against SQL Server running locally, 6 physical cores).

**Comment by smitpatel** [comment] 2019-04-29 16:35
>It does not hang on Windows

@Gary-Zh - How many logical CPUs on your windows machine? The current implementation on query translation and concurrent running on tests can cause deadlock on machines with low number of cores regardless of OS.

**Comment by Gary-Zh** [comment] 2019-04-29 17:33
@smitpatel I have 8 logical CPUs on my windows machine. 
![image](https://user-images.githubusercontent.com/45860872/56914895-1ef59780-6a6a-11e9-933d-a5ad42f517f2.png)

Do you suggest me to add more cores to the VM and try reproducing the issue again?

**Comment by divega** [comment] 2019-04-29 17:37
@Gary-Zh yes, that is something we believe is worth trying.

**Comment by ajcvickers** [comment] 2019-05-06 18:44
Closing this as we have been able to run on Linux without issues, and until the known deadlock issues in query are fixed there is nothing more to try here for now.

**Comment by Gary-Zh** [comment] 2019-05-22 23:40
Hi @divega , it's been a while since we last time running EFCore tests.
So I've tried to increase the core number to 6 this time, same thing happens, please see the pictures below:
![EFCore_Test1](https://user-images.githubusercontent.com/45860872/58215738-34985e80-7cb0-11e9-9ec6-8c0616b864c1.PNG)
![EFCore_Test2](https://user-images.githubusercontent.com/45860872/58215739-34985e80-7cb0-11e9-98c6-fa7f24fd4ddb.PNG)

It still hangs on my Linux VM.

**Comment by Gary-Zh** [comment] 2019-05-22 23:40
Can we re-open this issue and investigate more?

**Comment by roji** [comment] 2019-05-23 10:40
@Gary-Zh the problem is that this occurs neither in our continuous builds (which run all the time), nor on my personal build machine. So whatever issue you're running into seems to be somehow tied to your specific environment...

Any chance you could try on a physical Linux box (non-VM) and report?

**Comment by divega** [comment] 2019-05-28 22:28
@roji would it possible to break into the running tests with a debugger to figure out where the execution is at then the tests stall?

**Comment by roji** [comment] 2019-05-28 23:20
Sure, but I haven't actually seen the tests stall on my Linux machine at any point... I just ran the SqlServer functional test suite, once on 2.2.5 and once on master and everything was fine.

@Gary-Zh have you had a chance to try on a physical Linux box, ideally against the same SQL Server instance?

**Closed** 2022-10-16 14:17 UTC
Labels: closed-could-not-reproduce, customer-reported
