### ISSUE TITLE
Exception while trying to load entities many-to-many related

### ISSUE THREAD

**Issue by CheloXL** [dotnet/efcore#12130] opened 2018-05-24 01:40 UTC
I'm trying to project an entity and its relations to a dto. The query is the following:
```cs
Context.Set<UsuarioDb>()
	.Include(x => x.GrupoDb)
	.Include(x => x.Usuario_PuntoVentaDbs)
	.ThenInclude(x => x.PuntoVenta)
	.Include(x => x.Usuario_DepositoDbs)
	.ThenInclude(x => x.Deposito)
	.Select(x => new UsuarioDetail
	{
		Id = x.Id,
		Activo = x.Activo,
		FechaHoraCreacion = x.FechaHoraCreacion,
		Login = x.Login,
		Name = x.Name,
		Grupo = x.GrupoDb,
		PuntosVenta = x.Usuario_PuntoVentaDbs.Select(p => p.PuntoVenta),
		Depositos = x.Usuario_DepositoDbs.Select(p => p.Deposito)
	})
	.FirstOrDefaultAsync(x => x.Id == id)
```
And I'm getting the following exception:
```
Exception message:
System.ArgumentException: Expression of type 'System.Collections.Generic.IAsyncEnumerable`1[Microsoft.EntityFrameworkCore.Storage.ValueBuffer]' cannot be used for parameter of type 'System.Collections.Generic.IAsyncEnumerable`1[DDS.Genesis.Infrastructure.EntityFramework.DbEntities.Configuracion.Organizacion.PuntoVentaDb]' of method 'EnumerableAdapter`1 _ToEnumerable[PuntoVentaDb](System.Collections.Generic.IAsyncEnumerable`1[DDS.Genesis.Infrastructure.EntityFramework.DbEntities.Configuracion.Organizacion.PuntoVentaDb])'

Stack trace:
at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ProjectionExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass24_0`1.<CompileAsyncQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at DDS.Genesis.Infrastructure.EntityFramework.Queries.Configuracion.Organizacion.UsuariosQueries.Cargar(String id) in D:\Code\2DS\Genesis\Sistema\Infrastructure.EntityFramework\Queries\Configuracion\Organizacion\UsuariosQueries.cs:line 36
```

### Steps to reproduce
```cs
public sealed class UsuarioDb
{
	public string Id { get; set; }
	public DateTime FechaHoraCreacion { get; set; }
	public string Name { get; set; }
	public bool Activo { get; set; }
	public string Email { get; set; }
	public string HashedPassword { get; set; }
	public string Login { get; set; }
	public ICollection<Usuario_PuntoVentaDb> Usuario_PuntoVentaDbs { get; set; }
	public ICollection<Usuario_DepositoDb> Usuario_DepositoDbs { get; set; }
	public GrupoDb GrupoDb { get; set; }
	public string GrupoDbId { get; set; }
}

internal sealed class UsuariosConfiguration : IEntityTypeConfiguration<UsuarioDb>
{
	/// <inheritdoc />
	public void Configure(EntityTypeBuilder<UsuarioDb> builder)
	{
		builder.ToTable("usuarios");
		builder.HasKey(x => x.Id);

		builder.Property(x => x.Login).HasMaxLength(32);
		builder.HasIndex(x => x.Login).IsUnique();

		builder.Property(x => x.Name).HasMaxLength(255);
		builder.Property(x => x.Email).HasMaxLength(255);
		builder.Property(x => x.HashedPassword).HasMaxLength(255);
		builder.HasOne(x => x.GrupoDb)
			.WithMany()
			.HasForeignKey(x => x.GrupoDbId);
	}
}

public sealed class Usuario_DepositoDb
{
	public UsuarioDb Usuario { get; set; }
	public string UsuarioId { get; set; }
	public DepositoDb Deposito { get; set; }
	public string DepositoId { get; set; }
}

internal sealed class Usuario_DepositoConfiguration : IEntityTypeConfiguration<Usuario_DepositoDb>
{
	/// <inheritdoc />
	public void Configure(EntityTypeBuilder<Usuario_DepositoDb> builder)
	{
		builder.ToTable("usuarios_depositos");
		builder.HasKey(bc => new {bc.UsuarioId, bc.DepositoId});

		builder.HasOne(bc => bc.Usuario)
			.WithMany(b => b.Usuario_DepositoDbs)
			.HasForeignKey(bc => bc.UsuarioId);

		builder.HasOne(bc => bc.Deposito)
			.WithMany(c => c.Usuario_DepositoDbs)
			.HasForeignKey(bc => bc.DepositoId);
	}
}

public sealed class Usuario_PuntoVentaDb
{
	public PuntoVentaDb PuntoVenta { get; set; }
	public string PuntoVentaId { get; set; }
	public UsuarioDb Usuario { get; set; }
	public string UsuarioId { get; set; }
}

internal sealed class Usuario_PuntoVentaConfiguration : IEntityTypeConfiguration<Usuario_PuntoVentaDb>
{
	/// <inheritdoc />
	public void Configure(EntityTypeBuilder<Usuario_PuntoVentaDb> builder)
	{
		builder.ToTable("usuarios_puntosventa");
		builder.HasKey(bc => new {bc.UsuarioId, bc.PuntoVentaId});

		builder.HasOne(bc => bc.Usuario)
			.WithMany(b => b.Usuario_PuntoVentaDbs)
			.HasForeignKey(bc => bc.UsuarioId);

		builder.HasOne(bc => bc.PuntoVenta)
			.WithMany(c => c.Usuario_PuntoVentaDbs)
			.HasForeignKey(bc => bc.PuntoVentaId);
	}
}

public sealed class PuntoVentaDb
{
	public string Id { get; set; }
	public string Name { get; set; }
	public ICollection<Usuario_PuntoVentaDb> Usuario_PuntoVentaDbs { get; set; }
}

public sealed class DepositoDb
{
	public string Id { get; set; }
	public string Name { get; set; }
	public ICollection<Usuario_DepositoDb> Usuario_DepositoDbs { get; set; }
}
```

If I add `.ToList()` to both selects at the end, the query works, but it issues 3 queries to the DB, one to get the Usuario, and another two, one for PuntoVenta and another for Deposito. I would like to do this in one single query to the DB.

### Further technical details
EF Core version: 2.0.3
Database Provider: Pomelo.EntityFrameworkCore.MySql
Operating system: Win10
IDE: (e.g. Visual Studio 2017 15.7)

**Comment by ajcvickers** [comment] 2018-05-25 19:40
@CheloXL A couple observations on this:
* It doesn't look like any of the Includes are being used. It's possible that removing them may help.
* Can you try with 2.1 (currently in rc, soon to be RTM) since several issues like this were fixed.

**Comment by CheloXL** [comment] 2018-05-25 22:47
@ajcvickers The includes are used later in the projection (or at least that was the idea). But yes, if I add the `ToList()` at the end, they are not used (EF issues 3 requests to the DB).
Will try with 2.1 and let you know...

**Comment by CheloXL** [comment] 2018-05-25 23:17
@ajcvickers With 2.1 I'm getting another exception, right at app start:
```
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(System.String, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource)'.
   at Microsoft.EntityFrameworkCore.Metadata.Builders.DiscriminatorBuilder.HasValue(String entityTypeName, Object value)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.DiscriminatorConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder, EntityType oldBaseType)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnBaseEntityTypeChanged(InternalEntityTypeBuilder entityTypeBuilder, EntityType previousBaseType)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor.VisitOnBaseEntityTypeChanged(OnBaseEntityTypeChangedNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasBaseType(EntityType baseEntityType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.DerivedTypeDiscoveryConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(EntityType entityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(TypeIdentity& type, ConfigurationSource configurationSource, Boolean throwOnQuery)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource, Boolean throwOnQuery)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity]()
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration[TEntity](IEntityTypeConfiguration`1 configuration)
   at DDS.Genesis.Infrastructure.EntityFramework.GenesisDBContext.OnModelCreating(ModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at DDS.Patterns.Repository.EntityFramework.EfValueObjectRepository`5..ctor(TConcreteUnitOfWork unitOfWork)
```

**Comment by ajcvickers** [comment] 2018-05-29 17:01
@CheloXL With regard to build issue, this usually indicates some package version mismatches. See https://github.com/aspnet/EntityFrameworkCore/issues/11704#issuecomment-382122437 for more details--it refers to preview2, but the same steps still apply for RC and RTM.

With regard to the Includes, if the query is not returning any instances of `UsuarioDb` then the Includes are ignored. They are not needed for translation of navigation properties in the query.

**Comment by CheloXL** [comment] 2018-05-29 17:28
@ajcvickers But the issue is because the query is actually returning an instance. Again, running the query above leads to that exception, adding .ToListAsync to each select makes EF issue one additional query for each select.

**Comment by ajcvickers** [comment] 2018-05-29 17:39
@CheloXL The query, as written above, projects to `UsuarioDetail`, and so does not return `UsuarioDb`. (The Include stuff doesn't matter much for the repro other than as a possible workaround, so I don't want rat-hole on it. It might be worth reading the [docs on Include](https://docs.microsoft.com/en-us/ef/core/querying/related-data).)

Regarding it throwing an exception, do you mean that you were able to test on 2.1 RC1 and it still throws?

**Comment by CheloXL** [comment] 2018-05-29 18:10
@ajcvickers So does that means that Includes will not work on any projection? The documentation doesn't says anything about that. Yes, the query itself doesn't return `UsuarioDb`, but the projection makes use of the includes. This query is a simple one and it is returning just one record (so I can convert from `UsuarioDb` to `UsuarioDetail`), but if the query returns a list, I would need to iterate the list and convert each entry?

Regarding the original exception, no, I were not able to test in 2.1 as I'm using the mysql connector and it has not been updated yet.

**Comment by smitpatel** [comment] 2018-05-29 19:14
> Yes, the query itself doesn't return UsuarioDb, but the projection makes use of the includes.

If query does not return `UsuarioDb` then includes are ignored. It does not matter even if you are using same navigation in the projection. The query pipeline expands all navigations appropriately without needing include. Reading docs on include will help you understand where includes should be used.

Regarding exception, yes it is a bug. (It may have fixed in 2.1 release though) but the expectations would still remain unmet in terms of number of queries. You are projecting out a DTO which includes 2 collection properties. Collections cannot be lifted into single Select statement without doing cartesian product which causes duplicated data. In my comment here, https://github.com/aspnet/EntityFrameworkCore/issues/12098#issuecomment-391095895 I have explained in detail why EF Core by design issues multiple queries for collections. So for your case, in which there are enumerables (not using `ToList`), EF Core will actually generate N+1 evaluation. i.e. For each record in first query `UsuarioDb`, send 2 more queries to get data for each collection property (join table). So total 2N + 1 where N is records in `UsuarioDb`. Since you are doing `FirstOrDefault` N = 1 & it would be 3 queries. If you use `ToList` then we apply optimization implemented in #9282 (in 2.1 release) and generate only 3 queries regardless of size of `N`.

**Comment by CheloXL** [comment] 2018-05-29 19:26
@ajcvickers Ok. Will try to get back as soon as I can upgrade mysql connector.

**Comment by maumar** [comment] 2018-08-28 20:03
This no longer repros in current bits, closing.

**Closed** 2022-10-16 12:26 UTC
Labels: closed-could-not-reproduce, customer-reported
