### ISSUE TITLE
Implement event for before DBCommand is executed

### ISSUE THREAD

**Issue by nphmuller** [dotnet/efcore#15988] opened 2019-06-07 09:39 UTC
As requested in the Lifecycle hooks Epic (https://github.com/aspnet/EntityFrameworkCore/issues/626), this is one of the hooks/events we need for our use cases.

The event would execute before any DBCommand is executed.

Our use case is implementing a query level cache based on [EFCache](https://github.com/moozzyk/EFCache). To implement this cache, we need to capture a query before it's executed, so we can look it up and use the cached result.

For this we'd need an event that's executed before a DBCommand is executed. It should preferably expose the entity sets affected by the DBCommand and expose the SQL Query that's about to be executed (or a unique identifier that's always the same for the same query). It should also be able to stop the DBCommand from being executed on the database, so the cached result can be returned instead.

EFCache accomplishes this in EF6 by implementing a custom [DBProviderServices](https://github.com/moozzyk/EFCache/blob/master/EFCache/CachingProviderServices.cs) object which captures the original DBCommandDefinition in a [CachingCommandDefinition](https://github.com/moozzyk/EFCache/blob/master/EFCache/CachingCommandDefinition.cs). This `CachingCommandDefinition` creates a [CachingCommand](https://github.com/moozzyk/EFCache/blob/master/EFCache/CachingCommand.cs) which returns the cached result on `ExecuteDbDataReader`, or, if no cached result exists, it executes the original `DbCommand`.

If the event I described would be exposed, it would make this process a _lot_ easier. Creating a custom `QueryProvider` should not be necessary.

See also this comment by the author of EFCache: https://github.com/aspnet/EntityFrameworkCore/issues/5858#issuecomment-306441806

**Comment by ajcvickers** [comment] 2019-06-07 18:58
Note for triage: related to #15066 and other interceptors.

**Comment by ajcvickers** [comment] 2019-06-15 23:57
Scenarios are partially covered by #15066. Moving to the backlog for the rest.

**Comment by ajcvickers** [comment] 2019-09-02 20:39
Note that #17261 is basically a duplicate of this, although they come from different directions.

**Comment by ajcvickers** [comment] 2019-09-07 19:34
Closing this since command interceptors are the hook to use before any command is executed; this is already implemented for 3.0. #17261 tracks possible changes to the command creation event to move it closer to when it is used, but this isn't necessary for the behavior requested here.

**Closed** 2022-10-16 14:24 UTC
Labels: customer-reported
