### ISSUE TITLE
Group By is getting an alias and causing a SQL Exception (in 2.1 Preview 1)

### ISSUE THREAD

**Issue by joshuakent** [dotnet/efcore#11317] opened 2018-03-18 04:54 UTC
```C#
var test = _context.SystemStorefrontOrderLine.GroupBy(o => new { o.StorefrontId, o.OrderDate.Value.Date })
                            .Select(g => new
                            {
                                g.Key.StorefrontId,
                                Sum = g.Sum(o => o.OrderItemPrice),
                                Min = g.Min(o => o.OrderItemPrice),
                                Max = g.Max(o => o.OrderItemPrice),
                                Avg = g.Average(o => o.OrderItemPrice)
                            });
```
generates the following sql

```sql
SELECT [o].[StorefrontID], SUM([o].[OrderItemPrice]), MIN([o].[OrderItemPrice]), MAX([o].[OrderItemPrice]), AVG(CAST([o].[OrderItemPrice] AS decimal(18, 2)))
FROM [SystemStorefrontOrderLine] AS [o]
GROUP BY [o].[StorefrontID], CONVERT(date, [o].[OrderDate]) AS [Date]
```
where the AS [Date] is not valid SQL. This generates the following exception

`System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'AS'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
`

**Comment by smitpatel** [comment] 2018-03-20 18:37
Generated SQL in nightly builds
```SQL
      SELECT [o].[StorefrontId], SUM([o].[OrderItemPrice]) AS [Sum], MIN([o].[OrderItemPrice]) AS [Min], MAX([o].[OrderItemPrice]) AS [Max], AVG(CAST([o].[OrderItemPrice] AS float)) AS [Avg]
      FROM [SystemStorefrontOrderLine] AS [o]
      GROUP BY [o].[StorefrontId], CONVERT(date, [o].[OrderDate])
```
Duplicate of #11218

**Closed** 2022-10-16 12:14 UTC
