### ISSUE TITLE
EF Core Migration with multiple provider always runs SQL Server scripts

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#11683] opened 2018-04-16 07:36 UTC
I am using EF Core Code first and I ran into an issue when using multiple DB providers (SQL Server and MySql). Even when I choose to use MySql DB provider, SQL server migration files are used to create/update the database.

### Steps to reproduce
Sample project can be found [here](https://drive.google.com/open?id=17db4ACiEQTEPZouL-YtBANIe5inWy913)

### Further technical details
EF Core version: 2.0.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer and Pomelo.EntityFrameworkCore.MySql
Operating system: Windows 10
IDE:  Visual Studio 2017 15.6.6

**Comment by bricelam** [comment] 2018-04-16 15:30
Caused by this:
``` csharp
public ProjectContext(DbContextOptions<ProjectContext> options)
    : base(options)
{
    Database.Migrate();
}
```

**Comment by pantonis** [comment] 2018-04-16 15:38
But I cannot remove constructor.

**Comment by bricelam** [comment] 2018-04-16 15:54
Try moving the `Database.Migrate()` call outside of the constructor. This call typically belongs in the application starting logic.

**Comment by pantonis** [comment] 2018-04-16 15:58
The reason I put it there is when the app runs for first time checks if there are any migrations pending. If yes perform them.

**Comment by bricelam** [comment] 2018-04-16 16:09
All good, but the tools also need to construct the `DbContext` at design-time, and migrations shouldn't be applied if you're just calling `Add-Migration`.

**Comment by pantonis** [comment] 2018-04-16 16:14
I know. that is the reason I added it there. In any case I removed it and create a Dbinitializer class and added the ```Database.Migrate()``` there . Again the same problem.
Check the updated code [here](https://drive.google.com/open?id=1_BPgZdFcxW63SonWBE38ymitJbQO-QwY)

**Comment by ajcvickers** [comment] 2018-10-08 17:30
@pantonis Can you update to the 2.1 release of EF Core and report back if you are still seeing this issue?

**Comment by mani009** [comment] 2018-10-12 05:38
Hello Everyone,

Further technical details

EF Core version: 2.1.4
Database Providers: Microsoft.EntityFrameworkCore.Sqllite and Pomelo.EntityFrameworkCore.MySql
Operating system: Windows 10 17134
IDE: Visual Studio 2017 15.8.5

so this is not only a problem with the migrations tools.
The optionsBuilder is configured this way.
Is this possible??

```
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (OnOffLine == "Online")
            {
                optionsBuilder.UseMySql("...");
                optionsBuilder.UseLoggerFactory(new LoggerFactory().AddDebug());
            }
            else
            {
                optionsBuilder.UseSqlite("Data Source=localdatabase.db");
                optionsBuilder.UseLoggerFactory(new LoggerFactory().AddDebug());
            }
        }
```

When i call the database objects

```
var firstdb = new Database("Offline");
var seconddb = new Database("Online");
```

sometimes the second database has the the Provider inside from the first database.

**Comment by pantonis** [comment] 2018-10-12 07:01
@ajcvickers I updated to MS EfCore 2.1.4 and still the same problem

**Comment by bricelam** [comment] 2018-10-12 17:10
I'm able to repro this. MySqlProjectContext is used even when I specify `-Context ProjectContext`. MySqlProjectContext inherits from ProjectContext, so I suspect we're picking it's IDesignTimeDbContextFactory.

You can probably workaround the issue by making ProjectContext abstract and introducing a new derived type for SqlServer.

**Comment by bricelam** [comment] 2018-10-12 17:11
This may be related to #11611

**Comment by weitzhandler** [comment] 2019-05-29 10:34
Hi guys and thanks for your input.
How can I call `context.Database.Migrate` post `OnConfiguring`?

I have a dynamic per-tenant configuration and I want the DB to be generated once the tenant info is available.

**Comment by bricelam** [comment] 2019-05-29 21:48
@weitzhandler Please submit a new issue describing where your tenant identifier is coming from and where you'd like to call Migrate

**Comment by weitzhandler** [comment] 2019-05-29 22:25
@bricelam 
Opened #15846, thanks.

**Comment by bricelam** [comment] 2020-03-10 18:30
Duplicate of #11611. That fix made this work too

**Closed** 2022-10-16 12:19 UTC
Labels: closed-duplicate, punted-for-2.2, punted-for-3.0, punted-for-3.1
