### ISSUE TITLE
Method not found:  Microsoft.EntityFrameworkCore.SqlServerPropertyBuilderExtensions.UseSqlServerIdentityColumn

### ISSUE THREAD

**Issue by dpedrelli** [dotnet/efcore#19767] opened 2020-02-01 00:59 UTC
I have an existing ASP.NET Core 2.0 app.  I am trying to upgrade EFCore from 2.0.3 to 3.1.1.  Upon adding a migration, I get the error:

`Method not found:  Microsoft.EntityFrameworkCore.SqlServerPropertyBuilderExtensions.UseSqlServerIdentityColumn`

I replaced all instances of .UseSqlServerIdentityColumn() with .UseIdentityColumn() and I still get the above error, when executing Package Manager Console command:

`Add-Migration `

**Comment by ajcvickers** [comment] 2020-02-03 17:52
@dpedrelli Can you post your csproj file so we can look at the dependencies?

**Comment by dpedrelli** [comment] 2020-02-04 01:08
@ajcvickers I had so many problems upgrading .NET Core versions that I rolled-back the changes, to get everything working.  I am attaching the two project files involved in my Add-Migration command (-Project SM.DAL -StartupProject SM.Mvc).  The only differences is they specify EntityFrameworkCore 2.0.3 instead of 3.1.1.

[SM.zip](https://github.com/dotnet/efcore/files/4150930/SM.zip)

**Comment by ajcvickers** [comment] 2020-02-04 23:57
@dpedrelli 

> The only differences is they specify EntityFrameworkCore 2.0.3 instead of 3.1.1.

This won't work. The provider and any other EF packages also need to be updated to a consistent version.

**Comment by dpedrelli** [comment] 2020-02-05 21:29
@ajcvickers Originally, I did update the packages to 3.1.1.  Do to all the errors, I rolled back the changes, prior to your request for the project file.  I started a new solution and created 3.1.1 projects.  I had to create my Data Abstraction Layer project as .NET Standard 2.1, because 2.0 is no longer supported.  However, I reported an issue with remapping ASP.NET Identity table names as of 2.1, which still seems to be not working.

**Comment by ajcvickers** [comment] 2020-02-05 21:50
@dpedrelli If you can attach something small that isn't working then I can take a look at it.

**Comment by dpedrelli** [comment] 2020-02-05 22:21
@ajcvickers I created a project that targets Net Core 3.1 and uses 3.1.1 libraries.  ApplicationDbContext.cs defines three DbContexts, mapping three instances of Identity tables to different table names.  Startup.cs uses three, different IdentityBuilders to establish three instances of Identity.  There are three, different migrations.  The behavior works perfectly in 2.0, but not since 2.1.  Since 2.1, AspNetRoles does not map to the specified table name.

[IdentityTest.NetCore311.zip](https://github.com/dotnet/efcore/files/4162331/IdentityTest.NetCore311.zip)

**Comment by ajcvickers** [comment] 2020-02-08 23:02
@dpedrelli In the original issue you posted that you get, "Method not found: Microsoft.EntityFrameworkCore.SqlServerPropertyBuilderExtensions.UseSqlServerIdentityColumn".

Above you say, "since 2.1, AspNetRoles does not map to the specified table name."

So is this now a different issue from the one you originally posted? (So I know what to investigate/attempt to reproduce.)

**Comment by dpedrelli** [comment] 2020-02-09 00:57
@ajcvickers In the original issue, I got "Method not found: Microsoft.EntityFrameworkCore.SqlServerPropertyBuilderExtensions.UseSqlServerIdentityColumn". while trying to update a Net Core 2.0 app to 3.1.1.  I experienced other issues as well and rolled back the changes.  I created a new project, from scratch, with a Net Core 3.1.1 template, because it may be easier to create a new project, rather than update the existing packages.  The new, 3.1.1, project gave me the errors regarding remapping Identity tables.  Originally, I reported the Identity problem, under Net Core 2.1.  [https://github.com/dotnet/aspnetcore/issues/5824](url)  Simply replacing my existing project with a new one may be the easier option; however, whether I update the existing project or create a new project, Identity table mapping has not worked since 2.0.  The solution that I attached is a bare bones project that illustrates the Identity problem.

**Comment by ajcvickers** [comment] 2020-02-09 02:09
@dpedrelli Thanks for the detailed information. I'll take a look tomorrow.

**Comment by ajcvickers** [comment] 2020-02-09 17:46
@HaoK Can you take a look at this? Exception and stack trace below. It looks like `ApplicationUser` is being registered, but something is trying to resolve `UserManager<IdentityUser>` still. It could be the EF mappings, but I suspect it is more likely in the server registration. Note that three different Identity DbContexts are being registered.

```
System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.UserManager`1[Microsoft.AspNetCore.Identity.IdentityUser]' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPagePropertyActivator.<>c__DisplayClass8_0.<CreateActivateInfo>b__1(ViewContext context)
   at Microsoft.Extensions.Internal.PropertyActivator`1.Activate(Object instance, TContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPagePropertyActivator.Activate(Object page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator.Activate(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.RenderPartialViewAsync(TextWriter writer, Object model, IView view)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCore.Views_Shared__Layout.<ExecuteAsync>b__25_1()
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCore.Views_Shared__Layout.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by ajcvickers** [comment] 2020-02-21 17:31
@HaoK Ping.

**Comment by HaoK** [comment] 2020-02-21 17:49
So interesting, this exception is coming from the databaseerrorpage middleware/migrations page (most likely since the db doesn't exist) trying to see if something is messed up in there for this scenario

**Comment by HaoK** [comment] 2020-02-21 17:56
Oh never mind, the issue is in Shared/_LoginPartial.cshtml, that needs to be updated to reference the appropriate users, its currently looking for IdentityUser which isn't registered...  The callstack here sucks, but if you turn on symbol sources and framework debugging, you can see that's the view causing the error.

**Comment by ajcvickers** [comment] 2020-02-22 00:05
@HaoK So which repo should this be tracked in. (I know I should know.)

**Comment by HaoK** [comment] 2020-02-22 08:54
Well I don't think this is a bug, if you customize the user types, you need to also update the _loginPartial.cshtml that's in the app to match.

**Comment by dpedrelli** [comment] 2020-02-22 18:42
@HaoK is mapping the Identity tables to new names.  This worked in 2.0.  Ever since 2.1, you can remap all of the tables except AspNetRoles.  Identity does not look for the table under the remapped name, but only AspNetRoles.  The other table names work correctly.  The attached project illustrates the problem.

Originally, I reported this under  [ https://github.com/dotnet/aspnetcore/issues/5824](url) with multiple sample project, illustrating different versions of .NET Core.

**Comment by ajcvickers** [comment] 2020-02-24 17:28
I'm going to close the issue here as I think https://github.com/dotnet/aspnetcore/issues/5824 is the right place to track this.

@dpedrelli We will continue any follow up on the original issue you posted.

**Closed** 2022-10-16 18:08 UTC
Labels: closed-external, customer-reported
