### ISSUE TITLE
EF Core 1.1 Microsoft.EntityFrameworkCore.Sqlite package fails Windows App Certification Test

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#7117] opened 2016-11-24 11:47 UTC
### Steps to reproduce

1. Create a UWP application targeting Windows 10 Anniversary Edition.
2. Follow steps provided at https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started except for using the later Microsoft.EntityFrameworkCore.Tools v1.1.0-preview4-final and not needing to create the XAML page.
3. Change build configuration to Release x86.
4. Right click on project and select Store --> Create App Packages... to view the "Create App Packages" dialog.
5. Select No for "Do you want to build packages to upload to the Windows Store?".
6. Keep all the defaults and you should see the Release configurations for x86, x64, and ARM selected.
7. Click Create and follow through the rest of the steps.

### The issue
1. The "Windows App Certification Kit - Test Results" generated shows overall result as failed.
2. Windows security features test FAILED
Binary analyzer
Error Found: The binary analyzer test detected the following errors:
File c:\program files\windowsapps\cf3d8cd1-0309-403e-ad0b-ef6cdc2a84c8_1.0.1.0_x64__cfeysmghd291c\sqlite3.dll has failed the AppContainerCheck check.
File c:\program files\windowsapps\cf3d8cd1-0309-403e-ad0b-ef6cdc2a84c8_1.0.1.0_x64__cfeysmghd291c\sqlite3.dll has failed the DBCheck check.

3. Supported API test FAILED
Supported APIs
Error Found: The supported APIs test detected the following errors:
API AreFileApisANSI in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CompareStringA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CompareStringW in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CreateFileA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CreateFileMappingA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CreateFileMappingW in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CreateFileW in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API EnumSystemLocalesA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API ExitProcess in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API FatalAppExitA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API FreeEnvironmentStringsA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API FreeEnvironmentStringsW in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API GetACP in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.

4. This issue does not exist with EF 1.01 though.

### Further technical details

EF Core version:  "dependencies": {
    "Microsoft.EntityFrameworkCore.Sqlite": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2"
  },
Operating system: Windows 10 Anniversary Edition
Visual Studio version: VS 2013 Community Edition Version 14.0.25431.01 Update 3

Other details about my project setup: Repo project and Validation results for EF Core 1.1 attached
[SqliteAppPackageRepo.zip](https://github.com/aspnet/EntityFramework/files/611196/SqliteAppPackageRepo.zip)

[ValidationResult.zip](https://github.com/aspnet/EntityFramework/files/611201/ValidationResult.zip)

**Comment by divega** [comment] 2016-11-24 16:07
duplicate of #7040?

**Comment by sgmon** [comment] 2016-11-25 02:23
Downgrading to SQLite 3.12.3 as mentioned in work around for bug #7040 solved the issue. Thanks.

**Closed** 2022-10-16 10:44 UTC
