### ISSUE TITLE
How to map a custom select or view to hierarchical structure?

### ISSUE THREAD

**Issue by Liero** [dotnet/efcore#24794] opened 2021-04-28 12:21 UTC
I would like to get IQueryable of Blogs with Post included from similar query:

```
string sql= @"SELECT * FROM Blogs
INNER JOIN Posts on Blogs.BlogId = Posts.BlogId AND Author like 'Lier%'"
```

The reason is, that I need to be able to paginate the blogs like this

```cshapr
var query = dbContext.Set<Blog>().Include(b => b.Posts).FromSql??(sql)
  .Skip(pageIndex * pageSize).
  .Take(pageSize);
```
so I can't do the mapping in memory.

Is it possible to map flat dataset to a class hierarchy? If not, it is theoretically possible in future EF versions?

--------------
The entities are the standard Blog/Posts entities from the docs..

```csharp
public class Blog {
   public int BlogId {get; set;}
   public List<Posts> Posts {get; set;}
}

public class Posts {
   public int PostId {get; set;}
   public int BlogId {get; set;}
   public Blog Blog {get; set;}
   public string Author {get; set;}
}
```

**Comment by smitpatel** [comment] 2021-04-28 16:21
Duplicate of #14525

**Closed** 2022-10-16 19:32 UTC
Labels: customer-reported
