### ISSUE TITLE
Test failure: Save_partial_update_on_missing_record_throws

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/efcore#13415] opened 2018-09-25 22:53 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=561294&buildTypeId=Lite_UniverseTest) occasionally with the following error:
```
System.AggregateException : One or more errors occurred.
---- Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'The system cannot find the file specified.
'.
---- The following constructor parameters did not have matching fixture data: UpdatesSqliteFixture fixture
----- Inner Stack Trace #1 (Microsoft.Data.Sqlite.SqliteException) -----
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Infrastructure.SpatialiteLoader.Load(DbConnection connection) in /_/src/EFCore.Sqlite.Core/Infrastructure/SpatialiteLoader.cs:line 85
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.LoadSpatialite() in /_/src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs:line 101
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected) in /_/src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs:line 68
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create() in /_/src/EFCore.Sqlite.Core/Storage/Internal/SqliteDatabaseCreator.cs:line 43
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated() in /_/src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs:line 224
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated() in /_/src/EFCore/Infrastructure/DatabaseFacade.cs:line 56
   at Microsoft.EntityFrameworkCore.TestUtilities.SqliteTestStore.Initialize(Func`1 createContext, Action`1 seed) in /_/test/EFCore.Sqlite.FunctionalTests/TestUtilities/SqliteTestStore.cs:line 64
   at Microsoft.EntityFrameworkCore.TestUtilities.TestStore.<>c__DisplayClass11_0.<Initialize>b__1() in /_/src/EFCore.Specification.Tests/TestUtilities/TestStore.cs:line 40
   at Microsoft.EntityFrameworkCore.TestUtilities.TestStoreIndex.CreateShared(String name, Action initializeDatabase) in /_/src/EFCore.Specification.Tests/TestUtilities/TestStoreIndex.cs:line 30
   at Microsoft.EntityFrameworkCore.TestUtilities.TestStore.Initialize(IServiceProvider serviceProvider, Func`1 createContext, Action`1 seed) in /_/src/EFCore.Specification.Tests/TestUtilities/TestStore.cs:line 40
   at Microsoft.EntityFrameworkCore.TestUtilities.RelationalTestStore.Initialize(IServiceProvider serviceProvider, Func`1 createContext, Action`1 seed) in /_/src/EFCore.Relational.Specification.Tests/TestUtilities/RelationalTestStore.cs:line 29
   at Microsoft.EntityFrameworkCore.SharedStoreFixtureBase`1..ctor() in /_/src/EFCore.Specification.Tests/SharedStoreFixtureBase.cs:line 55
   at Microsoft.EntityFrameworkCore.UpdatesFixtureBase..ctor() in /_/src/EFCore.Specification.Tests/UpdatesFixtureBase.cs:line 10
   at Microsoft.EntityFrameworkCore.UpdatesSqliteFixture..ctor()
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @ajcvickers

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-09-25 22:53
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-09-25 22:58
There were 16 failures [with about the same error](http://aspnetci/viewLog.html?buildId=561294&buildTypeId=Lite_UniverseTest) on master:
- Save_replaced_principal
- Update_on_bytes_concurrency_token_original_value_mismatch_throws
- Identifiers_are_generated_correctly
- SaveChanges_processes_all_tracked_entities
- SaveChangesAsync_false_processes_all_tracked_entities_without_calling_AcceptAllChanges
- Remove_on_bytes_concurrency_token_original_value_matches_does_not_throw
- Remove_partial_on_missing_record_throws
- Update_on_bytes_concurrency_token_original_value_matches_does_not_throw
- Mutation_of_tracked_values_does_not_mutate_values_in_store
- Can_remove_partial
- (And 6 more test failures in this build)


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-09-26 00:08
There were 17 failures [with about the same error](http://aspnetci/viewLog.html?buildId=561382&buildTypeId=Lite_UniverseTest) on master:
- Update_on_bytes_concurrency_token_original_value_mismatch_throws
- Remove_on_bytes_concurrency_token_original_value_mismatch_throws
- Save_replaced_principal
- SaveChanges_false_processes_all_tracked_entities_without_calling_AcceptAllChanges
- Save_partial_update_on_concurrency_token_original_value_mismatch_throws
- Save_partial_update_on_missing_record_throws
- Remove_on_bytes_concurrency_token_original_value_matches_does_not_throw
- Remove_partial_on_concurrency_token_original_value_mismatch_throws
- SaveChangesAsync_false_processes_all_tracked_entities_without_calling_AcceptAllChanges
- Can_remove_partial
- (And 7 more test failures in this build)


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ajcvickers** [comment] 2018-09-28 16:51
Duplicate of #13407

**Closed** 2022-10-16 13:32 UTC
Labels: closed-duplicate, test-failure
