### ISSUE TITLE
Int64 properties cannot be queried in EntityCore

### ISSUE THREAD

**Issue by HolyOne** [dotnet/efcore#26603] opened 2021-11-10 01:49 UTC
I have a entity class with Int64 properties. The int64 fields are mapped as BigInt in SQL Server.

when I run a simple query containing Int64 fields

`
ulong myInt64=123123;
db.Contacts.Where(o=>o.Phone == myInt64).ToList()
`

I get string parsing error. But there is no string involved and the types in the class and my query are identical. This looks like a bug in efcore.

By the way I get the same string parsing error If I try to run raw sql like

     db.Contacts.FromSqlRaw( "select * from contacts" )

It seems The problem occures when ef tries to map an SQL query result with Bigint field to a class containing Int64/long field

**Comment by roji** [comment] 2021-11-10 09:22
@HolyOne in the above code, you are trying to compare a ulong (myInt64) to a long - this does not compile.

If myInt64 is a long rather than a ulong, everything works for me - please see the below code sample. Can you please submit a runnable code sample which demonstrates the error, or tweak the below code to make it fail?

<details>
<summary>Attempted repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

long myInt64 = 123123;

var blogs = ctx.Blogs.Where(b => b.SomeLong == myInt64).ToList();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Blog
{
    public int Id { get; set; }
    public long SomeLong { get; set; }
}
```

</details>

**Comment by ajcvickers** [comment] 2021-11-18 12:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:13 UTC
Labels: closed-could-not-reproduce, customer-reported
