### ISSUE TITLE
OwnsOne fields being saved as null

### ISSUE THREAD

**Issue by Lobosque** [dotnet/efcore#24795] opened 2021-04-28 12:29 UTC
Hello,

We are getting into a problem with the following types structure:
```
            builder.OwnsMany<Transaction>("_transactions", y =>
            {
                y.ToTable("books__transactions", "banking");

                y.HasKey("Id");
                y.Property<TransactionId>("Id").ValueGeneratedNever().HasColumnName("id");

                y.Property<BookId>("_bookId").HasColumnName("book_id");
                y.WithOwner().HasForeignKey("_bookId");

                y.OwnsMany<Entry>("_entries", z =>
                {
                    z.ToTable("books__transactions__entries", "banking");

                    z.HasKey("Id");
                    z.Property<EntryId>("Id").ValueGeneratedNever().HasColumnName("id");

                    z.Property<TransactionId>("_transactionId").HasColumnName("transaction_id");
                    z.WithOwner().HasForeignKey("_transactionId");

                    z.Property<AccountId>("AccountId").HasColumnName("account_id");

                    z.OwnsOne<Money>("_amount", m =>
                    {
                        m.Property(p => p.Value).HasColumnName("amount");
                        m.Property(p => p.Currency).HasColumnName("currency");
                    });

                    z.Property<DateTime>("_createdAt").HasColumnName("created_at");
                });
```

When saving a transaction with two or more entries, in some situations the _amount gets nulled when added to the ChangeTracker, and thus also gets null when saved to the database.

We are still digging and will try to come up with a PoC - but apparently when two different entries have the same amount and currency, only one of them is added to the changeTracker. What can we do in order to avoid this from happening?

**Comment by Lobosque** [comment] 2021-04-28 12:57
The problem was passing the same `Money` Instance for different `Entries`.

Is this a bug or by design?

**Comment by ajcvickers** [comment] 2021-04-29 18:28
@Lobosque Using the same entity instance is not recommended because it's easy to make inconsistent changes, but we don't think that it should be causing this exception. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2021-05-07 16:33
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:32 UTC
Labels: closed-could-not-reproduce, customer-reported
