### ISSUE TITLE
KeyLess entity

### ISSUE THREAD

**Issue by krisrajzlive** [dotnet/efcore#27778] opened 2022-04-07 07:29 UTC
I have a key less table, tried both HasNoKey and KeyLess but none of them works still keep getting the same error message asking to mark the entity has no key in modelcreating method of the context.

protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ARMaster>(armaster =>
               {
                   armaster.HasNoKey();
                   armaster.ToTable("armaster_all");
               });
        }

**Comment by ajcvickers** [comment] 2022-04-19 12:27
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:30 UTC
Labels: closed-could-not-reproduce, customer-reported

**Comment by akshay-zz** [comment] 2023-02-21 06:21
I'm facing a similar issue. On removing the `HasNoKey` getting an error `The entity type 'RetailerFarmer' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.` 

After adding the property `builder?.HasNoKey();`. I'm getting `The navigation 'RetailerFarmerFarmers' cannot be added because it targets the keyless entity type 'RetailerFarmer'. Navigations can only target entity types with keys.`

It is replicated here
https://github.com/akshay-zz/TestHasNoKey

**Comment by ajcvickers** [comment] 2023-02-23 14:02
@akshay-zz I filed a new issue for this: #30331

**Comment by akshay-zz** [comment] 2023-02-23 14:14
> I'm facing a similar issue. On removing the `HasNoKey` getting an error `The entity type 'RetailerFarmer' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.`
> 
> After adding the property `builder?.HasNoKey();`. I'm getting `The navigation 'RetailerFarmerFarmers' cannot be added because it targets the keyless entity type 'RetailerFarmer'. Navigations can only target entity types with keys.`
> 
> It is replicated here https://github.com/akshay-zz/TestHasNoKey

Although if anyone facing this issue. It can be fixed by having a composite key for the table without adding any primary key for the table.

`.HasKey(x.ForeignKey) or .HasKey(x.ForeignKey1 , x.ForeignKey2) `
