### ISSUE TITLE
Running dnx ef dbcontext scaffold throws 'The given key was not present in the dictionary.' dnvm 1.0.0-rc1-final

### ISSUE THREAD

**Issue by collintime** [dotnet/efcore#4031] opened 2015-12-09 23:27 UTC
I'm able to generate models for a test database, but for a complex db I get the error below. A great deal of googling yielded mostly ef6 issues.   

I'm roughly following https://ef.readthedocs.org/en/latest/getting-started/aspnet5/existing-db.html#install-entity-framework

any ideas? thanks for looking.

from project.json:
...
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer.Design": "7.0.0-rc1-final"
},
  "frameworks": {
    "dnxcore50": { }
  },
...

`<C:\git\zeus\OrdersService\src\OrdersService>dnx ef dbcontext scaffold "Server=dev3;Database=db3;Trusted_Connection=True;" EntityFramework.MicrosoftSqlServer --outputDir Models`

`System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary```2.get_Item(TKey key)
   at Microsoft.Data.Entity.Scaffolding.SqlServerDatabaseModelFactory.GetIndexes()
   at Microsoft.Data.Entity.Scaffolding.SqlServerDatabaseModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.Data.Entity.Scaffolding.RelationalScaffoldingModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.Data.Entity.Scaffolding.SqlServerScaffoldingModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.Data.Entity.Scaffolding.Internal.ReverseEngineeringGenerator.GetMetadataModel(ReverseEngineeringConfiguration configuration)
   at Microsoft.Data.Entity.Scaffolding.Internal.ReverseEngineeringGenerator.GenerateAsync(ReverseEngineeringConfiguration configuration, CancellationToken cancellationToken)
   at Microsoft.Data.Entity.Design.DatabaseOperations.ReverseEngineerAsync(String provider, String connectionString, String outputDir, String dbContextClassName, List`1 schemas, List`1 tables, Boolean useDataAnnotations, CancellationToken cancellationToken)
   at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass11_0.<<ReverseEngineerAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Data.Entity.Commands.Program.Executor.<ExecuteAsync>d__13.MoveNext()
The given key was not present in the dictionary.`

**Comment by voodoogit** [comment] 2015-12-10 01:17
to clarify a little:

when using a test database with very few tables, model generation succeeds.

when using the ACTUAL database with a ton of tables, I get the error.

**Comment by voodoogit** [comment] 2015-12-14 21:01
we removed all non-clustered indexes and the model generation was successful

**Comment by lajones** [comment] 2015-12-14 21:13
Looks like a dupe of #3861 - fix was checked in with commit 454968a. But feel free to reopen if you are still experiencing it.

**Comment by cokobware** [comment] 2016-03-23 14:09
I'm doing the same thing, and getting the same error. 

Running "dnx --version" gives me:
Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16231
 Type:         Clr
 Architecture: x86
 OS Name:      Windows
 OS Version:   6.1
 Runtime Id:   win7-x86

Running "dnx ef --version" gives me:
Entity Framework Commands
7.0.0-rc1-16348

Am I doing something wrong, or do I need to update my tooling?

**Comment by lajones** [comment] 2016-03-23 16:33
See #3861 and #4566 for possible reasons for this. If you have control over the DB schema you may be able to avoid the issues that cause this (it's usually to do with tables with the same name in different schemas or indexes with the same name on different tables), but if not you will need to update your tooling to one of the nightly builds. Note: we are commonly experiencing difficulties with nightly builds for other reasons at the moment - so for now I'd recommend fixing the DB schema and sticking with RC1 if you can.

**Closed** 2022-10-16 09:20 UTC
