### ISSUE TITLE
Please fix Array.Contains(x.Property) so it generates intelligent SQL

### ISSUE THREAD

**Issue by JohnGalt1717** [dotnet/efcore#12740] opened 2018-07-20 11:45 UTC
Describe what is not working as expected.

If you use contains to find an array of say Primary Keys from an array like so:
var ids = new int[] {1,2,3,4,5};
dbset.Where(x => ids.Contains(x.Id))

Like the instructions all over the web including on Microsoft sites.

This generates HORRIBLE SQL for a common requirement (especially if you're say missing CosmosDb and Azure Sql).

For instance the following on a table of 45,000 records:

dbSet.FromSql("SELECT * FROM data.X WHERE Id IN (1,2,3,4,5)") with a few joins for security will take about 0.2 seconds.

The same using the above id.Contains will take 85 seconds!!!!

EF Core desperately needs to fix this use case by improving the generated SQL for Array Contains.

**Comment by ErikEJ** [comment] 2018-07-20 11:58
What does the "bad" SQL look like?

**Comment by JohnGalt1717** [comment] 2018-07-20 12:34
Here's a whole analysis on the topic on SOF: https://stackoverflow.com/questions/8107439/why-is-contains-slow-most-efficient-way-to-get-multiple-entities-by-primary-ke

Here's the EF 6 uservoice issue that was completed: https://data.uservoice.com/forums/72025--closed-entity-framework-core-feature-suggestions/suggestions/2598644-improve-the-performance-of-the-contains-operator

I don't have an example of produced SQL because we manually hacked up a FromSqlIn extension method to work around this for now so I don't have any code to generate it (and it would expose our schema)

Simple cases work fine and generate the right in, it's complex cases where the sql generated is multiple pages long as a result, especially from what we were doing in the lcase of DefaultIfEmpty() (Yuk, that syntax needs to be replaced with leftjoin/rightjoin 6 years ago!)

**Comment by JohnGalt1717** [comment] 2018-07-20 14:06
Yes, I just did. Using DefaultIfEmpty it would take 85 seconds if I used contains and 0.2 seconds if I used FromSql on it.

**Comment by ErikEJ** [comment] 2018-07-20 20:30
I do not see any reference to "DefaultIfEmpty" in your initial post? Please share some sample code

**Comment by smitpatel** [comment] 2018-07-20 21:12
@JohnGalt1717 - The links you have posted are irrelevant. Both of them refers to EF 6. The reason for slow performance was using OR to represent the Contains query. Which was fixed in EF 6 alpha 2 version by introducing DbInExpression.
EF Core from very start has InExpression (https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/src/EFCore.Relational/Query/Expressions/InExpression.cs) to represent the structure hence there is no perf issue there.

**Comment by smitpatel** [comment] 2018-07-20 21:12
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by divega** [comment] 2018-07-22 22:15
@JohnGalt1717 as mentioned by @smitpatel the analysis in the StackOverflow thread you pointed to have been obsolete for EF since 2013 and never applied to EF Core. 

If you are having specific issues with the performance of the translation of Enumerable.Contains in EF Core, we would be **very grateful** if you could create a new issue with a repro, or at least with examples of the patterns you have in your LINQ queries and the patterns you are seeing in the SQL. We also regularly accept repros from customers that can't share them publicly but are comfortable sharing them with us over email.

**Closed** 2022-10-16 13:20 UTC
Labels: closed-could-not-reproduce, customer-reported
