### ISSUE TITLE
Data modified when AsNoTracking() not placed in the top

### ISSUE THREAD

**Issue by mohammed-fuad** [dotnet/efcore#20020] opened 2020-02-21 17:01 UTC
I added AsNoTracking() at the end before `ToArrayAsync()` for a query which returned data shouldn't be modified, but I found entity state changed to Modified.

### Steps to reproduce

``` C#
var data =await this.context.Users.Where(a => a.IsActive).AsNoTracking().ToArrayAsync();

//In this line I should return manipulated data (e.g. Parse some numeric data to text).
data = data.ReflectLabels();

// To add tracking log
this.context.Logs.Add(new Log(DateTime.UtcNow, this.userContext.UserId));
await this.context.SaveChangesAsync()
```

After executing above code, I found data where changed inside `data.ReflectLabels()` are persisted in database.

But if I added `AsNoTracking()` in top after DbSet, state of entity will remain as UnChanged as:

``` C#
var data =await this.context.Users.AsNoTracking().Where(a => a.IsActive).ToArrayAsync();

//In this line I should return manipulated data (e.g. Parse some numeric data to text).
data = data.ReflectLabels();

// To add tracking log
this.context.Logs.Add(new Log(DateTime.UtcNow, this.userContext.UserId));
await this.context.SaveChangesAsync();
```

### Further technical details

EF Core version: 2.2.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 2.2
Operating system:
IDE: (e.g. Visual Studio 2017 15.9.20)

**Comment by ajcvickers** [comment] 2020-02-21 21:17
@mohammed-fuad EF Core 2.2 is [out-of-support](https://docs.microsoft.com/en-us/ef/core/what-is-new/). Please try this with EF Core 3.1. If you are still seeing this behavior, then please attach a small, runnable project that reproduces what you are seeing.

**Comment by ajcvickers** [comment] 2020-02-28 17:09
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by mohammed-fuad** [comment] 2020-02-29 17:35
@ajcvickers I found the issue caused by [LinqKit.Microsoft.EntityFrameworkCore](https://github.com/scottksmith95/LINQKit) version 1.1.16 which is not part of efcore

**Closed** 2022-10-16 18:12 UTC
Labels: closed-could-not-reproduce, customer-reported
