### ISSUE TITLE
add-migration generating code from previous migrations

### ISSUE THREAD

**Issue by TehWardy** [dotnet/efcore#19669] opened 2020-01-22 17:01 UTC
So I have a migration that I generated last week with the usual "add-migration" command, it's also been applied to my db.

Then I call "add-migration" today and I see stuff that's in the previous migration again.

Naturally this won't run on my db because it's trying to do things like drop stuff that's no longer there or create stuff that already exists.

Is there a way to force the system to sync up somehow so it doesn't do this?

I've noticed on another context every time I generate a new migration it's trying to drop a few columns that were dropped about 5 migrations ago, I have been just removing these generated lines each time and the rest of the migration is fine but now this is happening in other contexts i'm worried that i'm backing myself in to a bad corner that i'm not going to like later.

any ideas?

**Comment by ajcvickers** [comment] 2020-01-24 20:09
@TehWardy If you haven't been customizing the migrations, then you could delete them and start again  with a new migration. However, given that you are hitting what seems to be a bug, it would be great if you could provide a small repro project so that we can investigate.

**Comment by TehWardy** [comment] 2020-01-30 16:25
That's frustrating ... Digging out the code that causes this is not going to be trivial. 
Is there no way I execute some sort of PMC command to force the model information files to "correct" themselves. 

I haven't been editing the migrations but i have had to roll a couple back (using the remove-migration command from pmc).

If I delete my local copy of the db and regen the initial migration from scratch surely it'll go bang as soon as I attempt a deploy. My issue boils down to the Migrations history either in code or the db / both not agreeing with one another for some reason. 

One other solution might be for Migrations to attempt and then if it's doing say a column add and the column already exists, consider it done and a success.

**Comment by ajcvickers** [comment] 2020-01-31 20:14
@TehWardy 

> Is there no way I execute some sort of PMC command to force the model information files to "correct" themselves.

No, there isn't such a command. Even if there was, it likely wouldn't help given this:

> I generate a new migration it's trying to drop a few columns that were dropped about 5 migrations ago,

Because this means it's not just a broken model snapshot or last migration, but instead something else going on.

We discussed this again, but we came to the same conclusion: this is likely a bug and we need to be able to reproduce it in order to both fix it and to give guidance on workarounds.

**Comment by TehWardy** [comment] 2020-02-10 13:27
Idea ... as a work around ... 

When this situation arises, if I push the latest code to all environments to sync up the database versions then drop my local copy of the databases and gen a new initial migration, is there some way I can push a command during deploy to say "update the migrations history to match that initial is already run" ... as a sort of one off WITHOUT actually trying to migrate any db's?

Pinning this down is going to be a nightmare.

**Comment by ajcvickers** [comment] 2020-02-10 19:35
@TehWardy Would it be possible to give us access to your code? If it's not public, then could you send it directly to us? My email is avickers at microsoft.com.

**Comment by ajcvickers** [comment] 2020-02-21 17:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:07 UTC
Labels: closed-could-not-reproduce, customer-reported
