### ISSUE TITLE
Support value conversion for keys (indexes)

### ISSUE THREAD

**Issue by amoorthaemer** [dotnet/efcore#12720] opened 2018-07-19 09:18 UTC
Hi guys,

EF Core currently supports value conversions on non key/index properties. I have a scenario in which i need to convert a key property also. Is this something that can be taken into account for the next/future version?

TIA
Bert

**Comment by smitpatel** [comment] 2018-07-19 17:33
Related #11597

**Comment by divega** [comment] 2018-07-20 19:03
This seems to be just a duplicate of #11597. We support keys and indexes as long as the values are not store generated.

**Comment by divega** [comment] 2018-07-20 19:04
@amoorthaemer feel free to post more details about the scenario that isn't working for you if you disagree that this is a duplicate of #11597.

**Comment by amoorthaemer** [comment] 2018-07-21 06:31
Hmmmm, I strongly disagree with the fact that you can’t use value conversions even if the value is store generated. As long as you have a scenario in which the value conversion is able to comply with the rules for store generated values (eg return default values when a value needs to be generated from by the store) also I can image a scenario in which the value processing is layered. Eg value conversion generates default value and default value gets a temporary value which in turn gets converted into a store generated value ...

For example
1. Value converter => Guid to default long (eg 0)
2. Temporary value generator => some random long
3. Store = generates long based on identity column and returns it
4. Value generator converts the new long into a Guid

Step 2 can be omitted if a temporary value generator isn’t used

This scenario is typically useful if you want to obfuscate the real ids to the world and also makes it much more workable if you have a long identity column instead of a Guid identity column in the database

Anyway that’s my point on view in this
Bert

**Closed** 2022-10-16 13:20 UTC
Labels: closed-duplicate, customer-reported
