### ISSUE TITLE
FromSqlRaw For InMemory Db working in dotnet 6 but breaking in dotnet 8

### ISSUE THREAD

**Issue by jp1482** [dotnet/efcore#32875] opened 2024-01-20 17:44 UTC
I have couple of Unittest around call to the stored procedure.  This working fine around actual provider ( Means SqlServer) but for unit test it was written around InMemory provider. This is working fine in dotnet 6 but not for dotnet 8.

- DbContext.
```
	public class SimpleDbContext : DbContext
	{
		public SimpleDbContext(DbContextOptions<SimpleDbContext> option)
			: base(option)
		{ }

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			modelBuilder.Entity<SimpleRow>().HasNoKey();
			base.OnModelCreating(modelBuilder);
		}
	}

	/// <summary>
	/// Stored Procedure Result Row.
	/// </summary>
	public class SimpleRow
	{
		public int Id { get; set; }
		public string GivenName { get; set; }
		public string FamilyName { get; set; }
	}
```
- Code that call this. 
```
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Dotnet6Check
{
	internal class Program
	{
		static async Task Main(string[] args)
		{
			ILoggerFactory loggerFactory = LoggerFactory.Create(builder =>
			{
				builder.SetMinimumLevel(LogLevel.Trace);
				builder.AddConsole();
			});
			var optionBuilder = new DbContextOptionsBuilder<SimpleDbContext>()
								.UseLoggerFactory(loggerFactory)
								.UseInMemoryDatabase("Test");
			using var context = new SimpleDbContext(optionBuilder.Options);
			var data = await context.Set<SimpleRow>().FromSqlRaw("EXEC GetData").ToListAsync();			
		}
	}
}
```

It failed in dotnet 8 with error. 
```
Query root of type 'FromSqlQueryRootExpression' wasn't handled by provider code. This issue happens when using a provider specific method on a different provider where it is not supported
```

Stack trace.
```
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at Dotnet8Check.Program.<Main>d__0.MoveNext() in J:\Code\Win32ProcessAndMemoryLimit\EFCoreUnitTestCheck\Dotnet8Check\Program.cs:line 23
```

EF Core version:
Database provider: (Microsoft.EntityFrameworkCore.InMemory)
Target framework:  .NET 6.0, .NET 8.0
Operating system: Windows (But may be issue with any OS)
IDE: (e.g. Visual Studio 2022 17.8.4)

**Comment by ajcvickers** [comment] 2024-01-22 11:16
Duplicate of #30246. See also https://github.com/dotnet/EntityFramework.Docs/issues/4257

**Closed** 2024-01-23 09:29 UTC
Labels: customer-reported

**Comment by tdeepak789** [comment] 2024-10-15 18:21
I have got into the same issue,

Unit tests around FromSqlRaw is failing and throwing 'query root of type fromsqlqueryrootexpression wasn't handled by provider'

this error was thrown only during unit testing, application (SUT)  is working correctly.
1. InMemory database for unit testing
2. Used ms sql as actual database in application before , now we have migrated to postgres
3. Unit tests around FromSqlRaw is passed when the database is in ms sql
4. Unit tests around FromSqlRaw is failed when the database is postgres.


I have used RelationalQueryableExtensions.FromSqlRaw, but the issue not resolved.

**Comment by roji** [comment] 2024-10-16 09:21
@tdeepak789 please fully read the comments #34918 on the status of this - it's not something we consider a bug/regression that would be fixed.

**Comment by tdeepak789** [comment] 2024-10-16 18:01
@roji , I have not understand how FromSqlRaw query root expression not handled by provider issue is related to creation of multiple instances of IServiceProvider that mentioned #34918 



I am getting

 "Query root of type 'FromSqlQueryRootExpression' wasn't handled by provider code. This issue happens when using a provider specific method on a different provider where it is not supported."

this error is only thrown when executing integration test cases which uses in memory database on SUT which uses postgres as database, but the same code (FromSqlRaw) is working correctly while using ms sql for SUT.

let me know If I am missing anything here.
Have used the RelationalQueryableExtensions.FromSqlRaw instead of dbcontext.Entity.FromSqlRaw, but issue not resolved.

**Comment by roji** [comment] 2024-10-16 18:30
Apologies, I pasted in the wrong issue number - please read the conversation in #30246.
