### ISSUE TITLE
Separate Table for Owned Type across multiple normal types

### ISSUE THREAD

**Issue by moataz1991** [dotnet/efcore#17545] opened 2019-08-31 05:54 UTC
I have RowInfo owned type in an abstract base class for my models
i want to make it in a separate table and i couldn't , please help 

### Steps to reproduce

```c#
[Owned]
public class RowInfo{
public long RowInfoId{get;set;}
public DateTime LastUpdated{get;set;}
}

public abstract class DbModel{
public long Id{get;set;}
public RowInfo RowInfo {get;set;} = new RowInfo();
}

public class c1 : DbModel...
public class c2 : DbModel...
public class c3 : DbModel...
...

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            try
            {
                var entityMethod = typeof(ModelBuilder).GetMethods().First(m => m.IsGenericMethod && m.Name == "Entity");
                //modelBuilder.Entity<DbModel>().OwnsOne(a => a.RowInfo,a=>a.ToTable("RowInfo")); -----> First Try(1)
                if (assemblies == null)
                {
                    var cBase = Assembly.GetEntryAssembly().CodeBase;
                    assemblies = new List<Assembly>();
                }
                assemblies.Add(Assembly.GetAssembly(typeof(User)));

                foreach (var assembly in assemblies)
                {
                    var entityTypes = assembly
                      .GetTypes()
                      .Where(t =>
                        typeof(DbModel).IsAssignableFrom(t) && !t.IsAbstract && !t.IsInterface)
                        .Where(t => t.GetCustomAttribute<IgnoreDbTableAttribute>() == null);
                    var _types = entityTypes;
                    foreach (var type in _types)
                    {
                        entityMethod.MakeGenericMethod(type)
                          .Invoke(modelBuilder, new object[] { });
                    }
                }

                

                var types = modelBuilder.Model.GetEntityTypes();
                foreach (var entityType in types)
                {
                    foreach (var property in entityType.GetProperties())
                    {
                        if (property.ClrType.IsEnum)
                        {

                            var converterType = typeof(EnumToStringConverter<>)
                                .MakeGenericType(property.ClrType);
                            var converter = (ValueConverter)Activator.CreateInstance(converterType, (object)null);
                            property.SetValueConverter(converter);
                        }
                    }
                    modelBuilder.Entity(entityType.ClrType).OwnsOne("RowInfo", "RowInfo", a => a.ToTable("RowInfo"));-----> Second Try(2)
                }

                foreach (var pdb in modelBuilder.Model
                .GetEntityTypes()
                .SelectMany(t => t.GetProperties()))
                {
                    var pb = modelBuilder.Entity(pdb.DeclaringEntityType.ClrType).Property(pdb.Name);
                    if (pb.Metadata.ClrType == typeof(DateTime))
                        pb.HasColumnType("datetime2");
                    if (pb.Metadata.Name == "LastDateTimeUpdated")
                        pb.HasDefaultValueSql("getdate()")
                            .ValueGeneratedOnAddOrUpdate();
                    if (pb.Metadata.Name == "RowVersion")
                        pb.IsRowVersion()
                            .ValueGeneratedOnAddOrUpdate()
                            .IsConcurrencyToken();
                }

                OnModelCreatingExtentionActions.ForEach(a => a.Invoke(modelBuilder));


                foreach (var relationship in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
                {
                    relationship.DeleteBehavior = DeleteBehavior.Restrict;
                }
            }
            catch (Exception e)
            {
                File.AppendAllText(Path.Combine(Directory.GetCurrentDirectory(), "logger.txt"), e.Message);
                throw;
            }

        }
```

Try No.1
```
Exception message:The derived type 't1' cannot have KeyAttribute on property 'Id' since primary key can only be declared on the root type
Stack trace:System.InvalidOperationException: The derived type 'AssetModel' cannot have KeyAttribute on property 'Id' since primary key can only be declared on the root type.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.KeyAttributeConvention.ProcessModelFinalized(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

Try No.2
```
Exception message:The entity type 'RowInfo' cannot be added to the model because a weak entity type with the same name already exists.
Stack trace:System.InvalidOperationException: The entity type 'RowInfo' cannot be added to the model because a weak entity type with the same name already exists.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(EntityType entityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(TypeIdentity& type, ConfigurationSource configurationSource, Nullable`1 shouldBeOwned)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource, Nullable`1 shouldBeOwned)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasOwnership(TypeIdentity& targetEntityType, MemberIdentity navigation, Nullable`1 inverse, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasOwnership(String targetEntityTypeName, String navigationName, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.OwnsOneBuilder(TypeIdentity& ownedType, String navigationName)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.OwnsOne(String ownedTypeName, String navigationName, Action`1 buildAction)
   at DataAccessLayer.TheDbContext.OnModelCreating(ModelBuilder modelBuilder) in C:\Users\Eng.Moataz\source\repos\vs2019\iEstate\DataAccessLayer\TheDbContext.cs:line 117
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Further technical details
EF Core version: 3 preview 7
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: VS 2019 Preview

**Comment by AndriySvyryd** [comment] 2019-09-04 18:10
@moataz1991 

- There were some bug fixes in this area, try using a [nightly build](https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md).
- Make sure to not use KeyAttribute in a derived class.
- Do go through the `OwnsOne` method to set the table name: `modelBuilder.Entity<DbModel>().OwnsOne(a => a.RowInfo,a=>a.ToTable("RowInfo"))`

If these don't help please post a small runnable project that shows the issue.

**Comment by divega** [comment] 2019-09-11 18:55
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 14:39 UTC
Labels: closed-could-not-reproduce, customer-reported
