### ISSUE TITLE
Do not map property to column in database but fetch property value by raw SQL query

### ISSUE THREAD

**Issue by arturwv** [dotnet/efcore#30756] opened 2023-04-25 07:13 UTC
Need to have property in an entity which is computed every query execution.
This property should not be mapped to the DB column

now It works when you use
modelBuilder.Entity<Person>().Ignore(a => a.SomeData);  //but it disables populating Property in class when I use SQLRaw query.

db is created, then you comment abowe-  
and add 
modelBuilder.Entity<Person>().Property(a => a.SomeData).HasComputedColumnSql();

but it is no a solution :/

So maybe add this future ->  eg. HasComputedRawSqlProperty() -> dont create dbCollumn and expect the SQLRaw query will deliver a value or not.

**Comment by roji** [comment] 2023-04-25 07:46
Duplicate of #10768

**Comment by arturwv** [comment] 2023-04-25 07:53
It is not the same,
With Hierarchical table, I wan to have column generated by ... recursive query whit path 

with a computed  column, I need to make a function that will update this column every time I make an insert or update (when I change the parent, add a node, etc.)

**Comment by roji** [comment] 2023-04-25 08:40
I don't follow... You seem to be asking for HasComputedRawSqlProperty, which would mean that when you load the entity, that property is loaded from raw SQL that you specify. For example, you could do HasComputedRawSqlProperty("SOME RAW SQL"), and then EF Core would generate SQL like the following when loading the entity:

```sql
SELECT [Id], [SomeOtherField], <SOME RAW SQL> AS MyProperty ...
```

That same `SOME RAW SQL` can be passed to HasComputedColumn today, and will be computed on-demand whenever you query the database computed column:

```sql
SELECT [Id], [SomeOtherField], [MyProperty] ...
```

There's no need to update the column - the whole point of a computed column is that this is managed for you by the database; the value simply gets calculated when you query it (for virtual columns).

**Comment by arturwv** [comment] 2023-04-25 09:00
Maybe I don't know how.. 
How would you "compute" HierarchyPath collumn in "compputed collumn"?

Id	Name	ParentId	HierarchyPath
1	Loc 1	NULL	1
3	Loc 2	1		1/3
4	Loc 3	1		1/4
5	Loc 4	1		1/5
6	Loc 5	1		1/6
7	Loc 6	3		1/3/7
8	Loc 7	7		1/3/7/8
9	Loc 8	7		1/3/7/9

**Comment by arturwv** [comment] 2023-04-25 09:06
by query which gives me all the data. 

```
  WITH CTELocationsTree
	                    AS
	                    (
	                    SELECT [Id],[Name],[ParentId], Convert(NVARCHAR(MAX),[Id]) as HierarchyPath
	                    FROM [dbo].[Locations] WHERE Id = 1 

	                    UNION ALL

	                    SELECT loc.[Id],loc.[Name],loc.[ParentId], Convert(NVARCHAR(MAX),cloc.HierarchyPath +'/'+ Convert(NVARCHAR(20),loc.Id))  as HierarchyPath
	                    FROM [dbo].[Locations] loc
	                    INNER JOIN CTELocationsTree cloc  ON loc.ParentId = cloc.Id
	                    )
	                    SELECT * FROM CTELocationsTree cte 
```

**Comment by roji** [comment] 2023-04-25 14:38
I don't understand what you're asking...

**Comment by arturwv** [comment] 2023-04-25 20:23
in the described case, I don't see a place for solutions using a virtual column in db

**Comment by roji** [comment] 2023-04-25 20:41
@arturwv I'm sorry, but I don't understand your argument. If what you want is to have a .NET property which, when loaded, evaluates arbitrary raw SQL in the database, than a database virtual column provides that capability. You haven't provided a reason to avoid this.

**Comment by arturwv** [comment] 2023-05-04 06:09
> database virtual column provides that capability 
In a what way ?
1. Create Scalar function (with recursive query )  -func is  not deterministic, so it cant be persisted.
2. add Computed column with this function
3. performance of that construction is zero - that is reason against > standard way

**Comment by roji** [comment] 2023-05-05 08:26
As far as I know, there is no performance difference whatsoever between calling your scalar function directly in the query (which is what you're asking for), or creating a (non-persisted) computed column and fetching that column. In both cases the database has to invoke your function for each table row that's selected - it's exactly the same.

I'm going to go ahead and close this as a duplicate of #10768 - I don't see anything new here compared to that issue. Please feel free to continue posting here, but I recommend understanding exactly why you're asking for this - performance-wise there really should be a difference, and computed columns should already address the vast majority of needs here.

**Closed by roji** 2023-05-05 08:26 UTC
Labels: type-enhancement, customer-reported
