### ISSUE TITLE
"dotnet ef" console output does not look good on dark backgrounds

### ISSUE THREAD

**Issue by jaworek** [dotnet/efcore#14809] opened 2019-02-25 08:13 UTC
When using built in console in JetBrains Rider, output from the "dotnet ef" command is not very readable due to text being black on a dark background.
I have not noticed similar problems with other console tools, so my first assumption is that there may be a problem with dotnet tool instead of it being IDEs fault.

I also tested this behaviour with iTerm2 for Mac with ZSH and custom theme and such a problem does not occur.

Ouput of "dotnet ef migrations list" command in Rider:
![screenshot 2019-02-25 at 08 44 47](https://user-images.githubusercontent.com/22678765/53322241-62e9e600-38db-11e9-8f54-565ff376d7ab.png)

Ouput of "dotnet ef migrations list" command in iTerm2:
<img width="412" alt="screenshot 2019-02-25 at 08 44 58" src="https://user-images.githubusercontent.com/22678765/53322252-20280e00-38db-11e9-9ad8-888da87bc45b.png">

Ouput of "dotnet ef" command in Rider:
![screenshot 2019-02-25 at 08 45 38](https://user-images.githubusercontent.com/22678765/53322266-274f1c00-38db-11e9-9a0e-5d30cdd4170b.png)
In this case only horse does not display properly as the usage/help instructions are rendered properly.

Ouput of "dotnet ef" command in iTerm2:
<img width="932" alt="screenshot 2019-02-25 at 08 45 15" src="https://user-images.githubusercontent.com/22678765/53322259-23bb9500-38db-11e9-9907-c96af4895e17.png">

### Further technical details
EF Core version: 2.2.1-servicing-10028
Operating system: MacOS 10.14.3
IDE: JetBrains Rider
Terminal: iTerm2 with OhMyZsh and Powerlevel9k theme

**Comment by ajcvickers** [comment] 2019-02-25 21:05
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/9766

We don't plan to change anything here. The guidance is to use "--no-color" when the colorization makes things hard to read. Please comment on this issue if things are still hard to read when "--no-color--" is used; that is something we would look into.

**Closed** 2022-10-16 13:53 UTC
Labels: customer-reported
