### ISSUE TITLE
Support `DbContext.FromSqlRaw`

### ISSUE THREAD

**Issue by John0King** [dotnet/efcore#17516] opened 2019-08-30 01:39 UTC
Today there is a `DbContext.Set<T>().FromSql<T>()`, the problem is that when u use this , your sql should map to entity or a quey type that DbContext know about how to map the property.
That add many overhead for devs to just use group by , join  for some temporary query.
normally we just switch to use Dapper ,  but the good of `.FormSql<T>()` is you can then add `.Where(Expression)` to it.

I'm suggestion add a new method that create `IQuerable<T>` directly from sql,  and the property map must use Sql to match model  instead of use model to match sql so there no need to configurate the query model in the dbContext.

```C#
DbContext.FromSqlRaw<T>(string sql)
DbContext.FromSqlRaw<T>(string sql, T objectProjection> // some idea of dynamic/anonymous support , .FromSql("SELECT **", new { Name= "", Age = 0, BirthDay = (DateTime?)null })
```

**Comment by smitpatel** [comment] 2019-08-30 01:41
Duplicate of #10753

**Closed** 2022-10-16 14:38 UTC
Labels: closed-duplicate, customer-reported
