### ISSUE TITLE
EF Core Scaffold-DbContext command (database-first) does not add proper [DatabaseGenerated(DatabaseGeneratedOption.Computed)] on generated class properties

### ISSUE THREAD

**Issue by allanchao** [dotnet/efcore#15838] opened 2019-05-29 06:50 UTC
There is an [existing issue](https://github.com/aspnet/EntityFrameworkCore/issues/14910) that was closed as could not reproduce, but I will try my best to describe what's happening.

Using EF Core v3.0.0-preview5.19227.1
+ Microsoft.EntityFrameworkCore.SqlServer
+ Microsoft.EntityFrameworkCore.Proxies
+ Microsoft.EntityFrameworkCore.Tools

Steps to reproduce:

1. Create any database table in SQL Server
2. On that database table, create a computed column that uses another column
3. In web project C#, run Scaffold-DbContext

Expected result:

The auto-generated data class has the property for the computed column, with the attribute [DatabaseGenerated(DatabaseGeneratedOption.Computed)]

Actual:
The auto-generated data class has the property for the computed column, with no attribute

This attribute is needed for EF inserts, and without it, will error on inserts.

Microsoft.EntityFrameworkCore.DbUpdateException: 'An error occurred while updating the entries. See the inner exception for details.

Inner Exception
SqlException: The column "xxx" cannot be modified because it is either a computed column or is the result of a UNION operator.
The column "xxx" cannot be modified because it is either a computed column or is the result of a UNION operator.

The current workaround is to add the attribute to the property in the autogenerated class, but it must be re-added on every database scaffold, which is a pain. Since c# does not currently support any way to add attributes to properties from other partial classes, I was unable to get any workaround to work.

**Comment by ajcvickers** [comment] 2019-06-03 16:04
@allanchao Can you post the project that is created after you follow the "steps to reproduce" that you list above?

**Comment by ajcvickers** [comment] 2019-06-10 16:40
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by jornhd** [comment] 2020-03-25 10:21
I'm experiencing the same thing. I was able to work around the problem by implementing the partial OnModelCreatingPartial. On the computed properties I added .ValueGeneratedOnAddOrUpdate().
`modelBuilder.Entity<MyEntity>(entity => entity.Property(e => .ComputedProperty).ValueGeneratedOnAddOrUpdate());`

But this should be fixed in the Scaffold-DBContext.

**Comment by aeslinger0** [comment] 2020-06-11 13:27
@jornhd thank you so much for this! The scaffolding was generating my computed, persisted column as `entity.Property(e => e.TypeId).HasComputedColumnSql("((1))");` which seems right. It is also part of a composite foreign key (not sure if that's part of the problem or not). I get the same exception as the OP when adding a new entity. It didn't matter if I left the property alone or tried setting it to the computed value. Your fix worked in a way that I can still regenerate my DbContext. Thanks again!

@ajcvickers, is this expected behavior?

**Comment by ajcvickers** [comment] 2020-06-11 14:23
@aeslinger0 We have not been able to reproduce this. Please post a small, runnable project created by scaffolding the context that demonstrates the error you are seeing.

**Comment by marcelodesarrollo** [comment] 2020-06-23 03:13
I have the same problem It occurs when the Identity column is not the primary key 
For ejemple you have MeetingID varchar(36), MeetingName varchar(200) MeetingNumber int -Identity
We need to have a ValueGeneratedOnAddOrUpdate, because EF tries to update it

**Comment by erikmourits** [comment] 2020-11-05 07:55
Having the same issue with a temporal table
`CREATE TABLE [dbo].[test]
(
    [Id] INT IDENTITY (1, 1) NOT NULL,
    SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL, 
    SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL, 
    PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime)
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.test_History));`

`Scaffold-DbContext "name=Test" Microsoft.EntityFrameworkCore.SqlServer -Project Test -OutputDir Entities -f -Context TestContext`

**Comment by ErikEJ** [comment] 2020-11-05 08:22
@erikmourits Mark the columns HIDDEN

**Comment by allanchao** [comment] 2022-02-28 23:21
@ajcvickers 

Here is the small project requested. I'm sure myself and others would still appreciate a fix in future versions of Entity Framework Core.

[ScaffoldDbComputed.zip](https://github.com/dotnet/efcore/files/8157563/ScaffoldDbComputed.zip)

PROBLEM:
the MyScaffold\Employee.cs autogenerated file from Scaffold-DbContext should have [DatabaseGenerated(DatabaseGeneratedOption.Computed)] on both properties NameReversed and NameReversedNotNull . This issue occurs for all computed columns, whenever using Scaffold-DbContext.

Additional Information:
using .NET 6.0 Console Application
Visual Studio 2022 64-bit version 17.0.5
SQL Server 2016
(this problem occurs on all versions of Visual Studio, .NET, and SQL Server

Packages:
Microsoft.EntityFrameworkCore.Tools 7.0.0-preview.1.22076.6
Microsoft.EntityFrameworkCore.SqlServer 7.0.0-preview.1.22076.6
(this problem occurs on all versions of these packages)

```
PM> Scaffold-DbContext "Server=108.xx.xx.xx\xxxx;Database=ScaffoldDbComputed;Trusted_Connection=False;TrustServerCertificate=True;User Id=xxxx;Password=xxxx" Microsoft.EntityFrameworkCore.SqlServer -OutputDir "MyScaffold" -ContextDir "MyScaffold" -Namespace ScaffoldDbComputed -Force
```

```
======================================================
USE [ScaffoldDbComputed]
GO

/****** Object:  Table [dbo].[Employees]    Script Date: 2/28/2022 11:02:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Employees](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[NameReversed]  AS (reverse([name])) PERSISTED,
	[NameReversedAndNotNull]  AS (isnull(reverse([Name]),'')) PERSISTED NOT NULL,
 CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

======================================================
```

**Comment by ajcvickers** [comment] 2022-03-01 09:56
@allanchao This is likely a duplicate of #22842. When I scaffold from that schema I get:

```C#
modelBuilder.Entity<Employee>(entity =>
{
    entity.Property(e => e.Name)
        .IsRequired()
        .HasMaxLength(50)
        .IsUnicode(false);

    entity.Property(e => e.NameReversed)
        .HasMaxLength(50)
        .IsUnicode(false)
        .HasComputedColumnSql("(reverse([name]))", true);

    entity.Property(e => e.NameReversedAndNotNull)
        .IsRequired()
        .HasMaxLength(50)
        .IsUnicode(false)
        .HasComputedColumnSql("(isnull(reverse([Name]),''))", true);
});
```

**Comment by ErikEJ** [comment] 2022-03-01 14:37
@allanchao our you not specifying to use data annotations?

**Comment by allanchao** [comment] 2022-03-03 22:05
@ajcvickers you are correct, this was my issue, thanks. After I gave view definition 

`
GRANT VIEW ANY DEFINITION TO myuser
`

using this SQL, it added the HasComputedColumnSql(...). Thanks for your assistance.

**Closed** 2022-10-16 14:22 UTC
Labels: customer-reported
