### ISSUE TITLE
Is there any chance so I can use part of EF to just generate SQL from expression tree?

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/efcore#17231] opened 2019-08-18 04:34 UTC
Hi,

Can I?

By part of, I mean use some code _with little modification_ or refrence the EF's dll but use it as SQL generator, not ORM.

**Comment by ajcvickers** [comment] 2019-08-19 15:36
@dehghani-mehdi What do you plan to do with the generated SQL?

**Comment by dehghani-mehdi** [comment] 2019-08-20 04:04
@ajcvickers nothing fancy, I just want to use them against database, e.g using ADO.

In fact I want to use power of LINQ and provide rich apis for my users, but don't want to use EF as ORM.

**Comment by dehghani-mehdi** [comment] 2019-08-20 15:27
@ajcvickers I'm sorry I didn't get you.

I just want to write LINQ queries and get SQL version of it, as minimal example, I like to provide something like following to my users:

```
Task<IEnumerable<T>> FindAsync<T>(Expression<Func<T, bool>> predicate);
```
And then in the method EF convert `predicate` to `SQL`.

I'm looking for similar thing asked at [this stackoverflow question](https://stackoverflow.com/q/7731905/3367974)

**Comment by ajcvickers** [comment] 2019-08-20 16:14
@dehghani-mehdi This is not currently a goal of EF. When considering as something we might do we would need to understand what the real value is, which always comes down to what to do with the queries after they have been generated. An OR/M generates queries for which it can also interpret the results. Without interpretation of the results, generation of queries doesn't seem very useful. For example, in your trivial example above, how do get an `IEnumerable<T>` from the query?

**Comment by dehghani-mehdi** [comment] 2019-08-20 18:02
Yes, I know, obviously my request is not popular and as you mentioned, it is not the goal of EF.

Currently I could convert `Expression<Func<T, bool>> predicate` to SQL's `WHERE `. but it is not enough.

The body of `FindAsync` contains `$"SELECT {fields} FROM {tableName} {where}"`, I run it against database (_I use Dapper, so `IEnumerable<T>` comes form it_). I use reflection to find out what `fields` and `tableName` are. obviously this solution is not good, the performance may not be good enough, specially the `WHERE` part, also I could not solve complex queries/expressions, e.g JOIN.
So, I'm looking for a good solution to handle this kind of problems in my application.

**Comment by AndriySvyryd** [comment] 2019-08-22 21:05
Dupe of https://github.com/aspnet/EntityFrameworkCore/issues/11625?

**Comment by smitpatel** [comment] 2019-08-22 21:13
I would say both are different slightly.
The other is about getting command for a full query without executing it. Which we may able to do it.
This one is about converting arbitrary part. The linked question also mentions an example
```C#
Expression<Func<Product, int, int, bool>> inPriceRange =
        (Product product, int from, int to) =>
            product.PriceInCents >= from && product.PriceInCents <= to;
```
There are no query roots no connection to EF Core. So everything needed to translate needs to come from outside. The cost of such a linq to sql translator like that may exceed cost of EF core as ORM.
As @ajcvickers is asking above, if there is no way to consume data, then is there any value in such a feature? It becomes more like query translator abstraction between ORMs (& non-ORMs).
Hence propose-close.

**Comment by dehghani-mehdi** [comment] 2019-08-23 04:23
@smitpatel in .Net _core_ world what if someone doesn't like/want to use EF as ORM but want to use power of LINQ in his/her application? what is better place to ask for this ability but EF? if there is other repository/project please let me know.

**Closed** 2022-10-16 14:36 UTC
Labels: closed-no-further-action, customer-reported
