### ISSUE TITLE
OnModelCreating error (CENTOS 8, .net 5, ARM64)

### ISSUE THREAD

**Issue by ElmirSecerbegovic** [dotnet/efcore#24056] opened 2021-02-03 16:03 UTC
As Roji suggested we are moving our issue from npgsql/efcore the efcore.

We have API in .net frameworks that works fine with (.net core 3.1, Centos 7, Intel x64). We have migrated our API to Centos 8, arm64 and .net 5.0.102 and start to get same errors randomly.

We are experiencing random issue "Object reference not set to an instance of an object". When we restart the service (console app) it runs fine for couple of hours and then raise the same issue.

We are using latest Npgsql.EntityFrameworkCore.PostgreSQL 5.0.2.

Error Stack
_____________________________
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.Property[TProperty](Expression`1 propertyExpression)
   at optimus_datalayer.DataModels.Optimus.<>c.<OnModelCreating>b__1148_218(EntityTypeBuilder`1 entity)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity](Action`1 buildAction)
   at optimus_datalayer.DataModels.Optimus.OnModelCreating(ModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Join[TOuter,TInner,TKey,TResult](IQueryable`1 outer, IEnumerable`1 inner, Expression`1 outerKeySelector, Expression`1 innerKeySelector, Expression`1 resultSelector)

We are attaching code cause it is pretty large. Also, as we said everythings works fine after restart for the some time period. Se, exceptions happens randomly during the running state

[onModelCreating.txt](https://github.com/dotnet/efcore/files/5919776/onModelCreating.txt)

**Comment by roji** [comment] 2021-02-03 16:07
As mentioned in https://github.com/npgsql/efcore.pg/issues/1682#issuecomment-772600510, one suspicious thing here is the possible model rebuilding - the exception comes out of OnModelCreating, but randomly and after startup.

**Comment by AndriySvyryd** [comment] 2021-02-05 20:29
We'd need a repro project to be able to investigate this, I understand that it's hard to create one as the issue only happens after some time, but we can't proceed otherwise.

**Comment by ElmirSecerbegovic** [comment] 2021-02-10 11:52
Sorry but we have a NDA for project files. However, same issue is generated where  service is restarted (CENTOS systemctl restart)

Exception has been thrown by the target of an invocation. at System.RuntimeMethodHandle.InvokeMethod(Object target,
	Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
	at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[]
	parameters, CultureInfo culture)
	at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
	at Microsoft.EntityFrameworkCore.Internal.DbSetSource.<>c__DisplayClass4_0.<CreateCore>b__0(ValueTuple`2 t)
			at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
			at Microsoft.EntityFrameworkCore.Internal.DbSetSource.CreateCore(DbContext context, Type type, String name,
			MethodInfo createMethod)
			at Microsoft.EntityFrameworkCore.Internal.DbSetSource.Create(DbContext context, Type type)
			at
			Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Internal.IDbSetCache.GetOrAddSet(IDbSetSource
			source, Type type)
			at Microsoft.EntityFrameworkCore.Internal.DbSetInitializer.InitializeSets(DbContext context)
			at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
			at optimus_datalayer.DataModels.Optimus..ctor(DbContextOptions options)
			at optimus_datalayer.OptimusDbContext.OptimusReadOnlyDbContext..ctor(DbContextOptions`1 options)
			at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean
			constructor, Boolean wrapExceptions)
			at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[]
			parameters, CultureInfo culture)
			at
			Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite
			constructorCallSite, RuntimeResolverContext context)
			at
			Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite
			callSite, TArgument argument)
			at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite
			callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine,
			RuntimeResolverLock lockType)
			at
			Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite
			singletonCallSite, RuntimeResolverContext context)
			at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite
			callSite, TArgument argument)
			at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite
			callSite, ServiceProviderEngineScope scope)
			at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.
				<RealizeService>b__0(ServiceProviderEngineScope scope)
					at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type
					serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
					at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type
					serviceType)
					at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type
					type, Type requiredBy, Boolean isDefaultParameterRequired)
					at lambda_method16(Closure , IServiceProvider , Object[] )
					at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.
						<CreateActivator>b__0(ControllerContext controllerContext)
							at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.
								<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
									at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next,
									Scope& scope, Object& state, Boolean& isCompleted)
									at
									Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
									--- End of stack trace from previous location ---
									at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.
									<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask,
										State next, Scope scope, Object state, Boolean isCompleted)
										at
										Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed
										context)
										at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next,
										Scope& scope, Object& state, Boolean& isCompleted)
										at
										Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
										--- End of stack trace from previous location ---
										at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>
											g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
											at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>
												g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger
												logger)
												at
												Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext
												context)
												at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>
													g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext
													context, Task task) Object reference not set to an instance of an
													object.<br>

**Comment by roji** [comment] 2021-02-10 12:40
@ElmirSecerbegovic we're not asking for your complete project, but rather for an isolated case that reproduces the error - this is necessary in order for us to investigate. You would typically get this by starting out with your project and stripping away irrelevant bits, until you're left with the minimum necessary to trigger the exception; if needed you can also rename type/properties to anonymize the code.

It's also possible to deliver that minimal sample via email if you don't want to share it publicly here (see my email on my github profile).

**Comment by ElmirSecerbegovic** [comment] 2021-02-11 08:41
We have created demo version from our production REPO.

https://github.com/ElmirSecerbegovic/TestIssue.git

**Comment by roji** [comment] 2021-02-15 17:43
@ElmirSecerbegovic there's nothing in your repro that looks immediately wrong - I also let an HTTP benchmarking tool bombard the application in parallel and got 100% OK results.

Can you please confirm whether you can see the issue occurring with this repro? What we need is a way to see the error that you're seeing.

PS On an unrelated note, your application doesn't make use of DI for EF context management, which is the standard thing to do ([you can see the ASP.NET tutorial on this](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio)). Similarly, there are simpler ways to manage your connection string which you can find in that tutorial.

**Comment by roji** [comment] 2021-02-15 17:44
One more thought - I'd try reproducing the issue on your side, with your production app, on a separate/new machine. There may be something environmental or setup-related with your machine that's causing this.

**Comment by ElmirSecerbegovic** [comment] 2021-02-16 08:01
We also believe that issues is couse different environment. We are using Centos 8.2 on arm64 (AWS Graviton processors). While we was on Centos 7 and linux x64 processor same code was running fine.

**Comment by roji** [comment] 2021-02-16 08:12
@ElmirSecerbegovic this could conceivably be a runtime issue related to ARM somehow - though it's odd that the stack traces are purely managed (no visible native issue). Can you please try to put together a console program which reproduces this, by looping and running the same logic again and again (possibly over multiple tasks/threads)? Once we have such a program, I can confirm the issue on my side and submit it to the runtime team for investigation...

**Comment by ElmirSecerbegovic** [comment] 2021-02-16 12:36
Also, if we upload the new versions of files and on systemctl restart app.service we are getting next error

System.NullReferenceException: Object reference not set to an instance of an object.\n   
at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrAccessorFactory`1.Create(MemberInfo memberInfo, IPropertyBase propertyBase)\n   
at Microsoft.EntityFrameworkCore.Internal.DbSetFinder.<>c__DisplayClass2_0.<FindSetsNonCached>b__2(PropertyInfo p)\n   
at System.Linq.Enumerable.SelectIPartitionIterator`2.LazyToArray()\n   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToArray()\n   
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)\n   
at Microsoft.EntityFrameworkCore.Internal.DbSetInitializer.InitializeSets(DbContext context)\n   
at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)\n   
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)\n   
at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\n   
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)\n   
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)\n   
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)\n   
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)\n   
at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)\n   
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)\n   
at lambda_method4838(Closure , IServiceProvider , Object[] )\n   
at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)\n   
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location ---\n   
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   
at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


when we again restart with systemctl restart app.service everything is running fine for some time.

It seems like CENTOS and arm64 processor keeping files running even doe we stoped them with systemctl command

**Comment by ajcvickers** [comment] 2021-03-01 16:53
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:21 UTC
Labels: closed-could-not-reproduce, customer-reported
