### ISSUE TITLE
Inheritance creating duplicate foreign keys and indexes

### ISSUE THREAD

**Issue by GeorgePetri** [dotnet/efcore#14100] opened 2018-12-06 10:39 UTC
I have a TPH that looks like this:
```csharp
    [Table("Entity")]
    public class BaseEntity
    {
        [Key]
        public Guid Guid { get; set; }
        
        public string Value { get; set; }
    }
```
```csharp
    [Table("Entity")]
    public class ChildEntityOne : BaseEntity
    {
        public string ValueOne { get; set; }

        [ForeignKey(nameof(OtherEntityId))]
        public OtherEntity OtherEntity { get; set; }
        
        [Column(nameof(OtherEntityId))]
        public Guid? OtherEntityId { get; set; }
    }
```
```csharp
    [Table("Entity")]
    public class ChildEntityTwo : BaseEntity
    {
        public string ValueTwo { get; set; }
        
        [ForeignKey(nameof(OtherEntityId))]
        public OtherEntity OtherEntity { get; set; }
        
        [Column(nameof(OtherEntityId))]
        public Guid? OtherEntityId { get; set; }
    }
```
```csharp
    [Table("Entity")]
    public class ChildEntityThree : BaseEntity
    {
        public string ValueThree { get; set; }
    }
```
```csharp
    [Table(nameof(OtherEntity))]
    public class OtherEntity
    {
        [Key]
        public Guid Guid { get; set; }
        
        public int SomeData { get; set; }
    }
```

Both ChildEntityOne and two have a foreign key to OtherEntity and I want them to share the same table column. The Issue is that in Sql Server, it generates the same foreign key multiple times.
![efbug](https://user-images.githubusercontent.com/11257358/49578757-239e9f80-f953-11e8-882b-cf40c5ad8af5.PNG)

I have a project that displays the Issue [here](https://github.com/GeorgePetri/EFBug), just change the connection string. It happens in EF Core 2.2.

Is there a workaround for this issue in the meantime?

**Comment by DownGoat** [comment] 2018-12-06 13:16
Also experiencing the same problem with a similar setup after upgrade to 2.2.0. This problem persists on any machine that seems to have installed the SDK, even after downgrading the solution packages to 2.1.4

**Comment by ajcvickers** [comment] 2018-12-07 21:02
Duplicate of #12963

**Closed** 2022-10-16 13:43 UTC
Labels: customer-reported
