### ISSUE TITLE
Cache the full list some properties are populated from in the complex properties of an object

### ISSUE THREAD

**Issue by DavidThielen** [dotnet/efcore#33459] opened 2024-04-02 18:20 UTC
I have several models that have a `List<Tag>` property of the tags associated with that model. There are 3 other lists like this. The full list of all tags (and the other 3 models) rarely changes. Maybe twice/month.

So it would be great if there was a way to:
1. Create a DbContext
2. Read in the full lists of these 4 models using the DbContext
3. Any subsequent queries by this DbContext, using split queries, will pull from these existing lists rather than reading again, from the DB, the subset of the lists for the object(s) just queried.
4. Keep this DbContext for future use, in a singleton service.

This obviously would only work for a non-tracking DbContext. But when displaying a lot of data, that generally is from a non-tracking query. And while it would still have 2 query the join tables, it would not have to query the `Tag`, etc. tables.

This works (I tested it). But I view it as a bad idea if this kind of use is not supported/suggested. Instead every single discussion of the DbContext says don't keep them around. Create them, use them, dispose them. Which 99% of the time is very good advice.

But I think officially supporting this use case would enable safely adding a nice optimization.

**Comment by roji** [comment] 2024-04-02 20:46
@DavidThielen I'm not sure I understand: would your singleton DbContext be used concurrently as multiple e.g. web requests come in? If so, that doesn't work since DbContext isn't thread-safe; you cannot use the same DbContext instance concurrently from more than one thread.

I'm also not quite understanding - if you use non-tracking queries, then the tags wouldn't be tracked (e.g. cached), and each query would retrieve them again from the database, which seems to defeat the whole purpose of the scheme.

If what you want is to cache, I'd generally advise doing that outside of EF, i.e. just do a query at startup (or whenever) and read your tags into some singleton service (which no longer has anything to do with EF), and then consult them there. Otherwise, you'll have to provide a bit more context on what you're doing there.

**Comment by roji** [comment] 2024-04-02 21:14
Right, so as I proposed above, why not just load those lists into memory, i.e. have them as actual `List<string>` on some singleton object, and then use them in your program as usual, possibly doing a join (client-side) with data fetched with EF?

**Comment by DavidThielen** [comment] 2024-04-02 21:18
@roji I may not be understanding your suggestion. Take the example of `User.Tags`, that has 4 tags in the list (the tags this user is interested in). While all the repository of all the tags does not change, 
- The users will somewhat regularly change what subset of the list is in their property.
- This user list property is used in numerous pages, such as to only show the user events with the same tags.

So I do need that list that is unique to each user.

??? - thanks - dave

**Comment by roji** [comment] 2024-04-02 21:34
If each user has a different list of tags, it sounds like you need to load them from the database no? Unless you're proposing to cache the tags for all your users in memory (e.g. by having a .NET Dictionary that maps users to their tags, which you load once)?

I'm still not quite clear what it is exactly that you're trying to solve here.

**Comment by ajcvickers** [comment] 2024-04-03 08:26
This seems basically a duplicate of #7586.

**Closed** 2024-04-08 11:10 UTC
Labels: type-enhancement, closed-duplicate, customer-reported
