### ISSUE TITLE
Entity Framework Core does not support ambient transactions

### ISSUE THREAD

**Issue by aiyowa** [dotnet/efcore#10628] opened 2018-01-02 06:42 UTC
When using a transaction scope around Microsoft.EntityFrameworkCore.SqlServer 2.0.1, I get an exception:

```
Warning as error exception for warning 'Microsoft.EntityFrameworkCore.Database.Transaction.AmbientTransactionWarning': An ambient transaction has been detected. Entity Framework Core does not support ambient transactions. See http://go.microsoft.com/fwlink/?LinkId=800142 To suppress this Exception use the DbContextOptionsBuilder.ConfigureWarnings API. ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
```

Is there any plan for support TransactionScope with EntityFramework Core?

**Comment by ajcvickers** [comment] 2018-01-02 19:11
Duplicate of #5595

**Closed** 2022-10-16 12:04 UTC
Labels: closed-duplicate
