### ISSUE TITLE
GroupBy forces local evaluation if selecting navigation property as key

### ISSUE THREAD

**Issue by sandersaares** [dotnet/efcore#14530] opened 2019-01-28 11:37 UTC
If I GroupBy `orderRow.Product.Id` everything is fine. But if I GroupBy `orderRow.Product` I get client evaluation.

This is undesirable. I would expect EF to figure out the right thing to do here.

Presumably, this "right thing to do" might be to use `orderRow.Product.Id` internally and later do whatever joins/etc are needed to achieve the final query that references members of the grouping key entity type.

```
Unhandled Exception: System.InvalidOperationException: Error generated for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'GroupBy([orderRow.Product], [orderRow])' could not be translated and will be evaluated locally.'. This exception can be suppressed or logged by passing event ID 'RelationalEventId.QueryClientEvaluationWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, TParam arg, Exception exception)
   at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.QueryClientEvaluationWarning(IDiagnosticsLogger`1 diagnostics, QueryModel queryModel, Object queryModelElement)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.LiftSubQuery(IQuerySource querySource, SubQueryExpression subQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.CompileMainFromClauseExpression(MainFromClause mainFromClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ConsoleApp16.Program.Main(String[] args) in C:\Source\ConsoleApp16\ConsoleApp16\Program.cs:line 16
```

### Steps to reproduce

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Debug;
using System;
using System.Linq;

namespace ConsoleApp16
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            using (var dc = new DataContext())
            {
                var query = dc.Order
                    .GroupBy(orderRow => orderRow.Product, (product, orders) => new
                    {
                        Product = product,
                        MaxPrice = orders.Select(order => order.Price).Max()
                    })
                    .ToArray();

                foreach (var result in query)
                    Console.WriteLine($"{result.Product.Name} MaxPrice {result.MaxPrice}");

/* For comparison, this works but is not quite what I want:

                var query = dc.Order
                    .GroupBy(orderRow => orderRow.Product.Id, (productId, orders) => new
                    {
                        ProductId = productId,
                        MaxPrice = orders.Select(order => order.Price).Max()
                    })
                    .ToArray();

                foreach (var result in query)
                    Console.WriteLine($"{result.ProductId} MaxPrice {result.MaxPrice}");
*/
            }
        }
    }

    public class ProductRow
    {
        public Guid Id { get; set; }

        public string Name { get; set; }
    }

    public class OrderRow
    {
        public Guid Id { get; set; }

        public Guid ProductId { get; set; }
        public ProductRow Product { get; set; }

        public double Price { get; set; }
    }

    public class DataContext : DbContext
    {
        public DbSet<OrderRow> Order { get; set; }
        public DbSet<ProductRow> Product { get; set; }

        public DataContext()
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.ConfigureWarnings(warnings =>
            {
                warnings.Throw(RelationalEventId.QueryClientEvaluationWarning);
            });

            optionsBuilder.EnableSensitiveDataLogging();
            optionsBuilder.UseLoggerFactory(MyLoggerFactory);

            if (!optionsBuilder.IsConfigured)
                optionsBuilder.UseSqlServer("Server=(local);Database=EFCore_Issue_Repro;Trusted_Connection=True;");
        }

        public static readonly LoggerFactory MyLoggerFactory = new LoggerFactory(new[]
        {
            new DebugLoggerProvider((category, level) => true)
        });

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var fooId = Guid.NewGuid();
            var barId = Guid.NewGuid();

            modelBuilder.Entity<ProductRow>()
                .HasData(
                    new ProductRow
                    {
                        Id = fooId,
                        Name = "foo"
                    },
                    new ProductRow
                    {
                        Id = barId,
                        Name = "bar",
                    }
                );

            modelBuilder.Entity<OrderRow>()
                .HasData(
                    new OrderRow
                    {
                        Id = Guid.NewGuid(),
                        ProductId = fooId,
                        Price = 100
                    },
                    new OrderRow
                    {
                        Id = Guid.NewGuid(),
                        ProductId = fooId,
                        Price = 222
                    },
                    new OrderRow
                    {
                        Id = Guid.NewGuid(),
                        ProductId = fooId,
                        Price = 333
                    },
                    new OrderRow
                    {
                        Id = Guid.NewGuid(),
                        ProductId = fooId,
                        Price = 444
                    },
                    new OrderRow
                    {
                        Id = Guid.NewGuid(),
                        ProductId = barId,
                        Price = 555
                    },
                    new OrderRow
                    {
                        Id = Guid.NewGuid(),
                        ProductId = barId,
                        Price = 123
                    }
                );
        }
    }
}
```

### Further technical details

EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1809
IDE: Visual Studio 2017 15.9.5

**Comment by sandersaares** [comment] 2019-01-28 11:52
I suppose the above query structure of `.GroupBy().ToArray()` might be a bit unrealistic and potentially not supported by design? Just in case, I provide alternative formation here that is more realistic:

```c#
var query = dc.Order
    .GroupBy(orderRow => orderRow.Product, (product, orders) => new
    {
        Product = product,
        MaxPrice = orders.Select(order => order.Price).Max()
    })
    .Select(group =>
        new
        {
            group.MaxPrice,
            group.Product.Name
        })
    .ToArray();

foreach (var result in query)
    Console.WriteLine($"{result.Name} MaxPrice {result.MaxPrice}");
```

**Comment by REscobar** [comment] 2019-01-28 17:44
I believe this is by design, since sql can only group by using scalars, to properly evaluate this, the generated sql should expand all the properties of the navigation into the group by clause, but then again I don't know if you redefine the equality of the of the class that backs the navigation, you could get different results wether the linq is transalate to sql or evaluated in the application.

For example

```csharp
var query = dc.Order
    .AsEnumerable()
    .GroupBy(orderRow => orderRow.Product, (product, orders) => new
    {
        Product = product,
        MaxPrice = orders.Select(order => order.Price).Max()
    })
    .Select(group =>
        new
        {
            group.MaxPrice,
            group.Product.Name
        })
    .ToArray()
```

Could give you a different result if you redefine the `Equals` and `GetHash`.

You can run the following in LinqPad or similar to see how overriding this functions could affect the `GroupBy` result

```csharp
void Main()
{
	new []
	{
		new Poco1
		{
			Prop1 = "Val1"
		},
		new Poco1
		{
			Prop1 = "Val2"
		},
		new Poco1
		{
			Prop1 = "Val3"
		}
	}
	.GroupBy(x => x)
	.Dump("Overriden Hash and Equals");
	
	new []
	{
		new Poco2
		{
			Prop1 = "Val1"
		},
		new Poco2
		{
			Prop1 = "Val2"
		},
		new Poco2
		{
			Prop1 = "Val3"
		}
	}
	.GroupBy(x => x)
	.Dump("No overrides");
}

class Poco1
{
	public string Prop1 { get; set; }
	
	public override bool Equals(object other)
	{
		return true;
	}
	public override int GetHashCode()
	{
		return 0;
	}
}

class Poco2
{
	public string Prop1 { get; set; }
}

```
Produces the following output:


![image](https://user-images.githubusercontent.com/348416/51855088-fa1a4880-22f1-11e9-8ff8-1926b782fa08.png)

**Comment by smitpatel** [comment] 2019-01-28 18:11
Duplicate of #13761

**Closed** 2022-10-16 13:49 UTC
Labels: closed-duplicate, customer-reported
