### ISSUE TITLE
IProperty.GetColumnName(in StoreObjectIdentifier) returns NULL

### ISSUE THREAD

**Issue by alexanderyaremchuk** [dotnet/efcore#24367] opened 2021-03-10 14:38 UTC
1. Create an instance of StoreObjectIdentifier by passing in tableName and schema parameters.
2. When invoking IProperty.GetColumnName(storeObjectIdentifierInstance) returns NULL .
I get the correct value if I pass in NULL for schema parameter during step 1.

**Comment by AndriySvyryd** [comment] 2021-03-11 02:43
Could you provide a small repro project that shows the issue?

**Comment by ajcvickers** [comment] 2021-03-19 16:31
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:27 UTC
Labels: closed-could-not-reproduce, customer-reported
