### ISSUE TITLE
Getting "An attempt was made to lazy-load navigation property" error when using AsNoTracking despite using Include to eager fetch children

### ISSUE THREAD

**Issue by arnileibovits** [dotnet/efcore#21593] opened 2020-07-11 20:40 UTC
I'm performing a query with lazy-loading proxies enabled and using AsNoTracking. I'm using Include to eagerly load a navigation property (a collection). Even though the data is actually fetched from the database (can be seen in SQL Profiler), I'm getting the error **"An attempt was made to lazy-load navigation property..."**.

Note that the collection property is part of an **abstract class**.

Interestingly, when lazy-loading is turned off, too many child entities are loaded (see example code).

Background: The reason for wanting to have lazy-loading proxies enabled is to get an exception when a child entity was **not** eagerly loaded. This would be the expected behavior. If proxies were not enabled and you forgot to add an Include, you would just get an empty collection without any errors.

```
System.InvalidOperationException: Error generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.DetachedLazyLoadingWarning': An attempt was made to lazy-load navigation property 'GrandChildren' on detached entity of type 'ConcreteChildProxy'. Lazy-loading is not supported for detached entities or entities that are loaded with 'AsNoTracking()'. This exception can be suppressed or logged by passing event ID 'CoreEventId.DetachedLazyLoadingWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`2.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, TParam1 arg1, TParam2 arg2)
   at Microsoft.EntityFrameworkCore.Diagnostics.CoreLoggerExtensions.DetachedLazyLoadingWarning(IDiagnosticsLogger`1 diagnostics, DbContext context, Object entityType, String navigationName)
   at Microsoft.EntityFrameworkCore.Internal.LazyLoader.ShouldLoad(Object entity, String navigationName, NavigationEntry& navigationEntry)
   at Microsoft.EntityFrameworkCore.Internal.LazyLoader.Load(Object entity, String navigationName)
   at Microsoft.EntityFrameworkCore.Proxies.Internal.LazyLoadingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ConcreteChildProxy.get_GrandChildren()
```

### Steps to reproduce
Link to code example: https://github.com/arnileibovits/efcore.issue.21593

### Further technical details

EF Core version: 3.1.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.3

**Comment by smitpatel** [comment] 2020-07-11 20:43
Duplicate of #19851?

**Comment by arnileibovits** [comment] 2020-07-11 21:10
Since #19851 was about 3.1.1, but the issue is still present in 3.1.5 (also in 5.0.0-preview.6.20312.4), I feel this should be worthy of attention. Or do I understand that this is planned to be fixed in 5.0.0-preview7?

Also noteworthy is the fact then when lazy-loading is turned off, **duplicate** child entities are loaded if a certain way is used for Select() (see example code).

**Comment by smitpatel** [comment] 2020-07-11 21:18
First error is definitely duplicate of #19851 , The navigation exists on base type which is abstract but the derived type is concrete and actually being loaded so it was not setting IsLoaded correctly.

Second may need more investigation to see what results are coming back. It does have overlap with https://github.com/dotnet/efcore/issues/15783

**Comment by ajcvickers** [comment] 2020-07-13 20:00
@smitpatel Second part still fails on latest daily build. Using `AsNoTrackingWithIdentityResolution` results in the correct behavior.

**Comment by smitpatel** [comment] 2020-07-13 21:08
Duplicate of #15783

**Closed** 2022-10-16 18:33 UTC
Labels: closed-duplicate, customer-reported
