### ISSUE TITLE
Query: Translate Array.Any

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#9419] opened 2017-08-15 18:10 UTC
```
var query = db.Blogs.Where(x => (new int[] { 1, 2, 3 }).Any(I => I == x.Id)).ToList();
```
Causes client eval
```
 The LINQ expression 'where {from Int32 I in value(System.Int32[]) where ([I] == [x].Id) select [I] => Any()}' could not be translated and will be evaluated locally.
```

**Comment by maumar** [comment] 2017-08-15 18:21
dupe of https://github.com/aspnet/EntityFramework/issues/6660

**Closed** 2022-10-16 11:15 UTC
