### ISSUE TITLE
Add more Translations for DateTime

### ISSUE THREAD

**Issue by DominikPf** [dotnet/efcore#10887] opened 2018-02-06 08:40 UTC
The following Code cannot be translated with the SqLite Provider.
Everything works fine with SqlServer

`.Where(x => x.Expiration < DateTime.UtcNow)`

### Warning:
```
{
    "@t": "2018-02-05T08:43:20.2806558Z",
    "@mt": "The LINQ expression '{expression}' could not be translated and will be evaluated locally.",
    "@m": "The LINQ expression 'where ([x].Expiration < Convert(DateTime.UtcNow, Nullable`1))' could not be translated and will be evaluated locally.",
    "@i": "245bba28",
    "@l": "Warning",
    "expression": "where ([x].Expiration < Convert(DateTime.UtcNow, Nullable`1))",
    "EventId": {
        "Id": 20500,
        "Name": "Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning"
    },
    "SourceContext": "Microsoft.EntityFrameworkCore.Query",
    "Scope": ["Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor"],
    "Environment": "Production",
    "Application": "***.Identity.Server"
}
```

### Steps to reproduce
```
var expired = context.PersistedGrants
   .Where(x => x.Expiration.HasValue && x.Expiration.Value < DateTime.UtcNow)
   .OrderBy(x => x.Key)
   .Take(_options.TokenCleanupBatchSize)
   .ToArray();
```
```
    public class PersistedGrant
    {
        public string Key { get; set; }
        public string Type { get; set; }
        public string SubjectId { get; set; }
        public string ClientId { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime? Expiration { get; set; }
        public string Data { get; set; }
    }
```

https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/1d7a862903b82c08f28d0787b1dafe1590e2f526/src/IdentityServer4.EntityFramework/TokenCleanup.cs#L113

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 1709
IDE: Visual Studio Professional 2017 15.5.5

**Comment by smitpatel** [comment] 2018-02-06 22:14
Fixed in https://github.com/aspnet/EntityFrameworkCore/pull/10528

Sqlite did not have translation specified for `DateTime.UtcNow` which has changed. It should be able to translate it correctly.

**Comment by smitpatel** [comment] 2018-02-06 22:15
Duplicate of #4108

**Closed** 2022-10-16 12:08 UTC
Labels: closed-duplicate
