### ISSUE TITLE
Migrations: CHECK Discriminator Values

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#2594] opened 2015-07-10 17:18 UTC
We could add a `CHECK` constraint to the discriminator column to ensure it's one expected by your model.

**Comment by roji** [comment] 2020-05-15 15:42
Duplicate of https://github.com/efcore/EFCore.CheckConstraints/issues/2#issuecomment-628914348

**Closed** 2022-10-16 09:02 UTC
Labels: type-enhancement, closed-external
