### ISSUE TITLE
The instance of entity type ClassModel cannot be tracked because another instance with the same key value for {ID} is already being tracked.

### ISSUE THREAD

**Issue by deanilvincent** [dotnet/efcore#10245] opened 2017-11-09 09:05 UTC
Good day, 

I'm having a problem in updating my item. Here's the exception error
```
Exception message:
"The instance of entity type 'Items' cannot be tracked because another instance with the same key value for {'ItemId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values."
```
**Code Details**
My Items and ItemCategories Class Model
```
public class Items
{
        [Key]
        public int ItemId { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public int ItemCatId { get; set; }
        public virtual ItemCategories ItemCategories { get; set; }
}

public class ItemCategories
{
        [Key]
        public int ItemCatId { get; set; }

        public string Name { get; set; }
}
```
My DbContext
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
         modelBuilder.Entity<Items>().ToTable("Items");
         modelBuilder.Entity<ItemCategories>().ToTable("ItemCategories");
}

public DbSet<POSRestaurant.Models.ItemCategories> ItemCategories { get; set; }

public DbSet<POSRestaurant.Models.Items> Items { get; set; }
```
And lastly my repository codes inside the update
```
context.Update(items);
await context.SaveChangesAsync();
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

Thank you in advance

**Comment by ajcvickers** [comment] 2017-11-09 16:47
@deanilvincent There isn't enough information here for us to be able to reproduce what you are seeing. Can you please post a full code listing or project that reproduces the issue?

**Comment by ajcvickers** [comment] 2017-11-17 19:13
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:57 UTC
Labels: closed-could-not-reproduce
