### ISSUE TITLE
System.InvalidOperationException "instance of entity type 'A' is marked as 'Modified', but an instance of entity type 'B' is marked as 'Added' and both are mapped to the same row." when modify OwnsOne configured ValueObject with nullable field.

### ISSUE THREAD

**Issue by goncharov-do** [dotnet/efcore#18365] opened 2019-10-14 14:32 UTC
I am trying to modify ValueObject (OwnsOne) with nullable fields, but can't because it failed on SaveChanges with 

```
System.InvalidOperationException: The entity of type 'ValueObject2' is sharing the table 'TestEntities' with entities of type 'TestEntity', but there is no entity of this type with the same key value that has been marked as 'Added'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values.
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.Validate(Dictionary`2 sharedTablesCommandsMap)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.CreateModificationCommands(IList`1 entries, IUpdateAdapter updateAdapter, Func`1 generateParameterName)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.BatchCommands(IList`1 entries, IUpdateAdapter updateAdapter)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at EfCoreV3Bugs.Program.Main(String[] args) in C:\Projects\EfCore3VOBugs\EfCoreV3Bugs\Program.cs:line 45
```

### Steps to reproduce
You can find my sample project in the following repository:
https://github.com/goncharov-do/EfCore3VOBugs

It is just console app which creates new database on local SqlServer ( ".\" ), removes 
database "EfCoreV3Bugs", creates it, migrate, inserts test entity, and tries to modify a nullable field of ValueObject.

### Further technical details
.Net core 3.0
Microsoft.EntityFrameworkCore v3.0.0
Microsoft.EntityFrameworkCore.SqlServer v3.0.0

Please let me know if need more details.

**Comment by AndriySvyryd** [comment] 2019-10-14 15:37
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/17935

**Closed** 2022-10-16 14:49 UTC
Labels: closed-duplicate, customer-reported
