### ISSUE TITLE
Add support StandardDeviation query

### ISSUE THREAD

**Issue by ldqk** [dotnet/efcore#28385] opened 2022-07-07 06:56 UTC
Add support StandardDeviation query such as Max(),Min(),Sum() etc...

eg:
```charp
dbset.Scores.Select(e=>e.English).StandardDeviation();
dbset.Scores.StandardDeviation(e=>e.English);
```

**Comment by KimXing666** [comment] 2022-07-07 07:03
why not support for StandardDeviation queries such as Max(), Min(), and Sum() in the latest of EfCore version?
![image](https://user-images.githubusercontent.com/104540807/177712286-7a441624-1bcc-49ec-9a42-17cb1940c2a4.png)

**Comment by xingwen1987** [comment] 2022-07-07 07:05
why not support for StandardDeviation queries such as Max(), Min(), and Sum() in the latest of EfCore version?
![image](https://user-images.githubusercontent.com/15207100/177712539-a01f925e-2124-4855-84a7-dd2105262c57.png)

**Comment by roji** [comment] 2022-07-07 08:07
Duplicate of #28104

**Comment by roji** [comment] 2022-07-07 08:07
This is being implemented for .NET 7.0 (in #28110).

**Closed** 2022-07-07 08:25 UTC
Labels: customer-reported
