### ISSUE TITLE
Enum seed data converted to string yields UPDATE every migration

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#18728] opened 2019-11-02 21:54 UTC
``` csharp
enum Days : long
{
    Sun,
    Mon,
    Tue,
    Wed,
    Thu,
    Fri,
    Sat
}

class EntityWithEnumType
{
    public int Id { get; set; }
    public Days Day { get; set; }
}
```
``` csharp
modelBuilder.Entity<EntityWithEnumType>(
    eb =>
    {
        eb.Property(e => e.Day).HasDefaultValue(Days.Wed)
            .HasConversion(v => v.ToString(), v => (Days)Enum.Parse(typeof(Days), v));
        eb.HasData(
            new { Id = 1, Day = Days.Fri });
    });
```

``` sql
UPDATE [EntityWithEnumType]
SET [Day] = 'Fri'
WHERE [Id] = 1
```

**Comment by AndriySvyryd** [comment] 2019-11-12 13:16
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/13776

**Closed** 2022-10-16 14:53 UTC
