### ISSUE TITLE
strange behavior ordering a query

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/efcore#3918] opened 2015-11-28 11:28 UTC
I have this query inside an action

```
            var clienti = db.Fatture
                .OrderByDescending(cli => cli.DataFattura).ThenByDescending(cli => cli.NumFattura)
                .Include(cli => cli.Cliente).Include(cli => cli.Righe)
                .Take(recNum)
                .ToList();
            return clienti.Select( cli => new FatturaVm {
                FatturaNo = cli.FatturaNo,
                Cliente = cli.Cliente.Descrizione,
                Data = cli.DataFattura.Value.ToString("dd/MM/yyyy"),
                Importo = cli.Righe.Sum( rg => rg.Importo.Value),
                NumeroDocumento = cli.NumFattura.Value + "/" + cli.Anno.Value
            }).ToList();
```

First the data are extracted and after a model class is filled extracting some fields from the invoice, the name of the customer, and the sum of the values from the rows.
I found a strange thing: if I add the OrderByDescending the invoices are returned with an empty list of the rows, but if I remove the ordering the rows in another order are returned with the details.
Am I missing something?

Looking in the vs log I see that executes 2 queries:

```
SELECT TOP(30) [cli].[FatturaNo], [cli].[Anno], [cli].[ClienteNo], [cli].[DataFattura], [cli].[DataScadenza], [cli].[Note], [cli].[NumFattura], [cli].[Saldata], [c].[ClienteNo], [c].[Attivo], [c].[Colore], [c].[Descrizione], [c].[Note], [c].[Operativo]
FROM [Fatture] AS [cli]
INNER JOIN [Clienti] AS [c] ON [cli].[ClienteNo] = [c].[ClienteNo]
ORDER BY [cli].[DataFattura] DESC, [cli].[NumFattura] DESC, [cli].[FatturaNo]

and 

SELECT [f].[FatturaRigaNo], [f].[CommessaNo], [f].[Descrizione], [f].[FatturaNo], [f].[Importo]
FROM [Fatture_Righe] AS [f]
INNER JOIN (
    SELECT DISTINCT TOP(30) [cli].[DataFattura], [cli].[NumFattura], [cli].[FatturaNo]
    FROM [Fatture] AS [cli]
) AS [cli] ON [f].[FatturaNo] = [cli].[FatturaNo]
ORDER BY [cli].[DataFattura] DESC, [cli].[NumFattura] DESC, [cli].[FatturaNo]
```

changing the position of the ordering clause in the command is not of help

**Comment by jparish9** [comment] 2015-12-07 17:14
I'm seeing the same thing, using rc1.  My minimal case is an `.Include` and a `.First` with `.OrderByDescending`.  For example,

```c#
Blog blog = _dbContext.Blogs
   .Include(b => b.Posts)
   .OrderBy(b => b.Title).First();
```

generates sql:

```sql
SELECT TOP(1) [b].[BlogId], [b].[Title]
FROM [Blog] AS [b]
ORDER BY [b].[Title], [b].[BlogId]

SELECT [p].[PostId], [p].[BlogId], [p].[PostText]
FROM [Post] AS [p]
INNER JOIN (
    SELECT DISTINCT TOP(1) [b].[Title], [b].[BlogId]
    FROM [Blog] AS [b]
) AS [b] ON [p].[BlogId] = [b].[BlogId]
ORDER BY [b].[Title], [b].[BlogId]
```

which correctly populates the `Posts` collection, but 

```c#
Blog blog = _dbContext.Blogs
   .Include(b => b.Posts)
   .OrderByDescending(b => b.Title).First();
```

Generates:

```sql
SELECT TOP(1) [b].[BlogId], [b].[Title]
FROM [Blog] AS [b]
ORDER BY [b].[Title] DESC, [b].[BlogId]

SELECT [p].[PostId], [p].[BlogId], [p].[PostText]
FROM [Post] AS [p]
INNER JOIN (
    SELECT DISTINCT TOP(1) [b].[Title], [b].[BlogId]
    FROM [Blog] AS [b]
) AS [b] ON [p].[BlogId] = [b].[BlogId]
ORDER BY [b].[Title] DESC, [b].[BlogId]
```

which gets the `Posts` for the wrong `Blog` and leaves an empty but non-null `Posts` collection.  The subquery seems suspect, as
```sql
SELECT DISTINCT TOP(1) [b].[Title], [b].[BlogId]
    FROM [Blog] AS [b]
```
is not using the same ordering as given for the parent, so it retrieves the wrong `Blog`.

**Comment by rowanmiller** [comment] 2015-12-08 20:20
Duplicate of https://github.com/aspnet/EntityFramework/issues/3732

**Closed** 2022-10-16 09:18 UTC
