### ISSUE TITLE
dotnet ef migrations script generation ArgumentNullException: Value cannot be null (Parameter 'o')

### ISSUE THREAD

**Issue by davidyee** [dotnet/efcore#20807] opened 2020-05-01 18:23 UTC
I'm testing out DotNet 5 Preview 3 (`Microsoft.EntityFrameworkCore 5.0.0-preview.3.20181.2`) after upgrading from DotNet Core 2.2. The project itself appears to work fine; however, I noticed that generating migrations scripts with the latest EF Core Tool (5.0.0-preview.3.20181.2) results in the following runtime error:

```csharp
System.ArgumentNullException: Value cannot be null. (Parameter 'o')
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommandListBuilder.Append(Object o)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.ColumnDefinition(String schema, String table, String name, ColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.ColumnDefinition(String schema, String table, String name, ColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.ColumnDefinition(AddColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(AddColumnOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(AddColumnOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__71_0(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateScript(String fromMigration, String toMigration, Boolean idempotent)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.ScriptMigration(String fromMigration, String toMigration, Boolean idempotent, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigrationImpl(String fromMigration, String toMigration, Boolean idempotent, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Value cannot be null. (Parameter 'o')
```

This error appears to occur on the first migration encountered (it doesn't matter if I specify a later migration range to generate as the same error occurs).

### Initial Investigation

I'm not familiar with the EF Core codebase so I don't know if any of the following means anything or not:

I attempted to attach to a debug process in VS 2019 and it would appear that in `MigrationsSqlGenerator.cs#ColumnDefinition` that the `columnType` variable is set to null when it is passed to the builder:
https://github.com/dotnet/efcore/blob/55269770c4e757617e1bab7d81c3e1159e0c8401/src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs#L1365

![MigrationCommandListBuilder.cs debug](https://i.imgur.com/UURGdnU.png)

`MigrationCommandListerBuilder#Append` then throws the exception because it was passed a null object o:
https://github.com/dotnet/efcore/blob/bdaeee111bf81d26c2e4f52749b93d8b687895a6/src/EFCore.Relational/Migrations/MigrationCommandListBuilder.cs#L74

![MigrationsSqlGenerator.cs debug](https://i.imgur.com/qYkAI2x.png)

The above suggests to me that the migration tool is getting stuck processing the column type for the migration. The one referenced in the above image happens to be the first statement in the `Up` of the first migration file:

```csharp
using System;
using System.IO;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace AcmeCompany.AdventureWorks.Data.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AspNetRoles",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(maxLength: 256, nullable: true),
                    NormalizedName = table.Column<string>(maxLength: 256, nullable: true),
                    ConcurrencyStamp = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetRoles", x => x.Id);
                });
                
            // more migrations ...
            
        }
        
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // down migrations ...
        }
        
    }
}
```

### Workaround

Since we have our project split into a server (DotNet Core App) and a data project (DbContext with POCO files) I noticed that I could downgrade the data project to DotNet Core 3.1 (netcoreapp3.1) and the migration script generation worked as expected.

#### Output with Error

The following is output on my local dev system using the dotnet-ef CLI tool:

```csharp
PS C:\git\set> dotnet tool update --global dotnet-ef --version 5.0.0-preview.3.20181.2
Tool 'dotnet-ef' was reinstalled with the latest stable version (version '5.0.0-preview.3.20181.2').
PS C:\git\set> dotnet ef migrations script -i -o C:\migrate.sql --project AcmeCompany.AdventureWorks.Data\AcmeCompany.AdventureWorks.Data.csproj -v
Using project 'AcmeCompany.AdventureWorks.Data\AcmeCompany.AdventureWorks.Data.csproj'.
Using startup project 'AcmeCompany.AdventureWorks.Data\AcmeCompany.AdventureWorks.Data.csproj'.
Writing 'AcmeCompany.AdventureWorks.Data\obj\AcmeCompany.AdventureWorks.Data.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\dyee\AppData\Local\Temp\tmp6476.tmp /verbosity:quiet /nologo AcmeCompany.AdventureWorks.Data\AcmeCompany.AdventureWorks.Data.csproj
Writing 'AcmeCompany.AdventureWorks.Data\obj\AcmeCompany.AdventureWorks.Data.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\dyee\AppData\Local\Temp\tmp67D2.tmp /verbosity:quiet /nologo AcmeCompany.AdventureWorks.Data\AcmeCompany.AdventureWorks.Data.csproj
Build started...
dotnet build AcmeCompany.AdventureWorks.Data\AcmeCompany.AdventureWorks.Data.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.27
Build succeeded.
dotnet exec --depsfile C:\git\set\AcmeCompany.AdventureWorks.Data\bin\Debug\netcoreapp5.0\AcmeCompany.AdventureWorks.Data.deps.json --additionalprobingpath C:\Users\dyee\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\git\set\AcmeCompany.AdventureWorks.Data\bin\Debug\netcoreapp5.0\AcmeCompany.AdventureWorks.Data.runtimeconfig.json C:\Users\dyee\.dotnet\tools\.store\dotnet-ef\5.0.0-preview.3.20181.2\dotnet-ef\5.0.0-preview.3.20181.2\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll migrations script -i -o C:\migrate.sql --assembly C:\git\set\AcmeCompany.AdventureWorks.Data\bin\Debug\netcoreapp5.0\AcmeCompany.AdventureWorks.Data.dll --startup-assembly C:\git\set\AcmeCompany.AdventureWorks.Data\bin\Debug\netcoreapp5.0\AcmeCompany.AdventureWorks.Data.dll --project-dir C:\git\set\AcmeCompany.AdventureWorks.Data\ --language C# --working-dir C:\git\set --verbose --root-namespace AcmeCompany.AdventureWorks.Data
Using assembly 'AcmeCompany.AdventureWorks.Data'.
Using startup assembly 'AcmeCompany.AdventureWorks.Data'.
Using application base 'C:\git\set\AcmeCompany.AdventureWorks.Data\bin\Debug\netcoreapp5.0'.
Using working directory 'C:\git\set\AcmeCompany.AdventureWorks.Data'.
Using root namespace 'AcmeCompany.AdventureWorks.Data'.
Using project directory 'C:\git\set\AcmeCompany.AdventureWorks.Data\'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'AppDbContextFactory'.
Found DbContext 'AppDbContext'.
Finding application service provider...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'AppDbContextFactory'.
DesignTimeDbContextFactory.Create(string): Connection string: Server=(localdb)\mssqllocaldb;Database=AcmeCompany.AdventureWorks.Server;Trusted_Connection=True;
Using context 'AppDbContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'AcmeCompany.AdventureWorks.Data'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'AcmeCompany.AdventureWorks.Data'...
No design-time services were found.
DetectChanges starting for 'AppDbContext'.
DetectChanges completed for 'AppDbContext'.
Generating up script for migration '20200326231410_InitialCreate'.
'AppDbContext' disposed.
System.ArgumentNullException: Value cannot be null. (Parameter 'o')
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommandListBuilder.Append(Object o)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.ColumnDefinition(String schema, String table, String name, ColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.ColumnDefinition(String schema, String table, String name, ColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.ColumnDefinition(AddColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.CreateTableColumns(CreateTableOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(CreateTableOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(CreateTableOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__71_11(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateScript(String fromMigration, String toMigration, Boolean idempotent)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.ScriptMigration(String fromMigration, String toMigration, Boolean idempotent, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigrationImpl(String fromMigration, String toMigration, Boolean idempotent, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Value cannot be null. (Parameter 'o')
```

### Further technical details

EF Core version: 5.0.0-preview.3.20181.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: netcoreapp5.0
Operating system: Windows 10 1909
IDE: Visual Studio Professional 2019 16.6.0 Preview 5.0

**Comment by ajcvickers** [comment] 2020-05-04 17:17
@lajones to find dupe.

**Comment by lajones** [comment] 2020-05-04 22:50
Dupe of #20755.

**Closed** 2022-10-16 18:23 UTC
Labels: customer-reported
