### ISSUE TITLE
When I set the environment variable and use the dotnet EF migrations add and dotnet EF database update commands, I cannot get the connectionstring

### ISSUE THREAD

**Issue by nianwu** [dotnet/efcore#18393] opened 2019-10-16 04:33 UTC
my appsettings.json:
``` json
{
  "CommandActions": {
    "News": {
      "ImportNews": false,
    }
  }
  // other
}
```

my appsettings.Development.json:
``` json
{
  "ConnectionStrings": {
    "Default": "Data Source=xxx;Initial Catalog=xxx;Persist Security Info=True;User ID=sa;Password=xxx"
  }
}
```
command:
```
set DOTNET_ENVIRONMENT=Development
dotnet ef migrations add InitDB
```

error:
```
Value cannot be null. (Parameter 'connectionString')
```

**Comment by bricelam** [comment] 2019-10-17 20:55
Are you using PowerShell? If so, use `$env:DOTNET_ENVIRONMENT = 'Development'` instead.

**Comment by ajcvickers** [comment] 2019-10-25 16:07
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:50 UTC
Labels: closed-could-not-reproduce, customer-reported
