### ISSUE TITLE
Unable to Run Add-Migration Command in VS2017 RC2

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/efcore#7345] opened 2017-01-03 22:19 UTC
The is a .net 4.6.1 class library project.

I run 
```
PM> Add-Migration Initial
Cannot execute this command because Microsoft.EntityFrameworkCore.Design is not installed. Install the version of that package that matches the installed version of Microsoft.EntityFrameworkCore and try again.
```

Even though Microsoft.EntityFrameworkCore.Design is installed!

Any ideas?

packages.config
```
<package id="Microsoft.AspNetCore.Hosting.Abstractions" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Hosting.Server.Abstractions" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Http.Abstractions" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Http.Features" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.Data.Sqlite" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.EntityFrameworkCore" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.EntityFrameworkCore.Design" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.EntityFrameworkCore.Relational" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.EntityFrameworkCore.Relational.Design" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.EntityFrameworkCore.Sqlite" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.EntityFrameworkCore.Tools" version="1.1.0-preview4-final" targetFramework="net461" developmentDependency="true" />
```

I found that (as setting the solutions default project to the class library made it work) even though I had selected my class library in the package manager console.

Perhaps a bug in visual studio?

**Comment by JDunaganFL** [comment] 2017-01-04 15:43
Stupid question for you: did you dotnet restore before trying the add migration?

**Comment by bricelam** [comment] 2017-01-04 17:14
Does adding `-Verbose` give any additional information?

**Comment by asleight** [comment] 2017-01-09 21:43
I was having the same issues where EF components were not found. Try doing a `cd` to the project directory (where the VS Project file is) before running the command.

ie:
```
cd C:\MyDevFolder\ProjectFolder
Add-Migration Initial
```

if you have more than one Context, be sure to specify it with:
`Add-Migration Initial --context MyDbContext`

**Comment by divega** [comment] 2017-01-13 23:53
In case you can try the latest version of the tooling, here are some instructions: #7358.

**Comment by rowanmiller** [comment] 2017-01-27 19:48
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 10:48 UTC
