### ISSUE TITLE
Cast<T> for enums not working as expected

### ISSUE THREAD

**Issue by kaspertygesen** [dotnet/efcore#18331] opened 2019-10-11 10:21 UTC
When casting an enum to int using Cast<int>() then the name of the enum is included in the SQL generated instead of its int value.

### Workaround 

``` CSharp
Select(_ => (int)_)
// or
Cast<int>().ToArray()
```

### Steps to reproduce

``` CSharp
public enum StateEnum
{
    Valid = 1,
    Invalid = 2
}

public async void Test(StateEnum[] enums) // Input [StateEnum.Valid]
{
    var states = enums.Cast<int>();
    var result = _context.ParkingRights.Where(pr => states.Contains(pr.ParkingRightStateId));

    // Throws  Microsoft.Data.SqlClient.SqlException : Invalid column name 'Valid'.
}
```

``` SQL
SELECT ...
FROM [ParkingRights] AS [p]
WHERE [p].[ParkingRightStateId] IN (Valid)
```

```
Stack Trace: 
    <>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
    ContinuationResultTaskFromResultTask`2.InnerInvoke()
    <.cctor>b__274_0(Object obj)
    ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
    ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
    --- End of stack trace from previous location where exception was thrown ---
    RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    AsyncEnumerator.MoveNextAsync()
    EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
    EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.4

**Comment by smitpatel** [comment] 2019-10-11 14:58
Duplicate of #17342

**Closed** 2022-10-16 14:49 UTC
Labels: closed-duplicate, customer-reported
