### ISSUE TITLE
Many to Many, Hide One collection Navigation property

### ISSUE THREAD

**Issue by julienGrd** [dotnet/efcore#27658] opened 2022-03-17 09:09 UTC
Hello guys, in my model im able to do something like that for example to load only one side of a relation
````
 entity.HasOne(d => d.Coord)
                    .WithMany()
                    .HasForeignKey(d => d.CoordID)
                    .HasConstraintName("FK_Enfant_Coord");
````
It allow me to load the object Coord without have the all collection on the other side

I would like to have the same for many to many relation but it seem i don't have the method WithMany with null parameter
````
entity.HasMany(d => d.Fns)
                    .WithMany()//compilation error
                    .UsingEntity<Dictionary<string, object>>(
                        "QlQuestsFn",
                        l => l.HasOne<Fn>().WithMany().HasForeignKey("FnNum").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_QlQuestFn_Fn"),
                        r => r.HasOne<QlQuest>().WithMany().HasForeignKey("QlNum").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_QlQuestFn_Ql"),
                        j =>
                        {
                            j.HasKey("QlNum", "FnNum").HasName("PK_QlQuestFn");

                            j.ToTable("QlQuests_Fns");
                        });
````
How i Can achieve what i want ? is it possible now ?

thanks !

**Comment by ajcvickers** [comment] 2022-03-17 16:48
Duplicate of #3864.

**Closed** 2022-10-16 20:29 UTC
Labels: customer-reported
