### ISSUE TITLE
Add ReverseEngineerOptions to ReverseEngineerScaffolder.Generate

### ISSUE THREAD

**Issue by tonysneed** [dotnet/efcore#10156] opened 2017-10-25 14:11 UTC
There are cases when it is desirable to generate either only entity classes or only a DbContext class, rather than always generate both.  For example, a developer may want to place entity and context classes in separate projects, so that a repository / unit of work pattern can be used or entity classes can be shared with a client app.

I would propose that `ReverseEngineerOptions` enum be created with options for this.  For example:

```csharp
public enum ReverseEngineerOptions
{
    DbContextOnly,
    EntitiesOnly,
    DbContextAndEntities
}
```

Then `ICSharpDbContextGenerator` can be registered with a `NullCSharpDbContextGenerator` that returns `null` from `WriteCode`, so that no code generation takes place.  Then `CSharpScaffoldingGenerator` can check for `NullCSharpDbContextGenerator` and not generate the `DbContext` class.  The same can be done for `ICSharpEntityTypeGenerator` and a `NullCSharpEntityTypeGenerator`.

Would you accept a PR for this feature?

**Comment by bricelam** [comment] 2017-10-25 16:06
Duplicate of #1836 (in scenario)

**Comment by tonysneed** [comment] 2017-10-27 13:30
FYI, @ErikEJ provides a feature in his [EF Core Power Tools](https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools), where developers can select options to generate a) DbContext only, b) EntityTypes only, or c) EntityTypes & DbContext.  So it seems this is a valid use-case scenario and something developers want to do.

**Comment by bricelam** [comment] 2017-10-30 21:26
We discussed this again and came to some conclusions:

As @smitpatel already mentioned, the `Scaffold-DbContext` output represents an atomic unit composed of a DbContext and its entity types. While we see value in being able to put those in separate projects (#1836), we don't see any reason to do it in two steps.

Given this, we think you have two options:
1. Make this a feature of your scaffolding implementation. E.g. if there is no template for the DbContext, return `null` or empty. If necessary, let's update EF not to generate a file if it's contents are `null` or empty.
2. Maybe you're expanding the semantics of `dotnet ef dbcontext scaffold` too far beyond its original design, and you should introduce a new command instead (e.g. `dotnet handlebars ef`). This command could leverage all the existing `Microsoft.EntityFrameworkCore.Design` infrastructure, but be tailored to fit your scenarios. Again, we'd update EF as needed.

**Comment by smitpatel** [comment] 2017-10-30 22:27
I looked at the code of HandleBars. They call I/O utility to write each file. So I guess, first check should be easily done at template provider level.

**Comment by tonysneed** [comment] 2017-10-30 22:30
Thanks for considering my proposal for separately generating context and entities separately, but I can see why you'd want those to be atomic.

In my templating package I actually take option 1 above, so it's a non-problem for me at this point.  I just opt to not run a generator if the output is null. Just wanted to explore doing that in the EF tools.  All good now.

**Comment by bricelam** [comment] 2017-10-31 18:19
Sounds good. Sorry for pushing back so much on this. Please, please, please let us know if there are any additional changes we can make to Microsoft.EntityFrameworkCore.Design to enable your scenarios. Also, let us know in #4038 what parts of the API are awkward/conflated so we can clean them up as part of that work.

**Comment by tonysneed** [comment] 2017-10-31 18:58
Appreciate the chance to toss ideas around. I do have a suggestion for graph traversal, so I’ll create an issue for that.

**Closed** 2022-10-16 11:55 UTC
Labels: closed-out-of-scope
