### ISSUE TITLE
"dotnet ef dbcontext scaffold" can't find connection string (NullReferenceException in NamedConnectionStringResolver)

### ISSUE THREAD

**Issue by plettb** [dotnet/efcore#26169] opened 2021-09-24 06:28 UTC
```
dotnet tool install --global dotnet-ef --version 6.0.0-rc.1.21452.10
dotnet user-secrets set ConnectionStrings:Chinook "Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Chinook"
dotnet ef dbcontext scaffold Name=ConnectionStrings:Chinook Microsoft.EntityFrameworkCore.SqlServer
```

produces the following exception:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Storage.Internal.NamedConnectionStringResolver.get_ApplicationServiceProvider()
   at Microsoft.EntityFrameworkCore.Storage.Internal.NamedConnectionStringResolverBase.ResolveConnectionString(String connectionString)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

See also https://stackoverflow.com/questions/69036107/why-does-the-ef-scaffold-dbcontext-command-throw-an-nre-after-reporting-no-des

**Comment by ajcvickers** [comment] 2021-09-28 18:49
Note for triage: we should investigate this. It happens with a default web application in 6.0 rc1. I suspect two things are going on:

1. IConfiguration is not available in the service provider. EF Core named connection string support depends on this.
2. We throw a NullReferenceException instead of the better exception we used to throw in 5.0

This is the 5.0 exception:

> A named connection string was used, but the name 'ConnectionStrings:Chinook' was not found in the application's configuration. Note that named connection strings are only supported when using 'IConfiguration' and a service provider, such as in a typical ASP.NET Core application. See https://go.microsoft.com/fwlink/?linkid=850912 for more information.

/cc @davidfowl @bricelam

**Comment by davidfowl** [comment] 2021-09-28 19:12
dupe of this https://github.com/dotnet/efcore/issues/26177?

**Comment by ajcvickers** [comment] 2021-09-28 19:15
@davidfowl Could be. How is the fix coming?

**Comment by davidfowl** [comment] 2021-09-28 19:17
I have a branch but I can't figure out how to test it.

**Comment by ajcvickers** [comment] 2021-09-28 19:22
Point me to the branch and I'll take a look.

**Comment by davidfowl** [comment] 2021-09-29 03:33
Here https://github.com/dotnet/efcore/pull/26198

**Comment by ajcvickers** [comment] 2021-09-29 18:17
Note a dupe. The issue here is that we started TryAdding design time services, which is good since it allows for overrides. However, it meant that for INamedConnectionStringResolver we were not replacing the runtime service, which then null-reffed at design time. Fix is to make them different services so one does not have to override the other.

**Closed** 2021-09-30 09:13 UTC
Labels: type-bug, closed-fixed, customer-reported, area-scaffolding

**Comment by plettb** [comment] 2021-09-30 18:57
Does this mean the fix is available?  If so, how do I get it?

**Comment by plettb** [comment] 2021-09-30 20:02
@ajcvickers Perfect.  Thanks a lot! :)
