### ISSUE TITLE
Fluent API

### ISSUE THREAD

**Issue by walmanarias** [dotnet/efcore#18384] opened 2019-10-15 19:05 UTC
When writing the configuration on fluent api like this:
builder.Property(x=>x.SomeProperty).HasColumnType("char").HasMaxLength(10);

migration for this line:
SomeProperty: table.Column<string>(type: "char", unicode: false, fixedLength: true, maxLength: 10, nullable: true)

the database end result for the column type is char(1) and the maxlength part is not taken in consideration although the migration looks find.

**Comment by ajcvickers** [comment] 2019-10-15 22:38
Duplicate of #15159

**Closed** 2022-10-16 14:50 UTC
Labels: customer-reported
