### ISSUE TITLE
`UseSqlite(DbConnection)` Behavior Change

### ISSUE THREAD

**Issue by justindbaur** [dotnet/efcore#33930] opened 2024-06-07 19:06 UTC
### Include your code

When trying to update our EF packages in bitwarden/server#3744 we are getting new test failures. That we don't get on our `main` branch. 

[Here is a link](https://github.com/bitwarden/server/blob/fa4dc4aaf2f6b47cd4c6adc39ada24a0d6195bf3/test/Api.IntegrationTest/Controllers/AccountsControllerTest.cs#L15-L37) to the newly failing test. This test is attempting to replicate multiple of our services running at once but sharing the same database. We have an `Api` project that registers users and an `Identity` project that signs users in. To emulate this and make it more testable, we have our `Api` `WebApplicationFactory` create and open a `SqliteConnection` to an in memory database ([link](https://github.com/bitwarden/server/blob/36705790adf553df69de59d59e82f99e7f32d678/test/Api.IntegrationTest/Factories/ApiApplicationFactory.cs#L16-L20)). It then shares that connection with the sub `IdentityApplicationFactory`. That connection is then used in a call to `UseSqlite` [here](https://github.com/bitwarden/server/blob/36705790adf553df69de59d59e82f99e7f32d678/test/IntegrationTestCommon/Factories/WebApplicationFactoryBase.cs#L101-L107).

- [Working example](https://github.com/bitwarden/server/actions/runs/9420648571/job/25953143326)
- [Failing example](https://github.com/bitwarden/server/actions/runs/9419796666/job/25950386352?pr=3744)

The problem seems to be that EF is closing and opening that `SqliteConnection` when it previously didn't. I can verify that by adding a handler for `StateChange` and seeing it get toggled between Closed and Open multiple times throughout the test but previously it only runs when the application factory gets disposed. 

Is this an intended change in behavior?

### Include stack traces

N/A

### Include version information

Microsoft.Data.Sqlite version: `7.0.20` -> `8.0.6`
Target framework: (e.g. .NET 8.0)
Operating system: Ubuntu 22.04

**Comment by bradmarder** [comment] 2024-06-08 01:30
@justindbaur I think the github link is pointing to the wrong test - it should be going to the other `AccountsControllerTest` in the namespace `Bit.Api.IntegrationTest.Controllers` with the test name `GetPublicKey`

**Comment by justindbaur** [comment] 2024-06-08 01:53
@bradmarder Thank you! Good catch, too many test classes with the same name!

**Comment by bradmarder** [comment] 2024-06-08 03:58
Both `ApiApplicationFactory` and `IdentityApplicationFactory` derive from `WebApplicationFactoryBase`.  In this base class, inside the `ConfigureTestServices` block, the method `MigrateDbContext` is called, which in turn calls both `EnsureDeleted` and then `EnsureCreated`. 

The `ConfigureTestServices` block is *never* called until you first access `Client` or `Server`. 

So what is happening here...you are calling `_identityApplicationFactory.RegisterAsync` and then `_identityApplicationFactory.TokenFromPasswordAsync`, both of which are using the `Server` of `IdentityApplicationFactory`.

Then, on line 18 in `AccountsControllerTest`, you are calling `_factory.CreateClient()` (which creates/access the client for the first time of `ApiApplicationFactory` and triggers `ConfigureTestServices`), and which instantly nukes your in-memory database (because of the `EnsureDeleted`).

There are multiple fixes and better ways to approach this, but the simplest temp solution is to just move the`_factory.CreateClient()` line above `_factory.LoginWithNewAccount()`. I think a better solution might be to have both your classes that derive from `WebApplicationFactoryBase` require a `SqliteConnection` arg that is already opened, and then they both register it as a singleton.

**Comment by roji** [comment] 2024-06-08 22:15
@justindbaur can you please isolate a minimal, runnable repro (i.e. a console program) that shows the behavioral change here? EF Core has always opened the connection when needed (e.g. when a query needs to be executed) and closed it right afterwards; the underlying connection pooling of the ADO.NET driver makes this very fast.

**Comment by justindbaur** [comment] 2024-06-09 00:17
Hi @roji, I've made this repo: https://github.com/justindbaur/efcore-33930 that contains a console app that helps show the problem. The docs on the `UseSqlite` method says that if the connection is in the open state then EF will not open/close it. 

@bradmarder Does have a very good point though, that we are running `EnsureDeleted` and `EnsureCreated` on the same connection twice which I would have expected to always have this problem for us. I can definitely make that change on our side but it seems like something still happened in EF.

**Comment by bradmarder** [comment] 2024-06-10 02:53
I've narrowed down the repro to just this.

```c#
using var connection = new SqliteConnection("DataSource=:memory:");
connection.Open();

var db = new ServiceCollection()
	.AddDbContext<DatabaseContext>(x => x.UseSqlite(connection))
	.BuildServiceProvider()
	.GetRequiredService<DatabaseContext>();

Console.WriteLine(db.Database.EnsureCreated());
Console.WriteLine(db.Database.EnsureDeleted());
Console.WriteLine(db.Database.EnsureCreated());
```

Latest version will output True/True/True, which is the expected behavior IMO.
Version `7.0.20` will output True/True/False, but if you remove the `connection.Open();` then the results match.

**Comment by roji** [comment] 2024-06-10 06:59
@bradmarder thanks for that - such small repros really help us when investigating stuff. I can confirm I'm seeing the same results.

The 7.0 behavior indeed seems like a bug - after EnsureDeleted, EnsureCreated is definitely expected to return true. I'm not sure what we did exactly that caused this change, but as the behavior seems correct I suggest closing this issue as "by design". Will leave open for a bit to let @ajcvickers and/or @AndriySvyryd take a look, in case they have something to add.

**Comment by ajcvickers** [comment] 2024-06-11 11:52
Agreed. The 7.0 behavior looks like a bug.

**Comment by roji** [comment] 2024-06-11 14:52
Reclassifying this as a bug fixed in 8.0.

**Closed** 2024-06-11 14:52 UTC
Labels: closed-by-design, customer-reported, area-sqlite
