### ISSUE TITLE
UWP Microsoft.Data.Sqlite problem version > 2.2.6

### ISSUE THREAD

**Issue by Fernand-Delavy** [dotnet/efcore#20100] opened 2020-02-28 12:04 UTC
### To Reproduce

The Test.zip App attached demonstrate the problem with Microsoft.Data.Sqlite on UWP App
It works with Microsoft.Data.Sqlite version 2.2.6
I get Sqlite Error 1 ‘SQL Logoc Error’ wirh Microsoft.Data.Sqlite version 3.1.2 ( version > 2.2.6)

Microsoft.Data.Sqlite version:  > 2.2.6
Target framework: (UWP)
Operating system: Windows 10 Pro 18363.657
`
[Test.zip](https://github.com/dotnet/efcore/files/4266947/Test.zip)
`

**Comment by ajcvickers** [comment] 2020-02-28 17:22
Note for team: looks like another duplicate of #20044

**Closed** 2022-10-16 18:13 UTC
Labels: closed-duplicate, customer-reported
