### ISSUE TITLE
EF core 2.2.4, TPH types mixed up in navigation property

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#16281] opened 2019-06-25 23:41 UTC
Given hierachical objects Mother, ChildA and ChildB in EF core TPH table and using lazy loading.

When I create a navigation between Mother and ChildA objects, EF core gets confused and mixes up the relation updates.

Result: wrong query results and crashes telling me I am using the wrong types.

As a workaround I tried to make the relation optional. Also in that case different errors occur.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/590655/ef-core-224-tph-types-mixed-up-in-navigation-prope.html
VSTS ticketId: 903455_
_These are the original issue comments:_

Willem-Derk Nijdam on 5/31/2019, 04:08 AM (25 days ago): I was using .HasPrincipalKey(a => a.NavId) instead of .HasForeignKey(a => a.NavId)<br>Please close this problem.
Visual Studio Feedback System on 6/3/2019, 02:34 AM (22 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by ajcvickers** [comment] 2019-06-26 17:33
Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-07-05 15:59
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:27 UTC
Labels: closed-could-not-reproduce, customer-reported
