### ISSUE TITLE
EF7 issues with Linq queries in Release compiles using SQLite.

### ISSUE THREAD

**Issue by maxmin88** [dotnet/efcore#4331] opened 2016-01-18 21:22 UTC
I haven't found a better place to submit bug issues....

I have been working on a couple apps for UWP using EF 7.0 RC1.  I am utilizing SqLite DBs on both PC and Mobile Win 10 in Visual Studio 15.  When I run the apps on both ARM and x86 release in Debug mode they they apps work fine but they are slow to load and switch views, for example, since the apps are not natively complied.

However when I switch to Release version I am having trouble running with the EF and Linq commands.  I have incorporated EntityFramework.SQLite and EntityFramework.Commands 7.0.0-rc1-f. 

I am using a rather basic DbContext arrangement.

``` c#
 public class myDbContext:DbContext
    {
        public DbSet<ListItem> ListItems { get; set; }
        public DbSet<Store> Category { get; set; }
        public DbSet<LinkItemCategory> LinksItemCategories{ get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            string databaseFilePath = "ListCategories.db";
            try
            {
                databaseFilePath = Path.Combine(ApplicationData.Current.LocalFolder.Path, databaseFilePath);
            }
            catch (InvalidOperationException) { }

            optionsBuilder.UseSqlite($"Data source={databaseFilePath}");
        }
    }
```

In App.xaml.cs simple calls

```
            RelationalDatabaseFacadeExtensions.Migrate(db.Database);
            InitialData.InitializeDB(db);
```

In Release mode the first call to the DB In the InitialData.InitializeDB fails. 

```
        public static void InitializeDB(myDbContext db)
        {
            if (!db.ListItems.Any())    
```

Fails on db.ListItems.Any().  It says 

I also tried db.ListItems.Select(....) and it also failed with the same message.
'Microsoft.Data.Entity.DbSet<ShopEZ.Models.ListItems>' does not contain a definition for 'Any' and no extension method 'Any' accepting a first argument of type 'Microsoft.Data.Entity.DbSet<ShopEZ.Models.ListItems>' could be found (are you missing a using directive or an assembly reference?)

I also tried .ToList() and same error.

But these apps run fine in Debug mode.  There appears to be some type of bug or limitation when trying to run a fully compiled EF7 UWP project

If someone tells me by return comment where I should submit this I will do so.

**Comment by natemcmaster** [comment] 2016-01-19 18:04
This is a known compatibility issue caused by .NET Native. See http://docs.efproject.net/en/latest/getting-started/uwp.html and https://msdn.microsoft.com/en-us/library/dn600165(v=vs.110).aspx

Duplicate of https://github.com/aspnet/EntityFramework/issues/3603

**Comment by rowanmiller** [comment] 2016-01-19 20:50
> I also tried .ToList() and same error.

@natemcmaster `ToList` should work fine right? And I thought `Any` worked as well.

**Comment by natemcmaster** [comment] 2016-01-19 21:15
@rowanmiller I don't remember finding these issues in our (limited) test coverage for in RC1 but I am not surprised. We knew RC1 + NetNative were not going to be chummy

@maxmin88 you may be able to work around this by adding runtime directives to your project. Also, RC2 (landing soon) will be bringing lots of improvements to the .NET Native compatibility

**Comment by rowanmiller** [comment] 2016-01-19 21:27
ToList/Migrate/etc. should definitely work (I have [UnicornClicker](https://github.com/rowanmiller/UnicornStore/tree/master/UnicornClicker/UWP/UnicornClicker.UWP) deployed to the App Store and it uses those APIs.)

@maxmin88 maybe check your Properties/Default.rd.xml and make sure it has the [same entries as mine](https://github.com/rowanmiller/UnicornStore/blob/master/UnicornClicker/UWP/UnicornClicker.UWP/Properties/Default.rd.xml)

**Comment by rowanmiller** [comment] 2016-02-01 19:48
Closing as we haven't heard back and the UWP pipeline is very different in RC2

**Closed** 2022-10-16 09:25 UTC
