### ISSUE TITLE
add global casesensitive setting in DbContextOptionsBuilder

### ISSUE THREAD

**Issue by wensaint** [dotnet/efcore#20770] opened 2020-04-28 09:59 UTC
when i use function such as  contains, startwith, endwith in string query. there is no where to turn off the casesensitive option.
so, at current, i have to write sql query manually 

suggest to add this option in  DbContextOptionsBuilder,so i can turn it off globally

**Comment by roji** [comment] 2020-04-28 10:28
Duplicate of #6577

**Comment by roji** [comment] 2020-04-28 10:29
EF Core 5.0 will allow you to specify a collation at the database level, which will affect all operations within that database. You would be able to set a case-sensitive collation and achieve what you want.

This should appear in 5.0 preview4.

**Closed** 2022-10-16 18:22 UTC
Labels: closed-duplicate, customer-reported
