### ISSUE TITLE
Default order by when using includes causes performance issues after upgrade from efcore 3 to efcore 5

### ISSUE THREAD

**Issue by ntziolis** [dotnet/efcore#24009] opened 2021-01-28 12:29 UTC
We have recently upgraded from efcore 3 (latest) to efcore 5 (latest) and have seen massive performance issues when using includes.
- efcore 3 query runs <1s
- efcore5 query runs >1min

Please note:
- We know about split query and have started using it where it makes sense for us
- However we are using auto mapper projections which is not compatible with split queries as of today
- The application is to big to migrate away from auto mapper projections in any reasonable timeframe

Source of the problem:
We have traced the issue to efcore5 adding a default order by clause to statements with includes. These order by clauses can become massive:

```SQL
--efcore3
ORDER BY [t].[CreatedAt] DESC

-- efcore5
ORDER BY [t].[CreatedAt] DESC, [t].[Id], [l0].[Id], [a].[Id], [c].[Id], [c0].[Id], 
   [e1].[Id], [t0].[Id0], [t0].[Id4], [t0].[Id], [t0].[Id5], [t0].[Id6], [t0].[Id7], 
   [t0].[Id8], [t0].[Id9], [t0].[Id2], [t0].[Id1], [t0].[Id3], [t0].[Id10], [t0].[Id11], 
   [t0].[Id12], [t0].[Id13], [t0].[Id14]
```

We assume this change in behavior stems from efcore 5 ability to apply order by on includes:
https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include

When no order by is provided efcore 5 falls back to using the primary key (assumption) as the default order by clause.

This changes queries across the entire application dramatically (and I'm sure we are not alone) and has brought our dev efforts to a complete stop since we cannot deploy to production anymore (after update to efcore 5).

Potential solutions:
- for efcore 5 not to apply default order by clause on includes anymore
- for efcore 5 to provide a configuration option that disables default order by clauses on includes either globally or per query (for us globally would be just fine)

**Comment by roji** [comment] 2021-01-28 12:42
Can you please post the LINQ query and (minimal) model, as well as the full SQL queries for both EF Core 3 and 5?

**Comment by ntziolis** [comment] 2021-01-28 13:43
I will collect the information and update this issue.

**Comment by ntziolis** [comment] 2021-01-28 14:01
The below is from memory, but I its 100% accurate where it counts. I believe it highlights the change in behavior very well despite being very simplistic and easily reproducible.

If this is not suitable I'm happy or if would help get this address more quickly I'm happy to setup a repo as well.

Model
```c#
public class Customer
{
        public int Id { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
}

public class Invoice
{
        public int Id { get; set; }
        public virtual Address Address { get; set; }
}

public class Address 
{
        public int Id { get; set; }
}

public class SampleDbContext : DbContext
{
        public DbSet<Customer> Customers { get; set; }
}
```

Linq Query:
```c#
context.Customers.Include(i => i.Invoices).ThenInclude(i => i.Address);
```

SQL :
```SQL
-- efcore3
SELECT [t].*, [a].*, [b].* --simplified
FROM Customers as [t]
LEFT JOIN Invoices as [a] ON [t].Id = [a].Id
LEFT JOIN Addresses [b] ON [a].Id = [b].Id

-- efcore5
SELECT [t].*, [a].*, [b].* --simplified
FROM Customers as [t]
LEFT JOIN Invoices as [a] ON [t].Id = [a].Id
LEFT JOIN Addresses [b] ON [a].Id = [b].Id
ORDER BY [t].Id, [a].Id, [b].Id -- this is the new part in efcore5
```

**Comment by roji** [comment] 2021-01-28 14:40
See the code below which shows the two SQL queries produced in EF Core 3 and 5. There's indeed one extra ORDER BY in the 5 version, but definitely not all of them.

EF Core 5.0:

```sql
SELECT [c].[Id], [t].[Id], [t].[AddressId], [t].[CustomerId], [t].[Id0]
FROM [Customers] AS [c]
LEFT JOIN (
    SELECT [i].[Id], [i].[AddressId], [i].[CustomerId], [a].[Id] AS [Id0]
    FROM [Invoice] AS [i]
    LEFT JOIN [Address] AS [a] ON [i].[AddressId] = [a].[Id]
) AS [t] ON [c].[Id] = [t].[CustomerId]
ORDER BY [c].[Id], [t].[Id], [t].[Id0]
```

EF Core 3.0:

```sql
SELECT [c].[Id], [t].[Id], [t].[AddressId], [t].[CustomerId], [t].[Id0]
FROM [Customers] AS [c]
LEFT JOIN (
    SELECT [i].[Id], [i].[AddressId], [i].[CustomerId], [a].[Id] AS [Id0]
    FROM [Invoice] AS [i]
    LEFT JOIN [Address] AS [a] ON [i].[AddressId] = [a].[Id]
) AS [t] ON [c].[Id] = [t].[CustomerId]
ORDER BY [c].[Id], [t].[Id]
```

@smitpatel dup of #19828?

<details>
<summary>Code</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

_ = ctx.Customers.Include(i => i.Invoices).ThenInclude(i => i.Address).ToList();

public class BlogContext : DbContext
{
    public DbSet<Customer> Customers { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
    }
}

public class Customer
{
    public int Id { get; set; }
    public virtual ICollection<Invoice> Invoices { get; set; }
}

public class Invoice
{
    public int Id { get; set; }
    public virtual Address Address { get; set; }
}

public class Address
{
    public int Id { get; set; }
}

public class SampleDbContext : DbContext
{
    public DbSet<Customer> Customers { get; set; }
}
```

</details>

**Comment by ntziolis** [comment] 2021-01-28 14:53
Thank you for the quick turnaround. We are further investigating the issue we are seeing and I will update here asap (likely by end of day latest tmr).

**Comment by ntziolis** [comment] 2021-01-29 07:05
After further investigation we found that it wasn't the additional order by's (amount of order bys seems to be = number of includes include - 1), but that the main query was now part of a sub query which dramatically changed its execution time.

The problem for us was that this seemed to be an effect we are seeing for quite a few queries. I'm certain that we are doing something wrong as otherwise ef5 users would all be screaming.

Right now our immediate issue was solved by reverting to efcore 3. We are still actively investigating where this issue is coming from, since we absolutely need to move back to efcore5 as soon as possible. The reason for that is that we cannot create any new idempotent migration scripts in efcore 3 due to a bug that was resolved in efcore 5).

Is there a secure way to share the actual linq + efcore3+efcore5 sql (we have them at hand) with you. We are not expecting you to solve this for us, but there might be a chance you can spot something right away that wouldn't be obvious to us.

**Comment by roji** [comment] 2021-01-29 08:53
@ntziolis if you're seeing a SQL change for the same LINQ query between EF Core 3 and 5, please post a minimal, runnable code sample here (minimal model and LINQ query, plus the two SQLs you're seeing). You can also send code to my email address (listed on my github profile), but please try to reduce the sample to a minimal model and query (at which it should also be postable here).

**Comment by ntziolis** [comment] 2021-01-29 14:33
Got it. I will take the time over the weekend to reduce the scenario to minimum and post it here.

**Comment by ajcvickers** [comment] 2021-02-12 16:41
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ntziolis** [comment] 2021-02-12 17:19
I apologize, but were not able to recreate this issue in a minimal repro. Closing this on our end as well.

**Closed** 2022-10-16 19:20 UTC
Labels: closed-could-not-reproduce, customer-reported
