### ISSUE TITLE
Implement a subquery in a SqlExpression?

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#31858] opened 2023-09-26 06:17 UTC
I'm trying to map a method to custom SQL. Here's the function I want to map:

    public static double GetCurrentQuantity(Railcar railcar)
    {
        throw new InvalidOperationException("This method cannot be executed directly.");
    }

And here's the expression I want to map it to:

    return (Railcar r) => r.InboundQuantity
        - dbContext.Transfers
            .Where(t => t.FromId == r.Id && t.FromType == TransferType.Railcar)
            .Sum(t => t.Quantity)
        + dbContext.Transfers
           .Where(t => t.ToId == r.Id && t.ToType == TransferType.Railcar)
           .Sum(t => t.Quantity);

But I cannot figure out the syntax to specify these subqueries. And I haven't been able to find my documentation on this. This is as far as I got:

    builder.HasDbFunction(
        typeof(QueryHelper).GetMethod(nameof(QueryHelper.GetCurrentQuantity), new[] { typeof(Railcar) }))
        .HasTranslation(
            args =>
                new SqlBinaryExpression(
                    ExpressionType.Subtract,
                    ColumnExpression.Property(args[0], nameof(Railcar.InboundQuantity)),
                    ????

Could someone be good enough to get me moving in the right direction?

**Comment by roji** [comment] 2023-09-26 23:02
@SoftCircuits OK to close this as a duplicate of #31871?

**Comment by SoftCircuits** [comment] 2023-09-26 23:13
@roji Sure, although I would love to hear if you thought "stored functions" would be an option in my case?

**Comment by roji** [comment] 2023-09-27 11:14
Duplicate of #31871

**Closed by roji** 2023-09-27 11:15 UTC
Labels: customer-reported

**Comment by SoftCircuits** [comment] 2023-09-27 15:42
@roji I don't know how that would work exactly, but it sounds like it would add additional overhead, which I was hoping to avoid.

Currently, there doesn't appear to be a good solution for me. I have it working with LINQKit, but the approach there seems very brittle and tied to specific versions of .NET.
