### ISSUE TITLE
Why does EF Core use nested select statements in all joins?

### ISSUE THREAD

**Issue by uehlbran** [dotnet/efcore#28252] opened 2022-06-16 17:46 UTC
Query generated by EF Core 6.

```SQL
SELECT 't'.'UserId', 't'.'Username', 'o'.'OrderId', 'o'.'Total', 'o'.'UserId'
FROM (
    SELECT 'u'.'UserId', 'u'.'Username'
    FROM 'Users' AS 'u'
    WHERE 'u'.'UserId' = 1
    LIMIT 1
) AS 't'
LEFT JOIN 'Orders' AS 'o' ON 't'.'UserId' = 'o'.'UserId'
ORDER BY 't'.'UserId'
```

The second select seems redundant and feels like an issue to me (N+1 query issue). It should be generating the following SQL code:

```SQL
SELECT u.userid, u.username, o.orderid, o.total, o.userid 
FROM users AS u 
JOIN orders AS o ON o.userid = u.userid
WHERE u.userid = 1
```

C# Dummy code

```C#
namespace LearningCSharp1
{
    class Program
    {
        public static async Task Main(string[] args)
        {
            var context = new Context();
            var user = await context.Users.Include(u => u.Order).FirstAsync();
        }
    }

    class User
    {
        public int UserId { get; set; }
        public string Username { get; set; } = null!;
        public IEnumerable<Order> Order { get; set; } = new List<Order>();

        public override string ToString()
        {
            return $"Id: {UserId} | Username: {Username}";
        }
    }

    class Order
    {
        public int OrderId { get; set; }
        public decimal Total { get; set; }
        public User User { get; set; } = null!;
        public int UserId { get; set; }
    }

    class Context : DbContext
    {
        public DbSet<User> Users => Set<User>();
        public DbSet<Order> Orders => Set<Order>();

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseMySql(
                    "Server=localhost;Database=efcore;User=root;Password=password.",
                    ServerVersion.AutoDetect("Server=localhost;Database=efcore;User=root;Password=password.")
                )
                .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking)
                .LogTo(Console.WriteLine, LogLevel.Information)
                .EnableSensitiveDataLogging();
        }
    }
}
```

### Further technical details

Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.AspNetCore.App version: 6.0.6
Npgsql.EntityFrameworkCore.PostgreSQL version: 6.0.4

The issue is not the provider. I want to assume I'm doing something wrong but, this example is so simple that I can't imagine that is the case.

**Comment by roji** [comment] 2022-06-18 15:00
@uehlbran is this still relevant after the discussion in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1669?

**Comment by ajcvickers** [comment] 2022-06-30 08:45
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-06-30 08:45 UTC
Labels: closed-by-design, customer-reported
