### ISSUE TITLE
JSON_VALUE query not able to use indexes

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#29342] opened 2022-10-13 06:55 UTC
Using sample from docs sample: (only selecting Id and Name)

```sql
SELECT [a].[Id], [a].[Name]
FROM [Authors] AS [a]
WHERE 
CAST(JSON_VALUE([a].[Contact],'$.Address.City') AS nvarchar(max)) = N'Chigley'
```
=> generates table scan

Adding index base on [this doc](https://learn.microsoft.com/en-us/sql/relational-databases/json/index-json-data?view=sql-server-ver16#example-index)

```sql
ALTER TABLE [dbo].[Authors]
ADD vContactCity AS JSON_VALUE(Contact,'$.Address.City')

CREATE INDEX idx_soh_json_ContactCity
ON [dbo].[Authors](vContactCity)
INCLUDE(Name)
```
Above query still uses table scan.

(Using RC2 from NuGet.org)

This does not:

```sql
SELECT [a].[Id], [a].[Name]
FROM [Authors] AS [a]
WHERE 
JSON_VALUE([a].[Contact],'$.Address.City') = N'Chigley'
```

**Comment by ErikEJ** [comment] 2022-10-13 07:06
Found duplicate #28881 

But trying this:

```
ALTER TABLE [dbo].[Authors] 
ADD vContactCity AS CAST(JSON_VALUE([Contact],'$.Address.City') AS nvarchar(max))

CREATE INDEX idx_soh_json_ContactCity
ON [dbo].[Authors](vContactCity)
INCLUDE(Name)
```

Results in:

Column 'vContactCity' in table 'dbo.Authors' is of a type that is invalid for use as a key column in an index.

@roji What magic incantation am I missing? and maybe it should be added to the docs?

**Comment by roji** [comment] 2022-10-13 11:58
@ErikEJ I cleaned up and uploaded the setup and benchmarks I used - see https://github.com/roji/JsonColumnsPerf. tl;dr I can definitely see an index seek in the plan(not a table scan), although that's still much slower than if the cast to `nvarchar(max)` weren't there (in which case we get a super-optimized index seek.

**Comment by ErikEJ** [comment] 2022-10-13 12:04
I see 

`Index Scan: Index Scan(OBJECT:([JsonColumns].[dbo].[Customers].[IX_Customers_ComputedJsonCountry] AS [c])) `

SQL Server is using that index because you are asking for COUNT(*) (not column data) and the index is narrow.

**Comment by ErikEJ** [comment] 2022-10-13 12:15
Done! :smile:

**Comment by roji** [comment] 2022-10-13 12:29
Duplicate of #28881

**Closed by roji** 2022-10-13 12:29 UTC
Labels: customer-reported
