### ISSUE TITLE
Support legacy code layout

### ISSUE THREAD

**Issue by fogzot** [dotnet/efcore#8852] opened 2017-06-14 09:49 UTC
A lot of projects in the wild have two characteristics that create a lot of attrition while porting them to .NET Core and EF:

  1. the directory structure can be different from the classic NS/SUBNS;
  2. a database already exists, so scaffolding the entities using the `ef` tool is almost mandatory.

Specifically, `ef` infers the namespaces from the project structure and while this is good and easy for new projects, it makes almost mandatory to edit the generated files by hand (which if bad).

It would be extremely useful to be able to decouple the naming of the generated classes (in particular the namespace) from the output directory.

Will the project accept a small patch to add a new option `--namespace` to override the value automatically inferred from the `-o` parameter?

**Comment by ErikEJ** [comment] 2017-06-14 10:38
Have you tried my GUI tool, it allows you to set the default namespace. https://twitter.com/ErikEJ/status/834452863380250624

**Comment by fogzot** [comment] 2017-06-14 10:48
@ErikEJ no, I didn't know about it and I'll surely have a look. But I was thinking about different backends (we use at least 3: SQLite, PostgreSQL via Npgsql and MS-SQL) on different platforms using only command line tools (no UI). I think this is a little bit different from what you're proposing. In the end, EF Core is very good but trying to use it in a workflow with legacy code/database-first still creates a bit of attrition.

**Comment by ajcvickers** [comment] 2017-06-16 19:48
@bricelam @lajones @smitpatel Do you know if we are already tracking something for namespaces on reverse engineering? If so, is this sufficiently different to keep it open as a separate issue?

**Comment by lajones** [comment] 2017-06-16 20:56
@ajcvickers #3988 comes to mind. There was another bug that explicitly discussed all the options for output directory structure / namespace / database schemas - but I can't find that right now. `Scaffold-DbContext` originally had a `--namespace` arg that you could use to override the namespace for any given run, but it was scoped out in v1.

**Comment by smitpatel** [comment] 2017-06-16 23:08
Another related issue https://github.com/aspnet/EntityFramework/issues/4524

**Comment by ajcvickers** [comment] 2017-06-19 19:11
Closing this as a dupe of #3988 which has been re-purposed to cover the general question of namespaces in reverse enineering.

**Closed** 2022-10-16 11:08 UTC
