### ISSUE TITLE
InMemory ArgumentException with OwnedType and InMemoryDatabaseRoot

### ISSUE THREAD

**Issue by Materix** [dotnet/efcore#17055] opened 2019-08-09 08:25 UTC
I am trying to work with multimodel (due to different QueryFilters based on logged user) approach and InMemory provider (in integration tests). Therefore I have to use InMemoryDatabaseRoot to share data between model.

I have TransliteratedString class which I use as owned type in many entities. When I was trying to add two different entity with different TransliteratedString instance in them I have ArgumentException in SaveChanges()

Own investigation:
In https://github.com/aspnet/EntityFrameworkCore/blob/v3.0.0-preview7.19362.6/src/EFCore.InMemory/Storage/Internal/InMemoryStore.cs#L184 table is chosen based on name of entity so TransliteratedString instances are added to same InMemoryTable

### Steps to reproduce
Repro repository:  https://github.com/Materix/EFInMemoryRootOwnedType

Model definition in src/EFInMemoryRootOwnedType
Tests in test/EFInMemoryRootOwnedType.Test

Checkout and run `dotnet test`

### Further technical details
EF Core version: 3.0.0-preview7.19362.6
Database Provider: Microsoft.EntityFrameworkCore.InMemory 3.0.0-preview7.19362.6

**Comment by ajcvickers** [comment] 2019-08-14 16:20
Note for triage: my guess is that this is because we are using the simple entity type name to try to match owned types.

**Comment by SamVanheer** [comment] 2020-01-09 22:39
I encountered this issue as well. #19446 has the code for my use case. When both `Vector3` properties are non-null i get the same exception.

I dug a little further and stepped through the code. The `EntityType` name is `EntityFrameworkOwnedBug.Vector3`, which is being used as the key for database lookup. It's the same for all `Vector3` properties defined on the `Axis` type.

The primary key member for the entity type is `{Key: Axis.Position#Vector3.AxisId PK}`, dependent on the member in the owner.

The `ToString` method returns `{EntityType: Axis.Position#Vector3}`, which seems to be returned by the `DisplayName` extension method.

I can also confirm that removing the database root resolves the issue since the underlying `EntityType` instances are unique.

**Comment by ajcvickers** [comment] 2020-05-25 20:36
Duplicate of #20784

**Closed** 2022-10-16 14:34 UTC
Labels: closed-duplicate, customer-reported
