### ISSUE TITLE
Wrong translation of captured boolean variable into a string and compared to a bit of 0

### ISSUE THREAD

**Issue by raymens** [dotnet/efcore#12161] opened 2018-05-29 09:55 UTC
I have converted our application from EF6 to EF Core 2.1 RC1.
We get an exception where it seems a captured `bool` variable is being translated wrong into a `string` but compared to an `integer` of `0`.

```
Exception message: System.Data.SqlClient.SqlException: 'Conversion failed when converting the nvarchar value 'True' to data type int.'
Stack trace: 

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Nexus.Portal.Controllers.AccountListController.Index(String DefaultStatusFilter) in F:\Workspace\nexus\src\Nexus.OperatorWebApp\Controllers\AccountListController.cs:line 63
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()

```

### Steps to reproduce

I have tried but didn't manage to reproduce this in a separate solution yet, not sure why that is.
`isGlobalOperator` is a boolean property. If I replace it by some other check like `account.Id == 0` in the expression it does work.

(excerpt)
```c#
            var list = db.Accounts.Select(account => new AccountListView()
            {
                Created = account.Created,
                Status = (isGlobalOperator
                            ? account.LabelPartner.TransactionCodePrefix.Trim() + " "
                            : "")
                          + account.AccountStatu.Name.Trim()
             });
```
This gets translated to the following SQL (excerpt).

```sql
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (90ms) [Parameters=[@__isGlobalOperator_0='?' (Size = -1)], CommandType='Text', CommandTimeout='30']
SELECT [account].[Created], CASE
    WHEN @__isGlobalOperator_0 = 1
    THEN LTRIM(RTRIM([account.LabelPartner].[TransactionCodePrefix])) + N' ' ELSE N''
```

### Further technical details
EF Core version: 2.1.0-RC1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1803
IDE: Visual Studio 2017 15.7.2

**Comment by smitpatel** [comment] 2018-05-29 20:00
@raymens - Can you share your model classes too? The bug is due to incorrect type inference. We would like to know type mappings in the class.

It is happening because for some reason, bool parameter `@__isGlobalOperator_0` got string type mapping and generated string parameter instead of Boolean.

**Comment by ajcvickers** [comment] 2018-06-06 18:08
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:27 UTC
Labels: closed-could-not-reproduce, customer-reported
