### ISSUE TITLE
Migration: `HasData` generates migration with `object[,]` instead of `object?[,]`

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/efcore#25588] opened 2021-08-19 13:29 UTC
## File a bug

When generating migration from `HasData`, `values` should be `object?[,]` instead of `object[,]` (in nullable projects)

### Include your code

```cs
public MyClass
{
    public int A { get; set; }
    
    public string? B { get; set; }
}
```

```cs
public class MyClassConfiguration : IEntityTypeConfiguration<MyClass>
{
    public void Configure(EntityTypeBuilder<MyClass> builder)
    {
        builder.HasData(new MyClass[]
        {
            new()
            {
                A = 1,
            },
            new()
            {
                A = 2,
                B = "str"
            });
        }
    }
}
```

Resulting migration:
```cs
public partial class AddSeeder : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.InsertData(
            table: "MyClass",
            columns: new[] { "Code", "DescriptionFormat", "Params" },
            values: new object[,] // Should be object?[,]
            {
                { 1, null },
                { 2, "str" },
            }
   }
}
```

### Include provider and version information

EF Core version: 5.0.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Winddows
IDE: Visual Studio 2019 16.11.1

**Comment by roji** [comment] 2021-08-19 14:06
Duplicate of #18950

**Closed** 2022-10-16 19:43 UTC
Labels: closed-duplicate, customer-reported
