### ISSUE TITLE
EF Core 3.1.0 - Method not found: 'System.Collections.Generic.IEnumerable`1<!!0>

### ISSUE THREAD

**Issue by almuba** [dotnet/efcore#19572] opened 2020-01-12 05:53 UTC
Hi All,

   When I'm deploying windows services using EF 3.1.0, the following error has occurred while executing the Linq Query. and it's working perfectly in my local machine, the issue happens while deploying in the windows server 2012 R2.

.Net framework 4.6.1
EF CORE 3.1.0

```C#
using (var ctx = new DatabaseContext())
                    {                        
                        var bats = (from bt in ctx.Batches
                                    where bt.Is_Active == true && bt.Is_Completed == false && bt.Is_Locked == false
                                    select new
                                    {
                                        bt.Batch_Id,
                                        bt.Batch_No                           
                                    }).ToList();
```

**Error:**

```
 Method not found: 'System.Collections.Generic.IEnumerable`1<!!0> System.Linq.Enumerable.Append(System.Collections.Generic.IEnumerable`1<!!0>, !!0)'. :  :    at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.InsertRuntimeParameters(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at InvitationSrvcs.InvitationService.ReadMsgs(Object s, ElapsedEventArgs e) 
```

Please advise me to fix this issue as soon as possible.

@radical @ajcvickers @shanselman @AArnott

**Comment by almuba** [comment] 2020-01-12 11:53
is there any update on the above request? Please highlight me if I did anything wrong.

**Comment by ajcvickers** [comment] 2020-01-13 17:23
@almuba The cause of the issue is not immediately obvious from the information posted. A couple of things to check:
* Make sure that different EF Core versions are not being mixed together. All packages should be 3.1 versions.
* While .NET Framework will run NET Standard 2.0 assemblies, there are [significant issues with all versions below 4.7.2](https://docs.microsoft.com/en-us/dotnet/standard/net-standard). (See the notes in the table on that page.)

If this doesn't help, then please attach a small, runnable project or post a complete code listing that reproduces the behavior you are seeing.

**Comment by ajcvickers** [comment] 2020-01-21 16:57
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:05 UTC
Labels: closed-could-not-reproduce, customer-reported
