### ISSUE TITLE
Enums with string conversion do not become required (non-nullable) in model snapshot

### ISSUE THREAD

**Issue by ilyazolotarov** [dotnet/efcore#11783] opened 2018-04-23 17:30 UTC
When enum property is configured like  
```c#
t.Property(p => p.Enum).HasConversion<string>() 
```
the valid migration is scaffolded

```c#
migrationBuilder.CreateTable(
                name: "TableName",
                columns: table => new
                {
                    Enum = table.Column<string>(nullable: false)
                },
...);
```
But when it goes to updating the model snapshot it missed ".IsRequired()" modifier on that column. So the next migration looks like the following
```c#
migrationBuilder.AlterColumn<string>(
                name: "Enum",
                table: "TableName",
                nullable: false,
                oldClrType: typeof(string),
                oldNullable: true);
```

Even if you append ".IsRequired()" manually to the snapshot, on the next migration scaffolding it will be deleted and the subsequent migrations will have that  redundant "AlterColumn ... nullable: false ... oldNullable: true".

### Further technical details
EF Core version: 2.1.0-preview2-final
EF Core Tools version: 2.1.0-preview2-final
EF Core Tools.DotNet version: 2.1.0-preview1-final
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL

**Comment by ajcvickers** [comment] 2018-04-23 17:57
Duplicate of #11343
Fixed in [the nightly builds of 2.1](https://dotnet.myget.org/gallery/dotnet-core).

**Closed** 2022-10-16 12:20 UTC
Labels: closed-duplicate
