### ISSUE TITLE
Single navigation property creates null child

### ISSUE THREAD

**Issue by EdRbt** [dotnet/efcore#4154] opened 2015-12-22 16:17 UTC
Hi,

Here is my scenario.
I have an Address entity, used in both Hotels and Restaurant entities (I voluntarly simplified the models)
Here are my entities:

```
public class Address
{
    public int Id { get; set; }
    public string Street { get; set; }
    public string City { get; set; }
}

public class Hotel
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Address Address { get; set; }
}

public class Restaurant
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Address Address { get; set; }
}
```

And my DbContext:

```
public class MyDbContext : DbContext
{
    public DbSet<Address> Addresses { get; set; }
    public DbSet<Restaurant> Restaurants{ get; set; }
    public DbSet<Hotel> Hotels{ get; set; }

    [...]

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Restaurant>.HasOne(r => r.Address).WithOne();
        modelBuilder.Entity<Hotel>.HasOne(r => r.Address).WithOne();
    }
}
```

But when I call Add on a Restaurant or Hotel entity initialized with an Address, the Address is not registered in the database and the navigation property is set to null.

Am I missing something ?
I followed the doc on single navigation properties here: http://ef.readthedocs.org/en/latest/modeling/relationships.html#id14

**Comment by smitpatel** [comment] 2015-12-22 17:44
Duplicate of #4035.

**Comment by EdRbt** [comment] 2015-12-23 09:19
Hi,

Thanks for your answer. Actually I was confused with the Add function, because it contains a parameter GraphBehavior set to GraphBehavior.IncludeDependents but I don't think it does anything.
I'm now using ChangeTracker.TrackGraph, and it works perfectly.

**Closed** 2022-10-16 09:21 UTC
