### ISSUE TITLE
.NET Core 3.0.100-preview6-012264 upgrade breaks Culture Comparison

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#16125] opened 2019-06-17 15:16 UTC
Moved from https://github.com/dotnet/core/issues/2872 originally filed by @NichUK

- .NET Core 3.0.100-preview6-012264
- Windows Server 2019

**Problem Description**
I upgraded a project to Preview 6 (from Preview 5) and started getting exceptions on a line of code that has been working for months...

`return _oeContext.ConfigItems.Where(c =>`
`                c.Name.Equals(key, StringComparison.CurrentCultureIgnoreCase));`

My current culture is "en-GB"

When replaced with:

`return _oeContext.ConfigItems.Where(c =>`
`                c.Name.ToLower() == key.ToLower());`

everything started working again, so I think there is something wrong with culture comparison in Preview6.

I also tried changing the culture to en-US both by using CurrentThread.CurrentCulture and by changing the whole machine to en-US, but it still didn't work with the original code.

**Comment by ajcvickers** [comment] 2019-06-17 15:19
@NichUK First, many thanks for trying preview 6. We really appreciate people trying the previews and filing issues on what they find.

If you haven't seen it already, there is some good information in the [preview announcement post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/) about the changes that are happening to LINQ queries for EF Core 3.0. Preview 6 is the first release containing these changes, which means we are both expecting things to be broken, but at the same time very grateful for everyone who tries the release and generated feedback.

**Comment by NichUK** [comment] 2019-06-17 18:38
Aha! :)  Thanks for that @ajcvickers. I had not seen that blog, great news, and also says quite clearly that equality comparisons may well fail.

I'm using the ToLower() workaround for now, so all good. I'm happy to either close this as a known issue, or leave it open for tracking, whichever the owning team prefer. 

Otherwise Preview 6 is working pretty well for me.

**Comment by ajcvickers** [comment] 2019-06-17 18:55
@NichUK Thanks; great to hear preview 6 is working.

@maumar @smitpatel Please de-dupe this if needed.

**Comment by smitpatel** [comment] 2019-06-17 18:58
Duplicate of #1222

I am bit surprised that it worked in preview5 perhaps client eval was set to be on. And now we don't have it anymore in preview6.

**Comment by NichUK** [comment] 2019-06-17 22:01
I think EF Core was a few versions behind when I was on Preview 5, hence the problem only appeared when I upgraded everything to 6.

Thanks!

**Closed** 2022-10-16 14:26 UTC
