### ISSUE TITLE
DefaultIfEmpty fails if default value specified

### ISSUE THREAD

**Issue by FormerMarine** [dotnet/efcore#19704] opened 2020-01-25 11:49 UTC
If you specifiy a default value in DefaultIfEmpty (e.g. DefaultIfEmpty(-1)) an InvalidOperationException is thrown with the message "NavigationExpandingExpressionVisitor failed".

EF Core version: 3.1.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16..4.3)

**Comment by ajcvickers** [comment] 2020-01-27 17:55
Note for team: looks like a duplicate of #17783. However, maybe we can improve the exception message.

@FormerMarine Please post the full exception message and stack trace.

**Comment by FormerMarine** [comment] 2020-01-27 19:09
When it became obvious that EF Core wasn't going to satisfy my requirements I redid the project using EF 6.4. If you think the information is critical, I can create another project and get it.

**Comment by ajcvickers** [comment] 2020-01-28 18:13
Follow up with @smitpatel

**Comment by smitpatel** [comment] 2020-02-05 20:06
Exception message improved in master to throw translation failure.

**Comment by FormerMarine** [comment] 2020-02-05 21:12
This problem existed in Linq-To-Sql (EF's predecessor) where the "defaultValue" option was not implemented. Is this the same problem?

**Comment by FormerMarine** [comment] 2020-09-26 23:33
Still fails in 5.0

**Comment by roji** [comment] 2020-10-12 14:55
@FormerMarine note that this was flagged as a duplicate of #17783, which is indeed still open. Please follow that issue rather than posting here.

**Closed** 2022-10-16 18:07 UTC
Labels: customer-reported
