### ISSUE TITLE
Support for Document Databases in General

### ISSUE THREAD

**Issue by craiggwilson** [dotnet/efcore#1063] opened 2014-11-14 22:00 UTC
I saw that there was a ticket for including support for DocumentDB. I hacked around today building a MongoDB provider. I haven't tackled queries yet, just the save changes stuff which all works great when the entity is flat - no nested documents or nested arrays in json speak.

So, it doesn't seem like there is any support for tracking changes in nested documents/nested arrays when they don't have a key. For a document database, these aren't relationships in the foreign key sense, but more of a parent-child in structure. I began attempting to use a Sidecar for this (like the RelationshipsSnapshot) and overriding the ChangeDetector to use it but found that I still need to be able to get a StateEntry in order to determine whether changes have been made to a nested entity. However, StateManager can only do that when a key has been defined. Ho, hum...  It seems like 1 or 2 concepts are missing in the existing Metadata related to handling embedded classes/dictionarys and arrays/lists that don't exist in a separate table (or collection).  This is obviously only useful for those providers able to handle this type of thing, but the same could be said about ForeignKeys only being relevant for providers able to handle relationships.

Let me know your thoughts. I'm excited about EF7 opening up to allow this type of integration and hope I'll be able to get something working.

Thanks, Craig Wilson

**Comment by divega** [comment] 2015-05-23 18:38
Moving straight to our backlog as we are not going to make much progress in this area for EF7 RTM, but it still of high importance after that. Also following up with Craig on email.

**Comment by smitpatel** [comment] 2017-08-15 02:58
Duplicate of #8443 ?

**Closed** 2022-10-16 08:46 UTC
Labels: closed-out-of-scope
