### ISSUE TITLE
FromSqlRaw Failing with derived Keyless Entity Types

### ISSUE THREAD

**Issue by joshvote** [dotnet/efcore#19520] opened 2020-01-08 06:33 UTC
When using a keyless entity type that is derived from a base class eg:

```
public class PersonView
{
  public string Name { get; set; }
}

public class ParentView : PersonView
{
  public long ParentID { get; set; }
}
```
And configured in a context with
```
modelBuilder.Entity<PersonView>(entity =>
{
  entity.HasNoKey();
});
```
Attempting to return that keyless entity type using some custom SQL: `dc.ParentViews.FromSqlRaw("SELECT [Name], 11 AS [ParentID] FROM [test].[People] ORDER BY [Name]")` results in an `SqlException: The ORDER BY clause is invalid in views,...`

This is because the generated SQL ends up looking like this:
```
SELECT [p].[Discriminator], [p].[Name], [p].[ParentID]
FROM(
SELECT[Name], 11 AS[ParentID] FROM[test].[People] ORDER BY[Name]
) AS[p]
WHERE[p].[Discriminator] = N'ParentView'
```

Is there anyway to tell EF to ignore the subclass and just treat it as a "normal" entity?

I understand that this is a bit of clunky set of circumstances due to the class extension on PersonView / ParentView, unfortunately that model hierarchy is outside our control (defined in a seperate lib).

### Steps to reproduce

Example project showing issue (requires SQL Server LocalDB) - https://github.com/joshvote/efcorerawsqlbug

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.2

**Comment by smitpatel** [comment] 2020-01-08 09:05
Duplicate of #18232 

It has same root cause. Though in your case you can just modify your SQL little bit to make it work
```SQL
SELECT [Name], 11 AS [ParentID] FROM [test].[People] ORDER BY [Name] OFFSET 0 ROWS
```

**Closed** 2022-10-16 18:04 UTC
Labels: closed-duplicate, customer-reported
