### ISSUE TITLE
Add `dotnet ef database create-tables` command

### ISSUE THREAD

**Issue by glen-84** [dotnet/efcore#29629] opened 2022-11-20 13:19 UTC
Easily create and drop all tables during initial development.

`dotnet ef database create-tables`
`dotnet ef database drop-tables`

Alternative: `dotnet ef dbcontext script --apply` (apply the script to the database).

Related to #3053, but without involving migrations.

**Comment by ErikEJ** [comment] 2022-11-20 13:28
There is 

    context. Database.EnsureDeleted();

And

    context.Database.EnsureCreated();

**Comment by glen-84** [comment] 2022-11-20 13:37
I know, but it would be better as a CLI command. It seems strange to add code like this to every application, especially if it's not used after initial development.

**Comment by roji** [comment] 2022-11-21 09:45
How about `dotnet ef database drop` and `dotnet ef database update`?

**Comment by ajcvickers** [comment] 2022-11-21 10:40
@roji `dotnet ef database update` only works if there are Migrations. So this issue is really about doing `EnsureCreated` from the command line.

**Comment by roji** [comment] 2022-11-21 10:52
OK, thanks. Though @glen-84, I'm not sure why a CLI is needed if we're just talking about early development; what's the down-side of just using EnsureDeleted/Created in early development and then switching to Migrations when the model stabilizies?

(Note that EnsuredDeleted/Created can also be useful in other scenarios, e.g. creating databases in tests - though a CLI command also doesn't seem useful there)

**Comment by glen-84** [comment] 2022-11-21 11:29
I answered that above. 🙂

> It seems strange to add code like this to every application, especially if it's not used after initial development.

You wouldn't want to run EnsureDeleted/Created on every launch, so then you need to involve a CLI argument to the application itself ... then do you commit this temporary code for other devs to use? Starts getting messy IMO.

**Comment by ErikEJ** [comment] 2022-11-21 11:34
So

    dotnet ef database create

Or

    dotnet ef database ensurecreated

??

happy to do a PR if this is useful at all

**Comment by glen-84** [comment] 2022-11-21 11:46
TBH, the existing naming is a bit unclear, since I would expect `Database.EnsureCreated` to create the database itself, and not the tables within it. That's why I had suggested something like `create-tables`, but I suppose it should be consistent with existing terminology (`ensure-created`).

I'll leave the naming to the maintainers. 🙂

**Comment by roji** [comment] 2022-11-21 15:30
> then do you commit this temporary code for other devs to use? Starts getting messy IMO.

Aren't you already committing temporary model states in this early development phase? If so, why would it be any worse to commit EnsureDeleted/EnsureCreated? I don't see any problem with these to get committed in the early phase.

Another possibly way to do this is to just do `dotnet ef migrations add dummy` and then `dotnet ef database drop; dotnet ef database update`; to restart you can just delete the migrations directory and do the same again. You can put these command in a tiny script to make it a single command.

The point is that it's not great to add two more CLI commands that everyone will have to see and understand (when should I use `create-tables` vs. `update`), unless there's a compelling reason to do so...

**Comment by ajcvickers** [comment] 2022-11-21 16:53
Duplicate of #7840. Make sure to vote (👍) for that issue.

**Comment by glen-84** [comment] 2022-11-21 17:18
@roji

> Aren't you already committing temporary model states in this early development phase? If so, why would it be any worse to commit EnsureDeleted/EnsureCreated? I don't see any problem with these to get committed in the early phase.

There's a difference between committing partial/incomplete code, and code that you know for sure will need to be removed later. I try to avoid the latter where possible.

> Another possibly way to do this is to just do dotnet ef migrations add dummy and then dotnet ef database drop; dotnet ef database update; to restart you can just delete the migrations directory and do the same again. You can put these command in a tiny script to make it a single command.

Messy, and would need to be shared anyway.

> The point is that it's not great to add two more CLI commands that everyone will have to see and understand (when should I use create-tables vs. update), unless there's a compelling reason to do so...

I would argue that `update` might be less confusing under the `migrations` namespace. What does it mean to "update" a database? Using migrations, using the entity model, using a SQL script, ... ?

f.e. `dotnet ef migrations apply InitialCreate`

And to leave the `database` namespace for more generic operations like `drop`, `create`, `create-tables` (or `create-schema`), etc.

Doctrine (PHP) has [commands for this](https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/reference/tools.html#command-overview) (`orm:schema-tool:create/drop/update`). I'm not sure about other ORMs.

@ajcvickers

Apologies! I tried to search existing issues but didn't find anything.

**Comment by roji** [comment] 2022-11-21 18:36
> I would argue that update might be less confusing under the migrations namespace. What does it mean to "update" a database? Using migrations, using the entity model, using a SQL script, ... ?

`dotnet ef database update` already exists - we're not creating a tool from scratch, and it's definitely not an option to remove this and redo the entire `dotnet ef` CLI interface. Regardless, it seems like pretty decent naming to me - "update the database (to the latest migration)".

Will leave the rest of the discussion to take place in #7840.

**Comment by roji** [comment] 2022-11-21 18:36
Duplicate of #7840

**Closed** 2022-11-23 13:20 UTC
Labels: customer-reported
