### ISSUE TITLE
RevEng: Types with length can be specified using data annotations

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#5290] opened 2016-05-07 01:02 UTC
Using Northwind Database with SqlServer provider,

```
// Orders class
public partial class Orders
{
    [Key]
    public int OrderID { get; set; }
    public string CustomerID { get; set; }
    public int? EmployeeID { get; set; }
    public DateTime? OrderDate { get; set; }
    public DateTime? RequiredDate { get; set; }
    public DateTime? ShippedDate { get; set; }
    public int? ShipVia { get; set; }
    public decimal? Freight { get; set; }
    [MaxLength(40)]
    public string ShipName { get; set; }
    [MaxLength(60)]
    public string ShipAddress { get; set; }
    [MaxLength(15)]
    public string ShipCity { get; set; }
    [MaxLength(15)]
    public string ShipRegion { get; set; }
    [MaxLength(10)]
    public string ShipPostalCode { get; set; }
    [MaxLength(15)]
    public string ShipCountry { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("Orders")]
    public virtual Employees Employee { get; set; }
}

// Orders configuration in OnModelCreating
modelBuilder.Entity<Orders>(entity =>
{
    entity.HasIndex(e => e.CustomerID)
        .HasName("CustomersOrders");

    entity.HasIndex(e => e.EmployeeID)
        .HasName("EmployeesOrders");

    entity.HasIndex(e => e.OrderDate)
        .HasName("OrderDate");

    entity.HasIndex(e => e.ShipPostalCode)
        .HasName("ShipPostalCode");

    entity.HasIndex(e => e.ShipVia)
        .HasName("ShippersOrders");

    entity.HasIndex(e => e.ShippedDate)
        .HasName("ShippedDate");

    entity.Property(e => e.CustomerID).HasColumnType("nchar(5)");

    entity.Property(e => e.Freight)
        .HasColumnType("money")
        .HasDefaultValueSql("0");

    entity.Property(e => e.OrderDate).HasColumnType("datetime");

    entity.Property(e => e.RequiredDate).HasColumnType("datetime");

    entity.Property(e => e.ShippedDate).HasColumnType("datetime");
});
```

SqlServer db type is made of the type and length. If the type is default for given clr type we generate annotation for length. If type is different from default then we generate fluent api. (like `nchar(5)`)
But according to
https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Relational/Metadata/Conventions/Internal/RelationalColumnAttributeConvention.cs#L21
We set the column type same as what is specified on the data-annotation. So `nchar(5)` should also be able to specified using `ColumnAttribute`

**Comment by rowanmiller** [comment] 2016-05-17 17:15
This seems to be a dupe of https://github.com/aspnet/EntityFramework/issues/5289 - we should be using the `[Column]` annotation to specify types that need to be manually set, regardless of whether they have a length or not.

Feel free to reopen if we missed something 😄

**Comment by smitpatel** [comment] 2016-05-17 17:21
During my discussion with @lajones , he mentioned that there is some issue on using data annotations specifically for the case when a length specified so I filed separate issue otherwise they are the same.
I also believe that all types (with or without length) can be specified using data annotations.

**Comment by lajones** [comment] 2016-05-17 17:27
Sorry if I wasn't clear. The rule is if you are mapped to a the "default" type (e.g. C# string maps to SQL Server `nvarchar`) then you should use `[MaxLength]` and should _not_ have the `[Column(..., TypeName="type_includes_the_length")]` annotation. But if you map to a non-default type then you need `[Column(..., TypeName="type_includes_the_length")]` and any `[MaxLength]` will be ignored.

But we already do this - so no need for any extra issue tracking that.

**Comment by rowanmiller** [comment] 2016-05-17 17:28
👍

**Closed** 2022-10-16 09:39 UTC
