### ISSUE TITLE
Cosmos: Narrow gap between EF and SDK LINQ provider

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#25764] opened 2021-08-28 07:44 UTC
https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-linq-to-sql

Partial issue list:

* [ ] #25701
* [ ] #25700
* [ ] #17312
* [ ] #17317

**Comment by AndriySvyryd** [comment] 2024-02-10 05:25
Is this just a dupe of https://github.com/dotnet/efcore/issues/33033 now?

**Comment by ajcvickers** [comment] 2024-02-10 11:40
@AndriySvyryd Yeah, I'm going to go do the older composites for cosmos and see if they need retaining for anything.

**Closed** 2024-03-07 09:01 UTC
Labels: type-enhancement, area-query, area-cosmos, composite-issue
