### ISSUE TITLE
Sum of float may return double and throw InvalidCastException

### ISSUE THREAD

**Issue by ahumeniy** [dotnet/efcore#5892] opened 2016-06-29 00:35 UTC
### Steps to reproduce

With model:

```
public class Product{
    public int Id {get; set;}
    pubic string Name {get; set;}
    public float Value {get; set;}
}
```

Execute query 

`var sum = context.Products.Sum(x=>x.Value);`

When there are lots of records. This happened when the sum was round 500,000 (five hunded thousands) but may happen with lower amounts. Notice that's still below the maximum amount float can hold.
### The issue

The operation fails with InvalidCastException:

```
Exception message: Unable to cast object of type 'System.Double' to type 'System.Single'.
Stack trace:
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
   at System.Linq.Queryable.Sum[TSource](IQueryable`1 source, Expression`1 selector)
   at {internal calls from my application}
```
### Workaround

I can work around the problem replacing the operation:

`var sum = (float) context.Products.Sum(x=> (double)x.Value);`
### Further technical details

EF Core version: 

```
Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14372
 OS Platform: Windows
 RID:         win10-x64
```

Operating system: Windows 10 x64
Visual Studio version: VS 2015

**Comment by smitpatel** [comment] 2017-06-08 22:52
closing as dupe of #7136 Which is already fixed 2.0.0-preview1

**Closed** 2017-06-08 22:52 UTC
Labels: closed-duplicate
