### ISSUE TITLE
Load related entities on attribute access

### ISSUE THREAD

**Issue by daniel3303** [dotnet/efcore#22673] opened 2020-09-22 20:31 UTC
Suppose you have the following class.

```csharp
 public class Request {
        public int Id { get; private set;  }
        private readonly List<Store> _stores = new List<Store>();
        public virtual IReadOnlyList<Store> Stores => _stores;
        
        private readonly List<Brand> _brands = new List<Brand>();
        public virtual IReadOnlyList<Brand> Brands => _brands;

        public Request() { }
        
        public Request AddStore(Store store) {
            if (!Stores.Contains(store) && store != null) {
                _stores.Add(store);
                store.AddRequest(this);
                
                foreach (var brand in Brands) {
                    // do something
                }
            }
            return this;
        }
        
        public Request AddBrand(Brand brand) {
            if (!Brands.Contains(brand) && brand != null) {
                _brands.Add(brand);
                brand.AddRequest(this);
                foreach (var store in Stores) {
                    // do something
                }
            }
            return this;
        }
    }

```
Ir order to access the related Stores or Brand you need to explicitly read from the property Stores or Brands. If you try to access the attributes _stores or _brands before accessing the corresponding properties you will get an empty list. This may cause confusion.

I propose that the original Lists are replaces by some proxy that will load the related entities when the attribute is accessed, making the following code work. Of course, we could not use readonly properties for this to work.

```csharp
public class Request {
        public int Id { get; private set;  }
        
        private readonly List<Store> _stores = new List<Store>();
        public virtual IReadOnlyList<Store> Stores => _stores;
        
        private readonly List<Brand> _brands = new List<Brand>();
        public virtual IReadOnlyList<Brand> Brands => _brands;

        public Request() { }
        
        public Request AddStore(Store store) {
            if (!_stores.Contains(store) && store != null) {
                _stores.Add(store);
                store.AddRequest(this);
                
                foreach (var brand in _brands) {
                    // do something
                }
            }
            return this;
        }
        
        public Request AddBrand(Brand brand) {
            if (!_brands.Contains(brand) && brand != null) {
                _brands.Add(brand);
                brand.AddRequest(this);
                foreach (var store in _stores) {
                    // do something
                }
            }
            return this;
        }
    }

```

**Comment by ajcvickers** [comment] 2020-09-23 20:57
@daniel3303 I assume by "attribute" here you mean ["field"](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/fields) in C#/.NET parlance. If not, can you explain more?

> I propose that the original Lists are replaces by some proxy that will load the related entities when the attribute is accessed

Do you have a suggestion how that replacement should happen?

**Comment by ajcvickers** [comment] 2020-10-02 15:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:41 UTC
Labels: closed-no-further-action, customer-reported
