### ISSUE TITLE
Include queries are not consistently loading relationships

### ISSUE THREAD

**Issue by arendvw** [dotnet/efcore#15244] opened 2019-04-03 10:06 UTC
I have two tables. An Article table and a ArticleVersion table.  (see definition below)

When using a select query with an include, the included relationship is loaded properly for the first 70 records, afterwards all included relationships are empty; while these records definitely have relationships in the database.

This issue does not occur when the data is paginated in batches of 20. (skip/take the query below in batches of 20/30);

The debug log shows fine, and this is also returns the correct data when run as SQL query

```sql
      SELECT [a.Versions].[Id], [a.Versions].[ArticleName]
      FROM [ArticleVersion] AS [a.Versions]
      INNER JOIN (
          SELECT [a0].[Name]
          FROM [Article] AS [a0]
      ) AS [t] ON [a.Versions].[ArticleName] = [t].[Name]
      ORDER BY [t].[Name]
```

Am I missing something obvious? Are there any suggestions on how to debug this further?

#### Query to reproduce

```C#
    var query = _dbContext.Article
        .Include(a => a.Versions)
        .ToList();

    foreach (var article in data)
    {
        var db = _dbContext.ArticleVersion.Where(v => v.ArticleName == item.Name).ToList();
        if (item.Versions.Count != db.Count)
        {
            throw new Exception("Data does not match up with database");
        }
    }
```

#### Datamodel to reproduce

```C#
    public class Article
    {
        [StringLength(20, MinimumLength = 6)]
        [Required]
        [Key]
        public string Name { get;set; }
        
        public List<ArticleVersion> Versions { get; set; }
    }

    public class ArticleVersion
    {
        public int Id { get; set; }

        [StringLength(20, MinimumLength = 6)]
        [Required]
        public string ArticleName { get; set; }

        public Article Article { get; set; }
    }
```

And with fluent/dbcontext settings:

```C#
    modelBuilder.Entity<ArticleVersion>()
        .HasOne(v => v.Article)
        .WithMany(a => a.Versions)
        .HasForeignKey(a => a.ArticleName)
        .OnDelete(DeleteBehavior.Restrict);
```

### Further technical details
EF Core version: 2.2.3 
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 15.9.9

**Comment by ajcvickers** [comment] 2019-04-03 15:41
@arendvw I have not been able to reproduce this--my code is below. Please post a small, runnable project/solution or complete code listing (like below) that demonstrates the behavior you are seeing.

```C#
public class Article
{
    [StringLength(20, MinimumLength = 6)]
    [Required]
    [Key]
    public string Name { get;set; }
        
    public List<ArticleVersion> Versions { get; set; }
}

public class ArticleVersion
{
    public int Id { get; set; }

    [StringLength(20, MinimumLength = 6)]
    [Required]
    public string ArticleName { get; set; }

    public Article Article { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    public DbSet<Article> Article { get; set; }
    public DbSet<ArticleVersion> ArticleVersion { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ArticleVersion>()
            .HasOne(v => v.Article)
            .WithMany(a => a.Versions)
            .HasForeignKey(a => a.ArticleName)
            .OnDelete(DeleteBehavior.Restrict);
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            for (var i = 0; i < 100; i++)
            {
                var article = new Article {Name = $"A{i}", Versions = new List<ArticleVersion>()};

                for (var j = 0; j < 100; j++)
                {
                    article.Versions.Add(new ArticleVersion());
                }

                context.Add(article);
            }

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var query = context.Article
                .Include(a => a.Versions)
                .ToList();

            foreach (var article in query)
            {
                var db = context.ArticleVersion.Where(v => v.ArticleName == article.Name).ToList();
                
                if (article.Versions.Count != db.Count)
                {
                    throw new Exception("Data does not match up with database");
                }
            }
        }
    }
}
```

**Comment by ajcvickers** [comment] 2019-04-11 15:23
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:58 UTC
Labels: closed-could-not-reproduce, customer-reported
