### ISSUE TITLE
Connection state is coming as closed in First itteration when selecting table data

### ISSUE THREAD

**Issue by archanasoni** [dotnet/efcore#7129] opened 2016-11-25 14:30 UTC
**Issue**
Our IBM EntityFramework Core Provider is based MS EF Core 1.0.1 . We have written MVC EF Application using IBM EntityFramework Core provider by following below link:
https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db

It just selects data from table. When we run application we are getting error:
AggregateException: An error occurred while writing to logger(s). (Invalid operation. The connection is closed.)

On Debugging, we figured out that From MS EF layer to IBM EF layer we have 3 times call for 
```C#
 public Db2QuerySqlGenerator(
            [NotNull] IRelationalCommandBuilderFactory relationalCommandBuilderFactory,
            [NotNull]ISqlGenerationHelper sqlGenerationHelper,
            [NotNull] IParameterNameGeneratorFactory parameterNameGeneratorFactory,
            [NotNull] IRelationalTypeMapper relationalTypeMapper,
            [NotNull] SelectExpression selectExpression,                   
                      IRelationalConnection connection) 
            : base(relationalCommandBuilderFactory,
                sqlGenerationHelper,
                parameterNameGeneratorFactory,
                relationalTypeMapper,
                selectExpression)
```
And in first iteration Connection state is coming as closed. Please note Connection Object is created but its state is closed.
Since We have one common provider for all DB2 Servers, We require to get database server type. We already had discussion about the implementation here https://github.com/aspnet/EntityFramework/issues/2636

In user\test application scenario Connection state is closed and it throws error.

If we change our user\test application context class from
```C#
 public class TestContext: DbContext
    {

        public TestContext(DbContextOptions<TestContext> options) : base(options) { }
........
.......
}
```
to
```C# 
 public class TestContext: DbContext
    {

        public TestContext() : base() { }
       protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
                        optionsBuilder.UseDb2(ConnectionString);
        }
...
...
}
```
Application works perfectly because Connection state is coming as Opened.

Why is Connection state coming as closed in First call of method Db2QuerySqlGenerator(....) from MS layer when we have context class implementation like below:
```C#
public class TestContext: DbContext
    {

        public TestContext(DbContextOptions<TestContext> options) : base(options) { }
........
.......
}
```
Regards,
Archana

**Comment by ajcvickers** [comment] 2016-11-28 18:02
@archanasoni Can you post the code that creates the DbContextOptions object passed to the constructor and also the implementation of the UseDb2 method?

**Comment by archanasoni** [comment] 2016-11-29 13:35
@ajcvickers, We are not creating DbContextOptions object any where. we register the service and as per the article dependency injection takes care:
https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db
"
_You'll notice that the controller takes a BloggingContext as a constructor parameter. ASP.NET dependency injection will take care of passing an instance of BloggingContext into your controller._"

Implementation for UseDb2 is below:
 public static DbContextOptionsBuilder UseDb2 (
             [NotNull] this DbContextOptionsBuilder optionsBuilder ,
			 [NotNull] string connectionString,
			 [CanBeNull] Action<Db2DbContextOptionsBuilder> Db2OptionsAction = null )
        {
            Check.NotNull(optionsBuilder, nameof(optionsBuilder));
            Check.NotEmpty(connectionString, nameof(connectionString));

            var extension = GetOrCreateExtension(optionsBuilder);

            extension.ConnectionString = connectionString;

            ((IDbContextOptionsBuilderInfrastructure)optionsBuilder).AddOrUpdateExtension(extension);

            Db2OptionsAction?.Invoke(new Db2DbContextOptionsBuilder(optionsBuilder));
			
            return optionsBuilder;

        }

**Comment by ajcvickers** [comment] 2016-11-29 16:55
@archanasoni In that case it could you show the code that sets up the service provider and calls AddDbContext? Also, are you using this in a standard web app with MVC and having the context injected into the controller? If not, how are you managing the service provider and creating scopes? Can you show code for that?

**Comment by archanasoni** [comment] 2016-11-30 11:41
@ajcvickers, We are using standard Web App with MVC. Controller and DBContext  are defined, same as what is described in article. Database and object already exist. 
Below is call hierarchy :

>	IBM.EntityFrameworkCore.dll!IBM.EntityFrameworkCore.Db2DbContextOptionsExtensions.UseDb2(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder optionsBuilder, string connectionString, System.Action<IBM.EntityFrameworkCore.Infrastructure.Db2DbContextOptionsBuilder> Db2OptionsAction) Line 39	C#
 	WebApplication3.dll!WebApplication3.Startup.ConfigureServices.AnonymousMethod__0(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder options) Line 39	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.DbContextOptionsFactory<WebApplication3.Model.LuwContext>(System.IServiceProvider applicationServiceProvider, System.Action<System.IServiceProvider, Microsoft.EntityFrameworkCore.DbContextOptionsBuilder> optionsAction)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.Internal.ActivatorUtilities.GetService(System.IServiceProvider sp, System.Type type, System.Type requiredBy, bool isDefaultParameterRequired)	Unknown
 	[Lightweight Function]	
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Internal.TypeActivatorCache.CreateInstance<object>(System.IServiceProvider serviceProvider, System.Type implementationType)	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory.CreateController(Microsoft.AspNetCore.Mvc.ControllerContext context)	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeAllActionFiltersAsync()	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAllActionFiltersAsync>d__26>(ref Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAllActionFiltersAsync>d__26 stateMachine)	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeAllActionFiltersAsync()	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeExceptionFilterAsync()	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeExceptionFilterAsync>d__25>(ref Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeExceptionFilterAsync>d__25 stateMachine)	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeExceptionFilterAsync()	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeResourceFilterAsync()	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResourceFilterAsync>d__23>(ref Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResourceFilterAsync>d__23 stateMachine)	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeResourceFilterAsync()	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeResourceFilterAsync()	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResourceFilterAsync>d__23>(ref Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResourceFilterAsync>d__23 stateMachine)	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeResourceFilterAsync()	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeAsync()	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18>(ref Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18 stateMachine)	Unknown
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeAsync()	Unknown
 	Microsoft.AspNetCore.Routing.dll!Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext httpContext)	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4>(ref Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4 stateMachine)	Unknown
 	Microsoft.AspNetCore.Routing.dll!Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext httpContext)	Unknown
 	Microsoft.AspNetCore.StaticFiles.dll!Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext context)	Unknown
 	Microsoft.ApplicationInsights.AspNetCore.dll!Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext httpContext)	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d__4>(ref Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d__4 stateMachine)	Unknown
 	Microsoft.ApplicationInsights.AspNetCore.dll!Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext httpContext)	Unknown
 	Microsoft.VisualStudio.Web.BrowserLink.Runtime.dll!Microsoft.VisualStudio.Web.BrowserLink.Runtime.BrowserLinkMiddleware.ExecuteWithFilter(Microsoft.VisualStudio.Web.BrowserLink.Runtime.IHttpSocketAdapter visualStudioSocket, string requestId, Microsoft.AspNetCore.Http.HttpContext httpContext)	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.VisualStudio.Web.BrowserLink.Runtime.BrowserLinkMiddleware.<ExecuteWithFilter>d__7>(ref Microsoft.VisualStudio.Web.BrowserLink.Runtime.BrowserLinkMiddleware.<ExecuteWithFilter>d__7 stateMachine)	Unknown
 	Microsoft.VisualStudio.Web.BrowserLink.Runtime.dll!Microsoft.VisualStudio.Web.BrowserLink.Runtime.BrowserLinkMiddleware.ExecuteWithFilter(Microsoft.VisualStudio.Web.BrowserLink.Runtime.IHttpSocketAdapter visualStudioSocket, string requestId, Microsoft.AspNetCore.Http.HttpContext httpContext)	Unknown
 	Microsoft.VisualStudio.Web.BrowserLink.Runtime.dll!Microsoft.VisualStudio.Web.BrowserLink.Runtime.BrowserLinkMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext context)	Unknown
 	Microsoft.AspNetCore.Diagnostics.dll!Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext context)	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6>(ref Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6 stateMachine)	Unknown
 	Microsoft.AspNetCore.Diagnostics.dll!Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext context)	Unknown
 	Microsoft.ApplicationInsights.AspNetCore.dll!Microsoft.ApplicationInsights.AspNetCore.RequestTrackingMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext httpContext, Microsoft.ApplicationInsights.DataContracts.RequestTelemetry telemetry)	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.ApplicationInsights.AspNetCore.RequestTrackingMiddleware.<Invoke>d__4>(ref Microsoft.ApplicationInsights.AspNetCore.RequestTrackingMiddleware.<Invoke>d__4 stateMachine)	Unknown
 	Microsoft.ApplicationInsights.AspNetCore.dll!Microsoft.ApplicationInsights.AspNetCore.RequestTrackingMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext httpContext, Microsoft.ApplicationInsights.DataContracts.RequestTelemetry telemetry)	Unknown
 	Microsoft.AspNetCore.Server.IISIntegration.dll!Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext httpContext)	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__8>(ref Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__8 stateMachine)	Unknown
 	Microsoft.AspNetCore.Server.IISIntegration.dll!Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext httpContext)	Unknown
 	Microsoft.AspNetCore.Hosting.dll!Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext httpContext)	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3>(ref Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3 stateMachine)	Unknown
 	Microsoft.AspNetCore.Hosting.dll!Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext httpContext)	Unknown
 	Microsoft.AspNetCore.Hosting.dll!Microsoft.AspNetCore.Hosting.Internal.HostingApplication.ProcessRequestAsync(Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context context)	Unknown
 	Microsoft.AspNetCore.Server.Kestrel.dll!Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame<Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context>.RequestProcessingAsync()	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunnerWithContext.RunWithCapturedContext()	Unknown
 	Microsoft.AspNetCore.Server.Kestrel.dll!Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.LoggingThreadPool..ctor.AnonymousMethod__4_0(object o)	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown

**Comment by ajcvickers** [comment] 2016-11-30 17:14
@archanasoni I'm running out of ideas. There should be no difference in behavior between using OnConfiguring and AddDbContext. Can you post the full code for your implementation of the RelationalOptionsExtension class and the class that contains the UseDb2 method?  Also, can you check that your implementation of QuerySqlGeneratorFactoryBase is registered as scoped?

**Comment by ajcvickers** [comment] 2016-12-07 17:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Comment by archanasoni** [comment] 2017-03-02 10:57
Still we have same issue and we are using EF Core 1.0.1.
To proceed further, Which path would you prefer- Either we can provide the data points which were asked Or we can also share some sample repro with Nuget pkg. This sample repro would require DB2 database to connect and repro the issue. Do you have any existing DB2 server ?

**Comment by rowanmiller** [comment] 2017-03-02 17:36
@archanasoni please open a new issue. Including some code we can run is great. Here is the info on the DB2 provider https://docs.microsoft.com/en-us/ef/core/providers/ibm/.

**Comment by archanasoni** [comment] 2017-04-11 09:58
Opened issue #8125  to discuss further.

**Closed** 2022-10-16 10:44 UTC
