### ISSUE TITLE
Delete operation sets null to navigation property

### ISSUE THREAD

**Issue by TonyTroeff** [dotnet/efcore#20456] opened 2020-03-29 16:14 UTC
This is the structure of my database:

 1. One User can have many Categories
 2. One Category can have many Tags.
 3. One Tag can have many Transfer.
 4. One User can have many Accounts.
 5. One Account can have many transfers.

Following the EF Core guidelines on using nullable navigation properties, this is the code for the `Author` navigation property between the `Category` and `User` relationship.

``` C#
private User? _author;
public User Author
{
    get => this._author ?? throw new InvalidOperationException(...); 
    set => this._author = value ?? throw new ArgumentNullException(nameof(value));
}
```

However when I try to delete a `User`, EF Core invokes both the setter (setting value of `null`) and the getter of that navigation property. Which apparently will cause exceptions to be thrown.

All relations are required and have cascade behavior so I do not understand why null value should be set to that property...

This is the stack trace:

> System.ArgumentNullException: Value cannot be null. (Parameter 'value')
       at TryAtSoftware.ExpenseTracker.Data.Models.Category.set_Author(User value) in D:\C#\TryAtSoftware.ExpenseTracker\ExpenseTracker\TryAtSoftware.ExpenseTracker.Data\Models\Category.cs:line 29
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.WritePropertyValue(IPropertyBase propertyBase, Object value, Boolean forMaterialization)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete, CurrentValueType valueType)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.SetNavigation(InternalEntityEntry entry, INavigation navigation, InternalEntityEntry value, Boolean fromQuery)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.DeleteFixup(InternalEntityEntry entry)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.FireStateChanged(EntityState oldState)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.AcceptChanges()
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.AcceptAllChanges(IReadOnlyList`1 changedEntries)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
       at TryAtSoftware.ExpenseTracker.Repositories.RepositoryHelper.SafelySaveChangesAsync(ExpenseTrackerDbContext dbContext, CancellationToken cancellationToken) in D:\C#\TryAtSoftware.ExpenseTracker\ExpenseTracker\TryAtSoftware.ExpenseTracker.Repositories\RepositoryHelper.cs:line 23

### Further technical details

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 Enterprise 16.5.1

**Comment by TonyTroeff** [comment] 2020-03-29 16:15
If you want to see the code, this is the repository of my project - https://dev.azure.com/TryAtSoftware/ExpenseTracker

You can debug that test:
![image](https://user-images.githubusercontent.com/33567383/77854229-9b9c7300-71f1-11ea-90c1-c93ccf656920.png)

**Comment by ajcvickers** [comment] 2020-04-02 22:09
@TonyTroeff I cloned your repo and ran the tests on master, but didn't see any failures. Is there a specific branch I need?

**Comment by TonyTroeff** [comment] 2020-04-03 06:40
Yes, I made a temporary workaround:
![image](https://user-images.githubusercontent.com/33567383/78331605-15848180-758f-11ea-96b3-2d96756cef72.png)
You can remove lines 196 and 197 from TryAtSoftware.ExpenseTracker.Repositories/UserRepositories/UserRepository.cs

**Comment by ajcvickers** [comment] 2020-04-03 21:41
@TonyTroeff Thanks--this repros for me now.

Team: The issue here is that a non-nullable reference navigation property is not picking up the nullable reference as a backing field.

```
  EntityType: Category
    Properties: 
      Id (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd
      AuthorId (Guid) Required FK Index
      Description (string)
      IsGlobal (bool) Required
      Name (string) Required
    Navigations: 
      Author (no field, User) ToPrincipal User Inverse: Categories
      Tags (ICollection<Tag>) Collection ToDependent Tag Inverse: Category
    Keys: 
      Id PK
    Foreign keys: 
      Category {'AuthorId'} -> User {'Id'} ToDependent: Categories ToPrincipal: Author
```

**Comment by TonyTroeff** [comment] 2020-04-04 14:34
But why this problem occurs only with that relation. I mean that there are other entities that are connected the same way but such a problem has not occurred. And also, is there something wrong in the database configuration so I have encountered that problem?

**Comment by ajcvickers** [comment] 2020-04-06 15:10
@TonyTroeff Yes, this is a bug. We haven't yet investigated why it is happening only in this case.

**Comment by ajcvickers** [comment] 2020-06-16 21:36
@TonyTroeff I am no longer able to reproduce this, and it looks like your code has changed since you filed the issue. Are you able to point me to a branch that fails or provide a repo in some other way?

**Comment by ajcvickers** [comment] 2020-07-06 15:22
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:18 UTC
Labels: closed-could-not-reproduce, customer-reported
