### ISSUE TITLE
Reverse Engineer: projects with space getting the wrong namespace

### ISSUE THREAD

**Issue by neville-nazerane** [dotnet/efcore#10916] opened 2018-02-08 03:32 UTC
When I use `Scaffold-DbContext` to reverse engineer a project whose name has a space, for instance "test db", Generated c# files use generate the namespace as "test db.Models" instead of "test_db.Models"

**Comment by bricelam** [comment] 2018-02-08 22:06
Duplicate of dotnet/sdk#1564

**Closed** 2022-10-16 12:08 UTC
Labels: closed-external
