### ISSUE TITLE
Columns are not generated by default for base properties 

### ISSUE THREAD

**Issue by myshon** [dotnet/efcore#9798] opened 2017-09-13 09:07 UTC
Is it intentional that columns are not generated by default for base properties?
I have following classes: 

```
public class Contact : ValueObject<Contact>
 {
        public string Name { get; private set; }
        public string Phone { get; private set; }
        public string Email { get; private set; }

        public Contact(string name, string phone, string email)
        {
            Name = name;
            Phone = phone;
            Email = email;
        }
        protected Contact() { }
}

public class CustomerContact : Contact
{
       public string AdditionalInfo { get; set; }

        private CustomerContact () { } 

        public CustomerContact (string name, string phone, string email, string additionalInfo)
            : base(name, phone, email)
        {
            AdditionalInfo = additionalInfo;
        }
}
```

and only `CustomerContact` mapped as value object

```
modelBuilder.Entity<CustomerContact>(b =>
{
    b.Property<Guid>("Id").ValueGeneratedOnAdd();
    b.HasKey("Id");
});
```
When I add migration then it generates
```
migrationBuilder.CreateTable(
	name: "CustomerContract",
	schema: "Configuration",
	columns: table => new
	{
		Id = table.Column<Guid>(nullable: false),
		AdditionalInfo = table.Column<string>(nullable: true)
	},
	constraints: table =>
	{
		table.PrimaryKey("PK_CustomerContact", x => x.Id);
	});
```

Expected result: generate columns for base properties (Name, Phone, Email) by default. 
Actual result: no columns for base properties. 

### technical details
EF Core version: 1.1.2.0
Database Provider: Npgsql.EntityFrameworkCore.PostgresSQL 1.1.0
Operating system: Windows 10 Enterprise
IDE: (e.g. Visual Studio 2017 Professional)

**Comment by fgheysels** [comment] 2017-09-13 11:17
I think this is due to the fact that the setters for those properties are private.
I have opened an [issue](https://github.com/aspnet/EntityFrameworkCore/issues/9705) that is related to this.

**Comment by ajcvickers** [comment] 2017-09-13 16:25
Duplicate of #9705

**Closed** 2022-10-16 11:49 UTC
Labels: closed-duplicate
