### ISSUE TITLE
Nestandard, EFCore 2.1 and migrations

### ISSUE THREAD

**Issue by raffaeler** [dotnet/efcore#12171] opened 2018-05-30 15:01 UTC
It is currently not possible to run migrations (using PS command) on netstandard class libraries.
I am running EFCore 2.1 over NetCore 2.0.

If I run migrations on a NetCore console using this context, I get an error
```C#
public class AcmeContext : DbContext
{
    private SeedDataContainer _seedDataContainer;

    // you can comment or uncomment this one, it makes no difference
    public AcmeContext()
    {
    }

    public AcmeContext(DbContextOptions<AcmeContext> options) : base(options)
    {
        _seedDataContainer = new SeedDataContainer();
    }

    public static AcmeContext Create(DbContextOptions<AcmeContext> options,
        SeedDataContainer seedDataContainer)
    {
        var context = new AcmeContext(options);
        context._seedDataContainer = seedDataContainer ?? new SeedDataContainer();
        return context;
    }

    public DbSet<Person> People { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>().ToTable("Person").HasData(_seedDataContainer.GetSeedData<Person>());
    }
}

```
The result of `Add-Migration InitialCreate` is the following confusing error which does not reveal the real problem.
```
System.MissingMethodException: No parameterless constructor defined for this object.
```

If instead I run `C:\temp>dotnet ef` the error is:
```
No executable found matching command "dotnet-ef"
``` 

The csproj is the following:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Acme.Models\Acme.Models.csproj" />
  </ItemGroup>

  <!--<ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
  </ItemGroup>-->

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Design" Version="1.1.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
  </ItemGroup>

  <Import Project="..\Acme.Data.Shared\Acme.Data.Shared.projitems" Label="Shared" />

</Project>
```

The developer experience is bad.
If the netstandard scenario alone cannot be supported, enable (and document) the scenario of referencing a netstandard library from a netcore console application.

The workaround is to run migrations by code and it works.

**Comment by raffaeler** [comment] 2018-05-30 15:12
There is no 2.1 release for `Microsoft.EntityFrameworkCore.Tools.DotNet`

**Comment by raffaeler** [comment] 2018-05-30 15:44
yep, I they are referenced, but they doesn't work as expected.
Even worse, the error message is super-misleading.

**Comment by ajcvickers** [comment] 2018-05-31 20:27
@raffaeler A few questions/comments:
* Are you using the Package Manager Console (PMC) or the dotnet command line?
  * Docs for PMC: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell
  * Docs for dotnet CLI: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet
* Targeting .NET Standard class libraries is problematic since there is no target framework on which the EF code can run during tooling. Therefore, we recommend that you create a dummy project targeting some framework such that it is possible for the tools to execute code. See https://github.com/aspnet/EntityFramework.Docs/issues/581
* The Microsoft.EntityFrameworkCore.Sqlite.Design is no longer needed. It should not be referenced.
* The .DotNet package should not be referenced as a normal package reference
  * If you have the 2.1 SDK installed, then remove the DotNetCliToolReference as well, since the tools are now included in the SDK, even if you are targeting .NET Core 2.0.
  * If you are still using 2.0 SDK, then leave the DotNetCliToolReference as is pointing to the 2.0 package.

**Comment by raffaeler** [comment] 2018-05-31 20:39
- PMC vs dotnet. As I wrote, I tried both. PMC was available but I got only errors (see below). The dotnet-ef was not even available and I had to give up.
- Dummy project. None of them worked with a console (not asp.net) NetCore 2.0 project referencing the class library declaring the context. It did work with a console .NET Framework 4.72 referencing the class library instead.
- Sqlite.Design. I would love to see metapackages referencing all the required packages. It is hard to find the docs on what should be referenced and what is obsolete. The nuget page does not mention this either.
- Tool. I was in the middle of the path. I was using efcore 2.1 over netcore 2.0. I will now do it. But again the nuget description should clearly give a message on that. It's hard to understand.

Also please improve the error message error you see above. It is clearly wrong and terribly misleading... I still don't know what went wrong.

Thanks

**Comment by ajcvickers** [comment] 2018-06-04 17:40
Triage: filed https://github.com/aspnet/EntityFramework.Docs/issues/740 for the package issue.

**Comment by ajcvickers** [comment] 2018-06-04 17:41
@raffaeler Can you please post the full stack trace of the exception?

**Comment by raffaeler** [comment] 2018-06-04 17:56
@ajcvickers 
Here is the stack trace:
```
PM> Add-Migration InitialCreate
System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
No parameterless constructor defined for this object.
```

The full code for the Context is:
```
    public class AcmeContext : DbContext
    {
        private SeedDataContainer _seedDataContainer;

        public AcmeContext()
        {
        }

        public AcmeContext(DbContextOptions<AcmeContext> options) : base(options)
        {
            _seedDataContainer = new SeedDataContainer();
        }

        public AcmeContext(DbContextOptions<AcmeContext> options,
            SeedDataContainer seedDataContainer) : base(options)
        {
            _seedDataContainer = seedDataContainer ?? new SeedDataContainer();
        }

        public static AcmeContext Create(DbContextOptions<AcmeContext> options,
            SeedDataContainer seedDataContainer)
        {
            var context = new AcmeContext(options);
            context._seedDataContainer = seedDataContainer ?? new SeedDataContainer();
            return context;
        }

        public DbSet<Person> People { get; set; }
        public DbSet<Consent> Consents { get; set; }
        public DbSet<ConsentApproval> ConsentApprovals { get; set; }
        public DbSet<Category> Categories { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Person>().ToTable("Persons").HasData(_seedDataContainer.GetSeedData<Person>());
            modelBuilder.Entity<Consent>().ToTable("Consents").HasData(_seedDataContainer.GetSeedData<Consent>());
        }

    }
```

The context all the code is inside a shared project that is referenced from both the nestandard library and a dummy console netcore 2.0 app that it was supposed only to run migrations.

**Comment by ajcvickers** [comment] 2018-06-04 21:35
@raffaeler I was not able to reproduce the exception with the code posted. Could you please post the project/solution that reproduces what you are seeing?

**Comment by ajcvickers** [comment] 2018-06-11 18:07
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:27 UTC
Labels: closed-no-further-action, customer-reported
