### ISSUE TITLE
Exception on upgrade [Bug]

### ISSUE THREAD

**Issue by GVX111** [dotnet/efcore#3260] opened 2015-09-29 11:34 UTC
Exception on: Database.Migrate();

<pre>An exception of type 'System.ArgumentException' occurred in EntityFramework.Core.dll but was not handled in user code
Additional information: The properties expression 'u => Convert(Convert(u).Id)' is not valid. The expression should represent a property access: 't => t.MyProperty'. When specifying multiple properties use an anonymous type: 't => new { t.MyProperty1, t.MyProperty2 }'.</pre>

**Comment by NeelBhatt** [comment] 2015-09-29 11:41
I guess the exception occurred because you entered wrong syntax. can you put your code?

**Comment by gvx111** [comment] 2015-09-29 11:45
<pre> public class Account : IdentityUser
    {
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public DateTime Birthdate { get; set; }
        public bool Gender { get; set; }

        public string GetGender()
        {
            return Gender ? "Male" : "Female";
        }
    }
    public class EfContext : IdentityDbContext<Account>
    {
        private static bool _created = false;
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Site> Sites { get; set; }
        public DbSet<Page> Pages { get; set; }

        public EfContext()
        {
            // Create the database and schema if it doesn't exist
            // This is a temporary workaround to create database until Entity Framework database migrations 
            // are supported in ASP.NET 5 
            if (!_created)
            {
                Database.Migrate();
                // this.Configuration.ProxyCreationEnabled = false;
                _created = true;
            }
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=***;Database=***; User Id=**; Password=*****; MultipleActiveResultSets=true");
        }
      
    }

**Comment by gvx111** [comment] 2015-09-29 11:45
Its worked correctly before dnu restore

**Comment by smitpatel** [comment] 2015-09-29 22:57
possible dupe of #3267

**Comment by rowanmiller** [comment] 2015-10-02 18:46
Fixed now (see #3267)

**Closed** 2022-10-16 09:10 UTC
