### ISSUE TITLE
ValueGeneratedOnAdd index is not reset across InMemoryDatabase instances

### ISSUE THREAD

**Issue by aphex-** [dotnet/efcore#7282] opened 2016-12-20 14:35 UTC
I wrote some tests using Xunit. Every [Fact] method creates a new DBContext to test.

```c#
    var services = new ServiceCollection();
    services.AddEntityFrameworkInMemoryDatabase()
        .AddDbContext<ApplicationContext>(
	    options => options.UseInMemoryDatabase(Guid.NewGuid().ToString()));
```

An **User** has the property **ID**

```c#
     protected override void OnModelCreating(ModelBuilder modelBuilder)
     {
          // ...
          modelBuilder.Entity<User>().HasKey(e => e.Id)
          modelBuilder.Entity<User>().Property(f => f.Id).ValueGeneratedOnAdd();
          // ...
     }
```

As test data I add two users without assigning their ids:
```c#
     conext.Users.Add(new User {Name = "Peter"});
     conext.Users.Add(new User {Name = "Paul"});
```

My DBContext sometimes contains: Peter (id:3) and Paul (id:4) if I run the tests. I am not sure if this only occurs on tests that are using a [Theory].

(_If I explicitly set the ids while adding the users it works as expected. This workaround solves the issue in my case._)

### Further technical details
EF Core version:  "Microsoft.NETCore.App": { "version": "1.1.0", "type": "platform" },
Database Provider: InMemoryDatabase
Operating system:  macOS Sierra 10.12.1 
IDE: JetBrains Rider 1.0 EAP

**Comment by ErikEJ** [comment] 2016-12-20 14:40
InMemory is not a relational provider - it is unfortunate the the extension method is named AddEntityFrameworkInMemoryDatabase rather than AddEntityFrameworkInMemoryProvider or similar

**Comment by ajcvickers** [comment] 2016-12-20 18:01
Dupe of #6872

**Closed** 2022-10-16 10:47 UTC
