### ISSUE TITLE
 Linq Query and sever-side sorting with pagination where EF core is producing unexpected results

### ISSUE THREAD

**Issue by LiamDotPro** [dotnet/efcore#10843] opened 2018-02-01 10:37 UTC
Hello,

We are experiencing difficulties with a Linq Query and sever-side sorting with pagination where EF core is producing unexpected results. 

We have outlined our problem in great detail on SO: https://stackoverflow.com/questions/48560609/linq-query-in-ef-core-2-when-using-joins-and-pagination-order-by-column-alias-do

### Further technical details
EF Core version: 2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: WIndows 10
IDE: Visual Studio 15.4.4

**Comment by smitpatel** [comment] 2018-02-01 11:31
Duplicate of #9535

**Comment by LiamDotPro** [comment] 2018-02-01 13:28
Hello @smitpatel we have downloaded and reconfigured our project to use `2.1.0-preview2-30002` and it does not resolve our problem.

**Comment by smitpatel** [comment] 2018-02-01 16:52
@LiamDotPro - Please share a runnable project so that we can debug into the issue.

**Comment by ajcvickers** [comment] 2018-02-12 18:05
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:07 UTC
Labels: closed-could-not-reproduce
