### ISSUE TITLE
LINQ query is failing in VB.NET same query works with same EF in C#

### ISSUE THREAD

**Issue by DurgaprasadKalidandi** [dotnet/efcore#33214] opened 2024-03-01 04:34 UTC
## File a bug

LINQ query is failing in VB.NET, same query works with same EF and provider version (4.5) in C#.

They are getting the following error:

System.InvalidOperationException

HResult=0x80131509

Message=The LINQ expression 'Pra => (IEnumerable<PrRichieste>)Pra.Richiestes' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

Source=Microsoft.EntityFrameworkCore

StackTrace:

at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessSelectMany(NavigationExpansionExpression source, LambdaExpression collectionSelector, LambdaExpression resultSelector)

at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)

at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)

at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)

at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)

at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)

at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)

at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c_DisplayClass9_0`1.<Execute>b_0()

at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)

at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)

at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at ActianZenEfCoreIssues.VB.Program.Main(String[] args) in
### Include your code
[ADO-1474.zip](https://github.com/dotnet/efcore/files/14456476/ADO-1474.zip)

EF Core version:Efcore6
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system:Windows
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by ajcvickers** [comment] 2024-03-01 08:33
Duplicate of #31878

**Closed** 2024-03-06 19:54 UTC
Labels: closed-duplicate, customer-reported
