### ISSUE TITLE
Casting integer to double for division in queries can lead to unexpected / wrong results

### ISSUE THREAD

**Issue by dgschrei** [dotnet/efcore#15528] opened 2019-04-29 21:51 UTC
The usual way to divide two integer values without loosing a fraction is to cast one of the two values to a double so that the runtime evaluates the entire statement as a double.

e.g.  var result  =(double)5 / 2 ;

Doing this inside a Where clause in Entity framework does not seem to work properly. (So far I have only tested this with the Sqlite provider) 

My repro context looks like this:

```
    public class TestContext : DbContext
    {
        public TestContext(DbContextOptions options) : base (options)
        {
            
        }
        
        public DbSet<Entity> Entities { get; set; }
    }

    public class Entity
    {
        public int Id { get; set; }

        public int Prop1 { get; set; }
        public int Prop2 { get; set; }
    }
```

If I now do this on an empty database:

```
context.Entities.Add(new Entity {Prop1 = 30, Prop2 = 100});
context.SaveChanges();

var wrongResult = context.Entities.Where(e => (double)e.Prop1 / e.Prop2 < 0.25).ToList();
//Will print "found 1" 
Console.WriteLine($"Found {wrongResult.Count}");

```
As the comment states, even though 30/100 should produce 0.3 the query will match, which I guess means the cast is somehow lost in the translation to SQL and the query is run in integer mode.

What will work as expected, is if the query is rewritten like this:

 ```
var result = context.Entities.Where(e =>1.0* e.Prop1 / e.Prop2 < 0.25).ToList();
//Will print "found 0" as expected
Console.WriteLine($"Found {result.Count}");
```

This is just highly confusing behavior that I'm sure did not only cause me serious head scratching in the debugger because somehow "the math" didn't work.

full repro solution attached

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityframeworkCore.Sqlite
Operating system:  Windows 10 x64 1809
IDE: VS 2017 15.8.4

**Comment by smitpatel** [comment] 2019-04-29 21:53
Duplicate of #13908

**Closed** 2022-10-16 14:19 UTC
Labels: customer-reported
