### ISSUE TITLE
Compiled Query with Struct Parameter Evaluating In-Memory

### ISSUE THREAD

**Issue by akozmic** [dotnet/efcore#14857] opened 2019-02-27 20:33 UTC
###Describe what is not working as expected.
Compiled Query not working as expected when taking struct as input parameter.  Full details can be found here: https://stackoverflow.com/questions/54909758/entity-framework-core-2-2-compiled-query-struct-parameter-evaluating-locally/54910798

When taking in struct pagingOptions to compiled query - its pulling ALL rows and then evaluating Skip and Take in-memory. 

warn: Microsoft.EntityFrameworkCore.Query[20500]
  => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
  The LINQ expression 'Skip(__paging.Skip)' could not be translated 
and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
  => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
  The LINQ expression 'Take(__paging.Take)' could not be translated 
and will be evaluated locally.

### Steps to reproduce
Pull Down https://github.com/akozmic/EntityFrameworkCore_StructParameterInCompiledQuery and run the project.  See Debug window for logging output.  You may need to adjust the connection string to fit your local environment.  

### Further technical details
EF Core version: 2.2.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Microsoft Windows Server 2016
IDE: Visual Studio 2017 15.9.7

**Comment by smitpatel** [comment] 2019-02-27 20:49
Duplicate of #13976

**Closed** 2022-10-16 13:54 UTC
Labels: closed-duplicate, customer-reported
