### ISSUE TITLE
Missing Exception information

### ISSUE THREAD

**Issue by Bjego** [dotnet/efcore#17569] opened 2019-05-27 08:40 UTC
In your text it says:
Asynchronously returns the only element of a sequence, and throws an exception if there is not exactly one element in the sequence.
But you don't list them.
I assume they are equal to the exceptions listed in Single + Task Cancellation... 
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.single?view=netframework-4.8 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b7deb0-a592-b6dc-1564-fba73a4dcb4c
* Version Independent ID: 1836b7d9-419e-d8a4-51ff-09f504a56462
* Content: [EntityFrameworkQueryableExtensions.SingleAsync Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.singleasync?view=efcore-2.1#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-02 17:28
Duplicate of #17564

**Closed** 2022-10-16 14:39 UTC
Labels: closed-duplicate
