### ISSUE TITLE
Seed nullable guid with default value  

### ISSUE THREAD

**Issue by c1kad14** [dotnet/efcore#22464] opened 2020-09-09 12:09 UTC
If you have model with nullable guid as a foreign key reference:
```
    public class MyClass
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public Guid? AnotherClassId { get; set; }
        public MyClass AnotherClass { get; set; }
    }
```
And try to seed with default data with any of these approaches:

```
builder.Entity<MyClass>().HasData(new MyClass { Id = Guid.NewGuid(), Name = "First" });
builder.Entity<MyClass>().HasData(new MyClass { Id = Guid.NewGuid(), Name = "Second", AnotherClassId = default });
builder.Entity<MyClass>().HasData(new MyClass { Id = Guid.NewGuid(), Name = "Third", AnotherClassId = null });
builder.Entity<MyClass>().HasData(new MyClass { Id = Guid.NewGuid(), Name = "Fourth", AnotherClassId = (Guid?)null });
builder.Entity<MyClass>().HasData(new MyClass { Id = Guid.NewGuid(), Name = "Fifth", AnotherClassId = (Guid?)default });

```
All of these seeds will generate next code:
```
            migrationBuilder.InsertData(
                table: "MyClasses",
                columns: new[] { "Id", "AnotherClassId", "Name" },
                values: new object[] { new Guid("4df3edf6-0b7c-46a4-af44-b069c4d5c07e"), "First" })
```

That cause this exception:
***
The number of values (2) doesn't match the number of columns (3) for the data insertion operation on 'MyClasses'. Provide the same number of values and columns.
***
### Further technical details

EF Core version:
5.0.0-preview.8.20407.4

**Comment by skclusive** [comment] 2020-09-10 18:26
about to raise the same issue. this bug is reproducible in last few preview releases. i have a repository with reproducible code [EFNullableSeedBug](https://github.com/skclusive/EFNullableSeedBug)

**Comment by AndriySvyryd** [comment] 2020-09-11 16:03
Duplicate of https://github.com/dotnet/efcore/issues/21244

**Closed** 2022-10-16 18:40 UTC
Labels: closed-duplicate, customer-reported
