### ISSUE TITLE
Is there any progress on adding a DTABASE NOW approach at the efcore level

### ISSUE THREAD

**Issue by lindalinya** [dotnet/efcore#29549] opened 2022-11-14 07:40 UTC
In most businesses, relying on client time, UTC or not, is an unreliable thing. Of course, we also know that there are many ways to implement this function in our business projects. 
I would like to ask if the community has the ability to support the acquisition of DATABASE NOW at the EFCore level. If not, will you consider adding such interfaces for each driver to implement in the future?

**Comment by roji** [comment] 2022-11-14 08:13
@lindalinya can you please provide more details on what you're asking? You can already get the current database time in EF queries by invoking DateTime.UtcNow in your LINQ queries (this translates to [GETUTCDATE](https://learn.microsoft.com/en-us/sql/t-sql/functions/current-timestamp-transact-sql?view=sql-server-ver16) on SQL Server).

**Comment by ajcvickers** [comment] 2022-11-23 12:58
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-11-23 12:58 UTC
Labels: customer-reported
