### ISSUE TITLE
SqliteMigrationsSqlGenerator doesn't supports One-to-One and One-to-Many relationships to the same entity.

### ISSUE THREAD

**Issue by Suchiman** [dotnet/efcore#3041] opened 2015-09-06 23:45 UTC
Using `7.0.0-beta8-15623` when you try to define a One-to-One and a One-to-Many relationship between the same entities you will receive following exception:

```
Unhandled System.NotSupportedException
  HResult=-2146233067
  Message=SQLite cannot support this migration operation.
  Source=EntityFramework.Sqlite
  StackTrace:
       at Microsoft.Data.Entity.Migrations.SqliteMigrationsSqlGenerator.Generate(AddForeignKeyOperation operation, IModel model, SqlBatchBuilder builder)
       at Microsoft.Data.Entity.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__47_1(MigrationsSqlGenerator g, MigrationOperation o, IModel m, SqlBatchBuilder b)
       at Microsoft.Data.Entity.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, SqlBatchBuilder builder)
       at Microsoft.Data.Entity.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
       at Microsoft.Data.Entity.Storage.RelationalDatabaseCreator.GetCreateTablesCommands()
       at Microsoft.Data.Entity.Storage.RelationalDatabaseCreator.CreateTables()
       at Microsoft.Data.Entity.Storage.RelationalDatabaseCreator.EnsureCreated()
       at Microsoft.Data.Entity.Infrastructure.DatabaseFacade.EnsureCreated()
       at EFTest.Program.Main(String[] args) in c:\users\robin\documents\visual studio 2015\Projects\EFTest\EFTest\Program.cs:Zeile 17.
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

To reproduce i've modified the common Blog / Post example.

``` csharp
class Program
{
    static void Main(string[] args)
    {
        using (var context = new TestContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }
    }
}

public class TestContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Data Source=db.sqlite");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        //modelBuilder.Entity<Blog>()
        //    .Collection(x => x.Posts)
        //    .InverseReference(x => x.Blog);

        //modelBuilder.Entity<Blog>()
        //    .Reference(x => x.LatestPost);
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string Author { get; set; }

    public List<Post> Posts { get; set; }
    //public Post LatestPost { get; set; }
}

public class Post
{
    public int PostId { get; set; }
    public string Url { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }

    public Blog Blog { get; set; }
}
```
1. When you run this, it will generate Schema v1.
2. Next uncomment `//public Post LatestPost { get; set; }` and run this again, EF removes the `BlogBlogId` foreign key on Post in Schema v2 and there's no relationship between Blog and Post at all.
3. Now uncomment this
   
   ``` csharp
       //modelBuilder.Entity<Blog>()
       //    .Collection(x => x.Posts)
       //    .InverseReference(x => x.Blog);
   ```
   
   and run again, this time Schema v3 looks identical to Schema v1 again.
4. When you now force EF to think about the `LatestPost` property by uncommenting
   
   ``` csharp
       //modelBuilder.Entity<Blog>()
       //    .Reference(x => x.LatestPost);
   ```
   
   and running again, you will receive former exception.

Same works in EF6

**Comment by ErikEJ** [comment] 2015-09-07 05:41
"Same works in EF6" - I doubt it, as the EF6 SQLite provider does not support migrations

**Comment by Suchiman** [comment] 2015-09-07 07:32
@ErikEJ for the original EF6 provider made by the SQLite team this is true.
But for example devart has an EF6 provider with migrations support and i've heavily modified the original provider to support migrations.

In EF6 there's nothing stopping the ModelDiffer, which is common to all providers, to generate two AddForeignKeyOperations, one for Post_LatestPost on the Blog table and one for Blog_BlogId on each Post. Generating the SQL for adding two foreign keys is a piece of cake.

**Comment by ErikEJ** [comment] 2015-09-07 07:45
>> Generating the SQL for adding two foreign keys is a piece of cake.

I am not sure it is as simple as that with SQLite: https://www.sqlite.org/lang_altertable.html

**Comment by Suchiman** [comment] 2015-09-07 08:07
@ErikEJ As you can see on your link, ALTER TABLE ADD COLUMN is one of the few operations supported without witchcraft (at least when ignoring column ordering and referential integrity).

For all other operations i had to beseech dark forces. Recreating tables, extracting informations about the other columns of the table via extracting the edmx entry that is going to be added to the _MigrationHistory table and the severe limitation, that i couldn't safely recreate tables when they had cascade deletes because i couldn't disable them since the MigrationSqlGenerator in EF6 has no control over the Connection (and it has to be disabled before the transaction begins using some pragma) in which i had to recreate the new table, delete the old one and rename the new table to the old one.

The migration SQL generator for EF6 and SQLite i wrote "mostly works" but isn't a beauty. I gave up on improving it as i heard of the upcomming EF7 with offical SQLite Support.

**Comment by ErikEJ** [comment] 2015-09-07 08:20
Thanks for the info. Adding two columns does not add foreign key constraints, though. And FYI, the EF 7 team have currently postponed advanced migration operations due to the exact limitations you describe. Maybe it would help them if you could share your experiences and code with them? @natemcmaster ?

**Comment by Suchiman** [comment] 2015-09-07 08:49
Sure if there's a list of what is missing i can have a look if there's something i've already implemented. But just in case it went missing here, the original intent of this case isn't really using migrations but simply dropping the whole database and re-creating it, so it doesn't have to add additional columns / foreign keys but simply create the table correct in the first run.

**Comment by natemcmaster** [comment] 2015-09-08 16:20
@Suchiman Thank you for the thorough error description. SQLite cannot add a foreign key to an existing table, so `AddForeignKeyOperation` will always throw this error. Currently we do not compensate for this (and other) limitations. We investigated the possibility of performing table rebuilds automatically (see #329), and have postponed development on this feature. 

You can workaround limitations by adding a SQL directly into your migrations by using the `.Sql()` method on `MigrationBuilder`. I recommend following SQLite's guide, [Making Other Kinds Of Table Schema Changes](http://sqlite.org/lang_altertable.html#otheralter). We plan to add documentation to better explain this workaround (see https://github.com/aspnet/EntityFramework.Docs/issues/32).

Closing as a duplicate of #329

**Comment by Suchiman** [comment] 2015-09-08 16:26
@natemcmaster hi, sorry if it wasn't clear. I'm not migrating tables, i'm recreating them.
As per my first example, i'm dropping all tables and then re-create them, so there's no "adding to existing table"
```csharp
context.Database.EnsureDeleted();
context.Database.EnsureCreated();
```

**Comment by ErikEJ** [comment] 2015-09-08 16:27
@natemcmaster Notice that this is probably not a simple Migrations issue, as the database is created from scratch. but more of a mapping issue, as far as I can see.

**Comment by natemcmaster** [comment] 2015-09-08 16:29
Thank you for clarifying. This is likely the result of https://github.com/aspnet/EntityFramework/pull/2885. /cc: @bricelam

**Comment by bricelam** [comment] 2015-09-08 16:39
Possibly a dupe of #2590

**Comment by Suchiman** [comment] 2015-09-10 19:23
I've tried the same using SqlServer and updated my first point with step numbers.
The behaviour is the same until step 4 (though i think it's weird for EF here to do nothing when in doubt instead of throwing an exception).
SqlServer behaves correctly and adds a `LatestPostPostId` to `dbo.Blog` here.

**Comment by bricelam** [comment] 2015-09-10 22:45
I've investigate further and found that, as expected, this is the same issue described by #2590. Closing as a duplicate.

**Closed** 2022-10-16 09:07 UTC
