### ISSUE TITLE
Ownership does not work for enumerable property

### ISSUE THREAD

**Issue by crhairr** [dotnet/efcore#10269] opened 2017-11-12 08:00 UTC
I'm developing  a [MongoDB provider for EF Core](https://github.com/crhairr/EntityFrameworkCore.MongoDb). Being a document DB, MongoDB requires arbitrary structures including deeply nested and enumerable complex type properties.

I created a property discovery convention for detecting complex types and I'm calling the following:

```C#
        public virtual InternalEntityTypeBuilder Apply(InternalEntityTypeBuilder entityTypeBuilder)
        {
            Check.NotNull(entityTypeBuilder, nameof(entityTypeBuilder));
            var entityType = entityTypeBuilder.Metadata;

            if (entityType.HasClrType())
            {
                var complexTypeProperties = entityType.ClrType.GetRuntimeProperties().Where(IsCandidateComplexTypeProperty);

                foreach (var propertyInfo in complexTypeProperties)
                {
                    entityTypeBuilder.Owns(propertyInfo.PropertyType, propertyInfo, ConfigurationSource.Convention);
                }
            }

            return entityTypeBuilder;
        }
```

I have a sample model that contains the following entity:

```C#
    public class Employee
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public ObjectId Id { get; [UsedImplicitly] private set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        [BsonIgnore]
        public string FullName => string.IsNullOrWhiteSpace(FirstName)
            ? LastName
            : $"{LastName}, {FirstName}";

        public decimal Age { get; set; }
        public IList<Specialty> Specialties { get; set; } = new List<Specialty>();
    }

    public enum ZooTask
    {
        Feeding,
        Training,
        Exercise,
        TourGuide
    }

    public class Specialty
    {
        public string AnimalType { get; set; }
        public ZooTask Task { get; set; }
    }
```

The attempt to declare the ownership on `Employee.Specialties` is generating the following exception:

`Message: System.InvalidOperationException : The entity type 'Specialty' requires a primary key to be defined.`

**Comment by lillo42** [comment] 2017-11-12 10:56
I think it is because your class need a primary key,  try to do this
```
public class Specialty
{
       [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public ObjectId Id { get; [UsedImplicitly] private set; }
        public string AnimalType { get; set; }
        public ZooTask Task { get; set; }
}
```
or 

```
public class Specialty
{
       [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string AnimalType { get; set; }
        public ZooTask Task { get; set; }
}
```

**Comment by crhairr** [comment] 2017-11-12 14:33
You're missing the point. Complex types don't have keys. They're just a collection of related properties on an Entity. In the case of MongoDB, they're tested as subdcuments of the parent/containing Entity. The point is that they should not require keys, and it is either a bug or a design flaw that the mechanism used to "implement" complex types requires that they have keys.

**Comment by crhairr** [comment] 2017-11-12 14:51
Sorry... Now that I've had a cup of coffee, my brain is working again.

I've already verified that the ownership mechanism doesn't require a key. The problem here, as stated in the title of the issue, is that the ownership system does not support enumerable properties.

**Comment by smitpatel** [comment] 2017-11-12 16:49
It is at present unsupported to have collection/enumerable of owned entities.

Duplicate of #8172

**Closed** 2022-10-16 11:58 UTC
