### ISSUE TITLE
Migration Classes are made Public by Default

### ISSUE THREAD

**Issue by NArnott** [dotnet/efcore#14835] opened 2019-02-26 15:05 UTC
When add migrations, the migration classes are made public by default. For projects where we are generating xml documentation, this creates unwanted warnings. The simple workaround is to manually remove the `public ` keyword, which migrations appears to work fine without.

Is there any reason why migrations classes can't be made private by default?

### Further technical details
EF Core version: 2.1.8
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: WIndows 10
IDE: Visual Studio 2017 15.9.7

**Comment by roji** [comment] 2019-02-26 15:43
Duplicate of #13955

**Comment by ajcvickers** [comment] 2019-02-26 17:51
@roji @bricelam Just out of curiosity, is there any specific reason we don't make them internal?

**Comment by bricelam** [comment] 2019-02-27 22:48
No technical reason; it's just what we did in EF6. We explicitly *don't* specify the visibility in the *.Designer partial class to make it easier to manually update them to `internal` if you want.

**Comment by bricelam** [comment] 2019-02-27 22:49
Actually, there may be one reason: If we made them internal, you may get a lot of "unused code" warnings.

**Comment by ajcvickers** [comment] 2019-02-28 00:12
@bricelam Thanks. Don't think we should change it; just curious.

**Comment by roji** [comment] 2019-02-28 08:35
Yeah, I admit I can't really think of anything technical... In some logical sense they're public since they're meant to be discovered via reflection by a component that's external to the assembly, I guess that's my main argument, not super strong.

**Closed** 2022-10-16 13:53 UTC
Labels: customer-reported
