### ISSUE TITLE
How to configure my Cosmos Db with Spatial IndexingPolicy

### ISSUE THREAD

**Issue by ranouf** [dotnet/efcore#27076] opened 2021-12-30 04:08 UTC
Hi,

Using Microsoft Azure Documents package, I'm able to set the Spatial Indexing Policy to the collection like:

            var collection = new DocumentCollection
            {
                Id = collectionName,
                IndexingPolicy = new IndexingPolicy(new SpatialIndex(DataType.Point)),
            };

            var databaseUri = UriFactory.CreateDatabaseUri(Name);
            var options = new RequestOptions { OfferThroughput = 1000 };
            var response = await DocumentClient.CreateDocumentCollectionIfNotExistsAsync(databaseUri, collection, options);

How to set the Indexing Policy using Entity Framework Core?

Thanks

**Comment by ranouf** [comment] 2021-12-30 04:49
I found the answer here:
https://github.com/MicrosoftDocs/azure-docs/issues/84374

It's not supported (yet maybe)

**Comment by ajcvickers** [comment] 2022-01-06 09:45
Duplicate of #17317.

**Closed** 2022-10-16 20:20 UTC
Labels: customer-reported
