### ISSUE TITLE
The DbSet is not resetting if use DbContext from pool

### ISSUE THREAD

**Issue by sergei66666** [dotnet/efcore#13667] opened 2018-10-18 09:39 UTC
Sometimes i am using DbSet.Local property. After applying context pooling i got some NullPointerExceptions. It happen if take context from pool. 

It mean (from my point of view) that context doesn't resetted properly. Similarly here #13491

### Steps to reproduce
```cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace DbSetResetIssue
{
    public class Model
    {
        public int Id { get; set; }
    }

    public sealed class MyContext : DbContext
    {
        public MyContext(DbContextOptions<MyContext> options)
            : base(options)
        {
        }
        public DbSet<Model> Models { get; set; }

    }

    class Program
    {
        static void Main(string[] args)
        {
            var services = new ServiceCollection();
            services.AddDbContextPool<MyContext>(c =>
            {
                c.UseInMemoryDatabase("test");
            });

            var sp = services.BuildServiceProvider();

            using (var scope = sp.CreateScope())
            {
                var ctx = scope.ServiceProvider.GetRequiredService<MyContext>();
                Trace.WriteLine($"1: TotalCount {ctx.Models.Local.Count}. Nulls {ctx.Models.Local.ToList().Count(it => it == null)}");

                ctx.Models.AddRange(new List<Model> {
                    new Model(), new Model(), new Model(),
                    new Model(), new Model(), new Model(),
                });
                ctx.SaveChanges();

                Trace.WriteLine($"2: TotalCount {ctx.Models.Local.Count}. Nulls {ctx.Models.Local.ToList().Count(it => it == null)}");
            }

            using (var scope = sp.CreateScope())
            {
                var ctx = scope.ServiceProvider.GetRequiredService<MyContext>();
                Trace.WriteLine($"3: TotalCount {ctx.Models.Local.Count}. Nulls {ctx.Models.Local.ToList().Count(it => it == null)}");


                ctx.Models.Load();

                Trace.WriteLine($"4: TotalCount {ctx.Models.Local.Count}. Nulls {ctx.Models.Local.ToList().Count(it => it == null)}");
            }

            using (var scope = sp.CreateScope())
            {
                var ctx = scope.ServiceProvider.GetRequiredService<MyContext>();
                Trace.WriteLine($"5: TotalCount {ctx.Models.Local.Count}. Nulls {ctx.Models.Local.ToList().Count(it => it == null)}");

                ctx.Models.Load();

                Trace.WriteLine($"6: TotalCount {ctx.Models.Local.Count}. Nulls {ctx.Models.Local.ToList().Count(it => it == null)}");
            }
        }
    }
}
```
Outputs:
1: TotalCount 0. Nulls 0
2: TotalCount 6. Nulls 0
3: TotalCount 6. Nulls 6
4: TotalCount 12. Nulls 6
5: TotalCount 12. Nulls 12
6: TotalCount 18. Nulls 12

Expected outputs:
1: TotalCount 0. Nulls 0
2: TotalCount 6. Nulls 0
3: TotalCount 0. Nulls 0
4: TotalCount 6. Nulls 0
5: TotalCount 0. Nulls 0
6: TotalCount 6. Nulls 0

### Interesting remark
If replace
```cs
Trace.WriteLine($"n: TotalCount {ctx.Models.Local.Count}. Nulls {ctx.Models.Local.ToList().Count(it => it == null)}");
```
with (remove ToList())
```cs
Trace.WriteLine($"n: TotalCount {ctx.Models.Local.Count}. Nulls {ctx.Models.Local.Count(it => it == null)}");
```

It outputs:
1: TotalCount 0. Nulls 0
2: TotalCount 6. Nulls 0
3: TotalCount 6. Nulls 0
4: TotalCount 12. Nulls 0
5: TotalCount 12. Nulls 0
6: TotalCount 18. Nulls 0

### Further technical details
EF Core version: 2.1.4
Database Provider: SqlServer or In Memory
Operating system: Windows 10
IDE: Visual Studio 15.7.4

**Comment by sergei66666** [comment] 2018-10-18 09:39
#13491

**Comment by smitpatel** [comment] 2018-10-18 18:33
Duplicate of #12126

**Closed** 2022-10-16 13:35 UTC
Labels: closed-duplicate, customer-reported
