### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by dansoper** [dotnet/efcore#20465] opened 2020-03-30 08:37 UTC
I came to this page to find out what the default values of maxRetryCount and maxRetryDelay are, if not provided. Not sure if they should be mentioned on this page, and I'm not sure whether the values have changed over time, but a brief look at the source suggests maxRetryCount is 6 and maxRetryDelay is 30 seconds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcac28c8-acc4-81b6-01f6-6ffad57c64a1
* Version Independent ID: 9fcb9d42-63cf-af0a-14b0-ac470130b089
* Content: [SqlServerDbContextOptionsBuilder.EnableRetryOnFailure Method (Microsoft.EntityFrameworkCore.Infrastructure)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.sqlserverdbcontextoptionsbuilder.enableretryonfailure?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/SqlServerDbContextOptionsBuilder.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/SqlServerDbContextOptionsBuilder.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2020-09-20 18:27
Duplicate of #17574

**Closed** 2022-10-16 18:18 UTC
Labels: closed-duplicate, customer-reported
