### ISSUE TITLE
Scaffold-DbContext needs an environment variable connection string option

### ISSUE THREAD

**Issue by BrandonPotter** [dotnet/efcore#11430] opened 2018-03-26 03:51 UTC
Opening this issue for discussion / new feature request. (Didn't see anything obvious in a search of open issues, so forgive me if duplicate.)

**Problem**

Currently, each time you run Scaffold-DbContext to generate a database-first model and context (a common workflow when adding columns to a table, etc), the connection string is hardcoded into the DbContext class, along with a `#warning` reminder to go replace it. While the warning is helpful, each time you must remember to go replace this, prior to committing changes.

It's easy to forget, not to mention Entity Framework full and Entity Framework core, by default, have always seemed to go against the official Microsoft recommendation and common sense architecture guidelines of "keep your connection strings out of your source code".

**Proposal**

Support an additional, optional argument in Scaffold-DbContext:

`-UseConnectionStringEnvironmentVariable <name>`

ex, `-UseConnectionStringEnvironmentVariable MyConnectionString`

... which would then produce a slightly different `OnConfiguring` section:

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
	if (!optionsBuilder.IsConfigured)
	{
		optionsBuilder.UseSqlServer(System.Environment.GetEnvironmentVariable("MyConnectionString"));
	}
}
```

The environment variable approach maps nicely to docker container configuration in AWS ECS, Kubernetes, and other orchestrators.

Alternatively, or in addition, offer an optional argument:

`-ExcludeOptionsBuilderConfiguration` (for lack of a better term)

... which skips the `OnConfiguring` method in generated code altogether, so that it's possible to place the `OnConfiguring` override in a separate partial class that doesn't get overwritten each time Scaffold-DbContext is run.

**Comment by ErikEJ** [comment] 2018-03-26 07:44
Not sure it it helps your situation, but with "EF Core Power Tools" you can choose to not generate the connection string, and then add a partial class like this, that you can configure with an OptionsBuilder
```
public partial class DataContext
    {
        public DataContext(DbContextOptions<DataContext> options) : base(options) { }
    }

```

**Comment by ErikEJ** [comment] 2018-03-26 13:30
Of course it does! 😁

**Comment by bricelam** [comment] 2018-03-26 19:08
We'll also support using a `name=` syntax in 2.1. The workflow:
1. Add your connection string to your ASP.NET Core configuration (environment variables, user secrets, json, etc.)
2. Reverse engineer using `Scaffold-DbContext Name=MyConnectionStringKey My.EFCore.Provider`
3. Behold the awesomeness. No `#warning` is generated since you're connection string just contains a configuration key.

**Comment by bricelam** [comment] 2018-03-26 19:10
That was issue #2464

**Comment by ajcvickers** [comment] 2018-03-28 21:44
@bricelam Suggested triage decision on this?

**Comment by bricelam** [comment] 2018-03-28 22:08
I think we can close it as a duplicate of #2464, but if @BrandonPotter has any additional ideas on how we can make this scenario better (keeping #831 in mind too), we'd love to hear it.

**Closed** 2022-10-16 12:16 UTC
