### ISSUE TITLE
The property 'X' is of type 'Y' which is not supported by the current database provider. Either change the property CLR type, or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

### ISSUE THREAD

**Issue by ShvetsovAU** [dotnet/efcore#24037] opened 2021-02-01 14:21 UTC
Hello.

We are migrate from EntityFramework 6 to EF.Core.

We have two model as:

```c#
public partial class User
    {
        [Key]
        [Required]
        public Int16 ObjectId { get; set; }

        [Required]
        [MaxLength(80)]
        public string Name { get; set; }
    }
}

[Table("P3DbModel")]
    public partial class P3DBModel : IP3DBModel, IMD5
    {       
        
        [Key]
        [Required]
        [ExtendedColumn(IsRowGuid = true)]
        public Guid ObjectId { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public virtual User User { get; set; }

        public User RelationsLastUpdateUser { get; set; }
    }
}
```

configuration in model creating:

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{						
		modelBuilder.Entity<P3DBModel>(entity =>
            {
                entity.HasKey(e => e.ObjectId)
                    .HasName("PK_dbo.P3DBModel");

                entity.ToTable("P3DBModel");
                
                entity.Property(e => e.ObjectId).ValueGeneratedNever();

                entity.Property(e => e.Name).IsRequired();
                                
                entity.Property(e => e.User).HasDefaultValueSql("((1))");
                
            });
            
            modelBuilder.Entity<P3DBModel>()
                .HasOne<User>()
                .WithMany()
                .HasForeignKey(d => d.RelationsLastUpdateUser)
                .HasConstraintName("FK_dbo.P3DBModel_dbo.Users_RelationsLastUpdateUser_ObjectId");

            modelBuilder.Entity<P3DBModel>()
                .HasOne<User>()
                .WithMany()
                .HasForeignKey(d => d.User)
                .HasConstraintName("FK_dbo.P3DBModel_dbo.Users_User_ObjectId");
				
				
		modelBuilder.Entity<User>(entity =>
            {
                entity.HasKey(e => e.ObjectId)
                    .HasName("PK_dbo.Users");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(80);
            });
}
```

We are use Microsoft.EntityFrameworkCore.SqlServer (5.0.2) provider and Microsoft.EntityFrameworkCore (5.0.2)
Then db context is created and i try use Context.Set<TEntity>(), i get error:

"System.InvalidOperationException: 'The property 'P3DBModel.User' is of type 'User' which is not supported by the current database provider. Either change the property CLR type, or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.'"

or

"System.InvalidOperationException: 'The property 'P3DBModel.RelationsLastUpdateUser ' is of type 'User' which is not supported by the current database provider. Either change the property CLR type, or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.'"

Try set "User" setting

entity.Property(e => e.ObjectId).HasColumnType("SMALLINT");

not did not help

Similar situation with another entities with key field with Int16 or short.

Can you help me, what's i do wrong?

**Comment by roji** [comment] 2021-02-01 15:09
The HasForeignKey needs to reference the foreign key property - an Int16 property - and not the navigation property (which has type User). Either add a UserId property of type Int16 to P3DBModel and reference that, or remove the HasForeignKey altogether and EF Core will use a shadow property for the foreign key (less recommended). [See these docs for more info](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#foreign-key).

Similarly, you can't call HasDefaultValueSql on a navigation property (User) - that needs to be removed.

**Comment by ShvetsovAU** [comment] 2021-02-01 15:48
Thank you.

>[See these docs for more info](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#foreign-key).

I use this docs)

> The HasForeignKey needs to reference the foreign key property - an Int16 property - and not the navigation property (which has type User). Either add a UserId property of type Int16 to P3DBModel and reference that, or remove the HasForeignKey altogether and EF Core will use a shadow property for the foreign key (less recommended). 

If i add to User entity field 
`public ICollection<P3DbModel> LastUpdatedP3dbModelUsers {get;set;}`

and add to configuration

`modelBuilder.Entity<P3DBModel>()
                .HasOne<User>(p => p.RelationsLastUpdateUser)
                .WithMany(p => p.LastUpdatedP3dbModelUsers)
                .HasForeignKey(d => d.RelationsLastUpdateUser)
                .HasConstraintName("FK_dbo.P3DBModel_dbo.Users_RelationsLastUpdateUser_ObjectId");`

It will be created shadow foreign key?
 
> Similarly, you can't call HasDefaultValueSql on a navigation property (User) - that needs to be removed.

EF create this setting by scaffold-dbcontext command

**Comment by roji** [comment] 2021-02-01 16:04
@ShvetsovAU let's leave aside shadow foreign keys.

If I understand you correctly, each User has many P3DBModels. This means that P3DBModel needs to have a UserId foreign key property, of the same type as User's key. Here's a simplified model:

```c#
public class User
{
    public Int16 Id { get; set; }
    public string Name { get; set; }
}

public class P3DBModel
{
    public Guid Id { get; set; }

    public string Name { get; set; }
    public User User { get; set; } // Navigation property to User
    public Int16 UserId { get; set; } // Foreign key property, same type as User.Id
}
```

Note that with the above model you don't need to specify anything in OnModelCreating. Since everything is named according to the convention, the Id properties are automatically detected as the keys for both entity types, and the UserId property is automatically detected as the foreign key for the User navigation property. This is the simplest way to use EF Core.

Hope that clarifies things.

**Comment by ShvetsovAU** [comment] 2021-02-01 17:16
> Note that with the above model you don't need to specify anything in OnModelCreating. Since everything is named according to the convention, the Id properties are automatically detected as the keys for both entity types, and the UserId property is automatically detected as the foreign key for the User navigation property. This is the simplest way to use EF Core.
> 
> Hope that clarifies things.

Yes, This is clear, but this is perfect models with Fully defined relationships, which is not always the case. In our case models modification maybe will require modification of existing logic and data base schema, I would not like this...

**Comment by roji** [comment] 2021-02-01 20:49
@ShvetsovAU you indeed don't have to define the model with conventions as I did above - it's perfectly fine to configure it explicitly in OnModelCreating. But you have to distinguish between the navigation property and the foreign key property - HasForeignKey needs to accept the foreign key property and not the navigation property (as you did in https://github.com/dotnet/efcore/issues/24037#issuecomment-770954072 with RelationsLastUpdateUser).

**Comment by ShvetsovAU** [comment] 2021-02-02 04:20
> @ShvetsovAU you indeed don't have to define the model with conventions as I did above - it's perfectly fine to configure it explicitly in OnModelCreating. But you have to distinguish between the navigation property and the foreign key property - HasForeignKey needs to accept the foreign key property and not the navigation property (as you did in [#24037 (comment)](https://github.com/dotnet/efcore/issues/24037#issuecomment-770954072) with RelationsLastUpdateUser).

Ok, i modified model as:

```cs
public class User
 {
     public Int16 Id { get; set; }
     public string Name { get; set; }
 }
 
 public class P3DBModel
 {
        [Key]
        [Required]
       public Guid Id { get; set; }
 
     public string Name { get; set; }

     public Int16 User_ObjectId { get; set; } // Foreign key property, same type as User.Id
        
        [Required]
        [ForeignKey("User_ObjectId")]
        public virtual User User { get; set; } // Navigation property to User
        
        public Int16? RelationsLastUpdateUser_ObjectId { get; set; } // Foreign key property, same type as User.Id
        
        [ForeignKey("RelationsLastUpdateUser_ObjectId")]
        public virtual User RelationsLastUpdateUser { get; set; } // Navigation property to User
 }
 ```
and

```cs

 modelBuilder.Entity<P3DBModel>(entity =>
            {
                entity.HasKey(e => e.ObjectId)
                    .HasName("PK_dbo.P3DBModel");

                entity.ToTable("P3DBModel");

                entity.HasIndex(e => e.RelationsLastUpdateUser, "IX_RelationsLastUpdateUser_ObjectId");
                entity.HasIndex(e => e.User, "IX_User_ObjectId");
                entity.Property(e => e.ObjectId).ValueGeneratedNever();

                entity.Property(e => e.Name).IsRequired();

                entity.Property(e => e.User_ObjectId).HasDefaultValueSql("((1))");
            });

modelBuilder.Entity<User>(entity =>
            {
                entity.HasKey(e => e.ObjectId)
                    .HasName("PK_dbo.Users");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(80);              
            });
 ```

and geting same error: "System.InvalidOperationException: 'The property 'P3DBModel.RelationsLastUpdateUser ' is of type 'User' which is not supported by the current database provider. Either change the property CLR type, or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.'"

if i modify onModelCreating as:

```cs

 modelBuilder.Entity<P3DBModel>(entity =>
            {
                entity.HasKey(e => e.ObjectId)
                    .HasName("PK_dbo.P3DBModel");

                entity.ToTable("P3DBModel");

                entity.HasIndex(e => e.RelationsLastUpdateUser, "IX_RelationsLastUpdateUser_ObjectId");
                entity.HasIndex(e => e.User, "IX_User_ObjectId");
                entity.Property(e => e.ObjectId).ValueGeneratedNever();

                entity.Property(e => e.Name).IsRequired();

                entity.Property(e => e.User_ObjectId).HasDefaultValueSql("((1))");

               entity.HasOne(d => d.RelationsLastUpdateUser)
                    .WithMany()
                    .HasForeignKey(d => d.RelationsLastUpdateUser_ObjectId)
                    .HasConstraintName("FK_dbo.P3DBModel_dbo.Users_RelationsLastUpdateUser_ObjectId");
            });

modelBuilder.Entity<User>(entity =>
            {
                entity.HasKey(e => e.ObjectId)
                    .HasName("PK_dbo.Users");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(80);              
            });
 ```

error is: "System.InvalidOperationException: 'The property or navigation 'RelationsLastUpdateUser' cannot be added to the entity type 'P3DBModel' because a property or navigation with the same name already exists on entity type 'P3DBModel'.'"

**Comment by roji** [comment] 2021-02-02 11:25
The problem in your first sample is the HasIndex: just like with HasForeignKey, you cannot pass a navigation property to it:

```c#
entity.HasIndex(e => e.RelationsLastUpdateUser, "IX_RelationsLastUpdateUser_ObjectId");
entity.HasIndex(e => e.User, "IX_User_ObjectId");
```

Removing these two lines makes the model build correctly. EF Core automatically creates an index on your foreign keys, so you don't need to do this explicitly.

**Comment by ShvetsovAU** [comment] 2021-02-02 11:37
> The problem in your first sample is the HasIndex: just like with HasForeignKey, you cannot pass a navigation property to it:
> 
> ```cs
> entity.HasIndex(e => e.RelationsLastUpdateUser, "IX_RelationsLastUpdateUser_ObjectId");
> entity.HasIndex(e => e.User, "IX_User_ObjectId");
> ```
> 
> Removing these two lines makes the model build correctly.

Ok, i'll check. Thank you.

> EF Core automatically creates an index on your foreign keys, so you don't need to do this explicitly.

I know, but this is existing data base, i need create db context to connect to her.

**Comment by roji** [comment] 2021-02-02 12:52
> I know, but this is existing data base, i need create db context to connect to her.

If it's an existing database, then there's no need to configure the indexes in the model at all - they're already in your database. Using HasIndex only has an effect if you're going to be creating a new database from this model.

**Comment by ajcvickers** [comment] 2021-02-02 20:30
@ShvetsovAU If you have an existing database, then [reverse-engineering it to scaffold a DbContext and model]() is the best way to get a working EF Core model configuration that maps to your database. You can then modify this model if you need to, but you will have a complete, working configuration to start from which makes things much easier.

**Comment by ShvetsovAU** [comment] 2021-02-03 03:03
> @ShvetsovAU If you have an existing database, then [reverse-engineering it to scaffold a DbContext and model](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli) is the best way to get a working EF Core model configuration that maps to your database. You can then modify this model if you need to, but you will have a complete, working configuration to start from which makes things much easier.

Hello. Yes, i used this feature and Ef generate me constructions, which i wrote here

**Comment by ShvetsovAU** [comment] 2021-02-03 03:04
> > I know, but this is existing data base, i need create db context to connect to her.
> 
> If it's an existing database, then there's no need to configure the indexes in the model at all - they're already in your database. Using HasIndex only has an effect if you're going to be creating a new database from this model.

Maybe in feture will need create db from this project.

**Comment by ajcvickers** [comment] 2021-02-03 16:06
@ShvetsovAU The code you originally posted really doesn't look like anything the EF Core tool would generate. Can you let us know exactly what steps you took to generate this?

**Comment by ShvetsovAU** [comment] 2021-02-04 11:44
> @ShvetsovAU The code you originally posted really doesn't look like anything the EF Core tool would generate. Can you let us know exactly what steps you took to generate this?
By isung next command: scaffold-dbcontext -provider Microsoft.EntityFrameworkCore.SqlServer -connection "Server=localhost; Database=...; Trusted_Connection=true; Integrated Security=true;” -OutputDir EntityModel -Schemas dbo -UseDatabaseNames

**Comment by AndriySvyryd** [comment] 2021-02-05 20:33
@ShvetsovAU Please attach a small SQL script that creates a database that can be used to reproduce this issue

**Comment by ajcvickers** [comment] 2021-02-16 16:33
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:21 UTC
Labels: closed-could-not-reproduce, customer-reported
