### ISSUE TITLE
[Question] dnx ef migrations add

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#4166] opened 2015-12-23 13:25 UTC
Hi Guys,

Something weird in the migrations?
I create my domain, and I add dnx ef migrations add v0.0.1, and perform dnx ef database update. this step is successfully.
without modify my domain properties, I do perform dnx ef migrations add v0.0.2, it will generate another script and this time it create this below.

```
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(name: "FK_JobPost_User_UserId", table: "JobPost");
        migrationBuilder.DropForeignKey(name: "FK_JobPostUser_JobPost_JobPostId", table: "JobPostUser");
        migrationBuilder.AddForeignKey(
            name: "FK_JobPost_User_UserId",
            table: "JobPost",
            column: "UserId",
            principalTable: "User",
            principalColumn: "Id",
            onDelete: ReferentialAction.Cascade);
        migrationBuilder.AddForeignKey(
            name: "FK_JobPostUser_JobPost_JobPostId",
            table: "JobPostUser",
            column: "JobPostId",
            principalTable: "JobPost",
            principalColumn: "Id",
            onDelete: ReferentialAction.Cascade);
    }
```

Why this code is not generating on the first migrations?
Is this a bug or ?

**Comment by nocommonsense** [comment] 2015-12-23 15:53
dupe of #3751

**Closed** 2022-10-16 09:22 UTC
