### ISSUE TITLE
Problem with Owned Entity: exception raised when using it and no exception without it

### ISSUE THREAD

**Issue by JohnyL** [dotnet/efcore#12332] opened 2018-06-12 07:29 UTC
I'm trying to emulate SQL Server's FileTable. I decided to move several attributes into separate class, so the obvious solution is Owned Entities.

There are two variants of table for test:
1. When all properties are in the "table" class.
2. When several properties are moved into separate (owned) class (FileAttributes).

The `USE_OWNED` directive lets switch between these two modes.

### Code:
```C#
#define USE_OWNED
using Microsoft.SqlServer.Types;

// FileTable emulation

[Table("Drawing", Schema = "ft")]
class Drawing
{
    [Required]
    [Timestamp]
    [Column("stream_id")]
    public Guid StreamId { get; set; }

    [Column("file_stream")]
    public byte[] FileStream { get; set; }

    [Column("name")]
    public string Name { get; set; }

    [Key]
    [Column("path_locator")]
    public SqlHierarchyId PathLocator { get; set; }

    [Column("parent_path_locator")]
    public SqlHierarchyId? ParentPathLocator { get; set; }

#if USE_OWNED
    public FileAttributes Attributes { get; set; }
#else
    [Column("file_type")]
    public string FileType { get; set; }

    [Column("cached_file_size")]
    public long? CachedFileSize { get; set; }

    [Column("creation_time")]
    public DateTimeOffset CreationTime { get; set; }

    [Column("last_write_time")]
    public DateTimeOffset LastWriteTime { get; set; }

    [Column("last_access_time")]
    public DateTimeOffset? LastAccessTime { get; set; }

    [Column("is_directory")]
    public bool IsDirectory { get; set; }

    [Column("is_offline")]
    public bool IsOffline { get; set; }

    [Column("is_hidden")]
    public bool IsHidden { get; set; }

    [Column("is_readonly")]
    public bool IsReadOnly { get; set; }

    [Column("is_archive")]
    public bool IsArchive { get; set; }

    [Column("is_system")]
    public bool IsSystem { get; set; }

    [Column("is_temporary")]
    public bool IsTemporary { get; set; }
#endif
		
}

// Owned Entity

[Owned]
class FileAttributes
{

    [Column("file_type")]
    public string FileType { get; set; }

    [Column("cached_file_size")]
    public long? CachedFileSize { get; set; }

    [Column("creation_time")]
    public DateTimeOffset CreationTime { get; set; }

    [Column("last_write_time")]
    public DateTimeOffset LastWriteTime { get; set; }

    [Column("last_access_time")]
    public DateTimeOffset? LastAccessTime { get; set; }

    [Column("is_directory")]
    public bool IsDirectory { get; set; }

    [Column("is_offline")]
    public bool IsOffline { get; set; }

    [Column("is_hidden")]
    public bool IsHidden { get; set; }

    [Column("is_readonly")]
    public bool IsReadOnly { get; set; }

    [Column("is_archive")]
    public bool IsArchive { get; set; }

    [Column("is_system")]
    public bool IsSystem { get; set; }

    [Column("is_temporary")]
    public bool IsTemporary { get; set; }
}
```

### Test code:
```C#
private void OnRun(object sender, RoutedEventArgs e)
{
    using (var db = new FileStreamContext())
    {
        var file = db.Drawings.First();
	if (file != null)
	{
#if USE_OWNED
	   MessageBox.Show($"Is dir: {file.Attributes.IsDirectory.ToString()}");
#else
	    MessageBox.Show($"Is dir: {file.IsDirectory.ToString()}");
#endif
	}
    }
}
```

### Results:
1. When all properties are in one class, _everything is OK, and table is queried successfully_.
2. When using Owned Entity (FileAttributes), I get the following error:

> **System.ArgumentException**: Expression of type 'System.Data.SqlTypes.SqlBoolean' cannot be used for return type 'System.Boolean'

### Stack trace:

>    at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrAccessorFactory\`1.Create(PropertyInfo propertyInfo, IPropertyBase propertyBase)
>    at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrAccessorFactory\`1.Create(IPropertyBase property)
>    at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func\`2 valueFactory)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.MemberAccessBindingExpressionVisitor.<>c__DisplayClass14_0.<VisitMethodCall>b__0(IProperty property, IQuerySource _)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.<>c__DisplayClass92_0\`1.<BindMethodCallExpression>b__0(IReadOnlyList\`1 ps, IQuerySource qs)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindPropertyExpressionCore[TResult](Expression propertyExpression, IQuerySource querySource, Func\`3 propertyBinder)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.MemberAccessBindingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitGroupJoinClause(GroupJoinClause groupJoinClause, QueryModel queryModel, Int32 index)
>    at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitGroupJoinClause(GroupJoinClause groupJoinClause, QueryModel queryModel, Int32 index)
>    at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection\`1 bodyClauses, QueryModel queryModel)
>    at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger\`1 logger, Type contextType)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0\`1.<Execute>b__0()
>    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func\`1 compiler)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
>    at FileStreamApp.Root.OnRun(Object sender, RoutedEventArgs e) in D:\Projects\FileStreamProject\FileStreamApp\Root.xaml.cs:line 39
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.Controls.Primitives.ButtonBase.OnClick()
>    at System.Windows.Controls.Button.OnClick()
>    at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
>    at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at FileStreamApp.App.Main()

### Further technical details
EF Core version: **2.1.0**
Database Provider: **Microsoft.EntityFrameworkCore.SqlServer**
Operating system: **Windows 10 x64 Home Edition 1803 build 17134.81**
IDE: **Visual Studio 2017 15.8.0 Preview 2.0**

**Comment by ajcvickers** [comment] 2018-06-12 16:16
@JohnyL What is the definition for the table in the database?

**Comment by JohnyL** [comment] 2018-06-12 19:12
@ajcvickers The schema for FileTable is [fixed](https://docs.microsoft.com/en-us/sql/relational-databases/blob/filetable-schema):

![FileTableSchema](https://i.imgur.com/y9Yym3f.png)

**Comment by JohnyL** [comment] 2018-06-15 08:18
**UPDATE**

After some tests, I figured out that _Owned Entity has nothing to do with error_. This error occurs when calling, for instance, `Entry` method:
```
using (var db = new FileStreamContext())
{
    var file = db.Drawings.First();
    var entry = db.Entry(file);
}
```

**Comment by ajcvickers** [comment] 2018-06-15 16:35
@JohnyL Our suspicion is that this is something to do with using SqlHierarchyId as the primary key, but we will know more after further investigation.

**Comment by ajcvickers** [comment] 2020-03-27 21:28
Closing as duplicate of #365; see discussion there.

**Closed** 2022-10-16 12:30 UTC
Labels: type-bug, closed-out-of-scope, customer-reported, punted-for-2.2, punted-for-3.0, punted-for-3.1, area-model-building
