### ISSUE TITLE
Regression when using ImmutableArray's Contains, while Array's Contains method still works.

### ISSUE THREAD

**Issue by fschwiet** [dotnet/efcore#35102] opened 2024-11-14 00:16 UTC
## File a bug

I ran into a regression going from 8.0.1 to 9.0.0 using the Sqlite provider. I have some code which is checking if the string value of a column (column name Value) is one of a number of values (using dbKeys.Contains). dbKeys was an ImmutableArray, I found if I used an Array instead it start to work. But I don't see any reason it shouldn't keep working with an ImmutableArray.

### Include your code

The following code using ToImmutableArray stopped working when going from 8.0.1 to 9.0.0:

```C#
		var dbKeys = dbTags.Select(t => t.Value).Distinct().ToImmutableArray();

		var existingEntities = await context
			.Tags.Where(t => dbKeys.Contains(t.Value))
			.ToArrayAsync(cancellationToken);
```

But it works if I use ToArray():

```C#
		var dbKeys = dbTags.Select(t => t.Value).Distinct().ToArray();

		var existingEntities = await context
			.Tags.Where(t => dbKeys.Contains(t.Value))
			.ToArrayAsync(cancellationToken);
```

### Include stack traces

```
Unhandled exception. System.ArgumentException: Expression of type 'System.Collections.Immutable.ImmutableArray`1[System.String]' cannot be used for parameter of type 'System.Collecti
ons.Generic.IEnumerable`1[System.String]' of method 'System.Linq.IQueryable`1[System.String] AsQueryable[String](System.Collections.Generic.IEnumerable`1[System.String])' (Parameter 'arg0')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryableMethodNormalizingExpressionVisitor.TryConvertCollectionContainsToQueryableContains(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryableMethodNormalizingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryableMethodNormalizingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryableMethodNormalizingExpressionVisitor.Normalize(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.NormalizeQueryableMethod(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPreprocessor.NormalizeQueryableMethod(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutorExpression[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass11_0`1.<ExecuteCore>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteCore[TResult](Expression query, Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

### Include provider and version information

EF Core version:  regressed with version 9.0.0, worked for version 8.0.1
Database provider: Microsoft.EntityFrameworkCore.Sqlite regressed with version 9.0.0, worked for version 8.0.1
Target framework: regression seen with net9.0, worked with net8.0
Operating system: Windows 11 Home
IDE: JetBrains Rider 2024.2.5

**Comment by roji** [comment] 2024-11-14 06:28
Confirmed regression from 8.0 to 9.0; not specific to SQLite.

```c#
await using var context = new BlogContext();
await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

ImmutableArray<string> tags = ["foo", "bar"];
// List<string> tags = ["foo", "bar"]; // This works

var existingEntities = await context
    .Tags.Where(t => tags.Contains(t.Value))
    .ToArrayAsync();

public class BlogContext : DbContext
{
    public DbSet<Tag> Tags { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Tag
{
    public int Id { get; set; }
    public string Value { get; set; }
}
```

@cincuranet assigning to you as you worked in this area in 9.0, IIRC.

**Comment by caxepok** [comment] 2024-11-27 12:15
Confirmed regression from 8.0 to 9.0; - Postgres.

```
    public IAsyncEnumerable<Scope> FindByNamesAsync(ImmutableArray<string> names, CancellationToken cancellationToken)
    {
        return _db.Resources.AsNoTracking().Where(r => names**.AsEnumerable()**.Contains(r.Scope))
            .Select(r => new Scope { Name = r.Scope })
            .AsAsyncEnumerable();
    }
```

Temporary with AsEnumerable

**Comment by roji** [comment] 2024-11-28 14:12
@cincuranet note https://github.com/npgsql/efcore.pg/issues/3385 which is about FrozenSet, but seems to be the same issue otherwise.

**Closed** 2024-12-02 14:18 UTC
Labels: type-bug, closed-fixed, regression, customer-reported, area-query

**Comment by TonyValenti** [comment] 2024-12-04 18:38
Glad this resolution is coming. We are dealing with this as well.

**Comment by EvgenyMuryshkin** [comment] 2025-01-15 00:52
@cincuranet 
Still reproducible in 9.0.1 for MSSQL

Here is a repo with an example - see tests for EF8Perf_900
https://github.com/EvgenyMuryshkin/EF8PPerf

![Image](https://github.com/user-attachments/assets/32a1832c-f2a1-4c52-a973-cae3ee5f8c44)

Thanks,
Regards,
Evgeny

**Comment by cincuranet** [comment] 2025-01-20 13:18
I'll have a look.

**Comment by cincuranet** [comment] 2025-01-30 11:04
@EvgenyMuryshkin 

The `IdsContainerWithContainsQuery` is correct failure. The `Contains` method is your method, not the one from `IQueryable<T>` (or similar interfaces). The reason why it works on `BaseRefCollection` is because we have special handling for `ICollection<T>.Contains` with _assumption_ that if collection implements `ICollection<T>`  and you call method named `Contains` it's _the contains_ you want in query. Otherwise it would be weird naming that method `Contains`.

For the `GenericBaseRefCollectionQuery` it is a similar story. We do allow using custom collections, but we _assume_, that the first generic argument is the type for elements, because basically every collection is like that (well, basically every collection has only one generic argument). In your case, workaround would be to simply swap the order of generic arguments and it should be fine.

**Comment by EvgenyMuryshkin** [comment] 2025-01-30 11:17
@cincuranet thank you, I will have a look shortly.

Would be nice to have these assumptions somehow marked in code e.g. I mark Contains method to "save" assumption so IdsContainerWithContainsQuery  will also can be made workable.

**Comment by cincuranet** [comment] 2025-01-30 17:22
This is such an internal detail, that you'd be better off writing your own translator.

**Comment by EvgenyMuryshkin** [comment] 2025-01-30 21:16
> [@EvgenyMuryshkin](https://github.com/EvgenyMuryshkin)
> 
> The `IdsContainerWithContainsQuery` is correct failure. The `Contains` method is your method, not the one from `IQueryable<T>` (or similar interfaces). The reason why it works on `BaseRefCollection` is because we have special handling for `ICollection<T>.Contains` with _assumption_ that if collection implements `ICollection<T>` and you call method named `Contains` it's _the contains_ you want in query. Otherwise it would be weird naming that method `Contains`.
> 
> For the `GenericBaseRefCollectionQuery` it is a similar story. We do allow using custom collections, but we _assume_, that the first generic argument is the type for elements, because basically every collection is like that (well, basically every collection has only one generic argument). In your case, workaround would be to simply swap the order of generic arguments and it should be fine.

Nope, I swapped order of generics, then removed collection type arg. Test fails.
```
    public class GenericBaseRefCollection<TEntity> : ICollection<Guid>
        //where T : ICollection<Guid>, new()
        where TEntity : IEntity
```

```
Test method EF8Perf900.QueryTests.GenericBaseRefCollectionQuery threw exception: 
System.ArgumentException: Expression of type 'EF8Perf900.GenericBaseRefCollection`1[EF8Perf900.IEntity]' cannot be used for parameter of type 'System.Collections.Generic.IEnumerable`1[EF8Perf900.IEntity]' of method 'System.Linq.IQueryable`1[EF8Perf900.IEntity] AsQueryable[IEntity](System.Collections.Generic.IEnumerable`1[EF8Perf900.IEntity])' (Parameter 'arg0')
```

Something like this might help
```
[AssumeAsCollectionMethod] // attributes to help EF convert expressions
public bool Contains(Guid id) => _container.Contains(id);
```

Thanks

**Comment by EvgenyMuryshkin** [comment] 2025-01-30 21:38
@cincuranet 

I somewhat managed to get it running - first generic argument must be set to Guid in order to match underlying collection type.
```
    public class GenericBaseRefCollection<TArg, TEntity, T> : IEnumerable<TArg>, ICollection<TArg>
        where TArg : struct
        where TEntity : IEntity
        where T : ICollection<TArg>, new()
    {
```

and usage 
```
var refSet = new GenericBaseRefCollection<Guid, IEntity, HashSet<Guid>>();
```

but the result SQL is suspicious.

This is result from non-generic version
```
SELECT [r].[id], [r].[date_created], [r].[date_time], [r].[date_updated], [r].[index], [r].[is_system], [r].[revision]
FROM [tst].[raws] AS [r]
WHERE [r].[id] = '642e54f8-1869-471f-a382-c8ea105be415'
```


And this is for generic
```
exec sp_executesql N'SELECT [r].[id], [r].[date_created], [r].[date_time], [r].[date_updated], [r].[index], [r].[is_system], [r].[revision]
FROM [tst].[raws] AS [r]
WHERE [r].[id] IN (
    SELECT [r0].[value]
    FROM OPENJSON(@__refSet_0) WITH ([value] uniqueidentifier ''$'') AS [r0]
)',N'@__refSet_0 nvarchar(4000)',@__refSet_0=N'["4d8afc7f-3c9d-4a70-b954-5c3c5c2c5c48"]'
```

What else can be done here?

Thanks.

**Comment by roji** [comment] 2025-02-05 16:33
@cincuranet ping, in case you missed the above comment.

**Comment by EvgenyMuryshkin** [comment] 2025-02-06 02:20
@cincuranet @roji 

I did a bit more digging and it turns out that any generic argument will cause SQL to become exec - order, type or usage is irrelevant.

A sort of solution is to move all generic stuff to higher levels of inheritance

```
    public class HashSetGuidCollection<TEntity> : AbstractEntityCollection<TEntity>
        where TEntity : class
    {
        public HashSetGuidCollection()
        {
            _container = new HashSet<Guid>(); // create an instance of collection on top-level class instead of passing as generic arg
        }
    }

    public class ListGuidCollection<TEntity> : AbstractEntityCollection<TEntity>
        where TEntity : class
    {
        public ListGuidCollection()
        {
            _container = new List<Guid>(); // create an instance of collection on top-level class instead of passing as generic arg
        }
    }

    public abstract class AbstractEntityCollection<TEntity> : AbstractGuidCollection
        where TEntity : class
    {

    }

    public abstract class AbstractGuidCollection : ICollection<Guid>
    {
        protected ICollection<Guid> _container;

        public int Count => _container.Count;

        public bool IsReadOnly => _container.IsReadOnly;

        public void Add(Guid item)
        {
            _container.Add(item);
        }

        public void Clear()
        {
            _container.Clear();
        }

        public bool Contains(Guid item)
        {
            return _container.Contains(item);
        }

        public void CopyTo(Guid[] array, int arrayIndex)
        {
            _container.CopyTo(array, arrayIndex);
        }

        public IEnumerator<Guid> GetEnumerator()
        {
            return _container.GetEnumerator();
        }

        public bool Remove(Guid item)
        {
            return _container.Remove(item);
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return ((IEnumerable)_container).GetEnumerator();
        }
    }
```

**Comment by cincuranet** [comment] 2025-02-06 14:14
The reason for the difference is because `BaseGuidCollection<T>` is generic while `BaseRefCollection` is not. For generic one, again because of assumptions around collections, we do some internal optimizations to convert `.Contains()` into slightly different shape.

Here's where it starts:
https://github.com/dotnet/efcore/blob/6cacf97e1093965928d27e99a7b3f90d25c0b01b/src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs#L172-L177

The rest of the logic is built around that. In case of the non-generic one, it eventually falls back into `ContainsTranslator` and hence the `IN` in the resulting query.

**Comment by EvgenyMuryshkin** [comment] 2025-02-07 02:03
I don't know, lots more stuff no longer works in EF9, will see if I can distill it into reproducible sets.

**Comment by EvgenyMuryshkin** [comment] 2025-02-07 02:20
@cincuranet @roji 

Here is another example, works in EF8, does not work in EF9
Repo updated with test scenario https://github.com/EvgenyMuryshkin/EF8PPerf

```
        void ContainsInEnumerableWithOption(bool flag)
        {
            using (var ctx = Context)
            {
                var ids = flag ? ctx.Raws.Select(c => c.Id) : null;

                var items4 = ctx.Raws.Where(r => ids != null && ids.Contains(r.Id)).ToList();
            }
        }

        [TestMethod]
        public void ContainsInEnumerable()
        {
            ContainsInEnumerableWithOption(true);
            ContainsInEnumerableWithOption(false);
        }
```

**Comment by cincuranet** [comment] 2025-02-07 18:17
> Here is another example, works in EF8, does not work in EF9

#35598

> This is weird - query using just HashSet produces IN query in EF9. Is that an expected behavior now?

Yes.
