### ISSUE TITLE
Aggregate nullable nested data in select

### ISSUE THREAD

**Issue by ice1e0** [dotnet/efcore#16961] opened 2019-08-05 19:32 UTC
Given the following strucutre:
``` c#
public class Line
{
    public int EntryId { get; set; }
    public decimal Amount { get; set; }
}

public class Entry
{
    public int Id { get; set; }
    public decimal BaseAmount { get; set; }
    public ICollection<Line> Lines { get; set; }
}
```

When I now do the following query:
``` c#
var query = from e in context.Entries
    select new {
        Id = e.Id,
        TotalAmount = BaseAmount - e.Lines.Sum(l => l.Amount)
    };
var entry = query.FirstOrDefault();
```
I get the following exception in case that no `Lines` exist for an entry:

```
Exception message: InvalidOperationException: {"Das Objekt mit Nullwert muss einen Wert haben."} (ok, that's german and means like the object with null-value must have an value)
Stack trace:
   bei System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   bei lambda_method(Closure , QueryContext , ValueBuffer )
   bei Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   bei Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IShaper<TOut>.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   bei Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   bei Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   bei Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   bei lambda_method(Closure )
   bei Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   bei Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   bei System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   bei Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   bei Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   bei Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   bei System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
```

I found a way to work around this issue, and this is, to cast the Line.Amount into an nullable object and then deal with the nullable object via an null propagation:

``` c#
var query = from e in context.Entries
    select new {
        Id = e.Id,
        TotalAmount = BaseAmount - (e.Lines.Sum(l => (decimal?)l.Amount) ?? 0)
    };
var entry = query.FirstOrDefault();
```

But seriously, I think this is an ugly solution and I want to ask here if we can get something better, for example:

### Solution Option 1:
Add support for `DefaultIfEmpty(default)` at this point; currently this crashes.

``` c#
var query = from e in context.Entries
    select new {
        Id = e.Id,
        TotalAmount = BaseAmount - e.Lines.DefaultIfEmpty(default).Sum(l =>l.Amount)
    };
var entry = query.FirstOrDefault();
```

### Solution Option 2:
This one would require an special extension method.
``` c#
var query = from e in context.Entries
    select new {
        Id = e.Id,
        TotalAmount = BaseAmount - e.Lines.Sum(l =>l.Amount, handleEmptyResultAs: default)
    };
var entry = query.FirstOrDefault();
```

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 8.1
IDE: Visual Studio 2019 16.1.2

**Comment by ajcvickers** [comment] 2019-08-09 18:03
@maumar Is #13870 the dupe here?

**Comment by smitpatel** [comment] 2019-08-09 18:26
Duplicate of #12657

**Closed** 2022-10-16 14:34 UTC
Labels: closed-duplicate, customer-reported
