### ISSUE TITLE
Retrieving entity from db-context changes the entity-status to 'Added' 

### ISSUE THREAD

**Issue by KarlAndenmatten** [dotnet/efcore#4155] opened 2015-12-22 20:17 UTC
I have detected a very strange problem with the newest version of EntityFramework.Sqlite (rc1-final): retrieving data from the db-context marks the entity in the change-tracker as 'Added'!
To reproduce this i have stripped our model down to this simple model:
- Entity "Address" (no reference to other entities)
- Entity "Customer": references 'Address'
- Entity 'ServiceOrder': references 'Customer' and separate 'Address' (delivery address)

Whe add now two addresses, a customer and a service-order to the database. I then read the data on a separate db-context from the database:
- I read the order with including the delivery address and the customer but not with including the customers address:

```
var retrievedOrder = 
DbContext.ServiceOrders
.Include(o => o.Customer)
.Include(o => o.DeliveryAddress)
.SingleOrDefault(order => order.No.Equals(ORDER_NO));
```
- I read then the customer with including the customer-address:

```
var customer = DbContext.Customers
.Include(c => c.Address)
.SingleOrDefault(o => o.No.Equals(CUSTOMER_NO));
```

After the second statement the data in the db-context includes changed data: the customers address is marked as 'Added'! 
And additionally strange: when saving the context the generated sql-statement includes the unique 'Id' of the address which should be generated in the database.

When i include in the first statement additionally the customers address then all is ok.
I think that this is a very heavy bug because it could occur in very many circumstances and leads to very strange behaviour.

On my github-account I have uploaded the visual studio solution 'EF7BugRetrieveDataAddsThemToChangeTracker.zip' which reproduces the bug.

**Comment by rowanmiller** [comment] 2016-01-07 19:26
@KarlAndenmatten I'm not able to reproduce this issue. Below is the code I used to try and reproduce it. I did have to make a lot of assumptions based on details not included in the bug report, so perhaps you can just adjust my code listing to demonstrate the issue you are seeing.

```c#
using Microsoft.Data.Entity;
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new TestContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                var add1 = new Address { LineOne = "Somewhere" };
                var add2 = new Address { LineOne = "Somewhere Else" };
                var cus = new Customer { Name = "Bob", Address = add1 };
                var order = new ServiceOrder { DeliveryAddress = add2, Customer = cus };

                db.Addresses.Add(add1);
                db.Addresses.Add(add2);
                db.Customers.Add(cus);
                db.ServiceOrders.Add(order);
                db.SaveChanges();
            }

            using (var db = new TestContext())
            {
                var ORDER_NO = 1;

                var retrievedOrder =
                    db.ServiceOrders
                    .Include(o => o.Customer)
                    .Include(o => o.DeliveryAddress)
                    .SingleOrDefault(order => order.No.Equals(ORDER_NO));

                var CUSTOMER_NO = 1;

                var customer = db.Customers
                    .Include(c => c.Address)
                    .SingleOrDefault(o => o.No.Equals(CUSTOMER_NO));

                foreach (var item in db.ChangeTracker.Entries())
                {
                    Console.WriteLine($"{item.Entity.GetType()} : {item.State}");
                }
            }
        }
    }

    class TestContext : DbContext
    {
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<ServiceOrder> ServiceOrders { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Sample;Trusted_Connection=True;");
        }
    }

    public class Address
    {
        public int Id { get; set; }
        public string LineOne { get; set; }
    }

    public class Customer
    {
        [Key]
        public int No { get; set; }
        public string Name { get; set; }

        public int? AddressId { get; set; }
        public Address Address { get; set; }
    }

    public class ServiceOrder
    {
        [Key]
        public int No { get; set; }

        public int DeliveryAddressId { get; set; }
        public Address DeliveryAddress { get; set; }

        public int CustomerNo { get; set; }
        public Customer Customer { get; set; }
    }
}
```

Results in the following output:

> ConsoleApp1.ServiceOrder : Unchanged
ConsoleApp1.Customer : Unchanged
ConsoleApp1.Address : Unchanged
ConsoleApp1.Address : Unchanged

**Comment by KarlAndenmatten** [comment] 2016-01-07 21:54
@rowanmiller : I don't know if the bug also occurs in a console app but we use EF7 in our uwp-application and therefore i have prepared the uwp-application 
'EF7BugRetrieveDataAddsThemToChangeTracker.zip' to reproduce the bug. 
With this code it should easily be possible to reproduce the bug.
Why didn't you use this code to reproduce the bug?

**Comment by rowanmiller** [comment] 2016-01-07 22:06
@KarlAndenmatten ah I missed that you mentioned that file at the end of your bug report (apologies). I don't see it in GitHub though. I only see EF7BugBaseFieldsNotUpdated.zip and EF7BugWhenBuildx64.zip

**Comment by KarlAndenmatten** [comment] 2016-01-08 12:18
![image](https://cloud.githubusercontent.com/assets/15981528/12197764/492fd9a6-b60a-11e5-85e2-3dece71e8823.png)

**Comment by rowanmiller** [comment] 2016-01-08 18:19
@KarlAndenmatten yep I see it now. When I was looking at the repo yesterday there were only two commits, but now I see the third with the file you mentioned (maybe you only pushed the commit yesterday?). I'll take a look at it today.

**Comment by rowanmiller** [comment] 2016-01-22 19:45
Repro code is as follows. The bug must be in the interaction between materializing related data when `INotifyPropertyChanged` is implemented. Confirmed it still reproduces on a recent RC2 build.

```c#
using Microsoft.Data.Entity;
using System;
using System.ComponentModel;
using System.Linq;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new SampleContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                var customer = new Customer()
                {
                    Address = new Address
                    {
                        Name = "Customer",
                    },
                };

                db.Customers.Add(customer);
                db.Addresses.Add(customer.Address);
                db.SaveChanges();
            }

            using (var db = new SampleContext())
            {
                db.Customers.SingleOrDefault();
                db.Customers.Include(c => c.Address).SingleOrDefault();

                foreach (var item in db.ChangeTracker.Entries())
                {
                    Console.WriteLine($"{item.Entity} {item.State}");
                }
            }
        }

    }

    public class SampleContext : DbContext
    {
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Address> Addresses { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Data source=Test.db");
        }
    }

    public class Customer : INotifyPropertyChanged
    {
        private int _id;
        private Address _address;

        public int Id
        {
            get { return _id; }
            set
            {
                _id = value;
                OnPropertyChanged(nameof(Id));
            }
        }

        public Address Address
        {
            get { return _address; }
            set
            {
                _address = value;
                OnPropertyChanged(nameof(Address));
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    public class Address
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
```

Output is

> ConsoleApp1.Customer Unchanged
ConsoleApp1.Address Added

**Comment by rowanmiller** [comment] 2016-01-22 19:45
cc @ajcvickers

**Comment by rowanmiller** [comment] 2016-02-01 19:31
This is fixed in our latest code base (@ajcvickers checked in a fix last week)

**Closed** 2022-10-16 09:21 UTC
