### ISSUE TITLE
Inconvenient temporary identity keys

### ISSUE THREAD

**Issue by Jupakabra** [dotnet/efcore#4619] opened 2016-02-22 17:31 UTC
Is there a reason why EF7 started generating negative values for identity properties? Because now, compared to EF6 it's very hard to use identity columns then inserting parent/child entities together. Inserting only parent entity doesn't insert children either, don't know if it's intended. Remapping everything after each context add seems to be a lot of work and might not be available in some scenarios.

``` C#
public class Parent
{
    public Int32 Id { get; set; }

    public IList<Child> Children { get; set; }
}

public class Child
{
    public Int32 Id { get; set; }
    public String Name { get; set; }

    public Int32 ParentId { get; set; }
    public Parent Parent { get; set; }
}

public class Program
{
    public void Insert(Parent parent)
    {
        DbContext context = new Context();
        context.Add(parent); // doesn't insert children?

        context.Add(parent.Children[0]);

        context.SaveChanges(); // crash, parent got -1 id and child still has 0
    }
}
```

**Comment by rowanmiller** [comment] 2016-02-22 17:53
@Jupakabra the negative numbers are only temporary values that are used until the data is saved and a value is generated by the database.

> `context.Add(parent); // doesn't insert children?`

What version are you using? This should also add the children. In RC1, adding a child won't add the parent... but we are changing that for RC2.

> `context.SaveChanges(); // crash, parent got -1 id and child still has 0`

Are you using RC1? This would be a bug, but I am not able to reproduce it. Below is some code I used to try and get the same error, but it inserts data as expected and propagates the value generated for parent ids to the related children.

```c#
using Microsoft.Data.Entity;
using System;
using System.Collections.Generic;

namespace Console.CI
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new Context())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
            }


            var parent = new Parent
            {
                Children = new List<Child>
                {
                    new Child {  Name = "Ted" },
                    new Child {  Name = "Jane" },
                    new Child {  Name = "Bob" }
                }
            };

            Insert(parent);

            System.Console.WriteLine($"Parent: {parent.Id}");
            foreach (var child in parent.Children)
            {
                System.Console.WriteLine($" - Child: {child.Id} | ParentId: {child.ParentId}");
            }
        }

        public static void Insert(Parent parent)
        {
            DbContext context = new Context();
            context.Add(parent);
            context.SaveChanges();
        }
    }

    class Context : DbContext
    {
        public DbSet<Parent> Parents { get; set; }
        public DbSet<Child> Children { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Sample;Trusted_Connection=True;");
        }
    }

    public class Parent
    {
        public Int32 Id { get; set; }
        public IList<Child> Children { get; set; }
    }

    public class Child
    {
        public Int32 Id { get; set; }
        public String Name { get; set; }

        public Int32 ParentId { get; set; }
        public Parent Parent { get; set; }
    }
}
```

Here is the output.

```
Parent: 1
 - Child: 1 | ParentId: 1
 - Child: 2 | ParentId: 1
 - Child: 3 | ParentId: 1
```

**Comment by Jupakabra** [comment] 2016-02-22 18:52
Yes, I was using RC1, glad it's fixed in RC2. Thanks.

**Comment by rowanmiller** [comment] 2016-02-22 18:54
@Jupakabra the code I listed above actually works in RC1, so perhaps you could adjust it to demonstrate your issue so that we can verify it is fixed in RC2?

**Comment by Jupakabra** [comment] 2016-02-24 13:57
ok, I will try that

**Comment by Jupakabra** [comment] 2016-02-24 14:41
@rowanmiller, I found the problem
```C#
public class Program
{
    public void Insert(Parent parent, Child child)
    {
        DbContext context = new Context();
        context.Add(parent); // parent.Children is empty, parent gets -1
        context.Add(child); // child has parent id 0 and Parent property is null

        context.SaveChanges(); // crash, child didn't update to -1
    }
}
```
I'm guessing this worked on EF6, because it didn't generate any new ids.
I suppose, managing relations correctly, is a fair thing to ask here.

**Comment by rowanmiller** [comment] 2016-02-24 17:54
@Jupakabra ah, yes that makes sense - thanks for following up

**Closed** 2022-10-16 09:30 UTC
