### ISSUE TITLE
#EF Core 6.0.10  EntityTypeConfiguration seting class can't  binds DataBase Table

### ISSUE THREAD

**Issue by Aaron-Rommel** [dotnet/efcore#29454] opened 2022-10-30 09:50 UTC
### Include your code

To fix any bug we must first reproduce it. To make this possible, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

 EntityTypeBuilder  ToTable  is not defined .
![image](https://user-images.githubusercontent.com/45854331/198872471-bb9c834e-237b-4bf7-966c-c521ea2c777c.png)

```C#
        public void Configure(EntityTypeBuilder<Blog> builder)
        {
            builder.ToTable("dbo.T_Blogs");
            builder.HasKey(x => x.Id);
            builder.Property(x => x.Url).HasMaxLength(250).HasField("Url").IsRequired();

            //关联表
            builder.HasMany(x => x.Posts).WithOne(r => r.Blog).HasForeignKey(r => r.BlogId);

        }
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS1061	“EntityTypeBuilder<Blog>”未包含“ToTable”的定义，并且找不到可接受第一个“EntityTypeBuilder<Blog>”类型参数的可访问扩展方法“ToTable”(是否缺少 using 指令或程序集引用?)	Rommel.EF.CORE.STUDY	F:\07 - Rommel Study\.NET CORE\11 .NET CORE WEB API\Rommel.EF.CORE.STUDY\Rommel.EF.CORE.STUDY\Models\BlogEntityTypeConfiguration\BlogEntityTypeConfiguration.cs	10	活动

```

### Include verbose output

Please include `--verbose` output when filing bugs about the `dotnet ef` or Package Manager Console tools.

Use triple-tick fences for tool output. For example:

```
1>
已启动生成...
1>------ 已启动生成: 项目: Rommel.EF.CORE.STUDY, 配置: Debug Any CPU ------
1>跳过分析器以加快生成速度。可以执行“生成”或“重新生成”命令来运行分析器。
1>F:\07 - Rommel Study\.NET CORE\11 .NET CORE WEB API\Rommel.EF.CORE.STUDY\Rommel.EF.CORE.STUDY\Models\BlogEntityTypeConfiguration\PostEntityTypeConfiguration.cs(13,21,13,28): error CS1061: “EntityTypeBuilder<Post>”未包含“ToTable”的定义，并且找不到可接受第一个“EntityTypeBuilder<Post>”类型参数的可访问扩展方法“ToTable”(是否缺少 using 指令或程序集引用?)
1>F:\07 - Rommel Study\.NET CORE\11 .NET CORE WEB API\Rommel.EF.CORE.STUDY\Rommel.EF.CORE.STUDY\Models\BlogEntityTypeConfiguration\BlogEntityTypeConfiguration.cs(10,21,10,28): error CS1061: “EntityTypeBuilder<Blog>”未包含“ToTable”的定义，并且找不到可接受第一个“EntityTypeBuilder<Blog>”类型参数的可访问扩展方法“ToTable”(是否缺少 using 指令或程序集引用?)
1>已完成生成项目“Rommel.EF.CORE.STUDY.csproj”的操作 - 失败。
========== “生成”: 0 成功，1 失败，0 更新，0 已跳过 ==========
```

### Include provider and version information

EF Core version:
Database provider:  Microsoft.EntityFrameworkCore.SqlServer (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET 6  (e.g. .NET 5.0)
Operating system:
IDE:Visual Studio 2022   17.3.1 (e.g. Visual Studio 2019 16.3)

**Comment by roji** [comment] 2022-10-30 18:48
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-11-07 16:13
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-11-07 16:13 UTC
Labels: customer-reported
