### ISSUE TITLE
Baffling query generation with .Include and multiple conditions

### ISSUE THREAD

**Issue by 36PopTarts** [dotnet/efcore#29398] opened 2022-10-19 20:55 UTC
## Ask a question
**EF Core Version:** EF Core 3.1,
**DB Provider:** Microsoft.EntityFrameworkCore.SqlServer
**Target Framework:** .NET Core 3.1
**Operating system:** Windows Server 2012 R2
**IDE:** Visual Studio 2019 16.10.2

**Background:** I am writing code which identifies records which haven't yet been added to another table that tracks encrypted files, then it encrypts the file on disk and adds a new row for that file. There are three tables I am working with here:
* ManagedFile (tracks encrypted files, lives on a separate database server)
* DocDetails (tracks all files, some of which may be in ManagedFile, and some which are not)
* DocVersion (tracks new versions of files in DocDetails stored as separate files, some of which may be in ManagedFile, has a many-to-one relationship with DocDetails)

The key value linking these three tables together is a GUID. ManagedFile doesn't care about the difference between DocDetails and DocVersion; they both represent individual files and it tracks encrypted files. Ideally every GUID from both DocDetails and DocVersion would eventually be added to ManagedFile once they're all encrypted.

**The Problem:** I am trying to write a query that fetches all the DocDetails records that don't have a GUID in ManagedFile, and I also want to include the DocVersion records associated with each DocDetails record. However, EF Core generates baffling queries that I simply do not understand and it results in bad data sets.
**My Code:** 
```
managedFileGuids = await context1.ManagedFile
                    .Include(x => x.Account)
                    .Where(x => x.Account.AccountAlias == tenantAlias)
                    .Select(x => x.ManagedFileServerName.ToString())
                    .ToListAsync();
...
var unmanagedFiles = context2.DocDetails
                    .Include(x => x.DocVersion)
                    .Where(x => x.IsDeleted != 1
                                && (!managedFileGuids.Contains(x.DocGUID) 
                                    || x.DocVersion.Any(y => !managedFileGuids.Contains(y.DocGUID))))
```
**Expected Result:** A query that would start something like this:
```
SELECT * FROM DocDetails dd
LEFT JOIN DocVersion dv
    ON dd.Id = dv.DocDetailsId
...
```
Instead, EF generates this:
```
SELECT [x.TDocVersion].[Id], <columns omitted>
      FROM [DocVersion] AS [x.DocVersion]
      INNER JOIN (
          SELECT [x0].[Id]
          FROM [DocDetails] AS [x0]
          WHERE ([x0].[IsDeleted] <> 1) AND ([x0].[DocGUID] NOT IN <long list of GUIDs> OR EXISTS (
              SELECT 1
              FROM [TDocVersion] AS [y0]
              WHERE [y0].[DocGUID] NOT IN <long list of GUIDs> AND ([x0].[Id] = [y0].[DocDetailsId])))
      ) AS [t] ON [x.DocVersion].[DocDetailsId] = [t].[Id]
      ORDER BY [t].[Id]
```
This isn't going to work, because there are DocDetails records without equivalent DocVersion records if a new version hasn't been created. The INNER JOIN filters those rows. Why is a LEFT JOIN not being used, and why is the relationship reversed in the query? The foreign key is not required and it is a one-to-many relationship. On top of that, in the result set the GUIDs in the "NOT IN" clause are included for some reason. I can't quite wrap my mind around this.

**Comment by smitpatel** [comment] 2022-10-19 22:01
This is not EF Core 3.1 query.

**Comment by 36PopTarts** [comment] 2022-10-20 14:34
Okay. I'm beginning to think it's more difficult to keep up with the evolving syntax than to just use and refine my knowledge of T-SQL. Can you explain how an INNER JOIN somehow includes the records I'm looking for? Because I'm not getting it from the generated syntax.

This project targets 3.1 but it seems I have to use 2.2 due to library dependencies. It's a mess.

**Comment by ajcvickers** [comment] 2022-10-21 10:43
@36PopTarts EF Core 2.2 has been out-of-support for a couple of years now. If you have questions about SQL generated by EF Core 3.1 or later, then we'll take a look at that.

**Comment by ajcvickers** [comment] 2022-11-02 19:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-11-02 19:28 UTC
Labels: customer-reported
