### ISSUE TITLE
Exception when using EF Core InMemory and a projection including Count and a non-parameterless constructor

### ISSUE THREAD

**Issue by jgbpercy** [dotnet/efcore#21001] opened 2020-05-20 17:27 UTC
## Issue
The following combination of things causes a runtime exception:
- Using the EF Core InMemory provider
- A Select LINQ projection expression with a constructor that is **not** parameterless
- Using `.Count` or `.Count()` on some navigation property

If _any_ of these three things is not true, then the code works. The same code works with SQLite in memory and SQL Server providers (not tried any other providers). Using a parameterless constructor makes the problem go away. Avoiding calling Count makes the problem go away.

### Steps to reproduce

Run the unit tests in [this minimal reproduction solution](https://github.com/jgbpercy/EfCoreInMemoryBug).

There are five tests:
- InMemory with parameterless constructor, which runs ok
- SQLite (in memory) with parameters in the constructor, which runs ok
- Three variations on InMemory with parameters in the constructor, all of which throw the same exception (albeit with very slight variations in the stack trace)

The exception is as follows:
```
  Message: 
    System.InvalidCastException : Unable to cast object of type 'System.Linq.Expressions.NewExpression' to type 'System.Linq.Expressions.MethodCallExpression'.
  Stack Trace: 
    InMemoryQueryExpression.AddSubqueryProjection(ShapedQueryExpression shapedQueryExpression, Expression& innerShaper)
    InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
    InMemoryProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
    NewExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
    InMemoryProjectionBindingExpressionVisitor.Translate(InMemoryQueryExpression queryExpression, Expression expression)
    InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
    QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    MethodCallExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
    Database.CompileQuery[TResult](Expression query, Boolean async)
    QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
    <>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
    CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
    CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
    QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
    EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
    EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
    ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
    EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
    EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
    Tests.InMemoryCtorParams() line 30
    --- End of stack trace from previous location where exception was thrown ---
```

### Further technical details

EF Core version: Tried with 3.1.2 and 3.1.4 (same issue on both versions)
Database provider: The minimal repro uses InMemory and SQLite (in memory). In our real code, using the SQL Server provider (at runtime) works and does not error, as with SQLite. Using the InMemory provider (in our tests) fails.
Target framework: NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.5.4

**Comment by smitpatel** [comment] 2020-05-20 17:36
Duplicate of #17620

**Closed** 2022-10-16 18:26 UTC
Labels: closed-duplicate, customer-reported
