### ISSUE TITLE
AsSplitQuery not working with sort string.Join

### ISSUE THREAD

**Issue by jindovu** [dotnet/efcore#32749] opened 2024-01-09 08:23 UTC
When I upgrade from ef 3x to ef 8.0 and using AsSplitQuery for complex query, it's not working with sort string.Join as query below, please help me to resolve this.

### 
```
var data = model.Data;
var sortColumn = model.SortColumn;

var query = Query(x => !x.IsDeleted)
    .Include(x => x.FabricTestResultTo)
    .ThenInclude(x => x.User);
if (!string.IsNullOrEmpty(sortColumn.ColumnName) && sortColumn.ColumnName.Equals("testResultTo"))
{
    query = sortColumn.IsAsc ? query.OrderBy(x => string.Join(",", x.FabricTestResultTo.Where(c => !c.IsDeleted).Select(c => c.User.Name).ToList()))
                : query.OrderByDescending(x => string.Join(",", x.FabricTestResultTo.Where(c => !c.IsDeleted).Select(c => c.User.Name).ToList()));
}
else
{
    query = query.OrderByDescending(x => x.Id);
}
 var queryResult = query.AsSplitQuery();
 result.Records = queryResult.Select(ConvertFabricResult).ToList();
```
EF Core version: 
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 8.0
Operating system: Window
IDE: Visual Studio 2022 17.8

**Comment by ajcvickers** [comment] 2024-01-09 15:56
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by jindovu** [comment] 2024-01-10 09:50
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

Please check out with this sample https://github.com/jindovu/AsSplitQuery-.git
Thank you.

**Comment by ajcvickers** [comment] 2024-01-16 15:02
@jindovu This throws the following exception for me even without AsSplitQuery. Are you seeing something different?

```
Unhandled exception. System.InvalidOperationException: The LINQ expression 'DbSet<FabricTest>()
    .Where(f => !(f.IsDeleted))
    .Where(f => f.IsActive)
    .OrderBy(f => string.Join(
        separator: ",", 
        values: DbSet<FabricTestResultTo>()
            .Where(f0 => EF.Property<int?>(f, "Id") != null && object.Equals(
                objA: (object)EF.Property<int?>(f, "Id"), 
                objB: (object)EF.Property<int?>(f0, "FabricTestId")))
            .Where(f0 => !(f0.IsDeleted))
            .Join(
                inner: DbSet<User>(), 
                outerKeySelector: f0 => EF.Property<int?>(f0, "UserId"), 
                innerKeySelector: u => EF.Property<int?>(u, "Id"), 
                resultSelector: (o, i) => new TransparentIdentifier<FabricTestResultTo, User>(
                    Outer = o, 
                    Inner = i
                ))
            .Select(f0 => f0.Inner.Name)
            .ToList()))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in D:\code\repros\AsSplitQuery--main\AsSplitQuery--main\Demo\Demo\Program.cs:line 92
```

**Comment by ajcvickers** [comment] 2024-01-17 19:48
@maumar to check if this is a regression.

**Comment by jindovu** [comment] 2024-01-22 09:22
> @maumar to check if this is a regression.

thanks, hopefully, it will be fixed soon

**Comment by maumar** [comment] 2024-01-22 19:11
I tried this on 3.1.32 and getting translation error as well. This would have "worked" on 2.x because we did client evaluation. The query is essentially trying to order by over string aggregate coming from a correlated subquery.

**Comment by jindovu** [comment] 2024-01-23 06:56
> I tried this on 3.1.32 and getting translation error as well. This would have "worked" on 2.x because we did client evaluation. The query is essentially trying to order by over string aggregate coming from a correlated subquery.

You are right, we upgrade from 2.1 to 3.1 and up to version 8, What I should to do for this?

**Comment by ilmax** [comment] 2024-01-23 07:34
You should probably materialize (i.e. add a ToList/ToListAsync/ToArray/ToArrayAsync/etc before the OrderBy) and execute the OrderBy in memory. That's pretty much what EF core v2 was doing anyway with client eval.

**Comment by roji** [comment] 2024-01-23 12:02
For cases like this, using AsEnumerable or AsAsyncEnumerable is preferable to ToList/ToArray, since the latter materialize the full results in memory, only to be processed by another LINQ operator (OrderBy). As a result, AsEnumerable uses much less memory.

Apart from that, translating the actual query is tracked by #29200, as this is an aggregate function without a GroupBy.

**Comment by roji** [comment] 2024-01-23 12:02
Duplicate of #29200

**Comment by jindovu** [comment] 2024-01-24 04:16
Thank you for your all support, using AsEnumerable before sort already resloved issue.

**Closed** 2024-01-24 11:25 UTC
Labels: customer-reported
