### ISSUE TITLE
Error Downloading  7.0.0-beta5-12747 build via Nuget

### ISSUE THREAD

**Issue by codemasta** [dotnet/efcore#1947] opened 2015-03-29 22:44 UTC
![new error](https://cloud.githubusercontent.com/assets/1274708/6888158/2a9f078c-d66d-11e4-83bd-c599bb6a853c.PNG)

Please see error from 7.0.0-beta5-12747 build via  https://www.myget.org/F/aspnetvnext/  Nuget URL

**Comment by bricelam** [comment] 2015-03-30 03:51
Dupe of #1882?

**Closed** 2022-10-16 08:53 UTC
