### ISSUE TITLE
Consider allowing to specify another DbContext for the .Include method

### ISSUE THREAD

**Issue by JeanCollas** [dotnet/efcore#11654] opened 2018-04-12 08:15 UTC
It may happen that we store data in different databases and that we would like to do JOINs, load collections of objects, etc...

What about allowing to specify a DbContext when including? Something like:

    var owner = await _Context.Users.Where(u => u.Name == "John").IncludeExternal<CarsDbContext>(u => u.Cars).FirstOrDefaultAsync();

Or by providing the DbContext instance to the method, foreign key information or whatever is required.

**Comment by tuespetre** [comment] 2018-04-12 12:55
That seems like a very niche requirement. Why not just write a join between the two or store that kind of data in a denormalized schema or document format?

**Comment by JeanCollas** [comment] 2018-04-12 13:13
Dealing with several database is really a niche?

Anyway, this could also be used in order to specialize DbContexts, and have "unit contexts" instead of multiplying contexts for each use cases or building a single huge DbContext.

For example, an event database would have different units
- Authentication
- Users data
- Places data
- Events data
- Images data

And depending on the complexity of each unit, it may require a number of tables/views/functions/... to be handled.
By using a combination of 5 DbContext, it would be possible to handle any case. It may not be always optimal in DB query, but it does not matter if it is not the objective. 

That is a suggestion.


In case of a same database, an option to share the connection by registering several dbcontext at once could also be a nice optimization.

**Comment by tuespetre** [comment] 2018-04-12 14:05
> Dealing with several database is really a niche?

No, just the include overload. There would also need to be model logic bridging the two contexts and their models. Change tracking would also need to get involved or be explicitly disallowed. It’s a fair amount of complexity for something that could be easily done without it.

**Comment by ajcvickers** [comment] 2018-04-13 18:56
Duplicate of #6089

**Comment by JeanCollas** [comment] 2018-04-13 22:48
Indeed seems it is the same problematic. This case is not so much a "niche feature"...

**Closed** 2022-10-16 12:18 UTC
Labels: closed-duplicate
