### ISSUE TITLE
'System.TypeLoadException. Method 'get_SqlGenerationHelper' in type 'Microsoft.Data.Entity.Storage.Internal.SqlServerDatabaseProviderServices'

### ISSUE THREAD

**Issue by takazm** [dotnet/efcore#4175] opened 2015-12-25 22:05 UTC
I am getting this following error in my ConfigureServices method of my Startup class, specifically, the line that I add EF to the DI Container:  **Method 'get_SqlGenerationHelper' in type 'Microsoft.Data.Entity.Storage.Internal.SqlServerDatabaseProviderServices' from assembly 'EntityFramework.MicrosoftSqlServer, 
Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.**
![error](https://cloud.githubusercontent.com/assets/5674007/12004469/4d4922c8-ab64-11e5-9871-ec80f185857f.PNG)

**Comment by druzza** [comment] 2015-12-29 19:34
@takazm How are the steps to reproduce this problem? It seems to be a misconfigured service.

Could you try to change this piece of code with the following code:

```csharp
services
    .AddEntityFramework()
    .AddSqlServer()
    .AddDbContext<LeaseContext>(options => options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));
```

**Comment by takazm** [comment] 2015-12-31 13:22
Unfortunately that is no longer applicable in rc2-*.  See screenshot
![ef7rc2](https://cloud.githubusercontent.com/assets/5674007/12064679/447b27dc-afd2-11e5-86db-039cbceaad82.png)

**Comment by takazm** [comment] 2015-12-31 13:42
Sorry, i just realized that i needed to add the an additional using statement to get the method ; 
using **Microsoft.Data.Entity;**

**Comment by takazm** [comment] 2015-12-31 13:46
I did modify as suggested and still get the error
![error22](https://cloud.githubusercontent.com/assets/5674007/12064845/a1873c88-afd5-11e5-9131-75f130de1347.PNG)

**Comment by druzza** [comment] 2015-12-31 19:07
Inspect your dnx version and nuget feed.
If the problem continues, try to reinstall VS2015 updates.
Take a look at http://docs.asp.net/en/latest/getting-started/installing-on-windows.html

**Comment by takazm** [comment] 2015-12-31 19:23
I have been working on the same project since beta8 and it was running just fine so I'm convinced packages changed after rc1-final as it was my last known good run (currently on rc2-16357). I could go back to targeting rc1-final and see if it works.

**Comment by bricelam** [comment] 2015-12-31 20:33
EntityFramework.SqlServer got renamed to EntityFramework.MicrosoftSqlServer. Are you still using the old one?

**Comment by takazm** [comment] 2015-12-31 21:33
No. I am not. Here's my packages file 
![packages](https://cloud.githubusercontent.com/assets/5674007/12068443/f2f9f510-b016-11e5-9f65-4663b9ed77bf.PNG)

**Comment by takazm** [comment] 2015-12-31 22:18
Thanks @bricelam. After uploading the screenshot I realized that one of my references for EF is targeting rc1. After updating it works now.
![packages2](https://cloud.githubusercontent.com/assets/5674007/12068746/18e04166-b01d-11e5-9f62-ccaa9948afcf.PNG)

**Comment by rowanmiller** [comment] 2015-12-31 22:54
@takazm ok to close this one now?

**Comment by takazm** [comment] 2015-12-31 23:25
Yes please.

**Closed** 2022-10-16 09:22 UTC
