### ISSUE TITLE
Unnecessary left joins in query generation in EF Core 3 and 5

### ISSUE THREAD

**Issue by z16** [dotnet/efcore#23577] opened 2020-12-03 23:34 UTC
We recently tried upgrading our code base from 2.1 to 5.0 and noticed a difference in SQL query generation, which was expected given the extent of the internal changes. While our query speed improved significantly across the board, there were single instances in which the computation time spiked and we realized it was because the query generation included left joins that were unnecessary. But I don't know whether this is a bug or an intended change that we may have to live with, as there is a workaround which I will mention later. It may be related to #21774, but I feel it goes a bit beyond the description, as it does not only affect the result size and is actually used (to whatever redundant effect) in the `WHERE` clause as well.

The full minimal working example can be found [here](https://gist.github.com/z16/057de79fe650fa1230b0f9c6f34820cc) and is reproducible on a simple SQLite DB, but the same query is generated on our SQL Server instance. The relevant classes are here:
```cs
	internal class Main {
		public Int32 Id { get; set; }
		public Related Related { get; set; }
	}

	internal class Related {
		public Int32 Id { get; set; }
	}
```

If you now execute this query:
```cs
var query = db.Mains.Where(m => m.Related.Id == 1);
```

You get these results based on the EF Core version (removed double quotes for legibility):
```sql
-- 5.0.0

SELECT m.Id, m.RelatedId
FROM Mains AS m
LEFT JOIN Relateds AS r ON m.RelatedId = r.Id
WHERE r.Id = 1

-- 3.1.10

SELECT m.Id, m.RelatedId
FROM Mains AS m
LEFT JOIN Relateds AS r ON m.RelatedId = r.Id
WHERE r.Id = 1

-- 3.0.0

SELECT m.Id, m.RelatedId
FROM Mains AS m
LEFT JOIN Relateds AS r ON m.RelatedId = r.Id
WHERE (r.Id = 1) AND r.Id IS NOT NULL

-- 2.1.14

SELECT m.Id, m.RelatedId
FROM Mains AS m
WHERE m.RelatedId = 1
```

From 3.0 onwards all EF Core versions use left joins, but I do not understand the need for them. To my eyes the queries look semantically identical, just some more bloated than others. Since the left joins join on the field which we use to filter, and nowhere else, it may as well have been omitted (as indeed EF Core 2.1 did).

As I mentioned before, there is a workaround. If you add the foreign entity IDs to the respective entity models as well you can use them to compare, i.e. if you had `public Int32 RelatedId { get; set; }` you could use that, and in that case there would be no left join generated. Unfortunately it would involve adjusting a significant part of our code base, especially since we don't use them elsewhere and it would be just a crutch to get this to work. Not to mention the field already does exist, and is already linked to the foreign entity's own ID (as that is how the query is built in the first place).

So I was wondering if there was another way around this, possibly some configuration setting, attributes to use on the DB entity classes, or a different way to design our query? Or is using explicit ID fields the intended way to use EF Core going forward?

I am far from a DB expert, so there may be something I'm missing here. If so, sorry for the possibly dumb question.

**Comment by z16** [comment] 2020-12-03 23:38
Minor addition, while in some test cases the DB manages to abstract those left joins away (as it did in some sample cases I tried to create), it failed to do so in others, like some of the queries in our actual code base. So if the idea was to rely on the DB to handle it, it is not working reliably.

**Comment by smitpatel** [comment] 2020-12-03 23:42
Duplicate of #15826

**Comment by z16** [comment] 2020-12-03 23:55
I always admire people who can find things in 3 minutes that I couldn't after two hours of searching. Thanks! And sorry for the unnecessary issue.

**Comment by ajcvickers** [comment] 2020-12-03 23:58
@z16 Believe me, we all admire @smitpatel's ability to find things and remember issue numbers. I think he may have a secret implant...

**Closed** 2022-10-16 19:13 UTC
Labels: closed-duplicate, customer-reported
