### ISSUE TITLE
More than 2 Unions cannot be translated

### ISSUE THREAD

**Issue by Ben555555** [dotnet/efcore#32544] opened 2023-12-07 12:50 UTC
## File a bug

The following code cannot be translated and throws an exception:

```
            var data = await dbContext.DistributionLists.Select(distributionList => new
            {
                Id = distributionList.Id,
                Contacts = distributionList.DistributionListUsers
                .Select(distributionListUser => new
                {
                    Id = distributionListUser.UserId,
                    Name = Convert.ToString(distributionListUser.User.FirstName),
                    Email = Convert.ToString(distributionListUser.User.Email)
                })
                .Union(distributionList.DistributionListNaturalPersonAddresses
                .Select(distributionListNaturalPersonAddress => new
                {
                    Id = distributionListNaturalPersonAddress.NaturalPersonAddressId,
                    Name = Convert.ToString(distributionListNaturalPersonAddress.NaturalPersonAddress.FirstName!),
                    Email = Convert.ToString(distributionListNaturalPersonAddress.NaturalPersonAddress.Email)
                }))
                .Union(distributionList.DistributionListJuridicalPersonAddresses
                .Select(distributionListJuridicalPersonAddress => new
                {
                    Id = distributionListJuridicalPersonAddress.JuridicalPersonAddressId,
                    Name = Convert.ToString(distributionListJuridicalPersonAddress.JuridicalPersonAddress.Name!),
                    Email = Convert.ToString(distributionListJuridicalPersonAddress.JuridicalPersonAddress.Email)
                })).ToList()
            }).ToListAsync();
```

If the Unions are nested it works though:

            var data = await dbContext.DistributionLists.Select(distributionList => new
            {
                Id = distributionList.Id,
                Contacts = distributionList.DistributionListUsers
                .Select(distributionListUser => new
                {
                    Id = distributionListUser.UserId,
                    Name = Convert.ToString(distributionListUser.User.FirstName),
                    Email = Convert.ToString(distributionListUser.User.Email)
                })
                .Union(distributionList.DistributionListNaturalPersonAddresses
                .Select(distributionListNaturalPersonAddress => new
                {
                    Id = distributionListNaturalPersonAddress.NaturalPersonAddressId,
                    Name = Convert.ToString(distributionListNaturalPersonAddress.NaturalPersonAddress.FirstName!),
                    Email = Convert.ToString(distributionListNaturalPersonAddress.NaturalPersonAddress.Email)
                }).Union(distributionList.DistributionListJuridicalPersonAddresses
                .Select(distributionListJuridicalPersonAddress => new
                {
                    Id = distributionListJuridicalPersonAddress.JuridicalPersonAddressId,
                    Name = Convert.ToString(distributionListJuridicalPersonAddress.JuridicalPersonAddress.Name!),
                    Email = Convert.ToString(distributionListJuridicalPersonAddress.JuridicalPersonAddress.Email)
                }))).ToList()
            }).ToListAsync();

Shouldn't this result in the same query? I think the first approach is more intuitive.
The weirdest thing is, when I remove the Email property from each projection, the exception is also thrown with the nested Unions.

### Include stack traces

System.InvalidOperationException: Unable to translate a collection subquery in a projection since either parent or the subquery doesn't project necessary information required to uniquely identify it and correctly generate results on the client side. This can happen when trying to correlate on keyless entity type. This can also happen for some cases of projection before 'Distinct' or some shapes of grouping key in case of 'GroupBy'. These should either contain all key properties of the entity that the operation is applied on, or only contain simple property access expressions.
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyProjection(Expression shaperExpression, ResultCardinality resultCardinality, QuerySplittingBehavior querySplittingBehavior)
   at Microsoft.EntityFrameworkCore.Query.Internal.SelectExpressionProjectionApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

### Include provider and version information

EF Core version: 6.0.11
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment] 2023-12-13 16:20
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2024-01-03 14:09
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-01-03 14:09 UTC
Labels: customer-reported
