### ISSUE TITLE
HasFilter not worked on Microsoft.EntityFrameworkCore.Sqlite for UnitTest

### ISSUE THREAD

**Issue by Wenfengcheng** [dotnet/efcore#28458] opened 2022-07-15 09:01 UTC
A unique index where at least one column is nullable will by default get a filter like [SomeColumn] IS NOT NULL. With EF Core 6.0.7, this filter could be suppressed with .HasFilter(null) in the fluent definition, like so:

```C#
x.Entity<Template>()
    .HasIndex(d => new { d.ExternalId })
    .IsUnique(true)
    .HasFilter(null);
```

Use sqlite as provider for unit test , two entities with both [ExternalId] is null can be saved normally, but we expect it to fail, sample code like this:

```C#
connection = new SqliteConnection("Filename=:memory:");
connection.Open();

var dbName = $"Db_{DateTime.Now.ToFileTimeUtc()}";
contextOptions = new DbContextOptionsBuilder<CreatorDbContext>()
    .UseSqlite(connection)
    .Options;

context = new CreatorDbContext(contextOptions);
context.Database.EnsureCreated();
```

Microsoft.EntityFrameworkCore.Sqlite version: 6.0.7
Target framework: net6.0
Operating system: Windows 11

**Comment by ajcvickers** [comment] 2022-07-23 10:20
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-08-02 13:32
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-08-02 13:32 UTC
Labels: customer-reported
