### ISSUE TITLE
Support join with enumerable on client

### ISSUE THREAD

**Issue by dotlogix** [dotnet/efcore#17031] opened 2019-08-08 16:06 UTC
Describe what is not working as expected.
Why EF Core cant translate this query, its is a simple join on multiple columns and looks the same as in many tutorials for EF.
Is this not implemented yet and the tutorials are related to ef6 or what's wrong with this implementation?

Is there any way to solve this kind of Problem in EF Core?

```c#
protected override Task<List<TEntity>> LoadEntitiesAsync(DbContext context, IEnumerable<(string fsymId, string feItem, DateTime feFpEnd)> keys) {
return context.Set<TEntity>()
        .Join(keys,
          e => new { p1= e.FsymId, p2=e.FeItem, p3 = e.FeFpEnd },
          i => new { p1= i.fsymId, p2=i.feItem, p3 = i.feFpEnd },
          (e, i) => e)
        .ToListAsync();
		}
```

### Further technical details
EF Core version: 2.2.6.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: (e.g. Visual Studio 2019)

**Comment by smitpatel** [comment] 2019-08-08 16:46
`keys` is client side enumerable. The join is purely client side. You can just get all TEntity-ies from server and do join on client. If not then how are you expecting this to be translated to server? Can you write a SQL translation for it?

**Comment by dotlogix** [comment] 2019-08-08 17:23
Sure I would expect sth like this:

SELECT e.* FROM [table] e
JOIN (SELECT * FROM VALUES ((p1, p2, p3), ...) AS i (p1, p2, p3)) ON e.p1=i.p2 AND e.p2=i.p2 AND e.p3=i.p3

It should be used to select multiple entities BA a 3 column composite key

**Comment by smitpatel** [comment] 2019-08-08 17:25
That is invalid SQL in SqlServer.

**Comment by dotlogix** [comment] 2019-08-08 17:35
I executed this command on our local SQL instance  and it worked as expected. I will try it again be be it is just a Syntax error. I wrote the Statement by Hand so maybe thats why it is invalid Syntax

SELECT *
  FROM (VALUES (1,2)
             , (3,4)
       ) t1 (c1, c2)

This is where I got it from it is valid SQL Server Statement 

https://modern-sql.com/de/anwendung/select-ohne-from

**Comment by PawelGerr** [comment] 2019-08-08 22:26
Interessting idea for JOIN with smaller collections.
The current implementation of EF requires the type (to join with) to be registered in `OnModelCreating`, i.e. something like
```
class MyClass
{ 
    string FsymId
    string FeItem
    DateTime FeFpEnd
}

void OnModelCreating(ModelBuilder builder)
{
    modelBuilder.Query<MyClass>();
}
```
After that we need a custom method/expression to generate the SQL.
```
IQueryable<MyClass> keysQuery = ctx.CreateMagicallyQueryableFrom(keys);
```
Now, we could join with the `keysQuery`.

Don't know if it helps in your use case. But I'm usually working with big collection having hundreds or thousands or records so I'm using `SqlBulkCopy` to [insert some data into temp tables](https://dev.azure.com/pawelgerr/Thinktecture.EntityFrameworkCore/_wiki/wikis/Thinktecture.EntityFrameworkCore.wiki?pagePath=%2FPerformance%2FBulk%252DInsert%20(into%20real%252D%20and%20%20temp%252Dtables)&wikiVersion=GBwikiMaster&pageId=2) then I use this temp table for joins. It looks like
```
// config
void OnModelCreating(ModelBuilder modelBuilder)
{
   modelBuilder.ConfigureTempTableEntity<MyClass>();
}

// usage
IEnumerable<MyClass> keys = ...;

using(ITempTableQuery<MyClass> tempTableQuery = await ctx.BulkInsertIntoTempTableAsync(keys))
{
    IQueryable<MyClass> keysQuery = tempTableQuery.Query;
   // join with keysQuery the usual way
}
```

**Comment by roji** [comment] 2023-06-13 09:59
Duplicate of #30426

**Closed by roji** 2023-06-13 09:59 UTC
Labels: customer-reported
