### ISSUE TITLE
EF emitting wrong Sql on Union join

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#6475] opened 2016-09-05 08:14 UTC
The following code is intended to return a collection of teachers and students, according to the supplied filter criteria.  For brevity I am omitting "if" clauses that were not run in the error case:

```
        public ICollection<User> GetUsersMatchingCriteria(UserSearchCriteria criteria)
        {
            var now = DateTime.UtcNow;
            var studentClasses =
                DbContext.StudentClassCrossReferences
                         .Where(sc => sc.StartDate <= now && sc.EndDate > now);
            var teacherClasses =
                 DbContext.TeacherClassCrossReferences
                         .Where(tc => tc.StartDate <= now && tc.EndDate > now);

            if (criteria.UserGroupId.HasValue)
            {
                studentClasses = studentClasses.Where(sc => sc.Class.UserGroupId == criteria.UserGroupId);
                teacherClasses = teacherClasses.Where(tc => tc.Class.UserGroupId == criteria.UserGroupId);
            }

            var users = studentClasses.Select(sc => sc.Student.User)
                                      .Union(teacherClasses.Select(tc => tc.Teacher.User));

            if (criteria.MaxCreateDate.HasValue)
            {
                users = users.Where(u => u.CreatedDateTime <= criteria.MaxCreateDate.Value);
            }

            return users.ToList();
        }
```

In the error case, the criteria included a `UserGroupId` and a `MaxCreateDate`.  The first Sql query executed was:

```
exec sp_executesql N'SELECT [sc.Student.User].[UserId], [sc.Student.User].[CreatedDateTime], [sc.Student.User].[LastLoginDate], [sc.Student.User].[Locked], [sc.Student.User].[LoginAttempts], [sc.Student.User].[Password], [sc.Student.User].[PasswordChangeRequired], [sc.Student.User].[UserTypeId], [sc.Student.User].[Username], [sc.Class].[CreatedDateTime]
FROM [dbo].[StudentClassCrossReference] AS [sc]
INNER JOIN [dbo].[Student] AS [sc.Student] ON [sc].[StudentId] = [sc.Student].[StudentId]
INNER JOIN [dbo].[User] AS [sc.Student.User] ON [sc.Student].[UserId] = [sc.Student.User].[UserId]
INNER JOIN [dbo].[Class] AS [sc.Class] ON [sc].[ClassId] = [sc.Class].[ClassId]
WHERE (([sc].[StartDate] <= @__now_0) AND ([sc].[EndDate] > @__now_1)) AND ([sc.Class].[UserGroupId] = @__criteria_UserGroupId_2)'
,N'@__now_0 datetime2(7),@__now_1 datetime2(7),@__criteria_UserGroupId_2 uniqueidentifier'
,@__now_0='2016-09-05 08:00:18.5630882',@__now_1='2016-09-05 08:00:18.5630882',@__criteria_UserGroupId_2='54EF0137-454D-4FE8-B4ED-08D3D562A93D'
```

The notable part is that it's including `[sc.Class].[CreatedDateTime]`, which is not in the `Class` model, and needless to say, not in the DB either, so it throws a SqlException "Invalid column name 'CreatedDateTime'".

I will attach the model classes for User, Student, Teacher and Class and the intersection tables.

**Comment by shaulbehr** [comment] 2016-09-05 08:16
Models attached




[Models.zip](https://github.com/aspnet/EntityFramework/files/454607/Models.zip)

**Comment by shaulbehr** [comment] 2016-09-05 08:32
FYI, it's the "Union" that messes things up.  I commented out the "Union" join and the query worked.  Of course, it gives the wrong results now...

**Comment by smitpatel** [comment] 2016-09-30 19:04
@shaulbehr - Can you share a standalone repro for this? I am not able to reproduce this.

**Comment by maumar** [comment] 2016-10-05 22:22
Closing as no repro.

**Closed by maumar** 2016-10-05 22:22 UTC
Labels: closed-could-not-reproduce
