### ISSUE TITLE
Can not save data when it has a primary key values 0

### ISSUE THREAD

**Issue by zmqcherish** [dotnet/efcore#10382] opened 2017-11-23 01:27 UTC
### Expected behavior
Using db(DbContext) .Add func to add a data when it has a primary key values 0, and then execute the db.SaveChanges(). After it, just read the data out, the primary key has be changed to value 1.

### Steps to reproduce
here is the demo code in github: [code](https://github.com/zmqcherish/EFCoreBug)
1. create a dotnet core console project, and  add 'Microsoft.EntityFrameworkCore.Sqlite(2.0.1)' dll by NuGet

2. create a data.db file with a table named 'Users'. It has a primary key named 'Id', and a simple field name 'Id1'. below show the sql:
`CREATE TABLE "Users" (
"Id"  INTEGER NOT NULL,
"Id1"  INTEGER,
PRIMARY KEY ("Id")
);`

3. create a class named 'User' 
```c#
public class User
    {
        public int Id { get; set; }
        public int Id1 { get; set; }
    }
```
4. create a class named 'UserDataContext' 
```c#
public class UserDataContext: DbContext
    {
        public DbSet<User> Users { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Data Source=data.db");
        }
    }
```
5. In the main func:
```c#
static void Main(string[] args)
        {
            using (var db = new UserDataContext())
            {
                User user = new User() { Id = 0, Id1 = 0 };
                db.Users.Add(user);
                db.SaveChanges();
            }

            List<User> users = null;
            using (var db = new UserDataContext())
            {
                users = db.Users.ToList();
            }

            Console.WriteLine($"Id:{users[0].Id}");
            Console.WriteLine($"Id1:{users[0].Id1}");
            Console.ReadKey();
        }
```

6. run the project. It should output:
`Id:0
Id1:0
`
but it has wrong result:
`Id:1
Id1:0
`
7. debug the project, when run 'db.SaveChanges()' the user.Id be change to '-2147482647', and then store to the db file, it become 1.
![qq 20171123094827](https://user-images.githubusercontent.com/6880848/33156329-af8ab046-d033-11e7-9acc-fa9615dd87fa.jpg)

### Further technical details
EF Core version:  2.0.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 Build 1703 (15063.726)
IDE:  Visual Studio 2017

**Comment by smitpatel** [comment] 2017-11-23 01:31
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by zmqcherish** [comment] 2017-11-23 02:06
@smitpatel well i just update the issue.

**Comment by smitpatel** [comment] 2017-11-23 02:17
It is expected behavior.

Based on docs: https://sqlite.org/autoinc.html
When you define Integer primary key in database, it will get value automatically if none supplied.
From EF Core perspective, Id is int PK & by convention it is configured as auto-increment. When user provides explicit value for a property, we try to save it but in the absence of explicit value, we assume database is going to generate a value. Now the way we decide if user has specified explicit value is based on default for the type. For `int` type default value is 0. So when you try to add a record with Id=0, we assume you haven't given explicit value and it will be generated by database when saved. For tracking purposes we use values from int.Min range hence you see value of `-2147482647` Once you call SaveChanges, we don't send that column in Insert statement so SQLite generates a value and we read the value back and assign it to the property so you get Id=1.

Hope that explains why it is happening this way. If you make type `int?` (it will be still NOT NULL in the database because its PK) then `null` would be considered sentinel value and if you specify any value other than null, we will save it to database.

**Comment by ralmsdeveloper** [comment] 2017-11-23 02:26
@smitpatel, it could solve this, with the setting below, by setting the _**OnModelCreating**_.

```csharp
public class UserDataContext : DbContext
{
    public DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Data Source=data.db");
    }

    protected override void OnModelCreating(ModelBuilder model)
    { 
        model.Entity<User>()
            .Property(p => p.Id)
            .ValueGeneratedNever();

        base.OnModelCreating(model);
    }
}
```

**Comment by zmqcherish** [comment] 2017-11-23 08:30
@ralmsdeveloper @smitpatel  thank you very much. And @ralmsdeveloper method work well.

**Comment by joetherod** [comment] 2019-03-22 14:14
Worse thing when trying to port an existing app and you run into these behaviro changes. There should be a global configuration for this. So much time wasted dealing with all over the place in core.

**Comment by totpero** [comment] 2019-06-18 21:51
I create little "hack" to **bypass 0 PK value restriction** after I reverse engineering the [EF Core][1] code and I find [this][2] line of code.

Here is my snipped extension code:

    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Internal;
    using Microsoft.EntityFrameworkCore.Metadata.Internal;
    
    namespace EntityFrameworkCore.CustomMigration
    {
        public static class CustomModelBuilder
        {
            public static bool IsSignedInteger(this Type type)
               => type == typeof(int)
                  || type == typeof(long)
                  || type == typeof(short)
                  || type == typeof(sbyte);
    
            public static void Seed<T>(this ModelBuilder modelBuilder, IEnumerable<T> data) where T : class
            {
                var entnty = modelBuilder.Entity<T>();
    
                var pk = entnty.Metadata
                    .GetProperties()
                    .FirstOrDefault(property => 
                        property.RequiresValueGenerator() 
                        && property.IsPrimaryKey()
                        && property.ClrType.IsSignedInteger()
                        && property.ClrType.IsDefaultValue(0)
                    );
                if (pk != null)
                {
                    entnty.Property(pk.Name).ValueGeneratedNever();
                    entnty.HasData(data);
                    entnty.Property(pk.Name).UseSqlServerIdentityColumn();
                }
                else
                {
                    entnty.HasData(data);
                }          
            }
        }
    }


And you can use it like this in `OnModelCreating` method:

    protected override void OnModelCreating(ModelBuilder builder)
    {
    	base.OnModelCreating(builder);
    
    	builder.Seed(new List<Tenant> {
    		new Tenant() {TenantID = 0 , Name = string.Empty},
    		new Tenant() {TenantID = 1 , Name = "test"}
    		//....
    		);
    		
    	//....
    }

  [1]: https://github.com/aspnet/EntityFrameworkCore
  [2]: https://github.com/aspnet/EntityFrameworkCore/blob/0ba65b8dfc9294b714b6855eef340bdfbfb8d64c/src/EFCore/Infrastructure/ModelValidator.cs#L884

**Comment by emre1702** [comment] 2019-06-22 23:52
@totpero I tried your code and had a bug for like 3 hours, where a normal insert always tried to insert the Id (with value 0), too.
You are deactivating the value generating.

**Comment by nthdeveloper** [comment] 2020-03-03 14:10
If you are using attributes, adding the DatabaseGenerated also solves this problem.

       ```
 [Key]
 [DatabaseGenerated(DatabaseGeneratedOption.None)]       
 public int Id { get; set; }
```

**Closed** 2022-10-16 12:00 UTC
Labels: closed-by-design
