### ISSUE TITLE
Issue running a linq contains statement on a nullable type

### ISSUE THREAD

**Issue by StormOli** [dotnet/efcore#6483] opened 2016-09-07 14:33 UTC
The following code where members is an `IQueryable<Member>` and `searchModel.SectionIDs` is a `List<int>`

``` C#
members = members.Where(p => searchModel.SectionIDs.Contains(p.SectionId));
```

Results in the correct SQL being produced if "SectionID" is a Non Nullable Int.  However if SectionID is nullable and I change the code to p.SectionID.Value then I get the warning 
the linq expression contains() could not be translated and will be evaluated locally
and thus all records are retrieved from the database.

Is there another way to write the linq query that will fix the problem?

-------EDIT------
I should note that the sql is generated correctly if the contains list is of type List<int?> - I can convert the list<int> into this even if I can't change the original list to fix the issue but wondering if this shouldn't be resolved another way? 

EF Core version: 1.0.0
Operating system: Win10
Visual Studio version: 2015

**Comment by smitpatel** [comment] 2020-03-15 20:27
The cause of error as `Nullable<int>.Value` not getting translated to server. The translation is added a long time ago. (but not as long as when this issue was filed). Closing as fixed in 3.1

**Closed by smitpatel** 2020-03-15 20:27 UTC
Labels: area-query, type-enhancement
