### ISSUE TITLE
No possible to load related Data per level with .Include and .ThenInclude

### ISSUE THREAD

**Issue by rmunozramirez** [dotnet/efcore#6711] opened 2016-10-07 13:54 UTC
I am building a project with the following structure:

```
- Organization1:
  --Contact1:
    ---Phones:
        ----phone1
        ----phone2 
    ---Addresses: 
        ----address1
        ----address2 
    ---Bankdata: 
        ----bankdata1
        ----bankdata2
  --Contact2:
    ---Phones: phone1, phone2
    --- Addresses: address1, address2
    ---Bankdata: bankdata1, bankdata2

  --Contact3:
...
-Organization2:...and so on...
```
### The issue

**.Include** and **.ThenInclude**, include just ONE item per level building a lineal descendance of just one Item per level. 

The following method does not compile 

```
var organizations = _context.Organizations
                    .OrderBy(o => o.organizationName)
                    .Include(v => v.Contacts)
                                        .ThenInclude(v => v.Addresses)
                                        .ThenInclude(v => v.Bankdatas)
                                        .ThenInclude(v => v.Phones)
                    .ToList();
```

**The question:**
Is not possible to get more than one Item per level
### Further technical details

EF Core version: 1.0.0
Visual Studio version: VS 2015

**Comment by smitpatel** [comment] 2016-10-07 13:59
dupe of #4490
At present you need to start at the top of tree again.
The query needs to be written like this
```c#
var organizations = _context.Organizations
                    .OrderBy(o => o.organizationName)
                    .Include(v => v.Contacts).ThenInclude(v => v.Addresses)
                    .Include(v => v.Contacts).ThenInclude(v => v.Bankdatas)
                    .Include(v => v.Contacts).ThenInclude(v => v.Phones)
                    .ToList();
```

**Closed** 2022-10-16 10:37 UTC
Labels: closed-duplicate
