### ISSUE TITLE
Inheritance Composition interfering in Raw SQL

### ISSUE THREAD

**Issue by SuricateCan** [dotnet/efcore#21315] opened 2020-06-17 21:07 UTC
Using `context.Somethings.FromRawSql("dbo.myProc").AsEnumerable()` works for simple entities (without inheritance).
However, when my class has inheritance, EF tries to compose the discriminator over it, which throws an exception:

`System.InvalidOperationException: FromSqlRaw or FromSqlInterpolated was called with non-composable SQL and with a query composing over it. Consider calling 'AsEnumerable' after the FromSqlRaw or FromSqlInterpolated method to perform the composition on the client side.`

Obviously, the `AsEnumerable` is there and still the error persist.
What happens is that the composition happens automatically, and there is nothing I can do about it, no workaround.

EF ties to do this to my call:

```SQL
SELECT [dbo].[Field1]
FROM (
    EXEC dbo.myProc -- as expected, this composition does not work
) [r]
WHERE [r].Discriminator IN ('WhateverTheDiscriminatorIs')
```

To keep using the procedure, I had to undo de inheritance.

### Steps to reproduce

``` C#
class MyBase {
  public int Id { get; set; }
}
class MyDerived {
  public string Foo { get; set; }
}
class MyContext : DbContext {
  public DbSet<MyBase> Items { get; set; }
  protected override void OnModelCreating(ModelBuilder modelBuilder){
    modelBuilder.Entity<MyBase>();
    modelBuilder.Entity<MyDerived>().HasBaseType<MyBase>();
  }
}

class Program {
  public static void Main(string args[]){
    using var db = new MyContext();
    //this line will throw
    var items = db.Items.FromRawSql("dbo.MySimpleProcThatReturnsEverything").AsEnumerable().ToArray();
    ...
  }
}
```

```
Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type 'MyContext'.
System.InvalidOperationException: FromSqlRaw or FromSqlInterpolated was called with non-composable SQL and with a query composing over it. Consider calling `AsEnumerable` after the FromSqlRaw or FromSqlInterpolated method to perform the composition on the client side.
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitFromSql(FromSqlExpression fromSqlExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.<VisitSelect>b__18_1(TableExpressionBase e)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GenerateList[T](IReadOnlyList`1 items, Action`1 generationAction, Action`1 joinAction)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GetCommand(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalCommandCache.GetRelationalCommand(IReadOnlyDictionary`2 parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()

System.InvalidOperationException: FromSqlRaw or FromSqlInterpolated was called with non-composable SQL and with a query composing over it. Consider calling `AsEnumerable` after the FromSqlRaw or FromSqlInterpolated method to perform the composition on the client side.
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitFromSql(FromSqlExpression fromSqlExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.<VisitSelect>b__18_1(TableExpressionBase e)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GenerateList[T](IReadOnlyList`1 items, Action`1 generationAction, Action`1 joinAction)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GetCommand(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalCommandCache.GetRelationalCommand(IReadOnlyDictionary`2 parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.Relational.dll
```

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer 3.1.0
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.6

**Comment by smitpatel** [comment] 2020-06-17 21:51
Duplicate of #18232

**Closed** 2022-10-16 18:30 UTC
Labels: closed-duplicate, customer-reported
