### ISSUE TITLE
Navigation properties on other entities are not removed when OnDelete Restrict

### ISSUE THREAD

**Issue by rotem925** [dotnet/efcore#13478] opened 2018-10-03 07:26 UTC
It seems that when using DeleteBehaviour.Restrict and removing an entity from the navigation property - the navigation property gets deleted from the database and from the removed collection after SaveChanges, BUT it still exists in other entities that have a relation to that deleted entity.
However, this issue does not happen if the DeleteBehaviour.Cascade is specified. 
This seems to be a bug, the DbContext probably does not refresh the other entities.

On my example, I have a many-to-many scenario, where I delete a related navigation property entity and try to access it through other entities in my tests.

These are my entities:
```csharp
public class SchoolStudent
{
    public virtual int Id { get; set; }
    public virtual string Name { get; set; }
    public virtual School School { get; set; }
    
    public virtual ICollection<SchoolStudentSchoolClass> Classes { get; set; }
}

public class SchoolClass
{
    public virtual int Id { get; set; }
    public virtual string Name { get; set; }
    public virtual School School { get; set; }
    public virtual ICollection<SchoolStudentSchoolClass> Students { get; set; }
}

public class SchoolStudentSchoolClass
{
    public virtual int SchoolStudentId { get; set; }
    public virtual SchoolStudent SchoolStudent { get; set; }
    public virtual int SchoolClassId { get; set; }
    public virtual SchoolClass SchoolClass { get; set; }
}
```
Here is a test example:
```csharp
var userId=1;
var classId=1;

//removing the class navigation property
var student = _dbContext.Set<SchoolStudent>().First(a => a.Id == userId);
student.Classes.Remove(student.Classes.First(a => a.SchoolClassId == classId));
_session.SaveChanges();

//accessing the other entity (in this case, the class entity)
var student =  _dbContext.Set<SchoolClass>().First(a => a.Id == classId).Students.FirstOrDefault(a => a.Id == userId);
Assert.IsNull(student);// this is somehow not null, in the database it is deleted of course. 
```

### Further technical details
EF Core version:  2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Windows 10
IDE:  Visual Studio 2017 15.8.2

**Comment by ajcvickers** [comment] 2018-10-03 15:55
Duplicate of #12114

**Closed** 2022-10-16 13:33 UTC
Labels: customer-reported
