### ISSUE TITLE
Remove-Migration does not lead to an exception if migration has already been rolled out to database

### ISSUE THREAD

**Issue by ManuelHaas** [dotnet/efcore#14850] opened 2019-02-27 13:31 UTC
Since updating from 2.1 to 2.2 if I call `Remove-Migration` via Package Manager Console it does not lead to an exception if migration has already been rolled out to the connected database. So the migration gets removed and afterwards I cannot remove it from database anymore with `Update-Database`. 
Calling `Update-Database` leads to: "No migrations were applied. The database is already up to date." Of course because the migration in Visual Studio is no longer available. So I have to drop and recreate the database again.

### Further technical details
EF Core version: 2.2.0
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Win10
IDE: (e.g. Visual Studio 2017 15.9.7)

**Comment by ajcvickers** [comment] 2019-03-04 21:45
@ManuelHaas I have not been able to reproduce this using the latest 2.2.2 packages. This is what I see:
```Powershell
PM> add-migration One
To undo this action, use Remove-Migration.
PM> update-database
Applying migration '20190304214414_One'.
Done.
PM> remove-migration
The migration '20190304214414_One' has already been applied to the database. Revert it and try again. If the migration has been applied to other databases, consider reverting its changes using a new migration.
PM> 
```
Can you please post a runnable project/solution that demonstrates the behavior you are seeing?

**Comment by ManuelHaas** [comment] 2019-03-07 06:59
Das ist schräg. I will try to create a sample the next days.

**Comment by ajcvickers** [comment] 2019-03-15 16:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:54 UTC
Labels: closed-could-not-reproduce, customer-reported
