### ISSUE TITLE
FirstOrDefaultAsync and binary data

### ISSUE THREAD

**Issue by TeamLucky7** [dotnet/efcore#23521] opened 2020-11-28 23:09 UTC
Hi,

In my project files are stored in database (SQL Server). A column, that stores content of the files, is type of varbinary(MAX).

C# class that represents table with files is following
```C#
internal class ApplicationFile
{
    public int ApplicationFileId { get; set; }
    public int ApplicationVersionId { get; set; }
    public virtual ApplicationVersion ApplicationVersion { get; set; }
    public string Name { get; set; }
    public byte[] Content { get; set; }
}
```
I use following code to fetch data with content of the file:
```C#
ApplicationVersion latestApplicationVersionEntity = await Context.ApplicationVersions.FirstAsync(x => x.ApplicationId == applicationEntity.ApplicationId && x.ApplicationVersionId == applicationEntity.CurrentVersionId);
ApplicationFile applicationFileEntity = await Context.ApplicationFiles.FirstOrDefaultAsync(x => x.ApplicationVersionId == latestApplicationVersionEntity.ApplicationVersionId);
```

The code works fine when file is small (like 100kb), but when the content of the file is bigger than 50MB, then the second line of the code never ends (I waited for result more than 1 hour and I stopped after that time). One core of CPU works with full power all the time, but the execution of the line is endless.

When I replace
```C#
ApplicationFile applicationFileEntity = await Context.ApplicationFiles.FirstOrDefaultAsync(x => x.ApplicationVersionId == latestApplicationVersionEntity.ApplicationVersionId);
```
with
```C#
ApplicationFile applicationFileEntity = Context.ApplicationFiles.FirstOrDefault(x => x.ApplicationVersionId == latestApplicationVersionEntity.ApplicationVersionId);
```
then execution takes less than some seconds.

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.2

**Comment by roji** [comment] 2020-11-29 05:35
Duplicate of https://github.com/dotnet/SqlClient/issues/593

**Comment by roji** [comment] 2020-11-29 05:35
This is an issue with SqlClient rather than with EF Core. As you've noticed, the recommended workaround is currently to use synchronous I/O.

**Closed** 2022-10-16 19:12 UTC
Labels: closed-external, customer-reported
