### ISSUE TITLE
5.0 RC1 OwnsOne Separate Table: NullReferenceException when translating a query

### ISSUE THREAD

**Issue by bperc2** [dotnet/efcore#22581] opened 2020-09-17 16:46 UTC
I Updated an existing project from 3.1 to 5.0 RC1 and, many of my queries we producing NullReferenceExceptions at the point where they were being translated/resolved. All the broken queries involved a parent record and an OwnsOne child that is stored in a separate table. 

I was then able to reproduce this in a small sample project using the classes and configurations from the Owned Entity Types documentation.

### Exception: 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.GetPropertyExpressionsFromJoinedTable(IEntityType entityType, ITableBase table, TableExpressionBase tableExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.TryExpand(Expression source, MemberIdentity member)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.Expand(SelectExpression selectExpression, Expression lambdaBody)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.ExpandWeakEntities(SelectExpression selectExpression, Expression lambdaBody)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EfCore5RC1OwnedBug.Program.Main(String[] args) in C:\Users\bperc2\source\repos\EfCore5RC1OwnedBug\EfCore5RC1OwnedBug\Program.cs:line 80
```

### Steps to reproduce

``` C#
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace EfCore5RC1OwnedBug
{
    public class Program
    {
        [Owned]
        public class StreetAddress
        {
            public string Street { get; set; }
            public string City { get; set; }
        }

        public class OrderDetails
        {
            public DetailedOrder Order { get; set; }
            public StreetAddress BillingAddress { get; set; }
            public StreetAddress ShippingAddress { get; set; }
        }

        public class DetailedOrder
        {
            public int Id { get; set; }
            public OrderDetails OrderDetails { get; set; }
            public OrderStatus Status { get; set; }
        }

        public enum OrderStatus
        {
            Pending,
            Shipped
        }


        public class EfBugDbContext : DbContext
        {
            public DbSet<DetailedOrder> DetailedOrders { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder options)
            {
                options
                    .UseSqlServer(
                        "Data Source=localhost;Initial Catalog=TestDB_EfBug_TPT_OwnedType;Persist Security Info=True;User ID=User;Password=Pass",
                        providerOptions => providerOptions.EnableRetryOnFailure())
                    .EnableDetailedErrors()
                    .EnableSensitiveDataLogging();
            }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<DetailedOrder>().OwnsOne(p => p.OrderDetails, od =>
                {
                    // Everything works if this is omitted.
                    od.ToTable("OrderDetails");

                    od.WithOwner(d => d.Order);
                    od.Navigation(d => d.Order).UsePropertyAccessMode(PropertyAccessMode.Property);
                    od.OwnsOne(c => c.BillingAddress);
                    od.OwnsOne(c => c.ShippingAddress);
                });
            }
        }


        static void Main(string[] args)
        {
            try
            {
                using (EfBugDbContext db = new EfBugDbContext() )
                {
                    db.Database.EnsureCreated();
                }

                using (EfBugDbContext db = new EfBugDbContext() )
                {
                    // Exception occurs here
                    var allOrders = db.DetailedOrders.ToList();

                    Console.WriteLine("OK");
                }
            }
            catch (Exception ex)
            {
                var exceptionString = ex.ToString();
                Console.WriteLine(ex.ToString());
            }

            Console.ReadLine();
        }
    }
}

```

``` C#
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0-rc.1.20451.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.0-rc.1.20451.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0-rc.1.20451.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.0-rc.1.20451.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

### Further technical details

EF Core version: 5.0.0-rc.1.20451.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.2 & 16.8.0 Preview 3.0

**Comment by smitpatel** [comment] 2020-09-17 16:58
Works in 5.0.0-rc.2.20464.2

Duplicate of https://github.com/dotnet/efcore/issues/22340

**Closed** 2022-10-16 18:41 UTC
Labels: closed-duplicate, customer-reported
