### ISSUE TITLE
Guid properties cause exception on physical iOS devices

### ISSUE THREAD

**Issue by failwyn** [dotnet/efcore#11035] opened 2018-02-22 19:56 UTC
Guid properties with multiple other properties cause an exception on physical iOS devices

System.ExecutionEngineException: Attempting to JIT compile method `(wrapper runtime-invoke) <Module>:runtime_invoke_void__this___Guid_Guid_Guid_Guid (object,intptr,intptr,intptr)` while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.

```
public class GuidModel
{
  [Key]
  public Guid Id { get; set; }
  public Guid OtherId { get; set; }
  public Guid AnotherId { get; set; }
  public Guid MoreId { get; set; }
}
```

If you have 2 Guid properties, you can have a maximum of 6 propterties total, 3 Guid Properties you can have a maximum of 5 properties, and with 4 Guid properties, you can only have 4 properties.

```
Unhandled Exception:
System.ExecutionEngineException: Attempting to JIT compile method '(wrapper runtime-invoke) <Module>:runtime_invoke_void__this___Guid_Guid_Guid_Guid (object,intptr,intptr,intptr)' while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.

  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:661 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/mcs/class/referencesource/mscorlib/system/r
untime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Exception source) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:156 
  at System.Linq.Expressions.Interpreter.ExceptionHelpers.UnwrapAndRethrow (System.Reflection.TargetInvocationException exception) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/Utilities.cs:172 
  at System.Linq.Expressions.Interpreter.NewInstruction.Run (System.Linq.Expressions.Interpreter.InterpretedFrame frame) [0x00026] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/NewInstruction.cs:39 
  at System.Linq.Expressions.Interpreter.Interpreter.Run (System.Linq
.Expressions.Interpreter.InterpretedFrame frame) [0x00015] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/Interpreter.cs:63 
  at System.Linq.Expressions.Interpreter.LightLambda.Run1[T0,TRet] (T0 arg0) [0x0001c] in <8bc31b0df50a4d32b3f1d5af764165ad>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry+OriginalValues..ctor (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry) [0x00001] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\OriginalValues.cs:20 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.EnsureOriginalValues () [0x00011] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\InternalEntityEntry.cs:708 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe (Microsoft.EntityFrameworkCore.ChangeTracking.I
nternal.InternalEntityEntry entry) [0x00013] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\InternalEntityEntrySubscriber.cs:31 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry) [0x000b6] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\StateManager.cs:471 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState (Microsoft.EntityFrameworkCore.EntityState oldState, Microsoft.EntityFrameworkCore.EntityState newState, System.Boolean acceptChanges) [0x001d2] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\InternalEntityEntry.cs:228 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState (Microsoft.EntityFrameworkCore.EntityState entityState, System.Boolean acceptChanges, System.Boolean forceStateWhenUnknownKey) [0x0003a] in W:\Libraries\Enti
tyFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\InternalEntityEntry.cs:86 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction (Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntryGraphNode node) [0x00033] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\EntityGraphAttacher.cs:65 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph (Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntryGraphNode node, System.Func`2[T,TResult] handleNode) [0x00001] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\EntityEntryGraphIterator.cs:25 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry rootEntry, Microsoft.EntityFrameworkCore.EntityState entityState, System.Boolean forceStateWhenUnknownKey) [0x00000] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\ChangeT
racking\Internal\EntityGraphAttacher.cs:31 
  at Microsoft.EntityFrameworkCore.DbContext.SetEntityState (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry, Microsoft.EntityFrameworkCore.EntityState entityState) [0x0000f] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\DbContext.cs:649 
  at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity] (TEntity entity, Microsoft.EntityFrameworkCore.EntityState entityState) [0x00010] in <024b24e444ca46babc14cddedff156b3>:0 
  at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity] (TEntity entity) [0x00014] in <024b24e444ca46babc14cddedff156b3>:0 
  at XamarinApp.App..ctor (Autofac.Core.IModule[] platformSpecificModules) [0x00042] in W:\Xamarin\KaterraLabor\csx-xamarin\CSX\CSX\App.xaml.cs:54 
  at XamarinApp.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00022] in W:\Xamarin\KaterraLabor\csx-xamarin\CSX\CSX.iOS\AppDelegate.cs:31 
  at (wrapper managed-to-native) UIKit.UIApplicat
ion:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/src/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/src/UIKit/UIApplication.cs:63 
  at XamarinApp.iOS.Application.Main (System.String[] args) [0x00001] in W:\Xamarin\KaterraLabor\csx-xamarin\CSX\CSX.iOS\Main.cs:17 
2018-02-22 14:48:32.748 CSX.iOS[910:364189] Unhandled managed exception:
Attempting to JIT compile method '(wrapper runtime-invoke) <Module>:runtime_invoke_void__this___Guid_Guid_Guid_Guid (object,intptr,intptr,intptr)' while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.
 (System.ExecutionEngineException)
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:661 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/mcs/class/referencesource/mscorlib/
system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Exception source) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:156 
  at System.Linq.Expressions.Interpreter.ExceptionHelpers.UnwrapAndRethrow (System.Reflection.TargetInvocationException exception) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/Utilities.cs:172 
  at System.Linq.Expressions.Interpreter.NewInstruction.Run (System.Linq.Expressions.Interpreter.InterpretedFrame frame) [0x00026] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/NewInstruction.cs:39 
  at System.Linq.Expressions.Interpreter.Interpreter.Run (Sys
tem.Linq.Expressions.Interpreter.InterpretedFrame frame) [0x00015] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/Interpreter.cs:63 
  at System.Linq.Expressions.Interpreter.LightLambda.Run1[T0,TRet] (T0 arg0) [0x0001c] in <8bc31b0df50a4d32b3f1d5af764165ad>:0 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry+OriginalValues..ctor (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry) [0x00001] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\OriginalValues.cs:20 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.EnsureOriginalValues () [0x00011] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\InternalEntityEntry.cs:708 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe (Microsoft.EntityFrameworkCore.ChangeTr
acking.Internal.InternalEntityEntry entry) [0x00013] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\InternalEntityEntrySubscriber.cs:31 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry) [0x000b6] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\StateManager.cs:471 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState (Microsoft.EntityFrameworkCore.EntityState oldState, Microsoft.EntityFrameworkCore.EntityState newState, System.Boolean acceptChanges) [0x001d2] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\InternalEntityEntry.cs:228 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState (Microsoft.EntityFrameworkCore.EntityState entityState, System.Boolean acceptChanges, System.Boolean forceStateWhenUnknownKey) [0x0003a] in W:\Librar
ies\EntityFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\InternalEntityEntry.cs:86 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction (Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntryGraphNode node) [0x00033] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\EntityGraphAttacher.cs:65 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph (Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntryGraphNode node, System.Func`2[T,TResult] handleNode) [0x00001] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\ChangeTracking\Internal\EntityEntryGraphIterator.cs:25 
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry rootEntry, Microsoft.EntityFrameworkCore.EntityState entityState, System.Boolean forceStateWhenUnknownKey) [0x00000] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore
\ChangeTracking\Internal\EntityGraphAttacher.cs:31 
  at Microsoft.EntityFrameworkCore.DbContext.SetEntityState (Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry entry, Microsoft.EntityFrameworkCore.EntityState entityState) [0x0000f] in W:\Libraries\EntityFrameworkCore-dev\src\EFCore\DbContext.cs:649 
  at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity] (TEntity entity, Microsoft.EntityFrameworkCore.EntityState entityState) [0x00010] in <024b24e444ca46babc14cddedff156b3>:0 
  at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity] (TEntity entity) [0x00014] in <024b24e444ca46babc14cddedff156b3>:0 
  at XamarinApp.App..ctor (Autofac.Core.IModule[] platformSpecificModules) [0x00042] in W:\Xamarin\KaterraLabor\csx-xamarin\CSX\CSX\App.xaml.cs:54 
  at XamarinApp.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00022] in W:\Xamarin\KaterraLabor\csx-xamarin\CSX\CSX.iOS\AppDelegate.cs:31 
  at (wrapper managed-to-native) UIKit.UI
Application:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/src/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/src/UIKit/UIApplication.cs:63 
  at XamarinApp.iOS.Application.Main (System.String[] args) [0x00001] in W:\Xamarin\KaterraLabor\csx-xamarin\CSX\CSX.iOS\Main.cs:17 
```

### Further technical details
EF Core version: 2.0.1
Database Provider: SQLite
Operating system: Windows
IDE: Visual Studio 2017 15.5.7
Device: iPhone 7+

**Comment by ajcvickers** [comment] 2018-03-02 20:44
Duplicate of #9249

**Closed** 2022-10-16 12:10 UTC
