### ISSUE TITLE
Adding an -exclude option to db first scaffold

### ISSUE THREAD

**Issue by denious** [dotnet/efcore#17184] opened 2019-08-15 20:19 UTC
As described [in the docs](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding#specifying-tables), it is possible to limit generated models by specifying table names. Works great until you have 20 tables and want 18 of them!

So this is a feature request to add an -exclude option. :)
Thanks!

**Comment by smitpatel** [comment] 2019-08-15 20:20
Duplicate of #6182

**Comment by ErikEJ** [comment] 2019-08-16 11:35
@denious maybe EF Core Power Tools can help you?

**Closed** 2022-10-16 14:36 UTC
Labels: customer-reported
