### ISSUE TITLE
Scaffold-DbContext fails: System.InvalidOperationException: The key {'DocumentTypeId'} cannot be added to keyless type 'DocumentType (Dictionary<string, object>)'.

### ISSUE THREAD

**Issue by Degats** [dotnet/efcore#30448] opened 2023-03-09 15:39 UTC
I've searched for existing issues, but can only find similar references to code errors after the DbContext has been successfully generated.

In this case, Scaffold-DbContext doesn't get that far and fails before writing any generated code.

This is a vendor controlled database, so I am unable to change it.

> Note: Only EFCore errors like this, it works correctly on the same database in .NET Framework 4.8 using "ADO.NET Entity Data Model" -> "Code First from database".

Command (Package manager console in Visual Studio):

`PM> Scaffold-DbContext "Server=<server>;Database=test;Trusted_Connection=True;TrustServerCertificate=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Test`

## Repro Database

```SQL
CREATE TABLE [dbo].[DocumentType](
	[DocumentTypeID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Description] [nvarchar](200) NULL,
 CONSTRAINT [UQ_DocumentType_DocumentTypeID] UNIQUE CLUSTERED 
(
	[DocumentTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- ==========

CREATE TABLE [dbo].[DocumentRevision](
	[DocumentRevisionID] [int] IDENTITY(1,1) NOT NULL,
	[DocumentID] [int] NOT NULL,
	[DocumentTypeID] [int] NULL,
 CONSTRAINT [PK_DocumentRevision] PRIMARY KEY CLUSTERED 
(
	[DocumentID] ASC,
	[DocumentRevisionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_DocumentRevision_DocumentRevisionID] UNIQUE NONCLUSTERED 
(
	[DocumentRevisionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[DocumentRevision]  WITH CHECK ADD  CONSTRAINT [FK_DocumentRevision_DocumentType] FOREIGN KEY([DocumentTypeID])
REFERENCES [dbo].[DocumentType] ([DocumentTypeID])
GO

ALTER TABLE [dbo].[DocumentRevision] CHECK CONSTRAINT [FK_DocumentRevision_DocumentType]
GO
```

## Stack trace

```
System.InvalidOperationException: The key {'DocumentTypeId'} cannot be added to keyless type 'DocumentType (Dictionary<string, object>)'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddKey(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType.AddKey(IReadOnlyList`1 properties)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKey(ModelBuilder modelBuilder, DatabaseForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKeys(ModelBuilder modelBuilder, IList`1 foreignKeys)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The key {'DocumentTypeId'} cannot be added to keyless type 'DocumentType (Dictionary<string, object>)'.
```

## Verbose output

```
PM> Scaffold-DbContext "Server=redacted;Database=test;Trusted_Connection=True;TrustServerCertificate=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Test -verbose
Using project 'Test'.
Using startup project 'Test'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\projects\Test\Test\bin\Debug\net6.0\Test.deps.json --additionalprobingpath C:\Users\redacted\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --runtimeconfig C:\projects\Test\Test\bin\Debug\net6.0\Test.runtimeconfig.json C:\Users\redacted\.nuget\packages\microsoft.entityframeworkcore.tools\7.0.3\tools\netcoreapp2.0\any\ef.dll dbcontext scaffold Server=redacted;Database=test;Trusted_Connection=True;TrustServerCertificate=True; Microsoft.EntityFrameworkCore.SqlServer --json --output-dir Test --verbose --no-color --prefix-output --assembly C:\projects\Test\Test\bin\Debug\net6.0\Test.dll --project C:\projects\Test\Test\Test.csproj --startup-assembly C:\projects\Test\Test\bin\Debug\net6.0\Test.dll --startup-project C:\projects\Test\Test\Test.csproj --project-dir C:\projects\Test\Test\ --language C# --configuration Debug --working-dir C:\projects\Test --root-namespace Test --nullable
Using assembly 'Test'.
Using startup assembly 'Test'.
Using application base 'C:\projects\Test\Test\bin\Debug\net6.0'.
Using working directory 'C:\projects\Test\Test'.
Using root namespace 'Test'.
Using project directory 'C:\projects\Test\Test\'.
Remaining arguments: .
Using configuration file 'C:\projects\Test\Test\bin\Debug\net6.0\Test.dll.config'.
Finding design-time services referenced by assembly 'Test'...
Finding design-time services referenced by assembly 'Test'...
No referenced design-time services were found.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding IDesignTimeServices implementations in assembly 'Test'...
No design-time services were found.
To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
Found default schema 'dbo'.
Found type alias with name 'sys.sysname' which maps to underlying data type nvarchar(128).
Found table with name 'dbo.DocumentRevision'.
Found table with name 'dbo.DocumentType'.
Found column with table: dbo.DocumentRevision, column name: DocumentRevisionID, ordinal: 1, data type: sys.int, maximum length: 4, precision: 10, scale: 0, nullable: False, identity: True, default value: (null), computed value: (null), computed value is stored: False.
Found column with table: dbo.DocumentRevision, column name: DocumentID, ordinal: 2, data type: sys.int, maximum length: 4, precision: 10, scale: 0, nullable: False, identity: False, default value: (null), computed value: (null), computed value is stored: False.
Found column with table: dbo.DocumentRevision, column name: DocumentTypeID, ordinal: 3, data type: sys.int, maximum length: 4, precision: 10, scale: 0, nullable: True, identity: False, default value: (null), computed value: (null), computed value is stored: False.
Found column with table: dbo.DocumentType, column name: DocumentTypeID, ordinal: 1, data type: sys.int, maximum length: 4, precision: 10, scale: 0, nullable: False, identity: True, default value: (null), computed value: (null), computed value is stored: False.
Found column with table: dbo.DocumentType, column name: Name, ordinal: 2, data type: sys.nvarchar, maximum length: 200, precision: 0, scale: 0, nullable: False, identity: False, default value: (null), computed value: (null), computed value is stored: False.
Found column with table: dbo.DocumentType, column name: Description, ordinal: 3, data type: sys.nvarchar, maximum length: 400, precision: 0, scale: 0, nullable: True, identity: False, default value: (null), computed value: (null), computed value is stored: False.
Found primary key on table 'PK_DocumentRevision' with name 'dbo.DocumentRevision'.
Found unique constraint on table 'UQ_DocumentRevision_DocumentRevisionID' with name 'dbo.DocumentRevision'.
Found unique constraint on table 'UQ_DocumentType_DocumentTypeID' with name 'dbo.DocumentType'.
Found foreign key on table 'FK_DocumentRevision_DocumentType' with name 'dbo.DocumentRevision', principal table 'dbo.DocumentType', delete action NO_ACTION.
System.InvalidOperationException: The key {'DocumentTypeId'} cannot be added to keyless type 'DocumentType (Dictionary<string, object>)'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddKey(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType.AddKey(IReadOnlyList`1 properties)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKey(ModelBuilder modelBuilder, DatabaseForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKeys(ModelBuilder modelBuilder, IList`1 foreignKeys)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The key {'DocumentTypeId'} cannot be added to keyless type 'DocumentType (Dictionary<string, object>)'.
```

## Version information

* EF Core version: 7.0.3 (via nuget)
* Database provider: Microsoft.EntityFrameworkCore.SqlServer
* Target framework: .NET 6.0
* Operating system: Win11 22621.1265
* IDE: Visual Studio 2022 17.5.1
* SQL Server 2019, DB Compatibility level 2019 (150)

**Comment by ajcvickers** [comment] 2023-03-12 20:31
Note for triage: in this case, the `DocumentType` table has no keys defined, but the `DocumentRevision` nevertheless has a foreign key constraint to the keyless table. So I think this is a duplicate of #19918.

**Closed** 2023-03-16 14:16 UTC
Labels: closed-duplicate, customer-reported
