### ISSUE TITLE
Garbled code appears when I save a Chinese character.

### ISSUE THREAD

**Issue by mematrix** [dotnet/efcore#3471] opened 2015-10-18 13:19 UTC
I'm using MVC6 and EF7 in a mac with `mono` environment. When I store a **Chinese character** to the database(using `sqlite`), **garbled code** will appear. 

I have checked the data sent from the client, which is stored in a `String` type, and it can be displayed correctly (_I tried to sent data to the client directly, and it displayed correctly_) . But when I stored it to the database and then read it from database, garbled code appears. 

Does anyone know why?

**Comment by natemcmaster** [comment] 2015-10-19 16:39
Can you please include a sample that reproduces the issues?

Also, can you verify that the SQLite file itself has the wrong characters? ( I use http://sqlitebrowser.org/ for inspecting the file directly.)

This looks similar to a bug we resolved a few months ago (see https://github.com/aspnet/EntityFramework/issues/2936). Which version of Entity Framework are you using?

**Comment by 3meng** [comment] 2015-10-20 15:11
Thanks for your reply.

Well, Here is the project dependencies:
``` CSharp
"dependencies": {
    "EntityFramework.SQLite": "7.0.0-beta7",
    "EntityFramework.Commands": "7.0.0-beta7",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta7",
    "Microsoft.AspNet.Mvc": "6.0.0-beta7",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta7",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta7",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta7",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta7",
    "Microsoft.AspNet.Session": "1.0.0-beta7",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta7",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta7",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta7",
    "Microsoft.Framework.Logging": "1.0.0-beta7",
    "Microsoft.Framework.Logging.Debug" : "1.0.0-beta7",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta7"
  },
```

And ConfigureServeces of Startup.cs:
``` CSharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddEntityFramework()
        .AddSqlite()
        .AddDbContext<AppDbContext>();
       
    ...
}
```

This is the DbContext config:
``` CSharp
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    base.OnConfiguring(optionsBuilder);
    var appEvn = CallContextServiceLocator.Locator.ServiceProvider.GetRequiredService<IApplicationEnvironment>();
    optionsBuilder.UseSqlite($"Data Source = { appEvn.ApplicationBasePath }/app.db");
}
```

Now, I start a test:
<img width="475" alt="qq20151020-1 2x" src="https://cloud.githubusercontent.com/assets/5876057/10611360/540910a6-777e-11e5-85cb-96f525bcf914.png">

When I submit, an action like this will be called:
``` CSharp
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Comment(string userName, int rating, string comment)
{
    var model = new RatingRecord
    {
        UserName = user.UserName,
        SupporterName = supUser.UserName,
        Rating = rating,
        RatingMsg = comment,
        Time = System.DateTime.Now
    };
    DbContext.RatingRecords.Add(model);
    await DbContext.SaveChangesAsync();

    ...
}
```

Next then I read the data from database and show it:
<img width="706" alt="qq20151020-2 2x" src="https://cloud.githubusercontent.com/assets/5876057/10611555/307e8d04-777f-11e5-87da-de2baf536443.png">

And the data in the database is also incorrect:
<img width="316" alt="qq20150820-4 2x" src="https://cloud.githubusercontent.com/assets/5876057/10611603/71dadf5a-777f-11e5-9172-c7fe6b8c44c6.png">

**Comment by 3meng** [comment] 2015-10-20 15:57
Year, I do a similar test like the [#2936](https://github.com/aspnet/EntityFramework/issues/2936), and the result is the same as his.

Like this:
<img width="476" alt="qq20151020-4 2x" src="https://cloud.githubusercontent.com/assets/5876057/10612038/a47f821a-7781-11e5-945f-ffb9afb9afb5.png">
<img width="704" alt="qq20151020-5 2x" src="https://cloud.githubusercontent.com/assets/5876057/10612040/a4d7b520-7781-11e5-9b1c-cde8b732a824.png">
<img width="355" alt="qq20151020-6 2x" src="https://cloud.githubusercontent.com/assets/5876057/10612039/a4d1a6a8-7781-11e5-8500-147a012c8e05.png">

But **now my project depends on the library of the version beta7**, is there any tool to help me to update? Especially to **detect the dependencies between project references**. Or I just need to change all the version string on `dependencies` of `project.json` file to "[version]-beta8"?

**Comment by natemcmaster** [comment] 2015-10-20 16:01
This looks like a duplicate of https://github.com/aspnet/EntityFramework/issues/2936. We fixed this in the beta8 release of Microsoft.Data.Sqlite (see https://github.com/aspnet/Microsoft.Data.Sqlite/pull/127).

Please try upgrading by just changing to "[version]-beta8". There will be some breaking changes (look at [this list on announcements](https://github.com/aspnet/announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-beta8) to see those relevant to beta8).

**Comment by rowanmiller** [comment] 2015-10-22 18:56
Please re-open if this still happens on Beta 8

**Closed** 2022-10-16 09:12 UTC
