### ISSUE TITLE
EFCore idempotent script fails when executed with "Incorrect syntax near 'CONCAT'"

### ISSUE THREAD

**Issue by kyletindle** [dotnet/efcore#22936] opened 2020-10-09 09:06 UTC
Given this 

    public partial class ApplicationType
    {
        public ApplicationType(string Name, string Description)
        {
            this.Name = Name;
            this.Description = Description;
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Other> Other{ get; set; } = new HashSet<Other>();
    }

in the SomeDBContext.cs in.NET core project 1 (.NET core class library)

     protected override void OnModelCreating(ModelBuilder modelBuilder)
     {
            base.OnModelCreating(modelBuilder);

            // ... snip ...

            modelBuilder.Entity<ApplicationType>().HasData(
                new ApplicationType("Type 1", "Description 1") { Id = 1 },
                new ApplicationType("Type 2", "Description 2") { Id = 2 });
     }

and this as a first migration in project 2 (ASP.NET core that references project 1)

        protected override void Up(MigrationBuilder migrationBuilder)
        {
           // .... snip ....
           migrationBuilder.CreateTable(
                name: "ApplicationType",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(maxLength: 100, nullable: false),
                    Description = table.Column<string>(maxLength: 500, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ApplicationType", x => x.Id);
                });

             // ... snip ...

             migrationBuilder.InsertData(
                table: "ApplicationType",
                columns: new[] { "Id", "Description", "Name" },
                values: new object[,]
                {
                    { 1, "Description 1", "Name 1" },
                    { 2, "Description 2", "Name 2" }
                });

           // ... snip ...
        }
Gives this invalid SQL in the idempotent sql file:

       IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20200715105610_SomeMigrationName')
       BEGIN
        IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Description', N'Name') AND [object_id] = 
          OBJECT_ID(N'[ApplicationType]'))
              SET IDENTITY_INSERT [ApplicationType] ON;
           EXEC(CONCAT(N'INSERT INTO [ApplicationType] ([Id], [Description], [Name])', CHAR(13), CHAR(10), N'VALUES (1Description1''Name1''),', CHAR(13), CHAR(10), N'(2Description 2''Name2'')'));
             IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Description', N'Name') AND [object_id] = OBJECT_ID(N'[ApplicationType]'))
             SET IDENTITY_INSERT [ApplicationType] OFF;
      END;
     GO

### Further information

This command is run from the parent solution folder containing both project folders

     dotnet.exe ef migrations script --idempotent --project ..\src\WebProject\WebProject.csproj --output C:\Output.sql

### Environment

.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015095 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by AndriySvyryd** [comment] 2020-10-09 18:35
Duplicate of https://github.com/dotnet/efcore/issues/22553
Fixed in 5.0.0-rc2

**Comment by kyletindle** [comment] 2020-10-14 08:48
Hi. I dont think this is fixed fully. I've installed .NET 5 RC2 AND VS2019 16.8 preview 4 and upgraded all of my NuGet packages to latest versions but its giving the exact same error messgae. This did used to work in .NET 5 preview 6 i think from memory. How to proceed?

**Closed** 2022-10-16 19:04 UTC
Labels: customer-reported
