### ISSUE TITLE
EF Core5.0 Slow queries

### ISSUE THREAD

**Issue by hwl962589950** [dotnet/efcore#24194] opened 2021-02-19 03:21 UTC
### Include your code

In the asynchronous method ToListAsync, when the field VCHAR is too long, the query is slow. When the asynchronization is eliminated and the ToList method is used, the query field is base64 of image transcoding, but I use the log to check, the database query part only takes 2ms. The actual mapping asynchronization is about 20S, and the non-asynchronization requires about 2S

### Code
```C#
            Stopwatch stopwatch = new Stopwatch();
            Console.WriteLine($"ToList Time Start");
            stopwatch.Start();
            var test1 = dbContext.CourseTree.ToList();
            stopwatch.Stop();
	    Console.WriteLine($"ToList Time {stopwatch.ElapsedMilliseconds}ms End");

            Console.WriteLine($"ToListAsync Time Start");
            stopwatch.Restart();
            var test2 = await dbContext.CourseTree.ToListAsync();
            stopwatch.Stop();
            Console.WriteLine($"ToListAsync Time {stopwatch.ElapsedMilliseconds}ms End");
```
### Log
```C#
ToList Time Start
info: 2021-02-19 11:19:35.263 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [c].[Id], [c].[CourseId], [c].[CourseTreeMainBoby], [c].[CourseTreeMainType], [c].[CreationTime], [c].[Name], [c].[OrderByIndex], [c].[ParentId], [c].[TreePath]
      FROM [CourseTree] AS [c]
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [c].[Id], [c].[CourseId], [c].[CourseTreeMainBoby], [c].[CourseTreeMainType], [c].[CreationTime], [c].[Name], [c].[OrderByIndex], [c].[ParentId], [c].[TreePath]
      FROM [CourseTree] AS [c]
ToList Time 93ms End
ToListAsync Time Start
info: 2021-02-19 11:19:35.353 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [c].[Id], [c].[CourseId], [c].[CourseTreeMainBoby], [c].[CourseTreeMainType], [c].[CreationTime], [c].[Name], [c].[OrderByIndex], [c].[ParentId], [c].[TreePath]
      FROM [CourseTree] AS [c]
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [c].[Id], [c].[CourseId], [c].[CourseTreeMainBoby], [c].[CourseTreeMainType], [c].[CreationTime], [c].[Name], [c].[OrderByIndex], [c].[ParentId], [c].[TreePath]
      FROM [CourseTree] AS [c]
ToListAsync Time 26799ms End
```

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by anranruye** [comment] 2021-02-19 05:44
See #23900. For this scenario, don't use Async methods.

**Comment by hwl962589950** [comment] 2021-02-19 06:36
> 
> 
> See #23900. For this scenario, don't use Async methods.

OK, it's greater than 1MB

**Comment by hwl962589950** [comment] 2021-02-19 06:41
OK, it's greater than 1MB




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "anranruye"<notifications@github.com&gt;; 
发送时间: 2021年2月19日(星期五) 中午1:45
收件人: "dotnet/efcore"<efcore@noreply.github.com&gt;; 
抄送: " "<962589950@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dotnet/efcore] EF Core5.0 Slow queries (#24194)





 
See #23900. For this scenario, don't use Async methods.

**Comment by roji** [comment] 2021-02-19 08:11
Duplicate of https://github.com/dotnet/SqlClient/issues/593

**Comment by roji** [comment] 2021-02-19 08:12
This is unfortunately a SqlClient issue that is out of EF 's control... You can indeed use the sync API as a workaround until that's fixed.

**Comment by hwl962589950** [comment] 2021-02-20 00:41
> 
> 
> This is unfortunately a SqlClient issue that is out of EF 's control... You can indeed use the sync API as a workaround until that's fixed.

All right. Got the question

**Closed** 2022-10-16 19:24 UTC
Labels: closed-external, customer-reported
