### ISSUE TITLE
Count after Take throws "No column name was specified for column 1 of 't'."

### ISSUE THREAD

**Issue by ditchcode** [dotnet/efcore#29667] opened 2022-11-23 19:45 UTC
I found similar closed issues surrounding Count with subqueries.

I discovered this passing a Linq query into a 3rd party library which internally performs a Count on the query it is given.

EF Core 7.0 Repro:
Perform a Take(25).CountAsync() on any context DbSet.

You wind up with

```
exec sp_executesql N'SELECT COUNT(*)
FROM (
    SELECT TOP(@__p_0) 1
    FROM [SomeTable] AS [c]
) AS [t]',N'@__p_0 int',@__p_0=25

```
Which throws database error "No column name was specified for column 1 of 't'"

This could easily be resolved by adding a column name ```AS [t](x)```, such as:

```
exec sp_executesql N'SELECT COUNT(*)
FROM (
    SELECT TOP(@__p_0) 1
    FROM [SomeTable] AS [c]
) AS [t](x)',N'@__p_0 int',@__p_0=25
```

EF Core 6.0 does not have this issue as it produces
``` SELECT TOP(@__p_0) [c].[Column1],[c].[Column2],.....```
It seems in 7.0, it was decided to simplify the Count by removing the SELECT fields and just using a hard-coded 1.
``` SELECT TOP(@__p_0) 1```

**Comment by roji** [comment] 2022-11-23 20:03
Which version of EF and SQL Server are you using? If you're on a version under 6.0, please upgrade to at least 6.0.

I can't reproduce this with either 6.0 or 7.0 on modern SQL Server; please see the code below, and tweak it to make the failure apparent.

<details>
<summary>Attempted repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

_ = await ctx.Blogs.Take(25).CountAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Blog
{
    public int Id { get; set; }
    public string? Name { get; set; }
}
```

</details>

**Comment by ditchcode** [comment] 2022-11-23 20:55
I discovered the issue affects specifically tables or views that have no key.
I'll have to read up further on the newer features surrounding this to see if this is expected.

Here's a Repro:
SQL 2019
Net Core 7.0


`#nullable disable

using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.Extensions.Logging;

var ctx = new ApiContext();
var x = await new ApiContext().Contacts.Take(25).CountAsync();
Console.WriteLine(x);

public class ApiContext : DbContext
{
    protected override void OnConfiguring
   (DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer("server=.;DATABASE=MyTestDataBase;Integrated Security=true;TrustServerCertificate=True;");
        optionsBuilder.LogTo(m => Console.WriteLine(m), Microsoft.Extensions.Logging.LogLevel.Debug);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
    }

    public DbSet<Contact> Contacts { get; set; }

}

public class Contact
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
}


public partial class ContactMap : IEntityTypeConfiguration<Contact>
{
    public void Configure(EntityTypeBuilder<Contact> entity)
    {
        entity.ToTable("Contacts", "dbo");

        //entity.HasKey(e => e.Id);
        entity.HasNoKey();

        entity.Property(e => e.FirstName)
            .HasColumnName("First_Name")
            .HasMaxLength(50)
            .IsUnicode(false);

        entity.Property(e => e.LastName)
            .HasColumnName("Last_Name")
            .HasMaxLength(50)
            .IsUnicode(false);
    }
}
`

**Comment by ditchcode** [comment] 2022-11-23 21:02
Apparently when the entity has a key the SQL produced has a valid column name:

```
SELECT COUNT(*)
      FROM (
          SELECT TOP(@__p_0) [t].[Id]
          FROM [dbo].[t_Contacts] AS [t]
      ) AS [t0]

```

**Comment by roji** [comment] 2022-11-24 08:45
Thanks, this indeed repros for keyless entity types. When there's a key we just select that in the subquery, but there isn't we select nothing, which is syntactically incorrect. We could always select out star instead for this case.

**Comment by roji** [comment] 2022-11-24 08:46
Note that this is a regression from 6.0, where we'd always select all columns, regardless of key/keyless:

```c#
      SELECT COUNT(*)
      FROM (
          SELECT TOP(@__p_0) [b].[Id], [b].[Name]
          FROM [Blogs] AS [b]
      ) AS [t]
```

**Comment by StefanOssendorf** [comment] 2022-12-22 08:48
With milestone 8.0.0 this will be fixed with EFCore 8.0? Is that correct?

**Comment by StefanOssendorf** [comment] 2022-12-22 09:46
Furthermore this also holds for e.g. table valued functions used in a query which results in a `SELECT TOP(@__p_0) 1`.

**Comment by ajcvickers** [comment] 2023-01-11 21:12
@maumar to look for workaround.

**Comment by maumar** [comment] 2023-01-21 02:00
sadly there is no good workaround - Count if effectively pruning the projection, so we can't do any tricks to circumvent the issue. Either entity must have a key, or Count must be performed on the client.

Note that 


```sql
exec sp_executesql N'SELECT COUNT(*)
FROM (
    SELECT TOP(@__p_0) 1 as foo
    FROM [SomeTable] AS [c]
) AS [t](x)',N'@__p_0 int',@__p_0=25
```

works just fine. i.e. we just need to add alias to the "empty" projection to satisfy the sql engine, but that's not something we can force from the user side at the moment.

We should either revert to old behavior or force a dummy alias on the empty projection

**Comment by maumar** [comment] 2023-01-26 18:39
reopen for potential servicing

**Closed** 2023-02-14 19:47 UTC
Labels: type-bug, closed-fixed, regression, customer-reported, Servicing-approved, area-query
