### ISSUE TITLE
Wrong 'Order by' priorities in SQL when using multiple OrderBy statements

### ISSUE THREAD

**Issue by gius** [dotnet/efcore#13514] opened 2018-10-05 14:18 UTC
Using multiple `OrderBy` statements is sometimes translated with wrong priorities just like the later `OrderBy` was `ThenBy`.

This was OK with EF Core 2.0.3 but does not work with 2.1.0 and later.

Unfortunately, I can reproduce the issue only when using Automapper, I was not able to isolate the problem further. However, since the test case works properly when using differrent IQueryable source or EF Core version 2.0.3, I believe the problem is within EF Core.
Please see the [gist](https://gist.github.com/gius/d1cff1dea8686c6d822a1ef290a042bc).

The problem is with the third query where 
```c#
.OrderBy(x => x.ID)
.OrderBy(x => x.Name)
```
is translated to SQL as
`ORDER BY [x].[ID], [x].[Name]`
instead of
`ORDER BY [x].[Name], [x].[ID]`

The problem is simplified in the example, real use of such feature is to provide a default sorting (first `OrderBy` call) when returning an `IQueryable` but allowing the client to apply custom sorting if needed.

### Further technical details
EF Core version: 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.5

**Comment by smitpatel** [comment] 2018-10-05 17:02
@maumar - Looks like correlated subquery is doing something funky with ordering.

**Comment by ajcvickers** [comment] 2018-10-05 20:20
Triage: we will look at this for 2.2, but will punt to 3.0 if it gets complicated and/or risky.

**Comment by maumar** [comment] 2018-10-10 20:08
Problem is indeed caused by correlated collection optimization. When determining order in which the correlated queries should be returned we take all the orderby clauses in the order that they were declared. This is incorrect for corner cases, such as one in the repro. Problem also exists to a certain extent in the Include pipeline, when including collections, although the algorithm used is slightly different so the problem manifests differently and for different cases. Good news is that both queries are returned in the same order, so there is no data corruption - all relevant children are returned and associated with their parents. Its just that the parents come in the different order than expected.

**Comment by maumar** [comment] 2018-10-10 20:13
@gius workaround is to change a mapping for the `Addresses` collection somewhat by adding Skip(0) at the end. This will not change the results but will disable correlated collection optimization which is the source of the issue you are seeing. 

Caveat is that queries won't be able to take advantage of the perf boost that comes with this optimization - we will now issue N+1 queries, rather than just 2 (just like we did in EF 2.03).

```
config.CreateMap<Customer, CustomerDto>().ForMember(c => c.Addresses, mo => mo.MapFrom(e => e.Addresses.Skip(0)));
```

**Comment by maumar** [comment] 2019-06-20 01:09
we changed the way correlated subqueries are implemented - everything will be in one query now so the issue is no longer relevant, closing

**Closed** 2022-10-16 13:34 UTC
Labels: type-bug, closed-out-of-scope, regression, customer-reported
