### ISSUE TITLE
How to query to retrieve all records and also see if the records exists in many-to-many mapping table 

### ISSUE THREAD

**Issue by mkothapalli418** [dotnet/efcore#30646] opened 2023-04-06 22:23 UTC
I have below  scenarios, where EF core 7 ignored creating the many-to-many mapping table using the ef-scaffolding. 

1. I have to query the return all the entries in mapping table by joining it to the primary key table
2. I have to check if there is an entry in mapping table my using the keys of its primary key table

Table Schema
Products -> ProductGroupMapping <- ProductGroups **->** **ProductGroupUserGroup** **<-** UserGroups -> UserGroupMapping -> Users

Please help

**Comment by ajcvickers** [comment] 2023-04-07 16:52
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-04-19 19:15
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-04-19 19:15 UTC
Labels: customer-reported
