### ISSUE TITLE
remove-migration: The model must be finalized before 'GetTypeMapping' can be used

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#16857] opened 2019-07-30 21:07 UTC
using asp.net core preview 7

&gt;The model must be finalized before 'GetTypeMapping' can be used. Ensure that either 'OnModelCreating' has completed or, if using a stand-alone 'ModelBuilder', that 'FinalizeModel' has been called

This exception occures when I use the command _remove-migration_ at the Package Manager Console

The project is quite standard except
- I created _ApplicationUser_
- Changed DB default schema at _OnModelCreating()_ using _builder. HasDefaultSchema()_

Steps to reproduce:
- Alter model or DbContext to modify schema
- add-migration
- remove-migration -&gt; error occures

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/664157/remove-migration-the-model-must-be-finalized-befor.html
VSTS ticketId: 956522_
_These are the original issue comments:_

Visual Studio Feedback System on 7/29/2019, 02:01 AM (36 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
Visual Studio Feedback System on 7/30/2019, 00:07 AM (13 hours ago): <markdown><p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by ajcvickers** [comment] 2019-07-30 21:10
Duplicate of #16737

**Closed** 2022-10-16 14:33 UTC
Labels: closed-duplicate, customer-reported
