### ISSUE TITLE
InMemory and SQL Server provider seems to access TPH shared columns differently

### ISSUE THREAD

**Issue by joakimriedel** [dotnet/efcore#25210] opened 2021-07-06 19:24 UTC
## File a bug

While trying to find a way to access a shared column between multiple classes using TPH [(see StackOverflow post here)](https://stackoverflow.com/questions/68270038/is-it-possible-to-access-a-shared-tph-column-in-ef-core-without-using-intermedia) I learned that there is a difference in how the SqlServer and InMemory providers handle accessing a shared column between multiple classes in TPH.

In SqlServer provider, I can access the shared columns for all overrides using a single cast of one of the types.
In InMemory provider, it is more specific so I need to add each override manually (actually more correct imo)

Depending on what is the proper way forward here, this issue is about:

a) Fixing a bug to ensure feature parity between the two providers so that
a1) They both need to be specific for each type (like InMemory today)
a2) They both will access the shared column when using a single type (like SqlServer today)

or

b) request a feature to access the shared column in a future proof way, perhaps with EF.Property as below (which does not currently work)

What do you suggest from the EF team?

### Include your code

```C#
class Program
    {
        public static readonly ILoggerFactory MyLoggerFactory
            = LoggerFactory.Create(builder => { 
                builder.AddConsole(); 
            });

        static async Task Main(string[] args)
        {
            using (var context = new ClientContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                var actions = await context.Actions
                    .Select(a => new
                    {
                        Id = a.Id,

                        // this will access Message column in all overrides in SqlServer but not with InMemory
                        Message = (a as ActionB).Message,

                        // this works for both providers - but really messy and complex in real world code
                        //Message = (a as ActionA).Message ?? (a as ActionB).Message,

                        // this throws "Either the query source is not an entity type, or the specified property does not exist on the entity type."
                        // is there any other way to access the shared column Message?
                        // Message = EF.Property<string>(a, "Message"),
                    })
                    .ToListAsync();

                actions.ForEach(a => Console.WriteLine(a.Id + a.Message));
            }
        }

        public class ActionBase
        {
            public int Id { get; set; }

            // ... other shared properties
        }

        public class ActionA : ActionBase
        {
            // shared with B
            [Required]
            [Column("Message")]
            public string Message { get; set; }

            // ... other specific properties
        }

        public class ActionB : ActionBase
        {
            // shared with A
            [Required]
            [Column("Message")]
            public string Message { get; set; }

            // ... other specific properties
        }

        public class ActionC : ActionBase
        {
            public string SomethingElse { get; set; }

            // ... other specific properties
        }

        class ClientContext : DbContext
        {
            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                // TO USE SQL
                //optionsBuilder
                //    .UseLoggerFactory(MyLoggerFactory)
                //    .UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=TPHSharedColumn;Trusted_Connection=True;MultipleActiveResultSets=true;Connect Timeout=30")
                //    .EnableSensitiveDataLogging(false);
                // TO USE INMEMORY
                optionsBuilder
                   .UseLoggerFactory(MyLoggerFactory)
                   .UseInMemoryDatabase(Guid.NewGuid().ToString());
            }

            protected override void OnModelCreating(ModelBuilder builder)
            {
                base.OnModelCreating(builder);

                builder.Entity<ActionA>().HasData(new ActionA()
                {
                    Id = 1,
                    Message = "A"
                });
                builder.Entity<ActionB>().HasData(new ActionB()
                {
                    Id = 2,
                    Message = "B"
                });
                builder.Entity<ActionC>().HasData(new ActionC()
                {
                    Id = 3,
                    SomethingElse = "C"
                });
            }

            public DbSet<ActionBase> Actions { get; set; }
        }
    }
```

### Expected output

Running the above code with any valid access method, I expect the output to be

```
1A
2B
3
```

for both providers.

### Include provider and version information

EF Core version: 5.0.7 or 6.0.0-preview.5.21301.9
Database provider: SqlServer and InMemory
Target framework: .NET 5.0

**Comment by smitpatel** [comment] 2021-07-06 20:06
Related #20335

This is by-design.

InMemory does not have TPH mapping pattern. Each entity type is stored in their own table. So when selecting property from one of the derived type only, the correct property will be picked up because there is no "column" sharing.

Relational providers which uses TPH and shared column also does similar processing except it translate to column access in SQL which contains data for other types. The only way to make it "accurate" in relational is to add condition on discriminator so translation would be something like `CASE WHEN a.Discriminator is "ActionB" THEN a.Message ELSE null END` which is complicated and may cause index miss in most providers. (it translate to conditional here because of `as` operator which is soft-cast, hard-cast in ideal scenario should client-eval to throw as in linked issue.). The issue only happens when the column is being used by other types also. So the cost of making it entirely accurate doesn't justify the perf penalty.

Since, the issue stems from sharing same column to store data for different types which is specific to relational provider only, these is scenario where queries are going to differ between providers in how they operate. In order to make query work in accurate way for relational, users can add the conditional access on discriminator type rather than soft-cast. Since making inmemory like relational is opposite of accurate behavior and doesn't correspond to InMemory data storage behavior (no column sharing), it is not something we are planning to add. To get the relational-like faulty behavior in InMemory the work-around used in OP is right way to do it.

**Comment by joakimriedel** [comment] 2021-07-07 09:04
I understand, thanks for sharing that.

A) So what the InMemory provider actually does is to ignore the column mapping set with ColumnAttribute? If it respected the column and stored information on that, would it be reasonable to introduce something like EF.Column<string>(item, "Message") to access a specific column across a TPH inheritance chain that would then have the same behaviour for all providers?

B) About the "accuracy" of the SqlServer provider, I would actually have appreciated if it translate to a condition on discriminator if I used the soft-cast version - and for performance perhaps leave the current behaviour for hard-cast. From a user perspective, if I wrote something like this

```c#
   ItemXHasExpired = (item as ItemX).Expired
```

while at the same time having reused the columns like this due to some unknown sql dba requirement

```c#
   // ItemX
   [Column("additional_bit_flag")]
   public bool Expired {get; set;}

   // ItemY
   [Column("additional_bit_flag")]
   public bool CustomerApproved {get; set;}
```

this would render some funny debugging sessions on why it behaves differently locally in InMemory unit tests compared to actual production server (SqlServer).

Current solution if I understand correctly would be always doing

```c#
   ItemXHasExpired = item is ItemX ? (item as ItemX).Expired : false
```

But I think this is easily forgotten since where the `(item as ItemX).Expired` part normally would yield results for ItemX.

Either way, if this issue would close by design, I do think some documentation update in the chapter of inheritance and shared columns would be nice to clarify how this works and with a warning that the implementation of accessing shared columns differs between the provider implementations.

**Comment by smitpatel** [comment] 2021-07-07 15:46
1) ColumnAttribute sets the name of the column in the database, except InMemory doesn't have column names so that attribute is not used for InMemory database. Same goes for other attributes which are database object names like TableAttribute. Which is somewhat fine since InMemory is not really a database which has object naming. I will let @AndriySvyryd share his thoughts relating to how TPH is different in InMemory compared to relational. Query is just consumer of the metadata model.

2) I would agree with you hence I filed issue #20335. We discussed that in detail when triaging the issue. We decided to close it by design because changing it now becomes breaking change and very few cases where it truly causes issue, which can be made work by rewriting query. There are differences between providers in variety of different ways in how they translate query, so this mismatch between providers wasn't enough reason to justify the breaking change.

**Comment by AndriySvyryd** [comment] 2021-07-07 17:12
InMemory is not a relational provider, we don't plan to add support for relational features to it.

**Comment by joakimriedel** [comment] 2021-07-08 18:56
Ok, won't argue against the valid points. Feel free to close by design.

As a user, I would enjoy some sort of notice or warning in the chapter on shared columns about this. Could prepare a PR if you'd like me to.

**Comment by AndriySvyryd** [comment] 2021-07-08 19:10
@joakimriedel You could send a PR to add something to https://docs.microsoft.com/en-us/ef/core/testing/#approach-3-the-ef-core-in-memory-database if you think the current text is not explicit enough. I don't think it's worth it to sprinkle all relational articles with warnings about testing with InMemory

**Comment by joakimriedel** [comment] 2021-07-08 19:55
@AndriySvyryd this issue is not about testing with InMemory, it's about accessing shared columns in SqlServer.

**Comment by AndriySvyryd** [comment] 2021-07-08 20:56
Ok, prepare the PR and we can discuss it further there.

**Comment by joakimriedel** [comment] 2021-07-09 12:25
@AndriySvyryd submitted PR in the Docs repo here https://github.com/dotnet/EntityFramework.Docs/pull/3321

**Closed** 2022-10-16 19:39 UTC
Labels: closed-by-design, customer-reported
