### ISSUE TITLE
SingleOrDefaultAsync throws NullReference Exception if source is empty

### ISSUE THREAD

**Issue by BenjaminAbt** [dotnet/efcore#17056] opened 2019-08-09 13:39 UTC
We have updated our source code from Preview 5 to Preview 7.
We found a bug in SingleOrDefaultAsync. As soon as the collection is empty, a NullReference exception is thrown.

### Steps to reproduce

This is our in-memory test
```c#
[Theory, AutoMoqData]
public async Task HandleTests_Without_User(Mock<IEventDispatcher> evntDp, Mock<IActivationkeyGenerator> keyMock, string userName)
{
    // Connection
    DbContextOptions<SampleDbContext > options = new DbContextOptionsBuilder<SampleDbContext >()
              .UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;

    // Execute
    using (SampleDbContext = new SampleDbContext (options))
    {
        // Notification
        UserAddedEventNotification notification = new UserAddedEventNotification(1, userName);

        // Command Handler
        SampleHandler ch = new SampleHandler (evntDp.Object, dbContext, keyMock.Object);

        // Execute
        Func<Task> f = async () => await ch.Handle(notification, default);

         await f.Should().ThrowAsync<UserNotFoundException>();
    }
}
```
The actually interesting snippet is the following:
```c#
var userEntity = await _dbContext.Users.Where(x => x.Id == userId).SingleOrDefaultAsync(cancellationToken);
if (userEntity is null)
{
    throw new UserNotFoundException();
}
```

`SingleOrDefaultAsync` throws a NullReference Exception, if no entry was found.
Works if entry was found.

> "Object reference not set to an instance of an object."   at Microsoft.EntityFrameworkCore.InMemory.Query.Pipeline.InMemoryShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable1.AsyncEnumerator.MoveNextAsync()   at Microsoft.EntityFrameworkCore.Query.Pipeline.ShapedQueryCompilingExpressionVisitor.<SingleOrDefaultAsync>d__17'1.MoveNext()  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at Microsoft.EntityFrameworkCore.Query.Pipeline.ShapedQueryCompilingExpressionVisitor.<SingleOrDefaultAsync>d__17'1.MoveNext()  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

However, the following workaround works:

```c#
var userEntities = await _dbContext.Users.Where(x => x.Id == userId).ToListAsync(cancellationToken);
var userEntity = userEntities.SingleOrDefault();
if (userEntity is null)
{
    throw new UserNotFoundException();
}
```

### Further technical details
EF Core version: 3.0.0-preview7.19362.6
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: 10.0.17763.615
IDE: 16.3.0 Preview 1.0

**Comment by ajcvickers** [comment] 2019-08-09 15:55
Duplicate of #16099

**Closed** 2022-10-16 14:34 UTC
Labels: closed-duplicate, customer-reported
