### ISSUE TITLE
single query with auto-calculation does not support tracking

### ISSUE THREAD

**Issue by ice1e0** [dotnet/efcore#15509] opened 2019-04-27 16:19 UTC
## In short
I try to do get an SQL query from linq which combines calculated information (SUM, COUNT etc.) form other tables in a single query but with the option that my main entry is tracked, but it looks like that I can get only one of both done.

(Related MSDN article: https://docs.microsoft.com/en-us/ef/core/querying/tracking )

## Detailed explanation with samples

Given is the following data model:

``` c#
public class MyAccountEntry
{
	public string AccountNum { get; set; }
	
	public decimal Amount { get; set; }
}

public class MyAccount
{
	public string AccountNum { get; set; }
	
	public string Description { get; set; }
	
	public virtual ICollection<MyAccountEntry> Entries { get; set; }
	
	[NotMapped]
	public decimal Balance { get; set; }
}
```

I want to get now all `MyAccount` entries with the blanace. The balance is calculated by summarizing all entries from one account, e.g. `account.Entries.Sum(en => en.Amount)`.

### Option 1: SQL looks good, but no tracking

The following code produces a singe SQL query which gives me the data I want:
``` c#
var query = from account in dbContext.Accounts
	select new MyAccount()
	{
		// all normal db fields
		AccountNum = account.AccountNum,
		Description = account.Description,
		
		// calculated fields
		Balance = account.Entries.Sum(en => en.Amount)
	};
var accounts = query.ToList();
```
``` sql
SELECT [e].[AccountNum], [e].[Description], (
    SELECT SUM([en].[Amount])
    FROM [LedgerAccountEntry] AS [en]
    WHERE ([e].[LedgerAccountNum] = [en].[LedgerAccountNum])
) AS [Balance]
FROM [MyAccount] AS [e]
```

The problem is that now there is no tracking for my `MyAccount()` instances. I would have to manually attach the entries to the ChangeTracker. This is not what I want (and it is difficult to do this because I might attach entries twice which causes an exception!). 

### Option 2: With tracking but SQL iteration for each calculation

The following code gives me the entry which is tracked:
``` c#
var query = from account in dbContext.Accounts
	select new
	{
		// entry
		Account = account,
		
		// calculated fields
		Balance = account.Entries.Sum(e => e.Amount)
	};
var dynamicList = query.ToList();
var accounts = new List<MyAccount>();
foreach(var dynamicEntry in query)
{
	var account = dynamicEntry.Account;
	account.Balance = dynamicEntry.Balance;
	accounts.Add(account);
}
```

But the SQL execution is terrible:
``` sql

-- query for MyAccount
SELECT [e].[CompanyNum], [e].[LedgerAccountNum], [e].[CurrencyCode], [e].[Description], [e].[RowVersion]
FROM [LedgerAccount] AS [e]
WHERE [e].[CompanyNum] = @__dataDomainScope_CurrentCompanyNum_0
ORDER BY [e].[CompanyNum], [e].[LedgerAccountNum]

-- single query for each account entry:
SELECT SUM([en0].[Amount])
FROM [MyAccountEntry] AS [en0]
WHERE (@_outer_AccountNum = [en0].[AccountNum])

SELECT SUM([en0].[Amount])
FROM [MyAccountEntry] AS [en0]
WHERE (@_outer_AccountNum = [en0].[AccountNum])

SELECT SUM([en0].[Amount])
FROM [MyAccountEntry] AS [en0]
WHERE (@_outer_AccountNum = [en0].[AccountNum])

...

```

I could optimize this so that I use a second query which gives me just the account sum and the primary key to reduce the SQL executions to two, but than I have to deal with merging both lists together.

## Conclusion

I miss an option how I can combine the benefits of both worlds: Getting the nice SQL query shown in option 1 and the tracking as it works in option 2.

### Suggestion how to solve this
When I initialize a new object in the `select` statement I can use an method `quert.WithTracking(DbSet)` to tell the change tracker that I want to have these entries tracked.

``` c#
var query = from account in dbContext.Accounts
	select new MyAccount()
	{
		// all normal db fields
		AccountNum = account.AccountNum,
		Description = account.Description,
		
		// calculated fields
		Balance = account.Entries.Sum(en => en.Amount)
	};
var accounts = query.WithTracking(dbContext.Accounts).ToList();
```

This could be implemented in two options:

1. all db fields are set automatically, I don't need to take care of this.
2. the db fields are not set automatically. I need to set all primary key fields to be able to use the method `query.WithTracking(...)`.

This might not be the best solution and there might be a better way; but as conclusion, I think we all can conclude on that this function would make things a lot easier e.g in editable views.

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 
IDE: Visual Studio 2019 16.0.2

**Comment by smitpatel** [comment] 2019-04-29 03:14
Duplicate of #11186

**Closed** 2022-10-16 14:19 UTC
Labels: customer-reported
