### ISSUE TITLE
EF Core generates Update instead of Insert

### ISSUE THREAD

**Issue by bdaniel7** [dotnet/efcore#20831] opened 2020-05-04 10:42 UTC
This setup used to work with EF Core 2.2. Then I decided to upgrade to .NET (EF) Core 3.1. And it didn't work anymore.

```C#
public class Measure : IAmAuditable
{
  [Key] public int Id { get; set; }
	// IAmAuditable 
  public DateTime Created { get; set; }
  public string CreatedBy { get; set; }
  public string CreatedWith { get; set; }
  public DateTime? Updated { get; set; }
  public string UpdatedBy { get; set; }
  public string UpdatedWith { get; set; }
  public Guid? UpdatedById { get; set; }

  public bool IsDeleted { get; set; }

  readonly HashSet<AffectedProduct> affectedProducts
		= new HashSet<AffectedProduct>();

  public virtual IReadOnlyCollection<AffectedProduct> AffectedProducts
		=> affectedProducts.ToList();

  public void MergeAffectedProducts(HashSet<AffectedProduct> incomingAffectedProducts)
  {
	if (incomingAffectedProducts.IsNullOrEmpty())
		return;

	foreach (var dbAffectedProduct in AffectedProducts)
	{
		if (!incomingAffectedProducts.Contains(dbAffectedProduct))
		{
			affectedProducts.Remove(dbAffectedProduct);
			Updated = DateTime.UtcNow;
		}
		else
		{
			incomingAffectedProducts.TryGetValue(dbAffectedProduct,
						out var incomingAffectedProduct);
	   		if (incomingAffectedProduct != null)
			{
				Map(dbAffectedProduct, incomingAffectedProduct);
				Updated = DateTime.UtcNow;
			}
		}
	}

	foreach (var affectedProductToAdd in incomingAffectedProducts)
	{
		if (!affectedProducts.Contains(affectedProductToAdd))
		{
			affectedProductToAdd.MeasureId = Id;
			affectedProducts.Add(affectedProductToAdd);
			Updated = DateTime.UtcNow;
		}
	}
  }

   void Map(AffectedProduct dbAffectedProduct, AffectedProduct incomingAffectedProduct)
   {
	  dbAffectedProduct.IsDeleted = false;
	  dbAffectedProduct.ValidTo = incomingAffectedProduct.ValidTo;
	  dbAffectedProduct.ValidFrom = incomingAffectedProduct.ValidFrom;	 
	}
}

public class AffectedProduct : IEquatable<AffectedProduct>, IAmAuditable
{
	public int MeasureId { get; set; }
	public int ProductId { get; set; }
	public int DatasetId { get; set; }

	public DateTime ValidFrom { get; set; }
	public DateTime? ValidTo { get; set; }

    // IAmAuditable 
	public DateTime Created { get; set; }
	public string CreatedBy { get; set; }
	public string CreatedWith { get; set; }
	public DateTime? Updated { get; set; }
	public string UpdatedBy { get; set; }
	public string UpdatedWith { get; set; }
	public Guid? UpdatedById { get; set; }

	public bool IsDeleted { get; set; }

	/// <inheritdoc />
	public bool Equals(AffectedProduct other)
	{
		if (ReferenceEquals(null, other)) return false;
		if (ReferenceEquals(this, other)) return true;
		return MeasureId == other.MeasureId
		    && ProductId == other.ProductId
		    && DatasetId == other.DatasetId;
	}

	/// <inheritdoc />
	public override bool Equals(object obj)
	{
		if (ReferenceEquals(null, obj)) return false;
		if (ReferenceEquals(this, obj)) return true;
		if (obj.GetType() != GetType()) return false;
		return Equals((AffectedProduct) obj);
	}

	/// <inheritdoc />
	public override int GetHashCode()
	{
		return HashCode.Combine(MeasureId, ProductId, DatasetId);
	}
}

public class MeasureConfiguration : IEntityTypeConfiguration<Measure>
{
	// some legacy database
	public void Configure(EntityTypeBuilder<Measure> builder)
	{
		builder.ToTable("Measures");
		builder.Property<int>("Id")
				.ValueGeneratedOnAdd()
				.HasAnnotation("SqlServer:ValueGenerationStrategy",
				SqlServerValueGenerationStrategy.IdentityColumn);

		builder.Metadata
			.FindNavigation(nameof(Measure.AffectedProducts))
			.SetPropertyAccessMode(PropertyAccessMode.Field);
	}
}

public class AffectedProductConfiguration : IEntityTypeConfiguration<AffectedProduct>
{
	public void Configure(EntityTypeBuilder<AffectedProduct> builder)
	{
       // some legacy database
       builder.HasKey(e => new {e.MeasureId, e.ProductId, e.ValidFrom});
	   builder.ToTable("AffectedProducts");

	   builder.HasOne(d => d.Measure)
		    .WithMany(p => p.AffectedProducts)
		    .HasForeignKey(d => d.MeasureId)
		    .HasConstraintName("FK_Measures_AffectedProducts");
	}
}

public class AffectedProductDto : IEquatable<AffectedProductDto>
{
	public int MeasureId { get; set; }
	public int ProductId { get; set; }
	public int DatasetId { get; set; }

	public DateTime ValidFrom { get; set; }
	public DateTime? ValidTo { get; set; }

	public bool Equals(AffectedProductDto other)
	{
		if (ReferenceEquals(null, other)) return false;
		if (ReferenceEquals(this, other)) return true;
		return MeasureId == other.MeasureId
				&& ProductId == other.ProductId
				&& DatasetId == other.DatasetId;
	}

	public override bool Equals(object obj)
	{
		if (ReferenceEquals(null, obj)) return false;
		if (ReferenceEquals(this, obj)) return true;
		if (obj.GetType() != GetType()) return false;
		return Equals((AffectedProductDto) obj);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(MeasureId, ProductId, DatasetId);
	}
}

public static class ChangeTrackerExtensions 
{
  public static void SetShadowProperties(this ChangeTracker changeTracker, UserInfo userInfo)
  {
    if (userInfo == null)
    {
	   throw new TException("userInfo is not set! Cannot get Audit info.");
    }
  	changeTracker.DetectChanges();

	var timestamp = DateTime.UtcNow;

	foreach (var entry in changeTracker.Entries())
	{
      if (entry.Entity is IAmAuditable)
	  {
	    if (entry.State == EntityState.Modified)
		{
		  entry.Property("Updated").CurrentValue = timestamp;
		  entry.Property("UpdatedBy").CurrentValue = userInfo.FullName;
		  entry.Property("UpdatedWith").CurrentValue = "t-online";
		  entry.Property("UpdatedById").CurrentValue = Guid.Parse(userInfo.UserId);
		}

		if (entry.State == EntityState.Added)
		{
			entry.Property("Created").CurrentValue = timestamp;
			entry.Property("CreatedBy").CurrentValue = userInfo.FullName;
			entry.Property("CreatedWith").CurrentValue = "t-online";

			entry.Property("Updated").CurrentValue = timestamp;
			entry.Property("UpdatedBy").CurrentValue = userInfo.FullName;
			entry.Property("UpdatedWith").CurrentValue = "t-online";
			entry.Property("UpdatedById").CurrentValue = Guid.Parse(userInfo.UserId);
		}
	  }

	if (entry.State == EntityState.Deleted && entry.Entity is ICanBeSoftDeleted)
	{
		if (entry.Entity is IAmAuditable)
	    {
			entry.Property("Updated").CurrentValue = timestamp;
			entry.Property("UpdatedBy").CurrentValue = userInfo.FullName;
			entry.Property("UpdatedWith").CurrentValue = "t-online";
			entry.Property("UpdatedById").CurrentValue = Guid.Parse(userInfo.UserId);
		}

		entry.State = EntityState.Modified;
		entry.Property("IsDeleted").CurrentValue = true;
	}
  }
  }
}

public class UpdateMeasureCommand
{
  public List<AffectedProductsDto> AffectedProducts
		= new List<AffectedProductsDto>();
  public HashSet<AffectedProducts> CreateAffectedProductsForDb()
  {
	// all fields are copied from dto to entity, all OK.
    // Adapt is from Mapster.
    return AffectedProducts.Adapt<List<AffectedProductDto>,
				HashSet<AffectedProduct>>();
  }
}

// no disconnected entities
var measure = dbContext.Measures
				.Include(m => m.AffectedProducts)
				.SingleOrDefaultAsync(m => m.Id = request.Id);

// these are new objects, 
var incomingAffectedProducts = command.CreateAffectedProductsForDb();

measure.MergeAffectedProducts(incomingAffectedProducts);

await dbContext.SaveChangesAsync();
```

The resulted SQL:
```SQL
UPDATE [AffectedProducts] SET [Created] = @p0, [Created_by] = @p1, [Created_with] = @p2, [DatasetId] = @p3, [IsDeleted] = @p4, [Notes] = @p5, [Updated] = @p8, [Updated_by] = @p9, [UpdatedById] = @p10, [Updated_with] = @p11, [Valid_To] = @p12
WHERE [MeasureId] = @p13 AND [ProductId] = @p14 AND [Valid_From] = @p15;
SELECT @@ROWCOUNT;

UPDATE [Measures] SET [Updated] = @p32
WHERE [Id] = @p33;
SELECT @@ROWCOUNT;

@p0='0001-01-01T00:00:00' (DbType = DateTime), @p1=NULL (Nullable = false) (Size = 50), @p2=NULL (Nullable = false) (Size = 128), @p3='2145', @p4='False', @p5=NULL (Size = 4000), @p6='False', @p7='' (Size = 4000), @p8='2020-05-04T09:47:43' (Nullable = true) (DbType = DateTime), @p9='' (Size = 50), @p10='0a4c2328-ad09-407d-8fb0-66e63169928f' (Nullable = true), @p11='t-online' (Size = 128), @p12='9999-12-31T00:00:00' (Nullable = true) (DbType = Date), @p13='344079', @p14='2456330', @p15='1970-01-01T00:00:00' (DbType = Date)
```

But it should be 
```sql
INSERT INTO [AffectedProducts] ([MeasureId], [ProductId], [DatasetId], [Created]...)
```

### Further technical details

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1.3
Operating system: Windows 10 
IDE: JetBrains Rider 2020.1.1

**Comment by ajcvickers** [comment] 2020-05-04 19:21
@bdaniel7 It's not clear to me what is going on here. However, I notice that your types are overriding Equals/GetHashCode. EF can only track a single instance of a given type. If you have two instances that are intended to represent the same entity, then this could be causing issues. Beyond this, 
please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate. The key thing here is that we need to be able to run the code, which is not possible with the code posted above since it is missing too much.

**Comment by ajcvickers** [comment] 2020-05-15 16:26
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:23 UTC
Labels: closed-could-not-reproduce, customer-reported
