### ISSUE TITLE
test Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpEntityTypeGeneratorTest.Navigation_properties() failed

### ISSUE THREAD

**Issue by MarinaRybalko** [dotnet/efcore#15614] opened 2019-05-04 07:50 UTC
Describe what is not working as expected.

I run test  Namespace: `Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpEntityTypeGeneratorTest`
Method: `Navigation_properties()`

If you are seeing an exception, include the full exceptions details (message and stack trace).
Test does not assert.
Expected string: 
 `"using System;\nusing System.Collections.Generic;\nusing System.ComponentModel.DataAnnotations;\nusing System.ComponentModel.DataAnnotations.Schema;\n\nnamespace TestNamespace\n{\n    public partial class Post\n    {\n        public Post()\n        {\n            Contributions = new HashSet<Contribution>();\n        }\n\n        public int Id { get; set; }\n        public int? AuthorId { get; set; }\n\n        [ForeignKey(\"AuthorId\")]\n        public virtual Person Author { get; set; }\n        public virtual ICollection<Contribution> Contributions { get; set; }\n    }\n}\n" `

Actual string: `"using System;\r\nusing System.Collections.Generic;\r\nusing System.ComponentModel.DataAnnotations;\r\nusing System.ComponentModel.DataAnnotations.Schema;\r\n\r\nnamespace TestNamespace\r\n{\r\n    public partial class Post\r\n    {\r\n        public Post()\r\n        {\r\n            Contributions = new HashSet<Contribution>();\r\n        }\r\n\r\n        public int Id { get; set; }\r\n        public int? AuthorId { get; set; }\r\n\r\n        [ForeignKey(\"AuthorId\")]\r\n        public virtual Person Author { get; set; }\r\n        public virtual ICollection<Contribution> Contributions { get; set; }\r\n    }\r\n}\r\n"`

```
Test Name:	Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpEntityTypeGeneratorTest.Navigation_properties
Test FullName:	Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpEntityTypeGeneratorTest.Navigation_properties
Test Source:	D:\VladikKek\EntityFrameworkCore-master\test\EFCore.Design.Tests\Scaffolding\Internal\CSharpEntityTypeGeneratorTest.cs : line 12
Test Outcome:	Failed
Test Duration:	0:00:00.941

Result StackTrace:	
at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpEntityTypeGeneratorTest.<>c.<Navigation_properties>b__0_1(ScaffoldedModel code) in D:\VladikKek\EntityFrameworkCore-master\test\EFCore.Design.Tests\Scaffolding\Internal\CSharpEntityTypeGeneratorTest.cs:line 61
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ModelCodeGeneratorTestBase.Test(Action`1 buildModel, ModelCodeGenerationOptions options, Action`1 assertScaffold, Action`1 assertModel) in D:\VladikKek\EntityFrameworkCore-master\test\EFCore.Design.Tests\Scaffolding\Internal\ModelCodeGeneratorTestBase.cs:line 71
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpEntityTypeGeneratorTest.Navigation_properties() in D:\VladikKek\EntityFrameworkCore-master\test\EFCore.Design.Tests\Scaffolding\Internal\CSharpEntityTypeGeneratorTest.cs:line 14
Result Message:	
Assert.Equal() Failure
                       ↓ (pos 13)
Expected: using System;\nusing System.Collections.Generic;\nusing ···
Actual:   using System;\r\nusing System.Collections.Generic;\r\nusin···
                       ↑ (pos 13)

```

### Steps to reproduce

Run following test
Namespace:`Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpEntityTypeGeneratorTest`
Method: `Navigation_properties()`

### Further technical details 
EF Core version:  3.0.0-dev
Database Provider: Don't know how to find
Operating system: Windows 10 Educational
Version: 1703
OS.Build: 15063.1746
IDE: (e.g. Visual Studio 2019 16.0.3)

**Comment by ajcvickers** [comment] 2019-05-06 18:47
@MarinaRybalko We're not 100% sure why you are hitting this. Did you clone from git on one operating system, but then run on another?

Either way, assigning to @bricelam to make the tests more robust in this case.

**Comment by AndriySvyryd** [comment] 2020-03-20 04:30
Likely duplicate of https://github.com/dotnet/efcore/issues/19964

**Comment by smitpatel** [comment] 2020-08-27 22:55
The test is working correctly in current branch.

**Closed by smitpatel** 2020-08-27 22:55 UTC
Labels: area-test, customer-reported, punted-for-3.1, type-bug, verify-fixed
