### ISSUE TITLE
LINQ Expression cannot correctly translate string.Contains method call

### ISSUE THREAD

**Issue by sgjsakura** [dotnet/efcore#5927] opened 2016-07-01 04:33 UTC
### Steps to reproduce

Building up a query like the following:

``` C#
var result = from i in myDatabase.myTable where i.Name.Contains("%") select i;
```
### The issue

The `%`char in the linq expression is not escaped and directly passed to the `LIKE` expression, for the above example, the query will returns all rows in the table. 

The % may also comes from a user input variable. The actual meaning of the above code should be "find any item whose name contains a percent sign". The user should not know the special effect of % in SQL expression, also the author of the LINQ expression should not have to take special handling for this sign.

I think LINQ translator should make a preprocess for percent sign, or maybe using `CHARINDEX` function instead of `LIKE` will be better.
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 10 Enterprise
Visual Studio version: Visual Studio 2015 Update 3
Other details about my project setup:

**Comment by sgjsakura** [comment] 2016-07-01 05:23
Seems related with #474

**Comment by rowanmiller** [comment] 2016-07-05 18:15
> The % may also comes from a user input variable.

If the string came from something other than an inline constant (i.e. a variable etc.) then it would get parameterized.

We shoudl still fix this though.

**Comment by sgjsakura** [comment] 2016-07-06 04:58
@rowanmiller In the current version the following code
```C#
var result = from i in myDatabase.myTable where i.Name.Contains(serachWord) select i;
```
still not works in my project if `serachWord` contains `%` sign. It seems that parameterized is not working correctly.

**Comment by gdoron** [comment] 2016-07-06 07:30
@sgjsakura can you share the generated SQL?

**Comment by sgjsakura** [comment] 2016-07-06 11:03
@gdoron Here is the generated SQL output to debug view:
```SQL
      Executed DbCommand (20ms) [Parameters=[@__word_0='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SELECT [i].[Id], [i].[Content]
      FROM [Datas] AS [i]
      WHERE [i].[Content] LIKE (N'%' + @__word_0) + N'%'
```
Thus the special char in parameters (e.g. '%' or '_') still works!

**Comment by maumar** [comment] 2016-07-22 22:58
closing this as it's a duplicate of #474 as @sgjsakura pointed out. Moved the original bug from backlog to 1.1.0 milestone and assigned myself.

**Closed by maumar** 2016-07-22 22:58 UTC
