### ISSUE TITLE
Execution order of deletes on related tables

### ISSUE THREAD

**Issue by danielSt-dev** [dotnet/efcore#33990] opened 2024-06-14 09:58 UTC
## Ask a question

Hi,

I have the following db model:
<img width="353" alt="image" src="https://github.com/dotnet/efcore/assets/58980796/4ac6ddf3-6833-4edb-8dc8-f2f6c88f1f31">

then I generated via scaffold db context the ef core model:
```C#
 modelBuilder.Entity<Account>(entity =>
 {
     entity.HasKey(e => e.Id).HasName("PK__TAccount__3214EC077C4BF9BF");

     entity.ToTable("TAccount", tb =>
         {
             tb.HasTrigger("D_Trig_TAccount");
             tb.HasTrigger("U_Trig_TAccount");
         });

     entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
     entity.Property(e => e.CreatedBy)
         .IsRequired()
         .HasMaxLength(200);
     entity.Property(e => e.DeletedBy).HasMaxLength(200);
     entity.Property(e => e.Description).HasMaxLength(200);
     entity.Property(e => e.Email)
         .HasMaxLength(200)
         .HasColumnName("EMail");
     entity.Property(e => e.Firstname).HasMaxLength(200);
     entity.Property(e => e.Lastname).HasMaxLength(200);
     entity.Property(e => e.ModifiedAt).HasDefaultValueSql("(getdate())");
     entity.Property(e => e.ModifiedBy).HasMaxLength(200);
     entity.Property(e => e.ObjectId).HasDefaultValueSql("(newid())");
     entity.Property(e => e.Type)
         .IsRequired()
         .HasMaxLength(200);
     entity.Property(e => e.Username)
         .IsRequired()
         .HasMaxLength(200);
 });

 modelBuilder.Entity<AccountSetting>(entity =>
 {
     entity.HasKey(e => e.Id).HasName("PK__TAccount__3214EC075AEC97F6");

     entity.ToTable("TAccountSetting", tb =>
         {
             tb.HasTrigger("D_Trig_TAccountSetting");
             tb.HasTrigger("U_Trig_TAccountSetting");
         });

     entity.Property(e => e.AppName).HasMaxLength(200);
     entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
     entity.Property(e => e.CreatedBy)
         .IsRequired()
         .HasMaxLength(200);
     entity.Property(e => e.DeletedBy).HasMaxLength(200);
     entity.Property(e => e.AccountId).HasColumnName("FK_AccountId");
     entity.Property(e => e.Key)
         .IsRequired()
         .HasMaxLength(200);
     entity.Property(e => e.ModifiedAt).HasDefaultValueSql("(getdate())");
     entity.Property(e => e.ModifiedBy).HasMaxLength(200);
     entity.Property(e => e.ObjectId).HasDefaultValueSql("(newid())");

     entity.HasOne(d => d.Account).WithMany(p => p.AccountSettings)
         .HasForeignKey(d => d.AccountId)
         .OnDelete(DeleteBehavior.ClientSetNull)
         .HasConstraintName("FK_AccountId_AccountSetting");
 });
```

for traceability purpose at db **trigger** level we forbid direct delete queries. 
Delete have to be done with an update:
```SQL
update XXX 
set deletedby = 'username'
where Id = YYY
```
this is on database level because manual operations with DML also works with this restriction.
[edit:
The update trigger copies the entry to seperate history table and then deletes the original entry.
]

So we created an SaveChangesInterceptor that the EntityState.Deleted will be changed to EntityState.Modified and the deletedby will be automatically set.

But now, ef core executes the update statements in "false" order:

```SQL
 SET NOCOUNT ON;
 UPDATE [TAccount] SET [Active] = @p0, [CreatedAt] = @p1, [CreatedBy] = @p2, [DeletedAt] = @p3, [DeletedBy] = @p4, [Description] = @p5, [EMail] = @p6, [Firstname] = @p7, [Lastname] = @p8, [ModifiedAt] = @p9, [ModifiedBy] = @p10, [ObjectId] = @p11, [Type] = @p12, [Username] = @p13
 WHERE [Id] = @p14;
 SELECT @@ROWCOUNT;
 
 UPDATE [TAccountSetting] SET [FK_AccountId] = @p15, [AppName] = @p16, [CreatedAt] = @p17, [CreatedBy] = @p18, [DeletedAt] = @p19, [DeletedBy] = @p20, [Key] = @p21, [ModifiedAt] = @p22, [ModifiedBy] = @p23, [ObjectId] = @p24, [Value] = @p25
 WHERE [Id] = @p26;
 SELECT @@ROWCOUNT;
```
which results in an exception:
_Die DELETE-Anweisung steht in Konflikt mit der REFERENCE-Einschränkung "FK_AccountId_AccountSetting". Der Konflikt trat in der dev-Datenbank, Tabelle "dbo.TAccountSetting", column 'FK_AccountId' auf._

Can I change the execution order to update TAccountSettings before TAccount?

To execute the statements atomic, I don't want call SaveChanges multiple times. 
As an alternative I see a transaction can be used. Am I right?

Do you have other suggestions?

Thanks

### provider and version information

EF Core version: 8.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 8.0
IDE: Visual Studio 2022 17.10.2

**Comment by roji** [comment] 2024-06-14 10:47
@danielSt-dev I'm a bit confused - the FK violation message seems to indicate that the `FK_AccountId` column is being changed, whereas all you want to do is to modify the `deletedby` column, no? I'd first try to understand why `FK_AccountId` is being modified at all - from your description it sounds that this isn't intentional, and may be the result of problematic logic in your interceptor. Once you get EF to generate the actual UPDATE that you want - one that only touched `deletedby` - the ordering of the statements should no longer matter at all.

> To execute the statements atomic, I don't want call SaveChanges multiple times.
> As an alternative I see a transaction can be used. Am I right?

Yes, you can always perform two SaveChanges but put them in an explicit transaction, at which point they're atomic. However, that does mean performing two database roundtrips instead of one.

**Comment by danielSt-dev** [comment] 2024-06-15 06:07
Ah sorry, I forgot something important:
the delete is performed in the update trigger if "deletedby" is set.

So with this update command the triggers will copy the entry to a history tabe for traceability purpose and then deletes the origianal entry.

this is why the delete is executed.

**Comment by roji** [comment] 2024-06-15 07:03
If I understand you correctly, you have a database trigger set up, which actually deletes the row in the database when EF sends an UPDATE statement to set `deletedby` to true. And EF's ordering of statements - which is of course oblivious of your trigger - causes the FK constraint to be violated.

If the above is true, then it would be good to understand why exactly things are set up that way; instead of converting special UPDATEs to DELETEs, why not just have EF send DELETE to the database, and have the trigger in the database copy the row for auditing purposes etc.? This would make everything simpler, and since EF will be aware it's actually doing DELETEs, it will order them appropriately to avoid FK violations.

Otherwise I'm not sure what can be done here... EF's SaveChanges() is very much by design a high-level API, where EF is the one figuring out what needs to be saved to the database and also in what order; you're undermining that by changing the meaning of the operations (a seemingly harmless UPDATE actually becomes a DELETE in the database etc.). If you can't change the way things work, then you'll need to split the save into two SaveChanges()./

**Comment by danielSt-dev** [comment] 2024-06-15 08:13
First, thanks for your support.

Well, we make an update because to track who deletes the entry. And with who I mean an logical user which is not the user who connects to the database.
With a classic delete statement this information can not be passed.

And to track this information too, if a developer performs DML direct via SQL we have set up this environment.

So If the execution order can not be changed, I will try  transaction with multiple  .SaveChanges() calls.

**Comment by roji** [comment] 2024-06-15 08:38
Understood, thanks for the details. I'm going to go ahead and close this as I don't think anything can be done on the EF side to support this kind of scenario.

**Closed by roji** 2024-06-15 08:38 UTC
Labels: customer-reported, area-save-changes, area-interception
