### ISSUE TITLE
The specified deps.json does not exist

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#24258] opened 2021-02-24 16:16 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/The-specified-depsjson-does-not-exist/1332770)._

---
[severity:It's more difficult to complete my work]
This is still a problem in VS Professional 16.8.4 

Run any migration function in Package manager Console.
Has never worked on my Lenovo P43 but works using CLI command interface
File exists in Bin/Debug/net5.0 folder

---
#### Feedback Bot on 2/7/2021, 07:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2021-02-24 16:31
Duplicate of #16386

**Closed** 2022-10-16 19:25 UTC
Labels: customer-reported
