### ISSUE TITLE
EF Core Cosmos DB - collection storing multiple document types

### ISSUE THREAD

**Issue by andreicroitoriu** [dotnet/efcore#25181] opened 2021-07-01 11:47 UTC
Hi all,
Posting here because I can't sort out what am I getting wrong after a few days of debugging/reading code/googling.
I have a Cosmos DB database and one collection in it stores 2 types of documents: `DocumentA` and  `DocumentB` - both derived from a base class let's call it `DocumentBase`. My EF Core context class looks something like this:
```C#
    public class MyContext : DbContext
    {
        public MyContext(DbContextOptions<MyContext> options) : base(options)
        {
        }

        public  DbSet<DocumentA> DocsA{ get; set; }
        public DbSet<DocumentB> DocsB { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {                
            var converter = new GuidToStringConverter();            

            modelBuilder.Entity<DocumentA>().ToContainer("AandB");                
            modelBuilder.Entity<DocumentA>()
                .Property(x => x.Id)
                .HasConversion(converter);
            modelBuilder.Entity<DocumentB>().ToContainer("AandB");                
            modelBuilder.Entity<DocumentB>()
                .Property(x => x.Id)
                .HasConversion(converter);
        }
   }
```

this was the only way I could get it to work with multiple document types in same collection.
To access data I inject my `MyContext` in the service class and based on what I am looking for i query something like:

`DocumentA docA = _db.DocsA.OfType<DocumentA>().SingleOrDefault(x => x.Id.Equals(myId));`

So far things seem to work fine, but I'm running into issues when performing updates (especially when I'm running my code under some higher load and things start running in parallel). The issue I'm facing is that my update code looks something like:

``` C#
DocumentA docA = _db.DocsA.OfType<DocumentA>().SingleOrDefault(x => x.Id.Equals(myId));
docA.Property2 = "new value";
docA.Property3 = "some new value";
await _db.SaveChangesAsync();
```

In some case (NOT ALL) some of the other properties in `docA` get lost (although they are not touched/set in the update method) - so from whatever value they had are set to null (for strings) and 0 for int...
Is this a case of Cosmos DB not supporting partial updates (although as mentioned in many cases the values the values are not lost). What am I missing/not paying attention to as I am out of ideas at the moment.

Thank you in advance for your assistance!
Andrei

**Comment by AndriySvyryd** [comment] 2021-07-06 22:20
I am not able to repro the behavior you are seing. I tried this:
``` C#
var myId = Guid.NewGuid();
await using (var context = new MyContext(options))
{
    await context.Database.EnsureCreatedAsync();

    var document = new DocumentA
    {
        Id = myId,
        Property1 = "Value1",
        Property2 = "Value2",
        Property3 = "Value3"
    };

    context.Add(document);

    await context.SaveChangesAsync();
}

await using (var context = new MyContext(options))
{
    var docA = context.DocsA.OfType<DocumentA>().Single(x => x.Id.Equals(myId));
    docA.Property2 = "new value";
    docA.Property3 = "some new value";
    await context.SaveChangesAsync();
}

await using (var context = new MyContext(options))
{
    var docA = context.DocsA.OfType<DocumentA>().Single(x => x.Id.Equals(myId));

    Assert.Equal("Value1", docA.Property1);
    Assert.Equal("new value", docA.Property2);
    Assert.Equal("some new value", docA.Property3);
}
```

With these entity types:
``` C#
private class DocumentBase
{
    public Guid Id { get; set; }
}

private class DocumentA : DocumentBase
{
    public string Property1 { get; set; }
    public string Property2 { get; set; }
    public string Property3 { get; set; }
}

private class DocumentB : DocumentBase
{
    public string Property1 { get; set; }
    public string Property2 { get; set; }
    public string Property3 { get; set; }
}
```

Post``` C#
private class DocumentBase
{
    public Guid Id { get; set; }
}

private class DocumentA : DocumentBase
{
    public string Property1 { get; set; }
    public string Property2 { get; set; }
    public string Property3 { get; set; }
}

private class DocumentB : DocumentBase
{
    public string Property1 { get; set; }
    public string Property2 { get; set; }
    public string Property3 { get; set; }
}
```

Please post some code that consistently fails for us to investigate further.

**Comment by ajcvickers** [comment] 2021-07-13 16:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:38 UTC
Labels: closed-could-not-reproduce, customer-reported
