### ISSUE TITLE
Owned Collections as Many to Many Relationship

### ISSUE THREAD

**Issue by todd-skelton** [dotnet/efcore#14145] opened 2018-12-11 20:31 UTC
I would like to have owned collections for two classes that share a table that creates a many-to-many relationship. Is there a way to map the intermediate entity as an owned collection on both entities?

```
Unhandled Exception: System.InvalidOperationException: Cannot use table 'Accounts' for entity type 'User.Accounts#Account' since it is being used for entity type 'Application.Accounts#Account' and there is no relationship between their primary keys.
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IReadOnlyList`1 mappedTypes, String tableName)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.EntryWithoutDetectChanges[TEntity](TEntity entity)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
```

### Steps to reproduce
```c#
    public class User
    {
        public Guid Id { get; set; }
        public string Username { get; set; }
        public ICollection<Account> Accounts { get; set; }
    }

    public class Application
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ICollection<Account> Accounts { get; set; }
    }

    public class Account
    {
        public Guid UserId { get; private set; }
        public Guid ApplicationId { get; private set; }
    }

    public class SecurityDbContext : DbContext
    {
        public SecurityDbContext(DbContextOptions options) : base(options)
        {
        }

        public DbSet<Application> Applications { get; set; }
        public DbSet<User> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Application>(builder =>
            {
                builder.OwnsMany(e => e.Accounts, o =>
                {
                    o.ToTable("Accounts");
                    o.HasForeignKey(e => e.ApplicationId);
                    o.HasKey(e => new { e.UserId, e.ApplicationId });
                });
            });

            modelBuilder.Entity<User>(builder =>
            {
                builder.OwnsMany(e => e.Accounts, o =>
                {
                    o.ToTable("Accounts");
                    o.HasForeignKey(e => e.UserId);
                    o.HasKey(e => new { e.UserId, e.ApplicationId });
                });
            });
        }
    }
```

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.3

**Comment by ajcvickers** [comment] 2018-12-13 01:33
@xKloc Can you give us some insights on why you want to use owned collections for this?

**Comment by xKloc** [comment] 2018-12-13 03:33
The main goal was to use nested owned types and collections on my two aggregates (user and application), so I would load the entire object graph without having to chain all the includes. I tried to use two different types mapped to the same table, but I run into the same issue. I have to create a one-to-one relationship between the two types, and I can't do that because they are owned entities.

I just created some extension methods that perform all the includes for now.

**Comment by AndriySvyryd** [comment] 2019-09-18 19:31
This is mainly a duplicate of #2953

**Comment by pantonis** [comment] 2021-02-09 10:28
@AndriySvyryd @ajcvickers any update on this. I run into a similar case and I cannot define a many-to-many between two tables when the join table is a ValueObject (ownsmany)

**Comment by AndriySvyryd** [comment] 2021-02-09 18:39
@pantonis We aren't planning to support this as it doesn't match owned entities semantics (they can only have one owner).

**Comment by xKloc** [comment] 2021-02-09 18:45
@pantonis, as a work around, I created a view for one of my value objects linking back to the same table. Any inserts have to come from the owner, but reads can come from both.

**Closed** 2022-10-16 13:43 UTC
Labels: customer-reported
