### ISSUE TITLE
Define temporal tables by data annotation

### ISSUE THREAD

**Issue by LukasKubicek** [dotnet/efcore#29431] opened 2022-10-26 12:35 UTC
I prefer to define my model by data annotations on classes and properties instead of fluent api in model builder.
It seems that temporal tables can only be defined by fluent api.

My suggestion:
add something like:

```
[Temporal]
class Person
```

**Comment by ajcvickers** [comment] 2022-10-26 15:13
Duplicate of #25743.

**Closed by ajcvickers** 2022-10-26 15:13 UTC
Labels: type-enhancement, customer-reported
