### ISSUE TITLE
Reverse Engineering issue with user permissions

### ISSUE THREAD

**Issue by boppercr** [dotnet/efcore#26716] opened 2021-11-16 16:42 UTC
Hi,
I know the Reverse Engineering isn't the absolute focus of the EF Core project, but still, I have an issue with it. The problem comes from the user that is used for the scaffold. We have a big database that we want to separate into smaller databases in the future. Right now, the solution we found to make it more secure is to create users with limited access to scaffold and for the app to use. Up until a little while, there was no problem, but now, we get an exception on the scaffold command saying "System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.String'.". Having searched for the problem using the verbose parameter, I found that the issue arises when looking for Foreign Key Constraints. I also tried to run the SQL command directly on the server, and I realize that a couple of informations go missing since they come from a table that isn't wanted in the scaffold. The missing informations are from the "principal_table_schema", "principal_table_name" and "referenced_column_name". When I add "View Definition" permissions to the user on the referenced schema/tables, the information is available, but then the tables and schemas become part of the scaffold. 

I realize that a possibility would be to specify in the scaffold command the tables that I want, but I feel like there should be a better management there if the table aren't available to the user. 

Let me know if anything wasn't clear or if you have further questions.

Thanks in advance for your time.

**Comment by ErikEJ** [comment] 2021-11-16 16:48
Duplicate of #22842

A check for this (and the ability easily select tables to scaffold) is available today in EF Core Power Tools.

I plan to implement a warning for this in EF Core  7 - https://github.com/dotnet/efcore/issues/22842#issuecomment-701168538

**Comment by ajcvickers** [comment] 2021-11-16 21:02
@boppercr Your approach should work. The issue you are seeing looks very much like #23359, which is fixed in EF Core 6.0. If you're not already, then can you try with 6.0? If you're still seeing issues, then a database schema and definition of the permissions would be very useful so that we can investigate.

@ErikEJ I don't think this same scenario as addressed by #22842.

**Comment by boppercr** [comment] 2021-11-18 15:54
I can't try 6.0 at the moment, but I'll keep my eyes opened for that. I managed to do what I had to, but I felt like it should be known in case it was an unwanted behaviour. 

Thanks for the help.

**Closed** 2022-10-16 20:14 UTC
Labels: closed-could-not-reproduce, customer-reported
