### ISSUE TITLE
sqlite + ef core 

### ISSUE THREAD

**Issue by NiubilityOptimus** [dotnet/efcore#26991] opened 2021-12-13 15:11 UTC
SqliteException: SQLite Error 19: 'NOT NULL constraint failed

After setting the composite primary key in the sqlite table through ef core, the value cannot be inserted for the composite primary key

**Comment by ajcvickers** [comment] 2021-12-13 20:40
This issue is lacking enough information for us to be able to effectively triage it. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by NiubilityOptimus** [comment] 2021-12-13 20:40
Dear Sir or Miss.
This is an e-mail from Johnnie' QQ Mail.Thank you for your E-mail.I apologize that I am unable to respond to you immediately . I will get back to you as soon as I return.

**Comment by ajcvickers** [comment] 2022-01-11 12:19
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by NiubilityOptimus** [comment] 2022-01-11 12:19
Dear Sir or Miss.
This is an e-mail from Johnnie' QQ Mail.Thank you for your E-mail.I apologize that I am unable to respond to you immediately . I will get back to you as soon as I return.

**Comment by NiubilityOptimus** [comment] 2022-10-16 20:19
Dear Sir or Miss.
This is an e-mail from Johnnie' QQ Mail.Thank you for your E-mail.I apologize that I am unable to respond to you immediately . I will get back to you as soon as I return.

**Closed** 2022-10-16 20:19 UTC
Labels: closed-could-not-reproduce, customer-reported
