### ISSUE TITLE
preview8 join giving not implemented 

### ISSUE THREAD

**Issue by dotnetshadow** [dotnet/efcore#17176] opened 2019-08-15 12:52 UTC
When upgrading from preview5 to preview8 the following query throws
``"The method or operation is not implemented."``

The following query taken from:
https://github.com/KalikoCMS/KalikoCMS.NextGen/blob/netcore3.0-experimental/KalikoCMS.Legacy/Data/Repositories/LegacyContentRepository.cs#L35

```cs
var nodes = (from content in _context.Pages
                         join contentLanguage in _context.PageInstances.Where(x => x.DeletedDate == null && (x.Status == ContentStatus.Published || (x.Status == ContentStatus.WorkingCopy && x.CurrentVersion == 0)))
                on content.PageId equals contentLanguage.PageId into grouped
                orderby content.TreeLevel
                select new ContentNode
                {
                    ContentId = content.PageId,
                    SortOrder = content.SortOrder,
                    TreeLevel = content.TreeLevel,
                    ParentId = content.ParentId,
                    ContentTypeId = ToGuid(content.PageTypeId),
                    ContentProviderId = PageContentProvider.UniqueId,
                    Languages = (from contentLanguage in grouped
                        select new LanguageNode
                        {
                            ContentLanguageId = contentLanguage.PageInstanceId,
                            ContentName = contentLanguage.PageName,
                            ChildSortOrder = contentLanguage.ChildSortOrder,
                            StopPublish = contentLanguage.StopPublish,
                            UpdateDate = contentLanguage.UpdateDate,
                            ChildSortDirection = contentLanguage.ChildSortDirection,
                            Status = contentLanguage.Status,
                            Author = contentLanguage.Author,
                            StartPublish = contentLanguage.StartPublish,
                            CreatedDate = contentLanguage.CreatedDate,
                            VisibleInSitemap = contentLanguage.VisibleInSitemap,
                            CurrentVersion = contentLanguage.CurrentVersion,
                            UrlSegment = contentLanguage.PageUrl,
                            VisibleInMenu = contentLanguage.VisibleInMenu,
                            LanguageId = contentLanguage.LanguageId
                        }).ToList()
                }).ToList();
```

It's saying that the GroupJoin can't be translated?
If I add `.AsEnumerable` to L35 then it works, because it's evaluating locally

I'm guessing the query needs to be rewritten, but not sure how it should look?

### Exception message:
`"The method or operation is not implemented."`
```
Stack trace:
"   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateGroupJoin(ShapedQueryExpression outer, ShapedQueryExpression inner, LambdaExpression outerKeySelector, LambdaExpression innerKeySelector, LambdaExpression resultSelector)\r\n   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)\r\n   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at KalikoCMS.Legacy.Data.Repositories.LegacyContentRepository.GetContentNodes() in D:\\Programming\\Projects\\Libraries\\KalikoCMS.NextGen\\KalikoCMS.NextGen\\KalikoCMS.Legacy\\Data\\Repositories\\LegacyContentRepository.cs:line 35\r\n   at KalikoCMS.Services.Content.ContentIndexService.Initialize() in D:\\Programming\\Projects\\Libraries\\KalikoCMS.NextGen\\KalikoCMS.NextGen\\KalikoCMS\\Services\\Content\\ContentIndexService.cs:line 30\r\n   at KalikoCMS.Services.Initialization.InitializationService.Initialize() in D:\\Programming\\Projects\\Libraries\\KalikoCMS.NextGen\\KalikoCMS.NextGen\\KalikoCMS\\Services\\Initialization\\InitializationService.cs:line 45"
```

### Steps to reproduce

1. Download the project
    https://github.com/KalikoCMS/KalikoCMS.NextGen/tree/netcore3.0-experimental
    Change the EF core 3.0 reference from preview 5 to 8 in KalioCMS.Legacy and KalikoCMS.Data.SqlServer projects

### Further technical details
EF Core version: 3.0 preview8
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Visual Studio 2019 16.2 preview 2

**Comment by smitpatel** [comment] 2019-08-15 14:52
Client side group join. This query cannot be translated to SQL directly. Adding AsEnumerable should be good way since it does not affect how much data is transferred from server.

**Comment by dotnetshadow** [comment] 2019-08-15 23:10
Thanks for confirming, much appreciated.

Just for my understanding, this seems like a join that could be handled in the server. 

1. Why didn't this translate on the server?
2. What causes it to think it should evaluate client side?

**Comment by smitpatel** [comment] 2019-08-15 23:11
There is no SQL equivalent of GroupJoin.

**Comment by dotnetshadow** [comment] 2019-08-15 23:30
Cheers, thanks for clearing it up.

I was thinking perhaps i could of used a navigational property instead to get around the issue.

**Comment by coderfox** [comment] 2019-08-31 08:21
I wonder how would I implement a *left join* in EF Core 3.0? As `GroupJoin` requires client-side evaluation and is disabled in 3.0, and `Join` is *inner join*, while the new `LeftJoin` is internal, currently I cannot figure out any approaches to perform a *left join*.

**Comment by smitpatel** [comment] 2019-09-01 05:22
@coderfox - GroupJoin-DefaultIfEmpty-SelectMany is LINQ's way of writing Left join
e.g.
```C#
from c in cs
join o in os on c.CustomerID equals o.CustomerID into grouping
from o in grouping.DefaultIfEmpty()
select { c, o }
```
This generates Customers LEFT JOIN Orders in database.

**Comment by dotnetshadow** [comment] 2019-09-01 05:28
@smitpatel and that would translate obviously to client side evaluation?

**Comment by coderfox** [comment] 2019-09-01 05:46
@smitpatel Thanks for your instruction, your code works, but how can I use the Fluent API to perform left join? The following three versions of the code does not work.

```csharp
var d2 = await _dbContext.UserDataType
    .GroupJoin(_dbContext.UserData,
        d => new { d.Id, UserId = _userManager.GetUserId(User) },
        v => new { v.DataType.Id, v.UserId },
        (DataType, DataValues) => new { DataType, DataValue = DataValues.DefaultIfEmpty() })
    .ToArrayAsync();
```

It throws:

```console
InvalidOperationException: Processing of the LINQ expression 'GroupJoin<UserDataType, UserData, <>f__AnonymousType5<int, string>, <>f__AnonymousType6<UserDataType, IEnumerable<UserData>>>(
outer: DbSet<UserDataType>, 
inner: DbSet<UserData>, 
outerKeySelector: (d) => new { 
Id = d.Id, 
UserId = (Unhandled parameter: __GetUserId_0)
}, 
innerKeySelector: (v) => new { 
Id = v.DataType.Id, 
UserId = v.UserId
}, 
resultSelector: (DataType, DataValues) => new { 
DataType = DataType, 
DataValue = DefaultIfEmpty<UserData>(DataValues)
})' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
```

```csharp
var d2 = await _dbContext.UserDataType
    .GroupJoin(_dbContext.UserData,
        d => new { d.Id, UserId = _userManager.GetUserId(User) },
        v => new { v.DataType.Id, v.UserId },
        (DataType, DataValues) => new { DataType, DataValues })
    .SelectMany(r => r.DataValues.DefaultIfEmpty(),
    (DataType, DataValue) => new { DataType, DataValue })
    .ToArrayAsync();
```

It throws:

```console
InvalidOperationException: variable 'DataValues' of type 'System.Collections.Generic.IEnumerable`1[mscfreshman.Data.UserData]' referenced from scope '', but it is not defined
```

```csharp
var d2 = await _dbContext.UserDataType
    .GroupJoin(_dbContext.UserData,
        d => new { d.Id, UserId = _userManager.GetUserId(User) },
        v => new { v.DataType.Id, v.UserId },
        (DataType, DataValues) => new { DataType, DataValue = DataValues.SingleOrDefault() })
    .ToArrayAsync();
```

It also throws `InvalidOperationException`.

**Comment by smitpatel** [comment] 2019-09-01 16:28
@dotnetshadow - that would translate to 
```SQL
Select c.*, o.*
FROM Customers AS c
LEFT JOIN Orders AS o ON c.CustomerID = o.CustomerID
```
If you write a proper equivalent of LEFT JOIN on client side, we generate a left join. Not all variations of GroupJoin-DefaultIfEmpty-SelectMany are left join. LINQ has a lot more range variables in the scope than what LEFT JOIN could allow. So if you do it incorrectly, it is client evaluation. You can have server side left join query if you write it correctly. We have 100s of test verifying that.

**Comment by smitpatel** [comment] 2020-03-16 20:31
Duplicate of #19930

**Closed** 2022-10-16 14:36 UTC
Labels: customer-reported
