### ISSUE TITLE
Custom Migrations History Table does not work from `ConfigureServices()`  method

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/efcore#15785] opened 2019-05-23 07:14 UTC
[Custom Migrations History Table](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/history-table#schema-and-table-name) document says that:

> You can change the schema and table name using the MigrationsHistoryTable() method in OnConfiguring() (or ConfigureServices() on ASP.NET Core). 

But it does not work from `ConfigureServices()` method in Startup class. It only works from `OnConfiguring()`. Please take a look on it!

What I have tried is:

            services.AddDbContext<TanvirArjelDbContext>(options =>
            {
                options.UseSqlServer(connectionString, builder =>
                {
                    builder.EnableRetryOnFailure(3, TimeSpan.FromSeconds(10), null);
                    builder.MigrationsAssembly("TanvirArjel.Infrastructure.Data");
                    builder.MigrationsHistoryTable("__EFCoreMigrationsHistory", schema: "_Migration"); // Here it is
                });

                options.ConfigureWarnings(warnings => warnings.Throw(RelationalEventId.QueryClientEvaluationWarning));
            });

**Comment by ajcvickers** [comment] 2019-05-27 19:28
@TanvirArjel I have not been able to reproduce this--my code and output from Migrations is below. Can you post a small, runnable project/solution or complete code listing (like below) that demonstrates the issue you are seeing.

```C#
public class Blog
{
    public int Id { get; set; }
}

public class BloggingContext : DbContext
{
    public BloggingContext(DbContextOptions options) : base(options)
    {
    }

    public DbSet<Blog> Blogs { get; set; }
}

public class DbContextFactory : IDesignTimeDbContextFactory<BloggingContext>
{
    public BloggingContext CreateDbContext(string[] args) 
        => Program.CreateServiceProvider().CreateScope().ServiceProvider.GetService<BloggingContext>();
}

public class Program
{
    public static void Main()
    {
        var provider = CreateServiceProvider();

        using (var scope = provider.CreateScope())
        {
            var context = scope.ServiceProvider.GetService<BloggingContext>();
            // context.Database.EnsureDeleted();
            // context.Database.EnsureCreated();
        }
    }

    public static ServiceProvider CreateServiceProvider()
    {
        var services = new ServiceCollection();

        services.AddDbContext<BloggingContext>(options =>
        {
            options.UseSqlServer(
                @"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0",
                builder =>
                {
                    builder.EnableRetryOnFailure(3, TimeSpan.FromSeconds(10), null);
                    //builder.MigrationsAssembly("TanvirArjel.Infrastructure.Data");
                    builder.MigrationsHistoryTable("__EFCoreMigrationsHistory", schema: "_Migration"); // Here it is
                });

            options.ConfigureWarnings(warnings => warnings.Throw(RelationalEventId.QueryClientEvaluationWarning));
        });

        var provider = services.BuildServiceProvider();
        return provider;
    }
}
```
```
C:\Stuff\TwoTwo\TwoTwo>dotnet ef database update --verbose
Using project 'C:\Stuff\TwoTwo\TwoTwo\TwoTwo.csproj'.
Using startup project 'C:\Stuff\TwoTwo\TwoTwo\TwoTwo.csproj'.
Writing 'C:\Stuff\TwoTwo\TwoTwo\obj\TwoTwo.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Arthur\AppData\Local\Temp\tmp550E.tmp /verbosity:quiet /nologo C:\Stuff\TwoTwo\TwoTwo\TwoTwo.csproj
Writing 'C:\Stuff\TwoTwo\TwoTwo\obj\TwoTwo.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Arthur\AppData\Local\Temp\tmp57A0.tmp /verbosity:quiet /nologo C:\Stuff\TwoTwo\TwoTwo\TwoTwo.csproj
dotnet build C:\Stuff\TwoTwo\TwoTwo\TwoTwo.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.00
dotnet exec --depsfile C:\Stuff\TwoTwo\TwoTwo\bin\Debug\netcoreapp2.2\TwoTwo.deps.json --additionalprobingpath C:\Users\Arthur\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\Stuff\TwoTwo\TwoTwo\bin\Debug\netcoreapp2.2\TwoTwo.runtimeconfig.json "C:\Program Files\dotnet\sdk\2.2.203\DotnetTools\d
otnet-ef\2.2.4\tools\netcoreapp2.2\any\tools\netcoreapp2.0\any\ef.dll" database update --assembly C:\Stuff\TwoTwo\TwoTwo\bin\Debug\netcoreapp2.2\TwoTwo.dll --startup-assembly C:\Stuff\TwoTwo\TwoTwo\bin\Debug\netcoreapp2.2\TwoTwo.dll --project-dir C:\Stuff\TwoTwo\TwoTwo\ --language C# --working-dir C:\Stuff\TwoTwo\TwoTwo --verbose --root-namespace TwoTwo
Using assembly 'TwoTwo'.
Using startup assembly 'TwoTwo'.
Using application base 'C:\Stuff\TwoTwo\TwoTwo\bin\Debug\netcoreapp2.2'.
Using working directory 'C:\Stuff\TwoTwo\TwoTwo'.
Using root namespace 'TwoTwo'.
Using project directory 'C:\Stuff\TwoTwo\TwoTwo\'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'DbContextFactory'.
Found DbContext 'BloggingContext'.
Finding application service provider...
Finding IWebHost accessor...
No CreateWebHostBuilder(string[]) method was found on type 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'DbContextFactory'.
Using context 'BloggingContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'TwoTwo'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'TwoTwo'...
No design-time services were found.
Executed DbCommand (185ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
CREATE DATABASE [Test];
Executed DbCommand (41ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
IF SERVERPROPERTY('EngineEdition') <> 5
BEGIN
    ALTER DATABASE [Test] SET READ_COMMITTED_SNAPSHOT ON;
END;
Executed DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
IF SCHEMA_ID(N'_Migration') IS NULL EXEC(N'CREATE SCHEMA [_Migration];');
CREATE TABLE [_Migration].[__EFCoreMigrationsHistory] (
    [MigrationId] nvarchar(150) NOT NULL,
    [ProductVersion] nvarchar(32) NOT NULL,
    CONSTRAINT [PK___EFCoreMigrationsHistory] PRIMARY KEY ([MigrationId])
);
Executed DbCommand (25ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[_Migration].[__EFCoreMigrationsHistory]');
Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [_Migration].[__EFCoreMigrationsHistory]
ORDER BY [MigrationId];
Applying migration '20190527192236_First'.
Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE [Blogs] (
    [Id] int NOT NULL IDENTITY,
    CONSTRAINT [PK_Blogs] PRIMARY KEY ([Id])
);
Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
INSERT INTO [_Migration].[__EFCoreMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20190527192236_First', N'2.2.4-servicing-10062');
Done.

C:\Stuff\TwoTwo\TwoTwo>
```

**Comment by TanvirArjel** [comment] 2019-05-28 04:33
@ajcvickers As MyDbContext is in a different class library, I had to put `builder.MigrationsHistoryTable("__EFCoreMigrationsHistory", schema: "_Migration");` in `DesignTimeDbContextFactory` also as follows:

   public class DesignTimeDbContextFactory : IDesignTimeDbContextFactory<TanvirArjelDbContext>
    {
        public TanvirArjelDbContext CreateDbContext(string[] args)
        {
            var dbContextOptions = DbContextHelper.GetDbContextOptions();
            return new TanvirArjelDbContext(dbContextOptions);
        }
    }

   public static class DbContextHelper
    {
        public static DbContextOptions<TanvirArjelDbContext> GetDbContextOptions()
        {
            IConfiguration configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .Build();


          return new DbContextOptionsBuilder<TanvirArjelDbContext>()
                .UseSqlServer(new SqlConnection(configuration.GetConnectionString("TanvirArjelConnection")), builder =>
                {
                    builder.MigrationsHistoryTable("__EFCoreMigrationsHistory", schema: "_Migration"); // Here it is
                }).Options;

        }
    }

Now its working as expected! But only from `ConfigureServices()` it does not work. Can you explain this behavior please?

**Comment by bricelam** [comment] 2019-05-28 17:42
> Finding application service provider...
> Finding IWebHost accessor...
> No CreateWebHostBuilder(string[]) method was found on type 'Program'.
> No application service provider was found.
> Finding DbContext classes in the project...
> Using DbContext factory 'DbContextFactory'.

It looks like your application services aren't being used at design-time.

**Comment by TanvirArjel** [comment] 2019-05-31 03:21
@bricelam Here is my `Program` and `Startup` classes:

   ```
public class Program
    {
        public static void Main(string[] args)
        {
            CurrentDirectoryHelpers.SetCurrentDirectory();
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Information() // Set the minimun log level
                .Enrich.FromLogContext()
                .WriteTo.File("Logs\\log-.txt", rollingInterval: RollingInterval.Day, retainedFileCountLimit: 7) // this is for logging into file system
                .CreateLogger();

            try
            {
                Log.Information("Starting web host");
                CreateWebHostBuilder(args).Build().Run();
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Host terminated unexpectedly");
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureLogging(logging => logging.ClearProviders())
                .UseSerilog();
    }
```

Configure Service Method of the startup class as follows:

        ```
public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => false;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddIdentityConfiguration(Configuration);

            services.AddDatabaseConfiguration(Configuration);
            services.AddCustomServices(Configuration);
            services.AddAutoMapperConfiguration();

            services.AddRouting(option =>
            {
               option.ConstraintMap["slugify"] = typeof(SlugifyParameterTransformer);
               option.LowercaseUrls = true;
            });

            

            //services.AddDistributedMemoryCache();
            services.AddMemoryCache();
            services.AddResponseCaching();

            services.AddMvc(options =>
            {
                options.Filters.Add(typeof(CustomAuthorizeAttribute));
                options.Conventions.Add(new RouteTokenTransformerConvention(
                    new SlugifyParameterTransformer()));
            }).SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

            services.AddMvc().AddSessionStateTempDataProvider();
            services.AddFluentValidation();

            services.AddSession(options =>
            {
                options.Cookie.Name = "TanvirArjel.Session";
                options.Cookie.HttpOnly = true;
                options.IdleTimeout = TimeSpan.FromDays(10);
            });

            services.AddHealthChecks(); // Registers health checks services


        }
```
And here is the `AddDatabaseConfiguration` extension method:
    ```
public static class DbContextStartupConfiguration
    {
        public static void AddDatabaseConfiguration(this IServiceCollection services, IConfiguration configuration)
        {
            string connectionString = configuration.GetConnectionString("TanvirArjelConnection");
            services.AddDbContext<TanvirArjelDbContext>(options =>
            {
                options.UseSqlServer(connectionString, builder =>
                {
                    builder.EnableRetryOnFailure(3, TimeSpan.FromSeconds(10), null);
                    builder.MigrationsAssembly("TanvirArjel.Infrastructure.Data");
                    builder.MigrationsHistoryTable("__EFCoreMigrationsHistory", schema: "_Migration");
                });

                options.ConfigureWarnings(warnings => warnings.Throw(RelationalEventId.QueryClientEvaluationWarning));
            });
        }
    }
```
Please let me know whats wrong here.

**Comment by ajcvickers** [comment] 2019-06-03 18:55
@TanvirArjel I still am not able to reproduce what you are seeing. Can you post a runnable project/solution that demonstrates this behavior?

**Comment by TanvirArjel** [comment] 2019-06-03 19:15
@ajcvickers Could you please connect me via Skype (My SkypeId: TanvirArjel) so that I can give you access  to my computer and code base so that you can see the behavior on live.

**Comment by ajcvickers** [comment] 2019-06-03 19:18
@TanvirArjel I'm sorry, but I can't so that. You will need to post a repro solution, or you can send it privately if you don't want to post it in public. Either way, it must be something where I can build and reproduce what you are seeing.

**Comment by TanvirArjel** [comment] 2019-06-03 19:20
@ajcvickers Okay! No problem! Let me check what can I do for you.

**Comment by ajcvickers** [comment] 2019-06-10 16:39
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:22 UTC
Labels: closed-could-not-reproduce, customer-reported
