### ISSUE TITLE
The specified deps.json file doesn't exist

### ISSUE THREAD

**Issue by Nizpatrick** [dotnet/efcore#22247] opened 2020-08-26 16:46 UTC
Hi to everyone, I've a big problem with Ef core 3.1.7

When I try to add-migration or update-database the console show me this message: 
- The specified deps.json [...\Desktop\fake\ClassLibrary1\ClassLibrary1\ClassLibrary1.deps.json] does not exist

The file that It try to pick up is located in my bin folder.
Why It look in this location ?

I've found a walk around, but I can't use it so long.
Can You Fix it ?

Thanks !

### Steps to reproduce
- Try Add-Migration or Update-Database in the project that you store file for db.

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE:  Visual Studio 2019 16.6.5
PC: Lenovo ThinkPad

**Comment by ajcvickers** [comment] 2020-08-28 16:44
Possibly duplicate of #21519

**Comment by ajcvickers** [comment] 2020-08-28 19:32
@bricelam Is there a project system issue that we can link to here? (The returning null when we don't expect it that you mentioned.)

**Comment by bricelam** [comment] 2020-08-28 21:39
No public issue as far as I know.

**Comment by Nizpatrick** [comment] 2020-09-01 12:32
I've tried a lot, and I've found a walk around, that let you work. You have to copy all elements under:
 -bin/Debug/netcoreapp/ 
Inside the folder that visual studio says.

However, is only the package manager console, on visual studio that isn't work, if I try via cmd it works.
Is possibile releted to #21519  cause it's only doesn't work on my PC.

But i try to re-install all from IDE to SDK. 
Any Ideas ?

Thanks a lot

**Comment by bricelam** [comment] 2020-09-03 21:19
Try:

1. Closing package manager console
2. Restarting Visual Studio
3. Opening the solution
4. Opening package manager console and trying again. It could be a race condition between NuGet initialization and the project system

**Comment by JeremyLikness** [comment] 2020-09-04 17:25
Tracked by internal (duplicate).

**Comment by Behzadf94** [comment] 2021-11-30 10:23
> Try:
> 
> 1. Closing package manager console
> 2. Restarting Visual Studio
> 3. Opening the solution
> 4. Opening package manager console and trying again. It could be a race condition between NuGet initialization and the project system

I did this steps but I'm getting the below message:
The specified deps.json [D:\Projects\...\bin\Debug\net6.0\ChargeBuilding.deps.json] does not exist

**Comment by patrickwensel** [comment] 2022-01-15 09:59
@JeremyLikness Not sure why you closed this?  You said it was a duplicate but the other ticket does not show us how to fix the issue.  I am using .net 6 and it is happening for me after i had to rename the project and solution files

**Comment by atloZ** [comment] 2022-05-02 14:52
try cli [HELP_LINK](https://www.entityframeworktutorial.net/efcore/entity-framework-core-migration.aspx)
it worked for me from then on

**Comment by ajcvickers** [comment] 2023-03-02 11:58
@DaveCousineau This should be reported on the SDK repo: https://github.com/dotnet/sdk

**Closed by ajcvickers** 2023-03-02 11:58 UTC
Labels: customer-reported
