### ISSUE TITLE
Insert value without overwrite default value

### ISSUE THREAD

**Issue by symphony2014** [dotnet/efcore#3405] opened 2015-10-12 02:29 UTC
Insert value without overwrite default value

**Comment by rowanmiller** [comment] 2015-10-13 18:15
Dupe of https://github.com/aspnet/EntityFramework/issues/3072 (currently being implemented)

**Comment by symphony2014** [comment] 2015-11-01 12:45
Thanks

**Comment by symphony2014** [comment] 2015-11-01 12:46
@rowanmiller  thanks

**Closed** 2022-10-16 09:11 UTC
