### ISSUE TITLE
Navigation Properties Fix-up before SaveChanges(), like EF6

### ISSUE THREAD

**Issue by stevozilik** [dotnet/efcore#23940] opened 2021-01-22 18:01 UTC
## Can EF Core be configured to fix-up navigation properties immediately, as EF 6 does?

When changing relationship(s) via Foreign Keys, EF Core seems to only propagate changes to navigation properties after SaveChanges() 
Explicitly calling ChangeTracker DetectChanges/CascadeChanges/AcceptAllChanges (before SaveChanges) does not help either
We are relying on EF 6 behaviour and consider it logically more correct, navigation properties immediately matching FK values.

### Code example

DB
```C#
class MyContext : DbContext
{
    public MyContext(DbContextOptions<MyContext> options)
        : base(options)
    { }

    public virtual DbSet<Parent> Parents { get; set; }
    public virtual DbSet<Child> Children { get; set; }
}

class Parent
{
    public int ParentId { get; set; }
    public virtual IList<Child> Children { get; set; }
}

class Child
{
    public int ChildId { get; set; }
    public int ParentId { get; set; }
    public virtual Parent Parent { get; set; }
}
```
Repro
```C#
var ob = new DbContextOptionsBuilder<MyContext>();
ob.UseInMemoryDatabase("db");

// generate data
using (var db1 = new MyContext(ob.Options))
{
    var p1 = new Parent();
    var p2 = new Parent();
    db1.Add(p1);
    db1.Add(p2);
    var ch = new Child() { Parent = p1 };
    db1.Add(ch);
    db1.SaveChanges();
}

// manipulation
using (var db2 = new MyContext(ob.Options))
{
    // load data
    var parents = db2.Parents.Include(p => p.Children).ToList();
    var p1 = parents[0];
    var p2 = parents[1];
    var ch = p1.Children.First();

    // this triggers navigation properties Fixup in EF6
    // such that p1.Children goes from 1 > 0
    // p2.Children goes from 0 > 1
    ch.ParentId = p2.ParentId;                   

    // EF Core only applies changes to navigation properties after SaveChanges() is called
    db2.SaveChanges();
}
```

### Provider and version information

EF Core version: 5.0.2
Database provider: Any
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: VS 2019

**Comment by anranruye** [comment] 2021-01-23 02:53
You can use ChangeTrackingProxies to achieve a similar behavior(need to install `Microsoft.EntityFrameworkCore.Proxies` nuget package):
```C#
using System.Collections.ObjectModel;
using System.Linq;
using Microsoft.EntityFrameworkCore;

class Program
{
    static void Main(string[] args)
    {
        //generate data
        using (var db1 = new MyContext())
        {
            db1.Database.EnsureDeleted();
            db1.Database.EnsureCreated();
            var p1 = db1.CreateProxy<Parent>();
            var p2 = db1.CreateProxy<Parent>();
            db1.Add(p1);
            db1.Add(p2);
            var ch = db1.CreateProxy<Child>();
            ch.Parent = p1;
            db1.Add(ch);
            db1.SaveChanges();
        }

        // manipulation
        using (var db2 = new MyContext())
        {
            // load data
            var parents = db2.Parents.Include(p => p.Children).ToList();
            var p1 = parents[0];
            var p2 = parents[1];
            var ch = db2.Children.First();

            // this triggers navigation properties Fixup
            // such that p1.Children goes from 1 > 0
            // p2.Children goes from 0 > 1
            ch.ParentId = p2.ParentId;

            db2.SaveChanges();
        }
    }
}


class MyContext : DbContext
{
    public MyContext()
    { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer("MyConnectionString")
            .UseChangeTrackingProxies();
    }

    public virtual DbSet<Parent> Parents { get; set; }
    public virtual DbSet<Child> Children { get; set; }
}

public class Parent
{
    public virtual int ParentId { get; set; }
    public virtual ObservableCollection<Child> Children { get; set; }
}

public class Child
{
    public virtual int ChildId { get; set; }
    public virtual int ParentId { get; set; }
    public virtual Parent Parent { get; set; }
}
```

**Comment by stevozilik** [comment] 2021-01-24 13:14
Hi @anranruye 

thank you for the working example, I can see this working for some scenarios. However in our case, it would be quite a big refactoring to change all creation to proxies, which is prohibitive in this case. I can imagine many existing customers of EF 6 would feel similar.

Given the functionality is already present (inside SaveChanges) without the proxies, is there no other way of invoking it? 

If not, should this request be considered a feature request to close the gap between EF6 & EF Core?

**Comment by ajcvickers** [comment] 2021-01-25 17:21
@stevozilik I don't believe the behavior is different in EF Core than it was in EF6. In both cases a call to `DetectChanges` is needed before the navigations will be fixed up. I verified with you code that this works on EF Core.

```C#
            ch.ParentId = p2.ParentId;
            
            db2.ChangeTracker.DetectChanges();
```

If this was working without DetectChanges in EF6, then it would be interesting to be able to reproduce that so we can see what EF6 is doing. (EF6 is more aggressive at calling DetectChanges automatically than EF Core is, so it could be related to that, but there's nothing I can see that would trigger DetectChanges in the code you posted.)

**Comment by stevozilik** [comment] 2021-01-26 13:35
@ajcvickers Yes you are correct, the example I posted is in fact working correctly.

It was not working correctly in my real app, because the Child.ParentId property name was not matching the naming convention on connecting FKs and navigation properties (imagine it was called Child.ParentsId), and thus the navigation properties fix-up was not working as expected. After getting to the bottom of this, I was able to use EF fluent API to correctly connect the FK with Navigation properties and it's working as expected. 

Thank you for looking into this, apologies for wasting your time

**Closed** 2022-10-16 19:19 UTC
Labels: closed-no-further-action, customer-reported

**Comment by NoConnection12367** [comment] 2022-11-03 08:50
Hi @ajcvickers,

what is the current status of this issue? Unlike your and @stevozilik comments state, I can not confirm this is working in the current version. When executing the exact code posted above, the relationship fixup is only executed after `SaveChanges `is being called. Also `ChangeTracker.DetectChanges()` does not update the relationships either.

I also created another example of it not working when deleting entities via the contexts method, which should get the context aware of the changes and update the navigation properties:

### Code Example
DB
```
    public class MyContext : DbContext
    {
        public MyContext(DbContextOptions<MyContext> options)
        : base(options)
        { }

        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Child> Childs { get; set; }
    }

    public class Parent
    {
        public int Id { get; set; }

        public virtual IList<Child> Childs { get; set; }
    }

    public class Child
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public virtual Parent Parent { get; set; }
    }
```
Repro
```
var ob = new DbContextOptionsBuilder<MyContext>();
ob.UseInMemoryDatabase("db");

// generate data
using (var db1 = new MyContext(ob.Options))
{
    var p1 = new Parent();
    db1.Parents.Add(p1);

    var ch1 = new Child() { Parent = p1 };
    db1.Childs.Add(ch1);
    db1.SaveChanges();
}

// manipulation
using (var db2 = new MyContext(ob.Options))
{
    // load data
    var p1 = db2.Parents.Include(p => p.Childs).First();
    var p1_local = db2.Parents.Local.First();
    var ch1 = p1.Childs.First();

    Console.WriteLine("Before remove: " + p1.Childs.Count);
    Console.WriteLine("Before remove: " + p1_local.Childs.Count);

    db2.Childs.Remove(ch1);

    Console.WriteLine("After remove: " + p1.Childs.Count);
    Console.WriteLine("After remove: " + p1_local.Childs.Count);

    db2.ChangeTracker.DetectChanges();

    Console.WriteLine("After detect: " + p1.Childs.Count);
    Console.WriteLine("After detect: " + p1_local.Childs.Count);

    // EF Core only applies changes to navigation properties after SaveChanges() is called
    db2.SaveChanges();

    Console.WriteLine("After save: " + p1.Childs.Count);
    Console.WriteLine("After save: " + p1_local.Childs.Count);
}
```

This creates the following output. The navigation property of p1 is not updated after deleting the entity via the dbcontext. Also detectchanges doesn't fix this, only after saving the changes, the properties are updated.
```
Before remove: 1
Before remove: 1
After remove: 1
After remove: 1
After detect: 1
After detect: 1
After save: 0
After save: 0
```
In fact, I would totally expect the observed behavior for p1, as it represents the current state in the database. However in my understanding, the entities in the local collection (p1_local) should be updated to reflect the changes immediately after the child is removed via the context.


Can you confirm this as the expected behavior? When using EF6, saving the changes is definitely not required to update the relationships.

### Provider and version information
EF Core version: 6.0.10
Database provider: SQLite/In-Memory
Target framework: .NET 6.0
Operating system:
IDE: VS 2022

**Comment by DennyWeinberg** [comment] 2023-04-05 15:29
Calling ChangeTracker.DetectChanges() works for me, using Blazor
