### ISSUE TITLE
Does .UseLazyLoadingProxies() not work in XUnitTests?

### ISSUE THREAD

**Issue by bstrother1** [dotnet/efcore#26597] opened 2021-11-09 17:37 UTC
Greetings,
    As the header states, is this a known issue? Might be related to https://github.com/dotnet/efcore/issues/15532

Example:

```c#
    class ExampleContextFactory
    {
        private DbConnection _connection;

        private DbContextOptions<ExampleContext> CreateOptions()
        {
            return new DbContextOptionsBuilder<ExampleContext>()
                .UseLazyLoadingProxies()
                .UseSqlite(_connection).Options;
        }

        public ExampleDbContext CreateContext()
        {
            if (_connection == null)
            {
                _connection = new SqliteConnection("DataSource=:memory:");
                _connection.Open();

                var options = CreateOptions();
                using (var context = new ExampleContext(options))
                {
                    context.Database.EnsureCreated();
                }
            }

            return new ExampleContext(CreateOptions());
        }

        public void Dispose()
        {
            if (_connection != null)
            {
                _connection.Dispose();
                _connection = null;
            }
        }
    }
```

EFCore: 3.1.14 
Microsoft.EntityFrameworkCore.Proxies: 3.1.14

**Comment by ajcvickers** [comment] 2021-11-10 10:19
@bstrother1 I'm not aware of any issues here. If somethin is not working, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate. Also, try updating to a newer version of EF Core.

**Comment by ajcvickers** [comment] 2021-11-18 12:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:13 UTC
Labels: closed-could-not-reproduce, customer-reported
