### ISSUE TITLE
AsNoTracking() before OrderBy() forces client-side evaluation

### ISSUE THREAD

**Issue by sandersaares** [dotnet/efcore#14485] opened 2019-01-22 07:13 UTC
The below example code results in client-side evaluation of the "order by" statement.

```
The LINQ expression 'orderby [x].P.Created asc' could not be translated and will be evaluated locally.'.
```

It is not obvious to me where in the query `AsNoTracking()` is valid but I assume it works like a "flag" so should be valid anywhere. By trying random permutations, I found that I could get rid of the error by:

* Moving it to the very end before ToArray. However, this causes another query translation issue: https://github.com/aspnet/EntityFrameworkCore/issues/14484
* Moving it right in the beginning, after the accessor of both DbSet properties

The latter might be a functioning workaround (so far so good). However, I would expect `AsNoTracking()` to work anywhere in the query.

**Edit**: Okay nope, moving .AsNoTracking() to the beginning will also make .Take() not work.

### Steps to reproduce

Use migrations to generate database.

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Debug;
using System;
using System.Linq;

namespace ConsoleApp14
{
    internal class Program
    {
        public static readonly Guid Parent1Id = new Guid("bcee42c7-ad08-4a43-b9ea-ecb62939666e");
        public static readonly Guid Parent2Id = new Guid("d65de666-7a3c-49bb-90e2-c780d10832aa");
        public static readonly Guid Child1Id = new Guid("5d846ff2-9db8-4a45-a939-3746df161eb4");
        public static readonly Guid Child2Id = new Guid("7dcdc71c-d4c9-4d79-a62a-10e9545f4e21");

        private static void Main(string[] args)
        {
            using (var dc = new DataContext())
            {
                var joined = dc.Parent
                    .GroupJoin(dc.Child, p => p.Id, c => c.ParentId, (parent, children) => new { P = parent, C = children })
                    .AsNoTracking() // This forces client evaluation and throws an exception.
                    .OrderBy(x => x.P.Created)
                    .ToArray();

                Console.WriteLine($"{joined.Length} rows.");
            }
        }
    }

    public class ParentRow
    {
        public Guid Id { get; set; }

        public DateTimeOffset Created { get; set; }
    }

    public class ChildRow
    {
        public Guid Id { get; set; }
        public Guid ParentId { get; set; }

        public DateTimeOffset Created { get; set; }
    }

    public class DataContext : DbContext
    {
        public DbSet<ParentRow> Parent { get; set; }
        public DbSet<ChildRow> Child { get; set; }

        public DataContext()
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.ConfigureWarnings(warnings =>
            {
                warnings.Throw(RelationalEventId.QueryClientEvaluationWarning);
            });

            optionsBuilder.EnableSensitiveDataLogging();
            optionsBuilder.UseLoggerFactory(MyLoggerFactory);

            if (!optionsBuilder.IsConfigured)
                optionsBuilder.UseSqlServer("Server=(local);Database=EFCore_Issue_Repro;Trusted_Connection=True;");
        }

        public static readonly LoggerFactory MyLoggerFactory = new LoggerFactory(new[]
        {
            new DebugLoggerProvider((category, level) => true)
        });

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ParentRow>()
                .HasData(
                    new ParentRow
                    {
                        Id = Program.Parent1Id,
                        Created = DateTimeOffset.UtcNow
                    },
                    new ParentRow
                    {
                        Id = Program.Parent2Id,
                        Created = DateTimeOffset.UtcNow
                    }
                    );

            modelBuilder.Entity<ChildRow>()
                .HasData(
                    new ChildRow
                    {
                        Id = Program.Child1Id,
                        ParentId = Program.Parent1Id,
                        Created = DateTimeOffset.UtcNow
                    },
                    new ChildRow
                    {
                        Id = Program.Child2Id,
                        ParentId = Program.Parent2Id,
                        Created = DateTimeOffset.UtcNow
                    }
                );
        }
    }
}
```

### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1809
IDE: Visual Studio 2017 15.9.5

**Comment by ajcvickers** [comment] 2019-01-22 22:32
This one does repro for me. Tracking log:
```
dbug: Microsoft.EntityFrameworkCore.Query[10104]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      Optimized query model:
      'from ParentRow p in DbSet<ParentRow>
      join ChildRow c in DbSet<ChildRow>
      on [p].Id equals [c].ParentId into children
      order by [p].Created asc
      select new {
          [p],
          [children]
       }'
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      (QueryContext queryContext) => IEnumerable<<>f__AnonymousType0<ParentRow, IEnumerable<ChildRow>>> _InterceptExceptions(
      |__ source: IEnumerable<<>f__AnonymousType0<ParentRow, IEnumerable<ChildRow>>> _TrackEntities(
      |   |__ results: IEnumerable<<>f__AnonymousType0<ParentRow, IEnumerable<ChildRow>>> _Select(
      |   |   |__ source: IEnumerable<TransparentIdentifier<ParentRow, IEnumerable<ChildRow>>> _GroupJoin(
      |   |   |   |__ queryContext: (RelationalQueryContext)queryContext,
      |   |   |   |__ source: IEnumerable<ValueBuffer> _Query(
      |   |   |   |   |__ queryContext: queryContext,
      |   |   |   |   |__ shaperCommandContext: SelectExpression:
      |   |   |   |           SELECT [p].[Id], [p].[Created], [c].[Id], [c].[Created], [c].[ParentId]
      |   |   |   |           FROM [Parent] AS [p]
      |   |   |   |           LEFT JOIN [Child] AS [c] ON [p].[Id] = [c].[ParentId]
      |   |   |   |           ORDER BY [p].[Created], [p].[Id]),
      |   |   |   |__ outerShaper: BufferedOffsetEntityShaper<ParentRow>,
      |   |   |   |__ innerShaper: BufferedOffsetEntityShaper<ChildRow>,
      |   |   |   |__ innerKeySelector: (ChildRow c) => c.ParentId,
      |   |   |   |__ resultSelector: (ParentRow p | IEnumerable<ChildRow> children) => TransparentIdentifier<ParentRow, IEnumerable<ChildRow>> CreateTransparentIdentifier(
      |   |   |       |__ outer: p,
      |   |   |       |__ inner: children)),
      |   |   |__ selector: (TransparentIdentifier<ParentRow, IEnumerable<ChildRow>> t0) => new {
      |   |           t0.Outer,
      |   |           t0.Inner
      |   |        }),
      |   |__ queryContext: queryContext,
      |   |__ entityTrackingInfos: { itemType: ParentRow, itemType: IEnumerable`1 },
      |   |__ entityAccessors: List<Func<<>f__AnonymousType0<ParentRow, IEnumerable<ChildRow>>, object>>
      |       {
      |           Func<<>f__AnonymousType0<ParentRow, IEnumerable<ChildRow>>, ParentRow>,
      |           Func<<>f__AnonymousType0<ParentRow, IEnumerable<ChildRow>>, IEnumerable<ChildRow>>,
      |       }),
      |__ contextType: DataContext,
      |__ logger: DiagnosticsLogger<Query>,
      |__ queryContext: queryContext)
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (85ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [p].[Id], [p].[Created], [c].[Id], [c].[Created], [c].[ParentId]
      FROM [Parent] AS [p]
      LEFT JOIN [Child] AS [c] ON [p].[Id] = [c].[ParentId]
      ORDER BY [p].[Created], [p].[Id]
```
No-tracking log:
```
dbug: Microsoft.EntityFrameworkCore.Query[10104]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      Optimized query model:
      'from <>f__AnonymousType0<ParentRow, IEnumerable<ChildRow>> x in
          from ParentRow p in DbSet<ParentRow>
          join ChildRow c in DbSet<ChildRow>
          on [p].Id equals [c].ParentId into children
          select new {
              [p],
              [children]
           }
      order by [x].P.Created asc
      select [x]'
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'orderby [x].P.Created asc' could not be translated and will be evaluated locally.
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      (QueryContext queryContext) => IEnumerable<<>f__AnonymousType0<ParentRow, IEnumerable<ChildRow>>> _InterceptExceptions(
      |__ source: IOrderedEnumerable<<>f__AnonymousType0<ParentRow, IEnumerable<ChildRow>>> _OrderBy(
      |   |__ source: IEnumerable<<>f__AnonymousType0<ParentRow, IEnumerable<ChildRow>>> _Select(
      |   |   |__ source: IEnumerable<TransparentIdentifier<ParentRow, IEnumerable<ChildRow>>> _GroupJoin(
      |   |   |   |__ queryContext: (RelationalQueryContext)queryContext,
      |   |   |   |__ source: IEnumerable<ValueBuffer> _Query(
      |   |   |   |   |__ queryContext: queryContext,
      |   |   |   |   |__ shaperCommandContext: SelectExpression:
      |   |   |   |           SELECT [p0].[Id], [p0].[Created], [c0].[Id], [c0].[Created], [c0].[ParentId]
      |   |   |   |           FROM [Parent] AS [p0]
      |   |   |   |           LEFT JOIN [Child] AS [c0] ON [p0].[Id] = [c0].[ParentId]
      |   |   |   |           ORDER BY [p0].[Id]),
      |   |   |   |__ outerShaper: BufferedOffsetEntityShaper<ParentRow>,
      |   |   |   |__ innerShaper: BufferedOffsetEntityShaper<ChildRow>,
      |   |   |   |__ innerKeySelector: (ChildRow c) => c.ParentId,
      |   |   |   |__ resultSelector: (ParentRow p | IEnumerable<ChildRow> children) => TransparentIdentifier<ParentRow, IEnumerable<ChildRow>> CreateTransparentIdentifier(
      |   |   |       |__ outer: p,
      |   |   |       |__ inner: children)),
      |   |   |__ selector: (TransparentIdentifier<ParentRow, IEnumerable<ChildRow>> t0) => new {
      |   |           t0.Outer,
      |   |           t0.Inner
      |   |        }),
      |   |__ expression: (<>f__AnonymousType0<ParentRow, IEnumerable<ChildRow>> x) => x.P.Created,
      |   |__ orderingDirection: Asc),
      |__ contextType: DataContext,
      |__ logger: DiagnosticsLogger<Query>,
      |__ queryContext: queryContext)
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (23ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [p0].[Id], [p0].[Created], [c0].[Id], [c0].[Created], [c0].[ParentId]
      FROM [Parent] AS [p0]
      LEFT JOIN [Child] AS [c0] ON [p0].[Id] = [c0].[ParentId]
      ORDER BY [p0].[Id]
```

**Comment by smitpatel** [comment] 2019-01-25 06:48
Duplicate of #14515

**Closed** 2022-10-16 13:48 UTC
Labels: customer-reported
