### ISSUE TITLE
Changing PK Identity Column to DatabaseGeneratedOption.None does not generate correct migration for SQL server

### ISSUE THREAD

**Issue by nh43de** [dotnet/efcore#6978] opened 2016-11-09 17:10 UTC
### Steps to reproduce

1. Create a new empty project (I used sample web application, with net46, and individual user accounts). 
2. Create a class "TestClass", add DbSet<TestClass> to the context and add PK column "int TestClassId" to TestClass.
3. Apply attribute "[DatabaseGenerated(DatabaseGeneratedOption.Identity)]"
4. Add migration and update database. This column is a PK and identity column.
5. Change database generated option for the PK column "TestClassId" to "[DatabaseGenerated(DatabaseGeneratedOption.None)]".
6. Add migration and update database. 

The migration that is generated does not remove the identity from the PK column. My guess is that this would require a tree traversal to determine how to handle rebuilding of FK relationships, or would require table rebuilds i.e. #329.

### Further technical details

Operating system: Windows 10
Visual Studio version: 2015
Other details: created sample web application, using net46 and individual user accounts. 
EF Core project dependencies: 
    "Microsoft.EntityFrameworkCore.SqlServer: "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.0.1",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    }

**Comment by ajcvickers** [comment] 2016-11-09 17:28
Dupe of #5345.

@nh43de As of EF 1.1 you should now get a warning in this case.

**Closed** 2022-10-16 10:41 UTC
