### ISSUE TITLE
Using AsSplitQuery with AsNoTracking causes duplicated Included entities

### ISSUE THREAD

**Issue by smartcodinghub** [dotnet/efcore#28586] opened 2022-08-04 10:03 UTC
## File a bug

Remember:

When using AsSplitQuery with AsNoTracking in a many to many or many to one relationship, I end up with multiple duplicated children entities (by Key). My hypothesis is that as we are having many queries with no ChangeTracker, it's adding it by  duplicate. If I only use one of them, it works flawlessly.

Workaround:

* I'll use only AsSplitQuery to avoid the Cartesian Explosion.

### Include your code

```C#
context.ParentEntity
        .Include(pe => pe.ChildrenEntities)
    .AsSplitQuery()
    .AsNoTracking()
    .ToList()
```

```
ParentEntity (Id, Name, ChildrenId)

1, "First", 1
2, "Second", 2
3, "Third", 1
4, "Forth", 2
```

```
ChildrenEntity (Id, Name)

1, "First"
2, "Second"
```

### Include stack traces

![image (15)](https://user-images.githubusercontent.com/12385152/182820514-5c2f8e0e-6002-4047-ad5d-755ff373bcd4.png)
![image (16)](https://user-images.githubusercontent.com/12385152/182820910-de6ae90c-a291-491c-9b45-a2ab763f88e7.png)

### Include provider and version information

EF Core version: 6.07
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: dotnet 6.0
Operating system: Windows 10
IDE: Visual Studio 2022

**Comment by smitpatel** [comment] 2022-08-04 16:37
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2022-08-15 14:53
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-08-15 14:53 UTC
Labels: customer-reported

**Comment by victor-priceputu-tb** [comment] 2025-01-09 16:25
I have the same issue:

Let's say the following relations:

```public class Book 
{
  public string Name;
  public int GenreId;
  public ICollection<Genre> Genre;
}

public class Genre
{
  public int GenreId;

  public int SubGenreId;
  public SubGenre SubGenre;

  public int LibraryShelfId;
  public LibraryShelf LibrarySelf;
}

public class SubGenre
{
  public int SubGenreId;
  public string Name;

  public ICollection<Genre> Genre;
}

public class LibraryShelf 
{
  public int LibraryShelfId;
  public string Name;

  public ICollection<Genre> Genre;
}
```

querying the data using context like 

```var result = await context
.AsSplitQuery()
.AsNoTracking()
.Book
.Include(o => o.Genre)
  .ThenInclude(o => o.SubGenre)
.Include(o => o.Genre)
 .ThenInclude(o => o.LibraryShelf)
.SingleAsync(o => o.Name == "RandomBookName")
```

results in `Genre` being loaded about 6 times more than it should (in my case I have 4 items in the DB and have 24 loaded into memory)

This is a somewhat replication of what my actual code is.

**Comment by roji** [comment] 2025-01-09 18:12
@victor-priceputu-tb in order to properly investigate this, we're going to need a minimal, runnable code sample (e.g. console program) showing the program - snippets that represent a loose approximation aren't sufficient.
