### ISSUE TITLE
Groupby after distinct with projection to a different column name fails

### ISSUE THREAD

**Issue by yepeekai** [dotnet/efcore#15486] opened 2019-04-24 15:41 UTC
Here is the code.

``` 
MySet.Select(e => new { e.MembreId, Id = e.EmployeurId })
.Distinct()
.GroupBy(e => new { e.Id })
.Select(grp => new { Value = grp.Key.Id, Count = grp.Count() }).ToListAsync();
```

It generates the following sql:
```
SELECT [t].[EmployeurId] AS [Value], COUNT(*) AS [Count]
FROM (
    SELECT DISTINCT [p].[MembreId], [p].[EmployeurId] AS [Id]
    FROM [Emploi] AS [p]
) AS [t]
GROUP BY [t].[EmployeurId]
```

The distinct sub query rename the column to Id but the group by query surrounding that uses the original names.  So it fails.

If I remove the distinct or if I remove the column renaming (Id = e.EmployeurId), everything works as expected.

Expected behavior:
The generated SQL Should use the renamed column by the distinct sub query or the distinct subquery shouldn't rename anything yet and let the master query deal with the renaming.

**Comment by smitpatel** [comment] 2019-04-24 17:57
Duplicate of #12826

**Closed** 2022-10-16 14:18 UTC
Labels: customer-reported
