### ISSUE TITLE
Feature Request: Savepoints

### ISSUE THREAD

**Issue by Lobosque** [dotnet/efcore#20211] opened 2020-03-07 12:03 UTC
Rollback a transaction up to a specific savepoint without `ExecuteSqlRaw` and without mannually re-arranging the ChangeTracker State

```C#
transaction.Savepoint("step2") // --> SAVEPOINT step2
//....
transaction.Rollback("step2") // --> ROLLBACK TO SAVEPOINT step2
// ...
transaction.Rollback() // --> ROLLBACK
```

**Comment by roji** [comment] 2020-03-07 12:24
@Lobosque savepoints are a PostgreSQL-specific concept, or at least not a universal thing supported across database. For this reason, it isn't present in the ADO.NET API, and so we can't really add anything to EF Core generically. This would also be quite an effort, as the EF Core infrastructure currently knows about transactions succeeding or failing, and does not have a concept of partially rolling back a transaction (which is what savepoints allow).

Note that you can extract the ADO DbTransaction from the RelationalTransaction instance, down-cast that to NpgsqlTransaction, and call those methods yourself - so you don't need to do ExecuteSqlRaw.

**Comment by roji** [comment] 2020-03-07 12:29
I took a quick look and apparently most DBs do support some form of savepoints ([PostgreSQL](https://www.postgresql.org/docs/current/sql-savepoint.html), [SQL Server](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqltransaction.save?view=netframework-4.8), [Sqlite](https://www.sqlite.org/lang_savepoint.html), [MySQL](https://dev.mysql.com/doc/refman/8.0/en/savepoint.html)). So we could expose something in ADO.NET for managing them (and after that possibly do something with that in EF), though we'd need to first investigate that semantics are consistent.

**Comment by Lobosque** [comment] 2020-03-07 16:23
@roji it is implemented accross all relevant databases and it looks like it is in the SQL standard.
Without a deep analysis, semantics seems to be pretty consistent accross implementations. (If you look too deep, then what is?).

Shouldn't the issue be reopened so others could also show their interest and discuss the feature?

**Comment by roji** [comment] 2020-03-07 18:01
I do agree there is potential here for a cross-database transaction savepoint API - but we'd add it to ADO.NET first in any case (so https://github.com/dotnet/runtime). We haven't seen any request for it up to now, but that doesn't mean we shouldn't have an issue for it.

At the EF level, assuming support is added in ADO.NET we'd have to understand what it means to have savepoint support exactly. I agree it may make sense to use a savepoint when SaveUpdates is called and a transaction is already open (so that the entire transaction doesn't have to be rolled back in case of an error), but that's something that can only come significantly later.

Reopening to discuss in triage.

**Comment by roji** [comment] 2020-03-09 20:22
Opened https://github.com/dotnet/runtime/issues/33397 to track adding savepoint APIs to System.Data.Common.

Using savepoints as a fix for #20176 (rolling back on optimistic concurrency exceptions) can be tracked in that issue, so I don't think this issue can track anything else (except maybe adding sugar on RelationalTransaction to call the new savepoint APIs on DbTransaction, which seems pretty low value).

**Comment by roji** [comment] 2020-04-27 15:37
Note that the proposal for System.Data support (https://github.com/dotnet/runtime/issues/33397) is waiting to be reviewed and will probably make it into .NET 5.0. At the same time, full support for savepoints has already been merged for EF Core as well in #20176.

Thanks for raising this issue!

**Comment by Lobosque** [comment] 2020-04-29 22:18
@roji thank you and the team for making it happen!

**Comment by roji** [comment] 2020-04-30 00:07
Thank you for raising it and making the original suggestion! This probably wouldn't have happened otherwise...!

**Comment by roji** [comment] 2020-06-04 20:24
Duplicate of #20176

**Closed** 2022-10-16 18:15 UTC
Labels: closed-duplicate, customer-reported
