### ISSUE TITLE
Why ef core 2.1 generates multiple select for include

### ISSUE THREAD

**Issue by viveknuna** [dotnet/efcore#12478] opened 2018-06-27 12:12 UTC
I have an ef command which is:

```C#
var project = await _context.Set<Project>().Include(p => p.Controllers).FirstOrDefaultAsync(p => p.Id == pid);
```

and in execution process it generates two select in form of sql:

```sql
SELECT TOP(1) [p].[Id], [p].[AppKey], [p].[CreateDate], [p].[Name], [p].[Title]
FROM [Project] AS [p]
WHERE [p].[Id] = @__pid_0
ORDER BY [p].[Id]

SELECT [p.Controllers].[Id], [p.Controllers].[CommandTimeout], [p.Controllers].[ContentType], [p.Controllers].[CreateDate], [p.Controllers].[IsActive], [p.Controllers].[IsJsonSerialize], [p.Controllers].[IsTested], [p.Controllers].[Method], [p.Controllers].[Name], [p.Controllers].[ProjectId], [p.Controllers].[Query], [p.Controllers].[Title]
FROM [Controller] AS [p.Controllers]
INNER JOIN (
    SELECT TOP(1) [p0].[Id]
    FROM [Project] AS [p0]
    WHERE [p0].[Id] = @__pid_0
    ORDER BY [p0].[Id]
) AS [t] ON [p.Controllers].[ProjectId] = [t].[Id]
ORDER BY [t].[Id]
```

The question is why two independent SQL commands are being generated while the first one could be skipped?? is there any reason behind that? for me, it seems like a bug!

You can find the same question [here](https://stackoverflow.com/questions/51060244/why-ef-core-2-1-generates-multiple-select-for-include) also, One person commented that 

> It's not a bug, but EF Core design decision. Instead of doing single monster union query, they do one query per each collection. It's debatable which approach is better - EF6 uses the former, EF Core - the later. As of why - only EF Core team members can answer that.

**Comment by kbekkenutte** [comment] 2018-06-27 17:57
What if there are no controllers for a project? You would get no project results (something that could be overcome by left joining controllers into projects). What if there are multiple controllers? Each record would then bring in a copy of the same project. Either case has its up and downs. Also check this post: https://stackoverflow.com/questions/34724196/entity-framework-code-is-slow-when-using-include-many-times/34732579#34732579

**Comment by smitpatel** [comment] 2018-06-27 18:03
Duplicate of #12098

**Comment by smitpatel** [comment] 2018-06-27 18:06
Especially I would suggest reading this comment https://github.com/aspnet/EntityFrameworkCore/issues/12098#issuecomment-391095895 which elaborates in detail why EF Core is using split query instead of one large query like EF 6.
As @kbekkenutte said, either case has its up and downs and it is entirely dependent on the cardinality of one to many relationship. (More projects each Controller have better the performance with split queries).

**Comment by elyasnew** [comment] 2018-06-28 06:02
there are 2 independent queries which means the second query does nothing with the first query, so still I don't understand how running 2 queries prevents data duplication!

**Closed** 2022-10-16 13:16 UTC
Labels: customer-reported
