### ISSUE TITLE
How do you sort or filter a .Include()?

### ISSUE THREAD

**Issue by IndigoHealth** [dotnet/efcore#17566] opened 2019-04-30 22:46 UTC
The article goes into great detail on various scenarios that use .Include() or .ThenInclude() to include related data via eager loading. How do I extend that concept to sort or filter the related data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-02 16:54
Duplicate of #1833

**Closed** 2022-10-16 14:39 UTC
Labels: closed-duplicate
