### ISSUE TITLE
Scaffold-DbContext false warnings

### ISSUE THREAD

**Issue by tdjastrzebski** [dotnet/efcore#9870] opened 2017-09-21 20:13 UTC
`Scaffold-DbContext` warns about all the potential issues with the indexes of the objects excluded by providing `-Schemas` switch. It seems like this switch does not limit indexes scope. Note the lack of the schema prefixes in the warning message.
Example:
```
PM> Scaffold-DbContext "Server..." Microsoft.EntityFrameworkCore.SqlServer -Context TestContext -Schemas test
Index column dbo.Content belongs to index PK_Content on table LanguageId which is not included in the selection set. Skipping.
```
Steps to reproduce: take any DB with tables and indexes, add 'test' schema, create any table in that 'test' schema, run Scaffold-DbContext for the 'test' schema only. You will get bunch of warnings about 'dbo' schema indexes.

**Comment by smitpatel** [comment] 2017-09-21 21:01
Duplicate of #9334 
Already fixed in 2.1 release.

**Closed** 2022-10-16 11:50 UTC
Labels: closed-duplicate
