### ISSUE TITLE
runtime error that i cant figure out

### ISSUE THREAD

**Issue by figuerres** [dotnet/efcore#23151] opened 2020-10-30 17:47 UTC
this error is a puzzle as it seems to be something in the runtime trying to make a relation.
the code is a very trivial starter - creating a new instance of a context and then trying to get rows from a table.
when it starts to enumerate the table an error is thrown that does not seem to be related to the current operation.

here is the error:
```
Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.SqlServer.dll
An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.SqlServer.dll
Include property 'ReliusBalance.SSNUM' not found.
```
code

```C#
            using (MARSODSContext db = new MARSODSContext ()) {
                Console.WriteLine("");
                foreach (var wb in  from wb in db.WexBalances 
                                        where wb.RunDate == dtnow 
                                        select wb
                    ) {
                    var id = wb.OfferingId;
                    var ss = wb.Ssn;
                    var rec = new Recon() {
                        RunDate = wb.RunDate,
                        IndId = wb.IndId,
                        EmployerId = wb.EmployerId,
                        EmployerAlias = wb.EmployerCode,
                        OfferingID = wb.OfferingId,
                        PlanDisplayName = wb.PlanDisplayName,
                        LastName = wb.LastName,
                        FirstName = wb.FirstName,
                        SSN = wb.Ssn,
                        AvailableBalance = wb.AvailableBalance,
                        CashBalance = wb.CashBalance
                    };
                    ReconList.Add(rec);
                }
            }
```
the error is thrown at the start of the for-each loop.

the table reliusBalance is a sql table that has no proper primary key.
SSNUM is a column in the table that is a part of an index.

i can create an ef 6 model for the same tables and there is no runtime error like this.

if i comment out the 
```
 modelBuilder.Entity<ReliusBalance>(entity =>
            {
```
section i now get an error much like this for next entity.
possibly this has to do with the sql table us the column in UPPERCASE but the c# class is not ??

### Include provider and version information

EF Core version: ef 5 rc2 for .net 5 rc2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: windows 10
IDE: Visual Studio 2019 16.8.2 preview

**Comment by figuerres** [comment] 2020-10-30 18:08
@ErikEJ  yes i just went over this and found that when the scaffolding casing is not the same as the db casing it happens.
in the try out project i had to manually update the  poco classes and entity constructors to be all UPPERCASE in c# to match the SQL db.
 is this solved by making the runtime case insensitive ? or by making the scaffolding follow the DB ??  
i guess i will see the rtm build in a few days as the whole .net 5 is due in November unless that has changed ?

**Comment by ErikEJ** [comment] 2020-10-30 18:24
By skipping the included columns (for now)

And yes, November 9...

**Comment by ajcvickers** [comment] 2020-10-30 22:25
@ErikEJ I don't think I said anywhere that EF Core 5.0 was going to be released on the 9th. I think I said it would be released the week of .NET Conf, which starts on the 9th. :-)

**Comment by ajcvickers** [comment] 2020-10-30 22:28
Duplicate of #23089

**Closed** 2022-10-16 19:07 UTC
Labels: customer-reported
