### ISSUE TITLE
Issue with Column Naming in Migrations for Snake Case

### ISSUE THREAD

**Issue by IlyaNavodkin** [dotnet/efcore#34874] opened 2024-10-10 15:43 UTC
**Package Version:**

- Microsoft.EntityFrameworkCore Version 8.0.7
- Microsoft.EntityFrameworkCore.Design Version 8.0.7
- Microsoft.EntityFrameworkCore.Relational Version 8.0.7
- Microsoft.EntityFrameworkCore.Tools Version 8.0.7
- Npgsql.EntityFrameworkCore.PostgreSQL Version 8.0.4

**Description**
I'm experiencing an issue when renaming columns in my migrations. Despite successfully renaming columns to snake_case, the migration process still attempts to insert values into the original camelCase column names.

**Steps to Reproduce**

Create a migration to rename a column in the migrations_history table from ProductVersion to product_version.

```C#
migrationBuilder.RenameColumn(
    name: "ProductVersion",
    schema: "universal_family",
    table: "migrations_history",
    newName: "product_version"
);
```

Run the migration using the command:

```C#
dotnet ef database update
```

Observe the following error in the logs:

```C#
Npgsql.PostgresException (0x80004005): 42703: column "ProductVersion" of relation "migrations_history" does not exist
```

The SQL statement being executed is:

```C#
INSERT INTO universal_family.migrations_history ("MigrationId", "ProductVersion") VALUES ('20241010144908_ChangeMigrationStyleNames', '8.0.7');
```

**Expected Behavior**
I expect the migration process to utilize the updated column names, specifically using product_version instead of ProductVersion in SQL statements, like this:
```C#
INSERT INTO universal_family.migrations_history ("MigrationId", product_version) VALUES ('20241010144908_ChangeMigrationStyleNames', '8.0.7');

```

**Actual Behavior**
The migration attempts to reference the old column names (ProductVersion), resulting in an error that indicates the column does not exist.

**Additional Information**

- This behavior occurs despite correctly renaming the columns in the migration.
- I have confirmed that the migration has been applied and that the database schema reflects these changes.
- There appears to be a discrepancy between the snapshot of the migrations and the actual state of the database, which leads to this issue.

**Comment by AndriySvyryd** [comment] 2024-10-11 18:39
Did you follow the [instructions for customizing the migrations history table](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/history-table)?

If so, please create a small runnable console project that illustrates the issue.

**Comment by IlyaNavodkin** [comment] 2024-10-15 17:34
Hello

https://github.com/IlyaNavodkin/MigrationCaseBug - sample

Use this flow:

1. Create db for dbcontext and create init migration =>  dotnet ef migrations add InitMigration
2. Run project (for miration). You have db with tables and migration table with one row history
3. Add in dbcontext configuring this method UseSnakeCaseNamingConvention();
![Image](https://github.com/user-attachments/assets/04bc8273-a97a-4ac4-b8d9-a4ba194d2686)
4. Create migration => dotnet ef migrations add ChangeCaseConvention
5. Catch exception 
![Image](https://github.com/user-attachments/assets/2b8e0544-ab51-433d-adf4-8879b27e3bf9)

**Comment by ajcvickers** [comment] 2024-11-29 17:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-11-29 17:51 UTC
Labels: customer-reported, area-migrations
