### ISSUE TITLE
Nested owned entities are not eager loaded when root entity is not projected out

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#14168] opened 2018-12-14 11:25 UTC
I've got a case when I want to nest a value object in another - PostalCode in Address. Following [the documentation](https://docs.microsoft.com/pl-pl/ef/core/modeling/owned-entities#nested-owned-types) I managed to get it working, but got an issue with reading entities owning these value objects.

When I'm reading the database using Select(Expression), only top-level value object is obtained from the database, since the inner value object is not visible in the query. I expected that it would eagerly load whole value object tree, or there would be a way to force such behaviour (.Include() doesn't work for owned types). The only workaround I came up with is using a method instead of property, so EF will select whole entity.

I provided full example in "Steps to reproduce" section, with comments explaining where the problem occurs.

So I want to ask: 
1. Is that behaviour intended?
2. Is there another way to force eager loading, other than the workaround I provided?

### Steps to reproduce
Complete Startup.cs with sample Entity and nested Value Objects

```c#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.DependencyInjection;
using Newtonsoft.Json;

namespace EfCoreIssueExample
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<ExampleDbContext>(builder => 
                builder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFProviders.InMemory;Trusted_Connection=True;ConnectRetryCount=0")
            );
        }

        public void Configure(IServiceProvider serviceProvider)
        {
            // Populate the database with test data
            using (var scope = serviceProvider.CreateScope())
            {
                var dbContext = scope.ServiceProvider.GetRequiredService<ExampleDbContext>();
                dbContext.Database.EnsureDeleted();
                dbContext.Database.Migrate();

                dbContext.Entities.Add(new Entity
                {
                    Name = "First entity",
                    Address = new Address
                    {
                        Street = "Sample street",
                        PostalCode = new PostalCode {Value = "12-345"}
                    }
                });

                dbContext.Entities.Add(new Entity
                {
                    Name = "Second entity",
                    Address = new Address
                    {
                        Street = "Another street",
                        PostalCode = new PostalCode {Value = "67-890"}
                    }
                });

                dbContext.SaveChanges();
            }

            // Read the data
            using (var scope = serviceProvider.CreateScope())
            {
                var dbContext = scope.ServiceProvider.GetRequiredService<ExampleDbContext>();
                
                // Selecting this way causes the issue
                var viewModelsNoPostalCode = dbContext.Entities.Select(entity => new ViewModel
                {
                    Id = entity.Id,
                    Name = entity.Name,
                    Address = entity.Address.ToString() // Doesn't know about PostalCode inside
                });
                
                // Selecting this way is a workaround
                var viewModelsWithPostalCode = dbContext.Entities.Select(entity => new ViewModel
                {
                    Id = entity.Id,
                    Name = entity.Name,
                    Address = entity.GetAddress().ToString() // Uses a method, so loads whole Entity anyway
                });

                Console.WriteLine(JsonConvert.SerializeObject(viewModelsNoPostalCode));
                Console.WriteLine(JsonConvert.SerializeObject(viewModelsWithPostalCode));
            }
        }
    }

    public class ExampleDbContext : DbContext
    {
        public ExampleDbContext(DbContextOptions options) : base(options) { }
        
        public DbSet<Entity> Entities { get; private set; }
        
        protected override void OnModelCreating(ModelBuilder builder)
        {
            // Entity owns Address, Address owns PostalCode
            builder.Entity<Entity>(entityBuilder =>
            {
                entityBuilder.OwnsOne(entity => entity.Address, addressBuilder =>
                {
                    addressBuilder.OwnsOne(address => address.PostalCode);
                });
            });
        }
    }

    public class Entity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Address Address { get; set; } // This won't load PostalCode
        public Address GetAddress() => Address; // This loads all columns, including PostalCode_Value
    }

    public class Address
    {
        public string Street { get; set; }
        public PostalCode PostalCode { get; set; } // Nested value object
        public override string ToString() => $"{Street} {PostalCode?.Value}";
    }

    public class PostalCode
    {
        public string Value { get; set; }
    }

    public class ViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    }
    
    public class SampleShopDbContextFactory : IDesignTimeDbContextFactory<ExampleDbContext>
    {
        public ExampleDbContext CreateDbContext(string[] args)
        {
            var builder = new DbContextOptionsBuilder<ExampleDbContext>();
            builder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFProviders.InMemory;Trusted_Connection=True;ConnectRetryCount=0");
            return new ExampleDbContext(builder.Options);
        }
    }
}
```

### Further technical details
EF Core version: 2.2.0 (from Microsoft.AspNetCore.App), also tested on 3.0.0 Preview-1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 64 bit
IDE: Rider 2018.2

**Comment by smitpatel** [comment] 2018-12-18 00:11
Duplicate of #13546

**Closed** 2022-10-16 13:44 UTC
Labels: customer-reported
