### ISSUE TITLE
Is there a method to intercept query expression tree in EF Core?

### ISSUE THREAD

**Issue by Li7ye** [dotnet/efcore#24721] opened 2021-04-22 06:34 UTC
## Ask a question
For instance, a certain entity has two global filters. However, I want to disable one of the global filters in the certain condition without calling `IgnoreQueryFilters` function and explicitly invoking `Where` function in `Queryable `class.

Please give me advice for this requirment. Thanks.

### Include provider and version information

EF Core version: 5.0.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .Net Core 3.1)
Operating system: Windows
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment] 2021-04-22 15:04
Please provide a code listing of what are you trying to achieve? Above text has several issues
- In EF Core an entity can have only 1 global filters so what do you mean when you say "a certain entity has two global filters"
- If you don't want to call `IgnoreQueryFilters` when both filters will be applied and you cannot disable (essentially remove or nullify) a filtering in a query by invoking additional Where.

**Comment by ajcvickers** [comment] 2021-05-04 14:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:32 UTC
Labels: closed-no-further-action, customer-reported
