### ISSUE TITLE
Owned property of related collection's item in EF Core mapped as NULL

### ISSUE THREAD

**Issue by Fram90** [dotnet/efcore#10819] opened 2018-01-30 11:38 UTC
Hello everyone. 

I have a simple relation one-to-many between two entities implemented in EF Core Code First, and when I call the parent I'd like to have all children with their properties in returned object. In fact, if the child entity has an **Owned** entities, then these owned entities mapped as NULL, even though there is valid data in DB (successfully mapped via the same mappings).

### Steps to reproduce

1. Add a Service entity to DB using given mappings.

2. Get it from there via _context.Services.FirstOfDefault();

3. Service.Environments.ServiceDiscovery is Null (expected to be populated with data)

It is interesting that if I make a backdoor like create DbSet<ServiceEnvironment> and take FirstOfDefault from there, everything is mapped fine. It seems like it is a one-to-many relationship, that brokes everything.

Entities:
```c#
public class Service
{
    public Guid Id { get; set; }
    public string Name { get; set; }

    private HashSet<ServiceEnvironment> _environments;
    public IReadOnlyCollection<ServiceEnvironment> Environments => _environments;
}

public class ServiceEnvironment
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public ServiceDiscovery ServiceDiscovery { get; set; }
}

    public sealed class ServiceDiscovery
    {
        public string Name { get; set; }
        public ServiceLocation Location { get; set; }
    }

    public sealed class ServiceLocation
    {
        public string Url { get; set; }
    }
```
And mappings:
```c#
    public class ServiceConfiguration : IEntityTypeConfiguration<Service>
    {
        public void Configure(EntityTypeBuilder<Service> builder)
        {
            builder.HasKey(x => x.Id);
            builder.HasMany(x => x.Environments).WithOne().OnDelete(DeleteBehavior.Cascade);

            var nav = builder.Metadata.FindNavigation(nameof(Service.Environments));
            nav.SetPropertyAccessMode(PropertyAccessMode.Field);
        }
    }

    public class ServiceEnvironmentConfiguration : IEntityTypeConfiguration<ServiceEnvironment>
    {
        public void Configure(EntityTypeBuilder<ServiceEnvironment> builder)
        {
            builder.HasKey(x => x.Id);

            builder.OwnsOne(x => x.ServiceDiscovery, opt =>
            {
                opt.Property(c => c.Name).HasColumnName("DiscoveryName").IsRequired();
                opt.OwnsOne(c => c.Location, locationOptions =>
                {
                    locationOptions.Property(x => x.Url).HasColumnName("Location_Url");
                });
            });
        }
    }
```

I'm not sure whether this is a bug or not, but if it isn't then this behavior is very unexpectable.

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10 x64
IDE: Visual Studio 2017 15.4.3

**Comment by smitpatel** [comment] 2018-01-30 16:03
Duplicate of #9210

**Closed** 2022-10-16 12:07 UTC
Labels: closed-duplicate
