### ISSUE TITLE
CompiledQueryCache uses a static lock

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#5802] opened 2016-06-17 17:38 UTC
This means that if there are multiple independent service providers each with their own instance of the query compiler, then the lock will block access to all those instances even though they should be functionally independent.

**Comment by AndriySvyryd** [comment] 2019-09-05 13:57
Also use ConcurrentBag instead of ConcurrentDictionary

**Comment by smitpatel** [comment] 2019-11-13 02:19
@roji

**Comment by roji** [comment] 2019-11-13 02:49
See #18516.

Note: the static lock in question is per query cache key, not global. So it would only block identical queries being compiled at the same time, across the entire program. We should revisit whether we actually want to block.

**Comment by roji** [comment] 2019-11-16 23:02
Closing as duplicate of #18516 since that issue contains more information by now.

**Closed** 2022-10-16 09:45 UTC
Labels: area-perf, area-query
