### ISSUE TITLE
Query execution throws an exception linq

### ISSUE THREAD

**Issue by HASSEN-MEDDEB-ATOS** [dotnet/efcore#21046] opened 2020-05-25 23:46 UTC
Hello,

i get this error below :
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)

**Comment by maumar** [comment] 2020-05-26 22:25
@HASSEN-MEDDEB-ATOS please provide FULL standalone repro. The code above is missing a bunch of stuff. I tried to fill in the blanks. ending up with something like this (which works as expected). Alternatively you can modify the code below so that it reproduces the issue.

```cs
        [ConditionalFact]
        public virtual void Repro21046()
        {
            var ListTrustedContactByFirtNameLastName = new List<Result>();

            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var ListTrustedContactByMail = new List<Result>();

                var contrat = new Result { subscriber = new Subscriber { firstName = "Foo", lastName = "bar", phoneNumbers = "baz" } };

                var ListSubsciberByFirstNameLastName = from p in ctx.Results
                                                       where p.subscriber.lastName == contrat.subscriber.lastName &&
                                                             p.subscriber.firstName == contrat.subscriber.firstName &&
                                                             p.subscriber.phoneNumbers == contrat.subscriber.phoneNumbers
                                                       select p;

                var ListRecipientrByFirstNameLastName = from p in ctx.Results
                                                        where p.recipient.lastName == contrat.subscriber.lastName &&
                                                              p.recipient.firstName == contrat.recipient.firstName &&
                                                              p.recipient.phoneNumbers == contrat.recipient.phoneNumbers
                                                        select p;

                var ListSubsciberByMail = from p in ctx.Results
                                          where p.subscriber.lastName == contrat.subscriber.lastName &&
                                                p.subscriber.firstName == contrat.subscriber.firstName &&
                                                p.subscriber.phoneNumbers == contrat.subscriber.phoneNumbers
                                          select p;

                var ListRecipientrByMail = from p in ctx.Results
                                           where p.recipient.lastName == contrat.subscriber.lastName &&
                                                 p.recipient.firstName == contrat.recipient.firstName &&
                                                 p.recipient.phoneNumbers == contrat.recipient.phoneNumbers
                                           select p;


                var trustedcon = new Trustedcontact { firstName = "fn", lastName = "ln" };

                var ListTrustedContactByFirtNameLastNameTemp =
                                                               from p in ctx.Results
                                                               where p.trustedContact.Any(x => x.firstName == trustedcon.firstName
                                                                                            && x.lastName == trustedcon.lastName
                                                                                         //&& x.phoneNumbers.Any( d=> d.number == trustedcon.phoneNumbers.Select( w => w.number).ToString())
                                                                                         )
                                                               select p;
                if (ListTrustedContactByFirtNameLastNameTemp != null)
                {
                    ListTrustedContactByFirtNameLastName = ListTrustedContactByFirtNameLastNameTemp.ToList();
                }

                var ListTrustedByMailTemp = (from p in ctx.Results
                                            where p.trustedContact.Any(x => x.mail == trustedcon.mail)
                                            select p).ToList();
            }
        }


        public class Contract
        {
            public int Id { get; set; }
            public string nextResults { get; set; }
            public string href { get; set; }
            public Result[] results { get; set; }
        }

        public class Result : IComparable<Result>
        {
            public string id { get; set; }
            public DateTime? dateModification { get; set; }
            public Subscriber subscriber { get; set; }
            public Recipient recipient { get; set; }
            public Trustedcontact[] trustedContact { get; set; }

            public int CompareTo([AllowNull] Result other)
            {
                return id == other.id
                    ? 0
                    : -1;
            }
        }

        public class Subscriber
        {
            public string id { get; set; }
            public string lastName { get; set; }
            public string firstName { get; set; }
            public string phoneNumbers { get; set; }
        }


        public class Recipient
        {
            public string id { get; set; }
            public string lastName { get; set; }
            public string firstName { get; set; }
            public string phoneNumbers { get; set; }
        }

        public class Trustedcontact
        {
            public string id { get; set; }
            public string lastName { get; set; }
            public string firstName { get; set; }
            public string mail { get; set; }
        }

        public class MyContext : DbContext
        {
            public DbSet<Result> Results { get; set; }
            public DbSet<Contract> Contracts { get; set; }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
            }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Repro21046;Trusted_Connection=True;MultipleActiveResultSets=true");
            }
        }
```

generated sql:
```sql
SELECT [r].[id], [r].[ContractId], [r].[dateModification], [r].[recipientid], [r].[subscriberid]
FROM [Results] AS [r]
WHERE EXISTS (
    SELECT 1
    FROM [Trustedcontact] AS [t]
    WHERE ([r].[id] = [t].[Resultid]) AND [t].[mail] IS NULL)
```

**Comment by maumar** [comment] 2020-05-26 22:29
also, what version of EF Core are you using?

**Comment by HASSEN-MEDDEB-ATOS** [comment] 2020-05-26 22:33
Hello, thanks for your answer, i used EF Core 3.1, i am trying with your way ;)

**Comment by HASSEN-MEDDEB-ATOS** [comment] 2020-05-26 22:41
`````````` 
public class Trustedcontact
    {
        public string idHUB { get; set; }
       public string customerId { get; set; }
       public string lastName { get; set; }
       public string firstName { get; set; }
       public DateTime? birthDate { get; set; }
       public Phonenumber2[] phoneNumbers { get; set; }
       public int travelTimeInMinutes { get; set; }
       public string contactType { get; set; }
      public string mail { get; set; } 
    }
``````````
phoneNumbers  is a list if numbers, i get always error when i use any 
`````````
  //        var ListTrustedContactByFirtNameLastNameTemp = 
            //                                                       from p in contrats
                                                                  
            //                                                       where p.trustedContact.Any(x => x.firstName == trustedcon.firstName
            //                                                                                    && x.lastName == trustedcon.lastName
            //                                                                                 //&& x.phoneNumbers.Any( d=> d.number == trustedcon.phoneNumbers.Select( w => w.number).ToString())
            //                                                                                 )
            //                                                       select p;
            //        if (ListTrustedContactByFirtNameLastNameTemp != null)
            //        {
            //            ListTrustedContactByFirtNameLastName = ListTrustedContactByFirtNameLastNameTemp.ToList();
            //        }
``````

**Comment by maumar** [comment] 2020-05-27 04:14
@HASSEN-MEDDEB-ATOS I tried the code on 3.1.4 with the updated Trustedcontract class (I assume Phonenumber2 is another entity and added the key to the entity) and I'm still getting the expected result. Can you provide the entire code listing that you are using or a gist project, rather than just the snippets?

**Comment by ajcvickers** [comment] 2020-06-08 16:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:26 UTC
Labels: closed-could-not-reproduce, customer-reported
