### ISSUE TITLE
Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite not working with .NET6.0 application

### ISSUE THREAD

**Issue by jessecallahan** [dotnet/efcore#28235] opened 2022-06-15 01:04 UTC
## Trying to update application .NET 6.0 while class library targets  .NETstandard 2.0.

We are trying to update our application to .NET6.0.

We have a class library that is a dependency and it targets .NETstandard 2.0.

According to NuGet.org, Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite v.3.1.8 should support .NET6.0 (it's listed as additional computed target framework) 

However at runtime we are getting the error:
```
System.TypeLoadException: 'Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.'
```

Class Library:
EF Core version: 3.1.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite
Target framework:  .NETstandard 2.0

Application: 
EF Core version: 6.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET6

Operating system: Windows 11 Pro
IDE: Visual Studio 2022 17.2

**Comment by ErikEJ** [comment] 2022-06-15 07:14
You should update to 6 for all, you cannot mix dependencies like that

**Comment by roji** [comment] 2022-06-15 07:49
As @ErikEJ wrote, the problem is mixing two versions of EF Core in the same application (3.1.8 and 6.0.0). You can continue using EF Core 3.1.8 after upgrading to .NET 6.0, though.

**Comment by jessecallahan** [comment] 2022-06-15 18:41
Hi,

Thanks so much for the response.

**Comment by jessecallahan** [comment] 2022-06-15 18:54
Hi,

Thanks for the response.

We have now changed our EF Core version in our application back to 3.1.8 and we are running into another error.

So are set up - 

Class Library:
EF Core version: 3.1.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite
Target framework: .NETstandard 2.0

Application:
EF Core version: 3.1.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET6

Operating system: Windows 11 Pro
IDE: Visual Studio 2022 17.2

**New Error:**
```An exception of type 'System.TypeInitializationException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code
The type initializer for 'Microsoft.EntityFrameworkCore.EnumerableMethods' threw an exception.
```

The only information I could really decipher for this fix was found here: [https://docs.microsoft.com/en-us/answers/questions/622611/net-6-upgrade.html](url)

Which essentially says, the ef core packages in all libraries need to be updated to the newest version, in this case, 6.0.

Am I understanding this right? The only way to fix this is to update our EF Core version in our application and class libraries is to 6.0? (Which unfortunately is a problem based on our client's constraints)

Thanks in advance for your help.

**Comment by roji** [comment] 2022-06-15 19:36
This sounds like #24002 - try using 3.1.26 instead of 3.1.8.

**Comment by jessecallahan** [comment] 2022-06-16 19:53
Hi, this looks like its working so far ... I'll let you know when I successfully upgrade the full solution so you can close the ticket. Thanks!

**Comment by roji** [comment] 2022-06-16 21:10
Closing as the reported bug matches a known issue. But if you encounter other issues, don't hesitate to post back or file a new bug.

**Closed by roji** 2022-06-16 21:10 UTC
Labels: customer-reported
