### ISSUE TITLE
Query: Uncorrelated subquery returning entities produces ArgumentException: Argument type '...EntityQueryable`1[Repro13739.Entity]' does not match the corresponding member type '...DbSet`1[Repro13739.Entity]'

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#13745] opened 2018-10-24 19:43 UTC
I found this while playing with the repro for #13739. 

Repro:
``` csharp
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Repro13739
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var dbContext = new MyContext())
            {
                dbContext.Database.EnsureDeleted();
                dbContext.Database.EnsureCreated();
                dbContext.Add(new Entity { Name = "Dog" });
                dbContext.Add(new Entity { Name = "Cat" });
                dbContext.Add(new Entity { Name = "Kitchen" });
                dbContext.Add(new Entity { Name = "House" });
                dbContext.SaveChanges();
            }

            using (var dbContext = new MyContext())
            {

                var query = dbContext.Set<Entity>();
                var pagedQueryable = query.OrderBy(e => e.Id)
                                          .Skip(1).Take(5)
                                          .Select(e => new
                                          {
                                              Total = query,
                                              Item = e
                                          });

                var page = pagedQueryable.ToList();

                var total = page.First()
                                .Total;
                var items = page.Select(x => x.Item)
                                .ToList();
            }
        }
    }

    public class MyContext: DbContext
    {
        public DbSet<Entity> Entities { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("server=(localdb)\\mssqllocaldb;database=blah;integrated security=true;connectretrycount=0");
        }
    }

    public class Entity
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

```

**Comment by ajcvickers** [comment] 2018-10-26 18:13
This should throw because can't project DbSet.
@divega to file the other issue--when ToList is present.

**Comment by smitpatel** [comment] 2019-11-21 17:49
Closing as duplicate of #16314

**Closed** 2022-10-16 13:37 UTC
Labels: area-query
