### ISSUE TITLE
Why my entity primary key shows to be modified after updating entity?

### ISSUE THREAD

**Issue by embryologist** [dotnet/efcore#12363] opened 2018-06-14 20:53 UTC
Describe what is not working as expected.

I have a class `ApplicationUser` that inherits from `IdentityUser`. I added the property `LastLoggedIn` which is `OffsetDateTime ` datatype and I modify it with every request to the API. Also, I am using [`Audit`](http://entityframework-plus.net/audit) from entity framework plus to log user add/update/delete operations and this is how I came across this issue. every time I update the `ApplicationUser` entity's `LastLoggedIn` property I can see that the `Id` property has been modified as well, showing same old and new value. Why my primary key is being modified here?

```
No Exception message:
```

### Steps to reproduce
Call `UserManager` `FindByIdAsync`, Modify a property and save changes

```c#
public class ApplicationUser : IdentityUser {
            [Required, StringLength(50)]
            [Display (Name = "First Name")]
            public string FirstName { get; set; }
            public OffsetDateTime? LastLoggedIn { get; set; }
}

// Method

public async Task UpdateUserLastActivityDateAsync (string userId, string timeZone) {
           var user = await userManager.FindByIdAsync(userId);
           user.LastLoggedIn = timeZone.GetInstantOffsetDateTime();
           await unitOfWork.CompleteAsync(); //  = context.SaveChangesAsync();
}
```

I tried the following but I get an exception,

```
    builder.Entity<ApplicationUser>()
            .Property(e => e.Id)
            .ValueGeneratedOnAddOrUpdate()
            .Metadata.BeforeSaveBehavior = PropertySaveBehavior.Ignore;
```

> The property 'Id' cannot be configured as 'ValueGeneratedOnUpdate' or
> 'ValueGeneratedOnAddOrUpdate' because the key value cannot be changed
> after the entity has been added to the store.

### Further technical details
EF Core version: 2.1
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Operating system: macOS High Sierra
IDE: (VS.Code)

**Comment by ajcvickers** [comment] 2018-06-15 16:52
@embryologist There is not enough here for me to be able to reproduce what you are seeing. Can you please post a runnable project/solution or complete code listing that demonstrates the behavior so that we can investigate more?

**Comment by ajcvickers** [comment] 2018-06-25 17:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:31 UTC
Labels: closed-could-not-reproduce, customer-reported
