### ISSUE TITLE
A column has been specified more than once in the order by list. Columns in the order by list must be unique

### ISSUE THREAD

**Issue by Mtaraby** [dotnet/efcore#19442] opened 2019-12-31 11:04 UTC
I am using EF Core 2.2.2 in my project, and I am getting this error when trying to fetch any data from DB, I am not sure what is the reason of this, but it works fine when trying to insert new item to DB:

Error Message :

> "A column has been specified more than once in the order by list. Columns in the order by list must be unique"

I think the issue happened because of using nested OwnsMany many times but not sure:

```csharp
    public class Program
    {
        private static void Main(string[] args)
        {
            using(var context = new OwnsManyIssueContext())
            {
                var accidentEstimationDetails = new List<AccidentEstimationDetails>
                {
                 new AccidentEstimationDetails(true, "test1"),
                 new AccidentEstimationDetails(false, "test2"),
                 new AccidentEstimationDetails(true, "test3")
                };
                var accidentEstimation = new AccidentEstimation(12, 11, accidentEstimationDetails);
                var partiesLiabilityAmounts = new List<PartyAmountDetails>
                {
                    new PartyAmountDetails(1,11,120),
                    new PartyAmountDetails(1,12,121),
                    new PartyAmountDetails(1,10,122)
                };

                var accident = new Accident(accidentEstimation, partiesLiabilityAmounts);

                context.Accidents.Add(accident);
                context.SaveChanges();

                var dbAggregate = context.Accidents.FirstOrDefault();
            }
        }
    }

    public class Accident
    {
        public int Id { get; private set; }

        public AccidentEstimation AccidentEstimation { get; private set; }

        private List<PartyAmountDetails> _partiesAmountDetails;

        public IReadOnlyCollection<PartyAmountDetails> PartiesAmountDetails => _partiesAmountDetails;

        private Accident()
        {
            _partiesAmountDetails = new List<PartyAmountDetails>();
        }

        public Accident(AccidentEstimation accidentEstimation, List<PartyAmountDetails> partiesLiabilityAmount)
        {
            AccidentEstimation = accidentEstimation;
            _partiesAmountDetails = partiesLiabilityAmount;
        }
    }

    public class AccidentEstimation
    {
        public int EstimationPartyId { get; private set; }
        public int FollowerId { get; private set; }

        private readonly List<AccidentEstimationDetails> _details;
        public IReadOnlyCollection<AccidentEstimationDetails> Details => _details;

        private AccidentEstimation()
        {
            _details = new List<AccidentEstimationDetails>();
        }

        public AccidentEstimation(int estimationPartyId, int followerId, List<AccidentEstimationDetails> details)
        {
            EstimationPartyId = estimationPartyId;
            FollowerId = followerId;
            _details = details;
        }
    }

    public class AccidentEstimationDetails
    {
        public bool IsApproved { get; private set; }
        public string Name { get; private set; }

        private AccidentEstimationDetails()
        {
        }

        public AccidentEstimationDetails(bool isApproved, string name)
        {
            IsApproved = isApproved;
            Name = name;
        }
    }

    public class PartyAmountDetails
    {
        public int ItemTypeId { get; private set; }
        public decimal Amount { get; private set; }
        public decimal? Discount { get; private set; }

        private PartyAmountDetails()
        {
        }

        public PartyAmountDetails(int itemTypeId, decimal amount, decimal? discount)
        {
            ItemTypeId = itemTypeId;
            Amount = amount;
            Discount = discount;
        }
    }


    public class AccidentTypeConfiguration : IEntityTypeConfiguration<Accident>
    {
        public void Configure(EntityTypeBuilder<Accident> builder)
        {
            builder.ToTable("Accidents");
            builder.Property(b => b.Id).ValueGeneratedOnAdd(); ;
            builder.HasKey(b => b.Id);

            builder.OwnsOne(a => a.AccidentEstimation, a =>
            {
                a.Property(p => p.FollowerId).HasColumnName("FollowerId");
                a.Property(p => p.EstimationPartyId).HasColumnName("EstimationPartyId");


                a.OwnsMany(dd => dd.Details, dd =>
                {
                    dd.ToTable("AccidentEstimationDetails");
                    dd.Property<int>("Id");
                    dd.HasKey("Id");
                });
            });

            builder.OwnsMany(a => a.PartiesAmountDetails, a =>
            {
                a.ToTable("PartiesLiabilityAmounts");
                a.Property<long>("Id");
                a.HasKey("Id");
            });
        }
    }

    public class OwnsManyIssueContext : DbContext
    {
        public DbSet<Accident> Accidents { get; set; }


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@";");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new AccidentTypeConfiguration());

            base.OnModelCreating(modelBuilder);
        }
    }
```

**Comment by ajcvickers** [comment] 2020-01-02 19:05
Note for triage: this works in 3.1. Possible dupe?

**Comment by smitpatel** [comment] 2020-01-03 00:45
New include pipeline.

**Comment by ajcvickers** [comment] 2020-01-03 18:59
Duplicate of #12795

**Closed** 2022-10-16 18:03 UTC
Labels: closed-duplicate, customer-reported
