### ISSUE TITLE
Eager .Include() not loading related data

### ISSUE THREAD

**Issue by thekatstevens** [dotnet/efcore#19980] opened 2020-02-19 12:38 UTC
Query to a collection using multiple eager `.Include()`s for related tables isn't actually loading data into the returned object. 

### Steps to reproduce

Current query looks like this:

```
             transaction = context.Transactions
                    .Include(t => t.Allocations)
                    .Include(t => t.Account)
                    .SingleOrDefault(t => t.Id == transactionId);
```

This should load a single `Transaction` (based on the ID), with one related `Account`, and a collection of related `Allocation`s. Models look more or less like this:

```
    public class Transaction
    {
        public Transaction()
        {
            Allocations = new List<Allocation>();
        }

        public int Id { get; set; }

        public virtual BankAccount Account { get; set; }

        public List<Allocation> Allocations { get; set; }
    }

    public class Allocation
    {
        public int Id { get; set; }

        public int TransactionId { get; set; }

        [Required] public Transaction Transaction { get; set; } = new Transaction();
    }
```

Prior to upgrading from EF Core 2.2 this was working fine. I've checked through the list of breaking changes and can't see anything around this behaviour.

I've also checked the SQL that is being sent to the DB and it looks fine -> I've run it against the DB directly (with the ID explicitly stated) and it returns a fully populated row as expected. So something is going wrong between the data being returned from the query and mapping it into the object model. When inspecting during debug, the `Transaction` object is populated with the `BankAccount`, but the `Allocations` list is empty. I expect it to contain the allocation as returned by the query.

Current workaround is to explicitly query the allocations separately in a second query and map it across manually.

Thanks :)

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Rider 2019.3.2

**Comment by smitpatel** [comment] 2020-02-21 01:04
Can you provide a runable repro? I am not able to reproduce this.

**Comment by LaurentKubler** [comment] 2020-02-28 12:55
Hello, 
I had a problem looking more or less like yours.

But, I had a line looking rather like that:
public List<Allocation> Allocations { get; set; } = new List<Allocation>();

Having removed the initialization, it looks like it's working.

**Comment by ajcvickers** [comment] 2020-02-28 17:05
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by GertArnold** [comment] 2020-03-26 12:47
You have to remove `= new Transaction()`. See https://stackoverflow.com/q/20757594/861716

**Comment by thekatstevens** [comment] 2020-04-14 12:11
Thanks @GertArnold, can confirm that that assignment line in the model is what was tripping it up! Interesting that this behaviour changed between 2.2 and 3.1.

Thanks for the help and comments :)

**Closed** 2022-10-16 18:11 UTC
Labels: closed-could-not-reproduce, customer-reported
