### ISSUE TITLE
Using HasData to seed values in a new table cannot retrieve ColumnTypes 

### ISSUE THREAD

**Issue by gio994** [dotnet/efcore#31888] opened 2023-09-28 09:13 UTC
I created a new Table in my database and used entity builder HasData to add a new seed for the table
```C#
modelBuilder.Entity<TableCounter>().HasData(new TableCounter() { TableRecapNumber = 0 });
```
The generated migration is the following:
```C#
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.CreateTable(
        name: "Table_TableCounter",
        columns: table => new
        {
            FixedIdentity = table.Column<byte>(type: "tinyint", nullable: false),
            TableRecapNumber = table.Column<int>(type: "int", nullable: false),
            OCC = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: true)
        },
        constraints: table =>
        {
            table.PrimaryKey("PK_Table_TableCounter", x => x.FixedIdentity);
        });

    migrationBuilder.InsertData(
        table: "Table_TableCounter",
        columns: new[] { "FixedIdentity", "TableRecapNumber " },
        values: new object[] { (byte)0, 0 });
}
```
But when i try to run it i get the following exception:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=There is no entity type mapped to the table '1.Table_TableCounter' which is used in a data operation. Either add the corresponding entity type to the model, or specify the column types in the data operation.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.GetPropertyMappings(String[] names, String tableName, String schema, IModel model) in Microsoft.EntityFrameworkCore.Migrations\MigrationsSqlGenerator.cs:line 758

```

### Workaround

If i manually modify the generated migration including ColumnTypes in the InsertData statement the problem does not occur.

```C#

 migrationBuilder.InsertData(
        table: "Table_TableCounter",
        columnTypes: new[] {"tinyint", "int"},
        columns: new[] { "FixedIdentity", "TableRecapNumber " },
        values: new object[] { (byte)0, 0 });
```
But this is not a practical solution, i will be forced to modify every using InsertData to make it work.

### The problem
Investigating the issue i found that the problem is generated when efcore tries to generate the modification command for the insert operation: specifically, in the framework class
```
Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator
```
there is a point in the method GenerateModificationCommands where, at row 981 (should be it, found in the github class https://github.com/dotnet/efcore/blob/v6.0.15/src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs) it tries to get the property mappings:
```C#
      protected virtual IEnumerable<IReadOnlyModificationCommand> GenerateModificationCommands(InsertDataOperation operation, IModel? model)
     {
            ...

	    IColumnMapping[] propertyMappings = ((operation.ColumnTypes == null) ? GetPropertyMappings(operation.Columns, operation.Table, operation.Schema, model) : null);

	    ...
     }
```
But calling the method GetPropertyMappings, at row 1249 it tries to read the table where  the insertdata is getting done to read the column types of the operation, getting the exception shown above because the table is not yet on the database

```C#
    private static IColumnMapping[] GetPropertyMappings(string[] names, string tableName, string? schema, IModel? model)
        {
            ...

	    ITable table = model?.GetRelationalModel().FindTable(tableName, schema);
                if (table == null)
                    {
	                throw new InvalidOperationException(RelationalStrings.DataOperationNoTable(FormatTable(tableName, schema)));
                    }

	    ...
        }
```

### Provider and version information

EF Core version: 6.0.15
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 11 Pro
IDE: Visual Studio 2022 17.7.3

**Comment by ajcvickers** [comment] 2023-10-03 09:31
@gio994 Please try with [EF Core 8 RC 1](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/8.0.0-rc.1.23419.6) and if you are still seeing an issue, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-10-16 19:20
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-10-16 19:20 UTC
Labels: customer-reported
