### ISSUE TITLE
Will EF7 support UWP with SQL server when released?

### ISSUE THREAD

**Issue by jasondjelinek** [dotnet/efcore#4692] opened 2016-03-03 05:04 UTC
When Entity Framework Core 1.0(EF7) is released will a UWP application be able to connect to a sql server?  Reading through the roadmap, it looks like EntityFramework.MicrosoftSqlServer will be a supported provider, but will not be supported on the UWP platform, is that correct?  

If its not supported....
- What is recommend alternative for connecting UWP apps to a SQL Server?
- Is it planned for a future release?  
- What platforms will EntityFramework.MicrosoftSqlServer be supported on?

**Comment by divega** [comment] 2016-03-03 07:12
This is going to require SqlClient (the ADO.NET provider for SQL Server) to have support for UWP. There shouldn't be any fundamental reason for the EF portion of the provider not to work in UWP.

**Comment by divega** [comment] 2016-03-03 07:18
@YoungGah and @saurabh500 may be able to comment on whether this is in the roadmap for SqlClient.

**Comment by rowanmiller** [comment] 2016-03-08 18:47
Closing as there is nothing actionable on the EF side - the EF SQL Server provider will work on UWP if SQL Client is enabled. SQL Client is managed as part of https://github.com/dotnet/corefx, so feel free to post there if you don't hear back from folks cc'd above.

**Comment by tdjastrzebski** [comment] 2017-03-20 17:16
Do I correctly understand the problem is currently System.Data.SqlClient ver 4.1 or above is not supported on UWP?

**Comment by ajcvickers** [comment] 2017-03-20 17:18
@tdjastrzebski Correct. As far as I am aware, there is no released version of System.Data.SqlClient that works on UWP.

**Comment by tdjastrzebski** [comment] 2017-03-21 09:12
That is a show stopper - my first attempt at UWP development :/

**Comment by sannyi** [comment] 2017-05-25 11:27
Few days ago a successfully imported System.Data.SqlClient, but chrashed because UWP does not support System.Threading.Thread. What's the status today? Also how the status with a FTPClient (.NET Core 2 and Standard 2) ?

**Comment by AlfredBauer** [comment] 2017-05-29 11:12
I agree with sannyi. Have the same error about "System.Threading.Thread"

**Comment by taspeotis** [comment] 2017-12-16 13:12
It would appear that `System.Data.SqlClient` is now available on UWP, given:

* You're targeting Fall Creators Update at a minimum
* You ask for the *Enterprise Authentication* entitlement

https://docs.microsoft.com/en-us/windows/uwp/data-access/sql-server-databases

**Closed** 2022-10-16 09:31 UTC
