### ISSUE TITLE
Support filtered Lazy Loading

### ISSUE THREAD

**Issue by JamesMenetrey** [dotnet/efcore#22755] opened 2020-09-25 12:46 UTC
Dear EF Core Community,

The new filtered Include capabilities that EF Core 5 is bringing is fascinating! I would like to know if something similar can be made when using lazy loading. As an example, assuming I have a collection navigation property `blog.Posts` that is backed by lazy loading, I would like to be able to query posts in a filtered way, such as last year's posts `blog.Posts.Where(p => p.PublishedDate > DateTime.Today.AddYear(-1))`.

Currently, performing such queries retrieve all the posts from the database and filter them in memory. Implementing filtered lazy loading capabilities would tailor the query only to retrieve the requested posts.

What do you think?

Cheers!

**Comment by ajcvickers** [comment] 2020-09-28 21:13
Duplicate of #1204

**Closed** 2022-10-16 19:00 UTC
Labels: customer-reported
