### ISSUE TITLE
In "database first" the underscores character are not transferred into the model.

### ISSUE THREAD

**Issue by j-nord** [dotnet/efcore#6194] opened 2016-07-28 12:51 UTC
### Steps to reproduce

Generate the model with the following command:
Scaffold-DbContext "Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models
### The issue

Describe what is not working as expected.
The table name in the database is **d_documentation**. The generated model name is **DDocumentation**. So all disappear any underscores. Is there any way this underscores to take over in the model. Also it would be nice if everything were to lowercase.
### Further technical details

EF Core version: 1.0.0-preview2-final
Operating system: Windows 10
Visual Studio version: Visual Studio 2015

**Comment by ajcvickers** [comment] 2016-07-28 16:35
Dupe of #6018

**Comment by j-nord** [comment] 2016-09-01 18:38
Dupe of #6018 

Sorry, we have tested it and it doesn't work.

Is there an example of the current Framework which really work?

We have it include in the startup.cs in the curent Framework but the CustomCandidateNamingService methode was not called.

Why?

**Comment by divega** [comment] 2016-09-01 19:27
@j-nord not sure. The sample code at https://gist.github.com/natemcmaster/353f4ab3efb4514eeaec846df28f0e24 is working for me. Is `Startup.ConfigureDesignTimeServices()` called for you?

**Closed** 2022-10-16 09:52 UTC
Labels: closed-duplicate
