### ISSUE TITLE
Add Update Method to DbSet

### ISSUE THREAD

**Issue by mohamedmahmoudalemam** [dotnet/efcore#14599] opened 2019-02-04 13:12 UTC
Why not add Update method to DbSet class
Method Signature: DbSet<T>.Update(Func<T, bool> predicate, T);
So to update a row in a table:
Employee employee = new Employee{FirstName = "Mohamed"};
context.Employees.Update(x => x.Id == 1, employee);
this line should produce this sql statement: update Employee set FirstName = 'Mohamed' where Id = 1;
If for example, user want to update multiple rows this method will help him/her.
example: context.Employees.Update(x => 1 == 1, new Employee{DepartmentId= 1});
this line  should produce this sql statement: update Employee set DepartmentId = 1 where 1 =1;

**Comment by kmolerov** [comment] 2019-02-04 13:34
EF core should have more functionalities for C/U/D operations without using change tracker - directly composing and execution the query. Most of the times we don't need the change-tracker. It only adds overhead.

**Comment by mohamedmahmoudalemam** [comment] 2019-02-04 13:40
Many developers use AsNoTracking method, so these types of C/U/D operations should be implemented

**Comment by ajcvickers** [comment] 2019-02-04 16:59
Duplicate of #795

**Closed** 2022-10-16 13:50 UTC
Labels: closed-duplicate, customer-reported
