### ISSUE TITLE
 HierarchyId Support [Discussion Link]

### ISSUE THREAD

**Issue by RandyBuchholz** [dotnet/efcore#7490] opened 2017-01-26 02:55 UTC
I opened a discussion over at Roslyn for a Hierarchy type. Since it would be advantageous to design this type to work cleanly with EF and SQL's HierarchyID I thought I'd post a link here for anyone interested.

[[C# Feature Request] Hierarchy Data Type #16193](https://github.com/dotnet/roslyn/issues/16193)

**Comment by rowanmiller** [comment] 2017-02-01 18:47
Duplicate of #365. Added a note about the C# feature request to that issue.

**Closed** 2022-10-16 10:51 UTC
Labels: closed-duplicate
