### ISSUE TITLE
EF Core 8 - InvalidOperationException when updating ComplexProperty using ExecuteUpdateAsync

### ISSUE THREAD

**Issue by xeonix** [dotnet/efcore#32846] opened 2024-01-16 18:23 UTC
Hi Guys!
You did a great job introducing ComplexProperty feature in EF Core 8 that perfectly fits DDD ValueObject idea.
However I faced an issue when using
`DbContext.Set<SomeEntity>().Where([condition]).ExecuteUpdateAsync(sp => sp.SetProperty(e => e.ComplexProperty, new ComplexPropertyType(...)))`.
**For example.**
Here's my Entity/EntityConfiguration
```C#
record AddressValue(string? State, string? Street);

class Company
{
    public int Id { get; init; }

    public required string Name { get; init; }

    public required AddressValue Address1 { get; set; }

    public required AddressValue Address2 { get; set; }
}

class EfCore8PlaygroundDbContext : DbContext
{
    public EfCore8PlaygroundDbContext(DbContextOptions<EfCore8PlaygroundDbContext> options) : base(options) { }

    public DbSet<Company> Companies { get; private set; }

    protected sealed override void OnModelCreating(ModelBuilder modelBuilder) =>
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(EfCore8PlaygroundDbContext).Assembly);
}

class ComanyEntityConfiguration : IEntityTypeConfiguration<Company>
{
    public void Configure(EntityTypeBuilder<Company> builder)
    {
        builder.ToTable("Companies");

        builder.HasKey(e => e.Id);
        builder.Property(e => e.Id).UseIdentityColumn();

        builder.Property(e => e.Name).
            IsRequired().
            HasMaxLength(100);

        builder.ComplexProperty(e => e.Address1, address1Builder =>
        {
            address1Builder.Property(e => e.State).HasColumnName("Address1State").HasMaxLength(100);
            address1Builder.Property(e => e.Street).HasColumnName("Address1Street").HasMaxLength(100);
        });

        builder.ComplexProperty(e => e.Address2, address2Builder =>
        {
            address2Builder.Property(e => e.State).HasColumnName("Address2State").HasMaxLength(100);
            address2Builder.Property(e => e.Street).HasColumnName("Address2Street").HasMaxLength(100);
        });
    }
}
```
and here's my code that fails:
```C#
var builder = new DbContextOptionsBuilder<EfCore8PlaygroundDbContext>();
builder.UseSqlServer("Server=(local);Initial Catalog=EfCore8Playground;Integrated Security=True;TrustServerCertificate=True");

await using var dbContext = new EfCore8PlaygroundDbContext(builder.Options);
await dbContext.Database.EnsureCreatedAsync();

var company = new Company { Name = "TestCompany", Address1 = new("Address1State", "Address1Street"), Address2 = new ("Address2State", "Address2Street") };
await dbContext.AddAsync(company);
await dbContext.SaveChangesAsync();

await dbContext.Companies.
    Where(e => e.Address1.Street == "Address1Street").
    ExecuteUpdateAsync(e => sp.SetProperty(e => e.Address1, new AddressValue("Address1StateXyz", "Address1StreetXyz")));
```
The last line fails with:
```
Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
An exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll but was not handled in user code
The LINQ expression 'DbSet<Company>()
    .Where(c => c.Address1.Street == "Address1StateAsdf")
    .ExecuteUpdate(sp => sp.SetProperty<AddressValue>(
        propertyExpression: e => e.Address1, 
        valueExpression: new AddressValue(
            "Address1StateXyz", 
            "Address1StreetXyz"
        )))' could not be translated. Additional information: The following lambda argument to 'SetProperty' does not represent a valid property to be set: 'e => e.Address1'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```
When I change that line to
```C#
await dbContext.Companies.
    Where(e => e.Address1.Street == "Address1Street").
    ExecuteUpdateAsync(sp => sp.
        SetProperty(e => e.Address1.State, "Address1StateXyz").
        SetProperty(e => e.Address1.Street, "Address1StreetXyz"));
```
it works fine.

EF Core version: 8.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET 8.0)
Operating system: Windows/Linux
IDE: Visual Studio 2022 17.8.4

**Comment by roji** [comment] 2024-01-16 19:02
Duplicate of #32058

**Comment by roji** [comment] 2024-01-16 19:03
Glad to hear complex types are working well for you! The feature you described was just implemented and merged (#32058), you can try to latest EF [daily build](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md) and see how it works (it would be great to get feedback!).

**Closed** 2024-01-17 19:00 UTC
Labels: closed-duplicate, customer-reported

**Comment by xeonix** [comment] 2024-01-19 11:07
@roji Thank you for sharing this commit with me. Unfortunately it's scheduled for EF Core 9, which is scheduled to the end of this year. But I managed to integrate your fixes to EF Core 8 as `RelationalQueryableMethodTranslatingExpressionVisitor9` and used it with `ReplaceService<IQueryableMethodTranslatingExpressionVisitorFactory, RelationalQueryableMethodTranslatingExpressionVisitor9Factory>();`. This proves that the fix could be easily release as part of EF Core 8.

**Comment by roji** [comment] 2024-01-21 21:59
@xeonix the question isn't how easy or hard it is to backport this to 8 - it's the fact that this is an enhancement rather than a bug fix or a regression. As is standard, we do not release new enhancements in patch releases.

But by all means, using your copied RelationalQueryableMethodTranslatingExpressionVisitor9 with the change is a reasonable workaround until EF9 is released.
