### ISSUE TITLE
Query: invalid SQL generated for query with default DateTime value

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12819] opened 2018-07-26 23:06 UTC
query:

```cs
                var nextYear = 2017;

                var query = ctx.Orders.Where(o => o.OrderDate != ((DateTime?)null ?? default) )
                    .Select(o => o.OrderDate.Value.Year)
                    .Distinct()
                    .Where(x => x < nextYear);

                var result = query.ToList();
```

sql:
```sql
SELECT [t].[c]
FROM (
    SELECT DISTINCT DATEPART(year, [o].[OrderDate]) AS [c]
    FROM [Orders] AS [o]
    WHERE ([o].[OrderDate] <> '0001-01-01T00:00:00.000') OR [o].[OrderDate] IS NULL
) AS [t]
WHERE [t].[c] < @__nextYear_0
```

Exception:

```
The conversion of a varchar data type to a datetime data type resulted in an out-of-range value.
	at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
	at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
	at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
	at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
	at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
	at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
	at System.Data.SqlClient.SqlDataReader.Read()
	at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Read()
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
	at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
	at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by maumar** [comment] 2018-07-26 23:06
similar to https://github.com/aspnet/EntityFrameworkCore/issues/12797

**Comment by amoorthaemer** [comment] 2018-07-27 05:19
@maumar even EF 6 has problems with this. SQL DATETIME shouldn’t be used anymore ... use DATETIME2 instead. The generated SQL is just fine...

**Comment by smitpatel** [comment] 2018-07-27 19:45
We need to generate `IS NULL` instead of DateTime literal for null.

**Comment by maumar** [comment] 2018-07-27 21:07
its `default(DateTIme)`, not `DateTime?`, also this is a problem when the value is in projection, not only in predicate

**Comment by ajcvickers** [comment] 2018-07-30 19:29
Triage: closing this as duplicate of #12797

**Closed** 2022-10-16 13:22 UTC
Labels: closed-duplicate
