### ISSUE TITLE
Creation of DB takes several minutes after update to Visual Studio 15.3.1

### ISSUE THREAD

**Issue by ManuelHaas** [dotnet/efcore#9532] opened 2017-08-23 09:00 UTC
Hi,

I have an ASP.NET Core 1.2 (using .NET framework 4.6.2) app with EF Core 1.2. After updating Visual Studio 2017 to version 15.3.1 the creation of the database (if it was deleted in a previous step) takes several minutes!! Before update the creation takes a few seconds.
Watching the creation in debug log looks like slow motion. It creates two or three tables and freezes for one or two minutes, than it creates another one or two tables and so on.

**Comment by ajcvickers** [comment] 2017-08-23 16:52
@ManuelHaas Could you provide a full project that reproduces what you are seeing. You can email it privately (avickers at where I work) if it can't be posted publicly.

**Comment by ManuelHaas** [comment] 2017-08-23 17:37
@ajcvickers I'm sorry but there is some intellectual property in the project that is not free for transfer. Is there a way to turn on some kind of detailled logging for a log file that would help you?
If not, I had to remove some parts of the project which will take some time...

**Comment by ajcvickers** [comment] 2017-08-25 16:37
@ManuelHaas We discussed this in triage but unfortunately we don't have any great ideas on how to debug this without additional details. Is it really creating the database that takes a lot of time as opposed to creating the model or something else? If it is, then it may not be an EF issue, but something about the interaction with the database. What database server are you using? Could you try running scripts directly against the database and see if those execute quickly or also take a lot of time?

**Comment by ManuelHaas** [comment] 2017-08-26 09:19
@ajcvickers What takes so long is creating the model - sorry if I hadn`t been exact in my explanation. I'm using localDB version 13.0.4001 (SQL Server 2016 Service Pack 1) and updated to 13.0.4446 (Cumulative Update #4 for SP1) afterwards because I also think that it maybe is a DB related problem. But nothing changes. A total build of the database took about 35 minutes currently (before it where 4 or 5 seconds).

Add-Migration statements through npm also takes much more time than previously.

I created a branch and updated the solution to EF Core 2.0 and ASP.NET Core 2.0. In this setup no problems occur.

**Comment by ajcvickers** [comment] 2017-08-30 20:36
@ManuelHaas We're finding it quite hard to grasp what is going on and have discussion we think the best way forward would be fore you to create a project that exhibits this behavior so we can try to reproduce the issue and root cause it. Is that something you can do?

**Comment by ajcvickers** [comment] 2017-09-06 18:40
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:17 UTC
Labels: closed-could-not-reproduce
