### ISSUE TITLE
RelationalDatabaseFacadeExtensions.Migrate output?

### ISSUE THREAD

**Issue by dliberatore-th** [dotnet/efcore#20798] opened 2020-05-01 02:52 UTC
When calling RelationalDatabaseFacadeExtensions.Migrate, it would be very useful to have some kind of parameter that causes actions to be posted via logs/outputs/a callback.

My use case is that we list the migrations via GetPendingMigrations then execute via Migrate, but the exceptions that occur if the database is in a wrong state do not readily identify which specific migration item failed.

**Comment by ajcvickers** [comment] 2020-05-04 16:40
@dliberatore-th Are you asking how to see the logs? Or are you asking for some functional change?

**Comment by dliberatore-th** [comment] 2020-05-04 17:35
I'm looking for some kind of logging mechanism (or info on how to access/hook an existing one) so I can see migration progress with at least coarse granularity i.e. entry-per-script level "doing script XYZ now" type entries.

**Comment by roji** [comment] 2020-05-04 18:05
@dliberatore-th have you set up logging [as described in the docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging?tabs=v3)? That shows the exact migration SQL getting executed, allowing you to know exactly what triggered the exception.

**Comment by ajcvickers** [comment] 2020-05-15 16:24
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:22 UTC
Labels: closed-could-not-reproduce
