### ISSUE TITLE
LINQ Contains with concatenated columns generates OPENJSON with incorrect varchar length

### ISSUE THREAD

**Issue by TimSirmovics** [dotnet/efcore#32965] opened 2024-01-30 23:38 UTC
When using `contains` in a LINQ query with a concatenation of columns, the new OPENJSON optimisation generates a varchar declaration with only the length of the first column, and not the subsequent columns.
This causes the values for comparison to be truncated to the length of the first column, whilst being compared to the concatenation of columns from the table, which fails.

Related:

[Breaking change documentation](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#sqlserver-contains-compatibility)
[Sql Server - LINQ Contains returns false positive results for string values larger than column size](https://github.com/dotnet/efcore/issues/32735)
[In what scenarios will the new .Contains functionality using OPENJSON change the data being returned by a query?](https://github.com/dotnet/efcore/issues/32852)

### Table / EF setup

```
CREATE TABLE [dbo].[EXAMPLE](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Value1] [varchar](4) NOT NULL,
	[Value2] [varchar](6) NOT NULL)
```
```
builder.Property(x => x.Value1).HasColumnName(@"Value1").HasColumnType("varchar(4)").IsRequired().IsUnicode(false).HasMaxLength(4).ValueGeneratedNever();
builder.Property(x => x.Value2).HasColumnName(@"Value2").HasColumnType("varchar(6)").IsRequired().IsUnicode(false).HasMaxLength(6).ValueGeneratedNever();
```

### Query / Generated SQL

```
var list = new List<string> { "AAAABBBBBB" };
var sampleQuery = _context.Example.Where(e => list.Contains(e.Value1 + e.Value2)).Select(e => e.Id).ToList();
```

```
exec sp_executesql N'SELECT [e].[Id]
FROM [dbo].[EXAMPLE] AS [e]
WHERE [e].[Value1] + [e].[Value2] IN (
    SELECT [l].[value]
    FROM OPENJSON(@__list_0) WITH ([value] varchar(4) ''$'') AS [l]
)',N'@__list_0 nvarchar(4000)',@__list_0=N'["AAAABBBBBB"]'
```

The result of the `OPENJSON` subquery is that the value is truncated to `'AAAA'`, which fails to match with the `IN` statement.

### Provider and version information

EF Core version: 8.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
SQL Server version: 2019 (15.0.2104.1)
Target framework: net8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.8.6

**Comment by roji** [comment] 2024-01-31 11:15
Duplicate of #32333

**Closed** 2024-01-31 13:36 UTC
Labels: closed-duplicate, customer-reported
