### ISSUE TITLE
"InvalidOperationException: EF.Property called [...]" when using nested projection with conditions

### ISSUE THREAD

**Issue by Erythnul** [dotnet/efcore#19997] opened 2020-02-20 09:59 UTC
Apologies in advance for what is going to be a long issue, I tried to be as complete in my information as possible and have done some debugging into your code to (hopefully) help speed up triage. 

We are upgrading an existing EF6-based codebase to use EF Core 3.1, to take advantage of the significant performance and query-readability improvements provided by the new EF.

We use software to generate expression trees to do our projection from entities to DTO, and are running into a problem with projecting to nested types.
This scenario is supported in EF6.

This example is simplified for brevity. Expression generation is removed, as the issue can be reproduced by making a similar query with a Select statement. 
Null checking seems excessive, but is both required (because our legacy database has... issues) and even if it wasn't, because of the dynamic nature of the expressions they would probably still be generated this way.
I used the ReadableExpressions.Visualizers to keep reading the expression trees managable for this issue.
If you need more information, please let me know!

### Steps to reproduce

Let's say we have a customer entity:

```
public class CustomerEntity
{
    public Guid Id { get; set; }
    public int CountryId { get; set; }
    public int? PostalAddressCountryId { get; set; }
    public CountryEntity Country { get; set; }
    public CountryEntity? PostalAddressCountry { get; set; }
}

public class CountryEntity
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class CustomerDTO
{
    public CountryDTO Country { get; set; }
    public CountryDTO? PostalAddressCountry { get; set; }
}
public class CountryDTO
{
    public string Name { get; set; }
}
```

Using a method and query such as this:

```
public async Task<CustomerDTO> GetCustomerByCustomerIdAsync(Guid customerId)
{
    var customer = await this.context.Customers.Where(x => x.Id == customerId).Select(x => new CustomerDTO
    {
        PostalAddressCountry = (x.PostalAddressCountryId != null ? x.PostalAddressCountry : null) != null ? new CountryDTO { Name = x.PostalAddressCountry.Name } : null
    })
    .FirstOrDefaultAsync();

    return customer;
}
```

results in the following Expression tree:

```
EntityQueryable<CustomerEntity>
    .Where(x => x.Id == __customerId_0)
    .Select(
        x => new CustomerDTO
        {
            PostalAddressCountry = (((((int?)x.PostalAddressCountryId) != null) ? x.PostalAddressCountry : null) != null)
                ? new CountryDTO
                {
                    Name = x.PostalAddressCountry.Name
                }
                : null
        })
    .FirstOrDefault()
```

After it's been run through the QueryTranslationPreprocessor it looks like this:

```
EntityQueryable<CustomerEntity>
    .Where(v => v.Id == __customerId_0)
    .Join(
        EntityQueryable<CountryEntity>,
        v => EF.Property<int?>(v, "PostalAddressCountryId"),
        l => EF.Property<int?>(l, "Id"),
        (o, i) => new TransparentIdentifierFactory.TransparentIdentifier<CustomerEntity, CountryEntity>(o, i))
    .Select(
        v => new CustomerDTO
        {
            PostalAddressCountry = (EF.Property<int?>((((int?)v.Outer.PostalAddressCountryId) != null) ? v.Inner : null, "Id") != null)
                ? new CountryDTO
                {
                    Name = v.Inner.Name
                }
                : null
        })
    .FirstOrDefault()
```

When the query is processed in the RelationalSqlTranslatingExpressionVisitor the exception occurs. It seems that in the TryBindMember method the expectation is that the input expression should always be an EntityShaperExpression, however, we arrive at the method with a ConditionalExpression, causing binding to fail.

Exception:
System.InvalidOperationException: 'EF.Property called with wrong property name.'

StackTrace:
```
at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in D:\tfs\Git\efcore\src\EFCore.Relational\Query\RelationalSqlTranslatingExpressionVisitor.cs:line 379
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression) in D:\tfs\Git\efcore\src\EFCore.Relational\Query\RelationalSqlTranslatingExpressionVisitor.cs:line 557
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression) in D:\tfs\Git\efcore\src\EFCore.SqlServer\Query\Internal\SqlServerSqlTranslatingExpressionVisitor.cs:line 48
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitConditional(ConditionalExpression conditionalExpression) in D:\tfs\Git\efcore\src\EFCore.Relational\Query\RelationalSqlTranslatingExpressionVisitor.cs:line 686
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression) in D:\tfs\Git\efcore\src\EFCore.Relational\Query\RelationalSqlTranslatingExpressionVisitor.cs:line 50
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression) in D:\tfs\Git\efcore\src\EFCore.Relational\Query\Internal\RelationalProjectionBindingExpressionVisitor.cs:line 165
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment) in D:\tfs\Git\efcore\src\EFCore.Relational\Query\Internal\RelationalProjectionBindingExpressionVisitor.cs:line 308
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression) in D:\tfs\Git\efcore\src\EFCore.Relational\Query\Internal\RelationalProjectionBindingExpressionVisitor.cs:line 287
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression) in D:\tfs\Git\efcore\src\EFCore.Relational\Query\Internal\RelationalProjectionBindingExpressionVisitor.cs:line 177
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression) in D:\tfs\Git\efcore\src\EFCore.Relational\Query\Internal\RelationalProjectionBindingExpressionVisitor.cs:line 47
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector) in D:\tfs\Git\efcore\src\EFCore.Relational\Query\RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 752
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in D:\tfs\Git\efcore\src\EFCore\Query\QueryableMethodTranslatingExpressionVisitor.cs:line 351
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in D:\tfs\Git\efcore\src\EFCore.Relational\Query\RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 78
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in D:\tfs\Git\efcore\src\EFCore\Query\QueryableMethodTranslatingExpressionVisitor.cs:line 66
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in D:\tfs\Git\efcore\src\EFCore.Relational\Query\RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 78
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) in D:\tfs\Git\efcore\src\EFCore\Query\QueryCompilationContext.cs:line 76
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async) in D:\tfs\Git\efcore\src\EFCore\Storage\Database.cs:line 71
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in D:\tfs\Git\efcore\src\EFCore\Query\Internal\QueryCompiler.cs:line 112
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0() in D:\tfs\Git\efcore\src\EFCore\Query\Internal\QueryCompiler.cs:line 149
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in D:\tfs\Git\efcore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 84
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in D:\tfs\Git\efcore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 59
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken) in D:\tfs\Git\efcore\src\EFCore\Query\Internal\QueryCompiler.cs:line 145
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken) in D:\tfs\Git\efcore\src\EFCore\Query\Internal\EntityQueryProvider.cs:line 98
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken) in D:\tfs\Git\efcore\src\EFCore\Extensions\EntityFrameworkQueryableExtensions.cs:line 2861
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken) in D:\tfs\Git\efcore\src\EFCore\Extensions\EntityFrameworkQueryableExtensions.cs:line 2886
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken) in D:\tfs\Git\efcore\src\EFCore\Extensions\EntityFrameworkQueryableExtensions.cs:line 366
```

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.5

**Comment by smitpatel** [comment] 2020-02-20 21:52
`PostalAddressCountry = (x.PostalAddressCountryId != null ? x.PostalAddressCountry : null) != null ? new CountryDTO { Name = x.PostalAddressCountry.Name } : null`
 is a pattern we don't recognize to removal null.
You can simplify it this way
```C#
PostalAddressCountry = x.PostalAddressCountryId != null && x.PostalAddressCountry != null ? new CountryDTO { Name = x.PostalAddressCountry.Name } : null
```

Duplicate of #17020

**Comment by Erythnul** [comment] 2020-02-21 08:21
Thanks for your response. 

Unfortunately, we can't really influence how the expressions are structured as they are generated dynamically by external code.
Am I right to assume that #17020 will get picked up by your team eventually (as it's tagged as an easy win)? If so, hopefully it'll make it into 5.0. I'll follow that issue.

As a stopgap measure until more complex conditionals are supported, we'll probably write an expression visitor to fix up the expressions before they enter your code. 
Do you want me to close this issue, or is it something you prefer to handle yourselves?

**Comment by smitpatel** [comment] 2020-02-21 18:12
> expressions are structured as they are generated dynamically by external code.

Can you tell us what external library are you using?

**Comment by NetTecture** [comment] 2020-02-22 20:40
@smitpatel I am betting he is using Automapper Queryable Extensions (ProjectTo). You know, the same one you said are not generating LINQ but materializing the object in #19999, which was wrong back then and is quite likely wrong here.
Now, how do I know this? Well, let me say it like that: if he uses another library I would also like to know the name because... I am not aware of anything outside the Automapper complex that generates projections as LINQ.

**Comment by Erythnul** [comment] 2020-02-25 15:51
@smitpatel We are indeed using ProjectTo from Automapper Queryable Extensions.
We find it reliably generates complex expression trees as long as the mapping is well-written and it allows us to only select the exact fields we require from the database with the right conditions. Combined with EF core, the queries are highly efficient.
Unfortunately, we ran into this issue, but hopefully, it can be resolved at some point.
Apologies for the late response, work got in the way.

**Comment by smitpatel** [comment] 2020-02-25 17:29
Closing as duplicate of #17020

**Closed** 2022-10-16 18:12 UTC
Labels: customer-reported
