### ISSUE TITLE
Child records not included in query result

### ISSUE THREAD

**Issue by ritcoder** [dotnet/efcore#2719] opened 2015-07-26 21:57 UTC
When I run the query below, the `ratings` property for all records is a list with no records even though the first record has 10 rating items.

This does not work. The 

```
            var data = await _db.products
                .Include(x => x.ratings)
                .Where(x => x.companyId == user.companyId)
                .Select(x => new { productId = x.id, productName = x.name, productCode = x.code, x.ratings })
                .ToListAsync();
```

This works (when the select statement is comment)

```
            var data = await _db.products //just a temp measure
                .Include(x => x.ratings)
                .Where(x => x.companyId == user.companyId)
                //.Select(x => new { productId = x.id, productName = x.name, productCode = x.code, x.ratings })
                .ToListAsync();
```

Ratings is defined as

```
public virtual ICollection<ProductRating> ratings { get; set; } = new HashSet<ProductRating>();
```

At the moment, to get it to work, I must execute the query to get all the items and do the select after the toList. 
Is this a bug or by design?
What is the correct way to include child records?

**Comment by rowanmiller** [comment] 2015-07-29 18:38
Also a dupe of #325 (PR out for review at the moment that will enable this scenario)

**Closed** 2022-10-16 09:03 UTC
