### ISSUE TITLE
VerificationException: Method Microsoft.EntityFrameworkCore.Query.Internal.IQueryBuffer.CorrelateSubquery: type argument 'System.Collections.Generic.IReadOnlyCollection`1[Entity]' violates the constraint of type parameter 'TCollection'.

### ISSUE THREAD

**Issue by ShamsulAmry** [dotnet/efcore#12925] opened 2018-08-07 23:09 UTC
The exception will be thrown if I project a property of type IReadOnlyCollection<>, but will be fine if I project a property of type ICollection<>.
```
Exception message:
System.ArgumentException: GenericArguments[2], 'System.Collections.Generic.IReadOnlyCollection`1[TestConsole.Program+TestDbContext+StockListRecord]', on 'TCollection CorrelateSubquery[TInner,TOut,TCollection](Int32, Microsoft.EntityFrameworkCore.Metadata.INavigation, System.Func`2[Microsoft.EntityFrameworkCore.Metadata.INavigation,TCollection], Microsoft.EntityFrameworkCore.Query.Internal.MaterializedAnonymousObject ByRef, Boolean, System.Func`1[System.Collections.Generic.IEnumerable`1[System.Tuple`3[TInner,Microsoft.EntityFrameworkCore.Query.Internal.MaterializedAnonymousObject,Microsoft.EntityFrameworkCore.Query.Internal.MaterializedAnonymousObject]]], System.Func`3[Microsoft.EntityFrameworkCore.Query.Internal.MaterializedAnonymousObject,Microsoft.EntityFrameworkCore.Query.Internal.MaterializedAnonymousObject,System.Boolean])' violates the constraint of type 'TCollection'.

Stack trace:
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CorrelatedCollectionOptimizingVisitor.Rewrite(Int32 correlatedCollectionIndex, QueryModel collectionQueryModel, INavigation navigation, Boolean trackingQuery, QuerySourceReferenceExpression originQuerySource, Boolean forceListResult, Type listResultElementType)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CorrelatedCollectionOptimizingVisitor.TryRewrite(SubQueryExpression subQueryExpression, Boolean forceToListResult, Type listResultElementType, Expression& result)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CorrelatedCollectionOptimizingVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.TryOptimizeCorrelatedCollections(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at TestConsole.Program.<Main>d__0.MoveNext() in E:\Projects\Test\src\TestConsole\Program.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TestConsole.Program.<Main>(String[] args)
```

Inner exception:
```
Exception message:
VerificationException: Method Microsoft.EntityFrameworkCore.Query.Internal.IQueryBuffer.CorrelateSubquery: type argument 'System.Collections.Generic.IReadOnlyCollection`1[TestConsole.Program+TestDbContext+StockListRecord]' violates the constraint of type parameter 'TCollection'.

Stack trace:
   at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType declaringType, RuntimeType[] methodInstantiation)
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
```

### Steps to reproduce
I have the following DbContext:
```c#
        public class TestDbContext : DbContext
        {
            public TestDbContext(DbContextOptions options) : base(options)
            { }

            public DbSet<StockItemRefRecord> StockItemRefTable { get; private set; }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<StockListRecord>()
                    .HasKey(sl => new {sl.StockItemId, sl.ItemUomCode});
            }

            [Table("StockItemRef", Schema = "gs")]
            public class StockItemRefRecord
            {
                [Key]
                public int StockItemId { get; private set; }

                public IReadOnlyCollection<StockListRecord> StockList { get; private set; }
            }

            [Table("StockList", Schema = "gs")]
            public class StockListRecord
            {
                [ForeignKey(nameof(StockItemRefRecord.StockItemId)), Required]
                public StockItemRefRecord StockItemRef { get; private set; }

                public int StockItemId { get; private set; }
                public string ItemUomCode { get; private set; }
            }
        }
```

And a call which will throw the exception:
```c#
db.StockItemRefTable.Where(sir => sir.StockItemId == 11947).Select(sir => sir.StockList).FirstOrDefault()
```

If I change `StockItemRefRecord.StockList` to ICollection<> instead of IReadOnlyCollection<>, it will work fine.

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.1

**Comment by ajcvickers** [comment] 2018-08-08 16:59
Duplicate of #12881

**Comment by ahedreville** [comment] 2019-03-23 17:41
Hi any update?

Same problem when trying to apply DDD read only collection as follows.. (code sample reduced for brevity)

The classes..
```
    public class EmailAddress
    {
        public Guid Id { get; protected set; }
        public string MailAddress { get; protected set; }
    }

    public class Player 
    {
        public Guid Id { get; protected set; }
        public string Name{ get; protected set; }
        private readonly List<EmailAddress> _emailAddresses = new List<EmailAddress>();
        public ICollection<EmailAddress> EmailAddresses
        {
            get => _emailAddresses.AsReadOnly();   // We need the backing field AsReadOnly since we will be assigning it to an IReadOnlyCollection (on a future once issue gets solved)
            protected set=> _emailAddresses = value.ToList();  // Trick to allow Select<T> of IQueryable<T> extension method to work since composing the projection the projection sub query will need to have a setter.
        }
    }
```

The fluent API configuration 
```
            builder.HasMany(e => e.EmailAddresses)
                .WithOne(e => e.Player)
                .HasForeignKey(e => e.PlayerId)
                .OnDelete(DeleteBehavior.Cascade);
                //.Metadata.PrincipalToDependent.SetPropertyAccessMode(PropertyAccessMode.Field); // Not need to define this as backing field since we will be using a protected setter instead.
```

The code to get test the issue..
```
var players = context.Set<Player>().AsQueryable();

var player = players
         .Include("EmailAddresses")
         .Select<Player>(new []{ "Id", "EmailAddresses" })
         .FirstOrDefault();
```

**The handy extension method Select<T> that would break with _' violates the constraint of type parameter 'TCollection'_  if IReadOnlyCollection<EmailAddress> is used instead of ICollection<EmailAddress>**
```
        public static IQueryable<T> Select<T>(this IQueryable queryable, IEnumerable<string> fields) where T : class
        {
            var resultType = typeof(T);
            var sourceType = queryable.ElementType;

            var parameterExpression = Expression.Parameter(sourceType, "e");
            var expressionBody = GetNewMember(typeof(T), parameterExpression, fields.Select(field => field.Split('.')));
            var lambdaExpression = Expression.Lambda(expressionBody, parameterExpression);

            return queryable.Provider.CreateQuery<T>(Expression.Call(typeof(Queryable), "Select", new[] { sourceType, resultType }, queryable.Expression, Expression.Quote(lambdaExpression)));
        }

        private static Expression GetNewMember(Type targetType, Expression parameterExpression, IEnumerable<string[]> memberPaths, int depth = 0)
        {
            var target = Expression.Constant(null, targetType);

            var bindings = memberPaths
                .GroupBy(path => path[depth])
                .Select(memberGroup =>
                {
                    var memberName = memberGroup.Key;
                    var targetMember = Expression.PropertyOrField(target, memberName);
                    var sourceMember = Expression.PropertyOrField(parameterExpression, memberName);
                    var childMembers = memberGroup.Where(path => depth + 1 < path.Length);
                    var enumerable = childMembers as string[][] ?? childMembers.ToArray();
                    var targetValue = !enumerable.Any() ? sourceMember : GetNewMember(targetMember.Type, sourceMember, enumerable, depth + 1);

                    return Expression.Bind(targetMember.Member, targetValue);
                });

            return Expression.MemberInit(Expression.New(targetType), bindings); // See note below (*)
        }
```


For now **the solution is to have declared ICollection<EmailAddress> EmailAddresses instead of IReadOnlyCollection<EmailAddress> EmailAddresses**.

From DDD perspective will work since any attempt to modify the ICollection<EmailAddress> EmailAddresses  collection with methods like Add, Clear, etc. will trow System.NotSupportedException : Collection is read-only.
From developer perspective instead, some one could be tempted to use such methods since they are available

**Closed** 2022-10-16 13:24 UTC
Labels: customer-reported
