### ISSUE TITLE
Include siblings syntactic sugar with AndInclude

### ISSUE THREAD

**Issue by isonil** [dotnet/efcore#9593] opened 2017-08-26 11:17 UTC
Currently we have to write this:

```c#
db.Posts
    .Include(x => x.Author).ThenInclude(x => x.FavoriteBook)
    .Include(x => x.Author).ThenInclude(x => x.FavoriteMovie);
```

It would look better and reduce redundancy if we could do this:

```c#
db.Posts
    .Include(x => x.Author)
    .ThenInclude(x => x.FavoriteBook)
    .AndInclude(x => x.FavoriteMovie);
```

**Comment by ajcvickers** [comment] 2017-08-30 21:07
@isonil This is an interesting idea and similar to some suggestions that have been made in issue #4490. It's not clear that this can be implemented without breaking changes using the current types because the generics for the previous level in the hierarchy are not necessarily available. If you find a way to make this work we would be interested to consider it more. For now, closing as a duplicate of #4490

**Closed** 2022-10-16 11:18 UTC
Labels: closed-duplicate
