### ISSUE TITLE
How to make a SP call in EF core 3

### ISSUE THREAD

**Issue by jt4000** [dotnet/efcore#19014] opened 2019-11-21 18:14 UTC
I can't make a call with SP when I use EF core 3 using FromSQLRow.

It works in EF core 2 but not in EF core 3.

What approach should I go?

**Comment by smitpatel** [comment] 2019-11-21 20:25
Please refer to https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#fromsqlsproc 

If that does not resolve your question then please give us repro code.

**Comment by ajcvickers** [comment] 2019-12-02 16:55
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:57 UTC
Labels: closed-could-not-reproduce, customer-reported
