### ISSUE TITLE
Does Json Column support a collection value?

### ISSUE THREAD

**Issue by rongconzx** [dotnet/efcore#29735] opened 2022-12-02 05:42 UTC
## Ask a question

I have the column FollowSOIds with the typed string as JSON array int. I mapped it to Json Column in the database context. I got an error in the query *could not be translated*.
Is there any way to map collection values (int, string) with Json Array in  Entity Framework 7?

### Include your code
My db scheme

![image](https://user-images.githubusercontent.com/9065933/205222973-a5a86168-869c-4eef-a501-45b99ce5ffc1.png)

```C#
 public class UserNotificationPreference
    {
        public int Id { get; set; }
   
        public List<int> FollowSOIds { get; set; }

    }

      public class AppDBContext : DbContext
    {
        public AppDBContext()
            : base()
        {
        }     

    
        public DbSet<UserNotificationPreference> UserNotificationPreference { get; set; }
        protected override void OnModelCreating(ModelBuilder builder)
        {     
            builder.Entity<UserNotificationPreference>()
                .ToTable("UserNotificationPreference").OwnsOne(x => x.FollowSOIds, z => z.ToJson());
        }
}

```

### Include stack traces

![image](https://user-images.githubusercontent.com/9065933/205222787-705fe77b-6114-4f13-9e3b-951048f2b815.png)
```

### Include verbose output


```
System.InvalidOperationException
  HResult=0x80131509
  Message=The LINQ expression 'DbSet<UserNotificationPreference>()
    .Where(u => u.FollowSOIds
        .Contains(1))' could not be translated. Additional information: Translation of method 'System.Linq.Enumerable.Contains' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in C:\Users\admin\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 8

```

### Include provider and version information

EF Core version: 7
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 7.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by maumar** [comment] 2022-12-02 07:53
dupe of https://github.com/dotnet/efcore/issues/29427

**Closed** 2022-12-05 12:06 UTC
Labels: customer-reported

**Comment by roji** [comment] 2022-12-05 14:14
Duplicate of #29427
