### ISSUE TITLE
Attribute.IsDefined is a perf hotsport during model building

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#25891] opened 2021-09-06 17:07 UTC
In #20135, building a user-submitted model shows a huge amount of time spent in Attribute.IsDefined, called from ForeignKeyAttributeConvention.FindForeignKeyAttributeOnProperty (and other conventions). I suspect that the inherit flag increases the perf cost, and the model in question seems to have quite a bit of hierarchy.

In addition, it seems like the same MemberInfo gets checked more than once; introducing a simple `Dictionary<MemberInfo, bool>` cache in ForeignKeyAttributeConvention for the results of Attribute.IsDefined reduced model building time from 79 to 45 seconds. After this I can still see other call-side for Attribute.IsDefined showing up (e.g. PropertyAttributeCOnventionBase) - we may want to investigate if it makes sense to be traversing the same members/entity types multiple times, and if so, consider adding caching.

**Comment by AndriySvyryd** [comment] 2021-09-07 15:54
Duplicate of https://github.com/dotnet/efcore/issues/13691

Also https://github.com/dotnet/efcore/issues/214 will allow to remove the attribute conventions if attributes aren't used for model configuration.

**Closed** 2022-10-16 20:07 UTC
Labels: closed-duplicate
