### ISSUE TITLE
Column Order in EF Core 3.0.1

### ISSUE THREAD

**Issue by subbiahkalidasan** [dotnet/efcore#19889] opened 2020-02-12 04:26 UTC
Column ordering is Not working in EF Core 3.0.1. For example I have the following Classes.

```C#
public class BaseEntity
    {
        [Key]
       [Column(Order = 1)]
        public Guid Id { get; set; }  
  
       [Column(Order = 100)]
        public Guid? CreatedBy { get; set; }

        [Column(Order = 101)]
        public DateTime? CreatedDt { get; set; }

        [Column(Order = 102)]
        public Guid? ModifiedBy { get; set; }

        [Column(Order = 103)]
        public DateTime? ModifiedDt { get; set; } 
    }
```

```C#
Public class Product : BaseEntity
{
       [Column(Order = 2)]
        public string Name{ get; set; }     
}
```

the output of  the Add-Migartion  cmd is like this

```C#
 migrationBuilder.CreateTable(
                name: "Product",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    CreatedBy = table.Column<Guid>(nullable: true),
                    CreatedDt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<Guid>(nullable: true),
                    ModifiedDt = table.Column<DateTime>(nullable: true),
                    Name = table.Column<string>(type: "varchar(60)", nullable: true)
                },
```

I am expecting output Like this

```C#
 migrationBuilder.CreateTable(
                name: "Product",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    Name = table.Column<string>(type: "varchar(60)", nullable: true),
                    CreatedBy = table.Column<Guid>(nullable: true),
                    CreatedDt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<Guid>(nullable: true),
                    ModifiedDt = table.Column<DateTime>(nullable: true),
                    
                },
```

Thanks in Advance,
Subbiah K

**Comment by ajcvickers** [comment] 2020-02-14 21:29
Duplicate of #10059

**Closed** 2022-10-16 18:10 UTC
Labels: customer-reported
