### ISSUE TITLE
Changes to property converters / ValueComparer's in efcore 7

### ISSUE THREAD

**Issue by nstdspace** [dotnet/efcore#28984] opened 2022-09-05 15:20 UTC
I am trying to get our application running with the current daily build of efcore 7, version 7.0.0-rc.2.22453.1 and currently facing a very weird issue. Since I have trouble identifying the exact reason and not able to create a small reproducible example, I decided to ask if there are any significant changes which could lead to the behaviour, I will describe in the following, to potentially safe myslef some further debugging hours.

In some tables we have configured some properties to be converted from arrays (in the model) to json strings (in the database) using `propertyBuilder.HasConversion(serialize, deserialize, arrayComparer)`. Now, during some import processes and respective `context#SaveChanges` I get a `ClassCastException` in `ValueComparer#Equals` which is due to the fact, that in `ModificationCommand.ColumnValuePropagator#TryPropagate`, during the evaluation of the first if-condition, `mapping.Column.ProviderValueComparer` is a `DefaultValueComparer<string>` but `_originalValue` is a json string while `entry.GetCurrentValue(property)` evaluates to the actual domain value (which is an array), so the cast to a string obviously fails.

Is there any obvious reason related to changes in efcore 7 which could lead to that problem?

**Comment by ajcvickers** [comment] 2022-09-07 20:28
@nstdspace I've tried a few things to reproduce this on the latest daily build, but have not been able to do so--see my code below. I think at this point we need a small, runnable project or code listing that reproduces what you are seeing so that we can investigate.

```C#
public class Blog
{
    public int Id { get; set; }
    public string? Title { get; set; }

    public int[] NumericData { get; set; } = null!;
    public string[] StringData { get; set; } = null!;
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    public DbSet<Blog> Blogs { get; set; } = null!;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>(
            b =>
                {
                    b.Property(e => e.NumericData)
                        .HasMaxLength(32)
                        .HasConversion(
                            v => JsonSerializer.Serialize(v, (JsonSerializerOptions?)null),
                            v => JsonSerializer.Deserialize<int[]>(v, (JsonSerializerOptions?)null)!,
                            new ValueComparer<int[]>(
                                (c1, c2) => c1!.SequenceEqual(c2!),
                                c => c.Aggregate(0, (a, v) => HashCode.Combine(a, v.GetHashCode())),
                                c => c.ToArray()));

                    b.Property(e => e.StringData)
                        .HasMaxLength(32)
                        .HasConversion(
                            v => JsonSerializer.Serialize(v, (JsonSerializerOptions?)null),
                            v => JsonSerializer.Deserialize<string[]>(v, (JsonSerializerOptions?)null)!,
                            new ValueComparer<string[]>(
                                (c1, c2) => c1!.SequenceEqual(c2!),
                                c => c.Aggregate(0, (a, v) => HashCode.Combine(a, v.GetHashCode())),
                                c => c.ToArray()));

                    b.HasIndex(e => e.NumericData).IsUnique();
                    b.HasIndex(e => e.StringData).IsUnique();
                });
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.AddRange(
                new Blog
                {
                    NumericData = new[] { 1, 1, 2, 3, 5, 8, 13 },
                    StringData = new[] { "1", "1", "2", "3", "5", "8", "13" }
                },
                new Blog
                {
                    NumericData = new[] { 1, 2, 3, 5, 8, 13 },
                    StringData = new[] { "1", "2", "3", "5", "8", "13" }
                },
                new Blog
                {
                    NumericData = new[] { 2, 3, 5, 8, 13 },
                    StringData = new[] { "2", "3", "5", "8", "13" }
                },
                new Blog
                {
                    NumericData = new[] { 3, 5, 8, 13 },
                    StringData = new[] { "3", "5", "8", "13" }
                });

            context.SaveChanges();
        }

        using (var context = new SomeDbContext())
        {
            foreach (var blog in context.Blogs)
            {
                blog.Title = blog.Id.ToString();
                Console.WriteLine(string.Join(", ", blog.NumericData));
                Console.WriteLine(string.Join(", ", blog.StringData));
            }

            context.SaveChanges();
        }
    }
}
```

**Comment by ajcvickers** [comment] 2022-09-16 11:46
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-09-16 11:46 UTC
Labels: customer-reported
