### ISSUE TITLE
Using collection.Contains on nvarchar column with max length could result in partial matches

### ISSUE THREAD

**Issue by RobLiekens** [dotnet/efcore#33564] opened 2024-04-18 15:26 UTC
Example:

I have a simple `Country `entity containing a string property `Alpha2Code` with a max length of 2 chars and value "CO" in my database.

Executing the following query with some random codes that are longer than 2 chars and start with "CO" (e.g. "COUNTRY", "COLA")
`query.Where(x => ids.Contains(x.Alpha2Code))`

Results in the following SQL being generated:

exec sp_executesql N'SELECT TOP(1) [c].[Alpha2Code], [c].[Alpha3Code], [c].[Name]
FROM [Countries] AS [c]
WHERE [c].[Alpha2Code] IN (
    SELECT [i].[value]
    FROM OPENJSON(@__ids_0) WITH ([value] **nvarchar(2)** ''$'') AS [i]
)',N'@__ids_0 nvarchar(4000)',@__ids_0=N'["COUNTRY","COLA"]

The outcome: my entity with Alpha2Code "CO" is considered as a match, despite it being only a partial match of both of the items I'm searching for ("COUNTRY" and "COLA")

Explanation:
In the bold part of the generated SQL query, EF cuts each inputted item after 2 chars (the max length of the column). 
This is an incorrect assumption. It's not because the values in the DB column are restricted to a certain max length , that there are any guarantees that the input variables of the query (list of ID's in the given example), will also be restricted to that same length.

Fix:
bold part should be nvarchar(max length restriction + 1) instead of nvarchar(maxlength) to prevent cutting of values resulting in possible partial matches

**Comment by ErikEJ** [comment] 2024-04-18 15:43
Which exact EF core version??

**Comment by RobLiekens** [comment] 2024-04-18 15:45
I'm using 8.0.4

**Comment by maumar** [comment] 2024-04-19 00:51
dupe of https://github.com/dotnet/efcore/issues/32735

**Closed** 2024-04-19 00:52 UTC
Labels: closed-duplicate, customer-reported
