### ISSUE TITLE
Another entity with the same key is tracked

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#8368] opened 2017-05-03 09:28 UTC
I have an entity which key is two properties:

- TableA(IDTableA, ...)
- TableB(IDTableB, ...)
- TableC(IDTableA, IDTableB, ....)

In my logic, sometimes I have to delete the entity type C but later sometimes I need to add a new one that has the same IDTableA and same IDTableB with different data. But in the save changes, EF tells that there are two entities with the same key and it is not possible.

So I have tried this:

- Delete my entity type C
- Save changes, expecting that the dbContext knows that I have deleted the row in the database
- Create the new entity type C with the same key.

But I still have the same error. With EF 6 this works as expected, I can delete the entity and create a new one with the same key with no problems.

Another solution it would be find the entity with the same key and update that instead of create a new one, but in my case the logic of the application is that first I delete the entity type C and later, to see if I need to create a new one with different data.

How could I solve this case?

Thanks.

**Comment by smitpatel** [comment] 2017-05-03 17:47
Can you post the exact exception are you getting & stack trace? Also your model classes & OnModelCreating method code.

**Comment by ajcvickers** [comment] 2017-05-12 18:07
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 11:03 UTC
