### ISSUE TITLE
scaffold db : add an option to prefix entities with schema name

### ISSUE THREAD

**Issue by Pearseak** [dotnet/efcore#23374] opened 2020-11-18 06:35 UTC
currently, if we have table `pig.price` and `cow.price` in the same DB, scaffolding will generate class `price` and `price1` which is very confusing.

Since the schema can not be merged due to the difference in permissions, can we have an option that prefix entities with schema names so that the generated class would be `PigPrice` and `CowPrice`?

I had tried to separate the context by schema but it would be bad if they start adding cat and dog or maybe elephant which is very likely that it gonna happen.

**Comment by ErikEJ** [comment] 2020-11-18 06:39
Have you had a look at the renaming feature in EF Core Power Tools? https://github.com/ErikEJ/EFCorePowerTools/issues/488#issuecomment-685447772

**Comment by smitpatel** [comment] 2020-11-18 06:42
Duplicate of #3988

**Comment by Pearseak** [comment] 2020-11-18 06:48
> Have you had a look at the renaming feature in EF Core Power Tools? [ErikEJ/EFCorePowerTools#488 (comment)](https://github.com/ErikEJ/EFCorePowerTools/issues/488#issuecomment-685447772)

If I have 20 tables in each schema does that mean I have to explicitly rename 100 tables if I have 4 schemas? or there are any helpers?

**Comment by fastfoot** [comment] 2020-11-18 10:52
I have many schemas id db too, maybe some {{schema}} makro will resolve this problem ?

**Comment by ajcvickers** [comment] 2020-11-20 21:07
As mentioned above, this is tracked by #3988. Also, reverse-engineering templates (#4038) would allow fully flexible naming here.

**Comment by Pearseak** [comment] 2020-11-24 07:37
I made this mini project for anyone who really needs this right now.

https://github.com/Pearseak/scaffold-with-schema-prefix

**Closed** 2022-10-16 19:10 UTC
Labels: customer-reported
