### ISSUE TITLE
readonly datetime property in mysql always '0001-01-01'

### ISSUE THREAD

**Issue by at0717** [dotnet/efcore#10866] opened 2018-02-03 06:48 UTC
### When I use the readonly property for datetime without setter can't get right resutl in mysql

```c#
public DateTime CreatedDate { get; } = DateTime.Now;
```
or
```c#
class SomeType
{
    SomeType()
    {
        CreatedDate  = Datetime.Now;
    }
    public DateTime CreatedDate { get; } 
}

```
after ef saved, the value always '0001-01-01'
if give it a setter,there will be a right value

### Further technical details
DotNet Core Version: 2.1.4
EF Core Version: 2.0.1
DB Provider: MySql.Data.EntityFrameworkCore 6.10.6

**Comment by ajcvickers** [comment] 2018-02-03 20:08
@at0717 Without a runnable project/solution or full code listing it is hard to say what is going on, but my guess would be that the property is not mapped by convention because it does not have a setter. It will need to mapped explicitly, for example, with a .Property call in OnModelCreating.

**Comment by ajcvickers** [comment] 2018-02-12 21:05
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:08 UTC
Labels: closed-could-not-reproduce
