### ISSUE TITLE
SQL results with Linq IQueryable subquery includes extra columns

### ISSUE THREAD

**Issue by blogcraft** [dotnet/efcore#22342] opened 2020-09-01 00:26 UTC
I have a problem when using Joining IQueryable to an other query. 

The SQL generated includes columns that are not defined in the IQueryable and makes the result different than intended.

### Steps to reproduce

I have a query that consists of different IQueryable.

            IQueryable<TableA> aQuery = (from cue in _gpiContext.TableA
                                          join rel in _gpiContext.RelTableATableB on cue.IdTableA equals rel.IdTableA
                                          join gru in _gpiContext.TableB on rel.IdTableB equals gru.IdTableB
                                          where gru.EstTableB == Vigente
                                          && cue.FlgBloqueado == Desbloqueada
                                          && gru.IdTableB == (idGrupo ?? gru.IdTableB)
                                          select cue);

That I use in another query.

    var patrimonioQuery = (from cc in await _gpiContext.TableZ()
                                   join cu in aQuery on cc.IdTableA equals cu.IdTableA
                                   select new
                                   {
                                       X = cu.X,
                                       Y = cu.Y,
                                       Z = cc.Z
                                   });

Then when I run the query, EF translates this into the following SQL:

```
SELECT [t0].[IdTableA0] AS [IdCuenta], [t0].[X], [t0].[Y], [t0].[Z], [p].[D], [p].[F]
FROM [TableZ] AS [p]
INNER JOIN (
    SELECT [g].[IdTableA], [g].[X], [g].[Y], [g].[Z], [r].[IdTableB] AS [IdTableB], [c].[IdTableA] AS [IdTableA0], [c].[A], [c].[B], [c].[C]
    FROM [TableA] AS [g]
    INNER JOIN [RelTableATableB] AS [r] ON [g].[IdTableA] = [r].[IdTableA]
    INNER JOIN [TableB] AS [c] ON [r].[IdTableB] = [c].[IdTableB]
    WHERE (([g].[EstTableB] = 'VIG') AND ([c].[FlgBloqueado] = 'N')) AND ([g].[IdTableB] = COALESCE(null, [g].[IdTableB]))
) AS [t0] ON [p].[IdTableA] = [t0].[IdTableA0]
```

**Notice** the SQL included in the columns A, B and C from TableB Even tho the Linq selects only TableA. 

### Further technical details

EF Core version: 3.1.2
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET Core 3.1.401
Operating system: Windows 10 version 2004
IDE: Visual Studio Code

**Comment by smitpatel** [comment] 2020-09-04 14:59
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

Specifically, SQL contains Distinct operator but LINQ query does not. Which implies that the SQL posted is not associated with the LINQ query posted.

**Comment by ajcvickers** [comment] 2020-09-14 15:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:38 UTC
Labels: closed-could-not-reproduce, customer-reported
