### ISSUE TITLE
Add-Migration is not recognized in Package Manager unless two instances of the Microsoft.EntityFrameworkCore.Design package are installed.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#30547] opened 2023-03-22 09:58 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-Migration-is-not-recognized-in-Packa/10306894)._

---
I am building an ASP.NET Core 7 application in Visual Studio 2022. When installing Microsoft.EntityFrameworkCore.Tools package, a copy of the Microsoft.EntityFrameworkCore.Design is installed as well (see the image below).

After restarting Visual Studio 2022, I launched the Package Manager Console and typed Add-Migration. This returned the message that:

     `Add-Migration : The term 'Add-Migration' is not recognized...`.
If I install Microsoft.EntityFrameworkCore.Design separately a second instance of Microsoft.EntityFrameworkCore.Design is added to my Packages. However, Add-Migration is now recognized.

---
#### Feedback Bot on 3/13/2023, 02:28 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2023-04-05 17:19
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-04-05 17:19 UTC
Labels: closed-could-not-reproduce, customer-reported
