### ISSUE TITLE
Cannot delete a parent entity even there is no child referencing the parent.

### ISSUE THREAD

**Issue by EnterpriseIreland** [dotnet/efcore#10386] opened 2017-11-23 11:44 UTC
Hello,

I have two entities - BookableItemType and BookableItem which is one to many relation. 

BookableItemType Entity has many BookableItems
```c#
        public ICollection<BookableItem> BookableItems { get; set; } = new List<BookableItem>();
```
BookableItem has a parent
```c#
        [ForeignKey("BookableItemType")]
        public int BookableItemTypeId { get; set; }

        public BookableItemType BookableItemType { get; set; }
```

I have set to DeleteBehavior as restrict. 
```c#
            foreach (var relationship in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
            {
                relationship.DeleteBehavior = DeleteBehavior.Restrict;
            }
```
This should not delete the parent parent entity if it has no children.
However it throw an error 

```c#
The association between entity types 'BookableItemType' and 'BookableItem' has been severed but the foreign key for this relationship cannot be set to null. If the dependent entity should be deleted, then setup the relationship to use cascade deletes.
```
I have run the query in SSMS and there is no children referencing the parent entity.
Could you explain why it does not allow to delete the parent entity?

### Further technical details
EF Core version:     <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.2" />
Database Provider:      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.1" />
Operating system:  IDE: (e.g. Visual Studio 2017)

**Comment by ajcvickers** [comment] 2017-11-27 20:23
@EnterpriseIreland Can you post a full runnable project/solution or code listing that reproduces what you are seeing? (The exception should not be generated unless a dependent is actually being tracked.)

**Comment by ajcvickers** [comment] 2017-12-04 16:53
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:00 UTC
Labels: closed-could-not-reproduce
