### ISSUE TITLE
Initializing new empty List in query projection - results in shared instance among items.

### ISSUE THREAD

**Issue by kmolerov** [dotnet/efcore#14562] opened 2019-01-31 08:28 UTC
When having the following query:
var result = context	.MyItems				
	.Select(e => new {
		Id = e.Id,
		**SomeCollection = new List<string>()**
	})
	.ToList();
all items in **result** will have their SomeCollection proprty reference to the same instance of List<string> (shared instance among all items in "result").
How I found it:
foreach (var item in result)
{
     item.SomeCollection.Add(item.Id.ToString());
}
this will result in all items having SomeColleciton property filled with all Ids from "result" instead of having only one item in SomeColleciton property with their corresponding Id (for example if you have 5 items in result with ids 1,2,3,4,5 then item[0].SomeCollection will be filled with "1","2","3","4","5" instead of "1").

If this is made in Controller Action the instance of the collection will remain the same in all calls to the Action and the items inisde SomeCollection will aggragate in each API call! There must be something fundamentally wrong with the initial query compilation that is holding the instance as singelton.

Note:
It doesn't matter if projection is made to anonymous object or to some custom DTO type. 
It doesn't matter the type of the generic List that is instantiated in projection. I have tried it with List of some custom class and the result is the same (reference to one instance).

### Further technical details
EF Core version: 2.2
Database Provider: NpgSql
Operating system: Windows 8.1
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by smitpatel** [comment] 2019-01-31 16:22
Duplicate of #7983

**Closed** 2022-10-16 13:50 UTC
Labels: customer-reported
