### ISSUE TITLE
Incorrect Linq To SQL Generation, Nesting Too Deeply

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#19212] opened 2019-12-06 19:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/821204/incorrect-linq-to-sql-generation-nesting-too-deepl.html)._

---
<p>.Net Core 2.2 generates the Case expressions without nesting, but .Net Core 3.0 nests them, resulting in a &quot;SqlException: Case expressions may only be nested to level 10.&quot; The Linq expression is a standard shortcut of an if-statement, such as the following, nested to hundreds of levels for a variety of scheduling policies:</p><pre>     (o.Cycle == WhichCycle.Originally ? false :
     o.Cycle == WhichCycle.Eternally ? true :
     #region Qualifications
     o.Cycle == WhichCycle.Millennially ? EF.Functions.DateDiffYear(o.WhenStarted, now) % 1000 &lt;= 0 :
     o.Cycle == WhichCycle.Quinticenturily ? EF.Functions.DateDiffYear(o.WhenStarted, now) % 500 &lt;= 0 :
     o.Cycle == WhichCycle.Bicenturily ? EF.Functions.DateDiffYear(o.WhenStarted, now) % 200 &lt;= 0 :
</pre><p>In .Net Core 2.2, the generated SQL is flattened, hence running very efficiently. In .Net Core 3.0, the Case expressions are deeply nested.</p>

---
#### Visual Studio Feedback System on 11/14/2019, 10:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by smitpatel** [comment] 2019-12-06 22:24
Duplicate of #12729

**Comment by Yen-David** [comment] 2019-12-06 22:56
@smitpatel, it's not really a duplicate. It was fixed in .Net Core 2.2 but appeared again in .Net Core 3.0! You must re-close it (close it again).

**Comment by smitpatel** [comment] 2019-12-06 22:58
#12729 is closed in 5.0 milestone.

**Closed** 2022-10-16 18:00 UTC
Labels: closed-duplicate, customer-reported
