### ISSUE TITLE
AddData trying to insert timestamp/rowversion 

### ISSUE THREAD

**Issue by gpryce-dci** [dotnet/efcore#13996] opened 2018-11-22 04:05 UTC
After using modelBuilder.Entity<>().AddData, the generated seed data add the rowversion column even those I specify it as a [timestamp] coloumn.  If I try to supply a timestamp I guess this error during migration:
Cannot insert an explicit value into a timestamp column. Use INSERT with a column list to exclude the timestamp column, or insert a DEFAULT into the timestamp column.

if I leave it as null I get this error:
System.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated.

and if I try to set it to "DEFAULT" I get this error:
The seed entity fo

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
``System.InvalidOperationException: The seed entity for entity type 'Operation' cannot be added because the value provided for the property 'RowVersion' is not of the type 'byte[]'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the involved property values.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateData(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)`

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
 builder.HasData(new { Id = Utility.CreateNewId(), Name = x, Status = "Active,"  Description = x, RowVersion = "DEFAULT" });
```

### Further technical details
EF Core version: (found in project.csproj or packages.config) 2.1.4
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) 2.1.4
Operating system: Windows 10 
IDE: (e.g. Visual Studio 2017 15.4) Visual studio 2017

**Comment by ajcvickers** [comment] 2018-11-26 17:51
Duplicate of #11969

**Closed** 2022-10-16 13:41 UTC
Labels: closed-duplicate, customer-reported
