### ISSUE TITLE
Remove vs. Delete

### ISSUE THREAD

**Issue by kabua** [dotnet/efcore#3099] opened 2015-09-10 23:34 UTC
First off, I've only spent a few hours studying the EF 7 code base and I have to say "I LOVE IT!" I love the fact that it is clean, open and following good patterns. PLEASE keep up the good work! Can't wait to start using it in production.

Next, I dislike EF 1..6's Remove functionality. I don't like the fact that I have to remove the item from my DTO object (like: `model.Children.Remove(child)`) and then have to physically remove it from the DbSet (like: `context.Set<TModel>().Remove(child)`), just to delete an record from the database.

I know that there are times when one or more tables (or rows) may reference the same child and in those cases you don't want to physically delete the child but simply break the link between parent and child. However, most of the time, I see the case where removing the child from the parent DOES mean delete the child from the database.

Therefore, would it be possible to support a new type of `HashSet<T>` that would support both the ideas of "Remove" and "Delete"?

As in:
`model.Children.Remove(child)` // breaks the link between parent and child (as it does today). And...
`model.Children.Delete(child)`    // remove the child from the database (assuming that all constraints are meet, of course).

The current way feels more like working in C++; (remove for container, then delete from memory - yuck).

**Comment by rowanmiller** [comment] 2015-09-28 22:14
This is a duplicate of https://github.com/aspnet/EntityFramework/issues/333 (which is currently being implemented).

**Closed** 2022-10-16 09:08 UTC
