### ISSUE TITLE
Entity Framework 7 in memory database exception

### ISSUE THREAD

**Issue by bryanjhogan** [dotnet/efcore#4345] opened 2016-01-20 19:15 UTC
I hit a problem when using the in memory database for unit testing with EF 7. The following application will demonstrate the problem.

```
using System;
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Infrastructure;

namespace EF7InMemoryBug
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Program p = new Program();

            MembershipContext m1 = p.GetNewContext();
            MembershipContext m2 = p.GetNewContext();

            foreach (var member in m1.Members)
            {
                Console.WriteLine(member);
            }
        }

        private MembershipContext GetNewContext()
        {
            var optionsBuilder =
                new DbContextOptionsBuilder<MembershipContext>();
            optionsBuilder.UseInMemoryDatabase();

            MembershipContext context = new MembershipContext(optionsBuilder.Options);

            Member member1 = new Member()
            {
                MemberId = 1,
                FirstName = "James",
                LastName = "Jones"
            };

            context.Members.Add(member1);
            context.SaveChanges();
            return context;
        }

    }

    public class Member
    {
        public int MemberId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public override string ToString()
        {
            return $"{MemberId} {FirstName} {LastName}";
        }
    }

    public class MembershipContext : DbContext
    {
        public MembershipContext(DbContextOptions options)
        : base(options) {}
        public DbSet<Member> Members { get; set; }
    }
}
```

After calling `MembershipContext m2 = p.GetNewContext();` an exception is thrown on the `context.SaveChanges()`.

> An exception of type 'System.ArgumentException' occurred in EntityFramework.Core.dll but was not handled in user code
> 
> Additional information: An element with the same key but a different
> value already exists. Key:
> Microsoft.Data.Entity.ChangeTracking.Internal.SimpleKeyValue`1[System.Int32]

I know what is happening, but I don't know why. 

When `MembershipContext context = new MembershipContext(optionsBuilder.Options);` is called the second time, the context is created, BUT the `context.Members` already has the entry from the first time I created the context, hence the exception.

**Comment by bryanjhogan** [comment] 2016-01-22 14:06
Are people too busy to respond to this or is something about my issue unclear?

**Comment by ErikEJ** [comment] 2016-01-22 14:21
@bryanjhogan I think the team goes through new items once a week...

**Comment by bryanjhogan** [comment] 2016-01-22 14:23
@ErikEJ thanks

**Comment by rowanmiller** [comment] 2016-01-22 17:46
We've had a really high rate of incoming issues, so we go thru them several times a week... but we're still catching up. We're almost up to this one.

**Comment by mhenderson442** [comment] 2016-01-28 12:24
I am running into the same issue. Like @bryanjhogan, I am using the in memory database for unit testing. For what it's worth, I didn't run into this problem until I added a table with a composite primary key.

**Comment by rowanmiller** [comment] 2016-02-02 18:31
This looks by design, the `GetNewContext()` method inserts a new `Member` with a primary key of `1`. Your `Main` method calls this twice, meaning it is trying to insert two entities with a primary key value of `1`... which is not supported since primary key values are unique.

If you are wanting each context instance to connect to a new InMemory database, then take a look at http://docs.efproject.net/en/latest/miscellaneous/testing.html for an example of how to control the scope of the InMemory database.

**Comment by rowanmiller** [comment] 2016-02-02 18:32
Closing this one out as I am confident I've answered the question... but feel free to reopen if you disagree :smile:

**Comment by bryanjhogan** [comment] 2016-02-03 16:58
Thank Rowan. I was hoping for a way of achieving this without using the ServiceCollection. But if that is not possible, no problem.

**Comment by rowanmiller** [comment] 2016-02-03 17:45
@bryanjhogan yep we just bumped up the "named instance" feature for InMemory (#3253) to try and get it in sooner... so that you don't have to muck around with ServiceCollection.

**Closed** 2022-10-16 09:25 UTC
