### ISSUE TITLE
Multiple repeated records when using Include and ThenInclude

### ISSUE THREAD

**Issue by fkhasib** [dotnet/efcore#9553] opened 2017-08-24 15:07 UTC
This was suppose to be fixed by 2.0.0 but I still get this error, if I have an entity with Include and then include, I end up with multiple records for the same Entity Y
```
var q = dbTenantContext.Yes
                                        .Include(e => e.Y)
                                            .ThenInclude(e => e.YY)
                                                .ThenInclude(e => e.YYY)
                                                    .ThenInclude(e => e.YYYY)
                                        .Include(e => e.Y)
                                            .ThenInclude(e => e.YY)
                                                .ThenInclude(e => e.YYY)
                                                    .ThenInclude(e => e.YYYX)
                                                        .ThenInclude(e => e.YYYXX)
                                         .Include(e => e.Z)
                                            .ThenInclude(e => e.ZZ)
                                                .ThenInclude(e => e.ZZZ)
                                                    .ThenInclude(e => e.ZZZZ)
                                        .Include(e => e.Z)
                                            .ThenInclude(e => e.ZZ)
                                                .ThenInclude(e => e.ZZX)
                                                   .ThenInclude(e => e.ZZXX)
                                        .Where(e => e.IsDeleted != true)
```
I used to fix this in 1.1 by adding at the end of the query the following
```
.GroupBy(e => e.Id)
 .Select(e => e.First())
```
but now with 2.0.0 I am getting the following error if I add that group and select
```
Expression of type 'System.Object' cannot be used for parameter of type 'Microsoft.EntityFrameworkCore.Metadata.IEntityType'
```

Further technical details

EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: MS Windows 7
IDE: Visual Studio 2017

**Comment by smitpatel** [comment] 2017-08-24 21:07
duplicate of #9551

**Closed** 2022-10-16 11:18 UTC
