### ISSUE TITLE
System.Data.SqlTypes.SqlNullValueException: 'Data is Null. This method or property cannot be called on Null values.'

### ISSUE THREAD

**Issue by Looooooka** [dotnet/efcore#19090] opened 2019-11-27 13:36 UTC
basically using the rawsql command no longer works.
I tried adding a fake dbset property with the class that the query returns
tried adding the dbquery property and using that
there is simply no way to get the results anymore. this used to work fine and the query returns a list of items with the exact column names as expected in the class
how can one run a custom query with a custom class in EF Core 3 now?

**Comment by ajcvickers** [comment] 2019-12-02 17:19
@Looooooka Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing so we can fully investigate.

**Comment by ajcvickers** [comment] 2019-12-09 18:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:58 UTC
Labels: closed-could-not-reproduce, customer-reported
