### ISSUE TITLE
Support for joining tables from multiple databases

### ISSUE THREAD

**Issue by Mikilll94** [dotnet/efcore#14440] opened 2019-01-16 12:53 UTC
Are there any plans to support table JOINs from multiple databases?

Regards

### Further technical details
EF Core version: 2.2
Database Provider: Any
Operating system: Windows
IDE: (e.g. Visual Studio 2017 15.8)

**Comment by ajcvickers** [comment] 2019-01-17 18:19
Duplicate of #4019

**Closed** 2022-10-16 13:47 UTC
Labels: closed-duplicate, customer-reported
