### ISSUE TITLE
add-migration failed

### ISSUE THREAD

**Issue by dvdobrovolskiy** [dotnet/efcore#12033] opened 2018-05-16 20:21 UTC
fresh VS update brings fresh pain

dotnet ef migrations add NAME
from cmd works well but in package manager I get

PM> add-migration NAME
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\dima\source\repos\TNPK\TNPK\M:\Build\TNPK\net461\win7-x64\' because it does not exist.

Build path outside project folder (ram drive) - always worked well

Verbose does not bring any clue
PM> add-migration NAME -Verbose
Using project 'TNPK'.
Using startup project 'TNPK'.
Build started...
Build succeeded.
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\dima\source\repos\TNPK\TNPK\M:\Build\TNPK\net461\win7-x64\' because it does not exist.

**Comment by smitpatel** [comment] 2018-05-16 20:28
Can you share csproj?
`C:\Users\dima\source\repos\TNPK\TNPK\M:\Build\TNPK\net461\win7-x64` Something generated invalid path.

**Comment by dvdobrovolskiy** [comment] 2018-05-16 20:53
sure https://gist.github.com/dvdobrovolskiy/59f70c9e6ccab8ff8e7093e818d1a507

**Comment by bricelam** [comment] 2018-05-16 22:05
Duplicate of #11781

**Comment by bricelam** [comment] 2018-05-16 22:06
(As a workaround, you should be able to use the `dotnet ef` commands instead.)

**Comment by dvdobrovolskiy** [comment] 2018-05-16 23:03
sorry for dupe. Year, I mentioned I can use cmd and it works. Tnanks

**Comment by albertwoo** [comment] 2018-05-17 13:08
I have a similar issue, it can be easily reproduced in the project created by the latest dotnet (2.1.300-rc1-008673).
PM> Update-Database InitialCreate -Context OnTheWayDbContext
Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.0-rc1-32029 initialized 'OnTheWayDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: MaxPoolSize=128 
System.MissingMethodException: Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBuilder..ctor(Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlCommandBuilder..ctor(IDiagnosticsLogger`1 logger, IRelationalTypeMapper typeMapper)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlCommandBuilderFactory.CreateCore(IDiagnosticsLogger`1 logger, IRelationalTypeMapper relationalTypeMapper)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RawSqlCommandBuilder.Build(String sql)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBuilder..ctor(Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.

**Comment by bricelam** [comment] 2018-05-17 15:56
@albertwoo What version of the MySQL provider are you using? It looks like it may be incompatible with the version of EF Core you have installed.

**Comment by fradsham** [comment] 2020-02-27 18:26
I am experiencing a very similar issue. I have a .net standard 2.0 project with the DB context, a netcore 2.1.15 app project, and a wpf 4.7 app project, with the latter two referencing the net standard project. I recently add the following Directory.Build.props file (details below) to the solution directory so all items that are generated during the build process are outputted to a single /build directory and leaving my src directory unpolluted. Everything works fine except the ef commands I use in the package manager console (in VS 2019) no longer work. ex:

PM> Drop-Database -Context SqliteDbContext 

results in a error :

>The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\code\c#\MultiSpeciesDataLogger\src\DataProvider\C:\code\c#\MultiSpeciesDataLogger\build\bin\DataProvider\Debug\netstandard2.0\' because it does not exist.

You notice the dupicate file path. If I move the Directory.Build.props file from the Solution folder to just the wpf project folder, it works as expected, except I am back to seeing bin and obj folders polluting the subdirectories of the /src directory for the .net standard and dotnet core projects. The following is the Directory.Build.props file 

`<Project>
     <PropertyGroup>
          <BaseIntermediateOutputPath>$(SolutionDir)\build\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
          <IntermediateOutputPath>$(BaseIntermediateOutputPath)</IntermediateOutputPath>
    <OutputPath>$(SolutionDir)\build\bin\$(MSBuildProjectName)\$(Configuration)\</OutputPath>
  </PropertyGroup>
</Project>`

I wanted to see if there is any improvements on this in current or upcoming releases. I did not want to open a new issue, since it is linked to this one.

**Comment by ajcvickers** [comment] 2020-02-28 17:56
@fradsham This is a duplicate of issue #11781, which was fixed for EF Core 2.2. Please update to athe 3.1 release since EF Core 2.2 is now [out-of-support](https://docs.microsoft.com/en-us/ef/core/what-is-new/).

**Closed** 2022-10-16 12:25 UTC
Labels: customer-reported
