### ISSUE TITLE
Time in command log seems show only up to 999ms

### ISSUE THREAD

**Issue by rarera** [dotnet/efcore#25309] opened 2021-07-21 15:50 UTC
The maximum command duration I see in any of our logs is 999ms:

Executed DbCommand (999ms) [Parameters=[transcriptionId='?' (DbType = Guid), artifactSetId='?' (DbType = Guid)], CommandType='Text'

Can it be that Milliseconds is used instead of TotalMilliseconds? Alternatively can it be that only 3 digits are printed?

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0

**Comment by ErikEJ** [comment] 2021-07-21 18:21
Implementation looks ok, I think:

https://github.com/dotnet/efcore/blob/7d9ce9023b55aa316b0682c300c4d550d5235095/src/EFCore.Relational/Diagnostics/Internal/RelationalCommandDiagnosticsLogger.cs#L666

**Comment by rarera** [comment] 2021-07-22 15:16
Yes implementation looks ok, still it is suspicious that the max command time. I find in the logs is always 999 ms. It can probably be reproduced with ExexcuteSqlRaw("WAITFOR DELAY '00:00:02'")

**Comment by ajcvickers** [comment] 2021-07-26 13:19
@rarera This doesn't repro for me--see my code below. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .LogTo(Console.WriteLine, LogLevel.Information)
            .UseSqlServer(Your.ConnectionString)
            .EnableSensitiveDataLogging();
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Database.ExecuteSqlRaw("WAITFOR DELAY '00:00:02'");
        }
    }
}
```

Output:
```
info: 7/26/2021 14:17:39.703 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (2,002ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      WAITFOR DELAY '00:00:02'
```

**Comment by ajcvickers** [comment] 2021-08-03 15:27
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:40 UTC
Labels: closed-could-not-reproduce, customer-reported
