### ISSUE TITLE
Allow one-to-one transitive relationships

### ISSUE THREAD

**Issue by xperiandri** [dotnet/efcore#13269] opened 2018-09-09 19:00 UTC
I migrate from EF 6 which has TPT inheritance.
So that I have UserMembership to InternalContact 1-1 relationship which where InternalContact is a type derived from Contact.
And I've made InternalContact and ExternalContact as owned types of Contact to simulate TPT.
However, UserMembership is related to InternalContact which is not an entity. But defining EF Core model relationship from UserMembership to Contact does not work.

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro x64 1803
Visual Studio 2017 15.9 Preview 1

**Comment by ajcvickers** [comment] 2018-09-10 17:55
@xperiandri Can you please post a runnable project/solution or complete code listing showing the types and how they are configured and how the behavior is different from what you expect.

**Comment by xperiandri** [comment] 2018-09-16 22:26
Provided reproduction in private email.
Let me know if anything else required.

**Comment by ajcvickers** [comment] 2018-09-24 18:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by xperiandri** [comment] 2018-09-24 19:47
I uploaded an updated fixed version

**Comment by ajcvickers** [comment] 2018-09-25 16:28
@xperiandri Can you please answer the question above: 
> However, on looking at the code I am still unsure what you mean by, "made InternalContact and ExternalContact as owned types of Contact to simulate TPT". Can you post a simple example of what you mean by this?

**Comment by xperiandri** [comment] 2018-09-25 17:08
You can find this in `BaseDbContext.cs`
``` C#
builder.Entity<Contact>(c =>
{
    c.OwnsOne(contact => contact.Internal, ic =>
    {
        ic.ToTable("Contacts_InternalContact");
        ic.HasPrincipalKey("Id")
          .HasForeignKey("Id");
        ic.Property<long>("Id");
        ic.OwnsOne(intContact => intContact.Address, addr =>
        {
            addr.HasPrincipalKey("Id");
            addr.Property<long>("Id");

            addr.HasOne(address => address.StateProvince);
        });
    });

    c.OwnsOne(contact => contact.External, ec =>
    {
        ec.ToTable("Contacts_ExternalContact");
        ec.Property<long>("Id");
        ec.HasPrincipalKey("Id")
          .HasForeignKey("Id");
    });
});
```

**Comment by xperiandri** [comment] 2018-09-25 17:12
Then I database I have a foreign key from Internal Contact to UserMemebership.
And foreign key from InternalContact to Contact.
But I cannot establish a transitive relationship from InternalContact to UserMemebership or vice versa.

**Comment by xperiandri** [comment] 2018-09-25 17:18
``` C#
public class Contact: ICompanyBound
{
    public long CompanyId { get; set; }

    public InternalContact Internal { get; set; }
    public ExternalContact External { get; set; }
}

public class InternalContact
{
    public string FirstName { get; set; }
    public string LastName { get; set; }

    public UserMembership User { get; set; }
}

public class ExternalContact
{
    public long TargetCompanyId { get; set; }
}

public class UserMembership
{
    public long Id { get; set; }
    public string Login { get; set; }
    public string Password { get; set; }
    public UserRole Role { get; set; }
    public string RegistrationCoupon { get; set; }
    public string SessionId { get; set; }
    public DateTime? SessionExpiration { get; set; }
    public string ConfirmationKey { get; set; }
    public DateTime? ConfirmationExpiration { get; set; }
    public bool IsConfirmed { get; set; }

    public Contact InternalContact { get; set; }
}
```

**Comment by ajcvickers** [comment] 2018-10-02 20:54
@xperiandri After digging through the configuration it's still hard for me to tell exactly what the intention is, but it looks like an attempt is being made to configure an owned type as the principal end of a relationship, which is not supported. If that's not the case, then it would be really helpful to see the database structure that you are attempting to map to so I can see exactly where the FKs are defined.

**Comment by ajcvickers** [comment] 2018-10-10 17:58
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:30 UTC
Labels: closed-could-not-reproduce, customer-reported
