### ISSUE TITLE
Should I be able to use the EF Core tools to apply migrations when using an interceptor to set my connection string

### ISSUE THREAD

**Issue by mdemler** [dotnet/efcore#31055] opened 2023-06-07 22:18 UTC
Should the EF Core tools work when using an interceptor to set the connection string?

We're using EF Core 7 with PosgreSQL.  We're deriving from DbConnectionInterceptor and overriding ConnectionOpenAsync to set the connection string using a value that we construct at runtime.

Previously, before switching to this model, we were able to use **dotnet ef database update** to apply generated migrations to the database, but now we're receiving a "Host can't be null" error.

This error does look to originate from with Npgsql, but before bugging those folks, I wanted to check to see if this is something that should even be supported.  I wasn't able to find details on how the tools go about establishing a database connection.  Both our current and prior approaches were implemented by overriding OnModelCreating() for the DbContext.

Here's our current approach:

```
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var interceptor = new DbConnectionInterceptorDerivative();

            optionsBuilder.AddInterceptors(interceptor);

            optionsBuilder.UseNpgsql();
        }

```
Here's the callstack of the error reported by the tool:

```
System.ArgumentException: Host can't be null
   at Npgsql.NpgsqlConnectionStringBuilder.PostProcessAndValidate()
   at Npgsql.NpgsqlConnection.SetupDataSource()
   at Npgsql.NpgsqlConnection.set_ConnectionString(String value)
   at Npgsql.NpgsqlConnection..ctor(String connectionString)
   at Npgsql.NpgsqlConnection.CloneWith(String connectionString)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlRelationalConnection.CloneWith(String connectionString)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Host can't be null

```

**Comment by ajcvickers** [comment] 2023-06-19 12:43
@mdemler Looks like the command line tools use the sync API, so you'll need to override `ConnectionOpening` as well as `ConnectionOpeningAsync`.

Note for triage: is this okay?

**Comment by mdemler** [comment] 2023-06-19 14:50
@ajcvickers Thanks for getting to me.  I just gave that a try, and it unfortunately didn't seem to make a difference.  I had ConnectionOpening being overridden and throwing a NotSupportException previously, which wasn't triggering.

**Comment by ajcvickers** [comment] 2023-06-21 19:40
@mdemler I'm not able to reproduce this either with the SQL Server or the Npgsql provider. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-07-07 16:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by mdemler** [comment] 2023-07-21 20:07
@ajcvickers - Can this issue please be reopened now that I've provided an example?

**Comment by ajcvickers** [comment] 2023-07-27 10:48
@roji This repros using the Npgsql provider, but not with SQL Server. Changing the interceptor to set a valid connection string, I get the following with PostgreSQL:

```
dbug: 7/27/2023 11:42:51.841 CoreEventId.ContextInitialized[10403] (Microsoft.EntityFrameworkCore.Infrastructure)
      Entity Framework Core 7.0.9 initialized 'SampleDBContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL:7.0.4+96806371445869d20be357993820cd4be366e145' with options: SensitiveDataLoggingEnabled
dbug: 7/27/2023 11:42:51.851 RelationalEventId.ConnectionCreating[20005] (Microsoft.EntityFrameworkCore.Database.Connection)
      Creating DbConnection.
dbug: 7/27/2023 11:42:51.855 RelationalEventId.ConnectionCreated[20006] (Microsoft.EntityFrameworkCore.Database.Connection)
      Created DbConnection. (2ms).
dbug: 7/27/2023 11:42:51.856 RelationalEventId.MigrateUsingConnection[20400] (Microsoft.EntityFrameworkCore.Migrations)
      Migrating using database '' on server ''.
dbug: 7/27/2023 11:42:51.871 CoreEventId.ContextDisposed[10407] (Microsoft.EntityFrameworkCore.Infrastructure)
      'SampleDBContext' disposed.
dbug: 7/27/2023 11:42:51.873 RelationalEventId.ConnectionDisposing[20007] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposing connection to database '' on server ''.
dbug: 7/27/2023 11:42:51.875 RelationalEventId.ConnectionDisposed[20008] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposed connection to database '' on server '' (0ms).
System.ArgumentException: Host can't be null
   at Npgsql.NpgsqlConnectionStringBuilder.PostProcessAndValidate()
   at Npgsql.NpgsqlConnection.SetupDataSource()
   at Npgsql.NpgsqlConnection.set_ConnectionString(String value)
   at Npgsql.NpgsqlConnection..ctor(String connectionString)
   at Npgsql.NpgsqlConnection.CloneWith(String connectionString)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlRelationalConnection.CloneWith(String connectionString)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Host can't be null
```

But this with SQL Server:

```
dbug: 7/27/2023 11:46:18.317 CoreEventId.ContextInitialized[10403] (Microsoft.EntityFrameworkCore.Infrastructure)
      Entity Framework Core 7.0.9 initialized 'SampleDBContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:7.0.9' with options: SensitiveDataLoggingEnabled
dbug: 7/27/2023 11:46:18.328 RelationalEventId.ConnectionCreating[20005] (Microsoft.EntityFrameworkCore.Database.Connection)
      Creating DbConnection.
dbug: 7/27/2023 11:46:18.341 RelationalEventId.ConnectionCreated[20006] (Microsoft.EntityFrameworkCore.Database.Connection)
      Created DbConnection. (12ms).
dbug: 7/27/2023 11:46:18.342 RelationalEventId.MigrateUsingConnection[20400] (Microsoft.EntityFrameworkCore.Migrations)
      Migrating using database '' on server ''.
dbug: 7/27/2023 11:46:18.345 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database '' on server ''.
dbug: 7/27/2023 11:46:19.101 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.105 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: 7/27/2023 11:46:19.109 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteNonQuery' (3ms).
dbug: 7/27/2023 11:46:19.111 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteNonQuery' (6ms).
dbug: 7/27/2023 11:46:19.115 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
info: 7/27/2023 11:46:19.128 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (14ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
dbug: 7/27/2023 11:46:19.129 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.134 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB' (3ms).
dbug: 7/27/2023 11:46:19.136 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteScalar'.
dbug: 7/27/2023 11:46:19.136 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteScalar' (0ms).
dbug: 7/27/2023 11:46:19.137 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteScalar' (0ms).
dbug: 7/27/2023 11:46:19.137 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.137 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.138 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
info: 7/27/2023 11:46:19.146 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
dbug: 7/27/2023 11:46:19.146 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.147 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB' (0ms).
dbug: 7/27/2023 11:46:19.147 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.147 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.148 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: 7/27/2023 11:46:19.148 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 7/27/2023 11:46:19.148 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 7/27/2023 11:46:19.148 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
info: 7/27/2023 11:46:19.149 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
dbug: 7/27/2023 11:46:19.149 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.149 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB' (0ms).
dbug: 7/27/2023 11:46:19.150 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteScalar'.
dbug: 7/27/2023 11:46:19.150 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteScalar' (0ms).
dbug: 7/27/2023 11:46:19.150 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteScalar' (0ms).
dbug: 7/27/2023 11:46:19.150 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.150 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.150 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
info: 7/27/2023 11:46:19.151 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
dbug: 7/27/2023 11:46:19.151 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.151 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB' (0ms).
dbug: 7/27/2023 11:46:19.253 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteReader'.
dbug: 7/27/2023 11:46:19.253 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteReader' (0ms).
dbug: 7/27/2023 11:46:19.253 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteReader' (0ms).
dbug: 7/27/2023 11:46:19.253 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.254 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.254 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
info: 7/27/2023 11:46:19.256 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
dbug: 7/27/2023 11:46:19.258 RelationalEventId.DataReaderClosing[20301] (Microsoft.EntityFrameworkCore.Database.Command)
      Closing data reader to 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.259 RelationalEventId.DataReaderDisposing[20300] (Microsoft.EntityFrameworkCore.Database.Command)
      A data reader for 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB' is being disposed after spending 1ms reading results.
dbug: 7/27/2023 11:46:19.259 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.259 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB' (0ms).
Applying migration '20230727104610_One'.
info: 7/27/2023 11:46:19.268 RelationalEventId.MigrationApplying[20402] (Microsoft.EntityFrameworkCore.Migrations)
      Applying migration '20230727104610_One'.
dbug: 7/27/2023 11:46:19.273 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.273 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.275 RelationalEventId.TransactionStarting[20209] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Beginning transaction with isolation level 'Unspecified'.
dbug: 7/27/2023 11:46:19.278 RelationalEventId.TransactionStarted[20200] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Began transaction with isolation level 'ReadCommitted'.
dbug: 7/27/2023 11:46:19.279 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: 7/27/2023 11:46:19.279 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 7/27/2023 11:46:19.280 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 7/27/2023 11:46:19.280 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
      VALUES (N'20230727104610_One', N'7.0.9');
info: 7/27/2023 11:46:19.281 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
      VALUES (N'20230727104610_One', N'7.0.9');
dbug: 7/27/2023 11:46:19.283 RelationalEventId.TransactionCommitting[20210] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Committing transaction.
dbug: 7/27/2023 11:46:19.285 RelationalEventId.TransactionCommitted[20202] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Committed transaction.
dbug: 7/27/2023 11:46:19.286 RelationalEventId.TransactionDisposed[20204] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Disposing transaction.
dbug: 7/27/2023 11:46:19.286 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.286 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB' (0ms).
dbug: 7/27/2023 11:46:19.288 CoreEventId.ContextDisposed[10407] (Microsoft.EntityFrameworkCore.Infrastructure)
      'SampleDBContext' disposed.
dbug: 7/27/2023 11:46:19.289 RelationalEventId.ConnectionDisposing[20007] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposing connection to database 'AllTogetherNow' on server '(LocalDb)\MSSQLLocalDB'.
dbug: 7/27/2023 11:46:19.289 RelationalEventId.ConnectionDisposed[20008] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposed connection to database '' on server '' (0ms).
Done.
```

**Comment by roji** [comment] 2023-09-21 12:51
Moved this out to https://github.com/npgsql/efcore.pg/issues/2880 as it's Npgsql-specific.

**Closed by roji** 2023-09-21 12:51 UTC
Labels: customer-reported
