### ISSUE TITLE
EF Core self referencing not working if there are 2 foreign keys to self (Code first)

### ISSUE THREAD

**Issue by MaklaCof** [dotnet/efcore#10123] opened 2017-10-19 19:13 UTC
If I defined (in code first) one navigation property to self it works (foreign key is created), but if I define 2 it doesn't work.

```
Exception message: No exception, column in SQL Server is not created as Foreign key.
```

### Steps to reproduce
This works:
```c#
public class DbPart 
{
    [Key]
    [Required]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [ForeignKey("Source")]
    public int? SourceId { get; set; }
    public DbPart Source { get; set; }

    [InverseProperty("Source")]
    public List<DbPart> SourceParts { get; set; }
}
```
also this:
```c#
public class DbPart 
{
    [Key]
    [Required]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [ForeignKey("SourceFake")]
    public int? SourceFakeId { get; set; }
    public DbPart SourceFake { get; set; }

    [InverseProperty("SourceFake")]
    public List<DbPart> SourceFakeParts { get; set; }
}
```
but not this:
```c#
public class DbPart 
{
    [Key]
    [Required]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [ForeignKey("Source")]
    public int? SourceId { get; set; }
    public DbPart Source { get; set; }


    [ForeignKey("SourceFake")]
    public int? SourceFakeId { get; set; }
    public DbPart SourceFake { get; set; }

    [InverseProperty("SourceFake")]
    public List<DbPart> SourceFakeParts { get; set; }

    [InverseProperty("Source")]
    public List<DbPart> SourceParts { get; set; }
}
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 64-bit
IDE: Visual Studio 2017

Code works with fluent code. Before bug report I also post question on [SO](https://stackoverflow.com/questions/46827795/ef-core-self-referencing-not-working-if-there-are-2-foreign-keys-to-self-code-f).

**Comment by smitpatel** [comment] 2017-10-19 19:33
Possible 
Duplicate of #9180 

Can you try with no `[Key]` attribute used?

**Comment by ajcvickers** [comment] 2017-10-19 19:36
For me, the code above creates the model below, which looks right to me, and results in the SQL below, which also looks correct. Can you post a full code listing or project that reproduces what you are seeing?
> Model: 
  EntityType: DbPart
    Properties: 
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
      SourceFakeId (Nullable<int>) FK Index 1 1 1 -1 1
      SourceId (Nullable<int>) FK Index 2 2 2 -1 2
    Navigations: 
      Source (<Source>k__BackingField, DbPart) ToPrincipal DbPart Inverse: SourceParts 0 -1 3 -1 -1
      SourceFake (<SourceFake>k__BackingField, DbPart) ToPrincipal DbPart Inverse: SourceFakeParts 1 -1 4 -1 -1
      SourceFakeParts (<SourceFakeParts>k__BackingField, List<DbPart>) Collection ToDependent DbPart Inverse: SourceFake 2 -1 5 -1 -1
      SourceParts (<SourceParts>k__BackingField, List<DbPart>) Collection ToDependent DbPart Inverse: Source 3 -1 6 -1 -1
    Keys: 
      Id PK
    Foreign keys: 
      DbPart {'SourceFakeId'} -> DbPart {'Id'} ToDependent: SourceFakeParts ToPrincipal: SourceFake
      DbPart {'SourceId'} -> DbPart {'Id'} ToDependent: SourceParts ToPrincipal: Source

```sql
CREATE TABLE [DbParts] (
    [Id] int NOT NULL IDENTITY,
    [SourceFakeId] int NULL,
    [SourceId] int NULL,
    CONSTRAINT [PK_DbParts] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_DbParts_DbParts_SourceFakeId] FOREIGN KEY ([SourceFakeId]) REFERENCES [DbParts] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_DbParts_DbParts_SourceId] FOREIGN KEY ([SourceId]) REFERENCES [DbParts] ([Id]) ON DELETE NO ACTION
);
CREATE INDEX [IX_DbParts_SourceFakeId] ON [DbParts] ([SourceFakeId]);
CREATE INDEX [IX_DbParts_SourceFakeId] ON [DbParts] ([SourceFakeId]);
CREATE INDEX [IX_DbParts_SourceId] ON [DbParts] ([SourceId]);
CREATE INDEX [IX_DbParts_SourceId] ON [DbParts] ([SourceId]);
```

**Comment by MaklaCof** [comment] 2017-10-20 05:25
Removing
```
        [Key]
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
```
did it. Foreign keys are (or will be) created:
```
            migrationBuilder.CreateTable(
                name: "VarDesign_Parts",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    SourceFakeId = table.Column<int>(type: "int", nullable: true),
                    SourceId = table.Column<int>(type: "int", nullable: true),
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_VarDesign_Parts", x => x.Id);
                    table.ForeignKey(
                        name: "FK_VarDesign_Parts_VarDesign_Parts_SourceFakeId",
                        column: x => x.SourceFakeId,
                        principalTable: "VarDesign_Parts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_VarDesign_Parts_VarDesign_Parts_SourceId",
                        column: x => x.SourceId,
                        principalTable: "VarDesign_Parts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });
```

With `[Key]` migration was:
```
            migrationBuilder.CreateTable(
                name: "VarDesign_Parts",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    SourceFakeId = table.Column<int>(type: "int", nullable: true),
                    SourceId = table.Column<int>(type: "int", nullable: true),
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_VarDesign_Parts", x => x.Id);
                });
```

@ajcvickers Hope this helps.
My database does not exists yet and I am using command 
`dotnet ef migrations add "Initial" -o "Server\Data\Migrations"`

**Closed** 2022-10-16 11:55 UTC
