### ISSUE TITLE
Multiple entity insert, unique key violation fires ConcurrencyException 

### ISSUE THREAD

**Issue by kenfolza** [dotnet/efcore#20649] opened 2020-04-15 15:20 UTC
Hi,

We use ef core 3.1.2 and ms sql server in our project. We have an unique key (on 'name' column) on a table.
If we try to insert one entity in a single transaction ef core fires unique key exception (DbUpdateException) as expected.
But when we try to insert different entities in a single transaction and one of the tables has a unique key violation, ef core fires DBConcurrency Exception. But it has to be a unique key exception. 

### Further technical details

EF Core version: 3.1.2
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment] 2020-04-15 16:49
@kenfolza Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by kenfolza** [comment] 2020-04-16 08:15
Hi again,
Sorry for duplicated issues. I realized that the problem is not about saving multiple entities in a single transaction. There was a problem with a specific entity.
Let's have two tables, Table A and Table B. Table A has an **unique index** with multiple columns. If i try to insert a record which violates the unique index, ef core fires unique index violation exception as expected. 
Table B has an **unique key constraint** (not index)  with multiple columns. If i try to insert a record which violates the unique key, ef core fires dbconcurrency exception. If i remove the unique key from Table B and add the rule as a new "unique index", problem is being solved. 
But i think that ef core has to fire the same exception for unique key constraints too.

**Comment by ajcvickers** [comment] 2020-04-16 14:35
@kenfolza Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by kenfolza** [comment] 2020-04-17 07:41
Hi again, i have created a sample table named 'Test' (sql script is in the zip file) . Test table has a unique key constraint named 'IX_Test_Number_Date' which has 4 columns. According to the sample code below, second time i try to insert the data, i am expecting unique key violation exception but 'Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. ' exception occurs. 

` static void Main(string[] args)
        {
            try
            {
                var context = new AviationDBManagementContext();
                context.Test.Add(new Test { FlightNumber = "1", DepartureDate = DateTime.Today, ArrivalDate=DateTime.Today,DepartureAirportId=1,ArrivalAirportId=2,VehicleType=0});
                context.SaveChanges();
                Console.WriteLine("Hello World!");
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }`

[TestTableScript.zip](https://github.com/dotnet/efcore/files/4491588/TestTableScript.zip)

**Comment by ajcvickers** [comment] 2020-05-04 16:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:20 UTC
Labels: closed-could-not-reproduce, customer-reported
