### ISSUE TITLE
DbContext.SaveChanges() doesn't work after DbContext.Dbset<T>.Add(Entity) InvalidOperationException

### ISSUE THREAD

**Issue by khoren-mansuryan** [dotnet/efcore#9835] opened 2017-09-15 21:45 UTC
I have a simple model named Person that has ID (PK) , Name and Surname properties wich are combined AlternateKey. 
There is one record in database Id=1, Name="John" Surname="Smith"
After creating and loading whole data by DBSet.Load()
i'm trying to add a new person in DbSet with Name="John", Surname="Smith" (wich cause uniqe conflit) with DbSet.Add(Person) and getting a InvalidOperation Exception, After, i'm removing entity from context by DBContext.DbSet.Remove(Person) and adding another Person with Name="aaa" Surname="bbb" and do SaveChanges() and get 0 for result and no exception. 
**Question: WHY those operations doesn't add second added Person to the database.**

Exception message when adding unique name,surname pair to DbSet: "The instance of entity type 'Customer' cannot be tracked because another instance with the same key value for {'Name', 'Surname'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values."

Stack trace:
"   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean forceStateWhenUnknownKey)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)\r\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState entityState, Boolean forceStateWhenUnknownKey)\r\n   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)\r\n   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)\r\n   at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity](TEntity entity)\r\n   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)\r\n   at Store.MainForm.button1_Click_1(Object sender, EventArgs e) in line 232"

c#

``` C#
 public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    }
    public class PersonConfiguratinon : IEntityTypeConfiguration<Person>
   {
        public void Configure(EntityTypeBuilder<Person> builder)
        {
           builder.HasKey(p => p.Id);
           builder.Property(p => p.Name).IsRequired().HasMaxLength(200);
          builder.Property(p => p.Name).IsRequired(false).HasMaxLength(200);
       }
    }
    public class StoreContext : DbContext
    {
        public virtual DbSet<Person> People { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
           {
  
             optionsBuilder.UseSqlServer(ConfigurationManager
                            .ConnectionStrings["StoreContext"].ConnectionString);
            optionsBuilder.ConfigureWarnings(warnings => warnings
                              .Throw(new EventId[]
                                  {
                                       CoreEventId.IncludeIgnoredWarning,
                                       RelationalEventId.QueryClientEvaluationWarning
                                  }));
           }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
                   {
                       modelBuilder.ApplyConfiguration(new PersonConfiguratinon());
                       modelBuilder.Entity<Person>().HasAlternateKey(c => new { c.Name, c.Surname });
                   }
}
```
Code
``` C#
 using (StoreContext context = new StoreContext())
            {
                Person person = new Person
                {
                    Name = "John",
                    Surname = "Smith",
                };
                context.People.Add(person);
                context.SaveChanges();
            }
            using (StoreContext context = new StoreContext())
            {
                
                context.People.Load();
                Person person = new Person
                {
                    Name = "John",
                    Surname = "Smith",
                };

                try
                {
                    context.People.Add(person);
                }
                catch (Exception)
                { 
                   //Exception because of unique Name and Surname
                    context.People.Remove(person);
                }
                var anotherPerson = new Person
                {
                    Name = "aaa",
                    Surname = "bbb",
                };
                context.People.Add(anotherPerson);
                int i = context.SaveChanges(); // i=0 after SaveChanges()
            }
```
technical details
EF Core version: Microsoft.EntityFrameworkCore" version="2.0.0" targetFramework="net47"
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 x64
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment] 2017-09-15 22:01
@xoro91 Can you show the code that does the actual updates?

**Comment by xoro91** [comment] 2017-09-15 22:03
@ajcvickers sorry, i forgot about it

**Comment by xoro91** [comment] 2017-09-15 22:15
@ajcvickers I can givve you full project by email

**Comment by ajcvickers** [comment] 2017-09-18 17:52
@xoro91 You can contact me as avickers at the place I work.

**Comment by xoro91** [comment] 2017-09-19 05:29
I did not understand exactly how I can get in touch with you.

**Comment by xoro91** [comment] 2017-09-19 05:32
Could you reproduce the problem?

**Comment by ajcvickers** [comment] 2017-09-19 20:46
@xoro91 Looks like there is an issue here that the context is left in a bad state after the exception. We will look into this, but in general it's not a good idea to use this kind of exception to do flow control in your application code. That is, application code should strive to not put the model in an inconsistent state though tracking multiple entities with the same key. If the context does get into this state, it usually indicates an application bug that needs to be fixed.

**Comment by xoro91** [comment] 2017-09-20 05:30
Well. hope you will fix fix this bug. Thank you.

**Comment by ajcvickers** [comment] 2017-09-20 20:04
Notes from triage: we will look into this and consider doing rollback in some simple cases and/or putting the context into a "Corrupted" state that forces a new context to be used after an error like this. That might constitute a breaking change, so it might need to wait for a major version--adding label so we look at this when planning next major.

**Comment by ajcvickers** [comment] 2018-05-17 21:50
Filed [a docs issue to document current behavior](https://github.com/aspnet/EntityFrameworkCore/issues/9835) and closing this for now. As always, we could revisit based on feedback.

**Comment by cristian-eriomenco** [comment] 2021-05-11 13:19
@ajcvickers Any updates on this one? Seems wrong for the DbContext to malfunction after an exception being thrown.

If I have a Seed scenario where the Seed method might be executed multiple times and I do consider UniqueKeyConstraintException to be a false negative, why would everything fail implicitly? Think about it from a consumer perspective, if this would be ADO.NET there wouldn't be any concept of session, effectively treating the calls to DB as stateless.

What is the temporary solution for cases like this? P.S. Overbloating the consumer code with lifecycle management of the efcontext for exception cases is something I'd really prefer to avoid.

Sorry If I haven't been polite correct but its been an eternity since EF is putting its beans together, and only hopes and crossed fingers are the sole reason why I still didn't gave up on it. Thanks

**Closed** 2022-10-16 11:50 UTC
Labels: closed-out-of-scope, customer-reported
