### ISSUE TITLE
Support Scoped ConnectionString with DbContextPool and Managed Identity

### ISSUE THREAD

**Issue by Eneuman** [dotnet/efcore#19906] opened 2020-02-13 13:14 UTC
We have a MicroServices solution with 40 services.
Each customer (Tenant) has there own database. All database have the same schema.

A microservice needs to connect to the right database based on the tenant information in the user claims. The connection also need to user Managed Identity as authentication agains Azure SQL (Token based)

Since all the databases have the same schema I want to use a DbContextPool, but I want to change the connectionstring by custom logic (per scope)

It would be great if I could inject a ConnectionStringFactory that resolves my connectionstring and sets the token.

I think I have a found a working solution, however, it relies on internal methods.
A more "supported" option would be prefered.

**Startup.cs**
`services.AddDbContextPool<Infrastructure.MyDbContext>(options => options.UseTenantConnection(Configuration));`

**AzureSqlServerConnectionExtensions.cs** (based on the code found [here](https://gist.github.com/ChristopherHaws/b1c54b95838f1513bfb74fa1c8e408f3))
```
using Microsoft.AspNetCore.Http;
using Microsoft.Azure.Services.AppAuthentication;
using Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using System;
using System.Data.Common;
using System.Data.SqlClient;
using System.Linq;

namespace Microsoft.EntityFrameworkCore
{
  public static class AzureSqlServerConnectionExtensions
  {
    public static void UseTenantConnection(this DbContextOptionsBuilder options, IConfiguration configuration)
    {
      var serviceColection = new ServiceCollection()
      .AddEntityFrameworkSqlServer()
      .AddHttpContextAccessor()
      .AddSingleton(configuration);

      serviceColection.Replace(ServiceDescriptor.Scoped<ISqlServerConnection, AzureSqlServerConnection>());

      var services = serviceColection.BuildServiceProvider();

      options.UseInternalServiceProvider(services);
      options.UseSqlServer("Fake", providerOptions => providerOptions.EnableRetryOnFailure()).EnableSensitiveDataLogging(true);
    }
  }

  [System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "EF1001:Internal EF Core API usage.", Justification = "pending")]
  public class AzureSqlServerConnection : SqlServerConnection
  {
    // Compensate for slow SQL Server database creation
    private readonly IHttpContextAccessor _contextAccessor;
    private readonly IConfiguration _configuration;

    private const int DefaultMasterConnectionCommandTimeout = 60;
    private static readonly AzureServiceTokenProvider TokenProvider = new AzureServiceTokenProvider();

    public AzureSqlServerConnection(RelationalConnectionDependencies dependencies, IHttpContextAccessor contextAccessor, IConfiguration configuration) : base(dependencies)
    {
      _contextAccessor = contextAccessor ?? throw new ArgumentNullException(nameof(contextAccessor));
      _configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
    }

    protected override DbConnection CreateDbConnection() => new Data.SqlClient.SqlConnection(GetTenantConnectionString())
    {
      AccessToken = TokenProvider.GetAccessTokenAsync("https://database.windows.net/", "<my tenant id>").Result
    };

    public override ISqlServerConnection CreateMasterConnection()
    {
      var connectionStringBuilder = new SqlConnectionStringBuilder(GetTenantConnectionString())
      {
        InitialCatalog = "master"
      };
      connectionStringBuilder.Remove("AttachDBFilename");

      var contextOptions = new DbContextOptionsBuilder()
        .UseSqlServer(
          connectionStringBuilder.ConnectionString,
          b => b.CommandTimeout(this.CommandTimeout ?? DefaultMasterConnectionCommandTimeout))
        .Options;

      return new AzureSqlServerConnection(this.Dependencies.With(contextOptions), _contextAccessor, _configuration);
    }

    private string GetTenantConnectionString()
    {
      var tenantId = _contextAccessor.HttpContext.User.Claims.First(c => c.Type == "tenantId").Value;
      return _configuration[$"Tenant{tenantId}:DatabaseConnectionString"];
    }
  }
}
```

**Comment by AndriySvyryd** [comment] 2020-02-13 19:01
Something similar will be available in 5.0.0
Duplicate of https://github.com/dotnet/efcore/issues/8494

**Closed** 2022-10-16 18:10 UTC
Labels: customer-reported
