### ISSUE TITLE
Generate incorrect migration when using owned entity

### ISSUE THREAD

**Issue by phuong-n-d** [dotnet/efcore#12947] opened 2018-08-09 09:19 UTC
I'm facing an issue when using design owned entity as follow:

I have Address class and it is marked as [Owned]. The Address entity also own the Country. Then I have 2 others entities owned the Address and 1 entity directly own the Country. 

```C#
[Owned]
public class Address
{
    public string Street { get; set; }
    public string Ward { get; set; }
    public string City { get; set; }
    public Country Country { get; set; }
}

[Owned]
public class Country
{
    public string Name { get; set; }
    public string Code { get; set; }
}

public class Buyer
{
    public int Id { get; set; }
    public Address Address { get; set; } // owned Address => Country
}

public class Shipper
{
    public int Id { get; set; }

    public Address Address { get; set; } // owned Address => Country
}

public class Product
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Country MadeInCountry { get; set; } // owned Country directly
}
```

When I added the first migration, everything look good. However, for the second times and later, even though I did not modify anything, the new migration generated as follow:

```C#
public partial class Test : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "Address_Country_AddressBuyerId",
            table: "Buyers");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<int>(
            name: "Address_Country_AddressBuyerId",
            table: "Buyers",
            nullable: false,
            defaultValue: 0)
            .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
    }
}
```

Column **Address_Country_AddressBuyerId** does not exist on Buyers table and I cannot update the database. If I remove the MadeInCountry property which is type of Country and be owned directly from Product entity, everything is ok.

Question: Does EF core support this scenario?

**Comment by phuong-n-d** [comment] 2018-08-10 02:53
Hi, I found that if I add one more entity with name order before the Product (eg. AbcModel and also own Address), it's fined. Is this a bug?

**Comment by ajcvickers** [comment] 2018-08-10 16:15
Note for triage: looks like a duplicate of #12107

**Comment by ajcvickers** [comment] 2018-08-10 22:04
Closing as duplicate of #12107, which will be released with the next patch.

**Closed** 2022-10-16 13:24 UTC
Labels: closed-duplicate, customer-reported
