### ISSUE TITLE
Cosmos DB Provider - Only root Container entity can have more than one Owned property (and get data)

### ISSUE THREAD

**Issue by bobbydowling** [dotnet/efcore#18829] opened 2019-11-10 01:04 UTC
Root Container entity can have multiple complex and/or collection Owned properties however, Owned types off the root can only have one Owned complex and/or collection property that can get data from the IQueryable.

If I have a DbContext with one DbSet<container entity>, then configure Owned types on this type that themselves have multiple owned types, only one of those owned types will be "hydrated" with data.

### Steps to reproduce

If I create an object graph that models the below and configure it with the below fluent configuration, when I call .ToListAsync() or .FirstOrDefaultAsync() etc..., I will only get Components and Options **OR** AmountOptions off of Benefit, since Benefit has two Owned types.

If I comment one configuration and it's relating properties, so I don't get a runtime configuration exception... say Components and Options, the other (AmountOptions) will get data.

1. Create object graph structured as below
2. Create DbContext with one root DbSet<Package>
3. Wire up with fluent syntax (or [Owned] attributes) as below
4. Context.Packages.FirstOrDefaultAsync(...);

``` C#
modelBuilder
           .Entity<Package>()
           .OwnsOne(t => t.Snapshot)
           .OwnsMany(t => t.ServicesFlex)
           .OwnsMany(t => t.Benefits)
           .OwnsMany(t => t.Components)
           .OwnsMany(t => t.Options);

modelBuilder
          .Entity<Package>()
          .OwnsOne(t => t.Snapshot)
          .OwnsMany(t => t.ServicesFlex)
          .OwnsMany(t => t.Benefits)
          .OwnsMany(t => t.AmountOptions);
```

Am I configuring this the wrong way?  I also tried the more verbose syntax, with the same results:

``` C#
modelBuilder.Entity<Package>(package =>
{
    // Snapshot
    package.OwnsOne(p => p.Snapshot, snapshot =>
    {
        // ***** Flex Services *****
        snapshot.OwnsMany(s => s.ServicesFlex, servicesFlex =>
        {
            servicesFlex.OwnsMany(sc => sc.Benefits, benefits =>
            {
                benefits.OwnsMany(b => b.Components, components =>
                {
                    components.OwnsMany(c => c.Options);
                });

                benefits.OwnsMany(b => b.AmountOptions);
            });
        });
...
```

The issue means I have to create a separate set of types to hold the second Owned property (AmountOptions).

**No Exceptions.**

Further technical details

- **EF Core Version**: 3 and 3.1.0-preview2.19525.5 and 5.0.0-alpha1.19552.2 (all exhibit the issue)

- **Database Provider**: CosmosDB

- **Target Framework**: .NET Core 3.0/Standard 2.1

- **Operating System**: Windows 10

- **IDE**: Visual Studio 2019 16.7

**Comment by ajcvickers** [comment] 2019-11-11 20:55
@AndriySvyryd Any ideas here?

**Comment by AndriySvyryd** [comment] 2019-11-11 21:37
Looks like a bug

**Comment by bobbydowling** [comment] 2019-11-11 21:38
BTW, it saves fine.

**Comment by mdcleber** [comment] 2020-05-30 19:51
Any news about this bug? I am facing the same problem when I try to something like this:

` modelBuilder.Entity<Root>().OwnsOne(p => p.Attributes, attributes =>
            {
                attributes.OwnsOne(x => x.SubAttributes, subAttributes => subAttributes.OwnsOne(x => x.AnyThing);
            });`

It saves on the database but throws 
 System.InvalidOperationException : Called EntityProjectionExpression.GetNavigation() with incorrect INavigation. EntityType:Root, Navigation:Attributes

**Comment by AndriySvyryd** [comment] 2020-06-02 17:44
@mdcleber Your issue is different, please try the latest version (5.0.0-preview.4.20220.10) and if it is still failing open a new issue with full repro code.

**Comment by AndriySvyryd** [comment] 2020-06-18 23:49
Verified that the issue is fixed in daily builds.

**Closed by AndriySvyryd** 2020-06-18 23:49 UTC
Labels: area-cosmos, customer-reported, type-bug, verify-fixed
