### ISSUE TITLE
Is there any way to run dotnet ef command in Xamarin PLC .netstandard ?

### ISSUE THREAD

**Issue by paradisehuman** [dotnet/efcore#8268] opened 2017-04-24 17:14 UTC
I tried dotnet ef command on Xamarin PLC .netstandard but the cmd shows me does not exist.
This is my project json : 
```
{
  "supports": {},
  "dependencies": {
    "Microsoft.NETCore.Portable.Compatibility": "1.0.2",
    "NETStandard.Library": "1.6.1",
    "Microsoft.EntityFrameworkCore": "1.1.1",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.1",
    "Microsoft.Extensions.Configuration.Abstractions": "1.1.1",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.1",
    "Microsoft.EntityFrameworkCore.Design": "1.1.1",
    "Microsoft.EntityFrameworkCore.InMemory": "1.1.1"
  },
  "frameworks": {
    "netstandard1.4": {}
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": {
      "version": "1.1.0",
      "imports": [
        "portable-net45+win8"
      ]
    }
  }
}
```
When I use a .netstandard class library ( Not PLC ) dotnet ef works but when I tries to migrate the cmd shows me your :

> error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.3\Microsoft\Portable\v5.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> C:\Program Files\dotnet\sdk\1.0.3\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for 'D:\Downloads\Documents\Eella\Eella.Common\Eella.Common.csproj'. This can indicate a missing project reference.

I have All references but the project does not find them.

**Comment by ajcvickers** [comment] 2017-04-24 19:08
@paradisehuman Here is the canned response for anything with project.json: We are not planning to fix this issue because the  [.NET Core SDK 1.0.0](https://www.microsoft.com/net/download/core) no longer supports project.json or Visual Studio 2015. Everyone doing .NET Core development is encouraged to [migrate from project.json to csproj](https://docs.microsoft.com/dotnet/articles/core/migration/) and [Visual Studio 2017](https://www.visualstudio.com/downloads/).

Beyond that we have this work item to track tooling for Xamarin: https://github.com/aspnet/EntityFramework/issues/7152, so I will close this as a dupe of that. When we discussed this briefly in triage we decided that with the transition from project.json to msbuild it may be possible to get this to work with Xamarin. You might want to look at #4269 which is the general issue for tracking Xamarin workarounds, etc.

**Closed** 2022-10-16 11:02 UTC
Labels: closed-duplicate
