### ISSUE TITLE
Does EF Core 5.0 migration and JSON deserialization work with C#9.0 init-only setters?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#23626] opened 2020-12-08 19:16 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Does-EF-Core-50-migration-and-JSON-dese/1264657)._

---
<p>Or do I still need private setters? Thanks.</p>

---
#### Feedback Bot on 11/22/2020, 10:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2020-12-08 19:16
Duplicate of https://github.com/dotnet/docs/issues/21741

**Closed** 2022-10-16 19:14 UTC
Labels: customer-reported
