### ISSUE TITLE
Without any changes on the model, migration is still generating an alter colum on all primary keys

### ISSUE THREAD

**Issue by LucasMilletID3i** [dotnet/efcore#23725] opened 2020-12-18 10:57 UTC
My team and I are using EF core 5.0.1 and discovered a somewhat strange behaviour.
Even if we don't alter the model class any further, if we use the command 
```
PM> dotnet ef migrations
```
The generated migration class is not empty and generates the following code:
```C#
protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "UserClaim",
                type: "int",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int")
                .Annotation("SqlServer:Identity", "1, 1");

            migrationBuilder.AlterColumn<long>(
                name: "Id",
                table: "User",
                type: "bigint",
                nullable: false,
                oldClrType: typeof(long),
                oldType: "bigint")
                .Annotation("SqlServer:Identity", "1, 1");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "UserClaim",
                type: "int",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int")
                .OldAnnotation("SqlServer:Identity", "1, 1");

            migrationBuilder.AlterColumn<long>(
                name: "Id",
                table: "User",
                type: "bigint",
                nullable: false,
                oldClrType: typeof(long),
                oldType: "bigint")
                .OldAnnotation("SqlServer:Identity", "1, 1");
           
        }
```
We don't understand why the migrator is acting like this.

It wouldn't be a problem if when we run the project, the following error message ensued
```
To change the IDENTITY property of a column, the column needs to be dropped and recreated.
```
And the stack trace:
```
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(AlterColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__83_4(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass16_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<MigrateAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at iD3i.Extensions.DependencyInjection.Persistence.DbContextExtensions.<ApplyDbMigrationsWithDataSeedAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Sam.Program.<Main>d__0.MoveNext() in C:\Sam\Program.cs:line 39
```

The real issue is why would the migration command generates this code in the first place ?

## Steps to reproduce

Run the command 
```
dotnet ef migrations add className -p Project-o Folder/Migrations -s Solution-c ApplicationContext
```
Then check the Migrations folder.

## Further technical details

EF Core version: "Microsoft.EntityFrameworkCore" Version="5.0.1"
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 Professional 16.8.2

**Comment by roji** [comment] 2020-12-18 11:53
Do you happen to also reference the PostgreSQL provider? If so, this could be a dup of #23456.

Otherwise, can you submit a minimal project so we can investigate further?

**Comment by LucasMilletID3i** [comment] 2020-12-18 12:34
Indeed, thank you very much roji !

**Comment by roji** [comment] 2020-12-18 13:00
Duplicate of #23456

**Closed** 2022-10-16 19:15 UTC
Labels: closed-duplicate, customer-reported
