### ISSUE TITLE
Conditional operator projecting to type causes invalid SQL.

### ISSUE THREAD

**Issue by 6cUbi57z** [dotnet/efcore#4192] opened 2015-12-29 22:36 UTC
I have a select operation which is combining two values into an object which forms the value on a property as below:

``` C#
.Include(p => p.CameraModel)
.Select(p => new PhotoDetails()
{
    ...
    Camera = p.CameraModel == null ? null : new Camera()
    {
        Make = p.CameraModel.CameraMake,
        Model = p.CameraModel.CameraModel
    },
    ...
});
```

This is generating the invalid SQL below:

``` SQL
SELECT TOP(2)
    ...
    [p].[CameraModelId] IS NULL,
    [p.CameraModel].[CameraMake],
    [p.CameraModel].[CameraModel],
    ...
FROM [Photos] AS [p]
INNER JOIN [Cameras] AS [p.CameraModel]
ON [p].[CameraModelId] = [p.CameraModel].[Id]
...
WHERE
...
```

Which is generating the following exception:

```
SqlException: Incorrect syntax near the keyword 'IS'.
System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__167_0(Task`1 result)
System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
```

I am using dnx451 version 1.0.0-rc1-update1, EF version 7.0.0-rc1-final.

**Comment by smitpatel** [comment] 2016-01-05 22:05
dupe of #3703

**Comment by dale2507** [comment] 2016-01-05 22:09
Ah so it is. I'll close this then.

**Closed** 2022-10-16 09:22 UTC
