### ISSUE TITLE
Key constraint (specifically, max length of a string key) should be mirrored by foreign key.

### ISSUE THREAD

**Issue by danielcweber** [dotnet/efcore#2789] opened 2015-08-07 07:51 UTC
Suppose you have an entity "A" with a string field "Id" as key, which is further configured to be of a maximum length of 32 charachters. When an entity "B" defines a navigation to "A" through a property named "Value", the max length constraint is not copied. At least for SQL-server, this leads to an error:

Column 'A.Id' is not the same length or scale as referencing column 'B.ValueId' in foreign key 'FK_B_Value_ValueId'. Columns participating in a foreign key relationship must be defined with the same length and scale.

Once you take the constraint out (which sets the maximum length to 450), it works. I don't know whether string keys are not supposed to have a maximum length other than default. It is highly desirable though, if you consider Guids as keys.

**Comment by rowanmiller** [comment] 2015-08-07 18:13
@danielcweber is the FK property part of your class, or is it a shadow state property that EF introduced based on the relationship?

**Comment by danielcweber** [comment] 2015-08-10 12:28
It is a shadow state property introduced by EF. I avoid having explicit foreign key properties in my classes if possible.

**Comment by rowanmiller** [comment] 2015-09-17 22:40
Duplicate of https://github.com/aspnet/EntityFramework/issues/2455

**Comment by danielcweber** [comment] 2015-09-25 07:59
Why is this considered a bug with pri0, while #2455 is considered only an enhancement and pri1 ?

**Closed** 2022-10-16 09:04 UTC
Labels: type-bug
