### ISSUE TITLE
Issues using idempotent migration scripts to apply migrations

### ISSUE THREAD

**Issue by AFDevMike** [dotnet/efcore#28780] opened 2022-08-18 21:59 UTC
## Ask a question

RE: Advice to "Consider generating SQL scripts from migrations instead." documented [here](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#idempotent-sql-scripts:~:text=Carefully%20consider%20before%20using%20this%20approach%20in%20production.%20Experience%20has%20shown%20that%20the%20simplicity%20of%20this%20deployment%20strategy%20is%20outweighed%20by%20the%20issues%20it%20creates.%20Consider%20generating%20SQL%20scripts%20from%20migrations%20instead.)
& Idempotent SQL scripts documented [here](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#idempotent-sql-scripts)

The result of running `dotnet ef migrations script --idempotent -o idempotent.sql` produces a sql file that is not idempotent.  

- Its not idempotent in the sense that I can run it multiple times in a row and get the same result.  On second plus run in specific scenario of having previously dropped a column in a prior migration, the SQL fails.  This has repro and is and addressed in this [SO](https://stackoverflow.com/questions/68045105/ef-core-idempotent-migration-script-fails-despite-check-on-applied-migration) by MS Employee "David Browne - Microsoft"

The suggested solution is to "work around this by using dynamic SQL, so that the batch referencing the non-existent column is not parsed and compiled unless the migration is being applied." for statements inside `BEGIN` and `END`.

Tangent that seems awkward - I need to parse this file and split on `GO` (Batches) to send in code.

This seems to be a very brittle way to apply migrations.   Is there better guidance and or something I have missed or perhaps fixed in newer versions of EFCore?

### Include provider and version information

EF Core version: 3.1.14
Database provider: Microsoft.EntityFrameworkCore.SqlServer 3.1.14
Target framework: .Net Core 3.1.14
Operating system: Windows

**Comment by ajcvickers** [comment] 2022-08-22 12:36
@AFDevMike Are you still seeing this issue with the latest EF Core 6.0 or the latest EF Core 7.0 preview? We have made significant improvements to Migrations since the 3.1 release.

**Comment by AFDevMike** [comment] 2022-08-22 12:49
Hi @ajcvickers ,

I have not had the opportunity to to update and try.  I worked past my own issue by generating each "From" SQL script "To" the current migration.  The remaining issue would be reduced down to, ...the result of running `dotnet ef migrations script --idempotent -o idempotent.sql` produces a sql file that is not idempotent. 

In the next few evenings I will see if I can create a minimal duplication on EF Core 6.0 or the latest EF Core 7.0.

**Comment by ajcvickers** [comment] 2022-09-06 17:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-09-06 17:44 UTC
Labels: customer-reported
