### ISSUE TITLE
Issue with EF 6 migration from ef 3.1 instead of delete perform update.

### ISSUE THREAD

**Issue by dmitriy-pisarevskiy** [dotnet/efcore#27805] opened 2022-04-12 09:45 UTC
By some reasons to delete all related VO _languageStrings.Clear() is called update instead of delete on DDD approach, before on ef 3.1 it perform DELETE command. LocalizedResourceKey and LocalizedResourceId can't be null because it used as combined key on Aggregate.  Please help how to work with VO on ef 6.0.3 maybe something is changed.

```sql
exec sp_executesql N'SET NOCOUNT ON;
UPDATE [LocalizedResourceLanguageStrings] SET [LocalizedResourceId] = @p0, [LocalizedResourceKey] = @p1
WHERE [Id] = @p2;
SELECT @@ROWCOUNT;
',N'@p2 int,@p0 int,@p1 nvarchar(128)',@p2=1,@p0=NULL,@p1=NULL
```

```C#
private List<LocalizedResourceLanguageString> _languageStrings;
public IReadOnlyCollection<LocalizedResourceLanguageString> LanguageStrings => _languageStrings;

        public void ClearLanguageStrings()
        {
            var langs = _languageStrings.Select(l => l.LanguageId).Distinct().ToList();

            _languageStrings.Clear();

            foreach (var lang in langs)
            {
                AddDomainEvent(new LocalizedResourceKeyChanged(ResourceId, _key, lang));
            }
        }
```
```C#
            builder.ToTable("LocalizedResourceKeys");

            builder.HasKey(a => new { a.ResourceId, a.Key });


            builder.Property(c => c.Key).IsRequired().HasMaxLength(128);

            builder.HasOne<LocalizedResource>()
                .WithMany()
                .HasForeignKey(c => c.ResourceId)
                .IsRequired()
                .OnDelete(DeleteBehavior.Restrict);

builder.OwnsMany(c => c.LanguageStrings, languageStringsBuilder =>
            {
                languageStringsBuilder.ToTable("LocalizedResourceLanguageStrings");

                languageStringsBuilder.Property(typeof(int), "Id").UseIdentityColumn();
                languageStringsBuilder.HasKey("Id");

                languageStringsBuilder.WithOwner().HasForeignKey("LocalizedResourceId", "LocalizedResourceKey");
                languageStringsBuilder.Property("LocalizedResourceKey").IsRequired();

                languageStringsBuilder.Property(c => c.LanguageId).IsRequired();
                languageStringsBuilder.Property(c => c.Value).IsRequired();

                languageStringsBuilder.HasOne<Language>()
                    .WithMany()
                    .HasForeignKey("LanguageId")
                    .IsRequired()
                    .OnDelete(DeleteBehavior.Cascade);
            });
```

### Include provider and version information

EF Core version: EF 6.0.3
Database provider: . Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system:. Windows 11, Visual Studio 2022 17.1.3

**Comment by ajcvickers** [comment] 2022-04-19 12:41
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-04-28 13:05
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by dmitriy-pisarevskiy** [comment] 2022-04-29 06:45
@ajcvickers thanks, I already solved it related to wrong generated snapshot, I removed shadow keys .HasForeignKey("LocalizedResourceId", "LocalizedResourceKey") and it currently working as expected.

**Closed** 2022-10-16 20:31 UTC
Labels: closed-could-not-reproduce, customer-reported
