### ISSUE TITLE
DataAnnotation issues to Scaffold-Dbcontext

### ISSUE THREAD

**Issue by HelvioBlazor** [dotnet/efcore#16462] opened 2019-07-03 18:28 UTC
I am using data base first, then I run multiple time the Scaffold-DbContext to re-sync the database to EFcore every time I modify the database.

I was using Scaffold-DbContext "Connection String" Microsoft.EntityFrameworkCore.SqlServer -o Model -DataAnnotation -Force, but after update to the preview 6 it cause problem and I had to remove the "-DataAnnotation". When I use DataAnnotation it briging the Table name to the Model declarations what cause problems.

I hope it helps to remove this bug to the language, Thank you.

**Comment by ajcvickers** [comment] 2019-07-05 20:22
@HelvioBlazor Please post a small, runnable project/solution or complete code listing that demonstrates this behavior so that we can fully investigate.

**Comment by ajcvickers** [comment] 2019-07-12 15:47
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:29 UTC
Labels: closed-could-not-reproduce, customer-reported
