### ISSUE TITLE
Defining columns index sort

### ISSUE THREAD

**Issue by alikleitcr7** [dotnet/efcore#24029] opened 2021-01-30 12:16 UTC
We should be able to define the sort type of an index or primary key clustered index which could affect the query's performance.

For example:
```
modelBuilder.Entity<Product>()
    .HasKey(p => p.ID) // This is the PK, should be indexed DESC without having to do it manually since we are using code-first
```

Also, is there a way to do so with `HasIndex`?

**Comment by ajcvickers** [comment] 2021-02-02 20:34
@alikleitcr7 Creating an API for ascending/descending indexes is covered by #4150.

We are curious when it makes sense to make the primary key index descending? Also, what version of EF Core and what database provider are you using?

**Comment by alikleitcr7** [comment] 2021-02-03 08:07
I'm using SQL Server and ef core 5. 

I thought at first it will affect the query's performance if I have a full-text indexed table and I need to order by PK DESC (in case of identity column to get the latest entered first) without having to use `order by ID DESC` .

After doing a little search, I guess there is no downside to order by id desc as SQL will use Backward Scan on the index. In addition, there is the extra fragmentation problem on insert if the index was stored desc.

After all, sorting on a `composite index` can make a difference on either clustered or non-clustered index.

**Comment by roji** [comment] 2021-02-03 11:19
Duplicate of #4150

**Closed** 2022-10-16 19:21 UTC
Labels: closed-duplicate, customer-reported
