### ISSUE TITLE
Migrations: Should scaffold defaultValue: [CLR default] for new non-nullable columns

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#1843] opened 2015-03-17 21:29 UTC
In EF6, if you add a non-nullable column we set the defaultValue to the CLR default for the property type. Otherwise the AddColumn operation will always fail since you'll end up with NULL for existing data.

**Comment by bricelam** [comment] 2015-03-18 21:50
Dupe of #1275?

**Comment by rowanmiller** [comment] 2015-03-19 05:56
Yep, that's the same one

**Closed** 2022-10-16 08:53 UTC
Labels: type-bug
