### ISSUE TITLE
Explicit Loading sometimes not working

### ISSUE THREAD

**Issue by Bo-Yee-Woods** [dotnet/efcore#11736] opened 2018-04-19 08:28 UTC
I have entities like these.

```C#
    public class ZoneGroup
    {
        [StringLength(3)]
        public string DestinationCode { get; set; }

        [ForeignKey("DestinationCode")]
        public virtual Destination Destination { get; set; } 

        [Key]
        [StringLength(50)]
        public string Code { get; set; }
                
        public virtual ICollection<ZoneGroupName> Names { get; set; }

        public virtual ICollection<Zone> Zones { get; set; }
    }

    public class ZoneGroupName : MultiLangEntity
    {
        [ForeignKey("ZoneGroupCode")]
        public virtual ZoneGroup ZoneGroup { get; set; }
        
        [StringLength(50)]
        public string ZoneGroupCode { get; set; }
    }

    public class Zone
    {
        [StringLength(3)]
        public string DestinationCode { get; set; }

        [ForeignKey("DestinationCode")]
        public virtual Destination Destination { get; set; }
        
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Code { get; set; }
     
        public string Name { get; set; }

        [StringLength(50)]
        public string ZoneGroupCode { get; set; }

        [ForeignKey("ZoneGroupCode")]
        public virtual ZoneGroup ZoneGroup { get; set; }
    }
```
When I use explicit loading to load related data

```C#
    _Db.Entry(zoneGroup).Collection(x => x.Names).Load();
    _Db.Entry(zoneGroup).Collection(x => x.Zones).Load();
```
The "Names" is loaded but the "Zones" is empty. But my database do have "zone" of the "zoneGroup".

No Exception.

EF Core version: 2.0
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: vs 2017

**Comment by Bo-Yee-Woods** [comment] 2018-04-20 09:02
The 'Zone' has composite key of 'DestinationCode' and 'Code'. Does it matter?

My project is company's project. I cannot share it with you.

**Comment by ajcvickers** [comment] 2018-04-20 16:01
@Bo-Yee-Woods I understand that you can't share your company code. Instead, can you please create separate code listing (like I posted above) or runnable project/solution that reproduces the behavior you are seeing. Otherwise we're guessing trying to reproduce what you are doing, which makes it very difficult to figure out what bug you are hitting if we cannot reproduce it.

**Comment by Bo-Yee-Woods** [comment] 2018-04-23 03:03
I found that explicit loading work well for me everywhere except in this code block.

        public async Task<(bool, Task<T>)> UpdateDestinationsAsync<T>(int from, int batchSize, Task<T> getResponse = null) where T : DestinationResponse
        {
            var to = from + batchSize - 1;
            var responseGetter = new ContentResponseGetter<T>(_ContentClient, _Db);
            var response = getResponse == null ?
                           await responseGetter.GetNewUpdatesAsync(Resources.Destinations, from, to) :
                           await getResponse;

            var hasMoreResult = response.Total > to;
            var getNextBatch = hasMoreResult ?
                               responseGetter.GetNewUpdatesAsync(Resources.Destinations, from + batchSize, to + batchSize) :
                               null;

            foreach (var destinationModel in response.Destinations)
            {                                
                var destination = _Mapper.Map<DestinationModel, Destination>(destinationModel);
                var country = _Db.Countries.Find(destinationModel.CountryCode);
                destination.Country = country ?? throw new Exception("Country Not Found");

                var exists = _Db.Destinations.Any(x => x.Code == destinationModel.Code);
                _Db.Entry(destination).State = exists ? EntityState.Modified : EntityState.Added;

                if (destinationModel.Name != null)
                {
                    var name = _Mapper.Map<MultiLangContent, DestinationName>(destinationModel.Name);
                    name.DestinationCode = destination.Code;
                    name.LanguageCode = English.Code;
                    _Db.Entry(name).State = exists ? EntityState.Modified : EntityState.Added;
                }

                foreach (var zoneModel in destinationModel.ZoneModels)
                {
                    var zoneExists = _Db.Zones.Any(x => x.Code == zoneModel.Code && x.DestinationCode == destinationModel.Code);

                    var zone = _Mapper.Map<ZoneModel, Zone>(zoneModel);
                    zone.DestinationCode = destination.Code;
                    zone.Destination = destination;
                    _Db.Entry(zone).State = zoneExists ? EntityState.Modified : EntityState.Added;

                    var zoneDescription = _Mapper.Map<MultiLangContent, ZoneDescription>(zoneModel.Description);
                    zoneDescription.DestinationCode = destination.Code;
                    zoneDescription.ZoneCode = zone.Code;                    
                    zoneDescription.LanguageCode = English.Code;
                    _Db.Entry(zoneDescription).State = zoneExists ? EntityState.Modified : EntityState.Added;
                }

                foreach (var zoneGroupModel in destinationModel.GroupZoneModels)
                {                   
                    var zoneGroup = _Db.ZoneGroups.FirstOrDefault(x => x.Code == zoneGroupModel.Code);

                    if (zoneGroup == null)
                    {
                        zoneGroup = _Mapper.Map<GroupZoneModel, ZoneGroup>(zoneGroupModel);
                        zoneGroup.Destination = destination;

                        var zoneGroupName = _Mapper.Map<MultiLangContent, ZoneGroupName>(zoneGroupModel.Name);                        
                        zoneGroupName.ZoneGroup = zoneGroup;
                        zoneGroupName.Language = English;
                        _Db.Add(zoneGroupName);
                    }                    
                    **_Db.Entry(zoneGroup).Collection(x => x.Zones).Load();**
                    foreach (var zoneCode in zoneGroupModel.ZoneCodes)
                    {
                        var zone = _Db.Zones.Find(destination.Code, zoneCode);
                        zone.ZoneGroup = zoneGroup;
                    }
                }
            }
            if(!hasMoreResult) AddUpdateHistory(Resources.Destinations, English);
            await _Db.SaveChangesAsync();
            return (hasMoreResult, getNextBatch);
        }

**Comment by ajcvickers** [comment] 2018-04-24 22:13
@Bo-Yee-Woods I still can't reproduce the issue from the code provided. Can you try to put it into some running application (maybe just a console application) that actually hits the issue such that we can then run it here and reproduce what you are seeing?

**Comment by Bo-Yee-Woods** [comment] 2018-04-26 03:25
I cannot share my current project, but I try to reproduce the behavior in a test project.

**Comment by ajcvickers** [comment] 2018-05-03 21:47
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:19 UTC
Labels: closed-could-not-reproduce
