### ISSUE TITLE
ToListAsync never returns back after query execution

### ISSUE THREAD

**Issue by dixitsuneel** [dotnet/efcore#9293] opened 2017-07-28 22:00 UTC
We just upgraded to EF Core 2.0 Preview 2 and I have seen this issue in EF COre 1.1 

For some of our queries we want to fetch parent records, but then we also find the related child records in one db call. 

so we have our query outlined as this

await query.Select(parent=> new 
{
ParentPropertiesProjections..
ChildCollectionModel = parent.ChildCollection.Select(t=> ....)
}.ToListAsync();

I see in the logs that EF does fire the query to get all the parent tables data, but doesn't produce any more logs after that and then the query never returns back. 

If this scenario is not supported, then the EF core framework should throw an exception for such instead of silently killing the thread. 

I don't see anything in logs at all to provide you details on it. 

Any guidance is greatly appreciated. 

I am running EF Core 2.0 on Windows 10 machine with VS 2017 Enterprise 15.3 Preview 6 against Sql Server

**Comment by BenjiZombie** [comment] 2017-08-02 13:43
See #9128

**Comment by divega** [comment] 2017-08-11 08:24
This seems to be in fact a duplicate of #9363.

**Closed** 2022-10-16 11:13 UTC
Labels: closed-duplicate
