### ISSUE TITLE
Add-Migration generates nullable columns for non-nullable properties inside owned types

### ISSUE THREAD

**Issue by RafaelSalguero** [dotnet/efcore#18785] opened 2019-11-06 21:32 UTC
Migration tool `Add-Migration` generates code for adding a nullable column for non-nullable properties inside owned types

### Steps to reproduce
1.- C# 8 nullable checks are on
2.- Add a non-nullable property to an `Owned` type
3.- Run `Add-Migration`
4.- `nullable: true` code is generated

``` C#
class MyEntity {
  [Key]
  public int Id { get; set; }

  //This property is correctly generated (non nullable)
  public bool MyProp { get; set; }

  public MyOwnedType OwnedType { get; set; } = new MyOwnedType();
}

[Owned]
class MyOwnedType {
  //This property is generated as a nullable column (wrong)
  public bool OwnedProp { get; set; }
}
```

Generated code:
``` C#
 
          migrationBuilder.AddColumn<bool>(
                name: "MyProp",
                table: "MyEntity",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "OwnedType_OwnedProp",
                table: "MyEntity",
                nullable: true);
```

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer 3.0.0
Target framework: netcoreapp3
Operating system: Windows 10
Visual Studio 2019 16.3.7

**Comment by ajcvickers** [comment] 2019-11-06 21:58
Duplicate of #16943

**Closed** 2022-10-16 14:54 UTC
Labels: customer-reported
