### ISSUE TITLE
Preview 6: Multiple .Include() calls cause NotImplementedException

### ISSUE THREAD

**Issue by FeodorFitsner** [dotnet/efcore#16059] opened 2019-06-13 03:55 UTC
Just upgraded to EF Core Preview 6 from Preview 5. SQLite provider.

All LINQ queries with multiple `.Include()` calls started failing with **System.NotImplementedException: 'The method or operation is not implemented.'**

For example, the query like this works:

    dbset.Where(...).Include(e => e.SomeCollection);

However, the query with more than one `.Include()` fails:

    dbset.Where(...).Include(e => e.SomeCollectionA).Include(e => e.SomeCollectionB);

Will try to provide a simple repro project, but smells like a regression.

**Comment by FeodorFitsner** [comment] 2019-06-13 17:06
Here is the simplest repro project for `NotImplementedException`: https://github.com/FeodorFitsner/EFCorePreview6Bugs ([test method](https://github.com/FeodorFitsner/EFCorePreview6Bugs/blob/master/EFCorePreview6Bugs/Program.cs#L45-L55))

The issue is similar to https://github.com/aspnet/EntityFrameworkCore/issues/16061 as it fails on both `.Include()` and following `.FirstOrDefault()`.

It could be "workaround" by `.List().FirstOfDefault()`, but of course it's not a solution for large data sets.

cc @maartenba

**Comment by ajcvickers** [comment] 2019-06-14 19:14
@FeodorFitsner First, many thanks for trying preview 6. If you haven't seen it already, there is some good information in the [preview announcement post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/) about the changes that are happening to LINQ queries for EF Core 3.0. Preview 6 is the first release containing these changes, which means we are both expecting things to be broken, but at the same time very grateful for everyone who tries the release and generated feedback.

I'm going to close this issue as a duplicate of #15611, since this is a known issue with collections.

**Comment by FeodorFitsner** [comment] 2019-06-14 19:24
Yep, read that announcement after trying Preview 6 :) Thanks for looking into the issue anyway!

**Closed** 2022-10-16 14:25 UTC
Labels: customer-reported
