### ISSUE TITLE
Could Find() be more general?

### ISSUE THREAD

**Issue by Neme12** [dotnet/efcore#9554] opened 2017-08-24 19:03 UTC
It's really convenient to use the Find method on a DbSet:
```c#
albums.Find(albumId);
```
but when you need something more complicated, such as calling Include() or AsNoTracking() first, Find() is not available and I have to fall back to doing this:
```c#
albums.Include(album => album.Songs).Single(album => album.Id == albumId);
```
This is not only longer and terribly inconsistent, but from what I understand (forgive me if I'm wrong) it could also avoid an optimization that Find does if it's already tracking the entity to avoid going to the database.

Would it be possible to make Find an extension method on IIncludableQueryable or even IQueryable instead? (or possibly create another interface that has more functionality on top of that)

**Comment by ajcvickers** [comment] 2017-08-25 17:03
@Neme12 This is something that we have discussed at length in the past, but when you dig into the details on Find it ultimately doesn't really work to try to add these semantics, at least without significant changes to other parts of the stack as well. The comments on #6935 provide more details. Closing as a duplicate of #6935.

**Closed** 2022-10-16 11:18 UTC
Labels: closed-duplicate
