### ISSUE TITLE
Complex owned types slow down query by creating unnecessary self joins

### ISSUE THREAD

**Issue by groege** [dotnet/efcore#19073] opened 2019-11-26 09:05 UTC
I have tables with multiple complex owned types but for some reason when i do a simple select it will make a self join for each complex type within the table.
I.e. 
```C#
.Select(x => new OrderView
{
    Guid = x.TransportOrderGuid,
    Timestamp = x.Timestamp,
    TransportOrderNumber = x.TransportOrderSharedData.TransportOrderNumber,
    ExternalTransportOrderNumber = x.TransportOrderData.ExternalTransportOrderNumber,
    DeliveryNoteNumber = x.DeliveryNoteData.DeliveryNoteNumber,
    ExternalDeliveryNoteNumber = x.DeliveryNoteData.ExternalDeliveryNoteNumber,
    //and so on
}
```
Is there a way to force disable self joins for complex types? This is really slowing down the whole thing. The reason why I'm using complex types was because I wanted to reduce joins to improve perfomance.
So instead of having a separate Table with Addresses (containing a address type enum to differentiate the different addresses) I now have a complex Address type:
```C#
public TransportAddress Customer {get;set;}
public TransportAddress Supplier {get;set;}
```
instead of 
```C#
public List<TransportAddress> Addresses {get;set;}
```

But now instead of multiple joins to flatten out different addresses it's not creating unnecessary joins for owned types...

### Further technical details

EF Core version: 3.1 preview 3
Database provider: Npgsql.EntityFrameworkCore.PostgresServer
Target framework: .NET Core 3.1
Operating system: Win 10
IDE: Visual Studio 2019 Preview (latest)

EDIT:
My guess is this is done to see if the complex type is null ==> Is there a way to maybe make a complex type required so this check isn't necessary?
I would prefer to disable the null check for complex types for a query somehow...  => returning the default value for required fields and speeding up the query

**Comment by AndriySvyryd** [comment] 2019-11-27 00:17
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/12100 and https://github.com/aspnet/EntityFrameworkCore/issues/18869

**Closed** 2022-10-16 14:58 UTC
Labels: customer-reported
