### ISSUE TITLE
dotnet ef dbcontext optimize as a PreBuild task

### ISSUE THREAD

**Issue by HSchwichtenberg** [dotnet/efcore#25553] opened 2021-08-17 17:17 UTC
I try to run `dotnet ef dbcontext optimize` as a PreBuild task:

```
 <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
   <Exec Command="dotnet ef dbcontext optimize " />
 </Target>
```

This seems to create an endless compilation loop as `dotnet ef dbcontext optimize` starts a build itself :-(

How can I automate the creation of a compiled model? Starting it manually each time is error-prone as it could be forgotten...

### provider and version information

EF Core version: 6.0.0-preview.7.21378.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
IDE: Visual Studio 2022 Preview 3.0

**Comment by roji** [comment] 2021-08-17 17:32
@HSchwichtenberg building a compiled model via `dotnet ef dbcontext optimize` isn't something that you're meant to do every time you build your project. If you did that, you'd have to wait for `optimize` to complete on every build, and therefore end up exactly where you'd be if you never called `optimize` in the first place: without `optimize`, the model simply gets built as part of your program's startup, which would be essentially the same thing.

`optimize` is typically useful in your CI pipeilne, e.g. when producing a release build; this ensures that the binaries your users receive start up faster. Another usage is if you're working on non-EF areas of your program, and don't want to wait for model building every single time; doing `optimize` would make your startup time faster locally, provided you don't change your model.

**Comment by AndriySvyryd** [comment] 2021-08-18 00:44
Duplicate of https://github.com/dotnet/efcore/issues/24894

**Comment by HSchwichtenberg** [comment] 2021-08-18 14:06
OK... but: If I don't use `optimize` within build, but only in the CI pipeline, that means I have to modify my code in the CI pipeline, right? Because optimize tells me `to use it call 'options.UseModel(ContextModel.Instance)'.` Or is there a way to use the model without calling `UseModel()` (as it was possible with `edmgen.exe /mode:ViewGeneration` in the past.

Modifying in the code in the CI pipeline is possible, not very elegant.

**Closed** 2022-10-16 19:43 UTC
Labels: closed-duplicate, customer-reported
