### ISSUE TITLE
Add list of nested owned types

### ISSUE THREAD

**Issue by goetae** [dotnet/efcore#15757] opened 2019-05-20 13:17 UTC
I cannot add an entity with list of nested owned types. After calling "Add", the inner owned type is set to null, resulting in obvious errors

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The entity of type 'TestMoney' is sharing the table 'TestOrderItems' with entities of type 'TestCurrency', but there is no entity of this type with the same key value that has been marked as 'Added'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values.
```

For testing, I replaced the list with a single item reference and the nested owned type worked perfectly. 

Do I miss some required EF configuration? 

Simplified example project:

```C#
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace EfCore22.NestedOwnedType
{
    class Program
    {
        static void Main(string[] args)
        {
            var opt = new DbContextOptionsBuilder<Context>()
                .UseSqlServer("Data Source=(localdb)\\mssqllocaldb;Initial Catalog=efcore22-02;Integrated Security=true;");

            using (var context = new Context(opt.Options))
            {
                context.Database.EnsureCreated();

                var items = new List<TestOrderItem>();
                items.Add(new TestOrderItem { ProductName = "Test Product 1", Price = new TestMoney { Amount = 99.99, Currency = TestCurrency.EUR } });
                items.Add(new TestOrderItem { ProductName = "Test Product 2", Price = new TestMoney { Amount = 10, Currency = TestCurrency.EUR } });
                items.Add(new TestOrderItem { ProductName = "Test Product 3", Price = new TestMoney { Amount = 8.95, Currency = TestCurrency.USD } });
                items.Add(new TestOrderItem { ProductName = "Test Product 4", Price = new TestMoney { Amount = 2.99, Currency = TestCurrency.USD } });

                var order = new TestOrder
                {
                    CustomerName = "Test Customer",
                    TestOrderItems = items
                };

                Console.WriteLine($"Unit {order.TestOrderItems[0].Price.Currency?.Code}");
                context.TestOrders.Add(order);
// TestCurrency of every TestOrderItem is null
                Console.WriteLine($"Unit {order.TestOrderItems[0].Price.Currency?.Code}");

                context.SaveChanges();
            }
        }
    }

    class TestOrder // AggregateRoot simplified
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }

        public IList<TestOrderItem> TestOrderItems { get; set; }
        //public TestOrderItem TestOrderItem { get; set; }
    }

    class TestOrderItem // Entity simplified
    {
        public int Id { get; set; }
        public int TestOrderId { get; set; }
        public string ProductName { get; set; }
        public TestMoney Price { get; set; }
    }

    class TestMoney // ValueObject simpliefied
    {
        public double Amount { get; set; }
        public TestCurrency Currency { get; set; }
    }

    class TestCurrency // Enum class simplified
    {
        public static readonly TestCurrency EUR = new TestCurrency(49, "EUR", 978, "Euro");
        public static readonly TestCurrency USD = new TestCurrency(148, "USD", 840, "United States dollar");

        private TestCurrency() { } // EF

        public TestCurrency(int id, string code, int numericCode, string name)
        {
            Id = id;
            Name = name;
            Code = code;
            NumericCode = numericCode;
        }

        public int Id { get; private set; }
        public string Name { get; private set; }
        public string Code { get; private set; }
        public int NumericCode { get; private set; }
    }


    class Context : DbContext
    {
        public Context(DbContextOptions options) : base(options) { }

        public DbSet<TestOrder> TestOrders { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TestOrder>()
                .ToTable("TestOrders")
                .HasKey(o => o.Id);

            modelBuilder.Entity<TestOrderItem>()
                .OwnsOne(oi => oi.Price, ip =>
                {
                    ip.Property(p => p.Amount).IsRequired();
                    ip.OwnsOne(p => p.Currency, pc =>
                    {
                        pc.Property(c => c.Code).IsRequired();
                        pc.Ignore(c => c.Id);
                        pc.Ignore(c => c.Name);
                        pc.Ignore(c => c.NumericCode);
                    });
                })
                .ToTable("TestOrderItems")
                .HasKey(oi => oi.Id);
        }
    }
}

```

**Comment by MikaelEliasson** [comment] 2019-05-31 05:02
@goetae What you have to do is copy the Currency each time you use it. EF Core tracks owned entities with a hidden Id, So when you reuse the same object it get confused. 

This is in many cases a good thing as it can prevent some nasty bugs but can also be a bit annoying. But just add a copy method that you call and you should be fine.

**Comment by ajcvickers** [comment] 2019-07-07 22:10
Poaching...

Note: this is failing because the same instance of `TestCurrency` is being shared by multiple owners--this is tracked by #12345, so this is really a duplicate of that issue.

This can be made to work by changing the mapping to use a `ValueConverter` for the enum pattern type. Using a `ValueConverter` is often a better way to get the semantics of a value object. For example:

```C#
modelBuilder.Entity<TestOrderItem>()
    .OwnsOne(
        oi => oi.Price, ip =>
        {
            ip.Property(p => p.Amount).IsRequired();
            ip.Property(p => p.Currency).HasConversion<string>(
                v => v.Code,
                v => v == "EUR" ? TestCurrency.EUR : v == "USD" ? TestCurrency.USD : null);
        }).HasKey(oi => oi.Id);
```

**Closed** 2022-10-16 14:21 UTC
Labels: closed-duplicate, customer-reported
