### ISSUE TITLE
EF Core using Repository Pattern - "Specified cast is Invalid"  error

### ISSUE THREAD

**Issue by manishkrai** [dotnet/efcore#6820] opened 2016-10-19 17:55 UTC
While implementing Repository pattern with EF Core getting below error  @rowanmiller 

``` C#
namespace SMS.DataModel
{
    public abstract class EntityBase
    {
        public long Key { get; set; }
    }
}

using System;

namespace SMS.DataModel.Student
{
    public class Enquiry : EntityBase
    {
        public string ApplicationNumber { get; set; }
        public string Name { get; set; }        
    }
}

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SMS.DataModel.Student;

namespace SMS.DataAccess.Mappings
{
    public class EnquiryMap : EntityTypeConfiguration<Enquiry>
    {
        public const string TableName = "Enquiries";

        public override void Map(EntityTypeBuilder<Enquiry> builder)
        {
            builder.ToTable(TableName);

            builder.HasKey(b => b.Key);
            builder.Property(b => b.Key).UseSqlServerIdentityColumn();
            builder.Property(b => b.ApplicationNumber);
            builder.Property(b => b.Name);                        
        }
    }
}

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SMS.DataAccess.Mappings;
using SMS.DataModel;
using SMS.DataModel.Student;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.DataAccess
{
    public class DbAccessContext :DbContext
    {      

        protected new DbSet<TEntity> Set<TEntity>() where TEntity : EntityBase
        {
            return base.Set<TEntity>();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);            
            modelBuilder.AddConfiguration(new EnquiryMap());
        }
    }
}

using System;
using System.Collections.Generic;
using SMS.DataModel;
using System.Linq.Expressions;

namespace SMS.DataAccess.Repository
{
    public interface IRepository<T> where T : EntityBase
    {
        T GetByKey(long key);
        IEnumerable<T> List();
        IEnumerable<T> List(Expression<Func<T, bool>> predicate);
        void Add(T entity);
        void Update(T entity);
        void Delete(T entity);        
    }
}

using SMS.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SMS.DataAccess.Repository
{
    public class Repository<T> : IRepository<T> where T :EntityBase
    {
        private readonly DbAccessContext _dbContext;

        public Repository(DbAccessContext dbContext)
        {
            _dbContext = dbContext;
        }

        public T GetByKey(long key)
        {
            return _dbContext.Set<T>().FirstOrDefault(x => x.Key == key);
        }

        public IEnumerable<T> List()
        {
            return _dbContext.Set<T>().AsEnumerable();
        }

        public IEnumerable<T> List(System.Linq.Expressions.Expression<Func<T, bool>> predicate)
        {
            return _dbContext.Set<T>().Where(predicate).AsEnumerable();
        }

        public void Add(T entity)
        {
            _dbContext.Set<T>().Add(entity);
            _dbContext.SaveChanges();
        }

        public void Update(T entity)
        {
            _dbContext.Entry(entity).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            _dbContext.SaveChanges();
        }

        public void Delete(T entity)
        {
            _dbContext.Set<T>().Remove(entity);
            _dbContext.SaveChanges();
        }        
    }
}

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMS.ViewModels.Student;
using SMS.DataModel.Student;
using AutoMapper;
using SMS.ViewModels.Configuration;
using SMS.DataAccess.Repository;
using SMS.DataModel;

namespace SMS.Web.Areas.Student.Controllers
{
    public class EnquiryListController : Controller
    {
        Repository<Enquiry> _enquiryRepository;
        Repository<SMSType> _smsTypeRepository;

        public EnquiryListController(Repository<Enquiry> enquiryRepository, Repository<SMSType> smsTypeRepository)
        {
            _enquiryRepository = enquiryRepository;
            _smsTypeRepository = smsTypeRepository;
        }
        //
        // GET: /Student/EnquiryList/
        public ActionResult Index()
        {
            EnquiryRecSelectContextViewModel contextModel = new EnquiryRecSelectContextViewModel();
            var a = _enquiryRepository.List().ToList().Count();
            contextModel.Enquiries = Mapper.Map<IEnumerable<Enquiry>, IEnumerable<EnquiryViewModel>>(_enquiryRepository.List());            

            return View("EnquiryList", contextModel);
        }
    }
}

[InvalidCastException: Specified cast is not valid.]
   lambda_method(Closure , ValueBuffer ) +195
   Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalMixedEntityEntry..ctor(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer valueBuffer) +55
   Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.NewInternalEntityEntry(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer valueBuffer) +168
   Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.Create(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer valueBuffer) +24
   Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer valueBuffer) +137
   Microsoft.EntityFrameworkCore.Query.Internal.EntityTrackingInfo.StartTracking(IStateManager stateManager, Object entity, ValueBuffer valueBuffer) +68
   Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.StartTracking(Object entity, EntityTrackingInfo entityTrackingInfo) +166
   Microsoft.EntityFrameworkCore.Query.QueryContext.StartTracking(Object entity, EntityTrackingInfo entityTrackingInfo) +25
   Microsoft.EntityFrameworkCore.Query.Internal.<_TrackEntities>d__15`2.MoveNext() +547
   Microsoft.EntityFrameworkCore.Query.Internal.EnumeratorExceptionInterceptor.MoveNext() +396
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +381
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +58
   SMS.Web.Areas.Student.Controllers.EnquiryListController.Index() in e:\Projects\SMS\SMS.Web\Areas\Student\Controllers\EnquiryListController.cs:30
   lambda_method(Closure , ControllerBase , Object[] ) +62
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +157
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +22
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +39
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +28
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +31
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9658396
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

A first chance exception of type 'System.InvalidCastException' occurred in Microsoft.EntityFrameworkCore.dll
```

**Comment by manishkrai** [comment] 2016-10-19 18:02
[Stacktrace.txt](https://github.com/aspnet/EntityFramework/files/539810/Stacktrace.txt)
![error](https://cloud.githubusercontent.com/assets/8535126/19531173/55c0f9fe-9654-11e6-8f10-096da850d399.png)

**Comment by manishkrai** [comment] 2016-10-22 18:50
# @rowanmiller Any update on this issue ?

**Comment by rowanmiller** [comment] 2016-10-24 17:41
In 1.1 we've made some changes so that you'll get some more info about what went wrong (other than a generic invalid cast exception). Can you retry on 1.1.

**Comment by rowanmiller** [comment] 2016-10-25 17:59
BTW here info on trying out 1.1 Preview 1 https://blogs.msdn.microsoft.com/dotnet/2016/10/25/announcing-entity-framework-core-1-1-preview-1/

**Comment by rowanmiller** [comment] 2016-10-31 18:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 10:39 UTC
