### ISSUE TITLE
Hate the new HandleBar scaffolder

### ISSUE THREAD

**Issue by devoneonline** [dotnet/efcore#21009] opened 2020-05-21 18:18 UTC
Just wondering why a simple & robust TextTransform template for custom scaffolding & data generation Microsoft EF Core team gave up & use this stupid HandleBar templates, which neither offer any customization, nor control and most of all, filled with bugs, I mean, just because the new other platform based engineer who joins the Microsoft Team, is not aware of an awesome tool, he goes out to reinvent the wheel, why does his manager approves this kind of stupidity, just because both of them trying to prove they can code better than other programmers? 

I think, Microsoft Team & its new set of developers & probably Managers forgot the basic idea behind rapid application development, which thrieved the Growth of Microsoft Programming languages. 

In the name of so called new work, previous robust tools are getting discarded & new & untested, undercooked, code & tools are thrown at users & told to deal with them.

This is causing lot of trouble to the hard-core Microsoft Development Platform fan, and in the end, who will move away to other simpler tools, eventually making Microsoft Development languages Dead..

Think about it....anyone who wants to make a career as a Software Developer using Microsoft Tools & Technologies

**Comment by roji** [comment] 2020-05-21 19:20
@devoneonline are you referring to the [EntityFrameworkCore.Scaffolding.Handlebars package](https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/)? If so, that package isn't maintained by Microsoft - you should probably file an issue [on their repo](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars).

**Comment by smitpatel** [comment] 2020-05-21 21:27
Possible duplicate of #4038

**Comment by ajcvickers** [comment] 2020-05-22 20:19
Closing as duplicate of #4038 since that issue covers the functionality being requested.

**Closed** 2022-10-16 18:26 UTC
Labels: customer-reported
