### ISSUE TITLE
Bug in query generation involving a Math.Round?

### ISSUE THREAD

**Issue by JeanCollas** [dotnet/efcore#8162] opened 2017-04-13 21:37 UTC
I use EFCore 1.0.1.

Here is my request:

    var reqs1 = await (from r in DbContext.EventSearchs
                       where r.CreationDate > DateTime.Today.AddDays(-22)
                       group r by new { Date=r.CreationDate.Date, User= r.User, Latitude=Math.Round(r.Latitude,4), Longitude=Math.Round(r.Longitude,4) } into r2
                       select new { Date = r2.Key.Date, User=r2.Key.User, Lat=r2.Key.Latitude, Lng=r2.Key.Longitude }).ToListAsync();

Here is the request sent to SQL server:

    SELECT [r].[Id], [r].[AlreadyExists], [r].[Country], [r].[CreationDate], [r].[Latitude], [r].[Longitude], [r].[Type], [r].[User], [r].[What]
    FROM [Searchs] AS [r]
    WHERE ([r].[CreationDate] > @__AddDays_0)
    ORDER BY CONVERT(date, [r].[CreationDate]), [r].[User], ROUND(4, 4), ROUND(4, 4)

It generates a SQL error, as you can see the Math.Round is not well converted.

**Comment by maumar** [comment] 2017-04-13 21:50
dupe of https://github.com/aspnet/EntityFramework/issues/7600
Please upgrade EF to 1.1.1 and this issue should get resolved.

**Closed** 2022-10-16 11:01 UTC
Labels: closed-duplicate
