### ISSUE TITLE
MsSql = "Could not be translated", utests with InMemoryDatabase pass

### ISSUE THREAD

**Issue by generik0** [dotnet/efcore#18695] opened 2019-11-01 11:10 UTC
Hi

I am a little worried about some matters in EF Core 3.0

I have a pile of repository pattern tests. All using the InMemoryDatabase. They are passing.
However the "real code" using a MsSql connections throw exceptions.
I.e. Issue with linq:

- Contains
- CompareTo
- Any

Housten (or should I write Redmond), do we have a problem?

![image](https://user-images.githubusercontent.com/2411563/68020880-25c2c880-fca0-11e9-9b09-8a1ccfdc2042.png)

**Comment by generik0** [comment] 2019-11-01 11:20
Is there maybe i ayay i can add an event to my uTests, that all queries  trigger a ToSql check?

**Comment by generik0** [comment] 2019-11-01 11:41
The ".Equals(s, StringComparison.OrdinalIgnoreCase)" alos passes with in mem, but not for mssql

![image](https://user-images.githubusercontent.com/2411563/68022542-ee0a4f80-fca4-11e9-88ad-d9d44e4dcc37.png)

**Comment by generik0** [comment] 2019-11-01 12:35
Hmm. I tried adding the DbCommandInterceptor, did not breakpoint on any of the overrides...

**Comment by smitpatel** [comment] 2019-11-01 15:12
@generik0 - The first query seems like duplicate of #17342, we have fixed that for 3.1 release.
The second query - string equals method with StringComparison argument was never translated in EF Core. See #1222 which is tracking it and discussion why it is not easy to do. It was being evaluated in previous versions of EF, now it is throwing exception as EF Core 3.0 does not allow client evaluation.

**Comment by generik0** [comment] 2019-11-01 15:25
HI @smitpatel . Thanks for answering! :-)

My point is **not** that EF Core 3.0 is failing for MS. That is what it is.

My point is that the Memory Db, is not falling for the queries that the real db is failing for.....

How can I use the Memory Db for testing, if we can not trust it behaves the same way when we query? 😨 

In other words. if the memory db is to be used for testing, e.g. repos (which it was previously perfect for), then it should really fail here also...

Hence I have tried to add a question/be proactive:  Van one add an interrupt (or something), that tests converting the memory db queries into a generic sql or something, so we can catch exceptions for the translations?

**Comment by generik0** [comment] 2019-11-01 15:27
Again, if the mssql ef core LINQ fails for translations, the memory really also should too.. Otherwise, test with the memory db has no value at all... :-/
Does it make sense what I am trying to convey here?

**Comment by ajcvickers** [comment] 2019-11-01 15:33
> How can I use the Memory Db for testing, if we can not trust it behaves the same way when we query?

You can't. See the discussion here: #18457

**Comment by generik0** [comment] 2019-11-01 15:38
@ajcvickers, oh, that is bad new. The InMemeroy Db rocked.. And a clear advantage when using the repo pattern and TDDing / integration tests...

**Closed** 2022-10-16 14:53 UTC
Labels: closed-no-further-action, customer-reported
