### ISSUE TITLE
Entity Framework Core 2 Owned Entity on Multiple Entities

### ISSUE THREAD

**Issue by footedr** [dotnet/efcore#10145] opened 2017-10-23 21:00 UTC
I have the following domain class that I'm using as an owned entity on multiple entities.

```
public class DateTimeSpan
{
    private DateTimeSpan()
    {
    }

    private DateTimeSpan(DateTime start, DateTime end)
    {
        Start = start;
        End = end;
    }

    public DateTime? Start { get; private set; }
    public DateTime? End { get; private set; }

    public TimeSpan? TimeSpan
    {
        get
        {
            if (End.HasValue && Start.HasValue)
                return End.Value - Start.Value;
            return null;
        }   
    }

    public static DateTimeSpan Create(DateTime start, DateTime end)
    {
        return new DateTimeSpan(start, end);
    }
}
```
Worked great on the first entity. Both properties showed up in it w/ the correct names. When I go to add it to the second entity, EF tries to rename the first entity to the second entity (the one I am adding in the migration), and THEN add the two columns.

So this is basically what I have going...
```
public class Entity1
{
    public DateTimeSpan MyDateRange1 { get; set; }

    public DateTimeSpan MyDateRange2 { get; set; }
}

public class Entity2
{
    public DateTimeSpan AnotherDateRange { get; set; }
}
```
Entity1 is cool. EF tries to rename Entity1 to Entity2 and add the new fields in the migration.

**Comment by smitpatel** [comment] 2017-10-23 21:04
Duplicate of #9873

**Closed** 2022-10-16 11:55 UTC
Labels: closed-duplicate
