### ISSUE TITLE
ObservableHashSet: binding to WPF and removing items leads to InvalidOperationException

### ISSUE THREAD

**Issue by michaelmairegger** [dotnet/efcore#12529] opened 2018-07-03 06:22 UTC
When I bind to an ObservableHashSet<T> from WPF and remove an item then an InvalidOperationException is thrown

```
Exception message:
Vom "Remove"-Ereignis für eine Sammlung muss eine Elementposition angegeben werden.
Stack trace:

   bei MS.Internal.Data.EnumerableCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   bei System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   bei Microsoft.EntityFrameworkCore.ChangeTracking.ObservableHashSet`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   bei Microsoft.EntityFrameworkCore.ChangeTracking.ObservableHashSet`1.Remove(T item)
   bei Mairegger.SchwerVerwaltung.ViewModels.ViewModels.Creator.ArticleCreatorViewModel.ExecuteDeleteMeasurementTemplate(MeasurementTemplateItem arg)
   bei Prism.Commands.DelegateCommand`1.Execute(T parameter)
   bei Prism.Commands.DelegateCommand`1.Execute(Object parameter)
   bei Prism.Commands.DelegateCommandBase.System.Windows.Input.ICommand.Execute(Object parameter)
   bei MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   bei System.Windows.Controls.Primitives.ButtonBase.OnClick()
   bei System.Windows.Controls.Button.OnClick()
   bei System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   bei System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   bei System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   bei System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   bei System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

### Steps to reproduce

```c#
public class C1 : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;
    public virtual ICollection<C2> C2s { get; set; }
}

public class C2 : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;
    public string SomeString {get;set;}
}
```

```xaml
<ItemsControl ItemsSource="{Binding Path=ObjOfC1.CSs}" />
```

If I bind to ` <ItemsControl ItemsSource="{Binding Path=ObjOfC1.CSs}" />` and remove an item from ObjOcC1.CSs then the exception shown above is thrown.

There is no issue if I define ObservableCollection instead of ICollection on `C2s`.

### Further technical details
EF Core version: 2.1.0-rtm-30799
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 2.1.0-rtm-30799
Operating system: 1803 Build 17134.112
IDE: Visual Studio 2017 15.7.4

**Comment by ajcvickers** [comment] 2018-07-03 17:10
Duplicate of #7397. Short answer is that WPF requires the use of ObservableCollection, or some other type that that preserves order.

**Closed** 2022-10-16 13:17 UTC
Labels: closed-duplicate, customer-reported
