### ISSUE TITLE
Invalid Column in Linq query after migration to 2.0

### ISSUE THREAD

**Issue by sylvaincaillot** [dotnet/efcore#10570] opened 2017-12-15 04:48 UTC
I just updated my API application to ASP.Net Core 2.0 as well as EF Core accordingly.

The following query used to work fine before:

```
IList<myDTO> allRecords = _context.myModel                               
                                .Select(item => new myDTO()
                                {
                                   recordId = item.myId,                                   
                                    recordName = item.myName                                  
                                })
                                .OrderBy(o=>o.recordName)                                
                                .Skip(limit * (page - 1))
                                .Take(limit)
                                .ToList();

public class myModel
    {       
        [Key]       
        public int myId { get; set; }       
        public string myName { get; set; }       
    }

public class myDTO
    {      
        public int recordId { get; set; }      
        public string recordName { get; set; }      
    }
```
After the update I always get a

`System.Data.SqlClient.SqlException: 'Invalid column name 'recordName '.'`

### Additional info
If i remove the OrderBy statement as:

```
IList<myDTO> allRecords = _context.myModel                               
                                .Select(item => new myDTO()
                                {
                                   recordId = item.myId,                                   
                                    recordName = item.myName                                  
                                })                                                             
                                .Skip(limit * (page - 1))
                                .Take(limit)
                                .ToList();
```
or the recordName field as :

```
 IList<myDTO> allRecords = _context.myModel                               
                                .Select(item => new myDTO()
                                {
                                   recordId = item.myId            
                                })
                                .OrderBy(o=>o.recordName)                                
                                .Skip(limit * (page - 1))
                                .Take(limit)
                                .ToList();
```
or the Skip statement as:

```
IList<myDTO> allRecords = _context.myModel                               
                                    .Select(item => new myDTO()
                                    {
                                       recordId = item.myId,                                   
                                        recordName = item.myName                                  
                                    })
                                    .OrderBy(o=>o.recordName)
                                    .Take(limit)
                                    .ToList();
```
The Linq query works.

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.5.2)

**Comment by smitpatel** [comment] 2017-12-15 05:24
possible duplicate of #9535
are you using `RowNumberPaging`?

**Comment by sylvaincaillot** [comment] 2017-12-15 07:19
Thank you
Yes i am effectivelly using `RowNumberPaging `as I am using SQL Server 2008 R2:
`optionsBuilder.UseSqlServer(_config["ConnectionStrings:XXX"], b => b.UseRowNumberForPaging());`

It is really a blocking issue for me.

**Comment by ajcvickers** [comment] 2018-11-14 23:02
@sylvaincaillot If you are still using RowNumberForPaging, could you please comment on issue #13959 and let us know why?

**Closed** 2022-10-16 12:03 UTC
