### ISSUE TITLE
ForeignKeyAttribute add cascadeDelete cascadeUpdate param

### ISSUE THREAD

**Issue by Varorbc** [dotnet/efcore#13627] opened 2018-10-15 07:03 UTC
ForeignKeyAttribute add cascadeDelete cascadeUpdate param

**Comment by ajcvickers** [comment] 2018-10-15 19:34
This is unlikely to go on `ForeignKeyAttribute`, since those types are pretty locked down, but this is a reasonable suggestion for #10864

**Comment by Varorbc** [comment] 2018-10-16 02:31
[#9750](https://github.com/dotnet/corefx/issues/9750)

**Comment by ajcvickers** [comment] 2018-10-16 17:31
Duplicate of #9621

**Closed** 2022-10-16 13:35 UTC
Labels: closed-duplicate, customer-reported
