### ISSUE TITLE
Multilevel inheritance throws on adding the second discriminator

### ISSUE THREAD

**Issue by bessgeor** [dotnet/efcore#16377] opened 2019-07-01 16:27 UTC
I'm writing tests for entity graph provider over EFCore.
One of the cases is multilevel inheritance (full mapping below).
I've got the following exception:
```
Exception message: CLR property 'ChildDiscriminatorInt' cannot be added to entity type 'NonAbstractBase' because it is declared on the CLR type 'Mid_NonAbstract_NonAbstract'.
Stack trace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddProperty(MemberInfo memberInfo, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Property existingProperty, String propertyName, Type propertyType, MemberInfo clrProperty, Nullable`1 configurationSource, Nullable`1 typeConfigurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(String propertyName, Type propertyType, MemberInfo memberInfo, Nullable`1 configurationSource, Nullable`1 typeConfigurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(MemberInfo clrProperty, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalEntityTypeBuilderAnnotations.DiscriminatorBuilder(Func`2 createProperty, Type propertyType)
   at Microsoft.EntityFrameworkCore.RelationalEntityTypeBuilderExtensions.HasDiscriminator[TEntity,TDiscriminator](EntityTypeBuilder`1 entityTypeBuilder, Expression`1 propertyExpression)
   at Sirena.Transhost.Core.EntityHierarchy.Test.Tests.Inheritance.Complex.NonAbstract_NonAbstract_DbTest.Db.MapMid(ModelBuilder modelBuilder, EntityTypeBuilder`1 mid) in C:\Users\bessOnovgb\source\repos\Transhost\PSS_AUT\Sirena.Transhost.Core\Sirena.Transhost.Core.EntityHierarchy.Test\Tests\Inheritance\Complex\NonAbstract_NonAbstract_DbTest.cs:line 26
   at Sirena.Transhost.Core.EntityHierarchy.Test.Tests.Inheritance.Complex.Helpers.NonAbstractTPHBaseContext`1.OnModelCreating(ModelBuilder modelBuilder) in C:\Users\bessOnovgb\source\repos\Transhost\PSS_AUT\Sirena.Transhost.Core\Sirena.Transhost.Core.EntityHierarchy.Test\Tests\Inheritance\Complex\Helpers\NonAbstractTPHBaseContext.cs:line 63
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Sirena.Transhost.Core.OfflineMode.Helpers.GrafEntity..ctor(DbContext dbContext, List`1 considerationType, Type[] exeptType) in C:\Users\bessOnovgb\source\repos\Transhost\PSS_AUT\Sirena.Transhost.Core\Sirena.Transhost.Core.OfflineMode\Helpers\GrafEntity.cs:line 26
   at Sirena.Transhost.Core.OfflineMode.Helpers.EntityHierarchyBuilder.GetEntityHierarchy[TData](TData data, DbContext dbContext, Type[] exeptType) in C:\Users\bessOnovgb\source\repos\Transhost\PSS_AUT\Sirena.Transhost.Core\Sirena.Transhost.Core.OfflineMode\Helpers\EntityHierarchyBuilder.cs:line 18
   at Sirena.Transhost.Core.EntityHierarchy.Tests.Infrastructure.EntityHierarchyFactories.<>c.<EnumerateFactories>b__0_0(DbContext ctx) in C:\Users\bessOnovgb\source\repos\Transhost\PSS_AUT\Sirena.Transhost.Core\Sirena.Transhost.Core.EntityHierarchy.Test\Infrastructure\EntityHierarchyFactories.cs:line 15
   at Sirena.Transhost.Core.EntityHierarchy.Test.Tests.Inheritance.Complex.NonAbstract_NonAbstract_DbTest.GraphIsBuiltCorrectly(Func`2 hierarchyFactory) in C:\Users\bessOnovgb\source\repos\Transhost\PSS_AUT\Sirena.Transhost.Core\Sirena.Transhost.Core.EntityHierarchy.Test\Tests\Inheritance\Complex\NonAbstract_NonAbstract_DbTest.cs:line 52
```

### Steps to reproduce
try to create `Db` instance:
```c#
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace whatever
{

	internal class TestDbContext : DbContext
	{
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseInMemoryDatabase("graph_test");
	}

	internal abstract class NonAbstractTPHBaseContext<T> : TestDbContext
		where T : NonAbstractBase
	{
		public DbSet<NonAbstractBase> Base { get; set; }
		public DbSet<NonAbstractChildA> A { get; set; }
		public DbSet<NonAbstractChildB> B { get; set; }
		public DbSet<NonAbstractChildC> C { get; set; }
		public DbSet<T> D { get; set; }
		public DbSet<Order> Orders { get; set; }
		public DbSet<Trip> Trips { get; set; }

		protected abstract void MapMid(ModelBuilder modelBuilder, EntityTypeBuilder<T> builder);

		protected sealed override void OnModelCreating(ModelBuilder modelBuilder)
		{
			var eb = modelBuilder.Entity<NonAbstractBase>();

			eb
				.HasKey(e => e.Id)
			;

			eb
				.HasOne(typeof(Order))
				.WithMany()
				.HasForeignKey(nameof(NonAbstractBase.OrderId))
			;

			eb
				.HasDiscriminator(e => e.DiscriminatorInt)
				.HasValue<NonAbstractChildA>((int) Discriminator.A)
				.HasValue<NonAbstractChildB>((int) Discriminator.B)
				.HasValue<NonAbstractChildC>((int) Discriminator.C)
				.HasValue<T>((int) Discriminator.D)
			;

			modelBuilder
				.Entity<NonAbstractChildC>()
				.HasOne(typeof(Trip))
				.WithMany()
				.HasForeignKey(nameof(NonAbstractChildC.TripId))
			;

			modelBuilder
				.Entity<Order>()
				.HasOne(typeof(Trip))
				.WithMany()
				.HasForeignKey("trip_id")
			;

			MapMid(modelBuilder, modelBuilder.Entity<T>());
		}
	}
	internal class Db : NonAbstractTPHBaseContext<Mid_NonAbstract_NonAbstract>
	{
		public DbSet<NonAbstract_NonAbstract_A> MidA { get; set; }
		public DbSet<NonAbstract_NonAbstract_B> MidB { get; set; }

		protected override void MapMid(ModelBuilder modelBuilder, EntityTypeBuilder<Mid_NonAbstract_NonAbstract> mid)
		{
			modelBuilder
				.Entity<Mid_NonAbstract_NonAbstract>()
				.HasDiscriminator(e => e.ChildDiscriminatorInt) // throws here
				.HasValue<NonAbstract_NonAbstract_A>((int) AnotherDiscriminator.A)
				.HasValue<NonAbstract_NonAbstract_B>((int) AnotherDiscriminator.B)
			;

			modelBuilder
				.Entity<NonAbstract_NonAbstract_A>()
				.HasOne(typeof(NonAbstractChildC))
				.WithOne()
				.HasForeignKey(typeof(NonAbstract_NonAbstract_A), nameof(NonAbstract_NonAbstract_A.AuntieC))
				.HasPrincipalKey(typeof(NonAbstractChildC), nameof(NonAbstractChildC.Id))
			;

			modelBuilder
				.Entity<NonAbstract_NonAbstract_B>()
				.HasOne(typeof(Trip))
				.WithMany()
			;
		}
	}

	// models
	public class NonAbstract_NonAbstract_A : Mid_NonAbstract_NonAbstract
	{
		public int? AuntieC { get; internal set; }
	}
	public class NonAbstract_NonAbstract_B : Mid_NonAbstract_NonAbstract
	{
	}
	public enum Discriminator
	{
		A = 1,
		B = 2,
		C = 3,
		D = 4
	}
	public enum AnotherDiscriminator
	{
		A = 1,
		B = 2,
	}
	public class Mid_NonAbstract_NonAbstract : NonAbstractBase
	{
		public AnotherDiscriminator? ChildDiscriminator { get; set; }
		internal int ChildDiscriminatorInt { get => (int) ChildDiscriminator; set => ChildDiscriminator = (AnotherDiscriminator) value; }
	}
	public static class Pipe
	{
		public static TOut Then<TIn, TOut>(this TIn @in, Func<TIn, TOut> pipe)
			=> pipe(@in);
	}
	public class NonAbstractBase
	{
		public int Id { get; set; }
		public int OrderId { get; set; }
		public int? DiscriminatorInt { get; set; }
		public Discriminator? Disc { get => DiscriminatorInt?.Then(d => (Discriminator) d); set => DiscriminatorInt = value?.Then(v => (int) v); }
	}
	public class NonAbstractChildA : NonAbstractBase
	{
		public NonAbstractChildA() => Disc = Discriminator.A;

		public int AField { get; set; }
	}
	public class NonAbstractChildB : NonAbstractBase
	{
		public NonAbstractChildB() => Disc = Discriminator.B;

		public Guid BField { get; set; }
	}
	public class NonAbstractChildC : NonAbstractBase
	{
		public NonAbstractChildC() => Disc = Discriminator.C;

		public int TripId { get; set; }
		public string CField1 { get; set; }
		public decimal CField2 { get; set; }
	}
	internal class Trip
	{
		public int Id { get; set; }
	}
	internal class Order
	{
		public int Id { get; set; }
		public int OtherPrincipal { get; set; }
	}
}
```

### Further technical details
EF Core version: 2.0.3
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10 Pro 1803 build 17134.81
IDE: Visual Studio 2017 Professional 15.9.3

I can't update EF because can't update because https://github.com/aspnet/EntityFrameworkCore/issues/12239

**Comment by ajcvickers** [comment] 2019-07-01 16:52
@bessgeor EF Core 2.0 is no longer supported. You will need to update to either 2.1, 2.2, or the 3.0 previews. You'll need to workaround #12239, if that is what is preventing this. If you provide some more details on your exact scenario for #12239, then we can help look for workarounds.

**Comment by bessgeor** [comment] 2019-07-01 17:31
@ajcvickers the problem that there are about one hundred use places of #12239 in solution so I'll wait for fix.
But the mapping itself is isolated enough to try another version. I'll try it tomorrow.

**Comment by bessgeor** [comment] 2019-07-02 09:27
@ajcvickers Can't reproduce it on EFCore 2.2.4 (all of the code above plus test case below)
```c#
	public class Test
	{
		[Fact]
		public void TestCase()
		{
			new Db();
		}
	}
```
I'm getting following compilation errors: 
```
CS1061	'EntityTypeBuilder<NonAbstractBase>' does not contain a definition for 'HasDiscriminator' and no accessible extension method 'HasDiscriminator' accepting a first argument of type 'EntityTypeBuilder<NonAbstractBase>' could be found (are you missing a using directive or an assembly reference?)
CS1061	'EntityTypeBuilder<Mid_NonAbstract_NonAbstract>' does not contain a definition for 'HasDiscriminator' and no accessible extension method 'HasDiscriminator' accepting a first argument of type 'EntityTypeBuilder<Mid_NonAbstract_NonAbstract>' could be found (are you missing a using directive or an assembly reference?)
```

**Comment by ajcvickers** [comment] 2019-07-02 15:14
@bessgeor When you say that you "can't reproduce it on EFCore 2.2.4", you mean that the bug has been fixed in that release? Or that you can't build against 2.2.4 and hence the compiler errors?

**Comment by bessgeor** [comment] 2019-07-03 17:36
@ajcvickers the second, can't build against 2.2.4

**Comment by ajcvickers** [comment] 2019-07-08 16:41
@bessgeor The code above builds fine for me against 2.2.4, and no exception is thrown when creating the model. Can you post a small, runnable project/solution or complete code listing that demonstrates the issues you are seeing.

**Comment by bessgeor** [comment] 2019-07-10 07:24
@ajvickers, I've managed to compile the example above during minimal repro creation. The issue doesn't appear on EF 2.2.4. Thank you.

**Closed** 2022-10-16 14:28 UTC
Labels: closed-no-further-action, customer-reported
