### ISSUE TITLE
dotnet-ef 3.0.0-preview5.19227.1 segfaults on start on Solus linux

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#15824] opened 2019-05-28 02:22 UTC
Hello

I am getting a segfault trying to run `dotnet-ef`.  This is a brand new project created with `dotnet new webapi`.  No other information given other than "Segmentation fault"

See below:

```
$ dotnet tool install -g dotnet-ef --version 3.0.0-preview5.19227.1 --add-source https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json --framework netcoreapp3.0 
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '3.0.0-preview5.19227.1') was successfully installed.
adam@adam-solus ~/Source/test $ dotnet-ef
Segmentation fault
adam@adam-solus ~/Source/test $
```

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     solus
 OS Version:  4.0
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /snap/dotnet-sdk/37/sdk/3.0.100-preview5-011568/

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  3.0.100-preview5-011568 [/snap/dotnet-sdk/37/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/snap/dotnet-sdk/37/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/snap/dotnet-sdk/37/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Some custom environment paths from bashrc .. mostly needed as workarounds on solus

```
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
export SSL_CERT_DIR=/dev/null
export PATH="$PATH:~/Software/azuredatastudio-linux-x64"


export DOTNET_ROOT=/snap/dotnet-sdk/current
export PATH="$PATH:$DOTNET_ROOT"
export PATH="$PATH:/home/adam/.dotnet/tools"
export MSBuildSDKsPath=$DOTNET_ROOT/sdk/$(dotnet --version)/Sdks
```

**Comment by ajcvickers** [comment] 2019-05-31 01:02
@karelz @danmosemsft Is "solus" one of our supported distros?

**Comment by ajcvickers** [comment] 2019-05-31 01:03
@arcooke Does everything else in .NET Core work for you? Is it just the dotnet-ef command that is broken?

**Comment by karelz** [comment] 2019-05-31 03:41
Never heard of it, so no, it is not supported ... see also list of supported OS: https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md

**Comment by arcooke** [comment] 2019-05-31 04:33
@karelz I do understand my OS is not supported though I believe my feedback can still be of some value.  I have no expectations for support. I figure someone would like to know if it is segfaulting for any reason. 

@ajcvickers I've had one other crash issue in coreclr (https://github.com/dotnet/coreclr/issues/24727) which was recently fixed (https://github.com/dotnet/coreclr/pull/24847).  dotnet-ef is the only other component causing issues that I've run into.  

Let me know if there's anything else that might be helpful to test.

Cheers

**Comment by karelz** [comment] 2019-05-31 05:34
My opinion is: investigation = support.
If you have root cause and know what should change to better support an unsupported OS, we would be ok with PR. However, investigating segfaults on non-supported platforms is 98% chance it will be waste of our time as it will be with high probability something related to the fact the distro is unsupported (i.e. known "problem"), while the investigation can easily take days. Not a good cost/benefit ratio IMO.

If you can reproduce it on a supported distro, then it is different story and we would be interested.

I hope it makes sense ...

**Comment by danmosemsft** [comment] 2019-05-31 06:07
It does not hurt to log an issue like this although as Karel says we are unlikely to investigate it may be something others in the community can collaborate with you on. I would include the native stack trace though.

**Comment by karelz** [comment] 2019-05-31 18:56
@arcooke if you can get callstack, etc., we may be able to advice or fix some things if it is clear from the info.
Otherwise, we can close the issue as unsupported OS ... I let @ajcvickers decide when is the right time for that ...

**Comment by ajcvickers** [comment] 2019-06-10 16:39
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:22 UTC
Labels: closed-could-not-reproduce, customer-reported
