### ISSUE TITLE
EFCore's error handling is useless and leads to loss of productivity and frustration!

### ISSUE THREAD

**Issue by Joebeazelman** [dotnet/efcore#29034] opened 2022-09-09 17:52 UTC
I just spent an 2 hours of my life that I can never get back trying to find out why my EF connection string keeps giving me an error every time I try to update my database:

> Format of the initialization string does not conform to specification starting at index 0.

I searched  around for every possible clue on what this cryptic error message could mean. The general consensus is that my string has a typo or is improperly formatted.  My string, however, has no errors and connects to the database when supplied directly to a SqlConnection.  Figuring it may prefer a certain style of connection string, I tried every imaginable variation only to discover nothing worked.

Just as I was about to give up on EF Core, I noticed the verbiage on how to submit a bug mentioned the verbose option (--verbose).  I used the option and  discovered the error has nothing to do with the connection string!  As demonstrated in the dump below, the error is because I have a design time error!  This could have been solved by proper error handling! 

What is going on at Microsoft?  Is this an unfortunate contraindication of legalization in Washington state?  Does Microsoft only hire developers who can survive their cruel whiteboarding process because they spent months memorizing leetcode solutions?  This is downright sad and pathetic! Get it together Microsoft!!!!

> Finding IDesignTimeDbContextFactory implementations...
> Finding application service provider in assembly 'ShopCartier'...
> Finding Microsoft.Extensions.Hosting service provider...
> Using environment 'Development'.
> Using application service provider from Microsoft.Extensions.Hosting.
> Found DbContext 'DbContext'.
> Finding DbContext classes in the project...
> Found DbContext 'DataContext'.
> Using context 'DataContext'.
> Finding design-time services referenced by assembly 'ShopCartier'...
> Finding design-time services referenced by assembly 'ShopCartier'...
> No referenced design-time services were found.
> Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
> Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
> Finding IDesignTimeServices implementations in assembly 'ShopCartier'...
> No design-time services were found.
> 'DataContext' disposed.

```
{
  "ConnectionStrings": {
    "DefaultConnection": "Data Source=localhost;Initial Catalog=Master;User Id=sa; Password=someThingComplicated1234;"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  }
}
```

> EF Core version: 6.0.8
> Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
> Target framework: .NET 6
> Operating system: macOS Monterey
> IDE: VSCode and VS Studio

**Comment by ajcvickers** [comment] 2022-09-09 18:53
@Joebeazelman What error message would have helped you in this case?

**Comment by Joebeazelman** [comment] 2022-09-09 19:18
The correct error message is "No referenced design-time services were found." The first message claiming there was a problem with my connection string is NOT the correct message.

**Comment by AraHaan** [comment] 2022-09-10 05:50
I had a similar problem, also check your Sql Server settings. Even when connecting on the same device make sure all the options for connecting to it are enabled. This will ensure you can also connect to it on a different device on the same network as well. I found that it helped me months ago with an similar issue as well.

**Comment by ajcvickers** [comment] 2022-09-10 09:29
@Joebeazelman It's unlikely that this is due to not finding design-time services in those assemblies. The verbose output here is saying that it looked and didn't find any, but that's not an error because there doesn't need to be any. Other than the messages in the verbose output, do you have other reasons to believe that this is the source of the problem?

It would help if you could attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-09-19 18:53
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-09-19 18:53 UTC
Labels: customer-reported
