### ISSUE TITLE
Add-Migration Issue when users folder has Chinese

### ISSUE THREAD

**Issue by hejiajun107** [dotnet/efcore#10619] opened 2017-12-28 05:04 UTC
When excute "add-migration init "
it shows "无法识别的转义序列"  because of the chinese name in users/ folder in windows 10

```
Exception message:
无法识别的转义序列。 
Stack trace:

**Comment by bricelam** [comment] 2018-01-02 18:44
Possibly a duplicate of #10467...

**Comment by ajcvickers** [comment] 2018-02-16 18:36
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by hejiajun107** [comment] 2018-02-28 02:38
Chinese folder name such as "users/用户/" may cause this error

**Comment by bricelam** [comment] 2018-03-09 23:26
I'm still not able to repro this. I'll assume it was fixed by #10532. If the error still occurs in versions 2.0.2 (not yet released) or 2.1.0-preview1-final, let us know.

**Closed** 2022-10-16 12:04 UTC
Labels: type-bug, closed-duplicate
