### ISSUE TITLE
Build models with conventions in MigrationsTestBase

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#20157] opened 2020-03-04 02:22 UTC

**Comment by ajcvickers** [comment] 2020-03-06 18:37
@roji Check for issue for/coverage of round-tripping snapshot.

**Comment by roji** [comment] 2020-05-06 13:27
Duplicate of  #11193?

**Comment by ajcvickers** [comment] 2020-09-17 23:23
See also:
* Migrations: Test using snapshot #11193
* Remaining clean up for migration tests #19668

**Comment by roji** [comment] 2021-05-04 17:32
MQ?

**Comment by roji** [comment] 2021-11-10 17:21
This would add good coverage, but doesn't seem like a bug.

**Closed** 2022-01-04 18:11 UTC
Labels: type-enhancement, area-test, closed-fixed, area-migrations, area-conventions, punted-for-6.0
