### ISSUE TITLE
[DatabaseGenerated(DatabaseGeneratedOption.Computed)] gets lost from Entity Models in DB first Scafolding Command

### ISSUE THREAD

**Issue by zp978** [dotnet/efcore#14910] opened 2019-03-04 06:47 UTC
Describe what is not working as expected.

[DatabaseGenerated(DatabaseGeneratedOption.Computed)] gets lost from Entity Models in DB first Scafolding Command

if I run the Scaffold-DbContext command for DB update in database first approach any data annotations are lost and need to be added manual to all Entity models.

**Comment by ajcvickers** [comment] 2019-03-04 17:43
@zp978 Can you be more explicit about what you mean by "gets lost." Do you mean that you expect them to be generated from database metadata, and that's not happening? Or that you had manually added some to generated entity classes, but then these were overwritten when the database was later scaffolded again? Or something else?

**Comment by zp978** [comment] 2019-03-05 04:01
Hello, 
I have a database computed column in a SQL Server table for which i have the [DatabaseGenerated(DatabaseGeneratedOption.Computed)]  attribute for that property in the Entity Class, whenever i scafold the database the attribute gets overwritten and i need to manually add the [DatabaseGenerated(DatabaseGeneratedOption.Computed)] attributte. Is there a way that this is not overwritten. Thanks.

**Comment by ajcvickers** [comment] 2019-03-05 16:50
@zp978 When you scaffold, do you get configuration of the property in `OnModelCreating`? If so, what does it look like?

**Comment by zp978** [comment] 2019-03-12 01:07
Hello,

Thanks for the reply. In OnModelCreating I do not see the Age (this is the db calculated field) [DatabaseGenerated(DatabaseGeneratedOption.Computed)] property although the property is there in the Entity Model after scaffold.

**Comment by ajcvickers** [comment] 2019-03-12 16:49
@zp978 Can you post the definition of the table in SQL so that we can try scaffolding from it and investigate.

**Comment by zp978** [comment] 2019-03-13 00:15
My Table 

CREATE TABLE [dbo].[Assets](
	[ID] [uniqueidentifier] NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[Age]  AS (datediff(month,case when [ManufactureDate] IS NULL then CONVERT([date],getdate()) else [ManufactureDate] end,CONVERT([date],getdate()))),
	[DateCommissioned] [date] NOT NULL,
	[ManufactureDate] [date] NULL,
	CONSTRAINT [PK_Assets] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Assets] ADD  CONSTRAINT [DF_Assets_ID]  DEFAULT (newid()) FOR [ID]
GO

ALTER TABLE [dbo].[Assets] ADD  CONSTRAINT [DF_Assets_Description]  DEFAULT ('') FOR [Description]
GO


ALTER TABLE [dbo].[Assets] ADD  CONSTRAINT [DF_Assets_DateCommissioned]  DEFAULT (getdate()) FOR [DateCommissioned]
GO

Model below 

public partial class Asset
    {
        public Guid Id { get; set; }
        public string Description { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public int? Age { get; set; }
        public DateTime DateCommissioned { get; set; }
        public DateTime? ManufactureDate { get; set; }
}

DB Context model builder 

modelBuilder.Entity<Asset>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasColumnName("ID")
                    .ValueGeneratedNever();



                entity.Property(e => e.DateCommissioned).HasColumnType("date");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.ManufactureDate).HasColumnType("date");

                         });


Anytime when I run the scaffold command in future I need to manually add the [DatabaseGenerated(DatabaseGeneratedOption.Computed)] in the asset class although the change is on another table and not the asset table, the asset class is updated and  [DatabaseGenerated(DatabaseGeneratedOption.Computed)]  attribute removed.

**Comment by ajcvickers** [comment] 2019-03-13 18:47
@zp978 I am not able to reproduce this. Using exactly that table, when I scaffold I get:
```C#
entity.Property(e => e.Age).HasComputedColumnSql("(datediff(month,case when [ManufactureDate] IS NULL then CONVERT([date],getdate()) else [ManufactureDate] end,CONVERT([date],getdate())))");
```
This configures the `Age` property as computed.

**Comment by ajcvickers** [comment] 2019-03-22 16:35
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:54 UTC
Labels: closed-could-not-reproduce, customer-reported
