### ISSUE TITLE
Running dotnet ef database update on linux failed with FileNotFoundException

### ISSUE THREAD

**Issue by Knaackee** [dotnet/efcore#6810] opened 2016-10-18 13:46 UTC
I have a project called `MyProject.App`. 

On windows i am able to run `dotnet ef database update` without problems (My Database gets updated as expected).

But on Linux (Build Server) and even on my Mac (same source code directory) i get 

```
System.IO.FileNotFoundException: Could not load file or assembly 'MyProject, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MyProject, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.EntityFrameworkCore.Design.Internal.OperationExecutor..ctor(CommonOptions options, String environment)
   at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
```

The strange thing is that i dont have any assembly called "MyProject". Ive searched the project and every file but didnt find something.

Any ideas?

**Comment by rowanmiller** [comment] 2016-10-24 17:42
Can you share a project that we can use to reproduce and debug the issue with?

**Comment by rowanmiller** [comment] 2016-10-31 18:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed** 2022-10-16 10:39 UTC
