### ISSUE TITLE
Timeout expired

### ISSUE THREAD

**Issue by Mitch528** [dotnet/efcore#6357] opened 2016-08-18 20:18 UTC
### The issue

After a while of heavy traffic, I encounter this issue which pretty much kills the app. A restart is usually required and sometimes even that doesn't really help. 

Is this an issue with EF? If so, is there a temporary workaround that can be applied until this bug is fixed?

```
Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached.
```

![error](http://i.imgur.com/VeAeufz.png)
### Further technical details

EF Core version: 1.0.0
Visual Studio version: VS 2015
SQL Server
Deployed on Azure

**Comment by divega** [comment] 2016-08-19 18:33
**Triage:** could you provide a code repro for the issue? 

The symptoms match a possible leak of connections which could exist in either your application code or in our stack. 

It would also help to know if this happens consistently after having the application running for a period of time and how consistently restarting the application help.

**Comment by Mitch528** [comment] 2016-08-19 19:23
I am unable to figure out where this problem is originating from, so I cannot provide a code reproduction of the issue. All I know is that it starts getting those errors usually after a few hours of being online. After that, the application then goes into an unusable state.

Restarting the application usually helps, although I think that it doesn't help as much when there is a large amount of traffic trying to get through at that same time.

I only use the database context in the scope of my controllers and services with dependency injection.

**Comment by divega** [comment] 2016-08-23 19:56
@Mitch528 there are no known issues with EF Core that would lead to these symptoms. If you could share your application's code there is a chance that we could find something by looking at the code or testing it. Let me know if you want to try that. 

Otherwise it is possible that we can spot something unusual if you just provide the following snippets:
- The code that registers EF related services in `Startup.ConfigureServices()`.
- Your `DbContext` and entity types (or at least a subset of them)
- Examples of how you use them in a controller
- Any other usage of EF, e.g. in other methods in `Startup`

**Comment by Mitch528** [comment] 2016-08-23 20:39
@divega 

Sure. Where should I send the code to?

**Comment by divega** [comment] 2016-08-25 21:50
@Mitch528 My Microsoft email address is the same as my GitHub alias.

**Comment by divega** [comment] 2016-08-31 18:34
@Mitch528 are you still planning to send a repro?

**Comment by ajcvickers** [comment] 2016-09-08 19:22
@Mitch528 I don't see anything obviously wrong in the way you are using the contexts in your application. The only thing that is somewhat dubious is the code in Startup where you build a service provider and then use this to create context instances which you then call Migrate on. Normally this should be done by first creating a scope and then requesting the context instances from this scope, then disposing the scope. However, in your case I think that what you have should be okay because you are disposing the context instances and then the service provider is being thrown away. It might be worth creating a scope for the context here just to be sure. Also, unrelated to what you are seeing but worth mentioning, when using this mechanism to migrate the database can have issues. For example, if there are ever multiple instances of your app running, then there is a race condition in migrating the database which could result in corruption.

**Comment by ajcvickers** [comment] 2016-09-08 19:23
Note for triage: Marking this for re-triage. We may want to try some stress testing to see if we can reproduce this. It could really be the pool running out of connections, but it is possible that there is something else going on.

**Comment by rowanmiller** [comment] 2016-09-12 18:09
I will use some load test tools to try and repro this

**Comment by rowanmiller** [comment] 2016-09-22 18:54
Note to self, the repro code for this is sitting in my 1.1.0 folder and has the issue number in the title.

**Comment by ajcvickers** [comment] 2017-03-10 20:17
@Mitch528 Can you let us know if you are still seeing this issue with the 1.1.1 release?

**Comment by ajcvickers** [comment] 2017-03-17 18:04
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 09:55 UTC
Labels: closed-could-not-reproduce
