### ISSUE TITLE
Incorrect syntax in the script generated by command "migrations script --idempotent"

### ISSUE THREAD

**Issue by ManuStang** [dotnet/efcore#10726] opened 2018-01-19 13:42 UTC
Hello,

I have a project with multiple migrations.
One of the migration have multiple procedures like this : 
`private static string SCRIPT_TableUserSynchronizationRepository_GetFirstPendingUserSynchronizations =
            @"CREATE PROCEDURE procedure_GetFirstPendingUserSynchronizations
                        [...]
              END";`

When i execute the command line "_dotnet ef migrations script_" everything work fine !

But when i execute the code generated by the command "_dotnet ef migrations script --idempotent_" i have several errors !

EF generate this kind of code : 
`IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20171124083142_addStoredProcedures')
BEGIN
    CREATE PROCEDURE procedure_GetFirstPendingUserSynchronizations                
                [...]
                  END
END;
GO`

And the error is "Incorrect syntax near the keyword 'Procedure'".

I have found a workaround by putting the "CREATE PROCEDURE" in "EXE(' [...]').
https://stackoverflow.com/questions/16729520/incorrect-syntax-near-the-keyword-procedure.

I use SQL Server 2016 (localdb)

Is it an EF Core bug ?

**Comment by bricelam** [comment] 2018-01-19 17:12
It's more-or-less by design. EF Core doesn't know which statements need to be in their own batch, so you're responsible for wrapping them inside `EXEC` as needed.

**Comment by ajcvickers** [comment] 2018-01-19 20:33
Per @bricelam's comment, closing this as by-design.

**Comment by markarnolditpro** [comment] 2019-02-04 19:55
This is giving me some grief also.  My hope was to generate scripts during my build pipeline with `--idempotent`, then pass it along to different release environments.  I won't be able to effectively build in CI/CD if I have to manually edit the output.  Understand this is pretty much by design, but at risk of being naive is it harmful if the tooling preemptively wraps everything in `EXEC`?

**Comment by bricelam** [comment] 2019-02-06 19:40
See https://github.com/aspnet/EntityFrameworkCore/issues/12911#issuecomment-416699916

**Comment by markarnolditpro** [comment] 2019-02-09 12:39
Thanks Brice.  Looking forward to 3.0.

Best Regards

**Closed** 2022-10-16 12:06 UTC
Labels: closed-by-design
