### ISSUE TITLE
HasQueryFilter ignores ToQuery declaration

### ISSUE THREAD

**Issue by zamzowd** [dotnet/efcore#15263] opened 2019-04-05 20:50 UTC
If a `DbQuery` is set up with `ToQuery`, and that `DbQuery` is used in `HasQueryFilter` for another DbSet or DbQuery, Entity Framework tries to query a saved view rather than use the ToQuery definition.

DataContext:
```csharp
public DbSet<Foo> Foos { get; set; }
public DbQuery<FilteredFoo> FilteredFoos { get; set; }
public DbSet<Bar> Bars { get; set; }

protected override void OnModelCreating(ModelBuilder builder)
{
  builder.Query<FilteredFoo>().ToQuery(() => 
    Foos
      .Where(b => !b.IsDeleted)
      .Select(foo => new FilteredFoo { Id = foo.Id, BarId = foo.BarId })
  );
  builder.Entity<Bar>().HasQueryFilter(bar => FilteredFoos.Any(foo => foo.BarId == bar.Id));
}
```

```
var foos = await Context.FilteredFoos.ToListAsync();
var bars = await Context.Bars.ToListAsync();
```

The first call to `FilteredFoos` works, but the second call to `Bars` fails with: `SqlException: Invalid object name 'FilteredFoos'`.  The constructed SQL for the call to `Bars` has `WHERE EXISTS (SELECT 1 FROM FilteredFoos)` rather than inject the Linq-To-Sql from `ToQuery`.

**Comment by ajcvickers** [comment] 2019-04-08 17:21
Duplicate of #13361

**Closed** 2022-10-16 13:59 UTC
Labels: customer-reported
