### ISSUE TITLE
Support arrays of related entity types

### ISSUE THREAD

**Issue by bcallaghan-et** [dotnet/efcore#20615] opened 2020-04-13 19:55 UTC
I have several classes that contain an array of linked items that should be stored in a separate table, using foreign keys to maintain a reference back to their parent. For example:

```cs
public class MyEntity
{
    public int Id { get; set; }
    public LinkedEntity[] LinkedItems { get; set; }
}

[Owned]
public class LinkedEntity
{
    public string Name { get; set; }
    public int Value { get; set; }
}
```

This setup builds the correct model and migrations, but fails at runtime if the array actually contains values. If I replace `LinkedEntity[]` with `ICollection<LinkedEntity>`, there are no errors, and the data is stored appopriately. However, the real `MyEntity` class is auto-generated and used by `XmlSerializer` which only supports collections that are arrays.

I would like to see arrays treated the same as any other collection type. They are already treated as such when building the model. Why are they treated any differently at runtime?

**Comment by ajcvickers** [comment] 2020-04-14 19:53
@bcallaghan-et EF needs a collection type that can have items added to it. Arrays can't be used because they are always a fixed size and the `ICollection.Add` method always throws.

Implementation of #2919 would allow this, so this is likely a duplicate of that issue--we will discuss.

**Closed** 2022-10-16 18:20 UTC
Labels: closed-duplicate, customer-reported
