### ISSUE TITLE
Exception in DatabaseErrorPageMiddleware.System.IObserver coming from SaveChangesFailed 

### ISSUE THREAD

**Issue by LeslieMurphy** [dotnet/efcore#10841] opened 2018-01-31 20:57 UTC
Had code that added a default row to a table, then tried to context.SaveChanges()

Application was in error - did not set two DateTime fields in the class; these are NOT NULL DB columns.

Result is an obscure error thrown in  DatabaseErrorPageMiddleware.System.IObserver 
(OnNext(KeyValuePair` KeyValuePair)

There should be a clean error message.
Stack trace:

EntityFrameworkCore.DatabaseErrorPageMiddleware.System.IObserver from DiagnosticsListener.Write from Internal.CoreLoggerExceptions.SaveChangesFailed from SaveChanges

### Steps to reproduce
Set up an entity with DateTime fields.  Mine has a PK of ID and one FK to another entity - not sure if those are relevant to the problem.

```c#

// Company
public class Company
    {
        [Key]
        [ScaffoldColumn(false)]
        public int ID { get; set; }

        [Required]
        [Display(Name = "Company Name")]
        public string CompanyName { get; set; }

        [Display(Name = "Address Line 1")]
        public string AddressLine1 { get; set; }

        [Display(Name = "Address Line 2")]
        public string AddressLine2 { get; set; }

        [Display(Name = "City")]
        public string City { get; set; }

        [Display(Name = "State")]
        public string State { get; set; }

        [Display(Name = "Zip Code")]
        [RegularExpression("^\\d{5}(?:[-\\s]\\d{4})?$",ErrorMessage ="Please enter a valid zip code.")]
        public string ZipCode { get; set; }

        [ForeignKey("Contact")]
        public int? ContactID { get; set; }
        public Person Contact { get; set; }
       
        [Display(Name = "Comments -- Visable to Internal Only")]
        public string InternalComments { get; set; }

        [Display(Name = "Comments -- Visable to all")]
        public string PublicComments { get; set; }

        [Display(Name = "Status")]
        [ScaffoldColumn(false)]
        public CompanyStatus Status { get; set; }

        [Display(Name = "Company Type")]
        [UIHint("CompanyTypeEditor")]
        public CompanyType CompanyType { get; set; }

        public List<Project> Projects { get; set;}

    }

    public enum CompanyStatus { Active, Archived}
    public enum CompanyType {  Internal, Client, Target}

// Project
public class Project
    {
       
        [Key]
        public int ID { get; set; }

        public int CompanyID { get; set; }
        public virtual Company Company { get; set; }

        [Display(Name = "Project Name")]
        public string ProjectName { get; set; } 

        [Display(Name = "Source System")]
        public SourceSystemType SourceSystem { get; set; }
        [Display(Name = "Target System")]
        public TargetSystemType TargetSystem { get; set; }

        [Display(Name = "Project Status")]
        public ProjectStatus Status { get; set; }
        
        [Display(Name = "Phases for this Project")]
        public string ProjectPhaseList { get; set; }

        [Display(Name = "Curent Project Phase")]
        public string CurrentProjectPhase { get; set; }

        public List<PersonProjectRoles> ProjectTeam { get; set; }

        public DateTime CreationDate { get; set; }
        public DateTime LastUpdatedDateTime { get; set; }

        public string CreatedBy { get; set; }
        public string LastUpdatedBy { get; set; }

        [Display(Name = "Comments -- Visable to Internal Only")]
        public string InternalComments { get; set; }

        [Display(Name = "Comments -- Visable to all")]
        public string PublicComments { get; set; }

        public string GetDatabaseName()
        {
            return ProjectName + ID;
        }
    }
    public enum ProjectStatus
    { Active, Archived, OnHold }

    public enum SourceSystemType
    { ABC, DEF, XYZ, Other }

    public enum TargetSystemType
    { ABC, DEF, XYZ, Other }


Company company = new Company
                {
                    CompanyName = "Acme Industries",
                    CompanyType = CompanyType.Client,
                    InternalComments = "Explosive Company",
                    Status = CompanyStatus.Active
                };
                context.Companies.Add(company);
                context.SaveChanges();
                int companyId = context.Companies.FirstOrDefault().ID;

Project project = new Project
                {
                    ProjectName = "TNT Merger",
                    CompanyID = companyId,
                    CreatedBy = "Default",
                    SourceSystem = SourceSystemType.ABC,
                    TargetSystem = TargetSystemType.DEF,
                    CreationDate = DateTime.Now,   // these two cause the exception if left NULL
                    LastUpdatedDateTime = DateTime.Now //  causes the exception if  left NULL
                };
                context.Projects.Add(project);
                context.SaveChanges();  // This throws the Object reference not set to an instance of object in DatabaseErrorPageMiddleware.System.IObserver 

```

### Further technical details
EF Core version: 2.0.0
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Window 10
IDE:  Visual Studio 2017 15.5.6

**Comment by ajcvickers** [comment] 2018-01-31 21:19
@LeslieMurphy Can you post the full stack trace and exception message?

**Comment by LeslieMurphy** [comment] 2018-01-31 22:09
{System.NullReferenceException: Object reference not set to an instance of
an object.
   at
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.System.IObserver
<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2
keyValuePair)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at
Microsoft.EntityFrameworkCore.Internal.CoreLoggerExtensions.SaveChangesFailed(IDiagnosticsLogger`1
diagnostics, DbContext context, Exception exception)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean
acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at zzz.Data.DbInitializer.Initialize(ApplicationDbContext context,
UserManager`1 _userManager) in
C:\Users\xxxx\source\Workspaces\zzz\zzz\zzz\Data\DbInitializer.cs:line 85
   at zzz.Program.Main(String[] args) in C:\Users\
xxxx\source\Workspaces\zzz\zzz\zzz\Program.cs:line 29}

**Comment by ajcvickers** [comment] 2018-02-01 17:28
@LeslieMurphy Thanks for the additional info. This looks like a duplicate of #9599

**Closed** 2022-10-16 12:07 UTC
Labels: closed-duplicate
