### ISSUE TITLE
i changed scaffold-dbcontext template for class name its work but i cant change filename

### ISSUE THREAD

**Issue by alsanbedirhan** [dotnet/efcore#30284] opened 2023-02-14 09:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i changed scaffold-dbcontext template for class name its work but i cant change filename

![image](https://user-images.githubusercontent.com/59397675/218692313-becb9275-51cc-429e-8fce-c5652ab9ad6d.png)
--EntityType.t4 file

![image](https://user-images.githubusercontent.com/59397675/218691330-8dd835f8-0e1e-47c3-bd2f-9370cf52d0f4.png)
--MyEntityClass

![image](https://user-images.githubusercontent.com/59397675/218691433-1b2e31fb-6307-4809-a435-6f9de7c105cf.png) 
--FileName

### Expected Behavior

how i can change file name

### .NET Version

7.0.102

**Comment by ajcvickers** [comment] 2023-02-16 19:18
Duplicate of #29541. Please vote (👍) for that issue.

**Closed by ajcvickers** 2023-02-16 19:18 UTC
Labels: customer-reported
