### ISSUE TITLE
Migrations slow build after upgrading from .NET Core 3.1 to .NET 6

### ISSUE THREAD

**Issue by VicenzoMartinelli** [dotnet/efcore#30057] opened 2023-01-13 15:38 UTC
Hi guys, need some help.
I have a solution with serveral projects, all targeting netcoreapp3.1.
In this solution i have a project with all the migration files and designers used in production, that i ignore from build when developing. 
I have about 220 migration files in this project, which is almost 1GB of files.

The build of this project (with dotnet cli) inside our ci/cd job used to run in about 12 minutes (💀), after upgrading to .NET 6 this build is taking more than 1 hour(not sure exactly because this is the timeout of the job).

Some issues that can  be related:
https://github.com/dotnet/efcore/issues/23291
https://github.com/dotnet/efcore/issues/23426

EF Core version: 6.0.9
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 6.07
Target framework: net6.0
Operating system: Linux 20.04

**Comment by roji** [comment] 2023-01-13 16:44
@VicenzoMartinelli can you confirm how you're getting to 1GB of migration file size, are you using data seeding with large amounts of data? We generally highly discouraged getting to this state - having 1GB of source files is an abnormal situation that could cause various kinds of issues. I can at least recommend trying to [reset your migrations](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#resetting-all-migrations) to help reduce the size.

Specifically about your issue... We're not currently aware of any specific outstanding issues - definitely make sure you're using the latest versions of VS and/or the dotnet SDK; please also check with the recently-released EF Core 7.0 to make sure that the problem exists there as well. Beyond that, we'd need some sort of repro to be able to investigate this; if it's possible to reduce the size - e.g. by resetting back to a single migration - while still showing a significant regression between EF Core 3.1 and 6.0, that would be ideal.

**Comment by VicenzoMartinelli** [comment] 2023-01-13 17:45
Yeah, we have a lot of seeds in our model and i'm aware that it's a big problem.
I will work on some tests with ef core 7,  try to make an effort to remove this seeds from our mapping and analyze the feasibility to reset our migrations too.

Furthermore, i'll verify some kind of repro and post here.
ty for now @roji

**Comment by ajcvickers** [comment] 2023-01-27 13:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-01-27 13:10 UTC
Labels: customer-reported

**Comment by MichelZ** [comment] 2023-05-08 08:19
I've created an MSBuild task that tries to solve this automatically. All you have to do is install the task.
(Not the historic migration collapse, but it decreases build times significantly by excluding most *.Designer.cs files on compilation)

It automatically moves these attributes from the `*.Designer.cs` file to the main code file:

```
[DbContext...
[Migration...
```

It sets the `*.Designer.cs` files to not compile:
`<DefaultItemExcludes>$(DefaultItemExcludes);**\*.Designer.cs</DefaultItemExcludes>`

It then looks for the latest `N`(configurable count) of *.Designer.cs files and specifically enables them for compilation by 
`<Compile Include="xxx" />`

Install:
`dotnet add package MSBuild.EntityFrameworkCore.RemoveDesignerCompilation --prerelease`

(You have to use `--prerelease` until there is a stable version published. I'd like to gather some pre-release feedback first)


[NuGet](https://www.nuget.org/packages/MSBuild.EntityFrameworkCore.RemoveDesignerCompilation)

[GitHub](https://github.com/MichelZ/MSBuild.EntityFrameworkCore.RemoveDesignerCompilation)

**Comment by DiogoAnphiloquio** [comment] 2024-04-12 18:14
Thanks for the solution, using DefaultItemExcludes for the "Designer.cs" files, we were able to solve the slowness problem when running build.
