### ISSUE TITLE
Wrong SQL generation with group by and Count() in EF Core 2.1 Preview 1

### ISSUE THREAD

**Issue by HSchwichtenberg** [dotnet/efcore#11322] opened 2018-03-19 11:04 UTC
In EF Core 2.1 Preview 1, this query

```C#
var groups = (from p in ctx.FlightSet
                   group p by p.Departure into g
                   select new { City = g.Key, Count = g.Count() }).Where(x => x.Count > 5).OrderBy(x => x.Count).ToList();
```
produces this SQL
```sql
SELECT [p].[Departure], COUNT(*)
FROM [Flight] AS [p]
WHERE COUNT(*) > 5
GROUP BY [p].[Departure]
```
which is wrong.

Exception:

System.Data.SqlClient.SqlException: 'An aggregate may not appear in the WHERE clause unless it is in a subquery contained in a HAVING clause or a select list, and the column being aggregated is an outer reference.'

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Windows 10 1703
SQL Server: 2017
IDE: Visual Studio 2017 15.6.1

**Comment by smitpatel** [comment] 2018-03-20 18:34
Generated SQL in nightly build
```SQL
      SELECT [p].[Departure] AS [City], COUNT(*) AS [Count]
      FROM [FlightSet] AS [p]
      GROUP BY [p].[Departure]
      HAVING COUNT(*) > 5
      ORDER BY [Count]
```
Duplicate of #10870

**Closed** 2022-10-16 12:14 UTC
