### ISSUE TITLE
deps.json is not generating Visual studio 2022 v 17.6.4

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#31186] opened 2023-07-05 11:22 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/depsjson-is-not-generating-Visual-studi/10404450)._

---
[severity:It's more difficult to complete my work]
Since A week, And I've tried all possible ways to fix this issue, But no way to fix it.
Please note I could not use the (dotnet ef migrations add) in MAUI Project based on this error>
dotnet : The specified deps.json [E:\MAUI\IFx\bin\Debug\net7.0-android\IFx.deps.json] does not exist

Please do something, As I'm very sure this is bug in VS.

Thanls.

---
#### Feedback Bot on 6/30/2023, 02:11 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2023-07-05 11:50
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-07-19 18:19
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-07-19 18:19 UTC
Labels: customer-reported
