### ISSUE TITLE
String StartsWith problem with square brackets

### ISSUE THREAD

**Issue by nikodz** [dotnet/efcore#18313] opened 2019-10-10 13:40 UTC
EF Core 3 translates `.Where(i => i.Name.StartsWith("a"))` with some complicated SQL query.

Part of that query is something like `a.[Name] like a.[Name] + N'%'` which works fine, since you don't have `[` symbol in `Name` column in database.

I guess this part of query needs some kind of escape for `[` symbol.

For me, this SQL query worked
```SQL
where a.[Name] like replace(a.[Name], '[', '[[]') + N'%'
```

### Steps to reproduce
Simple SQL query to check the behavior:
```SQL
declare @t table ([Name] nvarchar(100));
insert into @t values ('a [b]')

select * @t a
where a.[Name] like a.[Name] + N'%'
```

If we change string in column from `'a [b]'` to `'a b]'` or use where condition as mentioned above, it works.

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio Code

**Comment by smitpatel** [comment] 2019-10-10 17:08
Duplicate of #17948

**Closed** 2022-10-16 14:48 UTC
Labels: customer-reported
