### ISSUE TITLE
Use of hyphen in database name throwing error and creating database as General Purpose

### ISSUE THREAD

**Issue by bontempzadmin** [dotnet/efcore#22698] opened 2020-09-24 13:28 UTC
After spending hours trying to ensure that my Azure databases would not automatically be created as General Purpose by default, I came across an issue in which if my connection string contains a hyphen, the database will still be created (with the correct, hyphenated name), but the Service Tier and Database MaxSize limit are ignored. All attempts to submit the database name with qualifying or escape characters failed ([database-name], \"database-name\", [\"database-name\"], 'database-name').

It seems strange that the database can be created with the correct names (including hyphens), only to trigger an error message and not apply the metadata to ensure they are created on the appropriate, desired Azure plans. Is this a known issue, or am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f761f42d-980f-a967-92bb-9fe104894ebf
* Version Independent ID: 41253fd8-44e8-a72c-21e6-bc0a05030ffa
* Content: [Microsoft SQL Server Database Provider - Azure SQL Database Options - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/sql-server/azure-sql-database)
* Content Source: [entity-framework/core/providers/sql-server/azure-sql-database.md](https://github.com/dotnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/sql-server/azure-sql-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by ajcvickers** [comment] 2020-09-24 19:07
Duplicate of #19290.

@bontempzadmin This is fixed in EF Core 5.0. Can you try it with the RC1 release and report back if it is still failing?

**Closed** 2022-10-16 18:42 UTC
Labels: closed-duplicate, customer-reported
