### ISSUE TITLE
How to store a conditional/calculated property in ef core 6

### ISSUE THREAD

**Issue by mdhthahmd** [dotnet/efcore#30127] opened 2023-01-24 09:53 UTC
Hello,

I have the following entities

```csharp

public class Parent
{
    public int Id { get; set; }
    public string Name { get; set; }
    private readonly List<Child> _children;
    public IReadOnlyCollection<Child> Children => _children;
    public Status Status { get; private set; }
    private int _statusId;
}

public class Child
{
    private string _description;
    private bool _isValid;
    // other data fields
    public bool IsValid() 
    {
        return _isValid == true;
    }

     protected Child() { }
}


public class Status : Enumeration
{
   // Enumeration is from https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Domain/SeedWork/Enumeration.cs

    public static Status Pending = new(1, nameof(Pending));
    public static Status InValid = new(2, nameof(InValid));
    public static Status Valid = new(3, nameof(Valid));

    public Status(int id, string name)
        : base(id, name)
    { }

      public static IEnumerable<Status> List() =>
        new[] { Pending, InValid, Valid };

}
```

My question is how to configure the `Status` property and the `_statusId` in `Parent` Entity such that,

When `_children` collection is empty `Status` needs to be set to `Pending`, or
When all objects in `_children` collection returns true from `IsValid()` method, `Status` needs to be set to `Valid`, else
`Status` needs to be set to `InValid`.

Basically the Status is set from the state of the `_children` collection

Regards,

**Comment by roji** [comment] 2023-01-24 11:01
You could simply make Status a regular C# property which looks at Children and and calculates the return value from that. [Configure that property as unmapped](https://learn.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt#included-and-excluded-properties) in order to make sure it isn't persisted to the database.

**Comment by ajcvickers** [comment] 2023-01-25 19:32
Duplicate of #13316. For now, use an empty setter as shown in that issue.

**Comment by mdhthahmd** [comment] 2023-01-28 13:32
thanks for the tip @ajcvickers, have the following getter and setter for the field,

```csharp
public Status Status
{
    get
    {
        return _children.Count() == 0 
        ? Status.Pending
        : (_children.All(a => a.IsValid()) ? Status.Valid : Status.InValid);
    }
    private set { }
}
 
private int _statusId;
```
and it is working fine for the most part,
that is, the first db row insert to parent table works, but any consequent inserts fails with the following exception `Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_status'. Cannot insert duplicate key in object 'dbo.status'. The duplicate key value is (1)`
As far as i know, ef core is trying to insert the status for each parent save, but i am unsure how to prevent that.

**Comment by ajcvickers** [comment] 2023-01-29 19:47
@mdhthahmd This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by mdhthahmd** [comment] 2023-02-02 20:35
Hi,
@ajcvickers i have created a [repro](https://github.com/mdhthahmd/ef-core-6) as instructed, i hope this provides a full picture. Hope this clarifies the issue.

Regards

**Comment by ajcvickers** [comment] 2023-02-14 10:55
@mdhthahmd The `Status.Id` is configured as `.ValueGeneratedNever()` and always has the value of 1 when inserting.

**Closed** 2023-02-22 15:09 UTC
Labels: customer-reported
