### ISSUE TITLE
Upgrade to EFCore 7 Results in Unexpected Index Changes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#29880] opened 2022-12-17 11:00 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Upgrade-to-EFCore-7-Results-in-Unexpecte/10231883)._

---
[severity:It's more difficult to complete my work]
This is in regards to this issue:
https://github.com/dotnet/efcore/issues/29847

I have managed to reproduce this on an older solution.  Please find it attached as a zip.

1. load `Starbeam.sln`
2. Run `dotnet ef dbcontext optimize --output-dir Generated --project Starbeam.Entities.Integration --startup-project Starbeam.Entities.Design`

---
#### Feedback Bot on 12/16/2022, 02:19 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2022-12-17 11:02
Duplicate of #29847.

**Closed** 2022-12-17 11:02 UTC
Labels: customer-reported

**Comment by roji** [comment] 2022-12-17 14:49
Duplicate of #29847
