### ISSUE TITLE
about dotnet ef tool some idea/关于ef 升级数据库时的一些想法

### ISSUE THREAD

**Issue by guor-dev** [dotnet/efcore#26536] opened 2021-11-04 09:51 UTC
english: when i migrate a database to new version,if the excutions throw error,migration stop,the SQL has took effection,i must manual delete colum when i migrate again,could ef delete dirty data Auto?   
chinese: 当我在升级数据库版本的时候产生报错，导致升级失败，但是SQL已经执行了一部分，当我在下次执行的时候我必须去数据库中手动删除无用的列或者键，是否能在执行失败时自动回滚数据库操作呢？

any

**Comment by roji** [comment] 2021-11-04 10:52
Duplicate of #22616

**Comment by roji** [comment] 2021-11-04 10:52
@guor-dev #22616 (planned for EF Core 7.0) will roll back all the migrations being applied if an error occurred.

**Closed** 2022-10-16 20:12 UTC
Labels: customer-reported
