### ISSUE TITLE
Migration inconsistently generates nullable columns for derived classes

### ISSUE THREAD

**Issue by matthias-0** [dotnet/efcore#27859] opened 2022-04-22 09:23 UTC
## Description

When using inheritance with two nullable foreign keys the generated migration does not always set the inherited nullable navigation properties.

In the following example the columns for the table User is correctly for CreatedBy and ModifiedBy (nullable: true). But for the table Entity1 it is nullable false and the onDelete ist set for the foreign key.

I would expect the same behaviour for all tables to be like the user table.

Perhaps the user table is somehow generted correcty because the type of the navigation properties is users.

### Steps to reproduce

- Create Console App .NET 6
- Install EF Core 6 (SqlServer, Tools)
- Insert classes below
- Add-Migration Initial

### Code

EntityBase
```C#
    public abstract class EntityBase
    {
        public User CreatedBy { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        public int? CreatedById { get; set; }

        public User ModifiedBy { get; set; }
        [ForeignKey(nameof(ModifiedBy))]
        public int? ModifiedById { get; set; }
    }
```
User
```C#
    public class User: EntityBase
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }


        public string Name { get; set; }
    }
```
Entity1
```C#
    public class Entity1: EntityBase
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
    }
```

EfContext
```C#
    public class EfContext: DbContext
    {
        public DbSet<User> Users { get; set; }
        public DbSet<Entity1> Entity1s { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\\mssqllocaldb;Database=Console2;Trusted_Connection=True;MultipleActiveResultSets=true");
        }
    }
```

```C#
public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedById = table.Column<int>(type: "int", nullable: true),
                    ModifiedById = table.Column<int>(type: "int", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Users_Users_CreatedById",
                        column: x => x.CreatedById,
                        principalTable: "Users",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_Users_Users_ModifiedById",
                        column: x => x.ModifiedById,
                        principalTable: "Users",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateTable(
                name: "Entity1s",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CreatedById = table.Column<int>(type: "int", nullable: false),
                    ModifiedById = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Entity1s", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Entity1s_Users_CreatedById",
                        column: x => x.CreatedById,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Entity1s_Users_ModifiedById",
                        column: x => x.ModifiedById,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Entity1s_CreatedById",
                table: "Entity1s",
                column: "CreatedById");

            migrationBuilder.CreateIndex(
                name: "IX_Entity1s_ModifiedById",
                table: "Entity1s",
                column: "ModifiedById");

            migrationBuilder.CreateIndex(
                name: "IX_Users_CreatedById",
                table: "Users",
                column: "CreatedById");

            migrationBuilder.CreateIndex(
                name: "IX_Users_ModifiedById",
                table: "Users",
                column: "ModifiedById");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Entity1s");

            migrationBuilder.DropTable(
                name: "Users");
        }
    }
```

### Add-Migration output

```
C:\Stuff\AllTogetherNow\FiveOh>Add-Migration Initial -verbose
...
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'ConsoleApp2'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'EfContext'.
Using context 'EfContext'.
Finding design-time services referenced by assembly 'ConsoleApp2'...
Finding design-time services referenced by assembly 'ConsoleApp2'...
No referenced design-time services were found.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding IDesignTimeServices implementations in assembly 'ConsoleApp2'...
No design-time services were found.
DetectChanges starting for 'EfContext'.
DetectChanges completed for 'EfContext'.
```

### Versions

EF Core version: 6.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022  17.1.0

**Comment by ajcvickers** [comment] 2022-04-25 18:44
@matthias-0 The code above does not create a TPH mapping. This is because the `EntityBase` is not mapped or referenced as an entity type, and hence is treated as an un-mapped base type. This is why the migration creates two tables; a TPH mapping would only ever have one table.

**Comment by matthias-0** [comment] 2022-04-26 07:24
Maybe I misunderstood the TPH definition, but the creation of the tables is as I expected. The base class columns are merged into the derived classes (I thought this behavior was called TPH). The problem is that the merged columns for "CreatedById" and "ModifiedById" should always be nullable. But they are only nullable for the "Users" table, in all other tables (in this example "Entity1") the columns are not nullable .

**Comment by ajcvickers** [comment] 2022-04-26 11:08
Note for triage: with NRTs enabled, the self-referencing relationship is created as optional, while the relationship between types is created as Required. Not sure why this is happening--presumably something about the way the navigations are discovered/configured?

```
Model: 
  EntityType: Entity1
    Properties: 
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      CreatedById (int?) Required FK Index
      ModifiedById (int?) Required FK Index
    Navigations: 
      CreatedBy (User) ToPrincipal User
      ModifiedBy (User) ToPrincipal User
    Keys: 
      Id PK
    Foreign keys: 
      Entity1 {'CreatedById'} -> User {'Id'} ToPrincipal: CreatedBy Cascade
      Entity1 {'ModifiedById'} -> User {'Id'} ToPrincipal: ModifiedBy Cascade
    Indexes: 
      CreatedById 
      ModifiedById 
  EntityType: User
    Properties: 
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      CreatedById (int?) FK Index
      ModifiedById (int?) FK Index
      Name (string) Required
    Navigations: 
      CreatedBy (User) ToPrincipal User
      ModifiedBy (User) ToPrincipal User
    Keys: 
      Id PK
    Foreign keys: 
      User {'CreatedById'} -> User {'Id'} ToPrincipal: CreatedBy ClientSetNull
      User {'ModifiedById'} -> User {'Id'} ToPrincipal: ModifiedBy ClientSetNull
    Indexes: 
      CreatedById 
      ModifiedById 
```

**Comment by ajcvickers** [comment] 2022-04-26 16:42
Yes. Without NRTs, the code above generates optional relationships for both self-referencing and not--as expected because the FKs are nullable.

**Comment by ajcvickers** [comment] 2022-05-02 10:35
See also #27925 for a warning in cases like this.

**Comment by cyclr-adrian** [comment] 2022-11-21 12:41
I'm hitting this error, is there a workaround?

**Comment by cyclr-adrian** [comment] 2022-11-21 18:19
@ajcvickers I have tried adding `.IsRequired()` but it makes no difference.  I have filed an issue with more detail: https://github.com/dotnet/efcore/issues/29640

**Comment by AndriySvyryd** [comment] 2023-09-17 21:34
Duplicate of #30227

**Closed by AndriySvyryd** 2023-09-17 21:34 UTC
Labels: customer-reported
