### ISSUE TITLE
Error in Open SqliteDatabase

### ISSUE THREAD

**Issue by paulocarinhena** [dotnet/efcore#26854] opened 2021-11-30 15:35 UTC
Hi! In version 5.0.12 the code below works fine (example used: GetConnection("D:\\Banco\\sqlite\\bancoTeste.db")):

```C#
   public static SqliteConnection GetConnection(string caminhoBanco)
        {
            string ConnectionString = String.Format("Data Source={0};", caminhoBanco);
            SqliteConnection connection = new SqliteConnection(ConnectionString);
            if (connection.State != ConnectionState.Open)
                connection.Open();
            return connection;
        }
```

but in the latest (6.0.0) version it has the following error:

```
The type initializer for 'Microsoft.Data.Sqile.SQliteConnection' threw an exception
   at Microsoft.Data.Sqlite.Utilities.ApplicationDataHelper.GetFolderPath(String propertyName)
   at Microsoft.Data.Sqlite.Utilities.ApplicationDataHelper.get_LocalFolderPath()
   at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
```
Changed anything from the previous version to the new version?

Microsoft.Data.Sqlite:  version 6.0.0
Target framework: .NET 4.8
Operating system: Windows 11

**Comment by ajcvickers** [comment] 2021-11-30 15:42
Duplicate of #26574.

**Comment by paulocarinhena** [comment] 2021-11-30 15:53
Will this bug be fixed in version 6.0.1?

**Comment by ajcvickers** [comment] 2021-11-30 15:57
@paulocarinhena Yes; that's what the 6.0.1 milestone indicates.

**Comment by paulocarinhena** [comment] 2021-11-30 15:59
> @paulocarinhena Yes; that's what the 6.0.1 milestone indicates.

wonderful, thank you very much for your attention!

**Closed** 2022-10-16 20:17 UTC
Labels: customer-reported, area-adonet-sqlite
