### ISSUE TITLE
Error when scaffolding a DB first database on .NET Core 3

### ISSUE THREAD

**Issue by KianFitz** [dotnet/efcore#18131] opened 2019-09-29 16:56 UTC
When trying to run scaffold for a dbcontext on EF Core 3, it fails as one of the overloads for JsonDocument can't be found.

### Steps to reproduce

- Create new ASP.NET Core 3.0 project.
- Install EF Core
- Run scaffold command (e.g "dotnet ef scaffold "Server=localhost;Port=3306;Database=Database1;Username=user1;Password=password" MySql.Data.EntityFrameworkCore --verbose)

System.MissingMethodException: Method not found: 'System.Text.Json.JsonDocument System.Text.Json.JsonDocument.Parse(System.IO.Stream, System.Text.Json.JsonReaderOptions)'.
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Method not found: 'System.Text.Json.JsonDocument System.Text.Json.JsonDocument.Parse(System.IO.Stream, System.Text.Json.JsonReaderOptions)'.

### Further technical details

EF Core version:
Database provider: MySql.Data.EntityFrameworkCore
Target framework: ASP.NET Core 3.0
Operating system: Windows 10 Pro
IDE: 16.3.1

**Comment by ErikEJ** [comment] 2019-09-29 16:59
This is not a bug - you cannot use a EF Core 2 provider with EF Core 3

**Comment by Onekii** [comment] 2019-09-29 17:03
My apologies, i'll close the issue now. I wasn't aware it was outdated.

**Comment by ErikEJ** [comment] 2019-09-29 17:32
You should ask the maintainers for an update!

**Closed** 2022-10-16 14:46 UTC
Labels: closed-no-further-action, customer-reported
