### ISSUE TITLE
Problem with applying odata filter on IQueryable

### ISSUE THREAD

**Issue by MADzO** [dotnet/efcore#20262] opened 2020-03-12 11:28 UTC
We are trying to implement latest OData in our project. We are using EF Core, and what we are trying to do is, map the domain set to new IQueryable of Dto Models using custom expression function as mapper. After the apply of the OData filters, the query is broken and cannot be executerd.

### Steps to reproduce

IQueryable that is returned in the controller

```C#
_dbContext.PurchaseTypes.Select(Mapper.ToDto())
```

Expression function used for mapping

```C#
    public static Expression<Func<PurchaseType, PurchaseTypeDto>> ToDto()
    {
        return domain => new PurchaseTypeDto
        {
            Id = domain.Id,
            Code = domain.Code
        };
    }
```

In the controller, we have service call (which returns IQueryable) and we are applying the ODataQueryOptions opts.

```C#
    [HttpGet]
    public async Task<IActionResult> Get(ODataQueryOptions<PurchaseTypeDto> opts)
    {
        var query =
            opts.ApplyTo(_purchaseTypeService.GetAll()) as IQueryable<PurchaseTypeDto>;

        var result = await query.ToListAsync();

        return Ok(result);
    }
```
Expected result
When the url is accessed https://localhost:44361/odata/PurchaseType?%24filter=Id%20eq%202,
execute the query and result is returned

Actual result
The created query could not be executed

```
InvalidOperationException: The LINQ expression
'DbSet
.Where(p => new PurchaseTypeDto(
p.Id,
p.Code
).Id == __TypedProperty_0)' could not be translated.
```

### Further technical details

Microsoft.AspNetCore.OData v7.3.0
Microsoft.EntityFrameworkCore v3.1.2
.Net Core 3.1 WebApi Project

**Comment by smitpatel** [comment] 2020-03-12 14:11
This is likely duplicate of #19087

**Comment by MADzO** [comment] 2020-03-13 09:01
> This is likely duplicate of #19087

By changing Microsoft.EntityFrameworkCore version from 3.1.2 to 2.2.6 the problem is resolved so indeed it is duplicated

**Closed** 2022-10-16 18:16 UTC
Labels: customer-reported
