### ISSUE TITLE
Specify Throughput for a Cosmos Container or Database

### ISSUE THREAD

**Issue by Thorstensen** [dotnet/efcore#20983] opened 2020-05-18 17:15 UTC
When using Entity Framework Core with the `UseCosmos` options, I would like to be able to specify on what level the throughput should be configured. In our current solution, we have a database with several containers. By default, Entity Framework specifies the Throughput(RU/s) on the container during creation of the database. 

I would like an option to specify on what level to configure the throughput(RU/s) on. For instance when using the Action in `UseCosmos`:

**Example 1:**

```
optionsBuilder.UseCosmos(_instanceUrl,  _primaryKey,  _databaseName, options =>
{
    options.ThroughputOn(typeOfThroughput: Level.Database, amount:1000);
});
```
**Example 2:**

```
optionsBuilder.UseCosmos(_instanceUrl,  _primaryKey,  _databaseName, options =>
{
    options.ThroughputOn(typeOfThroughput: Level.Containers, amount:400);
});
```

**Comment by Marusyk** [comment] 2020-08-03 20:39
+1 it would be a nice fature

**Comment by AndriySvyryd** [comment] 2020-11-26 08:38
Duplicate of https://github.com/dotnet/efcore/issues/17301

**Closed** 2022-10-16 18:25 UTC
Labels: type-enhancement, closed-duplicate, customer-reported, area-cosmos

**Comment by ciacco85** [comment] 2024-03-30 06:05
any update?

**Comment by roji** [comment] 2024-03-30 13:56
@ciacco85 this issue was closed as a duplicate of #17301, which was done for EF 6.0.
