### ISSUE TITLE
System.MissingMethodException IEntityType.get_ClrType()

### ISSUE THREAD

**Issue by john1452** [dotnet/efcore#11986] opened 2018-05-13 13:23 UTC
### Describe what is not working as expected.
I am trying to retrieve the interfaces of entities in ModelBuilder inside OnModelCreating method.

The code I am using is: 

 ```
 var entites = builder.Model.GetEntityTypes();
            foreach (var mutableEntityType in entites)
            {
                var interfaces = mutableEntityType.ClrType.GetInterfaces();
            }
```

I want to be able to find the interfaces and entity types implemented by the entity that are currently inside ModelBuilder.

Below is the exception i am getting.

###  Exception
```

`System.MissingMethodException: 'Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.IEntityType.get_ClrType()'.'`

```

### Steps to reproduce

run the following code in OnModelCreating method.

```c#

 var entites = builder.Model.GetEntityTypes();
            foreach (var mutableEntityType in entites)
            {
                var interfaces = mutableEntityType.ClrType.GetInterfaces();
            }
```

### Further technical details
EF Core version: 2.0.3
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.6.7)

**Comment by ajcvickers** [comment] 2018-05-14 17:37
@john1452 This kind of exception usually indicates a mismatch of package versions. What does your .csproj look like?

**Comment by ajcvickers** [comment] 2018-05-21 17:52
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by enkodellc** [comment] 2021-09-13 00:47
I was receiving this when trying use EF6 with Finbuckle.MultiTenant. As of writing this Finbuckle does not support EF6. Just in case anyone else didn't read their documentation like I didn't.

**Closed** 2022-10-16 12:24 UTC
Labels: closed-could-not-reproduce, customer-reported
