### ISSUE TITLE
Two of the same owned classes inside an entity returns an exception on building the model

### ISSUE THREAD

**Issue by amoorthaemer** [dotnet/efcore#12692] opened 2018-07-17 15:55 UTC
Hi,

Sorry, I'm productive today ...
I have an (owned) Address class with a reference to a Country entity (mandatory)
When I create an entity class with two properties of Address (e.g. Address and BillingAddress) I receive this exception on creating the model ... I guess I'm not doing anything wrong here, although I suspect the references to the Country entity ...

Result StackTrace:	
at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(TypeIdentity& type, ConfigurationSource configurationSource, Boolean throwOnQuery)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource, Boolean throwOnQuery)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(Type type)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at DryIoc.Registrator.<>c__DisplayClass27_0.<RegisterDelegate>b__0(IResolverContext r)
   at lambda_method(Closure )
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args)
   at lambda_method(Closure )
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureDeleted()
   at Nodes.Data.Tests.UnitTest1.<TestEntityModel>d__3.MoveNext() in C:\Users\BertM\source\repos\RPX_Market\src\Nodes.Shared\Nodes.Data.Tests\UnitTest1.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	
Test method Nodes.Data.Tests.UnitTest1.TestEntityModel threw exception: 
**System.InvalidOperationException: The convention invocations have reached the recursion limit. This is likely an issue in EF Core, please report it.**

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Window 10
IDE: Visual Studio Enterprise 2017 15.7.5

**Comment by divega** [comment] 2018-07-17 19:31
@AndriySvyryd will look for a duplicate of this.

**Comment by AndriySvyryd** [comment] 2018-07-17 21:55
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/12628

**Comment by amoorthaemer** [comment] 2018-07-18 06:11
Hmmmm, I see you have marked it as a duplicate... workaround by using fluent api is not working for me because I already use the fluent api... any other workaround on this?

**Comment by AndriySvyryd** [comment] 2018-07-18 06:14
@amoorthaemer The stack trace suggests that you are using the `[Owned]` annotation. Try removing it as part of the workaround.

**Comment by amoorthaemer** [comment] 2018-07-18 06:15
Ah ... thanks will try that ...

**Comment by amoorthaemer** [comment] 2018-07-18 10:41
Ok works ... thanks

**Closed** 2022-10-16 13:19 UTC
Labels: customer-reported
