### ISSUE TITLE
Using these could lead to Memory Leak?

### ISSUE THREAD

**Issue by bijaymandal362** [dotnet/efcore#32678] opened 2023-12-27 00:03 UTC
```c#
    // PostgreSQL
    services.AddDbContext<ApplicationDbContext>(options =>
    {
        options.UseNpgsql(builder.Configuration.GetConnectionString("Default"),
            action => NpgsqlHelpers.SetupNpgsql(action, builder.Configuration,
                typeof(NpgsqlHelpers).Assembly.FullName));
#if DEBUG
        options.EnableSensitiveDataLogging(true);
#endif
    },
    ServiceLifetime.Transient, ServiceLifetime.Singleton);

    EntityFrameworkManager.ContextFactory = context =>
    {
        var loggerFactory = new LoggerFactory();

        var options = new DbContextOptionsBuilder<ApplicationDbContext>();

        options.UseNpgsql(builder.Configuration.GetConnectionString("Default"),
           action => NpgsqlHelpers.SetupNpgsql(action, builder.Configuration, typeof(NpgsqlHelpers).Assembly.FullName));
#if DEBUG
        options.EnableSensitiveDataLogging(true);
#endif
        return new ApplicationDbContext(loggerFactory, options.Options);
    };
```

is this necessary to use ContextFactory? and using  ServiceLifetime.Transient, ServiceLifetime.Singleton can lead to memory leak?
is above is the good apporach to use EF core, 

my      GC Heap Size (MB)                                                     12
so from where i am getting memory leak?
I am using dot net 6

**Comment by ajcvickers** [comment] 2024-01-03 14:38
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2024-01-25 17:58
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-01-25 17:58 UTC
Labels: customer-reported
