### ISSUE TITLE
OwnedType does not work with type configured with .ToSqlQuery

### ISSUE THREAD

**Issue by romfir** [dotnet/efcore#34160] opened 2024-07-04 12:55 UTC
When type configured using `ToSqlQuery` has an owned type, EF Core generates incorrect query

### EF Core Config
```C#
async Task Main()
{
	var c = new Context();

	c.Centres.First(); //Invalid object name 'Centres'.
}

public class Context : DbContext
{
	public DbSet<Centre> Centres { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		base.OnModelCreating(modelBuilder);

		modelBuilder.Entity<Centre>(config =>
		{
			config.ToSqlQuery(@"SELECT c.Id, c.Name, cg.Guid FROM CENTRE c
			JOIN CentreGuid cg on cg.CentreId = c.Id
			");

			config.OwnsOne(c => c.Test, c =>
			{
				c.Property(c => c.Guid).HasColumnName("Guid");
			});
		});
	}

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		optionsBuilder
			.UseLazyLoadingProxies()
			.UseSqlServer(".")
			.EnableSensitiveDataLogging(true);
	}
}

public class Centre
{
	public int Id { get; set; }
	public string Name { get; set; }
	public GuidWrapper Test { get; set; }
}

public class GuidWrapper 
{
	public Guid Guid { get; set; }
}


```

### Generated SQL
```sql
SELECT TOP(1) [u].[Id], [u].[Name], [c].[Id], [c].[Guid]
FROM (
    SELECT c.Id, c.Name, cg.Guid FROM CENTRE c
    			JOIN CentreGuid cg on cg.CentreId = c.Id
    			
) AS [u]
LEFT JOIN [Centres] AS [c] ON [u].[Id] = [c].[Id]
```
Here we can observe join to non existant table `Centres`. The join should eaither not be made and its data shoud be selected from the first part or it should be made to the same subquery as in the first part 

Possibly releated issue: https://github.com/dotnet/efcore/issues/29300

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer 8.0.4
Target framework: .NET 8.0

**Comment by ajcvickers** [comment] 2024-07-07 14:19
Duplicate of #14525

**Closed by ajcvickers** 2024-07-07 14:19 UTC
Labels: customer-reported
