### ISSUE TITLE
attribute in base class property lost when generating new migrations from inheriting class

### ISSUE THREAD

**Issue by felixxu06** [dotnet/efcore#31162] opened 2023-06-30 11:18 UTC
I have a base class called 

```c#
public abstract class BaseEntity
{  
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public virtual Int64 Id { get; set; }

    public virtual Int64 CreatedById { get; set; }

    public virtual UserEntity? CreatedBy { get; set; }

    public virtual DateTime CreatedAt { get; set; }

    public virtual Int64 LastUpdatedById { get; set; }

    public virtual UserEntity? LastUpdatedBy { get; set; }

    public virtual DateTime LastUpdatedAt { get; set; }

    public virtual DateTime? DeletedAt { get; set; }

    public virtual Guid Uuid { get; set; }
}
```

And a heritage class called audit,

```C#
public class Audit : BaseEntity
    {
        public Guid AssociatedListId { get; set; }
}
```

After generating a new migration, the audit table don't has IdentityColumn annotation.

in the table I give attribute [DatabaseGenerated(DatabaseGeneratedOption.Identity)] directly,
it can generate IdentityColumn annotation.

Why inheritance class can't inherit the attribute?

**Comment by ajcvickers** [comment] 2023-07-07 16:56
@felixxu06 

> After generating a new migration, the audit table don't has IdentityColumn annotation.

Can you explain a bit more what you mean by this? What kind of "annotation" are you expecting on which "table" construct?

**Comment by ajcvickers** [comment] 2023-07-26 19:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-07-26 19:43 UTC
Labels: customer-reported
