### ISSUE TITLE
INSERT error (The property 'ID' on entity type 'xxx' has a temporary value)

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/efcore#21555] opened 2020-07-08 01:34 UTC
See https://github.com/dotnet/efcore/issues/9552

Same issue still in 3.1.5

If I remove the Entity property it `Attach`'s without issue and I can even use `Update`

## Solution

Automatically null the references which are in the entity during the building of the graph in `SaveChanges`, it's annoying and pointless to get this because you can just erase or ignore the references yourself.

**Comment by juliusfriedman** [comment] 2020-07-08 02:00
I have a entry which has multiple entities which can be attached e.g. many to one.

When I don't attach them I get the exception.

I propose you just null these if they are in the graph and consider them unchanged unless someone adds them / updates or deletes them.

**Comment by ajcvickers** [comment] 2020-07-10 16:11
As @smitpatel said, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by juliusfriedman** [comment] 2020-07-10 18:02
The problem is in my current project not the one I will produce (but hopefully I can)

The point still stands. Why do we throw at all in these sitations.

**Comment by ajcvickers** [comment] 2020-07-24 15:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:32 UTC
Labels: closed-could-not-reproduce, customer-reported
