### ISSUE TITLE
 System.InvalidOperationException: The instance of entity type 'AccountsLabels' cannot be tracked because another instance with the key value '{AccountsTreeEntityId: 65, LabelId: 25}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.

### ISSUE THREAD

**Issue by M-JOXx** [dotnet/efcore#32149] opened 2023-10-24 07:29 UTC
i'm using Blazor , I think this issue happend while using Blazor.

The Exceptions :

>  System.InvalidOperationException: The instance of entity type 'AccountsLabels' cannot be tracked because another instance with the key value '{AccountsTreeEntityId: 65, LabelId: 25}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.

Please I need to solve this asap . and why this happen??

Database : MySQL
DotNet Version : 7.0.400
--------------------------------------------------------
      protected async Task EditActionAccountTree(ActionEventArgs<AccountTreeDto> Args)
      {

      await DeleteOlds(entity.Id);

       if (Args.Data._selectedlabels != null)
       {
           var alllabels = Args.Data._selectedlabels.Distinct();
           foreach (var item in alllabels)
           {
                      **//Here throw an exception** 
               _accountlabelService.Add(new AccountsLabels
               {
                   AccountsTreeEntityId = entity.Id,
                   LabelId = item
               });
           }
       }
          _accountService.Edit(entity);
       }

      protected async Task<bool> DeleteOlds(int Id)
      {
          var Old = _accountlabelService.GetByList(x => x.AccountsTreeEntityId == Id, false, false);

          _accountlabelService.DeleteRange(Old);

          return true;
      }

**Comment by ajcvickers** [comment] 2023-10-24 11:13
See [general guidance here](https://learn.microsoft.com/en-us/ef/core/change-tracking/identity-resolution). If this doesn't help, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2023-11-08 18:36
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-11-08 18:36 UTC
Labels: customer-reported
