### ISSUE TITLE
Query: inconsistent behavior between relational and InMemory/L2O for queries grouping by a constant

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#19683] opened 2020-01-23 20:05 UTC
In relational we ignore groupby constant or parameter, so we just generate simple select. However, on InMemory and Linq2Objects we generate a single grouping with the key.

**Comment by ajcvickers** [comment] 2020-01-24 19:08
Talk with @smitpatel on this. Related to client-grouping.

**Comment by smitpatel** [comment] 2020-02-06 21:58
Duplicate of #19027

**Comment by smitpatel** [comment] 2021-09-10 23:51
`StartsWith(null)` is exception in client-side. If we consider the result as false then the translation on relational is incorrect. It should group by false and just generate 1 grouping.

**Comment by smitpatel** [comment] 2022-05-03 01:17
Poached

**Closed** 2022-05-04 21:28 UTC
Labels: type-bug, closed-fixed, area-query
