### ISSUE TITLE
Invalid SQL generated in Table-per-hierarchy with discriminator configuration

### ISSUE THREAD

**Issue by jamezamm** [dotnet/efcore#33486] opened 2024-04-07 07:20 UTC
I am using EFCore Version 8.0.3 with Oracle Database.

The Models:
```
[PrimaryKey(nameof(Gkey))]
[Table("NOTIFICATIONS")]
public class Notification
{
	[Column("GKEY")] public long Gkey { get; set; }
	[Column("TITLE")] public string Title { get; set; }

	[ForeignKey(nameof(NotificationPrivilege.Id))]
	public virtual ICollection<NotificationPrivilege> NotificationPrivileges { get; set; } = new List<NotificationPrivilege>();
}

[PrimaryKey(nameof(ContextId), nameof(Id), nameof(PrivilegeId))]
[Table("PRIVILEGES")]
public class Privilege
{
	[Column("CONTEXT_ID")] public string ContextId { get; set; }
	[Column("ID")] public long Id { get; set; }
	[Column("PRIVILEGE_ID")] public string PrivilegeId { get; set; }
}

public class NotificationPrivilege : Privilege
{
}
```

The discriminator model configuration:
```
modelBuilder.Entity<Privilege>()
            .HasDiscriminator(x => x.ContextId)
            .HasValue<NotificationPrivilege>("NOTIFICATIONS");
```

The query:
```
MyDbContext.Query<Notification>().Include(x => x.NotificationPrivileges).ToList();
```

The generated SQL from the above query:
```
SELECT "s"."GKEY", "s"."TITLE", "t"."CONTEXT_ID", "t"."ID", "t"."PRIVILEGE_ID", "t"."NotificationGkey"
FROM "NOTIFICATIONS" "s"
LEFT JOIN (
    SELECT "w"."CONTEXT_ID", "w"."ID", "w"."PRIVILEGE_ID", "w"."NotificationGkey"
    FROM "PRIVILEGES" "w"
    WHERE "w"."CONTEXT_ID" = N'NOTIFICATIONS'
) "t" ON "s"."GKEY" = "t"."NotificationGkey"
ORDER BY "s"."GKEY", "t"."CONTEXT_ID", "t"."ID"
```

The query above correctly generated SQL for the discriminator configuration but is unable to find the foreign key `NotificationPrivilege.Id` specified in the base type. Thus it is generating a phantom column **NotificationGkey**.

Replacing `"s"."GKEY" = "t"."NotificationGkey"` with `"s"."GKEY" = "t"."ID"` and removing `"t"."NotificationGkey"` and `"w"."NotificationGkey"` would make the SQL work.

This issue is linked with issue #33481. Solving one issue would solve the other one.

**Comment by roji** [comment] 2024-04-07 07:38
@jamezamm is this a different issue from #33481? Isn't #33481 enough to track this?

**Comment by jamezamm** [comment] 2024-04-07 07:50
Both issues have the same outcome, but I think this issue is better explained than #33481.

**Comment by maumar** [comment] 2024-08-08 07:59
dupe of https://github.com/dotnet/efcore/issues/33481

**Closed by maumar** 2024-08-08 07:59 UTC
Labels: customer-reported, area-query
