### ISSUE TITLE
EF Core 8.0: Arrays with Microsoft SQL Server:  Any type for which you define your own value converter

### ISSUE THREAD

**Issue by jaliyaudagedara** [dotnet/efcore#33958] opened 2024-06-11 05:55 UTC
## Ask a question

[A beginner’s guide to mapping arrays in EF Core 8](https://devblogs.microsoft.com/dotnet/array-mapping-in-ef-core-8/) states the following (@ajcvickers nice post by the way):

> What types can be used in arrays?
Any type that is natively supported by the database, as well as any type for which EF has a [built-in value converter](https://learn.microsoft.com/ef/core/modeling/value-conversions), or any type for which you define your own value converter.

So I have tried the following code.

```csharp
public record Post
{
    public int Id { get; set; }

    public string Title { get; set; }

    public PostEdit[] PostEdits { get; set; }
}

public record PostEdit
{
    public string EditedBy { get; set; }

    public DateTime EditedDatetime { get; set; }
}
```

In the DbContext,
```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    var jsonSerializerOptions = new JsonSerializerOptions
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        PropertyNameCaseInsensitive = true
    };

    // ValueConverter for PostEdits
    var converter = new ValueConverter<PostEdit[], string>(
        x => JsonSerializer.Serialize(x, jsonSerializerOptions),
        x => JsonSerializer.Deserialize<PostEdit[]>(x, jsonSerializerOptions));

    modelBuilder
        .Entity<Post>()
        .Property(e => e.PostEdits)
        .HasConversion(converter);
}
```
And querying as follows:

```csharp
List<Post> postsEditedByUser = await context.Posts
    .Where(x => x.PostEdits.Any(x => x.EditedBy == "User 1"))
    .ToListAsync();
```
And the query fails:
```
      Compiling query expression:
      'DbSet<Post>()
          .Where(x => x.PostEdits
              .Any(x => x.EditedBy == "User 1"))'
Unhandled exception. System.InvalidOperationException: The LINQ expression 'x => x.EditedBy == "User 1"' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitLambda[T](Expression`1 lambdaExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression, Boolean applyDefaultTypeMapping)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression, Boolean applyDefaultTypeMapping)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateExpression(Expression expression, Boolean applyDefaultTypeMapping)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateLambdaExpression(ShapedQueryExpression shapedQueryExpression, LambdaExpression lambdaExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```
So, the array doesn't seem to support `any type for which you define your own value converter`. Or am I missing something?

EF Core version:
```
Database provider: Microsoft.EntityFrameworkCore.SqlServer 8.0.6
Target framework: .NET 8
```
Operating system:
```
IDE: Visual Studio Enterprise 2022 (64-bit) - Preview Version 17.11.0 Preview 1.1
```

**Comment by roji** [comment] 2024-06-11 07:25
You need to remove the value conversion configuration in your OnModelCreating. As per the blog post, EF's support for JSON arrays is built-in and does not depend on the user defining a value converter. In fact, if you do, EF can no longer translate queries over the JSON document (as you're trying above) because it has no idea about the internal representation of the JSON document you produce from your value converter.

**Comment by jaliyaudagedara** [comment] 2024-06-11 09:06
Thanks @roji!

> Refers to scalar/primitive types in arrays, whereas you're trying to apply a value converter to the entire array. That can't be supported with querying.
Got it!

Tried the following, didn't work :(
> You need to remove the value conversion configuration in your OnModelCreating
```
Unhandled exception. System.InvalidOperationException: The entity type 'PostEdit' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.
```

**Comment by roji** [comment] 2024-06-11 09:27
So take a look at this again:

> Any type that is natively supported by the database, as well as any type for which EF has a [built-in value converter](https://learn.microsoft.com/ef/core/modeling/value-conversions), or any type for which you define your own value converter.

You're trying to map an array of PostEdit, which isn't a scalar/primitive type (like int, string). What you're looking for is JSON mapping, which was added with EF Core 7.0 - [see these docs](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#json-columns). For that, you're missing the ToJson() configuration. To summarize, there's a pretty strict distinction between scalars/primitives (even when those have a value converter configured), and "structural types", which can contain multiple scalars (or other structural types). Since PostEdit is a structural type, you need to use ToJson().

Am going to go ahead and close this issue as everything seems by design, but if you're having further problems don't hesitate to post back here.

**Closed by roji** 2024-06-11 09:27 UTC
Labels: customer-reported

**Comment by jaliyaudagedara** [comment] 2024-06-11 09:38
Thanks @roji, appreciate your patience :)

Finally, got it. I almost forgot `ToJson()` :(

```csharp
public record Post
{
    public int Id { get; set; }

    public string Title { get; set; }

    // No longer can be an array
    public List<PostEdit> PostEdits { get; set; }
}
```
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Post>()
        .OwnsMany(x => x.PostEdits, x =>
        {
            x.ToJson();
        });
}
```
Now a query is getting built.
```
SELECT [p].[Id], [p].[Tags], [p].[Title], [p].[Visits], [p].[PostEdits]
      FROM [Posts] AS [p]
      WHERE EXISTS (
          SELECT 1
          FROM OPENJSON([p].[PostEdits], '$') WITH (
              [EditedBy] nvarchar(max) '$.EditedBy',
              [EditedDatetime] datetime2 '$.EditedDatetime'
          ) AS [p0]
          WHERE [p0].[EditedBy] = N'User 1')
```

Think what drove me the other way is,
> Any type for which you define your own value converter.

Thought it's `Any` type and not just the `scalar/primitive` types.

**Comment by roji** [comment] 2024-06-11 09:50
> Any type for which you define your own value converter.

That's true; you can indeed map any .NET type (like PostItem) by defining a value converter over it, at which point it's mapped as a scalar/primitive in the database; but by doing this you lose the ability to query over it.

**Comment by jaliyaudagedara** [comment] 2024-06-11 10:08
yeah, makes sense!

Thank you again for all the explanations, highly appreciated!
