### ISSUE TITLE
`SingleOrDefault` causes `QueryClientEvaluationWarning`

### ISSUE THREAD

**Issue by Yaojian** [dotnet/efcore#6455] opened 2016-09-02 03:44 UTC
### The code which causes an exception

```
            var builder = new DbContextOptionsBuilder<MsSqlDomainContext>()
                .UseSqlServer(config.ConnectionString)
                .ConfigureWarnings(warnings =>
                {
                    warnings.Throw(RelationalEventId.QueryClientEvaluationWarning);
                });
            var options = builder.Options;

            using (var dbContext = new MsSqlDomainContext(options))
            {
                var entity = dbContext.Dummies.SingleOrDefault(x => x.Id == 1);  //This line causes exception
                Assert.Null(entity);
            }
```
### The issue

SQL Profiler shows that the `SingleOrDefault` function can be translated to SQL successfully with `ConfigureWarnings` disabled:

```
SELECT TOP(2) [x].[Id], [x].[BoolValue], [x].[DateValue], [x].[EnumValue], [x].[StrValue], [x].[TextValue]
FROM [teamwork].[TwDummy] AS [x]
WHERE [x].[Id] = 1
```

But with `ConfigureWarnings` enabled, it throws an exception:

```
Result Message: Warning as error exception for warning 'RelationalEventId.QueryClientEvaluationWarning': The LINQ expression 'SingleOrDefault()' could not be translated and will be evaluated locally. To suppress this Exception use the DbContextOptionsBuilder.ConfigureWarnings API. ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
```

This confuse me as I client evaluation should be performed only when the query cannot be translated, but the above result from SQL Profiler shows the SQL can be translated.
### Further technical details

EF Core version: 1.0.0
Operating system: 
Visual Studio version: VS 2015

**Comment by maumar** [comment] 2016-09-02 04:57
Duplicate of https://github.com/aspnet/EntityFramework/issues/5897 which is already fixed in current bits

**Closed** 2022-10-16 09:56 UTC
