### ISSUE TITLE
Add interceptors as generic types to the DbContext

### ISSUE THREAD

**Issue by lettuceDestroyer** [dotnet/efcore#33837] opened 2024-05-29 13:54 UTC
If you have an interceptor which injects other services, it does not appear to be possible to use the `DbContextOptionsBuilder` to add the interceptor.

Let's assume I have a `SaveChangesInterceptor` called `CustomSaveChangesInterceptor` which looks something like this:
```cs
 public class CustomSaveChangesInterceptor: SaveChangesInterceptor
 {
     private readonly IHttpContextAccessor _httpContextAccessor;
     private readonly IServiceProvider _serviceProvider;

     public CustomSaveChangesInterceptor(IHttpContextAccessor httpContextAccessor, IServiceProvider serviceProvider)
     {
         _httpContextAccessor = httpContextAccessor;
         _serviceProvider = serviceProvider;
     }
     ...
}
```

If I want to use this interceptor I have to create a custom `DbContext` class and add the interceptor in the `OnConfiguring` method like so:
```cs
public class CustomDbContext : DbContext
{
    ...
    private CustomSaveChangesInterceptor _customSaveChangesInterceptor;
    
    public CustomDbContext (DbContextOptions options, CustomSaveChangesInterceptor customSaveChangesInterceptor) : 
    base(options)
    {
        _customSaveChangesInterceptor = customSaveChangesInterceptor;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .AddInterceptors(_customSaveChangesInterceptor);

        base.OnConfiguring(optionsBuilder);
    }
    ...
}
```
In my opinion it would be cleaner to add the interceptors in the `Program.cs` like so:
```cs
builder.Services.AddDbContext<CustomDbContext>(
options =>
{
    ...
    options.AddInterceptor<SoftDeleteInterceptor>();
});
```

**Comment by WeihanLi** [comment] 2024-05-30 15:03
You could try to register the dbContext like follows:

```c#
builder.Services.AddDbContext<AppDbContext>((provider, options) =>
{
    options.AddInterceptors(provider.GetRequiredService<SoftDeleteInterceptor>());
    options.UseSqlServer(builder.Configuration.GetConnectionString("Default"));
});
```

**Comment by ajcvickers** [comment] 2024-06-15 14:33
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2024-07-01 14:02
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-07-01 14:02 UTC
Labels: type-enhancement, customer-reported
