### ISSUE TITLE
Contains in LINQ queries - invalid escape character

### ISSUE THREAD

**Issue by tmendes-dev** [dotnet/efcore#32798] opened 2024-01-12 15:15 UTC
Hi, i'm facing this issue reported on SO:

https://stackoverflow.com/questions/77807212/contains-in-linq-queries-invalid-escape-character

I'm not sure if it is related to the #32432 , because my ApiContext is in a NuGet package with the models that are shared among our services, it's already on .NET 8 with the same Microsoft.EntityFramework packages versions.

Maybe it's this: https://github.com/roji/efcore/blob/main/src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs#L297

**Comment by roji** [comment] 2024-01-12 16:35
@tmendes-dev can you please test with the latest EF [daily build](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md)? This would help us know whether it's #32432, which has already been fixed and backported.

**Comment by tmendes-dev** [comment] 2024-01-12 23:06
> @tmendes-dev can you please test with the latest EF [daily build](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md)? This would help us know whether it's #32432, which has already been fixed and backported.

@roji  after update to the newer version of daily build on both nugetpackage and api, the error still happen, package versions:
`   
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0-alpha.1.24061.3" />
`
`
   <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0-alpha.1.24061.3">
`
`
   <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.0-alpha.1.24061.3" />
`
`
   <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="9.0.0-alpha.1.24061.3" />
`
`
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0-alpha.1.24061.3" />
`

**Comment by maumar** [comment] 2024-01-16 19:41
I tried to reproduce the problem based on info provided in the so issue and what I tried works fine on current bits.

Here is the code I ended up with. 
@tmendes-dev please either provide full standalone repro or modify the code below so that it reproduces the issue.

```c#
    public void Repro32798()
    {
        using (var ctx = new MyContext32798())
        {
            ctx.Database.EnsureDeleted();
            ctx.Database.EnsureCreated();
        }

        using (var ctx = new MyContext32798())
        {
            var value = "%Foo[";
            var skip = 1;
            var take = 10;

            var query = ctx.Entities
                .Where(c => c.FieldB.ToLower().Contains(value) || c.FieldB.Contains(value) || c.FieldDocuments.Any(d => d.Contains(value)))
                .Include(c => c.Category).Include(c => c.Headquarters).Include(c => c.Addresses).ThenInclude(c => c.Address)
                .OrderBy(c => c.Id)
                .Skip(skip)
                .Take(take)
                .AsSplitQuery()
                .AsNoTracking()
                .ToList();
        }
    }

    public class MyEntity
    {
        public int Id { get; set; }
        public string Field { get; set; }
        public string FieldB { get; set; }
        public string[] FieldDocuments { get; set; }

        public Category Category { get; set; }
        public Headquarters Headquarters { get; set; }
        public List<AddressEntity> Addresses { get; set; }
    }

    public class Category
    {
        public int Id { get; set; }

        public int? MyEntityId { get; set; }
        public string Value { get; set; }
    }

    public class Headquarters
    {
        public int Id { get; set; }

        public int MyEntityId { get; set; }
        public string Value { get; set; }
    }

    public class AddressEntity
    {
        public int Id { get; set; }
        public AddressDetail Address { get; set; }
    }

    public class AddressDetail
    {
        public int Id { get; set; }
        public int AddressId { get; set; }
        public string Street { get; set; }
    }

    public class MyContext32798 : DbContext
    {
        public DbSet<MyEntity> Entities { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Headquarters> Headquarters { get; set; }
        public DbSet<AddressEntity> Addresses { get; set; }
        public DbSet<AddressDetail> AddressDetails { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Repro32798;Trusted_Connection=True;MultipleActiveResultSets=true");
        }
    }
```

What EF is doing here is, when pattern is a parameter we peek into it's values in runtime and escape wildcard chars and then add ESCAPE clause to LIKE. It would seem like the pattern value is somehow missing, which is weird because AFAICT we do hardcore it and use that constant anytime we pass escape string.

```
private const string LikeEscapeString = "\\";
```

The code snippet from SqlServerStringMethodTranslator shouldn't be a problem. There we just compare pattern to empty string. Note the signature of Like method:

```c#
LikeExpression Like(SqlExpression match, SqlExpression pattern, SqlExpression? escapeChar = null);
```

escape char is third argument, in the snippet we only use 2.

**Comment by tmendes-dev** [comment] 2024-01-17 16:57
@maumar sorry for the delay in my response, I had some problems isolating the problem, but I finally managed it, it seems that my map methods and extensions that worked before the update to dotnet8 contained some broken form, here is the code:
MyEntityController.cs:
```
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApi.Context;


namespace WebApi.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class MyEntityController : ControllerBase
    {
    

        private readonly ILogger<MyEntityController> _logger;
        private readonly ApiContext _context;
        public MyEntityController(ILogger<MyEntityController> logger, ApiContext context)
        {
            _logger = logger;
            _context = context;
        }

        [HttpGet(Name = "Get")]
        public IActionResult Get()
        {
            try
            {
                _context.Database.EnsureDeleted();
                _context.Database.EnsureCreated();
                _context.Entities.Add(new MyEntity() { Field = "TesteFoo",FieldB="FOOOOO"});
                _context.SaveChanges();
                _context.Database.ExecuteSql($"ALTER DATABASE MyContext32798 SET COMPATIBILITY_LEVEL=140");

                var value = "Foo";
                var skip = 1;
                var take = 10;
                var query = _context.Entities.AsQueryable();
               
                var result = query
                    .Where(c => c.Field.ToLower().Contains(value) || c.FieldB.Contains(value))
                    .OrderBy(c => c.Id)
                    .Skip(skip)
                    .Take(take)
                    .AsSplitQuery()
                    .AsNoTracking()
                    .ToQueryString();

                return Ok(result);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"An error ocurred.Message: {ex.Message}");
                return BadRequest(ex.Message);
            }
        }
    }
}

```
Program.cs

```
 
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using WebApi.Context;

namespace WebApi
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);

            // Add services to the container.

            builder.Services.AddControllers();
            // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
            builder.Services.AddEndpointsApiExplorer();
            builder.Services.AddSwaggerGen();
            builder.Services.AddDbContext<ApiContext>(options =>
                options.UseSqlServer(builder.Configuration.GetConnectionString("ApiContext"),
                            c =>
                                c.EnableRetryOnFailure(
                                        maxRetryCount: 3,
                                        maxRetryDelay: TimeSpan.FromSeconds(2),
                                        errorNumbersToAdd: null))
                        .EnableSensitiveDataLogging()
                        .EnableDetailedErrors()
                        .ConfigureWarnings(c => c.Log((RelationalEventId.CommandExecuting, LogLevel.Debug))),
                ServiceLifetime.Transient, ServiceLifetime.Singleton);
            var app = builder.Build();

            // Configure the HTTP request pipeline.
            if (app.Environment.IsDevelopment())
            {
                app.UseSwagger();
                app.UseSwaggerUI();
            }

            app.UseHttpsRedirection();

            app.UseAuthorization();


            app.MapControllers();

            app.Run();
        }
    }
}
```
ApiContext.cs
```
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.Extensions.Logging.Abstractions;
using System.Globalization;
using System.Text.RegularExpressions;
using System.Text;

namespace WebApi.Context
{
    public class ApiContext : DbContext
    {
        private readonly NullLogger<ApiContext> _logger;

        public DbSet<MyEntity> Entities { get; set; }



        public ApiContext(DbContextOptions<ApiContext> options, IHostEnvironment env) : base(options)
        {
            _logger = NullLogger<ApiContext>.Instance;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            MyEntityMap.Map(modelBuilder);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
        
        }
    }
    public class MyEntity
    {
        public int Id { get; set; }
        public string Field { get; set; }
        public string FieldB { get; set; }
    }
    public static class MyEntityMap
    {
        public static void Map(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MyEntity>(builder =>
            {
                builder.Property(p => p.Field).DefaultString(150, true, TextType.NoSpecialCharsUpper);
                builder.Property(p => p.FieldB).DefaultString(150, true, TextType.NoSpecialCharsUpper);
            });
        }

        internal static PropertyBuilder<string> DefaultString(
        this PropertyBuilder<string> builder,
        int maxLength = 256,
        bool required = false,
        TextType type = TextType.None)
        {
            return builder
                .HasMaxLength(maxLength)
                .HasConversion(
                    c => HandleTo(c, maxLength, type, required),
                    c => c)
                .IsRequired(required);
        }
        private static string HandleTo(string s, int maxLength, TextType type, bool required)
        {
            if (string.IsNullOrEmpty(s)) return required ? string.Empty : null;

            switch (type)
            {

                case TextType.NoSpecialCharsUpper:
                    s = s.RemoveSpecialCharacters().ToUpperInvariant();
                    break;
                case TextType.None:
                default:
                    break;
            }

            if (s.Length < maxLength) maxLength = s.Length;

            s = s.Substring(0, maxLength).Trim();

            return s;
        }
        public static string RemoveDiacritics(this string stIn)
        {
            if (stIn is null) return "";

            var stFormD = stIn.Normalize(NormalizationForm.FormD);
            var sb = new StringBuilder();

            foreach (var t in stFormD)
            {
                var uc = CharUnicodeInfo.GetUnicodeCategory(t);
                if (uc != UnicodeCategory.NonSpacingMark)
                {
                    sb.Append(t);
                }
            }

            return (sb.ToString().Normalize(NormalizationForm.FormC));
        }
        public static string RemoveSpecialCharacters(this string input)
        {
            if (input is null) return null;

            input = RemoveDiacritics(input);

            input = input.Replace('-', ' ')
                         .Replace('º', ' ')
                         .Replace(',', ' ')
                         .Replace('ª', ' ')
                         .Replace('.', ' ');

            input = Regex.Replace(input, @"[^\p{L}\p{Nd}.º \u00BA]+", " ");

            return input.Trim();
        }

        internal enum TextType
        {
            None,
            NoSpecialCharsUpper,
        }
    }
}

```
Generated SQL:
```
DECLARE @__value_0_rewritten nvarchar(150) = N'FOO';
DECLARE @__value_0_rewritten_1 nvarchar(150) = N'FOO';
DECLARE @__p_1 int = 1;
DECLARE @__p_2 int = 10;

SELECT [e].[Id], [e].[Field], [e].[FieldB]
FROM [Entities] AS [e]
WHERE LOWER([e].[Field]) LIKE @__value_0_rewritten ESCAPE N'' OR [e].[FieldB] LIKE @__value_0_rewritten_1 ESCAPE N''
ORDER BY [e].[Id]
OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY
```

Full code snippet is in my repo : [https://github.com/tmendes-dev/efcore-issue-32798](url)

**Comment by maumar** [comment] 2024-01-18 09:21
@tmendes-dev thanks, I'm able to reproduce this now. 

What's happening is that custom type mapping, which does a bunch of processing including removal of special characters gets applied on the ESCAPE char string and wipes out what we put there. I'm guessing that in previous version we were not escaping parameters (because we didn't have capability to peek into parameter values), so the code worked.

**Comment by tmendes-dev** [comment] 2024-01-18 11:33
> @tmendes-dev thanks, I'm able to reproduce this now.
> 
> What's happening is that custom type mapping, which does a bunch of processing including removal of special characters gets applied on the ESCAPE char string and wipes out what we put there. I'm guessing that in previous version we were not escaping parameters (because we didn't have capability to peek into parameter values), so the code worked.

That's it, i changed the Regex to: ``` @"[^\p{L}\p{Nd}.º \u00BA/\\]+" ``` to allow "\" and "%" and it worked fine. 

Thanks for the patiencie and time spent.

**Comment by ajcvickers** [comment] 2024-01-18 11:35
@maumar Is this a regression?

**Comment by roji** [comment] 2024-01-18 12:03
@ajcvickers if I understand correctly, the user here set up special logic to strip out special chars, and since 8.0 out improved handling for parameters adds an ESCAPE clause to LIKE which contains a backslash.. I think once users go into arbitrarily rewriting string values via special type mappings, all bets are off and it's on them to ensure compatibility...

**Comment by tmendes-dev** [comment] 2024-01-18 12:11
> @ajcvickers if I understand correctly, the user here set up special logic to strip out special chars, and since 8.0 out improved handling for parameters adds an ESCAPE clause to LIKE which contains a backslash.. I think once users go into arbitrarily rewriting string values via special type mappings, all bets are off and it's on them to ensure compatibility...

if that's the case, i assume that the microsoft docs should have a disclaimer about this and its possibles outcomes

**Comment by roji** [comment] 2024-01-18 12:45
> if that's the case, i assume that the microsoft docs should have a disclaimer about this and its possibles outcomes

This is akin to someone setting up an interceptor to rewrite the SQL that EF produces, and ending up interfering with the proper functioning of the query; once you do these kinds of things, you really are on your own. I don't think this is something that we should document, nor would I think it would help anyone catch any sort of error up-front.

**Comment by penihel** [comment] 2024-01-18 20:49
I have this problem.

look my c#
`AddCriteria(q => q.Pessoa.NomeCompleto.Contains(Term) ||
						q.Pessoa.NumeroDocumentoIdentificador.StartsWith(Term));`


Look the SQL,

Has created 2 parameters, but with the same value. it's wrong
`DECLARE @__Term_0_rewritten nvarchar(300) = N'D%';`
`DECLARE @__Term_0_rewritten_1 nvarchar(100) = N'D%';`


look the where clause
`WHERE [p].[Ativo] = CAST(1 AS bit) AND ([p].[NomeCompleto] LIKE @__Term_0_rewritten ESCAPE N'\' OR [p].[NumeroDocumentoIdentificador] LIKE @__Term_0_rewritten_1 ESCAPE N'\')`


was expected the parameters values like this
Has created 2 parameters, but with the same value. it's wrong
`DECLARE @__Term_0_rewritten nvarchar(300) = N'%D%';`
`DECLARE @__Term_0_rewritten_1 nvarchar(100) = N'D%';`

in another words.

The value of **@__Term_0_rewritten** shold be "LIKE" with **N'%D%';`**


I think this is problem is related with this issue

and its the same #32432 32432

**Comment by maumar** [comment] 2024-01-19 00:58
@penihel this looks like exact duplicate of #32432 - can you try running your code on latest daily build?

**Comment by penihel** [comment] 2024-01-23 14:51
i think its ok , but when [8.0.2](https://github.com/dotnet/efcore/milestone/186) will be released?

**Comment by ajcvickers** [comment] 2024-01-25 18:02
@penihel Scheduled for second Tuesday in Feburary.

**Closed by ajcvickers** 2024-01-25 18:02 UTC
Labels: type-bug, customer-reported, area-query
