### ISSUE TITLE
Incorrect Entry when catching DBUpdateException

### ISSUE THREAD

**Issue by brandonseydel** [dotnet/efcore#26530] opened 2021-11-03 18:52 UTC
## Issue

The entry coming back from DBUpdateException is not the correct entry.

![image](https://user-images.githubusercontent.com/5033585/140174102-a26b8669-ead1-4275-806b-f82e8f2d9b95.png)

The error is for truncation of a column which is true but only on the last entry in the AddRange call that is being made.  This entry is the first entry which is actually not an issue.  In fact it has no value for the one stating it will be truncated...

### Include your code

```C#
private async Task<(int RecordsSaved, IEnumerable<DbUpdateException> Errors)> SaveChangesPartialAsync(IEnumerable<DbUpdateException> errors = null, CancellationToken cancellationToken = default)
		{
			var hasError = false;
			errors ??= new HashSet<DbUpdateException>();
			try
			{
				var recordsSaved = await this.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
				return (recordsSaved, errors);
			}
			// remove any entries that may have caused an error
			catch (DbUpdateException ex)
			{
				ex.Entries.ToList().ForEach(y =>
				{
					y.State = EntityState.Detached;
					y.Collections.ToList().ForEach(collection =>
					{
						collection.EntityEntry.State = EntityState.Detached;
						foreach (var entity in collection.CurrentValue)
						{
							var entry = this.Entry(entity);
							if (entry != null) {
							entry.State = EntityState.Detached;
							}

						}
					});
					y.References.ToList().ForEach(x => { x.EntityEntry.State = EntityState.Detached; });
				});
				errors = Enumerable.Append(errors, ex).ToList();
				hasError = true;
			}
			return hasError ? await SaveChangesPartialAsync(errors, cancellationToken).ConfigureAwait(false) : (0, errors);
		}
```

```
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.<ConsumeAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__29.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__29.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__100.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__104.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__56.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__56.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at RSM.ClientMdm.DataAccess.MdmContext.<SaveChangesPartialAsync>d__482.MoveNext() in C:\Users\E060589\source\repos\RSM.ClientMDM\Server\RSM.ClientMdm.DataAccess\MDMContext.cs:line 314
```

### Include provider and version information

EF Core version: Core 5.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET CORE 3.1
Operating system: Window 10
IDE: Visual Studio 2022

**Comment by brandonseydel** [comment] 2021-11-15 18:20
The latter. I will make a repo soon

**Comment by ajcvickers** [comment] 2021-11-28 14:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by mikeleigh1010** [comment] 2022-09-22 15:36
> @brandonseydel Is the issue here that `Entries` contains all saved entries, including those that did not generate any error? Or that `Entries` contains only one entry, but it is not the one that caused the error? If the latter, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

I'm seeing the former behaviour in some cases. I've added a unique index for a column on a table and I've got some integration tests, mostly this will return one item in the entries (the one the unique key index is referring to) which is great, I remove and retry. 

However, I am seeing in cases where say, I am inserting two records which already match items in the db (so expecting an exception) and two perfectly fine items, I am seeing all of these returned in the exception. If I change this to two invalid and one happy day then I'm back to one item in the entries collection.

**Comment by roji** [comment] 2022-09-22 16:32
@mikeleigh1010 please open a new issue with a runnable code sample that shows the problematic behavior.

**Comment by mikeleigh1010** [comment] 2022-09-23 14:29
Below is some code I've put together to show what is happening, I'm seeming to observe that 3 items (one duplicate and two happy day) can fail and entries will return only the item failed but > 3 in an addrange seems to be where the exception entries includes all items attempted.

`


    [Index(nameof(Name), IsUnique = true)]
    public class Cat
    {
        public int Id { get; init; }
        public string Name { get; init; } = string.Empty;
        public int Age { get; init; }
    }
    
    public class AppDbContext : DbContext
    {
        public DbSet<Cat> Cats { get; set; }

        public AppDbContext(DbContextOptions<PspDbContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        }
    }

    public class Processor
    {

        private IDbContextFactory<AppDbContext> _contextFactory;
        public Processor(IDbContextFactory<AppDbContext> contextFactory)
        {
            _contextFactory = contextFactory;
        }

        public async Task ProcessCats()
        {
            await using var context = await _contextFactory.CreateDbContextAsync();
            var cat = new Cat
            {
                Name = "garfield",
                Age = 10
            };

            context.Cats.Add(cat);
            await context.SaveChangesAsync();
            
            try
            {
                context.Cats.AddRange(new List<Cat>
                {
                    cat,
                    new()
                    {
                        Name = "topcat",
                        Age = 3
                    },
                    new()
                    {
                        Name = "felix",
                        Age = 2
                    }
                });
                await context.SaveChangesAsync();
            }
            catch (DbUpdateException dbEx)
            {
                var entries = dbEx.Entries;
                // entries collection will only contain duplicate cat of "garfield"
            }
            
            try
            {
                context.Cats.AddRange(new List<Cat>
                {
                    cat,
                    new()
                    {
                        Name = "topcat",
                        Age = 3
                    },
                    new()
                    {
                        Name = "felix",
                        Age = 2
                    },
                    new()
                    {
                        Name = "lucky",
                        Age = 55
                    }
                });
                await context.SaveChangesAsync();
            }
            catch (DbUpdateException dbEx)
            {
                var entries = dbEx.Entries;
                // entries collection will contain all cats attempted to be inserted
            }
        }
    }

`

**Comment by mikeleigh1010** [comment] 2022-09-23 15:16
Apologies, did not read message fully. Will open as a new issue.

**Closed** 2022-10-16 20:12 UTC
Labels: closed-could-not-reproduce, customer-reported

**Comment by jerviscui** [comment] 2023-09-13 05:57
Any progress on this issue?

**Comment by roji** [comment] 2023-09-13 09:09
@jerviscui this issue is closed, so there will be no progress on it - as is #39190 (which you may want to take a look at). If you're still encountering a problem, please open a new issue with a minimal, runnable code sample.
