### ISSUE TITLE
EF Core 7 Scaffold-DbContext pluralizer incorrectly removes .ToTable() in many-to-many relationship

### ISSUE THREAD

**Issue by jornhd** [dotnet/efcore#29977] opened 2023-01-04 14:16 UTC
We use Scaffold-DbContext to generate entity classes and db context from a legacy SQLServer database.
Several of the tables in the database ends with a plural 's', including the table "CarDrivers" containing a many-to-many relationship between tables "Car" and "Driver".
The pluralizer removes this ending 's' from table names when creating entity classes, and that's fine.
But when generating the many-to-many relationship, this now causes an error.
In EF Core 6, .ToTable("CarDrivers") was added that made this work, but now in EF Core 7 this ToTable is removed causing SQLException Invalid object name 'CarDriver'

**The many-to-many relation generated with EF Core 6:**
```
  modelBuilder.Entity<Car>(entity =>
  {
      _(snip)_

      entity.HasMany(d => d.Drivers)
          .WithMany(p => p.Cars)
          .UsingEntity<Dictionary<string, object>>(
              "CarDriver",
              l => l.HasOne<Driver>().WithMany().HasForeignKey("DriverId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_CarDrivers_Driver"),
              r => r.HasOne<Car>().WithMany().HasForeignKey("CarId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_CarDrivers_Car"),
              j =>
              {
                  j.HasKey("CarId", "DriverId");
                  j.ToTable("CarDrivers");
              });
    });
```

**The many-to-many relation generated with EF Core 7:**
```
  modelBuilder.Entity<Car>(entity =>
  {
      _(snip)_

      entity.HasMany(d => d.Drivers).WithMany(p => p.Cars)
        .UsingEntity<Dictionary<string, object>>(
            "CalendarResource",
            r => r.HasOne<Driver>().WithMany()
                .HasForeignKey("DriverId")
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CarDrivers_Driver"),
            l => l.HasOne<Car>().WithMany()
                .HasForeignKey("CarId")
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CarDrivers_Car"),
            j =>
            {
                j.HasKey("CarId", "DriverId");
            });
    });
```

**Note** the` j.ToTable("CarDrivers");` is missing in the EF Core 7 code.

By adding -NoPluralize in the Scaffold-DbContext command line, the generated code is correct, as the joinEntityName is set to "CarDrivers" instead of "CarDriver", but then many of the class names and collection properties changes, causing lots of errors in the code base, so this is not a desirable workaround.

**Comment by ajcvickers** [comment] 2023-01-04 14:26
Duplicate of #29634.

**Comment by jornhd** [comment] 2023-01-04 14:50
Actually it was closer to #29544 but glad to see it's already fixed. :)

**Closed** 2023-01-11 20:09 UTC
Labels: closed-duplicate, customer-reported
