### ISSUE TITLE
Mapping nullable DB conlumns to non-nullable Entity properties

### ISSUE THREAD

**Issue by xeonix** [dotnet/efcore#32718] opened 2024-01-04 10:42 UTC
Hello Guys!
I have a legacy SQL Server DB with `bit null` column.
However, `null` for that column is always treated as `false`, so why not to map it to non-nullable entity property and apply a converter?
Let's say we have a table:
```SQL
create table Test(Id int primary key identity, IsEnabled bit);
```
The entity with it's configuration and `NullToFalseValueConverter` look like this:
```C#
public class Test
{
  public int Id { get; init; }
  public required bool IsEnabled { get; init; }
}

class NullToFalseValueConverter : ValueConverter<bool, bool?>
{
    public NullToFalseValueConverter() : base(e => e ? true : null, e => e == true) { }
    public override bool ConvertsNulls => true;
}

class TestEntityConfiguration : IEntityTypeConfiguration<Test>
{
    public void Configure(EntityTypeBuilder<Test> builder)
    {
        builder.ToTable("Test");
        builder.HasKey(e => e.Id);

        builder.Property(e => e.IsEnabled).HasConversion<NullToFalseValueConverter>();
    }
}
```
However, when I query `Test` entities and there are `null`s in `IsEnabled` column EF Core fails with:
```
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_Boolean()
   at Microsoft.Data.SqlClient.SqlDataReader.GetBoolean(Int32 i)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadBool(DbDataReader reader, Int32 ordinal, ReaderColumn column)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadRow()
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.InitializeAsync(DbDataReader reader, IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.InitializeAsync(IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.InitializeAsync(IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.<PopulateSplitIncludeCollectionAsync>g__InitializeReaderAsync|27_0[TIncludingEntity,TIncludedEntity](RelationalQueryContext queryContext, RelationalCommandCache relationalCommandCache, IReadOnlyList`1 readerColumns, Boolean detailedErrorsEnabled, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass30_0`2.<<ExecuteAsync>b__0>d.MoveNext()
```
Even though according to `NullToFalseValueConverter` the actual provider type has to be `bool?` instead of `bool`, EF Core still tries to read it as non-nullable and fails.
I played around with entity configuration to investigate what can I do to make it work:
```C#
class TestEntityConfiguration : IEntityTypeConfiguration<Test>
{
    public void Configure(EntityTypeBuilder<Test> builder)
    {
        builder.ToTable("Test");
        builder.HasKey(e => e.Id);

        var propertyBuilder = builder.Property(e => e.IsEnabled).HasConversion<NullToFalseValueConverter>();

        //Returns null even after NullToFalseValueConverter is applied while I expected it to be 'bool?',
        //because 'NullToFalseValueConverter.ProviderClrType' is actually a 'bool?'.
        var providerClrType = propertyBuilder.Metadata.GetProviderClrType();

        //Tried to set ProviderClrType explicitly, but that didn't work, EF Core still fails with the same SqlNullValueException when reading nulls:
        propertyBuilder.Metadata.SetProviderClrType(typeof(Nullable<>).MakeGenericType(propertyBuilder.Metadata.ClrType));
    }
}
```
Moving forward, considering bare `SetProviderClrType` didn't work, I added `propertyBuilder.Metadata.IsNullable = true;`, which has failed with:
```
System.InvalidOperationException: 'The property 'Test.IsEnabled' cannot be marked as nullable/optional because the type of the property is 'bool' which is not a nullable type. Any property can be marked as non-nullable/required, but only properties of nullable types can be marked as nullable/optional.'
```
Looking at the code for both EF Core 7 and EF Core 8 I noticed, that when setting `Property.IsNullable`, `SetIsNullable` method is called:
https://github.com/dotnet/efcore/blob/release/8.0/src/EFCore/Metadata/Internal/Property.cs#L182
https://github.com/dotnet/efcore/blob/release/7.0/src/EFCore/Metadata/Internal/Property.cs#L155
This method validates whether `Property.ClrType` is a nullable type and does not consider `GetProviderClrType()` at all - that's why `SetProviderClrType` didn't help.
In order to bypass that validation I had to create a dirty workaround, that finally worked for me:
```C#
public static class RelationalPropertyBuilderExtensions
{
    /// <summary>
    /// Overrides the actual type of the property to be nullable.
    /// There are cases when a new column was added as nullable by mistake - i.e. having <c>bit</c> column instead of <c>bit not null</c>, but treating <c>null</c> as <c>false</c>.
    /// In order to fix that at EF Core model level, we use <c>NullTo...ValueConverter</c>.
    /// However, having <c>NullTo...ValueConverter</c> applied to a property, even though <see cref="Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter.ProviderClrType" />
    /// clearly specifies what the actual provider property type is, EF Core 7 still tries to read it as non-nullable and fails when there are <c>null</c>s stored in DB.
    /// </summary>
    /// <param name="propertyBuilder">A property builder.</param>
    /// <returns>Updated property builder.</returns>
    public static PropertyBuilder IsNullable(this PropertyBuilder propertyBuilder)
    {
        propertyBuilder.Metadata.GetType().GetField("_isNullable", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic)?.
            SetValue(propertyBuilder.Metadata, true);

        return propertyBuilder;
    }

    /// <summary>
    /// Overrides the actual type of the property to be nullable.
    /// There are cases when a new column was added as nullable by mistake - i.e. having <c>bit</c> column instead of <c>bit not null</c>, but treating <c>null</c> as <c>false</c>.
    /// In order to fix that at EF Core model level, we use <c>NullTo...ValueConverter</c>.
    /// However, having <c>NullTo...ValueConverter</c> applied to a property, even though <see cref="Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter.ProviderClrType" />
    /// clearly specifies what the actual provider property type is, EF Core 7 still tries to read it as non-nullable and fails when there are <c>null</c>s stored in DB.
    /// </summary>
    /// <typeparam name="TProperty">Original, non-nullable property type.</typeparam>
    /// <param name="propertyBuilder">A property builder.</param>
    /// <returns>Updated property builder.</returns>
    public static PropertyBuilder<TProperty> IsNullable<TProperty>(this PropertyBuilder<TProperty> propertyBuilder) =>
        (PropertyBuilder<TProperty>)IsNullable((PropertyBuilder)propertyBuilder);
}

class TestEntityConfiguration : IEntityTypeConfiguration<Test>
{
    public void Configure(EntityTypeBuilder<Test> builder)
    {
        builder.ToTable("Test");
        builder.HasKey(e => e.Id);

        builder.Property(e => e.IsEnabled).HasConversion<NullToFalseValueConverter>().IsNullable();
    }
}
```
By setting `Property._isNullable` field directly using reflection, EF Core 7 and EF Core 8 were finally managed to read `null`s, use `NullToFalseValueConverter` and assign `false` to non-nullable entity property `Test.IsEnabled`. Worked like a charm!

So I'm wondering, if `Property.SetIsNullable` should be updated to check `Property.GetProviderClrType()` first, and if it's null - fallback to `Property.ClrType`?
And probably, `Property.SetProviderClrType()` should be called as part of `HasConversion` implementation.

EF Core version: 7, 8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0, .NET 8.0
Operating system: Windows, Linux
IDE: Visual Studio 2022 17.8.3

**Comment by ajcvickers** [comment] 2024-01-04 10:52
Duplicate of #24685

**Closed** 2024-01-10 03:07 UTC
Labels: closed-duplicate, customer-reported
