### ISSUE TITLE
LINQ Query and ViewModel related issue

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#6481] opened 2016-09-07 01:29 UTC
_From @saf-itpro on August 31, 2016 17:6_

In my ASP.NET MVC Core app, I get following error when the following LINQ Query is sent to ViewModel:

**Error**: InvalidOperationException: Operation is not valid due to the current state of the object.

**View Model**:

``` C#
    public class StatesViewModel
    {
        public string StateCode { get; set; }
    }
```

**LINQ Queries**:

``` C#
    var QryStates = from s in _context.States
                 where s.StateAbrv != null && s.StateAbrv != string.Empty
                 select new { s.StateAbrv };

    var QryCustCount = (from c in ontext.Customers
            join qs in QryStates on c.StateAbrv equals qs.StateAbrv 
            group qs by new { qs.StateAbrv } into grpStateAbrv
            select new StatesViewModel{ StateCode = grpStateAbrv.Key.Statecd }).ToList();
```

**NOTE**: 
1. Error occurs on `select new StatesViewModel{ StateCode = grpStateAbrv.Key.Statecd }).ToList();` line of the second query. It does not occur if I replace this part with just `select new { StateCode = grpStateAbrv.Key.Statecd };` But then I won't be able to send the query result to the View Model that is used in the View I'm using for display the second query result.
2. I've tested and verified that the first query `QryStates` itself does return correct data.

_Copied from original issue: aspnet/Mvc#5206_

**Comment by divega** [comment] 2016-09-07 01:29
_From @rynowak on August 31, 2016 18:43_

Is the error coming from EntityFramework? Do you have a complete callstack for the exception

**Comment by divega** [comment] 2016-09-07 01:29
_From @saf-itpro on September 6, 2016 20:38_

@rynowak Yes, I'm using the EF and below is the detailed error:

**complete callstack for the exception**:

``` 
Message=Operation is not valid due to the current state of the object.
  Source=System.Linq.Expressions
  StackTrace:
       at System.Linq.Expressions.MethodCallExpression2.GetArgument(Int32 index)
       at System.Dynamic.Utils.ListArgumentProvider.get_Item(Int32 index)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.QueryFlattener.Flatten(MethodCallExpression methodCallExpression)
       at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index, Action baseVisitAction, MethodInfo operatorToFlatten, Boolean outerJoin)
       at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index)
       at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
       at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression node)
       at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
       at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.CompileMainFromClauseExpression(MainFromClause mainFromClause, QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
       at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by divega** [comment] 2016-09-07 01:29
_From @rynowak on September 6, 2016 20:56_

/cc @divega @rowanmiller @anpete

**Comment by divega** [comment] 2016-09-07 18:40
@saf-itpro could you provide a complete repro including the model?

**Comment by smitpatel** [comment] 2016-09-21 00:33
Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed by smitpatel** 2016-09-21 00:33 UTC
Labels: closed-could-not-reproduce
