### ISSUE TITLE
ValueObject is null if all properties inside are null

### ISSUE THREAD

**Issue by skhoma** [dotnet/efcore#22146] opened 2020-08-20 17:35 UTC
Application was migrated from EF Core 2.2 to EF Core 3.1
We have ValueObject with nullable properties inside (they are lazy-loaded).
The issue happens when all properties are NULL and entity is fetched from DB.
In EF Core 2.2: ValueObject was initialized, but properties were NULL.
In EF Core 3.1: ValueObject is not initialized. When at least one property is not NULL it is initialized.

A ValueObject:

        public class Payer : ValueObject
        {
                  private Company _company;
                  private Account _account;
                  private Customer _customer;

                  public Payer()
                  {
                  }

                  public virtual Account Account => _account;
                  public virtual Customer Customer => _customer;
                  public virtual Company Company => _company;
        }

How it is used:

          public abstract class InvoiceBase
          {
                    protected InvoiceBase()
                    {
                    }
            
                    public virtual Payer Payer { get; protected set; }
          }

          public class Invoice : InvoiceBase 
          {
                  protected Invoice()
                  {
                  }
          }

A model configuration:

          public class InvoiceConfiguration : IEntityTypeConfiguration<Invoice>, IEntityTypeConfiguration
          {
                    public void Configure(EntityTypeBuilder<Invoice> builder)
                    {
                              builder.OwnsOne(invoice => invoice.Payer, b =>
                              {
                                        b.HasOne(e => e.Customer).WithMany().OnDelete(DeleteBehavior.Restrict);
                                        b.HasOne(e => e.Account).WithMany().OnDelete(DeleteBehavior.Restrict);
                                        b.HasOne(e => e.Company).WithMany().OnDelete(DeleteBehavior.Restrict);
                              });
                    }
          }

EF Core version: 3.1.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.1

**Comment by smitpatel** [comment] 2020-08-20 17:42
Duplicate of #12100

See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#de

**Comment by skhoma** [comment] 2020-08-20 17:47
Have checked the link. The issue is NOT the same.

**Comment by smitpatel** [comment] 2020-08-20 18:14
In 3.1 all dependents (in this case your valueobject), is considered optional. So if all the properties are null then the dependent does not exist and value object is not initialized. If you want to initialize value object even when there is no data (all properties are null) then you need to configure it as required dependent.

**Comment by skhoma** [comment] 2020-08-20 18:20
Thank you

**Closed** 2022-10-16 18:37 UTC
Labels: closed-duplicate, customer-reported
