### ISSUE TITLE
NullReferenceException when filtering by null navigation property

### ISSUE THREAD

**Issue by francescomazzurco** [dotnet/efcore#13141] opened 2018-08-28 15:38 UTC
Hello all,

I have a really basic one-to-many relationship model:

```c#
public class Parent
{
    public int ParentId { get; set; }
    public string Name { get; set; }
    public List<Child> Children { get; set; }
}

public class Child
{
    public int ChildId { get; set; }
    public int ParentId { get; set; }
    public Parent Parent { get; set; }
    public string Name { get; set; }
}

public class Context : DbContext
{
    public DbSet<Parent> Parents { get; set; }
    public DbSet<Child> Children { get; set; }
}
```

When I query a `Parent` which results in null, and then try to query a `Child` having such parent, I get a `NullReferenceException`. For instance:

```c#
var parent = context.Parents
    .Where(p => p.Name == "Some nonexistent name")
    .FirstOrDefault(); // will be null

var child = context.Children
    .Where(c => c.Parent == parent)
    .FirstOrDefault(); // NullReferenceException
```

However, this query does not throw:
```c#
var child = context.Children
    .Where(c => c.Parent == null)
    .FirstOrDefault(); // will be null, but no exception
```

Finally, I was forced to find this workaround:

```c#
var child = context.Children
     .Where(c => c.Parent == (parent ?? null))
     .FirstOrDefault(); // will be null, but no exception
```

Is this the expected behaviour?

This is the Stack trace of the `NullReferenceException` I get in the first scenario:
```
at lambda_method(Closure , Parent )
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrPropertyGetter`2.GetClrValue(Object instance)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedPropertyRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at ConsoleApp1.Program.Main(String[] args) in D:\VS\ConsoleApp1\Program.cs:line 20
```

### Further technical details
EF Core version: 2.1.2 running on .NET Framework 4.7
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.1

Thanks

**Comment by smitpatel** [comment] 2018-08-28 19:06
Not a regression.

**Comment by cello99d** [comment] 2018-08-28 22:00
Duplicate of #12062?

**Comment by francescomazzurco** [comment] 2018-08-29 06:52
Yes it is indeed the same bug of [#12062](https://github.com/aspnet/EntityFrameworkCore/issues/12062). My apologies for not spotting it before posting the issue.

 Anyhow, I still think it is worth noticing that the exception is thrown only when comparing the navigation property to an object being null, and not when comparing it to explicit `null`.

**Comment by Wain123** [comment] 2018-10-10 11:30
@francescomazzurco Your workaround works because it causes the query to be client-evaluated instead of being translated to SQL. See issue #13568

**Closed** 2022-10-16 13:27 UTC
Labels: customer-reported
