### ISSUE TITLE
EnumToStringConverter fails to initialize when updating database

### ISSUE THREAD

**Issue by edwiles** [dotnet/efcore#11113] opened 2018-03-01 10:41 UTC
I'm trying to use enums in my EF Core model, using EnumToStringConverter so that they are stored as strings in the database rather than ints. I get the following when running "dotnet ef database update". Looking like the migrations code generator needs to generate an enum property rather than an int?

(While I'm here, is there a way to use converter with nullable enums too? e.g. public TestEnum? MyTestEnum; Out of the box it seems I can't.)

```
Exception message: System.ArgumentException: Converter for model type 'TestEnum' cannot be used for 'Domain.Model.Project.TestEnum' because its type is 'int'.
Stack trace: System.ArgumentException: Converter for model type 'TestEnum' cannot be used for 'Domain.Model.Project.TestEnum' because its type is 'int'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalPropertyBuilder.HasConversion(ValueConverter valueConverter, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder`1.HasConversion(ValueConverter converter)
   at Database.Migrations.InitialCreate.<>c.<BuildTargetModel>b__2_3(EntityTypeBuilder b) in C:\Users\wile\source\repos\VST\Source\Infrastructure\Database\Migrations\20180301102746_InitialCreate.Designer.cs:line 97
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(String name, Action`1 buildAction)
   at Database.Migrations.InitialCreate.BuildTargetModel(ModelBuilder modelBuilder) in C:\Users\wile\source\repos\VST\Source\Infrastructure\Database\Migrations\20180301102746_InitialCreate.Designer.cs:line 87
   at Microsoft.EntityFrameworkCore.Migrations.Migration.<.ctor>b__4_0()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Steps to reproduce
1. Create any enumeration:
```
    public enum TestEnum
    {
        EnumValue1,
        EnumValue2
    }
```

2. Use in an entity:
```
   public TestEnum MyTestEnum { get; set; }
```

3. Add a property configuration (and apply this during OnModelCreating as usual):
```
            builder.Property(o => o.MyTestEnum)
                .IsRequired()
                .HasConversion(new EnumToStringConverter<TestEnum>());
```

4. Drop and recreate the database via migrations:
```
dotnet ef database drop -f
dotnet ef migrations remove
dotnet ef migrations add InitialCreate
dotnet ef database update
```

Also here is an extract from my csproj:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.1.0-preview1-final" />
  </ItemGroup>
```

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Professional
IDE: Visual Studio 2017 15.5.4

**Comment by ajcvickers** [comment] 2018-03-01 17:28
@edwiles The migrations issue looks like a duplicate of #10748, which is already fixed in the current dev branch. Could you try with our nightly build feed, as listed here: https://github.com/aspnet/EntityFrameworkCore

Also, unless you are doing something special there is no need to use EnumToStringConverter explicitly. Instead you should just need:
```C#
builder.Property(o => o.MyTestEnum)
    .IsRequired()
    .HasConversion<string>();
```
See the docs here which cover that case specifically: https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions. I think this should also work with Migrations in preview1, but I'm not 100% sure.

With regard to converters for nullable types, first it should work--what issue are you seeing? Second, usually it's fine to just create a converter for the non-nullable type and use it everywhere, even with nullable types. This is because nulls are handled outside of conversion--again, see the docs.

**Closed** 2022-10-16 12:11 UTC
Labels: closed-duplicate
