### ISSUE TITLE
Data type issue on Enumerable.Sum(TSource) method

### ISSUE THREAD

**Issue by saf-itpro** [dotnet/efcore#8324] opened 2017-04-28 19:07 UTC
**Environment**: EF-Core 1.1, VS2015, Windows 10 (updated from Windows 7)

I'm getting the following error on LINQ Query shown below:
`Unable to cast object of type 'System.Double' to type 'System.Nullable`1[System.Single]'`

**LINQ**:
var `totalFreight =
    (from cust in db.Customers
       join ord in db.Orders on cust.ordID equals ord.OrdID
      select ord.Freight).Sum();`

**NOTES**:

1.  I'm trying to follow these _MSDN_ examples: [1](https://msdn.microsoft.com/en-us/library/bb386928(v=vs.110).aspx) and [2](https://msdn.microsoft.com/en-us/library/bb302045(v=vs.110).aspx)

2. I've verified that `Freight` column in Orders table is of type `float?`.  In VS2015, I've hover over `ord.Freight` in the above query to confirm the type of `Freight` column - that's is showing as `float?`

3. I've tried changing `var` to `float?` and `double?` and `decimal?`. But still the EXACT SAME error message as shown above.

**Comment by smitpatel** [comment] 2017-04-28 19:10
@maumar

**Comment by maumar** [comment] 2017-04-28 20:32
dupe of #7136 which is fixed in 1.1.2

**Closed** 2022-10-16 11:03 UTC
