### ISSUE TITLE
EF Core 3.1 and InMemoryDatabase doesn't look at transactional data.. maybe?

### ISSUE THREAD

**Issue by mortenmoulder** [dotnet/efcore#19204] opened 2019-12-06 12:43 UTC
I'm not sure when and why this isn't happening, but I know that EF Core 2.2.3 works as expected. I just figured this was an issue, because all I did was update to EF Core 3.1 and then my unit tests started to fail.

When you get an item from the database, then update its properties, asking the database for the same item (from an id) should return the one in the transaction, that hasn't been saved to the InMemoryDatabase yet.

### Steps to reproduce
Install the InMemory EF Core 3.1 NuGet package then:

```
var item = _dbContext.Items.Single(x => x.Id == id);
item.Name = "foo";

var item2 = _dbContext.Items.Single(x => x.id); //same id as above
Assert.IsTrue(item.Name, item2.Name); //explodes because they're different
```

Works perfectly if I insert a `_dbContext.SaveChangesAsync()` after I change the `item.Name`

### Further technical details

EF Core version: 3.1 (up from 2.2.3)
Database provider: InMemoryDatabase in tests. SqlServer in the normal application
Target framework: 2.2
Operating system: Windows 10

**Comment by ajcvickers** [comment] 2019-12-06 22:45
@mortenmoulder I am not able to reproduce this--see my code below. Please post a small, runnable project or complete code listing like below so we can investigate.

```C#
public class Item
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseInMemoryDatabase(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    public DbSet<Item> Items { get; set; }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Item {Name = "X"});
            
            await context.SaveChangesAsync();
        }
        
        using (var context = new BloggingContext())
        {
            var id = 1;
            var item = context.Items.Single(x => x.Id == id);
            item.Name = "foo";

            var item2 = context.Items.Single(x => x.Id == id); //same id as above
 
            Console.WriteLine(item.Name);
            Console.WriteLine(item2.Name);
        }
    }
}
```

**Comment by ajcvickers** [comment] 2019-12-13 17:46
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 17:59 UTC
Labels: closed-could-not-reproduce, customer-reported
