### ISSUE TITLE
New MissingRuntimeArtifactException in Release mode after EF Core 2.0 upgrade

### ISSUE THREAD

**Issue by thnk2wn** [dotnet/efcore#10189] opened 2017-10-30 21:01 UTC
We upgraded:
* UWP 10.0.15063.0 to 10.0.16299.0
* Microsoft.EntityFrameworkCore.Sqlite 1.1.3 to 2.0.0
* Net Standard 1.4 to 2.0.1

We now get the below error when the app runs in release mode (w/.net native compilation) with various queries:

<pre>
System.Reflection.MissingRuntimeArtifactException occurred
  HResult=0x8013151A
  Message=Cannot retrieve a MethodInfo for this delegate because the method it targeted was not enabled for metadata using the Dynamic attribute. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=616868
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
</pre>

Sample query where the error happens:

```c#
public async Task<IList<ServingOptionCategory>> GetServingOptionCategories()
{
    IList<ServingOptionCategory> servingOptionCategories =
        await _menuContext
            .ServingOptionCategories
            .Include(soc => soc.ServingOptionCategoryTag)
            .AsNoTracking()
            .ToListAsync();

    return servingOptionCategories;
}
```
This behavior didn't happen before targeting the previous versions. 

### Steps to reproduce
See the repo: https://github.com/thnk2wn/UwpReleaseBuildEfCoreIssue

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Win 10 Enterprise, Ver 1709, OS Build 16299.19
IDE: Visual Studio Enterprise 2017 15.4.1

### Expected Behavior
EF Core query runs the same without error in Release mode as it does in Debug. This was the behavior when targeting Microsoft.EntityFrameworkCore.Sqlite 1.1.3, .NET Standard 1.4, and UWP 10.0.15063.0.

**Comment by ajcvickers** [comment] 2017-10-31 01:43
@thnk2wn Could you try with the 2.0.1 pre-release bits as described at the end of this issue: #9355? We fixed a few issues with .NET Native in the 2.0.1 release, so it would be good to know if this is one of them.

**Comment by thnk2wn** [comment] 2017-10-31 03:27
Thanks @ajcvickers that appears to fix this issue. 

These might be separate (but perhaps related) issues but I could report them separately later if needed.

There's a new 'hidden' exception calling Context.Database.EnsureCreatedAsync:

<pre>
Microsoft.Data.Sqlite.SqliteException occurred
  HResult=0x80004005
  Message=SQLite Error 14: 'unable to open database file'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
</pre>

Performance is worse. Rebuilding our DB went from 2 minutes to 3 minutes in Debug builds and is 5 minutes in Release builds.

**Comment by smitpatel** [comment] 2017-10-31 05:22
Unable to open database could be related to https://github.com/aspnet/Microsoft.Data.Sqlite/issues/408

**Comment by ajcvickers** [comment] 2017-10-31 16:24
@thnk2wn Can you be more specific about what, "rebuilding our DB" means? Is this just building the EF model, or is it also running migrations, doing EnsureCreated, etc.?

I'm closing this as a dupe since it looks like both the original issue and the SQLite issue are already tracked.

Duplicate of #9355

**Comment by thnk2wn** [comment] 2017-10-31 17:41
Sorry @ajcvickers. By rebuilding our DB I'm referring to populating some 47 tables with data that comes from web services. That time **excludes** creating the DB itself and the web service calls - it's just taking the deserialized data, doing a little mapping/projecting in cases, and doing AddRangeAsync and SaveChangesAsync.

Are we better off excluding our EF project from .net native compilation? I see various issues on this topic such as https://github.com/aspnet/EntityFrameworkCore/issues/5570

**Closed** 2022-10-16 11:56 UTC
Labels: closed-duplicate
