### ISSUE TITLE
Blazor concurrently updating objects

### ISSUE THREAD

**Issue by mkalinski93** [dotnet/efcore#25303] opened 2021-07-21 10:08 UTC
Hello,

I have a question about updating objects within Blazor WebAssembly (ASP.Net Core Hosted).
In my Application, I have an updater which is a background job (Hangfire). This job gets tons of data and I need to update my objects in a transaction. Unfortunately, when I go into my blazor application and wants to update a specific object (in my example adding an Asp Net Core Identity Role user), I will get the following error: "An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call."

``` 
 An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
      System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
       ---> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
       ---> MySqlConnector.MySqlException (0x80004005): The Command Timeout expired before the operation completed.
       ---> MySqlConnector.MySqlException (0x80004005): Query execution was interrupted
         at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 890
         at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
         at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 119
         at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
         at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
         at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 315
         at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 307
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.UpdateAsync(TUser user, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Identity.UserManager`1.UpdateUserAsync(TUser user)
         at Microsoft.AspNetCore.Identity.UserManager`1.AddToRoleAsync(TUser user, String role)
         at Application.Roles.Commands.UpdateRoles.UpdateRoleUsersCommandHandler.Handle(UpdateRoleUsersCommand request, CancellationToken cancellationToken) in /Project/src/Server/Application/Roles/Commands/UpdateRoles/UpdateRoleUsersCommand.cs:line 71
         at Application.Common.Behaviors.PerformanceBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in /Project/src/Server/Application/Common/Behaviors/PerformanceBehavior.cs:line 38
         at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
         at Infrastructure.Services.RoleService.UpdateRoleUsersAsync(UpdateRoleUsersCommand command, CancellationToken cancellationToken) in /Project/src/Server/Infrastructure/Services/RoleService.cs:line 68
         at Pricing.Server.Controllers.V1.RoleController.UpdateRoleUsers(UpdateRoleUsersRequest request) in /Project/src/Server/Pricing.Server/Controllers/V1/RoleController.cs:line 111
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Pricing.Server.Common.Middlewares.ExceptionMiddleware.InvokeAsync(HttpContext context) in /Project/src/Server/Pricing.Server/Common/Middlewares/ExceptionMiddleware.cs:line 53

```

I´ve activate the EnableRetryOnFailure strategy, but this doesn´t cooperate with user-initiated transactions.

Somehow, when the background worker is doing its part, I am not able to update any other objects anymore. Also it seems that something is in transaction, the dbcontext is blocked for writing purposes.
My services and the dbcontext is added as a scoped service.

Please let me know if you need additional information.

UnitOfWork.cs - Transactions
```csharp
        private IDbContextTransaction _transaction;
        public async Task BeginTransactionAsync(CancellationToken cancellationToken = default) {
            if (_dbFactory.DbContext.Database.CurrentTransaction != null && _transaction != null)
                throw new TransactionException("There´s already an open transaction");
            _transaction = await _dbFactory.DbContext.Database.BeginTransactionAsync(cancellationToken);
        }

        public async Task CommitTransactionAsync(CancellationToken cancellationToken = default) {
            await _transaction.CommitAsync(cancellationToken);
        }

        public async Task RollbackTransactionAsync(CancellationToken cancellationToken = default) {
            await _transaction.RollbackAsync(cancellationToken);
            await _transaction.DisposeAsync();
            _transaction = null;
        }
```

```csharp
services.AddDbContext<PricingDbContext>(options => {
                options.UseMySql(connectionString, ServerVersion.AutoDetect(connectionString), builder => {
                    builder.EnableStringComparisonTranslations();
                });
#if DEBUG
                options.EnableSensitiveDataLogging();
                options.EnableDetailedErrors();
#endif
            });
            services.AddScoped<DbContext, PricingDbContext>();
            services.AddIdentity<ApplicationUser, ApplicationRole>()
                .AddEntityFrameworkStores<PricingDbContext>()
                .AddDefaultTokenProviders();
            services.AddScoped<Func<PricingDbContext>>(provider => () => provider.GetService<PricingDbContext>());
            services.AddScoped<DbFactory>();
            services.AddScoped<IUnitOfWork, UnitOfWork>();
```

![image](https://user-images.githubusercontent.com/64005967/126475609-0e67aba5-83df-497f-b784-6f1aa1f1c4b3.png)

My assumption is that when I submit the job request to the server, the Server then will create a new background instance which my dbcontext gets scoped into. The very next request from my frontend should create a new instance of DbContext. But somehow the update call just gets stuck and the command times out.

*EDIT: It seems that only this method is not working.
 ```chsarp
 IdentityResult addResult = await _userManager.AddToRoleAsync(applicationUser, role.Name);
``` 

Setup

Blazor WebAssembly
EntityFrameworkCore 5.0.7
Net5.0

**Comment by ajcvickers** [comment] 2021-07-26 09:49
@mkalinski93 It's not obvious to me what is going on here, but it seems likely that the same DbContext instance instance is being used concurrently by multiple threads. To that end, can you verify this assumption:

> My assumption is that when I submit the job request to the server, the Server then will create a new background instance which my dbcontext gets scoped into.

And also that the DbContext itself is a new instance?

**Comment by mkalinski93** [comment] 2021-07-27 04:58
Theoretically it shouldn´t be the same instance. 
The services are scoped and when I create a background job it actually should create a new instance of DbContext, because the job instance will be created and executed later on (the initial request/response scope should have been disposed at this moment). I can not say for sure what hangfire does in the background, but it would result into multiple threads in which the dbcontext would be instantiated and scoped into. Meaning for another request (while the job is running in the background), it should create yet another instance for the request/response scope.

I´ve found out that the asp net core identity "AddToRoleAsync" method is the only method which causes this issue. Maybe it has something to do with asp net core identity?!

**Comment by ajcvickers** [comment] 2021-07-28 11:12
@mkalinski93 I think we will need to be able to see what you are seeing to investigate further. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2021-08-06 13:01
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:40 UTC
Labels: closed-could-not-reproduce, customer-reported
