### ISSUE TITLE
Exception thrown when grouping by  DATEPART

### ISSUE THREAD

**Issue by denisstepanenko** [dotnet/efcore#27078] opened 2021-12-30 10:38 UTC
Lets assume we have the following table:

```
CREATE TABLE Entities (
	EntityID INT NOT NULL IDENTITY, 
	CreatedOn DATETIME NOT NULL
	Description VARCHAR(50) NOT NULL
)
```

Next we have the following group-by query:

```
var query = 
	from e in context.Entities
	group e by e.Description
	into grp
	select new {
		grp.Key, 
		values=grp.Select(s=>s.EntityID)
	};
```

If we execute the above query we'd get the following SQL statement:

```
SELECT [t].[Description], [d0].[EntityID]
FROM (
    SELECT [d].[Description]
    FROM [Entities] AS [d]
    GROUP BY [d].[Description]
) AS [t]
LEFT JOIN [Entities] AS [d0] ON [t].[Description] = [d0].[Description]
ORDER BY [t].[Description]
```

However, if we use a date part in a group-by statement we'd get an exception as follows:

```
var query = 
	from e in context.Entities
	group e by e.CreatedOn.Day
	into grp
	select new {
		grp.Key, 
		values=grp.Select(s=>s.EntityID)
	};
```
	
Exception: 
```
	System.InvalidOperationException: 'Unable to translate a collection subquery in a projection since either parent or the subquery doesn't project necessary information required to uniquely identify it and correctly generate results on the client side. This can happen when trying to correlate on keyless entity type. This can also happen for some cases of projection before 'Distinct' or some shapes of grouping key in case of 'GroupBy'. These should either contain all key properties of the entity that the operation is applied on, or only contain simple property access expressions.'
```
	
Expected behaviour:
	Exception should not be thrown and the following SQL statement should be generated:
	
```
SELECT [t].[c], [d0].[EntityID]
FROM (
    SELECT DATEPART(day, [d].[CreatedOn]) AS [c]
    FROM [Entities] AS [d]
    GROUP BY DATEPART(day, [d].[CreatedOn])
) AS [t]
LEFT JOIN [Entities] AS [d0] ON [t].c = DATEPART(day, [d0].[CreatedOn])
ORDER BY [t].[c]
```

The above was tested with:

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows
IDE: Visual Studio 2022 17.0.3

**Comment by smitpatel** [comment] 2022-01-03 19:20
Duplicate of #26077

**Closed** 2022-10-16 20:20 UTC
Labels: closed-duplicate, customer-reported
