### ISSUE TITLE
Nested grouping generates invalid SQL

### ISSUE THREAD

**Issue by mcb2001** [dotnet/efcore#22240] opened 2020-08-26 08:41 UTC
Running a nested query results in invalid SQL for multitable select.

### Steps to reproduce

**Running the LINQ as provided below:**

`await portalDb.InvoiceHeaders
                .Where(x => x.BsFileHeader.Month == month
                    && x.BsFileHeader.Year == year
                    && x.PartnerId == partnerId)
                .AsNoTracking()
                .Select(invoice => new BsFileEntry
                {
                    ContractNumber = invoice.Contract.ContractNumber,
                    CustomerNumber = invoice.Customer.CustomerNumber,
                    InvoiceNumber = invoice.InvoiceNumber,
                    AmountIncludingVAT = invoice.Lines
                        .GroupBy(y => y.VatPercentage)
                        .Sum(y => y.Key * y.Sum(z => z.LineAmountExcludingVat) / 100.0M),
                })
                .ToListAsync();`

**generates the following SQL:**

` SELECT [x.Contract].[ContractNumber], [x.Customer].[CustomerNumber], [x].[InvoiceNumber], (
          SELECT SUM([t].[c])
          FROM (
              SELECT ([y].[VatPercentage] AS [Key] * SUM([y].[LineAmountExcludingVat])) / 100.0 AS [c]
              FROM [InvoiceLines] AS [y]
              WHERE [x].[Id] = [y].[InvoiceHeaderId]
              GROUP BY [y].[VatPercentage]
          ) AS [t]
      ) AS [AmountIncludingVAT]
      FROM [InvoiceHeaders] AS [x]
      INNER JOIN [Customers] AS [x.Customer] ON [x].[CustomerId] = [x.Customer].[Id]
      INNER JOIN [ContractHeaders] AS [x.Contract] ON [x].[ContractId] = [x.Contract].[Id]
      LEFT JOIN [BsFileHeaders] AS [x.BsFileHeader] ON [x].[BsFileHeaderId] = [x.BsFileHeader].[Id]
      WHERE (([x.BsFileHeader].[Month] = @__month_0) AND ([x.BsFileHeader].[Year] = @__year_1)) AND ([x].[PartnerId] = @__partnerId_2)`

**which for Azure SQL and SQL express 2019 is invalid SQL. Line 4, `AS [Key]` is the first invalid part. And yields the following exception to be thrown:**

fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (26ms) [Parameters=[@__month_0='?' (DbType = Int32), @__year_1='?' (DbType = Int32), @__partnerId_2='?' (DbType = Int64)], CommandType='Text', CommandTimeout='30']
      SELECT [x.Contract].[ContractNumber], [x.Customer].[CustomerNumber], [x].[InvoiceNumber], (
          SELECT SUM([t].[c])
          FROM (
              SELECT ([y].[VatPercentage] AS [Key] * SUM([y].[LineAmountExcludingVat])) / 100.0 AS [c]
              FROM [InvoiceLines] AS [y]
              WHERE [x].[Id] = [y].[InvoiceHeaderId]
              GROUP BY [y].[VatPercentage]
          ) AS [t]
      ) AS [AmountIncludingVAT]
      FROM [InvoiceHeaders] AS [x]
      INNER JOIN [Customers] AS [x.Customer] ON [x].[CustomerId] = [x.Customer].[Id]
      INNER JOIN [ContractHeaders] AS [x.Contract] ON [x].[ContractId] = [x.Contract].[Id]
      LEFT JOIN [BsFileHeaders] AS [x.BsFileHeader] ON [x].[BsFileHeaderId] = [x.BsFileHeader].[Id]
      WHERE (([x.BsFileHeader].[Month] = @__month_0) AND ([x.BsFileHeader].[Year] = @__year_1)) AND ([x].[PartnerId] = @__partnerId_2)
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'AS'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
ClientConnectionId:299bc2a4-2f65-4584-ac6c-92d9942f1f8e
Error Number:156,State:1,Class:15

### Further technical details

EF Core version: 2.2.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 2.2
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.2

**Comment by ErikEJ** [comment] 2020-08-26 13:42
EF Core 2.2 is no longer supported.

**Comment by ajcvickers** [comment] 2020-08-28 20:42
@mcb2001 As Erik says, EF Core 2.2 is [out-of-support](https://docs.microsoft.com/en-us/ef/core/what-is-new/). Please try [5.0 preview 8](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/5.0.0-preview.8.20407.4) and report back if the issue still occurs.

**Comment by smitpatel** [comment] 2020-09-04 14:55
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.

**Closed** 2022-10-16 18:38 UTC
Labels: closed-could-not-reproduce, customer-reported
