### ISSUE TITLE
DataAnnotation BUG

### ISSUE THREAD

**Issue by Mazin97** [dotnet/efcore#27492] opened 2022-02-22 13:53 UTC
## Visual Studio Version
2022 Version 17.1.0

## Summary
The DataAnnotation for colum type dont recognize if the case wasnt in correct format.

## Steps to Reproduce

1. put this DataAnnotation in column mapping:  [Column(TypeName = "SmallDateTime")]

## Expected Behavior
Translate the migration query to smalldatetime format

## Actual Behavior
Doesnt translate and inputs datetime format

## User Impact
Cannot run migrations

My migrations only worked when i changed from "SmallDateTime" to "smalldatetime"

**Comment by roji** [comment] 2022-02-23 09:14
@Mazin97 I couldn't reproduce any error - SQL Server doesn't care about the care of the types you specify, so `SmallDateTime` works the same way as `smalldatetime`. When specifying `SmallDateTime` as above, I got a migration file generated accordingly with `SmallDateTime`, and the following SQL got sent to the database, working just fine:

```sql
      CREATE TABLE [Blogs] (
          [Id] int NOT NULL IDENTITY,
          [DateTime] SmallDateTime NOT NULL,
          CONSTRAINT [PK_Blogs] PRIMARY KEY ([Id])
      );
```

Check your code again, and if you're still running into issues, please post a full, runnable code sample which shows the problem.

**Comment by ajcvickers** [comment] 2022-03-04 16:27
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:27 UTC
Labels: closed-could-not-reproduce, customer-reported
