### ISSUE TITLE
SQL with two inner join for the same table

### ISSUE THREAD

**Issue by stenionobres** [dotnet/efcore#21493] opened 2020-07-02 10:43 UTC
LINQ Query is parsed to SQL with two inner join for the same table.

### Steps to reproduce
**1** - Create Customer model class 

``` C#
[Table("Customer", Schema = "common")]
    public class Customer
    {
        public int Id { get; set; }
        
        [Required]
        [MaxLength(80)]
        public string Name { get; set; }

        [Required]
        [MaxLength(60)]
        public string Email { get; set; }

        [Required]
        public Address Address { get; set; }

        public int AddressId { get; set; }
    }
```
**2** - Create Address model class 

``` C#
[Table("Address", Schema = "common")]
    public class Address
    {
        public int Id { get; set; }

        [MaxLength(20)]
        public string Street { get; set; }
        
        [Required]
        [MaxLength(8)]
        public string ZipPostCode { get; set; }

        [Required]
        [MaxLength(20)]
        public string City { get; set; }
    }
```

**3** - Generate and apply migrations

**4** - Run the LINQ query

``` C#
using (var amazonCodeFirstContext = new AmazonCodeFirstDbContext())
{
                var query = from customer in amazonCodeFirstContext.Customer
                            join address in amazonCodeFirstContext.Address
                                on customer.Address.Id equals address.Id
                            select new
                            {
                                customer, address
                            };

                var data = query.ToList();

                return data.Select(d => d.customer);
}
```

**5** - SQL generated in the log

``` SQL
SELECT [c].[Id], [c].[AddressId], [c].[Email], [c].[Name], [a0].[Id], [a0].[City], [a0].[Street], [a0].[ZipPostCode]
      FROM [common].[Customer] AS [c]
      INNER JOIN [common].[Address] AS [a] ON [c].[AddressId] = [a].[Id]
      INNER JOIN [common].[Address] AS [a0] ON [a].[Id] = [a0].[Id]
```

**When I use the AddressId property in the LINQ the problem don't occurs.**

### Further technical details

**EF Core version**: 3.1
**Database provider**: Microsoft.EntityFrameworkCore.SqlServer 3.1.2
**Target framework**: NET Core 3.1
**Operating system**: Windows 10 Pro N
**IDE**: Visual Studio Community 2019 16.4.3

**Comment by smitpatel** [comment] 2020-07-02 13:47
Duplicate of #15826

**Closed** 2022-10-16 18:32 UTC
Labels: closed-duplicate, customer-reported
