### ISSUE TITLE
Script-Migration -idempotent creates script with errors

### ISSUE THREAD

**Issue by sdpollack** [dotnet/efcore#19740] opened 2020-01-29 16:53 UTC
I'm trying to create an idempotent migration script (as I've done previously).  The resulting script won't load due to errors.

### Steps to reproduce
1) At the VS Package Manager Console,  issue command "Script-Migration -idempotent"
2) Connect to a database running an earlier migration.
3) run the script.

Loading the script in VS shows 3 errors.  Running the script results in 5 errors.

[sd5bgmh0.txt](https://github.com/dotnet/efcore/files/4129294/sd5bgmh0.txt)

Msg 156, Level 15, State 1, Line 792
Incorrect syntax near the keyword 'procedure'.
Msg 156, Level 15, State 1, Line 1255
Incorrect syntax near the keyword 'procedure'.
Msg 137, Level 15, State 2, Line 1268
Must declare the scalar variable "@unitId".
Msg 156, Level 15, State 1, Line 1306
Incorrect syntax near the keyword 'procedure'.
Msg 137, Level 15, State 2, Line 1324
Must declare the scalar variable "@parentUnitId".
Msg 102, Level 15, State 1, Line 1333
Incorrect syntax near ')'.

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer 3.1.1
Target framework:  .NET Core 3.1
Operating system: Windows 10 Enterprise 1909
IDE: (e.g. Visual Studio 2019 16.3) VS 16.4.2

**Comment by ajcvickers** [comment] 2020-01-29 17:01
Could be a dupe of #12911.
/cc @bricelam

**Comment by bricelam** [comment] 2020-01-29 19:06
Not exactly a dupe. CREATE PROCEDURE calls are tricky since they need to be the first statement in a batch. EF6 wraps them inside EXEC:

```
EXECUTE('
    CREATE PROCEDURE ...
')
```

**Comment by ajcvickers** [comment] 2020-02-03 21:20
Linked to docs: https://github.com/aspnet/EntityFramework.Docs/issues/694

**Comment by bricelam** [comment] 2020-02-05 23:56
@sdpollack In case I was too subtle, you can work around this by changing your migration to use EXEC:
```csharp
migrationBuilder.Sql(@"
    EXECUTE('
        CREATE PROCEDURE ...
    ')
");
```

**Comment by ajcvickers** [comment] 2020-02-14 21:20
Tracked by documentation and #245

**Closed** 2022-10-16 18:08 UTC
Labels: closed-no-further-action, customer-reported
