### ISSUE TITLE
Skip Navigation issue with Many to Many join

### ISSUE THREAD

**Issue by Gregory-Lange** [dotnet/efcore#32857] opened 2024-01-18 18:38 UTC
I am getting an error with .Net 8 EF Core when using navigations and many to many joins.  

If I have it setup using the basic code:

```C#
_ = builder.HasMany(m => m.Class1s)
    .WithMany(m => m.Class2s)
    .UsingEntity("Class1Class2s");
```
It does work but then the column names doesn't align with the standards that are in place.  

When I use the more advanced way below so I can set those column names:

```C#
_ = builder.HasMany(m => m.Class1s)
    .WithMany(m => m.Class2s)
    .UsingEntity("Class1Class2s",
        l => l.HasOne(typeof(Entity.Class1)).WithMany().HasForeignKey("TitleId").HasPrincipalKey(nameof(Entity.Class1.Id)),
        r => r.HasOne(typeof(Entity.Class2)).WithMany().HasForeignKey("NameId").HasPrincipalKey(nameof(Entity.Class2.Id)),
        j => j.HasKey("TitleId", "NameId")
    );
```

This throws the below error and I do not understand why.  Also the linked article isn't even about the many to many join so not sure what it is trying to say.

```
Unable to create a 'DbContext' of type ''. The exception 'The skip navigation 'Class1.Class2s' doesn't have a foreign key associated with it. Every skip navigation must have a configured foreign key.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

In my class I have the following callouts to the navigations

```C#
Class1.cs
public virtual ICollection<Class2> Class2s { get; set; }

Class2.cs
public virtual ICollection<Class1> Class1s { get; set; }
```

Here is the CLI command I am using that throws the error.

```
dotnet ef migrations add Version1
```

**Comment by Gregory-Lange** [comment] 2024-01-18 21:21
Here is a bit more context this only happens for a non-self referencing many-to-many join.  If I have a self-referencing it works just fine with the advanced way. So I am really confused as to what is going on.

**Comment by ajcvickers** [comment] 2024-01-22 12:23
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2024-02-07 10:44
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-02-07 10:44 UTC
Labels: customer-reported

**Comment by Gregory-Lange** [comment] 2024-02-07 12:32
I will open new once I have had a chance to create the requested demo app showing this issue as I cannot just give you the code that I uncovered this with.  I acknowledge it could be something else in the solution but it works for self referencing many to many but not duel table as I describe.
