### ISSUE TITLE
Reference Data DbSet concept

### ISSUE THREAD

**Issue by benmccallum** [dotnet/efcore#22382] opened 2020-09-03 07:16 UTC
**Problem**
I've recently wrapped a couple of db calls to "reference data" tables with caching that I know will never change once the app starts up (States in a country for instance). I had a thought though that perhaps EF Core could have a built-in concept of a table that holds reference data that would make this easier and utilise `IMemoryCache` to cleverly avoid re-hitting the db every time for these.

**Solution ideas**
A special type of DbSet perhaps could handle this. Or an attribute/fluent config on the DbSet prop. Would also need to support navigation properties.

```
public class DbContext
{
    [ReferenceData]
    public DbSet<State> States { get; set; }

    // or

    public ReferenceDataDbSet<State> States { get; set; }
}
```

I like the attribute (and I guess an accompanying fluent-style method too) because we could support things like a cache configurations, and it's a smaller change but honestly have no idea what could be involved to achieve this (for direct calls to this prop, for calls via a navigation prop, etc)

Just an idea I thought I'd throw out!

**Comment by AndriySvyryd** [comment] 2020-09-03 07:46
Duplicate of https://github.com/dotnet/efcore/issues/12206

**Comment by benmccallum** [comment] 2020-09-03 07:52
Sorry @AndriySvyryd, I did try to look, but when "reference data" returns 100 issues... it's painful!

**Closed** 2022-10-16 18:39 UTC
Labels: customer-reported
