### ISSUE TITLE
Just upgrade from .net 6 to .net 7 and get an issue on "await app.RunAsync();"

### ISSUE THREAD

**Issue by ranouf** [dotnet/efcore#29684] opened 2022-11-27 03:14 UTC
Hi, 
 
 I just Just upgraded from .net 6 to .net 7 and get an issue on "await app.RunAsync();".
 
  System.MissingMethodException : Method not found: 'System.Collections.Generic.IList`1<Microsoft.EntityFrameworkCore.Metadata.Conventions.IModelFinalizingConvention> Microsoft.EntityFrameworkCore.Metadata.Conventions.ConventionSet.get_ModelFinalizingConventions()'.
  Stack Trace:
     at Microsoft.EntityFrameworkCore.InMemory.Metadata.Conventions.InMemoryConventionSetBuilder.CreateConventionSet()
     
     
![image](https://user-images.githubusercontent.com/1764519/204117552-6aa9d94b-28d3-4b46-8015-8cbae1034840.png)

     
  Any idea how to fix the issue?
  
  Thanks

**Comment by roji** [comment] 2022-11-27 08:27
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ErikEJ** [comment] 2022-11-27 08:57
Mixing EF Core versions. Please share your .csproj

**Comment by miguelfradinho** [comment] 2022-12-01 13:14
@ranouf  
It's what @ErikEJ said, _**check if you're not referencing any projects that have previous versions of EF Core**_


Had a similar issue when using a multi-project solution while using InMemoryDatabase as the context, on .NET 6.
Structure was the following
```
Solution
|-- DataProject
|--|-- DataService (provides a default implementation for DbContext)

|-- MainProject (references DataProject)
|--|-- MainProgram (setups DbContext with options for InMemoryDb and instantiates DataService with that context)
```

DataProject had `Microsoft.EntityFrameworkCore`  + ``Microsoft.EntityFrameworkCore.InMemory` versions 6.0.11

MainProject had `Microsoft.EntityFrameworkCore` version 7.0.0

When downgrading MainProject to 6.0.11, everything would work, but not when updating it to EF Core 7.

I fixed it by just installing EF Core 7 + EF Core InMemory 7 on `MainProject`, while DataProject still has EF Core 6 dependencies

(sorry for the bump, but just a confirmation of the fix)

**Comment by ajcvickers** [comment] 2022-12-05 11:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2022-12-05 11:49 UTC
Labels: customer-reported
