### ISSUE TITLE
Simple scalar group by does not work

### ISSUE THREAD

**Issue by TehWardy** [dotnet/efcore#20328] opened 2020-03-18 09:30 UTC
Having been advised to upgrade from v2 because of it's end of life I notice that basically grouping is broken, the current advice appears to be to generate a ticket for grouping scenario, I couldn't find one for this scenario so here it is ...

```cs
var results = Db.Set<T>().GroupBy(i => i.ScalarValue).ToArray();
```

... this results in the well known issue that others reporting grouping problems are facing.
Solving this by the looks of things will fix at least 5 or 6 OData related tickets too.

Typical example from my web stack, I have an entity that looks like this ...

```cs
[Table("Resources", Schema = "CMS")]
public class Resource
{
    [Key]
    public int Id { get; set; }

    [ForeignKey("App")]
    public int AppId { get; set; }

    [Required]
    public string Key { get; set; }

    [Required(AllowEmptyStrings = true)]
    public string Culture { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string DisplayName { get; set; }

    [Required]
    public string ShortDisplayName { get; set; }

    [Required]
    public string Description { get; set; }

    public virtual App App { get; set; }
}
```

Running this query on EF Core 3.1 breaks, but works find on EF Core 2 ...
```cs
var resources = Db.Set<Resource>()
   .Where(r => r.AppId = 1).GroupBy(r => r.Key)
   .ToArray();
```

**Comment by smitpatel** [comment] 2020-03-18 11:49
duplicate of #19929

**Closed** 2022-10-16 18:16 UTC
Labels: customer-reported
