### ISSUE TITLE
Model-level query sortings

### ISSUE THREAD

**Issue by MarcoLoetscher** [dotnet/efcore#9493] opened 2017-08-20 18:19 UTC
It would be very handy if sortings could be defined model-based.

Fluent API:
`modelBuilder.Entity<Post>().HasQuerySortOrderAsc(p => p.Title);`
`modelBuilder.Entity<Post>().HasQuerySortOrderAsc(p => p.Title).HasQuerySortOrderDesc(p => p.Content);`

Data Annotations:
`[QuerySortOrderAsc]
public string Title { get; set; }`
or
`[QuerySortOrderAsc(1)]
public string Title { get; set; }`
`[QuerySortOrderDesc(2)]
public string Content { get; set; }`

Using:
`var posts = context.Posts.Where(p => p.Title.StartsWith("a").ToList();`  //Without the OrderBy method, "model-level query sorting" should be used
or
`var blogs = context.Blogs.Include(blog => blog.Posts).ToList();`  //"model-level query sorting" should be used
or
`context.Entry(blog).Collection(b => b.Posts).Load();`  //"model-level query sorting" should be used

Thanks Marco

**Comment by ajcvickers** [comment] 2017-08-25 15:59
Note for triage:  I was not able to find this on the backlog, so putting it there.

**Comment by smitpatel** [comment] 2017-08-25 19:28
duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/7450 ?

**Comment by ajcvickers** [comment] 2017-08-25 19:52
Nice find, @smitpatel. You cal it sorting I call it ordering, let's call the whole thing off. ;-)

**Closed** 2022-10-16 11:17 UTC
