### ISSUE TITLE
Scaffold-DbContext: make an option to not capitalize table columns

### ISSUE THREAD

**Issue by reader-man** [dotnet/efcore#8078] opened 2017-04-05 11:23 UTC
Describe what is not working as expected.
Scaffold-DbContext is working as the designers want, but it would be helpful if there was an option to leave the generated table column names as is, leaving their capital/small letters without changing them, here i am talking especially about the first letter of the table column.

### Steps to reproduce
just use Scaffold-DbContext as normal to produce entities.

### Further technical details
EF Core version: 1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: win 10
IDE: Visual Studio 2017

**Comment by lajones** [comment] 2017-04-05 16:10
Many people want many different things for the generated code - closing this as dupe of e.g. #5947.

But, as referenced in that issue, it is possible already to override the `CandidateNamingService` - see https://gist.github.com/natemcmaster/353f4ab3efb4514eeaec846df28f0e24.

**Comment by ErikEJ** [comment] 2017-04-05 17:36
@sjh37 !

**Closed** 2022-10-16 10:59 UTC

**Comment by sjh37** [comment] 2022-10-16 18:37
This can already be achieved with the [EntityFramework Reverse POCO Code First Generator](https://marketplace.visualstudio.com/items?itemName=SimonHughes.EntityFrameworkReversePOCOGenerator). 

Beautifully generated code that is fully customisable. It generates code as if it was hand-written.

## Customisable output

The generated output is also fully customisable. Take a [look](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Full-control-over-the-generated-code) at some of the things you can customise. For example:

- Creating enumerations from database tables.
- Filter tables, columns, views, stored procedures, table-valued functions and scalar-valued functions to just the minimum set you require. This is key to having a fast EntityFramework.
- Generate FakeDbContext for easy unit testing.
- Rename tables, columns and stored procedures in your DB context.

To name but a few of what this generator is capable of. 
Used and trusted by over 500,000 developers worldwide.

**To remove the trail restrictions you will require a licence key.**
Free to academics (you need a .edu or a .ac email address), not free for commercial use.
Go to the [ReversePOCO](https://www.reversepoco.co.uk/) website to obtain/purchase your licence key.
