### ISSUE TITLE
.HasComputedColumnSql does not writes data

### ISSUE THREAD

**Issue by adindariztia** [dotnet/efcore#30872] opened 2023-05-11 02:52 UTC
Hi, i have a .net 6 server that has a table named Company which has a CompanyRate column that supposes to get its value generated by an SQL storeprocedure named "get_rate()", this store procedure has 2 params: a table reference name and the value of CompanyTypeId.

After a db migration using EF, i checked that in Pgadmin, the table Company is correctly configured, the column CompanyRate also has generated column as its constraint using get_rate(). However, the data insert seems like performing poorly. When I insert new data using either manually typing it in the pgadmin table or using INSERT script, the CompanyRate value is correctly generated and stored in the column. However, when there is a POST connection through the server to insert new data to the table, CompanyRate value is not promptly generated/stored in the column. I noticed that the CompanyRate data gets generated and stored only after another POST connection comes and inserts new data into the table.

Can anyone please help me, is this a bug or am i doing it wrong? Thank you!

```
public class Company
{
public long CompanyTypeId {get; set;}

[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
public long? CompanyRate {get; private set;}
}
```
```
public CompanyConfiguration : IEntityTypeConfiguration<Company>
{
  public void Configuration(EntityTypeBuilder<Company> builder)
  {
    builder.ToTable("Company");
    builder.HasKey(e => e.Id);
    builder.Property(e => e.Id).HasColumnType("bigint").ValueGeneratedOnAdd().IsRequired();

    builder.Property(e => e.CompanyTypeId ).HasColumnType("bigint").IsRequired();

   builder.Property(e => e.CompanyRate).HasColumnType("bigint").ValueGeneratedOnAddOrUpdate()
   .HasComputedColumnSql(@"get_rate('CompanyTypeRate','CompanyTypeId : ' || CAST(""CompanyTypeId"" AS text))",  stored: true);
  }
}
```

**Comment by roji** [comment] 2023-05-11 09:41
@adindariztia PostgreSQL is the one responsible for actually recalculating the computed column - EF merely provides the definition for it when creating the column. So if there's a problem here, it would be a PostgreSQL issue - which I highly doubt.

I'd recommend checking exactly what you're doing to make sure you're not e.g. accidentally caching values in your application etc. Otherwise, we're going to need to see a minimal, runnable code sample in order to investigate.

**Comment by ajcvickers** [comment] 2023-05-24 15:45
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-05-24 15:45 UTC
Labels: customer-reported
