### ISSUE TITLE
Compiled query does not respect ChangeTracker.QueryTrackingBehavior

### ISSUE THREAD

**Issue by mmateevadeltek** [dotnet/efcore#33389] opened 2024-03-25 08:04 UTC
I am using EF 6.0 and I have several compiled queries. Tracking behavior is not specified on the queries, so I expect tracking behavior to be what is set in ChangeTracker.QueryTrackingBehavior. But it seems to me that that behavior is the one that was currently set on the time of the compilation of the query. Is this the expected behavior? Does that mean I need to have different queries explicitly using .AsTracking() or .AsNoTracking() and use one or the other?

**Comment by roji** [comment] 2024-03-25 08:29
> Is this the expected behavior? Does that mean I need to have different queries explicitly using .AsTracking() or .AsNoTracking() and use one or the other?

Yes, that is the expected behavior.

The point of a compiled query is to be able to fully compile the query early, and exactly once. Different tracking behavior implies quite serious changes in the code which EF generates to read back results from the database (the shaper or materializer); if the compiled query took the context's tracking behavior into account each time it were executed, that would mean it would have to do a lot of query processing each time, which would defeat the purpose of a compiled query in the first place.

However, the tracking behavior of the context **at the time of compilation** should still be taken into account, so it should be possible to use that as a default (which can be overridden by inserting AsTracking/AsNoTracking into the compiled query).

I'm going to go ahead and close this issue as by design, but definitely feel free to post back here - we can continue the conversation.

**Closed by roji** 2024-03-25 08:29 UTC
Labels: customer-reported
