### ISSUE TITLE
ODBC EF Core database provider

### ISSUE THREAD

**Issue by eddiepantoja** [dotnet/efcore#20908] opened 2020-05-10 23:38 UTC
Are there any plans to support a ODBC provider for ef core?

**Comment by ErikEJ** [comment] 2020-05-11 08:00
Duplicate of #16795

**Comment by roji** [comment] 2020-05-11 08:04
@eddiepantoja out of curiosity, could you provide more details on your reason for wanting an ODBC provider? Is there a specific database you want to use, which doesn't have an ADO.NET provider? If so, which one?

**Comment by roji** [comment] 2020-05-11 14:17
@eddiepantoja I can only suggest you try the regular SQL Server provider which works on top of the ADO.NET SqlClient provider.

**Comment by eddiepantoja** [comment] 2020-05-11 14:27
I am using the SQL server provider on internal applications and it works perfectly. However in the case of external applications, the DB server has no DNS cannot be found on the external network. It is my understanding that it is common practice to use ODBC when connecting an internal DB to applications on the external network.

**Comment by roji** [comment] 2020-05-11 16:32
@eddiepantoja I've not heard of anything like that - but I may simply be unaware (am not particularly familiar with ODBC). As long as there's a way for the application to reach SQL Server (IP/hostname), then I can't really see what ODBC would bring to the table beyond just using ADO.NET via the regular provider.

**Closed** 2022-10-16 18:24 UTC
Labels: customer-reported
