### ISSUE TITLE
Timeout Issue in Entity Framework Core

### ISSUE THREAD

**Issue by gopal-k** [dotnet/efcore#14743] opened 2019-02-20 07:19 UTC
I have a **multi threading** application that needs to insert bulk of records in the same table from different places.  After continuously running 2 Hrs my application gets connection time out issue

**_Stack Trace_**
System.Data.SqlClient.SqlException (0x80131904): **Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding**. ---> System.ComponentModel.Win32Exception (258): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()

**I suspect this may be the cause of deadlock in a particular table. I verified in SQL that table is on deadlock.**

I have tried the following solution
1. using (var scope = new TransactionScope(TransactionScopeOption.Required, new TransactionOptions { IsolationLevel = IsolationLevel.ReadUncommitted }))

2.  I tried with SERIALIZABLE and  SNAPSHOT isolation levels also

When running the multi threading application it says **MSDTC Server on unavailble** . Note: I started the Distributed Transaction Coordinator service but still i get your environment not support distributed transactions 

I tried with **SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED** but still i am getting the same issue after 2Hrs running continuously

I added this  **SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED** between the BeginTransaction and Commit transaction in my C# code but no luck.

Could you please someone can help me to overcome from this ?

**Comment by roji** [comment] 2019-02-20 12:16
There don't seem to be any Entity Framework classes in your stack trace, are you using EF Core? Consider also posting this question on stackoverflow.

Either way, you'd have to provide some code sample to help understand what you're doing. The error mentioning MSDTC indicates that your code may be causing distributed transactions (probably unintentionally), which could be the source of your problem - you should definitely not be using distributed transactions unless you specifically need them, as they can cause severe perf degradation and other problems as well.

**Comment by ajcvickers** [comment] 2019-03-01 17:19
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ddineen** [comment] 2020-11-19 04:47
@gopal-k Did you find a solution to this issue? I am facing the same issue.

**Closed** 2022-10-16 13:52 UTC
Labels: closed-could-not-reproduce, customer-reported
