### ISSUE TITLE
Any/AnyAsync and concurrency problem

### ISSUE THREAD

**Issue by bugproof** [dotnet/efcore#14750] opened 2019-02-20 14:02 UTC
Let's say you want to check if something exists before inserting it. If this kind of check is executed concurrently and you're using `Any` for that there are high chances duplicate records will be inserted (unless you have a UNIQUE constraint for that column) because this isn't done atomically.

https://stackoverflow.com/questions/27005269/entity-framework-6-check-if-record-exists-before-insert-and-concurrency

Possible solutions:
- `INSERT ... INTO ... WHERE` and checking number of affected rows (impossible to do in EF Core without writing raw query)
- UNIQUE constraint and handling database exception (each backend has a different exception and code for that)

Is there any database-agnostic way to deal with this kind of problem? (atomic operation to check if not exists and insert) 

It would be good to document this scenario: https://docs.microsoft.com/en-us/ef/core/saving/concurrency

**Comment by ajcvickers** [comment] 2019-02-21 18:59
Duplicate of #14464

**Closed** 2022-10-16 13:52 UTC
Labels: customer-reported
