### ISSUE TITLE
Reverse engineering enum support 

### ISSUE THREAD

**Issue by emdadgar2** [dotnet/efcore#11366] opened 2018-03-21 03:09 UTC
Hi,
Please make enum support Reverse engineering.

Thanks

**Comment by ajcvickers** [comment] 2018-03-22 03:15
@emdadgar2 What would such support do? What would be recognized in the database that would then be  reverse engineered into an enum?

**Comment by ajcvickers** [comment] 2018-03-28 15:49
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:15 UTC
Labels: closed-could-not-reproduce
