### ISSUE TITLE
Query translation error with join linq

### ISSUE THREAD

**Issue by oruchreis** [dotnet/efcore#18449] opened 2019-10-18 12:29 UTC
### Summary
This code from Asp.Net Core Identity repo doesnt work with `long` User Id:
``` C#
var query = from userRole in UserRoles
                        join role in Roles on userRole.RoleId equals role.Id
                        where userRole.UserId.Equals(userId)
                        select role.Name;
```
but this works:
``` C#
var query = UserRoles.Where(ur => ur.UserId == userId).Select(ur => ur.Role.Name);
```

### Details
I'm using custom type for IdentityUser's Id which is long:
``` C#
public class User : IdentityUser<long>
```
I've upgraded EF Core and Asp.Net Core to 3.0 recently. And I've got this error:
```
The LINQ expression 'Join<UserRole, Role, long, TransparentIdentifier<UserRole, Role>>( outer: DbSet<UserRole>, inner: DbSet<Role>, outerKeySelector: (u) => u.RoleId, innerKeySelector: (r) => r.Id, resultSelector: (u, r) => new TransparentIdentifier<UserRole, Role>( Outer = u, Inner = r ))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```
_I attached stacktrace to end of this post._

I've researched Asp.Net Core Identity sources for this error, and I saw that the query is simple join linq query in the `GetRolesAsync` method: https://github.com/aspnet/AspNetCore/blob/b3599b6cfa1a65da3c3b5c74fa63111bdf62be34/src/Identity/EntityFrameworkCore/src/UserStore.cs#L398

As a workaround I've created custom `UserManager` and overrided `GetRolesAsync` method, and converted linq query to method based query, it worked well :
``` C#
public override async Task<IList<string>> GetRolesAsync(User user)
{
    ThrowIfDisposed();
    if (user == null)
    {
        throw new ArgumentNullException(nameof(user));
    }
    var userId = user.Id;
    var query = _membershipContext.UserRoles.Where(ur => ur.UserId == userId).Select(ur => ur.Role.Name);
    return await query.ToListAsync();
}
```
### Entities
``` C#
public class User : IdentityUser<long>
{
    public User()
    {
        Claims = new List<UserClaim>();
        Roles = new List<UserRole>();
    }
    public long RefId { get => Id; set => Id = value; }
    public Guid UserId { get; set; }
    public List<UserClaim> Claims { get; set; }
    public DateTime CreateDate { get; set; }
    public DateTime? DeleteDate { get; set; }
    public ICollection<UserRole> Roles { get; set; }
}

public class Role: IdentityRole<long>
{
    public Role()
    {
        Claims = new List<RoleClaim>();
    }
    public long RefId { get => Id; set => Id = value; }
    public Guid RoleId { get; set; }
    public ICollection<UserRole> Users { get; set; }
    public DateTime CreateDate { get; set; }
    public DateTime? DeleteDate { get; set; }
    public List<RoleClaim> Claims { get; set; }
}

public partial class UserRole: IdentityUserRole<long>
{
    public virtual Role Role { get; set; }
    public virtual User User { get; set; }
}

protected override void OnModelCreating(ModelBuilder builder)
{
    base.OnModelCreating(builder);

    builder.Entity<User>(entity =>
    {
        entity.Ignore(u => u.Id);
        entity.HasKey(u => u.RefId);
        entity.HasIndex(u => u.NormalizedUserName)
            .IsUnique(false);

        entity.Property(u => u.UserId)
            .IsRequired()
            .HasColumnType("uniqueidentifier")
            .ValueGeneratedOnAdd()
            .HasDefaultValueSql("NewID()");

        entity.HasMany(u => u.Claims)
            .WithOne(uc => uc.User)
            .HasForeignKey(u => u.UserId);

        entity.HasAlternateKey(u => u.UserId);
        entity.HasIndex(u => u.UserId).IsUnique().HasName("IX_UserId");
        entity.Property(u => u.CreateDate).HasDefaultValueSql("getdate()");                
        entity.ToTable("Users", "Membership");
    });

    builder.Entity<Role>(entity =>
    {
        entity.Ignore(u => u.Id);
        entity.HasKey(u => u.RefId);
        entity.HasIndex(u => u.NormalizedName)
            .IsUnique(false);

        entity.HasMany(u => u.Claims)
            .WithOne(uc => uc.Role)
            .HasForeignKey(u => u.RoleId);

        entity.Property(u => u.RoleId).IsRequired().HasColumnType("uniqueidentifier").ValueGeneratedOnAdd().HasDefaultValueSql("NewID()");
        entity.HasAlternateKey(u => u.RoleId);
        entity.HasIndex(u => u.RoleId).IsUnique().HasName("IX_RoleId");

        entity.ToTable("Roles", "Membership");
    });

    builder.Entity<UserRole>(entity =>
    {
        entity.HasKey(r => new { r.UserId, r.RoleId });
        entity.Property(u => u.RoleId).HasColumnName("RoleRefId");
        entity.Property(u => u.UserId).HasColumnName("UserRefId");

        entity.HasOne(d => d.Role)
            .WithMany(p => p.Users)
            .HasForeignKey(d => d.RoleId);

        entity.HasOne(d => d.User)
            .WithMany(p => p.Roles)
            .HasForeignKey(d => d.UserId);

        entity.ToTable("UserRoles", "Membership");
    });
```

### Exception:
```
The LINQ expression 'Join<UserRole, Role, long, TransparentIdentifier<UserRole, Role>>( outer: DbSet<UserRole>, inner: DbSet<Role>, outerKeySelector: (u) => u.RoleId, innerKeySelector: (r) => r.Id, resultSelector: (u, r) => new TransparentIdentifier<UserRole, Role>( Outer = u, Inner = r ))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.



    Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, ref <>c__DisplayClass8_0 )
    Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
    Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
    Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
    Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor<TResult>(Expression query)
    Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery<TResult>(Expression query, bool async)
    Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore<TResult>(IDatabase database, Expression query, IModel model, bool async)
    Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler+<>c__DisplayClass12_0<TResult>.<ExecuteAsync>b__0()
    Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore<TFunc>(object cacheKey, Func<Func<QueryContext, TFunc>> compiler)
    Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery<TResult>(object cacheKey, Func<Func<QueryContext, TResult>> compiler)
    Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync<TResult>(Expression query, CancellationToken cancellationToken)
    Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync<TResult>(Expression expression, CancellationToken cancellationToken)
    Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<TResult>.GetAsyncEnumerator(CancellationToken cancellationToken)
    System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable<T>.GetAsyncEnumerator()
    Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken)
    Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore<TUser, TRole, TContext, TKey, TUserClaim, TUserRole, TUserLogin, TUserToken, TRoleClaim>.GetRolesAsync(TUser user, CancellationToken cancellationToken)
    Microsoft.AspNetCore.Identity.UserManager<TUser>.GetRolesAsync(TUser user)
    Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory<TUser, TRole>.GenerateClaimsAsync(TUser user)
    Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory<TUser>.CreateAsync(TUser user)
    IdentityServer4.AspNetIdentity.UserClaimsFactory<TUser>.CreateAsync(TUser user)
    IdentityServer4.AspNetIdentity.ProfileService<TUser>.GetProfileDataAsync(ProfileDataRequestContext context)
    IdentityServer4.Services.DefaultClaimsService.GetIdentityTokenClaimsAsync(ClaimsPrincipal subject, Resources resources, bool includeAllIdentityClaims, ValidatedRequest request)
    IdentityServer4.Services.DefaultTokenService.CreateIdentityTokenAsync(TokenCreationRequest request)
    IdentityServer4.ResponseHandling.AuthorizeResponseGenerator.CreateImplicitFlowResponseAsync(ValidatedAuthorizeRequest request, string authorizationCode)
    IdentityServer4.ResponseHandling.AuthorizeResponseGenerator.CreateHybridFlowResponseAsync(ValidatedAuthorizeRequest request)
    IdentityServer4.ResponseHandling.AuthorizeResponseGenerator.CreateResponseAsync(ValidatedAuthorizeRequest request)
    IdentityServer4.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, ConsentResponse consent)
    IdentityServer4.Endpoints.AuthorizeEndpoint.ProcessAsync(HttpContext context)
    IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
    IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
    IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
    Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
    IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
    Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Further technical details
EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: win10-x64
IDE: Visual Studio 2019 16.3

**Comment by smitpatel** [comment] 2019-10-18 17:21
>  builder.Entity<Role>(entity =>
    {
        entity.Ignore(u => u.Id);


You have explicitly marked Role.Id as not mapped property in EF Core.
Following query uses that property. Since EF model does not know about property your query cannot be translated to SQL.
```C#
var query = from userRole in UserRoles
                        join role in Roles on userRole.RoleId equals role.Id
                        where userRole.UserId.Equals(userId)
                        select role.Name;
```

**Comment by ajcvickers** [comment] 2019-10-18 19:27
@oruchreis This "worked" in previous releases because the Identity queries were being evaluated in-memory. In 3.0, we explicitly [don't do this anymore](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client) partly because it often results in the entire table being pulled into memory.

The [key type can be changed](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.0) for most `Identity` entity types without needing to ignore properties from the model.

**Comment by oruchreis** [comment] 2019-10-21 08:14
@ajcvickers Thanks, but it worked in "3.0", not previous release. So If I use method based query, it pulls into memory and it works but if I use linq query it throws exception. Shouldn't the both query in 3.0 behave same? 
I'm ignoring the Id property because I want to change the name of Id column to RefId. So I ignored it, and implemented the RefId as:
``` C#
public long RefId { get => Id; set => Id = value; }
```

As far as I saw in @smitpatel 's answer, If I want to rename Id property, I must implement custom UserManager?

**Comment by smitpatel** [comment] 2019-10-21 14:43
> I'm ignoring the Id property because I want to change the name of Id column to RefId. So I ignored it, and implemented the RefId as:

Have you tried using `HasColumnName` API to just change name of the column on server side?

**Comment by ajcvickers** [comment] 2019-10-21 23:03
@oruchreis It would be useful to know what was the most recent release where you tested this and it worked? And what is the earliest release where you tested this and it doesn't work?

I didn't expect this to ever work with the final release of 3.0, although it likely would have worked up to and including 3.0 preview 5, since preview 6 is when the relevant change was made to EF Core.

**Comment by oruchreis** [comment] 2019-10-22 13:23
@smitpatel yes, it changes the column name, what i need to change is the name of the property of the entity as well as column name.
@ajcvickers I've tested both method-based and linq query with these same version:
```
<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0" />
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.0.0" />
```

**Comment by ajcvickers** [comment] 2019-10-25 20:49
@oruchreis The two queries posted originally are different queries doing different things. Is there some reason that if one works that means the other should work too?

**Comment by ajcvickers** [comment] 2019-11-01 15:10
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:50 UTC
Labels: closed-by-design, customer-reported
