### ISSUE TITLE
EF does'nt produce nested query when filter and top 1 in use

### ISSUE THREAD

**Issue by savamas** [dotnet/efcore#24634] opened 2021-04-12 10:18 UTC
Hi! I have the following code:
![image](https://user-images.githubusercontent.com/37020194/114378640-9574fc80-9b90-11eb-8310-97d17efcd260.png)

![image](https://user-images.githubusercontent.com/37020194/114378743-a9b8f980-9b90-11eb-8d63-689cc472b00b.png)

So I have Name and Description as Select Top1

I want to wrap this select as a subquery and make smth like this:
![image](https://user-images.githubusercontent.com/37020194/114378924-e127a600-9b90-11eb-8faa-007b91e61258.png)

So I want to wrap it and filter on Name or Number

But EF doesn't wrap it:

![image](https://user-images.githubusercontent.com/37020194/114379268-4380a680-9b91-11eb-8bad-39908afaf532.png)

It produces the following SQL without wrap:

![image](https://user-images.githubusercontent.com/37020194/114379325-58f5d080-9b91-11eb-806b-a5af82713d06.png)

It evaluates Name twice

Any ideas? Thanks

EF Core version: 5.0.2
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)

/Regards

**Comment by smitpatel** [comment] 2021-04-12 15:18
Duplicate of #7776

**Closed** 2022-10-16 19:31 UTC
Labels: closed-duplicate, customer-reported
