### ISSUE TITLE
Dotnet Core 3.1.101 can't install dotnet-ef

### ISSUE THREAD

**Issue by zliang68** [dotnet/efcore#19923] opened 2020-02-14 02:49 UTC
I have installed DotNet Core SDK 3.1.101 on Windows 10 Pro
This command won't work:
-> dotnet tool install --global dotnet-ef
error NU1100: Unable to resolve 'dotnet-ef ' for '.NETCoreApp,Version=v3.1'.
error NU1100: Unable to resolve 'dotnet-ef ' for '.NETCoreApp,Version=v3.1/any'.
The tool package could not be restored.
Tool 'dotnet-ef' failed to install. This failure may have been caused by:

You are attempting to install a preview release and did not use the --version option to specify the version.
A package by this name was found, but it was not a .NET Core tool.
The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
You mistyped the name of the tool.
For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by ajcvickers** [comment] 2020-02-14 21:56
@zliang68 Are you able to restore other NuGet packages without error?

**Comment by zliang68** [comment] 2020-02-15 02:25
I can install it using NUGET package manager in VS2019.  Not working when using dotnet cli.

**Comment by ajcvickers** [comment] 2020-02-21 22:01
@zliang68 We're going to need additional information to figure why these errors are being generated. To start with:
* Which version of Visual Studio 2019 are you using?
* Which .NET Core SDKs do you have installed?
* What NuGet feeds are you using? Just nuget.org or something else too?

**Comment by ajcvickers** [comment] 2020-02-28 17:02
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 18:11 UTC
Labels: closed-could-not-reproduce, customer-reported
