### ISSUE TITLE
Migrations: Mapping an Enum as IsRequired HasConversion<string> causes repeated migrations

### ISSUE THREAD

**Issue by AtomicBlom** [dotnet/efcore#11754] opened 2018-04-20 07:21 UTC
When attempting to map an enum as a non-nullable string to the database, when we generate migrations, the migrations will attempt to migrate the column with every new migration added.

### Steps to reproduce
Create a new .NET Core project (EFMigrationTest)

EFMigrationTest.csproj
```c#
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0-preview2-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0-preview2-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.0-preview2-final" />
  </ItemGroup>

</Project>
```

Program.cs
```c#
using Microsoft.EntityFrameworkCore;

namespace EFMigrationTest
{
    class Program
    {
        static void Main(string[] args)
        {
        }
    }

    public class MigrationTestContext : DbContext
    {
        public DbSet<EntityWithEnum> EntitiesWithEnum { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<EntityWithEnum>().Property(_ => _.TheEnum).HasConversion<string>().HasMaxLength(10).IsRequired();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFTest;Trusted_Connection=True;");
        }
    }

    public enum ExampleEnum
    {
        ValueA,
        ValueB
    }

    public class EntityWithEnum
    {
        public int Id { get; set; }
        public ExampleEnum TheEnum { get; set; }
    }
}
```

Restore the NuGet packages.

Run the following steps in the Package Manager Console
```powershell
Add-Migration initial_import
Add-Migration expect_no_changes
```

#### Expected Result
Migration `{date}_expect_no_changes.cs` should have empty Up() and Down()s

#### Actual Result
Migration `{date}_expect_no_changes.cs` adds AlterColumns that should already be set in `{date}_initial_import.cs`
```c#
    public partial class no_change : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "TheEnum",
                table: "EntitiesWithEnum",
                maxLength: 10,
                nullable: false,
                oldClrType: typeof(string),
                oldMaxLength: 10,
                oldNullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "TheEnum",
                table: "EntitiesWithEnum",
                maxLength: 10,
                nullable: true,
                oldClrType: typeof(string),
                oldMaxLength: 10);
        }
    }
```

### Further technical details
EF Core version: 2.1.0-preview2-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1709
IDE:  Visual Studio 2017 15.6.5

**Comment by bricelam** [comment] 2018-04-20 17:06
Duplicate of #11343. Fixed in [the nightly build of 2.1](https://dotnet.myget.org/gallery/dotnet-core).

**Closed** 2022-10-16 12:20 UTC
Labels: closed-duplicate
