### ISSUE TITLE
EFCore Use timestamps to control concurrency problems

### ISSUE THREAD

**Issue by grantgonggithub** [dotnet/efcore#16236] opened 2019-06-25 08:27 UTC
### My code is fine on ef6 but in efcore it will have the following exception:

_Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException:“Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.”_

Code:
```C#
    public partial class itemDetail
    {
        public string ItemGID { get; set; }
        public string GUID { get; set; }
        public string LineName { get; set; }

        public Nullable<int> LineId { get; set; }
        public virtual item item { get; set; }
        _public System.DateTime TS { get; set; }_  // This field is a timestamp in the database
    }


            using (var context = new demoContext())
            {
                var defaultPrimaryKey = "TestPK1";
               var _item = context.Set<item>().Find(defaultPrimaryKey); // Use the primary key to query the primary record
                var query = context.Set<itemDetail>().Where<itemDetail>(x => x.ItemGID == _item.ItemGID).AsEnumerable();
                context.Set<itemDetail>().RemoveRange(query); // Delete all details based on foreign keys
                var _itemDetails = _item.itemDetail.Where(x => x.LineId % 2 == 0).ToList(); // Select records where lineid is even
                int i = 0;
                for (i=0;i< _itemDetails.Count(); i++)
                {
                    var d = new itemDetail {
                        GUID = Guid.NewGuid().ToString("N"),
                        ItemGID = _itemDetails[i].ItemGID,
                        LineId = i,
                        LineName= _itemDetails[i].LineName
                    };
                    context.Set<itemDetail>().Add(d); //Insert records whose lineid is even after changing their Numbers
                }

                var newOne = new itemDetail
                {
                    GUID = Guid.NewGuid().ToString("N"),
                    ItemGID = defaultPrimaryKey,
                    LineId = i+1,
                    LineName ="new_LineName"
                };
                context.Set<itemDetail>().Add(newOne); //Insert new detail

                context.SaveChanges(); // commit
            }
        }
```

See the link below for the full code
https://github.com/grantgonggithub/mytestProj/tree/dev

### Further technical details
EF Core version: 2.2.4
Database Provider: Pomelo.EntityFrameworkCore.MySql 2.2
Operating system: 
IDE: Visual Studio 2019 16.1.3)

**Comment by grantgonggithub** [comment] 2019-06-25 08:44
If remove the TS field from the Model, I can succeed

delete  :     _public System.DateTime TS { get; set; }_
delete  :     _builder.Property(t => t.TS) .ValueGeneratedOnUpdate().IsConcurrencyToken();_

**Comment by ajcvickers** [comment] 2019-06-25 15:06
@grantgonggithub So in EF6 you had a SQL Server timestamp/rowversion column mapped to a C# `DataTime` property?

**Comment by grantgonggithub** [comment] 2019-06-26 01:13
> @grantgonggithub So in EF6 you had a SQL Server timestamp/rowversion column mapped to a C# `DataTime` property?

Yes, there is no problem with this code in EF6, but it reported an error when it was upgraded to netcore, and the table structure and code were not modified

**Comment by grantgonggithub** [comment] 2019-06-26 01:17
> > @grantgonggithub So in EF6 you had a SQL Server timestamp/rowversion column mapped to a C# `DataTime` property?
> 
> Yes, there is no problem with this code in EF6, but it reported an error when it was upgraded to netcore, and the table structure and code were not modified



Now I want to know what the real problem is and how to solve it

**Comment by ajcvickers** [comment] 2019-06-26 14:32
@grantgonggithub This looks like a MySQL database provider issue. I'm not sure what the mapping was in EF6 when using MySQL, but it sounds like the EF Core provider will need to support the same things for this to work. I suggest you follow up at: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

**Comment by grantgonggithub** [comment] 2019-06-28 04:50
> @grantgonggithub This looks like a MySQL database provider issue. I'm not sure what the mapping was in EF6 when using MySQL, but it sounds like the EF Core provider will need to support the same things for this to work. I suggest you follow up at: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

If it's  "Pomelo.EntityFrameworkCore.MySql" problem, it's the same error when I switch to sqlserver, so it's still  EFCore problem

**Comment by divega** [comment] 2019-06-28 08:28
FWIW, the [TIMESTAMP data type](https://dev.mysql.com/doc/refman/5.5/en/datetime.html) in MySQL is closer to the definition in SQL standard and equivalent to DATETIME in SQL Server. TIMESTAMP in SQL Server is a binary row version that doesn't make sense to map to a .NET DateTime. I think that might be the source of the confusion.

@grantgonggithub if you have a repro with SQL Server, please point us to it.

**Comment by grantgonggithub** [comment] 2019-06-28 10:07
> FWIW, the [TIMESTAMP data type](https://dev.mysql.com/doc/refman/5.5/en/datetime.html) in MySQL is closer to the definition in SQL standard and equivalent to DATETIME in SQL Server. TIMESTAMP in SQL Server is a binary type used for row versioning that doesn't make sense to map to a .NET DateTime. I think that might be the source of the confusion.
> 
> @grantgonggithub if you have a repro with SQL Server, please point us to it.

@divega   Thank you for answering my questions!
    My question is actually quite simple. This code works well in EF6, including SQL Server and MySql, but there is an error after upgrading EFCore. MySql and SQL Server both reported an error, so it can be confirmed that there is a difference between EF6 and EFCore in processing timestamp,I want to know what the difference is, or how can I solve the problem?

**Comment by ajcvickers** [comment] 2019-07-05 15:58
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:27 UTC
Labels: closed-could-not-reproduce, customer-reported
