### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. Parameter name: source

### ISSUE THREAD

**Issue by iberodev** [dotnet/efcore#6394] opened 2016-08-23 22:49 UTC
### Steps to reproduce

I have tried this with the 1.0.0 version and also with the nightly latest build `1.1.0-alpha1-21944` with same result.

I have a simple query where I try an include - then include.
**EXAMPLE 1 (fails):**

```
var businesses= _context.Businesses
                .Include(b => b.UserBusinesses).ThenInclude(ub => ub.AppAccesses)
                .ToList();
```

For some reason when I try to include the UserBusinesses related and then the AppAccesses related to each one of the UserBusiness, it crashes with the error below.
But if I try the following
**EXAMPLE 2 (ok):**

```
var businesses= _context.Businesses
                .Include(b => b.UserBusinesses).ThenInclude(ub => ub.GroupMemberships)
                .ToList();
```

which is basically the same (including all the user businesses with its groupMemberships), the query works well.

I have tried directly in the (localdb)\MSSQLLocalDB database with the following queries and it works well in both.

**EXAMPLE 1 (ok):**

```
SELECT *
  FROM [SpeediAuth].[Auth].[Business] b
  join [SpeediAuth].[Auth].[UserBusiness] ub on b.Id = ub.BusinessId
  join [SpeediAuth].[Auth].[AppAccess] aa on aa.UserBusinessId = ub.Id
```

**EXAMPLE 2 (ok):**

```
SELECT *
  FROM [SpeediAuth].[Auth].[Business] b
  join [SpeediAuth].[Auth].[UserBusiness] ub on b.Id = ub.BusinessId
  join [SpeediAuth].[Auth].[GroupMember] gm on gm.UserBusinessId = ub.Id
```

The mapping is almost identical in both list examples for the UserBusiness:

```
public class AppAccess
 {
        public Guid Id { get; set; }
        public Guid UserBusinessId { get; set; }
        public UserBusiness UserBusiness { get; set; }
        public Guid BusinessAppId { get; set; }
        public BusinessApp BusinessApp { get; set; }
        public DateTime CreatedOn { get; set; }
}

public class GroupMember
{
        public Guid Id { get; set; }
        public Guid UserBusinessId { get; set; }
        public UserBusiness UserBusiness { get; set; }
        public Guid GroupId { get; set; }
        public Group Group { get; set; }
        public DateTime CreatedOn { get; set; }
}

public class UserBusiness
{
        public Guid Id { get; set; }
        public string UserId { get; set; }
        public User User { get; set; }
        public Guid BusinessId { get; set; }
        public Business Business { get; set; }
        public byte[] RowVersion { get; set; }
        public List<AppAccess> AppAccesses { get; set; }
        public List<GroupMember> GroupMemberships { get; set; }
}

public class UserBusinessMap
{
        public UserBusinessMap(EntityTypeBuilder<UserBusiness> entityBuilder)
        {
            entityBuilder
                .HasKey(t => t.Id)
                .ForSqlServerIsClustered(clustered: false);

            entityBuilder.HasAlternateKey(t => new { t.UserId, t.BusinessId });

            //...
            entityBuilder.HasMany(t => t.AppAccesses)
                .WithOne(aa => aa.UserBusiness);

            entityBuilder.HasMany(t => t.GroupMemberships)
                .WithOne(aa => aa.UserBusiness);
            //...
        }
}
```

**EXAMPLE 1:**

```
    public class GroupMemberMap
    {
        public GroupMemberMap(EntityTypeBuilder<GroupMember> entityBuilder)
        {
            entityBuilder
                .HasKey(t => t.Id)
                .ForSqlServerIsClustered(clustered: false);

            entityBuilder.HasAlternateKey(t => new { t.UserBusinessId, t.GroupId });
            //...
            entityBuilder.HasOne(t => t.UserBusiness)
                .WithMany(userbusines => userbusines.GroupMemberships)
                .HasForeignKey(t => t.UserBusinessId)
                .OnDelete(DeleteBehavior.Cascade);
            //...
            entityBuilder.Property(t => t.UserBusinessId);
        }
    }
```

**EXAMPLE 2:**

```
    public class AppAccessMap
    {
        public AppAccessMap(EntityTypeBuilder<AppAccess> entityBuilder)
        {
            entityBuilder
                .HasKey(t => t.Id)
                .ForSqlServerIsClustered(clustered: false);

            entityBuilder.HasAlternateKey(t => new { t.UserBusinessId, t.BusinessAppId });

            entityBuilder
                .HasIndex(t => t.CreatedOn)
                .ForSqlServerIsClustered(clustered: true);

            entityBuilder.HasOne(aa => aa.UserBusiness)
                .WithMany(ub => ub.AppAccesses)
                .HasForeignKey(aa => aa.UserBusinessId)
                .OnDelete(DeleteBehavior.Cascade);
            //...
            entityBuilder.Property(t => t.UserBusinessId);
        }
    }
```
### The issue

Why when I query the Business including its UserBusinesses and then each GroupMembershisps it works well and when I query the Business including its UserBusinesses and then each AppAccesses **generates an almost identical query in database but it fails** with the error `System.ArgumentNullException: Value cannot be null.
Parameter name: source` as shown below in EXAMPLE 2?

**EXAMPLE 1 (ok):**

```
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Debug: Compiling query model: 'value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Speedi.Auth.Data.Models.Business]) => Include([b].UserBusinesses.GroupMemberships)'
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Debug: Optimized query model: 'value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Speedi.Auth.Data.Models.Business])'
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Debug: Including navigation: 'b.UserBusinesses.GroupMemberships'
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Debug: TRACKED: True
(QueryContext queryContext) => IEnumerable<Business> _Include(
    queryContext: (RelationalQueryContext) queryContext, 
    innerResults: IEnumerable<Business> _ShapedQuery(
        queryContext: queryContext, 
        shaperCommandContext: SelectExpression: 
            SELECT [b].[Id], [b].[AddressLine1], [b].[AddressLine2], [b].[BillingCurrencyCode], [b].[BusinessName], [b].[City], [b].[ContactName], [b].[CountryCode], [b].[CreatedOn], [b].[IsTestBusiness], [b].[ModifiedOn], [b].[PaymentType], [b].[PhoneNumber], [b].[PostalCode], [b].[Region], [b].[RowVersion], [b].[TimeZoneId]
            FROM [Auth].[Business] AS [b]
            ORDER BY [b].[Id]
        , 
        shaper: BufferedEntityShaper<Business>
    )
    , 
    entityAccessor: default(System.Func`2[Speedi.Auth.Data.Models.Business,System.Object]), 
    navigationPath: INavigation[] { Business.UserBusinesses, UserBusiness.GroupMemberships, }, 
    relatedEntitiesLoaderFactories: List<Func<QueryContext, IRelatedEntitiesLoader>> 
    { 
        System.Func`2[QueryContext,Internal.IRelatedEntitiesLoader], 
        System.Func`2[QueryContext,Internal.IRelatedEntitiesLoader], 
    }
    , 
    querySourceRequiresTracking: True
)

Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection:Debug: Opening connection to database 'SpeediAuth' on server '(localdb)\mssqllocaldb'.
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [b].[Id], [b].[AddressLine1], [b].[AddressLine2], [b].[BillingCurrencyCode], [b].[BusinessName], [b].[City], [b].[ContactName], [b].[CountryCode], [b].[CreatedOn], [b].[IsTestBusiness], [b].[ModifiedOn], [b].[PaymentType], [b].[PhoneNumber], [b].[PostalCode], [b].[Region], [b].[RowVersion], [b].[TimeZoneId]
FROM [Auth].[Business] AS [b]
ORDER BY [b].[Id]
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [u].[Id], [u].[BusinessId], [u].[CreatedOn], [u].[DeclarantCode], [u].[DeclarantPin], [u].[ModifiedOn], [u].[RowVersion], [u].[UserId], [u].[UserStatus]
FROM [Auth].[UserBusiness] AS [u]
WHERE EXISTS (
    SELECT 1
    FROM [Auth].[Business] AS [b]
    WHERE [u].[BusinessId] = [b].[Id])
ORDER BY [u].[BusinessId], [u].[Id]
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [g].[Id], [g].[CreatedOn], [g].[GroupId], [g].[UserBusinessId]
FROM [Auth].[GroupMember] AS [g]
INNER JOIN (
    SELECT DISTINCT [u].[BusinessId], [u].[Id]
    FROM [Auth].[UserBusiness] AS [u]
    WHERE EXISTS (
        SELECT 1
        FROM [Auth].[Business] AS [b]
        WHERE [u].[BusinessId] = [b].[Id])
) AS [u0] ON [g].[UserBusinessId] = [u0].[Id]
ORDER BY [u0].[BusinessId], [u0].[Id]
Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection:Debug: Closing connection to database 'SpeediAuth' on server '(localdb)\mssqllocaldb'.
```

**EXAMPLE 2 (fails):**

```
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Debug: Compiling query model: 'value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Speedi.Auth.Data.Models.Business]) => Include([b].UserBusinesses.AppAccesses)'
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Debug: Optimized query model: 'value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Speedi.Auth.Data.Models.Business])'
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Debug: Including navigation: 'b.UserBusinesses.AppAccesses'
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Debug: TRACKED: True
(QueryContext queryContext) => IEnumerable<Business> _Include(
    queryContext: (RelationalQueryContext) queryContext, 
    innerResults: IEnumerable<Business> _ShapedQuery(
        queryContext: queryContext, 
        shaperCommandContext: SelectExpression: 
            SELECT [b].[Id], [b].[AddressLine1], [b].[AddressLine2], [b].[BillingCurrencyCode], [b].[BusinessName], [b].[City], [b].[ContactName], [b].[CountryCode], [b].[CreatedOn], [b].[IsTestBusiness], [b].[ModifiedOn], [b].[PaymentType], [b].[PhoneNumber], [b].[PostalCode], [b].[Region], [b].[RowVersion], [b].[TimeZoneId]
            FROM [Auth].[Business] AS [b]
            ORDER BY [b].[Id]
        , 
        shaper: BufferedEntityShaper<Business>
    )
    , 
    entityAccessor: default(System.Func`2[Speedi.Auth.Data.Models.Business,System.Object]), 
    navigationPath: INavigation[] { Business.UserBusinesses, UserBusiness.AppAccesses, }, 
    relatedEntitiesLoaderFactories: List<Func<QueryContext, IRelatedEntitiesLoader>> 
    { 
        System.Func`2[QueryContext,Internal.IRelatedEntitiesLoader], 
        System.Func`2[QueryContext,Internal.IRelatedEntitiesLoader], 
    }
    , 
    querySourceRequiresTracking: True
)

Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection:Debug: Opening connection to database 'SpeediAuth' on server '(localdb)\mssqllocaldb'.
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [b].[Id], [b].[AddressLine1], [b].[AddressLine2], [b].[BillingCurrencyCode], [b].[BusinessName], [b].[City], [b].[ContactName], [b].[CountryCode], [b].[CreatedOn], [b].[IsTestBusiness], [b].[ModifiedOn], [b].[PaymentType], [b].[PhoneNumber], [b].[PostalCode], [b].[Region], [b].[RowVersion], [b].[TimeZoneId]
FROM [Auth].[Business] AS [b]
ORDER BY [b].[Id]
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [u].[Id], [u].[BusinessId], [u].[CreatedOn], [u].[DeclarantCode], [u].[DeclarantPin], [u].[ModifiedOn], [u].[RowVersion], [u].[UserId], [u].[UserStatus]
FROM [Auth].[UserBusiness] AS [u]
WHERE EXISTS (
    SELECT 1
    FROM [Auth].[Business] AS [b]
    WHERE [u].[BusinessId] = [b].[Id])
ORDER BY [u].[BusinessId], [u].[Id]
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [a].[Id], [a].[BusinessAppId], [a].[CreatedOn], [a].[UserBusinessId]
FROM [Auth].[AppAccess] AS [a]
INNER JOIN (
    SELECT DISTINCT [u].[BusinessId], [u].[Id]
    FROM [Auth].[UserBusiness] AS [u]
    WHERE EXISTS (
        SELECT 1
        FROM [Auth].[Business] AS [b]
        WHERE [u].[BusinessId] = [b].[Id])
) AS [u0] ON [a].[UserBusinessId] = [u0].[Id]
ORDER BY [u0].[BusinessId], [u0].[Id]
Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection:Debug: Closing connection to database 'SpeediAuth' on server '(localdb)\mssqllocaldb'.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.IO.MemoryMappedFiles.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.IO.UnmanagedMemoryStream.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory:Error: An exception occurred in the database while iterating the results of a query.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityTrackingInfo.<GetIncludedEntities>d__17.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityTrackingInfo.<GetIncludedEntities>d__17.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__157`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.StartTracking(Object entity, EntityTrackingInfo entityTrackingInfo)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()

System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityTrackingInfo.<GetIncludedEntities>d__17.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityTrackingInfo.<GetIncludedEntities>d__17.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__157`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.StartTracking(Object entity, EntityTrackingInfo entityTrackingInfo)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
Exception thrown: 'System.ArgumentNullException' in Microsoft.EntityFrameworkCore.dll

```
### Further technical details

EF Core version: **1.0.0** and I have also tried with **1.1.0-alpha1-21944**
Frameworks: netcoreapp1.0
Operating system:  Win10
Visual Studio version: 2015 update 3

Other details about my project setup: using (localdb)\MSSQLLocalDB

**Comment by iberodev** [comment] 2016-08-23 23:15
Also if I execute directly on database the generated SQL query that Entity generates :
```
SELECT [u].[Id], [u].[BusinessId], [u].[CreatedOn], [u].[DeclarantCode], [u].[DeclarantPin], [u].[ModifiedOn], [u].[RowVersion], [u].[UserId], [u].[UserStatus]
FROM [Auth].[UserBusiness] AS [u]
WHERE EXISTS (
    SELECT 1
    FROM [Auth].[Business] AS [b]
    WHERE [u].[BusinessId] = [b].[Id])
ORDER BY [u].[BusinessId], [u].[Id]
```

and 

```
SELECT [a].[Id], [a].[BusinessAppId], [a].[CreatedOn], [a].[UserBusinessId]
FROM [Auth].[AppAccess] AS [a]
INNER JOIN (
    SELECT DISTINCT [u].[BusinessId], [u].[Id]
    FROM [Auth].[UserBusiness] AS [u]
    WHERE EXISTS (
        SELECT 1
        FROM [Auth].[Business] AS [b]
        WHERE [u].[BusinessId] = [b].[Id])
) AS [u0] ON [a].[UserBusinessId] = [u0].[Id]
ORDER BY [u0].[BusinessId], [u0].[Id]
```

it works well and it returns one result (as expected).
But if it's Entity Framework who executes that query internally it throws the ArgumentNullException described before.
It seems there's a bug.

**Comment by maumar** [comment] 2016-08-30 01:17
This seems to be data-dependent. For some reason we are unable to extract tracked entities from EntityTrackingInfo. @iberodev could you give us some more info:

1) is this the only query you execute, or are there other queries execute before it?
2) does it work with AsNoTracking()?

```
                var businesses = ctx.Businesses.AsNoTracking()
                    .Include(b => b.UserBusinesses).ThenInclude(ub => ub.AppAccesses)
                    .ToList();
```

3) could you provide a data that your database is seeded with?
4) alternative to 3.  could you execute TSQL statements generated by the failing and working scenarios and paste the screenshots of the returned data? (should be 4 queries, you mentioned only one result is returned so hopefully it's not too much trouble)
5.) probably doesn't matter, but could you also provide listing for Business and User entities, along with the configuration.

**Comment by iberodev** [comment] 2016-08-30 22:59
Hi @maumar,

I forgot to mention before that I am also using ASP.NET Identity in case that affects, 

1)but I don't think there is any query executing before the problematic one.

I have spent some time trying to reproduce the issue in a small isolated project with almost similar data [ in this repository here ] (https://github.com/iberodev/EntityFramework6394)

but I have been unable to reproduce the issue so you must be right and it's something to do with my data (although I couldn't find any discrepancy). So I'm afraid this may not be a bug in EF after all.

I am suspecting there is some self-referencing loop that may be causing the issue since the E-R model has many inter dependencies.

2) if I try the same query adding AsNoTracking() as suggested it works well.

3) the data (a subset of the database) is [ in the repository I created ] (https://github.com/iberodev/EntityFramework6394). There is a SQL script to seed the database.

5) The entities and configuration is also included in the repository I created.

Sorry I couldn't identify the issue. I could reopen this issue if I ever spot the problem.

**Comment by maumar** [comment] 2016-08-31 02:16
@iberodev there is definitely and EF bug here - we should never be throwing this type of exception from our code. But there might also be an issue on your end. 

Problem is, without the actual data/workflow it will be very hard to diagnose the bug. If you happen to come across this issue again and are able to reproduce it reliably, please reactivate the issue or file a new one. For the time being I would suggest using AsNoTracking if the problem blocks your development.

**Comment by maumar** [comment] 2016-10-05 21:44
Closing as no repro.

**Closed by maumar** 2016-10-05 21:44 UTC
Labels: closed-could-not-reproduce

**Comment by cossth** [comment] 2019-08-02 12:02
I was getting same Error. I fixed it.
In my case I was running this query
`from d in _context.Data.Include(a => a.Timestamps).SelectMany(a => a.Timestamps).AsNoTracking()
                       group d by new TSKey
                       {
                           Time = new DateTime(
                           d.Timestamp.ToLocalTime().Year,
                           d.Timestamp.ToLocalTime().Month,
                           d.Timestamp.ToLocalTime().Day, 0, 0, 0),
                           CustId = d.CustId,
                           Hour = d.Timestamp.ToLocalTime().Hour
                       } into dm
                       select new
                       {
                           dm.Key,
                           Stamps = dm.Count()
                       };`

The Solution was implementing IComparable<TSKey> on TSKey
