### ISSUE TITLE
EnsureCreated and multiple connectionstrings

### ISSUE THREAD

**Issue by jarosmalen** [dotnet/efcore#6606] opened 2016-09-26 18:27 UTC
### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.
### The issue

Describe what is not working as expected.
The order of specification of the connectionstrings influences teh database creation.

For example I have the following DbContexts:

```
      services.AddEntityFramework()
        .AddSqlServer()
        .AddDbContext<SurveyDbContext>(options =>
            options.UseSqlServer(Configuration["Data:SurveyConnection:ConnectionString"]));

            services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<ApplicationDbContext>(options =>
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();
```

And subsequently in further on:

```
using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>()
                       .CreateScope())
                {
                   bool userDb = serviceScope.ServiceProvider.GetService<ApplicationDbContext>()
                          .Database.EnsureCreated();

                    bool success = serviceScope.ServiceProvider.GetService<SurveyDbContext>().Database.EnsureCreated();

                }
```

Only the ApplicationDbContext gets created, if I move the line

```
            services.AddEntityFramework()
           .AddSqlServer()
           .AddDbContext<SurveyDbContext>(options =>
               options.UseSqlServer(Configuration["Data:SurveyConnection:ConnectionString"]));
```

and put it after 

```
            services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<ApplicationDbContext>(options =>
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();
```

Both databases will be created. 

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```
### Further technical details

EF Core version: (found in project.json or packages.config)
Operating system: 
Visual Studio version: (e.g. VS 2013 or n/a)

Other details about my project setup:

**Comment by jarosmalen** [comment] 2016-09-26 18:30
"EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",

Are being used

**Comment by rowanmiller** [comment] 2016-10-04 20:07
Hey,

Those packages are very outdated, can you upgrade to the 1.0 RTM versions (`Microsoft.EntityFrameworkCore.SqlServer` etc.) and see if the issue is resolved.

One other thought... are both connection string pointing to the same database? If they are, then `EnsureCreated` will only create the database and schema if the database doesn't physically exist. So it won't add the tables from a second context if the database was already created from another context.

~Rowan

**Comment by rowanmiller** [comment] 2016-10-07 18:04
Closing as this should be fixed in the RTM version, but feel free to reply if not and we will reopen.

**Closed** 2022-10-16 09:58 UTC
Labels: closed-could-not-reproduce
