### ISSUE TITLE
Nullable Alternate Keys / Navigation Properties on Unique Keys

### ISSUE THREAD

**Issue by NathanNZ** [dotnet/efcore#13508] opened 2018-10-04 21:06 UTC
I'm currently prototyping a solution using EF Core, but I've hit into an issue with nullable alternate keys. As data coming into this system is going to be eventually consistent with identifiers coming from an outside event driven system I'd like to have the ability to link the objects when they eventually arrive using EF Core, but just have them return null if the object has not arrived yet.

My expected behaviour - if the alternate key was null then you just skip the join altogether and the object it is linked to should return as a null value. Instead I get the following exception message.

```
Exception message:
System.InvalidOperationException: 'Unable to track an entity of type 'User' because alternate key property 'ExternalId' is null. If the alternate key is not used in a relationship, then consider using a unique index instead. Unique indexes may contain nulls, while alternate keys must not.'

```

As I know I'm going to shoot myself in the foot by having checked foreign keys it would be even better to have EF do a join on a navigation property without resorting to foreign keys. Something like the below.. but with a bit more thought into the syntax.

>  userTasks.HasOne(e => e.User)
>                 .WithMany(e => e.UserTasks)
>                 .HasUniqueKey(e => e.ExternalUserId)
>                 .HasPrincipalKey(e => e.ExternalId);

As most relational databases support this pattern I don't think this is something that would be impossible, although I could also be going about this the completely wrong way - so open to advice on this front too 👍 

### Steps to reproduce
Run the following solution:
https://github.com/NathanNZ/EFCoreAlternateKeyHandling

### Further technical details
EF Core version: 2.1.1
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: 1809 Enterprise
IDE: Visual Studio 2017 15.8

**Comment by ajcvickers** [comment] 2018-10-05 16:49
Duplicate of #4415

**Comment by vinguan** [comment] 2019-09-09 13:58
Any updates on this? We can have nullable alternate keys now?

**Comment by AndriySvyryd** [comment] 2019-09-10 01:15
@vinguan See https://github.com/aspnet/EntityFrameworkCore/issues/4415

**Closed** 2022-10-16 13:34 UTC
Labels: closed-duplicate, customer-reported
