### ISSUE TITLE
Comment attributes on generated code from scaffolding

### ISSUE THREAD

**Issue by tr1ckyk1d** [dotnet/efcore#24070] opened 2021-02-05 11:16 UTC
Hi,

I can see  Microsoft.EntityFrameworkCore.CommentAttribute exists. There is also IColumn.Comment property in metadata. And I was able to find code in SqlServer specific provider which takes comment value from "MS_Description" extended property.
But I can not get Comment generated on my Model classes when I run "dotnet ef dbcontext scaffold". 
Any change to get it working with the latest codebase? It would be huge deal for self-documenting models - then we could expose these comments via OData API.

Thanks in advance!
- Roman

**Comment by roji** [comment] 2021-02-05 11:20
Duplicate of #19113

**Comment by roji** [comment] 2021-02-05 11:22
@ErikEJ has been done this 6.0.0 - you should be able to test it with the upcoming first preview release.

**Comment by ErikEJ** [comment] 2021-02-05 11:35
@tr1ckyk1d You can get that with EF Core Power Tools today, btw

**Comment by ErikEJ** [comment] 2021-02-05 13:19
@roji Did you mean to close this?

**Comment by tr1ckyk1d** [comment] 2021-02-05 14:06
Very promising, thanks everyone.

**Comment by tr1ckyk1d** [comment] 2021-02-05 15:40
> Duplicate of #19113

Not a duplicate though. We need 

[Comment("My Description from db.")] 

attributes on generated Classes and Properties, not how it's stated in #19113 

/// <summary>
///    My Description from db.
/// </summary>

**Comment by tr1ckyk1d** [comment] 2021-02-05 15:43
> @tr1ckyk1d You can get that with EF Core Power Tools today, btw

Can we get attribute generated, not comment?

**Comment by ErikEJ** [comment] 2021-02-05 15:49
Ah! Good feature suggestion, please post that on the EF Core Power Tools repo, and I will implement.

**Comment by ErikEJ** [comment] 2021-02-05 15:51
@roji Did I miss something in the EF Core 6 implementation perhaps?

**Comment by AndriySvyryd** [comment] 2021-02-05 18:42
Customizations like these will be possible by changing the templates: https://github.com/dotnet/efcore/issues/4038

**Comment by ErikEJ** [comment] 2021-02-06 08:02
@tr1ckyk1d Generation of Comment attribute (for EF Cofre 5) added to latest daily build of EF Core Power Tools

**Comment by ajcvickers** [comment] 2021-02-08 18:15
Note from triage: this will be possible once #4038 is implemented.

**Closed** 2022-10-16 19:22 UTC
Labels: closed-duplicate, customer-reported
