### ISSUE TITLE
EFCore3.0  Generate SQL

### ISSUE THREAD

**Issue by naruto1227** [dotnet/efcore#19026] opened 2019-11-22 03:11 UTC
I executed a simple query, but the SQL it generated contained many conditions that I did not want, which was not what I wanted, because the SQL executed in efcore2.2 was perfect

My code
            string i = "1";
            var contetnt = services.BuildServiceProvider().GetRequiredService<CPMemSysContext>();
            var info = contetnt.LoginRecord.Where(a => a.UserId == i).ToList();

![{91PHN4(ELBVER6K@Z8I%$E](https://user-images.githubusercontent.com/43592384/69394964-76b26380-0d18-11ea-9f4a-55f902260682.png)

EFCore3.0 Generate SQL

SELECT `l`.`Id`, `l`.`LoginIP`, `l`.`LoginTime`, `l`.`SourceType`, `l`.`UserId`
FROM `LoginRecord` AS `l`
WHERE ((`l`.`UserId` = @__i_0) AND (`l`.`UserId` IS NOT NULL AND @__i_0 IS NOT NULL)) OR (`l`.`UserId` IS NULL AND @__i_0 IS NULL)

![image](https://user-images.githubusercontent.com/43592384/69395025-98134f80-0d18-11ea-85bc-90aaaef8b5f9.png)

EFCore2.2 Generate SQL

SELECT `a`.`Id`, `a`.`LoginIP`, `a`.`LoginTime`, `a`.`SourceType`, `a`.`UserId`
FROM `LoginRecord` AS `a`
WHERE `a`.`UserId` = @__i_0

**Comment by zhanghaiboshiwo** [comment] 2019-11-22 03:12
I think efcore3.0 is more perfect, what configuration do I need to set

**Comment by ajcvickers** [comment] 2019-11-22 23:45
@maumar to de-dupe.

**Comment by maumar** [comment] 2019-11-25 18:45
dupe of #17543

**Closed** 2022-10-16 14:57 UTC
Labels: customer-reported
