### ISSUE TITLE
Different SQL Server DELETE statement in EF Core 7 surfaces SQL Server issue

### ISSUE THREAD

**Issue by rmja** [dotnet/efcore#29673] opened 2022-11-24 12:35 UTC
## File a bug

This is most likely a bug in SQL server but it is shown in EF Core 7. The same code in EF Core 6 works.

The SQL is captured in SQL Server Profiler after the following simple EF code:

```C#
db.AlarmRule.Remove(rule);
await db.SaveChangesAsync();
```

### Include your code

Restore the attached test database in sql server 15.0.2095.3.

Start SQL Server Management Studio and run:
```
USE [InferenceMonitoringContext-1]
```

Then run this sql which matches the sql generated by EF Core 7 when removing an entity:

```sql	  
SET NOCOUNT ON;
DELETE FROM [InferenceMonitoring].[AlarmRule]
OUTPUT 1
WHERE [Id] = 1;
```

This raises the following:

```
Msg 0, Level 11, State 0, Line 1
A severe error occurred on the current command.  The results, if any, should be discarded.

Completion time: 2022-11-24T13:26:35.1406808+01:00
```

The reason why this works in EF Core 6 is that the delete statement is different:

```sql
SET NOCOUNT ON;
DELETE FROM [InferenceMonitoring].[AlarmRule]
WHERE [Id] = @p0;
SELECT @@ROWCOUNT;
```
This completes just fine.

As I said, this is most likely a bug in SQL Server, but it shows after upgrading to .NET 7 / EF Core 7 because of the different delete operation used.

### Include provider and version information

EF Core version: 7.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system:
IDE: Visual Studio 2022 17.4
[Example.zip](https://github.com/dotnet/efcore/files/10084592/Example.zip)

**Comment by rmja** [comment] 2022-11-24 12:46
Upgrading to SQL Server 15.0.4261.1 solves this issue.

**Comment by ErikEJ** [comment] 2022-11-24 12:48
I am not able to repro on 15.0.2095.3 - can you share the full DDL for the table?

**Comment by rmja** [comment] 2022-11-24 12:53
1) Yes, how do I do that?, and 2) Is it too late now when have already upgraded my SQL Server instance?

**Comment by ErikEJ** [comment] 2022-11-24 12:55
Use script table as CREATE in SSMS

**Comment by rmja** [comment] 2022-11-24 13:01
One more related thing. I have a different place where I do deletes in the same database:

```sql
exec sp_executesql N'SET NOCOUNT ON;
DELETE FROM [InferenceMonitoring].[AlarmSelector]
OUTPUT 1
WHERE [Id] = @p0;
DELETE FROM [InferenceMonitoring].[AlarmSchedule]
OUTPUT 1
WHERE [Id] = @p1;
',N'@p0 int,@p1 int',@p0=1,@p1=1
```
This now returns

> The target table 'InferenceMonitoring.AlarmSchedule' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.

I guess that is very related to the change of delete statement in v7. The same "EF C# code" worked just fine in v6.

Here you go:

```sql
USE [InferenceMonitoringContext-1]
GO

/****** Object:  Table [InferenceMonitoring].[AlarmRule]    Script Date: 24/11/2022 13.55.55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [InferenceMonitoring].[AlarmRule](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ConsumptionTypeId] [int] NOT NULL,
	[Created] [datetime2](7) NOT NULL,
	[RepoTeam] [nvarchar](50) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[RepoName] [nvarchar](50) NOT NULL,
	[UqeExpression] [nvarchar](max) NOT NULL,
	[ThrottleDurationRule] [nvarchar](200) NOT NULL,
	[Repo]  AS (([RepoTeam]+'/')+[RepoName]) PERSISTED NOT NULL,
 CONSTRAINT [PK_AlarmRule] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [InferenceMonitoring].[AlarmRule] ADD  DEFAULT (N'') FOR [ThrottleDurationRule]
GO
```

**Comment by ErikEJ** [comment] 2022-11-24 13:07
for the other table, have a look at this [breaking change](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#sqlserver-tables-with-triggers)

**Comment by roji** [comment] 2022-11-24 13:51
> I am guessing is is due to this:
> [Repo]  AS (([RepoTeam]+'/')+[RepoName]) PERSISTED NOT NULL,

@ErikEJ I'm not aware of an issue with this...

@rmja as @ErikEJ wrote, for the trigger issue see [the breaking change note](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#sqlserver-tables-with-triggers).

For the issue with DELETE, I'm still unable to reproduce it with the following SQL, based on your description above:

<details>
<summary>Attempted repro</summary>

```sql
CREATE SCHEMA [InferenceMonitoring];
CREATE TABLE [InferenceMonitoring].[AlarmRule](
                                                  [Id] [int] IDENTITY(1,1) NOT NULL,
                                                  [ConsumptionTypeId] [int] NOT NULL,
                                                  [Created] [datetime2](7) NOT NULL,
                                                  [RepoTeam] [nvarchar](50) NOT NULL,
                                                  [Name] [nvarchar](100) NOT NULL,
                                                  [RepoName] [nvarchar](50) NOT NULL,
                                                  [UqeExpression] [nvarchar](max) NOT NULL,
                                                  [ThrottleDurationRule] [nvarchar](200) NOT NULL,
                                                  [Repo]  AS (([RepoTeam]+'/')+[RepoName]) PERSISTED NOT NULL,
                                                  CONSTRAINT [PK_AlarmRule] PRIMARY KEY CLUSTERED
                                                      (
                                                       [Id] ASC
                                                          )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
ALTER TABLE [InferenceMonitoring].[AlarmRule] ADD  DEFAULT (N'') FOR [ThrottleDurationRule];

DELETE FROM [InferenceMonitoring].[AlarmRule]
OUTPUT 1
WHERE [Id] = 1;
```

</details>

Note that I'm using SQL Server 16.0.1000.6, which is very recent. Can you please confirm if the above SQL fails for you, and what exact SQL Server version it fails on?

**Comment by rmja** [comment] 2022-11-24 13:55
The database in the attached [backup](https://github.com/dotnet/efcore/files/10084592/Example.zip) zip file produced the error in SQL Server 15.0.2095.3 after a simple restore.
I then upgraded to SQL Server 15.0.4261.1 - that version does not reproduce the error.

**Comment by rmja** [comment] 2022-11-24 14:06
@ErikEJ did you restore the attached example database on 15.0.2095.3? Or did you try and reproduce with example tables? (I realize now that it was easy to miss that a db backup was attached in the original issue)

**Comment by roji** [comment] 2022-11-24 14:08
OK, thanks.

If this is indeed a bug in 15.0.2095.3 which was fixed in a later patch, I don't think there's anything in particular we need to do... It's already possible to make EF revert to the previous SQL - which is considerably less efficient but more compatible - by configuring the table with HasTrigger.

**Closed** 2022-12-01 13:24 UTC
Labels: closed-external, customer-reported
