### ISSUE TITLE
ArgumentException thrown when building queries involving owned entities mapped with .ToJson()

### ISSUE THREAD

**Issue by bperc2** [dotnet/efcore#33046] opened 2024-02-09 21:56 UTC
After updating my project from versions 7.0.15 to 8.0.1, I'm encountering an exception with queries against a model that used to work before the upgrade. The part of the model that appears to be the hang-up involves:

-  An entity that owns many of something mapped with .ToJson()
- That owned entity owns many of another kind of entity
- These relationships involve properties and fields of differing types (property is an interface, field is concrete)

Here is a runnable example to demonstrate

```C#
using Microsoft.EntityFrameworkCore;

try
{
    using TestContext db = new();
    db.Database.EnsureCreated();

    var allOneLevelReviews = db.OneLevelReviews.ToList();

    // Exception occurs here
    var allReviews = db.Reviews.ToList();
    Console.WriteLine("OK");

}
catch (Exception ex)
{
    var exceptionString = ex.ToString();
    Console.WriteLine(ex.ToString());
}

Console.ReadLine();


public class Review
{
    public int Id { get; set; }

    private List<ReviewRound> _rounds = [];
    public IReadOnlyList<ReviewRound> Rounds => _rounds.AsReadOnly();
}

public class ReviewRound
{
    public int RoundNumber { get; set; }

    private List<SubRound> _subRounds = [];
    public IReadOnlyList<SubRound> SubRounds => _subRounds.AsReadOnly();
}

public class SubRound
{
    public int SubRoundNumber { get; set; }

}

public class OneLevelReview
{
    public int Id { get; set; }

    private List<SubRound> _subRounds = [];
    public IReadOnlyList<SubRound> SubRounds => _subRounds.AsReadOnly();
}



public class TestContext : DbContext
{
    public DbSet<Review> Reviews { get; set; }
    public DbSet<OneLevelReview> OneLevelReviews { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
    {
        options
            .UseSqlServer(
                "...",
                providerOptions => providerOptions.EnableRetryOnFailure())
            .EnableDetailedErrors()
            .EnableSensitiveDataLogging();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Review>().OwnsMany(x => x.Rounds, ownedBuilder =>
        {
            ownedBuilder.ToJson();

            ownedBuilder.OwnsMany(r => r.SubRounds);
        });

        modelBuilder.Entity<OneLevelReview>().OwnsMany(x => x.SubRounds, ownedBuilder =>
        {
            ownedBuilder.ToJson();
        });
    }
}

```

### Include stack traces

```
System.ArgumentException
  HResult=0x80070057
  Message=Expression of type 'System.Collections.Generic.IReadOnlyList`1[SubRound]' cannot be used for assignment to type 'System.Collections.Generic.List`1[SubRound]'
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Expression.Assign(Expression left, Expression right)
   at Microsoft.EntityFrameworkCore.Infrastructure.ExpressionExtensions.Assign(MemberExpression memberExpression, Expression valueExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.CreateJsonShapers(IEntityType entityType, Boolean nullable, ParameterExpression jsonReaderDataParameter, ParameterExpression keyValuesParameter, Expression parentEntityExpression, INavigation navigation)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ProcessShaper(Expression shaperExpression, RelationalCommandCache& relationalCommandCache, IReadOnlyList`1& readerColumns, LambdaExpression& relatedDataLoaders, Int32& collectionId)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQuery(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

### Include provider and version information

EF Core version: 8.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8

**Comment by maumar** [comment] 2024-02-10 08:56
the code provided works fine on current main as well as current release (8.0.3+). So this is a dupe. My guess was it's a dupe of https://github.com/dotnet/efcore/issues/31760 but that one should already be fixed in 8.0.0

**Comment by maumar** [comment] 2024-02-10 09:08
note: code works fine when _rounds, `_subRounds` and `_subRounds` are marked as `readonly` fields

**Comment by bperc2** [comment] 2024-02-12 19:37
I appreciate the quick response. Making my list fields readonly will work fine.

**Comment by maumar** [comment] 2024-02-16 03:10
when building `MaterializeJsonEntityCollection` method call, we take `navigation.ClrType` as target collection type. In reality the logic is more complicated. We should do something like `navigation.GetMemberInfo(...).GetMemberType()` instead.

**Closed** 2024-02-18 05:06 UTC
Labels: type-bug, closed-fixed, Servicing-consider, customer-reported
