### ISSUE TITLE
EF Core ignores 'Include' method after using 'SelectMany'

### ISSUE THREAD

**Issue by AlexandrTsvetkov** [dotnet/efcore#14667] opened 2019-02-10 21:49 UTC
It seems, EF Core ignores `Include(...)` method after calling `SelectMany(...)`

### Steps to reproduce
Let's say I have 4 basic models:
```c#
    public class Order
    {
        public int Id { get; set; }

        public IEnumerable<OrderItem> Items { get; set; }
    }

    public class OrderItem
    {
        public int Id { get; set; }

        public int ProductId { get; set; }

        public Product Product { get; set; }

        public int OrderId { get; set; }

        public Order Order { get; set; }
    }

    public class Product
    {
        public int Id { get; set; }

        public int UserId { get; set; }

        public User User { get; set; }
    }

    public class User
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
```
And `DbContext`
```c#
    public class AppDbContext :  DbContext
    {
        public DbSet<User> Users { get; set; }

        public DbSet<Order> Orders { get; set; }

        public DbSet<OrderItem> OrderItems { get; set; }

        public DbSet<Product> Products { get; set; }

        public AppDbContext(DbContextOptions<AppDbContext> options)
            : base(options)
        {
        }
    }
```
My case is I am trying to get all `Products` with `Users` from all `Orders`. Basically, I have two ways how to do it, but first way ignores `Include` and second doesn't.
1. **Ingoring** `Include`
```c#
context.Orders.SelectMany(x => x.Items.Select(y => y.Product))
                .Include(x => x.User).ToList();
```
Output SQL:
```sql
SELECT [x.Items.Product].[Id], [x.Items.Product].[UserId]
FROM [Orders] AS [x]
INNER JOIN [OrderItems] AS [x.Items] ON [x].[Id] = [x.Items].[OrderId]
INNER JOIN [Products] AS [x.Items.Product] ON [x.Items].[ProductId] = [x.Items.Product].[Id]
```
2. **Not ignoring** `Include`
```c#
context.Orders.SelectMany(x => x.Items).Select(y => y.Product)
                .Include(x => x.User).ToList();
```
Output SQL:
```sql
SELECT [x.Items.Product].[Id], [x.Items.Product].[UserId], [x.Items.Product.User].[Id], [x.Items.Product.User].[Name]
FROM [Orders] AS [x]
INNER JOIN [OrderItems] AS [x.Items] ON [x].[Id] = [x.Items].[OrderId]
INNER JOIN [Products] AS [x.Items.Product] ON [x.Items].[ProductId] = [x.Items.Product].[Id]
INNER JOIN [Users] AS [x.Items.Product.User] ON [x.Items.Product].[UserId] = [x.Items.Product.User].[Id]
```

### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.6

**Comment by ajcvickers** [comment] 2019-02-11 18:32
@smitpatel to find dupe.

**Comment by smitpatel** [comment] 2019-02-11 18:35
Duplicate of #12737

**Closed** 2022-10-16 13:51 UTC
Labels: customer-reported
