### ISSUE TITLE
ef core commands run slower on release mode

### ISSUE THREAD

**Issue by usapop** [dotnet/efcore#24594] opened 2021-04-06 14:07 UTC
Hi.
I work on a wpf application (.net framework 4.6.1) with entity framework core (version 3.1.13).
when I run my app in debug mode, application is run very fast, but in release mode, If I create instance from context or use linq queries, it takes some seconds (every time and every where in my app).
my database is sqlite with no data and simple.

**Comment by roji** [comment] 2021-04-06 14:31
@usapop are you also seeing seconds to connect every time in a minimal console program? If so, can you please post the source code?

**Comment by ajcvickers** [comment] 2021-04-16 14:21
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:30 UTC
Labels: closed-could-not-reproduce, customer-reported
