### ISSUE TITLE
EF Core generate SQL request which always return empty result.

### ISSUE THREAD

**Issue by vzabavnov** [dotnet/efcore#31129] opened 2023-06-23 19:14 UTC
Sample context:
```
[EntityTypeConfiguration(typeof(EntityConfig))]
public class Entity
{
        public int ID { get; set; }

        public string? SecondID { get; set; }

        public string? RefID { get; set; }

        public Entity? Ref { get; set; }
}

public class EntityConfig : IEntityTypeConfiguration<Entity>
{
        public void Configure(EntityTypeBuilder<Entity> builder)
        {
            builder.HasOne(z => z.Ref)
                .WithMany()
                .HasForeignKey(z => z.RefID)
                .HasPrincipalKey(z => z.SecondID);
        }
}

public class TheContext : DbContext
{
        public DbSet<Entity> Entities { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(
                "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=EFBugReproduction;Integrated Security=True;Encrypt=False;Application Intent=ReadWrite;");
        }
}
```
the code to reproduce:
```
internal class Program
{
        static void Main(string[] args)
        {
            using var ctx = new TheContext();

            var q = ctx.Entities.Where(z => z.SecondID == null);

            var str = q.ToQueryString();

            Console.WriteLine(str);
        }
}
```

The str has as result:
```
SELECT [e].[ID], [e].[RefID], [e].[SecondID]
FROM [Entities] AS [e]
WHERE 0 = 1
```

clause **WHERE 0 = 1** is an issue

dotnet ef dbcontext list --verbose output:
```
Entity Framework Core .NET Command-line Tools
7.0.8
PM> dotnet ef dbcontext list --verbose
Using project 'C:\Dev\EFBugReproduce\EFBugReproduce.csproj'.
Using startup project 'C:\Dev\EFBugReproduce\EFBugReproduce.csproj'.
Writing 'C:\Dev\EFBugReproduce\obj\EFBugReproduce.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\vad.HOME\AppData\Local\Temp\tmpC713.tmp /verbosity:quiet /nologo C:\Dev\EFBugReproduce\EFBugReproduce.csproj
Writing 'C:\Dev\EFBugReproduce\obj\EFBugReproduce.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\vad.HOME\AppData\Local\Temp\tmpC9B4.tmp /verbosity:quiet /nologo C:\Dev\EFBugReproduce\EFBugReproduce.csproj
Build started...
dotnet build C:\Dev\EFBugReproduce\EFBugReproduce.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.29
Build succeeded.
dotnet exec --depsfile C:\Dev\EFBugReproduce\bin\Debug\net7.0\EFBugReproduce.deps.json --additionalprobingpath C:\Users\vad.HOME\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --runtimeconfig C:\Dev\EFBugReproduce\bin\Debug\net7.0\EFBugReproduce.runtimeconfig.json C:\Users\vad.HOME\.dotnet\tools\.store\dotnet-ef\7.0.8\dotnet-ef\7.0.8\tools\net6.0\any\tools\netcoreapp2.0\any\ef.dll dbcontext list --assembly C:\Dev\EFBugReproduce\bin\Debug\net7.0\EFBugReproduce.dll --project C:\Dev\EFBugReproduce\EFBugReproduce.csproj --startup-assembly C:\Dev\EFBugReproduce\bin\Debug\net7.0\EFBugReproduce.dll --startup-project C:\Dev\EFBugReproduce\EFBugReproduce.csproj --project-dir C:\Dev\EFBugReproduce\ --root-namespace EFBugReproduce --language C# --framework net7.0 --nullable --working-dir C:\Dev\EFBugReproduce --verbose
Using assembly 'EFBugReproduce'.
Using startup assembly 'EFBugReproduce'.
Using application base 'C:\Dev\EFBugReproduce\bin\Debug\net7.0'.
Using working directory 'C:\Dev\EFBugReproduce'.
Using root namespace 'EFBugReproduce'.
Using project directory 'C:\Dev\EFBugReproduce\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'EFBugReproduce'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'TheContext'.
EFBugReproduce.TheContext
```
```
EF Core version: 7.0.8
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system: Windows 10 version 22H2 build 19045.3086
IDE: (e.g. Visual Studio 2022 17.6.4)
```

**Comment by roji** [comment] 2023-06-25 07:58
EF generally does not support nullable keys: if you look at the database schema created from your model, you'll see a NOT NULL column for SecondID even though the .NET property's type is `string?`. As such, the query `ctx.Entities.Where(z => z.SecondID == null)` can never return any values and EF translates it to `WHERE 1=0`.

**Comment by vzabavnov** [comment] 2023-06-26 18:22
Hello Shay,

I would agree if it is primary key. But the SecondID is not primary and could be nullable.

In normal live scenario often table has column, not primary key, that use to Join another table. In past I use that approach many times, but now this limitation not allow to use navigation property. I use EF from beginning, from 2008 and it worked before!

BTW, even is limited, it should not be like “WHERE 0 =1”, should be diagnostic with explanation.

 

My real live scenario:

I have table with PrimaryID and SecondaryID. PrimaryID is a Key and type nvarchar(50),  SecondaryID is optional, mean nullable and has type Int.

Also I have in the same table ParentID, it has type int and it is use to get parent row.

 

Another way to prove that is a bug: just add to configuration:

builder.ToView("JustView");

So, now we use view and cannot “modify” nullability. Result – still the same! It Is a BUG!

 

BTW, I already published the solution for Left Outer Join. You can take a look my article at 

Implementation of Left Outer Join for Entity Framework | by Vadim Zabavnov | Medium ***@***.***/implementation-of-left-outer-join-for-entity-framework-b47469633e2f> 

 

With Best Regards

 ***@***.***> Vadim Zabavnov

**Comment by roji** [comment] 2023-06-27 05:55
> I would agree if it is primary key. But the SecondID is not primary and could be nullable.

What I wrote above isn't specific to primary keys, but to all keys. In order for a navigation to point to an entity, there must be a key (primary or alternate) and that key cannot be nullable.

> In normal live scenario often table has column, not primary key, that use to Join another table. In past I use that approach many times, but now this limitation not allow to use navigation property. I use EF from beginning, from 2008 and it worked before!

I don't think EF ever supported null in keys, primary or otherwise - check the previous code which worked to understand exactly what you were doing.

Note that you can use the LINQ Join operator to manually specify JOINs; but if you use EF's navigations, your keys must be non-nullable.

More importantly, think carefully what it means for SecondID to be nullable; you're defining it is a key, which means that it must be unique. So even if EF supported this, it would mean that there can only ever be one Entity with SecondID null - is this really what you're looking to do?

> I have table with PrimaryID and SecondaryID. PrimaryID is a Key and type nvarchar(50),  SecondaryID is optional, mean nullable and has type Int.

Once again, keys are by their nature unique, since they must uniquely identify an entity, so that it can be pointed to by other entities. Is it really your intention to only allow one Entity with without a SecondaryID? If not, how would this key ever be used?

> BTW, even is limited, it should not be like “WHERE 0 =1”, should be diagnostic with explanation.

We could indeed warn for queries where this happens.

**Comment by vzabavnov** [comment] 2023-06-27 13:09
Hello Shay,

Well, this is not good, and not good at all. Navigation property is comfortable way to avoid Joins and now it does not work.

From DB perspective to retrieve data it is Inner Join or Left Outer Join, to store – it is a way to find related entity. Right?

Just imagine EF work with Views only, where, Primary, Secondary, Etc. keys – just value of complex query. In this case storage scenario not supported and it is fine. But using navigation really simplify life of EF developer. What EF currently force to do – I strongly do not like and will develop something to replace it for more comfortable use.

To support scenario I mentioned:

1.	Foreign key not nullable – use Inner Join
2.	Foreign Key nullable – use Left Outer Join
3.	Foreign Key nullable and Alternative Key nullable – use Left Outer Join. What is difference between this one and previous scenario?

EF lie to developers and try to change DB schema behind, even was specified  field IS NULLABLE. Not good.

 

BTW, wen specify Unique Index on nullable field – there is already constrain for uniqueness but support nullable values as well.

 

p.s. I already have in mind something to REPLACE NOT SUPPORTED feature related to this scenario. Another article you will see soon from me on Medium.com 

 

With Best Regards

 ***@***.***> Vadim Zabavnov

**Comment by roji** [comment] 2023-06-27 13:52
@vzabavnov as I said, this is something that EF currently doesn't support; this is something we could do, but as far as I know nobody has asked for it, since being able to have a nullable key generally isn't very useful. Note also that databases generally don't support nullable **primary** keys; it's true that alternate keys are different (and databases do support foreign key constraints pointing at nullable columns), but the database limitation for primary keys does provide some indication of the general non-usefulness of null keys.

> EF lie to developers and try to change DB schema behind, even was specified  field IS NULLABLE. Not good.

There's no lying here; your .NET property is configured as nullable, but EF maps it to a non-nullable database column - the property and the column are two different things. There are other scenarios where a the nullability of the property and the column may differ.

**Comment by ajcvickers** [comment] 2023-06-27 13:55
@vzabavnov Optional alternate keys is tracked by #4415. Make sure to vote (👍) for that issue.

**Comment by vzabavnov** [comment] 2023-06-27 14:01
Hello Arthur,

Done.

Well, with 1.8K issues it may be in EF version 1K, not  sooner ☹

 

For instance, left outer join support I was waiting for years and now implemented support for it myself

 

 

With Best Regards

 ***@***.***> Vadim Zabavnov

**Comment by roji** [comment] 2023-06-27 14:06
Duplicate of #4415

**Closed by roji** 2023-06-27 14:06 UTC
Labels: customer-reported
