### ISSUE TITLE
#9202 getting the same error in 2.1.2 when using include

### ISSUE THREAD

**Issue by Phalanx123** [dotnet/efcore#13412] opened 2018-09-25 08:29 UTC
I'm getting the same issue in 2.1.2 as was the case in issue #9202. If I use an include it fails with Value cannot be null.

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.4

**Comment by ajcvickers** [comment] 2018-09-25 15:17
@Phalanx123 Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by Phalanx123** [comment] 2018-09-25 23:42
I found that adding .AsNoTracking() prevents this from occurring.

OnGet
`NextService = await _context.EMWHs.Include(x=>x.EMWIs).FirstOrDefaultAsync(x =>  x.Complete == 'N' && x.EMCo == Equipment.EMCo && x.Equipment == Equipment.Equipment).ConfigureAwait(false);`

Context
```
            modelBuilder.Entity<EMWH>().HasMany(x => x.EMWIs).WithOne(x => x.EMWH)
                .HasForeignKey(x => new { x.EMCo, x.Equipment,x.WorkOrder }).HasPrincipalKey(x => new { x.EMCo, x.Equipment,x.WorkOrder });
```
EMWH
`   public class EMWH
    {
        public byte EMCo { get; set; }

        public string WorkOrder { get; set; }
        public string Equipment { get; set; }
        public string Description { get; set; }
        public Guid? UniqueAttchID { get; set; }
        public char Complete { get; set; }
        [Key]
        public long KeyID { get; set; }

        [Column("DateSched")]
        [Display(Name = "Scheduled Date")]
        public  DateTime ScheduledDate { get; set; }

        public virtual EMEM EMEM { get; set; }
       
        public virtual  IEnumerable<EMWI> EMWIs { get; set; }
        [NotMapped]
        public IEnumerable<HQAT> HQATs { get; set; }

    }`

EMWI
` public class EMWI
    {
        public byte EMCo { get; set; }
        public string WorkOrder { get; set; }
        public string Equipment { get; set; }
        public short WOItem { get; set; }
        public string CostCode { get; set; }
        public string Description { get; set; }
        public string StatusCode { get; set; }
        public string RepairType { get; set; }

        [Display(Name = "Date Completed")]
        [Column("DateCompl")]
        public DateTime? DateCompleted { get; set; }
        public Guid? UniqueAttchID { get; set; }
        [Key]
        public long KeyID { get; set; }

        public virtual  EMWH EMWH { get; set; }

        [NotMapped]
        public IEnumerable<HQAT> HQATs { get; set; }
    }`

**Comment by ajcvickers** [comment] 2018-10-03 17:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:32 UTC
Labels: closed-could-not-reproduce, customer-reported
