### ISSUE TITLE
Blazor-App Template with local authentication generates errors

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#19807] opened 2020-02-05 19:03 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/901174/blazor-app-template-with-local-authentication-gene.html)._

---
I use Visual Studion Professional 2019 version 16.4.3. When I create a Blazor app template with local authentication, I receive error messages in the added packages Microsoft.EntityFrameworkCore.SqlServer and Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.
For example: The package Microsoft.Data.SqlClient 1.0.19269.1 is not compatible with netcoreapp3.1 (. NETCoreApp, Version = v3.1). The Microsoft.Data.SqlClient 1.0.19269.1 package does not support target frameworks.
How can I solve this problem?

---
#### Visual Studio Feedback System on 2/3/2020, 01:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2020-02-08 23:05
I have not been able to reproduce this. Please post a small, runnable project that reproduces the behavior you are seeing so that we can fully investigate.

**Comment by mbloch17** [comment] 2020-02-09 08:50
[BlazorApp2.zip](https://github.com/dotnet/efcore/files/4176621/BlazorApp2.zip)
Thanks
Michael

**Comment by ajcvickers** [comment] 2020-02-11 21:41
@mkArtakMSFT Could this issue be caused by something in Blazor? I am able to reproduce the issue, but I can't figure out why the conflicts are happening.

**Comment by ajcvickers** [comment] 2020-02-18 20:29
@mkArtakMSFT Ping.

**Comment by mbloch17** [comment] 2020-02-19 06:13
Hi, 
after uninstalling the VS2017 and repairing the VS2019, the error no longer occurs. Thank you very much

**Comment by mkArtakMSFT** [comment] 2020-02-21 06:13
Sorry for noticing this late, @ajcvickers. I just noticed this notification but it looks like there was some VS related issue, as per @mbloch17 the error no longer occurs after VS2019 upgrade. We should close this.

**Closed** 2022-10-16 18:09 UTC
Labels: closed-external, customer-reported
