### ISSUE TITLE
Migrations: issue with enum type for new field - erroneous default value generated

### ISSUE THREAD

**Issue by bdelaney** [dotnet/efcore#4542] opened 2016-02-12 10:16 UTC
Ran Initial migration on small set of tables where I use a few enums. In the intial migration all worked well and I ran seed method. All good.
Returned to make small changes. Add one field to existing table. Used same enum type for field as used in two other tables in my Initial migration. Added migration. Fails Build on line number containing this code:
`defaultValue: phase.0);`
This being the last line in adding the new column.

Removing this line allows build. But the migration of course does not work because I had seeded that table and I had not allowed nulls in column I added.

Still, the migration code created would not even build and I thought this was worth bringing to your attention.
Running EF 7.0.0-rc1-16348

And marking the new column type as nullable did the trick.

**Comment by smitpatel** [comment] 2016-02-12 16:26
dupe of #4061

**Closed** 2022-10-16 09:28 UTC
