### ISSUE TITLE
Create model of views by Scaffold-DbContext

### ISSUE THREAD

**Issue by netbidev** [dotnet/efcore#10055] opened 2017-10-12 14:27 UTC
Hello everyone.

Is it possible to create model of views via Scaffold-DbContext?

**Comment by smitpatel** [comment] 2017-10-12 16:38
@netbidev - At present there is no way.
There is some work-around posted by a user here https://github.com/aspnet/EntityFrameworkCore/issues/9854#issue-258984255

Duplicate of #1679

**Comment by cgountanis** [comment] 2020-05-18 18:29
This seems to be an issue again with Core 3.1.

**Closed** 2022-10-16 11:54 UTC
