### ISSUE TITLE
Delete_entity_with_auto_include fails on Sqlite/PG

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#30577] opened 2023-03-24 21:07 UTC
Tracking issue to investigate what's going on here. 
Exception:

System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

```
  Stack Trace: 
    List`1.get_Item(Int32 index)
    SelectExpression.GetProjection(ProjectionBindingExpression projectionBindingExpression) line 1786
    RelationalSqlTranslatingExpressionVisitor.VisitExtension(Expression extensionExpression) line 629
    RelationalSqlTranslatingExpressionVisitor.BindProperty(EntityReferenceExpression entityReferenceExpression, IProperty property) line 1184
    RelationalSqlTranslatingExpressionVisitor.TryBindMember(Expression source, MemberIdentity member) line 1169
    RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 747
    RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 817
    RelationalSqlTranslatingExpressionVisitor.TryRewriteEntityEquality(ExpressionType nodeType, Expression left, Expression right, Boolean equalsMethod, Expression& result) line 1760
    RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 820
    RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression) line 133
    <28 more frames...>
    <>c__2`1.<Execute>b__2_0(<>f__AnonymousType0`2 s) line 83
    <>c__DisplayClass12_0`2.<Execute>b__0(DbContext _, TState s) line 392
    NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) line 75
    ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded) line 390
    ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation) line 331
    ExecutionStrategyExtensions.Execute[TState](IExecutionStrategy strategy, TState state, Action`1 operation) line 77
    TestHelpers.ExecuteWithStrategyInTransaction[TContext](Func`1 createContext, Action`2 useTransaction, Action`1 testOperation, Action`1 nestedTestOperation1, Action`1 nestedTestOperation2, Action`1 nestedTestOperation3) line 290
    NonSharedModelBulkUpdatesTestBase.AssertDelete[TContext,TResult](Boolean async, Func`1 contextCreator, Func`2 query, Int32 rowsAffectedCount) line 240
    NonSharedModelBulkUpdatesTestBase.Delete_entity_with_auto_include(Boolean async) line 135
```

**Comment by roji** [comment] 2024-02-11 12:14
@maumar FYI I'm syncing EFCore.PG to 9.0.0-preview.1 and the bug is gone for me; I can also see that there's no error for SQLite either. I think this can be closed-fixed.

**Comment by roji** [comment] 2024-02-11 12:22
Ah, here we go: this was apparently fixed in https://github.com/dotnet/efcore/pull/32824/files#diff-8de53372c76c56ee2828fdc0677bfe2a66cc44c23b942deff72c8945a99c4733R132. So this is a dup of #32823.

**Comment by roji** [comment] 2024-02-11 12:23
Duplicate of #32823

**Closed** 2024-02-14 13:15 UTC
Labels: closed-duplicate
