### ISSUE TITLE
How to manage adding/removal of properties to a class mapped to Json column?

### ISSUE THREAD

**Issue by cluka** [dotnet/efcore#32642] opened 2023-12-19 10:49 UTC
Hi,
I have a class that has reference to other class I want to be saved to json column in sql server.
ie.
```C#

    public class User
    {
        public Guid Id {get;set;}
        public string Name {get;set;}
        public UserSettings? Settings {get;set;}
    }

    public class UserSettings
    {
        public string Name {get;set;}
        public List<UiSetting> UiSettings {get;set;} = new();
    }

    public class UiSetting 
    {
        public string Name {get;set;}
        public string Value {get;set;}
    }
```

and it is mapped like this:

```C#

    builder.Entity<User>(b=>
    {
        b.ToTable("Users");
        b.HasKey(x=>x.Id);
        b.OwnsOne(x=>x.Settings, cfg=>
        {
            cfg.ToJson();
            cfg.WithOwner();
            cfg.OwnsMany(x=>x.UiSettings, pcfg=>pcfg.WithOwner());
        }  
    }

```

Everything is ok and working, and I can save/load Users.
Now if I add a new property to UserSetting ie.
```C#
    public class UserSettings
    {
        public string Name {get;set;}
        public List<UiSetting> UiSettings {get;set;} = new();
        
        public List<DeviceSetting> DeviceSettings {get;set;} = new();
    }

    public class DeviceSetting
    {
          public string Name {get;set;}
          public string Value {get;set;}
    }

    builder.Entity<User>(b=>
    {
        b.ToTable("Users");
        b.HasKey(x=>x.Id);
        b.OwnsOne(x=>x.Settings, cfg=>
        {
            cfg.ToJson();
            cfg.WithOwner();
            cfg.OwnsMany(x=>x.UiSettings, pcfg=>pcfg.WithOwner());
            cfg.OwnsMany(x=>x.DeviceSettings, pcfg=>pcfg.WithOwner());
        }  
    }
```

Now the problems begins.
If there is already data in User.Settings column and I try to load/update/save User I get error that the property DeviceSettings does not exist and it is an error thrown by SQL server itself. And to make it work again, I need to update every row in Users table and manually change Settings json to add missing new property.

Then...
If I remove property from UserSetting
Ie.

```C#
    public class UserSettings
    {
        public string Name {get;set;}
        //public List<UiSetting> UiSettings {get;set;} = new();
        
        public List<DeviceSetting> DeviceSettings {get;set;} = new();
    }
   
    builder.Entity<User>(b=>
    {
        b.ToTable("Users");
        b.HasKey(x=>x.Id);
        b.OwnsOne(x=>x.Settings, cfg=>
        {
            cfg.ToJson();
            cfg.WithOwner();
            //cfg.OwnsMany(x=>x.UiSettings, pcfg=>pcfg.WithOwner());
            cfg.OwnsMany(x=>x.DeviceSettings, pcfg=>pcfg.WithOwner());
        }  
    }
```

And then I try to load users:
```C#
    await DbContext.Users.FirstOrDefaultAsync(x=>x.Name=="someusername");
```

I get ```Index was out of range. Must be non-negative and less than the size of the collection. Parameter "Index" ```
So now my question is how do I manage schema changes to classes saved as JSON columns?

EF Core version: 8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11 23H2
IDE: Visual Studio 2022 17.4, Jetbrains Rider

**Comment by ajcvickers** [comment] 2024-01-03 14:25
Duplicate of #32301

**Closed by ajcvickers** 2024-01-03 14:25 UTC
Labels: customer-reported
