### ISSUE TITLE
Add tag in add, update and delete operations

### ISSUE THREAD

**Issue by CwjXFH** [dotnet/efcore#27481] opened 2022-02-21 05:52 UTC
EFCore support [QueryTag](https://docs.microsoft.com/en-us/ef/core/querying/tags), I want to add a tag when executing add, update or delete operations, it is possible in EFCore3.1+?

Thanks!

**Comment by roji** [comment] 2022-02-21 11:51
Duplicate of #14078

**Closed** 2022-10-16 20:27 UTC
Labels: closed-duplicate, customer-reported
