### ISSUE TITLE
InvalidOperationException when projection is used with distinct and where condition using related table

### ISSUE THREAD

**Issue by jmalczak** [dotnet/efcore#24079] opened 2021-02-07 12:17 UTC
After migration from EF Core 3 to 5 following code throws InvalidOperationException.

### Repro source code
```c#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            using var db = new Context();

            // Works fine
            var result = db.OperatorTaskGroup
                .Where(otg =>
                    otg.Id == new Guid("9c51346c-bb19-4f45-247b-08d8840cd73a"))
                .Select(otg => new
                {
                    otg.Id, 
                    Sales = otg.OperatorTaskGroupSales.Select(ots => new
                    {
                        ots.SaleId
                    })
                })
                .Distinct()
                .ToList();
            
            // Fails in EF Core 5.0.2
            var result2 = db.OperatorTaskGroup
                .Where(otg =>
                    otg.Id == new Guid("9c51346c-bb19-4f45-247b-08d8840cd73a") && 
                    otg.Delivery.DeliveryNumber != "test")
                .Select(otg => new
                {
                    otg.Id, 
                    Sales = otg.OperatorTaskGroupSales.Select(ots => new
                    {
                        ots.SaleId
                    })
                })
                .Distinct()
                .ToList();
        }

        public class Context : DbContext
        {
            private static ILoggerFactory LoggerFactory => new ServiceCollection()
                .AddLogging(l => l.AddConsole().SetMinimumLevel(LogLevel.Trace)).BuildServiceProvider()
                .GetRequiredService<ILoggerFactory>();

            public DbSet<OperatorTaskGroupSale> OperatorTaskGroupSale { get; set; } = null!;
            public DbSet<OperatorTaskGroup> OperatorTaskGroup { get; set; } = null!;
            public DbSet<Delivery> Delivery { get; set; } = null!;

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder
                    .UseSqlServer("Server=.;Initial Catalog=easystorage;User Id=sa;Password=Admin123")
                    .EnableSensitiveDataLogging()
                    .UseLoggerFactory(LoggerFactory);
            }
        }

        public class OperatorTaskGroupSale
        {
            public Guid Id { get; set; }
            public Guid OperatorTaskGroupId { get; set; }
            public Guid SaleId { get; set; }
        }

        public class OperatorTaskGroup
        {
            public Guid Id { get; set; }
            public virtual List<OperatorTaskGroupSale> OperatorTaskGroupSales { get; set; }
            public Guid? DeliveryId { get; set; }
            public Delivery Delivery { get; set; }
        }

        public class Delivery
        {
            public Guid Id { get; set; }
            public string DeliveryNumber { get; set; }
        }
    }
}

```

### Stack trace

```
System.InvalidOperationException: Unable to translate collection subquery in projection since the parent query doesn't project key columns of all of it's tables which are required to generate results on client side. This can happen when trying to correlate on keyless entity or when using 'Distinct' or 'GroupBy' operations without projecting all of the key columns.
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyCollectionJoin(Int32 collectionIndex, Int32 collectionId, Expression innerShaper, INavigationBase navigation, Type elementType, Boolean splitQuery)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitNew(NewExpression node)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConsoleApp1.Program.Main(String[] args) in /Volumes/data/development/easystorage/src/ConsoleApp1/ConsoleApp1/Program.cs:line 36
```

### SQL Generated by EF Core 3.1.11

```sql
      SELECT [t].[Id], [o0].[SaleId], [o0].[Id]
      FROM (
          SELECT DISTINCT [o].[Id]
          FROM [OperatorTaskGroup] AS [o]
          LEFT JOIN [Delivery] AS [d] ON [o].[DeliveryId] = [d].[Id]
          WHERE ([o].[Id] = '9c51346c-bb19-4f45-247b-08d8840cd73a') AND (([d].[DeliveryNumber] <> N'test') OR [d].[DeliveryNumber] IS NULL)
      ) AS [t]
      LEFT JOIN [OperatorTaskGroupSale] AS [o0] ON [t].[Id] = [o0].[OperatorTaskGroupId]
      ORDER BY [t].[Id], [o0].[Id]
```

### Provider and version information

EF Core version: 5.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 5.0

**Comment by ajcvickers** [comment] 2021-02-08 17:41
@maumar to find dupe.

**Comment by santosh-kh** [comment] 2021-02-09 08:17
@ajcvickers : Any work around for this issue?

**Comment by jmalczak** [comment] 2021-02-09 09:36
@santosh-kh you can do client side Distinct, just do ToList before Distinct. This way you will pull more data from the server but you avoid exception.

**Comment by santosh-kh** [comment] 2021-02-09 10:09
> @santosh-kh you can do client side Distinct, just do ToList before Distinct. This way you will pull more data from the server but you avoid exception.

Yeah, I can do that as temporary for moving with upgrade. But with the data it's fetching this is not suitable for me.

**Comment by maumar** [comment] 2021-02-12 09:40
dupe of https://github.com/dotnet/efcore/issues/22049

**Closed** 2022-10-16 19:22 UTC
Labels: customer-reported
