### ISSUE TITLE
Refresh schema on each request

### ISSUE THREAD

**Issue by LeoCavalheiro** [dotnet/efcore#15402] opened 2019-04-18 18:32 UTC
I'm developing a multi-tenant API, using schema to separate each company. But as I register the DBContext in startup.cs, I can not update Schema in the requisitions.
On the first request, I write the schema using "HasDefaultSchema" in the "OnModelCreating" method of "DBContext", and everything works fine. From the second requisition that the problems begin:
1) The "OnModelCreating" method does not execute (because the DBContext is already registered), which does not change the Schema, keeping the same of the first request.
2) I was able to force the execution of the "OnModelCreating" method (calling through the "OnConfiguring" method) on all the requests, but it still does not update the schema.

Is there any way to update Schema on each request, or is it a limitation of EFCore?
I do not want to change the registry for the repository builder, since I do not want to lose transaction control for more than one repository.

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.Npgsql
Operating system: Developing Win 10 (Compile for Linux)
IDE: Visual Studio 2019 16.0.1

Thank's!

**Comment by ajcvickers** [comment] 2019-04-18 23:22
Duplicate of #12939 and see https://docs.microsoft.com/en-us/ef/core/modeling/dynamic-model

**Closed** 2022-10-16 14:18 UTC
Labels: customer-reported
