### ISSUE TITLE
Invalid migration Code and Snapshot code

### ISSUE THREAD

**Issue by cothman** [dotnet/efcore#33125] opened 2024-02-20 14:09 UTC
When adding or deleting a migration using dotnet-ef tool, the migration code generated and the snapshot code contains an extra ```using ;``` that breaks the build.
Everytime we have to delete this line of code when adding/deleting a migration

### Provider and version information

EF Core version: 6
Database provider: PostgreSQL
Target framework: .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.9

**Comment by ajcvickers** [comment] 2024-02-21 08:36
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2024-03-06 19:47
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2024-03-06 19:47 UTC
Labels: customer-reported
