### ISSUE TITLE
Same codes, different result after updating entity framework core

### ISSUE THREAD

**Issue by BitBridgeCoin** [dotnet/efcore#10439] opened 2017-11-30 07:50 UTC
I run the same pieces of code except for packages, and got different results. Anything wrong?

Exception Message = "Sequence contains more than one element"
Stack trace: at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)\r\n 

Previous packages:
```xml
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel.Https" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0" />
```
Update one:
```xml
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
```

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.
```c#
                var buildingInfo = (from bu in _context.Building
                                    join bt in _context.BuildingType on (bu.BuildingTypeId ?? 0) equals bt.Id into BuildingType2
                                    from bt2 in BuildingType2.DefaultIfEmpty()
                                    join os in _context.OtherStatistic on bu.OtherStatisticId equals os.Id into OtherStatistic2
                                    from os2 in OtherStatistic2.DefaultIfEmpty()
                                    join ad in _context.Address on bu.AddressId equals ad.Id into Address2
                                    from ad2 in Address2.DefaultIfEmpty()
                                    join ids in _context.District on ad2.DistrictId equals ids.Id into District2
                                    from ids2 in District2.DefaultIfEmpty()
                                        //join bf in _context.BuildingFeatures on bu.Id equals bf.BuildingId
                                        //join fe in _context.Features on bf.FeaturesId equals fe.Id
                                    where bu.Id == id
                                    select (new
                                    {
                                        Id = bu.Id,
                                        BuildingNameEng = bu.BuildingNameEng,
                                        //StreetNameEng = ad2.StreetNameEng,
                                        StreetNameEng = bu.StreetNameEng,
                                        Address1 = ad2.Address1,
                                        Address2 = ad2.Address2,
                                        TotalUnit = bu.TotalUnit,
                                        BuiltYear = bu.BuiltYear,
                                        MgmtPhone = bu.MgmtPhone,
                                        BuildingType = bt2==null ? "": bt2.Name, //Note: not bt2.name, or there will be a null error
                                        FloorPerBlock = os2.FloorPerBlock,
                                        UnitPerBlock = os2.UnitPerBlock,
                                        UnitRange = os2.UnitRange,
                                        Features = features,
                                        TotalBuildingBlocks = bu.TotalBlock,
                                        DistrictName = ids2.Name,
                                        HksarDistrictNameEng = ids2.HksarDistrictNameEng,
                                        StreetNameEng2 = ad2.StreetNameEng,
                                        StreetNo = ad2.StreetNo,
                                        ZipCode=ad2.ZipCode
                                        //FeaturesId = bf.FeaturesId
                                        //Features = fe.Name
                                    }))/*.SingleOrDefaultAsync()*/
                                    .GroupJoin(
                                    _context.BuildingBlock,
                                    o => o.Id,
                                    bblock => bblock.BuildingId,
                                    (o, bblock) => new { building = o, block = bblock })
                                    .ToList()
                                    .Select(r => new
                                    {
                                        Id = r.building.Id,
                                        BuildingNameEng = r.building.BuildingNameEng,
                                        //StreetNameEng = ad2.StreetNameEng,
                                        StreetNameEng = r.building.StreetNameEng,
                                        Address1 = r.building.Address1,
                                        Address2 = r.building.Address2,
                                        TotalUnit = r.building.TotalUnit,
                                        BuiltYear = r.building.BuiltYear,
                                        MgmtPhone = r.building.MgmtPhone,
                                        BuildingType = r.building.BuildingType, //Note: not bt2.name, or there will be a null error
                                        FloorPerBlock = r.building.FloorPerBlock,
                                        UnitPerBlock = r.building.UnitPerBlock,
                                        UnitRange = r.building.UnitRange,
                                        Features = features,
                                        unitcountfrompropertylisting=unitcountfrompropertylisting,
                                        TotalBuildingBlocks = r.building.TotalBuildingBlocks,
                                        DistrictName=r.building.DistrictName,
                                        HksarDistrictNameEng=r.building.HksarDistrictNameEng,
                                        StreetNameEng2 = r.building.StreetNameEng2,
                                        StreetNo = r.building.StreetNo,
                                        ZipCode = r.building.ZipCode,
                                        bblockids = r.block.Select(bblock => new
                                        {
                                            bbid = bblock.BuildingBlockId,
                                        }).ToList()
                                    }).SingleOrDefault();
```

### Further technical details
IDE: visual studio 2017

**Comment by ajcvickers** [comment] 2017-12-01 20:46
@Jingkun-Hu Unfortunately there isn't enough information here to diagnose the issue. Could you post:
* Full stack trace for the exception
* A runnable project/solution or code listing that reproduces what you are seeing.

**Comment by ajcvickers** [comment] 2017-12-11 19:05
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 12:01 UTC
Labels: closed-could-not-reproduce
