### ISSUE TITLE
Add configuration files for dotnet ef

### ISSUE THREAD

**Issue by timia2109** [dotnet/efcore#33005] opened 2024-02-05 14:06 UTC
For some more complicated projects (such as a project with a core library and a web API), additional configuration is required for the dotnet ef tools. For example, I might need the following line to add a new migration:
```bash
dotnet ef migrations add "MyMigration" --startup-project ./API --project ./Core --namespace "MyProject.Database" --context "MyContext"
```
For me this is very unconvincing. I started writing scripts to fill in these parameters automatically. But the problem with that is that they have to be copied to every git repo.

One solution would be to create a convenient way to store these parameters for the hole project in a configuration file, where the dotnet ef tools would automatically load the information and set these values for execution. This would reduce the repository footprint and provide a conventional way to configure the dotnet ef tools.

If this feature request is accepted, I could implement this feature.

**Comment by ajcvickers** [comment] 2024-02-07 10:55
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/4381

**Closed** 2024-02-14 14:05 UTC
Labels: type-enhancement, customer-reported
