### ISSUE TITLE
HasConversion to a nullable Type does not seem to work

### ISSUE THREAD

**Issue by YanicHoegger** [dotnet/efcore#33645] opened 2024-04-30 13:47 UTC
Hello 

I would like to change a property of `double` into a `double?` column. My idea of doing so would be through a converter. But when I run the `dotnet ef Migrations add` command it still creates a column with `nullable: false`. How can I make a nullable column through the fluent api? I also tried to set `IsRequired(false)` but that throws an exception.

Here is the DataContext i was trying:
```C#
namespace EfCoreNaN;

public class MyContext : DbContext
{
    public DbSet<Entity> Entities { get; set; }
    
    protected sealed override void OnConfiguring(DbContextOptionsBuilder options)
    {
        options.UseSqlServer("Server=(localdb)\\test;Database=Test;Trusted_Connection=True;MultipleActiveResultSets=true");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        
        var valueConverter = new ValueConverter<double, double?>(x => ConvertToProvider(x), x => ConvertFromProvider(x));
        modelBuilder.Entity("EfCoreNaN.Entity")
            .Property(nameof(Entity.NullableValue))
            .HasConversion(valueConverter);

        modelBuilder.Entity("EfCoreNaN.Entity")
            .Property(nameof(Entity.StringValue))
            .HasConversion(new ValueConverter<double, string>(x => x.ToString(CultureInfo.InvariantCulture), x => double.Parse(x)));
    }

    private double ConvertFromProvider(double? value)
    {
        return value ?? double.NaN;
    }

    private static double? ConvertToProvider(double value)
    {
        return double.IsNaN(value) ? null : value;
    }
}

public class Entity
{
    [Key]
    public int Id { get; set; }
    public double NullableValue { get; set; }
    public double StringValue { get; set; }
}
```

And that is the generated code:
```C#
migrationBuilder.CreateTable(
                name: "Entities",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    NullableValue = table.Column<double>(type: "float", nullable: false),
                    StringValue = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Entities", x => x.Id);
                });
```

EF Core version: 8.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: W10
IDE: Visual Studio 2022 17.8.6 & JetBrains Rider 2024.1.1 

[Solution as .zip](https://github.com/dotnet/efcore/files/15165235/EfCoreNaN.zip)

**Comment by ajcvickers** [comment] 2024-04-30 13:55
Duplicate of #13850. See also #24685.

**Closed by ajcvickers** 2024-04-30 13:55 UTC
Labels: customer-reported

**Comment by alandryz83** [comment] 2024-05-05 22:42
> Hello 
> 
> 
> 
> I would like to change a property of `double` into a `double?` column. My idea of doing so would be through a converter. But when I run the `dotnet ef Migrations add` command it still creates a column with `nullable: false`. How can I make a nullable column through the fluent api? I also tried to set `IsRequired(false)` but that throws an exception.
> 
> 
> 
> Here is the DataContext i was trying:
> 
> ```C#
> 
> namespace EfCoreNaN;
> 
> 
> 
> public class MyContext : DbContext
> 
> {
> 
>     public DbSet<Entity> Entities { get; set; }
> 
>     
> 
>     protected sealed override void OnConfiguring(DbContextOptionsBuilder options)
> 
>     {
> 
>         options.UseSqlServer("Server=(localdb)\\test;Database=Test;Trusted_Connection=True;MultipleActiveResultSets=true");
> 
>     }
> 
> 
> 
>     protected override void OnModelCreating(ModelBuilder modelBuilder)
> 
>     {
> 
>         base.OnModelCreating(modelBuilder);
> 
>         
> 
>         var valueConverter = new ValueConverter<double, double?>(x => ConvertToProvider(x), x => ConvertFromProvider(x));
> 
>         modelBuilder.Entity("EfCoreNaN.Entity")
> 
>             .Property(nameof(Entity.NullableValue))
> 
>             .HasConversion(valueConverter);
> 
> 
> 
>         modelBuilder.Entity("EfCoreNaN.Entity")
> 
>             .Property(nameof(Entity.StringValue))
> 
>             .HasConversion(new ValueConverter<double, string>(x => x.ToString(CultureInfo.InvariantCulture), x => double.Parse(x)));
> 
>     }
> 
> 
> 
>     private double ConvertFromProvider(double? value)
> 
>     {
> 
>         return value ?? double.NaN;
> 
>     }
> 
> 
> 
>     private static double? ConvertToProvider(double value)
> 
>     {
> 
>         return double.IsNaN(value) ? null : value;
> 
>     }
> 
> }
> 
> 
> 
> public class Entity
> 
> {
> 
>     [Key]
> 
>     public int Id { get; set; }
> 
>     public double NullableValue { get; set; }
> 
>     public double StringValue { get; set; }
> 
> }
> 
> ```
> 
> 
> 
> And that is the generated code:
> 
> ```C#
> 
> migrationBuilder.CreateTable(
> 
>                 name: "Entities",
> 
>                 columns: table => new
> 
>                 {
> 
>                     Id = table.Column<int>(type: "int", nullable: false)
> 
>                         .Annotation("SqlServer:Identity", "1, 1"),
> 
>                     NullableValue = table.Column<double>(type: "float", nullable: false),
> 
>                     StringValue = table.Column<string>(type: "nvarchar(max)", nullable: false)
> 
>                 },
> 
>                 constraints: table =>
> 
>                 {
> 
>                     table.PrimaryKey("PK_Entities", x => x.Id);
> 
>                 });
> 
> ```
> 
> 
> 
> EF Core version: 8.0.4
> 
> Database provider: Microsoft.EntityFrameworkCore.SqlServer
> 
> Target framework: .NET 8.0
> 
> Operating system: W10
> 
> IDE: Visual Studio 2022 17.8.6 & JetBrains Rider 2024.1.1 
> 
> 
> 
> [Solution as .zip](https://github.com/dotnet/efcore/files/15165235/EfCoreNaN.zip)
> 
>
