### ISSUE TITLE
EF migration creates designer.cs file with compile error

### ISSUE THREAD

**Issue by vsmahesh** [dotnet/efcore#11775] opened 2018-04-23 08:42 UTC
`dotnet ef migrations add <name>` command generates  the cs and designer.cs files. However the `dotnet ef database update` shows error Build failed. On further investigation it is found that the second line of the designer file & the ModelSnapshot.cs file are the culprit - `using ;`

### Steps to reproduce
Create a migration using the cli - `dotnet ef migrations add <name>` 
Try to apply it in the database using the command - `dotnet ef database update` 

### Further technical details
Entity Framework Core .NET Command Line Tools
2.0.0-rtm-26452
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system:  Windows 10
IDE: VS Code

**Comment by smitpatel** [comment] 2018-04-23 15:47
Duplicate of #2467

Fixed in 2.1.0-preview1

**Closed** 2022-10-16 12:20 UTC
