### ISSUE TITLE
EF 6 Support for .net framework core

### ISSUE THREAD

**Issue by thiruppathik-tw** [dotnet/efcore#26648] opened 2021-11-12 12:21 UTC
Right now Entity Framework version 3.1.18 is the latest for .net framework core applications. Problem with 3.1.18 is using older sqlite v3 and there are few risks reported. Any release plan for .net framework core support with latest sqlite v3 latest versions?

**Comment by ajcvickers** [comment] 2021-11-16 09:55
@thiruppathik-tw You should be able to update the underlying native SQLite packages by explicitly including them in your csproj.

**Comment by ajcvickers** [comment] 2021-11-28 14:11
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:14 UTC
Labels: closed-no-further-action, customer-reported
