### ISSUE TITLE
asp.net core 6 with efcore not working in release mode

### ISSUE THREAD

**Issue by selvam920** [dotnet/efcore#24999] opened 2021-05-29 10:11 UTC
i'm getting below error in win 64 release mode.
in development mode is working fine

The type initializer for 'Microsoft.EntityFrameworkCore.Sqlite.Query.Internal.SqliteMathTranslator' threw an exception.An item with the same key has already been added. Key: Int32 Abs(Int32)"

**Comment by roji** [comment] 2021-05-29 10:21
@selvam920 which version of EF Core are you using, and which version of .NET are you targetting? Can you please post your csproj?

**Comment by selvam920** [comment] 2021-05-29 10:33
dotnet version: 6.0.100-preview.4.21255.9
targeting: .net 6.0

**Comment by selvam920** [comment] 2021-05-29 10:33
<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.0-preview.4.21253.5" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="6.0.0-preview.4.21253.5" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.0-preview.4.21253.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.0-preview.4.21253.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.0-preview.4.21253.1">

**Comment by selvam920** [comment] 2021-05-29 10:39
![image](https://user-images.githubusercontent.com/20491308/120067254-2c8e0900-c098-11eb-8148-03f4174e06af.png)

**Comment by roji** [comment] 2021-05-29 12:00
Any chance you can put together a minimal code sample (e.g. console program) which reproduces this?

**Comment by selvam920** [comment] 2021-05-29 15:21
i don't have minimal code, i'm rollbacking to .net 5 version

**Comment by ajcvickers** [comment] 2021-06-01 15:53
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:36 UTC
Labels: closed-could-not-reproduce, customer-reported
