### ISSUE TITLE
"auto-generated" doc-tag in migrations

### ISSUE THREAD

**Issue by amosonn** [dotnet/efcore#20691] opened 2020-04-20 14:05 UTC
Currently, when generating migrations using the EF tool (`dotnet-ef migrations add <name> ...`), two files are automatically generated: `<timestamp>_<name>.cs` and `<timestamp>_<name>.Designer.cs`. Whereas the second has a leading line `// <auto-generated />`, which tells tooling such as stylecop to skip this file, the first one doesn't, which requires adding it manually to avoid warnings/errors. It would be nice if the first one had it as well.

Version 3.1.3, archlinux.

**Comment by ajcvickers** [comment] 2020-04-20 15:32
Duplicate of #10203

**Closed** 2022-10-16 18:21 UTC
Labels: customer-reported
