### ISSUE TITLE
Provide option to use varchar instead of nvarchar for JSON columns

### ISSUE THREAD

**Issue by RushuiGuan** [dotnet/efcore#33643] opened 2024-04-30 03:14 UTC
For sql server database or table columns with utf8 collation, nvarchar is not needed.  But it seems that there is no way to configure json columns with varchar data type.  Would be nice to have that option.

Thanks

**Comment by roji** [comment] 2024-04-30 05:46
Duplicate of #28452

**Closed by roji** 2024-04-30 05:46 UTC
Labels: type-enhancement, customer-reported
