### ISSUE TITLE
EF Core 2.1.1 group by with Include generates wrong query

### ISSUE THREAD

**Issue by AdGalesso** [dotnet/efcore#12475] opened 2018-06-27 04:13 UTC
I've just updated my EF Core to 2.1.1 to get the Group By and it is working for simple queries like this one:

```cs
    var response = _dbContext.Capacities
        .GroupBy(g => g.AgencyId)
        .Select(g => new { g.Key, Sum = g.Sum(c => c.DefaultCapacity) })
        .ToList();
```

This generates this SQL:

```sql
    SELECT [g].[AgencyId]             AS [Key],
           SUM([g].[DefaultCapacity]) AS [Sum]
    FROM   [Capacity] AS [g]
    GROUP  BY [g].[AgencyId]
```

That's perfect. However, when I try to include a table to do a inner join:

```cs
    var response = _dbContext.Capacities
        .Include(c => c.Agency)
        .GroupBy(g => g.AgencyId)
        .Select(g => new { g.Key, Sum = g.Sum(c => c.DefaultCapacity), Name = g.Max(c => c.Agency.AgencyName) })
        .ToList();
```

It gets lost and generates this query:

```sql
    SELECT [c].[CapacityId],
           [c].[AgencyId],
           [c].[CreatedBy],
           [c].[CreatedOn],
           ...
           [c.Agency].[AgencyId],
           [c.Agency].[ABN],
           [c.Agency].[ActiveFlag],
           ...
    FROM   [Capacity] AS [c]
           INNER JOIN [Agency] AS [c.Agency]
             ON [c].[AgencyId] = [c.Agency].[AgencyId]
    ORDER  BY [c].[AgencyId]
```
Am I doing something wrong or Group By is still not being translated correctly in EF Core?

**Comment by smitpatel** [comment] 2018-06-27 04:41
Duplicate of #12173

**Comment by AdGalesso** [comment] 2018-06-27 05:34
Is it a duplicate? In #12173 the projection was unnecessary, but what if it is? In my case, I join the table to get a further column, the query should be translated to this:

```sql
SELECT  
	c.AgencyId,
	SUM(C.DefaultCapacity) AS [Capacity],
	MAX(A.AgencyName) AS [AgencyName]
FROM aCapacity C
	INNER JOIN Agency A ON C.AgencyId = A.AgencyId
GROUP BY c.AgencyId
```

Tried a join and still doesn't work:

```cs
            var response = (from c in _dbContext.Capacities
                            join a in _dbContext.Agencies
                                 on c.AgencyId equals a.AgencyId
                            group c by c.AgencyId)
                            .Select(g => new { g.Key, Sum = g.Sum(c => c.DefaultCapacity), Name = g.Max(c => c.Agency.AgencyName) })
                            .ToList();
```

**Comment by AdGalesso** [comment] 2018-06-27 06:20
@smitpatel Ok got it, cannot Include, but since I need data from both tables I decided to inner join, and worked, just a side note of a wired thing:

This is the Linq:

```cs
var query = (from c in _dbContext.Capacities
                join a in _dbContext.Agencies
                    on c.AgencyId equals a.AgencyId
                group c by new { c.AgencyId, c.Agency.AgencyName } into g
                select new { g.Key.AgencyId, g.Key.AgencyName, Capacity = g.Sum(n => n.DefaultCapacity) });
```

That generated this query:

```sql
SELECT [c].[AgencyId],
       [c.Agency].[AgencyName],
       CAST(SUM([c].[DefaultCapacity]) AS bigint) AS [Capacity]
FROM   [Capacity] AS [c]
       INNER JOIN [Agency] AS [c.Agency]
         ON [c].[AgencyId] = [c.Agency].[AgencyId]
       INNER JOIN [Agency] AS [a]
         ON [c].[AgencyId] = [a].[AgencyId]
GROUP  BY [c].[AgencyId],
          [c.Agency].[AgencyName]
```

As you can see... INNER JOIN 2x

**Comment by smitpatel** [comment] 2018-06-27 17:41
@AdGalesso - I marked as duplicate since in the original query, you are doing group by and aggregate operation which does not project out any entity type so `Include` is effectively ignored. `Include` is used to load related data only. Navigations used inside the query are automatically expanded and does not require any `Include` operator.

The kind of query you would want is described in https://github.com/aspnet/EntityFrameworkCore/issues/11813 though it is not server translated in current release. The work-around or to get a server-eval query is the pattern which you used in your query (i.e. custom key/element selector depending on where you need the property through navigation appearing). The reason you are seeing 2x inner join is same as last paragraph. When you use navigation in the query EF will expand it automatically hence the manual join you added is redundant. You can safe remove manual join and query will work just fine.

**Comment by AdGalesso** [comment] 2018-06-28 04:55
@smitpatel thank you for the time/response. Perfect, Used to procs and EF6 didn't knew about the automatic expand. Removed the join and the query is perfect.

**Closed** 2022-10-16 13:16 UTC
Labels: closed-duplicate, customer-reported
