### ISSUE TITLE
Query: invalid sql for query with groupby aggregate pushdown, projecting Lenght property on top of that

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12577] opened 2018-07-06 01:31 UTC
query:

```cs
                var query = ctx.Orders.GroupBy(e => e.CustomerID)
                        .Where(g => g.Count() > 10)
                        .Select(g => g.Key)
                        .OrderBy(t => t)
                        .Take(20)
                        .Skip(4)
                        .Select(e => e.Length);

                var result = query.ToList();
```

generated sql:

```sql
SELECT [t].[c]
FROM (
    SELECT TOP(@__p_0) CAST(LEN([e].[CustomerID] AS [Key]) AS int) AS [c], [e].[CustomerID] AS [Key]
    FROM [Orders] AS [e]
    GROUP BY [e].[CustomerID]
    HAVING COUNT(*) > 10
    ORDER BY [c0]
) AS [t]
ORDER BY [t].[Key]
OFFSET @__p_1 ROWS
```

**Comment by smitpatel** [comment] 2018-07-27 19:57
Duplicate of #12826

**Closed** 2022-10-16 13:17 UTC
