### ISSUE TITLE
How to share an InMemory Db between a read and write context

### ISSUE THREAD

**Issue by czifro** [dotnet/efcore#10609] opened 2017-12-27 00:48 UTC
I have am working on a project that needs to support a read db and write db. I have decided to create two contexts accordingly. I have a Web API to interact with the db. I have an endpoint creates a user and another that fetches a user by id. The issue I'm running into is on the Development server, and Local instances, where an InMemory Db is used since development is rather rapid. The issue lies with the read context not giving me the data I stored with the write context. It thinks the table is empty. Upon further examination using the debugger, I am able to navigate and find the "missing" data. I'm not sure what is wrong.

### Steps to reproduce
Here is an illustration of what I have in my project

```c#
public class WriteContext : IdentityDbContext<User>
{
  public WriteContext(DbContextOptions<WriteContext> options) : base(options) {}
}

public class ReadContext : IdentityDbContext<User>
{
  public ReadContext(DbContextOptions<ReadContext> options) : base(options) {}
}

public class UserController : Controller
{
  private readonly WriteContext _write;
  private readonly ReadContext _read;

  // constructor injection here

  // attributes...
  public IActionResult Post(UserModel model)
  {
    var user = // map model to User
    _write.Users.Add(user);
    _write.SaveChanges();
    return Ok(user);
  }

  // attributes...
  public IActionResult Get(string userId)
  {
    var user = _read.Users.SingleOrDefault(x => x.Id == userId);
    return Ok(user);
  }
}

public class Startup
{
  public void ConfigureServices(IServiceCollection services)
  {
    // other stuff...

    services.AddDbContext<WriteContext>(options => options.UseInMemoryDatabase("MemDb"));
    services.AddDbContext<ReadContext>(options => options.UseInMemoryDatabase("MemDb"));

    // other stuff
  }

  // other stuff
}
```

Add a user via write context and then try and fetch user via read context.

### Further technical details
EF Core version: 2.0.1
Database Provider: InMemory
Operating system: macOS Sierra
IDE: Jetbrains Rider 2017.2

**Comment by ajcvickers** [comment] 2017-12-27 23:42
Duplicate of #10318, which is itself a duplicate of the root cause in #9613.

**Closed** 2022-10-16 12:04 UTC
Labels: closed-duplicate
