### ISSUE TITLE
blazor server app cannot compile

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#19613] opened 2020-01-16 19:15 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/884683/blazor-server-app-cannot-compile.html)._

---
[regression] [worked-in:3.1.0]
Create a new project
choose blazor app (server side).  I left the default name.  Hit Create.
change authentication to individual user accounts and hit Ok
I told it to ignore the open warnings
I gave it permission to close the blazorapp1.csproj and reopen it.
I hit Ctrl-Shift-B to compile and immediately get the Unable to find package errors for all the entityframeworkcore packages.
I open the nuget package manager adn the packages folder in the project.  I see its having trouble with microsoft.entityframeworkcore.tools (3.1.1) which the package manager says is installed.  
the updates tab says no packages need updates.

---
#### Visual Studio Feedback System on 1/14/2020, 11:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2020-01-17 17:40
We think this issue was caused by inconsistent state while new packages were being uploaded. This is something that is being looked at for future releases. I'm closing this, but if it still repros for you then please comment and we can reopen and do some more investigation.

**Closed** 2022-10-16 18:06 UTC
Labels: closed-no-further-action, customer-reported
