### ISSUE TITLE
Include Client Side evaluation analyzer rule set in EntitiyFrameworkCore Analyzers

### ISSUE THREAD

**Issue by bharatdwarkani** [dotnet/efcore#17994] opened 2019-09-23 06:52 UTC
Client-Side Evaluation of Queries

Avoiding Client SIde Evaluation of queries using Analyzers

**Comment by smitpatel** [comment] 2019-09-23 17:01
@bharatdwarkani - Can you elaborate more what feature you are asking for?

**Comment by smitpatel** [comment] 2019-09-27 21:48
@bharatdwarkani - Also is this for 2.1/2.2 release or 3.0 release as 3.0 disallow client side evaluation unless in top level projection.

**Comment by ajcvickers** [comment] 2019-10-04 16:18
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:43 UTC
Labels: closed-could-not-reproduce, customer-reported
