### ISSUE TITLE
No parameterless constructor was found on 'ClientsContext'. Either add a parameterless constructor to 'ClientsContext' or add an implementation of 'IDbContextFactory<ClientsContext>' in the same assembly as 'ClientsContext'.

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#8024] opened 2017-03-29 14:51 UTC
Describe what is not working as expected.
I am using a window service with Autofac DI and when I run ```Add-Migration TestDD1InitialMigration``` I get error 
```
No parameterless constructor was found on 'ClientsContext'. Either add a parameterless constructor to 'ClientsContext' or add an implementation of 'IDbContextFactory<ClientsContext>' in the same assembly as 'ClientsContext'.
```

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment] 2017-03-29 17:06
@pantonis Can you post the code of your DbContext class?

**Comment by pantonis** [comment] 2017-03-29 17:21
````
using Microsoft.EntityFrameworkCore;

namespace Test.Infrastructure.EntityFramework
{
    public class ClientContext : DbContext
    {
        public ClientContext(DbContextOptions<ClientContext> options)
                : base(options)
        {
            Database.Migrate();
        }

        public DbSet<Client> Clients { get; set; }
        public DbSet<Operation> Operations { get; set; }
    }
}

````

**Comment by ajcvickers** [comment] 2017-03-31 23:05
@pantonis This usually means that tooling is unable to use your Startup class for some reason. The exception message in this case is confusing; we need to generate better feedback for this case.

@bricelam I was unable to find the duplicate for this, so assigning to you to de-dupe as necessary.

**Comment by ajcvickers** [comment] 2017-03-31 23:07
@pantonis Also, calling Database.Migrate in your context constructor is likely to cause issues both because it is attempting to use the context before it is fully constructed, and because it will interfere with tooling which is also trying to do Migrations things at the same time.

**Comment by bricelam** [comment] 2017-04-01 00:25
Dupe of #7264

**Comment by pantonis** [comment] 2017-04-01 06:24
For anyone out there having the same problem I managed to resolve it using an IDbContextFactory

```
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.Configuration;

namespace Test.Infrastructure.EntityFramework
{
    public class ClientContextFactory : IDbContextFactory<ClientContext>
    {
        private IConfigurationRoot configuration;

        public ClientContextFactory()
        {
            var builder = new ConfigurationBuilder()
           .SetBasePath(System.AppContext.BaseDirectory)
           .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);

            configuration = builder.Build();
        }

        public ClientContext Create(DbContextFactoryOptions options)
        {
            var optionsBuilder = new DbContextOptionsBuilder<ClientContext>();
            optionsBuilder.UseSqlServer(configuration.GetConnectionString("DefaultConnection"), m => { m.EnableRetryOnFailure(); });

            return new ClientContext(optionsBuilder.Options);
        }
    }
}
```

**Closed** 2022-10-16 10:59 UTC
