### ISSUE TITLE
Entity tracking

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/efcore#26819] opened 2021-11-24 14:12 UTC
Hello, 

I'm wondering why I'm getting this error when my Dbcontext is set to NoTracking.

Thanks.
![image](https://user-images.githubusercontent.com/23618436/143254037-c2aca0e0-f3fe-436c-a91f-80e51d7c6ea2.png)

**Comment by ajcvickers** [comment] 2021-11-24 16:47
@Julien-Marpault See [Identity Resolution](https://docs.microsoft.com/en-us/ef/core/change-tracking/identity-resolution). If that doesn't help, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Julien-Marpault** [comment] 2021-11-24 18:00
I already tested both

````
 options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTrackingWithIdentityResolution);
  options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
````
But it doesn't changed anything.

By default I use 
````
 options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTrackingWithIdentityResolution);
````

I tweaked a bit my code to take this in count but I was a bit surprised by this tracking error in a context which is not meant to be tracked.

**Comment by ajcvickers** [comment] 2021-12-03 12:21
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:16 UTC
Labels: closed-could-not-reproduce, customer-reported
