### ISSUE TITLE
Context.ChangeTracker in EFCore 7 is "losing" added entities

### ISSUE THREAD

**Issue by rafalgradziel** [dotnet/efcore#30787] opened 2023-04-28 12:23 UTC
## File a bug

For a code which was working with EF6, but migrated to EFCore (DB schema, FK keys, constraints etc is exactly the same), I am experiencing strange **Context.ChangeTracking** misbehaviour.
For example, after my code objects initialization like this:

```C#
                // prepare
                var kontakt = kundeRepo.GetDummyKunde();

                var vorgang = vorgangRepo.Create();
                vorgang.Kontakt = kontakt;
                
                var beleg = _context.Belege.CreateInstance();
                beleg.Vorgang = vorgang;

                var ba1 = _context.BelegAdressen.CreateInstance();
                ba1.Name = "AAA";
                ba1.Kontakt = kontakt;
                var ba2 = _context.BelegAdressen.CreateInstance();
                ba2.Name = "ZZZ";
                ba2.Kontakt = kontakt;

                beleg.SetBelegAdresse(ba1);
                beleg.SetVersandAdresse(ba2);

                // save
                vorgangRepo.Add(vorgang);
```

I can see in `Context.ChangeTracker.DebugView.ShortView`:
```
Beleg {BelegId: -9223372036854774807} Added FK {BelegAdresse_AdressId: <null>} FK {VersandAdresse_AdressId: <null>} FK {VorgangId: -9223372036854774807}
BelegAdresse {AdressId: -9223372036854774807} Added FK {KontaktId: 1}
BelegAdresse {AdressId: -9223372036854774806} Added FK {KontaktId: 1}
Kontakt {KontaktId: 1} Unchanged
Vorgang {VorgangId: -9223372036854774807} Added FK {KontaktId: 1}
```
... but shortly after this call...
```C#
var entries = Context.ChangeTracker.Entries()
````

... I see missing tracking for firstly assigned "BelegAdresse":
```
Beleg {BelegId: -9223372036854774807} Added FK {BelegAdresse_AdressId: -9223372036854774807} FK {VersandAdresse_AdressId: -9223372036854774806} FK {VorgangId: -9223372036854774807}
BelegAdresse {AdressId: -9223372036854774806} Added FK {KontaktId: 1}
Kontakt {KontaktId: 1} Unchanged
Vorgang {VorgangId: -9223372036854774807} Added FK {KontaktId: 1}
```

The issue is when I assign `BelegAdresse.Kontakt` and does not appear to be related to `Beleg` <-> `BelegAdresse` FK. 
Why it is loosing information for only 1 of 2 `BelegAdresse`?

### When it is working?

If I have created only 1 `BelegAdresse` assigned to either (`Beleg.BelegAdresse`) OR (`Beleg.VersandAdresse`) OR (same `BelegAdresse` assigned together to `Beleg.BelegAdresse` and `Beleg.VersandAdresse`).
The problem starts when I create two different entries for `BelegAdresse` and assign them to `Beleg` - then ChangeTracker is going crazy.

The issue (with this DB schemat and code) worked fine on EF6.

### Include your code

Repro project is available here: https://github.com/rafalgradziel/EFCoreChangeTrackerIssue

See `ServiceTest.ScenarioOne()` for the scenario stripped down from already working EF6 project.
Also `ServiceTest.ScenarioTwo()` is a reproduction of the issue with even smaller code (I think).

### Exception and debug outputs

```
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Beleg_dbo.BelegAdresse_BelegAdresse_AdressId". The conflict occurred in database "IBOS3_Dev_EFCore_repro", table "dbo.BelegAdresse", column 'AdressId'.
```
because EFCore is trying to execute this SQL (message copied from debug output):
```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (35ms) [Parameters=[@p5='-9223372036854774807' (Nullable = true), @p6='e7339f2e-48c9-40c7-87ff-49935277469b', @p7='3' (Nullable = true), @p8='3' (Nullable = true)], CommandType='Text', CommandTimeout='30']
      SET IMPLICIT_TRANSACTIONS OFF;
      SET NOCOUNT ON;
      INSERT INTO [Beleg] ([BelegAdresse_AdressId], [BelegGuid], [VersandAdresse_AdressId], [VorgangId])
      OUTPUT INSERTED.[BelegId]
      VALUES (@p5, @p6, @p7, @p8);
```
Note `@p5='-9223372036854774807'` which is negative value, but `Context.ChangeTracking` should not loose (1 of 2 `BelegAdresse` objects) and convert that to some real ID value (>0)

### Include provider and version information

EF Core version: 7.0.5 (but tested also on 7.0 - 7.0.4)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.5.3

**Comment by ajcvickers** [comment] 2023-05-01 17:07
@rafalgradziel This no longer repros on EF8 preview 1 or later. I suspect it has the same root cause as https://github.com/dotnet/efcore/issues/29568, but it's hard to say because there is a lot of explicit state manipulation going on, coupled with lazy-loading.

**Comment by rafalgradziel** [comment] 2023-05-02 06:07
> @rafalgradziel This no longer repros on EF8 preview 1 or later. 

Not really true: on EF8 (for example: 8.0.0-preview.3.23174.2) I can not see the exception (finally) BUT saved data is incorrect.

**Expected:** 
- `Beleg.BelegAdresse_AdressId` is not null
- `Beleg.VersandAdresse_AdressId` is not null
- there must be 2 new records in table `BelegAdresse` created.

**Actual:** 
- `Beleg.BelegAdresse_AdressId` is null (incorrect)
- `Beleg.VersandAdresse_AdressId` is not null (correct)
- there is only 1 records added to table `BelegAdresse` (incorrect).

**Comment by Saibamen** [comment] 2023-05-04 12:53
Few `Debug.Assert`s were added to repository

Small note: `Sequence` table is not needed in this repro project.

**Comment by rafalgradziel** [comment] 2023-05-18 09:16
Still the same problem (tried with newest version `8.0.0-preview.4.23259.5`)

**Comment by ajcvickers** [comment] 2023-05-19 12:34
On creation of `KundeRepository`, the context starts tracking a `Kontakt` and saves it to the database. The result is that the context is tracking a `Kontakt` in the `Unchanged` state:

```
Kontakt {KontaktId: 1} Unchanged
  KontaktId: 1 PK
  KontaktGuid: 'b9fbb616-0bf8-4436-82ae-fb215794fa04'
  KundenNummer: '<not assigned>'
```

The code then queries for `Vorgang`, but doesn't find one. It instead creates a new one and tracks it in the `Added` state. It is not saved to the database. At this point the context is tracking the following:

```
Kontakt {KontaktId: 1} Unchanged
  KontaktId: 1 PK
  KontaktGuid: 'b9fbb616-0bf8-4436-82ae-fb215794fa04'
  KundenNummer: '<not assigned>'
Vorgang {VorgangId: -9223372036854774807} Added
  VorgangId: -9223372036854774807 PK Temporary
  KontaktId: 1 FK
  VorgangGuid: '1053c2d4-dd3b-4cef-b499-5f31ef420fc3'
  Belege: []
  Kontakt: {KontaktId: 1}
```

The code then attempts to find a `Kontakt` in the database using `dtoVorgang.KundeGuid` as the GUID to lookup. This GUID was never set, so the query looks for "00000000-0000-0000-0000-000000000000", which is not found. The code then calls `GetDummyKunde` instead, which returns the `Kontakt` that was saved to the database above:

So at this point, `dbVorgang` looks like this:

<img width="325" alt="image" src="https://github.com/dotnet/efcore/assets/1430078/f33461bf-89eb-463a-8785-669703b4892a">

Where the `Kontkat` is tracked as `Unchanged` and exists in the database, and the `Vorgang` has is tracked as `Added` and has not yet been saved to the database.

The code now processes the single `BelegDTO` object, which looks like this:

<img width="320" alt="image" src="https://github.com/dotnet/efcore/assets/1430078/70d074de-9ec5-4880-8c06-cdc0509c625d">

No `Beleg` is found in `vorgang.Belege` and so an instance is created an tracked by the context in the `Added` state. The context is now tracking:

```
Beleg {BelegId: -9223372036854774807} Added
  BelegId: -9223372036854774807 PK Temporary
  BelegAdresse_AdressId: <null> FK
  BelegGuid: 'cdd2baec-d216-4215-9225-25f9c0159543'
  VersandAdresse_AdressId: <null> FK
  VorgangId: <null> FK
  BelegAdresse: <null>
  VersandAdresse: <null>
  Vorgang: <null>
Kontakt {KontaktId: 1} Unchanged
  KontaktId: 1 PK
  KontaktGuid: 'b9fbb616-0bf8-4436-82ae-fb215794fa04'
  KundenNummer: '<not assigned>'
Vorgang {VorgangId: -9223372036854774807} Added
  VorgangId: -9223372036854774807 PK Temporary
  KontaktId: 1 FK
  VorgangGuid: '1053c2d4-dd3b-4cef-b499-5f31ef420fc3'
  Belege: [{BelegId: -9223372036854774807}]
  Kontakt: {KontaktId: 1}
```

At this point, the context does not know that this new `Beleg` has been added to `vorgang.Belege` because that requires `DetectChanges` to be called.

Next, `beleg.BelegAdresse` and `beleg.VersandAdresse` are set. The context is now tracking:

```
Beleg {BelegId: -9223372036854774807} Added
  BelegId: -9223372036854774807 PK Temporary
  BelegAdresse_AdressId: <null> FK
  BelegGuid: '5eb44c2c-a029-4ff0-b5d7-5fea8357a3d9' Originally 'cdd2baec-d216-4215-9225-25f9c0159543'
  VersandAdresse_AdressId: <null> FK
  VorgangId: <null> FK
  BelegAdresse: {AdressId: -9223372036854774807}
  VersandAdresse: {AdressId: -9223372036854774806}
  Vorgang: <null>
BelegAdresse {AdressId: -9223372036854774807} Added
  AdressId: -9223372036854774807 PK Temporary
  AdressGuid: 'b27429f4-dd0e-44dc-9693-622eb67cd42c' Originally '84d444cb-5c2a-4f37-871c-2f409069111e'
  KontaktId: 0 FK
  Name: 'AAA' Originally <null>
  Kontakt: <null>
BelegAdresse {AdressId: -9223372036854774806} Added
  AdressId: -9223372036854774806 PK Temporary
  AdressGuid: '6be5c782-47a3-47cf-92bc-1d788402cfef' Originally '9f75e75c-32ee-4354-b921-da2590977779'
  KontaktId: 0 FK
  Name: 'BBB' Originally <null>
  Kontakt: <null>
Kontakt {KontaktId: 1} Unchanged
  KontaktId: 1 PK
  KontaktGuid: 'b9fbb616-0bf8-4436-82ae-fb215794fa04'
  KundenNummer: '<not assigned>'
Vorgang {VorgangId: -9223372036854774807} Added
  VorgangId: -9223372036854774807 PK Temporary
  KontaktId: 1 FK
  VorgangGuid: '1053c2d4-dd3b-4cef-b499-5f31ef420fc3'
  Belege: [{BelegId: -9223372036854774807}]
  Kontakt: {KontaktId: 1}
```

This is where the "problem" occurs, since the following code:

```C#
if (beleg.BelegAdresse != null)
{
    beleg.BelegAdresse.Kontakt = vorgang.Kontakt;
    beleg.BelegAdresse.KontaktId = vorgang.Kontakt.KontaktId;
}
if (beleg.VersandAdresse != null)
{
    beleg.VersandAdresse.Kontakt = vorgang.Kontakt;
    beleg.VersandAdresse.KontaktId = vorgang.Kontakt.KontaktId;
}
```

Sets both  the `BelegAdresse` and `VersandAdresse` to point to the same `Kontakt` instance. But looking at the model:

```
Model: 
  EntityType: BelegAdresse
    Properties: 
      AdressId (long) Required PK AfterSave:Throw ValueGenerated.OnAdd
      AdressGuid (Guid) Required ValueGenerated.OnAdd
      KontaktId (long) Required FK Index ValueGenerated.OnAdd
      Name (string)
    Navigations: 
      Kontakt (Kontakt) ToPrincipal Kontakt
    Keys: 
      AdressId PK
    Foreign keys: 
      BelegAdresse {'KontaktId'} -> Kontakt {'KontaktId'} Unique Required Cascade ToPrincipal: Kontakt
    Indexes: 
      KontaktId
  EntityType: Kontakt
    Properties: 
      KontaktId (long) Required PK BeforeSave:Ignore AfterSave:Throw ValueGenerated.OnAdd
      KontaktGuid (Guid) Required ValueGenerated.OnAdd
      KundenNummer (string)
    Keys: 
      KontaktId PK
```

We can see that there is a required one-to-one relationship with cascade delete between `BelegAdresse` and `Kontakt`. This means that the given `Kontakt` can be related to only one for the two addresses, not both. When the second one is set, the relationship to the first is severed, and this causes it to be detached--it is not deleted because it has never been saved in the database, so there is nothing to delete.

None of this happens immediately, because EF has no way of knowing that the changes in the code snippet above have been made until `DetectChanges` is called. Hence, at this point the context is tracking:

```
Beleg {BelegId: -9223372036854774807} Added
  BelegId: -9223372036854774807 PK Temporary
  BelegAdresse_AdressId: <null> FK
  BelegGuid: '5eb44c2c-a029-4ff0-b5d7-5fea8357a3d9' Originally 'cdd2baec-d216-4215-9225-25f9c0159543'
  VersandAdresse_AdressId: <null> FK
  VorgangId: <null> FK
  BelegAdresse: {AdressId: -9223372036854774807}
  VersandAdresse: {AdressId: -9223372036854774806}
  Vorgang: <null>
BelegAdresse {AdressId: -9223372036854774807} Added
  AdressId: -9223372036854774807 PK Temporary
  AdressGuid: 'b27429f4-dd0e-44dc-9693-622eb67cd42c' Originally '84d444cb-5c2a-4f37-871c-2f409069111e'
  KontaktId: 1 FK Originally 0
  Name: 'AAA' Originally <null>
  Kontakt: {KontaktId: 1}
BelegAdresse {AdressId: -9223372036854774806} Added
  AdressId: -9223372036854774806 PK Temporary
  AdressGuid: '6be5c782-47a3-47cf-92bc-1d788402cfef' Originally '9f75e75c-32ee-4354-b921-da2590977779'
  KontaktId: 1 FK Originally 0
  Name: 'BBB' Originally <null>
  Kontakt: {KontaktId: 1}
Kontakt {KontaktId: 1} Unchanged
  KontaktId: 1 PK
  KontaktGuid: 'b9fbb616-0bf8-4436-82ae-fb215794fa04'
  KundenNummer: '<not assigned>'
Vorgang {VorgangId: -9223372036854774807} Added
  VorgangId: -9223372036854774807 PK Temporary
  KontaktId: 1 FK
  VorgangGuid: '1053c2d4-dd3b-4cef-b499-5f31ef420fc3'
  Belege: [{BelegId: -9223372036854774807}]
  Kontakt: {KontaktId: 1}
```

The code then goes into `AddOrUpdate` and calls `Exists` on the `Vorgang` instance. I'm not sure if `Exists` is supposed to indicate that it exists in the database, or that it exists as a tracked entity. In this case, `Exists` won't find the tracked entity because its being tracked by a temporary key value, and `Exists` doesn't handle that, and it is not in the database either, so it indicates that `Vorgang` does not exist.

`Add` is called, which calls `Add` on the `DbSet` for the `Vorgang`. This is a no-op, since its already being tracked in the `Added` state. 

Next, `OnBeforeSave` is called. This does a query which has no impact on what is being tracked. A call to `kr.Get` then gets back the instance of `Kontakt` that is already being tracked. It sets this on `Vorgang.Kontakt`, but this is a no-op because it already has that instance. The call to set the state to `EntityState.Added` is also a no-op, except that calling `context.Entry` results in a local `DetectChanges`, which means that `Vorgang` and `VorgangId` are now fixed up. So the context is now tracking:

```
Beleg {BelegId: -9223372036854774807} Added
  BelegId: -9223372036854774807 PK Temporary
  BelegAdresse_AdressId: <null> FK
  BelegGuid: '5eb44c2c-a029-4ff0-b5d7-5fea8357a3d9' Originally 'cdd2baec-d216-4215-9225-25f9c0159543'
  VersandAdresse_AdressId: <null> FK
  VorgangId: -9223372036854774807 FK Temporary
  BelegAdresse: {AdressId: -9223372036854774807}
  VersandAdresse: {AdressId: -9223372036854774806}
  Vorgang: {VorgangId: -9223372036854774807}
BelegAdresse {AdressId: -9223372036854774807} Added
  AdressId: -9223372036854774807 PK Temporary
  AdressGuid: 'b27429f4-dd0e-44dc-9693-622eb67cd42c' Originally '84d444cb-5c2a-4f37-871c-2f409069111e'
  KontaktId: 1 FK Originally 0
  Name: 'AAA' Originally <null>
  Kontakt: {KontaktId: 1}
BelegAdresse {AdressId: -9223372036854774806} Added
  AdressId: -9223372036854774806 PK Temporary
  AdressGuid: '6be5c782-47a3-47cf-92bc-1d788402cfef' Originally '9f75e75c-32ee-4354-b921-da2590977779'
  KontaktId: 1 FK Originally 0
  Name: 'BBB' Originally <null>
  Kontakt: {KontaktId: 1}
Kontakt {KontaktId: 1} Unchanged
  KontaktId: 1 PK
  KontaktGuid: 'b9fbb616-0bf8-4436-82ae-fb215794fa04'
  KundenNummer: '<not assigned>'
Vorgang {VorgangId: -9223372036854774807} Added
  VorgangId: -9223372036854774807 PK Temporary
  KontaktId: 1 FK
  VorgangGuid: '1053c2d4-dd3b-4cef-b499-5f31ef420fc3'
  Belege: [{BelegId: -9223372036854774807}]
  Kontakt: {KontaktId: 1}
```

Finally, `SaveChanges` is called. At this point a full `DetectChanges` is finally done, either by calling `Context.ChangeTracker.Entries()` or as part of `context.SaveChanges()` itself. This is where the two instances both using the same one-to-one relationship is finally detected, and the second one replaces the first, meaning that only a single instance of `BelegAdresse` remains.

**Comment by rafalgradziel** [comment] 2023-05-19 13:36
> Sets both the `BelegAdresse` and `VersandAdresse` to point to the same `Kontakt` instance. But looking at the model:
> 
> ```
> Model: 
>   EntityType: BelegAdresse
>     Properties: 
>       AdressId (long) Required PK AfterSave:Throw ValueGenerated.OnAdd
>       AdressGuid (Guid) Required ValueGenerated.OnAdd
>       KontaktId (long) Required FK Index ValueGenerated.OnAdd
>       Name (string)
>     Navigations: 
>       Kontakt (Kontakt) ToPrincipal Kontakt
>     Keys: 
>       AdressId PK
>     Foreign keys: 
>       BelegAdresse {'KontaktId'} -> Kontakt {'KontaktId'} Unique Required Cascade ToPrincipal: Kontakt
>     Indexes: 
>       KontaktId
>   EntityType: Kontakt
>     Properties: 
>       KontaktId (long) Required PK BeforeSave:Ignore AfterSave:Throw ValueGenerated.OnAdd
>       KontaktGuid (Guid) Required ValueGenerated.OnAdd
>       KundenNummer (string)
>     Keys: 
>       KontaktId PK
> ```
> 
> We can see that there is a required one-to-one relationship with cascade delete between `BelegAdresse` and `Kontakt`. This means that the given `Kontakt` can be related to only one for the two addresses, not both. When the second one is set, the relationship to the first is severed, and this causes it to be detached--it is not deleted because it has never been saved in the database, so there is nothing to delete.

@ajcvickers 
Please note `BelegConfiguration` where we explicite specify `.IsUnique(false)`:
```
entity.HasIndex(d => d.BelegAdresse_AdressId).HasDatabaseName("IX_BelegAdresse_AdressId").IsUnique(false);
entity.HasIndex(d => d.VersandAdresse_AdressId).HasDatabaseName("IX_VersandAdresse_AdressId").IsUnique(false);
```
and by looking at the table index definitions in the database, I can see them created both as **non-unique**:
![image](https://github.com/dotnet/efcore/assets/4716102/8ca85862-ab94-4d3d-b401-851f5dc34e87)

Also additional note: exactly the same configuration worked fine on EF6 (table with exactly the same table/indexes as a result were created), that's why I still suggest there is something wrong with EFCore, because it is not reflecting the database schema correctly in its context/ChangeTracker.

**Comment by ajcvickers** [comment] 2023-05-22 11:20
@rafalgradziel By convention, EF configures the database schema in such a way that it is aligned with the model. So, defining a one-to-one relationship results in a unique database constraint by convention, because that works with the model. However, EF always lets you explicitly configure the things it does by convention. In this case, you explicitly set the index to be not-unique. However, that doesn't change the way EF is modeling the relationship, just what is happening to the underlying database. These things are intentionally de-coupled to provide mapping flexibility.

The general guidance here is:
* Ensure that the model is defined accurately. It is this, not the database schema, that controls EF behavior.
* If the database schema doesn't seem to align with the model, that's probably because the model is different than you think it is. Fix this, rather than just changing the schema.
* Don't over-configure the model or the schema. The more configuration code you have that just does what EF would do by convention anyway, the more difficult it is to find errors in this code.

**Closed by ajcvickers** 2023-05-22 11:20 UTC
Labels: closed-by-design, customer-reported
