### ISSUE TITLE
EF core 6.0.1 Add Migrations Fail, with default decimal - Fails/Does NOT create Database

### ISSUE THREAD

**Issue by fasteddys** [dotnet/efcore#27197] opened 2022-01-16 21:41 UTC
EF core 6 fails create migrations and update database, but EF core 3.1 LTS does it fine (I repeated this test in both with` both annotations decimal (18,4) & reverting to default (decimal)`

In general EF core 

```
No store type was specified for the decimal property 'LoginAtt' on entity type 'DeviceLoginAttribute'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values in 'OnModelCreating' using 'HasColumnType', specify precision and scale using 'HasPrecision', or configure a value converter using 'HasConversion'.
No store type was specified for the decimal property 'LoginAtt' on entity type 'DeviceLoginAttribute'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values in 'OnModelCreating' using 'HasColumnType', specify precision and scale using 'HasPrecision', or configure a value converter using 'HasConversion'.
warn: Microsoft.EntityFrameworkCore.Model.Validation[30000]
```

**Comment by roji** [comment] 2022-01-16 23:46
@fasteddys please submit a runnable code sample with step-by-step instructions on how to reproduce the problem; it's not possible to investigate the issue based on the limited info above.

**Comment by fasteddys** [comment] 2022-01-17 06:08
If you migrate up & down after a couple times it falls out of sync. The database falls into a bad state, you can not longer access data. The machine has to be rebooted for sql server to allow access.

If you delete migration and try to add, update database, then delete db, and miigrations and try it s few times, the dotnet build fails!

This is just too unstable to perform basic migrations.

Lastly, there is no seeding strategy for users and roles, with EF core Identity!

**Comment by roji** [comment] 2022-01-17 10:19
@fasteddys you'll really need to submit detailed steps here - we routinely delete migrations, add, update and delete DBs, and I'm not aware of an issue. I'm especially unaware of any EF Core issue which requires the machine to be rebooted.

I suggest starting from a blank project, and documenting the steps needed to produce this bad state. Once you have such a list which reproduces the problem, you can post it here and we can use that to investigate.

**Comment by ajcvickers** [comment] 2022-01-28 15:40
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:22 UTC
Labels: closed-could-not-reproduce, customer-reported
