### ISSUE TITLE
Unable to install dotnet-ef

### ISSUE THREAD

**Issue by facu-larocca-zenfolio** [dotnet/efcore#18609] opened 2019-10-26 21:07 UTC
I am trying to install from Package Manager Entity Framework Core Tools and I am getting this error:

> PM> dotnet tool install --global dotnet-ef
> C:\Program Files\dotnet\sdk\3.0.100\NuGet.targets(123,5): error : 'VERSION' is not a valid version string. (Parameter 'value') [C:\Users\Facundo\AppData\Local\Temp\vzjggok2.j40\restore.csproj]
> dotnet : The tool package could not be restored.
> At line:1 char:1
> + dotnet tool install --global dotnet-ef
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (The tool package could not be restored.:String) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
>  
> Tool 'dotnet-ef' failed to install. This failure may have been caused by:
> 
> * You are attempting to install a preview release and did not use the --version option to specify the version.
> * A package by this name w
> as found, but it was not a .NET Core tool.
> * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
> * You mistyped the name of the tool.
> 
> For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

This is a brand new project, using VS 2019 CE templates from the scratch, using Net Core 3.
I am really stuck as I can't run migrations. 

Any help?

Thanks a lot.

**Comment by ErikEJ** [comment] 2019-10-27 06:34
Run from the command prompt instead of inside VS..

**Comment by kp2017** [comment] 2019-10-27 16:39
I just ran the command successfully from Visual Studio 2019 Package Manager Console using the Nunit test project template for .net core. Can you try a similar install just to see if it works on your box?

**Comment by facu-larocca-zenfolio** [comment] 2019-10-27 17:21
@ErikEJ @kp2017, thanks for responding so quickly.
Same result, same error for both approaches. That **'VERSION'** makes me feel like there is something in my environment that EF Core 3 doesn't like. But it is weird, cause it is working fine with EF Core 2

**Comment by ajcvickers** [comment] 2019-10-28 18:42
@facu-larocca-zenfolio I have not been able to reproduce this--I see the output below. However, why is it that you want to install the `dotnet` tool inside the VS Package Manager Console? The [PowerShell commands designed for the PMC](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell) provide a better experience.

```
PM> dotnet tool install --global dotnet-ef

Welcome to .NET Core 3.1!
---------------------
SDK Version: 3.1.100-preview1-014459

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
Since you just installed the .NET Core SDK, you will need to reopen the Command Prompt window before running the tool you installed.
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '3.0.0') was successfully installed.
PM> 
```

**Comment by ajcvickers** [comment] 2019-11-04 17:28
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 14:52 UTC
Labels: closed-could-not-reproduce, customer-reported

**Comment by antwjadam** [comment] 2023-05-18 16:16
I had this problem - if you have vis studio open, open your nuget sources configuration (Tools -> Nuget Package Manager -> Package Manager Settings... Package Sources) and uncheck all nuget sources except for the nuget.org one. 

Hit OK,

Then in your Package Manager Console window in vis studio, try the "dotnet tool install --global dotnet-ef" again.

This worked for me as one of the other package sources I had was causing a clash.

Then once installed, open the nuget sources config again as before and re-check everything you have unchecked.
