### ISSUE TITLE
EF Core : Database First Conversion : Foreign Key wrong column

### ISSUE THREAD

**Issue by sc-vudo** [dotnet/efcore#14409] opened 2019-01-14 15:58 UTC
I am trying to embrace asp.net core by migrating my existing application from .net 4.6.2 with EF6 to .net Core 2.2 with EF Core.

Given that I have an existing database I generated the model from the database to move start with. All of my column names use underscores and where foreign keys live they all start with the table name.

With EF Core it insists that my code column names change from Manager_UserLogin_ID to ManagerUserLoginId which is fine and I can go through my code

The problem arises when I try and query the UserLogin and Manager using the include

__DB.UserLogin.Include(x=>x.Manager).First();
The query trying to run tries to include a UserLoginId column in the Manager query as well as the Manager_UserLogin_ID column.

The Classes are as follows

```C#
partial class Manager
{
    public int ManagerId { get; set; }
    public int ManagerCompanyId { get; set; }
    public int ManagerUserLoginId { get; set; }
    public virtual Company ManagerCompany { get; set; }
    public virtual UserLogin ManagerUserLogin { get; set; }
}
public partial class UserLogin
{
    public UserLogin()
    {
        Manager = new HashSet<Manager>();
    }
    public int UserLoginId { get; set; }
    public string FullName { get; set; }
    public virtual ICollection<Manager> Manager { get; set; }
}
public partial class Company
{
    public Company()
    {
        Manager = new HashSet<Manager>();
    }
    public int CompanyId { get; set; }
    public string CompanyName { get; set; }
    public virtual ICollection<Manager> Manager { get; set; }
}
```

The EF Core context has the following

```C#
protected override void OnModelCreating(ModelBuilder modelBuilder
{
    base.OnModelCreating(modelBuilder);

    modelBuilder.Entity<Company>(entity =>
    {
        entity.HasKey(e => e.CompanyId).HasName("PK_Company_ID");
        entity.Property(e => e.CompanyId).HasColumnName("Company_ID");

        entity.Property(e => e.CompanyName)
            .IsRequired()
            .HasColumnName("Company_Name")
            .HasMaxLength(200);

    modelBuilder.Entity<Manager>(entity =>
    {
        entity.HasKey(e => e.ManagerId)
            .HasName("PK_Manager_ID")
            .ForSqlServerIsClustered(false);

        entity.HasIndex(e => new { e.ManagerCompanyId, e.ManagerUserLoginId })
            .HasName("IX_Manager")
            .IsUnique()
            .ForSqlServerIsClustered();

        entity.Property(e => e.ManagerId).HasColumnName("Manager_ID");

        entity.Property(e => e.ManagerCompanyId).HasColumnName("Manager_Company_ID");

        entity.Property(e => e.ManagerUserLoginId).HasColumnName("Manager_UserLogin_ID");

        entity.HasOne(d => d.ManagerCompany)
            .WithMany(p => p.Manager)
            .HasForeignKey(d => d.ManagerCompanyId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Manager_Company_ID");

        entity.HasOne(d => d.ManagerUserLogin)
            .WithMany(p => p.Manager)
            .HasForeignKey(d => d.ManagerUserLoginId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Manager_UserLogin_ID");
        });

    modelBuilder.Entity<UserLogin>(entity =>
    {
        entity.HasKey(e => e.UserLoginId).HasName("PK_UserLogin_ID");
        entity.HasIndex(e => e.UserLoginUid)
            .HasName("IX_UserLogin_UID")
            .IsUnique();

        entity.Property(e => e.UserLoginId).HasColumnName("UserLogin_ID");

        entity.Property(e => e.FullName)
            .IsRequired()
            .HasColumnName("Full_Name")
            .HasMaxLength(300);

        entity.Property(e => e.UserLoginUid).HasColumnName("UserLogin_UID");
    });
```

And here is the query from Sql Profiler

```sql
    exec sp_executesql N'SELECT [x.Manager].[Manager_ID], [x.Manager].[Manager_Company_ID], [x.Manager].[Manager_UserLogin_ID], , [x.Manager].[UserLoginId]
    FROM [Manager] AS [x.Manager]
    INNER JOIN (
        SELECT TOP(1) [x0].[UserLogin_ID]
        FROM [UserLogin] AS [x0]
        WHERE [x0].[UserLogin_UID] = @____UID_0
        ORDER BY [x0].[UserLogin_ID]
    ) AS [t] ON [x.Manager].[Manager_UserLogin_ID] = [t].[UserLogin_ID]
    ORDER BY [t].[UserLogin_ID]',N'@____UID_0 uniqueidentifier',@____UID_0='F55C9BBB-C7FF-4C87-B834-B2FE6B0F0B17'
```

**Comment by ajcvickers** [comment] 2019-01-14 23:53
@sc-vudo With regard to your original issue, did you consider scaffolding the context with the "use-database-names" options? See: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#dotnet-ef-dbcontext-scaffold

For the bad column name, I have not been able to reproduce this. Can you post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by ajcvickers** [comment] 2019-01-23 17:58
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by sc-vudo** [comment] 2019-03-08 09:55
So I have rebuilt a solution with EF 2.2 and managed to get the --use-database-names to run

However when the sql is querying my database it is still adding additional columns that do not exist.

> exec sp_executesql N'SELECT [x].[Manager_ID], [x].[Active], [x].[AmendTimeStamp], [x].[Company_ID], [x].[CreatedTimeStamp], [x].[Manager_Company_ID], [x].[Manager_UserLogin_ID], [x].[PrimaryManager], [x].[UserLogin_ID]
FROM [Manager] AS [x]
WHERE ([x].[Manager_UserLogin_ID] = @___UserID_0) AND ([x].[Active] = 1)',N'@___UserID_0 int',@___UserID_0=4

The manager table does not have columns UserLogin_ID it has Manager_UserLogin_ID and does not have COmpany_ID it has Manager_Company_ID

**Closed** 2022-10-16 13:47 UTC
Labels: closed-could-not-reproduce, customer-reported
