### ISSUE TITLE
CAST in generated SQL statement leads to possible overflow in SQL or .NET

### ISSUE THREAD

**Issue by klinckag** [dotnet/efcore#23602] opened 2020-12-07 14:54 UTC
source code:
[EFCoreCASTing.zip](https://github.com/dotnet/efcore/files/5653375/EFCoreCASTing.zip)

Linq query to an SQL database table where Quantity is an integer and ItemPrice is a decimal(18,12)
```C#
                var q = from di in context.DeclaredItems
                        group di by 1 into g
                        select new
                        {
                            Price = g.Sum(e => e.Quantity * e.ItemPrice)
                        };
```
results in a CAST in the generated SQL
```SQL
SUM(CAST([d].[Quantity] AS decimal(18,12)) * [d].[ItemPrice])
```
This results in overflow in SQL when Quantity >= 1000000

Because the result in SQL has a precision of 24 (where the last 12 digits
 are always zero) we risk unnecessary overflow in .NET.
1000 * 100.000000000001 => 100000,000000001000000000000000

EF Core version: 3.1.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 3.1
Operating system: Windows 10
IDE: Microsoft Visual Studio Enterprise 2019 Version 16.7.7

**Comment by ajcvickers** [comment] 2020-12-07 18:57
@smitpatel I can't find the dupe...

**Comment by smitpatel** [comment] 2020-12-07 19:37
Related #15586
Duplicate of #14719

**Closed** 2022-10-16 19:14 UTC
Labels: customer-reported
