### ISSUE TITLE
Include() not working when filtered with Contains() and aggregating to list

### ISSUE THREAD

**Issue by olivierr91** [dotnet/efcore#12852] opened 2018-07-31 09:58 UTC
Given the following query in EF Core 2.1:

```
var inventorySummary = myContext.InventoryEntries
    .Include(ie => ie.PurchaseOrderItem).ThenInclude(poi => poi.PurchaseOrder)
    .Where(ie => new HashSet<Guid>() { new Guid("cdd40f38-d3ff-4d2f-be66-ace7f2090745") }.Contains(ie.PurchaseOrderItem.PurchaseOrderId.Value))
    .GroupBy(ie => new { ie.Item, ie.Warehouse })
    .Select(g => new InventorySummaryEntry() {
        Entries = g.ToList()
    })
    .ToListAsync();
```

One would expect that` Entries` contains a list of ` InventoryEntry` with their included` PurchaseOrderItem`, but they do not (`PurchaseOrderItem` is null):

`Assert.NotNull(inventorySummary.Entries.First().PurchaseOrderItem) //Fails`

- Removing `GroupBy()` and `Select()` clause produces the expected result
- Keeping `GroupBy(...)` but replacing `Where(...)` by simple equality (`.Where(ie => ie == new Guid("cdd40f38-d3ff-4d2f-be66-ace7f2090745")`) also produces the expected result.
- The combination of `GroupBy()` and `Contains()` does not produce the expected result.

**Comment by ajcvickers** [comment] 2018-08-01 19:11
@smitpatel to reference in 3.0 Include issue and respond to customer.

**Comment by smitpatel** [comment] 2018-08-01 21:44
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database
                db.Add(
                    new InventoryEntry
                    {
                        Item = 1,
                        Warehouse = 1,
                        PurchaseOrderItem = new PurchaseOrderItem
                        {
                            PurchaseOrder = new PurchaseOrder
                            {
                                Id = new Guid("cdd40f38-d3ff-4d2f-be66-ace7f2090745")
                            }
                        }
                    }
                    );

                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                var inventorySummary = db.InventoryEntries
                    .Include(ie => ie.PurchaseOrderItem)
                        .ThenInclude(poi => poi.PurchaseOrder)
                    .Where(ie => new HashSet<Guid>()
                        {
                            new Guid("cdd40f38-d3ff-4d2f-be66-ace7f2090745")
                        }
                        .Contains(ie.PurchaseOrderItem.PurchaseOrderId.Value))
                    .GroupBy(ie => new { ie.Item, ie.Warehouse })
                    .Select(g => new
                    {
                        Entries = g//.ToList()
                    })
                    .ToList();

                Console.WriteLine(inventorySummary[0].Entries.First().PurchaseOrderItem.PurchaseOrder);
            }

            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        private static ILoggerFactory LoggerFactory => new LoggerFactory().AddConsole(LogLevel.Trace);

        // Declare DBSets
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<InventoryEntry> InventoryEntries { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                //.UseSqlite("filename=_modelApp.db")
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(LoggerFactory);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
        }
    }

    public class Blog
    {
        public int Id { get; set; }
    }

    public class InventoryEntry
    {
        public int Id { get; set; }
        public int Item { get; set; }
        public int Warehouse { get; set; }
        public PurchaseOrderItem PurchaseOrderItem { get; set; }
    }

    public class PurchaseOrderItem
    {
        public int Id { get; set; }
        public Guid? PurchaseOrderId { get; set; }
        public PurchaseOrder PurchaseOrder { get; set; }
    }

    public class PurchaseOrder
    {
        public Guid Id { get; set; }
    }
}
```

Apparently we fail to identify where to put Include in QueryModel.

**Comment by smitpatel** [comment] 2018-08-01 21:44
Related #12795

**Comment by Menighin** [comment] 2019-03-12 13:32
Just hit a similar problem. On the following query, the included `ScheduledStopActivity` and `ScheduledStopActivityTranslations` are `null` if I filter with the `Contains`. If not, they are defined:

    var entities = _context.DbScheduledStop.Include(o => o.ScheduledStopActivity).ThenInclude(s => s.ScheduledStopActivityTranslations)
                     .Include(o => o.Vehicle).Include(o => o.Location)
                     .Where(o => idList.Contains(o.TrainId))
                     .ToList();

Checking the query, there is no join for those entities.

Is it the same problem? Is there a workaround for this?

**Comment by smitpatel** [comment] 2019-03-12 16:29
@Menighin - Can you file a new issue with repro code? Based on initial investigation done on this issue, it was caused because of GroupBy + Contains combination. Since you query does not contain GroupBy, it may be similar issue but with different root cause.

**Comment by dracan** [comment] 2019-03-24 16:08
I've just hit the same issue. I'm using `GroupJoin`. Works as expected if my query doesn't include `Contains`, however if I use contains, then navigation property is null.

**Comment by smitpatel** [comment] 2019-11-21 02:09
Won't fix as per #17068

**Comment by kot-pilot** [comment] 2020-01-24 11:04
> Just hit a similar problem. On the following query, the included `ScheduledStopActivity` and `ScheduledStopActivityTranslations` are `null` if I filter with the `Contains`. If not, they are defined:
> 
> ```
> var entities = _context.DbScheduledStop.Include(o => o.ScheduledStopActivity).ThenInclude(s => s.ScheduledStopActivityTranslations)
>                  .Include(o => o.Vehicle).Include(o => o.Location)
>                  .Where(o => idList.Contains(o.VehicleId))
>                  .ToList();
> ```
> 
> Checking the query, there is no join for those entities.
> 
> Is it the same problem? Is there a workaround for this?

i have the same situation, include is ignored when filtering with 'contains' of some array/list
like 

var entities=context.Items.Include(x=>x.SubItem).Where(x => statuses.Contains(x.Status)).ToList()

Maybe it's already fixed? Or some workaround for that?

**Comment by zuckerthoben** [comment] 2020-08-21 07:39
Did you find a solution for the Include with contains problem? @kot-pilot @dracan @Menighin

**Closed** 2022-10-16 13:22 UTC
Labels: type-bug, closed-out-of-scope, customer-reported, area-query
