### ISSUE TITLE
.ForSqlServer().Column("AName") fails to change name of column

### ISSUE THREAD

**Issue by matthewDDennis** [dotnet/efcore#2243] opened 2015-05-21 16:02 UTC
I have a class

``` c#
    public class BadIdentity
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
```

If my Code First Configuration is

``` c#
            // Demo issue with ForSqlServer
            modelBuilder.Entity<BadIdentity>(b =>
            {
                b.Table("BadIdentity");
                b.Key(bi => bi.Id);
                b.Property(bi => bi.Id).ForSqlServer().Column("BadIdentityId").UseIdentity();
            });
```

then the PK in the table is "Id" not the expected "BadIdentityId".
If I move the ForSqlServer() after the Column(...) then it works.

``` c#
            // Demo issue with ForSqlServer
            modelBuilder.Entity<BadIdentity>(b =>
            {
                b.Table("BadIdentity");
                b.Key(bi => bi.Id);
                b.Property(bi => bi.Id).Column("BadIdentityId").ForSqlServer().UseIdentity();
            });
```

I have created a repo with tests for EF issues as I find them at https://github.com/matthewDDennis/E7Issue.git
The test you should see is OrderOfForSqlDoesNotMatter().

Why does SqlServerPropertyBuilder even have a Column method?

**Comment by smitpatel** [comment] 2015-05-21 21:32
The issue is actually not about ordering.
At present Migrations don't use the columnname annotation set for sqlserver so `ForSqlServer().Column(...)` doesn't have any effect which is bug.
But if you put `Column(...)` right after `Property(..)` it will use Relational annotations which are being used in migrations so that would work as you intend to.

We have Column method in SqlServerPropertyBuilder so that you can specifically set column name for SqlServerProvider and use different column name for any other provider.

**Comment by smitpatel** [comment] 2015-05-21 21:34
the issue is being tracked at #1975

**Comment by rowanmiller** [comment] 2015-05-21 21:45
Closing as this is covered by the issue @smitpatel linked to (#1975).

Note we also decided in today's API review to remove the `ForSqlServer()` method and just have root level methods like `SqlServerColumn(...)`. Also note this just allows a different column name to be set for individual relational providers (i.e. ProductId on SQL Server and PRODUCT_ID on Oracle). You can just use `Column(...)` if you want to set a column names for you relational provider(s).

**Closed** 2022-10-16 08:57 UTC
