### ISSUE TITLE
BoolToStringConverter value converter fails without error for implicit boolean comparison

### ISSUE THREAD

**Issue by eric10k93** [dotnet/efcore#22555] opened 2020-09-16 04:02 UTC
I have an entity class with a value converter on the builder.  When I perform a query, the value is returned properly, but when I attempt to use the property in the WHERE clause of a query, it fails unless I perform an explicit boolean value comparison.

### Steps to reproduce

Created a class with a property built like so (I didn't create this database, just working with what was already being done):
```
    public void Configure(EntityTypeBuilder<Machine> builder)
    {
    //...
    builder.Property(e => e.IsEnabled)
                .HasColumnName("is_enabled")
                .HasColumnType("varchar(45)")
                .HasDefaultValueSql("'TRUE'")
                .IsRequired()
                .HasConversion(new BoolToStringConverter("FALSE", "TRUE"));
    //...
    }
```

Then I run the following (with pre-existing data in database):
```
//this returns 0 rows despite most of the existing data having IsEnabled set to true
var machines = dbContext.Machine
                    .Where(x => x.IsEnabled)
                    .ToList();

//this returns around 200 rows (the correct amount)
var machines = dbContext.Machine
                    .Where(x => x.IsEnabled == true)
                    .ToList();
```

### Further technical details

EF Core version: 3.1.8
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by smitpatel** [comment] 2020-09-16 04:35
Duplicate of #18147

**Comment by eric10k93** [comment] 2020-09-16 04:39
@smitpatel , huh, guess I should've checked for closed issues as well when I ran my search... sorry about that, looks like this issue is planned to be fixed with EF Core 5 now?

**Closed** 2022-10-16 18:40 UTC
Labels: closed-duplicate, customer-reported
