### ISSUE TITLE
Migrations: Setting HasMaxLength is not reflected in migration

### ISSUE THREAD

**Issue by rmja** [dotnet/efcore#3717] opened 2015-11-11 08:37 UTC
If in the previous migration we have:

```
builder.Property(x => x.SomeStringProperty);
```

The SQL field is correctly set to nvarchar(MAX). If this is later changed to:

```
builder.Property(x => x.SomeStringProperty).HasMaxLength(100);
```

Then this change is not reflected in the new migration, and when applying it, the SQL field remains to have datatype nvarchar(MAX) and not nvarchar(100) as expected.

**Comment by rowanmiller** [comment] 2015-11-11 17:24
@bricelam I think you checked in a fix for this recently?

**Comment by bricelam** [comment] 2015-11-11 17:35
Soon. See PR #3699
Closing as a dupe of #3434

**Closed** 2022-10-16 09:15 UTC
