### ISSUE TITLE
Migrations XMLDOC

### ISSUE THREAD

**Issue by leotsarev** [dotnet/efcore#13955] opened 2018-11-14 15:42 UTC
I'm trying to keep my projects wih Warnings-As-Errors and XMLDoc documenation. Sadly, it leads to EF Core projects being source of manual work.

Please either:
1. Code-generate migrations with XMLDoc
2. Code-generate migrations with internal
3. Code-generate migrations with `#pragma warning disable`

### Steps to reproduce
Create EF .csproj. Create dbcontext and some entities.
Set:
```
<GenerateDocumentationFile>True</GenerateDocumentationFile>
<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
```
Call:
```
dotnet ef migrations add InitialCreate
```
Expected result:
Everything fine w/o fixes

Actual result:
`CS1591` in auto-generated files 

### Further technical details
EF Core version: 2.1.4
Database Provider: any relational
Operating system: Windows 10
IDE: VS 2017 15.8

**Comment by ajcvickers** [comment] 2018-11-14 23:07
We discussed this again in triage, and we would consider taking a PR to add XML comments to the generated migrations.

(The reason we didn't do this in the past was to avoid the burden of localizing the comments. However, .NET Core in general does not localize these things except for special cases, so I we believe if should be okay to add English comments. If that changes, then we may consider removing them again rather than taking on the localization cost.)

**Comment by TKharaishvili** [comment] 2018-12-02 21:05
@ajcvickers what exactly should the generated comments say?

**Comment by ajcvickers** [comment] 2018-12-03 18:33
@TKharaishvili I don't think anyone has actually written the comments yet, but they would not need to be overly detailed; rather just concise statements for each generated method saying what it does.

**Comment by Meir017** [comment] 2019-02-12 21:11
implementation notes:
* generated class docs -  https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs#L95
* the up method - https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs#L100
* the down method - https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs#L111

**Comment by roji** [comment] 2019-02-13 12:34
Another option here is to just disable these specific warnings in generated migration files, especially since the comments have almost no value in themselves.

**Comment by smitpatel** [comment] 2019-02-14 01:42
We already output `// <auto-generated >` somewhere in the file and `"#pragma warning disable 612, 618"`. Adding pragma should be easier and better.

**Comment by NArnott** [comment] 2019-02-26 15:47
What point is there to keeping the migrations public? Why not just make them internal?

**Comment by ajcvickers** [comment] 2020-10-10 20:08
@bricelam Is this a dupe of #10695?

**Comment by bricelam** [comment] 2020-10-11 15:52
Yes

**Closed** 2022-10-16 13:40 UTC
Labels: customer-reported
