### ISSUE TITLE
[BUG+REPRO] Objects created from a SELECT without any data are shared instances and are reused across queries

### ISSUE THREAD

**Issue by KLuuKer** [dotnet/efcore#13993] opened 2018-11-21 19:32 UTC
_Sorry it's already late for me but I found this...._

Objects created from a SELECT without any data are shared instances and are reused across queries

### Steps to reproduce
any random context will do (I used a standalone one without any funky config (also happend on our big scary project)
```c#
var step1 = ctx.Foos.Select(f => new
{
    DontAsk = new List<string>(),
    FooName = f.Name,
    FooId = f.Id,
}).ToList();
step1.ForEach(f => f.DontAsk.Add("tracked string"));
```
now dispose that context (or don't doesn't matter anyway), do some GC.Collect(force block the works) (also doesn't matter) drink some tea (or coffee also fine) and whatever else you fancy

when your done **make a new context**
```c#
var inspectme = ctx2.Foos.Select(f => new
{
    DontAsk = new List<string>(),
    FooName = f.Name,
    FooId = f.Id,
}).ToList();
// notice how the strings from step1 appear inside the inspectme
// if you change me to a FirstOrDefault the strings wont appear (unless you also do the same for step1)

var iamfine = ctx2.Foos.Select(f => new
{
    DontAsk = new List<string>(),
    FooName = f.Name,
    IAmSomeRandomChangeOnTheModel = true,
    FooId = f.Id,
}).ToList();
// look in iamfine and notice the changes not appearing
```

UPDATE 1: same thing happens when using typed classes, I think EF core is pooling the allocations of the objects and recycling them, that List in the DontAsk property is a shared instance between all items that come from the query.

UPDATE 2: objects are cached PER query, any change to it (like `.AsNoTracking()`) makes it a unique query and even with notracking the same problem exists.

### Further technical details
EF Core version: 2.2.0-preview3-35497 (also for 2.1)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 (patched etc)
IDE: Visual Studio 2017 15.9.0 Preview 6

**Comment by KLuuKer** [comment] 2018-11-26 03:31
@ajcvickers sorry for the tag but can you please take a quick look at this?

**Comment by KLuuKer** [comment] 2018-11-27 04:17
relinq, so milestone v3 then :(

UPDATE 3: when the List\object is created in the constructor of a class the issue doesn't happen

**Comment by smitpatel** [comment] 2018-11-27 19:52
Based on my understanding, issue here is since `new List<string>()` is not dependent on range variable, relinq optimizes out and generate a constant. In compiled query since this constant is captured. And when we reuse the same compiled query, the constant is referencing same memory space so you such weird behaviour. Ideally, any new object creation in Select should generate new object every time it is iterated.

Related #7983

**Comment by divega** [comment] 2019-06-24 04:11
Removing propose-punt lable as per discussion in triage. IIRC, we said this could be fixed for 3.0. @smitpatel feel free to push back if i misunderstood.

**Comment by smitpatel** [comment] 2019-06-24 04:25
Closing as duplicate of #7983

**Comment by divega** [comment] 2019-06-24 05:49
@smitpatel okay.

**Closed** 2022-10-16 13:41 UTC
Labels: closed-duplicate, customer-reported
