### ISSUE TITLE
Query: Provide a way to indicate that part of a query should translate to server or throw

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#28155] opened 2022-06-03 18:04 UTC
Rather than client eval when in top-level projection

**Comment by roji** [comment] 2022-07-10 09:51
Aggregate functions are a motivation for this: https://github.com/dotnet/efcore/issues/28409#issuecomment-1179695122

**Comment by stevendarby** [comment] 2022-07-10 18:32
Is this distinct from https://github.com/dotnet/efcore/issues/24509?

**Comment by smitpatel** [comment] 2022-07-10 19:29
#28155 supersedes #24509

**Comment by ajcvickers** [comment] 2022-07-14 11:55
Duplicate of #24509.

**Closed by ajcvickers** 2022-07-14 11:55 UTC
Labels: type-enhancement, customer-reported, area-query
