### ISSUE TITLE
Problem with migrating from EF6 to EF Core

### ISSUE THREAD

**Issue by tuscen** [dotnet/efcore#12269] opened 2018-06-07 04:58 UTC
Hi. I'm migrating a project from EF6 to EF Core 2.1 and have a problem. I used scaffold to create a new context class. Almost everything was good however it didn't inlined existing primary key names. EF6 generated names for primary keys include their schema name (`PK_dbo_`). The problem is that EF Core algorithm for generating PK names don't include schema name so that after I create a new migration primary key names don't include schema name (`PK_`). This will affect subsequent migrations unless I either manually add names for every primary key or somehow influence the mechanism that generates names for primary keys. Is there some setting in EF Core so I can avoid this tedious task?

**Comment by tuscen** [comment] 2018-06-07 09:08
After a bit of googling I've found a solution:

```c#
foreach (var entity in modelBuilder.Model.GetEntityTypes())
{
    foreach (var property in entity.GetProperties())
    {
        var primarykeyName = $"PK_{entity.Relational().Schema}.{entity.Relational().TableName.Pluralize()}";
        property.DeclaringEntityType.FindPrimaryKey().Relational().Name = primarykeyName;
    }
}
```

`.Pluralize()` is from `Humanizer` package.

Now primary key names in the generated migration is the same as in the database.

**Comment by bricelam** [comment] 2018-07-31 17:07
Duplicate of #12821 this will be fixed in EF Core 2.2

**Closed** 2022-10-16 12:29 UTC
Labels: closed-duplicate, customer-reported
