### ISSUE TITLE
Specify order of columns in SQL generated from LINQ queries that project a whole entity

### ISSUE THREAD

**Issue by zinov** [dotnet/efcore#11239] opened 2018-03-12 18:49 UTC
I would like to have an option or an attribute in entity framework core that cares about the order of how the SQL queries are generated from Linq queries that project a whole entity, 

If my model a Person or a Truck,  IsDeleted and CreatedDate fields can't be marked as the last properties of every generated query. The [Column(Order = #)] attribute doesn't work in this scenario

```C#
class ModelBase
{ 
    int Id{get;set;}
   string CreatedDate{get;set;}
    bool IsDeleted{get;set;}
}

public Person: ModelBase
{
    string Name{get;set;}
   string LastName{get;set;}
   string SSN{get;set;}
}

public Truck: ModelBase
{
  string Model{get;set;}
  int Year{get;set;}
}
```

**Comment by ajcvickers** [comment] 2018-03-12 22:46
@zinov Can you explain a bit more about why the order in the query is important to you?

**Comment by ajcvickers** [comment] 2018-03-19 17:41
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by zinov** [comment] 2018-03-19 17:59
@ajcvickers The order is important to maintain a consistent standard when you see the data you query, in another way you need to start looking for the fields randomly displayed as part of your query result

**Comment by ajcvickers** [comment] 2018-03-19 19:03
@zinov The order that the columns are created does not necessarily correspond to the order that the columns are queried. I am closing this as by-design because, regardless of the behavior of column creation, we have no plans to implement anything that would allow the order of columns in the query to be specified. This would add complexity to queries for very minimal value.

**Comment by zinov** [comment] 2018-03-19 21:21
@ajcvickers my point is that even the table can't be generated in that way, you can't specify that a certain column goes as the final column on a table(IsDeleted), then the query itself doesn't make much sense because with every select * the field(IsDeleted) will be the latest.

**Closed** 2022-10-16 12:13 UTC
Labels: closed-by-design
