### ISSUE TITLE
Problem faced with transactions with EF6 for .net core 6 but was working fine in EF6 for .net framework

### ISSUE THREAD

**Issue by jwdsoft** [dotnet/efcore#31112] opened 2023-06-20 23:30 UTC
I have a problem with entity framework in a web api project with DotNet Core 6. the problem is that the manual transaction is not taken in consideration and changes are saved and not rolled back
While I have a winforms app using the same code but targeting Dotnet framework 4.6 which was working as expected (when an error occurs the transaction is rolled back)

I'm using mysql as the database i'm using the same database being used in winform app since i'm migrating the winform app to a Web App (API and Front End)

Here is the code found in both Winform App and Web Api Project

```C#
var transaction = _context.Database.BeginTransaction();
try
{
_context.Entry(old).CurrentValues.SetValues(order);
        _context.Entry(old).State = EntityState.Modified;
        _context.OrderDetails.RemoveRange(_context.OrderDetails.Where(x => x.id== order.Id));
        _context.SaveChanges();
        _context.Database.ExecuteSqlRaw("ALTER TABLE order_detail AUTO_INCREMENT=1");
        foreach (OrderDetail od in order.orderDetail)
        {
            _context.OrderDetails.Add(od);
        }
        _context.SaveChanges();
        throw new DbUpdateConcurrencyException();
    transaction.Commit();
    return Ok(order);
}
catch (Exception ex)
{
    transaction.Rollback();
 }
```

I can't figure out what is the problem so maybe its a EF problem

**Comment by ajcvickers** [comment] 2023-06-21 08:25
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by jwdsoft** [comment] 2023-07-02 18:02
Thanks for your response
sorry for not posting a runnable code
here is a working web api example

I'm using mysql as the Database
the database has two tables : Orders and OrderDetails 

public class Orders
    {
        [Key]
        public int orderId { get; set; }
        public decimal totalPrice { get; set; }
        [ForeignKey("orderId")]
        public virtual ICollection<OrderDetails> orderDetail { get; set; }
}
public class OrderDetails
{
    [Key]
    public int orderDetailId { get; set; }
    public int orderId { get; set; }
    public decimal price { get; set; }
    public decimal quantity { get; set; }
}
    
and here is the controller EndPoint code
public async Task<ActionResult<Orders>> GetOrder(int id){
            
            using (var T = _context.Database.BeginTransaction())
            {
                Orders order = new Orders()
                {
                    orderId = 1,
                    totalPrice = 100, // the value in database is 200
                };
                OrderDetails orderDetail = new OrderDetails()
                {
                    orderDetailId = 1,
                    orderId = 1,
                    price = 100, // the value in database is 200
                    quantity = 1
                };
                Orders? old = _context.orders.FirstOrDefault(d => d.orderId == order.orderId);
                if (old == null)
                    _context.orders.Add(order);
                else
                {
                    _context.Entry(old).CurrentValues.SetValues(order);
                    _context.Entry(old).State = EntityState.Modified;
                    _context.orderDetails.RemoveRange(_context.orderDetails.Where(x => x.orderId == order.orderId));
                    _context.SaveChanges();
                    _context.Database.ExecuteSqlRaw("ALTER TABLE OrderDetails AUTO_INCREMENT=1");
                }
                _context.orderDetails.Add(orderDetail);


                _context.SaveChanges();
                throw new DbUpdateConcurrencyException();
                T.Commit(); // since this commit is after an exception all the changes inside this manual transaction should be rolled back, but the changes are saved even thought the changes aren't commited,even if I use try catch and use T.Rollback() it doesn't rollback
            }
}

I hope this is clear enough for you to reproduce the issue

**Comment by roji** [comment] 2023-07-02 18:51
@jwdsoft I am unable to reproduce this. I took your code and pasted it (more or less) into a console program, and ran that; the DbUpdateConcurrencyException is thrown and the database is empty as expected after the program terminates.

Take a look at the code sample below - this is why we ask for a fully runnable, minimal code sample which reproduces the error. Please try to tweak the below to make it fail, or submit a similar, fully runnable code sample.

<details>
<summary>Attempted repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

using (var T = ctx.Database.BeginTransaction())
{
    Orders order = new Orders()
    {
        orderId = 1,
        totalPrice = 100, // the value in database is 200
    };
    OrderDetails orderDetail = new OrderDetails()
    {
        orderDetailId = 1,
        orderId = 1,
        price = 100, // the value in database is 200
        quantity = 1
    };
    Orders? old = ctx.orders.FirstOrDefault(d => d.orderId == order.orderId);
    if (old == null)
        ctx.orders.Add(order);
    else
    {
        ctx.Entry(old).CurrentValues.SetValues(order);
        ctx.Entry(old).State = EntityState.Modified;
        ctx.orderDetails.RemoveRange(ctx.orderDetails.Where(x => x.orderId == order.orderId));
        ctx.SaveChanges();
        ctx.Database.ExecuteSqlRaw("ALTER TABLE OrderDetails AUTO_INCREMENT=1");
    }

    ctx.orderDetails.Add(orderDetail);


    ctx.SaveChanges();
    throw new DbUpdateConcurrencyException();
    T.Commit(); // since this commit is after an exception all the changes inside this manual transaction should be rolled back, but the changes are saved even thought the changes aren't commited,even if I use try catch and use T.Rollback() it doesn't rollback
}

public class BlogContext : DbContext
{
    public DbSet<Orders> orders { get; set; }
    public DbSet<OrderDetails> orderDetails { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
    }
}

public class Orders
{
    [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int orderId { get; set; }
    public decimal totalPrice { get; set; }
    [ForeignKey("orderId")]
    public virtual ICollection<OrderDetails> orderDetail { get; set; }
}
public class OrderDetails
{
    [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int orderDetailId { get; set; }
    public int orderId { get; set; }
    public decimal price { get; set; }
    public decimal quantity { get; set; }
}
```

</details>

**Comment by ajcvickers** [comment] 2023-07-19 18:17
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by jwdsoft** [comment] 2023-08-16 21:07
I'm sorry not answering at time and providing a working example since I was away.
here is a working example that show up the issue, and also I figured out what the issue is. the problem is when I use rawSql Query which was working fine in previous version with dotnet framework
here is the code

`public class BlogContext : DbContext
    {
        private static string con;
        public virtual DbSet<Order> Orders { get; set; } = null!;
        public virtual DbSet<Orderdetail> Orderdetails { get; set; } = null!;
        public BlogContext()
        {
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder
                .UseMySQL(@"Server=localhost;Database=test;User=root;Password=;")
                .LogTo(Console.WriteLine, LogLevel.Information)
                .EnableSensitiveDataLogging();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        }
        
    }

    public class Order
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int OrderId { get; set; }
        public decimal TotalPrice { get; set; }
    }
    public class Orderdetail
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int OrderDetailId { get; set; }
        public int OrderId { get; set; }
        public decimal Price { get; set; }
        public decimal Quantity { get; set; }
    }
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        

        [HttpGet(Name = "Order")]
        public async Task<ActionResult<IEnumerable<Order>>> Get()
        {
            await using var ctx = new BlogContext();
            Order order0 = new Order()
            {
                OrderId = 1,
                TotalPrice = 200,
            };
            Orderdetail orderDetail0 = new Orderdetail()
            {
                OrderDetailId = 1,
                OrderId = 1,
                Price = 200,
                Quantity = 1
            };
            Order? o = ctx.Orders.FirstOrDefault(x => x.OrderId == order0.OrderId);
            if (o == null)
                ctx.Orders.Add(order0);
            else
            {
                ctx.Entry(o).CurrentValues.SetValues(order0);
                ctx.Entry(o).State = EntityState.Modified;
            }
            ctx.Orderdetails.RemoveRange(ctx.Orderdetails.Where(x => x.OrderId == order0.OrderId));
            ctx.Orderdetails.Add(orderDetail0);
            ctx.SaveChanges();

            using (var T = ctx.Database.BeginTransaction())
            {
                Order order = new Order()
                {
                    OrderId = 1,
                    TotalPrice = 100, // the value in database is 200
                };
                Orderdetail orderDetail = new Orderdetail()
                {
                    OrderDetailId = 1,
                    OrderId = 1,
                    Price = 100, // the value in database is 200
                    Quantity = 1
                };
                Order? old = ctx.Orders.FirstOrDefault(d => d.OrderId == order.OrderId);
                if (old == null)
                    ctx.Orders.Add(order);
                else
                {
                    ctx.Entry(old).CurrentValues.SetValues(order);
                    ctx.Entry(old).State = EntityState.Modified;
                    ctx.Orderdetails.RemoveRange(ctx.Orderdetails.Where(x => x.OrderId == order.OrderId));
                    ctx.SaveChanges();
                    //ctx.Database.ExecuteSqlRaw("ALTER TABLE OrderDetails AUTO_INCREMENT=1"); // when I comment this code the transaction is rolled back on exception when I uncomment it the transaction is commited even when an exception occurs
                }
                ctx.Orderdetails.Add(orderDetail);
                ctx.SaveChanges();
                throw new DbUpdateConcurrencyException();
                T.Commit(); 
                return Ok();
            }
        }
    }`

**Comment by jwdsoft** [comment] 2023-09-02 19:59
Did you get the same problem on your side ?

**Comment by ajcvickers** [comment] 2023-09-20 19:09
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2023-09-20 19:09 UTC
Labels: closed-could-not-reproduce, customer-reported
