### ISSUE TITLE
Query: compilation error for query that joins two GroupBys by their keys

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12438] opened 2018-06-20 23:43 UTC
query using northwind model:

```
ctx.Orders.GroupBy(o => o.CustomerID).Join(ctx.Orders.GroupBy(oo => oo.CustomerID), o => o.Key, i => i.Key, (o, i) => new { o, i }).Select(e => e.i.Count())
```

query plan (dangling qsre):

```
(QueryContext queryContext) => IEnumerable<int> _InterceptExceptions(
    source: IEnumerable<int> _Select(
        source: IEnumerable<TransparentIdentifier<ValueBuffer, IGrouping<string, Order>>> _Join(
            outer: IEnumerable<ValueBuffer> _ShapedQuery(
                queryContext: queryContext, 
                shaperCommandContext: SelectExpression: 
                    SELECT 1
                    FROM [Orders] AS [o]
                    GROUP BY [o].[CustomerID], 
                shaper: ValueBufferShaper), 
            inner: IEnumerable<IGrouping<string, Order>> _GroupBy(
                source: IEnumerable<Order> _ShapedQuery(
                    queryContext: queryContext, 
                    shaperCommandContext: SelectExpression: 
                        SELECT [oo].[OrderID], [oo].[CustomerID], [oo].[EmployeeID], [oo].[OrderDate]
                        FROM [Orders] AS [oo]
                        ORDER BY [oo].[CustomerID], 
                    shaper: BufferedEntityShaper<Order>), 
                keySelector: (Order oo) => oo.CustomerID, 
                elementSelector: (Order oo) => oo), 
            outerKeySelector: (ValueBuffer o) =>  ---> [o] <--- .Key, 
            innerKeySelector: (IGrouping<string, Order> i) => i.Key, 
            resultSelector: (ValueBuffer o | IGrouping<string, Order> i) => TransparentIdentifier<ValueBuffer, IGrouping<string, Order>> CreateTransparentIdentifier(
                outer: o, 
                inner: i)), 
        selector: (TransparentIdentifier<ValueBuffer, IGrouping<string, Order>> t0) => int Count(t0.Inner)), 
    contextType: TestModels.Northwind.NorthwindRelationalContext, 
    logger: DiagnosticsLogger<Query>, 
    queryContext: queryContext)
```

**Comment by ajcvickers** [comment] 2018-06-27 20:53
@smitpatel to de-dupe.

**Comment by smitpatel** [comment] 2018-06-27 21:09
Duplicate of #12304

**Closed** 2022-10-16 13:15 UTC
