### ISSUE TITLE
[Cosmos] Objects sometimes corrupted and mutated in memory on DbContext.Set<T>().Add call

### ISSUE THREAD

**Issue by chucksspencer** [dotnet/efcore#25560] opened 2021-08-17 22:16 UTC
We've got a .NET Core 3.1 project using Microsoft.Azure.Cosmos/3.20.1 to work with a Cosmos Document DB. We started seeing some incorrect data saved in the DB. Upon investigation we discovered that sometimes objects were being inexplicably mutated in memory on the `DbContext.Set<T>().Add` call.

To verify this, I serialized the object immediately before and after the call, to get an immutable state of its value before and after for comparison. Note that I'm doing this with the object provided as input to the `Add` call, I'm not looking at the result.

```C#
string preSerialize = JsonConvert.SerializeObject(entity);
var result = context.Set<TEntity>().Add(entity);
string postSerialize = JsonConvert.SerializeObject(entity);
if (!preSerialize.Equals(postSerialize))
{
    throw new Exception($"Unexplained mutation during save of entity {entity.Id}. Aborting.");
}
```

In some cases (with one particular record we were trying to save), the value of `entity` would be different after the `Add()` call. Substantially different, with objects missing from child collections within the entity. Still valid, but substantially different.

The following seems to solve the problem - the data is saved correctly and the entity is not mutated in memory. But it is gross. I create a deep copy of the `entity` be serializing then deserializing - and I give that deep copy to the `Add` call.

```C#
string preSerialize = JsonConvert.SerializeObject(entity);
var result = context.Set<TEntity>().Add(JsonConvert.DeserializeObject<TEntity>(preSerialize));
string postSerialize = JsonConvert.SerializeObject(entity);
if (!preSerialize.Equals(postSerialize))
{
    throw new Exception($"Unexplained mutation during save of entity {entity.Id}. Aborting.");
}
```

I'd love to know what's going on and why this fix works.

**Comment by chucksspencer** [comment] 2021-08-17 22:28
Note: we are *not* using lazy loading proxies at this time.

**Comment by ajcvickers** [comment] 2021-08-20 10:02
@chucksspencer Is the DbContext already tracking entities before you call `Add`? or is it a new context not yet tracking anything?

**Comment by chucksspencer** [comment] 2021-08-23 18:34
@ajcvickers It's a new DbContext. It's part of an atomic "Add" call initiated via a web endpoint - and the DbContext has a Transient lifecycle per the dependency injection setup. This `.Set<T>.Add()` call is all we do here, then the `SaveChanges` call and that's it. However the mutation of the object happens when the `Add()` call is made, before the `SaveChanges` call happens.

**Comment by ajcvickers** [comment] 2021-08-25 08:10
@chucksspencer We discussed this and there is a good chance that EF Core is synthesizing the "id" key value used by Cosmos. However, we will likely need a full repro to be able to verify this or investigate more. To that end, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

**Comment by ajcvickers** [comment] 2021-09-07 11:26
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 19:43 UTC
Labels: closed-no-further-action, customer-reported
