### ISSUE TITLE
string#Equals with StringComparison fails in queries where it shouldn't

### ISSUE THREAD

**Issue by QuantumToasted** [dotnet/efcore#18897] opened 2019-11-14 06:53 UTC
I discovered an odd bug or inconsistency today; when querying data of a DbSet<T>, in my case, via `Any`, using the `StringComparison`* overload of `string#Equals` results in the query not finding any matches when it should be. Attempting the same query without any `StringComparison` succeeds. 

*\*Note: only tested with `StringComparison.OrdinalIgnoreCase` and `StringComparison.InvariantCultureIgnoreCase`. Not sure if this applies to all of them.*

### Steps to reproduce

Using the code below will cause the check in `Main()` to fail, despite an entry in the table with the exact same text existing.

```cs
public class CustomDbContext : DbContext
{
    private const string CONNECTION_STRING = "YOUR_CONNECTION_STRING";

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseNpgsql(CONNECTION_STRING);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Highlight>(highlight =>
        {
            highlight.HasKey(x => x.Id);
            highlight.Property(x => x.Id)
                .ValueGeneratedOnAdd();
        });
    }

    public DbSet<Highlight> Highlights { get; set; }
}

public sealed class Highlight
{
    public int Id { get; set; }

    public string Text { get; set; }
}

private const string TEXT = "kiel";

public static void Main()
{
    using var ctx = new CustomDbContext();

    ctx.Highlights.Add(new Highlight { Text = TEXT });
    ctx.SaveChanges();

    if (ctx.Highlights.Any(x => x.Text.Equals(TEXT, StringComparison.OrdinalIgnoreCase)))
    {
        Console.WriteLine($"Text {TEXT} - OK");
    }
    else
    {
        Console.WriteLine($"Text {TEXT} - NOT_FOUND");
    }

    Console.ReadKey();
}
```

### Further technical details

EF Core version: 3.0.0
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET Core 3.0
Operating system: Windows 10 x64
IDE: Visual Studio 2019 16.3.7

**Comment by smitpatel** [comment] 2019-11-14 06:57
Duplicate of #18472

**Closed** 2022-10-16 14:56 UTC
Labels: customer-reported
