### ISSUE TITLE
store procedure is not work in entityframework core 

### ISSUE THREAD

**Issue by debin168** [dotnet/efcore#14072] opened 2018-12-04 06:20 UTC
with the same c# code ,the first store procedure is work perfect  the c# code can  get data, but with the second store prodecure   c# code can't get datas(no exception just cant get data),  the second store procedure work in ef6.0  perfect like first store procedure ,so what's the problem with my c# code or store procedure or ef core ?
anyone give me some  suggestion?
``` first store procedure  
-- =============================================
ALTER PROCEDURE [dbo].[TEST_PROCEDURE]
	@pageIndex INT=1,
	@pageSize INT=20,
	@pointStr nvarchar(4000)='114.403479 30.556776',
	@environment VARCHAR(20)='
AS
BEGIN
	SET NOCOUNT ON;
	Declare @currentLocation geography
	select  Id from citys
END
```
```second store procedure  
-- =============================================
ALTER PROCEDURE [dbo].[TEST_PROCEDURE]
	@pageIndex INT=1,
	@pageSize INT=20,
	@pointStr nvarchar(4000)='114.403479 30.556776',
	@environment VARCHAR(20)='
AS
BEGIN
	SET NOCOUNT ON;
	Declare @currentLocation geography
	select @currentLocation = geography::STPointFromText('POINT ('+@pointStr+')', 4326)
       select *, geo.STDistance(@currentLocation) as 距离 from citys
     where geo.STDistance(@currentLocation) < 1000000
      order by geo.STDistance(@currentLocation)
END
```

```c#
       var connection = db.Database.GetDbConnection();
                using (var cmd = connection.CreateCommand())
                {
                    await db.Database.OpenConnectionAsync();
                    cmd.CommandText = sql;
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.Parameters.AddRange(sqlParams);
                    var dr = await cmd.ExecuteReaderAsync();
                    var columnSchema = dr.GetColumnSchema();
                    var data = new ArrayList();
                    while (await dr.ReadAsync())
                    {
                        var item = new Dictionary<string, object>();
                        foreach (var kv in columnSchema)
                        {
                            if (kv.ColumnOrdinal.HasValue)
                            {
                                var itemVal = dr.GetValue(kv.ColumnOrdinal.Value);
                                item.Add(kv.ColumnName, itemVal.GetType() != typeof(DBNull) ? itemVal : "");
                            }
                        }
                        data.Add(item);
                    }
                    dr.Dispose();
                    return data;

                }
```

EF Core version: (2.1.4)
Database Provider: (SqlServer2012)
Operating system: windows 10

**Comment by ajcvickers** [comment] 2018-12-12 19:41
Pinging @div

**Comment by ajcvickers** [comment] 2018-12-12 19:41
Pinging @divega

**Comment by ajcvickers** [comment] 2019-01-04 19:17
Pinging @divega

**Comment by divega** [comment] 2019-01-07 21:45
@debin168 I don't see anything obvious that could make this code work in some cases and not in others. 

But I am not sure I understand what you are seeing. Are you running this on .NET Framework with both EF Core and EF6, or are you running the EF Core version against .NET Core? 

It is just a shot in the dark, but there could be differences in the SqlClient functionality between .NET Framework and .NET Core, specifically in the behavior of GetColumnSchema.  

FWIW, the C# snippet contains only one EF call:  db.Database.GetDbConnection(). And I cannot think of any differences between EF Core and EF6 in this area that should affect the scenario. 

As a next step, I would suggest removing EF completely from the picture by creating a SqlConnection manually. Then if you still see differences in behavior, we may need to redirect this issue to some other repository.

**Comment by ajcvickers** [comment] 2019-01-16 17:56
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 13:42 UTC
Labels: closed-could-not-reproduce, customer-reported
