### ISSUE TITLE
DbUpdateException.Entries is empty when a unique constraint sql error is thrown.

### ISSUE THREAD

**Issue by alaatm** [dotnet/efcore#7829] opened 2017-03-10 02:51 UTC
When a `DbUpdateException` is thrown because of unique index constraint, the `DbUpdateException.Entries` collection is empty. Is this an expected behavior or should it contain the involved entity in there?

### Further technical details
EF Core version: 1.1.1

**Comment by jpiquot** [comment] 2017-03-12 14:37
Hi,
I have the same issue on unique indexes or on primary key duplicates. The Entries value of the BbUpdateException is empty.

Regards

**Comment by JonPSmith** [comment] 2018-10-12 10:51
Can I request this issue be considered again. Here is the use case.

I am trying to write a SQL error handler that will produce a user-friendly error message from a unique index constraint. I can decode the SQL Server error message if its a single column constraint, but for multiple column indexes it is far harder.

I would also like to alert users to possible duplicate errors where the errors come from a Soft Deleted entry, hidden by a Query Filter. That requires me to extract the property values and search for the duplicate item to detect if it was hidden by a Query Filter.

**Comment by ajcvickers** [comment] 2018-10-12 16:14
@JonPSmith The issue is not closed; it is scheduled to be fixed in the 3.0 release.

**Comment by JonPSmith** [comment] 2019-04-02 14:51
Did this make its way into EF Core 2.2? I don't see and code so I assume not. Be nice to have in 3.0

**Comment by ajcvickers** [comment] 2019-04-02 17:07
@JonPSmith The milestone is set to 3.0. This means it's not in 2.2.

**Comment by SebastiaanPolfliet** [comment] 2019-09-02 15:19
Any news about this? The [weekly status update](https://github.com/aspnet/EntityFrameworkCore/issues/15403) does not mention the item and there is only one issue that's still being worked on for 3.0.

**Comment by ajcvickers** [comment] 2019-09-08 20:43
@SebastiaanPolfliet Unfortunately, it had to be cut from 3.0. However, it is scheduled for the 3.1 release scheduled for the beginning of December.

**Comment by Detzito** [comment] 2019-12-04 10:02
I do also need it but it seems it has not been fixed in 3.1...

**Comment by ajcvickers** [comment] 2020-01-27 19:42
Re-triage based on https://github.com/dotnet/efcore/issues/15404#issuecomment-578224138

**Comment by roja** [comment] 2020-03-11 11:17
Any update on this? It stops us from recovering from unique collisions.

**Comment by ajcvickers** [comment] 2020-03-12 20:13
@roja This issue is in the Backlog milestone. This means that it is not planned for the next release (EF Core 5.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by DeluxeAgency2020** [comment] 2020-07-04 06:12
Is any workaround for this issue with a performance problem?

**Closed** 2020-09-02 03:15 UTC
Labels: closed-fixed, consider-for-next-release, punted-for-2.0, punted-for-2.1, punted-for-2.2, punted-for-3.0, punted-for-3.1, type-bug
