### ISSUE TITLE
the generated database table column sequence is different from the model class property definition sequence when code first generation

### ISSUE THREAD

**Issue by linsmod** [dotnet/efcore#8761] opened 2017-06-07 06:36 UTC
### Steps to reproduce

my model class is
```c#
public class AppEvent : BaseModel
    {
        public AppEvent()
        {
        }
        /// <summary>
        /// 事件名称
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// AppName
        /// </summary>
        public string AppName { get; set; }
        /// <summary>
        /// App版本
        /// </summary>
        public string AppVersion { get; set; }
        /// <summary>
        /// 分发渠道
        /// </summary>
        public string Channel { get; set; }
        /// <summary>
        /// 设备ID
        /// </summary>
        public string DeviceID { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public string UserID { get; set; }
        /// <summary>
        /// 登录用户具有的会话ID
        /// </summary>
        public string UserSID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PrevEvent { get; set; }
        /// <summary>
        /// 堆栈跟踪/最大5/JSON
        /// </summary>
        public string StackTrace { get; set; }
        /// <summary>
        /// 操作系统
        /// </summary>
        public string Os { get; set; }
        /// <summary>
        /// 设备商标
        /// </summary>
        public string DeviceBrand { get; set; }
        /// <summary>
        /// 设备型号
        /// </summary>
        public string DeviceModel { get; set; }

        /// <summary>
        /// 额外内容
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// 事件时间
        /// </summary>
        public DateTime EventTime { get; set; }

        /// <summary>
        /// 服务端存入时间
        /// </summary>
        public DateTime CreateTime { get; set; }
    }
```

but the columns sequence is: A-Z

```c#
protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AppEvents",
                columns: table => new
                {
                    ID = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    AppName = table.Column<string>(nullable: true),
                    AppVersion = table.Column<string>(nullable: true),
                    Channel = table.Column<string>(nullable: true),
                    Content = table.Column<string>(nullable: true),
                    CreateTime = table.Column<DateTime>(nullable: false),
                    DeviceBrand = table.Column<string>(nullable: true),
                    DeviceID = table.Column<string>(nullable: true),
                    DeviceModel = table.Column<string>(nullable: true),
                    EventTime = table.Column<DateTime>(nullable: false),
                    Name = table.Column<string>(nullable: true),
                    Os = table.Column<string>(nullable: true),
                    PrevEvent = table.Column<string>(nullable: true),
                    StackTrace = table.Column<string>(nullable: true),
                    UserID = table.Column<string>(nullable: true),
                    UserSID = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppEvents", x => x.ID);
                });
        }
```

i think it should use class properties definition sequence like the non-core ef behavior

### Further technical details
EF Core version:1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10 15063
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment] 2017-06-09 18:32
Closing as a duplicate of #2272

**Closed** 2022-10-16 11:07 UTC
