### ISSUE TITLE
Mapping referenced entity only to the backing field

### ISSUE THREAD

**Issue by TsengSR** [dotnet/efcore#9485] opened 2017-08-19 21:32 UTC
I got a case, where I have a base type `ModuleConfigBase` which can have multiple modules which share a common base class. 

I want to ensure that a specific type which inherits from `ModuleConfigBase` can only assign specific types of modules to it, i.e. `NativeModule`. 

Since the `Module` itself should be accessible anywhere, I'd like to avoid adding a property which is only private on the base type and instead have typed `Module` properties on the child classes. 

### Steps to reproduce
```c#
public abstract class ModuleConfigBase
{
    protected Module module;
    public ICollection<ModuleConfigProperty> Properties { get; set; } 
        = new List<ModuleConfigProperty>();
}

public abstract class Module
{
    public int Id { get; set; }
    public List<ModuleProperty> Properties { get; set; }
}

public class NativeModule : Module
{
    public string Assembly { get; set; }
    public string Type { get; set; }
}

public class NativeModuleConfig : ConnectorConfig
{
    // This would be the only way to access the backing field
    public NativeModule Module
    {
        get => module as NativeModule;
        set => module = value;
    }
}
```

I just can't find anyway to configure the navigation w/o having a property. 

```c#
modelBuilder.Entity<ModuleConfigBase>(c =>
{
    c.HasOne<Module>()
        .WithMany()
        .HasForeignKey("moduleID");

    var moduleMetadata = c.Metadata.FindNavigation("module");
    moduleMetadata.SetField("module");
    moduleMetadata.SetPropertyAccessMode(PropertyAccessMode.Field);
}
```
It fails obviously with 

```
Value cannot be null.
Parameter name: property
```

Is there any way map the referenced types to a backing field w/o having to add a private property on the base class? Seems quite ugly and pollutes my domain classes (trying to have EF Core map directly map into the domain classes w/o leaking too much DB specifics into the domain model). 

### Further technical details
EF Core version: 2.0.0 (RTM)
Database Provider: Pomelo.EntityFrameworkCore.MySql 2.0.0-rtm-10056
Operating system: Windows 10
IDE: Visual Studio 2017 15.3.1

**Comment by ajcvickers** [comment] 2017-08-21 17:55
@TsengSR I don't think you can do exactly what you want, and I'm finding it a little hard looking at your code and connecting that to your description. I think if you make `protected Module module;` a protected property instead of a protected field, and then reference it in your configuration:
```C#
c.HasOne(typeof(Module), "module")
        .WithMany()
        .HasForeignKey("moduleID");
```
then EF would bind to it.

**Comment by TsengSR** [comment] 2017-08-22 19:56
I know that works, but I hoped there is (or at least would be in future) a way to directly map it, so we could have a cleaner way to design our domain models w/o too much persistence specifics leaking into the domain model and or using event sourcing, even for simpler problem domains.

**Comment by ajcvickers** [comment] 2017-08-23 20:22
Closing as duplicate of #9059

**Closed** 2022-10-16 11:16 UTC
