### ISSUE TITLE
Primary key with converter causes constant migrations

### ISSUE THREAD

**Issue by macias** [dotnet/efcore#31213] opened 2023-07-09 10:07 UTC
## File a bug

Continuation of: https://github.com/dotnet/efcore/issues/13776

### Include your code

Full code: https://codeberg.org/macias/lala/src/branch/master/app/Playground/DbDemo

In short create a table with primary key which is not raw/primitive type, but something "complex" with its converter. For example:

```
public readonly record struct CompanyId(int Id)
{
}

public sealed class Company
{
    public CompanyId Id { get; set; }
    public string Name { get; set; } = null!;
}

        modelBuilder.Entity<Company>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasConversion<int>(wrap => wrap.Id, raw => new CompanyId(raw));
        });

```

With such setup even if there is no change EF migration always create one with such code ("Up" part):

```
            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Companies",
                type: "INTEGER",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "INTEGER")
                .OldAnnotation("Sqlite:Autoincrement", true);

```

### Include verbose output

```
dotnet exec --depsfile /home/mist/Projekty/lala/app/Playground/DbDemo/bin/Debug/net7.0/DbDemo.deps.json --additionalprobingpath /home/mist/.nuget/packages --additionalprobingpath /usr/share/dotnet/sdk/NuGetFallbackFolder --runtimeconfig /home/mist/Projekty/lala/app/Playground/DbDemo/bin/Debug/net7.0/DbDemo.runtimeconfig.json /home/mist/.dotnet/tools/.store/dotnet-ef/7.0.8/dotnet-ef/7.0.8/tools/net6.0/any/tools/netcoreapp2.0/any/ef.dll dbcontext list --assembly /home/mist/Projekty/lala/app/Playground/DbDemo/bin/Debug/net7.0/DbDemo.dll --project /home/mist/Projekty/lala/app/Playground/DbDemo/DbDemo.csproj --startup-assembly /home/mist/Projekty/lala/app/Playground/DbDemo/bin/Debug/net7.0/DbDemo.dll --startup-project /home/mist/Projekty/lala/app/Playground/DbDemo/DbDemo.csproj --project-dir /home/mist/Projekty/lala/app/Playground/DbDemo/ --root-namespace DbDemo --language C# --framework net7.0 --nullable --working-dir /home/mist/Projekty/lala/app/Playground/DbDemo --verbose
Using assembly 'DbDemo'.
Using startup assembly 'DbDemo'.
Using application base '/home/mist/Projekty/lala/app/Playground/DbDemo/bin/Debug/net7.0'.
Using working directory '/home/mist/Projekty/lala/app/Playground/DbDemo'.
Using root namespace 'DbDemo'.
Using project directory '/home/mist/Projekty/lala/app/Playground/DbDemo/'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'DbDemo'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'DemoContext'.
DbDemo.DemoContext
```

### Include provider and version information

EF Core version: 7.0.8
Database provider: Microsoft.Data.Sqlite
Target framework: .NET 7.0
Operating system: openSUSE 15.3
IDE: JetBrains Rider 2023.1.3

**Comment by ajcvickers** [comment] 2023-07-12 19:24
@macias Can you put the code on GitHub or point to some instructions on how to download from "codeberg".

**Comment by macias** [comment] 2023-07-13 15:23
@ajcvickers GitHub is no-go for me because of license violations, but is git OK with you? If yes, simply:

```
git clone https://codeberg.org/macias/lala.git
```

and you will get a solution. This project is "app/Playground)/DbDemo" subdirectory.

**Comment by vslee** [comment] 2023-07-13 17:34
Looks like codeberg has a similar interface to GitHub. So if you go up to the top level of the project (https://codeberg.org/macias/lala), you can click the 3 dots on the top right to download.

**Comment by ajcvickers** [comment] 2023-07-15 14:55
Duplicate of #30699

**Closed** 2023-07-19 18:20 UTC
Labels: closed-duplicate, customer-reported
