### ISSUE TITLE
Consider un-deleting an entity when it has been orphaned and then reparented

### ISSUE THREAD

**Issue by NeVeSpl** [dotnet/efcore#19568] opened 2020-01-11 08:30 UTC
On ef core 3.0, 3.1 and 5.0 after removing child entity from parent aggregate and adding it to another aggregate, child entity disappears from db after SaveChanges.

On ef core 2.2.6 child entity was preserved as expected. 

### Steps to reproduce

``` C#
class Program
{
    static void Main(string[] args)
    {
        var db = new BloggingContext();
        db.Add(new Blog());
        db.Add(new Blog());
        db.SaveChanges();

        db.Blogs.First().Posts.Add(new Post());
        db.SaveChanges();

        var blogs = db.Blogs.ToArray();
        var post = blogs[0].Posts.First();
        blogs[0].Posts.Remove(post);
        blogs[1].Posts.Add(post);

        var entry = db.Entry(post);
        Console.WriteLine(entry.State); // ef 2 -> Modified, ef 3 -> Deleted

        db.SaveChanges();
        blogs = db.Blogs.ToArray();

        Console.WriteLine($"{blogs[0].Posts.Count} {blogs[1].Posts.Count} {db.Posts.Count()}");
        // ef 2 -> 0 1 1, ef 3 -> 0 0 0       
    }
}

public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder options) => options.UseInMemoryDatabase("test");
}

public class Blog
{
    public int BlogId { get; set; }
    public List<Post> Posts { get; } = new List<Post>();
}

public class Post
{
    public int PostId { get; set; }
    public int BlogId { get; set; }
    public Blog Blog { get; set; }
}
```

**Comment by bachratyg** [comment] 2020-01-13 15:21
This looks like it has the same root cause as #17828. See sample repro in https://github.com/dotnet/efcore/issues/17828#issuecomment-532422761

**Comment by ajcvickers** [comment] 2020-01-13 16:22
@bachratyg It's not exactly the same as #17828 because that also involves DetectChanges. I think this case is limited to just the [change to cascade timing](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#cascade-deletions-now-happen-immediately-by-default) and can be fixed by switching back to the 2.x default.

However, I want to discuss with the team, because I think we may be able to do something better here--that is, let the entity go through a deleted phase but then bring it back when it is re-added.

**Comment by NeVeSpl** [comment] 2020-01-13 19:01
Thank you guys, restoring back to `context.ChangeTracker.DeleteOrphansTiming = CascadeTiming.OnSaveChanges;` indeed solves the problem.

Anyway, it would be nice if that could work regardless of that setting. This is kind of most idiomatic way to change of owner in object-oriented manner.

**Comment by DerGary** [comment] 2020-01-17 11:36
Encountered the same issue today. Thanks for the workaround!

**Comment by mgraf1** [comment] 2020-07-15 21:29
I'm running into an issue where we are implementing soft deletes by checking for deleted entities prior to SaveChanges and changing them to modified and setting a DateDeleted property.

When DeleteOrphansTiming is set to OnSaveChanges, it solves the re-parenting problem but does not allow orphans to be soft deleted because those orphans are marked as Modified when the soft-delete check is performed. Then when SaveChanges is called, these orphaned entities just get hard-deleted.

**Closed** 2021-08-19 18:35 UTC
Labels: type-bug, closed-fixed, customer-reported, area-change-tracking

**Comment by soloham** [comment] 2024-05-12 01:07
@ajcvickers @roji  This is still an issue in EF Core 6.0.1 - Is there not a proper solution to this yet? Reparenting is a common need of many apps.
