### ISSUE TITLE
"Specified filter criteria was invalid" on ToDictionary in Select

### ISSUE THREAD

**Issue by NaivE2k4** [dotnet/efcore#20101] opened 2020-02-28 12:16 UTC
Hello!
I am switching from EF Core 2.1 to 3.1 step by step. Now i am doing 2.2 => 3.0.
So far i've managed to get app to build and run and now i'm struggling with some runtime issues.

This piece of code shows one of the issues:
```C#
            var result = _dbContext.Users.Select(user => new MyUser
            {
                //This works
                //RolesTemp = user.UsersToGroups.Select(groups => groups.Usrgrp).Select(g => new MyRole { Id = g.Usrgrpid, Name = g.Name }).ToList(),
                //And this doesn't
                Roles = user.UsersToGroups.Select(groups => groups.Usrgrp).ToDictionary(usrgrp => usrgrp.Name, usrgrp => new MyRole
                {
                    Id = usrgrp.Usrgrpid,
                    Name = usrgrp.Name,
                }),
            });

```
When doing "ToList" on result i've got System.Reflection.InvalidFilterCriteriaException: "Specified filter criteria was invalid."
Fields in MyUser (partially)
```C#
public class MyUser
    {
        public Dictionary<string, MyRole> Roles { get; set; }
        public List<MyRole>  RolesTemp { get; set; }
    }
```

My entities were configured in "fluent style" by DbFirst approach
Here are they, partially
```C#
    public partial class UsersToGroups
    {
        public long Usrgrpid { get; set; }
        public Usrgrp Usrgrp { get; set; }
    }

 public partial class Usrgrp
    {
        public Usrgrp()
        {
            . . .
        }

        public long Usrgrpid { get; set; }
        public string Name { get; set; }
        . . .
     }  

```

I think it might be duplicate of https://github.com/dotnet/efcore/issues/18440
but the error message is different, and i couldn't find it by googling.

### Further technical details

EF Core version: 3.1.2
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL (3.1.2)
Target framework: .NET Core 3.0
Operating system: Win10
IDE: Visual Studio 2019 16.4.5

**Comment by ajcvickers** [comment] 2020-02-28 20:40
Duplicate of #18440
See also #16730

**Comment by ajcvickers** [comment] 2020-02-28 20:42
@smitpatel Is #18440 the correct duplicate? Is that where we should add the note about warning if we client-eval this?

**Closed** 2022-10-16 18:13 UTC
Labels: customer-reported
