### ISSUE TITLE
EF Core v3.1 Translation Fail On GroupJoin

### ISSUE THREAD

**Issue by CompuBoy** [dotnet/efcore#19319] opened 2019-12-14 05:48 UTC
EF Core v3.1 final release throws InvalidOperationException upon executing a simple GroupJoin query between two DbSets.

### Steps to reproduce

Consider a simple DbContext with two entities AssetType and Asset. the following simple query 
fails:

``` C#
var result = from at in dbContext.AssetTypes
                    join a in dbContext.Assets on at.Id equals a.AssetTypeId into ag
                   select new AssetSummaryItem
                   {
                          AssetTypeId = at.Id,
                          AssetTypeName = at.Name,
                          Quantity = ag.Count(),
                   };
```

Throwing the following Exception:

```
Exception has occurred: CLR/System.InvalidOperationException
An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.dll: 'Processing of the LINQ expression 'DbSet<AssetType>
    .GroupJoin(
        outer: DbSet<Asset>, 
        inner: at => at.Id, 
        outerKeySelector: a => a.AssetTypeId, 
        innerKeySelector: (at, ag) => new AssetSummaryItem{ 
            AssetTypeId = at.Id, 
            AssetTypeName = at.Name, 
            Quantity = ag
                .Count() 
        }
    )' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.'


```

### Further technical details

EF Core version: v3.1 
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: VS Code vLatest

**Comment by smitpatel** [comment] 2019-12-14 09:43
Duplicate of #17068

**Closed** 2022-10-16 18:01 UTC
Labels: closed-duplicate, customer-reported
