### ISSUE TITLE
How to use Add-Migration command to just generate current assembly entities migration

### ISSUE THREAD

**Issue by stantoxt** [dotnet/efcore#19303] opened 2019-12-13 08:40 UTC
I have a base project which has it's own migration. Then I create a new project dependent on the base one, when I add migration to this new one, it will generate  all entities in both base project and new project and this  cause duplicated migrations.
What should I do to generate migration for current assembly entity?

**Comment by ajcvickers** [comment] 2019-12-15 21:27
Duplicate of #2725. See that issue for workarounds.

**Closed** 2022-10-16 18:01 UTC
Labels: closed-duplicate, customer-reported
