### ISSUE TITLE
Is there anything like IPostLoadEventListener in Entity Framework Core

### ISSUE THREAD

**Issue by mrtn-t** [dotnet/efcore#16507] opened 2019-07-08 11:44 UTC
I'm moving quite big solution from NHibernate to Entity Framework Core 2.2. Existing solution is using DDD with all BL in Domain models. That business logic is heavily dependent on some objects, which are added to models in custom PostLoadListener, which is registered in Nhibernate Configuration and is triggered each time an Entity is loaded from DB.

I can't find nothing similar in EF. Is there any way in EF to register some custom code (like event handler) which would be triggered every time some entity is read from DB?

**Comment by ajcvickers** [comment] 2019-07-08 16:10
Duplicate of #15911

**Closed** 2022-10-16 14:29 UTC
Labels: customer-reported
