### ISSUE TITLE
[UWP] Could not load assembly

### ISSUE THREAD

**Issue by nicolasparada** [dotnet/efcore#5911] opened 2016-06-30 02:55 UTC
I've created a new UWP and added Ef Core Sqlite with Tools.
First I got this error when I tried to run `Add-Migration InitialMigration`

> Could not load assembly 'MyApp'. Ensure it is referenced by the startup project 'MyApp'.

Then, I though I could made a reproduction repo and create the issue. But it was solved the right moment I created the new solution, added those same dependencies and ran the migration. I just got the [#5471](https://github.com/aspnet/EntityFramework/issues/5471), but, then, it created the migration just fine.

Then I ran `Remove-Migration` and got the same error...

> Could not load assembly 'MyApp'. Ensure it is referenced by the startup project 'MyApp'.

**Details:**
Visual Studio 2015 Update 3

"Microsoft.EntityFrameworkCore.Sqlite": "1.0.0"
"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
"Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0"

**Comment by natemcmaster** [comment] 2016-06-30 19:04
Can you run `Remove-Migration -Verbose` and share additional output? If #5471 worked for `Add-MIgration`, then I'm willing to bet we just need to add additional binding redirects.

**Comment by NicolasParada** [comment] 2016-06-30 21:19
```bash
PM> Remove-Migration -Verbose
Using startup project 'TalkQ'.
Using project 'TalkQ'
Build started...
Build succeeded.
Using application base 'C:\Users\Nicolas\Dev\talk-q\TalkQ\bin\x64\Debug\'.
Using application configuration 'C:\Users\Nicolas\Dev\talk-q\TalkQ\App.config'
Using current directory 'C:\Users\Nicolas\Dev\talk-q\TalkQ\bin\x64\Debug\'.
Microsoft.EntityFrameworkCore.Design.OperationException: Could not load assembly 'TalkQ'. Ensure it is referenced by the startup project 'TalkQ'. ---> System.BadImageFormatException: Could not load file or assembly 'TalkQ' or one of its dependencies. An attempt was made to load a program with an incorrect format.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.EntityFrameworkCore.Design.AssemblyLoader.Load(String assemblyName)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<>c__DisplayClass5_0.<.ctor>b__2()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<>c__DisplayClass5_0.<.ctor>b__2()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<>c__DisplayClass5_0.<.ctor>b__5()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<RemoveMigrationImpl>d__15.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Could not load assembly 'TalkQ'. Ensure it is referenced by the startup project 'TalkQ'.
```

I was reading over the issues here. This one [#1074](https://github.com/aspnet/EntityFramework/issues/1074) and yep, it only fails when I had the solution platform selected on x64. But ran fine if I left it on x86. So... "solved" I think xD

**Comment by natemcmaster** [comment] 2016-06-30 21:26
Ok, thanks for the info. Closing as a duplicate of https://github.com/aspnet/EntityFramework/issues/5839.

**Closed** 2016-06-30 21:26 UTC
Labels: closed-duplicate
