### ISSUE TITLE
How to Remove and Insert Data on Middle Table  together??

### ISSUE THREAD

**Issue by BruceQiu1996** [dotnet/efcore#27023] opened 2021-12-16 09:12 UTC
I have a scenior that i need clear data on table A and Insert new data into A.
table A is a mapper table save relationships betweeen B and C
When i  was delete data on Table A  and Insert on Table A，then Use method DbContext.SaveChanges() , i found that my Table A is empty，data was deleted but not insert.
When  i was delete data on Table A  and use method DbContext.SaveChanges(), then insert data on Table A  and use method DbContext.SaveChanges(),it's worked.
But i wanna SaveChanges()  together to confirm my delete and insert actions are all in one transaction....

**Comment by ajcvickers** [comment] 2021-12-16 12:58
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-01-11 12:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed** 2022-10-16 20:19 UTC
Labels: closed-could-not-reproduce, customer-reported
